### ISSUE TITLE
Problem z sale/product-offers REST API

### ISSUE THREAD

**Issue by ircoo2022** [allegro/allegro-api#6280]
Wysyłam POST na https://api.allegro.pl/sale/product-offers ale mam ciągle :

 string(176) "{"errors":[{"code":"MissedCategoryIdException","message":"Unprocessable Entity","details":null,"path":"","userMessage":"Product category is required. Enter the category ID."}]}" int(422)

Co jest nie tak ???

	
	$headers = array(
            "Authorization: Bearer {$access_token}",
            //"Api-Key: $key",
            "Content-Type: application/vnd.allegro.public.v1+json",
            "Accept: application/vnd.allegro.public.v1+json"
        );
	$params = array();
	$params[0]['productSet']['product']['id'] = "6e184ccc-a620-4556-a312-b97a54758b53";
	$params[0]['productSet']['product']['idType'] = "GTIN";
	
	$params[0]['productSet']['product']['category']['id'] = "89010";
	
	$params[0]['productSet']['product']['parameters'][0]['name'] = "Category";
	$params[0]['productSet']['product']['parameters'][0]['values'] = "89010";
	
	$params['sellingMode']['price']['amount'] = 100;
	$params['sellingMode']['price']['currency'] = 'PLN';
	
	$params['stock']['available'] = 10;
	$params['category']['id'] = '89010';
	
	$ch = curl_init();
    curl_setopt_array($ch, array(
        CURLOPT_URL => 'https://api.allegro.pl/sale/product-offers',
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST => false,
        CURLOPT_POSTFIELDS => json_encode($params)
    ));
    
	 $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
	var_dump($tokenResult);
	var_dump($resultCode);

**Comment by polenquick** [comment]
```$params[0]['productSet']['product']['id'] = "6e184ccc-a620-4556-a312-b97a54758b53";
$params[0]['productSet']['product']['idType'] = "GTIN";```

a to nie jest tak, że odwołujesz się do ID produktu allegro, a szukasz w GTIN czyli EAN/ISBN/UPC
Produkt allegro wygląda na poprawnie utworzony.
Mogę się mylić, więc prosiłbym o poprawę.

**Comment by Lukasz-Zurek** [comment]
@ircoo2022 Dokładnie tak jak sugeruje to **polenquick** - próbujesz wystawić ofertę powiązaną z produktem, który istnieje już w naszym katalogu. Zgodnie z [naszą instrukcją](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem-za-pomoca-zasobu-sale-product-offers) - jeśli wskazujesz ID produktu, pole "idType" pozostaw puste. Nie musisz przekazywać id kategorii. Ta zostanie zaciągnięta z podpinanego do oferty produktu.

**Comment by ircoo2022** [comment]
Jak dałem to:


	
	$headers = array(
            "Authorization: Bearer {$access_token}",
            //"Api-Key: $key",
            "Content-Type: application/vnd.allegro.public.v1+json",
            "Accept: application/vnd.allegro.public.v1+json"
        );
	$params = array();
	//$params['name'] = "Oferta testowa 2710v1";
	$params[0]['productSet']['product']['id'] = "6e184ccc-a620-4556-a312-b97a54758b53";
	//$params[0]['productSet']['product']['idType'] = "ID";
	
	$params[0]['productSet']['product']['category']['id'] = "89010";
	
	//$params[0]['productSet']['product']['parameters'][0]['name'] = "Category";
	//$params[0]['productSet']['product']['parameters'][0]['values'] = "89010";
	
	$params['sellingMode']['price']['amount'] = 100;
	$params['sellingMode']['price']['currency'] = 'PLN';
	
	$params['stock']['available'] = 10;
	//$params['category']['id'] = '89010';
	
	$ch = curl_init();
    curl_setopt_array($ch, array(
        CURLOPT_URL => 'https://api.allegro.pl/sale/product-offers',
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST => false,
        CURLOPT_POSTFIELDS => json_encode($params)
    ));
    
	 $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
	var_dump($tokenResult);
	var_dump($resultCode);
	


to nadal to samo :(

**Comment by Lukasz-Zurek** [comment]
W formacie json wspomniany request powinien ostatecznie wyglądać tak jak poniżej:

```
{
  "productSet": 
        [{
        "product":
            {
            "id": "6e184ccc-a620-4556-a312-b97a54758b53",
            "idType": null,
            "name": "Oferta testowa 2710v1"
            }
        }],
  "sellingMode": {
    "price": {
      "amount": "100", 
      "currency": "PLN"
    }
  },
  "stock": {
    "available": 10
  }
}
```

Z Twojego requestu wynika, że przekazujesz gdzieś dodatkowo identyfikator kategorii. Ze względu na dużą liczbę jezyków programowania, nie świadczymy jednak wsparcia dla każdego z nich. Być może któryś z użytkowników forum miał już wcześniej podobny problem i będzie w stanie pomóc.

**Comment by ircoo2022** [comment]
W php to jest

$params = array();
	$params[0]['productSet']['product']['name'] = "Oferta testowa 2710v1";
	$params[0]['productSet']['product']['id'] = "6e184ccc-a620-4556-a312-b97a54758b53";
	$params['sellingMode']['price']['amount'] = 100;
	$params['sellingMode']['price']['currency'] = 'PLN';
	$params['stock']['available'] = 10;

i json_encode($params);

**Comment by hahyes** [comment]
@ircoo2022 
Nie zakomentowałeś tej linii:
```
$params[0]['productSet']['product']['category']['id'] = "89010";
```

**Comment by ircoo2022** [comment]
Nie ma go już w poprzednim poście jest cała lista parametrów a to cały kod:


	$headers = array(
            "Authorization: Bearer {$access_token}",
            //"Api-Key: $key",
            "Content-Type: application/vnd.allegro.public.v1+json",
            "Accept: application/vnd.allegro.public.v1+json"
        );
	$params = array();
	$params[0]['productSet']['product']['name'] = "Oferta testowa 2710v1";
	$params[0]['productSet']['product']['id'] = "6e184ccc-a620-4556-a312-b97a54758b53";
	//$params[0]['productSet']['product']['idType'] = "ID";
	
	//$params[0]['productSet']['product']['category']['id'] = "89010";
	
	//$params[0]['productSet']['product']['parameters'][0]['name'] = "Category";
	//$params[0]['productSet']['product']['parameters'][0]['values'] = "89010";
	
	$params['sellingMode']['price']['amount'] = 100;
	$params['sellingMode']['price']['currency'] = 'PLN';
	
	$params['stock']['available'] = 10;
	//$params['category']['id'] = '89010';
	
	$ch = curl_init();
    curl_setopt_array($ch, array(
        CURLOPT_URL => 'https://api.allegro.pl/sale/product-offers',
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST => false,
        CURLOPT_POSTFIELDS => json_encode($params)
    ));
    
	 $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

**Comment by PrzemyslawLukanowski** [comment]
@ircoo2022 Z samym kodem PHP, tak jak już wspomniał @Lukasz-Zurek, niestety nie pomożemy, ale czy możesz nam przesłać przykładowe trace-id? Sprawdzimy, w jakiej ostatecznie postaci dane od Ciebie docierają do nas.

**Comment by ircoo2022** [comment]
A jak trace id uzyskać?

**Comment by PrzemyslawLukanowski** [comment]
Trace ID znajdziesz w nagłówkach odpowiedzi, wartość zwracamy dla wszystkich wywołań. Ew. możesz przesłać swój login/id, co pozwoli mi samodzielnie zlokalizować Twoje requesty. Jeśli nie chcesz przekazywać ich w tym wątku, możesz skorzystać z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=6a7ab6d0-2364-4a46-86ff-3aafcca487ab&subjectId=2aad59dd-2c45-422e-8fa7-805492e1e06c) - dopisz wtedy, że dane dotyczą wątku #6280 na GitHub i należy je przekazać zespołowi API.

**Comment by ircoo2022** [comment]
trace-id: cf181e5524d3e9d5 date: Mon, 31 Oct 2022 10:37:11

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję. Dane, które od Ciebie otrzymujemy wyglądają następująco:

```
{
	"0": {
		"productSet": {
			"product": {
				"name": "Oferta testowa 2710v1",
				"id": "6e184ccc-a620-4556-a312-b97a54758b53"
			}
		}
	},
	"sellingMode": {
		"price": {
			"amount": 100,
			"currency": "PLN"
		}
	},
	"stock": {
		"available": 10
	}
}
```

- "productSet" jest niepotrzebnie zawarte w obiekcie o nazwie "0";
- obiekt "product" w "productSet" powinien być dodatkowo zawarty w tablicy.

Musisz dostosować tę strukturę, tak aby wyglądała jak poniżej:

```
{
	"productSet": [{
		"product": {
			"name": "Oferta testowa 2710v1",
			"id": "6e184ccc-a620-4556-a312-b97a54758b53"
		}
	}],
	"sellingMode": {
		"price": {
			"amount": "100",
			"currency": "PLN"
		}
	},
	"stock": {
		"available": 10
	}
}

```

**Comment by ircoo2022** [comment]
OK teraz chyba ok poszło  trace-id: e779d7f479523a6a ?

bo chcą dane do wysyłki chyba więc coś się zmieniło :)
:[{"code":"ShippingRatesNotFoundException","message":"Unprocessable Entity","details":null,"path":"delivery.shippingRates","userMessage":"The user does not have a shipping price list named: default."}]}

**Comment by PrzemyslawLukanowski** [comment]
Tak, teraz jest dobrze :) A aktualny błąd wskazuje, że musisz na swoim koncie dodać cennik dostawy o nazwie "default" lub alternatywnie, wskazać w żądaniu inny, o innej nazwie. Dokładnie to opisaliśmy [w tym punkcie naszego poradnika](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#lokalizacja-i-cenniki).

**Comment by ircoo2022** [comment]
ok dobrze wystawia a jak chciałbym edytować tytuł aukcji i treść to podac muszę pola:

$params['productSet'][0]['product']['name'] = "Inny tytuł niż podpięty";
$params['description']['sections'][0]['items'][1]['content'] = $description_new;

tak ?

**Comment by PrzemyslawLukanowski** [comment]
Nazwy produktu nie możesz zmienić, jeśli chcesz zmienić tytuł oferty, to w takim razie odwołaj się po prostu do "name". Pamiętaj jednak, że tytuł w aktywnej ofercie możesz zmienić tylko wtedy, jeśli nie doszło w niej do żadnego zakupu. 
W przypadku opisu oferty odwołujesz się wyłącznie do drugiego elementu w sekcji "items" i zakładasz, że jest on elementem, który zawiera tekst (a nie zdjęcie). Jeśli przyjmujesz z góry takie założenie, że tak będzie wyglądać schemat opisu, to jest to ok, ale jeśli tekst będzie znajdować się również w innych elementach, to one pozostaną bez zmiany.

**Comment by PrzemyslawLukanowski** [comment]
Jeszcze co do opisu - w zależności oczywiście od tego, co się kryje pod $description_new. Założyłem, że przekazujesz tam tekst opakowany w znaczniki HTML.

**Comment by ircoo2022** [comment]
Tak tekst w html 
a może pan zobaczyć  trace-id: f4912010049ec489 co otrzymaliście?

**Comment by ircoo2022** [comment]
pS> Jak dodam ofertę https://api.allegro.pl/sale/product-offers to zwracane są dane jak tam id oferty wyodrębnić tej nowododanej ? bo ciężko się połapać :) 

 $tokenResult = curl_exec($ch);

 $tokenResult->id nie działa

**Comment by PrzemyslawLukanowski** [comment]
[1] którą przekazujesz w konstrukcji swojego żądania zostaje również wygenerowana w odpowiedzi, co wpływa na nieodpowiednią strukturę. Prócz tego jest ona nie do końca kompletna. Otrzymaliśmy poniższe dane:

```
	"description": {
		"sections": [{
			"items": {
				"1": {
					"content": "<p><b>ORGANIC Mr Gentle u017bel pod prysznic, 250 ml</b></p> <p>u017bel pod prysznic MR GENTLE powstau0142 z myu015blu0105 o wymagaju0105cej sku00f3rze mu0119u017cczyzn. W sku0142adzie znajdziecie au017c 98% sku0142adniku00f3w pochodzenia naturalnego.</p> <p><b>Wu0142au015bciwou015bci ORGANIC Mr Gentle u017bel pod prysznic:</b></p> <ul> <li>o zapachu mocnej kawy idealnie myje</li> <li>pielu0119gnuje i nastraja pozytywnie</li> <li>greenleaf nadaje siu0119 do recyklingu</li> </ul> <p><b>Jak stosowau0107 u017cel pod prysznic ORGANIC Mr Gentle?</b></p> <p>Niewielku0105 ilou015bu0107 u017celu nanieu015b na wilgotnu0105 sku00f3ru0119, delikatnie rozprowadu017a, a nastu0119pnie spu0142ucz wodu0105.</p> <p><b>Sku0142ad ORGANIC Mr Gentle u017bel pod prysznic:</b></p> <p>Aqua,Sodum Coco-Sulfate, Coco-Glucoside, Sodium Chloride, Glycerin, Lauryl Glucoside, Glyceryl Oleate, Aloe Barbadiens Leaf Juice, Hydrogenated Palm Glycerides Citrate, Tocopherol, Sodium Phytate, Citric Acid, Sodium Benzoate, Potassium Sorbate,Parfum</p>"
				}
			}
		}]
	}, 
```

a powinniśmy:

```
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p><b>ORGANIC Mr Gentle u017bel pod prysznic, 250 ml</b></p> <p>u017bel pod prysznic MR GENTLE powstau0142 z myu015blu0105 o wymagaju0105cej sku00f3rze mu0119u017cczyzn. W sku0142adzie znajdziecie au017c 98% sku0142adniku00f3w pochodzenia naturalnego.</p> <p><b>Wu0142au015bciwou015bci ORGANIC Mr Gentle u017bel pod prysznic:</b></p> <ul> <li>o zapachu mocnej kawy idealnie myje</li> <li>pielu0119gnuje i nastraja pozytywnie</li> <li>greenleaf nadaje siu0119 do recyklingu</li> </ul> <p><b>Jak stosowau0107 u017cel pod prysznic ORGANIC Mr Gentle?</b></p> <p>Niewielku0105 ilou015bu0107 u017celu nanieu015b na wilgotnu0105 sku00f3ru0119, delikatnie rozprowadu017a, a nastu0119pnie spu0142ucz wodu0105.</p> <p><b>Sku0142ad ORGANIC Mr Gentle u017bel pod prysznic:</b></p> <p>Aqua,Sodum Coco-Sulfate, Coco-Glucoside, Sodium Chloride, Glycerin, Lauryl Glucoside, Glyceryl Oleate, Aloe Barbadiens Leaf Juice, Hydrogenated Palm Glycerides Citrate, Tocopherol, Sodium Phytate, Citric Acid, Sodium Benzoate, Potassium Sorbate,Parfum</p>"
                    }
                ]
            }
        ]
    }
```

Co do drugiego pytania, to trudno nam coś doradzić, byc może ktoś z pozostałych użytkowników będzie znał odpowiedź. Czy przez tokenResult nie odwołujesz się wylącznie do danych tokena, a nie do odpowiedzi na wysłany request? Być może w tym tkwi problem.

**Comment by ircoo2022** [comment]
ok a trace-id: 682300dd4e35a587 jak wygląda ?

**Comment by PrzemyslawLukanowski** [comment]
```
...
	"description": {
		"sections": [{
			"items": [{
				"content": "OK"
			}]
		}]
	},
...
```

Brakuje zatem "type": "TEXT" obok "content "plus opakowania wartości w "content" w znaczniki HTM (chociaż rozumiem, że to zapewne przykład na potrzeby testu).

**Comment by ircoo2022** [comment]
już działa ok super

tylko tytuł oferty mi się nie podmienił na taki jak chcialem - opis OK

$params['productSet'][0]['product']['name'] to jako tytuł wypełniam 

trace-id: d09fd00b0b52e441 na końcu powinno być (P1) w tytule

**Comment by PrzemyslawLukanowski** [comment]
To dlatego, że próbujesz zmienić tytuł produktu, a nie oferty. Czyli odwołałeś się do productSet->product->name, zamiast do name na najwyższym poziomie, które to jest właśnie tytułem oferty, ale nie produktu.

**Comment by ircoo2022** [comment]
Dzięki - wlasnie sam na to wpadem juz :)))

**Comment by ircoo2022** [comment]
mam jeszzce pytanie czy mozna pobrać info czy produukt jest nowy czy używany oraz czy sprzedawca wystawia fakture vat?

tym zapytaniem chyba nie >?
https://api.allegro.pl/sale/products?phrase='.$model.'&mode=GTIN',

**Comment by PrzemyslawLukanowski** [comment]
GET /sale/products to wyszukiwarka produktów w naszym katalogu, takie informacje nie są tam zawarte. Dane, o których wspominasz można ustawić jako filtry przy wyszukiwaniu ofert w [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing), jednak jest to zasób, do którego dostęp posiadają wyłącznie zweryfikowane aplikacje. Więcej na ten temat znajdziesz [w naszym poradniku](https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk):

> **Jak zweryfikować aplikację?**
> 
> Jeśli jesteś w [Programie Partnerskim](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm) skontaktuj się ze swoim opiekunem. W innym wypadku skontaktuj się z nami przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by ircoo2022** [comment]
Hm a nie można oferty pobrać po ID i tam nie będzie też tych info ?  ( nie przez sale/products ) ale innym

**Comment by PrzemyslawLukanowski** [comment]
Przez [GET /sale/offers/{offerID}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) możesz pobrać takie dane, ale tylko odnośnie Twoich ofert. W przypadku ofert innych użytkowników, którzy nie autoryzowali Twojej aplikacji, nie ma takiej możliwości.

**Comment by ircoo2022** [comment]
Ok a mam pytanie ad. pobierania tokena/ autoryzacja
gdyż obecnie mam po zalogowaniu i przekierowaniu na redirect_uri otrzymuje kod $authorization_code

 $authorization = base64_encode(CLIENT_ID.':'.CLIENT_SECRET);
    $authorization_code = urlencode($authorization_code);
    $headers = array("Authorization: Basic {$authorization}","Content-Type: application/x-www-form-urlencoded");
    $content = "grant_type=authorization_code&code=${authorization_code}&redirect_uri=" . REDIRECT_URI;
    $ch = getCurl($headers, $content);
    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

Czy można zautomatyzować to aby nie trzabyło wpisywać dancyh logowania? czyli żeby skrypt działa w cron a tam skrypt się "nie zaloguje przez formularz"

**Comment by ircoo2022** [comment]
TO chcemy wyrazić zgodę - zgodę gdzie można zaakceptować ? :)

**Comment by PrzemyslawLukanowski** [comment]
Nie zrozumieliśmy się do końca :) Mam na myśli ekran zgody opisany w [3. punkcie poradnika](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#autoryzacja-uzytkownika). Tego kroku nie da się pominąć. Gdy już nastąpi zgoda, możecie korzystać z wyżej wspomnianych refresh tokenów, dzięki czemu użytkownik nie będzie już musiał ponownie logować się do serwisu.

**Comment by PrzemyslawLukanowski** [comment]
Nie posiadam niestety wystarczającej wiedzy na temat crona, ale zerknij proszę [na ten wątek](https://github.com/allegro/allegro-api/issues/5197#issuecomment-983167130). Być może pomoże Ci w uzyskaniu odpowiedzi na pytanie.

**Comment by ircoo2022** [comment]
Ok mam pytanie ad. autoryzacji:


function getAuthorizationCode() {
    $authorization_redirect_url = AUTH_URL . "?response_type=code&client_id=" 
    . CLIENT_ID . "&redirect_uri=" . REDIRECT_URI;
    ?>
    <html>
    <body>
    <a href="<?php echo $authorization_redirect_url; ?>">Login to Allegro</a>
    </body>
    </html>
    <?php
}
 
function main(){
    if ($_GET["code"]) {
        $refreshToken = getRefreshToken($_GET["code"]);
        $nextToken= TokenRefresh($refreshToken);
        echo "access_token = ", $nextToken;
    } else {
        getAuthorizationCode();
    }
}

Taki kod mam w pliku np. start,php a w drugim pliku tym redirect_uri np. index.php mam kod już do api czyli wystawianie ofert itp ale on za kAżdym razem po odświezeniju stromny mnie na nowo autoryzuje,.,.., co jest nie tak ?

czyli zaczynam w start.php -> jest zaloguj do allegro loguje -> przekierowuje do redirect_uri i tam wykonuje kod api a później jak odświeżam index/redirect_uri lub start.php to zmnów jest zaloguj... ? dlaczego?

może ten $_GET['code'] mam zapisac w sesji i uzywac?

**Comment by PrzemyslawLukanowski** [comment]
W tym zakresie niestety nie mogę Ci pomóc. Z uwagi na dużą liczbę języków programowania nie świadczymy wsparcia dla każdego z nich, ale jak już wcześniej wspominaliśmy - być może któryś użytkowników napotkał podobny problem i będzie w stanie pomóc. Ewentualnie możesz także skorzystać z wyszukiwarki i przejrzeć nasze wątki z przeszłości i w nich spróbować znaleźć podpowiedź.

**Comment by ircoo2022** [comment]
Ok nie chodzi o język ale o logikę czy to ma być w 1 pliku autoryzacja czy dwóch??? Kod który pobieramy jest ile ważny? Kod , nie token  
            
          
     
      
       
        Dnia 10 listopada 2022 09:37 PrzemyslawLukanowski ***@***.***&gt; napisał(a):
       
    
       
         
 W tym zakresie niestety nie mogę Ci pomóc. Z uwagi na dużą liczbę języków programowania nie świadczymy wsparcia dla każdego z nich, ale jak już wcześniej wspominaliśmy - być może któryś użytkowników napotkał podobny problem i będzie w stanie pomóc. Ewentualnie możesz także skorzystać z wyszukiwarki i przejrzeć nasze wątki z przeszłości i w nich spróbować znaleźć podpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Zależnie od Twoich preferencji, może to być w jednym pliku, a przy użyciu odpowiednich funkcji możesz korzystać także z dwóch. Kod, który przekazujesz w polu "code", jest ważny 10 sekund.

**Comment by ircoo2022** [comment]
10 sekund no właśnie.   A ten kod jest niezbędny do wygenerowania tokena który z kolei jest potrzebny do edycji ofert itp  Tak ? Mając token z tego kodu (10 sekund) możemy tym tokenem się posługiwać 12 h ?   Pytanie jak w tle skrypt może ponownie odświeżyć token skoro kodu nie ma bo 10 sekund wazny ? 
            
          
     
      
       
        Dnia 10 listopada 2022 11:52 PrzemyslawLukanowski ***@***.***&gt; napisał(a):
       
    
       
         
 Zależnie od Twoich preferencji, może to być w jednym pliku, a przy użyciu odpowiednich funkcji możesz korzystać także z dwóch. Kod, który przekazujesz w polu &#34;code&#34;, jest ważny 10 sekund.

**Comment by PrzemyslawLukanowski** [comment]
10 sekundowy kod jest potrzebny tylko na początku, kiedy jako użytkownik autoryzujesz aplikację. Za pomocą access tokena możesz przez 12 godzin wykonywać operacje w imieniu użytkownika, a przed upływem tego czasu musisz odświeżyć token za pomocą refresh tokena. W przypadku odświeżenia nie potrzebujesz tego 10 sekundowego kodu - przykład znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena).

**Comment by ircoo2022** [comment]
ok dzieki

czy jest mozliwe 'https://api.allegro.pl/sale/product-offers/ID oferty lub inna funkcja?

aktualizowac ceny aukcji/ilosci przekazujac wiecej niz 1 id aukcji? w sensie masowo żeby aktualizować ceny/stany ? a nie tylko jednego id ? chodzi o wydajnosc ??

**Comment by ircoo2022** [comment]
chodzi o szybkość działania - potrzebuje zaktualizowac okolo 20tys oproduktow a każdorazowy request  'https://api.allegro.pl/sale/product-offers/ID oferty  z parametyrami ilosci trwa okolo 2 produkty na sekundę.

Można szybciej ?

**Comment by PrzemyslawLukanowski** [comment]
Za pomocą [PUT /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT) i [PUT /sale/offer-quantity-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/quantityModificationCommandUsingPUT) możesz zmienić cenę i stan aż w 1000 ofertach, jednak w tym przypadku dotyczy to zmiany na tą samą wartość. Prócz tego najwłaściwszym rozwiązaniem pozostaje właśnie [PATCH /sale/product-offers/{id}](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pojedynczej-oferty).

**Comment by ircoo2022** [comment]
ok a jak mam szkic oferty a chcę opublikować to status daje na "active" a "inactive" to szkic tak ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, dokładnie, zaznaczę jeszcze, że nie możesz z powrotem zmienić statusu z "ACTIVE" na "INACTIVE",  a jedynie na "ENDED" (i taka oferta może być ponownie aktywowana).

**Comment by ircoo2022** [comment]
aha czyli z ACTIVE na ENDED można a potem z ENDED na ACTIVE można znów ?

**Comment by PrzemyslawLukanowski** [comment]
Dokladnie tak.

**Comment by ircoo2022** [comment]
Mam pytanie przy wystawianiu oferty mamy dodane:

**Comment by ircoo2022** [comment]
['tax']['exemption'] = "MONEY_EQUIVALENT";

czy można wyzerować ten parametr ? czy jak podczas edycji zostawię puste to bedzie ok ? ew. jakie inne śa dostępne wartości?

**Comment by PrzemyslawLukanowski** [comment]
Aby wyzerować ten parametr musisz dodatkowo usunąć pole tax.id, ponieważ wartość w tax.exemption jest związana z tym konkretnym ustawieniem podatku VAT. Jeśli tego nie zrobisz i zostawisz ID, to automatycznie ponownie przypiszemy wcześniejszą wartość tax.exemption. Po tym, jak wykonasz operację usunięcia obu pól, do oferty przypiszemy nowe tax.id, w którym nie występuje wartość w tax.exemption.
Tak, są dostępne inne wartości w ramach innych ustawień podatku VAT, możesz je przeglądać za pomocą [GET /sale/tax-settings?category.id={category.id}](https://developer.allegro.pl/documentation/#operation/getTaxSettingsForCategory).

**Comment by ircoo2022** [comment]
Ok    Tax id nie ustawiałem chyba ale też wyzeruje i wyślę  
            
          
     
      
       
        Dnia 18 listopada 2022 08:58 PrzemyslawLukanowski ***@***.***&gt; napisał(a):
       
    
       
         
 Aby wyzerować ten parametr musisz dodatkowo usunąć pole tax.id, ponieważ wartość w tax.exemption jest związana z tym konkretnym ustawieniem podatku VAT. Jeśli tego nie zrobisz i zostawisz ID, to automatycznie ponownie przypiszemy wcześniejszą wartość tax.exemption. Po tym, jak wykonasz operację usunięcia obu pól, do oferty przypiszemy nowe tax.id, w którym nie występuje wartość w tax.exemption.  
Tak, są dostępne inne wartości w ramach innych ustawień podatku VAT, możesz je przeglądać za pomocą  developer.allegro.pl GET /sale/tax-settings?category.id={category.id} .

**Comment by ircoo2022** [comment]
$params['tax']['id'] = ""
$params['tax']['rate'] = 23;
						$params['tax']['subject'] = "GOODS";			
						$params['tax']['exemption'] = "";	 //MONEY_EQUIVALENT

Czy tak ?

**Comment by PrzemyslawLukanowski** [comment]
Przy pustych stringach zwrócimy błąd, musisz przekazać null lub w ogóle usunąć te pola.

**Comment by PrzemyslawLukanowski** [comment]
null, bez dodatkowych znaków

**Comment by ircoo2022** [comment]
dzieki

**Comment by ircoo2022** [comment]
a gdy chce dodac zdjecie do akcji poprzez
/sale/product-offers

to 

$params['images'] = "link do zdjecia";

lubn 

$params['images'][0] = "link do zdjecia";

tak ?

**Comment by PrzemyslawLukanowski** [comment]
Zdjęcia muszą być przekazane ostatecznie w takiej postaci:

```
  "images": [
    "https://...link.jpeg",
    "https://...link2.jpeg"
  ]
```

Nie świadczymy wsparcia dla wszystkich języków programowania, dlatego nie mogę udzielic odpowiedzi na powyższe pytanie.

**Comment by ircoo2022** [comment]
pytanie czy pobierajac produkt przez https://api.allegro.pl/sale/products?phrase='.$model.'&mode=GTIN',

moge odczytać info o kategorii z jakiej jest ten produkt i prowizji dla tej kategorii jaką allegro sobie pobiera ?

**Comment by PrzemyslawLukanowski** [comment]
Identyfikator kategorii otrzymasz w polu category.id, jednak jeśli chcesz sprawdzić opłaty, jakie pobieramy, musisz skorzystać z [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST), gdzie w strukturze musisz przekazać przykładowy model oferty. Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-sprawdzic-oplaty-nn9DOL5PASX#kalkulator-oplat).

**Comment by ircoo2022** [comment]
Model oferty? Np. Ean ? Id product ? Czy ?   I ostatnie pytanie   Jak usuwać szkice lub zakończone aukcje ?? Dnia 25 listopada 2022 07:30 PrzemyslawLukanowski ***@***.***&gt; napisał(a):   Identyfikator kategorii otrzymasz w polu category.id, jednak jeśli chcesz sprawdzić opłaty, jakie pobieramy, musisz skorzystać z  developer.allegro.pl POST /pricing/offer-fee-preview , gdzie w strukturze musisz przekazać przykładowy model oferty. Więcej na ten temat znajdziesz w  developer.allegro.pl naszym poradniku .  —  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .  You are receiving this because you were mentioned. Message ID:  &lt;allegro/allegro-api/issues/6280/1327070398 @ github . com&gt;

**Comment by PrzemyslawLukanowski** [comment]
Wszystkie szczegóły, wraz z przykładem, znajdziesz w linkowanym przeze mnie fragmencie poradnika. Model oferty, inaczej struktura, dane, które zwracamy w GET /sale/offers/{offerId}. Szkice usuniesz za pomocą [DELETE /sale/offers/{offerId}](https://developer.allegro.pl/documentation#operation/deleteOfferUsingDELETE), zakończonej oferty nie da się usunąć - jeśli nie aktywujesz jej ponownie w ciągu 60 dni, to przeniesiemy ją do archiwum i w tym momencie nie będzie już widoczna na Twoim koncie i nie będziesz mógł wykonywać w niej żadnych zmian.

**Comment by ircoo2022** [comment]
ok a czy to może być obiekt zwracany z /sale/product-offers ?

**Comment by ircoo2022** [comment]
ok chyhba moza bo zwraca string(279) "{"commissions":[{"name":"Prowizja od sprzedaży","type":"commissionFee","fee":{"amount":"1.11","currency":"PLN"}}],"quotes":[{"name":"Wystawienie przedmiotu","type":"listingFee","fee":{"amount":"0.00","currency":"PLN"},"cycleDuration":"PT240H","classifiedsPackage":{"id":null}}]}" 

 ;)

**Comment by ircoo2022** [comment]
Pytanko jeszcze czy można sprawdzic przez api czy były oferty kupna dla danej aukcji ???

**Comment by PrzemyslawLukanowski** [comment]
Tak, w odpowiedzi [GET /sale/offers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET) znajdziesz pole `stock.sold` przy każdej ofercie (możesz rozwinąć przykładowy response z kodem 200) - widnieje tam informacja o liczbie sprzedanych przedmiotów w ciągu ostatnich 30 dni.
