### ISSUE TITLE
Sandbox padł

### ISSUE THREAD

**Issue by gustawdaniel** [allegro/allegro-api#6282]
![2022-10-28_21-01](https://user-images.githubusercontent.com/16663028/198692489-a5cd06e1-37c5-40a8-b595-18bdb66a2dc5.png)

https://allegro.pl.allegrosandbox.pl/

Ta witryna jest nieosiągalna
Serwer allegro.pl.allegrosandbox.pl potrzebował zbyt wiele czasu na odpowiedź.

---

U was też, czy ja mam coś nie tak z internetem?

---

czy to przez to: https://github.com/allegro/allegro-api/issues/6263 xD?

**Comment by gustawdaniel** [comment]
Już działa.

**Comment by gustawdaniel** [comment]
Znowu nie działa, czy jest na to jakiś monitoring, czy tylko ja mam ten problem.

Wszystkie inne strony działają u mnie dobrze, mam internet.

**Comment by MaciejFrackowiak** [comment]
Nie potwierdzam problemu - Sandbox via WWW funkcjonuje w pełni prawidłowo.

**Comment by gustawdaniel** [comment]
Łączę się z Gruzji, czy to może mieć znaczenie.

Spróbuję przez jakieś proxy.

**Comment by gustawdaniel** [comment]
Przez proxy działa. Nie wiem dlaczego u mnie nie.
