### ISSUE TITLE
POST /sale/product-offers i ewentualne drafty

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#6283]
Chciałbym wrócić do #5940 a dokładniej do mojego pytania i odpowiedzi:

Pytanie było takie:

> czy POST /sale/product-offers jest walidowany synchronicznie? Tzn. czy jeśli dostanę w odpowiedzi 200 OK, 201 Created lub 202 Accepted to mogę założyć, że oferta będzie prędzej czy później opublikowana?

I odpowiedź:

> Tak, walidacja również odbywa się synchronicznie. Musisz jednak zwrócić uwagę na ew. komunikaty w validation, nawet przy kodzie 2xx.

A teraz moja prośba o uściślenie:

Czy to znaczy, że w POST /sale/product-offers też mogę dostać niepustą tablicę validation.errors? Co z kolei prowadzi do faktu, że oferta, a w zasadzie jej draft pozostanie w stanie INACTIVE dopóki nie zrobię edycji na tym drafcie?

Generalnie chciałbym się dowiedzieć czy dla POST /sale/product-offers wciąż muszę pamiętać, żeby nie przekroczyć limitu 20 000 draftów pomimo deklaracji w każdym POST /sale/product-offers o natychmiastowej publikacji.

Dzięki z góry.

**Comment by PrzemyslawLukanowski** [comment]
Nie, taka sytuacja się nie wydarzy. Nie utworzymy draftu oferty, zatem nie musisz mieć na uwadze limitu draftów, ponieważ na wszelkie błędy odpowiemy kodem 422. Przepraszam za nie do końca dokładną odpowiedź we wspomnianym wątku.
