### ISSUE TITLE
Pobieranie załączników oferty

### ISSUE THREAD

**Issue by Oblako1223** [allegro/allegro-api#6284]
Witam, czy jest możliwość pobierania załączników wystawionej oferty? Endpoint dot. pobierania szczegółów oferty zwraca id załącznika, ale z dokumentacji nie wynika, żebym mógł ten załączników pobrać. Jedyna taka możliwość jest w załącznikach dyskusji.

**Comment by PrzemyslawLukanowski** [comment]
Nie da się pobrać załącznika z poziomu oferty. Adres URL do pliku zwracamy wyłącznie na etapie, gdy przesyłasz do nas załącznik. Opisaliśmy to dokładniej [w naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#zalaczniki).
