### ISSUE TITLE
/sale/offers/11581641184 - Nieobsługiwany format żądania

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#6285]
TraceId: dfa71d8b5a1bc5fc

Przy próbie zaktualizowania oferty, API zwraca błąd, który tak na prawdę nic mi nie mówi.

**Comment by PrzemyslawLukanowski** [comment]
Błąd wskazuje na nieprawidłowy format struktury JSON, przez co nie została ona przyjęta przez naszą usługę i nie mogliśmy  odpowiednio przeprowadzić walidacji oferty. Możesz przekazać nam tutaj strukturę, którą wysyłasz (usuń przy tym wrażliwe dane, jak np. token) lub za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). Dopisz wtedy, że dane dotyczą wątku #6285 i należy je przekazać zespołowi API. Zweryfikujemy ten przypadek i wskażemy źródło błędu.
