### ISSUE TITLE
Zestawy produktów - zachowanie API jest inne niż w przypadku ręcznego wystawiania przez formularz

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#6286]
1. Utworzyłem przez formularz ofertę 12814853750. Zaznaczyłem w nim pole "Wystawiam wiele sztuk produktu jako zestaw" i wpisałem, że zestaw dotyczy 10szt.
- W nagłówku pojawiła sie wyraźna informacja, że zestaw dotyczy 10szt
![image](https://user-images.githubusercontent.com/5887720/199294431-96c2079e-47dd-45fc-8434-690e7cccf2c4.png)
- Na liście wyników wyszukiwania widać wyraźnie, że jest to zestaw 10szt
![image](https://user-images.githubusercontent.com/5887720/199294561-368629fa-758d-4344-8774-abaad34105f4.png)
- W parametrach produktu nie ma informacji ilu sztuk dotyczy oferta, ale nie jest to dla mnie problem - wspominam o tym tylko dla porównania 
![image](https://user-images.githubusercontent.com/5887720/199294735-1e838b36-e516-4ec8-b527-86a0041dd579.png)

2. Następnie chciałem powtórzyć ten sam eksperyment przez API, korzystająć z poradnika - https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA i pól productSet.product.id oraz productSet.quantity.value . Przekazywałem je w różnej konfiguracji (raz samo productSet, później i productSet i samo product w tej samej strukturze). Ostatnie TraceId: 70f5bdfac8f99bcf. Efekt zawsze był taki sam:
- brak informacji o wielopaku w nagłówku
- brak informacji o wielopaku w wynikach wyszukiwania
- informacja o ilości sztuk pojawiała się tylko w mało widocznym miejscu w Parametrach.

3. Dla eksperymentu wszedłem w edycję produktu przez formularz. Checkbox z wielopakiem był odznaczony. Zaznaczyłem, wpisałem ilość sztuk - wszystko zaczcęło się poprawnie wyświetlać. Następnie pobrałem dane o ofercie za pomocą GET /sale/offers/{offerId} i porównałem wyniki. Poza różnicami w datach/godzinach, wszystko było identyczne, tak jak gdyby struktura której używa API nie uwzględniała pola "Wystawiam wiele sztuk produktu jako zestaw" z formularza.

Tak więc pytanie:
Czy za pomocą API mogę wystawić oferty składające się z wielu sztuk tego samego produktu w taki sposób, aby informacja ta była widoczna w nagłówku produktu oraz (przede wszystkim) w wynikach wyszukiwania?

**Comment by PrzemyslawLukanowski** [comment]
Odpowiadając na Twoje pytanie - tak, możesz to zrobić w sposób, jaki opisaliśmy [w poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-utworzyc-zestaw-produktowy), przed chwilą dla pewności sam utworzyłem taki zestaw. Pamiętaj, ze zestawy produktowe wspieramy wyłącznie w zasobach /sale/product-offers - w naszych logach nie widzę informacji, aby Twoja oferta została utworzona w ten sposób. Wspomniane trace-id dotyczy operacji PUT /sale/offers/{offerID}. 
Aby wystawić zestaw produktowy, który składa się z wielu sztuk tego samego produktu, musisz skorzystać z POST sale/product-offers i użyć poniższej konstrukcji JSON:

```
{
  "productSet": 
        [{
        "product":
            {
            "id": {productID}
            },
            "quantity": {
                "value": (liczba sztuk w zestawie, w ramach jednego zakupy)
            }
        }],
  "sellingMode": {
    "price": {
      "amount":  {cena},
      "currency": "PLN"
    }
  },
  "stock": {
    "available": {liczba wszystkich sztuk, np. jeśli liczba sztuk w zestawie to 3, a wszystkich przedmiotów posiadasz 6, to odpowiednią wartościa będzie 2 - czyli dostępne są 2 zestawy po 3 sztuki}
  }
}
```
