### ISSUE TITLE
Slow/timeout of uploading image API

### ISSUE THREAD

**Issue by CrazyTaolt** [allegro/allegro-api#6287]
Hi Allegro Developer：
  Recently, we often have a problem during API calls
  **Path**：/sale/images
  **Response**: {"destination":{"host":"api.allegro.pl","originalDst":null,"path":"/sale/images","serviceTag":null},"message":"stream timeout","code":"SI","details":{"connectionId":214332365}}

  After this problem occurs, the upload of images will be very slow, or even **timeout** will occur.

  Hope it can be solved as soon as possible, thank you！

  Best Regards,

  Zero

**Comment by PrzemyslawLukanowski** [comment]
Hi, we will need some examples to verify this issue. Could you please send us a sample link to the image that you are uploading to our servers? It could also be a sample request and response from our API.

**Comment by CrazyTaolt** [comment]
> {"destination":{"host":"api.allegro.pl","o

image url ：https://ae01.alicdn.com/kf/H4f9355b6b887419bbca20971dc262ccbi/E1-3-inteligentny-zegarek-m-czy-ni-1-28-cal-w-pe-ni-dotykowy-ekran-IP68.jpg

**Comment by CrazyTaolt** [comment]
> Hi, we will need some examples to verify this issue. Could you please send us a sample link to the image that you are uploading to our servers? It could also be a sample request and response from our API.

image url ：https://ae01.alicdn.com/kf/H4f9355b6b887419bbca20971dc262ccbi/E1-3-inteligentny-zegarek-m-czy-ni-1-28-cal-w-pe-ni-dotykowy-ekran-IP68.jpg

Our software is a third-party ERP service provider. More than 3000 Allegro sellers use our software to upload products to Allegro. When there are many people uploading products, this exception often occurs. Is our IP address limited?

**Comment by PrzemyslawLukanowski** [comment]
I'm veryfing this case with the team responsible for uploading images services. I will let you know when I have more details.

**Comment by CrazyTaolt** [comment]
> I'm veryfing this case with the team responsible for uploading images services. I will let you know when I have more details.

OK, thank you. I hope it can be resolved as soon as possible

**Comment by PrzemyslawLukanowski** [comment]
I’m back with an answer - we don’t have limits on IP. It looks the server on which images are is not efficient enough. For addresses from the alicdn.com domain our average time for returning proper response is 1s, sometimes even 1.6s, while most servers respond within hundredths of a second. It doesn't look like a problem caused by our services.

**Comment by CrazyTaolt** [comment]
> I’m back with an answer - we don’t have limits on IP. It looks the server on which images are is not efficient enough. For addresses from the alicdn.com domain our average time for returning proper response is 1s, sometimes even 1.6s, while most servers respond within hundredths of a second. It doesn't look like a problem caused by our services.

I would like to ask if your API has a limit on concurrency?

**Comment by CrazyTaolt** [comment]
Not only is the response timeout of the alicdn.com domain name, we will convert the image of the alicdn.com domain name into a file stream to call your API. The following image domain name is allegroimg.com, and this error is also returned when calling the API to upload images. They are images from the same product
images:
https://a.allegroimg.com/original/11d3e6/9369e9474bc9bd3c0beb3619f4de
https://a.allegroimg.com/original/110daf/df2724204c7ea21bdbfa91d7f903
https://a.allegroimg.com/original/11f439/385084664d8ba4ce476dc1832256
https://a.allegroimg.com/original/110e05/ac6b93044486b0555b74999305b3
https://a.allegroimg.com/original/11e0b8/8ea3c3bf4636aa4404a5f02c55c1
https://a.allegroimg.com/original/11729f/95643c3e48fe86d67ed6204764ee
https://a.allegroimg.com/original/1187e3/7273de8948c6a9c4b982329a9adc
https://a.allegroimg.com/original/1148f5/eaf918a1428b9aeb3a8484eb5635
https://a.allegroimg.com/original/112ebf/e31eb6554a17b4d5bfcdf476528c
https://a.allegroimg.com/original/11620a/c558cc134cdbb3f9bc96343bd2dd

**Comment by CrazyTaolt** [comment]
Not only is the response timeout of the alicdn.com domain name, we will convert the image of the alicdn.com domain name into a file stream to call your API. The following image domain name is allegroimg.com, and this error is also returned when calling the API to upload images. They are images from the same product
images:
https://a.allegroimg.com/original/11d3e6/9369e9474bc9bd3c0beb3619f4de
https://a.allegroimg.com/original/110daf/df2724204c7ea21bdbfa91d7f903
https://a.allegroimg.com/original/11f439/385084664d8ba4ce476dc1832256
https://a.allegroimg.com/original/110e05/ac6b93044486b0555b74999305b3
https://a.allegroimg.com/original/11e0b8/8ea3c3bf4636aa4404a5f02c55c1
https://a.allegroimg.com/original/11729f/95643c3e48fe86d67ed6204764ee
https://a.allegroimg.com/original/1187e3/7273de8948c6a9c4b982329a9adc
https://a.allegroimg.com/original/1148f5/eaf918a1428b9aeb3a8484eb5635
https://a.allegroimg.com/original/112ebf/e31eb6554a17b4d5bfcdf476528c
https://a.allegroimg.com/original/11620a/c558cc134cdbb3f9bc96343bd2dd

**Comment by CrazyTaolt** [comment]
Now the image upload API has returned to normal

**Comment by PrzemyslawLukanowski** [comment]
> I would like to ask if your API has a limit on concurrency?

No, we don't have such limit.

> The following image domain name is allegroimg.com, and this error is also returned when calling the API to upload images.

The images on a.allegroimg.com domain are already uploaded to our server, these are the addresses that you receive in the response after successfully upload and they can be used in the offer.

**Comment by CrazyTaolt** [comment]
Hi Allegro Developer：

We found the second exception type.We use file streams to upload images,Every day after 16:00 Beijing time, this anomaly occurs frequently when uploading pictures：
Path：/sale/images
Request：file stream
Response: 
{code:UC,details:{connectionId:345625328},destination:{host:api.allegro.pl,serviceTag:null,originalDst:null,path:/sale/images},message:upstream connect error or disconnect/reset before headers. reset reason: connection termination}

Hope it can be solved as soon as possible, thank you！

Best Regards,

Zero

**Comment by PrzemyslawLukanowski** [comment]
Hi, I'm checking with our team whether this may be caused by our side or if it is still related to a stability issue with the server hosting the images you are trying to upload. I will let you know when I have more details.

**Comment by CrazyTaolt** [comment]
Ok, look forward to your reply
