### ISSUE TITLE
Statusy edycji - oczekiwanie w nieskończoność

### ISSUE THREAD

**Issue by volan1** [allegro/allegro-api#6289]
Witam,
Czy odnotowujecie jakieś problemy ze zwracaniem statusów edycji oferty w API? Niestety ale program zewnętrzny z którego korzystamy my i tysiące użytkowników (EasyUploader) ostatnio pobiera nam w nieskończoność statusy edycji po zakończeniu lub wznowieniu oferty. Co najgorsze - to ma wpływ na kolejne działania ponieważ programy zewnętrzne po API sprawdzają status edycji i potem od tego uzależniają wiele pozostałych działań od tego statusu. Na przykład tworzenie zestawów czy wielowariantowości po wznowieniu oferty. Niestety w ostatnim czasie pogubiliśmy na maxa dużo informacji o naszych ofertach promocyjnych właśnie i nie wrzuciły się one do Allegro z tego względu że na statusy edycji z API Allegro po zakończeniu oferty lub wznowieniu/wystawieniu program czeka w nieskończoność na informację o poprawnym statusie edycji dla danego działania. Na przykład zakończenie oferty po wysłaniu do Was informacji o zakończeniu (czyli kliknięciu w programie Zakończ) kończy po chwili ofertę - ale status zakończenia wisi godzinami jako: "Zakończenie: w trakcie". Ta asynchroniczność działań (czyli to że nie API nie zwraca od razu odpowiedzi tylko kolejkuje) jest dobijająca i blokująca wszelkie pozostałe działania. Sporo użytkowników na forum na to narzeka - u nas ten problem teraz już jest na maxa widoczny. Nie uśmiecha nam się czekanie godzinami na informację zwrotną z API Allegro niestety.

**Comment by PrzemyslawLukanowski** [comment]
Konsultuję ten temat z odpowiednim zespołem. Wrócę z odpowiedzią, gdy uda mi się ustalić więcej szczegółów.

**Comment by PrzemyslawLukanowski** [comment]
W jakich dniach ten problem się nasilił? Czy nadał występuje?

**Comment by PrzemyslawLukanowski** [comment]
Prosiłbym również o podanie przykładowych commandID, które dotyczyły zadań, gdzie długo nie odpowiadaliśmy, jaki jest wynik operacji.
