### ISSUE TITLE
Klucze WebApi RestApi

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#629]
Takie pytanie. Mam zintegrowaną z Allegro aplikację desktopową działającą w oparciu o WebApi. Loguję się za pomocą starego 8 znakowego klucza WebApi. Wszystko działa poprawnie.
Równocześnie rozmawiam z zewnętrzną firmą w sprawie integracji mojego konta Allegro z ich oprogramowaniem. Czy jesli zewnętrzna aplikacja wygeneruje klucz RestAPI, by móc łączyć się z Allegro to działający dotychczas klucz WebAPI wciąż będzie aktywny?
Rozumiem, że do konta Allegro przypisanych może być wiele kluczy, każdy do innego adresu strony?

**Comment by TomekKaczmarek** [comment]
Klucz powinna generować aplikacja, a nie użytkownik. Także to w aplikacji powinien być zapisany klucz, a Ty jako użytkownik nie powinieneś podawać klucza API, tylko przejść proces logowania danymi allegro.

**Comment by lukada4100** [comment]
Świetnie. Wciąż jednak nie wiem czy jeśli aplikacja wygeneruje klucz RestAPI to czy zapisany w aplikacji desktopowej klucz WebAPI (dzięki któremu otrzymuje sessionHandle) wciąż będzie aktywny i będzie można korzystać z niego w ten sam sposób co do tej pory.

**Comment by TomekKaczmarek** [comment]
Jeśli aplikacja nadal będzie przechowywać stary klucz WebAPI i nadal będzie on aktywny, to powinna działać tak jak do tej pory. Wiele jednak zależy od tego, jak aplikacja obsługuje klucze.

**Comment by lukada4100** [comment]
Piszesz "jeśli ... nadal będzie on aktywny". A ja właśnie o to pytam. Czy będzie aktywny.
Po kolei:
- czy z kontem Allegro można łączyć się korzystając równocześnie z klucza WebApi i RestApi?
- czy wygenerowanie jednego klucza nie wpływa na funkcjonowanie wygenerowanych wcześniej kluczy?
- w jaki sposób klucz WebApi może się zdezaktalizować? (W panelu Allegro nie ma już przecież możliwości jego ponownego wygenerowania)

**Comment by TomekKaczmarek** [comment]
Odpowiadając na Twoje pytania:

1. czy z kontem Allegro można łączyć się korzystając równocześnie z klucza WebApi i RestApi? 
Tak
2. czy wygenerowanie jednego klucza nie wpływa na funkcjonowanie wygenerowanych wcześniej kluczy?
Po stronie Allegro nie.
3. w jaki sposób klucz WebApi może się zdezaktalizować? (W panelu Allegro nie ma już przecież możliwości jego ponownego wygenerowania)
Klucz może zostać zablokowany, jeśli jego właściciel naruszy regulamin Allegro lub regulamin API Allegro.

**Comment by lukada4100** [comment]
Ok. Dzięki.
