### ISSUE TITLE
Product [...] is not included in the contract, problem z nadaniem paczek

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#6290]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dzień dobry,

nieoczekiwanie Poczta Polska bez większego ostrzeżenia wyłączyła stare metody dostaw odpowiedzialne za kuriera i dostawę do punktów. Pytanie: co mam zrobić z zamówieniami, które mają wybrane niemożliwe do realizacji metody dostawy? Czy mogę w tym przypadku wybrać nowe metody dostawy?

Komunikat od (zapewne) API Poczty Polskiej (otrzymany oczywiście z WzA):
![image](https://user-images.githubusercontent.com/37104952/199460069-ede5608a-2a80-4511-94b9-d0f0f0dd1ae2.png)

**Comment by PrzemyslawLukanowski** [comment]
Skonsultowałem ten temat z zespołem odpowiedzialnym za usługę WzA - z naszej stronie nie możemy nic zrobić, musisz nadać przesyłkę na umowie własnej, nie mamy wpływu jednak na to, jak działa Twoja umowa. Według naszej wiedzy Poczta Polska wyłącza te usługi stopniowo - w każdym razie, to jest poza nami, musisz wyjaśnić to z PP. W WzA nie można przełączyć metod Pocztex Kurier 48 na metody Pocztex 2.0.

**Comment by PrzemyslawLukanowski** [comment]
Nasz zespół skonsultował się dodatkowo z Pocztą Polską. Możliwe są dwa rozwiązania. W obu przypadkach możliwe będzie utworzenie usługi / przesyłki w Elektronicznym Nadawcy, zgodnie z katalogiem usług dostępnych w umowie w chwili tworzenia przesyłek:
- ręczna rejestracja przesyłki w systemie Elektroniczny Nadawca. WAŻNE: w polu "Email" w danych przesyłki musi być podany alias/maskowany adres email przypisany do zamówienia w Allegro,
- wykorzystanie do tworzenia przesyłek funkcjonalności EN "Import --> z zamówień pobranych przez API Allegro".

Natomiast co do "Poczta Polska niespodziewanie wyłączyła im usługi Pocztex Kurier 48" - nie jest to kwestia niespodziewana, wyłączenie usługi nastąpiło zgodnie z zapisami zawartej umowy/aneksu.
W umowach usługa Pocztex Kurier 48 została zastąpiona usługą Pocztex 2.0.

**Comment by hahyes** [comment]
@PrzemyslawLukanowski Dziękuję za odpowiedź. Nie posiadam dostępu do umów klientów ani nie otrzymałem od nich żadnych informacji na ten temat, więc przepraszam za może pretensjonalny ton wypowiedzi. Nie wiem, czy PP wysyłała jakieś przypomnienia do swoich klientów. Wygląda to na problem po naszej stronie. W każdym razie dziękuję jeszcze raz za podpowiedzi, mam nadzieję że się przydadzą.

Ah, na forum Allegro Gadane ludzie przytaczają, jakoby PP miało przesunąć wyłączenie tych metod dostawy do 31 grudnia. Teraz to ja już nic nie wiem. No nic, pozdrawiam.
