### ISSUE TITLE
Czy jest możliwość pobrania danych o ofertach z konkretnej produktyzacji ?

### ISSUE THREAD

**Issue by Kamill1987** [allegro/allegro-api#6291]
Witam,

Przeglądając API na szybko, nie odnalazłem funkcji za pomocą której mógłbym pobrać listę ofert przypisanych do konkretnego produktu z produktyzacji, np. https://allegro.pl/produkt/odkurzacz-workowy-zelmer-zvc316bb-adas-178153b1-1d12-461e-8b34-8bc5b7329a7d

Chciałbym pobrać listę ofert z tytułem, numerem oferty i ceną czy jest to do wykonania z użyciem REST API ?

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale nie udostępniamy takiej funkcjonalności.

**Comment by Kamill1987** [comment]
> 

Ok, rozumiem. Prosiłbym jeszcze o informację jakie są limity wywołań ofert allegro zanim pojawi się prośba o weryfikację CAPTCHA? Jak to wygląda pod względem czasowym i ilości wywołań.

**Comment by PrzemyslawLukanowski** [comment]
Informację znajdziesz [w naszym FAQ](https://developer.allegro.pl/faq#jakie-sa-ograniczenia-liczby-sesji-i-zapytan-w-allegro-api-):

> W usłudze Allegro REST API (produkcyjnej oraz testowej) obowiązuje główny limit nakładany na Client ID (lub Sofware Statement ID w przypadku [DCR](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#dynamic-client-registration)) - 9000 zapytań na minutę.
> 
> Gdy przekroczysz limit:
> 
>  - na minutę zablokujemy twój Client ID,
>  - zwrócimy odpowiedź ze statusem: 429 Too Many Requests.
> Po tym czasie automatycznie przywrócimy dostęp do usługi dla twojego Client ID.
