### ISSUE TITLE
Przeniesienie produktów z Allegro i przeszkody w związku z katalogiem produktów.

### ISSUE THREAD

**Issue by 1329130156** [allegro/allegro-api#6292]
Dzień dobry.
Jestem w trakcie tworzenia sklepu internetowego, gdzie istnieje możliwość połączenia poprzez Allegro Api. W momencie przenoszenia produktów napotykam na problem: przenoszą się jedynie główne produkty z katalogu produktów-16 ofert, a podpięte pod nie przeszło 200 ofert nie jest w ogóle widoczna. Zarówno na platformie sklepu jak i Allegro nie wiedzą co z tym zrobić (nie ma możliwości odpinania ofert od katalogu).Czy ma ktoś może pomysł co z tym fantem zrobić?

**Comment by Lukasz-Zurek** [comment]
Nie wiem jak działa wspomniana aplikacja/oprogramowanie sklepu internetowego, w związku z czym trudno mi się odnieść do problemów, które opisujesz. Jeżeli platforma sklepu, z której korzystasz - ma konkretne problemy z integracją - powinna skontaktować się z nami, przekazując szczegółowe informacje, request i response oraz trace-id - za pośrednictwem naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu należy dopisać GitHub #6292.
