### ISSUE TITLE
Pobieranie wielu etykiet w Get parcel label

### ISSUE THREAD

**Issue by vendoremo** [allegro/allegro-api#6293]
:bulb: **Sugestia / Suggestions**

Niedawno w zakładce Moje Allegro -> Sprzedaż -> Obsługa zamówień -> Zamówione przesyłki pojawiła się możliwość pobrania wielu etykiety w formacie A6, połączonych po 4 szt. na stronę A4 i do jednego pliku PDF.

Czy planowane są zmiany, aby tego typu funkcja była dostępna także w API?

**Comment by Lukasz-Zurek** [comment]
Nie mamy tego jeszcze w planach aczkolwiek sam pomysł ma jak najbardziej rację bytu. Otrzymaliśmy już [podobną sugestię na Github Discussions](https://github.com/allegro/allegro-api/discussions/5027). Tam możesz oddać również swój głos.
