### ISSUE TITLE
Problem z dodaniem aukcji za posrednictwem modulu od x13

### ISSUE THREAD

**Issue by jmb-group** [allegro/allegro-api#6298]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Podczas próby dodania aukcji z prestashop za pośrednictwem modułu od x13 wyskakuje błąd:
Niepoprawne ustawienia aukcji: 1
Popraw występujące błędy i kliknij przycisk "Wystaw aukcje" ponownie.
Nazwa produktu: Wystapiły nastepujące błędy:

X13Allegro API: Nie można pobrać zdjęcia z adresu 'link do zdjęcia'. Serwer ze zdjęciem zwrócił kod HTTP: 500 INTERNAL_SERVER_ERROR z błędem: 'Internal server error'. (REST_API: 422) - link do zdjęcia
X13Allegro API: Nie można pobrać zdjęcia z adresu 'link do zdjęcia'. Serwer ze zdjęciem zwrócił kod HTTP: 500 INTERNAL_SERVER_ERROR z błędem: 'Internal server error'. (REST_API: 422) - link do zdjęcia 
X13Allegro API: Nie można pobrać zdjęcia z adresu 'link do zdjęcia'. Serwer ze zdjęciem zwrócił kod HTTP: 500 INTERNAL_SERVER_ERROR z błędem: 'Internal server error'. (REST_API: 422) - link do zdjęcia 
X13Allegro API: Nie można pobrać zdjęcia z adresu 'Link do zdjęcia'. Serwer ze zdjęciem zwrócił kod HTTP: 500 INTERNAL_SERVER_ERROR z błędem: 'Internal server error'. (REST_API: 422) - Link do zdjęcia

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, udało nam się już namierzyć źródło problemu i będziemy przygotowywać poprawkę. Wrócę z informacją, kiedy wdrożymy ją na nasze środowiska.
