### ISSUE TITLE
Sekcja pasuje do - edycja  

### ISSUE THREAD

**Issue by szymoki** [allegro/allegro-api#6299]
Witam, mam pytanie odnoścnie sekcji Pasuje Do
Mam produkt  https://allegro.pl/moje-allegro/sprzedaz/zglos-blad-w-produkcie/48e9ed9e-b4fe-4afb-bab3-da51269a8f0c który nie ma możliwości edycji sekcji pasuje do, jednak gdy przez Api chcę wysłać własne pasujące auta to dostaję komunikat _Given compatibility table is not valid for this product, use product compatibility table. Update offer with the most recent product data._ Jednak klient upiera się że do tego produktu akurat pasuje więcej niż jedno auto które jest wybrane domyślnie. Jaka jest możliwość aktualizacji tej listy?

**Comment by PrzemyslawLukanowski** [comment]
Klient może przekazać w takim przypadku swoją sugestię za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Zgłoszenie trafi do odpowiedniego zespołu, który je zweryfikuje i w razie akceptacji doda dodatkowe modele do sekcji Pasuje Do.
