### ISSUE TITLE
Brak opisu przedmiotu w metodzie doGetItemsInfo

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#63]
Metoda doGetItemsInfo przestała zwracać wartość itemInfo.itDescription w przypadku, kiedy oferta nie korzysta z nowego opisu. Prowadzi to do sytuacji, w której dla ofert ze starym opisem nie można przez API pobrać żadnego opisu przedmiotu.

**Comment by DINK74** [comment]
To nieprawda - przed chwilą sprawdzałem starą aukcję i wszystko jest ok. Zaznaczyłeś żeby pobierał opis?

**Comment by TimothyKoval** [comment]
Dobra, inaczej. Do niedawna, jeżeli nie było nowego opisu, dla itStandardizedDescription zwracany był string "NULL" (najjaśniejszy raczy wiedzieć czemu). Teraz, bez jakiejkolwiek zapowiedzi (zgodnie z moją wiedzą) zwracany jest pusty string.

Standardowo - gromkie brawa dla "programistów"...

**Comment by DINK74** [comment]
Szczerze mówiąc nie bardzo widzę logiczne połączenie między pierwszym postem a ostatnim.
O tym "NULL" wydaje mi się, że coś czytałem - teraz to poprawili - to chyba dobrze?
