### ISSUE TITLE
Ładowanie plików z towarem (XML,CSV,JSON)

### ISSUE THREAD

**Issue by tadeuskozlovski** [allegro/allegro-api#630]
Czy Allegro posiada interfeis bezpośredniego zaladowania pliku towarów do systemu?(XML,CSV,JSON)

**Comment by TomekKaczmarek** [comment]
Nie, nie planujemy też tego rodzaju funkcjonalności w najbliższym czasie.

**Comment by tadeuskozlovski** [comment]
Szkoda. Dziękuję.
