### ISSUE TITLE
Is everything is ok with publishing listing drafts?

### ISSUE THREAD

**Issue by antalos** [allegro/allegro-api#6301]
Hi.

We're creating listings through API by using `/sale/product-offers` endpoint. Today we're observing that some listings have been published successfully as drafts but those drafts had not been published.

Example of such listings (createdAt, listingId, operationId):
- 2022-11-03 13:47:57, 12822443647, cdd750d9-101d-4182-a08b-e02adea94434
- 2022-11-03 13:46:10, 12822438210, 24470a7c-8997-4bf7-bbb1-2af539bc9ccd
- 2022-11-03 13:45:37, 12822436634, cb9e5575-a503-4405-9abb-9a69d9a7ad48
- 2022-11-03 13:18:42, 12822342200, 7d1d1cc9-beaa-4090-9870-2b275ff301c0
- 2022-11-03 13:09:59, 12822314604, 74966ed3-fcd6-4f60-b58d-81c1f0afc8ef
- 2022-11-03 13:05:45, 12822301365, c3b45a2b-cdf0-441b-b87b-55a4778717b2

Can you please check if everything is ok on your side?

Thanks.

**Comment by Lukasz-Zurek** [comment]
I have verified these cases and still I don't see any errors. Did you try to check the statuses? Can you provide some trace-ids?

**Comment by antalos** [comment]
JobId: 74966ed3-fcd6-4f60-b58d-81c1f0afc8ef
Started At: 2022-11-03T11:10:24.713Z

So this job is being stuck for 2 hours already.

Request of its status with trace id:
```
13:20:45 DEBUG     [http_client] >>>>>>>> REQUEST:\nGET /sale/product-offers/12822314604/operations/74966ed3-fcd6-4f60-b58d-81c1f0afc8ef HTTP/1.1
User-Agent: GuzzleHttp/7
Host: api.allegro.pl
Content-Type: application/vnd.allegro.public.v1+json
Accept: application/vnd.allegro.public.v1+json

13:20:45 DEBUG     [http_client] <<<<<<<< RESPONSE:\nHTTP/1.1 202 Accepted
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
retry-after: 5
x-xss-protection: 1; mode=block
pragma: no-cache
location: https://api.allegro.pl:443/sale/product-offers/12822314604/operations/74966ed3-fcd6-4f60-b58d-81c1f0afc8ef
date: Thu, 03 Nov 2022 11:20:45 GMT
strict-transport-security: max-age=31536000 ; includeSubDomains
x-frame-options: DENY
trace-id: a004c97c1bbacd1d
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json
content-length: 150

{"offer":{"id":"12822314604"},"operation":{"id":"74966ed3-fcd6-4f60-b58d-81c1f0afc8ef","status":"IN_PROGRESS","startedAt":"2022-11-03T11:10:24.713Z"}}
```

**Comment by Lukasz-Zurek** [comment]
Ok, thank you, we will check it out closely. Please be patient.

**Comment by anatolijphp** [comment]
@Lukasz-Zurek Having the same issue. Some of the offers are listed in few minutes, but for some it take whole day to be published. Is there any information on workaround this issue?

**Comment by Lukasz-Zurek** [comment]
@anatolijphp @antalos I would like to apologize for this inconvenience. I can confirm that we have some delays and we are still working on it.

**Comment by antalos** [comment]
The problem is still in place, do you have any updates on it?

**Comment by Lukasz-Zurek** [comment]
@antalos We're really sorry for this inconvenience. We have some big lags/delays in offer listing and we are still working on it. I will let you know when the problem will be fixed.

**Comment by glinkaa** [comment]
@Lukasz-Zurek Czy problem został już rozwiązany?

**Comment by Lukasz-Zurek** [comment]
Problem został już rozwiązany. Lag zszedł natomiast oferty powinny zmieniać status o czasie.

Raz jeszcze przepraszamy za te utrudnienia.

---

The problem has been resolved. The lag has gone down and the offers should change status on time.

We apologize again for these inconveniences.
