### ISSUE TITLE
Problem z działeniem API produkcyjnym

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6302]
Czy występują jakieś problemy z działaniem API produkcyjnego? Od dłuższego czasu mamy problemy ze wznawianiem, wystawianiem oraz zakańczaniem ofert. Ponisze pozycje od dłuższgo czasu znajdują się w statusie IN PROGRESS (niestety nie mam trace-id) - /sale/product-offers/{ID OFERTY}/operations/:

{"offer":{"id":"11481175874"},"operation":{"id":"86371f38-58e8-4fe4-87f3-4bd1793999b7","status":"IN_PROGRESS","startedAt":"2022-11-03T11:25:56.624Z"}}
{"offer":{"id":"12822366812"},"operation":{"id":"5e1462a2-6a2d-45a1-81f1-e08694c57428","status":"IN_PROGRESS","startedAt":"2022-11-03T11:25:58.414Z"}}
{"offer":{"id":"12822718601"},"operation":{"id":"eab27d8c-49b1-4fce-bacc-d32d9385e2a7","status":"IN_PROGRESS","startedAt":"2022-11-03T12:57:23.013Z"}}

**Comment by Lukasz-Zurek** [comment]
Problem ten przekazałem dalej do weryfikacji. Wkrótce wrócę z informacją.

**Comment by podniesm** [comment]
Ten sam problem. Publikacja ofert utyka w statusie NEW (/sale/offer-publication-commands/{commandId}/tasks).

Przykładowe commandId:
47c68170-9bf5-463e-9100-f9f52e42da3c
d8e9539a-186a-4318-bc66-e3ea3b047ae3
7241d7f8-f32b-404f-9b88-2232683557a4
6e727011-1ba9-44d8-992a-dcd9418fdd0c
5c728603-bdfd-412b-b3fc-63a1319bce39
f5666b22-e45d-4ecd-8ea8-b1154aac542d
9a3d63b2-6778-45bf-bf25-0ac9d50da952
3ce8eac6-1a4d-41c5-9a4a-e48f910facc9
75f79b54-a938-4ace-a242-1d814ef65361
9b57092f-a6d0-4d13-898c-08f76085c3b6
df0efd59-0d7c-4901-88d3-4c2f3209ec12
3c3a6040-beca-4444-8a1f-9d8ff8cbeed1
df2fd9d3-6a33-4963-99d7-85c666e4bb1c
b25f6ef1-9915-4682-b3ef-ed798c188439
7b2117c8-0559-477c-91f7-69099eed5e3b
a1756d2a-8517-4ce1-b4f2-5f11f8d1d6de
03ba90af-d7c0-4e20-bb2e-f48098e1e8ba
76b8a437-b972-4323-8810-be7f1388527f
ce63e60b-8078-4d73-afaa-08d6a6fa79a9

**Comment by glinkaa** [comment]
Również mam ten sam problem, cześć ofert się wystawia, a część cały czas jest w statusie "NEW" (/sale/offer-publication-commands/{commandId}/tasks).

**Comment by Lukasz-Zurek** [comment]
@podniesm @glinkaa Weryfikujemy problem.

**Comment by antalos** [comment]
The problem is still in place, do you have any updates on it?

**Comment by Lukasz-Zurek** [comment]
@antalos I wrote you back [here](https://github.com/allegro/allegro-api/issues/6301#issuecomment-1305230837). So still - work in progress.

**Comment by Lukasz-Zurek** [comment]
Problem został już rozwiązany. Lag zszedł, natomiast oferty powinny zmieniać status o czasie.

Raz jeszcze przepraszamy za te utrudnienia.

---

The problem has been resolved. The lag has gone down and the offers should change status on time.

We apologize again for these inconveniences.
