### ISSUE TITLE
Parametr 223541 i Bad request

### ISSUE THREAD

**Issue by kl-innosoft** [allegro/allegro-api#6303]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dlaczego od jakiegoś czasu informacje zwrotne dotyczące parametru 223541 są zwracane w formie 'gołych błędów'; o stastusie odpowiedzi 400 Bad request? Poniżej przykładowe odpowiedzi:
```
{"errors":[{"code":"BAD_REQUEST","message":"Parameter not found: parameterId=223541, categoryId=26159","details":null,"path":"","userMessage":"Unable to extend dictionary, because parameter does not appear in the category"}]}
```
```
{"errors":[{"code":"BAD_REQUEST","message":"Incorrect value of the Publishing house (223541) parameter for the offered product. The correct parameter value for the product is: 'Szkoła Główna Handlowa w Warszawie'","details":null,"path":"","userMessage":"Value already exists: value='Szkoła Główna Handlowa w Warszawie', parameter.id='223541'"}]}
```
Do tej pory były zwracane w kluczu `validation.errors` z pełnymi danymi oferty, czy to jakiś błąd po Waszej stronie?

**Comment by PrzemyslawLukanowski** [comment]
Dziękuje za zgłoszenie. Weryfikujemy ten temat, wrócę z odpowiedzią, gdy uda nam się ustalić więcej szczegółów.

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam za spóźnioną odpowiedź. Sytuacja, kiedy wystąpi status 400 zamiast 200, nastąpi wtedy, gdy w strukturze parametrów przekażesz parametr, który nie istnieje w danej kategorii i **dodatkowo** uwzględnisz w nim także własną wartość w polu `"values"` dla wartości niejednoznacznej. Będziemy poprawiać takie przypadki, aby dla nich również tworzyć draft z odpowiednim komunikatem błędu w `validation.errors`.

**Comment by kl-innosoft** [comment]
@PrzemyslawLukanowski dziękuję za informację, tak Twoj opis pokyrwa się z przypadkami, w których mieliśmy te błędy. Czy dostanę informacje gdy zmiany zostaną wdrożone na proda?

**Comment by PrzemyslawLukanowski** [comment]
Tak, wrócę z informacją z tym wątku, gdy uda się zespołowi odpowiedzialnemu za usługę naprawić przypadki tego typu.

**Comment by kl-innosoft** [comment]
@PrzemyslawLukanowski dorzucam przypadek, w którym również zwracana jest 400 z błędem dla parametru 223541, który jest wymagany w danej kategorii. Dodatkowo zwraca komunikat, że wartość "Inne" istnieje w słowniku. Identyfikator kategorii: `79157`.
Błąd:
```
{"errors":[{"code":"BAD_REQUEST","message":"Value already exists: value='inne', parameter.id='223541'","details":null,"path":"","userMessage":"Value 'inne' already exists in parameter 'Wydawnictwo'"}]}
```

Parametry przesłane dla powyższego przypadku:
```
[{"id":"245669","values":["837124018x"]},{"id":"223545","values":["Modliszka"]},{"id":"223489","values":["Marek Kdzierski"]},{"id":"75","valuesIds":["75_306417"]},{"id":"74","values":["1995"]},{"id":"223541","valuesIds":["223541_305725"],"values":["Inne"]},{"id":"11323","valuesIds":["11323_2"]},{"id":"223493","values":[63]},{"id":"223333","values":[15]},{"id":"223329","values":[21.5]}]
```

Identyfikator draftu, który utworzono wczesniej, ale bez wartości w 'values' dla parametru 223541: `12868774468`

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za przykład, również przekazałem do zespołu. Sam komunikat natomiast jest prawidłowy, ponieważ wartość "inne" występuje na samym końcu dostępnych wartości:

```
                {
                    "id": "223541_305725",
                    "value": "inne",
                    "dependsOnValueIds": []
                }
```

Identyfikator niejednoznacznej wartości zwrócimy w polu options.ambiguousValueId przy danym parametrze.

**Comment by kl-innosoft** [comment]
@PrzemyslawLukanowski 
zgadza się, natomiast pomimo ustawienia parametru `223541` z identyfikatorem zawartym w `ambiguousValueId`
```
{
   "id":"223541",
   "valuesIds":[
      "223541_305725"
   ]
}
```
API wymaga, aby podać stringa w values z nazwą tego 'innego' wydawnictwa
```
[{"code":"EmptyCustomValueOnAmbiguousValueException","message":"Wydawnictwo","details":null,"path":null,"userMessage":"Nie zosta\u0142a podana propozycja warto\u015bci do warto\u015bci niejednoznacznej w parametrze Wydawnictwo"}]
```

Niektóre produkty nie posiadają takiej cechy, wtedy zataczamy błędne koło

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, w takim przypadku należy podać właściwą nazwę wydawnictwa, nie może tutaj być powielona wartość "inne".
