### ISSUE TITLE
The provided parameter `Wysokość` value `1.00` does not match the existing parameter value `1`.

### ISSUE THREAD

**Issue by bingnew** [allegro/allegro-api#6305]
Dear allegro api team, we have recently uploaded products a large number of such errors(The provided parameter `Wysokość` value `1.00` does not match the existing parameter value `1`.), please see what is the reason and how to solve it?
Example: store name TOOYFUL, external.id: 19760192

**Comment by PrzemyslawLukanowski** [comment]
Based on provided data we have found an existing product in our catalog (I assume it was created by your account), but the parameter value for "Wysokość" in your request differs from the value in our catalog. You should try to change this value to "1" or 1.
