### ISSUE TITLE
Brak produktu w bazie Allegro.

### ISSUE THREAD

**Issue by KrzychuWalek** [allegro/allegro-api#6306]
Klient ma możliwość dodawania nowego produktu za pomocą panelu na stronie Allegro. Jest to konto producenta.

[https://static.investmag.pl/kw/16675648532743517065.jpg](url)

Jaka jest możliwość wykonania tej czynności w REST API. 

Pozdrawiam, Krzysztof Wałek

**Comment by Lukasz-Zurek** [comment]
W naszym API masz dwie możliwości:

1. Tworzysz produkt za pomocą [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct). Przesłane dane weryfikujemy, a zaakceptowane przez nas dane produktu zostaną zapisane w katalogu produktów. Identyfikator takiego produktu możesz wykorzystać do wystawienia oferty w Serwisie - zarówno za pomocą [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) (zalecane rozwiązanie), jak i np. [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT) (który jednak wkrótce przestanie być przez nas wspierany).
2. Za pomocą wspomnianego [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) przy użyciu jednego żądania możesz wystawić ofertę powiązaną z produktem, który istnieje w naszym Katalogu (bo np. utworzyłeś już ją wcześniej sposobem opisanym w punkcie 1), lub ofertę powiązaną z produktem, którego nie ma w naszym Katalogu - w tej sytuacji produkt utworzymy automatycznie.

Powyższe procesy opisaliśmy w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem-za-pomoca-zasobu-sale-product-offers).

**Comment by KrzychuWalek** [comment]
Dziękuję, ogólnie przeszło.

Mam jednak produkt, który wyrzuca mi błąd 422:

Client error: `POST https://api.allegro.pl/sale/product-proposals` resulted in a `422 Unprocessable Entity` response

Przy statusie 422 guuzleClient zwraca mi wyjątek, więc nie mogę pobrać informacji o błędach (errors)
 (dla statusu 409 wyjątku nie ma, tam odczytuję komunikat: "code":"ProductDuplicate","message":"An error has occurred")
Dokumentacja sugeruje, że dla statusu 422 też tak winno być.

```
{
    "name": "JUNAK M15 125CCM ŚLIZG ŁAŃCUCHA NAPĘDOWEGO",
    "category": {
        "id": 316901
    },
    "images": [
        {
            "url": "https://a.allegroimg.com/original/11211e/46a8c87f459ca4773831f6b24c4b"
        },
        {
            "url": "https://a.allegroimg.com/original/111593/311b9e8f44aba4018c666b0c2175"
        }
    ],
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ]
        },
        {
            "id": "127415",
            "valuesIds": [
                "127415_1678533"
            ]
        },
        {
            "id": "214434",
            "valuesIds": [
                "214434_266978"
            ]
        },
        {
            "id": "215858",
            "values": [
                "t73484"
            ]
        },
        {
            "id": "247756",
            "valuesIds": [
                "247756_763694"
            ]
        },
        {
            "id": "229205",
            "valuesIds": [
                "229205_340245"
            ]
        }
    ],
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>JUNAK M15 125CCM ŚLIZG ŁAŃCUCHA NAPĘDOWEGO (na wahaczu głównym) (EURO IV)</p>"
                    }
                ]
            }
        ]
    }
}
```

**Comment by Lukasz-Zurek** [comment]
@KrzychuWalek Prześlij proszę trace-id. We wskazanym zasobie w przypadku błędu 422 zwracamy pełen komunikat błędu, zgodnie z dokumentacją i nie inaczej powinno być w tym przypadku.

**Comment by Lukasz-Zurek** [comment]
@KrzychuWalek Przeanalizowałem nasze logi. Użyłeś niedozwolonej encji w:

`"content": "<p>JUNAK M15 125CCM ŚLIZG ŁAŃCUCHA NAPĘDOWEGO (na wahaczu gł&oacute;wnym) (EURO IV)</p>"`

w związku z czym zwróciliśmy błąd 422:

`{"errors":[{"code":"VALIDATION_ERROR","message":"Użyto niedozwoloną encję "oacute". Dostępne encje to: &nbsp; &quot; &amp; &apos; &lt; &gt; &#160;","details":null,"path":"standardized.sections[0].items[0].content","userMessage":"Użyto niedozwoloną encję "oacute". Dostępne encje to: &nbsp; &quot; &amp; &apos; &lt; &gt; &#160;"}]}`

**Comment by KrzychuWalek** [comment]
Dzięki. Wyświetlałem logi na stronie.
