### ISSUE TITLE
Aktywacja konta allegro sandbox / allegro api sandbox

### ISSUE THREAD

**Issue by arcytest** [allegro/allegro-api#6307]
Dzień dobry,
Posiadam konto w allegro sandbox/"developer", chciałbym je wykorzystać do przygotowania sobie integracji z api innej firmy. Jednak nie mogę go aktywować, mimo że postępuję wg. instrukcji.
Mój login: arcytest
Mój e-mail: poczta@markomp.pl

**Comment by Lukasz-Zurek** [comment]
Aktywowałem Twoje konto. Jest w pełni aktywne i zweryfikowane jako firma.
