### ISSUE TITLE
Nie działa refresh token

### ISSUE THREAD

**Issue by AdamJachocki** [allegro/allegro-api#6309]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [X] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://dWystępuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środoeveloper.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Działam w trybie device flow. Po uzyskaniu access tokena i refresh tokena, za pomocą tego access tokena mogę pobierać dane. Wg dokumentacji access token jest ważny 12 godzin, a refresh token 3 miesiące. Po ponad 12 godzinach próbuję pobrać dane, używając starego access tokena. Otrzymuję odpowiedź 401 - tego się można spodziwać. Więc uderzam po nowy access token na adres:
`https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token={tokenData.RefreshToken}`
przekazując otrzymany 12 godzin wcześniej refresh token.
Niestety w tym momencie również otrzymuję odpowiedź 401

**Spodziewane działanie:**
Po strzale na odświeżenie tokena, powinienem otrzymać nowy access i refresh token

**Faktyczne działanie:**
Po strzale na odświeżenie tokena otrzymuję błąd 401. Cały flow autoryzacji musi zacząć się od nowa, co w przypadku device flow jest w ogóle nie do zaakceptowania.

**Comment by MaciejFrackowiak** [comment]
Abyśmy mogli zweryfikować konkretny przypadek potrzebujemy szczegóły Twojego wywołania - proszę przekaż nam je poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=78c31546-41e0-4305-8a41-4415ed3bd32c&subjectId=e6bcf131-deb8-4c2e-88cb-d929981a108c) dodając w wiadomości nr postu z GitHub - 6309.

**Comment by AdamJachocki** [comment]
Dzień dobry, napisałem już jakiś czas temu, ale nadal nie otrzymałem żadnej odpowiedzi.

**Comment by MaciejFrackowiak** [comment]
Niestety, żadna wiadomość nie została do nas przekazana. Czy możesz podać nr zgłoszenia, które wysłałeś? Może tak uda nam się do niego dotrzeć.

**Comment by AdamJachocki** [comment]
Niestety nie mam tego numeru. Mogę zgłosić drugi raz. Ale jakich danych konkretnie potrzebujecie?

**Comment by MaciejFrackowiak** [comment]
Piszesz:
> Po strzale na odświeżenie tokena otrzymuję błąd 401. Cały flow autoryzacji musi zacząć się od nowa, co w przypadku device flow jest w ogóle nie do zaakceptowania.

Aby to zweryfikować potrzebujemy szczegółów Twoich wywołań - prześlij proszę pełne dane z wysyłanymi tokenami.

**Comment by MaciejFrackowiak** [comment]
Wybierz proszę alternatywną ścieżkę z formularza kontaktowego i wówczas będziesz mógł wysłać wiadomość bezpośrednio.

**Comment by AdamJachocki** [comment]
Nie rozumiem jaką alternatywą ścieżkę. Co mam kliknąć?
![image](https://user-images.githubusercontent.com/36266826/202704910-9bc2bfd8-339c-438f-92c0-cc2fa25a3504.png)

**Comment by MaciejFrackowiak** [comment]
Np. Sprzedaję > Zarządzanie sprzedażą > Wystawianie oferty przez formularz.

**Comment by AdamJachocki** [comment]
OK, wysłane

**Comment by AdamJachocki** [comment]
Kurde, dostałem odpowiedź z Allegro, że muszę problem zgłosić na GitHub(!). Co z Wami jest nie tak??? Nr zgłoszenia na Allegro: 27886967

**Comment by MaciejFrackowiak** [comment]
Szukam Twojego zgłoszenia inną "ściężką". Wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Dotarłem do Twojej wiadomości - niestety, pomimo mojej wcześniejszej prośby nie przekazałeś żadnych szczegółowych danych tj. wysyłanych tokenów, dat wywołań, etc. Bez tego nie mamy praktycznie żadnej możliwości weryfikacji opisanej sytuacji.

**Comment by AdamJachocki** [comment]
Napisałem wszystko - daty i godziny wywołań i tokeny :| Gdzie mam to jeszcze umieścić?

**Comment by MaciejFrackowiak** [comment]
Próbuję uzyskać przedmiotowe dane.

**Comment by AdamJachocki** [comment]
Faktycznie. Jednak robiąc od nowa i dodając Authorization do odświeżenia tokenu (27.11.2022, godzina 20:43) nadal mam ten sam błąd 401:
{
    "error": "Unauthorized",
    "error_description": "Unauthorized"
}

**Comment by MaciejFrackowiak** [comment]
Prześlij proszę nam aktualne trace-id swoich wywołań, ponieważ jak wspomniałem wcześniej tylko tak możemy cokolwiek odnaleźć w naszych logach.

**Comment by PrzemyslawLukanowski** [comment]
Powyższy request zakończył się powodzeniem - zwróciliśmy status 200. Wyżej wspomniałeś o tym, że problem występuje w przypadku próby odświeżenia tokena i tutaj faktycznie udało mi się znaleźć Twoja próbę, jednak nie mam dostępu do informacji, w jaki sposób i jakie dane, przekazujesz w nagłówku Authorization. Czy na pewno tak, jak opisaliśmy to na naszej stronie?
<img width="626" alt="Zrzut ekranu 2022-11-29 o 09 08 10" src="https://user-images.githubusercontent.com/51473661/204473717-df65eb2e-ae19-475d-8e60-d74075db78fb.png">
Czy problem również występuje, jeśli spróbujesz odświeżyć token w konsoli?

**Comment by AdamJachocki** [comment]
OMG, nie robiłem tutaj Basica... Jakoś mi to umknęło. Dziękuję za pomoc.
