### ISSUE TITLE
Generowanie etykiet (kurier)

### ISSUE THREAD

**Issue by krzysda** [allegro/allegro-api#6310]
Witam,
Dzisiaj od rana otrzymuję komunikat "Execution of the request timed-out. Try again." podczas prób wygenerowania etykiet kurierskich.

**Comment by MaciejFrackowiak** [comment]
Tak, potwierdzam zaobserwowany problem - działamy już, aby przywrócić prawidłowe działanie mechanizmów.

**Comment by bragyou** [comment]
Nadal nic? Poniedziałkowy listopad, straszny problem.

**Comment by bragyou** [comment]
Listopadowy poniedziałek, to mega problem.

**Comment by MaciejFrackowiak** [comment]
Problem został usunięty. Przepraszam za niedogodności.
