### ISSUE TITLE
Problem z przetwarzaniem zapytań - timeout

### ISSUE THREAD

**Issue by shivson1337** [allegro/allegro-api#6311]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Podczas wysyłania zapytań do API do zasobów takich jak:

- /parcel-management/delivery-services 
- /parcel-management/parcel-create-commands/3bca85e2-xxxx-xxxx-xxxx-db2360948716
- /parcel-management/parcels/label?parcelId=xxxxxxxx&pageFormat=A6

Bardzo często otrzymujemy odpowiedź
`{"errors":[{"code":"ServiceTimeoutException","message":"An error occurred","details":null,"path":null,"userMessage":"Execution of the request timed-out. Try again."}]}`

Większość zapytań kończy się taką odpowiedzią.

Przykładowe trace-id:
trace-id: b6c484d0fdb247cc
trace-id: 297ebeb4c47b5dad
trace-id: c63c226b1e7c11a5

**Comment by MaciejFrackowiak** [comment]
Podobnie jak w wątku #6310 - potwierdzam zaobserwowany problem - działamy już, aby przywrócić prawidłowe działanie mechanizmów.

**Comment by shivson1337** [comment]
Jasne, czekamy w takim razie na rozwiązanie problemu.

**Comment by wap18** [comment]
Czy udało się rozwiązać problem?

**Comment by MaciejFrackowiak** [comment]
@wap18 Niestety, jeszcze nie. Działanie usługi poprawiło się, jednak nie jest to jeszcze stan oczekiwany.

**Comment by MaciejFrackowiak** [comment]
Problem został usunięty. Przepraszam za niedogodności.
