### ISSUE TITLE
Nie da się dotrzeć do przycisku WYLOGUJ bo nie da się przewinąć okna w dół gdzie owy przycisk winien się znajdować. Takie cuda widziane z laptopa a nie z komórki.

### ISSUE THREAD

**Issue by spacemenalt** [allegro/allegro-api#6313]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by MaciejFrackowiak** [comment]
Proszę doprecyzuj z jakiej przeglądarki korzystasz, jeśli możesz proszę załącz także screen obrazujący problem.

**Comment by spacemenalt** [comment]
Z Mozilli, ale dzisiaj już wszystko działa. Przycisk wylogowania cały czas
jest na widoku. Dziękuję za zainteresowanie problemem i pozdrawiam.

wt., 8 lis 2022 o 08:39 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
Dziękuję za potwierdzenie.
