### ISSUE TITLE
Dostęp do GET/offfers/listing

### ISSUE THREAD

**Issue by czytamy2022** [allegro/allegro-api#6314]
Dzień dobry, uprzejmie proszę o przydzielenie dostępu do GET /offers/listing dla aplikacji "poczytajmi". Dzięki dostępowi będziemy mogli wyszukać podobne oferty w celu dobrania odpowiedniej ceny w sposób bardziej zoptymalizowany. Dziękuję i pozdrawiam

**Comment by MaciejFrackowiak** [comment]
W celu uzyskania dostępu do zasobu skontaktuj się proszę ze swoim opiekunem (jeżeli go posiadasz) lub bezpośrednio poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=78c31546-41e0-4305-8a41-4415ed3bd32c&subjectId=e6bcf131-deb8-4c2e-88cb-d929981a108c).

**Comment by czytamy2022** [comment]
Formularz kontaktowy odsyła mnie na github, więc z kim mam się skontaktować? Opiekuna nie posiadam.

**Comment by MaciejFrackowiak** [comment]
Wybierz zatem [alternatywną](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) ściężkę z drzewa kategorii.

**Comment by michaltrojmiasto** [comment]
@MaciejFrackowiak dlaczego allegro w sposób jawny i czytelny nie informuje o warunkach jakie trzeba spełnić aby uzyskać dostęp do tej części API? Odnoszę wrażenie, iż decyzja o dostępie zależy od "widzimisie" i dobrego humoru osoby do której trafia wniosek.

**Comment by czytamy2022** [comment]
> @czytamy2022 - udało Ci się uzyskać dostęp?

Niestety nie

**Comment by MaciejFrackowiak** [comment]
@michaltrojmiasto [Regulamin](https://developer.allegro.pl/rules) REST API to precyzuje w punkcie 3.2.

**Comment by michaltrojmiasto** [comment]
@MaciejFrackowiak Tyle, że nie jest jasno sprecyzowane co należy zrobić aby przystąpić do programu: "Programu Allegro VIP". Pracownicy obsługujący zgłoszenia niestety nie chcą / nie potrafią udzielić takiej informacji, m.in. jaki poziom obrotów należy uzyskać informując jedynie, że obroty są za niskie. Dlaczego nie są to jawne i czytelne informacje aby każdy z użytkowników jasno wiedział do czego musi dążyć aby móc skorzystać z funkcjonalności "dla wybranych"? Może Pan jest w stanie sprecyzować te wymagania?

**Comment by MaciejFrackowiak** [comment]
@michaltrojmiasto Jak wielokrotnie pisaliśmy na forum - kwestia weryfikacji aplikacji oraz sam jej przebieg to proces całkowicie poza nami, na który realnie nie mamy żadnego wpływu. Z naszej strony świadczymy wsparcie w zakresie wykorzystaniu zasobu, czy też w momencie pojawienia się błędów podczas korzystania z API. Niestety, ale nie mam mocy sprawczych w opisanej kwestii.

**Comment by michaltrojmiasto** [comment]
@MaciejFrackowiak Rozumiem Twoją niemoc sprawczą w tym zakresie, natomiast warto o tym rozmawiać, może jeśli takich głosów będzie więcej to osoba, która za to odpowiada kiedyś podejdzie rozsądnie i uczciwie do tematu. Na ten moment w zasadzie nie wiadomo czy na konto VIP zasługuje osoba/firma o ładnym nicku, kolorze oczy, skóry, obrocie 100 tys, 1mln, 10 czy 100mln złotych czy rubli.
Niestety z punktu widzenia sprzedawców takie niejasne sytuacje i zwalanie odpowiedzialności na inne osoby/działy w firmie pokazuje politykę allegro do nas jako partnerów biznesowych. 
Zrozumiałym jest że pewne funkcjonalności mogą być uwarunkowane różnymi względami, natomiast w mojej ocenie powinny one być jasne i klarowne zarówno dla osób odpowiedzialnych za ich weryfikacje jak i dla nas użytkowników zainteresowanych.

**Comment by MaciejFrackowiak** [comment]
Mogę wyłącznie zachęcić Ciebie do przekazania swoich uwag via formularz kontaktowy bezpośrednio do obsługi serwisu, ponieważ tylko tak wiadomośc trafi do właściwej komórki.
