### ISSUE TITLE
Products created with sale/product-proposals are not visible

### ISSUE THREAD

**Issue by arslansahin** [allegro/allegro-api#6315]
Hello,
The product is created with the sale/product-proposals api, but I can't see the product I created on the sandbox page.
https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/obsluga-ofert/moj-asortyment

When I query with the sale/products api, the product created is listed.

What could be the reason why the created products are not visible in the sandbox account?

Also, how can I add price and stock information to products with the sale/product-proposals api.

Apart from the above issue, I am getting the following error regarding the sale/product-offers api.
I get an error that the brand information is missing even though the data sent contains the brand information.

request
{
  "productSet": [
    {
      "product": {
        "name": "Test ürünü",
        "category": {
          "id": "254779"
        },
        "images": [
          "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8cHJvZHVjdHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=750&q=60"
        ],
        "parameters": [
          {
            "id": "3786",
            "valuesIds": [
              "3786_904749"
            ],
            "values": [
              "32 Degrees"
            ]
          },
          {
            "id": "54",
            "valuesIds": [
              "54_859714"
            ]
          },
          {
            "id": "451",
            "valuesIds": [
              "451_16384"
            ]
          },
          {
            "id": "129392",
            "valuesIds": [
              "129392_3"
            ]
          },
          {
            "id": "201077",
            "valuesIds": [
              "201077_2569"
            ]
          },
          {
            "id": "201025",
            "valuesIds": [
              "201025_212045"
            ]
          },
          {
            "id": "201017",
            "valuesIds": [
              "201017_323985"
            ]
          }
        ]
      }
    }
  ],
  "delivery": {
    "shippingRates": {
      "name": "kargo"
    }
  },
  "sellingMode": {
    "price": {
      "amount": "220.85",
      "currency": "USD"
    }
  },
  "stock": {
    "available": 1
  }
}

response

    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ProductValidationException
                    [message] => Unable to create product without proper values in all required parameters: [Marka] in category: 254779
                    [details] => 
                    [path] => productSet[0].product
                    [userMessage] => Unable to create product without proper values in all required parameters: [Brand]
                )

        )

**Comment by MaciejFrackowiak** [comment]
[POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct) resource is responsible for creating product proposal, not for an active/inactive offer which should be visible on [My Assortment](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/obsluga-ofert/moj-asortyment?limit=20&publication.status=ACTIVE&sellingMode.format=BUY_NOW) page. 
In the next step, you should create an offer based on the product with [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) resource.
Yes, after last week's [synchronization](https://github.com/allegro/allegro-api/issues/6242) we have some issues with the Brand parameter on Sandbox - we are working to resolve it.
