### ISSUE TITLE
Inne oferty produktu

### ISSUE THREAD

**Issue by mloncur** [allegro/allegro-api#6316]
Nie mogę znaleźć informacji(albo po prostu jestem ślepy :)) czy istnieje możliwość sprawdzenia informacji o innych ofertach wybranego produktu?

Interesuje mnie tak naprawdę cena poszczególnych ofert

**Comment by PrzemyslawLukanowski** [comment]
Nie zwracamy w naszym API informacji o tym, jakie oferty są podłączone do danego produktu.
