### ISSUE TITLE
Problem z tworzeniem paczki po zmianach ID usług

### ISSUE THREAD

**Issue by shivson1337** [allegro/allegro-api#6317]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**
Po zmianie ID usług dostawy podczas tworzenia przesyłki przy sprawdzaniu stanu za pomocą /parcel-management/parcel-create-commands/ otrzymujemy odpowiedź:

`
{"id":"3aea8dbb-xxxx-xxxx-xxxx-1be6aa47998d","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Internal system error","details":null,"path":null,"userMessage":"Wewnętrzny błąd systemu"}]}
`

trace-id: 44aff78c8b25fc19 - pobierania statusu
trace-id: ff36aa37198af093 - tworzenia paczki

**Comment by shivson1337** [comment]
Czy mogę prosić o weryfikację @MaciejFrackowiak ?

**Comment by MaciejFrackowiak** [comment]
Weryfikuję już sytuację z zespołem - wrócę z odpowiedzią.

**Comment by krzysztofgal** [comment]
Zmieniły się również typy w odpowiedziach w Create New Parcel - niespodziewane nulle. Miały się zmienić id usług, zmienione są również nazwy - **kolejny** k*** **raz**, usługa nie dziła drugi raz w tym tygodzniu. Team WzA jest do zwolnienia. My zamiast zająć się obsługą zamówień, zajmujemy się debugowanniem.

**Comment by Onixarts** [comment]
Ja dodam od siebie, że chyba zmieniły się też identyfikatory paczek zwracane przez GET /parcel-create-commands. Było tak:

```json
{
"id": "b572cdd0-7f2c-4800-9165-15795bd95f3c",
"parcelId": "12345",
"status": "ERROR",
"errors": [
{}
]
}
```

A teraz jest tak:

```json
{
"id": "b572cdd0-7f2c-4800-9165-15795bd95f3c",
"parcelId": "259b5c7a-9056-4c74-80ec-9bb2978cf293",
"status": "ERROR",
"errors": [
{}
]
}
```
Z identyfikatora "cyfrowego" zrobił się GUID i rozwaliło nam to bazy użytkowników, które nie były na to gotowe. Dlaczego taka zmiana się pojawiła bez ostrzeżenia i dlaczego występuje tylko na niektórych paczkach?

Czy zostanie to wycofane/poprawione? Użytkownicy nie mogą nadawać przesyłek.

**Comment by MaciejFrackowiak** [comment]
@Onixarts Zgodnie z dokumentacją parcelId to pole stringowe, zatem nie można zakładać, że przyjmuje tylko wartości "cyfrowe". Zmiana ta jest docelowa.

**Comment by Onixarts** [comment]
No tak ale jednak zmiana z "12355" na guid to jest dość istotna zmiana, tym bardziej, że nie podajecie nigdzie ( o co już wielokrotnie prosiłem) długości tych stringów. Skąd mamy wiedzieć jakie pole w bazie danych przygotować na te identyfikatory? Jeśli widzę, że to są stringi w postaci liczb to zakładam, że będą to nieduże raczej stringi, wiec robię pole np na 16 znaków. A tu nagle pojawia się guid i trzeba 36 znaków. 
A co jeśli nagle zrobicie guid#guid... to i 36 nie wystarczy. Przecież bazy danych nie są z gumy i takie informacje jak maksymalna liczba znaków dla stringa **są bardzo istotne**. Dla nas takie zmiany powinny być dużo wcześniej ogłaszane, bo wymaga to zmian w bazach użytkowników, dystrybucji nowej wersji.

**Comment by krzysztofgal** [comment]
ParcelItemDetails - pole description w odpowiedzi nagle zrobiło się null zamiast pustego stringa.

**Comment by Onixarts** [comment]
Ja pierniczę, ale kłopotu narobiliście. U klientów tworzą się teraz kolejne przesyłki w WzA, bo nie da się zapisać paczek (przez błąd zbyt długiego identyfikatora paczki) przez co aplikacja nie wie, że przesyłka została już w WzA utworzona #omg.

**Comment by shivson1337** [comment]
Panie @MaciejFrackowiak ja powrócę jednak do kwestii poruszonej na początku. Czy wiadomo już coś w tym temacie?
Każda godzina to kolejne opóźnienia na magazynie i kolejna paleta przesyłek z opóźnieniem.

**Comment by bragyou** [comment]
Porażka.
Kolejny dzień, setki paczek.

**Comment by MaciejFrackowiak** [comment]
@shivson1337 Czekam na wyjaśnienie ze strony zespołu. Obecnie kluczowe było ustabilizowanie działania usługi.

**Comment by bragyou** [comment]
> @shivson1337 Czekam na wyjaśnienie ze strony zespołu. Obecnie kluczowe było ustabilizowanie działania usługi.

Która nadal nie działa.

**Comment by hahyes** [comment]
> Ja pierniczę, ale kłopotu narobiliście. U klientów tworzą się teraz kolejne przesyłki w WzA, bo nie da się zapisać paczek (przez błąd zbyt długiego identyfikatora paczki) przez co aplikacja nie wie, że przesyłka została już w WzA utworzona #omg.

@Onixarts Na to się jakoś przygotowałem więc żyję, ale kompresowanie etykiet do ZIPa bez jakiejkolwiek zapowiedzi... kurde, największy sadysta by czegoś takiego nie wymyślił.

**Comment by bragyou** [comment]
Kiedy problem będzie rozwiązany? Zaczyna się gorący okres a Wam zachciało się zmian, które od dwóch dni nękają sprzedawców. Mały poradzi sobie bezpośrednio na WzA, ale duży? Nie mamy czasu na ręczne klepanie!

**Comment by Onixarts** [comment]
> @Onixarts Zgodnie z dokumentacją parcelId to pole stringowe, zatem nie można zakładać, że przyjmuje tylko wartości "cyfrowe". Zmiana ta jest docelowa.

Zgodnie z dokumentacją cena w ofercie to też pole stringowe. Czy to oznacza, że w losowym momencie bez zapowiedzi zmienicie cenę z wartości cyfrowych na guidy? No tak nie można postępować. Zrozumcie wreszcie, że istnieje coś takiego jak typy danych i nasze oprogramowanie na tym bazuje.  A wy sobie robicie zmianę liczb na guid bez zapowiedzi, a tłumaczycie to sposobem przekazywania tych danych. Gdzie są te wasze podwójne code review, automaty monitorujące błędy, jak tak podstawowej sprawy nikt nie wykrył i nie podważył zanim trafiła na produkcję.

W dokumentacji przy niektorych stringach jest napisane, że jest to uuid i wszystko jasne. Ale samo pole stringowe wykorzystujecie do przesyłania różnych typów danych: Decimal, int, guid, string. Jakakolwiek zmiana w tych ukrytych typach musi być wcześniej ogłoszona, bo to są bardzo istotne informacje. Przecież nasze softy te dane przetwarzają, konwertują na odpowiedni typ, zapisują to w relacyjnych bazach danych. Taka zmiana wywala systemy sprzedawców uniemożliwiając im pracę!

**Comment by MaciejFrackowiak** [comment]
@bragyou Jaki konkretnie problem napotykasz obecnie? Usługa obecnie działa stabilnie, zatem proszę określ co dokładnie u Ciebie nie działa poprawnie.

**Comment by shivson1337** [comment]
W naszym przypadku nadal błąd z otwierającej wiadomości.

**Comment by shivson1337** [comment]
Załączam nowe trace-id
trace-id: 34846b0b7931e3f4
trace-id: c91eb8c8baca6767

**Comment by shivson1337** [comment]
Dla przypomnienia problemu:

Podczas tworzenia etykiety za pomocą endpointu PUT /parcel-management/parcel-create-commands otrzymujemy odpowiedź 201 Created, ale podczas odpytania tego samego zasobu metodą GET w celu pobrania statusu przesyłki, otrzymujemy zwrotkę

```
{
    "id": "efe36cd7-5d71-44c4-a18a-04cca2e9be56",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Internal system error",
            "details": null,
            "path": null,
            "userMessage": "Wewnętrzny błąd systemu"
        }
    ]
}
```

**Comment by MaciejFrackowiak** [comment]
@shivson1337 Pamiętam ;) - nowe przykłady przekazałem również do weryfikacji.

**Comment by shivson1337** [comment]
Znaleźliśmy rozwiązanie.
W czasie aktualiacji zmieniła się wymagalność pola "countryCode" w adresach.
Do tej pory, zgodnie z dokumentacją, pole miało domyślną wartość "PL".

![image](https://user-images.githubusercontent.com/60777356/201055915-958cf1a5-cb9f-4109-83b0-b75ee72f4bf3.png)

Niestety zostało to zmienione i od teraz pole jest wymagane, ale API nie zwraca stosownego błędu walidacji.

**Comment by MaciejFrackowiak** [comment]
@krzysztofgal Problem null został wyeliminowany, zwracmy już pusty string.

**Comment by larysoftware** [comment]
`{
  "id": "089cf722-a99b-4cc9-9657-b83985dda7a2",
  "parcelId": null,
  "status": "ERROR",
  "errors": [
    {
      "code": "ERROR",
      "message": "Internal system error",
      "details": null,
      "path": null,
      "userMessage": "Wewnętrzny błąd systemu"
    }
  ]
}`
wciąż dostajemy ten sam response. Dodatkowo podczas generowania etykiet
poleceniem
https://developer.allegro.pl/documentation/#operation/getParcelLabel chcemy wygenerować inną etykietę niż pdf.
w nagłowkach  ustawiamy
`-H 'Accept:  text/plain' \ 
  -H 'Content-Type: text/plain'`
a pole pageFormat pomijamy wd dokumentacji 
dostajemy zwrotkę

The Allegro REST Api service has returned one or more errors in response to a request (Not acceptable representation requested. Please check 'Accept' request header (NotAcceptableException))



id takiego requestu ad5d1930-0077-4964-a9c3-dabaab88f71
prosimy o naprawę bo nie da się pracować

**Comment by MaciejFrackowiak** [comment]
@larysoftware Prośba o podanie właściwego commandId, ponieważ pod wskazanym nie widzę żadnych logów.

**Comment by larysoftware** [comment]
https://api.allegro.pl/parcel-management/parcel-create-commands/c2aaff5b-40ef-4e5a-9856-85db844c9bbe

`{
  "id": "c2aaff5b-40ef-4e5a-9856-85db844c9bbe",
  "parcelId": null,
  "status": "ERROR",
  "errors": [
    {
      "code": "ERROR",
      "message": "Internal system error",
      "details": null,
      "path": null,
      "userMessage": "Wewnętrzny błąd systemu"
    }
  ]
}`

aktualnie nie mogę odtworzyć błędu z etykietą gdyż nie mogę zarejestrować paczki

**Comment by MaciejFrackowiak** [comment]
@larysoftware Przyczyną błędu jest brak podanych wymiarów paczki - dokładnie element "items":[{"dimensions":null". Podaj zatem prawidłowe wymiary paczki i wówczas request zakończy się poprawnie. Oczywiście, będziemy poprawiać treść zwracanego komunikatu.

**Comment by larysoftware** [comment]
{
  "id": "58a52c96-d060-4dbb-9158-c008785733d9",
  "parcelId": null,
  "status": "ERROR",
  "errors": [
    {
      "code": "VALIDATION_ERROR",
      "message": "must match \"\\d+\\.\\d{2}\"",
      "details": "Invalid value: 2",
      "path": "cod.amount",
      "userMessage": "must match \"\\d+\\.\\d{2}\""
    }
  ]
}

Czy to ma być userMessage ??

**Comment by MaciejFrackowiak** [comment]
@larysoftware Oczywiście nie - przekazuję temat do zespołu w celu poprawienia treści.

**Comment by MaciejFrackowiak** [comment]
@larysoftware Kwestia protokołu - docelowo będziemy zwracać *.pdf - pracujemy nad poprawieniem tej niespójności. Natomiast odnośnie kwot - tak, format musi posiadać dwa miejsca po przecinku, taki sposób prezentacji kwoty obowiązuje od początku - wspominamy o tym w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke).

**Comment by larysoftware** [comment]
podobnie ten request 
422780ff-e9f9-4cb4-80aa-71b336d18f81

**Comment by larysoftware** [comment]
@MaciejFrackowiak Czy korzystają państwo w protokołach odbioru kompresji cross-reference tables. W przypadku etykiet możemy łączyć dokumenty natomiast w przypadku porotokołów odobioru takiego łączenia nie jesteśmy wstanie przeprowadzić . Wcześniej działało to poprawnie. Dodatkowo zauważyłem że PDF dla etykiet zwracany jest w wersji 1.4 natomiast porotokoły odbioru w wersji PDF 1.5

**Comment by MaciejFrackowiak** [comment]
@larysoftware Wyjaśniam kwestię plików, wrócę z odpowiedzią.

**Comment by larysoftware** [comment]
@MaciejFrackowiak przypominam się z pytaniem

**Comment by MaciejFrackowiak** [comment]
@larysoftware Pamiętam i mam odpowiedź - wspieramy kompresję cross-reference tables. Kompresja została wdrożona 8 listopada wraz z pojawieniem się zmian w przetwarzaniu dokumentów. Aby poprawić efektywność zmniejszymy stopień kompresji. Natomiast odnośnie wersji PDF - jeżeli pobieramy protokoły dla jednej umowy to przekazujemy plik bezpośrednio od przewoźnika. Natomiast jeżeli mamy wiele plików od różnych przewoźników to je przetwarzamy i scalamy.

**Comment by larysoftware** [comment]
@MaciejFrackowiak państwa api umożliwia pobranie dokumentów per jedno parcelId nie jest możliwe pobranie złączonego pliku dla wielu parcelId. Prawda czy jest coś co przeoczyłem 
https://developer.allegro.pl/documentation/#operation/getParcelsProtocol ?

**Comment by MaciejFrackowiak** [comment]
@larysoftware Możesz podać do 100 identyfikatorów przesyłek - przy opisie query parameters znajdziesz ten dopisek.

**Comment by larysoftware** [comment]
@MaciejFrackowiak ok dzięki faktycznie nie zauważyłem

**Comment by lmichalFerrodo** [comment]
Dzień dobry,
mam następujący problem. Podczas tworzenia paczki:

https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/36092320-9008-11ed-ba61-dbcba483d56d

Request:
`{"serviceId":"0aafb43c-e66a-46ec-9cc4-29bb39ebb483","receiver":{"address":{"street":"Testowa 8","postCode":"62-010","city":"Pobiedziska","countryCode":"PL","county":null},"email":"n3tmqh8wcv+16ea4ade6@user.allegrogroup.pl","name":"Test","company":null,"phone":"+48501602703","pointId":"AL041PO1"},"pickup":{"address":{"street":"Testowa Michała 123","postCode":"60-694","city":"Poznań","countryCode":"PL","county":null},"email":"testowyEmail@testowy.pl","name":"Testowa Nazwa","company":"Testowa firma","phone":"123456789","pointId":null},"items":[{"dimensions":{"height":{"value":"38","unit":"CENTIMETER"},"width":{"value":"38","unit":"CENTIMETER"},"depth":{"value":"38","unit":"CENTIMETER"}},"weight":{"value":"2.22","unit":"KILOGRAM"},"description":"testowy opis","value":{"amount":"261.88","currency":"PLN"},"type":"PACKAGE"}],"type":"PACKAGE","label":{"sender":{"address":{"street":"Testowa Michała 123","postCode":"60-694","city":"Poznań","countryCode":"PL","county":null},"email":"testowyEmail@testowy.pl","name":"Testowa nazwa","company":"Testowa firma","phone":"123456789"},"fileFormat":"PDF","referenceNumber":"20221001"},"additionalServices":null}`

Otrzymuje informacje o utworzeniu paczki (status 201) oraz Response:
`{"id":"36092320-9008-11ed-ba61-dbcba483d56d","input":{"serviceId":"0aafb43c-e66a-46ec-9cc4-29bb39ebb483","label":{"sender":{"name":null,"company":"Testowa firma","address":{"street":"Testowa Michała 123","postCode":"60-694","city":"Poznań","county":null,"countryCode":null},"email":"testowyEmail@testowy.pl","phone":"123456789"},"fileFormat":"PDF","referenceNumber":"20221001"},"receiver":{"name":"Test","company":null,"address":{"street":"Testowa 8","postCode":"62-010","city":"Pobiedziska","county":null,"countryCode":"PL"},"pointId":"AL041PO1","email":"n3tmqh8wcv+16ea4ade6@user.allegrogroup.pl","phone":"+48501602703"},"pickup":{"name":null,"company":"Testowa firma","address":{"street":"Testowa Michała 123","postCode":"60-694","city":"Poznań","county":null,"countryCode":"PL"},"pointId":null,"email":"testowyEmail@testowy.pl","phone":"123456789"},"items":[{"dimensions":null,"weight":{"value":"2.22","unit":"KILOGRAM"},"description":null,"value":{"amount":"261.88","currency":"PLN"},"type":"PACKAGE"}],"type":null,"additionalServices":null}}`

Jak można zauważyć w responsie nie są uwzględnione np informacje o wymiarach paczki czy typie paczki, pola te są nullowe, chociaż były wypełnione w Requescie. Przez to podczas próby pobrania informacji o statusie utworzenia przesyłki:

https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/36092320-9008-11ed-ba61-dbcba483d56d

Otrzymuje response w postaci:

`{"id":"36092320-9008-11ed-ba61-dbcba483d56d","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Internal system error","details":null,"path":null,"userMessage":"Wewnętrzny błąd systemu"}]}`

Proszę o informacje, co możne być przyczyną problemu oraz ewentualne rozwiązanie.
Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
@lmichalFerrodo W pierwszym requeście PUT z podanym commandId nie wskazałeś m.in. rozmiarów przesyłki i dlatego zwróciliśmy błąd. Każdy kolejny request musi być wywołany z nowym commandId - a jak widzę Ty wywoływałeś kolejne requesty z tym samym commandId (36092320-9008-11ed-ba61-dbcba483d56d). W rezultacie otrzymujesz zawsze odpowiedź dla Twojego pierwszego wywołania (z brakiem rozmiaru).

**Comment by lmichalFerrodo** [comment]
Dziękuje bardzo za odpowiedz.
Wracam teraz z kolejnym pytaniem. Podczas próby wywołania:
https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcels/label?parcelId=56006f0f-9ece-4c99-acaa-807365bf179a&pageFormat=A4
otrzymuje odpowiedź: Błąd odpowiedźi kod statusu : 406 ,ReasonPhrase: Not Acceptable.
Proszę o informacje, w którym miejscu robię błąd. Paczka została utworzona dla uuid: 315cbbc0-90fd-11ed-932c-a95a51399753, status utworzenia również był OK.

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
@lmichalFerrodo Jest dokładnie jak @krzysztofgal zauważył - przesyłasz nagłówek Accept w postaci "application/vnd.allegro.public.v1+json", a w tym przypadku musi to być "application/pdf" lub "text/plain".

**Comment by ar2oor** [comment]
Jaki Accept powinien być dla ZPL? "x-application/zpl" lub "text/plain" nie działa,  dostaję zwrotkę 
"Not acceptable representation requested. Please check 'Accept' request header"

**Comment by MaciejFrackowiak** [comment]
@ar2oor Dla zasobów Shipment management właściwy nagłówek to "application/octet-stream".
