### ISSUE TITLE
/parcel-management/parcels/label wymaga accept i content-type dla PDF nawet przy pobieraniu ZPL

### ISSUE THREAD

**Issue by q3ok** [allegro/allegro-api#6319]
Środowisko produkcyjne.

Aby pobrać etykietę wygenerowaną w ZPL, to mimo tego trzeba ustawić headery accept i content-type na application/pdf, w innym wypadku przyjdzie zwrotka w JSON o błędnym header. Problem zauważony dzisiaj w godzinach wieczornych, wcześniej działało poprawnie.

**Comment by Sebastian-Le** [comment]
Opisany problem dalej występuje, proszę o informację jak to usuniecie aby poprawić nagłówki na właściwe.

**Comment by MaciejFrackowiak** [comment]
@q3ok @Sebastian-Le Zespół pracuje nad poprawką eliminującą opisany przez Was problem. Zmianę przywracającą właściwe działanie chcemy wdrożyć najszybciej jak to możliwe.

**Comment by paafcioc22** [comment]
Mam to samo . Nie mogę wydrukować paczek utworzonych w formacie ZPL. Błąd w nagłówku.

**Comment by karolus888** [comment]
Mamy ten sam problem. Zlecenie na ZPL, tworzy się przesyłka z etykietą w formacie PDF.
Przykładowe parcelId = b357cf02-8cd7-40de-9f05-4808c505d122

**Comment by MaciejFrackowiak** [comment]
@paafcioc22 @karolus888 Jak wspomniałem wyżej - pracujemy nad poprawką eliminującą błąd.

**Comment by Sebastian-Le** [comment]
Teraz przestała nawet działać opcja rezerwowa wydruku ZPL z nagłówkami  application/pdf (otrzymuję plik pdf), 

dla nagłówków text/plain 
{"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept' request header","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji"}]}

**Comment by MaciejFrackowiak** [comment]
@q3ok @Sebastian-Le @paafcioc22 @karolus888 Problem został wyeliminowany, od godzin nocnych zwracamy już prawidłowe etykiety.

**Comment by q3ok** [comment]
Dziękuję, działa.
