### ISSUE TITLE
Prośba o external w /offers/listing

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#632]
Dzień dobry,

czy byłoby możliwe dodanie pola external występującego w ofercie (np. GET /sale/offers/{offerId}) do rezultatu GET /offers/listing, oraz dodanie tego do filtrów? 

Byłoby wygodnie móc przeszukiwać oferty wg. swojego identyfikatora, co więcej jeżeli chcemy external pokazać w listingu to trzeba wykonać dodatkowe zapytanie GET do /sale/offers/{offerId} albo mieć u siebie w jakiś sposób to zapisane np. w cache albo bazie danych.

**Comment by TomekKaczmarek** [comment]
Na razie nie planujemy dodawać tego pola do listy ofert. Być może taka opcja pojawi się w nowych zasobach, który przygotowujemy do zarządzania ofert przez sprzedawcę - dziękujemy za sugestię.

**Comment by jakubmaguza** [comment]
Zastanawiam się, czy jest jakieś techniczne wytłumaczenie dlaczego tak bardzo nie chcecie podawać tego pola.

**Comment by TimothyKoval** [comment]
A ja się zastanawiam jakie jest techniczne wytłumaczenie jego używania w tak szerokim zakresie.

**Comment by TomekKaczmarek** [comment]
@kadetth dzięki za sugestie
@jakubmaguza tak jak pisaliśmy, ten zasób odpowiada liście ofert i wyszukiwarce, które są dostępne na froncie dla klientów - nie ma sensu, by zasób obsługiwał pole external, które jest potrzebne tylko z perspektywy sprzedawcy - dlatego pole external obsłuży lista ofert sprzedawcy, nad która obecnie pracujemy.

**Comment by tztztztz** [comment]
@TimothyKoval - to ja może powtórzę jakie jest techniczne wytłumaczenie:

"Byłoby wygodnie móc przeszukiwać oferty wg. swojego identyfikatora, co więcej jeżeli chcemy external pokazać w listingu to trzeba wykonać dodatkowe zapytanie GET do /sale/offers/{offerId} albo mieć u siebie w jakiś sposób to zapisane np. w cache albo bazie danych."

Już wiesz? Bez identyfikatora external muszę robić dla każdej oferty na liście wyswietlanej klientowi dodatkowe zapytanie do REST API, żeby mu pokazać z jakim produktem lokalnym jest dana oferta na liście powiązana. Gdybym od razu miał external, wystarczy, że teraz zapytam lokalną bazę danych o pozostałe parametry powiązanego produktu - nazwa, aktualna cena w lokalnym systemie, etc., a bez tego muszę dodatkowo męczyć RESTA setką zapytań do REST API za każdym razem kiedy klient wyświetli jedną listę ofert - czyli 101 zapytań do REST API, żeby klientowi pokazać stornę z listą jego aukcji.

**Comment by mpysz** [comment]
@TomekKaczmarek czy jest znany termin wdrożenia listy ofert dla sprzedawcy zawierającej pole external?

**Comment by jakubmaguza** [comment]
@TomekKaczmarek Tak, tutaj nie ma takiej potrzeby, ale w liście ofert sprzedawcy, czy w sprzedanych przedmiotach już jak najbardziej :)

**Comment by TomekKaczmarek** [comment]
@mpysz @jakubmaguza lista ofert sprzedawcy w wersji beta powinna się pojawić w ciągu tygodnia, dwóch - właśnie jesteśmy w trakcie jej opisywania i testowania. Na początku najprawdopodobniej bez pola external, które wdrożymy trochę później. O wszystkich zmianach będziemy Was informować na bieżąco.
