### ISSUE TITLE
/parcel-management/parcels/label - zawsze zwraca format A4

### ISSUE THREAD

**Issue by arolznov** [allegro/allegro-api#6320]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Etykiety DPD pomino wybranego rozmiaru A6 i typu PDF są generowane zawsze w formacie A4 i zajmują 1/4 strony
przykładowy parcel id:
ac22c81e-6539-47a7-bc20-c65371f338f0

**Comment by hahyes** [comment]
Podpinam się, dostałem to samo zgłoszenie problemu dosłownie minutę temu.

**Comment by MaciejFrackowiak** [comment]
Opisany tu problem weryfikuję już z zespołem, wrócę z odpowiedzią.

**Comment by arolznov** [comment]
Dodatkowo często pod tym endpointem wyskakuje błąd 504 Gateway Timeout

**Comment by q3ok** [comment]
@arolznov z ciekawości zapytam, czy przy pobieraniu dajesz parametr w url pageFormat? (&pageFormat=A6) czy tylko przy generowaniu format.

**Comment by arolznov** [comment]
Tak, zawsze podaje parametr pageFormat

**Comment by relains** [comment]
U mnie ten sam problem dla Orlen paczki i Allegro One.

Czy mógłby ktoś wreszcie to naprawić? Ponosimy realne straty z tego powodu.

**Comment by arolznov** [comment]
@MaciejFrackowiak kiedy ten problem zostanie rozwiązany oraz naprawiona stabilność działania WzA (co chwile są błędy 500, 503, 504)?

**Comment by MaciejFrackowiak** [comment]
@arolznov @hahyes @q3ok @relains Pracujemy, aby przywrócić właściwe działanie funkcjonalności, nastąpi to możliwie szybko.

@arolznov Nadal otrzymujesz błędy typu 50x? Serwis generalnie działa stabilnie, stąd prośba o szczegóły.

**Comment by Qenozis** [comment]
> Występuje problem:
> 
>     * [x]  z zasobem REST API / with a REST API resource
> 
>     * [ ]  ze środowiskiem produkcyjnym / with the production environment
> 
>     * [ ]  ze środowiskiem testowym / with the test environment
> 
>     * [ ]  z logowaniem lub autoryzacją / with login or authorization
> 
>     * [ ]  na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
> 
>     * [ ]  inny / other
> 
> 
> Etykiety DPD pomino wybranego rozmiaru A6 i typu PDF są generowane zawsze w formacie A4 i zajmują 1/4 strony przykładowy parcel id: ac22c81e-6539-47a7-bc20-c65371f338f0

U nas jest dokładnie ten sam problem.
Problem ten nie występuje jedynie przy etykietach wygenerowanych przed 2022-11-09, które miały (i nadal mają) jeszcze numeryczne identyfikatory. Po ostatniej zmianie na identyfikatory GUID jest problem. Wybrany przewoźnik nie ma znaczenia - zawsze generuje się A4 zamiast wymaganego A6... Wymaga on pilnej naprawy, ponieważ utrudnia to wysyłkę poprzez brak możliwości używania drukarki do naklejek z listem przewozowym.

**Comment by MaciejFrackowiak** [comment]
@Qenozis Trwają prace nad przywróceniem możliwości drukowania etykiet zgodnie z wybranym przez użytkownika formatem.

**Comment by Qenozis** [comment]
> @Qenozis Trwają prace nad przywróceniem możliwości drukowania etykiet zgodnie z wybranym przez użytkownika formatem.

Pozytywne efekty już widzimy - dziś listy generują nam się poprawnie w formacie A6.

**Comment by MaciejFrackowiak** [comment]
@Qenozis @hahyes Prace jeszcze trwają, ale już bliżej niż dalej ;)
