### ISSUE TITLE
Błąd braku wymiarów podczas pobierania szczegółów paczki oraz 503

### ISSUE THREAD

**Issue by mtanasiewicz** [allegro/allegro-api#6321]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Trace id: 9fd5494f5f99ea30

1. Endpoint GET  /parcel-management/parcels/f04eb467-e02e-44f6-a774-942b9f8b0468 zwraca null w polu dimensions, pomimo że wymiary  zostały przekazane podczas tworzenia.
2. Co chwilę dostajemy status 503 w odpowiedzi na różnych endpointach.

**Comment by MaciejFrackowiak** [comment]
Problem z punktu 1 przekazałem do weryfikacji, natomiast odnośnie punktu 2 - działamy, aby przywrócić stabilność działania serwisu.

**Comment by mtanasiewicz** [comment]
OK dziękuję za informację

**Comment by MaciejFrackowiak** [comment]
Stabilne działanie usługi zostało przywrócone. Z tematem nr 1 powrócę.

**Comment by mtanasiewicz** [comment]
OK. Obsłużyliśmy już nulle które wracały na tym endpoincie. Występują też inne problemy z api. Randomowo dostajemy błędy o treści `Delivery Method is not available for this order` na endpoincie `/parcel-management/parcel-create-commands/98b47499-84bc-4506-b934-6692f290f343`. O co może chodzić?

Trace id: 15078420efa99a04

**Comment by arolznov** [comment]
@mtanasiewicz zmieniły się id'ki usług dostawy, sprawdź czy usługa jest zgodna z tą jaką wybrał klient.
Lista tutaj:
GET /parcel-management/delivery-services

**Comment by MaciejFrackowiak** [comment]
@mtanasiewicz Ad punkt 1 - pracujemy nad wyeliminowaniem tego problemu.

**Comment by MaciejFrackowiak** [comment]
@mtanasiewicz Poprawka dot. null została wdrożona, problem nie powinien już występować.
