### ISSUE TITLE
Pobieranie etykiet

### ISSUE THREAD

**Issue by McCain98** [allegro/allegro-api#6322]
Podczas pobierania etykiety generuje się plik zip, który trzeba pobrać i otworzyć. Wcześniej pobierało i otwierało od razu pdf. Zbyt czasochłonne przy większej ilości zamówień.

**Comment by MaciejFrackowiak** [comment]
Obecnie taki sposób działania tj. pobieranie pliku *.zip będzie domyślnym sposobem działania mechanizmu.

**Comment by hahyes** [comment]
> Obecnie taki sposób działania tj. pobieranie pliku *.zip będzie domyślnym sposobem działania mechanizmu.

@MaciejFrackowiak Proszę o sprecyzowanie tej informacji. Chce Pan powiedzieć, że nie będzie możliwości pobrania pliku PDF bezpośrednio? Nie ma sposobu, aby pobrać plik PDF bez archiwum? Pytam, ponieważ pierwsze słyszę o takiej zmianie. To jest bardzo poważna modyfikacja.

**Comment by MaciejFrackowiak** [comment]
@hahyes Tak, zgadza się. Bezpośrednio plik *.pdf można pobrać tylko poprzez zakładkę [Zamówione przesyłki](https://allegro.pl/moje-allegro/sprzedaz/wysylam/lista-przesylek).

**Comment by Radeq** [comment]
@MaciejFrackowiak , kiedy ta zmiana została zapowiedziana?

**Comment by McCain98** [comment]
Powinno więc być na odwrót, że w zakładce "Zamówione przesyłki" generował się zip podczas zaznaczania kilku przesyłek, a nie jak generuje się tylko jedną zaraz po nadaniu. Kolejne niepotrzebne kliknięcia.

**Comment by hahyes** [comment]
>Tak, zgadza się. Bezpośrednio plik *.pdf można pobrać tylko poprzez zakładkę [Zamówione przesyłki](https://allegro.pl/moje-allegro/sprzedaz/wysylam/lista-przesylek).

@MaciejFrackowiak Zapytam jeszcze raz, ponieważ jestem solidnie zmieszany i nie wiem, czego się spodziewać. Co pobierze mi się poprzez zasób `/parcel-management/parcels/label`? Co powinno się pobierać? ZIP czy plik w wybranym formacie pliku etykiety? Poprzednia odpowiedź spowodowała chaos, testuje rzekome zmiany i nie wiem, czego mam się spodziewać.

**Comment by MaciejFrackowiak** [comment]
@hahyes Wracam z ostatecznymi ustaleniami - obecny stan, czyli zwracanie w API pliku w formacie *.zip jest błędem. Zespół pracuje nad przywróceniem właściwego działania tj. chcesz otrzymać *.pdf i to określasz w requeście, otrzymujesz *.pdf.

**Comment by MaciejFrackowiak** [comment]
@McCain98 @Radeq @hahyes Błąd został wyeliminowany - od teraz w API otrzymacie załącznik w formacie ZPL/EPL/PDF zgodnie z Waszym wyborem.

**Comment by Zooroompl** [comment]
Mamy problem z wysyłką UPS, w trakcie próby nadania etykiety UPS w baselinkerze wyskakuje taka informacja:
"Go to the integration settings and save the account settings again in order to retrieve active information for the Allegro services account (#NP1a)"

**Comment by MaciejFrackowiak** [comment]
@Zooroompl Tu musisz skontaktować się z supportem BaseLinker, który ten komunikat zwraca.

**Comment by hahyes** [comment]
> Mamy problem z wysyłką UPS, w trakcie próby nadania etykiety UPS w baselinkerze wyskakuje taka informacja: "Go to the integration settings and save the account settings again in order to retrieve active information for the Allegro services account (#NP1a)"

Wejdź w ustawienia integracji i zapisz ponownie ustawienia konta, żeby naprawić ten problem.
Przetłumaczyłem ci komunikat, nie ma za co. ;)
