### ISSUE TITLE
Zip - etykiety, status zamowienia z NOWE na WYSLANE

### ISSUE THREAD

**Issue by CaniggiaClaudio** [allegro/allegro-api#6323]
Dzień dobry

1
Zauważyłem od kilku dni, ze po wygenerowaniu etykiety (ONE/DPD/UPS) przez allegro "aukcja" zmienia status automatycznie z NOWA na WYSLANE.
Co musze zrobić, żeby tak się nie działo? 
Wcześniej sam manualnie zmieniałem status i mi to odpowiadało.

2
Etykiety wygenerowane ta droga utworzone są w pliku rar/zip, wcześniej były od razu w PDF. Jak to zmienić? Ciągle wypakowywanie pliku jest irytujące.

Dziękuję
Piotr

**Comment by PrzemyslawLukanowski** [comment]
1. Upewnij się, że w zakładce Zamówienia -> Ustawienia nie masz ustawionej poniższej opcji:
<img width="542" alt="Zrzut ekranu 2022-11-9 o 11 44 09" src="https://user-images.githubusercontent.com/51473661/200810511-97c3c440-3c67-4191-9562-b9aac4ad0764.png">

Jeśli nie masz, a status mimo to zmienia się automatycznie, podaj proszę przykładowy numer zamówienia.

2. Otrzymaliśmy już podobne zgłoszenie w wątku #6322 - udzielimy w nim odpowiedzi po konsultacjach z zespołem odpowiedzialnym za usługę.
