### ISSUE TITLE
Oferta aktywna pomimo dezaktywacji

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#6325]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

Pomimo tego ,że api zwraca 201 created, przy requescie na  /sale/offer-publication-commands z body {"offerCriteria":[{"offers":[{"id":"12848426780"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"END","scheduledFor":null}} oferta nadal jest aktywna

Response:
HTTP CODE 201
{"id":"78115eca-9f21-4a3a-b8b0-5a00d86db29f","taskCount":{"total":0,"success":0,"failed":0}}

Oferta jest aktywna od dłuższego czasu, tak jakby utworzony task nie został wykonany i porzucony

trace-id: 3343fdaa6e353bab

**Comment by PrzemyslawLukanowski** [comment]
Status 201 oznacza, że przyjęliśmy zadanie, jednak nie jest to równoznaczne z tym, że zostało od razu przez nas przetworzone. Zasób działa asynchronicznie, dlatego dokładny status wykonania możesz sprawdzić za pomocą [GET 
 /sale/offer-publication-commands/{commandID}/tasks](https://developer.allegro.pl/documentation#operation/getPublicationTasksUsingGET). Samo przetworzenie zadania może potrwać do godziny, natomiast w przypadku tej oferty, sekundę przed otrzymaniem zadania 78115eca-9f21-4a3a-b8b0-5a00d86db29f otrzymaliśmy komendę ad2574b9-232d-46c8-87e1-d70290e9b6b0,, której celem była aktywacja oferty. Jako pierwsze przetworzyliśmy zadanie związane z zakończeniem oferty, a jako drugie, te związane z aktywacją - oferta została zatem na krótki czas zakończona, po czym od razy ponownie aktywowana.
