### ISSUE TITLE
Maksymalne wymiary ORLEN paczka

### ISSUE THREAD

**Issue by relains** [allegro/allegro-api#6326]
Witam,

Po dzisiejszych zmianach zaczęli mi wywalać dla ORLEN paczki błędy dotyczące zbyt dużej wartości w polu "Długość". Do wczoraj przekazywałem wymiary 50x30x20 i było OK. Nigdzie nie mogę znaleźć jakie są dopuszczalne wartości dla tego kuriera. Proszę mi tutaj przekazać taką informację.

Pozdrawiam
Rafał Stępień

**Comment by PrzemyslawLukanowski** [comment]
Poniżej przesyłam informacje:

> Wymiary paczki dla klientów indywidualnych: Mini: maksymalny wymiar paczki 20x20x30 cm, maksymalna waga do 5 kg. Standard: maksymalny wymiar paczki 20x30x50 cm, maksymalna waga do 20 kg.   Wymiary paczki dla klientów biznesowych: S:  8x38x60 cm, maksymalna waga 25 kg M: 19x38x60 cm, maksymalna waga 25 kg L: 41x38x60 cm, maksymalna waga 25 kg

**Comment by q3ok** [comment]
Miałem taki sam problem, musiałem wygenerować paczkę bezpośrednio z managera paczkawruchu, przy paczce 35x20x10 (cm), która powinna "wejść" w gabaryt "M" a.k.a. STANDARD.

Z informacji które mam od przedstawiciela ORLEN Paczka:

> Paczki do Automatów paczkowych i na stacje paliw Orlen mają 3 rozmiary – s/m/l.
> Paczki do innych punktów mają rozmiary mini i standard.

oraz

> W naszym api dalej są stare gabaryty MINI i STANDARD natomiast są one maczowane z nowymi wymiarami czyli MINI rozliczamy w cenie S a STANDARD w cenie M

natomiast z umowy rozmiary gabarytów S/M/L:

> S waga do 25 kg i wymiary nie większe niż 8 X 38 X 60 cm
> M waga do 25 kg i wymiary nie większe niż 19 X 38 X 60 cm
> L waga do 25 kg i wymiary nie większe niż 41 X 38 X 60 cm
