### ISSUE TITLE
Brak etykiet dla przesyłek Allegro One oraz UPS

### ISSUE THREAD

**Issue by q3ok** [allegro/allegro-api#6327]
Problem występuje na produkcji, zarówno po REST API jak i bezpośrednio w Wysyłam z Allegro.

Nie mogę wygenerować etykiety dla metod dostawy Allegro One Box jak też UPS, zarówno przy wyborze w ustawieniach formatu ZPL jak i PDF, oraz A4 i A6.
Niezależnie, czy etykieta zostanie wygenerowana jako PDF, czy jako ZPL, w rozmiarze A4 i A6, czy pobrana z nowej podstrony z listą, czy podczas generowania paczki, czy z REST API, kod etykiety zawiera na początku "PK" i znaki specjalne, odpowiednio jest ta treść w pliku z rozszerzeniem ZIP, PDF lub ZPL, czy też tekstem pobrana z API.

Przykładowa etykieta:
[label-error.pdf](https://github.com/allegro/allegro-api/files/9972253/label-error.pdf)

**Comment by MaciejFrackowiak** [comment]
Proszę podaj przykładowe commandId przesyłki, dla której opisany problem natrafiłeś przy korzystaniu z API.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przykłady, kieruję je do weryfikacji.

**Comment by karolus888** [comment]
Potwierdzam, mamy podobny problem z etykietami. Zlecenie utworzenia przesyłki z etykietą ZPL, tworzy się przesyłka PDF.
Przykładowe parcelId:  b357cf02-8cd7-40de-9f05-4808c505d122

Proszę o pilne podjęcie, blokuje drukowanie etykiet.

**Comment by MaciejFrackowiak** [comment]
@MaciejSzypnicky Działamy, aby jak najszybciej wyeliminować problem. Nie sposób mi jednak w tej chwili podać jednoznacznego terminu.

**Comment by MaciejSzypnicky** [comment]
@MaciejFrackowiak Widzę że etykiety pobrane dziś rano przez API mają poprawną zawartość (UPS i ONE)

**Comment by MaciejFrackowiak** [comment]
@q3ok @MaciejSzypnicky Poprawka została wdrożona, od godzin nocnych etykiety są już poprawnie generowane.

**Comment by q3ok** [comment]
Potwierdzam, działa zarówno w PDF jak i ZPL, dodatkowo widzę że zamawianie kuriera też działa. Dziękuję.

**Comment by q3ok** [comment]
@MaciejFrackowiak dziś problem powrócił

**Comment by MaciejFrackowiak** [comment]
@q3ok Poproszę o przykładowe commandId - i proszę opisz dokładnie co się dzieje lub co jest nie tak.

**Comment by q3ok** [comment]
problem był chwilowy, chciałem wygenerować na świeżo etykietę i zadziałało wszystko poprawnie, niestety nie mam zapisanych uuid dla transakcji które zakończyły się etykietą z błędem, mogę jedynie podać trzy numery przesyłek które przy pobieraniu etykiet (w tym wypadku przez aplikację webową) zwracają tak jak na samym początku kod etykiety zawiera na początku "PK" i znaki specjalne.

**Comment by MaciejFrackowiak** [comment]
@q3ok OK, jeśli problem powróci proszę daj nam znać z przykładowym commandId.
