### ISSUE TITLE
Problem z pobraniem statusu parcel-pickup

### ISSUE THREAD

**Issue by cieplik206** [allegro/allegro-api#6328]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Po utworzenu zlecenia podjazdu za pomocą endpointa /parcel-management/parcel-pickup-request-commands/{commandID} zlecenie tworzy się poprawnie, dyspozytor u was widzi zlecenie, wszystko działa, ale nie da się pobrać statusu po zmianach ID usług, 

mianowicie odpytując endpoint:

/parcel-management/parcel-pickup-request-commands/e173a7a0-60cf-11ed-b528-df008739e362

dostaje odpowiedź 

`
{
    "errors": [
        {
            "code": "ERROR",
            "message": "Command doesn't exist",
            "details": null,
            "path": "/parcel-management/parcel-pickup-request-commands/{commandId}",
            "userMessage": "Komenda nie istnieje"
        }
    ]
}
`

do 8 Listopada wszystko działało poprawnie

**Comment by Pawelpwg** [comment]
jest jakies ETA na rozwiazanie, drugi dzien z rzedu problemy i kliencie stoja

**Comment by MaciejFrackowiak** [comment]
@Pawelpwg Działamy by możliwie szybko wyeliminować ten problem.

**Comment by MaciejFrackowiak** [comment]
@cieplik206 @Pawelpwg Opisany tu błąd został już usunięty.
