### ISSUE TITLE
About store maximum number of active offers

### ISSUE THREAD

**Issue by fxsshiwo** [allegro/allegro-api#6329]
`You cannot publish new offers - your account has exceeded the maximum number 200000 of active offers.`

Is there an interface to obtain the maximum number of quotations that can be published by the store?

I want to control the frequency of publishing after the store reaches this limit

**Comment by MaciejFrackowiak** [comment]
The default value of active offers is 200,000 per single account.

**Comment by fxsshiwo** [comment]
Is the 200000 active offers fixed? 
Will it increase or decrease because of the qualification of the store

**Comment by MaciejFrackowiak** [comment]
Yes, it is fixed for every account.
