### ISSUE TITLE
[REST] Filtrowanie /order/checkout-forms po numerze aukcji

### ISSUE THREAD

**Issue by kiczek** [allegro/allegro-api#633]
Dzień dobry,

chciałbym zgłosić sugestię do procesowania poniższego przypadku w nowym REST API:

_Sprzedawca Allegro zaczyna korzystać z naszego oprogramowania. Potrzebujemy pobrać historyczną listę zamówień z konkretnej aukcji. Przy obecnej formie API musimy przefiltrować cały dziennik w poszukiwaniu zdarzeń dot. wybranej przez Sprzedawcę aukcji._

Czy istnieje możliwość dodania filtrowania po numerze aukcji na zasobie: **/order/checkout-forms**?

**Comment by PawelTaberski** [comment]
Obecnie nie ma możliwości filtrowania po numerze oferty, jednakże możesz zastosować sortowanie po statusie zamówienia i dacie zamówienia. Zgłosiłem Twoją sugestię o dodanie dodatkowego sortowania po numerze oferty do odpowiedniego zespołu. Jeśli zdecydujemy się wdrożyć taką zmianę poinformujemy o tym.
