### ISSUE TITLE
Allegro Product Listing Issue

### ISSUE THREAD

**Issue by SenolGunaydin** [allegro/allegro-api#6330]
Hi, when I try to list Allegro products, I get the following error. Can you help me?

Request:

{
    "productSet": [
        {
            "product": {
                "id": null,
                "name": "Product Test",
                "category": {
                    "id": "78721",
                    "leaf": false,
                    "name": null,
                    "options": null,
                    "parent": null
                },
                "images": [
                    "https://www.***.com/***-40547-10-B.jpg",
                    "https://www.***.com/***-40548-10-B.jpg"
                ],
                "parameters": [
                    {
                        "id": "11323",
                        "valuesIds": null,
                        "values": ["11323_1"],
                        "rangeValue": null
                    },
                    {
                        "id": "201017",
                        "name": "Main Fabric",
                        "valuesIds": null,
                        "values": [
                            "201017_214285"
                        ],
                        "rangeValue": null
                    },
                    {
                        "id": "3946",
                        "name": "Brand",
                        "valuesIds": ["3946_217313"],
                        "values": [
                            "4F"
                        ],
                        "rangeValue": null
                    },
                    {
                        "id": "54",
                        "name": "Size",
                        "valuesIds": ["54_1156976"],
                        "values": [
                            "176-182/40"
                        ],
                        "rangeValue": null
                    },{

                        "id": "451",
                        "name": "Color",
                        "valuesIds": ["451_131072"],
                        "values": [
                            "clear"
                        ],
                        "rangeValue": null
                    },
                                        {
                        "id": "225693",
                        "name": "EAN (GTIN)",
                        "valuesIds": null,
                        "values": [
                            "11323_1"
                        ],
                        "rangeValue": null
                    }
                ],
                "description": null,
                "publication": null
            },
            "quantity": {
                "value": 1
            }
        }
    ],
    "b2b": null,
    "attachments": null,
    "fundraisingCampaign": null,
    "additionalServices": null,
    "delivery": {
        "shippingRates": {
            "id": "7c8ad088-***-4d74-***-c515c3b105a9"
        }
    },
    "publication": null,
    "compatibilityList": null,
    "language": "pl-PL",
    "category": {
        "id": "78721"
    },
    "parameters": null,
    "afterSalesServices": null,
    "sizeTable": null,
    "discounts": null,
    "name": "Product Test",
    "payments": {
        "invoice": "NO_INVOICE"
    },
    "sellingMode": {
        "price": {
            "amount": 5.99,
            "currency": "PLN"
        }
    },
    "location": {
        "countryCode": "PL",
        "province": "***",
        "city": "***",
        "postCode": "**-400"
    },
    "images": null,
    "description": null,
    "external": null,
    "stock": {
        "available": 1,
        "unit": "UNIT"
    },
	"tax": null,
    "messageToSellerSettings": null
}

Response:

 {
    "errors": [
        {
            "code": "ParameterCategoryException",
            "message": "Unprocessable Entity",
            "details": null,
            "path": "productSet[0].product.parameters",
            "userMessage": "The definitions of the parameter `11323:Stan` were incorrectly specified as a parameter in section `product`."
        }
    ]
}

**Comment by MaciejFrackowiak** [comment]
Parameter State in an offer parameter, not a product one. So you should add it to the offer part of the request - in the field "parameters" - please, see [our tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#offer-parameters).

**Comment by SenolGunaydin** [comment]
Hello, how should we find the id of the product for which a new offer will be made.

Thank you

**Comment by MaciejFrackowiak** [comment]
You can use [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts) to browse our product catalogue.
