### ISSUE TITLE
WzA Poczta żabka i Pickup point is incorrect

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#6332]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Nr generowanej paczki : 197669e2-0f7b-4c8d-842b-dcd3620e4bcc.
Na froncie daje sie wygenerować paczkę, dla tego zamówienia

**Comment by PrzemyslawLukanowski** [comment]
Według naszych logów nie przekazujesz żadnej wartości w polu `pickup.pointId` - widnieje tam null. Dla przesyłek Poczty Polskiej nie da się zamówić podjazdu, zatem musisz wskazać odpowiedni punkt nadania.

**Comment by Radeq** [comment]
@PrzemyslawLukanowski , chyba mam podobny problem, czy mógłbyś zerknąć na 

`PUT parcel-management/parcel-create-commands/bf459ee2-442e-4dfc-9bca-d9d37c8a1853 || trace-id:48f0c23f03bdb190`

serwer produkcyjny, podaję pickup.point_id oraz receiver.point_id, punkty widzę jako aktywne.

**Comment by paafcioc22** [comment]
@Radeq sprawdź w ustawieniach zamówień czy masz wybrany urząd pocztowy w szczegółach umowy. U mnie to chyba było powodem błędu.

**Comment by PrzemyslawLukanowski** [comment]
@Radeq Weryfikuję ten problem z zespołem odpowiedzialnym za usługę. Jak tylko otrzymam jakieś wieści, poinformuję w wątku.

**Comment by PrzemyslawLukanowski** [comment]
Otrzymałem informację, że wskazany punkt Żabki nie oferuje nadań, a jedynie odbiory paczek.
