### ISSUE TITLE
Błąd AccessDenied w środowisku testowy podczas pobierania ofert

### ISSUE THREAD

**Issue by pogotowiefiskalne** [allegro/allegro-api#6333]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Endpoint '/sale/offers' zwraca błąd 'AccessDenied'. W ustawieniach aplikacji jest zaznaczone
```
Zarządzanie ofertami
allegro:api:sale:offers:read
```

Przykładowe cURL z request i response:

Request:
```
curl --location --request GET 'https://api.allegro.pl.allegrosandbox.pl/sale/offers' \
--header 'Authorization: Bearer ACCESS_TOKEN....'
```

Response:
```
{
    "errors": [
        {
            "code": "AccessDenied",
            "message": "Access is denied",
            "details": null,
            "path": null,
            "userMessage": "Access denied. Contact the author of the application."
        }
    ]
}
```

Access token jest prawidłowy ponieważ endpoint "/order/checkout-forms" odpowiada prawidłowo:
Request:
```
curl --location --request GET 'https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms' \
--header 'Authorization: Bearer ACCESS_TOKEN....'
```

Response:
```
{
    "checkoutForms": [
        {
....
```

**Comment by PrzemyslawLukanowski** [comment]
Czy na pewno w nagłówku Accept przekazujesz wartość "application/vnd.allegro.public.v1+json"? Jeśli po dodaniu tego nagłówka problem nadal występuje, prześlij proszę przykładowe trace-id.

**Comment by pogotowiefiskalne** [comment]
Ustawienie nagłówka "Accept": "application/vnd.allegro.public.v1+json" rozwiązało problem. Dziękuję za szybką odpowiedź.
