### ISSUE TITLE
Pytanie o limit ofert w /sale/offer-price-change-commands/

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#6334]
Jaki jest limit ilości ofert dla komendy masowej zmiany cen /sale/offer-price-change-commands/?

Można tam wstawić na raz np. 5000 ofert do zmiany ceny?

To się dość często zdarza w momencie np. wahania kursów walut.

**Comment by tztztztz** [comment]
W sumie to i tak nie ma znaczenia, niestety musimy indywidualnie 5000 razy wysyłać dla każdej oferty osobno zapytanie API, bo Wasz system zabrania zbyt dużej zmiany ceny. 

Dlatego jeżeli np. w paczce 1000 ofert jest jedna taka gdzie cena zmienia się o zbyt wielką wartość to wszystko się wysypie. 

Szkoda, że macie takie "zabezpieczenie", to bardzo utrudnia zrobienie jedną komendą API zmian cen w wielu ofertach.

**Comment by PrzemyslawLukanowski** [comment]
Odpowiadając na Twoje pytanie mimo wszystko - limit ofert w jednym żądaniu wynosi 1000.
