### ISSUE TITLE
Po zmianie ID usług, ID usługi umowy własnej odwołuje się w pierwszym członie do nie-allegrowej wersji dostawy

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#6336]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dzień dobry, 
analizuje temat zmian ID usług, jakie zaszły w `/parcel-management/delivery-services`. Rozumiem rozdzielenie na metody dostawy, ale niestety coś tu się srogo nie zgadza.
Dotychczas mój klient korzystał z usługi Allegro Kurier DPD na bazie umowy własnej. Teraz w umowach własnych zawartych w ww. zasobie widzę usługi `Kurier DPD (DPD_umowa_wlasna)` oraz `Kurier DPD pobranie (DPD_umowa_wlasna)`. Jakim cudem po zmianie ID usług zmieniły się przypisane metody dostawy na te "nie-allegrowe"? Cenniki dostaw pozostały takie same, jakie były i teraz są zamówienia mające przypisane metody dostawy, których nie mogę zrealizować ponieważ to nie do nich odwołują się umowy własne dodane do WzA.
Trace-Id: abef8b870570dac8

Zbadajcie to, proszę.
Pozdrawiam.

**Comment by hahyes** [comment]
Odkryłem na własną rękę, że zasób `parcel-management/delivery-services` nie pokazuje usług `Allegro Kurier DPD ...` mimo tego, że one dla danej umowy własnej istnieją i można utworzyć do nich paczkę. Złożyłem ręcznie uuid z metody przesyłki i uuid umowy i to zadziałało. Jednak nadal jest to problemem.
Trace-Id tworzenia paczki: 66b08b5fa94564b1

**Comment by MaciejFrackowiak** [comment]
Konsultuję opisany przez Ciebie przypadek z zespołem, wrócę z odpowiedzią.

**Comment by hahyes** [comment]
@MaciejFrackowiak Dodam, że ten sam problem znalazłem dla metody dostawy `Allegro Punkty Poczta, Żabka`. Nie ma odpowiedniej metody dostawy powiązanej z umową własną.

**Comment by hahyes** [comment]
@MaciejFrackowiak 

>Allegro Kurier DPD i Allegro Kurier DPD pobranie są umowami brokerskimi Allegro i w ramach nich nie można korzystać z umowy własnej.

Z całym szacunkiem. Ja naprawdę rozumiem że Pan jest tylko przekaźnikiem pomiędzy zespołem od WzA i mną, ale to jest po prostu nieprawda. Wasze API nawet się nie zająka po przyjęciu tych metod dostawy z UUID umowy własnej, co udowodniłem powyżej. Więcej, mój klient dzisiaj zapakował dziesiątki paczek i nic się złego nie dzieje. Ponadto udostępniono mi rozliczenia mojego klienta, które obalają to zdanie, ponieważ nie ma tam żadnych waszych rozliczeń dot. korzystania z tych metod dostawy w ciągu ostatnich co najmniej 12 miesięcy.
Dopóki nie rozdzieliliście umów własnych po metodach dostawy, nic i nikt nie protestował ani nie informował mojego klienta o złym wykorzystaniu integracji czy nieprawidłowych pozycjach w cenniku dostaw. Nie wiem, co zespół WzA miał na myśli ale chyba się nie zrozumieliśmy.

>Oczywiście analogiczny schemat obowiązuje dla pozostałych przewoźników.

Więc wyjaśnijcie proszę tę usługę:
ec0e7fff-8233-4869-99ce-fe2b67a7de84#c13274a2-e4e5-4c8c-8919-7eaeeef9099e

A potem jeszcze te:
88f677d9-c125-45e0-bdf0-f965826542a9#c13274a2-e4e5-4c8c-8919-7eaeeef9099e
193d950b-0082-408f-9192-6081e5e7e7e2#c13274a2-e4e5-4c8c-8919-7eaeeef9099e
128e2be0-a2b9-4793-aafd-ec5557273786#c13274a2-e4e5-4c8c-8919-7eaeeef9099e

> które są zwracane dla użytkownika z przykładu.

I jeszcze jedno pytanie dot. tego fragmentu: czy usługi zwracane w tym zasobie są "z przykładu?". To nie jest aktualna lista usług, które mogę wykorzystać? To są przykłady? Proszę o wyjaśnienie, ponieważ nie rozumiem.

**Comment by MaciejFrackowiak** [comment]
Trochę to trwało, ale wracam z odpowiedzią. Co do zasady masz rację, jednak nie jest to właściwe wykorzystanie dostępnych metod dostawy i zasobów WzA. Metody dostawy Allegro XXX Poczta/ Pocztex pobranie są metodami mix  tzn. są to metody, gdzie merchant nadaje przesyłki na umowie własnej i jeżeli zamówienie spełnia kryteria to część kosztów jest refundowana. Przesyłki pobraniowe na umowach Allegro można nadać tylko dla poniższych metod dostawy:
Allegro Kurier DPD pobranie, Allegro Odbiór w Punkcie DPD Pickup pobranie, Allegro Kurier UPS pobranie. Zmiana, którą ostatnio przeprocesowaliśmy jednoznacznie powinna "matchować" usługi WzA wraz z metodą dostawy przekazaną w szczegółach zamówienia. Również zapis z [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/wysylam-z-allegro-narzedzie-do-nadawania-przesylek-bezposrednio-z-konta-E7doGw8VgI1) jednoznacznie wskazuje, które metody nie wymagają umowy własnej, a jednocześnie zapewniają właściwe rozliczanie opłat za te przesyłki.
