### ISSUE TITLE
Sandbox - business account

### ISSUE THREAD

**Issue by KamilKalbarczyk** [allegro/allegro-api#6337]
Witam,

W jaki sposob moge zmienc konto na BusinessAccount w allegro sandbox ?
Nazwa: KamilTest
Wybralem opcje przejdz na konto firmowe, ale w odpowiedzi z API nadal mam wiadomosc o nie posiadaniu business account.

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem i w naszej bazie nie widzę konta o wskazanej przez Ciebie nazwie. Proszę upewnij się co do nazwy konta lub podaj jego userId. Typ konta możesz zmienić w zakładce [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by KamilKalbarczyk** [comment]
![image](https://user-images.githubusercontent.com/47779722/201891913-d65ec241-427d-4dc7-9fc0-c7fb2c1a52d2.png)

**Comment by KamilKalbarczyk** [comment]
client:105709480

Zmienilem typ konta na businessowe recznie, ale dalej dostaje komunikaty:

{"errors":[{"code":"AccessDeniedException","message":"Regular Account (not registered as a Business Account) does not have access to this method.","details":"AccessDeniedException","path":"/sale/offers","userMessage":"Regular Account (not registered as a Business Account) does not have access to this method."}]}

**Comment by MaciejFrackowiak** [comment]
Konto nie zostało jeszcze zweryfikowane jako firmowe, stąd posiadasz ograniczoną możliwość wystawienia ofert. Jak tylko uda się je zweryfikować wrócę do Ciebie z informacją.

**Comment by MaciejFrackowiak** [comment]
Jeżeli chcesz posiadać konto firmowe, które umożliwi wystawianie ofert to musisz wybrać opcję aktywacji sprzedaży w [panelu](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/panel-sprzedawcy) sprzedawcy - obecnie zaznaczyłeś opcję tylko kupowania.

**Comment by KamilKalbarczyk** [comment]
Dziekuje za link. Niestety problemy wystepuja nadal. Probuje wykonac przelew testowy: "Nie mogliśmy wybrać metody weryfikacji. Spróbuj ponownie później."

**Comment by KamilKalbarczyk** [comment]
Udalo sie po kliknieciu przelew tradycyjny. Jestem na procesie weryfikacji.

**Comment by MaciejFrackowiak** [comment]
Twoje konto jest już zweryfikowane jako firmowe.
