### ISSUE TITLE
parcel-create-commands komenda nie istnieje

### ISSUE THREAD

**Issue by akxx87** [allegro/allegro-api#6338]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Przy próbie sprawdzenia statusu wygenerowanej przesyłki otrzymuję komunikat "Komenda nie istnieje"

[errors] => Array
                (
                    [0] => stdClass Object
                        (
                            [code] => ERROR
                            [message] => Command doesn't exist
                            [details] => 
                            [path] => /parcel-management/parcel-create-commands/{commandId}
                            [userMessage] => Komenda nie istnieje
                        )

                )

**Comment by MaciejFrackowiak** [comment]
Opisany tu błąd został już wyeliminowany.

**Comment by akxx87** [comment]
Problem dalej występuje.
body: {
errors: {
0: {
code: "ERROR",
message: "Command doesn't exist",
details: "",
path: "/parcel-management/parcel-create-commands/{commandId}",
userMessage: "Komenda nie istnieje"
}
}
},

**Comment by MaciejFrackowiak** [comment]
Proszę podaj przykładowe traceId wywołania lub commandId przesyłki.

**Comment by akxx87** [comment]
commandId f1d90ed9-0e95-4399-b1a5-522b7ec52a5e

**Comment by MaciejFrackowiak** [comment]
Jak widzę dla podanego commandId otrzymałeś inny komunikat - "Nieprawidłowa treść żądania JSON" z błędem 400. W requeście przekazałeś serviceId nie jako pole string i to spowodowało błąd.
