### ISSUE TITLE
GET product-offers - brak pustej tablicy "productSet.product.images" mimo, że tak było wystawione

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#6339]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Testowane na sandboxie. Nie sprawdzałem na produkcji.

Wystawiam ofertę przez POST product-offers z pustą tablicą "productSet.product.images" i z wypełnionym "images" - wg dokumentacji oznacza to, że chcę mieć swoje zdjęcie a nie zdjęcie produktowe. Robię potem na tej ofercie GET product-offers (trace-id: abb3fbdd7ffa6c14). Nie mam w odpowiedzi w ogóle "productSet.product.images". A powinienem dostać tam pustą tablicę bo teraz próbując tworzyć funcjonalność "Wystaw podobną" i kopiując odpowiedź z GET'a do POST'a dostaję nową ofertę z dwoma zdjęciami (moim i produktowym) a nie z jednym. 

P.S.
Zauważyłem jednak, że jakoś jest to obsłużone na sandboxie robiąc ręcznie z panelu www "Wystaw podobną". Otrzymuję wtedy prawidłowo skopiowaną ofertę z jednym zdjęciem. Może tam jest to jeszcze robione przez sale/offers a nie sale/product-offers?

**Comment by PrzemyslawLukanowski** [comment]
To zachowanie jest zgodne z [dokumentacja](https://developer.allegro.pl/documentation#operation/createProductOffers), w której nie wskazujemy tego pola wśród zwróconych informacji. Przekazałem do zespołu odpowiedzialnego za usługę prośbę o weryfikację, czy będą mogli dodać takie pole przed wygaszeniem zasobów /sale/offers. Po zbadaniu sytuacji i otrzymaniu odpowiedzi wrócę z informacją.
