### ISSUE TITLE
[REST] dane kupującego przy statusie BOUGHT

### ISSUE THREAD

**Issue by kuli-g** [allegro/allegro-api#634]
Taka sytuacja, 
Kupujący dokonuje zakupu ale nie wypełnia formularza, w dzienniku zdarzeń mam wpis, pobieram dane poprzez order/checkout-forms/ID i dostaję podstawowe dane o zakupie i tylko adres email i numer telefonu kupującego.

Gdzie mam szukać reszty danych?

Dopiero po wypełnieniu formularza (FILLED_IN) pełne dane się pokazują, jednak często kupujący nie wypełnia formularza bo coś-tam i prosi mailowo/telefonicznie o pchnięcie zamówienia do wysyłki, wolałbym w takich sytuacjach mieć już adres.

Poza tym zwracanie tylko adresu wysyłkowego to moim zdaniem błąd, formularz powinien zawsze zwracać dane kupującego, a jeśli formularz dostawy został wypełniony to również dane wysyłkowe.

**Comment by PawelTaberski** [comment]
Zdarza się, że kupujący nie uzupełnia danych dotyczących zakupu, jeśli nie uzupełni takich danych w celu realizacji zamówienia polecamy skontaktować się z kupujących. Nie możemy w takim wypadku wysyłać adresu przypisanego do konta, bo wielu kupujących podaje inne adresy do wysyłki niż ten przypisany do konta. Dlatego jeśli nie otrzymamy od kupującego konkretnych informacji na kogo i na jaki adres ma być nadana paczka nie możemy w jego imieniu podejmować takich decyzji.

**Comment by kuli-g** [comment]
Dziwne podejście, w starym API jest metoda pobierająca dane kupującego, na maila przychodzi wiadomość z danymi kupującego w obu przypadkach nawet jak kupujący formularza nie wypełni do dane są dostępne. Dlaczego w REST jest takie ograniczenie? Skoro ktoś kliknął KUP TERAZ to zgodził się na udostępnienie swoich danych, jeśli już jest takie ograniczenie to usuńcie możliwość zakupu przez KUP TERAZ i zostawcie tylko koszyk, wtedy kupujący czy chce czy nie formularz uzupełnić musi.

To chociaż wnoszę o dodatkową metodę zwracającą dane kupującego dla danego zakupu tak samo jak w starym API

**Comment by TimothyKoval** [comment]
@kuli-g A co jeżeli kliknę kup teraz, Ty wyślesz mi towar na domyślne dane, a ja następnego dnia wypełnię formularz? Prawda jest taka, że utworzenie "aktu zakupowego" powinno z miejsca wymagać podanie danych.

**Comment by PawelTaberski** [comment]
Zrezygnowaliśmy z tego podejścia ze względu na to, że wielu użytkowników ma podane nieprawidłowe bądź stare dane adresowe. Aby poprawnie zrealizować takie zamówienie zachęcamy do skorzystania z otrzymanych danych kontaktowych i skontaktowanie się z kupującym.

**Comment by kuli-g** [comment]
@TimothyKoval Twój argument jest inwalidą, nie wyślę towaru jeśli ktoś nie wypełni formularza bo nie wiem czym i gdzie, chodzi mi po prostu o przejrzystość, a tak to w REST mam w bazie co kilka wpisów pusty wiersz bo api nie zwraca danych. Po drugie bez danych kupującego nawet nie wiem o co mam pytać jak ktoś dzwoni. Po trzecie pisałem że już lepiej niech zrezygnują z KUP TERAZ to nie będzie problemu z danymi

@PawelTaberski Niepotrzebnie komplikujecie życie sprzedającym, każdy przyzwoicie napisany program rozróżnia adres wysyłkowy od adresu użytkownika, jeśli ktoś wpisuje adresy ręcznie i się myli to raczej API używać nie będzie, a jeśli kupujący ma nieaktualny adres to jego sprawa, to nie jest powód do takich ograniczeń API. Zgodnie z regulaminem Allegro dane mają być prawidłowe i aktualne, zachęcacie więc do łamania regulaminu.

**Comment by PawelTaberski** [comment]
@mack3d Rozumiem Twoje podejście i rzeczywiście w ujęciu przyspieszenia informacji od kupującego jest to ciekawe rozwiązanie w przypadku jak nie uzupełni informacji. Przekazałem sugestię o zwrot takich danych przez REST API. Jeśli podejmiemy jakąś decyzję w tym zakresie poinformujemy o tym.

**Comment by aktywnitu** [comment]
A mnie zmiana się podoba - mniejsze prawdopodobieństwo pomyłek u programistów, brak potrzeby aktualizacji tych danych.

**Comment by kuli-g** [comment]
@aktywnitu tyle że ja pisze jako sprzedawca mający kilkadziesiąt sprzedaży dziennie a nie programista, sam sobie piszę skrypty w php więc mam lepiej, ale to sprzedawca będzie się męczył bo teraz dane są a później ich nagle nie będzie, programista zrobi swoje i rozłoży ręce że więcej allegro nie udostępniło. Zresztą co to za programista że prostego api z dziennikiem zdarzeń nie ogarnie

**Comment by mr-luke** [comment]
@kuli-g Dziennik zdarzeń spoko, brak danych spoko ale niech to będzie w dokumentacji 😄 Wpadłbyś na to, że możesz tych danych nie dostać po lekturze dokumentacji? Poza tym jak się już wprowadza dziennik zdarzeń do API to fajnie, jakby był on synchroniczny. A tym czasem:

> z uwagi na uwarunkowania techniczne, w pojedynczych przypadkach zdarzenia mogą pojawić się w nieoczekiwanej kolejności; to znaczy, że jest możliwość by np. zdarzenie ze statusem READY_FOR_PROCESSING pojawiło się przed FILLED_IN; nie traktujemy tego jako błąd.

To jest takie nie wprost przyznanie się do tego, że "My nie umiemy do końca w API" 🙈 Dochodzi do tego, że programiści (w niektórych przypadkach) muszą "hakować" zachowania API, żeby nie budować dziurawego softu.

@PawelTaberski tak czysto informacyjnie... co to za uwarunkowania techniczne? Jaka to architektura stoi za tym, że synchroniczne akcje zapisują się w dzienniku asynchronicznie?

**Comment by kuli-g** [comment]
@mr-luke oj nie przesadzaj w webapi też miałem sytuacje że czasami zdarzenia z formularzem dostawałem przed zakupem, rzadko bo rzadko ale się zdarzało.  Osobiście uważam REST za dużo prostszy od webapi ale ma dużo braków. Dołożyć tylko dane kupującego, jakiś identyfikator dla inpostu i nawet teraz przechodzę na REST bo nawet działa szybciej od webapi

**Comment by mr-luke** [comment]
@kuli-g z webApi do czynienia nie miałem. Uważam jednak, że zapewnienie synchroniczności w akcjach, które z natury są synchroniczne, nie jest jakimś wielkim wyczynem a ułatwia życie developerom 😉

**Comment by mack3d** [comment]
Jedyny duży problem to brak spójności między webAPI i REST... mimo wszystko że w mailu mamy te informacje połączone.
@mr-luke z tą asynchronizacją też można żyć bez większego kombinowania, przecież w zdarzeniu innym niż Bought mamy wszystkie dane potrzebne - przynajmniej ja tak sobie radzę.

**Comment by PawelTaberski** [comment]
Odnośnie pytania o warunkowania techniczne to cały system mamy rozproszony, mikrousługowy i oparty o eventy. Z tego powodu zdarzenia o zakupach, fodach i płatnościach mogą spływać do dziennika z systemu w rożnych kolejnościach.

**Comment by kuli-g** [comment]
@PawelTaberski dziennik nie jest problemem, asynchroniczność da się przeżyć występuje nie tylko u allegro, ale okrojenie z danych które do tej pory były standardem ponieważ (cytuję) 

> wielu użytkowników ma podane nieprawidłowe bądź stare dane adresowe

uważam za co najmniej mało profesjonalne, w końcu umowa zakupu zawierana jest z osobą która kupuje a nie która paczkę dostaje. Jak ktoś paczki nie odbierze to mam pytać allegro o dane kupującego? Odbiorca paczki powie że on nic nie wie i co mu zrobię, przecież nie on kupował.

**Comment by PawelTaberski** [comment]
Tak, jak napisałem wcześniej z doświadczenia wiemy, że wielu kupujących zamawia paczki na inne adresy niż mają podane w ustawieniach konta. Dlatego jeśli nie ma deklaracji kupującego, że zamawia paczkę na dany adres, to wysyłanie mu w "ciemno" na adres przypisany do konta jest błędne. 
Przykładowo może nie przebywać w godzinach pracy kuriera pod tym adresem. Jednakże rozumiem podejście, że jeżeli kupujący nie podał adresu, to można go zapytać tylko o potwierdzenie adresu, aby przyspieszyć proces i zgłosiłem taką sugestie do odpowiedniego zespołu. Jeśli zdecydujemy się wdrożyć takie rozwiązanie to poinformujemy o tym.

**Comment by kuli-g** [comment]
@PawelTaberski czy to "wysyłanie w ciemno" bez czekania na formularz czy płatność jest takim nagminnym procederem że jest jedynym i głównym powodem wycinania danych? Sprzedaję i kupuję na allegro jakieś 15 lat i jeszcze mi się nie zdarzyło by ktoś mi coś wysłał jak tylko kliknę KUP TERAZ.. dziwne rzeczy się dzieją w allegro...

**Comment by PawelTaberski** [comment]
Tak, jak pisałem przekazałem taką sugestię jeśli zdecydujemy się wdrożyć takie rozwiązanie poinformujemy o tym.

**Comment by mack3d** [comment]
dlaczego przy statusie FILLED_IN nie są zwracane dane kupującego/dane dostawy ??

**Comment by neldh** [comment]
Czy planujecie jakąś zmianę w tym temacie? Dobrze by było znać chociaż imię kupującego w przypadku konieczności kontaktu z nim.

**Comment by PawelTaberski** [comment]
@neldh Jak już kupujący uzupełni formularz dostawy to otrzymujesz jego dane do wysyłki. Przy jakiej metodzie, bądź w którym momencie masz na myśli, że przydałyby się Tobie jakieś dane kupującego?

**Comment by PawelTaberski** [comment]
@kuli-g Rozumiem, pracujemy nad rozwiązanie tego problemu, nieuzupełnionych/niepełnych formularzy dostawy. Twoją sugestię oczywiście przekazałem,

**Comment by aktywnitu** [comment]
> @PawelTaberski za pewnie ma na myśli w momencie kiedy ten formularz nie jest wypełniony. Skoro sprzedający musi się dopraszać o wypełnienie formularza to chociaż warto by było wiedzieć do kogo ma dzwonić, czyli to samo co ja pisałem na początku. Klikanie Kup Teraz bez wypełniania formularza to nie jest wcale śladowy proceder, miesięcznie mam kilkanaście takich a jestem bardzo małym sprzedawcą.

dane kupującego są zawsze. Dane do wysyłki moim zdaniem są poprawnie udostępniane po odnotowaniu płatności / płatności przy odbiorze.

**Comment by kuli-g** [comment]
@aktywnitu dane są zawsze w mailach i webapi, w restapi jakiekolwiek dane chociażby imię i nazwisko pokazują się dopiero po wypełnieniu formularza i nikt nie neguje zasadności udostępniania danych do wysyłki po wypełnieniu formularza tylko braku danych dla zakupów bez wypełnionego formularza. Dla sprzedawców posługujących się tylko restapi takie sprzedaże są można powiedzieć anonimowe, nie wiadomo nawet do kogo dzwonić i czy numer/email są aktualne. Z punktu widzenia prawnego i regulaminu allegro kliknięcie KupTeraz jest już zawarciem umowy zakupu więc nie wiem dlaczego allegro nie chce udostępnić danych kontrahenta.

**Comment by PawelTaberski** [comment]
Tak jak pisałem pracujemy nad poprawą mechanizmu, aby nie było możliwości niewypełnienia fod-a, i Twoją sugestię o danych do kontaktu w przypadku nieuzupełnienia przekazałem. Ale najprawdopodobniej problem się rozwiąże jak już poprawimy proces.

**Comment by neldh** [comment]
Adres do wysyłki nie musi być przecież wcale adresem kupującego. Nie musi być też adresem na fakturze (no bo przecież mogę sobie zamówić na inny adres niż ten na który mam zarejestrowaną firmę, bo akurat jest mi tak wygodnie).

Tymczasem wy podajecie następujące dane kupującego:
  "buyer": {
        "id": "23123123",
        "email": "user-email@allegro.pl",
        "login": "User_Login",
        "guest": false,
        "personalIdentity": "67062589524",
        "phoneNumber": "+48999999999"
}

A po wypelnieniu przez niego formularza pozakupowego otrzymam także:
  "address": {
          "firstName": "Jan",
          "lastName": "Kowalski",
          "street": "Grunwaldzka 182",
          "city": "Poznań",
          "zipCode": "60-166",
          "countryCode": "PL",
          "companyName": "Allegro.pl sp. z o.o.",
          "phoneNumber": "+48999999999"
        },

No i będę miał też dane na fakture:
    "invoice": {
        "required": true,
   "address": {
          "street": "Grunwaldzka 182",
          "city": "Poznań",
          "zipCode": "60-166",
          "countryCode": "PL",
          "company": {
            "name": "string",
            "taxId": "string"
          },
          "naturalPerson": {
            "firstName": "Jan",
            "lastName": "Kowalski"
          }
}

i oczywiście mógłbym brać sobie imię/nazwisko kupującego z danych faktury, ale te dane są dostępne dopiero po wypełnieniu przez kupującego formularza pozakupowego.

Po prostu uważam, że jak mamy encję buyer i chcemy jakoś obsługiwać klienta, zanim ten wypełni owy formularz, to pasowałoby znać jego imię, żeby w razie kontaktu (np telefonem na +48999999999) odwzwać się do niego np "Dzień dobry Panie Janie"/ "Czy mam przyjemność z Panem Janem", zamiast "Dzień Dobry, czy to nie Pan ma czasem login User_Login na Allegro?"

**Comment by kuli-g** [comment]
@neldh w obecnej chwili tak to wygląda, nie ważne kto kupuje, rest nie zwróci danych kupującego tylko sam adres wysyłki. Jeśli osoba B nie odbierze paczki bo powie że nic nie wie o jakimś zakupie z allegro to osobie A możemy napisać maila co najwyżej, nawet nie wiemy kto to jest.

**Comment by neldh** [comment]
Ano wiem... po prostu starałem się przekazać jeszcze raz na czym polega problem

**Comment by PawelTaberski** [comment]
@neldh Wszystko jest dla mnie jasne po co te dane i taką sugestię przekazałem 👍

**Comment by sbrzezin** [comment]
Dołączam się. Bardzo jest mi potrzebna informacja na temat danych buyer-a w restapi. Jej brak (podczas gdy jest ona dostępna przez webapi i w mailu) jest nieuzasadniona.

**Comment by PawelTaberski** [comment]
Adresów przed tym jak zamówienie będzie miało status READY_FOR_PROCESSING nie planujemy pokazywać. Planujemy dodać w statusie BOUGHT imię i nazwisko, aby ułatwić kontakt z kupującym.
