### ISSUE TITLE
Błędne dane specyfikacji technicznej TecDoc

### ISSUE THREAD

**Issue by lukasczg** [allegro/allegro-api#6340]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X] inny / other

:beetle: **Opis / Description**

**Get search products results**
**https://api.allegro.pl/sale/products?...**

Dzień dobry, 
problem dotyczy produktu Allegro "b0c4f039-7be8-48b7-9c62-3e560eda9236" a konkretnie jego specyfikacji technicznej TecDoc.
W wersji TecDoc 2132 wszystko było ok. Natomiast w wersji 2219 została dodana informacja: 
 "Artykuł uzupełniający / informacja uzupełniająca": ["bez łożyska koła",  "z pierścieniem nadajnika impulsów ABS"] 

Problem polega na tym, że informacja "z pierścieniem nadajnika impulsów ABS" jest błędna. 

Ponadto identyfikator specyfikacji technicznej TecDoc ""951bc9eb-c578-4f0d-abd4-ee2595776023" nie uległ zmianie.
Jest taki sam zarówno dla wersji TecDoc 2132 jak i 2219.

Produkt o którym mowa to tarcza hamulcowa. Marka: "MaxGear", nr katalogowy: "19-1278"
Właścicielem i wyłącznym dystrybutorem marki MaxGear  jest Auto Partner SA. W katalogu AutoPartner w specyfikacji technicznej nie ma informacji o tym, że tarcza wyposażona jest w pierścień ABS. Faktycznie tarcze nie są w niego wyposażone. 

Poniżej  informacja z katalogu AutoPartner (właściciela marki) oraz porównanie specyfikacji technicznej TecDoc w nowej i starej wersji 
https://photos.app.goo.gl/ZWfVCLB7Ab9dLhnd6

**Comment by PrzemyslawLukanowski** [comment]
Problem dotyczy produktu w kontekście całego serwisu, dlatego zgłoś proszę swoją sugestię za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Prośba trafi do odpowiedniego zespołu, który w momencie potwierdzenia zgodności danych, zaktualizuje informacje w produkcie.
