### ISSUE TITLE
Aktywacja konta Allegro sandbox.

### ISSUE THREAD

**Issue by davvtech** [allegro/allegro-api#6341]
Proszę o pełną aktywacje konta w Allegro sandbox o loginie "dawidfogiel".

**Comment by PrzemyslawLukanowski** [comment]
Wygląda na to, że aktualnie mamy problem z aktywacją tego konta - czy w danych konta możesz uzupełnić adres na prawidłowy? Aktualnie zamiast nazwy ulicy widnieje wyłącznie numer.

**Comment by MykhailoPetrenko** [comment]
Witam! Poproszę o aktywacji konta "mpetrenko" w sandbox. Mam włączone dwustopniowe logowanie, zrobiłem przelew na konto (dostałem potwierdzenie), ale nadal mam komunikat, ze musze aktywować konto.

**Comment by PrzemyslawLukanowski** [comment]
@MykhailoPetrenko Czy to na pewno prawidłowy login? Nie posiadamy takiego użytkownika w naszej bazie na Sandboxie.

**Comment by MykhailoPetrenko** [comment]
> @MykhailoPetrenko Czy to na pewno prawidłowy login? Nie posiadamy takiego użytkownika w naszej bazie na Sandboxie.

client:105651641

**Comment by PrzemyslawLukanowski** [comment]
@MykhailoPetrenko Aktywowałem Twoje konto. Jeśli za pomocą tego konta chcesz wystawiać oferty za pomocą API, miej na uwadze, że musisz w takiej sytuacji zmienić jego rodzaj na firmowe. Zrobisz to przez zakładkę [Dane Konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) ("Zmień na firmowe").

**Comment by davvtech** [comment]
> Wygląda na to, że aktualnie mamy problem z aktywacją tego konta - czy w danych konta możesz uzupełnić adres na prawidłowy? Aktualnie zamiast nazwy ulicy widnieje wyłącznie numer.

Niestety nie mogę zmienić danych, ponieważ podczas próby jestem przenoszony na stronę z informacją "Weryfikujemy dane Twojej firmy", proszę o ręczną zmianę i próbę aktywacji.

**Comment by PrzemyslawLukanowski** [comment]
@davvtech Weryfikuję ten przypadek z zespołem odpowiedzialnym za usługę. Ew. możesz założyć nowe konto, podając przy tym pełen adres.

**Comment by m-dn** [comment]
@PrzemyslawLukanowski  Dzień dobry, proszę o aktywację konta w sandbox:  Client:105780872

**Comment by davvtech** [comment]
> @davvtech Weryfikuję ten przypadek z zespołem odpowiedzialnym za usługę. Ew. możesz założyć nowe konto, podając przy tym pełen adres.

Założyłem nowe konto "davv", proszę o aktywację :)

**Comment by PrzemyslawLukanowski** [comment]
@davvtech Aktywowałem Twoje nowe konto.

**Comment by PrzemyslawLukanowski** [comment]
@davvtech Poprzednie konto również udalo się ostatecznie aktywować :)
