### ISSUE TITLE
Czy dla produktu rozpoznanego po EAN mogę zmienić atrybut?

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#6343]
Mam błąd wystawiając produkt po kodzie ean:

```
Wskazany produkt istnieje. Przesłany parametr `Kod producenta` o wartości `1938891478` nie pasuje do parametru produktu `BM0156478-41`. 
```

Chciałbym zapytać również czy jest możliwość wystawiania produktu rozpoznanego po ean, lecz z innym parametrem niż ten z waszej bazy?

**Comment by MartaNowaczyk** [comment]
Jeśli na podstawie parametrów znaleźliśmy pasujący produkt (również EAN), a jakiś parametr się nie zgadza, to pozostaje zgłoszenie błędu w produkcie. W innym wypadku jeśli podasz parametr, który nie pasuje do tych, które w naszym katalogu opisują produkt, dostaniesz błąd.

Ogólne zasady dotyczące katalogu produktów powinny być zgłaszane przez [formularz kontaktowy,](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) bo to ogólne zasady allegro. Dopiero, gdy błąd z API wskazuje, że API nie działa poprawnie, wtedy takie zgłoszenie powinno trafić do nas. Gdy przesyłasz request lub response, podaj również trace-id, aby można było zweryfikować opisany problem.
