### ISSUE TITLE
Aktywacja sprzedaży w sandbox - jak długo trwa? 

### ISSUE THREAD

**Issue by studio-afterglow** [allegro/allegro-api#6344]
Witam
Jak długo czeka się na aktywację sprzedaży? Po wejściu w link "Aktywuj sprzedaż" wyświetlił mi się formularz, który wypełniłam przykładowymi danymi, zrobiłam też symulację przelewu, wyświetlił mi się normalny komunikat. Teraz gdy wejdę na ten link, znów mam wybór banku do przelewu. Jak długo trwa aktywacja sprzedaży w sandbox, nie wiem, czy to normalne, że trwa to jakiś czas, czy to jakiś błąd.
Email, na który założone jest konto: kontakt@studioafterglow.pl

**Comment by MartaNowaczyk** [comment]
Aktywowałam to konto, jednak jest to konto zwykłe. Aby wystawiać oferty przez API, musisz posiadać konto firmowe. Możesz zmienić rodzaj konta w tej [zakładce](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta)("zmień na firmowe") i następnie aktywować sprzedaż. W razie problemów pisz śmiało.

**Comment by studio-afterglow** [comment]
Ok, zmieniłam dane i wypełniłam wszystkie kroki i czekam na aktywacje sprzedaży. Czy to stanie się automatycznie po jakimś czasie?

**Comment by MartaNowaczyk** [comment]
Zweryfikowałam to konto, powinno być w pełni aktywne.

**Comment by MartaNowaczyk** [comment]
W niektórych przypadkach potrzebna jest nasza ingerencja, także gdybyś miała jakieś problemy daj nam znać, a postaramy się przyspieszyć aktywację.

**Comment by studio-afterglow** [comment]
Mimo 24h nadal nie mam aktywnego konta, proszę o aktywację konta w sandbox o loginie Nazwa123

**Comment by MartaNowaczyk** [comment]
Aktywowałam twoje konto zwykłe Nazwa123.

**Comment by studio-afterglow** [comment]
Dziękuję
