### ISSUE TITLE
testowe konto firmowe

### ISSUE THREAD

**Issue by PiotrPiotrP** [allegro/allegro-api#6345]
Witam, mam pytanie potrzebuję konta testowego firmowego żeby sprawdzać czy moja aplikacja działa poprawnie z allegro. Ale nie mam firmy a sandbox chce konto firmowe, czy da się założyć konto firmowe na sandboxie jak się nie ma działalności?

**Comment by MartaNowaczyk** [comment]
Tak, na sandboxie możesz założyć konto firmowe z fikcyjnymi danymi. Pomocne mogą być generatory takich danych jak NIP, REGON, IBAN. Więcej o sandboxie znajdziesz na naszej [stronie](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#srodowisko-testowe).

**Comment by PiotrPiotrP** [comment]
dziękuję, wygeneruję IBAN i zobaczę czy działa, bo tam przelew jest wymagany.
