### ISSUE TITLE
Odblokowanie konta

### ISSUE THREAD

**Issue by PiotrPiotrP** [allegro/allegro-api#6346]
Witam, proszę o odblokowanie konta androbit_seller, płatności zostały dwa tygodnie temu uregulowane.

**Comment by MartaNowaczyk** [comment]
Jesteś pewien, że dostałeś komunikat w stylu "Dziękujemy za dokonaną wpłatę"? Przejdź do zakładki [rozliczeń](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) i ponów proces. Daj znać co masz za komunikat. Przed chwilą sprawdzałam na swoim koncie i przelew mBank przeszedł bez problemu, a po 2 minutach saldo się zaktualizowało.

**Comment by MartaNowaczyk** [comment]
Zgłosiłam to do odpowiedniego zespołu. Konto dzisiaj powinno być odblokowane. Dam jeszcze znać jak to poprawimy.

**Comment by PiotrPiotrP** [comment]
dziękuję

**Comment by PiotrPiotrP** [comment]
Działa, dziękuję.
