### ISSUE TITLE
podpięcie aplikacji

### ISSUE THREAD

**Issue by faran22** [allegro/allegro-api#6347]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dzień dobry nie mogę podpiąć aplikacji w środowisku testowym. Gdy wykonuje zapytanie GET https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=0a0638d1428a45208ed88e57230d9b76&redirect_uri=https://ukryte.pl/allegro/test95.php pojawia się błąd 145c04d8dbe6de82
Client:44292194

**Comment by MartaNowaczyk** [comment]
Client ID, którego użyłeś jest na produkcji, nie na środowisku testowym. Poza tym redirect_uri się nie zgadza. Konto na produkcji pod które podpięta jest ta aplikacja jest kontem zwykłym, a powinno być firmowe. Sprawdź swoje aplikacje:

- [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/),
- [Zarządzanie aplikacjami Allegro Sandbox](https://apps.developer.allegro.pl.allegrosandbox.pl/).

**Comment by faran22** [comment]
Przepraszam pomyłka.
Problem jest dla clientID: 7a62ca0f78d24696aaff4dc6d53be7b5 jest to na środowisku testowym.
Zwracany jest numer błędu: db116de9e4d9ad79

**Comment by MartaNowaczyk** [comment]
Sprawdź proszę czy wpisujesz poprawny redirect_uri, albo podaj pełną ścieżkę wywołania.
