### ISSUE TITLE
 [code] => CheckoutFormNotFoundException

### ISSUE THREAD

**Issue by ButcherFromHell** [allegro/allegro-api#6348]
Hej,

mam problem z pobraniem danych zamówienia allegro.

1) Na naszym koncie allegro jest zamówienie o ID : XXXx

2) Gdy pobieram (dotychczas pobierałem bez problemu - problem występuje od niedzieli tj. od 13/11)  to dostaje response:

```
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => CheckoutFormNotFoundException
                    [message] => Checkout form XXXX not found
                    [details] => 
                    [path] => /order/checkout-forms/XXX
                    [userMessage] => Checkout form XXX not found
                )

        )

)
```

wywołuje:
https://api.allegro.pl/order/checkout-forms/XXX
```

                $url = "https://api.allegro.pl/order/checkout-forms/{XXX}";
                $make_call = callAllegroAPI("GET", $url, $data, $token);
                $response = json_decode($make_call, true);
```
jako response otrzymuje:

`CheckoutFormNotFoundException`

Sprawdziłem i mam zamówienia o tym id widoczne na koncie.
Dotyczy wszystkich zamówień z 13/11.

Będę wdzięczny za wskazówkę,

**Comment by MartaNowaczyk** [comment]
Taki komunikat zwracamy, gdy dany checkoutForm.id nie jest dostępny na danym koncie (np. zamówienie pochodzi z innego konta lub połączono kilka zamówień w jedno z nowym checkoutForm.id). Podaj proszę trace-id takiego wywołania, albo numer tego zamówienia.
