### ISSUE TITLE
Aktywacja konta sandbox - link z email

### ISSUE THREAD

**Issue by troncomputers** [allegro/allegro-api#6349]
Witam.
Czy aktywacja kont sandboxowych nie powinno się odbywać poprzez kliknięcie w link z maila? To jest jakiś sposób zabezpieczeń przed spamowaniem kontami na piaskownicy?

Proszę o aktywację `troncomputers`.

**Comment by MartaNowaczyk** [comment]
Nie widzę takiego konta. Konto powinno być potwierdzone w mailu, który wysyłamy po rejestracji konta. Sprawdź, czy nie trafił do spamu.

**Comment by troncomputers** [comment]
Nie trafił. Poczta wsadziła go do "segretora". Kliknąłem w ten link kilka razy, nie było żadnej informacji na stronie, że aktywne, tylko pokazała się główna strona. Logowanie pokazuje błedny login lub hasło, a przypominanie hasła pokazuje, że nie ma takiego maila... To jak dostałem maila z aktywacją 🤔

**Comment by MartaNowaczyk** [comment]
Możesz spróbować jeszcze raz założyć konto? Jeśli pokazuje błędy dla loginu i hasła oraz brak maila, to wygląda na to, że konto nie jest potwierdzone.
