### ISSUE TITLE
WZA - błąd pobrania etykiet dla listów 

### ISSUE THREAD

**Issue by PiotrTaraszkiewicz** [allegro/allegro-api#6350]
Dzień dobry 
W dniu dzisiejszym zacząłem otrzymywać komunikaty błędu przy pobieraniu etykiet:
{
	"errors": [
		{
			"code": "INTERNAL_SERVER_ERROR",
			"message": "Error during processing request",
			"details": null,
			"path": null,
			"userMessage": "Przekroczony czas przetwarzania żądania"
		}
	]
}

Sam list się tworzy, ale komunikat jest zwracany niezależnie od tego czy to nowy list czy utworzony wcześniej.
Przykłady:
f7241312-bbb5-490c-9671-74a9f971cbf2
4f406dd0-3e86-4ac2-8a28-4e2adc05272b

**Comment by PiotrTaraszkiewicz** [comment]
Dołączam przykład requesta pobrania etykiety:

https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcels/label?parcelId=f7241312-bbb5-490c-9671-74a9f971cbf2&pageFormat=A6

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przykłady - poprawka już wdrożona, powinno być OK.

**Comment by PiotrTaraszkiewicz** [comment]
Dziękuję za poprawkę, potwierdzam że już działa :)
