### ISSUE TITLE
CheckoutForm.payment płatność z kwotą 0.0 dla FILLED_IN

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#6352]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Witam,

Czy dziś około godziny 10:00  zmieniła się w logika w `order/checkout-forms/{id}` dla zamówień ze statusem `FILLED_IN`? Dokładniej to chodzi mi o pole payment, obecnie otrzymuję płatność o wartości 0.0 bez finished_at. O ile dobrze pamiętam to ostatnio nie otrzymałbym obiektu payment

```
    "id" => "6d103c73-64d7-11ed-9d8a-598f439e0a73"
    "type" => "ONLINE"
    "provider" => "PAYU"
    "finished_at" => null
    "paid_amount" => Webcom\Api\Allegro\Rest\Model\Price {#1415
      #container: array:2 [
        "amount" => "0.00"
        "currency" => "PLN"
      ]
    }
    "reconciliation" => null
```

`"GET order/checkout-forms/{id} || trace-id:efeecef4990009d0"`

Jeśli to celowa zmiana to czy mogę założyć, że taka płatność (kwota 0.0, brak finished_at) nie wystąpi dla statusu formularza `READY_FOR_PROCESSING`?

UPDATE:
Dla statusu `CANCELED` również otrzymuję dane w tym formacie, przykład:
`GET order/checkout-forms/{id} || trace-id:ec6a4753fe52ee34`

**Comment by MaciejFrackowiak** [comment]
Weryfikuję sprawę z odpowiedzialnym zespołem, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Jak już pewnie zauważyłeś przywróciliśmy właściwe działanie funkcjonalności. Dodatkowo, wszystkie zamówienia w statusie READY_FOR_PROCESSING przetworzyliśmy ponownie i "poprawiliśmy" niewłaściwe kwoty. Natomiast dla zamówień FILLED_IN i CANCELLED z problematycznego okresu nie dokonamy takiej korekty kwot - nie chcemy naruszyć struktury zamówień, gdy np. pojawi się status RFP po FILLED_IN. Przepraszamy za zamieszanie.
