### ISSUE TITLE
WzA brak paczek w zbiorze po stronie e-nadawcy

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#6353]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Jak w tytule.
Z dziś brakuje ok 30 paczek w e-nadawcy.
przykładowy numer guid: 8acf2a67-310a-41df-884a-a113ba50e570
parcel : 2f939ddb-1ac6-42ed-84de-6c24f7185a3e

**Comment by MaciejFrackowiak** [comment]
W tym wypadku muszę skierować Cię do Poczty Polskiej, który zarządza Elektronicznym Nadawcą - nie mamy tu żadnej możliwości weryfikacji po stronie EN.

**Comment by paafcioc22** [comment]
Do tej pory wszystko było ok. Problem pojawił się w zeszłym tygodniu po Waszej awarii. Przed awarią nie przekazywałem pola pickup.pointId jako id urzędu nadania i wszystko było ok. Po awarii pole musiało zostać uzupełnione i jak widać paczki się generują, ale nie widać ich po stronie poczty.

**Comment by MaciejFrackowiak** [comment]
@paafcioc22 Kwestie związane z działaniem WzA na stronie WWW zgłaszaj proszę poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&subjectId=2d542135-a6d7-474c-a4a1-f96451c8bbc5). Jak wspomniałem wcześniej - my jako Allegro nie mamy wpływu na obsługę przesyłek po stronie Elektronicznego Nadawcy - tu wszelkie ewentualne zmiany musi wykonać Poczta Polska.

**Comment by paafcioc22** [comment]
Problem jednak zdaje się po Waszej stronie. Wcześniej sugerowane było żeby wiązać metody dostawy po nazwie, ale np.
Zamówienie 9a75f350-6525-11ed-adb8-9ffe78354473 metoda Allegro Punkty Poczta, Żabka nie jest już możliwe związanie z umową własną ponieważ tam mamy tylko "Punkty Poczta, Żabka (nazwa umowy)". Być może to jest przyczyna mojego problemu. 
W jaki sposób mogę bezpiecznie wiązać metodę wysyłki którą wybrał klient z tymi pobranymi przez parcel-management/delivery-services?

**Comment by MaciejFrackowiak** [comment]
Metody dostawy Allegro m.in. Allegro Punkty Poczta, Żabka to metody, gdzie operatorem i pośrednikiem jest Allegro - cytując informacje z formularza odpowiedzialnego za cenniki dostawy - "Skorzystaj z atrakcyjnych cen. Nadawaj bez umowy dzięki Wysyłam z Allegro i rozliczaj opłaty bezpośrednio z nami".
Jeżeli chcesz korzystać z własnej umowy to adekwatną metodą wysyłki jest Punkty Poczta, Żabka (pocztex), gdzie jako właściciel umowy wskazany jest "CLIENT", a nie "ALLEGRO" (informacje z GET /parcel-management/delivery-services).

**Comment by paafcioc22** [comment]
Ok, dziękuje. Jeszcze jedna kwestia. Przestały pobierać się nam etykiety ZPL (te z umową ) np. Allegro Kurier Pocztex pobranie. 
parcel c5d3a9ff-7894-4e20-82cd-fda9beb60528.

**Comment by MaciejFrackowiak** [comment]
Proszę doprecyzuj problem z etykietami - czy nie otrzymujesz od nas zwrotki dla GET /parcel-management/parcels/label czy jest to inny problem.

**Comment by paafcioc22** [comment]
Dostaję zwrotkę, pobiera się plik *.zpl, ale jest uszkodzony/błędny - waży ledwie 2kb.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za doprecyzowanie. Weryfikujemy zawartość pliku z dostawcą zewnętrznym, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Otrzymaliśmy odpowiedź od dostawcy - Poczta Polska przekazała nam etykietę w formacie A4 zamiast spodziewanego formatu A6. Po zalogowaniu się na swoje konto w Elektronicznym Nadawcy jest możliwość zmiany formatu etykiety - i to jest obejście tej problematycznej sytuacji.

**Comment by paafcioc22** [comment]
Dzięki
