### ISSUE TITLE
Do you have some C# connector to this API?

### ISSUE THREAD

**Issue by MGabala** [allegro/allegro-api#6354]
Hello, could you please tell me if you have created C# connector to AllegroAPI?

**Comment by MaciejFrackowiak** [comment]
As Allegro we do not provide any connector.

**Comment by MGabala** [comment]
Ok, do you have some examples in C# how to connect to AllegroAPI?

**Comment by MaciejFrackowiak** [comment]
No, we only provide [documentation](https://developer.allegro.pl/documentation/) - may other users from GitHub have examples and can share them with you.

**Comment by MGabala** [comment]
This is bad. You should take care of users and provide some basic examples.
