### ISSUE TITLE
Pobieranie aukcji jako produkty

### ISSUE THREAD

**Issue by innhousepl** [allegro/allegro-api#6357]
Dzień dobry, czy jest możliwość, aby za pomocą REST API pobrać swoje aukcje?
Planuje pobrać aukcje allegro jako produkty do sklepu prestashop, aby później zsynchronizować stany magazynowe.

**Comment by MartaNowaczyk** [comment]
Możesz pobrać wszystkie swoje oferty za pomocą  [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET). Więcej informacji znajdziesz w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-pobrac-moje-oferty-w-rest-api).
