### ISSUE TITLE
WZA - walidacja formy dostawy: pobranie / bez pobrania 

### ISSUE THREAD

**Issue by PiotrTaraszkiewicz** [allegro/allegro-api#6359]
Dzień dobry 
Po zmianie identyfikatorów i nazw umów / usług w WZA wprowadzone zostały osobne pozycje bez pobrania i za pobraniem, p:

Allegro Kurier UPS (0e4c7d59-64b6-4b06-89c3-c1d941506dd0 - UPS)
Allegro Kurier UPS pobranie (199d2a2a-7c90-4ca7-aaf3-c1d941506dd0 - UPS)

Czy wprowadzana będzie walidacja sprawdzająca czy umowa w WZA odpowiada formie dostawy?
W tej chwili nawet jak zamówienie zostało zapisane bez pobrania: 
Allegro Kurier UPS
To można dla niego przygotować list za pobraniem:
"serviceId": "199d2a2a-7c90-4ca7-aaf3-c1d941506dd0",

{
	"id": "0c6aca12-f5f1-4292-930b-3d034c44b704",
	"parcelId": "467e5ddf-419d-4f95-b463-c1988d887956",
	"status": "SUCCESS",
	"errors": []
}

Czy tak już zostanie że użytkownik przez API może  decydować której umowy/usługi użyje?

**Comment by PiotrTaraszkiewicz** [comment]
Analogicznie jest w drugą stronę.
Do zamówienia z pobraniem:
Allegro Kurier UPS pobranie
Można przygotować list bez pobrania:
	"parcelId": "8943d495-e7da-45d9-b6cf-eb385775d7c8",
	"serviceId": "0e4c7d59-64b6-4b06-89c3-c1d941506dd0",

**Comment by hahyes** [comment]
@PiotrTaraszkiewicz Umowy własne w tym zasobie poznasz po tym, że pole `owner` ma wartość `CLIENT` oraz UUID usługi składa się z dwóch członów: `UUID_dostawy#UUID_umowy_wlasnej`.

**Comment by PiotrTaraszkiewicz** [comment]
Używane były umowy predefiniowane Allegro UPS.
Dla umów własnych przyjmuję że klient ma pełne prawo nadać przesyłkę jak chce.

Pytam, bo w naszym przypadku bazujemy na sposobie dostawy określonym w ERP i nie widzimy oryginalnego sposobu dostawy wybranego przez kupującego w formularzu Allegro.
Jeżeli informacja źle zapisze się w ERP to może dojść do sytuacji że przygotowana będzie przesyłka nie pasująca do wybranej w zamówieniu formy dostawy.

Jeżeli nie ma planów walidacji wybranej usługi pod kątem pobrania to postaramy się uczulić na to naszych klientów.

**Comment by MartaNowaczyk** [comment]
@PiotrTaraszkiewicz użytkownik może decydować jakiej usługi użyje, także nie ma tutaj z naszej strony walidacji.
