### ISSUE TITLE
doGetSiteJournalDeals numer transakcji

### ISSUE THREAD

**Issue by methadd** [allegro/allegro-api#636]
Dzień dobry.

Chciałbym za pomocą metody doGetSiteJournalDeals pobrać numer transakcji jednak dealTransactionId nie zgadza się z numerem transakcji który widnieje w menedżerze sprzedaży. Który numer jest faktycznie tym numerem transakcji?

**Comment by kuli-g** [comment]
Możesz podać przykład? Nie korzystam z MS ale możliwe że różnica wynika z zastosowanego API

**Comment by PawelTaberski** [comment]
@methadd  Zgodnie z tym co napisaliśmy w dokumentacji metody [doGetSiteJournalDeals](https://allegro.pl/webapi/documentation.php/show/id,742#method-output).  Numer dealTransactionId jest to identyfikator transakcji, który pobierzesz za pomocą metody [doGetTransactionsIDs](https://allegro.pl/webapi/documentation.php/show/id,121). MS nie korzysta z tego API także są to zupełnie odrębne byty.
