### ISSUE TITLE
parcel-management - API dane przesyłki utworzonej przez panel Allegro

### ISSUE THREAD

**Issue by mack3d** [allegro/allegro-api#6360]
Dzień dobry,
czy istnieje możliwość pobrania wszystkich danych o utworzonej paczce takich jak zwraca:
GET /parcel-management/parcels/{parcelId}
ale nie mając "parcelId".
Mam na myśli sytuacje gdy paczkę utworzymy poprzez panel allegro, a w późniejszym czasie chcielibyśmy poprzez API te dane odczytać, dodam że zasób: GET /order/checkout-forms/{orderId}/shipments nie zwraca wszystkich danych.

M.Krupinski

**Comment by MaciejFrackowiak** [comment]
Nie, nie mamy takiego zasobu. "parcelId" jest niezbędne by pobrać dane przesyłki.

**Comment by mack3d** [comment]
Gdzie mogę zgłosić propozycję wprowadzenia takiej możliwości ?

**Comment by MaciejFrackowiak** [comment]
Swoją sugestię rozwoju zasobów możesz umieścić w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions).
