### ISSUE TITLE
"Delivery Method is not available" dla poprawnego serviceID

### ISSUE THREAD

**Issue by shivson1337** [allegro/allegro-api#6361]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**
Witam,
pojawił się dzisiaj problem z zamówieniem, które próbujemy nadać poprzez WzA.
Klient dokonał zamówienia z formą wysyłki kurierem DPD. W zapytaniu deklarujemy powiązane z nią serviceID,
jednak otrzymujemy informację zwrotną `Delivery Method is not available for this order`.

trace-id tworzenia paczki: 4d93a57fc17d3e41
trace-id pobierania statusu: 4d93a57fc17d3e41

**Comment by MaciejFrackowiak** [comment]
We wskazanym zamówieniu widnieje metoda dostawy Kurier DPD, a zlecenie wysłane zostało na Allegro Kurier DPD.

**Comment by shivson1337** [comment]
Tak, właśnie to zauważyłem. Dziękuję za utwierdzenie.
