### ISSUE TITLE
Weryfikacja aplikacji. 

### ISSUE THREAD

**Issue by MGabala** [allegro/allegro-api#6362]
Witam, chciałbym się dowiedzieć w jaki sposób mogę zweryfikować swoją aplikację? Formularz allegro odesłał mnie tutaj.

**Comment by MartaNowaczyk** [comment]
Rozumiem, że chodzi o weryfikację aplikacji, aby mieć dostęp do GET /offers/listing? Jeśli tak to [formularz](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) to dobra droga i niepoprawnie Cię przekierowano. Jeśli masz na myśli coś innego, podaj więcej szczegółów.

**Comment by MGabala** [comment]
Ok, dzięki. Chodzi o  GET /offers/listing itd
