### ISSUE TITLE
Lista produktów w produktyzacji a kod EAN

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6363]
Zauważyłem, że korzystając z zasobu `/sale/products?phrase=` po otrzymaniu listy z produktami, wśród parametrów nie ma EAN. Wszystkie parametry są zwracane, ale bez EAN, pomimo, że jest uzupełniony i znajduje się przy produkcie.

W przypadku `/sale/products/{productId}` EAN jest widoczny.

Proszę o informację jak w przypadku `/sale/products?phrase=` pozyskać kod EAN. Wykonywanie kolejnego zapytania, aby tylko do uzupełnić o brakujący parametr jest trochę nieekonomiczne pod kątem zasobów.

**Comment by MartaNowaczyk** [comment]
Zgadza się, jednak nie zamierzamy tego zmieniać. Tak jak piszesz musisz odpytać o szczegóły produktu by otrzymać wszystkie dane.
