### ISSUE TITLE
W jaki sposób obliczyć opłaty dla oferty z pakietami wyróżnień

### ISSUE THREAD

**Issue by waliwdenko** [allegro/allegro-api#6364]
Co prawda /pricing/offer-fee-preview przyjmuje strukturę classifiedsPackages, jednak po jej przekazaniu otrzymuę error "Only advertisements can have packages.".
Chciałbym już całkowicie przejść na /sale/product-offers, jednak w tej chwili, bez wystawienia aukcji lub chociaż zapisania jej jako draft nie uzyskam struktury dla offer-fee-preview

Chyba, że coś pominąłem.

Proszę o pomoc.

**Comment by MartaNowaczyk** [comment]
Kalkulator nie zwraca opłat dla pakietów wyróżnień. Dane oferty możesz też pobrać za pomocą [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/getProductOffer).

**Comment by waliwdenko** [comment]
To trochę bez sensu. Zalecacie przejście na endpoint /sale/product-offers, który nie wykorzystuje struktury promotion z danych oferty, tylko wykorzystuje classifiedsPackages do aktywowania wyróżnień. Jednak, gdy przejdziemy na ten endpoint to nie będziemy już w stanie policzyć kosztów z wyróżnieniami, bez zapisywania oferty lub musimy samodzielnie symulować struktruę promotion tylko dla potrzeba kalkulacji oferty (co chyba jednak nie da się przełożyć 1 do 1).

**Comment by MartaNowaczyk** [comment]
Rozumiem, jednak na ten moment nie ma innego rozwiązania. Możesz dodać sugestię lub swój głos w naszej dedykowanej zakładce [Discussions](https://github.com/allegro/allegro-api/discussions).
