### ISSUE TITLE
Sandbox - GET: parcel-create-COMMANDS - Processing error

### ISSUE THREAD

**Issue by artbski** [allegro/allegro-api#6365]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry,
Podczas wywołania endpointa:   /parcel-management/parcel-create-commands/:commandId

otrzymuję response:

{
    "id": "88ec106c-2d8e-4cb4-8167-81c1929cc7c5",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Processing error",
            "details": null,
            "path": null,
            "userMessage": "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."
        }
    ]
}

**Comment by Onixarts** [comment]
> Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.

Przy okazcji, moglibyście nie pisać takich niejasnych komunikatów? **Z kim należy się skontaktować?** Użytkownicy naszych aplikacji czytają takie treści i kontaktują się z... **nami** - no bo w naszym programie widzą taką treść ;).

**Comment by artbski** [comment]
To prawda dzwoni się tam gdzie najłatwiej się dodzwonić... :-) 
Tu sensowniejszym jest podanie komunikatu z "message" a resztę wrzucać do logów.

**Comment by hahyes** [comment]
> Przy okazji, moglibyście nie pisać takich niejasnych komunikatów? **Z kim należy się skontaktować?** Użytkownicy naszych aplikacji czytają takie treści i kontaktują się z... **nami** - no bo w naszym programie widzą taką treść ;).

@Onixarts Choć zgadzam się z prośbą, komunikat definitywnie pochodzi z API WzA, które jest zdaje się poza zasięgiem deweloperów od API dla sprzedawców i im ewentualnie mogą przekazać. Widziałem te same komunikaty na portalu.
