### ISSUE TITLE
Internal system error przy sprawdzeniu statusu paczki.

### ISSUE THREAD

**Issue by gkrupkowski** [allegro/allegro-api#6367]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Za pomocą /parcel-management/parcel-create-commands/ stworzylem paczkę z guid: {684785c1-ed61-45a1-8a56-21704731add2} i otrzymałem 201 Created. Sprawdzenie statusu stworzenia tej paczki z tym guidem zwraca jednak:

{
	"id": "684785c1-ed61-45a1-8a56-21704731add2",
	"parcelId": null,
	"status": "ERROR",
	"errors": [
		{
			"code": "ERROR",
			"message": "Internal system error",
			"details": null,
			"path": null,
			"userMessage": "Wewnętrzny błąd systemu"
		}
	]
}

Mozna jakoś rozszyfrować ten Wewnętrzny błąd systemu?

**Comment by MaciejFrackowiak** [comment]
Jak widzę w szczegółach requestu nie podałeś wymiarów ani wagi paczki.
