### ISSUE TITLE
Aktywacja sprzedaży na testowym serwisie

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#637]
W jaki sposób można aktywować sprzedaż na serwisie testowym?

Cały czas mam komunikat:

"Nie możesz jeszcze sprzedawać.
Poczekaj na weryfikację swoich danych. O jej wyniku poinformujemy Cię e-mailem w ciągu 3 dni roboczych. "

I tak już 3 tygodnie.

**Comment by LukaszKorek** [comment]
Podaj proszę login konta.

**Comment by tztztztz** [comment]
tomek3kropki

**Comment by LukaszKorek** [comment]
Konto aktywowałem.

**Comment by tztztztz** [comment]
Dziękuję

**Comment by LukaszKorek** [comment]
Teraz powinno już być ok. Sprawdź proszę.

**Comment by tztztztz** [comment]
Działa, dzięki.

**Comment by sergot** [comment]
Dziękuję

**Comment by JanPono** [comment]
Same issue propably. Can you activate sprzedaz for account ppp344 ? Thank!

**Comment by PrzemyslawLukanowski** [comment]
> Same issue propably. Can you activate sprzedaz for account ppp344 ? Thank!

Account ppp344 activated.
