### ISSUE TITLE
Aktywacja konta Allegro Sandbox

### ISSUE THREAD

**Issue by m-dn** [allegro/allegro-api#6373]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Proszę o weryfikację konta client:105780872 w środowisku Sandbox.

**Comment by MartaNowaczyk** [comment]
Aktywowałam Twoje konto.

**Comment by m-dn** [comment]
Działa, dzięki!

**Comment by m-dn** [comment]
mógłbym prosić o ponowną weryfikację tak bym mógł zasymulować wypłaty? uzupełniłem dane firmy, które nie były kompletne.

_client:105780872 w środowisku Sandbox_

**Comment by MaciejFrackowiak** [comment]
@m-dn Dokonałem ponownej weryfikacji.
