### ISSUE TITLE
Processing error w trakcie generowania przesyłki

### ISSUE THREAD

**Issue by OskarSw** [allegro/allegro-api#6374]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dzień dobry,
Przy próbie wygenerowania przesyłki (parcel-management/parcel-create-commands) dla jednego z zamówień przy próbie pobrania statusu otrzymujemy odpowiedź:
```
{
  "id": "0b40986b-70ca-43fc-b991-c5cb4f8ce1f5",
  "parcelId": null,
  "status": "ERROR",
  "errors": [
    {
      "code": "ERROR",
      "message": "Processing error",
      "details": null,
      "path": null,
      "userMessage": "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."
    }
  ]
}
```
Proszę o pomoc w identyfikacji problemu, bo sam komunikat niestety niewiele mówi.

**Comment by MaciejFrackowiak** [comment]
Sprawdzam szczegóły zlecenia z zespołem, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Operator zwrócił szczegóły błędu - punkt odbiorcy nie obsługuje przesyłek typu "next day".

**Comment by OskarSw** [comment]
> Operator zwrócił szczegóły błędu - punkt odbiorcy nie obsługuje przesyłek typu "next day".

Co mam w takim przypadku zrobić? Wybieram usługę "Allegro One Box, One Kurier" taką, jaka jest zgodna z metodą wysyłki wybraną przez kupującego. CZy trzeba w takim wypadku zmienić punkt odbioru na inny?

**Comment by MaciejFrackowiak** [comment]
Tak, konieczny jest wybór innego punktu.

**Comment by mmodrzejewski** [comment]
Dzień dobry,

Mam podobny problem u klienta (taki sam, enigmatyczny komunikat dotyczący przesyłki jak u założyciela wątku)

Numer zamówienia:
7e183871-735e-11ed-8ea2-b33b0cc3ddea

ID przesyłki:
ef590f25-ef0f-4e23-a82e-7d4d325a4183

Proszę o wyjaśnienie, czy problem też dotyczy punktu odbioru czy może czegoś innego.

**Comment by OskarSw** [comment]
Dzisiaj u mnie także kolejny taki komunikat - e323f1f3-11e9-44ba-8af0-9924bd16186a

Jeśli to błąd operatora to fajnie by było gdyby api zwracało jego treść.

**Comment by MaciejFrackowiak** [comment]
@mmodrzejewski @OskarSw W obu przypadkach osiągneliśmy tymczasowy limit połączeń. Proszę raz jeszcze złóżcie zlecenia.
