### ISSUE TITLE
Listing?string i 429

### ISSUE THREAD

**Issue by adamz464** [allegro/allegro-api#6377]
Jak się teraz pobiera bez api dane o listingu?
Długie odstępy i ciasteczka nie pomagają. Po jakimś czasie leci 429...

**Comment by MaciejFrackowiak** [comment]
Błąd 429 to zabezpieczenie przed działaniem, które nie wykazuje znamion standardowego użytkownika korzystającego z serwisu WWW. Z naszej strony sugerujemy zaprzestanie tego procederu.

**Comment by adamz464** [comment]
> 
nie dogadamy się. Trzeba było nie zabierać API. Nie masz raczej czego tu szukać w tym temacie.

**Comment by adamz464** [comment]
Nie należy go zamykać

**Comment by PrzemyslawLukanowski** [comment]
Zamykamy temat - nie jest w żaden sposób powiązany z API Allegro.

**Comment by adamz464** [comment]
odmawiam
