### ISSUE TITLE
brak kampanii BLACK WEEK ‑ AlleObniżka

### ISSUE THREAD

**Issue by Sebastian-Le** [allegro/allegro-api#6379]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

zasób GET /sale/badges?offer.id=<offer>

dla oferty biorącej udział w kampanii "BLACK WEEK ‑ AlleObniżka" nie zwraca żadnego oznaczenia, ta sama oferta na froncie widoczna jest z oznaczeniami i obniżoną ceną.

zasób GET /sale/badge-campaigns

z black week zwraca jedynie 
                    [id] => BLACK_WEEK_2022
                    [name] => BLACK WEEK 2022
brak jest natomiast kampanii dla "BLACK WEEK ‑ AlleObniżka"

**Comment by Lukasz-Zurek** [comment]
Problem zgłosiłem do odpowiedniego zespołu.

**Comment by Lukasz-Zurek** [comment]
@Sebastian-Le Wracam z informacją - nie jest to błąd. W naszym API nie można zgłosić oferty do wspomnianej kampanii "BLACK WEEK ‑ AlleObniżka", jak również nie zwracamy jej w odpowiedzi, gdy skorzystasz z GET /sale/badge-campaigns.

**Comment by PLoO95** [comment]
@Lukasz-Zurek, 
Mam podobny problem, w jaki sposób mogę w takim razie pobrać informacje, że oferta jest w podanej kampanii.

Używam bramki: /sale/badges
Cel: Pobranie aktywnych promocji i powiązanie z ofertami. Możliwość filtrowania w programie, po ofertach z aktywnymi promocjami + pokazanie aktualnej ceny

Mam oferty w 
- BLACK_WEEK_2022 -> tutaj jestem w stanie pobrać promocje i powiązać z ofertą
- BLACK WEEK ‑ AlleObniżka -> nie jestem w stanie pobrać takiej informacji

W efekcie nasz program nie widzi ceny promocyjnej ?
Z jakiego zasobu skorzystać, by dowiedzieć się, że oferta jest zakwalifikowana do tego typu promocji ?

**Comment by Lukasz-Zurek** [comment]
@PLoO95 Niestety zespół odpowiedzialny za kampanie nie wdrożył tego typu promocji w naszym API, w związku z czym nie uzyskasz informacji o tym, że oferta jest zakwalifikowana do tego typu promocji.

**Comment by Sebastian-Le** [comment]
@Lukasz-Zurek , to jest celowy podział które kampanie dostępne są w API a które na froncie ?? 
![allegro](https://user-images.githubusercontent.com/82901132/203038973-6622abe0-50ec-469c-88f1-4b6c16eb8bc3.png)

Mamy oferty zgłoszone z poziomu frontu i w żaden sposób nie sposób ustalić w jakiej promocji się znajduje poprzez API
1.) w związku z czym pojawiają się rozbieżności w cenach przy importowaniu zamówień
2.) oferta może zostać szybko usunięta z kampanii zmianą ceny na 'tą która jest ustalona do oferty' 

Nawet jak nie zakładacie możliwości zgłoszenia do kampanii z poziomu API (dziwne, ale ok) to przynajmniej przekazujcie przez API informację o zmianie ceny i opisem 'inna kampania', aby był jakiś ślad z czego wzięła się zmiana ceny.

**Comment by Lukasz-Zurek** [comment]
W pełni Was wszystkich rozumiem. @Sebastian-Le Temat ten konsultuję jeszcze z zespołem od kampanii. Mam nadzieję, że uda się wypracować alternatywne rozwiązanie.

**Comment by Sebastian-Le** [comment]
Na około ale to chyba jedyny ślad udziału w kampanii jaki widzę to informacja po zakupie w zasobie 
GET billing/billing-entries?offer.id=
Sprawdzając billing po typie PS1 i porównując checkOutFormId danego zamówienia z wpisami w billingu do aukcji pozwoli ustalić ile było dopłaty

[type] => 
        (
            [id] => PS1
            [name] => Wyrównanie w programie Allegro Ceny
        )
(...)
[value] => 
        (
            [amount] => 21.00
            [currency] => PLN
        )
(...)
    [order] => 
        (
            [id] => checkOutFormIdUUID
        )

**Comment by Lukasz-Zurek** [comment]
@PLoO95 Nasze API powinno już zwracać:

```
"id": "BLACK_WEEK_ALLEOBNIZKA_2022",
"name": "BLACK WEEK - AlleDiscount",
```
gdy skorzystasz z GET /sale/badge-campaigns.

Sprawdź proszę czy wszystko jest ok w kontekście ofert, które mają takie oznaczenia.

**Comment by Sebastian-Le** [comment]
@Lukasz-Zurek , u mnie prawidłowo już zwraca, tak jak podałeś z GET /sale/badge-campaigns

**Comment by Lukasz-Zurek** [comment]
@Sebastian-Le Ok, dzięki za potwierdzenie.
