### ISSUE TITLE
doAddPackageInfoToPostBuyForm poprzez RESTAPI

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#638]
Dzień dobry,

czy poprzez REST API możliwe jest dodanie informacji o przesyłce do transakcji allegro (odpowiednik doAddPackageInfoToPostBuyForm) ?
Jeśli nie, to na kiedy planujecie dodanie takiej metody do REST API?

**Comment by LukaszKorek** [comment]
Na ten moment nie ma takiej metody, ale na pewno ją dodamy. Terminu nie jestem jednak jeszcze w stanie podać. Zachęcam do śledzenia naszych newsów.

**Comment by aktywnitu** [comment]
A jakiś przybliżony termin np. wrzesień, ten rok, rok 2019?

**Comment by LukaszKorek** [comment]
Przykro mi, ale nie jestem w stanie podać.
