### ISSUE TITLE
Wystawianie ofert w sandboxie z csv

### ISSUE THREAD

**Issue by asteroidnixtaurus** [allegro/allegro-api#6381]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dzień dobry,
ostatnio mam problem z wystawieniem ofert na sandboxie z pliku csv. Po przesłaniu pliku przetwarzanie rozpoczyna się prawidłowo, jednak praktycznie od razu UI informuje o błędach, a w raporcie każda pozycja ma status "Wystąpił wewnętrzny problem". Próbowałem importować mniejsze pliki, ale one także nie przechodziły.

Moja nazwa użytkownika: caxab15090

Plik csv, który próbuję zaimportować:
[bulk-import_v4.1_pl-1.csv](https://github.com/allegro/allegro-api/files/10056099/bulk-import_v4.1_pl-1.csv)

Raport:
[report_pl_ff86dc18-3241-4b9d-ad7c-b08bd28b0c27.xlsx](https://github.com/allegro/allegro-api/files/10056131/report_pl_ff86dc18-3241-4b9d-ad7c-b08bd28b0c27.xlsx)

**Comment by Lukasz-Zurek** [comment]
@asteroidnixtaurus W sprawie procesu wystawiania ofert z pliku napisz proszę poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by asteroidnixtaurus** [comment]
Ok, dziękuję za odpowiedź
