### ISSUE TITLE
Listing Edit 

### ISSUE THREAD

**Issue by SenolGunaydin** [allegro/allegro-api#6382]
Hello,

I am getting an error when I try to update a product that has been released. I am sharing the necessary information.
Can you provide information?

PATCH /sale/product-offers/{offerId} - edit offer

Request;

{
	"productSet": [
		{
			"product": {
				"id": "82**f918-***-4423-***-b5bea**35820",
				"idType": "GTIN",
				"name": "****",
				"category": {
					"id": "254778",
					"leaf": false,
					"name": null,
					"options": null,
					"parent": null
				},
				"images": [
					"",
					
				],
				"parameters": [
					{
						"id": "11323",
						"name": null,
						"valuesIds": [
							"11323_1"
						],
						"values": null,
						"rangeValue": null
					},
					{
						"id": "129309",
						"name": null,
						"valuesIds": [
							"129309_1"
						],
						"values": null,
						"rangeValue": null
					},
					{
						"id": "129314",
						"name": null,
						"valuesIds": [
							"129314_1"
						],
						"values": null,
						"rangeValue": null
					},
					{
						"id": "201017",
						"name": null,
						"valuesIds": [
							"201017_214285"
						],
						"values": null,
						"rangeValue": null
					},
					{
						"id": "201025",
						"name": null,
						"valuesIds": [
							"201025_2505"
						],
						"values": null,
						"rangeValue": null
					},
					{
						"id": "201077",
						"name": null,
						"valuesIds": [
							"201077_2581"
						],
						"values": null,
						"rangeValue": null
					},
					{
						"id": "225693",
						"name": null,
						"valuesIds": null,
						"values": [
							"8683260544280"
						],
						"rangeValue": null
					},
					{
						"id": "3786",
						"name": null,
						"valuesIds": [
							"3786_31"
						],
						"values": null,
						"rangeValue": null
					},
					{
						"id": "451",
						"name": null,
						"valuesIds": [
							"451_2"
						],
						"values": null,
						"rangeValue": null
					},
					{
						"id": "54",
						"name": null,
						"valuesIds": [
							"3806_6"
						],
						"values": null,
						"rangeValue": null
					}
				],
				"description": null,
				"publication": null
			},
			"quantity": {
				"value": 2
			}
		}
	],
	"b2b": null,
	"attachments": null,
	"fundraisingCampaign": null,
	"additionalServices": null,
	"delivery": {
		"shippingRates": {
			"id": "***"
		},
		"handlingTime": null
	},
	"publication": null,
	"publicationUpdate": {
		"status": "ACTIVATE"
	},
	"compatibilityList": null,
	"language": "pl-PL",
	"category": {
		"id": "254778"
	},
	"parameters": [
		{
			"id": "11323",
			"name": null,
			"valuesIds": [
				"11323_1"
			],
			"values": null,
			"rangeValue": null
		},
		{
			"id": "129309",
			"name": null,
			"valuesIds": [
				"129309_1"
			],
			"values": null,
			"rangeValue": null
		},
		{
			"id": "129314",
			"name": null,
			"valuesIds": [
				"129314_1"
			],
			"values": null,
			"rangeValue": null
		},
		{
			"id": "201017",
			"name": null,
			"valuesIds": [
				"201017_214285"
			],
			"values": null,
			"rangeValue": null
		},
		{
			"id": "201025",
			"name": null,
			"valuesIds": [
				"201025_2505"
			],
			"values": null,
			"rangeValue": null
		},
		{
			"id": "201077",
			"name": null,
			"valuesIds": [
				"201077_2581"
			],
			"values": null,
			"rangeValue": null
		},
		{
			"id": "225693",
			"name": null,
			"valuesIds": null,
			"values": [
				"8683260544280"
			],
			"rangeValue": null
		},
		{
			"id": "3786",
			"name": null,
			"valuesIds": [
				"3786_31"
			],
			"values": null,
			"rangeValue": null
		},
		{
			"id": "451",
			"name": null,
			"valuesIds": [
				"451_2"
			],
			"values": null,
			"rangeValue": null
		},
		{
			"id": "54",
			"name": null,
			"valuesIds": [
				"3806_6"
			],
			"values": null,
			"rangeValue": null
		}
	],
	"afterSalesServices": {
		"impliedWarranty": {
			"id": "***",
			"name": "***"
		},
		"returnPolicy": {
			"id": "***",
			"name": "**"
		},
		"warranty": null
	},
	"sizeTable": null,
	"discounts": null,
	"name": "***",
	"payments": {
		"invoice": "NO_INVOICE"
	},
	"sellingMode": {
		"format": "BUY_NOW",
		"price": {
			"amount": 115.99,
			"currency": "PLN"
		},
		"startingPrice": null,
		"minimalPrice": null
	},
	"location": {
		"countryCode": "**",
		"province": "**_***",
		"city": "***",
		"postCode": "***"
	},
	"images": [
		" "
	],
	"description": {
		"sections": [
			{
				"items": [
					{
						"type": "TEXT",
						"text": null,
						"content": "<h2>***.</h2>",
						"url": null
					}
				]
			}
		]
	},
	"external": null,
	"stock": {
		"available": 5,
		"unit": "UNIT"
	},
	"tax": null,
	"messageToSellerSettings": null
}

response;

{"errors":[{"code":"ParameterCategoryException","message":"Unprocessable Entity","details":null,"path":"productSet[0].product.parameters","userMessage":"The definitions of the parameter `11323:Stan` were incorrectly specified as a parameter in section `product`."}]}

Thank you

-->

**Comment by Lukasz-Zurek** [comment]
@SenolGunaydin You're providing 11323 parameter in the product section, in the **productSet.product.parameters** (as a product parameter) which is incorrect.

You should only provide this parameter in the **parameters** section.

Please read more about offer and product parameters in [our guide](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#parametry-ofertowe).

**Comment by SenolGunaydin** [comment]
Hello,
First of all, thank you for your help.
I want to get one more information.
How should it be terminated when the published product is out of stock or the price is 0?

Thank you

**Comment by Lukasz-Zurek** [comment]
You should manage your stock on your own but if you want to finish (or just stop) your offers, you will have to use [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT). You can read more about it in [our guide](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-zakonczyc-oferte).

Please note the fact that the price cannot be lower than 1,00 PLN.
