### ISSUE TITLE
Czy jest możliwość ręcznej zmiany ceny bezpośrednio na portalu Allegro? 

### ISSUE THREAD

**Issue by Agata5991** [allegro/allegro-api#6383]

**Comment by Agata5991** [comment]
Pecyzując temat - firmą którą obsługujemy chce zintegrować ERP XL z Allegro, wiemy ze jest możliwość importu cenników, ale czy jest możliwość aby zmieniać ceny bezposrednio na portalu? Jeżeli tak, to jak wygląda proces?

**Comment by Lukasz-Zurek** [comment]
@Agata5991 Podobnie jak w API Allegro - możesz edytować cenniki dostawy w "Moim Allegro". To pytanie nie dotyczy jednak stricte API, w związku z czym zachęcam Cię do kontaktu poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a22643f3-4fb6-4aaa-ba32-1bd7a6619db6&subjectId=c8ed8df2-243b-4d06-ae79-240c312ea735), lub forum [Allegro Gadane](https://spolecznosc.allegro.pl).

**Comment by Agata5991** [comment]
To inaczej: czy w momencie zmiany ceny ręcznie, API Allegro dostarczy informację do systemu z którym będzie zintegrowane o tej konkretnej zmianie?
