### ISSUE TITLE
Upstream_Service_Timeout

### ISSUE THREAD

**Issue by artbski** [allegro/allegro-api#6384]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Witam, 
PO wywołaniu GET parcel-create-commands otrzymuję poniższy błąd - prośba o pomoc.

{
    "id": "4182d301-6b2f-438d-903f-57fcb0574557",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "UPSTREAM_SERVICE_TIMEOUT",
            "message": "Przekroczony czas przetwarzania żądania",
            "details": null,
            "path": null,
            "userMessage": "Przekroczony czas przetwarzania żądania"
        }
    ]
}

**Comment by AureliuszBrussy** [comment]
Wyjaśniam to z zespołem odpowiedzialnym za te zasoby. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Niestety, jednak błędy te spowodowane są problemami po stronie API Poczty Polskiej.

**Comment by gkrupkowski** [comment]
Proszę o ponowną weryfikację czy na pewno to jest problem poczty polskiej. Ja składam request o OneBoxa, czy ta usługa jest realizowana przez pocztę polską?
Oto guid mojego przykłądowego requestu: {72682b78-8bed-434f-9002-d8708ab0819b}
