### ISSUE TITLE
Problem z wystawieniem oferty z produktem w których brakuje wartość atrybutów.

### ISSUE THREAD

**Issue by Infoserwis-2019** [allegro/allegro-api#6385]
<p>Mam problem z produktami w bazie Allegro, dokładniej rzecz biorąc niektóre produkty nie mają wszystkich atrybutów wymaganych. 
Przykładem takiego produktu jest: 'f4df2923-e743-4ee8-a0a7-1a0a34d0368a' w kategorii o id '251529' | <i>Środowisko produkcyjne.</i></p>
<p>Gdy tworzę ofertę [nową funkcją 'sale/product-offers/'] z tym produktem, zgłasza mi błąd : "Uzupełnij parametry obowiązkowe: Liczba zębów na tarczach, Długość.".</p>
<p>Produkt ten nie ma atrybutów "Liczba zębów na tarczach" [id 248719] i "Długość" [id 227361]. Mimo to że requiredForProduct i required w definicji tej kategorii w obu przypadkach jest na "true".</p>
<p><i>Najprawdopodobniej produkt te zostały dodane, a potem do kategorii w której jest ten produkt zostały dodane nowe atrybuty wymagane.</i></p>
<p>Z tego co wcześniej testowałem nie można było modyfikować wartość atrybutów, które należą do już wcześniej powstałego produktu.</p>
<p>W jaki sposób należy to obsłużyć w funkcji 'sale/product-offers/' ?</p>

<hr>

<p>I have a problem with products, more specifically some products do not have all the required attributes.
An example of such a product is: 'f4df2923-e743-4ee8-a0a7-1a0a34d0368a' in category with id '251529' | production environment.</p>
<p>When I create an offer [with the new function 'sale/product-offers/'] with this product, it gives me an error: "Please complete the mandatory parameters: Number of teeth on the discs, Length."</p>
<p>This product does not have the attributes "Number of teeth on discs" [id 248719] and "Length" [id 227361]. Even though requiredForProduct and required in the definition of this category are both set to "true".</p>
<p>Most likely, these products were added, and then new required attributes were added to the category in which this product is located.</p>
<p>From what I tested earlier, it was not possible to modify the value of attributes that belong to an already created product.</p>
<p>How should this be handled in the 'sale/product-offers/' function?</p>

**Comment by AureliuszBrussy** [comment]
Mogą zdarzyć się produkty, które nie mają uzupełnionych wszystkich parametrów obowiązkowych - to zupełnie standardowa sytuacja. Brakujące parametry przekaż po prostu w obiekcie product. 

Inną sytuacją jest próba nadpisywania zdefiniowanych już wartości parametrów podstawowych produktu. W takich przypadkach możliwe jest tylko zasugerowanie zmiany w produkcie za pomocą [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation#operation/productChangeProposal).

**Comment by Uriziel01** [comment]
@AureliuszBrussy  Czy po użyciu endpoint'a change-proposals produkt którego wcześniej nie dało się wystawić (parametr odcień ma w produkcie błędną wartość, niezgodną z wymaganym parametrem kolor) to czy wystawienie powinno być możliwe natychmiastowo? Czy też należy zaczekać aż ręcznie rozpatrzona zostanie sugestia zmiany w produkcie?

**Comment by AureliuszBrussy** [comment]
Nie gwarantujemy, że zmiana zostanie naniesiona natychmiastowo - zgłoszenia rozpatrywane są w ciągu 2 dni roboczych. Możesz sprawdzić status sugestii: [GET /sale/products/change-proposals/{changeProposalId}](https://developer.allegro.pl/documentation/#operation/getProductChangeProposal).

**Comment by Uriziel01** [comment]
Tak tak, to że proces jest asynchroniczny opisane zostało w dokumentacji. Pytanie brzmiało bardziej - czy blokuje to na czas rozpatrywania (te przykładowe 2 dni) możliwość wystawienia takiej aukcji? Czy po złożeniu sugestii zmiany można będzie taki produkt jednak wystawić? Przepraszam jeżeli wcześniej niejasno opisałem problem 😄

**Comment by AureliuszBrussy** [comment]
Produkt możesz użyć, jednak dopóki nie zaakceptujemy poprawki - wciąż będziesz musiał wykorzystać wartości parametru zapisaną aktualnie w produkcie (o ile jest to parametr, którego wartości nie możesz zmienić/pominąć). Po zaktualizowaniu produktu, musiałbyś także zaktualizować dane w ofercie.

**Comment by Uriziel01** [comment]
Czyli jeżeli produkt jest uszkodzony, posiada wykluczające się wartości parametrów tym samym generując błąd podczas próby wystawienia (np. produkt `d9055ed0-5636-47c6-aa70-31c2767c5d9` który posiada kolor i odcień które się dosłownie wykluczają) to aż do czasu zaakceptowania blokuję to efektywnie możliwość jego użycia.

**Comment by AureliuszBrussy** [comment]
Tak, potwierdzam, może zdarzyć się taki przypadek.
