### ISSUE TITLE
Pytanie o różnice między zdjęciami produktowymi a ofertowymi, a ich potencjalne restrykcje.

### ISSUE THREAD

**Issue by AdrianeZ** [allegro/allegro-api#6386]
Jak wiadomo zdjęcia mogą być 'produktowe' -> powiązane z danym produktem np. przy wystawianiu oferty z produktem kiedy chcemy utworzyć nowy produkt (nie powiązać wystawianej oferty z istniejącym) zdjęcia w requescie z pola product.images oraz ofertowe -> dołączone dodatkowo albo zamiast kiedy w polu product.images przekażemy pustą tablicę. Ta kwestia jest dla mnie  jasna, moje pytania się pojawia np. mamy produkt A - wystawiamy ofertę z produktem POST /sale/offers  zakładamy że jest to nowy produkt utworzony razem z ofertą, oraz mamy produkt B (są to np. bliźniacze produkty ale różniące się załozmy jakims parametrem) - który już istnieje w requescie w zasobie POST /sale/product-offers przekazujemy jego uuid do pola product.id, zaciągają się zdjęcia z katalogu w produkcie B domyślnie (nie przekazujemy pustej tablicy w product.images) czy mogę teraz użyć dodatkowo w tablicy images zdjęcia z produktu A? Czy są z tym związane jakieś restrykcje, założmy nawet że produkt A utworzył inny użytkownik.
Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
Czy chodzi Ci o skorzystanie z tych samych url pobranych z pola productSet.product.images z produktu A w produkcie B (nowo utworzonym)? Możesz to zrobić, nie ma tutaj restrykcji.

**Comment by AdrianeZ** [comment]
Chodzi mi bardziej o to czy moge mając produkt A (dodany przez innego użytkownika który ma swoje zdjęcia). Wystawić ofertę z produktem B już istniejącym i do tej oferty poza zdjęciami które się zaciągną auotmatycznie albo nie (w zależności czy ustawie product.images na pustą tablicę kiedy podam indentyfikator produktu) dołączyć także zdjęcia z produktu A w tablicy images ['urlZProduktuA']

**Comment by AureliuszBrussy** [comment]
Tak, nic nie stoi na przeszkodzie, aby tak zrobić.

**Comment by AdrianeZ** [comment]
Czyli rozumiem że nic nie stoi na przeszkodzie żeby korzystać ze zdjęć np. z zasobu /sale/products/{productId} gdzie mogę zobaczyć zdjecia przypisać je do ew. nowo tworzonych produktów lub nawet wykorzystywać je jako 'moje zdjęcie' które przekazuje w tablicy images. Jest to zgodne z regulaminem?

**Comment by AdrianeZ** [comment]
@AureliuszBrussy - dziękuje za opdowiedzi, mam nadzieje trochę prostsze ostatnie pytanie ;) - jest możliwość kiedy wiąże ofertę z istniejącym produktem mam dwie opcje pierwszą (domyślna) podać tylko uuid lub EAN aby zaciągnąć wszystkie zdjecie do oferty z produktu drugą dodać w requescie productSet.product.images = [], aby zabronić ładowania zdjęć z produktu, a czy mogę mieć jakieś swoje zdjęcia i dołożyć tylko wybrane jedno czy dwa (nie wszystkie i nie żadne) do oferty z produktu A. Np. przesłac w tablicy images ['url1', 'url2', 'url3', 'urlZProduktuA', 'drugiUrlZProduktuA'].

**Comment by AureliuszBrussy** [comment]
Tak, możesz tak zrobić i zdecydować, które zdjęcia z produktu chcesz w ofercie umieścić.
