### ISSUE TITLE
WzA - problem przy generowaniu przesyłki

### ISSUE THREAD

**Issue by Kuba-Id** [allegro/allegro-api#6387]
Klient w zamówieniu wybrał jako sposób dostawy: "Allegro One Kurier - dostawa jutro" - przeklejam dokładnie co do literki.

Do wygenerowania listu przewozowego z zwróconej listy przewoźników wybrany został przewoźnik z ID: **01d3468e-42af-474d-b06c-9a2f986f2ec3**:

`Object
(
    [id] => 01d3468e-42af-474d-b06c-9a2f986f2ec3
    [service] => X_PRESS_COURIERS
    [name] => Allegro One Kurier - dostawa jutro (X_PRESS)
    [owner] => ALLEGRO
    [carrierId] => X_PRESS_COURIERS
    [additionalServices] => stdClass Object
        (
            [cashOnDelivery] => stdClass Object
                (
                    [available] => 
                    [expressAvailable] => 
                )
            [options] => Array
                (
                    [0] => stdClass Object
                        (
                            [name] => additionalHandling
                            [description] => Paczka niestandardowa.
                        )
                    [1] => stdClass Object
                        (
                            [name] => sameDay1822
                            [description] => Dostawa tego samego dnia, co odbiór od nadawcy.
                        )
                    [2] => stdClass Object
                        (
                            [name] => nextDay1822
                            [description] => Dostawa następnego dnia, po dniu odbioru od nadawcy.
                        )
                )
        )
)`

Dane przekazywane w Requeście:

`Array
(
    [serviceId] => 01d3468e-42af-474d-b06c-9a2f986f2ec3
    [receiver] => Array
        (
            [address] => Array
                (
                    [street] => Bobrowiecka 11a m ***
                    [postCode] => 00-728
                    [city] => Warszawa
                    [countryCode] => PL
                )
            [email] => ***@allegromail.pl
            [name] => ***
            [phone] => ***
        )
    [pickup] => Array
        (
            [address] => Array
                (
                    [street] => ***
                    [postCode] => 61-007
                    [city] => Poznań
                    [countryCode] => PL
                )
            [email] => ***
            [name] => ***
            [company] => ***
            [phone] => ***
        )
    [items] => Array
        (
            [0] => Array
                (
                    [weight] => Array
                        (
                            [value] => 1
                            [unit] => KILOGRAM
                        )
                    [dimensions] => Array
                        (
                            [height] => Array
                                (
                                    [value] => 64
                                    [unit] => CENTIMETER
                                )
                            [width] => Array
                                (
                                    [value] => 41
                                    [unit] => CENTIMETER
                                )
                            [depth] => Array
                                (
                                    [value] => 38
                                    [unit] => CENTIMETER
                                )
                        )
                    [type] => PACKAGE
                    [description] => Akcesoria rowerowe
                    [value] => Array
                        (
                            [amount] => 68.99
                            [currency] => PLN
                        )
                )
        )
    [type] => PACKAGE
)`

W trakcie generowaniu listu przewozowego zwracany jest wyjątek:
`{"code":"VALIDATION_ERROR","message":"Order delivery method: 01d3468e-42af-474d-b06c-9a2f986f2ec3 is not allowed","details":null,"path":"deliveryMethodId","userMessage":"Metoda dostawy jest niedost\u0119pna"}]`

**Metoda dostawy jest niedostępna** - będę wdzięczny za wskazówkę co tutaj jest nie tak, bo totalnie się pogubiłem. Jaką zatem metodę dostawa wybrać?

Metoda: **parcel-management/delivery-services**

Zwraca do wyboru tylko (wklejam całą listę):
- Allegro Kurier UPS
- Allegro Kurier UPS pobranie
- Allegro Odbiór w Punkcie UPS
- Allegro Pocztex Kurier 48
- Allegro Punkty Poczta, Żabka
- Allegro Przesyłka polecona
- Allegro Kurier Pocztex
- Allegro Odbiór w Punkcie Pocztex
- Allegro Automat Pocztex
- Allegro Kurier DPD Austria
- Allegro Kurier DPD Belgia
- Allegro Kurier DPD Bułgaria
- Allegro Kurier DPD Chorwacja
- Allegro Kurier DPD Czechy
- Allegro Kurier DPD Dania
- Allegro Kurier DPD Estonia
- Allegro Kurier DPD Finlandia
- Allegro Kurier DPD Francja
- Allegro Kurier DPD Grecja
- Allegro Kurier DPD Hiszpania
- Allegro Kurier DPD Holandia
- Allegro Kurier DPD Irlandia
- Allegro Kurier DPD Litwa
- Allegro Kurier DPD Luksemburg
- Allegro Kurier DPD Łotwa
- Allegro Kurier DPD Niemcy
- Allegro Kurier DPD Portugalia
- Allegro Kurier DPD Rumunia
- Allegro Kurier DPD Słowacja
- Allegro Kurier DPD Słowenia
- Allegro Kurier DPD Szwecja
- Allegro Kurier DPD Węgry
- Allegro Kurier DPD Włochy
- Allegro Kurier DPD
- Allegro Kurier DPD pobranie
- Allegro Odbiór w Punkcie DPD Pickup
- Allegro Odbiór w Punkcie DPD Pickup pobranie
- Allegro One Kurier - dostawa dzisiaj (X_PRESS)
- Allegro One Kurier - dostawa jutro (X_PRESS)

Z góry dziękuję!

**Comment by Lukasz-Zurek** [comment]
Te dwie ostatnie usługi dostawy planujemy wkrótce usunąć, zgodnie z [moją wypowiedzią w innym wątku](https://github.com/allegro/allegro-api/issues/6244#issuecomment-1310157184).

Tym samym - metody dostawy 01d3468e-42af-474d-b06c-9a2f986f2ec3 i 0ffc08e7-9ef9-4189-adcc-ec6d99f27f02 nie powinny być dostępne.

Jak tylko usuniemy wspomniane metody dostawy, jak i usługi dostawy - poinformujemy o tym fakcie w [aktualnościach](https://developer.allegro.pl/news/).

Przepraszamy za te utrudnienia.

**Comment by Kuba-Id** [comment]
Jak zatem wygenerować temu klientowi przesyłkę? Którą metodę z tej listy wybrać w takiej sytuacji?

**Comment by Lukasz-Zurek** [comment]
@Kuba-Id Powinieneś użyć ostatniej usługi dostawy z przesłanej przez Ciebie listy, czyli 01d3468e-42af-474d-b06c-9a2f986f2ec3 - Allegro One Kurier - dostawa jutro (X_PRESS).

**Comment by Kuba-Id** [comment]
Pogubiłem się. Tylko, gdy ją używam... API w metodzie **parcel-management/parcel-create-commands/** zwraca informację:

Order delivery method: 01d3468e-42af-474d-b06c-9a2f986f2ec3 is not allowed

Opisałem proces w mojej pierwszej wiadomości, hmm... list mi się nie generuje?

**Comment by Lukasz-Zurek** [comment]
@Kuba-Id Podaj proszę commandId do powyższego requestu, lub numer zamówienia.

**Comment by Lukasz-Zurek** [comment]
Dziękuję. Wkrótce wrócę z wyjaśnieniem.

**Comment by Kuba-Id** [comment]
Panie Łukaszu, zły przekleiłem: 9722ca00-68f1-11ed-ac0e-034b845ef919

**Comment by Lukasz-Zurek** [comment]
Ok, nie ma problemu :)

**Comment by Lukasz-Zurek** [comment]
Za pomocą GET /parcel-management/delivery-services - oprócz powyżej wskazanych wyników, powinieneś również otrzymać usługę "Allegro One Kurier - dostawa jutro" o identyfikatorze identycznym co metoda dostawy, czyli 0d83955a-4297-4169-adef-9790d53b11ff. Ten identyfikator powinieneś przekazać podczas tworzenia paczki.

**Comment by Kuba-Id** [comment]
Poszło Panie Łukaszu, dziękuję!
