### ISSUE TITLE
POST - /sale/offers - 503 

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#6388]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam,
 
Dzisiaj mam problemy podczas tworzenia ofert poprzez API otrzymuję taki bład: 
``` {"message":"upstream connect error or disconnect/reset before headers. reset reason: connection termination","details":{"connectionId":5842431},"destination":{"host":"api.allegro.pl","path":"/sale/offers","originalDst":null,"serviceTag":null},"code":"UC"}```

**Comment by Lukasz-Zurek** [comment]
Podaj proszę przykładowe trace-id i doprecyzuj kiedy po raz pierwszy pojawił się ten problem? Jaka jest skala tych błędów?

**Comment by mrezlik** [comment]
Teraz już jest w porządku wszystko :) Wydaje się, że wszystkie wystepiły między godzinami 12:30 a 13:30 :) Problem występował również przy zapytaniu `GET` do `sale/offers`. Niestety z jakiegoś powodu dla wszystkich requestów nie mogę znaleźć trace-id. :)

**Comment by Lukasz-Zurek** [comment]
@mrezlik Ok :) Dzięki za szczegółowe informacje. Gdyby problem się powtórzył - daj proszę znać.
