### ISSUE TITLE
dokumentacja niedostępna na developer.allegro.pl

### ISSUE THREAD

**Issue by waliwdenko** [allegro/allegro-api#6389]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [X] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Po kliknięciu w "DOKUMENTACJA" z menu developer.allegro.pl pojawia się informacja "Ta przestrzeń jest pusta".

**Comment by Lukasz-Zurek** [comment]
Analizujemy ten problem. 

Przepraszamy za utrudnienia.
