### ISSUE TITLE
Dostęp do publicznego API

### ISSUE THREAD

**Issue by MGabala** [allegro/allegro-api#6390]
Witam, proszę o wytyczne co muszę spełnić aby dostać dostęp do funkcji zweryfikowanego API.

**Comment by AureliuszBrussy** [comment]
Czy chodzi Ci o dostęp do [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing)? Jeżeli tak - w kwestiach dotyczących weryfikacji kontaktuj się przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). Jeżeli jesteś w [Programie Partnerskim](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm), napisz do swojego opiekuna. Podstawowe kryteria to udział w Programie VIP lub co najmniej 100 Użytkowników Allegro dla aplikacji.

**Comment by MGabala** [comment]
chodzi mi o dostęp do  `GET /offers/listing? `

**Comment by AureliuszBrussy** [comment]
Tak, tak jak wspomniałem - podstawowe kryteria to co najmniej 100 Użytkowników Allegro w aplikacji lub udział w [Programie Partnerskim](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm). Jeżeli spełniasz jeden z warunków - skontaktuj się z nami za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by MGabala** [comment]
Rozumiem, natomiast ja jestem developerem. Zajmuje się budową rozwiązania dla firmy która korzysta z Allegro i w ten sposób dostarcza produkty do swoich klientów. Co w takiej sytuacji?

**Comment by AureliuszBrussy** [comment]
Jako developer aplikacji możesz potencjalnie spełnić warunek pierwszy, czyli minimalna liczba użytkowników aplikacji. Jeżeli masz bardziej szczegółowe pytania dotyczące weryfikacji - proszę, zadaj je przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by MGabala** [comment]
Ok

**Comment by MGabala** [comment]
Witam, problem w tym, że nie dostaje tam żadnych odpowiedzi a sprawa się ciągnie od tygodnia.

**Comment by AureliuszBrussy** [comment]
Niestety, nie jestem w stanie tego przyspieszyć. Pozostaje oczekiwanie na ostateczną odpowiedź w zgłoszeniu, które założyłeś przez formularz.

**Comment by MGabala** [comment]
Ostatnio trwało to tydzień i dostałem odpowiedź po swoim ponagleniu. To są jakieś żarty.

**Comment by MGabala** [comment]
Już złożyłem skargę w tej sprawie.

**Comment by MGabala** [comment]
Mam jeszcze pytanie odnośnie samych restrykcji dostępowych. Skąd taki pomysł? Np. dużo większe serwisy finansowe - binance.com bez problemu udostępniają swoje API. Skąd takie cyrki z wami (Allegro)?

**Comment by AureliuszBrussy** [comment]
Zdecydowaliśmy się wprowadzić dodatkową weryfikację dla zasobu `GET /offers/listing` aby chronić dane dot. sprzedaży dostępne w ramach platformy (np. popularność ofert), w tym dane pochodzące od sprzedających, przed nieuprawnionym ujawnieniem podmiotom trzecim, spoza platformy.

Dodam, że wszystkie inne publiczne endpointy, które udostępniamy **nie wymagają** takiej weryfikacji, także możesz z nich korzystać swobodnie, wystarczy, że [zarejestrujesz aplikację](https://apps.developer.allegro.pl/). `GET /offers/listing` to jedyny zasób, dla którego prowadzimy weryfikację.

**Comment by MGabala** [comment]
Przecież oboje wiemy, że to nie chroni Allegro przed tym aby takie dane mogły być zaciągnięte. Rozumiem. Czekam na odpowiedź mailową.

**Comment by MGabala** [comment]
Czy jak prowadzę sprzedaż dla swoich klientów, a oni korzystają z mojej aplikacji zamiast z allegro, to też się kwalifikuje do otrzymania takiego dostępu?

**Comment by Lukasz-Zurek** [comment]
@MGabala Nie znam niestety dokładnych warunków kwalifikacji, ponieważ jako zespół wsparcia API - nie bierzemy w tym udziału. Najlepiej będzie jak dopytasz o te kwestie w toku trwającej korespondencji dotyczącej weryfikacji aplikacji.
