### ISSUE TITLE
WZA - Wybrany punkt DPD Pickup odbiorcy jest nieaktywny

### ISSUE THREAD

**Issue by Sebastian-Le** [allegro/allegro-api#6391]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Przy zgłaszaniu paczki do punktu wybranego przez klienta, "pointId":"PL13629"

{"id":"58de5db0-2b60-4a34-b1f3-790dd45839da","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Receiver point is inactive","details":null,"path":"receiver.pointId","userMessage":"- Wybrany punkt DPD Pickup odbiorcy jest nieaktywny"}]}

{"id":"9ab490b8-055d-410c-9c38-a09d4ac473f0","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Receiver point is inactive","details":null,"path":"receiver.pointId","userMessage":"- Wybrany punkt DPD Pickup odbiorcy jest nieaktywny"}]}

2x próbowaliśmy, otrzymujemy tą samą zwrotkę
trace-id: 346afcddeb8f1212
trace-id: e0e67949287ea53a

**Comment by AureliuszBrussy** [comment]
Błąd zwróciło API przewoźnika. Widzę, że w dniach 11.11-25.11.2022 punkt ten jest nieczynny z powodu urlopu.

**Comment by Sebastian-Le** [comment]
Czemu wyświetlacie do wyboru dla klientów punkty, które możecie zweryfikować że są niedostępne ?

22.11 klient wybrał punkt niedostępny od 11.11, czyli nawet raz na 10 dni nie odświeżacie listy dostępnych punktów, logiczne by było ich odświeżanie przynajmniej 1 raz dziennie aby wyeliminować takie sytuacje.

Teraz niedobry sprzedawca będzie pisał do klienta 'że nie może (czytaj nie chce/nie potrafi)' wysłać paczki do jego wybranego punktu.

**Comment by AureliuszBrussy** [comment]
Dostępność punktów jest przez nas pobierana bezpośrednio od przewoźników. Dane aktualizujemy kilka razy dziennie. Wygląda na to, że w momencie składania zamówienia przez Kupującego - punkt w API przewoźnika był wciąż dostępny.

**Comment by Sebastian-Le** [comment]
A sprawdziłeś co pokazuje wasz system ?

Stan na 23.11.2022 12:36 w allegro:

![dostepnoscDPDallegro](https://user-images.githubusercontent.com/82901132/203537178-bc8e68d3-e65a-4d1c-85c9-2100800392fd.png)

a w DPD
![dostepnoscDPD](https://user-images.githubusercontent.com/82901132/203537190-53da5b17-974b-4d3f-90d8-8805c1a7a242.png)

**Comment by AureliuszBrussy** [comment]
@Sebastian-Le dzięki za zrzuty. API dostawy zwracane ten punkt jako aktywny - wygląda to na jakiś błąd. Zgłosiłem to, jestem w trakcie wyjaśniania.
