### ISSUE TITLE
waga obrazu

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#6392]
Przepraszam, nie mogę znaleźć informacji jakie są limity wagowe obrazków przy dodawaniu przez api Allegro. Wszędzie w opisach widzę ograniczenia co do ilości, ale nie co do wagi.
2 mb
2 gb
100 gb
moze byc?

**Comment by Lukasz-Zurek** [comment]
Maksymalna rozdzielczość to 2560x2560 pikseli, natomiast waga nie może przekroczyć 26,2 MB. Możesz wgrać zdjęcia o maksymalnej rozdzielczości 26 Mpix.
