### ISSUE TITLE
Sandbox cannot create applications

### ISSUE THREAD

**Issue by He79** [allegro/allegro-api#6393]
why sandbox cannot create applications?
![image](https://user-images.githubusercontent.com/69881314/203542573-3286f80d-a467-4f73-b722-6ff208f6fe99.png)

**Comment by Lukasz-Zurek** [comment]
You can create new applications on the Sandbox via this site: https://apps.developer.allegro.pl.allegrosandbox.pl

**Comment by Lukasz-Zurek** [comment]
@He79 Could you give me a trace-id for product-proposals request? The trace-id: 91b0b3f224c94175 which you have just sent refers to GET /sale/categories/{categoryId}/parameters where you did get 200 response status.

**Comment by He79** [comment]
HttpResponseProxy{HTTP/1.1 403 Forbidden [expires: 0, cache-control: no-cache, no-store, max-age=0, must-revalidate, x-xss-protection: 1; mode=block, pragma: no-cache, x-frame-options: DENY, trace-id: de1c513cc08da73e, date: Thu, 24 Nov 2022 07:05:03 GMT, x-content-type-options: nosniff, strict-transport-security: max-age=31536000 ; includeSubDomains, content-type: application/json; charset=UTF-8, content-length: 126] ResponseEntityProxy{[Content-Type: application/json; charset=UTF-8,Content-Length: 126,Chunked: false]}}

**Comment by He79** [comment]
@Lukasz-Zurek I see that there are people who have the same problem as me, but the authentication method they choose is different from mine. I choose Authorization Code Flow to verify my identity

**Comment by Lukasz-Zurek** [comment]
@He79 The problem was with your sandbox account - where you were authorized. This account has not been verified. I have just activated it and verified as a company :) So please try again, it should work now.

**Comment by He79** [comment]
thank you

**Comment by He79** [comment]
Hello, I'm asking two questions,

1 When I upload a new product, do I have to upload the product first and then the price, or can I upload it at the same time

2. I don't understand how you combine multiple varieties. I have read the documents for many times, but I don't understand. Is it based on the uploaded preferential combination

**Comment by He79** [comment]
@Lukasz-Zurek

**Comment by Lukasz-Zurek** [comment]
@He79 

1. I think that the best option for you will be [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) - where you can handle an offer with a product together in one request. We described this process in [our guide](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem-za-pomoca-zasobu-sale-product-offers).

2. I understand that you meant [POST /sale/offer-variants](https://developer.allegro.pl/documentation/#operation/createVariantSet) - so you can provide colorPattern to create color variants for one offer. First of all you will have to check the category if you will be able to create variants there and the parameters if they do have "variantsAllowed" value. I guess you have already read [this guide](https://developer.allegro.pl/tutorials/jak-utworzyc-oferte-wielowariantowa-oA6ZYBg5XFo). If you have some specific questions - please let me know.

**Comment by He79** [comment]
@Lukasz-Zurek 
I met 403 again in product-offers
HttpResponseProxy{HTTP/1.1 403 Forbidden [content-length: 587, content-type: text/html, x-frame-options: SAMEORIGIN, strict-transport-security: max-age=15552000, accept-ch: Sec-CH-UA,Sec-CH-UA-Mobile,Sec-CH-UA-Platform,Sec-CH-UA-Arch,Sec-CH-UA-Full-Version-List,Sec-CH-UA-Model,Sec-CH-Device-Memory, content-type: text/html; charset=utf-8, charset: utf-8, cache-control: max-age=0, private, no-cache, no-store, must-revalidate, pragma: no-cache, access-control-allow-credentials: true, access-control-expose-headers: x-dd-b, x-set-cookie, access-control-allow-origin: *, accept-ch: Sec-CH-UA,Sec-CH-UA-Mobile,Sec-CH-UA-Platform,Sec-CH-UA-Arch,Sec-CH-UA-Full-Version-List,Sec-CH-UA-Model,Sec-CH-Device-Memory, x-datadome-cid: AHrlqAAAAAMA9t688QM86PMAGybo9w==, set-cookie: datadome=4CJ~6w~Zecuh5EvCpOmWDHSW8cYHD8oW7bgbZAVxAWTqX9erMEMmEuVsogjkUo~VcpDpC3w~KgZeFgSB7p~m~tg93dRzK~S3WkARWXY-9xLYIrO_X_I2p6jEABkISXpV; Max-Age=31536000; Domain=.allegrosandbox.pl; Path=/; Secure; SameSite=Lax, x-robots-tag: noindex, set-cookie: _cmuid=14f455f1-710c-45a1-a627-243681966c32; Expires=Sat, 23 Nov 2024 08:55:33 GMT; Path=/; Domain=.allegro.pl.allegrosandbox.pl; Secure] ResponseEntityProxy{[Content-Type: text/html,Content-Length: 587,Chunked: false]}}

**Comment by He79** [comment]
I don't know if you can understand that I attach my request data without the trace id
{"sellingMode":{"price":{"amount":"123.45","currency":"PLN"},"format":"BUY_NOW"},"stock":{"unit":"UNIT","available":99},"category":{"id":"55207"},"parameters":[{"id":"219629","valuesIds":["219629_286873"]}],"productSet":[{"product":{"id":"bd6d000b-0fbd-41db-8598-b0853ab0237c"},"quantity":{"value":1}}]}

**Comment by Lukasz-Zurek** [comment]
@He79 I see that you are providing an incorrect "Accept" header: application/vnd.allegro.beta.v1+json so that's why you are receiving an 403 status code error. 

Please provide correct Accept header: **application/vnd.allegro.public.v1+json**

**Comment by He79** [comment]
Hello, Allegro official,  Now I have encountered a new problem, and I want to get the answer

When I want to upload a product with color and size, size will be automatically combined into a variation set. When I combine colors at this time, the system reports an error saying that the product is part of other variation sets. Should I delete the existing size variation set first, and then combine the size and color variation sets? Is there any better way to do this
Only one image can be converted to an internal address at a time

**Comment by Lukasz-Zurek** [comment]
@He79 I am sorry that you had to wait. As I see - my colleague has already answered you right [here](https://github.com/allegro/allegro-api/issues/6441#issuecomment-1336874150). Obviously you will have to delete these variation sets and combine the size and color variation sets once again. There is no other option/possibility to make it better in any different way.

**Comment by He79** [comment]
@Lukasz-Zurek  Hello
1. Do I have a way to bypass two-step verification and create applications
2. When I use interfaces（GET） after-sales-service-conditions/return-policies
HttpResponseProxy{HTTP/1.1 403 Forbidden [trace-id: cc3f5a565a047356, content-type: application/json; charset=utf-8, content-length: 162, date: Sun, 11 Dec 2022 22:04:18 GMT] ResponseEntityProxy{[Content-Type: application/json; charset=utf-8,Content-Length: 162,Chunked: false]}}

**Comment by Lukasz-Zurek** [comment]
@He79 I would like to clarify this case - as I am not sure what are you trying to provide in your request - most likely you are not providing any value in the "Accept" header at all. Please check it closely and provide: application/vnd.allegro.public.v1+json as mentioned above.

**Comment by He79** [comment]
@Lukasz-Zurek My Request Header Settings
1.![image](https://user-images.githubusercontent.com/69881314/206998234-b80e0c2f-af43-4eb0-be94-7f27a28326cc.png)
2.Why can this program bypass two-step verification to create applications https://www.dianxiaomi.com/

**Comment by Lukasz-Zurek** [comment]
1. Yes, you are not providing "Accept" header. Please provide it and you should not have that kind of error.
2. I am not sure what do you mean. Every account on the production has to enable two-step verification. But is not required on the Sandbox (test environment).

**Comment by He79** [comment]
@Lukasz-Zurek Hello, I'm testing to refresh the token automatically, but my IP seems to be blocked. Can you unblock my IP (119.91.30.103), or is there any way to unblock my IP? Thank you

**Comment by Lukasz-Zurek** [comment]
@He79 Hi. I've already reported it to another department. Please be patient. I will be back with some more information soon.

**Comment by Lukasz-Zurek** [comment]
@He79 Right now we do not see in our logs that your ip is blocked, so it should be ok.

**Comment by He79** [comment]
@Lukasz-Zurek Thank you very much for your patient answer before. Now it can't be passed https://apps.developer.allegro.pl/ Has the application been created

**Comment by AureliuszBrussy** [comment]
@He79 could you elaborate on exactly what problem you currently encountered?

**Comment by He79** [comment]
I passed in a formal environment https://apps.developer.allegro.pl/ Create an application, but I found that there is no button created. What is the problem with the system

**Comment by AureliuszBrussy** [comment]
try using the link: [https://apps.developer.allegro.pl/new](https://apps.developer.allegro.pl/new). I would add that you can create a maximum of 5 Client IDs on a single account, so this could also be the reason for not being able to create another key.

**Comment by He79** [comment]
Thank you for your patience. Thank you

**Comment by He79** [comment]
@AureliuszBrussy  Dear Allegro officials, why can't you make color user-customizable?
![image](https://user-images.githubusercontent.com/69881314/232180106-ac73f798-853e-45c8-b605-f668c961dd89.png)

**Comment by AureliuszBrussy** [comment]
If you would like to make suggestions about the parameters and their options - please use the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by He79** [comment]
@AureliuszBrussy Dear allegro officials, I would like to know where the api documentation for the Czech site is

**Comment by AureliuszBrussy** [comment]
We provide [a guide](https://developer.allegro.pl/tutorials/listing-and-managing-offers-on-foreign-marketplaces-7GndGjeAATn) to managing additional marketplaces. The API for allegro.cz itself works the same as the API of allegro.pl. We distinguish that the user is registered at allegro.cz, so for example, if you try to create a new product offer by [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) using the access token of the account registered at allegro.cz - we will create the offer in the allegro.cz as base marketplace.

You can also list an offer on allegro.pl and manage its visibility in a additional marketplace (allegro.cz).
