### ISSUE TITLE
Questions about uploading the Offer API

### ISSUE THREAD

**Issue by CrazyTaolt** [allegro/allegro-api#6394]
Hello, Aellgro Developer,

  I heard that the interface for uploading offers will be cancelled in 2023.
  URL:https://developer.allegro.pl/documentation#operation/createOfferUsingPOST
  I would like to ask if it is true?

  If this API is cancelled, which API should I use instead?

  thank you!

  Zero

**Comment by AureliuszBrussy** [comment]
Yes, it is true - we plan to completely disable resources (on January 1, 2024) for creating and editing offers from the **/sale/offers** and **/sale/offers/{offerId}** paths. The **/sale/product-offers** resource will be the only one to allow listing and editing offers. 

You should start using: 
- [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers), 
- [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/editProductOffers),
- [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/getProductOffer).

You can find more information in [our news](https://github.com/allegro/allegro-api/issues/5729).

**Comment by CrazyTaolt** [comment]
Is there a request example for this API?The example in the document seems incomplete.
[POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers)

**Comment by AureliuszBrussy** [comment]
Check [our guide](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-list-an-offer-with-a-product-via-sale-product-offers-resource) if you need more info about this endpoint.

**Comment by CrazyTaolt** [comment]
OK,Thank you!
Is there an alternative interface for the [GetOffers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET) interface?

**Comment by AureliuszBrussy** [comment]
@CrazyTaolt no, there is no alternative endpoint for **GET /sale/offers**. We do not plan to shut down [GET /sale/offers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET).

**Comment by CrazyTaolt** [comment]
OK,Thank you!
![image](https://user-images.githubusercontent.com/68230900/204477743-2ef1f721-0a49-4091-b9fe-20440f8d993d.png)
If the category does not allow creation of products(offersWithProductPublicationEnabled=false,productCreationEnabled=false), how can I upload an offer?

**Comment by AureliuszBrussy** [comment]
You can create offers without creating new products, as well as without linking a product to an offer. **POST /sale/product-offers** interface will also handle such a case.

**Comment by CrazyTaolt** [comment]
OK, Thank you!

**Comment by CrazyTaolt** [comment]
When creating an offer using the category that prohibits the creation of products, I do not pass the productSet parameter, but an error is reported.

request:
{"id":null,"name":"Niesławna czarna modna koszulka Mobba","productSet":null,"category":{"id":"87913"},"images":["https://a.allegroimg.allegrosandbox.pl/original/11a547/bc5f20e744b394f80014975641e8","https://a.allegroimg.allegrosandbox.pl/original/11ef32/13cbcc0542948ba007a6212ab410","https://a.allegroimg.allegrosandbox.pl/original/11892f/001fa4e24f2c870e7de1d5786879"],"parameters":[{"id":"11323","name":"Stan","requiredForProduct":false,"describesProduct":false,"valuesIds":["11323_1"],"values":null,"rangeValue":null}],"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>If you are not satisfied with the goods received, please leave a message before giving a bad evaluation</p><p>Hej! zapraszamy do naszego sklepu!</p><p>szczęśliwe zakupy!</p><p>Produkt: koszulka</p><p>Cechy: przeciwzmarszczkowy, </p><p>oddychający, wysoka absorpcja wody, dobra elastyczność, wygodny, wygodny, elastyczny i łatwy w </p><p>obsłudze.</p><p>Nasze tkaniny są tak miękkie, że stykają się bezpośrednio ze skórą.</p><p>SIZE:</p><p>S   / Chest  96 cm / Shoulder 43 cm / Length 70 cm</p><p>M  / Chest 104 cm / Shoulder 45 cm /Length 71 cm</p><p>L   / Chest 112 cm / Shoulder 47 cm / Length 73 cm</p><p>XL  / Chest 120 cm / Shoulder 49 cm / Length  76 cm</p><p>2XL / Chest 128 cm /  Shoulder 52 cm / Length 80 cm</p><p>3XL /Chest 136 cm / Shoulder 55 cm / Length 84 cm</p><p>4XL/Chest 144 cm / Shoulder 58 cm/ Length 86 cm</p>","url":null}]},{"items":[{"type":"IMAGE","content":null,"url":"https://a.allegroimg.allegrosandbox.pl/original/11a547/bc5f20e744b394f80014975641e8"}]},{"items":[{"type":"IMAGE","content":null,"url":"https://a.allegroimg.allegrosandbox.pl/original/11ef32/13cbcc0542948ba007a6212ab410"}]},{"items":[{"type":"IMAGE","content":null,"url":"https://a.allegroimg.allegrosandbox.pl/original/11892f/001fa4e24f2c870e7de1d5786879"}]}]},"sellingMode":{"format":"BUY_NOW","price":{"amount":699.00,"currency":"PLN"},"minimalPrice":{"amount":699.00,"currency":"PLN"},"startingPrice":{"amount":699.00,"currency":"PLN"}},"stock":{"available":500,"unit":"UNIT","sold":0},"delivery":{"shippingRates":null,"additionalInfo":"","handlingTime":"PT24H","shipmentDate":null},"external":{"id":"1128sruy8-test-red-S"},"afterSalesServices":{"impliedWarranty":null,"returnPolicy":null,"warranty":null},"payments":{"invoice":"NO_INVOICE"},"location":{"countryCode":"CN","province":"福建省","city":"莆田市","postCode":"351111"},"publication":null,"tax":null,"sizeTable":null,"discounts":null,"customParameters":null}

response:
{"errors":[{"code":"RemoveProductException","message":"Unprocessable Entity","details":null,"path":"productSet[0].product","userMessage":"Unable to unlink product from offer."}]}

**Comment by CrazyTaolt** [comment]
Can you give an example of calling API from the category where product creation is prohibited?

**Comment by AureliuszBrussy** [comment]
You simply have to distinguish between product and offer parameters. Product parameters are the parameters you need to pass in the **productSet.product[].parameters** structure. You will recognize them with **parameters[].options.describesProduct = true** flag on [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). You proceed exactly as in the category where you can create a product.

Sample payload for category 88309 (Sandbox):

```
{
    "name": "Test offer",
    "productSet": [
        {
            "quantity": {
                "value": 1
            },
            "product": {
                "category": {
                    "id": "88309"
                },
                "parameters": [
                    {
                        "id": "7174",
                        "valuesIds": [
                            "7174_400"
                        ],
                        "values": [
                            "TestBrand"
                        ],
                        "rangeValue": null
                    },
                    {
                        "id": "6952",
                        "valuesIds": [],
                        "values": [
                            "12"
                        ],
                        "rangeValue": null
                    },
                    {
                        "id": "205826",
                        "valuesIds": [
                            "205826_1041839"
                        ],
                        "values": [],
                        "rangeValue": null
                    }
                ]
            }
        }
    ],
    "parameters": [
        {
            "id": "11323",
            "name": "Stan",
            "values": [
                "Nowy"
            ],
            "valuesIds": [
                "11323_1"
            ],
            "rangeValue": null
        }
    ],
    "images": [
        "https://a.allegroimg.allegrosandbox.pl/original/11b2ae/a0c2ae3d407e8cd8f63388b0c486"
    ],
    "publication": {
        "status": "ACTIVE"
    },
    "afterSalesServices": {
        "impliedWarranty": {
            "name": "default"
        },
        "returnPolicy": {
            "name": "default"
        },
        "warranty": null
    },
    "payments": {
        "invoice": "NO_INVOICE"
    },
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "100.00",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null
    },
    "stock": {
        "available": 12,
        "unit": "UNIT"
    },
    "location": {
        "countryCode": "PL",
        "province": "WIELKOPOLSKIE",
        "city": "Poznań",
        "postCode": "66-166"
    },
    "delivery": {
        "shippingRates": {
            "name": "default"
        },
        "handlingTime": "PT48H",
        "additionalInfo": "",
        "shipmentDate": null
    },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>Test</p>"
                    }
                ]
            }
        ]
    },
    "external": null,
    "tax": null,
    "sizeTable": null,
    "discounts": {
        "wholesalePriceList": null
    },
    "contact": null,
    "fundraisingCampaign": null,
    "messageToSellerSettings": {
        "mode": "OPTIONAL"
    },
    "attachments": [],
    "b2b": null,
    "additionalServices": null,
    "compatibilityList": null,
    "language": "pl-PL"
}
```

**Comment by CrazyTaolt** [comment]
I used the category: 12181

request:
`{"id":null,"name":"4*5M WOJSKOWA SIATKA MASKUJĄCA MORO KA 12156","productSet":[{"product":{"name":"4*5M WOJSKOWA SIATKA MASKUJĄCA MORO KA 12156","category":{"id":"12181"},"id":"","parameters":[{"id":"4713","name":"oryginał / kopia","requiredForProduct":true,"describesProduct":true,"valuesIds":["4713_2"],"values":null,"rangeValue":null}],"images":["https://a.allegroimg.com/original/11c045/304071fa4bafb8cc8666ccb60c0c","https://a.allegroimg.com/original/11499a/2e2cef8742068278cc46b43ea4a2","https://a.allegroimg.com/original/1134ee/531a47264b84908fccd70b799bf4","https://a.allegroimg.com/original/11f1e1/8059409942c8bc9ec56a46f0c601","https://a.allegroimg.com/original/113738/4f0ccc23406db14d485a0b255c83","https://a.allegroimg.com/original/1139a8/737b443e4c29b47243f87dc24653","https://a.allegroimg.com/original/116aae/089f09a14543b5bb4859e20e5829","https://a.allegroimg.com/original/115806/bc76bb5349c3a5181cfda9d1bc04","https://a.allegroimg.com/original/117092/0adef1884aa090748e16f1299eeb","https://a.allegroimg.com/original/116c0a/76a6826d482f89a45e326a9239e7"]},"quantity":{"value":500}}],"category":{"id":"12181"},"images":["https://a.allegroimg.com/original/11c045/304071fa4bafb8cc8666ccb60c0c","https://a.allegroimg.com/original/11499a/2e2cef8742068278cc46b43ea4a2","https://a.allegroimg.com/original/1134ee/531a47264b84908fccd70b799bf4","https://a.allegroimg.com/original/11f1e1/8059409942c8bc9ec56a46f0c601","https://a.allegroimg.com/original/113738/4f0ccc23406db14d485a0b255c83","https://a.allegroimg.com/original/1139a8/737b443e4c29b47243f87dc24653","https://a.allegroimg.com/original/116aae/089f09a14543b5bb4859e20e5829","https://a.allegroimg.com/original/115806/bc76bb5349c3a5181cfda9d1bc04","https://a.allegroimg.com/original/117092/0adef1884aa090748e16f1299eeb","https://a.allegroimg.com/original/116c0a/76a6826d482f89a45e326a9239e7"],"parameters":[],"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Funkcja:</p><p>-100% nowy i wysokiej jakości.</p><p>-Kamuflażowa kamuflażowa dżungla bez liny.</p><p>- Kamuflaż jest bardzo skutecznym, realistycznym efektem i wszechstronnym.</p><p>Główna rola i cele:</p><p>Szkolenie wojskowe w kamuflażu, instalacje wojskowe radar przeciw podczerwieni.</p><p>Firma zajmująca się nieruchomościami, lotnicza fotografia lotnicza.</p><p>Nielegalne budynki i fotografia roślinna z satelity.</p><p>Parkingi i inne miejsca publiczne cienią krajobraz.</p><p>Pokrywa górska i zielona, pokrywa śmieci.</p><p>Miłośnicy obserwowania ptaków muszą strzelać w dal i w kontakcie z kamuflażem ptaków.</p><p>Kamuflaż snajperski i użycie.</p><p>Dekoracyjne architektura krajobrazu (parki tematyczne, wystawy, baza filmowa, zagospodarowanie terenu, symulacja pola CS, dekoracja hotelu, dekoracja przemysłowa, dekoracja domu itp.), Kolor tła imitacji i inne aspekty.</p><p>Dane techniczne:</p><p>Nazwa produktu: Camo Net</p><p>Materiał: tkanina poliestrowa Oxford</p><p>Kolor: jako pokaz obrazu</p><h2>Rozmiar: około 4 x 5 M.</h2><p>Paczka zawiera:</p><p>1x Siatka kamuflażowa</p><p>Uwagi:</p><p>1. Rzeczywisty kolor może nieznacznie różnić się od obrazu ze względu na różne efekty monitora i oświetlenia.</p><p>2. Proszę pozwolić 1-3 mm odchylenie ze względu na pomiarze ręcznym.</p>","url":null}]},{"items":[{"type":"IMAGE","content":null,"url":"https://a.allegroimg.com/original/116aae/089f09a14543b5bb4859e20e5829"}]},{"items":[{"type":"IMAGE","content":null,"url":"https://a.allegroimg.com/original/115806/bc76bb5349c3a5181cfda9d1bc04"}]},{"items":[{"type":"IMAGE","content":null,"url":"https://a.allegroimg.com/original/117092/0adef1884aa090748e16f1299eeb"}]},{"items":[{"type":"IMAGE","content":null,"url":"https://a.allegroimg.com/original/116c0a/76a6826d482f89a45e326a9239e7"}]}]},"sellingMode":{"format":"BUY_NOW","price":{"amount":119.00,"currency":"PLN"},"minimalPrice":{"amount":119.00,"currency":"PLN"},"startingPrice":{"amount":119.00,"currency":"PLN"}},"stock":{"available":500,"unit":"UNIT","sold":0},"delivery":{"shippingRates":{"id":"8ecb5e01-cc96-428c-82bd-7b414aede340"},"additionalInfo":"","handlingTime":"P4D","shipmentDate":null},"external":{"id":"SKU32296-kopia / replika"},"afterSalesServices":{"impliedWarranty":{"id":"f91fe8cc-1c4a-4860-b7ee-ec4939e0c553"},"returnPolicy":{"id":"561b9b6f-cb32-4f15-aa32-37f739e2259a"},"warranty":null},"payments":{"invoice":"NO_INVOICE"},"location":{"countryCode":"HK","province":"Hongkong","city":"Hongkong","postCode":"000000"},"publication":null,"tax":null,"sizeTable":null,"discounts":null,"customParameters":null}`

response:
`{"errors":[{"code":"ProductSetOfferWithoutIdsException","message":"Unprocessable Entity","details":null,"path":"productSet.product.id","userMessage":"Unable to create a product set containing non-product items. Make sure that all set elements belong to categories that support creating products."}]}`

**Comment by CrazyTaolt** [comment]
The parameters of this category are as follows:
offersWithProductPublicationEnabled=false
productCreationEnabled=false

This category prohibits the creation of products, but in the previous API ([POST
/sale/offers](https://developer.allegro.pl/documentation#operation/createOfferUsingPOST)), it was allowed to create an offer separately. How should I pass parameters to this category now?

**Comment by AureliuszBrussy** [comment]
I just tried a request to list in this category and was able to list successfully. My payload:

```
{
    "productSet": [
        {
            "product": {
                "name": "4*5M WOJSKOWA SIATKA MASKUJĄCA MORO KA 12156",
                "category": {
                    "id": "12181"
                },
                "parameters": [
                    {
                        "id": "4713",
                        "valuesIds": [
                            "4713_1"
                        ],
                        "values": [],
                        "rangeValue": null
                    }
                ]
            }
        }
    ],
    "images": [
        "https://a.allegroimg.allegrosandbox.pl/original/11b2ae/a0c2ae3d407e8cd8f63388b0c486"
    ],
    "afterSalesServices": {
        "impliedWarranty": {
            "name": "default"
        },
        "returnPolicy": {
            "name": "default"
        },
        "warranty": null
    },
    "payments": {
        "invoice": "NO_INVOICE"
    },
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "100.00",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null
    },
    "stock": {
        "available": 200,
        "unit": "UNIT"
    },
    "location": {
        "countryCode": "PL",
        "province": "WIELKOPOLSKIE",
        "city": "Poznań",
        "postCode": "66-166"
    },
    "delivery": {
        "shippingRates": {
            "name": "default"
        },
        "handlingTime": "PT48H",
        "additionalInfo": "",
        "shipmentDate": null
    },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>Test</p>"
                    }
                ]
            }
        ]
    },
    "external": null,
    "tax": null,
    "sizeTable": null,
    "discounts": {
        "wholesalePriceList": null
    },
    "contact": null,
    "fundraisingCampaign": null,
    "messageToSellerSettings": {
        "mode": "OPTIONAL"
    },
    "attachments": [],
    "b2b": null,
    "additionalServices": null,
    "compatibilityList": null,
    "publication": {
        "status": "ACTIVE"
    }
}
}
```

Change the value of the product.quantity.value field to 1 or do not pass this field in these cases. In this field, you define the number of products in the set, not the number of products in stock.

**Comment by MaciejFrackowiak** [comment]
This is our error with the parameter - we are working to eliminate it.

**Comment by CrazyTaolt** [comment]
OK, please let me know after you solve this problem

**Comment by CrazyTaolt** [comment]
Hello, Aellgro Developer,
I would like to ask if there is any update on this issue.
Thank you!

**Comment by MaciejFrackowiak** [comment]
I see the task is not finished yet, but I sent a request with data from your template a minute ago and the offer was listed.

**Comment by CrazyTaolt** [comment]
OK, thank you very much for your reply!
I asked them to try again.
