### ISSUE TITLE
1. Czy narzucacie podczas integracji z innym systemem swój nr listu przewozowego? 

### ISSUE THREAD

**Issue by Agata5991** [allegro/allegro-api#6395]

**Comment by AureliuszBrussy** [comment]
Chodzi Ci o generowanie przesyłek w ramach Wysyłam z Allegro? Jeżeli tak - nie narzucamy go, numer listu przewozowego/przesyłki jest generowany przez przewoźnika, my tylko go przekazujemy.

**Comment by Agata5991** [comment]
Nie wiem dokładnie czy chodzi o ten proces, ponieważ pierwszy raz będziemy integrowac ERP XL z Allegro, chodzi o moment w którym klient dostaje potwierdzenie zakupu wraz z nr listu przewozowego.

**Comment by AureliuszBrussy** [comment]
Nie, nie narzucamy numeru listu przewozowego. Jest on przekazywany Kupującemu po [uzupełnieniu numeru przesyłki](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#jak-dodac-numer-przesylki-do-przedmiotu-w-zamowieniu) w zamówieniu. Można go dodać przez API jak i w zakładce [Zamówenia](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/). Jest on także uzupełniany automatycznie w przypadku korzystania m.in.  z Wysyłam z Allegro, jak i ze zintegrowanych narzędzi przewoźników.
