### ISSUE TITLE
2. Jak wygląda kwestia szablonów, czy macie gotowy szablon do którego podstawia sie konkretne dane, czy są różne rodzaje szablonów aukcji, czy klient sam tworzy taki szablon? Czy jest możliwość importować gotowe szablony aukcji utworzone zewnętrzne? 

### ISSUE THREAD

**Issue by Agata5991** [allegro/allegro-api#6396]

**Comment by Agata5991** [comment]
Czy z wykorzystaniem Vendor API można wgrać szablon opisu aukcji, napisany np. w HTML?

**Comment by AureliuszBrussy** [comment]
@Agata5991 pytanie to powinnaś zadać supportowi tego narzędzia.

**Comment by Agata5991** [comment]
> @Agata5991 pytanie to powinnaś zadać supportowi tego narzędzia.

Czyli u Państwa  w innym wątku?

**Comment by AureliuszBrussy** [comment]
Co masz na myśli poprzez Vendor API? Czy to jakieś narzędzie, z którego korzystasz? Jeżeli tak - powinnaś zadać pytanie to pytanie supportowi tego narzędzia. Nasze API odbiera i przesyła dane (payload) w formacie JSON. Nie ma możliwości przesłania ich w HTMLu.
