### ISSUE TITLE
Zestawienie zamówień sprzedażny - stawka VAT produktów

### ISSUE THREAD

**Issue by mikolaj-bronk** [allegro/allegro-api#6397]
Dzień dobry,

do wygenerowania zestawień zamówień, potrzebujemy pobierać listę sprzedaży (ukończonych zamówień) dla konkretnych naszych sprzedawców wraz z produktami w tych zamówieniach i ich stawkami VAT.

Moje pytanie jest następujące:

Czy jedynym sposobem, aby je uzyskać jest:
1. wyjście z GET order/checkout-forms - pobranie wszystkich zamówień
2. dla każdego zamówienia i dla każdego produktu w lineItems wyciągnąć id_offer, 
3. z endpointu GET /sale/offers wyciągać id kategorii dla danego offer, 
4. uderzyć z id kategorii w GET /sale/tax-settings?

Zakładając, że mamy 1000 zamówień i w każdym z nich jest optymistycznie 1 produkt, to generuje nam to 2000 dodatkowych requestów, co jest niezbyt wydajną ścieżką.

Czy jest jakiś prostszy sposób, aby wykorzystując API móc stworzyć zestawienie zamówień sprzedawców zawierające dane stawki VAT na produkty?

**Comment by Lukasz-Zurek** [comment]
@mikolaj-bronk Sposób opisany przez Ciebie to tak na prawdę jedyna możliwość pobrania tego typu informacji i tak jak napisałeś - nie jest to w pełni wydajna ścieżka.

**Comment by Lukasz-Zurek** [comment]
@mikolaj-bronk Uzupełniając moją wiadomość chciałbym jeszcze dodać, że w punkcie nr 2 uzyskasz już numery ofert, następnie w punkcie nr 3 za pomocą GET /sale/offers/{offerId} pobierzesz szczegółowe informacje dotyczące ofert (w tym również informacje o stawce VAT w sekcji "tax". W tym momencie punkt nr 4 możesz całkowicie pominąć. To niewątpliwie skraca i upraszcza cały proces

**Comment by mikolaj-bronk** [comment]
> @mikolaj-bronk Uzupełniając moją wiadomość chciałbym jeszcze dodać, że w punkcie nr 2 uzyskasz już numery ofert, następnie w punkcie nr 3 za pomocą GET /sale/offers/{offerId} pobierzesz szczegółowe informacje dotyczące ofert, w tym również informacje o stawce VAT w sekcji "tax". W tym momencie punkt nr 4 możesz całkowicie pominąć. To niewątpliwie skraca i upraszcza cały proces

Dopytam w takim razie: jaką mam pewność, że węzeł  
 ```
"tax": {
"id": "ae727432-8b72-4bfe-b732-6f163a2bf32a",
"rate": "23.00",
"subject": "GOODS",
"exemption": "MONEY_EQUIVALENT",
"percentage": "23.00"
},
```
Zawsze będzie oznaczał podatek VAT? Nie ma możliwości, że jest tutaj jakiś inny podatek? Ew. czy np. rozpoznajemy to po jakimś kluczu, np. subject == 'GOODS' .

**Comment by Lukasz-Zurek** [comment]
@mikolaj-bronk Tak. Niezależnie od stawki procentowej - w polu **"subject"** zwrócimy "GOODS" (czyli towar), lub **null**. Ustawienia VAT opisaliśmy w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-wystawic-oferte-GRaj0q1PMSK#ustawienia-vat).

W polu **"exemption"** zwracamy różne wartości. Jest to obiekt reprezentujący zwolnienie z opodatkowania, które przypisane jest ustawieniu VAT.

**Comment by mikolaj-bronk** [comment]
Dziękuję
