### ISSUE TITLE
Allegro Sandbox - zdjęcia

### ISSUE THREAD

**Issue by AdrianeZ** [allegro/allegro-api#6398]
Czy macie jakiś problem ze zdjęciami na sandbox, nie pokazują się one w opisie i w galerii i jest to chyba globalny problem?

**Comment by Lukasz-Zurek** [comment]
Dziękuję za zgłoszenie. Sprawdzamy to.

**Comment by Lukasz-Zurek** [comment]
@AdrianeZ Podaj proszę przykładowe numery ofert.
