### ISSUE TITLE
Wiele form dostawy WzA na jednej parze kluczy client secret i client ID - device code flow auth

### ISSUE THREAD

**Issue by wap18** [allegro/allegro-api#6399]
Dzień dobry,

czy autoryzując aplikację poprzez Device code flow mogę skorzystać z tej samej pary kluczy dla wielu form dostawy WzA?
Ostatnio wprowadzili Państwo podział usług, jest ujęty w tym wątku: 
https://github.com/allegro/allegro-api/issues/6159

Pozdrawiam,
Arek

**Comment by Lukasz-Zurek** [comment]
Jeśli mówimy o liście metod wspólnych dla wszystkich użytkowników (dla umowy Allegro) to tak, ponieważ identyfikatory usług dostawy są spójne z id metod dostawy. Należy pamiętać, że jeśli użytkownik posiada umowę własną - wtedy przypisujemy id_metody#id_umowy_wlasnej. Umowy własne będą się tutaj różniły identyfikatorem, a tym samym cały identyfikator takiej usługi dostawy dla różnych użytkowników (na każdym z nich trzeba przejść przez odrębny proces autoryzacji) - będzie inny.
