### ISSUE TITLE
doGetSellFormFieldsForCategory nie działa dla ID: 4140 [ / Motoryzacja / Części samochodowe / Oświetlenie / Żarówki ]

### ISSUE THREAD

**Issue by karol-gontarski** [allegro/allegro-api#64]
doGetSellFormFieldsForCategory 
działa dla wszystkich kategorii oprócz 
ID: 4140 [ / Motoryzacja / Części samochodowe / Oświetlenie / Żarówki ]

łapie mi błąd: "looks like we got no XML document"

> SoapFault exception: [Client] looks like we got no XML document in ... 

Czy ktoś może to potwierdzić ?

**Comment by karol-gontarski** [comment]
to samo dla ID: 99204 [ / Motoryzacja / Opony / Opony samochodowe / Całoroczne ]

**Comment by KrzysztofLukanowski** [comment]
Pobierz proszę aktualne drzewo kategorii metodą [doGetCatsData](https://allegro.pl/webapi/documentation.php/show/id,46). Podane przez Ciebie numery kategorii nie istnieją.

**Comment by spiasecki** [comment]
Ja dostaje ten sam error na sandboksie np, dla kategorii 15579 (id pobrałem po API wyżej wymienioną metodą)

```xml
<?xml version="1.0" encoding="UTF-8"?>\n
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Body>
        <SOAP-ENV:Fault>
        <faultcode>SOAP-ENV:Server</faultcode
        <faultstring>Call to a member function getParametersIds() on a non-object</faultstring>
        <detail>\n</detail>
    </SOAP-ENV:Fault>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Body>
        <SOAP-ENV:Fault>
            <faultcode>ERR_INTERNAL_SYSTEM_ERROR</faultcode>
            <faultstring>Internal system error</faultstring>
            <faultactor>Internal system error</faultactor>
        </SOAP-ENV:Fault>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

**Comment by KrzysztofLukanowski** [comment]
@spiasecki Drzewo kategorii na sandboksie nie odpowiada 1:1 kategoriom na produkcji. Aktualne kategorie znajdziesz zawsze w [wsdl ](https://webapi.allegro.pl/service.php?wsdl)produkcyjnym.
