### ISSUE TITLE
[Pytanie] Pobranie listy niesprzedanych ofert - dalsze plany?

### ISSUE THREAD

**Issue by Uriziel01** [allegro/allegro-api#640]
Witam,
czy i w jakiej formie zostanie udostępniony zasób pozwalający pobierać listę niesprzedanych aukcji, chodzi o odpowiednik powiedzmy `doGetMyNotSoldItems` czy też `doMyAccount2`. 

Według Państwa wcześniejszych zapowiedzi zawartej w `Wygaszamy WebAPI do obsługi ofert i sprzedaży. Korzystaj z REST API` wymienione metody WebAPI wejdą w proces "_wygaszania_" w październiku, jednocześnie widnieje tam informacja że chodzi jedynie o `obsługę ofert i sprzedaży`.

Czy oznacza to że usunięte zostaną jedynie zasoby służące obsłudze ofert i nie powinniśmy się martwić o  przyszłość metod służących listowaniu ofert? Ale czy oznacza to że docelowo jednocześnie wszyscy będą zmuszeni korzystać ze starego `WebAPI` i nowego `REST API`?

Jest to dość osobliwe podejście bo doprowadzi do tego że aby być w stanie obsługiwać wszystkie funkcjonalności serwisu niezbędne do prowadzenia działalności będzie trzeba łączyć się z różnymi końcówkami, o zupełnie innej architekturze, sposobie autoryzacji klucza, formacie parametrów, formacie zwracanych danach i kompetencjach.

**Comment by Uriziel01** [comment]
A widzisz, dzięki @collector1871 ! Nie miałem pojęcia że metoda `offers-listing` posiada też opcję `CLOSED`, zaraz sprawdzę jak to wszystko działa ale chyba jest to czego szukam. :)

**Comment by Uriziel01** [comment]
Szkoda tylko że maksymalna ilość to 100, będę musiał zrobić BARDZO dużo zapytań żeby pobrać je wszystkie.

**Comment by collector1871** [comment]
tak, dokładnie, da się to zrobić.

pętle i dużo requestów

jeszcze jak będziesz wpadał w pętle, to można się zastanowić jaka różnica jest pomiędzy:
"availableCount" a "totalCount"

ja używam "totalCount", ale to łapie mi też aukcje niewidoczne w GUI (tyle, że dla mnie to wygodne, bo lokalnie to dodatkowo odfiltrowuję):

>       "availableCount": 1,                        -- liczba ofert, które spełniają
>                                                     warunki określone w zapytaniu i które
>                                                     wyświetlamy w serwisie. Przykładowo - dla
>                                                     danego zapytania liczba ofert jakie je
>                                                     spełniają to 2 000 000, ale na listach ofert w
>                                                     serwisie wyświetlamy maksymalnie 
>                                                     6000. Liczba 6000 to availableCount.
>         "totalCount": 1,                            -- całkowita liczba ofert, które spełniają
>                                                     warunki określone w zapytaniu.
>                                                     Przykładowo - dla danego zapytania liczba
>                                                     ofert jakie je spełniają to 2 000 000, ale na
>                                                     listach ofert w serwisie wyświetlamy maksymalnie
>                                                     6000. Liczba 2 000 000 to totalCount.

oczywiście to i to dzielimy przez 100 i wpadamy w pętle

**Comment by Uriziel01** [comment]
Nie zbadałem jeszcze sprawy do końca ale po wstępnych oględzinach z metodą `GET offers/listing` jest coś poważnie nie tak, nie dość że ilość zwróconych aukcji w `availableCount` jest zdecydowanie mniejsza niż faktyczna ilość zakończonych aukcji (wielokrotnie niższa) to same wyniki są niezrozumiałe.

Chciałem po zwracanym `bidCount` sprawdzić czy ktoś faktycznie licytował daną aukcję ale po sprawdzeniu 160 000 zakończonych aukcji (tylko tyle zwraca metoda) znalazłem ich tylko 29 (słownie dwadzieścia dziewięć) co jest oczywiście kompletnie niemożliwe (na tę chwilę samych niesprzedanych powinno być przeszło 177 000), czy ktoś z zespołu allegro może się wypowiedzieć co ta metodą tak naprawdę zwraca dla `searchMode=CLOSED` i dlaczego ilość wyników jest tak bardzo ograniczona.

**Comment by collector1871** [comment]
W ciągu ostatnich 2 tygodni też się tym zajmowałem, więc @Uriziel01 siedzimy przy tych samych problemach (szkoda, że nie obok siebie) :)

Więc z mojego doświadczenia i działającego kodu (2200 - 2600 aukcji na produkcji, nie żaden sandbox) wynika, że metoda działa i responsy są poprawne.
Requesty bazują na `totalCount` (nie wiem jakie wyniki zwracałby `availableCount`, ale możliwe, że brakowałoby czegoś).
`availableCount` napisałem jako ciekawostkę, ale wydaje mi się, że chyba lepiej jednak ściagnąć "wszystko co się da".

Kolejna rzecz: z tego co zauważyłem, to przy Allegro REST Api nie da się nic sensownego zrobić bez doskonałej wręcz obsługi wyjątków/errorów (exception handling, error handling). Sytuacja wygląda w ten sposób, że nawet jak 9 requestów/responsów jest poprawne, to 10te wysypią się bez wyraźnego powodu - i wtedy kod wchodzi w fazę "exception handling".

Następnie:
tutaj jest dyskusja:
[https://github.com/allegro/allegro-api/issues/582](https://github.com/allegro/allegro-api/issues/582) o zamkniętych ofertach.
Wynika z tego, że po "60 dniach" oferty mogą przejść w magiczny status : tzn. że są NIEWIDOCZNE przeważne w GUI, ale mogą być widoczne w responsie.
Albo odwrotnie.
Z tego co zauważyłem też, to nawet jak w GUI da się "UKRYJ", to reponse REST Api i tak zwraca ofertę - więc ona nie jest ukryta w responsach.

Sprawa wygląda tak, że magiczny termin **60 dni** dla zamkniętej oferty zdecydowanie coś zmienia: zarówno dla GUI oraz dla REST API... ale co dokładnie zmienia, to nie wiem.

Bardzo interesuje mnie ten topic, z czym się zmaga teraz @Uriziel01 , bo chociaż próbkę aukcji mamy mniejszą (do 2600) oraz (póki co) to wszystko nam działa, kod robi swoje, to jednak wolałbym dokładnie rozumieć co tu się dzieje :)

**Comment by LukaszKorek** [comment]
@Uriziel01  "availableCount": to zgodnie z dokumentacja iczba ofert, które spełniają warunki określone w zapytaniu i które wyświetlamy w serwisie czyli np. jeśli oferta przeszła do archiwum po 60 dniach nie otrzymasz jej. Odnośnie bidCount - podaj przykłąd oferty, której nie otrzymałeś, a powinieneś. Pozwoli to na weryfikację.

**Comment by Uriziel01** [comment]
@collector1871 nie wiem jak dokładnie działa to u Ciebie ale ja nie jestem w stanie wyjść poza liczbę aukcji określoną w availableCount gdyż dostaje wtedy komunikat:
`Invalid offset parameter value. Offset should be multiplier of limit and less than searchMeta.availableCount.`. Niestety potwierdzam także problem losowego wysypywania się API, można zrobić dosłownie 100 razy to samo zapytanie i zawsze chociaż kilka zakończy się błędem połączenia, pobranie kilkuset tysięcy aukcji (teoretycznie można pobierać tylko 100 w jednym zapytaniu ale i na to jest sprytny sposób ;)) przez te ciągłe wysypywanie się API trwa godziny.

@LukaszKorek przepraszam serdecznie, błąd leżał po naszej stronie, sprawdzaliśmy oferty z tablicy `regular` a ilość bid'ów z tablicy `promoted` ;)

**Comment by collector1871** [comment]
@Uriziel01 u nas jest `availableCount` = `totalCount` ; więc pewnie dlatego mi się wydawało, że `totalCount` można w całości pobrać. Ale z tego co opisujesz to wynika, że chyba mamy dostęp tylko do liczby/offsetu maksymalnie zbudowanego na `availableCount`... 
dobrze wiedzieć, ale dla pewności:

@LukaszKorek
mamy jakiś dostęp do danych aukcji, które są w całym `totalCount` ? 
szczególnie np. jak `totalCount` > `availableCount` (bo aktualnie mam to samo)

**Comment by LukaszKorek** [comment]
@Uriziel01 tak, jeżeli availableCount zwraca 160 000 a totalCount 1 558 108 to będziesz w stanie pobrać tylko te 160 000.
@collector1871 totalCount to całkowita liczba ofert, które spełniają warunki określone w zapytaniu (np. szukam firany w kolorze białym) , ale nie wszystkie wyswietlamy w serwisie na listach ofert, bo "nie mieszczą się".
