### ISSUE TITLE
Aktywacja konta - Sandbox

### ISSUE THREAD

**Issue by bujajsie** [allegro/allegro-api#6401]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Proszę o aktywacje konta rchmielewski. Pomimo wpisania poprawnych danych według dokumentacji, konto się nie weryfikuje.

**Comment by AureliuszBrussy** [comment]
@bujajsie mamy problemy techniczne z aktywacją i weryfikacją kont na Sandboxie. Pracujemy już nad rozwiązaniem problem. Wrócę do Ciebie z informacją po aktywacji.

**Comment by bujajsie** [comment]
@AureliuszBrussy jest możliwość ręcznej aktywacji? Potrzebuje konta do testów API

**Comment by AureliuszBrussy** [comment]
@bujajsie niestety, jednak nie jestem w stanie na ten moment tego przyspieszyć. Czekamy jeszcze na wdrożenie poprawki w procesie aktywacji konta na Sandboxie. Wrócę jeszcze z informacją.

**Comment by AureliuszBrussy** [comment]
@bujajsie spróbuj proszę ponownie wykonać [przelew weryfikacyjny](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) na koncie rchmielewski. To umożliwi mi dalsze przeprowadzenie aktywacji.
