### ISSUE TITLE
API Wysyłam z allegro. Numery przesyłek na zamówieniu

### ISSUE THREAD

**Issue by bartekc7** [allegro/allegro-api#6402]
Dzień dobry,
Mam pytanie odnoście nadawania przesyłek przez API wysyłam z Allegro [/parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/createNewParcel).
Czy numery listów przewozowych nie powinny podpiąć się z automatu pod zamówienie wg. podanego emaila w domenie allegro?
Jeżeli nie to czy jest dostępna metoda w API do pobrania identyfikatora zamówienia po emailu?

**Comment by hahyes** [comment]
> Czy numery listów przewozowych nie powinny podpiąć się z automatu pod zamówienie wg. podanego emaila w domenie allegro?

@bartekc7 Od tego jest ten zasób: https://developer.allegro.pl/documentation#operation/createOrderShipmentsUsingPOST

> Jeżeli nie to czy jest dostępna metoda w API do pobrania identyfikatora zamówienia po emailu?

Po e-mail nie, ale po loginie można szukać: https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET

**Comment by AureliuszBrussy** [comment]
Numer trackingowy przesyłki wygenerowanej w ramach Wysyłam z Allegro powinien być automatycznie przekazywany do Zamówień w momencie gdy operator przesyłki nada jej status.

**Comment by bartekc7** [comment]
> 

Czyli powinien np. jak przesyłka otrzyma status "W drodze" to wtedy automatycznie numer podepnie się pod zamówienie?
Ogólnie chodzi o to czy jest konieczność podpinania numeru pod zamówienie w przypadku przesyłek wygenerowanych przez API.
![image](https://user-images.githubusercontent.com/207927/203938053-99cb93fd-e99e-4cf9-936e-f688ddf1ea05.png)

**Comment by AureliuszBrussy** [comment]
Tak, zgadza się, numer przesyłki powinien został automatycznie uzupełniony w zamówienia dla przesyłek wygenerowanych w API WzA.

**Comment by bartekc7** [comment]
Dziękuje. Już wszystko jasne.
