### ISSUE TITLE
Wystawianie ofert a zwracany status

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#6403]
Mam pytanie co do wystawiania ofert przez nowy zasób:
POST /sale/product-offers

Kiedy operacja zostanie przetworzona od razu i otrzymamy 201 Created, a kiedy potrzebuje dłuższego czasu i zwróci 202 Accepted? Chciałbym doprecyzować tę kwestię.

Tak samo jak wygląda sytuacja z aktualizacją ofert za pomocą PATCH?

Dodam, że chciałbym tworzyć oferty jako szkice a dopiero potem je publikować za pomocą innego zasobu i zastanawiam się czy może z tego powodu nie będę zawsze dostawał statusu 201 podczas tworzenia szkiców.
PUT /sale/offer-publication-commands/{commandId}

**Comment by AureliuszBrussy** [comment]
Tak, masz rację - jeżeli operacja jest przetworzona od razu, dla żądania POST otrzymasz status 201, a dla PATCH - status 200.

Jeżeli przetworzenie żądania zajmuje więcej czasu - otrzymasz zwrotkę 202 wraz z nagłówkiem Location, gdzie wskazujemy adres, który możesz odpytywać, aby odczytać ostateczny status.  

Jeżeli będziesz tworzył tylko szkic oferty - dla POST powinieneś otrzymywać zawsze tylko status 201.  Możesz ją oczywiście swobodnie aktywować innym zasobem.
