### ISSUE TITLE
Mechanizm liczenia wejść na ofertę

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6404]
Proszę o wytłumaczenie, jak dokładnie działa zliczanie wejść na daną ofertę. Z tego co pamiętam, to licznik wyłapuje tylko unikatowe wejścia, tylko teraz pytanie, które to unikatowe wejścia. Czy unikatowe wejście użytkownika na Allegro, czy unikatowe wejście na jakąkolwiek naszą ofertę, itp.

**Comment by PrzemyslawLukanowski** [comment]
Konsultuję tę kwestię z odpowiednim zespołem, wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Licznik oznacza liczbę unikalnych wizyt użytkownika w konkretnej ofercie. Nie liczymy przy tym wizyt sprzedającego w swojej własnej ofercie. 

Natomiast nie wchodząc w szczegóły mechanizmu, mogę jeszcze przekazać, że z racji tego, że to “wizyta”, a nie samo "wejście", to jeśli użytkownik wejdzie na ofertę ponownie po jakimś czasie (np. następnego dnia lub po jakiejś przerwie od korzystania z serwisu), to policzymy to jako kolejną odsłonę.
