### ISSUE TITLE
Centrum wiadomości - informacja o polu "read" w GET /messaging/threads/{threadId}

### ISSUE THREAD

**Issue by acsklep** [allegro/allegro-api#6405]
Witam
Chodzi o pole "read" gdy pobieram dany wątek z centrum wiadomości np:

GET /messaging/threads/{threadId}

Co dokładnie oznacza pole read? Czy oznacza ono, że jak wyślę komuś wiadomość i ktoś jej nie odczytał to pole read jest "false" a jeśli wiadomość zostanie odczytana to zmieni się na "true"?
Czy chodzi o odczytanie przez odbiorcę czy nadawcę?

W dokumentacji jest tylko napisane:             "read": false,                                        - informacja, czy wątek został odczytany

**Comment by Lukasz-Zurek** [comment]
Tak, tutaj chodzi o odczytanie przez odbiorcę wiadomości, czyli pole "read": true - jeżeli:

- Klient wejdzie do "Centrum wiadomości", do wysłanej przez Sprzedawcy wiadomości i już w tym momencie wartość pola "read" zmienia się z false na true,
- jeśli Sprzedawca skorzysta z opcji [PUT /messaging/threads/{threadId}/read](https://developer.allegro.pl/documentation/#operation/changeReadFlagOnThreadPUT) - czyli oznaczy wybrany wątek jako przeczytany.
