### ISSUE TITLE
Weryfikacja

### ISSUE THREAD

**Issue by kacperson** [allegro/allegro-api#6406]
Czy mógłbym prosić o weryfikację mojej aplikacji "zabawkUwU" aby dostać możliwość korzystania z "[GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing)" ?

**Comment by hahyes** [comment]
> Czy mógłbym prosić o weryfikację mojej aplikacji "zabawkUwU" aby dostać możliwość korzystania z "[GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing)" ?

https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk
Tutaj nikt ci takiej weryfikacji nie da.

**Comment by Lukasz-Zurek** [comment]
@kacperson W celu uzyskania dostępu do zasobu skontaktuj się proszę ze swoim opiekunem (jeżeli go posiadasz) lub bezpośrednio poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=78c31546-41e0-4305-8a41-4415ed3bd32c&subjectId=e6bcf131-deb8-4c2e-88cb-d929981a108c).
