### ISSUE TITLE
Produktyzacja wyszukiwanie produktów znaki specjalne

### ISSUE THREAD

**Issue by Troom** [allegro/allegro-api#6407]
Mam problem z znalezieniem produktu który zawiera dwukropek, nawiasy lub inna przyczyne. Problem dotyczy wszystkich kart Art Series (jest ich więcej). Pozostałe produkty działaja jak należy.

Przykładowa Nazwa towaru: Art Series: Forest (V.2)
Sam produkt istnieje na allegro: 
![image](https://user-images.githubusercontent.com/10126507/204092063-2694d1a7-4f55-44df-8077-fd20dcf46e70.png)

Moj request:
https://api.allegro.pl/sale/products?phrase=Art%20Series:%20Forest%20(V.2)%20XZNR%20MTGMarket&category.id=6093
Response nie zawiera produktów. Nazwa i kategoria jest zgodna z produktem który znajduje na Allegro.

Podczas próby dodania produkty otrzymuje informacje ze taki produkt już istnieje.

**Comment by Lukasz-Zurek** [comment]
@Troom W odpowiedzi na powyższy request otrzymałem jeden produkt - "24a88361-b5df-4ef7-b930-626553be7a38" - "Magic: The Gathering Art Series: Forest (V.2) XZNR MTGMarket".
