### ISSUE TITLE
MultipleProductsFoundException

### ISSUE THREAD

**Issue by ghost** [allegro/allegro-api#6408]
Witam co robi się w przypadku takiego bledu przy wystawianiu produktu:

  "errors" => array:1 [
    0 => array:5 [
      "code" => "MultipleProductsFoundException"
      "message" => "Unprocessable Entity"
      "details" => null
      "path" => "productSet[0].product"
      "userMessage" => "Could not find a precisely matching product."
    ]
  ]
]

Błąd powstaje przy dodawaniu produktów po EAN lub kodzie producenta gdy w katalogu pod jednym z tych numerów są 2 lub wiecej sugerowane produkty.

**Comment by AureliuszBrussy** [comment]
W pierwszej kolejności próbujemy rozróżnić produktu po parametrach, więc jeżeli produkty różnią się jakimś parametrem - wybierzemy ten, który bardziej odpowiada Twojemu requestowi. 
Jeżeli jednak takie rozróżnienie nie jest możliwe, najlepszym rozwiązaniem będzie sprawdzenie tych produktów ([GET /sale/products](https://developer.allegro.pl/documentation#operation/getSaleProducts)) i wskazanie w requeście konkretnego produktu (przez przekazane id wybranego produktu), który ma zostać w ofercie użyty.
