### ISSUE TITLE
PARAMETER_MISMATCH przy wystawianiu ofert ze zmiennym parametrem z katalogu

### ISSUE THREAD

**Issue by bzass** [allegro/allegro-api#6409]
Występuje problem:
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
https://api.allegro.pl.allegrosandbox.pl/sale/product-offers

**Trace-id (dla wywołania kończącego się błędem): 33f1218df7f27a0a**
Trace-id (dla analogicznego wywołania, które kończy się sukcesem): bffd76c0cfd18d63

Korzystamy z metody Web API /sale/product-offers do wystawiania ofert biżuterii. Pojawił się problem podczas wystawiania dodatkowych rozmiarów pierścionków w sytuacjach, w których wcześniej była już wystawiona oferta produktu z inną wartością parametru 372 Rozmiar (Allegro nie pozwala na wystawienie dodatkowej oferty tego samego produktu z inną wartością parametru Rozmiar - 372). 

Błąd jaki się pojawia np. przy próbie wystawienia pierścionka o rozmiarze 17, kiedy wystawiona jest już oferta z produktu o rozmiarze 13 to Unprocessable Entity (422):
```json
{
    "errors": [
        {
            "code": "PARAMETER_MISMATCH",
            "message": "The provided parameter 'Rozmiar/Średnica wew. (mm)'(372) value (17/18,00(372_17)) does not match the existing parameter value (13/16,67(372_13))",
            "details": null,
            "path": "productSet[0].product.parameters",
            "userMessage": "The specified product exists. The specified parameter `Rozmiar/Średnica wew. (mm)` with the value `17/18,00(372_17)` does not match the product parameter `13/16,67(372_13)`."
        }
    ]
}
```

Co ciekawe, dotyczy to tylko niektórych pierścionków i to dopiero od niedawna (kilka tygodni temu funkcjonalność działała bez zarzutu). W przypadku niektórych pierścionków problem nie występuje. Nie jesteśmy w stanie określić od czego zależy to, że dla niektórych produktów pojawia się błąd a dla innych nie.

W załączniku dwa przykładowe żądania POST API /sale/product-offers wywoływane w środowisku Allegro Sandbox. Pierwszy (trace-id: 33f1218df7f27a0a) - kończący się opisanym błędem. Drugi analogiczny dla innego produktu kończący się sukcesem i wystawieniem dodatkowego rozmiaru (trace-id: bffd76c0cfd18d63). Nazwy załączonych plików sugerują których wywołań dotyczą.

Wygląda to na problem po stronie Allegro - parametr 372 Rozmiar (dla niektórych zestawów parametrów / kategorii ? ) traktowany jest jako parametr, który musi być zawsze taki jak w katalogu produktów i nie można wystawić dwóch różnych ofert danego produktu z innym rozmiarem. Tymczasem powinna być możliwość wystawienia dwóch ofert tego samego produktu o różnych wartościach parametru Rozmiar (372) - tak zresztą było jeszcze kilka tygodni temu i dla niektórych produktów tak to nadal działa.

Z góry dziękujemy za pomoc w usunięciu błędu.

[ok - sale-product-offers - traceid bffd76c0cfd18d63.txt](https://github.com/allegro/allegro-api/files/10099092/ok.-.sale-product-offers.-.traceid.bffd76c0cfd18d63.txt)
[error - sale-product-offers - traceid 33f1218df7f27a0a.txt](https://github.com/allegro/allegro-api/files/10099093/error.-.sale-product-offers.-.traceid.33f1218df7f27a0a.txt)

**Comment by AureliuszBrussy** [comment]
Dziękuję za szczegółowe opisanie problemu. Wyjaśniam to - wrócę do Ciebie z odpowiedzią.

**Comment by bzass** [comment]
@AureliuszBrussy czy może udało się już wyjaśnić coś w zakresie tego problemu?

**Comment by AureliuszBrussy** [comment]
Niestety, ale wciąż czekam na wyjaśnienie. Wrócę do Ciebie od razu gdy coś ustalę.

**Comment by bzass** [comment]
@AureliuszBrussy czy istnieje możliwość podwyższenia priorytetu po stronie Allegro? Powoduje on brak możliwości wystawiania niektórych ofert co w grudniowym okresie przekłada się na straty finansowe. Zgłoszenie czeka już 2 tygodnie na reakcję Allegro.

**Comment by AureliuszBrussy** [comment]
@bzass staram się możliwie najszybciej to wyjaśnić. Prosiłbym o jeszcze trochę cierpliwości.

**Comment by AureliuszBrussy** [comment]
@bzass wdrożyliśmy poprawkę. Jeżeli napotykasz jeszcze na podobny problem - daj znać.

**Comment by bzass** [comment]
@AureliuszBrussy bardzo dziękuję. Niestety wygląda na to, że problem nadal występuje. Dodatkowo pojawił się problem #6477. Wieczorem uzupełnię jeszcze informacje, ponieważ znaleźliśmy podobny problem z innym parametrem w innej kategorii - być może się przyda.

**Comment by AureliuszBrussy** [comment]
Potwierdzam, że wczoraj, od 13:00 do 21:30, wystąpił problem po naszej stronie, przez który edycja części ofert kończyła się błędem takim jak w zgłoszeniu #6477. Przepraszam za niedogodności.

Natomiast jeżeli problem z PARAMETER_MISMATCH wciąż występuje - prześlij proszę przykładowe trace-id z nowymi przykładami.

**Comment by AureliuszBrussy** [comment]
@bzass w tej kategorii produkt o innym rozmiarze potraktujemy jako osobny, nowy produkt. Jeżeli nie wskażesz w swoim requeście konkretnego produktu po MPN (numerze katalogowym) w polu **productSet.product.id** - wtedy utworzymy kolejny, nowy produkt w innym rozmiarze i nie zwrócimy błędu PARAMETER_MISMATCH.

**Comment by bzass** [comment]
@AureliuszBrussy bardzo dziękuję za odpowiedzi. Mam kilka dodatkowych obserwacji. Problem może być nieco szerszy i związany z tym jak tworzone są produkty w katalogu przez /sale/product-offers lub jest coś oczywistego czego nie doczytałem (chociaż jakiś czas temu problem nie występował). 

Błędy nie dotyczą wyłącznie parametru Rozmiar (372) w przypadku pierścionków. Zaobserwowaliśmy go również dla parametru Długość całkowita (2206) dla łańcuszków. W przypadku tych produktów istnieje taki sam numer katalogowy / producenta dla wielu rozmiarów (w przypadku pierścionków) lub długości (dla łańcuszków). 

Problem polega na tym, że wskazane parametry (np. 372, 2206) niepotrzebnie są zapisywane do katalogu po wysyłaniu ich do /sale/product-offers. Powinny być ignorowane przez Allegro, ponieważ są unikalne dla każdej z ofert i nie powinny trafiać do katalogu. Być może tworzenie produktu przez /sale/product-offers błędnie nie odfiltrowuje tych parametrów lub parametry nie są oznaczone po stronie Allegro jako unikalne dla ofert (dopuszczając możliwość podawania innych wartości podczas tworzenia ofert). 

Może po stronie Allegro niektóre parametry kategorii powinny mieć flagę np. "offer-unique" tak aby przy dodawaniu produktów do katalogu w danej kategorii przez /sale/product-offers takie parametry nigdy nie trafiały do katalogu? Tylko, że w takim wypadku będzie problem jeśli akurat jakiś producent stosuje różne kody dla różnych wariantów produktu. 
Druga sensowniejsza chyba opcja to przekazywanie flagi "offer-unique" przy parametrach przekazywanych do /sale/product-offers lub osobnej kolekcji "offer-unique-param-ids". Wtedy Allegro będzie wiedziało, że akurat dla tego kodu producenta oznaczony w ten sposób parametr nie powinien trafić do katalogu, ponieważ producent stosuje te same kody dla różnych rozmiarów (czy innych parametrów charakteryzujących wariant - np. kolor). Parametru oczywiście nie można po prostu pominąć, ponieważ jest obowiązkowy dla danej kategorii. 

O tym, że rozmiary niepotrzebnie trafiają do katalogu można się przekonać próbując utworzyć ofertę przez formularz Allegro podając "nazwę lub kod produktu": CL18846. 

![image](https://user-images.githubusercontent.com/12543258/207586603-20f12196-e710-4e61-8689-33d6f1da39ee.png)

Jak widać w katalogu jest "długość całkowita: 45" co blokuje możliwość wystawiania ofert tego samego produktu z innymi długościami (chociaż każdy wariant to ten sam produkt / ten sam kod producenta). Także przez formularz Allegro nie można wtedy wystawić oferty o innej długości co jest błędem. Domyślam się, że w przypadku wielu innych produktów każdy rozmiar ma inny kod producenta i powinien mieć osobny wpis w katalogu. Jednak są sytuacje takie jak w przypadku biżuterii, kiedy mamy różne rozmiary pomimo tego samego kodu producenta. 
Obejściem problemu może być tworzenie osobnego wpisu w katalogu dla każdego rozmiaru pierścionka / łańcuszka, ale wtedy należy tworzyć nieistniejący w rzeczywistości kod producenta (np. CL18846-45 jak w tym wypadku dla długości 45) i taki produkt będzie niemożliwy do wykorzystania przez innych użytkowników Allegro, ponieważ faktyczny kod producenta to CL18846 (dla każdego rozmiaru) a obejście z dopisywaniem rozmiarów po myślniku będzie znane tylko dla osoby, która je zastosowała. Spowodowałoby to duży bałagan w katalogu.

**Co ciekawe, wszystko wcześniej działało poprawnie i problem pojawił się dopiero ok. 1.5 miesiąca temu.** Widać to na przykładzie produktu o kodzie PW50984. Tu oferty tego produktu wystawione kiedyś przez /sale/product-offers: 12962989840, 12962989953, 12962990076, 12962990238 (każda z innym rozmiarem). Jak widać API działało wtedy tak, że pozwalało dodać kilka produktów do katalogu o różnych rozmiarach

![image](https://user-images.githubusercontent.com/12543258/207588755-90c26c3d-d3c0-42f1-b85f-2985b3839b50.png)

Sprawdziłem jak wygląda[ request załączony w pierwszym wpisie jako poprawny](https://github.com/allegro/allegro-api/files/10099092/ok.-.sale-product-offers.-.traceid.bffd76c0cfd18d63.txt). Po wprowadzeniu poprawki przez Allegro także ten request kończy się błędem PARAMETER_MISMATCH. Jest to przynajmniej już spójne (w katalogu dla produktu 18882/1 jest zapisany rozmiar) - ale wcześniej te requesty działały. Wcześniej katalog dopuszczał zapisanie w nim kilku wariantów posiadających ten sam kod produktu (i tak działało /sale/product-offers) - teraz to samo API generuje PARAMETER_MISMATCH zamiast dodać wariant z tym samym kodem produktu do katalogu.

Dlatego podsumowując - wydaje mi się, że takie parametry jak 372 czy 2206 powinny być odfiltrowywane podczas dodawania do katalogu (ew. specjalnie oznaczane przez użytkownika API, aby je ignorować podczas dodawania) lub oznaczone jako możliwe do modyfikacji podczas wystawiania ofert. **Albo też katalog powinien dopuszczać kilka wpisów z tym samym kodem, ale innymi parametrami (tak jak kiedyś).**

----

Poniższe może pomóc w diagnostyce, chociaż problem jest raczej projektowy (lub coś przegapiłem w dokumentacji).

**Przykładowy pierścionek:**

CURL kończący się poprawnym utworzeniem oferty: [ringsize-OK.txt](https://github.com/allegro/allegro-api/files/10227024/ringsize-OK.txt)
trace-id: d56759a893399f70
offer: 13019380036

CURL kończący się błędem: [chainlength-ERROR.txt](https://github.com/allegro/allegro-api/files/10227021/chainlength-ERROR.txt)
trace-ids: c95a4b1bdd3a95c7, 56a7621124d590d4, f81321e082a4d254

Błąd:
```json
{
    "errors": [
        {
            "code": "PARAMETER_MISMATCH",
            "message": "The provided parameter 'Rozmiar/Średnica wew. (mm)'(372) value (17/18,00(372_17)) does not match the existing parameter value (13/16,67(372_13))",
            "details": null,
            "path": "productSet[0].product.parameters",
            "userMessage": "The specified product exists. The specified parameter `Rozmiar/Średnica wew. (mm)` with the value `17/18,00(372_17)` does not match the product parameter `13/16,67(372_13)`."
        }
    ]
}
```

**Przykładowy łańcuszek**

CURL kończący się poprawnym utworzeniem oferty: [chainlength-OK.txt](https://github.com/allegro/allegro-api/files/10227022/chainlength-OK.txt)
trace-id: 15ef335079e2f82f
offer: 13019437409

CURL kończący się błędem: [ringsize-ERROR.txt](https://github.com/allegro/allegro-api/files/10227023/ringsize-ERROR.txt)
trace-ids: 4c9ca49ffa3bf5f3, 252305a186783827, 423628f2285a80ed

```json
{
    "errors": [
        {
            "code": "PARAMETER_MISMATCH",
            "message": "The provided parameter 'Długość całkowita'(2206) value (42.00) does not match the existing parameter value (45.00)",
            "details": null,
            "path": "productSet[0].product.parameters",
            "userMessage": "The specified product exists. The specified parameter `Długość całkowita` with the value `42.00` does not match the product parameter `45.00`."
        }
    ]
}
```

**Comment by AureliuszBrussy** [comment]
Dziękuję za spostrzeżenia. Przekazaliśmy je do zespołu odpowiadającego za katalog produktów. Jednocześnie sprawdzamy jeszcze kwestię tworzenia nowych produktów dla innych rozmiarów. 

Tak jak wspomniałem, na ten moment możesz utworzyć nowy produkt bez błędu PARAMETER_MISMATCH jeżeli w requeście nie przekażesz kodu producenta w polu **productSet.product.id**. Wtedy nie będziemy wymagać dokładnej zgodności parametrów, ale utworzymy produkt w innym wariancie (rozmiarze).

**Comment by bzass** [comment]
Bardzo dziękuję! Rzeczywiście bez przekazania kodu produktu działa. Czy jest to tymczasowe obejście i docelowo kod produktu będzie wymagany?
