### ISSUE TITLE
DoMyAccount2Request

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#641]
Ciekawostka taka. Ściągam za pomocą DoMyAccount2Request wszystkie aukcje not_sold, które nie zostały jeszcze archiwizowane. Jest ich dużo. Asynchronicznie zapuszczam serię requestów z offsetem za każdym razem większym o 100 (0, 100, 200 itd) oraz limitem zawsze wynoszącym 100. Gdy mam już wszystkie wyniki, niemal zawsze okazuje się, że część zwracanych w tej metodzie MyAccountArray została pobrana dwukrotnie. Łączna liczba pobranych MyAccountArray jest stała. Najstarsze i najnowsze są te same (więc w międzyczasie nic na listę nie wpadło ani z niej nie wyleciało). 
Od przybytku głowa co prawda nie boli, ale boje się, że skoro zdarza się, że niektóre zaciąga podwójnie to innych może nie zaciągać wcale.
O co może więc chodzić?

**Comment by LukaszKorek** [comment]
Aby kwestia mogła być w pełni zweryfikowana podeślij proszę pełen request i response w formacie .xml.

**Comment by lukada4100** [comment]
Już chyba wiem o co chodzi. Zwracane metodą doMyAccount2Request myAccountArray posortowane są malejąco wg daty zamknięcia (i chyba wg żadnego innego kryterium). Więc w sytuacji, gdy jest na tyle dużo licytacji z tą samą datą zamknięcia, że nie mieszczą się wszystkie w jednym responsie, zdarza, że że w kolejnym responsie są zwracane jeszcze raz.
Gdy próbuję zaciągnąć wszystkie aukcje, które nie zostały jeszcze zarchiwizowane, łączna ich liczba za każdym razem jest taka sama, wśród nich niemal zawsze jest jakaś ilość podwójnych, co oznacza, że taka sama ilość aukcji nie została pobrana.

Na potrzeby zgłoszenia pobierałem 100 najnowszych zakończonych aukcji, z limitem 5, za każdym razem zwiększając offset o 5. Ze stu zwróconych łącznie aukcji łącznie powtarza się 5. [Ticket#1251687040]
Każdorazowe wysłanie tego samego zestawu requestów zwraca różne wyniki - liczba powtarzających się aukcji też waha się.

**Comment by LukaszKorek** [comment]
Poproszę jeszcze o nr przykładowych ofert, które się dublują w danym wywołaniu.

**Comment by lukada4100** [comment]
7571748411
7571773185
7571994011
7571717204
7571718069

**Comment by LukaszKorek** [comment]
Pracujemy nad rozwiązaniem problemu. Wkrótce powinien przestać występować.

**Comment by lukada4100** [comment]
Dajcie proszę znać gdy się uda sprawę załatwić.
