### ISSUE TITLE
Weryfikacja API

### ISSUE THREAD

**Issue by Przemek-93** [allegro/allegro-api#6410]
Dzień dobry,
Postanowiłem zadać pytanie na githubie ponieważ odbijam się od działu weryfikacyjnego.

Od dłuższego czasu mam zaimplementowaną integrację z Allegro API, używałem jej wyłącznie do pobierania produktów po słowie kluczowym. W związku ze zmianami po waszej stronie w 2021 roku integracja przestała działać, a konto powinno zostać ponownie zweryfikowane, jednak po licznych próbach kontaktu (zazwyczaj brak odpowiedzi) w końcu zasugerowano mi założenie issue na githubie co może może przyśpieszyć proces. 

Przechodząc do sedna pozwolę sobie wkleić kilka zrzutów:
zapytania o accessToken:
![image](https://user-images.githubusercontent.com/77680155/204213795-51489bc9-1416-4aca-ba1d-44544e2bcb74.png)

główny request:
![image](https://user-images.githubusercontent.com/77680155/204213932-b5abaf55-9053-4533-87ea-85df576a41fe.png)

response:
![image](https://user-images.githubusercontent.com/77680155/204214009-111042c9-7549-45fe-a14c-98e460a55393.png)

ClientId: 7dac0874cc8547538e518a967a813ab9

Bardzo proszę o sprawdzenie czy requesty wykonywane są w poprawny sposób i zajęcie się sprawą/pokierowanie tak abym znów mógł cieszyć się działającą integracją.

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Tutaj nie chodzi o requesty - otrzymujesz błąd, ponieważ nie masz zweryfikowanej aplikacji. Ograniczenia dla tego zasoby wprowadziliśmy 1 czerwca 2021, o czym informowaliśmy [tutaj](https://developer.allegro.pl/news/wprowadzilismy-ograniczenia-dla-get-offers-listing-WvGz1qOlxc6). 

Niestety zostałeś źle przekierowany, ponieważ nie zajmujemy się weryfikacją. Jest to proces, na który nie mamy żadnego wpływu. W celu uzyskania dostępu do zasobu musisz skontaktować się poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=78c31546-41e0-4305-8a41-4415ed3bd32c&subjectId=e6bcf131-deb8-4c2e-88cb-d929981a108c), lub kontynuując korespondencję w rozpoczętej już sprawie.

**Comment by Przemek-93** [comment]
Ok rozumiem. Dziękuję za odpowiedź.
