### ISSUE TITLE
Allegro default category code

### ISSUE THREAD

**Issue by autodocallegro** [allegro/allegro-api#6411]
Dear everyone,
we do sell products in Automotive category.

When the system wasn't able to recognize category, we have used category code 620. But now it's not relevant anymore. 
Have you got any recommendations about another categories we can use as a default once? We're thinking on 3618,Motoryzacja
14899,Motoryzacja. Perhaps they're gonna fit.

Thank and regards,
Autodoc Team

**Comment by MaciejFrackowiak** [comment]
Category 620 is not a leaf category, so you cannot list offers there.
Category 14899 is a leaf category, but it is connected with the main category "Collections and Art", not "Automotive".
You as a seller decide which category suits the best for your items. You can browse Allegro categories by [GET /sale/categories](https://developer.allegro.pl/documentation/#operation/getCategoriesUsingGET) resource.
