### ISSUE TITLE
Sandbox - Wysyłam z Allegro umowa własna

### ISSUE THREAD

**Issue by bartekc7** [allegro/allegro-api#6413]
Dzień dobry,
Czy w  środowisku sandbox nie da sie dodać umowy Inpost z tokenem do ich api testowego?
Z tokenem produkcyjnym dodaje się bez problemu.
Jak w tym wypadku przetestować jedną z takich wysyłek które wymagają dodania umowy własnej? 

![image](https://user-images.githubusercontent.com/207927/204251737-cd9b461d-9523-4581-b8de-b9dfbb5cc882.png)

**Comment by MaciejFrackowiak** [comment]
Sprawdź proszę token do środowiska testowego InPost - my nie mamy de facto wpływu na zwracany komunikat, który widzimy na zrzucie.

**Comment by bartekc7** [comment]
Token jest ok. Przesyłki moge wystawiać bezpośrednio przez API Inpost. 
Na sandbox w Allegro niestety mogę zarejestrować tylko token do produkcyjnego API.
Pytanie czy wystawiona przesyłka w sandboxie API Allegro na tokenie produkcyjnym Inpost zostanie zarejestrowana jako produkcyjna czy testowa?

**Comment by PrzemyslawLukanowski** [comment]
W takim przypadku nasze dane/zamówienie będą testowe, ale etykiety będą produkcyjne.

**Comment by bartekc7** [comment]
Ok, dziękuje za odpowiedź. Wysłałem zapytanie do Inpost w tej sprawie.

**Comment by bartekc7** [comment]
Dostałem odpowiedź sugerującą że to nie jest problem po stronie Inpost że nie mogę w sandboxie Allegro zarejestrować tokena do sandbox Inpost. 
![image](https://user-images.githubusercontent.com/207927/204781556-bc6a46cc-8cca-4043-a746-8b9f18b40425.png)

**Comment by PrzemyslawLukanowski** [comment]
Konsultuję ten temat z odpowiednim zespołem. Prosiłbym o cierpliwość, wrócę z informacją.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowaliśmy tę sytuację - problem leży po stronie InPost, ponieważ przewoźnik wymaga od nas token do innego środowiska niż Sandbox. Zgłosiliśmy już ten problem bezpośrednio do InPost. Czy mógłbym dodatkowo poprosić Cię o ID login/użytkownika?

**Comment by bartekc7** [comment]
Login Allegro Sandbox: StreamTest
Id organizacji w API sandbox Inpost: 249 zarejestrowany na konto:  
Allegro i Inpost zarejestrowane na email: b.ciupa@streamsoft.pl
