### ISSUE TITLE
ConstraintViolationException.MaxInactiveOffers przy każdej próbie wystawienia oferty

### ISSUE THREAD

**Issue by podniesm** [allegro/allegro-api#6414]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

POST https://api.allegro.pl/sale/product-offers
Response:
`{"errors":[{"code":"ConstraintViolationException.MaxInactiveOffers","message":"You cannot create new drafts - your account has exceeded the maximum number 20000 of drafts.","details":"ConstraintViolationException.MaxInactiveOffers","path":"null","userMessage":"Nie możesz utworzyć nowych szkiców - Twoje konto przekroczyło maksymalną liczbę 20000 szkiców."}]}`

trace-id: 199a534cb9cbf60b

Przy każdej próbie utworzenia oferty dla danego konta dostaje błąd z kodem `ConstraintViolationException.MaxInactiveOffers`. Jest to o tyle dziwne, że konto nie ma żadnych szkiców .

**Comment by MaciejFrackowiak** [comment]
Problem potwierdzam, przekazałem do odpowiedzialnego zespołu.

**Comment by MaciejFrackowiak** [comment]
Poprawiliśmy już liczbę draftów na wskazanym koncie.
