### ISSUE TITLE
GET /sale/offer-events nie zwraca danych przy ukryciu oferty w panelu WWW

### ISSUE THREAD

**Issue by dawidczech355a** [allegro/allegro-api#6415]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis**
Zasób `/sale/offer-events` nie zwraca żadnej informacji o ukryciu oferty przez panel klienta WWW. Czy istnieje możliwość, aby taka zmiana była również trackowana przez wspomniany endpoint?

Nie wiem jak mogę traktować taką ofertę, jeżeli nie da się jej przywrócić z ukrytych ofert to czy mam ją traktować jako zarchiwizowaną? Jeżeli tak to czy API może zwracać z wyżej wspomnianego endpointu, jako `{ type: OFFER_ARCHIVED }`? Jeżeli nie to czy istnieje możliwość rozszerzenia API o typ np. `OFFER_HIDDEN`?
Jeżeli istnieje jakaś możliwość, aby rozpoznać, że oferta została ukryta - bardzo prosiłbym o nakierowanie jak to zrobić.

**Comment by AureliuszBrussy** [comment]
Funkcja ukrywania zakończonej oferty występuje tylko w panelu WWW w zakładce [Mój asortyment](https://allegro.pl/moje-allegro/sprzedaz/obsluga-ofert/moj-asortyment). Funkcjonalność polega tylko na wykluczeniu oferty z widoku - w żaden sposób nie zmienia się jej stan, a co za tym idzie, zmiana jest całkowicie transparentna w API i nie ma możliwości rozpoznania tego faktu. 

Otrzymywaliśmy już sugestię dot. wdrożenia takiej funkcjonalności w API. Możesz dodać swój głos [w wątku](https://github.com/allegro/allegro-api/discussions/4330).

**Comment by mloncur** [comment]
> Funkcja ukrywania zakończonej oferty występuje tylko w panelu WWW w zakładce [Mój asortyment](https://allegro.pl/moje-allegro/sprzedaz/obsluga-ofert/moj-asortyment). Funkcjonalność polega tylko na wykluczeniu oferty z widoku - w żaden sposób nie zmienia się jej stan, a co za tym idzie, zmiana jest całkowicie transparentna w API i nie ma możliwości rozpoznania tego faktu.
> 
> Otrzymywaliśmy już sugestię dot. wdrożenia takiej funkcjonalności w API. Możesz dodać swój głos [w wątku](https://github.com/allegro/allegro-api/discussions/4330).

Wspomniany wątek dotyczy innego tematu(dodanie opcji ukryj do API)

W tym temacie chodzi o informację w zasobie /sale/offer-events o tym, że oferta została ukryta tak by można było przenieśc ją w aplikacji pod inny status(nasz wewnętrzny)

**Comment by AureliuszBrussy** [comment]
Rozumiem, moglibyśmy potencjalnie dodać tą opcję kompleksowo, dlatego podrzuciłem wątek, w którym poruszony był temat dot. ukrywania ofert. @dawidczech355a możesz także utworzyć nowy wątek w [Discussions](https://github.com/allegro/allegro-api/discussions) z tą konkretną sugestią.

**Comment by dawidczech355a** [comment]
Sugestia: https://github.com/allegro/allegro-api/discussions/6417
