### ISSUE TITLE
Problem z pobraniem etykiety dla istniejącej przesyłki

### ISSUE THREAD

**Issue by mstrojecki** [allegro/allegro-api#6418]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Pobierając informację o wcześniej utworzonej przesyłce 8a38e610-b696-41a2-9024-5fd4e9a58ea7 (GET parcel-management/parcel-create-commands/8a38e610-b696-41a2-9024-5fd4e9a58ea7) dostaję odpowiedź SUCCESS:
Array
(
    [id] => 8a38e610-b696-41a2-9024-5fd4e9a58ea7
    [parcelId] => 845b6eec-5702-4545-9abc-a1871ef66d7a
    [status] => SUCCESS
    [errors] => Array
        (
        )

)

Natomiast w dalszej kolejności próba pobrania etykiety dla danego parcelId (GET parcel-management/parcels/label?parcelId=845b6eec-5702-4545-9abc-a1871ef66d7a&pageFormat=A6) zwraca błąd:
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ERROR
                    [message] => Label doesn't exist
                    [details] => 
                    [path] => /parcel-management/parcels/label?parcelId={parcelId}
                    [userMessage] => Etykieta nie istnieje
                )
        )
)

Skąd ten błąd i co zrobić w tej sytuacji? Nie wiem czy mogę wymusić ponowne wygenerowanie etykiety, bo skoro jest już jedna przesyłka to pewnie kolejna nie będzie Smart.

**Comment by hahyes** [comment]
@mstrojecki Zasób `GET parcel-management/parcel-create-commands/8a38e610-b696-41a2-9024-5fd4e9a58ea7` zwraca status dodania polecenia utworzenia paczki do kolejki, nic więcej. Musisz odpytać zasób `GET parcel-management/parcel-create-commands/8a38e610-b696-41a2-9024-5fd4e9a58ea7/tasks`. Wtedy otrzymasz potwierdzenie utworzenia paczki bądź potencjalne błędy. Etykieta nie istnieje, ponieważ przesyłka najwyraźniej nie powstała.

**Comment by mstrojecki** [comment]
@hahyes Cos chyba nie tak

GET parcel-management/parcel-create-commands/8a38e610-b696-41a2-9024-5fd4e9a58ea7/tasks

Response:
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => NotFoundException
                    [message] => Not found
                    [details] => 
                    [path] => 
                    [userMessage] => Funkcja niedostępna. Skontaktuj się z autorem aplikacji.
                )
        )
)

Z resztą w dokumentacji również nie widzę nic o tym zasobie /tasks

**Comment by hahyes** [comment]
@mstrojecki Prawda, pamięć zaszwankowała. Dla ofert występuje zasób w takiej postaci (dla tej samej funkcjonalności sprawdzenia statusu zadania). Dla paczek właśnie odpytywałeś prawidłowo, bo tam zasobu /tasks nie ma. W takim razie dev musi zerknąć, co się stało. 

@PrzemyslawLukanowski

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem ten problem z zespołem odpowiedzialnym za usługę, który potwierdził, że mogły wystąpić chwilowe problemy związane z pobieraniem etykiet. Planujemy wdrożyć dziś odpowiednią poprawkę, która umożliwi wydruk tej przesyłki, w tym czasie możesz utworzyć nową paczkę.

**Comment by mstrojecki** [comment]
@PrzemyslawLukanowski czy z usługą Smart będzie wszystko ok?  Druga paczka będzie Smart'owa, skoro jest już wygenerowana jedna?

**Comment by PrzemyslawLukanowski** [comment]
@mstrojecki Problem wystąpiłby tylko dla InPostu, w Twoim przypadku - Allegro One Box, One Kurier - będzie ok, potwierdziłem to z zespołem.

**Comment by mstrojecki** [comment]
@PrzemyslawLukanowski nie zakładam nowego wątku bo to pewnie powiązane ze sobą sprawy.
Dziasiaj dla GET parcel-management/parcel-create-commands/c682f138-040b-492e-9afd-066ee181e1a3
otrzymuję:
Array ( [id] => c682f138-040b-492e-9afd-066ee181e1a3 [parcelId] => [status] => ERROR [errors] => Array ( [0] => Array ( [code] => ERROR [message] => Processing error [details] => [path] => [userMessage] => Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej. ) ) )

**Comment by PrzemyslawLukanowski** [comment]
Problemem jest długość nazwy ulicy - maksymalna wartość to 35 znaków. Analizujemy, dlaczego ten błąd nie został zwrócony w odpowiedzi. Po znalezieniu przyczyny wprowadzimy poprawkę w komunikacie.
