### ISSUE TITLE
Błąd z wartością typu float w parametrach

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#6419]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
korzystam z produkturyzacji do pobrania parametrów produktu. 
Kategoria: Dom i ogród -> Wyposażenie -> Ozdoby świąteczne i okolicznościowe -> Boże Narodzenie -> Oświetlenie choinkowe
EAN: 5904955107225

Odpowiedź Allegro: Wskazany produkt istnieje. Przesłany parametr `Długość sznura` o wartości `5.80` nie pasuje do parametru produktu `5.8`.

z perspektywy tego że to parametr float i to tak na prawdę ta sama wartość nie powinniście takiej wartości przepuszczać?

Tyczy się to też innych parametrów float

**Comment by PrzemyslawLukanowski** [comment]
Dla POST /sale/product-offers i PATCH /sale/product-offers/{offerId} wprowadziliśmy w zeszłym tygodniu zmianę, dzięki której możesz przekazywać takie wartości parametrów. Czy korzystasz z tych endpointów? Czy możesz podać trace-id, gdzie mimo to zwróciliśmy błąd?
