### ISSUE TITLE
Zakup allegroSMART - rozliczenie klienta

### ISSUE THREAD

**Issue by mack3d** [allegro/allegro-api#642]
Dzień dobry,
w dniu wczorajszym napotkałem na taki problem: klient dokonał zwrotu towaru za wysyłkę którego skorzystał z wykupionego pakietu allegroSmart.
Ów klient nie wypełnił formularza odstąpienia od umowy w terminie 14 dni poprzez serwis tylko po prostu zwrócił towar z danymi do zwrotu kosztów na wskazane konto.

W opisanym przypadku nie otrzymałem informacji czy mam zwrócić koszty dostawy czy też nie, tak jak to ma miejsce w sytuacji gdy klient wypełni formularz.

**Comment by MartaNowaczyk** [comment]
Dzień dobry,
w sprawie odstąpienia od umowy napisz do nas proszę przez [ten formularz](https://allegro.pl/pomoc/kontakt#subjectId=b2c7e9be-301c-441d-9b8d-03b75fa46d91). 
Pozdrawiam

**Comment by mack3d** [comment]
Rozumiem że w ten sposób mogę uzyskać informacje czy kupujący korzystał ze smart allegro?

**Comment by MartaNowaczyk** [comment]
Tak, jeśli jednak klient wypełni formularz zwrotu przez Moje kupione, w treści wiadomości o odstąpieniu od transakcji, poinformujemy, że zakup był z Allegro Smart!
