### ISSUE TITLE
WZA - Allegro One (UPS) nadpisywanie referenceNumber / description

### ISSUE THREAD

**Issue by Sebastian-Le** [allegro/allegro-api#6423]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

trace-id: bf3095154958166c

zgłaszając paczę przekazuję pełne dane wraz z 
"label":{"fileFormat":"ZPL","referenceNumber":"445532"},
"description":"445532 1z1"

ale są one nadpisywane przez treść przekazywaną przez was i efekt jest taki że na etykiecie w polach 
Reference No.1 jest "ALE0000....."
Reference No.2 jest "Operator: Allegro sp. z o.o."

![al](https://user-images.githubusercontent.com/82901132/204586919-ac955657-b2da-42d2-9704-6f52d9a3c7ed.png)

**Comment by PrzemyslawLukanowski** [comment]
Niestety, ale nie każdy przewoźnik pozwala na prezentację przekazanego numeru referencyjnego. Przykro mi, ale nie mamy na tę chwilę możliwości wprowadzenia zmian w tym temacie.

**Comment by Sebastian-Le** [comment]
Obecne podejście, "zamażemy wszystko bo nam wygodnie" rodzi problem z identyfikacją poprawnej etykiety do paczki. 
Przy pakowaniu oklejamy każdą paczkę, własną małą etykietą pozbawioną danych osobowych, na której jest numer referencyjny i 4 ostatnie cyfry numeru telefonu, na etykiecie od allegro one(ups) nie ma żadnej z tych informacji.

Według dokumentacji API UPS, pola ReferenceNumber mogą przyjąć do 35 znaków
![u](https://user-images.githubusercontent.com/82901132/204756221-f4cee193-83dd-458e-aa7b-e815a623d78c.png)

Pierwotnie dobrze zakładaliście i to nawet opisaliście w waszej dokumentacji/poradniku:
![doc](https://user-images.githubusercontent.com/82901132/204757062-98a0f5ff-4c01-434b-87a9-80de8583103d.png)

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, jednak to ograniczenie jest po stronie przewoźnika, nie mamy wpływu na to, jakie informacje zwraca na etykiecie. Dodam odpowiednią adnotację w naszym poradniku, w udostępnionym przez Ciebie fragmencie.

**Comment by Sebastian-Le** [comment]
Idąc waszym tokiem rozumowania... najlepiej po prostu nie wysyłać korzystając z "Allegro One", strata niewielka patrząc na wykorzystywane przez kupujących inne formy dostawy, które oferują przekazywanie referencji od sprzedawcy.

**Comment by Sebastian-Le** [comment]
@MaciejFrackowiak możesz się odnieść do mojej ostatniej  wiadomości ?

**Comment by PrzemyslawLukanowski** [comment]
Jak wspomniałem, jesteśmy uzależnieni w tym przypadku od API przewoźnika, w tym przypadku od UPS. Nie mamy możliwości samodzielnego wprowadzania zmian.

**Comment by tomasz-grzesik** [comment]
I dalej nic? Przecież to jest chore, że nie ma możliwości podać własnego reference number.
Przy takich ograniczeniach bez sensu jest promować całe Allegro One.

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę niestety nie mam nowych informacji. Podniosłem ten temat ponownie dalej, przekazując przy tym Wasze uwagi, które pojawiły się w wątku. Zespół będzie badać, jakie mamy możliwości w kwestii prezentowania dodatkowych danych na etykiecie. Prosiłbym jednak o cierpliwość - ze względu na to, że jesteśmy w tej kwestii uzależnieni od ograniczeń przewoźnika, decyzje, które możemy podjąć, nie są wynikiem wyłącznie naszych ustaleń.

**Comment by tomasz-grzesik** [comment]
Dziękuję.
Jedno z rozwiązań padło wyżej:
"W 1 polu reference zmieścicie:
Operator:Allegro ALE00043C8D9E8
to 31 znaków z 36 dostępnych

2 pole reference mogło by być wtedy prawidłowo przekazywane od sprzedawcy(nadawcy) to przewoźnika i na etykietę.."

**Comment by PrzemyslawLukanowski** [comment]
Takie rozwiązanie niestety odpada, pole ref 2 nie może zostać zmienione - wymóg prawny, i tak ograniczaliśmy zapisy, aby zmieścić wartość w tym polu.  Do pola nr ref 1 nie rekomendujemy zmian, ponieważ klienci/punkty obsługi są uczeni że jest to czysty numer paczki Allegro.

**Comment by tomasz-grzesik** [comment]
Rozumiem. W takim razie ograniczenie jest po stronie UPS.

**Comment by ZAK2828** [comment]
@Sebastian-Le 
> Wątki #5577 i #6198 opisują dokładnie tą samą sytuację, jak potrzebujecie rozwiązania to proszę: W 1 polu reference zmieścicie: Operator:Allegro ALE00043C8D9E8 to 31 znaków z 36 dostępnych
> 
> 2 pole reference mogło by być wtedy prawidłowo przekazywane od sprzedawcy(nadawcy) to przewoźnika i na etykietę..

Czy jakoś wewnętrznie udało się Wam "pokonać" ten problem i przekazujecie jakimś "trickiem" numer referencyjny na etykietę?

**Comment by tomasz-grzesik** [comment]
@PrzemyslawLukanowski a czy API Allegro pozwala na pobranie jakiegokolwiek numeru zakodowanego w kodach kreskowych / kodach QR zawartych na etykiecie?
Chodzi o sposób powiązania etykiety z zamówieniem Allegro.

**Comment by MartaNowaczyk** [comment]
@tomasz-grzesik nie ma takiej możliwości.
