### ISSUE TITLE
Weryfikacja konta

### ISSUE THREAD

**Issue by PawelGluszek** [allegro/allegro-api#6424]
Proszę o weryfikacje konta dostawczaki-com

**Comment by PrzemyslawLukanowski** [comment]
Uzupełnij proszę wszystkie dane niezbędne do aktywacji, np. numer konta bankowego. Pozostałe kroki, które musisz wykonać, znajdziesz w zakładce [Moje Konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto).

**Comment by LewyMistrz** [comment]
prosze o weryfikację konta papes_sandbox

**Comment by PrzemyslawLukanowski** [comment]
@LewyMistrz Aktywowałem Twoje konto.

**Comment by PawelGluszek** [comment]
Uzupełnione

**Comment by PrzemyslawLukanowski** [comment]
@PawelGluszek Dziękuję, Twoje konto również powinno już być w pełni aktywne.

**Comment by krzar** [comment]
Proszę o aktywowanie konta ZebraK

**Comment by PrzemyslawLukanowski** [comment]
@krzar Twoje konto zostało założone na początku sierpnia, jednak w międzyczasie zmieniły się mechanizmy związane z aktywacją po naszej stronie, przez co nie możemy aktualnie zweryfikować Twojego konta. Proszę Cię i założenie nowego konta i jednocześnie przepraszam za niedogodności.

**Comment by MGRINZ** [comment]
Proszę o aktywację konta Format. Dziękuję.

**Comment by PrzemyslawLukanowski** [comment]
@MGRINZ Aktywowałem Twoje konto.
