### ISSUE TITLE
Message Center-Get message

### ISSUE THREAD

**Issue by jizhien** [allegro/allegro-api#6425]
Hi, i am trying to get message data through API- Message center, but it seems that only the full amount of data can be pulled, but new messages cannot be pulled based on time or message status; which means that the more previous meesages, the more time it needs to take to get new message i need.  Is there anything i make mistake? 
![message center](https://user-images.githubusercontent.com/118327418/204744615-b4e0b81b-c999-4228-a5c3-89996c9a75ff.png)
If it is true that only the full amount of data can be pulled each time,do you plan on adding a query parameter for time?

**Comment by PrzemyslawLukanowski** [comment]
Unfortunately, there are no other query parameters and we don't plan to add them right now. The results are sorted by the last message date, so you can save this value on your side when you downloaded threads, and next time, using the offset parameter, you can retrieve threads until you encounter the last saved "lastMessageDateTime".
