### ISSUE TITLE
błąd wystawiania ofert

### ISSUE THREAD

**Issue by testMail1113** [allegro/allegro-api#6426]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

założyłem konto firmowe i zweryfikowałem pierwsze 4 punkty. wpłaciłem nadwyżkę 100zł na konto. gdy próbuje zrealizować 5 punkt weryfikacji czyli wystawić ofertę dostaję 2 błędy. login papes_sandbox

Wystąpił błąd - Prowadząc sprzedaż na koncie zwykłym (nie zarejestrowanym jako konto firma), musisz ustawić czas trwania oferty. Jeśli nie możesz już edytować tej wartości to utwórz nową ofertę korzystając z funkcji "Wystaw Podobną".

Wystąpił błąd - Użytkownik z blokadą konta Firma nie może wystawiać nowych ofert.

**Comment by AureliuszBrussy** [comment]
Powodem braku możliwości wystawienia jest brak zakończonej weryfikacji konta. Poczekaj na odpowiedź w wątku #6424, gdzie zgłoszono prośbę o aktywację konta papes_sandbox.
