### ISSUE TITLE
Zablokowana sprzedaż sanbox 

### ISSUE THREAD

**Issue by riepa** [allegro/allegro-api#6427]
Mam zablokowaną sprzedaż na koncie Kokoszambo mimo dodatniego salda

**Comment by AureliuszBrussy** [comment]
Usunęliśmy blokadę - możesz swobodnie wystawiać oferty.

**Comment by riepa** [comment]
dziękuję

**Comment by ofixit** [comment]
Witam,
Mam ten sam problem - proszę o zdjęcie blokady.
Nazwa konta: ofixsandbox

**Comment by AureliuszBrussy** [comment]
@ofixit i tutaj usunęliśmy blokadę.

**Comment by ofixit** [comment]
dzięki

**Comment by Piotr89-sol** [comment]
Dzień dobry, mam także zablokowane konto - saldo nie jest już ujemne. Prośba o odblokowanie. 
konto: test_sprzedawca
Dziekuję

**Comment by MaciejFrackowiak** [comment]
@Piotr89-sol Blokada zdjęta.
