### ISSUE TITLE
wystawianie oferty POST sale/product-offers

### ISSUE THREAD

**Issue by reprezenter** [allegro/allegro-api#6429]
Wysyłam parametry:
array(1) {
  ["productSet"]=>
  array(1) {
    [0]=>
    array(13) {
      ["parameters"]=>
      array(7) {
        [0]=>
        array(4) {
          ["id"]=>
          string(5) "11323"
          ["valuesIds"]=>
          array(1) {
            [0]=>
            string(7) "11323_1"
          }
          ["values"]=>
          array(0) {
          }
          ["rangeValue"]=>
          NULL
        }
        [1]=>
        array(4) {
          ["id"]=>
          string(6) "224017"
          ["valuesIds"]=>
          array(0) {
          }
          ["values"]=>
          array(1) {
            [0]=>
            string(12) "TO-344 Z 9 8"
          }
          ["rangeValue"]=>
          NULL
        }
        [2]=>
        array(4) {
          ["id"]=>
          string(6) "127788"
          ["valuesIds"]=>
          array(1) {
            [0]=>
            string(13) "127788_541853"
          }
          ["values"]=>
          array(0) {
          }
          ["rangeValue"]=>
          NULL
        }
        [3]=>
        array(4) {
          ["id"]=>
          string(6) "235129"
          ["valuesIds"]=>
          array(1) {
            [0]=>
            string(13) "235129_387949"
          }
          ["values"]=>
          array(0) {
          }
          ["rangeValue"]=>
          NULL
        }
        [4]=>
        array(4) {
          ["id"]=>
          string(6) "212158"
          ["valuesIds"]=>
          array(0) {
          }
          ["values"]=>
          array(1) {
            [0]=>
            string(2) "12"
          }
          ["rangeValue"]=>
          NULL
        }
        [5]=>
        array(4) {
          ["id"]=>
          string(6) "225693"
          ["valuesIds"]=>
          array(0) {
          }
          ["values"]=>
          array(1) {
            [0]=>
            string(13) "5901133344984"
          }
          ["rangeValue"]=>
          NULL
        }
        [6]=>
        array(4) {
          ["id"]=>
          string(6) "248489"
          ["valuesIds"]=>
          array(0) {
          }
          ["values"]=>
          array(1) {
            [0]=>
            string(3) "100"
          }
          ["rangeValue"]=>
          NULL
        }
      }
      ["name"]=>
      string(34) "Cienkopis Toma F-Liner 12 kolorów"
      ["category"]=>
      array(1) {
        ["id"]=>
        string(5) "64508"
      }
      ["product"]=>
      array(2) {
        ["id"]=>
        string(13) "5901133344984"
        ["idType"]=>
        string(4) "GTIN"
      }
      ["description"]=>
      array(1) {
        ["sections"]=>
        array(1) {
          [0]=>
          array(1) {
            ["items"]=>
            array(1) {
              [0]=>
              array(2) {
                ["type"]=>
                string(4) "TEXT"
                ["content"]=>
                string(241) "
- cienkopisy z fibrową końcówką 0,4 mm- pomarańczowa obudowa- niewysychający tusz- ładne i żywe kolory- tusz łatwo spieralny - metalowe wsparcie końcówki pozwala na niebrudzące kreślenie przy linijce- komplet 12 kolorów 

"
              }
            }
          }
        }
      }
      ["payments"]=>
      array(1) {
        ["invoice"]=>
        string(3) "VAT"
      }
      ["location"]=>
      array(4) {
        ["countryCode"]=>
        string(2) "PL"
        ["province"]=>
        string(12) "DOLNOSLASKIE"
        ["city"]=>
        string(8) "Wrocław"
        ["postCode"]=>
        string(6) "50-069"
      }
      ["sellingMode"]=>
      array(1) {
        ["price"]=>
        array(2) {
          ["amount"]=>
          string(5) "24.34"
          ["currency"]=>
          string(3) "PLN"
        }
      }
      ["delivery"]=>
      array(2) {
        ["shippingRates"]=>
        array(1) {
          ["id"]=>
          string(36) "33b526cb-13b8-4449-b618-d1e03088b4a6"
        }
        ["handlingTime"]=>
        string(5) "PT24H"
      }
      ["afterSalesServices"]=>
      array(3) {
        ["impliedWarranty"]=>
        array(1) {
          ["id"]=>
          string(36) "20133c7e-a1f2-4d7a-ab70-bb45dbae8c82"
        }
        ["returnPolicy"]=>
        array(1) {
          ["id"]=>
          string(36) "4617aa9f-c510-4569-b823-6ecd5e7e2bc7"
        }
        ["warranty"]=>
        array(1) {
          ["id"]=>
          string(36) "494a6ea0-82b9-487a-8774-835e5169014c"
        }
      }
      ["stock"]=>
      array(1) {
        ["available"]=>
        string(2) "19"
      }
      ["publication"]=>
      array(1) {
        ["republish"]=>
        bool(true)
      }
      ["images"]=>
      string(69) "https://a.allegroimg.com/original/11e9ac/8edddef541cd834609f26e79ba60"
    }
  }
}

i dostaje odpowiedź:

array(1) {
  ["error"]=>
  string(869) "{"errors":[{"code":"ConstraintViolationException.MissingRequiredParameters","message":"Missing required parameters: 248489","details":"ConstraintViolationException.MissingRequiredParameters","path":"parameters","userMessage":"Uzupełnij parametry obowiązkowe: Liczba sztuk w ofercie."},{"code":"ConstraintViolationException.AtLeastOneMode","message":"You must select at least one selling mode and provide the required prices.","details":"ConstraintViolationException.AtLeastOneMode","path":"sellingMode.null","userMessage":"Musisz wybrać przynajmniej jeden sposób sprzedaży oraz podać wymagane ceny."},{"code":"ConstraintViolationException.Min","message":"The stock level of items to be listed may not be lower than 1.","details":"ConstraintViolationException.Min","path":"stock.initialQuantity","userMessage":"Wystawiana liczba nie może być mniejsza niż 1."}]}"
}

proszę o informację gdzie jest błąd w zapytaniu

**Comment by AureliuszBrussy** [comment]
Jeżeli chodzi o error dotyczący parametru 248489 - parametr ten jest parametrem ofertowym ("**describesProduct**": false), a nie produktowym, więc nie powinieneś go przekazywać wewnątrz strukturze **productSet**, tylko jako parametr ofertowy (**parameters** poza **productSet**). Abym mógł zidentyfikować resztę problemów - prześlij proszę trace-id takiego wywołania. Znajdziesz go w nagłówku naszej odpowiedzi.

**Comment by reprezenter** [comment]
Faktycznie błąd z parametrem znikną, po przesunięciu tego parametru poza produkt,
dalej są 2 pozostałe błędy
nagłówek odpowiedzi:
{"expiresAt":"2022-12-01T19:54:34.131916Z","location":"https://a.allegroimg.com/original/11c6ff/25970cf3423881dec9e811a56cf9"}

**Comment by AureliuszBrussy** [comment]
@reprezenter w headerze odpowiedzi przekazujemy "trace-id" z wartością - potrzebuję, abyś przekazał mi tą wartość. Dzięki temu namierzę po naszej stronie odpowiednie logi.

**Comment by AureliuszBrussy** [comment]
Przyjrzyj się dokładniej payloadowi w [naszej dokumentacji](https://developer.allegro.pl/documentation#operation/createProductOffers) - sprawdź dokładnie, które z pól powinieneś przekazać w tablicy **productSet**, a które poza tą tablicą. M.in. powinieneś przekazać poza **productSet** pola, o których informujemy w komunikacie błędu, czyli m.in. sellingMode, stock itd.

**Comment by reprezenter** [comment]
racja, dzięki, zamykam
