### ISSUE TITLE
Integracja z Inpostem - brak id transakcji w REST API

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#643]
Dzień dobry,

widzę, że rozwijacie API dodając dodatkowe metody np. dyskusje, a nie skupiacie się na istotnych sprawach, czyli umożliwieniu integracji nowego API z API Inpostu.
Proszę dogadajcie się z Inpostem i to jakoś rozwiążcie.
Inpost oczekuje id transakcji typu INTEGER, REST API zwraca UUID.

**Comment by kuli-g** [comment]
Pytałem o to przez formularz jakiś miesiąc temu... odpowiedzieli że nic nie wiedzą i nie wiadomo kiedy będą wiedzieć.
Nowe REST API inpostu również przyjmuje tylko INT, w menedzer.paczkomaty.pl jak się zobaczy szczegóły transakcji też jest INT. Tylko Allegro musiało wymyślić guid który do niczego nie pasuje...

**Comment by mack3d** [comment]
Jeśli w mailu informacyjnym o płatności otrzymujemy zarówno transaction_id jak i UUID to poproszę @MartaNowaczyk o informacje jak radzi z tym sobie allegro?
W jaki sposób oba numery są ze sobą skorelowane?
Jedna rzecz a rozwiąże wiele problemów i co najważniejsze umożliwi już dziś korzystać z REST bez większych problemów.

**Comment by MartaNowaczyk** [comment]
Wiemy o problemie i pracujemy w tym temacie. Jak będziemy mieli konkretne rozwiązania zamieścimy tu taką informację.

**Comment by aktywnitu** [comment]
Pani Marto, czy już drgnęło w tej sprawie?
Jakieś informacje?

**Comment by MartaNowaczyk** [comment]
Tak, mamy już powiązanie "dwóch światów", jednak staramy sie rozwiązać tę kwestię w inny sposób. O zmianach jak zawsze będziemy informować w [aktualnościach](https://developer.allegro.pl/news/) na naszej stronie oraz w oddzielnym poście na GitHubie.

**Comment by kuli-g** [comment]
Tylko że tu bardziej chodziło wszystkim (i mi również) o postBuyFormId  a nie dealId... bo do inpostu przesyła się numer transakcji/płatności a nie zakupu. Czy wiadomo może czy inpost zostanie przy identyfikatorze webapi czy może w przyszłości zmieni go na ten z restapi?

**Comment by MartaNowaczyk** [comment]
Jeszcze nie wiadomo, także proszę o jeszcze trochę cierpliwości w oczekiwaniu na informacje.

**Comment by coobitus** [comment]
@MartaNowaczyk jak widzę nie tylko ja mam ten problem ... Kiedy coś z tym zrobicie? Nasi klienci obsługiwani przez Inpost nie mogą dokonać np. darmowego zwrotu (jedna z fajnych cech Allegro Inpost) i są z tego powodu wściekli!  Kiedy w końcu coś z tym zrobicie ???!!!??

**Comment by MartaNowaczyk** [comment]
@cobbitus rozumiem, jednak to nie tylko od nas zależy. Jesteśmy w kontakcie z InPostem w tej sprawie.

**Comment by coobitus** [comment]
@MartaNowaczyk a co ma do tego "biedny" Inpost? Nie możecie po prostu w swoim restowym API dodać oprócz UUID zamówienia także id starej transakcji??? To naprawdę takie trudne? Podajecie ten numer bezpośrednio do Inpostu ze swojego systemu, więc NA PEWNO macie takie powiązanie gdzieś zanotowane ...

**Comment by coobitus** [comment]
Zanim Inpost cokolwiek nowego zaimplementuje w swoim dziurawym i pełnym błędów API to miną WIEKI. A do tego czasu nasi kliencie nas zjedzą z wściekłości ...

**Comment by kuli-g** [comment]
@coobitus zdaje się że inpost nie korzysta z rest tylko webapi, allegro chce porzucić stare api wraz z jego identyfikatorami więc teraz pytanie czy uda się im "zmusić" inpost do stosowania nowych identyfikatorów czy się ugną i zachowają kompatybilność wsteczną.... Inpost miał zablokować integrację xml już rok temu a system dalej aktywny i działa więc im się za bardzo nie śpieszy ze zmianami.

**Comment by kuli-g** [comment]
@coobitus widzisz dlatego że inpost korzysta z identyfikatorów webapi dowodzi że nie używają restapi do komunikacji z allegro... tu jest problem. Gdyby korzystali z REST to dałoby się korzystać ze starych i nowych identyfikatorów równolegle, a tak nie wiadomo kto się podda. Jak się spojrzy w ich dokumentację rest to tam nawet podają że numer transakcji należy pobierać ze starego webapi o_O. Bądź tu mądry i pisz integrację

**Comment by MartaNowaczyk** [comment]
@coobitus poza tym skąd pewność, że to na pewno takie proste. Tak jak pisałam w innych postach, jak tylko będą nowe informacje w tej sprawie na pewno poinformujemy o tym.

**Comment by coobitus** [comment]
@MartaNowaczyk skoro możecie te identyfikatory (UUID ZAMÓWIENIA oraz id TRANSAKCJI) przekazywać bezpośrednio do Inpostu z Waszych aplikacji (Allegro i Menadżer Sprzedaży) to zakładam, że JEST TO PROSTE i że MACIE TAKIE POWIĄZANIA :-D

**Comment by coobitus** [comment]
@MartaNowaczyk tylko że pewnie chcecie zmusić Inpost do tego, żeby przeszli na Waszego RESTa (jak to zasugerował ktoś powyżej), HAHAHAHA

**Comment by kuli-g** [comment]
@coobitus allegro ma obecnie dwa równolegle działające systemy dlatego sobie może podawać dwa identyfikatory, jeśli chcą zostawić tylko REST, porzucić webapi i jednocześnie zachować stary numer transakcji to musieli by większą część starego systemu również zachować (dziennik zdarzeń, transakcje), to jest marnotrawienie zasobów bo po co utrzymywać na chodzie gigabajtowe bazy danych dla jednego identyfikatora? Muszą to zrobić inaczej, albo zmuszą Inpost do przejścia na REST albo... webapi będzie działać dłużej niż planowali. Możliwe też że jakoś zintegrują stary identyfikator w REST ale to raczej sprzeczne z ich polityką

**Comment by kuli-g** [comment]
@coobitus jak najbardziej masz rację :) obecnie mam integrację z restapi allegro i inpostu więc jak dla mnie obojętne jak się dogadają, ważne żeby się dogadali. Parę zmian w kodzie i będzie działać z jakimkolwiek identyfikatorem.

Tymczasem jednak ich harmonogram już ma opóźnienie bo planowane wyłączenie webapi jest na kwiecień a rest z obsługą zamówień dalej na wersji BETA siedzi https://allegro.pl/webapi/news.php/page,2#news_100617

**Comment by MMaciaszek** [comment]
Witam, czy coś drgnęło w tym temacie? 
Czy ewentualnie ma ktoś jakiś sposób na pobranie starego id transakcji.

**Comment by MartaNowaczyk** [comment]
@MMaciaszek Rozmowy cały czas trwają. Jak będziemy znać szczegóły zamieścimy taką informację.
