### ISSUE TITLE
Błąd w wygenerowanym pliku yaml

### ISSUE THREAD

**Issue by LukaszWypych** [allegro/allegro-api#6432]
Witam,
W wygenerowanym przez Państwa pliku yaml obiekt 'ProductSetElement' posiada tylko 1 pole typu 'ProductOffer'. Brakuje w nim natomiast pola z ilością, która również jest wymagana w np. metodzie 'createProductOffers'. Moim zdaniem powinno się tam również znaleźć pole typu 'ProductSetElementQuantity' (które przy okazji ma pole ilość obudowane w obiekt, a nie od razu wartość liczbową tak jak w metodzie api).

Kawałek api, o którym piszę:
```
    ProductSetElement:
      type: object
      properties:
        product:
          allOf:
          - $ref: '#/components/schemas/ProductOffer'
          description: You should enter the product identifier (UUID or EAN) or a complete product definition.
    ProductSetElementQuantity:
      type: object
      properties:
        quantity:
          type: object
          properties:
            value:
              type: integer
              example: 1
              minimum: 1
```

Stuktura metody 'createProductOffers'

```
"productSet": [
	{
		"product": {},
		"quantity": {
			"value": 1
		}
	}
]
```

Według mnie powinno to wyglądać coś na wzór :
```
    ProductSetElement:
      type: object
      properties:
        product:
          allOf:
          - $ref: '#/components/schemas/ProductOffer'
          description: You should enter the product identifier (UUID or EAN) or a complete product definition.
        quantity:
          allOf:
          - $ref: '#/components/schemas/ProductSetElementQuantity'
    ProductSetElementQuantity:
      type: object
      properties:
        value:
          type: integer
          example: 1
          minimum: 1
```

Jeżeli jednak się mylę, to z góry przepraszam.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za spostrzeżenie, opisany przypadek nie jest błędem technicznym, jednak zgadzamy się, że nie jest także do końca intuicyjny. Postaramy się to poprawić w przyszłości, jednak na ten moment nie jestem w stanie zadeklarować konkretnego terminu.
