### ISSUE TITLE
The state for the country CN must be empty

### ISSUE THREAD

**Issue by fxsshiwo** [allegro/allegro-api#6433]
Hello, we encountered this error when publishing recently. What does it mean?
How should we solve this problem?

`{"response":{"errors":[{"code":"UNSUPPORTED_STATE_FOR_GIVEN_COUNTRY","message":"The state for the country CN must be empty","details":null,"path":"location.state","userMessage":"Wojew\u00f3dztwo dla CN musi by\u0107 puste."}]}`

**Comment by PrzemyslawLukanowski** [comment]
This message indicates that you should leave "location.province" field empty when in the "location.countryCode" you passing a different value than "PL".

**Comment by fxsshiwo** [comment]
Is it a recently adjusted interface? We can publish it before

**Comment by PrzemyslawLukanowski** [comment]
I'm verifying this with our team because this value should be ignored in your case. I will be back with an answer, sorry for the inconvenience.

**Comment by PrzemyslawLukanowski** [comment]
The problem is solved, this error shouldn't appear anymore.
