### ISSUE TITLE
IP was blocked

### ISSUE THREAD

**Issue by ateccc1985** [allegro/allegro-api#6435]
Good day
we set up exchange with Allegro via api
But our IP was blocked.

We receive orders and transfer the stock of goods
  every 10 minutes.

IF it is frequent, then we can reduce the frequency

Please unblock our IP

Below the trace

@vs2944.mirohost.net ~ # traceroute 5.134.213.80
traceroute to 5.134.213.80 (5.134.213.80), 30 hops max, 60 byte packets
1 169.254.0.1 (169.254.0.1) 0.036 ms 0.018 ms 0.017 ms
2 78.27.226.2.mirohost.net (78.27.226.2) 0.137 ms 0.132 ms 0.133 ms
3 gdynr008rt02.inetia.pl (213.17.213.221) 1.560 ms 1.537 ms 1.514 ms
4 warsh002rt73.inetia.pl (87.204.224.98) 0.596 ms 0.600 ms 0.600 ms
5 POZNH002RT17.inetia.pl (87.204.224.7) 5.164 ms 5.249 ms 5.145 ms
6 poznh002rt11.inetia.pl (87.204.224.14) 5.161 ms 5.139 ms 5.177 ms
7 * * *
8 * * *
9 * * *
10 * * *
11 * * *

**Comment by PrzemyslawLukanowski** [comment]
Could you please send a screenshot with a sample error message?

**Comment by ateccc1985** [comment]
We don't see the error
The request just freezes
Everything was working for 5 months before.

If we try to connect from another IP, everything is OK


My hosting provider answered me that IP is blocked
See screenshot

![image](https://user-images.githubusercontent.com/119663019/205269053-b36c8c52-88e1-4b27-9bb2-894d000198b9.png)

**Comment by PrzemyslawLukanowski** [comment]
But is there any response you receive from our API?

**Comment by ateccc1985** [comment]
Right
We do not receive any response

**Comment by ateccc1985** [comment]
please check IP
77.87.197.175

**Comment by ateccc1985** [comment]
Could you traceroute to our IP 77.87.197.175 ?

Is possible blocking at the level of the router or provider ?

**Comment by PrzemyslawLukanowski** [comment]
Your IP address was not blocked, it seems the problem is with the operator cause we were not receiving your traffic at all. We made some changes on our side and for now, it should work properly.

**Comment by ateccc1985** [comment]
Thanks a lot
Exchange is working again
