### ISSUE TITLE
Problem z przesyłaniem parametrów po nazwie (sale/product-offers) 

### ISSUE THREAD

**Issue by glinkaa** [allegro/allegro-api#6436]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Przy próbie dodania oferty poprzez zasób sale/product-offers w kategorii 261043 przy użyciu nazw parametrów (zamiast id parametrów) zwracany jest błąd {"code":"ParameterNameNotUniqueException","message":"Unprocessable Entity","details":null,"path":"productSet[0].product.parameters","userMessage":"Znaleziono więcej niż jeden parametr o nazwie  `Wytwórnia` w podanej kategorii `261043`. Prześlij id parametru."} czy rzeczywiście konieczne jest podanie id parametru w tym przypadku czy jest to raczej błąd, ponieważ na allegro.pl przy próbie wystawienia oferty w tej kategorii parametr 'Wytwórnia' występuje tylko raz?

 trace-id: 39a8322186afeb52

**Comment by AureliuszBrussy** [comment]
Weryfikujemy to. Wrócę do Ciebie z odpowiedzią.

**Comment by glinkaa** [comment]
@AureliuszBrussy czy już coś wiadomo?

**Comment by AureliuszBrussy** [comment]
@glinkaa problem występował ze względu na migrację parametru "Wytwórnia" w tej kategorii. W tym momencie error nie powinien być zwracamy.

**Comment by glinkaa** [comment]
@AureliuszBrussy tym razem problem z kategorią 112724 i parametrem 'Długość'
podaje wartość dla parametru 'Długość', a zwraca błąd "Unable to create product without proper values in all required parameters: [Długość] in category: 112724"

trace-id: 1fd661e23e5a9b3

**Comment by MaciejFrackowiak** [comment]
@glinkaa Potwierdzam problem - działamy już nad jego wyeliminowaniem.

**Comment by glinkaa** [comment]
@MaciejFrackowiak czy problem został już rozwiązany?

**Comment by MaciejFrackowiak** [comment]
@glinkaa Zadanie nadal jest w toku, jednak część requestów dla niektórych kategorii kończy się powodzeniem. Dlatego sprawdź proszę dla swojego przypadku.
