### ISSUE TITLE
Brak możliwości wznowienia i zakończenia aukcji przez rest api

### ISSUE THREAD

**Issue by q3ok** [allegro/allegro-api#6437]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Requesty o wznowienie (i zakończenie) aukcji wiszą w statusie "NEW"
Przykładowe commandid na wznowienie: 3e484e7c-c0f0-46c1-9a89-588665699ad9, d053e0a5-1218-4e56-8a97-f12037d45e75
Przykładowe commandid na zakończenie: d2847241-7b4a-4821-bc31-556efd0835cb, 3a03cb4b-2885-4a74-ae70-ce3b0e9bc0bd

Zasób:
Sprawdzane przez /sale/offer-publication-commands/[uuid]/tasks
Zarequestowane przez /sale/offer-publication-commands/[uuid]

**Comment by AureliuszBrussy** [comment]
Aktualnie mogą wystąpić pewne opóźnienia w zmianach statusu publikacji. Już namierzyliśmy problem i pracujemy nad jego rozwiązaniem.
