### ISSUE TITLE
Generowanie etykiety Allegro One Kurier

### ISSUE THREAD

**Issue by PrzemyslawLukanowski** [allegro/allegro-api#6438]
### Discussed in https://github.com/allegro/allegro-api/discussions/6431

<div type='discussions-op-text'>

<sup>Originally posted by **PawelPseudo** December  1, 2022</sup>
Witam

Chcemy nadac paczkę i wygenerować etykietę.
uuid paczki: f3c3fc2a-b676-424b-bc1d-90255fc98c08

i sprawdzając status jest:

[code] => VALIDATION_ERROR
  | [message] => Order delivery method: 01d3468e-42af-474d-b06c-9a2f986f2ec3 is not allowed
  | [details] =>
  | [path] => deliveryMethodId
  | [userMessage] => Metoda dostawy jest niedostępna

a taki id metody wysyłki jest zwracane przez listę metod wysyłki.
Jeżeli ten jest niepoprawny to jak pobrać / sprawdzić właściwy ?
</div>

**Comment by PrzemyslawLukanowski** [comment]
Podobny problem został opisany w wątku #6387. W najbliższym czasie będziemy usuwać wspomnianą metodę dostawy i powiązaną z nią usługę. Użyj proszę usługi dostawy o identyfikatorze 0d83955a-4297-4169-adef-9790d53b11ff. Przepraszam za związane z tym problemem niedogodności.

**Comment by PawelPseudo** [comment]
dziękuję za info, jeszcze mam pytanie o maksymalny wymiar paczki bo te podane u Was na stronie powoduja komunikat  za dużych wymiarach paczki.

![image](https://user-images.githubusercontent.com/73448782/205400076-f730169c-7d8b-439f-b48d-c4a57c0914a0.png)

**Comment by PawelPseudo** [comment]
mamy jeszcze taki komunikat, ale nie widze go nigdzie w dokumentacji:

<html>
<body>


$httpCode: 200<br>
--
  | Array
  | (
  | [id] => 91179fef-b476-4edf-a560-359bf1f478d5
  | [parcelId] =>
  | [status] => ERROR
  | [errors] => Array
  | (
  | [0] => Array
  | (
  | [code] => UPSTREAM_SERVICE_TIMEOUT
  | [message] => Przekroczony czas przetwarzania żądania
  | [details] =>
  | [path] =>
  | [userMessage] => Przekroczony czas przetwarzania żądania
  | )
  |  
  | )
  |  
  | )


</body>
</html>

**Comment by PrzemyslawLukanowski** [comment]
1. Błąd prawdopodobnie otrzymujesz dlatego, że podając 120 x 76 x 76 przekraczasz wagę gabarytową. Waga gabarytowa paczki jest związana z rozmiarami paczki i obliczana jest wg wzoru: [(Długość (cm) x szerokość (cm) x wysokość (cm)) / 5000].
![image (2)](https://user-images.githubusercontent.com/51473661/205589381-9939ce27-4d04-4c29-a7af-abef081d7d4d.png)
2. Ten timeout zwrócimy, jeśli z jakichś powodów (np. problem po naszej stronie lub z API przewoźnika) nie uda nam się utworzyć paczki. W takim przypadku musisz podjąć nową próbę utworzenia, z nowym command ID.

**Comment by PawelPseudo** [comment]
Dostajemy jeszcze taki error dla UUID: fcc8d312-1ac4-4c44-89db-0d7a0c8224a5
Nie ma innych pól, niż te w dokumentacji.

<html>
<body>

--
[status] => ERROR
  | [errors] => Array
  | (
  | [0] => Array
  | (
  | [code] => ERROR
  | [message] => "Inne dane na etykiecie" not supporter for carrier
  | [details] =>
  | [path] => /sender
  | [userMessage] => Opcja 'Inne dane na etykiecie' nie są dostępne dla wybranego przewoźnika
  | )
  |  
  | )
  |  


</body>
</html>

**Comment by PrzemyslawLukanowski** [comment]
Błąd jest spowodowany tym, że nie każdy przewoźnik umożliwia umieszczenie na etykiecie innych danych niż dane nadawcy z sekcji "pickup". W takim przypadku "label.sender" powinno zostać polem z wartością null - przewoźnik pobierze dane z pola "pickup". Pole to jest obsługiwane wyłącznie przez DPD, DHL, FedEx, UPS oraz InPost Kurier.

**Comment by PawelPseudo** [comment]
Jest jeszcze taki komunikat. Prosze o sprawdzenie.

![Screenshot_17](https://user-images.githubusercontent.com/73448782/206990680-537d47cc-0c5d-4cce-a721-9e4fa1ef10fa.png)

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam za długi czas odpowiedzi - request skonstruowany jest poprawnie, problem był po naszej stronie, prosiłbym o powtórzenie operacji z nowym commandId.

**Comment by PawelPseudo** [comment]
dziekuje za informacje
