### ISSUE TITLE
Od około godz. 13 przetały się zakańczać oferty

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#6439]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

Dzisiaj mniej więcej od godz. 13, wysyłanie przez Allegro API żądań zakończenia ofert skutkuje zwracaniem przez wasze API potwierdzenia przyjęcia komendy (sukces), jednak oferta nie kończy się.

Każda odpowiedź ma status HTTP 201

Przykłady odpowiedzi:
{"id":"99345e5a-18fe-48e7-bd3b-b41d4c1a96e3","taskCount":{"total":0,"success":0,"failed":0}}
{"id":"7cc79631-973d-4592-bb08-f1560c10c47f","taskCount":{"total":0,"success":0,"failed":0}}
{"id":"7d3a019a-3d9a-4f69-ae4e-0449ffc664ec","taskCount":{"total":0,"success":0,"failed":0}}
{"id":"cc3ebd86-988f-4008-976b-bf9ecff05be8","taskCount":{"total":0,"success":0,"failed":0}}

Prosimy o naprawienie, ponieważ w tym gorącym okresie świątecznym nie chcemy zawieść ludzi wystawiając na Allegro towar, który zszedł nam z magazynu sprzedany przez inny kanał.

Dotyczy endpoint PUT /sale/offer-publication-commands/

gdzie action = "END"

**Comment by ppart** [comment]
Potwierdzam problem, ogromne opóźnienia. Wczoraj również występowały ale mniejsze.

**Comment by ZomaGo** [comment]
Potwierdzam problem. Czy wiadomo kiedy zostanie rozwiazany?

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że w podanym okresie mogły wystąpić opóźnienia przetwarzania zadań związanych z publikacją i zakańczaniem ofert. Podobny problem został już zgłoszony wcześniej w wątku #6437 i tego samego dnia został przez nas usunięty. Przepraszam za wszelkie niedogodności z tym związane.
