### ISSUE TITLE
funkcja start stop aukcje allegro

### ISSUE THREAD

**Issue by sma-automator** [allegro/allegro-api#644]
Witam
Czy istnieje mozliwosc korzystania z funkcji start stop (aukcje) po api  ?

**Comment by MartaNowaczyk** [comment]
Witam, 
1/ Dla ofert zwykłych możesz użyć metody PUT /sale/offer-publication-commands/{commandId} podając odpowiedni status w polu action - więcej [tutaj](https://developer.allegro.pl/sale/#step-8-offer-publication-commands).
2/ Dla licytacji nie ma start stop.
