### ISSUE TITLE
Brak możliwości wystawienia aukcji przez API

### ISSUE THREAD

**Issue by michalmkr** [allegro/allegro-api#6440]
Występuje problem z wystawieniem aukcji przez API.

Od około godziny 13.00 przestały się wystawiać aukcje.
Mam ponad kilkaset aukcji w kolejce i od tamtej pory nic się nie ruszyło.

Proszę o pomoc i sprawdzenie co się dzieje oraz naprawienie tego.
Kontaktowałem się z moją platformą sklepową i napisali, ze problem leży po stronie Allegro.

**Comment by jakub-adamski** [comment]
Potwierdzam, u nas też jest problem ze wznawianiem, kilka k ofert jest w kolejce, nowych limitów na pewno nie przekraczamy
