### ISSUE TITLE
Sandbox Provided image address is incorrect

### ISSUE THREAD

**Issue by He79** [allegro/allegro-api#6441]
HttpResponseProxy{HTTP/1.1 422 Unprocessable Entity [expires: 0, cache-control: no-cache, no-store, max-age=0, must-revalidate, x-xss-protection: 1; mode=block, pragma: no-cache, x-frame-options: DENY, trace-id: b451c3c6146172b1, date: Sat, 03 Dec 2022 20:47:44 GMT, x-content-type-options: nosniff, strict-transport-security: max-age=31536000 ; includeSubDomains, content-type: application/json, content-length: 212] ResponseEntityProxy{[Content-Type: application/json,Content-Length: 212,Chunked: false]}}
responseproductproposals(创建产品价格) = {"errors":[{"code":"OfferImagesNotFoundException","message":"Provided image address is incorrect.","details":"OfferImagesNotFoundException","path":null,"userMessage":"Podany adres obrazka jest nieprawidłowy."}]}

I checked the image link and found no problem

**Comment by He79** [comment]
Hello, Allegro official, I have solved the problem about images. Now I have encountered a new problem, and I want to get the answer
1. When I want to upload a product with color and size, size will be automatically combined into a variation set. When I combine colors at this time, the system reports an error saying that the product is part of other variation sets. Should I delete the existing size variation set first, and then combine the size and color variation sets? Is there any better way to do this
2. Only one image can be converted to an internal address at a time

**Comment by He79** [comment]
If I use /sale/product-offer, do I not need to upload pictures to your server first？I use product offer to create products and offers. Why should I fill the image url in both product set and offer

**Comment by PrzemyslawLukanowski** [comment]
Yes, images can be from external addresses.

> Why should I fill the image url in both product set and offer?

I'm not sure I understand this question, I didn't mention that.

**Comment by He79** [comment]
When I upload a multi size and multi color product, size will be automatically combined into a variation set, but when I delete the size variation set, I need to provide the variation ID, and how do I get this ID

**Comment by He79** [comment]
@PrzemyslawLukanowski

**Comment by PrzemyslawLukanowski** [comment]
You can get this ID via [GET /sale/offer-variants](https://developer.allegro.pl/documentation/#operation/getVariantSets) and using [GET /sale/offer-variants/{setId}](https://developer.allegro.pl/documentation/#operation/getVariantSet) you will retrieve details of the given variant set. 
Alternatively, you can remove automatically created variants through [our website](https://allegro.pl/moje-allegro/sprzedaz/wielowariantowosc).

**Comment by PrzemyslawLukanowski** [comment]
There is no one ID, you can check the IDs using [GET /sale/categories](https://developer.allegro.pl/documentation/#tag/Categories-and-parameters) and query parameter "parent.id".

**Comment by He79** [comment]
@PrzemyslawLukanowski Hello, I got the following errors when I created the product, and I hope to solve them
HttpResponseProxy{HTTP/1.1 422 Unprocessable Entity  [expires: 0, cache-control: no-cache, no-store, max-age=0, must-revalidate, x-xss-protection: 1; mode=block, pragma: no-cache, x-frame-options: DENY, trace-id: fc724c1281cdbdaf, date: Tue, 06 Dec 2022 20:19:14 GMT, x-content-type-options: nosniff, strict-transport-security: max-age=31536000 ; includeSubDomains, content-type: application/json, content-length: 227] ResponseEntityProxy{ [Content-Type: application/json,Content-Length: 227,Chunked: false]}}
{"errors":[{"code":"ProductValidationException","message":"Invalid GTIN: 225693 - 2968139575548 in category: 313105","details":null,"path":"productSet[0].product","userMessage":"Nieprawid ł owy kod EAN (GTIN) - 2968139575548"}]}
I checked that my EAN is correct
I have another question. If I have 5 pictures, I can only send them to your server one by one. Is there a better way

**Comment by PrzemyslawLukanowski** [comment]
Hello, the EAN number that starts with 296 is a so-called Restricted Circulation Number ― such a number is not unique and may already be used internally by some other company. You should contact the distributor, publisher or manufacturer and get the correct EAN number.

> I have another question. If I have 5 pictures, I can only send them to your server one by one. Is there a better way

Can you give me more details on what you mean by one by one? If you use POST /sale/product-offers endpoint you can send us more images than one with a single request.
