### ISSUE TITLE
Edycja oferty i dodanie do niej produktu

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#6442]
Cześć, korzystam w Waszego nowego zasobu: PATCH sale/product-offers/{id}.
Edytuje ofertę, uzupełniam strukturę ProductSet, ale nie żaden produkt nie jest przypisywany do oferty.

Z poradnika wynika, że produkt powinien być podlinkowany do oferty. Do oferty powinien być podlinkowany produkt, który został zlokalizowany w Waszej bazie, lub powinien być utworzony nowy.

W czym jest problem?
TraceId: 	"965919ca46a3f96f"

**Comment by AureliuszBrussy** [comment]
Gdy korzystasz z PATCH nie utworzymy i nie przypiszemy automatycznie produktu. Jeżeli chcesz powiązać ofertę z katalogiem przy edycji, musisz wskazać konkretny produkt (productSet.product.id).

**Comment by marmited** [comment]
Ok, dzięki. Mam też inne pytanie. Jako że za pomocą PATCH można edytować pojedyncze pola to czy można edytować tylko liczbę aktualnych produktów? 

Jeżeli tak to co w hipotecznej sytuacji sytuacji gdy chciałbym zmienić tylko ilośc wolnych sztuk, a w produkcie pojawiły się nowe wymagane parametry. 

Przy korzystaniu ze starego zasobu musiałbym je ustawić, jak jest teraz? Inne obszary edytowanej oferty są walidowane pomimo braku ich aktualizacji przez sprzedającego?

**Comment by AureliuszBrussy** [comment]
@marmited aktualnie zasób zachowa się tak jak edycja na **/sale/offers** - zwrócimy błąd z informacją o konieczności uzupełnienia brakujących parametrów. Planujemy jednak zmienić to zachowanie, tak aby zmiana liczby sztuk była możliwa mimo braku parametrów. Zmianę tą będziemy komunikować - śledź nasze newsy.
