### ISSUE TITLE
Brak możliwości przesłania ofert z pliku

### ISSUE THREAD

**Issue by PatrykPaziewski** [allegro/allegro-api#6445]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Podczas próby wczytania ofert z pliku w środowisku sandbox pojawia się błąd "Przesyłanie pliku zakończyło się niepowodzeniem". Podczas próby pobrania raportu otrzymujemy błąd "Pobieranie raportu się nie powiodło. Prawdopodobnie wystąpiły problemy techniczne. Spróbuj ponownie później". 
Login: DDCarparts, 
Login konta z produkcji, z krórego chcemy przenieść oferty: DDCarparts2.

Link do pliku z ofertami, który próbujemy załadować: https://we.tl/t-svj9tzCdpM

Z góry serdecznie dziękuję za pomoc.

**Comment by PrzemyslawLukanowski** [comment]
W przypadku pytań związanych z przesyłaniem ofert z pliku, skorzystaj proszę z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt), aby zgłosić problem.
