### ISSUE TITLE
Dublowanie numerów nadawczy WZA Poczta Polska

### ISSUE THREAD

**Issue by RABENEPL** [allegro/allegro-api#6446]
Dzień dobry,

Podczas tworzenia przesyłek przez oprogramowanie zewnętrzne Sello w WZA Poczta Polska wyskakuje nam komunikat o następującej treści.

"Pobieranie stanu wykonania zlecenia utworzenia przesyłki z Allegro dla paczki "******/2022" na koncie "****" (******): Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.

Kod błędu: 0 

[ERROR]: Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."

Zgłosiłem to do producenta oprogramowania ale odesłali mnie do Allegro, gdyż to błąd według nich po Państwa stronie.

Błąd powoduje dublowanie numerów nadawczych i konieczność tworzenia nowych przesyłek. Same przesyłki się tworzą, jednak za pierwszym razem do jednej paczki tworzą się 2 numery nadawcze w tym samym czasie. Ustawione są prawidłowo w Sello. 1 paczka powinna tworzyć 1 numer nadawczy. Musimy w takim wypadku usuwać takie przesyłki i za drugim razem tworzą się już poprawnie.

Zauważyliśmy, że taki problem występuje gdy takich przesyłek jest więcej np. 50 paczek, wtedy przy 10 paczkach zwraca błąd. Gdy wysyłamy mniejsze partie np. 5 paczek to błąd nie występuje lub np. jest to pojedyncza paczka. 

Przykładowe nicki Klientów, których problem dotyczy:
agatamach1 
Pys1987 
gorsko19 

Administrator oprogramowania zasugerował nam wcześniej, że problem może być następujący:
Podejrzewam, że timeout leci gdzieś na styku Allegro <-> Poczta Polska. Timeout, czyli przekroczony czas oczekiwania na odpowiedź serwera. Niestety w takich przypadkach jeśli nie ma odpowiednich zabezpieczeń może dochodzić do dublowania wpisów. Po prostu zleceniodawca (Sello, Allegro) nie otrzymuje odpowiedzi z serwera Poczty Polskiej w założonym czasie (np 20s) więc zrywa połączenia i uznaje, że wystąpił problem. Po stronie serwerów docelowych (Poczta Polska) przesyłka zapewne się tworzy ale z dużym opóźnieniem, natomiast nikt już nie czeka na odpowiedź serwera i informacja o tym, że przesyłka została utworzona ginie. Zleceniodawca nic nie wie o tej przesyłce i tworzy ją ponownie.
Jeśli to jest timeout pomiędzy Allegro <--> Poczta Polska to tylko Allegro może to zrobić. 

Sami niestety nie posiadamy wiedzy programistycznej aby rozwiązać ten problem. 

Pozdrawiam
Rafał

**Comment by PrzemyslawLukanowski** [comment]
Czy mogę prosić o przykładowe command ID, dla których zwracamy komunikat "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."?

**Comment by RABENEPL** [comment]
O ile dobrze zrozumiałem pytanie to jedynie taki komunikat dostajemy w raporcie:

Pobieranie stanu wykonania zlecenia utworzenia przesyłki z Allegro dla paczki "******/****" na koncie "ddcbpl" (41527513): Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.

Kod błędu: 0 

[ERROR]: Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.

To przykładowe zamówienie Allegro nr d8857900-732a-11ed-9f20-0918d89f813c Klient gorsko19

Pierwsza próba wysłania żądania utworzenia 1x przesyłki tworzą się dwa numery nadania i wyskakuje powyższy błąd. A tak wygląda historia tworzenia numerów. 
5 gru 2022, 09:08	
00159007738240204251
Allegro Pocztex Kurier 48
5 gru 2022, 09:09	
00159007738240206651
Allegro Pocztex Kurier 48

Druga próba wysyłamy żądanie utworzenia 1x przesyłki i już poprawnie - tylko 1x numer i bez błędu. 
5 gru 2022, 10:31	
00159007738240415084
Allegro Pocztex Kurier 48

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za dane. Analizujemy tę sytuację po naszej stronie. Wrócę z informacją, gdy będę mógł udzielić więcej szczegółów.
