### ISSUE TITLE
weryfikacja konta sandbox

### ISSUE THREAD

**Issue by SteveMavic** [allegro/allegro-api#6447]
Proszę o weryfikację konta "sandboxexcat"

**Comment by SteveMavic** [comment]
Dokończyłem aktywację, ponownie proszę o sprawdzenie i weryfikację.

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.

**Comment by SteveMavic** [comment]
Jest ok, dzięki.
