### ISSUE TITLE
Grupowa zmiana promowania na ofertach

### ISSUE THREAD

**Issue by LukaszWypych** [allegro/allegro-api#6448]
Dzień dobry,
zauważyłem, że aktualnie są 2 możliwości na grupową zmianę promowania na ofertach:

- "/sale/offers/promo-options-commands/{commandId}", w którym wskazuje się predefiniowane opcje promowania
- "/sale/offer-modification-commands/{commandId}", w którym wskazuje się poszczególne atrybuty promowania (bold, highlight, itp)

Mam pytanie, czy obie metody są poprawne? Czy może jedno z nich zostanie wygaszone w najbliższym czasie?

**Comment by MaciejFrackowiak** [comment]
Zdecydowanie lepszym rozwiązaniem jest wybór [/sale/offers/promo-options-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/promoModificationCommandUsingPUT), ponieważ obecnie dostępne w Allegro opcje promowania oparte są głównie na pakietach promowań. Zachęcam Ciebie do lektury [naszego poradnika](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-zarzadzac-promowaniem), gdzie opisaliśmy zarządzanie promowaniem.
