### ISSUE TITLE
Projekt inżynierski wycena nieruchomości 

### ISSUE THREAD

**Issue by Jakwisnie** [allegro/allegro-api#6449]
Witam wraz z kolegą z grupy robimy projekt inżynierski na Polsko-Japońskiej akademii technik komputerowych w Gdańsku, o tematyce wyceny nieruchomości przy pomocy wykorzystania sztucznej inteligencji. Przekazujemy sieci neuronowej dane o istniejących ofertach mieszkań na terenie trójmiasta w celu nauczenia i poprawy wiarygodności wyników zapytań. Tu pojawia się pytanie do was, czy była by możliwość wykorzystania allegro api przy naszym scraperze w celu zbierania danych ofert z waszej witryny, scraper działał by tylko w momencie uruchomienia ręcznego przez nas, moglibyśmy ustawić również limit zapytań by nie przeciążało zbyt mocno serwerów. Wcześniej pytałem pod allegro kontakt i podobno była by taka możliwość.
Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Nie, nie udostępniamy zasobów API Allegro w celu wykorzystania ich do scrappowania serwisu. Jest to działanie niezgodne z [naszym regulaminem](https://developer.allegro.pl/rules).
