### ISSUE TITLE
Limit ilości ofert na koncie

### ISSUE THREAD

**Issue by kuli-g** [allegro/allegro-api#645]
Podobno API czy stare czy nowe ma limit ilości ofert na koncie do 100tyś, a ten sprzedający ma ponad 111tyś... nie żebym go kablował ale chodzi mi technicznie, jak to z tym limitem jest?
https://allegro.pl/uzytkownik/auto-hol2009?order=m

**Comment by MartaNowaczyk** [comment]
Jeśli na koncie przed zmianą było więcej niż 100000 ofert, może zdarzyć się sytuacja o której piszesz. Nadmiarowych ofert nie usuwaliśmy, ale nie pozwalamy wystawić nowych ofert.
