### ISSUE TITLE
POST /pricing/offer-fee-preview odpowiedź StatusCode: 308

### ISSUE THREAD

**Issue by ricarderobl** [allegro/allegro-api#6450]
Dzień dobry, Jako Uri używam "https://api.allegro.pl". Polecenie jakie wpisuje to "pricing/offer-fee-preview". Jednak dostaje odpowiedź iż "StatusCode: 308, ReasonPhrase: 'Permanent Redirect'". Wynika z tego, że jakoby Uri przeze mnie podawane jest błędne. Jednak używam go też przy innych poleceniach i działa prawidłowo. Proszę o informacje, ponieważ nie wiem gdzie popełniam błąd.

**Comment by MaciejFrackowiak** [comment]
Sprawdź proszę w ustawieniach swojej aplikacji, czy nie masz wybranej opcji automatycznego przekierowania. Wywołanie zasobu [POST https://api.allegro.pl/pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST) przy właściwej konstrukcji requestu powinno zakończyć się statusem 200.

**Comment by ricarderobl** [comment]
Wyłączenie automatycznego przekierowania nie pomogło, komunikat jaki otrzymuje jest identyczny. Co jeszcze może być przyczyną?

**Comment by MaciejFrackowiak** [comment]
To jest właściwy adres wywołania: POST https://api.allegro.pl/pricing/offer-fee-preview

**Comment by ricarderobl** [comment]
Znalazłem błąd, poprawiłem kod i teraz otrzymuje błąd 401 czyli problem z autoryzacją.

Problem polega na tym, że źle buduje Header, który wgrywaj jako allklient. Jaki jest prawidłowy format Headera?

**Comment by MaciejFrackowiak** [comment]
Zarówno Accept, jak i Content-Type powinien przyjąć format "application/vnd.allegro.public.v1+json".

**Comment by ricarderobl** [comment]
Te mam poprawnie, czyli "Accept: application/vnd.allegro.public.v1+json" oraz "Content-Type: application/vnd.allegro.public.v1+json". A jak musi wyglądać "Authorization:" oraz czy "Accept-Language" jest konieczny?

**Comment by ricarderobl** [comment]
Ponawiam zapytanie, jak poradzić sobie z:

`error_description="Cannot convert access token to JSON"`

**Comment by MaciejFrackowiak** [comment]
Musisz skorzystać z autoryzacji typu Basic z zawartością w formie client_id:client_secret (dane otrzymane przy rejestracji aplikacji) w postaci [Base64](http://base64encode.org/). Proces opisujemy w [poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#autoryzacja-uzytkownika).

**Comment by ricarderobl** [comment]
A nie mogę tego zrobić w OAuth?

Próbowałem znaleźć przykładową klasę w C# bym mógł się na niej wzorować, bo widzę, iż źle ją zdefiniowałem i z tego powodu nie mogę poprawnie wykonać polecenia POST. Niestety nie jestem w stanie takowej znaleźć. Czy mógłbym prosić o wskazówkę jak powinienem ją zbudować?

**Comment by MaciejFrackowiak** [comment]
Nasza autoryzacja opiera się o OAuth. Z uwagi na liczbę języków programowania nie prowadzimy wsparcia w zakresie korzystania z nich - być może ktoś z forumowiczów będzie mógł Tobie pomóc.

**Comment by ricarderobl** [comment]
Poprawiłem kilka kwestii i otrzymuje teraz komunikat:

"{"errors":[{"code":"ERROR","message":"An error has occurred","details":"Field error in object 'apiOfferFeePreviewRequest' on field 'offer': message  [musi być podane]","path":"offer","userMessage":"Żądanie zawiera niepoprawny format danych."}]}"

Czy mogę prosić o wyjaśnienie tego komunikatu?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swojego wywołania, wówczas będę mógł spojrzeć na Twój request.

**Comment by ricarderobl** [comment]
74aeef23c220b36d

**Comment by ricarderobl** [comment]
Czy wiadomo co źle zrobiłem?

**Comment by MaciejFrackowiak** [comment]
Przekazujesz niewłaściwą strukturę - w Twoim requeście umieściłeś zawartość oferty pobraną z [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET), a dla zasobu [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST) jest ona inna tzn. zawartość oferty musisz osadzić w strukturze "offer".

**Comment by ricarderobl** [comment]
Co znaczy, że zawartość oferty musisz osadzić w strukturze "offer"? Jak mam pobraną ofertę z GET /sale/offers/{offerId} to co mam z tym dokładnie zrobić?

**Comment by ricarderobl** [comment]
Proszę o sprawdzenie tego trace-id b410e43b58e33b97, nie widzę by response z GET /sale/offers/{offerId} był osadzony w strukturze offer.

**Comment by MaciejFrackowiak** [comment]
Response nie jest osadzony w "offer" - na potrzeby POST /pricing/offer-fee-preview musisz go "przerobić" we własnym zakresie.

**Comment by ricarderobl** [comment]
Udało mi się poprawnie wykonać zapytanie POST. Jednak występuje teraz inny problem. Mianowicie pracuje na tysiącach aukcji i pierwsze kilkaset response jest przetwarzane poprawnie, a potem otrzymuje komunikat: "Status NotFound: Not Found".

Co może być przyczyną?

**Comment by MaciejFrackowiak** [comment]
Nie sposób mi odpowiedzieć na to pytanie, ponieważ to Twoja aplikacja natrafia na problem - jak sam zauważyłeś wykonujesz kolejne requesty i kończą się poprawnie, po czym pojawia się request x i tu jest problem.
