### ISSUE TITLE
Parametry produktowe a ofertowe

### ISSUE THREAD

**Issue by AdrianeZ** [allegro/allegro-api#6451]
Mam pytanie implementuje interfejs który będzie wystawiał oferty za pomocą zasobu POST /sale/proudct-offers. Pobierając parametry dla danej kategorii, z pola 'describesProduct' mogę dowiedzieć się który parametr jest ofertowy, a który produktowy. Czy musze rozdzielać te parametry productSet.product.parameters -> [parametry produktowe], parameters =>[parametry ofertowe], czy mogę wszystkie wrzucić do productSet.product.parameters, a algorytm po stronie allegro sam rozpozna jakie są produktowe, a jakie ofertowe?

**Comment by MaciejFrackowiak** [comment]
Parametry produktowe i parametry ofertowe to dwa osobne byty. Dlatego parametry produktowe musisz umieścić w części opisującej produkt (productSet.product.parameters), a ofertowe już poza szczegółami produktu (parameters). Więcej informacji o parametrach ofertowych znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#parametry-ofertowe).
