### ISSUE TITLE
Problem z atrybutem Marka fid 3786

### ISSUE THREAD

**Issue by adamus994** [allegro/allegro-api#6452]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [x ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry,
Nie mogę dzisiaj wystawić aukcji w kategorii Galanteria.
Wydaje się, ze jest coś nie tak z atrybutem Marka fid 3786, ponieważ po pominięciu tego atrybutu jest ok.

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać przykładowe trace-id z tym komunikatem błędu? Bez problemu udało mi się wystawić ofertę z tym parametrem, nie widzę również żadnych zmian w jego zakresie.

**Comment by adamus994** [comment]
Już wiem co się stało. To raczej problem po naszej stronie.
Pojawiła się marka o nazwie 'inna|J.Style' , a my za pomocą znaku '|' sklejamy wszystkie marki w jeden string i po ponownym rozbiciu w tablice powstawała nam jedna więcej marka...
Już to u nas poprawiłem.
