### ISSUE TITLE
Brak aplikacji dodanych kiedyś w panelu zarządzania aplikacjami na https://apps.developer.allegro.pl/ które działają produkcyjnie

### ISSUE THREAD

**Issue by pkowalski700lm** [allegro/allegro-api#6453]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [X ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Po zalogowaniu do panelu i kliknięciu "Zarządzaj aplikacjami" nie pokazują się żadne aplikacje które mamy wpięte w konto. Działają one produkcyjnie już od conajmniej 2 lat i było ich conajmniej 2.

Dodatkowe pytanie - czy teraz jak coś dodam to stare aplikacje przestaną działać ?

**Comment by PrzemyslawLukanowski** [comment]
Na podanej stronie wyświetlamy tylko te aplikacje, których jesteś twórcą, nie zobaczysz tam wszystkich aplikacji, z którymi powiązane jest Twoje konto - takie aplikacje widnieją w zakładce [Powiązane aplikacje](https://allegro.pl/moje-allegro/moje-konto/powiazane-aplikacje).
Nie, stare aplikacje nie przestaną działać, konto może być powiązane z wieloma aplikacjami.

**Comment by pkowalski700lm** [comment]
OK. W takim razie na liście powiązanych aplikacji widzę 3x aplikacje , których jestem twórcą a nie ma ich na https://developer.allegro.pl/ (nie mam tam nic).

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz przesłać nam:
 - zrzut ekranu ze strony https://apps.developer.allegro.pl/ z widocznym loginem użytkownika;
 - client ID aplikacji, które powinny tam widnieć? 
 
Zweryfikujemy to. Dane możesz udostępnić tutaj lub przesłać nam za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=6a7ab6d0-2364-4a46-86ff-3aafcca487ab&subjectId=2aad59dd-2c45-422e-8fa7-805492e1e06c) - w takim przypadku dopisz, że dane dotyczą wątku #6453 na GitHubie.

**Comment by pkowalski700lm** [comment]
Witam, wysłałem, wycofuje zapytanie.. Chyba wiem co się stało. Możecie to zignorować.
