### ISSUE TITLE
[ShopGold] - Problem ze zweryfikowaniem konta

### ISSUE THREAD

**Issue by unc61** [allegro/allegro-api#6454]
Cześć,

Chciałbym dokończyć integrację pomiędzy Allegro, a sklepem opartym o shop gold. Konto zostało dodane, natomiast do dalszych zmian potrzebuję aktywnej sesji. Po przekierowaniu ze strony sklepu do allegro i zalogowaniu, zostaję odesłany na stronę z kodem błędu:

Nie możemy wyświetlić strony
Numer błędu: a05da0df389ca48b

UserID: 7707188

Z góry dziękuję za pomoc!

**Comment by MaciejFrackowiak** [comment]
Adres przekierowania, który podałeś w aplikacji nie jest zgodny z tym, który podałeś podczas rejestracji aplikacji na stronie [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/). Gdy poprawisz adres błąd zniknie.
