### ISSUE TITLE
[ With login or authorization] Don`t generate a new token

### ISSUE THREAD

**Issue by TarnJul** [allegro/allegro-api#6455]
Hi.

Earlier we set up the 1C connection to Allegro and it worked correctly.
But a month ago it stopped working.

Gives a 401 error, not generate token.

1C access to the program is also available. Application id is in related applications.

In the site: https://apps.developer.allegro.pl/ I find Client id and Client secret. But they don't generate a token too.
Can you tell what is the problem?

**Comment by PrzemyslawLukanowski** [comment]
It seems you are trying to refresh the token using an invalid refresh token. The token may have been revoked due to: expiration, password, or email change on the account. You need to authorize the application once again and generate new pair of tokens.

**Comment by TarnJul** [comment]
Is it necessary to remove the application from Powiązane aplikacje in the Allegro account and add it again?

**Comment by PrzemyslawLukanowski** [comment]
No, there is no need to do that. Your application should once again send a request to `https://allegro.pl/auth/oauth/authorize` to receive 10 seconds code and then call `https://allegro.pl/auth/oauth/token` to get new access and refresh the token. [Here](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#user-authorization) it is described in detail in points 1 and 5.

**Comment by PrzemyslawLukanowski** [comment]
Sorry, now I noticed that your application uses a device flow type of authorization, not code. In this case, you should take all the steps described [here](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow), from "The entire process is as follows (...)" (if you are seeing the page in Polish, change the language settings using top-right corner icon).

**Comment by TarnJul** [comment]
In link https://allegro.pl/auth/oauth/device I`m entered datas ( Client id and Client secret). Return error {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/auth/oauth/device","userMessage":null}]}

So I added new application in https://apps.developer.allegro.pl/, had new Client id and new client secret. And when i enter this datas in https://allegro.pl/auth/oauth/device i have this error too

**Comment by PrzemyslawLukanowski** [comment]
Are you sure that your request looks like this:

curl --location --request POST 'https://allegro.pl/auth/oauth/device?client_id={client_id}' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic {base64(client_id:client_secret)}' \

Can try to run it in the terminal?

If you are still getting this error, send us a sample code with all data using the c[ontact form](https://allegro.pl/pomoc/kontakt?kategoria=61571da6-f6de-4b8f-9ab9-699c8c797cfc&subjectId=35c2c795-4f94-49e2-8057-bbf00efe4433). Add information that the data applies to GitHub #6455 thread and should be forwarded to API Support.

**Comment by TarnJul** [comment]
Nothing changes. When I run the app it returns a 401 error again

I'd rather fill out the contact form. But the application uses the language of the 1C program, it is Russian. Is it ok? Or translate into English?
![Снимок](https://user-images.githubusercontent.com/99078207/206452557-439d96e9-3567-4975-9db6-e7c13948f3a7.PNG)

**Comment by PrzemyslawLukanowski** [comment]
It will be better to understand if you translate it into English. 401 status indicates that there must be something wrong with your Authorization header. Are you sure it's encoded properly? Also, I don't see information about the "Basic" type of authorization, after "Authorization" you pass some value right away.

**Comment by TarnJul** [comment]
There, the value is passed to the variable. The following is a function in which we get Base

"Are you sure it's encoded properly?" - I think yes because it worked. Stopped just a month ago 
![Снимок](https://user-images.githubusercontent.com/99078207/206459620-6b597c33-cb58-4395-aeff-bbffffa47893.PNG)

**Comment by PrzemyslawLukanowski** [comment]
Ok, so send us sample logs along with the client ID and client secret via the contact form. We will check our logs if there's something that could indicate the reason of the problem.

**Comment by TarnJul** [comment]
Thanks a lot

**Comment by PrzemyslawLukanowski** [comment]
We received your message, but these are not logs from your application - it seems that you are trying to enter https://allegro.pl/auth/oauth/device in the browser, and that’s why you’re receiving a 400 status with the „An error occurred” message. This request should be sent by your application, to generate the user code, device code, and the pair of tokens in the last step. This process is described in detail in [our tutorial](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow).
I assume you receive 401 Unauthorized status when you’re trying to refresh the token - that’s a proper response in this case because the refresh token you're using is no longer valid.

**Comment by TarnJul** [comment]
Well ok. Read carefully please.
You have seen my code. I run everything through the application. Plus, I created a new connection at https://apps.developer.allegro.pl/. Got a new ID and a secret. But they still throw a 401 error when I try to register the device app.
