### ISSUE TITLE
Sprzedaż zablokowana - ureguluj zaległości

### ISSUE THREAD

**Issue by piotrooo** [allegro/allegro-api#6456]
Podczas próby wystawienia przedmiotu dostaję błąd:

> Wystąpił błąd - Nie masz wymaganych uprawnień, aby wystawić ofertę (sprzedaż zablokowana). Ureguluj zaległości w "Rozliczenia z Allegro";

Przy czym dla konta jest wykonana nadpłata 20k zł
![Zrzut ekranu z 2022-12-07 12-17-03](https://user-images.githubusercontent.com/2005054/206165518-3c7a3122-66b1-4d04-8b59-41ed7a3087e3.png)

Czym może to być spowodowane?

Konto: **thulium**

**Comment by PrzemyslawLukanowski** [comment]
Czy problem występuje na produkcji czy na sandboxie?

**Comment by piotrooo** [comment]
Sandbox - wybacz nie dopisałem.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję. Problem już nie powinien występować, przepraszam za niedogodności.

**Comment by piotrooo** [comment]
Potwierdzam, jest ok, udało się wystawić ofertę.

**Comment by romigrabarz** [comment]
Mam również zablokowaną sprzedaż z powodu zaległości w "Rozliczenia z Allegro".
Proszę o aktywację konta sandbox - konto Acenter.

**Comment by PrzemyslawLukanowski** [comment]
@romigrabarz Blokada została zdjęta dziś o 13:08. Czy nadal masz problemy z kontem?
