### ISSUE TITLE
Transakcje zawarte w wypłacie środków

### ISSUE THREAD

**Issue by m-dn** [allegro/allegro-api#6457]
Dzień dobry,

Proszę o update, czy od ticketów nr. [#2913](https://github.com/allegro/allegro-api/issues/2913) i [#3970](https://github.com/allegro/allegro-api/issues/3970) została dodana jakaś metoda pozwalająca na bezpośrednie pobieranie danych o transakcjach zawartych w wypłacanych środkach, czy wciąż jedynym sposobem jest skorzystanie z metody wspomnianej w [#3970](https://github.com/allegro/allegro-api/issues/3970) [GET/payments/payment-operations](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory)?

**Comment by PrzemyslawLukanowski** [comment]
Nie wprowadzaliśmy żadnych zmian w związku z tym tematem, musisz zatem skorzystać z [GET/payments/payment-operations](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory).
