### ISSUE TITLE
Prośba o podanie przyczyny endedBy ADMIN oferty

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#6458]
Czy mogę poprosić o podanie przyczyny usunięcia przykładowej oferty z tego trace-id: f5d011fc3715aed4 ?

Mamy na tym koncie usuniętych około 3 tys. ofert z endedBy ADMIN. Czy to dlatego, że konto było przez chwilę zablokowane?

Przy okazji pytanie: może przeoczyliśmy i jest już jakiś sposób aby pobrać konkretniejszą przyczynę endedBy ADMIN przez REST API?

Dzięki z góry 
Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale nie udostępniamy w API zasobu, który zwróciłby bardziej konkretny powód, dlatego aby poznać przyczyny zakończenia ofert, skorzystaj proszę z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt).
