### ISSUE TITLE
Problem z wystawieniem aukcji przez IdoSell

### ISSUE THREAD

**Issue by pnow2022** [allegro/allegro-api#6459]
Dzień dobry,
mamy problem z wystawieniem aukcji przez IdoSell, podczas próby wystawienia produktu przez IdoSell i integracji tego systemu z Allegro wyskakuje nam komunikat: VALIDATION_ERROR null: nie możesz wystawić oferty bz powiązanego produktu w tej kategorii. Wybierz z katalogu lub utwórz nowy produkt i połącz go ze swoja oferta.

IdoSell twierdzi, ze wina leży po stronie systemu Allegro.

Niestety wystawiając aukcje przez allegro nie działa integracja z IdoSell.

Proszę o pomoc w rozwiązaniu problemu i informację w jaki sposób mogę wystawić aukcję na Allegro tak aby było to zintegrowane z moim systemem IdoSell i po zakupie informacje o nim pojawiała się w IdoSell

Pozdrawiam
Piotr
![6830f78de8588c5d701b36e3cb99cd5576eb56ac906e5595462fab3b0a9c1642](https://user-images.githubusercontent.com/120085539/206382802-910f7185-3b22-47d2-96fc-c0eb8ace4399.png)

**Comment by MaciejFrackowiak** [comment]
Komunikat, który pojawił się precyzyjnie informuje co jest powodem błędu - nie został podpięty produkt do oferty lub nie zostały podane wystarczające dane do utworzenia nowego produktu. Jako Allegro nie mamy wpływu na działanie IdoSell w tym zakresie - to w ich integracji wybierasz produkt z naszej bazy lub podajesz niezbędne dane do jego stworzenia. Jeżeli integrator twierdzi inaczej, to oczekujemy na informacje od niego - ma do nas kontakt. W tym momencie mogę Ciebie wyłącznie skierować do IdoSell, ponieważ tylko oni posiadają niezbędne logi potwierdzające wykonaną operację.
