### ISSUE TITLE
Problem z dodaniem oferty ConstraintViolationException.NoDuplicateIds

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#6460]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Witam,
Mam problem z dodaniem oferty. Przy próbie dodania dostaje dość enigmatyczny w treści błąd "Dany parametr możesz podać tylko raz.", ale brakuje mi informacji o jaki parametr chodzi, a na dodatek sprawdziłem parametry jakie wysyłamy i jedyne co dodajemy od siebie to stan i zawartość opakowania. Reszta parametrów pochodzi ze sparowanego produktu z katalogu Allegro.

```json
{
    "errors": [
      {
        "code": "ConstraintViolationException.NoDuplicateIds",
        "message": "You can only enter the parameter once.",
        "details": "ConstraintViolationException.NoDuplicateIds",
        "path": "parameters",
        "userMessage": "Dany parametr możesz podać tylko raz."
      }
    ]
  }
```

trace-id: 10612238e8b61d3e

**Comment by MaciejFrackowiak** [comment]
Źródłem problemu jest parametr "głębokość", który widnieje dwukrotnie w produkcie - przekazałem już sprawę do właściwego zespołu z prośbą o korektę danych produktu.

**Comment by MaciejFrackowiak** [comment]
Jak widzę produkt został już zaktualizowany. Obecnie problem nie powinien już występować.

**Comment by Himon-SYNCRAFT** [comment]
Super. Dziękuję bardzo za pomoc :+1:
