### ISSUE TITLE
Katalog produktów brak interesującej kategorii w kategoriach podobnych

### ISSUE THREAD

**Issue by kowalikus** [allegro/allegro-api#6461]
Mamy produkt, który chcielibyśmy prezentować **w innej kategorii** niż ta, która wynika z produktu znajdującego się **w katalogu Allegro**. Kategoria nie występuje też w podobnych (similar) kategoriach.

**Produkt w katalogu Allegro należy do kategorii:**

Allegro / Moda / Odzież, Obuwie, Dodatki / Odzież męska / Koszulki z długim rękawem

**Chcemy aby produkt znajdował się tutaj:**

Allegro / Sport i turystyka / Turystyka / Odzież / Bluzy, swetry

Jako, że chcemy zautomatyzować integracje **jak do tego powinniśmy podejść**?

**Comment by PrzemyslawLukanowski** [comment]
Jeśli natomiast nie chcecie wpływać na zmianę kategorii głównej, ale tylko dodać kategorię do kategorii podobnych, to w takim przypadku, zgodnie z [artykułem](https://allegro.pl/dla-sprzedajacych/jak-wystawic-oferte-w-innej-kategorii-niz-ta-przypisana-do-produktu-z-katalogu-1nKPvAzAKiP), musicie zgłosić zmianę za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
