### ISSUE TITLE
Adres nadawcy na etykiecie Allegro One Box

### ISSUE THREAD

**Issue by drzemik** [allegro/allegro-api#6463]
Dzień dobry,
W metodzie parcel-management/parcel-create-commands/
generuję przesyłkę:
array(6) {
  ["serviceId"]=>string(36) "0aafb43c-e66a-46ec-9cc4-29bb39ebb483"
  ["receiver"]=>array(6) {
    ...
  }
  ["pickup"]=>array(5) {
    ["address"]=>array(3) {
      ["street"]=>string(33) "Jerzego Kurpińskiego-Ponurego 12"
      ["postCode"]=>string(6) "42-215"
      ["city"]=>string(12) "Częstochowa"
    }
    ["name"]=>...
    ["pointId"]=>string(8) "AL006SC1"
    ["email"]=>...
    ["phone"]=>...
  }
  ["items"]=>array(1) {
    [0]=>array(4) {
      ["dimensions"]=>array(3) {
        ["height"]=>array(2) {
          ["value"]=>string(1) "1"
          ["unit"]=>string(10) "CENTIMETER"
        }
        ["width"]=>array(2) {
          ["value"]=>string(2) "30"
          ["unit"]=>string(10) "CENTIMETER"
        }
        ["depth"]=>array(2) {
          ["value"]=>string(2) "50"
          ["unit"]=>string(10) "CENTIMETER"
        }
      }
      ["weight"]=>array(2) {
        ["value"]=>string(1) "4"
        ["unit"]=>string(8) "KILOGRAM"
      }
      ["description"]=>string(17) "elektronarzędzia"
      ["type"]=>string(7) "PACKAGE"
    }
  }
  ["type"]=>string(7) "PACKAGE"
  ["label"]=>array(3) {
    ["sender"]=>array(4) {
      ["address"]=>array(4) {
        ["street"]=>...
        ["postCode"]=>...
        ["city"]=>...
        ["countryCode"]=>string(2) "PL"
      }
      ["email"]=>...
      ["company"]=>...
      ["phone"]=>...
    }
    ["fileFormat"]=>string(3) "PDF"
    ["referenceNumber"]=>string(7) "M246931"
  }
}
i otrzymuję response:
object(stdClass)#76 (4) {
  ["id"]=>string(36) "7c97a914-851c-4929-9546-8f8ba3294ca7"
  ["parcelId"]=>NULL
  ["status"]=>string(5) "ERROR"
  ["errors"]=>array(2) {
    [0]=>object(stdClass)#75 (5) {
      ["code"]=>string(5) "ERROR"
      ["message"]=>string(39) "Pickup street is too long, max 31 chars"
      ["details"]=>NULL
      ["path"]=>string(21) "pickup.address.street"
      ["userMessage"]=>string(55) "Ulica punktu nadania przesyłki jest za długa (Max 31)"
    }
    [1]=>object(stdClass)#74 (5) {
      ["code"]=>string(5) "ERROR"
      ["message"]=>string(50) ""Inne dane na etykiecie" not supporter for carrier"
      ["details"]=>NULL
      ["path"]=>string(7) "/sender"
      ["userMessage"]=>string(75) "Opcja 'Inne dane na etykiecie' nie są dostępne dla wybranego przewoźnika"
    }
  }
}
Jeżeli usunę gałąź label, etykietę uzyskuję, ale bez adresu nadawcy. Adres nadawcy jest potrzebny do ewentualnego zwrotu.
Jak mogę uzyskać adres nadawcy na etykiecie Allegro One Box?
Ulica pickup pochodzi z allegro. Dlaczego allegro podaje ulicę, którą potem weryfikuje jako nieprawidłową?

Pozdrawiam
Dariusz Drzemicki

**Comment by PrzemyslawLukanowski** [comment]
> Jak mogę uzyskać adres nadawcy na etykiecie Allegro One Box?

Błąd o treści "Opcja 'Inne dane na etykiecie' nie są dostępne dla wybranego przewoźnika""jest spowodowany tym, że nie każdy przewoźnik umożliwia na umieszczenie na etykiecie innych danych niż dane nadawcy z sekcji "pickup". Jeśli w polu label.sender przekazujesz null, przewoźnik powinien pobrać dane z pola "pickup". Czy po poprawieniu nazwy ulicy w pickup, adres nadal nie jest widoczny? 

> Ulica pickup pochodzi z allegro. Dlaczego allegro podaje ulicę, którą potem weryfikuje jako nieprawidłową?

Długość wartości w tym polu jest zależna od ustawień danego przewoźnika, nie jest to stała wartość dla każdego z nich. Może się zatem zdarzyć, że długość w książce nadawczej ma więcej znaków, ale przewoźnik ma mniejszy limit.

**Comment by PrzemyslawLukanowski** [comment]
Adres odbiorcy to receiver:
<img width="504" alt="Zrzut ekranu 2022-12-8 o 12 15 11" src="https://user-images.githubusercontent.com/51473661/206433241-d0a67c91-07b1-40e4-b0a6-f2098105749c.png">
pickup to dane nadawcy - miejsce, z którego odbierana jest przesyłka
<img width="533" alt="Zrzut ekranu 2022-12-8 o 12 15 18" src="https://user-images.githubusercontent.com/51473661/206433258-232851e7-f159-410f-b86e-0a1fe30b4364.png">
