### ISSUE TITLE
Dodanie produktu do katalogu - parametr nie istnieje

### ISSUE THREAD

**Issue by d21d4** [allegro/allegro-api#6464]
Dzień dobry, 
przy próbie dodania produktu do katalogu poprzez zewnętrzne oprogramowanie wyrzuca nam błąd " Nie udało się zaktualizować przypisania katalogu Allegro - Parametr 245577 nie istnieje. " 
Ścieżka kategorii, w której występuje błąd: Allegro / Dom i ogród / Budownictwo i akcesoria / Ogrzewanie / Grzejniki / Grzejniki konwektorowe
Po weryfikacji z poziomu wystawiania przez formularz Allegro - ilość oraz treść parametrów jest taka sama.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że parametr o identyfikatorze 245577 nie występuje we wspomnianej kategorii. Prawdopodobnie jest to nieaktualna wartość ID parametru "Wysokość", która została przez nas w przeszłości zmieniona na 227357. Parametr 245577  nie występuje aktualnie w żadnej kategorii. W tej sytuacji prosiłbym o kontakt ze wsparciem aplikacji, z której Państwo korzystają - konieczna będzie aktualizacja listy parametrów.

**Comment by d21d4** [comment]
Dziękuję za szczegółowe wyjaśnienie i sugestie.
