### ISSUE TITLE
How to get a security token?

### ISSUE THREAD

**Issue by cunekp** [allegro/allegro-api#6465]
Hello,
I need to download a list of orders. I have Client secret and Client ID. How do I get the security token automatically without the user having to log into Allegro? Is it possible?

**Comment by MaciejFrackowiak** [comment]
No, you are not able to retrieve orders without user consent. You have to use one of the existing authorization - you can read about it in [our tutorial](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY).
