### ISSUE TITLE
sandbox - aktywacja konta sprzedawcy 

### ISSUE THREAD

**Issue by mikolaj-bronk** [allegro/allegro-api#6466]
Dzień dobry, 

Tak jak w innych tego typu przypadkach tutaj na forum prosiłbym o aktywację/weryfikację konta sprzedawcy **ecommerce_CS** na środowisku sandboxowym. Niestety weryfikacja poprzez sandboxowe środowisko przelewów natychmiastowych nie aktywuje automatycznie sprzedawcy nawet w wersji małej firmy.

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.

**Comment by mikolaj-bronk** [comment]
Dziękuję pięknie
