### ISSUE TITLE
Allegro Kurier Pocztex pobranie

### ISSUE THREAD

**Issue by allegrofan** [allegro/allegro-api#6467]
Cześć, pobieram ID usługi : "service":"POCZTA_POLSKA","name":"Allegro Kurier Pocztex pobranie (umowa poczta)","owner":"CLIENT","carrierId":"POCZTA_POLSKA","additionalServices":{"cashOnDelivery":{"available": ...
mam podpiętą umowę z pocztą.
Zamówienie z dostawą: Allegro Kurier Pocztex pobranie.
Podczas tworzenia przesyłki otrzymuję komunikat: "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać przykładowe commandId, za pomocą którego próbujesz utworzyć paczkę?

**Comment by allegrofan** [comment]
{"id":"7bc1aeb1-82f0-43b8-bd8d-f11d38d43fb8","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Processing error","details":null,"path":null,"userMessage":"Problem z nadaniem przesyu0142ki. Skontaktuj siu0119 z nami. Pomou017cemy jak najszybciej."}]}

**Comment by PrzemyslawLukanowski** [comment]
Prosiłbym jeszcze o cierpliwość, weryfikuję ten problem. Wrócę z odpowiedzią.

**Comment by allegrofan** [comment]
Dziękuję, czekam

**Comment by PrzemyslawLukanowski** [comment]
Dokładny powód przez, który nie udało się utworzyć przesyłki jest taki, że Pocztex Kurier 48 (Przesyłka biznesowa) nie znajduje się na umowie zawartej z Pocztą Polską S.A.

**Comment by allegrofan** [comment]
Poczta zmieniła usługę na Pocztex 2.0 zastępując Pocztex Kurier 48 więc nie wiem dlaczego nie zostało to zmienione również w API Allegro?

**Comment by allegrofan** [comment]
W dodatku w ustawieniach Allegro mam wyłączone "Allegro Pocztex Kurier 48 "i aktywne "Allegro Kurier Pocztex".

**Comment by PrzemyslawLukanowski** [comment]
> Poczta zmieniła usługę na Pocztex 2.0 zastępując Pocztex Kurier 48 więc nie wiem dlaczego nie zostało to zmienione również w API Allegro?

Ponieważ dotyczy to Twojej indywidualnej umowy, a nie wszystkich.

Poczta Polska zastępuje "stare" usługi, tj. Kurier Pocztex 48, nowymi - Kurier Pocztex (tzw. Pocztex 2.0). W związku z tym stopniowo wyłącza klientom usługi, zgodnie z zapisami umowy/aneksu.

Umowa Allegro działa zarówno dla Kurier Pocztex 48, jak i Pocztex. Natomiast problem może pojawić się w momencie, kiedy będziesz musiał w WzA nadać coś na umowie własnej (a wszystkie paczki pobraniowe trzeba nadawać na umowie własnej). Jeśli Twoja usługa Kurier Pocztex 48 wygasła, nie nadasz takiej paczki w WzA, otrzymasz od nas wspominany komunikat: "Produkt ('Pocztex Kurier 48 (Przesyłka biznesowa) (852)') nie znajduje się na umowie zawartej z Pocztą Polską S.A."

Zapytaliśmy Pocztę Polską, co użytkownik może zrobić w takiej sytuacji - możliwe są dwa rozwiązania. W obu przypadkach możliwe będzie utworzenie usługi / przesyłki w Elektronicznym Nadawcy, zgodnie z katalogiem usług dostępnych w umowie w chwili tworzenia przesyłek:
* ręczna rejestracja przesyłki w systemie Elektroniczny Nadawca. WAŻNE: w polu "Email" w danych przesyłki musi być podany alias/maskowany adres email przypisany do zamówienia w Allegro,
* wykorzystanie do tworzenia przesyłek funkcjonalności EN "Import --> z zamówień pobranych przez API Allegro".

**Comment by PrzemyslawLukanowski** [comment]
Prosiłbym jeszcze o cierpliwość, weryfikuję tę sytuację z zespołem odpowiedzialnym za usługę Wysyłam z Allegro.

**Comment by PrzemyslawLukanowski** [comment]
Wracam z odpowiedzią - do wybranej metody musisz wybrać odpowiednią usługę dodatkową: additionalServices. W tym przypadku "pocztex. W przyszłości to uspójnimy, aby nie było to konieczne.

**Comment by allegrofan** [comment]
W jaki sposób? $data[additionalServices][name]="pocztex"; ?

**Comment by PrzemyslawLukanowski** [comment]
Struktura powinna wyglądać jak na poniższym przykładzie:

```
"additionalServices": {
    "options": [
        "pocztex"
     ]
}
```

**Comment by allegrofan** [comment]
{"id":"e0d0b2c2-a192-4256-8c48-46e0c7c392c1","parcelId":null,"status":"IN_PROGRESS","errors":[]}
a potem komunikat "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."
Zamawiam przesyłkę "Allegro Punkty Poczta pobranie"

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję tę sytuację, wrócę z informacją.

**Comment by allegrofan** [comment]
To co mam zrobić? Wciąż nie mogę zamówić przesyłki pobraniowej na swojej umowie z pocztą. Gdzie jest problem? w API Allegro czy coś jest nie tak z umową i panelem Poczty?

**Comment by PrzemyslawLukanowski** [comment]
Wcześniej wspomniałeś, że klient złożył zamówienie z przesyłką Allegro Kurier Pocztex pobranie, dlatego powinieneś nadać ją na odpowiedniej umowie /usłudze dostawy i w strukturze żądania dołożyć informację o usłudze dodatkowej - "pocztex". W powyższym przypadku kupujący wybrał metodę "Allegro Punkty Poczta pobranie" i związku z tym wybrałeś także inną usługę - Allegro Punkty Poczta pobranie (umowa poczta), dla niej nie wspieramy opcji dodatkowej "pocztex", zatem nie powinieneś przekazywać tego pola.

**Comment by allegrofan** [comment]
Dziękuję, potrzebuję czasu aby to sprawdzić tzn poczekać na nowe zamówienia z tą formą przesyłki.

**Comment by allegrofan** [comment]
Mam zamówienie z przesyłką : Allegro Kurier Pocztex pobranie.

Przekazałem $data[additionalServices][options] = array("pocztex");

i mimo to :

{"id":"a34e55ef-53e7-4c28-b7db-89993b2c9efe","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Processing error","details":null,"path":null,"userMessage":"Problem z nadaniem przesyu0142ki. Skontaktuj siu0119 z nami. Pomou017cemy jak najszybciej."}]}

**Comment by PrzemyslawLukanowski** [comment]
Usługa ubezpieczenia nie jest dostępna dla wybranej umowy, skontaktuj się proszę z opiekunem klienta lub z infolinią Poczty Polskiej. W naszym API za ubezpieczenie odpowiada pole items.value.amount, możesz również spróbować je usunąć.

**Comment by allegrofan** [comment]
Skasowanie  'value' => array("amount" => "".$amount."", "currency" => "".$currency."") nic nie dało. Wciąż mam błąd

{"id":"d093969e-4bff-4ea6-bb37-6ec35e9e7e61","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Processing error","details":null,"path":null,"userMessage":"Problem z nadaniem przesyu0142ki. Skontaktuj siu0119 z nami. Pomou017cemy jak najszybciej."}]}

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku w `additionalServices.options` brakuje informacji o "pocztex".
