### ISSUE TITLE
Missing Body section in PUT Delivery Settings (/sale/delivery-settings)

### ISSUE THREAD

**Issue by JiriSobotikAtMall** [allegro/allegro-api#6468]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource

:beetle: **Opis / Description**
There is missing a requestBody section in PUT operation for Delivery Settings [/sale/delivery-settings]
Its impossible to use generated client properly, because of this.

**Comment by PrzemyslawLukanowski** [comment]
Thank you for that. I passed a request to our team responsible for this service to complete the missing data. I will let you know when the problem is solved.

**Comment by AureliuszBrussy** [comment]
We completed the documentation with the missing section.
