### ISSUE TITLE
Pobieranie listy wystawionych ofert

### ISSUE THREAD

**Issue by krzysztoffigiel** [allegro/allegro-api#647]
Dzień dobry,

Czy istnieje możliwość pobierania listy wystawionych przeze mnie ofert w REST API?

**Comment by collector1871** [comment]
tak w skrócie:
[https://developer.allegro.pl/documentation/#/offers-listing](https://developer.allegro.pl/documentation/#/offers-listing)
[https://developer.allegro.pl/news/2018-07-03-Listing_ofert/](https://developer.allegro.pl/news/2018-07-03-Listing_ofert/)

GET /offers/listing

`searchMode` dajesz jako ACTIVE

tutaj więcej jak to zaimplementować, żeby całą listę mieć:
[https://github.com/allegro/allegro-api/issues/640](https://github.com/allegro/allegro-api/issues/640)

**Comment by krzysztoffigiel** [comment]
@collector1871 dziękuję bardzo!
