### ISSUE TITLE
Problemy z działaniem WzA

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#6472]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Czy macie jakieś problemy z działaniem usługi wza?
Paczki generują się strasznie długo.  Jedne po bardzo długim czasie w końcu mają status Succes a inne nadal in_progres ( a mimo to na froncie nr listu dodany?)
nr :
60379259-2420-4fd6-9023-7e5bf6162bb8
9bd5e279-5bdd-4406-b3ac-c9276d80a443
0e60a68f-bb12-4baa-abf0-e1741928a6f8
7c0b4cdd-637e-431b-8a43-fcd9f5a320f1

**Comment by MaciejFrackowiak** [comment]
Tak, nasz dostawca usługi przeprowadził nieoczekiwane zmiany, które od ok. 10:40 powinny zostać wycofane. Proszę spróbuj nadać ponownie przesyłki.
