### ISSUE TITLE
Pobieranie punktów odbioru 

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#6476]
Czy jest możliwość pobrania aktualnych punktów odbioru dla konta allegro z allegro api?

Przy zamówieniu z wybraną formą dostawy typu odbiór osobisty dostajemy taką zwrotkę, ale nie mamy możliwości (albo nie znamy endpointu) do pobrania wszystkich takich punktów ustawionych w panelu allegro. W dokumentacji nie widziałem takich informacji dlatego zakładam wątek.

67024
```
 [pickupPoint] => Array
                        (
                            [id] => 95b620de-964d-11e9-bc29-000af7f61ee0
                            [name] => ---
                            [description] => 
                            [address] => Array
                                (
                                    [street] => ---
                                    [zipCode] => ---
                                    [city] => Warszawa
                                )

                            [modifiedAt] => 
                        )
```

**Comment by Lukasz-Zurek** [comment]
Niestety nie mamy zasobu, który pozwoliłby pobrać listę punktów odbioru osobistego. Możesz dodać sugestię w dedykowanej do tego zakładce [Discussions](https://github.com/allegro/allegro-api/discussions).
