### ISSUE TITLE
Błędy przy próbie wysłania /sale/product-offers

### ISSUE THREAD

**Issue by mkawczynski** [allegro/allegro-api#6477]
Witam,
w dniu dzisiejszym dostajemy błędy przy próbie wysłania oferty. Dane wysyłane te same co od miesięcy.
Błąd sugeruje problem z wypełnieniem pola delivery:

errors:
  - code: PRICE_LIST_NOT_SAVED
    message: Delivery details not saved.
    details:
    path: offer.delivery
    userMessage: Brak uzupełnionych danych o dostawie.

przydkładowe dane pola delivery jakie wysyłam:
{"handlingTime"=>"PT24H", "shippingRates"=>{"id"=>"dfe42879-10f6-4091-b438-4faa5ec1e783"}}
id shippingRates jest poprawne - sprawdzałem pobierając przez API aktualne cenniki dostaw

Nie wiem, co się dzieję - proszę o pomoc.

Pozdrawiam
Marek Kawczyński

**Comment by czlowiekpolar** [comment]
Potwierdzam, taki sam błąd występuje u nas.

**Comment by Maczuga** [comment]
Potwierdzam, też mamy ten problem.

W naszym przypadku udało się zlokalizować, że nagle z dniem dzisiejszym - GET /sale/product-offers/:offerId nagle zwraca podzbiór `delivery` w taki sposób:
```
"delivery":{"shippingRates":null,"handlingTime":null,"additionalInfo":null,"shipmentDate":null}
```
Dane te były wcześniej uzupełnione.

Niestety ponowne uzupełnienie tych danych i przesłanie uzupełnionego JSONa nic nie daje - dalej zwraca błąd.

**Comment by CrazyTaolt** [comment]
We have the same problem

`
{"errors":[{"code":"PRICE_LIST_NOT_SAVED","message":"Delivery details not saved.","details":null,"path":"offer.delivery","userMessage":"Brak uzupełnionych danych o dostawie."}]}
`

**Comment by raimondases4b** [comment]
+ same. Sometimes with several retries its passes without error.

**Comment by MaciejFrackowiak** [comment]
Weryfikujemy Wasze obserwacje / We are investigating your observations.

**Comment by jakubmaguza** [comment]
Problem podobny, ale trudniejszy do wykrycia -> Nie mogę tym zasobem zmienić czasu dostawy. Teoretycznie nie ma żadnych błędów, ale czas dostawy się nie zmienia.

**Comment by cyfranT** [comment]
Również mamy ten problem, przy aktualizacji handlingTime oraz shippingRateId z użyciem zasobu PATCH /sale/product-offers/{offerId} otrzymujemy zwrotnie STATUS OK ale aktualizacja się nie wykonuje a wartości  zwracane w sekcji delivery to same null:
{"shippingRates":null,"handlingTime":null,"additionalInfo":null,"shipmentDate":null}

**Comment by Pavulon87** [comment]
J.w. - nie zmienia się czas dostawy pomimo statusu ok.
Problem nie występuje w innych przypadkach jak np. sellingMode.

**Comment by Lukasz-Zurek** [comment]
Bardzo przepraszamy Was wszystkich za zaistniałe utrudnienia, które miały miejsce w dniu wczorajszym. Problemy te nie powinny się już powtarzać.

**Comment by CrazyTaolt** [comment]
@Lukasz-Zurek Witam, chciałbym zapytać, czy ten problem został rozwiązany?

**Comment by Lukasz-Zurek** [comment]
@CrazyTaolt Tak, problem został rozwiązany.
