### ISSUE TITLE
Błąd przy próbie dodania nowej oferty - PRICE_LIST_NOT_SAVED: Brak uzupełnionych danych o dostawie

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#6478]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Witam.
Dostaję dziwny błąd przy próbie dodania nowej oferty: "PRICE_LIST_NOT_SAVED: Brak uzupełnionych danych o dostawie". Sprawdziłem i wydaje się, że poprawnie wysyłam dane o dostawach.

trace-id: f9a7b40bc9bce63a

**Comment by MaciejFrackowiak** [comment]
Sprawdzamy to - podobnie jak w zgłoszeniu https://github.com/allegro/allegro-api/issues/6477.

**Comment by glorifyingpeace** [comment]
Podbijam temat. U naszych klientów to samo....

**Comment by jakubmaguza** [comment]
Problem podobny, ale trudniejszy do wykrycia -> Nie mogę tym zasobem zmienić czasu dostawy. Teoretycznie nie ma żadnych błędów, ale czas dostawy się nie zmienia.
