### ISSUE TITLE
Maintenance fee

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#6479]
Dobry wieczór!
Stosując metodę
`https://api.allegro.pl/sale/offers?limit=1000&publication.status=ACTIVE`
+ offset
Dostałem wszystkie aktywne oferty.
Również z kolumny
 _['publication']['startedAt']_ 
uzyskałem datę publikacji ofert i z
_["stock"]["sold"]_
aby dowiedzieć się, które oferty zostały sprzedane.
Jednak efekt wyszedł zupełnie inny niż się spodziewałem. Opłata za utrzymanie, którą widzę na koncie osobistym jest zupełnie inna.
**Dlaczego tak jest?**
Czytałem tutaj
https://allegro.pl/for-sellers/fees-on-allegro-5Lxk5j64OFO
że opłata jest pobierana co 365 dni od momentu zamieszczenia oferty lub do momentu jej sprzedaży.
Czy możecie mi powiedzieć, jak mogę uzyskać informacje o tym, które oferty podlegają opłacie eksploatacyjnej, inaczej niż w moim gabinecie? Chciałbym zautomatyzować raportowanie. Ja, wcześniej, trafiłem na reklamy i, o ile pamiętam wtedy, nie dało się uzyskać danych o reklamach przez api, co oczywiście bardzo utrudnia analizę danych i spowalnia decyzję o dodaniu nowych ofert do platformy. A w ogóle to spowalnia gęstszą pracę z Allegro. Jeśli istnieje możliwość automatycznego otrzymywania danych o kontach reklamowych i innych alokacjach, **proszę o informację** na ten temat

**Comment by Lukasz-Zurek** [comment]
Za pomocą [GET /pricing/offer-quotes](https://developer.allegro.pl/tutorials/jak-sprawdzic-oplaty-nn9DOL5PASX#data-naliczenia-kolejnej-oplaty) sprawdzisz opłaty nadchodzące w najbliższym cyklu 10-dniowym - w tym również informację o opłacie utrzymaniowej. Nie ma innej możliwości sprawdzania opłat utrzymaniowych. Natomiast wspomniany zasób zwraca informacje tylko o najbliższych cyklach 10 dniowych. Tu zatem należałoby we własnym zakresie zapisywać datę ostatniej sprzedaży w danej ofercie i względem niej obliczać 365 dni do naliczania opłaty utrzymaniowej.

Dodam, że nie jestem pewien co masz na myśli pisząc o otrzymywaniu danych o kontach reklamowych i innych alokacjach. Doprecyzuj proszę.

**Comment by sergeidebug** [comment]
Bardzo dziękuję!
Chodzi mi o to, że pracujemy z wieloma platformami i analizujemy dane pod kątem innych platform i serwisów niż Allegro. Ustawiłem automatyczne raporty. Po prostu nie będzie fizycznie możliwe wyciągnięcie danych z szafy do csv i nadanie im struktury. Więc jeśli jest lub będzie sposób, aby uzyskać dane z konta Allegro poprzez api, to byłoby świetnie!
Dzięki, spróbuję tej metody Pan wskazał powyżej

Przetłumaczono z www.DeepL.com/Translator (wersja darmowa)

**Comment by sergeidebug** [comment]
Bardzo dziękuję!
Chodzi mi o to, że pracujemy z wieloma platformami i analizujemy dane pod kątem innych platform i serwisów niż Allegro. Ustawiłem automatyczne raporty. Po prostu nie będzie fizycznie możliwe wyciągnięcie danych z szafy do csv i nadanie im struktury. Więc jeśli jest lub będzie sposób, aby uzyskać dane z konta Allegro poprzez api, to byłoby świetnie!
Dzięki, spróbuję tej metody Pan wskazał powyżej
