### ISSUE TITLE
[REST] GET /order/checkout-forms - kolejność i filtry

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#648]
Dzień dobry,

korzystam z GET /order/checkout-forms, i zauważyłem dwa błędy:

1. Zwracane rekordy nie są w kolejności od najnowszego zamówienia (wg. boughtAt), pierwsza strona wyniku to sprzedaż pomieszana w ostatnich kilku dniach. W panelu na allegro.pl sprzedaż jest ładnie poukładana wg. kolejności od najnowszego zakupu.

2. Zapytanie ignoruje filtry lineItems.boughtAt.gte oraz lineItems.boughtAt.lte - np. chcę zakupy dokonane tylko dzisiejszego dnia, a dostaję w paczce zakupy z przed kilku dni.

Przykład zapytania:

https://api.allegro.pl/order/checkout-forms?status=READY_FOR_PROCESSING&lineItems.boughtAt.gte=2018-25-09T00%3A00%3A00.000Z

**Comment by tztztztz** [comment]
Wykonany URL: https://api.allegro.pl/order/checkout-forms?status=READY_FOR_PROCESSING&lineItems.boughtAt.gte=2018-26-09T00%3A00%3A00.000Z

Parametry:

Array
(
    [status] => READY_FOR_PROCESSING
    [lineItems.boughtAt.gte] => 2018-26-09T00:00:00.000Z
)


Nie mogę wkleić pełnej odpowiedzi, bo zawiera dane osobowe, podam kolejność ID transakcji:

d823a604-c166-11e8-b319-bf7f50f827c3 (2018-09-26T08:35:37.134Z)
4d12f832-c022-11e8-9b77-cfae7a3f01a2 (2018-09-24T17:50:23.656Z)
1460ceb2-c160-11e8-b319-bf7f50f827c3 (2018-09-26T07:45:25.682Z)

i tak dalej....

Już pierwsze 3 rekordy pokazują problem:

pierwszy z dzisiaj, kolejny z dnia 24, a potem znowu z dzisiaj

**Comment by MartaNowaczyk** [comment]
Na początek zamień miejscami miesiąc i dzień
z 2018-26-09T00:00:00.000Z na 2018-09-26T00:00:00.000Z
Nie dostawałeś żadnego błędu?

**Comment by tztztztz** [comment]
Hmm faktycznie miesiąc powinien być po roku, zmieniłem, i oto URL do pobrania dzisiejszej sprzedaży:

https://api.allegro.pl/order/checkout-forms?status=READY_FOR_PROCESSING&lineItems.boughtAt.gte=2018-09-27T00%3A00%3A00.000Z

Niestey nadal to samo, podaję id transakcji, a w nawiasie boughtAt:

31605542-c0c4-11e8-91c0-a73af41b74d2 (2018-09-25T13:09:25.939Z)
1179b5e2-c1c4-11e8-b535-81418c733987 (2018-09-26T19:40:54.417Z)
d823a604-c166-11e8-b319-bf7f50f827c3 (2018-09-26T08:35:37.134Z)
77a137a2-c1d1-11e8-91c0-a73af41b74d2 (2018-09-26T21:18:58.287Z)
cda15942-c1cd-11e8-9684-81418c733987 (2018-09-26T20:51:50.465Z)

Jeden filtry działa jedynie poprawnie - wybierający sprzedaż o okreslonym statusie READY_FOR_PROCESSING, i jak rozumiem cdecha "boughtAt" zostaje ustawiona na datę i czas zmiany statusu na READY_FOR_PROCESSING? Problememy (dla mnie) by było kiedy klient wczoraj zrobiłby zakup, a dzisiaj dopiero opłacił, i "boughtAt" wskazywałoby na wczoraj.

I tak dalej jest nawet sprzedaż z przed 3 dni - bo o ile rozumiem

**Comment by tztztztz** [comment]
Połowiczny sukces: problem tkwił w rozdzielaniu parametrów - używałem &amp;, zamiast po prostu samego &, stąd Wasz system brał pod uwagę tylko pierwszy parametr GET.

Teraz dostaję wyniki z okresu czasu jaki potrzebuję, niestety nadal pozostaje kwestia pomieszania kolejności w wyniku, np. pobieram zamówienia dla okresu ostatnich 3 dni i mam najpierw zamowienia z dnia 26, potem 25, a potem znowu 26, etc.

Dlatego skorzystam raczej z /order/events i na ten moment dziękuję za pomoc.

**Comment by MartaNowaczyk** [comment]
Czy możesz jeszcze podać trace-id z nagłówka? Pomoże to w weryfikacji.

**Comment by MartaNowaczyk** [comment]
Mam jeszcze jedną prośbę. Prześlij proszę pełne curle response i request przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt#appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=9fe60f94-a07b-47e5-84b4-b15beafe2422), aby nie było problemu z wrażliwymi danymi. Dopisz tylko, że to dane na prośbę admina GitHub #648.

**Comment by tztztztz** [comment]
Przykro mi, ale absolutnie nie, dane osobowe to dla mnie świętość. Nawet jeżeli i tak macie do nich dostęp przez swoją platformę, to ja nie zamierzam ich pobierać i wysyłać.

Po za tym, uważam, że macie już wszystko co potrzeba do zidentyfikowania błędu, nie rozumiem po co pełny wynik razem z danymi osobowymi. 

Brakuje Wam po prostu w miejscu gdzie przekazujecie wynik klientowi API, dyrektywy ORDER BY lub innej sortującej po cesze "boughtAt" jeżeli działacie na jakimś NoSQLu.

**Comment by MartaNowaczyk** [comment]
Z podpiętego wątku wynika, że temat do zamknięcia.

**Comment by madkot** [comment]
W podpiętym wątku sprawa się nie wyjaśniła! Proszę o wznowienie tematu. To ważne i co istotne może ograniczyć zapytania do API.

**Comment by expondo** [comment]
Liczę na szybkie rozwiązanie problemu sortowania zamówień, ponieważ temat ciągnie się od miesiąca na kilku zgłoszeniach i nadal nie było żadnej poprawki w tym zakresie.

**Comment by expondo** [comment]
I proszę zmienić status zgłoszenia aby inni użytkownicy widzieli że temat jest cały czas na tapecie i mogli go kontrolować.

**Comment by MartaNowaczyk** [comment]
Potwierdzam błędnie zwracaną kolejność. Pracujemy nad rozwiązaniem problemu.

**Comment by tztztztz** [comment]
Brawo, tylko 27 dni zajęło potwierdzenie błędu, który można było potwierdzić w 2 minuty wbijając komendą CURL i patrząc na kolejność na ekranie. Należy się medal 🥇 Jestem ciekaw ile zajmie naprawa.

**Comment by MartaNowaczyk** [comment]
@tztztztz @madkot @expondo największy problem polegał na tym, że nie zawsze zwracane dane były w nieprawidłowej kolejności, ale udało nam się namierzyć problem i wprowadziliśmy poprawkę. Sprawdźcie proszę czy działa. Dzięki.

**Comment by expondo** [comment]
Sprawdziliśmy wyniki i teraz mamy je posortowane po statusie a nie po dacie złożenia zamówienia.

**Comment by MartaNowaczyk** [comment]
@expando używasz filtrów? Podaj request URL i trace-id

**Comment by madkot** [comment]
u mnie z filtrem czy bez, nie sortuje po dacie jak należy
https://api.allegro.pl/order/checkout-forms?status=ALL
Obecnie posortowane wyniki po statusie mają różne daty z bieżącego miesiące (23, 22, 23, 21 .. i tak na zmianę bez żadnej logiki odnośnie sortowania po dacie)

**Comment by MartaNowaczyk** [comment]
@madkot @expando sprawdźcie jeszcze raz proszę

**Comment by madkot** [comment]
@MartaNowaczyk wstępnie widzę, że jest posortowane po dacie :) sprawdzę to później na spokojnie czy jest w 100% poprawnie i jeszcze raz odpisze.

**Comment by MartaNowaczyk** [comment]
@madkot Świetnie, zatem czekam na info :)

**Comment by madkot** [comment]
Wygląda ok, dziękuje :)

**Comment by MartaNowaczyk** [comment]
Błąd naprawiony. Dziękuję wszystkim za zaangażowanie. 
Mogę już chyba zamknąć wątek.
