### ISSUE TITLE
sale/product-offers/ i brak zmiany handlingTime

### ISSUE THREAD

**Issue by chermol** [allegro/allegro-api#6480]
PATCH na sale/product-offers/{id} i próba zmiany wartości handlingTime nie odnosi skutku, mam kod 200, ale rezultat żaden, w zwrotce żadne pole w delivery nie ma wartości, nową wartość podaje zgodnie z ISO 8601

działa tylko zmiana shipmentDate, żadne inne w delivery nie

pobranie zresztą GET na sale/product-offers/{id} też w delivery pusto

czy jest jakis inny sposób na zmianę wartości handlingTime ?

**Comment by Lukasz-Zurek** [comment]
Sprawdziłem i bez problemu udało mi się zmienić czas wysyłki w **handlingTime**. Jaką wartość miała wcześniej Twoja oferta i na jaką wartość próbowałeś zmienić czas wysyłki? W polu **handlingTime** możesz przekazywać zarówno wartość PT48H (w godzinach), jak i P2D (w dniach) - to jest to samo. Podobnie jak PT72H i P3D. Być może miałeś właśnie taką sytuację. Jeśli nie - prześlij proszę trace-id.

**Comment by chermol** [comment]
Niesamowite :-) dziś już działa.

**Comment by Lukasz-Zurek** [comment]
@chermol **Pavulon87** słusznie zwrócił uwagę na wskazany wątek. Przepraszamy za zaistniałe utrudnienia.
