### ISSUE TITLE
Błąd przy generowaniu przesyłek

### ISSUE THREAD

**Issue by OskarSw** [allegro/allegro-api#6485]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dzień dobry,
Przy próbie generowania przesyłek (dla różnych zamówień) przy pomocy parcel-management/parcel-create-commands zaczęliśmy otrzymywać odpowiedź:

```{
  "status": "ERROR",
  "errors": [
    {
      "path": null,
      "message": "Processing error",
      "code": "ERROR",
      "details": null,
      "userMessage": "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."
    }
  ],
  "parcelId": null,
  "id": "11671e6d-2145-403a-aae0-b1f59ab3ef35"
}
```
Proszę o pomoc w ustaleniu przyczyny.

**Comment by MartaNowaczyk** [comment]
Weryfikuję zgłoszenie. Wrócę z informacją.

**Comment by MartaNowaczyk** [comment]
W tym przypadku kod pocztowy odbiorcy znajduje się poza obszarem metody dostawy One Kurier.
