### ISSUE TITLE
Mapowanie paczek z zamówieniem Allegro

### ISSUE THREAD

**Issue by LukaszWypych** [allegro/allegro-api#6486]
Dzień dobry,
mam pytanie w jaki sposób mapowane są wysyłane paczki za pomocą "Wysyłam z Allegro" (endpoint /parcel-management/parcel-create-commands/{commandId})?
W dokumentacji napisane jest, że wybór serwisu kurierskiego jest zależny od tego podanego na zamówieniu, ale nie widzę opcji w api podczas tworzenia packi do wskazania, którego zamówienia ta paczka dotyczy.

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Zamówienie rozpoznajemy na podstawie maskowanego adresu e-mail wygenerowanego przez Allegro, który zawiera identyfikator transakcji.
