### ISSUE TITLE
Endpoint - customer-returns - pozytywny status akceptacji zwrotu

### ISSUE THREAD

**Issue by mikolaj-bronk** [allegro/allegro-api#6487]
Dzień dobry,

Mam pytanie do endpointu /order/customer-returns.

W jaki sposób można wyciągnąć, że zwrot został zaakceptowany?
Obecnie jest tak, że jeżeli klient zgłosi zwrot, to w endpointcie pojawia się wpis o zwrocie, ale gdy go jako sprzedawca zaakceptowałem, to nie widzę zmian w tym endpointcie. Dopiero gdy wybrałem odrzucenie zwrotu, to mam informację o tym w węźle "rejection". W jaki sposób mogę rozpoznać/odfiltrować takie, które zostały zaakceptowane przez sprzedawcę.

**Comment by MartaNowaczyk** [comment]
Nie ma takiego statusu i możliwości odfiltrowania takich zwrotów, tak jak piszesz jest tylko odrzucenie zwrotu. 
Zachęcam do zgłaszania swoich sugestii/braków w zasobach w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions). Po liczbie osób, które popierają dany pomysł, widzimy jak duża jest potrzeba wprowadzenia danej zmiany.
