### ISSUE TITLE
Get parcel label

### ISSUE THREAD

**Issue by filip-frisbo** [allegro/allegro-api#6488]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Hello! I need to retrieve the parcel label using this request https://developer.allegro.pl/documentation#operation/getParcelLabel. 
However, when I'm trying to get the parcelId using this route GET https://api.allegro.pl/parcel-management/parcel-create-commands/c61b7750-77b8-11ed-82ce-17091860525a I get 404 Not found and this body message {
"errors": [
{
"code": "ERROR",
"message": "Command doesn't exist",
"details": null,
"path": "/parcel-management/parcel-create-commands/{commandId}",
"userMessage": "Komenda nie istnieje"
}
]
}
The command id exists in the seller account so I can't tell what the problem is.
Can you help me out?
Thank you!

**Comment by MartaNowaczyk** [comment]
Thank you for your report, as soon as we trace the cause of the problem I will let you know.

**Comment by filip-frisbo** [comment]
Hello! Any news about this issue?

**Comment by Lukasz-Zurek** [comment]
@filip-frisbo We have already forwarded this case to another department. Please be patient. I will let you know if I receive additional information about this specific case - as it is not as obvious as we thought it would be.

**Comment by MartaNowaczyk** [comment]
@filip-frisbo The package was created on the 9th of December based on CommandId 4400d796-5e64-4b05-b220-a5a0c429f60f - successfully. It was also queried for its successful creation. The package was sent correctly.
Then, from the 12th of December, our system was queried for CommandId = c61b7750-77b8-11ed-82ce-17091860525a - this ID is the OrderId associated with this package, not the CommandId, hence the error received (such command does not exist).

Translated with www.DeepL.com/Translator (free version)

**Comment by filip-frisbo** [comment]
@MartaNowaczyk thank you for the explanation! I understand that I need to use the parcelId to retrieve the label.
![image](https://user-images.githubusercontent.com/103931881/210824821-fc033993-1035-4b81-9705-85ced7a32e7d.png)
However what route can I use to get the parcel command Id as it's missing when retrieving the order.
![image](https://user-images.githubusercontent.com/103931881/210824958-5a53066c-99c6-4be8-84ec-2cb5d2f9d1cf.png)
Much appreciated!

**Comment by PrzemyslawLukanowski** [comment]
Hello, yes, to retrieve label you should use [GET /parcel-management/parcels/label](https://developer.allegro.pl/documentation/#operation/getParcelLabel) with "parcelId" as a query parameter. You can find more information in [our guide](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-create-a-label-for-parcel). If you see this page in Polish, change the language settings by clicking on the icon in the top-right corner and open the page once again.
The command ID is used only for creating parcels via Ship With Allegro within PUT and GET /parcel-management/parcel-create-commands/{commandId}, it is not returned in the order details.

**Comment by filip-frisbo** [comment]
@PrzemyslawLukanowski the issue here is that I do not know the id that the parcel was created with. This action is done by the seller before I query the allegro API. So I need to retrieve somehow this parcel command id (e.g. 4400d796-...) to further retrieve the parcelId using GET /parcel-management/parcel-create-commands/{commandId}.

So my question is where can I find this ID after the parcel was created, such that I can further retrieve the label PDF.

**Comment by PrzemyslawLukanowski** [comment]
This value is stored only within the mentioned endpoint, we return it in the response to the [PUT](https://developer.allegro.pl/documentation/#operation/createNewParcel) method, and there is no other place it can be retrieved.
