### ISSUE TITLE
[restApi] chwilowe zawieszenie aukcji

### ISSUE THREAD

**Issue by arhimano** [allegro/allegro-api#649]
Witam.
Czy jest możliwe chwilowe zawieszenie/wyłączenie aukcji? Np stan produktu spada do zera, wyłączamy aukcję, ale po kilku dniach chcemy ją aktywować ponownie.
Nie znaleźliśmy żadnych metod w API służących do tego...

**Comment by imper86** [comment]
@arhimano to chyba słabo szukaliście ;) zasób /sale/offer-publication-commands

**Comment by imper86** [comment]
@arhimano tak, dokładnie :) taki protip - przy wznowieniu może się okazać konieczne uzupełnienie brakujących parametrów, lub edycja stanu magazynowego (aukcje które zakończyły się same, bo się skończyła dostępna ilość przedmiotów nie wznowią się, bo mają zapisany zerowy stan mag.) - to można sobie ogarnąć metodą PUT w zasobie /sale/offer

**Comment by MartaNowaczyk** [comment]
@arhimano tak, to ta sam oferta, dlatego po 365 dniach jeśli w ofercie nie było sprzedaży naliczymy opłatę 10gr/10dni
