### ISSUE TITLE
Problem ze sprawdzeniem statusu paczki (Allegro One Box)

### ISSUE THREAD

**Issue by oskarguz** [allegro/allegro-api#6490]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam, 
utworzyłem paczkę dla commandId = 6cd05184-6341-4611-b1da-5667d5dc7876
ale przy próbie sprawdzenia statusu paczki otrzymuje taki błąd:

```
{
    "id": "6cd05184-6341-4611-b1da-5667d5dc7876",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Internal system error",
            "details": null,
            "path": null,
            "userMessage": "Wewnętrzny błąd systemu"
        }
    ]
}
```

jest to środowisko testowe natomiast paczka wysyłana jest przez Allegro One Box

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
@oskarguz Nie przekazujesz w ogóle sekcji "dimensions" z wymiarami paczki, stąd zaistniały błąd.

**Comment by oskarguz** [comment]
Rzeczywiscie, dzieki bardzo
