### ISSUE TITLE
Bug w Allegro - nieprawidłowe dane Pickup Point

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#6492]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

Dzień dobry,

w Waszym systemie dane punktu odbioru o id "AL002KWI" są nieprawidłowe, i przez to przy próbie zrobienia paczki Allegro ONE występuje błąd "Receiver city is incorrect". Dzieje się tak dlatego, że zamiast nazwy miejscowości, jest powtórzona ulica. Już kolejny raz musiałem ręcznie w bazie danych poprawiać checkout form wysyłany od Was.

Nieprawidłowe dane "pickupPoint" które umieszczacie w danych Checkout Form:

"pickupPoint": {
"id": "AL002KWI",
"name": "Allegro One Box, zielony automat",
"address": {
  "city": "Ochmanów 105",
  "street": "Ochmanów 105",
  "zipCode": "32-003"
}

Powinno być:

"pickupPoint": {
"id": "AL002KWI",
"name": "Allegro One Box, zielony automat",
"address": {
  "city": "Podłęże",
  "street": "Ochmanów 105",
  "zipCode": "32-003"
}

Proszę o poprawienie danych w Waszej bazie.

**Comment by tztztztz** [comment]
To jest problem z API, wysyłacie złe dane które później sami odrzucacie. Po drugie dlaczego ja mam pisać tą prośbę - sami nie możecie tego załatwić?

**Comment by MartaNowaczyk** [comment]
Jeśli twierdzisz, że to dane w naszej bazie to ogólny problem allegro i zgłoszenie powinno iść przez formularz, jeśli jest problem z danymi zamówienia możemy je sprawdzić tutaj, tylko podaj numer zamówienia jakiego to dotyczy.

**Comment by tztztztz** [comment]
Nie rozumiesz, więc jeszcze raz, łopatologicznie:

Macie w swojej bazie danych punktów odbioru źle wprowadzone dane punktu odbioru o id AL002KWI.

Musi jakiś programista  wejść do waszej bazy danych i poprawić w niej te dane, bo za każdym razem kiedy klient Allegro wybiera ten punkt odbioru wysyłacie przez API złe dane po czym nie da się przez API stworzyć paczki allegro ONE.

Poprawienie zamówienia nic nie da, ponieważ musiałbym przy każdym zamówieniu za każdym razem wysyłać prośbę co jest kompletnie bez sensu. Proszę poprawić dane punktu w swojej bazie danych?

Czy czegoś jeszcze tutaj nie rozumiesz? Jeżeli nie rozumiesz to proszę o przekazanie tego zgłoszenia komuś innemu. Dziękuję.

**Comment by MartaNowaczyk** [comment]
Nie wiem skąd taki niemiły ton. Nikt nie napisał, że będziemy poprawiać zamówienie. Numer zamówienia był mi potrzebny jako przykład do zweryfikowania przez odpowiedni zespół. Można też podać trace-id z błędem przy tworzeniu paczki. W tym wypadku jeśli dane punktu są niepoprawne już na etapie zamówienia zgłoszenie powinno iść przez formularz według naszych zasad, jednak poprosiłam o zamówienie by to przeprocesować.

**Comment by tztztztz** [comment]
Id checkout form:

1d429251-7a5e-11ed-9c79-898e4301a310

**Comment by MartaNowaczyk** [comment]
Dziękuję, zgłoszę to do odpowiedniego zespołu. Wrócę z informacją.

**Comment by PrzemyslawLukanowski** [comment]
Zmieniliśmy dane tego punktu w naszej bazie.

**Comment by tztztztz** [comment]
Dziękuję, zamykam.
