### ISSUE TITLE
Nie działa składanie zamówień na środowisku sandbox

### ISSUE THREAD

**Issue by LukaszWypych** [allegro/allegro-api#6493]
Dzień dobry,
Przy próbie wyboru metody dostawy podczas składania zamówienia wyskakuje błąd "An error has occurred".

W konsoli widać, że błąd jest podczas requestu na adres https://edge.allegro.pl.allegrosandbox.pl/purchases/68ac3100-7d34-11ed-8837-89611310c4bf. Zwracany jest kod 400 z body "{"errors":[{"code":"BAD_REQUEST","message":"An error has occurred","details":null,"path":null,"userMessage":"An error has occurred"}]}"

**Comment by MartaNowaczyk** [comment]
Przed chwilą zrobiłam kilka zamówień na sandbox w różnych scenariuszach i nie napotkałam takiego problemu. Czy problem nadal występuje?

**Comment by LukaszWypych** [comment]
Problemem okazała się być cena. Próbowałem kupić 4 sztuki przedmiotu wystawione do 500tys do dawało razem 2 miliony. Gdy spróbowałem z przedmiotem wystawionym za 20zł wszystko zadziałało

**Comment by LukaszWypych** [comment]
Chyba że się mylę i powodem jest coś innego. Błąd występował na tej aukcji https://allegro.pl.allegrosandbox.pl/oferta/bluza-testowa-7697952996

**Comment by PrzemyslawLukanowski** [comment]
Czy ten problem nadal występuje? Jeśli Twoje zakupy przekroczą 1mln złotych, zwrócimy w takiej sytuacji błąd. W przypadku niższych kwot, problem nie powinien występować.
