### ISSUE TITLE
Aktywacja konta testowego [sandbox]

### ISSUE THREAD

**Issue by oskarguz** [allegro/allegro-api#6494]
Witam,

Czy istnieje sposób aby aktywować konto testowe na sandboxie bez weryfikacji bankowej itp
nizej moje konto:
![Screenshot_1](https://user-images.githubusercontent.com/33939150/208118040-a883c549-812e-4fa2-b5a7-5761a012dfca.png)

**Comment by MartaNowaczyk** [comment]
Na środowisku sandbox są symulatory płatności, więc nie musisz robić realnych przelewów by się zweryfikować.

**Comment by oskarguz** [comment]
Albo czegoś nie rozumiem albo nie działa, przeklikalem weryfikacje konta firmowego, ale stanęło na potwierdzeniu konta bankowego

![image](https://user-images.githubusercontent.com/33939150/208121877-49845b99-844f-4843-92ef-5533e4692502.png)

**Comment by oskarguz** [comment]
Tu moze nie napisalem, chodzi mi o aktywacje konta sprzedawcy na sandboxie :)

**Comment by MartaNowaczyk** [comment]
Tak, wiem, że na sandboxie :) Przeprocesowałam aktywację, konto widzę jako zweryfikowane, ale zerknij proszę jeszcze od swojej strony.

**Comment by oskarguz** [comment]
Dzięki ślicznie, wszystko zdaje sie działać
