### ISSUE TITLE
Brak marki produktu na liście

### ISSUE THREAD

**Issue by diamedica-pl** [allegro/allegro-api#6497]
Dzień dobry,
Nie mogę wystawić produktu z platformy IdoSell, ponieważ mam komunikat, że należy podać markę produktu. Produkt, który chcę wystawić posiada markę HEE, której nie ma na liście. Jak wystawić zatem ten produkt?
Oferty nie jestem w stanie też przypisać do produktyzacji, ponieważ nie ma go jeszcze na Allegro. 
Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Skontaktuj się proszę z IdoSell. Nie wiemy jak dokładnie działa wspomniane narzędzie i jakie możliwości oferuje. Co do zasady powinieneś mieć możliwość zdefiniowania nowej marki (takiej, której nie ma na liście) i przekazania jej podczas wystawiania oferty.
