### ISSUE TITLE
Nadpisywanie parametrów

### ISSUE THREAD

**Issue by AdrianeZ** [allegro/allegro-api#6498]
Czy jest możliwość wystawiania ofert z produktem przez zasób POST /sale/product-offers w requescie podając id produktu z którym chcę powiązać ofertę i jednocześnie nadpisać jakiś parametr który opisuje ten produkt który będzie widoczny tylko w ofercie, nie zmieniając parametru samego produktu?

**Comment by AureliuszBrussy** [comment]
Nadpisywanie parametrów opisującego produkt nie jest możliwe - parametry w ofercie muszą być zgodne z parametrami w wybranym produkcie. Request taki zakończy się błędem informującym o niezgodności parametrów.
