### ISSUE TITLE
request for cooperation

### ISSUE THREAD

**Issue by OlgaNokautPL** [allegro/allegro-api#6499]
Hello and welcome,

My name is Olga Krasodomska and I represent the Sales Intelligence advertising agency, the owner of the Nokaut.pl brand - a price comparison website operating on the Polish market. In addition to the price comparison engine, we have about 300 partners, including Google and Facebook.

Wanting to expand the cooperation already established between us, I would like to ask if Allegro has an affiliate program - where partners are paid for redirections?
Are there any integration options? For example, using a plug-in / application that Allegro stores also list their products with us in the comparison engine?
How would the product feed be obtained for us to be implemented in the comparison engine? We know how to integrate offers from XML.
And if the above issues are possible, how would the CPC or CPS settlement between us look like?

I will be grateful for a reply back.

With best regards, 
Olga Krasodomska

**Comment by AureliuszBrussy** [comment]
We do not provide any affiliate program endpoints within the Allegro public API. 

Please use the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) if you want to know more.

**Comment by OlgaNokautPL** [comment]
Hello, 
Thank you for your answer.
