### ISSUE TITLE
Unprocessable Entity

### ISSUE THREAD

**Issue by adampajak** [allegro/allegro-api#650]
Dlaczego otrzymuję taki komunikat, skoro tuż przed wywołaniem tworzenia wielowariantu, sprawdziłem metodą "/sale/offer-publication-commands/{commandId}/tasks" że wszystkie oferty są wystawione (status SUCCESS) ?

Unprocessable Entity{"errors":[{"code":"VALIDATION_ERROR","message":"Offers: 6205635137, 6205635134, 6205635133, 6205635136, 6205635135, 6205635132, 6205635131 are not found.","details":null,"path":null,"userMessage":"Offers: 6205635137, 6205635134, 6205635133, 6205635136, 6205635135, 6205635132, 6205635131 are not found."}]}

**Comment by MartaNowaczyk** [comment]
Podeślij proszę wszystkie curle dotyczące problemu do weryfikacji.

**Comment by adampajak** [comment]
Nie jestem w stanie ich przygotować bo serwery zwracają Internal Server Error już przy wystawianiu draftu.

**Comment by MartaNowaczyk** [comment]
To oferty z sandboxa czy z produkcji? Skoro dostajesz taki komunikat, to jakiś request chyba wysyłasz. Możesz go podesłać?

**Comment by adampajak** [comment]
Sprawdzam na sandbox. Sekwencja jest taka:

`curl -X POST \
  https://api.allegro.pl.allegrosandbox.pl/sale/offers \
  -H 'Accept: application/vnd.allegro.beta.v1+json' \
  -H 'Api-Key: apikey' \
  -H 'Content-Type: application/vnd.allegro.beta.v1+json' \
  -H 'Postman-Token: 131935c3-ae47-4e2d-ac86-ab97f43d0da6' \
  -H 'cache-control: no-cache' \
  -d '{
  "name": "Muszkieterki na obcasie szare B34H-HB GREY",
  "category": {
    "id": "5540"
  },
  "payments": {
    "invoice": "VAT"
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "209.99",
      "currency": "PLN"
    }
  },
  "publication": {
    "duration": null,
    "status": "INACTIVE"
  },
  "stock": {
    "available": 999,
    "unit": "UNIT"
  },
  "delivery": {
    "shippingRates": {
      "id": "ddcf0f7a-7057-4c48-9796-bd5c850dac12"
    },
    "handlingTime": "P2D"
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>www</p>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://0.allegroimg.allegrosandbox.pl/original/11a8b0/0b32913b4e4980aae4866839ca00"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://8.allegroimg.allegrosandbox.pl/original/11b6c8/d06df1d24337b4622a7d996a9288"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://e.allegroimg.allegrosandbox.pl/original/11713a/7d9303e94b4cab5d5290cfd53c5e"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://7.allegroimg.allegrosandbox.pl/original/114673/ccfa97ea4e0bb30191b15b7e7107"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://4.allegroimg.allegrosandbox.pl/original/1166dc/b3ec16eb4739ab8550b43def6fc4"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://5.allegroimg.allegrosandbox.pl/original/11aef0/38a065864af7b23a048b253c7955"
          }
        ]
      }
    ]
  },
  "location": {
    "countryCode": "PL",
    "province": "ZACHODNIOPOMORSKIE",
    "city": "Szczecin",
    "postCode": "71-447"
  },
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ]
    },
    {
      "id": "7108",
      "valuesIds": [
        "7108_160"
      ]
    },
    {
      "id": "64",
      "valuesIds": [
        "64_5"
      ]
    },
    {
      "id": "22728",
      "valuesIds": [
        "22728_215173"
      ]
    },
    {
      "id": "451",
      "valuesIds": [
        "451_1"
      ]
    },
    {
      "id": "18694",
      "valuesIds": [
        "18694_5"
      ]
    },
    {
      "id": "5588",
      "valuesIds": [
        "5588_1"
      ]
    },
    {
      "id": "203085",
      "valuesIds": [
        "203085_1"
      ]
    },
    {
      "id": "128188",
      "valuesIds": [
        "128188_2"
      ]
    },
    {
      "id": "26388",
      "valuesIds": [
        "26388_256"
      ]
    },
    {
      "id": "68",
      "values": [
        "12"
      ]
    }
  ],
  "images": [
    {
      "url": "https://0.allegroimg.allegrosandbox.pl/original/11a8b0/0b32913b4e4980aae4866839ca00"
    },
    {
      "url": "https://8.allegroimg.allegrosandbox.pl/original/11b6c8/d06df1d24337b4622a7d996a9288"
    },
    {
      "url": "https://e.allegroimg.allegrosandbox.pl/original/11713a/7d9303e94b4cab5d5290cfd53c5e"
    },
    {
      "url": "https://7.allegroimg.allegrosandbox.pl/original/114673/ccfa97ea4e0bb30191b15b7e7107"
    },
    {
      "url": "https://4.allegroimg.allegrosandbox.pl/original/1166dc/b3ec16eb4739ab8550b43def6fc4"
    },
    {
      "url": "https://5.allegroimg.allegrosandbox.pl/original/11aef0/38a065864af7b23a048b253c7955"
    }
  ],
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "4ef7cec0-bce1-41a3-8a83-5265c3ad1277"
    },
    "returnPolicy": {
      "id": "41d333e1-8646-4736-9ccd-6eca2d80f67f"
    },
    "warranty": {
      "id": "5c724aa0-ecc6-4f9c-b170-4412e4e3956d"
    }
  },
  "validation": null,
  "createdAt": null,
  "updatedAt": null
}'

curl -X POST \
  https://api.allegro.pl.allegrosandbox.pl/sale/offers \
  -H 'Accept: application/vnd.allegro.beta.v1+json' \
  -H 'Api-Key: apikey' \
  -H 'Content-Type: application/vnd.allegro.beta.v1+json' \
  -H 'Postman-Token: 362bb4ca-01a6-473f-a050-d242ccfb4b4f' \
  -H 'cache-control: no-cache' \
  -d '{
  "name": "Muszkieterki na obcasie szare B34H-HB GREY",
  "category": {
    "id": "5540"
  },
  "payments": {
    "invoice": "VAT"
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "209.99",
      "currency": "PLN"
    }
  },
  "publication": {
    "duration": null,
    "status": "INACTIVE"
  },
  "stock": {
    "available": 999,
    "unit": "UNIT"
  },
  "delivery": {
    "shippingRates": {
      "id": "ddcf0f7a-7057-4c48-9796-bd5c850dac12"
    },
    "handlingTime": "P2D"
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>www</p>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://0.allegroimg.allegrosandbox.pl/original/11a8b0/0b32913b4e4980aae4866839ca00"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://8.allegroimg.allegrosandbox.pl/original/11b6c8/d06df1d24337b4622a7d996a9288"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://e.allegroimg.allegrosandbox.pl/original/11713a/7d9303e94b4cab5d5290cfd53c5e"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://7.allegroimg.allegrosandbox.pl/original/114673/ccfa97ea4e0bb30191b15b7e7107"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://4.allegroimg.allegrosandbox.pl/original/1166dc/b3ec16eb4739ab8550b43def6fc4"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://5.allegroimg.allegrosandbox.pl/original/11aef0/38a065864af7b23a048b253c7955"
          }
        ]
      }
    ]
  },
  "location": {
    "countryCode": "PL",
    "province": "ZACHODNIOPOMORSKIE",
    "city": "Szczecin",
    "postCode": "71-447"
  },
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ]
    },
    {
      "id": "7108",
      "valuesIds": [
        "7108_160"
      ]
    },
    {
      "id": "64",
      "valuesIds": [
        "64_5"
      ]
    },
    {
      "id": "22728",
      "valuesIds": [
        "22728_215173"
      ]
    },
    {
      "id": "451",
      "valuesIds": [
        "451_1"
      ]
    },
    {
      "id": "18694",
      "valuesIds": [
        "18694_5"
      ]
    },
    {
      "id": "5588",
      "valuesIds": [
        "5588_1"
      ]
    },
    {
      "id": "203085",
      "valuesIds": [
        "203085_1"
      ]
    },
    {
      "id": "128188",
      "valuesIds": [
        "128188_2"
      ]
    },
    {
      "id": "26388",
      "valuesIds": [
        "26388_1024"
      ]
    },
    {
      "id": "68",
      "values": [
        "12"
      ]
    }
  ],
  "images": [
    {
      "url": "https://0.allegroimg.allegrosandbox.pl/original/11a8b0/0b32913b4e4980aae4866839ca00"
    },
    {
      "url": "https://8.allegroimg.allegrosandbox.pl/original/11b6c8/d06df1d24337b4622a7d996a9288"
    },
    {
      "url": "https://e.allegroimg.allegrosandbox.pl/original/11713a/7d9303e94b4cab5d5290cfd53c5e"
    },
    {
      "url": "https://7.allegroimg.allegrosandbox.pl/original/114673/ccfa97ea4e0bb30191b15b7e7107"
    },
    {
      "url": "https://4.allegroimg.allegrosandbox.pl/original/1166dc/b3ec16eb4739ab8550b43def6fc4"
    },
    {
      "url": "https://5.allegroimg.allegrosandbox.pl/original/11aef0/38a065864af7b23a048b253c7955"
    }
  ],
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "4ef7cec0-bce1-41a3-8a83-5265c3ad1277"
    },
    "returnPolicy": {
      "id": "41d333e1-8646-4736-9ccd-6eca2d80f67f"
    },
    "warranty": {
      "id": "5c724aa0-ecc6-4f9c-b170-4412e4e3956d"
    }
  },
  "validation": null,
  "createdAt": null,
  "updatedAt": null
}'

curl -X POST \
  https://api.allegro.pl.allegrosandbox.pl/sale/offers \
  -H 'Accept: application/vnd.allegro.beta.v1+json' \
  -H 'Api-Key: apikey' \
  -H 'Content-Type: application/vnd.allegro.beta.v1+json' \
  -H 'Postman-Token: 098d1bbc-9321-4d54-86e5-abb9aca4a29c' \
  -H 'cache-control: no-cache' \
  -d '{
  "name": "Muszkieterki na obcasie szare B34H-HB GREY",
  "category": {
    "id": "5540"
  },
  "payments": {
    "invoice": "VAT"
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "209.99",
      "currency": "PLN"
    }
  },
  "publication": {
    "duration": null,
    "status": "INACTIVE"
  },
  "stock": {
    "available": 999,
    "unit": "UNIT"
  },
  "delivery": {
    "shippingRates": {
      "id": "ddcf0f7a-7057-4c48-9796-bd5c850dac12"
    },
    "handlingTime": "P2D"
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>www</p>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://0.allegroimg.allegrosandbox.pl/original/11a8b0/0b32913b4e4980aae4866839ca00"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://8.allegroimg.allegrosandbox.pl/original/11b6c8/d06df1d24337b4622a7d996a9288"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://e.allegroimg.allegrosandbox.pl/original/11713a/7d9303e94b4cab5d5290cfd53c5e"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://7.allegroimg.allegrosandbox.pl/original/114673/ccfa97ea4e0bb30191b15b7e7107"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://4.allegroimg.allegrosandbox.pl/original/1166dc/b3ec16eb4739ab8550b43def6fc4"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://5.allegroimg.allegrosandbox.pl/original/11aef0/38a065864af7b23a048b253c7955"
          }
        ]
      }
    ]
  },
  "location": {
    "countryCode": "PL",
    "province": "ZACHODNIOPOMORSKIE",
    "city": "Szczecin",
    "postCode": "71-447"
  },
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ]
    },
    {
      "id": "7108",
      "valuesIds": [
        "7108_160"
      ]
    },
    {
      "id": "64",
      "valuesIds": [
        "64_5"
      ]
    },
    {
      "id": "22728",
      "valuesIds": [
        "22728_215173"
      ]
    },
    {
      "id": "451",
      "valuesIds": [
        "451_1"
      ]
    },
    {
      "id": "18694",
      "valuesIds": [
        "18694_5"
      ]
    },
    {
      "id": "5588",
      "valuesIds": [
        "5588_1"
      ]
    },
    {
      "id": "203085",
      "valuesIds": [
        "203085_1"
      ]
    },
    {
      "id": "128188",
      "valuesIds": [
        "128188_2"
      ]
    },
    {
      "id": "26388",
      "valuesIds": [
        "26388_4096"
      ]
    },
    {
      "id": "68",
      "values": [
        "12"
      ]
    }
  ],
  "images": [
    {
      "url": "https://0.allegroimg.allegrosandbox.pl/original/11a8b0/0b32913b4e4980aae4866839ca00"
    },
    {
      "url": "https://8.allegroimg.allegrosandbox.pl/original/11b6c8/d06df1d24337b4622a7d996a9288"
    },
    {
      "url": "https://e.allegroimg.allegrosandbox.pl/original/11713a/7d9303e94b4cab5d5290cfd53c5e"
    },
    {
      "url": "https://7.allegroimg.allegrosandbox.pl/original/114673/ccfa97ea4e0bb30191b15b7e7107"
    },
    {
      "url": "https://4.allegroimg.allegrosandbox.pl/original/1166dc/b3ec16eb4739ab8550b43def6fc4"
    },
    {
      "url": "https://5.allegroimg.allegrosandbox.pl/original/11aef0/38a065864af7b23a048b253c7955"
    }
  ],
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "4ef7cec0-bce1-41a3-8a83-5265c3ad1277"
    },
    "returnPolicy": {
      "id": "41d333e1-8646-4736-9ccd-6eca2d80f67f"
    },
    "warranty": {
      "id": "5c724aa0-ecc6-4f9c-b170-4412e4e3956d"
    }
  },
  "validation": null,
  "createdAt": null,
  "updatedAt": null
}'

curl -X POST \
  https://api.allegro.pl.allegrosandbox.pl/sale/offers \
  -H 'Accept: application/vnd.allegro.beta.v1+json' \
  -H 'Api-Key: apikey' \
  -H 'Content-Type: application/vnd.allegro.beta.v1+json' \
  -H 'Postman-Token: de250cba-2483-4e0d-8c10-7979c3b29d88' \
  -H 'cache-control: no-cache' \
  -d '{
  "name": "Muszkieterki na obcasie szare B34H-HB GREY",
  "category": {
    "id": "5540"
  },
  "payments": {
    "invoice": "VAT"
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "209.99",
      "currency": "PLN"
    }
  },
  "publication": {
    "duration": null,
    "status": "INACTIVE"
  },
  "stock": {
    "available": 999,
    "unit": "UNIT"
  },
  "delivery": {
    "shippingRates": {
      "id": "ddcf0f7a-7057-4c48-9796-bd5c850dac12"
    },
    "handlingTime": "P2D"
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>www</p>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://0.allegroimg.allegrosandbox.pl/original/11a8b0/0b32913b4e4980aae4866839ca00"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://8.allegroimg.allegrosandbox.pl/original/11b6c8/d06df1d24337b4622a7d996a9288"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://e.allegroimg.allegrosandbox.pl/original/11713a/7d9303e94b4cab5d5290cfd53c5e"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://7.allegroimg.allegrosandbox.pl/original/114673/ccfa97ea4e0bb30191b15b7e7107"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://4.allegroimg.allegrosandbox.pl/original/1166dc/b3ec16eb4739ab8550b43def6fc4"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://5.allegroimg.allegrosandbox.pl/original/11aef0/38a065864af7b23a048b253c7955"
          }
        ]
      }
    ]
  },
  "location": {
    "countryCode": "PL",
    "province": "ZACHODNIOPOMORSKIE",
    "city": "Szczecin",
    "postCode": "71-447"
  },
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ]
    },
    {
      "id": "7108",
      "valuesIds": [
        "7108_160"
      ]
    },
    {
      "id": "64",
      "valuesIds": [
        "64_5"
      ]
    },
    {
      "id": "22728",
      "valuesIds": [
        "22728_215173"
      ]
    },
    {
      "id": "451",
      "valuesIds": [
        "451_1"
      ]
    },
    {
      "id": "18694",
      "valuesIds": [
        "18694_5"
      ]
    },
    {
      "id": "5588",
      "valuesIds": [
        "5588_1"
      ]
    },
    {
      "id": "203085",
      "valuesIds": [
        "203085_1"
      ]
    },
    {
      "id": "128188",
      "valuesIds": [
        "128188_2"
      ]
    },
    {
      "id": "26388",
      "valuesIds": [
        "26388_16384"
      ]
    },
    {
      "id": "68",
      "values": [
        "12"
      ]
    }
  ],
  "images": [
    {
      "url": "https://0.allegroimg.allegrosandbox.pl/original/11a8b0/0b32913b4e4980aae4866839ca00"
    },
    {
      "url": "https://8.allegroimg.allegrosandbox.pl/original/11b6c8/d06df1d24337b4622a7d996a9288"
    },
    {
      "url": "https://e.allegroimg.allegrosandbox.pl/original/11713a/7d9303e94b4cab5d5290cfd53c5e"
    },
    {
      "url": "https://7.allegroimg.allegrosandbox.pl/original/114673/ccfa97ea4e0bb30191b15b7e7107"
    },
    {
      "url": "https://4.allegroimg.allegrosandbox.pl/original/1166dc/b3ec16eb4739ab8550b43def6fc4"
    },
    {
      "url": "https://5.allegroimg.allegrosandbox.pl/original/11aef0/38a065864af7b23a048b253c7955"
    }
  ],
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "4ef7cec0-bce1-41a3-8a83-5265c3ad1277"
    },
    "returnPolicy": {
      "id": "41d333e1-8646-4736-9ccd-6eca2d80f67f"
    },
    "warranty": {
      "id": "5c724aa0-ecc6-4f9c-b170-4412e4e3956d"
    }
  },
  "validation": null,
  "createdAt": null,
  "updatedAt": null
}'

curl -X POST \
  https://api.allegro.pl.allegrosandbox.pl/sale/offers \
  -H 'Accept: application/vnd.allegro.beta.v1+json' \
  -H 'Api-Key: apikey' \
  -H 'Content-Type: application/vnd.allegro.beta.v1+json' \
  -H 'Postman-Token: 19ebd8c2-ccba-4e11-9bf1-fb6bc913b4d7' \
  -H 'cache-control: no-cache' \
  -d '{
  "name": "Muszkieterki na obcasie szare B34H-HB GREY",
  "category": {
    "id": "5540"
  },
  "payments": {
    "invoice": "VAT"
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "209.99",
      "currency": "PLN"
    }
  },
  "publication": {
    "duration": null,
    "status": "INACTIVE"
  },
  "stock": {
    "available": 999,
    "unit": "UNIT"
  },
  "delivery": {
    "shippingRates": {
      "id": "ddcf0f7a-7057-4c48-9796-bd5c850dac12"
    },
    "handlingTime": "P2D"
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>www</p>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://0.allegroimg.allegrosandbox.pl/original/11a8b0/0b32913b4e4980aae4866839ca00"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://8.allegroimg.allegrosandbox.pl/original/11b6c8/d06df1d24337b4622a7d996a9288"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://e.allegroimg.allegrosandbox.pl/original/11713a/7d9303e94b4cab5d5290cfd53c5e"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://7.allegroimg.allegrosandbox.pl/original/114673/ccfa97ea4e0bb30191b15b7e7107"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://4.allegroimg.allegrosandbox.pl/original/1166dc/b3ec16eb4739ab8550b43def6fc4"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://5.allegroimg.allegrosandbox.pl/original/11aef0/38a065864af7b23a048b253c7955"
          }
        ]
      }
    ]
  },
  "location": {
    "countryCode": "PL",
    "province": "ZACHODNIOPOMORSKIE",
    "city": "Szczecin",
    "postCode": "71-447"
  },
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ]
    },
    {
      "id": "7108",
      "valuesIds": [
        "7108_160"
      ]
    },
    {
      "id": "64",
      "valuesIds": [
        "64_5"
      ]
    },
    {
      "id": "22728",
      "valuesIds": [
        "22728_215173"
      ]
    },
    {
      "id": "451",
      "valuesIds": [
        "451_1"
      ]
    },
    {
      "id": "18694",
      "valuesIds": [
        "18694_5"
      ]
    },
    {
      "id": "5588",
      "valuesIds": [
        "5588_1"
      ]
    },
    {
      "id": "203085",
      "valuesIds": [
        "203085_1"
      ]
    },
    {
      "id": "128188",
      "valuesIds": [
        "128188_2"
      ]
    },
    {
      "id": "26388",
      "valuesIds": [
        "26388_65536"
      ]
    },
    {
      "id": "68",
      "values": [
        "12"
      ]
    }
  ],
  "images": [
    {
      "url": "https://0.allegroimg.allegrosandbox.pl/original/11a8b0/0b32913b4e4980aae4866839ca00"
    },
    {
      "url": "https://8.allegroimg.allegrosandbox.pl/original/11b6c8/d06df1d24337b4622a7d996a9288"
    },
    {
      "url": "https://e.allegroimg.allegrosandbox.pl/original/11713a/7d9303e94b4cab5d5290cfd53c5e"
    },
    {
      "url": "https://7.allegroimg.allegrosandbox.pl/original/114673/ccfa97ea4e0bb30191b15b7e7107"
    },
    {
      "url": "https://4.allegroimg.allegrosandbox.pl/original/1166dc/b3ec16eb4739ab8550b43def6fc4"
    },
    {
      "url": "https://5.allegroimg.allegrosandbox.pl/original/11aef0/38a065864af7b23a048b253c7955"
    }
  ],
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "4ef7cec0-bce1-41a3-8a83-5265c3ad1277"
    },
    "returnPolicy": {
      "id": "41d333e1-8646-4736-9ccd-6eca2d80f67f"
    },
    "warranty": {
      "id": "5c724aa0-ecc6-4f9c-b170-4412e4e3956d"
    }
  },
  "validation": null,
  "createdAt": null,
  "updatedAt": null
}'

curl -X POST \
  https://api.allegro.pl.allegrosandbox.pl/sale/offers \
  -H 'Accept: application/vnd.allegro.beta.v1+json' \
  -H 'Api-Key: apikey' \
  -H 'Content-Type: application/vnd.allegro.beta.v1+json' \
  -H 'Postman-Token: 22b6a09c-fc39-41b3-b63e-f5010d91d2d3' \
  -H 'cache-control: no-cache' \
  -d '{
  "name": "Muszkieterki na obcasie szare B34H-HB GREY",
  "category": {
    "id": "5540"
  },
  "payments": {
    "invoice": "VAT"
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "209.99",
      "currency": "PLN"
    }
  },
  "publication": {
    "duration": null,
    "status": "INACTIVE"
  },
  "stock": {
    "available": 999,
    "unit": "UNIT"
  },
  "delivery": {
    "shippingRates": {
      "id": "ddcf0f7a-7057-4c48-9796-bd5c850dac12"
    },
    "handlingTime": "P2D"
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>www</p>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://0.allegroimg.allegrosandbox.pl/original/11a8b0/0b32913b4e4980aae4866839ca00"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://8.allegroimg.allegrosandbox.pl/original/11b6c8/d06df1d24337b4622a7d996a9288"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://e.allegroimg.allegrosandbox.pl/original/11713a/7d9303e94b4cab5d5290cfd53c5e"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://7.allegroimg.allegrosandbox.pl/original/114673/ccfa97ea4e0bb30191b15b7e7107"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://4.allegroimg.allegrosandbox.pl/original/1166dc/b3ec16eb4739ab8550b43def6fc4"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://5.allegroimg.allegrosandbox.pl/original/11aef0/38a065864af7b23a048b253c7955"
          }
        ]
      }
    ]
  },
  "location": {
    "countryCode": "PL",
    "province": "ZACHODNIOPOMORSKIE",
    "city": "Szczecin",
    "postCode": "71-447"
  },
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ]
    },
    {
      "id": "7108",
      "valuesIds": [
        "7108_160"
      ]
    },
    {
      "id": "64",
      "valuesIds": [
        "64_5"
      ]
    },
    {
      "id": "22728",
      "valuesIds": [
        "22728_215173"
      ]
    },
    {
      "id": "451",
      "valuesIds": [
        "451_1"
      ]
    },
    {
      "id": "18694",
      "valuesIds": [
        "18694_5"
      ]
    },
    {
      "id": "5588",
      "valuesIds": [
        "5588_1"
      ]
    },
    {
      "id": "203085",
      "valuesIds": [
        "203085_1"
      ]
    },
    {
      "id": "128188",
      "valuesIds": [
        "128188_2"
      ]
    },
    {
      "id": "26388",
      "valuesIds": [
        "26388_262144"
      ]
    },
    {
      "id": "68",
      "values": [
        "12"
      ]
    }
  ],
  "images": [
    {
      "url": "https://0.allegroimg.allegrosandbox.pl/original/11a8b0/0b32913b4e4980aae4866839ca00"
    },
    {
      "url": "https://8.allegroimg.allegrosandbox.pl/original/11b6c8/d06df1d24337b4622a7d996a9288"
    },
    {
      "url": "https://e.allegroimg.allegrosandbox.pl/original/11713a/7d9303e94b4cab5d5290cfd53c5e"
    },
    {
      "url": "https://7.allegroimg.allegrosandbox.pl/original/114673/ccfa97ea4e0bb30191b15b7e7107"
    },
    {
      "url": "https://4.allegroimg.allegrosandbox.pl/original/1166dc/b3ec16eb4739ab8550b43def6fc4"
    },
    {
      "url": "https://5.allegroimg.allegrosandbox.pl/original/11aef0/38a065864af7b23a048b253c7955"
    }
  ],
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "4ef7cec0-bce1-41a3-8a83-5265c3ad1277"
    },
    "returnPolicy": {
      "id": "41d333e1-8646-4736-9ccd-6eca2d80f67f"
    },
    "warranty": {
      "id": "5c724aa0-ecc6-4f9c-b170-4412e4e3956d"
    }
  },
  "validation": null,
  "createdAt": null,
  "updatedAt": null
}'

curl -X PUT \
  https://api.allegro.pl.allegrosandbox.pl/sale/offer-publication-commands/d5b5ded4-b962-4302-bda9-ad334acf0134 \
  -H 'Accept: application/vnd.allegro.beta.v1+json' \
  -H 'Api-Key: apikey' \
  -H 'Content-Type: application/vnd.allegro.beta.v1+json' \
  -H 'Postman-Token: 7277e960-84a6-4873-9750-9de88c697d0d' \
  -H 'cache-control: no-cache' \
  -d '{
  "publication": {
    "action": "ACTIVATE"
  },
  "offerCriteria": [
    {
      "offers": [
        {
          "id": "6205659972"
        },
        {
          "id": "6205659973"
        },
        {
          "id": "6205659974"
        },
        {
          "id": "6205659975"
        },
        {
          "id": "6205659976"
        },
        {
          "id": "6205659977"
        }
      ],
      "type": "CONTAINS_OFFERS"
    }
  ]
}'

curl -X PUT \
  https://api.allegro.pl.allegrosandbox.pl/sale/offer-variants/jakis_guid \
  -H 'Accept: application/vnd.allegro.beta.v1+json' \
  -H 'Content-Type: application/vnd.allegro.beta.v1+json' \
  -H 'Postman-Token: ac83fd6e-9581-4a86-be39-7f5a34dc1b0c' \
  -H 'cache-control: no-cache' \
  -d '{
  "offers": [
    {
      "id": "6205659972"
    },
    {
      "id": "6205659973"
    },
    {
      "id": "6205659974"
    },
    {
      "id": "6205659975"
    },
    {
      "id": "6205659976"
    },
    {
      "id": "6205659977"
    }
  ],
  "name": "Muszkieterki na obcasie szare B34H-HB GREY",
  "parameters": [
    {
      "id": "26388"
    }
  ]
}'

`

**Comment by MartaNowaczyk** [comment]
Jak tylko sprawdzę ten przypadek dam znać.

**Comment by MartaNowaczyk** [comment]
Testowałam to na wiele sposobów i nie dostaję takiego błędu jak piszesz w pierwszym poście. Moje oferty za każdym razem zyskały powiązanie i oferta wielowariantowa została utworzona. 
Przy tym ostatnim zapytaniu dostajesz taki sam błąd? Podeślij proszę trace-id z nagłówka do sprawdzenia.

**Comment by adampajak** [comment]
Dostaję to przy ostatnim zapytaniu czyli na zasobie https://api.allegro.pl.allegrosandbox.pl/sale/offer-variants/4443488e-9e4b-4fa6-806d-b083783fcdbf.
Uruchomiłem teraz i Response.TraceId wynosi: a8205b9aa3b7d6a5

**Comment by MartaNowaczyk** [comment]
Dzięki, przyglądamy się temu. Dam znać jak coś ustalimy.

**Comment by MartaNowaczyk** [comment]
Nie zanotowaliśmy błędu w tym obszarze. Po prostu za szybko wysyłasz kolejne zapytania.  Poczekaj aż wystawianie się przeprocesuje chociaż koło 5 minut. Regulaminowo jest nawet do 1h.
