### ISSUE TITLE
/sale/product-offers 500 - przy pobieraniu zdjęć

### ISSUE THREAD

**Issue by mediablue** [allegro/allegro-api#6500]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Problem z publikacją oferty powiązanej z produktem - 500

trace id:
5673313-e9a18e52-5872-435a-be2c-99b3c9021183

Pomimo zdjęć na serwerze API zwraca 500
```
{
    "errors": [
        {
            "code": "DownloadError.InternalServerError",
            "message": "Downloading image from URL 'url/92152/6393007020cda.jpeg' failed. Server returned the following HTTP status code: 500 INTERNAL_SERVER_ERROR and response body: 'Internal server error'.",
            "details": null,
            "path": "images",
            "userMessage": "Downloading image from URL 'url/92152/6393007020cda.jpeg' failed. Server returned the following HTTP status code: 500 INTERNAL_SERVER_ERROR and response body: 'Internal server error'."
        }
    ]
}
```

**Comment by Maczuga** [comment]
Potwierdzam, u nas to samo.

**Comment by xVinniVx** [comment]
Tu to samo. Proszę o reakcję.

**Comment by AureliuszBrussy** [comment]
Problem nadal występuje? Czy mogę prosić o trace-id konkretnych przykładowych wywołań kończących się tym błędem? Niestety, trace-id z pierwszej wiadomości nie jest poprawne.

**Comment by mediablue** [comment]
trace-id: f3be86f5d0418586

**Comment by AureliuszBrussy** [comment]
Nie obserwujemy problemów z naszą usługą do uploadowania zdjęć. 

@mediablue sprawdziliśmy podany przez Ciebie przykład i tutaj błąd wystąpił po stronie serwera na którym jest zdjęcie. Zdarza się, że nie otrzymujemy całości response'a.

**Comment by mediablue** [comment]
@AureliuszBrussy 

Prośba o ponowną weryfikację (nie jest to pojedynczy przypadek) przy testach wydajnościowych średni czas odpowiedzi dla zdjęcia to 112ms. 
Problem nie leży więc po stronie serwera na którym jest zdjęcie tylko po stronie odbierającej dane.

W mojej ocenie problem dotyczy parametrów odbioru parametrów:
- productSet/product/images
- images

**Comment by AureliuszBrussy** [comment]
@mediablue czy możesz podać do analizy trace-id przykładów z innymi zdjęciami (innymi url zdjęć)?

**Comment by mediablue** [comment]
c6a8baad872abd50
f1606c5c1f1f2a5
8d8bcff60b89b8bd
16f7460d13ef77ad

**Comment by AureliuszBrussy** [comment]
@mediablue dziękuję za kolejne przykłady - przekazałem je do zespołu odpowiedzialnego za zasób, wrócę z informacją.

**Comment by xVinniVx** [comment]
Czy coś w tym temacie zostanie zrobione? Problem nadal występuje.

**Comment by AureliuszBrussy** [comment]
@xVinniVx jeszcze to weryfikujemy. Wrócę z informacją, gdy tylko coś ustalimy.

**Comment by mediablue** [comment]
@AureliuszBrussy 
Kiedy można spodziewać się odpowiedzi?

**Comment by Maczuga** [comment]
Może nie cid'y, ale podaję logi z requestów od waszego "pobieracza" zdjęć. Wszystkie mają status 200. Parametr `?source=allegro` dodałem podczas testów dla łatwiejszego odnalezienia w logach.

Nie jesteśmy w stanie wystawić 99% nowych ofert powiązanych z produktem.

```
178.21.154.35 - - [23/Dec/2022:09:19:19 +0100] "GET /pubs/uploads/09795d9774054eaaa7e2eeb59fd566ad.png?source=allegro HTTP/1.0" 200 291978 "-" "Allegro-ImageDownloader/1.0"
178.21.154.35 - - [23/Dec/2022:09:19:19 +0100] "GET /pubs/uploads/2baba165602e476ebcac9dc081c26d40.png?source=allegro HTTP/1.0" 200 293464 "-" "Allegro-ImageDownloader/1.0"
178.21.154.33 - - [23/Dec/2022:09:19:19 +0100] "GET /pubs/uploads/71ebb5d7484342cf8a9bc2a70f210a1d.jpg?source=allegro HTTP/1.1" 200 76597 "-" "Allegro-ImageDownloader/1.0"
178.21.154.34 - - [23/Dec/2022:09:19:19 +0100] "GET /pubs/uploads/7ff752e0eca24a5487f8ce25c07e308f.png?source=allegro HTTP/1.1" 200 185236 "-" "Allegro-ImageDownloader/1.0"
178.21.154.34 - - [23/Dec/2022:09:19:19 +0100] "GET /pubs/uploads/0c14d9bf4a9c428380028daf68b286d0.png?source=allegro HTTP/1.1" 200 351787 "-" "Allegro-ImageDownloader/1.0"
178.21.154.32 - - [23/Dec/2022:09:19:19 +0100] "GET /pubs/uploads/f646671a95634ecf90cbaea3d72adfa4.png?source=allegro HTTP/1.1" 200 175425 "-" "Allegro-ImageDownloader/1.0"
```

**Comment by xVinniVx** [comment]
To samo - nadal - u mnie. Ja rozumiem, że sałatki trzeba kroić i lepić pierogi - ale biznes nie może czekać.... 
Wstyd, że nie ma żadnej informacji zwrotnej.

**Comment by AureliuszBrussy** [comment]
Wdrożyliśmy poprawkę - problem obecnie już nie powinien występować. Gdyby jednak było inaczej, dajcie znać.

Przepraszam za niedogodności.
