### ISSUE TITLE
cd @6170

### ISSUE THREAD

**Issue by mbcont** [allegro/allegro-api#6501]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

trace-id
c7a9a6a1f7503dd

poprzednie zgłoszenie #6170

**Comment by AureliuszBrussy** [comment]
@mbcont przed chwilą odpowiedzieliśmy na zgłoszenie w wątku #6170.
