### ISSUE TITLE
Brak zamówień zarówno w panelu allegro jak i po REST API

### ISSUE THREAD

**Issue by q3ok** [allegro/allegro-api#6504]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X] inny / other

:beetle: **Opis / Description**
Przychodzą maile z zamówieniami, natomiast nie widać ich ani w panelu allegro, ani po API. Problem występuje od ok. godz. 10:00, wcześniej zamówienia pojawiały się z ok 5-10min opóźnieniem.

**Comment by AureliuszBrussy** [comment]
Potwierdzam opóźnienia w widoczności zamówień - aktualnie pracujemy nad rozwiązaniem problemu.
