### ISSUE TITLE
Zamówienie z One Fulfillment

### ISSUE THREAD

**Issue by LukaszWypych** [allegro/allegro-api#6505]
Dzień dobry,
czy podczas pobierania zamówień istnieje możliwość rozróżnienia, które podchodzi pod One Fulfillment, a które powinien procesować sprzedawca?

**Comment by Lukasz-Zurek** [comment]
Nie, natomiast w [naszym poradniku](https://developer.allegro.pl/tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#jak-obslugiwac-zamowienia) wspomnieliśmy m.in. o tym, że obsługą tego typu zamówień zajmuje się w pełni nasz magazyn, czyli nie musisz tych zamówień w żaden sposób procesować. Na samym początku musisz jednak wiedzieć które [oferty wystawione zostały w usłudze One Fulfillment](https://developer.allegro.pl/tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#jak-wystawic-oferte).

**Comment by LukaszWypych** [comment]
Wiem, że nie muszę ich procesować dlatego chciałem je rozróżnić. Czyli jedynym sposobem na rozróżnienie ich jest zmapowanie oferty wystawionej w One Fulfillment z tą podaną w zamówieniu?

**Comment by LukaszWypych** [comment]
I przy okazji drugie pytanie. Czy możliwe jest testowanie One Fulfillment na sandboxie? Wypełniłem wniosek na stronie z nadzieją, że automatycznie zostanie zaakceptowany, ale chyba się myliłem

**Comment by Lukasz-Zurek** [comment]
@LukaszWypych Tak. Istnieje jeszcze możliwość rejestracji odrębnego [konta One Fulfillment](https://allegro.pl/pomoc/dla-sprzedajacych/one-fulfillment-by-allegro/jak-zaczac-korzystac-z-one-fulfillment-by-allegro-aMDP0d4dYs4) - wówczas wszystkie oferty będą One Fulfillment.

**Comment by Lukasz-Zurek** [comment]
@LukaszWypych Podaj proszę login na sandboxie. Dopytam i wrócę do Ciebie z informacją zwrotną.

**Comment by LukaszWypych** [comment]
login: Verto

**Comment by Lukasz-Zurek** [comment]
@LukaszWypych To konto było już używane do testowania. Aby móc oznaczyć konto jako One Fulfillment - potrzebujemy nowego, "czystego" i zweryfikowanego konta. Takiego, na którym nie była dokonywana jakakolwiek sprzedaż, czy nawet wystawianie ofert.

**Comment by LukaszWypych** [comment]
Czyli jedno konto nie może używać jednocześnie własnego procesowania i One Fulfillment? 

> @LukaszWypych Tak. Istnieje jeszcze możliwość rejestracji odrębnego [konta One Fulfillment](https://allegro.pl/pomoc/dla-sprzedajacych/one-fulfillment-by-allegro/jak-zaczac-korzystac-z-one-fulfillment-by-allegro-aMDP0d4dYs4) - wówczas wszystkie oferty będą One Fulfillment.

To mi sugerowało że jedno konto może obsługiwać oba tryby.

**Comment by Lukasz-Zurek** [comment]
@LukaszWypych Na wstępie - muszę Cię przeprosić za lekkie zamieszanie, które spowodowałem :) 

Pytałeś o rozróżnienie - nie ma takiego - to już wiemy. Błędnie zasugerowałem Tobie, że jedno konto może obsługiwać dwa tryby. Prawda jest taka, że na koncie One Fulfillment można wystawiać tylko oferty fulfillmentowe.

Co do warunków - opisane zostały w [Allegro Pomoc](https://allegro.pl/pomoc/dla-sprzedajacych/one-fulfillment-by-allegro/jak-zaczac-korzystac-z-one-fulfillment-by-allegro-aMDP0d4dYs4). Krótko mówiąc - na produkcji są 3 możliwości założenia/przekształcenia konta na One Fulfillment. Natomiast na sandboxie potrzebujemy nowego konta, by móc je manualnie przeprocesować :)

**Comment by LukaszWypych** [comment]
Nowe konto: verto_oneful.
Prosze o autoryzacje i zmiane na One Fulfillment

**Comment by Lukasz-Zurek** [comment]
@LukaszWypych Konto w pełni aktywne. Przekazałem je dalej w celu weryfikacji firmy i zmiany na One Fulfillment. Wkrótce wrócę z informacją.

**Comment by LukaszWypych** [comment]
Ile może potrwać weryfikacja?

**Comment by AureliuszBrussy** [comment]
@LukaszWypych aktywowałem Twoje konto oraz jest ono już oznaczone jako konto One Fulfillment. Jedna ważna informacja - na Sandboxie możliwości testowania One Fulfillment są ograniczone. Proces zatrzyma się na awizacji towaru (proces "Advance Ship Notices" w [dokumentacji](https://developer.allegro.pl/documentation#tag/Advance-Ship-Notices)) - towar nie zostanie "przyjęty" na magazynie.

**Comment by LukaszWypych** [comment]
Czyli rozumiem, że zatwierdzenie awiza jeszcze powinno zadziałać i status awiza będzie "IN_TRANSIT", ale nigdy nie będzie wpisów w endpoicie getAdvanceShipNoticeReceivingState?

**Comment by AureliuszBrussy** [comment]
Zgadza się, możesz utworzyć oferty z produktami oraz utworzyć awizo dla tych produktów, po zakończeniu uzupełniania awiza proces utknie w statusie IN_TRANSIT.
