### ISSUE TITLE
Zła wartość parametru słownikowego

### ISSUE THREAD

**Issue by arolznov** [allegro/allegro-api#6506]
Przy próbie wystawienia aukcji z produktem występuję błąd
```
 {
            "code":"VALIDATION_ERROR",
            "message":"You can only assign dictionary parameter by valueId for 13288.",
            "details":"ConstraintViolationException.ImproperlyAssignedDictionaryParameter",
            "path":"parameters[5]",
            "userMessage":"Parametr s\u0142ownikowy nale\u017cy uzupe\u0142ni\u0107 poprzez identyfikator warto\u015bci dla 13288."
         },
         {
            "code":"VALIDATION_ERROR",
            "message":"No value was given for parameter (13288)",
            "details":"ConstraintViolationException.NoValueInDictionaryParameter",
            "path":"parameters",
            "userMessage":"Nie podano warto\u015bci dla parametru Marka (13288)."
         },
         {
            "code":"VALIDATION_ERROR",
            "message":"Incorrect value of the Marka (13288) parameter for the offered product. The correct parameter value for the product is: \"Brit\".",
            "details":null,
            "path":"",
            "userMessage":"Niepoprawna warto\u015b\u0107 parametru Marka (13288) dla produktu w ofercie. Prawid\u0142owa warto\u015b\u0107 parametru dla produktu to: \"Brit\"."
         }
```

Dla parametru marka podaję w valuesIds: [ 228217_327757 ] zgodnie z tym co zwracają mi parametry dla produktu o id: 5e9538da-a22c-461b-8024-1055eaf8ce51
```
id: "13288"
name: "Marka"
options: {identifiesProduct: true}
identifiesProduct: true
unit: null
values: null
valuesIds: ["228217_327757"]
0: "228217_327757"
valuesLabels: ["Brit"]
0: "Brit"
```
Jak można zauważyć w valuesIds wartość dotyczy parametru o id 228217 a nie 13288. Jeśli pobiorę parametry dla tej kategorii Allegro (id: 90061) dostaję coś takiego:
```
{
"id": "13288_1092308",
"value": "Brexitaw",
"dependsOnValueIds": []
},
{
"id": "13288_1072977",
"value": "Briantos",
"dependsOnValueIds": []
},
{
"id": "228217_327757",
"value": "Brit",
"dependsOnValueIds": []
},
{
"id": "228217_327565",
"value": "Bros",
"dependsOnValueIds": []
},
{
"id": "13288_1072059",
"value": "Brothercatdog",
"dependsOnValueIds": []
}
```
Część ma poprawny id 13288, a część nie - ma 228217.

Reasumując: sale/products oraz sale/categories/{ID}/parameters zwracają parametry, których nie można użyć przy wstawianiu lub aktualizacji aukcji.

**Comment by Lukasz-Zurek** [comment]
Dziękuję za zgłoszenie. Przekazuję je dalej do weryfikacji. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@arolznov Podaj proszę jeszcze trace-id dla wywołania dotyczącego próby wystawienia oferty.

Dodam, że aktualny parametr marka w dziale "Supermarket" posiada identyfikator: 13288. Odmienne identyfikatory dla wartości wynikają z wcześniejszego połączenia tego parametru z 228217.

**Comment by arolznov** [comment]
@Lukasz-Zurek Przesyłam trace-id: 8da7da594c6b415c

**Comment by Lukasz-Zurek** [comment]
@arolznov Wartość parametru: 13288, czyli: "228217_327757" powinieneś przekazać w polu "valuesIds". Obecnie przekazujesz ją w polu "values", dlatego zwracamy błąd sugerujący skorzystanie z wartości słownikowej "Brit" (którą należy przekazać właśnie w "valuesIds").

**Comment by arolznov** [comment]
Na 100% poprawnie przekazywałem, dziwne bo nie zrobiłem dosłownie nic i zaczęło działać.
