### ISSUE TITLE
Problem z "identifiesProduct" w parametrach produktu

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#6507]
Dzień dobry,

chciałbym się zapytać o pole `identifiesProduct` w parametrach produktu. Z tego co widzę, `describesProduct` zawarte we właściwościach parametru dla danej kategorii nie informuje o tym, jakie parametry identyfikują produkty w poszczególnej kategorii. W takim razie - w jaki sposób mogę się dowiedzieć, jakie parametry w kategorii identyfikują produkt poza sprawdzaniem tego na istniejących już produktach? 

Pozdrawiam.

**Comment by MartaNowaczyk** [comment]
Nie ma takiej możliwości. Tylko w produkcie znajdziesz takie informacje, bo produkty w danej kategorii mogą być różne i mogą mieć różne parametry po których szukamy podobnego produktu.

**Comment by hahyes** [comment]
@MartaNowaczyk Rozumiem, miałem na uwadze, że może to być indywidualnie przypisywana zmienna. Jednakże widzę przykłady, które są dla mnie dziwne i prosiłbym o wyjaśnienie, jak to dokładniej działa.

Przykład: 2ec8d58d-b013-4b0d-856a-ee47d7d681a0

Produkt ten ma dokładnie dwa parametry identyfikujące: Marka oraz Rozmiar. Jak na spodnie to jest to za mało konkretne, mam wrażenie? Wydaje mi się, że spodnie mogą mieć różne modele, wersje, należeć do różnych kolekcji. Nie sprzedaję tego więc nie mam konkretnej wiedzy, ale nawet kolor nie jest tutaj identyfikujący. Rozumiem, że jakiś system moderacji (zapewne ludzkiej) podejmuje decyzje, co jest identyfikujące dla danego produktu. Jednakże dziwi mnie to, że dla spodni o określonym kolorze jedynie marka i rozmiar mają znaczenie. 

Czy tworząc dowolne spodnie tej marki w tej kategorii z tym samym rozmiarem będę skazany na korzystanie z wyżej wymienionego produktu?

**Comment by MartaNowaczyk** [comment]
Jeśli chodzi o identyfikację produktu to nie jest tak, że nie będziesz mógł stworzyć innego produktu z taką samą marką i rozmiarem. Możemy rozróżniać jeszcze np. na podstawie zdjęć tego produktu. To jakie są dokładnie zasady, co jest ustalane w produkcie i jak dobierane są parametry jest poza API, więc tutaj po więcej informacji możesz udać się do [formularza](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
