### ISSUE TITLE
Brak eksportu do sklepu internetowego i Managera paczek

### ISSUE THREAD

**Issue by newlightpl** [allegro/allegro-api#6508]
Występuje problem: 
 - [Poranna sprzedaż, brak mozliwości raportowania do sklepu internetowego i Managera Paczek ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by newlightpl** [comment]
Proszę o pomoc w braku możliwości raportowania transakcji 7c030a70-804b-11ed-8cc6-a719f60084e6

**Comment by MartaNowaczyk** [comment]
Sprawdziłam i nasze API poprawnie zwraca dane dla tego zamówienia. Z tego co widzę przesyłka została już nadana. Jeśli nadal występuje problem z eksportem do sklepu internetowego skontaktuj się proszę z jego obsługą.

**Comment by newlightpl** [comment]
Dzień dobry, przesyłkę nadaliśmy wpisując wszystkie dane "ręcznie" do naszego sklepu. W dalszym ciągu ta konkretna transakcja nie jest "zaciągana" ani przez nasz sklep, ani Managera Paczek Inpost. Inna sprzedaż z tego dnia została poprawnie zaimportowana.
Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Dzień dobry, jak wcześniej pisałam, nie mamy problemu z pobraniem tych danych przez API - sprawdziłam ponownie. Wczoraj mogły pojawić się opóźnienia w pobieraniu zamówień, ale nie powinno mieć to wpływu na możliwość pobrania tych danych. Czy możecie spróbować pobrać to zamówienie jeszcze raz? Najlepiej jest też zgłosić się do twórcy tego narzędzia, by sprawdził czy jest problem od strony technicznej.

**Comment by newlightpl** [comment]
Dzień dobry,
Sprawdzałem wielokrotnie, zarówno nasz sklep oparty na shopgold, jak i MAnager Paczek NIE zaciągają tej jednej konkretnej transakcji, kolejna z tego dnia importuje się do obu w/w prawidłowo. To się musiało stać, kiedy rano mieliście problemy z przekazywaniem danych, otrzymaliśmy powiadomienie o kupnie, którego nie było widać w Panelu sprzedawcy Allegro. Dopiero później pojawiła się płatność i widoczność całego zamówienia, ale TYLKO w panelu Allegro.

**Comment by MartaNowaczyk** [comment]
Dzień dobry, rozumiem i przepraszamy za niedogodności z zamówieniami. Jednak po naszej stronie tak jak pisałam te dane są już dostępne i to narzędzia z których korzystasz powinny odświeżyć, próbować ponownie pobrać dane tego zamówienia. Najlepiej się zgłosić właśnie do nich z taką sytuacją. Nie wiem jak te narzędzia działają, czy ponawiają próbę pobrania danych. W każdym razie z tego miejsca nie jestem w stanie przesłać tych danych do tych narzędzi. To z tych narzędzi musi wyjść zapytanie o to zamówienie. Jeśli ponowią i próba się z jakiegoś powodu nie uda, wtedy powinni do nas przesłać techniczne dane np. zwracane błędy, trace-id w którym uwidoczniony jest problem. Na ten moment nic takiego nie widzę.

**Comment by newlightpl** [comment]
Pani Marto dziękuję za poświęcony czas, choć sprawa już nieaktualna, gdyż jak pisałem, zrealizowaliśmy zamówienie wypełniając dane ręcznie. Problem jaki widzę, jest taki, że ani nasz sklep, ani Manager Paczkomaty NIE widzą tego zamówienia. Dwa niezależne mechanizmy nie są wstanie pobrać tej jednej konkretnej transakcji, co oznacza jakiś problem, który może powtarzać się w przyszłości i prawdopodobnie, nie tylko w naszym przypadku.
Z pozdrowieniami
Paweł Okraska

**Comment by MaciejFrackowiak** [comment]
Z naszej strony możemy tylko odpowiadać za dostępność danych w API Allegro - tak jak wspominała Marta, wskazane zamówienie jest w pełni dostępne w API, a zatem powinno być również w pełni dostępne do pobrania przez aplikacje zewnętrzne.
