### ISSUE TITLE
Problem z wystawieniem produktu w 1 z kategorii (/offer) - You cannot publish offer without a related product in this category

### ISSUE THREAD

**Issue by kofston** [allegro/allegro-api#6509]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

W załączniku na dole tego posta dodaję Państwu pliki odpowiedz.txt (odpowiedz zwrotna) + request_wyslany.txt (to co wysyłam przez Rest.API) + screeny z kategorii.
Allegro sellerid to: 37965974

Taki identyfikator otrzymałem w odpowiedzi (chyba to jest trace-id? ): 13048164003

Dzień dobry,
Mój klient, któremu zaimplementowaliśmy API ma problem z wystawieniem przedmiotu (przez zasób /offer) w 1 kategorii (czujniki i przetworniki), otrzymuje z API następujący komunikat przy próbie wystawienia (wcześniej klient korzystał już jakiś czas z api i wszystko działało w 100%):

Wystąpił błąd (produkt: PL20F), szczegóły poniżej:

    [VALIDATION_ERROR] - You cannot publish offer without a related product in this category. Select from the catalog or create a new product and associate it with your offer. - (null) - You cannot publish offer without a related product in this category. Select from the catalog or create a new product and associate it with your offer.

Obecnie ten błąd występuje tylko w tej kategorii, w innych może wystawić towar bez problemu.
Co ciekawe, myślałem że problem wynika z braku EAN'a (który jednak nie jest z tego co się orientuje obowiązkowy), a w dodatku mój klient sprzedaje specyficzny towar i nie zawsze zna ten numer (większość wystawia bez niego).
Kolejną ciekawą rzeczą jest to iż niewystawiona aukcja pojawia się u niego w panelu allegro "do dokończenia". Klient przechodząc tam, nie zmienia absolutnie nic po czym klika wystaw (już w Panelu jak normalny użytkownik) i aukcja normalnie się wystawia.

Co może być przyczyną takiego stanu rzeczy?

![kategorie_2](https://user-images.githubusercontent.com/50779251/208856803-4604253f-20db-415d-9fbe-2ba1ce8fb56e.jpg)
[odpowiedz.txt](https://github.com/allegro/allegro-api/files/10275894/odpowiedz.txt)
[request_wysylany.txt](https://github.com/allegro/allegro-api/files/10275895/request_wysylany.txt)

**Comment by hahyes** [comment]
@kofston W zapytaniu, które podajesz, nie ma podanego produktu z katalogu a najwyraźniej w tej kategorii wymagane jest powiązanie z produktyzacją.

**Comment by MartaNowaczyk** [comment]
[Od 1 sierpnia wszystkie oferty muszą być połączone z katalogiem produktów](https://developer.allegro.pl/news/od-1-sierpnia-nowe-oferty-w-wybranych-dzialach-wystawisz-dopiero-gdy-polaczysz-je-z-katalogiem-produktow-k16qKbnqkUY). Błąd wskazuje na to, że oferta nie jest połączona z produktem. W tym wypadku product.id jest niezbędny do powiązania produktu z ofertą podczas wystawiania oferty z użyciem [POST /sale/offers](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST). W przypadku tego rozwiązania warto, abyś spojrzał do [poradnika](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem-za-pomoca-zasobu-sale-offers). 
Poza tym zachęcam do sprawdzenia dedykowanych zasobów do wystawiania ofert z produktem - [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers). Na początku 2023 roku przestaniemy wspierać zasób [POST /sale/offers](https://developer.allegro.pl/documentation#operation/createOfferUsingPOST), a w 2024 planujemy go całkowicie wyłączyć.
