### ISSUE TITLE
Zdjęcie z oferty Allegro - embed

### ISSUE THREAD

**Issue by martinesocialgroup** [allegro/allegro-api#6510]
Witam. Posiadamy panel zarządzania firmą, w którym umieszczamy linki do zamówień (między innymi z Allegro), czy jest jakis kod embed, który by umieszczał zdjęcie z oferty w naszym panelu? Ułatwiłoby to nam podgląd zamówień. Wysyłam w załączniku pomysł szefa, jak miałoby to wizualnie wyglądać.

![Bez tytułu](https://user-images.githubusercontent.com/82035260/208891464-a9881cb3-7636-4036-a055-c266c3fc380c.png)

**Comment by Lukasz-Zurek** [comment]
Odpowiem Tobie w kontekście API - jeżeli pobierasz szczegóły zamówienia za pomocą GET /order/checkout-forms/{id} - w sekcji "lineItems" zwracamy oferty, które wchodzą w skład danego zamówienia. Pobierając oferty np. za pomocą GET /sale/offers w polu "primaryImage.url" zwracamy url pierwszego zdjęcia (miniaturki). Pamiętaj jednak, że w jednym zamówieniu może być kilka różnych ofert.
