### ISSUE TITLE
Możliwość kontroli One Fulfillment

### ISSUE THREAD

**Issue by LukaszWypych** [allegro/allegro-api#6511]
Dzień dobry,
czy istnieje możliwość ściągnięcia stanu magazynu One Fulfillment na zadany dzień? Chciałbym móc zamykać miesiąc i porównać zarejestrowane operacje, które wydarzyły się w przeciągu miesiąca ze stanem końcowym.
Drugie pytanie w tym temacie czy udostępniają Państwo operacje na magazynie razem z datami(wydanie towaru do klienta, przyjęcie towaru ze zwrotu klienta itp.)?

**Comment by MartaNowaczyk** [comment]
> czy istnieje możliwość ściągnięcia stanu magazynu One Fulfillment na zadany dzień? Chciałbym móc zamykać miesiąc i porównać zarejestrowane operacje, które wydarzyły się w przeciągu miesiąca ze stanem końcowym.

Nie ma takiej możliwości, mamy tylko aktualny status. Możesz jedynie zapisywać to po swojej stronie by do tego wracać.

> Drugie pytanie w tym temacie czy udostępniają Państwo operacje na magazynie razem z datami(wydanie towaru do klienta, przyjęcie towaru ze zwrotu klienta itp.)?

Mamy coś takiego jak fulfillment.status dla [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET), jednak nie ma tam dat i przyjęcia towaru ze zwrotu do klienta. O zmianie statusu informujemy w zasobie do pobierania zdarzeń w zamówieniach [GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET) "FULFILLMENT_STATUS_CHANGED". Tutaj uzyskasz daty, jednak pewnie nie są to wszystkie dane które chcesz otrzymać.
