### ISSUE TITLE
Get information about an offer

### ISSUE THREAD

**Issue by shahzain345** [allegro/allegro-api#6512]
I want to get information about an offer using the api, for example I want to get the seller, seller id, the price, the primary image and stuff, I do not see an endpoint in documentation that could help me with this

**Comment by MartaNowaczyk** [comment]
Do you mean public offers or "your" offers where you authorize with a token with user context? 
We have several ways to get the offer data:
1. [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getProductOffer) you will get the data of a single offer, but there is no seller ID and seller name here. You can download them separately via [GET /me](https://developer.allegro.pl/documentation/#operation/meGET). 
2. [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) - you will get the list of the seller's offers. As above - the seller ID and seller name are not here. You can download them separately via [GET /me](https://developer.allegro.pl/documentation/#operation/meGET). 
3. [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) - downloading public offer information, you will get seller's offer data along with seller.id and seller.login, but access to this resource is **limited**. You need to **verify your application to be able to download this data**. More you can find [here](https://developer.allegro.pl/tutorials/how-to-search-and-browse-offers-XxWm2ykMYHl).

I recommend that you check our [documentation](https://developer.allegro.pl/documentation/) for the fields you need.
