### ISSUE TITLE
Odmowa edycji oferty należącej do mojego konta

### ISSUE THREAD

**Issue by medikoo** [allegro/allegro-api#6513]
Autoryzowałem swoje konto (medikoo) by zarządzać ofertami przez API, nie mniej jak próbuję zmienić opis w istniejącej ofercie z pomocą API, dostaję błąd:

[403] "Brak dostępu. Nie masz uprawnień do operacji na wskazanej ofercie"

Dla ścisłości:
- Autoryzowałem się na pewno do konta "medikoo"
- Na pewno próbuję zmieniać ofertę z danego konta
- Ustawiony scope to: `allegro:api:sale:settings:write allegro:api:sale:offers:write allegro:api:sale:settings:read allegro:api:sale:offers:read`
- Nie mam problemu w wykonaniu takiej samej operacji na ofercie na drugim koncie (oczywiście używając innych kluczy autorauzacyjnych)

Z czego wynika odmowa?

**Comment by MartaNowaczyk** [comment]
Konto "medikoo" to konto zwykłe - aby wystawiać i edytować oferty powinno być zrejestrowane jako firmowe. W naszych [aktualnościach](https://developer.allegro.pl/news/od-12-lipca-2022-oferty-przez-api-beda-mogly-wystawiac-i-edytowac-tylko-konta-firmowe-aMGXmOdyXhq) znajdziesz więcej informacji na ten temat.

**Comment by medikoo** [comment]
@MartaNowaczyk Dziękuję za odpowiedź. Na tym koncie planuję wystawiać aukcje prywatne nie związane z moją działalnością gospodarczą (do sprzedaży firmowej korzystam z drugiego firmowego konta).

Czy mam rozumieć, że prywatna sprzedaż jest pozbawiona obsługi przez API?

**Comment by MartaNowaczyk** [comment]
W takim wypadku nie możesz zarządzać ofertami przez API.
