### ISSUE TITLE
PATCH sale/product-offers/{offerId} dodawanie zdjęć pomimo braku żądania

### ISSUE THREAD

**Issue by ricarderobl** [allegro/allegro-api#6514]
1. Najpierw pobieram aukcje z użyciem GET sale/product-offers/{offerId}.
2. Dostaje wynik, sprawdzam jakąś daną, np stawkę VAT czy jest ustawiona poprawnie, jeśli nie to edytuje.
3. Następnie wysyłam już edytowaną strukturę poprzez PATCH sale/product-offers/{offerId}, znajdują się tam w atrybucie Images tylko zdjęcia z przetwarzanej aukcji (np. sztuki w ilości 2).
4. Wysyłając takiego requesta dogrywane są zdjęcia z katalogu produktów Allegro (czyli bazowe 2 sztuki z aukcji plus wszystkie pozostałe z katalogu produktów), dlaczego? Zdjęcia w tym katalogu są często z bezsensowne. Są tam wgrywane zdjęcia nie mające nic wspólnego z produktem (np. absurdy pokroju logo jakiegoś innego sklepu czy też zdjęcia bardzo niskiej jakości). Proszę też nie odpisywać, że pracują Państwo nad jakością katalogu i zdjęć w nim się znajdujących i nie pisać, że możemy te błędy zgłaszać. Katalog produktów nazywa się katalogiem Allegro, więc to Państwo za niego odpowiadają i to w Państwa kwestii jest, by był poprawny.
5. **Największym problemem jest jednak to, że bez wyraźnego polecenia dogrania zdjęć coś jest dodawane.** Proszę o wyjaśnienie jak ma być zbudowany request, by nic Państwo od siebie nie dodawali.

**Comment by ricarderobl** [comment]
Dodam, że aktualnie chcę zmienić tylko stawkę VAT dla aukcji, gdzie ta stawka jest nieodpowiednia. Niestety dokumentacja w moim odczuciu jest tutaj niedokładna, gdyż z jednej strony twierdzą Państwo iż:

"Za pomocą [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) zmienisz dane w ofercie w prosty sposób - edytujesz dowolne pole oferty, a jednocześnie nie musisz przekazywać całego jej modelu.

W ten sposób edytujesz niezależnie m.in:"

A z drugiej:
"Ważne! Jeżeli chcesz zachować aktualny opis, zdjęcia i parametry produktowe, oprócz product.id powinieneś przekazać również takie pola jak: description, images i product.parameters. Możesz je pobrać z edytowanej przez Ciebie oferty, korzystając z [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET)."

Czyli jakoby mam zbudować request zawierający parametry produktowe, ale zachowując to dodawane są te zdjęcia, a także wpisuje parametry z katalogu produktów, które są często błędne, bo katalog jest źle zrobiony.

Chcę zmienić tylko jeden atrybut, niby PATCH na to pozwala, a tutaj chcąc zmienić jedną daną pobieram dane z katalogu, który jest źle zrobiony.

**Comment by ricarderobl** [comment]
Dla ułatwienia np. ten trace-id: 2c6c95d54f239586 dodał zdjęcia do aukcji.

Co ciekawe parametry samej aukcji są nieruszane (czyli product.parameters zostały takie jak były), natomiast images są dodawane.

**Comment by array3** [comment]
Potwierdzam ten problem. Niedawno zmieniliśmy funkcję:
`PUT /sale/offers/{offerId}`
na
`PATCH /sale/product-offers/{offerId}`
i od tego momentu zaczął występować ten problem. 
Zgadzam się z kolegą [ricarderobl](https://github.com/ricarderobl) i dlatego również proszę o uwzględnienie:
1. Przywrócenie zasady działania jak z wcześniejszej metody `PUT` (zdjęcia w ofercie powinny zawierać wyłącznie wysyłane zdjęcia)
2. Jedynie w przypadku wysyłania pustej wartości `"images": []` zdjęcia produktu mogłyby być dodawane do oferty
