### ISSUE TITLE
Numer przewozowy dla DPD - zły format?

### ISSUE THREAD

**Issue by micrec90** [allegro/allegro-api#6515]
Witam,

Korzystając z metody POST https://api.{environment}/order/checkout-forms/{id}/shipments chciałbym przypisać numer przewozowy do zamówienia (dla kuriera DPD).
Takie dane przesyłam:
```
{
  "carrierId": "DPD",
  "waybill": "0000001389486Q"
}
```
a tak wygląda response:
```
{
  "errors": [
    {
      "code": "CarrierWaybillValidationException",
      "message": "Provided waybill is not valid for this carrier",
      "details": null,
      "path": null,
      "userMessage": "Provided waybill is not valid for this carrier"
    }
  ]
}
```
waybill (numer przewozowy) pobieram korzystając z metody GET /parcel-management/parcels/{parcelId}

Według tego artykułu: https://www.kuriernet.pl/blog/2020/02/17/dpd-sledzenie-przesylek/
końcówka numeru przewozowego dla kurierów DPD powinna być U albo W

**Gdy w numerze przewozowym zmienię literę Q na U, żądanie jest zakończone sukcesem i numer jest przypisany.**

W przykładzie w dokumentacji: https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-pobrac-szczegolowe-informacje-o-paczce
również zwraca waybill z końcówką Q

Paczkę tworzyłem poprzez https://api.{environment}/parcel-management/parcel-create-commands/{commandId} podając serviceId c3066682-97a3-42fe-9eb5-3beeccab840c które według delivery services jest właśnie dla Allegro Kurier DPD (o carrierId "DPD")

Dodam że operuję na środowisku SANDBOX

Czy to jest błąd api czy numer przewozowy dla DPD należy pobrać w inny sposób?

**Comment by Lukasz-Zurek** [comment]
@micrec90 Zweryfikujemy ten przypadek, podaj proszę jednak numer zamówienia. W logach nie widzimy takiej przesyłki: 0000001389486Q.

**Comment by micrec90** [comment]
@Lukasz-Zurek 
numer zamówienia to: dd46dac0-7621-11ed-b2e3-29832197af5c
Tak jak wspomniałem, jest to zamówienie w środowisku SANDBOX i po krótkim eksperymentowaniu numer listu przewozowego został już dodany do zamówienia.

**Comment by micrec90** [comment]
Tak, do momentu uzyskania odpowiedzi po wywołaniu komendy /parcel-management/parcels/{parcelId} działało sprawnie
Chodzi o to że po wywołaniu tej komendy odpowiedź zwrotna miała waybill 0000001389486Q, dla której żądanie /order/checkout-forms/{id}/shipments zwróciło już błąd. Po zmianie litery Q na U, żądanie przeszło.

parcelId: 28fdeab1-25f0-4ae1-bd7e-22356ad0594f

**Comment by MaciejFrackowiak** [comment]
@micrec90 Weryfikujemy dalej opisany przez Ciebie przypadek, wrócimy z odpowiedzią.

**Comment by micrec90** [comment]
@MaciejFrackowiak @Lukasz-Zurek czy udało się zweryfikować sytuację? Czy suffix numeru przewozowego jest zależny od service id czy domyślnie zwraca literę Q?
(piszę w celu niewygaśnięcia wątku)

**Comment by Lukasz-Zurek** [comment]
@micrec90 Przepraszam Cię za długi czas oczekiwania. Sprawa ta była dość złożona, stąd dłuższy czas weryfikacji. Na Allegro Sandbox może się zdarzyć, że zwrócimy numer listu przewozowego z Q. Nie odnotowaliśmy jednak podobnych przypadków na produkcji. Jeśli taka sytuacja wystąpi poza środowiskiem testowym - proszę wówczas przesłać przykładowy numer listu oraz zamówienia.

**Comment by micrec90** [comment]
Dziękuję za odpowiedź. Zamykam temat.
