### ISSUE TITLE
Problem z aktualizacją ceny /offers/{auction-id}/change-price-commands/{}

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#6518]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Endpoint: /offers/{auction-id}/change-price-commands/{}

w czym tutaj jest problem?
wydaje mi się że request jest okej, niestety nie mam trace_id
```
(
    [response] => {"errors":[{"code":"ValidationError.MethodArgumentNotValidException","message":"Not valid parameters: input.buyNowPrice","details":"ValidationError.MethodArgumentNotValidException","path":"input.buyNowPrice","userMessage":"Niepoprawne parametry: input.buyNowPrice"}]}
    [request] => {"input":{"buyNowPrice":{"amount":"0.49","currency":"PLN"}}}
)
```

**Comment by DamianKAtomStore** [comment]
68260

**Comment by PrzemyslawLukanowski** [comment]
Otrzymujesz błąd, ponieważ cena w ofercie nie może być niższa niż 1zł.
