### ISSUE TITLE
400 Bad Request /sale/product-offers

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#6519]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Próbuje utworzyć ofertę za pomocą metody POST /sale/product-offers

`curl --location --request POST 'https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer ...' \
--data-raw '{
    "productSet": [
        {
            "product": {
                "name": "Produkt testowy",
                "category": {
                    "id": "89060"
                },
                "parameters": [
                    {
                        "id": 225693,
                        "name": "EAN",
                        "values": [
                            "0744861045021"
                        ]
                    },
                    {
                        "id": "237218",
                        "values": [
                            "Testowy tytuł"
                        ]
                    },
                    {
                        "id": 246845,
                        "valuesIds": [
                            "246845_622161"
                        ]
                    }
                ]
            }
        }
    ],
    "sellingMode": {
        "price": {
            "amount": "220.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 10
    }
}'`

W rezultacie dostaję 400 Bad Request a w body:
`{
    "details": {
        "connectionId": 1484276
    },
    "destination": {
        "path": "/sale/product-offers/",
        "originalDst": null,
        "host": null,
        "serviceTag": null
    },
    "message": "",
    "code": "-"
}`

Nie wiem o co dokładnie chodzi.

**Comment by PrzemyslawLukanowski** [comment]
Powinieneś otrzymać kod odpowiedzi 422 wraz z opisem błędu, w tym przypadku jest to "Wymagane jest co najmniej 1 zdjęcie.". Czy możesz podać trace-id tego wywołania?

**Comment by SlawomirMizerski** [comment]
W nagłówku odpowiedzi nie ma trace-id, jest tylko to
content-length 157
content-type application/vnd.allegro.envoy+json
date Fri, 23 Dec 2022 13:54:08 GMT
