### ISSUE TITLE
Aktywacja konta Allegro sandbox.

### ISSUE THREAD

**Issue by MykhailoPetrenko** [allegro/allegro-api#6520]
Proszę o pełną aktywacje konta w Allegro sandbox **client:105651641**

**Comment by MartaNowaczyk** [comment]
Uzupełnij jeszcze dane. Wejdź proszę do [ustawień konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy), skorzystaj z linku, który masz na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)" i wybierz "Weryfikacja pełna". Uzupełnij dane i prześlij dowolne pliki.

**Comment by MykhailoPetrenko** [comment]
Dane firmy są uzupełnione.

**Comment by MartaNowaczyk** [comment]
Dzięki. Aktywowałam to konto.

**Comment by dawidgorzanski** [comment]
Witam, mógłbym prosić o aktywację konta firmowego na Allegro sandbox?
login: dawidgorzanski

**Comment by MartaNowaczyk** [comment]
@dawidgorzanski z tego co widzę nie masz uzupełnionych [danych konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) np. adresu, nazwy firmy. Podaj takie jak podałeś w danych do wypłat podczas .

**Comment by dawidgorzanski** [comment]
Po przejściu w powyższy link widzę dane konta.
Gdy klikam "Zmień" przekierowuje mnie tutaj: https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty
A pod tym linkiem nie mogę nic zrobić...

**Comment by MartaNowaczyk** [comment]
@dawidgorzanski w takim razie sprawdzę co się stało po naszej stronie.

**Comment by MartaNowaczyk** [comment]
@dawidgorzanski przeprocesowałam aktywację, ale zobacz proszę czy wszystko jest ok, bo tu dziwna sytuacja była.

**Comment by dawidgorzanski** [comment]
@MartaNowaczyk w tym widoku https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty punkt "3. Weryfikacja firmy" wciąż wygląda jakby była w toku.

Dodatkowo spróbowałem wystawić nowy przedmiot na sprzedaż i formularz pojawił się poprawnie, ale przy próbie zapisania otrzymuje błąd: "Wystąpił błąd - Wskazane województwo jest nieprawidłowe."

**Comment by MartaNowaczyk** [comment]
@dawidgorzanski Po ręcznej aktywacji "Weryfikacja firmy" może być widoczna. 

Zobacz jakie dane masz w sekcji "Wysyłka z" w formularzu wystawiania oferty może w tym problem.

**Comment by MartaNowaczyk** [comment]
@dawidgorzanski Po ręcznej aktywacji "Weryfikacja firmy" może być widoczna. 

Zobacz jakie dane masz w sekcji "Wysyłka z" w formularzu wystawiania oferty może w tym problem.

**Comment by dawidgorzanski** [comment]
@MartaNowaczyk działa, faktycznie problemem była "Wysyłka z". Dziękuje za pomoc!

**Comment by optima2b** [comment]
Hey, proszę o aktywację dwóch business account: "linkapp", "linkapp_buyer"

**Comment by MaciejFrackowiak** [comment]
@optima2b Aktywowałem Twoje konta.

**Comment by optima2b** [comment]
Proszę jeszcze o aktywację regular account: "linkapp_buyer" (aktualnie nie można dokonywać płatności)

**Comment by MaciejFrackowiak** [comment]
@optima2b Pojawił się drobny problem podczas aktywacji wskazanego konta - działamy by go wyeliminować, wrócę z odpowiedzią.

**Comment by bigretromike** [comment]
Prosiłbym o aktywację: centrumradosci

**Comment by MaciejFrackowiak** [comment]
@optima2b Problem wyeliminowany - konto jest już aktywne!

**Comment by MaciejFrackowiak** [comment]
@bigretromike Czy uzupełniłeś cały krokowiec oraz dokonałeś przelew weryfikacyjny poprzez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta)? - pytam, ponieważ nie widzę pełnych danych Twojego konta.

**Comment by bigretromike** [comment]
> @bigretromike Czy uzupełniłeś cały krokowiec oraz dokonałeś przelew weryfikacyjny poprzez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta)? - pytam, ponieważ nie widzę pełnych danych Twojego konta.

może teraz?
krokowiec był zrobiony, nigdzie nie widziałem w menu nic o aktywacji, ale z linku wyżej dodałem numer konta i "zleciłem przelew"

**Comment by MaciejFrackowiak** [comment]
@bigretromike Trochę problemów z weryfikacją Twojego konta pojawiło się po drodze - proszę spróbuj raz jeszcze zlecić przelew.

**Comment by bigretromike** [comment]
> @bigretromike Trochę problemów z weryfikacją Twojego konta pojawiło się po drodze - proszę spróbuj raz jeszcze zlecić przelew.

Strona https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta nie ofertuje takiej możliwości
skorzystałem z https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty, tutaj twierdzi że "weryfikacja trwa" i że "coś poszło nie tak"

**Comment by MaciejFrackowiak** [comment]
@bigretromike Udało mi się zweryfikować Twoje konto.

**Comment by bigretromike** [comment]
> @bigretromike Udało mi się zweryfikować Twoje konto.

dziękuję
