### ISSUE TITLE
Proszę o aktywację konta na Sandbox

### ISSUE THREAD

**Issue by alicjafakturownia** [allegro/allegro-api#6524]
Proszę o aktywację konta na Sandbox- nie działa weryfikacja przelewem. 

integracje@fakturownia.pl

**Comment by MartaNowaczyk** [comment]
Wejdź proszę do [ustawień konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy), skorzystaj z linku, który masz na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)" i wybierz "Weryfikacja pełna". Uzupełnij dane i prześlij dowolne pliki.

**Comment by alicjafakturownia** [comment]
Gotowe :) Uzupełnione

**Comment by MartaNowaczyk** [comment]
Aktywowałam Twoje konto :)

**Comment by JacekStawicki360** [comment]
Cześć.
prosze o aktywacje konta 360sprzedawca1@gazeta.pl

wciaz mam info ponizsze (od miesiecy) i nic nie moge wiece zrobic

![image](https://user-images.githubusercontent.com/88323215/210738465-d8b5f778-64ad-4312-94e7-c0abb08c43b6.png)

**Comment by PrzemyslawLukanowski** [comment]
@JacekStawicki360 Wykonaj proszę [ponownie przelew weryfikacyjny](https://allegro.pl/moje-allegro/moje-konto/dane-konta/), umożliwi to nam dalszą weryfikację konta.

**Comment by JacekStawicki360** [comment]
Zrobione na sandbox

**Comment by PrzemyslawLukanowski** [comment]
@JacekStawicki360 Aktywowałem Twoje konto.

**Comment by JacekStawicki360** [comment]
Dziekuje

**Comment by robboh** [comment]
> Wejdź proszę do [ustawień konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy), skorzystaj z linku, który masz na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)" i wybierz "Weryfikacja pełna". Uzupełnij dane i prześlij dowolne pliki.

Ale to nie działa PO wpisanku fikcyjnych danych wyskakuje okienko "Nie możesz jeszcze wysłać swoich dokumentów
Najpierw ustaw konto do wypłat" i kółko się zamyka. Jak aktywować to konto sandbox?

**Comment by robboh** [comment]
Proszę o aktywację konta sandbox dla użytkownika conerczesci_pl

**Comment by MaciejFrackowiak** [comment]
@robboh Twoje konto jest już zweryfikowane.
