### ISSUE TITLE
Problem z autoryzacją, "Full authentication is required to access this resource"

### ISSUE THREAD

**Issue by DawidPPGithub** [allegro/allegro-api#6525]
Witam, 
mam problem z autoryzacją w API Allegro. Co pewien czas wyskakuje mi błąd: 401, {"error":"unauthorized","error_description":"Full authentication is required to access this resource"} i na jakiś nieokreślony czas (1-2 dni) blokuje dostęp do aplikacji. Aplikacja jest napisana w PHP.
Tokeny autoryzacyjne (access token i refresh token) odświeżają się prawidłowo. 

Jak mogę rozwiązać ten problem?

**Comment by AureliuszBrussy** [comment]
Taki problem zwykle powoduje korzystanie z nieodpowiedniego tokena (_bearer-token-for-application_ zamiast _bearer-token-for-user_ na zasobach, gdzie tego wymagamy) lub jakieś błędy w nagłówku Authorization. 

Wskaż proszę trace-id wywołania kończącego się tym błędem (znajdziesz go w nagłówku response'a) oraz wyślij proszę w [formularzu kontaktowym](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b)  access_token, z którego skorzystałeś w tym requeście. W formularzu dopisz numer wątku na GitHubie: #6525.

**Comment by DawidPPGithub** [comment]
Wysłałem potrzebne informacje w formularzu kontaktowym. (dodałem również kod PHP, z którego skorzystałem)

**Comment by AureliuszBrussy** [comment]
@DawidPPGithub otrzymałem Twoje dane, natomiast potrzebuję jeszcze trace-id wywołania, które zakończyło się wspomnianym błędem.

**Comment by DawidPPGithub** [comment]
Czy trace-id to Resource id?

**Comment by AureliuszBrussy** [comment]
@DawidPPGithub nie, nazwa nagłówka, w którym zwracamy trace-id to po prostu trace-id.

**Comment by DawidPPGithub** [comment]
Przepraszam, ale nie bardzo wiem, która zmienna to nazwa nagłówka. Chodzi o zmienną, która jest przypisana do funkcji curl_init?

**Comment by DawidPPGithub** [comment]
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Authorization: Basic " . base64_encode($cnf->clientId . ':' . $cnf->clientSecret), "Accept: application/vnd.allegro.public.v1+json"));

**Comment by AureliuszBrussy** [comment]
@AureliuszBrussy header trace-id znajdziesz w **naszym** response, czyli zapisany będzie w obiekcie, w którym zapisujesz wynik funkcji `curl_exec()`.

**Comment by DawidPPGithub** [comment]
Kod:
$result = curl_exec($ch); echo 'trace-id: '.$result;
Zwraca: "trace-id: {"error":"Unauthorized","error_description":"Unauthorized"}"

**Comment by AureliuszBrussy** [comment]
@DawidPPGithub w tej sposób nie uzyskasz trace-id. Możesz to zrobić w różny sposób, np. korzystając z opcji [CURLOPT_HEADERFUNCTION](https://curl.se/libcurl/c/CURLOPT_HEADERFUNCTION.html). Trace-id to unikatowy numer response'a, który zwracamy do każdego requesta, więc musiałbyś odtworzyć sytuację z błędem `{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}` i zapisać trace-id tej odpowiedzi. Trace-id pozwoli mi prześledzić dokładnie request w naszych logach i namierzyć powód tego problemu.

**Comment by DawidPPGithub** [comment]
Dobrze spróbuje zaraz to wykonać, ale mam jeszcze pytanie. Poprzez mój skrypt w mailach allegro wysyłam link do strony pod którą znajduje się zakupione przez klienta zamówienie. Czy jest możliwość, że otrzymałem automatyczną lub ręczną blokadę mojego API za wysyłanie linków w wiadomościach allegro?

**Comment by AureliuszBrussy** [comment]
@DawidPPGithub nie, nie powinien być to powód. Wygląda to na błąd przy próbie pozyskiwaniu tokenów lub użyciu niepoprawnego access_tokena.

**Comment by DawidPPGithub** [comment]
Jaką zmienną powinienem przypisać do header_callback? Nie mogę znaleźć tej informacji w internecie, będę wdzięczny za odpowiedź.
curl_setopt($ch, CURLOPT_HEADERFUNCTION, header_callback);

**Comment by AureliuszBrussy** [comment]
@DawidPPGithub przykro mi, jednak tutaj Ci nie pomogę. Jestem pewien, że znajdziesz jakiś przykład lub ew. możesz skorzystać z innych metod do pobrania nagłówka z response'a.

**Comment by DawidPPGithub** [comment]
Udało mi się znaleźć trace-id, ale czy moge je tu podać?

**Comment by DawidPPGithub** [comment]
Dla potwierdzenia wysyłam error, który otrzymałem: error="unauthorized", error_description="Full authentication is required to access this resource"
Oraz trace-id: 9277f5071271acd4

**Comment by AureliuszBrussy** [comment]
Dziękuję za trace-id - w swoim requeście nie przekazujesz w ogóle header'a Authorization, stąd błąd.

**Comment by DawidPPGithub** [comment]
Wydaje mi się, że przekazuje header authorization. 
Wysyłam kod funkcji używanej do wyświetlenia ofert:
function get_data($cnf, $url)
{
    $ch = curl_init();
    $headers = array("Authorization: Bearer " . $cnf->token, "Accept: application/vnd.allegro.public.v1+json");
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows; U; Windows NT 5.1; pl; rv:1.9.1.7) Gecko/20091221 Firefox/3.5.7');
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 10);
    curl_setopt($ch, CURLOPT_POSTREDIR, 3);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    // curl_setopt($ch, CURLOPT_HEADERFUNCTION, $ch, $strch);
    curl_setopt($ch, CURLOPT_HEADER, 1);
    $data = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    // After curl_exec
    $header_size = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
    $header = substr($data, 0, $header_size);
    $body = substr($data, $header_size);
    echo $header;

    if ($data === false || $resultCode !== 200) {

        exit("Coś poszło nie tak, kod_get_datah: " . $resultCode.', '.$data.','.$ch);
    }
    $data = json_decode($data);

    if (!is_object($data)) {
        $data = new stdClass();
        exit("Coś poszło nie tak, kod_get_data2: " . $resultCode);
    }
    return $data;
}

**Comment by DawidPPGithub** [comment]
Udało się rozwiązać problem! Dziękuję bardzo za pomoc. Musiałem pozmieniać url'e api allegro przekazywane do funkcji (zamiast http na https).
