### ISSUE TITLE
Liczba znaków w adresie. Walidacja danych przed wysłaniem do API

### ISSUE THREAD

**Issue by maniootek** [allegro/allegro-api#6528]
Nie mogę znaleźć jakiejś rozpiski dotyczącej zasad nadawania przesyłek przez WzA typu Allegro One Box, Allegro One Punkt związaną z minimalną i maksymalną liczbą znaków w adresie (ulica, imię i nazwisko, firma). Chodzi o to, że często moja integracja, która nadaje tego typu przesyłki wyrzuca mi błąd typu "ulica jest za długa" lub "imię jest za krótkie". Chciałbym poznać te widełki liczbowe odnośnie liczby znaków.
Dodam, że integracja nie jest moja tylko kupiona w sieci i nie jestem obeznany w API tylko chciałem sobie wcześniej w programie sprzedażowym poprawiać dane wg wytycznych.

**Comment by AureliuszBrussy** [comment]
Każdy przewoźnik określa swoje własne wymagania, więc nie mamy tych informacji w dokumentacji. 

W przypadku Allegro One/UPS limity wynoszą:

* sender:
    * name - 30
    * company - 30
    * email - długość nieokreślona
    * city - 30
    * street - 31
* receiver:
    * name - 30
    * company - 30
    * email - długość nieokreślona
    * city - 30
    * street - 35
* description - 50


Minimalne liczba znaków w polach to 2 znaki. Dla pola **name** są to 2 znaki dla imienia i 2 znaki dla nazwiska.

**Comment by maniootek** [comment]
Bardzo dziękuję. **Allegro Kurier UPS** ma tak samo?

**Comment by maniootek** [comment]
Czy dało by się też sprawdzić jakie znaki są dopuszczalne w danych polach? Ostatnio dla Allegro Kurier UPS wyrzuciło błąd jak w polu adres (ulica) był podany nr lokalu w nawiasach. Chodziło właśnie o znaki otwartego i zamkniętego nawiasu.
Tak samo które pola są obowiązkowe? Tylko pole company jest chyba opcjonalne a reszta wymagane, zgadza się?

**Comment by maniootek** [comment]
No i jaka jest minimalna masa?

**Comment by AureliuszBrussy** [comment]
Tak, dla Allegro Kurier UPS limity są takie same. 

Niestety, nie jestem w stanie podać listy dopuszczalnych/niedopuszczalnych znaków specjalnych. 

Co do wymagalności pól: 
uzupełnienie **name** wymagane jeśli nie jest uzupełnione pole **company**, a **company** jest wymagane, gdy nie jest uzupełnione **name**. Reszta pól jest wymagana. 

Minimalna masa to > 0. Realnie nie powinno być przypadku, że masa jest zbyt niska.

**Comment by maniootek** [comment]
waga minimalna to chyba 0.01kg bo 0.001kg nie przechodzi

**Comment by AureliuszBrussy** [comment]
@maniootek potwierdzę to jeszcze z zespołem odpowiedzialnym za usługę i wrócę od Ciebie z informacją.

**Comment by maniootek** [comment]
Czy udało się coś ustalić?
Dodam, że nadawanie listów kończy się błędem, jeżeli w polu ulica lub miejscowość pojawią się znaki takie jak kropka, przecinek, nawias. Jaki jest zakres dozwolonych znaków w tych polach?

**Comment by AureliuszBrussy** [comment]
Jeżeli chodzi o wagę minimalną - przekazana wartość musi wynosić więcej niż 0. Podana wartość jest jeszcze przetwarzana i "zaokrąglana" do góry (sufit po pierwszym miejscu po przecinku). To znaczy, że 3.14 zostanie zaokrąglone do 3.2, a 0.0000001 zostanie zaokrąglone do 0.1. 

Co do znaków specjalnych - jeszcze to potwierdzam. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@maniootek czy mógłbyś podać trace-id wywołania zakończonego błędem?

**Comment by maniootek** [comment]
mam serię request i response z programu, który nadaje przesyłki
`{"id":"4f465c57-be5e-4b06-b0b5-f823ade2e2df","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Parcel weight is incorrect","details":null,"path":"items.weight.value","userMessage":"Proszę podać prawidłową wagę"}]}`

**Comment by maniootek** [comment]
druga sprawa to kwestia pola "NAZWA" w danych adresowych, przykładowa fraza "Jan Kowalski - Sybrek" jest prawidłowa i paczka się nadaje, czyli znak myślnika jest dopuszczalny, jakie znaki są jeszcze dopuszczalne w polu nazwa?

**Comment by AureliuszBrussy** [comment]
Wg. naszych logów wartość, która do nas dotarła w tej komendzie to: 

`{"weight":{"value":"0.000","unit":"KILOGRAM"}`

Co do znaków specjalnych - jeszcze to ustalam. Wrócę ze szczegółami.

**Comment by maniootek** [comment]
Co do wagi to już udało mi się zlokalizować błąd i faktycznie wysyłana była wartość 0.000 zamiast 0.001
@AureliuszBrussy  Czekam co do specyfikacji i znaków specjalnych

**Comment by AureliuszBrussy** [comment]
Dla pola _street_ dozwolone znaki to: 
`' , . " - – /`

Dla pola _company_ dozwolone znaki to:
```
. , : ; ( ) / * # ` ' \ " _ - &
```

**Comment by maniootek** [comment]
Nadawanie przesyłki ze znakami takimi jak kropka, przecinek, średnik, nawias otwarty, nawias zamknięty w polu street (ulica) kończy się błędem. 
![image](https://user-images.githubusercontent.com/45625552/212928546-396909d4-dc1b-47ee-97d4-5545a0e216e5.png)

**Comment by AureliuszBrussy** [comment]
@maniootek w odpowiedzi wyżej wymieniłem **dozwolone** znaki. W polu _street_ niedozwolonym znakiem jest np. średnik, który użyłeś w przykładnie powyżej. Niedozwolone są także nawiasy. 

Przed chwilą to przetestowałem i każdy z dozwolonych znaków, które wymieniłem dla pola _street_ jest akceptowany.
