### ISSUE TITLE
Sprawdzenie historii logów dla konkretnych ofert.

### ISSUE THREAD

**Issue by polenquick** [allegro/allegro-api#6530]
Cześć.
Interesuje mnie sprawdzenie historii zmian cen dla dla konkretnego ID oferty do kilku miesięcy wstecz, albo zobaczyć podgląd requesta bez trace-id. Przypuszczam, że ktoś ręcznie podmienił cenę aukcji lub integracja zaczęła się wysypywać.
Dotychczas pisałem o to bezpośrednio na czacie Allegro i uzyskiwałem odpowiedź typu o której godzinie i i kiedy została wykonana aktualizacja oferty stąd pytanie, czy API pozwala na samodzielne pobranie logów dla danej oferty. Jeśli tak to jakiego endopointu użyć.

**Comment by MartaNowaczyk** [comment]
Cześć, nie mamy takiego endpointu, który dla konkretnej oferty zwróciłby Ci informacje o zmianach ceny do kilku miesięcy wstecz. Możesz tylko zbierać zdarzenia dla swoich ofert, które zwracamy z ostatnich 24 godzin - [GET /sale/offer-events](https://developer.allegro.pl/documentation/#operation/getOfferEvents).
