### ISSUE TITLE
Errors dla pól, które nie są i nie powinny być przekazywane [ADVERTISEMENT] sale/product-offers

### ISSUE THREAD

**Issue by redwingecommerce** [allegro/allegro-api#6533]
Dodaję ogłoszenie (ADVERTISEMENT).
Mimo, że nie przekazuję w request danych o delivery, stock, itp., otrzymuję w odpowiedzi kod 422 i błędy na ich temat (mówiące o tym, że nie powinienem ich podawać). Jak w tej sytuacji powinienem się zachować? Podawać puste? Czy to błąd API?
Przykładowo jest poniżej mowa o stock, którego nie należy podawać, nie podaję, a dostaję ten błąd. Wcześniej próbowałem podawać stock, ale dostawałem wtedy informację, że dla ADVERTISEMENT nie mogę podawać stock.

**REQUEST:**
{
  "productSet": [
    {
      "product": {
        "id": "Linde1234",
        "idType": "MPN",
        "name": "[2013] WÓZEK WIDŁOWY LINDE H80D-1100 DIESEL 8ton",
        "images": [
          "https://a.allegroimg.allegrosandbox.pl/original/11f059/39c2c4184e8aae7b6dea67fb8d71",
          "https://a.allegroimg.allegrosandbox.pl/original/115c6a/8b84e07242b8bbcb7cdb40799ee7",
          "https://a.allegroimg.allegrosandbox.pl/original/11cc5e/9ce5a2c548149e26599cea302e27",
          "https://a.allegroimg.allegrosandbox.pl/original/11f349/2f58fcf14d41a37b6ee3a872b398",
          "https://a.allegroimg.allegrosandbox.pl/original/11192a/aa4c001a431dae51c34ae78932df"
        ],
        "category": {
          "id": "252945"
        },
        "parameters": [
          {
            "id": "211406",
            "valuesIds": [
              "211406_249626"
            ],
            "values": [],
            "rangeValue": null
          },
          {
            "id": "1",
            "valuesIds": [],
            "values": [
              "2013"
            ],
            "rangeValue": null
          },
          {
            "id": "128813",
            "valuesIds": [],
            "values": [
              "16200"
            ],
            "rangeValue": null
          },
          {
            "id": "128842",
            "valuesIds": [],
            "values": [
              "8"
            ],
            "rangeValue": null
          },
          {
            "id": "128841",
            "valuesIds": [
              "128841_2"
            ],
            "values": [],
            "rangeValue": null
          }
        ]
      }
    }
  ],
  "name": "[2013] WÓZEK WIDŁOWY LINDE H80D-1100 DIESEL 8ton",
  "category": {
    "id": "252945"
  },
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_2"
      ],
      "values": [],
      "rangeValue": null
    }
  ],
  "images": [
    "https://a.allegroimg.allegrosandbox.pl/original/11f059/39c2c4184e8aae7b6dea67fb8d71",
    "https://a.allegroimg.allegrosandbox.pl/original/115c6a/8b84e07242b8bbcb7cdb40799ee7",
    "https://a.allegroimg.allegrosandbox.pl/original/11cc5e/9ce5a2c548149e26599cea302e27",
    "https://a.allegroimg.allegrosandbox.pl/original/11f349/2f58fcf14d41a37b6ee3a872b398",
    "https://a.allegroimg.allegrosandbox.pl/original/11192a/aa4c001a431dae51c34ae78932df"
  ],
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>Aaaa</p>"
          }
        ]
      }
    ]
  },
  "sellingMode": {
    "format": "ADVERTISEMENT",
    "price": {
      "amount": "251900",
      "currency": "PLN"
    }
  },
  "location": {
    "countryCode": "PL",
    "province": "PODLASKIE",
    "city": "Białystok",
    "postCode": "15-688"
  },
  "payments": {
    "invoice": "VAT"
  }
}

**RESPONSE:**
```
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => FORBIDDEN_SHIPPING_RATES_IN_ADVERTISEMENT
                    [message] => Shipping rate in advertisement is forbidden
                    [details] => 
                    [path] => delivery.shippingRates
                    [userMessage] => W ogłoszeniu nie może być ustawiony cennik.
                )

            [1] => Array
                (
                    [code] => ConstraintViolationException.NoAfterSalesServiceConditionsInAdvertisement
                    [message] => You cannot set after sales service conditions in the case of classified ads.
                    [details] => ConstraintViolationException.NoAfterSalesServiceConditionsInAdvertisement
                    [path] => null
                    [userMessage] => Nie możesz dodać warunków reklamacji, warunków zwrotów i warunków gwarancji do ogłoszenia.
                )

            [2] => Array
                (
                    [code] => ConstraintViolationException.ValidAdvertisementPackage
                    [message] => Package is unassigned to offer or category does not match to the package.
                    [details] => ConstraintViolationException.ValidAdvertisementPackage
                    [path] => sellingMode
                    [userMessage] => Pakiet ogłoszeniowy nie jest przypisany do oferty lub kategoria nie pasuje do pakietu.
                )

            [3] => Array
                (
                    [code] => AdvertisementWithoutStockViolation
                    [message] => You cannot set quantity of stock in the case of classified ads.
                    [details] => AdvertisementWithoutStockViolation
                    [path] => stock.available
                    [userMessage] => Nie możesz ustawić liczby sztuk dla ogłoszenia.
                )

            [4] => Array
                (
                    [code] => AvailableStockMustEqualToOneOrBeGreaterThanOne
                    [message] => The stock level of items to be listed may not be lower than 1.
                    [details] => AvailableStockMustEqualToOneOrBeGreaterThanOne
                    [path] => stock.available
                    [userMessage] => Wystawiana liczba nie może być mniejsza niż 1.
                )

        )

)
```

**Comment by AureliuszBrussy** [comment]
Zasób **/sale/product-offers** jest zaprojektowany tak, aby uzupełniać niektóre pola wartościami domyślnymi w przypadku braku ich podania. O tych wartościach domyślnych piszemy w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem-za-pomoca-zasobu-sale-product-offers). 

Rozwiązaniem na ten moment (dla oferty o formacie ADVERTISEMENT) jest przekazanie **null** w polach:
- delivery.shippingRates,
- afterSalesServices.impliedWarranty,
- afterSalesServices.returnPolicy,
- stock.available.

Zgłosiłem to do zepołu odpowiedzialnego za zasób - być może uda się wypracować rozwiązanie, dzięki któremu dla oferty o formacie ADVERTISEMENT będzie można pominąć ten warunek i wartości domyślne nie będą uzupełniane. Wrócimy z informacją, jeżeli wdrożymy zmiany. 

Dodatkowo, dla oferty w formacie ADVERTISEMENT niezbędne jest przypisanie pakietu ogłoszeniowego - można to zrobić, jeżeli oferta jest szkicem. Aby utworzyć szkic, przekaż w polu **publication.status** wartość **INACTIVE**. 

Następnie pobierz dostępne w kategorii pakiety ([GET /sale/classifieds-packages](https://developer.allegro.pl/documentation#operation/getClassifiedPackageConfigurationsForCategoryUsingGET)), przypisz wybrany pakiet do utworzonego wcześniej szkicu ([PUT /sale/offer-classifieds-packages/{offerId}](https://developer.allegro.pl/documentation#operation/assignClassifiedPackagesUsingPUT)). Po przypisaniu możesz aktywować ofertę z produktem za pomocą:
- [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/editProductOffers),
- lub [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation#operation/changePublicationStatusUsingPUT).

**Comment by redwingecommerce** [comment]
Tak, null pomogły, jednak zdecydowanie domyślne wartości powinny same się uzupełniać. Ułatwiłoby to sprawę.

**Comment by AureliuszBrussy** [comment]
@redwingecommerce wdrożyliśmy poprawkę, w której zmieniamy wartości domyślne dla oferty w formacie ADVERTISEMENT.
