### ISSUE TITLE
Wysyłam z Allegro błąd

### ISSUE THREAD

**Issue by skmaksio** [allegro/allegro-api#6535]
Czy są jakieś przerwy w działaniu Wysyłam z Allegro? Od około godziny otrzymuję zwrotkę z API:

Array
(
    [id] => 0ef281f5-23a3-2feb-d72a-36d0bc1a412a
    [parcelId] => 
    [status] => ERROR
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ERROR
                    [message] => Error during ordering - InPost service is not available
                    [details] => 
                    [path] => /parcel-management/parcel-create-commands/{commandId}
                    [userMessage] => Brak odpowiedzi z API InPost. Przesyłka nie została zamówiona. Spróbuj ponownie za chwilę.
                )

        )
)

**Comment by AureliuszBrussy** [comment]
@skmaksio wczoraj mogły wystąpić sporadyczne błędy w dostępie do API InPostu, natomiast nie były to problemy na szeroką skalę.
