### ISSUE TITLE
Integracja z Allegro

### ISSUE THREAD

**Issue by alicjafakturownia** [allegro/allegro-api#6536]
Czy jest możliwość, żeby w allegro sprzedawca podpiął zewnętrzny endpoint, który byłby wywoływany przy każdym zajściu order event? Tak aby nie trzeba było odpytywać API Allegro czy zaszło zdarzenie (order event), tylko żeby Allegro poinformowało zewnętrzne API o zajściu zdarzenia.

**Comment by AureliuszBrussy** [comment]
Nie, nie udostępniamy takiej funkcjonalności. Udostępniamy jedynie endpoint [GET /order/events](https://developer.allegro.pl/documentation#operation/getOrderEventsUsingGET).
