### ISSUE TITLE
Offer status changes and stock quantty

### ISSUE THREAD

**Issue by andriusdum** [allegro/allegro-api#6537]
Hi,
I noticed that i can no longer set offer status to 0. I can only set 1 or more.

It would be not big deal,if I could change status, but I can not change it also.
I try to set "INACTIVE", "ENDED" nothing works.

So my question what changed? and what can I do to change offer status or stock to 0.

My gold is to have correct stock quantity in Allegro ( set to 0 when we do not have it ) , or disable offer when we do not have stock

**Comment by AureliuszBrussy** [comment]
The stock level of items to be listed may not be lower than 1, so you cannot set it to 0. But you should be able to end the offer by changing the publication status to "ENDED".  

You can do this by using:
-  [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) - more info in [our guide](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#offer-status-change),
- [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation#operation/changePublicationStatusUsingPUT).

If you have a problem with ending the offer - please send the trace-id of an example request that failed. Trace-id can be found in the header of our API response.

**Comment by andriusdum** [comment]
Thank you, links you send helped .

My problem was , that I used old endpoint PUT /sales/offers/{offerId}

and I changed to PATCH /sales/product-offers/{offerid} and then I manage to change status as I need .

Thank you.
