### ISSUE TITLE
Błąd utworzenia oferty w wyniku nie znalezienia produktu

### ISSUE THREAD

**Issue by medikoo** [allegro/allegro-api#6538]
Próbuję dodać ofertę, podając EAN produktu. Allegro odrzuca moje żądanie błędem:

```
Nie znaleziono produktu dla podanego identyfikatora.
Nie podano danych niezbędnych do utworzenia propozycji produktu i/lub utworzenia oferty.
```

Gdzie znajdę informacje na temat tego jakie są niezbędne dane do utworzenia propozycji produktu? (Przydałoby się aby ta informacja o błędzie albo zawierała tę informację albo dawała odnośnik do miejsca gdzie można takę informację znaleźć)

**Comment by AureliuszBrussy** [comment]
Widzę, że jest to duplikat wątku #6539, gdzie podałeś więcej szczegółów, więc zamykam to zgłoszenie i odpowiem w drugim wątku.

**Comment by medikoo** [comment]
@AureliuszBrussy to nie jest duplikat. W tym wątku zgłosiłem, że w informacji o błędzie brakuje istotnych informacji i warto by to było polepszyć.

Natomast #6539 dotyczy niespodziewanego zachowania API, gdzie przy wszystkich wymaganych parametrach podanych wciąż jest zgłaszany błąd, że nie wszystkie są podane

**Comment by AureliuszBrussy** [comment]
@medikoo rozumiem, tak jak wspomniałem w wątku #6539 - informacje te znajdziesz korzystając z zasobu [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). Twoją uwagę dot. zmiany komunikatu błędu (tak, aby np. podpowiadał brakujące do utworzenia parametry) przekazuję do zespołu odpowiedzialnego za ten zasób.
