### ISSUE TITLE
Problem z pobraniem danych ofert z wykorzystaniem bear token

### ISSUE THREAD

**Issue by KonradKoch** [allegro/allegro-api#6543]
Witam, 

Probuje bezskutecznie pobrac dane wszystkich ofert z api z wykorzystaniem tego kodu i bear tokena, caly czas dostaje 403.

await axios.get('https://api.allegro.pl/sale/offers',
        {
            headers: {
                Authorization: 'Bearer' + ' ' + token,
                Accept: 'application/vnd.allegro.public.v1+json'
            }
        })

czy ten request jest wykonywany poprawnie?

**Comment by KonradKoch** [comment]
Przykladowy response:

response: {
    status: 406,
    statusText: 'Not Acceptable',
    headers: AxiosHeaders {
      'trace-id': 'd0d8b59f1784b5b0',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '255',
      date: 'Mon, 02 Jan 2023 00:53:06 GMT',
      connection: 'close'
},

**Comment by KonradKoch** [comment]
response: {
    status: 403,
    statusText: 'Forbidden',
    headers: AxiosHeaders {
      'trace-id': 'd67c8fe0b961d8d4',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '162',
      date: 'Mon, 02 Jan 2023 02:10:13 GMT',
      connection: 'close'
    },

**Comment by PrzemyslawLukanowski** [comment]
Twoje wywołanie odbywa się w ramach tokena, który nie posiada zakodowanej informacji o użytkowniku. Oznacza to, że najprawdopodobniej token wygenerowałeś w drodze autoryzacji [client_credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow). Musisz skorzystać z autoryzacji [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow), aby mieć dostęp do tego zasobu.
