### ISSUE TITLE
InPost service is not available

### ISSUE THREAD

**Issue by awawrowicz** [allegro/allegro-api#6544]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Nie jesteśmy w stanie wygenerować przesyłek dla Allegro Inpost. Problemy występują dzisiaj, tj 2023-01-02, od godziny 6:00 nieprzerwanie do 9:00. Przykładowy request i response poniżej.

`GET https://api.allegro.pl/parcel-management/parcel-create-commands/885e5aef-f013-44e8-beea-af5124b5ecc9`

`{
    "id": "885e5aef-f013-44e8-beea-af5124b5ecc9",
    "parcelId": null,
    "status": "ERROR",
    "errors": [{
        "code": "ERROR",
        "message": "Error during ordering - InPost service is not available",
        "details": null,
        "path": "/parcel-management/parcel-create-commands/{commandId}",
        "userMessage": "Brak odpowiedzi z API InPost. Przesyłka nie została zamówiona. Spróbuj ponownie za chwilę."
    }]
}`

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku prosiłbym o kontakt bezpośrednio z Inpost - konto, które próbuje wygenerować przesyłkę posiada niedoładowane konto prepaid w InPost albo nieopłaconą fakturę.

**Comment by awawrowicz** [comment]
A czy byłaby szansa na jakiś komunikat zwrotny z API, bo "Brak odpowiedzi z API InPost" nie pomaga zidentyfikować przyczyny.

**Comment by PrzemyslawLukanowski** [comment]
Tak, mamy to w planach, jednak w tym przypadku nie jest to zależne wyłącznie od nas.
