### ISSUE TITLE
Hello, why do you always prompt this error:Internal server error. Please try again in a few minutes.

### ISSUE THREAD

**Issue by lanxiaokeng** [allegro/allegro-api#6545]
{
  "name": "4PCS CHRISTMAS SOCK Santa Claus",
  "category": {
    "id": "320008"
  },
  "parameters": [
    {
      "id": "11323",
      "name": "Stan",
      "rangeValue": null,
      "values": [],
      "valuesIds": [
        "11323_1"
      ]
    }
  ],
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>Stan: Nowy</p><p>Faktura: Nie wystawiam faktury</p><p>Marka: inna (MER-SHOP)</p><p>Kod producenta: MER210001</p>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/11d2ef/cc1d536d4e9bb0420254fe02054a"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/11582e/59a52afb46118d6de18de424a219"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/11a2b7/fb1928974bed9a687352dddee409"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/11049c/d7ce12944b04aa118bf7fae2be45"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/11196f/d647520a4f08b27bcf1f78ba2ae8"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/11a63e/d55288db4f7dac153c257883686a"
          }
        ]
      }
    ]
  },
  "compatibilityList": null,
  "tax": null,
  "delivery": {
    "shippingRates": {
      "id": "0cefba9c-a4bc-40d3-b26d-1bf53cdbe6ea"
    },
    "handlingTime": "P5D",
    "additionalInfo": null,
    "shipmentDate": null
  },
  "payments": {
    "invoice": "NO_INVOICE"
  },
  "discounts": {
    "wholesalePriceList": {
      "id": ""
    }
  },
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "3e958753-cfb8-42db-8ca6-8f38381de758",
      "name": "complaints"
    },
    "returnPolicy": {
      "id": "04ac6ce8-3ac3-4c19-a551-75b0da66ce95",
      "name": "returns"
    },
    "warranty": null
  },
  "additionalServices": null,
  "sizeTable": null,
  "fundraisingCampaign": null,
  "location": {
    "countryCode": "CN",
    "province": null,
    "city": "quanzhou",
    "postCode": "362046"
  },
  "attachments": [],
  "b2b": {
    "buyableOnlyByBusiness": false
  },
  "messageToSellerSettings": {
    "mode": "OPTIONAL"
  },
  "language": "pl-PL",
  "product": null,
  "stock": {
    "available": 100,
    "unit": "UNIT"
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "110",
      "currency": "PLN"
    }
  }
}

patch
https://api.allegro.pl/sale/product-offers/12813993176

{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please try again in a few minutes."}]}

**Comment by PrzemyslawLukanowski** [comment]
Hello, the problem is caused because of the invalid structure, in the discounts.wholesalePriceList.id you are passing empty "" - provide null instead or don't pass this field at all.

**Comment by lanxiaokeng** [comment]
Excuse me, I only have 11 pictures. Why does it remind me that it exceeds the limit of 16

{
  "name": "4PCS CHRISTMAS SOCK Santa Claus",
  "category": {
    "id": "320008"
  },
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "229205",
      "valuesIds": [
        "229205_340261"
      ],
      "values": [],
      "rangeValue": null
    }
  ],
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>Stan: Nowy</p><p>Faktura: Nie wystawiam faktury</p><p>Marka: inna (MER-SHOP)</p><p>Kod producenta: MER210001</p>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/11d2ef/cc1d536d4e9bb0420254fe02054a"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/11582e/59a52afb46118d6de18de424a219"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/11a2b7/fb1928974bed9a687352dddee409"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/11049c/d7ce12944b04aa118bf7fae2be45"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/11196f/d647520a4f08b27bcf1f78ba2ae8"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/11a63e/d55288db4f7dac153c257883686a"
          }
        ]
      }
    ]
  },
  "compatibilityList": null,
  "tax": null,
  "delivery": {
    "shippingRates": {
      "id": "0cefba9c-a4bc-40d3-b26d-1bf53cdbe6ea"
    },
    "handlingTime": "P5D",
    "additionalInfo": null,
    "shipmentDate": null
  },
  "payments": {
    "invoice": "NO_INVOICE"
  },
  "discounts": null,
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "3e958753-cfb8-42db-8ca6-8f38381de758"
    },
    "returnPolicy": {
      "id": "04ac6ce8-3ac3-4c19-a551-75b0da66ce95"
    },
    "warranty": null
  },
  "additionalServices": null,
  "sizeTable": null,
  "fundraisingCampaign": null,
  "location": {
    "countryCode": "CN",
    "province": null,
    "city": "quanzhou",
    "postCode": "362046"
  },
  "attachments": [],
  "b2b": {
    "buyableOnlyByBusiness": false
  },
  "messageToSellerSettings": {
    "mode": "OPTIONAL"
  },
  "language": "pl-PL",
  "product": null,
  "stock": {
    "available": 100,
    "unit": "UNIT"
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "104.98",
      "currency": "PLN"
    },
    "startingPrice": null,
    "minimalPrice": null,
    "netPrice": null
  },
  "images": [
    "https://a.allegroimg.com/original/11842a/203554fa4b06a9c6003f598a182e",
    "https://a.allegroimg.com/original/1127f1/8d393ace4368b239e9bdc8363c0c",
    "https://a.allegroimg.com/original/118ed6/624e54f64fc08f0401bc161eb7bc",
    "https://a.allegroimg.com/original/113a58/0693825d409895d3ed8ee4b36a00",
    "https://a.allegroimg.com/original/114e32/34927ffa47638dc169f4d96ace46",
    "https://a.allegroimg.com/original/11fb7b/16c9f5834306bb78f6046d875050",
    "https://a.allegroimg.com/original/110b3a/8da285ef4cc994d2a16da86a8945",
    "https://a.allegroimg.com/original/11e656/6f1d697942a0a067ef2684bd906a",
    "https://a.allegroimg.com/original/11e492/a5f514ad4ab9b82aa9189f6ab46e",
    "https://a.allegroimg.com/original/11e159/371ce0ae456795e8835dc4361b20",
    "https://a.allegroimg.com/original/1160e2/4b656e584f80971ad6ed3f3bbaf6"
  ]
}

{"errors":[{"code":"GallerySizeException","message":"Unprocessable Entity","details":null,"path":"images","userMessage":"The limit of 16 images has been exceeded."}]}

**Comment by PrzemyslawLukanowski** [comment]
You are uploading different images in the "description" section than in the "images". When you add pictures from those two places, there are 17 images.

**Comment by lanxiaokeng** [comment]
Hello, I bother you again. I didn't fill in Odcien (249513). Why does this prompt appear

{"errors":[{"code":"ConstraintViolationException.DependencyValidator","message":"Dependent parameter Odcień (249513) cannot take values [chamois] when parameter Kolor dominujący (249512) has values [fioletowy]","details":"ConstraintViolationException.DependencyValidator","path":"parameters","userMessage":"Parametr zależny Odcień (249513) nie może przyjąć wartości [chamois], gdy parametr Kolor dominujący (249512) ma wartości [fioletowy]."}]}


https://api.allegro.pl/sale/product-offers

{
  "name": "Shirts Women Striped Flare Sleeve",
  "category": {
    "id": "89521"
  },
  "parameters": [
    {
      "id": "11323",
      "name": "Stan",
      "rangeValue": null,
      "values": [],
      "valuesIds": [
        "11323_1"
      ]
    }
  ],
  "compatibilityList": null,
  "delivery": {
    "shippingRates": {
      "id": "0cefba9c-a4bc-40d3-b26d-1bf53cdbe6ea"
    },
    "handlingTime": "P5D",
    "additionlInfo": null,
    "shipmentDate": null
  },
  "tax": null,
  "payments": {
    "invoice": "NO_INVOICE"
  },
  "discounts": {
    "wholesalePriceList": {
      "id": null
    }
  },
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "3e958753-cfb8-42db-8ca6-8f38381de758",
      "name": "complaints"
    },
    "returnPolicy": {
      "id": "04ac6ce8-3ac3-4c19-a551-75b0da66ce95",
      "name": "returns"
    }
  },
  "additionalServices": null,
  "sizeTable": null,
  "fundraisingCampaign": null,
  "location": {
    "countryCode": "CN",
    "province": null,
    "city": "quanzhou",
    "postCode": "362046"
  },
  "messageToSellerSettings": {
    "mode": "HIDDEN"
  },
  "attachments": null,
  "b2b": {
    "buyableOnlyByBusiness": false
  },
  "language": "pl-PL",
  "product": null,
  "stock": {
    "available": 999,
    "unit": "UNIT"
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "198",
      "currency": "PLN"
    }
  },
  "productSet": [
    {
      "product": {
        "name": "Shirts Women Striped Flare Sleeve",
        "category": {
          "id": "89521"
        },
        "parameters": [
          {
            "id": "7174",
            "name": "Marka",
            "rangeValue": null,
            "values": [],
            "valuesIds": [
              "7174_1707465"
            ]
          },
          {
            "id": "3475",
            "name": "Wiek dziecka",
            "rangeValue": null,
            "values": [],
            "valuesIds": [
              "3475_1"
            ]
          },
          {
            "id": "249512",
            "valuesIds": [
              "249512_1647423"
            ],
            "values": [],
            "rangeValue": null
          },
          {
            "id": "7173",
            "valuesIds": [],
            "values": [
              "0"
            ],
            "rangeValue": null
          },
          {
            "id": "224017",
            "rangeValue": null,
            "values": [
              "4"
            ],
            "valuesIds": []
          }
        ],
        "images": [
          "https://a.allegroimg.com/original/110536/4833878e4b97a6ae1e4c260924ee"
        ]
      },
      "quantity": {
        "value": 1
      }
    }
  ]
}

**Comment by PrzemyslawLukanowski** [comment]
Hello, that's because the "Odcień" is a dependent parameter, and the list of available values depends on the value you have chosen in the "Kolor dominujący" parameter. In the `options.dependsOnParameterId` field you can see the ID of the parameter on which the possible values are dependent. In the `dependsOnValueIds` field, we return the value from "Kolor dominujący" parameter that you should choose to be able to select the given value. You can read more about these fields [here](https://developer.allegro.pl/news/new-fields-for-dependent-parameters-oA6jyygxGTx).

**Comment by lanxiaokeng** [comment]
Hello, why attribute 451 is not allowed

https://api.allegro.pl/sale/offer-variants

{"errors":[{"code":"VARIANT_ATTRIBUTE_NOT_ALLOWED_IN_CATEGORY","message":"Łączenie ofert po parametrze 451 jest zablokowane w kategorii 78719.","details":null,"path":null,"userMessage":"Łączenie ofert po parametrze 451 jest zablokowane w kategorii 78719."}]}

{
  "offers": [
    {
      "id": "13128003353"
    },
    {
      "id": "13128004209"
    },
    {
      "id": "13128004418"
    },
    {
      "id": "13128004919"
    },
    {
      "id": "13128005277"
    },
    {
      "id": "13128005519"
    },
    {
      "id": "13128005772"
    },
    {
      "id": "13128005903"
    },
    {
      "id": "13128005970"
    },
    {
      "id": "13128006043"
    },
    {
      "id": "13128006158"
    },
    {
      "id": "13128006212"
    }
  ],
  "name": "BODY damskie WYSZCZUPLAJĄCE brzuch GORSET majtki",
  "parameters": [
    {
      "id": "451"
    },
    {
      "id": "54"
    }
  ]
}

**Comment by lanxiaokeng** [comment]
Hello, why attribute 451 is not allowed

https://api.allegro.pl/sale/offer-variants

{"errors":[{"code":"VARIANT_ATTRIBUTE_NOT_ALLOWED_IN_CATEGORY","message":"Łączenie ofert po parametrze 451 jest zablokowane w kategorii 78719.","details":null,"path":null,"userMessage":"Łączenie ofert po parametrze 451 jest zablokowane w kategorii 78719."}]}

{
  "offers": [
    {
      "id": "13128003353"
    },
    {
      "id": "13128004209"
    },
    {
      "id": "13128004418"
    },
    {
      "id": "13128004919"
    },
    {
      "id": "13128005277"
    },
    {
      "id": "13128005519"
    },
    {
      "id": "13128005772"
    },
    {
      "id": "13128005903"
    },
    {
      "id": "13128005970"
    },
    {
      "id": "13128006043"
    },
    {
      "id": "13128006158"
    },
    {
      "id": "13128006212"
    }
  ],
  "name": "BODY damskie WYSZCZUPLAJĄCE brzuch GORSET majtki",
  "parameters": [
    {
      "id": "451"
    },
    {
      "id": "54"
    }
  ]
}

**Comment by PrzemyslawLukanowski** [comment]
Information about parameters that can be used for creating other variants is returned in the [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2) in the options.variantsAllowed field:

<img width="605" alt="Zrzut ekranu 2023-01-12 o 07 52 38" src="https://user-images.githubusercontent.com/51473661/211997764-406d58af-8c0f-48bc-b36a-29e12c25beee.png">

**Comment by lanxiaokeng** [comment]
![image](https://user-images.githubusercontent.com/121671640/212243036-adf4fc17-836d-4712-9d22-ec13ffe1af7e.png)


Excuse me, where does the commandId need to be obtained

**Comment by MaciejFrackowiak** [comment]
You have to generate it automatically on your own - there are several websites which will help you.
