### ISSUE TITLE
Podany punkt jest obecnie niedostępny - Allegro One Punkt

### ISSUE THREAD

**Issue by polenquick** [allegro/allegro-api#6546]
cześć, mamy problem z nadaniem przez Wysyłam z Allegro One Punkt 
trace-id: 8436019dc069c981
ERROR","errors":[{"code":"ERROR","message":"Specified point is not available"

Punkt jest przeciążony, w remoncie, czy może go w ogóle nie ma? Uderzać z tym do Was, czy bezpośrednio do Kolportera w tym przypadku? Na mapie https://allegro.pl/kampania/one/znajdz-nas filtr nie uwzględnia tego punktu

**Comment by MaciejFrackowiak** [comment]
Dostępność punktów zmienia się w zależności m.in. od ilości otrzymywanych przesyłek. Jak widzę jest to transakcja z 19.12.2022, zatem wówczas punkt mógł być dostępny. Co więcej, jak widzę przesyłka do wspomnianej transakcji została nadana 20.12.2022.

**Comment by polenquick** [comment]
Jak najbardziej się to zgadza, bo akurat ten Klient ma mieć dosłaną kolejną paczkę. Na własną rękę można uderzyć bezpośrednio do tego punktu/Kolportera, czy cierpliwie czekać i może kiedyś automatycznie wspomniany punkt pojawi się jako dostępny? Czasami komunikacja z Klientami jest bardzo uciążliwa, aby doprosić się ich o możliwość nadania pod inny adres ;d

**Comment by MaciejFrackowiak** [comment]
Oczywiście jest to możliwe, że punkt powróci, tylko niestety nie znamy takiej daty - jest to generalnie niezależne od nas. Najprostszym rozwiązaniem jest wybranie alternatywnego punktu, dostępnego obecnie, ale jak wspominacie niekiedy ciężko taką alternatywę otrzymać od klienta.
