### ISSUE TITLE
Brak możliwości poprawnego stworzenia "Wystaw podobną ofertę" w sale/product-offers jeśli oferta ma swoje zdjęcie

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#6547]
Występuje problem: 
 - [x]  z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

Chciałbym przypomnieć się z #6339. Powtórzę o co chodzi: jeśli oferta ma tylko swoje zdjęcie to wciąż po odczytaniu oferty przez GET /sale/product-offers i wykorzystaniu odpowiedzi do zbudowania POST /sale/product-offers otrzymuję nową ofertę ale z dwoma zdjęciami: zdjęciem z kopiowanej oferty oraz ze zdjęciem produktowym. Nie powinno się dokładać zdjęcie produktowe.

Jeśli tak samo jest na produkcji to w tej chwili nie mamy możliwości poprawnego stworzenia funkcjonalności "Wystaw podobną ofertę". Chcemy wg zaleceń przejść na /sale/product-offers jak najszybciej ale w takiej sytuacji nie jest to możliwe.

Kiedy możemy się spodziewać poprawnie działającego GET-POST /sale/product-offers?

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale na tę chwilę nie ustaliliśmy jeszcze dalszych kroków. Jak tylko będę znał decyzję i przybliżony termin, poinformuję o tym w wątkach. Chciałbym jeszcze tylko dopytać, z czego wynika, że użytkownik chciałby wystawić drugi raz ofertę z tym samym produktem? Czy chce wystawić w tej samej kategorii czy innej? Z założenia chcemy ograniczyć duplikaty, tak aby dla jednego produktu sprzedawca posiadał wystawioną jedną ofertę.

**Comment by FromAnyHole** [comment]
...jasne, jasne - z założenia to chcecie kasować opłaty utrzymaniowe!! Wykrakałem 5 lat temu ;-)

**Comment by FromAnyHole** [comment]
Kiedy ktoś pisze prawdę, to kasujecie wpisy?? Co za jazda...

**Comment by PrzemyslawLukanowski** [comment]
Twój komentarz został usunięty, ponieważ narusza [zasady korzystania z forum](https://github.com/allegro/allegro-api), a dokładnie:

> Zabrania się zamieszczania postów (...) w szczególności zabrania się umieszczania treści, które:
nie mają związku z tematyką dyskusji prowadzonych w ramach forum,
...

Zapoznaj się proszę z informacjami, które zawarliśmy w dokumencie. Aby zachować czytelność, usunę nasze wpisy, które nie mają związku z poruszonym problemem.

**Comment by tomylee0** [comment]
Użytkownik chciałby mieć taką samą funkcjonalność "Wystaw podobną" jaka istnieje w panelu administrcyjnym www:

![image](https://user-images.githubusercontent.com/48419261/210539830-d85076cc-adc7-4486-bf7a-ea999dfcab17.png)
