### ISSUE TITLE
Informacja o rozliczeniu VAT przez platformę w API 

### ISSUE THREAD

**Issue by mikolaj-bronk** [allegro/allegro-api#6548]
Dzień dobry, mam 2 pytania:

W jaki sposób możemy się dowiedzieć w API czy podatek VAT został rozliczony przez platformę w przypadku, gdy sprzedawca jest zagraniczny spoza UE (obsługa tzw. Deemed Supplier)?

Przy okazji drugie pytanie trochę niezwiązane, ale zapytam: czy jest jakaś globalna statystyka nietajna ile średnio procent zgłoszonych zwrotów jest odrzucanych przez sprzedawców?

**Comment by AureliuszBrussy** [comment]
Cała kwota za towar wpłacona przez kupującego przy takiej transakcji trafi na konto sprzedającego w [Allegro Finanse](https://allegro.pl/moje-allegro/sprzedaz/srodki-i-historia-operacji#!/). Podatek z tytułu pakietu eCommerce VAT rozliczymy poprzez billing ― odpowiednią kwotę doliczymy w zakładce [Rozliczenia z Allegro](https://allegro.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro). Sprzedający rozliczenie to zobaczy także na wystawianych przez nas co miesiąc fakturach.

W API naliczenia na bilingu odczytasz za pomocą [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries). Więcej o zasobie przeczytasz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-sprawdzic-oplaty-nn9DOL5PASX#historia-operacji-billingowych).

Co do statystyk - nie jest to temat powiązany bezpośrednio z publicznym API Allegro. Pytania dotyczące spraw niepowiązanych z naszym API możesz kierować w [formularzu kontatkowym](https://allegro.pl/pomoc/kontakt).

**Comment by mikolaj-bronk** [comment]
Czy to oznacza, że do sprzedającego trafia kwota netto?

**Comment by AureliuszBrussy** [comment]
Na konto Allegro Finanse do sprzedającego trafi kwota brutto, a podatek zostanie rozliczony na bilingu.
