### ISSUE TITLE
CallBack do systemu sprzedawcy po sprzedaży przedmiotu?

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#655]
Dzień dobry 

Czy istnieje taka możliwość ? Czy macie coś takiego w planach ?
Ogólnie problem dotyczy informacji zwrotnej od was (allegro) do systemu sprzedawcy po sprzedaży przedmiotu np via web service lub innych zasobach zdalnych? 

wwwfactory

**Comment by MarcinLuczak** [comment]
@wwwfactory nie ma obecnie takiej możliwości. Trudno mi powiedzieć, czy jest to w dalszych planach. Obecnie dzienniki pozwalają na pobranie informacji o sprzedaży - zapoznaj się z tym artykułem https://developer.allegro.pl/orders/

**Comment by wwwfactory** [comment]
Dziękuję - to znamy. Pytanie dotyczyło konkretnego zachowania 'w drugą stronę'.
Zamykamy.
