### ISSUE TITLE
Komunikat o braku parametru przy wystawianiu oferty, a parametr jest.

### ISSUE THREAD

**Issue by arkwlcz** [allegro/allegro-api#6551]
Dzień dobry.

Podczas wystawiania oferty połączonej z produktem otrzymujemy komunikat, że nie jest podany parametr:
`Producent części - 247835`

Tymczasem w produkcie owy parametr występuje, o takiej samej nazwie, ale innym numerze:
`FID - 127415`.

Czyli podsumowując, oferta jest połączona z produktem, który posiada parametr producent części (**127415**), kategoria do której chcemy wystawić ofertę również posiada ten parametr tożsamy z tym przydzielonym do produktu (**127415**), ale API i tak domaga się tego parametru o innym ID (**247835**).

Trace ID przykładowego requestu, który zwraca błąd:
`8356b5536fb67945`

Ten problem uniemożliwia nam wystawienie oferty. Z informacji jakie mi przekazano, nie jest to jednostkowa sytuacja.

Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
Poszczególne kategorie mogą różnić się id parametru, mimo, że jego nazwa jest taka sama. Lista dostępnych wartości słownikowych może jednak być zupełnie inna. Nie jest to błąd. Pozostaje uzupełnienie wymaganego parametru. 

Możesz pobrać listę uzupełnionych w produkcie parametrów w kontekście danej kategorii podobnej. Zrobisz to za pomocą odpowiednio sparametryzowanego żądania: [GET ​/sale​/products​/{productId}?category.id={similarCategoryId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct).
