### ISSUE TITLE
Naliczenie opłaty od nieaktywnej oferty

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#6552]
Witam,

1) kiedy w zasobie pricing/offer-quotes po wystawieniu oferty, można spodziewać się wpisu z typem INEFFECTIVE_LISTING_FEE?,  czy pojawi się po pół roku, po 360 dniach? ile maksymalnie dni przed zamknięciem oferty pojawi się wpis? dla nowych ofert endpoint nie zwraca takiej informacji. 

2) Jeżeli system powinien naliczyć opłatę jutro, lecz dzisiaj pojawi się zamówienie na ofertę, wtedy wpis z w/w endpointu zostanie usunięty dla tej oferty, czy data naliczenia opłaty "nextDate" zostanie przesunięta o rok?

3) czy jest inny zasób, za pomocą którego, będzie możliwe sprawdzenie wyłącznie opłaty dla danej oferty z typem INEFFECTIVE_LISTING_FEE?

4) co jaki czas aktualizowany jest stan wpisu INEFFECTIVE_LISTING_FEE? co 10 dni? _(powiązane z punktem drugim)_

5) za pomocą którego zasobu, najlepiej pobrać informację o ostatniej transakcji dla danej oferty?

6) czy anulowanie zamówienia/transakcji ma wpływ na naliczenie opłaty utrzymaniowej?

7) czy aktualizacja zamówienia (np. próba ponowej opłaty, zmiana danych) ma wpływ na naliczenie opłaty utrzymaniowej?

**Comment by AureliuszBrussy** [comment]
Opłata utrzymaniowa dotyczy ofert w których przez ostatnie 365 dni nie doszło do żadnego zakupu. Później jest naliczana co 10 dni, do momentu, aż w ofercie dojdzie do zakupu lub zostanie ona zakończona przez sprzedającego. Po każdej sprzedaży czas (365 dni) odliczamy od nowa.

Ad 1. Zasób **/pricing/offer-quotes** zwraca informacje o najbliższych opłatach w 10 dniowym cyklu. Wpis z typem INEFFECTIVE_LISTING_FEE pojawi się dopiero, gdy opłata ma zostać naliczona w następnym cyklu. 


Ad 3. Nie ma takiego zasobu - na **/pricing/offer-quotes** nie udostępniamy możliwości filtrowania po typie opłaty.

Ad 5. W API nie zwracamy daty ostatniego zakupu w ofercie. Jeśli chcesz posiadać taką informację to możesz we własnym zakresie zapisywać datę ostatniej sprzedaży w danej ofercie i względem niej obliczać 365 dni do naliczania opłaty utrzymaniowej.

Jeżeli chodzi o pytania nr 2, 4, 6 i 7- potwierdzam to jeszcze z zespołem odpowiedzialnym za ten zasób. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Wraca z pozostałymi odpowiedziami:

Ad. 2. W przypadku zakupu wpis dla takiej oferty po prostu zniknie.

Ad. 4. Cykl trwa 10 dni, natomiast tak jak wspominam w punkcie wyżej - w przypadku jakiejś zmiany wypisy mogą znikać na bieżąco. 

Ad. 6. Anulowanie zamówienia nie ma wpływu na naliczanie opłaty utrzymaniowej. 

Ad. 7. Aktualizacja zamówienia nie ma wypływu na naliczanie opłaty utrzymaniowej.

**Comment by vitapak** [comment]
https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET

Czy ostatnia data transakcji, od której liczone jest 365 dni, jest równoznaczna z pierwszym wystąpieniem eventu dla danego zamówienia: BOUGHT, FILLED_IN, albo READY_FOR_PROCESSING?

**Comment by AureliuszBrussy** [comment]
Wystarczy, że zamówienie znajdzie się w statusie BOUGHT (lub dowolnym innym statusie). Datę zakupu przedmiotu znajdziesz w polu **lineItems[].boughtAt** w zamówieniu.

**Comment by vitapak** [comment]
@AureliuszBrussy czy nie myśleliście aby dodać nowy zasób, który zwróci listę opłat, które niedługo zostaną naliczone, niezależnie od oferty? klienci API nie musieliby odpytywać periodycznie wszystkich ofert :) 

Już samo zwiększenie limitu 20 -> 1000* byłoby połąwą sukcesu :)

**Comment by AureliuszBrussy** [comment]
@vitapak aktualnie nie mamy w planach wdrożenia takiego zasobu. W zakładce [Discussions](https://github.com/allegro/allegro-api/discussions) możesz założyć wątek ze swoją sugestią - inni użytkownicy ją zobaczą i będą mogli głosować.
