### ISSUE TITLE
Problem z prawidłowym formatem etykiety PDF / AllegroSandbox

### ISSUE THREAD

**Issue by rafciozarzecz** [allegro/allegro-api#6553]
Mam problem przy tworzeniu etykiety PDF listu kurierskiego. Na zasobie wskazuję format A6, a etykieta i tak tworzy się w formacie A4. Wcześniej nie występował ten problem.

Zasób, z którego korzystam:
https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcels/label?parcelId=123456&pageFormat=A6

**Comment by AureliuszBrussy** [comment]
Abym mógł to wyjaśnić, podaj proszę trace-id swojego wywołania. Trace-id znajdziesz w nagłówku naszego response'a.

**Comment by rafciozarzecz** [comment]
Dzięki za pomoc. Znalazłem problem po swojej stronie.
