### ISSUE TITLE
Problem z dostępem do API

### ISSUE THREAD

**Issue by slodki1997** [allegro/allegro-api#6554]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam,
w momencie logowania za pomocą doLoginWithAccessToken dostaję informację, że "Żądanie nie powiodło się. Odpowiedź żądania jest pusta". Sytuacja ta pojawiła się od 01.01.2023 r. i trwa do teraz. Bardzo proszę o szybką odpowiedź i wskazania drogi do rozwiązania problemu.

**Comment by slodki1997** [comment]
Mówimy to o Web Reference: https://webapi.allegro.pl/service.php?wsdl

Czy rzeczywiście to zostało wyłączone dopiero teraz? W podanym przez Państwa linku jest informacja o datach z roku 2020, a dziś mamy początek 2023 roku.

**Comment by AureliuszBrussy** [comment]
Jestem w trakcie wyjaśniania tej sytuacji. Tak jak wspominamy w komunikacie, zasób powinien nie być dostępny już od 2020 roku.

**Comment by slodki1997** [comment]
Dzień dobry,

czy wiadomo już coś w sprawie?

**Comment by AureliuszBrussy** [comment]
Jeszcze to sprawdzamy. Gdy tylko wszystko ustalę, wrócę do Ciebie z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Zasób doLoginWithAccessToken służył do uzyskiwania tokena dostępowego do webAPI. Zasoby webAPI Allegro są już od 2020 roku wyłączone - token wygenerowany w ramach tej usługi był nieużywalny. 

Aktualnie możesz swobodnie korzystać z funkcjonalności, które udostępniamy w [ramach REST API](https://developer.allegro.pl/documentation).
