### ISSUE TITLE
Temat REST API Allegro - Nie mogę aktywować konta

### ISSUE THREAD

**Issue by pawello32** [allegro/allegro-api#6555]
Witam
Rozpocząłem temat na Allegro Gadane, ale jeszcze nie uzyskałem pełnej odpowiedzi
Temat jest tutaj
https://spolecznosc.allegro.pl/t5/zaawansowani-sprzedawcy/temat-rest-api-allegro-nie-mog%C4%99-aktywowa%C4%87-konta/td-p/498026

Jak mógłbym uzyskać login użytkownika Allegro po odszyfrowaniu tokena korzystając ze strony https://jwt.io/ bo taka jest sugestia na forum. Tylko tak da się odszyfrować token? Chciałbym się też zweryfikować na tym koncie frodo38. Ono jest na allegro testowym. Czy muszę mieć dwa konta do testów? Jedno sprzedaje drugie kupuje.

Nie mogę przejść dalej na tej stronie do weryfikacji https://allegro.pl.allegrosandbox.pl/myaccount/FillData.php?fromCode=1

**Comment by PrzemyslawLukanowski** [comment]
> Tylko tak da się odszyfrować token? 

Posiadając token użytkownika, możesz także wykonać request do [GET /me](https://developer.allegro.pl/documentation#operation/meGET) - w odpowiedzi zwrócimy dane użytkownika, w tym jego login.

> Czy muszę mieć dwa konta do testów? Jedno sprzedaje drugie kupuje.

Tak, musisz utworzyć także konto kupującego, ponieważ jako sprzedawca nie możesz kupować w swoich ofertach.

> Chciałbym się też zweryfikować na tym koncie frodo38. (...) Nie mogę przejść dalej na tej stronie do weryfikacji https://allegro.pl.allegrosandbox.pl/myaccount/FillData.php?fromCode=1

Na tę chwilę nie mamy w naszej bazie takiego użytkownika, dlatego nie możemy go aktywować. Czy mógłbyś podać nam więcej szczegółów na temat tego błędu? W którym dokładnie momencie ma to miejsce, czy problem występuje na innych przeglądarkach i po wyczyszczeniu ciasteczek? Pomocny dla nas będzie także zrzut ekranu z ew. błędem.

**Comment by pawello32** [comment]
@PrzemyslawLukanowski 
Wrzucam zrzut ekranu https://chomikuj.pl/frodo_/Allegro+testowe - można go pobrać
Tym loginem frodo38 się loguje więc jest on dodany. To jest na koncie testowym e-mail to biore_to@wp.pl
Na stronie do weryfikacji (zrzut ekranu na chomiku) jest formularz. Po wypełnieniu jego i przyciśnięciu przycisku dane znikają i nie dzieje się później nic. Nie ma przekierowania dalej.

**Comment by pawello32** [comment]
To występuje na Chrome i Firefoxe na innych nie sprawdzałem, ale to chyba nie zależy od przeglądarki. Przeglądarki są wyczyszczone.

**Comment by PrzemyslawLukanowski** [comment]
Ta strona nie jest już przez nas wspierana. Czy mógłbyś podzielić się informacją, jak na nią trafiłeś? Wejdź proszę w zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta), w której możesz uzupełnić te informacje. W zakładce "[Moje konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto)" powinieneś widzieć "krokowiec" z listą kroków niezbędnych do wykonania, aby konto aktywować i zweryfikować .

**Comment by pawello32** [comment]
Ja właśnie tam wchodzę. W dane konta > aktywuj sprzedaż. Pojawia się ten formularz. Czy mogę usunąć to konto i ponownie wszystko ustawić? Będę musiał jeszcze jedno takie ustawić.
--
Wysłano z aplikacji myMail dla Androida czwartek, 05 stycznia 2023, 09:44AM +01:00 od PrzemyslawLukanowski  ***@***.*** :

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za informację, przenalizujemy to po naszej stronie. Tak, załóż proszę nowe nowe konto, a to pozostanie nieaktywne i niezweryfikowane, niestety nie mamy możliwości usunięcia.

**Comment by pawello32** [comment]
Na nowym koncie założonym 6 dni temu jest jeszcze gorzej. Wrzucam zrzut ekranu zrzut_ekranu2.png tutaj https://chomikuj.pl/frodo_/Allegro+testowe
Na ekranie pojawia się
"Ta strona nie działa
Strona allegro.pl.allegrosandbox.pl spowodowała zbyt wiele przekierowań."
Dobra sprawdzam na nowym koncie

**Comment by PrzemyslawLukanowski** [comment]
Dziękuje, analizuję sytuację z zespołem odpowiedzialnym za proces rejestracji. Przepraszam za niedogodności.

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz jeszcze napisać, czy konta są firmowe czy zwykłe?

**Comment by pawello32** [comment]
To zwykłe konta

**Comment by pawello32** [comment]
Nie można przejść na stronę "Aktywuj sprzedaż" Czasem się pojawia taki ekran z błędem
Nie możemy wyświetlić strony

Spróbuj jeszcze raz. Identyfikator błędu: 4df1cf0adfb9f68
Internal Server Error 500
Timestamp: Thu Jan 05 11:56:02 CET 2023
Request path: /login/auth
Query string: origin_url=https%3A%2F%2Fallegro.pl.allegrosandbox.pl%2FCodeForm.php&qstate=eyJyZXF1ZXN0IjoiXC9Db2RlRm9ybS5waHAiLCJ1cmxQcmVmaXgiOiJodHRwczpcL1wvYWxsZWdyby5wbC5hbGxlZ3Jvc2FuZGJveC5wbCIsImNvYnJhbmRJZCI6MCwiZ3Vlc3QiOltdfQ%3D%3D
Message: 400 Bad Request: [{"error":"invalid_token","error_description":"Token was not recognised"}]
Trace ID: 4df1cf0adfb9f68


Dodatkowo nie przychodzą smsy. Chciałem zapisać nr telefonu albo właczyć dwustopniowe logowanie i nie mogę

**Comment by pawello32** [comment]
@PrzemyslawLukanowski 
Sprawdziłem na drugim komputerze bo może mam coś namieszane, ale to samo...

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za kolejne informacje, sprawdzimy to. Co do smsów, to na środowisku Sandbox nie wysyłamy ich, do włączenia dwustopniowego logowania wpisz proszę 12345, a przy logowaniu 123456.

**Comment by PrzemyslawLukanowski** [comment]
Czy uzupełniłeś imię i nazwisko, adres zamieszkania i dopiero wtedy próbujesz aktywować sprzedaż? Natomiast do samego zakupu nie potrzebujesz pełnej aktywacji konta, komunikat na stronie wprowadza w błąd.

**Comment by pawello32** [comment]
Nie wiem skąd te problemy. Powinny pokazać się jakieś komunikaty że coś nie wypełniłem. Tak adres wprowadziłem i imię i nazwisko. Spróbuję ustawiać to na normalnym koncie nie testowym.

**Comment by PrzemyslawLukanowski** [comment]
Prawdopodobnie token uzyskałeś w ramach autoryzacji client_credentials, która nie posiada kontekstu użytkownika. Aby skorzystać z tego zasobu, jak i większości innych, musisz wygenerować token za pomocą autoryzacji [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow). W naszej [dokumentacji](https://developer.allegro.pl/documentation) znajdziesz odpowiednie oznaczenia: 
 - bearer-token-for-user przy zasobie oznacza autoryzacje code lub device;
 - bearer-token-for-application - client_credentials.
