### ISSUE TITLE
Wyczyszczenie sekcji "Pasuje do"

### ISSUE THREAD

**Issue by PSchelenz** [allegro/allegro-api#6556]
Czy za pomocą API jest możliwość wyczyszczenia listy "Pasuje do" w ofercie, tak żeby nie posiadała żadnego dopasowania? Nie można wysyłać pustej listy (zwracany jest błąd, że lista powinna posiadać między 1-2000 dopasowań) i póki co jedynym sposobem, jaki przyszedł mi do głowy jest wysłanie pojedynczego dopasowania i usunięcie tego jednego dopasowania ręcznie, co wydaje się być dość mozolne.

**Comment by PrzemyslawLukanowski** [comment]
Tak, możesz usunąć wszystkie pozycje, przekazując wartość null w polu "compatibilityList".

**Comment by PSchelenz** [comment]
Dziękuję za informację.
