### ISSUE TITLE
Brak etykiet One Fulfillment

### ISSUE THREAD

**Issue by LukaszWypych** [allegro/allegro-api#6557]
Witam,
generuje etykiety przy pomocy metody 'createLabelsCommand', ale później próbując pobrać wynik za pomocą 'getLabelCommand' otrzymuje status 'SUCCESSFUL' ale url z etykietami jest pusty. Dodam tylko, że przy pobraniu awiza poprzez 'getAdvanceShipNotice' url ten jest widoczny.

Sytuacja ma miejsce na środowisku sandbox. Na produkcji nie testowałem.

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać nam trace-id jednej z operacji, które wykonujesz? Pozwoli nam to zweryfikować opisaną przez Ciebie sytuację.

**Comment by PrzemyslawLukanowski** [comment]
Jeśli ID Twojej aplikacji to (xxx)66dc3 to widzę, że w każdym przypadku wywołania GET /fulfillment/create-labels-commands/0e343503-69a5-4f26-8bcf-30b0deb5580b url w polu `fileUrl` był widoczny. Będę zatem wdzięczny za trace-id wywołania, gdzie to pole zwróciliśmy puste.

**Comment by LukaszWypych** [comment]
trace-id=[574eec268bba387]

**Comment by PrzemyslawLukanowski** [comment]
Zasób działa asynchronicznie, dlatego ostateczny status oraz link do etykiet zwrócimy dopiero dla metody GET. Czy po powtórzeniu wywołania dla GET link nadal jest niewidoczny? Pytam, ponieważ wg naszych logów powinniśmy zwrócić adres https://api.allegro.pl.allegrosandbox.pl/fulfillment/advance-ship-notices/0ba75029-fd40-497d-a1e2-9ab2c40cd751/labels

**Comment by LukaszWypych** [comment]
Drugi trace, który podałem (5c075fdefbaf1652) był dla metody GET i w nim też to pole było puste

**Comment by LukaszWypych** [comment]
Tak

**Comment by PrzemyslawLukanowski** [comment]
Zbadam tę sytuację z zespołem odpowiedzialnym za One Fulfillment i wrócę z informacją.

**Comment by LukaszWypych** [comment]
> Zasób działa asynchronicznie, dlatego ostateczny status oraz link do etykiet zwrócimy dopiero dla metody GET. Czy po powtórzeniu wywołania dla GET link nadal jest niewidoczny? Pytam, ponieważ wg naszych logów powinniśmy zwrócić adres https://api.allegro.pl.allegrosandbox.pl/fulfillment/advance-ship-notices/0ba75029-fd40-497d-a1e2-9ab2c40cd751/labels

Czyli docelowo pomimo uzyskania statusu SUCCESSFUL w odpowiedzi na metodę PUT(createLabelsCommand), pole z etykietą zawsze będzie puste i muszę pobrać je za pomocą GET?

**Comment by PrzemyslawLukanowski** [comment]
Przeanalizowałem tę sytuację z zespołem odpowiedzialnym za One Fulfillment, ale również nie udało nam się stwierdzić błędów - widzimy, że adres w fileUrl jest uzupełniony w przypadku obu metod. Czy mógłbyś ponowić requesty i w przypadku kolejnych brakujących odpowiedzi, wkleić nam tutaj odpowiedź HTTP, wraz z trace id i zwróconą strukturą?

**Comment by PrzemyslawLukanowski** [comment]
@LukaszWypych W styczniu/lutym planujemy wprowadzić kilka zmian w obsłudze procesów One Fulfillment w API. Myślę, że dobrym pomysłem będzie, jeśli do tego czasu wstrzymasz się jeszcze z integracją. O wszelkich zmianach poinformujemy zarówno na naszej stronie, jak i na forum.

**Comment by LukaszWypych** [comment]
Rozumiem, w takim razie wstrzymam się z dokończeniem integracji. 
A co do pola fileUrl to znalazłem przyczynę. W pliku yaml struktura odpowiedzi wygląda tak:
`
CreateLabelsSuccessfulCommandOutput:
      allOf:
        - $ref: '#/components/schemas/CreateLabelsCommandOutput'
        - type: object
          required:
            - fileUrl
          properties:
            status:
              type: string
              default: 'SUCCESSFUL'
            fileUrl:
              type: string
              description: URL to download file with created labels.
              example: 'https://api.allegro.pl/fulfillment/advance-ship-notices/cc05cce0-3f6a-4f13-9c28-ea0d01faea86/labels'
`
Wygląda to jakby pole fileUrl było na tym samym poziomie co status, a w rzeczywistości to pole opakowane jest jeszcze w obiekt "labels", dlatego mój model miał to pole puste.
