### ISSUE TITLE
Dozwolone znaczniki HTML

### ISSUE THREAD

**Issue by GHalbt** [allegro/allegro-api#6559]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Odpowiedź API przy dodawaniu produktu z własnym opisem:
`VALIDATION_ERROR, Invalid tag: "b", allowed tags: {h1, h2, p, ul, ol}`

Odpowiedź konsultanta Allegro:
`Można korzystać z poniższych znaczników: h1 - tytuł h2 - podtytuł p - akapit ul - wypunktowanie ol -
wylistowanie li - element listy b - pogrubienie.`

**Comment by asoio** [comment]
Zobacz ten wątek: https://github.com/allegro/allegro-api/issues/5927

**Comment by PrzemyslawLukanowski** [comment]
Tak jak wspomniała w przytoczonym wątku @asoio - wspieramy znacznik pogrubienia, jednak w Twoim przypadku, najprawdopodobniej jest on osadzony w nieprawidłowym miejscu.
