### ISSUE TITLE
doAddPackageInfoToPostBuyForm Sandbox oraz Prod - problem z parametrem sessionId

### ISSUE THREAD

**Issue by hYOUstone** [allegro/allegro-api#656]
Mam problem z poprawnym wysłaniem parametrów do w/w funkcji... Przykładowe dane wysyłane:
Array
(
    [sessionId] => 939ed037f882978cc75475bb053bd87fb5cc8d79155a17//01_1
    [transactionId] => 727895966
    [packageInfo] => Array
        (
            [0] => Array
                (
                    [operatorId] => 4
                    [packageId] => 90005042768
                    [operatorName] => 
                )
        )
)

Funkcja zwraca mi caly czas blad:
ERR_NO_SESSION: Błędny identyfikator sesji. Proszę spróbować zalogować się jeszcze raz!
Ten sam błąd dotyczy również funkcji doGetTransactionsIDs().
Kombinowałem już na różne sposoby...

Co ciekawe gdy pukam do metody doGetMyData i używam linijkę wcześniej tego samego identyfikatora sessji metoda zwraca mi prawidłowo dane mojego użytkownika. Błąd występuje mi i na sandboxie i na wersji produkcyjnej API 

Adres do API jakiego używam (dla sandbox'a) to:
https://webapi.allegro.pl.allegrosandbox.pl/uploader.php?wsdl
...Gdy używam https://webapi.allegro.pl.allegrosandbox.pl/service.php?wsdl system, który mamy już zaprogramowany przestaje działać. 
Czy za błąd odpowiadać może url (...)uploader.php? Zmiany w systemie byłyby kolosalne gdybym musiał użyć (...)service.php. Może skoro to co mamy już zrobione na uploader.php (i działa) może działać dla w/w funkcji.
HELP

**Comment by MarcinLuczak** [comment]
@hYOUstone jedyny WSDL dla środowiska testowego, jaki wspieramy, to ten - https://webapi.allegro.pl.allegrosandbox.pl/service.php?wsdl

Trudno mi powiedzieć, czy to z jego powodu występują problemy, które opisałeś, ale nie mogę tego wykluczyć.

Upewnij się też, że dodajesz prawidłowo sessionId do każdej z metod (nie ma żadnych spacji czy nieprawidłowych znaków) oraz że każdą metodę wywołujesz z tego samo IP, na którym utworzyłeś daną sesję.

**Comment by hYOUstone** [comment]
Postanowiłem głębiej to potestować i problem rozwiązałem sam... Faktycznie należy używać url'a https://webapi.allegro.pl.allegrosandbox.pl/service.php?wsdl. Końcówka uploads nie działa z niektórymi funkcjami API. Niestety muszę dokonać większej ilości zmian tak jak podejrzewałem. Dziękuję za odpowiedź. Zamykam temat.
