### ISSUE TITLE
Brak numerów ofert w zasobie "GET /sale/offers/unfilled-parameters"

### ISSUE THREAD

**Issue by damol9** [allegro/allegro-api#6561]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Po wywołaniu zasobu ```GET /sale/offers/unfilled-parameters``` na środowisku produkcyjnym:
```https://api.allegro.pl/sale/offers/unfilled-parameters?limit=100&offset=0&parameterType=REQUIRED```
Otrzymuję odpowiedź bez żadnych numerów ofert, mimo że "totalCount" wskazuje że jest ich 67:
```
{
    "offers": [],
    "count": 0,
    "totalCount": 67
}
```
Limit jest ustawiony na 100, a offset 0, więc teoretycznie numery ofert powinny pojawić się w odpowiedzi
Trace-id: ```adefe750163c278```

**Comment by AureliuszBrussy** [comment]
Błędnie zwracamy liczbę w **totalCount**. Pracujemy nad poprawką. Wrócę z informacją po wdrożeniu.

**Comment by AureliuszBrussy** [comment]
@damol9 wdrożyliśmy poprawkę, problem nie powinien już wystąpić.
