### ISSUE TITLE
Dzien dobry potrzebuje klucz WebApi dla konta z ktorego pisze ale nie wiem jak go wygenerowac prosze o pomoc sprawa pilna

### ISSUE THREAD

**Issue by MiloszMiki** [allegro/allegro-api#6562]

**Comment by hahyes** [comment]
Jeżeli chodzi o WSDL, ono już zostało wyłączone dawno temu.

**Comment by AureliuszBrussy** [comment]
WebAPI nie jest przez nas wspierane i zostało wyłączone. Aktualnie udostępniamy REST API - więcej o generowaniu klucza oraz dostępnie przeczytasz w [naszym poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR).
