### ISSUE TITLE
Twoje konto przekroczyło maksymalną liczbę 20000 szkiców - liczba szkiców tyle nie wynosi.

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#6563]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam,

podczas wystawiania aukcji natrafiam na błąd:

```
Nie możesz utworzyć nowych szkiców - Twoje konto przekroczyło maksymalną liczbę 20000 szkiców.
```

Jednakże sprawdzam ilość nowych szkiców i jest ich obecnie na koncie dokładnie 13608. Dlaczego wyrzucany jest ten błąd, kiedy nie przekroczono liczby szkiców? 

Nie mam trace-id, więc podaje ID klienta: 87930495

EDIT: Dodam, że aktualnie sprzątam te szkice jednakże błąd już wystąpił 2 razy.

**Comment by AureliuszBrussy** [comment]
Poprawiliśmy to dla tego użytkownika, błąd nie powinien już wystąpić.

**Comment by hahyes** [comment]
Dziękuję.
