### ISSUE TITLE
/sale/offers/unfilled-parameters i parametr Język (2868)

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#6564]
Chciałbym się upewnić, czy zasób /sale/offers/unfilled-parameters działa poprawnie. Gdy szukam ofert z planowanymi obowiązkowymi parametrami (trace-id: 3dcee392fdb7ed46 i kolejne następujące po sobie ze zmieniającym się offset) otrzymuję, że planowany jest obowiązkowy parametr Język (2868) dla większości podkategorii w "Książki i komiksy". 

Sytuacja jest o tyle dla nas nieprzyjemna, że wygląda na to, że w zdecydowanej większości ten parametr nie jest wypełniony w aktualnej bazie produktowej Allegro. To spowoduje, że nagle nie będzie możliwości zmiany ilości, ceny ani wznowienia prawie żadnej oferty z kategorii książkowej.

Stąd moja prośba o potwierdzenie, czy faktycznie zasób /sale/offers/unfilled-parameters zwrócił prawidłową odpowiedź.

Dzięki z góry.

**Comment by AureliuszBrussy** [comment]
Nie jest to błąd na zasobie - faktycznie planowane jest uobowiązkowienie tego parametru, możesz to także sprawdzić dzięki [GET /sale/category-parameters-scheduled-changes](https://developer.allegro.pl/documentation#operation/getCategoryParametersScheduledChangesUsingGET_1).

**Comment by tomylee0** [comment]
Czy jest planowane w takim razie usunięcie podkategorii "Książki obcojęzyczne"?

**Comment by MaciejFrackowiak** [comment]
Niestety, nie posiadamy takiej informacji.

**Comment by tomylee0** [comment]
Jakiś czas temu parametr Język posiadał między innymi takie podwójne lub potrójne wartości (np. dla kategorii 111780) :

        {
          "id": "2868_480037",
          "value": "angielski, niemiecki",
          "dependsOnValueIds": []
        },
        {
          "id": "2868_560057",
          "value": "polski, angielski, niemiecki",
          "dependsOnValueIds": []
        },

W tej chwili są już tylko pojedyncze:

        {
          "id": "2868_2",
          "value": "angielski",
          "dependsOnValueIds": []
        },
        {
          "id": "2868_1122020",
          "value": "arabski",
          "dependsOnValueIds": []
        },

Czy dozwolone jest wstawianie więcej niż jedną wartość do tablicy valueIds parametru? Po czym poznać w definicji kategorii które parametry akceptują więcej niż jedną wartość?

**Comment by MaciejFrackowiak** [comment]
Dany parametr, w tym przypadku Język przy wymienionych wartościach słownikowych ma wpis:
```
"restrictions": {
                "multipleChoices": false
            }
```
Oznacza to, że do wyboru jest tylko jedna wartość.

**Comment by tomylee0** [comment]
Wygląda na to, że powoli rezygnujecie z planowanej obowiązkowości parametru "Język". W dniu rozpoczęcia tego wątku miałem na koncie kilkadziesiąt tysięcy ofert zwracanych przez /sale/offers/unfilled-parameters. Dziś jest to już kilka tysięcy. 

Czy sami automatycznie wypełniacie planowany obowiązkowy parametr na ofertach? A jeśli nie to kiedy możemy się spodziewać ustabilizowania sytuacji z parametrem "Język"?

**Comment by MaciejFrackowiak** [comment]
Proces ten odbywa się całkowicie poza API - API jako jeden z kanałów obsługi ofert jest po prostu nijako odbiorcą prowadzonych zmian. W związku z tym nie posiadamy szczegółowego planu zmian w kategoriach. Jeśli chcesz uzyskać więcej informacji proszę skontaktuj się bezpośrednio z [Pomocą Allegro](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
