### ISSUE TITLE
The token expires very quickly

### ISSUE THREAD

**Issue by TarnJul** [allegro/allegro-api#6565]
- [X] z zasobem REST API / with a REST API resource
 - [X] z logowaniem lub autoryzacją / with login or authorization

Hello. There was a problem with one of the Allegro accounts. The token expires very quickly. If for other accounts the token has not expired since 12/01/2022, then for the Venta account we change the token almost every day. Please, tell what's the problem?

**Comment by hahyes** [comment]
Do you mean access token or refresh token? Access token expires in 12 hours, always.

**Comment by TarnJul** [comment]
Refresh tocken

**Comment by hahyes** [comment]
@TarnJul Refresh token expires after single successful use (it returns new access and refresh token). Make sure your app is not refreshing token somewhere without saving new pair of tokens.
