### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by jcubic** [allegro/allegro-api#6566]
Utworzyłem aplikacje z jednym uprawnieniem: allegro:api:sale:offers:read

I probuje użyć kodu z przykładu PHP z auth:

```php
function main() {
    $token = getAccessToken();
    $headers = array("Authorization: Bearer $token", "accept: application/vnd.allegro.public.v1+json");
    $url = "https://api.allegro.pl/sale/offers?name=kurs%20programowania";
    $ch = getCurl($headers, $url);
    $content = curl_exec($ch);
    echo $content;
    curl_close($ch);
}
```

Ale dostaje błąd: "Access is denied", token sie generuje poprawnie.

**Comment by PrzemyslawLukanowski** [comment]
Najprawdopodobniej token uzyskałeś w ramach autoryzacji client_credentials, która nie posiada kontekstu użytkownika. Aby skorzystać z tego zasobu, jak i większości innych, musisz wygenerować token za pomocą autoryzacji [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow). W naszej [dokumentacji](https://developer.allegro.pl/documentation) znajdziesz odpowiednie oznaczenia:

- bearer-token-for-user przy zasobie oznacza autoryzacje code lub device;
- bearer-token-for-application - client_credentials.

**Comment by jcubic** [comment]
Chce zrobić prostą aplikacje która będzie mi wyświetlała moje oferty czyli autora aplikacji, Nie chce uwieżytelniać nikogo. Dokładnie chce wyświetlić ceny moich aukcji dla WOŚP na stronie. Jak mam to zrobić?

**Comment by PrzemyslawLukanowski** [comment]
Jako autor aplikacji, który posiada oferty na Allegro, jesteś również użytkownikiem Allegro, czyli jako ten użytkownik musisz zautoryzować aplikację, aby mogła wykonywać operacje w Twoim imieniu. Po tym, kiedy uwierzytelnisz siebie jako użytkownika i wygenerujesz parę tokenów (access i refresh), możesz zaimplementować obsługę refresh tokenów, tak aby aplikacja raz na 12 godzin automatycznie przedłużała (generowała nowe pary) ważność tokena. Więcej na ten temat przeczytasz w [naszym poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena).

**Comment by jcubic** [comment]
A czy można użyć uwierzytelniania [DCR](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#dynamic-client-registration), wydaje sie prostsze w użyciu, ponieważ nie muszę odpalać mojej aplikacji na serwerze i nawet używać przeglądarki.
