### ISSUE TITLE
Pobieranie parametrów ofert niepowiązanej z produktem

### ISSUE THREAD

**Issue by robsonek** [allegro/allegro-api#6567]
Jak pobrać parametry oferty, która w odpowiedzi na żądanie /sale/product-offers/ zwraca pusty parametr productSet, a po wejściu w ofertę przez www widzę wpisane parametry produktu takie jak EAN, Kod producenta, Marka, Kolekcja, itp.?

**Comment by robsonek** [comment]
13111993196

**Comment by PrzemyslawLukanowski** [comment]
Aby parametry produktowe były widoczne w sekcji productSet, musisz połączyć ofertę z produktem. Ew. możesz skorzystać z [GET /sale/offers/{id}](https://developer.allegro.pl/documentation#operation/getOfferUsingGET), jednak miej na uwadze, że jest to zasób, który wyłączymy z końcem tego roku.

**Comment by robsonek** [comment]
Rozumiem, ale nie mogę komuś łączyć ofert. Za pomocą tej metody pobiorę takie dane jak napisałem w pierwszym poście? One są normalnie widoczne na aukcji po otwarciu strony bez łączenia z produktem

**Comment by PrzemyslawLukanowski** [comment]
Tak, za pomocą [GET /sale/offers/{id}](https://developer.allegro.pl/documentation#operation/getOfferUsingGET) pobierzesz wszystkie parametry uwzględnione w ofercie. Będą widoczne w sekcji "parameters". Musisz oczywiście posiadać token użytkownika, do którego należy oferta, której dane chcesz pobrać.
