### ISSUE TITLE
Problem z wystawieniem oferty

### ISSUE THREAD

**Issue by lukasz1991a** [allegro/allegro-api#6568]
W środowisku testowym za pomocą metody POST sale/product-offers próbuję wystawić ofertę 
{"productSet":[{"product":{"id":"92e8142f-8214-47c0-ab83-b2506ecd1a92","idType":"GTIN"}}],"sellingMode":{"price":{"amount":"220.85","currency":"PLN"}},"stock":{"available":1}}
Otrzymuję błąd 

  "code": "OfferAccessDeniedException"
  "message": "Forbidden"
  "details": null
  "path": ""
  "userMessage": "Access denied. You are not authorized to perform operations on the indicated offer"

konto jest zweryfikowane, z poziomu przeglądarki potrafię wystawiać.
Aplikacja ma pełne prawo - ma zaznaczone wszystko co można było 
Produkt o id 7698228464 (92e8142f-8214-47c0-ab83-b2506ecd1a92) jest wystawiony z konta na które się loguję.

**Comment by PrzemyslawLukanowski** [comment]
Otrzymujesz błąd, ponieważ próbujesz wystawić ofertę za pomocą konta zwykłego. Zgodnie z [naszym komunikatem](https://developer.allegro.pl/news/od-dzis-oferty-przez-api-moga-wystawiac-i-edytowac-tylko-uzytkownicy-z-kontem-firmowym-9gRePwXxGiP) z ubiegłego roku, wystawiać i zarządzać ofertami przez API mogą tylko użytkownicy z kontem firmowym.

**Comment by lukasz1991a** [comment]
Mam konto firmowe również w środowisku testowym i nie potrafie zweryfikować środków wypłaty i firmy  optimal-net-pl

**Comment by PrzemyslawLukanowski** [comment]
Twoje konto firmowe nie było do końca aktywne, wykonałem to po naszej stronie. Nie powinieneś już mieć problemu z wystawianiem ofert na tym koncie.

**Comment by lukasz1991a** [comment]
Dziękuję za błyskawiczną pomoc
