### ISSUE TITLE
[srodowisko testowe] Jak zweryfikowac konto sprzedawcy?

### ISSUE THREAD

**Issue by KonradKoch** [allegro/allegro-api#6570]
Witam probuje zweryfikowac konto sprzedawcy na fikcyjne dane firmowe, w celu wystawienia ofert i przeprowadzenia testow integracji z api, czekam juz pare dni. Ile normalnie zajmuje ten proces? Adres email konta : konrad.a.koch@gmail.com

**Comment by MaciejFrackowiak** [comment]
Zweryfikowałem Twoje konto.

**Comment by dsedrowski** [comment]
Poproszę o weryfikację również Speedy044.

**Comment by Speedy044** [comment]
Podepnę się i również proszę o weryfikacje konta. Login: ECTesty

Swoją drogą trochę to słabe, że tak wygląda proces tworzenia konta w sandboxie, raczej z sandboxa korzystają tylko developerzy i na nic nam "symulacja" rzeczywistego procesu rejestracji jak to ktoś napisał w innym wątku :)

**Comment by MaciejFrackowiak** [comment]
@dsedrowski Zweryfikowałem Twoje konto.

**Comment by MaciejFrackowiak** [comment]
@Speedy044 Twoje konto również zweryfikowałem. Oczywiście, Sandbox via API wykorzystywany jest głównie przez develeoperów, jednak z wersji WWW korzysta również wielu sprzedających chcących przetestować funkcjonalności Allegro bez konsekwencji "zepsucia" czegoś.

**Comment by LAmcpp** [comment]
Podepnę się i również proszę o weryfikacje konta. Login: LA_NP

**Comment by Lukasz-Zurek** [comment]
@LAmcpp Zweryfikowałem wskazane konto.

**Comment by Lukasz-Zurek** [comment]
@LAmcpp Zweryfikowałem.

**Comment by LAmcpp** [comment]
@Lukasz-Zurek Dziękuję Ci!
Ale zmiany nie zostały zastosowane.
A kiedy wchodzę na profil firmy, widzę status:
2.Weryfikacja firmy

**Comment by Lukasz-Zurek** [comment]
@LAmcpp Ok, a teraz? :)

**Comment by allprs87dev** [comment]
Potwierdź moje konto, proszę. Potrzebuję go do testów. Dzięki.

* email:
allprs87dev@outlook.com
* Client:

**Comment by AureliuszBrussy** [comment]
@allprs87dev czy w zakładce "[Moje konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto)" wykonałeś (w tzw. "krokowcu") wszystkie kroki z listą kroków niezbędnych do aktywacji i weryfikacji ( w tym symulację przelewu weryfikacyjnego)?

**Comment by allprs87dev** [comment]
Jeszcze raz dzień dobry.
Muszę utworzyć aplikację. Aby to zrobić, muszę aktywować swoje konto i włączyć logowanie dwuetapowe.
Ale nie mogę aktywować konta (nie mogę wykonać przelewu w złotówkach)

Na stronie
https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto
Jaką listę kroków musisz wprowadzić?
Chcesz uzupełnić profil?
I nie znajdę „Przelew weryfikacyjny”

Jeśli nie jest trudno pomóc, to nic nie rozumiem. Dziękuję Ci

**Comment by AureliuszBrussy** [comment]
@allprs87dev nie wykonuj prawdziwego przelewu - wystarczy, że skorzystasz z opcji wykonania szybkiego przelewu. Zostaniesz przekierowany do symulatora operatora płatności, gdzie będziesz mógł po prostu zaakceptować "przelew".

**Comment by LAmcpp** [comment]
Czy proste, niebiznesowe konta też trzeba aktywować, aby zacząć sprzedawać produkty?
Proszę aktywować dwa konta:
1) Login: LA
2) Login Lalala

Z góry dziękuję!

**Comment by AureliuszBrussy** [comment]
@LAmcpp nie odnalazłem konta z loginem "LA". Konto "Lalala" jest aktywowane. Aby prowadzić sprzedaż, zarejestruj jednak [konto firma](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F).

**Comment by LAmcpp** [comment]
Przepraszam, zapomniałem, że zmieniłem nazwę użytkownika.
Login: LA111
Proszę aktywować.

**Comment by AureliuszBrussy** [comment]
@LAmcpp konto LA111 jest aktywne.
