### ISSUE TITLE
Rest API no longer working

### ISSUE THREAD

**Issue by Aledelfo** [allegro/allegro-api#6571]
Hi,
i created the REST API some time ago and until yesterday I had no problem, I got an error in the wordpress plug-in that I use to be able to connect Allegro to the website. I enter the data I find in the DEVELOPER APPS section of Allegro but when I save the changes it returns an error.
Are there any solutions to this problem ?

Thank you
![Ustawienia-‹-Maveat-Polska-—-WordPress](https://user-images.githubusercontent.com/122434016/211747775-cd910eba-163c-496b-ba6e-a7ecca3892a7.png)

**Comment by MaciejFrackowiak** [comment]
You are using a third-party app, so we cannot check any logs. Please, contact application support.
