### ISSUE TITLE
Sprawdzenie oferty - Allegro Ceny

### ISSUE THREAD

**Issue by glinkaa** [allegro/allegro-api#6572]
Czy jest możliwość sprawdzenia poprzez API czy oferta jest objęta obniżką w ramach programu Allegro Ceny?

**Comment by MaciejFrackowiak** [comment]
Tak, możesz skorzystać z [GET /sale/badges](https://developer.allegro.pl/documentation/#operation/getBadges), aby dowiedzieć się, która oferta jest objęta akcją.
