### ISSUE TITLE
Jak dodać usługi Allegro ONE do cennika?

### ISSUE THREAD

**Issue by rxgxs21** [allegro/allegro-api#6573]
Konto sandbox: polski24
Chcę przetestować tworzenie wysyłek dla zamówień z metodą dostawy z pakietu Allegro ONE.
Niestety nie widzę ich na liście przy tworzeniu cennika.
Co należy zrobić, aby w cenniku pojawiła się możliwość dodania dostawy z pakietu Allegro ONE?

**Comment by PrzemyslawLukanowski** [comment]
Wygląda to na problem z Twoim kontem - zostało założone w 2018 i od tego czasu nie było w pełni aktywowane. Nasze wewnętrzne mechanizmy związane z aktywacją kont na Sandboxie nieco zmieniły się od tego czasu, dlatego rozwiązaniem będzie założenie nowego konta. Jeśli będziesz mieć problem z aktywacją, napisz proszę w wątku. Metody powinny być automatycznie widoczne na koncie, bez konieczności wykonywania dodatkowych działań.

**Comment by rxgxs21** [comment]
Mogę prosić o weryfikację konta: polski24_pl

**Comment by MaciejFrackowiak** [comment]
@rxgxs21 Twoje konto jest już zweryfikowane.

**Comment by rxgxs21** [comment]
Przy próbie wystawienia oferty na nowym koncie pojawia się błąd: "Wystąpił błąd - Serwis niedostępny"

**Comment by paweligatowski** [comment]
Czy konto ignatowski-firma pi@iq200.com.pl też jest zbyt stare by działało normalnie. Kilka godzin się zastanawiam jak dodać taką formę wysyłki!

**Comment by PrzemyslawLukanowski** [comment]
@paweligatowski Twoje konto nie było w pełni aktywne - właśnie je aktywowałem.
