### ISSUE TITLE
Publishing offers for second-hand (used/używany) products using /sale/product-offers resource

### ISSUE THREAD

**Issue by fr1kk0nut** [allegro/allegro-api#6575]
I am looking for a way to publish second-hand (or "używany") products via a POST request using the /sale/product-offers resource. The problem is that I can nowhere define the condition; at least, the documentation doesn't cover it. Does anyone have experience with publishing second-hand products via REST API? Thanks in advance and best regards from Berlin <3

**Comment by MaciejFrackowiak** [comment]
Parameter Condition is an offer parameter, so you should describe it in the offer part of the request structure - we described it in [our tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#offer-parameters).

**Comment by fr1kk0nut** [comment]
> Parameter Condition is an offer parameter, so you should describe it in the offer part of the request structure - we described it in [our tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#offer-parameters).

Thanks for the instant reply! Understood, but I can't find how to define the parameter. So what's the parameter name and possible values? The documentation doesn't specify that (or i'm overseeing something). Thanks again and regards from Berlin :)

**Comment by MaciejFrackowiak** [comment]
You should use [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) to retrieve parameters and their values available in the selected category. 
Also, in the tutorial we have posted examples:
```
...
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_2"
            ]
        }
    ]
  ...    
```
or
```
 ...
    "parameters": [
            "name": "Condition",
         {
           "values": [
                "Used"
            ]
        }
    ]
  ...    
```
