### ISSUE TITLE
[Srodowisko testowe] autoryzacja, problem z CORS

### ISSUE THREAD

**Issue by KonradKoch** [allegro/allegro-api#6576]
WItam, wykonuje GET po stronie frontu, w celu otrzymania kodu do autoryzacji. Wyrzuca mi 403 i CORS error. 

Proxy error: Could not proxy request /service-worker.js from localhost:3000 to http://localhost.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
![Screenshot from 2023-01-13 03-28-05](https://user-images.githubusercontent.com/63077842/212223775-488079fc-3087-4098-800b-49d5a076c50b.png)

Dodam, ze zarejestrowana aplikacja ma dodany http://localhost:3000/ jako adres do przekierowan.

**Comment by MaciejFrackowiak** [comment]
Spójrz proszę na wątek https://github.com/allegro/allegro-api/issues/1061 - sytuacja wygląda na tożsamą.

**Comment by polenquick** [comment]
kiedyś miałem problem z CORS, wystarczyło w .htaccess ustawić
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^.*$ https://%{SERVER_NAME}%{REQUEST_URI} [R,L]
Header set Access-Control-Allow-Origin "*"

akurat w tym przypadku apka nie była postawiona lokalnie, ale możesz spróbować wymusić po http

**Comment by KonradKoch** [comment]
Z tego co zrozumialem serwer akceptuje tylko http://localhost i ma pretensje, ze origin requesta to http:/localhost:300, pomocy w/w nie dziala, a zalaczony watek nie jest pomocny w tym przypadku. Tam jest implementowany inny rodzaj autoryzacji, w trybie device flow.

**Comment by KonradKoch** [comment]
Jak klikam na adres nieudanego requesta dostaje kod autoryzacji, cors nie krzyczy... Kod jest poprawny z jakiegos powodu serwer odrzuca GET wywolywane na przycisk...

**Comment by MaciejFrackowiak** [comment]
Proszę podaj nam więcej szczegółów, ponieważ obecnie bazujemy na zrzucie ekranu. Przekaż nam ClientId Twojej aplikacji oraz całościowe wywołanie - dane możesz przekazać poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) (dodaj proszę  numer wątku z GitHub).
