### ISSUE TITLE
Dodawanie do kategorii numizmatyki nowych ofert w 2024

### ISSUE THREAD

**Issue by DenyaOver** [allegro/allegro-api#6577]
Dzień dobry, mam pytanie jak będzie można dodawać do kategorii "Numizmatyki" np. Talary, jeśli dla tego trzeba będzie dodawać produkt do katalogu, ale w tej kategorii nie ma możliwości dodawania nowego produktu?

**Comment by Lukasz-Zurek** [comment]
Póki co dział Numizmatyki nie jest objęty obowiązkową produktyzacją. Natomiast szczegółową listę kategorii objętych obowiązkową produktyzacją znajdziesz [w tym pliku](https://t.allegro.pl/rd/directSendout_a536954f-411e-4853-9aba-8640c91be2e9_62799754?name=szczeg%C3%B3%C5%82ow%C4%85_list%C4%99_wszystkich_kategorii&url=https://assets.allegrostatic.com/popart-attachments/att-c68bb895-b0e6-4101-ac3d-efd0bfa9083e?utm_source%3Dcoma_email%26utm_medium%3Da536954f-411e-4853-9aba-8640c91be2e9&s=A371lo%2B6).

Nie mamy informacji o ewentualnych zmianach w tym zakresie. Możesz zatem obecnie wystawić nową ofertę w Numizmatyce bez konieczności tworzenia produktu.

**Comment by DenyaOver** [comment]
Produkt nie jest obowiązkowy dla zapytania POST sale/product-offers?

**Comment by Lukasz-Zurek** [comment]
@DenyaOver W żądaniu musisz przekazać "productSet", w przeciwnym razie zwrócimy błąd.

W przypadku działu Numizmatyki wystarczy, że przekażesz podstawowe dane, m.in. tytuł, identyfikator kategorii, parametry, etc. (Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem-za-pomoca-zasobu-sale-product-offers)). Utworzysz w ten sposób ofertę, jednak bez produktu.

**Comment by DenyaOver** [comment]
@Lukasz-Zurek W obiekcie "productSet" w przykładzie muszę dodać "parameters", w którym trzeba wpisać id, nie rozumiem to id produktu, jego można nie wpisywać bo dla odziału numizmatyki nie mam tego produktu w katalogu?

**Comment by Lukasz-Zurek** [comment]
@DenyaOver Zasób ten (w kontekście Numizmatyki) należy traktować typowo jako zasób do wystawienia oferty, więc nie musisz przekazywać product.id. Możesz się skupić na wymaganych parametrach, które pozwolą Tobie wystawić ofertę.

Jeżeli Numizmatyka znajdzie się w przyszłości wśród kategorii objętych obowiązkowych - dla takiej oferty nasz system wyszuka produkt z katalogu, lub go utworzy.

**Comment by Lukasz-Zurek** [comment]
@DenyaOver Jeśli Twoje konto nie jest w pełni aktywne to tak - najprawdopodobniej to właśnie jest przyczyną błędu.

**Comment by DenyaOver** [comment]
@Lukasz-Zurek konto na sandbox wymaga, aktywacji konta, lub czegoś takiego?

**Comment by Lukasz-Zurek** [comment]
@DenyaOver Tak. Co istotne - konto powinno być firmowe i tu najlepiej rozpocząć jego weryfikację oraz ustawić wypłaty. Jeżeli miałbyś problem podczas tego procesu - prześlij proszę login konta na Sandboxie. Postaram się pomóc.

**Comment by DenyaOver** [comment]
@Lukasz-Zurek Tak, bardzo proszę pomóc, login do konta na Sandboxie: allegro@one.bid

**Comment by Lukasz-Zurek** [comment]
@DenyaOver Aktywowałem i zweryfikowałem Twoje konto firmowe.

**Comment by DenyaOver** [comment]
@Lukasz-Zurek Dziękuje, shippingRates jest obowiązkowym dla wpisywania, czy może on być null bo w przykładie jest ustawiony jako null, ale mnie pokazuje taki błąd
"{"errors":[{"code":"EMPTY_SHIPPING_RATES","message":"Empty shipping rates","details":null,"path":"delivery.shippingRates","userMessage":"Brak ustawionego cennika dostaw."}]}"

**Comment by Lukasz-Zurek** [comment]
@DenyaOver Musisz wskazać cennik dostawy.
