### ISSUE TITLE
Allegro wprowadza w błąd klientów tytułami z katalogu produktów

### ISSUE THREAD

**Issue by GHalbt** [allegro/allegro-api#6579]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X] inny / other

:beetle: **Opis / Description**

Brak możliwości schowania, nie wyświetlania tytułu z katalogu w ofercie.

Dyskusja:
https://github.com/allegro/allegro-api/discussions/6578

Wystawiając przez API dziesiątki tysięcy produktów nie ma możliwości sprawdzenia każdej aukcji. Są sytuację gdzie tytuł z bazy danych sklepu lub pliku XML mówi o jednej sztuce produktu a tytuł produktu z katalogu allegro zawiera dopisek X sztuk (to tylko pierwszy przyklad z brzegu, są gorsze patologię). Powoduje to straty u sprzedających, negatywne komentarze za anulowane zamówienia oraz straty allegro w ramach prowizji.

Natychmiast trzeba zrobić opcje aby tytuł produktu z katalogu NIE wyświetlał się jako główny na 3/4 szerokości ekranu a na pewno nie był pierwszy z góry. To nim głównie sugerują się kupujący. Jest to absurdalne ze aukcja końcowo zawiera 2 różne tytuły. Główny, na samej górze jest z katalogu a ten po prawej stronie (w wersji mobilnej ten niżej) to tytuł własny.

Rozważcie temat bo jest to trochę na pograniczu prawa zawierania umów kupna sprzedaży na odległość. A dzieje się to z winy serwisu. UOKIK i tak już ostatnio obserwuje allegro.

![212546253-1fbf37c4-997f-405a-98f8-fbc2e2829131](https://user-images.githubusercontent.com/120689175/212552369-c6f84ef8-a826-432a-8b73-b79318922bc3.jpg)

**Comment by polenquick** [comment]
+1
Jest masa produktów gdzie sprzedawcy albo źle utworzyli produkty allegro, albo doszły nowe parametry i nie nadaję się to do niczego, bo kolejne zmiany będą wprowadzone dopiero na opłacie utrzymaniowej, albo zostanie podmieniony na nowy produkt Allegro. Na hurtowych operacjach, gdzie wiążemy po kilka tysięcy produktów nie da się tego zweryfikować, a tym bardziej zgłaszać pojedynczo każdy taki błędnie powiązany produkt. Tytuły oferty to zupełnie co innego niż produkt allegro i w mojej opinii powinny znajdować się pod tytułem, a nie odwrotnie jak to jest teraz, bo spora część Klientów nawet nie zjeżdża  nigdy do połowy opisu nie wspominając o czytaniu. Spotkałem masę osób, które walczą z tym na każdy możliwy sposób i dodają nazwy produktów Allegro na zasadzie "PRODUKT Z TYTUŁU I OPISU OFERTY", aby były one jak najbardziej mylące.
Czasami podpina się np. po EANIE pod producenta i aukcja dotyczy np. etui, a pobierają się zdjęcia do zestawów typu etui + szkło lub logo zupełnie innych firm, albo ktoś 16 zdjęć doda z czego połowa się duplikuje - tutaj działa chyba zasada kto pierwszy ten lepszy.

**Comment by hahyes** [comment]
Dałbym wam i tysiąc plusów, panowie (lub panie).
Niestety nie jest to odpowiednie miejsce na tą dyskusję, jako iż zespół od REST API Allegro nie ma żadnej decyzyjności w tej sprawie. Gadane już prędzej, jednakże na głosy rozsądku tak czy tak Allegro zdaje się nie reagować. A problem jest całkiem prosty - system produktyzacji nie nadaje się do niczego. To jest bardzo uboga kalka tego, co oferuje konkurencja z Zachodu. Wiadomo, że konkurencja nie jest idealna... ale poważnie? System, w którym każdy może dodawać i każdy może zgłaszać poprawki? Oni z tym nigdy nie osiągną jakiegoś sensownego konsensusu.

Widywałem jakieś testy widoku, w którym jest jedynie nazwa oferty podpięta zamiast nazwy produktu. Może w końcu pójdą po rozum do głowy?

**Comment by MaciejFrackowiak** [comment]
Z naszej strony muszę potwierdzić słowa @hahyes - jako osoby odpowiedzialne za API nie mamy realnego wpływu na wygląd ofert oraz sposób ich prezentacji w połączeniu z produktem. Dlatego też, swoje uwagi co do mechanizmu prezentacji ofert i produktów przekażcie proszę bezpośrednio poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) Pomocy Allegro, ponieważ tak Wasze głosy trafią w odpowiednie miejsce.

**Comment by GHalbt** [comment]
@MaciejFrackowiak Możemy liczyć na waszą interwencję chociażby w przekazaniu problemu gdzieś wyżej? Jako pracownicy macie większą siłę sprawczą. Tych formularzy kontaktowych i tak pewnie nikt nie czyta.

**Comment by MaciejFrackowiak** [comment]
@GHalbt W praktyce jest na odwrót - to Wasze głosy przekazywane m.in. przez formularz kontaktowy mają dużo większe znaczenie. Pokazujecie realne przykłady problemów, które pochodzą od prawdziwych sprzedawców, dlatego raz jeszcze polecę ze swojej strony indywidualne przekazanie przykładów poprzez formularz kontaktowy.
