### ISSUE TITLE
[REST] Niepoprawny kod błedu

### ISSUE THREAD

**Issue by pskz** [allegro/allegro-api#658]
Na przykładzie zasobu GET "/sale/offer-tags"

Pobierając listę tagów dla konta które nie posiada "Sklepu Allegro", według dokumentacji spodziewam się kodu 403 (konto z powodzeniem zalogowane, ale bez dostępu do zasobu), natomiast api zwraca mi kod 401 tak jakby wystąpił błąd autoryzacji, a przecież użytkownik z powodzeniem przeszedł etap autoryzacji skoro aplikacja pozwala na zapytanie do konkretnego zasobu z api.
W tym momencie treść błędu (która jest zbliżona do tej z dokumentacji, pomijając literówki) nie ma znaczenia ponieważ obsługa błędu zostaje wydzielona do innego bloku w aplikacji w zależności od zwróconego kodu.

Sprawia to trochę problemów, ponieważ różnica pomiędzy błędem autoryzacji a brakiem dostępu do konkretnego zasobu jest ogromna. Klient zostaje wprowadzony w błąd myśląc że wygasł token, nastąpił problem z powiązaniem aplikacji, czy może zablokowali mu konto, gdy zwyczajowo nie ma dostępu do konkretnego zasobu z powodu nie wykupionego abonamentu na "Sklep Allegro".

Problem występuje na produkcji jak i w sandboxie
response z produkcji: https://pastebin.com/jYNPGBLz
response z sandboxa: https://pastebin.com/daEzvznv

**Comment by MarcinLuczak** [comment]
@pskz zgadza się, masz rację. Tutaj powinien być zwracany błąd 403. Przekazałem Twoje zgłoszenia do sprawdzenia i poprawienia.

**Comment by MarcinLuczak** [comment]
@pskz poprawiliśmy to - w przypadku, który opisałeś, zwracamy już kod błędu 403.
