### ISSUE TITLE
Allegro One - Inne dane na etykiecie nie są dostępne dla wybranego przewoźnika ścieżka: /sender

### ISSUE THREAD

**Issue by MariuszBekus** [allegro/allegro-api#6580]
Podczas tworzenia przesyłek Allegro One przez API, otrzumuje poniższy błąd:

Opcja 'Inne dane na etykiecie' nie są dostępne dla wybranego przewoźnika
ścieżka: /sender

Jak usunę dane wysyłającego przesyłkę to przesyłka się nadaje poprawnie, aczkolwiek w polu "Nadawca" na etykiecie pokazują się dane klienta, zamiast danych nadawcy przesyłki. Podczas generowania przesyłek przez panel allegro, normalnie pokazuje dane nadawcy, więć nie wiem czy to błąd czy coś źle robie.

Dane przesyłam w taki sam sposób jak w instrukcji: https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY

"label": {                                
    "sender": {                                
      "address": {
        "street": "Testowa 8",
        "postCode": "10-200",
        "city": "Warszawa",
        "countryCode": "PL",
        "county": null                      
      },
      "email": "email@mail.com",
      "name": "Jan Kowalski",
      "company": "Allegro.pl sp. z o.o.",
      "phone": "500600700"
    },
    "fileFormat": "PDF",                
    "referenceNumber": "abcd1234"           
  },

**Comment by MaciejFrackowiak** [comment]
Usługi Allegro One nie obsługują innych danych nadawcy, w związku z tym w polu label.sender przekazuj null lub w ogóle pomijaj to pole - jest ono opcjonalne.

**Comment by MariuszBekus** [comment]
> Usługi Allegro One nie obsługują innych danych nadawcy, w związku z tym w polu label.sender przekazuj null lub w ogóle pomijaj to pole - jest ono opcjonalne.

Tak też zrobiłem, aczkolwiek na etykiecie w polu nadawca są dane kupującego, czy nie stanowi to żadnego problemu?
