### ISSUE TITLE
Zmiana statusu zamówienia - bez logowania do allegro

### ISSUE THREAD

**Issue by dominikc4f** [allegro/allegro-api#6581]
Witam, mam aplikację do której pracownik nie może dostać loginu i hasła konta do allegro w którym chce zmienić status zamówienia. Używając autoryzacji "Client_credentials flow" nie mogę zmienić statusu. Jak mogę inaczej rozwiązać ten problem bez logowania się na konto allegro ?

**Comment by Lukasz-Zurek** [comment]
Autoryzacja "Client_credentials flow" jest bez kontekstu użytkownika i generalnie bez autoryzacji na koncie (np. korzystając z pozostałych sposobów, które opisujemy w [poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR)) nie zmienisz statusu zamówienia.
