### ISSUE TITLE
Błąd podczas zapłaty za zamowienie blikiem na allegrosandbox.

### ISSUE THREAD

**Issue by lmichalFerrodo** [allegro/allegro-api#6582]
Na allegrosandbox bezskutecznie próbuje zapłacić za zamówienie (8e42d110-9596-11ed-babd-95b5f01c0e98)  BLIKIEM. W zeszłym tygodniu nie było z tym problemu i za każdym razem wpisywany kod(123456) przechodził bezproblemowo.

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Skorzystaj proszę z kodu 777123.

**Comment by lmichalFerrodo** [comment]
Płatność przeszła, dzięki! Czy tym kodem mogę opłacać kolejne, testowe zamówienia?

**Comment by MaciejFrackowiak** [comment]
Tak.

**Comment by lmichalFerrodo** [comment]
@MaciejFrackowiak Wczorajszy kod blik(777123) przestał działać. Mogę poprosić o nowy kod?

**Comment by MaciejFrackowiak** [comment]
Jest to uniwersalny kod - przed momentem dokonałem pomyślnej płatności. Spróbuj zatem ponownie lub wybierz alternatywną metodę płatności.
