### ISSUE TITLE
/sale/offers/unfilled-parameters nie zwraca wszystkiego

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#6583]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

Wygląda na to, że jednak coś jest nie tak z /sale/offers/unfilled-parameters (#6564).

Tutaj odpytanie o unfilled-parameters: dc19b783cb3d2281.
Dostałem 105 ofert. A dużo więcej ofert nie mogę już updatować ze względu na brak parametru "Język". Np. ten UPDATE (8601ea32629e2fa0) się nie udaje właśnie z tego powodu a nie mam tej oferty zwróconej przez unfilled-parameters.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za Twój przykład - wyjaśniam sprawę z odpowiedzialnym zespołem, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Zasób zwraca już wskazaną przez Ciebie ofertę - przepraszam za niedogodności. Przyczyną problemu był przedłużony czas wykonywania operacji uobowiązkowienia parametru - spowodowało to, że zasób nie otrzymał już tych informacji.
