### ISSUE TITLE
Aktualizacja cen - Python

### ISSUE THREAD

**Issue by Hitsujii** [allegro/allegro-api#6585]
Witam, próbuję zaaktualizować ceny używając **PATCH sale/product-offers/{offerId}**

Każda próba połączenia i przekazania nowej ceny kończy się komnunikatem: 
`{'errors': [{'code': 'BAD_REQUEST', 'message': 'Message is not readable.', 'details': None, 'path': 'request.body', 'userMessage': 'Request contains invalid data. Contact the application author.'}]}`

Kod:
`
            try:
                url = f"https://api.allegro.pl/sale/product-offers/{offerId}"
                headers = {'Authorization': 'Bearer ' + token, 'Accept': "application/vnd.allegro.public.v1+json",'Content-Type': 'application/vnd.allegro.public.v1+json'}
                data = { 
                    "sellingMode": {
                        "price": {
                            "amount": "30000",
                            "currency": "PLN"
                            }
                    }    
                }
                result = requests.patch(url, headers=headers, data=data)
                print(result.json())
            except requests.exceptions.HTTPError as err:
                raise SystemExit(err)
`

Z góry dziękuję za pomoc.

**Comment by Lukasz-Zurek** [comment]
Z requestu wynika, że zawartości w **data** nie wysyłasz w jsonie, stąd zaistniały błąd.

**Comment by Hitsujii** [comment]
Ah no właśnie, dziękuje. 
Problem rozwiązany.
