### ISSUE TITLE
GetParcelCreationStatus zwraca "Internal system error"

### ISSUE THREAD

**Issue by rxgxs21** [allegro/allegro-api#6586]
Konto sandbox: polski24_pl

Po stworzeniu paczki w allegro oraz wysłaniu zapytania o status tworzenia paczki zwracany jest response 200 OK, ale ciało wygląda następująco:
```
{
    "id": "b554ecf2-d6e7-4143-bad3-02746ed62926",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Internal system error",
            "details": null,
            "path": null,
            "userMessage": "Wewnętrzny błąd systemu"
        }
    ]
}
```

**Comment by Lukasz-Zurek** [comment]
Nie podałeś wymiarów paczki w polu "dimensions". Niemniej jednak pracujemy nad poprawką komunikatu zwracanego w tej sytuacji.

**Comment by rxgxs21** [comment]
Utworzenie przesyłki przeszło pomyślnie.
Teraz przy sprawdzaniu statusu przesyłki dostaję błąd: Proccessing error - error.common.processing
```
{
    "id": "3766ed45-08ef-49cb-9a47-79d6e5557e5f",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Processing error",
            "details": null,
            "path": null,
            "userMessage": "error.common.processing"
        }
    ]
}
```

**Comment by Lukasz-Zurek** [comment]
@rxgxs21 Mieliśmy problemy po naszej stronie. Sytuacja nie powinna się już powtarzać.

Przepraszamy za utrudnienia.
