### ISSUE TITLE
[środowisko testowe] brak dostępu do warunków zwrotów

### ISSUE THREAD

**Issue by muzyk24** [allegro/allegro-api#6587]
Występuje problem: [ze środowiskiem testowym]

Opis:
Nie można się dostać do warunków zwrotów.
Przez API też nic nie jest zwracane.

**Comment by Lukasz-Zurek** [comment]
Sprawdziłem działanie zakładki i bez problemu udało mi się dodać nowe warunki zwrotów.

Podaj proszę login na Sandboxie i prześlij zrzuty ekranu.

Dodatkowo prześlij proszę trace-id dla żądania wysyłanego w API.

**Comment by muzyk24** [comment]
Już działa, problem rozwiązany.
