### ISSUE TITLE
Nie można wystawić oferty przez formularz - "Wybrano nieprawidłowy numer kategorii"

### ISSUE THREAD

**Issue by asmolkowicz** [allegro/allegro-api#6588]
Formularz wystawiania uniemożliwia wystawienie oferty - wybór jakiejkolwiek kategorii powoduje wyświetlenie błędu "Wybrano nieprawidłowy numer kategorii".

![Bez tytułu](https://user-images.githubusercontent.com/74354855/212907182-2a8f94d9-5cf1-4e39-805d-0da9e404520a.png)

**Comment by MaciejFrackowiak** [comment]
Tak, potwierdzam występowanie problemu - działamy już, aby możliwie szybko go wyeliminować. Przepraszam za niedogodności.

**Comment by MaciejFrackowiak** [comment]
Problem został wyeliminowany.
