### ISSUE TITLE
Problem z tworzeniem ofert przez REST API sandbox

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#6589]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Mam problem z wystawieniem oferty przez API, praktycznie cały czas od rana otrzymuję odpowiedź ` Kod: 503. Błąd: {"destination":{"host":"api.allegro.pl.allegrosandbox.pl","path":"/sale/product-proposals","serviceTag":null,"originalDst":null},"details":{"connectionId":6696897},"code":"UC","message":"upstream connect error or disconnect/reset before headers. reset reason: connection termination"}` 

Trace-id=`1470d858e21adba4`

**Comment by MaciejFrackowiak** [comment]
Podobnie jak w wątku #6588 - wiemy i działamy.

**Comment by MaciejFrackowiak** [comment]
Problem nie powinien już występować.

**Comment by mrezlik** [comment]
Niestety dalej to samo. Przykład sprzed chwili: 
` Kod: 504. Błąd: ServiceTimeoutException Execution of the request timed-out. Try again. An error occurred . Trace-id=[fe06e51778a5e4a2].`

**Comment by MaciejFrackowiak** [comment]
To trochę jednak co innego ;) - teraz otrzymujesz błąd 504 na innym zasobie - wyjaśniam to.

**Comment by mrezlik** [comment]
Rzeczywiście, trochę zbyt szybko napisałem, aczkolwiek wydaje mi się, że wczoraj 504 też dostawałem :) W każdym razie czekam na dalsze informacje :)

**Comment by MaciejFrackowiak** [comment]
Już powinno być OK.

**Comment by mrezlik** [comment]
Zgadza się. Działa :)
