### ISSUE TITLE
Identyfikator płatności - API / zestawienia

### ISSUE THREAD

**Issue by nataniel** [allegro/allegro-api#659]
Identyfikator płatności podawany przez API oraz widoczny na zakładce "Zamówienia" (https://allegro.pl/seller-orders/#!/) jako "nr płatności", jest typu "97d80292-c0c0-11e8-b36e-77b5adcf0342", natomiast przy pobieraniu zestawień (https://allegro.pl/myaccount/NewpaymentsReports.php/statement_type,2), jest tylko kolumna "Płatność", gdzie ta sama płatność ma numer "905079730". Czy jest jakaś możliwość, aby połączyć te dwa identyfikatory?

**Comment by PawelTaberski** [comment]
Obecnie nie ma takiej możliwości, przekazałem to jako sugestię do odpowiedniego zespołu. Jeśli zdecydujemy się wdrożyć jakieś rozwiązanie, które pozwoli zmapować jeden numer na drugi poinformujemy o tym.
