### ISSUE TITLE
Błąd autoryzacji dla niektórych kont

### ISSUE THREAD

**Issue by Hornir91** [allegro/allegro-api#6590]
Witam.

Od początku tego roku w mojej aplikacji przestały działać niektóre konta na serwerze produkcyjnym. Przy wysyłaniu pary tokenów access oraz refresh z niektórych kont dostaję zwrotkę 400 "Bad Request" (inne konta działają normalnie i odświeżają swoje tokeny). W związku z tym spróbowałem ponownie uzyskać authorization_code dla tych kont, z których dostaję kod 400, lecz niestety przy próbie wlogowania się (wykorzystując opcję prompt), uzyskuję błąd: "Numer błędu: 8c4d3439cfae04b4". Probowałem też potwierdzić autoryzację z działających obecnie kont i tam wszystko jest w porządku.

Wiedzą może Państwo w czym tkwi błąd?

Z góry dziękuję za odpowiedź.

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
@Hornir91 Błąd tkwi w nieprawidłowym redirect-uri, które przekazujesz podczas próby autoryzacji. Powinien on być zgodny conajmniej z jednym z tych, które podałeś dla aplikacji na [tej stronie](https://apps.developer.allegro.pl).

**Comment by Hornir91** [comment]
Sprawdziłem powiązane aplikacje dla kont działających oraz niedziałających i obydwa rodzaje kont mają powiązane te same aplikacje oraz posiadają ten sam redirect_url, a jednak jedne konta działają bez problemu, a w drugich wyskakuje ww. błąd. Poniżej aplikacje widniejące na każdym z kont. Istnieją już długo i dotychczas działały bez problemu.
<img width="1258" alt="Zrzut ekranu 2023-01-18 o 12 38 27" src="https://user-images.githubusercontent.com/53277040/213162570-d927701e-2e25-46a7-b1e2-5fe652511153.png">

**Comment by Lukasz-Zurek** [comment]
Według przytoczonego przez Ciebie przykładu i naszych logów - podajesz redirect uri: _https://agregator.superauto24***/api/***/allegro-callback_, a w [ustawieniach aplikacji](https://apps.developer.allegro.pl/) (pierwsza z góry na liście ze zrzutu) masz inne redirect-uri.
