### ISSUE TITLE
Edycja oferty powiązanej z produktem i niechciane zdjęcia

### ISSUE THREAD

**Issue by robsonek** [allegro/allegro-api#6591]
Podczas edycji opisu oferty, allegro dodaje do oferty zdjęcia, podejrzewam że to są zdjęcia z katalogu produktów. Nie chcę korzystać z tych zdjęć. Czy da się jakoś to przez API wyłączyć, aby oferta zawierała tylko te zdjęcia które ja dodam?

**Comment by Lukasz-Zurek** [comment]
W tej sytuacji podczas edycji, w sekcji **"images"** przekaż własne zdjęcia. Jednocześnie jeśli chcesz w ofercie tylko własne zdjęcia, bez tych z Katalogu produktów - przekaż dodatkowo w polu **product.images** pustą tablicę.

Więcej informacji na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty).
