### ISSUE TITLE
Aktywacja konta sprzedaży

### ISSUE THREAD

**Issue by dcxpolska** [allegro/allegro-api#6593]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Proszę o aktywację sprzedaży dla konta DCXPolska log@dcx.eu
Cały czas trwa proces "Weryfikacji firmy"

Dziękuję.

**Comment by Lukasz-Zurek** [comment]
@dcxpolska W naszej bazie na Allegro Sandbox nie ma takiego konta.

**Comment by dcxpolska** [comment]
Dzień dobry,

 

Nie mamy założonego innego konta na Allegro, więc są to jedyne dane do
rejestracji jakie posiadamy.

Cały czas widnieje informacja o weryfikacji danych Firmy.

 

Proszę o pomoc.

 



 

 

Kind regards / Pozdrawiam,





 <https://meetings.hubspot.com/t-buk/video-call-with-dcx> 

 <https://meetings.hubspot.com/t-buk/video-call-with-dcx> Interested?
Schedule a quick call to get your quote!




 

Małgorzata Salamonowicz
Logistic Specialist at DCX

 

DCX Polska Sp. z o.o.

ul. Poleczki 23

02-822 Warszawa

 

NIP 9462689288


 <tel:+%2048%20661%20244%20%20602> + 48 661 244 602
 .   ***@***.***> ***@***.***  . Sales office:
Warsaw, Poland .
<http://cryptocooling.eu/?utm_source=WiseStamp&utm_medium=email&utm_term=&ut
m_content=&utm_campaign=signature> http://cryptocooling.eu/


	


 <https://www.linkedin.com/company/dcx-immersion-mining>
<https://www.youtube.com/c/DCXLiquidImmersionCooling/featured>
<https://twitter.com/dcx_immersion>

**Comment by Lukasz-Zurek** [comment]
Ok. Wszystko zatem wskazuje na to, że Twoje pytanie dotyczy konta na produkcji w Allegro.pl - w tej sytuacji skontaktuj się proszę za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=61571da6-f6de-4b8f-9ab9-699c8c797cfc&subjectId=35c2c795-4f94-49e2-8057-bbf00efe4433).
