### ISSUE TITLE
Konto Allegro - Zablokowana sprzedaż

### ISSUE THREAD

**Issue by tomasznowacki4** [allegro/allegro-api#6594]
Dzień dobry, czy mogę prosić o odblokowanie konta Allegro w środowisku sandbox:
Client:44324115
Mam informacje "Zablokowana sprzedaż" a saldo mam 0. Regulaminu raczej nie naruszyłem :) Dziękuję za pomoc.
Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Odblokowałem Twoje konto :) Możesz już działać.
