### ISSUE TITLE
Limit czasu zapytania - nowa oferta

### ISSUE THREAD

**Issue by algru1** [allegro/allegro-api#6595]
Widzę, ze problem kategorii został rozwiązany. Ale teraz otrzymuję błąd po kliknięciu 'Wystaw przedmiot'.
![image](https://user-images.githubusercontent.com/122799117/213126297-7313b43e-9129-42af-babc-3dc81e171f23.png)

Dziękuję. Teraz jednak mam problem z wystawieniem oferty. Nie ma znaczenia czy wybieram istniejący produkt czy próbuję zdefiniować nowy otrzymuję błąd nieprawidłowej kategorii (Kategoria wybierana z listy - efekt ten sam).
![image](https://user-images.githubusercontent.com/122799117/212831772-f43eaa3c-c05a-475d-b19d-2debe7cacb1c.png)

_Originally posted by @algru1 in https://github.com/allegro/allegro-api/issues/1046#issuecomment-1384922103_

**Comment by Lukasz-Zurek** [comment]
Potwierdzam, że mamy nowe problemy dotyczące wystawiania ofert na Sandboxie. Weryfikujemy temat. Proszę o cierpliwość.
