### ISSUE TITLE
Brak możliwości weryfikacji konta

### ISSUE THREAD

**Issue by bymbyn12** [allegro/allegro-api#6596]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [X] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Nie można zweryfikować konta firmowego
Login: polska123443321
email: bymbym@o2.pl

**Comment by MaciejFrackowiak** [comment]
Na jaki konkretnie problem natrafiasz? Czy pojawia się jakikolwiek komunikat błędu?

**Comment by bymbyn12** [comment]
Nie mam komunikatu o błędzie.
Wybrałem weryfikację uproszczoną, za pomocą konta i nie przechodzi dalej
Próbowałem pełną i tak samo
Pomimo wypełnienia warunków zwrotu, reklamacji i ustawienia dostaw nadal wymaga uzupełnienia.
Jak to przejść?

**Comment by MaciejFrackowiak** [comment]
Czy przeszedłeś cały krokowiec wraz z etapem przelewu weryfikacyjnego z poziomu zakładki [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta)?

**Comment by bymbyn12** [comment]
zatrzymałem się na przelewie
Przy próbie szybkiego przelweu online mam taki komunikat "Szybki przelew online jest niedostępny, zmień IBAN lub skorzystaj z przelewu tradycyjnego"
Natomiast przy przelewie tradycyjnym nic się nie dzieje.

**Comment by bymbyn12** [comment]
Czy można te konto zweryfikować by można było na nim wpełni działać?

**Comment by MaciejFrackowiak** [comment]
Oczywiście można, tylko niestety na chwilę obecną wygląda, że nie przeszedłeś całego "krokowca" - wykonałeś przelew, ale niezbędnych plików do weryfikacji firmy już nie przesłałeś.

**Comment by bymbyn12** [comment]
wystarczy dowolny obrazek czy jakies faktyczne dane?
Jeśli dowolny to zrobiłem wszystko

**Comment by MaciejFrackowiak** [comment]
Na Sandbox zawsze podawaj/przesyłaj "zmyślone" dane. Twoje konto jest już zweryfikowane.

**Comment by bymbyn12** [comment]
Dziekuje

**Comment by bymbyn12** [comment]
Mam teraz inny problem
Chce korzystać z Wysyłka z Allegro i utknąłem na pobraniu statusu generowania etykiety
Dostaję taki błąd wywołując metodę https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/95d56729-90e5-407c-9085-837af8b2194d
"{
    "id": "95d56729-90e5-407c-9085-837af8b2194d",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "INVALID_CREDENTIALS_ERROR",
            "message": "Cant extract serviceId from credentials header",
            "details": null,
            "path": "x-authorization",
            "userMessage": "Nie można pobać serwisu"
        }
    ]
}"

**Comment by paweelkopec** [comment]
@MaciejFrackowiak 

Ja również ma podobny problem z weryfikacją konta na sanbnox :)
Wszystkie kroki zostały wypełnione, plików nie da się wysłać ponownie.
Konto testowe sanbox: client:105875282
Login paweel

**Comment by MaciejFrackowiak** [comment]
@paweelkopec Twoje konto jest już zweryfikowane.

**Comment by MaciejFrackowiak** [comment]
@bymbyn12 Weryfikuję ten przypadek z zespołem, wrócę z odpowiedzią.

**Comment by bymbyn12** [comment]
Witam,
Czy już coś wiadomo w mojej sprawie?

**Comment by MaciejFrackowiak** [comment]
@bymbyn12 Nie, nie mam jeszcze odpowiedzi.

**Comment by MaciejFrackowiak** [comment]
@bymbyn12 Próbujesz nadać przesyłkę opartą o umową własną DPD, ale nie podałeś szczegółów tej umowy w ustawieniach WzA.
