### ISSUE TITLE
Czy w metodzie PUT /parcel-management/parcel-create-commands/{commandId} mogę w jakiś sposób dodać zdefiniowany gabaryt paczki?

### ISSUE THREAD

**Issue by zales2** [allegro/allegro-api#6597]
Dla kuriera Allegro Punkty Poczta, Żabka oraz Allegro Pocztex Kurier 48 podając wymiary 16x10x10cm i 2kg paczka tworzy sie w gabrycie XXL, mimo że takie wymiary odpowiadałyby gabarytowi M. Czy da się to w jakiś sposób zmienić, a jeśli nie to czy planujecie stworzenie dodatkowego parametru, dla kurierów posiadających z góry zdefiniowane gabaryty?

**Comment by MaciejFrackowiak** [comment]
Nie, stosujemy jedno rozwiązanie, bez rozróżniania gabarytów przesyłki. Z dostępnych mi danych wynika, że nie planujemy takiej zmiany w najbliższej przyszłości.
