### ISSUE TITLE
Get parcel label - Not acceptable representation requested

### ISSUE THREAD

**Issue by rxgxs21** [allegro/allegro-api#6598]
Zasób Get parcel label zwraca "Not acceptable representation requested" - "Please check 'Accept' request header"
Accept header ma ustawioną wartość "application/vnd.allegro.public.v1+json".
Inne zapytania na tak samo skonfigurowanym kliencie działają prawidłowo.

**Comment by MaciejFrackowiak** [comment]
Dla zasobu [GET /parcel-management/parcels/label](https://developer.allegro.pl/documentation/#operation/getParcelLabel) właściwy nagłówek to "application/pdf" lub "text/plain".
