### ISSUE TITLE
Parametry użytkownika (customerParameters) w POST /sale/product-offers

### ISSUE THREAD

**Issue by lukiopmoto** [allegro/allegro-api#6599]
Dzień dobry,

Chciałbym się zapytać o parametry dodatkowe (customerParameters) które można było dodawać podczas wystawiania oferty poprzez: [POST /sale/offers]. W metodzie [POST /sale/product-offers] nie widzę możliwości dodawania dodatkowych (niestandardowych parametrów). Czy to prawda, że z tego zrezygnowaliście? **Proszę o zaprzeczenie lub potwierdzenie.**

Dodałem ofertę przez formularz z parametrem dodatkowym, pobrałem przez API [GET/sale/product-offers/xxx] i nie było tego parametru.

Pozdrawiam
Łukasz

**Comment by MaciejFrackowiak** [comment]
Zgadza się, obecnie zasoby /product-offers nie obsługują jeszcze parametrów własnych - pracujemy, aby wprowadzić ich obsługę.

**Comment by lukiopmoto** [comment]
Dziękuję. Wdrożenie będzie raczej na dniach, tygodniach czy bardziej miesiącach? Pytam bo nie wiem czy kodować pomocnicze kawałki kodu czy sobie na razie dać spokój (bo wdrożenie po Państwa będzie za pół roku)

**Comment by MaciejFrackowiak** [comment]
Niestety, na chwilę obecną nie jestem w stanie podać jednoznacznej deklaracji terminu wdrożenia tej zmiany.
