### ISSUE TITLE
[REST] Różnice w /order/checkout-forms i /order/checkout-forms/{id}

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#660]
Hej,
Czy dane zwracane w podanych zasobach czymś się różnią (dla pojedynczego zamówienia)?
Z moich obserwacji wynika że nie, więc drugie pytanie: czy w przyszłości mogą się czymś różnić?

**Comment by PawelTaberski** [comment]
Nie ma różnicy co do pojedyńczych zamówień. przy pomocy metody GET na zasobie /order/checkout-forms pobierzesz maksymalnie 100 najnowszych zamówień. Natomiast GET-em na zasobie /order/checkout-forms/{checkoutForm_id}, otrzymasz szczegóły określonego zamówienia. Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/orders/).
