### ISSUE TITLE
Przesyłki a raport z pobrań 

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#6600]
Dzień dobry,
czy dodali już może Państwo możliwość pobrania informacji o rozliczeniu danego pobrania w danym przelewie zbiorczym od Państwa?

W jaki sposób mogę zidentyfikować zamówienia które są ujęte w danym przelewie zbiorczym z pobrań?

**Comment by MaciejFrackowiak** [comment]
Jaki konkretny zasób API masz tu na myśli?

**Comment by AleksyZajac** [comment]
Nie mam pojęcia, bo w dokumentacji tego nie znalazłem a problem był już tu poruszany ze 2 lata temu.

Nadal mamy problemy z rozliczaniem pobrań bo musimy wysyłać do Państwa prośby o przesłanie takiego raportu i po kilku dniach dostajemy z Waszego działu rozliczeń excela z listą zamówień do danego przelewu. Taki sposób jest lekko upierdliwy i chyba też mało efektywny dla Allegro?

Może warto coś z tym zrobić?

**Comment by MaciejFrackowiak** [comment]
Dotykasz kwestii stricte poza API, ponieważ rozliczanie kwot otrzymanych z pobrań i raport jest całkowicie poza nami. Swoje uwagi przekaż proszę poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&subjectId=2d542135-a6d7-474c-a4a1-f96451c8bbc5) bezpośrednio do obsługi Allegro i usługi Wysyłam z Allegro.

**Comment by AleksyZajac** [comment]
Szkoda, myślałem że może macie jakieś dodatkowe metody do raportowania.
Ale ok, skontaktuję z nimi przez formularz.
