### ISSUE TITLE
Clarification about Allegro Rest API authentication and use case

### ISSUE THREAD

**Issue by thomaskaestnerprocuros** [allegro/allegro-api#6601]
Hi,
I have a question regarding the Allegro API.
Following scenario: 
We try to fetch orders belonging to us from allegro on an hourly basis to forward them to an supplier software. We are working here with backend calls to the allegro api. 
From what I see we need to have the authorization from the user (customers) to call the https://api.{environment}/order/checkout-forms?
Is there any way to make the call without the users interaction? 
Kind regards

**Comment by MaciejFrackowiak** [comment]
No, there is no option - to retrieve orders user must give consent.

**Comment by thomaskaestnerprocuros** [comment]
Thanks for your answer
It's fine that we need the user contest for reading his orders, but what we try to achieve is the least manual effort for the allegro user
What we tried so far
- Device flow
1- /auth/oauth/device
2- verification link (Require human interaction)
3- /auth/oauth/token (with the refresh mechanism we are able to use the token for 3 months I guess)
- After 3 months the whole flow need to start from the beginning
      - This mean we need to talk to allegro user and ask then to repeat the step 2.
      Is there any easier way that requires maybe a user permission on the application creation without any further human interaction?

**Comment by hahyes** [comment]
> with the refresh mechanism we are able to use the token for 3 months I guess

@thomaskaestnerprocuros This is not how it works. Access token is valid for 12 hours. Refresh token is valid for 3 months OR it becomes unvalid in moment, where you use refresh token. Refreshing token gives you new pair of tokens (access and refresh). If you authorize once you can refresh token infinitely (until some error occure on Allegro side, but it is very rare).

**Comment by MaciejFrackowiak** [comment]
Thanks @hahyes for your answer. I will add that we described the whole process in [our tutorial](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#extending-token-validity).
