### ISSUE TITLE
Device flow - autoryzacja użytkownika An error has occurred

### ISSUE THREAD

**Issue by paweelkopec** [allegro/allegro-api#6602]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

**Request:** 

```
curl -X POST \
  'https://allegro.pl/auth/oauth/device?client_id={client_id}' \
  -H 'Authorization: Basic {base64(client_id:client_secret)}' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
```

Client ID oraz Client Secret są prawidłowe w zapytaniu.
**Response :** 

`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/auth/oauth/device","userMessage":null}]}`

https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow:

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę cały request w formacie cURL - korzystając z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Zweryfikuję dokładnie ten przypadek.

**Comment by paweelkopec** [comment]
Wysyłany.

**Comment by paweelkopec** [comment]
@Lukasz-Zurek W dokumentacji https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow:, brakuje naguatlato HTTP      'accept: */*',
Poniżej, podaje poprawny request w curl :)

```
curl -X POST \
  'https://allegro.pl/auth/oauth/device?client_id={client_id}' \
  -H 'Authorization: Basic {base64(client_id:client_secret)}' \
  -H 'Content-Type: application/x-www-form-urlencoded' \`\
 -H 'accept: */*'
```

Należy pamiętać o zmianie wartości `{base64(client_id:client_secret)}'` na base64 przed wysłaniem requestu w curl.

**Comment by Lukasz-Zurek** [comment]
@paweelkopec Nie jest to nagłówek wymagany do tego, aby zrealizować żądanie, dlatego go nie podajemy. Mimo wszystko bardzo Ci dziękuję za czujność.

Czy udało Ci się ostatecznie z requestem? Nie otrzymałem jeszcze zgłoszenia, ale oczywiście jak tylko do mnie dotrze - zweryfikuję problem.

**Comment by paweelkopec** [comment]
Tak, problem rozwiązany. Request przechodzi tylko  z nagłówkiem. 
Zgłoszenie z request zostało wysłane.

**Comment by Lukasz-Zurek** [comment]
@paweelkopec Spojrzałem jeszcze na request. Wspomniałeś, że korzystasz z Postmana - w tej sytuacji nagłówek */* domyślnie jest ukryty. Być może na początku był odznaczony, trudno powiedzieć. W moim przypadku niezależnie od tego czy jest zaznaczony, czy też nie - request przechodzi prawidłowo. Kluczowy jest tutaj 'Content-Type: application/x-www-form-urlencoded'. 

Najważniejsze, że udało się Tobie rozwiązać problem :)
