### ISSUE TITLE
403 ProductProposalsAccessForbiddenException - brak dostępu

### ISSUE THREAD

**Issue by kochanA** [allegro/allegro-api#6603]
Dzień dobry, chciałam dodać ofertę przez api sandbox ale dostaję błąd 403 ProductProposalsAccessForbiddenException - brak dostępu wzorowałam się na odpowiedziach do pytania #6017 zmieniłam rodzaj konta na firmowe, przy wysyłaniu oferty do api sandbox ciagle ten sam błąd przy wystawianiu oferty przez konto na podstawie produktu wyskakuje komunikat "Aby aktywować sprzedaż zweryfikuj konto". Proszę o podpowiedz w tej sprawie, co zrobić żebym mogła wystawiać oferty poprawnie. Client ID 78e65fe899da45588fc26446d7fcb1a0 #6603

**Comment by Lukasz-Zurek** [comment]
Przyczyna faktycznie leży po stronie braku weryfikacji konta firmowego. Aktywowałem je, ale proszę jeszcze [ustawić wypłaty](https://allegro.pl.allegrosandbox.pl/myaccount/newpayments_payout.php), by zweryfikować konto firmowe. Oczywiście w razie problemów, proszę o kontakt.

**Comment by kochanA** [comment]
dziękuję za odpowiedz, z poziomu konta pojawiła się możliwość dodawania ofert. Obecnie potrzebuję dostępu tylko do wystawiania, edytowania i usuwania ofert, czy niezbędne jest do tego ustawianie wypłat ? Bo próbuję wystawić ofertę przez API sandbox na podstawie przykładowego produktu z katalogu ale mam error 403 OfferAccessDeniedException - "Access denied. You are not authorized to perform operations on the indicated offer"

**Comment by kochanA** [comment]
dobrze, a czy mogłabym prosić więcej informacji na temat symulatora płatności ? Jak z niego skorzystać ?

**Comment by Lukasz-Zurek** [comment]
Symulator płatności symuluje realizację wpłaty w ramach weryfikacji ustawień wypłat w [tej zakładce](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty). Po uzupełnieniu danych (w tym również numeru konta) będziesz mogła skorzystać z opcji realizacji takiej płatności (opcja "Zrób przelew online"), następnie zostaniesz przekierowana na stronę operatora płatności (również w środowisku testowym), gdzie wystarczy jedynie zatwierdzić taką płatność.

**Comment by kochanA** [comment]
Panie Łukaszu przeszłam przez ustawienie wypłaty środków czy trzeba przejść wszystkie 5 kroków do tego aby wystawiać testowe oferty ?

**Comment by Lukasz-Zurek** [comment]
@kochanA Wykonała Pani kluczowy krok (ustawienia wypłat), dzięki czemu mogłem Pani w pełni zweryfikować konto :) Może już Pani w pełni korzystać z konta.

**Comment by kochanA** [comment]
@Lukasz-Zurek  dziękuję za dotychczasową pomoc, coś jednak nadal jest nie tak. Przy próbie pobrania ofert wystawionych z poziomu konta ponownie wyskakuje błąd :
403 {"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"Access denied. Contact the author of the application."}]} 

to samo przy próbie wysłania oferty do API sandbox : 403 {"errors":[{"code":"AccessDeniedException","message":"Access is denied","details":null,"path":null,"userMessage":"No access."}]}

**Comment by Lukasz-Zurek** [comment]
@kochanA Co prawda nie posiadam trace-id by to dokładnie sprawdzić, jednak wszystko wskazuje na to, że autoryzowałaś się poprzez [Client_credentials flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow) bez kontekstu użytkownika, dlatego nie masz dostępu do takich zasobów jak np. [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET). Client_credentials flow pozwala na uzyskanie ogólnodostępnych danych np. listy kategorii i parametrów, etc.

Skorzystaj proszę z innego sposobu autoryzacji, np. [Authorization Code flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow).

Wszystkie sposoby autoryzacji i uwierzytelniania opisaliśmy w [naszym poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#wstep).

**Comment by Lukasz-Zurek** [comment]
@kochanA Ok, już wiem, że nie to jest powodem błędu. Prawdopodobnie przyczyna nadal leży po stronie samego konta. Proszę o cierpliwość. Wyjaśnię to i wrócę z informacją.

**Comment by kochanA** [comment]
@Lukasz-Zurek dobrze, czekam w takim razie na odpowiedź

**Comment by Lukasz-Zurek** [comment]
@kochanA Pobieranie listy ofert na koncie powinno działać bez problemu, podobnie jak proces wystawiania ofert.

**Comment by kochanA** [comment]
@Lukasz-Zurek nic się w tej kwestii nie zmieniło, wzięłam przykładowy kod ze strony gdzie była opisana autoryzacja:

[allegro_sandbox.docx](https://github.com/allegro/allegro-api/files/10488899/allegro_sandbox.docx)

pobieranie kategorii działa ale gdy zmieniam zapytanie na "https://api.allegro.pl.allegrosandbox.pl/sale/offers"

dostaje taka odpowiedz : {'errors': [{'code': 'AccessDenied', 'message': 'Access is denied', 'details': None, 'path': None, 'userMessage': 'Access denied. Contact the author of the application.'}]}

gdyby to były błędy połączenia z moim kontem to nic nie mogłabym zrobić. Jedyną akcję związaną z ofertami jaką jestem w stanie wykonać to dodać ofertę z poziomu konta allegro sandbox.

**Comment by Lukasz-Zurek** [comment]
@kochanA Na podstawie przesłanych informacji jednak przyczyna leży po stronie sposobu autoryzacji client_credentials. Czyli autoryzowałaś się poprzez [Client_credentials flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow) bez kontekstu użytkownika, dlatego nie masz dostępu do takich zasobów jak np. [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET). Client_credentials flow pozwala na uzyskanie ogólnodostępnych danych np. listy kategorii i parametrów, etc. Zgodnie z tym co napisałem wcześniej.

Skorzystaj proszę z innego sposobu autoryzacji, np. [Authorization Code flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow).

**Comment by kochanA** [comment]
@Lukasz-Zurek dziękuję za odpowiedź, jestem na 1 kroku Autoryzacji gdzie generuje link z przekierowaniem do zalogowania się,  "https://allegro.pl/auth/oauth/authorize?response_type=code&client_id={client_id}&redirect_uri={url}".
Zalogowanie się jest jednak nie możliwe zmieniałam już kilka razy hasło bo myślałam ze się pomyliłam, próbowałam więc włączyć opcje logowania dwustopniowego za pomocą nr telefonu ale nie dostaję kodu autoryzacyjnego. Co mogę zrobić w takiej sytuacji ?

**Comment by Lukasz-Zurek** [comment]
@kochanA Podejrzewam, że chcesz przejść przez proces autoryzacji na sandboxie, a w tej sytuacji powinnaś użyć innego adresu do autoryzacji: https://allegro.pl.allegrosandbox.pl/auth/oauth/

Próbujesz autoryzować się na koncie na produkcji, dlatego pojawia się błąd nieprawidłowych danych do logowania.

**Comment by kochanA** [comment]
@Lukasz-Zurek faktycznie pomieszałam adresy, dziękuje
