### ISSUE TITLE
Communication error with carrier's API occurred - Wystąpił błąd komunikacji z API przewoźnika

### ISSUE THREAD

**Issue by rxgxs21** [allegro/allegro-api#6605]
Konto Sandbox: polski_24
CommandId: c9488bff-bf85-4896-86f6-ab49d416ecf7

Przy odpytywaniu zasobu: /parcel-management/parcel-create-commands/{commandId}

Zasób dla powyższego commandId zwraca status: Error z wiadomością:
Communication error with carrier's API occurred - Wystąpił błąd komunikacji z API przewoźnika

Czy jest to spowodowane moim błędem, czy istnieje wewnętrzny błąd?

**Comment by hahyes** [comment]
@rxgxs21 Zazwyczaj ten błąd występuje, gdy wystąpi błąd pomiędzy Allegro a przewoźnikiem. Nie można z tym nic zrobić.

**Comment by MaciejFrackowiak** [comment]
@rxgxs21 W większości przypadków to efekt błędu, o którym wspomina @hahyes. Przesyłki Allegro One nie obsługują ponadto opcji inne dane nadawcy, w związku z tym w polu label.sender przekazuj null lub w ogóle pomiń je.

**Comment by rxgxs21** [comment]
Wczoraj jeszcze działało, więc raczej błąd na linii allegro przewoźnik

**Comment by rxgxs21** [comment]
Błąd nadal występuje.

**Comment by MaciejFrackowiak** [comment]
@rxgxs21 Proszę podaj trace-id swojego wywołania.

**Comment by rxgxs21** [comment]
595a0f6b-b2be-40a5-b949-5149b9208397

**Comment by rxgxs21** [comment]
Trace-Id to Command-Id przkeazywany do requesta?

**Comment by MaciejFrackowiak** [comment]
Nie, trace-id to identyfikator wywołania, który my zwracamy w odpowiedzi. I bez niego dotarłem do logów Twojego wywołania - kwestię samego błędu wyjaśniamy z dostawcą usługi.

**Comment by rxgxs21** [comment]
Czy coś już wiadomo odnośnie problemu?

**Comment by MaciejFrackowiak** [comment]
Niestety, wciąż czekamy na odpowiedź.

**Comment by MaciejFrackowiak** [comment]
Problem w Twoim przypadku spowodowała zawartość pola "description":"---------------------" - mechanizm odczytywał to jako nieprawidłowe wyrażenie.

**Comment by rxgxs21** [comment]
Jakie wyrażenie spełni warunki?

**Comment by MaciejFrackowiak** [comment]
Coś bardziej oddającego opis np. abc aniżeli ciąg "-".

**Comment by rxgxs21** [comment]
Przetestowałem z ciągiem losowych liter - "dfafsdfagfgsdfgsdfgsdfgargsfddfafsdfagfgsdfgsdfgsdfgargsfd".
Wynik ten sam.

**Comment by MaciejFrackowiak** [comment]
Proszę podaj konkretne trace-id swoich wywołań - tylko tak jak wspominałem możemy sprawdzić logi.

**Comment by rxgxs21** [comment]
eba1fc0c5d9220a1

**Comment by MaciejFrackowiak** [comment]
Jak widzę wykonałeś kilkadziesiąt requestów PUT z tym samym commandId, co tłumaczy uzyskiwaną przez Ciebie odpowiedź od nas. Zwracamy odpowiedź dla pierwszego wykonanego requestu z danym commandId, resztę ignorujemy. Jednym słowem - każde kolejne wywołanie wykonuj z nowym commandId.
