### ISSUE TITLE
Problem z zakańczaniem ofert

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6606]
Czy występują problemy z edycją oraz zakańczaniem ofert? Wykonuję PATCH /sale/product-offers/{offerId} i pomimo przekazania statusu ENDED oferty nie zakańczają się. Nadmienię, że do tej pory działało wszystko poprawnie. Problem występuje również przy próbie aktualizacji treści ofert - w odpowiedzi otrzymujemy kod 200 a dane po stronie portalu nie, są aktualizowane. Problem dotyczy oczywiście środowiska produkcyjnego

**Comment by Lukasz-Zurek** [comment]
@mateuszcom Jeżeli problemy będą się powtarzać - daj proszę znać.
