### ISSUE TITLE
Sesje api allegro

### ISSUE THREAD

**Issue by Przedek1** [allegro/allegro-api#6607]
Jedno z kont (z dwóch) podpiętych do mojego api co jakiś czas wylogowuje się(z wersji przeglądarkowej). Z tego, co wyczytałem, to prawdopodobnie chodzi o przekroczoną ilość aktywnych sesji. I tutaj moje pytanie. Api jako sesje liczy każde wywołane polecenie, czy każdy wygenerowany klucz dostępu?

**Comment by MaciejFrackowiak** [comment]
Limit sesji wynosi 20 jednocześnie. Jeżeli ponownie się zalogujesz (czy to przez WWW czy API) i powstanie 21 sesja, to sesja nr 1 straci swoją ważność. Nie bierzemy tu pod uwagę każde wywołanie zasobu, a generowaną parę access + refresh token.

**Comment by Przedek1** [comment]
Jeszcze jedno pytanko. Access token traci swoją ważność(wygasa sesja) minutę po wygenerowaniu nowego tokenu, czy dopiero po 12 godzinach i 1 minucie, nawet jeżeli wcześniej został wygenerowany nowy token?

**Comment by MaciejFrackowiak** [comment]
Tak, każde wygenerowanie nowej pary tokenów powoduje usunięcie ważności poprzedniej.

**Comment by Przedek1** [comment]
Jeżeli wygenerowanie nowego tokenu zabija poprzednią sesje, to nie rozwiązuje to mojego problemu z wylogowaniem konta co kilka godzin. Jest możliwość sprawdzenia logowania się/tworzenia nowych tokenów na danym koncie?

**Comment by MaciejFrackowiak** [comment]
Pamiętaj, że każda aplikacja, którą logujesz na danym koncie np. aplikacja mobilna Allegro również wlicza się w limit aktywnych sesji.

**Comment by Przedek1** [comment]
Na szczęście konto jest używane tylko na jednym komputerze, sporadycznie ktoś się zaloguje z innego. Poza tym mam podłączone jest 8 aplikacji i nikt nie wiem, która za co odpowiada. Podejrzewam, ze co najmniej dwie są już dawno nie używane, ale nie dam sobie ręki uciąć, ze nie zajmują sesji. Pracownicy allegro będą w stanie zweryfikować z jakiej aplikacji ile jest logowań?

**Comment by MaciejFrackowiak** [comment]
Tak, posiadają możliwość sprawdzenia logowań na wskazanym koncie.

**Comment by Przedek1** [comment]
> Tak, posiadają możliwość sprawdzenia logowań na wskazanym koncie.

To czekam na odpowiedź allegro. Ale w sumie to już nie wiem o co chodzi. Bo inne konta, które nie używają mojego api też co chwile są wylogowywane. To nie jakiś nowy wymysł allegro?

**Comment by MaciejFrackowiak** [comment]
Aby uzyskać informacje dot. logowań skontaktuj się bezpośrednio poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=0cad5ed6-ca26-4669-8ff0-6a7da503fe80&subjectId=8b7d668e-6f52-47e4-8c6b-cfb5e985789a) Allegro.

**Comment by jakubmaguza** [comment]
> > Tak, posiadają możliwość sprawdzenia logowań na wskazanym koncie.
> 
> To czekam na odpowiedź allegro. Ale w sumie to już nie wiem o co chodzi. Bo inne konta, które nie używają mojego api też co chwile są wylogowywane. To nie jakiś nowy wymysł allegro?

Jakiś wymysł jest. Moje konto (bez żadnej dodatkowej aplikacji, tylko 1 przeglądarka + 2 mobilne) średnio z raz w tygodniu wylogowuje się z przeglądarki.

**Comment by FishBeat** [comment]
Potwierdzam, że coś jest na rzeczy. U mnie 5 kont - jedna apka i od tygodnia kilka razy dziennie wywala (apka działała do tej pory bezbłędnie jakieś 3 lata).

**Comment by MaciejFrackowiak** [comment]
@jakubmaguza @FishBeat Jeżeli macie jakiekolwiek pytania dot. logowania i opisanych tu problemów proszę skontaktujcie się bezpośrednio z [obsługą serwisu](https://allegro.pl/pomoc/kontakt?kategoria=0cad5ed6-ca26-4669-8ff0-6a7da503fe80&subjectId=8b7d668e-6f52-47e4-8c6b-cfb5e985789a).

**Comment by mojosoft** [comment]
U nas też od około tygodnia jest problem z tokenami, wcześniej działało to bez problemu, żądnych zmian w kodzie itp

**Comment by MaciejFrackowiak** [comment]
@mojosoft Dotarło do nas Twoje zgłoszenie, niestety nie widzę w nim żadnych przykładowych danych. Niebawem otrzymasz wiadomość od konsultanta z prośbą przesłanie przykładowych tokenów (access, refresh), dat wystąpienia problemu, itp.

**Comment by FishBeat** [comment]
@MaciejFrackowiak - a co ze mną? Napisałem przez link podany tutaj i dostałem jakże błyskotliwą odpowiedź:

Odpowiedź na zgłoszenie nr "31005920"
W kwestii zewnętrznej aplikacji niestety nie będę Panu w stanie pomóc. W takiej sytuacji należałoby się skontaktować z producentem/dystrybutorem danej aplikacji.

Natomiast w kwestii autoryzacji nie było zmian.

Odpisałem, że to ja jestem autorem tej aplikacji zgłaszam problem - od dłuższego czasu cisza.

**Comment by MaciejFrackowiak** [comment]
@FishBeat Ostatecznie zgłoszenie właśnie do nas dotarło - niestety, nie widzę w nim żadnych przykładowych danych. Niebawem otrzymasz wiadomość od konsultanta z prośbą przesłanie przykładowych tokenów (access, refresh), dat wystąpienia problemu, itp.

**Comment by Przedek1** [comment]
Jakiś czas temu coś zmieniło się z curlem. Miałem problem jakiś miesiąc temu w nodejs, a z tydzień temu w php. Dokładnie nie wiem, co się zmieniło, ale w node wystarczyło wywalić puste pola, a w php usunąć spację

**Comment by MaciejFrackowiak** [comment]
@FishBeat W swoich wywołaniach przekazujesz "ssl", co nie jest prawidłowym adresem. Właściwe adresy to  "https://allegro.pl/auth/oauth/authorize" jako AuthorizationUri i "https://allegro.pl/auth/oauth/token" jako TokenUri.

**Comment by FishBeat** [comment]
Dzięki, zmienię i sprawdze. A z ciekawości - to się jakoś zmieniło ostatnio gdyż te adresy mam tak wpisane od kilku dobrych lat i zawsze działało.

Ps. Jak by ktoś na przyszłość miał problem - to rozwiązanie jest takie: Zapisujcie proszę tokeny do bazy, NIGDY do pliku. To był mój błąd!

**Comment by MaciejFrackowiak** [comment]
@FishBeat Dawno temu - ssl przestaliśmy wspierać w marcu 2018 roku - [tu](https://github.com/allegro/allegro-api/issues/65) znajdziesz info.
