### ISSUE TITLE
Aktualizacja tytułu aukcji

### ISSUE THREAD

**Issue by Jacob1293** [allegro/allegro-api#6608]
Dzień dobry, 

Mam pytanie, czy mogę zaktualizować po Rest API tylko nazwę aukcji?? 
Jak tak, to w jaki sposób najlepiej to zrobić?? Posiadam ponad 1000 produktów i w każdej aukcji muszę dołożyć dopisek do jej nazwy. Szukam sposobu, żeby uniknąć ręcznej modyfikacji każdego produktu z osobna.

**Comment by MaciejFrackowiak** [comment]
Poprzez API możesz modyfikować dowolne pola oferty (oczywiście uwzględniając wszelkie istotne ograniczenia), jednak nie ma zasobu do aktualizacji tylko tytułu oferty.

**Comment by Jacob1293** [comment]
Ok, czyli w momencie puszczania aktualizacji za pomocą metody [PATCH /sale/product-offers/{ID}] muszę uwzględnić wszystkie pozycje z oferty, bo jak puszczę puste pola to zamieni mi wartość obecną na puste tak ??

**Comment by MaciejFrackowiak** [comment]
Korzystając z [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) możesz zmienić tylko konkretne pole z oferty, w tym przypadku pole "name". Musisz jednak pamiętać, że dla ofert, w których dokonano już zakupu nie zmienisz tytułu.
