### ISSUE TITLE
[sugestia] Nowa funkcja /orders/payments

### ISSUE THREAD

**Issue by nataniel** [allegro/allegro-api#661]
W związku z #659 - nie ma w tej chwili de facto możliwości połączenia informacji z Zestawienia (gdzie są pola nr płatności, nr oferty, login kupującego) z konkretnym CheckoutForm :(, a tym samym nie istnieje możliwość sensownego rozliczenia transakcji (np. w systemie księgowym).

Może w API powinna pojawić się funkcja /orders/payments, analogiczna do /orders/events? Powinna ona pobierać nie tylko płatności od kupujących, ale także zwroty - tak aby dawała pełny obraz transakcji na koncie Allegro Finanse.

**Comment by PawelTaberski** [comment]
Zgłosiłem Twoją sugestię do odpowiedniego zespołu, jeśli zdecydujemy się wdrożyć takie rozwiązanie poinformujemy o tym.

**Comment by horacy70** [comment]
Czy zmieniło się może coś w Waszym stanowisku? Podobnie jak w zestawieniach, nadawanie przesyłki "Allegro Paczkomaty24/7 InPost" również wymaga podania "starego" numeru płatności.

Czy rozważaliście np. dodanie w metodzie 'https://api.allegro.pl/order/checkout-forms' w sekcji 'payment' pola ze starym numerem płatności?

**Comment by PawelTaberski** [comment]
Nie planujemy wprowadzania tam starego numeru raczej przejście wszędzie na nowy numer, m.in. w tej kwestii trwają rozmowy z InPostem. Jak tylko będziemy mieli jakieś konkretne informacje w tym temacie poinformujemy o tym w osobnym komunikacie.
