### ISSUE TITLE
APLIKACJA API

### ISSUE THREAD

**Issue by Cyber-Przemo** [allegro/allegro-api#6611]
Czy macie udostępnioną aplikację którą można zaimplementować do swojej strony? 
a dokładnie chodzi o obsługę emaili, jako autoresponder, czy do odpowiadania na dyskusje ?

**Comment by MaciejFrackowiak** [comment]
Nie, jako Allegro udostępniamy wyłącznie zasoby API. Natomiast domeną firm trzecich jest udostępnianie gotowych rozwiązań dla użytkowników.
