### ISSUE TITLE
Zamówienie nie zostało pobrane.

### ISSUE THREAD

**Issue by suczarczyk** [allegro/allegro-api#6612]
Dzień dobry, z jakiegoś powodu zamówienie a06775e0-95a9-11ed-bc25-21661d93bf50 nie zostało pobrane do Idosell. 
Od integratora otrzymałam informację: "Z jakiegoś powodu nasz system w ogóle nie widzi tego zamówienia i nie jestem w stanie w ogóle go pobrać w żaden sposób. W tym momencie nie mamy jak sprawdzić przyczyny, bo wygląda to tak, jakby Allegro przez API w ogóle nie przesłało do nas informacji, że istnieje takie nowe i opłacone zamówienie." 
Jaka może być przyczyna?

**Comment by MartaNowaczyk** [comment]
Dzień dobry, z tego co widzę zamówienie można pobrać, jednak sprawdzam jeszcze czy odpowiedni event dla tego zamówienia został wygenerowany poprawnie, aby integracja miała informację o zamówieniu. Wrócę z odpowiedzią jak tylko to ustalę.

**Comment by MartaNowaczyk** [comment]
Potwierdzam, że to wina po naszej stronie. Rzeczywiście informacja o zamówieniu nie dotarła do Idosell. Ponowiliśmy event, zamówienie powinno być już widoczne. Przepraszamy za wszelkie niedogodności z tym związane.

**Comment by suczarczyk** [comment]
Dzień dobry, dziękuję Pani Marto za wszystkie informacje. Czy gdyby taki problem pojawił się w przyszłości zgłosić go do Państwa tutaj na forum?

**Comment by MartaNowaczyk** [comment]
Dzień dobry, forum to odpowiednie miejsce do takich zgłoszeń. Tak jak w tym przypadku, najpierw proszę skontaktować się z obsługą Idosell, a jeśli stwierdzą, że to problem po naszej stronie prosimy o kontakt. Pozdrawiam.

**Comment by suczarczyk** [comment]
Rozumiem, dziękuję i pozdrawiam.
