### ISSUE TITLE
Produkturyzacja 2024 a parametry ofert

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#6613]
Dzień dobry,
Z racji na wasze aktualności na temat zmiany wizji wystawiania przez allegro API 
https://developer.allegro.pl/news/na-poczatku-2024-roku-wylaczymy-zasoby-sale-offers-sluzace-do-tworzenia-i-edycji-ofert-BvqK3XOaEcW 

Chciałbym się zapytać jak sprawa ma się wyglądać do parametrów produktu. Czy przewidujecie stałe usunięcie/modyfikację ich z Allegro w 2024? Co praktycznie trzeba będzie podać w formularzu wystawiania produktu, czy pełna produkturyzacja wykluczy z nas obowiązek przydzielania parametrów aukcji/produktu?

**Comment by MartaNowaczyk** [comment]
Jeśli chodzi o planowane zmiany w funkcjonowaniu allegro w temacie parametrów produktu skontaktuj się proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
