### ISSUE TITLE
Błąd w aktualizacji danych oferty

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#6614]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
trace-id (get): e6fb501e6b00511b

Zgodnie z produkturyzacją nasza aplikacja oczekuję na zwrot danych formie productSet. Dlaczego więc przy próbie fetchowania aukcji dostajemy pusty productSet? Jest to nam niezbędne do aktualizacji aukcji, bo gdy bierzemy dane z tego endpointa to w aktualizacji danych aukcji dostajemy error, że podaliśmy złe parametry.  
```
{
    "name": "Męska Bluza adidas Entrada 22 Sweat Hoodie biała",
    "productSet": [],       /* <- czemu tutaj dostajemy posty productSet */ 
    "parameters": [
      {
        "id": "11323",
        "name": "Stan",
        "values": [
          "Nowy"
        ],
        "valuesIds": [
          "11323_1"
        ],
        "rangeValue": null
      }
    ],
(...)
}
```

**Comment by Lukasz-Zurek** [comment]
W requeście nie przekazujesz w ogóle **product.id**, natomiast oferta nie ma obecnie przypisanego produktu, w związku z czym zwracamy "productSet": []

**Comment by DamianKAtomStore** [comment]
> W requeście nie przekazujesz w ogóle **product.id**, natomiast oferta nie ma obecnie przypisanego produktu, w związku z czym zwracamy "productSet": []

Jak więc mam zaktualizować taką aukcję? Najpierw trzeba przypisać produkt?

**Comment by Lukasz-Zurek** [comment]
Wszystko zależy od tego, co konkretnie chcesz zaktualizować. Za pomocą [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) edytujesz dowolne pole i jednocześnie nie musisz tutaj przekazywać całej struktury. Więcej informacji na ten temat znajdziesz [tutaj](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pojedynczej-oferty).

Jeśli natomiast chcesz przypisać produkt do oferty (lub go zmienić), przekaż identyfikator produktu w product.id, a w odpowiedzi automatycznie zaktualizujemy kategorię i parametry, opis, itd. Więcej informacji w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-przypisac-produkt-do-oferty).

**Comment by DamianKAtomStore** [comment]
[PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers)
Problem jest taki, że w naszym systemie dajemy możliwość na zmianę paru rzeczy w aukcji więc siłą rzeczy musimy pobrać wszystkie dane aukcji, problem sie pojawia między pobraniem info aukcji a wysłaniem tego przez PATCH /sale/product-offers/{offerId}. Czy może to zależeć od tego, że aukcja została wystawiona starym endpointem?
