### ISSUE TITLE
 Nie możemy wyświetlić strony  Numer błędu: 2cee1292eed9c55b

### ISSUE THREAD

**Issue by jakubwcreo** [allegro/allegro-api#6615]
Występuje problem:
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Próbuje się zautentykować tzn. dostać tokeny od allegro. Muszę to zrobić bo utraciłem refresh token i nie mogę go użyć, dlatego potrzebuje jeszcze raz otrzymać tokeny. Otwieram okno przeglądarki z adresem:
https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=1434889cce6a4e30b9dedecf783f55b0&redirect_uri=https://apart.test/manager/allegro
ale niestety dostaje taki błąd:
![Screenshot_5](https://user-images.githubusercontent.com/123367879/214017911-315ccb07-410d-4598-8d51-5ffc84daa487.png)
Proszę o pomoc.

**Comment by Lukasz-Zurek** [comment]
Używasz nieprawidłowego redirect-uri. Powinien być zgodny z tym, który został podany podczas [rejestracji aplikacji](https://apps.developer.allegro.pl.allegrosandbox.pl).

**Comment by jakubwcreo** [comment]
Dziękuję za odpowiedź. To rozwiązało problem
