### ISSUE TITLE
Problem z przesłaniem parametru oferty (definitions of the parameter...)

### ISSUE THREAD

**Issue by morawcik** [allegro/allegro-api#6617]
Cześć.
Jakbym nie próbował przesłać parametru `rodzaj` dla oferty (czy to po id - valuesIds, id - values, name - valuesIds, name - values czy nawet po wszystkich 4 polach/wartościach) to zawsze zwracany jest błąd

> The definitions of the parameter `249229:Rodzaj` were incorrectly specified as a parameter in section `offer`.

Mógłbym prosić o nakierowanie co robię źle?

```
$response = Http::withHeaders([
    'Authorization' => "Bearer $accessToken",
    'Accept' => "application/vnd.allegro.public.v1+json",
    'Content-Type' => "application/vnd.allegro.public.v1+json",
])->post("$apiUrl/sale/product-offers", [
    'productSet' => [
        ['product' => ['id' => $allegroProduct['id']], 'quantity' => ['value' => 1]]
    ],
    'category' => ['id' => $allegroProduct['category']['id']],
    'parameters' => [
        ['name' => 'Stan', 'values' => ['Nowy']],
        ['id' => '249229', 'valuesIds' => ['249229_1121162']]
    ],
    'payments' => ['invoice' => 'VAT'],
    'sellingMode' => ['format' => 'BUY_NOW', 'price' => ['amount' => 100.00, 'currency' => 'PLN']],
    'stock' => ['available' => 10, 'unit' => 'UNIT']
]);
```
przykładowy trace-id - fafec8ae8b1a7670

Edit:
Jak już opublikowałem pytanie to podszedłem do tego nieco inaczej i okazuje się, że pomimo iż parametr jest wymagany w ofercie i produkcie (w produkcie aktualnie go nie ma) to muszę go przesłać tylko w `productSet.product.parametres`. 
Zakładam, że jeśli parametr jest wymagany i tu i tu to trzeba go wysłać tylko w produkcie a jeśli jest wymagany w ofercie a nie w produkcie to wtedy przesyłam go w ofercie tak jak próbowałem powyżej?

**Comment by MartaNowaczyk** [comment]
Tak, parametry produktowe, które mają "describesProduct": true powinny być umieszczone w sekcji productSet w polu product.parameters, a nie w parameters (to pole odpowiedzialne jest za parametry ofertowe, które szerzej opisaliśmy [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#parametry-ofertowe)).
