### ISSUE TITLE
Problem z ciągłością w działaniu bez powodu wywala 404 bez żadnych zmian.

### ISSUE THREAD

**Issue by jakkazdy** [allegro/allegro-api#6619]
Mamy problem z integracją.

Postanowiliśmy postawić integracje w celu aktualizacji cen i stanów, w przyszłości zamówienia.
Niestety mamy problem gdyż występuje u nas problem z nagłym 404 przy próbie nawet pobrania danych użytkownika(me).
Posiadamy dwa konta i potrzebujemy przy pobieraniu tokena odpytać o dane konta.

Jeśli chodzi o sam token to pobiera go bez problemu problem pojawia się dopiero przy pobraniu danych(me) lub pobraniu/aktualizacji stanow/cen.

Kod który raz działa a raz nie działa prezentuje poniżej:
```
 $headers = array("Authorization: Bearer {$token}","Content-Type: application/vnd.allegro.public.v1+json","Accept: application/vnd.allegro.public.v1+json");
      $content = "";
      $ch = $this->getCurlApi($headers, $content, 'me');
      $tokenResult = curl_exec($ch);
      $errorCode = curl_error($ch);
      $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
      curl_close($ch);
```

```
public function getCurlApi($headers, $content, $url){
      $ch = curl_init();
      curl_setopt_array($ch, array(
          CURLOPT_URL => $this->urlApi.'/'.$url,
          CURLOPT_HTTPHEADER => $headers,
          CURLOPT_SSL_VERIFYPEER => false,
          CURLOPT_SSL_VERIFYHOST => false,
          CURLOPT_RETURNTRANSFER => true,
          CURLOPT_POST => false
      ));
      return $ch;
    }
```

`public $urlApi = 'https://api.allegro.pl';`

Otrzymuje niestety rezultat: 
```
<!--#set var="code" value="404" -->
<!--#set var="reason" value="Not Found" -->
<!--#set var="msg" value="The server cannot find the requested page:" -->
<!--#include virtual="cp_errordocument.shtml" -->
```

**Comment by MartaNowaczyk** [comment]
Podaj proszę trace-id dla problematycznego wywołania.

**Comment by jakkazdy** [comment]
Przy prawidłowym zapytaniu```
HTTP/2 200 
trace-id: 3be95d7ba2c4b4ca
date: Tue, 24 Jan 2023 13:06:54 GMT
content-type: application/vnd.allegro.public.v1+json
content-length: 232
```

ale...

Dostałem informacje z hostingu: "Coś nam się dns gubi jeśli chodzi o tą subdomenę i trudno mi stwierdzić dlaczego 
dodałem mu lokalnie tą subdomenę ze wskazaniem na IP allegro to powinno rozwiązać problem
błędu 404"

**Comment by MartaNowaczyk** [comment]
Podałes prawidłowe zapytanie, stąd rozumiem, że problem już nie występuje?

**Comment by jakkazdy** [comment]
Nie miałem jak pobrać trace-id przy błędzie. Aktualnie działa i wydaje mi się że do zamknięcia.
Problemem było gubienie się DNS'a po stronie hostingu.

**Comment by jakkazdy** [comment]
Dzisiaj wszystko bez problemu. Zamykam temat. Dziękuję za pomoc!
