### ISSUE TITLE
[REST] Sortowanie w order/checkout-forms

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#662]
Po której dacie jest sortowana zwrotna lista z zasobu order/checkout-forms?
W odpowiedzi znalazłem dwie daty - datę płatności i datę zakupu 'line item'.
Przy wyborze płatności przy dostawie, nie ma daty płatności.

Co jeśli ktoś zamówi jakiś przedmiot np. 01.01.2019 i sfinalizuje 'checkoutForm' 05.01.2019.
Czy macie jeszcze jakąś dodatkową datę po której sortujecie?

Chodzi mi o sortowanie przy zastosowaniu parametrów limit i offset, bo sama zwrócona lista zamówień nie jest posortowana (co nie jest problemem).

**Comment by PawelTaberski** [comment]
Nie wiem, czy dobrze zrozumiałem Twoje pytanie, ale przy wyborze okresu z jakiego chcesz pobrać zamówienia metodą GET na zasobie /order/checkout-forms możesz skorzystać z filtra po dacie zamówienia, nie możesz wysortować po dacie płatności. Więcej na ten temat [tutaj](https://developer.allegro.pl/orders/).

**Comment by jakubmaguza** [comment]
Inaczej:
Jeśli ustawię offset na 1, to skąd wiecie które zamówienie pominąć? Po którym polu to sprawdzacie?

**Comment by PawelTaberski** [comment]
Zamówienia są sortowane od najnowszych do najstarszych, także offset=0 zwróci jako pierwszy wynik najnowsze zdarzenie. natomiast jako 1 zwróci kolejne. Offset przyjmuje wartości od 0 do liczba zamówień -1.

**Comment by jakubmaguza** [comment]
@PawelTaberski Tak, to się zgadza, więc ponownie pytam, które pole jest używane do wyznaczenia które zamówienie jest nowsze?

**Comment by mack3d** [comment]
Póki klient nie zapłaci, nie otrzymasz zdarzenia READY_FOR..., Zakup będzie miał status FILLED_IN.
Co nie zmienia faktu że też jestem ciekaw odpowiedzi.

**Comment by jakubmaguza** [comment]
Dziękuję za odpowiedź.
Proszę potwierdzić czy mam rację:
1. Ktoś dokonuje zamówienia, ale jeszcze nie finalizuje płatności. Zostaje przypisana data 'boughtAt'
2. Dostaję w tzw. międzyczasie 10 innych zamówień.
3. Ktoś finalizuje płatność z zamówienia 1.

Przy wywołaniu 'https://api.allegro.pl/events/checkout-forms?status=READY_FOR_PROCESSING'
za parametrami offset 0 i limit 10, zamówienie nr. 1 nie zostanie zwrócone, tak?

**Comment by jakubmaguza** [comment]
Szkoda, nie moglibyście tego zmienić na datę zatwierdzenia formularza? W momencie kiedy klient kupi, a zapłaci tydzień później, to może być problem.

**Comment by tztztztz** [comment]
> 
> 
> Sortowanie w zasobie /order/checkout-forms działa malejąco po polu 'boughtAt' czyli dacie zakupu.

Niestety, nie działa, nie ma sortowania po boughtAt, jest przypadkowa kolejność - przynajmniej u mnie, więcej tuta: https://github.com/allegro/allegro-api/issues/648

**Comment by jakubmaguza** [comment]
Według mnie zwracana lista jest posortowana, ale zwracany wynik nie. Czyli odpowiednio pomija rekordy, ale w zwrotce są one wysyłane w dowolnej kolejności. Można to zauważyć odpytując kilka razy ten sam zasób i porównując wyniki. Tak jak wspominałem, to raczej nie jest problem, bo sortować można lokalnie.

**Comment by tztztztz** [comment]
Hmmm lista jest posortowana, ale wynik nie? Przecież to jest nielogiczne :) Jeżeli cały zbiór danych jest posortowany, to podzbiór tego zbioru także jest posortowany.

Wysyłam zapytanie do API, i dostaję np. pierwszy rekord sprzedaż wg. boughtAt o godz. 17, nastepny rekord z godz. 9, a kolejny z godz 11, a potem jeszcze np. rekord w ogóle z poprzedniego dnia.

Może ten wynik jest posortowany, ale na pewno nie wg. "boughtAt".

**Comment by PawelTaberski** [comment]
@jakubmaguza W takim wypadku najlepiej śledzić najnowsze zdarzenia, a następnie pobierać szczegóły zamówienia już dla konkretnego zamówienia, przy pomocy metody GET na zasobie [/order/checkout-forms/{checkoutForm_id}](https://developer.allegro.pl/documentation/#/order-management/get_order_checkout_forms__id_).

**Comment by jakubmaguza** [comment]
@tztztztz Wiem, to może być nielogiczne, ale jak masz metodę wielowątkową pakującą wynik, może się tak zdarzyć, że będzie bez sortowania :) Oczywiście nie mam pojęcia jak jest zaimplementowane po stronie API.
@PawelTaberski tak, to jest druga opcja. Po checkout-forms byłoby łatwiej, ale skoro nie ma takiej możliwości, to będę używał eventów.

**Comment by tztztztz** [comment]
Jeżeli o mnie chodzi to już nie mam czasu czekać na sortowanie. Po prostu pobieram sprzedaż z danego wycinka czasu i analizuje wszystko zakładając, że kolejność jest przypadkowa, więc jeżeli o mnie chodzi nie ma już problemu właściwie.

**Comment by expondo** [comment]
Panie Pawle, skoro temat został zamknięty to oznacza że problem jest rozwiązany?
Jakoś nie widzę rozwiązania pobierając dane z API.

Kiedy można się spodziewać zakończenia tematu, ponieważ skoro daliście taką metodę to fajnie by było z niej korzystać.

**Comment by PawelTaberski** [comment]
Nie widzę, abyś w tym wątku zgłaszał jakiś problem z zamówieniami, jeśli chodzi Tobie o błędne sortowanie to widzę, że tego dotyczy wątek numer #648 . Jeśli problem u Pana również występuje proszę wznowić ten wątek, bądź założyć świeży.
