### ISSUE TITLE
Problem z PUT /sale/offers

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#6620]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] z logowaniem lub autoryzacją / with login or authorization

:beetle: **Opis / Description**
Witam,
>` PUT /sale/offers/12917158426` zwraca mi błąd: `400 unauthorized - Authorization header does not contain space after 'Bearer'.`
Sprawdzałem i po Bearer jest spacja: `authorization: Bearer eyJhbGci...`

A dziwniejsze jest to, że dla innej oferty `PUT /sale/offers/12917158258` działa poprawnie.

Proszę o pilną pomoc!

**Comment by Lukasz-Zurek** [comment]
Błędne żądanie odnotowałem tylko dla GET /sale/offers/12917158426, ale z logów wynika, że to była tylko jedna taka sytuacja. Oczywiście mogę to dokładnie zweryfikować, potrzebowałbym jednak pełnego requestu w formacie json. Możesz go przesłać kontaktując się z nami poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
