### ISSUE TITLE
Allegro DHL zagranica - error.common.processing

### ISSUE THREAD

**Issue by relains** [allegro/allegro-api#6621]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Mam problem z wygenerowaniem etykiety do Irlandii za pomocą kuriera Allegro DHL.

***Request****
`{
	"event": {
		"method": "PUT",
		"path": "/",
		"query": {},
		"client_ip": "178.216.201.212",
		"url": "https://api.allegro.pl/parcel-management/parcel-create-commands/9db1612b-2028-4b34-a6cb-b361536c0ea0",
		"headers": {
			"host": "api.allegro.pl",
			"content-length": "855",
			"authorization": "Bearer SecretSecret",
			"accept-language": "pl",
			"accept": "application/vnd.allegro.public.v1+json",
			"content-type": "application/vnd.allegro.public.v1+json"
		},
		"body": {
			"serviceId": "2274665b-926c-4d75-bb48-707a3f1be43b",
			"receiver": {
				"address": {
					"street": "18D Euro Business Park",
					"postCode": "T45DP80",
					"city": "Little Island",
					"countryCode": "IE"
				},
				"email": "fxf0w23yoi+559e35b47@allegromail.pl",
				"name": "Michal Sochacki",
				"company": "IPP IRL Ltd",
				"phone": "872168315",
				"pointId": null
			},
			"pickup": {
				"address": {
					"street": "ul. Fabryczna 25b",
					"postCode": "90-341",
					"city": "Łódź",
					"countryCode": "PL"
				},
				"email": "kontakt@drogeriaolmed.pl",
				"company": "OLMED",
				"phone": "422334909",
				"pointId": null
			},
			"items": [
				{
					"weight": {
						"value": 1,
						"unit": "KILOGRAM"
					},
					"dimensions": {
						"height": {
							"value": 50,
							"unit": "CENTIMETER"
						},
						"width": {
							"value": 30,
							"unit": "CENTIMETER"
						},
						"depth": {
							"value": 20,
							"unit": "CENTIMETER"
						}
					},
					"description": "Artykuły drogeryjne",
					"type": "PACKAGE"
				}
			],
			"type": "PACKAGE",
			"label": {
				"sender": null,
				"fileFormat": "PDF",
				"referenceNumber": "23012312001621"
			}
		}
	},
	"context": {
		"id": "2Klp4RWJ1ttXZfJFP0yrGh8Uixo",
		"ts": "2023-01-24T11:13:51.872Z",
		"pipeline_id": null,
		"workflow_id": "p_k2Cr9QA",
		"deployment_id": "d_evsPvNAz",
		"source_type": "COMPONENT",
		"verified": false,
		"hops": null,
		"test": false,
		"replay": false,
		"owner_id": "u_k2hQp5b",
		"platform_version": "3.36.1",
		"workflow_name": "RequestBin",
		"resume": null,
		"trace_id": "2Klp4OYi1PYkP598MhRxxIGHQUA"
	}
}`

***Response***
`(
	[id] => 9db1612b-2028-4b34-a6cb-b361536c0ea0
		[parcelId] =>
		[status] => ERROR
		[errors] => Array
		(
			[0] => Array
		(
			[code] => ERROR
			[message] => Processing error
			[details] =>
			[path] =>
			[userMessage] => error.common.processing
		)
	)
)`

**Comment by Lukasz-Zurek** [comment]
Potwierdzam występujący problem. Obecnie jest on weryfikowany przez zespół odpowiedzialny za usługę "Wysyłam z Allegro". Przepraszamy za zaistniałe utrudnienia.

**Comment by Lukasz-Zurek** [comment]
@relains Poprawka została wdrożona, w związku z czym problem nie powinien już występować.
