### ISSUE TITLE
Brak dostępu do danego zasobu - parcel-create-commands 

### ISSUE THREAD

**Issue by bartekc7** [allegro/allegro-api#6623]
Dzień dobry,

Proszę o wskazówkę jakich uprawnień i gdzie może brakować jeżeli przy próbie dodania przesyłki "Wysyłam z Allegro" przez API dostaję poniższą zwrotkę. Lista sposobów dostaw/zamówień się pobiera bez problemu na uprawnieniach tej aplikacji. 

https://api.{environment}/parcel-management/parcel-create-commands/537d5a39-e1af-455d-8534-3352234cee30
Response: 403, Forbidden, 

{
  "errors": [
    {
      "code": "AccessDenied",
      "message": "Access is denied",
      "details": null,
      "path": null,
      "userMessage": "Brak dostêpu do danego zasobu."
    }
  ]
}

**Comment by Lukasz-Zurek** [comment]
@bartekc7 Twój token dostępowy nie posiada scope'a: **allegro:api:orders:write**, a jest on wymagany do korzystania z [PUT /parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/createNewParcel). Możesz go dodać z poziomu [tej zakładki](https://apps.developer.allegro.pl), wchodząc w "szczegóły" i "edytuj". Będziesz musiał jednak na nowo się autoryzować.

**Comment by bartekc7** [comment]
Dziękuje za pomoc. Po ponownej autoryzacji przeszło więc można zamknąć zgłoszenie.
