### ISSUE TITLE
Duplikat przy propozycji produktu

### ISSUE THREAD

**Issue by BartlomiejCalus** [allegro/allegro-api#6624]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Podczas wystawiania produktu, którego nie powinno być w systemie (zapytanie https://api.{environment}/sale/products w odpowiedzi zwraca pustą listę produktów) przesyłamy propozycję produktu w odpowiedzi otrzymujemy błąd mówiący o duplikacie. W nagłówku odpowiedzi jest podana lokalizacja z id którego nie obsługujemy, więc nie jesteśmy w stanie sprawdzić gdzie i dlaczego występuje powtórzenie.

**Comment by AureliuszBrussy** [comment]
Prześlij proszę trace-id wywołania, które zwróciło informację o duplikacie produktu. Podaj proszę także trace-id wywołania, gdzie próbujesz wyszukać produktu (lub chociaż query parametry wraz z wartościami w zapytaniu).

**Comment by BartlomiejCalus** [comment]
Dla wyszukania produktu: 4b8da76897a96efb
Dla propozycji, gdzie zwróciło duplikat: c94ad0fe9583f81b

**Comment by AureliuszBrussy** [comment]
@BartlomiejCalus na podstawie przekazanych przez Ciebie danych w propozycji produktu rozpoznaliśmy duplikat - EAN nie zawsze jest rozstrzygający. Możesz znaleźć ten produkt np. po kodzie producenta (zmień w wyszukiwaniu **mode** na MPN i w **phrase** wprowadź kod producenta). Dobrą praktyką może być skorzystanie ze zwracanego przez nas headera **Location**, gdzie wskazujemy istniejący produkt.

**Comment by BartlomiejCalus** [comment]
Zmiana na kod producenta naprawiła sprawę. Dzięki za pomoc
