### ISSUE TITLE
Blokada IP

### ISSUE THREAD

**Issue by kowalikus** [allegro/allegro-api#6625]
Serwer nie może skomunikować się z API Allegro. Czy mogło dojść do blokady IP? Jak to sprawdzić? Jak dowiedzieć się z jakiego powodu została nałożona blokada? Jak odblokować?

**Comment by AureliuszBrussy** [comment]
Blokada IP może wystąpić, natomiast wszystko zależy od okoliczności. Jaki request wykonujesz oraz jakie response otrzymujesz?

**Comment by kowalikus** [comment]
Indywidualna integracja działa od wielu lat dla kilku kont klienta (setki tysięcy ofert). Jest Timeout w zasadzie na każdy request do API ale także   na `curl -X GET  https://allegro.pl/`.

**Comment by AureliuszBrussy** [comment]
Podaj proszę adres IP serwera. Jeżeli nie chcesz go podawać tutaj, możesz to zrobić przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). W treści zgłoszenia wskaż tylko numer wątku na GitHubie: #6625. Sprawdzę to.

**Comment by kowalikus** [comment]
@AureliuszBrussy Dzięki, wysłane formularzem.

**Comment by kowalikus** [comment]
@AureliuszBrussy Jakieś wieści?

**Comment by AureliuszBrussy** [comment]
Podaj proszę numer zgłoszenia z formularza. Postaram się przyspieszyć sprawę.

**Comment by AureliuszBrussy** [comment]
@kowalikus mam już adres IP. Wyjaśniam to. Możliwie szybko wrócę z informacją.

**Comment by kowalikus** [comment]
@AureliuszBrussy Dziękuję

**Comment by kowalikus** [comment]
Zaczęło działać
