### ISSUE TITLE
Witam, potzrebuje połączyć program do faktur faktura xl jak mam to zrobić?

### ISSUE THREAD

**Issue by faktury** [allegro/allegro-api#6626]

**Comment by faktury** [comment]
Witam, potzrebuje połączyć program do faktur faktura xl jak mam to zrobić?

**Comment by AureliuszBrussy** [comment]
Skontaktuj się z supportem oprogramowania, z którego chcesz skorzystać i do którego chcesz pobierać zamówienia. To oni udzielą Ci informacji czy jest to możliwe.

**Comment by faktury** [comment]
Problem lezy po stronie allegro w rejestracji aplickaji oraz client id

śr., 25 sty 2023 o 10:58 AureliuszBrussy ***@***.***>
napisał(a):

**Comment by AureliuszBrussy** [comment]
Nową aplikację na środowisku produkcyjnym możesz zarejestrować w [Allegro Developer Apps](https://apps.developer.allegro.pl/). Jaki dokładnie problem występuje z rejestracją aplikacji?

**Comment by AureliuszBrussy** [comment]
Niestety, jednak nie zobaczę załącznika dołączonego do wiadomości emailowej w zgłoszeniu na GitHubie. Przekaż proszę załącznik bezpośrednio w zgłoszeniu: https://github.com/allegro/allegro-api/issues/6626.

**Comment by faktury** [comment]
Przesyłam załącznik [](url)

**Comment by faktury** [comment]
Jak mogę go dodać?

**Comment by AureliuszBrussy** [comment]
Jeżeli masz problem z przesłaniem pliku, możesz to zrobić korzystając z naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). W treści zgłoszenia dopisz proszę numer wątku na GitHubie: #6626.

**Comment by faktury** [comment]
Wysłałwm maila z problemem

**Comment by AureliuszBrussy** [comment]
@faktury dziękuję, zespół biura obsługi klienta przekaże nam wiadomość. Tymczasem jednak spróbuj skorzystać z [tego linka](https://apps.developer.allegro.pl/new) - być może tym razem uda się utworzyć nową aplikację.

**Comment by faktury** [comment]
Niestety nie działa nie przechodzi do rejestracji

śr., 15 lut 2023 o 12:35 AureliuszBrussy ***@***.***>
napisał(a):

**Comment by AureliuszBrussy** [comment]
@faktury zgłoszenie do nas dotarło, jednak brak w nim załącznika o którym pisaliśmy. Załącz proszę plik w korespondencji w sprawie numer 31454566.
