### ISSUE TITLE
Brak netPrice w GET sale/product-offers/{offerId} 

### ISSUE THREAD

**Issue by g-radzio** [allegro/allegro-api#6627]
Zgodnie z informacjami typu: https://github.com/allegro/allegro-api/issues/6481

Zacząłem przechodzić z wycofywanych zasobów na te, które sugerujecie, jednak natrafiłem na nieścisłość.

Do tej pory przy pobieraniu struktury oferty za pomocą GET sale/offers/{itemId} dostawałem między innymi cenę netto (sellingMode.netPrice.amount)

```
  ["sellingMode"]=>
  object(stdClass)#51 (5) {
    ["format"]=>
    string(7) "BUY_NOW"
    ["price"]=>
    object(stdClass)#52 (2) {
      ["amount"]=>
      string(5) "31.44"
      ["currency"]=>
      string(3) "PLN"
    }
    ["startingPrice"]=>
    NULL
    ["minimalPrice"]=>
    NULL
    ["netPrice"]=>
    object(stdClass)#53 (2) {
      ["amount"]=>
      string(5) "29.94"
      ["currency"]=>
      string(3) "PLN"
    }
  }
```

Jednak gdy próbowałem użyć GET sale/product-offers/{itemId}, to w sellingMode nie dostałem netPrice.

```
  ["sellingMode"]=>
  object(stdClass)#88 (4) {
    ["format"]=>
    string(7) "BUY_NOW"
    ["price"]=>
    object(stdClass)#89 (2) {
      ["amount"]=>
      string(5) "31.44"
      ["currency"]=>
      string(3) "PLN"
    }
    ["startingPrice"]=>
    NULL
    ["minimalPrice"]=>
    NULL
  }
```

Czy to jakieś niedopatrzenie i mam spodziewać się, że netPrice będzie zwracane w GET sale/product-offers/{itemId} podobne jak w GET sale/offers/{itemId}? A jeżeli nie, to w jaki sposób mam to pobierać bez używania zasobu, który zostanie całkowicie wyłączony?

**Comment by Lukasz-Zurek** [comment]
Słuszna uwaga. Dopytuję właśnie odpowiedniego zespołu. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
Wracam z informacją - zespół odpowiedzialny za tę funkcjonalność zaktualizuje to. Nie jestem jednak w stanie zadeklarować tutaj konkretnego terminu zmiany.

**Comment by g-radzio** [comment]
Witam, wracam z tematem.
W styczniu pytałem o rozbieżność między wycofywanym zasobem GET sale/offers/{itemId} oraz używanym obecnie GET sale/product-offers/{itemId}.
W sale/product-offers/{itemId} sellingMode miało zostać uzupełnione o netPrice, choć nie wiadomo, w jakim terminie.

Z końcem roku stary zasób ma zostać ostatecznie wycofany, a w nowym wciąż brakuje ceny netto. Kiedy można spodziewać się uzupełnienia tego braku (co zostało tu zapowiedziane w styczniu)?
