### ISSUE TITLE
Podany adres obrazka jest nieprawidłowy.

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#6629]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

```
Array
                (
                    [code] => OfferImagesNotFoundException
                    [message] => Provided image address is incorrect.
                    [details] => OfferImagesNotFoundException
                    [path] => 
                    [userMessage] => Podany adres obrazka jest nieprawidłowy.
                )

```

Na moment wysyłania request zdjęcia które wstawiłem były aktywne i dostępne, prosto z przeglądarki.

:beetle: **Opis / Description**
trace-id: c58b59e76b4c1dac

**Comment by Lukasz-Zurek** [comment]
Problem był z jednym ze zdjęć z produktu na środowisku testowym. Przepraszamy za te utrudnienia.

Spróbuj teraz.
