### ISSUE TITLE
[REST] tworzenie draftów na sandbox

### ISSUE THREAD

**Issue by krzysztoffigiel** [allegro/allegro-api#663]
Witam,

Mam problem z jednoczesnym utworzeniem 300 draftów za pomocą pętli. Przy każdym obiegu wysyłany jest jeden draft w celu odebrania id potrzebnego później do wystawienia oferty. W trakcie wykonania próby wysłania 300 draftów na części z nich dostaję http status `503` i `504` oraz dodatkowo informację _Serwer nie jest w stanie zrealizować zapytania. Spróbuj ponownie później_. Dodatkowo na części requestów w response dostaję wiadomość: _Przekroczono czas wykonania zapytania. Spróbuj ponownie._ . Dodam że wysyłając 100 draftów w pętli wszystko przechodzi bez zarzutu. Działam na adresie sandbox. Nie jest to czasem kwestia tego że operuję na adresie testowym? Z góry dziękuję za pomoc.

**Comment by PawelTaberski** [comment]
Może to byś spowodowane tym, że wysyłasz requesty w zbyt małym odstępie czasowym. Podeślij nam przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) request i respond oraz trace-id przykładowego requesta, który zakończył się takim błędem. Sprawdzimy w czym jest problem.

**Comment by PawelTaberski** [comment]
Przetestowałem Twojego requesta i nie udało mi się powtórzyć tego błędu, ale przekazałem Twoją sprawę do odpowiedniego zespołu do weryfikacji. Proszę o cierpliwość.
