### ISSUE TITLE
API. Jak zmienić czas dostawy z 48H na 24H dla wszystkich ofert?

### ISSUE THREAD

**Issue by lukiopmoto** [allegro/allegro-api#6630]
Dzień dobry,

Na wyrost przy wystawianiu ofert ustawiłem 48H czas dostawy czyli PT48H. Jak się jednak okazuje 100% przesyłem dociera do klientów na drugi dzień. **Czy jest jakaś metoda w REST API która umożliwi masową zmianę handlingTime z PT48H na PT24H?**  Nie mogę ustawić godziny dla wysyłki tego samego dnia bo dotyczy ona tylko wysyłki "natychmiast" lub "24h".

Jeżeli nie ma takiej metody i trzeba aktualizować oferta po ofercie to proszę podać jakim zasobem to najsprawniej i najszybciej wykonam.

Pozdrawiam
Łukasz

**Comment by Lukasz-Zurek** [comment]
Niestety nie ma takiej metody, która umożliwiłaby zbiorczą zmianę czasu wysyłki w ofertach. Możesz natomiast skorzystać z metody [PATCH na zasobie /sale/product-offers/{offerID}](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pojedynczej-oferty), gdzie możesz przekazać tylko to pole, które chcesz edytować, czyli w tym przypadku - handlingTime. Jeden request jest jednak równoznaczny ze zmianą w jednej ofercie.

Więcej informacji na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pojedynczej-oferty).

**Comment by lukiopmoto** [comment]
Dobry wieczór. OK rozumiem, tylko w poradniku jest taki zapis: _Ważne! Jeżeli chcesz zachować aktualny opis, zdjęcia i parametry produktowe, oprócz product.id powinieneś przekazać również takie pola jak: description, images i product.parameters. Możesz je pobrać z edytowanej przez Ciebie oferty, korzystając z [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET)."_

To znaczy że jak przekażę w PATCH tylko handlingTime = PT24H to nie zachowam obecnych zdjęć i opisu dla wybranej oferty, której aktualizuję czas dostawy?

**Comment by Lukasz-Zurek** [comment]
Jeżeli nie chcesz, abyśmy aktualizowali Tobie ofertę na podstawie danych z produktu to te wymienione w ramce pola musisz przekazać. Parametry produktowe podlegają aktualizacji podczas zmian danych produktu w naszej bazie.

Natomiast jeśli chcesz dokonać aktualizacji konkretnego pola (czyli np. handlingTime) to przekazujesz tylko to jedno pole. Zachowasz pozostałe dane.

**Comment by mindc** [comment]
Wszystkich nie, ale w paczkach po maksymalnie 100 - chyba że coś się zmieniło - to szybciej niż pojedynczo.
Można to zrobić bez problemu za pomocą https://developer.allegro.pl/documentation#operation/modificationCommandUsingPUT

Przykładowe body requestu
```
{
  "modification": {
    "delivery": {
      "handlingTime": "PT24H"
    }
  },
  "offerCriteria": [
    {
      "offers": [ 
        {"id": ... }, 
        ... 
      ],
      "type": "CONTAINS_OFFERS"
    }
  ]
}
```
