### ISSUE TITLE
API (Wysyłam z Allegro) Jak pobrać adres domyślny zdefiniowany w Książce adresowej

### ISSUE THREAD

**Issue by luiggies** [allegro/allegro-api#6631]
Witam, 
czy za pomocą API (Wysyłam z Allegro) można pobrać adres domyślny zdefiniowany w Książce adresowej:
https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia

Jeśli tak to jak?
Pytam z nadzieją że można bo rozum podpowiada że skoro nie udało się odszukać tego w dokumentacji to pewnie nie można

**Comment by AureliuszBrussy** [comment]
Nie udostępniamy w ramach publicznego API książki adresowej Wysyłam z Allegro.

**Comment by luiggies** [comment]
A w ramach nie publicznego API jest dostępny taki zasób?
