### ISSUE TITLE
Encjowanie entities HTML nie działa

### ISSUE THREAD

**Issue by GHalbt** [allegro/allegro-api#6632]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Jako description w requescie przekazuje:
`<p>Lorem ipsum &quot;dolor&quot; sit amet</p>`

Aukcja na allegro:
![obraz](https://user-images.githubusercontent.com/120689175/214601659-d661320b-d799-4b15-971c-ec3308544b06.png)

Czy w tej sytuacji wystarczy tylko encjować symbol `&` na `&amp;`?

**Comment by AureliuszBrussy** [comment]
Przetestowałem to i encja `&quot;` zadziałała prawidłowo. Sprawdź, czy znak `&` w ciągu `&quot;`, gdy go wysyłasz na pewno nie jest zamieniony na encję. Możesz także podać trace-id wywołania (znajdziesz go w headerze naszego response'a), gdzie wysyłasz **description**. Sprawdzę ten konkretny przypadek.

**Comment by GHalbt** [comment]
Opis był ręcznie sprawdzony przed wysłaniem requestu do API. Nie ma tam żadnych &amp;

Problem rozwiązany został w sposób taki ze tylko & jest encjowane a resztę zamieniono na standardowe znaki UTF-8 (", ', <, >) i po sprawie.
