### ISSUE TITLE
Issue with offer publication via PATCH sale/product-offers/{offerId}

### ISSUE THREAD

**Issue by lukeroot** [allegro/allegro-api#6633]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Hi there, we have an issue with offer publication, specifically when trying to action an `INACTIVE`/`ENDED` publication value (Stock figure change works as expected)

[A very similar issue was raised 5 days ago](https://github.com/allegro/allegro-api/issues/6606) but was completed without solution.

Endpoint: PATCH https://api.allegro.pl/sale/product-offers/13179831085
TraceID: N/A
Payload:

```
{
    "productSet": [
        {
            "product": {
                "id": "8d916e91-5008-4e5b-96ae-7451904b9a26"
            },
            "quantity": {
                "value": 1
            }
        }
    ],
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "499.99",
            "currency": "PLN"
        },
        "minimalPrice": {
            "amount": "499.99",
            "currency": "PLN"
        },
        "startingPrice": {
            "amount": "499.99",
            "currency": "PLN"
        }
    },
    "delivery": {
        "handlingTime": "P3D",
        "additionalInfo": ""
    },
    "publication": {
        "status": "ENDED"
    }
}
```
Response (publication portion):
```
 "id": "13179831085",
 "language": "pl-PL",
 "publication": {
     "status": "ACTIVE",
     "duration": null,
     "endedBy": null,
     "endingAt": null,
     "startingAt": null,
     "republish": false
 },
``` 

Please can you provide understanding on how we can deactivate (0 stock figure) offers. 

Thanks

**Comment by AureliuszBrussy** [comment]
I don't see any PATCH request on this offer in our logs in the last 7 days. Can you provide the trace-id of the request? 

To deactivate the offer, you should send:

```
 {
  "publication": {
        "status": "ENDED"
    }
}
```

We do not accept the value of 0 in the **stock** field, so it is necessary to end the offer publication. 

Also, make sure you take into account that this is an asynchronous resource - some changes will not be made immediately. The status of our response says so: 

- 200 OK - when the request relates to modification of the offer's attributes that do not involve long-running operations. We will implement the changes immediately,

- 202 Accepted - when the request relates to long-running operations e.g. change of the offer publication status. We will perform the change asynchronously.

Here's the scheme:
![image](https://user-images.githubusercontent.com/68948612/214779289-3b4fa1c0-c76d-46af-b218-51416548d40b.png)

**Comment by lukeroot** [comment]
Got this working! Thanks for your help - just to clarify how I got this working:
New offer -
```
POST sale/product-offers/
{
    "publication": {
        "status": "ACTIVE"
    },
    "productSet": ...,
    "sellingMode": ...,
    "delivery": ...,
    "stock": ...,
}
```
Out of stock/Deactivate offer - 
```
PATCH sale/product-offers/{offerId}
{
    "publication": {
        "status": "ENDED"
    }
} 
```
Reactivate/In stock existing offer -
```
PATCH sale/product-offers/{offerId}
{
    "publication": {
        "status": "ACTIVE"
    }
    "stock": ...,
} 
```

Thanks again
