### ISSUE TITLE
Limit obrazków sprzeczny z komunikatem

### ISSUE THREAD

**Issue by GHalbt** [allegro/allegro-api#6634]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Zasób
`PATCH /sale/product-offers/{offerId}`

Przyjmuje maksymalnie 15 zamiast 16 obrazków przy wgrywaniu ich przez obiekt productSet -> [ product -> images ]

Komunikat przy wgrywaniu 16 obrazków:
`The limit of 16 images has been exceeded.`

**Comment by AureliuszBrussy** [comment]
Obsługujemy 16 obrazków. Sytuacja mogła wystąpić ze względu na to, że w requeście zawartych jest rzeczywiście więcej niż 16 zdjęć. Nadmiarowe zdjęcia mogły wystąpić w opisie lub produkcie. Abym mógł sprawdzić ten konkretny przypadek, prześlij proszę trace-id wywołania (zwracamy go w nagłówku naszej odpowiedzi).

**Comment by GHalbt** [comment]
Mam ten sam kod do metody POST. Na 50 tys aukcji 0 takich błędów. Przy aktualizacji obrazków dla PATCH już się takie pojawiają. Kod jest skonstruowany tak że nie pozwala na więcej niż 16 elementów w arrayu więc coś jest nie tak z API.

**Comment by AureliuszBrussy** [comment]
@GHalbt prześlij proszę trace-id wywołania, gdzie zwróciliśmy taki błąd. Sprawdzę to.
