### ISSUE TITLE
Faktury nie wyświetlają się w Centrum Wiadomości Allegro

### ISSUE THREAD

**Issue by eko-mixel** [allegro/allegro-api#6635]
Dzień dobry, mam powiązane konto Allegro z Baselinker. Posiadam ustawioną akcję automatyczną, przez którą klienci otrzymują faktury do Centrum Wiadomości na allegro. Niestety nie mogą otworzyć takich faktur. Otrzymują wiadomość z allegro: 'Wiadomość zawierała załącznik, którego nie możemy wyświetlić. Sprawdź, jakie rodzaje załączników pokazujemy.' (gif, bmp, tiff, jpeg, jpg, png) Bardzo prosiłbym o doradzenie co można w tej kwestii zrobić. Chciałbym aby faktury automatycznie wyświetlały się w Centrum Wiadomości do pobrania przez klienta lub żeby były wysłane pod adres email. Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Do wiadomości wysłanych z Centrum wiadomości można dodawać załączniku w formatach: .pdf, .gif, .bmp, .tiff, .jpeg, .jpg, .png. Jeżeli plik jest w jednym z tych formatów - Klient powinien móc pobrać taki załącznik.

Jeżeli plik jest wysyłany w jednym z tych formatów, a Klient ma problem z jego pobraniem - aby to wyjaśnić, może skontaktować się przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).

Dodam także, że w ramach API udostępniamy [dedykowany zasób](https://developer.allegro.pl/documentation/#operation/addOrderInvoicesMetadata) do dodawania faktury do zamówienia. Po dodaniu faktury kupujący otrzymuje powiadomienie z taką informacją i załącznik z plikiem. W kwestii użycia takiego zasobu przez integrację - skontaktuj się z supportem oprogramowania z którego korzystasz.
