### ISSUE TITLE
Zamówienie oznaczone jako nadpłata pomimo zwrotu pieniędzy

### ISSUE THREAD

**Issue by g-radzio** [allegro/allegro-api#6636]
Pobrałem za pomocą GET order/checkout-forms/f3058460-8b6b-11ed-b4bd-51ce1daa3410 dane dotyczące zamówienia. Fragment danych, który mnie interesuje to:

```
object(stdClass)#30 (14) {
  ["id"]=>
  string(36) "f3058460-8b6b-11ed-b4bd-51ce1daa3410"
  ["payment"]=>
  object(stdClass)#34 (6) {
    ["id"]=>
    string(36) "f35dde8f-8b6b-11ed-8d31-75937eb505b7"
    ["type"]=>
    string(6) "ONLINE"
    ["provider"]=>
    string(4) "PAYU"
    ["finishedAt"]=>
    string(24) "2023-01-04T11:31:33.244Z"
    ["paidAmount"]=>
    object(stdClass)#35 (2) {
      ["amount"]=>
      string(5) "35.14"
      ["currency"]=>
      string(3) "PLN"
    }
    ["reconciliation"]=>
    NULL
  }
  ["status"]=>
  string(20) "READY_FOR_PROCESSING"
  ["fulfillment"]=>
  object(stdClass)#36 (2) {
    ["status"]=>
    string(4) "SENT"
    ["shipmentSummary"]=>
    object(stdClass)#37 (1) {
      ["lineItemsSent"]=>
      string(3) "ALL"
    }
  }
  ["summary"]=>
  object(stdClass)#49 (1) {
    ["totalToPay"]=>
    object(stdClass)#50 (2) {
      ["amount"]=>
      string(5) "25.14"
      ["currency"]=>
      string(3) "PLN"
    }
  }
  ["updatedAt"]=>
  string(24) "2023-01-04T11:31:33.244Z"
  ["revision"]=>
  string(8) "bd4d65cd"
}
```
Zgodnie z poradnikiem https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#nadplaty-i-niedoplaty porównałem wartości z pól summary.totalToPay.amount i payment.paidAmount.amount

summary.totalToPay.amount = 25.14
payment.paidAmount.amount = 35.14

Jest nadpłata, więc klient dostał zwrot. Ale wciąż przy pobieraniu szczegółów zamówienia kwoty pozostają takie same. Z kolei po zalogowaniu do Allegro i sprawdzenia szczegółów zamówienia widzę, że dokonano zwrotu, jednak dalej mam informację o nadpłacie.

![Zrzut ekranu z 2023-01-26 09-12-25](https://user-images.githubusercontent.com/26047001/214787387-d6935f0c-edd8-4179-8a93-622bc4bf3347.png)
![Zrzut ekranu z 2023-01-26 09-12-41](https://user-images.githubusercontent.com/26047001/214787392-7f1cfcf4-5abc-4843-9899-a35f46c8cda7.png)

Jest to o tyle problematyczne, że przez nadpłatę nie możemy dodać faktury do zamówienia ani po zalogowaniu na konto na Allegro, ani przez API.

**Comment by AureliuszBrussy** [comment]
W strukturze zamówienia (checkout-forms) nie zwrócimy informacji o zwrotach płatności, tylko informacje o samej płatności oraz ewentualnej dopłacie. Aby pobrać informacje o zleconych zwrotach powinieneś skorzystać z [GET /payments/refunds](https://developer.allegro.pl/documentation/#operation/getRefundedPayments). Możesz dopasować zwrot to płatności za pomocą query parametru **payment.id**. 

Jaki problem występuje przy próbie dodania faktury VAT do zamówienia?

**Comment by g-radzio** [comment]
W logach znalazłem rzucony wyjątek:

```
{
	"errors":[
		{
			"code":"ORDER-WITHOUT-SUCCESSFUL-PAYMENT",
			"message":"Order with id [f3058460-8b6b-11ed-b4bd-51ce1daa3410] does not have a successful payment. paymentProvider: PAYU, paymentStatus: OVERPAID",
			"details":null,
			"path":"/order/checkout-forms/f3058460-8b6b-11ed-b4bd-51ce1daa3410/invoices",
			"userMessage":"Order with id [f3058460-8b6b-11ed-b4bd-51ce1daa3410] does not have a successfulpayment. paymentProvider: PAYU, paymentStatus: OVERPAID"
		}
	]
} 
```

Wygląda jakby nie było można dodać rachunku/faktury jeśli zamówienie jest oznaczone jako nadpłata. Problem w tym, że klient dostał już zwrot, więc nie wiem, co jeszcze możemy zrobić po naszej stronie.

**Comment by AureliuszBrussy** [comment]
Wygląda to na bug. Zgłosiłem ten przypadek do zespołu odpowiedzialnego za zasób. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@g-radzio pracujemy nad poprawką, tak, aby umożliwić wysłanie faktury dla takiego przypadku. Dam znać, gdy zostanie wdrożona. Aktualnie dla tego zamówienia pozostaje wysłanie faktury inaczej, np. przez Centrum wiadomości.

**Comment by AureliuszBrussy** [comment]
@g-radzio wdrożyliśmy poprawkę.

**Comment by g-radzio** [comment]
Potwierdzam, działa prawidłowo
