### ISSUE TITLE
Pytanie o Czechy Packeta

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#6638]
Dzień Dobry. W jaki sposób będzie można się zintegrować się z nowymi metodami przesyłki tzn.

    Allegro Wysyłka z Polski do Czech – Odbiór w Punkcie Packeta
    Allegro Wysyłka z Polski do Czech – Automaty Paczkowe Packeta.

Będzie to wymagać integracji z Pocztą Polską, czy wystarczy integracja z samym Allegro?

**Comment by Lukasz-Zurek** [comment]
Skorzystaj proszę z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&subjectId=2d542135-a6d7-474c-a4a1-f96451c8bbc5), gdzie powinieneś uzyskać szczegółowe informacje na temat nowych metod wysyłki z Polski do Czech.
