### ISSUE TITLE
Odpowiedź z API czasem zwraca HTML z reCAPTCHA

### ISSUE THREAD

**Issue by rzepetor** [allegro/allegro-api#6639]
Odpowiedź z API czasem zwraca HTML z reCAPTCHA

```<html><head><title>allegro.pl</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script data-cfasync="false">var dd={'cid':'AHrlqAAAAAMAMN_gFtlUWlcAkjsTfg==','hsh':'77DC0FFBAA0B77570F6B414F8E5BDB','t':'bv','s':29560,'e':'457ecb15759048d1e7a02519013d1e5ed301f3aa16e436a5905edcc7e1f8f6e3','host':'geo.captcha-delivery.com'}</script><script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script></body></html>
```

Czy jest to normalne zachowanie? Serwer nie powinien zwrócić błędu w formacie JSON lub no content z odpowiednim statusem HTTP?

**Comment by MartaNowaczyk** [comment]
Nie opisujesz dokładnie w którym momencie dostajesz reCAPTCHĘ. Sprawdź proszę, czy na pewno przekazujesz prawidłowe adresy:
- w CODE_URL (https://allegro.pl/auth/oauth/device) i TOKEN_URL (https://allegro.pl/auth/oauth/token),
- do wywołania zasobów: https://api.allegro.pl.allegrosandbox.pl/ (na środowisku testowym) oraz https://api.allegro.pl/ (na środowisku produkcyjnym). 
Zwróć też uwagę, czy aplikacja, którą zarejestrowałeś jest typu DEVICE, a nie WEB. Jeśli nadal będziesz otrzymywać błędy, prześlij nam swój cały kod za pośrednictwem [formularza](https://allegro.pl/pomoc/kontakt?kategoria=61571da6-f6de-4b8f-9ab9-699c8c797cfc&subjectId=35c2c795-4f94-49e2-8057-bbf00efe4433) - z dopiskiem, że dane dotyczą zgłoszenia [#6639](https://github.com/allegro/allegro-api/issues/5417) na GitHub.
