### ISSUE TITLE
sale/product-offers

### ISSUE THREAD

**Issue by czlowiekpolar** [allegro/allegro-api#6640]
Przenoszę obsługę tworzenia ofert ze starego zasobu na sale/product-offers. W jaki sposób obsłużyć wystawianie ofert w kategoriach nieproduktyzowanych (np. Zdrowie/Pozostałe)? 
- Czy w takiej sytuacji powinienem przesyłać pole productSet czy mogę wysłać tam pustą tablicę/null?
- Dlaczego w przypadku oferty produktyzowanej trzeba dodatkowo przesyłać pole category skoro produkt jest przypisany do kategorii?
- Czy istnieje jakiś artykuł który opisuje proces tworzenia ofert nieproduktyzowanych?

**Comment by MartaNowaczyk** [comment]
1. Musisz zawsze patrzeć w danej kategorii na parametry `"describesProduct": true` i te zawsze zawierać w `productSet.product`. Jeśli nie utworzyliśmy nowej propozycji produktu i nie powiązaliśmy oferty z żadnym produktem z naszej bazy otrzymasz wtedy w product.publication.status "NOT_LISTED".
2. W przypadku, gdy chcesz wystawić [ofertę powiązaną z produktem, który istnieje w naszym Katalogu](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem-za-pomoca-zasobu-sale-product-offers), to nie trzeba podawać kategorii.
3. Nie ma konkretnego artykułu z takim przypadkiem.
