### ISSUE TITLE
Naliczenie opłaty od nieaktywnej oferty

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#6641]
Witam,

W pomocy https://allegro.pl/pomoc/dla-sprzedajacych/oplaty-i-cenniki/oplata-za-utrzymanie-oferty-68KkXxbb2hY jest napisane: _"Opłatę naliczymy dokładnie po 365 dniach od daty utworzenia oferty"_

1. Jeśli utworzę szkic oferty dzisiaj, natomiast pierwsza publikacja będzie dopiero za 10 dni, opłata zostanie naliczona 365 dni od daty utworzenia szkicu czy pierwszej publikacji?
2. Czy data utworzenia szkicu jest niezmienna pod kluczem createdAt https://developer.allegro.pl/documentation/#operation/getOfferUsingGET ? 
3. Czy data pierwszej publikacji znajduje się pod kluczem public.startingAt w getOfferUsingGet?
4. Czy api umożliwia pobranie ostatniej daty wznowienia oferty?

**Comment by MartaNowaczyk** [comment]
Witam,
1. Od daty publikacji.
2. Tak
3. Tak, w `publication. startingAt`
4. Nie
Ogólnie opłata jest naliczana nie tylko od czasu publikacji oferty, ale również od czasu zakupu, dlatego musisz we własnym zakresie zapisywać też datę ostatniej sprzedaży w danej ofercie i względem niej obliczać 365 dni do naliczania opłaty utrzymaniowej.

**Comment by MartaNowaczyk** [comment]
- Data publication.startingAt to data, która wskazujesz, aby zaplanować wystawianie oferty i jest niezmienna,
- Tak możliwe, jeśli oferta nie jest zaplanowana do wystawienia,
- Nie ma takiego konkretnego pola, które zwróci Ci taką informację. Taką informację powinieneś przechowywać po swojej stronie lub pobierać odpowiednie eventy. 

Za pomocą [GET /pricing/offer-quotes](https://developer.allegro.pl/tutorials/jak-sprawdzic-oplaty-nn9DOL5PASX#data-naliczenia-kolejnej-oplaty) można sprawdzić opłaty nadchodzące w najbliższym cyklu 10-dniowym - w tym również informację o opłacie utrzymaniowej.
