### ISSUE TITLE
Nie możemy wyświetlić strony Numer błędu: a0b4a29273ee0078

### ISSUE THREAD

**Issue by killian13220** [allegro/allegro-api#6642]
hello i am trying to get an allegro token but i get this error: Please help me.

I tried several times
<img width="1363" alt="Capture d’écran 2023-01-26 à 17 30 57" src="https://user-images.githubusercontent.com/88785688/214892890-5b49e7a8-2d20-48c2-9466-b87194a4f9ef.png">

**Comment by MartaNowaczyk** [comment]
Hello, your redirect_uri is invalid. Make sure that the address you provided in redirect_uri is the same as the one you provided, when you registered the application. You can check and edit redirection addresses on page https://apps.developer.allegro.pl/.

**Comment by killian13220** [comment]
thank you 1000x, my problem is solved

But I have a new problem, when I try to import a user's announcements, I
have this error: Something went wrong: 403 Unexpected error:
VerificationRequired: Access denied. Access available only for verified
applications. for url
https://api.allegro.pl/offers/listing?include=all&fallback=false&seller.login=bmwparts-dowmont&offset=0&limit=60&sort=-price
and method GET


Can you help me? thank you

Le ven. 27 janv. 2023 à 09:09, MartaNowaczyk ***@***.***> a
écrit :

**Comment by MartaNowaczyk** [comment]
[GET /offers/listing](https://developer.allegro.pl/en/documentation/#operation/getListing) is available only for verified applications. You can read more https://github.com/allegro/allegro-api/issues/4213. Contact us via the [form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), or if you are in the [Partnership Program](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm) for Sellers via your account manager to verify the application.

**Comment by killian13220** [comment]
if I understand correctly I can not use the ads of sellers that I do not
know is that it? Le ven. 27 janv. 2023 à 11:36, MartaNowaczyk <

**Comment by MartaNowaczyk** [comment]
You cannot access other sellers' offers. As I wrote your application will pass verification. I don't quite understand if that's what you mean. If not, please provide more details.
