### ISSUE TITLE
Odmowa utworzenia oferty POST /sale/product-offers, środowisko sandbox.

### ISSUE THREAD

**Issue by zales2** [allegro/allegro-api#6644]
Gdy uderzam na wspomniany enpoint dostaje w response: Access denied. You are not authorized to perform operations on the indicated offer. EAN produktu 5702016369908. Jakie działania muszę podjąć by móc testować wystawianie ofert z tego endpointu? Nie działa to również przy innych wartościach EAN.

**Comment by MartaNowaczyk** [comment]
Być może konto, którego używasz to konto zwykłe, sprawdź to, bo powinno być firmowe.
