### ISSUE TITLE
Błąd podczas sprawdzania statusu utworzenia przesyłki

### ISSUE THREAD

**Issue by lukasz-lopata** [allegro/allegro-api#6645]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem testowym / with the test environment

:beetle: **Opis / Description**

Podczas sprawdzania statusu przesyłki w endpoincie `parcel-management/parcel-create-commands/{id}` odpowiedź nie zwraca wartości `parcelId`

`{trace-id=f22b351a04946f3a}
{"id":"33f06f9d-4ec4-4b0b-bcff-ecf298a540d6","parcelId":null,"status":"IN_PROGRESS","errors":[]}`

Zauważyliśmy, że dzieje się tak dla przesyłek do punktów odbioru
Co może być tego przyczyną?

**Comment by Lukasz-Zurek** [comment]
@lukasz-lopata Problem przekazałem dalej do weryfikacji, jednak wszystko wskazuje na to, że podobnie jak [tutaj](https://github.com/allegro/allegro-api/issues/6244#issuecomment-1406288991) - doszło do tymczasowych problemów u operatora i będziesz musiał spróbować ponownie. Wrócę do Ciebie jeszcze jednak z informacją.

**Comment by MartaNowaczyk** [comment]
@lukasz-lopata operator wprowadził poprawki po swojej stronie. Przepraszamy za niedogodności.
