### ISSUE TITLE
About Public Access to offers data

### ISSUE THREAD

**Issue by userisamir** [allegro/allegro-api#6646]
Hi,
Since I got a bit confused while reading the documentation, I have questions for clearify:
Is there a way to get 'Offers' or a 'Specific Offer' data (like: name, price, image, desc., etc...) through RestAPI ?
It should be mentioned that I am not an Allegro seller and I just want to get public information about Allegro products through api.

Thank you

**Comment by MartaNowaczyk** [comment]
We have a resource for public data [GET /offers/listing](https://developer.allegro.pl/en/documentation/#operation/getListing) but is available only for verified applications. You can read more https://github.com/allegro/allegro-api/issues/4213. Contact us via the [form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), or if you are in the [Partnership Program](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm) for Sellers via your account manager to verify the application.
