### ISSUE TITLE
Limity DCR

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#6647]
https://developer.allegro.pl/faq#jakie-sa-ograniczenia-liczby-sesji-i-zapytan-w-allegro-api-

Hej!
Mam SaaSa, z którego już teraz korzysta ok 500 klientów. Chcę dodać do niego obsługę Allegro.
Czy to znaczy, że na każdy z klientów może wykonać maksymalnie 18 zapytań na minutę?
Jesli dostanę od was Sofware Statement ID, to według tego poradnika limit będzie dotyczył Sofware Statement ID, a nie konkretnego klienta.

Czy jeśli skontaktuję się z wami, to możecie zwiększyć ten limit znacznie zanim rozpocznę wdrożenie, czy jedyna opcja to wymaganie od klientów generowania własnej pary client + secret? Aplikacja będzie m.in aktualizować stany i ceny, m.in klientom z branży moto, którzy maja po 200k+ aukcji i często zmieniają ceny.

**Comment by MartaNowaczyk** [comment]
Tak, limit jest nakładany na Sofware Statement ID - traktowany jest tak samo jak Client ID. Informacje o możliwości korzystania z DCR otrzymasz przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by jakubmaguza** [comment]
Dziękuję za odpowiedź, natomiast pytałem czy jest możliwość takiego zwiększenia limitów od razu, bo jeśli nie, to nawet nie będę występował o DCR.

**Comment by MartaNowaczyk** [comment]
Nie ma takiej możliwości by na wstępie zwiększyć limit.

**Comment by jakubmaguza** [comment]
W takim razie jaka jest procedura? Muszę udostępniać funkcję po kolei kilku klientom i co jakiś czasu (jaki?) prosić was o zwiększenie limitu, bo chcę dodać nowych klientów?

**Comment by MartaNowaczyk** [comment]
Limity obowiązują wszystkich użytkowników naszego API. Do każdego przypadku podchodzimy indywidualnie. O zwiększenie limitu można wnioskować jeśli pojawi się problem z ich przekroczeniem, wtedy dokładnie analizujemy sytuację pod względem optymalnego wykorzystywania naszych zasobów, np. czy nie przesyłasz zbędnych requestów, czy nie są one błędne itp.

Na początku staramy się przekazać odpowiednie rozwiązania oraz wskazujemy błędy, po to, abyś mógł zoptymalizować swoje działania. W większości przypadków po wyeliminowaniu błędnych requestów zwiększenie limitu nie jest potrzebne. Jeżeli stwierdzimy, że korzystasz z API w prawidłowy sposób, a mimo to limity nie pozwalają na optymalną pracę, istnieje możliwość ich podniesienia.
