### ISSUE TITLE
WZA error.common.processing

### ISSUE THREAD

**Issue by bartekc7** [allegro/allegro-api#6648]
Dzień dobry,
Co może powodować taki problem z API Wysyłam z Allegro? Czy potrzebny cały request? 

 "serviceId": "a3b4db98-4a70-4542-84ee-c642604d9d8a"

{
  "id": "06c86ca9-6e86-4bca-a894-5ef7062b53ea",
  "parcelId": null,
  "status": "ERROR",
  "errors": [
    {
      "code": "ERROR",
      "message": "Processing error",
      "details": null,
      "path": null,
      "userMessage": "error.common.processing"
    }
  ]
}

**Comment by bartekc7** [comment]
Jeszcze tylko dodam że występuje to w przypadku jednostki - PALLET

**Comment by AureliuszBrussy** [comment]
W DHL, przy odbiorze z punktu, możliwe jest nadanie wyłącznie paczek i kopert, stąd błąd. Poprawimy ten komunikat błędu na czytelny.

**Comment by bartekc7** [comment]
Dziękuje za odpowiedź ale czy na pewno o to chodzi? w komunikacie pointId jest null
Czy nie powinienem przekazywać wcale w takim przypadku?

**Comment by bartekc7** [comment]
Jeszcze tylko dodam że w innych testach paczkowych jak pointId = null to przechodzi bez problemu

**Comment by AureliuszBrussy** [comment]
@bartekc7 słuszna uwaga. Potwierdzam to jeszcze z zespołem odpowiedzialnym za usługę. Wrócę do Ciebie z informacją.

**Comment by bartekc7** [comment]
Dzień dobry, 
Kiedy mniej więcej można się spodziewać jakiejś informacji?

**Comment by AureliuszBrussy** [comment]
@bartekc7 niebawem, czekam jeszcze na odpowiedź. Wrócę z informacją najszybciej jak to możliwe.

**Comment by AureliuszBrussy** [comment]
@bartekc7 wybrana metoda dostawy w ogóle nie obsługuje palet. Poprawimy komunikat błędu.

**Comment by bartekc7** [comment]
Dziękuje za informacje. Zgłoszenie można zamknąć.
Taka mała sugestia, może rozwojowo powinniście pomyśleć nad informacją o obsługiwanych jednostkach w zasobie zwracającym listę dostępnych metod dostawy?
/parcel-management/delivery-services 

https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices

**Comment by AureliuszBrussy** [comment]
@bartekc7 dziękuję za sugestię. Możesz także dopisać ją do zakładki [Discussions](https://github.com/allegro/allegro-api/discussions) - łatwiej nam wtedy priorytetyzować potrzeby (inni użytkownicy mogą upvote'ować pomysły).
