### ISSUE TITLE
ConstraintViolationException.MaxInactiveOffers ale brak draftów na koncie

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#6649]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Przy próbie utworzenia draftu dostaję poniższy błąd:
{"errors":[{"code":"VALIDATION_ERROR","message":"You cannot create new drafts - your account has exceeded the maximum number 20000 of drafts.","details":"ConstraintViolationException.MaxInactiveOffers","path":"null","userMessage":"Nie możesz utworzyć nowych szkiców - Twoje konto przekroczyło maksymalną liczbę 20000 szkiców."}]}
Na tym koncie nie ma żadnych draftów (sprawdzone przez API oraz stronę)

trace-id: a4c6ae4e04832d48

**Comment by MartaNowaczyk** [comment]
Weryfikujemy problem z draftami. Dam znać, gdy uda nam się to poprawić.

**Comment by MartaNowaczyk** [comment]
Poprawiliśmy liczbę draftów. Problem występował po naszej stronie. Przepraszamy za niedogodności z tym związane.
