### ISSUE TITLE
[REST] - Parametry kategorii 

### ISSUE THREAD

**Issue by Rnapzsih** [allegro/allegro-api#665]
To już nawet nie jest śmieszne.... 
`{"id":"16101","valuesIds":[],"values":["Spoty"],"rangeValue":null},` 
Najlepsze jest to:
`,"validation":{"errors":[],"validatedAt":"2018-09-18T13:46:14.511Z"},"createdAt":"2018-09-05T07:08:23Z","updatedAt":"2018-09-19T10:16:10.803Z"} `
A teraz próba edycji aukcji.... 
`{"errors":[{"code":"VALIDATION_ERROR","message":"Attribute value does not exists Rodzaj lampy(16101).","details":"","path":"","userMessage":"Attribute value does not exists Rodzaj lampy(16101)."}]}` **Przecież ja to sobie sam nie ustawiłem...**, znaczy ustawiłem rodzaj lampy na Spoty ale wcześniej, jak jeszcze taki rodzaj był....  

Co się dzieje w kategorii Lampy?? Czy ktoś pomyślał, chociaż przez chwilę co robi zmieniając drzewo kategorii? Czy jak robicie zmiany w parametrach, to czy nie warto wyczyścić wartości parametrów, których już nie ma i nie będzie? Po co przesyłacie wartości których nie ma? Wiem, że mogę sobie wszystko zmienić ręcznie, poprzez stronę, (oczywiście oprócz kategorii, 35 aukcji z błędną kategorią, chociaż w chwili wystawiania wszystko było prawidłowo).... ale to po co te całe API?

**Comment by PawelTaberski** [comment]
Zachęcam do śledzenia strony w której informujemy kiedy u jakie parametry ulegną zmianie. Wszelkie informacje na ten temat znajdziesz [tutaj](https://allegro.pl/dla-sprzedajacych/kategoria/zmiany-w-parametrach). Starych parametrów nie usuwamy m.in. ze względu na to, aby można było sprawdzić w ofertach zakończonych i draftach jakie parametry były ustawione.

**Comment by Rnapzsih** [comment]
@PawelTaberski **"Starych parametrów nie usuwamy m.in. ze względu na to, aby można było sprawdzić w ofertach zakończonych i draftach jakie parametry były ustawione."** - Ale po co mi to w API?? Po to aby wznawiać każdą akcję ręcznie, czy może aby wykonywać kolejne zapytanie? Czyli do wznowienia aukcji mam pobierać dane o aukcji, pobierać dane o parametrach, wysyłać zaktualizowane dane (zaznaczę, że jest to tylko ilość produktów), a następnie publikować aukcję? Cztery zapytania dla jednej aukcji? A tak w ogóle, jeżeli się nie mylę to parametru, którego nie ma, nie widać w panelu na allegro.pl.

**Comment by PawelTaberski** [comment]
Może źle się wyraziłem parametry czyścimy, ale tylko w aktywnych ofertach, bo tylko takie można edytować.

**Comment by Rnapzsih** [comment]
I co ja się czepiam....
