### ISSUE TITLE
Problem z pobieraniem polityki prywatność, informacji o gwarancjach itp.

### ISSUE THREAD

**Issue by Oblako1223** [allegro/allegro-api#6650]
Witam, od 16 stycznia mam problem aby pobierać po przez API danych z 3 endpointów:

after-sales-service-conditions/warranties/%s',
after-sales-service-conditions/implied-warranties/%s',
after-sales-service-conditions/return-policies/%s

Zwracany jest mi błąd dot. uprawnień: {"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"Brak dostępu do danego zasobu."}]}

Nie za bardzo rozumiem, ponieważ konta w allegro developers mają nadane wszystkie możliwe uprawnienia, z czego może taki problem wynikać?

**Comment by AureliuszBrussy** [comment]
Wygenerowany przez Ciebie access_token prawdopodobnie nie posiada odpowiedniego scope'a: **allegro:api:sale:settings:read**. O scope'ach więcej możesz przeczytać w [naszym poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#scope-w-api-allegro). Jeżeli chcesz, aby dokładniej sprawdził ten przypadek - potrzebuję trace-id wywołania. Znajduje się ono w nagłówku naszego response'a.

**Comment by Oblako1223** [comment]
Tak jak wspomniałem posiadam wszystkie możliwe uprawnienia odznaczone w ustawieniach dostępu. 
![image](https://user-images.githubusercontent.com/43018609/215753318-2dc39ceb-617c-4afe-973c-bed758b1ded2.png)

**Comment by AureliuszBrussy** [comment]
Podczas generowania access_tokena możesz zawęzić te uprawnienia - czy masz pewność, że tego nie robisz? 

Tak jak wspomniałem, najlepiej, jeżeli wyślesz mi trace-id przykładowego wywołania kończącego się tym errorem. Będę mógł sprawdzić ten przypadek.

**Comment by Oblako1223** [comment]
Niestety ale nie widzę takiego nagłówku:
![image](https://user-images.githubusercontent.com/43018609/215754222-0616714e-9532-47f6-bf66-4ae0b33590b1.png)

Dodam, że requesty lecą po przez GuzzleHttp 
![image](https://user-images.githubusercontent.com/43018609/215755488-ece84fe9-e039-4f3c-9761-6fa141957566.png)

**Comment by Oblako1223** [comment]
Pogrzebałem trochę w Guzzle i znalazłem : 

  -headers: array:4 [
    "trace-id" => array:1 [
      0 => "bca01028996a2f28"
    ]

**Comment by AureliuszBrussy** [comment]
Zmień wartość, którą przekazujesz w swoich requestach w nagłówku "Accept" na "application/vnd.allegro.public.v1+json".

**Comment by Oblako1223** [comment]
Problem, został rozwiązany. Zamykam :)
