### ISSUE TITLE
POST /sale/product-offers - zdjęcia z zewnętrznymi URLami w opisie

### ISSUE THREAD

**Issue by enp-aszuszkiewicz** [allegro/allegro-api#6651]
Cześć, mam proste pytanie, na które nie znalazłem odpowiedzi w dokumentacji.

Załóżmy, że wystawiam ofertę za pomocą `POST /sale/product-offers` - czy mogę użyć wszędzie zewnętrznych URLi do zdjęć? Nawet w sekcji `description`?

**Comment by AureliuszBrussy** [comment]
Możesz wykorzystać zdjęcia z zewnętrznych URL, z zastrzeżeniem, że w **description** możesz wykorzystać tylko zdjęcia, które przesyłasz równocześnie w tablicy **images**.
