### ISSUE TITLE
API - pola aukcji

### ISSUE THREAD

**Issue by ircoo2022** [allegro/allegro-api#6652]
Witam
https://allegro.pl/oferta/barwa-barwy-botaniki-odzywczy-szampon-w-kostce-p1-13192597996

W tej aukcji mamy tytuł ( pole name w api allwegro ) Barwa Barwy Botaniki odżywczy szampon w kostce P1
$params['name']

a w innym miejscu Barwa Barwy Botaniki odżywczy szampon w kostce o włosów normalnych i suchych 100g

jak wysłać przez api allegro zmienną aby zmodyfikować te drugie pole ?

(CURLOPT_URL => 'https://api.allegro.pl/sale/product-offers',)

**Comment by AureliuszBrussy** [comment]
Nazwa "Barwa Barwy Botaniki odżywczy szampon w kostce o włosów normalnych i suchych 100g" jest ściągnięta prosto z powiązanego z ofertą produktu - tak prezentujemy aktualnie oferty. Nazwa samej oferty znajduje się nad ceną. 

Zmiana nazwy produktu możliwa jest poprzez wysłanie sugestii zmiany. Możesz to zrobić za pomocą API - opisujemy to w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-zglosic-blad-w-produkcie). 

Zmiany sugerować możesz także z poziomu [formularza wystawiania](https://allegro.pl/offer/). Wystarczy, że odszukasz produktu i skorzystasz z opcji "Zgłoś błąd w produkcie".
