### ISSUE TITLE
Help Needed: ChannelAdvisor X Allegro listing update errors (Bigriver Company)

### ISSUE THREAD

**Issue by bigriversam** [allegro/allegro-api#6653]
Problem on creating listing on Allegro through ChannelAdivosr in PL for Big River Company: 

I am the head of Product for Bigriver, and my operations team have been experiencing this issue for more than 6 months now. This has been causing us huge pain and impacting our business sales significantly. We have been working with your CS team but no one was able to help us, hence a CA agent directed us to this platform recently. We are trying to add more listings to Allegro through ChannelAdvisor, which is our go to multichannel management tool for all platforms now. The two pilot SKU we are trying to list (901547 & 901871), both are Logitech physical products. 
 
Errors on ChannelAdvisor when calling Allegro that we continue to see and not able to address that needs help: 
1.	"You cannot publish offer without a related product in this category. Select from the catalog or create a new product and associate it with your offer. (id ProductFailedDataValidation, code VALIDATION_ERROR)"
--> [BR]: is there a document where I can see what are “all basic parameters”, or what each error code stands for as well as the correspondent solutions? We filled in all the fields we find relevant for this product. 

2.	"Missing required parameters: 237206"
--> Parameter 237206 seems to be the "Model" parameter, which is mandatory. However, we've already mapped it. 

3.	"Invalid range (212570) need two values"
--> Parameter 212570 is the "Bandwidth" parameter. Seems that I need to complete the "Bandwidth from" and "Bandwidth to" values. However, 1) "Bandwidth" does not apply to this product, and 2) The only 'bandwidth' fields I see are the below. In exactly which section should 'Bandwidth from' and 'Bandwidth to' exist?
Common>Additional Attributes>Bandwith(Hz)
Electronics>Additional Attributes>Bandwidth Frequencies
Electronics>Video and Household Appliances>Electronics>Bandwidth (Mhz)
 
Additional questions/issues:
1. Is there a way that we can see all the errors on the return API call? We only see 1-2 errors every time and even after we address them (which we have been blocked for more than 6 months), we have been seeing new errors keeps coming up without clear guidance how to address them. 

Attaching error screenshots below:

![Allegro error_901547](https://user-images.githubusercontent.com/123984977/215598204-47691aa7-0b2c-4cf9-9154-549695bf4fbb.png)
![Allegro error_901871](https://user-images.githubusercontent.com/123984977/215598206-93c2e2af-394e-4ef6-9f6a-0670ae93854c.png)
![Allegro error_Bandwidth](https://user-images.githubusercontent.com/123984977/215598207-cbdf78ae-7e7c-49c3-9a2c-3f98c14d3522.png)

**Comment by bigriversam** [comment]
Needs help on this. Please provide ETA, thanks

**Comment by AureliuszBrussy** [comment]
Please contact Channel Advisor support directly. This is the only way you will receive support.

**Comment by bigriversam** [comment]
I was directed by ChannelAdvisor support to Allegro, and then by Allegro support to here.

**Comment by bigriversam** [comment]
Now are you redirecting me back to stage one? Are you saying this is no the place for me to ask Allegro related question, as Allegro CS mentioned?

**Comment by AureliuszBrussy** [comment]
We do not provide support for app users on GitHub.  Report any problems to the support of the software you are using.
