### ISSUE TITLE
Tracking of the status of the parcel 

### ISSUE THREAD

**Issue by LAmcpp** [allegro/allegro-api#6654]
Hi, guys!
How (using API) can I get all active tracking numbers of all carriers for an user?
And is it possible for the app to subscribe to delivery-related changes, or any other way to get those changes (using API)?

**Comment by MartaNowaczyk** [comment]
You can use [GET /order/carriers/{carrierId}/tracking?waybill={waybill}](https://developer.allegro.pl/documentation/#operation/getAllegroParcelTrackingUsingGET) to retrieve **indicated** parcels statuses history (not all active at once). More information in our [tutorial](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-retrieve-parcels-statuses-history).

**Comment by LAmcpp** [comment]
@MartaNowaczyk thank's for your response!
I have seen that endpoint, but it is not exactly what I need. And I have found answer in your tutorial.
I try to ask differently: how can I get a list of all existing 'waybill number' (parcel tracking number) with the corresponding 'carrier identifier' for the user?

**Comment by MartaNowaczyk** [comment]
We don't have a resource that returns such a list.

**Comment by LAmcpp** [comment]
@MartaNowaczyk is there a way to get this result somehow? Maybe some sequence of requests?
How can I get the data for this request: [GET /order/carriers/{carrierId}/tracking?waybill={waybill}](https://developer.allegro.pl/documentation/#operation/getAllegroParcelTrackingUsingGET)
???

**Comment by LAmcpp** [comment]
I have read your documentation very carefully, but it is not clear to me. That's why I'm writing these questions.
I guess, 'commandId' - must be the same 'commandId' that we use when creating a parcel:
[PUT /parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/createNewParcel)
And if any parcel was created not using the API, but on your website, then I won't be able to get data about it?
In addition, if I understand correctly, I can only create parcels for my own orders. But I need to get all the user's parcels,
regardless of how and by whom they were created.
There is any way to receive that data?

**Comment by LAmcpp** [comment]
@MartaNowaczyk 
And one more question: what should the following query return - [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET)
This will list only the user's sales or all orders (all purchases + all sales).
And can I get data about all active purchases of the user? And accordingly about all the expected parcels?

**Comment by MartaNowaczyk** [comment]
> I guess, 'commandId' - must be the same 'commandId' that we use when creating a parcel:
> [PUT /parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/createNewParcel)

Yes

> And if any parcel was created not using the API, but on your website, then won't I be able to get data about it?

Yes

> In addition, if I understand correctly, I can only create parcels for my own orders. But I need to get all the user's parcels,
> regardless of how and by whom they were created.
> There is any way to receive that data?

You must be authorized as a specific seller (to a specific allegro account), then you will download the data, but only those that were created by the API.
