### ISSUE TITLE
Pominięcie jednego z parametrów produktowych przy wystawianiu aukcji

### ISSUE THREAD

**Issue by robboh** [allegro/allegro-api#6655]
Witam,
czy jest możliwe pominięcie jednego z parametrów produktowych przy wystawianiu aukcji wykorzystującej produkt istniejący w zasobach Allegro?
Jeżeli tak, to czy wystarczy podać wartość null dla danego id parametru czy jest jakieś inne rozwiązanie

**Comment by MartaNowaczyk** [comment]
Gdy wykorzystujesz istniejący produkt (podajesz product.id) nie musisz podawać parametrów, możesz je po prostu pominąć - będą dodane z produktu. Tak samo powinno działać gdy podasz 3 z 4 parametrów wymaganych (jeden pominiesz).

**Comment by robboh** [comment]
Rozumiem - nie muszę podawać parametrów produktowych, które są już podpięte pod produkt z zasobów Allegro. Podczas wystawiania aukcji system podepnie je pod wystawwianą aukcję. Ja jednak chcę pominąć jeden z parametrów, który jest podpięty pod produkt. Jak to zrobić?

**Comment by MartaNowaczyk** [comment]
Przy wystawianiu z produktem go nie pominiesz, bo i tak dodamy swoje. Jedyna opcja może być taka, że edytujesz ofertę PATCHEM i bez podania product.id podasz wyłącznie parametry, które mają być widoczne. No chyba, że jest obowiązkowy, to go nie pominiesz.
