### ISSUE TITLE
Aukcja, dla której wystąpił event nie istnieje

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#6657]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,

badam dzisiaj działanie dziennika zdarzeń ofert i zauważyłem bardzo niepokojące zachowanie Allegro.
Otrzymałem event `OFFER_STOCK_CHANGED` o ID: MTY3NTIzNjYwMzgzMDU4Nw dotyczący oferty: 13208181672

Problem polega na tym, że ta oferta nie istnieje. Nie mogę jej odnaleźć ani w swojej bazie, ani w API Allegro, ani na portalu w żadnej z dostępnych kategorii (aktywne, aktywujące się, szkice, zakończone). 

Event zwraca external_id, które nasz system nadaje aukcjom, więc z jednej strony to wygląda na aukcję utworzoną przez nasz system. Jednocześnie nie mamy żadnych śladów co do jej istnienia. 

Czy są Państwo w stanie nakreślić mi historię tej oferty? 
Z góry dziękuję i pozdrawiam.

**Comment by AureliuszBrussy** [comment]
Dziękuję za zgłoszenie - sprawdzamy to. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Tutaj błędnie zwróciliśmy event dla draftu, który w rzeczywistości nie powstał (Twój request zakończył się errorem 400). Pracujemy już nad odpowiednią poprawką. Wrócę z informacją po wdrożeniu.

**Comment by hahyes** [comment]
@AureliuszBrussy Czy mogę liczyć na jakąś aktualizację? Problem nadal występuje.

**Comment by AureliuszBrussy** [comment]
@hahyes pracujemy jeszcze nad poprawką. Gdy tylko będę miał jakiś update - wrócę z informacją.

**Comment by pandresp** [comment]
U mnie podobny problem.
Od jakiegoś czasu mam problem z eventami ofert zwracanych przez allegro API.
Po odpytaniu endpointu "/sale/offer-events?limit=100" dostaję (pomiędzy innymi) eventy z id ofert których nie ma w allegro.
3 przykłady poniżej - jest tego znacznie więcej.
Dostaję np. event z id oferty 13335968053 po czym odpytuje allegro o szczegóły tej oferty i dostaję 404.

Czy udało się coś z powyższym zrobić?

------------------------------------------------------------------
{
	id: 'MTY3NzM4MjAzOTU4NDEzNA',
	type: 'OFFER_STOCK_CHANGED',
	occurredAt: '2023-02-26T03:27:08.566Z',
	offer => {
		id: '13335968053',
		publication': NULL,
		external {
			id => '534937'
		},
	},
}

------------------------------------------------------------------
{
	id: 'MTY3NzM4MjA0MDIzMTg3NA',
    type: 'OFFER_STOCK_CHANGED',
	occurredAt: '2023-02-26T03:27:09.845Z',
	offer: {
		id: '13335968162',
		publication: NULL,
		external: {
			id: '534669',
		},
	},
}

------------------------------------------------------------------
{
	id: 'MTY3NzM4MjA0MTg5NzczMw',
	type: 'OFFER_STOCK_CHANGED',
	occurredAt: '2023-02-26T03:27:11.836Z',
	offer: {
		id: '13335968375',
		publication: NULL,
		external: 
			id: '535633',
		},
	},
}

**Comment by AureliuszBrussy** [comment]
@pandresp problem jest nieco bardziej złożony. Nie wdrożyliśmy jeszcze poprawki, wciąż nad nią pracujemy. Będę informował, gdy tylko coś się zmieni.

**Comment by AureliuszBrussy** [comment]
@hahyes @pandresp - czy aktualne zachowanie dziennika ma duży wpływ na działanie logiki w Waszych aplikacjach? Generuje jakieś problemu, których nie jesteście w stanie obsłużyć?

**Comment by pandresp** [comment]
@AureliuszBrussy w moim przypadku dostaje zdarzenia odnośnie ofert które nie istnieją (API zawraca mi 404 sekundę po otrzymaniu z API eventa że oferta się zmieniła).
Mogę to zacząć ignorować ale co w sytuacjach które rzeczywiście będą błędne?
A moja aplikacja będzie to ignorowała i nie wyłapie realnych problemów.

Jeśli nie da się tego jakoś szybko naprawić, to może da się jakoś takie eventy odróżnić od innych?
np. jak jest type = 'OFFER_STOCK_CHANGED' i publication = NULL to wtedy mam to ignorować?

Nie chciałbym wrzucić ignora na wszystkie 404.

Proszę puki co na jakieś obejście problemu.
Bo generuje mi to jakieś 20k błędnych eventów w ciągu miesiąca.
I zapycha mi to logi śmieciami (reagowanie na prawdziwe problemy jest bardzo utrudnione)

**Comment by AureliuszBrussy** [comment]
@pandresp dziękuję za feedback. Aktualnie nie ma sposobu na odróżnienie takich eventów, natomiast cały czas próbujemy znaleźć odpowiednie rozwiązanie.
