### ISSUE TITLE
Adresy miniaturek zwracane przez doGetItemsList dają błąd 404

### ISSUE THREAD

**Issue by juhacz** [allegro/allegro-api#666]
Od około 4 godzin w aukcjach zwracanych poprzez doGetItemsList adresy obrazków są błędne. 
Np. itemId 7589343956
Obrazki:

[0] => https://redir-img17.allegroimg.com/photos/400x300/75/89/34/39/7589343956
[1] => https://redir-img17.allegroimg.com/photos/400x300/75/89/34/39/7589343956_1
[2] => https://redir-img17.allegroimg.com/photos/400x300/75/89/34/39/7589343956_2

Każdy z nich to error 404.

**Comment by solokazama** [comment]
potwierdzam - wszystkie obrazki ktore sa zapisane w danych aukcji dostaja 404, typu:
https://redir-img15.allegroimg.com/photos/oryginal/75/89/71/39/7589713934

powoduje to brak mozliwosci wznawiania aukcji - wznawiajac aukcje, chcac uzyc tych samych zdjec (sa przekazywane jako urle) - aukcja sie nie wznowi, bo w/w urle nie dzialaja

**Comment by juhacz** [comment]
Już działa. Można zamknąć.
