### ISSUE TITLE
requiredDependsOnValueIds not working for product?

### ISSUE THREAD

**Issue by Quesstor** [allegro/allegro-api#6660]
I am trying to create an offer via the /sale/product-offers resource for the product id 257689.

The parameter 225693 EAN (GTIN) option says: `...
        "dependsOnParameterId": "11323",
        "requiredDependsOnValueIds": [
          "11323_1"
        ]...
`, so the GTIN should only be required if the parameter `11323` is set to `11323_1`, right?

In this case the article is used, so parameter `11323` is set to `11323_2`, which disables the requirement for the `offer`, but not the `product`.
The problem is that it is not possible to set the parameter `225693` for the `product` to disable the requirement, so i get the error `ProductValidationException productSet[0].product This category requires parameter EAN (GTIN)`.

**How can i create an offer for a used article, if there is no EAN (GTIN) for this article?**

I tried to create an article with the Allegro Website and it works without the EAN (GTIN) so i think it should be possible with the api, too.

Here is the full request body:
```json
{
  "productSet": [
    {
      "product": {
        "name": "125/25 R10 63CRF Bridgestone Runflat",
        "category": {
          "id": "257689"
        },
        "images": [
          "..."
        ],
        "parameters": [
          {
            "id": "344",
            "valuesIds": [
              "344_1"
            ]
          },
          {
            "id": "345",
            "valuesIds": [
              "345_815238"
            ]
          },
          {
            "id": "9300",
            "valuesIds": [
              "9300_35"
            ]
          },
          {
            "id": "127088",
            "valuesIds": [
              "127090_362185"
            ]
          },
          {
            "id": "237206",
            "values": [
              "Test"
            ]
          }
        ]
      }
    }
  ],
  "parameters": [
    {
      "id": "344",
      "valuesIds": [
        "344_1"
      ]
    },
    {
      "id": "345",
      "valuesIds": [
        "345_815238"
      ]
    },
    {
      "id": "9300",
      "valuesIds": [
        "9300_35"
      ]
    },
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ]
    },
    {
      "id": "15808",
      "valuesIds": [
        "15808_1"
      ]
    },
    {
      "id": "127088",
      "valuesIds": [
        "127090_362185"
      ]
    },
    {
      "id": "237206",
      "values": [
        "Test"
      ]
    }
  ],
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "12.00",
      "currency": "EUR"
    }
  },
  "stock": {
    "available": 1
  },
  "delivery": {
    "handlingTime": "P3D"
  },
  "publication": {
    "status": "INACTIVE"
  },
  "language": "en-US",
  "name": "125/25 R10 63CRF Bridgestone Runflat",
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>...</p>"
          }
        ]
      }
    ]
  },
  "external": {
    "id": "VENDO-1"
  },
  "messageToSellerSettings": {
    "mode": "OPTIONAL"
  }
}
```

here is the full response body:
```json

{
  "errors": [
    {
      "code": "ProductValidationException",
      "path": "productSet[0].product",
      "details": null,
      "message": "Empty GTIN: 225693",
      "userMessage": "This category requires parameter EAN (GTIN)"
    }
  ]
}
```

**Comment by AureliuszBrussy** [comment]
It seems that we should allow the creation of an offer in such a case.

I reported this problem to the team responsible for this resource - they are analyzing it. I'll be back with an update.

**Comment by Quesstor** [comment]
Any news on this?

**Comment by AureliuszBrussy** [comment]
Sorry, it is still not resolved. I will come back with the info when anything changes.

**Comment by Quesstor** [comment]
Any news by now?

**Comment by AureliuszBrussy** [comment]
@Quesstor sorry, but nothing new. I ask for some more patience.

**Comment by Quesstor** [comment]
bump

**Comment by AureliuszBrussy** [comment]
@Quesstor nothing new yet - I will write in the thread immediately, as soon as something changes.

**Comment by AureliuszBrussy** [comment]
We have implemented the fix, the problem should not occur.
