### ISSUE TITLE
Problem z statusem 403.

### ISSUE THREAD

**Issue by tenszaqu** [allegro/allegro-api#6661]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

Mam problem z otrzymywanym statusem 403. Mianowicie co ~20minut wykonuje się skrypt. (działa)

1. Pobiera dane oferty poprzez "sale/offers/"
2. Wysyłane są zdjęcia dla tej oferty poprzez "sale/images"
3. Aktualizowana jest oferta o nowe zdjęcia i opis poprzez "sale/product-offers/"

I ten proces działa nieprzerwanie od pół roku, refresh_token odświeża się raz dziennie.

I czasem dostaje w odpowiedzi status 403. Nie mogę nic zrobić nawet się autoryzować poprzez 'grant_type' => 'authorization_code'  (nawet jestem zalogowany i wymuszam logowanie poprzez 'prompt' => 'confirm') czy 'grant_type' => 'refresh_token'. Dostaje wiecznie status 403. Automatycznie skrypt sypie błędami. Po 2-3 godzinach nagle mogę odświeżyć token poprzez 'grant_type' => 'refresh_token' bez problemu? O co może chodzić? Z góry dziękuję za pomoc.

**Comment by AureliuszBrussy** [comment]
Wyślij proszę trace-id przykładowego wywołania, gdzie zwróciliśmy 403. Trace-id znajdziesz w nagłówku naszego response'a. Postaram się ustalić przyczynę.

**Comment by Szaqu** [comment]
Aktualnie skrypt działa. Jak otrzymam ponownie status 403 to podeśle :)

**Comment by Szaqu** [comment]
Otrzymałem coś takiego header + body,

`tring(906) "HTTP/2 403 
content-type: text/html
content-length: 589
x-frame-options: SAMEORIGIN
accept-ch: Sec-CH-UA,Sec-CH-UA-Mobile,Sec-CH-UA-Platform,Sec-CH-UA-Arch,Sec-CH-UA-Full-Version-List,Sec-CH-UA-Model,Sec-CH-Device-Memory
content-type: text/html; charset=utf-8
charset: utf-8
cache-control: max-age=0, private, no-cache, no-store, must-revalidate
pragma: no-cache
access-control-allow-credentials: true
access-control-expose-headers: x-dd-b, x-set-cookie
access-control-allow-origin: *
accept-ch: Sec-CH-UA,Sec-CH-UA-Mobile,Sec-CH-UA-Platform,Sec-CH-UA-Arch,Sec-CH-UA-Full-Version-List,Sec-CH-UA-Model,Sec-CH-Device-Memory
x-datadome-cid: AHrlqAAAAAMAN-0y24XTd9cALvKC_A==
set-cookie: datadome=63kZNTt_0wSTLx1nbTnAAkild18VfI4oy6LSzkWU6d6nhBhdx1jg_G1WyBeLkUGLP8_nR07zmMyDNa307-K2G4Ouy_feks_k5pU3Im7cd17XAaRjQz_kqMDA51PdHUZm; Max-Age=31536000; Domain=.allegro.pl; Path=/; Secure; SameSite=Lax

"
string(589) "<title>allegro.pl</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style><script data-cfasync="false">var dd={'rt':'c','cid':'AHrlqAAAAAMAN-0y24XTd9cALvKC_A==','hsh':'77DC0FFBAA0B77570F6B414F8E5BDB','t':'bv','r':'b','s':16045,'e':'d4aad3360717e2d07524554fa159ec86c272b15bc4730dcd0d3e21bd5a263d3f','host':'geo.captcha-delivery.com'}</script><script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script><script>if("string"==typeof navigator.userAgent&&navigator.userAgent.indexOf("Firefox")>-1){var isIframeLoaded=!1,maxTimeoutMs=5e3;function iframeOnload(e){isIframeLoaded=!0;var a=document.getElementById("noiframe");a&&a.parentNode.removeChild(a)}var initialTime=(new Date).getTime();setTimeout(function(){isIframeLoaded||(new Date).getTime()-initialTime>maxTimeoutMs&&(document.body.innerHTML='<div id="noiframe">Please enable JS and disable any ad blocker</div>'+document.body.innerHTML)},maxTimeoutMs)}else function iframeOnload(){}</script><iframe src="https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAN-0y24XTd9cALvKC_A%3D%3D&amp;hash=77DC0FFBAA0B77570F6B414F8E5BDB&amp;cid=null&amp;t=bv&amp;referer=https%3A%2F%2Fwww.gobli.pl%2Fprim_imports%2Fallegro_2%2Frefreshtoken.php&amp;s=16045&amp;e=d4aad3360717e2d07524554fa159ec86c272b15bc4730dcd0d3e21bd5a263d3f" style="height:100vh;" border="0" scrolling="yes" onload="iframeOnload()" width="100%" height="100%" frameborder="0"></iframe>`

**Comment by Szaqu** [comment]
https://ssl.allegro.pl/auth/oauth/token/

grant_type: refresh_token

**Comment by Szaqu** [comment]
https%3A%2F%2Fxxxxxxxxxxxx <- tutaj adres www zmieniłem na xxxx

**Comment by AureliuszBrussy** [comment]
Zmień URL swoich wywołań:

'AuthorizationUri' => 'https://ssl.allegro.pl/auth/oauth/authorize', --> powinno być https://allegro.pl/auth/oauth/authorize
'TokenUri' => 'https://ssl.allegro.pl/auth/oauth/token' --> powinno być https://allegro.pl/auth/oauth/token

**Comment by tenszaqu** [comment]
Ustawiłem, poki co działa. Zobaczymy :)
