### ISSUE TITLE
Wywołanie /sale/offers nie zwraca ofert

### ISSUE THREAD

**Issue by pyton-jajko** [allegro/allegro-api#6662]
- [x]  z zasobem REST API / with a REST API resource
- [x]  ze środowiskiem produkcyjnym / with the production environment
- [ ]  ze środowiskiem testowym / with the test environment
- [ ]  z logowaniem lub autoryzacją / with login or authorization
- [ ]  na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
- [ ]  inny / other
 
Mam następujący problem z pobraniem ofert poprzez REST API. Przy wywołaniu `GET /sale/offers` nie otrzymuję żadnej oferty, niezależnie od tego z jakimi parametrami odwołuję się na endpoint. Mam również konto sandbox z utworzonymi produktami - tam problem nie występuje. Natomiast na środowisku produkcyjnym klient posiada aktualnie nieco ponad 100 ofert, niestety żadna nie jest zwracana. Gdzie może leżeć problem?

**Comment by MartaNowaczyk** [comment]
Podaj proszę trace-id dla zapytania z pustą tablicą, postaram się sprawdzić czy nie odpytujesz czasem innego konta.

**Comment by pyton-jajko** [comment]
trace-id: 7bfe72e48cf6c817

**Comment by MartaNowaczyk** [comment]
Jesteś zautoryzowany na koncie Py......ko ID 49....03, a na tym koncie nie widzę ofert.

**Comment by pyton-jajko** [comment]
Udało się. Problemem był następujący: w Chrome'ie zalogowany byłem swoim kontem, a w Firefoxie kontem klienta. Autoryzację w oprogramowaniu robiłem z Chorme'a i automatycznie zautoryzowało mnie moim osobistym kontem. Bardzo mi to pomogło, dzięki! :)
