### ISSUE TITLE
Problem ze zdjeciami

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#6663]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [ x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Mamy problem z aktualizacja ofert, dla zapytania trace-id416047675aac2d9e dostajemy blad 
{
    "errors": [
        {
            "code": "VALIDATION_ERROR",
            "message": "Provided image address is incorrect.",
            "details": "OfferImagesNotFoundException",
            "path": "",
            "userMessage": "Podany adres obrazka jest nieprawidłowy."
        }
    ]
}
mimo ze wszystkie zdjecia wyslane w ofercie wygladaja jakby byly poprawne
"images": [{"url": "[https://a.allegroimg.com/original/11b2bf/2c536a7c4d93b881171096861011"}](https://a.allegroimg.com/original/11b2bf/2c536a7c4d93b881171096861011%22%7D), {"url": "[https://d.allegroimg.com/original/014663/c6392e6749f5b003f92e95d7be0d"}](https://d.allegroimg.com/original/014663/c6392e6749f5b003f92e95d7be0d%22%7D), {"url": "[https://a.allegroimg.com/original/114acd/53842e1c461e9735fdb153690736"}]}](https://a.allegroimg.com/original/114acd/53842e1c461e9735fdb153690736%22%7D]%7D)``

**Comment by mindc** [comment]
Dwa obrazki z tej listy są niedostępne/nieaktualne, błąd "Object not found".
Trzeba ponowić upload tych obrazków, albo zamienić na aktualne linki.

**Comment by AureliuszBrussy** [comment]
Potwierdzam - zdjęcia nie są już dostępne na serwerze (Object not found), stąd błąd.

**Comment by d3stozaur** [comment]
Teraz tak tylko w momencie wysyłania requestów zdjęcia były na serwerze, linki normalnie wyświetlały zdjęcia, jestescie w stanie sprawdzić date ich usunięcia z serwera i porównać z trace-id requesta?

**Comment by AureliuszBrussy** [comment]
Tak, timestamp Twojego requesta to 2023-02-01 15:25:32.639, 2 z 3 zdjęć wygasły wcześniej:  

"11b2bf/2c536a7c4d93b881171096861011": "2023-01-31T23:31:22.118Z"
"114acd/53842e1c461e9735fdb153690736": "2023-01-31T23:31:22.596Z"

**Comment by d3stozaur** [comment]
A czy jest mozliwosc ze macie te zdjecia jeszcze gdzies cachowane? Bo patrzac wczoraj na te requesty na 2 roznych komputerach na roznych przegladarkach powyzsze urle wyswietlaly normalnie zdjecia, dlatego tez zalozylem ticket. Ew. czy jest jakaś inna metoda sprawdzenia czy zdjecie jest na serwerze?

**Comment by AureliuszBrussy** [comment]
Cache'ujemy zdjęcia po naszej stronie, więcej przeczytasz w [naszym newsie](https://developer.allegro.pl/news/rozpoczynamy-cache-owanie-zdjec-m09ye2LW0HX). Natomiast zdjęcia na pewno wczoraj nie powinny być dostępne - usunęliśmy je jeszcze 31.01.

Gdy wgrywasz zdjęcia na nasz serwer ([POST /sale/images](https://developer.allegro.pl/documentation#operation/uploadOfferImageUsingPOST)), wraz z url'em zwracamy pole "expiresAt", gdzie znajdziesz informacje, kiedy wygasa. 

Później jedynym sposobem na sprawdzenie, czy zdjęcie jest jeszcze dostępne jest po prostu jego pobranie.

**Comment by d3stozaur** [comment]
ok w takim razie dzieki za pomoc i mozna zamknac zgloszenie

**Comment by glinkaa** [comment]
@AureliuszBrussy czy macie w planach wprowadzenie w API zasobu do sprawdzania czy obrazek nadal jest dostępny na waszych serwerach?

**Comment by AureliuszBrussy** [comment]
@glinkaa kiedy obraz nie jest już dostępny to przy próbie pobrania (GET na url obrazka) otrzymasz odpowiedź 404. Jeżeli obraz wciąż jest dostępny - zwrócimy odpowiedź ze statusem 200. W ten sposób możesz sprawdzić dowolne zdjęcie.
