### ISSUE TITLE
Brak wartości external przy zapytaniu /sale/offers

### ISSUE THREAD

**Issue by kochanA** [allegro/allegro-api#6664]
Dzień dobry,
wystawiłam oferty za pomocą API na koncie sandbox, widzę je ze wszystkimi danymi na koncie (EAN (GTIN):xxxxxxxxxxxxx) jednak przy zaciąganiu wystawionych ofert za pomocą zapytania /sale/offers otrzymuję przy ofertach, które mają 'status': 'ACTIVE', wartość dla 'external': None, to samo jest przy wartości  'status': 'ENDED' oraz 'status': 'INACTIVE'. Dodam, że na koncie produkcyjnym zaciąga mi ten parametr bez problemu. Zależy mi na external z tego konkretnego zapytania /sale/offers gdzie może leżeć przyczyna problemu ?

**Comment by AureliuszBrussy** [comment]
External.id to zewnętrzny identyfikator - należy go wcześniej w ofercie uzupełnić samodzielnie. Jeżeli to zrobisz (podczas tworzenia lub edycji oferty), to powinniśmy go zwrócić w odpowiedzi na [GET /sale/offers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET). Upewnij się, czy faktycznie go uzupełniłaś.

**Comment by kochanA** [comment]
bez tego nie da się wystawić oferty bo robię to za pomocą zapytania POST sale/product-offers, i widzę to external id na koncie przy wystawionych ofertach nawet tych nieaktywnych. Jednak przy pobieraniu ofert dostaję "external" : None

**Comment by AureliuszBrussy** [comment]
Można wystawić ofertę za pomocą [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers) bez przekazania `external.id` - nie jest to pole "required". Wskaż proszę przykładową ofertę na Sandboxie, gdzie uzupełniasz to pole, a mimo to nie otrzymujesz `external.id` w odpowiedzi na _GET /sale/offers_. Przed chwilą to przetestowałem i nie mogę potwierdzić tego problemu.

**Comment by kochanA** [comment]
Proszę to external id jednej z ofert 7700198301

**Comment by AureliuszBrussy** [comment]
Przy tworzeniu tej oferty nie wysłałaś żadnej wartości w polu external.id.

**Comment by kochanA** [comment]
To coś chyba robię źle bo to jest mój szablon oferty, gdzie przesyłam external_id : 

` {
    "productSet": [
        {
            "product": {
                "name": "!!! basennn !!!",
                "category": {
                    "id": "49846"
                },
                "images": [
                    "xxxxxxxxxxxxxxxxxxxxxxxxx"
                ],
                "parameters": [
                    {
                        "name": "EAN",
                        "values": [
                            "6941057420578"
                        ]
                    },
                    {
                        "name": "Szeroko\u015b\u0107",
                        "values": [
                            "80"
                        ]
                    },
                    {
                        "name": "D\u0142ugo\u015b\u0107",
                        "values": [
                            "100"
                        ]
                    },
                    {
                        "name": "Marka",
                        "values": [
                            "xxxxxxxxxxxxxxxx"
                        ]
                    },
                    {
                        "name": "Kod producenta",
                        "values": [
                            "xxxxxxxxx"
                        ]
                    },
                    {
                        "name": "Rodzaj",
                        "values": [
                            "stela\u017cowy"
                        ]
                    },
                    {
                        "name": "Kszta\u0142t",
                        "values": [
                            "okr\u0105g\u0142y"
                        ]
                    },
                    {
                        "name": "Pojemno\u015b\u0107",
                        "values": [
                            "1000"
                        ]
                    },
                    {
                        "name": "Wysoko\u015b\u0107",
                        "values": [
                            "80"
                        ]
                    }
                ]
            }
        }
    ],
    "sellingMode": {
        "price": {
            "amount": 6234.0,
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 1
    },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>basen basen basen basen basen basen</p>"
                    }
                ]
            }
        ]
    }
}
`

tu mam widok przykładowej oferty wystawionej już na sandbox i widać tu ean :
<img width="274" alt="image" src="https://user-images.githubusercontent.com/99121757/216319015-909fe052-5910-4177-b5aa-e80b0e57418f.png">

**Comment by AureliuszBrussy** [comment]
External.id to osobne pole w strukturze oferty:

```
...
"external": {
     "id": "AH-129834"
}
...
```
Prawdopodobnie mylisz je z parametrem EAN. W external.id możesz przekazywać dowolną wartość, może być to EAN produktu, jeżeli np. takie są Twoje potrzeby.
