### ISSUE TITLE
Statystyki Moja sprzedaż a API

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6665]
Szybkie pytanie, czy z poziomu API można pobierać dane z zakładki SPRZEDAŻ -> OBSŁUGA ZAMÓWIEŃ -> MOJA SPRZEDAŻ? Najbardziej zależy mi na statystykach "Moje wyniki na Allegro"

**Comment by AureliuszBrussy** [comment]
Nie udostępniamy endpointów, dzięki którym mógłbyś pobrać stricte te statystyki, natomiast część z nich powinieneś móc wyliczyć po prostu korzystając z dostępnych endpointów (np. [GET /order/checkout-forms](https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET)).
