### ISSUE TITLE
POCZTA_POLSKA Carrier Api Client is temporary unavailable

### ISSUE THREAD

**Issue by Desseres** [allegro/allegro-api#6669]
Występuje problem: 
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [X] z logowaniem lub autoryzacją / with login or authorization

Dzień dobry, mam problem z użyciem własnej umowy dla operatora POCZTA_POLSKA. Niestety musimy nadawać paczki poprzez naszą umowę, bo inaczej operator życzy sobie 15 zł za każdy podjazd samochodu dla umowy Allegro.

Staram się użyć poniższego id formy dostawy dla zamówień wysyłanych przy pomocy `Smart Allegro Kurier Pocztex`:

``
{"id": "f7e952b5-9ae8-40a9-90dd-e71ab9da29dd#a2ff7b1f-5f33-448c-ac9b-e183ae32930d",
            "service": "POCZTA_POLSKA",
            "name": "Pocztex Kurier48 (493023/C)",
            "owner": "CLIENT",
            "carrierId": "POCZTA_POLSKA"}
``

oraz tej formy dostawy dla zamówień `Smart Allegro Punkty Poczta, Żabka`: 

``
{"id": "d44995ed-edd2-4abb-999f-a56bd0f12a68#a2ff7b1f-5f33-448c-ac9b-e183ae32930d",
            "service": "POCZTA_POLSKA",
            "name": "Punkty Poczta, Żabka (493023/C)",
            "owner": "CLIENT",
            "carrierId": "POCZTA_POLSKA"}
``

w obu przypadkach otrzymuję błąd: `Carrier Api Client is temporary unavailable - try again later or report problem`

Przykładowe numery zamówień dla których występuje problem: 

- 9d8adec0-a2ce-11ed-999c-010c2b3719e5
- cd5abfc0-a2cf-11ed-b0cb-1f9cdb1329f2

**Comment by AureliuszBrussy** [comment]
Podaj proszę `trace-id`, które zwróciliśmy w response z errorem. Ew. podaj proszę `commandId` komendy, w której próbujesz utworzyć przykładową przesyłkę. Zweryfikuję to.

**Comment by Desseres** [comment]
Request UUID: 89227558-d7c5-4a98-b2ed-d73be2535fe6
Request UUID: d83f2378-be5e-4c9f-ac03-95026dbc893b
Request UUID: f12f08bf-ebc8-4588-ace8-a263e52cd38f
Request UUID: b38e2fc7-7e1c-419a-ad5f-ceb31430fc86

**Comment by Desseres** [comment]
Po nic nie robieniu, aktualny błąd zwracany przy próbie wygenerowania listu to: 

``Service Pocztex Kurier 48 (Przesyłka biznesowa) (852)') was disabled on user Poczta Polska account, parcelId[121368400]``

Request UUID: 79c5142c-1c36-4261-b308-1c2b9bff6cf1
Request UUID: 9c745b6a-38e5-4483-a02f-9a7f83a1d141
Request UUID: 32f8f23b-c398-4e8f-a053-a00385b05f2f
Request UUID: 6ba62a67-4e0f-4564-8174-4f67de0119ae

**Comment by AureliuszBrussy** [comment]
Zmień metody dostawy udostępnione w cennikach dostawy, aby móc je nadawać w ramach Twojej umowy. Informacje o nowych metodach znajdziesz [w komunikacie](https://allegro.pl/dla-sprzedajacych/nowe-metody-dostawy-pocztex-informacje-dla-sprzedajacych-VL11Z14VmS8).
