### ISSUE TITLE
[Pytanie] Możliwość dodania pola `isHidden` do wyników z `GET /offers/listing`

### ISSUE THREAD

**Issue by Uriziel01** [allegro/allegro-api#667]
Witam,
czy jesteście skłonni rozważyć dodanie pola `isHidden` które jest zwracane przez API w interfejsie użytkownika także w metodzie REST API `GET /offers/listing`? 

Ktoś z zespołu Allegro już wcześniej wypowiedział się że w temacie na temat ukrywania w API nie ma to sensu bo przecież to ukrywa tylko aukcje w interfejsie a nie w API. Oczywiście jest to jak najbardziej prawdą, ALE prowadzi to do jakichś kuriozalnych sytuacji gdzie klient zgłasza mi błędy bo kliknął "Ukryj" i w naszym interfejsie nic mu się nie ukrywa a proponowane rozwiązanie godzi oba poglądy.

Nie jestem za tym żeby ukryte aukcje wyfiltrowywać z listy zwracanych aukcji bo jest to faktycznie głupotą (przecież ta aukcja dalej istnieje) ale opcja dodania jedynie pola `isHidden` (które i tak u was istnieje i jest dokładnie w tym celu używane) wydaje mi się nieinwazyjna i tylko od programisty obsługującego API będzie zależeć co z taką informacją zrobi.

---
EDIT:
Obecnie poradziliśmy sobie dodając własne niezależne pole `isHidden` po naszej stronie ale w związku z tym że nie można stanu ukrycia ani z API pobrać ani zapisać to posiadamy teraz 2 całkowicie niezależne od siebie pola i dodatkową logikę która jest w tym przypadku kompletnie zbędna, na własne życzenie dodajemy pracy zarówno sobie jak i wam.

**Comment by PawelTaberski** [comment]
Dziękujemy za sugestię przekazałem ją do odpowiedniego zespołu. Jeśli zdecydujemy się wdrożyć takie pole poinformujemy o tym.
