### ISSUE TITLE
The HTTP method is not allowed

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#6670]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

```
{
  "errors": [
    {
      "code": "NotAllowedException",
      "message": "The HTTP method is not allowed",
      "details": null,
      "path": null,
      "userMessage": "An error occurred"
    }
  ]
}
```
Dostajemy taką zwrotkę z endpointu: 
/sale/product-offers/11981736103

Request został wysłany 2023-02-01 16:23:39
Niestety z loga nie mamy trace-id więc nie jestem w stanie wam tego podać

Czy jesteście w stanie powiedzieć dlaczego allegro zwróciło nam taki błąd?

**Comment by AureliuszBrussy** [comment]
Z naszych logów wynika, że wykonaliście request metodą PUT, która nie jest dostępna na tym zasobie.
