### ISSUE TITLE
What is a proper way to handle cancellation from seller

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#6671]
Hello, as discused earlier in this [issue](https://github.com/allegro/allegro-api/issues/6212#event-7677309171), i understand, we cannot set status cancelled from seller side, nor customer will be aware of cancellation done by change to fullfilment status "cancelled". You did advice us to contact customer in such case. Can you describe the process in detail for us?

Here is an exmaple of what I need for model situation, when last unit is damaged during expedition
1) New order comes thru
2) Fullfilmet status is set to "PROCESSING" by seller
3) We find out last unit is dammaged, setting fulfilment status to "SUSPENDED"
4) Contacting the buyer, asking to cancell order the order
5) After customer cancels order, we refund the customer and set fullfilment status to "CANCELLED"
6) We request commision refund

Is this process passable, or do you suggest different flow?
Also what happens, if the payment method was CoD and customer does not care to cancell order? How do we get the commision back? From my experience, the request for commision will be denied, due to customer not cancelling the order.

Thanks!

Jirka

**Comment by AureliuszBrussy** [comment]
We do not provide the possibility of cancellation of the order by the seller. The sequence of actions you presented is, of course, entirely correct. 

If have questions about commission refunds and their processing in the context of payments methods etc. - please use the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=e44a8a7c-9f93-459a-9912-27b28391bb58&subjectId=b041ba5e-65a2-4ba9-9953-91803db0e66f).
