### ISSUE TITLE
aktywacja oferty z parametrem który nie jest przesyłany 

### ISSUE THREAD

**Issue by ArturBakAxl** [allegro/allegro-api#6672]
/patch/sale/product-offers

{
    "id": null,
    "tax": {
        "id": "b763d782-572a-47db-8752-8b2cb32b3d0a",
        "rate": null,
        "subject": null,
        "exemption": null,
        "percentage": null
    },
    "name": "\u015aWIECA SREBRNA METALICZNA WALEC 60 X 100 MM",
    "stock": {
        "unit": "UNIT",
        "available": 36
    },
    "images": [
        "https:\/\/a.allegroimg.com\/original\/11e196\/ecf6c5c141baa357aa58c4e54d9f"
    ],
    "category": {
        "id": "254295"
    },
    "delivery": {
        "handlingTime": "P2D",
        "shipmentDate": null,
        "shippingRates": {
            "id": "cd2e9a99-d128-4484-a08c-0f3c8b51864e"
        },
        "additionalInfo": ""
    },
    "external": {
        "id": "63\/262"
    },
    "location": {
        "city": "...",
        "postCode": "...",
        "province": "...",
        "countryCode": "PL"
    },
    "payments": {
        "invoice": "VAT"
    },
    "promotion": {
        "bold": false,
        "highlight": false,
        "emphasized": false,
        "departmentPage": false,
        "emphasizedHighlightBoldPackage": null
    },
    "sizeTable": null,
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ]
        },
        {
            "id": "229205",
            "valuesIds": [
                "229205_340245"
            ]
        }
    ],
    "productSet": [
        {
            "product": {
                "id": null,
                "name": "\u015aWIECA SREBRNA METALICZNA WALEC 60 X 100 MM",
                "images": [
                    "https:\/\/a.allegroimg.com\/original\/11e196\/ecf6c5c141baa357aa58c4e54d9f"
                ],
                "category": {
                    "id": "254295"
                },
                "parameters": [
                    {
                        "id": "129255",
                        "values": [
                            "Domy\u015blny"
                        ],
                        "valuesIds": [
                            "129255_5"
                        ]
                    },
                    {
                        "id": "129256",
                        "valuesIds": [
                            "129256_2"
                        ]
                    },
                    {
                        "id": "129257",
                        "valuesIds": [
                            "129257_8"
                        ]
                    },
                    {
                        "id": "224017",
                        "values": [
                            "60\/100 SREBRNA"
                        ]
                    },
                    {
                        "name": "EAN",
                        "values": [
                            "5903978349322"
                        ]
                    },
                    {
                        "id": "229473",
                        "values": [
                            1
                        ]
                    },
                    {
                        "id": "236290",
                        "valuesIds": [
                            "236290_1158108"
                        ]
                    },
                    {
                        "id": "247365",
                        "values": [
                            100
                        ]
                    },
                    {
                        "id": "247369",
                        "values": [
                            60
                        ]
                    },
                    {
                        "id": "247373",
                        "values": [
                            60
                        ]
                    },
                    {
                        "id": "247377",
                        "values": [
                            "Domy\u015blny"
                        ]
                    },
                    {
                        "id": "247381",
                        "values": [
                            1
                        ]
                    },
                    {
                        "id": "247385",
                        "valuesIds": [
                            "247385_681273"
                        ]
                    },
                    {
                        "id": "249355",
                        "valuesIds": [
                            "249355_1158110"
                        ]
                    }
                ]
            }
        }
    ],
    "attachments": null,
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "..."
                    }
                ]
            },
            {
                "items": [
                    {
                        "url": "https:\/\/a.allegroimg.com\/original\/11e196\/ecf6c5c141baa357aa58c4e54d9f",
                        "type": "IMAGE"
                    }
                ]
            }
        ]
    },
    "publication": {
        "status": null,
        "endedBy": null,
        "duration": null,
        "endingAt": null,
        "republish": false,
        "startingAt": null
    },
    "sellingMode": {
        "price": {
            "amount": "11.85",
            "currency": "PLN"
        },
        "format": "BUY_NOW",
        "minimalPrice": null,
        "startingPrice": null
    },
    "__internal_array": null,
    "afterSalesServices": {
        "warranty": {
            "id": "7f14c0bc-1f0c-4ed8-8f12-d0ebbe241b59"
        },
        "returnPolicy": {
            "id": "d9507099-11ee-4d03-8b79-dce29de6c005"
        },
        "impliedWarranty": {
            "id": "60be06bd-75e2-489d-ae58-b775ced2ad61"
        }
    }
}

a w odpowiedzi:
{
    "body": {
        "errors": [
            {
                "code": "ConstraintViolationException.DependencyValidator",
                "path": "parameters",
                "details": "ConstraintViolationException.DependencyValidator",
                "message": "Dependent parameter Rodzaj bi\u017cuterii (246393) cannot take values [inny] when parameter Rodzaj (236290) has values [tradycyjna]",
                "userMessage": "Parametr zale\u017cny Rodzaj bi\u017cuterii (246393) nie mo\u017ce przyj\u0105\u0107 warto\u015bci [inny], gdy parametr Rodzaj (236290) ma warto\u015bci [tradycyjna]."
            }
        ]
    },
    "code": 422,
    "headers": {
        "0": "HTTP\/1.1 422 Unprocessable Entity",
        "date": "Fri, 03 Feb 2023 08:20:31 GMT",
        "pragma": "no-cache",
        "expires": "0",
        "trace-id": "4c5890dfc9e254bc",
        "content-type": "application\/json; charset=UTF-8",
        "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
        "content-length": "448",
        "x-frame-options": "DENY",
        "x-xss-protection": "1; mode=block",
        "x-content-type-options": "nosniff",
        "strict-transport-security": "max-age=31536000 ; includeSubDomains"
    }
}

otóż parametr **246393** nie jest w ogóle przekazywany!!

**Comment by AureliuszBrussy** [comment]
Wyjaśniam to z zespołem odpowiedzialnym za zasób. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Na podstawie parametrów z Twojego requestu dopasowaliśmy produkt, jednak w samym produkcie był błąd, który został już poprawiony. Problem aktualnie nie powinien się powtórzyć.
