### ISSUE TITLE
katalogowanie produktów

### ISSUE THREAD

**Issue by kochanA** [allegro/allegro-api#6673]
Dzień dobry,
wystawiam oferty zgodnie z wytycznymi poprzez zapytanie POST sale/product-offers poprzez szablon : "aktywną ofertę powiązaną z produktem, którego nie ma w naszym Katalogu" dzięki temu mam oferty powiązane z katalogiem i produkt dodawany jest do waszej bazy. Mam jednak konta, na których oferty były wystawione ręcznie bez powiązania z katalogiem. Pytanie czy mogę jakoś przez api wystawić moją bazę produktową do katalogu, żeby móc przy wystawianiu ofert korzystać z szablonu: "aktywną ofertę powiązaną z produktem, który istnieje w naszym Katalogu" ?

**Comment by AureliuszBrussy** [comment]
Możesz spróbować odszukać produkty w naszym Katalogu produktów za pomocą [GET /sale/products](https://developer.allegro.pl/documentation#operation/getSaleProducts). 

Jeżeli produkt nie istnieje, możesz utworzyć nowy - skorzystaj z [POST /sale/product-proposals](https://developer.allegro.pl/documentation#operation/proposeSaleProduct). 

Jeżeli posiadasz już id danego produktu - możesz go przypisać do istniejącej oferty za pomocą [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers). Więcej o tym przeczytasz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-przypisac-produkt-do-oferty).
