### ISSUE TITLE
WZA - Nazwa punktu nadania przesyłki jest za krótka

### ISSUE THREAD

**Issue by bartekc7** [allegro/allegro-api#6674]
Proszę o informację co może być przyczyną poniższego komunikatu.
W komunikacie to pole ma 5 znaków. Czy są gdzieś wyszczególnione ograniczenia pól?
  "pickup": {
      "name": "LL LL",

`{
  "id": "847ac766-4daf-4c05-abf7-c17b3bb6064d",
  "parcelId": null,
  "status": "ERROR",
  "errors": [
    {
      "code": "ERROR",
      "message": "Pickup name is too short",
      "details": null,
      "path": "pickup.name",
      "userMessage": "Nazwa punktu nadania przesy³ki jest za krótka"
    }
  ]
}`

**Comment by AureliuszBrussy** [comment]
W polu powinieneś wprowadzić imię i nazwisko. Pole jest wymagane, jeśli nie jest uzupełnione pole **company**. Minimum to 2 znaki dla imienia oraz 2 znaki dla nazwiska, przy czym całkowita długość pola to minimum 6 znaków.

**Comment by bartekc7** [comment]
Dziękuje za odpowiedź. Co ciekawe pole company też było wypełnione
      "name": "LL LL",
      "company": "\"L£\" SP. Z O.O. SP. K.",

**Comment by AureliuszBrussy** [comment]
@bartekc7 jako że przekazałeś wartość - zwalidowaliśmy wartość w "name", nie jest ona ignorowana.

**Comment by bartekc7** [comment]
Dziękuje za wyjaśnienia. Można zamknąć zgłoszenie.
