### ISSUE TITLE
How can I get purchases data?

### ISSUE THREAD

**Issue by LAmcpp** [allegro/allegro-api#6675]
What should the following request return - [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET)
???
This will list only the user's sales or all orders (all purchases + all sales).
And can I get data only about all active purchases of the user? And accordingly about all the expected parcels?

**Comment by AureliuszBrussy** [comment]
By using [GET /order/checkout-forms ](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET) you only get user sales. We do not provide any resources to get user purchases.

**Comment by LAmcpp** [comment]
Thanks for fast answer.
