### ISSUE TITLE
Aktywacja sprzedaży allegro sandbox

### ISSUE THREAD

**Issue by iamironmanblacksabbath** [allegro/allegro-api#6676]
Witam

Można prosić o aktywację sprzedaży dla konta iamironman na sandbox?

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.

**Comment by davidx77** [comment]
> Aktywowałem Twoje konto.

Również proszę o szybką aktywację sprzedaży w Sandbox, login - dejwiddd22 lub - client:105887994

**Comment by MartaNowaczyk** [comment]
@davidx77 odpowiedziałam Ci w wątku #6677

**Comment by iamironmanblacksabbath** [comment]
Bardzo dziekuje

**Comment by hipernet** [comment]
proszę aktywacje konta Motorynka_pl, zgemma-eu

**Comment by PrzemyslawLukanowski** [comment]
@hipernet Żaden z tych użytkowników nie widnieje w naszej bazie na Sandboxie. Tak jak wspomniałem w innym wątku - jest to odrębne środowisko od produkcji, musisz zatem [zarejestrować nowe konta.](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F)

**Comment by hipernet** [comment]
jeżeli mam konto firmowe jak mogę wykorzystać dotychczasowe dane do zalogowania się  do sandboxa

**Comment by PrzemyslawLukanowski** [comment]
Danych ze środowiska produkcyjnego allegro.pl nie możesz wykorzystać. Tak jak wcześniej wspomniałem, Sandbox to odrębne środowisko, zatem musisz zarejestrować tutaj nowe konto i aktywować je przez link aktywacyjny, który wyślemy na adres mailowy, który wskażesz przy rejestracji. Następnie będziesz mógł zalogować się na konto.
