### ISSUE TITLE
Aktywacja sprzedaży allegro sandbox

### ISSUE THREAD

**Issue by davidx77** [allegro/allegro-api#6677]
Witam, proszę o aktywację sprzedaży w Sandbox, login - dejwiddd22 lub - client:105887994

**Comment by MartaNowaczyk** [comment]
Jeśli za pomocą tego konta chcesz wystawiać oferty, musisz w takiej sytuacji zmienić jego rodzaj na firmowe. Zrobisz to przez zakładkę [Dane Konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) ("Zmień na firmowe"). Uzupełnij wszelkie możliwe dane, abym mogła je aktywować.

**Comment by davidx77** [comment]
Ok już zmieniłem na firmowe. Proszę o aktywację sprzedaży

**Comment by MartaNowaczyk** [comment]
@davidx77 napotkałam problem podczas aktywacji tego konta. Sprawdzamy w czym problem. Wrócę z informacją.

**Comment by davidx77** [comment]
Z czym konkretnie jest problem? Dane firmy muszą być prawdziwe?

**Comment by MartaNowaczyk** [comment]
To nie problem z podanymi danymi, na Sandbox można podawać fałszywe dane. To jest raczej kwestia po naszej stronie.

**Comment by davidx77** [comment]
I kiedy zostanie to naprawione? Czekam już prawie 4 dni na aktywację. Widziałem, że innym osobom aktywowaliście sprzedaż.

**Comment by davidx77** [comment]
Chodzi o ten przycisk "Aktywuj sprzedaż" tak? Wypełniłem już te wszystkie dane i czekam na zatwierdzenie.
Bo nie ma do zaznaczenia żadnej opcji sprzedaży.

**Comment by MartaNowaczyk** [comment]
@davidx77 Teraz udało mi się aktywować to konto. Sprawdź czy jest ok.
