### ISSUE TITLE
422 Validation error - You cannot publish offer without a related product

### ISSUE THREAD

**Issue by optima2b** [allegro/allegro-api#6678]
Treść błędu: "_You cannot publish offer without a related product in this category. Select from the catalog or create a new product and associate it with your offer_".

**W jaki sposób, przed wywołaniem POST /sale/offers, sprawdzić czy w danej kategorii wymagane jest połączenie oferty z produktem?** Ewentualnie, czy można sprawdzić poprzez API, jaki procent połączeń jest wymagany?

Dla przykładu, kategoria 252230. Pole offersWithProductPublicationEnabled z metody GET /sale/categories ma wartość true lecz parametr EAN z GET /sale/categories/252230/parameters nie jest wymagany. Dodatkowo, na stronie My Assortment, w kolumnie Allegro Product Catalog, znajduje się informacja "_No Catalog linking required_".

**Comment by MartaNowaczyk** [comment]
Zgodnie z naszym [newsem](https://developer.allegro.pl/news/od-dzisiaj-nowe-oferty-w-wybranych-dzialach-wystawisz-dopiero-gdy-polaczysz-je-z-katalogiem-produktow-d2qzkBwy2CZ) nową ofertę wystawisz dopiero, gdy [połączysz ją z Katalogiem produktów](https://allegro.pl/dla-sprzedajacych/jak-skatalogowac-swoja-oferte-VEWrZz6n4sv). Jeżeli produktu nie ma w naszej bazie, to korzystając z zasobów /sale/product-offers taką propozycję produktu można zgłosić, i tym samym stworzony zostanie nowy produkt. Dla niektórych kategorii Allegro nie jest konieczne określenie kodu EAN.
