### ISSUE TITLE
Problem z migracją z wystawiania przez `sale/offers` na `sale/product-offers`

### ISSUE THREAD

**Issue by Uriziel01** [allegro/allegro-api#6679]
Witam,
próbuję właśnie zmigrować klienta na nowy endpoint ale utknąłem na błędzie walidacji 
```
  0 => array:5 [▼
    "code" => "MissedCategoryIdException"
    "message" => "Unprocessable Entity"
    "details" => null
    "path" => ""
    "userMessage" => "Kategoria produktu jest wymagana. Należy podać id kategorii."
  ]
```
podczas gdy id kategorii jest oczywiście zdefiniowane w formacie wg. oficjalnej dokumentacji:
```
  "category" => array:1 [▼
    "id" => "76105"
  ]
```
i to samo zapytanie w starym `sale/offers` działa poprawnie.
Jakieś sugestie lub pomysły?

**Comment by MartaNowaczyk** [comment]
Byś może nie przekazujesz kategorii w "productSet". Podaj proszę trace-id dla wywołania z tym błędem, abym mogła zweryfikować sytuację.
