### ISSUE TITLE
Wznawianie aukcji wyprzedanych do 0

### ISSUE THREAD

**Issue by mkaluszka** [allegro/allegro-api#668]
Czy da się przez API wznowić ofertę wyprzedaną do 0? Bo wg mnie jest to jakaś luka - nie da się zwiększyć ilości w aukcji zakończonej. Jednocześnie nie da się wznowić aukcji bez zmiany ilości, jeśli ilość wystawiana = ilości sprzedanej. W mojej ocenie albo trzeba w momencie wystawiania automatycznie zwiększyć ilość o 1 i wtedy już systemy aktualizujące ilości sobie z tym poradzą, albo trzeba umożliwić zmianę ilości na aukcji zakończonej. Albo niestety zostaje ręczne wznawianie tych aukcji, ale to jest dość upierdliwe i niepotrzebne. Chyba, że nie widzę, czegoś oczywistego. Bo teraz wg mnie jedyna opcja, to wystawiać w ilości o 1 większej niż mamy i kończyć jeśli towar sie skończy. Ale to będzie powodować zdecydowanie więcej komplikacji niż korzyści.

**Comment by Rnapzsih** [comment]
Da się, wystarczy najpierw zrobić edycję stanów poprzez PUT na zasobie https://api.allegro.pl/sale/offers/ a następnie robisz już tylko publikację poprzez PUT na zasobie https://api.allegro.pl/sale/offer-publication-commands/$uuid

**Comment by Rnapzsih** [comment]
Chociaż przeglądam swoje aukcje to wszystkie, które zamykałem, nie miały stanu 0 na allegro tylko na sklepie. Zmiany robiłem nie ze stanu 0 i może dlatego u mnie wznawianie działa bez problemu.

**Comment by mkaluszka** [comment]
Nie używam jeszcze rest do wystawienia i edycji ofert poza zmiana ceny więc zanim w to się zagłębie to dopytam. Jak rozumiem ten pierwszy put pozwala na zmianę aukcji nawet jak jest nieaktywna? Bo zwykle API wsdl nie pozwala modyfikowac takich ofert.

**Comment by PawelTaberski** [comment]
Dokładnie tak jak napisał @Rnapzsih  musisz najpierw uzupełnić stan produktu w ofercie, a potem możesz ją aktywować. Więcej na temat jak wystawić i edytować ofertę przez REST API znajdziesz [tutaj](https://developer.allegro.pl/sale/).

**Comment by mkaluszka** [comment]
Dziękuję za pomoc - rzeczywiście udało się poprzez REST API zmienić nieaktywną ofertę i się wznowiła.
