### ISSUE TITLE
Nadmiarowe zdarzenia OFFER_STOCK_CHANGED /sale/offer/events

### ISSUE THREAD

**Issue by piotr-gomola** [allegro/allegro-api#6680]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,
Czy coś od 1 lutego zmieniło się w emisji zdarzeń podczas wznawiania ofert?
Mam przypadek następujący:
MTY3NTQ1MTYyODExNzg2NA -> aktywacja oferty (wznowienie)
5 sekund później jest emisja eventów OFFER_STOCK_CHANGED o id MTY3NTQ1MTYyODE4MzkxNw oraz MTY3NTQ1MTYyOTQxOTgxOQ, posiadają one identyczny timestamp
ID oferty: 13221045489

**Comment by MartaNowaczyk** [comment]
Zweryfikuję sytuację i wrócę z informacją.

**Comment by MartaNowaczyk** [comment]
W tym przypadku nie powinny pojawić się dwa zdarzenia. Pracujemy nad tym by wyeliminować takie sytuacje. Przepraszamy za niedogodności z tym związane.

**Comment by piotr-gomola** [comment]
@MartaNowaczyk  dziękuję. A czy wznowienie w ogóle powinno dla tego typu oferty emitować zdarzenie zmiany stanu magazynowego?

**Comment by MartaNowaczyk** [comment]
No właśnie w tej kwestii też jeszcze sprawę weryfikujemy, także dam znać.

**Comment by mbcont** [comment]
Witam, kiedy możemy spodziewać się rozwiązania problemu?

**Comment by MartaNowaczyk** [comment]
Jest to bardziej złożona kwestia niż może się wydawać, także to nie będzie kwestia kilku dni. Dam znać jeśli termin będzie możliwy do określenia.

**Comment by glorifyingpeace** [comment]
Podbijam temat. Jest ciężko z tą ilością zdarzeń.

**Comment by MartaNowaczyk** [comment]
Jak tylko będę miała nowe informacje na ten temat, na pewno dam znać. Na ten moment trwają prace nad poprawieniem sytuacji. Za niedogodności przepraszamy.

**Comment by mateuszbienias** [comment]
Witam, czy coś już może wiadomo?

**Comment by mbcont** [comment]
witam, czy coś już wiadomo?

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale jeszcze nie.

**Comment by mbcont** [comment]
witam, czy to już może jest naprawione?

**Comment by MartaNowaczyk** [comment]
Przykro mi, ale problem jest na tyle złożony, że jeszcze nad tym pracujemy. Będę informować jak coś się zmieni w tym temacie.

**Comment by MartaNowaczyk** [comment]
@mbcont @glorifyingpeace @piotr-gomola czy aktualne zachowanie dziennika ma duży wpływ na działanie logiki w Waszych aplikacjach? Generuje jakieś problemu, których nie jesteście w stanie obsłużyć?

**Comment by piotr-gomola** [comment]
@MartaNowaczyk Zdecydowanie tak, ponieważ cześć logiki opiera się o wystąpienie lub nie konkretnych zdarzeń lub ich kombinacji. Zostaliśmy zmuszeni do ograniczenia lub wyłączenia części funkcji również z powodu dużego wzrostu wolumenu danych. Jeśli ta "funkcjnonalność" nie ma uzasadnienia biznesowego z Państwa strony to definitywnie błąd powinien zostać poprawiony.

**Comment by MartaNowaczyk** [comment]
@piotr-gomola dziękuję za feedback.

**Comment by AureliuszBrussy** [comment]
@mbcont @glorifyingpeace czy mogę jeszcze prosić o feedback z waszej strony?

**Comment by glorifyingpeace** [comment]
Ja się zgadzam z @piotr-gomola

**Comment by mbcont** [comment]
zgadzam się z @piotr-gomola

**Comment by AureliuszBrussy** [comment]
@glorifyingpeace @mbcont dziękuję za odpowiedź.
