### ISSUE TITLE
Zgłoszenie "30763958" [ ref:_00D24aE05._5003VWIz6r:ref ]

### ISSUE THREAD

**Issue by ws-mkulas** [allegro/allegro-api#6682]
Witam, 

Pisałem kilkukrotnie przez formularz Allegro z prośbą o przyznanie dostępu funkcjonalności 
https://developer.allegro.pl/documentation#operation/getListing 

Pani z którą się kontaktowałem napisała, że przekazała informację do odpowiedniego działu, lecz odpowiedzi brak. 
Mój Client id: ```bf30bf34b560445e8d67dab9684fd7f9```

Pozdrawiam Michał

**Comment by AureliuszBrussy** [comment]
Przykro mi, że nie otrzymałeś jeszcze odpowiedzi, natomiast nasz zespół nie zajmuje się weryfikacją. W tych kwestiach proszę, abyś  kontaktował się w zgłoszeniu o którym wspomniałeś.

**Comment by ws-mkulas** [comment]
Niestety, ale wydaje mi się, że tamten dział nie pracuje. Próbowałem rok temu, jak i teraz. Zapytanie o temat skutkuje klasyczną odpowiedzią, że czekamy na odpowiedź z innego działu, tylko, że ona nigdy nie następuje.

**Comment by AureliuszBrussy** [comment]
Zespół ten pracuje - przykro mi, jednak nie jestem w stanie tego przyspieszyć, czy zmienić wcześniejszych decyzji. Jak już wspomniałem, pozostaje tylko kontakt w wątku wygenerowanym przez formularz kontaktowy.
