### ISSUE TITLE
Czy jest możliwość posiadania najtańszej ceny produktu w allegro?

### ISSUE THREAD

**Issue by DawidPPGithub** [allegro/allegro-api#6683]
Witam, 

czy jest możliwość posiadania najtańszej ceny produktu w allegro? Dokładniej chodzi mi o podanie np. nazwy produktu do api i otrzymanie najtańszej ceny ze wszystkich ofert allegro pasujących do tej nazwy. 

Z góry dziękuję za odpowiedź.

**Comment by AureliuszBrussy** [comment]
Nie udostępniamy endpointu, który zwróciłby stricte takie dane, czyli dane o najtańszej ofercie dla wskazanego produktu. 

W ramach naszego API możesz jedynie wyszukiwać i przeglądać oferty dostępne na Allegro za pomocą [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) i filtrować wyniki m.in. po cenie. Dostęp do tego endpointu jest jednak ograniczony i możliwy jedynie po wcześniejszej weryfikacji. Więcej o tym przeczytasz w [newsie](https://developer.allegro.pl/news/get-offers-listing-tylko-dla-zweryfikowanych-aplikacji-GRax4oVgrs1) oraz [poradniku](https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk).

**Comment by DawidPPGithub** [comment]
Witam ponownie,

W powyżej wysłanym poradniku jest napisane, że trzeba dołączyć do programu partnerskiego lub skontaktować się przez formularz. Skontaktowałem się przez formularz i w odpowiedzi na mailu odesłali mnie do was. Jak mogę zweryfikować aplikację, aby mieć dostęp do zasobu "Search offers" w api?

**Comment by AureliuszBrussy** [comment]
Niestety, zostałeś błędnie przekierowany, nie zajmujemy się weryfikacją. Czy możesz podać numer Twojego zgłoszenia wysłanego przez formularz?

**Comment by DawidPPGithub** [comment]
Zgłoszenie nr "31329514"

**Comment by AureliuszBrussy** [comment]
@DawidPPGithub dziękuję, poprosiłem zespół obsługi o ponowne przyjrzenie się zgłoszeniu. Powinieneś niebawem otrzymać wiadomość w zgłoszeniu.
