### ISSUE TITLE
API Allegro nie odpowiada.

### ISSUE THREAD

**Issue by guliano06** [allegro/allegro-api#6685]
Mam problem z API Allegro po przez sky-shop. Brak możliwości dodania aukcji na allegro. Błąd ''API Allegro nie odpowiada.
Spróbuj później lub wystaw mniejszą liczbę produktów. Wszelkie pytania dotyczące działania API należy kierować bezpośrednio do Allegro.''
Proszę o pomoc, bądź odblokowanie użytkownika - guliano06.
Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Wg naszych danych, powinieneś otrzymać komunikat "Prowadząc sprzedaż na koncie zwykłym (nie zarejestrowanym jako konto firma).". Jest to prawidłowy komunikat, ponieważ[ od 27 lipca 2022](https://developer.allegro.pl/news/od-dzis-oferty-przez-api-moga-wystawiac-i-edytowac-tylko-uzytkownicy-z-kontem-firmowym-9gRePwXxGiP) konta zwykłe nie mogą wystawiać ofert i nimi zarządzać za pomocą API.

**Comment by guliano06** [comment]
W takim razie w jaki sposób wystawić produkty ? Teraz mam taki błąd ''Brak dostępu. Nie masz uprawnień do operacji na wskazanej ofercie [Forbidden (OfferAccessDeniedException)]''

**Comment by PrzemyslawLukanowski** [comment]
Aby wystawiać oferty i nimi zarządzać, musisz posiadać konto firmowe. Możesz[ zmienić typ swojego aktualnego konta](https://allegro.pl/pomoc/dla-sprzedajacych/dane-i-ustawienia-konta/jak-zmienic-status-konta-ze-zwyklego-na-firmowe-rKxBgnr6ksx) lub zarejestrować nowe.
