### ISSUE TITLE
Problem z użyciem tokenu dostępu do REST API Allegro

### ISSUE THREAD

**Issue by zymod** [allegro/allegro-api#6686]
Dzień dobry,

Prosze o pomoc w użyciu tokenu dostępu do Allegro REST API.

Skrypt generujący token jest napisany w Python wedle dokumentacji Allegro Device Flow i wygląda następująco:

[genererate_access_token.py]

import requests
import json
import time
import os
import urllib3
from dotenv import load_dotenv
load_dotenv()
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

lizard_id = os.getenv('LIZARD_ID')
lizard_secret = os.getenv('LIZARD_SECRET')

CODE_URL = "https://allegro.pl/auth/oauth/device"
TOKEN_URL = "https://allegro.pl/auth/oauth/token"

def access_token(_id, _secret):
    
    def get_code():
        try:
            payload = {'client_id': _id}
            headers = {'Content-type': 'application/x-www-form-urlencoded'}
            api_call_response = requests.post(CODE_URL, auth=(_id, _secret),
                                            headers=headers, data=payload, verify=False)
            return api_call_response
        except requests.exceptions.HTTPError as err:
            raise SystemExit(err)

    def get_access_token(device_code):
        try:
            headers = {'Content-type': 'application/x-www-form-urlencoded'}
            data = {'grant_type': 'urn:ietf:params:oauth:grant-type:device_code', 'device_code': device_code}
            api_call_response = requests.post(TOKEN_URL, auth=(_id, _secret),
                                            headers=headers, data=data, verify=False)
            return api_call_response
        except requests.exceptions.HTTPError as err:
            raise SystemExit(err)

    def await_for_access_token(interval, device_code):
        while True:
            time.sleep(interval)
            result_access_token = get_access_token(device_code)
            print(result_access_token)
            token = json.loads(result_access_token.text)
            if result_access_token.status_code == 400:
                if token['error'] == 'slow_down':
                    interval += interval
                if token['error'] == 'access_denied':
                    break
            else:
                return token['access_token']

    def generate_token():
        code = get_code()
        result = json.loads(code.text)
        print("User, open this address in the browser:" + result['verification_uri_complete'])
        access_token = await_for_access_token(int(result['interval']), result['device_code'])
        print("access_token = " + access_token)
        return access_token

    return generate_token

Powyższy kod otwiera przeglądarke w którą wprowadzam kod dostępu. Następnie musze się zalogować do konta allegro w celu uwierzytelnienia po czym do konsoli otrzymuje kod dostępu który zawiera 1284 znaki.

Teraz gdy wykonam zapytanie http do api allegro za pomocą curl: (oczywiście podnieniam {token} na mój kod dostępu)

curl -X GET \
  'https://api.allegro.pl/sale/offers' \
 -H 'Authorization: Bearer {token}' \
 -H 'Accept: application/vnd.allegro.public.v1+json'

W rezultacie otrzymuje błąd:

curl: (6) Could not resolve host: Bearer
curl: (6) Could not resolve host: access_token
curl: (6) Could not resolve host: application

Gdy spróbuje wykonać zapytanie za pomocą Python przy użyciu biblioteki requests które wygląda następująca:
[get_offers.py]
import requests
from database import db

url =  'https://api.allegro.pl/offers'

access_token = db.get_access_token('1')

headers = {}
headers['Accept'] = 'application/x-www-form-urlencoded'
headers['Authorization'] = f'Bearer {access_token}'

api_call_response = requests.get(url, headers=headers)
print(api_call_response.text)

W rezultacie otrzymuje błąd:
{"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept' request header","details":null,"path":null,"userMessage":"The request contains incorrect data. Contact the author of the application."}]}

Będę wdzięczny za pomoc w odpowiedzi na pytanie gdzie popełniam błąd w zapytaniu o listę ofert i czy nie powinienem również dostać tokenu odświeżenia przy wygenerowaniu tokenu dostępu?

**Comment by PrzemyslawLukanowski** [comment]
Prawidłowy nagłówek Accept dla tego wywołania, jak i pozostałych (prócz wersji beta) zasobów, to "application/vnd.allegro.public.v1+json" - widzę, że w ostatnim wywołaniu używasz "application/x-www-form-urlencoded". Jeśli nadal będziesz otrzymywać błąd, podaj nam proszę trace-id wywołania, pozwoli nam to namierzyć Twoje żądania w naszych logach.
Odpowiadając na Twoje ostatnie pytanie - tak, za każdym razem zwracamy parę tokenów: access i refresh token.

**Comment by zymod** [comment]
Zmieniłem Accept na application/vnd.allegro.public.v1+json lecz nie pomogło. 

Obecny kod wygląda tak:

[get_offers.py]
url =  'https://api.allegro.pl/offers'

headers = {}

headers['Accept'] = 'application/vnd.allegro.public.v1+json'
headers['Authorization'] = f'Bearer {access_token}'

api_call_response = requests.get(url, headers=headers)


output kończy się takim samym błędem jak poprzednio :/

**Comment by zymod** [comment]
Zmieniłem Accept na application/vnd.allegro.public.v1+json lecz nie pomogło.

Obecny kod wygląda tak:

[get_offers.py]
url = 'https://api.allegro.pl/offers'

headers = {}

headers['Accept'] = 'application/vnd.allegro.public.v1+json'
headers['Authorization'] = f'Bearer {access_token}'

api_call_response = requests.get(url, headers=headers)

output kończy się takim samym błędem jak poprzednio :/

trace_id = 7ce41f15f6628575

**Comment by PrzemyslawLukanowski** [comment]
Prawidłowy url to https://api.allegro.pl/sale/offers. W swoim wywołaniu używasz https://api.allegro.pl/offers.

**Comment by zymod** [comment]
Super! Dziękuję za pomoc wszystko jest ok

**Comment by PrzemyslawLukanowski** [comment]
Czy w tym przypadku również możesz podać przykładowe trace-id? W naszych logach widzę próby odpytania o szczegóły oferty, której nie jesteś właścicielem. To może być jeden z powodów, przez który zwróciliśmy status 403.
