### ISSUE TITLE
Limity API modyfikacji ofert

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#6687]
Dzień dobry,

Czy wysokość limitów API https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#limity dokonujących modyfikacji ofert _(np. PUT /sale/offer-price-change-commands/{commandId} | 250 tys. ofert na godzinę i 9 tys. na minutę)_ dotyczą 1 użytkownika autoryzowanego w ramach aplikacji, czy wszystkich użytkowników korzystających z jednej aplikacji?

**Comment by AureliuszBrussy** [comment]
Te limity są nałożone na pojedynczego użytkownika aplikacji.
