### ISSUE TITLE
Logowanie request/response

### ISSUE THREAD

**Issue by Hornir91** [allegro/allegro-api#6693]
Witam.

Niedawno zaktualizowałem aplikację z Allegro API V1 do V2. W starej wersji logowałem zapytania, dodając do AllegroAuth i AllegroClient swojego loggera, który umożliwiał logowanie requestów, które wychodzą do Allegro, a także otrzymywanych odpowiedzi.

        $this->allegroAuth = new AllegroAuth($this->appCredentials, $this->logger);
        $this->allegroClient = new AllegroClient($this->appCredentials, $this->logger);

W wersji V2 mam problem ze znalezieniem metody, która umożliwiłaby podpięcie swojego loggera, aby logował requesty oraz response'y pochodzące z Allegro. Wg pliku readme wystarczy utworzyć instancję API (poniżej), lecz nie wiem jak do tej instancji podpiąć swój logger.

        $this->allegroApi = new AllegroApi($this->credentials);

Czy trzeba napisać swój customowy Plugin i podpiąć go do metody ChainPlugin, która obsługuje requesty, czy jest jakiś inny sposób?

Z góry dziękuję za odpowiedź.

**Comment by hahyes** [comment]
Niestety to nie jest forum do wspierania jakichś nieznanych pluginów. Skontaktuj się z autorem aplikacji.

**Comment by AureliuszBrussy** [comment]
@Hornir91 taj jak wspomniał @hahyes - najlepiej, jeżeli skontaktujesz się z autorem aplikacji, z której próbujesz skorzystać.
