### ISSUE TITLE
Sandbox API Get search products results error AccessDenied

### ISSUE THREAD

**Issue by tuannt-eco** [allegro/allegro-api#6694]
try:
        url = URL_MAIN + "/sale/offers"
        headers = {
            'Authorization': 'Bearer ' + token,
            'Accept': "application/vnd.allegro.public.v1+json",
            'Content-Type': "application/vnd.allegro.public.v1+json"
        }
        query = {
            'language': 'en-US'
        }
        result = requests.get(url, headers=headers, params=query, verify=False)
        return result
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)

I write the above code in python but it always return error 403 AccessDenied. I'm not sure what step I did wrong.

**Comment by PrzemyslawLukanowski** [comment]
I've checked our logs and it seems that you are using [client_credentials ](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#clientcredentials-flow )type of authorization (marked as bearer-token-for-application in our documentation). To use this resource, you need to use bearer-token-for-user authentication, which means the token generated via [authorization code ](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device flow](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow).
Also, "/sale/offers" endpoint does not support the "language" query parameter. I believe you wanted to use "/sale/products" resource.
