### ISSUE TITLE
Przekraczanie limitu szkiców mimo dużo mniejszej ilości szkiców niż wskazuje błąd

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#6695]
Witam,

z powodu problemów z przekroczeniami limitów szkiców muszę zapytać: jak ten limit funkcjonuje? Co jest traktowane jako szkic? Co jest zliczane lub nie? 

```
Nie możesz utworzyć nowych szkiców - Twoje konto przekroczyło maksymalną liczbę 20000 szkiców.
```

Załóżmy, że mam na koncie w danej chwili 0 (słownie: zero) szkiców ofert. Po wystawieniu 200 aukcji (miałem taką sytuację) wyskakuje mi błąd o przekroczeniu limitu 20000 (słownie: dwudziestu tysięcy) szkiców. Usuwam istniejące szkice ofert. Problem się powtarza po wystawieniu kolejnych 200 aukcji. Sytuacja się powtarza wielokrotnie.

Błąd ten w zasadzie blokuje mi możliwość wystawiania do czasu usunięcia aktualnych szkiców. Czym jest ten limit? Czy oznacza on, że w ciągu doby nie mogę utworzyć więcej niż 20 tysięcy szkiców? Wliczają się do tego poprawnie wystawione i aktywujące się oferty? 

Proszę o wyjaśnienie tego zagadnienia, ponieważ nie rozumiem jak to jest możliwe że po wystawieniu kilkuset aukcji otrzymuje blokadę i muszę atakować API kolejnymi zapytaniami zamykania szkiców.

**Comment by PrzemyslawLukanowski** [comment]
Szkicem określamy wyłącznie tę ofertę, której aktualny status, to "INACTIVE". Aktualną ich liczbę możesz sprawdzić za pomocą wywołania GET /sale/offers?publication.status=INACTIVE, informację zwrócimy w polu `totalCount`. Nie ma tutaj zastosowania limit dobowy, o którym wspomniałeś, szkice traktujemy całościowo. 
Jeśli szkiców rzeczywiście masz mniej, ale problem z komunikatem występuje co jakiś czas, to podaj nam proszę przykładowe trace-id. Na tej podstawie zidentyfikujemy Twoje konto i przeanalizujemy sytuację z rozbieżnością danych.

**Comment by hahyes** [comment]
> Szkicem określamy wyłącznie tę ofertę, której aktualny status, to "INACTIVE". Aktualną ich liczbę możesz sprawdzić za pomocą wywołania GET /sale/offers?publication.status=INACTIVE, informację zwrócimy w polu `totalCount`. Nie ma tutaj zastosowania limit dobowy, o którym wspomniałeś, szkice traktujemy całościowo. Jeśli szkiców rzeczywiście masz mniej, ale problem z komunikatem występuje co jakiś czas, to podaj nam proszę przykładowe trace-id. Na tej podstawie zidentyfikujemy Twoje konto i przeanalizujemy sytuację z rozbieżnością danych.

Proszę bardzo, przykładowy trace-id sprzed chwili.
`Trace-Id: 325713cd908efc18`

Problem występuje nagminnie i to od wielu dni. W tym momencie na przykład widzę ok. 1900 szkiców na tym koncie. Zaobserwowałem, że głównie problem występuje po próbie utworzenia dużej ilości szkiców zakończonych niepowodzeniem np. z powodu braku parametru. Tak jakby szkice niewidoczne dla mnie się naliczały. Możliwe, że jest to powiązane z problemem https://github.com/allegro/allegro-api/issues/6657, który też zgłaszałem. Występują tam zdarzenia dla szkiców, które teoretycznie nie powstały ale zakładam, że wewnętrznie one zostały jakoś utworzone w systemie. Może te szkice gdzieś tam są naliczane, co powoduje takie zachowanie API.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za przykład, zweryfikuję sytuację z zespołem odpowiedzialnym za usługę i wrócę z informacją.

**Comment by hahyes** [comment]
@PrzemyslawLukanowski Niestety jest to już druga wasza interwencja, choć oczywiście za poprawienie jestem bardzo wdzięczny. Problem jest powtarzalny i nalegam aby zespół odpowiedzialny za usługę pochylił się nad problemem.

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, mamy na uwadze ten problem, będziemy pracować nad tym, aby rozwiązać go globalnie, jednak na tę chwilę nie mogę wskazać konkretnej daty, kiedy to się wydarzy.

**Comment by hahyes** [comment]
@PrzemyslawLukanowski Nie ma sprawy, w takim razie zamykam temat. Dziękuję za pomoc i pozdrawiam.

**Comment by hahyes** [comment]
@PrzemyslawLukanowski Niestety muszę zgłosić, że naprawienie licznika działa na krótką metę. Kilkanaście godzin później limit szkiców powrócił. Jednak to nie wszystko, ponieważ nie mogłem aktywować utworzonych szkiców z powodu:

```
Could not change offer publication status. You cannot publish new offers - your account has exceeded the maximum number 200000 of active offers.
```
Błąd wystąpił wczoraj w okolicy godziny 16.

Jak taki błąd mógł się pojawić przy 38 tysiącach na tamten moment? Nie mam pojęcia. Jednak takie problemy wskazują, że nie tylko licznik szkiców zachowuje się nieprawidłowo. Prosiłbym o weryfikację i zbadanie problemu, ponieważ to uciążliwie spowalnia pracę.

**Comment by MaciejFrackowiak** [comment]
@hahyes Licznik już poprawiony u Ciebie. Zdajemy sobie sprawę, iż mocno uprzykrza to pracę - staramy się podejść do naprawy tego globalnie, jednak to wymaga ciut czasu.

**Comment by hahyes** [comment]
> Licznik już poprawiony u Ciebie. Zdajemy sobie sprawę, iż mocno uprzykrza to pracę - staramy się podejść do naprawy tego globalnie, jednak to wymaga ciut czasu.

@MaciejFrackowiak Rozumiem i dziękuję za poprawkę licznika. Pozostawiam tym razem wątek otwarty jako iż problem nadal występuje.

**Comment by MaciejFrackowiak** [comment]
@hahyes Mam nadzieję, iż tym razem problem tak szybko nie powróci.

**Comment by Uriziel01** [comment]
Witam,
jakieś wieści odnośnie "globalnej" poprawki? Mamy obecnie jedynie 8000 szkiców a błąd wciąż się pojawia. Proszę o możliwie szybką interwencję.

**Comment by MaciejFrackowiak** [comment]
@Uriziel01 Prace trwają - tyle mogę w skrócie obecnie napisać. Podaj proszę id lub login swojego konta, wówczas zgłoszę je do aktualizacji.

**Comment by Uriziel01** [comment]
@MaciejFrackowiak
<details>
  <summary>Login:</summary>
  superstore
</details>

**Comment by MaciejFrackowiak** [comment]
@Uriziel01 Otrzymałem informację, że licznik jest obecnie zaktualizowany.

**Comment by Uriziel01** [comment]
@MaciejFrackowiak **Mogę pilnie prosić o ponowne poprawienie licznika dla tego konta, klient usunął większość szkicy a błąd wciąż występuję.** No i o informację kiedy i w jakiej formie planowane jest globalne wdrożenie poprawki? Dziękuję.

**Comment by MaciejFrackowiak** [comment]
@Uriziel01 Proszę podaj przykładowy trace-id wywołania.

**Comment by MaciejFrackowiak** [comment]
@Uriziel01 I bez trace-id udało się już poprawić licznik. Prace trwają, i niestety konkretnego terminu obecnie wskazać nie potrafię.
