### ISSUE TITLE
Czy można nadać wystawionej ofercie status INACTIVE za pomocą /offer-publication-commands

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#6696]
Dzień dobry,
U mnie na sklepie szefowa prosiła mnie abym wyłączył na allegro część ofert. Bo nie ma ich już na magazynie.
Za miesiąc ma przyjść dostawa i wtedy trzeba będzie je z powrotem włączyć.

Mam pytanie, jak w temacie, czy mogę ustawić status trwającej oferty jako INACTIVE za pomocą /offer-publication-commands
Dziękuję

**Comment by PrzemyslawLukanowski** [comment]
INACTIVE to status zarezerwowany wyłącznie dla szkiców, czyli dla ofert, które nie były jeszcze aktywowane. W związku z tym, niestety nie ma takiej możliwości, możesz jednak analogicznie zmienić status na "ENDED" (oferta zakończona) i ponownie ją aktywować, gdy zajdzie taka potrzeba.

**Comment by Witold1983** [comment]
Dobrze. Ok, dziękuję
