### ISSUE TITLE
Weryfikacja konta sandbox

### ISSUE THREAD

**Issue by adibuu** [allegro/allegro-api#6697]
Dzień dobry,

prosiłbym o weryfikację konta: uniqsoft@2bi.today

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.

**Comment by hipernet** [comment]
dlaczego nie moge sie zalogować na to samo hasło na sandboxa

**Comment by PrzemyslawLukanowski** [comment]
@hipernet Sandbox jest odrębnym środowiskiem od produkcji, musisz [zarejestrować tutaj nowe konto](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F).
