### ISSUE TITLE
PATH oferty wyrzuca "message":"The HTTP method is not allowed"  dla  /sale/offers/product_id

### ISSUE THREAD

**Issue by nnerel** [allegro/allegro-api#6698]
Witam.  Wykonując metodę PATCH na zasób 'https://api.allegro.pl/sale/offers/{offer_id}' otrzymuje  error 405
 {"errors":[{"code":"NotAllowedException","message":"The HTTP method is not allowed"

Log wskazuje jakby zasób nie obsługiwał metody PATCH ale dokumentacja podaje że https://api.{environment}/sale/product-offers/{offerId}  obsługuje PATCH. 

Gdy wykonam PUT otrzymam błąd 400 "message":"Message not readable" 

Czy błąd leży po stronie przekazywanych parametrów do zapytania czy używam błędnego zasobu do tej operacji?

**Comment by PrzemyslawLukanowski** [comment]
Zwróć proszę uwagę, że najpierw wspominasz o zasobie /sale/offers/{offerId}, który metody PATCH nie obsługuje, dopiero dalej wskazałeś prawidłowy adres endpointu - /sale/product-offers/{offerId}. PATCH na /sale/offers/{offerId} prawidłowo zwróci 405.

Przy metodzie PUT otrzymujesz 400, ponieważ najprawdopodobniej przekazujesz strukturę przeznaczoną dla zasobu /sale/product-offers/{offerID}, która różni się od tej, którą przyjmuje zasób /sale/offers/{{offerID}.
