### ISSUE TITLE
Pobieranie informacji o stawce VAT dla zamówień

### ISSUE THREAD

**Issue by Morph21** [allegro/allegro-api#6699]
Dzień dobry,

Chciałbym się dowiedzieć w jaki sposób mogę pobrać stawki vat zastosowane do zamówienia.

Aktualnie flow u mnie przebiega w następujący sposób:
1. Pobranie listy zamówień /order/checkout-forms
2. Wyciągnięcie offerId (bez powtórzeń) z obiektu lineItem dla wszystkich pobranych zamówień
3. Pętla pobierająca obiekt oferty tyle razy ile jest offerId /sale/product-offers/offerId lub /sale/offers/offerId
4. Wyliczenie kwot netto na podstawie informacji z pkt 3

I tutaj pojawia mi się kilka pytań
Pt 1. Czy jest jakaś różnica dotycząca tylko podatku vat pomiędzy endpointem /sale/product-offers/offerId a /sale/offers/offerId
Pt 2. Czy nie da się podać do jakiegoś endpointu listy offerId żeby nie wywoływać tego endpointu kilkadziesiąt razy (zależnie od ilości zamówień) w pętli?
Pt 3. Czy to podejście jest w ogóle prawidłowe czy powinno być coś zmienione?
Pt 4. Jak pobrać stawkę vat dla zamówienia dla którego nie pobiera się oferta? Zarówno /sale/product-offers/offerId i /sale/ofers/offerId zwraca mi dla niektórych offerId kod 404 mimo że zamówienia te zostały pobrane z endpointu /order/checkout-forms

**Comment by hahyes** [comment]
Czy korzystasz z offer.external_id? Wypełniasz to pole czymś, jak tworzysz oferty? Może warto by było wykorzystać to pole do przechowywania informacji o ofercie jak np. VAT? `offer.external_id` jest zwracane prosto w `lineitem` zamówienia. To taki trochę hack, ale jak najbardziej może ci to skrócić drogę.

**Comment by Morph21** [comment]
Tworzymy rozwiązanie dla naszych klientów których liczba jest dosyć duża, nie mamy kontroli nad utworzeniem oferty. Jedynie pobieramy zamówienia dla których w naszym systemie klient może wystawić faktury

**Comment by PrzemyslawLukanowski** [comment]
1. Nie ma, oba zasoby zwracają te same informacje na temat podatku VAT w polu „tax”. Miej jednak na uwadze, że zasób /sale/offers/{offerId} wyłączymy z końcem roku, dlatego warto przechodzić już wyłącznie na zasób /sale/product-offers/{offerId}.
2. Prócz słusznego rozwiązania, o którym napisał hayhes, niestety nie ma takiej możliwości. Informacje o stawce VAT zwracamy wyłącznie na poziomie szczegółów oferty.
3. Tak, podejście jest prawidłowe.
4. Najlepiej, jeśli wskażesz nam numer przykładowej oferty (lub trace-id, gdzie w odpowiedzi zwróciliśmy 404 Not Found). Jeśli oferta została zakończona 60 dni temu lub więcej i nie została w międzyczasie aktywowana ponownie, przenosimy ją wtedy do archiwum i jej pobranie nie jest już możliwe. Może to być jeden z powodów, przez który zwróciliśmy ten kod błędu.

**Comment by Morph21** [comment]
Dziękuję za odpowiedź. Co do pkt 4 to faktycznie oferta była dosyć stara.

Czy są jakieś plany aby rozbudować możliwość pobrania ofert na podstawie podania listy offerId? 

Jestem mocno zdziwiony że takiej funkcjonalności w Allegro nie ma gdzie praktycznie każda konkurencja posiada możliwość pobrania informacji o kwotach netto/brutto w łatwy sposób lub przesyła je bezpośrednio w zamówieniu.

Podczas tworzenia aplikacji mamy różne poziomy dostępu i jako że klienci nie koniecznie chcą udostępniać możliwość edycji ofert przez zewnętrzne oprogramowanie wydaje mi się że słusznym sposobem pobierania danych nie powinno być wymuszone ich tworzenie przez zewnętrzne oprogramowanie.

**Comment by PrzemyslawLukanowski** [comment]
Aktualnie nie mamy takich planów, zachęcam Cię jednak do założenia zgłoszenia w sekcji ["Discussions"](https://github.com/allegro/allegro-api/discussions). Zbieramy w niej wszelkie sugestie, które dotyczą dalszego rozwoju API Allegro.
