### ISSUE TITLE
Niezaktualizowane ilości sprzedanych przedmiotów z doGetMySellItems

### ISSUE THREAD

**Issue by cyfranT** [allegro/allegro-api#67]
Witam.

Ostatnio zdarzyło się kilka razy, że metoda doGetMySellItems zwróciła nieaktualne dane dotyczące ilości sprzedanych przedmiotów (itemsoldquantity).

Jeden z konkretnych przykładów: w pobranych zdarzeniach z doGetSiteJournal (wywołanie metody o godz. 07:04:32), było zdarzenie zakupu "now" z godziny 05:44:57, a metoda doGetMySellItems wywołana o godzinie 07:05:33 dalej zwracała niezaktualizowaną liczbę sprzedanych przedmiotów na tej aukcji (ID 7088686877) - bez uwzględnienia sprzedaży z godz. 5:44.

**Comment by PawelTaberski** [comment]
Podeślij nam przez formularz kontaktowy (https://allegro.pl/pomoc/kontakt#subjectId=9fe60f94-a07b-47e5-84b4-b15beafe2422) requesty i responsy od tych metod, wraz z dokładnymi czasami wywołania. Sprawdzimy w czym jest problem.
