### ISSUE TITLE
403 ProductProposalsAccessForbiddenException

### ISSUE THREAD

**Issue by adibuu** [allegro/allegro-api#6700]
Witam,

wysyłam POST na https://api.allegro.pl.allegrosandbox.pl/sale/product-offers

z body: 

`{
    "productSet": [
        {
            "product": {
                "name": "Logitech Mysz M185 Swift szara bezprzewodowa",
                "category": {
                    "id": "4575"
                },
                "parameters": [
                    {
                        "id": "221621",
                        "values": [
                            "Logitech"
                        ]
                    },
                    {
                        "id": "224017",
                        "values": [
                            "910-002238"
                        ]
                    },
                    {
                        "id": "237206",
                        "values": [
                            "M185"
                        ]
                    },
                    {
                        "id": "516",
                        "values": [
                            "1600"
                        ]
                    },
                    {
                        "id": "517",
                        "values": [
                            "USB"
                        ]
                    }
                ],
                "images": []
            }
        }
    ],
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h2>Mysz Logitech M185 Swift szara bezprzewodowa</h2>"
                    }
                ]
            }
        ]
    },
    "images": [
        "https://eoptimo.store/data/gfx/pictures/large/3/2/23_5.jpg"
    ],
    "sellingMode": {
        "price": {
            "amount": "53",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 10
    }
}`

w odpowiedzi otrzymuję:

403 Forbidden

`{
    "errors": [
        {
            "code": "ProductProposalsAccessForbiddenException",
            "message": "Access denied.",
            "details": null,
            "path": "productSet[0].product",
            "userMessage": "Brak dostępu."
        }
    ]
}`

Moje konto zostało aktywowane:

![image](https://user-images.githubusercontent.com/46864745/217777424-7c84b8b4-a868-43c2-809b-5fb1857b4ee1.png)

korzystam z [Authorization code flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow)

trace-id: eecb3de5cccc9c1c

Co powoduje ten błąd?

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję ten przypadek, wstępnie wygląda to na problem z aktywacją sprzedaży na danym koncie. Wrócę z informacją, jak tylko uda się ustalić więcej szczegółów.

**Comment by MartaNowaczyk** [comment]
@adibuu Twoje konto powinno być aktywne. Sprawdź proszę czy wszystko ok.

**Comment by adibuu** [comment]
> @adibuu Twoje konto powinno być aktywne. Sprawdź proszę czy wszystko ok.

Tak, wszystko już działa. Dzięki.
