### ISSUE TITLE
Skrypt dostępowy do API

### ISSUE THREAD

**Issue by wbankowski** [allegro/allegro-api#6702]
'trace-id': 'ac4947a30cbe9764',

Co w tym skrypcie jest nie tak? Próbuję wywołać go i cały czas zwraca mi błąd 403. Klucze Client_Id i Client_secret oczywiście podaje poprawne. Token generuje się poprawnie. Chcę pobrać dane zamówień.
`const axios = require("axios");

const CLIENT_ID = "XXXXX";
const CLIENT_SECRET = "XXXXXXX";
  
  async function getAccessToken() {
    try {
      const authorization = Buffer.from(`${CLIENT_ID}:${CLIENT_SECRET}`).toString('base64');
      const headers = {
        Authorization: `Basic ${authorization}`,
        'Content-Type': 'application/x-www-form-urlencoded'
      };
      const response = await axios.post('https://allegro.pl/auth/oauth/token',
        'grant_type=client_credentials',
        { headers }
      );
      const accessToken = response.data.access_token;
      console.log(`Access token: ${accessToken}`);
      return accessToken;
    } catch (error) {
      console.error(error);
    }
  }
async function getOrderEvents(accessToken) {
  try {
    const response = await axios({
      method: "get",
      url: "https://api.allegro.pl/order/events",
      headers: {
        Accept: "application/vnd.allegro.public.v1+json",
        Authorization: `Bearer ${accessToken}`
      }
    });
    console.log(response.data);
    return response.data;
  } catch (error) {
    console.error(error);
  }
}

async function main() {
    const accessToken = await getAccessToken();
    const orderEvents = await getOrderEvents(accessToken);
  }

main();

`

**Comment by AureliuszBrussy** [comment]
Korzystasz z autoryzacji typu client_credentials i generujesz token dla aplikacji, a nie dla użytkownika. Eventy w ofertach możesz pobrać jedynie w imieniu konkretnego użytkownika. Powinieneś więc wygenerować token w ramach [authorization code flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow)
 lub [device flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow).
