### ISSUE TITLE
Wysyłam z Allegro DHL - błąd

### ISSUE THREAD

**Issue by lukasz-lopata** [allegro/allegro-api#6703]
Witam, 
Podczas próby nadania paczki spedytorem DHL na środowisku testowym dostajemy błąd mówiący o niepoprawnej usłudze. ServiceId jest przekazywany zgodnie z instrukcjami. Proszę o sprawdzenie i informację co może być nie tak.

trace-id=3b7091d806c26975

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Aby skorzystać z usługi dostawy "Allegro Kurier DHL" podczas nadawania, w zamówieniu kupujący powinien skorzystać z analogiczny metody dostawy. W zamówieniu kupujący skorzystał nie skorzystał z "Allegro Kurier DHL", ale z "Kurier DHL". 

Spróbuj udostępnić w cenniku dostawy przypisanego do oferty metodę z Allegro w nazwie i zakup w ofercie ponownie, wybierając tą metodę dostawy. Wtedy powinno udać się wygenerować przesyłkę dla nowego zamówienia.

**Comment by lukasz-lopata** [comment]
Po poprawnym wybraniu metody dostawy dostajemy następujący błąd podczas próby nadania

"userMessage":"error.common.processing"

trace-id=9e6f6cae18bf7b66

**Comment by AureliuszBrussy** [comment]
Zgłosiłem ten problem do zespołu odpowiedzialnego za zasób. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@lukasz-lopata wracam z informacją - wystąpiły w tamtym czasie problem z testowym API przewoźnika.
