### ISSUE TITLE
ANOTHER_SERVICE_NOT_AVAILABLE. One of required services is unavailable.

### ISSUE THREAD

**Issue by awawrowicz** [allegro/allegro-api#6704]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Poniższa sytuacja dla Allegro Kurier DPD.

Request:
/parcel-management/parcel-create-commands/f89b8b3a-d15d-4cbc-bf21-a4992a0d8fd5

Response:
{
    "id": "f89b8b3a-d15d-4cbc-bf21-a4992a0d8fd5",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ANOTHER_SERVICE_NOT_AVAILABLE",
            "message": "One of required services is unavailable. Try again later.",
            "details": "One of required services is unavailable. Try again later.",
            "path": null,
            "userMessage": "Jeden z wymaganych serwisów, do poprawnego działania, jest niedostępny. Spróbuj ponownie za moment."
        }
    ]
}

**Comment by AureliuszBrussy** [comment]
@awawrowicz adres e-mailowy, którego próbujesz użyć pochodzi z zamówienia ze środowiska testowego (Sandbox).

**Comment by awawrowicz** [comment]
Dzięki za podpowiedź. Faktycznie był problem z nieprawidłowym adresem email. Szkoda, że komunikat błędu w żaden sposób nie naprowadza na źródło problemu.

**Comment by AureliuszBrussy** [comment]
@awawrowicz tak, to jest do poprawny po naszej stronie.
