### ISSUE TITLE
WZA API - Dostępne jednostki 

### ISSUE THREAD

**Issue by bartekc7** [allegro/allegro-api#6705]
Czy jest jakaś metoda wyciągnięcia obsługiwanych jednostek dla danej metody dostawy?

W serwisie jak chce nadać przesyłkę np. Allegro Paczkomaty InPost to mam do wyboru gabaryty jak poniżej:
![image](https://user-images.githubusercontent.com/207927/217830465-63122956-2592-4916-8a1e-e839a673f64b.png)

Generując przesyłkę poprzez API chciałbym, znając metodę wysyłki podpowiedzieć użytkownikowi np. tylko paczki o określonych gabarytach jak powyżej lub tylko palety jeśli wybrał usługę paletową. 
Pytanie czy w ogóle jest możliwe pobranie tej informacji obecnie?

Zgłaszałem też to jako pomysł [tu](https://github.com/allegro/allegro-api/discussions/6667) ale nie wiem czy cokolwiek się z tym zadzieje.

**Comment by AureliuszBrussy** [comment]
W naszym API nie zwracamy informacji dotyczących gabarytów. Na ten moment informacje takie możesz uzyskać od przewoźników czy np. z [artykułów w pomocy Allegro](https://allegro.pl/dla-sprzedajacych/allegro-paczkomaty-inpost-informacje-dla-sprzedajacych-dyBd14MXRFg). Oczywiście zgłoszone sugestie przekazujemy do zespołów odpowiedzialnych za konkretne zasoby, natomiast nie gwarantuje to wdrożenia zmiany. Priorytet mają także sugestie, które cieszą się większą popularnością. 

Jeżeli coś zmienimy - będziemy to komunikować i poinformujemy o tym w Twojej sugestii.
