### ISSUE TITLE
Rozłączanie autoryzacji OAuth2 co 12h 

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#6706]
Witam, mam problem z rozwiązywanie autoryzacji allegro średnio co 12h 
w zwrotce na jakikolwiek endpoint dostajemy  "Access token expired". Moglibyście proszę to zweryfikować? Tylko na jednym konkretnym koncie allegro mamy ten błąd czy to związku z tym jest problem?

przykładowy trace-id: 304c36d861ef3991

**Comment by hahyes** [comment]
Access token wygasa co 12 godzin, to jest normalne. Musisz użyć refresh token do wygenerowania nowej pary access_token i refresh_token.

**Comment by MaciejFrackowiak** [comment]
Ze swojej strony mogę tylko dodać [odnośnik](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena) do poradnika, gdzie opisaliśmy proces przedłużania ważności tokena.

**Comment by DamianKAtomStore** [comment]
No tak zgadzam się, tylko że generujemy standardowo nowy klucz cronem co +- 12h a w odpowiedzi dostajemy to:

```
{
"error": "Unauthorized",
"error_description": "Unauthorized"
}
```
Niestety nie widzę żebyście zwracali  z tego endpointa (/auth/oauth/token) trace id

**Comment by MaciejFrackowiak** [comment]
@DamianKAtomStore Abyśmy mogli cokolwiek sprawdzić potrzebujemy przykładu wywołania - proszę podeślij go poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) - w treści wiadomości podaj również nr wątku z GH - 6706.

**Comment by MaciejFrackowiak** [comment]
Otrzymaliśmy Twoje zgłoszenie, co pozwoliło spojrzeć mi w nasze logi:

1) 2023-02-20 01:30:17 - otrzymałeś tu access + refresh token (ten którego dane przesłałeś nam w zgłoszeniu);
2) 2023-02-20 13:30:38 - wystąpiłeś tu ponownie o autoryzację wykorzystując refresh token z punktu 1, w odpowiedzi otrzymałeś nową parę access + refresh token, refresh token z punktu 1 automatycznie traci ważność;
3) 2023-02-20 13:32:27 - tu ponownie odświeżasz token z wykorzystaniem refresh tokena z punktu 1 - jest on już nieważny, ponieważ 2 minuty wcześniej otrzymałeś całkowicie nową parę.

Sprawdź proszę działanie swojego mechanizmu odświeżania tokenów. Najlepiej, gdybyś operację wykonywał chwilę przed upływem 12 godzin ważności refresh tokena.
