### ISSUE TITLE
Błąd HttpMessageNotReadableException przy dodawaniu produktu

### ISSUE THREAD

**Issue by LechKulesza** [allegro/allegro-api#6709]
Mam problem z dodaniem produktu do Allegro Sandbox:

Idąc za poradnikiem:

1. Patrzę na parametry potrzebne dla danej kategorii
URL: `https://api.allegro.pl.allegrosandbox.pl/sale/categories/13368/product-parameters`
Metoda: GET
Headery:

- Accept: `application/vnd.allegro.public.v1+json`
- Authorization: `Bearer {token}`
- Accept-Language: `en-US`

Dostaje wszystkie parametry (według API parametr `EAN (GTIN)` nie jest wymagany dla tej kategorii)

2. Dodaje zdjęcia (dodają się prawidłowo)
3. Staram się dodać produkt poprzez:
URL: `https://api.allegro.pl.allegrosandbox.pl/sale/product-proposals`
Metoda: POST
Headery:

- Accept: `application/vnd.allegro.public.v1+json`
- Content-Type: `application/vnd.allegro.public.v1+json`
- Authorization: `Bearer {token}`
- Accept-Language: `en-US`

Jako body

```{"name":"Soccer` ball","category":{"id":"13368"},"images":[{"url":"https://a.allegroimg.allegrosandbox.pl/original/11a587/572eeb9b41378efb871797026359"}],"parameters":[{"id":"130411","unit":"","valuesIds":["130411_8"]}],"description":{"sections":[{"items":[{"type":"TEXT","content":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."}]}]}}```

I tutaj jako response dostaje kod 400:
`"{\"errors\":[{\"code\":\"HttpMessageNotReadableException\",\"message\":\"An error has occurred\",\"details\":null,\"path\":null,\"userMessage\":\"Request contains invalid data. Contact the application author.\"}]}"`

Byłbym bardzo wdzięczny za pomoc!

**Comment by PrzemyslawLukanowski** [comment]
Spróbowałem odtworzyć Twój błąd, jednak w moim przypadku otrzymałem status 422 z treścią błędu, która wskazuje na brak znaczników HTML w sekcji "description". Dodatkowo zauważyłem także, że próbujesz utworzyć produkt w kategorii, która nie jest liściem, tzn. w GET /sale/categories, w polu "leaf", nie zwracamy dla niej wartości `true`. Przekazujesz także nadmiarowe pole "unit" z pustym stringiem - możesz je usunąć. 
Jeśli nadal będziesz otrzymywać błąd po wprowadzeniu tych zmian, podaj nam proszę przykładowe trace-id. Zweryfikujemy w logach, jaką dokładnie strukturę od Ciebie otrzymujemy.

**Comment by LechKulesza** [comment]
Zmieniłem kategorię na taką która jest liściem, usunąłem "unit" oraz dodałem znaczniki HTML w sekcji description i body wygląda następująco:

`{
    "name":"Soccer ball",
    "category": {
        "id":"13369"
    },
    "images": [
        {"url":"https://a.allegroimg.allegrosandbox.pl/original/11a587/572eeb9b41378efb871797026359"}
    ],
    "parameters": [
        {"id":"130411","valuesIds":["130411_8"]}
    ],
    "description": {
        "sections": [{
            "items": [{
                "type":"TEXT",
                "content":"<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>"
            }]
        }]
    }
}`

Ale niestety nadal dostaję błąd 400, taki sam jak wcześniej.

trace-id dla tego request: `fb72ebfe844c4495`

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję. Według naszych logów Twój request nie zawiera w ogóle podpiętej struktury JSON, stąd różnica między Twoim kodem błędu 400, a moim 422, który wskazuje na inne źródło błędu. Upewnij się, że payload jest prawidłowo "podpinany" do żądania - aktualnie powinieneś otrzymać 422 z poniższą informacją:

```
{
    "errors": [
        {
            "code": "ProductParameterGtinRequired",
            "message": "Empty GTIN: 225693",
            "details": null,
            "path": "parameters",
            "userMessage": "W tej kategorii wymagane jest podanie parametru EAN (GTIN)"
        }
    ]
}
```

**Comment by LechKulesza** [comment]
```
"{\"errors\":[{\"code\":\"ProductParameterGtinRequired\",\"message\":\"Empty GTIN: 225693\",\"details\":null,\"path\":\"parameters\",\"userMessage\":\"This category requires parameter EAN (GTIN)\"}]}"
```

Zmieniłem metodę i dostaje poprawny błąd! Dzięki!

Swoją drogą to dziwne bo poprzednie requesty wysyłałem z Postmana wybierając w body raw > JSON więc powinny być normalnie podpięte...
