### ISSUE TITLE
Błędnie zwracany wymagany parametr EAN!

### ISSUE THREAD

**Issue by Uriziel01** [allegro/allegro-api#6711]
Witam,
napotkaliśmy błąd praktycznie uniemożliwiający pracę z naszą aplikacją na podstawie parametrów pobieranych z API.
Podczas wystawiania aukcji w kategoriach 76034 (Bluzki) oraz 254778 (Spodnie) w samym przeglądarkowym interfejsie Allegro pole EAN (GTIN) jest opcjonalne, jednak w API gdy odpytujemy o parametry dla tych samych kategorii otrzymujemy następującą odpowiedź (parametr jest w obu przypadkach wymagany):
![image](https://user-images.githubusercontent.com/568207/218335735-a094172c-0903-4243-9a41-2bd42e6322b1.png)
![image](https://user-images.githubusercontent.com/568207/218335748-0bbcbe57-029c-4dd4-bfa1-2d3ee7a72b12.png)
![image](https://user-images.githubusercontent.com/568207/218335776-e97f0ccb-3a08-4b44-8786-1180b3d88b08.png)

Sprawdzaliśmy zarówno endpoint 
`/sale/categories/{categoryId}/parameters` jak i 
`/sale/categories/{categoryId}/product-parameters`

**Comment by PrzemyslawLukanowski** [comment]
Parametr jest oznaczony jako required, ponieważ jest to parametr zależny - wymagamy go, gdy stan oznaczony jest jako "nowy" oraz dla wybranych marek. Na formularzu wystawiania możesz to sprawdzić, jeśli zmienisz nazwę marki na np. "adidas". Potwierdzam jednak, że w niektórych sytuacjach może wystąpić błąd i komunikat o wymaganym numerze EAN zostanie przez nas zwrócony, mimo że oferta powinna zostać utworzona prawidłowo ([powiązany wątek](76034)). Pracujemy jeszcze nad rozwiązaniem tego problemu, przepraszam za niedogodności.

**Comment by glorifyingpeace** [comment]
Mamy ten sam problem. Podpinam się tu żeby wiedzieć kiedy nastąpi rozwiązanie.

**Comment by PrzemyslawLukanowski** [comment]
Wprowadziliśmy poprawkę - aktualnie, jeśli [wymagalność parametru GTIN jest uzależniona od wybranej marki](https://allegro.pl/dla-sprzedajacych/16-stycznia-zmienilismy-wymagane-parametry-w-niektorych-kategoriach-8dA1n0A69fk), w polu `required` zwracamy wartość false.

**Comment by glorifyingpeace** [comment]
Co w przypadku w którym wymagalność GTIN uzależniona jest od parametru MARKA i STAN?

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam za niedoprecyzowanie, właśnie o takie sytuacje chodzi (nie ma scenariusza, gdzie wymagalność GTIN jest zależna wyłącznie od marki).

**Comment by Uriziel01** [comment]
Z tego co rozumiem ta logika pozostaje, musisz wtedy posiłkować się polami `dependsOnParameterId` oraz `requiredDependsOnValueIds` aby poprawnie wykryć czy pole jest w danej sytuacji wymagane czy też nie. Wdrożenie nie jest zbyt skomplikowane 🙂

**Comment by glorifyingpeace** [comment]
OK, wszystko zrozumiałe

**Comment by PrzemyslawLukanowski** [comment]
Tak, wymagalność nadal jest uzależniona od stanu "Nowy" i konkretnych marek, chciałbym Was jednak poinformować, że informacji o markach na tę chwilę, ze względów technicznych, nie zwrócimy w odpowiedzi GET /sale/categories/{id}/parameters. Pracujemy nad zmianami, które uwzględnią te informacje. Przepraszam za niedogodności, o zmianach będziemy informować na naszej stronie i forum.

**Comment by glorifyingpeace** [comment]
Czy przy wystawianiu przez formularz Allegro (front) te warunki działają poprawnie?
Sprawdzałem kategorie: 
Sukienki do Tenisa (które są w spisie kategorii które wymagają EAN - obowiązkowy-ean-w-modzie.xlsx)
https://allegro.pl/kategoria/odziez-sukienki-257794
i wybieranie marki z listy i spoza listy w przypadku gdy pole stan miało wartości: "NOWY" bądź "Używany" marka nie miała wpływu na wymagalność pola EAN.

**Comment by glorifyingpeace** [comment]
Czy możecie wygenerować json z kategoriami i markami które mają teraz teraz ten problem?

**Comment by PrzemyslawLukanowski** [comment]
@glorifyingpeace Wspomniana przez Ciebie kategoria nie powinna znaleźć się w pliku, przepraszam za pomyłkę - zostawimy w niej wyłącznie wymagalność na podstawie parametru stan. Poniżej znajdziesz listę kategorii, gdzie zależność wymagalności według stanu i określonej marki działa już teraz. Jest to proces ciągły i w pozostałych kategoriach wymienionych w pliku chcemy go zakończyć w kolejnych tygodniach. Aktualna lista marek znajduje się we wspomnianym pliku.

Kategorie, w których włączyliśmy wymagalność GTIN w zależności od parametru stan i wybranej marki (są to kategorie liście, najniższego rzędu, natomiast w pliku na stronie uwzględniliśmy także kategorie wyższego rzędu, stąd kategoria widoczna tutaj, może nie być widoczna w pliku):

```
257253
97554
257677
10783
261793
76040
123449
1493
76111
261788
76110
1491
257020
147417
257234
5554
76075
1494
1489
5553
76042
27000
15550
76095
76036
5541
123429
124265
76096
87981
76077
5543
123450
76044
78137
5540
76043
76083
76076
76035
76084
76102
254778
254259
76034
124264
25958
76025
76103
```

**Comment by glorifyingpeace** [comment]
@Przemyslaw Powiedz mi proszę, czy jeśli parametr EAN (GTIN), jego wymagalność zależy od więcej niż jednego parametru, (w naszym przypadku od parametru STAN i MARKA), to czy EAN (GTIN) powinien być wymagany jeśli spełnione będą oba te warunki czy przynajmniej jeden z nich?

Przykład 1:
Stan -> Nowy (wymagaj EANu)
Marka -> Abc (nie wymagaj EANu)

W tym przypadku EAN (GTIN) powinien być wymagany czy nie?

Przykład 2:
Stan -> Nowy (wymagaj EANu)
Marka -> Xyz (wymagaj EANu)

A jak w tym przypadku?

Czy zawsze będzie stosowana tylko jedna z poniższych logik?
- ustaw pole jako wymagane jeśli spełnione są wszystkie warunki
- ustaw pole jako wymagane jeśli spełniony jest przynajmniej jeden warunek

**Comment by PrzemyslawLukanowski** [comment]
Jeśli stan jest "używany", nie wymagamy EANu w takiej sytuacji niezależnie od wyboru marki. Muszą zatem zostać spełnione dwa warunki:

- stan - "Nowy",
- marka znajduje się na liście marek, dla których wymagamy podania EAN.

**Comment by glorifyingpeace** [comment]
Wyłapałem jeszcze kategorie:
75994
87873

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, mam ten wątek na uwadze - wrócę z informacją o kategoriach.

**Comment by PrzemyslawLukanowski** [comment]
@glorifyingpeace Przepraszam, że tak długo musiałeś czekać na odpowiedź. Poniżej znajdziesz listę kategorii, w których wprowadziliśmy dodatkową zależność od parametru Marka. Jednocześnie chciałbym Cię poinformować, że pracujemy nad zmianami w naszym API, które uwzględnią te informacje - o wszelkich szczegółach będziemy informować na naszej stronie oraz forum. 

```
10783
123429
123448
123449
123450
124264
124265
147417
147743
1489
1491
1493
1494
15550
19865
19913
251128
254259
254260
254778
254779
257020
257112
257234
257253
257677
257903
257929
257987
25958
25959
260415
261787
261788
261791
261793
27000
55202
55203
55205
55206
55207
5537
5538
5540
5541
5542
5543
5547
5553
5554
5556
75994
76025
76034
76035
76036
76040
76042
76043
76044
76075
76076
76077
76083
76084
76095
76096
76102
76103
76104
76110
76111
78137
87837
87839
87843
87846
87873
87875
87876
87893
87894
87897
87913
87981
89510
89515
91193
97554
97557
```

Odnośnie

> Tymczasem formularz wystawiania już wymaga i komunikat zwrotny dostajemy

W tym przypadku zarówno formularz, jak i API funkcjonuje tak samo - EAN wymagamy tylko w sytuacji, jeśli stan = Nowy oraz marka znajduje się na naszej liście.
