### ISSUE TITLE
[sandbox]  Nie można pobrać zdjęcia z adresu 'Internal server error'. 

### ISSUE THREAD

**Issue by trisopl** [allegro/allegro-api#6713]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Czy na sandbox jest jakiś problem z pobieraniem zdjęć (sale/product-offers)? Za każdym razem dostajemy taki komunikat:
Nie można pobrać zdjęcia z adresu 'https://booktown.pl/files/_product/17/business-english-b1-b2-gettinenglish.png'. Serwer ze zdjęciem zwrócił kod HTTP: 500 INTERNAL_SERVER_ERROR z błędem: 'Internal server error'. 

Przykład dla zdjęcia:
https://booktown.pl/files/_product/17/business-english-b1-b2-gettinenglish.png

Na produkcji działa to bez problemów. Co ciekawe pobieranie plików innego typu działa prawidłowo, np. 
https://booktown.pl/files/_product/17/__product/business-english-b1-b2-gettinenglish.webp

Ten problem występuje wyłącznie na sandbox.

**Comment by SylwesterZarebski** [comment]
Od rana pojawia się w sandboksie *INTERNAL_SERVER_ERROR* w różnych sytuacjach. Wcześniej w ogóle nie można było odczytać zamówienia, teraz przynajmniej to działa.

**Comment by trisopl** [comment]
Dzięki za poprawki. Przez jakiś czas dało się dodawać zdjęcia, ale aktualnie jest taki komunikat:
Nie można pobrać zdjęcia z adresu 'https://booktown.pl/files/_product/18/job-interview-gettinenglish.png'. Serwer ze zdjęciem zwrócił kod HTTP: 500 INTERNAL_SERVER_ERROR z błędem: 'DNS resolve timeout'. 

Na wersji oficjalnych takich komunikatów nie dostajemy

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję tę sytuację z odpowiednim zespołem. Jak tylko uda nam się ustalić więcej szczegółów, wrócę z odpowiedzią.

**Comment by trisopl** [comment]
Zdjęcia są dodawane jak kilkukrotnie się wyśle formularz. Za drugim, trzecim razem jest już ok ;)

**Comment by PrzemyslawLukanowski** [comment]
Czy problem z tym konkretnym obrazkiem pojawił się jeden raz czy więcej razy? Rozumiem, że błąd występuje także dla innych obrazków- czy mógłbyś podać nam kilka przykładów?
