### ISSUE TITLE
Problem dotyczący Sandbox

### ISSUE THREAD

**Issue by Jtest987** [allegro/allegro-api#6714]
Hej, 

od wczoraj mimo wyboru opcji opłaty rachunku na Sandbox konto posiada blokadę sprzedaży - nie pomaga nic - ani przeklikanie się przez kontakt z Allegro ani kilkukrotne wyklikanie nadpłaty - to dotyczy konta założonego na adres jtestowy999@gmail.com

Drugi problem - trwa weryfikacja drugiego konta firma na Sandbox - jest w toku i nie procesuje dalej - konto sprzedawcatestowy02

Będę wdzięczny za informacje :)

**Comment by MaciejFrackowiak** [comment]
Konto "jtestowy999@gmail.com" już odblokowane. Jednocześnie nie mogę znaleźć w naszej bazie konta o loginie "sprzedawcatestowy02" - sprawdź proszę poprawność loginu.

**Comment by Jtest987** [comment]
Dziękuję! Jeśli chodzi o drugie konto to jest założone na mail sprzedawcatestowy02@gmail.com i jego login to Partnertest02.

**Comment by MaciejFrackowiak** [comment]
Konto "Partnertest02" również jest już aktywne.
