### ISSUE TITLE
Podwójne naliczanie kosztów allegro DPD za granicę.

### ISSUE THREAD

**Issue by jata2** [allegro/allegro-api#6715]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x ] inny / other

:beetle: **Opis / Description**

Witam,
na wstępie chciałbym powiedzieć iż nie jestem programistą proszę mi więc wybaczyć laicki język i zapytanie aczkolwiek allegro nie może sobie poradzić z problemem mojej firmy i odesłało mnie na to forum.

Otóż do obsługi zamówień allegro obsługujemy aplikacji Baselinker.
Zdarzy się klient zagraniczny, który jako formę wysyłki wybiera allegro DPD za granicę.

Oprócz tego, że korzystamy z allegro DPD mamy też własną umowę DPD.

Zgodnie z wszelakimi wytycznymi w takim przypadku przy generowaniu listu przewozowego allegro DPD należy podać mail allegro.
Wtedy DPD "wie" że jest to przesyła allegro, wtedy rozliczamy się z allegro zgodnie z cennikiem itd. a nie z DPD

Przejrzałem biling DPD za miesiąc styczeń i jakież było moje zdziwienie iż kilka przesyłek zostało policzone nie przez allegro a przez DPD

I teraz tak:
DPD twierdzi iż przesyłki zostały policzone przez DPD gdyż nie dodano maila allegro do etykiety.

Baselinker twierdzi iż odpowiedni request z mailem allegro został wysłany.

Allegro twierdz iż wysyłki allegro DPD za granicę można zrobić tylko i wyłącznie z poziomu allegro co jest nonsensem gdyż baselinker zrobił nawet specjalną wtyczkę do "wysyłam z allegro" i wątpię by sprzedawcy, którzy dziennie wysyłają kilkaset-kilka tysięcy wysyłek dziennie ręcznie "klepali" wszystko na poziomie allegro a nie poprzez program zewnętrzny.

Moje pytanie brzmi:
czy ktoś z Was miał już taki problem? Jeśli tak to jak go rozwiązał?
Jako, że (w co aż nie dowierzam) allegro nie ogarnia tematu i oficjalnie wysłało mnie do Was co powinienem przekazać do allegro lub baselinker by rozwiązać problem?

Z poważaniem.

**Comment by MaciejFrackowiak** [comment]
Na forum GitHub wspieramy wyłącznie w zakresie wykorzystania zasobów API Allegro - kwestie rozliczeń przesyłek i wszelkich opłat są poza naszymi kompetencjami. Jednym słowem - właściwą komórką w tej materii jest [obsługa serwisu](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&subjectId=2d542135-a6d7-474c-a4a1-f96451c8bbc5).

**Comment by jata2** [comment]
Tak tak rozumiem aczkolwiek allegro rozkłada ręce.

Pytam więc Was jako programistów co mam przekazać allegro i baselinker by temat dalej ruszył?

Bo póki co to nikt: allegro DPD i baselinker nie przyznaje się do winy twierdząc, że wszystko jest ok.

**Comment by MaciejFrackowiak** [comment]
Zamówienia są rozpoznawane po adresie email przypisanym do konkretnego zamówienia - jednak jak wspomniałem - cały proces "kosztowy" odbywa się poza API, dlatego nie sposób nam tu udzielić bardziej dokładnych wskazówek, odpowiedzi.
