### ISSUE TITLE
Aktywacja konta ssstestowe

### ISSUE THREAD

**Issue by pzareba86** [allegro/allegro-api#6716]
Dzień dobry,
czy moge prosić o przyspieszenie aktywacji konta login ssstestowe. Mam 40%, ale zrobiłam juz  wypłate srodków i staneło na weryfikacji firmy.

![image](https://user-images.githubusercontent.com/98810516/218705026-451b9f67-2b52-48ae-ab27-b0d902cd58c8.png)

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.

**Comment by pzareba86** [comment]
Bardzo dziękuje 😊

***@***.***
Patrycja Zaręba
Sales Coordinator

#WeMakeATeam

email: ***@***.******@***.***>
fax: +48 12 3120 239
mobile: +48724750784
OTCF S.A.
75-412 Koszalin, ul. Monte Cassino 6, Poland

***@***.***
***@***.***
Sponsor of 8 Olympic Committees: Poland, Croatia, Lithuania, Latvia, Portugal, Greece, Slovakia and Serbia for the Olympic Winter Games Beijing 2022
Presenting Sponsor of the Four Hills Tournament 2018-2020, Global Partner of the Wings for Life World Run 2020
________________________________
OTCF S.A. z siedzibą w Krakowie przy ul. Saskiej 25C, 30-720 Kraków, wpisana do rejestru przedsiębiorców Krajowego Rejestru Sądowego prowadzonego przez Sąd Rejonowy dla Krakowa – Śródmieścia w Krakowie, XI Wydział Gospodarczy Krajowego Rejestru  Sądowego pod nr KRS: 0000555276, kapitał zakładowy w wysokości: 7 384 500,00 zł opłacony w całości, NIP: 9451978451, REGON: 356630870, o numerze rejestrowym BDO: 000005025. Ta wiadomość i jej treść mogą zawierać informacje poufne lub zastrzeżone, przeznaczone tylko dla adresata wiadomości. Takie informacje są objęte zakazem ich ujawniania. Wszelkie rozprowadzanie, dystrybucja lub powielanie niniejszej wiadomości lub innego rodzaju wykorzystanie przez osobę lub podmiot nie będący jego adresatem, jest zabronione. Jeżeli otrzymałeś tę wiadomość omyłkowo, proszę bezzwłocznie zawiadomić nadawcę wysyłając odpowiedź na niniejszą wiadomość i usunąć ją z poczty. Dziękuję.
OTCF S.A. with its registered seat in Kraków, ul. Saska 25C, 30-720 Kraków, Poland, registered in the entrepreneurs’ register kept by the District Court for Kraków - Śródmieście District in Krakow, 11th Commercial Department of the National Court Register, entry no KRS 0000555276, its share capital of PLN 7 384 500.00 paid in full, Tax ID No.(NIP) : 9451978451, Business Statistical Number (Regon): 356630870, BDO: 000005025. This e-mail and its content might contain confidential or privileged information intended solely for the use of the addressee. Such information are protected from disclosure. You are hereby notified that any dissemination, distribution or copying or other use of this e-mail by person or entity other than the intended recipient is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by replying to the message and deleting it from your computer. Thank you.

From: PrzemyslawLukanowski ***@***.***>
Sent: Tuesday, February 14, 2023 11:23 AM
To: allegro/allegro-api ***@***.***>
Cc: Patrycja Zaręba ***@***.***>; Author ***@***.***>
Subject: [Marketing Mail] Re: [allegro/allegro-api] Aktywacja konta ssstestowe (Issue #6716)

CAUTION: Ten email pochodzi spoza OTCF. Uważaj na zamieszczone załączniki oraz linki. Podejrzane wiadomości zgłoś na ***@***.******@***.***>

Aktywowałem Twoje konto.
