### ISSUE TITLE
Ustawianie statusu wysłania faktury poza allegro

### ISSUE THREAD

**Issue by JamesFordV3** [allegro/allegro-api#6717]
Dobry,

da się za pomocą api ustawić status wysłania faktury poza allegro? Chodzi mi o ten znaczek, żeby zmienił się na "pomarańczowo":
![obraz](https://user-images.githubusercontent.com/45076392/218705841-cc52bdbf-8763-45ef-b178-cf09364266a7.png)

```
    # TODO -> This method not working (allegro didnt support this?)
    def set_invoice_order_status(self, order_id: str, external_invoice: bool = True):
        """
        https://api.{environment}/order/checkout-forms/{id}/invoices
        """
        json_data = {
            "hasExternalInvoices": external_invoice,
        }
        endpoint = f"/order/checkout-forms/{order_id}/invoices"
        headers = {'Accept': 'application/vnd.allegro.public.v1+json',
                   'Content-Type': 'application/vnd.allegro.public.v1+json',
                   'Authorization': self.access_token}
        try:
            response = requests.put(self.environment + endpoint, headers=headers, json=json_data)
            print(response)
            print(response.headers)
            print(response.json())
```

W przeglądarce to wygląda prosto:
![obraz](https://user-images.githubusercontent.com/45076392/218707296-c86ce96d-25d6-480f-a66f-1559ae592bdf.png)

po kliknięciu "Zapisz" że "Faktura została wysłana poza allegro" leci prosty "put" z jedną zmienną w dictcie:
`{"hasExternalInvoices":true}`

nie da się tego ustawić po api? Byłoby fajnie, bo jest to fajny wizualny wskaźnik że faktura jest odhaczona. Dostaję odpowiedź jakoby nagłówek był był coś nie halo:

```
<Response [406]>, response.headers: {'trace-id': '...', 'content-type': 'application/json; charset=utf-8', 'content-length': '255', 'date': 'Tue, 14 Feb 2023...'}
<Response [406]>
{'trace-id': '...', 'content-type': 'application/json; charset=utf-8', 'content-length': '255', 'date': 'Tue, 14 Feb 2023 ....'}
{'errors': [{'code': 'NotAcceptableException', 'message': "Not acceptable representation requested. Please check 'Accept' request header", 'details': None, 'path': None, 'userMessage': 'The request contains incorrect data. Contact the author of the application.'}]}
```

**Comment by PrzemyslawLukanowski** [comment]
W ramach publicznego zasobu /order/checkout-forms/{order_id}/invoices obsługujemy wyłącznie metody [GET](https://developer.allegro.pl/documentation#operation/getOrderInvoicesDetails) i [POST](https://developer.allegro.pl/documentation#operation/addOrderInvoicesMetadata), dlatego dla PUT otrzymujesz błąd. Nie da się przez API zmienić wartości w tym polu.
