### ISSUE TITLE
[REST] Http 503 na zasobie after-sales-service-conditions od piątku ?

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#672]
after-sales-service-conditions

GET /after-sales-service-conditions/return-policies 503
GET /after-sales-service-conditions/implied-warranties 503 
GET /after-sales-service-conditions/warranties 503

na tych zasobach od piątku od popołudnia 503 ?

wwwfactory

**Comment by Uriziel01** [comment]
U nas wszystko OK, nie wiem jak w piątek ale zarówno wczoraj jak i dziś wszystko się poprawnie pobiera.

**Comment by wwwfactory** [comment]
doprecyzuję - na Sandboxie jest problem.

**Comment by wwwfactory** [comment]
ruszyło zamykamy
