### ISSUE TITLE
Metoda odpowiedzialna za przesyłanie plików do strony "Moja półka."

### ISSUE THREAD

**Issue by Bmitruk13** [allegro/allegro-api#6721]
Dzień dobry, 
nigdzie w dokumentacji nie mogę znaleźć informacji, jaka metoda odpowiada za przesłanie klientowi produktów cyfrowych do zakładki "Moja półka". 
Czy mogę prosić o wskazanie, która metoda jest za to odpowiedzialna?

**Comment by MaciejFrackowiak** [comment]
Zasoby do obsługi "Mojej półki" nie są dostępne w ramach publicznego API Allegro.
