### ISSUE TITLE
Autoryzacja aplikacji sandbox

### ISSUE THREAD

**Issue by vittekk** [allegro/allegro-api#6725]
**Błąd autoryzacji aplikacji po stornie Allegro na sandbox**

Błąd wewnątrz autoryzacji po stronie allegro:
Request
GET
`https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?api-key={...usnięte...}=&scope=allegro:api:profile:read+allegro:api:orders:read+allegro:api:orders:write+allegro:api:sale:offers:read&response_type=code&redirect_uri=https://konto-test.furgonetka.pl/allegroConnect&state={...usunięte...}
`

Response

> Nie możemy wyświetlić strony
> Numer błędu: 8ce5a0f8e1e47b8f

**Comment by MaciejFrackowiak** [comment]
Otrzymany komunikat sugeruje, że adres przekierowania, który podajesz w aplikacji nie jest zgodny z tym, który jest zarejestrowany na stronie [Zarządzanie aplikacjami Allegro Sandbox](https://apps.developer.allegro.pl.allegrosandbox.pl/). Adresy muszą być zgodne 1:1.

**Comment by vittekk** [comment]
> Otrzymany komunikat sugeruje, że adres przekierowania, który podajesz w aplikacji nie jest zgodny z tym, który jest zarejestrowany na stronie [Zarządzanie aplikacjami Allegro Sandbox](https://apps.developer.allegro.pl.allegrosandbox.pl/). Adresy muszą być zgodne 1:1.

Dziękuję za wskazówkę. Zweryfikuję i wrócę z feedbackiem.

**Comment by vittekk** [comment]
@MaciejFrackowiak  Niestety, ale próba zmiany kończy się to błędem "Nie udało się zarejestrować lub zaktualizować aplikacji. Spróbuj ponownie.".


**Request:**

_PUT https://edge.allegro.pl.allegrosandbox.pl/developer/my-applications/8d2aecc2-1d88-4ca5-9e00-157674909172
{
    "name": null,
    "description": "Furgonetka TEST",
    "applicationType": "WEB",
    "redirectUris": [
        "https://konto-test.furgonetka.pl/allegroConnect"
    ],
    "publicScopes": [
        "allegro:api:ads",
        "allegro:api:bids",
        "allegro:api:billing:read",
        "allegro:api:campaigns",
        "allegro:api:disputes",
        "allegro:api:messaging",
        "allegro:api:orders:read",
        "allegro:api:orders:write",
        "allegro:api:payments:read",
        "allegro:api:payments:write",
        "allegro:api:profile:read",
        "allegro:api:profile:write",
        "allegro:api:ratings",
        "allegro:api:sale:offers:read",
        "allegro:api:sale:offers:write",
        "allegro:api:sale:settings:read",
        "allegro:api:sale:settings:write"
    ],
    "regulationsAccepted": "true"
    }_
 
 **Response (500)**
    
_[
    {
        "code": "ERROR",
        "message": "An error has occurred",
        "details": null,
        "path": "/developer/my-applications/8d2aecc2-1d88-4ca5-9e00-157674909172",
        "userMessage": null
    }
]_

**Comment by MaciejFrackowiak** [comment]
Zmiany w konfiguracji aplikacji wykonaj poprzez [WWW](https://apps.developer.allegro.pl.allegrosandbox.pl/).

**Comment by vittekk** [comment]
Doprecyzuję, że używaliśmy interfejsu www. 
![image](https://user-images.githubusercontent.com/46939236/218990553-7af979eb-e75f-420c-9216-175558d3594d.png)
RQ miał posłużyć jako uszczegółowienie.

**Comment by vittekk** [comment]
@MaciejFrackowiak dzięki za wsparcie. Problem został rozwiązany.
