### ISSUE TITLE
Liczba sprzedanych na aukcji.

### ISSUE THREAD

**Issue by kacperKarman** [allegro/allegro-api#6727]
Czy istnieje zasób który umożliwiłby pobranie dokładnej liczby sprzedanych na aukcji która nie należy do mnie? Obecnie korzystam z listy dostępnej pod GET offers/listing i pól popularity oraz popularityRange, natomiast potrzebowałbym dokładne wartości a nie tylko przedział w którym znajduje się sprzedaż. Czy jest możliwe dostanie się do tych danych poprzez api?

**Comment by hahyes** [comment]
Nie. Poza /offers/listing nie ma innej możliwości otrzymania jakichkolwiek danych o aukcjach innych użytkowników poprzez REST API Allegro.

**Comment by kacperKarman** [comment]
Ok rozumiem, dziękuję za szybką odpowiedź!
