### ISSUE TITLE
Witaj, chcę kupić oprogramowanie do automatycznej odpowiedzi na wiadomości obsługi klienta i dyskusji. Gdzie to jest?

### ISSUE THREAD

**Issue by qq16632785** [allegro/allegro-api#6728]
Witaj, chcę kupić oprogramowanie do automatycznej odpowiedzi na wiadomości obsługi klienta i dyskusji. Gdzie to jest?

**Comment by PrzemyslawLukanowski** [comment]
Jako Allegro nie wskazujemy żadnego konkretnego oprogramowania, jego wybór pozostaje w pełni w Twojej gestii.
