### ISSUE TITLE
Pobranie wielkości sprzedaży

### ISSUE THREAD

**Issue by WladzCoel** [allegro/allegro-api#6729]
Dzień dobry, czy jest możliwość pobrania za pomocą REST API wielkości sprzedaży wszystkich sprzedających łącznie dla produktów z Mojego Asortymentu?

**Comment by PrzemyslawLukanowski** [comment]
Zwracamy informację o sprzedaży wyłącznie z ostatnich 30 dni - dane znajdziesz w odpowiedzi zasobu [GET /sale/offers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET) w polu `stock.sold` przy danej ofercie.
