### ISSUE TITLE
REST API  lista ofert - data wystawienia oferty

### ISSUE THREAD

**Issue by andrzejg07** [allegro/allegro-api#673]
Czy jest możliwość dodania do listy ofert pola - data wystawienia oferty lub data aktualizacji oferty.

**Comment by PawelTaberski** [comment]
A do czego chciałbyś wykorzystywać takie informacje i w jakiej metodzie chciałbyś, aby były zwracane.

**Comment by andrzejg07** [comment]
pytanie dotyczy metody GET/offers/listing - która aktualnie nie zwraca info o dacie utworzenia oferty.
Pobranie daty utworzenia wymaga dodatkowo wywołania metody GET/sale/offers/{id}
datę utworzenia oferty wykorzystujemy do weryfikacji zgodności zapisów ofert po stronie naszego api

**Comment by PawelTaberski** [comment]
Przekazałem Twoją sugestię do odpowiedniego zespołu. Jeśli zdecydujemy się na wdrożenie takiego rozwiązania, to poinformujemy o tym.
