### ISSUE TITLE
Identyfikatory wysyłek - czy są takie same dla wszystkich kont?

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#6731]
Dzień dobry,

przykładowa wysyłka "Allegro Odbiór w Punkcie UPS" w "Allegro wysyłam" ma identyfikator "0d69a62b-7a66-4bd1-9134-49dea68dccc8"  - jak rozumiem to nowy format identyfikatora wysyłki, stare identyfikatory numeryczne przestają obowiązywać od 20 lutego.

Zauważyłem, że stare identyfikatory dla tego samego rodzaju wysyłki są inne dla każdego z kont Allegro.

Pytanie: czy nowe identyfikatory, jak ten w/w "0d69a62b-7a66-4bd1-9134-49dea68dccc8" będą takie same dla każdego konta allegro? 

Z moich testów wynika, że tak, ale chciałbym mieć pewność, proszę o odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Szczegóły znajdziesz w [naszym newsie](https://developer.allegro.pl/news/wysylam-z-allegro-zmienimy-identyfikatory-uslug-dostawy-BvMdq20KEIm). W skrócie - tak, dla umowy Allegro będą takie same dla wszystkich sprzedawców; dla umowy własnej identyfikatory posiadają dodatkowy przypisek #id_umowy_wlasnej, który oczywiście będzie się różnić w zależności od sprzedawcy.
