### ISSUE TITLE
Czy jest jakieś demo lub przykład?

### ISSUE THREAD

**Issue by qq16632785** [allegro/allegro-api#6732]
Czy jest jakieś demo lub przykład?

**Comment by MaciejFrackowiak** [comment]
Przykłady wywołań i odpowiedzi znajdziesz w naszym pliku [swagger.yaml](https://developer.allegro.pl/swagger.yaml). Również w poradnikach dostępnych na [portalu developerskim](https://developer.allegro.pl/) znajdziesz przykładowe zastosowanie zasobów.
