### ISSUE TITLE
Invalid refresh token

### ISSUE THREAD

**Issue by huangzec** [allegro/allegro-api#6733]
The refresh token expires within the validity period but has not been re-authorized. What is the reason?

For example:

{
    "error": "invalid_grant",
    "error_description": "Invalid refresh token: ss.xxx.LtjtP-lK2VdP-ss-sss-ss-ss-BXFSkDS7ZPaXmmZj8-ss-ff"
}

**Comment by huangzec** [comment]
I have sent the details by email

**Comment by MaciejFrackowiak** [comment]
Yes, we received your email and I found in our logs:
1) 2023-02-15 04:41:10 - you received a new pair of access and refresh tokens;
2) 2023-02-15 15:21:14 - you used a refresh token from step 1;
3) 2023-02-15 15:21:14 - you received a new pair of access and refresh tokens.

It means that the refresh token from step 1 is no longer valid. You should use a refresh token from step 3 instead - please, check [our tutorial ](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#extending-token-validity)about extending token validity.

**Comment by huangzec** [comment]
okay ths
