### ISSUE TITLE
Sprawdzenie czy oferta ma przypisany produkt do aukcji.

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#6734]
Jak mogę sprawdzić czy dana oferta jest przypisana do produktu? Chodzi mi o sprawdzenie które aukcje z konta allegro zostały wystawione bez produktyzacji (czyli podejrzewam, że większość sprzed 1 sierpnia 2022)

**Comment by PrzemyslawLukanowski** [comment]
Zrobisz to za pomocą [GET /sale/offers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET) i użyciem parametru `product.id.empty=true`
