### ISSUE TITLE
Konto zwykłe a dostęp do API

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6737]
Czy posiadając konto zwykłe (niefirmowe), istnieje możliwość zarejestrowania aplikacji API oraz otrzymanie dostępu do GET /offers/listing (chodzi o zweryfikowanie aplikacji)

**Comment by pietras125** [comment]
Dołączam się do pytania

**Comment by PrzemyslawLukanowski** [comment]
Tak, posiadając konto zwykłe możecie zarejestrować aplikację oraz wystąpić o weryfikację aplikacji.

**Comment by pietras125** [comment]
> Tak, posiadając konto zwykłe możecie zarejestrować aplikację oraz wystąpić o weryfikację aplikacji.

Co może nie działać? Wykonuję kod python z poradnika https://developer.allegro.pl/tutorials/jak-zaczac-prace-z-rest-api-4RAvV2bgwtj#python i w odpowiedzi otrzymuję:
`{'error': 'Unauthorized', 'error_description': 'Unauthorized'}`

**Comment by PrzemyslawLukanowski** [comment]
Podczas jakiego dokładnie zapytania otrzymujesz ten komunikat? Czy możesz podać trace-id swojego wywołania?

**Comment by pietras125** [comment]
Tutaj nie wykonuję żadnego zapytania, chcę tylko uzyskać token, kod programu:
```
import requests
import json

CLIENT_ID = "mój id odczytany z panelu developera"          # wprowadź Client_ID aplikacji
CLIENT_SECRET = "mój client secret odczytany z panelu developera"      # wprowadź Client_Secret aplikacji
TOKEN_URL = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token"


def get_access_token():
    try:
        data = {'grant_type': 'client_credentials'}
        access_token_response = requests.post(TOKEN_URL, data=data, verify=False,
                                              allow_redirects=False, auth=(CLIENT_ID, CLIENT_SECRET))
        tokens = json.loads(access_token_response.text)
        print(tokens)
        access_token = tokens['access_token']
        return access_token
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)


def main():
    access_token = get_access_token()
    print("access token = " + access_token)

if __name__ == "__main__":
    main()
```

Bez tokena nie mogę wykonać żadnego odpytania. Nie wiem jak znaleźć trace-id.

**Comment by PrzemyslawLukanowski** [comment]
Czy nie korzystasz przypadkiem z clientId i clientSecret zarejestrowanego na produkcji, a zapytanie robisz do środowiska testowego (https://allegro.pl.allegrosandbox.pl/auth/oauth/token)? Chciałbym jeszcze dodać, że w przypadku tokena wygenerowanego w ramach autoryzacji client_credentials będziesz mieć dostęp tylko do publicznych danych, bez kontekstu użytkownika, np. do zbioru kategorii. Jeśli chcesz korzystać z zasobów, które w dokumentacji oznaczyliśmy jako bearer-token-for-user, musisz skorzystać z [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow.
