### ISSUE TITLE
/sale/offer-price-change-commands/ - ulepszenie aby można było indywidualnie określać zmianę ceny dla oferty

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#6739]
Dzień dobry,

w tej chwili, wg. dokumentacji mogę przeprowadzić zmianę ceny na wielu ofertach w ramach /sale/offer-price-change-commands/

Jest tylko pewien problem: otóż **wszystkie oferty w ramach tej paczki zmian muszą mieć tą samą zmianę ceny**.

Mamy tam obiekt "modification" który określa zmianę ceny a potem listę ofert. Nie da się indywidualnie dla oferty określić zmiany ceny, wszystkie mają taką samą zmianę ceny wg. obiektu "modyfication".

Czyli jeżeli mam oferty X, Y i Z gdzie w X chcemy zmienić cenę na 20 zł, w Y na 25 zł, a w X na 30 zł, to nie da się tego przeprowadzić jednym wywołaniem/requestem API, tylko trzeba zrobić 3 osobne wywołania.

**Prośba o to, żeby można było tutaj ustalać dla każdej oferty indywidualnie zmianę ceny**, bo tak jak jest to teraz zrobione, to jest to trochę bezużyteczne, ponieważ rzadko się zdarza, aby oferty miały identyczną zmianę ceny. 

Co prawda są u nas produkty które są powiązane z kilkoma różnymi ofertami Allegro, ale nawet wtedy się zdarza, że te oferty mają różne ceny.

Często mamy w kolejce tysiące zmian cen na raz np. w wyniku wahania kursów walut, i przez taką konstrukcję jak jest teraz, trwa to długo, a taka zmiana znacznie by to przyspieszyła, bo **moglibyśmy całą kolejkę włączyć do jednego wywołania API - lub podzielić na kilka, bo z tego co wiem limit jest 1000 ofert na jedno wywołanie**.

Tak samo dla Was ograniczenie wywołań API byłoby korzystne.

Proszę o rozpatrzenie tego pomysłu.

**Comment by PrzemyslawLukanowski** [comment]
Otrzymaliśmy już taką taką sugestię w wątku [#6035](https://github.com/allegro/allegro-api/discussions/6035) w zakładce Discussions, w której przyjmujemy sugestie dotyczące rozwoju API. Na tę chwilę nie planujemy takiej zmiany, zachęcam Cię jednak, aby na nią zagłosować. Więcej o zakładce Discussions przeczytasz [tutaj](https://github.com/allegro/allegro-api/issues/4337).

**Comment by tztztztz** [comment]
Bardzo szkoda, bo przecież dla Was tak samo byłoby to pozytywna zmiana ograniczająca wywołania HTTP. Trudno. 

Na ten moment nie zamykam tego zgłoszenia, bo sugestia o której piszesz jest w dyskusją, a tutaj stworzyłem zgłoszenie.
