### ISSUE TITLE
Rest API token

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#674]
Dobrze rozumiem, że mając otrzymany przez OAuth token REST API, można z jego pomocą wysyłać requesty z dowolnego IP? Kombinuję jak przestawić działającą u klienta desktopową aplikację webAPI na nowe API.

**Comment by PawelTaberski** [comment]
Zgadza się adres IP nie ma znaczenia jeśli masz access_token. Więcej na temat autoryzacji znajdziesz[ tutaj](https://developer.allegro.pl/auth/).

**Comment by PawelTaberski** [comment]
Aby zidentyfikować użytkownika po jego Tokenie wystarczy rozkodować token przy pomocy np. https://jwt.io/

**Comment by FromAnyHole** [comment]
@PawelTaberski - a kto zapomniał o tym napisać w dokumentacji ??

**Comment by FromAnyHole** [comment]
@PawelTaberski - odsyłacie jawnie różne zbędne dane:
,"expires_in":43199,"scope":"allegro_api","jti":"fa39dc64-f855 ... "
gdzie pole identyfikatora JWT w formacie UUID opisujecie jako niewykorzystane, więc komplementarna odpowiedź mogła by zwyczajnie zawierać identyfikator użytkownika, a jak ktoś bardzo by chciał, to za każdym razem może sobie dekodować nowy "access/refresh_token", zwyczajnie szkoda prądu...

**Comment by PawelTaberski** [comment]
Nie zapomnieliśmy taką informacje znajdziesz tutaj: https://developer.allegro.pl/auth/. OAuth2 jest pewnym standardem dlatego znajduje się tam taki zestaw informacji.

**Comment by FromAnyHole** [comment]
@PawelTaberski - a w Brukseli standardem jest płacenie w Euro, ale u nas na szczęście NIE.
