### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by wmierzej** [allegro/allegro-api#6742]
Dzień dobry
Założyłem konto na sandboxie (nick: wmierzej) lecz nie mogę się zalogować, jest informacja, że błędny login lub hasło. 
Proszę o pomoc oraz aktywacje konta

Z poważaniem
WM

**Comment by MaciejFrackowiak** [comment]
Niestety, ale konta o podanym loginie nie mamy w bazie użytkowników. Czy potwierdziłeś rejestrację konta klikając w link z naszego powiadomienia?

**Comment by wmierzej** [comment]
Niestety nie dostałem żadnej wiadomości

**Comment by MaciejFrackowiak** [comment]
Proszę podaj swój adres email, wówczas spojrzę na status wiadomości.

**Comment by wmierzej** [comment]
w_mierzej@o2.pl

**Comment by MaciejFrackowiak** [comment]
Jak widzę ostatnią wiadomość wysłaliśmy do Ciebie 2023/02/17 00:16:13.
Wiadomości z Sandbox zawierają załącznik w formacie *.eml - część skrzynek pocztowych uznaje to za spam - sprawdź proszę katalog ze spamem na swojej poczcie.

**Comment by wmierzej** [comment]
Faktycznie było w spamie, dziękuje. Czy musze przejść cały proces weryfikacji konta wraz z dodawaniem dokumentów i weryfikacją konta bankowego?

**Comment by MaciejFrackowiak** [comment]
Tak, jest to niezbędne - dodaj proszę dowolne pliki, a przelew zrealizujesz z wykorzystaniem symulatora płatności.

**Comment by wmierzej** [comment]
Ok, doszedłem do etapu "Weryfikujemy dane Twojej firmy" - czyli rozumiem, że teraz pozostaje czekać?

**Comment by MaciejFrackowiak** [comment]
Zweryfikowałem już Twoje konto.
