### ISSUE TITLE
Jak zdobyć token?

### ISSUE THREAD

**Issue by qq16632785** [allegro/allegro-api#6743]
Jak zdobyć token?

Ten link wymaga zalogowania, ale nie mogę się zalogować na konto allegro

https://allegro.pl/auth/oauth/token

**Comment by MaciejFrackowiak** [comment]
Aby uzyskać token użytkownik musi dać zgodę na wykonywanie operacji w jego imieniu. Następnie musisz zaimplementować u siebie obsługę autoryzacji code lub device flow. Cały proces autoryzacji - uzyskanie tokena, wywołania zasobów oraz przedłużenie ważności tokena znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR).

**Comment by qq16632785** [comment]
Czy możesz wysłać mi link do uzyskania zgody na token?

**Comment by MaciejFrackowiak** [comment]
Przygotuj odpowiedni odnośnik wg wzorca: `https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=a21...6be&redirect_uri=http://exemplary.redirect.uri`- opisaliśmy to w kroku [Autoryzacja użytkownika](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#autoryzacja-uzytkownika) w poradniku.
