### ISSUE TITLE
Create a refund application error

### ISSUE THREAD

**Issue by VEVOR** [allegro/allegro-api#6744]
request：
curl --location --request POST 'https://api.allegro.pl/order/refund-claims' \
--header 'Authorization: Bearer xxx' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--data-raw '{
    "lineItem": {
        "id": "846f2cc0-aba7-11ed-a87d-df92aab8e825"
    },
    "quantity": 1
}'

response：
{
    "errors": [
        {
            "code": "CommissionAmountException",
            "message": "Invalid commission amount of line item id 846f2cc0-aba7-11ed-a87d-df92aab8e825.",
            "details": null,
            "path": null,
            "userMessage": "You cannot apply for zero sales commission."
        }
    ]
}
The platform displays commission, please see the legend
![image](https://user-images.githubusercontent.com/99702013/219543212-4cb406b5-a71c-4940-871d-ee2355615244.png)

**Comment by VEVOR** [comment]
Please see what the problem is and how to solve it

**Comment by MaciejFrackowiak** [comment]
You received an error because we returned your money as a part of the reconciliation in the Allegro Prices Program. Please, filter your billing with order.id and you will see all the operations connected to that order.

**Comment by VEVOR** [comment]
Which api is used to filter bills. This error indicates that you cannot apply for commission or you need to do other processing to apply for commission.

**Comment by MaciejFrackowiak** [comment]
Please, check [the rules of the Allegro Prices](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/poznaj-allegro-ceny-na-czym-polega-program-wsparcia-dla-sprzedajacych-MR45D5zADiy) program to better understand how it works. To check your billing you can use [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries).
