### ISSUE TITLE
Pobieranie obcych przedmiotów

### ISSUE THREAD

**Issue by faran22** [allegro/allegro-api#6745]
Dzień dobry, czy można przez api pobrać nie swoje przedmioty ?

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma takiej możliwości. Przy wykorzystaniu [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) pobierzesz wyłącznie swoje oferty.
