### ISSUE TITLE
Odblokowanie sprzedaży - Sandbox

### ISSUE THREAD

**Issue by NM97** [allegro/allegro-api#6746]
Podczas próby wystawienia przedmiotu pojawia się komunikat:
 
Wystąpił błąd - Nie masz wymaganych uprawnień, aby wystawić ofertę (sprzedaż zablokowana). Ureguluj zaległości w "Rozliczenia z Allegro";

Proszę o odblokowanie. 
login:pomoc.binsoft@gmail.com

**Comment by MaciejFrackowiak** [comment]
Proszę ureguluj swoje zobowiązania poprzez zakładkę [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) - znajdziesz tam symulator płatności.

**Comment by ruzampl** [comment]
Mam podobny problem, ale uregulowałem należności, ba.. mam nawet nadpłatę 80 200zł :)
Uzupełniłem też dodatkowe dane, które były wymagane przy koncie biznesowym, dane do wypłaty itp.
Niestety ciągle mam komunikat o zablokowanej sprzedaży. Proszę o weryfikację, login: ruzampl

**Comment by MaciejFrackowiak** [comment]
@ruzampl Konto odblokowane.
