### ISSUE TITLE
Przestarzała (depraciated) metoda /sale/offers/{offerId} - jak długo będzie działać? Zamiennik?

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#6747]
Dzień dobry,

widzę że w API metoda /sale/offers/{offerId} została oznaczone jako przestarzała.

Pytania:

- jak długo będzie jeszcze działać?
- czy będzie jakiś zamiennik/sposób który dokładnie w takim formacie będzie zwracał dane przy użyciu innej metody?

Problem polega na tym, że **nowa metoda /sale/product-offers/{offerId} zwraca dane oferty w innym formacie który powoduje problem**, kiedy w naszym systemie chcemy tworzyć nową ofertę w oparciu o jakąś istniejącą która jest "szablonem" i na podstawie jej danych tworzymy nową ofertę.

Teraz tworzymy nową ofertę z danych oferty pobranych metodą /sale/offers/{offerId}, wcześniej usuwamy pola id, createdAt, updatedAt, validation, images i nowa oferta tworzy się bez problemu.

To nam ułatwia szybsze tworzenie ofert.

Niestety tworzenie struktury nowej oferty z danych pobranych nową metodą /sale/product-offers/{offerId} powoduje błędy np.: 

**Value already exists: value='Nowy', parameter.id='11323'** 

Dlatego ważne jest dla nas aby wiedzieć jak długo jeszcze stary sposób będzie działał (najlepiej zawsze), albo czy jest jakiś sposób żeby w nowej metodzie pobierać dane w starym formacie.

**Comment by PrzemyslawLukanowski** [comment]
Zasób będzie działać do końca 2023, szczegóły znajdziesz w [naszym komunikacie](https://developer.allegro.pl/news/na-poczatku-2024-roku-wylaczymy-zasoby-sale-offers-sluzace-do-tworzenia-i-edycji-ofert-BvqK3XOaEcW). Dane oferty możecie pobrać za pomocą [GET /sale/product-offers/{offerId} ](https://developer.allegro.pl/documentation#operation/editProductOffers) i następnie użyć ich jako szablonu, wystawiając ofertę za pomocą [POST /sale/product-offers ](https://developer.allegro.pl/documentation#operation/createProductOffers). Błędy w takim przypadku nie powinny zostać zwrócone.

**Comment by tomylee0** [comment]
Tylko, że jeśli oferta ma tylko swoje zdjęcie to wciąż po odczytaniu oferty przez GET /sale/product-offers i wykorzystaniu odpowiedzi do zbudowania POST /sale/product-offers otrzymujemy nową ofertę ale z dwoma zdjęciami: zdjęciem z kopiowanej oferty oraz ze zdjęciem produktowym: #6547 #6339

Chyba, że zaszły w tym temacie jakieś zmiany?

**Comment by PrzemyslawLukanowski** [comment]
W tym temacie nie zaszły zmiany - mimo wszystko, pobraną strukturę nadal można wykorzystać jako szablon, odpowiednio ją modyfikując.
