### ISSUE TITLE
Pobieranie etykiet kurierskich przez API

### ISSUE THREAD

**Issue by robsonek** [allegro/allegro-api#6748]
Czy jest możliwość pobrać ParcelId do wcześniej wygenerowanych paczek wysyłam z allegro, tak aby móc pobrać ponownie etykietę. Lub jakoś inaczej pobrać etykietę wygenerowaną wcześniej, bez zapisanych numerów parcelId.

Bądź drugi przypadek, pobrać etykietę przez API, dla paczek wygenerowanych przez stronę allegro.pl

**Comment by JamesFordV3** [comment]
ostatnio się nad tym samym głowiłem - z tego co grzebałem w dokumentacji do API to nie znalazłem takiej opcji

wystarczy że przepadnie Ci `{commandId}` to jak ParcelId nie zapisałeś to kaplica


Natomiast - w szczegółach zamówienia w przeglądarce:
https://allegro.pl/moje-allegro/sprzedaz/zamowienia/{id}
widnieje wygenerowany **packageId (to to samo co ParcelId)** pod przyciskiem "ZAMÓW PODJAZD" (przynajmniej dla DPD - nie wiem jak to wygląda dla innych dostawców) jak klikniesz ten przycisk to z adresu url możesz sobie skopiować ParcelId i po nim pobrać etykietę (uwaga! - to chyba działa tak długo jak przesyła jeszcze nie została wysłana, ale tego nie jestem pewien)
![obraz](https://user-images.githubusercontent.com/45076392/219903631-ce55e7bd-7065-44d3-9f3e-5f36971aa828.png)


Mając już packageId możesz już pobrać etykietę po API, natomaist jeżeli chcesz to zrobić z przeglądarki to musisz wkleić w link:
https://allegro.pl/moje-allegro/sprzedaz/wysylam/nadaj-paczke/status?packageId={ParcelId}
i tam sobie możesz pobrać ponownie - nic innego nie znalazłem.

Kiedyś również działał widoczny na screenie przycisk "DRUKUJ ETYKIETĘ" - który to właśnie pobierał etykietę, ale jakieś 3-4msc temu po jakiejś tam aktualizacji allegro nie działa (**choć powinien**) to chyba jakiś bug. No ale już nie działa (przynajmniej dla DPD). U mnie po jego kliknięciu totalnie nic się nie dzieje i to nie kwestia przeglądarki bo sprawdzałem na innych.


Tak czy owak lipa że nie da się pobrać parcelId przypisanych do danego orderId, według mnie to powinno wypluwać przy zapytaniu o szczegóły zamówienia bo to ważna informacja.

**Comment by robsonek** [comment]
@JamesFordV3 Dzięki za odpowiedź! Dokładnie to samo rozwiązanie znalazłem, żeby pobierać ParcelId ze strony, ale cieżko to będzie podłączyć pod API. 

"DRUKUJ ETYKIETĘ" u mnie też nie działa.

Pytanie do Allegro. Może pomyślicie o dodaniu ParcelId do np. /order/checkout-forms?

**Comment by MaciejFrackowiak** [comment]
@robsonek Podobna [sugestia](https://github.com/allegro/allegro-api/discussions/5436) już pojawiła się - proszę oddaj swój głos na nią.
