### ISSUE TITLE
How to get commission

### ISSUE THREAD

**Issue by VEVOR** [allegro/allegro-api#6749]
Call/billing/billing entries to query the commission. You can directly find out whether you need to call/order/refund claims first

**Comment by Lukasz-Zurek** [comment]
I can confirm that you can always use /billing/billing-entries?type.id=SUC where you can find out if we have charged sales commission for a specific offer and order.

If the transaction has not been finalized or if the buyer has withdrawn from the purchase contract (please check the [Customer returns guide](https://developer.allegro.pl/tutorials/process-orders-PgPMlWDr8Cv#customer-returns)), then you can create a sale commission refund application via [POST /order/refund-claims](https://developer.allegro.pl/documentation/#operation/createRefundApplication) and for this request you will need:

- **lineItem.id** (You can retrieve it via [GET /order/checkout-forms/{checkoutFormId}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET)),
- **quantity** (please make sure you provide a valid number of items for which you want to receive sale commission refund).

We have described the sale commission refunds in [our guide](https://developer.allegro.pl/tutorials/process-orders-PgPMlWDr8Cv#sale-commission-refunds) as well.
