### ISSUE TITLE
Indeksowanie opisu oferty vs. wyszukiwarka allegro

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#675]
W swoich opisach stosujemy kody produktów + unikatowy kod CE42TG
Wystawiliśmy dwie oferty, których nie wyświetla nam wyszukiwarka allegro:
https://allegro.pl/listing?string=53517%20ce42tg&description=1&order=m&bmatch=baseline-cl-uni-1-4-0806
oferta: https://allegro.pl/waga-kuchenna-slim-elektroniczna-led-5kg-1g-i7588405916.html

oraz 
https://allegro.pl/listing?string=53516%20ce42tg&description=1&order=m&bmatch=baseline-cl-uni-1-3-0806
https://allegro.pl/cyfrowa-waga-kuchenna-srebrna-inox-lcd-minutnik-i7588558344.html

**Comment by PawelTaberski** [comment]
Tutaj zajmujemy się problemami związanymi z Allegro API. Problemy z wyszukiwarką zgłoś proszę przez formularz kontaktowy [tutaj](https://allegro.pl/pomoc).
