### ISSUE TITLE
Historia zmian dla danych aukcji Allegro

### ISSUE THREAD

**Issue by Filtrytotu** [allegro/allegro-api#6750]
Dzień dobry, czy jest możliwość pobrania historii zmian takich jak np. cena,ilość dla danych aukcji?

**Comment by Lukasz-Zurek** [comment]
Udostępniamy dziennik zdarzeń w ofertach czyli [GET /sale/offer-events](https://developer.allegro.pl/documentation/#operation/getOfferEvents) za pomocą którego uzyskasz informacje z ostatnich 24 godzin, m.in. o zmianie:

- w ofercie ("type": "OFFER_CHANGED");
- liczby sztuk w ofercie - zwracany również po zakupie ("type": "OFFER_STOCK_CHANGED");
- ceny w ofercie ("type": "OFFER_PRICE_CHANGED");

W przypadku tego zasobu zwrócimy również inne dane, o których przeczytasz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#dziennik-zdarzen-w-ofertach-sprzedawcy).
