### ISSUE TITLE
Długi czas odpowiedzi na zasobie sale/products

### ISSUE THREAD

**Issue by ecat-rg** [allegro/allegro-api#6751]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Zwykle odpytanie endpointu sale/products trwa kilkaset milisekund. Co nieokreślony czas API allegro zwraca odpowiedź dopiero po około 20 sekundach i taki stan potrafi się utrzymywać przez wiele requestów z naszej aplikacji z rzędu. Czy serwery allegro nie wydalają czy możemy coś zoptymalizować po naszej stronie? 

Przykładowe odpytanie dotyczy URL:
https://api.allegro.pl/sale/products?phrase=5900050060281
(response  22 sekundy, po chwili w 110 ms)

**Comment by ecat-rg** [comment]
Po dalszej analizie zauważyłem, że zależy to od konta, z którego odpytujemy. Np. odpytanie
https://api.allegro.pl/sale/products?phrase=5907785541559 trwa regularnie 24 sekundy.

Jak mogę przekazać access token konta?

**Comment by Lukasz-Zurek** [comment]
Możliwe, że zadziałał tutaj nasz dodatkowy mechanizm tzw. Leaky Bucket. Jeżeli przekraczasz dozwoloną liczbę wywołań na minutę (RPM), wydłużamy czas odpowiedzi. Opisujemy to [tutaj](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#ograniczenie-liczby-zapytan-limity).

Jeśli jednak nie doszło tutaj do tego typu sytuacji i odpytując zasób - mieścisz się w naszym limicie, skontaktuj się z nami poprzez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), przesyłając również problematyczne trace-id. W zgłoszeniu dopisz GitHub #6751.

**Comment by Lukasz-Zurek** [comment]
@ecat-rg Dziękuję za wiadomość ze szczegółowymi danymi. Zweryfikowaliśmy to po naszej stronie i okazuje się, że zadziałał tutaj jednak dodatkowy mechanizm tzw. Leaky Bucket. Musisz rozłożyć ruch, aby nie wpadać w nasz dodatkowy limit. Zachęcam również do cache'owania pobieranych danych.
