### ISSUE TITLE
WZA - umowa własna id metody wysyłki

### ISSUE THREAD

**Issue by bartekc7** [allegro/allegro-api#6752]
Dzień dobry,
Jaki servivceId należy podawać w przypadku umów własnych?
Metoda GET https://api.{environment}/parcel-management/delivery-services  zwraca dwu-członowy id z separatorem # 
"id": "059c0d58-6cdb-4955-ab79-9031518f80f3#ee203931-e9b1-495a-9587-8c6d06100d72",
"service": "GLS",
"name": "Kurier GLS (GLS)",
"owner": "CLIENT",

Czy przy tworzeniu paczki powinno się podawać całość, id do separatora czy za separatorem?

Poniżej 3 przypadki i 3 różne błędy.

1. "serviceId" : "ee203931-e9b1-495a-9587-8c6d06100d72"

{
  "id": "95d23af0-bfa1-49cd-aaa9-794bd1ab6ef0",
  "parcelId": null,
  "status": "ERROR",
  "errors": [
    {
      "code": "DELIVERY_METHOD_NOT_FOUND",
      "message": "Requested delivery method was not found",
      "details": "Requested delivery method was not found",
      "path": "deliveryMethodId",
      "userMessage": "Requested delivery method was not found"
    }
  ]
}

2. 059c0d58-6cdb-4955-ab79-9031518f80f3

{
  "id": "abff282c-7962-4ff4-8bdb-d3363199fdbf",
  "parcelId": null,
  "status": "ERROR",
  "errors": [
    {
      "code": "INVALID_CREDENTIALS_ERROR",
      "message": "Cant extract serviceId from credentials header",
      "details": null,
      "path": "x-authorization",
      "userMessage": "Nie można pobać serwisu"
    }
  ]
}

3.  "serviceId": "059c0d58-6cdb-4955-ab79-9031518f80f3#ee203931-e9b1-495a-9587-8c6d06100d72"

{
  "id": "17e3586c-6e12-4746-bfd3-dd0c0769dae6",
  "parcelId": null,
  "status": "ERROR",
  "errors": [
    {
      "code": "ERROR",
      "message": "Processing error",
      "details": null,
      "path": null,
      "userMessage": "error.common.processing"
    }
  ]
}

**Comment by Lukasz-Zurek** [comment]
@bartekc7 Temat ten przekazałem dalej do weryfikacji. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
Jeśli chodzi o "serviceId", w tym konkretnym przypadku jest to umowa własna, więc identyfikator powinien zawierać id umowy własnej, czyli przekazywane "serviceId": "059c0d58-6cdb-4955-ab79-9031518f80f3#ee203931-e9b1-495a-9587-8c6d06100d72 jest prawidłowe. Przyczyną problemu jest tutaj przekroczona długość adresu e-mail w polu **receiver.email.** W swoim API firma GLS ogranicza niestety długość adresu mailowego do 40 znaków. Z uwagi na to, że może to być problematyczne dla kolejnych przesyłek, wyjaśniamy jeszcze tę sprawę po naszej stronie.

**Comment by bartekc7** [comment]
Dziękuje za odpowiedź. W takim razie czekam na informację jak się uda coś ustalić.

**Comment by bartekc7** [comment]
Dzień dobry,
Czy coś w tej sprawie wiadomo?

**Comment by Lukasz-Zurek** [comment]
@bartekc7 Nie, ustalenia w tym zakresie mogą potrwać z uwagi na to, że jako Serwis nie jesteśmy jedyną komórką odpowiedzialną za ten proces. Jest tutaj jeszcze operator, z którym współpracujemy w ramach "Wysyłam z Allegro". Proszę o cierpliwość.

Jak tylko uzyskam jakiekolwiek szczegółowe informacje dotyczące ewentualnych zmian - poinformuję Cię w tym wątku.

**Comment by bartekc7** [comment]
Ok, dziękuje za odpowiedź. W takim razie czekamy dalej.

**Comment by Lukasz-Zurek** [comment]
@bartekc7 Sprawa dotycząca limitu pola **receiver.email** zależna tutaj będzie w pierwszej kolejności od prac po stronie kuriera GLS. Otrzymaliśmy zapewnienie, że temat będzie po ich stronie realizowany.
