### ISSUE TITLE
Nie działa pobranie token dla aplikacji.

### ISSUE THREAD

**Issue by slkperkun** [allegro/allegro-api#6753]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Mam problem z pobraniem poprzez curl tokena do aplikacji, która pobiera aukcje z allegro.
Kod po autoryzacji pobieram bez problemu, ale próba pobrania tokena z tym kodem nie działa - nie ma błędów - jest zwracany pusty wynik wykonania zapytania.
Wcześniej wszystko działało, a od kilku dni pojawił się ten problem.

I have a problem with downloading a token via curl to the application that downloads auctions from allegro.
I download the code after authorization without a problem, but the attempt to download the token with this code does not work - there are no errors - an empty result of the query is returned.
It was working fine before, and this problem started a few days ago.

**Comment by MaciejFrackowiak** [comment]
Proszę przekaż nam szczegóły swoich wywołań poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - przy zgłoszeniu podaj proszę nr wątku z GH - 6753.

**Comment by sebastianlasaj** [comment]
Mamy ten sam problem. Zamiast tokenów dostajemy null.

**Comment by sebastianlasaj** [comment]
Niestety mimo zamknięcia zgłoszenia, u mnie nadal nie działa.

**Comment by slkperkun** [comment]
Ja zmieniłem wszystkie odwołania https://api.allegro.pl/ na https://allegro.pl/
i zastosowałem ich skrypt:

function getCurl($headers, $content) {
    $ch = curl_init();
    curl_setopt_array($ch, array(
        CURLOPT_URL => TOKEN_URL,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => $content
    ));
    return $ch;
}


function getAccessToken($authorization_code) {
    $authorization = base64_encode(CLIENT_ID.':'.CLIENT_SECRET);
    $authorization_code = urlencode($authorization_code);
    $headers = array("Authorization: Basic {$authorization}","Content-Type: application/x-www-form-urlencoded");
    $content = "grant_type=authorization_code&code=${authorization_code}&redirect_uri=" . REDIRECT_URI;
    $ch = getCurl($headers, $content);
    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong $resultCode $tokenResult");
    }
    return json_decode($tokenResult)->access_token;
}

**Comment by sebastianlasaj** [comment]
dzięki @slkperkun naprowadziłeś mnie na trop.
Problem rozwiązany.
U mnie była domena ssl.allegro.pl. Pomogła zamiana na allegro.pl

Jak dokładniej się przyjrzałem w zwracanych wcześniej wynikach była captcha.
