### ISSUE TITLE
429

### ISSUE THREAD

**Issue by narratorPL** [allegro/allegro-api#6754]

**Comment by narratorPL** [comment]
Błąd 429 ostatnio mi się pojawia. 
fakt, że był problem z oprogramowaniem i zapytania mogły się zapętlać. 
czy ograniczenie się zresetuje samo czy trzeba to jakoś zgłosić?

**Comment by MaciejFrackowiak** [comment]
Błąd 429 związany jest z działaniem mechanizmu [Leaky Bucket](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#ograniczenie-liczby-zapytan-limity). Po upływie czasu tj. bez wywoływania zasobów mechanizm automatycznie ściągnie blokadę.

**Comment by narratorPL** [comment]
Ile czasu potrzeba bez zapytań żeby blokada została zdjęta?

**Comment by MaciejFrackowiak** [comment]
Zależy to od intensywności wywołania błędu 429 - jeżeli otrzymasz błąd, a i tak będziesz wywoływać zasób, to czas ten będzie systematycznie wydłużać się.
