### ISSUE TITLE
Nieudokumentowany błąd (403 z adresem z domeny geo.captcha-delivery.com) przy próbie autoryzacji przez REST API

### ISSUE THREAD

**Issue by p-pawel** [allegro/allegro-api#6755]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [X] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy próbie uzyskania tokena (działając wg scenariusza "Authorization Code flow" punkty 5-6 ze strony https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow ) otrzymujemy błąd z 403 z następującym body (parametry usunięte jako że mogą zawierać jakieś wrażliwe dane):
```
{"url":"https://geo.captcha-delivery.com/captcha/?initialCid=...&cid=...&referer=...&hash=...&t=bv&s=...&e=..."}
```

Przy próbie wejścia na adres z odpowiedzi pojawia się strona "Zostałeś zablokowany." z nagłówkiem Allegro.

Czy oznacza to że coś się popsuło po stronie Allegro? Czy wprowadzona została jakaś zmiana, której nie udokumentowano na stronie? Do tej pory autoryzacja działała bez problemu - przez kilka lat. Co się zmieniło i dlaczego o tym nie wiemy?

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę cały request. W tym celu skorzystaj z naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). W zgłoszeniu dopisz GitHub #6755

**Comment by p-pawel** [comment]
Dzisiaj problem już nie występuje, więc (nie)stety nie mam czego przesłać. Pojawiło się samo i rozwiązało się samo, bez żadnych zmian z naszej strony, więc naturalnie podejrzewam (ciche) zmiany po stronie Allegro.

Przed zamknięciem ticketa zachęcam do aktualizacji dokumentacji w wyżej wskazanym punkcie o opis błędów, tak aby pokrywała ona scenariusze jakie rzeczywiście mogą pojawić się podczas korzystania z usługi.

**Comment by Lukasz-Zurek** [comment]
Cieszy mnie fakt, że sytuacja wróciła do normy. 

Nie zdążyliśmy zweryfikować tego jednostkowego przypadku. Dodam, że wskazany przez Ciebie link prowadzi do naszego poradnika, a nie dokumentacji. Poradnik staramy się aktualizować w oparciu o pewne dane. Jeżeli spotkasz się z podobnym problemem w przyszłości, bardzo proszę o kolejne zgłoszenie, dzięki czemu będziemy mogli poznać przyczynę i ewentualnie uzupełnić poradnik o przydatne dla wszystkich użytkowników informacje.

**Comment by p-pawel** [comment]
Dzień dobry. Błąd pojawił się znów wczoraj. Jest szansa że naprawi się znowu "samo" w ciągu jednej doby, czy przygotowywać logi?

Aby nie było żadnych nieporozumień:

- jeśli wskazałem nieprecyzyjnie miejsce, w którym oczekiwałbym opisu błędu, to poproszę o link do dokumentacji, w której znajdę coś o scenariuszach uwierzytelniania - szczególnie takie gdzie będzie coś więcej niż odesłanie do właśnie tego "poradnika" :)

- co potrzeba jeśli chodzi o logi zawierające cały request, czy np. curl będzie wystarczający?

- trzecia sprawa jest taka, że pojedynczy request pewnie niewiele pomoże, bo to jest dopiero któryś krok w całym flow :(

**Comment by Lukasz-Zurek** [comment]
@p-pawel Do dokładnej weryfikacji potrzebne nam będą pełne requesty (z przekazywanymi danymi) w cURL oraz response, krok po kroku tak jak przechodzisz cały proces autoryzacji. Prześlij proszę to wszystko korzystając z naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). W zgłoszeniu dopisz GitHub https://github.com/allegro/allegro-api/issues/6755.

**Comment by Lukasz-Zurek** [comment]
@p-pawel Wspomniałeś wcześniej o tym, że przy próbie wejścia na adres z odpowiedzi pojawia się strona "Zostałeś zablokowany." z nagłówkiem Allegro. Zanim prześlesz wszystkie requesty, prześlij proszę najpierw w [formularzu kontaktowym](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) adres IP, który został zablokowany wraz z informacjami kiedy dokładnie to się wydarzyło. Być może problem nie ma związku z samą autoryzacją.
