### ISSUE TITLE
Obecnie, po uzyskaniu tokenu za pośrednictwem API, możliwe jest zapytanie listy kategorii i listy produktów, ale błąd AccessDeniedException pojawia się podczas zapytania o szczegóły produktu? Jak to rozwiązać

### ISSUE THREAD

**Issue by qq16632785** [allegro/allegro-api#6756]
Obecnie, po uzyskaniu tokenu za pośrednictwem API, możliwe jest zapytanie listy kategorii i listy produktów, ale błąd AccessDeniedException pojawia się podczas zapytania o

**Comment by qq16632785** [comment]
Obecnie, po uzyskaniu tokenu za pośrednictwem API, możliwe jest zapytanie listy kategorii i listy produktów, ale błąd AccessDeniedException pojawia się podczas zapytania o szczegóły produktu? Jak to rozwiązać

**Comment by qq16632785** [comment]
![999](https://user-images.githubusercontent.com/125456710/220304646-cf3fdfea-adb5-43b0-9b1e-e0e0a13801a4.png)

**Comment by Lukasz-Zurek** [comment]
Prawdopodobnie korzystasz z autoryzacji typu[ client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow), która nie posiada kontekstu użytkownika. W[ naszej dokumentacji](https://developer.allegro.pl/documentation/) znajdziesz odpowiednie oznaczenie, jaki typ autoryzacji wymagany jest dla danego zasobu:

- bearer-token-for-user ([code](https://developer.allegro.pl/auth/#app) lub[ device](https://developer.allegro.pl/auth/#DeviceFlow) flow),
- bearer-token-for-application ([client credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow)).

Zasób [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct) wymaga [bearer-token-for-user](https://developer.allegro.pl/documentation/#section/Authentication/bearer-token-for-user).

**Comment by qq16632785** [comment]
Gdzie mogę uzyskać identyfikator filtra?

**Comment by Lukasz-Zurek** [comment]
Domyślam się, że chodzi Tobie o ten wątek: #6757 Zapoznaj się proszę z [tym poradnikiem](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#filters-types-and-paging).
