### ISSUE TITLE
Jak mogę uzyskać produkt oparty na ~categoryid~?

### ISSUE THREAD

**Issue by qq16632785** [allegro/allegro-api#6757]
Jak mogę uzyskać produkt oparty na ~categoryid~?

**Comment by Lukasz-Zurek** [comment]
Za pomocą [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) przy użyciu jednego żądania wystawisz m.in. ofertę powiązaną z produktem, którego nie ma w naszym Katalogu. W tej sytuacji musisz przekazać komplet danych, które opisują przedmiot, w tym również identyfikator kategorii. Więcej informacji na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-nowym-produktem).

**Comment by qq16632785** [comment]
Nie mogę tego zrozumieć,

**Comment by qq16632785** [comment]
![295a7df24d2a0f5c1fee6966fa5524f](https://user-images.githubusercontent.com/125456710/220587850-5795f713-2876-4af2-a1e8-f3f008248bc2.png)

**Comment by Lukasz-Zurek** [comment]
@qq16632785 Informacja ta dotyczy filtrów i możliwości ich użycia podczas wyszukiwania produktów z naszego katalogu, za pomocą [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts).

Typy filtrów i stronicowanie opisaliśmy dokładnie [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#typy-filtrow-i-stronicowanie).
