### ISSUE TITLE
Authorization header does not contain space after 'Bearer'.

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#6758]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Przy próbie zalogowania dostaje komunikat "Authorization header does not contain space after 'Bearer'." - 12.01.2021 wprowadziliście wytyczną "nie wstawiasz spacji między “Bearer” a tokenem, np. Authorization: Bearer{token}," . 
Czyli mam wstawiać spację czy nie mam wstawiać spacji?

**Comment by Lukasz-Zurek** [comment]
Powinieneś wstawić spację pomiędzy "Bearer", a tokenem.

**Comment by qshop123** [comment]
> Powinieneś wstawić spację pomiędzy "Bearer", a tokenem.

Ok, a gdzie jest w oficjalnej dokumentacji wzmianka o tym?

**Comment by Lukasz-Zurek** [comment]
W [dokumentacji](https://developer.allegro.pl/documentation/#section/Authentication) odsyłamy użytkowników do poradnika dotyczącego autoryzacji, w którym wspominamy o tym, że działamy w oparciu o [OAuth 2.0.](https://oauth.net/2/). Przydatne informacje znajdziesz również m.in. [tutaj](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#rejestracja-aplikacji) - _Tokeny dostępowe są zgodne ze standardem [JWT](https://en.wikipedia.org/wiki/JSON_Web_Token)_ - the Barer schema: `Authorization: Bearer eyJhbGci...<snip>...yu5CSpyHI`

Natomiast w części ["Wywołanie zasobu REST API"](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#wywolanie-zasobu-rest-api) znajdziesz przykład prawidłowego żądania, w tym również to jak ma wyglądać nagłówek "Authorization":

`'Authorization: Bearer {token}'`

Informacje te znajdziesz również w przykładowych żądaniach dla każdego zasobu opisanego w poradniku.
