### ISSUE TITLE
Jak uzyskać ID produktu do którego z automatu przypisuje mnie Allegro podczas wysyłania 

### ISSUE THREAD

**Issue by glorifyingpeace** [allegro/allegro-api#6759]
Wysyłamy produkt z ofertą na:
/sale/product-offers
Dostajemy komunikat:

```
{
    "errors": [
        {
            "code": "PARAMETER_MISMATCH",
            "message": "The provided parameter 'Marka'(3786) value (inna(3786_85)) does not match the existing parameter value (Nelly(3786_1646967))",
            "details": null,
            "path": "productSet[0].product.parameters",
            "userMessage": "The specified product exists. The specified parameter `Marka` with the value `inna(3786_85)` does not match the product parameter `Nelly(3786_1646967)`."
        }
    ]
}

```
W jaki sposób mogę sprawdzić do jakiego konkretnego ID produktu próbował mnie przyłączyć automat?
Mamy bardzo wiele prób połączenia naszych ofert z produktami posiadającymi błędnie wypełnione parametry. Bez tego nie jesteśmy w stanie zgłaszać zmian na "change - proposal"

**Comment by MaciejFrackowiak** [comment]
Niestety, obecnie nie zwracamy takiej informacji. Jedynym rozwiązaniem jest bazowanie na zwróconej informacji o niezgodności parametrów. W tym momencie można albo zgłosić propozycje produktu ([POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct)) lub opierając się na parametrach przeszukać bazę produktów ([GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts)).

**Comment by mbcont** [comment]
Ale jak zgłosić propozycję produktu w sytuacji jak nie mamy id produktu ponieważ np korzystamy sale/product-offers i to bo użytkownik nie potrafił dopasować wystawianego produktu do produtku allegro a api w response zwróciło taki błąd jak wyżej, czyli jak mniemam wewnętrzny system stojącym za sale/product-offers powiązał produkt z produktem allegro. A próba wyszukania tego produktu przez GET /sale/products nie daje jednoznacznego wyniku

**Comment by MaciejFrackowiak** [comment]
Odpytując [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts) z podanym kodem GTIN oraz wskazaną w Twoim requeście kategorią otrzymujesz listę produktów - bazując na rozmiarze XXL (id wartości 54_7) można przypisać konkretny produkt, który odpowiada przesyłanym przez Ciebie danym.

**Comment by mbcont** [comment]
ale wg nas żaden nie pasuje, bo np ktoś sobie wziął ean lub mpn

**Comment by mbcont** [comment]
dodatkowo np nie podaje w produkcie ean/mpn bo nie jest wymagany/nie mam a system i tak mnie powiązuje z produktem allegro

**Comment by MaciejFrackowiak** [comment]
Produkty identyfikujemy na podstawie wielu parametrów, nie tylko GTIN/EAN. W Twoim przypadku - podałeś 13 parametrów + parametr GTIN, które są tożsame z istniejącym już w naszej bazie produktem. Tym samym jednoznacznie można go zidentyfikować na podstawie danych z [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts). Alternatywnie - skorzystanie z [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct) z danymi z Twojego requestu zwraca konkretny produkt z naszej bazy - nagłówek "location".

**Comment by mateuszbienias** [comment]
W jaki sposób można wyszukać produkt na podstawie parametrów, które nie znajdują się w filtrach? W endpoincie GET /sale/products
