### ISSUE TITLE
Aktywacja sprzedaży - sandbox

### ISSUE THREAD

**Issue by xemix** [allegro/allegro-api#676]
Witam,
czy aktywacja sprzedaży w sandbox działa poprawnie? Kilkanaście dni temu zgłosiłem weryfikację, do tej pory nic: "Nieaktywne - trwa weryfikacja Twoich danych.".
Czy może ktoś pomóc? Aktywować konto ręcznie? Login: userek.
Druga sprawa (przy okazji) - jest problem z rejestracją w sandboxie - kilka skrzynek we własnych domenach - nie dociera mail aktywacyjny. Jedynie przy gmailu nie było problemów.

**Comment by PawelTaberski** [comment]
Aktywowałem Twoje konto, powinno już wszystko działać.

**Comment by xemix** [comment]
Działa, dziękuję.

**Comment by mpysz** [comment]
@PawelTaberski u mnie ten sam przypadek. Proszę o aktywowanie. Login: creativium2

**Comment by PawelTaberski** [comment]
Konto aktywowałem powinno już wszystko działać.

**Comment by mpysz** [comment]
Działa, dzięki.

**Comment by sewerp** [comment]
Bardzo proszę o aktywowanie konta na sandboxie (login: neonekpl) - nie mogę ani ustawić jako firma (wymaga dokonania przelewu) , ani aktywować konta gdyż płatniość pokazuje błąd 504. Bez aktywacji nie da się testować dodawania przedmiotów

![screenshot from 2018-11-08 20-16-11](https://user-images.githubusercontent.com/1838027/48221778-414c0980-e393-11e8-9ca5-a979ac2ad9f9.png)
![screenshot from 2018-11-08 20-16-48](https://user-images.githubusercontent.com/1838027/48221785-44df9080-e393-11e8-847d-a5cddb76c919.png)

**Comment by PawelTaberski** [comment]
Konto powinno już być aktywne.

**Comment by rfk91** [comment]
Witam

Proszę również o aktywowanie mojego konta: engin3s

Dziękuję

**Comment by MartaNowaczyk** [comment]
@rfk91 konto aktywowane
