### ISSUE TITLE
WZA - Punkt punktu nadania przesyłki jest niepoprawny

### ISSUE THREAD

**Issue by bartekc7** [allegro/allegro-api#6760]
Dzień dobry,
Mimo że kod punktu nadania nie jest przekazywany to API zawraca komunikat o błędnym punkcie nadania. 
Metoda Allegro Odbiór w Punkcie Pocztex.

`{
  "id": "6ee7e9af-c52f-4c33-a4d3-7681596e4763",
  "parcelId": null,
  "status": "ERROR",
  "errors": [
    {
      "code": "ERROR",
      "message": "Pickup point is incorrect",
      "details": null,
      "path": "pickup.pointId",
      "userMessage": "Punkt punktu nadania przesyłki jest niepoprawny"
    }
  ]
}`

**Comment by MaciejFrackowiak** [comment]
Czy możesz podać trace-id swojego wywołania, ponieważ nie mogę znaleźć tego wywołania po wskazanym id.

**Comment by bartekc7** [comment]
Wykonałem ponowną próbę
trace-id: 346909c38215b2ba
"id": "15713dc1-e233-4d81-8735-349aab93d9e3"

`{
  "id": "15713dc1-e233-4d81-8735-349aab93d9e3",
  "parcelId": null,
  "status": "ERROR",
  "errors": [
    {
      "code": "ERROR",
      "message": "Pickup point is incorrect",
      "details": null,
      "path": "pickup.pointId",
      "userMessage": "Punkt punktu nadania przesyłki jest niepoprawny"
    }
  ]
}`

**Comment by MaciejFrackowiak** [comment]
Wyjaśniam to z zespołem, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
W przypadku przesyłek Poczty Polskiej zawsze niezbędne jest wskazanie punktu nadania.

**Comment by bartekc7** [comment]
Dziękuje, po uzupełnieniu jest ok. 
Co ciekawe generowanie przesyłki Pocztex bezpośrednio przez API Poczty Polskiej już nie wymaga id punktu nadania:)
