### ISSUE TITLE
Error "NotAcceptableException" / "Not acceptable representation requested. Please check 'Accept' request header"

### ISSUE THREAD

**Issue by Atomek69** [allegro/allegro-api#6761]
Witam, przy próbie pobrania kategorii poprzez wywołanie https://api.allegro.pl/sale/categories wyskakuje mi błąd :
_{"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept' request header","details":null,"path":null,"userMessage":"The request contains incorrect data. Contact the author of the application."}]}_

Dopiero "poradziłem" sobie z autoryzacją, co nadal nie jest satysfakcjonujące, mało zrozumiale wytłumaczona dokumentacja jeśli chodzi o tematykę najważniejszą tj. AUTH,

**Comment by MaciejFrackowiak** [comment]
Czy przekazałeś nagłówek Accept w postaci "application/vnd.allegro.public.v1+json"? O wersjonowaniu wspominamy [tu](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#wersjonowanie-zasobow).

**Comment by Atomek69** [comment]
Tak też próbowałem, ale błędem okazało się niepotrzebne kodowanie json nagłówków. Dziękuję za odpowiedź teraz natomiast dostaję zwrotkę : "200" jeśli dobrze rozumiem,  to status odpowiedzi ? a gdzie znaleźć treść ?

**Comment by MaciejFrackowiak** [comment]
Status 200 oznacza, że zwróciliśmy w odpowiedzi listę kategorii. Dane powinny się pojawić w aplikacji, z której wykonujesz request.

**Comment by Atomek69** [comment]
Dziękuję za fachową pomoc, udało się nawiązać poprawnie połączenie i wywołać wstępne zapytanie z otrzymaniem odpowiedzi.
