### ISSUE TITLE
Witaj, chcę zapytać, jak użyć filtra do wyszukiwania i jak uzyskać filter_Id?

### ISSUE THREAD

**Issue by HUPg-95** [allegro/allegro-api#6762]
Witaj, chcę zapytać, jak użyć filtra do wyszukiwania i jak uzyskać filter_Id?
Chcę zapytać towar przez identyfikator kategorii i dodać kilka warunków filtrujących, ale nie wiem, jak użyć filtra. W dokumencie mówi się, że użyć filtra_ ID do filtrowania, ale nie wiem jak uzyskać filtr_ ID

**Comment by Lukasz-Zurek** [comment]
Gdy szukasz produktu w danej kategorii, np. zgodnie z naszym przykładem w poradniku:

`GET https://api.allegro.pl/sale/products?phrase=Harry Potter i Książę Półkrwi&category.id=66781`

na końcu odpowiedzi - w sekcji “filters” - otrzymasz listę dostępnych filtrów.

Filtr tworzysz, podając identyfikator filtra i identyfikator szukanej wartości, na zasadzie {filter.id}={filter.value}.

Wszelkie szczegóły dotyczące typów filtrów opisaliśmy [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#typy-filtrow-i-stronicowanie). Zapoznaj się również z całym procesem [wyszukiwania produktów](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-znalezc-produkt) poprzez API.

**Comment by HUPg-95** [comment]
Jeśli chcę uzyskać wszystkie produkty w kategorii Smartfony, co powinienem zrobić?

**Comment by HUPg-95** [comment]
> Jeśli chcę uzyskać wszystkie produkty w kategorii “Smartfony”, co powinienem zrobić?

**Comment by HUPg-95** [comment]
> Gdy szukasz produktu w danej kategorii, np. zgodnie z naszym przykładem w poradniku:
> 
> `GET https://api.allegro.pl/sale/products?phrase=Harry Potter i Książę Półkrwi&category.id=66781`
> 
> na końcu odpowiedzi - w sekcji “filters” - otrzymasz listę dostępnych filtrów.
> 
> Filtr tworzysz, podając identyfikator filtra i identyfikator szukanej wartości, na zasadzie {filter.id}={filter.value}.
> 
> Wszelkie szczegóły dotyczące typów filtrów opisaliśmy [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#typy-filtrow-i-stronicowanie). Zapoznaj się również z całym procesem [wyszukiwania produktów](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-znalezc-produkt) poprzez API.

Jeśli chcę uzyskać wszystkie produkty w kategorii “Smartfony”, co powinienem zrobić?

**Comment by Lukasz-Zurek** [comment]
Nie uzyskasz tego typu listy produktów. Aby skorzystać z [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts) musisz wskazać np. frazę i tryb wyszukiwania oraz identyfikator kategorii, czyli category.id, np. GET /sale/products?phrase=iphone14&category.id=48978.
