### ISSUE TITLE
api about Offer updates

### ISSUE THREAD

**Issue by bingnew** [allegro/allegro-api#6763]
Dear allegro team, 
we want to obtain the  “offer updates ”information under the account through the interface. Is there such an interface? 
![39001b7fb1262988fe29fa65beba9ec9](https://user-images.githubusercontent.com/72594584/220863041-23800ce3-641d-4b08-8f22-b3c83cbb18a9.png)

 In addition, can I accept change through api?
![8ac14298e29fc19786e960f6c06e7a24](https://user-images.githubusercontent.com/72594584/220863476-a6a11195-59bf-4aa5-b12c-010a69c5758e.png)

[Looking forward to your reply]

**Comment by Lukasz-Zurek** [comment]
Unfortunately we do not have such resources in our API, so you will not be able to check these information or accept suggested changes through API.
