### ISSUE TITLE
Ilość sprzedanych w sale/offers/{offerId}

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#6764]
Hej,
Przy pobraniu wszystkich ofert sprzedającego `sale/offers` dostaję informację o ilości sprzedanych w ostatnich 30 dniach. Nie dostaję niestety tej informacji przy pobraniu pełnej oferty `sale/offers/{offerId}`.
Czy to przeoczenie, czy celowe działanie?
Czy możecie dodać tą informację w pełnej ofercie?

**Comment by MaciejFrackowiak** [comment]
Jest to właściwe działanie zasobu - w ofercie w serwisie WWW również nie prezentujemy tych wartości. Nie przewidujemy zmian w tym zakresie.

**Comment by hahyes** [comment]
@jakubmaguza Niestety jedyną opcją jest zliczanie tego po zamówieniach na bieżąco w formie licznika w bazie czy zliczając zapisane w bazie zamówienia. Allegro nie daje danych statystycznych. :/

**Comment by jakubmaguza** [comment]
@hahyes Jeśli pobierzesz wszystkie oferty sprzedającego przez `sale/offers`, to tam masz sprzedaż z ostatnich 30 dni.
