### ISSUE TITLE
Informacja o kosztach promowania oferty

### ISSUE THREAD

**Issue by kacperKarman** [allegro/allegro-api#6765]
Mam pytanie dotyczące zasobu zwracającego informacje o kosztach związanych z ofertą (POST pricing/offer-fee-preview). Zauważyłem problem przy jednej aukcji która korzysta z opcji wyróżnienia ale powyższy endpoint mimo to zwraca tylko pola związane ze standardową prowizją i opłatą za utworzenie aukcji. Przy innych moich aukcjach promowanych otrzymuję pole z opłatą za wyróżnienie, a przy tej jednej z jakiegoś powodu nie. 
Mój sklep to telstar_sklep a numer aukcji której dotyczy pytanie to 13245879313. 
Jaki może być powód tego wyjątku?

**Comment by MaciejFrackowiak** [comment]
W zasobie [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST) nie uwzględniamy opłat za promowanie realizowanych w ramach pakietów promowań.

**Comment by kacperKarman** [comment]
Przy promowaniach w ramach pakietów do tej pory dostawałem pole z opłatą za wyróżnienie z kwotą 0zł natomiast w tym przypadku w ogóle nie otrzymuję tego pola i odpowiedź nie różni się niczym od odpowiedzi dla oferty bez promowania. Czy w ostatnim czasie coś może zmieniło się w API w tej kwestii lub jest możliwość że jednak chodzi o coś innego?

**Comment by kacperKarman** [comment]
Robię to w taki sposób, sprawdzę czy w szczegółach oferty otrzymuję rzeczywiście informację że jest promowana bo może tam coś się nie zgadza już przy pobieraniu. 
Dziękuję za pomoc!
