### ISSUE TITLE
Producenci

### ISSUE THREAD

**Issue by MartinScootshop** [allegro/allegro-api#6766]
Cześć,
uprzejma prośba o info, gdzie możemy się zgłosić z prośbą o dodanie nazw producentów? "Inna marka" w jakiś sposób uniemożliwia sparowanie z naszymi produktami w e-shopie.

**Comment by MaciejFrackowiak** [comment]
Proszę skontaktuj się z obsługą serwisu poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) i przedstaw w wiadomości swoje prośby.
