### ISSUE TITLE
problem z allegro i API

### ISSUE THREAD

**Issue by fabrykawydruku** [allegro/allegro-api#6767]
dzień dobry, mam taki problem. Bo korzystam z aleasystenta, który posiada kilka funkcji, między innymi unikanie opłaty utrzymaniowej. Problem jest tego typu, że do tej pory program aleasystent zamykał ofertę gdzie miała być naliczona opłata utrzymaniowa i wystawiał ją na nowo przez co nie musiałem płacić tej opłaty. Natomiast od kilku dni dzieje się tak, że to allegro samo od siebie wznawia te oferty i naliczana jest opłata. Dlaczego tak się dzieje? Rozmawiałem przedtem z konsultantem allegro i potwierdził, że oferty nie są wystawiane przez API, tylko wystawiane są z pozycji serwisu allegro. Dlaczego tak się dzieje? Dodam, że sprawdzam w panelu allegro aplikację używane przez API i aleasystent tam widnieje mimo to przestał wystawiać oferty i robi to od 3-4 allegro. Można zrobić tak żeby te oferty wznawiane były przez aleasystent? Czekam na odpowiedź, pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Oczywiście, aplikacje zewnętrzne mają możliwość zarządzania wznawianiem ofert - tu najlepiej gdybyś skontaktował się ze wsparciem swojej aplikacji.
Natomiast samym wznawianiem w Allegro możesz zarządzać również poprzez zakładkę [Mój asortyment](https://allegro.pl/moje-allegro/sprzedaz/obsluga-ofert/moj-asortyment?limit=20&publication.status=ACTIVE&sellingMode.format=BUY_NOW).

**Comment by fabrykawydruku** [comment]
a jak wyłączyć wystawianie przez allegro? tak żeby wystawiane było to przez
aleasystent ?

czw., 23 lut 2023 o 13:42 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
Operacje poprzez zakładkę Mój asortyment wykonujesz ręcznie - jeśli chcesz wyłączyć autowznawianie w ofercie, przejdź do jej edycji i odznacz opcję Wznawianie oferty.

**Comment by fabrykawydruku** [comment]
tylko, że ja mam tą opcję odznaczoną w każdej ofercie, więc dlaczego
allegro wystawia oferty ?

czw., 23 lut 2023 o 13:51 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
To już musisz wyjaśnić bezpośrednio z obsługą serwisu kontaktując się poprzez [formularz](https://allegro.pl/pomoc/kontakt).
