### ISSUE TITLE
Generowanie linków polecających

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#6769]
Hej,
Niektóre serwisy zewnętrzne posiadają możliwość generowania linków polecających. Niestety w API nie widzę takiej możliwości.
Czy planujecie ją dodać, albo czy jest jakaś alternatywna metoda, zamiast wchodzenia w każdą ofertę i klikania "Udostępnij"?

**Comment by Lukasz-Zurek** [comment]
Obawiam się, że nie ma innej alternatywnej metody w przypadku udostępniania ofert, natomiast co do samego programu Allegro Polecam - nie mamy w planach wdrażania zasobów, które pozwalałyby na generowanie linków polecających.

**Comment by jakubmaguza** [comment]
Czy wiesz w takim razie jak robią to serwisy typu pepper?

**Comment by Lukasz-Zurek** [comment]
@jakubmaguza Pepper opiera się na okazjach, w których użytkownicy dodają przekierowanie (linka) do oferty i tu zapewne niektórzy z nich dodają za pomocą opcji "Udostępnij" na stronie oferty w Allegro (będąc w programie Allegro Polecam), ale są też tacy, którzy wklejają zwykły link do oferty, nie będąc świadomym istnienia programu Allegro Polecam. Generalnie te dwa linki różnią się pomiędzy sobą.

**Comment by jakubmaguza** [comment]
Z tego co zauważyłem, pepper modyfikuje wrzucony link, usuwa afiliację użytkownika i dodaje swoją.
Z drugiej strony serwisy typu goodie czy letyshops też potrafią dodać swoją afilację. Czyli jeśli dobrze rozumiem, to juz kwestia indywidualnej umowy z allegro?

**Comment by Lukasz-Zurek** [comment]
Nie mam wiedzy na ten temat, więc też nie chcę tutaj ewentualnie wprowadzać Ciebie w błąd (czy to kwestia indywidualnej umowy z Allegro, czy może coś innego). Mogę jedynie zachęcić Cię do bezpośredniego kontaktu za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=e2e1f990-74d6-4bea-9b5c-a408bde7983d). Mam nadzieję, że tam uzyskasz więcej informacji na ten temat.
