### ISSUE TITLE
Problem z przekroczeniem liczby draftów

### ISSUE THREAD

**Issue by ODeviatkin** [allegro/allegro-api#6771]
Wystawiam oferty za pomocą :  POST _/sale/product-offers_, ale po wystawieniu koło 20500 ofert, pojawił się błąd: 
```
POST /sale/product-offers
<Response [422]>
{"errors":[{"code":"ConstraintViolationException.MaxInactiveOffers","message":"You cannot create new drafts - your account has exceeded the maximum number 20000 of drafts.","details":"ConstraintViolationException.MaxInactiveOffers","path":"null","userMessage":"Nie możesz utworzyć nowych szkiców - Twoje konto przekroczyło maksymalną liczbę 20000 szkiców."}]}
```
Ważna informacja: podczas publikacji to faktycznie serwer zwracał informacje, że oferta jest INACTIVE i kod 202, ale po wejściu na stronę widziałem, że oferta jest aktywna. poniższe zapytania zwracały analogiczną informację.

Wykasowałem wszystko co mogłem w asortymencie.
Sprawdzam liczbę draftów:
```
GET /sale/offers?publication.status=INACTIVE
<Response [200]>
{'offers': [], 'count': 0, 'totalCount': 0}
```
Sprawdzam liczbę wszystkiego:
```
/sale/offers?publication.status=INACTIVE&publication.status=ACTIVATING&publication.status=ACTIVE&publication.status=ENDED
<Response [200]>
{'offers': [], 'count': 0, 'totalCount': 0}
```
I teraz pytanie: Jak wykasować szkice których zdaniem serwera jest 20k+ podczas gdy zapytanie o stan asortymentu zwraca 0?

**Comment by hahyes** [comment]
@ODeviatkin Musisz poczekać do poniedziałku, aż ktoś z devów się zlituje i ci licznik ręcznie naprawi. Albo naprawi się sam po upłynięciu doby, mniej więcej. Zgłaszałem im ten problem, jest on powiązany z czymś co się dzieje z draftami u nich wewnętrznie, bo np. dostaje eventy o zmianie stanu oferty, której nie utworzono bo wystąpił błąd (niewypełniony parametr na przykład). Po swojej stronie taki draft z błędu nie istnieje, ale w systemie Allegro wewnętrznie został utworzony. 

TL;DR Allegro wewnętrznie u siebie widzi, że masz 20k draftów. Ty widzisz 0. I niestety nie da się tego naprawić po twojej stronie.

**Comment by MaciejFrackowiak** [comment]
@ODeviatkin Proszę podaj identyfikator lub login użytkownika, na którym otrzymałeś błąd. 
@hahyes Zgłosiłem Twoje konto do poprawienia licznika, wrócę z odpowiedzią.

**Comment by hahyes** [comment]
@MaciejFrackowiak Dodaje również dwa inne konta klientów, które padły ofiarą tego problemu.

Trace-Id: 2108e9c69e662e5e
Trace-Id: b5694004c311d0d0

Na każdym z nich jest 0 szkiców i nie można wystawić żadnej aukcji.

**Comment by MaciejFrackowiak** [comment]
@hahyes Konto z trace-id "9d6dbc311d3fd456" już poprawione. W nowym zgłoszeniu podałeś dwa trace-id, ale prowadzą one do jednego konta - 660xxxx, proszę podaj właściwy trace-id.

**Comment by ODeviatkin** [comment]
@MaciejFrackowiak, login użytkownika:
NeoSneakers
Dzięki!

Kiedy mniej więcej można się spodziewać, że błąd zostanie naprawiony?

**Comment by hahyes** [comment]
@MaciejFrackowiak Podaję poprawny trace-id do drugiego konta (na kolejnym widzę że już licznik został naprawiony): 
Trace-Id: 6b14433004e4d6f7

**Comment by MaciejFrackowiak** [comment]
@hahyes Potwierdzam - pierwsze poprawione, drugie zgłoszone.

@ODeviatkin Możliwie szybko, już zgłosiłem konto do poprawki.

**Comment by hahyes** [comment]
@MaciejFrackowiak I wracamy do początku pętli ze szkicami (naprawione dzisiaj 2 godziny temu):
Trace-Id: 14fe5dadebadedee

**Comment by MaciejFrackowiak** [comment]
@ODeviatkin Już poprawione.

@hahyes Nr 2 poprawione, a Twoje konto z pierwszego zgłoszenia ponownie przekazałem.

**Comment by MaciejFrackowiak** [comment]
@hahyes Posprzątane.

**Comment by ODeviatkin** [comment]
Znowu ten sam błąd :)

**Comment by MaciejFrackowiak** [comment]
@ODeviatkin Już poprawione.

**Comment by hahyes** [comment]
@MaciejFrackowiak Dołączam i ja: 
Trace-Id: ffec08df35817bd4
Trace-Id: ffd11194e6496fdf
Trace-Id: ffceb8cb12de6622

**Comment by ecat-rg** [comment]
Również ja się podepnę, problem występuje na wielu kontach. Wygląda na globalny.

**Comment by MaciejFrackowiak** [comment]
@hahyes Poprawione.

@ecat-rg Proszę podaj identyfikatory kont, jest to niezbędne do odświeżenia danych.

**Comment by ecat-rg** [comment]
@MaciejFrackowiak dwa przykładowe, ale jest ich cała masa, będziemy musieli pisać za każdym razem, kiedy będziemy się odbijać mimo nieprzekroczonego limitu?

Trace-Id: 2232f6f315afee00
Trace-Id: f632d72ab1492b1f

**Comment by MaciejFrackowiak** [comment]
@ecat-rg Dwa wymienione konta poprawione. Niestety tak, dopóki nie będziemy mieć globalnego rozwiązania, musimy działać ad hoc.

**Comment by hahyes** [comment]
@MaciejFrackowiak I jeszcze raz:
Trace-Id: 100929d53d776c8
Trace-Id: 1021834888242e0c
Trace-Id: 11f16e0cfb28c1f1

Z tego co widziałem udało się wystawić "zaledwie" 14 tysięcy aukcji i przyblokowało. Serio, bardzo dziwne jest to zachowanie systemu, skoro nawet nie mam tych 20k szkiców utworzonych ogółem a i tak pada jeszcze szybciej.

**Comment by MaciejFrackowiak** [comment]
@hahyes Nr 1 i 2 poprawione, dla nr 3 trace-id nie wskazuje na żadne wywołanie.

**Comment by hahyes** [comment]
@MaciejFrackowiak Spróbujmy zatem z tym?
Trace-Id: 138b2cf73ac90334

**Comment by MaciejFrackowiak** [comment]
@hahyes I tu poprawione.

**Comment by ecat-rg** [comment]
@MaciejFrackowiak Kolejne przypadki:
Trace-Id: ade0274adfebb432
Trace-Id: ef77a189b348afc

**Comment by MaciejFrackowiak** [comment]
@ecat-rg Wskazane przez Ciebie trace-id prowadzą do wywołań GET /sale/user-ratings.

**Comment by hahyes** [comment]
@MaciejFrackowiak Dzienna porcja trace-id:
Trace-Id: f702fa9aa041fa7e
Trace-Id: e3e4a4659004642c

**Comment by MaciejFrackowiak** [comment]
@hahyes Spożytkowane i poprawione ;)

**Comment by hahyes** [comment]
@MaciejFrackowiak Jeszcze jedno konto dołączyło:
Trace-Id: 8f6569c31476fae2

**Comment by MaciejFrackowiak** [comment]
@hahyes Gotowe.

**Comment by ecat-rg** [comment]
@MaciejFrackowiak nowy dzień, nowe konto ;) 
Trace-Id: abd9c4bac5289694

**Comment by ecat-rg** [comment]
@MaciejFrackowiak i jeszcze jedno:
Trace-Id: 96fc6025ddabe316

**Comment by MaciejFrackowiak** [comment]
@ecat-rg Załatwione.

**Comment by ecat-rg** [comment]
@MaciejFrackowiak kolejne 2 konta: 
trace-id: 6d14b1141a478b4c
trace-id: c5a13a640330384e

**Comment by MaciejFrackowiak** [comment]
@ecat-rg Poprawione.

**Comment by ecat-rg** [comment]
@MaciejFrackowiak kolejne przypadki:

trace-id: 7a9734376d618f7b
trace-id: ed8ea9e525aafc16
trace-id: ce5442eaac7bce65

**Comment by MaciejFrackowiak** [comment]
@ecat-rg Gotowe.

**Comment by ecat-rg** [comment]
@MaciejFrackowiak kolejny przypadek:
trace-id: 318b3f48335e309

**Comment by MaciejFrackowiak** [comment]
@ecat-rg Załatwione.
