### ISSUE TITLE
Metody eksportowe

### ISSUE THREAD

**Issue by xVinniVx** [allegro/allegro-api#6772]
Przy każdym requescie wystawienia draftu w niektórych kategoriach otrzymuję błąd walidacji i komunikat:

**Czy wiesz, że dodając metody eksportowe do swoich ofert, możesz trafić do większej grupy klientów? Nie czekaj, dodaj metody eksportowe już teraz i zwiększ swoją sprzedaż**

Jak to obejść?

**Comment by hahyes** [comment]
Jesteś pewien, że jest to błąd w polu `errors` a nie ostrzeżenie w polu `warnings`?

**Comment by xVinniVx** [comment]
W 100% - i najlepsze - jak się ponowi kilkadziesiąt razy wystawienie draftu, w odstępstwie czasu, to przechodzi.

Ogólnie, nawet jeżeli byłby to jakikolwiek błąd - to WTF Allegro? Ciężko wyświetlić poprawny errorMessage, tylko to co wyżej? Jak ma to pomóc przy eliminacji czegokolwiek?

**Comment by hahyes** [comment]
@xVinniVx Uważaj, bo zaraz wpadniesz w kolejny ich bug - limit draftów. ;)

W ogóle od kilku miesięcy mam wrażenie, że oni wrzucają bez kontroli rzeczy na produkcję. Wysyłam z Allegro leżało dobry tydzień po ich ostatnich zmianach w architekturze i metodach dostaw. Od paru tygodni dostaje zdarzenia ofert - draftów, których po stronie klientów w ogóle nie ma i nie można ich znaleźć. Regularnie wpada się w limit draftów, gdy dużo wystawiasz bo Allegro uparcie twierdzi, że masz nadal 20k draftów. Możesz mieć nałożoną blokadę i 0 draftów. Programuję integrację od kilku lat już i czasami aż się dziwię, co się u nich dzieje...

**Comment by Lukasz-Zurek** [comment]
@xVinniVx Prześlij proszę przykładowe trace-id. Zweryfikowałbym wówczas konkretny przypadek. Z dostępnych mi informacji wynika, że ta informacja zwracana jest w `warnings`.
