### ISSUE TITLE
Błąd informujący o limicie 20000 szkiców mimo ich braku

### ISSUE THREAD

**Issue by Kuba-Id** [allegro/allegro-api#6773]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ X] ze środowiskiem produkcyjnym / with the production environment

Podczas próby wystawienia przedmiotu, request:
https://api.allegro.pl/sale/offers

Dodawanie nowej oferty w celu jej wystawienia.

Wysyłane dane POST:
`
{"name":"T-SHIRT G\u0141ADKI DAMSKI 34 019","category":{"id":"76104"},"external":{"id":"258019"},"publication":{"duration":"P7D"},"sellingMode":{"format":"AUCTION","price":{"amount":"12.99","currency":"PLN"},"startingPrice":{"amount":"11.99","currency":"PLN"}},"stock":{"available":1,"unit":"UNIT"},"delivery":{"handlingTime":"PT24H","shippingRates":{"id":"ce792ec6-d290-4842-aacf-28f75bdbfd3d"}},"payments":{"invoice":"VAT"},"tax":{"percentage":"23.00"},"afterSalesServices":{"impliedWarranty":{"id":"68bc3779-083a-4389-8a9f-574a2107989c"},"returnPolicy":{"id":"1db04a6c-12df-47ab-86de-0f6e155c57df"},"warranty":{"id":"76744325-0c59-4d6a-8ef8-eef9e10851e1"}},"location":{"countryCode":"PL","province":"WIELKOPOLSKIE","city":"Pozna\u0144","postCode":"61-323"},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/1190bf\/f3cb62a74a5db9d119969291b497","description":null},{"url":"https:\/\/a.allegroimg.com\/original\/11c91d\/3ed570e84d3c8b67a8124bff9dda","description":null},{"url":"https:\/\/a.allegroimg.com\/original\/11900f\/e400f8a04ea0bdc28a3d78436fbf","description":null},{"url":"https:\/\/a.allegroimg.com\/original\/113b20\/c89ec026434c9b1b9f0a22c74787","description":null}],"parameters":[{"id":"202641","values":[],"valuesIds":["202641_212457"],"rangeValue":null},{"id":"249512","values":[],"valuesIds":["249512_1647413"],"rangeValue":null},{"id":"3786","values":[],"valuesIds":["3786_85"],"rangeValue":null},{"id":"201017","values":[],"valuesIds":["201017_2337"],"rangeValue":null},{"id":"54","values":[],"valuesIds":["3806_2"],"rangeValue":null},{"id":"11323","values":[],"valuesIds":["11323_2"],"rangeValue":null},{"id":"3766","values":[],"valuesIds":["3766_1"],"rangeValue":null}],"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>T-SHIRT G\u0141ADKI DAMSKI 34<\/h1>"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/1190bf\/f3cb62a74a5db9d119969291b497"},{"type":"TEXT","content":"<h1>Opis produktu<\/h1><ul><li><b>Marka<\/b>: -<\/li><li><b>Rozmiar<\/b>: 34<\/li><li><b>Cechy dodatkowe<\/b>: brak<\/li><li><b>Dekolt<\/b>: okr\u0105g\u0142y<\/li><li><b>Inna marka<\/b>: -<\/li><li><b>Kolor<\/b>: czarny<\/li><li><b>Materia\u0142 dominuj\u0105cy<\/b>: wiskoza<\/li><li><b>Stan<\/b>: U\u017cywany<\/li><li><b>Wz\u00f3r dominuj\u0105cy<\/b>: bez wzoru<\/li><li><b>Indeks produktu<\/b>: 258019<\/li><li><b>Dodatkowe informacje<\/b>: ROZPRUCIE Z TY\u0141U PRZY DEKOLCIE NA OK. 2 CM <\/li><\/ul>"}]},{"items":[{"type":"TEXT","content":"<h1>Metki<\/h1>\n\n<p>Produkt posiada cz\u0119\u015bciowo wyci\u0119te metki ze wzgl\u0119du na dystrybucje outletow\u0105.<\/p>"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11c91d\/3ed570e84d3c8b67a8124bff9dda"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11900f\/e400f8a04ea0bdc28a3d78436fbf"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/113b20\/c89ec026434c9b1b9f0a22c74787"}]}]},"product":{"id":"683c44a4-e2a7-43b7-846a-a314fc0bf2fb"}}
`

Następuje odpowiedź API:

`{"errors":[{"code":"VALIDATION_ERROR","message":"**You cannot create new drafts - your account has exceeded the maximum number 20000 of drafts.**","details":"ConstraintViolationException.MaxInactiveOffers","path":"null","userMessage":"Nie możesz utworzyć nowych szkiców - Twoje konto przekroczyło maksymalną liczbę 20000 szkiców."}]}`

Tymczasem na koncie, z którego następuję wystawianie jest może kilka szkiców. Nawet ich wyzerowanie, nie pomaga.

Trace ID - o dziwo, również, nie zostało zwrócone przez curl_info.

Prośba o pilną pomoc!

**Comment by MaciejFrackowiak** [comment]
Zgłosiłem problem już do właściwego zespołu, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Licznik szkicy już poprawiony.

**Comment by Kuba-Id** [comment]
Problem wrócił, prośba o szybką pomoc.

**Comment by MaciejFrackowiak** [comment]
Poprawione.

**Comment by Kuba-Id** [comment]
Powtórka z rozrywki - dzisiaj, przyznam, że robi się to męczące. Będziemy tak pisać codziennie? hmm...

**Comment by MaciejFrackowiak** [comment]
Staramy się znaleźć rozwiązanie globalne, ale to wymaga czasu. Licznik odświeżony.

**Comment by ecat-rg** [comment]
Kolejne dwa konta @MaciejFrackowiak 

trace-id: 80b98d4a8f32e6c8
trace-id: 302e9ce286fb22ff

**Comment by MaciejFrackowiak** [comment]
@ecat-rg Już poprawione.

**Comment by ecat-rg** [comment]
@MaciejFrackowiak 
jeszcze dwa:
trace-id: d02a5daeee7002c8
trace-id: 1975c5dca863c537

**Comment by MaciejFrackowiak** [comment]
@ecat-rg Załatwione.

**Comment by hahyes** [comment]
@MaciejFrackowiak Jedno konto się zablokowało w weekend, potrzeba pomocy: 
Trace-Id: 10112b307bd0849a

**Comment by MaciejFrackowiak** [comment]
@hahyes I już OK.

**Comment by hahyes** [comment]
@MaciejFrackowiak Chyba jeszcze nie, dalej mam błąd: e47391a992e8538

**Comment by MaciejFrackowiak** [comment]
@hahyes Wskazanego trace-id nie mogę wyszukać w historii wywołań.

**Comment by hahyes** [comment]
@MaciejFrackowiak Może jeden z poniższych spasuje:
e98a0550bcc45ab8
e9b70ae3088cfe71
e9c8086af097af60
ff5e0d7182728bbd

**Comment by MaciejFrackowiak** [comment]
@hahyes Double check poszedł i powinno teraz być już OK ;)

**Comment by hahyes** [comment]
@MaciejFrackowiak Jest OK. Dziękuję bardzo! :)

**Comment by MaciejFrackowiak** [comment]
@flixus-milan99 @arolznov Liczniki poprawione.

**Comment by ecat-rg** [comment]
@MaciejFrackowiak jeszcze dwa:
trace-id: 1d4810d30515162a
trace-id: 87824f90e9a4d7e0

**Comment by MaciejFrackowiak** [comment]
@ecat-rg Poprawione.

**Comment by Kuba-Id** [comment]
> Staramy się znaleźć rozwiązanie globalne, ale to wymaga czasu. Licznik odświeżony.

Panie Macieju, dziś znowu to samo, czuję bezsilność :-( Najgorzej, że tego błędu nie idzie poprawić samodzielnie - bez Pana pomoc, a ostatnio wydarzył się on w piątek pod wieczór i musieliśmy czekać do poniedziałku do 8 :-(

**Comment by MaciejFrackowiak** [comment]
@Kuba-Id Zgadza się, również i dla nas nie jest to komfortowe położenie. Mogę tylko zapewnić, że problem jest traktowany priorytetowo. Jednocześnie licznik draftów już poprawiony.

**Comment by Kuba-Id** [comment]
@MaciejFrackowiak Panie Macieju, chyba błąd jednak jest dalej, nic się nie zmieniło :-|

**Comment by MaciejFrackowiak** [comment]
@Kuba-Id Niestety, nie widzę w historii logów wskazanego trace-id.

**Comment by Kuba-Id** [comment]
Hmm... a może to coś pomoże, wklejam całość.

**response:**
stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => VALIDATION_ERROR [message] => You cannot create new drafts - your account has exceeded the maximum number 20000 of drafts. [details] => ConstraintViolationException.MaxInactiveOffers [path] => null [userMessage] => Nie możesz utworzyć nowych szkiców - Twoje konto przekroczyło maksymalną liczbę 20000 szkiców. ) ) ) 

**nagłówki:**
Array ( [expires] => 0 [cache-control] => no-cache, no-store, max-age=0, must-revalidate [x-xss-protection] => 1; mode=block [pragma] => no-cache [x-frame-options] => DENY [trace-id] => f893ce9ec692f68d [date] => Tue, 07 Mar 2023 10:00:50 GMT [x-content-type-options] => nosniff [strict-transport-security] => max-age=31536000 ; includeSubDomains [content-type] => application/json [http_code] => 422 )

**Comment by MaciejFrackowiak** [comment]
@Kuba-Id Problemem był identyfikator użytkownika - wcześniej podawałeś zawsze trace-id dla konta xxxx619, a teraz trace-id pasował do innego tj. xxxx898 - licznik wyrównany.

**Comment by ecat-rg** [comment]
@MaciejFrackowiak kolejna porcja ode mnie:
trace-id: 2752f1b96423e0d2
trace-id: a26982879f06f882
trace-id: 52844878b2fd4f6e

**Comment by ecat-rg** [comment]
@MaciejFrackowiak 
kolejna porcja z rana:
trace-id: 4c1a222b7e3d4c34
trace-id: a76cf5583e492590
trace-id: 88a0e52ce276d2eb
trace-id: ddf1c57c0954c32b
trace-id: dfe89cfc41118303
trace-id: 446c9fe3b9c6f7de
trace-id: 54a2649ad229128f
trace-id: dd32cf45a6304370
trace-id: 3fd6373f05e93b5c

**Comment by MaciejFrackowiak** [comment]
@ecat-rg Gotowe.

**Comment by ecat-rg** [comment]
@MaciejFrackowiak powracające konto do odblokowania
trace-id: 1d4026b573977ac8

**Comment by MaciejFrackowiak** [comment]
@ecat-rg W tym przypadku faktycznie został przekroczony limit 20000 szkicy na koncie.

**Comment by ecat-rg** [comment]
@MaciejFrackowiak problem wrócił po kilku miesiącach, podsyłam trace-id: cafeb8ef96508fd4

**Comment by MaciejFrackowiak** [comment]
@ecat-rg Problem rozwiązaliśmy w ramach [wątku](https://github.com/allegro/allegro-api/issues/7866).
