### ISSUE TITLE
Generowanie etykiety WzA

### ISSUE THREAD

**Issue by mstrojecki** [allegro/allegro-api#6774]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Podczas generowania etykiety WzA dla zamówienia [8018b880-b1c9-11ed-8391-9b7fb3f36399](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/8018b880-b1c9-11ed-8391-9b7fb3f36399)
dostajemy response:

Response:
            array
            (
                ['id'] => '6abfc1b8 - 5ca2 - 47c5 - 8ec5 - 55f873de4dcf',
                ['parcelId'] => '',
                ['status'] => 'ERROR',
                ['errors'] => array
                (
                    [0] => array
                    (
                        ['code'] => 'ERROR',
                        ['message'] => 'Processing error',
                        ['details'] => '',
                        ['path'] => '',
                        ['userMessage'] => 'error.common.processing',
                    )
                )
            )

proszę o wskazanie przyczyny błędu.

**Comment by MartaNowaczyk** [comment]
Sprawdziliśmy i dokładny błąd to `Przesyłka nie może zostać zamówiona z powodu braku możliwości realizacji usługi przez DPD transportem drogowym dla wskazanego adresu Odbiorcy`
Merchant próbuje zamówić transport drogowy do miejscowości gdzie nie ma takiej możliwości (wyspa).

**Comment by MartaNowaczyk** [comment]
Rozumiem, staramy się, aby nasze komunikaty były czytlene, dlatego pracujemy nad odpowiednim mapowaniem. Kwestie zakupu to już niestety nie kwestia API, więc możesz zgłosić to przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=713f3db7-e741-4fba-9404-09ee86a58e6c).
