### ISSUE TITLE
Integracja API brak treści na Allegro, które znajdują się w feedzie

### ISSUE THREAD

**Issue by patrickc1990** [allegro/allegro-api#6776]
Hope you are well

We are submitting titles in our product feed that are currently not being used by Allegro and I want to understand why. These changes are not displayed on the change requests page that you sent over early last week but currently none of our titles are being used for any of the products assigned to us.

Please can you help me understand why and if there is a page on Allegro I can use to view this information.

Below is an example that is currently in our catalogue

5059404901982 - RWA553___80008L

Current title on Allegro - Polar Regatta czarny r. 34
![thumbnail_image](https://user-images.githubusercontent.com/126468082/221550559-220d9c7a-00db-469e-8b33-09d88dff33d1.jpg)

Title we are submitting to you - Regatta - Damska bluza z suwakiem Highton III
![thumbnail_image](https://user-images.githubusercontent.com/126468082/221550632-cfcfc239-7d5e-41fc-9f35-f79c4b4f21cf.png)

Why aren't our titles being used? I can see nothing, within the api feedback or on Allegro itself, indicating they are being rejected so any help understanding what is happening would be really appreciated.

**Comment by Lukasz-Zurek** [comment]
Apparently we automatically set offer title based on product name. Please send me your trace-id. I will check it out closely.

**Comment by patrickc1990** [comment]
Hi Lukasz

I believe this is it 8cc886e9-3526-40ff-8d32-be8596f7bdf9
If it's not can you tell me where to find it.

**Comment by Lukasz-Zurek** [comment]
@patrickc1990 It is not a trace-id. You should receive it in the header "trace-id", in the response of your request.

**Comment by patrickc1990** [comment]
@Lukasz-Zurek f558f73d78e0bf44

**Comment by patrickc1990** [comment]
Sorry closed in error

**Comment by Lukasz-Zurek** [comment]
I see that you have provided a different photos in your request of change proposal, so we have rejected it with a messages `"Image presents another product [...]".` We have returned `null` for the product name. You can check the report status using [GET /sale/products/change-proposals/{id}](https://developer.allegro.pl/documentation/#operation/getProductChangeProposal) with an id: 8cc886e9-3526-40ff-8d32-be8596f7bdf9.

If you have provided a product name change proposal - please send us your full request in cURL Json, using our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by patrickc1990** [comment]
Are you saying the trace-id is reporting our product name is blank? Would a title that goes over the character limit be reported like this?

I can see a title in the information we're supposed to be submitting to you so I want to see if the character limit is causing this

**Comment by Lukasz-Zurek** [comment]
It would be great to see your full request. It should not be blank/null in this situation. The limit for the name field is 150 characters. I will check it out closely and will let you know if the character limit is the case in this situation.

**Comment by patrickc1990** [comment]
I have attached a zip file that contains the product file we are submitting to you for each product. This is the example from the original message I posted

I hope this helps

[RWA553___80008L_product_allegro_pl.zip](https://github.com/allegro/allegro-api/files/10851650/RWA553___80008L_product_allegro_pl.zip)

**Comment by Lukasz-Zurek** [comment]
@patrickc1990 Ok. I have already checked this and it is nothing to do with the request. This product has name rule so you will not be able to change it at all. This is why we return `null` in the name.

**Comment by patrickc1990** [comment]
Thanks @Lukasz-Zurek  Can you expain what a name rule is because I think a lot of products have this same rule applied to them.

**Comment by Lukasz-Zurek** [comment]
@patrickc1990 Name rule is an automated rule applied on categories to generate automated product name from parameter values. You can read more about product name creating right [here](https://allegro.pl/for-sellers/how-we-create-a-product-name-m0eWLKOPKsj). There is a possibility to change the name of the product by suggesting changing the parameter values. Unfortunately we do not have any resource to check the categories for which there is a name rule.

**Comment by patrickc1990** [comment]
Thanks for the help on this. I'm going to close this comment now and look into the product name and how to request changes.
