### ISSUE TITLE
Parametry do kategorii, różne odpowiedzi na to samo zapytanie.

### ISSUE THREAD

**Issue by PiotrPiotrP** [allegro/allegro-api#6779]
- [X ] ze środowiskiem produkcyjnym / with the production environment

Podczas pobierania parametrów kategorii, response:
https://api.allegro.pl/sale/categories/76035/parameters
dostaje różne odpowiedzi co przekłada się na problem przy wystawianiu produktów.

raz dostaję kolor jako 451 a raz jako 249512. Jak dostaję jako 451 to później mam problem z wystawieniem produktu.
Nie wklejam odpowiedzi z https://api.allegro.pl/sale/categories/76035/parameters, ponieważ są za długie.
Tu są ich trace-id:
trace-id=[6860158be30706f4] kolor jako 451,
trace-id=[f01ec3d9ca37164d] kolor jako 249512

https://api.allegro.pl/sale/offers requestBody={"afterSalesServices":{"impliedWarranty":{"id":"ef9a4f06-0c6e-4dcc-9414-7390a1348f56"},"returnPolicy":{"id":"f387e0e4-6250-45bf-9bb9-37fddc657159"}},"category":{"id":"76035"},"delivery":{"shippingRates":{"id":"35ff5dd8-c6fa-495b-bfc8-e0f67ab68835"},"handlingTime":"PT24H"},"external":{"id":"stocksell_681726801"},"images":[{"url":"https://a.allegroimg.com/original/11b2ea/b1e30c8d4e15b225d29819681518"},{"url":"https://a.allegroimg.com/original/1129b1/5e6de9834a18a87efafebd977130"}],"location":{"city":"Skawina","countryCode":"PL","postCode":"32-050","province":"MALOPOLSKIE"},"parameters":[{"id":"201025","valuesIds":["201025_2521"]},{"id":"54","valuesIds":["54_5"]},{"id":"11323","valuesIds":["11323_1"]},{"id":"201017","valuesIds":["201017_2317"]},{"id":"451","valuesIds":["451_256"]},{"id":"59","valuesIds":["59_9"]},{"id":"3766","valuesIds":["3766_1"]},{"id":"1294","valuesIds":["1294_2","1294_4"]},{"id":"15851","valuesIds":["15851_1"]},{"id":"225693","values":["196433002930"]},{"id":"3786","values":["Goodthreads"],"valuesIds":["3786_85"]},{"id":"201069","valuesIds":["201069_262144"]},{"id":"18293","valuesIds":["18293_1"]}],"name":"GOODTHREADS BLUZA Z KAPTUREM ZIELONA DAMSKA L 1SXA","payments":{"invoice":"VAT"},"publication":{"startingAt":"2023-02-21T17:40:02.000Z","republish":false},"sellingMode":{"format":"BUY_NOW","price":{"amount":151.99,"currency":"PLN"}},"stock":{"available":1,"sold":0,"unit":"UNIT"},"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003ch2\u003eGOODTHREADS BLUZA Z KAPTUREM ZIELONA DAMSKA\u003c/h2\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11b2ea/b1e30c8d4e15b225d29819681518"},{"type":"TEXT","content":"\u003ch2\u003eOpis Produktu\u003c/h2\u003e\u003cul\u003e\u003cli\u003e\u003cb\u003eMarka\u003c/b\u003e Goodthreads\u003c/li\u003e\u003cli\u003e\u003cb\u003eKolor\u003c/b\u003e Zielony  \u003c/li\u003e\u003cli\u003e\u003cb\u003eSkład\u003c/b\u003e 87% bawełna 13% poliester\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka papierowa\u003c/b\u003e Tak\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka wewnętrzna\u003c/b\u003e \tTak\u003c/li\u003e\u003cli\u003e\u003cb\u003eRozmiar\u003c/b\u003e L\u003c/li\u003e\u003cli\u003e\u003cb\u003eStan przedmiotu\u003c/b\u003e Punktowe przybrudzenie na lewym rękawie.\u003c/li\u003e\u003cli\u003e\u003cb\u003eCena katalogowa\u003c/b\u003e 231,99 zł\u003c/li\u003e\u003cli\u003e\u003cb\u003eInformacje dodatkowe1\u003c/b\u003e ocieplenie wewnątrz\u003c/li\u003e\u003cli\u003e\u003cb\u003eInformacje dodatkowe \u003c/b\u003e struktura materiału wewnątrz nie jest jednolita\u003c/li\u003e\u003c/ul\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/1129b1/5e6de9834a18a87efafebd977130"}]}]},"tax":{"percentage":"23.00"}} responseBody={"id":"13306003324","name":"GOODTHREADS BLUZA Z KAPTUREM ZIELONA DAMSKA L 1SXA","category":{"id":"76035"},"product":null,"parameters":[{"id":"201025","valuesIds":["201025_2521"],"values":[],"rangeValue":null},{"id":"54","valuesIds":["54_5"],"values":[],"rangeValue":null},{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"201017","valuesIds":["201017_2317"],"values":[],"rangeValue":null},{"id":"451","valuesIds":["451_256"],"values":[],"rangeValue":null},{"id":"59","valuesIds":["59_9"],"values":[],"rangeValue":null},{"id":"3766","valuesIds":["3766_1"],"values":[],"rangeValue":null},{"id":"1294","valuesIds":["1294_2","1294_4"],"values":[],"rangeValue":null},{"id":"15851","valuesIds":["15851_1"],"values":[],"rangeValue":null},{"id":"225693","valuesIds":[],"values":["196433002930"],"rangeValue":null},{"id":"3786","valuesIds":["3786_85"],"values":["Goodthreads"],"rangeValue":null},{"id":"201069","valuesIds":["201069_262144"],"values":[],"rangeValue":null},{"id":"18293","valuesIds":["18293_1"],"values":[],"rangeValue":null}],"customParameters":null,"description":{"sections":[{"items":[{"type":"TEXT","content":"<h2>GOODTHREADS BLUZA Z KAPTUREM ZIELONA DAMSKA</h2>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11b2ea/b1e30c8d4e15b225d29819681518"},{"type":"TEXT","content":"<h2>Opis Produktu</h2><ul><li><b>Marka</b> Goodthreads</li><li><b>Kolor</b> Zielony  </li><li><b>Skład</b> 87% bawełna 13% poliester</li><li><b>Metka papierowa</b> Tak</li><li><b>Metka wewnętrzna</b> \tTak</li><li><b>Rozmiar</b> L</li><li><b>Stan przedmiotu</b> Punktowe przybrudzenie na lewym rękawie.</li><li><b>Cena katalogowa</b> 231,99 zł</li><li><b>Informacje dodatkowe1</b> ocieplenie wewnątrz</li><li><b>Informacje dodatkowe </b> struktura materiału wewnątrz nie jest jednolita</li></ul>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/1129b1/5e6de9834a18a87efafebd977130"}]}]},"compatibilityList":null,"tecdocSpecification":null,"images":[{"url":"https://a.allegroimg.com/original/11b2ea/b1e30c8d4e15b225d29819681518"},{"url":"https://a.allegroimg.com/original/1129b1/5e6de9834a18a87efafebd977130"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"151.99","currency":"PLN"},"startingPrice":null,"minimalPrice":null,"netPrice":{"amount":"123.57","currency":"PLN"}},"tax":{"percentage":"23.00","rate":"23.00","subject":null,"exemption":null,"id":"b763d782-572a-47db-8752-8b2cb32b3d0a"},"stock":{"available":1,"unit":"UNIT"},"publication":{"duration":null,"status":"INACTIVE","startingAt":"2023-02-21T17:40:00.000Z","endingAt":null,"endedBy":null,"republish":false},"delivery":{"shippingRates":{"id":"35ff5dd8-c6fa-495b-bfc8-e0f67ab68835"},"handlingTime":"PT24H","additionalInfo":null,"shipmentDate":null},"payments":{"invoice":"VAT"},"discounts":null,"afterSalesServices":{"impliedWarranty":{"id":"ef9a4f06-0c6e-4dcc-9414-7390a1348f56"},"returnPolicy":{"id":"f387e0e4-6250-45bf-9bb9-37fddc657159"},"warranty":null},"additionalServices":null,"sizeTable":null,"fundraisingCampaign":null,"promotion":{"emphasized":false,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"MALOPOLSKIE","city":"Skawina","postCode":"32-050"},"external":{"id":"stocksell_681726801"},"attachments":[],"contact":null,"validation":{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: 249512","details":"","path":"parameters","userMessage":"Missing mandatory parameters: Color."},{"code":"VALIDATION_ERROR","message":"You cannot publish offer without a related product in this category. Select from the catalog or create a new product and associate it with your offer.","details":"","path":"null","userMessage":"You cannot publish offer without a related product in this category. Select from the catalog or create a new product and associate it with your offer."}],"warnings":[],"validatedAt":"2023-02-20T11:40:29.912Z"},"b2b":{"buyableOnlyByBusiness":false},"messageToSellerSettings":null,"createdAt":"2023-02-20T11:40:29.000Z","updatedAt":"2023-02-20T11:40:29.916Z","language":"pl-PL"} trace-id=[2c2832476becb312]

Jak na razie ten problem mam tylko przy tej kategorii 76035.

Z góry dziękuję za pomoc.

**Comment by hahyes** [comment]
A więc to dlatego mam od paru tygodni jakiś rozgardiasz z kolorami... 🥇

**Comment by Lukasz-Zurek** [comment]
@PiotrPiotrP Dziękuję za zgłoszenie. Konsultuję to z zespołem odpowiedzialnym za te funkcjonalności. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@PiotrPiotrP Wskazana kategoria i parametr "Kolor" były w trakcie migracji z 451 na nowy identyfikator 249512 i została już zakończona 20 lutego. Niemniej jednak tego typu sytuacje mogą się niestety powtarzać w przypadku innych podkategorii. Jest to sytuacja tymczasowa. Z góry przepraszamy za te utrudnienia.

**Comment by PiotrPiotrP** [comment]
Dziękuję za odpowiedź.
