### ISSUE TITLE
[REST] Sposób działania /order/checkout-forms/{id} 

### ISSUE THREAD

**Issue by kiczek** [allegro/allegro-api#678]
Dzień dobry,

do naszego oprogramowania pobieramy wszystkie zamówienia ze statusem _BOUGHT_. Ze względu na specyficzny sposób działania nie potrzebujemy informacji o sposobie dostawy i wypełnionego FOD, interesują nas tylko zamówienia dokonane na aukcji.

Po wykonaniu **GET /order/events** z aktywnym filtrem _BOUGHT_ otrzymujemy pole checkoutForm z ID. Po otrzymaniu danych zapisujemy wartość tego pola i odpytujemy **GET /order/checkout-forms/ID** w celu sprawdzenia, czy płatność dotarła.

Po wypełnieniu FOD dla tylko jednego zamówienia wszystko działa prawidłowo. Inaczej jest w przypadku wypełnienia FOD dla 2 zamówień. Do czasu gdy FOD nie jest dla nich wypełniony **GET /order/checkout-forms/ID** działa prawidłowo. Gdy wypełnimy jeden FOD dla 2 zamówień i odpytamy API zwracany jest błąd: _{"errors":[{"code":"ERROR","message":"An error has occurred","path":"/order/checkout-forms/a4011d82-c567-11e8-80d8-8ba957709881"}]}_ (trace: https://pastebin.com/3AaXgrye).

Proszę o informacje:
Dlaczego w ww. sytuacji zwracany jest błąd?
Czy po ID zamówienia, które znajduje się w _lineItems_, można sprawdzić status płatności?
Czy ID zamówienia, które znajduje się w _lineItems_, można powiązać z FOD?
Czy po ID z checkoutForm uzyskanym ze zdarzenia o typie _BOUGHT_ można sprawdzić status płatności?

**Comment by PawelTaberski** [comment]
Podeślij nam przez formularz kontaktowy pełnego cURL-a i responsa, a także trace-id sprawdzimy w czym jest problem. Więcej informacji odnośnie obsługi zamówień przez REST API znajdziesz [tutaj](https://developer.allegro.pl/orders/).  Szczegóły zamównia pobierzesz po identyfikatorze zamówienia. W szegółach zamówienia otrzymasz informacje o statusie płatności.

**Comment by kiczek** [comment]
Wiadomość została wysłana.
