### ISSUE TITLE
Wersjonowanie API, a pole version w swagger.yaml

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#6780]
Witam,
Chciałem zapytać dlaczego nie wersjonujecie API w widoczny sposób?
W changelogu są tylko daty zmian, a w swagger.yaml pole version ustawione jest na latest.

**Comment by MartaNowaczyk** [comment]
Rozumiem, że chciałbyś wiedzieć dokładna wersję swaggera zamiast "latest", czyli mieć informacje czy coś się zmieniło?
Kiedyś podjęliśmy wewnętrzną decyzję, że wygląda to w ten sposób. Aktualnie jesteśmy w trakcie ustalania czy nie wprowadzić tutaj zmian.

**Comment by dol1234** [comment]
Tak to na ogół działa i nie bardzo jest się nad czym zastanawiać. Można wtedy po ludzku wersjonować DTO i szybko sprawdzić czy były zmiany w API. Teraz muszę porównywać yamla i szukać różnic.

**Comment by MartaNowaczyk** [comment]
Rozumiem, tak jak pisałam - mamy to na uwadze, także jeśli się coś zmieni damy znać.
