### ISSUE TITLE
Auth | Device Flow | Token Polling | missing header

### ISSUE THREAD

**Issue by Jehezkel** [allegro/allegro-api#6782]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [x] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
W dziale Device flow jest błąd:
4b. Równocześnie twoja aplikacja powinna zacząć odpytywać zasób:

curl -X POST \
'https://allegro.pl/auth/oauth/token?grant_type=urn:ietf:params:oauth:grant-type:device_code&device_code={device_code}' \
  -H 'Authorization: Basic base64(clientId:secret)

Curl w takiej postaci zostanie odstrzelony z kodem 400 - invalid request  - brakuje informacji o headerze:
 -H 'Content-Type: application/x-www-form-urlencoded' \
ktory rowniez jest wymagany.

**Comment by MartaNowaczyk** [comment]
Dzięki za zgłoszenie, sprawdzimy i poprawimy.
