### ISSUE TITLE
Brak eventu OFFER_CHANGED przy edycji cennika dostaw

### ISSUE THREAD

**Issue by mstrojecki** [allegro/allegro-api#6785]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Zmiana jedynie cennik dostaw z poziomu przeglądarki, nie powoduje wysłania eventu o typie OFFER_CHANGED.
Wysyłany jest jedynie OFFER_STOCK_CHANGED oraz kilka eventów OFFER_TRANSLATION_UPDATED.

Problem polega na tym, że zaburza to w naszej integracji komunikację Allegro -> Integracja, która uruchamia aktualizację oferty, w momencie otrzymania eventu OFFER_CHANGED, a ten nie pojawia się w przypadku edycji samego cennika dostaw.

Prosiłbym o wytłumaczenie braku eventu OFFER_CHANGED oraz po co wysyłane są OFFER_STOCK_CHANGED i OFFER_TRANSLATION_UPDATED. Ewentualnie proszę o wskazanie sposobu na wykrycie zmiany samego cennika dostaw.

**Comment by Lukasz-Zurek** [comment]
Nie generujemy eventów dotyczących zmiany cennika dostawy czy też czasu wysyłki w ofercie.

Jeśli chodzi o eventy OFFER_STOCK_CHANGED i OFFER_TRANSLATION_UPDATED - czy miałeś sytuację, w której ów eventy wysłane zostały pomimo braku zmiany stocka, czy też tłumaczenia w ofercie?

**Comment by mstrojecki** [comment]
> Nie generujemy eventów dotyczących zmiany cennika dostawy czy też czasu wysyłki w ofercie.

To jak mam w takim razie wykryć zmiany w tej kwestii?

> Jeśli chodzi o eventy OFFER_STOCK_CHANGED i OFFER_TRANSLATION_UPDATED - czy miałeś sytuację, w której ów eventy wysłane zostały pomimo braku zmiany stocka, czy też tłumaczenia w ofercie?

No własnie dokładnie taką sytuację opisałem. Sprawdziłem też przed chwilą zmianę Czasu wysyłki.
1) Cennik dostaw - dostałem OFFER_STOCK_CHANGED i kilka OFFER_TRANSLATION_UPDATED
2) Czas wysyłki -  dostaełem OFFER_STOCK_CHANGED

**Comment by Lukasz-Zurek** [comment]
@mstrojecki Nie udostępniamy obecnie możliwości wykrycia zmian np. cennika dostawy w eventach. 

Jeśli chodzi o pozostałe kwestie - konsultuję to z zespołem odpowiedzialnym za te funkcjonalności. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@mstrojecki W przypadku zmiany cennika dostaw, lub/i czasu wysyłki - zwracamy OFFER_STOCK_CHANGED. 

Jeśli chodzi o zwracany event: OFFER_TRANSLATION_UPDATED - potrzebowalibyśmy konkretnego przykładu, np. numer oferty i informacji czy sytuacja się powtarza.

**Comment by relains** [comment]
> W przypadku zmiany cennika dostaw, lub/i czasu wysyłki - zwracamy OFFER_STOCK_CHANGED.

I to według Państwa jest w porządku? Chętnie posłucham jakiegoś logicznego wytłumaczenia, bo ja go znaleźć nie potrafię.

**Comment by Lukasz-Zurek** [comment]
@mstrojecki @relains Nie, nie powinno to tak funkcjonować. Wyjaśnię te kwestie.

Przepraszamy za powyższe utrudnienia.

**Comment by Lukasz-Zurek** [comment]
@mstrojecki @relains Podeślijcie proszę przykładowe identyfikatory ofert ze środowiska produkcyjnego.

**Comment by Lukasz-Zurek** [comment]
Problem dotyczący eventową zgłosiłem do odpowiedniego zespołu, który pracuje nad wyeliminowaniem tych utrudnień.

Jak tylko sytuacja wróci do normy - poinformuję bezpośrednio w tym wątku.

**Comment by Lukasz-Zurek** [comment]
@mstrojecki Zespół odpowiedzialny za eventy nadal pracuje nad rozwiązaniem problemu z eventami: OFFER_STOCK_CHANGED. Jednocześnie chciałbym się zapytać czy sytuacja dotycząca OFFER_TRANSLATION_UPDATED nadal występuje? Jeżeli tak - poprosimy o możliwie jak najwięcej szczegółów, np. przykładowy numer oferty, datę, etc.

**Comment by Lukasz-Zurek** [comment]
Po naszej stronie wdrożyliśmy już poprawkę i w opisanych sytuacjach nie powinniśmy już zwracać eventów OFFER_STOCK_CHANGED.

Przepraszam za zaistniałe utrudnienia.

**Comment by mstrojecki** [comment]
> Po naszej stronie wdrożyliśmy już poprawkę i w opisanych sytuacjach nie powinniśmy już zwracać eventów OFFER_STOCK_CHANGED.
> 
> Przepraszam za zaistniałe utrudnienia.

Ok, dziekuję. 


Mam jeszcze pytanie: czy jest wysyłany jakiś event w momencie kiedy oferta jest zakwalifikowana do programu Allegro Ceny? A jeśli tak to jaki?

**Comment by Lukasz-Zurek** [comment]
@mstrojecki Z dostępnych mi informacji, w tej sytuacji nie jest zwracany żaden konkretny event. Pozwól jednak, że skonsultuję jeszcze tę kwestię z odpowiednim zespołem.

**Comment by Lukasz-Zurek** [comment]
@mstrojecki W odpowiedzi na [GET /sale/offer-events](https://developer.allegro.pl/documentation/#operation/getOfferEvents) nie zwrócimy zdarzenia o zmianie ceny w ofercie w wyniku jej zakwalifikowania do programu.

**Comment by mstrojecki** [comment]
> @mstrojecki W odpowiedzi na [GET /sale/offer-events](https://developer.allegro.pl/documentation/#operation/getOfferEvents) nie zwrócimy zdarzenia o zmianie ceny w ofercie w wyniku jej zakwalifikowania do programu.

Ok, a czy jest zwracany jakikolwiek inny event, np. OFFER_CHANGED ?? Generalnie to interesuje mnie cokolwiek, co pozwoliłoby mi jakoś złapać moment, kiedy oferta kwalifikuje się do programu oraz kiedy jest z niego usuwana.
Endpoint [https://api.{environment}/sale/badges](https://api.%7Benvironment%7D/sale/badges) jest troche niewygodny, bo zwraca wszystkie "badges", które musiałbym za każdym razem parsować. Mógłby prosić o jakieś sugestie, jak to ugryźć?

I kolejna sprawa, czy można jakoś na sandboxie zasymulować kwalifikację oferty do programu Allegro Ceny?

**Comment by Lukasz-Zurek** [comment]
Jeżeli oferta zostanie zakwalifikowana do tego programu, nie zmienimy ceny w jej strukturze, dlatego w tym przypadku nie jest wysyłany jakikolwiek event. Tym samym rozróżnienie tego będzie problematyczne, a innej możliwości aniżeli /sale/badges - nie ma.

Dopytam jeszcze o możliwość przetestowania kwalifikacji oferty do programu Allegro Ceny na sandboxie. Wkrótce wrócę z odpowiedzią.

**Comment by mstrojecki** [comment]
Prosiłbym o oznaczenie nastepujących ofert jako zakwalifikowanych do Allegro Ceny:
7701810088, 7702070917, 7702015022, 7702026519, 7702015271

**Comment by Lukasz-Zurek** [comment]
@mstrojecki Przekazałem Twoją prośbę do odpowiedniego zespołu. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@mstrojecki Przepraszam za bardzo długi czas oczekiwania na odpowiedź. Zgłosiłem to wcześniej do odpowiedniego zespołu. Niestety występowały problemy techniczne, które nie pozwalały nam na zakwalifikowanie ofert testowych do programu "Allegro Ceny". Udało się jednak wyeliminować utrudnienia i przed momentem wszystkie wskazane oferty zostały zakwalifikowane.
