### ISSUE TITLE
Brak połączenia WAPRO

### ISSUE THREAD

**Issue by eMustang** [allegro/allegro-api#6786]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by eMustang** [comment]
Dzień dobry
Mam u Państwa konto "emustang"

Z Państwa kontem sprzedażowym łączę się za pomocą programy WAPRO.
Teraz gdy się chcę przez ten program zalogować wyskakuje mi taki błąd ( w załączeniu) i nie mogę się połączyć.
Kontaktowałem się z serwisem programu ale powiedzieli mi że to Państwa komunikat i abym się z Państwem skontaktował.

Bardzo proszę o pomoc
![IMG_3461](https://user-images.githubusercontent.com/126703487/222210051-1f373bda-b81b-4d59-b5cc-229e76b738d8.jpg)

**Comment by MartaNowaczyk** [comment]
Dzień dobry, sprawdzamy przyczynę blokady. Jak tylko uda nam się coś ustalić wrócę z informacją.

**Comment by eMustang** [comment]
Dzień dobry. Dziś sprawdzałem i już działa, dziękuję za pomoc.. W razie jak by znów coś nie działało pozwolę sobie do Państwa napisać.
Pozdrawiam
Sylwester Szyszko

**Comment by MartaNowaczyk** [comment]
Dzień dobry, dziękuję za informację.
