### ISSUE TITLE
Błąd generowania paczki pocztex WzA

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#6788]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Mam problem z nadaniem paczki "Allegro Odbiór w Punkcie Pocztex pobranie" (128e2be0-a2b9-4793-aafd-ec5557273786#2fba3b40-015c-48f4-a7e2-6bf6058a6ce5)

traceid : 97754ed5-ff87-452b-b4e1-1d09283a8fef

błąd : "Produkt Pocztex Kurier 48 (przesyłka biznesowa 852 nie znajduje się na umowie z Pocztą Polską)"
Co ciekawe generując na wza od frontu tego błędu nie ma..

**Comment by MartaNowaczyk** [comment]
Do wybranej metody powinieneś wybrać odpowiednią usługę dodatkową. Czyli dla `additionalServices.options` podaj wartość "pocztex".

**Comment by paafcioc22** [comment]
@MartaNowaczyk dziękuję. Czy jest gdzieś o tym mowa w dokumentacji/poradniku? Nic takiego nie znalazłem.

**Comment by hahyes** [comment]
> Do wybranej metody powinieneś wybrać odpowiednią usługę dodatkową. Czyli dla `additionalServices.options` podaj wartość "pocztex".

@MartaNowaczyk Przepraszam, ale od kiedy? To jest coś absolutnie nowego i pierwsze słyszę, by te metody dostawy wymagały podawania jakichś usług dodatkowych. Proszę o pełne źródło informacji dla całego Pocztex 2.0.

**Comment by MartaNowaczyk** [comment]
@hahyes Wymagamy, bo Pocztex 2.0 to jest inna usługa Poczty Polskiej niż Pocztex Kurier 48 i zaznaczenie tego jest wymagane, aby paczka została nadana jako Pocztex 2.0. 
Wysyłaj z Allegro nie wspiera jeszcze Pocztex 2.0 na umowach własnych, ale informacja o tym, że to "mamy w planach" była prawdziwa. Chcemy to udostępnić jeszcze przed końcem marca.
