### ISSUE TITLE
Kampanie i programy z poziomu API

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6789]
Czy do zasobów, które są prezentowane w zakładce Allegro: "Kampanie i programy" jest dostęp z poziomu API? Chodzi mi o możliwość pobierania listy ofert z danej kampanii oraz o możliwość przystępowania do kampanii

**Comment by MartaNowaczyk** [comment]
W naszym [poradniku](https://developer.allegro.pl/tutorials/jak-przypisac-oferte-kampanii-GRaj0q6Gwuy) dotyczącym kampanii powinieneś znaleźć potrzebne Ci informacje.
