### ISSUE TITLE
Metody dostawy o identycznych guidach. 

### ISSUE THREAD

**Issue by riepa** [allegro/allegro-api#679]
Metody dostawy o guidzie 2488f7b7-5d1c-4d65-b85c-4cbcf253fd93 oraz b20ef9e1-faa2-4f25-9032-adbea23e5cb9 mają nazwę: Allegro Paczkomaty 24/7 InPost
a 685d8b40-2571-4111-8937-9220b1710d4c i 2653ca13-67c8-48c3-bbf8-ff9aa3f70ed3 maja nazwę:
Paczkomaty 24/7

**Comment by riepa** [comment]
Widzę że to nie jedyne metody dostawy których to dotyczy. to samo jest w:
-Allegro Kurier24 InPost
-Allegro miniKurier24 InPost
-Kurier InPost
-PACZKA W RUCHu
-Paczka24 Odbiór w Punkcie
-Paczka48 Odbiór w Punkcie

**Comment by riepa** [comment]
przypominam że już zgłaszałem kiedyś podobny problem (https://github.com/allegro/allegro-api/issues/577) co pokazuje jak bardzo przydał by się dodatkowy parametr z oznaczeniem przesyłki pobraniowej.

**Comment by PawelTaberski** [comment]
Wiemy o tym problemie i pracujemy nad jego rozwiązaniem. Dodamy taką informację czy przesyłka jest pobraniowa. Proszę o cierpliwość. Jak tylko będziemy znali konkretną datę wdrożenia, to poinformujemy o tym.
