### ISSUE TITLE
Weryfikacja konta biznesowego

### ISSUE THREAD

**Issue by siarkopol112** [allegro/allegro-api#6790]
Proszę o aktywację konta biznesowego - "skleptest" - mail: skleptest@siarkopol.pl

**Comment by Lukasz-Zurek** [comment]
Musisz jeszcze [ustawić wypłaty](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty) i ponownie uzupełnić formularz danych i załączyć dokumenty (fikcyjne) firmy oraz wykonać przelew online (za pośrednictwem naszego symulatora płatności).

**Comment by siarkopol112** [comment]
Czy konieczne jest podanie poprawnego numeru IBAN czy macie jakiś testowy który przechodzi weryfikacje?

**Comment by Lukasz-Zurek** [comment]
Możesz skorzystać z generatora IBAN i wprowadzić losowy. Nie powinno być z tym problemu.

**Comment by siarkopol112** [comment]
Temat ogarnięty, proszę o weryfikację

**Comment by Lukasz-Zurek** [comment]
@siarkopol112 Konto zweryfikowałem.
