### ISSUE TITLE
Weryfikacja konta biznesowego sandbox

### ISSUE THREAD

**Issue by mstrojecki** [allegro/allegro-api#6791]
Poproszę o weryfikację konta biznesowego na sandbox'ie:
Login: sandbox-apteka
Email: allegro-sandbox-apteka@olmed.net.pl

**Comment by Lukasz-Zurek** [comment]
@mstrojecki Konto jest już w pełni zweryfikowane.

**Comment by mstrojecki** [comment]
dzieki
