### ISSUE TITLE
API Allegro - niepoprawne oferty (opisy, rozmiary, zdjęcia)

### ISSUE THREAD

**Issue by justynapalka** [allegro/allegro-api#6793]
Występuje problem: 
 - [ ] z zasobem REST API 
 - [ ] ze środowiskiem produkcyjnym / with the production environment

:beetle: **- Czy mogę prosić o weryfikację poniższych ofert dla konta?
Wg informacji, które mam od developerów w feedzie produktowym, który przekazujemy przez API, wszystkie informacje są poprawne.
Proszę o informacje, co blokuje przekazanie informacji dla poniższych ofert.
Przykłady:
13156722032 produkt Stormbreak z błędnym tytułem (od innego produktu, tj. Daysha), brak opisu
13345820350 produkt Birchdale, opis od innego resellera
13313226006 produkt Corinne, opis z innego produktu z feeda tj. Fuse up, podpięte rozmiary innych produktów.

Z góry dziękuję za pomoc.**

**Comment by Lukasz-Zurek** [comment]
@justynapalka Zweryfikuję zgłoszenie i wkrótce wrócę do Ciebie z informacją.

**Comment by justynapalka** [comment]
Dzień dobry, czy mamy jakiś update w tym temacie? Z góry dziękuję

**Comment by Lukasz-Zurek** [comment]
@justynapalka Sprawdziłem wskazane oferty. Wszystko wskazuje na to, że dane produktów mogą być nieprawidłowe, lub niespójne z tym co wystawiasz. Np. w przypadku oferty 13156722032 - podpięty produkt nie ma opisu, natomiast w przypadku oferty 13313226006 opis należy najprawdopodobniej do innego produktu.

Jeżeli w danych produktów są rozbieżności/nieprawidłowe dane - możesz zgłosić błędy w produktach. Tę funkcjonalność opisujemy dokładnie w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-zglosic-blad-w-produkcie).

Natomiast jeżeli otrzymujesz jakiekolwiek błędy po naszej stronie w trakcie procesu wystawiania za pośrednictwem API, do dokładnej weryfikacji potrzebować będziemy przynajmniej trace-id oraz request i response, które możesz przesłać przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #6793.
