### ISSUE TITLE
Proponowanie produktu - błąd

### ISSUE THREAD

**Issue by glinkaa** [allegro/allegro-api#6794]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Przy próbie utworzenia produktu poprzez zasób sale/product-proposals otrzymuje komunikat "Błąd przetwarzania żądania. Product with id 760496a5-52ce-4184-8d81-d0699b2bcddf not found". Z tego co widze w Allegro to produkt o takim id istnieje.

trace-id 93e9c9943059015c

**Comment by Lukasz-Zurek** [comment]
Dziękuję za szczegółowe informacje. Zgłosiłem to dalej do weryfikacji.

**Comment by Lukasz-Zurek** [comment]
Produkt ten faktycznie zwracamy jednak już pod innym identyfikatorem: 730f4bb6-74aa-46f0-bf6a-6d8ec51c6307 (to efekt połączenia 760496a5-52ce-4184-8d81-d0699b2bcddf i 730f4bb6-74aa-46f0-bf6a-6d8ec51c6307, efektem końcowym jest wskazany powyżej produkt. Przepraszamy jednak za utrudnienia, ponieważ sam komunikat może nie być do końca jasny.
