### ISSUE TITLE
Problem z wysyłką do InPost Paczkomat

### ISSUE THREAD

**Issue by marekbarczyk123** [allegro/allegro-api#6795]
Dzień dobry,

Mamy problem polegający na tym, że nie możemy wysłać InPostem paczki pod adres, który klient podał na aukcji.

Id transakcji:
3988b96b-c30e-4fc6-aeed-2397b5821fdd

Usługa:
INPOST_PACZKOMAT

ID access pointa:
OSO01M

Błąd:
Message: Order cannot be send using selected delivery service

**Comment by MartaNowaczyk** [comment]
Otrzymany komunikat mówi, że przesyłka nie została nadana metodą dostawy zgodną z wyborem kupującego. Wszelkie dostępne metody dostawy na danym koncie sprzedającego znajdziesz przy użyciu [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices). Jeśli to sprawdzisz, a problem nadal będzie występował podaj trace-id dla wywołania z błędem.

**Comment by marekbarczyk123** [comment]
Dziękuję za odpowiedź. Rozumiem komunikat. :)
Na testowym środowisku widziałem go bardzo, bardzo często, tworząc na sandboxie zamówienia gdzie mogłem wybrać dany AP inpostu na mapie, a nie mogłem tam potem zrealizować wysyłki przez API. 

Sprawdziliśmy na koncie i widzimy, że klient na auckji wybrał metodę Allegro Paczkomaty Inpost.
Taką metodę wysyłamy w requeście. ID pobrany z Państwa API to 2488 i jest zmapowany z Allegro Paczkomaty InPost (InPost).

Prośba o sprawdzenie.
ID requestu z dzisiaj 9ae19d92-c471-4307-9871-90b5eeb16ede.

Z góry dziękuję za pomoc!

**Comment by MartaNowaczyk** [comment]
Już jakiś czas temu [informowaliśmy](https://developer.allegro.pl/news/wysylam-z-allegro-20-lutego-2023-zakonczymy-wsparcie-dla-obslugi-starych-identyfikatorow-uslug-dostawy-RdLjPjoORHE), że zakończymy wsparcie dla starych identyfikatorów dostawy.

**Comment by MartaNowaczyk** [comment]
Podsyłam jeszcze [informację](https://developer.allegro.pl/news/wysylam-z-allegro-zmienimy-identyfikatory-uslug-dostawy-BvMdq20KEIm) o zmianach w identyfikatorach z września.

**Comment by marekbarczyk123** [comment]
Czy taka informacja została w jakiś sposób wysłana do użytkowników API?

**Comment by MartaNowaczyk** [comment]
Wszystkie informacje na temat zmian w API Allegro, są wysyłane do użytkowników API dedykowanymi kanałami:
- na [GitHubie](https://github.com/allegro/allegro-api/issues?q=is%3Aissue+is%3Aopen+label%3Anews) - możesz filtrować po label: news,
- na [stronie REST API Allegro](https://developer.allegro.pl/news),
- możesz zapisać się do [newslettera](https://developer.allegro.pl/newsletter), jeśli jeszcze tego nie zrobiłeś - dostaniesz informację prosto na maila.

**Comment by marekbarczyk123** [comment]
Poprawiłem kod i działa, dziękuję za pomoc!
