### ISSUE TITLE
Product change requests - Why are they rejected?

### ISSUE THREAD

**Issue by patrickc1990** [allegro/allegro-api#6796]
Hi 

We have recently opened a business Allegro account for Regatta and have started to send through our product information. The content we are supplying is being reviewed for changes against the master catalogue and is being rejected as it doesn't match what is in the master catalogue but upon reviewing our information the master catalogue is wrong.

It seems to be very inconsistent and very hard to understand why it happens.

We have tried to query the results but they also get rejected. How do we change this so the information displaying against our products is correct?

We have examples of rejections of Blank images being replaced by the correct images, 
![index-1](https://user-images.githubusercontent.com/126468082/222478535-6e45774e-6808-44f5-be05-990ac624d545.png)

Wrong parameter information being updated with the correct information
![index](https://user-images.githubusercontent.com/126468082/222478798-54216ff5-b301-4f9a-88df-094f03f0c120.png)

Images and incorrect product information - Images accepted this time but product code change was rejected
![index](https://user-images.githubusercontent.com/126468082/222478938-1cb84faa-e5a8-4749-8966-99d507424444.png)

Can you help me understand how or why this happens and how to fix this?

Thanks
Patrick

**Comment by MartaNowaczyk** [comment]
We are providing API support here, so please provide me trace-id for this call. I will check it out closely in our logs. 
If you are making changes by the website, please contact us via the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e).

**Comment by MartaNowaczyk** [comment]
Ok, thanks. I need to check these cases closely, I will come back with information.

**Comment by MartaNowaczyk** [comment]
The specified requests from the API side are correct (does not return an error, works fine). As API support, we are not responsible for whether the product change is accepted or rejected. You can find out more about the product change proposal from [our allegro support](https://allegro.pl/pomoc/kontakt?kategoria=b469d1bc-4353-4e65-a65b-6cac33aa595b), which is handling it.
