### ISSUE TITLE
Api i Super Cena

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6797]
Czy gdzieś z poziomu API jestem w stanie otrzymać informację, że moja oferta posiada oznaczenie SUPER CENA, albo aktualnie jest obniżona cena w programie Allegro Ceny?

**Comment by MartaNowaczyk** [comment]
Nic się nie zmieniło w tej kwestii od naszego ostatniego wątku #5983, także nie widać z poziomu API, że oferta ma to oznaczenie oraz tego, że cena jest obniżona.
