### ISSUE TITLE
Problem z usługą packeta przy tworzeniu listu?

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#6798]
- [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

Przy próbie utworzenia listu przewozoweg na serviceId paczkomatów packeta (/parcel-management/parcel-create-commands) otrzymuje błąd 
":[{"code":"ANOTHER_SERVICE_NOT_AVAILABLE","message":"One of required services is unavailable. Try again later.","details":"One of required services is unavailable. Try again later.","path":null,"userMessage":"One of required services is unavailable. Try again later."}

trace-id: 221e801dfdcb1d04 - Odczytanie rezultatu
trace-id: 7102583ece9eccbf - Utworzenie akcji tworzenia parcelu

Prosił bym o wyjaśnienie czym jest spowodowany i jak go rozwiązać.

**Comment by MartaNowaczyk** [comment]
Wyjaśniam Twoją sprawę z zespołem odpowiedzialnym za tą funkcjonalność. Wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Problem dotyczy braku hashmaila allegro.
