### ISSUE TITLE
Pobieranie szczegółów gwarancji, reklamacji i zwrotów

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#68]
Czy istnieją metody do pobierania tych szczegółów czy tylko możemy pobierać listę ?

**Comment by MarcinLuczak** [comment]
@yncki Obecnie mamy tylko zasoby do pobierania list warunków oferty:

- [Reklamacji](https://developer.allegro.pl/documentation/#!/after-sales-service-conditions/getPublicSellerListingUsingGET)
- [Gwarancji](https://developer.allegro.pl/documentation/#!/after-sales-service-conditions/getPublicSellerListingUsingGET_2)
- [Zwrotów](https://developer.allegro.pl/documentation/#!/after-sales-service-conditions/getPublicSellerListingUsingGET_1)

Nie istnieją metody do pobierania szczegółów tych warunków.
