### ISSUE TITLE
Logowanie do allegro - dane z wielu kont

### ISSUE THREAD

**Issue by omecon-allegro** [allegro/allegro-api#680]
W jaki sposób zrealizować scenariusz kiedy chcemy pobrać dane dla kilku kont allegro? W jaki sposób powiązać kod dostępu z danym użytkownikiem? Czy jest to teraz możliwe?
Mam na myśli to, że czasem sklepy mają kilka kont na allegro i chcą pobrać np. dane wysyłkowe dla wszystkich kont.
Wtedy powiedzmy logują się na pierwsze konto, ściągają dane wysyłkowe, potem następne konto itd.

**Comment by PawelTaberski** [comment]
Wszystko zależy od tego w jaki sposób skonstruujesz swój system. I jak będziesz zarządzał tokenami.  Każde z kont musi wcześniej powiązać się z Twoją aplikacją osobno. 
Pamiętaj, że każdy token możesz zdekodować otrzymasz w ten sposób m.in, identyfikator użytkownika. 
Więcej informacji odnośnie autoryzacji i uwierzytelniania znajdziesz [tutaj](https://developer.allegro.pl/auth/).

**Comment by FromAnyHole** [comment]
@omecon-allegro - jest fura niejednoznacznych rzeczy, bo część tzw. "publicznych" danych dostępna jest przy transmisji dowolnego i ważnego "access_token", a część tylko dla "access_token" konkretnego użytkownika. Generalnie trzeba się tu mocno pitolić z agregacją danych w wielu kont.

Kolejny absurd w REST-API, to niejednoznaczność w sposobie odsyłania danych, część odpowiedzi zwraca tylko nagłówek i "pusty" Content - i to nie tylko w odpowiedziach obsługi błędów, pomieszanie z poplątaniem...

**Comment by omecon-allegro** [comment]
generalnie wczesniejszy model byl taki klucz aplikacji i mozna sie bylo logowac z tym kluczem na dowolnego uzytkownika allegro.
teraz niby rejestrujemy znowu aplikacje - otrzymujemy Client ID / klucz WebAPI oraz Client Secret.
z tym pakietem jestesmy wstanei zalogowac sie na DOWOLNEGO uzytkownika.
jak wyglada dostep do danych w przypadku kiedy otrzymany Client ID i Client Secret pochodza od uzytkownika na ktorego zostaly zarejestrowane a jak w przypadku dowolnego innego uzytkownika?

**Comment by PawelTaberski** [comment]
@omecon-allegro  Nie wiem, czy dobrze Ciebie zrozumiałem, ale zestaw informacji, o którym wspomniałeś otrzymujesz przy rejestracji aplikacji. Aby Twoja aplikacja miała dostęp do allegro w imieniu użytkownika, to taki user musi się  uwierzytelnić i nadać uprawnienia twojej aplikacji, na tej podstawie otrzymujesz kod 10 sek przy pomocy którego otrzymasz token dostępowy. Przy pomocy tego tokenu możesz dokonywać operacji w imieniu użytkownika, token jest ważny 12 godzin. Możesz przedłużyć ważność tokena przy pomocy refresh tokena. Jeśli więcej użytkowników ma dostęp do Twojego konta to jeśli rozkodujesz dany token możesz sprawdzić do jakiego usera należy. Więcej na ten temat przeczytasz [tutaj](https://developer.allegro.pl/auth/).

**Comment by omecon-allegro** [comment]
Ja już czytalem ten artykuł, zalogowałem się też, jednak jest pewna nieścisłość. To może jeszcze raz.
Mamy uzytkowników A, B, C.
Użytkownik A rejestruje się i otrzymuje Client ID / klucz WebAPI oraz Client Secret.
Użytkownik B nie rejestruje się, do logowania używa client id oraz client secret użytkownika A.
Pytanie Czy jest wstanie pobrać te same dane co użytkownik A po zalogowaniu?
Czy jest to "dziura" i uzytkownik B wogole nie powinien mieć mozliwości zalogowania sie z client id oraz client secret użytkownika A? Czy może przewidujecie różne poziomy dostępu?

**Comment by PawelTaberski** [comment]
Wydaje mi się, że się nie do końca rozumiemy. Client ID to taki jakby login aplikacji a Client Secret to takie jakby hasło aplikacji i nie powinieneś podawać go nikomu. Korzystając z tych danych możesz wygenerować dla różnych użytkowników różne access_tokeny i z nich korzystając możesz obsługiwać wielu userów (dla każdego osobny access_token). Aby sprawdzić jaki token jest dla jakiego usera to tak jak pisałem musisz go rozkodować.
Odpowiadając na Twoje pytanie aby user B miał dostęp do konta usera A poprzez jego aplikacje musiałby mieć wszystkie dane client ID, secret, callback a nawet login i hasło użytkownika A do allegro.

**Comment by omecon-allegro** [comment]
Być może, staram się wywołać z POSTMAN
https://api.allegro.pl/order/events
Z dodanym nagłówkiem Authorization
O wartości: Bearer <access_token - otrzymany po logowaniu>
w odpowiedzi otrzymuje:
{
    "errors": [
        {
            "code": "NotAcceptableException",
            "message": "An error has occurred",
            "details": null,
            "path": null,
            "userMessage": "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."
        }
    ]
}

zarowno dla uzytkownika A i B

**Comment by omecon-allegro** [comment]
Z kolei po dodaniu headera
Accept
application/vnd.allegro.beta.v1+json
Dostaje odpowiedz:
{
    "error": "unauthorized",
    "error_description": "Full authentication is required to access this resource"
}

**Comment by PawelTaberski** [comment]
W pierwszym wywołaniu, tak jak zwróciłeś uwagę brak jednego nagłówka, który jest wymagany. Natomiast kolejny błąd najprawdopodobniej oznacza, że token masz na aplikację i nie korzystasz z pełnego flow OAuth, gdzie user loguje się po stronie allegro. Pobierasz token tylko na podstawie clientID, secret i flow client_credentials. W takim wypadku token nie ma kontekstu klienta. I dlatego otrzymujesz taki błąd.

**Comment by omecon-allegro** [comment]
dziekuje za pomoc udało mi się w końcu wywołać dla obu
https://api.allegro.pl/order/events
Pytanie o dekodowanie tokena. Po zdekodowaniu otrzymujemy w polu user_name id uzytkownika, czy tylko tyle bedzei dostepne? Chodzi mi o to, że chciałbym prezentować kto się zalogował a wygląda na to, że w tej chwili mogę prezentować tylko "zalogowany użytkownik o id: xxxx". Zdaje się, że żeby prezentować więcej muszę użyć jakiejs metody rest?

**Comment by PawelTaberski** [comment]
Nie przewidujemy rozbudowywać ilości danych zakodowanych w tokenie. Obecnie możesz przy pomocy metody doGetUserLogin na podstawie id usera otrzymać jego login.  W REST API nie ma jeszcze takiej możliwości.

**Comment by omecon-allegro** [comment]
Właśnie szukam i nie mogę znaleźć.
Staram się wywołać:
https://api.allegro.pl/users/1268307/ratings-summary
z takimi samymi nagłówkami jak:
https://api.allegro.pl/order/events
ale w odpowiedzi mam 406:
{
    "errors": [
        {
            "code": "NotAcceptableException",
            "message": "An error has occurred",
            "details": null,
            "path": null,
            "userMessage": "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."
        }
    ]
}

**Comment by FromAnyHole** [comment]
@PawelTaberski - oferujecie skorzystanie z metody [doGetUserLogin] na WebAPI, które to API zostanie wiosną wyłączone ?? Po dwóch latach kłamstw na temat rozwoju API, mamy bajzel jakiego nigdy wcześniej nie było...

**Comment by PawelTaberski** [comment]
@omecon-allegro Ten zasób jest w wersji public także wymaga nagłówka application/vnd.allegro.public.v1+json więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/news/2017-10-09-News_informacje_o_ocenach/).
@FromAnyHole Powoli rozbudowujemy udostępnione zasoby publicznie w REST API. Zasoby w WebAPI będziemy wygaszali stopniowo i będziemy o tym informować z odpowiednim wyprzedzeniem. Będziemy wygaszać zasoby, które mają już swój odpowiednik w REST API.

**Comment by omecon-allegro** [comment]
dziękuje jeszcze raz.
zmieniłem nagłówek i mam 404 Not found

**Comment by omecon-allegro** [comment]
hmmm mylące to mocno. 
The server has not found anything matching the Request-URI. No indication is given of whether the condition is temporary or permanent. The 410 (Gone) status code SHOULD be used if the server knows, through some internally configurable mechanism, that an old resource is permanently unavailable and has no forwarding address. This status code is commonly used when the server does not wish to reveal exactly why the request has been refused, or when no other response is applicable.
W przypadku np eventow jest pusta tablica

**Comment by PawelTaberski** [comment]
Rozumiem, a jaką odpowiedz chciałbyś otrzymać w przypadku braku danych? Respons z samymi zerami? Pytam bo chciałbym zgłosić twoją uwagę jako sugestię do odpowiedniego zespołu.

**Comment by omecon-allegro** [comment]
w przypadku events jest to pusta tablica np. Co jest sensowne. 404 jest odpowiedzią serwera zgodnie ze specyfikacją:
4xx (Client Error): The request contains bad syntax or cannot be fulfilled
404 Not Found
The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible.
wiec sugeruje blad klienta

**Comment by PawelTaberski** [comment]
Dziękuję, za sugestię przekazałem ją do odpowiedniego zespołu, jeśli zdecydujemy się wdrożyć takie rozwiązanie poinformujemy o nim.

**Comment by omecon-allegro** [comment]
jeszcze mam jedno pytanie. Zakładając że chce logować się z wielu kont. Logowanie na pierwsze konto wygląda tak jak napisaliście. Chcąc jednak zalogować się na następne od razu dostaje redirect z waszej strony do naszej ponieważ, jak domniemuje, wciąż zalogowany jest pierwszy user. Czy tego nie dałoby się zmienić? Z mojej strony nie za bardzo da się sprawdzić czy pierwszy user jest zalogowany czy go wylogować.

**Comment by PawelTaberski** [comment]
Drugi usera łączysz dokładnie tak jak pisałem wcześniej korzystając z danych dostępowych, jakie otrzymałeś przy rejestracji aplikacji. Korzystając z tych danych możesz wygenerować dla różnych użytkowników różne access_tokeny i z nich korzystając możesz obsługiwać wielu userów (dla każdego osobny access_token). Jeśli skończy się tobie ważność tokena możesz go odświeżyć na kolejne 12h przy pomocy refresha. User nie musi dawać dostępu do aplikacji za każdym razem. Jak już raz dał dostęp aplikacji można powiedzieć, ze jest on w niej cały czas zalogowany, nieważne ilu nowych userów da dostęp Twojej aplikacji. Nie powoduje to wylogowania poprzednich.

**Comment by omecon-allegro** [comment]
to co napisałeś jest zrozumiałe. chodzi mi o to że logując się do allegro z user A pozostaje on zalogowany. Wracamy do naszej aplikacji itd. I teraz chcemy zrobić to samo z user B ale ponieważ wciąż jest zalogowany wiec dostajemy od razu redirect z automatu.
 Tj idąc za instrukcją z https://developer.allegro.pl/auth/
wywołując link z punktu 1:
https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=a21...6be&redirect_uri=http://exemplary.redirect.uri
nie dostajemy okna logowania z 2 punktu a od razu redirect.

**Comment by PawelTaberski** [comment]
Rozumiem, w takim wypadku musisz przejść na stronę allegro.pl i wylogować się z usera A. Wtedy uwierzytelnianiu normalnie pokaże się okno do logowania dla usera B. Wiemy o tym problemie i pracujemy nad jego rozwiązaniem.

**Comment by FromAnyHole** [comment]
@PawelTaberski - wiecie o tym problemie i po ponad dwóch latach się dopiero zastanawiacie ?? A co z kolejną absurdalną sytuacją w całym systemie autoryzacji REST, gdzie użytkownik końcowy nie ma żadnej możliwości (poza jakimś zgłoszeniem tego do Was - o ile w ogóle na to wpadnie) anulowania wszystkich access/refresh token'ów w dowolnym momencie, bo cykl odnawiania biegnie przez 365 dni... Tego też nikt nie przewidział ?? A wystarczyło dodać jedno pole formularza na stronie, na której użytkownik końcowy wyraża zgodę na powiązanie aplikacji z jego kontem, gdzie domyślnie było by powiedzmy 30 dni, a jak ktoś ma obawy daje 7 lub mniej dni na odnawianie token'ów, albo zwyczajnie powraca do autoryzacji i deklaruje wtedy całe 365 dni.

**Comment by PawelTaberski** [comment]
@FromAnyHole  W najbliższym czasie powinniśmy wdrożyć rozwiązanie dla obu tych problemów. Prosiłbym o cierpliwość, jak tylko będziemy mieli więcej informacji poinformujemy o tym

**Comment by kuli-g** [comment]
Może nie najlepsze rozwiązanie ale ja mam 2 konta allegro i dla każdego osobno zarejestrowaną aplikację, tokeny trzymam w mysql, odświeżają się gdy wygasną. Ale cały plan w tym by skrypt ściągał dane z obu kont bez przelogowywania czy innej ingerencji użytkownika, po prostu zmienia tokeny w zapytaniach. I działa jak trzeba. Autoryzację logowaniem robiłem tylko raz jakiś miesiąc temu.

Na potrzeby własne to może działać z dowolną ilością kont, raz autoryzować i przez rok spokój.

**Comment by omecon-allegro** [comment]
> @FromAnyHole W najbliższym czasie powinniśmy wdrożyć rozwiązanie dla obu tych problemów. Prosiłbym o cierpliwość, jak tylko będziemy mieli więcej informacji poinformujemy o tym

czy jakieś ramy czasowe są przewidziane? Skoro mają zostać wyłączone metody starego API to rozumiem, że wprowadzicie te rozwiazania dużo wcześniej?

**Comment by PawelTaberski** [comment]
Jak tylko będziemy znali dokładny czas wdrożenia tych rozwiązań poinformujemy o tym. Na dzień dzisiejszy nie znam czasu wdrożenia tych rozwiązań.

**Comment by omecon-allegro** [comment]
własnie do tego wracam i zastanawiam się czemu zostało zamknięte. czy rozwiązano juz problem logowania do wielu kont? Mam na myśli że jeśli raz zalogowany użytkownik wywołując link do logowania dostaje od razu redirect. Druga rzecz czy można kodować login użytkownika w tokenie?

**Comment by PawelTaberski** [comment]
Ups, trochę z rozpędu zamknąłem, bo chciałem ogarnąć ilość tych wątków bo utrudnia to wyszukiwania i rozwiązywanie spraw. 
Odnośnie Twojego pytania jeszcze nie rozwiązaliśmy jeszcze tego pierwszego problemu, ale wiem że jest planowane wdrożenie, które będzie temu zapobiegać. Jak tylko zmiana dojdzie do skutku poinformujemy w osobnym komunikacie. 
Odnośnie drugiego pytania wszystkie tokeny zgodne są ze standardem JWT i po ich rozkodowaniu otrzymasz m.in. id usera na jaki jest ten token.

**Comment by XardasLord** [comment]
Czy problem uwierzytelniania na wielu kontach został rozwiązany przez allegro?

**Comment by MartaNowaczyk** [comment]
@XardasLord dla porządku zostawiam tu informację, że odpowiedziałam w wątku https://github.com/allegro/allegro-api/issues/789. Jeśli jeszcze jakieś inne kwestie, niż te poruszone w dodanym wątku są niejasne, doprecyzuj w nowym wątku.
