### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Marczuu** [allegro/allegro-api#6802]
Po uruchomieniu tego kodu (CLIENT_ID oraz CLIENT_SECRET usunąłem na czas demonstracji):

import requests
import json

CLIENT_ID = ".........."          # wprowadź Client_ID aplikacji
CLIENT_SECRET = ".........."      # wprowadź Client_Secret aplikacji
TOKEN_URL = "https://allegro.pl/auth/oauth/"

def get_access_token():
    try:
        data = {'grant_type': 'client_credentials'}
        access_token_response = requests.post(TOKEN_URL, data=data, verify=False,
                                              allow_redirects=False, auth=(CLIENT_ID, CLIENT_SECRET))
        tokens = json.loads(access_token_response.text)
        access_token = tokens['access_token']
        return access_token
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)

def main():
    access_token = get_access_token()
    print("access token = " + access_token)

if __name__ == "__main__":
    main()

Dostaje następującą wiadomość w terminalu:

C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'allegro.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "c:\Users\MSI\Desktop\Allegro API test\api_allegro.py", line 27, in <module>
    main()
  File "c:\Users\MSI\Desktop\Allegro API test\api_allegro.py", line 22, in main
    access_token = get_access_token()
  File "c:\Users\MSI\Desktop\Allegro API test\api_allegro.py", line 14, in get_access_token
    tokens = json.loads(access_token_response.text)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Jak mam to naprawić?

**Comment by hahyes** [comment]
@Marczuu Co do błędu:
```
InsecureRequestWarning: Unverified HTTPS request is being made to host 'allegro.pl'. Adding certificate verification is strongly advised.
```

Zapoznaj się z tym poradnikiem:
https://urllib3.readthedocs.io/en/1.26.x/user-guide.html#ssl

**Comment by Lukasz-Zurek** [comment]
@hahyes Dziękujemy za Twoje wsparcie :) @Marczuu Daj proszę znać czy problem udało się ostatecznie wyjaśnić i czy rozwiązanie zaproponowane przez **hahyes** pomogło.

**Comment by Marczuu** [comment]
Ten bląd, udało się naprawić:
InsecureRequestWarning: Unverified HTTPS request is being made to host 'allegro.pl'. Adding certificate verification is strongly advised.


Jednak wciąż dostaje taką wiadomość:

PS C:\Users\MSI\Desktop\Allegro API test>  c:; cd 'c:\Users\MSI\Desktop\Allegro API test'; & 'C:\Users\MSI\AppData\Local\Programs\Python\Python310\python.exe' 'c:\Users\MSI\.vscode\extensions\ms-python.python-2023.4.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '55837' '--' 'c:\Users\MSI\Desktop\Allegro API test\api_allegro.py' 
Traceback (most recent call last):
  File "c:\Users\MSI\Desktop\Allegro API test\api_allegro.py", line 38, in <module>
    main()
  File "c:\Users\MSI\Desktop\Allegro API test\api_allegro.py", line 33, in main
    access_token = get_access_token()
  File "c:\Users\MSI\Desktop\Allegro API test\api_allegro.py", line 25, in get_access_token
    tokens = json.loads(access_token_response.text)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads    
    return _default_decoder.decode(s)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode    
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Marczuu** [comment]
Ten problem udało się naprawić:
InsecureRequestWarning: Unverified HTTPS request is being made to host 'allegro.pl'. Adding certificate verification is strongly advised.


import requests
import json
import certifi
import urllib3

CLIENT_ID = ""          # wprowadź Client_ID aplikacji
CLIENT_SECRET = ""      # wprowadź Client_Secret aplikacji
TOKEN_URL = "https://allegro.pl/auth/oauth/"

http = urllib3.PoolManager(
    cert_reqs='CERT_REQUIRED',
    ca_certs=certifi.where()
)

def get_access_token():
    try:
        data = {'grant_type': 'client_credentials'}
        access_token_response = http.requests.post(TOKEN_URL, data=data, verify=False,
                                              allow_redirects=False, auth=(CLIENT_ID, CLIENT_SECRET))
        tokens = json.loads(access_token_response.text)
        access_token = tokens['access_token']
        return access_token
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)


def main():
    access_token = get_access_token()
    print("access token = " + access_token)


if __name__ == "__main__":
    main()


Jednak po uruchomieniu powyższego kody dostaje taki error:

PS C:\Users\MSI\Desktop\Allegro API test>  c:; cd 'c:\Users\MSI\Desktop\Allegro API test'; & 'C:\Users\MSI\AppData\Local\Programs\Python\Python310\python.exe' 'c:\Users\MSI\.vscode\extensions\ms-python.python-2023.4.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '56650' '--' 'c:\Users\MSI\Desktop\Allegro API test\api_allegro.py' 
Traceback (most recent call last):
  File "c:\Users\MSI\Desktop\Allegro API test\api_allegro.py", line 40, in <module>        
    main()
  File "c:\Users\MSI\Desktop\Allegro API test\api_allegro.py", line 35, in main
    access_token = get_access_token()
  File "c:\Users\MSI\Desktop\Allegro API test\api_allegro.py", line 25, in get_access_token
    access_token_response = http.requests.post(TOKEN_URL, data=data, verify=False,
AttributeError: 'PoolManager' object has no attribute 'requests'. Did you mean: 'request'? 


Jak zamieniłem requests na request to dostałem taki error:

PS C:\Users\MSI\Desktop\Allegro API test>  c:; cd 'c:\Users\MSI\Desktop\Allegro API test'; & 'C:\Users\MSI\AppData\Local\Programs\Python\Python310\python.exe' 'c:\Users\MSI\.vscode\extensions\ms-python.python-2023.4.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '56664' '--' 'c:\Users\MSI\Desktop\Allegro API test\api_allegro.py' 
Traceback (most recent call last):
  File "c:\Users\MSI\Desktop\Allegro API test\api_allegro.py", line 40, in <module>        
    main()
  File "c:\Users\MSI\Desktop\Allegro API test\api_allegro.py", line 35, in main
    access_token = get_access_token()
  File "c:\Users\MSI\Desktop\Allegro API test\api_allegro.py", line 25, in get_access_token
    access_token_response = http.request.post(TOKEN_URL, data=data, verify=False,
AttributeError: 'function' object has no attribute 'post'

**Comment by Lukasz-Zurek** [comment]
@Marczuu 

Popraw url w `TOKEN_URL = "https://allegro.pl/auth/oauth/"` na `"https://allegro.pl/auth/oauth/token".`

Ponadto próbujesz korzystać z biblioteki urllib3, wywołując http.requests.post, natomiast żądanie posiada inną strukturę (requests) - wskazaną przez nas w [naszym poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#autoryzacja-aplikacji), w miejscu, w którym mamy przykładowy kod (w Pythonie) dla takiego właśnie żądania.

Zdecyduj się proszę z której biblioteki korzystasz. Jeśli to będzie urllib3 - być może któryś z użytkowników forum miał już wcześniej podobny problem i będzie w stanie pomóc.
