### ISSUE TITLE
Brak dostępu. Nie masz uprawnień do operacji na wskazanej ofercie [Forbidden (OfferAccessDeniedException)]

### ISSUE THREAD

**Issue by slawoj5** [allegro/allegro-api#6803]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X ] inny / other

:beetle: **Opis / Description**

Przy próbie dodania aukcji przez SkyShop pojawia mi się poniższy komunikat z API Allegro
Brak dostępu. Nie masz uprawnień do operacji na wskazanej ofercie [Forbidden (OfferAccessDeniedException)]

**Comment by AureliuszBrussy** [comment]
Otrzymujesz błąd, ponieważ prawdopodobnie próbujesz wystawić ofertę za pomocą konta zwykłego. Zgodnie z [naszym komunikatem](https://developer.allegro.pl/news/od-dzis-oferty-przez-api-moga-wystawiac-i-edytowac-tylko-uzytkownicy-z-kontem-firmowym-9gRePwXxGiP) z ubiegłego roku, wystawiać i zarządzać ofertami przez API mogą tylko użytkownicy z kontem firmowym.

**Comment by slawoj5** [comment]
Dokładnie. Nie chcę jednak piblikować i wystawiać ofert a robić tylko szkice robocze szablonów, które bede wystawiał jak przekształcę konto zwykłe na firmowe. Czy mozecie udostępnic mi taką mozliwosc na moim nicku konta zwykłego?

**Comment by AureliuszBrussy** [comment]
Niestety, ale nie ma takiej możliwości - utworzysz szkice dopiero po przekształceniu konta.

**Comment by WSzoda** [comment]
Mam takie pytanie, czemu tak ważnej sprawy jak to, że oferta może byc edytowana tylko przez konto firmowe nie ma w dokumentacji ?

**Comment by AureliuszBrussy** [comment]
@WSzoda dziękuję za zwrócenie uwagi, zweryfikujemy to oraz zastanowimy się, gdzie dodać taką informację.
