### ISSUE TITLE
DELIVERY_METHOD_NOT_FOUND - Co oznacza?

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#6806]
- [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

Trace ids:
trace-id: 883fb06f1e1917f6 - odczytanie rezulatu
trace-id: 320c1e26c30d825c - utowrzenie parcelu

Prosił bym o wskazanie co jest uzupełniane w niepoprawny sposób przy próbie utworzenia paczki, i powoduje ten błąd:
![obraz](https://user-images.githubusercontent.com/87118074/223409796-63ef8edd-4a24-4a5f-8777-783bfdb8c6d1.png)

**Comment by MartaNowaczyk** [comment]
Jakiś czas temu [informowaliśmy](https://developer.allegro.pl/news/wysylam-z-allegro-20-lutego-2023-zakonczymy-wsparcie-dla-obslugi-starych-identyfikatorow-uslug-dostawy-RdLjPjoORHE), że zakończymy wsparcie dla starych identyfikatorów dostawy. 
Podsyłam jeszcze [informację](https://developer.allegro.pl/news/wysylam-z-allegro-zmienimy-identyfikatory-uslug-dostawy-BvMdq20KEIm) o zmianach w identyfikatorach z września.
