### ISSUE TITLE
Wymagalność parametru EAN (GTIN) w zależności od wybranej marki

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#6808]
Dzień dobry

Natrafiłem na przypadek w kategorii o id 91193, że parametr EAN (GTIN) jest wymagany lub nie w zależności od wybranej marki, np. po wyborze marki PUMA parametr staje się wymagalny, gdzie w api parametrów przechowywane są te zależności?

**Comment by Lukasz-Zurek** [comment]
Wymagalność uzależniona jest od stanu "Nowy" i konkretnych marek. Obecnie ze względów technicznych - nie zwrócimy informacji o zależności marek w odpowiedzi GET /sale/categories/{id}/parameters. Pracujemy nad zmianami, które uwzględnią te informacje. Przepraszam za te niedogodności. O wszelkich zmianach w tym zakresie będziemy informować na [naszym portalu](https://developer.allegro.pl/news) i forum.
