### ISSUE TITLE
KeyError: 'access_token'

### ISSUE THREAD

**Issue by krzysztofMajchrzak-GIT** [allegro/allegro-api#6809]
Używam waszego przykładowego kodu ze strony: https://developer.allegro.pl/tutorials/jak-zaczac-prace-z-rest-api-4RAvV2bgwtj#python

`

import requests
import json

CLIENT_ID = ""          # wprowadź Client_ID aplikacji
CLIENT_SECRET = ""      # wprowadź Client_Secret aplikacji
TOKEN_URL = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token"

def get_access_token():
    try:
        data = {'grant_type': 'client_credentials'}
        access_token_response = requests.post(TOKEN_URL, data=data, verify=False,
                                              allow_redirects=False, auth=(CLIENT_ID, CLIENT_SECRET))
        tokens = json.loads(access_token_response.text)
        access_token = tokens['access_token']
        return access_token
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)

def main():
    access_token = get_access_token()
    print("access token = " + access_token)

if __name__ == "__main__":
    main()

`

I dostaje: KeyError: 'access_token'

Moje ID to ceae3e24e5b546968ff28bc772006dc1

**Comment by krzysztofMajchrzak-GIT** [comment]
{'error': 'Unauthorized', 'error_description': 'Unauthorized'} - Do dostaje w zwrotce z API

**Comment by AureliuszBrussy** [comment]
Zarejestrowałeś aplikację na środowisku produkcyjnym, a próbujesz wykonać request na środowisku testowym (https://allegro.pl.allegrosandbox.pl/auth/oauth/token). [Zarejestruj aplikację](https://apps.developer.allegro.pl.allegrosandbox.pl/) na Sandboxie.
