### ISSUE TITLE
Sandbox - zakup jako gość - brak metody płatności

### ISSUE THREAD

**Issue by xemix** [allegro/allegro-api#681]
Podczas zakupu jako gość w Allegro Sandbox - nie można wybrać metody płatności: http://scr.hu/92hi/yom05

Nie ma żadnej metody płatności.
Możecie sprawdzić i naprawić?

**Comment by PawelTaberski** [comment]
Sprawdziłem i na środowisku testowym pojawiają się poprawnie metody płatności. Spróbuj odświeżyć stronę i wyczyścić dane przeglądarki. Napisz proszę później czy problem nadal występuje. Jeśli tak sprawdź czy pojawia się taki problem również w przypadku kupna innej oferty testowej.

**Comment by xemix** [comment]
@PawelTaberski - odświeżanie nie pomaga, cookies brak (tryb incognito otwarty pod zakup) - problem nadal występuje. Sprawdź na aukcji: https://allegro.pl.allegrosandbox.pl/doladowanie-play-10-pln-i6205657800.html

Wygląda na to, jakby moje konto nie posiadało skonfigurowanych metod płatności i dlatego podczas zakupu - po prostu ich nie ma. Czy to możliwe?

**Comment by PawelTaberski** [comment]
Przekazałem Twoją sprawę do odpowiedniego zespołu, konto masz w pełni aktywne. Sprawdzą w czym jest problem. Proszę o cierpliwość.

**Comment by xemix** [comment]
Coś się udało ustalić?

**Comment by PawelTaberski** [comment]
Z tego co widzę trwa jeszcze weryfikacja twojego zgłoszenia, proszę o cierpliwość.

**Comment by PawelTaberski** [comment]
Prosiłbym jeszcze o podesłanie pełnego zrzutu z widocznym całym FOD-em, przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). W treści zaznacz proszę, że informacje przesyłasz do zgłoszenia na GitHub-ie numer 681.
