### ISSUE TITLE
Problem z dodaniem umowy własnej WzA sandbox

### ISSUE THREAD

**Issue by tomasz3k** [allegro/allegro-api#6810]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
 
Mam problem na środowisku testowym. 
Korzystam z DCR, aplikacja zarejestrowana poprawnie. Autoryzacja wykonana poprawnie. 

Na koncie sensbit utworzyłem aukcje, następnie kupiłem ją na innym koncie testowym. Wybrałem sposób dostawy Allegro Paczkomaty Inpost. Wszystko poszło bez większych problemów.

Następnie po zalogowaniu do https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/zamowienia/
Klikam przy tym zamówieniu nadaj przesyłkę https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/wysylam/nadaj-paczke?orderId=1300e250-bd03-11ed-a37d-bba3a6b6a9d1

Wyskakuje komunikat 
Dodaj umowę własną
Aby nadać przesyłkę Allegro Paczkomaty InPost musisz dodać umowę własną. Po dodaniu umowy nadasz przesyłki wprost z Allegro według swoich indywidualnych stawek cenowych.

BTW. Myślałem, że metoda Allegro Paczkomaty Inpost będzie według cennika Allegro... ale ok. 
Klikam dodaj umowę

Jestem teraz na stronie https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/wysylam/nowa-umowa?addCarrier=inpost&redirectUrl=/moje-allegro/sprzedaz/wysylam/nadaj-paczke?orderId=1300e250-bd03-11ed-a37d-bba3a6b6a9d1

Wprowadzam nazwę umowy: test, mój klucz do środowiska produkcyjnego, zaznaczam używaj oferty dla sprzedawców allegro i klikam dodaj.

Przycisk dodaj kręci się teraz w nieskończoność, a w tle w konsoli przeglądarki mamy request  z błędem 403 https://edge.allegro.pl.allegrosandbox.pl/parcel-management-settings/carrier_contracts
A jako response 
{"errors":[{"code":"AUTHENTICATION_ERROR","message":"No access to 'Wysyłam z Allegro'","details":null,"path":"header.authorization","userMessage":"error.common.accountNotConnected"}]}

Proszę o pomoc w tym temacie oraz mam przy okazji pytania:
Które metody dostawy nie wymagają wprowadzenia umowy produkcyjnej? 
Czy jest opcja korzystania z umowy np. inpost czy poczty polskiej również w wersji sandboxowej?
Podczas opłacania zamówienia chciałem przetestować płatność blik, podałem jakiś kod, ale płatność nie została zweryfikowana poprawnie i musiałem zmienić na przelew.  Czy jest jakaś opcja przetestowania płatności blik?

**Comment by Lukasz-Zurek** [comment]
W przypadku środowiska testowego Sandbox musisz podać dane dotyczące umowy w ramach testowego ShipX i tutaj skontaktuj się w tej sprawie bezpośrednio z firmą Inpost.

Jeżeli natomiast chodzi o płatność BLIK - płatność powinna przejść z kodem: 123456.

**Comment by tomasz3k** [comment]
Problem w tym że podawałem dane do testowego API shipx i ten sam efekt sandbox dostaje 403 w tle i nie mogę dodać własnej umowy.

**Comment by Lukasz-Zurek** [comment]
Skontaktuj się proszę z Inpost, ponieważ wszystko wskazuje na to, że dane dostępowe są błędne.

**Comment by tomasz3k** [comment]
Dane dostępowe nie są błędne. Jestem autorem innej ntegracji z Inpost ShipX i od wielu lat korzystam z tego tokenu. 
Przesyłam link do filmu obrazujący problem, zwróć uwagę proszę, że to problem po waszej stronie.
https://watch.screencastify.com/v/DSfnJkVPGX6t58bnzxSV

**Comment by tomasz3k** [comment]
Dodatkowo film z dodaniem konta testowego poczty polskiej. Widać, że urzędy nadania pobrano poprawnie. Dodanie umowy kończy się tym samym błędem co dodanie umowy inpost. 
https://watch.screencastify.com/v/BxNpT5x0oCOrX1aJFQ8s

**Comment by Lukasz-Zurek** [comment]
@tomasz3k Bardzo Ci dziękuję za filmiki obrazujące te niedogodności, jak również za Twoją cierpliwość :) Przekazuję ten temat dalej do weryfikacji. Jak tylko uzyskam dodatkowe informacje - dam znać w wątku.

**Comment by tomasz3k** [comment]
Świetnie, czekam na informację zwrotną. Gdyby coś było potrzebne śmiało daj znać, postaram się uzupełnić wątek.

**Comment by Lukasz-Zurek** [comment]
@tomasz3k Błąd był po naszej stronie. Poprawiliśmy go. Daj proszę znać czy już jest ok.

**Comment by tomasz3k** [comment]
Niestety teraz jest jeszcze gorzej.
https://watch.screencastify.com/v/y92p8kbNCpNwWe5YlIYB

**Comment by Lukasz-Zurek** [comment]
@tomasz3k Rozumiem, że dodałeś umowę dla Inpostu i tu wszystko przebiegało prawidłowo tak?

**Comment by tomasz3k** [comment]
Nie, nic nie zmieniałem odkąd ostatnio nagrywałem film. Teraz nie mogę w ogóle nadawać przesyłek wyrzuca błąd jak na filmie, że nie mam dostępu do własnych zamówień.

**Comment by Lukasz-Zurek** [comment]
@tomasz3k Badamy temat. Przepraszamy za te utrudnienia.

**Comment by tomasz3k** [comment]
Czy coś wiadomo już w temacie?

**Comment by tomasz3k** [comment]
Czy wiadomo ile może to trwać mam wrażenie, że nikt nad tym nie siedzi, a u mnie praca stoi. Dramat

**Comment by Lukasz-Zurek** [comment]
@tomasz3k Przepraszam Cię za wydłużony czas oczekiwania na konkretną odpowiedź. Zapewniam Cię, że weryfikujemy ten problem. Póki co otrzymałem jedynie informację o tym, że proces zakładania konta/dodania umowy dla Inpostu - po naszej stronie zakończył się pomyślnie.  Sprawdzamy jednak przedstawione na filmiku zamówienia. Jak tylko uzyskam szczegółowe informacje - wrócę do Ciebie z odpowiedzią.

**Comment by tomasz3k** [comment]
Napiszę jeszcze raz tu nie chodzi o te zamówienia. Nie działa dodawanie umowy w ramach mojego konta. 
Problem jest związany z brakiem dostępu do usługi Wysyłam z Allegro (No access to 'Wysyłam z Allegro'").
Przez ten problem nie mogę dodać żadnej usługi własnej i musze korzystać tylko z metod "allegro". 

Tak samo jest przez restapi /parcel-management/delivery-services nie zwraca mi np. dostawy Allegro Paczkomaty, pomimo iż mam wystawiony przedmiot z taką dostawą i nawet mam zamówienie na tę dostawę. Ewidentnie moje konto nie ma wszystkich uprawnień i przez to jest problem. Problem bardzo krytyczny dla mnie i powodujący, że stoję w miejscu, a mam nad sobą presję kilkunastu klientów, którzy czekają na tę integrację.

**Comment by Lukasz-Zurek** [comment]
@tomasz3k Mieliśmy wcześniej błąd, w przypadku którego zapisywaliśmy błędne dane i to powodowało, że nasz operator zwracał komunikat, że taki użytkownik nie istnieje. Według naszych logów proces ten zakończył się pomyślnie. Czy próbowałeś ponownie skonfigurować umowę własną dla Inpostu? Jeżeli tak, doprecyzuj proszę kiedy. Czy miałeś podobne problemy jak poprzednio? Prześlij proszę jak najwięcej szczegółów potrzebnych do weryfikacji.

Zależy nam na wyjaśnieniu tego problemu, wymaga to jednak konsultacji z zespołem odpowiedzialnym za tę usługę.

**Comment by tomasz3k** [comment]
Nadal występuje ten sam problem {"errors":[{"code":"AUTHENTICATION_ERROR","message":"No access to 'Wysyłam z Allegro'","details":null,"path":"header.authorization","userMessage":"error.common.accountNotConnected"}]}

Może po prostu wejdziecie na moje konto i sobie sprawdzicie na nim bo im dłużej to trwa tym gorzej

**Comment by Lukasz-Zurek** [comment]
> Nadal występuje ten sam problem {"errors":[{"code":"AUTHENTICATION_ERROR","message":"No access to 'Wysyłam z Allegro'","details":null,"path":"header.authorization","userMessage":"error.common.accountNotConnected"}]}
> 
> Może po prostu wejdziecie na moje konto i sobie sprawdzicie na nim bo im dłużej to trwa tym gorzej

Nie mamy niestety takiej możliwości i to właśnie utrudnia nam weryfikację, a chcemy Tobie pomóc. Zespół odpowiedzialny za usługę twierdzi, że konfiguracja zakończyła się wcześniej prawidłowo. Mamy zatem wątpliwości.

1. Czy konfiguracja umowy własnej zakończyła się ostatecznie pozytywnie? Jeśli nie - poprosimy o informację i czy powtórzyła się sytuacja z filmiku nr 1.
2. Domyślam się, że nadawanie przesyłek nie działa. Poproszę o przykładowe, świeże numery zamówień, dla których próbowałeś nadać przesyłkę.

Generalnie im więcej szczegółów nam podasz - tym łatwiej będzie nam dalej wyjaśniać ten problem.

**Comment by tomasz3k** [comment]
ad 1. Cały czas filmik jest aktualny nic się nie zmieniło wyświetla się ten sam błąd przy próbie dodania umowy własnej inpost / poczty. 
ad 2. Działają tylko te allegro. Nie ma sensu podawać id zamówień bo problem nie leży po stronie zamówień, a po stronie dodawania umowy własnej z poziomu https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/zamowienia/ustawienia?sellerId=105873631

**Comment by Lukasz-Zurek** [comment]
Ok, dzięki. Przekazałem dalej.

**Comment by Lukasz-Zurek** [comment]
@tomasz3k Zresetowaliśmy dane. Spróbuj proszę ponownie dodać umowę własną.

**Comment by tomasz3k** [comment]
Umowa dodała się poprawnie. Przekierowało do https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/wysylam/nadaj-paczke?orderId=1300e250-bd03-11ed-a37d-bba3a6b6a9d1 ale nadal wyswietla się komunikat, że muszę dodać umowę własną. Tak jakby nie widziało utworzonej umowy. Próbowałem się przelogować ale bez skutku.

**Comment by tomasz3k** [comment]
Widzę, że problem został już rozwiązany. Mogę tworzyć przesyłki do paczkomatu. :-D

Natomiast zauważyłem, że w przypadku wybrania opcji Nadam paczkę w PaczkoPunkcie dostaję błąd 

> Punkt punktu nadania przesyłki jest niepoprawny
A nigdzie nie ma opcji wybrania tego punktu.

W dokumentacji api zaś nie ma nigdzie informacji w jaki sposób rozróżnić sposób nadania przesyłki https://developer.allegro.pl/documentation#operation/createNewParcel

Jest jedynie zmienna `pickup->pointId`, która ma być uzupełniona id punktu w którym nadajemy przesyłkę. 
Zauważyłem, że w waszym formularzu https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/wysylam/nadaj-paczke?orderId=1300e250-bd03-11ed-a37d-bba3a6b6a9d1 nigdzie nie podaje sie id punktu nadawcy, w zwiazku z czym pytanie czy przez api również można niepodawać punktu i zaznaczyć jedynie usługę dodatkową sendingAtPoint, co będzie oznaczało nadanie w dowolnym paczkomacie / paczkopunkcie?
