### ISSUE TITLE
Bład przy tworzeniu paczki INSURANCE_IS_MISSING

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#6811]
- [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

trace-id: 191e6f46ea013d89 - odczytanie rezultatu
trace-id: cf20ccfef68acc05 - tworzenie paczki 

Przy próbie utworzenia paczki dla wysyłki do punktu Packeta otrzymuję błąd INSURANCE_IS_MISSING. Czym jest on spowodowany i jak go rozwiązać?

**Comment by AureliuszBrussy** [comment]
@Maciej-Wilkosz zadeklaruj wartość paczki w obiekcie `items[].value`.
