### ISSUE TITLE
Parametry przesyłek dodawanych w ramach Wysyłam z Allegro

### ISSUE THREAD

**Issue by tomasz3k** [allegro/allegro-api#6812]
Witajcie,
Tworzę integrację z Wysyłam z Allegro, mam problem gdyż myślałem, że api allegro zwróci informację jakie parametry przesyłek są dostępne dla danej metody dostawy.
Np. nie znalazłem informacji w api allegro jakie są gabaryty przesyłek dla dostawy Allegro One

Można pobrać usługi dodatkowe na podstawie id metody dostawy ale nie zwracane są żadne inne według mnie potrzebne parametry. Jak podany wyżej gabaryt. 

Oprócz tego np. nie ma informacji jaki typ przesyłki można utworzyć. Czy pozostaje więc zakodowanie tych parametrów na sztywno w  integracji, czy też jest jakiś cień szansy że te parametry pojawią się w api bądź już są tylko nikt o tym nie wie?

**Comment by MartaNowaczyk** [comment]
Nie zwracamy w API takich informacji jak gabaryty.  Z dostępnych mi danych wynika, że nie planujemy takiej zmiany w najbliższej przyszłości.. Dostępne typy przesyłki znajdziesz w [dokumentacji](https://developer.allegro.pl/documentation/#operation/createNewParcel).

**Comment by tomasz3k** [comment]
Bardzo ułatwiłoby to pracę gdyby gabaryty pojawiły się np. w odpowiedzi https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices

Proszę uwzględnić sugestię w przyszłości

**Comment by MartaNowaczyk** [comment]
Dodaj proszę Twoją sugestię w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions), gdzie zbieramy potrzeby.
