### ISSUE TITLE
Aktualizacja EAN przez PATCH sale/product-offers/{id}

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#6815]
Witam,

Chciałbym się dowiedzieć, czy za pomocą zasobu PATCH sale/product-offers/{id} mogę zaktualizować ofertę o brakujący EAN.

Mam aukcję Allegro:
- jest powiązana z produktem, 
- produkt posiada EAN
- aukcja nie posiada EAN (komunikat _Uzupełnij parametry obowiązkowe: EAN (GTIN)._)
- aukcja na serwerze produkcyjnym `GET https://api.allegro.pl/sale/offers/{id} || trace-id:a151156301a72323`

Przy próbie aktualizacji jako parametr aukcji
`{"parameters":[{"id":"225693","values":["$ean"]}]}`
Otrzymuję błąd 
```
    +"code": "ParameterCategoryException"
    +"message": "Unprocessable Entity"
    +"details": null
    +"path": "parameters"
    +"userMessage": "Błędnie przesłano definicje parametru `225693:EAN (GTIN)` jako parametr w sekcji `offer`."
```

Co jest zrozumiałe - EAN jest wartością opisującą produkt https://github.com/allegro/allegro-api/issues/5362#issuecomment-1022875593

Dlatego chciałem przesłać EAN jako cechę produktu
`PATCH sale/product-offers/{id} || trace-id:75b8001120b9a37e`
`{"productSet":[{"product":{"parameters":[{"id":"225693","values":["$ean"]}]}}]}`
Otrzymuję błąd o braku uzupełnienia pozostałych parametrów
```
ConstraintViolationException.MissingRequiredParameters
ProductConstraintViolationException.DataIntegrity

```

1. Czy aby zaktualizować EAN oferty wystarczy jak pobiorę parametry produktowe aukcji (`productSet[].product.parameters`) z `GET sale/product-offers/{id}` i wstawię je w PATCH zmieniając/dodając EAN?

**Comment by AureliuszBrussy** [comment]
Tak, dla metody PATCH ([rfc7396](https://tools.ietf.org/html/rfc7396)) w przypadku tablic powinieneś przesłać całą zawartość tablicy (w tym przypadku wszystkie parametry produktowe).

**Comment by Radeq** [comment]
@AureliuszBrussy, czy mógłbyś przy okazji zweryfikować poprawność swagger.yml?
Chodzi o SaleProductOfferResponseV1 productsSet, linia 20934-20950, openapi-generator mi wychwytuje tylko productSet[].quantity bez product

**Comment by AureliuszBrussy** [comment]
@Radeq jest poprawnie - `quantity` jest częścią słownika produktu, natomiast nie chodzi w skład obiektu `product`. Dla lepszego zobrazowania struktura wygląda tak:

```
...
 "productSet": [
        {
         "product": {"id": "7b167551-0c7d-42fd-ba39-102ac5e4efc7"}, 
         "quantity": {"value": 1}   -- liczba sztuk wskazanego produktu, która 
                                   wejdzie w skład pojedynczego zestawu
        },
        {
        "product": {"id": "2903dd7e-4958-436c-8be0-491ea1ea0d85"},
        "quantity": {"value": 1}
        },
        {
        "product": {"id": "8487577e-e831-452c-83d7-d8b23b7fc1d3"}, 
        "quantity": {"value": 2} 
        }
     ]
...
```
