### ISSUE TITLE
Problem z wystawieniem produktu - brak parametru

### ISSUE THREAD

**Issue by ODeviatkin** [allegro/allegro-api#6819]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Request to 'https://api.allegro.pl/sale/product-offers':

`{'productSet': [{'product': {'name': ... 'parameters': [{'name': 'EAN', 'values': ['5903606101506']}, {'id': '7108', 'valuesIds': ['7108_1']}, {'id': 127048, 'valuesIds': ['127048_220885']}, {'id': '203093', 'values': ['22.9']}, {'id': '249512', 'valuesIds': ['249512_1647427']}, {'id': '127848', 'valuesIds': ['127848_380785']}, {'id': '64', 'valuesIds': ['64_3']}, {'id': '22728', 'valuesIds': ['22728_3']}, {'id': '203085', 'valuesIds': ['203085_32']}, {'id': '224017', 'values': ['GW4671']}, {'id': '237206', 'values': ['GW4671']}]}}], 'parameters': [{'id': '219629', 'valuesIds': ['219629_380781']}], ...}`

Response:

`{"errors":[{"code":"ConstraintViolationException.MissingRequiredParameters","message":"Missing required parameters: 249512, 64, 22728, 203085","details":"ConstraintViolationException.MissingRequiredParameters","path":"parameters","userMessage":"Uzupełnij parametry obowiązkowe: Kolor, Materiał zewnętrzny, Materiał wkładki, Zapięcie."}]}`

Trace-id:

d4b3457ab32a6bed

Podczas publikacji serwer narzeka na brak parametrów, które są w zapytaniu. Z czym to może być związane?

**Comment by Lukasz-Zurek** [comment]
@ODeviatkin Przekazałem ten temat dalej do weryfikacji. Proszę Cię o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@ODeviatkin Problem dotyczył produktu. Po naszej stronie wdrożyliśmy poprawkę i powinieneś już móc wystawić tę ofertę.

Przepraszamy za zaistniałe utrudnienia.
