### ISSUE TITLE
[REST] /sale/shipping-rates zwraca błąd podczas pobierania listy cenników dostaw

### ISSUE THREAD

**Issue by danielu78** [allegro/allegro-api#682]
Dla zapytania:
GET /sale/shipping-rates?sellerId=XXX HTTP/1.1
Host: api.allegro.pl
Accept: application/vnd.allegro.public.v1+json
Authorization: Bearer XXX
content-type: application/vnd.allegro.public.v1+json

Dostaję błąd:
```
{
    "errors": [
        {
            "code": "ConstraintViolationException",
            "message": "An error has occurred",
            "details": null,
            "path": "PublicShippingRatesResource$$EnhancerBySpringCGLIB$$8b6c7b54.getList.arg0",
            "userMessage": "Transferred data is incorrect"
        }
    ]
}
```

**Comment by PawelTaberski** [comment]
Sprawdziłem i wygląda na to, że wszystko działa prawidłowo. Podeślij proszę trace-id tego reqiuesta i informacje jaki status otrzymujesz.

**Comment by danielu78** [comment]
Trace-Id →b7652d84e6c9859a
Otrzymuję status "422 Unprocessable Entity"

**Comment by PawelTaberski** [comment]
Już widzę w czym jest problem masz źle skonstruowane zapytanie zmień sellerId na seller.id.

**Comment by danielu78** [comment]
Faktycznie, przepraszam za zamieszanie.
