### ISSUE TITLE
Problem z generowaniem przesyłki

### ISSUE THREAD

**Issue by SlawekMat** [allegro/allegro-api#6821]
Dzień dobry
Od kilku dni mam problem z generowaniem przesyłek dla "Allegro Kurier UPS", przy próbie założenia zwracany jest komunikat "Allegro Kurier UPS". W zleceniu przekazuje serviceId=0e4c7d59-64b6-4b06-89c3-c1d941506dd0

**Comment by AureliuszBrussy** [comment]
Podaj proszę przykładowe trace-id (znajdziesz w headerze naszego response'a), gdzie zwróciliśmy błąd. Możesz także podać id wygenerowanej komendy. Sprawdzę to.

**Comment by SlawekMat** [comment]
trace-id=213f366b2a61d92b

**Comment by AureliuszBrussy** [comment]
Pierwotnie komenda o id wskazanym w requeście została utworzona, z przekazaniem nieprawidłowej wartość w serviceId: `9495176`. Później widzę próby skorzystania z tego samego id komendy, ale z poprawną wartością w `serviceId`. Nie nadpiszesz komendy - musisz wygenerować nową, z nowym uuid.
