### ISSUE TITLE
Jak usunąć zakończoną oferte

### ISSUE THREAD

**Issue by Zbigi** [allegro/allegro-api#6822]
Mam następujący problem muszę wznowić kilkadziesiąt tysięcy ofert, które zostały w zeszłym roku w marcu wystawione.
Otrzymuje informację, ze nie mogę wznawiać ponieważ mam przekroczony limit 20 000 draftów. 
Faktycznie mam kilkadziesiąt tysięcy ofert ze statusem =ENDED, które są przeterminowane ale nie da się ich usunąć., bo otrzymuje info
Gdy próbuje Delete.
something went wrong: 400, {"errors":[{"code":"CannotDeleteOfferException","message":"You can delete only inactive offer.","details":"CannotDeleteOfferException","path":null,"userMessage":"Możesz usunąć tylko szkic oferty."}]}

i co teraz?
Wznowić nie mogę, skasować nie mogę. Jak wybrnąć z tej sytuacji?

**Comment by hahyes** [comment]
@Zbigi 
Nie możesz usunąć ofert o statusie ENDED. Nie są one też liczone do tego limitu, o którym wspominasz. Do tego limitu są liczone tylko oferty, które nigdy nie były aktywowane. Limit jest źle zliczany z powodu problemów technicznych po stronie Allegro, które obecnie naprawiają.

**Comment by AureliuszBrussy** [comment]
Limit odnosi się do draftów, czyli oferty nigdy nie aktywowanych (INACTIVE). Sprawdź, czy faktycznie nie przekroczyłeś na koncie tej liczby (**GET /sale/offers?publication.status=INACTIVE**). Wiemy o błędzie, gdzie error zwracamy mimo tego, że sprzedający nie przekracza tej liczby szkiców. Jeżeli potwierdzisz, że faktycznie nie przekraczasz limitu oferty INACTIVE, to podaj proszę id konta (lub np. przykładowy trace-id requestu ze zwracanym błędem).

**Comment by Zbigi** [comment]
Gdy próbuje listować ofert ze statusem  (GET /sale/offers?publication.status=INACTIVE).  otrzymuje pusty wynik

**Comment by AureliuszBrussy** [comment]
@Zbigi podaj proszę id tego konta (ew. trace-id przykładowego wywołania). Uspójnimy to na tym koncie.
