### ISSUE TITLE
WzA => Czy jest możliwość pobrania numeru kodu kreskowego?

### ISSUE THREAD

**Issue by lukasz-lopata** [allegro/allegro-api#6823]
Witam,
Na pobranej etykiecie jest kod kreskowy z numerem (załącznik). Czy jest możliwość pobrania również tego numeru z API? W aktualnych odpowiedziach nigdzie nie widzę takiego numeru?

Pozdrawiam.

[WysylamZAllegro_A00002HYO7.pdf](https://github.com/allegro/allegro-api/files/10940706/WysylamZAllegro_A00002HYO7.pdf)

**Comment by AureliuszBrussy** [comment]
Nie zwracamy takiego numeru z kodu kreskowego w API.

**Comment by lukasz-lopata** [comment]
Dziekuje za opdowiedz

**Comment by AureliuszBrussy** [comment]
@lukasz-lopata możesz zgłosić swoją potrzebę w naszej zakładce [Discussions](https://github.com/allegro/allegro-api/discussions) - zbieramy tam pomysły na zmiany w Allegro API. Utwórz nowy wątek, wyjaśnij i uzasadnij swoją potrzebę. Dzięki temu łatwiej nam zrozumieć potrzeby użytkowników.
