### ISSUE TITLE
Brak opłacenia rachunku

### ISSUE THREAD

**Issue by pzareba86** [allegro/allegro-api#6824]
Dzień dobry, 
czy mogę prosić o szybsze zaksięgowanie wpłaty za rozliczenie na koncie testowym sportcitytest, bo nie moge niczego wystawić.

Z góry dziękuję.

**Comment by MaciejFrackowiak** [comment]
Jak widzę środki zostały już rozliczone i blokada sprzedaży zniknęła.

**Comment by pzareba86** [comment]
Dziękuję, wszystko jest teraz ok😊

***@***.***
Patrycja Zaręba
Sales Coordinator

#WeMakeATeam

email: ***@***.******@***.***>
fax: +48 12 3120 239
mobile: +48724750784
OTCF S.A.
75-412 Koszalin, ul. Monte Cassino 6, Poland

***@***.***
***@***.***
Sponsor of 8 Olympic Committees: Poland, Croatia, Lithuania, Latvia, Portugal, Greece, Slovakia and Serbia for the Olympic Winter Games Beijing 2022
Presenting Sponsor of the Four Hills Tournament 2018-2020, Global Partner of the Wings for Life World Run 2020, Main Sponsor of FIS Alpine Ski World Championships Courchevel-Meribel 2023
________________________________
OTCF S.A. z siedzibą w Krakowie przy ul. Saskiej 25C, 30-720 Kraków, wpisana do rejestru przedsiębiorców Krajowego Rejestru Sądowego prowadzonego przez Sąd Rejonowy dla Krakowa – Śródmieścia w Krakowie, XI Wydział Gospodarczy Krajowego Rejestru  Sądowego pod nr KRS: 0000555276, kapitał zakładowy w wysokości: 7 384 500,00 zł opłacony w całości, NIP: 9451978451, REGON: 356630870, o numerze rejestrowym BDO: 000005025. Ta wiadomość i jej treść mogą zawierać informacje poufne lub zastrzeżone, przeznaczone tylko dla adresata wiadomości. Takie informacje są objęte zakazem ich ujawniania. Wszelkie rozprowadzanie, dystrybucja lub powielanie niniejszej wiadomości lub innego rodzaju wykorzystanie przez osobę lub podmiot nie będący jego adresatem, jest zabronione. Jeżeli otrzymałeś tę wiadomość omyłkowo, proszę bezzwłocznie zawiadomić nadawcę wysyłając odpowiedź na niniejszą wiadomość i usunąć ją z poczty. Dziękuję.
OTCF S.A. with its registered seat in Kraków, ul. Saska 25C, 30-720 Kraków, Poland, registered in the entrepreneurs’ register kept by the District Court for Kraków - Śródmieście District in Krakow, 11th Commercial Department of the National Court Register, entry no KRS 0000555276, its share capital of PLN 7 384 500.00 paid in full, Tax ID No.(NIP) : 9451978451, Business Statistical Number (Regon): 356630870, BDO: 000005025. This e-mail and its content might contain confidential or privileged information intended solely for the use of the addressee. Such information are protected from disclosure. You are hereby notified that any dissemination, distribution or copying or other use of this e-mail by person or entity other than the intended recipient is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by replying to the message and deleting it from your computer. Thank you.

From: MaciejFrackowiak ***@***.***>
Sent: Friday, March 10, 2023 1:12 PM
To: allegro/allegro-api ***@***.***>
Cc: Patrycja Zaręba ***@***.***>; Author ***@***.***>
Subject: [Marketing Mail] Re: [allegro/allegro-api] Brak opłacenia rachunku (Issue #6824)

CAUTION: Ten email pochodzi spoza OTCF. Uważaj na zamieszczone załączniki oraz linki. Podejrzane wiadomości zgłoś na ***@***.******@***.***>

Jak widzę środki zostały już rozliczone i blokada sprzedaży zniknęła.
