### ISSUE TITLE
Etykieta w formacie A6

### ISSUE THREAD

**Issue by SlawekMat** [allegro/allegro-api#6825]
Dzień dobry
Mam problem z etykieta w formacie A6
Dotąd pdf zawierał jedną etykietę we właściwym formacie, a w dniu dzisiejszym wydruk wygląda dość dziwnie
![image](https://user-images.githubusercontent.com/102292350/224315171-d6136e6a-91c6-4411-b384-7b0515ab6f09.png)

**Comment by SlawekMat** [comment]
Wywołanie robię z żądaniem właściwego formatu
parcel-management/parcels/label?parcelId=*****&pageFormat = A6

**Comment by MaciejFrackowiak** [comment]
Proszę podaj przykładowe id przesyłki lub trace-id wywołania.

**Comment by SlawekMat** [comment]
trace-id=213f366b2a61d92b

**Comment by MaciejFrackowiak** [comment]
Podany trace-id prowadzi do operacji utworzenia przesyłki, a nie pobrania etykiety. Proszę podaj właściwy trace-id.

**Comment by SlawekMat** [comment]
Już chyba znalazłem problem, dziękuję
