### ISSUE TITLE
Problem z wystawianiem z ładowaniem grafik

### ISSUE THREAD

**Issue by Zbigi** [allegro/allegro-api#6826]
Otrzymuje taki błąd:

Something went wrong: 422 {"errors":[{"code":"DownloadError.BadRequest","message":"Downloading image from URL 'http:/www.fotoartgeist.pl/ebaytemp/fototapety1/g-C-0262-a-a/g-C-0262-a-a-eb10.jpg' failed. Server returned the following HTTP status code: 400 BAD_REQUEST and response body: 'Invalid url'.","details":null,"path":null,"userMessage":"Downloading image from URL 'http:/www.fotoartgeist.pl/ebaytemp/fototapety1/g-C-0262-a-a/g-C-0262-a-a-eb10.jpg' failed. Server returned the following HTTP status code: 400 BAD_REQUEST and response body: 'Invalid url'."}]}

jak wpisuje te uri do przeglądarki, to grafiki się ściągają poprawnie. Dlaczego system nie ściąga tych grafik?

**Comment by Lukasz-Zurek** [comment]
@Zbigi Przekazałem ten temat dalej do weryfikacji. Wkrótce wrócę z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
@Zbigi W adresach, zaraz po http brakuje jednego backslasha.
