### ISSUE TITLE
questions api

### ISSUE THREAD

**Issue by merry75** [allegro/allegro-api#6827]
Hello I was asked by someone from allegro support to post my questions here so here they are thanks in advance for your assistance 

1. I saw there is a limit of maximum 200k offers per account correct ? can this limit be increased ? if yes how ?

2.I saw there is a limit of draft of 20k offers per account correct ? can this limit be increased ? if yes how ?

3.The offer listings are permanent or do they expire at some point ? same for draft offers

4.Everytime I create an offer there is a fee ; right now I saw because I am considered new sellers I dont have fees but after that there will be fees for listing ? is there solution for big sellers to avoid fee per listing ?

5.Is there a way to know before listing with api the cost to list the offer ? 

6.I created shipping rules but I am unsure I set it up properly can you double check basically we will be handling all of our deliveries ourself and our shipping time is between 2 to 7 days, which parameter should I use to set it up ?

7.Concerning the metrics and standard you set for your marketplace I didnt see them, like acceptance rate, refund rate, time to reply to buyers and so on can you let me know the value for each ? 

8. When I try to upload offers with /sale/product-offers it fails with 422 and ask a lot of parameters 
Is there a way that you take care of such params instead to avoid potential errors/issues instead ? especially if you already have the product data I am not sure why you ask for those params thanks for clarifying

**Comment by MartaNowaczyk** [comment]
> I saw there is a limit of maximum 200k offers per account correct ? can this limit be increased ? if yes how ?
> 2.I saw there is a limit of draft of 20k offers per account correct ? can this limit be increased ? if yes how ?

Yes, these are the limits. This is not an API issue, so contact via [the contact](https://allegro.pl/pomoc/kontakt?kategoria=4b0096d8-57bf-4af7-9a40-81c273a69423) form about this.

> 3.The offer listings are permanent or do they expire at some point ? same for draft offers

It depends on what option you choose whether you want the offer to be displayed for a certain period of time, e.g. for 7 days or until [the items are sold out](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/czym-jest-i-jak-dziala-oferta-do-wyczerpania-przedmiotow-7wOLX0D6dFo). The offer draft is stored for 60 days. After that, the offer draft will be deleted. If you edit something in the offer draft, we will extend its validity by 60 days. More about it you can find [here](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#offer-draft).

> 4.Everytime I create an offer there is a fee ; right now I saw because I am considered new sellers I dont have fees but after that there will be fees for listing ? is there solution for big sellers to avoid fee per listing ?

This is not an API topic. You can find information about fees in [Allegro help center](https://allegro.pl/pomoc/dla-sprzedajacych/oplaty-i-cenniki/jak-sprawdzic-nadchodzace-oplaty-za-oferte-vKvmg23EKcq) or via [the contact form](https://allegro.pl/pomoc/kontakt?kategoria=c4a0dab4-dd76-4bbf-92c8-bc3a715f01b5).

> 5.Is there a way to know before listing with api the cost to list the offer ?

You can check the fees for the offer through the API. You can find more information [here](https://developer.allegro.pl/tutorials/how-to-check-the-fees-3An6Wame3Um#fee-calculator).

> 6.I created shipping rules but I am unsure I set it up properly can you double check basically we will be handling all of our deliveries ourself and our shipping time is between 2 to 7 days, which parameter should I use to set it up ?
> 7.Concerning the metrics and standard you set for your marketplace I didnt see them, like acceptance rate, refund rate, time to reply to buyers and so on can you let me know the value for each ?

This is not a topic related to API support, contact through [the form](https://allegro.pl/pomoc/kontakt?kategoria=4b0096d8-57bf-4af7-9a40-81c273a69423).

**Comment by merry75** [comment]
thanks for the quick response could you let me know about 

When I try to upload offers with /sale/product-offers it fails with 422 and ask a lot of parameters
Is there a way that you take care of such params instead to avoid potential errors/issues instead ? especially if you already have the product data I am not sure why you ask for those params thanks for clarifying

**Comment by MartaNowaczyk** [comment]
Please give me the trace-id for this case with error 422. You can find the trace-id in the response header.

**Comment by merry75** [comment]
for example 

d6a62982c72d248e or cbe4499f4538de9f

**Comment by merry75** [comment]
thanks alot for clarification my next question is about how to calculate fee for an order i m using following api

https://api.{environment}/pricing/offer-fee-preview

I use previously /order/checkout-forms/orderId to get the order object and pass it to the offer-fee-preview api but I get 400 telling me offer object is not valid 

here is traceId f7fa93e78eac3136

Am I doing something wrong ?

thanks again !

**Comment by merry75** [comment]
when setting CONTAINS_OFFERS to END offers become expired but do they still account for the limit of the 200k offers ? or is it better to set them to inactive and then delete the corresponding draft ?

**Comment by MartaNowaczyk** [comment]
Offers in "INACTIVE" status count as drafts.

If you have too many of them or you want to delete an offer, you can use [DELETE /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/deleteOfferUsingDELETE)

**Comment by merry75** [comment]
I saw offers expired do not count as DRAFT so my question is are they still accounted in the 200k limit ?

**Comment by MartaNowaczyk** [comment]
Yes, the limit applies to drafts, that is, offers never activated (INACTIVE).

**Comment by MartaNowaczyk** [comment]
Let me further clarify, expired offers have status as ENDED and they do not count in the limit of 200k active offers.
