### ISSUE TITLE
Zamknięte oferty w offers/listing

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#6828]
Hej,
Od jakiegoś czasu endpoint `offers/listing` z parametrem '`searchMode=CLOSED` zwraca wyniki STARSZE niż 01.03.2023.

Czy coś zmienialiście? Nie jestem w stanie pobrać zakończonej oferty starszej niż 1 marca tego roku. Np takiej, która zakończyła się sprzedażą.
Tak, mam udzielony dostęp do `offers/listing`
Pozdrawiam!

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, że nie możesz pobrać oferty **młodszej** niż 1 marca? Nie udało mi się powtórzyć tego przypadku, w odpowiedzi otrzymałem oferty zarówno starsze, jak i młodsze, niż 1 marca tego roku. 
Czy możesz podać przykład oferty, której nie zwróciliśmy w response, a powinniśmy? Przydatne będzie również trace-id tego wywołania.

**Comment by jakubmaguza** [comment]
Hej,
Zapomniałem uściślić. Chodzi mi o datę zakończenia oferty `Publication.EndingAt`.
Np.: `offers/listing?category.id=261197&searchMode=CLOSED&price.from=80&price.to=90&sort=-startTime&offset=0&limit=60`

Nie ważne jaki offset użyję, jaki zakres cen, czy jaką kategorię (próbowałem większość podkategorii z działu książki) - nie jestem w stanie 'dostać' oferty, która została **zakończona** po 1.03.2023.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję Ci za przykład. Wykonałem przykładowe wywołania z użyciem category.id (wcześniej korzystałem z parametru phrase) i aktualnie mogę potwierdzić występujący problem. Przekazałem zgłoszenie do dalszej analizy do zespołu odpowiedzialnego za usługę. Jak tylko uda ustalić się coś więcej, poinformuję w wątku.

**Comment by PrzemyslawLukanowski** [comment]
@jakubmaguza Wprowadziliśmy poprawkę, problem nie powinien już wystepować.

**Comment by jakubmaguza** [comment]
Wygląda OK, dzięki!
