### ISSUE TITLE
Przesyłka pobraniowa UPS

### ISSUE THREAD

**Issue by SlawekMat** [allegro/allegro-api#6830]
Dzień dobry
Mam problem z wygenerowaniem przesyłki pobraniowej
Dotąd było wszystko poprawnie a obecnie pojawiają się wymagane pola
"accountNumber": "12345678901234567890123456",
"name": "Jan Kowalski",
"express": false
Nie mogę znaleźć informacji jakie dane w tych polach umieścić.

**Comment by AureliuszBrussy** [comment]
W `accountNumber` przekaż IBAN nadawcy (numer rachunku na który mają zostać przekazane środki od Kupującego), a w `name` przekaż nazwę (lub imię i nazwisko) właściciela tego rachunku bankowego. 

Z kolei `express` to flaga dla usługi pobraniowej Express - kwota pobrania wysyłana jest nadawcy 1 dzień roboczy po dostarczeniu przesyłki. Usługa dostępna tylko dla: DPD, FedEx, InPost Kurier.

**Comment by SlawekMat** [comment]
Dziękuję
