### ISSUE TITLE
Aktywacja konta testowego Sandbox

### ISSUE THREAD

**Issue by mczubala** [allegro/allegro-api#6832]
Proszę o aktywację konta testowego mfc_technology

**Comment by mczubala** [comment]
założyłem drugie konto mfc_test. Również wymaga aktywacji

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje oba konta.

**Comment by mczubala** [comment]
Dziękuję bardzo za pomoc

**Comment by UserKamil** [comment]
Również proszę o aktywację konta testtestt

**Comment by MaciejFrackowiak** [comment]
@UserKamil Konto jest już aktywne i zweryfikowane.

**Comment by ODeviatkin** [comment]
Proszę o aktywację konta "fasdfasdf" sandbox. Też próbowałem zmienić konto na firmowe, bo API nie chciało działać. Proszę również o akceptację tej zmiany :)

**Comment by PrzemyslawLukanowski** [comment]
@ODeviatkin Czy możesz nam wysłać screen krokowca z zakładki [Dane Konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta)? Czy uzupełniłeś wszystkie dane?

**Comment by ODeviatkin** [comment]
![image](https://user-images.githubusercontent.com/74683207/226359204-3a9ec57d-fdb3-44c6-8d77-bca1b25c9031.png)
po kliknięciu zwraca mnie na "Dane konta"
