### ISSUE TITLE
Problem z publikacją produktów - duplikaty

### ISSUE THREAD

**Issue by ODeviatkin** [allegro/allegro-api#6834]
Występuje problem:
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
 - POST https://api.allegro.pl/sale/product-offers + headers
 - trace-id: 7657bc284d4b1f9f

Podczas publikacji produktów w więcej niż jednym wątku, pojawia się problem z publikacją duplikatów. Za każdym razem jak publikuję nowy produkt, generuję nowy ean (wiem wiem), ale duplikaty mają ten sam ean. Między innymi stąd wiem, że algorytmicznie mam wszystko dobrze w kodzie. Z mojej strony wychodzi tylko jedno zapytanie, chyba że requests.post w Pythonie w implementacji ma inaczej, ale nigdy wcześniej nie miałem takiego problemu. 

Ten problem jest też nieregularny. Jeden produkt ma 10 duplikatów, inny tylko 2, większość nie ma w ogóle.

Jako trace-id dołączyłem tylko jeden taki przypadek, ale generalnie zdarza się dosyć często.  Możecie zobaczyć i podzielić się opinią?

PS: Tak czy siak dobrze by było, gdyby serwer po prostu blokował publikacje tego samego produktu(z tym samym czy innym ean) na tym samym koncie. Bo głupio trochę jest, że mogę opublikować coś, czego publikować nie wolno, po czym jeszcze dostaję maile, że jestem taki niedobry :)

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz napisać więcej szczegółów, na czym dokładnie polega problem z publikacją? Trace-id, które załączyłeś, dotyczy utworzenia propozycji produktu `0192442c-9827-4984-a738-44d8d6632f16` (duplikat). W tym przypadku to się udało, w odpowiedzi, w polu `product.publication.status`, otrzymałeś wartość `"PROPOSED"`, co oznacza, że utworzyliśmy propozycję nowego produktu. Gdybyśmy połączyli ofertę z już istniejącym produktem w naszym Katalogu, wtedy otrzymałbyś wartość `"LISTED"`, jednak nasze mechanizmy identyfikacji duplikatu w tym momencie jeszcze nie zadziałały, ponieważ oryginalny produkt (`ee0b9320-c9ce-4ebe-bb8b-57e3de47f073`) utworzyłeś niemalże w tym samym czasie, 2 sekundy wcześniej. 
Ze swojej strony powinieneś wyeliminować requesty, które zawierają identyczną strukturę, tak aby nie tworzyć duplikatów produktów i tym samym zduplikowanych ofert sprzedaży takiego produktu.

**Comment by ODeviatkin** [comment]
@PrzemyslawLukanowski,
Przepraszam, że tak długo nie odpisywałem.

Akurat udało mi się założyć Sandbox(login: asdfasd), stąd zasymilowałem ten błąd w nim. Tak jak mówiłem wcześniej, puszczam w wielu wątkach publikację produktów. Stworzyłem również plik z logami - za każdym razem jak robię zapytanie typu requests.post(), do logów trafia: czas kiedy zapytanie zostało wykonane, kod produktu, rozmiar, status_code oraz trace-id

Odpowiednio jeśli puszczam w jednym wątku, to problemu nie ma.

Gdybym robił dwa identyczne zapytania, to by kod i rozmiar się zdublowały w logach, ale tego nie zauważyłem: [log.txt](https://github.com/allegro/allegro-api/files/11021462/log.txt)

Do produktów które się zdublowały należą między innymi:
GW0613 40 r. EAN (GTIN): 5906182312700
GX6870 40 2/3 r. EAN (GTIN): 5906284689588
...

Nie wykluczam, że należy publikować produkt i jego rozmiary przez jedno zapytanie, ale na razie nie udało mi się  :(

Co Pan myśli na ten temat ?

**Comment by PrzemyslawLukanowski** [comment]
> Gdybym robił dwa identyczne zapytania, to by kod i rozmiar się zdublowały w logach, ale tego nie zauważyłem: [log.txt](https://github.com/allegro/allegro-api/files/11021462/log.txt)

Zweryfikowałem nasze logi i wygląda na to, że dwa identycznie zapytania występują i to jest właśnie powodem tworzenia duplikatów. Spójrz proszę na szczegóły poniżej:

EAN 5906182312700
```
3e4df204-e708-432c-a9b0-d9ab836697fe 
2023-03-20 18:34:38.167 trace id = 83d04359cf60baae
code w Twoich zapisanych logach = GW0612, rzeczywisty kod producenta, jaki od Ciebie otrzymaliśmy = GW0613

42230df6-bed7-4d18-915f-ddde30ab684c 
2023-03-20 18:34:39.283 trace id = c20e4976fbdee956
code w Twoich logach = GW1390, rzeczywisty kod producenta = GW0613
```

EAN 5906284689588
```
2b9af25e-f0fb-4991-b22e-4a1675e2565d 
2023-03-20 18:35:29.753 trace id = ab69eb4ce3cd1959
code w Twoich logach = GX6875, rzeczywisty kod producenta = GX6870


a14e9eb8-232d-4ff0-877a-847ad8854a9c 
2023-03-20 18:35:30.892 trace id = f87781f9aa05268e
code w Twoich logach = GX6551, rzeczywisty kod producenta = GX6870
```

Jeśli wyeliminujesz te identyczne zapytania dla tworzenia produktów, problem z duplikatami nie powinien już występować.
