### ISSUE TITLE
Brak trackingu logistyka

### ISSUE THREAD

**Issue by Levena007** [allegro/allegro-api#6835]

**Comment by PrzemyslawLukanowski** [comment]
Poprosimy o więcej szczegółów na temat problemów.

**Comment by Levena007** [comment]
Witam,
centrum logistyczne ma problem z trackingiem danych, co za tym idzie problem z monitorowaniem płatności za pobraniem.  Czy możemy działać bez tego? Czy nie grozi nam tu blokada konta?

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Na forum świadczymy wsparcie w tematach technicznych związanych z API Allegro. Kwestia blokady konta i tego, w jakich okolicznościach może nastąpić, wychodzi poza tę specyfikę, dlatego skorzystajcie proszę z [formularza kontaktowego.](https://allegro.pl/pomoc/kontakt)

**Comment by Levena007** [comment]
dziękuje
