### ISSUE TITLE
offers/listing

### ISSUE THREAD

**Issue by VerusPL** [allegro/allegro-api#6836]
Witam,

W jaki sposób mogę uzyskać dostep do offers/listing?
https://api.allegro.pl/offers/listing

Aktualnie kiedy próbuję wykonać dowolne zapytanie np: 
https://api.allegro.pl/offers/listing?category.id=177&phrase=laptop&limit=10&offset=1&sort=-startTime
otrzymuje nastp. error

{"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept' request header","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."}]}

Jakie kryteria trzeba spełnić aby uzyskać dostęp i gdzie należy wysłać żądanie z prośbą o dostęp?

**Comment by PrzemyslawLukanowski** [comment]
Jeśli jesteś w [Programie Partnerskim](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm) skontaktuj się ze swoim opiekunem. W innym wypadku skontaktuj się z nami przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). Kryteria dostępu wymieniliśmy w punkcie 3.2 naszego [regulaminu](https://developer.allegro.pl/rules).

Błąd, który otrzymujesz, wskazuje także na inny problem - zwróć uwagę, czy prawidłowo przekazujesz nagłówek "Accept" i wartość "application/vnd.allegro.public.v1+json".
