### ISSUE TITLE
Integracja z ING Fakturowanie

### ISSUE THREAD

**Issue by juicebartek** [allegro/allegro-api#6837]
Witam, mam pytanie czy istnieje możliwość powiązania konta Allegro z ING Fakturowanie?
Mają oni możliwość wygenerowania API lecz czy będzie możliwość wpisania tego na Allegro?
Korzystacie z takiego rozwiązania? Zależy mi na tym aby dało się do każdego zamówienia wystawić fakturę.

**Comment by PrzemyslawLukanowski** [comment]
W tym celu skontaktuj się proszę ze wsparciem ING Fakturowanie - to oni będą posiadać najlepszą wiedzę na temat możliwości, jakie daje ich oprogramowanie w zakresie pracy z Allegro API.

**Comment by juicebartek** [comment]
Właśnie się kontaktowałem, dlatego przyszedłem tutaj. U nich mogę wygenerować API które musiałbym wpisać na Allegro. Czy na Allegro będzie taka możliwość?

**Comment by PrzemyslawLukanowski** [comment]
Nie do końca rozumiem, co masz na myśli przez "wpisać na Allegro". Dana integracja powinna udostępnić Ci odpowiednią instrukcję, według której możesz powiązać swoje konto z ich aplikacją.

**Comment by juicebartek** [comment]
Faktycznie może trochę niezrozumiale napisałem. Chodziło mi czy jak klucz API wygeneruje w ING Fakturowanie będę miał jak go wprowadzić na stronie Allegro? Miałem na myśli czy integracja może być w tą stronę, czy musi być tak że API generuje na stronie Allegro i wprowadzam w ING Fakturowanie?

**Comment by PrzemyslawLukanowski** [comment]
Nie, nie udostępniamy takiej możliwości - aplikacja generuje klucz na naszej stronie.

**Comment by PrzemyslawLukanowski** [comment]
> Czyli podsumowywując z Allegro jestem w stanie uzyskać API, które powinienem wprowadzić w ING.

Nie do końca to miałem na myśli, doprecyzuję - aplikacja, która korzysta z Allegro API, przedstawia się kluczem zarejestrowanym na stronie https://apps.developer.allegro.pl/. Dzięki temu może korzystać z naszych zasobów i tym samym wykonywać operacje w imieniu użytkownika. Tego klucza nie wprowadza się już w innych, zewnętrznych aplikacjach, jest on związany strice z Allegro.

Link, który wysłałeś, dotyczy stricte API ING. Przykro mi, ale nie znamy tej integracji, nie jesteśmy jej twórcami, zatem nie możemy pomóc w tym przypadku.
