### ISSUE TITLE
Allegro Sandbox - błąd wysyłki DPD Pickup przez Wysyłam z Allegro

### ISSUE THREAD

**Issue by Wojtu204** [allegro/allegro-api#6839]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy próbie założenia paczki kurierskiej do DPD Pickup/ DPD Pickup Pobranie przez Wysyłam z Allegro otrzymuję zwrotny komunikat błędu: ANOTHER_SERVICE_NOT_AVAILABLE

Autoryzacja przez device flow - aplikacja zarejestrowana na koncie, token aktualny, ID usług pobrane w oparciu o uzyskany token:
"id": "08e2ef8e-90c8-49db-8970-d6c2773f1530",
            "service": "DPD",
            "name": "Allegro Odbiór w Punkcie DPD Pickup",

"id": "1d037bcd-7e6a-4713-9015-d6c2773f1530",
            "service": "DPD",
            "name": "Allegro Odbiór w Punkcie DPD Pickup pobranie",

Przy wysłaniu żądania założenia paczki otrzymuję status 201, przy próbie pobrania statusu paczki w odpowiedzi otrzymuję błąd:
{
	"id": "e944cc24-3e54-4d57-9dab-3e04fcc0adff",
	"parcelId": null,
	"status": "ERROR",
	"errors": [
		{
			"code": "ANOTHER_SERVICE_NOT_AVAILABLE",
			"message": "One of required services is unavailable. Try again later.",
			"details": "One of required services is unavailable. Try again later.",
			"path": null,
			"userMessage": "One of required services is unavailable. Try again later."
		}
	]
}

**Comment by AureliuszBrussy** [comment]
Skorzystałeś z maila kupującego pobranego ze środowiska produkcyjnego, co jest powodem tego błędu. Skorzystaj z danych pobranych z zamówienia z Sandboxa.
