### ISSUE TITLE
Problem z GetPostBuyData dla aukcji z dużą ilością ofert

### ISSUE THREAD

**Issue by miszellek** [allegro/allegro-api#684]
Zauważyliśmy ostatnio problem z metodą GetPostBuyData i okazało się że dla aukcji które mają powyżej 5000 ofert (np. 5413601046, 5543174734) wywołanie jej zwraca Internal Server Error, czy jest to znany problem? Jak to rozwiązać?

$arry = $allegro->GetPostBuyData(array(5413601046)); //Internal Server Error

**Comment by PawelTaberski** [comment]
Sprawdziłem dla dwóch przykładowych userów dane dla pierwszej oferty, którą podałeś i wszystko wygląda poprawnie. Podeślij proszę swojego pełnego requesta i responsa w formacie XML przez nasz[ formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). Sprawdzimy w czym jest problem. W treści zgłoszenia zaznacz proszę, że informacje są na potrzebę zgłoszenia na GitHub-ie numer 684.

**Comment by miszellek** [comment]
Może dodam że chcemy pobrać wszystkie formularze dla aukcji w których jesteśmy sprzedawcą (twojedziecko24), a nie dla konkretnego użytkownika. Poniżej request, bo respons jest pusty.

`<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:AllegroWebApi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:doGetPostBuyData><session-handle xsi:type="xsd:string">9df56c613439839d8e9d189510472383f80f2e2c155a17//01_1</session-handle><items-array SOAP-ENC:arrayType="xsd:long[1]" xsi:type="ns1:ArrayOfAuctionID"><item xsi:type="xsd:long">5413601046</item></items-array><buyer-filter-array xsi:nil="true" xsi:type="ns1:ArrayOfBuyerId"/></ns1:doGetPostBuyData></SOAP-ENV:Body></SOAP-ENV:Envelope>
`

**Comment by PawelTaberski** [comment]
Sprawdź proszę, ustawienia swoich timeout-ów czy nie masz jakiś lokalnie ustawionych krótszych. Przetestowałem Twojego requesta i otrzymałem odpowiedź w 34705 ms.

**Comment by miszellek** [comment]
Timeouty to było to co sprawdziłem w pierwszej kolejności, ale zrobiłem to teraz jeszcze raz i w Delphi i w php (SoapClientem i Curlem) i niestety po kolo 40 sekundach dostaje pusta odpowiedz.

**Comment by PawelTaberski** [comment]
Rozumiem podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełny request w formacie XML i konkretne czasy w jakich wysyłałeś requesty i z jakiego konta. W treści zaznacz, że dane na potrzeby zgłoszenia z GitHub-a numer 684. Sprawdzimy w czym jest problem.

**Comment by PawelTaberski** [comment]
Nie udało mi się powtórzyć tego błędu, ale przekazałem sprawę wraz z informacjami jakie dosłałeś do rozpatrzenia do odpowiedniego zespołu, proszę o cierpliwość.

**Comment by miszellek** [comment]
Zajęło to dwa tygodnie, ale 16.10.2018 w południe zaczęło działać, wiec temat do zamknięcia ;)

**Comment by miszellek** [comment]
Problem niestety niedawno powrócił, dotyczy tych samych aukcji i objawia się w identyczny sposób.

`doGetPostBuyData : SoapFault exception: [HTTP] Internal Server Error in doGetPostBuyData.php:41 Stack trace: #0 [internal function]: SoapClient->__doRequest('__call('doGetPostBuyDat...', Array) #2 doGetPostBuyData.php(41): SoapClient->doGetPostBuyData('57d34adb7776ff9...', Array) #3 {main}
POST /uploader.php HTTP/1.1
Host: webapi.allegro.pl
Connection: Keep-Alive
User-Agent: PHP-SOAP/5.3.28
Content-Type: text/xml; charset=utf-8
SOAPAction: "#dogetpostbuydata"
Content-Length: 777
Cookie: ws2=e4e835cb088209b15902d17768a29f26;

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:AllegroWebApi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:doGetPostBuyData><session-handle xsi:type="xsd:string">57d34adb7776ff94e7a59819b13b7a470954a31d155a17//01_1</session-handle><items-array SOAP-ENC:arrayType="xsd:long[1]" xsi:type="ns1:ArrayOfAuctionID"><item xsi:type="xsd:long">5413601046</item></items-array><buyer-filter-array xsi:nil="true" xsi:type="ns1:ArrayOfBuyerId"/></ns1:doGetPostBuyData></SOAP-ENV:Body></SOAP-ENV:Envelope>
HTTP/1.1 500 Internal Server Error
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Set-Cookie: ws2=e4e835cb088209b15902d17768a29f26; expires=Mon, 15-Apr-2019 10:12:24 GMT; path=/; domain=.allegro.pl
Set-Cookie: QXLSESSID=57d34adb7776ff94e7a59819b13b7a470954a31d155a17%2F%2F01; path=/; domain=.allegro.pl; secure; HttpOnly
Server: Apache
Pragma: no-cache
X-SOAPMethod: doGetPostBuyData
Date: Mon, 15 Apr 2019 09:42:24 GMT
Vary: Accept-Encoding
Content-Type: text/html;charset=UTF-8
Content-Length: 0
X-SOAPIgnore: true`

**Comment by PawelTaberski** [comment]
Przekazałem dane do odpowiedniego zespołu, prośba o cierpliwość.

**Comment by PawelTaberski** [comment]
@miszellek Dostałem informacje, że udało się namierzyć problem i wdrożyć rozwiązanie. Problem nie powinien już występować. Potwierdź proszę, czy u Ciebie jest teraz ok.

**Comment by miszellek** [comment]
Nie spodziewałem się aż takiej szybkiej reakcji, ale niestety nie przyniosła ona rozwiązania, bo z mojej strony nic się nie zmieniło ;(

doGetPostBuyData.php(41): SoapClient->doGetPostBuyData('384294c98a08171...', Array) #3 {main}
POST /uploader.php HTTP/1.1
Host: webapi.allegro.pl
Connection: Keep-Alive
User-Agent: PHP-SOAP/5.3.28
Content-Type: text/xml; charset=utf-8
SOAPAction: "#dogetpostbuydata"
Content-Length: 777
Cookie: ws2=b57fe851f9437e99f46db99528fac215;

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:AllegroWebApi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:doGetPostBuyData><session-handle xsi:type="xsd:string">384294c98a08171b9b48928a8ff51f3bf4391cf30bcc68//00_1</session-handle><items-array SOAP-ENC:arrayType="xsd:long[1]" xsi:type="ns1:ArrayOfAuctionID"><item xsi:type="xsd:long">5413601046</item></items-array><buyer-filter-array xsi:nil="true" xsi:type="ns1:ArrayOfBuyerId"/></ns1:doGetPostBuyData></SOAP-ENV:Body></SOAP-ENV:Envelope>
HTTP/1.1 500 Internal Server Error
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Set-Cookie: ws2=b57fe851f9437e99f46db99528fac215; expires=Thu, 18-Apr-2019 07:52:41 GMT; path=/; domain=.allegro.pl
Set-Cookie: QXLSESSID=384294c98a08171b9b48928a8ff51f3bf4391cf30bcc68%2F%2F00; path=/; domain=.allegro.pl; secure; HttpOnly
Server: Apache
Pragma: no-cache
X-SOAPMethod: doGetPostBuyData
Date: Thu, 18 Apr 2019 07:22:41 GMT
Vary: Accept-Encoding
Content-Type: text/html;charset=UTF-8
Content-Length: 0
X-SOAPIgnore: true

**Comment by PawelTaberski** [comment]
@miszellek Dzięki za info, przekazałem informacje do zespołu, jak tylko otrzymam jakieś informacje dam znać.

**Comment by miszellek** [comment]
Minęły 3 tygodnie, są jakieś postępy? Bo problem dalej nie jest rozwiązany:

doGetPostBuyData : SoapFault exception: [HTTP] Internal Server Error in doGetPostBuyData.php:41 Stack trace: #0 [internal function]: SoapClient->__doRequest('__call('doGetPostBuyDat...', Array) #2 doGetPostBuyData.php(41): SoapClient->doGetPostBuyData('8815f1d3f5f2fe4...', Array) #3 {main}
POST /uploader.php HTTP/1.1
Host: webapi.allegro.pl
Connection: Keep-Alive
User-Agent: PHP-SOAP/5.3.28
Content-Type: text/xml; charset=utf-8
SOAPAction: "#dogetpostbuydata"
Content-Length: 777

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:AllegroWebApi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:doGetPostBuyData><session-handle xsi:type="xsd:string">8815f1d3f5f2fe4f0b52663667a98fed807865f90bcc68//00_1</session-handle><items-array SOAP-ENC:arrayType="xsd:long[1]" xsi:type="ns1:ArrayOfAuctionID"><item xsi:type="xsd:long">5413601046</item></items-array><buyer-filter-array xsi:nil="true" xsi:type="ns1:ArrayOfBuyerId"/></ns1:doGetPostBuyData></SOAP-ENV:Body></SOAP-ENV:Envelope>

HTTP/1.1 500 Internal Server Error
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Set-Cookie: ws2=810c62dbad9edbc083d1de54c30b1b5d; expires=Tue, 07-May-2019 08:25:33 GMT; path=/; domain=.allegro.pl
Set-Cookie: QXLSESSID=8815f1d3f5f2fe4f0b52663667a98fed807865f90bcc68%2F%2F00; path=/; domain=.allegro.pl; secure; HttpOnly
Server: Apache
Pragma: no-cache
X-SOAPMethod: doGetPostBuyData
Date: Tue, 07 May 2019 07:55:33 GMT
Vary: Accept-Encoding
Content-Type: text/html;charset=UTF-8
Content-Length: 0
X-SOAPIgnore: true

**Comment by MartaNowaczyk** [comment]
@miszellek sprawdzamy to raz jeszcze.

**Comment by miszellek** [comment]
Kolejne 2 tygodnie!!!

doGetPostBuyData : SoapFault exception: [HTTP] Internal Server Error in doGetPostBuyData.php:41 Stack trace: #0 [internal function]: SoapClient->__doRequest('__call('doGetPostBuyDat...', Array) #2 doGetPostBuyData.php(41): SoapClient->doGetPostBuyData('2412971966396fc...', Array) #3 {main}
POST /uploader.php HTTP/1.1
Host: webapi.allegro.pl
Connection: Keep-Alive
User-Agent: PHP-SOAP/5.3.28
Content-Type: text/xml; charset=utf-8
SOAPAction: "#dogetpostbuydata"
Content-Length: 777

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:AllegroWebApi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:doGetPostBuyData><session-handle xsi:type="xsd:string">2412971966396fc2996fd11e4ece9f3ea465e19c030b7b//02_1</session-handle><items-array SOAP-ENC:arrayType="xsd:long[1]" xsi:type="ns1:ArrayOfAuctionID"><item xsi:type="xsd:long">5413601046</item></items-array><buyer-filter-array xsi:nil="true" xsi:type="ns1:ArrayOfBuyerId"/></ns1:doGetPostBuyData></SOAP-ENV:Body></SOAP-ENV:Envelope>
HTTP/1.1 500 Internal Server Error
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Set-Cookie: ws2=13b2b538407a933e0cde6cb4f433bdba; expires=Mon, 20-May-2019 08:10:42 GMT; path=/; domain=.allegro.pl
Set-Cookie: QXLSESSID=2412971966396fc2996fd11e4ece9f3ea465e19c030b7b%2F%2F02; path=/; domain=.allegro.pl; secure; HttpOnly
Server: Apache
Pragma: no-cache
X-SOAPMethod: doGetPostBuyData
Date: Mon, 20 May 2019 07:40:42 GMT
Vary: Accept-Encoding
Content-Type: text/html;charset=UTF-8
Content-Length: 0
X-SOAPIgnore: true

**Comment by MartaNowaczyk** [comment]
@miszellek Rozwiązanie na ten moment jest jedno. W przypadku ofert z dużą liczbą zakupów wywołuj  metodę z pojedynczą ofertą.

**Comment by neldh** [comment]
Ponad 5 tygodni walki z Internal Server Error.... Brawo! Dawno takiego wyczynu nie widziałem...
