### ISSUE TITLE
/sale/product-offers/{offerId} - dziwny response 

### ISSUE THREAD

**Issue by sl-aw-ek** [allegro/allegro-api#6840]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Request : /sale/product-offers/XXXXXXXX
Response : 422 
code: "OFFER_TAX_SETTING_NOT_YET_SERVED"
message: "The VAT settings for offer are not served for provided date 2023-03-15T18:26:42.919Z."

trace-id: 65e83210e098d64

Otrzymuje taką odpowiedź, jeszcze kilka dni temu wszystko działało "normalnie", to jakiś błąd czy coś nowego o czym nie ma ani śladu w dokumentacji?

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować, przepraszam za niedogodności.
