### ISSUE TITLE
WzA GLS Kuirer - problem z nadawaniem przesyłek

### ISSUE THREAD

**Issue by lukasz-lopata** [allegro/allegro-api#6841]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Podczas nadawania przesyłki GLS Kurier otrzymujemy następujący błąd:
`{
	"id": "4ced1fbd-920d-4feb-ba53-277d9f013447",
	"parcelId": null,
	"status": "ERROR",
	"errors": [
		{
			"code": "ERROR",
			"message": "Processing error",
			"details": null,
			"path": null,
			"userMessage": "error.common.processing"
		}
	]
}`

Problem występuje na środowisku testowym i produkcyjnym u jedego z naszych klientów.
Trace ID: 3438eb8c5a2e7b71

**Comment by PrzemyslawLukanowski** [comment]
Jest to podobny problem, który został również poruszony w wątku #6752:

> Przyczyną problemu jest tutaj przekroczona długość adresu e-mail w polu receiver.email. W swoim API firma GLS ogranicza niestety długość adresu mailowego do 40 znaków. Z uwagi na to, że może to być problematyczne dla kolejnych przesyłek, wyjaśniamy jeszcze tę sprawę po naszej stronie (...)
Sprawa dotycząca limitu pola receiver.email zależna tutaj będzie w pierwszej kolejności od prac po stronie kuriera GLS. Otrzymaliśmy zapewnienie, że temat będzie po ich stronie realizowany.
