### ISSUE TITLE
Wza Nieoczekiwany blad

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#6843]
Występuje problem: 
 - [ x ] z zasobem REST API / with a REST API resource
 - [ x ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy probie stworzenia wysylki dostajemy blad: Wystapil nieoczekiwany blad

'trace-id': '5b6ea683f6cd6418'

to cos z naszym requestem czy faktycznie problem po stronie Allegro?

**Comment by paafcioc22** [comment]
też mamy problemy z dpd pickup. Id 363cae26-2c5a-4f1b-8a0e-5b0f1534fb6e

**Comment by AureliuszBrussy** [comment]
Problem występuje po stronie przewoźnika - pracują już nad usunięciem błędu.

**Comment by d3stozaur** [comment]
A czy jest mozliwosc abyscie dodali w takich przypadkach zwracali w komunikacie ze blad jest po stronie przewoznika? Zakladam ze wasze api dziala tak ze my pytamy was a wy wysylacie do przewoznika zapytanie to fajnie by bylo jakby komunikat w jakis sposob dawał informacje gdzie mniej wiecej wystepuje bląd, a tak niepotrzebnie my szukamy u nas, potem zglaszamy do was a problem jest jeszcze gdzies indziej :)

**Comment by AureliuszBrussy** [comment]
@d3stozaur dziękuję za sugestię, przekazałem ją do zespołu odpowiedzialnego za usługę.
