### ISSUE TITLE
Pobranie całościowej sprzedaży na ofercie

### ISSUE THREAD

**Issue by MrYarovoi** [allegro/allegro-api#6845]
Dzień dobry, 

czy jest możliwość pobrania danych łącznej sprzedaży na mojej ofercie? Aby móc zrobić podobną tabelę:

Produkt   -- moja sprzedaż na ofercie w ciagu 30 dni -- Łączna sprzedaż wszystkich osób na ofercie

Produkt1 --                   10 szt                                      --                              100 szt

**Comment by PrzemyslawLukanowski** [comment]
W odpowiedzi [GET /sale/offers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET), w polu `stock.sold`, zwracamy wyłącznie informację o sprzedaży wyłącznie z ostatnich 30 dni. Jedynym rozwiązaniem będzie pobieranie tej informacji w pakietach 30-dniowych i zapisywanie ich po swojej stronie - dzięki temu będziesz mógł zobaczyć, jak sprzedaż rozkładała się na poszczególne miesiące i następnie zsumować ją całościowo.

**Comment by MrYarovoi** [comment]
Dziękuję za odpowiedź, a w tym przypadku jest zwracana wielkość sprzedaży za 30 dni wszystkich osób na ofercie? Podłączyłem się pod produktyzację, więc ja sprzedałem tylko część z całej sprzedaży oferty i chcę wyciągnąć sprzedaż całościową (nie tylko moją).

**Comment by PrzemyslawLukanowski** [comment]
Nie udostępniamy informacji na temat całościowej sprzedaży danego produktu, możesz sprawdzić wyłącznie sprzedaż w swoich ofertach.
