### ISSUE TITLE
Api sygnatura

### ISSUE THREAD

**Issue by messiosw** [allegro/allegro-api#6848]
mam takie pytanie czy jest możliwość dostępu do sygnatury która jest dostępna na koncie firmowym, chciałbym tę pozycję pobierać i przetwarzać poprzez API.  

ogólnie to mam jeszcze problem z aktywacją konta testowego moge wystawiąc aukcje ale zawiesiła się weryfikacja jako firma , jest też problem z uzyskaniem klucza do API występuje błąd access_token = Something went wrong.

**Comment by AureliuszBrussy** [comment]
Czy chodzi Ci o sygnaturę oferty? Sygnatura oferty to pole `external.id` w modelu oferty. Możesz pobrać tą informację m.in. za pomocą [GET /sale/offers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET) (lista ofert sprzedającego).

Jeżeli chodzi o aktywacje konta na Sandboxie - podaj proszę login (lub adres e-mail) konta.

Co to próby uzyskania access tokena - potrzebowałbym więcej szczegółów, najlepiej pełen przykładowy request i response.

**Comment by messiosw** [comment]
Email konta na Sandboxie :  ***@***.***

wklejam kod aplikacji

<?php
define('CLIENT_ID', 'f62deee01f064ac3ad1bdfe496f1c3eb'); // wprowadź
Client_ID aplikacji

define('CLIENT_SECRET',
'WegcrhJMfHCQDQiYMRAb3aWsc2CwSCUYMjwVHHGSIZjxyXptxSZHs7B1Oi4jsZ2B');
// wprowadź Client_Secret aplikacji
function getCurl($headers, $url, $content = null) {
    $ch = curl_init();
    curl_setopt_array($ch, array(
        CURLOPT_URL => $url,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_RETURNTRANSFER => true
    ));
    if ($content !== null) {
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $content);
    }
    return $ch;}
function getAccessToken() {
    $authorization = base64_encode(CLIENT_ID.':'.CLIENT_SECRET);
    $headers = array("Authorization: Basic
{$authorization}","Content-Type: application/x-www-form-urlencoded");
    $content = "grant_type=client_credentials";
    $url = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token";
    $ch = getCurl($headers, $url, $content);
    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }
    return json_decode($tokenResult)->access_token;}

 function main(){
    echo "access_token = ", getAccessToken();}
main();

[image: image.png]


pt., 17 mar 2023 o 12:02 AureliuszBrussy ***@***.***>
napisał(a):

**Comment by AureliuszBrussy** [comment]
Czy mógłbyś odpisać bezpośrednio w wątku [6848](https://github.com/allegro/allegro-api/issues/6848), a nie przez maila? Niestety, ale GitHub wycina część Twojej odpowiedzi (anonimizuje podanego maila oraz nie przekazuje załączników).

**Comment by messiosw** [comment]
login: krewcio

**Comment by AureliuszBrussy** [comment]
@messiosw aktywowałem Twoje konto. Co do uzyskania access tokena - próbujesz go wygenerować dla środowiska testowego (Sandbox), a wykorzystujesz do tego Client ID aplikacji zarejestrowanej na produkcji. Dla Sandboxa zarejestruj swoją aplikację [tutaj](https://apps.developer.allegro.pl.allegrosandbox.pl/).

**Comment by messiosw** [comment]
JAK rozwiazać problem z uwierzytelnianiem, aplikacja jest podpięta do konta allegro. 

function getMainCategories($token) {
    $headers = array("Authorization: Bearer {$token}", "Accept: application/vnd.allegro.public.v1+json", "Content-Type: application/x-www-form-urlencoded");
    $url = "https://api.allegro.pl/sale/offers?limit=1&offset=0";
    $ch = getCurl($headers, $url);
    $mainCategoriesResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($mainCategoriesResult === false || $resultCode !== 200) {
        exit ("Something went wrong:  $resultCode $mainCategoriesResult");
    }
    $categoriesList = json_decode($mainCategoriesResult);
    return $categoriesList;
} 


 function main()
{
    $token = getAccessToken();
    $main_categories = getMainCategories($token);
}

main();

Something went wrong: 403 {"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"Access denied. Contact the author of the application."}]}

**Comment by PrzemyslawLukanowski** [comment]
@messiosw Czy nie korzystasz przypadkiem z tokena wygenerowanego w ramach autoryzacji typu client_credentials? Taki token nie posiada kontekstu użytkownika, dlatego w odpowiedzi otrzymujesz kod 403. Aby prawidłowo pobrać dane dla GET /sale/offers, musisz skorzystać z autoryzacji typu [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow).

W naszej dokumentacji znajdzie odpowiednie oznaczenia, jakiego rodzaju autoryzacji musi użyć, aby otrzymać prawidłową odpowiedź z danego endpointu:

- bearer-token-for-user - [code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) lub [device flow](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow);
- bearer-token-for-application - [client credentials](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#clientcredentials-flow).

Dodatkowo wartość w Content-Type możesz zmienić na application/vnd.allegro.public.v1+json.
