### ISSUE TITLE
WzA dokumentacja nie zawiera wszystkiego co jest potrzebne

### ISSUE THREAD

**Issue by tomasz3k** [allegro/allegro-api#6849]
Proszę o odpowiedź na poniższe pytania bo nie znalazłem tego w dokumentacji.

1. Jak pobrać listę usług dostawy, które umożliwiają zmianę nadawcy na etykiecie.
2. Jak pobrać listę usług dostawy, które umożliwiają nadanie w punkcie? Jak pobrać listę takich punktów?
3. Jak pobrać listę usług dostawy wraz z parametrami jakie mogą zostać przekazane podczas tworzenia przesyłek danego typu. I nie chodzi tutaj o https://developer.allegro.pl/documentation#operation/getAvailableDeliveryServices, bo dane, które są zwracane nie zawierają np. typów przesyłek(np. z góry informacja o tym, że dana usługa nie przyjmuje "palet" jako typ paczki.), oraz np gabarytów, które dostępne są jedynie w formularzu wysylam z allegro na koncie allegro.

**Comment by AureliuszBrussy** [comment]
1. Co masz na myśli, poprzez "umożliwiają zmianę nadawcy na etykiecie"? Jaką konkretnie zmianę i w którym momencie?
2. W naszym API zwracamy tylko punkty nadania/odbioru dla usługi Allegro One ([GET /order/carriers/ALLEGRO/points](https://developer.allegro.pl/documentation#operation/uploadOrderInvoiceFile)). Nie zwracamy takich informacji dla pozostałych przewoźników. Punkt odbioru, do którego zamówił przesyłkę klient zwracamy w zamówieniu. Punkty nadania na ten moment sprzedający może ustalić bezpośrednio z poszczególnymi firmami kurierskimi. 
3. Na ten moment nie zwracamy takich szczegółów. Mamy już [podobną sugestię](https://github.com/allegro/allegro-api/discussions/6667) - czym większe zainteresowanie takim feature'em, tym większa szansa na wdrożenia z naszej strony.

**Comment by tomasz3k** [comment]
1. W api można podać nadawcę przesyłki (skąd kurier ma odebrać paczki) lub nadawcę na etykiecie. Z tego co widziałem w innym wątku napisaliście, że nie każda metoda dostawy pozwala na zmianę danych na etykiecie. Więc pytanie która metoda nie pozwala na to. 

2. Chodzi tutaj tylko o punkt nadania przesyłki. Tworzę uniwersalny moduł do obsługi Wysyłam z Allegro i nie mogę przewidzieć z jakich klient będzie korzystał dostawców w związku z czym muszę "ogarnąć" każdą metodę dostawy. Bez takich danych nie jestem w stanie tego zrobić bo przecież wasze api powinno zwrócić informację, jak np. robi to Inpost, i w odpowiedzi na listę dostępnych usług dostawy zwrócić również dostępny sposób nadania. https://dokumentacja-inpost.atlassian.net/wiki/spaces/PL/pages/11731047/1.8.1+Spos+b+nadania

3. To powinien być standard w chwili gdy wydaliście w ogóle możliwość nadawania przesyłek przez api. No dajcie spokój. Na tę chwilę dla każdej usługi dostawy muszę  złożyć osobne zamówienie i wygenerować formularz przesyłki przez stronę by zobaczyć jakie opcje są dostępne. Ponad 100 metod dostawy. Dramat :-(

**Comment by Lukasz-Zurek** [comment]
1. Przewoźnicy, którzy pozwalają na zmianę danych na etykiecie:

- One Kurier
- DHL
- InPost
- DPD
- Poczta Polska
- UPS

Przewoźnicy, którzy nie pozwalają na zmianę danych na etykiecie:

- One by UPS
- Orlen Paczka

2. Jak już wspomniał mój kolega we wcześniejszym poście - w naszym API zwracamy tylko punkty nadania/odbioru dla usługi Allegro One. Jednakże to o czym piszesz ma jak najbardziej rację bytu. Możesz opisać swoją propozycję w [Discussions](https://github.com/allegro/allegro-api/discussions), gdzie zbieramy i analizujemy sugestie dotyczące zmian w naszym API.

3. W tym miejscu podkreślę, że usługa "Wysyłam z Allegro" jest zależna od operatora zewnętrznego (a operator zależny jest od przewoźników), dlatego zwracanie dodatkowych informacji nie jest tutaj rzeczą łatwą do zaimplementowania. Niemniej jednak zachęcam do przekazania pomysłu, który usprawni ten proces j.w.

**Comment by tomasz3k** [comment]
Dziękuję za informację ale nie zgodzę się z punktem 3.
Skoro macie informacje, na podstawie których generowany jest formularz tworzenia przesylki po stronie waszego narzędzia, to te same dane wystarczyłoby udostępnić w api dla klientów.

**Comment by Lukasz-Zurek** [comment]
@tomasz3k Tak.
