### ISSUE TITLE
Wysyłam z Allegro DPD - lista przesyłek na protokole

### ISSUE THREAD

**Issue by Wojtu204** [allegro/allegro-api#6850]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy wysyłaniu żądania z listą przesyłek zwracany jest protokół, na którym przesyłki są rozbite w ten sposób, że wygląda jakby były pojedyncze, zamiast listy.
Trace-id żądania z niepoprawną odpowiedzią: 24b8607a46a411af
Przykładowy url:
https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcels/protocol?parcelId=b1ac38f4-bd7b-4e18-ac45-484e5829fb40&parcelId=e409c75a-a492-423f-8c71-984dd7e87954

Z kolei dla przesyłek założonych na analogiczne dane mamy zwracaną poprawnie listę.
Trace-id: 3ab760252cb43357
Url:
https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcels/protocol?parcelId=aaf83073-4fc5-48b7-81ba-b094c1916dfe&parcelId=b325dd67-ef34-490c-9e04-f89bebcaaa3f

**Comment by AureliuszBrussy** [comment]
Nie jest to bug - dla przesyłek nadawanych osobno protokoły będą oddzielne (i połączone w jeden plik .pdf), nie będzie to lista.

**Comment by Wojtu204** [comment]
Proszę o wyjaśnienie kwestii osobnego nadawania przesyłek. 
Przesyłki z drugiego zapytania były nadawane oddzielnie - każde zamówienie, w oparciu o które została wygenerowana przesyłka, było procesowane odrębnie, odrębnie został wywołany proces zakładania przesyłki i pobierania etykiety dla niej - były zatem dwa odrębne żądania, a mimo to przesyłki pojawiają się na protokole jako lista.

**Comment by Wojtu204** [comment]
Proszę o informację, czy powodem zakwalifikowania przesyłek jako nadane osobno są dane nadawcy? Jeśli będzie sytuacja, że n przesyłek będzie nadanych na jednych danych, a m przesyłek na drugich, to protokoły będą zawierały 2x2 listy odpowiednio z n i m przesyłek, czy otrzymamy 2x(n+m) osobnych protokołów?

**Comment by MaciejFrackowiak** [comment]
Wyjaśniam sprawę z zespołem odpowiedzialnym za funkcjonalność, wrócę z odpowiedzią.

**Comment by Wojtu204** [comment]
Analogiczną sytuację mamy na środowisku produkcyjnym, przy czym tam nie ma żadnej różnicy w nagłówku dokumentu - dane nadawcy są te same.

**Comment by Wojtu204** [comment]
Wyjaśniliśmy przypadek rozdzielenia przesyłek na zestawieniach na środowisku produkcyjnym - wnika on z tego, że zostały złożone na różnych ID Allegro sprzedawców  - na samym dokumencie nie widać różnicy, natomiast konfiguracja już to bierze pod uwagę ze względu na kwestię autoryzacji.
Pozostaje wyjaśnienie sytuacji jaką mamy na środowisku testowym - tam korzystamy z jednego ID.
