### ISSUE TITLE
Authorization Code flow

### ISSUE THREAD

**Issue by keczerad** [allegro/allegro-api#6851]
Próbujemy się autoryzować i w punkcie 4 dokumentacji dostajemy zamiast przykładowego:

http://exemplary.redirect.uri/?code=pOPEy9Tq94aEss540azzC7xL6nCJDWto

Dostajemy do Was jakieś bzdury w JSONIE, można wiedzieć dlaczego ? 

{
	"url": "https://geo.captcha-delivery.com/captcha/?dlasza cześć bzdur ...."
}

Nasze zgłoszenie odnośnie bzdur :
ID: 1d6e8c25-7ad9-903c-7acc-1cbdfc23e840

**Comment by PrzemyslawLukanowski** [comment]
Aby to zweryfikować, będziemy potrzebować adres IP, z jakiego wykonujecie połączenie oraz przykładowe logi zawierające clientID. Wygląda na to, że jesteście z jakiegoś powodu blokowani, musimy przeanalizować przyczynę. Dane możecie nam przesłać za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt). W zgłoszeniu dopiszcie, że dane dotyczą wątku #6851 na GitHubie.
Możecie także upewnić się, czy korzystacie z prawidłowych adresów wywołań, tj. https://allegro.pl/auth/oauth/authorize i https://allegro.pl/auth/oauth/token.

**Comment by keczerad** [comment]
Wiadomość dodana

**Comment by PrzemyslawLukanowski** [comment]
@keczerad Wstępnie na podstawie logów widzimy, że korzystacie jednak z https://ssl.allegro.pl/auth/oauth/token. Czy możecie zmienić adres na https://allegro.pl/auth/oauth/token i zweryfikować, czy problem nadal będzie występować?

**Comment by keczerad** [comment]
Dziękuje działa, mam jeszcze jeden problem techniczny po stronie strony dla developerów, przy edycji uprawnień do api dla naszych aplikacji nie możemy nic zrobić ponieważ ta strona zwraca informacje ze nazwa jest obowiązkowa a nazwy nie mozemy zmienić bo u nas jest nullem.

[https://1drv.ms/i/s!AgioGHW0t0gwhK4UAm-k9HKihQMx-w?e=0hUMhO](url)

**Comment by PrzemyslawLukanowski** [comment]
Niestety, ale link nie prowadzi nigdzie dalej. Czy mogę prosić o jakiekolwiek trace-id z Państwa aplikacji, aby mógł dotrzeć do client-Id? Co do zasady - rejestracja aplikacji bez nazwy nie powinna być możliwa.

**Comment by keczerad** [comment]
Niestety clientId mogę podać w komunikacie odnośnie trace-id nie mogę podać to blokuj Javascript na stronie i nie dochodzi do zapytania.

**Comment by PrzemyslawLukanowski** [comment]
Otrzymaliśmy clientId w zgłoszeniu, dziękuje. Potwierdzam, że aplikacja nie posiada nazwy - została utworzona, gdy jeszcze było to możliwe. W takiej sytuacji musimy ją nadać, czy wyrażacie zgodę, abym wykonał to po naszej stronie? Jeśli tak, podajcie proszę nazwę, jaka ma się wyświetlać. Możecie ją przekazać tutaj lub w zgłoszeniu.

**Comment by keczerad** [comment]
Proszę dodać nazwę "Aplikacje e-mo.pl" , z góry dziękuje.

**Comment by PrzemyslawLukanowski** [comment]
Zmieniłem nazwę aplikacji, aktualnie powinniśmy wyświetlać wyżej wskazaną.

**Comment by keczerad** [comment]
Dziękuje za wszystko.
