### ISSUE TITLE
Offer available amount

### ISSUE THREAD

**Issue by MKI-Miro** [allegro/allegro-api#6852]
Hi

In documentation for offer edit there is written:
available | integer <int32> **>= 0** Quantity of this offer available for sale - how many times this offer can be sold.

But when I try to edit an offer with 0 value I get error: The stock level of items to be listed may not be lower than 1.

It seems like bug or error in documentation.

Can anyone clarify it please.

**Comment by PrzemyslawLukanowski** [comment]
Hi, this is a mistake in the documentation, thank you for reporting this, we will change it. Sorry for the inconvenience.
