### ISSUE TITLE
Kupowanie produktów sprzedawców jako kupujący za pomocą Allegro API

### ISSUE THREAD

**Issue by Marczuu** [allegro/allegro-api#6853]
Czy za pomocą Allegro API można dokonać zakupu jako kupujący u sprzedającego (kupić produkt)?
Czy można pobrać listę złożonych przeze mnie zamówień (tak, aby dostać adresy dostawy, dane, numery przesyłek, itp.?
Jeśli nie, to czy w przyszłości będzie taka możliwość?

**Comment by PrzemyslawLukanowski** [comment]
Nasze API skupione jest na funkcjonalnościach dla sprzedających, dlatego nie udostępniamy takiego endpointu i na tę chwilę nie mamy go w planach. Na forum pojawiła się już sugestia, aby go dodać - [w tym wątku](https://github.com/allegro/allegro-api/discussions/5394) możesz na nią zagłosować. Jeśli coś w tej kwestii się zmieni, będziemy informować na naszej stronie oraz forum.
