### ISSUE TITLE
Refresh token dla Device_flow

### ISSUE THREAD

**Issue by ZakuroPL** [allegro/allegro-api#6855]
Cześć.
Czytałem dokumentacje oraz wątki na github, ale niestety wciąż nie rozumiem, więc proszę o pomoc tutaj.

Dla mojego pracodawcy piszę aplikacje konsolową w python do pobierania danych z naszego sklepu allegro raz na dobę.

Tak więc wybieram metodę device_flow
Mam stworzoną aplikacje w allegro, posiadam client_id oraz client_secret.
Mam napisaną funkcje, która pobiera access_token zgodnie z intrukcją w dokumentacji dla device_flow
Problem mam z pozyskaniem refresh_token. Access_token jest ważny 12h, a nasza aplikacja ma chodzić w tle na naszej maszynie.
Tak więc zgodnie z instrukcją tworzę url
"    authorization_redirect_url = AUTH_URL + '?response_type=code&client_id=' + CLIENT_ID + \
                                 '&redirect_uri=' + REDIRECT_URI"
Po kliknięciu w link dostaje: 
"
Nie możemy wyświetlić strony
Numer błędu: 212de69a8a3aaced
"
widzę też, że authorization_code jest dla przeglądarkowego programu, a ja korzystam z device_code, ale w instrukcji mam użyć authorization_code.

Proszę o pomoc. Nie wiem jak uzyskać refresh_token lub może powinienem skorzystać z innej metody?
Zamysł jest, aby program mógł działać miesiącami bez konieczności ingerencji człowieka.

**Comment by PrzemyslawLukanowski** [comment]
```
Mam napisaną funkcje, która pobiera access_token zgodnie z intrukcją w dokumentacji dla device_flow
Problem mam z pozyskaniem refresh_token. Access_token jest ważny 12h, a nasza aplikacja ma chodzić w tle na naszej maszynie.
```

Refresh token powineneś uzyskać wraz z access tokenem - zawsze zwracamy parę tokenów.  W przypadku odświeżania tokena za pomocą https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token={refresh_token} po prostu nie podawaj parametru redirect_uri, jeśli korzystasz z autoryzacji typu device flow.

```
Tak więc zgodnie z instrukcją tworzę url
" authorization_redirect_url = AUTH_URL + '?response_type=code&client_id=' + CLIENT_ID +
'&redirect_uri=' + REDIRECT_URI"
Po kliknięciu w link dostaje:
"
Nie możemy wyświetlić strony
Numer błędu: 212de69a8a3aaced
"
widzę też, że authorization_code jest dla przeglądarkowego programu, a ja korzystam z device_code, ale w instrukcji mam użyć authorization_code.
```

Ten przykład kodu w poradniku dla przedłużenia ważności tokena dotyczy stricte autoryzacji typu authorization_code.

**Comment by ZakuroPL** [comment]
Proszę jeszcze o jedną pomoc. 
1) uzyskuje klucz device_code:

>         api_call_response = requests.post(CODE_URL, auth=(CLIENT_ID, CLIENT_SECRET), headers=headers, data=payload, verify=False)

2) uzyskuje odpowiedź:

> {'device_code': '7zL..................8Q7jC9', 'expires_in': 3600, 'user_code': '8............o', 'interval': 5,

3) akceptuje z poziomu przeglądarki

4) teraz chcę wygenerować refresh token:

> data = {'grant_type': 'device_code', 'device_code': device_code}
> refresh_token_response = requests.post(TOKEN_URL, data=data, verify=False, allow_redirects=False, auth=(CLIENT_ID CLIENT_SECRET))

i dostaje odpowiedź:
> {'error': 'unsupported_grant_type', 'error_description': 'Unsupported grant type'}

,a gdy zmienię grant_type na "urn:ietf:params:oauth:grant-type:device_code" to mam error:
> {'error': 'invalid_request', 'error_description': 'Invalid device code'} 

mogę uzyskać pomoc jak powinienem skonstruować "data", aby uzyskać refresh_token używając do tego "device_code"

**Comment by PrzemyslawLukanowski** [comment]
Wszystko wskazuje, że jako wartość parametru "device_code" nie wskazujesz kodu aplikacji, który zwróciliśmy w kroku 2, w polu "device_code". Upewnij się, czy na pewno przekazujesz prawidłowe dane (miej na uwadze, że device code jest ważny tylko godzinę, być może musisz wygenerować nowe dane). Przykładowy kod, który realizuje wygenerowanie tokenów, znajdziesz np. w wątku #6686

**Comment by PrzemyslawLukanowski** [comment]
Cieszę się, że udało się rozwiązać problem i dziękuję za miłe słowo :)
