### ISSUE TITLE
availableCount => 600 - książki i komiksy

### ISSUE THREAD

**Issue by Daczek** [allegro/allegro-api#6856]
Kiedy chcę pobrać listę ofert (https://developer.allegro.pl/documentation/#operation/getListing) dla frazy KRONIKI WARDSTONE to dostaję response z listą znalezionych wyników. W searchMeta mam takie coś:
[availableCount] => 600
[totalCount] => 1575

Z tego co pamiętam to availableCount miało wcześniej wartość 6000 - czy teraz zwracane jest 600 czy jest to błąd?

Pozdrawiam serdecznie.

**Comment by hahyes** [comment]
@Daczek Masz nawet w dokumentacji: `Max offset is 600 - <limit>.` przy parametrze zapytania `offset`. Dostępne dla wyszukiwania jest tylko 600 wyników.

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, ograniczenia [wprowadziliśmy 1 czerwca 2021](https://developer.allegro.pl/news/wprowadzilismy-ograniczenia-dla-get-offers-listing-WvGz1qOlxc6).

**Comment by Daczek** [comment]
OK - gdzieś mi to umknęło. Dzięki bardzo za odpowiedź.
