### ISSUE TITLE
Identyfikator punktu zwracany na zamówieniu dla zamówień z metodą wysyłki PACKETA

### ISSUE THREAD

**Issue by kulisz** [allegro/allegro-api#6857]
Witam,

Czy na zamówieniach w których została wybrana metoda wysyłki Packeta, informacja o punkcie dostawy będzie miała format zwykłego identyfikatora z Packeta czyli np "8621" czy też będzie użyty labelRouting np "C78-405-8621"?

**Comment by PrzemyslawLukanowski** [comment]
Informacja o punkcie dostawy będzie miała format zwykłego identyfikatora z Packeta, czyli np "8621".
