### ISSUE TITLE
POST pricing/offer-fee-preview nie zwraca typu "commissionFeatureFee"

### ISSUE THREAD

**Issue by ricarderobl** [allegro/allegro-api#6858]
Zgodnie z zaleceniem zmieniłem polecenie GET /sale/offers/{offerID} na GET /sale/product-offers/{offerId}.

Tak jak wcześniej POST pricing/offer-fee-preview zwracał mi typ "commissionFeatureFee" tak teraz nie otrzymuje w Response takowej odpowiedzi pomimo iż aukcja jest wyróżniona. W strukturze offer przekazuje pełne dane oferty, pobrane za pomocą nowego polecenia GET /sale/product-offers/{offerId}.

Trace id: 64701dad22a6795b.

Response jest poprawny: 200, ale nie ma odpowiedniego typu w odpowiedzi. Proszę o pomoc, gdyż zgodnie z poradnikiem wszystko powinno pracować całkowicie poprawnie.

**Comment by MaciejFrackowiak** [comment]
Jest to prawidłowe zachowanie - zasoby /sale/product-offers nie zwracają informacji o promowaniu. Aby odczytać przypisane do oferty opcje promowania skorzystaj z [GET /sale/offers/{offerId}/promo-options](https://developer.allegro.pl/documentation/#operation/getOfferPromoOptionsUsingGET).

**Comment by MaciejFrackowiak** [comment]
Jeśli spojrzysz dokładnie to w poradniku jest przykład z modelem oferty pobranym z GET /sale/offers/{offerId}. Ponadto, jeżeli korzystasz z promowania opartego o pakiety promowań to również i w tym modelu nie znajdziesz wszystkich informacji związanych z promowaniami.

**Comment by ricarderobl** [comment]
Nie wiem, moim zdaniem to jest bezsensu pytać serwer dwa razy o to samo.

To tak jakbym pobierał dane z aukcji raz pytając o opis a raz pytając o resztę. Jeden rodzaj wyniku = jedno zapytanie.

W tym momencie jest to całkowity nonsens. Najpierw mam pytać serwer o zwykłe opłaty, a wcześniej zapytać o wszystkie inne opcje promowanie grupowo, a potem w POST pricing przesyłać te do promowań, co mają promowanie.

Naprawdę, jest to całkowicie bezsensu, ale trudno. Skoro tak zwracacie dane to zrobię to w ten bezsensowny sposób.

**Comment by ricarderobl** [comment]
Chociaż nadal nie rozumiem, jak mam otrzymać kwotę jaką zapłacę za wyróżnienie w ramach danej aukcji jak zostanie ona sprzedana?

**Comment by MaciejFrackowiak** [comment]
Nie otrzymasz tych danych, ponieważ zasób [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST) nie zwraca informacji o opłatach dla pakietów promowań. Tu możesz się posiłkować zapisami z [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/oplaty-i-cenniki/sposob-naliczania-oplat-za-opcje-promowania-ey2LgRgjaS8).

**Comment by ricarderobl** [comment]
![obraz](https://user-images.githubusercontent.com/112190475/226546228-ad612b5b-361b-4eaa-8dc3-316bd5b19818.png)

**Comment by ricarderobl** [comment]
Zwraca, ale dla GET /sale/offers/{offerID}.

Dodatkowo przecież nie będę przeglądał załącznika nr 4 regulaminu by ustalić ile % ma jaka kategoria dla kilku tysięcy ofert. Zwykła zmiana tej stawki sprawi, że po swojej stronie będę musiał mieć tabelę gdzie sam będę wpisywać ręcznie stawki aktualne i będę musiał czuwać, czy cokolwiek się dla jakiejkolwiek kategorii nie zmieniło.

Domyślam się, co może być problemem.

Moim zdaniem GET który wycofujecie zwraca tutaj opłaty za wyróżnienia bo aukcja tak pobrana zawiera w sobie te dane:
![obraz](https://user-images.githubusercontent.com/112190475/226546981-b9f30f5b-ef72-427d-88b9-34e53fb2d530.png)

Natomiast GET /sale/product-offers/{offerId} nie ma "Promotion" i stąd ten problem.

Dlatego uważam, że jest to znaczący błąd po stronie serwera, że GET /sale/product-offers/{offerId} nie zwraca "Promotion" bo potem jak przesyłam tak pobraną ofertę na serwer nie otrzymuje opłat dotyczących wyróżnień. Natomiast powinienem, bo zarówno w poradniku jak i w starej opcji pobierania otrzymywałem tę kwotę dla każdej z wyróżnionych aukcji.

**Comment by ricarderobl** [comment]
Tak, sprawdziłem i jest tak jak sądziłem.

trace-id: df4a3926dc67cf84

Dopisałem "promotion" do oferty i wysłałem tak przygotowaną ofertę przy użyciu [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST)

Otrzymałem dane w sposób właściwy z tego endpointa, czyli także opłatę za wyróżnienie.

W związku z tym czy GET /sale/product-offers/{offerId} zostanie poprawione? Nie wiem czy mam używać starej metody i czekać na poprawę nowej, czy też mam się dostosować do aktualnie błędnie napisanej.

Proszę o informację.

**Comment by MaciejFrackowiak** [comment]
To jest właściwe zachowanie endpointu [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getProductOffer) - nie zwraca on informacji o opcjach promowania oferty. Od momentu wprowadzenia pakietów promowań sugerowanym rozwiązaniem jest korzystanie z opcji i zasobów dla nich przeznaczonych - informowaliśmy o tym w [newsie](https://github.com/allegro/allegro-api/issues/3880).
