### ISSUE TITLE
Token JWT walidacja

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#686]
Uzyskany token oAuth ze środowiska sandbox po zdekodowaniu z użyciem narzędzia online https://jwt.io wskazuje nieprawidłowy podpis (invalid signture). Do zweryfikowania poprawności podpisu tokena dla użytego algorytmu RS256 narzędzie wymaga podania publicznego klucza lub certyfikatu (Public Key or Certificate. Enter it in plain text only if you want to verify a token).

W dokumentacji https://developer.allegro.pl/auth/ nie ma informacji na temat gdzie znajdę taki publiczny klucz lub certyfikat. Przykładowo implementacja standardu oAuth w google ma udostępnione takie informacje pod adresami https://www.googleapis.com/oauth2/v3/certs https://www.googleapis.com/oauth2/v1/certs

Gdzie znajdę wymagane dane dla oAuth allego.pl (https://allegro.pl.allegrosandbox.pl/auth/oauth/ oraz
https://allegro.pl/auth/oauth/)?

**Comment by FromAnyHole** [comment]
@alekskuc - bardzo dobre pytanie, obsługa Allegro twierdzi uparcie, że wszystko opisali w dokumentacji, że do dekodowania token'ów wystarczy odpytywać kolejny serwis (jwt.io) - co akurat jest bzdurą i tylko zbędną komplikacją. Generalnie tworzone jest to wszystko tak, aby jak najmniej osób się w tym połapało...

**Comment by PawelTaberski** [comment]
Żeby zdekodować token JWT nie jest potrzebna weryfikacja podpisu to nasze serwery musza weryfikować autentyczność tokenu, który jest wysyłany. Nie musisz odpytywać o zdekodowanie na tej stronie jest to tylko przykład. Są to tokeny JWT, które można zdekodować innym odpowiednim dekoderem dla tej technologii.

**Comment by alekskuc** [comment]
Dziękuję za szybką odpowiedź. 
Rozumiem, że wykonanie żądania opisanego w dokumentacji https://developer.allegro.pl/auth/ w pkt. 5 "Mając ważny kod, aplikacja zgłasza się po token wykonując żądanie HTTP metodą POST na adres: https://allegro.pl/auth/oauth/token, dołączając nagłówek Authorization" jest wystarczające, aby stwierdzić, że otrzymam prawidłowy token i nie jest wymagana dodatkowa walidacja podpisu zawartego w tokenie. Podpis zostanie każdorazowo sprawdzony w momencie wywoływania zasobów REST API.

**Comment by FromAnyHole** [comment]
Bum !
