### ISSUE TITLE
To receive a report via API

### ISSUE THREAD

**Issue by autodocallegro** [allegro/allegro-api#6860]
Hi everyone!
Is there any possibillity to receive a transaction reports via API on Allegro? We are considering a possibility of automatizing of receiving this type of reports. Thanks

**Comment by autodocallegro** [comment]
Thank you, but what about transactions reports?

**Comment by Lukasz-Zurek** [comment]
There is no possibility to receive that kind of reports in our API.

**Comment by Lukasz-Zurek** [comment]
@autodocallegro I would like to ask you - what kind of transaction reports do you mean?

The transactions from our perspective are the orders. But maybe you mean something different like payments?

If you mean the transaction reports - we do have [sales summary](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/co-to-jest-zestawienie-sprzedazy-i-jak-je-wygenerowac-nl5Lgqb4wFj), but you can generate it only through My Allegro tab. It is not available in our API.

If you mean something else - please precise it.

**Comment by autodocallegro** [comment]
I got it thank you. We can close this case now.
