### ISSUE TITLE
Probem z Api produktyzacja - duplikat

### ISSUE THREAD

**Issue by AZAGroup90** [allegro/allegro-api#6861]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam, 
Mamy problem techniczny przy wystawianiu nowych produktów po api, gdzie chcemy produktyzować produkt i dostajemy informacje o duplikacie i tutaj dwa pytania:
1. jesli mamy zwrotke ProductDuplicate to chcemy wiedziec przez jaka produktyzacje jest to duplikat lub co jest tym duplikatem?
2. jesli mamy inny tytul i inne parametry, to jak utworzyć nowa produktyzacje na podstawie nowych parametrow, aby nie miec duplikatu (lub konfliktow parametrow, jesli inny jest w produktyzacji a inny w ofercie) 
Przykład na produkcie:
takiego jsona wysylam do produktyzacji
{    "name": "Buty Casual 2",    "category": {        "id": 83674    },    "parameters": [        {            "id": "7174",            "valuesIds": [                "7174_583117"            ],            "values": [],            "rangeValue": null        },        {            "id": "5389",            "values": [                "29"            ]        },        {            "id": "249512",            "valuesIds": [                "249512_1647413"            ],            "values": [],            "rangeValue": null        },        {            "id": "224017",            "values": [                "2520010875538_2308369_191605"            ]        }    ],    "description": {        "sections": [            {                "items": [                    {                        "type": "IMAGE",                        "url": "[https://a.allegroimg.com/original/118dab/781d2ed44edf9a08223fcbe3c1d1"](https://a.allegroimg.com/original/118dab/781d2ed44edf9a08223fcbe3c1d1%22)}                ]            }        ]    },    "images": [        {            "url": "[https://a.allegroimg.com/original/118dab/781d2ed44edf9a08223fcbe3c1d1"](https://a.allegroimg.com/original/118dab/781d2ed44edf9a08223fcbe3c1d1%22)        }    ]}

i dostaje:

{    "errors": [        {            "code": "ProductDuplicate",            "message": "An error has occurred",            "details": null,            "path": null,            "userMessage": "Produkt z takimi danymi już istnieje. Skontaktuj się z autorem aplikacji."        }    ]}

dla ad.2 dostaję błędy typu:

  {
        "code": "VALIDATION_ERROR",
        "message": "Incorrect value of the Marka (3786) parameter for the offered product. The correct parameter value for the product is: \"Pawonex\".",
        "details": "",
        "path": null,
        "userMessage": "Niepoprawna wartość parametru Marka (3786) dla produktu w ofercie. Prawidłowa wartość parametru dla produktu to: \"Pawonex\"."
    },

czyli jakie parametry decyduja ze jest to nowa produktyzacja albo ProductDuplicate?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj przykładowe trace-id dla opisanych przez Ciebie punktów.

**Comment by AZAGroup90** [comment]
nie mam trace id, strzelam z postmana na https://api.allegro.pl/sale/product-proposals
i w response dostaje {    "errors": [        {            "code": "ProductDuplicate",            "message": "An error has occurred",            "details": null,            "path": null,            "userMessage": "Produkt z takimi danymi już istnieje. Skontaktuj się z autorem aplikacji."        }    ]}
nie ma tu żadnego Trace id

**Comment by MaciejFrackowiak** [comment]
W zakładce Headers znajdziesz pole z trace-id. Również w tej zakładce znajdziesz pole "location", w którym zwracamy id produktu rozpoznanego jako duplikat.

**Comment by MaciejFrackowiak** [comment]
Kluczowe są tu parametry oznaczone jako "describesProduct" - to one opisują produkt, a jednocześnie pozwalają nam stwierdzić, czy przekazywane dane nie są już dostępne w naszej bazie w postaci innego, de facto podobnego produktu. Zawsze także możesz zgłosić sugestię zmiany w istniejącym produkcie korzystając z [POST /sale/product/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal).

**Comment by MaciejFrackowiak** [comment]
Są to parametry opisujące produkt, znajdziesz je korzystając z [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) dla każdej z kategorii z osobna.

**Comment by AZAGroup90** [comment]
Ok, dzięki za odpowiedź. Mam jeszcze jedno pytanie dot. produktyzacji:
tworze produktyzacje dla tych butow sportowych i dodaje parametr Długość wkładki
[14:25] Jakub Przekop
wg definicji jest taki:

[14:26] Jakub Przekop
{
    "id": "203093",
    "name": "Długość wkładki",
    "type": "float",
    "required": true,
    "unit": "cm",
    "restrictions": {
        "min": 0,
        "max": 40,
        "range": false,
        "precision": 2
    }
}

czyli liczbowa z zakresu 0-40
daje wiec np 0

{    "name": "Born2Be Różowe Buty Sportowe damskie",    "category": {        "id": 257903    },    "parameters": [        {            "id": 7108,            "valuesIds": [                "7108_52"            ],            "values": [],            "rangeValue": null        },        {            "id": 26388,            "valuesIds": [                "26388_1744002"            ],            "values": [],            "rangeValue": null        },        {            "id": 203093,            "valuesIds": [],            "values": [                "0"            ],            "rangeValue": null        },        {            "id": 249512,            "valuesIds": [                "249512_1647415"            ],            "values": [],            "rangeValue": null        },        {            "id": 64,            "valuesIds": [                "64_3"            ],            "values": [],            "rangeValue": null        },        {            "id": 22728,            "valuesIds": [                "22728_3"            ],            "values": [],            "rangeValue": null        },        {            "id": 127848,            "valuesIds": [                "127848_380785"            ],            "values": [],            "rangeValue": null        },        {            "id": 203085,            "valuesIds": [                "203085_32"            ],            "values": [],            "rangeValue": null        },        {            "id": 224017,            "valuesIds": [],            "values": [                "2520010725369_2280267_132135"            ],            "rangeValue": null        }    ],    "description": null,    "images": null}

i dostaje 

{    "errors": [        {            "code": "ParameterException.InvalidParameterDtoException",            "message": "An error has occurred",            "details": null,            "path": "parameters",            "userMessage": "Niepoprawnie zdefininiowano values, valuesIds lub rangeValue dla parametru 203093."        }    ]}


jak dam np. 20 też nie przechodzi ...

{    "name": "Born2Be Różowe Buty Sportowe damskie",    "category": {        "id": 257903    },    "parameters": [        {            "id": 7108,            "valuesIds": [                "7108_52"            ],            "values": [],            "rangeValue": null        },        {            "id": 26388,            "valuesIds": [                "26388_1744002"            ],            "values": [],            "rangeValue": null        },        {            "id": 203093,            "valuesIds": [],            "values": [                "20.00"            ],            "rangeValue": null        },        {            "id": 249512,            "valuesIds": [                "249512_1647415"            ],            "values": [],            "rangeValue": null        },        {            "id": 64,            "valuesIds": [                "64_3"            ],            "values": [],            "rangeValue": null        },        {            "id": 22728,            "valuesIds": [                "22728_3"            ],            "values": [],            "rangeValue": null        },        {            "id": 127848,            "valuesIds": [                "127848_380785"            ],            "values": [],            "rangeValue": null        },        {            "id": 203085,            "valuesIds": [                "203085_32"            ],            "values": [],            "rangeValue": null        },        {            "id": 224017,            "valuesIds": [],            "values": [                "2520010725369_2280267_132135"            ],            "rangeValue": null        }    ],    "description": null,    "images": null}

**Comment by AZAGroup90** [comment]
zmienilem na null to daje mi teraz taki błąd
![MicrosoftTeams-image (41)](https://user-images.githubusercontent.com/128464837/227192151-8e03cb28-1c0d-46cf-8511-c1cf0d0be9a4.png)
:
a jak tu tez mienie na null to taki:
![MicrosoftTeams-image (42)](https://user-images.githubusercontent.com/128464837/227192250-b43eedc5-9625-4a41-8378-cdae51db7d29.png)

trace-id: 3a95b6e720c4a6d3

**Comment by AZAGroup90** [comment]
jak dam na null to mam taki blad:
{    "name": "Born2Be Różowe Buty Sportowe damskie",    "category": {        "id": 257903    },    "parameters": [        {            "id": 7108,            "valuesIds": [                "7108_52"            ],            "values": [],            "rangeValue": null        },        {            "id": 26388,            "valuesIds": [                "26388_1744002"            ],            "values": [],            "rangeValue": null        },        {            "id": 203093,            "valuesIds": null,            "values": [                "23"            ],            "rangeValue": null        },        {            "id": 249512,            "valuesIds": [                "249512_1647415"            ],            "values": [],            "rangeValue": null        },        {            "id": 64,            "valuesIds": [                "64_3"            ],            "values": [],            "rangeValue": null        },        {            "id": 22728,            "valuesIds": [                "22728_3"            ],            "values": [],            "rangeValue": null        },        {            "id": 127848,            "valuesIds": [                "127848_380785"            ],            "values": [],            "rangeValue": null        },        {            "id": 203085,            "valuesIds": [                "203085_32"            ],            "values": [],            "rangeValue": null        },        {            "id": 224017,            "valuesIds": null,            "values": [                "2520010725369_2280267_132135"            ],            "rangeValue": null        }    ],    "description": null,    "images": null}

{    "errors": [        {            "code": "HttpMessageNotReadableException",            "message": "An error has occurred",            "details": null,            "path": null,            "userMessage": "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."        }    ]}


trace-id: dc75ce18dd0dffa2
