### ISSUE TITLE
Brak aktualizacji ceny na listingu i karcie produktu

### ISSUE THREAD

**Issue by podniesm** [allegro/allegro-api#6862]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Oferta https://allegro.pl/oferta/kolo-zamachowe-415-0695-09-luk-hyundai-kia-cee-d-13121549065 od >24h  ma nieaktualną cenę na listingu i karcie produktu mimo iż w panelu klienta jest zaktualizowana.

**Comment by MaciejFrackowiak** [comment]
Przeglądając logi związane ze wskazaną ofertą nie widzę żadnych requestów dot. zmiany ceny. Czy masz jakieś szczegóły swoich wywołań np. trace-id?

**Comment by podniesm** [comment]
@MaciejFrackowiak niezależnie od requestów dot. zmiany ceny i ich trace-id. W panelu Moje Allegro ta oferta ma od ponad 48h inną cenę niż na karcie produktu i listingu.

**Comment by MaciejFrackowiak** [comment]
Kwestie związane z działaniem zakładki Moje Allegro proszę zgłoś bezpośrednio do obsługi Allegro poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).

**Comment by podniesm** [comment]
@MaciejFrackowiak to nie jest problem panelu klienta, ponieważ nie zmienialiśmy ceny przez niego tylko przez API. Problem jest z synchronizacją ceny, którą prezentujemy klientowi.

**Comment by MaciejFrackowiak** [comment]
Niestety, jak wspomniałem wcześniej - nie otrzymaliśmy żadnych requestów ze zmianą ceny. Czy obecnie posiadasz przykładowe trace-id takiej operacji?
