### ISSUE TITLE
Dodawanie zdjęć tylko do opisu

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#6863]
Dzień dobry,

Mam pytanie czy przez allegro api można dodać zdjęcia tylko do opisu oferty pomijając galerię główną. Aktualnie jak dodaję aukcje która ma w opisie link do zdjęcia a w data[images] go nie ma to mimo wszystko zostanie dodane do galerii.

**Comment by MaciejFrackowiak** [comment]
Każde zdjęcie z opisu oferty automatycznie przekazywane jest do galerii zdjęć danej oferty. Nie można tego zmienić.
