### ISSUE TITLE
brak informacji o promocjach (promotion) w GET /sale/products-offers/id

### ISSUE THREAD

**Issue by sbrzezin** [allegro/allegro-api#6864]
Dzień dobry,

W wycofywanej funkcji GET /sale/offers/id można odczytać infromacje o promocjach odczytując atrybut "promotion". W nowej funkcji GET /sale/products-offers/id nie ma takich informacji. Czy to celowe? A jeśli tak, jak inaczej odczytać informację o promocjach (wyróżnienie, pogrubienie itd)?

pozdrawiam

Sergiusz

**Comment by MaciejFrackowiak** [comment]
Tak, zasoby /sale/product-offers w swojej strukturze nie mają sekcji odpowiedzialnej za promowanie ofert. W [listopadzie 2020](https://github.com/allegro/allegro-api/issues/3880) udostępniliśmy dedykowane zasoby do zarządzania opcjami promowania i to na ich bazie odczytasz jakiego typu opcje promowania ma dana oferta.
