### ISSUE TITLE
Połączenie feedu Allegro z Facebook Ads

### ISSUE THREAD

**Issue by marcin-lew** [allegro/allegro-api#6865]
Cześć!

Czy istnieje możliwość połączenia w jakikolwiek sposób feedu produktowego konta Allegro z kontem reklamowym na Facebooku? Najlepiej w taki sposób, żeby dane zaciągały i aktualizowały się automatycznie z bazy produktów na Allegro.
Zależy nam też na możliwości dalszego śledzenia kampanii po kliknięciu w link (zliczaniu konwersji, dodania do koszyka, wartości zakupu)

Wiem, że takie rozwiązanie nie jest oferowane przez Allegro. Jest może jednak szansa, żeby zrobić taką konfigurację za pomocą API?

Z góry dziękuję za odpowiedź, Marcin

**Comment by MaciejFrackowiak** [comment]
Zgadza się, z naszej strony nie udostępniamy takiego rozwiązania. Możliwe, że któryś z użytkowników forum będzie mógł przekazać niezbędne wskazówki.
