### ISSUE TITLE
Rozróżnienie ofert dodanych poprzez /sale/offers oraz /sale/product-offers

### ISSUE THREAD

**Issue by arolznov** [allegro/allegro-api#6868]
Czy dla danej swojej oferty możemy sprawdzić poprzez API którą metodą została dodana?

Chciałbym sprawdzić czy oferta została dodana poprzez /sale/offers lub /sale/product-offers

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma takiej możliwości. Jaką korzyść chciałbyś osiągnąć posiadając taką wiedzę?

**Comment by arolznov** [comment]
Omyłkowo wrzuciliśmy oferty poprzez /sale/product-offers bez pola description i opis pobrał się z produktu, czego nie chcemy. Teraz chcemy sprawdzić, które ofery zostały stworzone poprzez /sale/product-offers i mają opis z produktu a nie nasz,
