### ISSUE TITLE
Błąd podczas publikacji oferty (nieprawidłowy rok produkcji, kategoria opony)

### ISSUE THREAD

**Issue by lukiopmoto** [allegro/allegro-api#6869]
Dzień dobry, 

Chcę dodać ofertę przez API ale dostaję błąd, który wcześniej nie występował:
{"code":"ParameterCategoryException","message":"Unprocessable Entity","details":null,"path":"parameters","userMessage":"The definitions of the parameter `1:Rok produkcji` were incorrectly specified as a parameter in section `offer`."}

EAN: 8714692351013
ID produktu allegro: 311b8348-d034-4035-8e09-1bf97188b6e3
Podaje rok produkcji: 2022

Dodaję rok produkcji w parametrach OFERTY (nie produktu) mimo wszystko API wywala błąd. Jeżeli nie podam roku produkcji, wszystko działa OK, jeżeli podam np. 2022 lub 2023 to otrzymuję komunikat jak wyżej.

Proszę o podanie przyczyny dlaczego dzisiaj nagle zaczęło się tak dziać. Problem dotyczy wielu produktów (opon) których nie mogę dzisiaj wystawiać jeżeli podam dla nich rok produkcji. Parametr jest typu: integer

**Comment by PrzemyslawLukanowski** [comment]
Parametr jest typu produktowego, tzn. w odpowiedzi GET /sale/categories/{categoryID}/parameters, w polu `"options.describesProduct"`, zwracamy dla niego wartość `true`. Aby uniknąć błędu, nie przekazuj parametru w sekcji `parameters`, ale w `productSet.product.parameters`.

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję jeszcze sytuację z tym parametrem, wrócę z informacją.

**Comment by PrzemyslawLukanowski** [comment]
Parametr rok produkcji (id 1) pozostanie parametrem produktowym, parametr rok produkcji (id 249825) będzie parametrem ofertowym -  dotyczy on kategorii z oponami.

**Comment by lukiopmoto** [comment]
OK czyli zmieniam ID z 1 na 249825 w parametrach oferty. Zobaczymy czy zadziała. 

Pytania dlaczego to działało bez problemu do dzisiaj do godziny 11:00 ?

**Comment by lukiopmoto** [comment]
Pobrałem listę parametrów dla opon osobowych letnich i nie widzę tam parametru o ID: 249825 Jedyny parametr z rokiem produkcji to ten z ID: 1

**Comment by PrzemyslawLukanowski** [comment]
Parametr w zależności od kategorii przyjmuje wartość 1 lub 249825. 1 Pozostanie parametrem produktowym (wcześniej był ofertowym), a 249825 będzie parametrem ofertowym. Otrzymałem informację, że dopiero jutro dla kategorii z oponami parametr 1 zostanie oznaczony jako 249825. Przepraszam za zamieszanie.

**Comment by lukiopmoto** [comment]
ok, dam znać czy faktycznie to zadziała.
