### ISSUE TITLE
[REST] Pobieranie tagów przypisanych do oferty

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#687]
Jak wywołuje metodę GET
https://api.allegro.pl.allegrosandbox.pl/sale/offers/6205652837
to otrzymuje cały draft oferty bez błędów walidacji
natomiast jak wywołam metodę GET
https://api.allegro.pl.allegrosandbox.pl/sale/offers/6205652837/tags
o otrzymuję błąd:
`[{
  "code": "ERROR",
  "message": "Offer 6205652837 not found",
  "details": "OfferNotFoundException",
  "path": null,
  "userMessage": null
}]`
W czym może być problem?

**Comment by PawelTaberski** [comment]
Możliwe, że informacje się jeszcze nie odświeżyły przy danej ofercie. Czy problem nadal występuje mógłbyś jeszcze raz wywołać ten zasób dla tej oferty. W przypadku braku przypisanych tagów powinieneś otrzymać pustą tablicę: 
`{
    "tags": []
}`

**Comment by SlawomirMizerski** [comment]
Cały czas jest ten sam efekt.

**Comment by PawelTaberski** [comment]
Prosiłbym o przesłanie pełnego cURL-a wraz z trace-id przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). Sprawdzimy w czym jest problem. W treści zgłoszenia zaznacz proszę, że informacje są na potrzeby zgłoszenia na GitHub-ie numer 687.
