### ISSUE TITLE
Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji

### ISSUE THREAD

**Issue by MKI-Miro** [allegro/allegro-api#6870]
Hi

As I am author I have a question. Whats wrong with this product request.

POST to sale/product-proposals

`{
	"name": "Manet: Most w Argenteuil",
	"description": null,
	"category": {
		"id": "257813",
		"similar": null
	},
	"images": [{
		"url": "https://a.allegroimg.com/original/11d82b/e07f403e4b699a079781cd3203e2"
	}],
	"parameters": [{
		"id": "224017",
		"name": null,
		"rangeValue": null,
		"values": ["69672"],
		"valuesIds": null,
		"valuesLabels": null,
		"unit": null,
		"options": null
	}, {
		"id": "201325",
		"name": null,
		"rangeValue": null,
		"values": ["1000"],
		"valuesIds": null,
		"valuesLabels": null,
		"unit": null,
		"options": null
	}, {
		"id": "234937",
		"name": null,
		"rangeValue": null,
		"values": ["Manet: Most w Argenteuil"],
		"valuesIds": null,
		"valuesLabels": null,
		"unit": null,
		"options": null
	}, {
		"id": "237210",
		"name": null,
		"rangeValue": null,
		"values": ["D-Toys 1000"],
		"valuesIds": null,
		"valuesLabels": null,
		"unit": null,
		"options": null
	}, {
		"id": "3475",
		"name": null,
		"rangeValue": null,
		"values": null,
		"valuesIds": ["3475_90"],
		"valuesLabels": null,
		"unit": null,
		"options": null
	}, {
		"id": "127812",
		"name": null,
		"rangeValue": null,
		"values": null,
		"valuesIds": ["127812_773421"],
		"valuesLabels": null,
		"unit": null,
		"options": null
	}, {
		"id": "225693",
		"name": "EAN",
		"rangeValue": null,
		"values": ["5947502869672"],
		"valuesIds": null,
		"valuesLabels": null,
		"unit": null,
		"options": {
			"identifiesProduct": true,
			"isGTIN": true
		}
	}],
	"language": "pl-PL"
}`

the response message 
Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji
it not very helpful :(

**Comment by MaciejFrackowiak** [comment]
You shouldn't add information about a similar category - without it, the request will finish OK.

**Comment by MKI-Miro** [comment]
It works, thank you. Error message should be improved :)

**Comment by MaciejFrackowiak** [comment]
You received error 400, which means that the request was incorrect. In this kind of situation, we do not even process requests, because their structure is incorrect - so only the owner of the application which created the request can fix it.
