### ISSUE TITLE
Czy jest możliwość autoryzacji bez angażowania użytkownika z każdym razem?

### ISSUE THREAD

**Issue by androl7** [allegro/allegro-api#6875]
Pytanie takie jak wyżej, chce zrobić dla klienta który ma u Państwa konto funkcję która będzie uruchamiana raz dziennie bez ingerencji użytkownika. Aby to wykonać potrzebuję uderzyć w Endpoint: https://api.allegro.pl/sale/offers. Czy jest możliwość pełnej automatyzacji uwierzytelnienia? Jedyne co znalazłem to Client_credentials flow ale token który otrzymuje nie pozwala na dostęp do tych zasobów. Reszta sposobów uwierzytelnienia czyli Authorization Code flow i Device flow potrzebuje ingerencji użytkownika. Proszę o pomoc w rozwiązaniu tego problemu.

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma takiej możliwości. Użytkownik musi dać Tobie/aplikacji zgodę na wykonywanie operacji w jego imieniu. Zasoby /sale/offers działają w ramach autoryzacji typu "bearer-token-for-user".

**Comment by shivson1337** [comment]
Dodam, że jeśli już raz użytkownik połączy Twoją aplikację ze swoim kontem to bez problemu odświeżasz token przy użyciu refresh tokenu co kilka godzin i tym sposobem możesz mieć ciągłe połączenie bez dalszej ingerencji użytkownika.

**Comment by androl7** [comment]
Dziękuję za szybką odpowiedź. @shivson1337 czyli jeśli chciałbym uruchamiać to raz dziennie czyli co 24h to i tak będę musiał cały proces Device Flow przechodzić od nowa. Drugą opcją jest odświeżać token co wartość podaną w polu 'expires_in', bo za każdym razem będę dostawał nowy bearer token i refresh token? Właśnie znalazłem w dokumentacji że refresh token można używać tylko przez 3 miesiące więc po tym czasie będę musiał i taka angażować znowu klienta? Jest możliwość żebyu refresh token odświerzyć automatycznie?

**Comment by shivson1337** [comment]
Refresh token odświeża się za każdym razem gdy użyjesz go do pozyskania nowego tokenu autoryzacji.
W związku z tym przy Twoim zastosowaniu nie powinno być żadnego problemu z odświeżaniem tokenu co 24h i wykonywaniem akcji.
