### ISSUE TITLE
payments/refunds

### ISSUE THREAD

**Issue by merry75** [allegro/allegro-api#6878]
Hello can you let me know what I am doing wrong I am trying to refund a customer and I get 422

here is traceid 960984c677a59f6

thank you

**Comment by MaciejFrackowiak** [comment]
You have to add to your request information what do you want to refund - you can make a refund for a product, delivery, overpaid, surcharges and additional services. Please, check [our tutorial](https://developer.allegro.pl/tutorials/process-orders-PgPMlWDr8Cv#how-to-refund-a-payment) where we describe the whole process.

**Comment by MaciejFrackowiak** [comment]
It cannot be required because every type is a unique object, so the user has to decide which option to choose.
