### ISSUE TITLE
Offer does not display category parameter being set on it

### ISSUE THREAD

**Issue by antalos** [allegro/allegro-api#6879]
Hello.

Product offer has been created using API: https://allegro.pl/oferta/volkswagen-touran-i-2006-czujniki-cofania-13459421021?item=13459421021

Category parameter 234493 is "1K0919283A". 

But the resulting offer does not show this parameter. It looks like this:
![image](https://user-images.githubusercontent.com/2435016/227466513-b454561f-7850-44e6-b675-c69bf79b2615.png)

Why is this parameter not being showed on offer page?

**Comment by MaciejFrackowiak** [comment]
The parameter "Manufacturer catalog number" has a value "false" assigned to "options.identifiesProduct" in [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct), so as a result we do not show it.

**Comment by antalos** [comment]
Does not it make more sense to show as much information as possible about offer to improve its visibility?

**Comment by MaciejFrackowiak** [comment]
Here, we discuss topics connected directly to Allegro API - if you have a question about WWW, please contact with Allegro Support via [the contact form](https://allegro.pl/pomoc/kontakt).

**Comment by antalos** [comment]
Thanks.
