### ISSUE TITLE
Problem przy pobieraniu ofert 

### ISSUE THREAD

**Issue by pyrekMB** [allegro/allegro-api#6880]
Witam! Z góry przepraszam za laickie pytanie  a siedzę od kilku godzin nad problemem i nie wiem co jest nie tak.

Dodam że od niedawna zacząłem prace nad rest api i jak na razie wszystko szło bez większych problemów.
A problem mam tego typu:
 
Mam na lokalnym serwerze skryty które tworzę i tu mi wszystko działa ok - jest to prosty xampowy serwer.
Po wgraniu na lokalny w firmie - dodam lokalny serwer tez xampp nie działa mi jedna opcja a mianowicie pobieranie ofert zwraca mi taki komunikat:

**Something went wrong 0** 

`

function getCurl($headers, $content) {
    $ch = curl_init();
    curl_setopt_array($ch, array(
        CURLOPT_URL => TOKEN_URL,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => $content
    ));
    return $ch;
}

function getOffers($token)
{

	
    $url = "https://api.allegro.pl/sale/offers?limit=30&offset=0";
 
    $ch = curl_init($url);
 
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, ["Authorization: Bearer $token","Accept: application/vnd.allegro.public.v1+json"]);
 
    $result = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
 
    if ($result === false || $resultCode !== 200) {
        exit ("Something went wrong  $resultCode ");
    }
 
    $offers = json_decode($result);
 
    return $offers;
}
 

 

function main()
{

var_dump(getOffers(TOKEN_OK));

}

main();`

brak pomysłów tym bardziej że autoryzacja działa i inne procesy przechodzą ok.

Bardzo proszę o jakaś podpowiedź

**Comment by PrzemyslawLukanowski** [comment]
Zasugeruj się proszę poniższym kodem. Pochodzi on z wątku z #1566, w którym użytkownik również otrzymywał podobny kod błędu. Być może również inni użytkownicy forum będą w stanie pomóc w rozwiązaniu problemu.

```
function get_data($t){
  $curl = curl_init();

  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://api.allegro.pl/sale/offers?limit=30&offset=0",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "GET",
    CURLOPT_POSTFIELDS => "",
    CURLOPT_HTTPHEADER => array(
      "Accept: application/vnd.allegro.public.v1+json",
      "Authorization: Bearer $t",
      "Content-Type: application/vnd.allegro.public.v1+json"
    ),
  ));
  
  $response = curl_exec($curl);
  $err = curl_error($curl);
  
  curl_close($curl);
  
  if ($err) {
    echo "cURL Error #:" . $err;
  } else {
    echo $response;
  }  
}
```

**Comment by pyrekMB** [comment]
Poprawiłem i mam obecnie tak: https://api.allegro.pl/sale/product-offers/$id_oferta  gdzie id_oferty pobieram wcześniej  
https://api.allegro.pl/sale/offers  i jako wartość offer.id

Kolejnie metodą PATCH próbuje zmienić cenę  https://api.allegro.pl/sale/product-offers/8244154576

dane generuję według wzorca:
`$data = array (
'sellingMode' => [
'price' => [
'amount' => $cena,
'currency' => 'PLN'
]
]
);`

jednak mam BŁAD: **Something went wrong 400**

**Comment by PrzemyslawLukanowski** [comment]
Według naszych logów payload (struktura JSON) nie jest podłączana do requestu, nie otrzymujemy tych danych. Upewnij się, czy w kodzie na pewno prawidłowo uwzględniasz zmienną $data, tak aby te informacje były do nas wysyłane.
