### ISSUE TITLE
Duplikowanie się tworzenia wiadomości

### ISSUE THREAD

**Issue by uranity** [allegro/allegro-api#6881]
Od jakiegoś czasu, mimo, że nie zmieniałem kodu w aplikacji, która wysyła wiadomości (autoresponder), niektóre (ok 2-3% wszystkich) wiadomości są tworzone podwójnie, w odstępie około 300ms.

Czy moglibyście sprawdzić czy po stronie api nie występuje duplikacja?
W formularzu kontaktowym wyślę za chwilę konkretne zapytanie z datą, które poszło do api.

Dziękuję

**Comment by PrzemyslawLukanowski** [comment]
Jak tylko otrzymamy przykłady zweryfikujemy sytuację i wrócimy z odpowiedzią.
