### ISSUE TITLE
Dane na etykiecie

### ISSUE THREAD

**Issue by SlawekMat** [allegro/allegro-api#6882]
Dzień dobry
Chciałbym zapytać co oznaczają na etykiecie wartości SHP DW i SHP DWT
Wydaje mi się, że w DW jest deklarowana przeze mnie waga, ale nie wiem skąd w DWT jest wartość 12
![ab204fcd-44f0-4750-8066-3a8c6453c820](https://user-images.githubusercontent.com/102292350/227526226-087c1866-9968-4088-aff2-48c9bbc8280d.jpg)

**Comment by PrzemyslawLukanowski** [comment]
Pytanie co prawda nie dotyczy API, ale WT to fizyczna waga paczki, a DWT to waga gabarytowa - wyliczona z wymiarów.
