### ISSUE TITLE
Brak dostępu do operacji grupowej

### ISSUE THREAD

**Issue by LukaszWypych** [allegro/allegro-api#6883]
Dzień dobry,
przy zmianie ilości na aukcji używam metody quantityModificationCommandUsingPUT i ona przechodzi pomyślnie. Problem pojawia się przy późniejszej próbie odczytania statusu żądania za pomocą metody getPriceModificationCommandTasksStatusesUsingGET. Otrzymuje taki wyjątek:
```
{"errors":[{"code":"COMMAND_ACCESS_FORBIDDEN","message":"You do not have access to this command — enter valid commandId.","details":null,"path":"","userMessage":"You do not have access to this command — enter valid commandId."}]}
```

Co może być powodem takiego zachowania?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swojego wywołania, wówczas będziemy mogli sprawdzić posiadane logi.
