### ISSUE TITLE
激活allegro账号

### ISSUE THREAD

**Issue by zhouer999** [allegro/allegro-api#6884]
在激活这一步，我已经完成转账激活操作，但是显示账户一直未激活。我应该怎么处理

**Comment by zhouer999** [comment]
Client:105943874
nianianyouyude@outlook.com

**Comment by MaciejFrackowiak** [comment]
You chose a regular account, so it will be activated after your first purchase. Please, also fill in the missing data - name, surname, etc.

**Comment by zhouer999** [comment]
How to register and activate the account if you need to register the application?

**Comment by zhouer999** [comment]
> 

How to register and activate the account if you need to register the application?

**Comment by MaciejFrackowiak** [comment]
Just make a purchase and your account will be activated. Then, you can register your application on the [Managing the Allegro Sandbox applications](https://apps.developer.allegro.pl.allegrosandbox.pl/) site.

**Comment by zhouer999** [comment]
> 只需进行购买，您的帐户就会被激活。[然后，您可以在管理 Allegro 沙盒应用程序](https://apps.developer.allegro.pl.allegrosandbox.pl/)站点上注册您的应用程序。

请问我们在管理 Allegro 沙盒应用程序站点上注册的应用程序在账户被激活后，是否能在正式环境下使用？

**Comment by Lukasz-Zurek** [comment]
@zhouer999 No, the application which you have created on the Allegro Sandbox - cannot be used on the production. It can be used only on the test environment.

**Comment by zhouer999** [comment]
> @zhouer999 No, the application which you have created on the Allegro Sandbox - cannot be used on the production. It can be used only on the test environment.

Then if I want to register the application and use it in the official environment, what should I do?

**Comment by Lukasz-Zurek** [comment]
@zhouer999 You have to [register](https://allegro.pl/rejestracja?origin_url=%2F) the account on production and then register the application [here](https://apps.developer.allegro.pl/), on the production as well.

**Comment by zhouer999** [comment]
> @zhouer999 You have to [register](https://allegro.pl/rejestracja?origin_url=%2F) the account on production and then register the application [here](https://apps.developer.allegro.pl/), on the production as well.

Registering an account in production means registering an application after activating the account by purchasing a product?

**Comment by zhouer999** [comment]
Our account in the production environment has transferred 1.01PLN, but the activation failed, (I see that account activation failed because the details of the owner of the bank account from which you made the transfer were different from the data from the Allegro account settings . Data compliance is a prerequisite for successful account activation.), we need to change which setting information of the Allegro account to activate successfully

**Comment by Lukasz-Zurek** [comment]
> Registering an account in production means registering an application after activating the account by purchasing a product?

Yes, it is an option. You can read more about the activation process in [Allegro Help guide](https://allegro.pl/pomoc/dla-kupujacych/aktywacja-konta/czym-jest-pelna-aktywacja-konta-i-jak-moge-ja-przeprowadzic-GDeq5WOB8uE).

Here, on the GitHub forum we can help you in Allegro Sandbox activation cases only. So in any cases regarding the activation process in the production environment - please use this [contact form](https://allegro.pl/pomoc/kontakt?kategoria=61571da6-f6de-4b8f-9ab9-699c8c797cfc). I am sure that you will receive a quick response and help.

**Comment by Lukasz-Zurek** [comment]
@zhouer999 I cannot help you in the activation process on the production environment. On the GitHub forum we provide support only in the field of Allegro API and Allegro Sandbox.

You have to use [contact form](https://allegro.pl/pomoc/kontakt?kategoria=61571da6-f6de-4b8f-9ab9-699c8c797cfc) and ask about the details regarding the verification process on the production.
