### ISSUE TITLE
Utrata autoryzacji, odświeżanie nie przynosi efektów - http 400

### ISSUE THREAD

**Issue by uranity** [allegro/allegro-api#6885]
Od kilku dni niektóre podpięte konta tracą autoryzację, a odświeżenie tokenów nie działa. Proszę o sprawdzenie w czym problem.

> Token może dodatkowo wygasnąć jeśli. np. zostanie już zużyty (bo wygenerujesz nową parę) albo kiedy użytkownik otrzyma blokadę, zmieni hasło lub adres mailowy.

Hasło nie zostało zmieniane. Przy próbie tworzenia nowej pary api zwraca http 400 z błędem, że nieprawidłowy refresh token. Co może być przyczyną utraty tokena? Aplikacja codziennie odświeża tokeny dla podpiętych kont więc nie mogły wygasnąć. Jest to uciążliwe, bo klienci musza ponawiać autoryzację w przeglądarce.

Ciekawe jest to, że dotyczy to tylko niektórych kont. Stąd moja dezorientacja. 

Proszę o pomoc.

W formularzu kontaktowym wysyłam szczegóły jednego z zapytań.

**Comment by MaciejFrackowiak** [comment]
Jak tylko dotrze do nas Twoje zgłoszenie, spojrzymy w logi.

**Comment by uranity** [comment]
2 dni temu wysłałem :/ Wysłać jeszcze raz?

**Comment by MaciejFrackowiak** [comment]
Zgłoszenie musi być do nas przekazane przez obsługę Allegro, a to zawsze chwilę trwa. Jeżeli nic do nas do jutra nie dotrze, poproszę Cię o napisanie ponownej wiadomości.

**Comment by uranity** [comment]
Sytuacja się powtórzyła. W ciągu kilkunastu godzin wiele kont (większość ok) z tej aplikacji, straciło ważność tokena przez co 2 dni nie działały usługi. To dość duża strata dla naszej appki.
Proszę o informację gdzie dokładnie wysłać szczegóły. Ostatnio chyba nie dotarło albo odpowiedź do mnie nie dotarła.

Dziekuję

**Comment by MaciejFrackowiak** [comment]
Napisz proszę poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) podając informację, że dane dot. GitHub 6885. Oczywiście w korespondencji przekaż przykładowy token, który wygasł + orientacyjny czas wystąpienia problemu.
