### ISSUE TITLE
Błąd zależności parametrów Próba srebra (206658) i Materiał (15835)

### ISSUE THREAD

**Issue by bzass** [allegro/allegro-api#6886]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

POST /sale/product-offers
Trace-id: ca0bc82cd529b371

Pełny cURL z parametrami w załączniku.

Podczas wystawiania oferty w kategorii Wisiorki (123448) wymagane jest podanie parametru obowiązkowego Materiał (15835). Istnieją też dwa opcjonalne parametry zależne od tego parametru: próba srebra (do określenia kiedy materiał ma wartość "srebro") oraz próba złota (do określenia kiedy materiał ma wartość "złoto"). 

W przypadku tworzenia oferty, której materiał to złoto (bez wskazania parametru "próba srebra") Allegro zwraca błąd:

```
Parametr zależny Próba srebra (206658) nie może przyjąć wartości [925], gdy parametr Materiał (15835) ma wartości [złoto].
```

Wygląda to tak jakby Allegro zawsze domyślnie przyjmowało wartość 925 dla parametru "próba srebra (206658)" (nawet kiedy nie został przekazany w requeście). Uniemożliwia to wystawienie produktów ze złota (które nie mają ustawionej wartości "srebro" w parametrze Materiał).

W załączniku cURL pokazujący dokładnie problem (produkt z wartością "złoto" jako materiał, z ustawioną wartością "próba złota" ale bez ustawionego parametru "próba srebra" zwraca błąd o przekazanej błędnej wartości parametru "próba srebra"). Aby potwierdzić błąd wystarczy sprawdzić, że w załączonym cURL nie ma parametru 206658.

[cURL-parameter-dependency-issue.txt](https://github.com/allegro/allegro-api/files/11072446/cURL-parameter-dependency-issue.txt)

**Comment by PrzemyslawLukanowski** [comment]
Wprowadziliśmy zmiany w produkcie, problem nie powinien już występować.

**Comment by bzass** [comment]
Bardzo dziękuję, rzeczywiście problem rozwiązany.
