### ISSUE TITLE
Aktywacja konta testowego

### ISSUE THREAD

**Issue by lhascilo** [allegro/allegro-api#6892]

**Comment by MaciejFrackowiak** [comment]
Proszę podaj identyfikator użytkownika lub login konta, wówczas będziemy mogli rozpocząć proces weryfikacji.

**Comment by MaciejFrackowiak** [comment]
Proszę uzupełnij dane na swoim koncie - imię, nazwisko, dane adresowe, a następnie dokonaj testowego zakupu, opłać go, wówczas konto zostanie zweryfikowane.
