### ISSUE TITLE
Możliwość modyfikacji/dodania/usunięcia dodanego numeru listu przewozowego.

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#6895]
Witam, czy po utworzeniu listu przewozowego dla danego zamówienia, jest możliwość podmienienia jego numeru na późniejszym etapie/dodanie nowego aby unieważnić poprzedni?

**Comment by Sebastian-Le** [comment]
Możesz 'zarządzać' listami a dokładniej, przekazując ParcelID jako payload,
ParcelID, jak się nic nie zmieniło w obsłudze API, musisz przechowywać gdzieś lokalnie u siebie

https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY

**Comment by Lukasz-Zurek** [comment]
@Maciej-Wilkosz Jeżeli chodzi Tobie o utworzenie np. kolejnej paczki do jednego zamówienia to jest to możliwe. Numer kolejnej przesyłki zostanie dopisany do zamówienia.

**Comment by Maciej-Wilkosz** [comment]
@Lukasz-Zurek Chodzi o możliwość modyfikacji już istniejącej paczki - numeru listu przewozowego. To dotyczy endpointu /order/checkout-forms/{numerZamowienia}/shipments. Czy dodane w ten sposób pole "Waybill" można potem modyfikować lub anulować przesłany w ten sposób waybill i wysłać nowy?

**Comment by Lukasz-Zurek** [comment]
@Maciej-Wilkosz Ok, rozumiem. Niestety możesz jedynie dodać nowy numer listu przewozowego, lub kilka. Nie możesz jednak ich modyfikować czy anulować.
