### ISSUE TITLE
Czy Allegro zamierza dodać do API wsparcie dla QUIC/HTTP3?

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#6896]
Witam,
Czy Allegro zamierza dodać do API wsparcie dla QUIC/HTTP3? Mogłoby to pomóc w niektórych przypadkach, gdy klient ma kiepskie połączenie z siecią chociażby.

Pozdrawiam.

**Comment by Lukasz-Zurek** [comment]
@hahyes Zespół odpowiedzialny za ten segment od pewnego czasu analizuje temat, jednak na ten moment jako Serwis nie mamy jeszcze żadnych konkretnych dat i podjętych decyzji.

**Comment by hahyes** [comment]
@Lukasz-Zurek Szkoda. Jak mówiłem, zdecydowanie na słabszych połączeniach poprawiłoby to jakość korzystania zarówno z API jak i portalu. Pozdrawiam.
