### ISSUE TITLE
Problem z aktualizowaniem aukcji o stanie zerowym

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#6898]
Mam ofertę
[13156281088](http://allegro.pl/item13156281088.html)
która zakończyła się ze względu na wyprzedany cały stan (stan = 1 / sprzedane = 1)

Jak ją aktualizujemy przez API dostajemy zwrotkę "niepoprawna liczba sztuk", W jaki sposób mogę taką aukcję przywrócić? Czy konieczne jest wystawienie nowej aukcji?

**Comment by MartaNowaczyk** [comment]
@DamianKAtomStore z tego co widzę oferta nadal ma stan = 0. Poza tym co piszesz, jest też problem z produktem, który powinien być podpięty do oferty. Dodaj produkt, wtedy powinieneś zaktualizować ofertę.
Jeśli dostajesz jakiś błąd lub chcesz wskazać swoje działania - np. gdy zmieniasz liczbę produktów, a mimo tego stan się nie zmienia, przesyłaj dla takich przypadków trace-id, to bardzo przyspiesza weryfikację.

**Comment by DamianKAtomStore** [comment]
Czyli najpierw wymagana jest aktualizacja samej ilosci sztuk. Czy w tym momencie będę wstanie aktualizować oferte czy dodanie produktu też jest konieczne?

**Comment by DamianKAtomStore** [comment]
Chciałbym odrazu się zapytać z czego wynika że aukcja nie jest połączona z produktem, z tego co mi wiadomo nie pozwalacie na wystawianie /sale/product-offers bez eanu

**Comment by MartaNowaczyk** [comment]
Z informacji, które mam wynika, że do oferty nie był podpięty produkt. Podepnij produkt i zmień liczbę sztuk, aby aktywować tę ofertę. Bez dodania produktu aktualizacja nie będzie możliwa. 
Jeśli chodzi o to, dlaczego oferta nie miała podpiętego produktu, to będzie ciężko to zweryfikować, bo nie mam już logów. Być może kategoria kiedyś na to pozwalała.
