### ISSUE TITLE
Nieprawidłowy carrierId na sprawdzaniu statusu doręczenia przesyłki

### ISSUE THREAD

**Issue by mtanasiewicz** [allegro/allegro-api#6899]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [?] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

traceId z tworzenia przesyłki: 2e020b1dec41a9d9
traceId z trackingu: 926c56999ce91438

Podczas tworzenia przesyłki za pomocą przewoźnika o zmienionej nazwie `RUCH` -> `ORLEN` zwracacie w szczegółach przesyłki `carrierId` jako `ORLEN`. Następnie po przekazaniu tego carrierId w urlu trackingu `https://api.allegro.pl/order/carriers/ORLEN/tracking?waybill=2100676601223` dostajemy 400 
```
{
  "errors": [
    {
      "code": "INTEGRATOR_STATUSES_ILLEGAL_ARGUMENT",
      "message": "Carrier id ORLEN is not allowed. Allowed carrier ids: [4PX_EXPRESS, ALLEGRO, AMBRO_EXPRESS, AUSTRIAN_POST_EXPRESS, AUSTRIAN_POST_REGISTERED, CAINIAO, CHINA_EMS, CHINA_POST, CHUKOU1, CNE_EXPRESS, DB_SCHENKER, DHL, DPD, DSV, DTS, ESHIPPING_GLOBAL, EXELOT, FEDEX, FLYT_EXPRESS, GEBRUDER_WEISS, GEIS, GLS, INPOST, JAPAN_POST, KARGOM_KOLAY, KN, LA_POSTE, LITHUANIAN_POST, MEEST, NA_DZISIAJ, NO_LIMIT, PACKETA, PICKPACK, POCZTA_POLSKA, POSTNORD, PTS, RABEN, RHENUS_LOGISTICS, RUCH, SFC, SF_EXPRESS, SHIPTER, SKYNET, SUNYOU, SUUS, TNT_EXPRESS, UKR_POSHTA, UPS, WANB_EXPRESS, WEDO, X_PRESS_COURIERS, YANWEN, YUN_EXPRESS, ZIGZAG]",
      "details": null,
      "path": "/order/carriers/ORLEN/tracking",
      "userMessage": "Identyfikator kuriera: ORLEN jest niedozwolony. Dopuszczalne identyfikatory kurierów to: [4PX_EXPRESS, ALLEGRO, AMBRO_EXPRESS, AUSTRIAN_POST_EXPRESS, AUSTRIAN_POST_REGISTERED, CAINIAO, CHINA_EMS, CHINA_POST, CHUKOU1, CNE_EXPRESS, DB_SCHENKER, DHL, DPD, DSV, DTS, ESHIPPING_GLOBAL, EXELOT, FEDEX, FLYT_EXPRESS, GEBRUDER_WEISS, GEIS, GLS, INPOST, JAPAN_POST, KARGOM_KOLAY, KN, LA_POSTE, LITHUANIAN_POST, MEEST, NA_DZISIAJ, NO_LIMIT, PACKETA, PICKPACK, POCZTA_POLSKA, POSTNORD, PTS, RABEN, RHENUS_LOGISTICS, RUCH, SFC, SF_EXPRESS, SHIPTER, SKYNET, SUNYOU, SUUS, TNT_EXPRESS, UKR_POSHTA, UPS, WANB_EXPRESS, WEDO, X_PRESS_COURIERS, YANWEN, YUN_EXPRESS, ZIGZAG]"
    }
  ]
}
```

Jak zmienimy `carrierId` z `ORLEN` na `RUCH` to endpoint trackingu zwraca statusy przesyłki.

Api powinno albo zwracać dalej `RUCH` na tworzeniu przesyłki, albo obsługiwać `ORLEN` na trackingu.

**Comment by mtanasiewicz** [comment]
Uprzejmie prosimy o ifnormację, czy to jest bug, czy zamierzone działanie systemu oraz czy i kiedy ewentualnie zostanie to poprawione. Musimy szybko obsłużyć ten problem na produkcji, jeżeli to zachowanie systemu nie zostanie poprawione w najbliższym czasie.

**Comment by Lukasz-Zurek** [comment]
@mtanasiewicz Dziękuję za dokładne opisanie sytuacji. Konsultuję tę sprawę z zespołem odpowiedzialnym za usługę "Wysyłam z Allegro". Wkrótce wrócę do Ciebie z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
@mtanasiewicz Wracam z informacją - jest to bug po naszej stronie. Nie jestem jednak w stanie podać terminu wdrożenia poprawki, aczkolwiek mogę zapewnić, że jest to dla nas priorytetowe. Jak tylko uzyskam informacje dotyczące wdrożenia poprawki - dam znać w tym wątku.

**Comment by mtanasiewicz** [comment]
OK dziękuję za informację. Wdrożyliśmy poprawkę po naszej stronie. Znaleźliśmy jednak kolejnego buga. API zaczęło nam zwracać błędy walidacji przesyłek na tym samym kurierze ze statusem HTTP 200. Response wyglądał tak
```
{
  "id": "43192138-d204-4d9f-ab92-113d7a2d7074",
  "parcelId": null,
  "status": "ERROR",
  "errors": [
    {
      "code": "ERROR",
      "message": "Receiver street is too long (max 35)",
      "details": null,
      "path": "receiver.address.street",
      "userMessage": "Wartość pola ulica dla adresu odbiorcy, jest zbyt długa (max 35)."
    }
  ]
}`

A status HTTP był 200 OK. Obsłużyliśmy tą sytucję również "na szybko" przeszukując treść odpowiedzi pod kątem zawarcia słówka "ERROR". Dobrze byłoby jednak, gdyby API zwracało poprawne statusy HTTP, gdyż nie jest to najlepsze rozwiązanie.

**Comment by mtanasiewicz** [comment]
Ten drugi zgłoszony bug okazał się być źle obsłużony po naszej stronie. Endpoint działa poprawnie.

**Comment by Lukasz-Zurek** [comment]
@mtanasiewicz Ok, dziękuję za informację.
