### ISSUE TITLE
Timeouty - wolne działanie API

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#69]
Czy notujecie ostatnio spowolnienie działania webapi? Mamy wiele informacji od klientów, że to aukcje się nie wystawiają i leci timeout (potrafią się nawet wystawić wielokrotnie), wydłużyło się pobieranie sprzedaży, nie wszystkie dane się pobierają (zapewne również przez timeout). Mowa o API soapowym.
U jednego z klientów timeouty trzeba było ustawić na niemal minutę aby webapi przetworzyło request i zwróciło odpowiedź.

**Comment by esprzedaz** [comment]
Tak, wystawianie i edycja ofert od parunastu minut zamula okrutnie.

**Comment by Onixarts** [comment]
My obserwujemy to od około 2 tygodni.

**Comment by MarcinLuczak** [comment]
Czy powolne działanie zaobserwowaliście tylko w niektórych momentach/okresach w ciągu dnia, czy występuje cały czas?

**Comment by Onixarts** [comment]
Nie mam takich informacji od użytkowników. Aczkolwiek wczoraj czy dzisiaj wystawiając aukcję testowo na Allegro w godzinach 10-15 musiałem zwiększyć timeout do 30s, bo przy 20s co 4 request dostawał timeouta. W aukcji wrzucone około 10 zdjęć, rozmiary raczej średnio małe, przy dużych to by chyba z minutę szła jedna aukcja.

**Comment by MarcinLuczak** [comment]
@Onixarts pamiętaj, że w niektórych godzinach z serwisu może korzystać znacznie więcej użytkowników i wtedy czas odpowiedzi może się lekko wydłużyć.

**Comment by Onixarts** [comment]
@MarcinLuczak zdaję sobie z tego sprawę, z tym, że twierdzę iż sytuacja w ciągu ostatnich 2 tygodni mocno się pogorszyła w stosunku do 10 lat wstecz - nie pamiętam aby tego typu masowe zgłaszanie problemów z timeoutem kiedykolwiek wystąpiło. Stąd moje pytanie, czy ktoś jeszcze zauważył znaczne spowolnienie działania.

**Comment by kormichu** [comment]
U nas to samo i także musimy się ratować zwiększonym timeoutem

**Comment by MarcinLuczak** [comment]
@kormichu @Onixarts @esprzedaz 
Abyśmy mogli dokładniej zbadać to zgłoszenie, potrzebujemy więcej informacji. Poproszę o info:

- dla jakich metod,
- dla jakich użytkowników,
- dla jakich kluczy

występuje problem oraz, jeśli macie takie informacje, w jakich przedziałach czasowych spowolnienie jest widoczne.

**Comment by Onixarts** [comment]
Dzisiaj u mnie idzie znacznie szybciej. Ostatnio bywało (w godzinach 8-16), że jedna aukcja wystawiała się 15-25s. Dziś 3-6. Nie wiem natomiast jak to wygląda u użytkowników.

**Comment by kormichu** [comment]
Spowolnienie działania API zauważyliśmy po raz pierwszy po niewyrabiających workerach pobierających aukcje / zamówienia w dniu 23.02 pomiędzy 02:30, a 03:00

**Comment by MarcinLuczak** [comment]
@kormichu A obecnie? Czy dzisiaj lub ciągu kilku poprzednich dni takie spowolnienie nastąpiło? W jakich dniach i godzinach?

**Comment by awronski** [comment]
Mamy tak samo, dokładnie od wieczora 6 kwietnia.

@MarcinLuczak Czy możecie potwierdzić, że występują problemy z API?

Od wczoraj mamy problemy z wystawieniem aukcji.
Dostajemy: `Błędny identyfikator sesji. Proszę spróbować zalogować się jeszcze raz! `

**Comment by anih** [comment]
@awronski cachujesz poprawnie identyfikatory sesji? Z mojego doświadczenia to cachujesz identyfikator sesji per serwer do momentu aż się przedawni, w pythonie mam dekorator który jak wyłapie ten błąd to odświeża sesję i ładnie działa.

**Comment by awronski** [comment]
@anih Dzięki za sugestię i zbadam ten temat.
Ale wydaje mi się, że jednak u mnie problem jest inny.

Aplikacje działa już od ładnych paru lat a problem z sesjami mamy od piątku wieczór.


Dokumentacja mówi:

Identyfikator sesji, otrzymany w wyniku wywołania metod doLogin(Enc), zachowuje ważność przez jedną godzinę od momentu jego utworzenia. Dodatkowo - sesja ma charakter odnawialny. **Oznacza to, że wywołanie jakiejkolwiek metody wymagającej podania identyfikatora sesji spowoduje, że czas trwania tej sesji będzie naliczany od nowa.**

A my wywołujemy metody co parę minut. Dlatego podejrzewam, że jednak coś allegro zmieniło?

**Comment by anih** [comment]
a to jeszcze ciekawe info jest w FAQ:
`
Identyfikator sesji, otrzymany w wyniku wywołania metod doLogin(Enc), zachowuje ważność przez jedną godzinę od momentu jego utworzenia. Dodatkowo - sesja ma charakter odnawialny. Oznacza to, że wywołanie jakiejkolwiek metody wymagającej podania identyfikatora sesji spowoduje, że czas trwania tej sesji będzie naliczany od nowa.

Dla każdego użytkownika obowiązuje limit maksimum 10 jednocześnie otwartych sesji. W przypadku otwarcia 11-tej z kolei, ta najwcześniej utworzona zostanie automatycznie zamknięta. 
`
;)

**Comment by anih** [comment]
więc obstawiam, że spowolnienie w allegro mogło spowodować, że możesz mieć więcej jednoczesnych połączeń i otwieranych sesji w tym samym czasie

**Comment by awronski** [comment]
Czytałem to. Bardzo ciekawe spostrzeżenie. Faktycznie przy wielowątkowości mogłoby się tak zdarzyć.

Jednak w apce trzymamy zawsze wyłącznie najnowszy numer sesji więc raczej wykluczam ten problem.
(Singleton z synchronizowanym dostępem)

**Comment by MarcinLuczak** [comment]
@anih @awronski 
> Czy możecie potwierdzić, że występują problemy z API?

Nie potwierdzam. Nie mamy także innych zgłoszeń dotyczących opóźnień.

> Od wczoraj mamy problemy z wystawieniem aukcji. Dostajemy: Błędny identyfikator sesji. Proszę spróbować zalogować się jeszcze raz!

Kwestię tych problemów rozwiązujemy w wątku #121
