### ISSUE TITLE
REST API - ocena produktu

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#690]
Czy można uzyskać obcenie lub planujecie Państwo udostępnienie metod do pobierania "ocen produktu"?
(Informacja, która się wyświetla w prawym górnym rogu oferty, pod tytułem.)

**Comment by PawelTaberski** [comment]
Obecnie nie planujemy wdrożenia metod związanych z ocenami produktowymi i opiniami w REST API. Jeśli będziemy planowali wdrożenie takich zasobów poinformujemy o tym.

**Comment by PawelTaberski** [comment]
Masz racje jak najbardziej słuszna uwaga zgłosiłem Twoją sugestię o dodanie takich zasobów. Jeśli zdecydujemy się dodać takie rozwiązania poinformujemy o tym.
