### ISSUE TITLE
Competitors price

### ISSUE THREAD

**Issue by merry75** [allegro/allegro-api#6900]
How can I check competitors price with your api ?

**Comment by merry75** [comment]
Hmm I see so you can not reprice against competitors by api ?

Also I noticed you have a lot of ean mismatch issue in your catalog  api do you have a solution for this issue ?

**Comment by Lukasz-Zurek** [comment]
@merry75 No, it is not possible.

Another thing regarding Ean mismatch - there can be specific issues but it always depends on the situation. If there is an incorrect data in a product - you can report it using [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal). You will find more information right [here](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-report-incorrect-data-in-a-product).

But if it's not the case - please give us some trace-ids. We will verify them.
