### ISSUE TITLE
Brak paczek w zbiorze z nowych metod Pocztexa

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#6901]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other
 
Włączyliśmy nową metodę dostawy : Allegro Odbiór w Punkcie Pocztex,
List (czy jego numer) się tworzy, ale paczka nie pojawia się w zbiorze po stronie e-nadawcy.

Problem występuje w środowisku produkcyjnym jak i testowym ( api i front ).
Id dla sandboxa :
b00f277e-4523-4164-bc27-2a0aca87b367
931f0929-1db8-4f65-bd88-60f6a82c0cbb

**Comment by Lukasz-Zurek** [comment]
Skontaktuj się proszę w tej sprawie z Pocztą Polską. Niestety nie mamy możliwości dokładnego zweryfikowania tego po naszej stronie. Sprawdziłem wskazane commandID i tu nie odnotowałem błędów. Przekazujesz również "pocztex"w additionalServices, w związku z czym być może problem może leżeć po stronie umowy, lub bezpośrednio po stronie narzędzia e-nadawca.

**Comment by paafcioc22** [comment]
Dzięki.. w poczcie w sumie też nie wiedzą a czym polega problem ;/
