### ISSUE TITLE
Problem adding an offer - "You have to add at least 1 image".

### ISSUE THREAD

**Issue by din1s** [allegro/allegro-api#6902]
Good afternoon
There was a problem when adding offers for API products - the error "ConstraintViolationException.GallerySize - You have to add at least 1 image." is returned.

Until recently, everything worked without problems. The picture of the product was transmitted only when adding the product, it was not required for the offer. Has something changed in the work of the API?

**Comment by Lukasz-Zurek** [comment]
From March 20, 2023, we require each offer to have a minimum of 1 photo. So when you try to list an offer or make any changes, we will check if the condition has been met.

Obviously if you provided at least 1 image and you still receive this error - please send trace-id of your request.
