### ISSUE TITLE
Ustawienie procesu wysyłki allegro WzA w magazynie fulfillmentowym.

### ISSUE THREAD

**Issue by MartaNowaczyk** [allegro/allegro-api#6906]
### Discussed in https://github.com/allegro/allegro-api/discussions/6905

<div type='discussions-op-text'>

<sup>Originally posted by **lhascilo** March 30, 2023</sup>
Dzień dobry,

Jesteśmy firmą fulfillmentową zajmującą się obsługą sklepów internetowych. Kliencie, którzy sprzedają produkty na allegro pobierają zamówienia z allegro do swoich systemów ERP, a następnie nasz WMS pobiera te zamówienia do siebie. Chciałbym poprawnie ustawić proces generowania etykiet kurierskich SMART za pomocą WzA. Moje pytanie jest takie, jakie funkcje powinienem okodować ? W jaki sposób Allegro znajdzie części wspólne zamówienia przesłanego z jego ERP do naszego WMS ?</div>

**Comment by lhascilo** [comment]
Dziękuje bardzo za odpowiedź. Czyli jak dobrze rozumiem, możemy używać swojego kontaktu np. z UPS, DPD, Inpost, etc. i jeżeli przekażemy maskowany adres email. To wtedy zamówienie zostanie przypisane do sprzedawcy, który ten adres email nam przekazał ?

**Comment by MartaNowaczyk** [comment]
Tak, maskowany email zawiera informację o danej transakcji, zawsze powinieneś przekazywać prawidłowy, zamaskowany adres email. Dotyczy to ogólnych zasad nadawania przesyłek rozliczanych w ramach SMART, dlatego więcej znajdziesz w [pomocy allegro](https://allegro.pl/pomoc/dla-sprzedajacych/informacje-dla-sprzedajacych/allegro-smart-jak-poprawnie-nadawac-przesylki-wq3Mxx1vMf2).

**Comment by lhascilo** [comment]
Dziękuje Pani Marto, Wychodzi na to, że otrzymałem sprzeczne informacje od naszego opiekuna. Czy istnieje możliwość krótkiego telko z kimś z supportu w celu wyjaśnienia naszych wątpliwości ?

**Comment by MartaNowaczyk** [comment]
Możecie zawsze napisać do swojego opiekuna, który się z nami skontaktuje, by wyjaśnić wątpliwości.

**Comment by lhascilo** [comment]
To podpytam jeszcze o generowanie etykiet. Jaka metoda służy do wygenerowania etykiety kurierskiej w WzA ?

**Comment by MartaNowaczyk** [comment]
Cały proces zarządzania przesyłkami, jak również utworzenie etykiety znajdziesz w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY).
