### ISSUE TITLE
Can I create a sandbox account without PL VAT ID?

### ISSUE THREAD

**Issue by radimzhor** [allegro/allegro-api#6907]
We are CZ developers and we need to create sandbox accounts for testing API. However, the registration requires a PL VAT ID, which we don't have. How to create a sandbox without PL VAT ID?

**Comment by Lukasz-Zurek** [comment]
As the Allegro Sandbox is our test environment - please use one of the generators available online (to generate PL VAT ID/NIP). You do not have to provide real data. Actually, I would suggest giving it a fictitious one in the data which you want to provide for this test account.
