### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by LukaszWypych** [allegro/allegro-api#6908]
Dzień dobry,
przy próbie zaktualizowania awiza One Fulfillment za pomocą metody "updateAdvanceShipNotice" dostaje odpowiedź
```
{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Try again in a few minutes."}]}
```
trace-id: 2e5eb280a635c6a7
środowisko: sandbox

**Comment by Lukasz-Zurek** [comment]
Sprawdziłem logi i wszystko wskazuje na to, że w polu shipping.method" wprowadzasz nieprawidłową wartość:

`"ThirdPartyDeliveryShipping"`,

prawidłowa to:

`“THIRD_PARTY_DELIVERY”`

**Comment by LukaszWypych** [comment]
Dziękuje, winą były źle wygenerowane model dla tego typu wysyłki. Powodem tego jest brak pola method w obiekcie ThirdPartyDeliveryShipping w pliku yaml. Po poprawieniu ręcznie klasy dla tego typu wysyłki request przeszedł poprawnie

**Comment by Lukasz-Zurek** [comment]
Ok, również dziękuję za informację. Cieszę się, że udało się wyjaśnić ten problem.
