### ISSUE TITLE
[Sandbox] Powiązanie kont

### ISSUE THREAD

**Issue by inTestowy** [allegro/allegro-api#6909]
Czy mogę prosić o wykonanie operacji 'Powiązania kont': 

intest2.testowy@gmail.com 
intest.testowy@gmail.com

oraz aktywacji sprzedaży dla konta: intest.testowy@gmail.com

**Comment by MartaNowaczyk** [comment]
Jak tylko uda mi się zweryfikować problem z aktywacją konta [intest.testowy@gmail.com](mailto:intest.testowy@gmail.com), wrócę z informacją.
Konta powinieneś powiązać samodzielnie przez zakładkę "[Powiąż swoje konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/powiazane-konta)".

**Comment by MartaNowaczyk** [comment]
Przy powiązaniu kont, w kodzie do potwierdzenia wpisz TestToken1234
