### ISSUE TITLE
Metoda POST /messaging/messages - jak dodać w sprawie jakiego zamówienia

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#6910]
Witam, mam pytanie, bo w dokumentacji nie widze, jak wysłać wiadomość do użytkownika za pomocą metody [POST /messaging/messages](https://developer.allegro.pl/documentation/#operation/newMessagePOST) tak, żeby mozna było podać id zamówienia o które chodzi?

**Comment by MartaNowaczyk** [comment]
Witam, numer zamówienia możesz podać w treści wiadomości (text).
