### ISSUE TITLE
Brak danych śledzenia przesyłki Allegro

### ISSUE THREAD

**Issue by shivson1337** [allegro/allegro-api#6914]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

W niektórych przypadkach gdy odwołujemy się do zasobu _order/carriers/ALLEGRO/tracking_ w celu pobrania danych śledzenia przesyłki, otrzymujemy w odpowiedzi **null** dla **trackingDetails**.

Do tej pory nie zauważyliśmy wspólnego mianownika dla tych przesyłek.

**Przykładowe trace-id:** 7f80bfb6f6799261

**Comment by Lukasz-Zurek** [comment]
Dziękuję za szczegółowy opis zgłoszenia. Sprawę konsultuję z odpowiednim zespołem. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@shivson1337 Otrzymałem informację o opóźnieniach po stronie operatora, stąd zaistniała sytuacja. Czy w przypadku innych, nowych przesyłek problem nadal się powtarza?

**Comment by shivson1337** [comment]
Monitorujemy po naszej stronie. Jeżeli w ciągu 48 godzin nie pojawi się nic nowego, zamknę zgłoszenie. :)

**Comment by Lukasz-Zurek** [comment]
@shivson1337 Ok, dziękuję za informację.
