### ISSUE TITLE
Błąd "This parameter can be entered only once"

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#6915]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

Podczas wykonywania PUT /sale/offers otrzymuję błąd "This parameter can be entered only once.". Jaka jest przyczyna? Wykonuję zwykłą zmianę ilości lub ceny robiąc GET /sale/offers i PUT /sale/offers.

Przykładowy trace-id: 48c6259fb6f47659

**Comment by MartaNowaczyk** [comment]
Weryfikuję sprawę, wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Problemowy okazał się parametr 223497. W tej kategorii zaktualizowaliśmy parametr 223497 i zmieniliśmy jego ID na 249782. Aktualnie podajesz oba parametry, ten stary i ten nowy (Seria wydawnicza 223497 i Seria 249782), stąd komunikat. Najlepiej jak podasz tylko ten nowy **Seria 249782**. Zdaję sobie sprawę, że nie jest on jasny, dlatego będziemy go poprawiać.

**Comment by tomylee0** [comment]
Tutaj przykład z dziś dla GET'a który zwrócił parametr w dwóch postaciach:
trace-id: 7a059311241d1426

A potem PUT z błędem "This parameter can be entered only once.":
trace-id: 7a94865ea605519f

**Comment by MartaNowaczyk** [comment]
Dzięki za informację. Sprawdzimy to po swojej stronie w takim razie.

**Comment by tomylee0** [comment]
Chciałbym się przypomnieć z tematem. Poniżej tylko kilka przykładów dla różnych ofert dla których GET /sale/offers zwraca nieprawidłowy zestaw parametrów:
trace-id: dc7575fbc23dadfd
trace-id: 488b308712cc1f58
trace-id: 176e90f1c6185b05

Powoduje to, że tych ofert nie udaje się w ogóle UPDATE'ować.

**Comment by MartaNowaczyk** [comment]
Przekazałam te przypadki do odpowiedniego zespołu, także wrócę z informacjami jak tylko będzie to możliwe.
