### ISSUE TITLE
Błąd nadania przesyłki przez Allegro Kurier DHL

### ISSUE THREAD

**Issue by krzwaw83** [allegro/allegro-api#6917]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Podczas wywoływania PUT endpointu /parcel-management/parcel-create-commands/{commandId} (https://developer.allegro.pl/documentation#operation/createNewParcel) dla usługi kurierskiej DHL (Allegro Kurier DHL) w której wykorzystano commandId = af528acf-d812-4a58-803c-5e9c7e0ad223 otrzymuję zwrotkę:
```
object(stdClass)#2154 (4) {
  ["id"]=>
  string(36) "af528acf-d812-4a58-803c-5e9c7e0ad223"
  ["parcelId"]=>
  NULL
  ["status"]=>
  string(5) "ERROR"
  ["errors"]=>
  array(1) {
    [0]=>
    object(stdClass)#2161 (5) {
      ["code"]=>
      string(5) "ERROR"
      ["message"]=>
      string(31) "Service unavailable for carrier"
      ["details"]=>
      NULL
      ["path"]=>
      string(14) "pickup.pointId"
      ["userMessage"]=>
      string(40) "Usługa niedostępna u tego przewoźnika"
    }
  }
}
```

Z czego to wynika ?

**Comment by MartaNowaczyk** [comment]
Gdy zamawiasz podjazd kuriera pod adres należy wypełnić strukturę pickup, jednak pominąć pickup.pointId (id punktu nadawczego) tzn. pickup.pointId powinien być używany tylko w przypadku, gdy użytkownik chce dostarczyć paczkę samodzielnie do punktu nadawczego.

**Comment by MartaNowaczyk** [comment]
@krzwaw83 W tym przypadku błąd wskazuje na to, że wybrana przy tworzeniu przesyłki metoda dostawy nie jest zgodna z tą wybraną przez kupującego w zamówieniu.
