### ISSUE TITLE
need acces to sandbox

### ISSUE THREAD

**Issue by worzala86** [allegro/allegro-api#6918]
f9930b4f71bc40ebbded18a8ba425860
worzala86@gmail.com

[Zapoznaj się z zasadami korzystania z forum API Allegro na GitHubie](https://github.com/allegro/allegro-api/wiki#zasady-korzystania-z-forum-api-allegro-na-githubie)
[REST API](https://developer.allegro.pl/)
[Uwierzytelnianie i autoryzacja](https://developer.allegro.pl/auth/)
[Jak wystawić ofertę](https://developer.allegro.pl/sale/)
[Jak zarządzać ofertami](https://developer.allegro.pl/my_offers/)
[Jak obsługiwać zamówienia](https://developer.allegro.pl/orders/)
[Jak zarządzać zestawami i rabatami](https://developer.allegro.pl/offer_bundles/)
[Jak utworzyć ofertę wielowariantową](https://developer.allegro.pl/multi_variant_offers/)
[Jak powiązać ofertę z produktem](https://developer.allegro.pl/product_offers/)
-->

**Comment by MartaNowaczyk** [comment]
Konto, które podałeś to konto zwykłe. Jeśli chcesz "sprzedawać" [załóż konto firmowe](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F).
