### ISSUE TITLE
Parametry obowiązkowe w API

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6919]
Czy z poziomu API jestem w stanie w jakiś sposób sprawdzić, które oferty posiadają nieuzupełnione obowiązkowe parametry? Coś na wzór zakładki "Uzupełnij parametry"

**Comment by MartaNowaczyk** [comment]
Możesz to sprawdzić przez API, gdy skorzystasz z [GET /sale/offers/unfilled-parameters](https://developer.allegro.pl/documentation/#operation/getOffersUnfilledParametersUsingGET_1). Więcej informacji znajdziesz w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-sprawdzic-nieuzupelnione-parametry-w-ofertach).
