### ISSUE TITLE
How to list offers with producset.quantity > 1

### ISSUE THREAD

**Issue by MKI-Miro** [allegro/allegro-api#6920]
Hi

Is it possible to find list of offers where productSet.quantity > 1

On some products we have entered stock quantity to productSet.quantity, so wee need to fix it.

Thank you

**Comment by MKI-Miro** [comment]
So there is no way how to fix it?

**Comment by MKI-Miro** [comment]
I can iterate through all offers but produset is missing there. So any idea how to fix it?

**Comment by MartaNowaczyk** [comment]
Unfortunately, we don't have a ready solution in our API. In that case you would have to check it by downloading the offer details.
