### ISSUE TITLE
Edycja wielu ofert jednym requestem

### ISSUE THREAD

**Issue by seoexelmedia** [allegro/allegro-api#6921]
Cześć!
Napisałem skrypt, który zmienia ceny w ofertach. W tym momencie ofert jest bardzo dużo i czas wykonania bardzo mocno się wydłużył i chciałem w jakiś sposób zoptymalizować całość. W tej chwili program działa bardzo prosto - jedna oferta - jeden request zmiany ceny.
Widziałem możliwość edycji wielu ofert naraz, ale to sprawdzi się kiedy miałbym jedną cenę dla wielu ofert, a w moim przypadku każda oferta posiada inną cenę. Czy w takim przypadku jest jakaś inna możliwość niż aktualny sposób działania? Np. wysyłanie kilku requestów ze zmianą jako "paczka" jednym requestem?
Jakaś wskazówka będzie dla mnie bardzo cenna :)

**Comment by MartaNowaczyk** [comment]
Tak jak napisałeś, grupowa edycja umożliwia zmianę wszystkich ofert o jeden parametr - na taką samą cenę, zmiana o taki sam procent itp. Nie ma innego zasobu, którym mógłbyś zmienić grupowo ceny.
