### ISSUE TITLE
Jakie są możliwe statusy przy zmianie ceny /zamknieciu kampanii 

### ISSUE THREAD

**Issue by lukasznurzynski** [allegro/allegro-api#6924]
Witam,
jestem w trakcie implementacji  funkcjonalności kampanii (badge campaign) i mam pytanie co do operacji zmiany ceny lub zakończenia aukcji w kampanii.

Zgodnie z dokumentacją wysyłam prośbę o zmianę cney lub zkończenie i w odpowiedzi zwrotnej otrzymuje id za pomoca którego sprawdzam stan operacji.

Z tego co zrozumiałem za pomocą [[GET] /sale/badge-operations/{operationId}](https://developer.allegro.pl/documentation/#operation/badgeOperations_get_one) sprawdzić sobie mogę status operacji a może on zwrócić status REQUESTED, DECLINED oraz PROCESSED.
Co jeśli zwróci mi PROCESSED? Dalej znów sprawdzam status przy pomocy GET /sale/badges?offer.id={offerId} ? Czy wtedy znowu są możliwe wszystkie statusy (IN_VERIFICATION itp.) aż do FINISHED? A czy jak operacja zwróci processed to się udało zmienić cenę i teraz takie GET /sale/badges?offer.id={offerId} od razu zwraca ACTIVE ?

Podobnie mam wątpliwości co do zakończenia aukcji w kampanni. Jak dostanę PROCESSED na operacji to kolejno w GET /sale/badges?offer.id={offerId} powinienem dostawać FINISHED co oznacza że całość zakończyła sie sukcesem? Czy mamy jeszcze jakieś posrednie statusy?

A co jeśli w operacji zmiany ceny dostanę DECLINED ? To tylko błąd operacji i aukcja dalej jest aktywna w kampanii tylko z nie zmienioną ceną? A czy  teraz aukcja w kampanii jest nieaktywna i trzeba poprawić cene  np.?

W skrócie brakuje mi informacji o możliwych scenariuszach już po otrzymaniu na operacji   PROCESSED albo DECLINED. W aplikacji do kampanni mamy jasno napisane ze jak dostane PROCESSED to sprawdzam już za pomocą sale/badges i wiadomo jakie tam statusy po kolei mogę otrzymać az do ACTIVE. Tutaj tej infomracji brakuje.

**Comment by MartaNowaczyk** [comment]
Nie ma pośrednich statusów, jeżeli zwrócimy status "PROCESSED" to znaczy, że ta konkretna operacja o którą odpytujesz została już wykonana, czyli wprowadziliśmy zmienę (cena zmieniona lub oznaczenie wyłączone). Ogólnie wygląda to tak, że status REQUESTED przechodzi w status "PROCESSED" lub "DECLINED", które potwierdzają wykonanie lub niewykonanie tej konkretnej operacji o którą odpytujesz.

**Comment by lukasznurzynski** [comment]
Ok , to wyjąsnia wiele :) Jeszcze dwa pytanka:
1. jeśli przy zmianie ceny dostanę DECLINED to  zmiana się nie wykonuje ale oferta jest dalej aktywna, czy to wyłącza oferte z kampanii z powodu błedu?
2. operacja zakończenia - jak dostanę DECLINED to oferta pozostaje aktywna czy będzie miała status DECLINED już cały czas? Jak wtedy zakończyć ją żeby faktycznie dostała FINISHED i była uznana za zakończoną?

**Comment by MartaNowaczyk** [comment]
1. Oferta zostaje w poprzednim stanie.
2. Jest taki jeden przypadek - konfigurując kampanie jest checkbox "pozwól na rezygnację" i jeśli tego ktoś nie zaznaczy to nigdy nie zrezygnujesz z badge (zawsze dostaniesz DECLINED).

**Comment by lukasznurzynski** [comment]
Ok super, dziękuje bardzo za pomoc.
