### ISSUE TITLE
Allegro Packeta - zwracane dwa różne ID do jednej metody

### ISSUE THREAD

**Issue by CSVK2022** [allegro/allegro-api#6926]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Witam,
zarejestrowaliśmy błąd przy zwracaniu ID metody dla:  Allegro Wysyłka z Polski do Czech-Automaty Paczkowe Packeta.
Zwracane ID: 

-  529b132a-2f6b-4f37-b7fb-9c4a33aba97c
-  07e2afc8-2f6b-4f37-b7fb-9c4a33aba97c

Nadmienię również, że obie identyczne metody widnieją filtrując zamówienia według metody dostawy (screen)
![packeta_czechy](https://user-images.githubusercontent.com/105273211/230079549-f1c64a8e-7ba3-463a-8d32-9c8df2297665.png)

Proszę o informację czy zabieg celowy, ewentualnie które ze zwracanych ID jest poprawne. Na chwilę obecną zwracane są oba pod tą samą nazwą.

**Comment by Lukasz-Zurek** [comment]
@CSVK2022 Na sandboxie wspomniana metoda dostawy została celowo zdublowana z uwagi na różne rynki, dla których jest ona przeznaczona. W przypadku metody 529b132a-2f6b-4f37-b7fb-9c4a33aba97c w polu "marketplaces" zwracamy "allegro-cz".

**Comment by CSVK2022** [comment]
Dziękuję za odpowiedź, prośba jeszcze o zmianę nazwy, bo może to być mylące, dla obu metod nazwa zwracana jest identyczna.
![packeta2](https://user-images.githubusercontent.com/105273211/230284124-fd3da806-bcf0-46f9-8caf-8cf153b2b5ef.png)

**Comment by Lukasz-Zurek** [comment]
Nie mamy w planach zmiany nazwy tej metody dostawy. Zgodnie z naszym [newsem](https://developer.allegro.pl/news/serwisy-zagraniczne-allegro-zmiany-w-metodach-i-ustawieniach-dostaw-lLqd9kkgBUd) - dla [GET /sale/delivery-methods](https://developer.allegro.pl/documentation/#operation/getListOfDeliveryMethodsUsingGET) dodaliśmy oznaczenie, które wskazuje, w jakich serwisach będzie widoczna dana metoda dostawy i w tym przypadku rozróżniamy to w polu "marketplaces".
