### ISSUE TITLE
How to get a list of all possible errors that are sent over API for product listings?

### ISSUE THREAD

**Issue by radimzhor** [allegro/allegro-api#6929]
Our tool helps sellers list their offers on Allegro. During product listing, the API can return different error messages, depending on the situation.
IT would be great for us to have a complete list of all possible error messages so that we can translate them into CZ for Czech sellers.
Is this possible?

**Comment by MartaNowaczyk** [comment]
Unfortunately, this is not possible, we do not have such a list.
