### ISSUE TITLE
Is there a way to list offer using combination of GTIN and MPN

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#6930]
When listing offer I get a response with error code "MultipleProductsFoundException"
My idea was to use combination of GTIN and Manufacturers Part Number in such case, however I was not able to prepare such request. Sending MPN in parameter did not work. Is ther a way to send such request and if so, can you help me prepare it?

My request
POST https://api.allegro.pl/sale/product-offers/
`{
    "productSet": [
        {
            "product": {
                "id": "8595042741308",
                "idType": "GTIN"
            },
            "parameters": [
                {
                    "id": "224017",
                    "name": "Manufacturer's code",
                    "valuesLabels": [
                        "ST06"
                    ],
                    "values": [
                        "ST06"
                    ],
                    "unit": null,
                    "options": {
                        "identifiesProduct": true
                    }
                }
            ],
            "quantity": {
                "value": 1
            }
        }
    ],
    "delivery": {
        "handlingTime": "PT0S",
        "shippingRates": {
            "id": "cb700d48-17bf-463c-9425-b0dc76ad6448"
        }
    },
    "publication": {
        "status": "INACTIVE"
    },
    "language": "pl-PL",
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "cb0afb63-fdd2-4fd1-99ff-7f387ee8d040"
        },
        "returnPolicy": {
            "id": "b03aeb24-2548-40b7-84af-54850061975e"
        }
    },
    "name": "Namiot 3 osobowy dwupowłokowy ST06",
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "1550.00",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 327,
        "unit": "UNIT"
    },
    "location": {
        "city": "Semily",
        "countryCode": "CZ",
        "postCode": "51301"
    },
    "external": {
        "id": "05-ST06"
    },
    "messageToSellerSettings": {
        "mode": "HIDDEN"
    }
}`

**Comment by MartaNowaczyk** [comment]
First of all, we try to distinguish products by parameters, so if the products differ by some parameter - we will choose the one that more closely matches your request.
However, if such a distinction is not possible, the best solution is to check these products (GET /sale/products) and indicate in the request a specific product (id of the selected product) that should be used in the offer.

**Comment by ZajdaBear** [comment]
Hi, I did exactly that.
Products differ in MPN and I have specified MPN in request. Please elaborate

![image](https://user-images.githubusercontent.com/109143627/230330813-9df41613-f2f8-4feb-8636-0c1f0ca3ae33.png)

**Comment by MartaNowaczyk** [comment]
IF we did not find the product by this data, you have to search for such product using `https://api.allegro.pl/sale/products?phrase=8595042741308&mode=GTIN`. Choose which one fits more and add the product.id from this response when listing the offer.  You can also try to add a new one based on the data from the offer.  You can find more in [our tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-list-an-offer-with-a-product-via-sale-product-offers-resource).

**Comment by ZajdaBear** [comment]
However, you should be able to identify the product precisely, since combination of GTIN and Manufacturer's code is unique, at least in this case right? This is what you asking me to do with extra step.
I will get those two products and pick one based on Manufacturer's code. I hope you understand what I mean.
It is quite some work on our side.
In case your claim about trying to distinguish precise product bsased on parameters is correct, that would IMHO mean, this is a bug on your side. Please advice, if the tiket should be raised on this issue.

**Comment by MartaNowaczyk** [comment]
I will confirm the correct operation for this combination and come back with an answer. The rule is that if you don't find a matching product then you have to search in the product catalog and select the one that matches. Anyway you should have this solution in your integration, because you can't always identify the product by these parameters.

**Comment by ZajdaBear** [comment]
Thank you Marta. I will do, but possibly in later phase.

**Comment by ZajdaBear** [comment]
Hi, is there an update?

**Comment by MartaNowaczyk** [comment]
I confirmed that if the product is unique it should be searched and the offer created. In the request, provide the parameters in the product structure as below and it should search for it. 

```
{
  "productSet": [
    {
      "product": {
        "id": "8595042741308",
        "idType": "GTIN",
        "parameters": [
        {
          "id": "224017",
          "name": "Manufacturer's code",
          "valuesLabels": [
            "ST06"
          ],
          "values": [
            "ST06"
          ]
        }
      ]
      },
      "quantity": {
        "value": 1
      }
    }
  ],
  "delivery": {
    "handlingTime": "PT0S",
    "shippingRates": {
      "id": "cb700d48-17bf-463c-9425-b0dc76ad6448"
    }
  },
  "publication": {
    "status": "INACTIVE"
  },
  "language": "pl-PL",
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "cb0afb63-fdd2-4fd1-99ff-7f387ee8d040"
    },
    "returnPolicy": {
      "id": "b03aeb24-2548-40b7-84af-54850061975e"
    }
  },
  "name": "Namiot 3 osobowy dwupowłokowy ST06",
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "1550.00",
      "currency": "PLN"
    }
  },
  "stock": {
    "available": 327,
    "unit": "UNIT"
  },
  "location": {
    "city": "Semily",
    "countryCode": "CZ",
    "postCode": "51301"
  },
  "external": {
    "id": "05-ST06"
  },
  "messageToSellerSettings": {
    "mode": "HIDDEN"
  }
}
```

**Comment by ZajdaBear** [comment]
Hi, this seems not to be working. I just tried this offer, and it still tells me, that the product cannot be matched precisely

`{
    "productSet": [
        {
            "product": {
                "id": "8595042733679",
                "idType": "GTIN",
                "parameters": [
                    {
                        "id": "224017",
                        "name": "Manufacturer's code",
                        "valuesLabels": [
                            "8595042733679"
                        ],
                        "values": [
                            "8595042733679"
                        ]
                    }
                ]
            },
            "quantity": {
                "value": 1
            }
        }
    ],
    "delivery": {
        "handlingTime": "PT0S",
        "shippingRates": {
            "id": "09669248-d46c-49bc-9513-21475afc6bec"
        }
    },
    "publication": {
        "status": "INACTIVE"
    },
    "language": "pl-PL",
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "b38c3333-aeac-403b-8028-9f9b32a279ca"
        },
        "returnPolicy": {
            "id": "b03aeb24-2548-40b7-84af-54850061975e"
        }
    },
    "name": "Ławka do ciężarów z kołem pasowym WB3400",
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "747.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 43,
        "unit": "UNIT"
    },
    "location": {
        "city": "Semily",
        "countryCode": "CZ",
        "postCode": "51301"
    },
    "images": [
        "https://www.acra.cz/uploads/2023/02/WB3400-a.jpg",
        "https://www.acra.cz/uploads/2023/02/WB3400-b.jpg",
        "https://www.acra.cz/uploads/2023/02/WB3400-d.jpg"
    ],
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>ŁAWKA DO CIĘŻARÓW Z KOŁEM PASOWYM - ŁAWECZKA - POZYCJONOWANIE OPARCIA - KOPNIĘCIE I POTKNIĘCIE Z PRZODU - BOCZNE WSPOMAGANIE - MOTYL - STOJAK Z KOŁEM PASOWYM. Wiele różnych pozycji ćwiczeniowych pozwala na wzmocnienie górnych partii ciała za pomocą różnorodnych ćwiczeń z użyciem hantli jednorącz lub stojącego krążka. Do wzmocnienia ramion przeznaczony jest boczny wzmacniacz motylkowy. Stojaki na hantle dwuręczne można regulować na wysokość 104 - 125 cm od podłoża. Dla wzmocnienia ud i łydek zaprojektowano obrotowy bloczek, który umożliwia ich ćwiczenie i wzmacnianie (kopanie i potykanie). Na stanowisku z kołem pasowym można również ćwiczyć wiele wariantów różnych ćwiczeń. Wymiar: 160 x 138 x 200 cm Waga: 32,5 kg Udźwig: 150 kg, koło pasowe na stojaku może udźwignąć 60 kg. Zalecany maksymalny nacisk osi na obciążniki wynosi 50 kg, średnica wynosi 25 mm. Profil elementów nośnych wynosi 40 x 40 mm przy grubości ścianki profilu 1,45 mm.</p>"
                    }
                ]
            }
        ]
    },
    "external": {
        "id": "05-WB3400"
    },
    "messageToSellerSettings": {
        "mode": "HIDDEN"
    }
}`

Please advice.

Bonus question. What if the product catalog has 2 products under same GTIN and I am interested in the product without MPN? How do I proceed? Thanks

**Comment by MartaNowaczyk** [comment]
We found two matching products for these parameters, hence the error.  You can see it here https://api.allegro.pl/sale/products?phrase=8595042733679&mode=GTIN
Result:
"id": "bf5887d4-4617-4742-89d9-693b2edf4db0"
"id": "7f7de294-3de0-4ec9-a901-ee465cecbdde"

If we find more than one product you must choose which one fits more.

**Comment by ZajdaBear** [comment]
Ok, I believe only one product matches the request based on MPN. Nevermind. Can you show me how to pass UUID of the products using POST  on /sale/product-offers/
In documentation only type GTIN or MPN is mentioned?

**Comment by MartaNowaczyk** [comment]
You provide the product ID the same way you give the GTIN or MPM, just omit the "idType"
```
"productSet": [
    {
      "product": {
        "id": "4946aadd-1448-45d8-9a4c-90dacbae9a4f",
...
]
```

In the [documentation](https://developer.allegro.pl/documentation/#operation/createProductOffers) we have a mention of this 

> "idType	string
> Enum: "GTIN" "MPN"
> Type of id. This field is optional. It helps in finding products more accurately. If an idType is not set, a given id is understood as a product's id."
