### ISSUE TITLE
Rest api - błąd VAT przy wznawianiu aukcji, w portalu działa

### ISSUE THREAD

**Issue by q3ok** [allegro/allegro-api#6934]
**Występuje problem:**
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

**Opis / Description**
Przy wznawianiu aukcji poprzez REST API otrzymuję błąd:
'Could not change offer publication status. The Vat settings are invalid. Please define offer VAT settings again.'

Wznowienie bezpośrednio z portalu allegro działa bezproblemowo. Stawka VAT jest skonfigurowana poprawnie.

Przykładowe identyfikatory które miały wznowić aukcje:
d40ac93d-15b5-4739-893b-b32edcdda6d4
28a1728c-69f4-432e-8f31-ab2a0370a2a2
65603c2d-cbb6-443c-ab7a-f41259a4d993

**Comment by AdrianeZ** [comment]
Zauważyłem podobny błąd jak zgłoszenie wyżej. Problem dotyczy zasobu masowego wznawianiu/zakończaniu ofert. Dostajemy błąd 1. The Vat settings are invalid. Please define offer VAT settings again.  Przesyłam też dodatkowo informacje o ofercie w której dosaliśmy błąd. 

![Insomnia 2023-04-10 17 23 42](https://user-images.githubusercontent.com/69970869/230933440-3df1d8c1-adb2-4963-ad62-71b98d343fe1.png)

**Comment by MartaNowaczyk** [comment]
Dziękuję za zgłoszenie. Gdy tylko zweryfikujemy opisaną sytuację, wrócę z informacją.

**Comment by MartaNowaczyk** [comment]
@q3ok  @AdrianeZ Problemem okazała się walidacja. Zmieniliśmy podejście i błąd nie powinien już występować. Przepraszamy za niedogodności.

**Comment by AdrianeZ** [comment]
@MartaNowaczyk - dzięki za wyjaśnienie. Pozdrawiam.

**Comment by q3ok** [comment]
@MartaNowaczyk przez chwilę działało poprawnie, jednak błąd znowu się pojawił.
Przykładowo uuid 89337a01-d33f-4df0-99d7-f3f4ec998bcc

**Comment by AdrianeZ** [comment]
@MartaNowaczyk  - u nas to samo jak u @q3ok

**Comment by MartaNowaczyk** [comment]
@q3ok @AdrianeZ jak tylko zweryfikujemy sytuację, wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Wczoraj wdrożyliśmy możliwość deklarowania stawek VAT dla Czech, dlatego walidacja wróciła. Problem o którym piszecie dotyczy starych zakończonych ofert lub starych ofert w statusie draft. Wymagają one ponownej deklaracji stawek. Na ten moment rozwiązaniem jest edycja takiej oferty i ponowne przypisanie stawki VAT. Oferty aktywne nie powinny mieć tego problemu. Gdyby było tego dużo dajcie proszę znać.

**Comment by AdrianeZ** [comment]
@MartaNowaczyk - przypisanie tej stawki ma odbywać się do starego pola 'tax' czy nowego 'taxSettings' - czy bez różnicy, ponieważ i tak będziecie migrować? Wystarczy skorzystać z zasobu PATCH sale/product-offers/{id} i edytować pole tax/taxSettings?

**Comment by MartaNowaczyk** [comment]
@AdrianeZ Wystarczy, że dla ofert zakończonych wyślesz ponownie te dane z ustawieniami VAT, które masz już w ofercie, abyśmy mieli te dane. Staramy się zrobić to po swojej stronie i pracujemy nad tym, ale na ten moment to jedyne rozwiązanie.

**Comment by AdrianeZ** [comment]
@MartaNowaczyk @AureliuszBrussy - ale lepiej wysłać te dane w polu tax czy taxSettings?

**Comment by MartaNowaczyk** [comment]
@AdrianeZ jeśli podasz wartości w starym polu “tax”, przepiszemy je do nowego pola “taxSettings”. Dlatego możesz zrobić tak jak Ci wygodniej. Na pewno "taxSettings" jest docelowym rozwiązaniem - w przyszłości zamierzamy usunąć pole “tax” i to trzeba mieć na uwadze. Pamiętaj też, że nie możesz przekazać wartości w obu polach jednocześnie.

**Comment by AdrianeZ** [comment]
@MartaNowaczyk  - dzięki mam to na uwadze, ale kiedy pobieram szczegóły mojej przykładowej oferty pole taxSettings jest nullem, Więc na razie niech tak będzie dopóki nie zrobicie migracji i w przyszłości usniecie pole tax i będzie wymagać tylko taxSettings. Więc na razie skorzystam z pola 'tax'.
