### ISSUE TITLE
Błąd, który nic mi nie mówi przy próbie edycji aukcji z poziomu Allegro

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#6936]
Witam,

Co powinienem poprawić aby móc zmienić tytuł na aukcji: 13498321774. Próbuje zmienić tytuł na "JoyRoom BEZPRZEWODOWE SŁUCHAWKI SPORTOWE BT 5.0", ale dostaję błąd:

Podczas modyfikowania oferty wystąpiły błędy - Tytuł Twojej oferty lub jej dalszy opis może wprowadzać w błąd co do pochodzenia towaru, jego producenta lub marki i tym samym naruszać prawa firmy, która współpracuje z nami w ramach programu Współpraca w Ochronie Praw. W opisie Twoich ofert używasz zarejestrowanego słownego znaku towarowego w celu sprzedaży produktu innej marki (widocznej w sekcji ‘Parametry’).

Niestety nie bardzo wiem, co na podstawie takiej treści błędu miałbym poprawić. Próbowałem poprawić w tytule z JoyRoom na Joyroom zakładając, że to może być niepoprawne, ale nic to nie dało.

**Comment by AureliuszBrussy** [comment]
Aby wyjaśnić tego rodzaju error w walidacji - niech właściciel oferty skontaktuje się poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
