### ISSUE TITLE
: One of required services is unavailable. Try again later.

### ISSUE THREAD

**Issue by marekbarczyk123** [allegro/allegro-api#6937]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy próbie wygenerowania paczki dostajemy błąd:
{
    "errors": [
        {
            "code": "ANOTHER_SERVICE_NOT_AVAILABLE",
            "details": "One of required services is unavailable. Try again later.",
            "message": "One of required services is unavailable. Try again later.",
            "path": null,
            "userMessage": "One of required services is unavailable. Try again later."
        }
    ],
    "id": "0ac730e7-6386-48bd-8006-e327883964d6",
    "parcelId": null,
    "status": "ERROR"
}

Wysyłamy request z tego typu przesyłką:
"serviceId": "2488f7b7-5d1c-4d65-b85c-4cbcf253fd93#f026b883-ec47-489a-b050-29f3fa9e8696",
    "type": "PACKAGE"

**Comment by AureliuszBrussy** [comment]
W swoim requeście przekazujesz adres email odbiorcy pobrany spoza zamówienia Allegro. Skorzystaj z tego, który pobierasz z zamówienia (maskowany adres mailowy).
