### ISSUE TITLE
Tworzenie oferty poprzez API w wersji Sandbox

### ISSUE THREAD

**Issue by barczykartur** [allegro/allegro-api#6938]
Cześć, po utworzeniu oferty przez endpoint: POST /sale/product-offers otrzymuję odpowiedź o statusie 202 z Headerem Location: https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/7702632224/operations/a67706ff-9788-454b-bcd9-24ba49702f69
Po wysłaniu zapytania GET na powyższy adres otrzymuję odpowiedź o statusie 200 oraz dane dodanej oferty. Według dokumentacji status 200 nie powinien nigdy wystąpić,  dodatkowo struktura odpowiedzi powinna być inna (otrzymuję strukturę z enpointa https://api.allegro.pl/sale/product-offers/${offerId}). Czy takie działanie jest porządane w przypadku wersji Sandbox? Jak tworzenie ofert wygląda w wersji produkcyjnej? Z góry dziękuję za odpowiedź.

**Comment by AureliuszBrussy** [comment]
Prawdopodobnie biblioteka/oprogramowanie z którego korzystasz automatycznie obsługuje status http _303 See Other_ i od razu pobiera wynik requestu z nagłówka Location.

**Comment by barczykartur** [comment]
Faktycznie, cURL'em zadziałało, dziękuję
