### ISSUE TITLE
Pobieranie listy Top 10 produktów pod względem sprzedaży 

### ISSUE THREAD

**Issue by klaudi2406** [allegro/allegro-api#6939]
Zacznę od tego, że nie znam się na programowaniu. potrzebuję jednak Allegro API do analizy rynku mebli biurowych.
Znalazłem poradnik jak połączyć się z API i pobrać listę kategorii poprzez Token i to mi się udało(kod wyglądał tak):
import requests
import json

CLIENT_ID = "tutaj podałem swoje ID "
CLIENT_SECRET = "******"
TOKEN_URL = "https://allegro.pl/auth/oauth/token"

def get_access_token():
    try:
        data = {'grant_type': 'client_credentials'}
        access_token_response = requests.post(TOKEN_URL, data=data, verify=False, allow_redirects=False, auth=(CLIENT_ID, CLIENT_SECRET))
        tokens = json.loads(access_token_response.text)
        access_token = tokens['access_token']
        return access_token
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)

def find_subcategories(parent_id, token):
    try:
        url = "https://api.allegro.pl/sale/categories"
        headers = {'Authorization': 'Bearer ' + token, 'Accept': "application/vnd.allegro.public.v1+json"}
        query = {'parent.id': parent_id}
        categories_result = requests.get(url, headers=headers, params=query, verify=False)
        categories = categories_result.json()
        categories_list = categories['categories']
        subcategories = []
        for category in categories_list:
            if category['leaf']:
                subcategories.append(category)
            else:
                subcategories += find_subcategories(category['id'], token)
        return subcategories
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)

def main():
    token = get_access_token()
    parent_id = "64477" 
    subcategories = find_subcategories(parent_id, token)
    for category in subcategories:
        print(category['name'])

if __name__ == "__main__":
    main()

I na tym się zatrzymałem i nie potrafię pójść dalej. Moim celem jest wyciąganie 10 najczęściej kupowanych produktów z kategorii meble biurowe w danym okresie i wypisanie ich w formie linków. Nie rozumiem do końca dokumentacji i nie wiem czy jest w ogóle możliwe takie coś.

**Comment by MartaNowaczyk** [comment]
Niestety, zajmujemy się tutaj wsparciem API, nie udzielamy tutaj wsparcia programistycznego. W takim wypadku może ktoś ze społeczności naszego forum Ci pomoże.
Oczywiście jeśli będziesz miał pytanie do samego API Allegro chętnie pomogę.

**Comment by klaudi2406** [comment]
To mam pytanie do samego API, czy jest w ogóle możliwość wyciągniecia danych o których mówię, czyli wyciąganie 10 najczęściej kupowanych produktów z kategorii meble biurowe w danym okresie?

**Comment by MartaNowaczyk** [comment]
Jeśli chodzi o oferty publiczne [GET offers/listing](https://developer.allegro.pl/documentation/#operation/getListing), to trzeba mieć zgodę na dostęp i zweryfikowaną aplikację. Tak czy inaczej nie otrzymasz tych danych, bo nie ma możliwości sortowania chociażby po popularności. Nie ma tam też informacji o liczbie sprzedanych produktów w danej ofercie. Więcej znajdziesz w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk). 
Jeśli chciałbyś szukać w swoich ofertach to możesz skorzystać z [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET), wybrać kategorię i sortować po "stock.sold" (liczba sprzedanych przedmiotów w ofercie z ostatnich 30 dni), do 10 wyników możesz ograniczyć poprzez parametr "limit". Więcej informacji znajdziesz na naszej [stronie](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-pobrac-moje-oferty-w-rest-api).
