### ISSUE TITLE
WZA - Po jakim czasie wygasają etykiety na paczki?

### ISSUE THREAD

**Issue by tomasz3k** [allegro/allegro-api#6940]
Witam, na środowisku testowym za pomocą REST API chciałem pobrać etykiete do paczki utworzonej kilka dni temu. 

Dostaję komunikat 
`{
    "code": "ERROR",
    "message": "Parcel's documents have expired",
    "details": null,
    "path": "shipmentId/shipments/{shipmentId}/label",
    "userMessage": "Dokumenty wygasły"
}`

To samo po zalogowaniu na swoje konto www.

Pytanie więc jest następujące dlaczego etykiety wygasły, skoro w Inpoście wygasają po co najmniej 30 dniach?
Przez jaki okres czasu od utworzenia paczki można pobierać etykietę? 

Sprawa dotyczy paczki np. parcelId=24e0db9f-605e-46c8-bbae-bd242d1dbb85

**Comment by MartaNowaczyk** [comment]
Dzięki za zgłoszenie. Sprawdzę ten przypadek i wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
@tomasz3k możesz podać jeszcze trace-id dla tego przypadku?

**Comment by tomasz3k** [comment]
"trace-id": "3423f70f92441c80",

**Comment by tomasz3k** [comment]
A w przypadku produkcji  jaki jest czas na pobranie etykiety?

**Comment by MaciejFrackowiak** [comment]
Etykiety na produkcji dostępne są do pobrania przez 30 dni.
