### ISSUE TITLE
Brak dostępu do zasobu GET /parcel-management/delivery-services

### ISSUE THREAD

**Issue by tomaszciula** [allegro/allegro-api#6941]
Witam, 

próbuję dostosować "Wysyłam z Allegro" do swoich potrzeb, jednak otrzymuję odmowę dostępu do zasobu GET /parcel-management/delivery-services (otrzymuję 403):

- token jest poprawny, działa przykładowo z zasobem GET sale/offers czy np. GET sale/delivery-methods
- dodałem domyślny adres w https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/zamowienia/ustawienia - (środowisko testowe) zgodnie z:  

- "Ważne! Zanim skorzystasz z API Wysyłam z Allegro, aktywuj swoje konto. Możesz to zrobić poprzez:
dodanie domyślnego adresu w Książce adresowej - Wysyłam z Allegro:
https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia - (środowisko produkcyjne),
https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/zamowienia/ustawienia - (środowisko testowe),
lub nadając dowolną przesyłkę korzystając z przycisku NADAJ PRZESYŁKĘ na liście [Zamówień](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/)."

i tak, wołając:
GET https://api.allegro.pl.allegrosandbox.pl/parcel-management/delivery-services
w headers mamy:
- Authorization: Bearer ....
- Accept: ....
otrzymuję:
{
    "errors": [
        {
            "code": "AccessDenied",
            "message": "Access is denied",
            "details": null,
            "path": null,
            "userMessage": "No access to the specified resource."
        }
    ]
}

**Comment by AureliuszBrussy** [comment]
Abym mógł to sprawdzić, podaj proszę trace-id wywołania kończącego się tym błędem. Trace-id znajdziesz w nagłówku response'a.

**Comment by tomaszciula** [comment]
Jasne,
trace-id: b7f0b08efbcf2e69

**Comment by AureliuszBrussy** [comment]
@tomaszciula niestety nie mogę namierzyć tego requestu. Czy mógłbyś podać jeszcze jeden przykład trace-id?

**Comment by tomaszciula** [comment]
e68933b813345224
GET na https://api.allegro.pl.allegrosandbox.pl/parcel-management/delivery-services

**Comment by AureliuszBrussy** [comment]
W access tokenie, którego wygenerowałeś i przekazujesz w requeście brakuje odpowiedniego dla tego zasobu scope'a: [allegro:api:orders:read].

**Comment by tomaszciula** [comment]
działa :) dziękuję za fachową pomoc :), pozdrawiam 👍
