### ISSUE TITLE
Tworzenie paczki z "Wysyłam z Allegro"

### ISSUE THREAD

**Issue by tomaszciula** [allegro/allegro-api#6943]
witam,
próbuję utworzyć nową paczkę korzystając z "wysyłam z Allegro" z zasobu [PUT /parcel-management/parcel-create-commands/{commandId}. NIezależnie od wybranego serviceId sprawdzając status paczki poprzez [GET /parcel-management/parcel-create-commands/{commandId}] otrzymuję status: ERROR, przy czym parcelId: null ->
{
    "id": "91e6054e-b933-4095-8cb6-c0a8a9c29462",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ANOTHER_SERVICE_NOT_AVAILABLE",
            "message": "One of required services is unavailable. Try again later.",
            "details": "One of required services is unavailable. Try again later.",
            "path": null,
            "userMessage": "One of required services is unavailable. Try again later."
        }
    ]
}

Tworzenie paczki:
PUT https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/91e6054e-b933-4095-8cb6-c0a8a9c29462
trace-id: f9e0f9097ba53e00

Sprawdzenie statusu paczki:
GET https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/91e6054e-b933-4095-8cb6-c0a8a9c29462
trace-id: 8820c9f0a734341c

**Comment by AureliuszBrussy** [comment]
W polu receiver.email przekazałeś na końcu adresu znak "/". Spróbuj wygenerować przesyłkę ponownie bez tego zbędnego znaku.

**Comment by tomaszciula** [comment]
niestety, bez zmian

**Comment by d3stozaur** [comment]
Również mamy ten błąd przy probie stworzenia paczki:
trace-id: 32bb3a9f64e20ec1

**Comment by AureliuszBrussy** [comment]
@tomaszciula przekazałeś adres e-mail kupującego (receiver.email) pochodzący ze środowiska produkcyjnego. Powinieneś przekazać taki z zamówienia złożonego na Sandboxie. 

@d3stozaur w Twoim requeście przekazujesz w receiver.email adres email w ogóle nie pochodzący z zamówienia Allegro.
