### ISSUE TITLE
Częste 403 z html captch'a w odpwiedzi na (POST /auth/oatuh/token) request o odświeżenie tokena

### ISSUE THREAD

**Issue by itav** [allegro/allegro-api#6944]
Witam, 
Zauważyłem że sporadycznie dostaję w odopowiedzi na request o odświeżenie tokena odpowiedź 403 z takim html:
```
<html>
<head>
	<title>allegro.pl</title>
	<style>
		#cmsg {
			animation: A 1.5s;
		}

		@keyframes A {
			0% {
				opacity: 0;
			}

			99% {
				opacity: 0;
			}

			100% {
				opacity: 1;
			}
		}
	</style>
</head>

<body style="margin:0">
	<p id="cmsg">Please enable JS and disable any ad blocker</p>
	<script data-cfasync="false">
		var dd={'rt':'c','cid':'xxxxxxxxxxxxxxxxxxxxxxxxxxxx==','hsh':'xxxxxxxxxxxxxxxxxx','t':'bv','r':'b','s':29664,'e':'xxxxxxxxxxxxxxxxxxxxxx','host':'geo.captcha-delivery.com'}
	</script>
	<script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script>
</body>
</html>
```
wartości cid, hsh, e wyiksowałem. 

Jest to request wysyłany po API i ta odpwiedź z html wydaję się tutaj nienaturalna. 
Dlaczego tak się dzieje ? 
Jak można to obsłużyć lub tego uniknąć ?

Pozdrawiam,

**Comment by MartaNowaczyk** [comment]
Wygląda na to, że korzystacie z https://ssl.allegro.pl/auth/oauth/token, gdzie może pojawić się captcha. Zmiana na https://allegro.pl/auth/oauth/token powinna pomóc.

**Comment by itav** [comment]
korzystamy tylko z https://allegro.pl/auth/oauth/token  nigdy nie uzywalimsy tego drugiego adresu

**Comment by MartaNowaczyk** [comment]
Mogę to zweryfikować, tylko prześlij proszę swój pełen request jaki wysyłasz przez [formularza kontaktowy](https://allegro.pl/pomoc/kontakt). W zgłoszeniu dopisz, że dane dotyczą wątku [#6944](https://github.com/allegro/allegro-api/issues/6851) na GitHubie.

**Comment by MartaNowaczyk** [comment]
Dzięki, sprawdzę, jak tylko otrzymam te dane.

**Comment by itav** [comment]
Wysłałem dane formularzem kontaktowym, i dostałem mailem odpowiedź:  "Jak mogę pomoć"
Obawiam że coś tutaj się zgubiło
Temat maila: Odpowiedź na zgłoszenie nr "32614520" [ ref:_00D24aE05._5003VYhCXW:ref ]
Możesz odszukać po tych numerach referencyjnych ?

**Comment by AureliuszBrussy** [comment]
@itav zgłoszenie faktycznie do nas nie dotarło, poprosiłem już zespół obsługi klienta o jego przekazanie. Wrócimy z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@itav w przesłanym przykładzie curl wykonujesz request pod niepoprawny url (https://allegro.pl/auth/**oatuh**). Upewnij się co do poprawności swoich requestów.

**Comment by itav** [comment]
@AureliuszBrussy  Ach teraz widzę że do curl'a przesłalem z literówką w kodzie url jest poprawny ale i tak dostaję 40x. 
Zweryfikuje i podeśle inny przykład.

**Comment by AureliuszBrussy** [comment]
Przyczyną faktycznie może być m.in. to co wymieniłeś, ale bez konkretnego przykładu - możemy tylko spekulować. Najlepiej, jak przyślesz przykład takiej próby odświeżenia (razem z refresh tokenem) i najlepiej timestampem.

**Comment by itav** [comment]
Wysłałem przez formularz ten request. To jest dokładnie ten sam tylko poprawiłem literówkę. 
Proszę o sprawdzenie przyczyny 401.

**Comment by AureliuszBrussy** [comment]
Dziękuję za informacje. Czy to to samo zgłoszenie, czy nowe, pod innym numerem?

**Comment by sylwesterkowalski** [comment]
To samo zgłoszenie.

**Comment by AureliuszBrussy** [comment]
@sylwesterkowalski dziękuję za informacje, weryfikujemy to.

**Comment by itav** [comment]
Czy udało się już może potwierdzić czym jest spowodowana 401 w przykładzie który podesłałem?

**Comment by AureliuszBrussy** [comment]
@itav niestety, ale nie udało nam się znaleźć przyczyny. Czy mógłbyś przesłać jeszcze jeden przykładowy (świeży) request, który rzeczywiście zakończył się tym błędem? Spróbujemy jeszcze coś ustalić. Prosiłbym o możliwie najwięcej informacji. Najlepiej, jak podasz timestamp swojego requestu, adres ip itp.

**Comment by itav** [comment]
Wysłałem przez formularz kontaktowy i zatytułowałem "Dotyczy zgłoszenia na Githubie 6944
https://github.com/allegro/allegro-api/issues/6944"

Dodałem timestamp oraz adres IP
