### ISSUE TITLE
Problem ze wznawianiem ofert TAX_SETTINGS_INCONSISTENT

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6946]
Od kilku dni zauważyłem, że jest problem ze wznawianiem części ofert (allegro produkcyjne). W odpowiedzi otrzymujemy błąd: "[kod błędu: 422]: {"errors":[{"code":"TAX_SETTINGS_INCONSISTENT","message":"The Vat settings are invalid. Please define offer VAT settings again.","details":null,"path":"taxSettings","userMessage":"The Vat settings are invalid. Please define offer VAT settings again."}]}"

Problem dotyczy PATCH /sale/product-offers/{offer}, przy przekazywanej strukturze:

`{
   "publication": {
      "status": "ACTIVE"
   },

   "sellingMode": {
      "price": {
         "amount": '.$price.',
         "currency": "PLN"
      }
   },

   "stock": {
      "available": '.$quantity.'
   }
}`

Problem jest o tyle dziwny, że po aktualizacji całej stuktury mogę bez problemu wznowić ofertę (PATCH /sale/product-offers/{offer} - działa poprawnie). Jeżeli próbuję wznowić ofertę bez wcześniejsze aktualizacji całości, otrzymuję błąd. Do tej pory nie było żadnych problemów ze wznawianiem ofert - w kodzie integracji również nic nie zmienialiśmy. Proszę o pomoc

**Comment by AureliuszBrussy** [comment]
Czy mógłbyś wskazać trace-id przykładowego wywołania kończącego się tym błędem? Trace-id znajdziesz w nagłówku response'a. Przyjrzę się temu.

**Comment by mateuszcom** [comment]
Przesyłam trace-id dla zapytania, które wznawia ofertę: b3ad32cf4a6173db

**Comment by AureliuszBrussy** [comment]
@mateuszcom rozumiem, że podczas aktualizowania wszystkich danych (cała struktura oferty) - nie zmieniasz żadnych danych w polu **taxSettings**? Czy jesteś jeszcze w stanie podać trace-id takiego requesta?

**Comment by mateuszcom** [comment]
Poprzedni trace-id był dla takiej struktury, którą napisałem w pierwszej wiadomości (dokładnie chodzi tylko o wznowienie oferty, więc przesyłam uboższą strukturę gdzie uwzględniam status, aktualną cenę oraz ilość magazynową.) Nie przesyłam danych o podatkach - do tej pory działało wszystko poprawnie

Przesyłam trace-id dla całej struktury (w tym przypadku tak jak pisałem wcześniej nie generuje błędu): 3d7ee1028cf4ea87 
Wykonałem teraz polecenie wznowienia oferty (to samo co wcześniej generowało błąd) i wszystko wykonało się poprawnie. Trace-i: 4cb4effa25acbab5 

Czyli jeżeli tylko chcę wznowić ofertę, to nie działa, ale jak wcześniej całą strukturę zaktualizuję, a następnie wykonam wznowienie, to działa. Tak jak pisałem poprzednio, do tej pory nie było takich problemów. Ponad rok stosowaliśmy ten mechanizm i wszystko działało prawidłowo, aż do ostatnich dni

**Comment by AureliuszBrussy** [comment]
Dziękuję za informacje. Problem jest w zasadzie ten sam co we wcześniej zgłoszonym wątku: #6934. Związany jest z wdrożeniem zmiany w [deklarowaniu stawki VAT](https://github.com/allegro/allegro-api/issues/6942). Błąd dotyczy starszych zakończonych ofert lub starych ofert w statusie draft. Wymagają one ponownej deklaracji stawek. Na ten moment rozwiązaniem jest edycja takiej oferty i ponowne przypisanie stawki VAT. Oferty aktywne nie powinny mieć tego problemu.
