### ISSUE TITLE
Błąd przy sprawdzaniu statusu po utworzeniu paczki

### ISSUE THREAD

**Issue by tomaszciula** [allegro/allegro-api#6947]
witam,
po utworzeniu paczki korzystając z zasobu PUT https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/{uuid} otrzymuję 201 Created, natomiast nie mogę sprawdzić Statusu paczki korzystając z GET https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/{uuid}, otrzymuję:
{
    "id": "89011c60-d917-11ed-982e-cfeeba4d9bfc",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "DELIVERY_METHOD_NOT_AVAILABLE",
            "message": "Delivery Method is not available for this order",
            "details": "Delivery Method is not available for this order",
            "path": "/serviceId",
            "userMessage": "Delivery Method is not available for this order"
        }
    ]
}
Tworzenie paczki - trace-id: 3f5d5603947d14a2
GET status - trace-id: 10aed75fffae4a9e

**Comment by AureliuszBrussy** [comment]
Cześć walidacji wykonywana jest asynchronicznie (stąd [command pattern](https://developer.allegro.pl/tutorials/wzorzec-command-RdoYnMve6FD)). Może zdarzyć się tak, że komenda zostanie zlecona (status 201), natomiast ostatecznie przesyłka nie zostanie wygenerowana. W tym przypadku błąd wskazuje na to, że wybrana przy tworzeniu przesyłki metoda dostawy nie jest zgodna z tą wybraną przez kupującego w zamówieniu.
