### ISSUE TITLE
[REST] 422 Unprocessable Entity

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#695]
Szanowni Państwo, 
godzinę wstecz wasze serwery zwracały 404 dla zasobu /sale/offers/{offerId}
a w chwili obecnej 422. 
Draft był walidowany przed kilkoma dniami i był okey bez problemów, dziś 422 ? 

Błąd: putMethodRequest - Allegro zwróciło błąd: http code 422 - Unprocessable Entity w metodzie: /sale/offers/6205615704 zasoby: v1

Macie jakieś problemy techniczne ? 

pozdrawiamy WWW Factory

**Comment by PawelTaberski** [comment]
Z tego co widzę po numerze oferty chodzi Tobie zapewne o Sandbox-a przetestowałem i pobieranie i edycje danych o ofercie działa prawidłowo. Oferta którą podałeś jest aktywna i wystawiona nie jest draftem. Prosiłbym o doprecyzowanie co próbujesz zrobić przy pomocy jakiej metody.

**Comment by wwwfactory** [comment]
Dziękuję za szybką odpowiedź. Nie jestem w stanie w tech chwili udzielić więcej informacji. Jeżeli jutro będzie ten sam problem podeślę traceID. Ttymczasem zamykamy. Teraz wszystko działa..
