### ISSUE TITLE
aktywacja konta

### ISSUE THREAD

**Issue by worzala86** [allegro/allegro-api#6951]
prosze o aktywacje konta id : 105959955

**Comment by worzala86** [comment]
w sandbox oczywiście , w allegro aktywowałem, ten sam mail

**Comment by AureliuszBrussy** [comment]
Widzę, że jest to konto zwykłe - aby je aktywować, wykonaj symulację przelewu weryfikacyjnego w [Moje konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto). 

Jeżeli chciałbyś testować API Allegro - [zarejestruj też konto firma](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F). Tylko w ten sposób będziesz miał dostęp do zasobów związanych ze sprzedażą (przede wszystkim możliwości wystawiania ofert). Dane podane podczas rejestracji powinny być całkowicie fikcyjne.

**Comment by worzala86** [comment]
prosze o aktywacje konta id : 105959955

**Comment by AureliuszBrussy** [comment]
@worzala86 aktywowałem Twoje konto.
