### ISSUE TITLE
Mogę zapytać, jak wywołać identyfikator kategorii?

### ISSUE THREAD

**Issue by tianyiha** [allegro/allegro-api#6952]
Mogę zapytać, jak wywołać identyfikator kategorii?

**Comment by MartaNowaczyk** [comment]
Nie wiem czy o to chodzi, bo nie podałeś kontekstu, ale najpierw wywołujesz [GET /sale/categories](https://developer.allegro.pl/documentation/#operation/getCategoriesUsingGET) bez podawania kategorii, następnie otrzymasz główne kategorie allegro, a potem już kolejno: `GET /sale/categories?parent.id={categoryId}` aż dojdziesz do liścia, czyli kategorii, w której można wystawić ofertę ("leaf": true)
