### ISSUE TITLE
Metoda płatności: przelew tradycyjny - tymczasowo niedostępny

### ISSUE THREAD

**Issue by Levena007** [allegro/allegro-api#6955]
Witam,
chciałabym stworzyć test zakupów w sandbox z metodą płatności:
1. BLIK za każdym razem przy testach tej metody płatności pokazuje komunikat:
Unpaid purchase
Incorrect BLIK code. The seller cannot send the package."
2.  Płatność przelew tradycyjny - jest komunikat, że ta opcja jest tymczasowo wyłączona. 
Czy mogę prosić o pomoc?

**Comment by AureliuszBrussy** [comment]
Aby skorzystać na Sandboxie z BLIKa wpisz kod 777123 i odczekaj chwilę, płatność powinna zakończyć się sukcesem. 

Jeżeli chodzi o przelew tradycyjny - nie jest dostępny na Sandboxie, więc tego wariantu nie uda się przetestować.

**Comment by Levena007** [comment]
1. Czy kod który podałeś jest uniwersalnym kodem czy zadziała mi tylko raz? Mam do przetestowania kilka wariantów
2. Czy istnieje jakiś sposób, żeby przetestować przelew tradycyjny? Musimy zobaczyć jak wygląda sprawa z naszym EROP przy tej metodzie płatności

**Comment by AureliuszBrussy** [comment]
Ten kod BLIK jest uniwersalny. Niestety, nie ma sposobu na przetestowanie przelewu tradycyjnego na Sandboxie.

**Comment by Levena007** [comment]
Nie przeszedł mi również kod podany przez ciebie

**Comment by Levena007** [comment]
Przepraszam: za 2 razem przeszedł.

**Comment by Levena007** [comment]
To mam jeszcze kilka tematów:
1. Czy jest jakaś dokumentacja/ dobre praktyki co należy przetestować w Sandboxie?
2. Czytałam że będziecie usuwać oferty w przyszłym tygodniu. Czy macie plany je wdrożyć znowu, czy wszystko trzeba będzie umieszczać raz jeszcze?
3. Czy jest możliwość przeniesienia ofert ze środowiska testowego na oficjalne konto?
