### ISSUE TITLE
Podczas zamykania aukcji access deniad

### ISSUE THREAD

**Issue by ircoo2022** [allegro/allegro-api#6956]
Podzcas edycji :

CURLOPT_URL => 'https://api.allegro.pl/sale/product-offers/'.$offer_id,
Podczas $params['publication']['status'] = "ENDED";	

Access denied. You are not authorized to perform operations on the indicated offer

Dlaczego ??

**Comment by AureliuszBrussy** [comment]
Komunikat błędu wskazuje na to, że próbujesz wykonać edycję w ofercie, która nie należy do użytkownika, którego access token posiadasz. Upewnij się, czy korzystasz z access_tokena odpowiedniego użytkownika.
