### ISSUE TITLE
Brak wyników przy filtrowaniu ofert SMART

### ISSUE THREAD

**Issue by olianet** [allegro/allegro-api#6957]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Zgodnie z dokumentacją przekazanie parametru _option=SMART_ do _/offers/listing_ powinno zwrócić wszystkie oferty oznaczone Smart. W przypadku, **gdy jest tylko jedna oferta** w wyniku zapytania i **ta jedna oferta** jest Smart to zapytanie z parameterm _option=SMART_ nie zwraca wyniku

Przyładowe zapytanie: GET /offers/listing?price.from=64&include=items&sellingMode.format=BUY_NOW&category.id=17865&sort=%2Bprice&phrase=75346&option=SMART&fallback=false&parameter.11323=11323_1

**Comment by olianet** [comment]
Wygląda na to, że coś innego ma jeszcze wpływ na to czy są zwracane dane, bo np. dla tego zapytania gdzie jest tylko jedna oferta dane są zwracane
_GET /offers/listing?sort=%2Bprice&option=SMART&sellingMode.format=BUY_NOW&phrase=10993&fallback=false&price.from=168&include=items&parameter.11323=11323_1&category.id=17865_

**Comment by AureliuszBrussy** [comment]
Dziękuję za zgłoszenie. Poprawiliśmy indeksowanie dla tej oferty - pojawia się już w wynikach wyszukiwania z filtrowaniem po opcji SMART.

**Comment by olianet** [comment]
@AureliuszBrussy dziękuje, ten sam problem występuje jeszcze dla dwóch ofert od tego samego sprzedawcy:
https://allegro.pl/oferta/lego-star-wars-75352-diorama-sala-tronowa-imperato-13531227803
https://allegro.pl/oferta/lego-star-wars-75353-diorama-poscig-na-scigaczu-pr-13531237364
