### ISSUE TITLE
Brak możliwości weryfikacji konta

### ISSUE THREAD

**Issue by Sylvesterx1** [allegro/allegro-api#6959]
Niestety od ok. tygodnia konto ma status oczekuje na weryfikację. Czy można prosić o aktywację verseoicom@gmail.com

**Comment by PrzemyslawLukanowski** [comment]
Widzimy, że konto nie zostało jeszcze do końca aktywowane. Czy na poniższym widoku wybrałeś weryfikację pełną? Czy możesz ponowić przelew weryfikacyjny?
![Screenshot 2023-02-10 at 09 43 17 (1)](https://user-images.githubusercontent.com/51473661/232020692-070ff991-741b-433c-9154-9be825ae28e3.png)

**Comment by Sylvesterx1** [comment]
Tak, została wybrana weryfikacja pełna, następnie został wysłany przelew weryfikacyjny. Obecnie ponowiłem przelew:
![image](https://user-images.githubusercontent.com/35328055/232029139-a6219522-35d1-4d96-bbd9-805bc3a48502.png)


W zakładce weryfikacji firmy obecnie widnieje status:
![image](https://user-images.githubusercontent.com/35328055/232029207-4ea90cf6-7196-44ae-9971-badb63d285cc.png)

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, udało mi się teraz aktywować Twoje konto.
