### ISSUE TITLE
Product variation issue when changing language to english

### ISSUE THREAD

**Issue by dmsmatrix** [allegro/allegro-api#6960]
I have created products that include various variations. 
However, when I switch the language to English, the variations are not visible. 
On the other hand, when I switch to Polski language, the variations are displayed. 
I have provided the Request and Response details, along with a snapshot of the offers page for reference.
Can you please confirm whether the variations have been added successfully or partially? 
Additionally, I noticed that the group view for the variations is not visible on the offers dashboard.

[Request.txt](https://github.com/allegro/allegro-api/files/11231740/Request.txt)
[Response.txt](https://github.com/allegro/allegro-api/files/11231766/Response.txt)

![image](https://user-images.githubusercontent.com/92523331/232020397-833cd7fa-3e12-41ea-9e1f-c1231be03db0.png)
![image](https://user-images.githubusercontent.com/92523331/232020490-96281837-9a74-47c6-a3ca-ed5419d0b5fa.png)

**Comment by PrzemyslawLukanowski** [comment]
This is correct and expected behavior - a multi-variant offer was created successfully, but variants are visible only in Polish language settings.

**Comment by dmsmatrix** [comment]
What about offers dashboard, developers are not able to see variants as group in Polish language.

**Comment by PrzemyslawLukanowski** [comment]
Multi-variant offers can be checked here https://allegro.pl/moje-allegro/sprzedaz/wielowariantowosc using Polish language or via API, using [GET /sale/offer-variants](https://developer.allegro.pl/documentation/#operation/getVariantSets).
