### ISSUE TITLE
 /sale/products szukanie po EAN?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#6962]
Dzień dobry,
czy zasób /sale/products umożliwia wyszukanie produktu po kodzie EAN w katalogu produktów.

W dokumentacji jest jedynie:
identyfikatorze produktu,
nazwie produktu,
kategorii produktu oraz kategoriach podobnych, w których także możesz wystawić dany produkt,
podstawowych parametrach produktu,
zdjęciach produktu,
opisie produktu.

**Comment by PrzemyslawLukanowski** [comment]
Tak, wspominamy o tym właśnie w przytocznym przez Ciebie [poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-znalezc-produkt) oraz w [dokumentacji](https://developer.allegro.pl/documentation/#operation/getSaleProducts) - musisz użyć parametrów **phrase**, gdzie wskazujesz konkretny numer GTIN oraz **mode**, gdzie określasz tryb wyszukiwania, czyli w Twoim przypadku GTIN.

Fragment, który przytoczyłeś, dotyczy informacji, jakie zwrócimy w odpowiedzi.

**Comment by AleksyZajac** [comment]
Dziękuje za informacje. Nie wiem jak to przeoczyłem.
