### ISSUE TITLE
Allegro PROBLEMS allegro_exception in updOffer10

### ISSUE THREAD

**Issue by Mojeallegro123** [allegro/allegro-api#6963]
2023-04-14 23:26:59 - stdClass Object
(
    [id] => 9293664317
    [name] => Zestaw do MALOWANIA PO NUMERACH prezent - IPICASSO
    [category] => stdClass Object
        (
            [id] => 260064
        )

    [product] =>
    [parameters] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 11323
                    [valuesIds] => Array
                        (
                            [0] => 11323_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [1] => stdClass Object
                (
                    [id] => 248928
                    [valuesIds] => Array
                        (
                            [0] => 248928_968629
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [2] => stdClass Object
                (
                    [id] => 223329
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 50
                        )

                    [rangeValue] =>
                )

            [3] => stdClass Object
                (
                    [id] => 223333
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 40
                        )

                    [rangeValue] =>
                )

            [4] => stdClass Object
                (
                    [id] => 220913
                    [valuesIds] => Array
                        (
                            [0] => 220913_1
                            [1] => 220913_4
                            [2] => 220913_8
                            [3] => 220913_16
                            [4] => 220913_32
                            [5] => 220913_64
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [5] => stdClass Object
                (
                    [id] => 774
                    [valuesIds] => Array
                        (
                            [0] => 774_6
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [6] => stdClass Object
                (
                    [id] => 17448
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 0.75
                        )

                    [rangeValue] =>
                )

            [7] => stdClass Object
                (
                    [id] => 225693
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 6928405041821
                        )

                    [rangeValue] =>
                )

        )

    [customParameters] =>
    [description] => stdClass Object
        (
            [sections] => Array
                (
                    [0] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] =>
https://a.allegroimg.com/original/117650/fb4e7fee472ab4a0af29c1956b7a
                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <h1>Czas na
miłość</h1><p>(PC4050182)</p><p>PODSTAWOWE CECHY
CHARAKTERYSTYCZNE:</p><ul><li>Rozmiar obrazu
<b>40x50</b></li><li>Fabuła                        <b> Miejskie
krajobrazy</b></li><li>Format obrazu         <b>Pojedynczy
obraz</b></li><li>Marka
<b>Picasso</b></li><li>Seria
<b>Classic</b></li></ul><p>DODATKOWE CECHY
CHARAKTERYSTYCZNE:</p><ul><li>Ilość kolorów w zestawie:
<b>23</b></li><li>Trudność ( od 1 do 5)       <b> 3</b></li></ul>
                                        )

                                )

                        )

                    [1] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] =>
<p>Przedstawiamy Państwu zestaw pobudzający kreatywność «Obraz po
numerach» Picasso serii Classic, który wypełni życie kolorami,
emocjami i pomoże ciekawie i ekscytująco spędzić
czas.</p><p>Kolorowanka po numerach – jest wspaniałym prezentem,
pięknym elementem dekoracyjnym, niezwykłym elementem wnętrza i
oryginalną niespodzianką!</p><p>Zacznij malować teraz i stwórz
niesamowity, kolorowy obraz własnoręcznie nawet bez umiejętności
malowania!</p><p>Zestaw Picasso Classic ma wszystko, co jest potrzebne
dla przyszłego arcydzieła:</p>
                                        )

                                )

                        )

                    [2] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] =>
https://a.allegroimg.com/original/064b15/726e8b95421c8f8e69be3a1f0d7d
                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <p><b>1)
Jaskrawe barwne opakowanie-dyplomatka,</b> wyposażone w wygodną rączkę
do przenoszenia. Zapakowany w taki sposób obraz będzie wspaniałym
prezentem waszym krewnym i bliskim</p>
                                        )

                                )

                        )

                    [3] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <p><b>2)
Prawdziwe, jakościowo zagruntowane płótno jest wykonane w 100 % z
bawełny.</b> Płótno jest podzielone na strefy z numerami,
przeznaczonymi do malowania. Wyraźne rozgraniczenie segmentów pozwala
łatwo i szybko zamalować odpowiednie pole farbą z przyporządkowanym do
niego numerem.</p><p>Zamiast naturalnego płótna niektórzy producenci
wykorzystują gruby karton o gęstej teksturze. Również można natknąć
się na obrazy z płótnami syntetycznymi, które są tańsze. Jednak w
rezultacie końcowym mogą Państwa rozczarować, ponieważ na płótno
syntetyczne całkiem inaczej nakłada się farba, która źle wsiąka.
Kolory nie są tak intensywne, wygląd zewnętrzny obrazu jest
gorszy.</p><p>Tylko naturalne płótno bawełniane stanowi najbardziej
optymalny i właściwy wybór. Przecież właśnie na takich płótnach malują
prawdziwi artyści. Właśnie dlatego wszystkie komplety do twórczości
PICASSO wyróżniają się wyjątkowym płótnem naturalnym.</p>
                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] =>
https://a.allegroimg.com/original/066fe5/a2171df947a7b481c92c4a23b47a
                                        )

                                )

                        )

                    [4] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] =>
https://a.allegroimg.com/original/06b55d/f81d36684b83adbc6917794ac123
                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <p><b>3)
Płótno jest naciągnięte na drewniany blejtram z wysuszonego
drewna,</b> który służy jako trwały szkielet do gotowej pracy
zachowując kształt obrazu przez dłuższe lata. Gotową pracę można
powiesić na ścianę zarówno na blejtramie, jak i w odpowiedniej ramce,
która będzie harmonizować z wnętrzem.</p><p>Niektórzy producenci
obrazów nie kompletują swoich zestawów drewnianymi blejtramami. W
wyniku otrzymasz skręcony zgnieciony rulon płótna, na którym będzie
niewygodnie malować, a po malowaniu będzie potrzebne wykonanie
indywidualnego blejtramu. Oszczędzanie na takich kompletach doprowadzi
w przyszłości do dodatkowych nakładów.</p><p><b>4) Komplet drewnianych
pędzli do malowania</b> z różną grubością pędzelka  dla wygodnego
nakładania farby (3 sztuki)</p>
                                        )

                                )

                        )

                    [5] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <p><b>5)
Jakość farb i ich właściwy dobór w dużej mierze określa rezultat
końcowy gotowej pracy.</b></p><p>We wszystkich obrazach po numerach
PICASSO znajdą Państwo komplet wysokiej jakości, bezpiecznych i
ekologicznie czystych farb akrylowych nieszkodliwych dla
zdrowia.</p><p>Farby są rozlane do indywidualnych słoiczków, z których
każdy posiada swój numer. Wszystkie słoiczki są zapakowane w specjalne
opakowanie próżniowe, dzięki któremu zachowują swoje właściwości przez
wiele lat. Liczba kolorów i odcieni farb zależy od rozmiaru i
złożoności obrazu i może osiągać 50 różnych kolorów.</p><p>Wszystkie
farby w kompletach PICASSO są dobrane w taki sposób, że nie wymagają
mieszania i od razu są gotowe do naniesienia. Nie musisz tracić czasu
na otrzymanie potrzebnego koloru, odcienia, mieszając farby ze sobą
nawzajem – o tym zawczasu zatroszczył się producent. A to znaczy, że
stworzyć swoje arcydzieło można szybko, prosto i z gwarantowanym
wynikiem.</p>
                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] =>
https://a.allegroimg.com/original/06ed6e/4494a17f4c77bf43c44a9f0c7748
                                        )

                                )

                        )

                    [6] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] =>
https://a.allegroimg.com/original/06ad16/cd59821d45cc9cb926529d512a5e
                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <p><b>6)
Elementy mocowania na ścianę.</b> Proste i efektywne rozwiązanie,
pozwalające szybko i łatwo umocować blejtram z płótnem na powierzchni
pionowej. Szczególnie pięknie obraz będzie wyglądać w obramowaniu z
indywidualnych ramek, które można nabyć w odpowiednich pracowniach
twórczych.</p>
                                        )

                                )

                        )

                    [7] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <p>Pozostaje
tylko dodać do zestawu troche cierpliwości, chęci i 2 łyżeczki talentu
;-)</p>
<p>Maluj z natchnieniem i przyjemnością – wszystko się uda, Picasso
gwarantuje!</p>
                                        )

                                )

                        )

                    [8] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] =>
https://a.allegroimg.com/original/062a9c/e0f5b45c4d6bb3d1dfba9eead0e4
                                        )

                                )

                        )

                )

        )

    [compatibilityList] =>
    [tecdocSpecification] =>
    [images] => Array
        (
            [0] => stdClass Object
                (
                    [url] =>
https://a.allegroimg.com/original/117650/fb4e7fee472ab4a0af29c1956b7a
                )

            [1] => stdClass Object
                (
                    [url] =>
https://a.allegroimg.com/original/064b15/726e8b95421c8f8e69be3a1f0d7d
                )

            [2] => stdClass Object
                (
                    [url] =>
https://a.allegroimg.com/original/066fe5/a2171df947a7b481c92c4a23b47a
                )

            [3] => stdClass Object
                (
                    [url] =>
https://a.allegroimg.com/original/06b55d/f81d36684b83adbc6917794ac123
                )

            [4] => stdClass Object
                (
                    [url] =>
https://a.allegroimg.com/original/06ed6e/4494a17f4c77bf43c44a9f0c7748
                )

            [5] => stdClass Object
                (
                    [url] =>
https://a.allegroimg.com/original/06ad16/cd59821d45cc9cb926529d512a5e
                )

            [6] => stdClass Object
                (
                    [url] =>
https://a.allegroimg.com/original/062a9c/e0f5b45c4d6bb3d1dfba9eead0e4
                )

        )

    [sellingMode] => stdClass Object
        (
            [format] => BUY_NOW
            [price] => stdClass Object
                (
                    [amount] => 68.9000
                    [currency] => PLN
                )

            [startingPrice] =>
            [minimalPrice] =>
            [netPrice] =>
        )

    [tax] =>
    [stock] => stdClass Object
        (
            [available] => 20
            [unit] => UNIT
        )

    [publication] => stdClass Object
        (
            [duration] =>
            [status] => ACTIVE
            [startingAt] =>
            [endingAt] =>
            [endedBy] =>
            [republish] =>
            [marketplaces] => stdClass Object
                (
                    [base] => stdClass Object
                        (
                            [id] => allegro-pl
                        )

                    [additional] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [id] => allegro-cz
                                )

                        )

                )

        )

    [delivery] => stdClass Object
        (
            [shippingRates] => stdClass Object
                (
                    [id] => 9fe08c0b-16eb-415d-b6c3-2941ea212f9c
                )

            [handlingTime] => PT24H
            [additionalInfo] =>
            [shipmentDate] =>
        )

    [payments] => stdClass Object
        (
            [invoice] => VAT
        )

    [discounts] =>
    [afterSalesServices] => stdClass Object
        (
            [impliedWarranty] => stdClass Object
                (
                    [id] => 47b92ed8-886d-43ce-a4e4-0e266390f3d6
                )

            [returnPolicy] => stdClass Object
                (
                    [id] => c9cb7e92-a843-428f-a961-6c4ff315a21c
                )

            [warranty] => stdClass Object
                (
                    [id] => 5530afbe-7255-4bc7-9478-ff4b9e9886e5
                )

        )

    [additionalServices] =>
    [sizeTable] =>
    [fundraisingCampaign] =>
    [promotion] => stdClass Object
        (
            [emphasized] =>
            [bold] =>
            [highlight] =>
            [departmentPage] =>
            [emphasizedHighlightBoldPackage] =>
        )

    [location] => stdClass Object
        (
            [countryCode] => PL
            [province] => MAZOWIECKIE
            [city] => Piaseczno
            [postCode] => 05-500
        )

    [external] => stdClass Object
        (
            [id] => PC4050182
        )

    [attachments] => Array
        (
        )

    [contact] =>
    [validation] => stdClass Object
        (
            [errors] => Array
                (
                )

            [warnings] => Array
                (
                )

            [validatedAt] => 2023-04-05T12:24:36.125Z
        )

    [b2b] => stdClass Object
        (
            [buyableOnlyByBusiness] =>
        )

    [messageToSellerSettings] => stdClass Object
        (
            [mode] => OPTIONAL
            [hint] =>
        )

    [createdAt] => 2020-05-21T12:02:08.000Z
    [updatedAt] => 2023-04-05T12:24:36.125Z
    [language] => pl-PL
    [additionalMarketplaces] => stdClass Object
        (
            [allegro-cz] => stdClass Object
                (
                    [sellingMode] => stdClass Object
                        (
                            [price] => stdClass Object
                                (
                                    [amount] => 343.00
                                    [currency] => CZK
                                )

                        )

                    [publication] => stdClass Object
                        (
                            [state] => REFUSED
                        )

                )

        )

    [taxSettings] => stdClass Object
        (
            [rates] => Array
                (
                )

            [subject] =>
            [exemption] =>
        )

    [response_headers] => Array
        (
            [0] => HTTP/1.0 200 OK
            [1] => expires: 0
            [2] => cache-control: no-cache, no-store, max-age=0, must-revalidate
            [3] => x-xss-protection: 1; mode=block
            [4] => pragma: no-cache
            [5] => x-frame-options: DENY
            [6] => trace-id: d4a0fba32f2cc545
            [7] => date: Fri, 14 Apr 2023 21:26:58 GMT
            [8] => x-content-type-options: nosniff
            [9] => strict-transport-security: max-age=31536000 ;
includeSubDomains
            [10] => content-type: application/vnd.allegro.public.v1+json
        )

)
 stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => VALIDATION_ERROR
                    [message] => Platforms other than [allegro.pl](http://allegro.pl/) only
support offers with a product linked.
                    [details] =>
ConstraintViolationException.ForeignMarketplacesWithProductOnly
                    [path] => null
                    [userMessage] => W serwisie innym niż [allegro.pl](http://allegro.pl/)
wspierane są tylko oferty z podpiętym produktem.
                )

        )

)
2023-04-14 23:26:59 - stdClass Object
(
    [id] => 9293664317
    [name] => Zestaw do MALOWANIA PO NUMERACH prezent - IPICASSO
    [category] => stdClass Object
        (
            [id] => 260064
        )

    [product] =>
    [parameters] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 11323
                    [valuesIds] => Array
                        (
                            [0] => 11323_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [1] => stdClass Object
                (
                    [id] => 248928
                    [valuesIds] => Array
                        (
                            [0] => 248928_968629
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [2] => stdClass Object
                (
                    [id] => 223329
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 50
                        )

                    [rangeValue] =>
                )

            [3] => stdClass Object
                (
                    [id] => 223333
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 40
                        )

                    [rangeValue] =>
                )

            [4] => stdClass Object
                (
                    [id] => 220913
                    [valuesIds] => Array
                        (
                            [0] => 220913_1
                            [1] => 220913_4
                            [2] => 220913_8
                            [3] => 220913_16
                            [4] => 220913_32
                            [5] => 220913_64
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [5] => stdClass Object
                (
                    [id] => 774
                    [valuesIds] => Array
                        (
                            [0] => 774_6
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [6] => stdClass Object
                (
                    [id] => 17448
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 0.75
                        )

                    [rangeValue] =>
                )

            [7] => stdClass Object
                (
                    [id] => 225693
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 6928405041821
                        )

                    [rangeValue] =>
                )

        )

    [customParameters] =>
    [description] => stdClass Object
        (
            [sections] => Array
                (
                    [0] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] =>
https://a.allegroimg.com/original/117650/fb4e7fee472ab4a0af29c1956b7a
                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <h1>Czas na
miłość</h1><p>(PC4050182)</p><p>PODSTAWOWE CECHY
CHARAKTERYSTYCZNE:</p><ul><li>Rozmiar obrazu
<b>40x50</b></li><li>Fabuła                        <b> Miejskie
krajobrazy</b></li><li>Format obrazu         <b>Pojedynczy
obraz</b></li><li>Marka
<b>Picasso</b></li><li>Seria
<b>Classic</b></li></ul><p>DODATKOWE CECHY
CHARAKTERYSTYCZNE:</p><ul><li>Ilość kolorów w zestawie:
<b>23</b></li><li>Trudność ( od 1 do 5)       <b> 3</b></li></ul>
                                        )

                                )

                        )

                    [1] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] =>
<p>Przedstawiamy Państwu zestaw pobudzający kreatywność «Obraz po
numerach» Picasso serii Classic, który wypełni życie kolorami,
emocjami i pomoże ciekawie i ekscytująco spędzić
czas.</p><p>Kolorowanka po numerach – jest wspaniałym prezentem,
pięknym elementem dekoracyjnym, niezwykłym elementem wnętrza i
oryginalną niespodzianką!</p><p>Zacznij malować teraz i stwórz
niesamowity, kolorowy obraz własnoręcznie nawet bez umiejętności
malowania!</p><p>Zestaw Picasso Classic ma wszystko, co jest potrzebne
dla przyszłego arcydzieła:</p>
                                        )

                                )

                        )

                    [2] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] =>
https://a.allegroimg.com/original/064b15/726e8b95421c8f8e69be3a1f0d7d
                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <p><b>1)
Jaskrawe barwne opakowanie-dyplomatka,</b> wyposażone w wygodną rączkę
do przenoszenia. Zapakowany w taki sposób obraz będzie wspaniałym
prezentem waszym krewnym i bliskim</p>
                                        )

                                )

                        )

                    [3] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <p><b>2)
Prawdziwe, jakościowo zagruntowane płótno jest wykonane w 100 % z
bawełny.</b> Płótno jest podzielone na strefy z numerami,
przeznaczonymi do malowania. Wyraźne rozgraniczenie segmentów pozwala
łatwo i szybko zamalować odpowiednie pole farbą z przyporządkowanym do
niego numerem.</p><p>Zamiast naturalnego płótna niektórzy producenci
wykorzystują gruby karton o gęstej teksturze. Również można natknąć
się na obrazy z płótnami syntetycznymi, które są tańsze. Jednak w
rezultacie końcowym mogą Państwa rozczarować, ponieważ na płótno
syntetyczne całkiem inaczej nakłada się farba, która źle wsiąka.
Kolory nie są tak intensywne, wygląd zewnętrzny obrazu jest
gorszy.</p><p>Tylko naturalne płótno bawełniane stanowi najbardziej
optymalny i właściwy wybór. Przecież właśnie na takich płótnach malują
prawdziwi artyści. Właśnie dlatego wszystkie komplety do twórczości
PICASSO wyróżniają się wyjątkowym płótnem naturalnym.</p>
                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] =>
https://a.allegroimg.com/original/066fe5/a2171df947a7b481c92c4a23b47a
                                        )

                                )

                        )

                    [4] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] =>
https://a.allegroimg.com/original/06b55d/f81d36684b83adbc6917794ac123
                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <p><b>3)
Płótno jest naciągnięte na drewniany blejtram z wysuszonego
drewna,</b> który służy jako trwały szkielet do gotowej pracy
zachowując kształt obrazu przez dłuższe lata. Gotową pracę można
powiesić na ścianę zarówno na blejtramie, jak i w odpowiedniej ramce,
która będzie harmonizować z wnętrzem.</p><p>Niektórzy producenci
obrazów nie kompletują swoich zestawów drewnianymi blejtramami. W
wyniku otrzymasz skręcony zgnieciony rulon płótna, na którym będzie
niewygodnie malować, a po malowaniu będzie potrzebne wykonanie
indywidualnego blejtramu. Oszczędzanie na takich kompletach doprowadzi
w przyszłości do dodatkowych nakładów.</p><p><b>4) Komplet drewnianych
pędzli do malowania</b> z różną grubością pędzelka  dla wygodnego
nakładania farby (3 sztuki)</p>
                                        )

                                )

                        )

                    [5] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <p><b>5)
Jakość farb i ich właściwy dobór w dużej mierze określa rezultat
końcowy gotowej pracy.</b></p><p>We wszystkich obrazach po numerach
PICASSO znajdą Państwo komplet wysokiej jakości, bezpiecznych i
ekologicznie czystych farb akrylowych nieszkodliwych dla
zdrowia.</p><p>Farby są rozlane do indywidualnych słoiczków, z których
każdy posiada swój numer. Wszystkie słoiczki są zapakowane w specjalne
opakowanie próżniowe, dzięki któremu zachowują swoje właściwości przez
wiele lat. Liczba kolorów i odcieni farb zależy od rozmiaru i
złożoności obrazu i może osiągać 50 różnych kolorów.</p><p>Wszystkie
farby w kompletach PICASSO są dobrane w taki sposób, że nie wymagają
mieszania i od razu są gotowe do naniesienia. Nie musisz tracić czasu
na otrzymanie potrzebnego koloru, odcienia, mieszając farby ze sobą
nawzajem – o tym zawczasu zatroszczył się producent. A to znaczy, że
stworzyć swoje arcydzieło można szybko, prosto i z gwarantowanym
wynikiem.</p>
                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] =>
https://a.allegroimg.com/original/06ed6e/4494a17f4c77bf43c44a9f0c7748
                                        )

                                )

                        )

                    [6] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] =>
https://a.allegroimg.com/original/06ad16/cd59821d45cc9cb926529d512a5e
                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <p><b>6)
Elementy mocowania na ścianę.</b> Proste i efektywne rozwiązanie,
pozwalające szybko i łatwo umocować blejtram z płótnem na powierzchni
pionowej. Szczególnie pięknie obraz będzie wyglądać w obramowaniu z
indywidualnych ramek, które można nabyć w odpowiednich pracowniach
twórczych.</p>
                                        )

                                )

                        )

                    [7] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <p>Pozostaje
tylko dodać do zestawu troche cierpliwości, chęci i 2 łyżeczki talentu
;-)</p>
<p>Maluj z natchnieniem i przyjemnością – wszystko się uda, Picasso
gwarantuje!</p>
                                        )

                                )

                        )

                    [8] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] =>
https://a.allegroimg.com/original/062a9c/e0f5b45c4d6bb3d1dfba9eead0e4
                                        )

                                )

                        )

                )

        )

    [compatibilityList] =>
    [tecdocSpecification] =>
    [images] => Array
        (
            [0] => stdClass Object
                (
                    [url] =>
https://a.allegroimg.com/original/117650/fb4e7fee472ab4a0af29c1956b7a
                )

            [1] => stdClass Object
                (
                    [url] =>
https://a.allegroimg.com/original/064b15/726e8b95421c8f8e69be3a1f0d7d
                )

            [2] => stdClass Object
                (
                    [url] =>
https://a.allegroimg.com/original/066fe5/a2171df947a7b481c92c4a23b47a
                )

            [3] => stdClass Object
                (
                    [url] =>
https://a.allegroimg.com/original/06b55d/f81d36684b83adbc6917794ac123
                )

            [4] => stdClass Object
                (
                    [url] =>
https://a.allegroimg.com/original/06ed6e/4494a17f4c77bf43c44a9f0c7748
                )

            [5] => stdClass Object
                (
                    [url] =>
https://a.allegroimg.com/original/06ad16/cd59821d45cc9cb926529d512a5e
                )

            [6] => stdClass Object
                (
                    [url] =>
https://a.allegroimg.com/original/062a9c/e0f5b45c4d6bb3d1dfba9eead0e4
                )

        )

    [sellingMode] => stdClass Object
        (
            [format] => BUY_NOW
            [price] => stdClass Object
                (
                    [amount] => 68.9000
                    [currency] => PLN
                )

            [startingPrice] =>
            [minimalPrice] =>
            [netPrice] =>
        )

    [tax] =>
    [stock] => stdClass Object
        (
            [available] => 20
            [unit] => UNIT
        )

    [publication] => stdClass Object
        (
            [duration] =>
            [status] => ACTIVE
            [startingAt] =>
            [endingAt] =>
            [endedBy] =>
            [republish] =>
            [marketplaces] => stdClass Object
                (
                    [base] => stdClass Object
                        (
                            [id] => allegro-pl
                        )

                    [additional] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [id] => allegro-cz
                                )

                        )

                )

        )

    [delivery] => stdClass Object
        (
            [shippingRates] => stdClass Object
                (
                    [id] => 9fe08c0b-16eb-415d-b6c3-2941ea212f9c
                )

            [handlingTime] => PT24H
            [additionalInfo] =>
            [shipmentDate] =>
        )

    [payments] => stdClass Object
        (
            [invoice] => VAT
        )

    [discounts] =>
    [afterSalesServices] => stdClass Object
        (
            [impliedWarranty] => stdClass Object
                (
                    [id] => 47b92ed8-886d-43ce-a4e4-0e266390f3d6
                )

            [returnPolicy] => stdClass Object
                (
                    [id] => c9cb7e92-a843-428f-a961-6c4ff315a21c
                )

            [warranty] => stdClass Object
                (
                    [id] => 5530afbe-7255-4bc7-9478-ff4b9e9886e5
                )

        )

    [additionalServices] =>
    [sizeTable] =>
    [fundraisingCampaign] =>
    [promotion] => stdClass Object
        (
            [emphasized] =>
            [bold] =>
            [highlight] =>
            [departmentPage] =>
            [emphasizedHighlightBoldPackage] =>
        )

    [location] => stdClass Object
        (
            [countryCode] => PL
            [province] => MAZOWIECKIE
            [city] => Piaseczno
            [postCode] => 05-500
        )

    [external] => stdClass Object
        (
            [id] => PC4050182
        )

    [attachments] => Array
        (
        )

    [contact] =>
    [validation] => stdClass Object
        (
            [errors] => Array
                (
                )

            [warnings] => Array
                (
                )

            [validatedAt] => 2023-04-05T12:24:36.125Z
        )

    [b2b] => stdClass Object
        (
            [buyableOnlyByBusiness] =>
        )

    [messageToSellerSettings] => stdClass Object
        (
            [mode] => OPTIONAL
            [hint] =>
        )

    [createdAt] => 2020-05-21T12:02:08.000Z
    [updatedAt] => 2023-04-05T12:24:36.125Z
    [language] => pl-PL
    [additionalMarketplaces] => stdClass Object
        (
            [allegro-cz] => stdClass Object
                (
                    [sellingMode] => stdClass Object
                        (
                            [price] => stdClass Object
                                (
                                    [amount] => 343.00
                                    [currency] => CZK
                                )

                        )

                    [publication] => stdClass Object
                        (
                            [state] => REFUSED
                        )

                )

        )

    [taxSettings] => stdClass Object
        (
            [rates] => Array
                (
                )

            [subject] =>
            [exemption] =>
        )

    [response_headers] => Array
        (
            [0] => HTTP/1.0 200 OK
            [1] => expires: 0
            [2] => cache-control: no-cache, no-store, max-age=0, must-revalidate
            [3] => x-xss-protection: 1; mode=block
            [4] => pragma: no-cache
            [5] => x-frame-options: DENY
            [6] => trace-id: d4a0fba32f2cc545
            [7] => date: Fri, 14 Apr 2023 21:26:58 GMT
            [8] => x-content-type-options: nosniff
            [9] => strict-transport-security: max-age=31536000 ;
includeSubDomains
            [10] => content-type: application/vnd.allegro.public.v1+json
        )

)
 stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => VALIDATION_ERROR
                    [message] => Platforms other than [allegro.pl](http://allegro.pl/) only
support offers with a product linked.
                    [details] =>
ConstraintViolationException.ForeignMarketplacesWithProductOnly
                    [path] => null
                    [userMessage] => W serwisie innym niż [allegro.pl](http://allegro.pl/)
wspierane są tylko oferty z podpiętym produktem.
                )

        )

)

**Comment by Mojeallegro123** [comment]
Błąd w aktualizacji oferty.

**Comment by AureliuszBrussy** [comment]
Oferta ma wprowadzoną intencję widoczności na marketplace allegro-cz, natomiast obecnie nie spełnia jednego z warunków takiej widoczności. W tym przypadku są dwie możliwości:
- przypisanie do oferty produktu (pole **product.id**),
- usunięcie intencji widoczności w allegro-cz (pole **publication.marketplaces.additional**).

Sprzedający może to także zrobić z poziomu zakładki [Mój asortyment](https://allegro.pl/moje-allegro/sprzedaz/obsluga-ofert/moj-asortyment).
