### ISSUE TITLE
Allegro Czechy

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#6964]
Czy jest planowane uruchomienie na sandboxie możliwości zakupu jako jako użytkownik Czeskiej wersji portalu, lub czy jest już taka możliwość?
W tej chwili można wystawiać produkty na wersji czeskiej ale nie ma chyba możliwości wykonania zakupu a chcielibyśmy sprawdzić wszystko w takim wariancie (głownie sposób w jaki będą przychodzić informacje o płatności)

**Comment by AureliuszBrussy** [comment]
Aktualnie nie udostępniamy Sandboxa marketplace'u allegro-cz. Gdy tylko się na to zdecydujemy - poinformujemy o tym.
