### ISSUE TITLE
Propozycja produktu - parametr kod producena

### ISSUE THREAD

**Issue by michalsukiennik** [allegro/allegro-api#6965]
Metoda /sale/product-proposals
Wysyłam
 
```
{
       "id":"224017",
         "name":"Kod producenta",
         "valuesIds":[
            
         ],
         "valuesLabels":[
            
         ],
         "values":[
            "33"
         ],
         "options":null
      },
```

W odpowiedzi jest błąd
`{"errors":[{"code":"ParameterException.InvalidParameterDtoException","message":"An error has occurred","details":null,"path":"parameters","userMessage":"Niepoprawnie zdefininiowano values, valuesIds lub rangeValue dla parametru 224017."}]}
`
Nie można wysyłać parametrów values... jeśli są pustą listą?

**Comment by PrzemyslawLukanowski** [comment]
Powodem błędu jest jest pusta tablica, którą wysyłasz dla `valuesIds` i `valuesLabels`. Zamiast tego nie wysyłaj tych pól/prześlij null, a problem nie powinien się powtórzyć.

**Comment by michalsukiennik** [comment]
```
{
   "name":"ttt",
   "category":{
      "Id":"315213"
   },
   "language":"pl-PL",
   "parameters":[
      {
         "Id":"11323",
         "ValuesIds":[
            "11323_1"
         ]
      },
      {
         "Id":"248811",
         "ValuesIds":[
            "248811_1073204"
         ]
      },
      {
         "Id":"247581",
         "ValuesIds":[
            "247581_716893"
         ]
      },
      {
         "Id":"224017",
         "Values":[
            "33"
         ]
      }
   ],
   "images":[
      {
         "url":"https://a.allegroimg.allegrosandbox.pl/original/116066/f44be6cb4b0ca5bd7d5eac57ceed"
      }
   ]
}
```
Odpowiedź
`{"errors":[{"code":"HttpMessageNotReadableException","message":"An error has occurred","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."}]}`
Bardzo ogólny komunikat błędu.

**Comment by PrzemyslawLukanowski** [comment]
Tym razem powodem problemu jest nieprawidłowe nazewnictwo, część pól rozpoczynasz z wielkiej litery, np. "Id", "Values", "ValuesIds", itp. W następnym kroku możesz ponownie wgrać zdjęcie na nasz serwer, ponieważ link wyżej nie jest już aktualny, dlatego otrzymasz aktualnie odpowiedź "Produkt powinien posiadać co najmniej jedno zdjęcie".

**Comment by PrzemyslawLukanowski** [comment]
Jeśli w odpowiedzi otrzymasz kod 201 Created, propozycja produktu automatycznie zostanie przez nas zaakceptowana, zatem możesz korzystać z otrzymanego ID.

**Comment by michalsukiennik** [comment]
A w przypadku ręcznego zatwierdzenia?

**Comment by PrzemyslawLukanowski** [comment]
Co masz na myśli przez ręczne zatwierdzenie? Takie zmiany są przez nas weryfikowane jedynie w przypadku propozycji zmian danych w produkcie, które zgłaszasz przez [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal). Wtedy aktualny status, czy zmiana została zatwierdzona czy tez nie, sprawdzisz za pomocą [GET /sale/products/change-proposals/{id}](https://developer.allegro.pl/documentation/#operation/getProductChangeProposal).

**Comment by michalsukiennik** [comment]
Utworzyłem propozycję produktu
```
{
   "id":null,
   "name":"22.04.2023",
   "category":{
      "id":"258277"
   },
   "language":"pl-PL",
   "parameters":[
      {
         "id":"11323",
         "valuesIds":[
            "11323_2"
         ]
      },
      {
         "id":"248811",
         "valuesIds":[
            "248811_1189512"
         ]
      },
      {
         "id":"214710",
         "valuesIds":[
            "214710_267638"
         ]
      },
      {
         "id":"224017",
         "values":[
            "3344"
         ]
      }
   ],
   "images":[
      {
         "url":"https://a.allegroimg.allegrosandbox.pl/original/11193e/45697488490bb6384f983beb1554"
      }
   ]
}
```
Parametr o ID 11323 odnosi się do stanu. 
Response nie zwraca parametru
```
{
   "id":"0c7502ed-ca8b-473e-bc66-db68b14a788f",
   "name":"22.04.2023",
   "category":{
      "id":"258277",
      "similar":[
         {
            "id":"316426"
         },
         {
            "id":"257785"
         },
         {
            "id":"112715"
         }
      ]
   },
   "parameters":[
      {
         "id":"214710",
         "valuesIds":[
            "214710_267638"
         ],
         "values":null
      },
      {
         "id":"248811",
         "valuesIds":[
            "248811_1189512"
         ],
         "values":null
      },
      {
         "id":"224017",
         "values":[
            "3344"
         ]
      }
   ],
   "images":[
      {
         "url":"https://a.allegroimg.allegrosandbox.pl/original/11193e/45697488490bb6384f983beb1554"
      }
   ],
   "language":"pl-PL"
}
```
Przekazana w żądaniu wartość parametru 11323_2 jest na liście słownikowej
```
{
         "id":"11323",
         "name":"Stan",
         "type":"dictionary",
         "required":true,
         "requiredForProduct":false,
         "unit":null,
         "options":{
            "variantsAllowed":false,
            "variantsEqual":true,
            "ambiguousValueId":null,
            "dependsOnParameterId":null,
            "requiredDependsOnValueIds":null,
            "displayDependsOnValueIds":null,
            "describesProduct":false,
            "customValuesEnabled":false
         },
         "dictionary":[
            {
               "id":"11323_1",
               "value":"Nowy",
               "dependsOnValueIds":[
                  
               ]
            },
            {
               "id":"11323_2",
               "value":"Używany",
               "dependsOnValueIds":[
                  
               ]
            },
```

**Comment by PrzemyslawLukanowski** [comment]
Tak, to prawidłowe zachowanie, ponieważ parametr `Stan` nie opisuje produktu (`"describesProduct":false`), jest parametrem ofertowym. Sprzedawcy, którzy wystawiają ofertę sprzedaży danego produktu, sami mogą określić, czy w ich ofercie stan jest nowy czy inny. Jeśli pobierzesz swoją ofertę, którą powiążesz z tym produktem, za pomocą GET /sale/product-offers/{offerId}, zobaczysz, że parametry produktowe zawarte są w sekcji `productSet.product.parameters`, natomiast te odnoszące się do oferty, są w `parameters`.
Zatem, parametry, które uwzględnimy w response dla utworzenia produktu w POST /sale/product-proposals, to te oznaczone flagą `"describesProduct":true`. Nie musisz przekazywać ich wszystkich, tylko te oznaczone jako `"requiredForProduct":true`.

**Comment by michalsukiennik** [comment]
Dzięki. W metodzie sale/products nie ma opcji wyszukiwania po ID. Przekazanie ID w parametrze phrase nie działa. Nie ma możliwości wyszukiwania po ID?

**Comment by PrzemyslawLukanowski** [comment]
Jeśli chcesz pobrać szczegóły produktu wg ID, skorzystaj z GET /sale/product/{productID}.
