### ISSUE TITLE
Problem z utworzeniem Avizo do FulFillment

### ISSUE THREAD

**Issue by Fudalii** [allegro/allegro-api#6966]
Witam.

Zasób: /fulfillment/advance-ship-notices  (POST)

Mimo, że otrzymuję response "Created" , tworzone jest Avizo (DRAFT) oraz mam w response listę produktów. To na samej stornie www.allegro.pl  w zakładce z roboczymi wersjami AVIZO nie widzę dodanych produktów ?!?

RESPONSE jest ok: 

{
"id:" "1596c400-4791-4ed8-8486-4439c49baa2c",
"displayNumber":"A-230417-0000056",
"status":"DRAFT",
"createdAt": "2023-04-17T16:16:18.646016705Z",
"updatedAt": "2023-04-17T16:16:18.646016705Z",
"items":[ ],  // Tutaj zwraca ładnie wszystkie produkty 
"labels":null,
"shipping":null,"
handlingUnit":null
}

Natomiast wysłanie zapytania dokładnie identycznej w formie jak pokazano to w ChangeLog z parametrami "HandlingUnit" i "Shipping" zwraca cały czas Nieznany błąd serwera i żeby spróbować za parę minut

{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Try again in a few minutes."}]}

!???

**Comment by PrzemyslawLukanowski** [comment]
Co do błędu `INTERNAL_SERVER_ERROR`- zwróć proszę uwagę czy wartość` ”COURIER_BY_SELLER”` nie przesyłasz w dodatkowym cudzysłowie, tzn.  `“”COURIER_BY_SELLER”“`. Czy utworzone awizo jesteś w stanie pobrać za pomocą GET /fulfillment/advance-ship-notices/{ID}? Czy nadal nie wyświetla się na stronie internetowej?

**Comment by Fudalii** [comment]
Avizo wyświetla się na www. Ale chodzi o to, że jak wchodzę w to Avizo lub klikam "Edytuj Avizo " - nie ma żadnych produktów. Jest puste :) 

Jeśli chodzi o parametr Metody - tak wysyłam w podwójnym cudzysłowie. Oto wysyłany JSON


{
"items":[],    // Tutaj wiadomo lista produktów. 

"handlingUnit":{"unitType":"BOX","amount":1,"labelsType":"ONE_FULFILMENT"},

"shipping":{"method":"\"COURIER_BY_SELLER\"","countryCode":"PL"}
}

Aktualnie działa jak wyślę tylko "items" bez pozostałych parametrów. Wtedy właśnie twory Avizo ale bez produktów mimo że response mówi ,że jest ok.

**Comment by PrzemyslawLukanowski** [comment]
Ok, rozumiem, wyświetlanie na stronie www jeszcze weryfikuję w takim razie, a co do podwójnego cudzysłowia - musisz właśnie użyć pojedynczego, czyli - "COURIER_BY_SELLER", wtedy request przejdzie poprawnie.

**Comment by Fudalii** [comment]
Ok faktycznie działa - przykładowe AVIZO A-230418-0000063 - f78e5882-fc3d-484e-87d3-e8145cf660b4

Niestety tak samo brak w nim produktów. 

Pełna odpowiedź serwera poniżej - status Created

{"id":"f78e5882-fc3d-484e-87d3-e8145cf660b4","displayNumber":"A-230418-0000063","status":"DRAFT","createdAt":"2023-04-18T07:43:54.946313493Z","updatedAt":"2023-04-18T07:43:54.946313493Z","items":[{"product":{"id":"2d3166fa-5fb7-4ace-a634-241624d1d5fe"},"quantity":2},{"product":{"id":"786a3b6e-4c9d-4adb-b774-89a58cf632a7"},"quantity":2},{"product":{"id":"c4481955-19f7-434c-b23a-e15083d4bcd2"},"quantity":2},{"product":{"id":"6efe032f-d172-4802-ac35-21d3f022eba4"},"quantity":2},{"product":{"id":"4d7f3f53-d2ac-4a2e-af9e-6c50b8fb0db5"},"quantity":2},{"product":{"id":"aeacc5a3-eea0-4265-9b1f-97f03279e09c"},"quantity":2},{"product":{"id":"e49500b2-d372-4efc-a592-98d8ed211f58"},"quantity":2},{"product":{"id":"0a2336f9-8cc8-45fa-864c-029745eb069b"},"quantity":2},{"product":{"id":"b6e9cde2-78bd-4d85-9bce-116a2b01b6ea"},"quantity":2},{"product":{"id":"422975ed-39d1-49db-a6ec-868c91c20874"},"quantity":2},{"product":{"id":"c460e85c-56a4-4c48-bccc-690d431a2f4a"},"quantity":2},{"product":{"id":"cee7d5c4-0342-4977-8470-331a2dc41572"},"quantity":2},{"product":{"id":"20f29464-7ed9-4c11-a675-46ebebdfcdc2"},"quantity":2},{"product":{"id":"404c05ae-2078-4992-abc9-d9d63f74acba"},"quantity":2},{"product":{"id":"21351084-fe8f-40e5-b6e4-3db1b5fb6e4a"},"quantity":2},{"product":{"id":"e95bd2c6-7bef-4d90-9e5a-77d22b1e9c66"},"quantity":3},{"product":{"id":"b711bd30-4db6-4e09-9f28-b43293a5c472"},"quantity":4},{"product":{"id":"74ba8a12-e8bd-4f74-a4e5-6c2138669910"},"quantity":2},{"product":{"id":"5dd58d04-662d-4bd4-9664-2490e97d2fb5"},"quantity":2},{"product":{"id":"79917e9e-ddd2-4454-a170-1afe75723c18"},"quantity":5},{"product":{"id":"cbdbb78a-a8d0-4664-bdad-17c95cad37e1"},"quantity":2},{"product":{"id":"bab0f1c7-c967-4522-825d-c27dd5923651"},"quantity":4},{"product":{"id":"bd3ace56-caf5-4827-a6e2-63d4f3c857bd"},"quantity":2},{"product":{"id":"21ab49cd-06f2-4c6f-92bd-af0384065928"},"quantity":2},{"product":{"id":"25ac9343-e10a-4b58-a324-4a76158ecf7b"},"quantity":2},{"product":{"id":"8bab1254-9d72-4720-8680-51451732e094"},"quantity":2},{"product":{"id":"5bb22805-ac2a-4f84-b74b-87acbf5bedda"},"quantity":4},{"product":{"id":"5608ebea-f0df-4331-aeb8-b71dac70ba93"},"quantity":2},{"product":{"id":"03eda0a9-2e37-4615-a5cd-e30962cafc7e"},"quantity":1},{"product":{"id":"049b5afa-7900-494e-bf5b-1451ce7dd3d5"},"quantity":2},{"product":{"id":"955e39a9-b324-4620-aea9-b8d403e4fe32"},"quantity":2},{"product":{"id":"f2b2ddda-8b88-4339-bd5d-344c82be672f"},"quantity":2},{"product":{"id":"2973e2dc-bbf5-4628-b91f-9e94510bf1c2"},"quantity":2},{"product":{"id":"ecaabd89-68af-4402-922c-45008d7040d4"},"quantity":3},{"product":{"id":"dc58d385-94bb-4681-bc50-064fce5e4306"},"quantity":2},{"product":{"id":"43e993ba-70e2-43bc-9d7e-db69875554bf"},"quantity":2},{"product":{"id":"d32f39fa-5958-4245-bd9a-87569060f792"},"quantity":1},{"product":{"id":"2a4d18c6-0b01-452e-a58d-450c4d5f388d"},"quantity":2},{"product":{"id":"9de675fc-d9d1-4d21-996f-28b8090b9c98"},"quantity":2},{"product":{"id":"328a9b61-6ed4-4b5b-9c98-2c69967352f2"},"quantity":4},{"product":{"id":"37edffc8-aa3c-4d7c-90b9-e2d92c156611"},"quantity":2},{"product":{"id":"608424bd-fd65-4695-b516-da6fd80174e6"},"quantity":2},{"product":{"id":"eda56a0c-764c-4eff-8e0d-8106b93c1691"},"quantity":2},{"product":{"id":"cc2a27f0-2df2-408d-9d8d-1cdb96207253"},"quantity":2},{"product":{"id":"4246fe2c-0e73-48b5-b44c-4f95bf846c2a"},"quantity":2},{"product":{"id":"9fe0da98-7573-4bbb-b937-22ac1a8de8a0"},"quantity":2},{"product":{"id":"007348c4-dc40-4893-823d-eb569ef0b496"},"quantity":2},{"product":{"id":"1739ebab-34c5-4280-b608-832721810530"},"quantity":4},{"product":{"id":"8813482e-80e7-4269-b4d2-d8d1f91c76ac"},"quantity":2},{"product":{"id":"3fa8f3b6-7541-46e9-9b53-16c532b9c870"},"quantity":1},{"product":{"id":"af2b521f-9552-441c-b99e-b58de9491623"},"quantity":1},{"product":{"id":"333581b0-1769-4f42-914c-0e08f9de466a"},"quantity":2},{"product":{"id":"648fca70-b710-4d1e-814b-71a1bf7dcae1"},"quantity":2},{"product":{"id":"ce8432d5-eb85-47cb-ae07-ebad6706d12f"},"quantity":2},{"product":{"id":"73d1edae-9a1e-473d-8d29-9ea4ddc81925"},"quantity":2},{"product":{"id":"5fb36651-5508-4914-8e06-aff18db95c49"},"quantity":2},{"product":{"id":"8d8f179b-abf1-4186-821d-af09890fb4ff"},"quantity":2},{"product":{"id":"25942e65-823d-4bce-b046-b4762a7767c5"},"quantity":3},{"product":{"id":"1f38c7ea-65a5-422c-8fc6-6d2d9c05ba20"},"quantity":1},{"product":{"id":"7d5221cc-3fbb-41df-b828-33392fa31120"},"quantity":1},{"product":{"id":"32283144-d2b3-4f12-9f80-5830165d9af2"},"quantity":1},{"product":{"id":"b1ea60cf-5ad3-45f9-bc71-dccef683ad4e"},"quantity":2},{"product":{"id":"413d4513-dcc2-4163-ada7-a11a77255c3b"},"quantity":2},{"product":{"id":"012df0dc-3557-4b55-beea-5e4c2cda4f7b"},"quantity":5},{"product":{"id":"5d4a2272-07d3-446b-9075-14282eb12913"},"quantity":2},{"product":{"id":"21e9a02c-0a69-4306-bf53-98a5fbac2781"},"quantity":2},{"product":{"id":"9c0c7b58-c659-4184-b36b-a5840dd8dd8f"},"quantity":3},{"product":{"id":"d964b732-3b44-478d-bb3e-c726e75349b4"},"quantity":2},{"product":{"id":"0f79fd68-d33a-437b-8619-48841c4063b5"},"quantity":1},{"product":{"id":"b398e05d-7f6f-4e30-9112-094b473c1776"},"quantity":2},{"product":{"id":"ddfcf435-ab3e-40a0-a4cb-2c4dc22c5adf"},"quantity":2},{"product":{"id":"c8447baa-eb3d-4b44-a79e-f483f2c8525e"},"quantity":4},{"product":{"id":"bab1785c-9db0-454a-8d44-6e3938d77ec2"},"quantity":2},{"product":{"id":"4a0a0e18-2c66-4ec0-954f-7db60d3cf9ec"},"quantity":2}],"labels":{"fileUrl":"https://api.allegro.pl/fulfillment/advance-ship-notices/f78e5882-fc3d-484e-87d3-e8145cf660b4/labels"},"shipping":{"estimatedTimeOfArrival":null,"method":"COURIER_BY_SELLER","trackingNumber":null,"truckLicencePlate":null,"thirdParty":{"name":null,"orderNumber":null},"countryCode":"PL"},"handlingUnit":{"unitType":"BOX","amount":1,"labelsType":"ONE_FULFILMENT"}}

**Comment by PrzemyslawLukanowski** [comment]
Udało nam się znaleźć przyczynę błędu - problem polega na tym, że ze względu na pewne kwestie techniczne po naszej stronie, dostępność produktów na www w ASN uzależniona aktualnie jest od tego, w jaki sposób ASN zostało utworzone. Tworząc je przez API, produkty - jak w opisanym przypadku - nie będę dostępne przez www. Problem oczywiście nie wystąpi, jeśli ASN modyfikowałbyś dalej za pomocą API. W poniedziałek wdrożymy poprawkę, która wyeliminuje ten problem, zatem będziesz mógł edytować ASN na stronie internetowej niezależnie od tego, w jaki sposób je utworzyłeś.
