### ISSUE TITLE
Upload products by XML feed instead of using API 

### ISSUE THREAD

**Issue by KirillkaVolkov** [allegro/allegro-api#6967]
Afternoon! My name is Kyrylo I am a new Allegro seller from Ukraine.

I work for cptheseller. It's a new seller on Allegro platform. 

As for Allegro account. 

We have around 6000 product in our price list.

I have been trying to upload all our product to Allegro MP through CSV file uploader. But I've realised that it doesn't appropriate way for such enhanced product list as we have. Also I've looked through your REST API docs. But we have not had our application yet to create connection to your API services. Son we cannot even download the category three because we cannot authenticate by Oauth protocol ((

So, I wanted to ask you - perhaps you some feature that allows us to upload our product by XML's format file ? 

It will be a solution for us ! We already maintane an XML creator service, so we can provide a relevant file for your system. By the way the file updates by cron job, it ensures us to keep data such as prices availability up to date!  As an example we already have a file
[https://toptul.online/products_feed.xml?hash_tag=442309995a1416e3104d287504a1846f&s[…]n=0&yandex_cpa...](https://toptul.online/products_feed.xml?hash_tag=442309995a1416e3104d287504a1846f&s[%E2%80%A6]n=0&yandex_cpa=&process_presence_sure=&languages=ru&group_ids=)

So is it possible to upload our products by XML ?

Thanks a lot in advance! I'll be waiting for your answer

**Comment by PrzemyslawLukanowski** [comment]
Hello, Unfortunately, in our public API, we do not provide such a possibility to upload products in XML format.
