### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by pebepebe** [allegro/allegro-api#6968]
Dzień dobry.
Dopiero zaczynam testy na sandboxie, więc proszę o wyrozumiałość. Konto fan@fan.pl (testFaN).
Przy próbie wyszukania produktu lub dodania oferty mam access denied.

https://api.allegro.pl.allegrosandbox.pl/sale/products?mode=GTIN&phrase=602455012487

{"errors":[{"code":"AccessDeniedException","message":"Access denied.","details":null,"path":null,"userMessage":"No access."}]} 

Proszę o pomoc.

**Comment by AureliuszBrussy** [comment]
Konto nie jest w pełni aktywne, stąd brak dostępu. W zakładce [Moje konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto) wykonaj symulację przelewu weryfikacyjnego (online). Daj znać, jak już to zrobisz.

**Comment by pebepebe** [comment]
To już robiłem, teraz jest tam tylko "Proces weryfikacji może potrwać kilka dni. Poinformujemy Cię o decyzji e-mailem." i Kontynuuj.

**Comment by AureliuszBrussy** [comment]
W trakcie weryfikacji wybrałeś "przelew tradycyjny", abym mógł aktywować konto konieczne jest wykonanie symulacji przelewu online. Prosiłbym o powtórzenie procesu w zakładce [Moje konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto).

**Comment by pebepebe** [comment]
Tylko nie bardzo wiem jak to zrobić, po wejściu w "ustaw wypłaty środków" nie mam możliwości zmiany.  Jak kliknę "aktywuj sprzedaż" wchodzi na tą samą stronę.
![Clipboard01](https://user-images.githubusercontent.com/131149297/232743716-7917567b-25ee-4dc8-8e87-20c6885ebb0c.jpg)

**Comment by AureliuszBrussy** [comment]
Spróbuj skorzystać z [tego linku](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty). Daj znać, jeżeli wciąż nie widzisz możliwości zmiany sposoby weryfikacji (szybka wpłata online).

**Comment by pebepebe** [comment]
Nie widzę, w tym linku jest dokładnie to samo co na powyższym screenie.

**Comment by AureliuszBrussy** [comment]
@pebepebe spróbuj teraz.

**Comment by pebepebe** [comment]
Jest OK, zasymulowałem przelew online, proszę o aktywację.

**Comment by pebepebe** [comment]
Tak czytam o tych metodach autoryzacji i chyba jestem coraz głupszy... Potrzebuję napisać program do komunikacji z Waszym API który będzie działał na serwerze bez kompletnie żadnej integracji z użytkownikiem. Którą metodą autoryzacji można uzyskać coś takiego?

**Comment by AureliuszBrussy** [comment]
Użytkownik musi wyrazić zgodę na działanie aplikacji w jego imieniu (zalogować się na konto i wyrazić zgodę), więc całkowite pominięcie integracji użytkownika przy pierwszym uwierzytelnianiu aplikacji nie jest możliwe. Później natomiast wystarczy, że skorzystasz z [przedłużania ważności access tokena](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena). Tutaj ingerencja użytkownika nie będzie już wymagana. 

Udostępniamy też [Client_credentials flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow), które umożliwia autoryzację aplikacji bez zgody użytkownika na jej działanie, jednak jest metoda, generująca token przeznaczony do ograniczonej liczby zasobów - w [dokumentacji](https://developer.allegro.pl/documentation) oznaczyliśmy takie zasoby (bearer-token-for-application).

**Comment by pebepebe** [comment]
Dziękuję za wyjaśnienia, zaczynam łapać, jednak natknąłem się na następny problem (pewnie coś źle robię).
Próbuję wygenerować na sandboxie token dla Device flow. Jestem zalogowany jako testFaN, pobieram device code i link do kliknięcia, klikam, pojawia się "udało się" i przy próbie pobrania tokena dostaję 
[code] => invalid_request
[message] => ClientId does not match authenticated client.

Czy może to być spowodowane tym, że w loginie są duże litery? Kilka razy przy próbie skojarzenia aplikacji miałem komunikat "jesteś zalogowany jako testfan, czy chcesz kontynuować jako testFaN" stąd moje wątpliwości.

**Comment by AureliuszBrussy** [comment]
Błąd ten najczęściej powodowany jest przez niepoprawne przekazywanie parametrów. Np. [w zgłoszeniu](https://github.com/allegro/allegro-api/issues/1224) użytkownik dotarł do rozwiązania problemów (w tamtym przypadku język to C#). 

Upewnij się też, że zarejestrowałeś aplikację [jako device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow).
