### ISSUE TITLE
Problem z edytowaniem zakończonej oferty

### ISSUE THREAD

**Issue by PiotrPioro** [allegro/allegro-api#6969]
Jak próbuję wznowić aukcję za pomocą PUT sale/offers/{offerId} to dostaje taki błąd:

VALIDATION_ERROR You cannot edit an expired offer with AUCTION in its sales format. You cannot edit an expired offer with AUCTION in its sales format. IllegalOfferUpdateException.IllegalEndedOfferUpdate publication.statusVALIDATION_ERROR You cannot edit parameters in auctions with bids already placed. You cannot edit parameters in auctions with bids already placed. IllegalOfferUpdateException.IllegalChangeAttributes parametersVALIDATION_ERROR You cannot change the price with bids already placed. You cannot change the price with bids already placed. IllegalOfferUpdateException.IllegalChangeAuctionPrice sellingModeVALIDATION_ERROR You cannot edit descriptions in auctions with bids already placed. You cannot edit descriptions in auctions with bids already placed. IllegalOfferUpdateException.DescriptionId descriptionVALIDATION_ERROR You cannot change the name with bids already placed. You cannot change the name with bids already placed. IllegalOfferUpdateException.IllegalChangeOfferName name. Trace-id=[9796dc1a37237e90].

Rozumiem, że w ten sposób mogę wznowić aukcję "kup teraz" a w jaki sposób można wznowić aukcję "licytacja i kup teraz"?
I mam jeszcze pytanie jak dawno temu ten sposób był zmieniany?

**Comment by AureliuszBrussy** [comment]
Nie wznowisz oferty z licytacją (sellingMode.format	
 = AUCTION) - powinieneś wystawić taką ofertę od nowa, pod nowym numerem. Nie zmienialiśmy nic w kwestii wznawiania aukcji.

**Comment by PiotrPioro** [comment]
Dziękuję
