### ISSUE TITLE
order/checkout-forms - ogólne pytania

### ISSUE THREAD

**Issue by Rnapzsih** [allegro/allegro-api#697]
Pewnie ktoś już gdzieś pytał, ale nie zaszkodzi jeszcze raz....

1. Czy zamówienia oznaczone jako wysłane będą zwracać inny status niż "READY_FOR_PROCESSING"? Jeżeli tak, to kiedy? 
2. Czy i kiedy będzie możliwość przesyłania statusu WYSŁANE do zamówień?

**Comment by PawelTaberski** [comment]
W odpowiedz na Twoje pytania na chwilę obecną nie planujemy zwracać innego statusu w fod-ach. Natomiast odnośnie drugiego pytania jeśli wdrożymy taką zmianę poinformujemy o tym, na chwilę obecną nie jestem w stanie podać terminu ani potwierdzić, że na pewno wdrożymy taką funkcjonalność.
