### ISSUE TITLE
Cannot convert access token to JSON

### ISSUE THREAD

**Issue by bartosz-macczak** [allegro/allegro-api#6970]
Próbuję uruchomić aplikację zbudowaną kilka lat temu.

Niestety po wysłaniu zapytania otrzymuję:

```
"error":"invalid_token"
"error_description":"Cannot convert access token to JSON"
```
Sprawdziłem:
- token jest sandboxowy, nieprzeterminowany
- konto w sandboxie ma status biznesowego

```
public string getOffers()
        {
            string token = "...";
            var client = new RestClient("https://api.allegro.pl.allegrosandbox.pl");
            var request = new RestRequest
            {
                Method = Method.GET,
                Resource = "/sale/offers"
            };

            request.AddHeader("Authorization", $"Bearer {token}");
            request.AddHeader("Accept", "application/vnd.allegro.public.v1+json");
            request.AddHeader("Content-Type", "application/vnd.allegro.public.v1+json");

            IRestResponse response = client.Execute(request);
            var content = response.Content;

            return content;
        }
```
Ktoś wie co mogę jeszcze sprawdzić?

**Comment by AureliuszBrussy** [comment]
Wygląda na to, że token nie jest poprawny - możliwe, że nie został np. przekazany w całości. Możesz wysłać nam przykładowy request (razem z pełnym access tokenem) i response przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). Dopisz wtedy, że dane dotyczą wątku #6970 na Githubie. Zweryfikujemy to.

**Comment by bartosz-macczak** [comment]
> Wygląda na to, że token nie jest poprawny - możliwe, że nie został np. przekazany w całości. Możesz wysłać nam przykładowy request (razem z pełnym access tokenem) i response przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). Dopisz wtedy, że dane dotyczą wątku #6970 na Githubie. Zweryfikujemy to.

Wysłałem

**Comment by bartosz-macczak** [comment]
Doszedłem sam do rozwiązania:
Token ma ponad 1500 znaków długości i nie mieścił się w bazie danych, możliwe że kilka lat temu był krótszy.

**Comment by AureliuszBrussy** [comment]
Tak, [3 lata temu zmienialiśmy długość tokenów](https://github.com/allegro/allegro-api/issues/3149).
