### ISSUE TITLE
Allegro One Box - pobieranie numeru śledzenia przesyłek UPS

### ISSUE THREAD

**Issue by Isudin** [allegro/allegro-api#6971]
Szanowni Państwo,
chciałbym się zapytać czy istnieje możliwość pobierania numeru śledzenia paczki UPS przez API dla sposobu dostawy (m. in.) ALLEGRO ONE BOX? Mam na myśli 18-sto znakowy numer UPS, nie zwracany przez API numer ALExxxxxxxxxxxx.
Próby jego pobrania przez _GET /order/carriers/{carrierId}/tracking?waybill={waybill}_ spełzły na niczym, niezależnie czy jako carrierId podawałem "ALLEGRO" (jak powinno być według danych z _GET /parcel-management/delivery-services_) czy "UPS" (z ciekawości czy coś to da).

**Comment by AureliuszBrussy** [comment]
Waybill umożliwiający śledzenie powinien być dostępny po pobraniu szczegółów utworzonej przesyłki ([GET /parcel-management/parcels/{parcelId}](https://developer.allegro.pl/documentation#operation/getParcelDetails)) w polu `items[].waybill`.

**Comment by Isudin** [comment]
Niestety nie o to mi chodzi, to jest wciąż numer ALExxxxxxxxxxxx, mój klient natomiast podesłał dodatkowo pytanie o numer w formacie xx xxx xxx xx xxxx xxxx, którym posługuje się UPS - i faktycznie gdy na monitoringu paczek tego kuriera posłużę się Państwa numerem, dostanę (w 3/4 ocenzurowany) osiemnastoznakowy numer.

**Comment by AureliuszBrussy** [comment]
W API WzA zwracamy tylko numer Allegro - nie ma opcji pobrania tego trackingu UPS.

**Comment by Isudin** [comment]
Rozumiem, dziękuję za odpowiedź
