### ISSUE TITLE
Problem przy wystawianiu ofert

### ISSUE THREAD

**Issue by PiotrPioro** [allegro/allegro-api#6972]
Od jakiegoś czasu lecą mi takie dwa błędy przy próbie wystawiania ofert.
BAD_REQUEST Unsupported request format. Unsupported request format. ValidationError.HttpMessageNotReadableException . Trace-id=[2bff5d98afba5b44].
i 
BAD_REQUEST Value 'Chiara Forthi.' already exists in parameter 'Marka' Value already exists: value='Chiara Forthi.', parameter.id='3786' . Trace-id=[310dd0f49e8b6edc].
Co powinienem poprawić w tych ofertach żeby te błędy nie leciały?

**Comment by PrzemyslawLukanowski** [comment]
> BAD_REQUEST Unsupported request format. Unsupported request format. ValidationError.HttpMessageNotReadableException . Trace-id=[2bff5d98afba5b44].

W tym przypadku, w polu `sellingMode.format`, przesyłasz nieznaną nam wartość `"COMBINE"`. Wspieramy wyłącznie `"BUY_NOW"`,` "AUCTION" `lub `"ADVERTISEMENT"`.

> BAD_REQUEST Value 'Chiara Forthi.' already exists in parameter 'Marka' Value already exists: value='Chiara Forthi.', parameter.id='3786' . Trace-id=[310dd0f49e8b6edc].

Tutaj natomiast błąd wskazuje na to, że w parametrze Marka (`3786`) wybraleś wartość niejednoznaczną (`3786_85`) i w polu `values` przekazujesz własną markę `Chiara Forthi.`. Marka o takiej nazwie znajduje się już na liście naszych dostępnych wartości, pod id `3786_1678747`. Aby uniknąć błędu, przekaż tę wartość w strukturze parametrów.

**Comment by PrzemyslawLukanowski** [comment]
Miej też proszę na uwadze, że zasoby /sale/offers (z pominięciem metody GET) do tworzenia oferty i /sale/offers/{id} wyłączymy z końcem roku, dlatego warto w planach uwzględnić już przepięcie się na zasoby /sale/product-offers i /sale/product-offers/{id}. Szczegóły znajdziesz w [naszym newsie.](https://developer.allegro.pl/news/na-poczatku-2024-roku-wylaczymy-zasoby-sale-offers-sluzace-do-tworzenia-i-edycji-ofert-BvqK3XOaEcW)

**Comment by PiotrPioro** [comment]
Żeby nie zmniejszyć ilość połączeń przechowuję potrzebne parametry dla danej kategorii w pamięci, za drugim razem w ciągu jednego dnia gdy potrzebne są parametry dla danej kategorii to biorę je z tej pamięci. Czy dalej trwa zmiana id w parametrach? To by tłumaczyło ten drugi błąd.

**Comment by PrzemyslawLukanowski** [comment]
Tak jest to aktualnie proces ciągły, jednak w tym przypadku nie doszło do zmiany ID parametru, ale dodaliśmy nową wartość na liście dostępnych marek, której wcześniej tam nie było (dlatego mogliście wysyłać własną wartość o takiej nazwie).

**Comment by PiotrPioro** [comment]
Dobrze, dziękuję.
