### ISSUE TITLE
Wypełnianie pola language w POST /sale/offers

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#6973]
Kilka dni temu wdrożyliśmy wypełnianie pola language w POST /sale/offers. Mimo to dostaliśmy dziś informację, że nie wypełniamy tego pola. Proszę o wskazanie co jest nie tak z tym przykładowym requestem. Czy pole language jest wstawione niepoprawnie?

trace-id: e70049f3dc97b81e

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Request jest w porządku, prawidłowo wypełniacie to pole. Mailing przypominający o zmianie wysłaliśmy do wszystkich korzystających z POST /sale/offers, w rzeczywistości nie pada tam zdanie o tym, że aplikacja odbiorcy nie wysyła tego pola. Rozumiem jednak, że tak mogło to zostać odebrane, zatem dziękuję za zgłoszenie - w przyszłości, w przypadku innych koniecznych zmian, dodamy odpowiedni fragment, który doprecyzuje tę kwestie.
