### ISSUE TITLE
Błąd w zwracanej wartości restrictions.min dla zasobu GET /sale/categories/{categoryId}/parameters

### ISSUE THREAD

**Issue by p3le** [allegro/allegro-api#6976]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Zgodnie z dokumentacją znajdującą się [tutaj](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2), wartość elementu zwracanego w `restrictions.min` dla typu `integer` nie może być mniejsza od 0. Dla /sale/categories/112739/parameters i parametru o id 279 (piętro) otrzymujemy `restrictions.min`  -1

Trace-id: 8eeb8ca68414bc80
![screenshot-developer allegro pl-2023 04 19-10_36_33](https://user-images.githubusercontent.com/2972454/233018437-d7396ded-0fe9-4975-bd8d-6a684430eda1.png)

![screenshot-8a6c7c60-8168-4dde-9ec8-90c8efe64e0a-2023 04 19-10_38_22](https://user-images.githubusercontent.com/2972454/233018717-0fe15b23-92ff-415a-a26d-1c572eb87deb.png)

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie. Weryfikujemy ten przypadek i będziemy poprawiać zwracane dane, wrócę z informacją.

**Comment by PrzemyslawLukanowski** [comment]
Ostatecznie - w najbliższym czasie wprowadzimy zmiany w naszej dokumentacji. Istnieją parametry, które mogą posiadać wartość mniejszą niż 0.
