### ISSUE TITLE
Pobieranie informacji o zestawach ofert

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6977]
Pobieram listę ofert za pomocą GET /sale/offers - pytanie w jaki sposób mogę odróżnić, które ze zwróconych ofert są zestawami wielu sztuk? Nie mogę odszukać informacji, która by świadczyła, że dana oferta jest zestawem X sztuk

**Comment by AureliuszBrussy** [comment]
Na liście ofert nie zwracamy takich informacji.

**Comment by mateuszcom** [comment]
A jest jakiś alternatywy sposób na pozyskanie takich informacji?

**Comment by AureliuszBrussy** [comment]
Dokładne informacje zwracamy jedynie przy pobieraniu szczegółów oferty: [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/getProductOffer).
