### ISSUE TITLE
Allegro DHL Odbiór w Punkcie-Problem z nadaniem

### ISSUE THREAD

**Issue by CSVK2022** [allegro/allegro-api#6978]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Request wygląda następująco:

`{:data=>
  {:id=>"a6f27e8f-2032-4573-bf0d-32966dbbfab1",
   :input=>
    {:serviceId=>"07c12933-584e-453d-bee5-60f3f32dfc73",
     :label=>{:fileFormat=>"PDF", :referenceNumber=>"40-de8f-11ed-bfca-cf895e84bb92_BIO"},
     :receiver=>
      {:name=>"XX",
       :company=>nil,
       :address=>{:street=>"xx, 1", :postCode=>xx", :city=>xx", :county=>nil, :countryCode=>"PL"},
       :pointId=>"4514611",
       :email=>"cit79mxgwr+47e8709c0@allegromail.pl",
       :phone=>"xxxx"},
     :pickup=>
      {:name=>"BioWee com",
       :company=>"BioWee.com",
       :address=>{:street=>"xx", :postCode=>"xx", :city=>"xx", :county=>nil, :countryCode=>"PL"},
       :pointId=>nil,
       :email=>"xx",
       :phone=>"xx"},
     :items=>
      [{:dimensions=>
         {:height=>{:value=>"40", :unit=>"CENTIMETER"},
          :width=>{:value=>"18", :unit=>"CENTIMETER"},
          :depth=>{:value=>"13", :unit=>"CENTIMETER"}},
        :weight=>{:value=>"0.24", :unit=>"KILOGRAM"},
        :description=>"ALL_dc3dca40...f895e84bb92_BIO",
        :value=>{:amount=>"29.48", :currency=>"PLN"},
        :type=>"PACKAGE"}],
     :type=>"PACKAGE",
     :additionalServices=>{}}},
 :retry_after=>5,
 :status=>201}`
 
 Response:
 `{:data=>
  {:id=>"a6f27e8f-2032-4573-bf0d-32966dbbfab1",
   :parcelId=>nil,
   :status=>"ERROR",
   :errors=>
    [{:code=>"ERROR",
      :message=>"Processing error",
      :details=>nil,
      :path=>nil,
      :userMessage=>"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}]},
 :status=>200}`

Proszę o zweryfikowanie, nie jesteśmy w stanie namierzyć błędu.

**Comment by AureliuszBrussy** [comment]
API przewoźnika nie zaakceptuje przesyłki o wadze niższej niż 1. W polu `weight.value` przekaż wartość >= 1.

**Comment by CSVK2022** [comment]
Dziękuję!
