### ISSUE TITLE
problem z atrybutami oraz nazwą. 

### ISSUE THREAD

**Issue by bseHlpDsk** [allegro/allegro-api#6979]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource

mimo podania prawidłowej wartości parametru - 248247_883382 - pobrana przed chwilą metodą 
https://api.allegro.pl/sale/categories/318912/parameters

 API zwraca błąd: Parameter value does not exist (248247)

Po drugie - w ofertach, które się udało wystawić, mimo wprowadzenia wartości product->name w oryginale (cyrilica) - w ofertach wyświetla się nazwa zapisana w produkcie. 

poniżej json (z wyciętym adresem obrazu) 

Po trzecie mam sporo przypadków, dotyczących książek w jezyku polskim, gdzie odpowiedź api  brzmi: 
"The provided parameter 'Autor'(223489) value (A. Albano, T. Marin) does not match the existing parameter value (A. Albano, T. Marin)", 
gdzie oba wartości parametru się zgadzają. 

/*
{"productSet": [
   {
  "product": {
    "id": "3c2c4788-34b6-4cc2-a873-7564db7eb567","name": "Гаррі Поттер і прокляте дитя.(Частина 8)" , "parameters": [{
            "id": "74",
            "values": [
                "2022"
            ]
        },{
            "id": "75",
            "valuesIds": [
                "75_2"
            ]
        },{
            "id": "2868",
            "valuesIds": [
                "2868_767635"
            ]
        },{
            "id": "223489",
            "values": [
                "J.K. Rowling"
            ]
        },{
            "id": "223541",
            "valuesIds": [
                "223541_305725"
            ]
        },{
            "id": "223545",
            "values": [
                "Harry Potter i przeklęte dziecko w języku ukraińskim"
            ]
        },{
            "id": "248247",
            "valuesIds": [
                "248247_883382"
            ]
        },{
            "id": "249493",
            "valuesIds": [
                "249493_1645837"
            ]
        } ],"images": ["https://img.com/upload/iblock/91c/91c89ca17169177785e685d627109081.jpg"] 
    ,"category": {

    "id": "318912"

} 

  } 
  ,
      "quantity": {
        "value": 1
      }
    }
  ]
  
  
  ,
  
  "sellingMode": {
    "price": {
      "amount": "61.98",
      "currency": "PLN"
    }
  },
  "stock": {
    "available": 2
  },
  "category": {
    "id": "318912"
  },
  "tax": {
    "percentage": 5.00
  },
  "delivery": {
       
        "handlingTime": "PT96H"
  },"images": ["https://dk-books.com/upload/iblock/91c/91c89ca17169177785e685d627109081.jpg"] , "description": {
            "sections": [{
            "items": [{
                "type": "TEXT",
                "content": "<h1>Гаррі Поттер і прокляте дитя.(Частина 8)</h1>"
            }]
        }, {
            "items": [ {
                "type": "IMAGE",
                "url": "https://dk-books.com/upload/iblock/91c/91c89ca17169177785e685d627109081.jpg"
            }, {
                "type": "TEXT",
                "content": "<ul><li>ISBN: 9786175851128</li><li>Видавець: А-БА-БА-ГА-ЛА-МА-ГА м. Київ </li><li>дата публікації: 2016 </li></ul>"
            }]
        }, {
            "items": [{
                "type": "TEXT",
                "content": "<p>«Гаррі Поттер і прокляте дитя» — сценарій пєси за сюжетом Джоан Ролінґ, написаної у співавторстві з Джоном Тіффані та Джеком Торном, яка з ЗО липня 2016 року з неймовірним успіхом іде в лондонському театрі «Палас». Події в пєсі розгортаються через девятнадцять років після переможної битви за Гоґвортс, якою закінчується сьома, заключна, частина «поттеріани». Бути Гаррі Поттером нелегко, а надто тепер, коли він — працівник Міністерства магії, трудоголік, одружений батько трьох школяриків. Доки Гаррі Поттер бореться зі своїм минулим, яке ніяк не хоче відпускати, його молодшому синові Албусові доводиться миритися з тягарем свого знаменитого роду, — спадком, якого він не обирав. У той час, як минуле зловісно змішалося з майбутнім, батько і син пізнають сумну істину: інколи темрява виходить звідти, де її ніхто не чекав. Це один з найперших перекладів пєси у світі після англомовного видання.</p>"
            }]
        }, 
        {
            "items": [{
                "type": "TEXT",
                "content": "<p>sygnatura 109</p>"
            }]
        }]
    }
 }
*/

**Comment by bseHlpDsk** [comment]
Jeszcze jeden problem znalazłem, 
jak dodać prawidłowo nazwę wydawcy, producenta nie występującego w słowniku. 

Na stronie allegro - wybieramy Inne/Inny i możemy wpisać właściwą wartość. 
W API jeśli podamy: 

/*
{
            "id": "223541",
            "valuesIds": "223541_305725", 
            "values": [
                "Клуб сімейного дозвілля Харків"
            ]
        }
*/
otrzymujemy błąd: Request contains invalid data

Brak podania wartości (czyli poprzestanie na inne) również zwraca błąd.

**Comment by PrzemyslawLukanowski** [comment]
1. Jeśli wskazujesz product po id w polu `productSet.product.id` nie musisz przekazywać nam wszystkich parametrów, pobierzemy je z danych produktu. Spróbuj usunąć sekcję parametrów problem nie powinien wtedy wystąpić. Prześlij nam proszę trace-id dla requestu, gdzie otrzymałeś taki komunikat błędu, zbadamy to.
2. Nie możesz zmienić nazwy istniejącego produktu, możesz jedynie ustawić nazwę swojej oferty - zrobisz to w polu "name", poza obiektem productSet.product.
3. Jak wspomniałem w punkcie pierwszym - jeśli w tym przypadku wskazujesz nam id produktu, nie musisz przekazywać parametrów. Problem może być spowodowany tym, że wartości nie są przekazane dokładnie tak jak w wartości parametru istniejącego produktu. Zwróć uwagę czy są to dwie osobne wartości, np. `"values": ["A. Albano", "T. Marin"]`, czy jedna wartość `"values": ["A. Albano, T. Marin"]`. Jeśli podasz nam trace-id, zweryfikujemy dokładnie, co spowodowało ten błąd.
4. W `valuesIds` przekazujesz string, ten string musi być osadzony w tablicy, tak jak ma to miejsce w `values`.
