### ISSUE TITLE
Logowanie do REST API

### ISSUE THREAD

**Issue by Radziasss** [allegro/allegro-api#698]
Pytanie: podczas logowania do REST API, w odpowiedzi do metody podanej w adresach przekierowań (redirect_uri) dostaję kod "code". Teraz powinienem przy pomocy kodu, w ciągu 10 sek zalogować się podając resztę danych. Skoro wielu użytkowników może się zalogować w - mniej więcej - tym samym czasie, skąd mam wiedzieć, którego z użytkowników dotyczy dany kod, aby na jego podstawie dobrać pozostałe dane potrzebne do logowania?

**Comment by PawelTaberski** [comment]
Po tym jak użytkownik się uwierzytelni i nada uprawnienia aplikacji dostajesz kod, który jest wazny 10 sek. Przy jego pomocy występujesz o access token na danego użytkownika. Tokeny są w technologii JWT, aby sprawdzić do jakiego usera należy wystarczy go rozkodować.

**Comment by Radziasss** [comment]
Jak już dostanę token, to wiem, że mogę go rozkodować i dostanę usera. Pytałem, czy wcześniej - mając tylko kod - jestem w stanie dowiedzieć się, do którego usera należy ten kod, bo muszę na tym etapie znać clientId i secretId tego usera. Czyli nie jest to możliwe?

**Comment by PawelTaberski** [comment]
CielntId i Client Secret nie są dane usera to są dane jakie otrzymujesz przy rejestracji aplikacji. ClientId to taki jakby login aplikacji a Client Secret to takie jakby hasło aplikacji. Korzystając z tych danych możesz wygenerować dla różnych użytkowników różne access_tokeny i z nich korzystając możesz obsługiwać wielu userów (dla każdego osobny access_token).

**Comment by Radziasss** [comment]
Ok, teraz chyba rozumiem. To znaczy, że aplikację i dostęp do REST API rejestruję np. na swoim koncie Allegro. Otrzymuję parę ClientId + Client Secret, którą wykorzystuję wraz z kodem po zalogowaniu dowolnego użytkownika. A na samym końcu mogę rozkodować token i wiem, któremu użytkownikowi przyporządkować te dane i zapisać w bazie. Zgadza się?

Do tej pory myślałem, że dla każdego usera potrzebuję osobną parę ClientId + Client Secret, dlatego coś mi się nie zgadzało. Wystarczy jedna. Jedna by rządzić wszystkimi!

**Comment by PawelTaberski** [comment]
Dokładnie tak wystarczy jedna para dzięki niej wiemy jaka aplikacja zgłasza się do nas z prośbą o token dla danego usera. I są to dane przypisane dla aplikacji nie dla usera. Swoją aplikacją możesz obsługiwać większą liczbę userów niż 1.

**Comment by Radziasss** [comment]
Ok, wszystko jasne, dzięki
