### ISSUE TITLE
PATCH offer not updating offer price - production

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#6980]
Hi, I must be missing something.
I sent a patch request on /sale/product-offers/13515533948
 `{"sellingMode":{"format":"BUY_NOW","price":{"amount":"50.00","currency":"PLN"}}}`
as a response i receive following json (price is chaged to 50
`{
    "name": "Mikrofon karaoke dla dzieci, złoty",
    "productSet": [
        {
            "product": {
                "id": "4e02ef67-a148-4e9c-b645-4b95a4fab48b",
                "publication": {
                    "status": "LISTED"
                },
                "parameters": [
                    {
                        "id": "224017",
                        "name": "Kod producenta",
                        "values": [
                            "4976498886692"
                        ],
                        "valuesIds": null,
                        "rangeValue": null
                    },
                    {
                        "id": "225693",
                        "name": "EAN (GTIN)",
                        "values": [
                            "4976498886692"
                        ],
                        "valuesIds": null,
                        "rangeValue": null
                    },
                    {
                        "id": "227449",
                        "name": "Marka",
                        "values": [
                            "Zaparkorun.cz"
                        ],
                        "valuesIds": [
                            "227449_320973"
                        ],
                        "rangeValue": null
                    },
                    {
                        "id": "237206",
                        "name": "Model",
                        "values": [
                            "WS-858"
                        ],
                        "valuesIds": null,
                        "rangeValue": null
                    }
                ]
            },
            "quantity": {
                "value": 1
            }
        }
    ],
    "parameters": [
        {
            "id": "11323",
            "name": "Stan",
            "values": [
                "Nowy"
            ],
            "valuesIds": [
                "11323_1"
            ],
            "rangeValue": null
        }
    ],
    "images": [
        "https://a.allegroimg.com/original/25b66b/03a36bc74ab4a941a8239542bd84"
    ],
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "0f6fbeab-29c6-4271-8c0e-69d943807296"
        },
        "returnPolicy": {
            "id": "b97051ba-6856-4c65-8b3b-c4469c3e64bf"
        },
        "warranty": null
    },
    "payments": {
        "invoice": "VAT"
    },
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "50.00",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null
    },
    "stock": {
        "available": 69,
        "unit": "UNIT"
    },
    "location": {
        "countryCode": null,
        "province": null,
        "city": null,
        "postCode": null
    },
    "delivery": {
        "shippingRates": {
            "id": "fb8561e2-f1f5-4c32-8476-d9bfdddd82f2"
        },
        "handlingTime": "PT0S",
        "additionalInfo": null,
        "shipmentDate": null
    },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p></p>"
                    }
                ]
            }
        ]
    },
    "external": {
        "id": "5921002"
    },
    "category": {
        "id": "259425"
    },
    "tax": null,
    "taxSettings": null,
    "sizeTable": null,
    "discounts": {
        "wholesalePriceList": null
    },
    "contact": null,
    "fundraisingCampaign": null,
    "messageToSellerSettings": {
        "mode": "HIDDEN"
    },
    "attachments": [],
    "b2b": null,
    "additionalServices": null,
    "compatibilityList": null,
    "additionalMarketplaces": {
        "allegro-cz": {
            "sellingMode": null,
            "publication": {
                "state": "NOT_REQUESTED"
            }
        }
    },
    "id": "13515533948",
    "language": "pl-PL",
    "publication": {
        "status": "INACTIVE",
        "duration": null,
        "endedBy": null,
        "endingAt": null,
        "startingAt": null,
        "republish": false,
        "marketplaces": {
            "base": {
                "id": "allegro-pl"
            },
            "additional": []
        }
    },
    "validation": {
        "errors": [
            {
                "code": "EMPTY_LOCATION",
                "message": "Empty location",
                "details": null,
                "path": "location",
                "userMessage": "Location cannot be empty."
            },
            {
                "code": "ConstraintViolationException.ValidOfferName",
                "message": "From October 1, 2021 a new goods returns policy applies on Allegro. You currently have invalid returns terms attached to your offers. To continue listing, editing, and relisting offers, visit returns terms: https://allegro.pl/moje-allegro/sprzedaz/warunki-zwrotow and update those you are using and those with the [update] marking. Once the returns terms have been updated, listing, editing, and relisting offers will be reinstated. Learn more at https://allegro.pl/dla-sprzedajacych/allegro-zwroty?fbclid=IwAR2yL_NG3t56guS3DABwilyu7M329CqFgwxAocv9buU1T00KG3oqDWIIsYk#zaktualizuj-warunki-zwrotow-w-swoich-ofertach",
                "details": "ConstraintViolationException.ValidOfferName",
                "path": "name",
                "userMessage": "From October 1, 2021 a new goods returns policy applies on Allegro. You currently have invalid returns terms attached to your offers. To continue listing, editing, and relisting offers, visit returns terms: https://allegro.pl/moje-allegro/sprzedaz/warunki-zwrotow and update those you are using and those with the [update] marking. Once the returns terms have been updated, listing, editing, and relisting offers will be reinstated. Learn more at https://allegro.pl/dla-sprzedajacych/allegro-zwroty?fbclid=IwAR2yL_NG3t56guS3DABwilyu7M329CqFgwxAocv9buU1T00KG3oqDWIIsYk#zaktualizuj-warunki-zwrotow-w-swoich-ofertach"
            }
        ],
        "warnings": [
            {
                "code": "ConstraintViolationException.ValidOfferName",
                "message": "Czy wiesz, że dodając metody eksportowe do swoich ofert, możesz trafić do większej grupy klientów? Nie czekaj, dodaj metody eksportowe już teraz i zwiększ swoją sprzedaż. Upewnij się, że produkt posiada wymagane oznakowanie w języku urzędowym kraju, do którego zostanie dostarczony.",
                "details": "ConstraintViolationException.ValidOfferName",
                "path": "name",
                "userMessage": "Czy wiesz, że dodając metody eksportowe do swoich ofert, możesz trafić do większej grupy klientów? Nie czekaj, dodaj metody eksportowe już teraz i zwiększ swoją sprzedaż. Upewnij się, że produkt posiada wymagane oznakowanie w języku urzędowym kraju, do którego zostanie dostarczony."
            }
        ],
        "validatedAt": "2023-04-13T08:16:10.259Z"
    },
    "createdAt": "2023-04-03T13:50:20.000Z",
    "updatedAt": "2023-04-13T08:16:10.260Z"
}`
However user claims, the price on GUI remains 100 and the same value is in responseto get for the same offer
GET /sale/product-offers/13515533948
`{
    "name": "Mikrofon karaoke dla dzieci, złoty",
    "productSet": [
        {
            "product": {
                "id": "4e02ef67-a148-4e9c-b645-4b95a4fab48b",
                "publication": {
                    "status": "LISTED"
                },
                "parameters": [
                    {
                        "id": "224017",
                        "name": "Kod producenta",
                        "values": [
                            "4976498886692"
                        ],
                        "valuesIds": null,
                        "rangeValue": null
                    },
                    {
                        "id": "225693",
                        "name": "EAN (GTIN)",
                        "values": [
                            "4976498886692"
                        ],
                        "valuesIds": null,
                        "rangeValue": null
                    },
                    {
                        "id": "227449",
                        "name": "Marka",
                        "values": [
                            "Zaparkorun.cz"
                        ],
                        "valuesIds": [
                            "227449_320973"
                        ],
                        "rangeValue": null
                    },
                    {
                        "id": "237206",
                        "name": "Model",
                        "values": [
                            "WS-858"
                        ],
                        "valuesIds": null,
                        "rangeValue": null
                    }
                ]
            },
            "quantity": {
                "value": 1
            }
        }
    ],
    "parameters": [
        {
            "id": "11323",
            "name": "Stan",
            "values": [
                "Nowy"
            ],
            "valuesIds": [
                "11323_1"
            ],
            "rangeValue": null
        }
    ],
    "images": [
        "https://a.allegroimg.com/original/25b66b/03a36bc74ab4a941a8239542bd84"
    ],
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "0f6fbeab-29c6-4271-8c0e-69d943807296"
        },
        "returnPolicy": {
            "id": "b97051ba-6856-4c65-8b3b-c4469c3e64bf"
        },
        "warranty": null
    },
    "payments": {
        "invoice": "VAT"
    },
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "100.00",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null
    },
    "stock": {
        "available": 69,
        "unit": "UNIT"
    },
    "location": null,
    "delivery": {
        "shippingRates": {
            "id": "fb8561e2-f1f5-4c32-8476-d9bfdddd82f2"
        },
        "handlingTime": "PT0S",
        "additionalInfo": null,
        "shipmentDate": null
    },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p></p>"
                    }
                ]
            }
        ]
    },
    "external": {
        "id": "5921002"
    },
    "category": {
        "id": "259425"
    },
    "tax": null,
    "taxSettings": null,
    "sizeTable": null,
    "discounts": {
        "wholesalePriceList": null
    },
    "contact": null,
    "fundraisingCampaign": null,
    "messageToSellerSettings": {
        "mode": "HIDDEN"
    },
    "attachments": [],
    "b2b": null,
    "additionalServices": null,
    "compatibilityList": null,
    "additionalMarketplaces": {
        "allegro-cz": {
            "sellingMode": null,
            "publication": {
                "state": "NOT_REQUESTED"
            }
        }
    },
    "id": "13515533948",
    "language": "pl-PL",
    "publication": {
        "status": "INACTIVE",
        "duration": null,
        "endedBy": null,
        "endingAt": null,
        "startingAt": null,
        "republish": false,
        "marketplaces": {
            "base": {
                "id": "allegro-pl"
            },
            "additional": []
        }
    },
    "validation": {
        "errors": [
            {
                "code": "EMPTY_LOCATION",
                "message": "Empty location",
                "details": null,
                "path": "location",
                "userMessage": "Location cannot be empty."
            },
            {
                "code": "ConstraintViolationException.ValidOfferName",
                "message": "From October 1, 2021 a new goods returns policy applies on Allegro. You currently have invalid returns terms attached to your offers. To continue listing, editing, and relisting offers, visit returns terms: https://allegro.pl/moje-allegro/sprzedaz/warunki-zwrotow and update those you are using and those with the [update] marking. Once the returns terms have been updated, listing, editing, and relisting offers will be reinstated. Learn more at https://allegro.pl/dla-sprzedajacych/allegro-zwroty?fbclid=IwAR2yL_NG3t56guS3DABwilyu7M329CqFgwxAocv9buU1T00KG3oqDWIIsYk#zaktualizuj-warunki-zwrotow-w-swoich-ofertach",
                "details": "ConstraintViolationException.ValidOfferName",
                "path": "name",
                "userMessage": "From October 1, 2021 a new goods returns policy applies on Allegro. You currently have invalid returns terms attached to your offers. To continue listing, editing, and relisting offers, visit returns terms: https://allegro.pl/moje-allegro/sprzedaz/warunki-zwrotow and update those you are using and those with the [update] marking. Once the returns terms have been updated, listing, editing, and relisting offers will be reinstated. Learn more at https://allegro.pl/dla-sprzedajacych/allegro-zwroty?fbclid=IwAR2yL_NG3t56guS3DABwilyu7M329CqFgwxAocv9buU1T00KG3oqDWIIsYk#zaktualizuj-warunki-zwrotow-w-swoich-ofertach"
            }
        ],
        "warnings": [],
        "validatedAt": "2023-04-13T08:16:10.259Z"
    },
    "createdAt": "2023-04-03T13:50:20.000Z",
    "updatedAt": "2023-04-13T08:16:10.260Z"
}`

**Comment by PrzemyslawLukanowski** [comment]
Hello, the reason of the problem is returned in the `validation.errors` section. To be more specific, the following issue is blicking the price change:

`"message": "From October 1, 2021 a new goods returns policy applies on Allegro. You currently have invalid returns terms attached to your offers. To continue listing, editing, and relisting offers, visit returns terms: https://allegro.pl/moje-allegro/sprzedaz/warunki-zwrotow and update those you are using and those with the [update] marking. Once the returns terms have been updated, listing, editing, and relisting offers will be reinstated. Learn more at https://allegro.pl/dla-sprzedajacych/allegro-zwroty?fbclid=IwAR2yL_NG3t56guS3DABwilyu7M329CqFgwxAocv9buU1T00KG3oqDWIIsYk#zaktualizuj-warunki-zwrotow-w-swoich-ofertach"`

I'm verifying with our team, why in the response we have returned the changed price. I will let you know when I have more details.

**Comment by ZajdaBear** [comment]
Thanks for quick response.
My issue is, I did not expect anything to be wrong, since the response code was 200
I have also noticed the other error. 
```
{
                "code": "EMPTY_LOCATION",
                "message": "Empty location",
                "details": null,
                "path": "location",
                "userMessage": "Location cannot be empty."
            }
```

I am not sure, if this prevents me from updating offer as well?
Is there a general rule, that will tell me, the update was successfull?

Thanks

**Comment by PrzemyslawLukanowski** [comment]
`My issue is, I did not expect anything to be wrong, since the response code was 200`

For the offer drafts, we will return a 200 status code, but the list of errors that prevents you from offer activation will be returned in the validation section. I'm still verifying this case because the price either should be changed despite the error (because this is a draft of the offer, it's not in ACTIVE status) or it shouldn't - and then we shouldn't return the changed price in the response. 

The second error doesn't prevent you from making changes (when the offer is in the INACTIVE status), but only from activating the offer.

**Comment by PrzemyslawLukanowski** [comment]
In some cases we can return 202 status Accepted, please check[ how this scenario should be handled](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#integration-with-an-asynchronous-api).

**Comment by ZajdaBear** [comment]
_For the offer drafts, we will return a 200 status code, but the list of errors that prevents you from offer activation will be returned in the validation section_

_The second error doesn't prevent you from making changes (when the offer is in the INACTIVE status), but only from activating the offer._

I am not sure I udnerstand correctly? Either "EMPTY_LOCATION" does prevent me from making the changes as well, according to your first statement, or it does not according to your other statement

Also from your documentation:

_200 OK - when the request relates to modification of the offer's attributes that do not involve long-running operations. We will implement the changes immediately,_

This is not true, since I have received 200 and changes were not implemented. 

Business is reviewing return policy. I will push offers one more time including location, but I am afraid, that in the future, I can receive 200 - ok status, but the change will not be done on your side, which is straight scary scenario and we probaly need to implement the check, that data we sent you and you responded 200 - ok to were actually done. 

Thanks for the help so far

**Comment by PrzemyslawLukanowski** [comment]
Sorry for not making it clear enough. "EMPTY_LOCATION" is not preventing you from making changes when an offer is in INACTIVE status. Based on our internal logs, the specific reason why we didn't change the offer price is the `" (...)You currently have invalid returns terms attached to your offers..."`. 

> This is not true, since I have received 200 and changes were not implemented.

You're right, that's why we investigating the inconsistent behavior from our side. Our team, which is responsible for this service, needs to check it in detail. I will return with more details as soon as I receive the info.

**Comment by ZajdaBear** [comment]
Any update on this please?

**Comment by PrzemyslawLukanowski** [comment]
Unfortunately no, our team carried out pre-verification, but this task still waits for a fix implementation.
