### ISSUE TITLE
Sandbox - nie działa ładowanie zdjęć

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#6982]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Podczas próby dodania zdjęcia w formularzu dodawania oferty otrzymuję błąd:
"Nie udało się dodać zdjęcia - Wystapił błąd podczas dodawania obrazka."
```
500
{"errors":[{"code":"InternalServerError","message":"Internal server error","details":null,"path":null,"userMessage":"Wewnętrzny błąd systemu."}]}
```

Analogicznie przez API
```
POST https://upload.allegro.pl.allegrosandbox.pl/sale/images"
{
    +"code": "INTERNAL_SERVER_ERROR"
    +"message": "Internal server error."
    +"details": null
    +"path": null
    +"userMessage": "Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."
    }
```

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam problemy po naszej stronie. Wrócę z informacją, gdy problem zostanie zażegnany. Przepraszam za niedogodności.

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować.
