### ISSUE TITLE
problemy przy wsyatwianiu ofert

### ISSUE THREAD

**Issue by muzyk24** [allegro/allegro-api#6983]
Podczas wystawiania oferty leci błąd **Missing mandatory parameters: Color.**

Jak na endpoincie POST /sale/offers rozwiązać ten problem? 
Na nowy przejdziemy prawdopodobnie za jakieś 2/3 miesiące, zależy nam na rozwiązaniu tego tymczasowo.

**Comment by AureliuszBrussy** [comment]
Czy możesz opisać problem szerzej? Z jakiego powodu masz trudność z uzupełnieniem parametru kolor? Prosiłbym też o podesłanie trace-id wywołania (znajdziesz go w nagłówku response'a).

**Comment by muzyk24** [comment]
> POST   https://api.allegro.pl.allegrosandbox.pl/sale/offers requestBody={"afterSalesServices":{"impliedWarranty":{"id":"9e3e2cef-b2cc-4971-941a-249111e4a4c2"},"returnPolicy":{"id":"0c667bcc-09c5-433e-b9a1-1e66ef233405"},"warranty":{"id":"38964799-6596-4bb3-847e-781925b46240"}},"category":{"id":"76084"},"delivery":{"shippingRates":{"id":"44e79fb3-0c23-45d2-98f1-825d23633468"},"handlingTime":"PT24H"},"external":{"id":"stocksell_308943042"},"images":[{"url":"https://a.allegroimg.allegrosandbox.pl/original/113db0/a55af97e4c3a8eae6c81470fcbc5"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/119769/0e5000bf40f793057bdbacefa37b"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/113f13/f78b4c2d41c790e496259cbee6d4"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/110e26/2e7a85f7486e8b8dddfa150905f1"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/11e559/07ede963415c839a3f8c451da268"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/11b8cb/a9723369469b97e6498324a565b7"}],"location":{"city":"Skawina","countryCode":"PL","postCode":"32-050","province":"MALOPOLSKIE"},"parameters":[{"id":"11323","valuesIds":["11323_1"]},{"id":"202329","valuesIds":["202329_32"]},{"id":"202465","valuesIds":["202465_212089"]},{"id":"3786","valuesIds":["3786_371597"]},{"id":"225693","values":["7325942826444"]},{"id":"54","valuesIds":["54_3"]},{"id":"15851","valuesIds":["15851_1"]},{"id":"451","valuesIds":["451_1","451_256"]},{"id":"201025","valuesIds":["201025_2509"]},{"id":"201017","valuesIds":["201017_2337"]},{"id":"3766","valuesIds":["3766_3"]},{"id":"201089","values":["35"]},{"id":"60","valuesIds":["60_2"]}],"name":"test niebezpieczny S YAA","payments":{"invoice":"VAT"},"publication":{"startingAt":"2023-04-22T20:48:26.000Z","republish":false},"sellingMode":{"format":"BUY_NOW","price":{"amount":55.99,"currency":"PLN"}},"stock":{"available":1,"sold":0,"unit":"UNIT"},"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003ch2\u003etest niebezpieczny\u003c/h2\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/113db0/a55af97e4c3a8eae6c81470fcbc5"},{"type":"TEXT","content":"\u003ch2\u003eOpis Produktu\u003c/h2\u003e\u003cul\u003e\u003cli\u003e\u003cb\u003eMarka\u003c/b\u003e NA-KD\u003c/li\u003e\u003cli\u003e\u003cb\u003eKolor\u003c/b\u003e ZIELONY, BIAŁY \u003c/li\u003e\u003cli\u003e\u003cb\u003eSkład\u003c/b\u003e 100% wiskoza      \u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka papierowa\u003c/b\u003e Tak\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka wewnętrzna\u003c/b\u003e \tTak\u003c/li\u003e\u003cli\u003e\u003cb\u003eRozmiar\u003c/b\u003e S\u003c/li\u003e\u003cli\u003e\u003cb\u003eCena katalogowa\u003c/b\u003e 141,99 zł\u003c/li\u003e\u003c/ul\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/110e26/2e7a85f7486e8b8dddfa150905f1"},{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/113f13/f78b4c2d41c790e496259cbee6d4"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/119769/0e5000bf40f793057bdbacefa37b"},{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/11b8cb/a9723369469b97e6498324a565b7"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/11e559/07ede963415c839a3f8c451da268"}]}]}} responseBody={"id":"7702801887","name":"test niebezpieczny S YAA","category":{"id":"76084"},"product":null,"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"202329","valuesIds":["202329_32"],"values":[],"rangeValue":null},{"id":"202465","valuesIds":["202465_212089"],"values":[],"rangeValue":null},{"id":"3786","valuesIds":["3786_371597"],"values":[],"rangeValue":null},{"id":"225693","valuesIds":[],"values":["7325942826444"],"rangeValue":null},{"id":"54","valuesIds":["54_3"],"values":[],"rangeValue":null},{"id":"15851","valuesIds":["15851_1"],"values":[],"rangeValue":null},{"id":"451","valuesIds":["451_1","451_256"],"values":[],"rangeValue":null},{"id":"201025","valuesIds":["201025_2509"],"values":[],"rangeValue":null},{"id":"201017","valuesIds":["201017_2337"],"values":[],"rangeValue":null},{"id":"3766","valuesIds":["3766_3"],"values":[],"rangeValue":null},{"id":"201089","valuesIds":[],"values":["35"],"rangeValue":null},{"id":"60","valuesIds":["60_2"],"values":[],"rangeValue":null}],"customParameters":null,"description":{"sections":[{"items":[{"type":"TEXT","content":"<h2>test niebezpieczny</h2>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/113db0/a55af97e4c3a8eae6c81470fcbc5"},{"type":"TEXT","content":"<h2>Opis Produktu</h2><ul><li><b>Marka</b> NA-KD</li><li><b>Kolor</b> ZIELONY, BIAŁY </li><li><b>Skład</b> 100% wiskoza      </li><li><b>Metka papierowa</b> Tak</li><li><b>Metka wewnętrzna</b> \tTak</li><li><b>Rozmiar</b> S</li><li><b>Cena katalogowa</b> 141,99 zł</li></ul>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/110e26/2e7a85f7486e8b8dddfa150905f1"},{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/113f13/f78b4c2d41c790e496259cbee6d4"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/119769/0e5000bf40f793057bdbacefa37b"},{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/11b8cb/a9723369469b97e6498324a565b7"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/11e559/07ede963415c839a3f8c451da268"}]}]},"compatibilityList":null,"tecdocSpecification":null,"images":[{"url":"https://a.allegroimg.allegrosandbox.pl/original/113db0/a55af97e4c3a8eae6c81470fcbc5"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/119769/0e5000bf40f793057bdbacefa37b"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/113f13/f78b4c2d41c790e496259cbee6d4"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/110e26/2e7a85f7486e8b8dddfa150905f1"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/11e559/07ede963415c839a3f8c451da268"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/11b8cb/a9723369469b97e6498324a565b7"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"55.99","currency":"PLN"},"startingPrice":null,"minimalPrice":null,"netPrice":null},"tax":null,"stock":{"available":1,"unit":"UNIT"},"publication":{"duration":null,"status":"INACTIVE","startingAt":"2023-04-22T20:48:00.000Z","endingAt":null,"endedBy":null,"republish":false,"marketplaces":{"base":{"id":"allegro-pl"},"additional":[]}},"delivery":{"shippingRates":{"id":"44e79fb3-0c23-45d2-98f1-825d23633468"},"handlingTime":"PT24H","additionalInfo":null,"shipmentDate":null},"payments":{"invoice":"VAT"},"discounts":null,"afterSalesServices":{"impliedWarranty":{"id":"9e3e2cef-b2cc-4971-941a-249111e4a4c2"},"returnPolicy":{"id":"0c667bcc-09c5-433e-b9a1-1e66ef233405"},"warranty":{"id":"38964799-6596-4bb3-847e-781925b46240"}},"additionalServices":null,"sizeTable":null,"fundraisingCampaign":null,"promotion":{"emphasized":false,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"MALOPOLSKIE","city":"Skawina","postCode":"32-050"},"external":{"id":"stocksell_308943042"},"attachments":[],"contact":null,"validation":{"errors":[{"code":"VALIDATION_ERROR","message":"Parameters (451) are not expected","details":"","path":"parameters","userMessage":"Invalid parameters (451) for selected category."},{"code":"VALIDATION_ERROR","message":"Missing required parameters: 249512","details":"","path":"parameters","userMessage":"Missing mandatory parameters: Color."},{"code":"VALIDATION_ERROR","message":"You cannot list an offer without a linked product in this category. Select a product from the catalog or create a new one and link it with your offer.","details":"","path":"null","userMessage":"You cannot list an offer without a linked product in this category. Select a product from the catalog or create a new one and link it with your offer."}],"warnings":[],"validatedAt":"2023-04-20T09:46:33.548Z"},"b2b":{"buyableOnlyByBusiness":false},"messageToSellerSettings":null,"createdAt":"2023-04-20T09:46:33.000Z","updatedAt":"2023-04-20T09:46:33.606Z","language":"pl-PL","additionalMarketplaces":{"allegro-cz":{"sellingMode":null,"publication":{"state":"NOT_REQUESTED"}}},"taxSettings":null} trace-id=[af9fe7695aa01111]

**Comment by AureliuszBrussy** [comment]
Błędy zwrócone w walidacji (`validation.error`) w zasadzie tłumaczą przyczynę problemu. W kategorii 76084 parametr Kolor (249512) jest parametrem wymaganym (`"required": true`, sprawdzisz to dzięki [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2)). Nie wysyłasz go w swoim requeście. 

Z kolei przekazujesz w żądaniu parametr, który w ogóle nie występuje w tej kategorii - 451. 

Dodatkowo wymagamy, aby oferta była powiązana z produktem. Powinieneś wskazać produkt z naszego Katalogu Produktów w polu `product.id`.

**Comment by muzyk24** [comment]
dobra dziękuję, widocznie tego zabrakło :)
