### ISSUE TITLE
Sprawdzanie czy zdjęcie istnieje

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#6984]
W skrypcie sprawdzam za pomocą curl czy zdjęcie istnieje, w odpowiedzi dostaję kod 200 ale gdy ten sam url wywołam w przeglądarce to zwraca komunikat Object not found.

Wywołanie curl:
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      curl_setopt($ch, CURLOPT_HEADER, 1);
      curl_setopt($ch, CURLOPT_NOBODY, 1);
      curl_setopt($ch, CURLOPT_URL, $url);
      curl_setopt($ch, CURLOPT_FRESH_CONNECT, TRUE);
      curl_setopt($ch, CURLOPT_HTTPHEADER, array("Cache-Control: no-cache, must-revalidate"));

Odpowiedź:
HTTP/2 200
date: Thu, 20 Apr 2023 09:45:08 GMT
content-type: image/jpeg
content-length: 768397
access-control-allow-origin: *
etag: "73418d1c4871edbf76d39bcabb76427c"
cache-control: public, max-age=31536000, immutable
x-content-type-options: nosniff
accept-ch: Width
accept-ch-lifetime: 86400
vary: Accept
timing-allow-origin: https://allegro.pl, http://allegro.pl
strict-transport-security: max-age=15552000

Zdaje się że poprzez curl dostaje z cach-owany obraz a z przeglądarki bieżący

**Comment by AureliuszBrussy** [comment]
Czy mógłbyś podać przykładowy url takiego zdjęcia? Zweryfikujemy to.

**Comment by SlawomirMizerski** [comment]
https://a.allegroimg.com/original/11eeab/1e57fe8c46a6a9250f82dfe16533

**Comment by AureliuszBrussy** [comment]
Powtórzyłem dokładnie taki sam curl i w odpowiedzi otrzymałem status HTTP/2 404.
