### ISSUE TITLE
Nowy kanał sprzedaży

### ISSUE THREAD

**Issue by PiotrPioro** [allegro/allegro-api#6985]
Czytałem to co jest na tej stronie https://developer.allegro.pl/tutorials/wystawianie-i-zarzadzanie-oferta-w-serwisach-zagranicznych-wwzjP4M8gTZ i chcę się tylko upewnić, jak nic nie zmienię u siebie w api to dalej wszystko będzie działało po staremu? To jest dodatkowa opcja a nie konieczność?

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, wszystko będzie działało po staremu.

**Comment by PiotrPioro** [comment]
Dziękuję
