### ISSUE TITLE
Tworzenie oferty

### ISSUE THREAD

**Issue by barczykartur** [allegro/allegro-api#6986]
Hej, mam problem. Próbuję utworzyć ofertę z parametrami otrzymanymi z endpointa /sale/categories/147642/product-parameters/.
Według odpowiedzi są tam cztery wymagane parametry: Marka, Model, Maksymalna moc oraz kod producenta. Mój request wygląda następująco: 
`{
  "productSet": [
    {
      "product": {
        "name": "Tani Basen Podgrzewacz",
        "category": {
          "id": "147642"
        },
        "parameters": [
          {
            "id": "237206",
            "values": [
              "Model"
            ]
          },
          {
            "id": "128608",
            "valuesIds": [
              "128608_16"
            ],
            "values": [ "Nazwa brakującej marki" ]
          },
          {
            "id": "24908",
            "values": [
              123.4
            ]
          },
          {
            "id": "224017",
            "values": [
              "Kod producenta"
            ]
          }
        ],
        "images": [
          "https://fastly.picsum.photos/id/724/200/300.jpg?hmac=MwcEnqDDOgKg6U3WYPytBPH_jurNEK2_2kcknpgP6wg"
        ]
      },
      "quantity": {}
    }
  ],
  "sellingMode": {
    "price": {
      "currency": "PLN",
      "amount": "62.7"
    }
  },
  "stock": {
    "available": 111
  },
  "afterSalesServices": {
    "returnPolicy": {
      "id": "fd42e7c5-e203-4b6a-bf9a-ec043173f046"
    }
  }
}`

Otrzymuję następujący błąd: 

`{
  "errors": [
    {
      "code": "ProductValidationException",
      "message": "Unable to create product without proper values in all required parameters: [Marka] in category: 147642",
      "details": null,
      "path": "productSet[0].product",
      "userMessage": "Nie można stworzyć produktu bez podania poprawnych wartości wszystkich parametrów wymaganych: [Marka]"
    }
  ]
`

Podałem markę w requeście. Czy robię coś nie tak? Jeżeli tak to bardzo bym prosił o wyjaśnienie. Jeżeli usunę parametr marka z zapytania to jest zwracany następujący błąd, który sugeruje, że istnieje więcej parametrów (2 parametry) o nazwie marka:
`{
  "errors": [
    {
      "code": "ProductValidationException",
      "message": "Unable to create product without proper values in all required parameters: [Marka, Marka] in category: 147642",
      "details": null,
      "path": "productSet[0].product",
      "userMessage": "Nie można stworzyć produktu bez podania poprawnych wartości wszystkich parametrów wymaganych: [Marka, Marka]"
    }
  ]
}`

Z góry dziękuję za odpowiedź, pozdrawiam :)

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować.
