### ISSUE TITLE
Description not considering the tags and writing them as a simple text

### ISSUE THREAD

**Issue by tufail-cedcommerce** [allegro/allegro-api#6987]
Hello there,

I'm trying to upload an offer and this is the description that I sent.

"description": {
		"sections": [
			{
				"items": [
					{
						"type": "TEXT",
						"content": "
`<ul><li>Dres męski to doskonały wybór dla mężczyzn kochających sport i jazdę na rowerze. To także idealny wybór na wycieczkę na wieś lub zakupy do sklepu. W dresie każdy mężczyzna będzie czuł się swobodnie i komfortowo zarówno w domu, jak i podczas uprawiania sportu.</li><li>Skład: 65% bawełna, 35% poliester.Model: 191cm 88kg noszący rozmiar L.</li><li>Pielęgnacja: Pranie w pralce w temperaturze 30°C.</li><li>Wysoka jakość, wykonana w Turcji.</li></ul>`

"
					}
				]
			}
		]
	},

But the thing is that this description is considered as a plain text and not as an unordered list.

Please let me know what changes I need to do from my end or is there something I need to know about the API.

Thank you.

**Comment by PrzemyslawLukanowski** [comment]
Could you please send me a sample trace-id connected with this issue? I've checked one of the offers that include this kind of text (13513xxx001) and this is the structure we received from you:

`"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>&lt;p&gt;Dres mu0119ski to doskonau0142y wybu00f3r dla mu0119u017cczyzn kochaju0105cych sport i jazdu0119 na rowerze. To taku017ce idealny wybu00f3r na wycieczku0119 na wieu015b lub zakupy do sklepu. W dresie kau017cdy mu0119u017cczyzna bu0119dzie czuu0142 siu0119 swobodnie i komfortowo zaru00f3wno w domu, jak i podczas uprawiania sportu.&lt;br&gt;&lt;/p&gt;&lt;p&gt;Sku0142ad: 65% baweu0142na, 35% poliester.&lt;br&gt;Model: 191cm 88kg noszu0105cy rozmiar L.&lt;/p&gt;&lt;p&gt;Pielu0119gnacja: Pranie w pralce w temperaturze 30u00b0C.&lt;br&gt;&lt;/p&gt;&lt;p&gt;Wysoka jakou015bu0107, wykonana w Turcji.&lt;/p&gt;</p>"}]}]}`

It doesn't include <ul> and <li> tags.

**Comment by tufail-cedcommerce** [comment]
From where I can get the sample trace-id? Or it's better if you can let me know the correction(s) that I need to do.

**Comment by PrzemyslawLukanowski** [comment]
Trace id should be returned in the response headers. The proper structure should be as follows, it's the same as you pasted in the beginning:

`"description":{"sections":[{"items":[{"type":"TEXT","content":"<ul><li>Dres męski to doskonały wybór dla mężczyzn kochających sport i jazdę na rowerze. To także idealny wybór na wycieczkę na wieś lub zakupy do sklepu. W dresie każdy mężczyzna będzie czuł się swobodnie i komfortowo zarówno w domu, jak i podczas uprawiania sportu.</li><li>Skład: 65% bawełna, 35% poliester.Model: 191cm 88kg noszący rozmiar L.</li><li>Pielęgnacja: Pranie w pralce w temperaturze 30°C.</li><li>Wysoka jakość, wykonana w Turcji.</li></ul>"}]}]}`

It seems that the characters such as "<" and ">" are transferred to HTML entities on your side.

**Comment by tufail-cedcommerce** [comment]
Okay let me try your way.
