### ISSUE TITLE
Grafiki w allegro Object not found

### ISSUE THREAD

**Issue by AZAGroup90** [allegro/allegro-api#6988]
Witam,
Czy jest jakiś sposób na api aby sprawdzić czy dany URL (Grafika) jest prawidłowym zdjęciem allegro
https://a.allegroimg.com/original/111f46/8539e7a24abfb6a5489f7c4a4c5a
problem jest taki, że jak dodaje propozycje to wywala mi ze nie może dodać obrazków, bo nie istnieją przy tworzeniu produktyzacji.

Mam np. obrazek
https://media.aza.io/2000/2000/80/3100002266262_2.jpg
który niby jest wrzucony na allegro pod adresem
https://a.allegroimg.com/original/1158b9/e75ad4344a9a810a7fa0b7f74733
ale mi go nie otwiera

![999](https://user-images.githubusercontent.com/128464837/233556612-d204a3fb-58e3-4911-8fca-ad1c85b98229.png)

**Comment by PrzemyslawLukanowski** [comment]
Zdjęcie musisz wykorzystać do 4 godzin po tym, gdy skorzystałeś z POST /sale/images. Możesz sugerować się czasem, który zwracamy w polu `expiresAt`. Nie udało mi się powtórzyć tego przypadku, zdjęcie prawidłowo pobiera się po wrzuceniu. Czy w tym przypadku próbowałeś użyć zdjęcia przed upływem 4 godzin czy faktycznie mógł minąć ten czas?
