### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by MKI-Miro** [allegro/allegro-api#6989]
Hi

When I try to update offer I get error that I should provide at least one image. But Why?

Missing image for offer: 13439788728 3663384324741 Grafika You have to add at least 1 image. null
Missing image for offer: 13439788560 3663384300073 Grafika You have to add at least 1 image. null
Missing image for offer: 13439788457 3663384300097 Grafika You have to add at least 1 image. null
Missing image for offer: 13439788153 3663384300448 Grafika You have to add at least 1 image. null
Missing image for offer: 13439787877 3663384323768 Grafika You have to add at least 1 image. null
Missing image for offer: 13439787600 3663384300776 Grafika You have to add at least 1 image. null
Missing image for offer: 13439787456 3663384300639 Grafika You have to add at least 1 image. null
Missing image for offer: 13439787013 3663384323973 Grafika You have to add at least 1 image. null
Missing image for offer: 13439786761 3663384300158 Grafika You have to add at least 1 image. null
Missing image for offer: 13439786616 3663384324772 Grafika You have to add at least 1 image. null
Missing image for offer: 13439786522 3663384300011 Grafika You have to add at least 1 image. null
Missing image for offer: 13439786321 3663384300103 Grafika You have to add at least 1 image. null
Missing image for offer: 13439782905 4001689294304 Heye You have to add at least 1 image. null
Missing image for offer: 13439780996 628136651585 Eurographics You have to add at least 1 image. null
Missing image for offer: 13439778896 628136656207 Eurographics You have to add at least 1 image. null
Missing image for offer: 13439777827 628136354257 Eurographics You have to add at least 1 image. null
Missing image for offer: 13439761558 5947502876724 D-Toys You have to add at least 1 image. null
Missing image for offer: 13439761536 5947502876717 D-Toys You have to add at least 1 image. null
Missing image for offer: 13439761504 5947502876700 D-Toys You have to add at least 1 image. null
Missing image for offer: 13438898899 796780677043 Sunsout You have to add at least 1 image. null
Missing image for offer: 13438886711 8412668191983 Educa You have to add at least 1 image. null
Missing image for offer: 13438886078 8412668188785 Educa You have to add at least 1 image. null
Missing image for offer: 13438868075 8005125395651 Clementoni You have to add at least 1 image. null
Missing image for offer: 13389980578 3663384705601 BlueBird You have to add at least 1 image. null
Missing image for offer: 13389959381 3663384600081 BlueBird You have to add at least 1 image. null
Missing image for offer: 13389958516 3663384600951 BlueBird You have to add at least 1 image. null
Missing image for offer: 13389954160 3663384704406 BlueBird You have to add at least 1 image. null
Missing image for offer: 13389947000 3663384702785 BlueBird You have to add at least 1 image. null
Missing image for offer: 13389785318 3663384701726 BlueBird You have to add at least 1 image. null
Missing image for offer: 13389785242 3663384705083 BlueBird You have to add at least 1 image. null
Missing image for offer: 13389784361 3663384701290 BlueBird You have to add at least 1 image. null
Missing image for offer: 13389778106 8698543111158 AnaTolian You have to add at least 1 image. null
Missing image for offer: 13389758424 8698543110878 AnaTolian You have to add at least 1 image. null
Missing image for offer: 13389752718 8698543136007 AnaTolian You have to add at least 1 image. null
Missing image for offer: 13385412297 5904438104390 Castorland You have to add at least 1 image. null

**Comment by PrzemyslawLukanowski** [comment]
This is a requirement we introduced on March, 20. You can find more information in [our news](https://github.com/allegro/allegro-api/issues/6718).

**Comment by MKI-Miro** [comment]
But I am not creating new offer. I am only updating offer price.

**Comment by PrzemyslawLukanowski** [comment]
It also applies to updating offers:

"(...)we will require each offer to have a minimum of 1 photo. When the seller tries to list an offer **or make changes**."

**Comment by MKI-Miro** [comment]
Ok

So I tried:

`{
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": 47.04,
      "currency": "PLN"
    },
    "startingPrice": null,
    "minimalPrice": null,
    "netPrice": null
  },
  "images": [
    {
      "url": "https://puzzlemania-154aa.kxcdn.com/products/2018/puzzle-grafika-1000-pieces-ortega-spiders-soul-aracne.jpg"
    }
  ]
}`

but I get

`{
  "errors": [
    {
      "code": "JsonMappingException",
      "message": "Message is not readable.",
      "details": null,
      "path": "images[0]",
      "userMessage": "Request contains invalid data. Contact the application author."
    }
  ]
}`

**Comment by PrzemyslawLukanowski** [comment]
Please remove the "url" field. According to the documentation "images", it's an array of strings:

<img width="174" alt="Zrzut ekranu 2023-04-21 o 12 35 43" src="https://user-images.githubusercontent.com/51473661/233615411-f11716c0-7b49-49ad-bdfa-adc28b1391f9.png">

**Comment by MKI-Miro** [comment]
thank you it works
