### ISSUE TITLE
Sandbox i błędny format ID kategorii

### ISSUE THREAD

**Issue by GyniO** [allegro/allegro-api#699]
Pobieram główne kategorie z sandboxa i dostaje różne formy ID kategorii typu:
"ea5b98dd-4b6f-4bd0-8c80-22c2629132d0"

Czy jest możliwość zaciągnięcia większej ilości zagłębień? Na webapi pobierało się całą listę, przy jednym requeście, a tutaj trzeba ich trochę zrobić.

`
{"categories":[{"id":"5","name":"Dom i Ogród","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false}},{"id":"11763","name":"Dziecko","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false}},{"id":"42540aec-367a-4e5e-b411-17c09b08e41f","name":"Elektronika","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":false,"advertisement":false,"advertisementPriceOptional":false}},{"id":"4bd97d96-f0ff-46cb-a52c-2992bd972bb1","name":"Firma","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":false,"advertisement":false,"advertisementPriceOptional":false}},{"id":"257900","name":"Kody i doładowania","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":false,"advertisement":false,"advertisementPriceOptional":false}},{"id":"a408e75a-cede-4587-8526-54e9be600d9f","name":"Kolekcje i sztuka","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":false,"advertisement":false,"advertisementPriceOptional":false}},{"id":"38d588fd-7e9c-4c42-a4ae-6831775eca45","name":"Kultura i rozrywka","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":false,"advertisement":false,"advertisementPriceOptional":false}},{"id":"ea5b98dd-4b6f-4bd0-8c80-22c2629132d0","name":"Moda","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":false,"advertisement":false,"advertisementPriceOptional":false}},{"id":"3","name":"Motoryzacja","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":false,"advertisement":false,"advertisementPriceOptional":false}},{"id":"258833","name":"Ogłoszenia i usługi","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false}},{"id":"3919","name":"Sport i turystyka","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false}},{"id":"258832","name":"Supermarket","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false}},{"id":"1429","name":"Uroda","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false}},{"id":"121882","name":"Zdrowie","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false}}]}`

**Comment by PawelTaberski** [comment]
Tak zgadza się nie wszystkie kategorie mają jeszcze numery w formacie UUID, nie da się jednym requestem pobrać należy po kolej przechodzić do liścia. Dzięki czemu wyszukiwanie jest szybsze i przy każdej zmianie w kategoriach nie trzeba na nowo pobierać całego drzewa kategorii.

**Comment by GyniO** [comment]
Może dla Was jest szybsze przy pojedynczym wystawianiu produktu, ale w momencie gdy wdrażam API na sklepie gdzie jest 10tyś produktów i klient chce przypisać do każdego produktu jakąś konfigurację w tym kategorie to dla niego łatwiej wybierać to z selekta z wyszukiwarką po tekście niż od klikanie 10 poziomów kategorii. 
Dlatego pobieranie na bieżąco listy kategorii i czekać na requesty to strata czasu. Łatwiej pobrać sobie wszystkie kategorie i mu wypuścić selecta ajaxowego gdzie będzie mu zawężać listę. Obecny sposób wystawiania produktów na allegro według mnie jest przyjazne dla zwykłych użytkowników, a tutaj powinno to być robione globalniej.

Kiedy można liczyć, że będą to intowe IDki ? Na tą chwilę brakuje tu spójności i trzymanie tego jako id i parent_id przy moim rozwiązaniu nie jest zbytnio optymalne, a tym bardziej gdy chce zrobić z tego drzewko.

**Comment by riepa** [comment]
Raczej nie będzie przejścia na intowe id : P nowa polityka, wszytko w guidach

**Comment by PawelTaberski** [comment]
Wszystkim nowym kategorią nadajemy numer w formacie UUID. Odnośnie Twojego pytania o całe drzewo w obecnej formie również możesz je pobrać tylko będzie to wymagało większej liczy requestów.

**Comment by GyniO** [comment]
Uwaga, Pan @PawelTaberski narobił zamieszania z ID'kami, jednak będą tylko integery. Super zmarnowany czas na przeróbki, a teraz z wszystkim trzeba wracać.
