### ISSUE TITLE
Wyszukanie produktu po EAN i rozmiarze

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#6990]
Czy jest iozliwość wyszukania produktu z określonym kodem ean i rozmiarem?

Np.: https://api.allegro.pl/sale/products?mode=GTIN&phrase=8050036955180&category.id=76076&54=5

**Comment by PrzemyslawLukanowski** [comment]
Tak, listę dostępnych filtrów znajdziesz na końcu odpowiedzi w polu "filters". Aby wyszukać wg rozmiaru "5", musisz użyć wartości "972321". W polu "count" znajdziesz liczbę produktów, która pasuje do tej wartości. W tym konkretnym przypadku jest to 0.
