### ISSUE TITLE
Przewidywana dostawa?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#6991]
Dzień dobry,
na aukcjach, które nie mają od ręki towaru pojawia się napis "przewidywana dostawa" np. za 25 dni.
W jaki sposób mogę tym sterować? 
Jak ustawiam "handlingTime": "P7D" to i tak na aukcji pojawia mi się 25 dni, a chciałbym aby było za 7 dni.

**Comment by PrzemyslawLukanowski** [comment]
"handlingTime" to czas wysyłki, który możesz ustawić ręcznie, ponieważ jest on w pełni zależny od Ciebie, nie jest on tożsamy z przewidywaną dostawą. Ją wyliczamy automatycznie, więcej informacji znajdziesz [w tym artykule dla sprzedających](https://allegro.pl/dla-sprzedajacych/przewidywany-czas-dostawy-twojej-przesylki-AVlrm8wY3Sg).

**Comment by AleksyZajac** [comment]
Dziękuje.
