### ISSUE TITLE
Brak uprawnień przy wywołaniu zasobu [/messaging/threads]

### ISSUE THREAD

**Issue by dawidikraina** [allegro/allegro-api#6994]
Dzień dobry,
przy wywołaniu zasobu  /messaging/threads dostaję komunikat o braku uprawnień, jednak kiedy sprawdzam w zarządzaniu aplikacjami [https://apps.developer.allegro.pl/ ] uprawnienia nadane aplikacji to widzę, że aplikacja ma ustawiony dostęp do "Zarządzanie wiadomościami" więc nie rozumiem dlaczego dostaję taki komunikat.
Proszę o pomoc w wyjaśnieniu tego problemu.
ID konta: 11127442

**Comment by PrzemyslawLukanowski** [comment]
Zakres uprawnień aplikacji zapisany w tokenie, w ramach którego otrzymałeś kod 403, zawierał:

`["allegro:api:orders:read","allegro:api:profile:write","allegro:api:sale:offers:write","allegro:api:billing:read","allegro:api:campaigns","allegro:api:disputes","allegro:api:bids","allegro:api:sale:offers:read","allegro:api:orders:write","allegro:api:ads","allegro:api:payments:write","allegro:api:sale:settings:write","allegro:api:profile:read","allegro:api:ratings","allegro:api:sale:settings:read","allegro:api:payments:read"]
`

czyli bez `[allegro:api:messaging]`. Możesz to sprawdzić także po swojej stronie, dekodując token. 

Jeśli dostęp do "Zarządzania wiadomościami" dodałeś w międzyczasie i nie autoryzowałeś przy tym aplikacji na nowo, musisz teraz wykonać ten krok.
