### ISSUE TITLE
adres aukcji - dane po API

### ISSUE THREAD

**Issue by konradkur** [allegro/allegro-api#6995]
Mam pytanie, mam adres URL aukcji X
Czy mogę na tej podstawie z API wyciągnąć takie dane jak np. dostępność produktu tzn. jaki jest czas dostawy? Te dane macie opisane w HTML w schema InStock.

Dziękuje za odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Nie wspieramy takiej funkcjonalności w ramach publicznego API, możesz pobierać wyłącznie informacje o ofertach zautoryzowanego użytkownika w ramach GET /sale/offers, GET /sale/offers/{id} i GET /sale/product-offers/{id} oraz - po wcześniejszej weryfikacji - ofertach innych użytkowników, korzystając z GET /offers/listing.

Poniżej załączam także punkt 4.1e z naszego regulaminu:

> Oprogramowanie REST API nie może być wykorzystywane w sposób naruszający prawa Spółki oraz osób trzecich, w szczególności niedozwolone jest:
> 
> e. wykorzystywanie do pobierania lub wykorzystywania w jakimkolwiek zakresie dostępnych w ramach Allegro materiałów (w tym danych oraz innych informacji) bez zgody Spółki lub w sposób naruszający postanowienia Regulaminu Allegro, Regulaminu, powszechnie obowiązujące przepisy prawa, interesy Spółki lub Użytkowników, w tym do dokonywania ekstrakcji (ang. scraping) tych materiałów.
>
