### ISSUE TITLE
ProductDuplicate - Produkt z takimi danymi już istnieje

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#6996]
Przed wystawieniem oferty szukam produktu:
https://api.allegro.pl/sale/products?phrase=8056206020245&mode=GTIN&category.id=25959

Nie znajduje w danej kategorii produktu z podanym EAN więc próbuje założyć produkt:
`{
    "name": "Elastyczne buty sportowe dla dziewczynki GEOX 20",
    "category": {
        "id": "25959"
    },
    "images": [
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11ae9c\/470cc3c14035b152d68987c24117"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/1135eb\/eaf5328342569377b4730ded5645"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/1162f0\/067a95a647d18d785fbb84cc3c7e"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11811f\/158c934a4f72bb0e390a0f7af70b"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/118710\/e1abe36a486eb56d468a2ac6f461"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11ca50\/ebe0c48b4327830f5d77c8f73388"
        }
    ],
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h1>IUPIDOO BABY GIRL<\/h1><h2>Buty sportowe<\/h2><p>B3558A01454C8842<\/p><p>Zapinane na rzepy sneakersy GEOX Iupidoo Baby Girl - najnowsza propozycja z kolekcji
 wiosna\/lato 2023. Jasnor\u00f3\u017cowa cholewka to po\u0142\u0105czenie ekosk\u00f3ry i przewiewnego materia\u0142u tekstylnego. Wzmocniony nosek zapewnia ochron\u0119 ma\u0142ych st\u00f3p. Ca\
u0142o\u015b\u0107 opiera si\u0119 na elastycznej, gumowej podeszwie wyposa\u017conej w Flexy System, kt\u00f3ry wspiera naturalne u\u0142o\u017cenie st\u00f3p podczas chodzenia. Najwy\u017cszy sto
pie\u0144 amortyzacji to zas\u0142uga zastosowanej technologii Softly Cushioned, kt\u00f3ra chroni stopy, niweluj\u0105c drobne wstrz\u0105sy. Wewn\u0105trz tekstylna, siateczkowa wy\u015bci\u00f3\
u0142ka oraz antybakteryjna wk\u0142adka z bezchromowej, bezpiecznej dla dzieci sk\u00f3ry naturalnej. Wyjmowana wk\u0142adka pozwala zachowa\u0107 wysoki poziom higieny. Unikatowa podeszwa Geox Re
spira odprowadza pot na zewn\u0105trz i pozwala stopom oddycha\u0107, przy jednoczesnym niedopuszczaniu wilgoci do \u015brodka but\u00f3w. W obuwiu Geox stopy utrzymane s\u0105 w optymalnej tempera
turze i pozostaj\u0105 suche przez ca\u0142y dzie\u0144. Dzieci\u0119ce buty Geox Respira to najlepszy wyb\u00f3r dla maluch\u00f3w.<\/p><ul><li>bardzo dobre <b>wsparcie kostki i wzmocniony nosek<\
/b><\/li><li>praktyczne rzepy<\/li><li>wyciagana, <b>antybakteryjna <\/b>wk\u0142adka z <b>bezpiecznej<\/b> bezchromowej sk\u00f3ry<\/li><li>odpowiednia amortyzacja stopy dzi\u0119ki systemom <b>So
ftly Cushioned i Flexy System<\/b><\/li><li><b>oddychaj\u0105ca podeszwa<\/b> GEOX RESPIRA\u00ae<\/li><\/ul>"
                    }
                ]
            },
 {
                "items": [
                    {
                        "url": "https:\/\/a.allegroimg.com\/original\/11ae9c\/470cc3c14035b152d68987c24117",
                        "type": "IMAGE"
                    },
                    {
                        "url": "https:\/\/a.allegroimg.com\/original\/1135eb\/eaf5328342569377b4730ded5645",
                        "type": "IMAGE"
                    }
                ]
            },
            {
                "items": [
                    {
                        "url": "https:\/\/a.allegroimg.com\/original\/1162f0\/067a95a647d18d785fbb84cc3c7e",
                        "type": "IMAGE"
                    },
                    {
                        "url": "https:\/\/a.allegroimg.com\/original\/11811f\/158c934a4f72bb0e390a0f7af70b",
                        "type": "IMAGE"
                    }
                ]
            },
            {
                "items": [
                    {
                        "url": "https:\/\/a.allegroimg.com\/original\/118710\/e1abe36a486eb56d468a2ac6f461",
                        "type": "IMAGE"
                    },
                    {
                        "url": "https:\/\/a.allegroimg.com\/original\/11ca50\/ebe0c48b4327830f5d77c8f73388",
                        "type": "IMAGE"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h1>SZCZEG\u00d3\u0141Y<\/h1><ul><li><b>KOLEKCJA:<\/b> Wiosna\/lato 2023<\/li><li><b>KOLOR:<\/b> R\u00f3\u017cowy<\/li><li><b>CHOLEWKA:<\/b> Sk\u00f3ra ekologicz
na, materia\u0142<\/li><li><b>WY\u015aCI\u00d3\u0141KA:<\/b> Materia\u0142 tekstylny<\/li><li><b>WK\u0141ADKA:<\/b> Sk\u00f3ra naturalna (bezchromowa)<\/li><li><b>PODESZWA:<\/b> Geox Respira - guma
<\/li><\/ul>"
                    }
                ]
            }
        ]
    },
 "parameters": [
        {
            "id": 224017,
            "values": [
                "B3558A01454C8842"
            ],
            "valuesIds": null,
            "rangeValue": null
        },
        {
            "id": 7174,
            "values": null,
            "valuesIds": [
                "7174_1675371"
            ],
            "rangeValue": null
        },
        {
            "id": 5389,
            "values": [
                20
            ],
            "valuesIds": null,
            "rangeValue": null
        },
        {
            "id": 127789,
            "values": null,
            "valuesIds": [
                "127789_2"
            ],
            "rangeValue": null
        },
        {
            "id": 451,
            "values": null,
            "valuesIds": [
                "451_8192"
            ],
            "rangeValue": null
        },
{
            "id": 225693,
            "values": [
                "8056206020245"
            ],
            "valuesIds": null,
            "rangeValue": null
        }
    ]
}`

I dostaje błąd: ProductDuplicate - Produkt z takimi danymi już istnieje

Jak wyszukać produkt w katalogu aby znaleźć ten który już istnieje ?

**Comment by MaciejFrackowiak** [comment]
W nagłówku odpowiedzi ("location") otrzymałeś identyfikator produktu, który jest wzorcowym produktem. Dla podanego przykładu kategorią produktu jest kategoria o id=25960.
