### ISSUE TITLE
Błąd ConstraintViolationException.ValidCompatibilityTable przy wystawianiu aukcji 

### ISSUE THREAD

**Issue by JacekWUG** [allegro/allegro-api#6998]
Cześć,

wystawiając aukcję końcówką `/sale/product-offers` dostajemy 422 z komunikatem:

`
{"errors":[{"code":"ConstraintViolationException.ValidCompatibilityTable","message":"This product has a \"Compatible with\" section, but it is not associated with the offer. Use the \"Compatible with\" section related to this product. Update the product data in the offer.","details":"ConstraintViolationException.ValidCompatibilityTable","path":"compatibilityTable","userMessage":"Wybrany produkt ma sekcję \"Pasuje do\" ale nie jest ona przypisana do oferty, użyj produktowej sekcji \"Pasuje do\". Zaktualizuj dane produktowe w ofercie."}]}
`

`trace-id:"91911c9f9023a901"`

błąd występuje tylko dla kategorii 260345 _Tusze_ (tonery chyba też). W polu `compatibilityList` wysyłamy nulla, ale nie znalazłem nigdzie w dokumentacji informacji o tym żeby to pole było wymagane. [Tutaj](https://github.com/allegro/allegro-api/issues/6117#issuecomment-1246286580) jest informacja o tym że pole zostanie automatycznie uzupełnione kiedy jest puste. [Tutaj](https://developer.allegro.pl/tutorials/jak-zarzadzac-sekcja-pasuje-do-E7Zj6gAEGil) jeśli dobrze rozumiem też jest info, że `compatibilityList` zostanie automatycznie jeżeli jest puste - `Jeżeli produkt z Katalogu produktów Allegro posiada sekcję Pasuje to, to wystawiając ofertę uwzględnimy ją automatycznie w wystawianej ofercie.`. Co ciekawe, na sandboxie https://allegro.pl.allegrosandbox.pl/ dla tego samego produktu błąd nie występuje i da się wystawić aukcję z pustym `compatibilityTable` (`trace-id:"849386815467853e"`).

1. Czy pole `compatibilityList` jest wymagane? Może tylko dla określonych kategorii?
2. Skąd wynika rozbieżność pomiędzy środowiskiem testowym a produkcją? Jest możliwość żeby ją naprostować i odtworzyć błąd na sandboxie?
3. W jaki sposób mogę obejść błąd? Jeżeli sekcja pasuje do jest wymagana, jak mogę najłatwiej przypisać do niej proponowane produkty?

**Comment by MaciejFrackowiak** [comment]
Błąd polega na tym, że w swoim requeście definiujesz:
```
"compatibilityList": null,
```
Oznacza to, że mamy nie dodawać sekcji Pasuje do - gdybyś pominął to pole, to wówczas dodalibyśmy zdefiniowaną dla produktu tabelę Pasuje do.

Środowiska produkcyjne i testowe są od siebie całkowicie niezależne - oznacza to, że produkty są specyficzne dla każdego ze środowisk. Wyszukując produkt na Sandbox rzeczywiście go znajdziesz, ale będzie to zupełnie inny produkt - nie ma zdefiniowanej wartości dla "compatibilityList" i dlatego request z null'em wystawił ofertę.

**Comment by JacekWUG** [comment]
Dzięki za szybką odpowiedź. Dobrze rozumiem, że w takim razie obecnie nie ma możliwości żeby opublikować aukcję bez sekcji _Pasuje do_ jeżeli w waszym katalogu produktów jest zdefiniowana wartość _compatibilityList_ dla wystawianego produktu?

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak.

**Comment by JacekWUG** [comment]
Dzięki, zamykam w takim razie iszu :)
