### ISSUE TITLE
Układ sekcji składający się z dwóch elementów typu TEXT nie jest dozwolony

### ISSUE THREAD

**Issue by Maczuga** [allegro/allegro-api#7]
**Układ sekcji składający się z dwóch elementów typu TEXT nie jest dozwolony**

Chciałbym się dowiedzieć od kiedy taki wymóg istnieje? Sporo naszych ofert było wprowadzanych w taki właśnie sposób - nigdy nie było problemu. Od wczoraj nagle zaczęło takie coś wypluwać, przez co nie idzie modyfikować ofert.

PS: na pewno nie było to ogłaszane tutaj: https://allegro.pl/webapi/news.php

**Comment by MarcinLuczak** [comment]
Taki wymóg istnieje od zawsze. Jeśli dało się stworzyć taki układ sekcji wcześniej, to to był błąd.

Czy w Twoich ofertach taki układ sekcji występuje? Podaj proszę przykład takiej oferty.

**Comment by Maczuga** [comment]
Przykład: http://allegro.pl/wyswietlacz-lcd-ekran-dotykowy-samsung-i9300-siii-i7006041298.html#shippingInfo

**Comment by MarcinLuczak** [comment]
Dziękuję. W takim przypadku, jeśli jest problem przy edycji takiej oferty, pozostaje zmiana błędnego układu sekcji na jeden z dostępnych, prawidłowych.

**Comment by coobitus** [comment]
Panie Marcinie, jeżeli takie zasady obowiązują "od zawsze" to chyba zapomnieliście (zgodnie ze swoim standardami) o tym napisać. W Waszej dokumentacji nie ma nigdzie słowa na ten temat ... I ja również wystawiałem wcześniej aukcje z dwiema kolumnami tekstowymi i to działało. Ale przestało parę dni temu ... Standardowa kicha? Może łaskawie więc uzupełnicie swoją dokumentację, żeby kolejne osoby się nie nacięły na taką głupotę?

**Comment by MarcinLuczak** [comment]
@coobitus 
W dokumentacji pokazujemy układy jakie mogą wystąpić. Układ z dwoma polami tekstowymi nie powinien występować, więc go tam nie umieściliśmy. To, że przez API można było wystawić ofertę z takim układem, to był tylko i wyłącznie błąd, za który przepraszamy.

Inne osoby się nie nadzieją na ten problem, bo on już nie wystąpi.

**Comment by coobitus** [comment]
Że niby na PRZYKŁADOWYM obrazku nie pokazujecie? Serio?? I to ma być porządna dokumentacja?

**Comment by Maczuga** [comment]
Tu bardziej chodzi o to, że nie poinformowaliście programistów o naprawieniu błędu wiedząc, że takich układów może trochę być na waszym serwisie. W naszym przypadku było tak, że należało masowo podmienić 1 informację, która nie miała nic wspólnego z opisem i to na cito. A tu na wstępie wita na komunikat błędu, którego nigdy przedtem nie było.

Dodatkowo jak powyżej: przykładowy obrazek != napisaniu wprost, że tak nie wolno. Ba, nawet nie macie nigdzie w dokumentacji, że kod błędu zwracany w takim przypadku może wystąpić.

**Comment by MarcinLuczak** [comment]
@coobitus @Maczuga 
Dokumentacja API to tylko opis wytycznych samego protokołu. Pełne zasady tworzenia opisu oferty zgodnie z nowymi zasadami są [tutaj](https://allegro.pl/dla-sprzedajacych/nowe-zasady-dla-opisu-przedmiotu-9dXYnO3OYcz) i to jest właśnie miejsce, które mówi jak należy wystawić ofertę. Dodamy ten link do [naszego artykułu](https://developer.allegroapi.io/new_desc/) na stronie REST API.

Za brak informacji o usunięciu błędu przepraszamy. Postaramy się o tym pamiętać następnym razem.

**Comment by coobitus** [comment]
No i właśnie to jest jeden z problemów w Allegro ... Dokumentacja która jest napisana w sposób urągający podstawowym zasadom. Informacji trzeba często szukać w kilku miejscach, jest ona niepełna, niespójna i często przeczy samej sobie. I wielu rzeczy trzeba się domyślać i w efekcie próbować po omacku.

Ten pierwszy link jak dla mnie to jest tylko informacja DLA SPRZEDAJĄCEGO, nie mająca nic wspólnego z dokumentacją dla programistów, którzy wykorzystują Wasze API. Ten DRUGI LINK to jest jak dla mnie dokumentacja - a tam nie ma słowa na temat tego, że nie są dozwolone dwie kolumny tekstowe obok siebie lub że tylko wymienione W DOKUMENTACJI zestawy kolumn są dozwolone. Zamiast "dodawać linki" lepiej chyba jednak jest napisać coś wyraźnie w dokumentacji do API ...

**Comment by MarcinLuczak** [comment]
Chcemy, by informacje były jasne i przejrzyste, dlatego zasady dotyczące wystawiania ofert znajdują się osobno, a w dokumentacji są tylko elementy stricte dotyczące API.
