### ISSUE TITLE
Podany opis zawiera błędy.

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#70]
Dało by radę dodać do treści błędu nieco więcej informacji? Rozwikłanie co jest nie tak z opisem zajmuje dużo czasu. Co jest błędne, gdzie? Czy niepoprawnie zagnieżdżony html czy znaki spoza widzialnych ASCII czy może JSON jest źle sformatowany. Nie wiadomo. 

```xml
<SOAP-ENV:Body>
	<SOAP-ENV:Fault>
		<faultcode>ERR_STANDARDIZED_DESCRIPTION_INCORRECT</faultcode>
		<faultstring>Podany opis zawiera błędy.</faultstring>
		<faultactor>doNewAuctionExt - Given standardized description is incorrect.</faultactor>
	</SOAP-ENV:Fault>
</SOAP-ENV:Body>
```

**Comment by MarcinLuczak** [comment]
@Onixarts podeślij proszę pełny XML z requestem, dla którego dostajesz taki komunikat błędu. Dopiero wtedy będę mógł zweryfikować gdzie leży problem w opisie.

**Comment by Onixarts** [comment]
No właśnie sęk w tym, że ja też mogę sobie w ten sposób zweryfikować, ale zajmuje to od wykrycia problemu przez użytkownika do ustalenia kilka godzin. A wystarczyła by dodatkowa informacja co i gdzie jest źle :). Wyobrażam sobie ile powstało by programów... gdyby kompilator zgłaszał błąd i nie mówił gdzie i o co chodzi :).

**Comment by kormichu** [comment]
@Onixarts z tego co kojarze to taki komunikat otrzymywaliśmy jeśli zagnieżdżaliśmy znaczniki np <b> wewnątrz znacznika <h1> lub <h2>. Zobacz sobie jakie ustawienia ma tinymce po stronie Allegro ;)

**Comment by Onixarts** [comment]
W tym wypadku akurat chodziło o nieistniejące zdjęcie do którego odwołuje się FID. Po dodaniu zdjęcia pojawił się kolejny, wskazujący na niepoprawny HTML w sekcji[4].item[0] - to już przynajmniej jest jakaś informacja gdzie szukać błędu. Nadal jednak wolałbym aby API zwracało informację:
- sekcja 3 item 1 odwołanie do nieistniejącego zdjęcia 
- sekcja 4 item 0 brak tagu zamykającego w liście wypunktowanej 

Taki komunikat 73% klientów jest w stanie zrozumieć i samemu naprawić problem, bez potrzeby angażowania w to całego sztabu ludzi :).

**Comment by MarcinLuczak** [comment]
@Onixarts Tak, rozumiem co masz na myśli. Nie jestem jednak w stanie powiedzieć, czy w najbliższym czasie ten komunikat się zmieni.

**Comment by gantel86** [comment]
Ja zauważyłem, że otrzymuje dokładnie taki sam komunikat gdy dodaje do oferty konkretne zdjęcie. Gdy je usunę błąd znika. Zdjęcie poprawnie się otwiera w przeglądarce. Otworzyłem je i zapisałem ponownie w programie graficznym i to również nie pomaga. Czy możecie wskazać co w tym zdjęciu jest nie tak? https://gmoto.pl/tmp/Aww_zebatka-tyl-41z_3.jpg

**Comment by MarcinLuczak** [comment]
@gantel86 Nie jestem w stanie tego ocenić. Spróbuj zapisać to zdjęcie w innym programie lub formacie.
