### ISSUE TITLE
[Sandbox] zniknęły aukcie i nie można utworzyć nowej oferty

### ISSUE THREAD

**Issue by tomasz3k** [allegro/allegro-api#7000]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ x] inny / other

:beetle: **Opis / Description**
 
Na moim koncie sandboxowym zniknęły wszystkie aukcje i nie mogę wystawić nowej. 
Korzystając z https://allegro.pl.allegrosandbox.pl/offer/ wyszukiwarka zwraca błąd 
Nie udało się wyświetlić produktów.

W tle zapytanie dostaje internal server error 

Kiedy błąd zostanie naprawiony?

**Comment by PrzemyslawLukanowski** [comment]
Problem z wystawianiem oferty nie powinien już występować.
