### ISSUE TITLE
WZA brak powiązania błędu z przesyłką podczas sprawdzania proponowanej daty nadania przesyłki dla więcej niż jeden przesyłki 

### ISSUE THREAD

**Issue by tomasz3k** [allegro/allegro-api#7001]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Zapytanie 
GET https://api.allegro.pl.allegrosandbox.pl/parcel-management/pickup-date-proposals?readyDate=2023-04-26&parcelId=86f125ab-111f-42b1-be91-6b6d63bacf39&parcelId=abb033f5-c432-431a-8acc-1cf7c2def1aa

Zwraca
`
{
    "errors": [
        {
            "code": "ERROR",
            "message": "Parcel pickup already requested",
            "details": null,
            "path": "parcelIds[%s]",
            "userMessage": "Odbiór przesyłki został już zamówiony"
        }
    ]
}`

W komunikacie brakuje parcelId tak by było wiadomo o jaką przesyłkę chodzi. Sprawdzając daty dla 100 przesyłek, nie wiemy o którą dokładnie chodzi, a wywołując zapytanie GET https://api.allegro.pl.allegrosandbox.pl/parcel-management/pickup-date-proposals osobno dla każdego parcelID mija się z celem, chyba, że tak ma być.

**Comment by PrzemyslawLukanowski** [comment]
Zdajemy sobie z tego sprawę, jednak na tę chwilę nie mogę zagwarantować, kiedy uda nam się wprowadzić zmiany - jest to złożony problem.

**Comment by tomasz3k** [comment]
Dziękuję za informację
