### ISSUE TITLE
Nie działający refresh token

### ISSUE THREAD

**Issue by adibuu** [allegro/allegro-api#7003]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [X] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Używam Authorization Code Flow. 
Próbowałem odświeżyć token za pomocą refresh tokenu wysyłając żądanie:
POST 
https://api.allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=[MÓJ TOKEN]&redirect_uri=[MÓJ REDIRECT_URI]

W odpowiedzi otrzymuję:
Status: 404 Not Found
Body:
```
{
    "errors": [
        {
            "code": "NotFoundException",
            "message": "Not found",
            "details": null,
            "path": null,
            "userMessage": "Feature unavailable. Contact the application author."
        }
    ]
}
```

Trace-id: c180417ae7e04e9

**Comment by PrzemyslawLukanowski** [comment]
Prawidłowy adres dla metod związanych z autoryzacją to https://allegro.pl.allegrosandbox.pl/auth/oauth/token (bez api na początku).
