### ISSUE TITLE
Tworznie oferty dla istniejacego produktu/EAN #Sandbox

### ISSUE THREAD

**Issue by lasongrzegorz** [allegro/allegro-api#7004]
Czesc,
Wystawilem oferte https://allegro.pl.allegrosandbox.pl/oferta/kolpaki-14-opel-astra-corsa-insignia-btc-7702878952 przez Dashboard uzywajac Formularza. W opisie oferty dodalem `Random tekst` i podpialem jakis obrazek.
Nastepnie dla tego samego EANa utworzylem oferte poprzez API (sale/offers), gdzie payload byl:

```
payload = {
    'productSet': [{'product': {'id': ean}}],
    'sellingMode': {
        'price': {
            'amount': 22222,
            'currency': "PLN",
        }
    },
    'stock': {'available': 1},
    'delivery': {
        'handlingTime': 'P60D',
        'shippingRates': {'name': 'cennik'},
    },
    "parameters": [
        {
            "id": "201129",
            "name": "Liczba sztuk",
            "values": ["1 szt."],
        }
    ]
}
```

Jak patrze jednak na https://allegro.pl.allegrosandbox.pl/oferta/kolpaki-14-opel-astra-corsa-insignia-btc-7702879322 to widze, ze oferta zostala stworzona z innym obrazkiem, ale opis zostal skopiowany z mojej poprzedniej oferty.

Dlaczego tak sie dzieje skoro uzywam EAN ktory juz istnieje w katalogu produktow?

Z gory dzieki za szybka odpowiedz

**Comment by PrzemyslawLukanowski** [comment]
Wskazałeś nam konkretny produkt w polu `productSet.product.id`, dlatego do oferty przypisaliśmy dane tego produktu z naszej bazy produktowej, w tym wspomniane przez Ciebie obrazki oraz opis. Produkt został utworzony jeszcze w 2021, za pomocą GET /sale/products/00fefe01-fb3b-4d9f-8091-c5f93ea4bcfe możesz podejrzeć jego dane.

**Comment by lasongrzegorz** [comment]
Na opis w ofercie stworzonej poprzez api skladaja sie dwie rzeczy: 
1. obrazek ktory przeszedl z automatu
2. opis "Random tekst" ktory dodalem tylko do oferty poprzez dashboard

W katalogu nie ma opisu produktu:
![image](https://user-images.githubusercontent.com/53792781/234285802-d2e80992-9912-4a2e-b30c-a86ea7b694fd.png)

Nie do konca dalej rozumiem wiec skad w ofercie z api pojawil sie "Random tekst" ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, zweryfikowałem to - jeśli produkt w naszej bazie nie posiada opisu, przypiszemy do produktu i oferty opis, który przekażesz nam w polu `description`. Jeśli produkt posiada opis i uwzględnisz także inny opis w body requestu, w ofercie uwzględnimy Twój przekazany opis, nie zmieniając przy tym danych w naszej bazie produktowej. Jeśli nie chcesz nadpisywać w swojej ofercie opisu z produktu, nie przekazuj pola `description` - w ofercie zostanie uwzględniony opis z naszego katalogu produktów.
