### ISSUE TITLE
PUT /sale/offers/{id} i błąd: "You may not list offers in this category"

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#7005]
Podczas wykonywania PUT /sale/offers/{id} otrzymuję błąd: "You may not list offers in this category". Nie bardzo rozumiem dlaczego nie mogę edytować tej oferty.

trace-id: d2a8294ca3d6e4eb

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Jest to odpowiedź zgodna z naszymi założeniami, ponieważ przygotowujemy się do usunięcia tej kategorii. Podobne zachowanie wystąpi także na formularzu na stronie internetowej. Szczegóły znajdziesz [w newsie na stronie dla sprzedających](https://allegro.pl/dla-sprzedajacych/24-kwietnia-wprowadzamy-zmiany-w-wystawianiu-ksiazek-obcojezycznych-VL7xBEwrYUG).

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję ten temat z zespołem odpowiedzialnym za zmiany. Jak tylko uda mi się coś ustalić, wrócę z informacją.

**Comment by PrzemyslawLukanowski** [comment]
Po analizie sytuacji zdecydowaliśmy się zdjąć blokadę edycji ofert. Natomiast samo przeniesienie do innych kategorii to kwestia tygodni.

**Comment by tomylee0** [comment]
Kapitalna wiadomość. Dziękuję za pomoc.
