### ISSUE TITLE
WzA etykieta DHL

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#7007]
Czy jest możliwość w jakiś sposób wyłączenia generowania etykiety z potwierdzeniem nadania dla przesyłek DHL?
Tworzymy przesyłki przez api i zwrotka z etykieta zawiera 2 etykiety, jedna normalna a druga to egzemplarz dla klienta z potwierdzeniem nadania (część tej drugiej zamieszczam na screenie). Czy jest jakiś parametr w api albo ustawienie w Allegro które pozwala na wyłączenie generowania tej drugiej etykiety?
![Zrzut ekranu 2023-04-26 o 10 20 04](https://user-images.githubusercontent.com/32417963/234514546-5309cb1d-229a-432e-a8ef-efd6ea7cd427.png)

**Comment by MaciejFrackowiak** [comment]
Weryfikuję Twoje zapytanie z zespołem, wrócę z odpowiedzią.

**Comment by d3stozaur** [comment]
udało się coś ustalić?

**Comment by MaciejFrackowiak** [comment]
Tak, skonsultowaliśmy sprawę z DHL - niestety, nie ma technicznej możliwości wyłączenia tej opcji.
