### ISSUE TITLE
Czy istnieje możliwość pobrania realnego adresu email osoby kupującej

### ISSUE THREAD

**Issue by jakubm999** [allegro/allegro-api#7009]
Witam,
pobierając informację o osobie kupującej z checkout-forms, w polu dostajemy wygenerowany email allegro, przykładowo: 2b2sudbqn9+5886ad639@user.allegrogroup.pl
Czy da się w jakiś sposób przez API pobrać prawdziwy email osoby kupującej?

**Comment by PrzemyslawLukanowski** [comment]
Nie udostępniamy takiej możliwości. Więcej o tym, jak wyświetlamy maile kupujących, przeczytasz [w tym artykule](https://allegro.pl/pomoc/dla-sprzedajacych/kontakt-z-klientem/jak-wyswietlamy-adresy-e-mail-w-korespondencji-w-ramach-allegro-5VZxXd8vzSL).

**Comment by jakubm999** [comment]
Ok, dzięki.
