### ISSUE TITLE
AbstractRestBetaResource::post()

### ISSUE THREAD

**Issue by nataniel** [allegro/allegro-api#701]
Warning: Declaration of Ircykk\AllegroApi\Rest\AbstractRestBetaResource::post($path, array $params = Array, array $requestHeaders = Array) should be compatible with 
Ircykk\AllegroApi\Rest\AbstractRestResource::post($path, $data, array $requestHeaders = Array) in /home/rebel/admin/vendor/ircykk/allegro-api/src/Rest/AbstractRestBetaResource.php on line 60

**Comment by PawelTaberski** [comment]
Prosiłbym o podesłanie troszkę więcej informacji. Przy jakiej metodzie masz problem co próbujesz zrobić.

**Comment by nataniel** [comment]
Przepraszam, zgłoszenie w złym miejscu :-), dotyczy biblioteki ircykk/allegro-api, przez zbieżność nazw zgłosiłem nie w tym projekcie.
