### ISSUE TITLE
Get offer id (/sale/offers) by any EAN

### ISSUE THREAD

**Issue by lasongrzegorz** [allegro/allegro-api#7010]
Czesc,
Mialbym pytanie do sprawdzenia ofert sellera `https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET` .
W ramach tego endpointu moge sprawdzic czy istnieje oferta dla konkretnego `external.id` ktore sobie nadam przytworzeniu oferty. Zdarza sie jednak, ze nie nadaje takie numeru. Jezeli zatem przypadkiem nie zapisze od oferty, to czy jest mozliwosc znalezienia id oferty szukajac po produkcie (EAN / allegro product id), dla ktorego zostala wystawiona?
Z gory dzieki

**Comment by MaciejFrackowiak** [comment]
Nie, takie parametry filtrowania nie są dostępne w ramach zasobu [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET).
