### ISSUE TITLE
Pobranie opisu produktu

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#7011]
Przy wystawianiu oferty z formularza jest możliwość pobrania opisu i zdjęć produktu. Jaki jest tego odpowiednik w API? sale/products/xxx nie zwraca sekcji description

**Comment by MaciejFrackowiak** [comment]
Zasób [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct) zwraca opis ("description") jeżeli dany produkt takowy opis posiada.
