### ISSUE TITLE
Wyszukiwanie ofert po ID produktu

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#7012]
Jak pobrać listę ofert w serwisie po id produktu? Konkretniej; jak dla konkretnego produktu pobrać zakres cen w jakich jest oferowany, analogicznie do tego jak to wygląda w formularzu wystawiania?

**Comment by MaciejFrackowiak** [comment]
Ta funkcjonalność nie jest dostępna w API.
