### ISSUE TITLE
brak kampanii w AlleObniżka w akcjach dostępnych pod sale/badges

### ISSUE THREAD

**Issue by Sebastian-Le** [allegro/allegro-api#7013]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Produkty zakwalifikowane i zaakceptowane do AlleObniżka 20.04-03.05.2023
nie mają wyświetlanej informacji o aktualnej promocji
analogiczna sytuacja była w #6379 

endpoint sale/badges nie ma takiej akcji w zasobach.

Sugestie już dodawałem w poprzednim wątku ale powtórzę:

"przynajmniej przekazujcie przez API informację o zmianie ceny i opisem 'inna kampania', aby był jakiś ślad z czego wzięła się zmiana ceny"

**Comment by MaciejFrackowiak** [comment]
Skonsultowałem Twoje zgłoszenie z zespołem odpowiedzialnym za usługę - w zasobach do obsługi badge nie zwracamy informacji o udziale w akcji AlleObniżka. Docelowo, udostępnimy zasoby, które będą odpowiedzialne wyłącznie za obsługę tego typu promocji.

**Comment by Sebastian-Le** [comment]
Mamy oferty zgłoszone z poziomu frontu i w żaden sposób nie sposób ustalić w jakiej promocji się znajduje poprzez API

1.) w związku z czym pojawiają się rozbieżności w cenach przy importowaniu zamówień
2.) oferta może zostać szybko usunięta z kampanii zmianą ceny na 'tą która jest ustalona do oferty'

**Comment by Sebastian-Le** [comment]
ok
Jest szansa określenia kiedy nowy zasób się pojawi ?

**Comment by MaciejFrackowiak** [comment]
Na chwilę obecną konkretnego terminu nie mogę wskazać. Na pewno będziemy informować o tym w naszych newsach.
