### ISSUE TITLE
sale -> product-offers return Product category is required. Enter the category ID [pilne]

### ISSUE THREAD

**Issue by BartDev785** [allegro/allegro-api#7014]
Hej, dostają właściwie czego bym nie robił zwrotkę od zasobu sale -> product-offers
_Product category is required. Enter the category ID._

(trace-id: db63ad57689c1a49)

wysłany json

`{"productSet":[{"product":{"category":{"id":"255920"},"id":"42d09554-78c1-46de-8a14-53249142a7d2"},"quantity":{"value":"1"}}],"name":"POMPA PALIWA RENAULT TWINGO 8200368239","category":{"id":"255920"},"sellingMode":{"format":"BUY_NOW","price":{"amount":"999.00","currency":"PLN"}},"stock":{"available":"1","unit":"UNIT"},"payments":{"invoice":"VAT"},"location":{"countryCode":"PL","province":"MALOPOLSKIE","city":"Raba Wyzna","postCode":"34-721"},"delivery":{"shippingRates":{"id":"52d8f274-c3d1-4a27-ba7f-3a54068d5161"},"handlingTime":"PT24H"},"afterSalesServices":{"warranty":{"id":"39a94e9b-7695-4520-aa67-9af2da31ad46","name":"Nowe"},"impliedWarranty":{"id":"1faec7ff-f9e9-43fa-ab3c-6eb0e98a6f7d","name":"Nowe"},"returnPolicy":{"id":"9a050833-e23e-406d-896c-37e604db7307","name":"Nowe"}},"external":{"id":"V46-09-0042"},"description":{"sections":[]},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/11ab35\/c630be7f4ae2ad2e890c1ce05af2"},{"url":"https:\/\/a.allegroimg.com\/original\/11088c\/2b819be54c26907db443114696fb"},{"url":"https:\/\/a.allegroimg.com\/original\/11dd04\/dd48e2a84c69bfc9fc7d16c96673"}],"publication":{"republish":false,"duration":"PT0S","status":"INACTIVE"},"language":"pl-PL"}`

**Comment by MaciejFrackowiak** [comment]
Trace-id, które podajesz prowadzi do wywołania:
```
{"type":"CAR","phrase":"Opel ZAFIRA A nadwozie wielkoprzestrzenne (MPV) (T98) 2.2 DTI 16V (F75) (Y 22 DTR) 2172ccm 125KM/92kW 2002/01-2005/06"}
```

Twój obecny request co do zasady jest poprawny - podając "description" musisz je uzupełnić o treść opisu.

**Comment by MaciejFrackowiak** [comment]
Walidujemy kolejno poszczególne wymagane pola requestu - pierwszy odnosi się do kategorii, a w Twoim przypadku jej brak. Zwracamy ogólny błąd 422 - Unprocessable Entity.

**Comment by BartDev785** [comment]
Kategrii produktu?

**Comment by BartDev785** [comment]
{"productSet":[{"product":{"id":"59621544-02ab-4e6f-b219-ad05fd6b4400","idType":""}}],"name":"MECHANIZM SILNIK WYCIERACZEK FIAT PUNTO 159200-734","category":{"id":"254185"},"sellingMode":{"format":"BUY_NOW","price":{"amount":"999.00","currency":"PLN"}},"stock":{"available":"1","unit":"UNIT"},"payments":{"invoice":"VAT"},"location":{"countryCode":"PL","province":"MALOPOLSKIE","city":"Raba Wyzna","postCode":"34-721"},"delivery":{"shippingRates":{"id":"52d8f274-c3d1-4a27-ba7f-3a54068d5161"},"handlingTime":"PT24H"},"afterSalesServices":{"warranty":{"id":"39a94e9b-7695-4520-aa67-9af2da31ad46","name":"Nowe"},"impliedWarranty":{"id":"1faec7ff-f9e9-43fa-ab3c-6eb0e98a6f7d","name":"Nowe"},"returnPolicy":{"id":"9a050833-e23e-406d-896c-37e604db7307","name":"Nowe"}},"external":{"id":"52451"},"description":{"sections":[]},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/11752e\/ff86cf8343fdb4eb744fc6d45549"},{"url":"https:\/\/a.allegroimg.com\/original\/11d516\/b698689f43599f8aa14966431232"},{"url":"https:\/\/a.allegroimg.com\/original\/11d5dc\/59a6d72b473f855dd59b7d03aedf"}],"publication":{"republish":false,"duration":"PT0S","status":"ACTIVE"},"language":"pl-PL"}

Nadal ten sam błąd

**Comment by BartDev785** [comment]
tutaj dokładnie jak to wygląda:

```
Nazwa: MECHANIZM PODNOSZENIA SZYB FIAT PUNTO 46536312

tablica szkicu:

{"productSet":[{"product":{"id":"a5268c4b-9e7b-41f8-b99d-ec3d1815c730","idType":""}}],"name":"MECHANIZM PODNOSZENIA SZYB FIAT PUNTO 46536312","category":{"id":"256182"},"sellingMode":{"format":"BUY_NOW","price":{"amount":"999.00","currency":"PLN"}},"stock":{"available":"1","unit":"UNIT"},"payments":{"invoice":"VAT"},"location":{"countryCode":"PL","province":"MALOPOLSKIE","city":"Raba Wyzna","postCode":"34-721"},"delivery":{"shippingRates":{"id":"52d8f274-c3d1-4a27-ba7f-3a54068d5161"},"handlingTime":"PT24H"},"afterSalesServices":{"warranty":{"id":"39a94e9b-7695-4520-aa67-9af2da31ad46","name":"Nowe"},"impliedWarranty":{"id":"1faec7ff-f9e9-43fa-ab3c-6eb0e98a6f7d","name":"Nowe"},"returnPolicy":{"id":"9a050833-e23e-406d-896c-37e604db7307","name":"Nowe"}},"external":{"id":"54399"},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/11b8d4\/2114dc0041eaa0c07d2c3bfeff27"},{"url":"https:\/\/a.allegroimg.com\/original\/11d915\/cdc5407c496988dd3d5d31efe0e2"},{"url":"https:\/\/a.allegroimg.com\/original\/1176ca\/d2b4f90e4908b74f68f22d5c4cea"}],"publication":{"republish":false,"duration":"PT0S","status":"ACTIVE"},"language":"pl-PL"}

2023-04-27 12:47:13 rozpoczęto dodawanie szkicu

Array ( [0] => HTTP/1.0 422 Unprocessable Entity [1] => expires: 0 [2] => cache-control: no-cache, no-store, max-age=0, must-revalidate [3] => x-xss-protection: 1; mode=block [4] => pragma: no-cache [5] => x-frame-options: DENY [6] => trace-id: c7ec79762690aef7 [7] => date: Thu, 27 Apr 2023 10:47:13 GMT [8] => x-content-type-options: nosniff [9] => strict-transport-security: max-age=31536000 ; includeSubDomains [10] => content-type: application/json; charset=UTF-8 [11] => content-length: 176 ) https://api.allegro.pl/sale/product-offers


2023-04-27 12:47:13 zakończono dodawanie szkicu

Product category is required. Enter the category ID.

Brak aktywacji!
```

**Comment by MaciejFrackowiak** [comment]
Podajesz trace-id=c7ec79762690aef7, który prowadzi do zupełnie innych danych niż te, które wklejasz do swoich zgłoszeń. Ponadto przekazujesz nieprawidłowo sekcję odpowiedzialną za zdjęcia ("images") - zgodnie z [dokumentacją](https://developer.allegro.pl/documentation/#operation/createProductOffers) jest to tablica stringów. Ponadto przekazujesz pusty opis ("description") - jak przekazujesz wartość to musisz go uzupełnić. Gdy to poprawisz powyższy przykład jest OK - kończy się statusem 202.

**Comment by MaciejFrackowiak** [comment]
Komunikat o braku kategorii z 422 dotyczy Twoich requestów w postaci:
```
{"type":"CAR","phrase":"Opel ZAFIRA A nadwozie wielkoprzestrzenne (MPV) (T98) 2.2 DTI 16V (F75) (Y 22 DTR) 2172ccm 125KM/92kW 2002/01-2005/06"}
```
Zatem sprawdź proszę poprawność przekazywanych przez siebie danych.

**Comment by BartDev785** [comment]
Okey, bardzo dziękuję :)

**Comment by BartDev785** [comment]
Okey, nadpisywały mi się zmienne, poprawione, dzięki, natomiast jest prawie dobrze ;) Niepoprawny czas trwania oferty? Teraz trace-id powinno być okey, zgadza się?

Nazwa: WŁĄCZNIK ŚWIATŁA STOP RENAULT ESPACE 414988

tablica szkicu:

{"productSet":[{"product":{"id":"d92231bb-b03c-467f-8786-e4974df017d0"}}],"name":"W\u0141\u0104CZNIK \u015aWIAT\u0141A STOP RENAULT ESPACE 414988","category":{"id":"257000"},"sellingMode":{"format":"BUY_NOW","price":{"amount":"999.00","currency":"PLN"}},"stock":{"available":"1","unit":"UNIT"},"payments":{"invoice":"VAT"},"location":{"countryCode":"PL","province":"MALOPOLSKIE","city":"Raba Wyzna","postCode":"34-721"},"delivery":{"shippingRates":{"id":"52d8f274-c3d1-4a27-ba7f-3a54068d5161"},"handlingTime":"PT24H"},"afterSalesServices":{"warranty":{"id":"39a94e9b-7695-4520-aa67-9af2da31ad46","name":"Nowe"},"impliedWarranty":{"id":"1faec7ff-f9e9-43fa-ab3c-6eb0e98a6f7d","name":"Nowe"},"returnPolicy":{"id":"9a050833-e23e-406d-896c-37e604db7307","name":"Nowe"}},"external":{"id":"V46-73-0002"},"images":["https:\/\/a.allegroimg.com\/original\/111af9\/825f9ee74c85b4427f77cedfdb13","https:\/\/a.allegroimg.com\/original\/112094\/997d09294927b8510bb653f6fe19","https:\/\/a.allegroimg.com\/original\/11edfe\/c6e8218c4ffcb066c5ab2f3b324b"],"publication":{"republish":false,"duration":"PT0S","status":"ACTIVE"},"language":"pl-PL"}

2023-04-27 13:49:04 rozpoczęto dodawanie szkicu

Array ( [0] => HTTP/1.0 422 Unprocessable Entity [1] => expires: 0 [2] => cache-control: no-cache, no-store, max-age=0, must-revalidate [3] => x-xss-protection: 1; mode=block [4] => pragma: no-cache [5] => x-frame-options: DENY [6] => trace-id: 5aa41e835b85eda0 [7] => date: Thu, 27 Apr 2023 11:49:05 GMT [8] => x-content-type-options: nosniff [9] => strict-transport-security: max-age=31536000 ; includeSubDomains [10] => content-type: application/json; charset=UTF-8 [11] => content-length: 437 ) https://api.allegro.pl/sale/product-offers


2023-04-27 13:49:05 zakończono dodawanie szkicu

Dostęp zabroniony.
Niepoprawny czas trwania oferty.

**Comment by BartDev785** [comment]
Dobra, już wiem: mieliśmy złe ID cennika, dla ofert kup teraz obowiązuje wartość NULL a nie PT0S, teraz śmiga :)
