### ISSUE TITLE
masowa zmiana delivery.handlingTime

### ISSUE THREAD

**Issue by bseHlpDsk** [allegro/allegro-api#7015]
Temat był już omawiany w wątku: 
https://github.com/allegro/allegro-api/issues/5461 - jednak bez rozwiązania. 

Wg dokumentacji nadal zmiana czasu wysyłki dostępna jest jedynie w metodzie 

PATCH 'https://api.allegro.pl/sale/product-offers/{offerID}'

co w sytuacji, gdy mamy ponad 100 tys ofert? (kategoria książki)  bez wykorzystywania równoległych procesów - czas realizacji wyniesie ponad dobę. 
Przez stronę allegro można zmienić - dla 1000 ofert naraz, niemniej brakuje w filtrach czasu wysyłki, więc nie da się tego efektywnie wprowadzić. 
Jaka jest wskazywana przez Allegro droga rozwiązania takiego problemu?

**Comment by MaciejFrackowiak** [comment]
W tej kwestii w API nic się nie zmieniło względem wskazanego wątku #5461.

**Comment by bseHlpDsk** [comment]
ok, a w związku z tym jaka jest wskazywana przez Allegro droga rozwiązania takiego problemu?
Czy jest możliwość wprowadzenia zbiorczych zmian przez Zespół Allegro na zlecenie Sprzedawcy, lub inne rozwiązanie?

**Comment by MaciejFrackowiak** [comment]
Nie, wszelkie operacje musi wykonać Sprzedawca - nie możemy wykonywać operacji w Twoim imieniu.

**Comment by bseHlpDsk** [comment]
ok, dziękuję
