### ISSUE TITLE
Informacje o tym, jakiego produktu dotyczy ta oferta

### ISSUE THREAD

**Issue by aktream** [allegro/allegro-api#7016]
Cześć!
/sale/offers zawiera informacje o oferty. Ale nie pokazuje, do którego produktu należy ta oferta.
Jak mogę się dowiedzieć?

**Comment by MaciejFrackowiak** [comment]
Skorzystaj z [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getProductOffer) lub [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET), wówczas poznasz identyfikator produktu przypisanego do danej oferty.
