### ISSUE TITLE
aktywacja sandbox

### ISSUE THREAD

**Issue by pebepebe** [allegro/allegro-api#7017]
Proszę o aktywację konta bisoft (bisoft@fan.pl) na sandbox. Przelew symulowany wysłałem przedwczoraj.

**Comment by MaciejFrackowiak** [comment]
Twoje konto jest już aktywne i zweryfikowane.

**Comment by pebepebe** [comment]
dziękuję!

**Comment by Chris-Brauner** [comment]
Proszę o aktywację konta sandbox SMA_Helion_SB.

**Comment by MaciejFrackowiak** [comment]
@Chris-Brauner Proszę dokończ proces weryfikacji - prześlij dowolny plik, aby potwierdzić dane z dowodu/paszportu - zrobisz to w tzw. [krokowcu](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by Chris-Brauner** [comment]
Gotowe.

**Comment by MaciejFrackowiak** [comment]
@Chris-Brauner I z mojej strony gotowe ;)

**Comment by Chris-Brauner** [comment]
Dziękuję. Teraz wszystko działa :)

**Comment by Sacrize** [comment]
Proszę o aktywację konta sandbox zaileto_test

**Comment by MaciejFrackowiak** [comment]
@Sacrize Proszę dokończ proces aktywacji - dokonaj przelewu weryfikacyjnego (poprzez dostępny symulator) oraz prześlij dowolne pliki jako kopie dokumentów - zrobisz to w tzw. [krokowcu](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by MaciejFrackowiak** [comment]
@Sacrize I z mojej strony gotowe ;)

**Comment by MaciejFrackowiak** [comment]
@Sacrize Dokumenty przesłane do nas są bezpieczne - dane Twojej firmy będą jednak widoczne np. gdy ktoś dokona testowego zakupu na Sandbox.

**Comment by wojciuch** [comment]
Witam,

Proszę o aktywację konta sandbox:
nazwa konta: gapcio
