### ISSUE TITLE
Języki oferty 

### ISSUE THREAD

**Issue by bseHlpDsk** [allegro/allegro-api#7018]
Po pierwsze błąd - 

https://allegro.pl/uzytkownik/bookseller_ukr - w przypadku zmiany języka użytkownika na ukraiński  - oferty nie są widoczne.  Co ciekawe - są widoczne dla zalogowanych użytkowników firmowych. 

Po drugie - odnośnie zapowiedzi  wprowadzenia wymagalności pola język: 
https://github.com/allegro/allegro-api/issues/6775

czy i kiedy można się spodziewać wsparcia dla języka ukraińskiego?

**Comment by PrzemyslawLukanowski** [comment]
Na forum zajmujemy się problemami związanymi stricte z API. Pierwsze Twoje pytanie dotyczy allegro.pl - strony internetowej, drugie również nie jest związane z API, a ofertą w kontekście całego Allegro. W związku z tym, skorzystaj proszę z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt).

**Comment by bseHlpDsk** [comment]
Skierowałem to pytanie na to forum gdyż zadane pytanie przez formularz pozostało bez odpowiedzi. 
zawężając problem do API - jeśli dysponuję danymi produktu w jezyku ukraińskim to jak powinna wyglądać oferta: gdzie zamieścić opis o oryginale aby był on wyświetlony użytkownikom w tym języku ? 
Obecnie zamieszczona przez API oferta - bez podanego pola "language" - nie wyświetla się użytkownikom w języku wprowadzenia opisu i nazwy oferty.

**Comment by PrzemyslawLukanowski** [comment]
>  jeśli dysponuję danymi produktu w jezyku ukraińskim to jak powinna wyglądać oferta: gdzie zamieścić opis o oryginale aby był on wyświetlony użytkownikom w tym języku ?

W ofercie wspieramy wyłącznie język polski i angielski, dlatego opis musisz uwzględnić w jednym z tych języków. Jeśli język produktu (nie oferty) jest ukraiński (tak został określony w polu "language" przy tworzeniu produktu), wtedy - po tym, gdy użytkownik zmieni język interfejsu na stronie na ukraiński -  przetłumaczymy wyłącznie tytuł oferty i i parametry. W polskiej lokalizacji tytuł zostanie wyświetlony po polsku.

> Obecnie zamieszczona przez API oferta - bez podanego pola "language" - nie wyświetla się użytkownikom w języku wprowadzenia opisu i nazwy oferty.

Jeśli nie określisz języka oferty, domyślnie na tę chwilę przypisujemy wartość "pl-PL" i właśnie w tym języku wyświetlimy dane.
