### ISSUE TITLE
Zmiana redirect_uri REST API

### ISSUE THREAD

**Issue by Radziasss** [allegro/allegro-api#702]
Czy można zmienić adres, na który ma zostać zwrócony token po poprawnym zalogowaniu usera (przez REST API), jeśli zarejestrowałem już aplikację w Allegro? Jak wchodzę w edycję, to te pola są "wyszarzone":

![rest_api_edycja](https://user-images.githubusercontent.com/37396944/46462731-7f697280-c7c2-11e8-98ba-2975eebdc176.png)

Czy przy takiej zmianie muszę rejestrować nową aplikację?

**Comment by PawelTaberski** [comment]
Raz zapisanych danych przy rejestracji nie da się zmienić, w takim wypadku musisz zarejestrować jeszcze raz aplikację z poprawnymi danymi.

**Comment by Radziasss** [comment]
Ok dzięki
