### ISSUE TITLE
Błąd aktualizacji cennika dostaw

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#7020]
Testuję aktualizację cennika dostaw na sandboxie.
Próbuję zaktualizować cennik dostawy PUT /sale/shipping-rates/0f9e64f0-28f5-4259-946d-6a87ddd3ce79 gdzie jedna z metod to "Czechy" i dostaję dwa błędy.

1. Cena wysyłki pierwszej sztuki przedmiotu dla waluty CZK musi być bez części ułamkowej.
2. Brak metod [d9616b72-9a79-11e5-8994-feff819cdc9f] wymaganych w pakiecie metod "CzechiaBundle".

Moje pytania:
1. Gdzie znajdę informacje w API na temat części ułamkowych cen wysyłek?
2. Gdzie znajdę informacje w API na temat pakietów metod (co z czym należy łączyć w cenniku lub jakie są zasady łączenia)?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie udostępniamy takich informacji na naszej stronie. Konsultuję ten temat i wrócę z odpowiedzią na drugie pytanie. Odpowiedni informacje dodamy także w [naszym poradniku](https://developer.allegro.pl/tutorials/wystawianie-i-zarzadzanie-oferta-w-serwisach-zagranicznych-wwzjP4M8gTZ).

**Comment by PrzemyslawLukanowski** [comment]
Wracam z odpowiedzią - eksportowe metody dostawy, które zwracamy w ramach [GET /sale/delivery-methods](https://developer.allegro.pl/documentation#operation/getListOfDeliveryMethodsUsingGET), mogą wystąpić w więcej niż jednym wariancie, rozróżnisz je na podstawie pola `marketplace.id`. W przypadku metod `Allegro Kurier DPD Czechy` i `Allegro Kurier DHL Czechy`, w ramach pakietu, musisz dodać także analogiczne metody na Słowację. Informację o tym, na jaki rynek przeznaczona jest dana metoda, znajdziesz w polu `marketplace.id`. 
Gdy tworzysz lub aktualizujesz cennik dostawy, musisz uwzględnić w nim wszystkie metody dostawy, które wchodzą w skład pakietu.
