### ISSUE TITLE
Ile kosztuje API, czy jest jakaś dokumentacja dotycząca kosztów?

### ISSUE THREAD

**Issue by KamilKozera** [allegro/allegro-api#7024]
Ile kosztuje API, czy jest jakaś dokumentacja dotycząca kosztów? Proszę o jakieś odnośniki, na allegro jest bardzo mało informacji.

**Comment by MaciejFrackowiak** [comment]
Korzystanie z API Allegro jest darmowe. Natomiast wszelkie operacje wykonywane są w imieniu danego użytkownika - jeżeli np. wystawia on ofertę za pośrednictwem API Allegro to mogą zostać naliczone koszty związane z wystawieniem oferty w serwisie. Opłaty i prowizje reguluje [Załącznik nr 4](https://allegro.pl/regulamin/zalacznik/4) do Regulaminu Allegro.

**Comment by KamilKozera** [comment]
Dzięki
