### ISSUE TITLE
Responso Allegro Zwrot Środków

### ISSUE THREAD

**Issue by 4TechGoods** [allegro/allegro-api#7025]
Dzień Dobry, 

Chciałem zapytać się w jaki sposób jestem w stanie mieć możliwość zwrotu środków poprzez przycisk Zwróć wpłatę w Responso tak jak w załącznik-nr. 1  aby gdy są zwroty z 2 różnych kont alegro i skanuje przesyłki to nie musiałbym się przelogowywać z jednego na konta na 2 ?

<img width="951" alt="Screenshot 2023-04-28 at 12 55 48" src="https://user-images.githubusercontent.com/132063051/235130293-dc10ca95-8c82-4be5-82cd-1d2c0fb268a3.png">

**Comment by PrzemyslawLukanowski** [comment]
Jeśli Twoje pytanie dotyczy stricte aplikacji z zrzutu, musisz skierować swoje pytanie do wsparcia Baselinkera. Z naszej strony, każde żądanie w API odbywa się w ramach zautoryzowanego użytkownika, informacja na ten temat zakodowana jest w tokenie, którym posługuje się aplikacja. Więcej informacji o samym procesie zwrotów płatności w API znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#zwroty-platnosci).

**Comment by PrzemyslawLukanowski** [comment]
Z naszej strony nie udostępniamy takiej możliwości.
