### ISSUE TITLE
sale->product-offers własne zdjęcia

### ISSUE THREAD

**Issue by BartDev785** [allegro/allegro-api#7028]
Hej, czy istnieje możliwość usunięcia zdjęć z produktu i dodania jedynie własnych? Dodałem kilka zdjęć i zostały dodane jako pierwsze, a ostatnie zostało wzięte z produktu, tu jest jakaś zasada? To działa na zasadzie zastąpienia? Rozumiem wysłanie pustego indeksu 'images'=>'' w tablicy z produktem nic nie da?

**Comment by PrzemyslawLukanowski** [comment]
Aby zachować wyłącznie zdjęcia z oferty, w polu `product.images` prześlij pustą tablicę. Przykład znajdziesz [w naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#obsluga-zdjec).
