### ISSUE TITLE
/sale/offers/{id} i edycja "tax" i "taxSettings"

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#7029]
Pytanie odnośnie #6942 a konkretnie tego fragmentu: _"jeśli podasz wartości w starym polu “tax”, przepiszemy je do nowego pola “taxSettings”. Nie możesz przekazać wartości w obu polach jednocześnie"_.

Chodzi mi o przypadek robienia edycji pola "tax" co ma miejsce przy reagowaniu na pomyłkę jeśli pierwotnie wystawiliśmy produkt z niewłaściwym VAT'em. Edycję robimy poprzez GET /sale/offers/{id}, zmienianie "tax" i potem PUT /sale/offers/{id}. W tym scenariuszu PUT wyśle dwa pola "tax" i "taxSettings" o różnych wartościach. Jak zachowa się wtedy mechanizm Allegro? Rzuci błędem czy zostawi oba pola "tax" i "taxSettings" z różnymi wartościami? 

A jak zachowa się PATCH /sale/product-offers jeśli umieścimy w requeście tylko "tax" albo tylko "taxSettings?

**Comment by PrzemyslawLukanowski** [comment]
> Edycję robimy poprzez GET /sale/offers/{id}, zmienianie "tax" i potem PUT /sale/offers/{id}. W tym scenariuszu PUT wyśle dwa pola "tax" i "taxSettings" o różnych wartościach. Jak zachowa się wtedy mechanizm Allegro? Rzuci błędem czy zostawi oba pola "tax" i "taxSettings" z różnymi wartościami?

Jako wartość "nadrzędną" odbierzemy `taxSettings`, zatem, mimo że w `tax` będziecie przesyłali inne dane, to zostaną one nadpisane, tym, co wysłaliście w `taxSettings`. Aby zmienić dane w `taxSettings`, musicie w tym przypadku usunąć to pole lub przesyłać w nim null - wtedy ten brak wartości nadpiszemy wartością z `tax`.

> A jak zachowa się PATCH /sale/product-offers jeśli umieścimy w requeście tylko "tax" albo tylko "taxSettings?

Niezależnie od tego, czy w body umieścicie `tax` czy `taxSettings`, zmienimy wartość w obu polach zgodnie z dyspozycją.

**Comment by tomylee0** [comment]
W informacji #6942 nie było wyraźnie powiedziane, że od momentu wdrożenia "taxSettings" przestaje działać dotychczasowy sposób zmiany VAT'u z użyciem "tax" i GET/PUT /sale/offers/{id}. Dodatkowo, jeśli nie było wcześniej zapowiedzi to nie mieliśmy w ogóle czasu, żeby się przygotować na pojawienie się nadrzędnego "taxSettings". Skutkiem czego nagle 12 kwietnia przestaje działać zmiana VAT'u.

**Comment by tomylee0** [comment]
Proszę jednak w moim i podejrzewam w imieniu innych użytkowników REST API o zrozumienie. News był dosyć długi i wyglądał na pierwszy rzut oka bardzo niewinnie. Można go było odebrać w taki sposób, że dotychczasowa funkcjonalność działa ale trzeba się przygotować w niedalekiej przyszłości na używanie taxSettings. I to się zgadza dla wystawiania nowych ofert. Natomiast dopiero po dłuższej analizie news'a zacząłem podejrzewać, że sporadycznie pojawiący się przypadek zmiany VAT'u przestał działać. A jeśli dobrze pamiętam to o zmianach w działaniu konkretnych funkcjonalności dowiadywaliśmy się zwykle z wyprzedzeniem. Tym razem jednak tak nie było. Dlatego nawet gdybym od razu to zauważył to i tak byłoby za późno. Ponawiam więc prośbę o informowaniu nas w miarę możliwości z wyprzedzeniem o każdej zmianie funkcjonalności.

**Comment by PrzemyslawLukanowski** [comment]
Oczywiście, weźmiemy to pod uwagę przy podobnych, przyszłych wdrożeniach. Jeszcze raz przepraszam za niedogodności.
