### ISSUE TITLE
2 pytania odnośnie cenników wysyłki.

### ISSUE THREAD

**Issue by riepa** [allegro/allegro-api#703]
Witam, mam 2 pytania które dotyczą cenników wysyłki i aukcji cennikami.
-Jak działa shippingTime w sensie kiedy jest wymagany a kiedy musi być null?
-Czy po wystawieniu aukcji przez rest api z cennikiem wysyłki nie będzie problemu z pobraniem jej parametrów i zdarzeń przez webApi (np metod metod i cen dostawy określonych w cenniku utworzonym w restapi)?

**Comment by riepa** [comment]
pytam bo wolał bym zablokować po naszej stronie przypisanie shippingTime do metody dostawy która go nie obsługuje

**Comment by PawelTaberski** [comment]
Obecnie taki czas możesz ustawić przy:
Przesyłce kurierskiej: płatnej z góry i przy odbiorze;
Paczka pocztowa ekonomiczna: opłata z góry;
Paczka pocztowa priorytetowa: opłata z góry.
Możesz sprawdzić przy jakich metodach możesz ustawić ten czas wchodząc na Moje Allegro w zakładce [ustawienia dostawy](https://allegro.pl/delivery-settings), sprawdzając poszczególne metody dostawy.
