### ISSUE TITLE
Need help: POST/PUT bad requests

### ISSUE THREAD

**Issue by mars0001** [allegro/allegro-api#7030]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [x ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Hello,
I have a problem with using the POST and PUT methods. I am trying to change the status of an order to SENT and I also am trying to update the tracking numbers/carrier for the same order.
In both cases I get the status 400, Bad Request answer.
When getting orders (using the "GET" method) all is OK.

Here are the details:

**Trying to set the status for an order to SENT.**

```
# Python Code

import requests

url = f"https://api.allegro.pl/order/checkout-forms/57d8def0-e71a-11ed-8cd8-7d8e9f9b1ec8/fulfillment"
payload = {"status": "SENT"}
headers = {
        'Accept': 		'application/vnd.allegro.public.v1+json',
        'Content-Type': 	'application/vnd.allegro.public.v1+json',
        "Authorization": 	"Bearer {token}"
}
res = requests.request("PUT", url, headers=headers, data=payload)
```
		
Request:	
```
{
	'method': 'PUT', 
	'url': 'https://api.allegro.pl/order/checkout-forms/57d8def0-e71a-11ed-8cd8-7d8e9f9b1ec8/fulfillment', 
	'headers': {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/vnd.allegro.public.v1+json', 'Connection': 'keep-alive', 'Content-Type': 'application/vnd.allegro.public.v1+json', 'Authorization': 'Bearer {token}', 'Content-Length': '11'}, 
	'_cookies': <RequestsCookieJar[]>, 
	'body': 'status=SENT', 
	'hooks': {'response': []}, '_body_position': None
}
```

Result:	
Status: 400
{'errors': [{'code': 'ERROR', 'message': 'Bad Request', 'details': None, 'path': None, 'userMessage': 'Bad Request'}]}
LE: Sometimes, even when the result is an error like this one, randomly, the order status is set.

**Trying to set the tracking number & carrier for an order .**

```
# Python code
import requests

url = f"https://api.allegro.pl/order/checkout-forms/57d8def0-e71a-11ed-8cd8-7d8e9f9b1ec8/shipments"
payload = {
	"carrierID": "OTHER",
	"waybill": "772003876324",
	"carrierName": "FedEx"
}
headers = {
        'Accept': 		'application/vnd.allegro.public.v1+json',
        'Content-Type': 	'application/vnd.allegro.public.v1+json',
        "Authorization": 	"Bearer {token}"
}
res = requests.request("POST", url, headers=headers, data=payload)
```

Request:
```
{
	'method': 'POST', 
	'url': 'https://api.allegro.pl/order/checkout-forms/57d8def0-e71a-11ed-8cd8-7d8e9f9b1ec8/shipments', 
	'headers': {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/vnd.allegro.public.v1+json', 'Connection': 'keep-alive', 'Content-Type': 'application/vnd.allegro.public.v1+json', 'Authorization': 'Bearer {token)', 'Content-Length': '54'}, 
	'_cookies': <RequestsCookieJar[]>, 
	'body': 'carrierID=OTHER&waybill=772003876324&carrierName=FedEx', 
	'hooks': {'response': []}, '_body_position': None
}
```

Result:	
Status: 400
{'errors': [{'code': 'ERROR', 'message': 'Bad Request', 'details': None, 'path': None, 'userMessage': 'Bad Request'}]}

Can you please please explain what I am doing wrong here?
Thank you,
Marius

**Comment by MaciejFrackowiak** [comment]
You have to use `res = requests.request("PUT", url, headers=headers, json=payload)` instead `res = requests.request("POST", url, headers=headers, data=payload)` - it should work.

**Comment by MaciejFrackowiak** [comment]
Nice that you managed to solve the problem.
