### ISSUE TITLE
shipmentDate 

### ISSUE THREAD

**Issue by wstoch** [allegro/allegro-api#7031]
Cześć,
co konkretnie przedstawia data zwracana w polu shipmentDate w zasobie GET /sale/offers?

**Comment by MaciejFrackowiak** [comment]
shipmentDate zwraca datę wysyłki - jest to opcja istotna np. z punktu widzenia przedsprzedaży, gdzie wskazujesz pierwszy możliwy termin wysyłki przedmiotu.

**Comment by wstoch** [comment]
Czy w przypadku ofert z normalnym trybem sprzedaży ta data zwraca deklarowany termin wysyłki zgodnie z polem handlingTime?

**Comment by MaciejFrackowiak** [comment]
Nie, data w tym polu jest tylko zwracana, gdy świadomie zadeklarujesz ten konkretny termin.
