### ISSUE TITLE
zdjęcia w opisach w tłumaczeniach.

### ISSUE THREAD

**Issue by bseHlpDsk** [allegro/allegro-api#7032]
Wprowadzając przez API w products-offers własny opis przedmiotu - można linkować do własnych zdjęciach przedmiotu. 
W przypadku wprowadzania tłumaczenia opisu - zwracany jest błąd "zdjęcie spoza Allegro". 

Czy jest planowane ujednolicenie zasady dotyczących wszystkich opisów? 
W którą stronę?

**Comment by MaciejFrackowiak** [comment]
Taka sytuacja ma miejsce, ponieważ pobierając szczegóły oferty zwracamy już zdjęcia (adresy), które są na naszym serwerze, a nie na ścieżce, którą wskazujesz w requeście podczas wystawiania ofert. Nie planujemy w tym zakresie żadnych zmian.
