### ISSUE TITLE
Aktywacja konta firmowego na sandbox

### ISSUE THREAD

**Issue by tomcik001** [allegro/allegro-api#7036]
Witam, poproszę o aktywację konta firmowego na sandboxie.

testsandboxfirma
tomekmich4@wp.pl

Pozdrawiam.

**Comment by Lukasz-Zurek** [comment]
@tomcik001 Aktywowałem w pełni Twoje konto.

**Comment by kepesian** [comment]
Dzień dobry, 
podpinam się z prośbą o aktywację konta firmowego na sandboxie, 
konto : panInv
Pozdrawiam

**Comment by prafinski** [comment]
Dzień dobry,
również poproszę o aktywację nowego konta w sandbox: **uxstudiotest**

**Comment by MartaNowaczyk** [comment]
@kepesian aktywowałam Twoje konto.

**Comment by Lukasz-Zurek** [comment]
@prafinski Konto jest już w pełni aktywne.

**Comment by PrzemyslawLukanowski** [comment]
@Marek-ShopStore Hello, your account is a regular type of account so it will be activated after the first purchase. If you want to list offers via API, register a company account or change the type of your current account.

The mentioned error is caused by an attempt to authorize an application using a client ID from the production environment. You need to register a separate application on https://apps.developer.allegro.pl.allegrosandbox.pl/.

**Comment by isgtabor** [comment]
Dzień dobry.

Chciałbym podpiąć się pod wątek aktywacji konta - prośba o aktywację konta `is_ap_gt`.

**Comment by PrzemyslawLukanowski** [comment]
@isgtabor Aktywowałem Twoje konto.

**Comment by isgtabor** [comment]
Dziękuję!

**Comment by Marek-ShopStore** [comment]
I can't upload any document as I get following error:
opbox-0a0779e0b.es6.js:1     POST https://upload.allegro.cz.allegrosandbox.pl/aml/documents net::ERR_NAME_NOT_RESOLVED
![2023-05-23 14_04_20-Allegro pl - Więcej niż aukcje  Najlepsze oferty na największej platformie handl](https://github.com/allegro/allegro-api/assets/134270003/68a94396-84f4-47ec-a764-8e012223fc72)

**Comment by PrzemyslawLukanowski** [comment]
Thank you for letting us know about this problem, I will report this to the team responsible for this feature.

Your account is finally activated :)

**Comment by AureliuszBrussy** [comment]
@mltr1 usunąłem blokadę, problem nie powinien już występować.

**Comment by daniellukaorbico** [comment]
proszę o aktywację konta na sandbox:
orbico_testowe2

**Comment by Lukasz-Zurek** [comment]
@TomasPilar I've done it already and I've mentioned about it right [here](https://github.com/allegro/allegro-api/issues/1046#issuecomment-1587039377).
