### ISSUE TITLE
order status change datetime

### ISSUE THREAD

**Issue by lasongrzegorz** [allegro/allegro-api#7037]
Czesc,
Poprzez api importuje order'y i `https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET` podajac w parametrach  `updatedAt.lte` oraz `updatedAt.gte`. Jednak z tego co widze na order'ze to mimo, ze status zmienil sie na Dispatched w piatek (28.04) o 16:05 (patrzac w Dashboard) , to w ramach powyzszego GETa taka informacja nie jest odnotowana i order o id=`dc25a8d0-e5aa-11ed-b06b-bd3cad3149fd` posiada dalej `'updatedAt': '2023-04-28T09:58:21.495Z',` mimo ze jeszcze w piatek zmienilem status na wyslany -> `'fulfillment': {'status': 'SENT',   'shipmentSummary': {'lineItemsSent': 'NONE'}},`.
Dlaczego updatedAt nie zmienia sie przy zmianie statusu ?

**Comment by Lukasz-Zurek** [comment]
@lasongrzegorz Dziękuję za zgłoszenie. Problem potwierdzam. Przekazałem tę sprawę do odpowiedniego zespołu w celu dalszej weryfikacji. Proszę o cierpliwość.

**Comment by lasongrzegorz** [comment]
dzieki - kiedy moge liczyc na jakas dalsza odpowiedz?

**Comment by Lukasz-Zurek** [comment]
@lasongrzegorz Jak tylko uzyskam więcej informacji na temat tego problemu - wrócę do Ciebie w tym wątku.

**Comment by Lukasz-Zurek** [comment]
@lasongrzegorz Okazuje się, że nie był to problem. Data w "updatedAt" nie zmienia się po uaktualnieniu statusu realizacji zamówienia przez Sprzedawcę. Wpływ na tę datę mają działania Klienta, a tym samym zmiany statusu zamówienia na: BOUGHT, FILLED_IN, READY_FOR_PROCESSING, BUYER_CANCELLED.

**Comment by lasongrzegorz** [comment]
ok, dziekuje. Czy w takim razie jest pole w zamowieniu z data, ktora jest aktualizowana jakakolwiek akcja ze strony Klienta i Sprzedawcy jednoczesnie? ?

**Comment by lasongrzegorz** [comment]
lub inaczej zadane pytanie - w jaki optymalny i periodyczny sposob polecacie sledzic zmiany na zamowieniu od ostatniego pobrania?

**Comment by Lukasz-Zurek** [comment]
@lasongrzegorz Pewnie zabrzmię dość ogólnie, ale warto śledzić na bieżąco [dziennik zdarzeń](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#dziennik-zdarzen) opierając się na wszystkich statusach, a głównie na tych, które wynikają głównie z działań wykonywanych przez Klienta, bo te zdarzenia możesz namierzyć i rozróżnić. Na tej podstawie możesz optymalnie zarządzać zamówieniami. Kluczowym statusem jest READY_FOR_PROCESSING, w przypadku którego Sprzedawca otrzymuje adres dostawy, płatność (jeśli Klient wybrał płatność z góry), etc. Możesz to porównać ze szczegółami zamówienia.

**Comment by lasongrzegorz** [comment]
dzieki. To tez zrobilem, ale mam tylko ogolnikowy `FULFILLMENT_STATUS_CHANGED - a seller changed the status of the order fulfillment.` i nie wiem na co zmienil sie ten fulfillment status :/ a takich zdarzen dla orderu moge miec kilka.

**Comment by Lukasz-Zurek** [comment]
@lasongrzegorz W pełni rozumiem sytuację. Niestety w tym przypadku mogę jedynie zasugerować sprawdzanie tych statusów w szczegółach zamówienia [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET), przy każdorazowym zwróceniu przez nas `FULFILLMENT_STATUS_CHANGED`.
