### ISSUE TITLE
 Serwisy zagraniczne Allegro i Centrum Wiadomości - pole marketplace

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#7038]
Dzień dobry,

czy Allegro przewiduje dodać pole identyfikujące kraj pytającego do wyników metody /messaging/threads?

**Comment by MaciejFrackowiak** [comment]
Nie, nie przewidujemy dodania takiej struktury.

**Comment by tomasz-grzesik** [comment]
Ok. Dziękuję za informacje.
