### ISSUE TITLE
[Pytanie] Możliwość komunikacji oraz liczenia zapytań dla IPv6

### ISSUE THREAD

**Issue by Uriziel01** [allegro/allegro-api#704]
Witam,
czy jeżeli posiadam serwer dedykowany który podzielę na VMki które będą korzystały fizycznie z tego samego interfejsu sieciowego co fizyczna maszyna ale posiadam pulę adresów IPv6 które pomiędzy je rozdzielę to mogę w jakiś sposób wskazać do API aby ilość zapytań była rozliczana z adresów IPv6 zamiast jednego głównego IPv4?

Innymi słowy czy API wspiera komunikację i co za tym idzie limitowanie po protokole IPv6 czy nadal utkeliśmy z IPv4 z **1981** roku? ;)

Oczywiście wiem że mogę zrobić to na _floating IP_ ale było by to zdecydowanie bardziej skomplikowane i droższe w implementacji.

**Comment by PawelTaberski** [comment]
Obecnie nie ma takiej możliwości.

**Comment by wispcasts** [comment]
A co tam IPv6.... proponuje od razu zrobić JUMP do IPv10

https://www.ietf.org/mail-archive/web/ietf/current/msg99869.html

**Comment by Uriziel01** [comment]
Nie wiem czy to kiepski trolling czy nie odróżnia Pan RFC od standardu ale w porządku, przyjąłem że nie ma takiej możliwości i nadal tkwimy w poprzednim stuleciu. Nie było tematu, podepniemy do serwera kilkanaście floating IPs i tak będziemy działać. Zamykam.
