### ISSUE TITLE
Symulacja zamówienia z Czech na środowisku testowym

### ISSUE THREAD

**Issue by Anch0rOne** [allegro/allegro-api#7040]
Witam,
Jak utworzyć zamówienie pochodzące z Czech na środowisku testowym Allegro ? Jest aktualnie taka możliwość ?

**Comment by MaciejFrackowiak** [comment]
Nie, obecnie jeszcze nie ma takiej możliwości.

**Comment by Anch0rOne** [comment]
Ale będzie taka możliwość przed uruchomieniem Czeskiej odsłony Allegro ?

**Comment by MaciejFrackowiak** [comment]
Uruchomienie Sandbox dla allegro.cz nastąpi nie wcześniej niż odsłonięcie głównego serwisu.
