### ISSUE TITLE
DHL-odbiór w punkcie

### ISSUE THREAD

**Issue by CSVK2022** [allegro/allegro-api#7041]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry, mamy problem z nadaniem, proszę o weryfikację.

REQUEST:
`{:serviceId=>"07c12933-584e-453d-bee5-60f3f32dfc73",
 :type=>"PACKAGE",
 :receiver=>{:address=>{:street=>"XX", :postCode=>XX", :city=>"XX", :countryCode=>"PL"}, :email=>"XX@allegromail.pl", :name=>"XX", :phone=>XX", :pointId=>"4514726"},
 :pickup=>{:address=>{:street=>"XX", :postCode=>"XX", :city=>"XX", :countryCode=>"PL"}, :email=>"XX", :name=>"XX", :company=>"XX", :phone=>"XX", :pointId=>nil},
 :label=>{:fileFormat=>"PDF", :referenceNumber=>"XX"},
 :items=>
  [{:dimensions=>{:height=>{:value=>40, :unit=>"CENTIMETER"}, :width=>{:value=>18, :unit=>"CENTIMETER"}, :depth=>{:value=>13, :unit=>"CENTIMETER"}},
    :weight=>{:value=>0.115e1, :unit=>"KILOGRAM"},
    :description=>"XX",
    :value=>{:amount=>"65.90", :currency=>"PLN"},
    :type=>"PACKAGE"}],
 :additionalServices=>{}}`

RESPONSE:

 
`=> {:data=>{:id=>"84f69592-cfbc-4d27-bd08-e2d7cede198a", :parcelId=>nil, :status=>"ERROR", :errors=>[{:code=>"ERROR", :message=>"Processing error", :details=>nil, :path=>nil, :userMessage=>"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}]},
`

**Comment by MaciejFrackowiak** [comment]
Weryfikuję przypadek z zespołem, wrócę z odpowiedzią.

**Comment by CSVK2022** [comment]
Proszę o informację jeżeli uda się coś ustalić

**Comment by Lukasz-Zurek** [comment]
@CSVK2022 Problem dotyczy wagi, która powinna być w pełnych kilogramach. Jest to ograniczenie przewoźnika. W najbliższych dniach postaramy się doprecyzować komunikaty błędów. Przepraszamy za te utrudnienia.
