### ISSUE TITLE
Problem z autoryzacją

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#7045]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [X] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry, 

mamy problem z autoryzacją aplikacji u jednego z klientów. Sprawdzono poprawność adresu URI, clientID, clientSecret. Pomimo sprawdzenia różnych scenariuszy, zawsze otrzymujemy tę samą odpowiedź:

```
[response] => Array
        (
            [error] => unauthorized
            [error_description] => Authorization header does not contain space after 'Bearer'.
        )
```

trace-id: d17e485645b3667a
wewn. nr zgłoszenia: 65743

**Comment by Lukasz-Zurek** [comment]
Komunikat: `Authorization header does not contain space after 'Bearer'` oznacza, że podczas odpytywania naszych zasobów brakuje spacji pomiędzy "Bearer", a tokenem. Tokeny dostępowe są zgodne ze standardem [JWT](https://en.wikipedia.org/wiki/JSON_Web_Token) - the Bearer schema: Authorization: Bearer eyJhbGci...<snip>...yu5CSpyHI

**Comment by DamianKAtomStore** [comment]
Racja to może powodu tego że token jest pusty dostaję taką zwrotkę przy próbie autoryzacji:
```
Brak połączenia z Allegro, prosze ponownie autoryzować konto.
```

**Comment by Lukasz-Zurek** [comment]
@DamianKAtomStore Zgadza się, przy przekazywaniu samej frazy Bearer bez tokena, zwracamy identyczny komunikat błędu i tu może być taka właśnie sytuacja.
