### ISSUE TITLE
Nadanie przesyłki do paczkomatu InPost - receiver.pointId Receiver point is incorrect

### ISSUE THREAD

**Issue by btc-jz** [allegro/allegro-api#7046]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [ X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

- środowisko, na jakim problem występuje:  produkcja
- czy powtórzenie requestu rozwiązuje problem?: nie
- login użytkownika, którego problem dotyczy: kamami_pl
- jak często problem się pojawia (wybiórczo, zawsze)?: dla tej paczki zawsze 
- jeżeli problem pojawia się wybiórczo podaj identyfikatory elementów, których dotyczy (ID ofert, formularzy posprzedażowych, użytkowników, etc.): n/d

Z jakiegoś powodu nie jestem w stanie nadać przesyłki do paczkomatu POZ224M, otrzymuję błąd:
Array
(
    [id] => 8add4d51-514c-4c43-bda2-d69090c7c0c3
    [parcelId] => 
    [status] => ERROR
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ERROR
                    [message] => Receiver point is incorrect
                    [details] => 
                    [path] => receiver.pointId
                    [userMessage] => Punkt odbiorcy jest niepoprawny
                )

        )

)

Request (usunąłem dane odbiorcy):
{"serviceId":"2488f7b7-5d1c-4d65-b85c-4cbcf253fd93#ff66f7a9-aa6f-4302-9aba-cfb466d1fe65","receiver":{"address":{"street":"xxxxx","postCode":"xxxxx","city":"Pozna\u0144","countryCode":"PL"},"email":"xxxxxxxxx@allegromail.pl","name":"xxxxxxx","company":"","phone":"xxxxxx","pointId":"POZ224M"},"pickup":{"address":{"street":"ul. Lwowska 5","postCode":"05-120","city":"Legionowo","countryCode":"PL"},"email":"sprzedaz@kamami.pl","name":"xxxxx","company":"BTC Korporacja sp. z o.o.","phone":"227673620","pointId":""},"type":"PACKAGE","label":{"fileFormat":"ZPL","referenceNumber":"F_2023_14370"},"items":[{"weight":{"value":2,"unit":"KILOGRAM"},"dimensions":{"height":{"value":8,"unit":"CENTIMETER"},"width":{"value":38,"unit":"CENTIMETER"},"depth":{"value":64,"unit":"CENTIMETER"}},"description":"Elektronika","value":{"amount":0,"currency":"PLN"}}]}

**Comment by Lukasz-Zurek** [comment]
@btc-jz Dziękuję za szczegółowe dane. Sprawę zgłosiłem do zespołu odpowiedzialnego za te funkcjonalności. Jak tylko uzyskam odpowiedź, wrócę oczywiście z informacją.

**Comment by JamesFordV3** [comment]
Hej @btc-jz,

nie wiem na ile to Ci pomoże ale tak o rzuciłem okiem na stronkę inpostu z tym paczkomatem:
https://inpost.pl/paczkomat-poznan-poz224m-sielawy-paczkomaty-wielkopolskie

na stronce pisze że jest on niedostępny /(stan na 6.05.202r. 14:00):
![obraz](https://user-images.githubusercontent.com/45076392/236622609-d4fa5436-be9d-46d5-9fb4-d897974d7af1.png)

może jakiś remont albo kij wie co i przez to nie możesz nadać tam paczki

**Comment by btc-jz** [comment]
Tak, prawdopodobnie w tym jest problem, dzięki.

**Comment by Lukasz-Zurek** [comment]
@btc-jz Początkowo myśleliśmy, że nasz operator nie odświeżył tego po swojej stronie, ale tu również potwierdzam, że paczkomat jest niedostępny z powodów bliżej nieokreślonych.

**Comment by btc-jz** [comment]
Wydaje mi się że na stronie InPost informacja o wyłączeniu paczkomatu pojawiła się z opóźnieniem, sprawdzałem to w momencie zgłoszenia problemu i prawie na pewno nie było informacji o problemie, oprócz tego mam potwierdzenie od drugiej osoby która niezależnie ode mnie również to sprawdzała z takim samym wynikiem. Tak czy inaczej byłoby miło jakby komunikat informował o tym że paczkomat istnieje ale jest nieczynny, bo obecny komunikat sugeruje raczej to, że podałem kod paczkomatu który nie istnieje.

**Comment by Lukasz-Zurek** [comment]
@btc-jz Dzięki. Kwestię dotyczącą stricte komunikatów błędów w tego typu sytuacjach, przekazałem do właściwego zespołu.
