### ISSUE TITLE
Deklarowany czas wysyłki z oferty w chwili zamówienia

### ISSUE THREAD

**Issue by kepesian** [allegro/allegro-api#7047]
W jakim zasobie można znaleźć deklarowany czas wysyłki z oferty w chwili złożenia zamówienia. Interesuje mnie opcja, gdy czas wysyłkiw ofercie uległ zmianie, ale zarejestrowane są zamówienia dokonane przed zaminą czasu wysyłki w ofercie i chciałbym pobrać dla tych zamówień jaki był deklarowany w ofercie wówczas czas wysyłki.

**Comment by Lukasz-Zurek** [comment]
Deklarowany czas wysyłki, czyli tzw. **delivery.handlingTime** uzyskasz w odpowiedzi na szczegóły oferty w [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET). Dodam jednak, że nie pobierzesz danych o (ustalonym wcześniej w ofercie) czasie wysyłki dla zamówień.

**Comment by kepesian** [comment]
Rozumie , dziękuję. Korzystam. Tego zasobu ale właśnie interesowało mnie jak on wygląda dla konkretnego zamówienia czy jest możliwość pobrania wartości z oferty z chwili zamówienia, czyli taki wgląd jak możliwy jest poprzez www oglądasz ofertę z dnia zakupu. Jeżeli tego nie można uzyskać to jednym słowem pozostaje własne rejestrowanie tego czasu. Dziękuję
