### ISSUE TITLE
Problem podczas aktualizacji opisu aukcji

### ISSUE THREAD

**Issue by ircoo2022** [allegro/allegro-api#7048]
Witam,

object(stdClass)#5 (1) { ["errors"]=> array(1) { [0]=> object(stdClass)#4 (5) { ["code"]=> string(16) "VALIDATION_ERROR" ["message"]=> string(19) "Invalid HTML subset" ["details"]=> string(24) "Invalid value: Test Test" ["path"]=> string(40) "description.sections[0].items[0].content" ["userMessage"]=> string(19) "Invalid HTML subset" } } }

takie coś zwraca api podczas aktualizacji opisu aukcji ... "https://api.allegro.pl/sale/product-offers/ID_AUKCJI

kod to < p >dsdadasdas fsdf 111< / p ><p>ddasdadasd 222< / p >

oczywuśice zdanie dłuższe ale jak damy osobno każdy  < p >dsdadasdas fsdf 111< / p >

i osobno aktualizcje  opisu < p >ddasdadasd 222< / p >

(oczywiście nie ma spacji w < p > itd bo tutaj inaczej kodu html nie wstawię

to przechodzi  a razem nie ...

Czy mogą państwo to zdebugować bardziej???

**Comment by ircoo2022** [comment]
Podczas wystawiania mamy błąd:

Co zobaczy ?

array(1) { [0]=> object(stdClass)#78 (5) { ["code"]=> string(32) "ImpliedWarrantyNotFoundException" ["message"]=> string(20) "Unprocessable Entity" ["details"]=> NULL ["path"]=> string(34) "afterSalesServices.impliedWarranty" ["userMessage"]=> string(55) "The user does not have Complaints Terms named: default." } } object(stdClass)#92 (1) { ["errors"]=> array(1) { [0]=> object(stdClass)#78 (5) { ["code"]=> string(32) "ImpliedWarrantyNotFoundException" ["message"]=> string(20) "Unprocessable Entity" ["details"]=> NULL ["path"]=> string(34) "afterSalesServices.impliedWarranty" ["userMessage"]=> string(55) "The user does not have Complaints Terms named: default." } } }

**Comment by Lukasz-Zurek** [comment]
@ircoo2022 Komunikat "The user does not have Complaints Terms named: default." świadczy o tym, że najprawdopodobniej posiadasz kilka różnych wariantów w warunkach reklamacji. Nie posiadasz natomiast wariantu o takiej nazwie, dlatego zwracamy błąd 422. Jeżeli posiadasz konto firma i po jednej opcji dla tych pól, to przypiszemy ją do oferty. Natomiast w przypadku większej liczby warunków reklamacji czy zwrotów, użyjemy wariantu o nazwie **default**.
