### ISSUE TITLE
Nadanie przesyłki InPost - wybór sposobu nadania

### ISSUE THREAD

**Issue by JamesFordV3** [allegro/allegro-api#7049]
Występuje problem:
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [X] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/

:beetle: **Opis / Description**
Na allegro https://allegro.pl/moje-allegro/sprzedaz/wysylam/nadaj-paczke?orderId=... dla serwisów dostawy InPost istnieje możliwość wyboru sposobu nadania paczki:
![obraz](https://user-images.githubusercontent.com/45076392/236623300-2c3d280b-b98c-4602-920e-91e43f9fafa0.png)

"Nadam przesyłkę w paczkomacie/Nadam przesyłkę w paczkopunkcie" (jak na screenie wyżej). 
Za pośrednictwem api używając komendy:
https://developer.allegro.pl/documentation/#operation/createNewParcel

nie jestem w stanie tego zrealizować - po mojej analizie doszedłem do wniosku że problem leży REST API z parametrami zapytania:
- pickup
- label.sender

`'pointId': 'any_apm'`

pickup przyjmuje stringa "pointId", natomiast label.sender nie (nawet jeżeli go tam podam jest ignorwany przez REST API). I otrzymuję przez to taki oto błąd identyczny do tego tutaj #5354, ale z trochę innej przyczyny

`{'id': '...', 'parcelId': None, 'status': 'ERROR', 'errors': [{'code': 'ERROR', 'message': '"Inne dane na etykiecie" not supporter for carrier', 'details': None, 'path': 'label.sender', 'userMessage': "Opcja 'Inne dane na etykiecie' nie są dostępne dla wybranego przewoźnika"}]}`

Sprawdzałem różnice i na allegro sprzedaz/wysylam/nadaj-paczke w "waszym API" "point" jest przekazywany zarówno w pickup jak również label.sender przez co z waszej stronki jest to możliwe, natomiast przez REST API jeżeli chodzi o InPost możliwa jest tylko ta pierwsza opcja: `Zamówię podjazd kuriera` bo ucinacie "pointId" w label.sender i InPost sie pulta że są inne dane na etykiecie.

Prosiłbym o dodanie obsługi tego 'pointId' w label.sender do REST API oraz do dokumentacji.

Poniżej trace-id jeżeli potrzebny
`'trace-id': '5cdee339a1656f6a'`

**Comment by MartaNowaczyk** [comment]
Możesz nadać przesyłkę w punkcie odbioru jeśli podasz konkretny ID punktu dla "pickup.pointId". Dla "label.sender" dodałeś pole "pointId": "any_apm", które nie jest zgodne z naszą [dokumentacją](https://developer.allegro.pl/documentation/#operation/createNewParcel). Poza tym dane dla "label.sender" możesz pominąć.

**Comment by JamesFordV3** [comment]
Pomogło ustawienie label.sender na None

Dziękuję
