### ISSUE TITLE
/offers/listing/  po id produktów

### ISSUE THREAD

**Issue by PunktAutoCzesci** [allegro/allegro-api#7051]
zasób:  **/offers/listing/**

Cześć, 
chciałbym używać tej metody do analizy cen konkurencji. Czyli według listy moich ofert porównywać ceny konkurencji. 

W związku z tym mam kilka pytań: 

**1.** Czy istnieje metoda / filtr pozwalający na wyszukanie ofert konkurencyjnych do wskazanej oferty?
Chciałbym uzyskać coś na wzór listy która pojawia się w ofercie po kliknięciu "Inne oferty tego produktu" "najtańsze" 
**2.** Czy istnieje filtr pozwalający wyszukać oferty połączone z konkretnym produktem? 
   Np. po identyfikatorze produktu Allegro. 

Nie widzę, żeby zwracany obiekt "items" zawierał id połączonego z ofertą produktu.
Ewentualnie proszę o sugestię w jaki sposób mogę uzyskać podobny efekt. 
Dziękuję.

**Comment by PunktAutoCzesci** [comment]
Dostęp mam.

Myślę, że warto by było pomyśleć o takiej metodzie. Produktyzacja na Allegro to już niemal 100% ofert. Dodatkowo w 1 ofercie może być przypięty więcej niż jeden produkt. 

Proszę o wskazówkę jak ustawić filtry. 
Szukany produkt: Klocki hamulcowe marki TRW nr katalogowy GDB1330


Jak na razie najlepsze co wymyśliłem to:

filtr na szukaną kategorię 
searchMode:   'REGULAR'
tylko KupTeraz
fallback: 'false'
parametr nowe
szukany string:  "TRW" "GDB1330"

W większości przypadków działa dlatego, że listing znajduje oferty po parametrach identyfikujących:
Producent części:    TRW
Numer katalogowy części:    GDB1330

Niestety wyniki zawierają też oferty gdzie parametr numer katalogowy części to  "DF2805 GDB1330"

Wady takiego rozwiązania to: 
1. Oferty tego produktu mogą znajdować się też w kategoriach podobnych. Trzeba by przeszukiwać każdą z kategorii podobnych. (do zrobienia)
2. wyniki nie zawsze są trafne wyniki jeśli w numerze katalogowym znajdują się też inne wartości.

Jakiś pomysł jak skonstruować zapytanie dla tego przypadku?

**Comment by rtnet-pl** [comment]
Możesz odczytać EAN z Twojej oferty i następnie przeszukać listing wg EAN (działa).
