### ISSUE TITLE
Aktywacja kont - środowisko testowe

### ISSUE THREAD

**Issue by mateuszluczak1996** [allegro/allegro-api#7057]
Dzień Dobry, 
Poproszę o aktywacje kont:
- mail: mateuszluczak1996@gmail.com, login: woochuck, konto firmowe
- mail: mateuszek99918@wp.pl, login: mateuszluczak, konto zwykłe.

Pytanie poboczne, czy jest to jedyna rzecz, którą muszę zrobić aby móc dodać oferty na allegro sandbox z konta firmowego, i potem z konta zwykłego zasymulować kupno? Obecnie nie jestem w stanie dodawać ofert z powodu braku weryfikacji.

Pozdrawiam
Mateusz

**Comment by MartaNowaczyk** [comment]
Z tego co widzę, dla konta **woochuck** masz wybraną niepełną opcję sprzedażową. Wejdź proszę do [ustawień konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy), skorzystaj z linku, który masz na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)" i wybierz "Weryfikacja pełna". Uzupełnij dane i prześlij dowolne pliki.

Konto **mateuszluczak** to konto zwykłe - aby je aktywować, wykonaj symulację przelewu weryfikacyjnego w [Moje konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto).

**Comment by danielev-qapla** [comment]
Hello, is it possibile to activate another sandbox business account ?
My login is QaplaSandbox, it was a regular account that I converted to a business account.
I think I did all the steps needed for sales activation, and I inserted "fake" data.
The "set payouts" and "company verification" are still in progress. Can you please activate it?

Let me know if I should open a new thread in English and/or if you need some other details for activating my account.
Thanks in advance.

Regards,
Daniele

**Comment by mateuszluczak1996** [comment]
> @MartaNowaczyk jeśli chodzi o konto firmowe, to w oczekiwaniu mam:
- krok 2. "Ustaw wypłaty środków"
- krok 3. "Weryfikacja firmy"
<img width="1260" alt="Screenshot 2023-05-09 at 19 44 00" src="https://github.com/allegro/allegro-api/assets/49898815/64d20c7e-ae7a-4415-ad3c-2572a87eba7e">
Czy muszę poczekać odpowiednią ilość czasu, czy powinno być automatycznie zaakceptowane?
Dodam też, że początkowo było to konto klienckie zmienione na firmowe, więc może jest to podobny problem do wątku #7059 

Przy próbie wystawienia produktu mam:
<img width="993" alt="Screenshot 2023-05-09 at 19 47 39" src="https://github.com/allegro/allegro-api/assets/49898815/09db6830-73b5-4cde-b973-bf186434faaf">

Mam konto firmowe, nie wiem co oznacza niepełna opcja sprzedażowa.

**Comment by MartaNowaczyk** [comment]
Zmieniłeś na pełną weryfikację, dlatego mogłam aktywować Twoje konto firmowe. Teraz powinno być wszystko ok.

**Comment by mateuszluczak1996** [comment]
> Zmieniłeś na pełną weryfikację, dlatego mogłam aktywować Twoje konto firmowe. Teraz powinno być wszystko ok.

Rozumiem, teraz już przechodzi mi do formularza wystawiania na koncie firmowym, dziękuje za pomoc @MartaNowaczyk 🥇
