### ISSUE TITLE
REST API docs url 

### ISSUE THREAD

**Issue by kriukovalex** [allegro/allegro-api#7058]
there is no page https://developer.allegro.pl/en/auth/
Q: how to get token from other soft (accounting soft 1c ) to use your api? Can we do it whithout interactive action?

**Comment by kriukovalex** [comment]
We want to do it automaticaly without user

**Comment by Lukasz-Zurek** [comment]
@kriukovalex You can change a language of our site: https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR right here:

<img width="505" alt="Zrzut ekranu 2023-05-9 o 12 37 02" src="https://github.com/allegro/allegro-api/assets/78350270/a9c8e2d0-0172-4b44-91ea-b67b1faaffdc">

The only authorization method which allows you to authorize the application **without the user's consent** is [Client_credentials flow](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#client-credentials-flow) - but please note that it is intended for resources that allow access to public data only, e.g. downloading a list of categories. So without user context you will not check the list of orders or offers, or list an offer, create a product, etc.

We recommend [Authorization code flow](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow), but I suggest reading about all of the available methods.

Another important thing is [Extending token validity](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#extending-token-validity). We make it possible to refresh tokens by refresh_token which is used to obtain a new access token for the user without the need for the user to perform any actions. Such a token is valid for 3 months and after first refresh, you can use it for another 60 seconds.

**Comment by kriukovalex** [comment]
What method can i use to update price and stocks? Could you please give me a sample of json?

**Comment by Lukasz-Zurek** [comment]
@kriukovalex If you want to update price and stock in multiply offers, you will read about it right [here](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#editing-many-offers). You will find there also sample requests and responses in json. 

We described offer management resources in [our tutorial](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3), so I recommend reading the tutorial. There you will find all the information, as well as documentation, faq, etc.
