### ISSUE TITLE
Prośba o aktywacje konta

### ISSUE THREAD

**Issue by tomaszkuczewski** [allegro/allegro-api#7059]
Dzień dobry,

Założyłem konto firmowe (a dokładnie przetransferowałem konto osobiste, na firmowe) na allegro-sandbox, przeszedłem proces weryfikacji, a konto oznaczone jest jako zweryfikowane. Ostatnim etapem do realizacji na profilu jest złożenie oferty. Niestety przy użyciu strony internetowej dostaje powiadomienie, aby "Aby aktywować sprzedaż zweryfikuj konto.".  Problem zgłaszałem do wsparcia allegro jakiś czas temu, na razie bez odzewu więc próbuje tutaj.

login: sajmoner
email: tomaszkuczewski9@gmail.com

Proszę o pomoc

**Comment by Lukasz-Zurek** [comment]
Wiemy o Twoim zgłoszeniu. Niestety jest to dość problematyczny przypadek. Temat ponownie przekazałem do właściwego zespołu odpowiedzialnego za ten proces. Jak tylko dowiem się czegoś więcej, wrócę do Ciebie z informacją bezpośrednio w tym wątku.

**Comment by Lukasz-Zurek** [comment]
@tomaszkuczewski Udało mi się aktywować Twoje konto. Sprawdź proszę czy wszystko działa :)
