### ISSUE TITLE
Nie działa kasowanie aukcji?

### ISSUE THREAD

**Issue by Krystus** [allegro/allegro-api#706]
Zgodnie z dokumentacją chcę skasować aukcję.

$offerResponse = $allegro->put('/sale/offer-publication-commands/'.$auction->uuid, 'public', $data);

```
$data = [
            'publication' => [
                'action' => 'END',
            ],
            'offerCriteria' => [
                [
                    'offers' => [
                        ['id' => $auction->uid],
                    ],
                    'type' => 'CONTAINS_OFFERS',
                ]
            ]
        ];
```

Niestety aukcja nie zmienia statusu. Cały czas jest dostępna w serwisie.

![screen shot 2018-10-04 at 15 03 35](https://user-images.githubusercontent.com/15039636/46476719-23feab00-c7e9-11e8-9a11-ad2043528171.png)

**Comment by Krystus** [comment]
Jasne, chodziło mi o jej zakończenie. Pop 20 minutach aukcja nadal wisi normalnie z Kup teraz i Dodaj do koszyka tak więc coś tu nie gra. Nie ma żadnego błędu. Ot. operacja przeszła. Status jej się nie zmienia po sprawdzeniu GET.

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619):
- pełnego cURL-a z PUT /sale/offer-publication-commands/{commandId} wraz z traceID i responsem
- a także taki sam zestaw danych dla GET /sale/offer-publication-commands/{commandId}/tasks
W treści zgłoszenia zaznacz proszę, że informacje są na potrzeby zgłoszenia na GitHuie numer 706.
Sprawdzimy w czym jest problem.

**Comment by PawelTaberski** [comment]
Prosiłbym abyś jeszcze raz podesłał te dane tym razem pełne wraz z numerem oferty itp. Podaj również jaki jest id usera dla jakiego wykonujesz daną czynność. Niestety z tych danych nie wynika za wiele. Nie wiem jaką ostateczne ofertę podstawiasz pod tą zmienną, w imieniu jakiego użytkownika Twoja aplikacja wykonuje te zadanie itp.

**Comment by Krystus** [comment]
@PawelTaberski kasuję aukcję o id: 7505840159, kasuję w imieniu seller_id: 46413766.

Wysyłam z takim body:

```
array:2 [▼
  "publication" => array:1 [▼
    "action" => "END"
  ]
  "offerCriteria" => array:1 [▼
    0 => array:2 [▼
      "offers" => array:1 [▼
        0 => array:1 [▼
          "id" => 7505840159
        ]
      ]
      "type" => "CONTAINS_OFFERS"
    ]
  ]
]
```

Odpowiedź jak we wcześniejszym komentarzu.

W /tasks nic poza taką zwrotką:

```
{#1657 ▼
  +"tasks": array:1 [▼
    0 => {#1656 ▼
      +"offer": {#1655 ▶}
      +"message": ""
      +"status": "SUCCESS"
      +"scheduledAt": "2018-08-12T02:54:00.001+02:00"
      +"finishedAt": "2018-08-12T02:54:00.803+02:00"
      +"field": "publication"
    }
  ]
}
```

**Comment by PawelTaberski** [comment]
Podeślij proszę jeszcze traceId zadania zakończenia oferty.

**Comment by Krystus** [comment]
@PawelTaberski minutę temu, ta sama aukcja co wyżej.

```
{#1655 ▼
  +"id": "ff5e4106-191e-4d70-9092-9b7bd1f420f3"
  +"taskCount": {#1656 ▼
    +"total": 0
    +"success": 0
    +"failed": 0
  }
}
```

**Comment by PawelTaberski** [comment]
Nie chodzi mi o UUID danego zadania, który nadajesz lokalnie a o wartość nagłówka jaki dostajesz w odpowiedzi w polu Trace-Id. Dzięki niemu będziemy w stanie wyśledzić Twojego requesta.

**Comment by PawelTaberski** [comment]
Przekazałem informacje jakie podałeś do odpowiedniego zespołu. Postarają się zweryfikować w czym jest problem. Proszę o cierpliwość.
