### ISSUE TITLE
[PROBLEM] - REST API ALLEGRO - Wapro (moduł aukcje) - AUTORYZACJA

### ISSUE THREAD

**Issue by Ostrowski-Hydrosan** [allegro/allegro-api#7061]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam, mam problem z integracją po REST API Allegro z Wapro (moduł aukcje) - W piątek wszystko się autoryzowało a dzisiaj mam stroną błędu allegro z numerem błędu: ea617e2945eab78d. Proszę o pomoc albo jakieś wskazówki :)

**Comment by MartaNowaczyk** [comment]
Witam, w logach widzę, że podajesz nieprawidłowy redirect_uri, stąd błąd. Prawidłowy znajdziesz [na stronie do zarządzania aplikacjami allegro](https://apps.developer.allegro.pl/).

**Comment by Ostrowski-Hydrosan** [comment]
Nie mogę zmienić adresu przekierować, ponieważ autoryzację obsługuje Wapro i to ich adres jest podany. Jest jakiś inny sposób, żeby autoryzacja przebiegła poprawnie po Waszej stronie?

**Comment by MartaNowaczyk** [comment]
Nie ma, adres przekierowań musi być poprawny, czyli dokładnie taki, jaki jest widoczny przy danej aplikacji. W takim razie skontaktuj się z Wapro i ustalcie, który adres powinien być używany, albo poprawią na ten, który jest dodany na stronie z aplikacjami, albo trzeba zmienić redirect-uri poprzez edycję [na stronie do zarządzania aplikacjami](https://apps.developer.allegro.pl/). Ja po swojej stronie tego adresu nie mogę zmienić.

**Comment by Ostrowski-Hydrosan** [comment]
Poszło, rzeczywiście coś było nie tak z redirect-url.. Dziękuję za pomoc!
Pozdrawiam!
