### ISSUE TITLE
Parametry produktów

### ISSUE THREAD

**Issue by gufio** [allegro/allegro-api#7062]
Witam. Tworzę produkt i dany parametr ma takie właściwości:

"requiredForProduct": true,
"customValuesEnabled": false
"ambiguousValueId": "204669_221445"

Czy podanie wartości ambiguousValueId np. w tym wypadku "pozostale" jest niedopuszczalne? Dla zwykłej oferty, bez tworzenia produktu jest to dopuszczalne? Czy jest gdzieś informacja w dokumentacji na temat wartości niejednoznacznych (ambiguousValue) przy tworzeniu ofert i produktów?

**Comment by MartaNowaczyk** [comment]
Jeżeli parametr jest wymagany, to nie ma znaczenia czy masz ofertę z produktem czy bez - trzeba go podać. 
Gdy w "customValuesEnabled" masz "false", to w danym  parametrze nie możesz dodać własnej wartość dla parametru z wartością niejednoznaczną.
W dokumentacji, dla [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2), znajdziesz opis zwracanych pól. 
W naszym [poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasna-wartosc-parametru) znajdziesz opis dla własnej wartości parametru.

**Comment by hahyes** [comment]
@gufio Z reguły wartości bliżej nieokreślone nie są dopuszczalne w katalogu. Ma to jakiś tam sens - produkt ma konkretne parametry a nie jakieś nieznane, pozostałe, inne itd.
