### ISSUE TITLE
Klucze ESD

### ISSUE THREAD

**Issue by fabMoth4n** [allegro/allegro-api#7064]
Witam,

w jaki sposób obsługuje się przez API wysyłkę kluczy ESD do klienta? Jest jakaś metoda do tego, czy zwyczajnie wysłac mu maila na adres  xxxxxx@allegro.pl ?

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Mamy [metody do komunikowania się z kupującymi](https://developer.allegro.pl/tutorials/jak-zarzadzac-centrum-wiadomosci-XxWm2K890Fk#nowa-wiadomosc), tzw. Centrum wiadomości. Taki klucz można też wysyłać na maila, przypisanego do danego zamówienia.
