### ISSUE TITLE
Co to jest za marketplace: allegro-cz-fnf ???

### ISSUE THREAD

**Issue by javaguru-pl** [allegro/allegro-api#7065]
Taki marketplace pojawił się w jednym z zamówień i został zapisany w tabeli.
Następnie przy pobieraniu billingów okazuje się że billingi dla marketu allegro-cz-fnf pokrywają się z billingami allegro-pl.
Można wywołać metodę GET /billing/billing-entries i łatwo się przekonać że zwraca te same billingi dla allegro-pl oraz allegro-cz-fnf.
Czyżbyśmy wracali do czasów WebAPI i "czarnych czwartków"? - kiedy to nigdy nie było pewności co dzisiaj zwróci WebAPI??? ;)

P.S. wracając do mojej sugestii #7006 , jeżeli już wymagacie podania marketu w /billing/billing-entries przynajmniej dopracujcie tę metodę aby zwracała właściwe dane. Lub zastosujcie się do mojej sugestii #7006 i nie będzie problemu z dublowaniem billingów.
Z góry dziękuję za odpowiedź na pytanie lub ew. pozytywne rozpatrzenie mojej prośby.

**Comment by MartaNowaczyk** [comment]
@javaguru-pl podaj proszę ID tego zamówienia lub trace-id dla tego przypadku.

**Comment by javaguru-pl** [comment]
Podaję poniżej trace-id:
f1a5ad1e4a9fad73

**Comment by MartaNowaczyk** [comment]
W każdym zamówieniu z tego zapytania widzę tylko serwis "allegro-pl". Mamy w tym momencie dostępne tylko dwa serwisy allegro-cz i allegro-pl. Gdy pobierasz dostępne serwisy nie powinno być nic więcej.  Sprawę tę zgłosiłam do odpowiedniego zespołi. Jeśli w jakimś zamówieniu pojawia się "allegro-cz-fnf" podaj proszę konkretne zamówienie - choć nie powinno się to zdarzyć. Ogólnie "allegro-cz-fnf" zwraca wszystko co dotyczy allegro-pl, stąd dostajesz te same dane.

**Comment by MartaNowaczyk** [comment]
Możesz jeszcze podać trace-id, dla przypadku w którym widzisz nieprawidłowy marketplace?

**Comment by javaguru-pl** [comment]
Witam Pani Marto, niestety nie jesteśmy w stanie zlokalizować rekordu który odwołuje się do tego marketplace. Prawdopodobnie został już usunięty (np. po pewnym czasie, usuwamy dane nieaktywnych użytkowników). Mogło to być albo zamówienie, albo billing lub np. sprzedawca dla którego metoda /me zwróciła taki marketplace jako bazowy. Ewentualnie jest możliwe że sama metoda /marketplaces przez jakiś krótki czas zwracała ten dodatkowy market-cz-fnf. Tak czy inaczej ten marketplace na 100% gdzieś się w API pojawił, gdyż inaczej nie byłoby go u nas w tabeli. A ponadto metody API uznają go jako prawidłowy (jeżeli podamy jakiś nieznany market, np. allegro-us to otrzymamy błąd).

**Comment by MartaNowaczyk** [comment]
Witam, dziękuję za informację. w takim razie gdyby jeszcze raz pojawił się ten marketplace, proszę o taką informację, będziemy weryfikować każdy taki przypadek, bo zależy nam by takie sytuacje nie miały miejsca.
