### ISSUE TITLE
GET /sale/delivery-methods - te same metody dostawy na różnych ID

### ISSUE THREAD

**Issue by enp-aszuszkiewicz** [allegro/allegro-api#7066]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**

Na endpoincie `GET /sale/delivery-methods` zaczęliśmy otrzymywać dwa razy te same metody dostawy pod różnymi ID. Rzecz dotyczy:
- Przesyłka kurierska - id `7203cb90-864c-4cda-bf08-dc883f0c78ad` i `0a89df8d-b806-41b3-b4d7-d537ca868995`
- Przesyłka kurierska pobranie - id `1a89df8d-947b-40ee-bfdc-d537ca868995` i `845efe05-0c96-47c3-a8cb-aa4699c158ce`

Prośba o info czy to błąd czy celowe działanie? Jak mamy tą sytuację potraktować?

**Comment by MartaNowaczyk** [comment]
To celowe działanie. Metoda dostawy jest przeznaczona na dwa różne rynki, rozpoznasz to po wartości w polu "marketplaces".
