### ISSUE TITLE
GET request with access token

### ISSUE THREAD

**Issue by gokunull** [allegro/allegro-api#7068]
Hello! I'm new with API. Could you please explain what I'm doing wrong?

I want to test a GET request with the code below, but every time I get `<Response [406]>`.

**Code:** 
```
import requests
import json

CLIENT_ID = 'ID'
CLIENT_SECRET = 'SECRET'

TOKEN_URL = "https://allegro.pl/auth/oauth/token"
ALLEGRO_URL = "https://api.allegro.pl/sale/offers"

def get_access_token():
    try:
        data = {'grant_type': 'client_credentials'}
        access_token_response = requests.post(TOKEN_URL, data=data, verify=False, allow_redirects=False, auth=(CLIENT_ID, CLIENT_SECRET))
        tokens = json.loads(access_token_response.text)
        access_token = tokens['access_token']
        return access_token
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)

def main():
    access_token = get_access_token()
    head = {'Authorization': 'Bearer {}'.format(access_token)}
    response = requests.get(ALLEGRO_URL, headers=head)
    print(response.json())

if __name__ == "__main__":
    main()
```

**Terminal output:**
```
/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'allegro.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
{'errors': [{'code': 'NotAcceptableException', 'message': "Not acceptable representation requested. Please check 'Accept' request header", 'details': None, 'path': None, 'userMessage': 'Request contains invalid data. Contact the application author.'}]}
```

**Comment by gokunull** [comment]
@Lukasz-Zurek thanks for the explanation.

One last question about `redirect_uri`. What exactly should I use there? If I just want to use python code from the terminal to test API capabilities, how can I do that? In the future I want to use flask for web access, but right now terminal output is enough for me.

Because if I use localhost, I can get only like, 
```Server started http://localhost:8080
127.0.0.1 - - [10/May/2023 16:13:33] "GET /?code='code' HTTP/1.1" 200 -```

Thanks you in advance.

**Comment by Lukasz-Zurek** [comment]
@gokunull I see that you have sent an update about device authorization. But if you have any additional questions, please don't hesitate to ask.

**Comment by zhangliangce** [comment]
Hello! I got a access_token but unuseful.Because it change every second.How to get refresh_token?

**Comment by PrzemyslawLukanowski** [comment]
The access token doesn't change and it is valid for 12 hours. Through authorization flow, we always return two tokens in the response: access and refresh. You can read more about using refresh tokens in [our tutorial.](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#extending-token-validity)
