### ISSUE TITLE
Błąd offer-price-change-command dla allegro-cz

### ISSUE THREAD

**Issue by promsters** [allegro/allegro-api#7070]
Występuje problem:
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Cześć :)

Czasami price-change-commandy dla czeskiego marketplace nie zostają zrealizowane i kończą z takim statusem:
```
"tasks": [
		{
			"offer": {
				"id": "13665026353"
			},
			"message": "OPERATION_FAILED",
			"status": "FAIL",
			"scheduledAt": "2023-05-10T15:17:13.431Z",
			"finishedAt": "2023-05-10T15:17:13.422Z",
			"field": "price",
			"errors": [
				{
					"code": "VALIDATION_FAILED",
					"message": "prices.price.currency.incorrectBaseCurrency",
					"details": null,
					"path": "prices[0].price.currency",
					"userMessage": "Currency is not valid for this marketplace."
				}
			]
		}
	]
}
```

Body requestu dla powyższego commanda:
```
{
	"offerCriteria": [
		{
			"offers": [
				{
					"id": "13665026353"
				}
			],
			"type": "CONTAINS_OFFERS"
		}
	],
	"modification": {
		"type": "FIXED_PRICE",
		"marketplaceId": "allegro-cz",
		"price": {
			"amount": "14327",
			"currency": "CZK"
		}
	}
}
```

CommandId: `76483852-9335-4211-b118-89fbdb000a75`
TraceId: `53df40779b41cb0b`

Ten sam command ponowiony po chwili zostaje poprawnie przetworzony.
Dodatkowo mam wrażenie, że ten błąd występuje w sytuacji gdy wysyłamy dwa commandy jeden po drugim - najpierw dla allegro-pl a potem dla allegro-cz.

Dorzucam też traceId poprzedniego command dla allegro-pl: `240e21fc3a27a12`

**Comment by MartaNowaczyk** [comment]
Cześć, dzięki za zgłoszenie. Zweryfikuję opisaną sytuację i wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Potwierdzamy problem, zespół odpowiedzialny za tę funkcjonalność będzie wprowadzał odpowiednią poprawkę. Przepraszamy za niedogodności.

**Comment by MartaNowaczyk** [comment]
Jeszcze tylko dodam, że błąd występuje tak jak napisałeś, gdy wyślesz requesty jeden po drugim, a poprzednia zmiana nie została jeszcze zapisana.

**Comment by promsters** [comment]
Super, dzięki za szybką weryfikację. Czy mogę Cię prosić o informację tutaj po tym jak poprawka zostanie wprowadzona?

**Comment by promsters** [comment]
@MartaNowaczyk coś w tym temacie się udało zrobić?

**Comment by MartaNowaczyk** [comment]
@promsters wdrożyliśmy poprawkę, błąd nie powinien już występować.

**Comment by promsters** [comment]
@MartaNowaczyk Potwierdzam, błąd już nie występuje. Dzięki :)
