### ISSUE TITLE
Patch exsiting offer to be available on allegro.cz

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#7072]
Hi, I was testing publishing offer on allegro.cz
My baseMarketplace is allegro.pl
I have created offer 13683770931
Offer is active. I have patched the offer in following way
`{
    "publication": {
        "additional": [
            {
                "id": "allegro-cz"
            }
        ]
    },
    "additionalMarketplaces": {
        "allegro-cz": {
            "sellingMode": {
                "price": {
                    "amount": "660",
                    "currency": "CZK"
                }
            }
        }
    }
}`
, but when I GET the offer, the additionalMarketplaces.allegro-cz.publication.state still shows "NOT_REQUESTED"
Could you please advice, what was missed on my side?

Thanks

Jirka Z

**Comment by Lukasz-Zurek** [comment]
I see that you don't provide **"marketplaces"** section, above **"additional.id"** field. It should look like this:

```
{
 "publication": {
     "marketplaces": {
       "additional": [
              {
              "id": "allegro-cz"
              }
       ]
     }
 },
   "additionalMarketplaces": {
      "allegro-cz": {
         "sellingMode": {
            "price": {
               "amount": "660",
               "currency": "CZK"
            }
         }
      }
   }
}
```
Then it should work (if the offer meets the qualifications).

**Comment by ZajdaBear** [comment]
Hi Lukasz, thanks for quick help. Works fine.
