### ISSUE TITLE
PUT /sale/offer-modification-commands/{commandId} - publikacja na allegro.cz

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#7073]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Próbuję zgodnie z dokumentacją korzystając z metody PUT /sale/offer-modification-commands/{commandId} dla ofert, które są jako NOT_REQUESTED na allegro.cz, wysłać prośbę o ich dodanie:
Request:
```
{
  "modification": {
    "publication": {
      "marketplaces": {
        "additional": {
          "add": {
            "id": "allegro-cz"
          }
        }
      }
    }
  }
  "offerCriteria": array:1 [
    0 => {
      "offers": array:3 [
        0 => {
          "id": "13657810941"
        }
        1 => {
          "id": "13657810664"
        }
        2 => {
          "id": "13657810487"
        }
      ]
      "type": "CONTAINS_OFFERS"
    }
  ]
}
```
Reponse:
```
{
  "errors":  [
    0 => {
      "code": "MESSAGE_NOT_READABLE"
      "message": "Message not readable"
      "details": null
      "path": null
      "userMessage": "Request contains invalid data. Contact the application author."
    }
  ]
}
```

Korzystam z powodzeniem z tej metody jeśli chodzi o modyfikację pola handlingTime i komunikat błędu jest zbyt ogólny, żebym samodzielnie znalazła powód błędu.

**Comment by Lukasz-Zurek** [comment]
W requeście jest kilka błędów:

- w tej części:
```
          "add": {
            "id": "allegro-cz"
          }
```
brakuje tablicy; powinno być:
```
          "add": [
              {
            "id": "allegro-cz"
          }
          ]
```
- brakuje przecinka:
```
  }
  "offerCriteria": [
```
powinno być:
```
  },
  "offerCriteria": [
```
- brakuje przecinków oddzielających oferty, powinno być:
```
           {
               "id": "13657810941"
            },
            {
               "id": "13657810664"
            },
            {
               "id": "13657810487"
            }
```

Żądanie powinno wyglądać tak:

```
{
   "modification": {
      "publication": {
         "marketplaces": {
            "additional": {
               "add": [
                  {
                     "id": "allegro-cz"
                  }
               ]
            }
         }
      }
   },
   "offerCriteria": [
      {
         "type": "CONTAINS_OFFERS",
         "offers": [
            {
               "id": "13657810941"
            },
            {
               "id": "13657810664"
            },
            {
               "id": "13657810487"
            }
         ]
      }
   ]
}
```

**Comment by martacronic** [comment]
Przecinki wszędzie miałam prawidłowo, tylko przy wklejaniu tutaj nie miałam, ale chodziło o tablicę w tablicy "add".

Dziękuję
