### ISSUE TITLE
Lista Wydawnictw 

### ISSUE THREAD

**Issue by Axlii50** [allegro/allegro-api#7074]
Jak mogę pozyskać listę wydawnictw książek wraz z ich id w celu uzupełniania parametru dla https://developer.allegro.pl/documentation#operation/proposeSaleProduct

**Comment by MartaNowaczyk** [comment]
Gdy pobierzesz listę dostępnych parametrów dla danej kategorii [GET /sale/categories/{categoruId}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2) możesz uzyskać listę wydawnictw dostępnych w allegro dla danej kategorii. Jeśli chodzi o ID, to doprecyzuj proszę o jakie ID chodzi.

**Comment by MartaNowaczyk** [comment]
Gdy pobierzesz parametry dla danej kategorii np. GET /sale/categories/66791/parameters otrzymasz parametr "Wydawnictwo":
```
           "id": "223541",
            "name": "Wydawnictwo",
....
```

oraz listę dostępnych wartości dla tego parametru - poniżej niewielka część ze zwracanych wartości słownikowych:

 ```
"dictionary": [
                {
                    "id": "223541_1111753",
                    "value": "12 Posterunek",
                    "dependsOnValueIds": []
                },
                {
                    "id": "223541_569389",
                    "value": "2+3D",
                    "dependsOnValueIds": []
                },
                {
                    "id": "223541_591369",
                    "value": "2K Consulting",
                    "dependsOnValueIds": []
                },
                {
                    "id": "223541_309965",
                    "value": "2ryby.pl",
                    "dependsOnValueIds": []
                },
                {
                    "id": "223541_302853",
                    "value": "3.49 Oficyna Wydawnicza",
                    "dependsOnValueIds": []
                },
                {
                    "id": "223541_1086254",
                    "value": "30. Plenum Spółdzielni Zenum",
                    "dependsOnValueIds": []
                },
                ...
}
```

**Comment by Axlii50** [comment]
Oo dokładnie o coś takiego mi chodziło, lecz niestety w dokumentacji tego bezpośrednio nie ma 
dziękuje bardzo
