### ISSUE TITLE
UnableToSetCustomValueWithoutAmbiguousValueException

### ISSUE THREAD

**Issue by Axlii50** [allegro/allegro-api#7075]
Witam mam problem z uzupełnianiem wartosci dla parametrów 
sam parametr wygląda następująca 
{"id":"75","values":["miękka"],"valuesIds":["75_1"],"options":{"ambiguousValueId":"75_314838"}}
id parametru 
nazwa w values oraz id tego wszystko jest zaczerpnięte z realnych produktów z allegro 
lecz nadal dostaje błąd w postaci 
{"errors":[{"code":"UnableToSetCustomValueWithoutAmbiguousValueException","message":"Okładka","details":null,"path":null,"userMessage":"Nie można podać propozycji wartości dla parametru Okładka bez wybierania wartości niejednoznacznej"}]}
pomimo ze jest nawet uzupełnione ambiguousValueId

**Comment by MartaNowaczyk** [comment]
Aby odpowiednio zweryfikować opisaną sytuację najlepiej podaj trace-id dla danego wywołania z błędem, albo prześlij request, który wysyłasz. Sprawdź też czy wysyłasz poprawną strukturę dla własnej wartości, opisaliśmy to szczegółowo w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasna-wartosc-parametru). W "valuesIds" trzeba podać id wartości niejednoznacznej ("ambiguousValueId"), a w "values" wartość, którą chcesz przekazać, a której nie ma na liście.

**Comment by Axlii50** [comment]
Okej juz rozumiem values oraz ambiguousValueId podajemy tylko w tedy by stworzyc nową wartosc lecz gdy znamy wartosc z słownika to wystarczy id tej wartosci w valueids
