### ISSUE TITLE
Pusta lista wiadomości w wątku

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#7077]
W jakich sytuacjach możliwa jest pusta lista wiadomości w wątku:
`{'limit': 20, 'messages': [], 'offset': 0}`

Przykładowy id wątku na produkcji: RHSmtijbem9xGSJFiPy5MHHahKU7q8lZueF2qEAhiyQ
Metoda: /messaging/threads/{threadId}

**Comment by Lukasz-Zurek** [comment]
Dziękuję za szczegółowe dane. Przekazałem ten konkretny przypadek do dodatkowej weryfikacji. Wkrótce wrócę do Ciebie z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
@tomasz-grzesik Przetestowałem to jeszcze i mogę już potwierdzić, że taka sytuacja jest możliwa wtedy, gdy Nadawca wiadomości napisze wiadomość (wtedy na liście w **GET messaging/threads/RHSmtijbem9xGSJFiPy5MHHahKU7q8lZueF2qEAhiyQ/messages** ta wiadomość jest widoczna), po czym usunie ją (nie będzie ona widoczna dla nadawcy, ale rozmówca czyli adresat będzie ją widział). W tej sytuacji po ponownym odpytaniu wiadomości tej nie będzie już na liście.

**Comment by tomasz-grzesik** [comment]
Dziękuję za wyjaśnienie.
