### ISSUE TITLE
Plik yaml

### ISSUE THREAD

**Issue by sl-aw-ek** [allegro/allegro-api#7078]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X] inny / other

Takie mam pytanie odnośnie pliku yaml, czy przypadkiem w klasie : DeliveryProductOfferRequest czegoś nie brakuje? Wydawało by się, że powinno być tam jeszcze pole shipmentDate?

**Comment by sl-aw-ek** [comment]
@Lukasz-Zurek to proszę przy okazji sprawdzić czy w SaleProductOfferPublicationMarketplacesRequest też czegoś nie brakuje.

**Comment by Lukasz-Zurek** [comment]
@sl-aw-ek Dziękuję. Zweryfikujemy dokumentację pod tym kątem.
