### ISSUE TITLE
Nie działa link aktywacyjny do aktywacji konta na allegro.cz

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#7079]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Link w mailu:
https://t.allegro.cz.allegrosandbox.pl/registrace/?utm_source=notification&utm_medium=After%20signup&utm_campaign=c5171bbd-bb97-4632-b675-35ffae57c6d8&tr_n=finish-signup&tr_id=85b32b66-556f-42d7-9c6d-5f772576ff6e&tr_d=allegro.cz.allegrosandbox.pl&tr_f=/confirm/dc4ea830d9474bc88790a6ca26ec0c83&tr_s=MwG5J84V

"Nie udało się połączyć z serwerem pod adresem „t.allegro.cz.allegrosandbox.pl”."

Dopiero zmiana linku subdomeny na t.allegro.pl.allegrosandbox.pl przyniosła efekt.

**Comment by MartaNowaczyk** [comment]
Dziękuję za zgłoszenie, zweryfikuję opisany problem z linkiem i wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Nie udało mi się powtórzyć opisanej sytuacji. Dodałam również nowe konto, mail z linkiem przyszedł poprawny, a rejestracja odbyła się bez przeszkód.

**Comment by Radeq** [comment]
Mam taki sam problem - e-mail potwierdzający jest w subdomenie `t.allegro.cz.allegrosandbox.pl`, potwierdzam, że rozwiązanie od @tomasz-grzesik zadziałało

**Comment by MartaNowaczyk** [comment]
@Radeq dziękuje za informację, będziemy w takim razie wyjaśniać tę kwestię.

**Comment by tomasz-grzesik** [comment]
@MartaNowaczyk subdomena t.allegro.cz.allegrosandbox.pl nie została skonfigurowana. Wygląda na to, że wystarczy skonfigurować tak jak subdomena t.allegro.pl.allegrosandbox.pl.

**Comment by MartaNowaczyk** [comment]
Tak, dzięki @tomasz-grzesik 
Odpowiedni zespół pracuje już nad poprawą tego.
