### ISSUE TITLE
Integracja stanów magazynowych

### ISSUE THREAD

**Issue by JS1960** [allegro/allegro-api#7080]
Dobry wieczór, potrzebuję dostępu do API Allegro: a konkretniej API Inventory, które umożliwi mi komunikację z platformą Allegro i aktualizację stanów magazynowych z pliku .xml->Allegro. Chcę wykonać skrypt aktualizacyjny: Muszę napisać skrypt, który będzie pobierał plik .xml, analizował go i używał dostępnego API Allegro do aktualizacji stanów magazynowych na platformie. W jakim języku powinien być napisany skrypt, aby obsługiwał dostęp do API Allegro? Chyba, że są już jakieś gotowe rozwiązania dla sprzedawców z których można odpłatnie skorzystać? Chcę aktualizować plik z produktami i stanami magazynowymi jeden raz dziennie.

**Comment by MartaNowaczyk** [comment]
Wybór języka zostawiamy Tobie. Nie wskazujemy też rozwiązań, z których możesz skorzystasz, ponieważ nie mamy na nie wpływu i nie możemy odpowiadać za ich działanie, ale pewnie znajdziesz jakieś w wyszukiwarce internetowej lub ktoś z naszego forum korzysta już z takiego rozwiązania i podzieli się swoimi doświadczeniami.

**Comment by JS1960** [comment]
> potrzebuję dostępu do API Allegro: a konkretniej API Inventory, które umożliwi mi komunikację z platformą Allegro i aktualizację stanów magazynowych z pliku .xml->Allegro. Chcę wykonać skrypt aktualizacyjny

**Comment by MartaNowaczyk** [comment]
Opis w jaki sposób uzyskać dostęp do REST API Allegro znajdziesz na naszej stronie w [dedykowanym poradniku](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#dostep-do-api).
