### ISSUE TITLE
Błąd 404 na GET /sale/offers/{id}

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#7081]
Czy to prawidłowe zachowanie, że na GET /sale/offers/{id} dostaję HTTP 404 z informacją "Tax setting with given percentage not found"? Jak np. teraz mogę pobrać ofertę?

trace-id: 59d848775c45e43b

**Comment by MartaNowaczyk** [comment]
Ofertę możesz jeszcze pobrać za pomocą GET /sale/product-offers/{offerId}. Problem z GET /sale/offers/{offerId} weryfikuję i wrócę z opowiedzią.

**Comment by MartaNowaczyk** [comment]
Potwierdzam błąd po naszej stronie. Odpowiedni zespół będzie wdrażał poprawkę, aby taka sytuacja nie miała miejsca. Za niedogodności przepraszamy.

**Comment by tomylee0** [comment]
Dziękuję i pozdrawiam.
