### ISSUE TITLE
InvalidDefinitionException

### ISSUE THREAD

**Issue by xcg340122** [allegro/allegro-api#7082]
Hello, a lot of data in the recently released offers will prompt exceptions. Approximate content: {"errors":[{"code":"InvalidDefinitionException","message":"The request data has an invalid format","details":null,"path" (truncated...)
Because there is no specific error message, there is no way to solve them for the time being, I hope you can help me solve it

**Comment by xcg340122** [comment]
I found that the error came from: `POST https://api.allegro.pl/sale/shipping-rates`, which appeared when creating the shipping rate template. The following is the submitted JSON data structure:
```json
{
     "name": "49.00",
     "rates": [
          {
               "deliveryMethod": {
                    "id": "7203cb90-864c-4cda-bf08-dc883f0c78ad"
               },
               "maxQuantityPerPackage": "1",
               "firstItemRate": {
                    "amount": "49.00",
                    "currency": "PLN"
               },
               "nextItemRate": {
                    "amount": "0",
                    "currency": "PLN"
               },
               "shippingTime": "P5D"
          }
     ]
}
```

**Comment by Lukasz-Zurek** [comment]
You have provided **"shippingTime"** field incorrectly. You should provide it together with **"from"** and to **"fields"**, for example:

```
            "shippingTime": {
                "from": "PT72H",
                "to": "PT120H"
            }                                
        }
```

**Comment by xcg340122** [comment]
> 您错误地提供了**“shippingTime”**字段。**您应该将它与"from"**和 to **"fields"**一起提供，例如：
> 
> ```
>             "shippingTime": {
>                 "from": "PT72H",
>                 "to": "PT120H"
>             }                                
>         }
> ```

Thank you. That's taken care of
