### ISSUE TITLE
Integracja Baselinker (jak sprawdzić poprawność integracji) 

### ISSUE THREAD

**Issue by malolatt** [allegro/allegro-api#7083]
Dzień dobry, w dniu wczorajszym wyrażałem klientowi integracje Allegro z baselinkerem. W celu sprawdzenia poprawności działania integracji dokonałem zakupu z jego starego konta. Czy mam zglosic oficjalne gdzieś te testy żeby konto klienta nie zostało zablokowane za naruszenie regulaminu? Chciałbym żeby odpowiedziała mi osoba która zna się na integracjach, a nie pracownik który podpiera się regulaminem.

**Comment by Lukasz-Zurek** [comment]
Jeżeli chodzi o wszelkiego rodzaju testy, dedykowanym środowiskiem do ich wykonywania jest [Allegro Sandbox](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#srodowisko-testowe). Nie mamy żadnej procedury zgłaszania kont do testów na Allegro.pl.
