### ISSUE TITLE
allegro.cz dostawa do punktu odbioru a kraj

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#7084]
Pytanie dotyczy zakupu przez serwis zagraniczny Allegro.cz https://github.com/allegro/allegro-api/issues/7069

Klient kupił przedmiot i wybrał metodę dostawy "Allegro Wysyłka z Polski do Czech - Automaty Paczkowe Packeta "

W `/order/checkout-forms/{id}` w obiekcie delivery.pickupPoint nie ma kraju ( https://developer.allegro.pl/documentation#operation/getOrdersDetailsUsingGET )
![image](https://github.com/allegro/allegro-api/assets/2742214/9d1db935-6e79-4de7-980f-11ffc3a6ca8b)

W delivery.address jest pole countryCode . Czy mogę założyć, że jest to równocześnie kraj punktu odbioru? Bo obawaim się przypadku, że klient poda dane adresowe do Polski a punkt odbioru w Czechach?

**Comment by AureliuszBrussy** [comment]
Faktycznie, może wystąpić sytuacja, o której piszesz - countryCode w polu delivery.address nie musi być zgodny z punktem odbioru. Aktualnie pracujemy nad wdrożeniem pola countryCode w obiekcie delivery.pickupPoint.address. Poinformujemy o takim wdrożeniu.

**Comment by AureliuszBrussy** [comment]
@Radeq wdrożyliśmy zmianę: https://github.com/allegro/allegro-api/issues/7216.
