### ISSUE TITLE
Problem z awizacją przesyłki, której wartość jest wartością dziesiętną.

### ISSUE THREAD

**Issue by inTestowy** [allegro/allegro-api#7085]
Dzień dobry, występuje problem z awizacją przesyłki w walucie PLN, gdy wartość jest wartością dziesiętną. Pojawia się komunikat "Podana waluta nie wspiera wartości dziesiętnych". W innym przypadku, dla wartości całkowitej przesyłka awizuje się. Czym może być spowodowany taki błąd? Czy zmieniło się coś w API odnośnie sposobu lub formatu przekazywania wartości?

**Comment by MartaNowaczyk** [comment]
Dla PLN nie powinno być problemu, ale do pełnej weryfikacji podaj proszę trace-id dla tego błędu.

**Comment by inTestowy** [comment]
{"Key":"trace-id","Value":["3adabce891b0b7f2"]}

**Comment by inTestowy** [comment]
![image (3)](https://github.com/allegro/allegro-api/assets/111511140/b8ea3e31-ea12-4bb3-bbd1-5939ebe7d14b)

**Comment by MartaNowaczyk** [comment]
Dziękuję za dane, sprawdzimy to.

**Comment by MartaNowaczyk** [comment]
Możesz jeszcze podać nr zamówienia dla którego jest ta przesyłka?

**Comment by inTestowy** [comment]
Numer zamówienia: 09eeef70-aeb9-11ed-9727-3def9c1851b1

**Comment by MartaNowaczyk** [comment]
Dziękuję, weryfikujemy to jeszcze, wrócę z informacją.

**Comment by MartaNowaczyk** [comment]
Potwierdzamy, że mieliśmy błąd, ale już nie powinien występować. Dzięki za zgłoszenie i przepraszamy za niedogodności.
