### ISSUE TITLE
Endpoint "/sale/badges" - nie zwraca promocji SMART_WEEK_ALLEOBNIZKA_2023_PL

### ISSUE THREAD

**Issue by PLoO95** [allegro/allegro-api#7086]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Endpoint: /sale/badges nie zwraca promocji SMART_WEEK_ALLEOBNIZKA_2023_PL
https://developer.allegro.pl/documentation#operation/getBadges

**Comment by PLoO95** [comment]
Może podobny case: https://github.com/allegro/allegro-api/issues/6379

**Comment by MartaNowaczyk** [comment]
Tak, to prawidłowe /sale/badges nie zwraca AlleObniżki.

**Comment by PLoO95** [comment]
@MartaNowaczyk 

Dziękuję za szybką odpowiedź. 
Czy to błąd że bramka /sale/badges nie zwraca promocji ?

- Jeżeli tak to na kiedy można się spodziewać wprowadzenia promocji do zasobu API ?
- Jeżeli nie to jak pobrać informacje o tej promocji z API ?

**Comment by PLoO95** [comment]
Proszę o wytłumaczenie mi różnicy pomiędzy tymi promocjami:

- SMART_WEEK_ALLEOBNIZKA_2023_PL
- SMART_WEEK_2023_PL

1. Jakie są różnice ?
2. Dlaczego jedna jest zwracana przez wymieniony zasób API a druga nie ?
3. Dlaczego ostatnio zostało to uznane za błąd przy wdrożeniu ? (https://github.com/allegro/allegro-api/issues/6379)
4. Gdzie mogę znaleźć wyjaśnienie, jak to działa ? Jak zaimplementować takie wyjątki ?

**Comment by MartaNowaczyk** [comment]
1. i 2. To decyzja biznesowa, nie techniczna, stąd tego nie zwracamy po API.
3. Na podstawie decyzji biznesowej nie powinno się to pojawić.
4. Obsługa jest możliwa tylko po stronie www.
