### ISSUE TITLE
[WZA] Problem z wygenerowaniem przesyłki: "Communication error with carrier's API occurred"

### ISSUE THREAD

**Issue by mmodrzejewski** [allegro/allegro-api#7087]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dzień dobry,

Klient nie może wygenerować przesyłki, API zwraca błąd:
`{
"id":"ef00d4c3-7749-4864-a6b4-6565ad8d9169","parcelId":null,"status":"ERROR","errors": 
[{"code":"ERROR","message":"Communication error with carrier's API occurred","details":null,"path":"parcelIds[%s]","userMessage":"Wystąpił błąd komunikacji z API przewoźnika"}
]}
`
Request ID:
ef00d4c3-7749-4864-a6b4-6565ad8d9169

Z danych zlecenia, jedyne co budzi moje podejrzenia, to adres odbiorcy, który jednak jest już w takiej formie w zamówieniu pobieranym z Allegro, w polu ulica: "Dąbrowskiego 3/2/<numer>", gdzie <numer> to kolejna liczba całkowita,

Czy to może być powodem błędu?

Metoda zamówienia  to Allegro Paczkomaty InPost.

**Comment by MartaNowaczyk** [comment]
Zweryfikuję to i wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Nie widzimy zwiększonej ilości błędów, wygląda to na chwilowe problemy przewoźnika.

**Comment by mmodrzejewski** [comment]
A czy ten przypadek, który wkleiłem, to problem z API przewoźnika, czy może był jakiś wewnętrzny komunikat względem zawartości żądania, zwrócony z API Shipx?

**Comment by MartaNowaczyk** [comment]
Nie mam informacji o innym, wewnętrznym komunikacie. Czy nadal masz problem z tą przesyłką?

**Comment by mmodrzejewski** [comment]
Klient próbował generować przesyłkę kilkukrotnie, w dniu 12 maja. Nie udało mu się.
Sprawdziliśmy jego zgłoszenie po weekendzie, w poniedziałek 15 maja, obie próby zwróciły ten sam błąd.
Ostatecznie zamówienie oznaczył w systemie zamówienie jako wysłane, nie mam obecnie informacji czy wygenerował list poza API.

**Comment by MartaNowaczyk** [comment]
12 maja, miał ten sam błąd? Jak tak, to podeślij commandId, albo trace-id. W takim wypadku to nie wygląda na chwilowe problemy przewoźnika.

**Comment by mmodrzejewski** [comment]
Oto  commandId, z 12 maja:

6b816481-fc7f-47dd-90b1-362722553afa

45538aa2-3d21-432b-9065-70cc675314f9

79cccc02-8310-423b-bf24-ad1dd0aa3220

I jeszcze jedna z 15 maja:
19ecb3c2-7a7a-4c90-9ae0-508175c8e286

Rezultat zawsze był ten sam
"Communication error with carrier's API occurred"
