### ISSUE TITLE
Usuwanie usług dodatkowych z istniejącej oferty PUT /sale/offers/:id

### ISSUE THREAD

**Issue by chomik-pawel** [allegro/allegro-api#7088]
Cześć,

Próbowałem używając endpointu PUT /sale/offers/{offerId} usunąć usługę dodatkową 'additionalServices' natomiast jest to  niemożliwe i dostaję 422 z 'VALIDATION_ERROR' 'Selected services do not exist.'

Czy są jakieś inne sposoby do usunięcia usług dodatkowych?

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Cześć, spróbuj wysłać tym samym endpointem dla `additionalServices": null,`
