### ISSUE TITLE
Błąd 401 przy pobieraniu oferty

### ISSUE THREAD

**Issue by kacperKarman** [allegro/allegro-api#7090]
Mam problem podczas użycia zasobu GET /sale/product-offers/:id gdyż praktycznie z dnia na dzień zaczął on zwracać błąd autoryzacji mimo że niczego nie zmieniałem zarówno przy generowaniu tokenu dla mojej aplikacji jak i przy samym użyciu zasobu. 

Czy zostały wprowadzone jakieś zmiany w API które mogą powodować ten problem? 

Konto do którego mam podłączoną moją aplikację to telstar_sklep, natomiast nazwa aplikacji REST API to telstar_app_v3

**Comment by AureliuszBrussy** [comment]
Nie, nie wprowadzaliśmy żadnych zmian w zasobie czy autoryzacji. Przejrzałem logi i widzę, że korzystałeś z access tokena, który już wygasł w wyniku użycia refresh_tokena. Wygląda, jakby Twoja aplikacja nie zapisała nowej pary access i refresh token. 

Aktualnie powinieneś zgłosić się po nową parę tokenów (zgodnie np. z [pkt.1](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#autoryzacja-uzytkownika) dla Authorization Code flow).

**Comment by kacperKarman** [comment]
Ok dziękuję za pomoc. Widzę teraz że z jakiegoś powodu faktycznie nie aktualizuje mi się access_token oraz refresh_token które pobieram za pomocą POST /auth/oauth/token, mimo że w tamtym miejscu również nie wprowadzałem żadnych zmian w ostanim czasie.

**Comment by kacperKarman** [comment]
w odpowiedzi otrzymuję error: 'invalid_grant' oraz error_description: 'Invalid refresh token: [tutaj mój token]'

**Comment by kacperKarman** [comment]
W jaki sposób mógłbym uzyskać nowy refresh token skoro z obecnym jest coś nie tak z jakiegoś powodu i nie mogę przez to wygenerować nowych tokenów?

**Comment by Morph21** [comment]
W naszym systemie zaczął pojawiać się ten sam problem. Wcześniej błędy "invalid_grant" występowały tylko jeżeli nastąpiła próba odświeżenia auth tokenu za pomocą refresh tokenu który wygasł. 

Mniej więcej od okolicy 15 maja błędy pojawiają się również dla próby odświeżenia authtoken-u za pomocą refresh tokenów które są ważne do sierpnia

**Comment by Morph21** [comment]
@AureliuszBrussy 
Zostały przesłane, zgłoszenie dostało numer 33805720

**Comment by AureliuszBrussy** [comment]
@Morph21 dziękuję, przeanalizujemy to.

**Comment by Morph21** [comment]
@AureliuszBrussy Czy ty masz dostęp do tej wiadomości, którą przesłałem w formularzu kontaktowym? Bo dostałem odpowiedź w tej sprawie od kogoś kto nie za bardzo rozumie jaki mamy problem

**Comment by AureliuszBrussy** [comment]
@Morph21 przepraszam za sytuację, treść zgłoszenia powinna być przekazana nam, natomiast jeszcze do nas nie dotarła. Aktualnie ustalam, jakie były losy zgłoszenia i na pewno niebawem otrzymam jego treść. Prosiłbym o jeszcze trochę cierpliwości.

**Comment by AureliuszBrussy** [comment]
@Morph21 czy jesteś w stanie przesłać przykłady jeszcze świeższych refresh tokenów? Takich, które były wygenerowane w ciągu ostatnich 7 dni?

**Comment by AureliuszBrussy** [comment]
@Morph21 najlepiej w tym samym zgłoszeniu.

**Comment by Morph21** [comment]
@AureliuszBrussy zostało wysłane w załączniku mailem do ostatniego zgłoszenia

**Comment by Morph21** [comment]
@AureliuszBrussy I jak wygląda sprawdzanie tych dosłanych kluczy?

**Comment by AureliuszBrussy** [comment]
@Morph21 w przykładach, które otrzymaliśmy widzimy, że nastąpił unieważnienie tokenów z powodu działań na koncie użytkownika. Takie unieważnienie może nastąpić z kilku powodów:
- wylogowania się ze wszystkich urządzeń, np. poprzez zakładkę Logowanie i hasło,
- zmiany hasła,
- zmiany adresu e-mail,
- blokady sprzedaży,
- w wyniku przekroczenia liczby aktywnych sesji (max. 20 otwartych sesji dla jednego użytkownika).
