### ISSUE TITLE
GET after-sales-service-conditions/warranties zwraca wszystkie rekordy

### ISSUE THREAD

**Issue by arolznov** [allegro/allegro-api#7091]
Dzień dobry

Zasób GET after-sales-service-conditions/warranties gdy nie podamy parametru **limit** zwraca wszystkie rekordy. W dokumentacji jest napisane, że domyślnie i maksymalnie zarazem **limit** przyjmuje 60.

**Comment by MartaNowaczyk** [comment]
Dzień dobry, rzeczywiście jest inny - przy najbliższej okazji poprawimy limit na zgodny z dokumentacją.
