### ISSUE TITLE
Dozwolone zasoby dla zwykłego konta. 

### ISSUE THREAD

**Issue by polenquick** [allegro/allegro-api#7092]
Cześć,
z którego zasobu powinienem skorzystać, aby sprawdzić aktualną cenę publicznej oferty np. w licytacji, w której nie biorę udziału?
Z tego co widzę zasób /offers/listing jest przeznaczony tylko do zweryfikowanych aplikacji.
Obiło mi się również, że na ten moment przez API można wystawiać i edytować oferty tylko z dostępem konta firmowego.

Czy jest w ogóle możliwość, aby na zwykłym koncie wyciągnąć informację z ofert?
trace-id: 1a3be549e56cbcf2

**Comment by MartaNowaczyk** [comment]
Jest tylko jeden zasób do przeglądania publicznych ofert GET /offers/listing, ale jest on dostępny tak jak piszesz, tylko dla zweryfikowanych aplikacji. 
Jeśli chodzi o wystawianie, to tylko aktywne konta firmowe mogą wystawiać i edytować oferty. 

Jeśli chodzi o trace-id, błąd występuje dlatego, że nie jesteś właścicielem tej oferty i niezależnie od tego jakie masz konto, zwykłe czy firmowe, nie pobierzesz tym endpointem jej danych.

**Comment by sl-aw-ek** [comment]
@MartaNowaczyk Jeżeli się już pojawił taki temat, to czy takie konto zwykłe (nie firmowe) może pobrać informację o swojej ofercie  GET /sale/product-offers/{offerId} ?

**Comment by polenquick** [comment]
@MartaNowaczyk okej czyli status zweryfikowanej aplikacji można uzyskać za jakieś specjalne zasługi? typu EasyUploader, Snajper, SkyShop, Baselinker? 

Czy jest w ogóle szansa, abym wypełniał formularz z prośbą i powodem dostępu do tego zasobu, czy lepiej odpuścić i nie tracić czasu, bo go nie otrzymam dla świeżo stworzonej apki na własny użytek :)

Chyba, że źle to rozumiem i dostęp do /offers/listing jest przeznaczony tylko dla sprzedawców VIP/partnerów?

**Comment by sl-aw-ek** [comment]
@polenquick ten endpoint posiada dokładny opis w języku polskim pod tym adresem: https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-pobrac-moje-oferty-w-rest-api

Cytuję "Aby otrzymać listę wszystkich ofert danego użytkownika, wywołaj [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET). Musisz być zautoryzowanym jako sprzedawca, który utworzył te oferty. Domyślnie oferty posortowane są po identyfikatorze oferty malejąco." 

Można pobrać listę ofert ale tylko dla swojego konta, kiedyś ten endpoint był publiczny, ale to było dawno.
