### ISSUE TITLE
Aktywacja konta

### ISSUE THREAD

**Issue by mzywica** [allegro/allegro-api#7093]
Dzień dobry,

proszę o pomoc w aktywacji konta na środowisku testowym:  LOGIN mzywica 
Chciałbym móc tam zarejestrować aplikację na tym koncie https://apps.developer.allegro.pl.allegrosandbox.pl/

**Comment by MartaNowaczyk** [comment]
Dzień dobry, nie widzę takiego konta, na pewno jest poprawne?

**Comment by mzywica** [comment]
![image](https://github.com/allegro/allegro-api/assets/133774444/053be395-1842-4e72-97ae-5a9fb9f6e85e)

Zaznaczam, że chodzi o sandbox

**Comment by MartaNowaczyk** [comment]
Aby wystawiać oferty przez API konto powinno być firmowe. Wybierz "Zmień na konto firmowe" w danych konta jak na zrzucie. Następnie przejdź przez cały "krokowiec" i uzupełnij wszystkie dane.

**Comment by PProtasewicz** [comment]
@MartaNowaczyk 
Dzień Dobry,
czy mógłbym prosić o aktywacje konta Peter7400  service-allegro@nethansa.com ? Z góry dziękuje

**Comment by mzywica** [comment]
Pani Marto,
na moim koncie prywatnym (które nie jest firmowym) w środowisku produkcyjnym zarejestrowałem aplikację, po włączeniu dwustopniowej weryfikacji odblokowała mi się taka możliwość. Na testowym z dokumentacji wyczytałem, że dwustopniowa weryfikacja nie jest konieczna, pomimo to próbowałem ją aktywować, jednak nie otrzymuję smsa.

W każdym razie, jeśli jednak musi to być konto firmowe, utworzyłem 

LOGIN
logifact

m.zywica@logifact.pl

**Comment by MartaNowaczyk** [comment]
Dzień dobry @PProtasewicz, konto Peter7400  jest już aktywne.

**Comment by PProtasewicz** [comment]
@MartaNowaczyk Dziękuje bardzo za pomoc.

**Comment by MartaNowaczyk** [comment]
@mzywica na podanym koncie widzę anulowany przelew weryfikacyjny i masz wybraną niepełną opcję sprzedażową. Wejdź proszę do [ustawień konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy), skorzystaj z linku, który masz na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)" i wybierz "Weryfikacja pełna". Uzupełnij dane i prześlij dowolne pliki.

Tak jak piszesz, na sandbox nie powinno być wymagane dwustopniowe logowanie, stąd smsy nie przychodzą. Włączenie jest  jednak możliwe i możesz spróbować wpisać 12345, a przy logowaniu 123456. Jednak tak jak pisałam nie powinno to być konieczne i lepiej skupić się na aktywacji konta.

**Comment by mzywica** [comment]
Ok, wykonałem powyższe kroki, czekam na weryfikację

![image](https://github.com/allegro/allegro-api/assets/133774444/cd3be1a3-bdb5-4dd0-9c73-5d84a90606c6)


Mam jeszcze pytanie, jak zachowa się na środowisku testowym funkcjonalność Parcel management? Jestem w stanie nadawać testowe przesyłki i otrzymam testowe etykiety aby sprawdzić np poprawność ich wydruku przez moją aplikację?

**Comment by MartaNowaczyk** [comment]
@mzywica aktywowałam konto logifact. Na sandboxie możesz zarządzać przesyłkami, czyli dodasz przesyłki i otrzymasz testowe etykiety.

**Comment by mzywica** [comment]
Dziękuję bardzo za pomoc.
