### ISSUE TITLE
Problem z produkturyzacją - Marka

### ISSUE THREAD

**Issue by Kuba-Id** [allegro/allegro-api#7094]
Mam problem z produktyryzacją, mimo określenia marki jest ona odrzucana.
Dodam, że przy napisaniu innej marki, niż "Trendy Outlet" (parametr ID: 3786) - wszystko działa ok.
Wygląda to tak, jakby ta nazwa była na tzw. czarnej liście. To możliwe?
Allegro, ma tzw. czarną listę?

Odpowiedź API to komunikat:
**Błąd podczas dodawania produktu do bazy Allegro: InvalidProductValueException.
Nieprawidłowe wartości parametrów: [parameter = Marka [ Wartość niejednoznaczna - inna]]**

trace-id: 8175459e4add57fe

Dotyczy kategorii: Odzież, Obuwie, Dodatki / Odzież damska / Spodnie / Casual (na co dzień)
Id kategorii: 254778

Parametry wysyłane podczas produkturyzacji:
`Array
(
    [0] => Array
        (
            [id] => 201077
            [rangeValue] => 
            [values] => 
            [valuesIds] => Array
                (
                    [0] => 201077_2581
                )
        )
    [1] => Array
        (
            [id] => 225693
            [rangeValue] => 
            [values] => Array
                (
                    [0] => 6110187457628
                )

            [valuesIds] => 
        )

    [2] => Array
        (
            [id] => 129314
            [rangeValue] => 
            [values] => 
            [valuesIds] => Array
                (
                    [0] => 129314_1766471
                )
        )
    [3] => Array
        (
            [id] => 249512
            [rangeValue] => 
            [values] => 
            [valuesIds] => Array
                (
                    [0] => 249512_1647413
                )
        )

    [4] => Array
        (
            [id] => 3786
            [rangeValue] => 
            [values] => Array
                (
                    [0] => Trendy Outlet
                )
            [valuesIds] => Array
                (
                    [0] => 3786_85
                )
        )

    [5] => Array
        (
            [id] => 201017
            [rangeValue] => 
            [values] => 
            [valuesIds] => Array
                (
                    [0] => 201017_2337
                )
        )
    [6] => Array
        (
            [id] => 54
            [rangeValue] => 
            [values] => 
            [valuesIds] => Array
                (
                    [0] => 54_4
                )
        )
    [7] => Array
        (
            [id] => 11323
            [rangeValue] => 
            [values] => 
            [valuesIds] => Array
                (
                    [0] => 11323_1
                )
        )
    [8] => Array
        (
            [id] => 129309
            [rangeValue] => 
            [values] => 
            [valuesIds] => Array
                (
                    [0] => 129309_2
                )
        )
    [9] => Array
        (
            [id] => 201025
            [rangeValue] => 
            [values] => 
            [valuesIds] => Array
                (
                    [0] => 201025_2509
                )
        )
)
`

Dodatkowo oferty, które zostały wcześniej sprodukturyzowane z podaną Marką, przy próbie wystawienia zwracają komunikat:

"**You cannot list an offer without a linked product in this category. Select a product from the catalog or create a new one and link it with your offer.**"

Mimo, że do niedawna wszystko się wznawiało bez problemów. Mija jaki czas... miesiąc, dwa i nagle przy próbie kolejnego wznowienia taki komunikat, gdzie jeszcze tydzień wcześniej oferta wznawiała się bez problemów.

**Comment by AureliuszBrussy** [comment]
Wartość, którą przesłałeś w tym parametrze wpadła na jedną z naszych reguł walidacji produktu. Traktujemy to jako wartość nieprawidłową - powinna się tam znaleźć realna nazwa marki (wygląda natomiast na nazwę sklepu sprzedającego). 

Jeżeli nie jesteś w stanie dopasować marki, skorzystaj z wartości "bez marki" (3786_1704209). Jeżeli natomiast marka istnieje: sprzedający [poprzez formularz kontaktowy](https://allegro.pl/pomoc/kontakt) może poprosić o dodanie jej do słownika wartości. 

Co do przypadku związanego z błędem dotyczącym braku powiązana produktu - być może produkt został usunięty z naszego katalogu. Żebym jednam mógł sprawdzić szczegóły - poprosiłbym o przykładowe trace-id wywołania zakończonego tym komunikatem lub ew. id danego produktu.
