### ISSUE TITLE
Info about Refresh Token lifetime in Sandbox Environment

### ISSUE THREAD

**Issue by danielev-qapla** [allegro/allegro-api#7095]
Hello,
I'd like to know if it is possible that Refresh Tokens are reset every day in the **sandbox environment** and they don't have a 3 months life.
It happened that I could complete the authentication and authorization process, getting the Access and Refresh token, but when I try to get a new access token, extending the token validity using the refresh token, I get an error saying that refresh token isn't valid when a day is passed and the access token is expired.
If I try to extend the token validity some minutes after I completed the "Authorization Code flow", I have no issues.
So I'm just wondering if I'm missing something, or if this is an expected behaviour in sandbox environment.
It's not easy to me to repeat this behaviour because I have to wait many hours before to see it again.
Thanks in advance for your help.

Kind Regards,
Daniele

**Comment by AureliuszBrussy** [comment]
The lifespan of refresh tokens on Sandbox is the same as on production, which is 3 months. 

Make sure you don't actually use them up before - remember they are disposable and once used, they expire. 

Tokens may also expire due to exceeding the number of sessions, which is 20.

**Comment by danielev-qapla** [comment]
Ok, thank you for these details.
