### ISSUE TITLE
413 Payload Too Large

### ISSUE THREAD

**Issue by adamus994** [allegro/allegro-api#7096]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry,
od wczoraj obserwujemy dziwne działanie API.
Dla części zapytań zamiast prawidłowej odpowiedzi otrzymujemy taki komunikat:

<html><body><h1>413 Payload Too Large</h1>
The request entity exceeds the maximum allowed.
</body></html>

Dostajemy ten komunikat całkowicie losowo, raz na to samo zapytanie dostaniemy poprawną odpowiedź, a kolejnym razem ten komunikat o błędzie. 
Obserwujemy takie działanie przykładowo podczas używania metod:
https://api.{environment}/parcel-management/parcel-create-commands/{commandId}
https://api.{environment}/sale/categories/{categoryId}/parameters

Będę wdzięczny za podpowiedź co może tu być nie tak.

**Comment by MartaNowaczyk** [comment]
Dziękuje za zgłoszenie, wygląda to na ogólny problem, przyjrzymy się opisanej sytuacji i damy znać, gdy coś ustalimy.

**Comment by MartaNowaczyk** [comment]
@adamus994 Udało nam się ustalić co jest przyczyną tych błędów i wycofać zmianę, która to powodowała. Problem występował jeśli request dla GET wysyłany był po HTTP 1.0, który dodatkowo zawierał payload. Prośba by nie dodawać payloadu, który i tak jest przez nas ignorowany dla metody GET. Rekomendujemy też, aby korzystać z HTTP 1.1 lub najlepiej HTTP 2.0. Za niedogodności przepraszamy.

**Comment by adamus994** [comment]
Ok, dziękuję za informację. Przed chwilą przełączyłem (chyba) na protokół HTTP/2
