### ISSUE TITLE
Błąd "413 Payload Too Large" przy pobieraniu ofert metodą GET /sale/offers

### ISSUE THREAD

**Issue by lukiopmoto** [allegro/allegro-api#7097]
Dzień dobry, od kliku dni obserwuję bardzo częste pojawianie się błędu: **413 Payload Too Large. The request entity exceeds the maximum allowed.** przy próbie pobierania moich ofert z Allego. Myślałem że próbuję pobierać za duży plik JSON więc ustawiłem limit z 1000 na 500, później nawet na 100 i cały czas to samo. Przy próbie odpytania o 100 000 ofert średnio ok. 2-3 tysięcy nie udaje się pobrać z powodu w/w błędu.  

Info z naszych logów podczas próby pobrania wszystkich ofert w celu zweryfikowania poprawności cen itd.: "Metoda getOffers zwróciła nieprawidłowy JSON (json_last_error = 4) dla limit:100 i offset:28200." 

Najlepsze to że gdy jeszcze raz pobiorę oferty przez API dla limit 100 i OFFSET 28200 to API zwraca już poprawny JSON, bez błędu. Całość odbywa się w pętli i błąd wyrzuca za każdym razem w innych offsetach.

Sytuację obserwuję nie tylko na moim koncie, ale również znajomi potwierdzają ten fakt. 

Proszę o informację co jest przyczyną takiego stanu rzeczy? Dodam iż w przeszłości zdarzały się takie sytuacje ale raz na tydzień albo rzadziej. teraz kilka dni bez przerwy.

**Comment by lukiopmoto** [comment]
Błąd zaczął pojawiać się od 16 maja mniej więcej po godzinie 9:00 jeżeli to w czymś Państwu pomoże.

**Comment by MartaNowaczyk** [comment]
Rozumiem, dziękuję za obszerny opis sytuacji, będziemy to weryfikować. Twoje zgłoszenie jest powiązane z #7096 i widać, że błąd pojawia się niezależnie od zasobu. Mam nadzieję, że szybko uda nam się znaleźć przyczynę.

**Comment by lukiopmoto** [comment]
Dziękuję. Proszę tylko o informację gdy problem zostanie rozwiązany. Do tego momentu będziemy musieli wyłączyć publikację ofert lub szukać jakieś szybkiej "łatki" w kodzie na obejście problemu.

**Comment by MartaNowaczyk** [comment]
Rozumiem, dam znać tak szybko jak to będzie możliwe.

**Comment by thefoe76** [comment]
To samo, problem zaczął się w poniedziałek bo wyrzucało co któreś robienie etykiet kuriera (program sprawdza najpierw na Allegro, czy między czasie nie anulowano zamówienia. Sprawa randomowa (nie ma zasady kiedy "nie wejdzie") . Dotyczy chyba wszystkich zasobów, ale na pewno wyłazi przy pobieraniu dyskusji. Zgaduje, ze problem z autoryzacją wtedy wywala do response kod strony HTML allegro, co przekracza limity (chyba Allegro zmniejszyło je, bo kiedyś juz potrafiło wczytywać całą stronę Allegro do response).

**Comment by MartaNowaczyk** [comment]
@thefoe76 dzięki za dodatkowe informacje. Sprawa jest już w odpowiednim zespole i weryfikujemy sytuację.

**Comment by MartaNowaczyk** [comment]
@lukiopmoto @thefoe76 @adamus994 Udało nam się ustalić co jest przyczyną tych błędów i wycofać zmianę, która to powodowała. Problem występował jeśli request dla GET wysyłany był po HTTP 1.0, który dodatkowo zawierał payload. Prośba by nie dodawać payloadu, który i tak jest przez nas ignorowany dla metody GET. Rekomendujemy też, aby korzystać z HTTP 1.1 lub najlepiej HTTP 2.0. Za niedogodności przepraszamy.

**Comment by lukiopmoto** [comment]
_Problem występował jeśli request dla GET wysyłany był po HTTP 1.0, który dodatkowo zawierał payload._

Może Pani wyjaśnić co to oznacza że Request zawierał dodatkowo payload? To znaczy że co dokładnie, bo nie rozumiem? Bo skoro skrypt raz coś wykonywał i nie działało, i po sekundzie wykonywał to samo w ten sam sposób i działało, to gdzie niby miałby się pojawić ten dodatkowy payload?

**Comment by MartaNowaczyk** [comment]
@lukiopmoto wycofane rozwiązanie nie działało dla całego ruchu, stąd błąd raz występował, a raz nie.

**Comment by thefoe76** [comment]
wygląda na to, ze naprawili. 
Ja nigdy nie wysyłam payloadu po GET, zresztą komunikat chyba miałby inną treść w takim przypadku? Gdzie indziej Allegro tłumaczyło, ze taki komunikat występuje jak response ma więcej niż 40 KB
bardziej przemawia do mnie, ze część ruchu odrzucało HTTP/1.0  a tak działa na defaulcie file_get_contents i raczej wątpie by było to co innego niż zwykły błąd po stronie Allegro, który jak zwykle nikt tam nie zauważył (kto by tam sprawdzał logi?)
