### ISSUE TITLE
MissedCategoryIdException error 

### ISSUE THREAD

**Issue by Axlii50** [allegro/allegro-api#7098]
Witam wysyłam taką strukture:
{"name":"BULLMASTIFF - Wołoczko Magdalena","payments":{"invoice":"VAT"},"external":{"id":"5763"},"productset":[{"Product":{"id":"2bbb55fc-a356-45d5-97b5-1f539b50fbca","name":"Bullmastiff Magdalena Wołoczko","category":{"id":"261372"},"parameters":[{"id":"75","name":"Okładka","type":null,"required":false,"requiredForProduct":false,"unit":null,"dictionary":null},{"id":"223545","name":"Tytuł","type":null,"required":false,"requiredForProduct":false,"unit":null,"dictionary":null},{"id":"223489","name":"Autor","type":null,"required":false,"requiredForProduct":false,"unit":null,"dictionary":null},{"id":"17448","name":"Waga produktu z opakowaniem jednostkowym","type":null,"required":false,"requiredForProduct":false,"unit":"kg","dictionary":null},{"id":"232161","name":"Rodzaj","type":null,"required":false,"requiredForProduct":false,"unit":null,"dictionary":null},{"id":"74","name":"Rok wydania","type":null,"required":false,"requiredForProduct":false,"unit":null,"dictionary":null},{"id":"2868","name":"Język","type":null,"required":false,"requiredForProduct":false,"unit":null,"dictionary":null},{"id":"4966","name":"Forma","type":null,"required":false,"requiredForProduct":false,"unit":null,"dictionary":null},{"id":"223541","name":"Wydawnictwo","type":null,"required":false,"requiredForProduct":false,"unit":null,"dictionary":null},{"id":"223493","name":"Liczba stron","type":null,"required":false,"requiredForProduct":false,"unit":null,"dictionary":null},{"id":"223341","name":"Numer wydania","type":null,"required":false,"requiredForProduct":false,"unit":null,"dictionary":null},{"id":"223333","name":"Szerokość produktu","type":null,"required":false,"requiredForProduct":false,"unit":"cm","dictionary":null},{"id":"223329","name":"Wysokość produktu","type":null,"required":false,"requiredForProduct":false,"unit":"cm","dictionary":null}],"images":[{"url":"https://a.allegroimg.com/original/11fb76/bde39f214e7ab650b3f04c2636ad"},{"url":"https://a.allegroimg.com/original/25a042/b771fe544660a001ef4e184fe02e"}]},"quantity":{"value":228}}],"category":{"id":"261372"},"publication":{"duration":"P7D","status":"INACTIVE","startingAt":null,"startedAt":null,"endingAt":null,"republish":true,"marketplaces":null},"stock":{"available":228,"unit":"UNIT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":"9.06","currency":"PLN"},"minimalPrice":null,"startingPrice":null},"images":null}

pod adres 
https://api.allegro.pl/sale/product-offers

i dostaje następujacy error 
{"errors":[{"code":"MissedCategoryIdException","message":"Unprocessable Entity","details":null,"path":"","userMessage":"Kategoria produktu jest wymagana. Należy podać id kategorii."}]}

gdzie obydwa pola w ofercie jak i produkcie są wypełnione oraz istnieja

**Comment by MartaNowaczyk** [comment]
Z tego co widzę, masz niepoprawną strukturę:
- masz "productset" zamiast "productSet"
- "Product" a powinno być "product"
- zdjęcia też do poprawki na         
```
"images": [
          "https://a.allegroimg.com/original/11fb76/bde39f214e7ab650b3f04c2636ad",
          "https://a.allegroimg.com/original/25a042/b771fe544660a001ef4e184fe02e"
        ]
```

Poprawną strukturę znajdziesz w naszej [dokumentacji](https://developer.allegro.pl/documentation#operation/createProductOffers).

**Comment by Axlii50** [comment]
Pomogło, dziękuje
