### ISSUE TITLE
Zmiana cen w wielu ofertach jednocześnie na kilku rynkach.

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#7099]
Witam,

zgodnie z dokumentacją za pomocą PUT /sale/offer-price-change-commands/{commandId} można zmienić cenę w kilku ofertach jednocześnie. 

Czy jest możliwość za pomocą powyższego zasobu zmienić cenę na kilku rynkach jednocześnie? (przykładowo podając cenę w złotówkach oraz koronach).

Ewentualnie czy jest inny zasób, którym można dokonać zbiorowych zmian cen podając jednocześnie dwie waluty?

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Dzień dobry.

Dzięki [PUT /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation#operation/priceModificationCommandUsingPUT) możesz zmienić cenę w ofertach dla jednego wybranego marketplace - wskazujesz go w polu `marketplaceId`.

Aby zmienić cenę w ofercie dla serwisu bazowego oraz serwisów dodatkowych równocześnie, możesz skorzystać z [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/editProductOffers). Wystarczy, że wyślesz zmianę w polu `sellingMode.price` oraz `additionalMarketplaces.{marketplaceId}.sellingMode.price`.
