### ISSUE TITLE
doRequestPayout i ERR_PAYOUT_NOT_POSSIBLE

### ISSUE THREAD

**Issue by juhacz** [allegro/allegro-api#71]
Od jakiegoś czasu (około tygodnia, może trochę więcej) próba wypłaty środków z PayU poprzez doRequestPayout kończy się błędem: 
Fatal error: Uncaught SoapFault exception: [ERR_PAYOUT_NOT_POSSIBLE] Nie można wykonać ręcznej wypłaty z rachunku w PayU

Co zabawne, błąd występuje, ale środki są wypłacane. Od kilku lat, kontem dla PayU jest konto w Banku Inteligo. Ostatnio na tym koncie zweryfikowałem się do płatności przez Przelewy24, może to ma coś wspólnego? 
Proszę o sprawdzenie.

**Comment by MarcinLuczak** [comment]
@juhacz czy możesz podać numer/identyfikator takiej wypłaty? Takiej, która dotarła do Ciebie pomimo tego, że dostałeś komunikat o błędzie.

**Comment by juhacz** [comment]
Np. 120722861, Widzę, że wpłata tej wypłaty była zrobiona przez Przelewy24, które dopiero aktywowałem, więc może w tym problem.

**Comment by MarcinLuczak** [comment]
@juhacz Dziękuję. Zgłosiłem to do analizy i poprawienia. Podeślij proszę jeszcze XML-e z requestem i responsem, w których widać problem. Możesz to zrobić np. przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).

**Comment by juhacz** [comment]
Nie zapisuję ich.

**Comment by MarcinLuczak** [comment]
@juhacz zapisz proszę najbliższe zapytanie i odpowiedź, a potem nam je podeślij.
