### ISSUE TITLE
[REST] POST  sale/loyalty/promotions zwraca error

### ISSUE THREAD

**Issue by madkot** [allegro/allegro-api#710]
Próba dodania nowego [zestawu promocyjnego](https://developer.allegro.pl/news/2017-10-18-News_promocyjne_zestawy_ofert/) z 2 produktów kończy się errorem:
`stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => ERROR [message] => An error has occurred [details] => [path] => /sale/loyalty/promotions [userMessage] => ) ) )`

Wysłane parametry:
`{"benefits":[{"specification":{"type":"ORDER_FIXED_DISCOUNT","value":{"amount":"80","currency":"PLN"}}}],"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"748336xxxx","quantity":"1","promotionEntryPoint":"1"},{"id":"666755xxxx","quantity":"1","promotionEntryPoint":"1"}]}]}`

Produkty miały istniejący zestaw "wyklikany" w panelu, który z powodzeniem usuną się poprzez API. 

Jak widać błąd nic ciekawego nie mówi.. co może być nie tak?

**Comment by madkot** [comment]
UPDATE:
problem był z promotionEntryPoint, zamiast "true" lub "false" wysyłałem odpoweidnio 1 lub 0. musi być true/false.

**Comment by PawelTaberski** [comment]
Dokładnie tak jak napisałeś dokładny opis jak korzystać z danego zasobu zawsze znajdziesz w naszych aktualnościach. Odnośnie wspomnianego zasobu więcej informacji znajdziesz [tutaj](https://developer.allegro.pl/news/2017-10-18-News_promocyjne_zestawy_ofert/).
