### ISSUE TITLE
Info about Apps and use of Rest API with many sellers account

### ISSUE THREAD

**Issue by danielev-qapla** [allegro/allegro-api#7101]
Hello,
I'm currently working to Qapla', a web application which helps our customers to manage their shipments and orders.
Our customers tipically are merchants, owning an e-commerce website, which often wants to sell also through some marketplaces (e.g. ebay, amazon, ecc.).

We'd like to let our customers to import their orders from Allegro and then, when the parcels are shipped, automatically update the orders in Allegro, changing the orders status and adding a tracking number.

I had no problem doing this in the sandbox environment, I created a business account and an App. Using the "Authorization Code Flow" I could use the APIs to import orders and update them.
Now we are planning to move this feature to our production environment, and I'm wondering if every merchant who wants to use Allegro as a marketplace should define a new App for using Rest API (with its client Id and secret), or if we can define a single "developer" App for Qapla' and let the merchants give us the access to rest api just loggin-in using the OAuth Authorization Code Flow.

It seems that a single "developer app" should work, because I created the App within the QaplaSandbox account and I could access to another account (SecondQaplaTest), but we want to be sure we're doing the right way. If this is not possibile, please let me know.

Thanks in advance.

Kind regards,
Daniele

**Comment by AureliuszBrussy** [comment]
Hi Daniele,
we encourage you to use a single Client ID for one application, generated by the application developer, not by Merchant. So I can confirm - your suspicions are correct, and you are doing the right way :).

**Comment by danielev-qapla** [comment]
Thanks!
