### ISSUE TITLE
Webhooki - płatności

### ISSUE THREAD

**Issue by devzby** [allegro/allegro-api#7102]
Cześć,

nie jestem w stanie znaleźć w dokumentacji (ani na sandboxie, na koncie) informacji o webhookach - czy Allegro API obsługuje webhooki  dot. opłacenia zamówienia? Czyli płatnik opłaca swoje zamówienie i w tym momencie wysyłany jest request na endpoint.

**Comment by hahyes** [comment]
> Cześć,
> 
> nie jestem w stanie znaleźć w dokumentacji (ani na sandboxie, na koncie) informacji o webhookach - czy Allegro API obsługuje webhooki dot. opłacenia zamówienia? Czyli płatnik opłaca swoje zamówienie i w tym momencie wysyłany jest request na endpoint.

Musisz śledzić dziennik zdarzeń pozakupowych w tym celu. Nie ma webhooków niestety.
