### ISSUE TITLE
"Wystaw podobną ofertę" w /sale/product-offers

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#7103]
W poradniku "Jak wystawić podobną ofertę" jest informacja o tym które pola należy usunąć z GET /sale/offers/id aby wystawić podobną ofertę przez wykonanie POST /sale/offers. A tu interesujący mnie fragment:

```
Całą pobraną strukturę z wyłączeniem:

- numeru identyfikacyjnego oferty,
- informacji, kiedy odbyła się ostatnia walidacja oferty,
- daty utworzenia oferty,
- daty ostatniej aktualizacji oferty,
- sekcję "publication".

prześlij za pomocą POST /sale/offers
```

Czy takie same zasady dotyczą wystawiania podobnej oferty przez **GET i POST /sale/product-offers**?

Link do wspomnianego poradnika:
https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-podobna-oferte

**Comment by AureliuszBrussy** [comment]
Zasób ten nie był projektowany z taką intencją (ze względu na logikę opartą o produkty), natomiast to, o czym piszesz powinno być prawdziwe także dla **/sale/product-offers**. Kłopot na ten moment może sprawić natomiast to, co opisałeś w zgłoszeniu #6547.

**Comment by tomylee0** [comment]
A jeśli chodzi o #6547, to pomyślałem, że wystawiając ofertę podobną w metodzie POST dodam pustą tablicę w "productSet.product.images". A w sam "images" nie będę ingerował. Jeśli więc kopiowana oferta miała w sobie zdjęcie tylko sprzedającego albo tylko produktowe albo np. jedno sprzedającego i jedno produktowe to czy mechanizm Allegro przyjmujący takiego POST'a zachowa się dla każdej z tych możliwości inaczej? Wydaje mi się, że nowa oferta powinna mieć dla każdego z tych przypadków taki sam zestaw zdjęć jak oferta kopiowana.

**Comment by AureliuszBrussy** [comment]
Sprawdziłem to i masz rację - to powinno rozwiązać problem. W oryginalnej ofercie wszystkie zdjęcia powinny znajdować się w sekcji _images_, po przekazaniu pustej tablicy w _productSet.product.images_ duplikatów nie będzie. 

Wracając jeszcze do pierwszego postu, dodam, że nie trzeba usuwać obiektu _publication_.
