### ISSUE TITLE
Wza czechy 

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#7106]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ X ] ze środowiskiem produkcyjnym / with the production environment

Mamy problem z tworzniem przesylek dla zamowien na Czechy. Otóz mamy zamowienie z metoda dostawy
Allegro Wysyłka z Polski do Czech - Automaty Paczkowe Packeta, przez panel www mozna bez problemu utworzyć numer przewozowy jak i etykietę, natomiast przez api nie.  Zwraca komunikat "Ubezpieczenie jest wymagane w celu utworzenia przesyłki", jako ze wedlug dokumentacji nie ma pola na ubezpieczenie jest tylko deklarowana wartosc wiec w obiekcie items['value'] dodalismy pola amount i currency ('CZK') i wtedy dostajemy blad "Waluta CZK nie jest wspierana dla wybranej metody dostawy". Coś robimy nie tak czy moze obecnie tworzenie przesyłek dla takich przypadkow dziala tylko przez panel?

**Comment by Maciej-Wilkosz** [comment]
Podlaczam sie do pytania, bo podobna kwestia. Allegro gdy pobieram zamowienia zwraca zamowienia z rynku czeskiego w walucie czeskiej, natomiast gdy dla danych 1 do 1 dla takiego zamowienia chcemy wygenerowac list przewozowy to allegro mowi ze nie obsluguje tej waluty tak jak wspomniano wyzej. Jak to ogarnac?

**Comment by AureliuszBrussy** [comment]
Aby ubezpieczyć przesyłkę, należy zadeklarować wartość przedmiotów w obiekcie `items[].value.` Waluta powinna być zgodna  tym do jakiego marketplace'u przynależy dana metoda dostawy (z jakiego marketplace było złożone zamówienie). @d3stozaur Twoje zamówienie prawdopodobnie zostało złożone na allegro.pl, dlatego też wymagamy, aby kwota była podana w PLN.
