### ISSUE TITLE
Product Offer Update Error

### ISSUE THREAD

**Issue by dmsmatrix** [allegro/allegro-api#7108]
Hi,

Please let me know why I am getting error **Parameter with ID `3346` not found in the specified category `308845`.** where category `67195` is parent category of my product's category `308845` and Parameter with ID `3346` is associated with parent category not product category.

Is Parent category parameters not allowed along with product's category parameters in request of product offer?

Please find request and response below:

endpoint : PATCH https://api.allegro.pl/sale/product-offers/13673971816

request : {"afterSalesServices":{"impliedWarranty":{"id":"d452e0ee-1830-404b-911c-dcd67a419bbd","name":"Gezhi complaint"},"returnPolicy":{"id":"9b6f2f33-f361-48e0-b5f4-da85999bc980","name":"Gezhi Return terms"}},"delivery":{"handlingTime":"P4D","shippingRates":{"id":"1379b287-d064-49c2-9926-9b27134cedef","name":"Gezhi Price"}},"publication":{"duration":null,"republish":true},"payments":{"invoice":"NO_INVOICE"},"productSet":[{"product":{"parameters":[{"id":"3346","name":"Cable Length","values":["0"]},{"id":"248135","name":"Brand","valuesIds":["248135_1645077"]},{"id":"237206","name":"Model","values":["GZ07"]},{"id":"224017","name":"Manufacturer's code","values":["GZ"]},{"id":"225693","name":"EAN (GTIN)","values":["768679654046"]}],"name":"Cable Management Organizer Box","category":{"id":"308845"},"images":["https://dmsmatrix.net/direct/images/644f61cf99d56d6e0f5a8de1_750x600.jpg"]},"quantity":{"value":1}}],"parameters":[{"id":"11323","name":"Condition","valuesIds":["11323_1"]}],"name":"Cable Management Organizer Box","description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Practical Storage Solution: It provides perfect storage and cover for cables, power strips, or cords.Multi Outlets: The three outlets on the sides allow positioning the box according to the cables and electrical plugs position. The narrow outlets on the cover allow the thin USB cables going through.Hollow Out Bottom: The holes on the bottom are designed for heat dissipation.ABS Material: Made of ABS material, it is durable to use.Material: ABSColor: WhiteSize: Approx. 32 x 13 x 11 cm / 13.0 x 5.1 x 4.3inPackage List:1 x Storage Box</p>"}]}]},"category":{"id":"308845"},"images":["https://dmsmatrix.net/direct/images/644f61cf99d56d6e0f5a8de1_750x600.jpg"],"sellingMode":{"price":{"amount":"59.80","currency":"PLN"},"format":"BUY_NOW"},"stock":{"available":196,"unit":"UNIT"},"external":{"id":"768679654046"}}

headers : {"expires":" 0","cache-control":" no-cache, no-store, max-age=0, must-revalidate","x-xss-protection":" 1; mode=block","pragma":" no-cache","x-frame-options":" DENY","trace-id":" 40fdd34744bcdd19","date":" Thu, 18 May 2023 14:00:52 GMT","x-content-type-options":" nosniff","strict-transport-security":" max-age=31536000 ; includeSubDomains","content-type":" application/json; charset=UTF-8","content-length":" 229"}

response : {"errors":[{"code":"ParameterIdNotFoundException","message":"Unprocessable Entity","details":null,"path":"productSet[0].product.parameters","userMessage":"Parameter with ID `3346` not found in the specified category `308845`."}]}

Thanks in advance

**Comment by AureliuszBrussy** [comment]
Hi. Categories do not inherit parameters. Each category, even if it is a subcategory, has its own set of parameters, which you get by using [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). Parameter id of 3346 does not exist in this category 308845.

**Comment by dmsmatrix** [comment]
.0
