### ISSUE TITLE
sale->product-offers błąd encji html (?)

### ISSUE THREAD

**Issue by BartDev785** [allegro/allegro-api#7109]
Hej, przeszliśmy na nową metodę wystawiania, wszystko super, parametry się uzupełniają tylko w 30% przypadków dostajemy błąd: To include the & character in the description, use the entity: & Other available entities:   " ' < >

Co ciekawe, w starej metodzie było ok, wnioskuje inne procesowanie encji html w opisie, będę wdzięczny za spojrzenie

response header wraz z trace-id

Array ( [0] => HTTP/1.0 422 Unprocessable Entity [1] => expires: 0 [2] => cache-control: no-cache, no-store, max-age=0, must-revalidate [3] => x-xss-protection: 1; mode=block [4] => pragma: no-cache [5] => x-frame-options: DENY [6] => trace-id: 6c1c91455bee9937 [7] => date: Thu, 18 May 2023 16:28:30 GMT [8] => x-content-type-options: nosniff [9] => strict-transport-security: max-age=31536000 ; includeSubDomains [10] => content-type: application/json; charset=UTF-8 [11] => content-length: 739 )

**Comment by thefoe76** [comment]
nalezy zamienić w tekście dla opisu & na &amp; i apostrof ' na &#039;

**Comment by AureliuszBrussy** [comment]
@thefoe76 potwierdzam to co napisał @thefoe76 - zamieniaj znaki na encje.
