### ISSUE TITLE
Różnica w kategoriach pomiędzy SOAP / REST

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#711]
Nawiązując do ticketów oraz odpowiedzi: 

https://github.com/allegro/allegro-api/issues/169
https://github.com/allegro/allegro-api/issues/699#issuecomment-426994881

Czy to znaczy że mogą pojawić się kategorie będące liśćmi które mają identyfikator w formacie UUID ?Jeśli tak to proszę o przykład. Pytam bo chcemy wprowadzić tymczasowo hybrydę wystawiającą aukcje po SOAP API, a pobierającą kategorie po REST, aby nie trzeba było pobierać wszystkich kategorii co jakiś czas (cron). Nie chce sytuacji w której przejdziemy na hybrydę, a aukcje zaczną wystawiać się w zupełnie losowych kategoriach (różnica pomiędzy identyfikatorami) albo nie będzie dało się ich wystawić bo dostałem od Was UUID. Muszę mieć absolutną pewność

**Comment by imper86** [comment]
Podpinam się pod temat. Swoją drogą, jeśli odpowiedź na powyższe pytanie brzmi "TAK" to czy po prostu do zasobu z kategoriami możecie dodać parametr np "legacyId", gdzie byłby stary integerowy id kategorii?

**Comment by PawelTaberski** [comment]
Obecnie wszystkie kategorie liście są intami i tak ma zostać, nie przewidujemy wprowadzenia tam numerów w formacie UUID. Tylko niektóre kategorie działów mają identyfikatory w postaci UUID-ów.

**Comment by kormichu** [comment]
Ok, trzymam za słowo
