### ISSUE TITLE
Status zamówienia (sandbox)

### ISSUE THREAD

**Issue by barczykartur** [allegro/allegro-api#7111]
Hej, mam problem ze zmianą statusu zamówienia. Sytuacja wygląda następująco: Wystawiam przedmiot. Kupuję ten przedmiot z innego konta. Po zakupie, jako sprzedający, zmieniam status zamówienia na "WYSŁANE" przez endpoint:
```https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms/${id}/fulfillment```
W panelu jako sprzedający widzę, że status zmienił się na "WYSŁANE". Lecz jeżeli sprawdzę status tego zamówienia z poziomu osoby kupującej to status jest ustawiony na "W PRZYGOTOWANIU". Czy status ten zmienia się po jakimś czasie? Czy robię coś nie tak/coś pominąłem? Prosiłbym o wskazówki, z góry dziękuję oraz pozdrawiam.

**Comment by barczykartur** [comment]
a83ced10-f574-11ed-bb9f-01f107cb0bbd

**Comment by AureliuszBrussy** [comment]
To jest poprawne działanie, w zakładce zamówienia pokazujemy status przesyłki - śledzimy dodany do zamówienia numer nadania. O zmianie statusów przez sprzedającego kupujący informowany jest w powiadomieniach. Jest też informacja dla sprzedającego.

**Comment by barczykartur** [comment]
Dziękuję za odpowiedź. Miałbym jeszcze jedno pytanie dotyczące widoku, który jest w zamówieniu tj.
![image](https://github.com/allegro/allegro-api/assets/90607951/fc4a93aa-4ddc-4c78-b4f4-f52598a5866c)
Status jest jako "WYSŁANE" według API. Dodałem też numer przesyłki, lecz zamówienie dalej znajduje się w pierwszym kroku. Czy tak powinno być? W jakich przypadkach widnieje informacja "Przesyłka bez możliwości śledzenia"? Co muszę zrobić, żeby na zamówieniu było widoczne, że przesyłka jest wysłana?

**Comment by AureliuszBrussy** [comment]
Metodą dostawy jest dostawa własna na adres, więc w takim przypadku nie mamy możliwości śledzenia przesyłki, stąd informacja o braku możliwości śledzenia przesyłki. W realnym scenariuszu, na produkcji, użytkownik (po uzupełnieniu numeru przesyłki przewoźnika, którego przesyłki śledzimy) będzie widział aktualny status przesyłki. 

Tak jak wspomniałem, o zmianach statusów wykonanych przez sprzedającego informujemy w powiadomieniach. Możesz zarządzać powiadomieniami w zakładce [Ustawienia](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/zamowienia/ustawienia).
