### ISSUE TITLE
/sale/product-proposals access denied

### ISSUE THREAD

**Issue by wangzengxing** [allegro/allegro-api#7112]
{"errors":[{"code":"AccessDeniedException","message":"Access denied.","details":null,"path":null,"userMessage":"No access."}]},
jwt:

**Comment by AureliuszBrussy** [comment]
To be able to send product proposals, the Allegro account must be fully active. The account you are sending the request on behalf of is not fully activated. To clarify this, the account owner should use the [contact form](https://allegro.pl/pomoc/kontakt).
