### ISSUE TITLE
OfferCustomParametersException

### ISSUE THREAD

**Issue by pwojciech** [allegro/allegro-api#7113]
Na sandbox wysyłam poniższy request dla metody 
https://api.allegro.pl.allegrosandbox.pl/sale/product-offers

> {
>     "id": null,
>     "langauge": "pl-PL",
>     "name": "Test482518",
>     "delivery": {
>         "shippingRates": {
>             "id": "6753e39a-a249-4033-9fac-7431b5b96759"
>         }
>     },
>     "sellingMode": {
>         "price": {
>             "amount": "999.00",
>             "currency": "PLN"
>         }
>     },
>     "stock": {
>         "available": 999,
>         "unit": "UNIT"
>     },
>     "images": [
>         "https://a.allegroimg.allegrosandbox.pl/original/11c702/69f0cae3486db19f79b326f05050"
>     ],
>     "productSet": [
>         {
>             "product": {
>                 "id": "515d584e-7fe0-4c14-b4f4-c0e1e20abf3c"
>             }
>         }
>     ]
> }

zwraca błędy:

> {
>     "errors": [
>         {
>             "code": "OfferCustomParametersException",
>             "message": "401 UNAUTHORIZED \"No valid `x-oauth-token-validated` or `x-client-name-trusted` header present!\"",
>             "details": null,
>             "path": "productSet[0].product.parameters",
>             "userMessage": "Wystąpił błąd w trakcie przetwarzania zapytania: 401 UNAUTHORIZED \"No valid `x-oauth-token-validated` or `x-client-name-trusted` header present!\""
>         }
>     ]
> }

Access token ważny, jeszcze wczoraj było wszysto ok. O co może chodzić?

**Comment by MartaNowaczyk** [comment]
Weryfikujemy opisaną sytuację. Wrócę z odpowiedzią, gdy tylko coś ustalimy.

**Comment by MartaNowaczyk** [comment]
Naprawiliśmy opisany problem. Teraz twój request powinien wykonać się poprawnie. Dziękujemy za zgłoszenie i przepraszamy za niedogodności.
