### ISSUE TITLE
Kategoria oferty nie pasuje do kategorii produktu - API nie zwraca tego błędy

### ISSUE THREAD

**Issue by relains** [allegro/allegro-api#7115]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Od jakiegoś czasu przestały nam się wznawiać niektóre oferty. Problemem jest błąd "Kategoria oferty nie pasuje do kategorii produktu" - niestety API nie przekazuje tego błędu w żaden sposób.

Bramka sale/offers/{offerId} (PUT oraz POST) - nie zwraca żadnych błędów czy ostrzeżeń.
Bramka sale/offer-publication-commands/ACTIVATE (PUT) - nie zwraca żadnych błędów czy ostrzeżeń.
Bramka sale/product-offers/{OfferID} (GET) - wywołana 30 sekund po wysłaniu komendy aktywacji, również nie pokazuje by oferta miała jakieś błędy czy ostrzeżenia.

**Comment by AureliuszBrussy** [comment]
Walidacja następuje w momencie wysłania requestu. Wygląda na to, że zwracamy error, skoro znasz jego treść?  

Czy mógłbyś podać jakieś konkretne przykłady ofert czy wywołań z taką nieudaną próbą aktywacji oferty? Najlepiej, jeżeli przekażesz nam trace-id (znajdziesz w nagłówku response'a).

**Comment by relains** [comment]
Błąd zwracany jest jedynie, jak próbuję wznowić ofertę z poziomu Allegro.

Przykładowe trace-id:
2c80d9aa3e5f9c02
95ceb7c5f61c3c53

**Comment by AureliuszBrussy** [comment]
Dziękuję za przykład. Widzę, że nie zwracamy dla tej oferty żadnych błędów, a sama komenda zakończyła się powodzeniem i udało się ją aktywować. Nie widzę tutaj nieprawidłowości.

**Comment by AureliuszBrussy** [comment]
W komendzie spod trace-id `95ceb7c5f61c3c53` aktywowałeś inną ofertę. Tutaj aktywacja zakończyła się sukcesem. 

Jeżeli chodzi o ofertę 10095030966 - faktycznie, ostatnia aktywacja zakończyła się niepowodzeniem, natomiast zwracamy powód niepowodzenia. Wystarczy, że sprawdzisz szczegóły komendy za pomocą [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET).
