### ISSUE TITLE
Nazwy usług z parcel-management/delivery-services zmieniły się na angielskie

### ISSUE THREAD

**Issue by OskarSw** [allegro/allegro-api#7118]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy pobieraniu listy dostępnych usług przez parcel-management/delivery-services zaczęliśmy dostawać nazwy w wersji angielskiej. Np zamiast "Allegro One Kurier - dostawa jutro" teraz jest "Allegro One Courier - next-day delivery".
Uniemożliwia nam to parowanie id usługi z metodą dostawy wybraną przez klienta na zamówieniu, która wciąż jest po polsku.

**Comment by AureliuszBrussy** [comment]
Jeżeli chcesz być pewny, że wszystkie teksty zwracane będą w języku polskim, wysyłaj z każdym żądaniem nagłówek:
` Accept-Language: pl-PL`.

Dodam także, że aktualnie do mapowania metod dostawy z usługami dostawy najlepiej użyj po prostu id (`delivery.method.id` w parze z `deliveryServices.id`). Szerzej o tym piszemy [w newsie](https://developer.allegro.pl/news/wysylam-z-allegro-zmienimy-identyfikatory-uslug-dostawy-BvMdq20KEIm).
