### ISSUE TITLE
błąd w woocomerce

### ISSUE THREAD

**Issue by admich82** [allegro/allegro-api#7119]
Witam, chcę połączyć sklep woocomerce z allegro, ale mam problem, wtyczka wymaga zaznaczenia usług posprzedazowych, które zaimportowałem z allegro ale jak wybieram którąś z nich to mam taki błąd:

Nieoczekiwany błąd: UNPROCESSABLE_ENTITY: description zawiera niedozwolone znaki:   dla adresu https://api.allegro.pl/after-sales-service-conditions/implied-warranties/a3f01ff2-2c50-4549-97b5-44ee0d66504d i metody PUT

**Comment by PrzemyslawLukanowski** [comment]
Według naszych logów, w opisie warunków reklamacji korzystasz z niedozwolonego znaku u00a0 (non-breaking space). Zwróć uwagę, czy w opisie nie korzystasz gdzieś z dodatkowej spacji, np. na końcu któregoś zdania.

**Comment by admich82** [comment]
Sprawdziłem, raczej już wszystko jest ok a mam taki błąd:
Nieoczekiwany błąd: UNPROCESSABLE_ENTITY: corporate.period musi być podane UNPROCESSABLE_ENTITY: address musi być podane UNPROCESSABLE_ENTITY: individual.period musi być podane dla adresu https://api.allegro.pl/after-sales-service-conditions/implied-warranties/a3f01ff2-2c50-4549-97b5-44ee0d66504d i metody PUT

**Comment by PrzemyslawLukanowski** [comment]
Wygląda na to, że w Twoich warunkach reklamacji brakuje poniższych danych:

- **individual.period** - wymagane, czas na reklamację z tytułu rękojmi w formacie ISO 8601. Jako wartość możesz wskazać tylko lata, np. “P3Y” oznacza 3 lata.
- **corporate.period** - niewymagane, czas na reklamację z tytułu rękojmi dla przedsiębiorców w formacie ISO 8601. Jeżeli chcesz ją wyłączyć, nie przekazuj tego pola lub przekaż wartość null.
- **address** - wymagane, adres do reklamacji,

**Comment by admich82** [comment]
nie wiem gdzie jest błąd:
Nieoczekiwany błąd: UNPROCESSABLE_ENTITY: corporate.period musi być podane UNPROCESSABLE_ENTITY: individual.period musi być podane UNPROCESSABLE_ENTITY: address musi być podane dla adresu https://api.allegro.pl/after-sales-service-conditions/implied-warranties/a3f01ff2-2c50-4549-97b5-44ee0d66504d i metody PUT

**Comment by PrzemyslawLukanowski** [comment]
Widzę, że o 8:39 zaktualizowałeś dane przez stronę internetową, spróbuj teraz ponownie wykonać akcje w aplikacji. Jeśli problem nadal będzie występować, skontaktuj się proszę ze wsparciem aplikacji, z której korzystasz. Z naszej strony wspomniany wyżej błąd oznacza właśnie brak wymienionych informacji.

**Comment by admich82** [comment]
a mam teraz taki błąd

Nieoczekiwany błąd: UNPROCESSABLE_ENTITY: description zawiera niedozwolone znaki: , , dla adresu https://api.allegro.pl/after-sales-service-conditions/implied-warranties i metody POST

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z komunikatem, wygląda na to, że żądanie nadal zawiera niedozwolone znaki. Mogą to być np. odstępy pomiędzy numerem punktu a dalszą treścią (zastosowane odstępy przez TAB).

**Comment by admich82** [comment]
wpisuję po jednym punkcie i już przy pierwszym mam taki błąd:
Nieoczekiwany błąd: UNPROCESSABLE_ENTITY: description zawiera niedozwolone znaki: , dla adresu https://api.allegro.pl/after-sales-service-conditions/implied-warranties i metody POST

**Comment by admich82** [comment]
Witam, poradziłem już ale teraz przy  zwrotach mam znowu taki błąd:

Nieoczekiwany błąd: UNPROCESSABLE_ENTITY: returnOptions Niepoprawne opcje dodatkowe. Wymagane jest zdefiniowanie wszystkich dostępnych opcji: cashOnDeliveryNotAllowed, freeAccessoriesReturnRequired, refundLoweredByReceivedDiscount, businessReturnAllowed, collectBySellerOnly, abroadReturnTermsMayDiffer dla adresu https://api.allegro.pl/after-sales-service-conditions/return-policies/07f18928-25b3-4f37-8c39-1f57fb0917da i metody PUT

**Comment by PrzemyslawLukanowski** [comment]
Czy za wyrażeniem "Działalności Gospodarczej" nie robisz czasem dodatkowej wolnej przestrzeni, za pomocą spacji i entera? Czy na pewno wyrażenie zakończone jest kropką i nic za nią dalej się nie znajduje? Według naszych logów wygląda na to, że taki odstęp się pojawia.  Jeśli problem nadal będzie występować, to tak jak wspomniałem, skontaktuj się proszę ze wsparciem aplikacji, z której korzystasz, ponieważ wygląda to na błędne formatowanie tekstu po stronie aplikacji.

**Comment by admich82** [comment]
z kolei w zwrotach mam coś takiego

400 Nieoczekiwany błąd: BAD_REQUEST: Request body was not readable dla adresu https://api.allegro.pl/after-sales-service-conditions/return-policies/07f18928-25b3-4f37-8c39-1f57fb0917da i metody PUT

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z komunikatem musisz zdefiniować te pola. Przykład ze strony internetowej, o które pola chodzi:

<img width="973" alt="Zrzut ekranu 2023-05-24 o 08 11 40" src="https://github.com/allegro/allegro-api/assets/51473661/3a291936-2a5b-4b6d-8b43-b3798f64b4f3">


> 400 Nieoczekiwany błąd: BAD_REQUEST: Request body was not readable dla adresu https://api.allegro.pl/after-sales-service-conditions/return-policies/07f18928-25b3-4f37-8c39-1f57fb0917da i metody PUT

W przypadku tego błędu niestety nie widzimy dokładnie, co do nas wysyłasz, zatem sugerowałbym podobnie dostarczyć treści na początek w mniejszych partiach, a w razie problemów skontaktować się ze wsparciem aplikacji.

**Comment by admich82** [comment]
Próbowałem już wszystkich zmian i nadal 

400 Nieoczekiwany błąd: BAD_REQUEST: Request body was not readable dla adresu https://api.allegro.pl/after-sales-service-conditions/return-policies/07f18928-25b3-4f37-8c39-1f57fb0917da i metody PUT

**Comment by PrzemyslawLukanowski** [comment]
Wyślij nam w takim razie całą strukturę JSON, którą przesyłasz w żądaniu. Jeśli nie wiesz, jak zdobyć te dane, skontaktuj się ze wsparciem aplikacji.

**Comment by PrzemyslawLukanowski** [comment]
Czy w polu "withdrawalPeriod" nie przekazujesz przypadkiem wartość "PD"? Między P a D musisz umieścić liczbę dni na odstąpienie umowy.
