### ISSUE TITLE
Wystawianie i zarządzanie ofertami

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#712]
Rozumiem że przy pomocy **GET /offers/listing** mogę pobierać oferty. Chodzi mi o możliwość pobierania wszelkich ofert ze swojego konta => trwających i zakończonych. Czy tą metodą także są pobierane oferty zakończone ? Z tego co udało mi się wyczytać to oferty zakończone są dostępne 60 dni od momentu ich zakończenia ? Później przechodzą do archiwum i już nie będą dostępne poprzez API ? Czy zawsze limit zwracanych ofert to 100, jest możliwość aby np. zwracała 1000 ? Czy jest możliwość aby zwracała tylko określone pola oferty, które mnie interesują zamiast wszystkich ? Czy jest gdzieś dokładny opis filtrów jakie można używać ido czego służą ? Czy można np. filtrować po wielu wartościach dla danego filtra ?

Metodą **POST /sale/offers** tworzę drafty. Czy za pomocą tej metody mogę tworzyć od razu aktywną ofertę ? Czy mogę modyfikować wiele ofert naraz ale w taki sposób, że każdej ofercie zmieniam różne dane, np. w jednej zmienię cenę, w innej tytuł a jeszcze w innej jakieś parametry ?

Czy podczas tworzenia draftu **POST /sale/offers** mogę podawać ścieżki do zdjęć ze swojego serwera ? Bo jeśli nie to w jaki sposób zarządzać przypisywaniem zdjęć do produktów ?

W ogóle czy jest jakiś "Best practices" dotyczący zarządzania ofertami. Mówimy o dużej ilości ofert np. 10 000. W jaki sposób to wystawiać, modyfikować tak aby nie przekroczyć limitów itp.

Dodam, że konto Allegro z jakiego korzystam to konto Strefy MArek

**Comment by PawelTaberski** [comment]
W odpowiedzi na Twoje pytania:

1. Aby sterować ilością odpowiedzi skorzystaj z parametru limit, wszystkie dostępne parametry znajdziesz w opisie metody [GET /offers/listing](https://developer.allegro.pl/documentation/#/offers-listing/getListing). Ponadto więcej informacji o tym zasobie znajdziesz [tutaj](https://developer.allegro.pl/news/2018-07-03-Listing_ofert/).
2. Odnośnie metody POST /sale/offers możesz przy jej pomocy od razu uzupełnić ofertę kompletem danych, ale aktywujesz ją metodą [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#/offer-management/changePublicationStatusUsingPUT)
3. Nie możesz załączyć zdjęć ze swojego serwera. Wszelkie zdjęcia prześlesz przy pomocy metody[ POST na zasobie /sale/images](https://developer.allegro.pl/sale/#step-3-images).

Zachęcam do zapoznania się z naszym poradnikiem odnośnie wystawiania ofert przez REST API. Znajdziesz tam informacje krok po kroku w jaki sposób wystawić ofertę. Więcej informacji [tutaj](https://developer.allegro.pl/sale/).

**Comment by PawelTaberski** [comment]
W nawiązaniu do Twoich pytań:

1. Tak, nie zwracamy ofert zakończonych starszych niż 60 dni, nie przewidujemy wydłużenia tego czasu.
2. Można grupowo edytować oferty, ale zmieniać wtedy tylko jedno wybrane pole nie różne w różnych ofertach. Grupowo wyedytujesz oferty przy pomocy metody [PUT na zasobie /sale/offer-modification-commands/{commandId}](https://developer.allegro.pl/documentation/#/offer-management/modificationCommandUsingPUT)

**Comment by pietrach** [comment]
A w jaki sposób pobrać oferty zakończone, których od daty zakończenia nie upłynęło 60 dni ? Bo jak wywołałem GET /offers/listing to zwrócił tylko te aktywne

**Comment by pietrach** [comment]
Już wiem, trzeba dodać **searchMode=CLOSED** a czy jest możliwość pobrania i aktywnych i nieaktywnych naraz ?

**Comment by PawelTaberski** [comment]
Nie, jednocześnie możesz pobrać tylko jeden typ.

**Comment by pietrach** [comment]
**GET /offers/listing** czy jest możliwość aby sterować jakie pola ma pokazywać ta metoda bo teraz np. potrzebuje **external.id** a nie ma tego

**Comment by PawelTaberski** [comment]
Nie ma takiej możliwości i tego pola nie zwracamy w tej metodzie, gdyż jest to zewnętrzny ID, który nadaje sprzedający,  np. aby powiązać ofertę z produktem w swoim magazynie. Więcej na ten temat możesz znaleźć w [naszym poradniku](https://developer.allegro.pl/sale/).
