### ISSUE TITLE
Status aukcji "PREVIEW" w ramach zasobu sale/offers

### ISSUE THREAD

**Issue by Arzecki** [allegro/allegro-api#7120]
Dzień dobry,

w ramach zasobu sale/offers:

https://developer.allegro.pl/documentation#tag/User's-offer-information

informujecie o dostępności w query param:

![image](https://github.com/allegro/allegro-api/assets/134301689/2faa5996-d11a-4ef9-a053-6cc0baa90331)

tylko poniższych wartości pola publication.status:

"INACTIVE" "ACTIVE" "ACTIVATING" "ENDED"

Korzystając z Waszego API napotykamy jednak na dodatkowy status "PREVIEW" - prosiłbym o informację, kiedy aukcja zostaje oznaczona takim statusem i co on dokładnie oznacza?

**Comment by Arzecki** [comment]
W dokumentacji, w podglądowym cyklu życia aukcji też nie informujecie o dostępności takiego statusu w API:

https://developer.allegro.pl/tutorials/jak-wystawic-i-zarzadzac-ogloszeniem-K6r3Z47dKcy

![image](https://github.com/allegro/allegro-api/assets/134301689/ad89bf55-59f9-4a7a-a62e-cc40b1c6606d)

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać przykład oferty, dla której zwracamy taki status? Taki status nie jest udokumentowany i nie powinien być zwracany, dlatego zweryfikujemy tę sytuację.
