### ISSUE TITLE
Listing of 100k+ offers + update of products

### ISSUE THREAD

**Issue by Marek-ShopStore** [allegro/allegro-api#7121]
Hello,

we have been given task to list about 100k offers in Books segment.

Using data from live API, it seems 99% of product are already listed, but no one is selling them.
Also some of those product do have "dirty" data - duplicite Author in Title so we will have to put correct data to your system.

It seems we can do it all easily using sale/offers and sale/products/{productId}/change-proposals API functions.
I noticed limit of 9k request per minute in documentation, it's fine as we can split data to multiple batches.

My main question is speed and your server load. We did some tests and using search function sale/products and it took cca 0.2s per product for 100 products to load. When we tried 1000 products it did not finish as request times went up to 5s per product search.
We didn't even try async requests as we didn't want to overload your servers.

Please advise on best approach.

Thank you.

**Comment by PrzemyslawLukanowski** [comment]
Hello, the mentioned /sale/products resource is additionally limited with the Leaky Bucket algorithm - it means that if you exceed a certain number of requests per minute (RPM), the response time will be extended. In that case, you can spread your requests in time. When listing offers, please remember to use[ /sale/product-offers](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6) resources as /sale/offers will be removed at the end of the year.

**Comment by PrzemyslawLukanowski** [comment]
Unfortunately, those numbers are fluid and we can't share them publicly.

Please note that the leaky bucket limit applies only to retrieving product data via GET /sale/products resource. Other endpoints have the standard limit, which is 9000 requests per minute, so if you use POST /sale/product-offers with the following payload, without checking before whether we already have the given product or not:


```
{
  "productSet": [{
        "product": {
            "id": "{gtinNumber}"   
            "idType": "GTIN"    
  }}],
  "sellingMode": {
    "price": {
      "amount": "{yourPrice}",              
      "currency": "PLN"
    }
  },
  "stock": {
    "available": {yourStock}                   
  }
}
```

you will be able to list mentioned 99% of your products that we already have in our product catalog, in a shorter period of time than several days. For other requests for which we will return 422 status with userMessage `"Product not found for the given ID. The data necessary to create the offer and/or to propose the product was not provided"` you will have to create a payload [with all the necessary data](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-list-an-offer-assigned-to-a-new-product).

**Comment by Marek-ShopStore** [comment]
Thank you for providing us with detail about fast offer creation it will be helpful.

Problem is, client would rather NOT offer products with bad titles as it looks uncredible and unprofessional.

See for yourself:
def88035-4369-4bbb-a738-e6bca028d5be
**Jan Rejžek**: Jak tohle vůbec můžete otisknout! **Jan Rejžek**

At least half of products in Books category (ID 7) does have this issue.
Problem is that _title_ in your data: Jan Rejžek: Jak tohle vůbec můžete otisknout!
And there is _parameter_ Author: Jan Rejžek
And name is composed of Title + Author

Is there any way on your side to clean the date so we do not have to?

**Comment by PrzemyslawLukanowski** [comment]
> Is there any way on your side to clean the date so we do not have to?

I'm waiting for the information from the product data team who is investigating this case. I'll be back with an answer.

**Comment by PrzemyslawLukanowski** [comment]
@Marek-ShopStore Is there a possibility that you have a list of those products with invalid names - titles and ISBN?

**Comment by Marek-ShopStore** [comment]
@PrzemyslawLukanowski Nope, as it would mean that I have to browse all products using search function and check their name and it would take a lot of time - as we discussed above.

But if your team can search all products in categoryID 7 that title begins with Author:

See attached example of 30 products extracted from search of 100 products.

[Marek[](url)](url)
[products-example.xlsx](https://github.com/allegro/allegro-api/files/11555072/products-example.xlsx)

**Comment by PrzemyslawLukanowski** [comment]
Sure, I understand. This issue is still being analyzed by our teams. I'll be back with more info after the investigation.

**Comment by PrzemyslawLukanowski** [comment]
@Marek-ShopStore We were able to correct most of invalid Czech titles. Tomorrow we will end our internal operations and all titles with wrong names will be renamed.
