### ISSUE TITLE
Unable to add offer - Category error

### ISSUE THREAD

**Issue by dmsmatrix** [allegro/allegro-api#7126]
I got error response for my request 1 that _I can sell OTC veterinary medicinal products only in leaf category Non-Prescription Veterinary Drugs (321823)_, so I sent another request after correction with required leaf category, I got another error response for my request 2 as _OTC Veterinary Drugs (321823) does not match the product category Other (972)_.

**Request 1:**

**Endpoint**: POST https://api.allegro.pl/sale/product-offers

**Request**: {"parameters":[{"id":"11323","name":"Condition","valuesIds":["11323_1"]}],"productSet":[{"product":{"parameters":[{"id":"224017","name":"Manufacturer's code","values":["9310160613769"]},{"id":"248926","name":"Brand","valuesIds":["248926_968438"],"values":["968438"]},{"id":"225693","name":"EAN (GTIN)","values":["9310160613769"]}],"name":"Drontal Allwormer Tablets For Medium Dogs","category":{"id":"972"},"images":["https://dmsmatrix.net/direct/images/6345da9cefbe334158778b46_750x600.jpg"]},"quantity":{"value":1}}],"afterSalesServices":{"impliedWarranty":{"id":"67aa6cfa-07f0-422b-87de-eb485299c9cc","name":"Test Complaint 1"},"returnPolicy":{"id":"5c1be946-8ac4-4636-9ca1-706f828382f7","name":"Test Return 1"}},"delivery":{"handlingTime":"P3D","shippingRates":{"id":"18ffc1ce-c9af-414b-9f7e-1acc38046662","name":"UK Price"}},"publication":{"duration":null,"status":"ACTIVE","republish":true},"payments":{"invoice":"NO_INVOICE"},"name":"Drontal Allwormer Tablets For Medium Dogs","description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Drontal Allwormer Tablets For Medium DogsDrontal is recommended for the control of all gastrointestinal worms in dog includingRoundworm, Taxocaracanis, Taxascaris leoninaHookwormWhipwormTapewormPack Contains:5 Tablets (One Tablet Treats 10kg (22 lbs)Directions for Use:  Bodyweight (kg / lbs)Tablets1.5-2 / 3.3-5.5 1/42.6-5 / 5.6-111/25.1-10 / 11.1-221over 10 / over 221 tablet for every 10kg (22lbs) bodyweightDoes not control heartworm in dogs</p>"}]}]},"category":{"id":"972"},"images":["https://dmsmatrix.net/direct/images/6345da9cefbe334158778b46_750x600.jpg"],"sellingMode":{"price":{"amount":"329.63","currency":"PLN"},"format":"BUY_NOW"},"stock":{"available":0,"unit":"UNIT"},"external":{"id":"9310160613769"}}

**Headers**: {"expires":" 0","cache-control":" no-cache, no-store, max-age=0, must-revalidate","x-xss-protection":" 1; mode=block","pragma":" no-cache","x-frame-options":" DENY","trace-id":" e01cde70de127691","date":" Tue, 23 May 2023 12:57:14 GMT","x-content-type-options":" nosniff","strict-transport-security":" max-age=31536000 ; includeSubDomains","content-type":" application/json; charset=UTF-8","content-length":" 3019"}

**Response**: {"errors":[{"code":"ConstraintViolationException.ValidOfferName","message":"On Allegro, you can sell OTC veterinary medicinal products only in the category: Supermarket > Pet Supplies > Non-Prescription Veterinary Drugs after appropriate verification. Information about the account verification process allowing listing in this category is described in the Article of Help Center (https://allegro.pl/pomoc/dla-sprzedajacych/zasady-i-regulamin/jak-sprzedawac-weterynaryjne-produkty-lecznicze-bez-recepty-otc-wwYokqbBqFY). Detailed information about the rules for selling non-prescription veterinary drugs can be found on the website of the General Veterinary Inspectorate (https://www.wetgiw.gov.pl/nadzor-weterynaryjny/obrot-detaliczny-produktami-otc-na-odleglosc). If you are going to sell non-prescription drugs on Allegro, make sure you do this in compliance with the applicable regulations. You are not allowed to offer veterinary medicinal products for sale on Allegro Lokalnie. Such actions violate our Terms & Conditions. If you wish to offer veterinary medicinal products, list your offer in an appropriate category on Allegro.pl and be sure to meet the conditions described in this Article of Help Center (https://allegro.pl/pomoc/dla-sprzedajacych/zasady-i-regulamin/jak-sprzedawac-weterynaryjne-produkty-lecznicze-bez-recepty-otc-wwYokqbBqFY).","details":"ConstraintViolationException.ValidOfferName","path":"name","userMessage":"On Allegro, you can sell OTC veterinary medicinal products only in the category: Supermarket > Pet Supplies > Non-Prescription Veterinary Drugs after appropriate verification. Information about the account verification process allowing listing in this category is described in the Article of Help Center (https://allegro.pl/pomoc/dla-sprzedajacych/zasady-i-regulamin/jak-sprzedawac-weterynaryjne-produkty-lecznicze-bez-recepty-otc-wwYokqbBqFY). Detailed information about the rules for selling non-prescription veterinary drugs can be found on the website of the General Veterinary Inspectorate (https://www.wetgiw.gov.pl/nadzor-weterynaryjny/obrot-detaliczny-produktami-otc-na-odleglosc). If you are going to sell non-prescription drugs on Allegro, make sure you do this in compliance with the applicable regulations. You are not allowed to offer veterinary medicinal products for sale on Allegro Lokalnie. Such actions violate our Terms & Conditions. If you wish to offer veterinary medicinal products, list your offer in an appropriate category on Allegro.pl and be sure to meet the conditions described in this Article of Help Center (https://allegro.pl/pomoc/dla-sprzedajacych/zasady-i-regulamin/jak-sprzedawac-weterynaryjne-produkty-lecznicze-bez-recepty-otc-wwYokqbBqFY)."},{"code":"AvailableStockMustEqualToOneOrBeGreaterThanOne","message":"The stock level of items to be listed may not be lower than 1.","details":"AvailableStockMustEqualToOneOrBeGreaterThanOne","path":"stock.available","userMessage":"The stock level of items to be listed may not be lower than 1."}]}

**Request 2:**

**Endpoint**: POST https://api.allegro.pl/sale/product-offers

**Request**: {"productSet":[{"product":{"parameters":[{"id":"249260","name":"Purpose","valuesIds":["249260_1144649"]},{"id":"249443","name":"Country of the sale notification","valuesIds":["249443_1220007"]},{"id":"13288","name":"Brand","valuesIds":["13268_10"],"values":["10"]},{"id":"225693","name":"EAN (GTIN)","values":["9310160613769"]}],"name":"Drontal Allwormer Tablets For Medium Dogs","category":{"id":"321823"},"images":["https://dmsmatrix.net/direct/images/6345da9cefbe334158778b46_750x600.jpg"]},"quantity":{"value":1}}],"afterSalesServices":{"impliedWarranty":{"id":"67aa6cfa-07f0-422b-87de-eb485299c9cc","name":"Test Complaint 1"},"returnPolicy":{"id":"5c1be946-8ac4-4636-9ca1-706f828382f7","name":"Test Return 1"}},"delivery":{"handlingTime":"P3D","shippingRates":{"id":"18ffc1ce-c9af-414b-9f7e-1acc38046662","name":"UK Price"}},"publication":{"duration":null,"status":"ACTIVE","republish":true},"payments":{"invoice":"NO_INVOICE"},"messageToSellerSettings":{"mode":"OPTIONAL"},"name":"Drontal Allwormer Tablets For Medium Dogs","description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Drontal Allwormer Tablets For Medium DogsDrontal is recommended for the control of all gastrointestinal worms in dog includingRoundworm, Taxocaracanis, Taxascaris leoninaHookwormWhipwormTapewormPack Contains:5 Tablets (One Tablet Treats 10kg (22 lbs)Directions for Use:  Bodyweight (kg / lbs)Tablets1.5-2 / 3.3-5.5 1/42.6-5 / 5.6-111/25.1-10 / 11.1-221over 10 / over 221 tablet for every 10kg (22lbs) bodyweightDoes not control heartworm in dogs</p>"}]}]},"category":{"id":"321823"},"images":["https://dmsmatrix.net/direct/images/6345da9cefbe334158778b46_750x600.jpg"],"sellingMode":{"price":{"amount":"329.63","currency":"PLN"},"format":"BUY_NOW"},"stock":{"available":0,"unit":"UNIT"},"external":{"id":"9310160613769"}}

**Headers**: {"expires":" 0","cache-control":" no-cache, no-store, max-age=0, must-revalidate","x-xss-protection":" 1; mode=block","pragma":" no-cache","x-frame-options":" DENY","trace-id":" 5e43855c2419e618","date":" Tue, 23 May 2023 13:10:14 GMT","x-content-type-options":" nosniff","strict-transport-security":" max-age=31536000 ; includeSubDomains","content-type":" application/json; charset=UTF-8","content-length":" 508"}

**Response**: {"errors":[{"code":"CATEGORY_MISMATCH","message":"Existing Product related to submitted data was found. The provided category `Leki weterynaryjne bez recepty` (321823) does not match the existing product category `Pozostałe` (972)","details":null,"path":"productSet[0].product.category.id","userMessage":"A product from our database has been recognized based on the specified data. The indicated category `Leki weterynaryjne bez recepty` (321823) does not match the product category: `Pozostałe` (972)."}]}

Can you help me in resolving this issue.

Thanks in advance.

**Comment by PrzemyslawLukanowski** [comment]
Based on your second request we have found a product in our database, but the data in the product (category to be precise) differs from the data in your request. The product in our database, which has the 972 category id, was also created by your account. You can report a mistake in the product data - via [www](https://allegro.pl/moje-allegro/sprzedaz/produkt/zglos-blad/bd0a1a7b-aec4-4aec-b1cf-74dd080444c1) or [API](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-report-incorrect-data-in-a-product).

**Comment by dmsmatrix** [comment]
Then why Allegro not updated my product even if Allegro suggested to use Non-Prescription Veterinary Drugs (321823) category instead Pozostałe (972) category. Or you are saying that it wont update using API in such case and I have to report to change .

**Comment by PrzemyslawLukanowski** [comment]
Exactly, the product won't be updated, unless you report it using the website form or mentioned API resource.

**Comment by dmsmatrix** [comment]
Ok...got it...thanks

**Comment by dmsmatrix** [comment]
I have another doubt, its regarding *ambiguousValueId*. I have mentioned two requests for the same. In both requests, I have not provided _values_ field to my ambiguousValueIds. I didn't get an error response for my request 1, whereas I get an error response for my request 2. Can you please let me know the reason for the same?

**Request 1:**
**Endpoint** : GET https://api.allegro.pl/sale/product-offers/13746691591/operations/3c35c803-0031-4a14-9932-4c42267f2c82
**Request** : null,
**Headers** : {
	"expires" : " 0",
	"cache-control" : " no-cache, no-store, max-age=0, must-revalidate",
	"x-xss-protection" : " 1; mode=block",
	"pragma" : " no-cache",
	"x-frame-options" : " DENY",
	"location" : " https://api.allegro.pl/sale/product-offers/13746691591",
	"trace-id" : " 2b99c180dffceca4",
	"date" : " Wed, 24 May 2023 11:55:43 GMT",
	"strict-transport-security" : " max-age=31536000 ; includeSubDomains",
	"x-content-type-options" : " nosniff",
	"content-length" : " 2655",
	"content-type" : " application/vnd.allegro.public.v1+json; charset=UTF-8"
},
**Response** : {"name":"Acne Scar Removal Cream","productSet":[{"product":{"id":"37babe27-1104-489a-83cb-253292d5f5ad","publication":{"status":"LISTED"},"parameters":[{"id":"213814","name":"Postać","values":["krem"],"valuesIds":["213814_263874"],"rangeValue":null},{"id":"213970","name":"Przeznaczenie","values":["inne"],"valuesIds":["213970_265358"],"rangeValue":null},{"id":"129369","name":"Marka","values":["bez marki"],"valuesIds":["129369_1681660"],"rangeValue":null},{"id":"225693","name":"EAN (GTIN)","values":["6938611751483"],"valuesIds":null,"rangeValue":null}]},"quantity":{"value":1}}],"parameters":[{"id":"11323","name":"Stan","values":["Nowy"],"valuesIds":["11323_1"],"rangeValue":null}],"images":["https://a.allegroimg.com/original/11c952/a951951147c18f6a25a4b0601aa3"],"afterSalesServices":{"impliedWarranty":{"id":"31750643-2418-41a6-ae1c-7325836d4a3f"},"returnPolicy":{"id":"f2090ff2-e66f-4379-8531-17d584b4cb9a"},"warranty":null},"payments":{"invoice":"NO_INVOICE"},"sellingMode":{"format":"BUY_NOW","price":{"amount":"171.03","currency":"PLN"},"startingPrice":null,"minimalPrice":null},"stock":{"available":170,"unit":"UNIT"},"location":{"countryCode":"CN","province":null,"city":"Wuhan","postCode":"430000"},"delivery":{"shippingRates":{"id":"326a3ebd-c83b-4bbb-b4db-869c851048e8"},"handlingTime":"PT72H","additionalInfo":null,"shipmentDate":null},"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Acne Scar Removal Cream. FEATURES: Removal Stretch Marks, Scar-removing Balance, Surgical Scars. Stretch Marks, Acne Removal Scars, Removal Burn Removal Scars. Spot Treatment for Acne, Lighten Dark. Acne Treatment. Removal Scar Hyperplasia, Removal Bruises Essence. SPECIFICATIONS: Item Type: Cream Feature: Pigmentation Corrector Use: Face Ingredient: Plant Extract, Gentle Formula Item Type : Acne Scar Removal Cream, Body Cream, Face Cream.</p>"}]}]},"external":{"id":"6938611751483"},"category":{"id":"258261"},"tax":null,"taxSettings":null,"sizeTable":null,"discounts":{"wholesalePriceList":null},"contact":null,"fundraisingCampaign":null,"messageToSellerSettings":null,"attachments":[],"b2b":null,"additionalServices":null,"compatibilityList":null,"additionalMarketplaces":{"allegro-cz":{"sellingMode":null,"publication":{"state":"NOT_REQUESTED"}}},"id":"13746691591","language":"pl-PL","publication":{"status":"ACTIVE","duration":null,"endedBy":null,"endingAt":null,"startingAt":null,"republish":true,"marketplaces":{"base":{"id":"allegro-pl"},"additional":[]}},"validation":{"errors":[],"warnings":[],"validatedAt":"2023-05-24T11:54:34.759Z"},"createdAt":"2023-05-24T11:54:34.000Z","updatedAt":"2023-05-24T11:54:35.332Z"}

**Request 2:**
**Endpoint** : POST https://api.allegro.pl/sale/product-offers
**Request** : {"afterSalesServices":{"impliedWarranty":{"id":"31750643-2418-41a6-ae1c-7325836d4a3f","name":"Tousu"},"returnPolicy":{"id":"f2090ff2-e66f-4379-8531-17d584b4cb9a","name":"Tuihuo"}},"delivery":{"handlingTime":"P3D","shippingRates":{"id":"326a3ebd-c83b-4bbb-b4db-869c851048e8","name":"sunyou"}},"publication":{"duration":null,"status":"ACTIVE","republish":true},"payments":{"invoice":"NO_INVOICE"},"parameters":[{"id":"11323","name":"Condition","valuesIds":["11323_1"]}],"productSet":[{"product":{"parameters":[{"id":"129369","name":"Brand","valuesIds":["129369_1681660"]},{"id":"129767","name":"Waterproof Product","valuesIds":["129767_1"]},{"id":"452","name":"SPF","valuesIds":["452_7"]},{"id":"129877","name":"Type","valuesIds":["129877_32"]},{"id":"129876","name":"Features","valuesIds":["129876_8"]},{"id":"225693","name":"EAN (GTIN)","values":["6938611751247"]}],"name":"Niacinamide Vc Freeze-dried Powder","category":{"id":"45669"},"images":["https://dmsmatrix.net/direct/images/646dae37eba20b5a2b6d202f_750x600.jpg"]},"quantity":{"value":1}}],"name":"Niacinamide Vc Freeze-dried Powder","description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Skin nicotinamide vc freeze-dried powder beauty, brightening, skin repairing, coloring, moisturizing and rejuvenation2pcs Feature: Tightens the skin, improves contours and fades facial lines. Deeply moisturizing, repairing and nourishing the skin, improving skin condition. Evens out skin tone and enhances skin plumpness. Improve skin looseness, increase skin elasticity, and make skin supple and smooth. Moisturizing and locking water, moisturizing and refreshing, multi-dimensional nourishing and repairing Specification:      Product name:Niacinamide vc Weightabout 16g Shelf Life:3 Years Package Included:2 x Niacinamide Vc Freeze-Dried Powder</p>"}]}]},"category":{"id":"45669"},"images":["https://dmsmatrix.net/direct/images/646dae37eba20b5a2b6d202f_750x600.jpg"],"sellingMode":{"price":{"amount":"53.66","currency":"PLN"},"format":"BUY_NOW"},"stock":{"available":237,"unit":"UNIT"},"external":{"id":"6938611751247"}}
**Headers** : {"expires":" 0","cache-control":" no-cache, no-store, max-age=0, must-revalidate","x-xss-protection":" 1; mode=block","pragma":" no-cache","x-frame-options":" DENY","trace-id":" bb0b474afdc2f2df","date":" Wed, 24 May 2023 11:55:31 GMT","x-content-type-options":" nosniff","strict-transport-security":" max-age=31536000 ; includeSubDomains","content-type":" application/json; charset=UTF-8","content-length":" 1016"}
**Response** : {"errors":[{"code":"ProductValidationException","message":"Product has invalid values [ValidatedParameter[parameter=SimpleParameter{id='129877', values=[ParameterValue{id='129877_32', value='inny'}]}, name=Rodzaj, validationErrors=[ValidationError{value='inny', valueId='129877_32', errorType=VALUE_AMBIGUOUS, illegalCharacters='null'}], isIdentifyingParameter=false, isParameterUsedInRuleSet=false, isRequiredParameter=true], ValidatedParameter[parameter=SimpleParameter{id='129876', values=[ParameterValue{id='129876_8', value='inne'}]}, name=Właściwości, validationErrors=[ValidationError{value='inne', valueId='129876_8', errorType=VALUE_AMBIGUOUS, illegalCharacters='null'}], isIdentifyingParameter=false, isParameterUsedInRuleSet=true, isRequiredParameter=true]] in category: 45669","details":null,"path":"productSet[0].product","userMessage":"Nieprawidłowe wartości parametrów: [parameter = Rodzaj [ Wartość niejednoznaczna - inny] , parameter = Właściwości [ Wartość niejednoznaczna - inne]]"}]}

**Comment by PrzemyslawLukanowski** [comment]
This request is connected with a different category - not all parameters require providing value for ambigousValue. It is required for those parameters that identify the product (so those parameter which are marked as `parameters.options.identifiesProduct` in the response to GET /sale/products/{productID}).

**Comment by dmsmatrix** [comment]
Are you saying `parameters.options.describesProduct` because I cant find `parameters.options.identifiesProduct`? If yes, how can I pass custom value for my parameter other than dictionary if `parameters.options.customValuesEnabled` is not enabled? I usually add custom value to my parameter other than dictionary value only in case `parameters.options.customValuesEnabled` is enabled.

**Comment by PrzemyslawLukanowski** [comment]
> Can parameters.options.describesProduct of GET /sale/categories/{categoryId}/parameters API be used instead of parameters.options.identifiesProduct of GET /sale/products/{productID} to check the same because I don't use GET /sale/products/{productID} API to first fetch products and then create offer, I directly use POST /sale/product-offers API to create offers.

To be precise -` parameters.options.describesProduct` tells you whether the parameter should be provided in the `productSet.product.parameters`  (for product parameters) or in `parameters` (for offer parameters) field. Parameters that identify products always be the parameters that have `parameters.options.describesProduct: true`, but not always you will be able to provide a custom value for them. For that kind of parameters, you should choose value from dictionary that is not an ambiguous value.

> If yes, how can I pass custom value for my parameter other than dictionary if parameters.options.customValuesEnabled is not enabled? I usually add custom value to my parameter other than dictionary value only in case parameters.options.customValuesEnabled is enabled. If I can pass custom value for my parameter if parameters.options.describesProduct is enabled, then let me know what value should be there.

If a custom value is not enabled for the given parameter, there's no way to provide a custom value for such a parameter. You can omit "values" field in this case, but if the parameter identifies the product, then you need to choose a value from the list.

> For example, parameter id 213970 of Request 1 and parameter id 129877 of Request 2 both has parameters.options.describesProduct field enabled of GET /sale/categories/{categoryId}/parameters API and I have not sent any value in values for both. Though Request 2 is getting error response but Request 1 is getting success response.

That's because the first parameter does not identify the product (so you don't need to choose a specific value, it could be ambiguous) and the second identify (so you need to select a value from the list, other than ambiguous, cause customValue is not enabled for this parameter).

**Comment by dmsmatrix** [comment]
Why we should take help of GET /sale/products/{productID} API to know `parameters.options.identifiesProduct` setting of parameter to use custom value in values alongwith ambiguousValueId in valuesId. This setting should be at paramter level itself or its category level but not in any other APIs like get products or get offers. What will be the case if I want to add/propose a product using POST /sale/product-proposals, how can I use GET /sale/products/{productID} before adding it.

{
	"id":"213970",
	"name":"Purpose",
	"valuesIds":[
		"213970_265358"
	]
}

{
	"id":"129877",
	"name":"Type",
	"valuesIds":[
		"129877_32"
	]
}

Please tell me how can I distinguish these both properties for values field selection where both has ambiguousValueId value and customValuesEnabled as false.

**Comment by dmsmatrix** [comment]
O...thanks for the suggestion. But as its given in the list, one of our clients has used it...we cant suggest them to use appropriate values...in that case I have to remove ambiguousId option from the list to avoid further confusion. But that is not right way I guess if Allegro has provided it.

**Comment by dmsmatrix** [comment]
I know that for given product request, parameters "Purpose" and "Type" should have used given values from list. However, our clients are facing issues in adding given values from the list of parameters. Sometimes they can't use given values from the list for most of the parameters due to their products specifications and in that case they try to use "Other" value with customized value for some parameters. But despite option "Other" provided in the list...Allegro doesn't accept it. I think Allegro should accept any value after using "Other" option despite of "Other" is mentioned as **ambiguousValueId** or not. If Other giving issue for some parameters, why Allegro keeps it in the list. Please provide your feedback.

**Comment by PrzemyslawLukanowski** [comment]
>  they try to use "Other" value with customized value for some parameters. But despite option "Other" provided in the list...Allegro doesn't accept it

Can you send us some samples of customized values that were not accepted? If the `customValuesEnabled` is `true` we accept all the values except the "dirty" data such as: "other" (because it's just a repetition of the selected ambiguous value), "aaa", "abcd", etc.

**Comment by dmsmatrix** [comment]
Please check trace-id: 74e5d0033ae0c29a

In its request we have provided:

{
    "id":"248544",
    "name":"Type",
    "valuesIds":[
        "248544_929227"
    ],
    "values":[
        "Other"
    ]
}

Where parameter **Type** has `ambiguousValueId` = 248544_929227 & `customValuesEnabled` = false, as customValuesEnabled is false and `ambiguousValueId` selected by client, I have provided hard-coded **Other** in values, which is giving me an error response. What should I do in this case, Shall I allow client to add `customValuesEnabled` or use another custom value instead **Other**?

**Comment by PrzemyslawLukanowski** [comment]
If customValuesEnabled = false any attempt to provide value in the "values" field will end with an error. In this case, you should choose a value from the list of available values.

**Comment by dmsmatrix** [comment]
Ok got it...

Now I am not using "Other" as custom value in values...but just selecting value from dictionary _25268_512: other_ as following:
{
    "id":"25268",
    "name":"Handle Type",
    "valuesIds":[
        "25268_512"
    ]
}

Still I am getting error:

_[ProductValidationException] productSet[0].product =>  Nieprawidłowe wartości parametrów: [parameter = Zastosowanie [ Wartość niejednoznaczna - inne zastosowanie] , parameter = Typ uchwytu [ Wartość niejednoznaczna - inny] , parameter = Typ ostrza [ Wartość niejednoznaczna - inny]]_

Trace-id: 9ea9fdeb6dc0641a

**Comment by PrzemyslawLukanowski** [comment]
That's because the user should select a proper value from a list of available values that is not an ambiguous value. I'm sure the item that the seller wants to list definitely shouldn't be in the category Home and Garden -> Tools -> Accessories and Equipment -> **Chisels**. If the seller selects the right category, then I think he will find the right values to choose in all parameters.

**Comment by dmsmatrix** [comment]
But why "Other" value is given in the list if it should not be used...It is there in the list so layman client using it if they don't get valid value other than "Other".

**Comment by PrzemyslawLukanowski** [comment]
„Other” value can be chosen for some parameters, for example when custom value is enabled. When custom value is disabled, it indicates that the list of possible values is sufficient and the user should select one of them. If your operation was successful, please imagine how many invalid products, with low-quality data, we could have in our product catalog - this would affect the experience of both other sellers and buyers.

**Comment by dmsmatrix** [comment]
Thats  true...I will handle this thing in my system for clients...Thanks for the help

**Comment by dmsmatrix** [comment]
We suggest you to please remove Other value from parameter if customValuesEnabled is false...so that this will not create problems for future sellers or integrators

**Comment by PrzemyslawLukanowski** [comment]
Unfortunately, that is not possible - there are parameters that are not identifying a product or are not required to create a product, or they just are offer parameters, not connected with the product, and for those parameters, it's still possible to choose the "Other" value.
