### ISSUE TITLE
Kod pocztowy odbiorcy jest niedostępny

### ISSUE THREAD

**Issue by drzemik** [allegro/allegro-api#7129]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [x ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ x] inny / other

:beetle: **Opis / Description**
Request:  parcel-management/parcel-create-commands/
Parametry:
array(5) {
  ["serviceId"]=>string(36) "a3b4db98-4a70-4542-84ee-c642604d9d8a"
  ["receiver"]=>array(6) {
    ["address"]=>array(4) {
      ["street"]=>string(17) "ul. Na Ostrowiu 1"
      ["postCode"]=>string(6) "80-958"
      ["city"]=>string(7) "Gdańsk"
      ["countryCode"]=>string(2) "PL"
    }
    ["email"]=>string(35) "rmwwr1e7es+50df268d9@allegromail.pl"
    ["name"]=>string(15) "Daniel Woźniak"
    ["company"]=>string(17) "EN-PRO sp. z o.o."
    ["phone"]=>string(9) "790017576"
    ["pointId"]=>string(0) ""
  }
  ["pickup"]=>array(4) {
    ["address"]=>array(4) {
      ["street"]=>string(12) "Bakaliowa 26"
      ["postCode"]=>string(6) "05-080"
      ["city"]=>string(9) "Mościska"
      ["countryCode"]=>string(2) "PL"
    }
    ["company"]=>string(8) "ERPATECH"
    ["email"]=>string(17) "biuro@erpatech.pl"
    ["phone"]=>string(14) "(22) 431-05-00"
  }
  ["items"]=>array(1) {
    [0]=>array(4) {
      ["dimensions"]=>array(3) {
        ["height"]=>array(2) {
          ["value"]=>float(25)
          ["unit"]=>string(10) "CENTIMETER"
        }
        ["width"]=>array(2) {
          ["value"]=>string(2) "25"
          ["unit"]=>string(10) "CENTIMETER"
        }
        ["depth"]=>array(2) {
          ["value"]=>string(2) "25"
          ["unit"]=>string(10) "CENTIMETER"
        }
      }
      ["weight"]=>array(2) {
        ["value"]=>string(2) "10"
        ["unit"]=>string(8) "KILOGRAM"
      }
      ["description"]=>string(17) "elektronarzędzia"
      ["type"]=>string(7) "PACKAGE"
    }
  }
  ["type"]=>string(7) "PACKAGE"
}
Response:
object(stdClass)#76 (4) {
  ["id"]=>string(36) "d7a9a6f4-2f77-4a4e-a2ef-20d39689d11e"
  ["parcelId"]=>NULL
  ["status"]=>string(5) "ERROR"
  ["errors"]=>array(1) {
    [0]=>object(stdClass)#74 (5) {
      ["code"]=>string(5) "ERROR"
      ["message"]=>string(33) "Receiver post code is unavailable"
      ["details"]=>NULL
      ["path"]=>string(25) "receiver.address.postCode"
      ["userMessage"]=>string(39) "Kod pocztowy odbiorcy jest niedostępny"
    }
  }
}
Kod pocztowy odbiorcy jest przekazywany, więc skąd ten komunikat?

**Comment by AureliuszBrussy** [comment]
Korzystamy z listy kodów pocztowych Poczty Polskiej - kod pocztowy z przykładu (80-958) na ten moment nie istnieje [w bazie](https://kody.poczta-polska.pl/#/) Poczty.

**Comment by drzemik** [comment]
Ale ten kod pocztowy został pobrany z GUS na postawie NIPu.

**Comment by AureliuszBrussy** [comment]
Rozumiem, natomiast tak jak wspomniałem, zgodnie z bazą Poczty Polskiej, ten kod pocztowy aktualnie nie istnieje (a to Poczta Polska nadaje kody pocztowe). Tutaj pozostaje kwestia wyjaśnienia sytuacji pomiędzy sprzedającym, a kupującym.

**Comment by drzemik** [comment]
Co tu wyjaśniać? Problem nie dotyczy kupującego, ale niespójności pomiędzy GUSem i Pocztą Polską. 
Może Państwo mają nieaktualną bazę?
A czy jest jakiś sposób, aby obejść ten problem?

**Comment by AureliuszBrussy** [comment]
Tak jak wspomniałe, kody pocztowe nadaje Poczta Polska i takiego kody pocztowego aktualnie nie ma w ich bazie. Możesz to nawet sprawdzić w [ich wyszukiwarce kodów](https://kody.poczta-polska.pl/#/). Obejściem problemu mogłoby być ustalenie faktycznego aktualnego kody pocztowego kupującego - czyli pozostaje wyjaśnienie sytuacji pomiędzy stronami transakcji.

**Comment by drzemik** [comment]
Problem rozwiązany. Pobraliśmy kod 80-873 dla tego adresu z bazy poczty.
Chciałbym jeszcze dodać, że nieprawidłowy kod jest również w adresie kupującego zamówienia allegro i ten cały adres został przeniesiony do parametru metody parcel-management/parcel-create-commands/
Dziękuję za pomoc.
