### ISSUE TITLE
Pobranie wszystkich kategorii

### ISSUE THREAD

**Issue by GyniO** [allegro/allegro-api#713]
Zależy mi na pobraniu wszystkich kategorii z allegro do mojego sklepu. W webapi otrzymywałem pełną listę z ustawionymi parentami i to rozwiązanie dawało dużo pole do popisu jeżeli chodzi o obsługę wyboru kategorii.
W rest zwracane są jedynie subkategorie pierwszego poziomu z kategorii, co niestety robi problem i synchronizowanie ich w obecnej chwili wiąże się z dużą ilością requestów ( mowa o setkach) co jest  nieoptymalne. 

Proszę o jakąś alternatywę, która rozwiąże problem, bo przy duża ilości requestów w krótkim czasie będzie wiązać się z blokowaniem przez was requestów.

**Comment by PawelTaberski** [comment]
Tak, jak już wspominałem Tobie w innym wątku nie ma możliwości pobrania przez REST API całego drzewa kategorii jak przez wielokrotne odpytywania.

**Comment by FromAnyHole** [comment]
@GyniO - nie spodziewaj się tu rozwiązania, wszystko zmierza (w sposób celowy) do co najwyżej obsługi pojedynczego konta, czyli Amazollegro chce docelowo wykosić wszelką konkurencję w swoich usługach, które rozwija kradnąc "zaobserwowane" pomysły innych i blokując po czasie różne elementy w serwisie oraz w API.

**Comment by PawelTaberski** [comment]
Tak, jak pisałem nie ma możliwości przez REST API pobrania jednym requestem całego drzewa.

**Comment by Pawikoski** [comment]
Jakby ktoś potrzebował to posiadam wszystkie kategorie (id + breadcrumb). Mogę przekonwertować do dowolnego formatu pliku, wedle potrzeb.
Przykład jednego rekordu w JSON:
`{"breadcrumb": "Elektronika > Fotografia > Akcesoria fotograficzne > Akcesoria wodoszczelne", "category_id": "28155"}`
Łącznie plik zawiera 25669 rekordów.
Mogę również przygotować listę kategorii z wybranej kategorii głównej, np. tylko z kategorii 'Elektronika'

Zapraszam do kontaktu: pawikoski@gmail.com
