### ISSUE TITLE
Pobieranie listy aukcji danego użytkownika łączenie ze statystykami do tych aukcji?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#7130]
Czy za pomocą restapi mogę pobrać aktywne aukcje danego użytkownika i statystyki do nich? 
Coś jak wszystkie przedmioty sprzedającego dostępne na stronie?

**Comment by AureliuszBrussy** [comment]
Rozumiem, że chodzi o pobranie takich danych dla dowolnego użytkownika, a nie własnych ofert danego sprzedającego? Udostępniamy endpoint [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing), natomiast są tam ograniczenia: przede wszystkim skorzystać mogą z niego tylko [zweryfikowane aplikacje](https://developer.allegro.pl/news/zmienilismy-regulamin-rest-api-v8Wdyj7mWfn). 

Do wyszukiwania ofert konkretnego sprzedającego można skorzystać z parametru `seller.id`. Nie zwrócimy jednak wszystkich ofert - offset ograniczony jest do 600. Popularność zwracamy w zakresach: 0, [1-5], [6-10], [11-20], [21-50], [51-100], [101+].
