### ISSUE TITLE
Różnica ilości pomiędzy zamówieniem a packing slipem

### ISSUE THREAD

**Issue by TomekTraczyk** [allegro/allegro-api#7131]
Witam,
Od kilku dni zauważyłem rozjazd w otrzymywanych przez api ilością sztuk w zamówieniach a ilością sztuk w odpowiadających packing slipach. Czy jest możliwość weryfikacji, czy wynika to z błędnej zwrotki z Waszej strony?

**Comment by PrzemyslawLukanowski** [comment]
Co masz dokładnie na myśli przez ilości sztuk w packing slipach? Czy mógłbyś to doprecyzować i podać przykład takiego zamówienia i rozbieżności?

**Comment by TomekTraczyk** [comment]
Brak precyzji wynika z tego, że komunikujemy się przez soap api, które jak rozumiem jest deprecated i nie mogę znaleźć na nie dokumentacji.
Endpoint 'getPurchaseOrder' (soap) pobieramy zamówienia z Waszego systemu. W każdym zamówieniu jest informacja m.in o ilości zamówionych sztuk, oraz id zamówienia. 
Endpoint 'getPackingSlip' (soap), pobieramy packing slipy z Waszego systemu. W każdym slipie jest m.in numerz zamówienia i ilość zamówionych sztuk. Slipy dopasowywujemy do zamówień na podstawie numeru zamówienia oraz ilości zamówionych produktów.
Od kilku dni te ilości się nie zgadzają (dla numeru zamówienia np. PO-703929). Ilość zamówionych sztuk, którą dostaliśmy z metody pierwszej (getPurchaseOrder), nie zgadza się z ilością sztuk które są w packing slipie (z getPackingSlip) z tym  numerem zamówienia.

**Comment by PrzemyslawLukanowski** [comment]
WebAPI zostało przez nas wyłączone z końcem 2020, było to opatrzone szeroką akcją komunikacyjną oraz planem wygaszania poszczególnych metod, więc przyznam, że jestem nieco zaskoczony tym wpisem :) Dodatkowo nie posługujemy się identyfikatorami w takim formacie jak PO-703929. Jedyne wspierane przez nas zasoby  REST API w kontekście obsługi zamówień opisaliśmy [w tym poradniku](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR). Znajdziesz tam cały opis tego procesu.

**Comment by TomekTraczyk** [comment]
![obraz](https://github.com/allegro/allegro-api/assets/86965379/079242c8-7b4c-45ea-8899-789e7a6dbfcb)
Udało mi się znaleźć dokumentację i jak widać purchaseId jest w takim formacie :P

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, jednak jest to już nieaktualna dokumentacja, poprawnie zwracany przez nas format to UUID, np. ten z [dokumentacji](https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET) - 29738e61-7f6a-11e8-ac45-09db60ede9d6  :)
