### ISSUE TITLE
Maksymalne długości pól odbiorcy

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#7132]
Witam, w dokumentacji niema tego sprecyzowanego , a API potrafi zwracać błąd o maksymalnej długości pól dla zasobu https://developer.allegro.pl/documentation/#operation/createNewParcel. Czy mógłbym prosić o sprecyzowanie jakie są dokładnie maksymalne wartości dla pól odbiorcy?

**Comment by PrzemyslawLukanowski** [comment]
Wartości te są zależne od API konkretnego przewoźnika:


**DPD**:
 - receiver:
   - name - długość nieokreślona
   - company - 80
   - email - długość nieokreślona
   - city - 30
   - street - 30

**UPS**:
 - receiver:
   - name - 30
   - company - 30
   - email - długość nieokreślona
   - city - 30
   - street - 35

**Poczta Polska**:
 - receiver:
   - name - 60
   - company - 30
   - email - 60
   - city - 100
   - street - 75

**Orlen**:
 - receiver:
   - name - długość nieokreślona
   - company - 30
   - email - 60
   - city - 30
   - street - 100

**Inpost**:
 - receiver:
   - name - długość nieokreślona
   - company - 80
   - email - długość nieokreślona
   - city - 100
   - street - 100

**DHL**:
 - receiver:
   - name - 60
   - company - 60
   - email - 60
   - city - 100
   - street - 60

**Fedex**:
 - receiver:
   - name - długość nieokreślona
   - company - 100
   - email - długość nieokreślona
   - city - 100
   - street - 30

**GLS**:
 - receiver:
   - name - długość nieokreślona
   - company - 80
   - email - długość nieokreślona
   - city - 100
   - street - 40
