### ISSUE TITLE
Problem z utworzeniem produktu (errorType=VALUE_AMBIGUOUS)

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#7133]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
trace-id: 'dde4745714d74373'

Witam. Dla kategorii 87981 i innych nie jesteśmy w stanie dodać produktu z własną marką. Przykładowy fragment jsona:
```
{'id': 7108, 'valuesIds': ['7108_52'], 'values': ['ButyModne']},
```
A w odpowiedzi taki error:
```
{'errors': [{'code': 'InvalidProductValueException',
   'message': "Product has invalid values [ValidatedParameter[parameter=SimpleParameter{id='7108', values=[ParameterValue{id='7108_52', value='inna'}]}, name=Marka, validationErrors=[ValidationError{value='inna', valueId='7108_52', errorType=VALUE_AMBIGUOUS, illegalCharacters='null'}], isIdentifyingParameter=true, isParameterUsedInRuleSet=false, isRequiredParameter=true]] in category: 87981",
   'details': None,
   'path': 'parameters',
   'userMessage': 'Nieprawidłowe wartości parametrów: [parameter = Marka [ Wartość niejednoznaczna - inna]]'}]}
```
Sporo produktów jakie posiadamy jest importowana i de facto nie posiada marki. Czy jest jakiś sposób na wystawienie takich produktów?

**Comment by anih** [comment]
A czy informacja w błędzie mogłaby dawać taką informację, bo bieżąca jest wyjątkowo myląca.

**Comment by AureliuszBrussy** [comment]
Dziękuję za sugestię - zgłoszę ją do zespołu odpowiedzialnego za usługę.
