### ISSUE TITLE
Dzień dobry,  Piszę w sprawie dostępu do publicznego endpointu API: /offers/listing  Jesteśmy w trakcie realizacji projektu który pozwoli nam uruchomić sprzedaż z Allegro. Potrzebujemy dostęp do tego API endpointu aby móc zakończyć prace nad integracją naszej nowo powstałej aplikacji z waszym systemem.   To jest nasz CLIENT ID: fdb2ab0a5e0a4c6fbd76d62abc7d0867  Proszę o pozytywne rozpatrzenie naszej prośby

### ISSUE THREAD

**Issue by CarPartsGroup** [allegro/allegro-api#7134]

**Comment by AureliuszBrussy** [comment]
We do not verify on GitHub. Contact us via the [form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), or if you are in the [Partnership Program](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm) for Sellers via your account manager to undergo the verification process.

**Comment by CarPartsGroup** [comment]
Which form should we use?
I already contacted Allegro about this many times. Please get us some contact that can solve this issue for us.
Thank you

**Comment by CarPartsGroup** [comment]
Your colleague told us to solve this issue here on GitHub.

**Comment by AureliuszBrussy** [comment]
Sorry, however, here I will not be able to help you. As I mentioned - describe the situation through the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by CarPartsGroup** [comment]
We already explained this problem to countless Allegro employees through the Allegro contact form and they never give us any information how to get this approval of our application.
Right now I finished another 10 minutes call through the Allegro contact form and did not get any more information again. I already had 5 calls each lasting about 10 minutes about this problem and I never get any information.
I also wrote many emails, no information.
I was told to contact the Allegro API employees through this GitHub forum and here you say you cannot help me.
So please tell me who can actually help us with this approval because no one in the contact form cannot help us.
Today I had a call with Aneta Jaroschová, the Retention Account Manager and she also sent me an email about the API we already have. I would like her to contact me again.
I also request someone who can help us with this kind of project or someone who can give us information about our application approval and how to get it.
Thank you

**Comment by AureliuszBrussy** [comment]
I see that your request has reached our customer service team and I have confirmation that it will be processed correctly. Expect a response in the created request.

**Comment by AureliuszBrussy** [comment]
You will receive a negative or positive decision. In the case of the latter - further information will also be provided in correspondence. As I mentioned - we do not deal with the verification of applications on GitHub.

**Comment by CarPartsGroup** [comment]
Okay, we will wait. We hope for a soon positive answer.
Thank you, Horvathova
