### ISSUE TITLE
Problem with API listing creartion

### ISSUE THREAD

**Issue by 1stmdc** [allegro/allegro-api#7135]
Występuje problem: 
 - [a ] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
During the publication of listing there are 2 errors and I do not know how to solve them.
Here they are:

W serwisie innym niż allegro.pl wspierane są tylko oferty z podpiętym produktem. (VALIDATION_ERROR null)
Nie można aktywować oferty bez produktu w serwisach innych niż allegro.pl (VALIDATION_ERROR null)

**Comment by PrzemyslawLukanowski** [comment]
It seems that you are trying to [display an offer on the additional allegro.cz marketplace](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6), but you have not met one of the conditions to do that - your offer is not [associated with a any product.](https://github.com/allegro/allegro-api/issues/7135)
