### ISSUE TITLE
Prośba o zakwalifikowanie ofert do programu Allegro Ceny na sandbox'ie

### ISSUE THREAD

**Issue by mstrojecki** [allegro/allegro-api#7137]
Witam,

chciałbym testować funkcjonalności API związane z programem Allegro Ceny, dlatego prosiłbym o zakwalifikowanie następujących ofert do tego programu na sandbox'ie: 
7705618541, 7705618442, 7705618345, 7705618269, 7705618153, 7705618037, 7705617674

Już kiedyś w innym wątku również o to prosiłem. Wtedy strasznie długo to trwało (ok. 2 tyg.) i w międzyczasie też oferty z sandbox'a zostały usunięte. 
Byłbym wdzięczny, jeśli moja prośba tym razem została zrealizowana szybciej ;)

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Czekam jeszcze za odpowiedzią od zespołu odpowiedzialnego za Allegro Ceny. Jak tylko oferty zostaną zakwalifikowane, wrócę z informacją.
