### ISSUE TITLE
WZA zamówienie przyjazdu kuriera

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#7139]
Zamawiamy przyjazd kuriera przez api /parcel-management/parcel-pickup-request-commands/ ale przy probie odpytania o status zgloszenia za kazdym razem dostajemy blad:
{
	"id": "d704b9e8-d8fd-4c5b-abd3-940536783563",
	"status": "ERROR",
	"errors": [
		{
			"code": "ERROR",
			"message": "Internal system error",
			"details": null,
			"path": "",
			"userMessage": "error.common.internal"
		}
	]
}

Coś robimy nie tak po naszej stronie czy to po stronie allegro / kuriera?

**Comment by AureliuszBrussy** [comment]
Przyczyną jest nieprawidłowo przekazana wartość w polach `pickupDate.minTime` oraz `pickupDate.maxTime` - powinniście ją przekazać w formacie `HH:mm`.
