### ISSUE TITLE
/offers/listing?seller.id={Seller_ID}  aktualizacja informacji

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#714]
Jak często aktualizowane są dane zwracane przez zasób "/offers/listing?seller.id={Seller_ID}’" bo ja widzę że już od około godziny zwraca to samo i nie reaguje na zmiany. Chodzi konkretnie o oferty wyszukane z filtrem "searchMode=CLOSED"

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a i responsa wraz z trace-id, a także numer oferty o której napisałeś. Sprawdzimy w czym jest problem.

**Comment by Rnapzsih** [comment]
@centrumelektroniki - u mnie wznowione aukcje znikają z searchMode=CLOSED dopiero po kilku godzinach.

**Comment by PawelTaberski** [comment]
@centrumelektroniki Przekazałem numery oferty, które podałeś do odpowiedniego zespołu jak tylko otrzymam jakieś informacje zwrotne dam znać.

**Comment by centrumelektroniki** [comment]
Dzięki, czekamy z niecierpliwością na informacje.

**Comment by PawelTaberski** [comment]
Dostałem informacje, że występuje jakieś opóźnienie i problem ma zostać rozwiązany. Prosimy o cierpliwość.

**Comment by centrumelektroniki** [comment]
Dziękuję za odpowiedź, będę wdzięczny za informację jak problem będzie rozwiązany.

**Comment by centrumelektroniki** [comment]
Panie Pawle coś ruszyło w temacie ? ile może to trwać, chcemy wprowadzić pewne funkcje automatyzujące sprzedaż.

**Comment by PawelTaberski** [comment]
Problem powinien zostać niedługo usunięty, proszę jeszcze o chwilę cierpliwości.

**Comment by centrumelektroniki** [comment]
Panie Pawle, jak nasz problem, rozwiązany ? Możemy testować ?

**Comment by PawelTaberski** [comment]
Dostałem informacje, że tak i problem nie powinien już występować.
