### ISSUE TITLE
product-offers update (PATCH) publication Status does not changes

### ISSUE THREAD

**Issue by andriusdum** [allegro/allegro-api#7141]
Hei,

today is stop working product-offer publication status changes. It was working till now.
I provide:

` "publication": {
        "duration": null,
        "status": "ACTIVE",
        "startingAt": null,
        "endingAt": null,
        "endedBy": "USER",
        "republish": false
    }`
    
    and I am getting response:
`"publication": {
        "duration": null,
        "status": "ENDED",
        "startingAt": null,
        "endingAt": null,
        "endedBy": "USER",
        "republish": false,
    }`
    
    endpoint I send request:
    PATCH https://api.allegro.pl/sale/product-offers/ofer_id
    
    maybe something changes and I need to provide something more for request?
    Edit: I do not get error on update
    thank you for the help

**Comment by AureliuszBrussy** [comment]
Please provide an example trace-id of such a request. You can find the trace-id in the response header. This will allow me to this case.

**Comment by andriusdum** [comment]
trace-id: fb40d4d1d6ce7f26

**Comment by AureliuszBrussy** [comment]
@andriusdum you received a 202 Accepted response to the requested operation. This means that you should check the status of the command (the resource is asynchronous). In the location header, we returned the address where you can check the status of this command.  You can read more about how this endpoint works in [our guide](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#editing-an-offer-in-the-async-api). 

If you query the address from the location header (GET sale/product-offers/{offerId}/operations/{commandId}) -  you will find out the reason why the publication failed.

**Comment by andriusdum** [comment]
oh nice, never noticed that I can check status.
thank you for the help i see problem now .
