### ISSUE TITLE
WzA Packeta Punkt i Automat

### ISSUE THREAD

**Issue by ZAK2828** [allegro/allegro-api#7142]
Korzystamy z softu prostapaczka, przy tworzeniu etykiety przekazywana jest informacja "descriptions", jednak po utworzeniu etykiety pole na etykiecie "Opis/Uwagi" jest puste. Czy można liczyć na poprawę tego problemu? Żeby przekazane informacje w polu "descriptions" lądowały w polu "Opis/Uwagi" na etykiecie?

W razie potrzeby mogę podesłać zapisane komunikaty z prostejpaczki w celu weryfikacji, że komunikacja odbywa się prawidłowo.

Proszę o informację, ewentualne instrukcje.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że aktualnie występuje problem w komunikacji z przewoźnikiem w kontekście obsługi tego pola. Powinien zostać naprawiony już niedługo (do kilku dni), przepraszam za niedogodności.

**Comment by ZAK2828** [comment]
Dziękuję za informację, prosiłbym jeszcze o info, czym różnią się te usługi, w programie prostapaczka zwraca mi w metodach WzA takie formy dostawy Packety z Polski do Czech:

Allegro Wysyłka z Polski do Czech - Odbiór w Punkcie Packeta (PACKETA - 05ed60e3-6ef4-4bc0-a424-36d2032265ad)
i
Allegro Wysyłka z Polski do Czech - Odbiór w Punkcie Packeta (PACKETA - 714d388f-6ef4-4bc0-a424-36d2032265ad)

oraz
Allegro Wysyłka z Polski do Czech - Automaty Paczkowe Packeta (PACKETA - 07e2afc8-2f6b-4f37-b7fb-9c4a33aba97c)
i
Allegro Wysyłka z Polski do Czech - Automaty Paczkowe Packeta (PACKETA - 529b132a-2f6b-4f37-b7fb-9c4a33aba97c)

**Comment by PrzemyslawLukanowski** [comment]
W przypadku dwóch metod o takiej samej nazwie zwróć proszę uwagę na pole `marketplaces` - zwracamy w nim informację, którego serwisu dotyczy dana metoda - czy `allegro.pl,` czy `allegro.cz`.

**Comment by ZAK2828** [comment]
Rozumiem, jednak nie testujemy tego na jakimiś środowisku informatycznym, gdzie znajdę te informację.
Jest Pan w stanie napisać, w takim razie które reprezentuje allegro.pl a które allegro.cz w tych powyższych metodach?

**Comment by PrzemyslawLukanowski** [comment]
Oczywiście:

- Allegro Wysyłka z Polski do Czech - Odbiór w Punkcie Packeta (PACKETA - 05ed60e3-6ef4-4bc0-a424-36d2032265ad) - **allegro-pl**
- Allegro Wysyłka z Polski do Czech - Odbiór w Punkcie Packeta (PACKETA - 714d388f-6ef4-4bc0-a424-36d2032265ad) - **allegro.cz**
- Allegro Wysyłka z Polski do Czech - Automaty Paczkowe Packeta (PACKETA - 07e2afc8-2f6b-4f37-b7fb-9c4a33aba97c) - **allegro-pl**
- Allegro Wysyłka z Polski do Czech - Automaty Paczkowe Packeta (PACKETA - 529b132a-2f6b-4f37-b7fb-9c4a33aba97c) - **allegro-cz**
