### ISSUE TITLE
Multiple accounts - API access

### ISSUE THREAD

**Issue by DavidRamba** [allegro/allegro-api#7144]
Hello,
 we have registred multiple seller accounts in allegro sandbox and they are connected. 
Can I use one API account for both accounts? Soo if I use /sale/offers I would get offers from both accounts combined?

**Comment by PrzemyslawLukanowski** [comment]
Hi, linked accounts are not fully supported in the API. You can only retrieve the connected account offer details via [GET /sale/offers/{offerID}](https://developer.allegro.pl/documentation#operation/getOfferUsingGET), but you can't modify it or perform any other operation being authorized as another account.
