### ISSUE TITLE
wtyczka Allegro DHL Czechy do baselinker do wysyłki towarów na Czechy w Allegro

### ISSUE THREAD

**Issue by DarekPekabet** [allegro/allegro-api#7145]
Witam, w jaki sposób możemy dodać do integracji w Baselinker wtyczkę do firmy kurierskiej Allegro DHL Czechy?

**Comment by PrzemyslawLukanowski** [comment]
Prosiłbym, aby to pytanie skierować bezpośrednio do wsparcia integracji Baselinker. Jako Allegro nie jesteśmy twórcami tej aplikacji, zatem nie posiadamy takiej wiedzy.

**Comment by DarekPekabet** [comment]
ok, dziękuję
