### ISSUE TITLE
How to obtain product data based on the product information purchased in the order

### ISSUE THREAD

**Issue by WorkingSilence-L** [allegro/allegro-api#7146]
Hello，currently I have found order data based on API:/order/checkout forms/{id}, which includes the following product information：
      "lineItems": [{
	"id": "62ae358b-8f65-4fc4-9c77-bedf604a2e2b",
	"offer": {
		"id": "3213213",
		"name": "Name of purchased offer",
		"external": {}
	},
	"quantity": 1,
	"originalPrice": {},
	"price": {},
	"reconciliation": {},
	"selectedAdditionalServices": [],
	"boughtAt": "2018-01-01T10:23:43.123Z"
}]
Currently, I use API：/sale/products/{productId} to query detailed product data, but the product ID in the order does not match the query parameters required in this API
I would like to use one of the product information returned in the order details to query specific product information. What data should I use and which APIs should I use for querying?
Or which API can I use to query specific product parameters that can be associated with product data in the order?

**Comment by MaciejFrackowiak** [comment]
In the order details, you will not find the "product.id". You will find an offer identifier in the "lineItems.offer.id" field. Then, you can use offer identifier as a value for {offerId} -  [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getProductOffer) or [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) to retrieve "product.id"
