### ISSUE TITLE
Wystawianie ofert na dodatkowy serwisie

### ISSUE THREAD

**Issue by BartlomiejCalus** [allegro/allegro-api#7147]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
W ramach naszej integracji staramy się wystawiać oferty na allegro-cz, jednak dla większości z nich po czasie kwalifikacji oferty (zwracany parametr IN_PROGRESS) oferta jest odrzucana (REFUSED). Są też takie oferty które zostały wystawione bez żadnych problemów. Oferty zarówno wystawione jak i te odrzucone podpięte są pod to samo konto. Czy możemy uzyskać jakiś dokładniejszy powód czemu tak się dzieje ?

Przykłady ofert zaakceptowanych:

- https://allegro.cz/nabidka/krbova-konzola-hula-bila-samomontaz-13672857409 (id oferty: 13672857409)

- https://allegro.cz/nabidka/terasovy-plynovy-vyhrivany-destnik-patio-light-8-2kw-13596546653?reco_id=82f3c1e5-feb2-11ed-bf1d-8ad6995c27ec&sid=041047f9c36843e364ecb91b45c568a2755aa386fe7e14ee7421a14291fbf951 (id oferty: 13596546653)

Przykłady ofert które chcieliśmy wystawić ale nie zostały zaakceptowane:

- https://allegro.pl/oferta/kratka-wentylacyjna-kominkowa-11x42-miedziana-10161886946?bi_s=ads&bi_m=listing:desktop:query&bi_c=ZTJmNmU4NDMtOWNkMy00YzA0LThmMDUtYTRmNmU1MmY3OTYzAA&bi_t=ape&referrer=proxy&emission_unit_id=f3a0dc2c-ec44-43c8-bc90-f777e3ab2415 (id oferty: 10161886946)

- https://allegro.pl/oferta/kominek-powietrzny-stalowy-mba-lewy-17-kw-fi-200-13671082960 (id oferty: 13671082960)

**Comment by MaciejFrackowiak** [comment]
Szczegóły braku kwalifikacji oferty do widoczności w serwisie dodatkowym uzyskasz pobierając dane z dziennika ofert - [GET /sale/offer-events](https://developer.allegro.pl/documentation/#operation/getOfferEvents).
