### ISSUE TITLE
Problem w kategorii  Stroje kąpielowe > Dwuczęściowe" [76024]

### ISSUE THREAD

**Issue by glorifyingpeace** [allegro/allegro-api#7148]
Problem dotyczy wystawiania produktów przez API w kategorii Stroje kąpielowe > Dwuczęściowe" [76024]

Dostajemy taki błąd:
trace-id: 5c1e6ad54d646e19
ConstraintViolationException.DependencyValidator
Parametr zależny Rozmiar (128610) nie może przyjąć wartości [46], gdy parametr Rodzaj (215534) ma wartości [góra].

Problem pojawia się gdy uzupełniamy **nieobowiązkowy** parametr "rozmiar". Jest on w parametrach dostępnych dla tej kategorii. Jeśli go pominiemy to produkt przechodzi. 
Jednakże jest on ważny w przypadku filtrowania produktów dlatego zależy nam na jego obecności.

**Comment by MaciejFrackowiak** [comment]
W zasobie [GET /sale/categories/{categoryId}/parameter](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2)s możesz pobrać zależności, które definiują możliwość wykorzystania parametrów i konkretnych wartości. I tak, przy parametrze Rozmiar (128610) i wartości "46" widzimy:
```
{
                    "id": "128610_141",
                    "value": "46",
                    "dependsOnValueIds": [
                        "215534_270230"
                    ]
                }
```
Oznacza to, że wartość "46" dla parametru Rozmiar możesz podać tylko, gdy parametr Rodzaj przyjmie wartość "komplet" (id=215534_270230).
