### ISSUE TITLE
[BUG] Metoda doGetBidItem2 Zwraca zakupy które nie istnieją

### ISSUE THREAD

**Issue by wispcasts** [allegro/allegro-api#715]
Witam

W wynikach metodydoGetBidItem2 do mojej aukcji nr 6049654041 jest rekord nr 884 gdzie widać, że klient o loginie C..4 zakupił 20 szt.
![screenshot 2018-10-05 at 13 06 43](https://user-images.githubusercontent.com/17798936/46532144-07717a00-c8a0-11e8-97d6-d5c431e86102.png)

Z tymże nie ma takiej transakcji ani w dzienniku, ani w sprzedanych ani nigdzie indziej.

Skąd to pochodzi ?

**Comment by PawelTaberski** [comment]
Z tego co widzę wszystko się zgadza ten użytkownik przez cały czas trwania oferty wielokrotnie robił w niej zakupy i w sumie zakupił 20 szt.

**Comment by wispcasts** [comment]
Czyli ot tak w dowolnym czasie agregujecie zakupy w wynikach tej metody ?

Skad się w takim razie wziął timestamp godz 10:57:42 ?

**Comment by PawelTaberski** [comment]
Jest to data ostatnio dokonanego zakupu przez danego usera w tej ofercie. Wspomniana przez Ciebie metoda zgodnie z opisem:  pozwala na pobranie publicznie dostępnych informacji na temat wszystkich użytkowników, którzy dokonali zakupu w danej ofercie. Nie służy ona do obsługi sprzedaży, ani do śledzenia kolejnych zakupów i nie wskazuje kolejnych fodów.
