### ISSUE TITLE
Nazwa płatności Allegro - Pobranie

### ISSUE THREAD

**Issue by agropol24** [allegro/allegro-api#7150]
Czy jest rozgraniczenie pomiędzy nazwą płatności allegro w przypadku płatności za pobraniem? Chciałbym rozróżnić pobranie od różnych kurierów: DPD, Inpost, GLS? https://i.imgur.com/edvARMm.png

**Comment by PrzemyslawLukanowski** [comment]
W szczegółach zamówienia  ([GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation#operation/getOrdersDetailsUsingGET)) rodzaj płatności zwrócimy w polu `payment.type`, natomiast informację o tym, jakiego przewoźnika to dotyczy, znajdziesz w polu `delivery.method.name`, w którym to wyświetlamy informację o wybranie metodzie dostawy. Łącząc informację z obu pól, powinieneś otrzymać oczekiwany efekt.
