### ISSUE TITLE
aktywacja konta allegrosandbox

### ISSUE THREAD

**Issue by pszponarski** [allegro/allegro-api#7151]
dzień dobry,
proszę o aktywację konta o loginie "test_tytan" na środowisku sandbox.

**Comment by PrzemyslawLukanowski** [comment]
Jest to konto zwykłe, zatem aktywacja nastąpi wraz z pierwszym zakupem. Jeśli chcesz przetestować wystawianie ofert za pomocą API, [utwórz konto firmowe](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F). To możesz pozostawić jako drugie konto, z którego np. będziesz wykonywać zakupy.

**Comment by PrzemyslawLukanowski** [comment]
Wskaż jeszcze proszę numer konta (możesz oczywiście wygenerować fikcyjny numer, ale w odpowiednim formacie) oraz wykonaj przelew weryfikacyjny.

**Comment by pszponarski** [comment]
Ale jak mam wykonać przelew weryfikacyjny z fikcyjnego numeru rachunku ?

**Comment by PrzemyslawLukanowski** [comment]
Przelew wykonujesz za pomocą symulatora płatności, on nie odbywa się naprawdę, żadne środki nie są pobierane z konta.

**Comment by pszponarski** [comment]
przelew fikcyjny zrobiony, teraz mam komunikat: Proces weryfikacji może potrwać kilka dni. Poinformujemy Cię o decyzji e-mailem.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję. Aktywowałem konto, masz już dostęp do wszystkich opcji w ramach konta firmowego.

**Comment by pszponarski** [comment]
dziękuję, działa.

**Comment by piraterr** [comment]
@PrzemyslawLukanowski Prosze o aktywowanie konta dla firmy  PIRATE CORP (pirate)

**Comment by PrzemyslawLukanowski** [comment]
@piraterr Aktywowałem Twoje konto.
