### ISSUE TITLE
API question regarding orders and offers

### ISSUE THREAD

**Issue by beatrizm87** [allegro/allegro-api#7152]
I have some questions regarding the API:
1- How can we identify if an order is fulfilled by Allegro?
2- Regarding the order workflow, READY_FOR_PICKUP and PICKED_UP status are managed by Allegro or by the seller?
3- Regarding offers, I saw 2 calls, creating an offer based on a product and editing an offer, is there a way to use only one for both cases? I tried to use the first one for editing a product and I always get a new product, but I am not able to know if the product is already created, is there another way to do that?
Also, do you have a way to send a file with many offers to update via API?

Thank you in advance.

**Comment by beatrizm87** [comment]
Hello,

Thank you for your answers.

Regarding One Fulfillment, I need to distinguish the order to don't send unnecessary calls in order to confirm the new fulfillment.status.  

The others points are clear for me.

Thank you

**Comment by PrzemyslawLukanowski** [comment]
For the One Fulfillment account, all orders will be fulfilled by Allegro, user cannot list offers other than One Fulfillment for this type of account. I also want to clarify the answer to the second question - those statuses are fully managed by Allegro when it comes to One Fulfillment orders (sorry for that, I automatically was thinking about basic orders, not One Fulfillment).

**Comment by beatrizm87** [comment]
Hello, 
I tried to create an offer using POST /sale/product-offers, I only added the EAN, price and stock but I know the offer category has mandatory parameters, however the offer was created. According to your doc: "If you receive information in the response to complete the missing mandatory parameters.....", I had understood that if the mandatory parameters were not found in the request body I got an error response that asked me to add them but this was not the case. Can you explain me how exactly this call works? And if there is a rule to fill the mandatory parameters if they are not present in the request body?
Thank you in advance.
Beatriz

**Comment by PrzemyslawLukanowski** [comment]
Hello, in the majority of calls, all you need to do to list offers is - as you mentioned - EAN, price, and stock. In some cases, due to changes in categories or product data, some products in our Catalog may not have all the required product parameters included. In that kind of situation, you need to provide the mentioned parameters on your own, like in the following example from our tutorial:

```
{
    "productSet": [{
        "product": {
            "id": "d26b023c-d52c-44f9-b61a-321eb202792b",
            "parameters": [{                        - list of product parameters
                "id": "202293",                     - ID of the parameter that was not specified in our product catalog
                "valuesIds": [
                    "202293_211441"             - a value of this required parameter
                ]
            }]
        }
    }],
    "sellingMode": {
        "price": {
            "amount": "220.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 1
    }
}
```

If you want to check all required product parameters in a specific category, use [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2) - information is included in the `requiredForProduct` flag.
