### ISSUE TITLE
May I ask what is the specific reason for the failure? All my prices are consistent

### ISSUE THREAD

**Issue by lanxiaokeng** [allegro/allegro-api#7153]
path:  
 https://api.allegro.pl/sale/offer-variants

 request parameters:
 {"offers":[{"id":"13774652216","colorPattern":"249512_1647413"},{"id":"13774652212","colorPattern":"249512_1647413"},{"id":"13774652211","colorPattern":"249512_1647413"},{"id":"13774652199","colorPattern":"249512_1647413"},{"id":"13774652208","colorPattern":"249512_1647416"},{"id":"13774652207","colorPattern":"249512_1647416"},{"id":"13774652229","colorPattern":"249512_1647416"},{"id":"13774652214","colorPattern":"249512_1647416"},{"id":"13774652206","colorPattern":"249512_1647415"},{"id":"13774652213","colorPattern":"249512_1647415"},{"id":"13774652205","colorPattern":"249512_1647415"},{"id":"13774652201","colorPattern":"249512_1647415"},{"id":"13774652203","colorPattern":"249512_1647414"},{"id":"13774652202","colorPattern":"249512_1647414"},{"id":"13774652200","colorPattern":"249512_1647414"},{"id":"13774652209","colorPattern":"249512_1647414"}],"name":"Gu Yun, Różowa gruba podeszwa płótna Buty damskie","parameters":[{"id":"color/pattern"},{"id":"26388"}]}

{"errors":[{"code":"VALIDATION_ERROR","message":"Podany parametr kolor/wzór nie może zostać dopasowany do ofert 13774652199, 13774652200, 13774652201, 13774652202, 13774652203, 13774652205, 13774652206, 13774652207, 13774652208, 13774652209, 13774652211, 13774652212, 13774652213, 13774652214, 13774652216, 13774652229. Użyj tej samej wartości parametru kolor/wzór w obrębie grupy ofert (13774652199, 13774652200, 13774652201, 13774652202, 13774652203, 13774652205, 13774652206, 13774652207, 13774652208, 13774652209, 13774652211, 13774652212, 13774652213, 13774652214, 13774652216, 13774652229).","details":null,"path":null,"userMessage":"Podany parametr kolor/wzór nie może zostać dopasowany do ofert 13774652199, 13774652200, 13774652201, 13774652202, 13774652203, 13774652205, 13774652206, 13774652207, 13774652208, 13774652209, 13774652211, 13774652212, 13774652213, 13774652214, 13774652216, 13774652229. Użyj tej samej wartości parametru kolor/wzór w obrębie grupy ofert (13774652199, 13774652200, 13774652201, 13774652202, 13774652203, 13774652205, 13774652206, 13774652207, 13774652208, 13774652209, 13774652211, 13774652212, 13774652213, 13774652214, 13774652216, 13774652229)."}]}

**Comment by MaciejFrackowiak** [comment]
You assigned four different values to the "colorPattern" field, where all of these offers have the same photo. If you want to vary offers by "colorPattern" they should have different photos.

**Comment by lanxiaokeng** [comment]
path:
https://api.allegro.pl/sale/product-offers       POST

request parameters:
{
  "parameters": [
    {
      "id": "11323",
      "name": "Stan",
      "valuesIds": [
        "11323_1"
      ],
      "values": null,
      "rangeValue": null
    }
  ],
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/112bed/499bdd00482fa2198eea1b6c081f"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/11af61/9da763bf4eb18ac5057e5feab6c6"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/11e23d/e959c8b54417b6357dc74a9e1602"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/114c99/982a6c904e13b21e44e03c3c774f"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/113f85/33680a3a49b78348642bb5f7f194"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/117093/84c2cb1b4c2fa3a3343cbacba631"
          }
        ]
      }
    ]
  },
  "category": {
    "id": "87873"
  },
  "compatibilityList": null,
  "delivery": {
    "shippingRates": {
      "id": "12acba75-c981-463d-b18a-123982595ece"
    },
    "handlingTime": "P5D",
    "shipmentDate": null,
    "additionalInfo": null
  },
  "payments": {
    "invoice": "NO_INVOICE"
  },
  "discounts": {
    "wholesalePriceList": null
  },
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "d928b5a1-0951-42d1-8357-d3a495a03e4b"
    },
    "returnPolicy": {
      "id": "72399c8d-0b90-4004-9a35-9b01f1645efa"
    },
    "warranty": null
  },
  "additionalServices": null,
  "sizeTable": null,
  "fundraisingCampaign": null,
  "location": {
    "countryCode": "CN",
    "province": null,
    "city": "Shenzhen",
    "postCode": "0000"
  },
  "messageToSellerSettings": {
    "mode": "HIDDEN"
  },
  "publication": {
    "duration": "P3D",
    "status": "ACTIVE",
    "startingAt": null,
    "endingAt": null,
    "endedBy": null,
    "republish": false,
    "marketplaces": null
  },
  "additionalMarketplaces": {
    "allegro-cz": {
      "sellingMode": null,
      "publication": {
        "state": "NOT_REQUESTED"
      }
    }
  },
  "tax": null,
  "taxSettings": null,
  "attachments": [],
  "contact": null,
  "b2b": {
    "buyableOnlyByBusiness": false
  },
  "language": "pl-PL",
  "stock": {
    "available": 999,
    "unit": "UNIT"
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": 19.59,
      "currency": "PLN"
    },
    "minimalPrice": null,
    "startingPrice": null
  },
  "external": {
    "id": "c647b5-1-1-S"
  },
  "productSet": [
    {
      "product": {
        "name": "Męski designer t shirt ubrania palmy designer",
        "category": {
          "id": "87873"
        },
        "parameters": [
          {
            "id": "3786",
            "name": "Marka",
            "valuesIds": [
              "3786_1704209"
            ],
            "values": null,
            "rangValue": {},
            "rangeValue": null
          },
          {
            "id": "3766",
            "name": "Wzór dominujący",
            "valuesIds": [
              "3766_3"
            ],
            "values": null,
            "rangeValue": null
          },
          {
            "id": "202677",
            "name": "Rodzaj kołnierzyka",
            "valuesIds": [
              "202677_212901"
            ],
            "values": null,
            "rangeValue": null
          },
          {
            "id": "18293",
            "name": "Rękaw",
            "valuesIds": [
              "18293_2"
            ],
            "values": null,
            "rangeValue": null
          },
          {
            "id": "129012",
            "name": "Fason",
            "valuesIds": [
              "129012_212853"
            ],
            "values": null,
            "rangeValue": null
          },
          {
            "id": "201017",
            "name": "Materiał dominujący",
            "valuesIds": [
              "201017_2317"
            ],
            "values": null,
            "rangeValue": null
          },
          {
            "id": "249512",
            "name": "Kolor",
            "valuesIds": [
              "249512_1647429"
            ],
            "values": null,
            "rangeValue": null
          },
          {
            "id": "54",
            "name": "Rozmiar",
            "valuesIds": [
              "54_3"
            ],
            "values": null,
            "rangeValue": null
          }
        ],
        "images": [
          "https://a.allegroimg.com/original/1184b2/469e7d5848a78f6bd3332e15bd97",
          "https://a.allegroimg.com/original/1172ed/ab50e28640adaafcfe4b02c977b1",
          "https://a.allegroimg.com/original/116e10/9f7f91a847579d97f36201482332",
          "https://a.allegroimg.com/original/1189eb/48612b5e4e42aed7176bd83d54c6",
          "https://a.allegroimg.com/original/113947/385d07b841588cd62819043cc99e",
          "https://a.allegroimg.com/original/117c6d/3b831b3c4d6e8c1630b5c9bdaf4f",
          "https://a.allegroimg.com/original/1189f3/47e290ad4589887c52bc73424eb6",
          "https://a.allegroimg.com/original/117ab9/fa1191da44428120e425c39563c9",
          "https://a.allegroimg.com/original/112bed/499bdd00482fa2198eea1b6c081f",
          "https://a.allegroimg.com/original/11af61/9da763bf4eb18ac5057e5feab6c6",
          "https://a.allegroimg.com/original/11e23d/e959c8b54417b6357dc74a9e1602",
          "https://a.allegroimg.com/original/114c99/982a6c904e13b21e44e03c3c774f"
        ]
      },
      "quantity": {
        "value": 1
      }
    }
  ]
}


{"errors":[{"code":"ConstraintViolationException.ValidOfferName","message":"Z opisu Twojej oferty wynika, że kupujący powinien się z Tobą skontaktować. Jeżeli zapis dotyczy kontaktu po zakupie przenieś go do zakładki „O Sprzedającym”. Zachęcanie do kontaktu przed zakupem nie jest dozwolone, ponieważ może skutkować sfinalizowaniem transakcji poza Allegro. Usuń z opisu niedozwolone zapisy.","details":"ConstraintViolationException.ValidOfferName","path":"name","userMessage":"Z opisu Twojej oferty wynika, że kupujący powinien się z Tobą skontaktować. Jeżeli zapis dotyczy kontaktu po zakupie przenieś go do zakładki „O Sprzedającym”. Zachęcanie do kontaktu przed zakupem nie jest dozwolone, ponieważ może skutkować sfinalizowaniem transakcji poza Allegro. Usuń z opisu niedozwolone zapisy."}]}



It can be seen from which part of the quotation that the buyer must contact me. I have been looking for it for a long time but haven't found it

**Comment by MaciejFrackowiak** [comment]
In the offer description - image: https://a.allegroimg.com/original/112bed/499bdd00482fa2198eea1b6c081f - you ask to contact via email or trademanager.

**Comment by lanxiaokeng** [comment]
Excuse me again, what caused this

path:  https://api.allegro.pl/sale/offer-variants

request parameters:
{{
  "offers": [
    {
      "id": "13784370245"
    },
    {
      "id": "13784370116"
    }
  ],
  "name": "2023 Nowy Oryginalny Lenovo X16 Słuchawki",
  "parameters": [
    {
      "id": "206002"
    }
  ]
}}

{"errors":[{"code":"VARIANT_ATTRIBUTE_NOT_ALLOWED_IN_CATEGORY","message":"Łączenie ofert po parametrze 206002 jest zablokowane w kategorii 4863.","details":null,"path":null,"userMessage":"Łączenie ofert po parametrze 206002 jest zablokowane w kategorii 4863."}]}

**Comment by MaciejFrackowiak** [comment]
In the category with id=4863, you cannot vary offers by parameter.id=206002.
