### ISSUE TITLE
/sale/categories - nie zwraca wszystkich kategorii

### ISSUE THREAD

**Issue by Maczuga** [allegro/allegro-api#7154]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

https://allegro.pl/kategoria/elektronika-samochodowa-nawigacje-i-akcesoria-gps-257399
Jak widać - ta kategoria ma 3 podkategorie.

Wywołanie /sale/categories?parent.id=257399
Zwraca tylko jedną podkategorię:
```json
{
   "categories":[
      {
         "id":"257973",
         "name":"Akcesoria i oprogramowanie",
         "parent":{
            "id":"257399"
         },
         "leaf":true,
         "options":{
            "variantsByColorPatternAllowed":true,
            "advertisement":false,
            "advertisementPriceOptional":false,
            "offersWithProductPublicationEnabled":true,
            "productCreationEnabled":true,
            "customParametersEnabled":true,
            "sellerCanRequirePurchaseComments":false
         }
      }
   ]
}
```

Podobna sytuacja:
https://allegro.pl/kategoria/wyposazenie-i-akcesoria-samochodowe-foteliki-samochodowe-253570 - ma 4 podkategorie
 /sale/categories?parent.id=253570 - zwraca 1

```json
{
   "categories":[
      {
         "id":"257956",
         "name":"Pozostałe",
         "parent":{
            "id":"253570"
         },
         "leaf":true,
         "options":{
            "variantsByColorPatternAllowed":true,
            "advertisement":false,
            "advertisementPriceOptional":false,
            "offersWithProductPublicationEnabled":true,
            "productCreationEnabled":true,
            "customParametersEnabled":true,
            "sellerCanRequirePurchaseComments":false
         }
      }
   ]
}
```

**Comment by MaciejFrackowiak** [comment]
Jest to prawidłowe działanie - w drzewie kategorii dostępna jest tylko jedna podkategoria z id=257973, w której możesz wystawić ofertę. Pozostałe widoczne kategorie to kategorie asortymentowe, czyli oferty sprzedających wystawione w kategorii X, widoczne są również w kategorii Y - więcej możesz o tym przeczytać na [stronie dla sprzedających](https://allegro.pl/dla-sprzedajacych/polaczylismy-kategorie-w-ktorych-wystawiasz-oferty-m0eRMnKMncP).

**Comment by MaciejFrackowiak** [comment]
Nie ma możliwości ich pobrania, one są widoczne i dostępne wyłącznie z pozycji kupującego.
