### ISSUE TITLE
Bład przy generowaniu tokenu 

### ISSUE THREAD

**Issue by TomekThiel** [allegro/allegro-api#7157]
Generalnie to skopiowałem kod php z Państwa strony do wygenerowania tokenu, wpisałem swoje danego w "klucze" i niestety ale wyskakuje mi komunikat: "access_token = Something went wrong

```
<?php

define('CLIENT_ID', ''); // wprowadź Client_ID aplikacji
define('CLIENT_SECRET', ''); // wprowadź Client_Secret aplikacji

function getCurl($headers, $url, $content = null) {
    $ch = curl_init();
    curl_setopt_array($ch, array(
        CURLOPT_URL => $url,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_RETURNTRANSFER => true
    ));
    if ($content !== null) {
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $content);
    }
    return $ch;
}

function getAccessToken() {
    $authorization = base64_encode(CLIENT_ID.':'.CLIENT_SECRET);
    $headers = array("Authorization: Basic {$authorization}","Content-Type: application/x-www-form-urlencoded");
    $content = "grant_type=client_credentials";
    $url = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token";
    $ch = getCurl($headers, $url, $content);
    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }
    return json_decode($tokenResult)->access_token;
}

 function main()
{
    echo "access_token = ", getAccessToken();
}

main();
```

**Comment by MaciejFrackowiak** [comment]
Niestety, po samym przykładzie niewiele możemy tu wywnioskować. Zmodyfikuj swój kod tak, abyśmy mogli zobaczyć faktyczny status code. Upewnij się także, czy przekazujesz właściwe dla Sandbox wartości ClientID oraz Client Secret.

**Comment by wgerro** [comment]
Też mam ten sam problem. Dzisiaj testowane

**Comment by MaciejFrackowiak** [comment]
@wgerro Mógłbyś doprecyzować, na jaki problem trafiłeś?

**Comment by wgerro** [comment]
`<?php

define('CLIENT_ID', "KOD CLIENT_ID"); // wprowadź Client_ID aplikacji
define('CLIENT_SECRET', "KOD SECRET_ID"); // wprowadź Client_Secret aplikacji

function getCurl($headers, $url, $content = null) {
    $ch = curl_init();
    curl_setopt_array($ch, array(
        CURLOPT_URL => $url,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_RETURNTRANSFER => true
    ));
    if ($content !== null) {
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $content);
    }
    return $ch;
}

function getAccessToken() {
    $authorization = base64_encode(CLIENT_ID.':'.CLIENT_SECRET);
    $headers = array("Authorization: Basic {$authorization}","Content-Type: application/x-www-form-urlencoded");
    $content = "grant_type=client_credentials";
    $url = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token";
    $ch = getCurl($headers, $url, $content);
    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }
    return json_decode($tokenResult)->access_token;
}

 function main()
{
    echo "access_token = ", getAccessToken();
}

main();
`

Otrzymuję kod -> {"error":"Unauthorized","error_description":"Unauthorized"}

redirect url wskazalem lokalny adres i tez probowalem w publicznym adresie to taki sam error. Czy coś pominałem ?

Jest utworzony kod API w zakladce (https://apps.developer.allegro.pl/)

**Comment by PrzemyslawLukanowski** [comment]
@wgerro Podejrzewam, że próbujesz zautoryzować aplikację ze środowiska produkcyjnego na środowisku testowym (https://allegro.pl.allegrosandbox.pl/auth/oauth/token). W zależności od tego, z jakiego środowiska chcesz korzystać, użyj odpowiednich danych. Dodam jeszcze, że za pomocą tokena wygenerowanego w ramach client_credentials otrzymasz dostęp wyłącznie do publicznych danych, które nie posiadają kontekstu użytkownika (oznaczone jako bearer-token-for-application w naszej dokumentacji). Jeśli chcesz wystawiać oferty, pobierać zamówienia, itp. skorzystaj z autoryzacji typu [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow).
