### ISSUE TITLE
Wystawianie oferty z własnym opisem

### ISSUE THREAD

**Issue by DawidPPGithub** [allegro/allegro-api#7158]
Witam,

Próbuję wystawić ofertę połączoną z produktem z katalogu allegro. Program tworzę w PHP przez cURL używając zasobu "Create offer based on product". Chcę dodać własny opis. Oferta wystawia się poprawnie, ale opis jest taki jak produktu z katalogu. Tak wyglada JSON "description": 
"description":{
      "sections":[
         {
            "items":[
               {
                  "content":"Twój opis oferty..."
               }
            ]
         }
      ]
   },

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz wskazać nam przykładowe trace-id lub payload, który do nas wysyłasz? Przed chwilą wykonałem test i nie mogę potwierdzić problemu. Poniżej załączam przykładową strukturę, w której nadpisałem opis z produktu:
```

{
"productSet": [{
        "product": {
            "id": "580d6947-8b15-4182-bda1-d58eda951265"
        }
    }],
  "sellingMode": {
    "price": {
      "amount": "220.85",
      "currency": "PLN"
    }
  },
  "stock": {
    "available": 10
  },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "IMAGE",
                        "url": "https://a.allegroimg.com/original/112f5f/0d3d883f46559411a9446d8e41e0"
                    },
                    {
                        "type": "TEXT",
                        "content": "<p>test</p>"
                    }
                ]
            }
        ]
    }
}
```

**Comment by DawidPPGithub** [comment]
Dziękuję za odpowiedź. Spróbowałem ze strukturą, którą Pan przesłał, również nie zadziałało. trace-id: 8845c437302e2b59

**Comment by PrzemyslawLukanowski** [comment]
Miałeś drobny błąd w payloadzie - "}" przed images. Spróbuj proszę ponownie używając dokładnie poniższego JSON-a:

```
{
	"productSet": [{
		"product": {
			"id": "5423bfe2-612d-4552-b3b8-d04338f61119"
		}
	}],
	"sellingMode": {
		"price": {
			"amount": "17.13",
			"currency": "PLN"
		}
	},
	"stock": {
		"available": 995
	},
	"description": {
		"sections": [{
			"items": [{
				"type": "IMAGE",
				"url": "https://a.allegroimg.com/original/03d68a/6092f8024506a01087c820e58f0c"
			}, {
				"type": "TEXT",
				"content": "<p>test</p>"
			}]
		}]
	}
}
```

Obrazek w międzyczasie może wygasnąć, dlatego jeśli otrzymasz błąd, użyj innego linka. Dodatkowo, jeśli chcesz przekazać obrazek w `images`, zamiast poniższej konstrukcji:

```
"images": [{
	"url": "https://a.allegroimg.com/original/03d68a/6092f8024506a01087c820e58f0c"
}]
```

musisz przekazać:

`"images": ["https://a.allegroimg.com/original/03d68a/6092f8024506a01087c820e58f0c"]`

**Comment by DawidPPGithub** [comment]
Opis już działa, ale mam teraz problem z "name" (chodzi mi o nazwe oferty). 
JSON request: 
        {
            "productSet": [{
                "product": {
                    "name": "test",
                    "id": "ID_PRODUKTU_Z_KATALOGU",
                    "idType": "GTIN"
                }
            }],
            "sellingMode": {
                "price": {
                    "amount": "19",
                    "currency": "PLN"
                }
            },
            "stock": {
                "available": 995
            },
            "description": {
                "sections": [{
                    "items": [
                        {
                            "type": "TEXT",
                            "content": "<p>opis</p>"
                        }
                    ]
                }]
            }
        }

*do id podaje zmienną, którą na potrzeby przesłania JSON usunąłem.

**Comment by PrzemyslawLukanowski** [comment]
Możesz napisać, jaki dokładnie błąd? Co otrzymujesz w odpowiedzi? Zamiast "test" spróbuj wpisać poprawną nazwę produktu.

**Comment by DawidPPGithub** [comment]
Nie otrzymuje żadnego błędu. Aukcja wystawia się poprawnie, ale z nazwą produktu z katalogu, a nie dodaną przeze mnie. (spróbowałem z poprawną nazwą produktu inną niż "test" i jest to samo)

**Comment by PrzemyslawLukanowski** [comment]
Tak się dzieje, ponieważ nie możesz zmienić nazwy istniejącego produktu. Możesz wprowadzić nazwę oferty - w takim przypadku pole `"name"` przekaż poza strukturą `"productSet"`, na tym samym poziomie co `sellingMode` i `price`. Jeśli natomiast uważasz, że nazwa produktu w naszym katalogu jest nieprawidłowa możesz zaproponować zmianę, przez [www](https://allegro.pl/dla-sprzedajacych/jak-zmienic-dane-w-produkcie-z-katalogu-allegro-ZGZG89WkOU0) lub [API](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-zglosic-blad-w-produkcie).
