### ISSUE TITLE
Etykiety z Poczty Polskiej wychodzą w dziwnym formacie

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#7159]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,
tworząc przesyłkę dla metod Poczty Polskiej napotykam taki problem, że etykieta drukuje się (tj. jest już taka w pliku PDF) umieszczona po prawej stronie i zdublowana. Wybierana była domyślnie w formacie A6, jednak niezależnie od wyboru problem występuje.

Trace-Id utworzonej przesyłki: 6be9520253ef785d

Trace-Id odpytania o etykietę: c32e3e2754240cba

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, że przesyłka została nadana na umowie własnej. W takim przypadku format etykiet ustawia się w Elektronicznym Nadawcy, więc rekomenduję, abyś właśnie tam sprawdził, czy ustawienia na pewno są prawidłowe.

**Comment by hahyes** [comment]
@PrzemyslawLukanowski Zgadza się, znaleźliśmy błąd w konfiguracji EN. Dzięki za podpowiedź, zamykam.
