### ISSUE TITLE
WebAPI/REST/www - Zmiany ID kategorii na UUID i zero INFO ??

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#716]
Czy Wy tam już oszaleliście do końca ?? Robicie podmianki FORMATU identyfikatorów kategorii i nawet nie raczyliście o tym oficjalnie wspomnieć ?? Przecież to wpływa na całą strukturę wszystkich danych, we wszystkich metodach pobierających i odsyłających dane - OGARNIJCIE SIĘ WRESZCIE !!

**Comment by PawelTaberski** [comment]
Wszystkie kategorie liście mają numer identyfikacyjny w formacie integer. W drzewie kategorii jakie pobierzesz przez REST API tylko w głównych kategoriach niektóre z nich mają numer w formacie UUID. Nie planujemy przechodzenia ze wszystkimi numerami kategorii na UUID. Nowe działy jakie będą powstawały również otrzymają numer w formacie integer.

**Comment by PawelTaberski** [comment]
Tak, jak wspomniałem nie będziemy już nadawali numerów do żadnych kategorii w formacie UUID, ani do nowych ani do już obecnych.

**Comment by GyniO** [comment]
No to czegoś tu nie rozumiem:
https://github.com/allegro/allegro-api/issues/699#issuecomment-426994881

Jaki jest w tym sens?

**Comment by PawelTaberski** [comment]
@GyniO Miałem na myśli integer a napisałem UUID bo wcześniej o nim pisałem, że niektóre większe kategorie mają numer w tym formacie, przepraszam za wprowadzenie w błąd, komentarz już poprawiłem.

**Comment by GyniO** [comment]
@PawelTaberski OMG!!. Na webApi były ID, teraz się zdziwiłem, że będą UUID no i specjalnie w tym wątku pytałem o "dziwne stringi" , dostałem odpowiedź, że będziecie na nie przechodzić... 
Zmarnowałem tylko czas by przerabiać obecny mechanizm, a teraz się okazuje, że robiłem to niepotrzebnie. Nie sprostował Pan też komentarzy w tamtym wątku powyżej. To wszystko wychodzi na niezłą bete, a szukacie developerów, którzy będą szukać błędów..

**Comment by FromAnyHole** [comment]
@GyniO - żyjemy w paranoi do piątej potęgi, a już tam gdzie rządzą zasady Corpo - nie liczy się człowiek...

**Comment by KrzysztofStachyra** [comment]
Komu można przesłać refakturę za dupo godziny popełnione na dostosowanie się do "nowego", które jednak będzie "stare"?
