### ISSUE TITLE
Po kliknięciu ,,Przejdź do sandboxa" nie działa link. (https://allegro.pl.allegrosandbox.pl/)

### ISSUE THREAD

**Issue by wgerro** [allegro/allegro-api#7160]
Na tej stronie https://developer.allegro.pl/

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, jednak nie mogę potwierdzić problemu. Test wykonałem na dwóch różnych urządzeniach i w obu przypadkach zostałem prawidłowo przeniesiony na stronę. Co w Twoim przypadku dzieje się po kliknięciu w link?

**Comment by wgerro** [comment]
Będąc na stronie -> https://developer.allegro.pl/ jak klikam na przycisk ,,Przejdź do sandboxa" to otwiera sie nowa karta i jest komunikat jak niżej na zdj 

![image](https://github.com/allegro/allegro-api/assets/16623552/d0eb5b87-2c2c-4981-a6a0-16f20013ab16)

jak zrobilem kopiuj adres linku to pokazuje mi https://allegro.pl.allegrosandbox.pl/ jak niżej na zdj

![uwaga](https://github.com/allegro/allegro-api/assets/16623552/7dea30f1-d7f6-412e-9105-b039042c52cd)

testowane na google chrome i na firefox i ten problem taki sam.
