### ISSUE TITLE
W jakiej kolejności zwracane są wyniki zapytania /sale/badges? Czy jest jakaś stała reguła/zależność?

### ISSUE THREAD

**Issue by michalmicpaw** [allegro/allegro-api#7161]
Dzień dobry.

Według jakiej zasady, reguły bądź klucza, sortowane są wyniki requesta **_/sale/badges_**? Czy można jakoś pominąć wyniki, które są już nieaktualne, z tytułu wygaśnięcia oferty? Czy trzeba pobrać wszystkie oferty, żeby mieć pewność, że pobraliśmy wszystkie trwające oferty?

Dziękuję
Pozdrawiam!
M.

**Comment by PrzemyslawLukanowski** [comment]
Najpierw bierzemy pod uwagę ID kampanii, zwrócimy wszystkie oferty rosnąco wg ID oferty dla konkretnej kampanii, następnie oferty uporządkowane rosnąco wg ID dla następnej kampanii. Niestety nie ma możliwości wykluczenia ofert nieaktywnych, możesz jedynie w query parametrze offer.id wskazać te oferty, dla których chcesz wyniki.

**Comment by michalmicpaw** [comment]
Dzięki!

`w query parametrze offer.id wskazać te oferty, dla których chcesz wyniki`

Jak mogę wskazać kilka id ofert w tym parametrze?
