### ISSUE TITLE
Sandbox : ConstraintViolationException.ValidSeller on sandbox

### ISSUE THREAD

**Issue by lwillems** [allegro/allegro-api#7164]
Hello

It's seems my sandbox account is locked, got this error when trying to post a new sale-product on rest API

```json
{
    "errors": [
        {
            "code": "ConstraintViolationException.ValidSeller",
            "message": "You do not have the permissions required to list an offer (sales suspended). Pay the arrears in Settlements with Allegro;",
            "details": "ConstraintViolationException.ValidSeller",
            "path": "seller",
            "userMessage": "Nie masz wymaganych uprawnień, aby wystawić ofertę (sprzedaż zablokowana). Ureguluj zaległości w \"Rozliczenia z Allegro\";"
        }
    ]
}
```
Got this message on my account :

_Sales suspension
The ability to sell from your account is currently suspended. This may be due to unpaid bills or other violations of the Terms & Conditions. To lift the sales suspension, pay the outstanding amounts or contact us_

Balance is positive so how can i unlock my dev account (obtao) ?

Regards

**Comment by PrzemyslawLukanowski** [comment]
Please send me your login or ID, so I will check it and remove the suspension.

**Comment by lwillems** [comment]
@PrzemyslawLukanowski 

Thx for your quick reply, my account nickname is obtao and email is willems.laurent@gmail.com.

Regards

**Comment by PrzemyslawLukanowski** [comment]
Thank you, I removed suspension manually so you can check if it works fine now :)

**Comment by lwillems** [comment]
Everything works fine thx @PrzemyslawLukanowski
