### ISSUE TITLE
Zestawy ofert Syndbox - nie widoczne

### ISSUE THREAD

**Issue by Levena007** [allegro/allegro-api#7165]
Witam,
zrobiłam testowo zestaw ofert. Na poziomie "Bundles & Discounts" są one widoczne, jednak nie widzę ich na poziomie produktu.
W czym leży problem?
Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam ten problem, przekazuję sprawę do zespołu odpowiedzialnego za usługę i wrócę z informacją, gdy poznam więcej szczegółów.

**Comment by PrzemyslawLukanowski** [comment]
Zestawy wyświetlamy poprawnie, upewnij się jednak, czy oferty:

- miały na sobie jakąś kampanię obniżającą cenę,
- były przeglądane w innym serwisie lub w innym języku (zestawy są widoczne tylko na allegro-pl dla języka polskiego i waluty PLN).
