### ISSUE TITLE
Problem z wystawianiem ofert na rynek Czeski

### ISSUE THREAD

**Issue by PiotrPiotrP** [allegro/allegro-api#7166]
Dzień dobry
Nie wiem dlaczego dostaje błąd.
PUT    https://api.allegro.pl/sale/offers/13767112425 requestBody={"afterSalesServices":{"impliedWarranty":{"id":"2599d697-eaee-4a9d-bfd5-213717c9ba62"},"returnPolicy":{"id":"10bbd9d6-a61a-421b-aafd-e2289c330400"},"warranty":{"id":"9f8841ad-ad8a-4cd8-aaf8-ae9087556b6f"}},"category":{"id":"5537"},"delivery":{"shippingRates":{"id":"92cb3f82-ae74-4d10-8804-2d9a444c4d55"},"handlingTime":"PT24H"},"external":{"id":"stocksell_890590930"},"id":"13767112425","images":[{"url":"https://a.allegroimg.com/original/11f4f7/9c03f68e44f48014c65159dce7d6"},{"url":"https://a.allegroimg.com/original/111399/5cd1b8d34e0fab639431e5a750d8"},{"url":"https://a.allegroimg.com/original/118953/a3ad39c64f8aae63d7806302838e"}],"location":{"city":"Skawina","countryCode":"PL","postCode":"32-050","province":"MALOPOLSKIE"},"parameters":[{"id":"54","valuesIds":["54_4"]},{"id":"201025","valuesIds":["201025_2513"]},{"id":"221333","valuesIds":["221333_295213"]},{"id":"3766","valuesIds":["3766_1"]},{"id":"202897","valuesIds":["202897_8192"]},{"id":"202893","valuesIds":["202893_214337"]},{"id":"15851","valuesIds":["15851_2"]},{"id":"3786","values":[],"valuesIds":["3786_85"]},{"id":"249512","valuesIds":["249512_1647422"]},{"id":"206438","valuesIds":["206438_227562"]},{"id":"11323","valuesIds":["11323_2"]},{"id":"201405","valuesIds":["201405_208161"]},{"id":"201017","valuesIds":["201017_2317"]}],"name":"KURTKA JEANSOWA NIEBIESKA MĘSKA KLASYCZNA M 2ZOH","payments":{"invoice":"VAT"},"publication":{"status":"ACTIVE","startingAt":"2023-05-29T16:32:00.000Z","republish":false},"sellingMode":{"format":"BUY_NOW","price":{"amount":59.99,"currency":"PLN"}},"stock":{"available":1,"sold":0,"unit":"UNIT"},"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003ch2\u003eKURTKA JEANSOWA NIEBIESKA MĘSKA KLASYCZNA\u003c/h2\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11f4f7/9c03f68e44f48014c65159dce7d6"},{"type":"TEXT","content":"\u003ch2\u003eOpis Produktu\u003c/h2\u003e\u003cul\u003e\u003cli\u003e\u003cb\u003eMarka\u003c/b\u003e inna          \u003c/li\u003e\u003cli\u003e\u003cb\u003eKolor\u003c/b\u003e Niebieski     \u003c/li\u003e\u003cli\u003e\u003cb\u003eSkład\u003c/b\u003e 100% bawełna    \u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka papierowa\u003c/b\u003e Brak\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka wewnętrzna\u003c/b\u003e Wycięte ze względu na restrykcję outletową\u003c/li\u003e\u003cli\u003e\u003cb\u003eRozmiar\u003c/b\u003e M\u003c/li\u003e\u003cli\u003e\u003cb\u003eStan przedmiotu\u003c/b\u003e zapach użytkowania, lekkie ślady użytkowania, kolor mniej intensywny\u003c/li\u003e\u003cli\u003e\u003cb\u003eCena katalogowa\u003c/b\u003e 189,99 zł\u003c/li\u003e\u003cli\u003e\u003cb\u003euwagi\u003c/b\u003e kurtka wpada w żólty kolor\u003c/li\u003e\u003cli\u003e\u003cb\u003estan\u003c/b\u003e dobry\u003c/li\u003e\u003c/ul\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/111399/5cd1b8d34e0fab639431e5a750d8"},{"type":"IMAGE","url":"https://a.allegroimg.com/original/118953/a3ad39c64f8aae63d7806302838e"}]}]},"tax":{"percentage":"23.00"},"language":"pl-PL"} exception=Niepoprawna odpowiedź z Allegro. Kod: 422. Błąd: VALIDATION_ERROR Platforms other than allegro.pl only support offers with a product linked. Platforms other than allegro.pl only support offers with a product linked. ConstraintViolationException.ForeignMarketplacesWithProductOnly . Trace-id=[95775c6c06e84e]. 

jest kurier który zapewnia dostawę na Czechy, jest cena w koronach, oferta jest połączona z produktem, jest też taka kategoria, tłumaczenie rozumiem że będzie zrobione automatycznie.

**Comment by PiotrPiotrP** [comment]
Dziękuję

**Comment by PiotrPiotrP** [comment]
PATCH  https://api.allegro.pl/sale/product-offers/13125160821 requestBody={"name":"PUBLIC DESIRE SANDAŁKI BEŻOWE KLASYCZNE 38 1XOB","sellingMode":{"format":"BUY_NOW","price":{"amount":109.99,"currency":"PLN"}}} exception=Niepoprawna odpowiedź z Allegro. Kod: 422. Błąd: ConstraintViolationException.ForeignMarketplacesWithProductOnly W serwisie innym niż allegro.pl wspierane są tylko oferty z podpiętym produktem. Platforms other than allegro.pl only support offers with a product linked. ConstraintViolationException.ForeignMarketplacesWithProductOnly . Trace-id=[8774ce067fe04422]. 

Przy zmianie ceny też trzeba wysyłać product_id?
Z tego co czytałem w dokumentacji to wtedy muszę uzupełnić też inne pola takie jak opis. Czy tak jest tylko w przypadku wystawiania ofert na rynek czeski?
Czy tak jest też dla ofert wystawianych wyłącznie na rynek polski. 
Wcześniej taki sposób zmiany ceny działał zanim był wprowadzony rynek czeski.

**Comment by PrzemyslawLukanowski** [comment]
Komunikat wynika z tego, że w ofercie masz włączoną deklarację widoczności na allegro-cz:

```
        "marketplaces": {
            "base": {
                "id": "allegro-pl"
            },
            "additional": [
                {
                    "id": "allegro-cz"
                }
            ]
```

W momencie, kiedy otrzymujemy Twój request, walidujemy całą ofertę. Ponieważ w polu `product` widnieje `null`, w rezultacie odpowiadamy przytoczonym komunikatem o braku połączenia z produktem.

> Z tego co czytałem w dokumentacji to wtedy muszę uzupełnić też inne pola takie jak opis. Czy tak jest tylko w przypadku wystawiania ofert na rynek czeski?
> Czy tak jest też dla ofert wystawianych wyłącznie na rynek polski.
> 

Każda oferta musi mieć opis - albo dostarczony przez Ciebie w polu `description`, albo pobrany automatycznie z danych produktu, jeśli wystawiasz przez POST /sale/product-offers. Pole jest wymagane niezależnie od rynku - jeśli oferta już go posiada, nie musisz robić dodatkowych kroków w tym kontekście, automatycznie przetłumaczymy go na czeski.

**Comment by PiotrPiotrP** [comment]
To jeszcze się upewnie, Oferta 13125160821 ma w polu product.id "e7e623e5-1fd1-4705-8eac-78f3d8a26734",  czy przy edycji ceny muszę jeszcze raz wysłać product.id?

**Comment by PrzemyslawLukanowski** [comment]
Jesteś pewien, że ma prawidłowo wypełnione to pole? Według naszych danych, dla tej oferty, w polu `product` widnieje `null`. Jeśli byłoby tam jednak ID, to wtedy nie musiałbyś wysyłać `product.id`, wystarczyłaby tylko informacja o tych polach, które chcesz rzeczywiście zmienić.

**Comment by PiotrPiotrP** [comment]
Dobra to pewnie tłumaczy wszystko, u mnie w bazie są te pola. Nie wiem skąd ta rozbieżność ale w takim razie muszę przy edycji wysłać to pole do was. Dziękuję.
