### ISSUE TITLE
Jak sprawdzić, czy klient płaci za transport?

### ISSUE THREAD

**Issue by mkawczynski** [allegro/allegro-api#7167]
W jaki sposób za pomocą API zweryfikować, czy klient faktycznie zapłacił za transport, czy nie? API zwraca informację o tym, czy klient ma SMART oraz jakie były koszty transportu, ale nie zwraca  informacji, czy nastąpiła dopłata do transportu przez Allegro.

**Comment by PrzemyslawLukanowski** [comment]
Taką informację sprawdzisz na billingu [GET /billing/billing-entries](https://developer.allegro.pl/documentation#operation/getBillingEntries) - o dopłacie Allegro do transportu świadczą takie operacje (`type.id`) jak np. HB1, HB2, etc. HXO, a numer powiązanego zamówienia znajdziesz w polu `order.id`. Pełną listę typów zwracamy w endpoincie [/billing/billing-types](https://developer.allegro.pl/documentation#operation/getBillingTypes).
