### ISSUE TITLE
[Allegro.cz sandbox] Problem z rejestracją

### ISSUE THREAD

**Issue by PProtasewicz** [allegro/allegro-api#7168]
Witam,

mam problem z dokończeniem rejestracji konta na platformie Allegro.cz sandbox tzn. nie mogę wysłać zdjęcia "dokumentu" aby dokończyć rejestracje (konto TestCZ123):

![image](https://github.com/allegro/allegro-api/assets/38344667/18f838ff-1dde-484f-bb0c-ee6a458ff7a4)

Próbowałem różnych formatów plików png, jpg, pdf, każdy z plików "ważył"  od 1 MB do 6 MB,  ale w odpowiedzi dostaje informacje "Nie mogliśmy przesłać formularza. Spróbuj ponownie.", lub też nagle platforma twierdzi że nie zaakceptuje moich zdjęć. 

![image](https://github.com/allegro/allegro-api/assets/38344667/2a318ffb-7505-4499-ae8f-f98b533a5fb3)

Pozdrawiam
Piotr

**Comment by MartaNowaczyk** [comment]
Witam, właśnie dodałam nowe konto i dokumenty - obraz w formacie PNG. Być może były to chwilowe problemy. Jeśli jednak nadal masz ten sam problem, spróbuj przejść ten proces w innej przeglądarce. Gdyby to nie pomogło daj mi proszę znać.

**Comment by PProtasewicz** [comment]
@MartaNowaczyk Niestety nie udało mi się wrzucić dokumentów, próbowałem Edge, Chrome, zarówno w trybie incognito itd.

**Comment by MartaNowaczyk** [comment]
Dzięki za info, będziemy to jeszcze weryfikować w takim razie.

**Comment by MartaNowaczyk** [comment]
Znaleźliśmy problem po naszej stronie i mam nadzieję, że teraz już wszystko będzie działać stabilnie. Jeszcze się upewniamy, że wszystko działa poprawnie, ale cieszę się, że już widać efekty.
