### ISSUE TITLE
Proszę o dodanie Badge do 3 z naszych ofert na Allegro Sandbox

### ISSUE THREAD

**Issue by michalmicpaw** [allegro/allegro-api#7169]
Dzień dobry,

chcemy przetestować generowanie statystyk w naszej aplikacji, odnośnie Badges, pobranych z ofert konta SandBox. Prosimy o dodanie Badgy do ofert (sandboxowych) o id:

7705157001
7702993944
7702914275

Prosimy aby badge były aktywne.

Dziękuję :)
M.

**Comment by Lukasz-Zurek** [comment]
@michalmicpaw Możesz samodzielnie przetestować ten proces za pomocą kampanii SANDBOX_TEST_CAMPAIGN.

Więcej informacji znajdziesz [tutaj](https://developer.allegro.pl/tutorials/jak-przypisac-oferte-kampanii-GRaj0q6Gwuy#jak-testowac-kampanie).

**Comment by michalmicpaw** [comment]
Nie jestem pewien czy dobrze rozumiem. Nie chcę przypisywać nowej kampanii dla ofert sandboxowych na produkcji, tylko do ofert Allegro w AllegroSandbox. Dostałem informację, że aby włączyć odznakę muszę napisać tutaj. Jeżeli się mylę to proszę o sprostowanie.

Dziękuję!
M.

**Comment by michalmicpaw** [comment]
Testowałem Badges na innym sklepie, mamy tam 7 ofert z odznakami. Chodzi mi o włączenie odznak, tak samo jak w 1 przypadku, o którym piszę.
Dziękuję

**Comment by Lukasz-Zurek** [comment]
> Nie jestem pewien czy dobrze rozumiem. Nie chcę przypisywać nowej kampanii dla ofert sandboxowych na produkcji, tylko do ofert Allegro w AllegroSandbox.

W opisany właśnie sposób, za pośrednictwem API, przypiszesz nowe kampanie dla ofert testowych na Allegro Sandbox.

**Comment by Lukasz-Zurek** [comment]
@michalmicpaw Przekazałem Twoją prośbę do innego zespołu. Jak tylko uzyskam informacje, wrócę do Ciebie w tym wątku.

**Comment by michalmicpaw** [comment]
Niestety nie o to mi chodziło. Chciałbym mieć nową datę w polu publication->from. Zaktualizowaliście Państwo tylko cenę. Zależy mi na czasowym wyłączeniu i włączeniu. Zaznaczam, że nie chodzi mi tylko o aktualizację daty from. Proszę o wyłączenie na co najmniej 30 sek. i ponowne włączenie (może być z taką samą ceną, jeżeli system na to pozwala).

Dziękuję!
M.

**Comment by Lukasz-Zurek** [comment]
@michalmicpaw Proszę sprawdzić teraz.
