### ISSUE TITLE
Upload zdjęcia z URL - HTTP 422 UnprocessableEntity (URL wyrzuca 403 Forbidden)

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#7171]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,
w przypadku zdjęć pochodzących z jednej domeny zauważyłem problem z uploadem, wyrzuca błąd UnprocessableEntity.

Link:
```
https://images.vestiairecollective.com/cdn-cgi/image/w=500,q=75,f=auto,/produit/red-polyester-bill-levkoff-dress-27194754-1_1.jpg
```

Komunikat błędu:

```
{
   "errors":[
      {
         "code":"DownloadError.Forbidden",
         "message":"Downloading image from URL 'https://images.vestiairecollective.com/cdn-cgi/image/w=500,q=75,f=auto,/produit/red-polyester-bill-levkoff-dress-27194754-1_1.jpg' failed. Server returned the following HTTP status code: 403 FORBIDDEN and response body: ''.",
         "details":null,
         "path":null,
         "userMessage":"Downloading image from URL 'https://images.vestiairecollective.com/cdn-cgi/image/w=500,q=75,f=auto,/produit/red-polyester-bill-levkoff-dress-27194754-1_1.jpg' failed. Server returned the following HTTP status code: 403 FORBIDDEN and response body: ''."
      }
   ]
}
```

Jednakże wchodząc z poziomu przeglądarki wszystko jest okej. Proszę o spojrzenie na problem.

**Comment by Lukasz-Zurek** [comment]
Przekazałem ten temat od razu do zespołu odpowiedzialnego za zdjęcia w Serwisie. Wkrótce wrócę do Ciebie z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
@hahyes Okazuje się, że zwróciliśmy błąd, ponieważ to zdjęcie ma rozszerzenie avif.

**Comment by hahyes** [comment]
@Lukasz-Zurek Rzeczywiście, wychodzi na to, że ten dopisek '.jpg' to tylko iluzja. Dziękuję za odpowiedź, zamykam wątek i pozdrawiam.
