### ISSUE TITLE
Parametr ean

### ISSUE THREAD

**Issue by PunktAutoCzesci** [allegro/allegro-api#7173]
Cześć, szybkie pytanie. 
Czy parametr z kodem EAN zawsze ma ID 225693 ? Jeśli nie to czy zawsze nazywa się "EAN" ?
Dzięki

**Comment by Lukasz-Zurek** [comment]
> Czy parametr z kodem EAN zawsze ma ID 225693 ?

Tak.

**Comment by PunktAutoCzesci** [comment]
ok, dzięki.
