### ISSUE TITLE
Brak możliwości obsłużenia pobrania packeta poprzez API?

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#7174]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

Witam, chciałbym się upewnić co do danych zwracanych z API w metod dostaw PACKETA. Dla obu możliwych jest zaznaczone ,że COD jest niedostępny, czy ma się to ze stanem faktycznym ? Jeśli tak to czy jest planowana obsługa płatności za pobraniem?

![obraz](https://github.com/allegro/allegro-api/assets/87118074/e281c716-c6b5-4beb-8526-dac310fa62e0)

**Comment by Lukasz-Zurek** [comment]
W tym celu musisz skorzystać z innych serwisów:

- Allegro Wysyłka z Polski do Czech - Odbiór w Punkcie Packeta pobranie (114d388f-354f-41c1-a0ea-36d2032265ad),
- Allegro Wysyłka z Polski do Czech - Automaty Paczkowe Packeta pobranie (129b132a-348c-4b48-aba0-9c4a33aba97c).
