### ISSUE TITLE
Brak zmiany ceny metodą PATCH

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#7175]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: 
Czy zasób działa poprawnie czy jest to błąd po mojej stronie? Wywołuje poniższe zapytanie celem zmiany ceny oferty
```
curl --location --request PATCH 'https://api.allegro.pl/sale/product-offers/13798046xxx' \
--header 'Authorization: Bearer {cut}' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--data-raw '{
    "id": 13798046xxx,
    "sellingMode": {
        "startingPrice": {
            "amount": 1,
            "currency": "PLN"
        }
    }
}'
```
W odpowiedzi otrzymuje (fragment)
```
"sellingMode": {
        "format": "AUCTION",
        "price": null,
        "startingPrice": {
            "amount": "1.00",
            "currency": "PLN"
        },
        "minimalPrice": null
    },
```
Jednak cena się nie zmienia. Struktura validation też jest pusta, kod odpowiedzi 200
Proszę o sprawdzenie. Trace Id zapytania `85cf2149e9f6bd69`

**Comment by Lukasz-Zurek** [comment]
Potwierdzam. Sprawę przekazałem do odpowiedniego zespołu. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@pawelosajda Zespół odpowiedzialny za tę usługę - wdrożył poprawkę i obecnie zmiana ceny początkowej realizowana jest prawidłowo.

Przepraszamy za zaistniałe utrudnienia.
