### ISSUE TITLE
Błąd generowania etykiet

### ISSUE THREAD

**Issue by CSVK2022** [allegro/allegro-api#7177]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzien dobry,  mamy problem z wygenerowaniem etykiet, wygląda jak ogólny problem WzA, gdyż nie dotyczy tylko jednego spedytora.
Zwracany błąd:
"{\"errors\":[{\"code\":\"FAILED_TO_OBTAIN_PL_POST_WAYBILL\",\"message\":\"The label is not ready yet or there was an error in the carrier API. Try again later\",\"details\":null,\"path\":null,\"userMessage\":\"The label is not ready yet or there was an error in the carrier API. Try again later\"}]}"

Przykładowy parcel ID: 9f0f494f-99d0-47b8-ac73-afe6ed967411

**Comment by MaciejFrackowiak** [comment]
Tak, niestety przewoźnik Packeta ma awarię - czekamy na rozwiązanie problemu po ich stronie.

**Comment by MaciejFrackowiak** [comment]
Problem został wyeliminowany.
