### ISSUE TITLE
Podmiot kończący oferty

### ISSUE THREAD

**Issue by BartlomiejCalus** [allegro/allegro-api#7178]
Czy istnieje możliwość uzyskania dokładniejszej informacji o podmiocie który zakończył ofertę niż ta którą zwraca dziennik zdarzeń? Zależy nam na tym żeby ustalić czy zostało to wykonane przez API czy przez bezpośrednio przy użyciu serwisu (wartość zwracana przez GET /sale/offer-events to "USER").

**Comment by MaciejFrackowiak** [comment]
W przypadku obu ofert zlecenia zakończenia zostały wysłane z aplikacji o ClientID=61da0cb9xxxxxxxxx433d6cc.

**Comment by BartlomiejCalus** [comment]
Super, dziękuję za pomoc
