### ISSUE TITLE
Zabronione nazwy marek

### ISSUE THREAD

**Issue by PiotrPiotrP** [allegro/allegro-api#7179]
Dzień dobry
Myślałem że restrykcje związane z nazwami marek wchodzą od 3 lipca, czy one już działają?
Można gdzieś znaleźć listę zabronionych marek?

POST   https://api.allegro.pl/sale/offers requestBody={"afterSalesServices":{"impliedWarranty":{"id":"e7eba7a3-af27-42c8-8e1f-12ff58ef127a"},"returnPolicy":{"id":"68340242-ef04-4d1a-a1a9-08788fe3a24d"},"warranty":{"id":"785f2261-0e68-4b57-a21c-e2015a1cabb8"}},"attachments":[],"category":{"id":"257903"},"delivery":{"shippingRates":{"id":"77b40ad8-3375-420d-a32c-20ff7fbbab66"},"handlingTime":"PT24H"},"external":{"id":"stocksell_545142145"},"images":[{"url":"https://a.allegroimg.com/original/11b3a1/553cb9324176aba71cf57671e494"},{"url":"https://a.allegroimg.com/original/113502/7c42fbe4442187569a0512f9cfc3"},{"url":"https://a.allegroimg.com/original/11d64c/4efc344d4f128ef7d93e65a2b548"}],"location":{"city":"Skawina","countryCode":"PL","postCode":"32-050","province":"MALOPOLSKIE"},"parameters":[{"id":"11323","values":[],"valuesIds":["11323_2"]},{"id":"127848","values":[],"valuesIds":["127848_1"]},{"id":"15851","values":[],"valuesIds":["15851_1"]},{"id":"203085","values":[],"valuesIds":["203085_4"]},{"id":"203089","values":[],"valuesIds":["203089_1"]},{"id":"203093","values":["5"],"valuesIds":[]},{"id":"203105","values":[],"valuesIds":["203105_215381"]},{"id":"219629","values":[],"valuesIds":["219629_286877"]},{"id":"224017","values":["DC3729 002"],"valuesIds":[]},{"id":"225693","values":["7759027922712"],"valuesIds":[]},{"id":"22728","values":[],"valuesIds":["22728_215177"]},{"id":"229205","values":[],"valuesIds":["229205_340257"]},{"id":"232289","values":[],"valuesIds":["232289_366645"]},{"id":"249512","values":[],"valuesIds":["249512_1647428"]},{"id":"26388","values":[],"valuesIds":["26388_65536"]},{"id":"3766","values":[],"valuesIds":["3766_2397"]},{"id":"64","values":[],"valuesIds":["64_6"]},{"id":"6828","values":[],"valuesIds":["6828_1"]},{"id":"7108","values":[],"valuesIds":["7108_34"]}],"name":"NIKE REVOLUTION 6 BUTY SPORTOWE DAMSKIE 40 1SDD","payments":{"invoice":"VAT"},"publication":{"startingAt":"2023-06-05T16:00:06.000Z","republish":false},"sellingMode":{"format":"BUY_NOW","price":{"amount":203.99,"currency":"PLN"}},"stock":{"available":1,"sold":0,"unit":"UNIT"},"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003ch2\u003eNIKE REVOLUTION 6 BUTY SPORTOWE DAMSKIE\u003c/h2\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11b3a1/553cb9324176aba71cf57671e494"},{"type":"TEXT","content":"\u003ch2\u003eOpis Produktu\u003c/h2\u003e\u003cul\u003e\u003cli\u003e\u003cb\u003eMarka\u003c/b\u003e Nike Performance\u003c/li\u003e\u003cli\u003e\u003cb\u003eKolor\u003c/b\u003e czarny, różowy\u003c/li\u003e\u003cli\u003e\u003cb\u003eSkład\u003c/b\u003e materiał zewnętrzny syntetyk + tekstylia, materiał wewnętrzny tekstylia , podeszwa syntetyk \u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka papierowa\u003c/b\u003e Brak\u003c/li\u003e\u003cli\u003e\u003cb\u003ePudełko\u003c/b\u003e Produkt w pudełku zastępczym\u003c/li\u003e\u003cli\u003e\u003cb\u003eRozmiar\u003c/b\u003e EU 40\u003c/li\u003e\u003cli\u003e\u003cb\u003eStan przedmiotu\u003c/b\u003e oba buty: ślady użytkowania na całości\u003c/li\u003e\u003cli\u003e\u003cb\u003eCena katalogowa\u003c/b\u003e 310,99 zł\u003c/li\u003e\u003cli\u003e\u003cb\u003estan\u003c/b\u003e bardzo dobry\u003c/li\u003e\u003cli\u003e\u003cb\u003eInformacje dodatkowe\u003c/b\u003e brak metki ze składem, skład sugerowany\u003c/li\u003e\u003c/ul\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/113502/7c42fbe4442187569a0512f9cfc3"},{"type":"IMAGE","url":"https://a.allegroimg.com/original/11d64c/4efc344d4f128ef7d93e65a2b548"}]}]},"tax":{"percentage":"23.00"},"product":{"id":"ad2c8be5-520d-4498-9eee-58dc3050cd8e"},"language":"pl-PL"} responseBody={"id":"13792947267","name":"NIKE REVOLUTION 6 BUTY SPORTOWE DAMSKIE 40 1SDD","category":{"id":"257903"},"product":{"id":"ad2c8be5-520d-4498-9eee-58dc3050cd8e"},"parameters":[{"id":"11323","valuesIds":["11323_2"],"values":[],"rangeValue":null},{"id":"127848","valuesIds":["127848_1"],"values":[],"rangeValue":null},{"id":"15851","valuesIds":["15851_1"],"values":[],"rangeValue":null},{"id":"203085","valuesIds":["203085_4"],"values":[],"rangeValue":null},{"id":"203089","valuesIds":["203089_1"],"values":[],"rangeValue":null},{"id":"203093","valuesIds":[],"values":["5"],"rangeValue":null},{"id":"203105","valuesIds":["203105_215381"],"values":[],"rangeValue":null},{"id":"219629","valuesIds":["219629_286877"],"values":[],"rangeValue":null},{"id":"224017","valuesIds":[],"values":["DC3729 002"],"rangeValue":null},{"id":"225693","valuesIds":[],"values":["7759027922712"],"rangeValue":null},{"id":"22728","valuesIds":["22728_215177"],"values":[],"rangeValue":null},{"id":"229205","valuesIds":["229205_340257"],"values":[],"rangeValue":null},{"id":"232289","valuesIds":["232289_366645"],"values":[],"rangeValue":null},{"id":"249512","valuesIds":["249512_1647428"],"values":[],"rangeValue":null},{"id":"26388","valuesIds":["26388_65536"],"values":[],"rangeValue":null},{"id":"3766","valuesIds":["3766_2397"],"values":[],"rangeValue":null},{"id":"64","valuesIds":["64_6"],"values":[],"rangeValue":null},{"id":"6828","valuesIds":["6828_1"],"values":[],"rangeValue":null},{"id":"7108","valuesIds":["7108_34"],"values":[],"rangeValue":null}],"customParameters":null,"description":{"sections":[{"items":[{"type":"TEXT","content":"<h2>NIKE REVOLUTION 6 BUTY SPORTOWE DAMSKIE</h2>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11b3a1/553cb9324176aba71cf57671e494"},{"type":"TEXT","content":"<h2>Opis Produktu</h2><ul><li><b>Marka</b> Nike Performance</li><li><b>Kolor</b> czarny, różowy</li><li><b>Skład</b> materiał zewnętrzny syntetyk + tekstylia, materiał wewnętrzny tekstylia , podeszwa syntetyk </li><li><b>Metka papierowa</b> Brak</li><li><b>Pudełko</b> Produkt w pudełku zastępczym</li><li><b>Rozmiar</b> EU 40</li><li><b>Stan przedmiotu</b> oba buty: ślady użytkowania na całości</li><li><b>Cena katalogowa</b> 310,99 zł</li><li><b>stan</b> bardzo dobry</li><li><b>Informacje dodatkowe</b> brak metki ze składem, skład sugerowany</li></ul>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/113502/7c42fbe4442187569a0512f9cfc3"},{"type":"IMAGE","url":"https://a.allegroimg.com/original/11d64c/4efc344d4f128ef7d93e65a2b548"}]}]},"compatibilityList":null,"tecdocSpecification":null,"images":[{"url":"https://a.allegroimg.com/original/11b3a1/553cb9324176aba71cf57671e494"},{"url":"https://a.allegroimg.com/original/113502/7c42fbe4442187569a0512f9cfc3"},{"url":"https://a.allegroimg.com/original/11d64c/4efc344d4f128ef7d93e65a2b548"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"203.99","currency":"PLN"},"startingPrice":null,"minimalPrice":null,"netPrice":null},"tax":{"percentage":"23.00","rate":"23.00","subject":null,"exemption":null,"id":"b763d782-572a-47db-8752-8b2cb32b3d0a"},"stock":{"available":1,"unit":"UNIT"},"publication":{"duration":null,"status":"INACTIVE","startingAt":"2023-06-05T16:00:00.000Z","endingAt":null,"endedBy":null,"republish":false,"marketplaces":{"base":{"id":"allegro-pl"},"additional":[]}},"delivery":{"shippingRates":{"id":"77b40ad8-3375-420d-a32c-20ff7fbbab66"},"handlingTime":"PT24H","additionalInfo":null,"shipmentDate":null},"payments":{"invoice":"VAT"},"discounts":null,"afterSalesServices":{"impliedWarranty":{"id":"e7eba7a3-af27-42c8-8e1f-12ff58ef127a"},"returnPolicy":{"id":"68340242-ef04-4d1a-a1a9-08788fe3a24d"},"warranty":{"id":"785f2261-0e68-4b57-a21c-e2015a1cabb8"}},"additionalServices":null,"sizeTable":null,"fundraisingCampaign":null,"promotion":{"emphasized":false,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"MALOPOLSKIE","city":"Skawina","postCode":"32-050"},"external":{"id":"stocksell_545142145"},"attachments":[],"contact":null,"validation":{"errors":[{"code":"VALIDATION_ERROR","message":"Your offer title or description may be misleading as to the goods' origin, manufacturer, or brand and, as a result, violate the rights of a company that cooperates with us as part of Rights Protection Cooperation Program. . In your offer description, you used a registered word trademark to sell a product of a different brand (visible in the ‘Parameters’ section).","details":"","path":"name","userMessage":"Your offer title or description may be misleading as to the goods' origin, manufacturer, or brand and, as a result, violate the rights of a company that cooperates with us as part of Rights Protection Cooperation Program. . In your offer description, you used a registered word trademark to sell a product of a different brand (visible in the ‘Parameters’ section)."}],"warnings":[{"code":"VALIDATION_WARNING","message":"As a merchant, take care of an accurate description of the offered goods. If you have information on the qualitative composition of the materials from which the product is made, include this data in the offer's description. At the same time, include percentage value of each material used in producing the goods.","details":"","path":"name","userMessage":"As a merchant, take care of an accurate description of the offered goods. If you have information on the qualitative composition of the materials from which the product is made, include this data in the offer's description. At the same time, include percentage value of each material used in producing the goods."},{"code":"VALIDATION_WARNING","message":"Did you know you can reach more customers by adding export options to your offers? Don't wait, add export options now, and increase your sales. Make sure the product has the required labeling in the official language of the country to which it will be delivered.","details":"","path":"name","userMessage":"Did you know you can reach more customers by adding export options to your offers? Don't wait, add export options now, and increase your sales. Make sure the product has the required labeling in the official language of the country to which it will be delivered."}],"validatedAt":"2023-06-02T16:32:58.610Z"},"b2b":{"buyableOnlyByBusiness":false},"messageToSellerSettings":null,"createdAt":"2023-06-02T16:32:58.000Z","updatedAt":"2023-06-02T16:32:58.615Z","language":"pl-PL","additionalMarketplaces":{"allegro-cz":{"sellingMode":null,"publication":{"state":"NOT_REQUESTED"}}},"taxSettings":{"rates":[{"rate":"23.00","countryCode":"PL"}],"subject":null,"exemption":null}} trace-id=[beabd4f70e7c86ca]

**Comment by MaciejFrackowiak** [comment]
Mechanizm odpowiedzialny za walidowanie opisów, tytułów ofert od dłuższego już czasu sprawdza, czy użyte tam frazy są zgodne z parametrami oferowanego przedmiotu. Sama jednak konfiguracja jego jest niezależna od funkcjonowania API - taki sam komunikat otrzymałbyś na stronie WWW Allegro. Jeżeli masz więcej pytań dot. funkcjonowania narzędzia proszę skontaktuj się z obsługą serwisu za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt).

**Comment by MaciejFrackowiak** [comment]
@karoprogramistka Próbuję wyjaśnić zauważoną przez Ciebie rozbieżność, wrócę z odpowiedzią.

**Comment by karoprogramistka** [comment]
Czy udało się wyjaśnić?

**Comment by MaciejFrackowiak** [comment]
Tak, mam już więcej informacji. W sytuacji, gdy walidacja oferty trwa dłużej niż zwyczajowo, wówczas na etapie tworzenia taka oferta jest dopuszczana do wystawienia, co miało miejsce w przypadku oferty przygotowanej przez formularz na WWW. Nie oznacza to jednak, że taka oferta jest dla nas OK - po pojawieniu się jej już w serwisie podlega ponownej weryfikacji i wówczas może zostać usunięta z uwagi na problematyczną zawartość, o której informowaliśmy dla oferty wystawianej z poziomu API.
