### ISSUE TITLE
Kiedy nie można zmienić trwającej oferty

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#718]
Pytanie jakie warunki muszą być spełnione aby nie można było zmienić trwającej oferty tylko np. trzeba byłoby ją zakończyć a następnie zaktualizować dane i wznowić ?

**Comment by PawelTaberski** [comment]
Zakończenie/Wstrzymanie oferty jest funkcją dedykowaną szczególnie dla sprzedawców, którzy mają chwilowe braki magazynowe, ale nie chcą kończyć oferty, aby nie tracić jej popularności. W takim wypadku można zatrzymać ofertę i wznowić ją jak znów dany produkt będzie dostępny.

**Comment by pietrach** [comment]
Ale chodzi mi też o pytanie kiedy nie mogę zmienić trwającej aukcji ? I jakich danych nie mogę w niej zmienić ?

**Comment by PawelTaberski** [comment]
Ograniczenia edytowanych elementów oferty dotyczą momentu, gdy w danej ofercie nastąpiła sprzedaż. Więcej na ten temat znajdziesz [tutaj](https://allegro.pl/webapi/faq.php#faq_7).
