### ISSUE TITLE
Numer paczki DHL

### ISSUE THREAD

**Issue by drzemik** [allegro/allegro-api#7180]
Wygenerowałem paczkę typu Allegro Kurier DHL:
-- REQUEST --
{
    "serviceId": "a3b4db98-4a70-4542-84ee-c642604d9d8a",
    "receiver": {
        "address": {
            "street": "Siedliska 57",
            "postCode": "32-104",
            "city": "Koniusza",
            "countryCode": "PL"
        },
        "email": "mpj6r29z5d+4498b8914@allegromail.pl",
        "name": "MAKROTERM SIEDLISKA",
        "company": null,
        "phone": "579307388",
        "pointId": ""
    },
    "pickup": {
        "address": {
            "street": "Bakaliowa 26",
            "postCode": "05-080",
            "city": "Mościska",
            "countryCode": "PL"
        },
        "company": "ERPATECH",
        "email": "biuro@erpatech.pl",
        "phone": "(22) 431-05-00"
    },
    "items": [
        {
            "dimensions": {
                "height": {
                    "value": 25,
                    "unit": "CENTIMETER"
                },
                "width": {
                    "value": "25",
                    "unit": "CENTIMETER"
                },
                "depth": {
                    "value": "25",
                    "unit": "CENTIMETER"
                }
            },
            "weight": {
                "value": "10",
                "unit": "KILOGRAM"
            },
            "description": "elektronarzędzia",
            "type": "PACKAGE"
        }
    ],
    "type": "PACKAGE"
}
-- RESPONSE --
{
    "parcelId": "5c1154e8-2fb8-44e5-905d-340aa9d57966",
    "serviceId": "a3b4db98-4a70-4542-84ee-c642604d9d8a",
    "label": {
        "sender": {
            "name": "ERPATECH",
            "company": "ERPATECH",
            "address": {
                "street": "Bakaliowa 26",
                "postCode": "05-080",
                "city": "Mościska",
                "county": null,
                "countryCode": "PL"
            },
            "email": "biuro@erpatech.pl",
            "phone": "224310500"
        },
        "fileFormat": "PDF",
        "referenceNumber": ""
    },
    "receiver": {
        "name": "MAKROTERM SIEDLISKA",
        "company": null,
        "address": {
            "street": "Siedliska 57",
            "postCode": "32-104",
            "city": "Koniusza",
            "county": null,
            "countryCode": "PL"
        },
        "pointId": null,
        "email": "mpj6r29z5d+4498b8914@allegromail.pl",
        "phone": "579307388"
    },
    "pickup": {
        "name": "ERPATECH",
        "company": "ERPATECH",
        "address": {
            "street": "Bakaliowa 26",
            "postCode": "05-080",
            "city": "Mościska",
            "county": null,
            "countryCode": "PL"
        },
        "pointId": null,
        "email": "biuro@erpatech.pl",
        "phone": "224310500"
    },
    "items": [
        {
            "waybill": "26384368836",
            "dimensions": {
                "height": {
                    "value": "25",
                    "unit": "CENTIMETER"
                },
                "width": {
                    "value": "25",
                    "unit": "CENTIMETER"
                },
                "depth": {
                    "value": "25",
                    "unit": "CENTIMETER"
                }
            },
            "weight": {
                "value": "10.0",
                "unit": "KILOGRAM"
            },
            "description": "elektronarzędzia",
            "value": {
                "amount": "0.0",
                "currency": "PLN"
            },
            "type": "PACKAGE"
        }
    ],
    "type": "PACKAGE",
    "additionalServices": {
        "options": []
    },
    "state": "CREATED"
Otrzymałem etykietę pdf z numerem JJD000030187081000007553609
Nie ma tego numeru w response. Jaką metodą w takim razie mogę ten numer uzyskać?

**Comment by Lukasz-Zurek** [comment]
@drzemik Nie zwracamy nigdzie numeru listu przewozowego. Zwracamy jedynie nasz identyfikator przesyłki.
