### ISSUE TITLE
Błędne ubezpieczenie packeta

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#7181]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

trace-id: 1935c633b6264477

![obraz](https://github.com/allegro/allegro-api/assets/87118074/b169d173-b75d-441f-a41a-d24ef97f5a30)

Api allegro dla metody dostawy packeta zwraca błąd jakoby błędnie zostało przekazane ubezpieczenie. Natomiast w dokumentacji API allegro jest wskazane ,że wartość paczki która odpowiada za ubezpieczenie może przyjmować jedynie PLN

![obraz](https://github.com/allegro/allegro-api/assets/87118074/e8a99057-bd9f-473d-9832-e5f5dd8e64b1)

**Comment by Lukasz-Zurek** [comment]
@Maciej-Wilkosz Wkrótce zaktualizujemy dokumentację, ponieważ wskazana informacja jest nieaktualna.

Przepraszamy za utrudnienia.

Jak tylko to poprawimy, wrócę z informacją.
