### ISSUE TITLE
Blokada sprzedaży proszę o odblokowanie.

### ISSUE THREAD

**Issue by Lukasz-Zurek** [allegro/allegro-api#7184]
### Discussed in https://github.com/allegro/allegro-api/discussions/7182

<div type='discussions-op-text'>

<sup>Originally posted by **applejablko** June  7, 2023</sup>
Blokada sprzedaży proszę o odblokowanie.</div>

**Comment by Lukasz-Zurek** [comment]
@applejablko Zakładka "Discussions" służy do przekazywania sugestii i pomysłów na usprawnienie, dlatego Twój wątek przeniosłem tutaj, natomiast ten w zakładce "Discussions" - usunąłem.

Podaj proszę login do konta na sandboxie, na którym widnieje blokada.

**Comment by applejablko** [comment]
applejablko

**Comment by Lukasz-Zurek** [comment]
@applejablko Zdjąłem blokadę.

**Comment by applejablko** [comment]
dziękuję
