### ISSUE TITLE
Notoryczne blokowanie moich requestów na sandboxie

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#7187]
Notorycznie jest blokowany mój ruch pomimo że nie wysyłam sporej ilości requestów

You have been blocked.
Why this blocking? Something about the behaviour of the browser has caught our attention.

There are various possible explanations for this:
 you are browsing and clicking at a speed much faster than expected of a human being
 something is preventing Javascript from working on your computer
 there is a robot on the same network (IP 77.*.*.*) as you
If something does not work please let us know.
ID: ba059a82-e5b6-d6f4-264b-8b8fd6b9e005

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie. Sprawę przekazałem do weryfikacji, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Wygląda, że prawdopodobnie korzystasz z niestandardowej przeglądarki i/lub z niestandardowymi dodatkami. W przypadku chęci wprowadzania automatyzacji korzystaj z api.allegro.pl.allegrosandbox.pl bezpośrednio, a nie poprzez serwis WWW.

**Comment by DamianKAtomStore** [comment]
Korzystam z wbudowanej przeglądarki postmana i wysyłam request pod ten adres https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize. Błąd dalej występuje

**Comment by MaciejFrackowiak** [comment]
Skorzystaj ze standardowej przeglądarki dostępnej na rynku, wówczas problem nie powinien się pojawić, jeśli Twoje działania nie będą przypominały automatycznego ruchu.

**Comment by DamianKAtomStore** [comment]
Przeglądarka jest na silniku chrome z Postmana. Korzystam z niego do większości API z którymi pracuje i tylko u was jest ten błąd. To trochę dziwne że nie można obsługiwać waszego api przez dedykowany program do tego celu

**Comment by MaciejFrackowiak** [comment]
Postman w głównej mierze służy do wykonywania requestów bezpośrednio pod zasoby API Allegro, a nie generowanie ruchu WWW. Dlatego też sugerujemy korzystanie z alternatywnych rozwiązań, aby zapobiec ponownemu wystąpieniu problemu.
