### ISSUE TITLE
Enpoint GET /payments/refunds

### ISSUE THREAD

**Issue by jakub-marchewka** [allegro/allegro-api#7188]
Dzień dobry,
Pracując z https://developer.allegro.pl/documentation/#operation/getRefundedPayments napotkałem problem z brakiem modelu listy na wzór
https://developer.allegro.pl/documentation/#operation/listThreadsGET gdzie zwracany jest ThreadsList, natomiast GET payments nie posiada takiego odpowiednika, czy w przyszłości jest planowane wprowadzenie podobnego rozwiązania w swaggerze ?

**Comment by MaciejFrackowiak** [comment]
Nie, nie przewidujemy żadnych zmian we wzorze odpowiedzi dla [GET /payments/refunds](https://developer.allegro.pl/documentation/#operation/getRefundedPayments).

**Comment by jakub-marchewka** [comment]
Dziękuję za informacje.
