### ISSUE TITLE
WebApi - brak żadnej informacji o wygaszeniu!?

### ISSUE THREAD

**Issue by GyniO** [allegro/allegro-api#719]
Dlaczego na głównej stronie https://allegro.pl/webapi nie ma żadnej zmianki o wygaszaniu tej usługi? Przypadkiem wpadłem na newsa z drugiej strony https://allegro.pl/webapi/news.php/page,2#news_100617, w połowie pracy dopiero się zorientowałem, że taką zmianę wprowadzacie - przez co pisanie nowej aplikacji o webapi mija się z jakimkolwiek sensem. Może warto powiadomić o tym fakcie, dużym czerwonym komunikatem...

**Comment by PawelTaberski** [comment]
W związku z przesunięciem czasu trwania zasobów w wersji beta termin ulegnie na pewno wydłużeniu. Metody oznaczymy jako deprecated w najbliższym kwartale. Od tego momentu, będziemy odradzać użycia tych metod w nowych rozwiązaniach i mocno zalecać migrację na REST API w istniejących rozwiązaniach. I minimum po pół roku od tego czasu usuniemy te metody. O aktualizacji terminów będziemy informować. Jak tylko oznaczymy te metody jako deprecated będzie to od razu widoczne po przejściu do dokumentacji.

**Comment by jakubmaguza** [comment]
Mimo wszystko sugerowałbym dodanie informacji w aktualnościach, że planujecie te wygasić WebAPI. Pierwszy link w google prowadzi właśnie do WebAPI. Sam zaczynając nowy projekt chciałem użyć WebAPI, ale coś mnie na szczęście podkusiło do poszukania głębiej. Zazwyczaj nowo tworzone projekty trwają dużo dłużej niż pół roku. Skoro już macie informacje o wygaszeniu dobrze by było podać ją osobom wchodzącym na stronę WebAPI.

**Comment by PawelTaberski** [comment]
Dziękujemy za sugestię postaramy się, aby ta informacja była bardziej widoczna.
