### ISSUE TITLE
Błędy w katalogu produktów Allegro ConstraintViolationException.DependencyValidator

### ISSUE THREAD

**Issue by kowalikus** [allegro/allegro-api#7190]
Występuje problem:
 - [ ] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: W katalogu produktów Allegro znajduje się produkt o identyfikatorze e3296915-cd35-4660-a587-70d37f1d1950 pobierając informacje o wartościach atrybutów dla tego produktu otrzymujemy m.in:

* Id atrybutu: 249512, nazwa: Kolor, wartość: czarny, Id wartości: 249512_1647413
* Id atrybutu: 249513, nazwa: Odcień, wartość: granatowy, Id wartości: 249513_1647539

Podczas próby utworzenia oferty otrzymujemy następujący błąd:

`Parametr zależny Odcień (249513) nie może przyjąć wartości [granatowy], gdy parametr Kolor (249512) ma wartości [czarny]. `

**Comment by MaciejFrackowiak** [comment]
Jeżeli napotykasz błąd w produkcie możesz zgłosić sugestię jego zmiany poprzez [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal) lub poprzez stronę WWW - https://allegro.pl/moje-allegro/sprzedaz/produkt/zglos-blad/{productId}.
