### ISSUE TITLE
Questions about default values of commodity parameters

### ISSUE THREAD

**Issue by xcg340122** [allegro/allegro-api#7191]
Hello, I recently encountered a problem with the default value of some parameters. I don't know how the default value of the parameter is provided. I often receive errors similar to: [An incorrect value `inny` has been entered for parameter `Funkcje`] , is there any place where I can check the default values of all parameters in the product
It is better if there is a reference document,thank you

**Comment by MaciejFrackowiak** [comment]
You can retrieve product details by [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct). Also, you can check the whole structure of parameters for the selected category by [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).

**Comment by xcg340122** [comment]
Assuming the parameter name is A, I did not find the A parameter through the [/sale/products/{productId}] API, but through [/sale/categories/{categoryId}/parameters] I can find the required parameter of A, But the [/sale/categories/{categoryId}/parameters] API tells me that A is a required item, and doesn't tell me the default value or demo value, so I can't do it when I encounter a product similar to this situation. provide a valid value

**Comment by xcg340122** [comment]
Can you help solve this problem...

**Comment by MaciejFrackowiak** [comment]
You as a seller should know which value suits the best to selected parameter. In the [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) we return information if the parameter is dictionary one or you can set your own value. Also, there is a flag=true if the parameter is required for the product or false if not.

**Comment by xcg340122** [comment]
> 作为卖家，您应该知道哪个值最适合所选参数。在[GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2)中，如果参数是字典一或者您可以设置自己的值，我们将返回信息。此外，如果产品需要该参数，则有一个 flag=true，否则为 false。

This is just to get the necessary parameters, but what I need is an example of the default value of the parameter, such as the property Kolor, if I pass a value containing the keyword "red", it will tell me that the value does not conform to the content of Kolor

**Comment by MaciejFrackowiak** [comment]
Parameters do not have default values -  every single product has its own parameters, so specified values of the parameters are assigned to the chosen product.

**Comment by xcg340122** [comment]
> Parameters do not have default values - every single product has its own parameters, so specified values of the parameters are assigned to the chosen product.

Then why do I pass in the red word and it will prompt that it does not match?

**Comment by xcg340122** [comment]
> Parameters do not have default values - every single product has its own parameters, so specified values of the parameters are assigned to the chosen product.

The content of the error is probably: An incorrect value `red` has been entered for parameter `Kolor`.

**Comment by MaciejFrackowiak** [comment]
Please, give us an example of data - without it, it is hard to answer.

**Comment by xcg340122** [comment]
> Please, give us an example of data - without it, it is hard to answer.

{
	"productSet": [{
		"product": {
			"category": {
				"id": "110914"
			},
			"parameters": [{
				"id": "248811",
				"valuesIds": ["248811_950468"],
				"values": ["inna (without brand)"]
			}, {
				"id": "249191",
				"valuesIds": ["249191_1120200"],
				"values": ["latarnia"]
			}, {
				"id": "11484",
				"valuesIds": ["11484_131072"],
				"values": ["inny"]
			}, {
				"id": 24169,
				"values": ["inny"]
			}],
			"idType": "GTIN",
			"id": "a0148fdd-0bf8-4ca9-9cdf-3eed30eaf9c2"
		}
	}],
	"stock": {
		"available": "199",
		"unit": "UNIT"
	},
	"location": {
		"countryCode": "HK",
		"province": "Zhejiang",
		"city": "Hangzhou",
		"postCode": "66-400"
	},
	"delivery": {
		"handlingTime": "P3D",
		"shippingRates": {
			"id": "a0853c97-d278-42c4-95ec-4f1ef6e5c904"
		}
	},
	"payments": {
		"invoice": "NO_INVOICE"
	},
	"sellingMode": {
		"format": "BUY_NOW",
		"price": {
			"amount": "35.23",
			"currency": "PLN"
		}
	},
	"description": {
		"sections": [{
			"items": [{
				"type": "TEXT",
				"content": "<p>  <\/p><p>Ten posiadacz \u015bwiecy jest dekoracyjnym i praktycznym dodatkiem do twojego<\/p><p>Wystr\u00f3j sto\u0142u. \u0141atwo doda\u0107 urok i pi\u0119kno swojej przestrzeni \u017cyciowej,<\/p><p>ma\u0142\u017ce\u0144stwo, impreza itp. Doskona\u0142e elementy dekoracyjnerobiny dla stron, wesela,<\/p><p>Kupki okien i kluby hotelowe. Idealny do sypialni, salonu lub biura<\/p><p> dekoracje.<\/p>"
			}]
		}, {
			"items": [{
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/11e638\/700e8c7442b6862b06da785a7138\/1Pc-Dostepny-w-blat-dekoracji-Plaza-morskie-ozdoby-Stan-opakowania-brak-opakowania"
			}, {
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/11940e\/5aa5ee9049e688b0e9ed456ccc16\/1Pc-Dostepny-w-blat-dekoracji-Plaza-morskie-ozdoby-Kolor-inny"
			}]
		}, {
			"items": [{
				"type": "TEXT",
				"content": "<h2>funkcje<\/h2><p><\/p><p> Kolor: niebieski.<\/p><p> Materia\u0142: \u017celazo i plastik.<\/p><p> Rozmiar: 18,50x7,50x7,50 cm\/7.27x2.95x2.95in  ch.<\/p><p> Uwaga: Losowy styl.  <\/p><p> Wykonane z iec\u221eiec Materia\u0142u, trwa\u0142ego do u\u017cycia.<\/p><p> W zestawie z p\u0142ask\u0105 baz\u0105, sta\u0144 na pulpicie. Bezpieczny i przeno\u015bny.<\/p><p> Tworzenie dla Ciebie pi\u0119knej, ciep\u0142ej i romantycznej atmosfery.<\/p><p> Wielkie ozdoby stacjonarnerobietek dla salonu, sypialni, \u0142azienki itp.<\/p><p> Candlesticks\u221e dla Walentynek, rekwizyty \u015blubne, romantyczna kolacja przy \u015bwiecach, co mo\u017ce poprawi\u0107 atmosfer\u0119.<\/p>"
			}, {
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/114c89\/c50442e94e5a80949311208c470f\/1Pc-Dostepny-w-blat-dekoracji-Plaza-morskie-ozdoby"
			}]
		}, {
			"items": [{
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/11ea4d\/aa495c4b46c18e4844118800e8cd\/1Pc-Dostepny-w-blat-dekoracji-Plaza-morskie-ozdoby-Marka-inna"
			}, {
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/11e3f6\/3d4f773f4a5aacdf612a75e204b8\/1Pc-Dostepny-w-blat-dekoracji-Plaza-morskie-ozdoby-Rodzaj-latarnia"
			}]
		}, {
			"items": [{
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/115adb\/7ce5be574646a47a6dd585f7f512"
			}, {
				"type": "TEXT",
				"content": "<h2>Lista pakiet\u00f3w<\/h2><p><\/p><p>1 x wystr\u00f3j latarni morskiej<\/p>"
			}]
		}, {
			"items": [{
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/11339b\/1df2d62a49c095ab24645cee018b"
			}, {
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/1117b0\/afb7db9a4db9ac1d3ace98b13b5a"
			}]
		}]
	}
}

Feedback error: An incorrect value 'inny' has been entered for parameter 'Materiał wykonania'.

**Comment by MaciejFrackowiak** [comment]
You provided the value "inny" for the parameter 24169 "Materiał wykonania" but this parameter is a dictionary one, so you can only choose one of the existing values - you can check them by [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).

**Comment by xcg340122** [comment]
> You provided the value "inny" for the parameter 24169 "Materiał wykonania" but this parameter is a dictionary one, so you can only choose one of the existing values - you can check them by [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).

I have obtained the necessary parameter values through the API, but I am not sure how to select an existing value. I enumerate the information of all parameters in this category:
```
Name:Marka, Type:dictionary, Id:248811, required:1
Name:Rodzaj, Type:dictionary, Id:249191, required:1
Name:Kolor, Type:dictionary, Id:11484, required:1
Name:Materiał wykonania, Type:dictionary, Id:24169, required:1
Name:Szerokość produktu, Type:float, Id:223333, required:0
Name:Wysokość produktu, Type:float, Id:223329, required:0
Name:Kod producenta, Type:string, Id:224017, required:0
Name:Waga produktu z opakowaniem jednostkowym, Type:float, Id:17448, required:0
Name:EAN (GTIN), Type:string, Id:225693, required:0
```

**Comment by MaciejFrackowiak** [comment]
In the response to [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2), you will receive the full list of available values, e.g.:
```
{
            "id": "24169",
            "name": "Materiał wykonania",
            "type": "dictionary",
            "required": true,
            "requiredForProduct": true,
            "requiredIf": null,
            "displayedIf": null,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false,
                "ambiguousValueId": null,
                "dependsOnParameterId": null,
                "requiredDependsOnValueIds": null,
                "displayDependsOnValueIds": null,
                "describesProduct": true,
                "customValuesEnabled": false
            },
            "dictionary": [
                {
                    "id": "24169_1",
                    "value": "ceramika",
                    "dependsOnValueIds": []
                },
                {
                    "id": "24169_2",
                    "value": "drewno",
                    "dependsOnValueIds": []
                },
                {
                    "id": "24169_1645686",
                    "value": "kamień naturalny",
                    "dependsOnValueIds": []
                },
                {
                    "id": "24169_4",
                    "value": "metal",
                    "dependsOnValueIds": []
                },
                {
                    "id": "24169_8",
                    "value": "papier",
                    "dependsOnValueIds": []
                },
                {
                    "id": "24169_16",
                    "value": "szkło",
                    "dependsOnValueIds": []
                },
                {
                    "id": "24169_1769407",
                    "value": "sznurek",
                    "dependsOnValueIds": []
                },
                {
                    "id": "24169_1769406",
                    "value": "tkanina",
                    "dependsOnValueIds": []
                },
                {
                    "id": "24169_32",
                    "value": "tworzywo sztuczne",
                    "dependsOnValueIds": []
                },
                {
                    "id": "24169_64",
                    "value": "wiklina/rattan",
                    "dependsOnValueIds": []
                }
            ],
            "restrictions": {
                "multipleChoices": true
            }
        }
```

**Comment by xcg340122** [comment]
> In the response to [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2), you will receive the full list of available values, e.g.:
> 
> ```
> {
>             "id": "24169",
>             "name": "Materiał wykonania",
>             "type": "dictionary",
>             "required": true,
>             "requiredForProduct": true,
>             "requiredIf": null,
>             "displayedIf": null,
>             "unit": null,
>             "options": {
>                 "variantsAllowed": false,
>                 "variantsEqual": false,
>                 "ambiguousValueId": null,
>                 "dependsOnParameterId": null,
>                 "requiredDependsOnValueIds": null,
>                 "displayDependsOnValueIds": null,
>                 "describesProduct": true,
>                 "customValuesEnabled": false
>             },
>             "dictionary": [
>                 {
>                     "id": "24169_1",
>                     "value": "ceramika",
>                     "dependsOnValueIds": []
>                 },
>                 {
>                     "id": "24169_2",
>                     "value": "drewno",
>                     "dependsOnValueIds": []
>                 },
>                 {
>                     "id": "24169_1645686",
>                     "value": "kamień naturalny",
>                     "dependsOnValueIds": []
>                 },
>                 {
>                     "id": "24169_4",
>                     "value": "metal",
>                     "dependsOnValueIds": []
>                 },
>                 {
>                     "id": "24169_8",
>                     "value": "papier",
>                     "dependsOnValueIds": []
>                 },
>                 {
>                     "id": "24169_16",
>                     "value": "szkło",
>                     "dependsOnValueIds": []
>                 },
>                 {
>                     "id": "24169_1769407",
>                     "value": "sznurek",
>                     "dependsOnValueIds": []
>                 },
>                 {
>                     "id": "24169_1769406",
>                     "value": "tkanina",
>                     "dependsOnValueIds": []
>                 },
>                 {
>                     "id": "24169_32",
>                     "value": "tworzywo sztuczne",
>                     "dependsOnValueIds": []
>                 },
>                 {
>                     "id": "24169_64",
>                     "value": "wiklina/rattan",
>                     "dependsOnValueIds": []
>                 }
>             ],
>             "restrictions": {
>                 "multipleChoices": true
>             }
>         }
> ```

```json

{
	"productSet": [{
		"product": {
			"category": {
				"id": "67523"
			},
			"parameters": [{
				"id": "248135",
				"valuesIds": ["248135_859076"],
				"values": ["Inna"]
			}, {
				"id": "237206",
				"values": ["3113220167111"]
			}, {
				"id": "224017",
				"values": ["3113220167111"]
			}],
			"idType": "GTIN",
			"id": "ed61de6b-dcde-41a1-8790-11d3c0fe6d9b"
		}
	}],
	"stock": {
		"available": "199",
		"unit": "UNIT"
	},
	"location": {
		"countryCode": "HK",
		"province": "Zhejiang",
		"city": "Hangzhou",
		"postCode": "66-400"
	},
	"delivery": {
		"handlingTime": "P3D",
		"shippingRates": {
			"id": "a0853c97-d278-42c4-95ec-4f1ef6e5c904"
		}
	},
	"parameters": [{
		"id": "11323",
		"valuesIds": ["11323_1"],
		"values": ["Nowy"]
	}],
	"payments": {
		"invoice": "NO_INVOICE"
	},
	"sellingMode": {
		"format": "BUY_NOW",
		"price": {
			"amount": "35.13",
			"currency": "PLN"
		}
	},
	"description": {
		"sections": [{
			"items": [{
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/111802\/a7e897d14a29bd55110da1818c3a\/5-3K-Pas-sygnalu-tetna-Czujnik-tetna-Pasek-na-Marka-Inna"
			}, {
				"type": "TEXT",
				"content": "<h2>Funkcja:<\/h2><p>1. Dotyczy modeli: kompatybilny z inteligentnymi zegarkami Polar i innymi aplikacjami. Mo\u017ce \u0142\u0105czy\u0107 si\u0119 z wieloma urz\u0105dzeniami jednocze\u015bnie. Obs\u0142uga 2 jednoczesnych po\u0142\u0105cze\u0144 Bluetooth.<\/p><p>2. Punkty silikonowe: dzi\u0119ki \u0142atwym w u\u017cyciu klamrom i silikonowym punktom, pasek na klatk\u0119 piersiow\u0105 jest wygodny i nie inwazyjny, utrzymuj\u0105c go na miejscu, gdy jeste\u015b w ruchu.<\/p><p>3. Zakres zastosowa\u0144: ten pasek na klatk\u0119 piersiow\u0105 do monitorowania t\u0119tna mo\u017cna nosi\u0107 podczas wios\u0142owania, jazdy na rowerze, biegania, treningu w pomieszczeniach lub p\u0142ywania.<\/p><p>4. Powi\u0105zane parametry: Cz\u0119stotliwo\u015b\u0107 wynosi 5.3K. Odleg\u0142o\u015b\u0107 wynosi 80\u2011100cm. Bateria to ogniwo guzikowe CR2032 150 mAh (w zestawie). Temperatura pracy wynosi od -10 do 40 \u00b0C.<\/p><p>5. Lekki: ten pasek na klatk\u0119 piersiow\u0105 monitora t\u0119tna jest lekki i bezstresowy w noszeniu. Mo\u017ce realizowa\u0107 monitorowanie t\u0119tna w czasie rzeczywistym.<\/p>"
			}]
		}, {
			"items": [{
				"type": "TEXT",
				"content": "<h2>Specyfikacja:<\/h2><ul><li>Typ artyku\u0142u: Pas nadajnika t\u0119tna<\/li><li>Materia\u0142: ABS, silikon<\/li><li>Waga brutto: 54g\/1,9 uncji<\/li><li>Cz\u0119stotliwo\u015b\u0107: 5,3 K<\/li><li>Odleg\u0142o\u015b\u0107: 80-100 cm<\/li><li>Bateria: dolne ogniwo CR2032 150 mAh (w zestawie)<\/li><li>Temperatura pracy: -10 do 40 \u00b0 C<\/li><li>Wilgotno\u015b\u0107 pracy: \u226485% RH<\/li><\/ul>"
			}, {
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/1105b5\/62b6678e416fa8a264f64dee791d"
			}]
		}, {
			"items": [{
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/112748\/5e26a5cd4dbfa2ff2e333e0b2147"
			}, {
				"type": "TEXT",
				"content": "<h2>Lista pakiet\u00f3w:<\/h2><ul><li>1 x pasek na klatk\u0119 piersiow\u0105 do pomiaru t\u0119tna<\/li><\/ul>"
			}]
		}]
	}
}
```

Error:The specified product exists. The specified parameter `Marka` with the value `Inna(248135_859076)` does not match the product parameter `bez marki(248135_1728479)`

**Comment by xcg340122** [comment]
There are still some problems. Sometimes the press conference prompts: Invalid HTML subset, but I have replaced the & symbol in the Text part of the description with &amp; and still prompts this error

**Comment by MaciejFrackowiak** [comment]
Error "The specified product exists. The specified parameter Marka with the value Inna(248135_859076) does not match the product parameter bez marki(248135_1728479)" means that the value which you used in the request is not the same as the value in the specified product. When you call GET /sale/products/{ed61de6b-dcde-41a1-8790-11d3c0fe6d9b}, you will receive product details:
```
"parameters": [
        {
            "id": "248135",
            "name": "Marka",
            "valuesLabels": [
                "bez marki"
            ],
            "valuesIds": [
                "248135_1728479"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": true
            }
        }
```
When you list a new offer you can use only data which describe the product - "bez marki" ("248135_1728479").

The second error - "Invalid HTML subset" means that you used an invalid HTML -  [here](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#own-images-and-description) you will find the whole list of available tags.
