### ISSUE TITLE
How to activate additional marketplace on offers with API ?

### ISSUE THREAD

**Issue by lwillems** [allegro/allegro-api#7193]
Hello

My dev account in sandbox is : obtao

I am migrating my app from legacy draft offers to product-offers and would like to include allegro-cz to my offers following this [documentation.](https://developer.allegro.pl/tutorials/wystawianie-i-zarzadzanie-oferta-w-serwisach-zagranicznych-wwzjP4M8gTZ#jak-wyswietlic-oferte-w-serwisie-dodatkowym)
I have tried to add additional marketplace in my POST /sale/product-offers : 

```json
    "publication": {
        "marketplaces": {
            "additional": [
                {
                    "id": "allegro-cz"
                }
            ]
        },
        "republish": true
    }
```

Got HTTP/1.1 422 Unprocessable Entity
```json
{
  "errors": [
    {
      "code": "ConstraintViolationException.ForeignMarketplacesWithProductOnly",
      "message": "Platforms other than allegro.pl only support offers with a product linked.",
      "details": "ConstraintViolationException.ForeignMarketplacesWithProductOnly",
      "path": "null",
      "userMessage": "Platforms other than allegro.pl only support offers with a product linked."
    }
  ]
}
```

Without this extra node offer is created and published.
Did i missed something ? how am i supposed to process to included cz in my offers ?

Thx for you help
Regards

```

**Comment by Lukasz-Zurek** [comment]
Please send me a trace-id of your request. I will verify it closely.

**Comment by lwillems** [comment]
Hello @Lukasz-Zurek 

trace-id: 14717e5bb0e08077

Thx

**Comment by Lukasz-Zurek** [comment]
@lwillems This offer does not meet the eligibility criteria on allegro.cz (There is no price in CZK). This is why it cannot be linked to the product and we return that kind of error message. The criteria/offer conditions you will find right [here](https://developer.allegro.pl/tutorials/listing-and-managing-offers-on-foreign-marketplaces-7GndGjeAATn#what-conditions-must-the-offer-meet-so-we-can-display-it-in-additional-marketplaces).

**Comment by lwillems** [comment]
@Lukasz-Zurek 

Where am i supposed to add CZK price ?
I have tried to add :

```json
    "additionalMarketplaces": {
        "allegro-cz": {
            "selling_mode": {
                "format": "BUY_NOW",
                "price": {
                    "amount": 3000,
                    "currency": "CZK"
                }
            }
        }
    },
```

But still got a 422 error.

Regards

**Comment by Lukasz-Zurek** [comment]
You did use shipping-rates which include only one delivery method: d9617aae-9a79-11e5-8994-feff819cdc9f - "France", but the offer should have at least one delivery method available for the allegro-cz marketplace allegro-cz:

- [Allegro DHL Courier Czechia](https://allegro.pl/dla-sprzedajacych/allegro-kurier-dhl-z-wysylka-z-polski-za-granice-informacje-dla-sprzedajacych-eKj4YWnWAFB)
- [Allegro DPD Courier Czechia](https://allegro.pl/dla-sprzedajacych/allegro-kurier-dpd-z-wysylka-z-polski-za-granice-informacje-dla-sprzedajacych-aMR4dYrK6i3)
- [Allegro Dispatch from Poland to Czechia — Packeta Pick-up Point](https://allegro.pl/dla-sprzedajacych/allegro-packeta-z-wysylka-z-polski-do-czech-informacje-dla-sprzedajacych-wwzG4RPjWuw)
- [Allegro Dispatch from Poland to Czechia — Packeta Parcel Lockers](https://allegro.pl/dla-sprzedajacych/allegro-packeta-z-wysylka-z-polski-do-czech-informacje-dla-sprzedajacych-wwzG4RPjWuw)
- or Shipping from Poland abroad - Czechia (own agreement).

So this is another thing which I have just found.

**Comment by lwillems** [comment]
@Lukasz-Zurek 

From what i see i am using this delivery id : 07d7684d-d44b-4b1f-9c15-19d91d68f69d
I have added CZ support but still got the 422
![Capture d’écran du 2023-06-09 15-24-59](https://github.com/allegro/allegro-api/assets/6826563/e2f53b12-6090-4481-b40d-dfd4ad3a108f)

**Comment by lwillems** [comment]
any news @Lukasz-Zurek

**Comment by Lukasz-Zurek** [comment]
@lwillems I have reported this specific case to another department. As soon as I receive any update, I will let you know in this thread. 

Please be patient. Thank you.

**Comment by lwillems** [comment]
please do not close this ticket automatically

**Comment by Lukasz-Zurek** [comment]
@lwillems It will be closed automatically, but it does not mean that we do not work on this issue. It is still in progress and as soon as I receive any details, I will let you know in this thread.
