### ISSUE TITLE
Zamówienie nie pobrało się do Idosell

### ISSUE THREAD

**Issue by suczarczyk** [allegro/allegro-api#7194]
Dzień dobry, z jakiego powodu do Idosell nie zostało pobrane zamówienie 10321930-0444-11ee-903f-e781fd192d2b?

**Comment by Lukasz-Zurek** [comment]
W tej sprawie skontaktuj się z supportem Idosell. Wskazane zamówienie prawidłowo zwracamy w naszym API.
