### ISSUE TITLE
403 Forbidden error

### ISSUE THREAD

**Issue by vyvledav** [allegro/allegro-api#7195]
Hello,
for user CGDemo in sandbox we have implemented [Authorization Code flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow). We are able to obtain valid token which is not expired and contains required scope:
```
{
  "exp": 1686342963,
  "scope": [
    "allegro:api:orders:read",
    "allegro:api:payments:write",
    "allegro:api:sale:offers:write",
    "allegro:api:sale:settings:write",
    "allegro:api:ratings",
    "allegro:api:billing:read",
    "allegro:api:sale:settings:read",
    "allegro:api:disputes",
    "allegro:api:payments:read",
    "allegro:api:sale:offers:read",
    "allegro:api:orders:write"
  ],
  "allegro_api": true
}
```

Yet, every other request to resource (eg. /order/events) returns 403 (Forbidden) error:

```
GET /order/events HTTP/1.1
Authorization: Bearer {we send token here}
Host: allegro.pl.allegrosandbox.pl
accept: application/vnd.allegro.public.v1+json
```

What am I missing please?

**Comment by Lukasz-Zurek** [comment]
As I don't have any details (I've already checked your token and it seems to be ok), please send me full request and response in cURL along with trace-id via [our contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Please add GitHub #7195 in your message. Thank you!

**Comment by Lukasz-Zurek** [comment]
@vyvledav I've just received your message with request and response. I see that you are trying to call:

`GET https://allegro.pl.allegrosandbox.pl/order/events`

(well, you've sent it in the previous message, but I haven't been sure about it).

You should call:

`GET https://api.allegro.pl.allegrosandbox.pl/order/events`

The resource address is always: https://api.allegro.pl.allegrosandbox.pl/

**Comment by vyvledav** [comment]
I see. The former url is used just for the authorisation. 
Now it seems to work as expected. Thank you!
