### ISSUE TITLE
błąd cechy przy wystawieniu produktu

### ISSUE THREAD

**Issue by lukasz1991a** [allegro/allegro-api#7196]
Chciałbym wystawić produkt w środowisku produkcyjnym poprzez api na bazie "Dławnica kablowa Ergom E03DK-01030100901"
Mam problem z parametrem Liczba sztuk w ofercie.
Dam puste dostaję błąd
Missing required parameters: 248489 - Uzupełnij parametry obowiązkowe: Liczba sztuk w ofercie.
dam 1 dostaję błąd
Unprocessable Entity - The definitions of the parameter `248489:Liczba sztuk w ofercie` were incorrectly specified as a parameter in section `product`.
Wystawiłem ten produkt poprzez formularz na stronie allegro.pl i produkt został dodany z ilością 1.

**Comment by Lukasz-Zurek** [comment]
Liczba sztuk w ofercie (248489) to parametr ofertowy, dlatego informacje te musisz przekazać poza szczegółami produktu (w sekcji **parameters**). Otrzymałeś wspomniany błąd, ponieważ próbowałeś zamieścić te informacje w Parametry produktowe w części opisującej produkt (**productSet.product.parameters**). Więcej informacji o parametrach ofertowych znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#parametry-ofertowe). Tam też znajdziesz różnicę pomiędzy parametrem ofertowym a produktowym.

**Comment by lukasz1991a** [comment]
super, dziękuję za pomoc. Już to uwzględniłem :)
