### ISSUE TITLE
Systemowa prośba o weryfikacje konta na aktywowanym koncie

### ISSUE THREAD

**Issue by krwicher** [allegro/allegro-api#7197]
Klient chce podpiąć moje rozwiązanie do swojego konta allegro.

Żeby to zrobić wchodzi na stronę https://apps.developer.allegro.pl/, gdzie powinien móc dodać konfigurację (jest użytkownikiem zweryfikowanym, posiadającym swoje aukcje).

Niestety pojawia się mu ekran, który oczekuje od niego weryfikacji konta. Według informacji jakie posiadam, konto klienta jest już w pełni aktywowane. Konto ma już duży staż więc jest możliwość, że z tego powodu nie ma na nim ustawień, które powinny istnieć.

Proszę o pomoc.
Login klienta: www_vedion_pl

**Comment by Lukasz-Zurek** [comment]
Na tym koncie brakuje aktywnego dwustopniowego logowania, które Klient może włączyć [tutaj](https://allegro.pl/moje-allegro/moje-konto/dwustopniowe-logowanie). Jest to wymagane do tego, aby móc zarejestrować aplikację na wskazanej przez Ciebie stronie.

**Comment by krwicher** [comment]
@Lukasz-Zurek Rozumiem, że zrobienie weryfikującego przelewu jest niewystarczające i będzie trzeba włączyć dwustopniowe logowanie?
Czy może jednak zastąpi ono weryfikacje konta za pomoca dwustopniowego logowania?

**Comment by Lukasz-Zurek** [comment]
@krwicher To konto produkcyjne jest w pełni aktywne, więc aby móc zarejestrować na nim nową aplikację - konieczne jest włączenie dwustopniowego logowania, które na koncie nie jest włączone. Jest to drugi wymóg, oprócz aktywacji.
