### ISSUE TITLE
Pole z zakresem danych - Zakres regulacji wysokości koszenia (cm)

### ISSUE THREAD

**Issue by krychu90** [allegro/allegro-api#72]
Witam,
dla kategorii:
_Dom i zdrowie - Dom i Ogród - Ogród - Narzędzia ogrodnicze - Kosiarki - Kosiarki spalinowe_

W panelu allegro jest pole _Zakres regulacji wysokości koszenia_ które jest podzielone na dwa:
![formularz wystawiania](https://user-images.githubusercontent.com/11661487/37459132-73f736c8-2847-11e8-844a-44369ecef468.png)

Natomiast API zwraca jako jedno pole z typem wprowadzania wartości float.

Jak podać wartość dla tego pola przez api?

Metoda _doGetSellFormFieldsForCategory_ zwraca te pole w postaci:
`
[33633] => stdClass Object
                (
                    [sellFormId] => 33633
                    [sellFormTitle] => Zakres regulacji wysokości koszenia (cm)
                    [sellFormCat] => 85212
                    [sellFormType] => 3
                    [sellFormResType] => 3
                    [sellFormDefValue] => 0
                    [sellFormOpt] => 8
                    [sellFormPos] => 5
                    [sellFormLength] => 4
                    [sellMinValue] => 0.00
                    [sellMaxValue] => 1000.00
                    [sellFormDesc] => 
                    [sellFormOptsValues] => 
                    [sellFormFieldDesc] => Ogród > Kosiarki
                    [sellFormParamId] => 211966
                    [sellFormParamValues] => 
                    [sellFormParentId] => 0
                    [sellFormParentValue] => 0
                    [sellFormUnit] => 
                    [sellFormOptions] => 8
                )
`

Pozdrawiam

**Comment by LukaszKorek** [comment]
Witaj, możesz podać zarówno wartość minimalną jak i maksymalną. Zgodnie z dokumentacją:

fvalueRangeFloat | RangeFloatValueStruct 
Wartość pola dla liczb rzeczywistych typu zakresowego. 
        1. fvalueRangeFloatMin | float 
            Wartość początkowa zakresu wartości parametru. 
        2. fvalueRangeFloatMax | float 
            Wartość końcowa zakresu wartości parametru. Przykład:

<ser:fid>33630</ser:fid>
               <ser:fvalueRangeFloat>
                  <ser:fvalueRangeFloatMin>0.2</ser:fvalueRangeFloatMin>
                  <ser:fvalueRangeFloatMax>1.8</ser:fvalueRangeFloatMax>
                  </ser:fvalueRangeFloat>
