### ISSUE TITLE
[Sandbox] Brak maila aktywacyjnego

### ISSUE THREAD

**Issue by docc46** [allegro/allegro-api#720]
Dzień dobry, 

Jak długo trzeba oczekiwać na mail aktywacyjny po zarejestrowaniu nowego użytkownika w sandboxie? Przez godzinę od rejestracji nadal go nie otrzymałem. 

Proszę o przesłanie maila z linkiem aktywacyjnym lub ręczną aktywację konta docc46@gmail.com

**Comment by PawelTaberski** [comment]
Sprawdziłem i występuje jakiś problem z mailami odnośnie rejestracji konta. Sprawę przekazałem do odpowiedniego zespołu. Proszę o cierpliwość.
