### ISSUE TITLE
billing/billing-entries - Internal Server Error

### ISSUE THREAD

**Issue by coolpina** [allegro/allegro-api#7200]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Próbuję uzyskać odpowiedź na zapytanie z API kierowane przez billing/billing-entries
Niezależnie od treści - zawsze zwracany jest błąd Internal Server Error. 
Inne zapytania, np. o listę kategorii kończą się powodzeniem. 

{
  errors: [
    {
      code: 'INTERNAL_SERVER_ERROR',
      message: 'Internal server error.',
      details: null,
      path: null,
      userMessage: 'Internal server error. Try again in a few minutes.'
    }
  ]
}

**Comment by Lukasz-Zurek** [comment]
Abym mógł to dokładnie sprawdzić, prześlij proszę trace-id.

**Comment by coolpina** [comment]
Problem niezmiennie występuje, przykładowe trade-id: 3ea9d9f242880dd3, c3639c679844189d.

**Comment by Lukasz-Zurek** [comment]
Wszystko wskazuje na to, że korzystasz z tokena uzyskanego w toku autoryzacji typu [client_credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow), która nie posiada kontekstu użytkownika (czyli możesz jedynie skorzystać z zasobów z ogólnodostępnymi informacjami, np. uzyskać listę kategorii i parametrów, etc.), dlatego otrzymujesz błąd. Wygeneruj proszę token w ramach autoryzacji code lub device. Informacje znajdziesz w naszym [poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR).

Jednakże błąd, który Ci zwróciliśmy, może wprowadzać w błąd i te kwestie wyjaśniam z odpowiednim zespołem.

**Comment by coolpina** [comment]
Dzięki wielkie za odpowiedź, teraz to jest jakiś kierunek. Ten błąd faktycznie wprowadził mnie w ślepy zaułek, nie mialem pomysłu żeby szukać błędu po swojej stronie bo myślałem po prostu że serwer padł.

**Comment by Lukasz-Zurek** [comment]
@coolpina Przepraszamy za te utrudnienia. Zarówno komunikat, jak i kod błędu wprowadzają niestety w błąd. Zgłosiłem to do zespołu odpowiedzialnego za rozliczenia.

**Comment by Lukasz-Zurek** [comment]
@coolpina Poprawiliśmy kod odpowiedzi, który zwracany jest w tego typu przypadkach. Raz jeszcze przepraszamy za zaistniałe utrudnienia.
