### ISSUE TITLE
Brak dostępu do ofert allegro

### ISSUE THREAD

**Issue by ZakuroPL** [allegro/allegro-api#7201]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Mam problem z requestem dla: "/sale/product-offers/13236206404"
Aplikacja ma dostęp do allegro:api:sale:offers:read.
Jestem w stanie pobierać zwroty allegro, zamówienia. Jedynie nie mogę pobrać ofert.
Taki sam rezultat mam gdy używam '/sale/offers/{offerId}
Dodam, że identyczny kod działa na innym sklepie allegro

trace-id: 723ca1a49d8f3c21
Response 403
{'errors': [{'code': 'AccessDenied', 'message': 'Access is denied', 'details': None, 'path': None, 'userMessage': 'No access to the specified resource.'}]}

          'Authorization': 'Bearer {_access_token}'
          'Accept': "application/vnd.allegro.public.v1+json",
          'Content-Type': "application/vnd.allegro.public.v1+json"

**Comment by Lukasz-Zurek** [comment]
Błąd zwróciliśmy dlatego, ponieważ informacje o ofercie próbowałeś uzyskać za pośrednictwem tokena, który nie posiada wspomnianego scope'a. Wymagany tutaj scope: _allegro:api:sale:offers:read_, w ustawieniach aplikacji, dodałeś faktycznie 10 czerwca, ok 10:04, ale konieczne jest jeszcze  powtórzenie procesu autoryzacji, od początku, tak, aby token zawierał już wszystkie scope'y, włącznie z nowym _allegro:api:sale:offers:read_.

**Comment by ZakuroPL** [comment]
> Błąd zwróciliśmy dlatego, ponieważ informacje o ofercie próbowałeś uzyskać za pośrednictwem tokena, który nie posiada wspomnianego scope'a. Wymagany tutaj scope: _allegro:api:sale:offers:read_, w ustawieniach aplikacji, dodałeś faktycznie 10 czerwca, ok 10:04, ale konieczne jest jeszcze powtórzenie procesu autoryzacji, od początku, tak, aby token zawierał już wszystkie scope'y, włącznie z nowym _allegro:api:sale:offers:read_.

Wielkie dzięki Łukaszu. Takie proste, a jednak trudne. Faktycznie po wygenerowaniu nowego zestawu kluczy po autoryzacji wszystko działa poprawnie. Muszę zapamiętać na przyszłość.
