### ISSUE TITLE
Odblokowanie sprzedaży na Sandboxie

### ISSUE THREAD

**Issue by Slpw20** [allegro/allegro-api#7203]
Dzień dobry,

uprzejmie prosiłbym o odblokowanie sprzedaży na Sandboxie, na kontach:

- 44348630 (blokada z powodu rozliczeń)
- 44318844 (weryfikacja firmy)
- 44322784 (weryfikacja firmy)

**Comment by MartaNowaczyk** [comment]
Dzień dobry, blokada zdjęta z konta 44348630, a pozostałe dwa zweryfikowane - sprawdź proszę czy wszystko ok, bo podczas procesu weryfikacji były komplikacje.

**Comment by Slpw20** [comment]
Konto 44322784 nadal nie zostało zweryfikowane

**Comment by Lukasz-Zurek** [comment]
@Slpw20 Aktywowałem.

**Comment by Slpw20** [comment]
Wszystko jest już ok. Bardzo dziękuję :)
