### ISSUE TITLE
Czy request /sale/badges zwraca pole publication->to różne od null?

### ISSUE THREAD

**Issue by michalmicpaw** [allegro/allegro-api#7204]
Dzień dobry.

Czy request **/sale/badges** zwraca czasem w polu **publiation->to** wartość inną niż **null**? Czy po zakończeniu kampanii widać czas jej wygaśnięcia i czy można zobaczyć **historię** badgów, dla tej samej oferty? Czy po ponownym uruchomieniu badga, stare wartości w tym requeście dla tej oferty są nadpisywane nowymi, czy istnieje kilka rekordów dla tej samej oferty i można dzięki temu prześledzić historię promocji?

Dziękuję
M.

**Comment by MartaNowaczyk** [comment]
> Czy request /sale/badges zwraca czasem w polu publiation->to wartość inną niż null?

Zwraca wartość inną niż null dla `type` "WITHIN" i "UNTIL"

> Czy po zakończeniu kampanii widać czas jej wygaśnięcia i czy można zobaczyć historię badgów, dla tej samej oferty?

Czasu wygaśnięcia nie ma, jest tylko status. Historię zobaczysz, gdy skorzystasz z [GET /sale/badge-applications](https://developer.allegro.pl/documentation/#operation/badgeApplications_get_all) dla konkretnego `offer.id`.

> Czy po ponownym uruchomieniu badga, stare wartości w tym requeście dla tej oferty są nadpisywane nowymi, czy istnieje kilka rekordów dla tej samej oferty i można dzięki temu prześledzić historię promocji?

Wartości są nadpisywane i podczas dodawania oznaczeń dostaniesz aktualne dane kampanii. Tutaj tak jak wyżej można pobrać wszystkie zgłoszenia [GET /sale/badge-applications](https://developer.allegro.pl/documentation/#operation/badgeApplications_get_all), również dla konkretnego `offer.id`, także jest taka możliwość.

**Comment by michalmicpaw** [comment]
Czy na **SandBox** można pobierać **historię Badgów**? Nie wiem czy robię coś źle, ale zapytanie zwraca pustą tablicę.

**sale/badge-applications**?campaign.id=SUBSIDY&offer.id=7705618541&offset=0&limit=1000

Czy coś robię źle? Ta sama konfiguracja aplikacji poprawnie pobiera Badge spod **sale/badges**. Raczej wykluczam błąd w naszym kodzie.

Proszę o odpowiedź.

Pozdrawiam
M

**Comment by MartaNowaczyk** [comment]
odp. w #7213
