### ISSUE TITLE
Wysyłam z Allegro - etykiety DHL

### ISSUE THREAD

**Issue by Wojtu204** [allegro/allegro-api#7205]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X] inny / other

:beetle: **Opis / Description**
Problem dotyczy generowania etykiety przez https://api.allegro.pl/parcel-management/parcels/label
Dla przesyłki wygenerowanej przez Wysyłam z Allegr dla przewoźnika DHL:
- żądanie wysłane na środowisku developerskim musi mieć w nagłówku Accept: text/plain i zwraca etykiete w ZPL
- żądanie wysłane na środowisku produkcyjnym musi mieć w nagłówku Accept: application/pdf i zwraca etykietę w pdf
Inna kombinacja powoduje odrzucenie żądania z błędem:
{"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept' request header","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji"}]}
Przykłady trace id z produkcji: 4564644e123a81f4

Powyższe powoduje błędy we wdrożeniu na produkcji - obecnie przewidujemy wyłącznie obsługę ZPL, która działała poprawnie na środowisku developerskim. W związku z powyższym proszę o włączenie obsługi ZPL i zwrot etykiet DHL w ZPL na środowisku produkcyjnym.
Dodatkowe info: obsługa etykiet w ZPL działa poprawnie na produkcji dla paczek zgłoszonych przez Wysyłam z Allegro dla przewoźnika DPD.

**Comment by MartaNowaczyk** [comment]
Czy to na pewno prawidłowy trace-id? Dla tego przykładu widzę w logach problem z tokenem, a nie ten błąd, który wskazujesz. Pamiętaj też, że `pageFormat` podajesz tylko dla `application/pdf`.

**Comment by Wojtu204** [comment]
Przesyłam aktualny: d2d6fd221ce5c914
Odświeżony token i w requeście usunąłem pageFormat.
Co ciekawe, pageFormat dla text/plain działa poprawnie dla etykiety dla DPD.

**Comment by MartaNowaczyk** [comment]
Nie, brak wartości nie oznacza, że będzie PDF. W ustawieniach tego konta na allegro jest wybrany domyślny format - PDF, żeby był ZPL, to albo trzeba tam zmienić, albo określić przy tworzeniu paczki.

**Comment by Wojtu204** [comment]
Dziękuję za informacje, temat wyjaśniony.
