### ISSUE TITLE
Pomóc przy rejestracji

### ISSUE THREAD

**Issue by Veronika1987** [allegro/allegro-api#7207]

**Comment by Veronika1987** [comment]
Dzień dobry, Czy mógłby Pan/Mogłaby Pani pomóc odpowiedzieć na kilka pytań?

Jak uzyskać kody autoryzacji API? Jeśli to możliwe, proszę o rzeczywisty przykład żądania, aby uzyskać nasze dane, nie z dokumentacji.
Które polecenie API można użyć do zmiany ceny produktu? Jeśli to możliwe, proszę o rzeczywisty przykład żądania, aby uzyskać nasze dane, nie z dokumentacji.
Które polecenie API można użyć do zmiany ilości produktu? Jeśli to możliwe, proszę o rzeczywisty przykład żądania, aby uzyskać nasze dane, nie z dokumentacji.
Czy jest możliwe zmiana zarówno ilości, jak i ceny produktu za pomocą jednego polecenia API? Jeśli to możliwe, proszę o rzeczywisty przykład żądania, aby uzyskać nasze dane, nie z dokumentacji.

Możliwe, że Państwo będą mogli przesłać zapytania zapisane w Postmanie.

**Comment by MartaNowaczyk** [comment]
Dzień dobry, wszelkie przykłady znajdziesz na naszej stronie https://developer.allegro.pl/

1. Jak uzyskać kody autoryzacji API?  - [Uwierzytelnianie i autoryzacja](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR)
2. Które polecenie API można użyć do zmiany ceny produktu? - [Edycja pól oferty](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pol-oferty) lub [Edycja wielu ofert jednocześnie](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-wielu-ofert-jednoczesnie) np.
```
curl -X PATCH
  ‘https://api.allegro.pl/sale/product-offers/{offerId}’
  -H 'Authorization: Bearer {token}'
  -H 'Accept: application/vnd.allegro.public.v1+json'
  -H 'Content-Type: application/vnd.allegro.public.v1+json'
  -d ’{
    "sellingMode": {
        "price": {
            "amount": 500,
            "currency": "PLN"
        }
    }
}'
```
3. Które polecenie API można użyć do zmiany ilości produktu? - [Edycja pól oferty](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pol-oferty) lub [Edycja wielu ofert jednocześnie](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-wielu-ofert-jednoczesnie) np.
```
curl -X PATCH
  ‘https://api.allegro.pl/sale/product-offers/{offerId}’
  -H 'Authorization: Bearer {token}'
  -H 'Accept: application/vnd.allegro.public.v1+json'
  -H 'Content-Type: application/vnd.allegro.public.v1+json'
  -d ’{
    "stock": {
        "available": 10,
        "unit": "UNIT"
    }
}'
```
4. Czy jest możliwe zmiana zarówno ilości, jak i ceny produktu za pomocą jednego polecenia API? [Edycja pól oferty](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pol-oferty) np.
```
curl -X PATCH
  ‘https://api.allegro.pl/sale/product-offers/{offerId}’
  -H 'Authorization: Bearer {token}'
  -H 'Accept: application/vnd.allegro.public.v1+json'
  -H 'Content-Type: application/vnd.allegro.public.v1+json'
  -d ’{
    "sellingMode": {
        "price": {
            "amount": 500,
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 10,
        "unit": "UNIT"
    }
}'
```

**Comment by Veronika1987** [comment]
Dzień dobry,

Pragniemy wyrazić naszą głęboką wdzięczność za wsparcie, jakie nam Państwo udzielacie. Bardzo liczymy na Państwa pomoc i współpracę w następującej kwestii.

Bardzo prosimy o przesłanie gotowego żądania API do uzyskania tokena z już gotowymi naszymi danymi autoryzacji, które są przedstawione poniżej. Chcielibyśmy skopiować i wkleić ten gotowy request do naszego produktu programistycznego i sprawdzić jego działanie w programie "Postman".

Otrzymaliśmy parametry autoryzacji:

CLIENT ID
60353a7c8bcf42b48904a7d1500ec7e2
CLIENT SECRET
HIDE
GMUYeR5Ihlc2MlUvlF5eEcT76I3M5a9myaHlNz7NL9wqpCwq9HkAoTxKUbT9­DD6k
APPLICATION SCOPES
Offers management
allegro:api:sale:offers:read
View offers information
allegro:api:sale:offers:write
Create, change, merge and close offers
Sales settings
allegro:api:sale:settings:read
View sales settings
allegro:api:sale:settings:write
Manage sales settings
Orders and after sale services
allegro:api:orders:read
View orders information
allegro:api:orders:write
Manage orders
allegro:api:ratings
Manage ratings and comments
allegro:api:disputes
Manage disputes

Z góry dziękujemy za Państwa pomoc i cenne wsparcie.

Z poważaniem,  zespoł Velotrade.
________________________________
От: MartaNowaczyk ***@***.***>
Отправлено: 12 июня 2023 г. 12:50
Кому: allegro/allegro-api ***@***.***>
Копия: Вероника Владимировна Царенко ***@***.***>; Author ***@***.***>
Тема: Re: [allegro/allegro-api] Pomóc przy rejestracji (Issue #7207)


Dzień dobry, wszelkie przykłady znajdziesz na naszej stronie https://developer.allegro.pl/

  1.  Jak uzyskać kody autoryzacji API? - Uwierzytelnianie i autoryzacja<https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR>
  2.  Które polecenie API można użyć do zmiany ceny produktu? - Edycja pól oferty<https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pol-oferty> lub Edycja wielu ofert jednocześnie<https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-wielu-ofert-jednoczesnie> np.

curl -X PATCH
  ‘https://api.allegro.pl/sale/product-offers/{offerId}’
  -H 'Authorization: Bearer {token}'
  -H 'Accept: application/vnd.allegro.public.v1+json'
  -H 'Content-Type: application/vnd.allegro.public.v1+json'
  -d ’{
    "sellingMode": {
        "price": {
            "amount": 500,
            "currency": "PLN"
        }
    }
}'


  1.  Które polecenie API można użyć do zmiany ilości produktu? - Edycja pól oferty<https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pol-oferty> lub Edycja wielu ofert jednocześnie<https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-wielu-ofert-jednoczesnie> np.

curl -X PATCH
  ‘https://api.allegro.pl/sale/product-offers/{offerId}’
  -H 'Authorization: Bearer {token}'
  -H 'Accept: application/vnd.allegro.public.v1+json'
  -H 'Content-Type: application/vnd.allegro.public.v1+json'
  -d ’{
    "stock": {
        "available": 10,
        "unit": "UNIT"
    }
}'


  1.  Czy jest możliwe zmiana zarówno ilości, jak i ceny produktu za pomocą jednego polecenia API? Edycja pól oferty<https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pol-oferty> np.

curl -X PATCH
  ‘https://api.allegro.pl/sale/product-offers/{offerId}’
  -H 'Authorization: Bearer {token}'
  -H 'Accept: application/vnd.allegro.public.v1+json'
  -H 'Content-Type: application/vnd.allegro.public.v1+json'
  -d ’{
    "sellingMode": {
        "price": {
            "amount": 500,
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 10,
        "unit": "UNIT"
    }
}'

**Comment by MartaNowaczyk** [comment]
Dzień dobry, nie robimy gotowych żądań pod daną aplikację. Proszę skorzystać z [poradnika](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR), w którym krok po kroku jest opisane jak to zrobić. 
Nie podawaj wrażliwych danych na publicznym forum. Twój post edytowałam.
