### ISSUE TITLE
Sale suspended error

### ISSUE THREAD

**Issue by lwillems** [allegro/allegro-api#7208]
Hello

Got an issue in production with API
All offers (using legacy draft) we are trying to publish are rejected : 
We have checked our account and provided required documents two weeks ago, balance has been paid multiple times.
Can you please check our account and tell us what we need to do to unlock ? we are unable to sale since 1 month :/ 

```json
    "errors": [
      {
        "code": "VALIDATION_ERROR",
        "message": "You do not have the permissions required to list an offer (sales suspended). Explain the violation of rules.",
        "details": "",
        "path": "seller",
        "userMessage": "You do not have the permissions required to list an offer (sales suspended). Explain the violation of rules."
      }
    ],
```

trace-id: a817ad3b83aa61c4 (is useful)
Our account login is numiscorner

Thx for your help

Regards

**Comment by MartaNowaczyk** [comment]
I would be happy to help, but the issue is related to the production account, so in this case you need to write through the [contact form](https://allegro.pl/pomoc/kontakt).

**Comment by lwillems** [comment]
Hi @MartaNowaczyk

Thx for your help i have reached them.

Regards
