### ISSUE TITLE
Szukanie produktu 

### ISSUE THREAD

**Issue by Axlii50** [allegro/allegro-api#7209]
czy bazując na responsie z url: https://developer.allegro.pl/documentation#operation/getSaleProducts
mozna wykryć czy produkt jest zestawem lub czy mozna ustawić requesta tak by mogło zwrócić tylko pojedynczy produkt a nie zestaw

**Comment by Lukasz-Zurek** [comment]
Niestety w obu przytoczonych przypadkach nie ma tego typu możliwości.

**Comment by Axlii50** [comment]
to w jaki sposób mógł rozróżnić czy zasugerowany produkt jest jako zestaw czy jako pojedynczy produkt ?

**Comment by Lukasz-Zurek** [comment]
Zestaw produktów składa się z więcej niż jednego produktu i nie zwracamy takich informacji na wskazanym zasobie (nie mamy ku temu podstaw), ponieważ zestaw produktowy to oferta sprzedaży, którą można utworzyć z kilku różnych produktów. Opisaliśmy to w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-utworzyc-zestaw-produktowy). Czyli o tym z których produktów składa się zestaw, decyduje Sprzedający.

**Comment by Axlii50** [comment]
czyli rozumiem ze z zasobu do sugerowania produktu nie ma możliwości otrzymania produktu który jest zestawem.

**Comment by Lukasz-Zurek** [comment]
@Axlii50 Nie ma możliwości.

**Comment by Axlii50** [comment]
W takim razie dziękuje za szybką pomoc w nakierowaniu na problem
Miłego dnia
