### ISSUE TITLE
Pobieranie nazwy użytkownika po ID

### ISSUE THREAD

**Issue by Radziasss** [allegro/allegro-api#721]
Jak za pomocą REST API pobrać nazwę użytkownika Allegro mając jego ID?

**Comment by PawelTaberski** [comment]
Obecnie w REST API nie ma takiej możliwości. Takie informacje możesz pobrać przez WebAPI przy pomocy zasobu [doGetUserLogin](https://allegro.pl/webapi/documentation.php/show/id,104).

**Comment by Radziasss** [comment]
A kiedy planujecie taką metodę dodać? Metoda nie wygląda na skomplikowaną, a byłaby bardzo pomocna. Nie chcę korzystać z webapi, skoro zaraz je wygasicie i będę musiał przerabiać na restapi.

**Comment by PawelTaberski** [comment]
Nie jestem w stanie powiedzieć kiedy wdrożymy taką metodę, jeśli otrzymamy informacje o czasie wdrożenia takiej metody to poinformujemy o tym.
