### ISSUE TITLE
Sandbox REST api activation / clientID + secret

### ISSUE THREAD

**Issue by dzejkob-b** [allegro/allegro-api#7210]
Hello, I want to test the integration using your API on a sandbox. I have probably activated sandbox account (link for activation in profile disappeared) with probably activated two step verification (at two step page it shows "turned on"). 
But at apps on sandbox web: https://apps.developer.allegro.pl.allegrosandbox.pl/ it still shows "Activate your account and enable two-step login.". Can you please activate my sandbox account for me to be able to create an app with client id and secret code?

Account name: admin_perfecto, admin@perfecto.cz

Thanks

**Comment by MartaNowaczyk** [comment]
I have activated your account. Check now to confirm that you can add a new application.

**Comment by dzejkob-b** [comment]
Tested, app added, it works, thanks.

**Comment by dzejkob-b** [comment]
I have another problem: product proposal request (/sale/product-proposals) returns 403 error - on sandbox environment:

	[0] => Array
	    (
	        [code] => AccessDeniedException
	        [message] => Access denied.
	        [details] => 
	        [path] => 
	        [userMessage] => Nedostupné.
	    )

I checked other tickets and read that i need a company account - but apparently i got company account (in account settings i see company info). I also checked sandbox application settings (with id 6c00919501654f768fbfd9afbc838138) and all possible permissions are checked. 
Is it possible to fix it?

**Comment by MartaNowaczyk** [comment]
Looks like you are trying to use a token from Client_credentials authorization method - which is without user context.

To use this resource you need to generate a token using [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) authorization. In our documentation you will find the appropriate markings:

- bearer-token-for-user - for resource means code or device authorization,
- bearer-token-for-application - client_credentials.
