### ISSUE TITLE
Problem z tworzeniem przesyłek Allegro One przez REST API (Sandbox)

### ISSUE THREAD

**Issue by akonopka** [allegro/allegro-api#7211]
Dzień dobry.

Czy przez REST API w wersji testowej można tworzyć przesyłki i etykiety dla Allegro One (różne metody wysyłki)? Tworzę przesyłkę, wysyłając żądanie na adres https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands. Status odpowiedzi 201. Odpowiedź:

"{"id":"a13f6a14-2af7-42df-9200-41715a053bb9","input":{"serviceId":"0d83955a-4297-4169-adef-9790d53b11ff","label":{"sender":{"name":"Jan Kowalski","company":"Allegro.pl sp. z o.o.","address":{"street":"Główna","postCode":"10-200","city":"Warszawa","county":"AL","countryCode":"PL"},"email":"email@mail.com","phone":"500600700"},"fileFormat":"PDF","referenceNumber":"abcd1234"},"receiver":{"name":"Jan Kowalski","company":"Allegro.pl sp. z o.o.","address":{"street":"Główna","postCode":"10-200","city":"Warszawa","county":"AL","countryCode":"PL"},"pointId":"1234567","email":"hamu7udk3p+17454c1b6@allegromail.pl","phone":"500600700"},"pickup":{"name":"Jan Kowalski","company":"Allegro.pl sp. z o.o.","address":{"street":"Główna","postCode":"10-200","city":"Warszawa","county":"AL","countryCode":"PL"},"pointId":null,"email":"email@mail.com","phone":"500600700"},"items":[{"dimensions":{"height":{"value":"12","unit":"CENTIMETER"},"width":{"value":"12","unit":"CENTIMETER"},"depth":{"value":"12","unit":"CENTIMETER"}},"weight":{"value":"12.45","unit":"KILOGRAM"},"description":"Car wheels.","value":{"amount":"2.50","currency":"PLN"},"type":"PACKAGE"}],"type":"PACKAGE","additionalServices":null}}" 

Ale jak chcę sprawdzić status utworzenia przesyłki mam status nadal poprawny, bo 200, ale w odpowiedzi już coś takiego:
"{"id":"a13f6a14-2af7-42df-9200-41715a053bb9","parcelId":null,"status":"ERROR","errors":[{"code":"ANOTHER_SERVICE_NOT_AVAILABLE","message":"One of required services is unavailable. Try again later.","details":"One of required services is unavailable. Try again later.","path":null,"userMessage":"Jeden z wymaganych serwisów, do poprawnego działania, jest niedostępny. Spróbuj ponownie za moment."}]}"

Co może być przyczyną tego problemu? Bez parcelId nie utworzę etykiety, czy dobrze myślę? 

Probówałam dla kilku różnych metod wysyłki pobieranych z /parcel-management/delivery-services. Zmieniłam też pointId na null, bo gdzieś widziałam w komentarzu taką poradę. To metoda wysyłki "Allegro One Kurier - dostawa jutro", czy dobrze myślę, że pointId dotyczy punktu odbioru dla paczkomatów? Skąd ewentualnie wziąć wartości dostępne na sandboxie, gdybym chciała to ustawić dla Allegro One Box?

**Comment by akonopka** [comment]
Dzień dobry.

Czy przez REST API w wersji testowej można tworzyć przesyłki i etykiety dla Allegro One (różne metody wysyłki)? Tworzę przesyłkę, wysyłając żądanie na adres https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands. Status odpowiedzi 201. Odpowiedź:

"{"id":"a13f6a14-2af7-42df-9200-41715a053bb9","input":{"serviceId":"0d83955a-4297-4169-adef-9790d53b11ff","label":{"sender":{"name":"Jan Kowalski","company":"Allegro.pl sp. z o.o.","address":{"street":"Główna","postCode":"10-200","city":"Warszawa","county":"AL","countryCode":"PL"},"email":"email@mail.com","phone":"500600700"},"fileFormat":"PDF","referenceNumber":"abcd1234"},"receiver":{"name":"Jan Kowalski","company":"Allegro.pl sp. z o.o.","address":{"street":"Główna","postCode":"10-200","city":"Warszawa","county":"AL","countryCode":"PL"},"pointId":"1234567","email":"hamu7udk3p+17454c1b6@allegromail.pl","phone":"500600700"},"pickup":{"name":"Jan Kowalski","company":"Allegro.pl sp. z o.o.","address":{"street":"Główna","postCode":"10-200","city":"Warszawa","county":"AL","countryCode":"PL"},"pointId":null,"email":"email@mail.com","phone":"500600700"},"items":[{"dimensions":{"height":{"value":"12","unit":"CENTIMETER"},"width":{"value":"12","unit":"CENTIMETER"},"depth":{"value":"12","unit":"CENTIMETER"}},"weight":{"value":"12.45","unit":"KILOGRAM"},"description":"Car wheels.","value":{"amount":"2.50","currency":"PLN"},"type":"PACKAGE"}],"type":"PACKAGE","additionalServices":null}}" 

Ale jak chcę sprawdzić status utworzenia przesyłki status nadal 200, ale w odpowiedzi już coś takiego:
"{"id":"a13f6a14-2af7-42df-9200-41715a053bb9","parcelId":null,"status":"ERROR","errors":[{"code":"ANOTHER_SERVICE_NOT_AVAILABLE","message":"One of required services is unavailable. Try again later.","details":"One of required services is unavailable. Try again later.","path":null,"userMessage":"Jeden z wymaganych serwisów, do poprawnego działania, jest niedostępny. Spróbuj ponownie za moment."}]}"

Co może być przyczyną tego problemu? Bez parcelId nie utworzę etykiety, czy dobrze myślę?

**Comment by akonopka** [comment]
Konkretnie takie metody wysyłki mnie interesują (W BaseLinkerze tak to wygląda):
Allegro: Allegro One Kurier - dostawa jutro
Allegro: Allegro One Box, One Kurier
Allegro: Allegro One Punkt
Allegro: Allegro One Box
Allegro: Allegro One Punkt, One Kurier

**Comment by akonopka** [comment]
Gdzieś widziałam też komentarz, że w godzinach porannych trzeba tworzyć przesyłki, ale chyba dotyczy to tylko przesyłek z dostawą dzisiaj, i nie wiem czy na sandboxie też jest to ograniczenie?

**Comment by MartaNowaczyk** [comment]
Sprawdzamy opisany problem z tym błędem, jak tylko uda nam się to zweryfikować dam znać.

**Comment by MartaNowaczyk** [comment]
@akonopka z jakiego dnia jest zamówienie do którego próbujesz utworzyć przesyłkę?

**Comment by akonopka** [comment]
> @akonopka z jakiego dnia jest zamówienie do którego próbujesz utworzyć przesyłkę?

To były fikcyjne dane z dokumentacji. Pierwsza styczność z tym API i chciałam tylko zobaczyć jak sam proces przebiega, a szczegółami zająć się potem.

**Comment by MartaNowaczyk** [comment]
Rozumiem, jednak ważne by z innego konta zrobić takie fikcyjne zamówienie i do niego dodawać przesyłkę. Najlepiej zrób świeże zamówienie i do niego spróbuj nadać przesyłkę, aby przejść poprawnie cały proces zakupowo-sprzedażowy.

**Comment by akonopka** [comment]
Nie widzę, żeby tutaj było jakieś powiązanie pomiędzy przesyłką, którą tworzę, a jakimś zamówieniem, nigdzie nie podaję id zamówienia np. Chyba, że już wcześniej jakiś problem z samym kontem się ujawni w ten sposób? To chodzi o sandbox, mam sobie utworzyć produkt i z drugiego konta (testowego też) kupić go?

Nie wiem, czy jeszcze możecie Państwo sprawdzić, w czym móbł być problem, bo pośpieszyłam się i usunęłam apkę. Potrzebuję w zasadzie apki, która nie będzie potrzebować dostępu do przeglądarki. Utworzyłam niemniej jednak nową apkę webową (tamta była tworzona pół roku temu, więc w sumie pod tym względem to nawet nie było złe posunięcie), ten sam problem jest (commandId fa28840a-e4ad-438e-bf85-1e2f843da989).

**Comment by MartaNowaczyk** [comment]
Powiązaniem jest [maskowany adres emai](https://allegro.pl/dla-sprzedajacych/usluga-dostawy-jak-poprawnie-przekazac-adres-mailowy-B89wXan7PiX)l, który jest tworzony w procesie zakupowym. W [poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke) w requeście tworzenia paczki znajdziesz opis, że musisz podać prawidłowy adres email dla tej transakcji. 
Można mieć jakieś fikcyjne dane, ale takie fikcyjne zamówienie musi istnieć. Czyli taki jak piszesz, możesz mieć dwa konta: do sprzedaży i do zakupów. Na jednym wystawiasz oferty, na drugim kupujesz. Otrzymujesz zamówienie i do tego zamówienia, według zawartych tam danych dodajesz przesyłkę.

**Comment by akonopka** [comment]
Ok, rozumiem, dzięki.

**Comment by akonopka** [comment]
Czy mogę prosić o weryfikację mojego konta? Login licjaa. Zmieniłam konto na firmowe, uzupełniłam dane, wysłałam cokolwiek jako dokumenty, bo podobno tak to przebiega (?). Dwustopniową weryfikację muszę włączyć na sandboxie? Nie dostałam SMS.

**Comment by MartaNowaczyk** [comment]
Aktywowałam Twoje konto firmowe licjaa. Dwustopniowe logowanie na sandboxie nie jest wymagane. Nie wysyłamy też smsów na środowisku testowym.

Client:106026728 to konto zwykłe. Aby je aktywować, wykonaj symulację przelewu weryfikacyjnego w [Moje konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto).

**Comment by akonopka** [comment]
Utworzyłam testowe zamówienie, ale mam wątpliwości jak teraz mam zmienić te przykładowe dane od Państwa.
Co powinno być w receiver->address->county? Województwo? Nie widzę, żeby to było gdzieś podawane w danych klienta.
receiver->pointId to numer punktu odbioru, jeśli np. klient zechce odebrać paczkę w jakimś paczkomacie?
A pickup co to jest? Skąd kurier odbierze paczkę? Czy skąd klient ją będzie odbierał? Na koncie firmowym mam coś takiego jak "Danych konta" jak "Adresy do wysyłki". Czy tych danych mam tutaj użyć?
I jeszcze label->sender. Tam mają być "Dane firmy" czy któryś z adresów z "Adresów do wysyłki"?

        `{
          "serviceId": "0d83955a-4297-4169-adef-9790d53b11ff",
          "receiver": {
            "address": {
              "street": "Główna",
              "postCode": "10-200",
              "city": "Warszawa",
              "countryCode": "PL",
              "county": "AL"
            },
            "email": "hamu7udk3p+17454c1b6@allegromail.pl",
            "name": "Jan Kowalski",
            "company": "Allegro.pl sp. z o.o.",
            "phone": "500600700",
            "pointId": null
          },
          "pickup": {
            "address": {
              "street": "Główna",
              "postCode": "10-200",
              "city": "Warszawa",
              "countryCode": "PL",
              "county": "AL"
            },
            "email": "email@mail.com",
            "name": "Jan Kowalski",
            "company": "Allegro.pl sp. z o.o.",
            "phone": "500600700",
            "pointId": null
          },
          "items": [
            {
              "dimensions": {
                "height": {
                  "value": "12",
                  "unit": "CENTIMETER"
                },
                "width": {
                  "value": "12",
                  "unit": "CENTIMETER"
                },
                "depth": {
                  "value": "12",
                  "unit": "CENTIMETER"
                }
              },
              "weight": {
                "value": "12.45",
                "unit": "KILOGRAM"
              },
              "description": "Car wheels.",
              "value": {
                "amount": "2.50",
                "currency": "PLN"
              },
              "type": "PACKAGE"
            }
          ],
          "type": "PACKAGE",
          "label": {
            "sender": {
              "address": {
                "street": "Główna",
                "postCode": "10-200",
                "city": "Warszawa",
                "countryCode": "PL",
                "county": "AL"
              },
              "email": "email@mail.com",
              "name": "Jan Kowalski",
              "company": "Allegro.pl sp. z o.o.",
              "phone": "500600700"
            },
            "fileFormat": "PDF",
            "referenceNumber": "abcd1234"
          }          
        }`

**Comment by akonopka** [comment]
Jako "Dane dostawy" dla tego zamówienia mam:

`
DANE DOSTAWY

Allegro One Punkt, One Kurier (Allegro One Punkt A004497)

8,99 zł

Jana Olbrachta 11
01-111 Warszawa

1 przesyłka
Klient Imię Klient Nazwisko
Kliencka 11
01-493 Warszawa PL
+48516606099
`
Może te dane powinny być w "pickup"?

**Comment by akonopka** [comment]
Sama sobie odpowiem, że dobrym pomysłem może być utworzenie przesyłki z poziomu Allegro, pobranie jej danych i zobaczenie, co tam w jakim polu się znajdzie. 
Ale chętnie przyjmę wszelkie inne sugestie :)
