### ISSUE TITLE
Problem z odświeżeniem tokenu

### ISSUE THREAD

**Issue by JurekAndrzejewski** [allegro/allegro-api#7212]
Hej,
Podczas próby odświeżenia tokenu przy użyciu zasobu **https://allegro.pl/auth/oauth/token**
dostaje zwrotkę **401**

> {"error":"invalid_token","error_description":"Error decoding token. Token: MÓJ TOKEN

Na czym może polegać ten błąd? Używając kodu dostępnego u was na stronie sytuacja wygląda tak samo.

**Comment by MartaNowaczyk** [comment]
Prześlij proszę przykładowy request i response w formacie cURL przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz, że dane dotyczą wątku [#7212](https://github.com/allegro/allegro-api/issues/7212) na GitHub. Zweryfikujemy, co jest przyczyną błędu.

**Comment by JurekAndrzejewski** [comment]
> 

Po drugiej próbie podpięcia "aplikacji do konta" przy użyciu zasobu https://allegro.pl/auth/oauth/device a potem https://allegro.pl/auth/oauth/token zaczęło działać, może wcześniej skopiowałem bez jednego znaku, aczkolwiek problem zaczął się od tego, że skrypt odświeżający token, gdzie przerzucam token bez żadnej modyfikacji przestał działać.

Na ten moment problem został rozwiązany, także dziękuję.
