### ISSUE TITLE
Aktywacja konta Allegro Sandbox CZ

### ISSUE THREAD

**Issue by PProtasewicz** [allegro/allegro-api#7215]
Witam,
prosiłbym o aktywacje konta TestCZ123 - Sandbox Allegro CZ.

Dziękuje i Pozdrawiam ;)
Piotr

**Comment by Lukasz-Zurek** [comment]
@PProtasewicz Aktywowałem wskazane konto.

**Comment by PProtasewicz** [comment]
@Lukasz-Zurek Super, dziękuje ;)
