### ISSUE TITLE
Błąd walidacji EAN podczas wystawiania oferty

### ISSUE THREAD

**Issue by kuba-end** [allegro/allegro-api#7217]
Dzień dobry, proszę o zerknięcie na mój problem

Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

- trace-id : d3b38b3cd557bdee
- OPIS: Wygląda na to że validator błędnie bierze id parametru (225693) jako values pomimo poprawnego wysłania EANu w requeście, zwracając error "Incorrect value of the EAN/ISBN/ISSN (225693) parameter for the offered product. The correct parameter value for the product is: \"5900378665809\".: Niepoprawna wartość parametru EAN/ISBN/ISSN (225693) dla produktu w ofercie. Prawidłowa wartość parametru dla produktu to: \"5900378665809\"."

Z góry dzięki, czekam na odpowiedź :)

**Comment by MartaNowaczyk** [comment]
Z logów wynika, że na podstawie Twojego zapytania znaleźliśmy pasujący produkt o ID c5834645-903b-4e45-9812-13271d2ba293, w którym parametr 225693 ma wartość 5900378665809, a Ty podajesz "5903949734492", stąd ten błąd.

**Comment by kuba-end** [comment]
Rzeczywiście wysłany został błędny EAN, do tej pory jednak zarówno na endpoincie createDraft jak i createProductOffer zwracaliście exception w przypadku błędnej walidacji. Teraz zwracany jest on tylko na endpoincie createDraft. Czy to zamierzone działanie?

**Comment by MartaNowaczyk** [comment]
Jak tylko zweryfikuję czy była jakaś zmiana w tym zakresie dam znać.

**Comment by kuba-end** [comment]
Dzień dobry w ten cudowny czwartkowy poranek, czy udało się coś ustalić?

**Comment by MartaNowaczyk** [comment]
Dzień dobry, mam informację, ze nie wprowadzaliśmy zmian. Masz jakiś konkretny przykład jak to się zmieniło?

**Comment by kuba-end** [comment]
Do tej pory byłem w stanie wyłapać $exception i na niego zareagować, obecnie nie jestem w stanie złapać wyjątku kiedy wyślę błędne dane na endpoint createProductOffer, 
`try {
            return $offerDTO instanceof ProductSaleOfferDTO ?
                $this->allegroApi->createProductOffer($accountId, $offerDTO) : $this->allegroApi->createDraft($accountId, $offerDTO);
        } catch (ClientExceptionInterface $exception) {`

Wysyłając te same dane pod createDraft dostanę zwrotkę i mogę automatycznie poprawić błędne pola. Kod działał ponad pół roku, natomiast teraz z jakiegoś powodu nie mogę złapać wyjątku z endpointu createProductOffer

**Comment by MartaNowaczyk** [comment]
Rozumiem. Możesz podać jeszcze trace-id z responsów konkretnych przypadków gdzie zwracamy, a gdzie nie?

**Comment by michaldabrowski98** [comment]
Dzień dobry, podsyłam trace-id z przypadków wspomnianych wcześniej przez kolegę:
Brak wyjątku: 8ba2b2d10852f31e
Wyjątek: b05e96ad8b511411

**Comment by MartaNowaczyk** [comment]
Dzień dobry. dziękuję sprawdzimy i dam znać.

**Comment by MartaNowaczyk** [comment]
@michaldabrowski98 przykłady miały dotyczyć przypadków dla createDraft i createProductOffer, a trace-id 8ba2b2d10852f31e dotyczy wyszukiwania produktów.
