### ISSUE TITLE
Zarządzanie aplikacjami Allegro Sandbox - Brak możliwości dodania aplikacji

### ISSUE THREAD

**Issue by hyper-cube** [allegro/allegro-api#7218]
Nie można zarejestrować nowej aplikacji (Sandbox). Cały czas mam informację o konieczności aktywowania konta. Nie wiem co jeszcze mógłbym zrobić, żeby konto było aktywne. Coś przegapilem? Konto (oximo_s).

Z góry dziękuję za pomoc.

**Comment by MartaNowaczyk** [comment]
Zrobiłeś wszystko co mogłeś. Aktywowałam to konto, więc teraz powinno być ok.

**Comment by hyper-cube** [comment]
Dziękuję bardzo. Teraz od kilku dni męczę się z wystawieniem czegokolwiek i zawsze dostaję błąd 403

"{"errors":[{"code":"AccessDeniedException","message":"Access is denied","details":null,"path":null,"userMessage":"No access."}]}"

Czy można jakoś w łatwy sposób sprawdzić, czy mam możliwość wystawienia czegokolwiek (w sensie czy nie mam zablokowanego dostępu)? Wciąż chodzi o Sandbox.

Z góry dziękuję za pomoc.

**Comment by MartaNowaczyk** [comment]
Z tego co widzę konto jest aktywne, więc nie powinno być problemu w tej kwestii. Sprawdź czy przekazujesz odpowiedni scope `allegro:api:sale:offers:write` oraz czy nie korzystasz podczas wystawiania z autoryzacji typu `client_credentials`, która nie posiada kontekstu użytkownika. W[ naszej dokumentacji](https://developer.allegro.pl/documentation/) znajdziesz odpowiednie oznaczenie, jaki typ autoryzacji wymagany jest dla danego zasobu:

- bearer-token-for-user ([code](https://developer.allegro.pl/auth/#app) lub[ device](https://developer.allegro.pl/auth/#DeviceFlow) flow),
- bearer-token-for-application ([client credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow)).

**Comment by hyper-cube** [comment]
OK. Posprawdzam wszystko jeszcze raz. Bardzo dziękuję za pomoc. Miłego dnia :)

**Comment by MartaNowaczyk** [comment]
Dziękuję i wzajemnie :)
