### ISSUE TITLE
Allegro.cz sandbox account

### ISSUE THREAD

**Issue by ondravojta** [allegro/allegro-api#7219]
Hello,

I need to develop API connection to Allegro.cz. I have created sandbox account (client:111818591). I am able to authenticate by device code flow. Now I wanted to create an offer (/sale/product-offers), but server is still returning OfferAccessDeniedException (Access denied. You are not authorized to perform operations on the indicated offer). I think it may be related to misconfigured sandbox account. In account details I can see that I don't have business acount and I don't have sales activated. But I am unable to change it. Attempts to activate sales ends after picking type of payment on error page saying "We can’t connect to the server at c2c-payu-simulator.dh-test.qxlint.". And changing account type to business is even worse - everything is in polish, it requires some ID numbers like NIP, KRS, ...

Can you please help me identify problem or make my account usable if it is account related error?

Thank you.

Request url:
https://api.allegro.pl.allegrosandbox.pl/sale/product-offers

Request body (from api doc):
```{
  "productSet": [{
        "product": {
            "id": "5902719471797",
            "idType": "GTIN"
                            
  }}],
  "sellingMode": {
    "price": {
      "amount": "220.85",              
      "currency": "PLN"
    }
  },
  "stock": {
    "available": 10                    
  }
}```

**Comment by MartaNowaczyk** [comment]
The account you provided is a regular account from production (allegro.pl), not from the sandbox test environment. If you want a Czech account on sandbox, register a [new company account](https://allegro.cz.allegrosandbox.pl/registrace/firemni-ucet/novy-ucet?origin_url=%2F) with fictitious data.

**Comment by ondravojta** [comment]
Strange, I thought I have sandbox account, but thank you.

I registred new account with username ondravojta. Does it need some activation? If I want to register application it says that I need to activate account and set 2FA. Somewhere I read that 2FA is not necessary with sandbox account, so account is not somehow activated?

**Comment by MartaNowaczyk** [comment]
I have activated your account. 2FA is not necessary on Sandbox.
