### ISSUE TITLE
Atrybut koloru API

### ISSUE THREAD

**Issue by justynapalka** [allegro/allegro-api#7220]
Dzień dory,
zostałam odesłałam z zespołu wsparcia VIP do team API odnośnie do poniższego problemu.
Czy mogę prosić o wsparcie w poniższym zapytaniu?
Z góry dziekuję.

We have seen multiple products rejected due to a "parameter not existing" error. Upon review this is the colour attribute which looks to have been updated but we do not have the correct information

So far we have found products under the following category ID's that have been rejected due to this error:

256728

256734

5537

Can you please share the updated parameter information for the above categories so these products can be updated and we can re-submit them to Allegro

**Comment by MartaNowaczyk** [comment]
Dzień dobry, aktualne parametry dla danej kategorii można sprawdzić samodzielnie przez wywołanie [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).

**Comment by justynapalka** [comment]
Dzień dobry, czy mogę prosić o informację czy parametry zostały poprawnie przekazane w ramach integracji dla poniższego przykładu?
DBP333___68LC20_
{"errors":[{"code":"ParameterException.ParameterDoesNotExistException","message":"An error has occurred","details":null,"path":"parameters","userMessage":"Parameter 215930 does not exist."}]}

**Comment by MartaNowaczyk** [comment]
Dzień dobry, z treści komunikatu błędu wynika, że nie, ale do pełnej weryfikacji potrzebuję trace-id lub ID kategorii, której to dotyczy. Może też być pełen request w postaci curl.

**Comment by justynapalka** [comment]
Dzień dobry,
Id kategorii to 256734.

Dziekuję

**Comment by MartaNowaczyk** [comment]
Dzień dobry, w podanej kategorii nie ma takiego parametru, także komunikat jest prawidłowy.

**Comment by justynapalka** [comment]
Dzień dobry,
wcześniej parametr ten był wymagany podczas przesyłania feedu.

Proszę o informację skąd mamy w danym momencie wiedzieć, że parametr przestaje być wymagany?
Z góry dziękuję

**Comment by MartaNowaczyk** [comment]
Dzień dobry, tak jak pisałam możesz pobierać aktualne dane przez wywołanie [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). 

Mamy też dwa zasoby, które pozwalają śledzić zmiany w kategoriach i parametrach:

[GET /sale/category-events](https://developer.allegro.pl/documentation/#operation/getCategoryEventsUsingGET_1) - wskazuje jakie zmiany zaszły w kategoriach w ciągu ostatnich 3 miesięcy;
[GET /sale/category-parameters-scheduled-changes](https://developer.allegro.pl/documentation/#operation/getCategoryParametersScheduledChangesUsingGET_1) - pozwala śledzić planowane zmiany w parametrach.
