### ISSUE TITLE
Aktywacja konta firmowego w ramach https://allegro.pl.allegrosandbox.pl/

### ISSUE THREAD

**Issue by Arzecki** [allegro/allegro-api#7221]
Dzień dobry,

proszę o aktywację mojego konta sandbox "SdboxAdamKorz".

Chciałbym potestować API, jednak obecnie, w ramach https://apps.developer.allegro.pl.allegrosandbox.pl widzę komunikat:

Nie możesz zarejestrować nowej aplikacji
Aktywuj konto oraz włącz dwustopniowe logowanie.

Dziękuję.

**Comment by MartaNowaczyk** [comment]
Dzień dobry, aktywowałam Twoje konto. Sprawdź czy teraz jest ok.

**Comment by Arzecki** [comment]
Wszystko jest już w porządku - dziękuję.
