### ISSUE TITLE
Problemy w obsłudze wybranych endpointów w REST API

### ISSUE THREAD

**Issue by Arzecki** [allegro/allegro-api#7224]
Dzień dobry,

proszę o pomoc w wyjaśnieniu problemów w obsłudze wybranych endpointów w REST API:

1. Korzystam z metody: https://developer.allegro.pl/documentation#tag/User's-offer-information 

curl --location 'https://api.allegro.pl/sale/offers' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer eyJ***

i dostaję w rs (trace-id: 1012cf0f891d536d) - pusto:

{
    "offers": [],
    "count": 0,
    "totalCount": 0
}

2. Korzystam z tej samej metody: https://developer.allegro.pl/documentation#tag/User's-offer-information 
ale wskazując w query param publication.status z jego wartością ACTIVE:

curl --location 'https://api.allegro.pl/sale/offers?publication.status=ACTIVE' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer eyJ***

i dostaję w rs (trace-id: 969bbf9b7c79d213) - pusto:

{
    "offers": [],
    "count": 0,
    "totalCount": 0
}

3. Korzystam z metody (Deprecated): https://developer.allegro.pl/documentation#operation/getOfferUsingGET
odpytując o konkretne offerId jako path param (przedłużenie url-a)

curl --location 'https://api.allegro.pl/sale/offers/12116638***' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer eyJ***

i dostaję w rs (trace-id: 1a38fabd0582375d) - szczegóły odpytywanej oferty są mi zwracane prawidłowo:

{
    "id": "12116638***",
    "name": "ROYAL CANIN CCN Mini Exigent 3kg",

4. Korzystam z metody: https://developer.allegro.pl/documentation#operation/getProductOffer
odpytując o konkretne offerId jako path param (przedłużenie url-a)

curl --location 'https://api.allegro.pl/sale/product-offers/12116638***' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer eyJ***

i dostaję w rs (trace-id: eae30da465f8fc12) - 403 Forbidden:

{
    "errors": [
        {
            "code": "OfferAccessDeniedException",
            "message": "Forbidden",
            "details": null,
            "path": "",
            "userMessage": "Access denied. You are not authorized to perform operations on the indicated offer"
        }
    ]
}

Proszę o pomoc w zlokalizowaniu przyczyn problemów przy ad.1-2-4 (w przypadku ad.3 endpoint wydaje się działać prawidłowo).

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Jeśli chodzi o 1. i 2. - prawidłowo nie zwracamy żadnych danych ponieważ na koncie, na którym jesteś zautoryzowany - nie ma ofert. 

Co do punktu 3. - wg. logów wskazana oferta należy do innego, ale powiązanego (z tym, na którym jesteś autoryzowany) konta, więc możesz tym zasobem uzyskać informacje dotyczące oferty (nie otrzymasz jej jednak na liście - patrz punkt 1. i 2.).

Punkt 4. - na tym zasobie nie uzyskasz informacji dotyczącej oferty z innego konta w Serwisie. Funkcjonalność ta nie przewiduje tego.
