### ISSUE TITLE
Długość nazwy odbiorcy w parcel-create-commands

### ISSUE THREAD

**Issue by SlawekMat** [allegro/allegro-api#7225]
Dzień dobry,
chciałbym dopytać jaka jest maksymalna długość nazwy odbiorcy przy zakładaniu przesyłki, obecnie wysyłając "CieKawa Cafe Aleksandra Śnieżk" otrzymuje komunikat:
"{\"id\":\"00735519-0001-0000-0000-003523003872\",\"parcelId\":null,\"status\":\"ERROR\",\"errors\":[{\"code\":\"VALIDATION_ERROR\",\"message\":\"Receiver name is too long\",\"details\":null,\"path\":\"receiver.name\",\"userMessage\":\"Nazwa odbiorcy jest za długa\"}]}"

**Comment by Lukasz-Zurek** [comment]
Przekazałem ten temat zespołowi odpowiedzialnemu za tę usługę. Potwierdzam, że na pierwszy rzut oka nie przekraczasz limitu dla tego pola. Błąd zwrócił nam nasz operator, dlatego musimy to jeszcze dodatkowo skonsultować.

**Comment by SlawekMat** [comment]
Dziękuję

**Comment by SlawekMat** [comment]
Udało się coś ustalić w tej sprawie?
Sam też wysyłam informacje do UPS i pole nazwy mają ograniczone do 35 znaków, ale tutaj jest mniej więc chyba to nie jest problemem.

**Comment by Lukasz-Zurek** [comment]
@SlawekMat Limit dla tego pola w przypadku "Allegro Kurier UPS" wynosi 30 znaków. Nasz operator miał problem z polskimi znakami, dlatego też zwracał błąd, mimo, że limit nie był przekraczany. Została już wdrożona poprawka i problem nie powinien już występować.

**Comment by SlawekMat** [comment]
Dziękuję :)
