### ISSUE TITLE
Dodawanie powiązanej aplikacji

### ISSUE THREAD

**Issue by kacperKarman** [allegro/allegro-api#7226]
Dzień dobry. Mam problem z powiązaniem aplikacji z moim kontem. Wchodząc na "https://allegro.pl/moje-allegro/ustawienia/powiazane-aplikacje" widzę komunikat "Ta strona nie istnieje. Mogliśmy ją usunąć lub przenieść". 
Około rok temu dodawałem aplikację w ten sposób. Czy coś się zmieniło w ostatnim czasie? Czy adres pod którym można powiązać aplikację z kontem się zmienił czy robi się to teraz w jakiś zupełnie inny sposób?

**Comment by Lukasz-Zurek** [comment]
Strona "Powiązane aplikacje" znajduje się pod adresem: [https://allegro.pl/moje-allegro/moje-konto/powiazane-aplikacje](https://allegro.pl/moje-allegro/moje-konto/powiazane-aplikacje).
