### ISSUE TITLE
Minimal required implementation

### ISSUE THREAD

**Issue by JiriKroupaFamico** [allegro/allegro-api#7227]
Hello, our company is considering integration of Allegro into our system. We would like to know what is the minimal required implementation needed for start selling on your platform

1. We need to list offers via POST [/sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers)
As I understand we must distinguish if the product is in your Catalog or not. To find out we simply have to call GET [/sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts) with parameters phrase containing EAN and mode set to GTIN. If endpoint returns empty result it is safe to say the product is not in your Catalog.

1.1 If product is in your Catalog, we should get category.id from product data (GET /sale/products) and check on GET [/sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) if the product has any required parameters I should send them in body to POST /sale/product-offers to avoid receiving response with information about missing required parameters.

1.2 If product is not in your Catalog, we should first pair your categories from API endpoint GET [/sale/categories](https://developer.allegro.pl/documentation/#operation/getCategoriesUsingGET) with our own categories to decide which category to put the product to. Then check for required category parameters at GET [/sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) and send them with the product data as well.

The result request body for API endpoint POST /sale/product-offers should look like this:
````
{
  "productSet": [{
        "product": {
            "name": "Test product",
            "id": "5902719471797",
            "idType": "GTIN",
            "images":[ "https://...first-image-address.jpeg"],
            "category":{
             "id":"89060"
            },
            "parameters":[
                {
                    "id": "237218",
                    "values": ["required parameter for category"]
                }
            ]
  }}],
  "sellingMode": {
    "price": {
      "amount": "220.85",              
      "currency": "CZK"
    }
  },
  "name": "Test product",
  "description": {
      "sections": [
          {
              "items": [
                  {
                      "type": "TEXT",
                      "content": "<p>test</p>"
                  }
              ]
          }
      ]
  },
  "language": "cs-CZ",
  "stock": {
    "available": 10,
    "unit": "UNIT"
  },
  "external": {
    "id": "ABC TEST"
  }
}
````

QUESTIONS:
a) Is above approach correct or can this be achieved in easier way?
b) I could not find how to get list of parameters in [API documentation](https://developer.allegro.pl/documentation) neither in [glossary](https://developer.allegro.pl/tutorials/glossary-LRVjol8kdCA) . Is there a way to get your parameters so we can pair them with parameters in our database, so we can automate the import, so we can send values for required parameters?
c) Is it possible to import offers in bulk via API or using feed? I found a possibility to use CSV file https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-ofert-z-pliku/jak-masowo-wystawic-oferty-z-wlasnego-pliku-oAemrk86MSV , but it seems to be available only from sales management and not API.
d) If I understand it correctly. If I use API endpoint POST [/sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) to create offer multiple times with the same productSet.product.id multiple offers for the same products will be created, the only way the edit existing offer is via PUT or PATCH /sale/offer* API endpoints containing offerId parameter. Meaning for offer editing I need to know offerId?

2. We need to fetch order events from API endpoint GET [/order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET) and filter them by type "READY_FOR_PROCESSING" (unless there is event with the same checkout form id with type "BUYER_CANCELLED" and later occurredAt value). To get info about buyer, payment and delivery we need to call API endpoint GET /order/checkout-form/{id} using checkout form id from order event.
2.2 if we start fulfilling order we use API endpoint PUT [/order/checkout-forms/{checkoutForm.id}/fulfillment](https://developer.allegro.pl/documentation/#operation/setOrderFulfillmentUsingPUT) to change status to PROCESSING and if the order is dispatched then to change status to SENT and add tracking numbers via POST [/order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST). If we have to cancel order for one reason or another we change status to CANCELLED

QUESTIONS:
a) Does this cover the minimum requirements for order handling?
b) Is there any need to send somewhere information about product sizes and possible transportations?
c) If we have our own processes to handle returns and reclamation then we do not have to implement it on your side?
d) Is there any need for payment matching from our side or is it all handled by you?
e) Is it required to upload invoice via your API to order if will send it to customer in email as attachement?

**Comment by Lukasz-Zurek** [comment]
You have raised a few different issues here, so I'll get back to you with a comprehensive answer tomorrow. Please be patient.

**Comment by Lukasz-Zurek** [comment]
@JiriKroupaFamico Hello again. I am coming back with some answers to your questions.

1. 
a) This approach is correct. Generally speaking - by using [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers), you only need to provide a product identifier, GTIN or MPN (Catalog number given by the manufacturer) of a product from our Catalog to list an offer. And if we do not have your product in our Catalog, then you can create a new one using the same resource. This works automatically but all needed parameters are required.
b) No, there is no such a list and we cannot add it to our documentation. Please note that the parameters can change constantly. This is why we provide GET [/sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) resource, where you can retrieve up-to-date data.
c) No, it is not possible. You cannot import offers in bulk, using our API. And you are right - there is an option in My Allegro tab, which you have just mentioned. But it’s not API related so I cannot help you in this case.
d) Yes, excactly.

2. 
a) Yes, it covers the minimum requirements. But using [fulfillment status](https://developer.allegro.pl/tutorials/process-orders-PgPMlWDr8Cv#order-fulfillment-status-change) in your orders is really up to you and your needs.
b) No, it is not needed. That kind of data you can provide while creating a parcel using PUT /parcel-management/parcel-create-commands/{commandId}. You will find more information right [here](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-create-a-new-parcel).
c) Please note the fact that Allegro Customers use our return process, this is why we provide [some resources to manage customer returns](https://developer.allegro.pl/tutorials/process-orders-PgPMlWDr8Cv#customer-returns).
d) First of all, by retrieving events, you can match the order and use [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET) where you can also retrieve an information about the payment (which is already matched to this specific order). You can also check the payment operations by using GET /payments/payment-operations ([more information](https://developer.allegro.pl/tutorials/how-to-check-the-fees-3An6Wame3Um#payment-operations)), as well as refund a payment via POST /payments/refunds ([more information](https://developer.allegro.pl/tutorials/process-orders-PgPMlWDr8Cv#payment-refunds)).
e) This question is more about Allegro as a whole, not Allegro API. Obviously we provide a resource for adding an invoice to the order and in that kind of situation the Customer will receive an invoice via e-mail message and he will be able to download it from the Allegro Orders tab.
Of course, again, it is up to you whether you prefer to send an invoice via e-mail by your own, or use our resources.
