### ISSUE TITLE
Tworzenie przesylki pobraniowej packeta API

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#7228]
Przy probie tworzenia przesylki pobraniowej packeta "Allegro Wysyłka z Polski do Czech - Odbiór w Punkcie Packeta pobranie" id: "114d388f-354f-41c1-a0ea-36d2032265ad", otrzymujemy komunikat "Wybrana metoda dostawy nie wymaga podania numeru iban, wpłatę za przesyłki pobraniowe prześlemy na Twoje środki". Problem w tym że niektóre metody dostaw wymagają podania konta numeru bankowego przy pobraniach a niektóre nie. Czy jest jakaś możliwość żeby dostać informację które metody wymagają tego pola? Lub taka sugestia skoro jakaś metoda dostawy nie wymaga podania numeru konta a wpłaty będą i tak zwrócone na środki Allegro to nie lepiej żeby api poprostu pomineło to pole automatycznie po waszej stronie zamiast zwracać niepotrzebnie błąd?

**Comment by MartaNowaczyk** [comment]
Sprawę zgłosiłam do odpowiedniego zespołu. Wrócę z informacją.

**Comment by MartaNowaczyk** [comment]
Metody pobraniowe na kierunku PL-CZ i CZ-CZ zgodnie z realizują przekaz środków dla sprzedającego następuje za pomocą zmiany salda w “Środki i historie operacji”. Z tego względu IBAN używany do przelewów jest tam zbędny, a wręcz mylący.
W związku z tym została podjęta decyzja o zmianie walidacji i dlatego pojawił się wspomniany komunikat błędu.

Dotyczy to metod:
- methodId: 1b28f4fb-df3e-4324-a6ef-707a3f1be43b
  methodName: "Allegro Kurier DHL Czechy pobranie"
- methodId: 1401412f-1bcc-4dad-98c4-b3146fe9f54a
  methodName: "Allegro International Czechy Kurier pobranie"
- methodId: 191819e3-32c6-4602-b78f-b3146fe9f54a
  methodName: "Allegro International Czechy Odbiór w Automacie Paczkowym pobranie"
- methodId: 1037d74a-2043-4ed0-aff7-b3146fe9f54a
  methodName: "Allegro International Czechy Odbiór w Punkcie pobranie"
- methodId: 114d388f-354f-41c1-a0ea-36d2032265ad
  methodName: "Allegro Wysyłka z Polski do Czech - Odbiór w Punkcie Packeta pobranie (allegro.cz)"
- methodId: 129b132a-348c-4b48-aba0-9c4a33aba97c
  methodName: "Allegro Wysyłka z Polski do Czech - Automaty Paczkowe Packeta pobranie (allegro.cz)"
- methodId: 1e080d8f-f20a-497a-8f88-4d184a138d2a
  methodName: "Allegro Odbiór w Punkcie Packeta pobranie"
- methodId: 19841d0a-374d-4764-8313-84a1765f3340
  methodName: "Allegro Automaty Paczkowe Packeta pobranie"
- methodId: 1856a050-2bcb-445b-a66d-0a3151c1da58
  methodName: "Allegro Kurier WE|DO pobranie"
- methodId: 1cfe0620-9616-4d36-9222-a3f8ed84a513
  methodName: "Allegro Odbiór w Punkcie WE|DO pobranie"
- methodId: 1acc38bc-9f08-470d-95b3-11c76ab6e905
  methodName: "Allegro Automaty Paczkowe WE|DO pobranie"
