### ISSUE TITLE
Sandbox – problem z pokazywaniem obrazków

### ISSUE THREAD

**Issue by shopelo** [allegro/allegro-api#7229]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Witam,
Występuje problem z pokazywaniem obrazków na sandboxie (problem globalny).
Czy mogę prosić o dokonanie fixa aby obrazki się pojawiały?

**Comment by MartaNowaczyk** [comment]
Zgłosiłam ten problem do odpowiedniego zespołu. Wrócę z informacją.

**Comment by MartaNowaczyk** [comment]
@shopelo Sprawdź proszę czy problem u Ciebie nadal występuje?

**Comment by shopelo** [comment]
> @shopelo Sprawdź proszę czy problem u Ciebie nadal występuje?

Potwierdzam. Problem nadal występuje. Brak widocznych zdjęć w serwisie oraz w panelu klienta

**Comment by MartaNowaczyk** [comment]
Pracujemy nad rozwiązaniem. Dam znać, gdy uda nam się to poprawić.

**Comment by MartaNowaczyk** [comment]
Poprawiliśmy, zdjęcia są już widoczne. Dzięki za zgłoszenie i przepraszamy za niedogodności.

**Comment by shopelo** [comment]
Dziękuję za szybką reakcję.
