### ISSUE TITLE
Bug w PUT /sale/offer-variants/{id} - nie usuwa nieuwzględnionych ofert

### ISSUE THREAD

**Issue by imper86** [allegro/allegro-api#7230]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**

Generalnie chodzi o to, że metoda `PUT /sale/offer-variants/{id}` nie usuwa ofert, których nie uwzględniono w tablicy z ofertami. Jako, że poza użyciem DELETE na zestawie nie ma innej opcji aby taką ofertę z zestawu usunąć zgłaszam temat jako błąd.

Przykładowy request:
`PUT /sale/offer-variants/1f86e8d1-1146-4e60-8f20-4a0c84e5c0b5`
```json
{"name":"123280\/adidas VS Switch + Altasport + V Jog + V Ra","offers":[{"id":"13204755410","colorPattern":"37936"},{"id":"13204755373","colorPattern":"37936"},{"id":"13204755313","colorPattern":"37936"},{"id":"13204755279","colorPattern":"37936"},{"id":"13204755242","colorPattern":"37936"},{"id":"13204656257","colorPattern":"37932"},{"id":"13204656232","colorPattern":"37932"},{"id":"13204656163","colorPattern":"37932"},{"id":"13204656091","colorPattern":"37932"}],"parameters":[{"id":"color\/pattern"},{"id":"26388"}]
```

Response:
```json
{"id":"1f86e8d1-1146-4e60-8f20-4a0c84e5c0b5","offers":[{"id":"13204656257","colorPattern":"37932"},{"id":"13204755410","colorPattern":"37936"},{"id":"13204755242","colorPattern":"37936"},{"id":"13613422555","colorPattern":"37936"},{"id":"13204656163","colorPattern":"37932"},{"id":"13204755313","colorPattern":"37936"},{"id":"13204656232","colorPattern":"37932"},{"id":"13204755279","colorPattern":"37936"},{"id":"13204755342","colorPattern":"37936"},{"id":"13204656091","colorPattern":"37932"},{"id":"13204755373","colorPattern":"37936"}],"name":"123280/adidas VS Switch + Altasport + V Jog + V Ra","parameters":[{"id":"26388"},{"id":"color/pattern"}]}
```

Prośba o zwrócenie uwagi na ofertę id `13204755342` - nie ma jej w requeście, a więc chcę ją usunąć z zestawu, a w response radośnie pojawia się jak gdyby nigdy nic :).

Trace id tego konkretnego requestu - `d5e176050418159b`

Najprawdopodobniej działa to w ten sposób od bardzo długiego czasu, ale wcześniej działało prawidłowo i się popsuło.

**Comment by imper86** [comment]
W sumie to wyłapałem jeszcze ciekawszy przypadek, który już w ogóle eliminuje możliwość dowolnego sterowania wielowariantowością.

Request `POST /sale/offer-variants`
```json
{"name":"126892\/adidas VS Switch + Altasport + V Jog + V Ra","offers":[{"id":"13204755410","colorPattern":"37936"},{"id":"13204755373","colorPattern":"37936"},{"id":"13204755313","colorPattern":"37936"},{"id":"13204755279","colorPattern":"37936"},{"id":"13204755242","colorPattern":"37936"},{"id":"13204656257","colorPattern":"37932"},{"id":"13204656232","colorPattern":"37932"},{"id":"13204656163","colorPattern":"37932"},{"id":"13204656091","colorPattern":"37932"}],"parameters":[{"id":"color\/pattern"},{"id":"26388"}]}
```

response:
```json
{"id":"4e120710-1035-4f5b-9f61-23b45c3510bc","offers":[{"id":"13204755410","colorPattern":"37936"},{"id":"13204755342","colorPattern":"37936"},{"id":"13204755242","colorPattern":"37936"},{"id":"13204755279","colorPattern":"37936"},{"id":"13204656163","colorPattern":"37932"},{"id":"13204656232","colorPattern":"37932"},{"id":"13204656091","colorPattern":"37932"},{"id":"13613422555","colorPattern":"37936"},{"id":"13204755373","colorPattern":"37936"},{"id":"13204656257","colorPattern":"37932"},{"id":"13204755313","colorPattern":"37936"}],"name":"126892/adidas VS Switch + Altasport + V Jog + V Ra","parameters":[{"id":"26388"},{"id":"color/pattern"}]}
```

Znowu ta sama oferta - `13204755342`...

trace id - `b4ba0e44d176505c`

**Comment by MartaNowaczyk** [comment]
Weryfikujemy Twój przypadek. Sprawdziłam też działanie podanych endpointów i nie miałam tego typu problemów. Wrócę z odpowiedzią.

**Comment by imper86** [comment]
Mam więcej takich przypadków, ten jest tylko przykładowy. Kolejny przykład:

`PUT /sale/offer-variants/e04104d6-cf3f-4655-8f28-e32cbd09c940`
request:
```json
{"name":"124261\/Bielizna\/147812\/G\u00f3ra","offers":[{"id":"13028349168","colorPattern":"37198"},{"id":"13028349074","colorPattern":"37198"}],"parameters":[{"id":"color\/pattern"},{"id":"54"}]}
```
response:
```json
{"id":"e04104d6-cf3f-4655-8f28-e32cbd09c940","offers":[{"id":"13028349104","colorPattern":"37198"},{"id":"13028349151","colorPattern":"37198"},{"id":"13028349168","colorPattern":"37198"},{"id":"13028349074","colorPattern":"37198"}],"name":"124261/Bielizna/147812/Góra","parameters":[{"id":"54"},{"id":"color/pattern"}]}
```
traceid - 51783fd072cd7454

Co tam robi oferta `13028349104`? :)

Daj proszę znać czy mam podesłać wszystkie znalezione przypadki. Nie wygląda to jak problem z pojedynczymi zestawami, bardziej jak problem w samej logice tych mechanizmów.

**Comment by MartaNowaczyk** [comment]
Na ten moment przeanalizowaliśmy pierwszy przypadek oferty 13204755342. Według naszych danych 14.06.2023 dla tej oferty wykonane były takie akcje:

```
setId | time | request | traceId

4e120710-1035-4f5b-9f61-23b45c3510bc | 2023-06-14 19:27:03 | POST 	/sale/offer-variants | b4ba0e44d176505c
1f86e8d1-1146-4e60-8f20-4a0c84e5c0b5 | 2023-06-14 19:26:42 | DELETE /sale/offer-variants/1f86e8d1-1146-4e60-8f20-4a0c84e5c0b5 | 230b2c13307b7112
1f86e8d1-1146-4e60-8f20-4a0c84e5c0b5 | 2023-06-14 19:02:03 | PUT 	/sale/offer-variants/1f86e8d1-1146-4e60-8f20-4a0c84e5c0b5 | d5e176050418159b

```

Jeśli chodzi o traceId:  `d5e176050418159b` - według naszych logów oferta 13204755342 nie była usunięta z oferty wielowariantowej.

Usuwanie jest możliwe i po naszych testach stwierdzamy, że działa to poprawnie.

**Comment by imper86** [comment]
No właśnie rzecz w tym, że nie działa poprawnie. Oferta 13204755342 nie była usunięta z zestawu ze względu na błąd. Zwróćcie proszę uwagę na request, który był wysyłany choćby ten traceid `d5e176050418159b`:
```json
{"name":"123280\/adidas VS Switch + Altasport + V Jog + V Ra","offers":[{"id":"13204755410","colorPattern":"37936"},{"id":"13204755373","colorPattern":"37936"},{"id":"13204755313","colorPattern":"37936"},{"id":"13204755279","colorPattern":"37936"},{"id":"13204755242","colorPattern":"37936"},{"id":"13204656257","colorPattern":"37932"},{"id":"13204656232","colorPattern":"37932"},{"id":"13204656163","colorPattern":"37932"},{"id":"13204656091","colorPattern":"37932"}],"parameters":[{"id":"color\/pattern"},{"id":"26388"}]
```

Nie ma w tym requeście oferty 13204755342, a mimo wszystko nadal była w zestawie.

Ponownie, request POST traceid `b4ba0e44d176505c`:
```json
{"name":"126892\/adidas VS Switch + Altasport + V Jog + V Ra","offers":[{"id":"13204755410","colorPattern":"37936"},{"id":"13204755373","colorPattern":"37936"},{"id":"13204755313","colorPattern":"37936"},{"id":"13204755279","colorPattern":"37936"},{"id":"13204755242","colorPattern":"37936"},{"id":"13204656257","colorPattern":"37932"},{"id":"13204656232","colorPattern":"37932"},{"id":"13204656163","colorPattern":"37932"},{"id":"13204656091","colorPattern":"37932"}],"parameters":[{"id":"color\/pattern"},{"id":"26388"}]}
```

Tutaj również próżno szukać oferty 13204755342, a mimo wszystko znalazła się w zestawie. Jak?

Podpowiem - nawet response do obydwu requestów zawierały już ofertę 13204755342 pomimo tego, że **nie była wysyłana w requeście**.

Jak dla mnie oczywisty błąd :)

**Comment by Lukasz-Zurek** [comment]
@imper86 Dziękuję za dokładne opisanie problemu. Przekazałem już temat do zespołu odpowiedzialnego za tę funkcjonalność. Jak tylko uzyskam szczegółowe informacje - wrócę do Ciebie w tym wątku.

**Comment by Lukasz-Zurek** [comment]
@imper86 W niektórych kategoriach (wymienionych w pkt 1.12.2 [Regulaminu Serwisu](https://allegro.pl/regulamin/pl/zalacznik-2)), oferty wielowariantowe łączymy automatycznie na podstawie parametrów, w związku z czym usunięcie jednej z ofert, która wcześniej została do takiej wielowariantowej oferty automatycznie dodana- nie będzie możliwe i tu niestety nie przewidujemy bezpośredniej ingerencji w zawartość dla ofert wielowariantowych w kategoriach [zarządzanych automatycznie](https://allegro.pl/dla-sprzedajacych/wprowadzamy-automatyczne-laczenie-ofert-w-oferty-wielowariantowe-EYWkzVmdOsD).
