### ISSUE TITLE
Prośba o kwalifikację offerId do programu Allegro Ceny w ramach https://allegro.pl.allegrosandbox.pl/

### ISSUE THREAD

**Issue by Arzecki** [allegro/allegro-api#7231]
Dzień dobry,

prosiłbym o zakwalifikowanie offerId 7708858638 do programu Allegro Ceny w ramach https://allegro.pl.allegrosandbox.pl/

Chciałbym potestować w REST API możliwości takiego oznaczenia oferty.

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Oferta 7708858638 jest już dodana do programu Allegro Ceny.
