### ISSUE TITLE
tworzenie produktu przez API

### ISSUE THREAD

**Issue by kochanA** [allegro/allegro-api#7232]
Próbuję wystawić testowy produkt ("sale/product-proposals") na koncie sandbox ciągle dostaje 400:

2023-06-15 06:23:08,677 30993 WARNING Error refers to : 400 {"errors":[{"code":"HttpMessageNotReadableException","message":"An error has occurred","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."}]}

sprawdzam strukturę body jak w zapytaniu : https://developer.allegro.pl/documentation/#operation/proposeSaleProduct
i wydaje się być wszystko dobrze.
Proszę o informację czy w ogóle istnieje możliwość wystawienia produktu przez zapytanie na koncie sandbox'owym.

**Comment by MartaNowaczyk** [comment]
Tak, powinna być taka możliwość. Do weryfikacji podeślij dane z requestu kończącego się wspomnianym błędem.

**Comment by kochanA** [comment]
{'name': 'Trampolina z siatką 305 cm', 'category': {'id': 1754}, 'images': {'url': 'https://a.allegroimg.allegrosandbox.pl/original/11da67/3111aa5143d8b55c53c9e977865c'}, 'parameters': [{'id': 127828, 'values': ['z siatką']}, {'id': 224017, 'values': ['HS-T10A Black/Green - 4 nogi']}, {'id': 127769, 'values': [’Sand-box']}, {'id': 249436, 'values': ['256,00 cm']}, {'id': 229049, 'values': ['305,00 cm']}], 'description': {'description': {'sections': [{'items': [{'type': 'TEXT', 'content': '<p><b>➡️ Trampolina ogrodowa  </b>to gwarancja świetnej, aktywnej rozrywki dla całej rodziny. Dla dzieci stanie się wyjątkowym centrum zabaw podczas wiosennych i letnich dni, skutecznie odciągając ich od tabletu czy telewizora,&nbsp;zapewniając tym samym ruch na powietrzu. Dorośli także mogą skorzystać z korzyści, jakie oferuje zabawa na trampolinie. Energiczne podskoki i akrobacje to bowiem doskonały sposób na wzmocnienie mięśni, dotlenienie organizmu oraz spalenie nadmiaru kalorii. Baw się i trenuj jednocześnie!</p><p>Podczas trampolinowych szaleństw najważniejsze jest bezpieczeństwo. Dlatego wszystkie modele trampolin marki wykonane są zgodnie z normami&nbsp;<b>PN-EN 71-14&nbsp;</b>oraz posiadają&nbsp;<b>Certyfikat INTERTEK,&nbsp;</b>dzięki czemu zapewniają bezpieczną zabawę zarówno młodszym, jak i starszym użytkownikom. Dzięki solidnej, stalowej konstrukcji trampolina jest&nbsp;<b>odporna na odkształcenia i uszkodzenia</b>, nawet w momencie intensywnego użytkowania przez całą rodzinę. Maksymalne obciążenie trampoliny wynosi aż 150 kg!</p><p style="margin-bottom: 0px;"> '}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.com/original/11c286/9e89c467418fbc9aa5b1c751532f'}]}, {'items': [{'type': 'TEXT', 'content': ' '}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.com/original/1135ba/9128b47b4917b4f1c7d508e72331'}]}, {'items': [{'type': 'TEXT', 'content': ' </p><p><b>➡️ W ZESTAWIE ZNAJDUJE SIĘ:</b></p><ul> <li>Trampolina 10ft (305cm) z zewnętrzną siatką zabezpieczającą</li>  <li>drabinka,</li> <li>osłona przeciwdeszczowa na batut,</li> <li>rękawice do montażu</li> <li>organizer na drobiazgi, siatka na buty</li> <li>haki do mocowania trampoliny</li> <li>piłka do siatkówki,</li> <li>piłka plażowa</li> </ul><p><b>➡️ </b>Atutem produktu jest&nbsp;<b>łatwy i szybki montaż</b>. Wszystkie kroki składania są precyzyjnie opisane w instrukcji dołączonej do zestawu. Dodatkowo, dla ułatwienia cały proces montażu prezentujemy w naszym filmie instruktażowym, umieszczonym poniżej. Zobacz, jakie to proste!</p><p>__________</p><p><b>❗❗❗BEZPIECZEŃSTWO:</b></p><ul> <li><b>Zgodność z normami PN-EN 71-14</b></li> <li><b>Certyfikat INTERTEK</b>&nbsp;- nasze trampoliny homologowane są przez najlepszą&nbsp;renomowaną instytucję badawczą w Europie -&nbsp;Intertek&nbsp;z Wielkiej Brytanii. Badane produkty poddawane są wnikliwym testom&nbsp;pod&nbsp;względem&nbsp;bezpieczeństwa&nbsp;oraz wymogów jakościowych.</li> <li><b>Konsumencki Lider Jakości 2018 oraz 2019 -</b> dwa lata z rzędu uzyskaliśmy złote godło w programie <b>KONSUMENCKI LIDER JAKOŚCI</b>&nbsp;w kategorii&nbsp;<b>TRAMPOLINY.&nbsp;</b>Nagroda przyznawana jest na podstawie analizy wyników badań konsumenckich.</li> </ul><p style="margin-bottom: 0px;"> '}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.com/original/11d391/e3fab8174ff2a0886296323eeeaf'}]}, {'items': [{'type': 'TEXT', 'content': ' '}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.com/original/110010/bb18258b43e8a273f1ab4b4c0228'}]}, {'items': [{'type': 'TEXT', 'content': ' </p><p><b>✅ Stalowa konstrukcja -</b> wszystkie elementy konstrukcyjne trampoliny ogrodowej marki  wykonano z wysokiej jakości stali hartowanej, ocynkowanej i galwanizowanej, co zapewnia im trwałość przez minimum kilka sezonów oraz skutecznie chroni przed korozją.</p><p style="margin-bottom: 0px;"> '}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.com/original/1127a7/55abbc4c4c649522be56692f07ff'}]}, {'items': [{'type': 'TEXT', 'content': ' </p><p><b>✅ Mocna siatka ochronna -</b> wykonana z wysokiej jakości polietylenu, wysoka siatka ochronna o wytrzymałym splocie, zapinana na zamek i na klamerki, gwarantuje bezpieczeństwo nawet podczas intensywnej zabawy. Jest to szczególnie istotne w przypadku najmłodszych użytkowników. Zamek posiada kształt litery L, dzięki czemu wchodzenie i wychodzenie z trampoliny jest jeszcze bardziej wygodne. Dodatkowo, zamek jest w innym kolorze niż siatka, co znacznie ułatwia dzieciom zlokalizowanie wyjścia.</p><p><b>✅ Wytrzymała mata -</b> mata do odbić wykonana jest z polipropylenu o grubości 275g/m2 – materiału odpornego nie tylko na duże obciążenia, ale także na wilgoć, promieniowanie słoneczne oraz inne warunki atmosferyczne.</p><p><b>✅ Zabezpieczone sprężyny -</b> galwanizowane sprężyny w trampolinie zostały precyzyjnie okryte dwuwarstwowym materiałem wypełnionym gąbką, stanowiącym jednocześnie skuteczną warstwę ochronną przed śniegiem, deszczem i innymi warunkami atmosferycznymi.</p><p>Dodatkowo, otrzymujesz od nas:</p><ul> <li>praktyczny&nbsp;pokrowiec ochronny&nbsp;na batut,</li> <li>drabinkę,</li> <li>organizer na drobiazgi, siatka na buty</li> <li>haki, za pomocą których&nbsp;przytwierdzisz&nbsp;trampolinę do podłoża,</li> <li>rękawiczki do montażu,</li> <li>piłki z logo do gier i zabaw z rodziną oraz przyjaciółmi.</li> </ul><p><b>➡️ Dane techniczne:</b></p><ul> <li>Producent: </li> <li>Model: Trampolina HS-T10A</li> <li>Kolor osłonki: czarno-zielony</li> <li>Maksymalne obciążenie: 150 kg</li> <li>Rozmiar: 10 ft</li> <li>Średnica: 305 cm</li> <li>Ilość nóg: 4</li> <li>Wysokość: 256 cm</li> <li>Wysokość od podłoża do maty: 76 cm</li> <li>Wysokość siatki: 180 cm</li> <li>Średnica maty: 261 cm</li> </ul><p><b>➡️ Szczegółowe parametry:</b></p><ul> <li>Waga brutto: 54 kg</li> <li>Wymiary kartonu 1/2: 125 x 50 x 23 cm</li> <li>Wymiary kartonu 2/2: 110 x 40 x 17 cm</li> <li>Mocowanie siatki: Wewnętrzne - sprężyny znajdują się po zewnętrznej stronie siatki</li> <li>Materiał siatki: Wytrzymały polietylen o grubości 100g/m2 (oczka)</li> <li>Materiał maty: Sprężysty polipropylen o grubości 275g/m2 (wysoka odporność na UV)</li> <li>Szerokość osłonki na sprężyny: 27 cm</li> <li>Grubość osłonki na sprężyny: 20 mm</li> <li>Materiał osłonki na sprężyny: Mieszanka PVC z PE (PVC 310g/m2 + PE 110g/m2)</li> <li>Wypełnienie osłonki: Pianka PVC</li> <li>Ilość sprężyn: 64 sztuki o parametrach splotu śr.3mm x 145mm</li> <li>Ilość nóg: 4 sztuki o parametrach rurek śr.38mm i gr.1.2mm</li> <li>Ilość słupków: 8 sztuk składające się z 12 rurek o parametrach śr.25mm i gr.1.2mm</li> <li>Ilość elementów ramy: 8 sztuk o parametrach rurek śr.38mm i gr.1.35mm</li> <li>Wysokość drabinki: 86 cm, z dwoma stopniami</li> </ul>'}]}]}}, 'language': 'pl-PL'}

**Comment by MartaNowaczyk** [comment]
Dzięki, jak tylko zweryfikuję te dane, dam znać.

**Comment by kochanA** [comment]
Dziękuję, czekam w takim razie na informację

**Comment by MartaNowaczyk** [comment]
Dla zdjęć brakuje tablicy, powinno być:

```
  "images": [
      {
    "url": "https://a.allegroimg.allegrosandbox.pl/original/11da67/3111aa5143d8b55c53c9e977865c"
  }
  ],
```

Dla opisu masz 2x "description" i nieprawidłowe wartości html  `style="margin-bottom: 0px;"` w dwóch miejscach - usuń

```
"description": {
    "description": {
      "sections": [
        {
          "items": [
            {
              "type": "TEXT",
              "content": "<p><b>➡️ Trampolina ogrodowa  </b>to gwarancja świetnej, aktywnej rozrywki dla całej rodziny. Dla dzieci stanie się wyjątkowym centrum zabaw podczas wiosennych i letnich dni, skutecznie odciągając ich od tabletu czy telewizora,&nbsp;zapewniając tym samym ruch na powietrzu. Dorośli także mogą skorzystać z korzyści, jakie oferuje zabawa na trampolinie. Energiczne podskoki i akrobacje to bowiem doskonały sposób na wzmocnienie mięśni, dotlenienie organizmu oraz spalenie nadmiaru kalorii. Baw się i trenuj jednocześnie!</p><p>Podczas trampolinowych szaleństw najważniejsze jest bezpieczeństwo. Dlatego wszystkie modele trampolin marki wykonane są zgodnie z normami&nbsp;<b>PN-EN 71-14&nbsp;</b>oraz posiadają&nbsp;<b>Certyfikat INTERTEK,&nbsp;</b>dzięki czemu zapewniają bezpieczną zabawę zarówno młodszym, jak i starszym użytkownikom. Dzięki solidnej, stalowej konstrukcji trampolina jest&nbsp;<b>odporna na odkształcenia i uszkodzenia</b>, nawet w momencie intensywnego użytkowania przez całą rodzinę. Maksymalne obciążenie trampoliny wynosi aż 150 kg!</p><p style="margin-bottom: 0px;"> "
            }
          ]
        },
  ...
```
Masz też niepoprawną kategorię.

**Comment by kochanA** [comment]
Bardzo dziękuje za wskazówki. Mam jeszcze jedno pytanie dostaje odpowiedz 422 z opisem czego brakuje :
 422 {"errors":[{"code":"VALIDATION_ERROR","message":"nie może być odstępem","details":null,"path":"standardized.sections[2].items[0].content","userMessage":"nie może być odstępem"},{"code":"VALIDATION_ERROR","message":"nie może być odstępem","details":null,"path":"standardized.sections[6].items[0].content","userMessage":"nie może być odstępem"}]}
 
 podmieniłam wysyłane dane we wcześniejszej wiadomości na aktualne, proszę o podpowiedz o co chodzi z tym błędem.

**Comment by MartaNowaczyk** [comment]
Podaj trace-id lub cały request, tak jak poprzednio, to sprawdzę o co chodzi.

**Comment by kochanA** [comment]
zmienione dane są w drugiej wiadomości https://github.com/allegro/allegro-api/issues/7232#issuecomment-1592694414

**Comment by MartaNowaczyk** [comment]
Dobra, pomyślałam, że u siebie zmieniałaś. Za chwilę sprawdzę.

**Comment by kochanA** [comment]
Dziękuję

**Comment by MartaNowaczyk** [comment]
Ten błąd powodują dwie puste sekcje, a dokładnie w podanym opisie:

```
{'items': [{'type': 'TEXT', 'content': ' '}]}
```

**Comment by kochanA** [comment]
Faktycznie bardzo dziękuję. Niestety to nie koniec : "Parametr 127828 nie jest parametrem stringowym."
jest to pierwszy z moich parametrów :

'parameters': [{'id': 127828, 'values': ['z siatką']}, {'id': 224017, 'values': ['HS-T10A Black/Green - 4 nogi']}, {'id': 127769, 'values': ['port']}, {'id': 249436, 'values': ['256,00 cm']}, {'id': 229049, 'values': ['305,00 cm']}, {'id': 3475, 'values': ['3 lata +']}, {'id': 215202, 'values': ['10 (304-312 cm)']}, {'id': 6876, 'values': ['150 kg']}, {'id': 220577, 'values': ['Round']}, {'id': '225693', 'values': ['5902308222007']}],

w opisie requesta https://developer.allegro.pl/documentation/#operation/proposeSaleProduct
parametry są opisane następująco :
"parameters": [
{
"id": "string",
"rangeValue": {},
"values": [
"string"
],
"valuesIds": [],
"valuesLabels": [],
"unit": "string",
"options": {
"identifiesProduct": true
}
}
],

ja wysyłam tylko "id" i "values" obie te wartości są oznaczone jako string, co tu robię źle ?

**Comment by PrzemyslawLukanowski** [comment]
Wygląda na to, że parametr 127828 nie jest typu "string", lecz "dictionary". Informację o typach parametrów znajdziesz w polu `type` w odpowiedzi zasobu[ /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). W takim przypadku, musisz przekazać identyfikator wybranej wartości w polu `valuesIds` zamiast w `values`. Wszystkie identyfikatory wartości również otrzymasz w wyżej wspomnianym zasobie. Przykład:

```
{
      "id": "209878",
      "valuesIds": [
      "209878_1"
      ],
      "values": [],
      "rangeValue": null
  }
```
