### ISSUE TITLE
tłumaczenie oferty 

### ISSUE THREAD

**Issue by bseHlpDsk** [allegro/allegro-api#7233]
Metoda (https://api.allegro.pl/sale/offers/13598997940/translations/uk-UA)
w odpowiedzi: 
Could not update description translation for offer:13598997940 and language:uk-UA

tytuł oferty zaktualizowany poprawnie. Dla części ofert poprawnie zaktualizowane zarówno nazwa oferty jak i opis. JSON poprawny. 

`{
"description": {

    "translation": 

{
            "sections": [{
            "items": [{
                "type": "TEXT",
                "content": "<h1>Найкращі казки України</h1>"
            }]
        }, {
            "items": [{
                "type": "IMAGE",
                "url": "https://a.allegroimg.com/original/117893/1704c64b495b99229f48d3a41d01"
            }, {
                "type": "TEXT",
                "content": "<ul><li>ISBN: 9789667991845</li><li>Видавець: Промінь Харків </li><li>дата публікації: 01.0 </li></ul>"
            }]
        }, {
            "items": [{
                "type": "TEXT",
                "content": "<p>До книги увійшли популярні, найвідоміші казки. Діти пізнають країну фантазії, познайомляться з дивовижними героями народних українських казок. Веселі та яскраві малюнки зроблять читання книги приємним і захоплюючим. Адресується дітям дошкільного та молодшого шкільного віку.</p>"
            }]
        }, 
        {
            "items": [{
                "type": "TEXT",
                "content": "<p>sygnatura 84</p>"
            }]
        }]
    }

}, 
"title": 

    {
        "translation": "Найкращі казки України"
    }

}`

**Comment by MartaNowaczyk** [comment]
Weryfikuję opisaną sytuację. W celu przyspieszenia weryfikacji, jeśli to możliwe, podsyłaj trace-id dla odpowiedzi z błędem.

**Comment by MartaNowaczyk** [comment]
Z ustaleń wynika, że taka sytuacja ma miejsce, gdy wysyłany tekst nie był zmieniany, czyli, gdy jest  taki sam jak tłumaczenie. Wtedy pojawia się właśnie błąd 422 Unprocessable Entity.

**Comment by bseHlpDsk** [comment]
Dziękuję 
m.
