### ISSUE TITLE
Oferty wielowariantowe

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#7235]
Przy tworzeniu oferty wielowariantowej pokazuje mi się komunikat:
Łączenie ofert po parametrze 249512 jest zablokowane w kategorii 87843.

Wystawiałem w kategorii Moda -> Odzież, Obuwie, Dodatki -> Odzież męska -> Bluzy -> Bluza z wariantami.
W tej kategorii na Allegro są oferty wielowariantowe: https://prnt.sc/4sLvJRmwnnkZ. Dlaczego więc jest taki komunikat u nas?

**Comment by Lukasz-Zurek** [comment]
W kategorii 87843 warianty ofertowe zastępują warianty produktowe, stąd ten błąd.

Więcej informacji na temat wariantów produktowych znajdziesz w [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/laczenie-ofert-z-katalogiem-produktow-produktyzacja-/czym-sa-warianty-produktowe-PgoV1gXzrt2).

**Comment by PrzemyslawLukanowski** [comment]
Warianty produktowe w odróżnieniu od wariantów ofertowych tworzymy w całości automatycznie po naszej stronie. Więcej informacji znajdziesz we wspomnianym wyżej artykule [pomocy Allegro.](https://allegro.pl/pomoc/dla-sprzedajacych/laczenie-ofert-z-katalogiem-produktow-produktyzacja-/czym-sa-warianty-produktowe-PgoV1gXzrt2) Na tę chwilę nie znajdziesz tych informacji w naszej dokumentacji - uzupełnimy to w najbliższej przyszłości. 

Jeśli chodzi o sytuację, którą opisałeś na początku, to przepraszam za wprowadzenie w błąd, ale przyczyna błędu jest inna. W tej kategorii nie ma możliwości łączenia po parametrze "kolor". Informację o tym znajdziesz w odpowiedzi dla GET /ale/categories/87843/parameters:

```
            "id": "249512",
            "name": "Kolor",
            ...
            "options": {
                "variantsAllowed": false,
```

Screen, który załączyłeś dotyczy parametru Kolor/Wzór (**colorPattern**), który nie jest tożsamy z parametrem Kolor o id 249512 w danej kategorii.

Informację o tym, że oferty możesz łączyć według **colorPattern** zwracamy w GET /sale/categories/{categoryId}:

```
    "id": "87843",
    "name": "Bluzy",
    "options": {
        "variantsByColorPatternAllowed": true,
```

**Comment by DamianKAtomStore** [comment]
Oferty 7711962039, 7711962544 nie mają wypełnionego parametru 4906.

Dostaję taki error przy próbie złączenia 2 ofert na środowisku testowym. Dlaczego dostaję taki błąd pomimo że oferty wystawiłem też przez wasze API i takiego błędu nam nie zwróciło?

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, że chcesz połączyć oferty wg tego parametru. Nie jest on obowiązkowy w związku z czym mogłeś wystawić wspomniane oferty. Jeśli jednak chcesz użyć go do połączenia ofert w ofertę wielowariantową, musisz go uzupełnić w ofertach, ponieważ w aktualnym stanie nie mamy informacji o wartości tego parametru w ofertach.
