### ISSUE TITLE
How to get arbitrary product details?

### ISSUE THREAD

**Issue by cosinus90** [allegro/allegro-api#7236]
Hello! I'm trying to get product details with
https://api.allegro.pl.allegrosandbox.pl/sale/products/7708639203
(Bearer token sent, I got the id from search by keyword)
and get
`{"errors":[{"code":"AccessDeniedException","message":"Access denied.","details":null,"path":null,"userMessage":"No access."}]}`

How can I (my client, actually) allowed to get this? Thanks.

Client id e074be6a405b4490a091b9487256eb6f

**Comment by MartaNowaczyk** [comment]
It looks like you are using a token with no user context - Client_credentials authorization method. 
To use [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct)  you need to generate a token using [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) authorization. In our documentation you will find the appropriate markings:
- bearer-token-for-user - for resource means code or device authorization;
- bearer-token-for-application - client_credentials.

The full list of authorization methods you will find in [our guide](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR).
