### ISSUE TITLE
GET /sale/offers/numer - Tax setting with given percentage not found

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#7237]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

Podczas wykonywania GET /sale/offers/numer dostaję błąd:
Tax setting with given percentage not found.
trace-id: 44ba3da5019bb6a9

Mamy mnóstwo takich przypadków.

**Comment by MartaNowaczyk** [comment]
Potwierdzam, że były problemy po naszej stronie, naprawiliśmy i wszystko powinno już wracać do normy. Za utrudnienia przepraszamy.
