### ISSUE TITLE
Rozbieżność statusu przesyłki pomiędzy DPD a WzA

### ISSUE THREAD

**Issue by shivson1337** [allegro/allegro-api#7238]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**

Występują rozbieżności pomiędzy statusami w śledzeniu przesyłki pomiędzy oficjalną stroną DPD, a śledzeniem w API.

Przesyłka 1000611543121U zgodnie ze statusem na stronie DPD ma statusy:

![image](https://github.com/allegro/allegro-api/assets/60777356/4ee614be-1737-4e06-848a-0e2dfacf6feb)

zgodnie ze śledzeniem w WzA

![image](https://github.com/allegro/allegro-api/assets/60777356/d81281d3-dd31-4710-a9c0-064be15b33ba)

Z czego wynika ta rozbieżność? Wewnętrznie używamy systemu, który na podstawie statusów wykonuje akcje, a rozbieżność tego typu powoduje sporo problemów.

**Comment by MartaNowaczyk** [comment]
Sprawę przekazałam do odpowiedniego zespołu, który zajmuje się statusami przesyłek. Wrócę z informacją.

**Comment by MartaNowaczyk** [comment]
Sprawdziliśmy i takie statusy otrzymujemy od DPD, także jest to z naszej strony poprawne.

**Comment by shivson1337** [comment]
W porządku, podpytam DPD :)

 Dziękuję za szybką odpowiedź.

**Comment by shivson1337** [comment]
W porządku, podpytam DPD :)

Dziękuję za szybką odpowiedź.
