### ISSUE TITLE
Is it possible to display czech website when authorizing app with Allegro 

### ISSUE THREAD

**Issue by MERGADOengineer** [allegro/allegro-api#7239]
Dear Sir or Madam,
When authozing our application with client that is from Czech Republic, would it be 
possible to display allegro.cz variation of this site `https://allegro.pl/uzytkownik/bezpieczenstwo/skojarz-aplikacje?code=zcf72syu2`? 
It is inconvenient for czech customers having to authorize using polish website.

Thank you for reply and I am looking forward hearing from you.

**Comment by MartaNowaczyk** [comment]
Hello, Thank you for the notification. We are looking into the possibilities of solving this problem. I will get back with an update.
