### ISSUE TITLE
Brak możliwości korzystania z tagów w sandboksie

### ISSUE THREAD

**Issue by SylwesterZarebski** [allegro/allegro-api#7240]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Przy próbie skorzystania z tagów w sandboksie otrzymuję komunikat:
```
403 Forbidden

{
  "errors": [
    {
      "code": "USER_IS_NOT_ALLOWED_TO_USE_TAGS",
      "message": "You may not use tags (Your store is not in the Brands Zone, or you do not have an active subscription)",
      "details": "UserIsNotAllowedToUseTagsException",
      "path": "",
      "userMessage": "You may not use tags (Your store is not in the Brands Zone, or you do not have an active subscription)"
    }
  ]
}
```

Czy coś muszę jeszcze wykonać, poczekać itp.?

URL: https://api.allegro.pl.allegrosandbox.pl/sale/offer-tags
trace-id: `46248f4df42183b2`

#### Dodatkowe informacje:
Najpierw miałem błędy, więc zacząłem szukać po interfejsie WWW, co skierowało mnie do opcji abonament. Włączyłem więc abonament podstawowy, co na kilka minut pozwoliło odwołać się bez błędów do endpointów z tagami, ale niestety nie udało się dodać żadnego taga z interfejsu WWW, który nadal pokazywał błąd, a i tak po chwili problem również w API wrócił.

Przed włączeniem abonamentu w interfejsie WWW miałem informację, że nie ma tagów bez abonamentu lub strefy marek, a po włączeniu mam pustą listę tagów, nie da się dodać tagu, a w konsoli mam błędy typu:
https://edge.allegro.pl.allegrosandbox.pl/sale/offer-tags?user.id=105267283&limit=1500 -> `403`

Wywołania robię ręcznie w *Insomnia REST*.

**Comment by Lukasz-Zurek** [comment]
@SylwesterZarebski Konsultuję ten problem z zespołem odpowiedzialnym za tę funkcjonalność. Jak tylko uzyskam więcej informacji, wrócę ze szczegółami w tym wątku.

**Comment by SylwesterZarebski** [comment]
Dziękuję. Sprawdzę później.

**Comment by Lukasz-Zurek** [comment]
@SylwesterZarebski Czy sytuacja się poprawiła? Wg. logów ostatnia próba uzyskania informacji o tagach zakończyła się pomyślnie. Dodatkowo napisz proszę czy działa Tobie opcja do dodawania nowych tagów na [tej stronie](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/tagi-ofertowe)?

**Comment by SylwesterZarebski** [comment]
Dziękuję bardzo, wygląda na to, że tak w kwestii odczytu tagów, jeszcze nie próbowałem dodawać. Zamknę zgłoszenie zaraz po sprawdzeniu.

**Comment by SylwesterZarebski** [comment]
Potwierdzam, że obecnie tagi działają poprawnie. Dziękuję za pomoc.

**Comment by Lukasz-Zurek** [comment]
@SylwesterZarebski Dziękuję za potwierdzenie. Cieszę się, że sytuacja wróciła do normy.
