### ISSUE TITLE
 Not Found for url - /sale/product-offers/

### ISSUE THREAD

**Issue by HIYJOKOU** [allegro/allegro-api#7242]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

Przy próbie zacięgnięcia oferty otrzymuje:
Error occurred: 404 Client Error: Not Found for url: https://api.allegro.pl/sale/product-offers/{numer}
Oferta istnieje w asortymencie.
Pojawia się to do 22 na 924 ofert.
```
def get_auction_details(auction_number, key):
    url = f"https://api.allegro.pl/sale/product-offers/{auction_number}"

    headers = {
        "Authorization": f"Bearer {key}",
        "Accept": "application/vnd.allegro.public.v1+json"
    }

    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        data = response.json()

	//
	#some data i fetch for instance:
 	status = data["publication"]["status"]
	

	//


        return status

    except requests.exceptions.RequestException as e:
        print(f"Error occurred: {e}")

    return None
```

URL: https://api.allegro.pl/sale/product-offers/
trace-id: ```1b9778d0fa064e0f```

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz ponowić requesty? Czy problem nadal występuje?

**Comment by HIYJOKOU** [comment]
Tak, trace-id: 12a31e89e48a972e

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, analizujemy temat dalej.

**Comment by PrzemyslawLukanowski** [comment]
Wprowadziliśmy poprawkę - problem nie powinien już występować. Dziękuje jeszcze raz za zgłoszenie tego błędu.
