### ISSUE TITLE
Ustalanie rozmiaru etykiety

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#7243]
Witam, czy jest możliwość ustalenia rozmiarów etykiety, sposobu generowania PDF przy tworzeniu listu przewozowego za pomoca metody parcel-management/parcel-create-commands? Dla usługi odpowiadającej DHL czechy otrzymuję PDF zawierający etykietę natomiast zajmuje ona jedynie 1/4 strony, ponieważ pozostałe 3 części są puste - chciałbym to wyeliminować.

**Comment by Lukasz-Zurek** [comment]
Za pomocą wskazanego zasobu ustalisz jedynie format pliku etykiety. Natomiast format strony (w przypadku plików PDF): A4 lub A6 (kilka etykiet na jednej stronie), ustalisz podczas tworzenia etykiety, za pomocą [GET /parcel-management/parcels/label](https://developer.allegro.pl/documentation/#operation/getParcelLabel).
