### ISSUE TITLE
Wystawianie produktów błąd 403

### ISSUE THREAD

**Issue by patziom** [allegro/allegro-api#7244]
- [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X] inny / other

:beetle: **Opis / Description**

Mam problem z program pomagającym w sprzedaży na allegro (wystawia, monitoruje i wysyła dla klientów przedmioty), API stworzyłem tutaj "https://apps.developer.allegro.pl", aplikacja przekierowała mnie na stronę allegro "powiązane konta" w celu właśnie powiązania API z kontem, adres przekierowania mam jak twórca aplikacji zalecił: "http://localhost:8000". Wykonałem krok po kroku poradnik, przy próbie wystawienia oferty wyskakuje mi błąd jak na screenie na dole (Adding product in draft mode, Listing failed... 403), pisałem z tamtym supportem upewnili się czy wina nie leży po ich stronie, uważają, że nie, napisali: "Wygląda na to, że Twoje konto nie ma uprawnień do przesyłania produktów za pomocą interfejsu API.", następnie przekierowali mnie do allegro, a support allegro, przekierował mnie tutaj, od razu mówię, że nie jestem żadnym programistą ani kimś kto w tym siedzi, zanim zdecydowałem się tutaj napisać szukałem rozwiązania ale jak widać nie udało się, wiem, że wymagacie "środowisko, zasób, trace-id, commandId lub podaj pełne cURL z responsem i requestem" jednak bez jakiegoś nakierowania nie mam bladego pojęcia skąd to wziąć dodam jeszcze, że znajomy używa tej samej aplikacji od kilku miesięcy i problemów u niego takich nie było, pozdrawiam i liczę na pomoc.
SCREEN:
https://imgur.com/ufPjxOI

EDIT.
znalazłem kod który miał wyświetlić informacje na temat mojej aukcji po wprowadzeniu potrzebnych danych access_token, client_id itp. dostałem taką informacje zwrotną: 
Wystąpił błąd: 403 Client Error: Forbidden for url: https://api.allegro.pl/offers/listing

**Comment by AureliuszBrussy** [comment]
[GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) jest udostępniony tylko zweryfikowanym aplikacjom. Aby przejść proces weryfikacji skorzystaj z [formularza](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) lub skontaktuj ze swoim opiekunem jeśli jesteś w [Programie Partnerskim](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm) dla Sprzedających. Więcej informacji znajdziesz w [naszym newsie](https://developer.allegro.pl/news/get-offers-listing-tylko-dla-zweryfikowanych-aplikacji-GRax4oVgrs1).
