### ISSUE TITLE
Metoda dostawy jest niedostępna

### ISSUE THREAD

**Issue by piojoch** [allegro/allegro-api#7245]
Dzień dobry,
przy nadaniu paczki dostajemy błąd: Metoda dostawy jest niedostępna (VALIDATION_ERROR: Order delivery method: xxx is not allowed).

Dzieje się tak dla:
Allegro One Punkt
Allegro One Box
Allegro One Box, One Kurier - dostawa dzisiaj

Wszystkie 3 usługi są zwracane przez endpoint "parcel-management/delivery-services".

W jaki sposób nadać przesyłkę dla takich usług?

**Comment by AureliuszBrussy** [comment]
Proszę o przesłanie trace-id wywołania, gdzie zwracamy taki error. Trace-id znajdziesz w nagłówku response'a. Sprawdzę to dokładnie.

**Comment by piojoch** [comment]
API produkcyjne.

Poniżej kolejno trace-id dla poszczególnych metod:
af30719a3a1e55c8
e4784bdee8c4df76
46870893aecac066

**Comment by AureliuszBrussy** [comment]
Po analizie logów widzę, że wybierasz niepoprawne usługi dostawy. Skorzystaj dokładnie z tych, które dla danego zamówienia zwracamy w polu **delivery.method.id**. Wystarczy, że przy tworzeniu przesyłki w polu **serviceId** przekażesz id metody, które zwróciliśmy w zamówieniu.

**Comment by piojoch** [comment]
Czyli otrzymaliśmy błędne dane z systemu nadrzędnego. Dziękuję serdecznie za pomoc.

**Comment by piojoch** [comment]
A w jaki sposób osiągnąć to, żeby dla danego zamówienia w polu **delivery.method.id** były te 3 usługi które mnie interesują? Jak to wyklikać jak etapie tworzenia zamówienia i później podczas składania zamówienia?

**Comment by AureliuszBrussy** [comment]
Sprzedający musi udostępniać w cenniku dostawy podpiętym do danej oferty jedną z tych metod dostawy, a kupujący musi wybrać właśnie taką metodę dostawy. Wtedy możesz swobodnie generować przesyłki dla usługi.

**Comment by piojoch** [comment]
A czy jesteś w stanie mi wylistować jakie usługi są przypisane do tych zamówień które próbowałem nadać?

**Comment by piojoch** [comment]
Czyli:
Allegro One Punkt, One Kurier
Allegro One Box, One Kurier

Dziękuję
