### ISSUE TITLE
Problem z wystawianiem ofert na region Czeski

### ISSUE THREAD

**Issue by BartlomiejCalus** [allegro/allegro-api#7248]
Mamy problem z wystawianiem produktów na region Czeski. 
W odpowiedzi otrzymujemy błąd: 
"code":"VALIDATION_ERROR","message":"Platforms other than allegro.pl only support offers with a product linked.","details":"ConstraintViolationException.ForeignMarketplacesWithProductOnly","path":"null","userMessage":"Platforms other than allegro.pl only support offers with a product linked."

Trace id: bdce6a80cb6486f9
Id oferty: 10841398046

Cena i pola w publicaton.marketplaces.additional są ustawione

**Comment by PrzemyslawLukanowski** [comment]
Prócz pól, które wymieniłeś, warunkiem, aby oferta była widoczna w serwisie dodatkowym, jest to, aby była połączona z produktem. W Waszym przypadku tak nie jest - w polu `product` widnieje wartość null.

Korzystając z okazji, chciałbym przypomnieć, że zasoby /sale/offers/{offerID} oraz metodę POST na zasobie /sale/offers wyłączymy z końcem roku. Zachęcam do uwzględnienia w harmonogramie prac przejścia na zasoby /sale/product-offers. Szczegóły zmian znajdują się w [naszym newsie](https://developer.allegro.pl/news/na-poczatku-2024-roku-wylaczymy-zasoby-sale-offers-sluzace-do-tworzenia-i-edycji-ofert-BvqK3XOaEcW).

**Comment by BartlomiejCalus** [comment]
Dziękuję za odpowiedź. O nadchodzących zmianach wiemy już od jakiegoś czasu i pracujemy nad ich implementacją
