### ISSUE TITLE
Chciałbym wystawić produkt z kategorii 16027 w 13409

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#7249]
Dzień dobry,
Chciałbym wystawić produkt z kategorii 16027
"productSet":[{"product":{"id":"b9179929-b363-4b03-b127-f6973ac3d8f0"}}]
w podobnej kategorii (13409) aby zwiększyć możliwość sprzedaży.
Otrzymuję komunikat, że nowo wybrana kategoria nie zgadza się z kategorią istniejącego produktu.
Mam pytanie czy można to jakoś obejść?

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie, ofertę możesz wystawić wyłącznie w kategorii produktu lub kategorii podobnej, które zwracamy w polu `category.similar` w odpowiedzi [GET /sale/products/{productId}](https://developer.allegro.pl/documentation#operation/getSaleProduct).
