### ISSUE TITLE
Sandbox account activation

### ISSUE THREAD

**Issue by Mukoo19** [allegro/allegro-api#7250]
Hello,
I'm new to Allegro. I want to do an integration and want to test my application. I couldn't understand the sandbox idea. Can you give me a path to the testing process? Should I activate my account for Sandbox? Do I need to complete full account activation?

**Comment by PrzemyslawLukanowski** [comment]
Hello, Sandbox is a test environment where you can test all features without any fees - all payments are processed in a payment simulator. First, you need to [register a new, company account](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F) and [your application](https://apps.developer.allegro.pl.allegrosandbox.pl/). After that, let me know what is your login - I will fully activate your account. More information about Sandbox can be found in [our tutorial](https://developer.allegro.pl/tutorials/basic-information-VL6YelvVKTn#test-environment) (if you see the Polish version of this site, change the language settings in the top-right corner). You can also register a second, regular account, thanks to which you will be able to purchase items as a buyer. 
The most important features of Allegro are described [here](https://developer.allegro.pl/tutorials/the-most-important-allegro-processes-in-a-nutshell-v8W4kKeB6TY).

**Comment by Mukoo19** [comment]
Thank you for your quick response. I registered an account. My login is "Onreon". You can fully activate that account. I will check the documents.

**Comment by PrzemyslawLukanowski** [comment]
Are you sure you registered your account using the link above? We don't have a user called "Onreon" in the Sandbox environment. I see there's one on production, but here, on this forum, we activate accounts registered only in the Sandbox environment.

**Comment by Mukoo19** [comment]
When I click that link, an Allegro page appears as I showed you in the attachment. I couldn't sign up again because I've already have an account. 
![Ekran görüntüsü 2023-06-20 085811](https://github.com/allegro/allegro-api/assets/137067345/95d01ce6-a3b4-45e6-b6a9-7d0333d0351d)

**Comment by PrzemyslawLukanowski** [comment]
Please try to go to https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F or https://allegro.pl.allegrosandbox.pl/ and choose "Sign up". There's no redirection to allegro.pl on these links, so you should be able to register an account on Sandbox.

**Comment by Mukoo19** [comment]
This link works. I registered on Sandbox as Onreon. After you will fully activate my account can I use that account for testing?

**Comment by PrzemyslawLukanowski** [comment]
Yes, but it seems that there is still some missing data, could you please provide a bank account number and make a payment transfer (the bank account number doesn't have to be real and the payment will be processed via the payment simulator)? Please make sure that you have completed all the steps presented in the ["My account" ](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto)tab.

**Comment by Mukoo19** [comment]
How can I make a payment transfer with a non-real bank account? Also on the company verification side, it needs lots of documents related to the company. Should I add real documents?

**Comment by PrzemyslawLukanowski** [comment]
> How can I make a payment transfer with a non-real bank account? 

As I mentioned - payment will be processed by a payment simulator so it won't be a real transfer :) 

> Should I add real documents?

No, it could be any documents. In the link I sent you before, there's a rules for using a test version of Allegro API and point 11 is:

> Due to the nature and character of the Service do not provide real personal data in the forms.

**Comment by PrzemyslawLukanowski** [comment]
I have activated your account so you can start testing.
