### ISSUE TITLE
Mam kilka produktów do zaproponowania

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#7251]
Dzień dobry,
Mam kilka produktów do zaproponowania, (pałeczki mażoretkowe, mażoretkowe pompony)
Zauważyłem w dokumentacji, że używacie category-familiar.
Chciałbym przy okazji spytać, czy mogę je określić podczas proponowania produktu?

Byłoby fajnie gdybyście zrobili kategorię cheerleaderek/mażoretek w kategorii sporty towarzyskie.
Sprzedawcy z tej branży mają kłopoty z podawaniem odpowiednich kategorii podczas dodawania produktów.

**Comment by AureliuszBrussy** [comment]
Zbiór kategorii podobnych jest określony przez nas, nie ma możliwości jego samodzielnego zdefiniowana. Więcej o kategoriach podobnych pisaliśmy [w newsie](https://developer.allegro.pl/news/kategorie-podobne-wystaw-oferte-w-latwiejszy-sposob-6MvlYxj5MFV). 

Jeżeli chodzi o propozycję nowych podkategorii - prosiłbym, aby takie propozycje sprzedający przekazał poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). W ten sposób prośba taka trafi do odpowiedniego zespołu.
