### ISSUE TITLE
Ukryte oferty

### ISSUE THREAD

**Issue by Axlii50** [allegro/allegro-api#7252]
Witam

Mam pytanie odnośnie ukrytych ofert
czy ukryte oferty będą dalej widoczne dla api tzn. czy api dalej będzie je pobierało za pomocą zapytania pod adres 
"https://api.{environment}/sale/offers"

**Comment by AureliuszBrussy** [comment]
Oferty są ukrywane tylko w zakładce Mój asortyment, w API wciąż będziemy je zwracać.
