### ISSUE TITLE
Allegro One Box błąd komunikacji z przewoźnikiem

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#7253]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Od rana występują problemy z wygenerowaniem paczki w WzA na one box . 
Id : 75ed346e-25e5-444b-88a7-fc4c54ec33ac

**Comment by MartaNowaczyk** [comment]
Punkt jest już dostępny, więc spróbuj jeszcze raz nadać przesyłkę.

**Comment by paafcioc22** [comment]
Tak, udało się, ale przydałoby się zmienić komunikat. 
"błąd komunikacji z api przewoźnika" chyba tu nie pasuje.

**Comment by MartaNowaczyk** [comment]
OK, zgłoszę sugestię do zespołu odpowiedzialnego za tę usługę.

**Comment by MartaNowaczyk** [comment]
Komunikat powinien być poprawiony jeszcze w tym tygodniu.
