### ISSUE TITLE
WzA - problem z pobieraniem historii statusów przesyłki

### ISSUE THREAD

**Issue by lukasz-lopata** [allegro/allegro-api#7255]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - [ X] ze środowiskiem testowym / with the test environment

Witam, otrzymujemy zgłoszenia o błędach związanych ze śledzeniem przesyłki.

`Carrier id c3066682-97a3-42fe-9eb5-3beeccab840c is not allowed. Allowed carrier ids: [4PX_EXPRESS, ALLEGRO, AMBRO_EXPRESS, AUSTRIAN_POST_EXPRESS, AUSTRIAN_POST_REGISTERED, CAINIAO, CHINA_EMS, CHINA_POST, CHUKOU1, CNE_EXPRESS, DB_SCHENKER, DHL, DPD, DSV, DTS, ESHIPPING_GLOBAL, EXELOT, FEDEX, FLYT_EXPRESS, GEBRUDER_WEISS, GEIS, GLS, INPOST, JAPAN_POST, KARGOM_KOLAY, KN, LA_POSTE, LITHUANIAN_POST, MEEST, NA_DZISIAJ, NO_LIMIT, PACKETA, PICKPACK, POCZTA_POLSKA, POSTNORD, PTS, RABEN, RHENUS_LOGISTICS, RUCH, SFC, SF_EXPRESS, SHIPTER, SKYNET, SUNYOU, SUUS, TNT_EXPRESS, UKR_POSHTA, UPS, WANB_EXPRESS, WEDO, X_PRESS_COURIERS, YANWEN, YUN_EXPRESS, ZIGZAG]","details":null,"path":"/order/carriers/c3066682-97a3-42fe-9eb5-3beeccab840c/tracking","userMessage":"Identyfikator kuriera: c3066682-97a3-42fe-9eb5-3beeccab840c jest niedozwolony. Dopuszczalne identyfikatory kurierów to: [4PX_EXPRESS, ALLEGRO, AMBRO_EXPRESS, AUSTRIAN_POST_EXPRESS, AUSTRIAN_POST_REGISTERED, CAINIAO, CHINA_EMS, CHINA_POST, CHUKOU1, CNE_EXPRESS, DB_SCHENKER, DHL, DPD, DSV, DTS, ESHIPPING_GLOBAL, EXELOT, FEDEX, FLYT_EXPRESS, GEBRUDER_WEISS, GEIS, GLS, INPOST, JAPAN_POST, KARGOM_KOLAY, KN, LA_POSTE, LITHUANIAN_POST, MEEST, NA_DZISIAJ, NO_LIMIT, PACKETA, PICKPACK, POCZTA_POLSKA, POSTNORD, PTS, RABEN, RHENUS_LOGISTICS, RUCH, SFC, SF_EXPRESS, SHIPTER, SKYNET, SUNYOU, SUUS, TNT_EXPRESS, UKR_POSHTA, UPS, WANB_EXPRESS, WEDO, X_PRESS_COURIERS, YANWEN, YUN_EXPRESS, ZIGZAG]"`

Czy zmiana po stronie API była zamierzona? Nie znalazłem żadnej informacji o planowanych zmianach odnośnie śledzenia przesyłki, natomiast do tej pory funkcja działała bez problemu, ale wygląda na to, że od jakiegoś czasu zamiast ID powinniśmy przesyłać CarrierId. Czy powinniśmy wprowadzić zmiany, czy może znów się coś niedługo zmieni?

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Komunikat jest poprawny, czyli zgodnie z nim, jako {carrierId} należy wskazać ID wybranego przewoźnika (dostępne wartości sprawdzisz w odpowiedzi dla [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices)). Nie zmienialiśmy tego.
