### ISSUE TITLE
Dhl pobranie polska

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#7256]
Witam, chciałbym się upewnić co do danych zwracanych z API przy zasobie parcel-management/delivery-services. Czy jest usługa pozwalająca na obsługę DHL na terenie polski + pobranie? Jeśli tak to prosił bym o wskazanie ID

**Comment by MartaNowaczyk** [comment]
Mamy usługę "Kurier DHL pobranie", a do nadania takiej paczki niezbędna jest umowa własna. ID usługi zostanie zwrócone, jak dodasz umowę własną, bo ID składa się z ID metody + ID umowy własnej.
