### ISSUE TITLE
Packeta - zwroty

### ISSUE THREAD

**Issue by Pawelpwg** [allegro/allegro-api#7257]
na etykiety do czech Packeta, jest sekcja do podania adresu na zwroty (Zwroty kierowac do:), i moje pytanie jest skad ta informacja jest pobierana, w API nie widze takiej sekcji w obiekcie lub jest pod jakas inna nazwa. albo jest to pobierane z jakiegos zewnetrznego systemu?

**Comment by AureliuszBrussy** [comment]
Adres podany na etykiecie jest używany do zwrotów operacyjnych i jest to adres nadawcy podany przy generowaniu przesyłki.

**Comment by Pawelpwg** [comment]
no wlasnie w tym problem ze nie dokonca, etykieta u klienta ma inne adresy i to jeszcze pol biedy, ale adres do zwrotu jest bledny i to powoduje problem, nie zalaczam etykiety ze wzgledu na rodo

**Comment by AureliuszBrussy** [comment]
Musiałbym znać jakieś szczegóły. Może jesteś w stanie wskazać uuid komendy, pod którą została wygenerowana ta przesyłka? Możemy także spróbować to namierzyć po numerze przesyłki. Jeżeli nie chcesz podawać takich informacji tutaj, możesz je przekazać poprzez [formularz kontatkowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). W treści zgłoszenia wpisz numer wątku GitHub: #7257.

**Comment by Pawelpwg** [comment]
tutaj jesli link do etykiety
https://www.dropbox.com/s/h526wz4142uy38u/etykieta.jpg?dl=0

powycinalem dane klienta ale powinno byc widac o co chodzi, adres nadawcy jest cieszyn a zwrot to rzeszow 
jesli trzeba wiecej informacji to musze isc do klienta i u niego to wygenerowac

**Comment by Pawelpwg** [comment]
troche musze zmienic orginalne zapytanie, informacje z api sender trafiaja do sekcji zwroty na etykiecie, a teraz pytanie skad bierze sie nadawca na etykiecie (troche mylace to nazewnictwo;) )

**Comment by AureliuszBrussy** [comment]
Taki układ danych na etykiecie wynika z tego, jak obsługiwana jest ta przesyłka. Na terenie Polski przewozi ją Poczta Polska do polskiego magazynu Packety, a Packeta zajmuje się dostarczeniem jej na terenie Czech.
Dlatego na etykiecie “Adresatem” (z perspektywy Poczty) jest Packeta, a w dolnym prawym rogu nad numerem Poczty widnieje pole “Recipient”, które jest adresatem z perspektywy Packety.

**Comment by Pawelpwg** [comment]
moje pytanie jest o nadawwce, skad sa pobierane o nadawcy na etykiecie? sa pobierane z poczty poslkiej (chodz tutaj chyba nie ma powiazania) czy moze z jakis innych danych sprzedajacego na allegro

odbiorca to domyslilem sie tego dzialania jakie opisalem

**Comment by AureliuszBrussy** [comment]
Takie dane w polu "Nadawca" na etykiecie wynikają z umów i są stałe dla tej usługi. Każda etykieta w ramach usługi na ten moment ma właśnie taki stały adres. Nie jest on pobierany od sprzedającego.
