### ISSUE TITLE
Problem z zakończeniem oferty

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#7258]
Zakańczam oferty za pomocą PATCH /sale/product-offers/{offerId}. Przekazuję jedynie "publication": { "status": "ENDED" }

Integracja potwierdza, czy operacja została wykonana poprawnie za pomocą adresu otrzymanego w nagłówku **Location**

Problem w tym, że w przypadku gdy jest wystawiona wyłącznie 1 sztuka produktu i klient dokona zakupu, czyli oferta otrzyma parametr endedBy = EMPTY_STOCK, po wykonaniu powyższej operacji nie otrzymuję w nagłówku **Location**

Czy to normalna sytuacja, że nie otrzymuję adresu w **Location**? Nadmienię, że w innych przypadkach wszystko działa poprawnie

Podaję TraceId przykładowego zapytania, w którym wystąpiła dana sytuacja: 8b103cee8ceda7d6

**Comment by AureliuszBrussy** [comment]
Musisz zwrócić uwagę na status odpowiedzi. Jeżeli odpowiemy kodem 200 (tak jak w tym przypadku) oznacza to, że operacja została od razu wykonana, payload w odpowiedzi jest już wynikiem całej operacji i nie musisz już sprawdzać dodatkowo jej wyniku. Nagłówek Location zwrócimy tylko w przypadku, gdy operacja jest asynchroniczna, czyli gdy odpowiemy statusem 202. 

Odpowiedni schemat znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-oferty-w-asynchronicznym-api).

**Comment by mateuszcom** [comment]
Dziękuję, za informację - faktycznie moje niedopatrzenie :)
