### ISSUE TITLE
Wysyłam z Allegro

### ISSUE THREAD

**Issue by RenataWildeagle** [allegro/allegro-api#7261]
Chcemy zintegrować funkcję Wysyłam z Allegro z systemem magazynowym.
Mamy ścieżkę połączenia: Allegro -> Baselinker -> sklep internetowy EC -> ERP xl
Z xl trafiają informacje do "magazyniera", na których podstawie jest drukowana etykieta.

Programiści, którzy zajmują się integracją wciąż dopytują o:
delivery_method
i
delivery_method_id

Baselinker powiedział, że wszystkie te informacje ida przez API i oni nie mają listy takich informacji.

Gdzie można to sprawdzić?

W pierwszej kolejności chcemy uruchomić:
- Allegro One BOX i Punkt - obsługiwane przez UPS
- Allegro One dostawy dziś i jutro obsługiwane przez Allegro Kurier
- Kurier UPS
- UPS Punkt Odbioru

Czy jesteście w stanie podać dla każdej z tych metod (w opcjach płatność z góry i płatność za pobraniem) owe delivery methods i delivery_method_id przesyłane przez API Allegro (czyli co trafi ado Baselinker z Allegro i dalej jest zaciągane), żeby to odpowiednio zmapować po stronie EC i xl'a?

Przyznam, zże bardzo się gubię w tych Allegro ONE obsługiwanych przez UPS i Kuriera Allegro. Nikt nie potrafi mi tego prosto "rozrysować".

Mogę liczyć na Wszą pomoc tu?

Z pozdrowieniami
Renata

**Comment by AureliuszBrussy** [comment]
Proszę mapować metody dostawy po ich identyfikatorach (id). W zamówieniach zwracamy id wybranej przez kupującego metody dostawy (pole `delivery.method.id`). Odpowiednie usługi dostawy (`serviceId`) mają takie same id i można z nich skorzystać podczas nadawania przesyłek.

Można także odczytać dostępne w serwisie metody dostawy ([GET /sale/delivery-methods](https://developer.allegro.pl/documentation#operation/putSaleDeliverySettings)), sprawdzić, jakie udostępniamy jako sprzedawca w cenniku dostawy ([GET /sale/shipping-rates](https://developer.allegro.pl/documentation#tag/Delivery) oraz [GET /sale/shipping-rates/{id}](https://developer.allegro.pl/documentation#operation/getShippingRatesSetUsingGET)) i porównać ich id z dostępnymi w Wysyłam z Allegro usługami dostawy ([GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation#operation/getAvailableDeliveryServices)).
