### ISSUE TITLE
Sprawdzanie czy oferta jest SMART

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#7263]
Czy jest jakiś inny sposób na sprawdzenie czy oferta posiada oznaczenie SMART lub go nie posiada, niż GET /sale/offers/{offerId}/smart ? Potrzebuję wyfiltrować oferty,  które nie mają opcji SMART. Odpytywanie każdej oferty z osobna zajmuje ogrom czasu

**Comment by AureliuszBrussy** [comment]
Nie, nie udostępniamy innego sposobu sprawdzenia klasyfikacji SMART!.

**Comment by mateuszcom** [comment]
Napotkałem pewien problem, którego nie jestem w stanie wyeliminować. Korzystam z GET /sale/offers/{offerId}/smart (integracja sprawdza oferta po ofercie). Co kilkanaście iteracji wyskakuje błąd (odpowiedź przesyłam na końcu wiadomości). Moment pojawienia się błędu to istna loteria. Za każdym razem jest dla innej oferty. Raz przetworzy 100 ofert i pojawi się błąd, innym razem ponad 700. Proszę o nakierowanie gdzie szukać przyczyny.

`[kod błędu: 400]: {"errors":[{"code":"INCOMPLETE_OFFER","message":"Offer 13503113368 on marketplace allegro-pl is incomplete - missing data [marketplaceOfferDelivery]","details":null,"path":null,"userMessage":"Nieznany błąd"}]}`

**Comment by AureliuszBrussy** [comment]
Dziękuję za zgłoszenie, wyjaśniam to. Wrócę z odpowiedzią.

**Comment by mateuszcom** [comment]
Proszę o informację, czy coś wiadomo w kwestii mojego zgłoszenia?

**Comment by AureliuszBrussy** [comment]
Mamy do czynienia z błędem. Problem jest dość złożony i nie został jeszcze rozwiązany. Dam znać, jak tylko uda się wdrożyć poprawkę.
