### ISSUE TITLE
wysyłam z allegro + dpd baselinker

### ISSUE THREAD

**Issue by ewe1011** [allegro/allegro-api#7264]
Witam, wtyczka wysyłam z allegro w baselinker nie daje mi wygenerować listu przewozowego dpd wyskakuje komunikat: Wyskakujący błąd „problem z polem nr referencyjny”

**Comment by AureliuszBrussy** [comment]
Proszę o bezpośrednie zgłoszenie problemu do supportu Baselinkera - to z ich strony możemy otrzymać niezbędne dane do dokładniejszej weryfikacji.
