### ISSUE TITLE
Device flow - problem z uzyskaniem zasobów

### ISSUE THREAD

**Issue by KK2138** [allegro/allegro-api#7265]
Witam,
Rozpoczynam swoją przygodę z `allegro API` i próbuję przeprowadzić integrację w modelu `device flow`.
Zarejestrowałem aplikację, otrzymałem `client_id` oraz `client_secret`.
```
```
Z waszego poradnika wiem, że teraz muszę uzyskać `user_code i device_code` wykonuje polecenie:
```
curl -X POST 'https://allegro.pl/auth/oauth/device?client_id=tutaj moje client_id' 
-H 'Authorization:Basic(zaszyfrowane client_id:client_secret)' 
-H 'Content-Type: application/x-www-form-urlencoded'
```
I tu pojawia się problem i otrzymuję informację:
```
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (6) Could not resolve host: application
```

**Comment by AureliuszBrussy** [comment]
Popełniłeś błąd w swoim curl, więc request w ogóle nie został wysłany. Po komunikacie błędu mogę się domyślać, że być może chodzi o jakiś błąd w url, lub że przesyłasz jakiś dodatkowy parametr do sterowania portami.

**Comment by KK2138** [comment]
Całe polecenie skopiowałem z tego co podajecie czyli:
```
curl -X POST \
  'https://allegro.pl/auth/oauth/device?client_id={client_id}' \
  -H 'Authorization: Basic {base64(client_id:client_secret)}' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
```
I uzupełniłem własnymi danymi, tak więc zdaje mi się że url nie zostało zmienione jak równie nie przesyłam żadnych dodatkowych parametrów.

**Comment by AureliuszBrussy** [comment]
Sprawdziłem takiego curla po swojej stronie i nie napotykam podobnych problemów. Możesz także spróbować zmienić nieco formatowanie, np.:

```
curl --location --request POST 'https://allegro.pl/auth/oauth/device?client_id={client_id}' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic {base64(client_id:client_secret)}' \
```

**Comment by KK2138** [comment]
Odpowiedź się powtarza:
```
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (6) Could not resolve host: application
```

Zauważyłem że w składni Authorization: Basic miałem Authorization:Basic po poprawieniu polecenia otrzymuje:
```
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) URL rejected: Bad hostname
curl: (6) Could not resolve host: application
```

Tak więc czy mogę uzyskać polecenie uzupełnione przykładowymi danymi? Może mam jeszcze jakiś błąd w związku z np. () {} itd? A jeśli to nie błąd składniowy to co może być problemem?

**Comment by AureliuszBrussy** [comment]
Uzupełniony curl (fikcyjny client_id i client_secret):

```
curl --location --request POST 'https://allegro.pl/auth/oauth/device?client_id=0f74305687a45bd2a729e68a57edcf25' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic MGY3NDMwNTY4N2E0NWJkMmE3MjllNjhhNTdlZGNmMjU6ZHpmamthempublJkVmZ6M2xFNUhSZGZXa21EMHZnSE4zWTEzZTRDUWhWaFRyaWxKd3BFeFFnTVJ4bXJsZnpjTQ=='
```

Tak jak wspomniałem, nie udało mi się powtórzyć Twojego problemu, nie wiem też, w jakich dokładnie warunkach wysyłasz curl.

**Comment by KK2138** [comment]
Tak jak sądziłem pojawił mi się jeszcze jakiś błąd składniowy tak czy siak po skopiowaniu twojego polecenia i zastąpieniu `client_id` i `client_secret` wysykakuje mi jeszcze więcej błędów:
```
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (6) Could not resolve host: application
curl: (6) Could not resolve host: Basic
curl: (3) URL rejected: Bad hostname
```

**Comment by AureliuszBrussy** [comment]
@KK2138 czy wykonujesz ten curl w wierszu poleceń (Windows), a może w powłoce (Unix)?

**Comment by KK2138** [comment]
W wierszu poleceń Windows

**Comment by AureliuszBrussy** [comment]
To spróbuj w ten sposób (inny escape character dla wieloliniowej komendy):

```
curl --location --request POST https://allegro.pl/auth/oauth/device?client_id=0f74305687a45bd2a729e68a57edcf25 ^
--header "Content-Type: application/x-www-form-urlencode" ^
--header "Authorization: Basic MGY3NDMwNTY4N2E0NWJkMmE3MjllNjhhNTdlZGNmMjU6ZHpmamthempublJkVmZ6M2xFNUhSZGZXa21EMHZnSE4zWTEzZTRDUWhWaFRyaWxKd3BFeFFnTVJ4bXJsZnpjTQ=="
```

**Comment by KK2138** [comment]
Informacja zwrotna: 
```
{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/auth/oauth/device","userMessage":null}]}
```

**Comment by AureliuszBrussy** [comment]
Udało Ci się wysłać request i to faktycznie odpowiedź z naszego serwisu. Upewnij się, czy nie masz żadnych błędów w znakach, np. `"` lub czy nie popełniasz jakiś błędów w kodowaniu base64. Metodą prób i błędów powinieneś dość do rozwiązania.

**Comment by KK2138** [comment]
Okej bardzo dziękuje za pomoc, postaram się dojść do błędu

**Comment by KK2138** [comment]
@AureliuszBrussy Przepraszam za kłopot jednak dalej potrzebuje pomocy, nie mogę znaleźć tego błędu, dane które wprowadzam i `"` wydają się być w porządku. W szczególności `"` ponieważ skopiowałem twoje polecenie i zastąpiłem moimi danymi.
Co do szyfrowania szyfruje same `client_id:client_secret` bez nawiasów itp.` client_id` i `client_secret` na pewno podaje dobre więc zdaje mi się że to również nie problem w szyfrowaniu

**Comment by AureliuszBrussy** [comment]
Już widzę w czym rzecz - w literówce w linii `--header "Content-Type: application/x-www-form-urlencode" ^`. 

Powinno być:  `--header "Content-Type: application/x-www-form-urlencoded" ^`.

Poprawna wersja całości:

```
curl --location --request POST https://allegro.pl/auth/oauth/device?client_id=0f74305687a45bd2a729e68a57edcf25 ^
--header "Content-Type: application/x-www-form-urlencoded" ^
--header "Authorization: Basic MGY3NDMwNTY4N2E0NWJkMmE3MjllNjhhNTdlZGNmMjU6ZHpmamthempublJkVmZ6M2xFNUhSZGZXa21EMHZnSE4zWTEzZTRDUWhWaFRyaWxKd3BFeFFnTVJ4bXJsZnpjTQ=="
```

**Comment by KK2138** [comment]
TAK! Działa, jeszcze raz dziękuje za pomoc i cierpliwość! Jesteś wielki
