### ISSUE TITLE
Problem ze zmianą tytułu w ogłoszeniu

### ISSUE THREAD

**Issue by Hornir91** [allegro/allegro-api#7266]
Dzień dobry.

Mam problem ze zmianą tytułu poprzez API w kilku ogłoszeniach.
Sprawa wygląda tak, że pobieram ogłoszenie i dostaję JSON-a. Modyfikuję wyłącznie jeden parametr - name, po czym wysyłam ogłoszenie z powrotem na adres /sale/product-offers/{id} metodą PATCH.

Parametr name posiada mniej niż 50 znaków oraz nie zawiera znaków specjalnych.

Przykładowe ID ogłoszeń, których dotyczy problem: 13770812718, 13826782263.

Większość ogłoszeń, które modyfikuję w ww. sposób przechodzi bez problemu, natomiast z tymi dwoma mam problem.

Mógłbym dowiedzieć się dlaczego Wasz serwis ich nie przepuszcza?

**Comment by AureliuszBrussy** [comment]
Prosiłbym o przesłanie przykładowego trace-id wywołania - znajdziesz go w nagłówku naszego response'a z błędem. Czy komunikat błędu mówi coś o problemach ze zmianą wartości w polu name?

**Comment by Hornir91** [comment]
trace-id: f7e13f8d8d3a0bbd

Pogrzebałem trochę w curlu i udało mi się uzyskać dodatkowe informacje.

_{"errors":[{"code":"GallerySizeException","message":"Unprocessable Entity","details":null,"path":"images","userMessage":"The limit of 16 images has been exceeded."}]}_

Ogłoszenia te posiadają więcej niż dopuszczalny limit 16 zdjęć. 

Czy w tym przypadku pomoże wysłanie ogłoszenia ze zmienionym tytułem, ale bez zdjęć i czy ewentualnie nieprzesłanie ponownie zdjęć spowoduje usunięcie dotychczasowych z ogłoszenia, zgodnie z zasadą "Wszystko albo nic"?

**Comment by AureliuszBrussy** [comment]
PATCHem możesz wysłać request tylko z polem `name` w payloadzie. W ten sposób zmienisz tylko wartość w `name`. "Wszystko albo nic" dotyczy tylko jawnie wysłanych tablic - czyli jeżeli wysyłasz tablicę taką jak `images`, to powinieneś wysłać całą wcześniejszą zawartość, jeżeli nie chcesz jej edytować.

**Comment by Hornir91** [comment]
Niestety nie mogę edytować samego parametru name, gdyż otrzymuję błąd:

{"errors":[{"code":"ImpliedWarrantyNotDefinedException","message":"Unprocessable Entity","details":null,"path":"afterSalesServices.impliedWarranty","userMessage":"The user does not have any Complaints Terms."}]}.

Na koncie faktycznie nie ma dodanych warunków reklamacji, tylko czy w przypadku wystawiania wyłącznie ogłoszeń, są one potrzebne? Konto istnieje 4 lata i dotychczas nie było problemów z wystawianiem ogłoszeń.

Dodam, iż do wystawiania ogłoszeń korzystamy jeszcze ze starego endpointu sale/offers/{id}, a jedynie skrypt do modyfikacji tytułów korzysta już z nowego adresu sale/product-offers/{id}.

**Comment by AureliuszBrussy** [comment]
Wyjaśniam to. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
Potwierdzam bug. Pracujemy nad poprawką.

**Comment by Hornir91** [comment]
Dziękuję za odpowiedź. 

Proszę o informację, gdy błąd zostanie naprawiony.

Pozdrawiam.
