### ISSUE TITLE
Payment Requested from Allegro Sandbox

### ISSUE THREAD

**Issue by danielev-qapla** [allegro/allegro-api#7267]
Hello,
I recently received an e-mail from the Allegro Sandbox environment. This e-mail has another e-mail as attachment where a payment is requested to continue using Allegro Sandbox (about 5.00 PLN).

Is there anything that I should do or should I just ingnore this kind of e-mail ? My account's name is QaplaSandbox.

Thanks in advance.

Regards,
Daniele
----------------------
Full Stack Developer @Qapla'

**Comment by AureliuszBrussy** [comment]
No, of course you don't have to pay anything, charging is simulated and does not involve real costs. 

Use the transfer simulator in the "[Settlements with Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro)" tab. The transfer made will not be real, while you will no longer have information about the debt. You can also just ignore this email.

**Comment by danielev-qapla** [comment]
Ok, thanks!
