### ISSUE TITLE
Zły format daty

### ISSUE THREAD

**Issue by LukaszWypych** [allegro/allegro-api#7268]
Dzień dobry,
podczas pobierania oferty w polu validatedAt otrzymuje datę w błędnym formacie (nie jest to poprawny format iso) , przez co nie udaje się deserializacja obiektu. Ten format występuje tylko na niektórych aukcjach, dla reszty jest to poprawny format np. "2023-04-11T07:52:28.033Z".

id oferty: 13623617115
trace-id: f853c01b224ed580
`
"validation": {
        "errors": [
        ],
        "validatedAt": "2023-06-22T11:52:33.894+02",
        "warnings": [
        ]
    }
`

**Comment by MartaNowaczyk** [comment]
Zespół odpowiedzialny za usługę weryfikuje opisaną sytuację. Wrócę z informacją.

**Comment by MartaNowaczyk** [comment]
Poprawiliśmy ten błąd we wszystkich ofertach, w których występował oraz wdrożyliśmy poprawkę, by problem nie występował w przyszłości. Dzięki za zgłoszenie i przepraszamy za problemy.
