### ISSUE TITLE
Sandbox autoryzacja Authorization Code flow - błąd 403 (Próba otwarcia strony została zablokowana) podczas autoryzacji (pobierania tokenów)

### ISSUE THREAD

**Issue by kubinho1032** [allegro/allegro-api#7269]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [X] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Witam,
Mam problem z autoryzacją przy pomocy Authorization Code flow.
1. Przenoszę użytkownika na https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id={ClientId}&redirect_uri={RedirectUrl}&scope={scopes}
2. Otrzymuje poprawny kod
3. Wysyłam żądanie POST na adres: https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=authorization_code&code={code}&redirect_uri={RedirectUrl}
W żądania załączam nagłówek: "Authorization: Basic base64(clientId:clientSecret)"

4. W odpowiedzi dostaję status 403 (Forbidden) z treścią:
```
 Próba otwarcia strony została zablokowana
 Coś poszło nie tak.
 Jeżeli sytuacja się powtarza, to zgłoś ten przypadek obsłudze klienta załączając kod błędu.
 Pomoże nam to w szybszym rozwiązaniu Twojego problemu.
```
Czasem treść jest następująca:
`Please enable JS and disable any ad blocker`

Dodam, że próbuję zalogować się tym samym kontem, na którym zarejestrowana jest aplikacja (w celu uzyskania ClientId oraz ClientSecret).

Jakie mogą być potencjalne przyczyny takiego działania?
Z góry dziękuje za odpowiedź

**Comment by AureliuszBrussy** [comment]
Upewnij się, czy w kroku nr 3 przesyłasz prawidłowy RedirectUrl, zgodny z tym wprowadzonym w [Developer Apps (Sandbox)](https://apps.developer.allegro.pl.allegrosandbox.pl/). Podaj także kod, który zwróciliśmy razem z odpowiedzią 403 (o którym piszemy w komunikacie). Spróbuję to namierzyć.

**Comment by kubinho1032** [comment]
RedirectUrl wygląda ok, są to następujące adres (dane wrażliwe wykropokowane):
1. URL dla użytkownika: https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=....&redirect_uri=https://example.127.0.0.1.nip.io:7225/allegro&scope=allegro:api:profile:read%20allegro:api:ratings

2. URL autoryzacji: https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=authorization_code&code=...&redirect_uri=https://example.127.0.0.1.nip.io:7225/allegro

Kod błędu jest niestety pusty.
Załączam zrzut z odpowiedzią w postaci HTML'a .
![403_error](https://github.com/allegro/allegro-api/assets/17827265/734d6cf6-608a-40ce-9aca-c0ef4d62756f)

Czy wymagane są jakieś nagłówki w żądania do endpoint'u "auth/oauth/token" poza autoryzacyjnym?
Z góry dzięki :)

**Comment by AureliuszBrussy** [comment]
Wyjaśniam to z jednym z naszych zespołów. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@kubinho1032 póki co nie znaleźliśmy wyjaśnienia. Prześlij proszę przykładowy timestamp, gdzie zwróciliśmy błąd o którym piszesz w wątku. Dla pewności prześlij proszę także pełen request z uzupełnionymi parametrami oraz nagłówkami, najlepiej w formacie curl. Prześlij proszę te dane [w formularzu](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) kontatkowym, w treści podając numer zgłoszenia GitHub: #7269.

**Comment by kubinho1032** [comment]
Przesłałem dane poprzez formularz.
Z góry dziękuje :)

**Comment by AureliuszBrussy** [comment]
Problem jest z wykorzystanym redirect_uri - nie możesz korzystać z adresu tzw. “loopback”, czyli 127.x.x.x. Zmiana adresu przekierowania powinna rozwiązać problem.

**Comment by kubinho1032** [comment]
Ok, dzięki za informację.
Sprawdzę i dam znać :)

**Comment by kubinho1032** [comment]
> Problem jest z wykorzystanym redirect_uri - nie możesz korzystać z adresu tzw. “loopback”, czyli 127.x.x.x. Zmiana adresu przekierowania powinna rozwiązać problem. Możesz korzystać wyłącznie z adresów domenowych, publicznych adresów IP oraz localhost.

Zmiana RedirectUrl na "localhost" pomogła.
Dzięki bardzo za pomoc :)

**Comment by tomsyty** [comment]
Dzień dobry, podepnę się pod temat ponieważ mam identyczny problem, przy czym nie jestem w stanie pokazać zrzutu z odpowiedzią w formie HTML, ponieważ jest to aplikacja w formie rozszerzenia do przeglądarki Chrome, korzystam z API chrome.identity.launchWebAuthFlow które tworzy nowe okno autoryzacji dla podanego URLa (wyświetla stronę "Potwierdź swoje konto" z nazwą użytkownika i przyciskami "Zmień konto / Kontynuuj") jednak jest ono automatycznie zamykane po otrzymaniu parametru code na adres redirect_uri więc nie jestem w stanie powiedzieć czy i co jest wyświetlane jak u kolegi wyżej. W kolejnym kroku wysyłane jest żądanie pobrania tokena z użyciem otrzymanego kodu które skutkuje błędem 403 z pustym kodem błędu. Ten sam kod programu wykorzystuję w logowaniu na normalne konto (jedynie podstawiając odpowiednie wartości zmiennych do URLa) i wszystko działa jak należy, adres przekierowania i scopy są w obu przypadkach te same, różne są jedynie Client ID i Client Secret, czyli u mnie problemem nie będzie redirect_uri bo ten działa dla normalnego konta. Ten sam kod używałem kilka miesięcy temu do logowania na Sandboxa i działało, miałem jednak przerwę w używaniu Sandboxa przez jakiś czas i zablokowane konto testowe z powodu nieuregulowanego "wirtualnego" rachunku, zastanawiam się czy to może mieć wpływ, choć mam też aplikację w której wykorzystuję Device Flow i na niej mogę się zalogować na to konto, więc podejrzewam że to nie to... Najlepiej chyba jakbym przesłał cURL do sprawdzenia?

**Comment by AureliuszBrussy** [comment]
@tomsyty podeślij proszę przykład w postaci curl oraz login konta. Spróbujemy to sprawdzić. Jeżeli nie chcesz tego robić tutaj, możesz skorzystać z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b&kategoria=4b0096d8-57bf-4af7-9a40-81c273a69423), w treści podając numer wątku na GitHubie: #7269.

**Comment by tomsyty** [comment]
Przesłałem przez formularz, dziękuję.

**Comment by AureliuszBrussy** [comment]
@tomsyty dziękuję za informację, zweryfikuję to i wrócę z wiadomością jak coś ustalę.
