### ISSUE TITLE
WZA - złe wymiary InPost Kurier

### ISSUE THREAD

**Issue by skmaksio** [allegro/allegro-api#7270]
Dzień dobry,

Otrzymuje error przy WZA, że są za duże wymiary. Według wytycznych InPost, są to wymiary dopuszczone do wysyłki jako standard.

Wymiary jakie przesyłam:
[dimensions] => Array
                                (
                                    [height] => Array
                                        (
                                            [value] => 120
                                            [unit] => CENTIMETER
                                        )

                                    [width] => Array
                                        (
                                            [value] => 10
                                            [unit] => CENTIMETER
                                        )

                                    [depth] => Array
                                        (
                                            [value] => 10
                                            [unit] => CENTIMETER
                                        )

                                )

Response:
Array
(
    [id] => 2d86d01a-a47b-5f69-7c59-d3ce5bda1f7e
    [parcelId] => 
    [status] => ERROR
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => DIMENSIONS_VALIDATION_ERROR
                    [message] => These dimensions exceed the limit of 80 x 80 x 80 cm
                    [details] => Package dimension limit exceeded
                    [path] => items.dimensions
                    [userMessage] => Podane wymiary wykraczają poza limit 80 x 80 x 80 cm
                )

        )

)

**Comment by AureliuszBrussy** [comment]
Rozpoznałem temat - widzę, że nadanie próbujesz zrealizować poza ofertą Allegro InPost (tam max. długość boku to właśnie 80cm). 

InPost natomiast aktualnie faktycznie informuje, że dla przesyłki standardowej najdłuższy bok może mieć 120cm. Zgłosiłem tą sprawę do zespołu odpowiedzialnego za Wysyłam z Allegro. Będą teraz wyjaśniać kwestię wymiarów. Nie jestem natomiast w stanie podać informacji, kiedy sprawa zostanie rozwiązana. Na teraz pozostaje wygenerowanie przesyłki o takich wymiarach poza Wysyłam z Allegro.
