### ISSUE TITLE
Problem z wystawieniem oferty - EAN

### ISSUE THREAD

**Issue by Kuba-Id** [allegro/allegro-api#7271]
Mimo podania prawidłowego EAN'u przy wystawianiu oferty, API zwraca informację i błędach walidacyjnych - że jest on nieprawidłowy. Błąd:
_**"Niepoprawna wartość parametru EAN/ISBN/ISSN (225693) dla produktu w ofercie. Prawidłowa wartość parametru dla produktu to: "5900000100692, 8590816037588, 9623752348759"."**_

Przekazywana wartość dla EANu którego dotyczy błąd to: **8590816037588**- czyli taka jaka powinna być.
Co może być nie tak?

Wystawianie oferty odbywa się poprzez zasób: "https://api.allegro.pl/sale/offers"

**Request:**

stdClass Object
(
    [name] => Lampa tylna AUTHOR Caddy 3 na bagażnik
    [publication] => Array
        (
            [duration] => 
        )
    [sellingMode] => Array
        (
            [format] => BUY_NOW
            [price] => Array
                (
                    [amount] => 36.99
                    [currency] => PLN
                )
            [startingPrice] => Array
                (
                    [amount] => 36.99
                    [currency] => PLN
                )
        )
    [tax] => Array
        (
            [percentage] => 23.00
        )
    [stock] => Array
        (
            [available] => 60
            [unit] => UNIT
        )
    [delivery] => Array
        (
            [handlingTime] => P4D
            [shippingRates] => Array
                (
                    [id] => e5e4021b-0380-430a-90fe-ff531b63ae49
                )
        )
    [payments] => Array
        (
            [invoice] => VAT
        )
    [afterSalesServices] => Array
        (
            [impliedWarranty] => Array
                (
                    [id] => 0043be2e-7195-40d9-a900-25353ba86beb
                )
            [returnPolicy] => Array
                (
                    [id] => e6c74c39-6ccb-4bb9-960e-b72aeccd019a
                )
            [warranty] => Array
                (
                    [id] => fe857451-913d-4443-baab-928ce2c33f5c
                )
        )
    [discounts] => Array
        (
            [wholesalePriceList] => Array
                (
                    [id] => 5f899921-a90b-41a4-90ae-f81cf20a534b
                )
        )
    [location] => Array
        (
            [countryCode] => PL
            [province] => WIELKOPOLSKIE
            [city] => Poznań
            [postCode] => 61-007
        )
    [category] => stdClass Object
        (
            [id] => 16427
        )
    [parameters] => Array
        (
            [0] => Array
                (
                    [id] => 203725
                    [values] => Array
                        (
                            [0] => 50
                        )
                    [valuesIds] => 
                    [rangeValue] => 
                    [valuesLabels] => Array
                        (
                            [0] => Czas pracy
                        )
                )
            [1] => Array
                (
                    [id] => 225693
                    [values] => Array
                        (
                            [0] => 8590816037588                           
                        )
                    [valuesIds] => 
                    [rangeValue] => 
                    [valuesLabels] => Array
                        (
                            [0] => EAN (GTIN)
                        )
                )
            [2] => Array
                (
                    [id] => 224017
                    [values] => Array
                        (
                            [0] => 11-12-039141
                        )

                    [valuesIds] => 
                    [rangeValue] => 
                    [valuesLabels] => Array
                        (
                            [0] => Kod producenta
                        )
                )
            [3] => Array
                (
                    [id] => 205826
                    [rangeValue] => 
                    [values] => 
                    [valuesIds] => Array
                        (
                            [0] => 205826_1041835
                        )
                )
            [4] => Array
                (
                    [id] => 213914
                    [values] => Array
                        (
                            [0] => 1
                        )
                    [valuesIds] => 
                    [rangeValue] => 
                    [valuesLabels] => Array
                        (
                            [0] => Liczba trybów świecenia
                        )
                )
            [5] => Array
                (
                    [id] => 213674
                    [rangeValue] => 
                    [values] => 
                    [valuesIds] => Array
                        (
                            [0] => 213674_261974
                        )
                )

            [6] => Array
                (
                    [id] => 237206
                    [values] => Array
                        (
                            [0] => Caddy 3
                        )
                    [valuesIds] => 
                    [rangeValue] => 
                    [valuesLabels] => Array
                        (
                            [0] => Model
                        )
                )
            [7] => Array
                (
                    [id] => 9128
                    [rangeValue] => 
                    [values] => 
                    [valuesIds] => Array
                        (
                            [0] => 9128_20
                        )
                )
            [8] => Array
                (
                    [id] => 11323
                    [rangeValue] => 
                    [values] => 
                    [valuesIds] => Array
                        (
                            [0] => 11323_1
                        )
                )
            [9] => Array
                (
                    [id] => 229205
                    [rangeValue] => 
                    [values] => 
                    [valuesIds] => Array
                        (
                            [0] => 229205_340245
                        )

                )

            [10] => Array
                (
                    [id] => 202217
                    [values] => Array
                        (
                            [0] => 1
                        )

                    [valuesIds] => 
                    [rangeValue] => 
                    [valuesLabels] => Array
                        (
                            [0] => Strumień świetlny
                        )

                )

            [11] => Array
                (
                    [id] => 213882
                    [rangeValue] => 
                    [values] => 
                    [valuesIds] => Array
                        (
                            [0] => 213882_264394
                        )

                )

            [12] => Array
                (
                    [id] => 213902
                    [rangeValue] => 
                    [values] => 
                    [valuesIds] => Array
                        (
                            [0] => 213902_1
                            [1] => 213902_2
                        )

                )

            [13] => Array
                (
                    [id] => 213886
                    [rangeValue] => 
                    [values] => 
                    [valuesIds] => Array
                        (
                            [0] => 213886_264414
                        )

                )

            [14] => Array
                (
                    [id] => 420
                    [valuesIds] => 
                    [values] => Array
                        (
                            [0] => 300
                        )

                    [rangeValue] => 
                )

        )

    [images] => Array
        (
            [0] => Array
                (
                    [url] => https://a.allegroimg.com/original/111fbf/050262ae40439d0272a0340d6655
                    [description] => 
                )

        )

    [description] => Array
        (
            [sections] => Array
                (
                    [0] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => TEXT
                                            [content] => <h1>Lampa tylna AUTHOR Caddy 3 na bagażnik</h1>
                                        )

                                )

                        )

                    [1] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => IMAGE
                                            [url] => https://a.allegroimg.com/original/111fbf/050262ae40439d0272a0340d6655
                                        )

                                )

                        )

                    [2] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => TEXT
                                            [content] => <h1>Opis</h1><p><b>Lampa tylna AUTHOR Caddy 3 na bagażnik</b></p><ul><li>Lampa diodowa z odblaskiem.</li><li>Posiada 3 diody LED Hi-Intense oraz duży panel odblaskowy zapewniający doskonałą widoczność pod kątem 180 stopni.</li><li>Montowana na bagażniku za pomocą 2 śrub M5 (rozstaw: 80 mm).</li><li>Tryb świecenia ciągły.</li><li>Czas świecenia - 50 godz.</li><li>Zasilanie: 2 baterie LR-03 (AAA) znajdujące się w zestawie.</li></ul>
                                        )

                                )

                        )

                    [3] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => IMAGE
                                            [url] => https://a.allegroimg.com/original/111fbf/050262ae40439d0272a0340d6655
                                        )

                                    [1] => Array
                                        (
                                            [type] => TEXT
                                            [content] => <h1>Specyfikacja</h1><p><b>Czas pracy</b>: 50</p><p><b>Kod producenta</b>: 11-12-039141</p><p><b>Kolor dominujący</b>: pomarańcze i czerwienie</p><p><b>Liczba trybów świecenia</b>: 1</p><p><b>Marka</b>: Author</p><p><b>Model</b>: Caddy 3</p><p><b>Rodzaj</b>: tylne</p><p><b>Stan</b>: Nowy</p><p><b>Stan opakowania</b>: oryginalne</p><p><b>Strumień świetlny</b>: 1</p><p><b>Zasilanie</b>: bateria</p><p><b>Zawartość zestawu</b>: baterie, lampka</p><p><b>Źródło światła</b>: dioda LED</p>
                                        )

                                )

                        )

                )

        )

    [product] => stdClass Object
        (
            [id] => 78407991-387a-446a-bedf-60a4727fb466
        )

)`

**Response:**
 [validation] => stdClass Object
        (
            [errors] => Array
                (
                    [0] => stdClass Object
                        (
                            [code] => VALIDATION_ERROR
                            [message] => Incorrect value of the EAN/ISBN/ISSN (225693) parameter for the offered product. The correct parameter value for the product is: "5900000100692, 8590816037588, 9623752348759".
                            [details] => 
                            [path] => 
                            [userMessage] => Niepoprawna wartość parametru EAN/ISBN/ISSN (225693) dla produktu w ofercie. Prawidłowa wartość parametru dla produktu to: "5900000100692, 8590816037588, 9623752348759".
                        )

                    [1] => stdClass Object
                        (
                            [code] => VALIDATION_ERROR
                            [message] => Provided EAN (GTIN) code is incorrect
                            [details] => 
                            [path] => parameters
                            [userMessage] => Nieprawidłowa długość parametru EAN (GTIN). Dopuszczalna długość to 8, 10, 12, 13 lub 14 znaków.
                        )

                    [2] => stdClass Object
                        (
                            [code] => VALIDATION_ERROR
                            [message] => Value is too long in parameter (225693)
                            [details] => 
                            [path] => parameters
                            [userMessage] => Zbyt długa wartość dla parametru EAN (GTIN) (225693).
                        )

                )

            [warnings] => Array
                (
                    [0] => stdClass Object
                        (
                            [code] => VALIDATION_WARNING
                            [message] => Czy wiesz, że dodając metody eksportowe do swoich ofert, możesz trafić do większej grupy klientów? Nie czekaj, dodaj metody eksportowe już teraz i zwiększ swoją sprzedaż. Upewnij się, że produkt posiada wymagane oznakowanie w języku urzędowym kraju, do którego zostanie dostarczony.
                            [details] => 
                            [path] => name
                            [userMessage] => Czy wiesz, że dodając metody eksportowe do swoich ofert, możesz trafić do większej grupy klientów? Nie czekaj, dodaj metody eksportowe już teraz i zwiększ swoją sprzedaż. Upewnij się, że produkt posiada wymagane oznakowanie w języku urzędowym kraju, do którego zostanie dostarczony.
                        )

                )

            [validatedAt] => 2023-06-23T10:53:25.806Z
        )

**Trace ID:** 64970d12cb477491

Będę wdzięczny za sugestię, dlaczego nie mogę wystawić oferty.
Z góry dziękuję!

**Comment by MartaNowaczyk** [comment]
Wygląda na to, że wraz z kodem EAN przesyłasz jeszcze puste znaki, stąd błąd dotyczący długości i błędnego kodu EAN
`8590816037588                           `

**Comment by hahyes** [comment]
Sprawdź, czy przypadkiem nie wysyłasz jakiegoś specjalnego lub ukrytego znaku. Przy kopiowaniu danych z katalogów czy stron internetowych czasami zdarzają się takie przypadki, że są jakieś ukryte znaczki niewidoczne na pierwszy rzut oka.

**Comment by Kuba-Id** [comment]
Super, dziękuję! To było to. Temat rozwiązany!
