### ISSUE TITLE
Error number: 5faee13778b6573f

### ISSUE THREAD

**Issue by Ashutoshgopal** [allegro/allegro-api#7273]
![IMG-20230622-WA0000](https://github.com/allegro/allegro-api/assets/137510026/4a242ab8-49d4-4de2-8402-ba1c763d70c9)

Hi there,
We're trying to authorise the API access and getting the error it says "We can display the page" it would be great if you can help us to get rid of the error and get authorisation code so that we can get the access token and start accessing all the endpoint.

Thanks

**Comment by MartaNowaczyk** [comment]
Hello, your redirect_uri is invalid. Make sure that the address you provided in redirect_uri is the same as the one you provided, when you registered the application. You can check and edit redirection addresses on page https://apps.developer.allegro.pl/.
