### ISSUE TITLE
Błąd podczas próby pobrania wszystkich produktów użytkownika

### ISSUE THREAD

**Issue by ganyamede** [allegro/allegro-api#7276]
Dobry wieczór, używamy allegro api , musimy pobrać wszystkie produkty sprzedawcy po nazwie użytkownika, próbowaliśmy użyć metody „oferty/listowanie”, ale otrzymaliśmy błąd „

{'errors': [{'code': „VerificationRequired”, „message”: „Odmowa dostępu. Wymagana weryfikacja.”, „szczegóły”: brak, „ścieżka”: brak, „userMessage”: „Brak dostępu do określonego zasobu. Dostęp jest możliwy tylko dla zweryfikowanych aplikacji .'}]}"

Powiedziano nam, że musimy przejść na konto firmowe, przeszliśmy na konto firmowe. I po wszystkim ten sam błąd. Możesz od razu napisać listę z rzędu, co dokładnie musimy zrobić, aby uzyskać dostęp do API

login: partsource
client id: ffad827eed5147bc97a962b78a53530c
app name: LinkChecker1

Proszę czekamy na pełną odpowiedź, dziękujemy!

![photo_2023-06-24_18-40-52](https://github.com/allegro/allegro-api/assets/96943330/3fa43b81-b277-4417-8c46-5f5fc49e354e)

**Comment by AureliuszBrussy** [comment]
Access to GET /offers/listing is limited only to verified applications. You can read more about it in [our news](https://developer.allegro.pl/news/get-offers-listing-only-for-verified-applications-Rdoz0LveKtl). If you want to verify your application: use the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), or (if you are in the [Partnership Program](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm) for Sellers) contact your account manager to go through the verification process.
