### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by PiotrPiotrP** [allegro/allegro-api#7277]
Dzień  dobry 
Jakiego pola dotyczy ten błąd:
06/19 13:15:34.430  PUT    https://api.allegro.pl/sale/offers/13845155452 requestBody={"afterSalesServices":{"impliedWarranty":{"id":"02778fe6-b201-4f7d-be2c-1ffc204e961b"},"returnPolicy":{"id":"f57bc1e4-a2d6-456c-a999-b6eccfad93a2"},"warranty":{"id":"eaad2d5b-9680-4181-9a4d-a19dd027b623"}},"category":{"id":"124264"},"delivery":{"shippingRates":{"id":"94522535-978f-4712-94cd-ae1e0ff9764e"},"handlingTime":"PT24H"},"external":{"id":"stocksell_286718358"},"id":"13845155452","images":[{"url":"https://a.allegroimg.com/original/118119/dd77466b4ebdb04efba26a9493d5"},{"url":"https://a.allegroimg.com/original/117f5e/74da412d4754ab4ae8f32ef5767f"}],"location":{"city":"Skawina","countryCode":"PL","postCode":"32-050","province":"MALOPOLSKIE"},"parameters":[{"id":"201089","values":["1"]},{"id":"18160","valuesIds":["18160_1"]},{"id":"249512","valuesIds":["249512_1647414"]},{"id":"15851","valuesIds":["15851_1"]},{"id":"11323","valuesIds":["11323_1"]},{"id":"54","valuesIds":["3806_5"]},{"id":"225693","values":["9409032812994"]},{"id":"127662","valuesIds":["127662_2"]},{"id":"3786","values":["Inna marka"],"valuesIds":["3786_85"]},{"id":"202477","valuesIds":["202477_2"]},{"id":"201017","valuesIds":["201017_2377"]},{"id":"4126","valuesIds":["4126_1"]},{"id":"3766","valuesIds":["3766_1"]},{"id":"127468","valuesIds":["127468_10"]},{"id":"201025","valuesIds":["201025_2513"]},{"id":"59","valuesIds":["59_3"]},{"id":"127488","valuesIds":["127488_2"]}],"name":"BIAŁA SUKIENKA SATYNOWA KOSZULOWA MINI* 40L 1VAB","payments":{"invoice":"VAT"},"publication":{"status":"ACTIVE","startingAt":"2023-06-14T16:15:00.000Z","republish":false},"sellingMode":{"format":"AUCTION","price":{"amount":39.99,"currency":"PLN"},"startingPrice":{"amount":34.99,"currency":"PLN"}},"stock":{"available":1,"sold":0,"unit":"UNIT"},"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003ch2\u003eBIAŁA SUKIENKA SATYNOWA KOSZULOWA MINI*\u003c/h2\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/118119/dd77466b4ebdb04efba26a9493d5"},{"type":"TEXT","content":"\u003ch2\u003eOpis Produktu\u003c/h2\u003e\u003cul\u003e\u003cli\u003e\u003cb\u003eMarka\u003c/b\u003e Inna marka\u003c/li\u003e\u003cli\u003e\u003cb\u003eKolor\u003c/b\u003e Biały\u003c/li\u003e\u003cli\u003e\u003cb\u003eSkład\u003c/b\u003e 95% poliester 5% elastan\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka papierowa\u003c/b\u003e Tak\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka wewnętrzna\u003c/b\u003e Wycięte ze względu na restrykcję outletową\u003c/li\u003e\u003cli\u003e\u003cb\u003eRozmiar\u003c/b\u003e EU40 UK12\u003c/li\u003e\u003cli\u003e\u003cb\u003eStan przedmiotu\u003c/b\u003e Przetarcie materiału na plecach po prawej, ok. 2 cm.  Trzy punktowe kropki na prawym rękawie. \u003c/li\u003e\u003cli\u003e\u003cb\u003eCena katalogowa\u003c/b\u003e 130,99 zł\u003c/li\u003e\u003c/ul\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/117f5e/74da412d4754ab4ae8f32ef5767f"}]}]},"tax":{"percentage":"23.00"},"product":{"id":"cc7a8d23-daf0-41fc-85e7-2becf97af123"},"language":"pl-PL"} exception=Niepoprawna odpowiedź z Allegro. Kod: 422. Błąd: VALIDATION_ERROR You cannot change the offer type. You cannot change the offer type. IllegalOfferUpdateException.IllegalChangeOfferType sellingMode. Trace-id=[1784ed6278d8e1f6]. 

Typ oferty to inaczej sellilngMode.format?
Jest gdzieś dostępna lista wiadomości opisujących błędy i ich interpretacja?

**Comment by AureliuszBrussy** [comment]
Tak, problem powoduje wartości przekazana w polu "**sellingMode.format**". W polu "**path**" przekazujemy ścieżkę (mniej lub bardziej precyzyjnie), której dotyczy błąd. 

Nie utrzymujemy zewnętrznej listy możliwych błędów.

**Comment by PiotrPiotrP** [comment]
Dziękuję
