### ISSUE TITLE
Unable to activate sales in sandbox environment

### ISSUE THREAD

**Issue by CodeWithOsvaldas** [allegro/allegro-api#7278]
Hello, I want to try out allegro rest api. I have created a business account in sandbox environment but I'm unable to activate sales. (after clicking on it, I get redirected to :
We are verifying your company details
The verification process might take a few days. We will inform you about the decision via email)

Account: 
codewithosvaldas@gmail.com
CodeWithOsvaldas

**Comment by PrzemyslawLukanowski** [comment]
Hello, I've activated your account. You should have access to all features within the company type of account.

**Comment by sikorskim** [comment]
Dzień dobry,
poproszę o aktywację konta:
m.sikorski@sellintegro.cloud
Pozdrawiam.

**Comment by PrzemyslawLukanowski** [comment]
@sikorskim Dzień dobry, aktywowałem Twoje konto.
