### ISSUE TITLE
Nowy parametr „Nośnik” w kategorii „Książki i Komiksy” 

### ISSUE THREAD

**Issue by is-tomaszgasior** [allegro/allegro-api#7279]
Chciałbym prosić o ujednoznacznienie komunikatu ze strony https://allegro.pl/pomoc/aktualnosci/wprowadzilismy-zmiany-w-parametrach-dotyczacych-gier-ksiazek-i-komiksow-b2zP1kgYyiv:

> Parametr Nośnik zaczęliśmy dodawać do podkategorii 26 czerwca i może to potrwać kilka dni. Gdy już to zrobimy, oznaczymy parametr Nośnik jako obowiązkowy. Dlatego gdy w tych podkategoriach będziesz wystawiać ofertę:
>
>    przez formularz wystawiania – automatycznie uzupełnimy ten parametr
>    przez API – podpowiemy Ci wartość, którą wybierzesz dla tego parametru.

Czy w związku z tą zmianą są wymagane jakiekolwiek realne zmiany w integracjach API aplikacji wystawiającej przez API oferty na Allegro w podkategoriach kategorii „Książki i Komiksy”? W jaki sposób zamierzacie „podpowiadać wartość” w sensie technicznym i czy aplikację trzeba w jakiś sposób do tego dostosowywać?

**Comment by PrzemyslawLukanowski** [comment]
"Podpowiadanie" w tym przypadku to ograniczenie listy dostępnych wartości na podstawie kategorii. Możesz już to sprawdzić np. w kategorii 253753 (Audiobooki - mp3). W odpowiedzi GET /sale/categories/253753/parameters zwrócimy poniższy fragment dla parametru "Nośnik":

```
        {
            "id": "249857",
            "name": "Nośnik",
            "type": "dictionary",
            "required": true,
            "requiredForProduct": true,
            "requiredIf": null,
            "displayedIf": null,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false,
                "ambiguousValueId": null,
                "dependsOnParameterId": null,
                "requiredDependsOnValueIds": null,
                "displayDependsOnValueIds": null,
                "describesProduct": true,
                "customValuesEnabled": false
            },
            "dictionary": [
                {
                    "id": "249857_1769439",
                    "value": "audiobook MP3",
                    "dependsOnValueIds": []
                }
            ],
            "restrictions": {
                "multipleChoices": false
            }
        },
```

Jedyną dostępną wartością jest:

```
"id": "249857_1769439",
"value": "audiobook MP3",
```

Analogicznie będzie to wyglądać w pozostałych kategoriach.

Co do dostosowania aplikacji - musi być ona po prostu gotowa na obsługę nowego wymaganego parametru, czyli oznaczonego jako `"required": true` - w kontekście tworzenia oferty, oraz `"requiredForProduct": true` - w kontekście tworzenia nowego produktu, którego nie ma w naszym Katalogu.

**Comment by PrzemyslawLukanowski** [comment]
Tak, przykład pochodzi z produkcyjnego Allegro. Taka sytuacja może wystąpić, ponieważ oba środowiska synchronizowane są w kontekście zgodności parametrów i kategorii **raz na kwartał**. O [takich akcjach zawsze informujemy na naszej stronie](https://developer.allegro.pl/news/sandbox-5-lipca-2023-zaktualizujemy-liste-kategorii-i-parametrow-oraz-usuniemy-wszystkie-oferty-K6PKz6GxqUL)  z odpowiednim wyprzedzeniem. W związku z tym, parametr będzie widoczny na Sandboxie dopiero 5 lipca.

**Comment by PrzemyslawLukanowski** [comment]
Na produkcyjnym Allegro parametr staje się wymagany w momencie, kiedy dodajemy go do kategorii. Tym sposobem jest on już wymagany w "Audiobooki - mp3", ale w części kategorii jeszcze go nie ma - cytując fragment artykułu, _"Parametr Nośnik zaczęliśmy dodawać do podkategorii 26 czerwca i może to potrwać kilka dni."_ 
Sam Sandbox jest tutaj drugorzędny, ponieważ środowisko testowe zostaje wtedy "dopasowane" do produkcyjnego, tak aby oba prezentowały aktualne dane dla parametrów i kategorii.
