### ISSUE TITLE
OfferRepository error

### ISSUE THREAD

**Issue by adampajak** [allegro/allegro-api#728]
Na sandbox dostaję taką odpowiedź dla jednej z poprawnie wystawionych ofert:
"offer": {
                "id": "6205659575"
            },
            "message": "OfferRepository error",
            "status": "FAIL",
            "scheduledAt": "2018-10-08T21:02:18.764+02:00",
            "finishedAt": "2018-10-08T21:03:10.901+02:00",
            "field": "publication"

Co to oznacza? Oferta jest wystawiona i wygląda dobrze.

Curl do sprawdzenia:
`curl -X GET \
  https://api.allegro.pl.allegrosandbox.pl/sale/offer-publication-commands/2cc2ec68-8062-4c04-a18c-2db2f0602a91/tasks \
  -H 'Accept: application/vnd.allegro.beta.v1+json' \
  -H 'Api-Key: apikey' \
  -H 'Authorization: Bearer token' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/vnd.allegro.beta.v1+json' \
  -H 'Postman-Token: 9c394a22-e36e-40c1-b6e7-1e688b1b1644'`

Odpowiedz:
`{
    "tasks": [
        {
            "offer": {
                "id": "6205659575"
            },
            "message": "OfferRepository error",
            "status": "FAIL",
            "scheduledAt": "2018-10-08T21:02:18.764+02:00",
            "finishedAt": "2018-10-08T21:03:10.901+02:00",
            "field": "publication"
        },
        {
            "offer": {
                "id": "6205659580"
            },
            "message": "OfferRepository error",
            "status": "FAIL",
            "scheduledAt": "2018-10-08T21:02:18.773+02:00",
            "finishedAt": "2018-10-08T21:03:10.908+02:00",
            "field": "publication"
        },
        {
            "offer": {
                "id": "6205659577"
            },
            "message": "",
            "status": "SUCCESS",
            "scheduledAt": "2018-10-08T21:02:18.768+02:00",
            "finishedAt": "2018-10-08T21:02:26.682+02:00",
            "field": "publication"
        },
        {
            "offer": {
                "id": "6205659576"
            },
            "message": "",
            "status": "SUCCESS",
            "scheduledAt": "2018-10-08T21:02:18.77+02:00",
            "finishedAt": "2018-10-08T21:02:26.682+02:00",
            "field": "publication"
        },
        {
            "offer": {
                "id": "6205659579"
            },
            "message": "",
            "status": "SUCCESS",
            "scheduledAt": "2018-10-08T21:02:18.771+02:00",
            "finishedAt": "2018-10-08T21:02:32.282+02:00",
            "field": "publication"
        },
        {
            "offer": {
                "id": "6205659578"
            },
            "message": "",
            "status": "SUCCESS",
            "scheduledAt": "2018-10-08T21:02:18.772+02:00",
            "finishedAt": "2018-10-08T21:02:26.682+02:00",
            "field": "publication"
        }
    ]
}`

**Comment by MartaNowaczyk** [comment]
Przetestowałam zasoby o których wspominasz i nie mam problemów. Czy problem się powtarza czy to tylko taki jeden przypadek?

**Comment by adampajak** [comment]
Teraz sprawdziłem i się nie pojawił. Pytanie czy kiedyś się jeszcze nie pojawi?

**Comment by MartaNowaczyk** [comment]
Mam nadzieję, że to tylko jednorazowy incydent, jdnak gdyby problem się powtórzył daj znać, sprawdzimy.
