### ISSUE TITLE
Device flow - refresh_token

### ISSUE THREAD

**Issue by KK2138** [allegro/allegro-api#7281]
Dzień dobry,
Piszę aplikacje w modelu `device flow` i chciałby zaimplementować w niej `refresh_token`.

Gdy za pomocą polecenia curl podanego w waszym poradniku próbuję uzyskać pierwszego refresh tokena: 
```
POLECENIE UZUPEŁNIONE PRZYKŁADOWYMI DANYMI:
curl -X POST https://allegro.pl/auth/oauth/token?grant_type=urn:ietf:params:oauth:grant-type:device_code&device_code=SDA0129lkfa2DJAKJj21j3p1p23jpjFA ^
-H "Authorization: Basic <hidden>"
```
Uzyskuję odpowiedź:
```
{"error":"Unauthorized","error_description":"Unauthorized"}'device_code' is not recognized as an internal or external command,
operable program or batch file.
```
Czy popełniam jakiś błąd czy może muszę użyć
```
curl -X POST ^ 
  'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=eyJ...SDA&redirect_uri=http://exemplary.redirect.uri' ^
  -H 'Authorization: Basic YTI...Hg=' ^
```
ale jeśli tak to skąd mam zastąpić `redirect_uri` albo czym go zastąpić?

**Comment by AureliuszBrussy** [comment]
Rozumiem, że:
1. Udało Ci się wygenerować `user_code`.
2. Równocześnie jako użytkownik wpisujesz user_code w [skojarz aplikację](https://allegro.pl/uzytkownik/bezpieczenstwo/skojarz-aplikacje) (lub korzystasz z uri zwróconego w "verification_uri_complete")?
3. W tym samym czasie odpytujesz (z interwałem zwróconym w polu "interval" razem z "user_code")?:
```
curl -X POST \
'https://allegro.pl/auth/oauth/token?grant_type=urn:ietf:params:oauth:grant-type:device_code&device_code={device_code}' \
  -H 'Authorization: Basic base64(clientId:secret)
```

Błąd "is not recognized as an internal or external command" sugeruje, że masz jakiś błąd w swoim curl'u w Wierszu poleceń.

Token możesz odświeżyć dopiero, gdy uzyskasz pierwszą parę access i refresh token. W przypadku device flow, przy odświeżaniu nie musisz przekazywać `redirect_uri`.

**Comment by KK2138** [comment]
Tak udało mi się wygenerować `user_code`, korzystam też z `verification_uri_complete`
Następnie wykonuje takie polecenie jak podawałem na samym początku tylko że z moimi danymi tzn: z `device_code` i `base64(clientId:secret)`. Czy powinienem dodać jeszcze coś innego (tzn to o czym pan mówi `interval` razem z `user_code`) i jeśli tak to w którym miejscu/ jak powinno wyglądać to polecenie (prosił bym o ile można o przykładowe polecenie)

**Comment by AureliuszBrussy** [comment]
Request w tym kształcie jest wystarczający:
```
curl -X POST \
'https://allegro.pl/auth/oauth/token?grant_type=urn:ietf:params:oauth:grant-type:device_code&device_code={device_code}' \
-H 'Authorization: Basic base64(clientId:secret)
```

Interval to logika, którą należałoby zaimplementować w kodzie. 

Upewnij się, czy na pewno poprawnie kodujesz token Basic (`base64(clientId:clientSecret)`), np. czy na pewno umieściłeś znak `:` pomiędzy `clientId`, a `clientSecret`. 

Tak jak wspomniałem, druga część odpowiedzi, którą otrzymałeś (`'device_code' is not recognized as an internal or external command, operable program or batch file.`) sugeruje, że być może popełniłeś jakiś błąd składniowy w swoim curl. 

Da ułatwienia rozeznania sugeruję skorzystanie z pomocniczych narzędzi do testów, np. z Postmana.

**Comment by KK2138** [comment]
Interval zastosowane, co do odpowiedniego zaszyfrowania - sprawdziłem i jest w 100% poprawne.
Co do drugiej części nadal szukam i na razie nic nie znalazłem

**Comment by KK2138** [comment]
Ogarnąłem, działa dziękuje za pomoc:
Rozwiązanie (zostawiam dla potomnych, może komuś się przyda)
```
curl --location --request POST https://allegro.pl/auth/oauth/token ^
--header "Content-Type: application/x-www-form-urlencoded" ^
--data-urlencode "grant_type=urn:ietf:params:oauth:grant-type:device_code" ^
--data-urlencode "device_code=[tutaj device_code]" ^
--header "Authorization: Basic [tutaj zakodowany client_id:client_secret]"
```
