### ISSUE TITLE
Wystawianie ofert i ich zamykanie.

### ISSUE THREAD

**Issue by lasongrzegorz** [allegro/allegro-api#7282]
Czesc, 
Znalazlem taki opis wystawiania/zamykania ofert - https://developer.allegro.pl/tutorials/jak-wystawic-i-zarzadzac-ogloszeniem-K6r3Z47dKcy#. Widze w nim, ze potrzebne jest podanie w parametrach url `commandId` ktore mam byc uuid'em. Nie jest dla mnie oczywiste czy ten uuid ma byc przeze mnie stworzony i pozniej uzywany do komunikacji, czy jest dostepny w jakims innym response'ie. Prosba o podpowiedz.
Jezeli jest to opcja wlasnego generowania uuid, to planujecie dodac w odpowiedzi o status takiej akcji, informacje ktore oferty sa failed a ktore success w :
```
    "taskCount": {
        "total": 1,
        "success": 1,
        "failed": 0
    }
```
? 

Na koniec, czy to jest jedyny mozliwe sposob aktywowania/zakonczenia oferty? Idealnie byloby to moc zrobic takze poprzez jakis endpoint typu https://developer.allegro.pl/documentation#operation/editProductOffers gdzie podaje offerId ktore chce zmodyfikowac. Jest cos takiego dostepne?
Dzieki

**Comment by hahyes** [comment]
@lasongrzegorz UUID generujesz i przesyłasz wraz z poleceniem wystawienia/zamknięcia oferty. To jest identyfikator zlecanego działania, po którym później możesz odpytać API o szczegóły, co się udało a co nie.
https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#informacje-o-publikacji

**Comment by hahyes** [comment]
@lasongrzegorz A co do ostatniego, zapoznaj się z nowym newsem z dzisiaj: https://github.com/allegro/allegro-api/issues/7280

**Comment by AureliuszBrussy** [comment]
To co napisał @hahyes oczywiście jest prawdą, natomiast dodam jeszcze, że możesz za pomocą [PATCH /sale/product-offers](https://developer.allegro.pl/documentation#operation/editProductOffers) swobodnie aktywować/zakończyć ofertę. Opisujemy to [w poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#zmiana-statusu-oferty).
