### ISSUE TITLE
pobieranie etykiety kurierskiej z Baselinker

### ISSUE THREAD

**Issue by FaleLokiKokipl** [allegro/allegro-api#7283]
Dzień dobry,

Chcę obsłużyć następujący proces:
zamówienie z allegro=> BL=> ERP XL=> WMS=> kompletacja=> WMS=> BL etykieta kurierska allegro kurier => WMS 
W związku z potrzebą pobierania etykiety allegro kurier z BL mam integrację z allegro oraz wysyłam z allegro. 
Czy takie integracje są wystarczający czy powinienem dodać integrację z każda firmą kurierską , która uczestniczy w programie allegro kurier ? 

Pozdrawiam
Tomek

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, 

Integracja Baselinker z Wysyłam z Allegro powinna Ci wystarczyć do pobierania etykiety i nie ma tutaj potrzeby integracji z każdą osobną firmą kurierską, którą możesz obsłużyć w ramach Wysyłam z Allegro. Napisałem „powinna”, ponieważ proces, którymi wymieniłeś i występujące w nim narzędzia:  

> zamówienie z allegro=> BL=> ERP XL=> WMS=> kompletacja=> WMS=> BL etykieta kurierska allegro kurier => WMS

nie są naszego autorstwa, nie mamy wiedzy, jak w tym przypadku wygląda przepływ danych, dlatego nie możemy się do niego dokładnie odnieść.
