### ISSUE TITLE
allegro.cz VQR002_LANGUAGE_NOT_AVAILABLE 

### ISSUE THREAD

**Issue by mciepiela** [allegro/allegro-api#7284]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Kilka ofert na sandbox wisi mi ze statusem w trakcie weryfikacji lub zgłoszona do weryfikacji. 
Po stronie swojego sklepu mam błąd:
{"AdditionalMarketplacesRequest":{"MarketplaceId":"allegro-cz","Auction":"7710713661","Error":"VQR002_LANGUAGE_NOT_AVAILABLE ","Status":"REFUSED"}}

Czy robicie dziś coś w tym obszarze, co wpływa na proces weryfikacji oferty na rynek czeski? Czy powinienem szukać błędu po naszej stronie.

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję ten przypadek z zespołem odpowiedzialnym za tłumaczenia ofert. Jak tylko uda mi się ustalić coś więcej, wrócę z informacją.

**Comment by mciepiela** [comment]
Zwróciłem właśnie uwagę, że po dwóch dniach aukcje wyszły z pętli i dostały status "zaakceptowana" :) tak czy inaczej, będę wdzięczny za feedback, na czym polegał / mógł polegać problem.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za update. Udało mi się dojść do przyczyny błędu, którą była przedwczorajsza i wczorajsza awaria jednej z naszych usług. Wczoraj po południu wgraliśmy fix, dlatego oferty wyszły z pętli. Przepraszam za niedogodności. Gdyby problem pojawił się ponownie, daj proszę znać w tym wątku.
