### ISSUE TITLE
Hurtowe zarządzanie warunkami gwarancji w ofertach

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#7285]
Czy istnieje możliwość z poziomu API, hurtowej modyfikacji warunków gwarancji dla wielu ofert? Chodzi mi o podobną możliwość jak w przypadku hurtowej modyfikacji usług dodatkowych: https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#uslugi-dodatkowe Przeszukałem dokumentację, ale nie mogę znaleźć żadnego punktu zaczepienia

**Comment by PrzemyslawLukanowski** [comment]
Nie udostępniamy takiej możliwości, jedynym wyjściem jest zmiana warunków gwarancji pojedynczo w ofertach, np. za pomocą [PATCH /sale/product-offers/{offerID} ](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pojedynczej-oferty).
