### ISSUE TITLE
Pobieranie kodu HTML w celu uzyskania danych

### ISSUE THREAD

**Issue by Smerf90** [allegro/allegro-api#7286]
Dzień Dobry, 
Chciałbym się dowiedzieć czy pobranie kodu HTLM strony w celu pobrania danych np. Ceny, tytułu oferty bądź opinii jest dozwolone? Wiem, że istnieje API Allegro jednak chciałbym użyć tej metody. 

Pozdrawiam,
Maciej

**Comment by PrzemyslawLukanowski** [comment]
Proces, o którym napisałeś, czyli tzw. scraping jest niedozwolony. Wspominamy o tym w pkt. 4.1e naszego [regulaminu](https://developer.allegro.pl/rules):

> e. wykorzystywanie do pobierania lub wykorzystywania w jakimkolwiek zakresie dostępnych w ramach Allegro materiałów (w tym danych oraz innych informacji) bez zgody Spółki lub w sposób naruszający postanowienia Regulaminu Allegro, Regulaminu, powszechnie obowiązujące przepisy prawa, interesy Spółki lub Użytkowników, w tym do dokonywania ekstrakcji (ang. scraping) tych materiałów.
