### ISSUE TITLE
Conditions list

### ISSUE THREAD

**Issue by beatrizm87** [allegro/allegro-api#7287]
Hello,
I would like to know if it is possible having an exhaustive list of conditions per category and also the condition definition. 

Thank you in advance.
Best regards,
Beatriz

**Comment by PrzemyslawLukanowski** [comment]
Hello, I'm not sure what you mean by conditions in terms of categories, but all public information about categories are returned in the response to [GET /sale/categories/{categoryID}](https://developer.allegro.pl/documentation#operation/getCategoryUsingGET_1) - you can expand the following section to get detailed information about each field:

<img width="746" alt="Zrzut ekranu 2023-06-28 o 08 53 55" src="https://github.com/allegro/allegro-api/assets/51473661/6a913d47-3069-4aa7-9886-3314bfed2ce3">

**Comment by beatrizm87** [comment]
Thank you for your answer, I would like to get the list of all categories with the parameters associated (usually the condition is one of these parameters), is there a call for that? Because in your call I need to know the categoryID and the call /sale/categories I got only the list of main categories.

**Comment by PrzemyslawLukanowski** [comment]
To get low-tier categories, you need to use `parent.id` query parameter.  For example, one of the main categories returned is:

  
```
            "id": "38d588fd-7e9c-4c42-a4ae-6831775eca45",
            "name": "Culture and Entertainment",
```

To get categories that are a level down from this category, you need to use `GET /sale/categories/{categoryID}?parent.id=38d588fd-7e9c-4c42-a4ae-6831775eca45`. One of the returned categories will be:

```
            "id": "300881",
            "name": "Tickets",
            "parent": {
                "id": "38d588fd-7e9c-4c42-a4ae-6831775eca45"
            },
            "leaf": false,
```

the information in `"leaf": false` indicates that this still isn't the lowest-tier category, so your next request can be  `GET /sale/categories/{categoryID}?parent.id=300881`

In your response, you will receive next level-down categories. After this series of requests, you will receive categories that are marked as `"leaf": true` - these are the categories in which offers can be listed. To get parameters associated with the given category, use [GET /sale/category/{categoryID}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2).
