### ISSUE TITLE
Pobranie listy "parametrów" wszystkich dla kategorii motoryzacja

### ISSUE THREAD

**Issue by kondziuuu** [allegro/allegro-api#729]
Hey chciałbym pobrać listę parametrów z kategorii motoryzacja. 
Chciałbym móc zmapować te parametry allegro z parametrami które wezmę z mojego ERP.

Jak moge pobrać całą listę parametrów dla poszczególnych kategorii.

**Comment by PawelTaberski** [comment]
Dostępne parametry dla danej kategorii pobierzesz przy pomocy metody: [GET na zasobie /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#/offer-management/getFlatParametersUsingGET_2). Więcej na ten temat znajdziesz w naszym poradniku [tutaj](https://developer.allegro.pl/sale/#parameters).

**Comment by kondziuuu** [comment]
A czy mogę pobrać do excela np. wszystkie możliwe parametry dla kategorii „czesci samochodowe” ?

**Comment by PawelTaberski** [comment]
W zależności jak ograsz to po stronie swojego systemu i w zależności do czego je potrzebujesz. To co zrobisz z tymi danymi zależy od Ciebie i potrzeb systemu jaki konstruujesz.
