### ISSUE TITLE
Active sessions per access token

### ISSUE THREAD

**Issue by DanielNoord** [allegro/allegro-api#7290]
In the FAQ (https://developer.allegro.pl/faq) we see that there is a limit of 20 "active sessions" for an access token and exceeding this might deactivate the token.
However, we're not quite sure what you mean with "active sessions". How are sessions counted? And when are they inactive/active?

Thank you for your help!

**Comment by PrzemyslawLukanowski** [comment]
20 active sessions mean that one user (not the application) can generate and operate within 20 active access tokens. Generating the 21st deactivates the token that was generated as the 1st.

**Comment by DanielNoord** [comment]
Thanks!
