### ISSUE TITLE
Nieudany PUT /sale/offers, parametr 249857

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#7291]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

Nieudany PUT /sale/offers/numer. Dostaję informację, że nie ma parametru 249857 o nazwie "Format". Ale w ofercie jest ten parametr. Za to nazwy "Format" w ogóle nie ma na liście parametrów kategorii. Jest "Nośnik". I może dlatego PUT się nie udaje? Problem dotyczy wielu ofert z parametrem 249857.

Przykładowy trace-id: 50705e6cdac0d4cd

```
{
   "errors":[
      {
         "code":"VALIDATION_ERROR",
         "message":"Missing required parameters: 249857",
         "details":"ConstraintViolationException.MissingRequiredParameters",
         "path":"parameters",
         "userMessage":"Missing mandatory parameters: Format."
      }
   ]
}
```

**Comment by AureliuszBrussy** [comment]
Sprawdziłem payload tego przykładowego requestu (50705e6cdac0d4cd) - nie przekazałeś w nim parametru 249857. Angielska nazwa tego parametru to "Format", stąd taka informacja w komunikacie błędu. 

To jest nowy parametr, więc być może to jest kwestia aktualizacji taksonomii po Twojej stronie.

**Comment by tomylee0** [comment]
Payload mam z GET /sale/offers dla tej samej oferty: 49558cfd9d0d748b
Zmieniam w nim jedynie ilość sztuk lub cenę. Jeśli zatem parametr 249857 nie pojawił się w PUT to błąd może polegać na tym, że nie pojawił się podczas wykonywania GET. Mogę Cię poprosić o sprawdzenie?

**Comment by AureliuszBrussy** [comment]
@tomylee0 to jest nowy parametr i nie był on wcześniej wymagany, więc mógł być on dotychczas nie wprowadzony. Dlatego faktycznie może się on nie pojawić w response.

**Comment by tomylee0** [comment]
Potwierdź proszę czy powoli uzupełniacie ten parametr automatycznie istniejącym ofertom? 

Bo wygląda na to, że oferta w momencie wysłania GET 49558cfd9d0d748b nie miała jeszcze tego parametru. A w tej chwili już ma. Czyli teraz GET i PUT by się powiódł.

**Comment by AureliuszBrussy** [comment]
Tak, masz rację, wraz ze stopniowym wprowadzaniem parametru, uzupełniamy również jego wartość w ofertach istniejących. Więcej piszemy w komunikacie [dla sprzedających](https://allegro.pl/pomoc/aktualnosci/wprowadzilismy-zmiany-w-parametrach-dotyczacych-gier-ksiazek-i-komiksow-b2zP1kgYyiv).

**Comment by tomylee0** [comment]
Dzięki za pomoc. Pozdrawiam.
