### ISSUE TITLE
Statusy zwrotów w api jak na stronie web

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#7292]
Na froncie można filtrować zwroty klienckie po statusie np : IN_TRANSIT.
Czy api również umożliwia takie pobranie danych? 
W jaki sposób pobrać tylko nierozliczone zwroty?

**Comment by AureliuszBrussy** [comment]
Nie udostępniamy takiego filtrowania w API. Wszystkie możliwości endpointu do pobierania zwrotów klienckich znajdziesz [w dokumentacji](https://developer.allegro.pl/documentation#tag/Customer-returns). Zwróć uwagę, że jest to zasób wciąż w wersji beta. Jeżeli chciałbyś zasugerować jakieś zmiany - skorzystaj proszę z zakładki [Discussions](https://github.com/allegro/allegro-api/discussions).

**Comment by paafcioc22** [comment]
a czy da się wykorzystać filtr parcels.waybill tak by pobrać tylko te zwroty które mają to pole nie puste?

**Comment by AureliuszBrussy** [comment]
Nie, można filtrować tylko po konkretnych wartościach.
