### ISSUE TITLE
WzA - przesyłki pobraniowe - weryfikacja IBAN

### ISSUE THREAD

**Issue by shivson1337** [allegro/allegro-api#7295]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**

Witam, 

zanotowaliśmy problemy z nadawaniem przesyłek pobraniowych na kilku naszych kontach.
Do tej pory wszystko działało bez problemu. Dzisiaj pojawił się komunikat o weryfikacji numeru IBAN.

Nie bardzo wiemy o co chodzi. Nie dokonywaliśmy żadnych zmian.

trace-id: 4a6005dec404a1f9

**Comment by PrzemyslawLukanowski** [comment]
Witam, 28 czerwca zmienił się sposób nadawania przesyłek nadawania przesyłek za pobraniem, sprzedawcy zostali o tej zmianie poinformowani mailowo, więcej na ten temat przeczytasz [w newsie na stronie dla sprzedających](https://allegro.pl/pomoc/aktualnosci/28-czerwca-zmienimy-sposob-nadawania-przesylek-z-platnoscia-przy-odbiorze-eKRoXel30S5#). W skrócie - numer konta wskazany w przez sprzedawcę przy tworzeniu przesyłki musi być taki sam, jak w ustawieniach wypłat Allegro - każdy inny zostanie odrzucony.

**Comment by amor22** [comment]
> Witam, 28 czerwca zmienił się sposób nadawania przesyłek nadawania przesyłek za pobraniem, sprzedawcy zostali o tej zmianie poinformowani mailowo, więcej na ten temat przeczytasz [w newsie na stronie dla sprzedających](https://allegro.pl/pomoc/aktualnosci/28-czerwca-zmienimy-sposob-nadawania-przesylek-z-platnoscia-przy-odbiorze-eKRoXel30S5#). W skrócie - numer konta wskazany w przez sprzedawcę przy tworzeniu przesyłki musi być taki sam, jak w ustawieniach wypłat Allegro - każdy inny zostanie odrzucony.

Pomimo ustawionych poprawnych wartości po obu stronach a IBAN jest zweryfikowany zwraca odpowiedź:

```

array (
  0 => 
  Rest\Response::__set_state(array(
     'httpCode' => 200,
     'content' => 
    stdClass::__set_state(array(
       'id' => '*******************',
       'parcelId' => NULL,
       'status' => 'ERROR',
       'errors' => 
      array (
        0 => 
        stdClass::__set_state(array(
           'code' => 'COD_IBAN_NOT_VERIFIED',
           'message' => 'This delivery option requires a verified Polish IBAN number',
           'details' => 'Provided Iban has to be verified',
           'path' => 'additionalServices',
           'userMessage' => 'Wybrana metoda dostawy wymaga podania zweryfikowanego, polskiego numeru iban',
        )),
      ),
    )),
     'contentType' => 'application/vnd.allegro.public.v1+json',
     'contentEncoding' => '',
     'contentSize' => 360,
     'headers' => 
    array (
      'expires' => '0',
      'cache-control' => 'no-cache, no-store, max-age=0, must-revalidate',
      'x-xss-protection' => '1; mode=block',
      'pragma' => 'no-cache',
      'x-frame-options' => 'DENY',
      'trace-id' => 'ad64edec54932970',
      'date' => 'Thu, 29 Jun 2023 06',
      'x-content-type-options' => 'nosniff',
      'strict-transport-security' => 'max-age=31536000 ; includeSubDomains',
      'content-type' => 'application/vnd.allegro.public.v1+json',
      'content-length' => '360',
    ),
  )),
)
```

**Comment by MrGadzet** [comment]
W moim przypadku zadziałało, ponowne dodanie numeru konta z przedrostkiem PL i usunięcie spacji pomiędzy cyframi. 
Polecam sprawdzić.

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, problemem są spacje w "accountNumber" - wprowadzimy poprawkę, aby były ignorowane. Na tę chwilę możecie powtórzyć request z usunięciem spacji.

**Comment by shivson1337** [comment]
Problem rozwiązany. Zamykam zgłoszenie.

Dziękuję za wsparcie. :)

**Comment by Kuba-Id** [comment]
Panie Przemysławie,
Otwieram temat ponownie.
Numer konta zgadza się z numerem konta do wypłat, a mimo wszystko komunikat błędu, jak i przedmówcy.
Będę wdzięczny za pomoc co jest nie tak.

TraceId: ff1f74cf37c1f90

**Comment by PrzemyslawLukanowski** [comment]
@Kuba-Id Spróbuj proszę przed numerem dodać przedrostek "PL".

**Comment by Kuba-Id** [comment]
Panie Przemku,

Dziękuję za szybką pomoc i reakcję.

Dodałem:
string(28) "PL02102040270000110219456217"

W jednym zamówieniu poszło. Ale spróbowałem kolejne.


I w drugim dalej jest problem. dziwna sprawa.
Raz działa, raz nie? :-|
Komunikat: "Provided Iban has to be verified This delivery option requires a verified Polish IBAN number"

trace-id: 520996ea07bd7e85

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem nasze logi - udało Ci się nadać przesyłkę z tym numerem konta, ponieważ utworzyłeś ją na koncie *****509, które to posiada taki numer rachunkowy. Kolejna próba, z trace-id powyżej, miała miejsce z konta ******427 - ten użytkownik posiada zdefiniowane inne konto do wypłat, stąd komunikat błędu.

**Comment by Kuba-Id** [comment]
Dziękuję, wszystko już działa. Racja!
