### ISSUE TITLE
Raporty Allegro

### ISSUE THREAD

**Issue by PProtasewicz** [allegro/allegro-api#7297]
Dzień Dobry,

czy Allegro zwraca poprzez API raporty w których są informacje nt. zmiany statusów aukcji itd ?. , ponieważ nigdzie nie znalazłem takiej informacji (pytam ponieważ takie raporty są zwracane w Amazonie) 

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, udostępniamy dziennik ofertowy GET /sale/offer-events, który zwraca informacje o zmianach w ofertach z ostatnich 24 godzin. W tym informacje, o których napisałeś. Szczegóły znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#dziennik-zdarzen-w-ofertach-sprzedawcy) oraz [dokumentacji](https://developer.allegro.pl/documentation/#operation/getOfferEvents).
