### ISSUE TITLE
 PUT /parcel-management/parcel-create-commands - JSON parse error

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#7298]
Próbuje na różne sposoby zgodnie z poradnikiem dodać paczkę dla zamówienia Allegro, ale dostaję błąd 400 bez szczegółowych informacji, które pola są nieprawidłowe.

CommandId = cfb638f6-ff60-438a-86cc-09141df641b4

```json
{
   "serviceId":"2488f7b7-5d1c-4d65-b85c-4cbcf253fd93",
   "receiver":{
      "address":{
         "street":"xxx",
         "postCode":"xxx",
         "city":"xxx",
         "countryCode":"PL"
      },
      "email":"xxx@allegromail.pl",
      "name":"xxx xxx",
      "phone":"xxx",
      "pointId":"JZD07N"
   },
   "pickup":{
      "name":"xxx xxx",
      "company":"xxx",
      "address":{
         "street":"xxx",
         "postCode":"xx-xxx",
         "city":"xxx",
         "countryCode":"PL"
      },
      "email":"allegro@xxx.pl",
      "phone":"xxx",
      "pointId":null
   },
   "items":{
      "dimensions":{
         "height":{
            "value":"41",
            "unit":"CENTIMETER"
         },
         "width":{
            "value":"38",
            "unit":"CENTIMETER"
         },
         "depth":{
            "value":"64",
            "unit":"CENTIMETER"
         }
      },
      "weight":{
         "value":"25.0",
         "unit":"KILOGRAM"
      },
      "description":"xxx",
      "value":{
         "amount":780,
         "currency":"PLN"
      },
      "type":"PACKAGE"
   },
   "label":{
      "sender":{
         "name":"xxx xxx",
         "company":"xxx",
         "address":{
            "street":"xxx",
            "postCode":"xx-xxx",
            "city":"xxx",
            "countryCode":"PL"
         },
         "email":"allegro@xxx.pl",
         "phone":"xxx",
      },
      "fileFormat":"PDF",
      "referenceNumber":"xxx"
   }
}
```

**Comment by PrzemyslawLukanowski** [comment]
Problem stanowi sekcja `items` przekazujesz obiekt w obiekcie, tymczasem jest to obiekt zagnieżdżony w tablicy. Kod Bad Request wskazuje m.in. właśnie na błąd w składni przesyłanej struktury. Przy tego rodzaju pomyłkach nie możemy zwrócić informacji o konkretnych polu.

**Comment by martacronic** [comment]
Wielkie dzięki za szybką odpowiedź.

Teraz pojawił się inny problem: ```"referenceNumber":"F\/352\/06\/23"```
i dostaję błąd "Invalid value: F/352/06/23 musi pasować do wzorca \"[A-Za-z0-9 _-]*\"

Od strony WzA dodajemy numery dokumentów bez problemu.

**Comment by PrzemyslawLukanowski** [comment]
Wygląda na to, że próbujesz nadać tę przesyłkę na umowie Allegro - 2488f7b7-5d1c-4d65-b85c-4cbcf253fd93, jednak takiej umowy nie zwracamy Tobie w odpowiedzi GET /parcel-management/delivery-services, posiadasz jedynie umowę własną, która posiada ID 2488f7b7-5d1c-4d65-b85c-4cbcf253fd93#600e3f......... Aby dodać umowę Allegro Inpost, zgodnie z info z [naszego poradnika](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY):

> *Umowa Allegro Inpost wymaga dodania w [ustawieniach Wysyłam z Allegro](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia) umowy własnej i wybrania opcji "Używaj oferty dla sprzedawców Allegro".
