### ISSUE TITLE
Gdzie znajdę informację o wymaganych brakujących metodach dostaw?

### ISSUE THREAD

**Issue by adibuu** [allegro/allegro-api#7299]
Próbowałem dodać nowy cennik dostaw za pomocą API, w odpowiedzi otrzymałem takie o to błędy:
errors: [
    {
      code: 'MISSING_DELIVERY_METHOD',
      message: 'Missing delivery method [0ee3467f-5451-4060-856e-7a2b502abe55] required in bundle "AllegroOnePunktBoxKurierBundle".',      
      details: null,
      path: null,
      userMessage: 'Brak metod [0ee3467f-5451-4060-856e-7a2b502abe55] wymaganych w pakiecie metod "AllegroOnePunktBoxKurierBundle".'       
    },
    {
      code: 'MISSING_REQUIRED_BUNDLE_METHODS',
      message: 'Adding method 0decb356-e694-42e7-82eb-f260691b856f requires existence of methods "[0ee3467f-5451-4060-856e-7a2b502abe55]".',
      details: null,
      path: null,
      userMessage: 'Dodanie metody 0decb356-e694-42e7-82eb-f260691b856f wymaga istnienia w cenniku, metod "[0ee3467f-5451-4060-856e-7a2b502abe55]".'
    },
    {
      code: 'MISSING_REQUIRED_BUNDLE_METHODS',
      message: 'Adding method 0e454c54-21dd-4e5c-9db2-0553724f9077 requires existence of methods "[0ee3467f-5451-4060-856e-7a2b502abe55]".',
      details: null,
      path: null,
      userMessage: 'Dodanie metody 0e454c54-21dd-4e5c-9db2-0553724f9077 wymaga istnienia w cenniku, metod "[0ee3467f-5451-4060-856e-7a2b502abe55]".'
    }
  ]
  
Wszystkie jest dla mnie jasne, mam jedynie pytanie czy znajdę gdzieś informacje o tym które metody są od siebie zależne? Tak aby móc zabezpieczyć moją aplikację i nie powielać tych błędów. W dokumentacji API nic takiego nie udało mi się znaleźć.

**Comment by PrzemyslawLukanowski** [comment]
Zasadę działania pakietów metod opisaliśmy [w naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#jak-dodac-cennik-dostaw) (pod "przykładowy response").

**Comment by adibuu** [comment]
Ok, jest tam informacja o tym że eksportowe metody dostaw łączą się w pakiety. Nie ma natomiast żadnego info o pakietach w lokalnych metodach dostaw.
W moim przykładzie błędów gdy odczytamy sobie metody dostaw po id to mamy odpowiednio:

Error 1: Brak metody "Allegro One Punkt, One Kurier" w pakiecie "AllegroOnePunktBoxKurierBundle" - gdzie znajdę informację o tym co wchodzi w skład takiego pakietu? Czy tutaj po prostu zasadą jest to, że każda metoda dostawy która ma w nazwie "One kurier" wchodzi w skład tego pakietu?

Error 2: Dodanie metody "Allegro One Kurier - dostawa dzisiaj" wymaga dodania także "Allegro One Punkt, One Kurier". Czy jest to analogiczna sytuacja z nazwą tak jak w przypadku Error 1?

Error 3: Dodanie metody "Allegro One Box, One Kurier - dostawa dzisiaj" wymaga dodania także  "Allegro One Punkt, One Kurier". Czy tutaj również chodzi o taką samą zasadę jak w Error 1 i 2?

Wszystkie powyższe metody dostaw obsługują płatność z góry.

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, jeśli chodzi pakiety dla lokalnych metod dostaw informacje znajdują się w tym [artykule](https://allegro.pl/dla-sprzedajacych/allegro-one-punkt-box-kurier-informacje-dla-sprzedajacych-2YKPLqY17HA#jak-udostepnic-metode-dostawy-w-swoich-ofertach) (informacje zawarte w nim uwzględnimy również w linkowanym przeze mnie wcześniej portalu developerskim). Podana tam metoda o nazwie "Allegro One (Punkt, Box, Kurier)" odnosi się de facto do pakietu trzech metod "Allegro One Punkt, One Kurier", "Allegro One Box, One Kurier" i "Allegro One Kurier - dostawa jutro" (wszystkie z "dostawą jutro").
Metody z "dostawą dzisiaj" tworzą osobny pakiet dwóch metod "Allegro One Box, One Kurier - dostawa dzisiaj" i "Allegro One Kurier - dostawa dzisiaj". Metody z "dostawą dzisiaj" wymagają wybrania metod z "dostawą jutro" (a więc w sumie pięciu metod nie licząc metod COD, które są opcjonalne). Zależności pomiędzy pakietami są pokazane także w postaci wcięć na formularzu edycji cennika:
![image (6)](https://github.com/allegro/allegro-api/assets/51473661/5d98171d-9509-44d6-888c-8ab359ccbe20)

**Comment by adibuu** [comment]
> Rozumiem, jeśli chodzi pakiety dla lokalnych metod dostaw informacje znajdują się w tym [artykule](https://allegro.pl/dla-sprzedajacych/allegro-one-punkt-box-kurier-informacje-dla-sprzedajacych-2YKPLqY17HA#jak-udostepnic-metode-dostawy-w-swoich-ofertach) (informacje zawarte w nim uwzględnimy również w linkowanym przeze mnie wcześniej portalu developerskim). Podana tam metoda o nazwie "Allegro One (Punkt, Box, Kurier)" odnosi się de facto do pakietu trzech metod "Allegro One Punkt, One Kurier", "Allegro One Box, One Kurier" i "Allegro One Kurier - dostawa jutro" (wszystkie z "dostawą jutro"). Metody z "dostawą dzisiaj" tworzą osobny pakiet dwóch metod "Allegro One Box, One Kurier - dostawa dzisiaj" i "Allegro One Kurier - dostawa dzisiaj". Metody z "dostawą dzisiaj" wymagają wybrania metod z "dostawą jutro" (a więc w sumie pięciu metod nie licząc metod COD, które są opcjonalne). Zależności pomiędzy pakietami są pokazane także w postaci wcięć na formularzu edycji cennika: ![image (6)](https://user-images.githubusercontent.com/51473661/250007435-5d98171d-9509-44d6-888c-8ab359ccbe20.png)

Dziękuję za wytłumaczenie.
