### ISSUE TITLE
Niechronologiczne zdarzenia w doGetSiteJournalDeals

### ISSUE THREAD

**Issue by DamianStepniewski** [allegro/allegro-api#73]
Korzystając z metody w tytule co jakiś czas mam problem z transakcjami, które są anulowane lub opłacone, zdarza się to średnio raz na tydzień, nie będę wchodził w szczegóły kodu, który napisałem. Natomiast dzisiaj udało mi się zidentyfikować przyczynę problemu: zdarzenia w doGetSiteJournalDeals są czasami niechronologiczne.
O ile dobrze rozumiem zasadę działania tych zdarzeń, podczas zakupu powstaje dealEventType = 1, czyli utworzenie deala, następnie dealEventType = 2, czyli utworzenie formularza pozakupowego i na końcu (opcjonalnie, jeżeli kupujący płaci przez Allegro Finanse) dealEventType = 3 lub = 4, czyli anulowanie lub opłacenie transakcji. Jednak czasami, z jakiegoś powodu event anulowania transakcji powstaje przed utworzeniem formularza.
Dla przykładu: 
dealEventId = 3618589756, dealEventType = 3 (anulowanie)
dealEventId = 3618589772 (a więc zdarzenie musiało nastąpić po poprzednim), dealEventType = 2
Oba zdarzenia mają ten sam Unix time = 1521124101, dotyczą dealTransactionid = 827499142

Mogę prosić o potwierdzenie, że taki problem występuje (i czy w ogóle jest to problem, czy zamierzone działanie)?

**Comment by LukaszKorek** [comment]
Taka sytuacja może mieć miejsce, nie jest to błąd. W skrócie - ze względu na ilość danych, są one pobierane z różnych miejsc, dlatego może się zdarzyć, że metoda zwróci dane w takiej kolejności.
