### ISSUE TITLE
Niespójność API dla Magic the gathering.

### ISSUE THREAD

**Issue by Troom** [allegro/allegro-api#7300]
Występuje problem:
 - [ X] ze środowiskiem produkcyjnym / with the production environment

Proszę o sprawdzenie spójności parametrów oferty dla kategorii:
 6089, 6090, 6091, 6092, 6093, 6094, 6095, 6096, 6097, 261207
 I dla parametrów produktowych.
 
 
 Przykładowo kategoria 6089,6091,6092 wymaga wydawcy.
![image](https://github.com/allegro/allegro-api/assets/10126507/77a964cd-4a1a-4749-8583-ebc44384122f)

Natomiast kategoria 6093, 6094,6095, 6096, 261207  wymaga producenta.
![image](https://github.com/allegro/allegro-api/assets/10126507/9d9e4438-f22b-42d8-9ce1-d801085b15d1)

Kategoria 6067 nie wymaga powyzszych parametrów.

 id=249839 wydawca
 id=248936 producent

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, przekazuję temat do dalszej analizy zespołowi odpowiedzialnemu za parametry.

> Kategoria 6067 nie wymaga powyzszych parametrów.

Tu tylko doprecyzuję, że nie do końca - parametr Wydawca również jest wymagany w tej kategorii.

**Comment by PrzemyslawLukanowski** [comment]
Otrzymałem informację od zespołu odpowiedzialnego za parametry, że wskazane przez Ciebie przypadki zostaną wkrótce uspójnione. Zespół już się tym zajmuje.

**Comment by Troom** [comment]
Kiedy moge się spodziewać uspójnienia tych kategorii?

**Comment by PrzemyslawLukanowski** [comment]
Kategorie zostały uspójnione - wymagamy we wszystkich wydawcy.

**Comment by PrzemyslawLukanowski** [comment]
Pozostała jeszcze jedynie kategoria 261207 - tutaj również już niedługo zamienimy Producenta na Wydawcę.
