### ISSUE TITLE
Identyfikator prowizji dla zakupów opłaconych przy pomocy Allegro Pay

### ISSUE THREAD

**Issue by kulisz** [allegro/allegro-api#7301]
Witam,

Chciałem się dowiedzieć pod jakim identyfikatorem będą widnieć prowizje dotyczące zakupów opłaconych przez Allegro Pay?

Tyczy się to zapowiedzianych waszych zmian w tym linku https://allegro.pl/pomoc/aktualnosci/wazne-zmiany-dla-sprzedajacych-w-czerwcu-lipcu-i-sierpniu-2Y5YODAZEfX#wprowadzimy-oplate-za-zakupy-oplacone-przy-pomocy-allegro-pay sekcja Wprowadzimy opłatę za zakupy opłacone przy pomocy Allegro Pay.

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, że masz na myśli wartość, jaką zwrócimy w `type.id` w odpowiedzi [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries). Będzie to `APF`:

```
    {
        "id": "APF",
        "description": "Opłata za udostępnienie metody płatności Allegro Pay"
    }
```

**Comment by kulisz** [comment]
Tak, dziękuje za informacje
