### ISSUE TITLE
Sandbox Wysyłam Allegro DPD Pobranie - PAYOUTS_USER_SETTINGS_NOT_FOUND

### ISSUE THREAD

**Issue by lukaszApilo** [allegro/allegro-api#7302]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem testowym / with the test environment

:beetle: Mam problem z przetestowaniem case'a nadania przesyłki Allegro kurier DPD Pobranie przez Sandbox. Dostaję błąd `PAYOUTS_USER_SETTINGS_NOT_FOUND` dlatego przechodzę do zakładki [newpayments_payout.php](https://allegro.pl.allegrosandbox.pl/myaccount/newpayments_payout.php?source=system) jednak Przelewy24 jest cały czas w trakcie weryfikacji, a PayU po przejściu na planszę z testową płatnością nie działa (w konsoli jest błąd `ncaught TypeError: Cannot read properties of undefined (reading '2') in models.js:442` w Chrome, `Uncaught TypeError: currentPayType is undefined` w Firefox, ta sama linia). Chyba że jest inna możliwość pozbycia się błędu `PAYOUTS_USER_SETTINGS_NOT_FOUND`?

Request:
`PUT https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/a9b037a3-9685-4d16-9672-b964756fa324b246`
Trace ID: d92006112c379219
Body:
```
{"serviceId":"259b5c7a-9056-4c74-80ec-8bdc50cb0413","receiver":{"address":{"street":"Warszawska 12","postCode":"44-444","city":"Warszawa","countryCode":"PL"},"email":"4t3cziv8l1+3d721e277@user.allegrogroup.pl","name":"Tester Test","company":"Testowa","phone":"+48 666 666 666"},"pickup":{"address":{"street":"Pawia 9","postCode":"31-154","city":"Krak\u00f3w","countryCode":"PL"},"email":"bok@apilo.com","name":"Company Test","phone":"+48500000000"},"items":[{"dimensions":{"height":{"value":10,"unit":"CENTIMETER"},"width":{"value":15,"unit":"CENTIMETER"},"depth":{"value":10,"unit":"CENTIMETER"}},"weight":{"value":1,"unit":"KILOGRAM"},"description":".."}],"type":"PACKAGE","label":{"fileFormat":"PDF","referenceNumber":"9b6138b5bb47b512fae5d76ff8adccaa"},"additionalServices":{"cashOnDelivery":{"value":{"amount":"76.99","currency":"PLN"},"accountNumber":"PL04105000288183144298295698","name":"Jan Kowalski","express":false}}}
```
Request:
`GET https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/a9b037a3-9685-4d16-9672-80ece0cbf99d`
Trace ID: `ace35e39249e9d99`
Response:
```
{"id":"a9b037a3-9685-4d16-9672-80ece0cbf99d","parcelId":null,"status":"ERROR","errors":[{"code":"PAYOUTS_USER_SETTINGS_NOT_FOUND","message":"Seller's payout settings not found","details":"Couldn't find payouts settings for requested user","path":"additionalServices","userMessage":"Nie znaleziono ustawień wypłat sprzedająceo"}]}
```

**Comment by AureliuszBrussy** [comment]
Aktualnie podczas rejestracji konta przechodzi się nowy proces weryfikacji wypłat. Dla starszego konta, które nie miało dotychczas aktywnych wypłat na Sandboxie nie mamy takiego procesu. Wyjaśniam z zespołem odpowiedzianym za usługę, czy możemy to jakoś aktywować. Wrócę z informacją. 

Jeżeli zależy Ci na czasie - możesz [zarejestrować na Sandboxie](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F) nowe konto i od razu aktywować wypłaty.

**Comment by lukaszApilo** [comment]
Założyłem konto `lukaszwator@apilo.com` - czekam na maila aktywacyjnego. Dałbyś radę przyspieszyć aktywację tego konta? Dziękuję z góry

**Comment by AureliuszBrussy** [comment]
Gdy już klikniesz w link aktywacyjny, przejdź przez tzw. "krokowca" weryfikacyjnego (w "Moje konto"). Gdy to zrobisz, daj znać. Aktywuję konto.

**Comment by lukaszApilo** [comment]
Hmmm, coś mail z linkiem nie przychodzi, a dodatkowo mogę się jeszcze raz zarejestrować na te same dane (mail: `lukaszwator@apilo.com`, login: `lukaszwator`). Nie zwiesiło się coś? :)
![image](https://github.com/allegro/allegro-api/assets/108129348/74ff89b8-4271-4634-96b9-a486831e09d7)

**Comment by AureliuszBrussy** [comment]
Sprawdziłem logi i mam potwierdzenie wysłania wiadomości, więc po naszej stronie proces się nie zawiesił. Upewnij się, czy mail nie wleciał do spamu. Wszystkie maile w ramach Sandboxa mają tytuł "Message from Allegro Sandbox environment" oraz sama treść jest w pliku .eml w załączniku.

**Comment by lukaszApilo** [comment]
Okej, powpisywałem allegrosandbox.pl na wszystkie białe listy i przyszły wszystkie zaległe maile. Konto linkiem, przeszedłem przez konfigurację. Mógłbyś proszę aktywować konto?

**Comment by AureliuszBrussy** [comment]
@lukaszApilo aktywowałem konto.

**Comment by lukaszApilo** [comment]
Super, udało mi się odtworzyć case klienta. Dzięki! Zamykam issue :)
