### ISSUE TITLE
How to Authenticate my app with Allegro Sandbox

### ISSUE THREAD

**Issue by AureliuszBrussy** [allegro/allegro-api#7304]
### Discussed in https://github.com/allegro/allegro-api/discussions/7303

<div type='discussions-op-text'>

<sup>Originally posted by **ravitvv** June 30, 2023</sup>
How to Authenticate my app with Allegro Sandbox? I was able to Authenticate using the Live link but with Sandbox, Im getting 

stdClass Object
(
[error] => invalid_grant
[error_description] => Invalid authorization code: xxxx
)

URL that I'm using: https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=CLIENT_ID&redirect_uri=REDIRECT_URI</div>

**Comment by AureliuszBrussy** [comment]
First, make sure you have registered your app in the [Developer Apps tab on Sandbox](https://apps.developer.allegro.pl.allegrosandbox.pl/).

Second, you should capture the authorization code that we returned on your redirect_url.

After capturing this code, you have 10 seconds to use it. To do this, execute curl (example):

```
curl -X POST \
  'https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=pOPEy9Tq94aEss540azzC7xL6nCJDWto&redirect_uri=http://exemplary.redirect.uri'
  -H 'Authorization: Basic YTI...Hg=' 
```

**Comment by ravitvv** [comment]
Thanks, Its resolved.
