### ISSUE TITLE
Problem z MissedCategoryIdException

### ISSUE THREAD

**Issue by fredzi** [allegro/allegro-api#7305]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **
Wysyłam poprawnego requesta z poprawnym id category a od niedawna api zwraca mi błąd MissedCategoryIdException
Przykładowy request:
{
   "productSet":[
      {
         "product":{
            "id":"",
            "idType":"GTIN"
         }
      }
   ],
   "afterSalesServices":{
      "impliedWarranty":{
         "id":"0149621d-5673-4610-944f-ad1544a18db2"
      },
      "returnPolicy":{
         "id":"44d890dd-507a-4303-b079-9b3f140a566c"
      },
      "warranty":{
         "id":"33145ea3-845d-4ec9-855c-bbd7835808b8"
      }
   },
   "category":{
      "id":"121465"
   },
   "delivery":{
      "additionalInfo":"",
      "handlingTime":"P2D",
      "shippingRates":{
         "id":"de4b26e5-6043-4040-9c1d-f4550a634877"
      }
   },
   "description":{
      "sections":[
         {
            "items":[
               {
                  "type":"TEXT",
                  "content":"<h1>Posnet Ergo Online - Modu\u0142owa Kasa Fiskalna<\/h1><p>Jedna z najbardziej popularnych kas fiskalnych na rynku Posnet ERGO teraz dost\u0119pna w wersji ONLINE. Urz\u0105dzenie, dzi\u0119ki modu\u0142owej konstrukcji, zapewnia u\u017cytkownikowi swobod\u0119 wyboru mi\u0119dzy przewodowym lub bezprzewodowym po\u0142\u0105czeniem z Centralnym Repozytorium Kas (CRK).<\/p><h2>Po\u0142\u0105cz si\u0119 z CRK<\/h2><p>Je\u015bli masz komputer po\u0142\u0105czony z Internetem - pod\u0142\u0105cz kas\u0119 do komputera za pomoc\u0105 z\u0142\u0105cza USB i nie p\u0142a\u0107 dodatkowo za transmisj\u0119 danych. To podstawowa wersja kasy.<\/p><p>W dowolnym momencie mo\u017cesz doposa\u017cy\u0107 Ergo w modu\u0142y komunikacyjne. Czy masz w swoim sklepie Internet i WiFi? Mo\u017cesz go wykorzysta\u0107 do komunikacji z CRK. \u015awiadczysz us\u0142ugi lub prowadzisz handel mobilny w terenie? Wyposa\u017c swoj\u0105 kas\u0119 w modem 3G.<\/p><p>\u015aci\u0105gnij instrukcj\u0119 dotycz\u0105c\u0105 skonfigurowania po\u0142\u0105czenia z CRK w kasach Posnet ONLINE (instrukcja Quick OnLine - PDF).<\/p><h2>Suma wszystkich zalet<\/h2><p>Kasa ERGO ONLINE \u0142\u0105czy w sobie zalety wszystkich naszych kas. Mo\u017ce dzia\u0142a\u0107 samodzielnie, jak r\u00f3wnie\u017c stanowi\u0107 element systemu kasowego. Do kasy pod\u0142\u0105czysz wag\u0119, skaner kod\u00f3w kreskowych, terminal p\u0142atniczy itp. Konstrukcja kasy, podobnie jak innych urz\u0105dze\u0144 POSNET, jest w stanie wytrzyma\u0107 upadki, wstrz\u0105sy czy zachlapanie.<\/p>"
               },
               {
                  "type":"IMAGE",
                  "url":"https:\/\/a.allegroimg.com\/original\/118a56\/f1a2312649e2a25bc222d38d67c0"
               }
            ]
         },
         {
            "items":[
               {
                  "type":"IMAGE",
                  "url":"https:\/\/a.allegroimg.com\/original\/111ed8\/803408a843bbac05e10baccf9e7d"
               },
               {
                  "type":"TEXT",
                  "content":"<h2>Zintegruj si\u0119 z wag\u0105<\/h2><p>Poszerz mo\u017cliwo\u015bci swojej kasy ERGO ONLINE, wykorzystuj\u0105c j\u0105 jako nowoczesn\u0105 i rozbudowan\u0105 kasowag\u0119. Jako pierwsi wprowadzili\u015bmy standard po\u0142\u0105czenia kasy z szalk\u0105 wa\u017c\u0105c\u0105 DS1. Takie rozwi\u0105zanie umo\u017cliwia obs\u0142ug\u0119 wagi bezpo\u015brednio z klawiatury kasy. Postaw na innowacyjno\u015b\u0107 - oszcz\u0119dno\u015b\u0107 czasu, miejsca i energii!<\/p><h2>Graficzne wy\u015bwietlacze<\/h2><p>ERGO ONLINE posiada dwa graficzne wy\u015bwietlacze, dzi\u0119ki czemu zoptymalizowali\u015bmy czytelno\u015b\u0107 prezentowanych informacji. Dodatkowo wydzielili\u015bmy pole przeznaczone na wy\u015bwietlanie wskaza\u0144 z wagi. Zar\u00f3wno klient, jak i sprzedaj\u0105cy na bie\u017c\u0105co otrzymuj\u0105 pe\u0142n\u0105 informacj\u0119 o zakupach.<\/p><h2>Zwi\u0119ksz baz\u0119 PLU<\/h2><p>Bez wzgl\u0119du na to, jak\u0105 dzia\u0142alno\u015b\u0107 prowadzisz, mo\u017cesz dostosowa\u0107 pojemno\u015b\u0107 bazy PLU do ilo\u015bci towar\u00f3w b\u0105d\u017a us\u0142ug, kt\u00f3re sprzedajesz. W zale\u017cno\u015bci od potrzeb na Twoim ERGO ONLINE mo\u017cesz zdefiniowa\u0107 4000, 6000 lub 8000 nazw towar\u00f3w lub us\u0142ug.<\/p>"
               }
            ]
         },
         {
            "items":[
               {
                  "type":"TEXT",
                  "content":"<h2>Wrzu\u0107 i drukuj<\/h2><p>Wymiana papieru zajmuje kilka sekund. Polega na wykonaniu trzech, prostych ruch\u00f3w: otwierasz - wrzucasz papier - zamykasz. I mo\u017cesz pracowa\u0107 dalej.<\/p><h2>Sprawdza si\u0119 na miejscu i w terenie<\/h2><p>Niezale\u017cnie od tego czy posiadasz punkt handlowy, czy \u015bwiadczysz us\u0142ugi, pracujesz stacjonarnie, a mo\u017ce w terenie? Kasa ERGO ONLINE doskonale sprawdzi si\u0119 w ka\u017cdej sytuacji.<\/p><p>ERGO ONLINE mo\u017cesz tak\u017ce wykorzysta\u0107 \u015bwiadcz\u0105c us\u0142ugi u klienta (np. mobilne kosmetyczki), na festynie lub jarmarku, je\u015bli wystawisz tam swoje stoisko. A kiedy zamienisz ma\u0142y sklep w du\u017cy salon, wystarczy, \u017ce dodasz odpowiednie modu\u0142y, poszerzysz baz\u0119 PLU i Posnet ERGO ONLINE nadal b\u0119dzie Ci s\u0142u\u017cy\u0107.<\/p><p>Szczeg\u00f3lnie polecamy kas\u0119 do: sklep\u00f3w internetowych, piekarni, cukierni, salon\u00f3w fryzjerskich i kosmetycznych, wysp marketowych i ma\u0142ych punkt\u00f3w gastronomicznych (fast-foody, food-trucki).<\/p>"
               },
               {
                  "type":"IMAGE",
                  "url":"https:\/\/a.allegroimg.com\/original\/11498a\/2ed398c14ddcb81623c53c5a66f2"
               }
            ]
         },
         {
            "items":[
               {
                  "type":"IMAGE",
                  "url":"https:\/\/a.allegroimg.com\/original\/112f67\/d95f22514eb088130e83e2984fa2"
               },
               {
                  "type":"TEXT",
                  "content":"<h2>W cenie urz\u0105dzenia otrzymuj\u0105 Pa\u0144stwo gratis<\/h2><ul><li>Ca\u0142kowicie przygotowan\u0105 kas\u0119 do pracy, zafiskalizowan\u0105.<\/li><li> Posiada zaprogramowany nag\u0142\u00f3wek, stawki vat oraz baz\u0119 towarow\u0105.<\/li><li> Istnieje mo\u017cliwo\u015b\u0107 zdalnej pomocy przy konfiguracji wymaganego po\u0142\u0105czenia internetowego.<\/li><\/ul><p><b>Po zakupie prosimy o o informacje: dane firmy oraz urz\u0119du skarbowego, nag\u0142\u00f3wek, adres gdzie kasa b\u0119dzie u\u017cywana.<\/b><\/p><h2>Dane techniczne<\/h2><ul><li><b>Wersja urz\u0105dzenia <\/b>ONLINE<\/li><li><b>Pami\u0119\u0107 chroniona <\/b>karta micro SD\/micro SDHC - 4GB<\/li><li><b>Komunikacja z CRK <\/b>USB, WiFi (opcja)<\/li><li><b>Eurofiskalizacja <\/b>mo\u017cliwo\u015b\u0107 zaprogramowania dowolnej waluty ewidencyjnej, w jakiej modu\u0142 fiskalny b\u0119dzie rejestrowa\u0142 sprzeda\u017c (np. euro)<\/li><\/ul><p><b>Bazy danych<\/b> <\/p><ul><li><b>Stawki VAT <\/b>7 (A...G)<\/li><li><b>Liczba PLU <\/b>4000, 6000\/8000 (opcja)<\/li><li><b>Nazwa towar\u00f3w <\/b>40 znak\u00f3w<\/li><li><b>Dodatkowe kody kreskowe <\/b>1000<\/li><li><b>Max. liczba kod\u00f3w do PLU <\/b>10<\/li><li><b>Zestawy towar\u00f3w \/ wielopaki <\/b>1000<\/li><li><b>Notatnik <\/b>500<\/li><li><b>Kasjerzy <\/b>16<\/li><li><b>Opakowania <\/b>65<\/li><li><b>Formy p\u0142atno\u015bci <\/b>16 (w tym 8 walut)<\/li><li><b>Rabaty \/ narzuty <\/b>16<\/li><li><b>Rabaty czasowe <\/b>8<\/li><li><b>Jednostki miary <\/b>5<\/li><li><b>Klawisze skr\u00f3tu <\/b>27<\/li><li><b>Grupy towarowe <\/b>32<\/li><li><b>Formaty kod\u00f3w wa\u017conych <\/b>10<\/li><li><b>Opisy wp\u0142at \/ wyp\u0142at <\/b>10<\/li><li><b>Opisy towar\u00f3w <\/b>30<\/li><li><b>Obs\u0142uga b\u0142\u0119d\u00f3w <\/b>20<\/li><li><b>Bufor pozycji paragonowych <\/b>5000<\/li><\/ul>"
               }
            ]
         },
         {
            "items":[
               {
                  "type":"TEXT",
                  "content":"<p><b>Mechanizm drukuj\u0105cy<\/b> <\/p><ul><li><b>Typ mechanizmu drukuj\u0105cego <\/b>termiczny, drop in - wrzu\u0107 i drukuj<\/li><li><b>Liczba znak\u00f3w w wierszu <\/b>40<\/li><li><b>Szeroko\u015b\u0107 papieru <\/b>57 mm<\/li><li><b>D\u0142ugo\u015b\u0107 rolki papieru <\/b>30 m<\/li><li><b>Szybko\u015b\u0107 wydruku <\/b>20 linii\/s<\/li><\/ul><p><b>Wy\u015bwietlacze<\/b> <\/p><ul><li><b>Wy\u015bwietlacz operatora <\/b>graficzny (192 x 64 pikseli)<\/li><li><b>Wy\u015bwietlacz klienta <\/b>graficzny (192 x 64 pikseli), pod\u015bwietlany<\/li><\/ul><p><b>Klawiatura<\/b> <\/p><ul><li><b>Liczba klawiszy klawiatury <\/b>29, klawiatura switchowa\/silikonowa<\/li><\/ul><p><b>Komunikacja<\/b> <\/p><ul><li><b>Porty standardowe <\/b>1 x USB (host), obs\u0142uga szuflady kasowej 5 V<\/li><li><b>Porty dodatkowe:<\/b><\/li><li> modu\u0142 rozszerzenia I - 2 x RS232 szuflada wielonapi\u0119ciowa (opcja)<\/li><li> modu\u0142 rozszerzenia II -WiFi, Bluetooth, 2 x RS232, szuflada wielonapi\u0119ciowa (opcja)<\/li><li> modu\u0142 rozszerzenia III - modem 3G, 2 x RS232, szuflada wielonapi\u0119ciowa (opcja)<\/li><li><b>Szuflada <\/b>5V (opcja 6V, 12V, 18V, 24V)<\/li><li><b>Obs\u0142ugiwane urz\u0105dzenia <\/b>komputer, skaner (USB\/RS), waga, szuflada, weryfikator cen, drukarka paragonowa, modem 3G, waga zintegrowana, czytnik magnetyczny, pendrive, terminal p\u0142atniczy, hub USB, tunelowanie port\u00f3w COM, monitoring<\/li><li><b>Komunikacja z komputerem <\/b>on-line, bez przerywania pracy kasjera<\/li><\/ul>"
               },
               {
                  "type":"IMAGE",
                  "url":"https:\/\/a.allegroimg.com\/original\/11be42\/4320a24b4bd48a011960e8a6c36f"
               }
            ]
         },
         {
            "items":[
               {
                  "type":"IMAGE",
                  "url":"https:\/\/a.allegroimg.com\/original\/1192ec\/155e707f4aad842887ef058b3aef"
               },
               {
                  "type":"TEXT",
                  "content":"<p><b>Zasilanie<\/b> <\/p><ul><li><b>Zasilacz <\/b>zewn\u0119trzny<\/li><li><b>Wbudowany akumulator <\/b>Li-ion 7,2V\/2150 mAh<\/li><li><b>Port USB <\/b>1<\/li><\/ul><p><b>Wymiary, waga, temperatury<\/b> <\/p><ul><li><b>Wymiary <\/b>94 x 62 x 230 mm (szer. x wys. x d\u0142.)<\/li><li><b>Waga <\/b>0,6 kg<\/li><\/ul><p><b>Najwa\u017cniejsze funkcje<\/b> <\/p><ul><li> modu\u0142owo\u015b\u0107 - \u0142atwo\u015b\u0107 rozbudowy<\/li><li> pami\u0119\u0107 chroniona z mo\u017cliwo\u015bci\u0105 zdalnej archiwizacji danych<\/li><li> zwi\u0119kszona wytrzyma\u0142o\u015b\u0107 konstrukcji<\/li><li> graficzne wy\u015bwietlacze<\/li><li> funkcja kasowagi<\/li><li> wsp\u00f3\u0142praca z terminalami p\u0142atniczymi<\/li><li> funkcjonalna klawiatura<\/li><li> grafika na paragonach<\/li><li> NIP nabywcy z kontrol\u0105 kwoty paragonu<\/li><li> paragon w trybie blokowym<\/li><li> komunikacja bezprzewodowa<\/li><\/ul>"
               }
            ]
         }
      ]
   },
   "images":[
      "https:\/\/a.allegroimg.com\/original\/118a56\/f1a2312649e2a25bc222d38d67c0",
      "https:\/\/a.allegroimg.com\/original\/111ed8\/803408a843bbac05e10baccf9e7d",
      "https:\/\/a.allegroimg.com\/original\/11498a\/2ed398c14ddcb81623c53c5a66f2",
      "https:\/\/a.allegroimg.com\/original\/112f67\/d95f22514eb088130e83e2984fa2",
      "https:\/\/a.allegroimg.com\/original\/11be42\/4320a24b4bd48a011960e8a6c36f",
      "https:\/\/a.allegroimg.com\/original\/1192ec\/155e707f4aad842887ef058b3aef",
      "https:\/\/a.allegroimg.com\/original\/116bd1\/82301f8248ffaa6db7d3abb0d857",
      "https:\/\/a.allegroimg.com\/original\/115ec2\/8b741f194bc3aabfc07f2ceb24bf",
      "https:\/\/a.allegroimg.com\/original\/11346a\/e3607f8340418ddd2bca2561baf2"
   ],
   "location":{
      "city":"Cz\u0119stochowa",
      "countryCode":"PL",
      "postCode":"42-217",
      "province":"SLASKIE"
   },
   "name":"Posnet Ergo ONLINE Modu\u0142owa Kasa Fiskalna PLU4000",
   "payments":{
      "invoice":"VAT"
   },
   "promotion":{
      "bold":false,
      "departmentPage":false,
      "emphasized":false,
      "emphasizedHighlightBoldPackage":false,
      "highlight":false
   },
   "publication":{
      "duration":null,
      "status":"INACTIVE"
   },
   "sellingMode":{
      "price":{
         "amount":1549,
         "currency":"PLN"
      },
      "format":"BUY_NOW"
   },
   "stock":{
      "available":"11",
      "unit":"UNIT"
   },
   "messageToSellerSettings":{
      "mode":"OPTIONAL"
   }
}
**

**Comment by AureliuszBrussy** [comment]
Jeżeli nie wskazujesz istniejącego produktu (brak wartości w productSet[].product.id), to powinieneś w obiekcie **productSet[].product** podać pełne dane produktu, takie jak nazwa, kategorię, parametry czy zdjęcia.
