### ISSUE TITLE
Dostaję błąd "Allegro returned error: No access to the specified resource" podczas próby generowania paczki

### ISSUE THREAD

**Issue by Pibrusz** [allegro/allegro-api#7306]
Przy próbie wysyłania request po utworzenie paczki przez serwis WzA dostaję błąd wymieniony w temacie. Dostaliśmy od Państwa podaną informację: 

```
„Aby nadać przesyłkę przez API niezbędny jest w tokenie scope "allegro:api:orders:write". Obecnie korzystają Państwo z tokena, który ma w sobie tylko wymienione scope'y: ["allegro:api:orders:read","allegro:api:billing:read","allegro:api:sale:settings:read","allegro:api:payments:read","allegro:api:sale:offers:read"].

W tym wypadku powinni ponownie Państwo zautoryzować API już ze scope'm odpowiedzialnym za [m.in](https://m.in/). przygotowanie przesyłek.
```
Dodaliśmy wszystkie możliwe uprawnienia, lecz błąd dalej występuje. Przez formularz kontaktowy załączyliśmy przykładowy request/response

**Comment by PrzemyslawLukanowski** [comment]
Co prawda nie otrzymaliśmy jeszcze danych z formularza, ale jeśli chcecie upewnić się, czy Wasz token zawiera wspomniane zakresy, to wejdźcie, np. na [tę stronę](https://jwt.io/), gdzie możecie zdekodować token - lista scope'ów będzie widoczna po prawej stronie. Jeśli go tam nie będzie, to podejrzewam, że dodaliście uprawnienia na stronie https://apps.developer.allegro.pl/,  jednak dalej działaliście w ramach tego samego refresh tokena, który nie posiadał nowych uprawnień. W takim przypadku musicie na nowo zautoryzować aplikację i wygenerować nową parę access + refresh token, już z nowymi uprawnieniami.

**Comment by Pibrusz** [comment]
Token mamy zaktualizowany, załączam listę uprawnień :( 
` "scope": [
    "allegro:api:orders:read",
    "allegro:api:billing:read",
    "allegro:api:sale:settings:read",
    "allegro:api:payments:read",
    "allegro:api:sale:offers:read",
    "allegro:api:orders:write"
  ]`

**Comment by Pibrusz** [comment]
Nie wiem, co się zmieniło lecz przed chwilą udało się poprawnie wygenerować paczkę :) Dzięki serdecznie za pomoc
