### ISSUE TITLE
Jak rozpoznać oferty bez możliwości wysyłki do Polski? offers/listing

### ISSUE THREAD

**Issue by bartoszkurek** [allegro/allegro-api#7307]
Dzień dobry,
pobieram dane z ofert publicznych poprzez offers/listing , od jakiegoś czasu coraz więcej ofert ma komunikat: "Tej oferty nie możesz zamówić do wybranego kraju", rozumiem, że użytkownik wystawia ją tylko za granicę? Jak takie oferty rozróżnić albo wykluczyć pobierając poprzez offers/listing?

PS. z resztą na Allegro w listningu te oferty też wyskakują, to nie ma sensu, znajduje najlepszą ofertę cenowo, wybieram ją z listy aby kupić, a tam komunikat, że jej nie zamówię.

Pozdrawiam

**Comment by bartoszkurek** [comment]
Czy to jest jakaś opcja na rozpoznanie braku wysyłki do Polski? Czyli brak wartości przy availableForFree oraz lowestPrice->amount o wartości 0?

[delivery] => stdClass Object
                (
                    [availableForFree] => 
                    [lowestPrice] => stdClass Object
                        (
                            [amount] => 0.00
                            [currency] => PLN
                        )
                )

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale nie udostępniamy takiej możliwości.

**Comment by PrzemyslawLukanowski** [comment]
Może nie do końca jest oto dpowiedzią na Twoje pytanie, ale w ramach wybranych kategorii możesz skorzystać z dynamicznego filtra "dostawa z Polski":

```
{
            "id": "shippingFromPoland",
            "type": "SINGLE",
            "name": "Dostawa z Polski",
            "values": [
                {
                    "value": "1",
                    "name": "tak",
                    "selected": false
                },
                {
                    "value": "0",
                    "name": "nie",
                    "selected": false
                }
            ]
        }
```
