### ISSUE TITLE
Problem z Parcel Create

### ISSUE THREAD

**Issue by Oktawian12** [allegro/allegro-api#7310]
Przy probie wygenerowania przesylki:
PUT https://api.allegro.pl/parcel-management/parcel-create-commands/dde0517a-8391-466a-a6f2-285c750882a0
Otrzymuje response
{"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"No access to the specified resource."}]}
Aplikacji ma nadane wszystkie dostepne uprawnienia.
Czy potrzebuje dodatkowo edytowac cos w kofiguracji?
Pozdrawiam
Oktawian

**Comment by MaciejFrackowiak** [comment]
W tokenie, który użyłeś podczas wykonania requestu nie miałeś scope "allegro:api:orders:write" i dlatego nie mogłeś utworzyć przesyłki. Musisz wygenerować nowy token, aby posiadał on aktualne wartości scope z przyznanych dla danej aplikacji.
