### ISSUE TITLE
GET unfilled-parameters nie zwraca wszystkich niewypełnionych obowiązkowych parametrów

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#7311]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

Wydaje się, że GET /sale/offers/unfilled-parameters nie zwraca wszystkich niewypełnionych obowiązkowych parametrów. Tu jest request dotyczący konkretnej oferty:

trace-id: 93a4981bc21f350f

W odpowiedzi mam:

```
      "parameters": [
        {
          "id": "223489"
        },
        {
          "id": "223541"
        },
        {
          "id": "223545"
        },
        {
          "id": "245669"
        },
        {
          "id": "248247"
        },
        {
          "id": "249857"
        },
        {
          "id": "2868"
        },
        {
          "id": "74"
        },
        {
          "id": "75"
        }
      ],
      "category": {
        "id": "318912"
      }
```

Ale podczas próby aktualizacji tych parametrów dostaję informację, że "Missing required parameters: 249493" którego nie dostałem w poprzedniej odpowiedzi.

trace-id: 28344365b5d9934b

No i jak to się w ogóle stało, że tyle parametrów obowiązkowych nagle nie ma...

Pytanie ogólne do wszystkich czytających. Czy oprócz mnie komuś to jeszcze przeszkadza, że nawet jeśli z uzasadnionych wewnętrznie powodów w Allegro znikają obowiązkowe parametry w aktywnej ofercie to i tak potem sprzedający jest odpowiedzialny za ich uzupełnienie bo inaczej nie może modyfikować ceny?

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem problem do zespołu, który odpowiada za tę usługę. Wrócę z informacją, gdy otrzymam więcej szczegółów.

**Comment by PrzemyslawLukanowski** [comment]
Po analizie błędu nie możemy potwierdzić błędu, zachowanie w tym przypadku było poprawne, ponieważ jest związane z [warunkową zależnością.](https://developer.allegro.pl/news/wprowadzamy-zmiany-w-obsludze-parametrow-zaleznych-yPOELGb2gTM) Oznacza to, że parametr jest wymagany jedynie pod warunkiem, gdy parametr nadrzędny dla niego ma wybraną jedną wartość z konkretnego zbioru. Uzupełniany parametr Gatunek (ID: 249493) jest domyślnie opcjonalny (stąd nie pojawił się w odpowiedzi z publicznego API), natomiast może stać się wymagalny, jeśli uzupełniony zostanie parametr Rodzaj (ID: 248247) jedną z wybranych wartości.

Tak stało się w tym przypadku, odpytując zasób /sale/offers/unfilled-parameters, otrzymałeś informacje o aktualnie brakujących parametrach obowiązkowych w ofercie, natomiast w tamtym momencie, ze względu na brak podanej wartości w parametrze Rodzaj, parametr Gatunek nie był obowiązkowy. Następnie, na formularzu edycji oferty, dla parametru Rodzaj podana została wartość Książki dla dzieci, co spowodowało obowiązkowość parametru Gatunek i odrzucenie na walidacji.

**Comment by tomylee0** [comment]
Dzięki wielkie za odpowiedź w sprawie unfilled-parameters.

Proszę potwierdź jeszcze czy przyczyną, że zniknęło tyle parametrów obowiązkowych było przeniesienie przez mechanizm Allegro tej oferty do innej kategorii? Czy może coś innego?

**Comment by PrzemyslawLukanowski** [comment]
Tak, według naszych danych było to wynikiem wewnętrznej operacji - zmiany kategorii.
