### ISSUE TITLE
Pytania odnośnie integracji z Allegro One

### ISSUE THREAD

**Issue by neldh** [allegro/allegro-api#7312]
Witam

Po przestudiowaniu https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY
mam kilka pytań odnośnie integracji z Allegro One za pomocą REST api.

Interesują mnie wszystkie metody allegro one:
Allegro One Box
Allegro One Box, One Kurier - dostawa dzisiaj
Allegro One Box, One Kurier - dostawa jutro
Allegro One Punkt
Allegro One Punkt, One Kurier
Allegro One Kurier - dostawa dzisiaj
Allegro One Kurier - dostawa jutro

1. Czy są jakieś limity czasowe na stworzenie paczki/etykiety, uzależnione od daty zamówienia?
2. Czy jest limit ilości paczek dla jednego zamówienia? Gdzieś znalazłem informację o tym, że 1 paczka dla Allegro One. Dotyczy to wszystkich wymienionych metod?
3. Jeśli nie ma limitu ilości paczek, to czy można dodać kolejną paczkę w późniejszym czasie (np po dniu), czy musi to być od razu?
4. Czy podanie przy tworzeniu paczki wagi/wymiarów jest wymagane? w dokumentacji przy tych parametrach nie ma słowa "wymagane", ale jest na całym "items".

**Comment by PrzemyslawLukanowski** [comment]
Poniżej znajdziesz odpowiedzi na poruszone pytania:

1. Paczkę możesz stworzyć tak długo, jak dostępne jest zamówienie czyli ok. 180dni.
2. Nie, nie ma limitu. Natomiast pierwsza paczka jest refundowana w ramach smarta, a kolejne są rozliczane wg. cennika.
3. Tak, możesz dodać paczkę w późniejszym terminie
4. Jest to zależne od przewoźnika, w przypadku wymienionych metod tak, dla nich wymiary i waga są wymagane.
