### ISSUE TITLE
Zakonczenie oferty

### ISSUE THREAD

**Issue by lasongrzegorz** [allegro/allegro-api#7314]
Czesc,
Wrzucilem request do api ( `sale/product-offers/13843261091` ) odnosnie zakonczenia oferty poprzez edycje status zgodnie z `https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#zmiana-statusu-oferty`. Otrzymalem status 200, ale widze ze oferta jest ciagle dostepna -> https://allegro.pl/oferta/biketek-dywan-motocyklowy-serii-4-13843261091. 
Czy oferta nie jest dezaktywowana natychmiast?
Z gory dzieki za szybka odpowiedz.

**Comment by PrzemyslawLukanowski** [comment]
Upewnij się proszę, czy JSON, który uwzględniasz w strukturze jest na pewno prawidłowy i dobrze "podpięty". Wg naszych logów, o godzinie 12:22:24.794 ,wysłałeś nam wyłącznie pusty obiekt `{}`.

**Comment by lasongrzegorz** [comment]
Dzieki za sprawdzenie. De facto wyslalem dwa requesty wczesniej, ale widac ze tylko jeden w ogole odnotowaliscie. 
Przed chwile wyslalem ponowny request, juz z payloadem i otrzymalem 202. Ta sama oferta w momencie pisania zostala juz poprawnie zakonczona.
Dzieki
