### ISSUE TITLE
ID parametru 1?

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#7316]
Witam,
w kategorii 16479 (Pozostałe) wyskoczył mi parametr Rok produkcji o ID: 1. Nigdy nie widziałem ID poniżej 50, więc zastanawiam się czy to nie jest bug czy jakaś nieścisłość w systemie.

Trace-Id: 8cf053ed8d3364c9
Jest to na API produkcyjnym.

**Comment by MaciejFrackowiak** [comment]
Jest to prawidłowe id dla parametru Rok produkcji - występuje głównie w motoryzacji i kategoriach związanych z rowerami.

**Comment by hahyes** [comment]
@MaciejFrackowiak Dziękuję za odpowiedź. :)
