### ISSUE TITLE
Dopłaty do smart w api

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#7317]
Proszę mi powiedzieć w jaki sposób za pośrednictwem API mogę uzyskać informacje na temat dopłat do przesyłek objętych programem smart. Zaznaczam, że podanie tych danych w tabelkach na trudno dostępnych stronach nie wyczerpuje obowiązku informacyjnego w tym zakresie.

**Comment by MaciejFrackowiak** [comment]
Informacje o kosztach dopłat zamieszczone są w [Załączniku nr 4](https://allegro.pl/regulamin/zalacznik/4#czesc-iv-oplaty-za-opcje-dodatkowe-dla-ofert-innych-niz-ogloszeniowe-allegropl) do Regulaminu Allegro. W API nie zwracamy ogólnych informacji o cenniku, a wyłącznie o opłatach naliczonych na danym koncie użytkownika - [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries).

**Comment by MaciejFrackowiak** [comment]
Zauważ proszę, że [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST) zwraca koszty w ujęciu pojedynczej oferty (jej wzorca), natomiast dopłaty naliczane są w ujęciu całego zamówienia klienta, które może obejmować x ofert jednocześnie.

**Comment by maniootek** [comment]
czy nadal nie da się pobrać z Allegro API informacji na temat dopłat do przesyłek smart z podziałem na zakresy ceny sprzedaży oraz form wysyłki? przykład w załączniku
![image](https://github.com/user-attachments/assets/ac590027-cbb7-4471-a005-ffbea6765455)
