### ISSUE TITLE
Zablokowana Aplikacja. 

### ISSUE THREAD

**Issue by itav** [allegro/allegro-api#7318]
Moja aplikacja w allegro została zablokowana. Jaka jest przyczyna blokady ? Czy mogą ją państwo odblokować ?

**Comment by itav** [comment]
Id aplikacji: d7c59d1a1d4842d6a02f288a1f......

**Comment by MartaNowaczyk** [comment]
W sprawie blokady napisz do nas przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) i podaj cały Client ID.
