### ISSUE TITLE
Różnice między API PL a CZ

### ISSUE THREAD

**Issue by PProtasewicz** [allegro/allegro-api#7319]
Witam,

mam pytanko, czy między API PL a API CZ występują jakieś różnice (na pierwszy rzut oka nie widzę takowych), ale wole dopytać ?

Pozdrawiam
Piotr

**Comment by PrzemyslawLukanowski** [comment]
W przypadku allegro-cz nie wystawisz:

- ofert typu AUCTION,
- ofert charytatywnych,
- ofert B2B,
- ofert, które nie są powiązane z produktem.

Dodatkowo:
- nie połączysz ofert w ofertę wielowariantową,
- nie skorzystasz z tagów ofertowych
- nie utworzysz promocji w ramach endpointu [POST /sale/loyalty/promotions](https://developer.allegro.pl/documentation#operation/createPromotionUsingPOST_1),

**Comment by PProtasewicz** [comment]
@PrzemyslawLukanowski Dzięki za odpowiedź :), to mi w zupełności wystarczy
