### ISSUE TITLE
[REST] zmiana statusów wszystkich aukcji na END

### ISSUE THREAD

**Issue by krzysztoffigiel** [allegro/allegro-api#732]
Dzień dobry,

Aktualnie zajmuje się problemem kończenia (zmiany statusu na `END`) wszystkich aukcji użytkownika. Stworzyłem metodę, która pobiera kolejne porcje 100 rekordów, wrzuca do tablicy `id` każdego z rekordu i przekazuje tą tablicę jako wartość pola `offers` tablicy `offerCriteria`, zgodnie z działaniem metody z `sale/offer-publication-commands/{commandId}`. Mając 100 tys. rekordów w bazie w bardzo szybkim tempie usunęło mi pierwsze 10 tys (około 50 rekordów na sekundę), a potem zwolniło usuwając około 1 rekord na sekundę. Dodatkowo w momencie usuwania (zmiany statusu na `END`) w pętli otrzymywałem komunikaty błędu: '_Serwer nie jest w stanie zrealizować zapytania. Spróbuj ponownie za kilka minut_' oraz '_Przekroczono czas wykonania zapytania. Spróbuj ponownie._'. 
Dodam, że zapytania realizuję na koncie produkcyjnym. Czy jest to spowodowane limitem czasowym requestów narzuconym na użytkownika? Jak inaczej można by zrealizować ten problem? Z góry dziękuję za odpowiedź.

**Comment by PawelTaberski** [comment]
Do weryfikacji potrzebowałbym pełnego cURL-a, responsa i trace-id przypadków z błędem. Podeślij proszę te dane przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) i zaznacz w zgłoszeniu, że informacje są potrzebne do zgłoszenia 732 na GitHub-ie. Sprawdzimy w czym jest problem.
