### ISSUE TITLE
WZA sandbox zniknęła forma dostawy GLS 

### ISSUE THREAD

**Issue by tomasz3k** [allegro/allegro-api#7320]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
 
Witam, po pewnym czasie na moim koncie testowym zniknęła metoda dostawy GLS z konta i nie mogę tworzyć tego typu przesyłek w WZA. Natomiast mogę przyjmować zamówienia z metodą dostawy GLS, bez możliwości utworzenia przesyłki. 
Mam dodaną umowę własną GLS i wcześniej tworzyłem przesyłki z serviceId 059c0d58-6cdb-4955-ab79-9031518f80f3#3b725557-89ab-4c5b-9806-26af8e202f56.

Podaję trace id z tworzenia przykładowej przesyłki przez restapi gdzie dostałem błąd "Wybrana metoda nie jest niewspierana". Pomijam nielogiczny komunikat. Aktualizując metody dostawy nie ma już na liście w ogóle przesyłek GLS. 

"trace-id": "6841b6e046b0601b"

Pytanie dlaczego i jak to rozwiązać?

**Comment by PrzemyslawLukanowski** [comment]
9 maja 2023 w Wysyłam z Allegro usunęliśmy opcję nadawania przesyłek GLS. Komunikację w tym temacie wysyłaliśmy do wszystkich sprzedawców, którzy mieli umowę z GLS.

**Comment by tomasz3k** [comment]
Niestety nie dostałem takiej informacji, czy sprzedawcy sandboxowi też dostali tę informację?

**Comment by PrzemyslawLukanowski** [comment]
Nie, komunikacja była wysyłana tylko do użytkowników środowiska produkcyjnego.
