### ISSUE TITLE
WZA problem z tworzeniem przesyłki paczkomatowej 

### ISSUE THREAD

**Issue by tomasz3k** [allegro/allegro-api#7321]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Tworząc przesyłkę z serviceId = 2488f7b7-5d1c-4d65-b85c-4cbcf253fd93#9f0daade-4501-4177-8d64-874d26935a10 dostaję błąd 

`{
            "code": "ANOTHER_SERVICE_NOT_AVAILABLE",
            "message": "One of required services is unavailable. Try again later.",
            "details": "One of required services is unavailable. Try again later.",
            "path": null,
            "userMessage": "Jeden z wymaganych serwisów, do poprawnego działania, jest niedostępny. Spróbuj ponownie za moment."
        }`

Dzieje się tak od kilku dni, proszę o informację w czym rzecz.

"trace-id": "f50870ee4dffa22a",

**Comment by PrzemyslawLukanowski** [comment]
Na umowie paczkomatowej próbujesz nadać zamówienie powiązane z metodą dostawy Kurier GLS, która to nie jest już wspierana w ramach Wysyłam z Allegro.

**Comment by tomasz3k** [comment]
Jak powiązane z metodą kurier gls?  

Mam zamówienie https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/zamowienia/05f9a7e0-ca2d-11ed-976e-d58829fa5220 z dostawą Allegro Paczkomaty InPost (Paczkomat KRA012)

Dodaję przesyłkę
`PUT https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/dd245149-f3d7-4a7c-bff5-53219642c416`

"serviceId": "2488f7b7-5d1c-4d65-b85c-4cbcf253fd93#9f0daade-4501-4177-8d64-874d26935a10"

i dostaję powyższy błąd. zamówienie nie jest powiązane z GLS.

**Comment by PrzemyslawLukanowski** [comment]
Oczywiście masz rację, przepraszam za pomyłkę, ale omyłko wziąłem pod uwagę logi z Twojego wcześniejszego wątku. W tym przypadku problemem jest data zamówienia i powiązany mail odbiorcy. Pochodzi ono z marca, a w miedzyczasie w naszej bazie na Sandboxie doszło do kilku wewnętrznych zmian, przez co wygenerowanie przesyłek dla zamówień z tego okresu nie jest już możliwe. Utwórz proszę nowe zamówienie i spróbuj wygenerować dla niego paczkę.
