### ISSUE TITLE
OfferAccessDeniedException Przy użyciu autoryzowanego konta firmowego. 

### ISSUE THREAD

**Issue by WSzoda** [allegro/allegro-api#7322]
Witam, spędzam już następną godzinę próbując doprowadzić skrypt do działania. Jednak sam chyba sobie nie dam z tym rady.

Na endpoint "/sale/product-offers/" wysyłam zapytanie typu PATCH. Wykorzystuję do tego aplikacje zweryfikowana poprzez OAuth grant-type: device_code. Konto użyte do weryfikacji aplikacji jest kontem firmowym i z niego stworzyłem ofertę. Podczas próby aktualizacji opisu oferty otrzymuję błąd typu "OfferAccessDeniedException" z wiadomoscią "Access denied. You are not authorized to perform operations on the indicated offer".  Kod wysyłajacy zapytanie wygląda jak poniżej. Z jakiego powodu request jest odrzucany ?
Przesyłane body ma taką postać: `{"description": {"sections": [{"items": [{"type": "IMAGE", "url": "https://a.allegroimg.com/original/11a065/9bd837034039b53cae6f2733636a"}]}]}}`

`    try:
        url = 'https://api.allegro.pl/sale/product-offers/' + id
        headers = {'Accept': 'application/vnd.allegro.public.v1+json',
                   'Content-Type': 'application/vnd.allegro.public.v1+json',
                   'Authorization': 'Bearer ' + token}
        api_call_response = requests.patch(url, headers=headers, data=result)
        print(json.loads(api_call_response.text))
    except requests.exceptions.HTTPError as err:
        file.close()
        raise SystemExit(err)`

**Comment by MaciejFrackowiak** [comment]
Oferta, którą próbujesz edytować należy do innego użytkownika aniżeli token, którego używasz do wykonania requestu i dlatego otrzymujesz błąd 403.

**Comment by WSzoda** [comment]
Wytworzyłem token używajac konta z którego stworzyłem ofertę. W jaki sposób może należeć do innego użytkownika?

**Comment by MaciejFrackowiak** [comment]
Jednoznacznie widzimy, że wykonując PATCH jesteś zautoryzowany na koncie B, a oferta należy do konta A. Musisz sprawdzić zatem jaki token przekazujesz podczas wywoływania zasobu.

**Comment by WSzoda** [comment]
Mam tylko jedno konto, w jaki sposób mogę pobierać token dla innego konta niż jedyne posiadane ?

**Comment by MaciejFrackowiak** [comment]
Sprawdź proszę proces uzyskiwania autoryzacji, czy przypadkiem nie wyraziłeś zgody na działanie aplikacji z innego konta. Nam nie sposób to stwierdzić - widzimy tylko dane konta B, które chce dokonywać zmian w ofercie wystawionej z konta A.
