### ISSUE TITLE
Filtrowanie ofert bez sprzedaży powyżej 3 miesięcy

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#7324]
Proszę o podpowiedź. Czy istnieje możliwość z poziomu API wyfiltrować oferty bez sprzedaży, np. powyżej 3 miesięcy? Potrzebuje pobrać ID ofert, które nie miały żadnej sprzedaży przez zadeklarowany czas (w tym przypadku 3 miesiące)

**Comment by MaciejFrackowiak** [comment]
Korzystając z [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) możesz wyfiltrować oferty tylko korzystając z pola "stock.sold", czyli po liczbie sprzedanych sztuk z ostatnich 30 dni.

**Comment by hahyes** [comment]
@mateuszcom Bez cache'owania danych w bazie czy gdziekolwiek niestety nie ma szans, aby to osiągnać. Zapisując informacje o ofertach w bazie danych oraz korelując to z zamówieniami można zorientować się, jakie oferty nie miały żadnej sprzedaży w określonym okresie.

**Comment by mateuszcom** [comment]
@hahyes dzięki za sugestię, tak właśnie myślałem, że będzie z tym więcej zabawy :)
