### ISSUE TITLE
Aktywacja konta Sandbox

### ISSUE THREAD

**Issue by Bmitruk13** [allegro/allegro-api#7325]
Cześć!

Czy mogę prosić o aktywacje konta w Allegro Sandbox.
Z góry wielkie dziękuję!

Login: bezkartek-com
Email: kontakt@bezkartek.com

**Comment by MaciejFrackowiak** [comment]
Nie mamy takiego konta w bazie - czy potwierdziłeś rejestrację konta klikając w link załączony do maila?

**Comment by Bmitruk13** [comment]
Tak, rzeczywiście moja wina, proszę sprawdzić teraz czy widać konto.

**Comment by MaciejFrackowiak** [comment]
Konto widać, jednak teraz musisz uzupełnić tzw. [krokowiec](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta), czyli wykonać przelew weryfikacyjny oraz przesłać dowolne pliki jako dokumenty.

**Comment by Bmitruk13** [comment]
@MaciejFrackowiak Dzięki z podpowiedz, wypełniłem cały "krokowiec" ale konto od 2 dni nie przeszło weryfikacje. Jesteś w stanie mi pomóc?

**Comment by MaciejFrackowiak** [comment]
Konto już zweryfikowałem.
