### ISSUE TITLE
Spis najczęstszych błędów 

### ISSUE THREAD

**Issue by PProtasewicz** [allegro/allegro-api#7326]
Witam,

mam do was kolejne pytanie, czy macie gdzieś jakiś spis najczęstszych błędów, które są związane z zamówieniami ?

Pozdrawiam
Piotr

**Comment by MaciejFrackowiak** [comment]
Nie, nie mamy takiej listy.

**Comment by PProtasewicz** [comment]
@MaciejFrackowiak Ok, rozumiem, dzięki za info
