### ISSUE TITLE
Product Proposals Error

### ISSUE THREAD

**Issue by dgkdev** [allegro/allegro-api#7327]
Hello, I would like to add a product using an API on a sandbox, but I'm getting an error like the one below. I'm obtaining an access token using device authorization, but when I try to add a product, it gives me this error. Can you please help me?

Client:106018578
omer@navisio.net

`errors: [
    {
      code: 'AccessDeniedException',
      message: 'Access denied.',
      details: null,
      path: null,
      userMessage: 'No access.'
    }
  ]`

**Comment by dgkdev** [comment]
I'm not receiving a verification code on my phone number (Turkey phone number). I have provided the other information.

**Comment by MaciejFrackowiak** [comment]
As a code, on the Sandbox please use 123456.

**Comment by dgkdev** [comment]
Ok, I received an email stating that my account has been activated, thank you. Now the error message in my request has changed. I'm getting a "Required parameter exception" and I will take care of fixing it. If I encounter any issues, I will open another issue. Thank you for your assistance.

**Comment by ithw23** [comment]
Hello, unfortunately I also get the error "{"errors":[{"code":"AccessDeniedException","message":"Access denied.","details":null,"path":null,"userMessage": "No access."}]}". It looks to me like I provided all the required information in the sandbox account. Can you please tell me what information is still missing? The account name is "Client:105944468"

**Comment by MaciejFrackowiak** [comment]
@ithw23 Your account is active now.

**Comment by ithw23** [comment]
Thanks, now it works.
