### ISSUE TITLE
i need help with allegro catalog

### ISSUE THREAD

**Issue by hopesf** [allegro/allegro-api#7328]
When creating a new product, I created a product using the "product Set" parameter.
But I am a bit of a beginner and I created the catalog incorrectly.
Is there a way I can delete or edit the catalogs I have created?

Thanks

**Comment by MaciejFrackowiak** [comment]
You can only propose a change in the existing product via [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal).

**Comment by hopesf** [comment]
very silly situation

**Comment by MaciejFrackowiak** [comment]
When you create a product, this product is available for everyone, so we cannot give an opportunity to remove it, because someone could assign it before to its offer.
