### ISSUE TITLE
Błędne parametry Allegro

### ISSUE THREAD

**Issue by JiriVyhnalek** [allegro/allegro-api#7329]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam,
Używamy BaseLinkera do wystawiania produktów w Allegro. Nie jesteśmy w stanie sparować parametrów (konkretnie koloru) podczas wystawiania produktów.

Podam przykład, który udokumentuję w załączniku:
Dwa produkty, jeden z listkiem, drugi bez. Parametry obowiązkowe wypełnione wszystkie. Kolory są poprawnie zapisane w parametrach jako brązowy (hnědá) i szary (šedá). Brązowy jest w porządku i produkt przechodzi, ale Szary nie przechodzi, ponieważ menu parametrów Allegro to Szary, a reguła działa z wartością Szary, która nie pasuje.

Prawidłowo nazwy kolorów powinny być w menu:
- modrý = modrá
- oranžový = oranžová
- stříbrný = stříbrná
- šedý = šedá
- zlatý = zlatá

Dziękuję za odpowiedź

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale bez konkretnych przykładów, logów, niewiele mogę pomóc. Jako że korzystają Państwo z BaseLinkera, prosiłbym o zgłoszenie tego problemu do wsparcia tej aplikacji. Jeśli zostaną stwierdzone nieprawidłowości po naszej stronie, wsparcie dostarczy nam logi niezbędne do weryfikacji problemu. W takiej postaci jak wyżej zgłoszenie jest dla nas niestety opisane zbyt ogólnie.

**Comment by JiriVyhnalek** [comment]
Poprosiłem o przesłanie żądanego egzemplarza. Konkretny przykład, który ci wysłałem, to błąd w tłumaczeniu... "modrý" x "modrá" = niebieski x niebieski. Problem polega na tym, że "modrý" nie jest kolorem.

**Comment by PrzemyslawLukanowski** [comment]
Czyli prawidłowa nazwa wartości parametru to "modrá" i masz na myśli błędy w tłumaczeniu czeskich wartości? Prawidłowe to te, które wymieniłeś po prawej stronie? Czy możesz wskazać kategorię, w której ten problem występuje? Bez tego trudno będzie nam je namierzyć.

**Comment by JiriVyhnalek** [comment]
Tak, jak mówisz. Mamy asortyment w kategorii Odzież, Obuwie, Akcesoria, ale myślę, że będzie też w innych miejscach.

**Comment by PrzemyslawLukanowski** [comment]
Ok, dziękuję. Przekażę ten temat dalej do odpowiedniego zespołu - nie jest on stricte związany z API, ale z parametrami w ramach całego Allegro.

**Comment by PrzemyslawLukanowski** [comment]
Poprawiliśmy nazewnictwo wartości w parametrze, dziękuję za zgłoszenie tego błędu.

**Comment by JiriVyhnalek** [comment]
Witam, czy wiadomo kiedy zmiana zostanie zakończona? To blokuje połowę naszego zasięgu... dziękuję.

**Comment by PrzemyslawLukanowski** [comment]
Po naszej stronie poprawiliśmy nazewnictwo tych wartości, możesz to zweryfikować na naszej stronie. Jeśli widzisz jeszcze jakieś kategorie, które wymagają zmian w nazwach wartości parametrów, daj proszę znać które to. Jeśli natomiast problem dotyczy stricte wystawia produktów w Baselinkerze, zgłoś proszę ten problem do ich wsparcia.
