### ISSUE TITLE
REST - Pytanie

### ISSUE THREAD

**Issue by mbx88** [allegro/allegro-api#733]
Witam,
czy planujecie Państwo wprowadzić w nowym api restowym lub może już jest to dostępne, aczkolwiek nie znalazłem tego w dokumentacji:
- możliwość filtrowania po ofertach promowanych
- możliwość sprawdzenia liczby sprzedanych przedmiotów w konkretnych przedziałach czasowych?

**Comment by PawelTaberski** [comment]
Przykładowo przy użyciu metody[ GET na zasobie /offers/listing](https://developer.allegro.pl/documentation/#/offers-listing/getListing) możesz wyszukać oferty ze strefy marek z monetami itp. Metoda ta jest odzwierciedleniem wyszukiwarki na froncie. 
Ilość sprzedanych ofert to już zależy w jaki sposób skorzystasz z metod do zarządzania zamówieniami. Opisaliśmy je w tym [poradniku ](https://developer.allegro.pl/orders/). Nie ma jednej metody w której określisz sobie, że chciałbyś wiedzieć ile w terminie od do sprzedałeś przedmiotów. Obecnie nie planujemy wdrożenia takiej metody.
