### ISSUE TITLE
Not getting allegro REST API Category tree | Error "Cannot convert access token to JSON"

### ISSUE THREAD

**Issue by Wooconnector** [allegro/allegro-api#7333]
I am currently facing an issue while attempting to retrieve the category list from the Allegro REST API. When using the sandbox URL, specifically "$categoriesUrl = 'https://api.allegro.pl.allegrosandbox.pl/sale/categories';," I am encountering an error stating, "Cannot convert access token to JSON." However, when I attempt to use the live URL, which is "$categoriesUrl = 'https://api.allegro.pl/categories';," I receive a different error. I have already explored various discussions and suggestions on GitHub regarding this matter, but unfortunately, none of the provided solutions have resolved my problem.

The PHP code that I'm trying to initiate :
$categoriesUrl = 'https://api.allegro.pl.allegrosandbox.pl/sale/categories';
// $categoriesUrl = 'https://api.allegro.pl.allegrosandbox.pl/';
$ch = curl_init($categoriesUrl);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true );
curl_setopt($ch, CURLOPT_HTTPHEADER, [
"Authorization: Bearer " . $accessToken,
"Accept: application/vnd.allegro.public.v1+json",
]);
// Execute the request
$response = curl_exec($ch);
curl_close($ch);
if ($response !== false) {
$responseData = json_decode($response, true);
echo "&lt;pre&gt;";
print_r( $responseData );
if (isset($responseData['categories'])) {
$categories = $responseData['categories'];
foreach ($categories as $category) {
echo $category['id'] . ' - ' . $category['name'] . "\n";
}
} else {
echo 'Failed to retrieve categories.';
}
} else {
echo 'cURL request failed.';
}

**Comment by MaciejFrackowiak** [comment]
It looks like you used a token from the production environment on the Sandbox - you should generate a token valid on the Sandbox.

**Comment by Wooconnector** [comment]
Now I'm getting " Not acceptable representation requested. Please check 'Accept' request header" with live site token when I'm trying to access REST Api

**Comment by MaciejFrackowiak** [comment]
Please, check Accept header value - it should be "application/vnd.allegro.public.v1+json".

**Comment by Wooconnector** [comment]
Thanks It Worked !!!
