### ISSUE TITLE
Aktywacja konta allegro sandbox

### ISSUE THREAD

**Issue by DORA-ZOO** [allegro/allegro-api#7334]
Cześć!

Czy mogę prosić o aktywacje konta biznesowego w Allegro Sandbox?

Login: l0g1n

Pozdrawiam,
Dawid

**Comment by MaciejFrackowiak** [comment]
Zmigrowałeś się na konto firmowe, jednak wybrałeś opcję ze sprzedażą okazjonalną - proszę przejdź na pełną weryfikację bym mógł aktywować w pełni to konto. Zrobisz to m.in. w zakładce [Środki i historia operacji](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/srodki-i-historia-operacji).

**Comment by DORA-ZOO** [comment]
Miałem pewne problemy z weryfikacją powyższego konta.
Proszę o aktywowanie konta o loginie: 
dorasandbox

Ustawiłem tam pełną weryfikację.

**Comment by MaciejFrackowiak** [comment]
Konto aktywowane.

**Comment by kolszowskiEUP** [comment]
Dzień dobry, mam taki sam problem.

Mogę prosić o aktywację konta biznesowego?
Login: autozlomsandbox
Email: autozlomallegrosandbox.b@gmail.com

Z góry dziękuję.

**Comment by MaciejFrackowiak** [comment]
@kolszowskiEUP Konto zweryfikowane.

**Comment by kolszowskiEUP** [comment]
@MaciejFrackowiak Dziękuję, działa poprawnie :D

**Comment by lukoc** [comment]
Proszę o aktywację sandboxowego konta o loginie "kociak"

**Comment by AureliuszBrussy** [comment]
@lukoc aktywowałem Twoje konto.

**Comment by bugproof** [comment]
Login: autoparts2023
Przy próbie dodania oferty api mam błąd OfferAccessDeniedException
