### ISSUE TITLE
Odbiór osobisty w punkcie sprzedawcy a zmiana statusu na "Przesyłka odebrania"

### ISSUE THREAD

**Issue by egro-allegro** [allegro/allegro-api#7335]
Dzień dobry.
Mam pytanie, w jaki sposób odczytać status potwierdzenia przez klienta odebrania przesyłki w punkcie sprzedawcy?
Mam zamówienie id: 328b21f0-1b1b-11ee-b246-f3b72c2fe790, gdzie zostało potwierdzone przez klienta odebranie przesyłki w punkcie, a API ciągle zwraca mi "fulfillment":{"status":"PROCESSING","shipmentSummary":{"lineItemsSent":"NONE"}}
![1688634661677](https://github.com/allegro/allegro-api/assets/105212868/0b495dd3-a539-4d18-9a70-95a3fbe89873)

**Comment by PrzemyslawLukanowski** [comment]
`fulfullment.status`, o którym wspomniałeś, to status realizacji zamówienia w pełni zarządzany przez sprzedawcę za pomocą [PUT /order/checkout-forms/{id}/fulfillment](https://developer.allegro.pl/documentation/#operation/setOrderFulfillmentUsingPUT). Więcej informacji na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#zmiana-statusu-realizacji-zamowienia). Nie jest on odzwierciedleniem historii statusów przesyłki. Historię statusów sprawdzisz w ramach endpointu [GET /order/carriers/{carrierId}/tracking?waybill={waybill}](https://developer.allegro.pl/documentation/#operation/getParcelTrackingUsingGET), jednak ma on zastosowanie wyłącznie dla przesyłek przewoźników nadanych w ramach Wysyłam z Allegro.

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie, nie ma takiej możliwości.
