### ISSUE TITLE
Allegro one box

### ISSUE THREAD

**Issue by programistaAndrzej** [allegro/allegro-api#7337]
Cześć jeden z naszych klientów ma kilka kont i listy z naszej aplikacji generują się bez problemu z wyjątkiem jednego konta, pojawia się komunikat, że metoda jest niedostępna- wczoraj według informacji było wszystko ok i działało

[{"code":"VALIDATION_ERROR","message":"Order delivery method: 0aafb43c-e66a-46ec-9cc4-29bb39ebb483 is not allowed","details":null,"path":"/serviceId","userMessage":"Metoda dostawy jest niedostępna"}]

Dodam, że tworzenie listu ze strony Allegro dział bez problemu. Podpowiecie co się mogło zmienić?

**Comment by PrzemyslawLukanowski** [comment]
Poproszę o commandId lub trace-id powiązane z tym błędem. Pozwoli nam to zweryfikować ten przypadek.

**Comment by programistaAndrzej** [comment]
e0694415-6fe5-4a07-b198-1b7936e4c44c

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, kupujący wybrał metodę dostawy Allegro One Box, One Kurier (0b9bed2c-0bc1-4e1f-9694-29bb39ebb483), zatem przesyłka musi zostać nadana w ramach service ID o tej samej wartości.
