### ISSUE TITLE
Zwroty kliencie - pobieranie po dacie

### ISSUE THREAD

**Issue by ZJK2177** [allegro/allegro-api#7338]
chciałbym pobrać zwroty klienckie z ostatnich 30 dni 

parametry zapytania wyglądają następująco
```
    params = {
        'limit': 1000,
        'createdAt_gte': 20230606 <- przykładowa data (wprowadzana akurat z palca)
    }
```
Jednak zapytanie zwraca zwroty od początku listy (od najstarszych) w dodatku przy limicie 1000, czy nawet później jak zmieniłem na 100 zwracane jest dokładnie `"count": 8301,`

**Comment by PrzemyslawLukanowski** [comment]
W `count` zwracamy zawsze łączną liczbę zwrotów na koncie, zatem nie jest to wartość związana z parametrem `limit`. Jeśli chodzi natomiast o drugi parametr, to używasz podkreślnika zamiast kropki, czyli prawidłowa nazwa parametru to `createdAt.gte `. Wartość, którą w nim przekazujesz musi być w formacie ISO860, czyli np. `2023-03-10T00:00:00Z`.

**Comment by ZJK2177** [comment]
Okej, dziękuje za pomoc, przepraszam za moje niedopatrzenie.

**Comment by PrzemyslawLukanowski** [comment]
Żaden problem, pozdrawiam.
