### ISSUE TITLE
Problem ze wznowieniem oferty poprzez API (produkcja)

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#7339]
Mam problem ze wznowieniem kilku ofert poprzez API na produkcyjnym Allegro. Korzystam z PATCH /sale/product-offers/{idOfferAllegro}. Cały czas otrzymuję komunikat: The limit of 16 images has been exceeded. W tym problem, że przekazuję 11 zdjęć. Proszę o pomoc. Trace-id: 483dec23b8fcdf17. W innym przypadku mam ten sam komunikat przy 9 zdjęciach. Z innymi ofertami nie ma problemu

**Comment by MaciejFrackowiak** [comment]
Do limitu 16 zdjęć wliczają się również zdjęcia dołączone do produktu. Jak widzę produkt przypisany do edytowanej oferty ma 10 zdjęć, zatem gdy przekazujesz swoich 11 zdjęć to łącznie przekroczony jest limit 16.

**Comment by mateuszcom** [comment]
A czy istnieje możliwość, aby nie korzystać ze zdjęć z katalogu? W wielu przypadkach zdjęcia w katalogu są słabej jakości, a sklep posiada np. własne zdjęcia wykonane przez fotografa. W tym przypadku nie byłoby możliwe użycie takich zdjęć

**Comment by MaciejFrackowiak** [comment]
Oczywiście tak. W takim przypadku w polu "product.images" należy przekazać pustą tablicę.

**Comment by mateuszcom** [comment]
W tym przypadku przekazujemy pustą tablicę a pomimo tego i tak wyskakuje komunikat. Trace ID jest w pierwszej wiadomości. Proszę o pomoc, może coś źle przekazujemy, ale dopiero od krótkiego czasu mamy z tym problem - wcześniej nigdy takie coś nam się nie pojawiało

**Comment by MaciejFrackowiak** [comment]
Niestety, nie widzę pełnego Twojego requestu - sprawdź proszę, czy w opisie samej oferty nie przekroczyłeś również limitu 16 zdjęć.

**Comment by mateuszcom** [comment]
Pełny request przesyłam jako załączniku
[request.zip](https://github.com/allegro/allegro-api/files/11977296/request.zip)

**Comment by MaciejFrackowiak** [comment]
Możesz dodać do galerii oferty maksymalnie 16 zdjęć i tylko 16 zdjęć użyć w samym opisie oferty. Jak dobrze policzyłem w Twojej sekcji "description" użyłeś łącznie 35 zdjęć - i stąd komunikat błędu.

**Comment by mateuszcom** [comment]
Dziękuję, już wszystko jasne

**Comment by mateuszcom** [comment]
> Możesz dodać do galerii oferty maksymalnie 16 zdjęć i tylko 16 zdjęć użyć w samym opisie oferty. Jak dobrze policzyłem w Twojej sekcji "description" użyłeś łącznie 35 zdjęć - i stąd komunikat błędu.

Proszę o wskazanie miejsca gdzie znajduje się oficjalna informacja, że w opisie oferty można użyć tylko 16 zdjęć. Szukam, ale nigdzie nie mogę nic odszukać - jedynie jest informacja, że galeria może mieć maksymalnie 16 zdjęć. Galeria, to nie to samo co sekcje

**Comment by MaciejFrackowiak** [comment]
Proszę uprzejmie: https://allegro.pl/dla-sprzedajacych/zasady-dla-zdjec-w-galerii-i-w-opisie-YLlAAa2oXf7
