### ISSUE TITLE
Parameter does not exist

### ISSUE THREAD

**Issue by justynapalka** [allegro/allegro-api#7340]
Dzień dobry,
przy przesyłniu feeda przez API otrzymujemy poniższy bład.
Proszę o informacje czy po usunieciu parametru, który wyświetla się w błedzie, oferta zostanie wystawiona? Czy może w strukturze feeda cos dodatkwoego jest do zmiany?

**ERROR**:
{"errors":[{"code":"ParameterException.ParameterDoesNotExistException","message":"An error has occurred","details":null,"path":"parameters","userMessage":"Parameter 333 does not exist."}]}

**FEED**:
{
    "name": "Damska koszulka szybkoschn\u0105ca Defy II",
    "category": {
        "id": "19638"
    },
    "images": [
        {
            "url": "https:\/\/a.allegroimg.com\/original\/1105a3\/90b0086345cf9377676e5b56bd01"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/110de9\/29dc6df94ac9a3fc28e139a39cfc"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/110fbd\/c9a73d534f2f8f6cf9bbe497824a"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/111ae6\/cf98893c44749f6648cfcc3a0c98"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/112c9c\/1010ebb6422492d2e5c6fdc4de23"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/113577\/9cd73bad4bfa969a1a2265031780"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/118d1c\/b3c79e724efaa657a91936149ca4"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11c138\/228841e747fc92c882f9c466b155"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11dee1\/d5a6297a49a0928081f831d2b7e3"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11e11d\/976773db4a23bf23ccf5b3f90bce"
        }
    ],
    "parameters": [
        {
            "id": "224017",
            "values": [
                "DWT639"
            ]
        },
        {
            "id": "130411",
            "valuesIds": [
                "130411_1"
            ]
        },
        {
            "id": "333",
            "valuesIds": [
                "333_2"
            ]
        },
        {
            "id": "129293",
            "valuesIds": [
                "129293_5"
            ]
        },
        {
            "id": "25929",
            "valuesIds": [
                "25929_8"
            ]
        },
        {
            "id": "215930",
            "values": [
                ""
            ]
        },
        {
            "id": "237206",
            "values": [
                ""
            ]
        },
        {
            "id": "237210",
            "values": [
                "Defy"
            ]
        },
        {
            "id": "54",
            "valuesIds": [
                "3806_3"
            ]
        },
        {
            "id": "225693",
            "values": [
                "5059404590339"
            ]
        }
    ],
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h1>Dare 2b - Damska koszulka szybkoschn\u0105ca Defy II<\/h1><p>Lekka koszulka Defy II od Dare 2b. Wykonana z bardzo lekkiego materia\u0142u, kt\u00f3ry odprowadza pot i wilgo\u0107 ze sk\u00f3ry oraz chroni przed bakteriami powoduj\u0105cymi nieprzyjemny zapach, zapewniaj\u0105c ch\u0142\u00f3d i \u015bwie\u017co\u015b\u0107 przez ca\u0142y trening. Odblaskowe detale, dzi\u0119ki kt\u00f3rym b\u0119dziesz widoczny podczas nocnych bieg\u00f3w.<\/p><p><b>Zalety produktu:<\/b><\/p><p>Odprowadzanie potu: Odprowadza wilgo\u0107 na zewn\u0105trz, zapewniaj\u0105c sucho\u015b\u0107 i komfort.<\/p><p>Zr\u00f3wnowa\u017cony: Zr\u00f3wnowa\u017cona produkcja z wykorzystaniem poliestru pochodz\u0105cego z recyklingu plastikowych butelek<\/p><p>Odblaskowy: Odblaskowe wyko\u0144czenia zwi\u0119kszaj\u0105 widoczno\u015b\u0107 w warunkach niedostatecznego o\u015bwietlenia<\/p><ul><li>Lekka tkanina poliestrowa Q-Wic odprowadza pot i przyspiesza schni\u0119cie<\/li>\r\r\r\n<li>Pozosta\u0144 widoczny dzi\u0119ki odblaskowym nadrukom<\/li>\r\r\r\n<\/ul><p><b>Przeznaczenie:<\/b><\/p><p>Si\u0142ownia i Fitness, Bieganie, Joga<\/p><p><b>Materia\u0142:<\/b><\/p><p>95% Poliester, 5% Elastan<\/p>"
                    }
                ]
            }
        ]
    },
    "language": "pl-PL"
}

**ERROR:**
{"errors":[{"code":"ParameterException.ParameterDoesNotExistException","message":"An error has occurred","details":null,"path":"parameters","userMessage":"Parameter 2974 does not exist."}]}

{
    "name": "M\u0119ska kurtka zimowa przeciwdeszczowa Faizan",
    "category": {
        "id": "5537"
    },
    "images": [
        {
            "url": "https:\/\/a.allegroimg.com\/original\/111283\/f2ed34ad408d833d5feeb882446d"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11259b\/b08689ec44b4bd3e5238008abdbe"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/1129a3\/d5918fd24e4b82b8667aa1610158"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/112d35\/e64723964c5b91683ada54883fff"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/115322\/083631db4fe49b716d9e2e34ece9"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/117d23\/6bea2b0844f6afe8a311bfe0f9dc"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/1193f5\/55e5a4c0425fb7a59081443a275d"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11aeb4\/c85f971b436eb603d8e9b54cbd9b"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11ba41\/a7e1e0354ccebd5ce358a2fd0ff8"
        }
    ],
    "parameters": [
        {
            "id": "224017",
            "values": [
                "RMP332"
            ]
        },
        {
            "id": "15851",
            "valuesIds": [
                "15851_2"
            ]
        },
        {
            "id": "202897",
            "valuesIds": [
                "202897_32"
            ]
        },
        {
            "id": "201405",
            "valuesIds": [
                "201405_208161"
            ]
        },
        {
            "id": "201017",
            "valuesIds": [
                "201017_2377"
            ]
        },
        {
            "id": "2974",
            "valuesIds": [
                "2974_1"
            ]
        },
        {
            "id": "202893",
            "valuesIds": [
                "202893_214333"
            ]
        },
        {
            "id": "3786",
            "valuesIds": [
                "3786_224"
            ]
        },
        {
            "id": "201025",
            "valuesIds": [
                "201025_380485"
            ]
        },
        {
            "id": "22133",
            "valuesIds": [
                "221333_295205"
            ]
        },
        {
            "id": "3766",
            "valuesIds": [
                "3766_1"
            ]
        },
        {
            "id": "215930",
            "values": [
                "100% Poliester"
            ]
        },
        {
            "id": "237206",
            "values": [
                "Faizan"
            ]
        },
        {
            "id": "215926",
            "values": [
                "Faizan"
            ]
        },
        {
            "id": "54",
            "valuesIds": [
                "54_4"
            ]
        },
        {
            "id": "225693",
            "values": [
                "5059404844302"
            ]
        }
    ],
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h1>Regatta - M\u0119ska kurtka zimowa przeciwdeszczowa Faizan<\/h1>\n<p>Stylowa, wodoodporna i ocieplana, nasza m\u0119ska kurtka bomberka Faizan zapewnia modny wygl\u0105d. Dzi\u0119ki naszej wodoodpornej i oddychaj\u0105cej tkaninie Isotex 8000 chroni przed wilgoci\u0105 i zapewnia uczucie \u015bwie\u017co\u015bci, a wype\u0142nienie Thermoguard utrzymuje ciep\u0142o, nawet gdy zima atakuje z moc\u0105. Ca\u0142o\u015bci dope\u0142nia stylowy kr\u00f3j bomberki.<\/p>\n<p><b>Zalety produktu:<\/b><\/p>\n<p>Ciep\u0142y: Utrzymuje ciep\u0142o i komfort w ch\u0142odniejszych warunkach klimatycznych<\/p>\n<p>Wodoodporny i oddychaj\u0105cy: Chroni przed wilgotno\u015bci\u0105, pozwalaj\u0105c parze wodnej wydosta\u0107 si\u0119 przez tkanin\u0119<\/p>\n<p>Klejone szwy: Zwi\u0119ksza ochron\u0119 wodoodporn\u0105 odzie\u017cy<\/p>\n<p><b>Technologia:<\/b><\/p>\n<p>Isotex: Wodoodporna, oddychaj\u0105ca i wiatroszczelna technologia membranowa<\/p>\n<p>Thermoguard: Szybkoschn\u0105ca izolacja z w\u0142\u00f3kien syntetycznych, kt\u00f3ra zatrzymuje powietrze<\/p>\n<p>Tkanina z recyklingu: Wykonane z recyklingowanych plastikowych butelek<\/p>\n<p><\/p>"
                    }
                ]
            }
        ]
    },
    "language": "pl-PL"
}:
{
    "name": "M\u0119ska kurtka zimowa przeciwdeszczowa Faizan",
    "category": {
        "id": "5537"
    },
    "images": [
        {
            "url": "https:\/\/a.allegroimg.com\/original\/111283\/f2ed34ad408d833d5feeb882446d"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11259b\/b08689ec44b4bd3e5238008abdbe"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/1129a3\/d5918fd24e4b82b8667aa1610158"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/112d35\/e64723964c5b91683ada54883fff"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/115322\/083631db4fe49b716d9e2e34ece9"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/117d23\/6bea2b0844f6afe8a311bfe0f9dc"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/1193f5\/55e5a4c0425fb7a59081443a275d"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11aeb4\/c85f971b436eb603d8e9b54cbd9b"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11ba41\/a7e1e0354ccebd5ce358a2fd0ff8"
        }
    ],
    "parameters": [
        {
            "id": "224017",
            "values": [
                "RMP332"
            ]
        },
        {
            "id": "15851",
            "valuesIds": [
                "15851_2"
            ]
        },
        {
            "id": "202897",
            "valuesIds": [
                "202897_32"
            ]
        },
        {
            "id": "201405",
            "valuesIds": [
                "201405_208161"
            ]
        },
        {
            "id": "201017",
            "valuesIds": [
                "201017_2377"
            ]
        },
        {
            "id": "2974",
            "valuesIds": [
                "2974_1"
            ]
        },
        {
            "id": "202893",
            "valuesIds": [
                "202893_214333"
            ]
        },
        {
            "id": "3786",
            "valuesIds": [
                "3786_224"
            ]
        },
        {
            "id": "201025",
            "valuesIds": [
                "201025_380485"
            ]
        },
        {
            "id": "22133",
            "valuesIds": [
                "221333_295205"
            ]
        },
        {
            "id": "3766",
            "valuesIds": [
                "3766_1"
            ]
        },
        {
            "id": "215930",
            "values": [
                "100% Poliester"
            ]
        },
        {
            "id": "237206",
            "values": [
                "Faizan"
            ]
        },
        {
            "id": "215926",
            "values": [
                "Faizan"
            ]
        },
        {
            "id": "54",
            "valuesIds": [
                "54_4"
            ]
        },
        {
            "id": "225693",
            "values": [
                "5059404844302"
            ]
        }
    ],
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h1>Regatta - M\u0119ska kurtka zimowa przeciwdeszczowa Faizan<\/h1>\n<p>Stylowa, wodoodporna i ocieplana, nasza m\u0119ska kurtka bomberka Faizan zapewnia modny wygl\u0105d. Dzi\u0119ki naszej wodoodpornej i oddychaj\u0105cej tkaninie Isotex 8000 chroni przed wilgoci\u0105 i zapewnia uczucie \u015bwie\u017co\u015bci, a wype\u0142nienie Thermoguard utrzymuje ciep\u0142o, nawet gdy zima atakuje z moc\u0105. Ca\u0142o\u015bci dope\u0142nia stylowy kr\u00f3j bomberki.<\/p>\n<p><b>Zalety produktu:<\/b><\/p>\n<p>Ciep\u0142y: Utrzymuje ciep\u0142o i komfort w ch\u0142odniejszych warunkach klimatycznych<\/p>\n<p>Wodoodporny i oddychaj\u0105cy: Chroni przed wilgotno\u015bci\u0105, pozwalaj\u0105c parze wodnej wydosta\u0107 si\u0119 przez tkanin\u0119<\/p>\n<p>Klejone szwy: Zwi\u0119ksza ochron\u0119 wodoodporn\u0105 odzie\u017cy<\/p>\n<p><b>Technologia:<\/b><\/p>\n<p>Isotex: Wodoodporna, oddychaj\u0105ca i wiatroszczelna technologia membranowa<\/p>\n<p>Thermoguard: Szybkoschn\u0105ca izolacja z w\u0142\u00f3kien syntetycznych, kt\u00f3ra zatrzymuje powietrze<\/p>\n<p>Tkanina z recyklingu: Wykonane z recyklingowanych plastikowych butelek<\/p>\n<p><\/p>"
                    }
                ]
            }
        ]
    },
    "language": "pl-PL"
}

**Comment by PrzemyslawLukanowski** [comment]
Po usunięciu tego parametru otrzymasz także błąd informujący o pustych elementach - chodzi o parametry 215930 i 237206, które definiujesz w requeście, ale nie przekazujesz w nich żadnych wartości.

Wygląda na to, że korzystasz z POST /sale/offers, więc korzystając z okazji, chciałbym przypomnieć, że m.in. ten endpoint wygasimy z końcem 2023. Zachęcam do uwzględnienia w planach prac migrację na odpowiednie zasoby /sale/product-offers. Więcej informacji znajdziesz w [naszym newsie](https://developer.allegro.pl/news/na-poczatku-2024-roku-wylaczymy-zasoby-sale-offers-sluzace-do-tworzenia-i-edycji-ofert-BvqK3XOaEcW).

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry,
Komunikat wskazuje, że parametry nie występują w kategorii, w której próbujecie wystawić ofertę, Aktualne parametry sprawdzicie za pomocą [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2). Rekomendujemy aktualizację drzewa kategorii i parametrów możliwie często, ponieważ może w nim dochodzić do drobnych zmian.
