### ISSUE TITLE
"The request failed due to failure of a previous request.","code":"SC424" Integromat

### ISSUE THREAD

**Issue by michasiatko** [allegro/allegro-api#7341]
Cześć!

Mam problem z autoryzacją oAuth w Make.com (dawny Integromat)- niezależnie od kombinacji ustawień zawsze dostaję kod błędu:

`{"message":"The request failed due to failure of a previous request.","code":"SC424","suberrors":[{"message":"\"Unauthorized\"","name":"Error"}]}`

State callback'a= 30d76464071d5efe02d7

Myślałem, że jest to problem nieumiejętnej konfiguracji jednak korzystając z dokładnie tak samo skonfigurowanego ustawienia autoryzacji w Postmanie wszystko przechodzi bez najmniejszych problemów... 

Próbując analizować co może powodować błąd przychodzą mi dwie opcje.

1. Make.com wysyła niepoprawne żądanie Authorize i cały proces się wysypuje- możliwe aczkolwiek mocno wątpliwe bo stworzyliście logowanie zgodnie z standardem którego również używa Postman w podstawowej konfiguracji bez żadnych dodatkowych parametrów i zmian a taka właśnie działa. 

2. Adresy Make.com są zablokowane na Waszych serwerach przez zbyt wiele prób dokonanych przez innych użytkowników.

Authorize URI z którego korzystam- https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize

Token URI- https://allegro.pl.allegrosandbox.pl/auth/oauth/token

Nie przesyłam żadnych dodatkowych danych poza nazwą tokenu w nagłówku (Authorization). 

Problem występuje zarówno na środowisku testowym jak i produkcyjnym.

Wrzucam zrzuty ekranu z Make- może komuś coś wpadnie do głowy na ich widok czego jeszcze mógłbym spróbować. 
Próbowałem dodawać parametry autoryzacji- response_type i redirect_uri- brak efektów. 

_Główna konfiguracja:_
![Zrzut ekranu 2023-07-7 o 23 11 49](https://github.com/allegro/allegro-api/assets/50913993/11241279-5aa6-45cc-b4a8-5b0f2cfbf410)

_3 konfiguracje nagłówka nie przynoszące efektu:_

![Zrzut ekranu 2023-07-7 o 23 13 10](https://github.com/allegro/allegro-api/assets/50913993/5add046b-fa7f-45c6-9c94-50ed9714a3d3)

![Zrzut ekranu 2023-07-7 o 23 13 03](https://github.com/allegro/allegro-api/assets/50913993/7d133908-8c39-4535-ae50-22809d718b7d)

![Zrzut ekranu 2023-07-7 o 23 12 56](https://github.com/allegro/allegro-api/assets/50913993/54a89601-af90-4e6b-862e-8c9373b19771)

**Comment by MaciejFrackowiak** [comment]
Niestety, ale błąd który wkleiłeś zwraca strona trzecia, z której korzystasz, a nie bezpośrednio API Allegro. Tym samym nie sposób nam się odnieść, co dokładnie kryje się pod tym błędem. Najlepszym rozwiązaniem jest bezpośredni kontakt z integratorem, aby wyjaśnił Tobie sedno zwracanego błędu.
