### ISSUE TITLE
Błąd adresu dostawy do klienta

### ISSUE THREAD

**Issue by coolpina** [allegro/allegro-api#7342]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Problem nie dotyczy bezpośrednio API, ale liczę że jest ktoś kto będzie w stanie przekazać to do właściwej osoby.

Allegro regularnie przepuszcza zamówienia bez podanej ulicy w adresie. Często klient z adresem: Wioska 231, XX-XXX Wioska, podaje adres w formie:
Jan Kowalski
231
XX-XXX Wioska 

i na tak podanym adresie wykładają się akcje generujące automatycznie etykiety. 

Formularz dostawy powinien być zabezpieczony aby nie dało się podać danych w taki sposób. Czy jest możliwe aby zostało to poprawione?

**Comment by MaciejFrackowiak** [comment]
Jak sam wspominasz API Allegro wyłącznie przekazuje dane, które zostały wprowadzone w formularzu dostawy, zatem de facto nie ma żadnego wpływu na ich zawartość. Tym samym swoje uwagi proszę przekaż bezpośrednio poprzez [formularz kontaktowy Allegro](https://allegro.pl/pomoc/kontakt), ponieważ tak Twoje spostrzeżenie zostanie przekazane do właściwej komórki.
