### ISSUE TITLE
brak wszystkich zdjęć w produkcie

### ISSUE THREAD

**Issue by kochanA** [allegro/allegro-api#7344]
Utworzyłam produkt a póżniej na jego podstawie ofertę na koncie testowym sandbox.
Przy tworzeniu produktu wysłałam takie dane dotyczące zdjęć: 
'images': [{'url': 'https://a.allegroimg.allegrosandbox.pl/original/11b655/143c25ef4f5c9cfc42fbbe37b966'}, {'url': 'https://a.allegroimg.allegrosandbox.pl/original/1198e5/856d560440c58baf0f418b864550'}, {'url': 'https://a.allegroimg.allegrosandbox.pl/original/11e1d9/8fdcf4154cf2938970f06ee78a08'}, {'url': 'https://a.allegroimg.allegrosandbox.pl/original/11a694/4ade3a2a41ab9efa545f4456ab52'}, {'url': 'https://a.allegroimg.allegrosandbox.pl/original/11aa98/f9526bee4f948248e7c0f88c0ee1'}, {'url': 'https://a.allegroimg.allegrosandbox.pl/original/11c7e2/01e60041447c9d36616253518e34'}, {'url': 'https://a.allegroimg.allegrosandbox.pl/original/118d7e/a4da532c4c5a86d095bdebca4f2a'}], 

w odpowiedzi na zapytanie "sale/product-proposals" typu "POST" otrzymałam tylko 2 zdjęcia :
'images': [{'url': 'https://a.allegroimg.allegrosandbox.pl/original/11b655/143c25ef4f5c9cfc42fbbe37b966'}, {'url': 'https://a.allegroimg.allegrosandbox.pl/original/118d7e/a4da532c4c5a86d095bdebca4f2a'}],

Proszę o podpowiedź jak to zrobić żeby mój produkt miał wszystkie przesłane przeze mnie zdjęcia ?

**Comment by MartaNowaczyk** [comment]
Prześlij proszę pełen request i response w formacie JSON dla takiego przypadku. Do weryfikacji przyda się również trace-id z odpowiedzi dla tego wywołania.

**Comment by kochanA** [comment]
request : {'name': '-- hamak z drążkiem di volio czarny 120 kg 280 x 100 --', 'category': {'id': '82257'}, 'images': [{'url': 'https://a.allegroimg.allegrosandbox.pl/original/11b655/143c25ef4f5c9cfc42fbbe37b966'}, {'url': 'https://a.allegroimg.allegrosandbox.pl/original/1198e5/856d560440c58baf0f418b864550'}, {'url': 'https://a.allegroimg.allegrosandbox.pl/original/11e1d9/8fdcf4154cf2938970f06ee78a08'}, {'url': 'https://a.allegroimg.allegrosandbox.pl/original/11a694/4ade3a2a41ab9efa545f4456ab52'}, {'url': 'https://a.allegroimg.allegrosandbox.pl/original/11aa98/f9526bee4f948248e7c0f88c0ee1'}, {'url': 'https://a.allegroimg.allegrosandbox.pl/original/11c7e2/01e60041447c9d36616253518e34'}, {'url': 'https://a.allegroimg.allegrosandbox.pl/original/118d7e/a4da532c4c5a86d095bdebca4f2a'}], 'parameters': [{'id': 224017, 'values': ['DV-005HWS Rimini']}, {'id': 248801, 'valuesIds': ['248801_984671']}, {'id': 211738, 'valuesIds': ['211738_251194']}, {'id': 211886, 'valuesIds': ['211886_251570']}, {'id': 205826, 'valuesIds': ['205826_225046']}, {'id': 9402, 'valuesIds': ['9402_2']}, {'id': 201033, 'values': ['280 cm']}, {'id': 211758, 'values': ['100 cm']}, {'id': 209802, 'values': ['120 kg']}, {'id': 237206, 'values': ['Rimini']}, {'id': '225693', 'values': ['5902308220584']}], 'description': {'sections': [{'items': [{'type': 'TEXT', 'content': '<p><b>Hamak jednoosobowy ze stelażem Rimini –\xa0</b>\xa0udanego relaksu w ogrodzie, na balkonie lub tarasie. Hamak wyróżnia się nowoczesnym, eleganckim wyglądem i solidnym wykonaniem. Mocna, stalowa rama stojaka zapewnia bezpieczeństwo użytkowania. Tkanina to wytrzymałe płótno, które jednocześnie jest przewiewne i przyjemne w dotyku. Funkcja złożenia stojaka umożliwia wygodne przechowywanie. Maksymalne obciążenie hamaka wynosi 120 kg.</p><p>✅ Hamak ze stelażem Rimini - Czarny</p><p> </p>'}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.allegrosandbox.pl/original/118d7e/a4da532c4c5a86d095bdebca4f2a'}]}, {'items': [{'type': 'TEXT', 'content': '<h2>⇨ Wytrzymały materiał</h2><p>Odpowiednią wytrzymałość zapewnia hamakowi płótno o gramaturze 320 g, które stanowi mieszaninę bawełny (65%) i poliestru (35%). Dzięki temu jest przewiewne, przyjemne w dotyku i jednocześnie trwałe.</p><h2>Dane techniczne:</h2><ul> <li>Producent: di Volio</li> <li>Model: RIMINI DV-005HWS</li> <li>Przeznaczenie: klasa H, do użytku domowego</li> <li>Kolor: czarny</li> <li>Długość hamaka wynosi 200 cm,</li> <li>Szerokość 100 cm,</li> <li>Długość stelaża 280 cm</li> <li>Wysokość stelaża 100 cm</li> <li>Stelaż stalowy w kolorze czarnym</li> </ul>'}]}]}, 'language': 'pl-PL'}

response: {'id': 'af6baded-71ae-4467-b27e-dc36058bc088', 'name': '-- hamak z drążkiem di volio czarny 120 kg 280 x 100 --', 'category': {'id': '82257', 'similar': [{'id': '257756'}]}, 'parameters': [{'id': '224017', 'values': ['DV-005HWS Rimini']}, {'id': '248801', 'valuesIds': ['248801_984671'], 'values': None}, {'id': '237206', 'values': ['Rimini']}, {'id': '211738', 'valuesIds': ['211738_251194'], 'values': None}, {'id': '211886', 'valuesIds': ['211886_251570'], 'values': None}, {'id': '205826', 'valuesIds': ['205826_225046'], 'values': None}, {'id': '9402', 'valuesIds': ['9402_2'], 'values': None}, {'id': '201033', 'values': ['280.00']}, {'id': '211758', 'values': ['100']}, {'id': '209802', 'values': ['120']}, {'id': '225693', 'values': ['5902308220584']}], 'images': [{'url': 'https://a.allegroimg.allegrosandbox.pl/original/11b655/143c25ef4f5c9cfc42fbbe37b966'}, {'url': 'https://a.allegroimg.allegrosandbox.pl/original/118d7e/a4da532c4c5a86d095bdebca4f2a'}], 'description': {'sections': [{'items': [{'type': 'TEXT', 'content': '<p><b>Hamak jednoosobowy ze stelażem Rimini –\xa0</b>\xa0udanego relaksu w ogrodzie, na balkonie lub tarasie. Hamak wyróżnia się nowoczesnym, eleganckim wyglądem i solidnym wykonaniem. Mocna, stalowa rama stojaka zapewnia bezpieczeństwo użytkowania. Tkanina to wytrzymałe płótno, które jednocześnie jest przewiewne i przyjemne w dotyku. Funkcja złożenia stojaka umożliwia wygodne przechowywanie. Maksymalne obciążenie hamaka wynosi 120 kg.</p><p>✅ Hamak ze stelażem Rimini - Czarny</p><p> </p>'}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.allegrosandbox.pl/original/118d7e/a4da532c4c5a86d095bdebca4f2a'}]}, {'items': [{'type': 'TEXT', 'content': '<h2>⇨ Wytrzymały materiał</h2><p>Odpowiednią wytrzymałość zapewnia hamakowi płótno o gramaturze 320 g, które stanowi mieszaninę bawełny (65%) i poliestru (35%). Dzięki temu jest przewiewne, przyjemne w dotyku i jednocześnie trwałe.</p><h2>Dane techniczne:</h2><ul> <li>Producent: di Volio</li> <li>Model: RIMINI DV-005HWS</li> <li>Przeznaczenie: klasa H, do użytku domowego</li> <li>Kolor: czarny</li> <li>Długość hamaka wynosi 200 cm,</li> <li>Szerokość 100 cm,</li> <li>Długość stelaża 280 cm</li> <li>Wysokość stelaża 100 cm</li> <li>Stelaż stalowy w kolorze czarnym</li> </ul>'}]}]}, 'language': 'pl-PL'}

czy trace-id to któraś z wartości response ?

**Comment by MartaNowaczyk** [comment]
Trace-id znajdziesz w nagłówku odpowiedzi.

**Comment by kochanA** [comment]
Nie złapałam nagłówka niestety, da Pani radę bez tego ?

**Comment by MartaNowaczyk** [comment]
Spróbuję, dam znać.

**Comment by kochanA** [comment]
ok dziękuję :)

**Comment by MartaNowaczyk** [comment]
Błąd znaleziony. Zdjęcia zostały odrzucone, bo miały nieodpowiedni rozmiar - były za małe.

**Comment by MartaNowaczyk** [comment]
[Zasady dotyczące zdjęć produktów](https://allegro.pl/dla-sprzedajacych/zasady-dotyczace-zdjec-produktow-Wv1Y6GOgkun)
