### ISSUE TITLE
You cannot register a new applicationActivate 

### ISSUE THREAD

**Issue by xu19950827** [allegro/allegro-api#7347]
![{AAA89E7A-EC7D-526B-6157-11F826D787CE}](https://github.com/allegro/allegro-api/assets/22289367/33db6103-fc95-41ce-a0eb-6bd316987ec8)
May I know what I need to do？

**Comment by MartaNowaczyk** [comment]
To be able to register a new application - it is necessary to [enable two-step login](https://allegro.pl/moje-allegro/moje-konto/dwustopniowe-logowanie), which is not enabled on the account.

**Comment by xu19950827** [comment]
Is it necessary to complete sandbox testing before creating an application in the production environment?

**Comment by xu19950827** [comment]
![{DF84E335-C1A1-CA73-1E27-ADCADA7BFF6E}](https://github.com/allegro/allegro-api/assets/22289367/be209d1d-364a-4991-b257-1f1fee3c4d52)
When I obtain the authorization code, I am prompted for this. May I know the situation

**Comment by MartaNowaczyk** [comment]
No, application registration on production is not affected by sandbox testing.

**Comment by manlolojaen** [comment]
Yo tengo activado el inicio de sesión en dos paso y sigue sin permitirme dar de alta una aplicación, o incluso obtener un token.

![image](https://github.com/allegro/allegro-api/assets/140380144/e1e8c3d8-2163-4f1c-a4c1-9f930694909c)

**Comment by AureliuszBrussy** [comment]
@manlolojaen you still need to activate your account. If you would like assistance in activating your account, please use [contact form](https://allegro.pl/pomoc/kontakt).

**Comment by manlolojaen** [comment]
Used contact form, but i can`t access to create a new application, thanks

**Comment by AureliuszBrussy** [comment]
@manlolojaen as I mentioned, your account must be fully active in order for you to create applications. Ask through the form to help you fully activate your account.
