### ISSUE TITLE
Błędne porównanie parametrów podczas aktualizacji

### ISSUE THREAD

**Issue by BartlomiejCalus** [allegro/allegro-api#7349]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Napotkaliśmy problem podczas aktualizacji ofert
W ramach aktualizacji oferty najpierw pobieramy ją (GET /sale/product-offers/{offerId}), zmieniamy odpowiednie pola i następnie wysyłamy zmiany (PATCH /sale/product-offers/{offerId}). 
Oferta pobiera się poprawnie wraz z wszystkimi polami, przy niektórych ofertach w odpowiedzi na zapytanie PATCH otrzymujemy błąd parametru w którym wartość jednego z nich jest porównywana do wartości nie związanej z tym parametrem co powoduje konflikt.

trace-id dla GET: c0d07b795d7293bb
trace-id dla PATCH: d3e86e08af283fe8

**Comment by MaciejFrackowiak** [comment]
Pobierając ofertę otrzymujesz jej stan sprzed aktualizacji wartości parametru Kod producenta w samym produkcie przypisanym do tej oferty. Aby wyeliminować błąd, obecnie należy wysłać komendę PATCH wyłącznie z identyfikatorem produktu, wówczas my automatycznie zaktualizujemy wartości parametrów w ofercie na podstawie aktualnych danych z produktu.
