### ISSUE TITLE
problem z sale/offer-modification-commands/

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#735]
Witam, odnotowujecie problemy z sale/offer-modification-commands/ ?

Od rana mam problem z zmianą czasu wysyłki.
W godzinach porannych metoda nic nie zwracała, teraz zwraca id lecz po sprawdzeniu przez sale/offer-modification-commands/8fdaa90d-8804-4d82-bd78-745d11ac66fb otrzymuję:

 [id] => 8fdaa90d-8804-4d82-bd78-745d11ac66fb
    [taskCount] => stdClass Object
        (
            [total] => 0
            [success] => 0
            [failed] => 0
        )

Tylko proszę, nie piszcie, ze mam podać response i request... ;)

**Comment by PawelTaberski** [comment]
Czy ostatecznie czas wysyłki zmienił się na ofertach. Czy stan wykonania zadania sprawdzałeś przy pomocy metody [GET na zasobie /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#/offer-management/getPublicationTasksUsingGET). Respons jaki podesłałeś w przypadku skorzystania z metody PUT /sale/offer-modification-commands/{commandId} jest prawidłowy. Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/news/2018-04-19-News_grupowa_edycja_ofert_update/).
