### ISSUE TITLE
Brak dostępu podczas pobierania wątków wiadomości

### ISSUE THREAD

**Issue by MGroskop** [allegro/allegro-api#7350]
Proszę o pomoc, ponieważ wykonuje niby prosty request, ale wyrzuca mi błąd w postaci "Braku dostępu do zasobu".
Przy rejestracji aplikacji na koncie zaznaczyłem wszystkie możliwe uprawnienia. Nie wiem czy od patrzenia stale w jedno miejsce nie mogę dojrzeć może jakiejś literówki, czy może czegoś innego brakuje. Gdyby token był wygaśnięty, to mam nadzieję, że zobaczyłbym inny komunikat o błędzie a tu ewidentnie brak dostępu.

uprawnienia:
![uprawnienia](https://github.com/allegro/allegro-api/assets/110199483/02759e72-3f3d-45b4-a3da-102197d72f05)

Request i response:

![reqires](https://github.com/allegro/allegro-api/assets/110199483/be7bf370-8f72-40a5-8d1c-7c623a13a6d9)

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swojego wywołania.

**Comment by MGroskop** [comment]
19a588156535829b :)

**Comment by MGroskop** [comment]
Tak użyłem tego, ponieważ nie działała mi metoda ze zrzutu, która wyświetla brak autoryzacji

![code1](https://github.com/allegro/allegro-api/assets/110199483/473ab2d7-29ad-480a-9987-d657e5ddb740)

![code2](https://github.com/allegro/allegro-api/assets/110199483/7183f838-b911-40b8-b8aa-559668729388)

**Comment by MaciejFrackowiak** [comment]
Niestety, z takiego częściowego przykładu wiele powiedzieć nie możemy. Proszę spójrz do [naszego poradnika](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#autoryzacja-uzytkownika), gdzie opisujemy proces autoryzacji wraz z przykładami.
