### ISSUE TITLE
W integracji pojawił się błąd w komunikacji z API:  Brak uprawnień do integracji: "Wysyłam z Allegro (DPD)", na koncie Kedziorek2010. " Zweryfikuj konfigurację konta Allegro w obszarze usługi Wysyłam z Allegro.

### ISSUE THREAD

**Issue by Kedziorek2010** [allegro/allegro-api#7351]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

**Comment by Kedziorek2010** [comment]
W integracji pojawił się błąd w komunikacji z API:

Brak uprawnień do integracji: "Wysyłam z Allegro (DPD)", na koncie Kedziorek2010. " Zweryfikuj konfigurację konta Allegro w obszarze usługi Wysyłam z Allegro.

**Comment by MaciejFrackowiak** [comment]
W tym przypadku proszę skontaktuj się bezpośrednio ze wsparciem aplikacji, z której usług korzystasz.

**Comment by Kedziorek2010** [comment]
ok
