### ISSUE TITLE
Problem z autoryzacją 

### ISSUE THREAD

**Issue by Bmitruk13** [allegro/allegro-api#7352]
Dzień dobry, postępuje zgodnie z instrukcja: https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow

Gdy wygeneruje link do autoryzacji aplikacji np:
https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=a67d634a8ad44373b72b0733422e2ef0&redirect_uri=http://sklep.test

To otrzymuje na stronie błąd 
![image](https://github.com/allegro/allegro-api/assets/86890189/fe649af1-92b7-4f89-95ca-95f595310f74)

Niezależenie czy to jest allegro.pl czy allegro.pl.allegrosandbox.pl

Gdzie popełniam błąd? 
Pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
Adres przekierowania, który wprowadziłeś w aplikacji nie jest zgodny 1:1 z adresem przekierowania, który podałeś na stronie https://apps.developer.allegro.pl.allegrosandbox.pl.
