### ISSUE TITLE
Dev Sandbox for testing

### ISSUE THREAD

**Issue by torben1000** [allegro/allegro-api#7353]
I did not find any other contact, other that opening a github issue.

So, I need to implement some API calls in a software, that a client of ours uses. For that it would be awesome if I have an enviroment for testing and developing.

Thanks in advance

**Comment by MartaNowaczyk** [comment]
We have a [Sandbox test environment](https://allegro.pl.allegrosandbox.pl/), see our [tutorial](https://developer.allegro.pl/tutorials/basic-information-VL6YelvVKTn#test-environment) for more information.
