### ISSUE TITLE
Add Product using REST API

### ISSUE THREAD

**Issue by dgkdev** [allegro/allegro-api#7354]
Hello, should we use "offer" or "product proposals" when loading the product?

**Comment by MartaNowaczyk** [comment]
It depends on what you mean. The product includes all the attributes and details of the product itself. If you are adding a new one to our Product Catalog, it will probably be the product. 
Offer - is to specify the conditions of sale of a product from the Product Catalog. That is, when you specify the price and other parameters for the sale.

**Comment by dgkdev** [comment]
thank you, does adding the product proposal directly make the product ready for sale? If not, should we use the offer endpoint?

**Comment by MartaNowaczyk** [comment]
If you add a product proposal via [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct), you still need to use [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) to specify sales information such as stock and price. With this endpoint, you can also list an offer associated with an existing product or, based on this request, add a new one already with sales information. You can find more in our [tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-list-an-offer-with-a-product-via-sale-product-offers-resource).
