### ISSUE TITLE
parcel-create-commands OneBox

### ISSUE THREAD

**Issue by SlawekMat** [allegro/allegro-api#7355]
Dzień dobry,
jakie dane powinienem wpisać w sekcji receiver (szczególnie chodzi mi o adres) jeśli przesyłka jest wysyłana do punktu i podaję pointId

**Comment by MartaNowaczyk** [comment]
Pobierz zamówienie, które utworzyłeś i na podstawie tych danych możesz utworzyć przesyłkę. Opis pól dotyczący danych nadawcy znajdziesz w przykładowym requeście w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke) o tworzeniu paczki.
