### ISSUE TITLE
Sandbox Problem z parametrem 224017 Kod producenta sale/product-offers

### ISSUE THREAD

**Issue by Cupik83** [allegro/allegro-api#7356]
Witam.

Mam problem przy próbie wystawienia aukcji na koncie Sandbox.

Przy próbie wystawienia dostaję błąd:

[code] => ParameterCategoryException
                    [message] => Unprocessable Entity
                    [details] => 
                    [path] => parameters
                    [userMessage] => The definitions of the parameter `224017:Kod producenta` were incorrectly specified as a parameter in section `offer`.

Mój request z tym parametrem:

[1] => stdClass Object
                (
                    [rangeValue] => 
                    [values] => Array
                        (
                            [0] => MNCY3PM/A
                        )

                    [id] => 224017
                    [valuesIds] => Array
                        (
                        )

                )

Co ciekawe dla już wystawionej aukcji przy odczycie danych dla tego parametru jest niby to samo:

[1] => stdClass Object
                (
                    [id] => 224017
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => MNCY3PM/A
                        )

                    [rangeValue] => 
                )

**Comment by MaciejFrackowiak** [comment]
Z opisu błędu wynika, że parametr Kod producenta jest parametrem produktowym w kategorii, w której chcesz wystawić ofertę. Jego definicja powinna znaleźć się w tablicy productSet.product.parameters - pomocne informacje znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#uzupelnij-kategorie-i-parametry).

**Comment by Cupik83** [comment]
Tutaj sobie poradziłem.

Ale mam kolejny problem.

Dostaje błąd przy parametrach:

stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ParameterCategoryException
                    [message] => Unprocessable Entity
                    [details] => 
                    [path] => parameters
                    [userMessage] => The definitions of the parameter `207802:Funkcje` were incorrectly specified as a parameter in section `offer`.
                )

        )

)

Tablica z parametrami wygląda tak:

[parameters] => Array
        (
            [0] => Array
                (
                    [rangeValue] => 
                    [valuesIds] => Array
                        (
                            [0] => 11323_1
                        )

                    [id] => 11323
                )

            [1] => Array
                (
                    [valuesIds] => Array
                        (
                            [0] => 207802_2
                            [1] => 207802_4
                            [2] => 207802_1
                        )

                    [id] => 207802
                )

            [2] => Array
                (
                    [rangeValue] => 
                    [valuesIds] => Array
                        (
                            [0] => 229205_340245
                        )

                    [id] => 229205
                )

        )

Po ręcznym dodaniu podobnej aukcji w parametrach pobranych nie widzę różnicy między tym co przesyłam.

**Comment by MaciejFrackowiak** [comment]
Komunikat błędu mówi, że parametr Funkcje powinien znaleźć się w części produktowej requestu - patrząc na to co wkleiłeś umieściłeś go w cześci ofertowej.

**Comment by Cupik83** [comment]
Dziękuje za pomoc. Rzeczywiście źle popatrzyłem na opcje parametrów. Teraz działa.
