### ISSUE TITLE
Waluta przesyłki

### ISSUE THREAD

**Issue by Skuria** [allegro/allegro-api#7357]
Witam, 
posiadam dwa zamówienia PL -> CZ
Jedno wysyłane metodą Allegro wysyłska z polski do Czech - odbiór w punkcie PACKETA, 
a drugie 
AllegroKurierDPDCzechy.

Ciągle posiadamy problemy z przesyłaną walutą wartości przesyłki. W dokumentacji napisane jest że pole przyjmuje tylko PLN. Jednak dla DPD musimy przesyłać walutę czeską. 
Dla PACKETA znów mimo iż to ten sam kierunek kraju musimy przesyłać walutę PLN.

Moje pytanie brzmi, czy jest jakaś możliwośc pobrania waluty dla danego przewoźnika? Jaka jest zasada przesyłania waluty?

**Comment by MaciejFrackowiak** [comment]
Skonsultowałem Twoje uwagi z zespołem odpowiedzialnym za usługę - w obu przypadkach ubezpieczenie powinno być wskazane w PLN.

**Comment by Skuria** [comment]
Nawet jeśli paczka została zamówiona w marketplace allegro-cz ?

**Comment by MaciejFrackowiak** [comment]
Przesyłka nadawana jest z Polski, zatem PLN.

**Comment by inTestowy** [comment]
Dzień dobry, wciąż istnieje problem z walutami dla różnych przewoźników.
Oto payload metody tworzenia przesyłki:
{"serviceId":"114d388f-354f-41c1-a0ea-36d2032265ad","receiver":{"address":{"street":"Pepickowa 12/1","postCode":"10000","city":"Praga","countryCode":"CZ","country":null},"email":"7x941aivwh+2d22d6f88@user.allegrogroup.pl","name":"Jan Kowalski","company":"Adres CZ","phone":"509059059","pointId":"9290"},"pickup":{"address":{"street":"testowa 72/","postCode":"01-001","city":"Warszawa","countryCode":"PL","country":null},"email":"intest2.testowy@gmail.com","name":"Zenonowa Żabka","company":"intest.testowy 2","phone":"521523522","pointId":null},"items":[{"dimensions":{"height":{"value":25,"unit":"CENTIMETER"},"width":{"value":20,"unit":"CENTIMETER"},"depth":{"value":10,"unit":"CENTIMETER"}},"weight":{"value":1,"unit":"KILOGRAM"},"description":null,"value":{"amount":"167.80","currency":"PLN"},"type":"PACKAGE"}],"type":"PACKAGE","label":{"sender":null,"fileFormat":"PDF","referenceNumber":""},"additionalServices":{"cashOnDelivery":{"value":{"amount":"882.00","currency":"CZK"},"accountNumber":"","name":"Zenonowa Żabka","express":false},"options":null}}

Jak widać wartość COD jest w walucie czeskiej, a wartość deklarowana przesyłki jest w walucie Polskiej - tak jak pan wyżej napisał.

Niestety przesyłka nie tworzy się. Dostajemy odpowiedź:
{"id":"4be59876-402a-4ac5-96e3-2c5632f93889","parcelId":null,"status":"ERROR","errors":[{"code":"INVALID_INSURANCE_CURRENCY_INTERNAL","details":null,"message":"The currency: PLN is not supported for the selected delivery option","path":"items.value.currency","userMessage":"Waluta PLN nie jest wspierana dla wybranej metody dostawy"}]}

Według dokumentacji COD powinno być w walucie kraju:
![image](https://github.com/allegro/allegro-api/assets/111511140/666b57a2-f83e-42d5-abb0-803cff30d59b)

A wartość przesyłki w PLN

![image](https://github.com/allegro/allegro-api/assets/111511140/76659140-2afc-4f83-885a-586fac88c32b)

Jak więc powinniśmy ustawić waluty tak aby odpowiednio wysyłać przesyłki pobraniowe i nie pobraniowe z Polski do Czech?

**Comment by MaciejFrackowiak** [comment]
@inTestowy W przypadku przesyłek Packeta obie kwoty muszą być wyrażone w CZK - wyjaśniam z zespołem odpowiedzialnym za zasoby kwestię obecnych zapisów w dokumentacji.

**Comment by Skuria** [comment]
@MaciejFrackowiak W takim razie czy jest jakiś zasób, z którego można pobrać informacje o tym w jakiej walucie powinniśmy wysyłać cod/wartość paczki? Aktualnie nasi klienci posiadają problem z wysyłką z erp, gdyż nie posiadamy informacji o tym jaki przewoźnik jaką walutę przyjmuje.

**Comment by MaciejFrackowiak** [comment]
@inTestowy Próbuję ustalić katalog takich usług. Jak tylko otrzymam właściwe informacje, zamieszczę tu szczegóły.

@Skuria NIe, nie ma takiego zasobu. Jak wspomniałem wyżej staram się przygotować listę usług z walutami różnymi od PLN.

**Comment by MaciejFrackowiak** [comment]
@inTestowy Są to metody dostawy, gdzie przewoźnikiem jest Packeta oraz WeDo.
