### ISSUE TITLE
ustawienie czasu zakończenia oferty

### ISSUE THREAD

**Issue by kochanA** [allegro/allegro-api#7358]
wystawiam ofertę z czasem rozpoczęcia i czasem zakończenia

{'productSet': [{'product': {'id': 'af6baded-71ae-4467-b27e-dc36058bc088'}, 'quantity': {'value': 1}}], 'stock': {'available': 3, 'unit': 'UNIT'}, 'sellingMode': {'price': {'amount': 1970.0, 'currency': 'PLN'}}, 'external': {'id': 'HS-5902308220584'}, 'delivery': {'handlingTime': 'PT72H'}, 'publication': {'startingAt': '2023-07-12T12:36:00.000000Z', 'endingAt': '2023-07-12T12:37:00.000000Z'}}

dla zapytania "sale/product-offers"

dostaję taka odpowiedź :
{'name': '-- hamak z drążkiem czarny 120 kg 280 x', 'productSet': [{'product': {'id': 'af6baded-71ae-4467-b27e-dc36058bc088', 'publication': {'status': 'LISTED'}, 'parameters': [{'id': '224017', 'name': 'Kod producenta', 'values': ['DV-005HWS Rimini'], 'valuesIds': None, 'rangeValue': None}, {'id': '248801', 'name': 'Producent', 'values': ['ttttrrrrr'], 'valuesIds': ['248801_984671'], 'rangeValue': None}, {'id': '225693', 'name': 'EAN (GTIN)', 'values': ['5902308220584'], 'valuesIds': None, 'rangeValue': None}, {'id': '237206', 'name': 'Model', 'values': ['Rimini'], 'valuesIds': None, 'rangeValue': None}, {'id': '211738', 'name': 'Rodzaj', 'values': ['hamak z drążkiem'], 'valuesIds': ['211738_251194'], 'rangeValue': None}, {'id': '211886', 'name': 'Styl', 'values': ['nowoczesny'], 'valuesIds': ['211886_251570'], 'rangeValue': None}, {'id': '205826', 'name': 'Kolor dominujący', 'values': ['czarny'], 'valuesIds': ['205826_225046'], 'rangeValue': None}, {'id': '9402', 'name': 'Materiał stelażu', 'values': ['metal'], 'valuesIds': ['9402_2'], 'rangeValue': None}, {'id': '201033', 'name': 'Długość całkowita', 'values': ['280.00'], 'valuesIds': None, 'rangeValue': None}, {'id': '211758', 'name': 'Szerokość materiału', 'values': ['100'], 'valuesIds': None, 'rangeValue': None}, {'id': '209802', 'name': 'Maksymalne obciążenie', 'values': ['120'], 'valuesIds': None, 'rangeValue': None}]}, 'quantity': {'value': 1}}], 'parameters': [{'id': '11323', 'name': 'Stan', 'values': ['Nowy'], 'valuesIds': ['11323_1'], 'rangeValue': None}], 'images': ['https://a.allegroimg.allegrosandbox.pl/original/11b655/143c25ef4f5c9cfc42fbbe37b966', 'https://a.allegroimg.allegrosandbox.pl/original/118d7e/a4da532c4c5a86d095bdebca4f2a'], 'afterSalesServices': {'impliedWarranty': {'id': '635857c8-055b-4a27-a567-3ef3dd43e7d6'}, 'returnPolicy': {'id': '404fb676-b978-427f-97a8-e88ecfc7e2ae'}, 'warranty': None}, 'payments': {'invoice': 'VAT'}, 'sellingMode': {'format': 'BUY_NOW', 'price': {'amount': '1970.00', 'currency': 'PLN'}, 'startingPrice': None, 'minimalPrice': None}, 'stock': {'available': 3, 'unit': 'UNIT'}, 'location': {'countryCode': 'PL', 'province': 'KUJAWSKO_POMORSKIE', 'city': 'Zabierzów', 'postCode': '32-080'}, 'delivery': {'shippingRates': {'id': 'ad4fbc47-7f40-46eb-be67-af51a3464c7f'}, 'handlingTime': 'PT72H', 'additionalInfo': None, 'shipmentDate': None}, 'description': {'sections': [{'items': [{'type': 'TEXT', 'content': '<p><b>Hamak jednoosobowy ze stelażem Rimini –&nbsp;</b>&nbsp;udanego relaksu w ogrodzie, na balkonie lub tarasie. Hamak wyróżnia się nowoczesnym, eleganckim wyglądem i solidnym wykonaniem. Mocna, stalowa rama stojaka zapewnia bezpieczeństwo użytkowania. Tkanina to wytrzymałe płótno, które jednocześnie jest przewiewne i przyjemne w dotyku. Funkcja złożenia stojaka umożliwia wygodne przechowywanie. Maksymalne obciążenie hamaka wynosi 120 kg.</p> <p>✅ Hamak ze stelażem Rimini - Czarny</p>'}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.allegrosandbox.pl/original/118d7e/a4da532c4c5a86d095bdebca4f2a'}, {'type': 'TEXT', 'content': '<p>Odpowiednią wytrzymałość zapewnia hamakowi płótno o gramaturze 320 g, które stanowi mieszaninę bawełny (65%) i poliestru (35%). Dzięki temu jest przewiewne, przyjemne w dotyku i jednocześnie trwałe.</p>'}]}, {'items': [{'type': 'TEXT', 'content': '<h2>⇨ Wytrzymały materiał</h2> <p>Odpowiednią wytrzymałość zapewnia hamakowi płótno o gramaturze 320 g, które stanowi mieszaninę bawełny (65%) i poliestru (35%). Dzięki temu jest przewiewne, przyjemne w dotyku i jednocześnie trwałe.</p> <h2>Dane techniczne:</h2> <ul> <li>Producent: tttrrr</li> <li>Model: RIMINI DV-005HWS</li> <li>Przeznaczenie: klasa H, do użytku domowego</li> <li>Kolor: czarny</li> <li>Długość hamaka wynosi 200 cm,</li> <li>Szerokość 100 cm,</li> <li>Długość stelaża 280 cm</li> <li>Wysokość stelaża 100 cm</li> <li>Stelaż stalowy w kolorze czarnym</li> </ul>'}]}]}, 'external': {'id': 'HS-5902308220584'}, 'category': {'id': '82257'}, 'tax': None, 'taxSettings': None, 'sizeTable': None, 'discounts': {'wholesalePriceList': None}, 'contact': None, 'fundraisingCampaign': None, 'messageToSellerSettings': None, 'attachments': [], 'b2b': {'buyableOnlyByBusiness': False}, 'additionalServices': None, 'compatibilityList': None, 'additionalMarketplaces': {'allegro-cz': {'sellingMode': None, 'publication': {'state': 'NOT_REQUESTED'}}}, 'id': '7713098320', 'language': 'pl-PL', 'publication': {'status': 'INACTIVE', 'duration': None, 'endedBy': None, 'endingAt': None, 'startingAt': '2023-07-12T12:36:00.000Z', 'republish': False, 'marketplaces': {'base': {'id': 'allegro-pl'}, 'additional': []}}, 'validation': {'errors': [], 'warnings': [], 'validatedAt': '2023-07-12T12:35:07.969Z'}, 'createdAt': '2023-07-12T12:35:07.000Z', 'updatedAt': '2023-07-12T12:35:07.991Z'}

startingAt działa i faktycznie oferta wystawia się o wskazanym czasie jeśli chodzi o endingAt to dostaje None,
proszę o podpowiedz jak wykonać to zapytanie poprawnie

**Comment by MaciejFrackowiak** [comment]
Wartość endingAt wyliczamy sami i co istotne wyłącznie dla aukcji.

**Comment by kochanA** [comment]
czyli przy ofercie typu "BUY_NOW" mogę podać tylko czas rozpoczęcia oferty ?

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak.
