### ISSUE TITLE
Problem ze strojami kąpielowymi

### ISSUE THREAD

**Issue by glorifyingpeace** [allegro/allegro-api#7359]
Obsługujemy wielu sprzedawców odzieży i mamy problem ze strojami kąpielowymi. 

"trace-id: 70a6dbec492730d1

ConstraintViolationException.DependencyValidator
Parametr zależny Rozmiar (128610) nie może przyjąć wartości [90C], gdy parametr Rodzaj (215534) ma wartości [góra]."

Produkt jest wystawiany przez endpoint który powinien tworzyć nowy produkt w produktyzacji. 
Ten błąd dostajemy ponieważ system nie chce stworzyć nowego produktu ponieważ dołącza nas do istniejącego. 
Natomiast istniejący został stworzony przed zmianami w parametrach i zawiera błędy przez które nasz produkt jest odrzucany. 

Poniżej widok z naszego programu ( na czerwono są parametry które się różnią)
https://ibb.co/Fg78Vw6

Jako użytkownicy mamy dwie możliwości:
1. przyjąć parametry produktu z produktyzacji - ale to skończy się tym że i tak produkt jest do przerobienia.
2. wysłać propozycję zmian w produkcie - robimy to ale najczęściej kończy się tym że nasza propozycja zmian jest odrzucana.

Problem jest olbrzymi zwłaszcza że jesteśmy u szczytu sezonu.

**Comment by MaciejFrackowiak** [comment]
Z punktu widzenia API nie mamy wpływu na przebieg weryfikacji zgłoszonych zmian w produkcie - to jest proces całkowicie poza nami. Z drzewa kategorii i parametrów wynika jednoznaczna zależność - określenie rozmiaru 90C możliwe jest tylko i wyłącznie, gdy Rodzaj przyjmie wartość "komplet" (id=215534_270230). W przesłanym do nas requeście była to wartość "góra" (id=215534_270222). Jeżeli masz uwagi co do zależności to proszę zgłoś je bezpośrednio do obsługi Allegro poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
