### ISSUE TITLE
Problem z sale/offer-publication-commands/{0}/tasks

### ISSUE THREAD

**Issue by SoftWareMG** [allegro/allegro-api#736]
Witam,
Od wczoraj mamy problem z tą bramką: sale/offer-publication-commands/{0}/tasks
Próbuje odczytać status tasku: 7ed5d514-7f71-4843-85e2-085fb52960a1

https://api.allegro.pl/sale/offer-publication-commands/7ed5d514-7f71-4843-85e2-085fb52960a1/tasks

Status request mam OK

**Respons tego requesta jest: '{"tasks":[]}' bez żadnej zawartości**

Wystawiam nową aukcję z podobnej i chcę sprawdzić czy status tasku jest zakończony prawidłowo.

5705536606 aukcja z której pobieram draft.
7608406455 nowa aukcja.

![allegro1](https://user-images.githubusercontent.com/38202814/46729907-ef766d80-cc86-11e8-8239-58e4f01d5b6c.png)

![allegro2](https://user-images.githubusercontent.com/38202814/46729911-f4d3b800-cc86-11e8-94f7-568f9ffb2cf3.png)

**Comment by PawelTaberski** [comment]
Co to oznacza, że masz dobrą odpowiedź przy publikacji? Czy otrzymujesz status 201? Dodatkowo czy na pewno przy publikacji używasz unikatowego UUID-a i po tym samym UUID-dzie śledzisz wykonanie zadania?
Czy postępujesz zgodnie z tym co opisaliśmy w poradniku [tutaj](https://developer.allegro.pl/sale/#step-8-offer-publication-commands).

**Comment by SoftWareMG** [comment]
Tak używam tego samego UUID.
Na załączonym zrzucie widać ze StatusCode jest OK .
Tak, zapoznałem się z poradnikiem i tak mi to działało przez miesiąc a od wczoraj response jest taki jak przesłałem.

**Comment by PawelTaberski** [comment]
Prosiłbym o dosłanie trace-id tego zadania. Jednocześnie sprawdziłem i występuje problem na tym zasobie z dużymi opóźnieniami, może to być powodem również i tego problemu. Pracujemy nad rozwiązaniem tego problemu.

**Comment by SoftWareMG** [comment]
https://api.allegro.pl/sale/offer-publication-commands/28bbdf97-f7ce-42fd-8d87-c316debe001f/tasks

Trace-Id: d4bc579355a0e568

Trace id mogę podać tylko dla nowej aukcji ale, zachowanie jest dokładnie takie samo.

**Comment by PawelTaberski** [comment]
Dziękuję za dane przekazałem je do zespołu, który pracuje nad rozwiązaniem tego problemu.

**Comment by SoftWareMG** [comment]
Witam,
Jak w temacie? Bo u mnie nadal nie można sprawdzić statusu tego tasku.

**Comment by PawelTaberski** [comment]
Problem nie powinien już występować. Mógłbyś ponowić zadanie publikacji pod nowym UUID-em i sprawdzić czy problem nadal u Ciebie występuje.
