### ISSUE TITLE
user_name from JWT cannot be empty

### ISSUE THREAD

**Issue by Vera57** [allegro/allegro-api#7360]
Hi,

I am trying to integrate the shipment creation webservice in my solution, but I didn't get far till now and that's partly because I don't have a person at Allegro to contact directly with my questions, partly because the developer page is very overloaded and partly because I need a Bearer token and don't have a redirect uri. 
I succeeded the Token Request for the Client-Credential Flow and got a Bearer Token for
curl --location 'https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials' \
--header 'Authorization: Basic base64(client_id:client_secret)'
I registered obviously for the scopes allegro:api:orders:read allegro:api:orders:write.
But I can neather call /order/checkout-forms nor /parcel-management/parcel-create-commands.
For /order/checkout-forms I get the following error:

    "errors": [
        {
            "code": "EmptyUserIdException",
            "message": "user_name from JWT cannot be empty",
            "details": null,
            "path": "/order/checkout-forms/29738e61-7f6a-11e8-ac45-09db60ede9d6",
            "userMessage": "user_name from JWT cannot be empty"
        }
I tried to put my username also in the header and/or body of the Token request above, but still I got this error.
What can I do?

**Comment by MaciejFrackowiak** [comment]
To use endpoints which require "bearer-token-for-user" you have to authorize using [code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#user-authorization) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow-user-authorization) flow. With client_credentials you will have access only to "bearer-token-for-application" resources.

**Comment by Vera57** [comment]
I need an authentication method, that requires user interaction and can be called just in the backend of my coding and maybe I understood something wrong in the documentation, but I understand it, like they need all user interaction

**Comment by MaciejFrackowiak** [comment]
Yes, this kind of authorization needs user action - we have to know that the user gives your application consent to use it in his name.

**Comment by Vera57** [comment]
And there is no other possibility? 
When I registered to get client_id and client_secret, I chose the scopes to which I give the application permission.

**Comment by MaciejFrackowiak** [comment]
No, there is no other possibility.
Scopes only define the data range which will be granted by us in the token, but the user has to give consent to share data from his account.

**Comment by Vera57** [comment]
Hi again, 
I managed to gain a token and then I wanted to create a label, but now I am stuck at the /parcel-management/parcel-create-commands/{commandID} call, wich I have to call because of the parcelId and gut the error
{
    "id": "{commandId}",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "CREDENTIALS_ID_NOT_PROVIDED",
            "message": "Seller didnt provide credentials for own delivery Method",
            "details": "Seller didnt provide credentials for own delivery Method",
            "path": "client credentials",
            "userMessage": "Wybrana metoda dostawy nie obsługuje tego zamówienia"
        }
    ]
}
Is this something the customer has to change or did I do something wrong with the requests.

**Comment by MaciejFrackowiak** [comment]
As a "serviceId" you should use a value from the "delivery.method.id" field from [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET) resource.

**Comment by Vera57** [comment]
Still not working, I even got new Orders from the GET /order/checkout-forms Webservice call. So I tell you what I do right now and maybe you can tell me, if I miss something or if the customer has to unlock something.

1. POST /auth/oauth/device?client_id={clientID} with Basic Authorization and content type application/x-www-form-urlencoded
2. POST /auth/oauth/token?device_code={deviceCode}&grant_type=urn:ietf:params:oauth:grant-type:device_code
3. GET /order/checkout-forms/{orderID} delivery-method-id = serviceId in 4.
4. PUT /parcel-management/parcel-create-commands/{commandID}
5. GET /parcel-management/parcel-create-commands/{commandID} here I  get the error
6. GET /parcel-management/label?parcelId={parcelID} which I don't have because of the response in the previous call

So, are these all calls or do I miss something?

**Comment by MaciejFrackowiak** [comment]
Please, give me a trace-id of your requests - I will be able to check our internal logs.

**Comment by Vera57** [comment]
So my path is correct?
1f16434928cf624d from PUT /parcel-management/parcel-create-commands/{commandID}
a570d320a9ba404 from GET /parcel-management/parcel-create-commands/{commandID}

**Comment by MaciejFrackowiak** [comment]
Please, give me also the order id for which you prepared a shipment.

**Comment by Vera57** [comment]
I think it's this one c3066682-97a3-42fe-9eb5-9bb2978cf293 but I tried like very much

**Comment by MaciejFrackowiak** [comment]
This is not an order id - it is a delivery.method.id - so please, check it again.

**Comment by Vera57** [comment]
8adeb6e0-2161-11ee-aa4a-9197983be20a ist this a order id?

**Comment by MaciejFrackowiak** [comment]
For order.id=8adeb6e0-2161-11ee-aa4a-9197983be20a the chosen delivery.method.id is "5d9c7838-e05f-4dec-afdd-58e884170ba7". In your request (with trace-id=1f16434928cf624d) you used a different delivery method - you cannot do it. You should pass on a value directly from the order.

**Comment by Vera57** [comment]
I tried it again, so that the orderId would match the trace-Ids
OrderID: 8adeb6e0-2161-11ee-aa4a-9197983be20a
TraceID GET /order/checkout-forms: 39a431ceb6f21c04
TraceID POST /parcel-management/parcel-create-commands: 26376c9fe920c540
TraceID GET /parcel-management/parcel-create-commands: e229141dd543fb9b

**Comment by MaciejFrackowiak** [comment]
Yes, the delivery service is OK now, but other data are wrong - you should use data from order details (address, email, etc.) In your request you mixed everything - you provided an email from the production environment, different addresses, etc. Please, read carefully our [tutorial about Ship with Allegro ](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV) to prevent similar problems.
