### ISSUE TITLE
Problem z wrzucaniem zdjęć na środowisku testowym

### ISSUE THREAD

**Issue by Hornir91** [allegro/allegro-api#7361]
Dzień dobry.

Od godzin porannych mam problem z wrzucaniem zdjęć na serwer testowy.  Ciągle dostaję kod 500.

Trace id: 27830d082a45df19

**Comment by MaciejFrackowiak** [comment]
Potwierdzam - mamy problem, zespół już pracuje nad jego wyeliminowaniem. Oczywiście dam znać, gdy przywrócimy właściwe działanie.

**Comment by Hornir91** [comment]
Dobrze, dziękuję za odpowiedź.

**Comment by MaciejFrackowiak** [comment]
Funkcjonalność została przywrócona.
