### ISSUE TITLE
Pobieranie wyników wyszukiwania przez API 

### ISSUE THREAD

**Issue by mcseem7** [allegro/allegro-api#7362]
Witam, 
Projektuje sklep internetowy (sprzedaż części samochodowych w Ukrainie, również na potrzeby AFU) i chciałbym mieć możliwość bezpośredniego pobierania danych z api allegro ponieważ wiem że scrapowanie (parsing) jest zakazany przez ToS Allegro. Planowana ilość zapytań to maks. 5000 dziennie. 
Schemat wygląda tak: 
1. Klient wprowadza nazwę towaru w języku ukraińskim na mojej stronie
2. Odbywa się automatyczne tłumaczenie przez Microsoft Azure Translator
3. Wysyła się request z mojego serwera do api allegro z zapytaniem w języku polskim
4. Klient otrzymuje listę ofert allegro i wybiera odpowiednią dla siebie 
5. Zamawiam ten produkt bezpośrednio na allegro i dostarczam do klienta
Jak najbardziej mogę wskazać na stronie że oferty pochodzą z Allegro.pl i dodać link do oferty.
Taki sklep internetowy nie zabiera traffic od allegro bo te ludzi nie znają języka polskiego i nie skorzystali by z państwa oferty. Natomiast to zwiększy sprzedaż części samochodowych na allegro o ilość moich sprzedaży (czyli dostaw, bo na tym polega zarobek) 
Bardzo proszę o pozytywną decyzję ;)

**Comment by MaciejFrackowiak** [comment]
Zgodnie z Regulaminem REST API - art. 4.1.c prezentowanie ofert Allegro w serwisach trzecich jest zabronione.

**Comment by mcseem7** [comment]
https://restauto.com.ua/
https://motopoland.com.ua/
https://spolshy.com.ua/
https://dvizok.com.ua/
https://motoallegro.net/
https://zp-auto.com.ua/
https://autodil.com.ua/
https://autoblok.com.ua/
https://automotive.org.ua/
https://avto-plus.com.ua/
https://mrzauto.com/
https://zakroot.com/
https://zapchasti.lviv.ua/

Dlaczego te serwisy mają dostęp do tej metody a mi tutaj rzucacie artykułami ?

**Comment by MaciejFrackowiak** [comment]
Prezentowanie ofert Allegro w serwisach trzecich zgodnie z Regulaminem REST API jest niedozwolone. O działaniach prowadzonych wobec podmiotów naruszających postanowienia Regulaminu REST API nie będziemy informować na forum GitHub.

**Comment by mcseem7** [comment]
> Prezentowanie ofert Allegro w serwisach trzecich zgodnie z Regulaminem REST API jest niedozwolone. O działaniach prowadzonych wobec podmiotów naruszających postanowienia Regulaminu REST API nie będziemy informować na forum GitHub.

Github to nie forum. 
Kłamie Pan bo działają te strony już od 3 lat i nic się nie zmienia. Jest Pan po prostu w skorumpowany przez właścicieli tych stron dlatego nadał Pan im dostęp a mi pisze wymówki.
