### ISSUE TITLE
szkice zamiast aktywnych ofert

### ISSUE THREAD

**Issue by bseHlpDsk** [allegro/allegro-api#7363]
Mimo niekorzystania ze szkiców - podczas wystawiania ofert powstało na koncie 20k szkiców, co uniemożliwia wystawianie nowych ofert. 
W związku z brakiem możliwości grupowego usuwania szkiców jak również braku obsługi szkiców przez api, proszę o usunięcie wszystkich szkiców z konta o id 99833307. Dziękuję.

**Comment by MaciejFrackowiak** [comment]
Przykro mi, jednak usunięcie szkicy pozostaje w gestii użytkownika. Szkice powstały na skutek działania użytkownika.

**Comment by bseHlpDsk** [comment]
pozwolę się nie zgodzić. Używamy tylko metody sale/product-offers. 

Już jakiś czas temu (ponad rok) mieliśmy taki przypadek i usunęliście szkice.

**Comment by MaciejFrackowiak** [comment]
Używając wymienionej oferty można również tworzyć szkice - wystarczy przekazać wartość INACTIVE w polu "publication.status".

**Comment by bseHlpDsk** [comment]
ok, ale jej nie używaliśmy - szkice powstały na skutek błędu w przetwarzaniu zapytania, które miało dać ofertę aktywną, bądź zwrócić błąd.

**Comment by MaciejFrackowiak** [comment]
Przykro mi, jak wspomniałem, usunięcie szkicy pozostaje wyłącznie w gestii użytkownika.
