### ISSUE TITLE
May I ask how to obtain the screenshot amount

### ISSUE THREAD

**Issue by VEVOR** [allegro/allegro-api#7364]
![1689302562626_7b23903f1aba63fe25463e993aee84ec](https://github.com/allegro/allegro-api/assets/99702013/27829265-f4aa-4261-88c0-832dc7140dbe)

**Comment by MaciejFrackowiak** [comment]
We do not return this price via API.

**Comment by VEVOR** [comment]
Is there any other way to obtain this price

**Comment by MaciejFrackowiak** [comment]
No.
