### ISSUE TITLE
Product upload failed. Response: "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji" | "HttpMessageNotReadableExceptio" 

### ISSUE THREAD

**Issue by Wooconnector** [allegro/allegro-api#7365]
Dear Team,

We are currently facing an issue while attempting to upload a product from our application to Allegro. The error message we are encountering is "HttpMessageNotReadableException," accompanied by the message "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji" (The request contains incorrect data. Please contact the application author). We have thoroughly verified the input payload multiple times, and it appears that the request to the "https://api.allegro.pl/sale/product-proposals" endpoint is preventing us from successfully creating the product.

Here is the input JSON payload we are using:
{
   "name":"T-Shirt with Logo",
   "category":{
      "id":"4bd97d96-f0ff-46cb-a52c-2992bd972bb1"
   },
   "description":{
      "sections":[
         {
            "items":[
               {
                  "type":"simple"
               }
            ]
         }
      ]
   },
   "images":[
      {
         "url":"https://geniwo.com/wp-content/uploads/2023/07/98ab589b-7ec3-433e-8471-9255cdf93a7d.jpeg"
      }
   ],
   "parameters":[
      {
         "id":"225693",
         "options":{
            "identifiesProduct":true
         },
         "rangeValue":{
            "from":"from string",
            "to":"to string"
         }
      }
   ]
}
We have ensured that all the required parameters are present in the payload. However, the issue persists. We kindly request your assistance in resolving this matter.

Thank you for your attention and support.

Best regards,
WooConnector

**Comment by MartaNowaczyk** [comment]
It is not possible to add a product for the specified category. In the response for GET /sale/categories/{categoryId}](https://developer.allegro.pl/documentation/#operation/getCategoryUsingGET_1) we return `"productCreationEnabled": false`. You can find the entire process and description for adding a product in our [
[tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-create-a-product).
