### ISSUE TITLE
Integracja "Wysyłam z Allegro" z ERP

### ISSUE THREAD

**Issue by RKruza** [allegro/allegro-api#7367]
Dzień dobry, chciałbym zintegrować wysyłkę przesyłek  One Box z ERP, pobieram dokumenty z Allegro i zapisuję je w ERP, następnie  po jakimś czasie chciałbym wygenerować paczkę i etykietę dla tego dokumentu. 
Nie jestem twórcą ERP, tworzę tylko do niego dodatki.

Czy muszę w celu wygenerowania przesyłki do One Box tworzyć oddzielną aplikację która by pośredniczyła w wymianie?

**Comment by MaciejFrackowiak** [comment]
Aby nadawać przesyłki w ramach Allegro musisz zaimplementować zasoby związane z usługą Wysyłam z Allegro. Szczegółowe informacje znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY).

**Comment by RKruza** [comment]
Czy potrzebuję stworzyć dodatkową aplikację i wystawić ją gdzieś?

Miałem nadzieje, że z uda się zrobić coś takiego, ze użytkownik z poziomu ERP wciśnie przycisk wygeneruj przesyłkę i pobiorę dla niego etykietę.

Z tego co jednak widzę to muszę wygenerować token,  a do tego potrzebna jest aplikacja

**Comment by RKruza** [comment]
czy dobrze mi się wydaje, ze do tego służy metoda autoryzacji typu Device flow?

Jeżeli tak, to tylko jeszcze proszę o wsparcie w jaki sposób aktywować konto w środowisku sandbox

**Comment by MaciejFrackowiak** [comment]
Konto na Sandbox założysz na stronie https://allegro.pl.allegrosandbox.pl/. Natomiast o przebiegu autoryzacji i uwierzytelniania informacje znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR).

**Comment by RKruza** [comment]
Dzieuję bardzo za odpowiedzi, jeszcze tylko pytanie czy aby aktywować konto na sandboxie muszę wykonać przelew?

**Comment by MaciejFrackowiak** [comment]
Tak, na Sandbox działa symulator płatności, czyli de facto nie wykonujesz prawdziwego przelewu.

**Comment by RKruza** [comment]
Cześć, ciągle mam problem z aktywacją konta, dokonałem "przelewu" ale wygląda na to że konto ciagle oczekuje na potwierdzenie. nie mogę dodać żadnych aplikacji.
nazwa konta: Turbopolex
![image](https://github.com/allegro/allegro-api/assets/139552376/6474b3bd-f7b6-4960-adf5-f41710d7934d)

**Comment by MaciejFrackowiak** [comment]
@RKruza Zweryfikowałem konto, powinno być OK.
