### ISSUE TITLE
Badges - aukcja jest w Allegro Prices CZ mimo, że nie jest

### ISSUE THREAD

**Issue by p3le** [allegro/allegro-api#7368]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Odpytując zasób `/sale/badges?offer.id={offerId}` w celu pobrania oznaczeń przypisanych do oferty, otrzymuję informację, że oferta jest przypisana do kampanii `ALLEGRO_PRICES_CZ` mimo, że nie jest przypisana do żadnych oznaczeń. Poniżej response z API:

```
{
   "badges":[
      {
         "offer":{
            "id":"12786207411"
         },
         "campaign":{
            "id":"ALLEGRO_PRICES_CZ",
            "name":"Allegro Prices CZ"
         },
         "publication":{
            "type":"SINCE",
            "from":"2023-06-04T09:09:02.259Z",
            "to":null
         },
         "prices":{
            "market":{
               "amount":"93.00",
               "currency":"CZK"
            },
            "bargain":{
               "amount":"93.00",
               "currency":"CZK"
            },
            "subsidy":{
               "targetPrice":{
                  "amount":"93.00",
                  "currency":"CZK"
               }
            }
         },
         "process":{
            "status":"ACTIVE",
            "rejectionReasons":[
               
            ]
         }
      }
   ]
}
```
Dodatkowo poniżej wklejam jak to wygląda po stronie frontendu Allegro:

CZ:
![image](https://github.com/allegro/allegro-api/assets/2972454/36fbe1b9-a5b2-4f78-b68e-5021fc73b0db)
![image](https://github.com/allegro/allegro-api/assets/2972454/b938c068-4db5-4973-9abb-77222e4bf4f8)

PL:
![image](https://github.com/allegro/allegro-api/assets/2972454/94fb147e-4965-4acb-b583-cbc70dcfce37)
![image](https://github.com/allegro/allegro-api/assets/2972454/95369b82-4c19-4b73-a9ab-06de23f6af3b)

`trace-id: a6cdef18a925a03e`

**Comment by MaciejFrackowiak** [comment]
Oferty zakwalifikowane do Allegro Ceny nie otrzymują dodatkowych oznaczeń - [tu](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/poznaj-allegro-ceny-na-czym-polega-program-wsparcia-dla-sprzedajacych-MR45D5zADiy) znajdziesz opis programu.

**Comment by p3le** [comment]
> Oferty zakwalifikowane do Allegro Ceny nie otrzymują dodatkowych oznaczeń - [tu](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/poznaj-allegro-ceny-na-czym-polega-program-wsparcia-dla-sprzedajacych-MR45D5zADiy) znajdziesz opis programu.

Po czym w takim razie rozpoznać oznaczenia nadawane przez Allegro automatycznie?

**Comment by MaciejFrackowiak** [comment]
Każdy z programów i kampanii ma swój regulamin oraz zasady działania - na podstawie wskazanego przez Ciebie pola można wnioskować, że dla danej kampanii nie trzeba w przypadku NEVER wnioskować osobiście - dzieje się to z "automatu".
