### ISSUE TITLE
Receiver name is too long

### ISSUE THREAD

**Issue by algru1** [allegro/allegro-api#7369]
Dzień dobry,
Jaka jest maksymalna wartość dla pola receiver.name?
Dostaję taki komunikat:
  "code": "VALIDATION_ERROR",
  "message": "Receiver name is too long",
  "path": "receiver.name",
  "userMessage": "Nazwa odbiorcy jest za długa"

**Comment by MaciejFrackowiak** [comment]
Każdy przewoźnik ma swoje własne limity, dlatego proszę podaj nazwę interesującego Cię przewoźnika.

**Comment by algru1** [comment]
Allegro Kurier UPS pobranie (199d2a2a-7c90-4ca7-aaf3-c1d941506dd0)

**Comment by algru1** [comment]
A czy możesz udostępnić limity dla poniższej listy:
Allegro One Box
Allegro One Box, One Kurier
Allegro Kurier UPS
Allegro Odbiór w Punkcie UPS
Allegro Kurier UPS pobranie
Allegro One Kurier - dostawa dzisiaj
Allegro One Kurier - dostawa jutro
Allegro One Kurier pobranie - dostawa dzisiaj
Allegro One Kurier pobranie - dostawa jutro
Allegro One Punkt, One Kurier
Allegro One Box, One Kurier - dostawa dzisiaj

**Comment by MaciejFrackowiak** [comment]
W przypadku UPS i Allegro One to 30 znaków.
