### ISSUE TITLE
nie moge zmienić statusu publikacji oferty

### ISSUE THREAD

**Issue by dostawcaopon** [allegro/allegro-api#737]
Dzien dobry,
jak długo trwa zmiana statusu publikacji ofert
czy są to sekundy, minuty , godziny?

dałem takie żadanie pół godziny temu i task ma nadal status "NEW"

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście występuje jakiś problem proszę o cierpliwość. Sprawę przekazałem do odpowiedniego zespołu.
