### ISSUE TITLE
Sandbox - testy ofert - wyszukiwarka, faktury

### ISSUE THREAD

**Issue by Levena007** [allegro/allegro-api#7370]
Witam,
1. testuje w sundbox dodanie oreft do koszyka. W  tej chwili mam dwie oferty - dodając jedną z nich jest widoczna opcja "Chcę otrzymać fakturę" w drugiej nie.
Ustawienia ofert są takie same. Skąd moze wynikać problem?

2. Na koncie klienta, nie działa wyszukiwarka produktów - ofertę znajduje tylko mając bezpośredni adres url (wpisuje słowa z nazwy produktu).

Czy mogę prosić o pomoc?

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Proszę podaj konkretne numery ofert, wówczas będę mógł się przyjrzeć sytuacji. Podobnie w drugim przypadku - tu również proszę o szczegóły.

**Comment by Levena007** [comment]
1. Oferty:
https://allegro.pl.allegrosandbox.pl/oferta/rcv-7709152249
https://allegro.pl.allegrosandbox.pl/oferta/rcv-5-test-1-7712325039

2. Słowo kluczowe: RCV

**Comment by Levena007** [comment]
1. Rozumiem - dziękuję, to rozwiewa moje wątpliwości
2. Powinna się przecież zindeksować oferta nr.1. A jej też nie znajduje

**Comment by MaciejFrackowiak** [comment]
Jak widzę obie oferty są już w pełni widoczne -> https://allegro.pl.allegrosandbox.pl/listing?string=RCV

**Comment by Levena007** [comment]
Super, dziękuje

**Comment by Levena007** [comment]
Witam,
w piątek założyłam kolejne 2 oferty:
7713429264
7713428372

Na słowo kluczowe "vc7", "vc 7 " nie znajduje produktów z ofert, a minął już czas w którym produkty powinny się zindeksować. Problem jest więc analogiczny do opisanego w punkcie 2.

Czy mogę prosić o pomoc i wyjaśnienie tego tematu.

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Nie potwierdzam problemu - obie oferty są widoczne: https://allegro.pl.allegrosandbox.pl/listing?string=vc%207

**Comment by MaciejFrackowiak** [comment]
Problem stanowi wersja strony - oferty w polskiej wersji serwisu są dostępne. Jest to związane z metodami dostawy - dla obu ofert wysyłka jest możliwa tylko do Polski, zatem oferty dostępne są wyłącznie w polskiej wersji językowej.
