### ISSUE TITLE
Dlaczego oferta uznana za zawierająca linki?

### ISSUE THREAD

**Issue by is-tomaszgasior** [allegro/allegro-api#7371]
Dlaczego oferta o ID 13759981637 (środowisko produkcyjne allegro.pl) została uznana za zawierającą niedozwolone linki? Który konkretnie fragment opisu tej oferty stanowił niedozwolony link?

**Comment by MaciejFrackowiak** [comment]
W tej kwestii skontaktuj się proszę bezpośrednio z obsługą serwisu poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
