### ISSUE TITLE
Odpowiednik show_item.php dla Allegro CZ

### ISSUE THREAD

**Issue by PLTytus** [allegro/allegro-api#7372]
Oferta dostępna na Allegro PL i CZ, adres https://allegro.pl/show_item.php?item=13745936974 przekierowuje na market PL, jaki jest odpowiednik dla marketu CZ? Nigdzie nie mogę znaleźć tej informacji, adres https://allegro.cz/show_item.php?item=13745936974 zwraca 404.

**Comment by MartaNowaczyk** [comment]
To nie kwestia API, dlatego takie pytania kieruj przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). Jednak z tego co sprawdziłam odpowiednie przekierowanie dostaniesz używając https://allegro.cz/nabidka/13745936974.

**Comment by rtnet-pl** [comment]
https://allegro.cz/nabidka/12682171268
