### ISSUE TITLE
Numer referencyjny - label

### ISSUE THREAD

**Issue by Skuria** [allegro/allegro-api#7373]
Witam,
Planujemy wpisywać numer referencyjny na etykietę, niestety wystąpił nam pewien problem/ niezgodność na razie na środowiku testowym ale myślę że może być również na produkcji.

Tworząc przesyłkę w systemie przewoźnika lub po prostu przez stronę allegro bez problemu w pole numer referencyjny możemy wprowadzić inne znaki niż małe/duże litery i cyfry- np numer dokumentu "FS/1/2/MAG/1"
![image](https://github.com/allegro/allegro-api/assets/42569681/3924819a-9981-4593-9882-66a8c9a61611)

Niestety dodając obsługę tego pola w api wpisując taki sam numer dostajemy błąd walidacji:

{"errors":[{"code":"VALIDATION_ERROR","message":"musi pasować do wzorca \"[A-Za-z0-9 _-]*\"","details":"Invalid value: ZK 431/JK/MAG/07/2023","path":"label.referenceNumber","userMessage":"musi pasować do wzorca \"[A-Za-z0-9 _-]*\""}]}

W jaki sposób przesłać w takim razie numer faktury aby był drukowany tak jak nadanie przez stronę Allegro?

**Comment by Lukasz-Zurek** [comment]
Mamy obecnie pewną niespójność, dlatego sprawę konsultuję z zespołem odpowiedzialnym za tę usługę. Z całą pewnością problem w API rozwiąże zamiana "/" na "-". Niemniej jednak jak tylko uzyskam więcej informacji na temat tego czy będziemy w API zezwalać na "/" - poinformuję o tym fakcie w Twoim wątku.

**Comment by Skuria** [comment]
Jasne, w takim razie czekam na informacje, proszę mieć jednak na uwadze że to raczej standardowa numeracja każdego z systemów ERP.

**Comment by Skuria** [comment]
@Lukasz-Zurek 
Czy coś dzieje się w tej sprawie? 
Oprogramowaliśmy rozszerzenie do usuwania znaków innych niż Litery i Cyfry - przez jakiś czas to działało, a aktualnie znów dostajemy błąd tym razem z wzorcem:

"errors":[{"code":"VALIDATION_ERROR","message":"musi pasować do wzorca "[A-Z]{2}"

Czy możemy dostać jasno określone warunki jakie muszą być spełnione do poprawnego wypełnienia tego pola?

**Comment by Skuria** [comment]
@Lukasz-Zurek Czy jest to definiowane typem przewoźnika? Skąd możemy pobrać w takim razie wzorce per każdy z przewoźników?

**Comment by Lukasz-Zurek** [comment]
@Skuria Podeślij proszę trace-id, lub commandId, sprawdzimy ten konkretny przypadek. Obecny wzorzec to `[A-Za-z0-9 _-]*`, jednakże przewoźnicy mogą posiadać różne wzorce, tzn. może się zdarzyć niespójność w tym zakresie. Dlatego wolimy to sprawdzić na konkretnym zgłoszeniu.

Dodam, że planujemy dodać `/` do obecnego wzorca.
