### ISSUE TITLE
Problem z wystawieniem oferty na nowym koncie - "Access denied. You are not authorized to perform operations on the indicated offer"

### ISSUE THREAD

**Issue by lukaszinnweb** [allegro/allegro-api#7374]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Witam! Mam problem z wystawieniem pierwszej testowej aukcji na nowo stworzonym koncie, na api produkcyjnym. Dodam że fragment kodu, który wykorzystuję działa bez problemu na innych kontach allegro (posiadam własny CRM) u innych klientów. Teraz jednak wystąpił problem i zastanawiam się czy to nie przez fakt iż może konto musi być zarejestrowane jako firma??? Bądź muszę wystawić jakąś pierwszą aukcję ręcznie? Tak jak wspomniałem u innego klienta, używam tego samego kodu (oczywiście z innymi tokenami client-id, secret i seller-id) i wszystko działa bez problemu na jego koncie. Tutaj czy tworzę nowy produkt, czy łączę już z istniejącym, to ten sam błąd.

Otrzymany błąd to: 

Access denied. You are not authorized to perform operations on the indicated offer

Sęk w tym że client id oraz shopper id i client service id jest przypisane pod moje konto, także nie rozumiem komunikatu.

Poniżej cały response wraz z trace-id (trace-id: 3facc570b7e29341) oraz wysyłany request. W tym przypadku wystawiany produkt jest przypisany pod ten z bazy allegro:

string(196) "{"errors":[{"code":"OfferAccessDeniedException","message":"Forbidden","details":null,"path":"","userMessage":"Access denied. You are not authorized to perform operations on the indicated offer"}]}" array(12) { [0]=> string(22) "HTTP/1.0 403 Forbidden" [1]=> string(10) "expires: 0" [2]=> string(61) "cache-control: no-cache, no-store, max-age=0, must-revalidate" [3]=> string(31) "x-xss-protection: 1; mode=block" [4]=> string(16) "pragma: no-cache" [5]=> string(21) "x-frame-options: DENY" [6]=> string(26) **"trace-id: 3facc570b7e29341"** [7]=> string(35) "date: Tue, 18 Jul 2023 08:16:19 GMT" [8]=> string(63) "strict-transport-security: max-age=31536000 ; includeSubDomains" [9]=> string(31) "x-content-type-options: nosniff" [10]=> string(45) "content-type: application/json; charset=UTF-8" [11]=> string(19) "content-length: 196" } 

** PONIŻEJ PRZESYŁANY REQUEST**

    [productSet] => Array
        (
            [0] => Array
                (

                    [product] => Array
                        (
                            [name] => To jest producent Buty Vans Zwykłe
                            [category] => Array
                                (
                                    [id] => 87981
                                )
                            [id] => 39dcf464-1c8b-40e1-bf5c-ffecc325a574
                        )

                    [quantity] => Array
                        (
                            [value] => 1
                        )

                )
        )
    [b2b] => Array
        (
            [buyableOnlyByBusiness] => 
        )

    [stock] => Array
        (
            [available] => 25
            [unit] => UNIT
        )

    [delivery] => Array
        (
            [shippingRates] => Array
                (
                    [id] => 8a06d4b6-42e4-4b46-9746-c83f70e0db74
                )

            [handlingTime] => PT24H
        )

    [publication] => Array
        (
            [duration] =>  
            [status] => ACTIVE
        )

    [compatibilityList] => 
    [category] => Array
        (
            [id] => 87981
        )

    [parameters] => Array
        (
            [0] => Array
                (
                    [id] => 11323
                    [valuesIds] => Array
                        (
                            [0] => 11323_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [1] => Array
                (
                    [id] => 229205
                    [valuesIds] => Array
                        (
                            [0] => 229205_340245
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

        )

    [afterSalesServices] => Array
        (
            [impliedWarranty] => Array
                (
                    [id] => ffaae85d-2538-4249-b4a8-941bae52aefb
                )

            [returnPolicy] => Array
                (
                    [id] => 48593220-a0e7-4511-a445-7e3ab387daa8
                )

        )

    [payments] => Array
        (
            [invoice] => VAT
        )

    [sellingMode] => Array
        (
            [format] => BUY_NOW
            [price] => Array
                (
                    [amount] => 66.23
                    [currency] => PLN
                )

        )

    [location] => Array
        (
            [countryCode] => PL
            [province] => PODKARPACKIE
            [city] => Jasło
            [postCode] => 38-200
        )

    [images] => Array
        (
            [0] => https://a.allegroimg.com/original/11fdd5/355540c7429e842f1d0d490d2450
            [1] => https://a.allegroimg.com/original/118060/c6305d1f451cb61beaf0044f9469
            [2] => https://a.allegroimg.com/original/116ee4/8a52e2334056ad4b2f2243903b11
            [3] => https://a.allegroimg.com/original/113165/581eac7f4252b0ea75f0d90bb561
        )

    [description] => Array
        (
            [sections] => Array
                (
                    [0] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => TEXT
                                            [content] => Tutaj jest opis, usunąłem go na github.
                                        )

                                )

                        )

                    [1] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => IMAGE
                                            [url] => https://a.allegroimg.com/original/11fdd5/355540c7429e842f1d0d490d2450
                                        )

                                )

                        )

                    [2] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => IMAGE
                                            [url] => https://a.allegroimg.com/original/118060/c6305d1f451cb61beaf0044f9469
                                        )

                                )

                        )

                    [3] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => IMAGE
                                            [url] => https://a.allegroimg.com/original/116ee4/8a52e2334056ad4b2f2243903b11
                                        )

                                )

                        )

                    [4] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => IMAGE
                                            [url] => https://a.allegroimg.com/original/113165/581eac7f4252b0ea75f0d90bb561
                                        )

                                )

                        )

                )

        )

    [external] => Array
        (
            [id] => 5
        )

** KONIEC REQUESTA **

**Comment by Lukasz-Zurek** [comment]
Twoje podejrzenia były prawidłowe - błąd zwracamy z uwagi na to, że ofertę próbujesz wystawić z poziomu konta zwykłego i tu potrzebne będzie przekonwertowanie go na konto firmowe.

**Comment by lukaszinnweb** [comment]
@Lukasz-Zurek super, dzięki za odpowiedź
