### ISSUE TITLE
Delivery methods setup 

### ISSUE THREAD

**Issue by razekZNZ** [allegro/allegro-api#7375]
Dear all,
I am not able to set up delivery methods properly. Allegro help center told me to go here. 
We have CZ VAT number. Superior account is set up for Allegro.PL, We have also set up account for Allegro.CZ, linekd to the superior. Both accounts succesfully validated. 
We use Baselinker for integration. 

Problem: I am not able for Allegro.cz set up combination of deliver methods a) Packeta (both PuP and PuB) and b)courier DPD (other than WeDo).  We also want to ship from CZ account only within CZ. But the system force me to set the delivery method also for POL region.

Can you help me? 
thanks

**Comment by Lukasz-Zurek** [comment]
I can confirm that you can only set up combination of Packeta methods together with WeDo Courier. You cannot choose DPD Courier from CZ to CZ. 

Another thing - you should choose at least one delivery method from allegro.pl with a price in PLN. There you can choose DPD Courier - shipping from CZ to PL.
