### ISSUE TITLE
Wartości "status" dla Get single message

### ISSUE THREAD

**Issue by kepesian** [allegro/allegro-api#7376]
WItam, 
jakie sa dostępne wartości tej zmiennej poza:
"VERIFYING", "DELIVERED"

Interesują mnie wszystkie wartości ale w szczególności wartość dla wiadomości zablokowanej przez filtr Allegro, ze względu na zawartość odnośnika do zasobu poza allegro który jest uznany za niezgodny regulaminowo.
Dziękuję za info

**Comment by Lukasz-Zurek** [comment]
Zgodnie z [dokumentacją](https://developer.allegro.pl/documentation/#operation/getMessageGET) w polu **"status"** zwracamy następujące wartości:

- "VERIFYING",
- "BLOCKED",
- "DELIVERED",
- "INTERACTING",
- "DISMISSED".

Pozostałe kwestie konsultuję z zespołem odpowiedzialnym za te funkcjonalności. Proszę o cierpliwość.
