### ISSUE TITLE
Product Offer - OfferAccessDeniedException

### ISSUE THREAD

**Issue by dgkdev** [allegro/allegro-api#7377]
I'm trying to create a product using the following link: https://api.allegro.pl.allegrosandbox.pl/sale/product-offers, but I'm getting an OfferAccessDeniedException error. The userMessage says, 'Access denied. You are not authorized to perform operations on the indicated offer.' What do we need to do to resolve this error?

**Comment by dgkdev** [comment]
trace-id: 9f85bd4f9989f9a3

**Comment by Lukasz-Zurek** [comment]
@dgkdev Ok, you have a regular account, this is why you receive an error. You should convert it to company account, which you can do right [here](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by Lukasz-Zurek** [comment]
@dgkdev Your company account should be verified so I've just verified it. Please try again and let me know.

**Comment by dgkdev** [comment]
`errors: [
    {
      code: 'ShippingRatesNotFoundException',
      message: 'Unprocessable Entity',
      details: null,
      path: 'delivery.shippingRates',
      userMessage: 'The user does not have a shipping price list named: default.'
    }
  ]`

I have already shipping-rates, when i send get request this url: https://api.allegro.pl.allegrosandbox.pl/sale/shipping-rates?seller.id=106018578, its gives 3 results.

**Comment by Lukasz-Zurek** [comment]
Yes, you have 3 shipping rates (with the same name), but none of these names are "default". So you should create one or edit one of current shipping rates.

If you have only one delivery price list, we will assign it to the offer. In other cases - we will use the delivery price list with name **default**. If you don't have a delivery price list with this name, we will return 422 status.

**Comment by dgkdev** [comment]
Thank you for helping us, i edited current shipping rates(name => default) and successfully product create. The product publication status appears to be inactive; does it require approval from the system to become active?

`
{
  name: 'Omer Test Product 8',
  productSet: [ { product: [Object], quantity: [Object] } ],
  parameters: [
    {
      id: '11323',
      name: 'Stan',
      values: [Array],
      valuesIds: [Array],
      rangeValue: null
    }
  ],
  images: [
    'https://a.allegroimg.allegrosandbox.pl/original/11e0ec/037187f8417fae4d51b3f2e48928'
  ],
  afterSalesServices: {
    impliedWarranty: { id: '2d93ce2e-1842-4e46-b317-7d94ec862ae9' },
    returnPolicy: { id: '0f82b8ff-4eb7-4dba-a02a-1c04f0af4bb5' },
    warranty: null
  },
  payments: { invoice: 'VAT' },
  sellingMode: {
    format: 'BUY_NOW',
    price: { amount: '220.85', currency: 'PLN' },
    startingPrice: null,
    minimalPrice: null
  },
  stock: { available: 10, unit: 'UNIT' },
  location: {
    countryCode: 'PL',
    province: 'MAZOWIECKIE',
    city: 'warszawa',
    postCode: '00-867'
  },
  delivery: {
    shippingRates: { id: '1e36fca3-44dd-46b0-9144-e82ccb31a53a' },
    handlingTime: 'PT24H',
    additionalInfo: null,
    shipmentDate: null
  },
  description: { sections: [ [Object] ] },
  external: null,
  category: { id: '257931' },
  tax: null,
  taxSettings: null,
  sizeTable: null,
  discounts: { wholesalePriceList: null },
  contact: null,
  fundraisingCampaign: null,
  messageToSellerSettings: null,
  attachments: [],
  b2b: { buyableOnlyByBusiness: false },
  additionalServices: null,
  compatibilityList: null,
  additionalMarketplaces: { 'allegro-cz': { sellingMode: null, publication: [Object] } },
  id: '7714237713',
  language: 'pl-PL',
  publication: {
    status: 'INACTIVE',
    duration: null,
    endedBy: null,
    endingAt: null,
    startingAt: null,
    republish: false,
    marketplaces: { base: [Object], additional: [] }
  },
  validation: { errors: [], warnings: [], validatedAt: '2023-07-19T12:59:40.364Z' },
  createdAt: '2023-07-19T12:59:40.000Z',
  updatedAt: '2023-07-19T12:59:40.397Z'
}
`

**Comment by Lukasz-Zurek** [comment]
@dgkdev I am sorry for waiting for so long. In this case the offer was successfully listed. You received 202 status code which does mean that it was publicated asynchronously. If you received 201 Created status, then we would have created it synchronously. 

You can read more about offer publication in asynchronous API in [our tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#offer-publication-in-asynchronous-api).

**Comment by dgkdev** [comment]
thank you for your answers.
