### ISSUE TITLE
BAD_REQUEST

### ISSUE THREAD

**Issue by krzysda** [allegro/allegro-api#7378]
Witam,
Dzisiaj od rana dostaję dziwne odpowiedzi podczas generowania paczek z Allegro One Kurier:
{s:4:"code";s:11:"BAD_REQUEST";s:7:"message";s:27:"The Name field is required.";s:7:"details";N;s:4:"path";s:20:"Shipment.ShipTo.Name";s:11:"userMessage";s:0:"";}}}

Shipment.ShipTo.Name jakie to pole ?

receiver->name jest uzupełnione

**Comment by Lukasz-Zurek** [comment]
W tej sytuacji prześlij proszę trace-id, lub commandId. Sprawdzę czy faktycznie w żądaniu wszystko jest ok i ewentualnie skonsultuję to z odpowiednim zespołem.

**Comment by krzysda** [comment]
64b7943b-64b7-64b7-64b7-64b7943b4f18

**Comment by Lukasz-Zurek** [comment]
@krzysda Ok, dziękuję. Weryfikujemy to.
