### ISSUE TITLE
Pobieranie nazwy kategorii z id kategorii

### ISSUE THREAD

**Issue by zymod** [allegro/allegro-api#7379]
Witam serdecznie,

czy istnieje możliwość pobrania drzewa kategorii poprzez API?

Gdybym chciał manualnie spisać nazwy i idendyfikatory kategorii zajęło by to z dwa tygodnie.

Wczoraj próbowałem zautomatyzować ten proces używając python oraz  webdriver, ale zostałem przez was zablokowany ponieważ allegro wykryło bota na moim komputerze. 

Jak sobie z tym po ludzku poradzić?

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Nie pobierzesz całego drzewa kategorii poprzez API, ale możesz pobierać kategorie za pomocą [GET /sale/categories](https://developer.allegro.pl/documentation/#operation/getCategoriesUsingGET) i zagłębiać się w kategorie niższych rzędów za pomocą parametru parent.id.

**Comment by zymod** [comment]
Okej działa dziękuję bardzo Panu za pomoc.

Pozdraiwam

**Comment by Lukasz-Zurek** [comment]
Niestety nie ma innej możliwości uzyskania informacji dotyczących kategorii i dalej podkategorii niższego rzędu.

**Comment by Lukasz-Zurek** [comment]
> Z tego co zauważyłem to nie ma możliwości przejścia z rodzica do dzieci, a jedynie z dziecka do rodzica. To bardzo mało elastyczne bo i tak muszę manualnie wyciągać id najniższego dziecka.
> 
> Załóżmy że wykonuje zapytanie get na sale/categories/16618 co jest kategorią smartfony i telefony komórkowe htc.
> 
> Nie otrzymam listy podkategorii dla smartfony i telefony komórkowe htc, a smartfony i telefony komórkowe.
> 
> Nie mogę więc zejść niżej. Jeżeli jednak zacznę od najniższego miejsca w drzewie czyli ostatniego dziecka to z tego miejsca i tak mogę dojść do rodzica i później do kolejnego rodzica, a to znaczy że ten przepływ i tak jest liniowy.
> 
> Naprawdę nie ma możliwości posiadając tych 13 id które są kategoriami głównymi zebrać wszystkie id podkategorii ?

Dodam jeszcze, że mając **parent.id** dotrzesz do najniższego dziecka.

Przykładowo wysyłasz żądanie: GET sale/categories?parent.id=165, wybierasz podkategorię, dla których chciałbyś uzyskać niższe kategorie, np. 4937 (GET sale/categories?parent.id=4937). Dlatego w ten sposób uda Ci się uzyskać wszystkie informacje. Nie potrzebujesz identyfikatora najniższego dziecka. Potrzebujesz tylko **parent.id**, dzięki któremu uzyskujesz wszystkie liście niższych kategorii, po kolei, wg. powyższego schematu.

**Comment by zymod** [comment]
Okej to chyba wszystko.
