### ISSUE TITLE
Problem z metodą  PUT/sale/offer-publication-commands/{commandId} 

### ISSUE THREAD

**Issue by andrzejg07** [allegro/allegro-api#738]
od godz. 11.58 09-10-2018 nie można opublikować oferty.
Drafty ofert zapisują się lecz ze statusem INACTIVE
Nie można zmienić statusu oferty na ACTIVE
brak komunikatów błędów.
Całość przypomina sytuacje z przed kilku tygodni opisaną w wątku #543

**Comment by dostawcaopon** [comment]
mam to samo
