### ISSUE TITLE
WZA Pole firma nadawcy jest wymagane

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#7380]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ X ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzisiaj od godziny 9 przestały nam się generować przesyłki ze z powodu błędu "Pole firma nadawcy jest wymagane". Do tej pory nie ustawialiśmy tego pola które wg dokumentacji nie jest wymagane. Czy były jakieś zmiany w tym zakresie i to pole będzie wymagane i dokumentacja nie jest jeszcze zaktualizowana czy może jakiś tymczasowy błąd i pole zostanie przywrócone jako nie wymagane? (pole pickup.company na endpoincie /parcel-management/parcel-create-commands/{commandId})

**Comment by Lukasz-Zurek** [comment]
Być może mamy tutaj do czynienia z błędem. Prześlij proszę przykładowe trace-id, lub commandId. Przekażę je dalej do weryfikacji.

**Comment by d3stozaur** [comment]
'trace-id': 'e619870989681598'
/parcel-management/parcel-create-commands/2e0edb5e-2a45-4c6c-9c54-82febd89fdd9

**Comment by Lukasz-Zurek** [comment]
@d3stozaur Dziękuję. Weryfikujemy ten przypadek.

**Comment by Lukasz-Zurek** [comment]
@d3stozaur Nasz operator odnotował błąd, przez co wymagane jest wypełnienie pola, które widnieje jako opcjonalne. Trwają prace nad poprawką. Jak tylko uda się ją wdrożyć - poinformuję w wątku.

Przepraszamy za zaistniałe utrudnienia.

**Comment by SlawekMat** [comment]
Mam podobny problem od kilku dni

**Comment by Lukasz-Zurek** [comment]
@SlawekMat Nasz operator pracuje nad poprawką, która ma zostać wdrożona jeszcze w tym tygodniu.
