### ISSUE TITLE
Aktywne punkty odbioru dla "Allegro Odbiór w Punkcie DPD Pickup" na serwerze testowym.

### ISSUE THREAD

**Issue by lmichalFerrodo** [allegro/allegro-api#7381]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry, czy mogę prosić o podesłanie listy działających punktów odbioru dla przesyłki typu "Allegro Odbiór w Punkcie DPD Pickup" na środowisku testowym. Zarówno z Państwa strony jak i własnego programu do integracji otrzymuje komunikat: "Punkt odbiorcy jest niepoprawny" 
![Allegro_error](https://github.com/allegro/allegro-api/assets/104895935/ece049c8-dace-4fcd-9e27-dc22f6b91fe3)

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Nie mamy listy działających punktów odbioru na sandboxie. Dopytuję jeszcze zespołu odpowiedzialnego za punkty odbioru. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@lmichalFerrodo Spróbuj skorzystać z punktu PL50870 (3907842), powinien działać.

**Comment by lmichalFerrodo** [comment]
Podany punkt zadziałał. Mógłbym jeszcze poprosić o wskazanie działającego punku na serwerze testowym dla typu usługi: "Allegro Odbiór w Punkcie Pocztex" oraz "Allegro Automat Pocztex". Z góry bardzo dziękuje za pomoc! :)

**Comment by Lukasz-Zurek** [comment]
@lmichalFerrodo W przypadku "Allegro Odbiór w Punkcie Pocztex" działający punkt to 257665, natomiast w kwestii "Allegro Automat Pocztex" - dopytuję innego zespołu. Wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@lmichalFerrodo W przypadku "Allegro Automat Pocztex" powinien zadziałać punkt: Pocztex Automat - Lewiatan
POCZTA_POLSKA: 737130 (3938060)

**Comment by lmichalFerrodo** [comment]
@Lukasz-Zurek bardzo dziekuje!

**Comment by lmichalFerrodo** [comment]
@Lukasz-Zurek mogę prosić o dokładne adresy dla wyżej wymienionych punktów: "Allegro Automat Pocztex" oraz "Allegro Odbiór w Punkcie Pocztex". Niestety podczas wyboru punktu na mapie z poziomu Allegro nie widać wypisanych przez Ciebie numerów punktów.

**Comment by Lukasz-Zurek** [comment]
@lmichalFerrodo Oczywiście.

"Allegro Odbiór w Punkcie Pocztex", 257665: 

ul. Dworcowa 10
86-150 Osie
kujawsko-pomorskie

-------

"Allegro Automat Pocztex", 3938060:

ul. Sandora Petofiego 3
01-917 Warszawa
mazowieckie

**Comment by lmichalFerrodo** [comment]
Przy próbie utworzenia paczki na poniższy punkt otrzymuje komunikat : Punkt odbiorcy jest niepoprawny.

"Allegro Automat Pocztex", 3938060:

ul. Sandora Petofiego 3
01-917 Warszawa
mazowieckie

Uprzejmie proszę o wskazanie innego działającego punktu.

**Comment by Lukasz-Zurek** [comment]
@lmichalFerrodo Sprawę konsultuję z odpowiednim zespołem. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@lmichalFerrodo Podaj proszę nr zamówienia, lub commandId/trace-id, jeśli próbujesz nadać poprzez API.

**Comment by Lukasz-Zurek** [comment]
@lmichalFerrodo Nadal weryfikujemy ten przypadek. Problem polega na tym, że punkty, które na sandboxie - z perspektywy Kupującego - działają prawidłowo, nie przechodzą podczas próby nadawania przesyłki.

**Comment by lmichalFerrodo** [comment]
@Lukasz-Zurek coś się udało ustalić?

**Comment by Lukasz-Zurek** [comment]
@lmichalFerrodo Operator najprawdopodobniej korzysta z innych punktów na środowisku testowym, aniżeli te, które wspieramy w naszym Serwisie dla Kupujących (i one powinny być spójne z punktami obsługiwanymi podczas nadawania przesyłek). Wyjaśniamy to z nimi.

**Comment by lmichalFerrodo** [comment]
Udało się państwu znaleźć problem lub inny działający punkt?

**Comment by Lukasz-Zurek** [comment]
@lmichalFerrodo Mamy problem, który polega na braku spójności punktów pomiędzy naszym Serwisem a operatorem. Chcąc uzyskać chociaż jeden działający punkt od operatora, dopytuję właśnie odpowiedniego zespołu. Wrócę do Ciebie z informacją. Przepraszam, że to tak długo trwa.

**Comment by lmichalFerrodo** [comment]
Dzień dobry, mogę prosić o informacje czy udało sie znaleźć jakiś dostępny punkt na środowisku testowym? Oraz proszę o wskazanie nowe punktu odbiory dla usługi "Allegro Odbiór w Punkcie DPD Pickup". Wcześniej podany punkt PL50870 (3907842) chyba przestał być dostępny, otrzymuje poniższy komunikat.
![obraz](https://github.com/allegro/allegro-api/assets/104895935/e8d827e6-1298-478f-94f8-ff4e99b00861)

**Comment by Lukasz-Zurek** [comment]
Jeżeli chodzi o Pocztę Polską, spróbuj z tym punktem: 256181.

W przypadku DPD Pickup - DPD_PL53811 (3942859).

**Comment by lmichalFerrodo** [comment]
Niestety podany punkt dla DPD Pickup - DPD_PL53811 (3942859) nie działa na **serwerze testowym**. Postman zwraca błąd:
![obraz](https://github.com/allegro/allegro-api/assets/104895935/e5c2f7a9-cafe-46e6-9dfd-deb9bdc492aa)
Uprzejmie proszę o podanie innego punktu.

**Comment by Lukasz-Zurek** [comment]
@lmichalFerrodo Weryfikujemy.

**Comment by lmichalFerrodo** [comment]
Coś się udało ustalić?

**Comment by Lukasz-Zurek** [comment]
@lmichalFerrodo Mamy niestety niespójność jeżeli chodzi o punkty dostępne na środowisku testowym (np. ten wskazany powinien funkcjonować, ale u operatora otrzymujemy błąd), dlatego musieliśmy skontaktować się z naszym operatorem logistycznym. Proszę Cię o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@lmichalFerrodo Spróbuj z tymi punktami:

**PL12919** - 90-269 Łódź, ul. Piotrkowska 26
**PL12940** - 97-500 Radomsko, ul. Żeromskiego 30
**PL12950** - 62-085 Skoki, ul. Jana Pawła II 21
