### ISSUE TITLE
Środki i Historia operacji - różne kwoty wypłat PAYU i P24 w zależności od tego czy generowanie nastąpiło z panelu allegro czy poprzez zasób API

### ISSUE THREAD

**Issue by pietruszysko** [allegro/allegro-api#7382]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

 - podaj pełne cURL : https://api.allegro.pl/payments/payment-operations?occurredAt.gte=2023-07-18T00:00:00.000Z&occurredAt.lte=2023-07-18T23:59:59.000Z&offset='.$offset.'&limit=50
- podaj trace-id : 96d84be0fcd7289c

Ściągająca dane z -> https://allegro.pl/moje-allegro/sprzedaz/srodki-i-historia-operacji?dateFrom=2023-07-18&dateTo=2023-07-18&sellerId=66239152&filter=outcome 
Dla dat od 2023-07-18 do 2023-07-18 dla OUTCOME otrzymuje w przypadku wypłat dla PAYU i P24 inne kwoty niż w przypadku ściagania danych dla tych samych dni poprzez API.

**Comment by Lukasz-Zurek** [comment]
Wskaż proszę kilka przykładów (z "payout.id", kwotą i datą) z API, zestawiając je z danymi z zakładki "środki i historia operacji".

**Comment by pietruszysko** [comment]
PLIK CSV ALLEGRO				
data	identyfikator	operacja	operator	kwota
18.07.2023 00:30	b798bdb7-df7d-4d91-b5e6-de6e31800287	wypłata środków	PayU	-32 786,85 zł
18.07.2023 00:30	9b0e33ae-9b83-40ac-95ff-f8ccf536a67c	wypłata środków	Przelewy24	-57 334,31 zł


API ALLEGRO					
ID OPRACJI	DATA OPERACJI	TYP OPERACJI	OPERATOR	GRUPA	KWOTA
API_ZWRÓCIŁO_PUSTE_POLE	2023-07-18T22:31:00.419Z	PAYOUT	PAYU	OUTCOME	-28523.32
API_ZWRÓCIŁO_PUSTE_POLE	2023-07-18T22:31:00.357Z	PAYOUT	P24	OUTCOME	-53792.23

**Comment by pietruszysko** [comment]
ok jakie powinno być w takim razie zapytanie do api (data od - do) aby otrzymać tożsame dane co w Moim Allegro?

**Comment by Lukasz-Zurek** [comment]
Tak jak napisałem - w API mamy czas uniwersalny, co opisujemy w [naszym poradniku](https://developer.allegro.pl/tutorials/basic-information-VL6YelvVKTn#date-and-time), dlatego zawsze będzie występować różnica czasu pomiędzy API, a "Moim Allegro".

**Comment by pietruszysko** [comment]
Proste TAK/NIE wystarczy jako odpowiedź :) i zamykamy temat.

**Comment by Lukasz-Zurek** [comment]
Twoje pytanie sugeruje odpowiedź :) Odpowiem: NIE, ponieważ da się poprzez API uzyskać rzeczywiste kwoty wypłat, ale należy tutaj uwzględnić różnicę wspomnianych 2h (czas letni).

**Comment by pietruszysko** [comment]
Panie Łukaszu - działa tak jak powinno. Dziękuję za pomoc. Można zamykać. Tak przy okazji - czy to że przy wypłatach z PAYU i P24 nie widzę payout.id to bug czy ficzer:)?

**Comment by Lukasz-Zurek** [comment]
Sprawdziłem i w naszym API zwracamy Tobie wartość w **payout.id** dla operacji typu OUTCOME i tu problemu nie odnotowałem. Chyba, że chodzi o "Moje Allegro" i zakładkę "Środki i historia operacji" - w tej sytuacji nie jestem w stanie się wypowiedzieć i mogę jedynie zasugerować kontakt poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=1588cdd0-0680-4a7f-a68c-8e1864769ebb).
