### ISSUE TITLE
Dyskusje - scenariusz z pracownikiem Allegro

### ISSUE THREAD

**Issue by piotrooo** [allegro/allegro-api#7383]
Cześć!

Chcielibyśmy przetestować scenariusz dyskusji, z tym jak do rozmowy włącza się pracownik Allegro. Chcemy sprawdzić czy poprawnie obsłużyliśmy ten przypadek.
Jako że nie możemy sami za symulować tego scenariusza przez sandbox'a, prosilibyśmy o pomoc.

Jakich danych potrzebujecie, żeby to zrealizować?

**Comment by Lukasz-Zurek** [comment]
Podaj proszę identyfikator dyskusji, w której mógłbym się wypowiedzieć jako pracownik Allegro.

**Comment by piotrooo** [comment]
Sure.
UUID: `b14a21d9-724d-46d0-bc4e-241691f7835a`
Link: https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/dyskusje/b14a21d9-724d-46d0-bc4e-241691f7835a

**Comment by Lukasz-Zurek** [comment]
@piotrooo Dziękuję. Właśnie wypowiedziałem się we wskazanej dyskusji.

**Comment by piotrooo** [comment]
Dzięki za pomoc. Jeśli będę miał więcej pytań - pozwolę sobie otworzyć tego issue.
