### ISSUE TITLE
Rabaty sandbox

### ISSUE THREAD

**Issue by Levena007** [allegro/allegro-api#7385]
Witam,
chciałabym przetestować w sandbox wszystkie formy możliwych rabatów.
1. W zakładce programy widzę listę, jednak w większości przypadków moje oferty nie spełniają warunków wzięcia udziału w programie. jak mogę rozwiązać ten problem?
2. W jaki sposób mogę przetestować inne formy obniżki ceny (chodzi mi o ich wygląd na fv) - np. kupony allegro, kody mybenefit itp.
3. Czy są jeszcze jakieś formy rabatowania o których powinnam pomyśleć?
Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Dostępne rabaty i promocje, którymi możesz zarządzać przez API opisaliśmy w [poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-rabatami-promocjami-yPya2mj6zUP). 

Kupony możesz tworzyć w zakładce [Kupony](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/kupony). Musisz jednak spełnić 2 warunki: 
- posiadać konto firmowe
- co najmniej neutralny poziom jakości sprzedaży.

Możesz zasymulować udane zakupy, aby spełnić drugi warunek. 

Dodatkowo [w poradniku opisaliśmy](https://developer.allegro.pl/tutorials/jak-przypisac-oferte-kampanii-GRaj0q6Gwuy), jak posługiwać się oznaczeniami z kampanii. W środowisku testowym skonfigurowaliśmy kampanię ’SANDBOX_TEST_CAMPAIGN’, aby można było samodzielnie sprawdzić proces.
