### ISSUE TITLE
ZPL label

### ISSUE THREAD

**Issue by Vera57** [allegro/allegro-api#7386]
Hello everybody,

I created the PDF label api.allegro.pl.allegrosandbox.pl/parcel-management/parcels/label?parcelId=e4bb9947-2a6c-4e13-823b-dd603cebf5dc just fine, but when I user totally the same request for creating a ZPL-Label  (I switched PDF and ZPL in the request), I got a Bad Request Error {"errors":[{"code":"BAD_REQUEST","message":"Opennet cant process label request","details":null,"path":null,"userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}]}
What's the problem with this request api.allegro.pl.allegrosandbox.pl/parcel-management/parcels/label?parcelId=e9bd8cd6-922b-439c-b8c3-c4be15007fe4?

**Comment by AureliuszBrussy** [comment]
You choose the label file format at the parcel creation stage ([GET parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/getParcelCreationStatus) - label.fileFormat field). You can't change it at the label download stage. You need to choose a different format when creating a parcel.

**Comment by Vera57** [comment]
Okay, because this order id is for a PDF shipment, I can't create a ZPL Label.

Another question: after I have the delivery.method.id from the GET https://api.{environment}/order/checkout-forms/{id} webservice call, I need it for the PUT https://api.{environment}/parcel-management/parcel-create-commands/{commandId} webservice call, but can I always find the same id in the https://api.{environment}/parcel-management/delivery-services, so that I now which additional services I can use for the PUT https://api.{environment}/parcel-management/parcel-create-commands/{commandId} ?

**Comment by AureliuszBrussy** [comment]
Yes, the id's returned in the orders are consistent with those we return in delivery services. However, some (custom contracts) may have a custom id attached to the string id. You can read more about this in [our news](https://developer.allegro.pl/news/ship-with-allegro-we-will-change-delivery-services-ids-2YxbKZgo2tD).

**Comment by Vera57** [comment]
Okay thank you very much for your help
