### ISSUE TITLE
[REST API] carriers ALLEGRO tracking 

### ISSUE THREAD

**Issue by allegrofan** [allegro/allegro-api#7387]
Dzień dobry,
na zapytanie: https://api.allegro.pl/order/carriers/ALLEGRO/tracking?waybill='.$data->numer

otrzymuję odpowiedź:
Array ( [errors] => Array ( [0] => Array ( [code] => NotAcceptableException [message] => Not acceptable representation requested. Please check 'Accept' request header [details] => [path] => [userMessage] => Request contains invalid data. Contact the application author. ) ) ) 

I nie działa tylko ALLEGRO. 
identyczne zapytania ale po innych przewoźników działają bez problemu:
https://api.allegro.pl/order/carriers/DPD/tracking?waybill='.$data->numer
https://api.allegro.pl/order/carriers/UPS/tracking?waybill='.$data->numer
https://api.allegro.pl/order/carriers/RUCH/tracking?waybill='.$data->numer

**Comment by AureliuszBrussy** [comment]
Sprawdziłem to - na ten moment nie mogę potwierdzić błędu. Po przekazaniu nagłówka _Accept: application/vnd.allegro.public.v1+json_ wszystko działa prawidłowo. 

Podaj trace-id wywołania, które znajdziesz w nagłówku naszej odpowiedzi z errorem.
