### ISSUE TITLE
Zdjęcie oferty `https://a.allegroimg.com/original/119bc4/aa0cd76a482d939ceb9fca7e5ffa` zostało przekazane więcej niż jeden raz. (VALIDATION_ERROR)

### ISSUE THREAD

**Issue by wald3k89** [allegro/allegro-api#7389]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry, problem pojawia się podczas korzystania z zewnętrznego oprogramowania EasyUplaoder podczas próby aktualizacji zdjęć w galerii pojawia się komunikat "Zdjęcie oferty `https://a.allegroimg.com/original/119bc4/aa0cd76a482d939ceb9fca7e5ffa` zostało przekazane więcej niż jeden raz. (VALIDATION_ERROR)"
jednak w rzeczywistości po weryfikacji aukcji to zdjęcie nie jest powtórzone w galerii allegro problem występuje w różnych aukcjach

**Comment by hahyes** [comment]
@wald3k89 Powinieneś to zgłosić do wsparcia technicznego EasyUploader
