### ISSUE TITLE
[REST] wartość domyślna payments->invoice podczas tworzenia draftu ?

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#739]
Dzień dobry,
podczas tworzenia draftu "invoice" przyjmuje wartość domyślną : 
"payments":{"invoice":"NO_INVOICE"}

pytanie - dlaczego - jaka w tym logika ? Inne pola pomimo tego że są obowiązkowe nie mają wartości domyślnych np.
"afterSalesServices":null
"delivery":null
etc...

draft to draft - użytkownik jeszcze nie definiował tego pola ...
pozdrawiamy wwwfactory

**Comment by PawelTaberski** [comment]
Zgadza się w przypadku tych pozostałych wartość nie jest domyślnie uzupełniana, bo wymagają one konkretnych wartości UUID, w przypadku faktury . Pole invoice nie ma dostępnej wartości null.

**Comment by wwwfactory** [comment]
W takim razie dlaczego akurat  NO_INVOICE ? decydujecie za użytkownika ?

**Comment by PawelTaberski** [comment]
Rozumiem, że w wypadku tego pola również wolałbyś otrzymywać null zamiast proponowanej wartości? Jednakże jest to również jedno z niewielu pól, które nie wymagają podania wartości w formie UUID, bądź innego dedykowanego do danego konta identyfikatora. I w tym momencie user po zwróceniu danych jest świadom w jakim formacie powinien tutaj wprowadzić wartość.

**Comment by wwwfactory** [comment]
rozważmy następujący scenariusz : 
pracujemy w zespole wieloosobowym w którym jedna osoba jest odpowiedzialna za tworzenie draftów ofert (zdjęcia, opisy, nazwa, parametry towaru),  inna osoba zajmuje się sprzedażą a więc wypełnia pola parametrów aukcji (nie towaru) i trafia na wypełnione zdefiniowane pole invoice. Jak ma to traktować ? 

jeżeli stworzymy programistyczny precedens dla tego pola to jak oprogramować precedensy o których nie wiemy a które to wy tworzycie ?

wniosek - draft to draft - nie możecie sami definiować pól wg. własnego uznania. 
w tym przypadku invoice powinno być null  lub brak paramertu invoice w drafcie jeżeli nie był definiowany przez użytkownika.

wwwfactory

**Comment by PawelTaberski** [comment]
Dziękuję za szerszy kontekst przekazałem Państwa uwagę wraz z opisem do odpowiedniego zespołu. Jeśli zdecydujemy się zmienić obecne rozwiązanie to poinformujemy o tym.
