### ISSUE TITLE
Pay the arrears in Settlements with Allegro [AllegroSandbox]

### ISSUE THREAD

**Issue by damyanchik** [allegro/allegro-api#7390]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Cześć,
w podobnych wątkach z poniższym błędem widziałem, że mogę tu uzyskać pomoc w odblokowaniu konta na sandboxie. Prosiłbym o pomoc. 
Nazwa użytkownika: wiisioner

You do not have the permissions required to list an offer (sales suspended). Pay the arrears in Settlements with Allegro;

**Comment by AureliuszBrussy** [comment]
Usunąłem blokadę. Pamiętaj też o zasymulowaniu opłaty za rachunek w zakładce [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro).
