### ISSUE TITLE
Error 403 picture Upload

### ISSUE THREAD

**Issue by ithw23** [allegro/allegro-api#7391]
Hello, 

i get an 403 error while uploading pictures on endpoint https://upload.allegro.pl.allegrosandbox.pl/sale/images. I get the following response:

{"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"No access to the specified resource."}]}

How i get access to this endpoint.

Best regards

Lars

**Comment by AureliuszBrussy** [comment]
Make sure you use the right type of access token - bearer-token-for-user. You can generate such an access token using [code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow. 

If you are sure about this - please send the trace-id of the request that ended with this error. You can find the trace-id in the header of our response.

**Comment by ithw23** [comment]
Hello,

I checked the type of the token. It looks fine. I also tested the access to other endpoints like sale/categories/. That worked without any problems.

Below you will find the request and the response to the request including the trace-id. I overwrote the token with XXX.

request:
string(1874) "POST /sale/images HTTP/2
Host: upload.allegro.pl.allegrosandbox.pl
Authorization: Bearer XXX
Content-Type: application/vnd.allegro.public.v1+json
Accept-Language: en-US

header response
HTTP/2 403 
trace-id: 961ecde1b6c15bef
content-type: application/json; charset=utf-8
content-length: 145
date: Sun, 23 Jul 2023 13:36:08 GMT

**Comment by AureliuszBrussy** [comment]
Hi, you are using bearer-token-for-application obtained as a result of the [client_credentials flow](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#clientcredentials-flow). Use [code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow to obtain right type access token.
