### ISSUE TITLE
Parameter(s) validation error: EAN (GTIN), Product weight with unit packaging | Can't Upload Products due to this Error 

### ISSUE THREAD

**Issue by Wooconnector** [allegro/allegro-api#7394]
Dear Team,

I wanted to reach out regarding the product creation tutorial I followed. While attempting to create a product with all the necessary attributes, including the category ID and the required parameters, I encountered an issue during the parameter validation process. Specifically, I received the following error: "Parameter(s) validation error: EAN (GTIN), Product weight with unit packaging."

After carefully reviewing the "Listing an offer with a product" details, I discovered that the GTIN should be provided by the manufacturer. The tutorial did not provide clear guidance on this matter. Consequently, I am unsure of the appropriate steps to take since I am unable to create the product with the required parameters.

I kindly request your assistance in resolving this matter. Could you please guide me on how to proceed in this situation? Your help would be greatly appreciated.

Thank you for your attention to this matter, and I look forward to your response.

**Comment by PrzemyslawLukanowski** [comment]
Hello, please make sure you are providing the correct values in "EAN (GTIN)" and "Product weight with unit packaging" - the merchant who is listing the offers should know what the valid values are. In the context of API, there's not much we can help with - in the [tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#provide-gtin-as-a-parameter) we described, how to provide GTIN parameter - it's the same way as all other product parameters. When it comes to the validation of this parameter - the API response is the reflection of the validation of our website, it's not a API technical issue.

**Comment by Wooconnector** [comment]
Thanks for replying Let me follow the tutorial

**Comment by Wooconnector** [comment]
Hi Team, 
When I tried after following the tutorial with this payload to create ( propose ) a product still getting the same error **"The request contains invalid data. Contact the author of the application"** please look at the product payload and let me know what am I missing in there. 
Payload : 
{
	"name": "Beanie with Logo",
	"category": {
		"id": "a408e75a-cede-4587-8526-54e9be600d9f"
	},
	"description": {
		"sections": [{
			"items": [{
				"type": "TEX",
				"content": "Hi this is first description"
			}]
		}]
	},
	"images": [{
		"url": "https:\/\/a.allegroimg.com\/original\/110bca\/9e518c694146ac730da8cb35409b"
	}],
	"parameters": [{
		"valuesIds": ["11323_1", "11323_2"],
		"id": "11323"
	}, {
		"values": ["EAN (GTIN)"],
		"id": "225693"
	}, {
		"valuesIds": ["11323_1", "11323_2", "229205_340245", "229205_340249", "229205_340253", "229205_340257", "229205_340261"],
		"id": "229205"
	}],
	"language": "pl-PL"
}

**Comment by PrzemyslawLukanowski** [comment]
Hello, there are a few issues with your payload:

- you're trying to create a product in a category, which is not "leaf" (lowest-tier category). According to our [tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-create-a-product) - "(...) Remember that you can add products to the lowest-tier category marked “**leaf”: true.**". To get the lower level categories please use parent.id parameter in your GET /sale/categories request, for example, GET /sale/categories?parent.id=a408e75a-cede-4587-8526-54e9be600d9f. After choosing a proper category, please update the list of parameters associated with the selected category,
- there's a typo in description.sections.items.type - "TEX" instead of "TEXT". Please also keep in mind that content should contain HTML tags,
- in the EAN (GTIN) you didn't provide a proper value in "values" but instead you used a repetition of the parameter name,  
- in the 229205 parameters you've entered too many valuesIds, you can select only one here. Some of them are not related to this parameter (like 11323_1 and 11323_2).

**Comment by Wooconnector** [comment]
Thanks I really appreciate your quick response.

**Comment by Wooconnector** [comment]
okay, 
These are not the leaf categories where do I can child category? when I try this endpoint GET https://api.allegro.pl/sale/categories  all category leaf=false not leaf = true. 

These are the response from API {"categories":[{"id":"5","name":"Dom i Ogr\u00f3d","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false,"offersWithProductPublicationEnabled":false,"productCreationEnabled":false,"customParametersEnabled":true,"sellerCanRequirePurchaseComments":false}},{"id":"11763","name":"Dziecko","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false,"offersWithProductPublicationEnabled":false,"productCreationEnabled":false,"customParametersEnabled":true,"sellerCanRequirePurchaseComments":false}},{"id":"42540aec-367a-4e5e-b411-17c09b08e41f","name":"Elektronika","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false,"offersWithProductPublicationEnabled":true,"productCreationEnabled":true,"customParametersEnabled":true,"sellerCanRequirePurchaseComments":false}},{"id":"4bd97d96-f0ff-46cb-a52c-2992bd972bb1","name":"Firma i us\u0142ugi","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false,"offersWithProductPublicationEnabled":false,"productCreationEnabled":false,"customParametersEnabled":true,"sellerCanRequirePurchaseComments":false}},{"id":"a408e75a-cede-4587-8526-54e9be600d9f","name":"Kolekcje i sztuka","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false,"offersWithProductPublicationEnabled":false,"productCreationEnabled":false,"customParametersEnabled":false,"sellerCanRequirePurchaseComments":true}},{"id":"38d588fd-7e9c-4c42-a4ae-6831775eca45","name":"Kultura i rozrywka","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false,"offersWithProductPublicationEnabled":false,"productCreationEnabled":false,"customParametersEnabled":true,"sellerCanRequirePurchaseComments":false}},{"id":"ea5b98dd-4b6f-4bd0-8c80-22c2629132d0","name":"Moda","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false,"offersWithProductPublicationEnabled":false,"productCreationEnabled":false,"customParametersEnabled":true,"sellerCanRequirePurchaseComments":false}},{"id":"3","name":"Motoryzacja","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false,"offersWithProductPublicationEnabled":false,"productCreationEnabled":false,"customParametersEnabled":true,"sellerCanRequirePurchaseComments":false}},{"id":"20782","name":"Nieruchomo\u015bci","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":false,"advertisement":true,"advertisementPriceOptional":false,"offersWithProductPublicationEnabled":false,"productCreationEnabled":false,"customParametersEnabled":false,"sellerCanRequirePurchaseComments":false}},{"id":"3919","name":"Sport i turystyka","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false,"offersWithProductPublicationEnabled":false,"productCreationEnabled":false,"customParametersEnabled":true,"sellerCanRequirePurchaseComments":false}},{"id":"258832","name":"Supermarket","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false,"offersWithProductPublicationEnabled":false,"productCreationEnabled":false,"customParametersEnabled":true,"sellerCanRequirePurchaseComments":false}},{"id":"1429","name":"Uroda","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false,"offersWithProductPublicationEnabled":true,"productCreationEnabled":true,"customParametersEnabled":true,"sellerCanRequirePurchaseComments":false}},{"id":"121882","name":"Zdrowie","parent":null,"leaf":false,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false,"offersWithProductPublicationEnabled":false,"productCreationEnabled":false,"customParametersEnabled":true,"sellerCanRequirePurchaseComments":false}}]}


Thanks

**Comment by MaciejFrackowiak** [comment]
You should call [GET /sale/categories](https://developer.allegro.pl/documentation/#operation/getCategoriesUsingGET) with query parameter "parent.id" to receive the whole structure of categories and parameters. For example, you will receive Allegro's main categories when you call GET /sale/categories. Then, you should choose one and provide its id under "parent.id" - as a result, you will receive child categories of their parent category.
