### ISSUE TITLE
parcel-management/parcel-create-commands - jak uzupełnić dane w body na podstawie danych zamówienia dla różnych metod wysyłki Allegro One

### ISSUE THREAD

**Issue by akonopka11** [allegro/allegro-api#7395]
Dzień dobry,

Mam pytanie jak w temacie. Jest co prawda dokumentacja, ale nie jest to dla mnie do końca jasne. 

serviceId - tutaj wstawiam ID pobrane z parcel-management/delivery-services, więc ok

receiver i pickup - tutaj nie wiem, jak to mam ustawić dla różnych metod wysyłki. Czy w receiver mam po prostu dane klienta z zamówienia? Dlaczego tam jest pointId też? Czy to jest adres, na który pójdzie paczka przy wysyłce kurierem? Co ma być w polu pickup? Domyślałabym się, że to pole dotyczy punktu odbioru, pointId mam, ale co ma być w adresie, adres punktu, adres klienta? Email, name, company, phone - z danych klienta mają iść? Dlaczego to pole pickup jest zawsze wymagane? Dla kuriera również? Będzie tam wtedy to samo i w receiver i w pickup?

label.sender to są dane, które będą widoczne na etykiecie jako dane nadawcy? To się nie musi zgadzać z tym, skąd paczka faktycznie jest nadawana?

additionalServices.cashOnDelivery.accountNumber - czy ten numer konta można pobrać przez API gdzieś z ustawień konta sprzedawcy?

Potrzebuję generować etykiety dla tych metod dostawy:

   Allegro One Kurier - dostawa jutro
   Allegro: Allegro One Kurier pobranie - dostawa jutro
   Allegro One Punkt, One Kurier
   Allegro: Allegro One Punkt
   Allegro: Allegro One Box
   Allegro: Allegro One Box, One Kurier
   
Aktualnie nad "Allegro One Box, One Kurier" pracuję, więc od tego bym chciała zacząć.

Będę wdzięczna za podpowiedzi.

**Comment by akonopka11** [comment]
Jeszcze o to pole items mam pytanie, jak ustawię maksymalne wymiary dla danego gabarytu, to pójdzie jako ten gabaryt? Mogę tak zrobić? Pracownik wybierałby jaki gabaryt go interesuje.

Gabaryt S – 8 x 38 x 64 cm, waga do 20 kg
Gabaryt M – 19 x 38 x 64 cm, waga do 20 kg
Gabaryt L – 41 x 38 x 64 cm, waga do 20 kg.

**Comment by AureliuszBrussy** [comment]
1. w obiekcie **receiver** uzupełniasz dane odbiorcy i adres dostawy pobrany z zamówienia. Jeżeli klient zamówił dostawę do punktu odbioru, powinieneś dodatkowo przekazać w **pointId** identyfikator punktu odbioru (pobrany z zamówienia z pola delivery.pickupPoint.id).
2. W obiekcie  **pickup** uzupełniasz adres nadania (spod którego paczka zostanie nadana). 
3. W polu **label.sender** uzupełniasz dane nadawcy, które będą widoczne na etykiecie. Nie musi się zgadza z adresem, spod którego paczka była nadana. 
4. Nie ma możliwości pobrania tego numeru konta, Klient aplikacji musi samodzielnie go podać. Musi on też być zgodny z tym, który jest podany w Allegro do wypłaty środków z Allegro Finanse. 
5. W kwestii gabarytów - jest tak, jak napisałeś.

**Comment by akonopka11** [comment]
Ok, super, tak spróbuję wypełnić, będę się dopytywać w razie czego. Dziękuję :)

**Comment by akonopka11** [comment]
Gabaryt S – 8 x 38 x 64 cm, waga do 20 kg
Gabaryt M – 19 x 38 x 64 cm, waga do 20 kg
Gabaryt L – 41 x 38 x 64 cm, waga do 20 kg.

Te wymiary tutaj to będzie po kolei height, width i depth? Czy jakaś inna kolejność?

**Comment by AureliuszBrussy** [comment]
@akonopka11 tak, potwierdzam, to height x width x depth.

**Comment by akonopka11** [comment]
Udało mi się utworzyć przesyłkę w środowisku produkcyjnym:

commandId: 3bdf2b63-baef-487f-bc3a-fa7a22959886
parcelId: 3bdf2b63-baef-487f-bc3a-fa7a22959886

Sprawdziłam status, jest jako SUCCESS. 

Próbuję teraz pobrać etykietę z adresu /parcel-management/parcels/label, ale mam kod błędu 400 i odpowiedź:

{
    "errors": [
        {
            "code": "SHIPMENT_NOT_FOUND",
            "path": "parcelIds[%s]",
            "details": "Requested shipment was not found",
            "message": "Requested shipment was not found",
            "userMessage": "Nie odnaleziono przewozu"
        }
    ]
}

Co robię nie tak?

**Comment by akonopka11** [comment]
Dzień dobry, 
Udało mi się utworzyć przesyłkę w środowisku produkcyjnym. Sprawdziłam status i jest jako SUCCESS.
{"id": "dd4fdb34-7d85-4a2d-ab07-a8b2b4e80bf6", "errors": [], "status": "SUCCESS", "parcelId": "0e453a32-cb06-48b5-a247-41860e2378d8"}
Niestety, nie mogę pobrać etykiety. Kod odpowiedzi 200, pusta odpowiedź. Co mogę robić nie tak?

**Comment by akonopka11** [comment]
Z tego adresu: 
/parcel-management/parcels/label

**Comment by akonopka11** [comment]
Udało się wygenerować etykietę, dziękuję za pomoc.
