### ISSUE TITLE
Sandbox offer proposal

### ISSUE THREAD

**Issue by papajda** [allegro/allegro-api#7398]
Hello, I would like to add a product using an API on a sandbox, but I'm getting an error like the one below. 

Client:106020336

`{"errors":[{"code":"ProductProposalsAccessForbiddenException","message":"Access denied.","details":null,"path":"productSet[0].product","userMessage":"Nedostupné."}]}`

I try activate sales https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta but i can't simulate payment. Can you activate it on my sandbox account?

**Comment by Lukasz-Zurek** [comment]
As I see right now - your account is regular so you should convert it to business account, using option available in [My Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta). After converting this account, please configure your payouts [right here](https://allegro.pl.allegrosandbox.pl/myaccount/newpayments_payout.php?source=system) and use our payment simulator. You won't have to make a real payment.

**Comment by papajda** [comment]
When I fill in the payouts and click the button, nothing happens. No error, no message.
I fill in the account information with false data

**Comment by papajda** [comment]
I finally succeeded. What else is needed?

**Comment by Lukasz-Zurek** [comment]
@papajda I have just activated and verified your test account.

**Comment by papajda** [comment]
@Lukasz-Zurek Thank you
