### ISSUE TITLE
Weryfikacja punktów odbioru

### ISSUE THREAD

**Issue by KrzysztofOrdersoft** [allegro/allegro-api#7399]
Dzień dobry,

Próbujemy nadać przesyłkę "AllegroPunktUPS" otrzymujemy jednak komunikat:
  "code": "VALIDATION_ERROR",
  "message": "Sender pickup point must be different than receiver point.",
  "path": "receiver.pointId",
  "userMessage": "Punkt nadania musi różnić się od punktu odbioru"

PickupPoint uzupełniamy w sekcji "pickup" oraz "receiver" tą samą wartością tj. "pointId":"U96261439"

Czym może być spowodowany błąd walidacji?

Pozdrawiam,
Krzysztof Bukowski

**Comment by Lukasz-Zurek** [comment]
@KrzysztofOrdersoft Prześlij proszę trace-id, lub commandId, a zweryfikuję ten konkretny przypadek.

**Comment by KrzysztofOrdersoft** [comment]
Niestety nie zalogowaliśmy ID response. Wprowadziliśmy już logowanie ale tego identyfikatora nie odzyskamy.

**Comment by Lukasz-Zurek** [comment]
@KrzysztofOrdersoft Z samego komunikatu wynika, że jako punkt nadania przesyłki przekazujesz ten sam, co w przypadku punktu odbioru dla Klienta - a powinien być inny. W tym konkretnym przypadku chciałem się upewnić co do konkretnej, przekazywanej w requeście usługi dostawy.

**Comment by Lukasz-Zurek** [comment]
W tym konkretnym przypadku problem dotyczy pola **pickup.pointId**, w którym punkt nadania powinien się różnić od tego, którego przekazujesz w polu **receiver.pointId**.

Ponadto otrzymujesz również błąd `Podane wymiary przesyłki przekraczają maksymalną wagę gabarytową.`

**Comment by KrzysztofOrdersoft** [comment]
Czy w przypadku odbioru przez kuriera pickup.pointId może nie być uzupełniany?

**Comment by Lukasz-Zurek** [comment]
@KrzysztofOrdersoft Tak, możesz je pominąć.
