### ISSUE TITLE
Multipaczki - tworzenie przez API WzA

### ISSUE THREAD

**Issue by pietruszysko** [allegro/allegro-api#7400]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Czy istnieje możliwość tworzenia "multipaczek" przez API WzA ?
W szczególności dla kurierów 
Allegro Kurier DHL 
Allegro Odbiór w Punkcie DHL
Allegro One Box
Allegro One Punkt
Allegro Kurier Pocztex
Allegro Odbiór w Punkcie Pocztex
Allegro Automat Pocztex

Czy jedynym sposobem jest stworzenie każdej paczki oddzielnie i przypisanie do danego "zamówienia" (poprzez unikalny e-mail zamówienia)?

**Comment by Lukasz-Zurek** [comment]
Usługa tzw. wielopaczki dostępna jest tylko w DPD.

**Comment by pietruszysko** [comment]
Dziękuje. A czy istnieje sposób aby po nr_zamówienia_allegro wyciągnąć wszystkie packageId przypisane do tego zamówienia?

**Comment by Lukasz-Zurek** [comment]
Niestety nie mamy takiej funkcjonalności w naszym API.

**Comment by Lukasz-Zurek** [comment]
@pietruszysko Dodam, że mamy taką funkcjonalność jak [GET /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation#operation/getOrderShipmentsUsingGET), za pomocą której pobierzesz dodane do zamówień numery listów przewozowych (zwracamy je w polu **shipments.waybill**). Informacje te zwracamy również w polu **items.waybill**, wtedy, gdy skorzystasz z [GET /parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/getParcelCreationStatus) do pobierania szczegółowych informacji dotyczących utworzonej paczki.

**Comment by pietruszysko** [comment]
Hmm, a czy posiadając waybill mogę ponownie wygenerować/pobrać etykietę?

**Comment by Lukasz-Zurek** [comment]
Nie, do utworzenia etykiety potrzebne jest m.in. **parcelId**. Więcej informacji znajdziesz [tutaj](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-etykiete-na-paczke).

**Comment by Lukasz-Zurek** [comment]
Nie planujemy wdrożenia takiego endpointu. Natomiast jeśli chodzi o wspomnianą lukę - nie odnotowaliśmy problemów u naszych Partnerów w zakresie integracji z usługą "Wysyłam z Allegro" czy też problemów stricte dotyczących tworzenia paczek. 

Dodam, że w naszym API możesz anulować utworzoną paczkę - jeśli np. posiada ona błędne dane, itp. Zrobisz to za pomocą [PUT /parcel-management/parcel-cancel-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/cancelParcel). Aczkolwiek nie możesz już anulować paczki odebranej przez kuriera lub nadanej w paczkomacie.
