### ISSUE TITLE
{"code":"VALIDATION_ERROR","message":"must not be blank"}

### ISSUE THREAD

**Issue by mathiasdeknudt** [allegro/allegro-api#7401]
Dear,

We use effectconnect for integration with Allegro. One of the things we are currently trying to do, is syncing our first products from effectconnect to Allegro.

We will however receive the following error in effectconnect while trying: '{"code":"VALIDATION_ERROR","message":"must not be blank"} '

I have contacted the support team of effectconnect, and they have no idea why it is not working and asked me to contact you, to see if you can see something from your side?

Could you please help me to check?

Thank you in advance.

Kind regards,

Mathias

**Comment by AureliuszBrussy** [comment]
Please, read #7332 - there we explain the issue and resolution, which probably applies to your problem.

**Comment by mathiasdeknudt** [comment]
Dear, thank you for your feedback. we however receive another error now in effectconnect,  more precisely: {"code":"VALIDATION_ERROR","message":"Missing ending tag for "br""}

I used some <b>, </b>, <br> & </br> tags before in my description, but I have removed them, so I am curious why I am getting above error?

Thank you in advance

**Comment by AureliuszBrussy** [comment]
The error message suggests that somewhere in the description you used the html <br> tag and did not close it with the </br> tag. Check the correctness of the description - whether it complies with [our guidelines](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#own-images-and-description). Without a sample request, I will not be able to help you more.

**Comment by mathiasdeknudt** [comment]
I think I found the reason, but now I am getting another error: '{"code":"VALIDATION_ERROR","message":"Invalid HTML subset"}.'.
Any idea what this could cause?

Thank you

**Comment by AureliuszBrussy** [comment]
You have some error in html tags - it's possible that you are using a forbidden tag, or nesting some tag in a way we don't allow. Make sure your description complies with [our guidelines](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#own-images-and-description).

**Comment by AureliuszBrussy** [comment]
Without seeing the full request, I can only guess, while from the error code, I can deduce that the proposed product already exists in our Product Catalog - we returned its id in the Location header. When listing, you should just use the product with the id we indicated.

**Comment by mathiasdeknudt** [comment]
> Without seeing the full request, I can only guess, while from the error code, I can deduce that the proposed product already exists in our Product Catalog - we returned its id in the Location header. When listing, you should just use the product with the id we indicated.

Dear, we work together with effectconnect on this matter. They howe

**Comment by mathiasdeknudt** [comment]
> You have some error in html tags - it's possible that you are using a forbidden tag, or nesting some tag in a way we don't allow. Make sure your description complies with [our guidelines](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#own-images-and-description).

Just to be clear, is it mandatory to use html tags in your description? If I understand well, that would mean that all text should be within html tags, correct? Thank you

**Comment by AureliuszBrussy** [comment]
@mathiasdeknudt yes, you are correct, you need to use html tags. 

You can use only the following HTML tags:
- h1 - title
- h2 - subtitle
- p - paragraph
- ul - unordered (bulleted) list
- ol - ordered list
- li - list item
- b - bold

You can use < b > < /b > tags inside:
- < p > < /p > - paragraph
- < ul > < /ul > - unordered (bulleted) list
- < ol > < /ol > - ordered list

And < p > < /p > tags inside:
- < ul > < /ul > - unordered (bulleted) list
- < ol > < /ol > - ordered list

**Comment by mathiasdeknudt** [comment]
Dear, could you please help me with below error?

{"code":"ImpliedWarrantyNotFoundException","message":"Unprocessable Entity"}

What can be the reason that I receive this error and how can I solve it?

Thank you in advance.

**Comment by AureliuszBrussy** [comment]
"ImpliedWarrantyNotFoundException" means that you are trying to use an implied warranty that does not exist on the account. Make sure you enter the correct name or id when creating the offer.
