### ISSUE TITLE
Tworzenie paczki, a podjazd kuriera

### ISSUE THREAD

**Issue by MateuszChodyraApilo** [allegro/allegro-api#7403]
Dzień dobry,

Chciałbym się dowiedzieć jak zapobiec zamówienia usługi podjazdu kuriera w poniższym endpoincie:
https://developer.allegro.pl/documentation#operation/createNewParcel
PUT https://api.{environment}/parcel-management/parcel-create-commands/{commandId}

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Jeśli chodzi o zamawianie podjazdu kuriera/odbioru paczek przez kuriera - mamy do tego dedykowany zasób: [PUT /parcel-management/parcel-pickup-request-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/requestParcelPickup). Więcej informacji na ten temat znajdziesz [tutaj](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-zamowic-odbior-paczek-przez-kuriera). Jeśli natomiast posiadasz stałe zlecenie podjazdu kuriera, wystarczy, że nie będziesz korzystał z tego zasobu.
