### ISSUE TITLE
Błąd formatu numeru telefonu.

### ISSUE THREAD

**Issue by KrzysztofOrdersoft** [allegro/allegro-api#7404]
Dostajemy komunikat dot. błędnego formatu numeru telefonu wysyłamy w formacie 48 + 9 cyfr. Identyfikator zapytania generującego wysyłkę to : ce5e99d1-4b7a-42c3-90b4-9b0a24cf3893

**Comment by AureliuszBrussy** [comment]
Sprawdziłem przesyłkę utworzoną pod przesłanym uuid (ce5e99d1-4b7a-42c3-90b4-9b0a24cf3893) - widzę tam komunikat błędu dot. przekroczenia wymiarów paczki, a nie taki dotyczący numeru telefonu.

**Comment by KrzysztofOrdersoft** [comment]
Przepraszam właściwe id to :491fe6d5-224d-4c63-a97a-bee84c3d0734

**Comment by AureliuszBrussy** [comment]
Wyślij cały numer telefonu wraz z "+" na początku lub całkowicie bez numeru kierunkowego.
