### ISSUE TITLE
Błąd wystawiania nowej aukcji

### ISSUE THREAD

**Issue by bartlomiejmytnik-is** [allegro/allegro-api#7407]
Dzień dobry, proszę o pomoc mam błąd wystawiania aukcji i nie wiem w czym szukać problemu:

trace-id:f9c772df8f933f02
Wysyłane na PUT /sale/offers

Sprawdzałem Jsona który wysyłam w validatorze - jest ok

Błąd jaki otrzymuje - +"code": "ValidationError.HttpMessageNotReadableException"

Środowisko sandbox

Dodam jeszcze, że mimo tego błędu, szkic poprawnie jest tworzony.

Pozdarwiam

**Comment by AureliuszBrussy** [comment]
Z naszych logów wynika, że dla podanego trace-id odpowiedzieliśmy statusem 200 i nie zwróciliśmy błędu o którym wspomniałeś. Czy to na pewno właściwe trace-id? 

Dodam, że widzę, że korzystasz z _POST /sale/offers_. Rozważ rezygnację z tego endpointu, ponieważ jest on oznaczony jak deprecated i zostanie wyłączony wraz z początkiem 2024. Zamiast niego, zacznij korzystać z [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers). Więcej o tym przeczytasz w [naszym newsie](https://developer.allegro.pl/news/na-poczatku-2024-roku-wylaczymy-zasoby-sale-offers-sluzace-do-tworzenia-i-edycji-ofert-BvqK3XOaEcW).

**Comment by bartlomiejmytnik-is** [comment]
Zrobilem jeszcze raz dla nowej aukcji:

"PUT sale/offers/7714906360 || trace-id:fba331cbbd8e33dd"

Proszę o sprawdzenie tego trace-id

**Comment by AureliuszBrussy** [comment]
Wygląda na to, że popełniasz jakiś błąd składniowy w body swojego requestu. Prześlij proszę całe body (cały json). Spróbuję wyłapać błąd.

**Comment by bartlomiejmytnik-is** [comment]
[request_allegro.txt](https://github.com/allegro/allegro-api/files/12169714/request_allegro.txt)

wrzuciłem jako plik, żeby tutaj nie robić zbytniej sciany tekstu :)

**Comment by AureliuszBrussy** [comment]
Pole **publication.marketplaces.additional** to tablica, zamień `{}` na `[]`.

**Comment by bartlomiejmytnik-is** [comment]
Dzięki za pomoc, sprawdze to :)

**Comment by bartlomiejmytnik-is** [comment]
To była ta kwestia, dzięki za pomoc, temat można zamknąć.
