### ISSUE TITLE
Aktywacaj konta 

### ISSUE THREAD

**Issue by KrzysztofOrdersoft** [allegro/allegro-api#7408]
Dzień dobry,

Czyt istnieje możliwość aktywacji konta ordTest na allegro.pl.allegrosandbox.pl?
obecnie przy próbie wystawienia oferty otrzymuję komunikat "Aby aktywować sprzedaż zweryfikuj konto."

Pozdrawiam,
Krzysztof

**Comment by Lukasz-Zurek** [comment]
Tak, już je aktywowałem i zweryfikowałem.
