### ISSUE TITLE
Pytanie - wielokrotne użycie tych samych zdjęć

### ISSUE THREAD

**Issue by imper86** [allegro/allegro-api#741]
Witam,

Takie szybkie pytanko - czy jedno zdjęcie wrzucone za pomocą REST api (w sensie link do tego zdjęcia) można wykorzystać na wielu różnych aukcjach? Jeżeli tak to czy można użyć na aukcjach na innym koncie allegro?

Z góry dzięki za informację

**Comment by PawelTaberski** [comment]
Tak, takie zdjęcie możesz użyć w wielu ofertach nie tylko na danym koncie.

**Comment by imper86** [comment]
dzięki, wypróbuję :)
