### ISSUE TITLE
Etykieta wysyłkowa UPS dla usługi AllegroOneBox.

### ISSUE THREAD

**Issue by KrzysztofOrdersoft** [allegro/allegro-api#7410]
Dzień dobry,

Wysłaliśmy request do usługi Wysyłam z Allegro z wybranym serwisem o id: 0aafb43c-e66a-46ec-9cc4-29bb39ebb483 (AllegroOneBox)
Otrzymaliśmy jednak etykietę UPS kurier. Id zamówienia to: 5fefc500-2b93-11ee-87df-63c13082cc47  
Proszę o weryfikację.

Pozdrawiam,
Krzysztof Bukowski

**Comment by Lukasz-Zurek** [comment]
Przesyłki Allegro One Box są realizowane przez UPS. Prześlij proszę zrzut ekranu z etykietą (oczywiście z zamazanymi danymi wrażliwymi). Potwierdzę, czy etykieta się zgadza.

**Comment by KrzysztofOrdersoft** [comment]
![MicrosoftTeams-image (15)](https://github.com/allegro/allegro-api/assets/140401209/118c7792-0601-4533-a4e4-ed75def2028b)

**Comment by Lukasz-Zurek** [comment]
@KrzysztofOrdersoft Etykieta jest w tej sytuacji jak najbardziej prawidłowa.
