### ISSUE TITLE
GET /payments/payment-operations DEDUCTION_CHARGE szczegóły

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#7411]
Po wprowadzeniu potrącania prowizji z salda metoda GET /payments/payment-operations zaczęła zwracać operacje typu DEDUCTION_CHARGE, które zawierają pole deduction.id.

Czy istnieje zasób, który pozwala określić jak na podstawie np. deduction.id z jakich prowizji, zwrotów prowizji, wyrównań itd. składa się dana operacja DEDUCTION_CHARGE?

**Comment by Lukasz-Zurek** [comment]
Nie, nie mamy tego typu zasobu w API. Zachęcam Cię do przekazania sugestii w [dedykowanym do tego miejscu](https://github.com/allegro/allegro-api/discussions), na którą głosy będą mogli oddać również inni użytkownicy.

**Comment by martacronic** [comment]
Ok, jak ktoś po wprowadzeniu potrąceń z salda również potrzebuje więcej danych to zapraszam https://github.com/allegro/allegro-api/discussions/7413
