### ISSUE TITLE
/sale/product-offers API Errors

### ISSUE THREAD

**Issue by dmsmatrix** [allegro/allegro-api#7412]
Hi,

I have given two requests for which I got errors. These errors are related due to change or removal of category or property in Allegro. I tried to find these category & property using **Get planned changes in category parameters (/sale/category-parameters-scheduled-changes)** API, but I didn't find ids for these category (iD: 1471) and property (iD: 129970) in its API response.

Please let me know the reason for not getting these category & property ids in Get planned changes in category parameters API. Due to this lots of my products getting API error responses.

**REQUEST 1:**
_endpoint_ : POST https://api.allegro.pl/sale/product-offers

_request_ : {"parameters":[{"id":"11323","name":"Condition","valuesIds":["11323_1"]}],"productSet":[{"product":{"parameters":[{"id":"233005","name":"Overall width","values":["36"]},{"id":"129970","name":"Brand","valuesIds":["129970_18"],"values":["bez marki"]},{"id":"18114","name":"Type","valuesIds":["18114_2"]},{"id":"225693","name":"EAN (GTIN)","values":["6466211273512"]}],"name":"Creative Led Digital Clock","category":{"id":"541"},"images":["https://dmsmatrix.net/direct/images/64ad2493277b953ef332ca22_750x600.jpg"]},"quantity":{"value":1}}],"name":"Creative Led Digital Clock","description":{"sections":[{"items":[{"type":"TEXT","content":"<p>This is a self-powered emergency radio that you and your family can rely on at any time and in all weather conditions.WATERPROOF: Very compact, lightweight and easy to carry, a good lifesaver when the phone is off or in a thunderstorm.Type: AM/FMStyle: wearableFunction: flashlight AM: 525 kHz to 1710 kHzFM: 88MHz to 108MHzLithium battery capacity: 1000 mAhWeather band: 162.40 to 162.55 MHzTorch: 3-LED flashlightMaterial: ABSDimensions: 128mm x 60mm x 50mm LED Lifetime: 100,000 HoursPackage Contents:1 x Crank Radio1x USB Charging Cable 1 * User</p>"}]}]},"category":{"id":"541"},"images":["https://dmsmatrix.net/direct/images/64ad2493277b953ef332ca22_750x600.jpg"],"publication":{"status":"ACTIVE","republish":true},"sellingMode":{"price":{"amount":"117.99","currency":"PLN"},"format":"BUY_NOW"},"delivery":{"shippingRates":{"id":"acf8ac0f-3087-4f60-893f-ff4564ce8329","name":"YCPL"}},"stock":{"available":0,"unit":"UNIT"},"external":{"id":"6466211273512"}}

_headers_ : {"expires":" 0","cache-control":" no-cache, no-store, max-age=0, must-revalidate","x-xss-protection":" 1; mode=block","pragma":" no-cache","x-frame-options":" DENY","trace-id":" 249f2e20b847ae9c","date":" Fri, 14 Jul 2023 19:21:34 GMT","x-content-type-options":" nosniff","strict-transport-security":" max-age=31536000 ; includeSubDomains","content-type":" application/json; charset=UTF-8","content-length":" 305"}

_response_ : {"errors":[{"code":"InvalidDictionaryParameter","message":"Unprocessable Entity","details":null,"path":"productSet[0].product.parameters","userMessage":"The entered dictionary value ID `129970_18` in the parameter with the ID `129970` indicates a different value than that added in the `values` field."}]}

**REQUEST 2:**
_endpoint_ : "POST https://api.allegro.pl/sale/product-offers

_request_ : {"afterSalesServices":{"impliedWarranty":{"id":"31750643-2418-41a6-ae1c-7325836d4a3f","name":"Tousu"},"returnPolicy":{"id":"f2090ff2-e66f-4379-8531-17d584b4cb9a","name":"Tuihuo"}},"delivery":{"handlingTime":"P3D","shippingRates":{"id":"326a3ebd-c83b-4bbb-b4db-869c851048e8","name":"sunyou"}},"publication":{"duration":null,"status":"ACTIVE","republish":true},"payments":{"invoice":"NO_INVOICE"},"productSet":[{"product":{"parameters":[{"id":"225693","name":"EAN (GTIN)","values":["885107663569"]}],"name":"Steel Toe Cap Safety Shoes - 39 -grey","category":{"id":"1471"},"images":["https://dmsmatrix.net/direct/images/648aca65b604a10320201f70_750x600.jpg"]},"quantity":{"value":1}}],"name":"Steel Toe Cap Safety Shoes - 39 -grey","description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Rubber soleLightweight &amp; Breathable: The safety shoes pick a breathable mesh fabric upper, offering super ventilation experience to keep your feet dry and cool all day. And the lightweight material adopt will keep you remain relax after fatigue job.Puncture Resistant Kevlar Sole: Compared to the steel midsole, these steel toe sneakers are made of the Kevlar that protect your feet from being punctured by sharp objects like nails or steel bar to bring you a safer but more soft fit.Standard Steel Toe Cap: These construction work shoes are capable of absorbing 20013 J forces with the protective standard steel toe cap. While the rubber-protected edge of steel toe cap can keep the upper from damage for extra durability.Anti-Skid Rubber Sole: Built with rubber outsole, the work shoes share deep groove to provide great traction even on slippery surface. And they are flexible and soft that can be bent arbitrarily for all day comfort.Widely Used: Coming with a casual sneakers appearance, this series of safety footwear is great for those working on electric power industry, forging, auto manufacturing, construction and machine manufacturing.</p>"}]}]},"category":{"id":"1471"},"images":["https://dmsmatrix.net/direct/images/648aca65b604a10320201f70_750x600.jpg"],"sellingMode":{"price":{"amount":"163.02","currency":"PLN"},"format":"BUY_NOW"},"stock":{"available":200,"unit":"UNIT"},"external":{"id":"885107663569"}}

_headers_ : {"expires":" 0","cache-control":" no-cache, no-store, max-age=0, must-revalidate","x-xss-protection":" 1; mode=block","pragma":" no-cache","x-frame-options":" DENY","trace-id":" f0dcf1b93dd72ff1","date":" Thu, 15 Jun 2023 17:43:36 GMT","x-content-type-options":" nosniff","strict-transport-security":" max-age=31536000 ; includeSubDomains","content-type":" application/json; charset=UTF-8","content-length":" 172"}

_response_ : {"errors":[{"code":"ProductValidationException","message":"An error has occurred","details":null,"path":"productSet[0].product","userMessage":"Nie znaleziono kategorii."}]}

Thanks in advance

**Comment by AureliuszBrussy** [comment]
[GET /sale/category-parameters-scheduled-changes](https://developer.allegro.pl/documentation#operation/getCategoryParametersScheduledChangesUsingGET_1) returns only information about the change in the requirement of the parameters. 

In the first request, you are trying to use an ambiguous value (_129970_18_) but the value that you trying to pass in value field ("_bez marki_") does exist in this category. Try to use _129970_853438_ value in **valueIds** array. 

In the second case - category 1471 does not exist right now. You should update your taxonomy ([GET /sale/categories](https://developer.allegro.pl/documentation#operation/getCategoriesUsingGET)).

**Comment by dmsmatrix** [comment]
I revise parameters according to GET /sale/category-parameters-scheduled-changes API. But despite of doing that, I get error responses for any of product, then after checking by error response only I come to know that I need to change parameter valueIds array. That is strange actually. You can see some more requests and error responses for the same, where these parameters and respective category is not there in GET /sale/category-parameters-scheduled-changes API, but still Allegro gives me its error in API response:

REQUEST 1:
parameter ids: 129877, 129876 & category id: 45669
endpoint : POST https://api.allegro.pl/sale/product-offers
request : {"afterSalesServices":{"impliedWarranty":{"id":"31750643-2418-41a6-ae1c-7325836d4a3f","name":"Tousu"},"returnPolicy":{"id":"f2090ff2-e66f-4379-8531-17d584b4cb9a","name":"Tuihuo"}},"delivery":{"handlingTime":"P3D","shippingRates":{"id":"326a3ebd-c83b-4bbb-b4db-869c851048e8","name":"sunyou"}},"publication":{"duration":null,"status":"ACTIVE","republish":true},"payments":{"invoice":"NO_INVOICE"},"parameters":[{"id":"11323","name":"Condition","valuesIds":["11323_1"]}],"productSet":[{"product":{"parameters":[{"id":"129369","name":"Brand","valuesIds":["129369_1681660"]},{"id":"129767","name":"Waterproof Product","valuesIds":["129767_1"]},{"id":"452","name":"SPF","valuesIds":["452_7"]},{"id":"129877","name":"Type","valuesIds":["129877_32"]},{"id":"129876","name":"Features","valuesIds":["129876_8"]},{"id":"225693","name":"EAN (GTIN)","values":["6938611751230"]}],"name":"Vitamin C Facial Powder","category":{"id":"45669"},"images":["https://dmsmatrix.net/direct/images/646db7b240e8194e8c1a83cd_750x600.jpg"]},"quantity":{"value":1}}],"name":"Vitamin C Facial Powder","description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Specification: Normal specification Color: as shown in the figure Shelf life: 3 years Quantity: two packs Applicable skin type: suitable for a variety of skin types Note: 1. If you feel unwell, stop using it immediately. 2. Please keep this product out of the reach of children. 3. Avoid storing light at room temperature. Package includes: 3 set( 2pcs VC POWDER)</p>"}]}]},"category":{"id":"45669"},"images":["https://dmsmatrix.net/direct/images/646db7b240e8194e8c1a83cd_750x600.jpg"],"sellingMode":{"price":{"amount":"53.66","currency":"PLN"},"format":"BUY_NOW"},"stock":{"available":239,"unit":"UNIT"},"external":{"id":"6938611751230"}}
headers : {"expires":" 0","cache-control":" no-cache, no-store, max-age=0, must-revalidate","x-xss-protection":" 1; mode=block","pragma":" no-cache","x-frame-options":" DENY","trace-id":" b9ca6e2ff130f757","date":" Wed, 24 May 2023 11:55:02 GMT","x-content-type-options":" nosniff","strict-transport-security":" max-age=31536000 ; includeSubDomains","content-type":" application/json; charset=UTF-8","content-length":" 1016"}
response : {"errors":[{"code":"ProductValidationException","message":"Product has invalid values [ValidatedParameter[parameter=SimpleParameter{id='129877', values=[ParameterValue{id='129877_32', value='inny'}]}, name=Rodzaj, validationErrors=[ValidationError{value='inny', valueId='129877_32', errorType=VALUE_AMBIGUOUS, illegalCharacters='null'}], isIdentifyingParameter=false, isParameterUsedInRuleSet=false, isRequiredParameter=true], ValidatedParameter[parameter=SimpleParameter{id='129876', values=[ParameterValue{id='129876_8', value='inne'}]}, name=Właściwości, validationErrors=[ValidationError{value='inne', valueId='129876_8', errorType=VALUE_AMBIGUOUS, illegalCharacters='null'}], isIdentifyingParameter=false, isParameterUsedInRuleSet=true, isRequiredParameter=true]] in category: 45669","details":null,"path":"productSet[0].product","userMessage":"Nieprawidłowe wartości parametrów: [parameter = Rodzaj [ Wartość niejednoznaczna - inny] , parameter = Właściwości [ Wartość niejednoznaczna - inne]]"}]}

REQUEST 2:
parameter id: 247945 & category id: 259810
endpoint : POST https://api.allegro.pl/sale/product-offers
request : {"parameters":[{"id":"11323","name":"Condition","valuesIds":["11323_1"]}],"productSet":[{"product":{"parameters":[{"id":"220853","name":"Collection","values":["String"]},{"id":"224017","name":"Manufacturer's code","values":["ALYC-23329-5"]},{"id":"248811","name":"Brand","valuesIds":["248811_950468"],"values":["GelldG"]},{"id":"24231","name":"Length/Height","values":["16"]},{"id":"24232","name":"Thread type","valuesIds":["24232_278533"]},{"id":"11484","name":"Color","valuesIds":["11484_2"]},{"id":"209566","name":"Power Supply","valuesIds":["209566_4"]},{"id":"225693","name":"EAN (GTIN)","values":["6466211273673"]}],"name":"Led Children's Desk Lamp","category":{"id":"259810"},"images":["https://dmsmatrix.net/direct/images/64ad2493277b953ef332ca26_750x600.jpg"]},"quantity":{"value":1}}],"name":"Led Children's Desk Lamp","description":{"sections":[{"items":[{"type":"TEXT","content":"<p>LED light source to protect your eyes: Clamp lamp for bed White power cord with LED light, the LED desk lamp can emit a natural, flicker-free light that does not hurt or strain your eyes. Perfect for reading, study, work, draw, sleep and more. Reduce eye strain and protect your eyes3 Brightness can be adjusted to best suit your needs. Single press to select color temperature, long press to adjust brightness. : The free-floating fluorescent lamp can be rotated 360 for the best viewing angle.With the non-slip silicone pad of the base, it can also be placed stablySnap-on design with non-slip mount or base: the clip can be extended to a maximum width of 6 cm .You can install this reading light in many places, such as books, desks, headboards, shelves, bookshelves, wardrobes, music stands, pianos and computers. You can also put it on the table as an ordinary desk lampWidely used: The LED clip on the USB reading lamp provides a more uniform and wider uniform diffused lighting area than other LED reading lamps, ideal for lighting dorms, offices, bedrooms, children&apos;s rooms, reading, studying, etc.Size: 420x120mmVoltage: 36VLight color: white lightLight source type: 16 beads for LED lampControl method: touch controlMounting method: clippackage includes1 x desk lamp 1x USB charging cable</p>"}]}]},"category":{"id":"259810"},"images":["https://dmsmatrix.net/direct/images/64ad2493277b953ef332ca26_750x600.jpg"],"publication":{"status":"ACTIVE","republish":true},"sellingMode":{"price":{"amount":"37.99","currency":"PLN"},"format":"BUY_NOW"},"delivery":{"shippingRates":{"id":"acf8ac0f-3087-4f60-893f-ff4564ce8329","name":"YCPL"}},"stock":{"available":0,"unit":"UNIT"},"external":{"id":"6466211273673"}}
headers : {"expires":" 0","cache-control":" no-cache, no-store, max-age=0, must-revalidate","x-xss-protection":" 1; mode=block","pragma":" no-cache","x-frame-options":" DENY","trace-id":" d2bafa2359d64038","date":" Fri, 14 Jul 2023 19:21:41 GMT","x-content-type-options":" nosniff","strict-transport-security":" max-age=31536000 ; includeSubDomains","content-type":" application/json; charset=UTF-8","content-length":" 389"}
response : {"errors":[{"code":"ProductValidationException","message":"Unable to create product without proper values in all required parameters: [Klasa efektywności energetycznej] in category: 259810","details":null,"path":"productSet[0].product","userMessage":"Nie można stworzyć produktu bez podania poprawnych wartości wszystkich parametrów wymaganych: [Klasa efektywności energetycznej]"}]}

**Comment by AureliuszBrussy** [comment]
As I wrote before [GET /sale/category-parameters-scheduled-changes](https://developer.allegro.pl/documentation#operation/getCategoryParametersScheduledChangesUsingGET_1) returns info only about the requirement changes, not all changes in parameters. You can also get future changes in the category tree by using [GET /sale/category-events](https://developer.allegro.pl/documentation#operation/getCategoryEventsUsingGET_1).

In the first request, when you are using an ambiguous value id (129877_32=inny), you should also pass your own value in the values[] array.

In the second request - you should also fill up the required parameter (247945).

PS. 
If you want to receive error messages in English, use the "Accept-Language" header and pass the "en-US" value in it. In addition, if you are sending product data in English, pass an additional "language" field with the value "en-US" in the payload.

**Comment by dmsmatrix** [comment]
Sorry but I didn't get this **_returns info only about the requirement changes, not all changes in parameters_**.  What do you mean by **requirement changes** whereas on other hand **changes in parameters**?

I can see from GET /sale/category-parameters-scheduled-changes API, sometimes parameter values array,

**Comment by AureliuszBrussy** [comment]
It will only return information about the fact that the parameter will soon become a required parameter in the category. Without its filling, it will not be possible to edit/list the offer.

**Comment by dmsmatrix** [comment]
Sorry but I didn't get this returns info only about the requirement changes, not all changes in parameters. What do you mean by requirement changes whereas on other hand changes in parameters? Could you please explain me in details as I am getting lots of errors for values array or required, requiredForProduct or options changes for parameters change for parameters?

I can see from GET /sale/category-parameters-scheduled-changes API, sometimes values array or required, requiredForProduct or options changes for parameters.

**Comment by dmsmatrix** [comment]
Please reply

**Comment by AureliuszBrussy** [comment]
You should regularly update your taxonomy by using [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2). The more often, the better.

**Comment by dmsmatrix** [comment]
Thanks for the information

**Comment by dmsmatrix** [comment]
Its not feasible to check and update 3,85,564 parameters of 25,785 categories regularly (lets say weekly). It will also increase API hits at your end and also our clients will also not be happy as due to frequent changes in parameters they have to update their products frequently.

**Comment by AureliuszBrussy** [comment]
There is no alternative solution. Values in dictionary-type parameters may change daily, new parameters may also appear from time to time.

**Comment by dmsmatrix** [comment]
Yedzavya
