### ISSUE TITLE
Blokada zmiany kategorii oferty

### ISSUE THREAD

**Issue by cyfranT** [allegro/allegro-api#7414]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Przy próbie aktualizacji kategorii oferty z użyciem PATCH /sale/product-offers/auction-id, na id kategorii które występuje na liście kategorii dozwolonych dla powiązanego produktu, otrzymujemy zwrotnie:
`"details":"IllegalOfferUpdateException.IllegalChangeCategoryId","path":"category","userMessage":"You cannot change the category after 12 hours from listing."`

trace-id 60ece28de943138

Proszę o weryfikację, dlaczego nie możemy zmienić kategorii.

**Comment by AureliuszBrussy** [comment]
Nie możesz zmienić kategorii oferty po 12 godzinach od wystawienia, nawet jeżeli próbujesz to zrobić w ramach zbioru kategorii podobnych. [W artykule znajdziesz szczegóły](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/jak-zmienic-szczegoly-oferty-po-jej-wystawieniu-3GBbgYX1RSn#kup-teraz).

**Comment by cyfranT** [comment]
Tylko, że spełniamy warunki dla zmiany, bo ustawiana kategoria jest zgodna z produktem:

Jeśli w ofercie jest już zakup lub minęło 12 godzin od wystawienia, **możesz zmienić kategorię na zgodną z kategorią powiązanego produktu** (poza kategoriami o nazwie Pozostałe).

**Comment by AureliuszBrussy** [comment]
Faktycznie, jest taka opcja, natomiast ten warunek dotyczy tylko kategorii głównej, nie dotyczy zbioru kategorii podobnych.
