### ISSUE TITLE
Batch update offers to set duration.republish to false

### ISSUE THREAD

**Issue by lwillems** [allegro/allegro-api#7415]
Hi

Is there a way to update the duration.republish to false using bulk request ?
We need to remove this option (set to true by mistake) on our 150K active offers and unfortunately in the batch offer edit this field does not exist.
https://developer.allegro.pl/documentation#tag/Batch-offer-modification

We would like to avoid updates one by one using PATCH because it would take a while ...

Thanks for your help

**Comment by AureliuszBrussy** [comment]
Sorry, but we do not have a bulk command for duration.republish field.

**Comment by lwillems** [comment]
> Sorry, but we do not have a bulk command for duration.republish field.

Hi @AureliuszBrussy thx for the quick reply, is there any chance allegro tech team can change this field on all active offers for us ? to avoid at least 150K requests on API.

Regards

**Comment by AureliuszBrussy** [comment]
@lwillems sorry, however, we will not perform such an operation for the user.

**Comment by lwillems** [comment]
understood, i will plan the update thx for your help
