### ISSUE TITLE
Testy automatyczne - dane mockowe

### ISSUE THREAD

**Issue by arvato-damkos** [allegro/allegro-api#7417]
Dzień dobry,

Chcemy przeprowadzać testy automatyczne samych wysyłek paczek przez wasze API (GET/PUT parcel-management/parcel-create-commands oraz parcel-management/parcels). Produkcyjnie **wszystkie** dane wysyłkowe dostarcza nam klient, my tylko przekazujemy je dalej do waszego API. Pytanie czy jesteśmy w stanie przetestować tylko tę ścieżkę bez pełnego flow, czyli tworzenia oferty, dokonania sprzedaży itd? Czy jesteście w stanie dostarczyć nam dane (pewnie najważniejszy email), które będą przechodzić nam w testach automatycznych?

**Comment by Lukasz-Zurek** [comment]
Nie, nie mamy takiej możliwości. Aby przetestować wysyłkę paczek poprzez nasze API, konieczne jest przejście przez całe flow.
