### ISSUE TITLE
API KEYS: Client key and secret key ??? How to get those keys???

### ISSUE THREAD

**Issue by Mercury747** [allegro/allegro-api#7418]

**Comment by hahyes** [comment]
@AureliuszBrussy Co się stało z angielską dokumentacją? Chciałem ją podlinkować tutaj ale okazuje się, że nie ma już jej. Chodzi mi o ten link: https://developer.allegro.pl/en/

**Comment by AureliuszBrussy** [comment]
@hahyes wystarczy, że zmienisz język w ustawieniach:
![image](https://github.com/allegro/allegro-api/assets/68948612/e72d1c60-11a9-43a2-abde-21a8373aa19c)

@Mercury747 to get a Client ID and Client Secret - you need to register the application on [Developer Apps](https://apps.developer.allegro.pl/). You can read more about app registration and authentication in [our guide](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY).
