### ISSUE TITLE
OfferAccessDeniedException - Access denied. You are not authorized to perform operations on the indicated offer

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#7419]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy próbie wystawienia oferty za pomocą metody /sale/product-offers dostaję błąd "OfferAccessDeniedException - Access denied. You are not authorized to perform operations on the indicated offer", konto jest firmowe ale może nie jest aktywowane?

Trace-id: d905f3fa4366df03

**Comment by Lukasz-Zurek** [comment]
Posiadasz konto firmowe, które nie zostało do końca zweryfikowane. Niestety to konto było rejestrowane w 2018 roku i jest problem z jego weryfikacją. Jeśli to nie problem - załóż proszę nowe konto firmowe na sandboxie, skorzystaj z symulatora płatności w procesie ustawień wypłat, a następnie daj znać w tym wątku - pomogę przy pełnej weryfikacji i aktywacji konta.

**Comment by SlawomirMizerski** [comment]
Nowe konto firmowe założone, login: slawekm

**Comment by Lukasz-Zurek** [comment]
@SlawomirMizerski Aktywowałem i zweryfikowałem Twoje konto.

**Comment by bugproof** [comment]
@Lukasz-Zurek mam ten sam problem, 
Login: autoparts2023
Przy próbie dodania oferty api mam błąd OfferAccessDeniedException

**Comment by Lukasz-Zurek** [comment]
@bugproof Przyczyną było konto firmowe, które nie było zweryfikowane. Teraz powinno być już ok.
