### ISSUE TITLE
Oferta pozostawiona w INACTIVE

### ISSUE THREAD

**Issue by adampajak** [allegro/allegro-api#742]
Co się dzieje z ofertą jeśli, zaraz po utworzeniu, nie ustawię na niej "ACTIVATE" - a dokładniej nie zrobię tego przez kilka następnych dni?

**Comment by PawelTaberski** [comment]
Nie wiem czy dobrze zrozumiałem Twoje pytanie, ale jeśli utworzyłeś draft i go nie aktywowałeś przez kilka dni to nic się nie stanie. Obecnie drafty nie mają daty ważności i ich nie usuwamy.

**Comment by adampajak** [comment]
OK, o to mi chodziło
