### ISSUE TITLE
Identyfikator usługi Allegro One Punkt

### ISSUE THREAD

**Issue by KrzysztofOrdersoft** [allegro/allegro-api#7420]
Dzień dobry,

Proszę o informację jakie id posiada usługa Allegro One Punkt?

Pozdrawiam,
Krzysztof

**Comment by Lukasz-Zurek** [comment]
Id: **08c15d0b-9b24-4b3f-89a8-7a2b502abe55**

Listę usług dostawy sprawdzisz za pomocą [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices).
