### ISSUE TITLE
Aktywacja konta

### ISSUE THREAD

**Issue by jarekprzybyszewski** [allegro/allegro-api#7421]
Dzień dobry

czy mógłbym prosić o aktywację konta dla aplikacji asReporting na sandboxie?

Z poważaniem
Jarek

**Comment by Lukasz-Zurek** [comment]
Nie mamy takiej aplikacji na środowisku testowym. Podaj proszę login do konta na sandboxie.

**Comment by jarekprzybyszewski** [comment]
Przepraszam – ale chyba się zagalopowałem i nie utworzyłem konta.

Pozdrawiam
Jarek

Jarosław Przybyszewski
Managing Partner
M: +48 793 555 661
E: ***@***.******@***.***>
