### ISSUE TITLE
Aktywacja konta

### ISSUE THREAD

**Issue by shopyon** [allegro/allegro-api#7422]
Dzień dobry,
proszę o aktywację konta peknynabytek na allegro.pl.allegrosandbox.pl
Od kilku dni widnieje tam komunikat "We are verifying your company details" w zakładkach "Set payouts" i "Company verification".

**Comment by AureliuszBrussy** [comment]
Aktywowałem Twoje konto.

**Comment by shopyon** [comment]
Dziękuję

**Comment by shopyon** [comment]
Czy można zmodyfikować konto, aby baseMarketplace było allegro-cz?

**Comment by AureliuszBrussy** [comment]
Nie, nie jest to możliwe, zarejestruj nowe konto pod innym mailem w [allegro.cz.allegrosandbox.pl](https://allegro.cz.allegrosandbox.pl/).

**Comment by shopyon** [comment]
Proszę o aktywację konta peknynabytek_cz na allegro.cz.allegrosandbox.pl
Czy w tej wersji można utworzyć aplikację do dostępu do interfejsu API?

**Comment by AureliuszBrussy** [comment]
@shopyon aktywowałem Twoje konto. API dla każdego marketplace'u jest jedno, aplikację rejestrujesz tak samo - w Developer Apps: [prod](https://apps.developer.allegro.pl/) i [test](https://apps.developer.allegro.pl.allegrosandbox.pl/).
