### ISSUE TITLE
Wysyłam z Allegro: Allegro One (Box, Punkt) 

### ISSUE THREAD

**Issue by ZAK2828** [allegro/allegro-api#7423]
Dzień dobry,
Tworzymy bilety za pomocą programu ProstaPaczka, w konfiguracji biletu wskazujemy pole "referencja" oraz "opis paczki", w naszym przypadku absolutnie niezbędne jest, żeby pojawił się nasz numer dokumentu na etykiecie i używaliśmy tych pól do wprowadzenia takiej informacji.
Natomiast na etykietach UPS w ramach Allegro One, Box czy też Punkt, numer dokumentu, który wprowadzamy zastępowany jest jakimś wewnętrznym numerem zamówienia/przesyłki oraz stałym tekstem: "Operator: Allegro sp. z o.o.".
Poniżej przykład:
![obraz](https://github.com/allegro/allegro-api/assets/63778087/b0049fce-6916-4919-9095-443eea82e670)
Czy mogą Państwo "oddać" jedno z tych pól, żeby faktycznie przechodziła informacja, którą my wprowadzamy?
Albo dodać możliwość wprowadzania takiej informacji za pomocą innego pola?
W załączeniu przykład całej takiej etykiety.
[A0000TF9J9.pdf](https://github.com/allegro/allegro-api/files/12190836/A0000TF9J9.pdf)

**Comment by AureliuszBrussy** [comment]
Ta kwestia była już poruszana wcześniej, np. w zgłoszeniu #6423. Przykro mi, ale nie mamy na tę chwilę możliwości wprowadzenia zmian w tym temacie. W skrócie: pole ref 2 nie może zostać zmienione - wymóg prawny, i tak ograniczaliśmy zapisy, aby zmieścić wartość w tym polu. Do pola nr ref 1 nie rekomendujemy zmian, ponieważ klienci/punkty obsługi są uczeni że jest to czysty numer paczki Allegro.

**Comment by ZAK2828** [comment]
Dziękuję za odpowiedź.
> Przykro mi, ale nie mamy na tę chwilę możliwości wprowadzenia zmian w tym temacie.
Na tę chwilę, tzn. jest szansa, że toczą się jakieś rozmowy o modyfikacji tych pól?
W ostatnich dniach pojawił się wymóg, że żeby oferta była SMART wśród wysyłek do punktu musi być Allegro One, a tak kluczowy parametr jak nr referencyjny jest przez Państwa nadpisywany, przez co część sprzedawców ze względów czysto technicznych nie będzie mogło wdrożyć tej usługi.
Bardzo proszę o przekazanie jakichś uwag komuś, kto może wywrzeć nacisk na UPS czy kogokolwiek, żeby te pole "odzyskać".

**Comment by AureliuszBrussy** [comment]
@ZAK2828 zespół będzie badać, jakie mamy możliwości w kwestii prezentowania dodatkowych danych na etykiecie. Prosiłbym jednak o cierpliwość - ze względu na to, że jesteśmy w tej kwestii uzależnieni od ograniczeń przewoźnika, decyzje, które możemy podjąć, nie są wynikiem wyłącznie naszych ustaleń.
