### ISSUE TITLE
Dostę do API w kontekście operatora logistycznego sprzedawcy

### ISSUE THREAD

**Issue by kkeiichi** [allegro/allegro-api#7424]
Mam pytanie, a może raczej prośbę po podpowiedź o możliwe rozwiązania.

Najpierw nakreślę jak wygląda sytuacja i co bym chciał uzyskać.

Załóżmy, że istnieje kilka firm, które posiadają konto w serwie Allegro i w nim wystawiają oraz sprzedają towary. Nazwijmy je _Sprzedawca A_, _Sprzedawca B_, _Sprzedawca C_ itd. Wszystkie te firmy nie posiadają własnych magazynów, a korzystają z usług jednego, wspólnego operatora logistycznego (firma, nazwijmy ją, _Operator_), który na wniosek konkretnego sprzedawcy dokonuje spakowania i wysyłki towaru. Sprzedawcy nie są ze sobą w żaden sposób powiązani ponad to, że ich operatorem logistycznym jest jedna firma.

Zgodnie z niedawnymi wytycznymi Allegro, aby sprzedawcy od września zachowali prawo do używania Smarta, muszą m.in. oferować dostawę poprzez Allegro One. Jako, że w rzeczywistości to _Operator_ dokonuje wysyłek, to _Operator_ będzie musiał komunikować się z API Allegro, tworzyć przesyłkę, pobierać etykietę na paczkę i przekazywać towar przewoźnikowi. Zaznaczam, że z góry odrzucam jakiekolwiek możliwości ręcznego tworzenia paczek przez sprzedawców lub operatora w aplikacji webowej „Wysyłam z Allegro”. Takie rozwiązanie, przy obecnej ilości wysyłek jest nieakceptowalne.

I teraz, z tego co rozumiem po zapoznaniu się z dokumentacją API, rozwiązanie takiego problemu powinno wyglądać następująco:
1. _Operator_ przygotowuje moduł do własnego oprogramowania magazynowego, który będzie się komunikował z API Allegro w celu utworzenia przesyłki do zamówienia jednego ze sprzedawców i pobrania etykiety.
2. _Operator_ rejestruje oprogramowanie integrujące na https://apps.developer.allegro.pl/. _Operator_ będzie więc musiał założyć własne konto w Allegro, pomimo że nie będzie wykonywał żadnych transakcji kupna/sprzedaży. W celu obsługi przesyłek aplikacja będzie wymagała uprawnień `allegro:api:orders:read` i `allegro:api:orders:write`.
3. Sprzedawcy (_Sprzedawca A_, _Sprzedawca B_ itp.) autoryzują aplikację na własnych kontach i w ten umożliwiają jej dostęp do sposobów wysyłki skonfigurowanych na swoich kontach. Moduł operatora tym samym zyskuje możliwość generowania wysyłek w imieniu sprzedawców.

Czy jest to właściwa logika takiego rozwiązania, czy może Allegro rekomenduje inny sposób, aby rozwiązań taką współpracę sprzedawcy z operatorem logistycznym.

**Comment by Lukasz-Zurek** [comment]
Tak, jest to właściwa logika takiego rozwiązania poprzez nasze API i usługę "Wysyłam z Allegro".
