### ISSUE TITLE
Post to /sale/product-offers returns code 100

### ISSUE THREAD

**Issue by papsko** [allegro/allegro-api#7425]
Witam,

dziś podczas wystawiania ofert poprzez endpoint /sale/product-offer w pewnym procencie offert (88/833) API zwróciło kod odpowiedzi http **100**. Jako, że sytuacja taka nie jest opisana w dokumentacji (nigdy wcześniej też mi się nie zdarzyła), nie było ona uwzględniona w programie i zwrócił on informacje, że nie udało się wystawić tych aukcji. Po sprawdzeniu w allegro okazało się, że aukcje dla których zwrócony został kod 100 zostały poprawnie wystawione. 

Co oznacza kod odpowiedzi 100 i jak program wystawiający aukcje powinien się zachować w przypadku otrzymania takiego kodu?

Pozdrawiam.

Hello,

today during posting offer via /sale/product-offer/ endpoint for some fraction of offers (88/833) API returned **100** http response code. As this situation is not described in documentation, it was also not taken into account in program and it returned information that operation on these offers failed. Later, after checking in Allegro platform it turned out that acutons with response code 100 have been posted successfully. 

What does 100 response code mean and how should program behave when getting such a response code?

Regards

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę trace-id. Nie odnotowaliśmy takich odpowiedzi w naszych logach.

**Comment by papsko** [comment]
Witam,
do tej pory nie logowaliśmy w programie trace-id. 
Dodaliśmy zapis trace-id w logach. Jeżeli sytuacja znowu wystąpi wrócimy do tematu.

**Comment by Lukasz-Zurek** [comment]
@papsko Ok, dziękuję.
