### ISSUE TITLE
Brak możliwości generowania paczek dla zamówień z kont powiązanych.

### ISSUE THREAD

**Issue by KrzysztofOrdersoft** [allegro/allegro-api#7426]
Dzień dobry,

Próbujemy nadać przesyłkę  z powiązanego konta allegro - w panelu WWW transakcje są widoczne i można wykonywać na nich działania będąc zalogowanym na koncie powiązanym. Korzystając z Api otrzymujemy jednak błąd (w zrzucie).
W tym temacie dostaliśmy odpowiedź w zgłoszeniu nr "34793703" wobec tego wysłaliśmy już klika paczek powiązanych bezpośrednio z kontem na które jesteśmy zalogowani. Proszę o informację jak można rozwiązać ten problem. 

Pozdrawiam,
Krzysztof

![MicrosoftTeams-image (16)](https://github.com/allegro/allegro-api/assets/140401209/2a0c7736-7bb2-4cf7-b2ed-d91e1c6fb297)

**Comment by Lukasz-Zurek** [comment]
Wszystko wskazuje na to, że próbujesz nadać przesyłkę do zamówienia innego Sprzedającego. Sprawdziłem logi i błąd leży po stronie adresu e-mail w polu **receiver.email** - musi być zgodny z zamówieniem, które otrzymałeś jako Sprzedający. Może to być od tego samego Klienta, ale w przypadku różnych zamówień, adres ten różni się identyfikatorem zamówienia w mailu. Więcej o tym przeczytasz w naszej [Pomocy](https://allegro.pl/pomoc/dla-sprzedajacych/kontakt-z-klientem/jak-wyswietlamy-adresy-e-mail-w-korespondencji-w-ramach-allegro-5VZxXd8vzSL).

**Comment by Lukasz-Zurek** [comment]
Tak. Paczkę próbujesz nadać jako Sprzedawca na koncie "A", a zamówienie Klient złożył u Sprzedawcy na koncie "B". Po prostu adres e-mail z zaszytym w nim identyfikatorem zamówienia, mówi nam, że to zamówienie należy do innego Sprzedawcy.
