### ISSUE TITLE
Edytowanie oferty przez API za pomocą metody PATCH - parametry

### ISSUE THREAD

**Issue by Foveros1** [allegro/allegro-api#7427]
Dzień dobry,

Próbuję zedytować parametry w istniejącej ofercie za pomocą metody PATCH, zgodnie z tą dokumentacją:

https://developer.allegro.pl/documentation/#operation/editProductOffers

W odpowiedzi na request otrzymuję błąd o treści:

"Parametr `15851:Płeć` nie powinien być wskazany w sekcji `offer`."

Podobny błąd dostaję dla praktycznie wszystkich parametrów w ofercie. 

Domyślam się, że błąd ten dotyczy rozróżnienia parametrów na ofertowe i produktowe, tak jak podano w odpowiedzi w zbliżonym wątku na stronach społeczności pod tym linkiem:

[https://spolecznosc.allegro.pl/t5/zaawansowani-sprzedawcy/parametr-kod-produktu-nie-powinien-by%C4%8...](https://spolecznosc.allegro.pl/t5/zaawansowani-sprzedawcy/parametr-kod-produktu-nie-powinien-by%C4%87-przepuszczany-jako/td-p/231563)

Jeżeli w data przesyłanym w zapytaniu zamienię "parameters" na "product.parameters" lub "offer.parameters" to nie otrzymuję błędu, jednak parametry w ofercie nie zostają zmienione. 

Proszę o informację w jaki sposób mogę zedytować parametry oferty za pomocą metody PATCH i czy dokumentacja dotycząca tej metody (patrz. pierwszy link, który podałem powyżej) jest nadal aktualna?

**Comment by Lukasz-Zurek** [comment]
@Foveros1 Parametry produktowe powinieneś przekazać w **"productSet"**, w polu **"product.parameters"**, natomiast ofertowe - w innym obiekcie **"parameters"** (poza **"productSet"**). W razie dalszych wątpliwości, prześlij proszę trace-id żądania.

**Comment by Lukasz-Zurek** [comment]
Zgadza się. Wśród parametrów ofertowych, w sekcji "parameters", przekazujesz obecnie parametr **15851**, który ma `"describesProduct": true` (parametr produktowy) i powinien zostać przekazany w sekcji **"productSet"**, kolejno w **"product.parameters"**.

**Comment by Foveros1** [comment]
Czyli rozumiem, że tego i innych parametrów, dla których dostaję ten error, w ogóle nie będę w stanie zedytować metodą PATCH dla samej oferty i możliwe jest jedynie aktualizowanie tych parametrów dla produktów?

**Comment by kamilwyremski** [comment]
Po jakim czasie od wysłania requestu to aktualizacji parametrów produktu zostaną one zaktualizowane w ofercie allegro?
Chodzi o parametry: 
227345 - numer katalogowy oryginału
215941 - numer katalogowy zamienników
215858 - numer katalogowy części
127415 - producent 
Wysłałem request, mam odpowiedź 200 i obiekt oferty, ale nie widzę zmian na Allegro.

**Comment by Lukasz-Zurek** [comment]
@kamilwyremski Jeżeli otrzymałeś odpowiedź 200 to zmiany powinny zostać wdrożone od razu. Prześlij proszę trace-id dla wspomnianego requestu.

**Comment by kamilwyremski** [comment]
Wysyłam taki request:
```
{
  "productSet": [
    {
      "parameters": [
        {
          "id": 227345,
          "values": [
            "AL3B5945257SL"
          ]
        },
        {
          "id": 215941,
          "values": [
            "1"
          ]
        },
        {
          "id": 215858,
          "values": [
            ""
          ]
        }
      ]
    }
  ]
}
```
Pod PATCH https://api.allegro.pl/sale/product-offers/[tu numer oferty]
Dostaje odpowiedź z kodem 200 i w zawartości obiekt oferty (taki sam wywołując https://api.allegro.pl/sale/offers/[tu numer oferty]), nie ma tam pola "trace".
Co robię źle?

**Comment by kamilwyremski** [comment]
Zauważyłem błąd u siebie. Niestety teraz mam błąd z API.
W requescie chcę zaktualizować tylko numery katalogowe produktu. 
ID produktu pobieram z https://api.allegro.pl/sale/offers/[tu numer oferty] pole product.id
Wysyłam taki request:
```
{
  "productSet": [
    {
      "parameters": [
        {
          "id": 227345,
          "values": [
            "AL3B5945257SL"
          ]
        },
        {
          "id": 215941,
          "values": [
            "1"
          ]
        },
        {
          "id": 215858,
          "values": [
            ""
          ]
        }
      ],
     "id": "78f673b9-641b-4237-9778-e2db5ee44e29"
    }
  ]
}
```
Pod PATCH https://api.allegro.pl/sale/product-offers/[tu numer oferty]
To ID produktu jest pobrane tak jak wyżej napisałem.
Dostaje taki error:
  | (
  | [code] => ProductConstraintViolationException.DataIntegrity
  | [message] => Incorrect value of the Numer katalogowy części (249034) parameter for the offered product. The correct parameter value for the product is: "AL3B5945257SL".
  | [details] =>
  | [path] =>
  | [userMessage] => Niepoprawna wartość parametru Numer katalogowy części (249034) dla produktu w ofercie. Prawidłowa wartość parametru dla produktu to: "AL3B5945257SL".
  | )
  |  
  Tylko że ja chcę właśnie zmienić ten numer katalogowy

**Comment by Lukasz-Zurek** [comment]
227345 - to numer katalogowy oryginału, natomiast 215858 to numer katalogowy części, w którym próbujesz przekazać pustą wartość, a powinna być również "AL3B5945257SL", ponieważ takie właśnie dane widnieją w wybranym produkcie. Jeśli chcesz zmienić wartość tego obowiązkowego parametru w produkcie - skorzystaj z [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal), za pomocą którego prześlesz sugestię zmiany w produkcie.

**Comment by kamilwyremski** [comment]
Dziękuje za pomoc, a dlaczego nie mogę użyć PATCH https://api.allegro.pl/sale/product-offers/[tu numer oferty] do zmiany tego parametru? Muszę korzystać z POST /sale/products/{productId}/change-proposals tak?

**Comment by Lukasz-Zurek** [comment]
Powyższą ofertę powiązałeś wcześniej z produktem 78f673b9-641b-4237-9778-e2db5ee44e29, dlatego przekazywana wartość parametru musi być zgodna z tą, która znajduje się w przypisanym do oferty produkcie. Możesz natomiast zmienić tę wartość (jeśli w produkcie jest ona błędna), a właściwie - zasugerować taką zmianę w produkcie poprzez wspomniany przeze mnie zasób i tam należy przekazać również pozostałe wymagane dane.
