### ISSUE TITLE
How to delete Return and Complaint policy ???

### ISSUE THREAD

**Issue by Mercury747** [allegro/allegro-api#7429]
Hello, 
I have an issue with API connector, I'm trying to synchronized  Bigbuy connector with allegro, but its gives me error because I've created  to much policies on Allegro dashboard, 
![Screenshot 2023-07-31 095520](https://github.com/allegro/allegro-api/assets/140708670/a62a5ab1-0c35-40fd-a9e8-d7f930eefb2c)

**Comment by AureliuszBrussy** [comment]
You can't remove the terms of return and complaint. You can edit ([warranty](https://allegro.pl/moje-allegro/sprzedaz/warunki-reklamacji) and [return terms](https://allegro.pl/moje-allegro/sprzedaz/warunki-zwrotow)) and name one of the existing policies as "default". If this does not solve the problem - report the error directly to BigBuy.
