### ISSUE TITLE
Trwające problemy technicznie z wystawianiem aukcji

### ISSUE THREAD

**Issue by Uriziel01** [allegro/allegro-api#743]
Witam,
wiadomo coś o trwających problemach technicznych związanych z wystawianiem aukcji. Wszystko aukcje które próbujemy wystawić ponownie zwracają błąd:
```
{ ["errors"]=> array(1) { [0]=> array(5) { ["code"]=> string(16) "VALIDATION_ERROR" ["message"]=> string(35) "ERR_NOT_EXISTING_VALUE_IN_ATTRIBUTE" ["details"]=> string(0) "" ["path"]=> string(0) "" ["userMessage"]=> string(53) "Nieprawidłowa wartość parametru: Dostawa z Polski " } }
```
mimo iż oryginalna aukcja miała oczywiście włączoną **dostawę z Polski**.

Zmieniła się może nazwa tego pola lub trzeba to teraz zadeklarować jakoś inaczej? Tylko taka zmiana powinna bezwzględnie być odzwierciedlona w dokumentacji API jeżeli o to faktycznie chodzi.

Przykładowa aukcja w której występuje taki problem `7574248023`.

**Comment by PawelTaberski** [comment]
Z tego co widzę masz źle ustawiony parametr odnośnie dostawy z polski powinno być:
```
        {
            "id": "128188",
            "valuesIds": [
                "128188_1"
            ],
            "values": [],
            "rangeValue": null
        },
```
a masz
```
        {
            "id": "128188",
            "valuesIds": [],
            "values": [
                "Tak"
            ],
            "rangeValue": null
        },
```

**Comment by Uriziel01** [comment]
No dobrze, ale to kiedy się to zmieniło? Do tej pory wszystkie wystawiane przez nas aukcje tak miały (setki tysięcy aukcji) i wystawiały się bez błędu. Kiedy nastąpiła zmiana?

**Comment by PawelTaberski** [comment]
Rozmawiałem z zespołem odpowiedzialnym za parametry i w tym wypadku jest to błąd po naszej stronie. Będziemy w przyszłości starali się, aby podobna sytuacja nie miała miejsca i informacja o zmianie była z odpowiednim wyprzedzeniem.
