### ISSUE TITLE
Problem przy próbie pobrania danych paczki

### ISSUE THREAD

**Issue by patryksz14** [allegro/allegro-api#7430]
Dążę do integracji Allegro z Magento 2, zamówienia mam już od jakiegoś czasu ogarnięte, teraz chcę też dołączyć do tego generowanie etykiet. Mam już integrację po stronie Magento z 2 przewoźnikami i teraz będzie dołączał trzeci, ale z tego co widzę jest możliwość ich generowania po stronie allegro (endpoint GET parcel-management/parcels/label) gdzie jest potrzebny id paczki, lecz po utworzeniu paczki (parcel) i próbie uzyskania id (endpoint GET parcel-management/parcel-create-commands/{{uuid}}) wyrzuca mi 
{
    "id": {{uuid}},
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Internal system error",
            "details": null,
            "path": "",
            "userMessage": "error.common.internal"
        }
    ]
}

Ktoś napotkał się z tym problemem? Lub może jest lepszy sposób na generowanie etykiet?

**Comment by AureliuszBrussy** [comment]
Podaj proszę trace-id swojego wywołania. Trace-id znajdziesz w nagłówku naszego response'a (tego z errorem). Sprawdzimy co jest powodem tego błędu.

**Comment by patryksz14** [comment]
Trace id to 6ad8d787a4bac063

**Comment by AureliuszBrussy** [comment]
Dziękuję za trace-id. Wyjaśniam to z zespołem odpowiedzialnym za te zasoby. Wrócę z odpowiedzią.

**Comment by kasprzykr** [comment]
Podepnę się pod temat. 

Ostatnio miałem podobny problem z "Internal system error" (środowisko sandbox) natomiast dzisiaj przy kilkunastu próbach, każda skończyła się zwrotką:
{
    "id": {{uuid}},
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ANOTHER_SERVICE_NOT_AVAILABLE",
            "message": "One of required services is unavailable. Try again later.",
            "details": "One of required services is unavailable. Try again later.",
            "path": null,
            "userMessage": "Jeden z wymaganych serwisów, do poprawnego działania, jest niedostępny. Spróbuj ponownie za moment."
        }
    ]
}

Przykładowe trace-id: 31d31480a0218ff0

**Comment by AureliuszBrussy** [comment]
@kasprzykr dziękuję za kolejny przykład, jeszcze to wyjaśniam. Wrócę z informacjami.

**Comment by patryksz14** [comment]
@AureliuszBrussy Mamy już jakieś informacje?

**Comment by AureliuszBrussy** [comment]
@patryksz14 niestety, wciąż nie mam wyjaśnienie. Czy masz może jeszcze jakiś przykład świeższego requesta zakończonego tym błędem?

**Comment by patryksz14** [comment]
@AureliuszBrussy Praktycznie jest ten sam błąd, podsyłam kolejny trace id: dacaad2364fb2683

**Comment by AureliuszBrussy** [comment]
@patryksz14 dziękuję za nowy przykład, staram się to wyjaśnić. Prosiłbym o jeszcze trochę cierpliwości.

**Comment by AureliuszBrussy** [comment]
@patryksz14 błąd powoduje brak przekazania wymiarów przesyłki w obiekcie **items.dimensions**. Przesyłka nie została ostatecznie utworzona. Po naszej stronie wdrożymy poprawkę w sposobie obsługi tego błędu.

**Comment by ls666-pz** [comment]
kiedy można liczyć na poprawkę?

**Comment by AureliuszBrussy** [comment]
Niestety, ale na teraz nie jestem w stanie podać dokładnej informacji. Poprawka będzie polegać na tym, że zwrócimy czytelny error, co jest przyczyną braku utworzenia przesyłki. Natomiast tak czy inaczej kwestia z tego wątku sprowadza się do braku przesłania wymiarów paczki.

**Comment by ls666-pz** [comment]
do 30.08.2023 już coraz bliżej, planujecie przedłużyć termin, czy będziemy musieli się zwijać "za pięć dwunasta"?

**Comment by AureliuszBrussy** [comment]
@ls666-pz tak jak wspomniałem, w przypadku z tego wątku wystarczy w requeście zdefiniować wymiary paczki i błąd nie wystąpi, a przesyłka zostanie utworzona.

**Comment by kasprzykr** [comment]
@AureliuszBrussy pytanie co ze zgłaszanym przezemnie problemem? Mam to zgłosić jako osobny wątek?
Problem nadal występuje trace_id z dzisiaj 52b26f4e1e936912 nie mogę kontynuować prac związanych z integracją Allegro One jeżeli za każdym razem otrzymuję komunikat:
`"errors": [
        {
            "code": "ANOTHER_SERVICE_NOT_AVAILABLE",
            "message": "One of required services is unavailable. Try again later.",
            "details": "One of required services is unavailable. Try again later.",
            "path": null,
            "userMessage": "Jeden z wymaganych serwisów, do poprawnego działania, jest niedostępny. Spróbuj ponownie za moment."
        }
    ]`

a czasu coraz mniej

**Comment by AureliuszBrussy** [comment]
@kasprzykr adres emailowy odbiorcy, który podałeś w **receiver.email** pochodzi z produkcji. Powinieneś przekazać mail pobrany z zamówienia z Sandboxa. 

Dodatkowo wybrana serwis dostawy nie wspiera płatności przy odbiorze - w swoim requeście przekazujesz wartość w **additionalServices.cashOnDelivery**. Nie przekazuj tej wartości.
