### ISSUE TITLE
Commission refund Schrodinger

### ISSUE THREAD

**Issue by jakub-marchewka** [allegro/allegro-api#7431]
Dzień dobry,
pracuję ze zwrotami prowizji i napotkałem zagwozdkę, a mianowicie:
Przy anulowanym zamówieniu, które nie było opłacone, została automatycznie zwrócona prowizja ale tej informacji próżno szukać we wnioskach o zwrot oraz historii płatności, nie mogę wyświetlić widoku płatności oraz nie wymogę wykonać zwrotu ? Czy orientują się państwo gdzie mogę znaleźć w api informacje o takich zwrotach ? 
id płatności: "237f45eb-2f95-11ee-87f8-89b777b3cad4"
środowisko: sandbox

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, takie informacje uzyskasz w odpowiedzi [GET /billing/billing-entries](https://developer.allegro.pl/tutorials/jak-sprawdzic-oplaty-nn9DOL5PASX#historia-operacji-billingowych). Typ takiego wpisu to:

```
            "type": {
                "id": "REF",
                "name": "Zwrot kosztów"
            },
```

**Comment by jakub-marchewka** [comment]
Dziękuję za odpowiedź, orientujesz się czy w tym endpoincie znajdują się też informacje o automatycznych zwrotach płatności ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, ponieważ znajdują się tutaj wszystkie operacji billingowe, które zwracamy w ramach [historii operacji billingowych](https://allegro.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro?sellerId=62799754) na stronie internetowej. Przykładem automatycznego zwrotu prowizji jest wpis o wyżej przytoczonym typie.

**Comment by jakub-marchewka** [comment]
![Zrzut ekranu z 2023-07-31 15-40-49](https://github.com/allegro/allegro-api/assets/57119404/22370403-5288-4146-9e2a-371dd540593e)
Miałem na myśli zmianę "statusu" danego paymentu

**Comment by PrzemyslawLukanowski** [comment]
Ok, widzę, że powyżej miałeś na myśli zwroty płatności a nie prowizji - listę zwrotów płatności zwracamy w [GET /payments/refunds](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#jak-pobrac-liste-zwrotow-platnosci). Są one także udokumentowane w ramach historii operacji płatnościowych - [GET /payments/payment-operations](https://developer.allegro.pl/tutorials/jak-sprawdzic-oplaty-nn9DOL5PASX#historia-operacji-platniczych). Nie udostępniamy endpointu, który wskazywałby bezpośrednio zmianę statusów danej płatności.

**Comment by jakub-marchewka** [comment]
Tak, przepraszam za zmianę tematu, początkowo chciałem ująć w wątku dwa problemy. Dziękuję za pomoc :)

**Comment by PrzemyslawLukanowski** [comment]
Nie ma problemu :) To jeszcze tylko doprecyzuję ostatnie zdanie - taką zmianę statusów możesz zaobserwować właśnie w [GET /payments/payment-operations](https://developer.allegro.pl/tutorials/jak-sprawdzic-oplaty-nn9DOL5PASX#historia-operacji-platniczych). Wspomniana przez Ciebie płatność najpierw "wpadła" jako:

```
            "type": "CONTRIBUTION",
            "group": "INCOME", 
```
a po tym, gdy nastąpił zwrot, otrzymałeś nowy wpis związany z tą płatnością:

```
            "type": "REFUND_CHARGE",
            "group": "REFUND",
```
