### ISSUE TITLE
Problem z aktualizacją aukcji

### ISSUE THREAD

**Issue by stprojects** [allegro/allegro-api#7433]
Witam, przygotowałem dla klienta skrypt który o określonej godzinie w określonym dniu aktualizuje opis aukcji. Skrypt ten działa już od roku i wszystko było w porządku, jednak od jakiegoś czasu przy aktualizacji pojawia się błąd "GallerySizeException" o treści "Przekroczono limit 16 zdjęć.". Klient faktycznie aktualizował aukcje przez panel Allegro i w tych aukcjach jest więcej zdjęć, jednak pytanie dlaczego przez panel miał możliwość dodać więcej niż 16 zdjęć, a przez api już nie ma?

Skrypt działa w taki sposób, że pobiera całą treść aukcji, wszystkie sekcje i zapisuje kopię tej treści. Następnie podmieniane są w treści wszystkie frazy określone przez użytkownika, i wysyłany jest update aukcji przez api. I to właśnie w tym momencie nie przechodzi ona walidacji. Czy mogę coś z tym zrobić?

**Comment by PrzemyslawLukanowski** [comment]
W przypadku pytań o formularz wystawiania zachęcam do skorzystania z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt). Nie udało mi się powtórzyć takiego scenariusza - maksymalnie mogę dodać 16 zdjęć, wliczając w to zdjęcia z Katalogu produktów, jak i te dodane manualnie przeze mnie.  

W kontekście API, jeśli oferta rzeczywiście zawiera więcej zdjęć niż 16 zdjęć, odpowiedź błędu jest prawidłowa i musisz usunąć nadmiarowe zdjęcia.

**Comment by zygfryd123** [comment]
Zdjęć (plików) fizycznie na aukcji jest max 16, natomiast jedno ze zdjęć jest powielone parokrotnie w opisie, bo to graficzna belka z logo, rozdzielająca poszczególne sekcje opisu. Edytor wizualny na Allegro nie widzi nadal przeszkód, żeby tak tworzyć aukcje i powielać jedno zdjęcie nawet w nieskończoność, natomiast problem pojawia się jedynie w przypadku API, ponieważ takie powielenie jest traktowane jakby każde powielenie było osobnym zdjęciem, co przekłada się na przekroczenie limitu 16 plików. Przez rok wszystko dobrze działało, problem pojawił się dopiero teraz. Czy mogę prosić o dokładną weryfikację?

**Comment by PrzemyslawLukanowski** [comment]
Jakiś czas temu rzeczywiście opisana sytuacja mogła wystąpić, jednak wprowadziliśmy odpowiednią poprawkę, która eliminowała ten problem. Aktualnie również nie udało mi się powtórzyć tego błędu, dlatego prosiłbym o przykładowe trace-id, dzięki któremu moglibyśmy przeanalizować tę sytuację.
