### ISSUE TITLE
Sprawdzenie czy oferta jest promowana

### ISSUE THREAD

**Issue by r1pped** [allegro/allegro-api#7434]
Dzień dobry, 

jestem w trakcie wdrażania zmian w swojej aplikacji związanych z oznaczeniem endpointu GET /sale/offers/{offerId} jako deprecated. Poprzednio za pomocą tego endpointu sprawdzałem czy oferta jest promowana po zwracanym polu „promotion”. Były tam informacje czy jest to pogrubienie czy podświetlenie aukcji na liście. W nowym endpoincie GET /sale/product-offers/{offerId} nie widzę takiej informacji w zwracanych polach. 

W jaki sposób mogę uzyskać te same informacje odnośnie promowania oferty co w poprzednim endpoincie?

**Comment by PrzemyslawLukanowski** [comment]
Jeśli chodzi o opcje promowania, to udostępniliśmy nowe zasoby, dzięki którym możesz zarządzać tą funkcjonalnością. Szczegóły znajdziesz w [naszym newsie](https://developer.allegro.pl/news/nowe-zasoby-do-promowania-ofert-YW2z1yG7DFj) oraz [poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-zarzadzac-promowaniem).

**Comment by r1pped** [comment]
Dziękuję za pomoc, już wszystko jasne. Natomiast mam jeszcze jedno pytanie odnośnie tych endpointów, więc może zadam je już w tym wątku.

Za pomocą endpointu PUT /sale/offers/{offerId} jestem w stanie odpiąć produkt od oferty, natomiast za pomocą PATCH /sale/product-offers/{offerId} już nie. W odpowiedzi dostaję 422 z wiadomością 'Unable to unlink product from offer'.

Według tego [poradnika](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-przypisac-produkt-do-oferty), jest to prawidłowe działanie. Pytanie brzmi, skoro ten pierwszy endpoint jest deprecated, czy jestem w stanie w inny sposób odpiąć produkt od oferty? Czy od 2024 roku już nie będzie takiej możliwości?

**Comment by MaciejFrackowiak** [comment]
Dążymy do sytuacji, w której praktycznie 100% ofert Allegro będzie połączonych z odpowiadającymi im produktami. Dlatego też nie będzie możliwości wystawienia oferty bez produktu, czy też odpięcia produktu od oferty.
