### ISSUE TITLE
Offer creating/editing compatibilities list problem

### ISSUE THREAD

**Issue by raimondases4b** [allegro/allegro-api#7435]
Hello,

Got problem with offer (create & edit).
I think something wrong with compatibilities list but I don't know whats wrong and how to find out because response isn't clearly...

Tried with methods:
/sale/offers/
/sale/product-offers/

I attaching /sale/offers/ editing method request and response data file.
[offer_data.zip](https://github.com/allegro/allegro-api/files/12237140/offer_data.zip)

**Comment by PrzemyslawLukanowski** [comment]
Hello, the message in the response indicates that the structure in your payload is not valid. You can compare it with our documentation:

<img width="741" alt="Zrzut ekranu 2023-08-2 o 09 42 13" src="https://github.com/allegro/allegro-api/assets/51473661/5febc6fc-b4f9-4ebc-986b-ccd1d551011c">


In your example, there are redundant fields in compatibilityList.items[] such as "1", "2", "3", etc. Besides, the "items" field should be an array. Here's an example of a valid JSON:

```
  "compatibilityList": {
    "items": [
      {
        "id": "4e2ed482-61bb-429a-94f3-648bcfbbd9e3",
        "type": "ID"
      },
      {
        "id": "9f326de6-71eb-40c9-ab55-0eea5a2a08fc",
        "type": "ID"
      },
      {
        "id": "60ec4b15-b4f1-4df5-a12f-ec734961bf47",
        "type": "ID"
      }
    ],
    "type": "MANUAL"
  },
```

**Comment by raimondases4b** [comment]
[offer_data2.zip](https://github.com/allegro/allegro-api/files/12238381/offer_data2.zip)

**Comment by PrzemyslawLukanowski** [comment]
Thanks, but you did not make the corrections that I have listed above :) You are still using redundant fields, like "0", "1", "2", etc:

```
  "compatibilityList": {
    "items": {
      "0":{
        "id": "4e2ed482-61bb-429a-94f3-648bcfbbd9e3",
        "type": "ID"
      },...
```

and the "items" field is still an object instead of an array.

**Comment by PrzemyslawLukanowski** [comment]
You need to get rid of those "0", "1" and so on and also use [] instead of {} in "items", because here's what we're receiving: 

```
  "compatibilityList": {
    "items": {
      "0": {
        "id": "4e2ed482-61bb-429a-94f3-648bcfbbd9e3",
        "type": "ID"
      } ...
```

and here's a proper structure of this section:

```
  "compatibilityList": {
    "items": [
      {
        "id": "4e2ed482-61bb-429a-94f3-648bcfbbd9e3",
        "type": "ID"
      } ...
```

You can also send me a trace-id of your request so I will also verify our internal logs and check how the JSON payload is built.

**Comment by raimondases4b** [comment]
Hmmm, im using php library and I need build simple array
Here is trace id : 86814cf8a4bb7164
But im still confused if i remove last 5 items from compatibilties - it worked

**Comment by PrzemyslawLukanowski** [comment]
Sorry, I forgot that in 400 Bad Request cases, the payload is not saved in our logs cause it's rejected due to a not readable message. I tried to recreate the scenario you mentioned (removing the last 5 items from compatibles), but it didn't work, the error is still returned. The only way to solve this issue is to change the structure to the example above.

**Comment by raimondases4b** [comment]
Sorry, there was problem in  compatibilities array, its has removed 1 duplicate item in example there is no 148 index and somehow its broke array than continues bad json encoding and than bad request...

Thank you for your time.
