### ISSUE TITLE
Brak zdjęć które były w allegro

### ISSUE THREAD

**Issue by PiotrPiotrP** [allegro/allegro-api#7436]
Dzień dobry

Nie wiem dlaczego zniknęły zdjęcia z allegro które tam były.

07/31 11:41:35.714  PUT    https://api.allegro.pl/sale/offers/13981269262 requestBody={"afterSalesServices":{"impliedWarranty":{"id":"2599d697-eaee-4a9d-bfd5-213717c9ba62"},"returnPolicy":{"id":"10bbd9d6-a61a-421b-aafd-e2289c330400"},"warranty":{"id":"9f8841ad-ad8a-4cd8-aaf8-ae9087556b6f"}},"category":{"id":"87873"},"delivery":{"shippingRates":{"id":"92cb3f82-ae74-4d10-8804-2d9a444c4d55"},"handlingTime":"PT24H"},"external":{"id":"stocksell_497183020"},"id":"13981269262","images":[{"url":"https://a.allegroimg.com/original/115924/289783d944e9ab39aea80e35c7a8"},{"url":"https://a.allegroimg.com/original/119b21/47247f2c481faa0f4f2ba20d08f5"},{"url":"https://a.allegroimg.com/original/113bc5/c233dbb447e4bd2a77f3a324bb44"},{"url":"https://a.allegroimg.com/original/110a53/70c3a7214630b37ac38cc067d63a"},{"url":"https://a.allegroimg.com/original/116425/0e5bd48f4a4fb08d4e2e5b163750"},{"url":"https://a.allegroimg.com/original/117f94/741ce7ff41c9aa7a225e7c06b360"},{"url":"https://a.allegroimg.com/original/117c9e/6e838f984506a4cc7113151683b1"}],"location":{"city":"Skawina","countryCode":"PL","postCode":"32-050","province":"MALOPOLSKIE"},"parameters":[{"id":"15851","valuesIds":["15851_2"]},{"id":"204185","valuesIds":["204185_8"]},{"id":"201017","valuesIds":["201017_2377"]},{"id":"203057","values":["0"]},{"id":"3786","values":["Inna marka"],"valuesIds":["3786_85"]},{"id":"129012","valuesIds":["129012_380765"]},{"id":"202677","valuesIds":["202677_212897"]},{"id":"201025","valuesIds":["201025_2513"]},{"id":"54","valuesIds":["54_5"]},{"id":"18293","valuesIds":["18293_2"]},{"id":"201089","values":["0"]},{"id":"11323","valuesIds":["11323_2"]},{"id":"3766","valuesIds":["3766_6"]},{"id":"249512","valuesIds":["249512_1647428"]}],"name":"KOSZULA MĘSKA Z KRÓTKIM RĘKAWEM W PASKI L 1XMA","payments":{"invoice":"VAT"},"publication":{"startingAt":"2023-08-01T16:35:16.000Z","republish":false},"sellingMode":{"format":"BUY_NOW","price":{"amount":34.99,"currency":"PLN"}},"stock":{"available":1,"sold":0,"unit":"UNIT"},"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003ch2\u003eKOSZULA MĘSKA Z KRÓTKIM RĘKAWEM W PASKI\u003c/h2\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/115924/289783d944e9ab39aea80e35c7a8"},{"type":"TEXT","content":"\u003ch2\u003eOpis Produktu\u003c/h2\u003e\u003cul\u003e\u003cli\u003e\u003cb\u003eMarka\u003c/b\u003e Inna marka\u003c/li\u003e\u003cli\u003e\u003cb\u003eKolor\u003c/b\u003e Wielokolorowy   \u003c/li\u003e\u003cli\u003e\u003cb\u003eSkład\u003c/b\u003e Poliester          \u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka papierowa\u003c/b\u003e Brak\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka wewnętrzna\u003c/b\u003e Wycięte ze względu na restrykcję outletową\u003c/li\u003e\u003cli\u003e\u003cb\u003eRozmiar\u003c/b\u003e L\u003c/li\u003e\u003cli\u003e\u003cb\u003eStan przedmiotu\u003c/b\u003e Opis znajduje się pod zdjęciami produktu\u003c/li\u003e\u003cli\u003e\u003cb\u003eCena katalogowa\u003c/b\u003e 97,99 zł\u003c/li\u003e\u003c/ul\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/110a53/70c3a7214630b37ac38cc067d63a"},{"type":"IMAGE","url":"https://a.allegroimg.com/original/113bc5/c233dbb447e4bd2a77f3a324bb44"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/116425/0e5bd48f4a4fb08d4e2e5b163750"},{"type":"IMAGE","url":"https://a.allegroimg.com/original/117f94/741ce7ff41c9aa7a225e7c06b360"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/119b21/47247f2c481faa0f4f2ba20d08f5"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/117c9e/6e838f984506a4cc7113151683b1"},{"type":"TEXT","content":"\u003ch2\u003eOpis Wady\u003c/h2\u003e\u003ch2\u003eWada\u003c/h2\u003e\u003cul\u003e\u003cli\u003eRodzaj wady: Rozmieszczenie wzoru może różnić się od umieszczonego na zdjęciu\u003c/li\u003e\u003cli\u003eRozmiar wady: Nie dotyczy\u003c/li\u003e\u003c/ul\u003e\u003ch2\u003eWada\u003c/h2\u003e\u003cul\u003e\u003cli\u003eRodzaj wady: zapach użytkowania\u003c/li\u003e\u003cli\u003eRozmiar wady: nie dotyczy\u003c/li\u003e\u003c/ul\u003e"}]}]},"tax":{"percentage":"23.00"},"language":"pl-PL"} exception=Niepoprawna odpowiedź z Allegro. Kod: 422. Błąd: VALIDATION_ERROR Invalid image address. Invalid image address. OfferImagesNotFoundException . Trace-id=[654c1a36a59dedb0].

**Comment by PiotrPiotrP** [comment]
Dziękuję za informację, a jak długi jest time-to-live?

**Comment by AureliuszBrussy** [comment]
Dopóki nie skorzystasz ze zdjęcia w ofercie, jest to 6 godzin. Zwracamy tą informację w polu expiresAt w momencie uploadu zdjęcia.

**Comment by PiotrPiotrP** [comment]
Ten przypadek dotyczył zdjęcia które było użyte w innej aukcji (ten sam produkt ktoś zwrócił i został wystawiony jeszcze raz) te url był użyte.

**Comment by AureliuszBrussy** [comment]
@PiotrPiotrP czy możesz podać numer tej wcześniejszej oferty? Sprawdzę to.

**Comment by PiotrPiotrP** [comment]
stary numer aukcji 12987120414

**Comment by AureliuszBrussy** [comment]
Spojrzałem w dane historyczne oferty - nie było w jej galerii zdjęć, o których piszemy. Tablica zdjęć dodanych do wcześniejszej oferty:

```
     "images": [
      {
        "url": "https://a.allegroimg.com/original/116425/0e5bd48f4a4fb08d4e2e5b163750"
      },
      {
        "url": "https://a.allegroimg.com/original/117f94/741ce7ff41c9aa7a225e7c06b360"
      },
      {
        "url": "https://a.allegroimg.com/original/119b21/47247f2c481faa0f4f2ba20d08f5"
      },
      {
        "url": "https://a.allegroimg.com/original/115a34/2b4f7c894b5ab6d2db2e02a42b47"
      }
    ]
```

**Comment by PiotrPiotrP** [comment]
Dziękuję
