### ISSUE TITLE
Błąd przy próbie utworzenia listu przewozowego

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#7437]
Dzień Dobry, przy próbie utworzenia listu przewozowego poprzez API otrzymuję błąd

Wystąpił błąd podczas komunikacji z systemem zewnętrznym (Allegro)
Błąd Allegro: Nie udało się utworzyć nowego [listu.Info](http://listu.info/) api allegro: 'Wybrana metoda dostawy nie obsługuje tego zamówienia [Seller didnt provide credentials for own delivery Method]'
Inner: Nie udało się utworzyć nowego [listu.Info](http://listu.info/) api allegro: 'Wybrana metoda dostawy nie obsługuje tego zamówienia [Seller didnt provide credentials for own delivery Method]'

Czy oznacza on ,że jest wymagana jakaś dodatkowa konfiguracja narzędzia wysyłam z allegro od strony panelu?

**Comment by AureliuszBrussy** [comment]
Dzień dobry. Podczas tworzenia przesyłki powinieneś skorzystać z usługi dostawy zgodnej z tą wybraną przez kupującego. Właściwą usługę dostawy rozpoznasz po identyfikatorze: w zamówieniu zwracamy go w polu delivery.method.id. Przy tworzeniu przesyłki skorzystaj z odpowiedniego serviceId - będzie on odpowiadał temu zwróconego w zamówieniu.

**Comment by AureliuszBrussy** [comment]
@Maciej-Wilkosz wyjaśniam to z zespołem odpowiedzianym za Wysyłam z Allegro. Wrócę z odpowiedzią.

**Comment by mwkkowalczyk** [comment]
Tytuł wątku zgadza się z moim pytaniem, więc tu się podkleję - 
proszę o zerknięcie i naprowadzenie co jest nie tak przy próbie utworzenia listu przewozowego 14d3b9c4-ca3b-4e37-89c0-6f6cac24a02e dla konta cf_skp_test
Dostaję w zwrotce:
400 Bad Request 
VALIDATION_ERROR
nie mo\u017ce by\u0107 puste,details:Invalid value: null,path:pickup.ad (truncated...)
A generalnie no to mam pola uzupełnione w pickup przecież...

**Comment by mwkkowalczyk** [comment]
@AureliuszBrussy  dziękuję! :)

**Comment by AureliuszBrussy** [comment]
@Maciej-Wilkosz dziękuję za cierpliwość, wygląda to na próbę wykorzystania metody dostawy, która wymaga umowy własnej z przewoźnikiem, sprzedający powinien spróbować dodać taką umową w ustawieniach [Wysyłam z Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/wysylam-z-allegro-narzedzie-do-nadawania-przesylek-bezposrednio-z-konta-E7doGw8VgI1#jak-dodac-umowe-wlasna-w-wysylam-z-allegro).
