### ISSUE TITLE
Jak sprzedawca może anulować zamówienie lub zablokować płatność z perspektywy klienta?

### ISSUE THREAD

**Issue by is-tomaszgasior** [allegro/allegro-api#7438]
W jaki sposób przez API jako sprzedawca (firma) mogę anulować zamówienie złożone przez klienta? Endpoint "/order/checkout-forms/{id}/fulfillment" pozwala na zmianę statusu z perspektywy sprzedawcy. Ja potrzebuję anulować zamówienie z perspektywy klienta w taki sposób, aby klient po swojej stronie widział, ze zamówienie jest anulowane. W szczególności zależy mi na tym, abym z poziomu API jako sprzedawca (firma) mógł zablokować możliwość opłacenia takiego zamówienia.

**Comment by PrzemyslawLukanowski** [comment]
Nie udostępniamy bezpośredniej możliwości anulowania zamówienia ze strony sprzedającego, możesz jedynie zwrócić wpłatę kupującemu, podając przy tym odpowiedni powód. Wykonasz to za pomocą [POST /payments/refunds](https://developer.allegro.pl/documentation/#operation/initiateRefund), więcej szczegółów znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#zwroty-platnosci), a na [stronie dla sprzedających](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/anulowanie-zakupu-informacje-dla-sprzedajacych-KMOZGKlO5fR) znajdziesz komplet informacji o samym procesie anulowania zakupów.
