### ISSUE TITLE
API - Errors when adding products

### ISSUE THREAD

**Issue by DenisScript** [allegro/allegro-api#7439]
Good afternoon.
When adding some products, the following errors occur:
Brak lub niepoprawna wartość w polu language.
Uzupełnij parametry obowiązkowe: Rodzaj.
Can I somehow find out the ID of the parameters by which the error occurs?

**Comment by PrzemyslawLukanowski** [comment]
Hello,
The first error:

> Brak lub niepoprawna wartość w polu language.

refers to the "language" field (so not a specific parameter in the "parameters" section):
<img width="409" alt="Zrzut ekranu 2023-08-3 o 08 12 44" src="https://github.com/allegro/allegro-api/assets/51473661/0779110f-c84d-4723-88a4-f15d2ddcdcaf">

the ID of the parameter in the second error:

> Uzupełnij parametry obowiązkowe: Rodzaj.

 can be retrieved from the `errors.message` field.

Also, please note that if you want to receive error messages in English, use additional header `Accept-Language: en-US`.
