### ISSUE TITLE
pobieranie ofert o stutusie publikacji ENDED

### ISSUE THREAD

**Issue by dostawcaopon** [allegro/allegro-api#744]
czy za pomocą zasobu /offers/listing
można pobierać również listę zakończonych ofert które można wznowić?

**Comment by PawelTaberski** [comment]
Nie wiem czy dobrze rozumiem Twoje pytanie, ale w takim przypadku wyślij GET na  /offers/listing?seller.id=(podaj user id)&searchMode=CLOSED . Więcej na temat tego zasobu znajdziesz [tutaj](https://developer.allegro.pl/news/2018-07-03-Listing_ofert/).

**Comment by dostawcaopon** [comment]
w "moim allegro" można listować swoje oferty z włączonym filtrem statusu oferty (aktywna, zakończona, zaplanowana, draft).

czy za pomocą zasobu /offers/listing z podanym własnym id_seller mogę zaciągnać listę ofert np tylko aktywnych albo tylko zakończonych ?
jeśli dam np  /offers/listing?seller.id=xxxxxx&searchMode=REGULAR to pobiorą się tylko oferty o statusie publikacji ACTIVE  czy wszystkie oferty (drafty, zakończone, etc) ?

**Comment by PawelTaberski** [comment]
Tylko aktywne bez draftów. Obecnie nie ma metody do wylistowania draftów jakie stworzyłeś, ale pracujemy nad taką metodą. Obecnie wystawiony zasób listing jest odzwierciedleniem wyszukiwarki jaka działa na froncie. Ale tak, jak mówiłem pracujemy nad metoda do listingu ofert sprzedawcy. Jak tylko będziemy wiedzieli kiedy skończymy nad nią pracę i ją wdrożymy to poinformujemy o tym.

**Comment by imper86** [comment]
@PawelTaberski jeśli mogę coś zasugerować to przydałaby się też metoda do usuwania draftów, bądź zrobić jakiś deadline np 30 dniowy życia danego draftu, żeby nie robić śmietniska

**Comment by PawelTaberski** [comment]
@imper86 Proszę bardzo :-) [DELETE /sale/offers/{offerId}](https://developer.allegro.pl/news/2018-10-09_Draft_delete/) Wdrożyliśmy metodę do usuwania draftów w tym tygodniu.

**Comment by imper86** [comment]
@PawelTaberski o kurde, tego to się nie spodziewałem :D

**Comment by imper86** [comment]
@PawelTaberski a kiedy można się spodziewać jakiejś metody do pobierania nieaktywowanych draftów?

**Comment by imper86** [comment]
@PawelTaberski super, dziękuję

**Comment by PawelTaberski** [comment]
@imper86 Udostępniliśmy taki zasób więcej na ten temat [tutaj](https://developer.allegro.pl/my_offers/#1).

**Comment by imper86** [comment]
@PawelTaberski widziałem już, superowo, dzięki :)
