### ISSUE TITLE
Zdjęcia - modyfikacja produktu wyszukanego w produktyzacji

### ISSUE THREAD

**Issue by ircoo2022** [allegro/allegro-api#7440]
Witam,

mam problem - pytanie.

Wyszukuję po ean produkt ( php curl ) CURLOPT_URL => 'https://api.allegro.pl/sale/products?phrase='.$model.'&mode=GTIN',

znajduje i modyfikuje m.in zdjecia:

$params['images'][0]  = ' link do zdjecia';
$params['images'][1]  = ' link do zdjecia 2';

wysyłam
$ch = curl_init();
				curl_setopt_array($ch, array(
					CURLOPT_URL => 'https://api.allegro.pl/sale/product-offers',
					CURLOPT_HTTPHEADER => $headers,
					CURLOPT_SSL_VERIFYPEER => false,
					CURLOPT_RETURNTRANSFER => true,
					//CURLOPT_HEADER => 1,		
					CURLOPT_POST => false,
					CURLOPT_POSTFIELDS => json_encode($params)
				));

Teraz po wystawieniu nowych sa również zdjęcia z produktyzacji, których nie powinno być. Chcę mieć tylko moje np. 2 a nie 10 czyli moje 2 i 8 z produktyzacji z podpinanego produktu
Czy to możliwe ???

**Comment by PrzemyslawLukanowski** [comment]
Tak, w tym celu w sekcji `productSet.product.images` przekaż tylko wybrane przez siebie zdjęcia z Katalogu produktów lub pustą tablicę, jeśli nie chcesz żadnych zdjęć z Katalogu.

**Comment by ircoo2022** [comment]
Tzn właśnie chcę zdjęcia ale całkiem inne niż te z produktyzacji produktu który znalazłem.
Powiedzmy tamten produkt ma 10 zdjec a ja chce nowe swoje  2 wgrac tylko a ten mi i tak przekazuje tamte

**Comment by PrzemyslawLukanowski** [comment]
W takim razie tak jak wspomniałem wyżej:

>  w sekcji productSet.product.images przekaż (...) pustą tablicę, jeśli nie chcesz żadnych zdjęć z Katalogu.

Przykład znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty).

**Comment by ircoo2022** [comment]
super
