### ISSUE TITLE
Problem z zapisem etykiety PDF/ZPL na środowisku testowym

### ISSUE THREAD

**Issue by ke-mez** [allegro/allegro-api#7441]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other
 
Dzień dobry, na środowisku testowym próbuję utworzyć paczkę, napotykam jednak pewien problem.

- traceId = "**1c6df6fa92102086**"
- parcelId = "**b3e126cd-20be-4c5f-9e30-5ee9d3fe6296**"

Podczas tworzenia paczki wybrałem opcję PDF
url:"https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcels/label?parcelId=b3e126cd-20be-4c5f-9e30-5ee9d3fe6296"
próba tworzenia etykiety jako PDF zwraca mi stringa, który wygląda tak:
"%PDF-1.4\n%����\n3 0 obj\n<</Filter/FlateDecode/Length 71>>stream\nx�+�r\n�26S�00S\bI�r\r�\n�*T0T0\0B\b����\u001f�f���\0�2г4\u0005�\u0003\u0019&\u0006fF\n\u0016\n&F�PUF\u0010U\0��\u0012\u0006\nendstream\nendobj\n5 0 obj\n<</Contents 3 0 R/Type/Page/Resources<</XObject<</Xf1 1 0 R/Xf2 2 0 R>>>>/Parent 4 0 R/MediaBox[0 0 595 842]>>\nendobj\n1 0 obj\n<</Subtype/Form/Filter/FlateDecode/Type/XObject/Matrix [1 0 0 1 0 0]/FormType 1/Resources<<>>/BBox[0 0 595 842]/Length 56>>stream\nx�3V(�62�U06PH�2P012T��2�4\u0005�r��,��L\u0015t-L���\u0010\u000e���\u0015�\u0005\0e�\v�\nendstream\nendobj\n2 0 obj\n<</Subtype/Form/Filter/FlateDecode/Type/XObject/Matrix[1 0 0 1 0 0]/FormType 1/Resources<</ProcSet[/PDF/Text/ImageB/ImageC/ImageI]/ExtGState<</GS0 6 0 R>>/XObject<</I0 7 0 R>>>>/Length 61/BBox[0 0 283.46 425.2]>>stream\nx�+�*�2P\0��t.}�`\u0003��b�B\u0005#\vc=\u00133\u00133���������%������i���\u0010�\u0005�\0Π\r�\nendstream\nendobj\n6 0 obj\n<</Type/ExtGState/ca 1>>\nendobj\n7 0 obj\n<</ColorSpace[/Indexed/DeviceRGB 255 8 0 R]/Mask[252 252]/Subtype/Image/Height 189/Filter/FlateDecode/Type/XObject/Width 70/Length 744/BitsPerComponent 8/Interpolate true>>stream\nx��Z1��@\u0010\\�H�Qb=B��U\u000e\u001d�\vX��)\u0011�Evr���6�\u0003�p�ˉ�ѾC��#�I�\v��.����E�KH$j�t�3�\"z\u0001��X�E\u0006!Ų>�O�kFK�i\u0019���>]B�H�eE��8���C_o�ο>e\u0010�N��\u001d�H\u0013��1�\u001c_$\u0005v,w�t�B?��F]\u000fH,��f8�X���\u0012`!\u0013\u007f�\bZ�×m~h�X\u001c�\rĲ�>m��\f�I��t���\u0013���6>4���\u001d\u000f�\nX]5���m�һ���\u0018�����;u��DPݵ&/rc1���lx�����XT��\u0016u��\u0012�ĝ\u0006pu�E\u0016\u0012qz��ٰ�@�4�e\u0001��X�i6�\u0002N��>�f\t�O��M�6]��r��5Y�jh�\u001fnk�{�<zn7\u0004Y\u0016,�\u001b�X<\u0002��\u001b��\u0010J\u000f8uCe��u�}��W\u0006���\"/�\u001e0\a[�\u0011��\u0004�����\f��hW��a\u0017�\r��3\u001e\u0014��_�\u0019Ua�ҟ��4M�\tR7�\u001b�P�d\u0004v��'l�M��\u000e�iCX��\u000e�\u001e\\��],Ӓf��\\�\u001eu��9�fY�i6\u0016p��28]�N�\0�<�$��z�cyV��,2�{�Te�7���P-�\u0019�j\u007f�'��:#�(\u007f���hr�\u001dk\u0005�i���\b�\u00016�w�\u001b7hB����\"��@=�\u001a��4��*\u0019��8�#<;#e��*��3\u001b2���\u0004���\u001b9��\bd!\u0013k���t>�\u001bp���~�*����\u0016���8]�N���\"3\u001b\u0017�\u007f\a�t��\nb]}Z'B}Z�Y���3r\u0013o�\n���C��,d�#����3���\n�;T~\"K�\u0004�ŔJ��ݿS@�@!��U��?��\u007fF2,!a}��\u0014�\fd2Z�.2\bI]\u0019��t\t)�׳�\u0001F��,\nendstream\nendobj\n8 0 obj\n<</Filter/FlateDecode/Length 380>>stream\nx�E���e1\fB��!��\u0005�p\u001b��ZHU\u000f{�OV�G3\u0006\u001d�o\b\b0\u0010�8�!�p�\u0013��\u0002���5np�\a<�\t�x�+\u0006\u0018b�1&�b�%VXc���7JT�Ѡ���&!�D�\u001d\u000fx�#\u001e\U000c49fc�%�x�\u001b��|�3_��\u0001�\u001cq�\t�\\p�\u0015��p˂%+�l���w6\u0005\t\u0016��ҁ\u000eu�c��T\u0017�ԕ�u�[=�QOz\u058b^5�P#�5�T\v-��Z\u001bmU�T�Z��!��Ӑa#\u001f\u0011\u001f��G>��O}�K_��7���\u001f��g���\u0003\u000f=��\u0013O���+���օKW�ݸ\u001f�/l\u0006\n\u001c�\v#\a9�Q�s��\\�2W��Mn��<�9/y� Ì2�$�,��*�l�M�2U�4i\u007fE����|���W��\u001e���=�i/z٫^���}�c��ܗ�v�aG\u001dw�i\u0017]v�u7ݟ�W�/�\u000f�w�����\a=Px�\nendstream\nendobj\n4 0 obj\n<</Kids[5 0 R]/Type/Pages/Count 1>>\nendobj\n9 0 obj\n<</Type/Catalog/Pages 4 0 R>>\nendobj\n10 0 obj\n<</ModDate(D:20230803105416+02'00')/CreationDate(D:20230803105416+02'00')/Producer(OpenPDF 1.3.30)>>\nendobj\nxref\n0 11\n0000000000 65535 f \n0000000278 00000 n \n0000000490 00000 n \n0000000015 00000 n \n0000002232 00000 n \n0000000152 00000 n \n0000000796 00000 n \n0000000836 00000 n \n0000001785 00000 n \n0000002283 00000 n \n0000002328 00000 n \ntrailer\n<</Info 10 0 R/ID [<0a7372960da60e096d264a73dd2fa6ed><890828226d5dd8fc6fcd0a55bf5d02c8>]/Root 9 0 R/Size 11>>\nstartxref\n2445\n%%EOF\n"

próba zapisania tego do PDF powoduje powstanie pustego pliku (którego rozmiar to 3 KB) i w podglądzie, np. w notatniku widać dokładnie tę treść, którą przechwycono.
[Label_b3e126cd-20be-4c5f-9e30-5ee9d3fe6296_20230803_110116.PDF](https://github.com/allegro/allegro-api/files/12248978/Label_b3e126cd-20be-4c5f-9e30-5ee9d3fe6296_20230803_110116.PDF)

Próbowałem też użyć opcji ZPL, ale próba tworzenia etykiety jako ZPL zwraca mi:
{"errors":[{"code":"BAD_REQUEST","message":"Opennet cant process label request","details":null,"path":null,"userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}]}
Proszę o podpowiedź, co tu jest nie tak :)

**Comment by AureliuszBrussy** [comment]
@ke-mez wyjaśniam to z zespołem odpowiedzialnym za Wysyłam z Allegro. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Nie udało nam się powtórzyć tego problemu. Wygląda to, jakby zmienione zostało kodowanie znaków podczas zapisywania pliku - co go uszkodziło.

**Comment by ke-mez** [comment]
W takim razie proszę o informację, w jakim kodowaniu otrzymam tę wartość?

**Comment by ke-mez** [comment]
OK, mam na myśli w jakim kodowaniu jest otrzymana tablica bajtów: np. UTF8, Unicode, ASCII? Pytam, bo próbuję to zgadnąć i póki co, ciągle w efekcie dostaję pustego PDF :(

**Comment by ke-mez** [comment]
Nvm, nie było pytania, nie doczytałem :) Zastanawiające jest tylko to, że etykieta pojawia się w formie innej niż na aplikacji producyjnej, ale poproszę o potwierdzenie, to tak ma być?
![image](https://github.com/allegro/allegro-api/assets/141305222/af3b5b3b-45f8-4047-ae64-f803cd60279f)
Mam założyć, że na aplikacji produkcyjnej dostałbym "normalną" wersję etykiety?

**Comment by ke-mez** [comment]
Znalazłem podobne pytanie, wnioskując po [tym](https://github.com/allegro/allegro-api/issues/7402) wątku, chyba można uznać, że jest ok. Proszę wybaczyć nadmiar wiadomości :)

**Comment by ke-mez** [comment]
Mam jeszcze jedno pytanie.

Czy wszystko w porządku ze środowiskiem sandbox?
Próbuję utworzyć etykiety, za każdym razem przy sprawdzeniu statusu dostaję błędy, np.:
"Usługa nie jest dostępna pomiędzy wskazanymi lokalizacjami. The selected service is unavailable between given locations" - adres wysyłki ustawiony na Warszawę, adres odbioru tak samo, adresy zawsze sprawdzam przez https://allegro.pl/kampania/one/kurier/godziny-graniczne żeby się upewnić czy dana usługa jest dostępna.
dostałem też:
"Kod pocztowy nadawcy znajduje się poza obszarem One Kuriera. Sender post code not support next day"
albo w przypadku podania punktu (np. AL014WW1): 
"Problem z nadaniem przesyłki. Spróbuj ponownie później. Route not available for next day."
Mam wrażenie, że jakiekolwiek dane bym nie podał, nie będę w stanie tego przetestować. Mogę poprosić o jakieś wsparcie?

**Comment by AureliuszBrussy** [comment]
@ke-mez postaram się pomóc, natomiast potrzebuję trace-id przykładowych requestów z próbą utworzenia przesyłki.

**Comment by ke-mez** [comment]
Proszę uprzejmie, oto moje przykłady:

1) traceId: a53a422a055d3731
operacja skończyła się błędem: "Usługa nie jest dostępna pomiędzy wskazanymi lokalizacjami. The selected service is unavailable between given locations"

2) traceId: bc1728f4fb1fff5
operacja skończyła się błędem: "Problem z nadaniem przesyłki. Spróbuj ponownie później. Route not available for next day"

z góry dzięki za pomoc ;)

**Comment by AureliuszBrussy** [comment]
Dziękuję, wyjaśniam to, wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
Hej, jeśli chodzi o przesyłki z punktu do punktu to możesz spróbować użyć np.: AL001WA1 jako punkt nadania i AL042PO1 jako punkt doręczenia.
Dla przesyłki z adresu do punktu możesz zrobić np. nadanie z adresu na kodzie 00-016 i doręczenie do punktu AL042PO1.
Dla przesyłki z adresu na adres możecie zrobić np. nadanie z adresu na kodzie 00-016 i doręczenie pod adres na kodzie 60-228.

Postaramy się dodać więcej kodów do puli na środowisku testowym, m.in. te z Twoich przykładowych requestów.

**Comment by ke-mez** [comment]
Dzięki, potestuję :)

**Comment by AureliuszBrussy** [comment]
@ke-mez poprawiliśmy kody pocztowe, które wcześniej użyłeś (w przykładowych requestach), możesz spróbować użyć ich ponownie.
