### ISSUE TITLE
WZA Brak opisów dodatkowych usług

### ISSUE THREAD

**Issue by tomasz3k** [allegro/allegro-api#7442]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Od jakiegoś czasu metoda
"GET": "https://api.allegro.pl.allegrosandbox.pl/parcel-management/delivery-services",
Zarówno na produkcji jak i sandboxie zwraca dla niektórych usług w opcjach dodatkowych puste opisy.

Np
```
"id": "0175efcd-8291-4328-ac41-258f5807b44e#a0cf4004-7e23-4462-9e88-0d0d81b99d9e",
                "service": "POCZTA_POLSKA",
                "name": "Kurier Pocztex (poczta)",
                "owner": "CLIENT",
                "carrierId": "POCZTA_POLSKA",
                "additionalServices": {
                    "cashOnDelivery": {
                        "available": false,
                        "expressAvailable": false
                    },
                    "options": [
                        {
                            "name": "additionalHandling",
                            "description": "Paczka o kształcie, który nie jest prostopadłościanem (np. opona, tuba) lub taka, która jest owinięta stretchem, folią lub innym materiałem utrudniającym przesuwanie."
                        },
                        {
                            "name": "guarantee0800",
                            "description": ""
                        },
                        {
                            "name": "guarantee1200",
                            "description": ""
                        },
                        {
                            "name": "fragile",
                            "description": "Traktowanie przesyłki ze szczególną ostrożnością (przedmioty szklane, łamliwe i kruche, płyny, gazy, itp.)."
                        },
                        {
                            "name": "valuableShipment",
                            "description": "Zadeklarowanie wartości powyżej 100 zł."
                        },
                        {
                            "name": "deliveryConfirmation",
                            "description": ""
                        },
                        {
                            "name": "deliveryAfter1700",
                            "description": ""
                        }
                    ]
                }
```
Rozwiązałem tymczasowo problem podając jako opis nazwę usługi ale dla klienta może to być rażące.

**Comment by AureliuszBrussy** [comment]
Ze względu na pewne ograniczenia - obecnie zwracamy opisy tylko dla usług dodatkowych, których nazwy mogą budzić wątpliwość. Tam gdzie ich brakuje - pozostaje samodzielne ich opisanie. 

Wszystkie możliwe na ten moment usługi dodatkowe: 

- additionalHandling - Przesyłka niestandardowa
- returnOfDocuments - Dokumenty zwrotne
- collectionUponDelivery - Przesyłka zwrotna
- guarantee0930 - Doręczenie do 09:30
- guarantee1200 - Doręczenie do 12:00
- guaranteeNextDay - Doręczenie w następnym dniu roboczym
- saturdayDelivery - Doręczenie w sobotę
- privateShipping - Doręczenie do osoby prywatnej
- documentsSupply - Dostarczenie dokumentów przewozowych przez kuriera
- sendingAtPoint - Nadanie w punkcie
- personalDelivery - Doręczenie do rąk własnych
- smsPredeliveryInformation - Awizo SMS
- saturdaySundayDelivery - Doręczenie w weekend
- guarantee0800 - Doręczenie do 08:00
- fragile - Usługa "Ostrożnie"
- valuableShipment - Przesyłka wartościowa
- registeredCompanyLetter - Przesyłka polecona firmowa
- deliveryConfirmation - Potwierdzenie doręczenia przesyłki
- deliveryAfter1700 - Doręczenie po 17:00

**Comment by TimothyKoval** [comment]
Kolejny żart...

**Comment by tomasz3k** [comment]
> Ze względu na pewne ograniczenia - obecnie zwracamy opisy tylko dla usług dodatkowych, których nazwy mogą budzić wątpliwość. Tam gdzie ich brakuje - pozostaje samodzielne ich opisanie.
> 
> Wszystkie możliwe na ten moment usługi dodatkowe:
> 
> * additionalHandling - Przesyłka niestandardowa
> * returnOfDocuments - Dokumenty zwrotne
> * collectionUponDelivery - Przesyłka zwrotna
> * guarantee0930 - Doręczenie do 09:30
> * guarantee1200 - Doręczenie do 12:00
> * guaranteeNextDay - Doręczenie w następnym dniu roboczym
> * saturdayDelivery - Doręczenie w sobotę
> * privateShipping - Doręczenie do osoby prywatnej
> * documentsSupply - Dostarczenie dokumentów przewozowych przez kuriera
> * sendingAtPoint - Nadanie w punkcie
> * personalDelivery - Doręczenie do rąk własnych
> * smsPredeliveryInformation - Awizo SMS
> * saturdaySundayDelivery - Doręczenie w weekend
> * guarantee0800 - Doręczenie do 08:00
> * fragile - Usługa "Ostrożnie"
> * valuableShipment - Przesyłka wartościowa
> * registeredCompanyLetter - Przesyłka polecona firmowa
> * deliveryConfirmation - Potwierdzenie doręczenia przesyłki
> * deliveryAfter1700 - Doręczenie po 17:00

Dziękuję. Działa ;-)
![image](https://github.com/allegro/allegro-api/assets/1394451/488f4fbf-424a-436a-b0df-b1d0444bf9b9)
