### ISSUE TITLE
Błąd przy pobieraniu produktu

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#7443]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam,
pobierając pewne starsze produkty występuje następujący błąd:
```
{
    "errors": [
        {
            "code": "NotFoundException",
            "message": "Not Found",
            "details": null,
            "path": null,
            "userMessage": "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."
        }
    ]
}
```

I o ile rozumiem błąd 404, że produktu nie znaleziono tak komunikat już jest mniej jasny. Źle odpytuje? Może brakuje jakiegoś nagłówka?

Czy mam traktować to jako, że produkt po prostu został usunięty?

Trace-Id: da095c6da6fdbe41

**Comment by AureliuszBrussy** [comment]
Ten błąd oznacza, że odpytywany zasób nie istnieje. Jest więc dokładnie tak, jak się domyślasz - produkt o tym id aktualnie nie istnieje.
