### ISSUE TITLE
Własny parametr

### ISSUE THREAD

**Issue by Axlii50** [allegro/allegro-api#7445]
Dzień dobry
chciał bym zapytać w jaki sposób mogę dodać własne paramtery do oferty przy jej wystawianiu ze względu ze w api allegro na stronie nie widnieje żaden sposób

**Comment by Axlii50** [comment]
Lub w jaki sposób mógł bym dołączyć pole zawierające EAN

**Comment by MaciejFrackowiak** [comment]
W API nie obsługujemy parametrów własnych. Parametr EAN (GTIN) może być przekazany wyłącznie w parametrze o id=225693.

**Comment by Axlii50** [comment]
Czyli po prostu przysłowiowo moge dokleić parametr o id 225693 wraz z wartoscią EAN i allegro to przyjmie?
oraz czy bede w stanie jakos sprawdzić ?

**Comment by MaciejFrackowiak** [comment]
Nie, w większości kategorii Allegro parametr EAN (GTIN) występuje pod id=225693. Jeżeli w kategorii, w której wystawiasz produkt dostępny jest taki parametr to wartość EAN powinienneś podać wyłącznie w nim.

**Comment by Axlii50** [comment]
a jeżeli takowy parametr normalnie nie występuje i nie jest pozyskiwany za pomocą  https://api.{environment}/sale/categories/{categoryId}/parameters

**Comment by MaciejFrackowiak** [comment]
To nie ma możliwości jego wprowadzenia jak wspomniałem w pierwszej odpowiedzi.

**Comment by Axlii50** [comment]
dziękuje bardzo za pomoc
