### ISSUE TITLE
Tytuł Twojej oferty lub jej dalszy opis może wprowadzać w błąd co do pochodzenia towaru, jego producenta lub marki i tym samym naruszać prawa firmy, która współpracuje z nami w ramach programu Współpraca w Ochronie Praw. W opisie Twoich ofert używasz zarejestrowanego słownego znaku towarowego w celu sprzedaży produktu innej marki (widocznej w sekcji ‘Parametry’). Wystawienie: wystąpił błąd

### ISSUE THREAD

**Issue by ZildijanEU** [allegro/allegro-api#7446]
_"Tytuł Twojej oferty lub jej dalszy opis może wprowadzać w błąd co do pochodzenia towaru, jego producenta lub marki i tym samym naruszać prawa firmy, która współpracuje z nami w ramach programu Współpraca w Ochronie Praw. W opisie Twoich ofert używasz zarejestrowanego słownego znaku towarowego w celu sprzedaży produktu innej marki (widocznej w sekcji ‘Parametry’).
Wystawienie: wystąpił błąd ..."_

Bardzo proszę o usunięcie tej weryfikacji po stronie allegro. 

Ona jest zupełnie bezsensowna, ponieważ niedokładnie sprawdza faktyczne naruszenia przez użytkownika allegro.
Często bywa tak, że producenci nazywają swoje produkty podobnie do nazw innych firm, które współpracują z allegro w ochronie praw.
Sprzedawcy zazwyczaj zamieszczają w tytule i parametrach allegro markę, oraz nazwę produktu. 
To daje fałszywe wrażenie, że zostało naruszone prawo zarejestrowanej nazwy innej marki.

Ta niedopracowana funkcja allegro działająca w tle jest szkodliwa dla sprzedawców, ponieważ ostatnio często hurtowo usuwa oferty, które są poprawne i nie powinny być usunięte. 

Dodatkowo uniemożliwia wystawiania nowych ofert, a nawet jeśli się za którymś razem uda, to po chwili są usuwane. 

**Przykładem jest produkt: MERRELL SPEED ECCO Męskie Buty**
W parametrach jest podana marka Merrell.
W tytule jest podana nazwa modelu ECCO. 
O tej samej nazwie jak model występuje również wartość parametru allegro "marka" = ECCO
W stworzonym produkcie w katalogu allegro jest np. Merrell Buty trekkingowe Merrell Speed Ecco r. 41
Wynikiem tego jest brak możliwości wystawienia takiej oferty.

**PROPOZYCJA**
Ograniczenie tej funkcji jedynie do dopasowania tytułu do wartości parametru marka tzn.
- w tytule jest MERRELL, a w parametrze jest Merrell = OK 
- w tytule jest MERRELL ECCO EDEN VIKING HEAD, a w parametrze marka jest Merrell = OK
(ECCO EDEN VIKING HEAD występują w parametrze marka, ale to, że występuje coś jeszcze poza dopasowanym Merrell nie powinno mieć znaczenia)

Jak można zauważyć, niektóre nazwy marek biorą się z życia, tak samo jak nazwy produktów, więc to normalne, że nazwy produktów mogą być takie same jak nazwy innych marek, dlatego liczę na mądrość programistów allegro w tej sprawie i poprawienie tego uprzykrzającej sprzedającym funkcji w tle stworzonej dla allegro i działającej jak na razie na szkodę sprzedawców.

**Comment by MaciejFrackowiak** [comment]
Mechanizm, o którym wspominasz działa zarówno w API, jak i w serwisie WWW. W związku z tym swoje spostrzeżenia proszę przekaż bezpośrednio poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) Allegro.
