### ISSUE TITLE
WZA Błędny Numer śledzenia przesyłek UPS

### ISSUE THREAD

**Issue by tomasz3k** [allegro/allegro-api#7448]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam,
Klient zwrócił mi uwagę na fakt iż moja integracja źle pobiera nr listu śledzenia przesyłki UPS.
Przesyłka jest tworzona poprawnie wg dokumentacji API, a nr listu jaki jest zwracany w polu waybill to A00013D9K8
Według klienta nr listu powinien być dłuższy i odpowiadać tracking # na etykiecie
![image](https://github.com/allegro/allegro-api/assets/1394451/0cb3760a-64ea-4b93-aa8b-8e558518406d)

  "trace-id": "43ca4ff6ac2833e4" // produkcja

**Comment by MaciejFrackowiak** [comment]
Numer listu przewozowego to A00013D9K8 - jest to przesyłka Allegro One. Korzystając z [GET /order/carriers/{carrierId}/tracking](https://developer.allegro.pl/documentation/#operation/getParcelTrackingUsingGET) uzyskasz aktualny stan przesyłki.

**Comment by tomasz3k** [comment]
Czyli nie da się jej śledzić na stronie ups?

**Comment by MaciejFrackowiak** [comment]
Nie.

**Comment by tomasz3k** [comment]
Dziękuję

**Comment by tomasz3k** [comment]
Mam jeszcze pytanie odnośnie tego samego,
Czy jest jakiś sposób by uzyskać nr listu UPS zamiast Allegrowego odnośnie przesyłek Allegro ONE? Zapewne macie to po swojej stronie i możnaby tylko udostępnić nr gdzieś w odpowiedzi API. 
Jest to na tyle problematyczne, że klienci skanują etykiety i w systemie powinni zobaczyć co w danej paczce powinno się znaleźć, a  niestety nie można powiązać w ten sposób etykiety z zamówieniem i cały proces staje w miejscu.

**Comment by Lukasz-Zurek** [comment]
@tomasz3k Niestety takiego sposobu po stronie naszego API nie ma. Zwracamy wyłącznie numery przesyłek Allegro One.

**Comment by tomasz3k** [comment]
Pytanie następujące, jak rozróżnić czy dana przesyłka jest Allegro One dostarczana przez UPS? Tzn ta, która ma inny numer śledzenia niż ten przewoźnika? Muszę wprowadzić dodatkowy kod kreskowy na tej etykiecie z waszym numerem przesyłki i potrzebuję mieć 100% pewności jak ją rozróżnić wśród innych etykiet.

**Comment by MaciejFrackowiak** [comment]
To zależy jaka jest wybrana metoda dostawy - czy ma dopisek One Kurier. Szczegółowo opisane jest to w [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/allegro-one/allegro-one-informacje-dla-sprzedajacych-2YVLlRloquD#jakie-sa-metody-dostawy-allegro-one).

**Comment by tomasz3k** [comment]
Z tego co tam czytam to UPS różni się od Allegro One Kurier.
![image](https://github.com/allegro/allegro-api/assets/1394451/59ef53e1-af23-4a38-b15c-b2a39968579e)
I z opisu wynika iż ups nie dostarcza na adres klienta. Chciałem wygenerować taką etykietę na swoim koncie ale mam ciągle etykietę z allegro one, a nie te z UPS. Natomiast klient na swoim koncie widzi już etykietę UPS i to z dostawą do domu. NIe rozumiem tego kompletnie kiedy zwracana jest etykieta UPS a kiedy Allegro One.

**Comment by MaciejFrackowiak** [comment]
Proszę wskaż mi przykładowe id zamówienia, z którym masz problem.

**Comment by tomasz3k** [comment]
eb244790-473b-11ee-a697-d70312396ca4
5aa2d480-473a-11ee-a697-d70312396ca4
to sandbox
w obu przypadkach na etykiecie jest allegro one zamiast ups

**Comment by MaciejFrackowiak** [comment]
I jest to prawidłowe, oba zamówienia dot. przesyłek obsługiwanych przez One Kurier:
1. Allegro One Kurier - dostawa jutro,
2. Allegro One Box, One Kurier.
