### ISSUE TITLE
Jak znaleźć numer przesyłki znajdujący się na kodzie kreskowym?

### ISSUE THREAD

**Issue by daniel93333** [allegro/allegro-api#7449]
Mam taki problem że pakuje paczki za pomocą skanowania kody kreskowego na etykiecie za pomocą którego znajduje konkretne zamówienie.
Problem w tym, że przesyłki allegro one mają inny numer przesyłki niż kod kreskowy na etykiecie - dlatego że przesyłki allegro obsługuje UPS.

W jaki sposób otrzymać numer przesyłki jaki jest na kodzie kreskowym?

**Comment by Lukasz-Zurek** [comment]
W przypadku paczek Allegro One zwracamy wyłącznie unikalne dla nich numery przesyłek, których nie można śledzić w UPS.

**Comment by daniel93333** [comment]
To w jaki inny sposób mają etykietę allegro one w ręce mogę znaleźć odpowiadające tej etykiecie zamówienie na allegro? 
Nie potrzebuje śledzić tej etykiety na UPS, chcę zapakować zamówienie...

**Comment by Lukasz-Zurek** [comment]
Na etapie tworzenia etykiety kończy się nasza rola w kontekście API, w związku z czym nie jestem w stanie pomóc Tobie w tym konkretnym przypadku. Dodam, że nie mamy wiedzy na temat używanego narzędzia/aplikacji. Normalne flow w naszym API polega na pobraniu danych zamówienia, nadania przesyłki poprzez wskazanie danych Klienta (w tym odpowiedniego zahashowanego maila identyfikującego zamówienie) oraz utworzenie etykiety.

**Comment by daniel93333** [comment]
Wystarczającym rozwiązaniem byłoby dodatkowe pole w API, które zawierało by informacje o numerze  przesyłki jaki jest zawarty w kodzie kreskowym na etykiecie.
