### ISSUE TITLE
Problemy z publikacją

### ISSUE THREAD

**Issue by mapsi-fixi** [allegro/allegro-api#745]
Nie można opublikować żadnej aukcji na sandbox, nieważny czy poprzez api, czy poprzez administrację alllegro

**Comment by PawelTaberski** [comment]
Przetestowałem i rzeczywiście jest jakiś problem, sprawę zgłosiłem do odpowiedniego zespołu proszę o cierpliwość.

**Comment by mapsi-fixi** [comment]
Wygląda na działające, natomiast jest również problem ze złożeniem zamówienia. Wyświetla się komunikat "Nie udało się kupić przedmiotu" sprawdzałem jako zalogowany i niezalogowany uzytkownik

**Comment by PawelTaberski** [comment]
Rzeczywiście jest jakiś problem z kupowaniem sprawę już zgłosiłem do rozwiązania. Proszę o cierpliwość.
