### ISSUE TITLE
Is it possible to upload delivery prices for each products through Allegro API?

### ISSUE THREAD

**Issue by EugenBodanov** [allegro/allegro-api#7451]

**Comment by Lukasz-Zurek** [comment]
If you mean - editing shipping price lists in many offers (up to 1000 offers) - you can do it via [PUT /sale/offer-modification-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/modificationCommandUsingPUT). You can read more about it in [our guide](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#shipping-price-list).

Obviously you can manage your shipping rates by using our resources. We described them in [another guide.](https://developer.allegro.pl/tutorials/account-and-user-data-management-jn9vBjqjnsw#delivery-settings-and-shipping-rates).

**Comment by Lukasz-Zurek** [comment]
You should not provide a shipping cost in the **delivery.shippingRates.id** field. You should provide shipping price list ID which you can retrieve by via [GET /sale/shipping-rates]([GET /sale/shipping-rates](https://developer.allegro.pl/documentation/#operation/getListOfShippingRatestUsingGET)).

I've sent you our guides where everything is described closely, together with sample requests.

**Comment by EugenBodanov** [comment]
Is it possible simply provide the exact shipping cost for each product?

**Comment by Lukasz-Zurek** [comment]
You can do it only by creating separated shipping rates via [POST /sale/shipping-rates](https://developer.allegro.pl/documentation/#operation/createShippingRatesSetUsingPOST) and assigning them to the offers. You will find more information right [here](https://developer.allegro.pl/news/nowe-zasoby-zarzadzaj-cennikami-dostawy-aMDnG7zamSX#create).

**Comment by EugenBodanov** [comment]
I changed my code:     
def get_shipping_rate_id_by_pricelist(self, pricelist_name: str) -> str:
        endpoint = "/sale/shipping-rates"
        response = self.make_request(endpoint, method="GET")
        if response.status_code == 200:
            rates = response.json().get('shippingRates', [])

            for rate in rates:
                if rate.get('name') == pricelist_name:
                    return rate['id']

            print(f"Price list {pricelist_name} not found in shipping rates.")
            return None
        else:
            print(f"Failed to fetch shipping rates. Response: {response.json()}")
            return None

    def select_shipping_pricelist(self, weight, height=None, width=None, depth=None):
        # Определение прайс-листа доставки на основе веса и габаритов
        if weight <= 1:
            return 'MIP-EXTRA-SMALL-0-1-KG'
        elif weight <= 5:
            return 'MIP-SMALL-1-5-KG'
        elif weight <= 15:
            return 'MIP-MEDIUM-5-15-KG'
        elif weight <= 28:
            return 'MIP-LARGE-15-28-KG'
        elif weight <= 40:
            return 'MIP-X-LARGE-28-40-KG'
        elif weight <= 60:
            return 'MIP-XX-LARGE-40-60-KG'
        else:
            return 'MIP-XXX-LARGE-60-100-KG'

    def update_shipping_cost(self, offer_id, shipping_rate_id):
        command_id = str(uuid.uuid4())
        endpoint = f"/sale/offer-modification-commands/{command_id}"
        payload = {
            "modification": {
                "delivery": {
                    "shippingRates": {
                        "id": shipping_rate_id
                    }
                }
            },
            "offerCriteria": [
                {
                    "type": "CONTAINS_OFFERS",
                    "offers": [
                        {
                            "id": offer_id
                        }
                    ]
                }
            ]
        }
        response = self.make_request(endpoint, method="PUT", data=payload)
        print(shipping_rate_id)

        # Проверка и обработка ответа от сервера
        if response.status_code != 200:
            # обработать ошибку
            print(f"Failed to update shipping cost for offer {offer_id}. Response: {response.json()}")

    def update_all_shipping_costs(self):
        with open('products.json', 'r') as products_file:
            products = json.load(products_file)

        processed_mapping = {}
        with open('processed_products.json', 'r') as processed_file:
            processed_products = json.load(processed_file)
            processed_mapping = {product['sku']: product for product in processed_products}

        update_count = 0

        for product in products:
            if update_count >= 10:
                break

            # Если у продукта нет SKU, пропускаем его
            if 'external' not in product or 'id' not in product['external']:
                continue

            # Используйте SKU для поиска в processed_mapping.
            processed_product = processed_mapping.get(product['external']['id'])

            if not processed_product:
                print(f"Processed data not found for product ID {product['id']}")
                continue

            weight = processed_product.get('weight')
            height = processed_product.get('height')
            width = processed_product.get('width')
            depth = processed_product.get('depth')

            # По весу и габаритам выбираем подходящий прайс-лист доставки
            pricelist_id = self.select_shipping_pricelist(weight, height, width, depth)

            # Получение shipping rate ID на основе выбранного прайс-листа
            shipping_rate_id = self.get_shipping_rate_id_by_pricelist(pricelist_id)

            if not shipping_rate_id:
                print(f"Couldn't find shipping rate ID for pricelist {pricelist_id}")
                continue

            self.update_shipping_cost(product['id'], shipping_rate_id)
            print(processed_product.get("sku"))
            update_count += 1
but I still get this error messages:
Failed to update shipping cost for offer 14136360280. Response: {'id': '6e21cfce-2333-42c8-b4dd-3f468f9ae179', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
S7168234
00c67a4e-d1c7-4a26-8a3b-4200dcf9c55a
Failed to update shipping cost for offer 14136322448. Response: {'id': '70d06f7b-d4a5-43dd-aa6c-7eb9f79ef4ce', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
S8416059
00c67a4e-d1c7-4a26-8a3b-4200dcf9c55a
Failed to update shipping cost for offer 14136322382. Response: {'id': '3d44935d-d6de-47f1-b351-226157e681a4', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
S7817377

**Comment by Lukasz-Zurek** [comment]
Please send me your request in json format. I have checked your commandIds and they have been all succesfully processed. You can check the details by using GET sale/offer-modification-commands/3d44935d-d6de-47f1-b351-226157e681a4/tasks (for example).

**Comment by EugenBodanov** [comment]
thanks for your help, I found the error
