### ISSUE TITLE
Dwie metody dostawy o tej samej nazwie

### ISSUE THREAD

**Issue by akonopka11** [allegro/allegro-api#7453]
Witam,

Pobieramy metody dostawy z endpointu parcel-management/delivery-services (konto produkcyjne). Jeśli chodzi o DHL Czechy mamy takie metody jak poniżej. "Allegro Kurier DHL Czechy" występuje dwa razy z dwoma różnymi ID. Przypuszczam, że chodzi o dwie różne metody dostawy jakie są widoczne w BaseLinkerze, a mianowicie "Allegro: Allegro Kurier DHL Czechy" i "Allegro: Allegro Kurier DHL Czechy (allegro.cz)", ale nie mamy jak tych metod odróżnić. Oprócz tego w BL mamy jeszcze tylko "Allegro: Allegro Kurier DHL Czechy pobranie (allegro.cz)", to by mogło odpowiadać tej metodzie w Allegro o ID 61 ("Allegro Kurier DHL Czechy pobranie").

Chcemy generować sami etykiety przez API Allegro, nie korzystając z rozwiązań BL, ale w momencie jak tak to wygląda, nie wiemy, którą metodę wybrać.

Proszę o pomoc

[59] => Array
                (
                    [id] => ...
                    [service] => DHL
                    [name] => Allegro Kurier DHL Czechy
                    [owner] => ALLEGRO
                    [carrierId] => DHL
                    [additionalServices] => Array
                        (
                            [cashOnDelivery] => Array
                                (
                                    [available] => 
                                    [expressAvailable] => 
                                )

                            [options] => Array
                                (
                                    [0] => Array
                                        (
                                            [name] => additionalHandling
                                            [description] => Paczka o kształcie, który nie jest prostopadłościanem (np. opona, tuba) lub taka, która jest owinięta stretchem, folią lub innym materiałem utrudniającym przesuwanie.
                                        )

                                    [1] => Array
                                        (
                                            [name] => smsPredeliveryInformation
                                            [description] => Powiadomienie do odbiorcy o terminie doręczenia przesyłki.
                                        )

                                )

                        )

                )

            [60] => Array
                (
                    [id] => ...
                    [service] => DHL
                    [name] => Allegro Kurier DHL Czechy
                    [owner] => ALLEGRO
                    [carrierId] => DHL
                    [additionalServices] => Array
                        (
                            [cashOnDelivery] => Array
                                (
                                    [available] => 
                                    [expressAvailable] => 
                                )

                            [options] => Array
                                (
                                    [0] => Array
                                        (
                                            [name] => additionalHandling
                                            [description] => Paczka o kształcie, który nie jest prostopadłościanem (np. opona, tuba) lub taka, która jest owinięta stretchem, folią lub innym materiałem utrudniającym przesuwanie.
                                        )

                                    [1] => Array
                                        (
                                            [name] => smsPredeliveryInformation
                                            [description] => Powiadomienie do odbiorcy o terminie doręczenia przesyłki.
                                        )

                                )

                        )

                )

            [61] => Array
                (
                    [id] => ..
                    [service] => DHL
                    [name] => Allegro Kurier DHL Czechy pobranie
                    [owner] => ALLEGRO
                    [carrierId] => DHL
                    [additionalServices] => Array
                        (
                            [cashOnDelivery] => Array
                                (
                                    [available] => 1
                                    [expressAvailable] => 
                                )

                            [options] => Array
                                (
                                    [0] => Array
                                        (
                                            [name] => additionalHandling
                                            [description] => Paczka o kształcie, który nie jest prostopadłościanem (np. opona, tuba) lub taka, która jest owinięta stretchem, folią lub innym materiałem utrudniającym przesuwanie.
                                        )

                                    [1] => Array
                                        (
                                            [name] => smsPredeliveryInformation
                                            [description] => Powiadomienie do odbiorcy o terminie doręczenia przesyłki.
                                        )

                                )

                        )

                )

**Comment by MaciejFrackowiak** [comment]
Nie musisz tego rozróżniać - w szczegółach zamówienia, dla którego generujesz etykietę otrzymujesz wybraną konkretną metodę dostawy - i właśnie nadając przesykę tę wybraną metodę dostawy musisz podstawić jako serviceId.

**Comment by akonopka11** [comment]
Dziękuję, rzeczywiście, robię coś tutaj na około. Super!
