### ISSUE TITLE
Czy istnieje sposób na sprawdzenie czy API działa czy nie?

### ISSUE THREAD

**Issue by RHaziak** [allegro/allegro-api#7454]
Dzień dobry!

Chciałem się spytać czy istnieje jakaś strona/sposób na sprawdzenie statusu systemu waszego API, ze szczególnym uwzględnieniem AllegroOne? Ostatnio dość często dostajemy informacje o komunikcie 
API przewoźnika jest tymczasowo niedostępne. Ponów próbę później.

Aby dać jakiś przykład o co mi chodzi to pierwsze na myśl mi przychodzi strona: https://discordstatus.com/

Pozwoliło by nam to na wyeliminowanie problemu z naszym oprogramowaniem od razu, bez potrzeby spędzania czasu nad danym problemem zbyt długo :D

**Comment by MaciejFrackowiak** [comment]
Nie, na ma obecnie takiej strony. Zwracanie statusów działania zasobów API Allegro to jedno, jednak działanie konkretnych przewoźników to już kwestia poza nami - pamiętaj proszę, że są to podmioty trzecie, które mają własny flow działania i od których również my jesteśmy uzależnieni.

**Comment by hahyes** [comment]
@RHaziak Jakimś źródłem informacji jest: https://status.baselinker.com/
Jako integrator usług wysyłki też informują o problemach z różnymi dostawcami, w tym Allegro.

**Comment by RHaziak** [comment]
Dzięki za szybkie info, @MaciejFrackowiak oraz @hahyes!
Już ten link od baselinkera dużo pomoże :D

**Comment by wap18** [comment]
@MaciejFrackowiak 
zgodnie z informacją z BL występują problemy z API Allegro do tworzenia etykiet przy pomocy WzA, czy jest Pan w stanie potwierdzić tę informację? Kiedy problem zostanie rozwiązany? 
![BaseLinker-Status](https://github.com/allegro/allegro-api/assets/40720743/9182f8fe-a97c-42b1-beff-22c9ae9b9342)

**Comment by MaciejFrackowiak** [comment]
@RHaziak @wap18 Problem udało nam się wyeliminować. Przepraszamy za niedogodności.
