### ISSUE TITLE
Różnice w danych statystycznych panel Allegro vs API

### ISSUE THREAD

**Issue by macest77** [allegro/allegro-api#7455]
Witam,
zauważamy różnice w danych otrzymywanych poprzez 
https://api.{environment}/advertising-agencies/clients/{id}/statistics
- dla reklam graficznych koszt zawsze różni się nieznacznie, dlaczego?

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
[Ta kategoria](https://allegro.pl/pomoc/kontakt?kategoria=76428715-3f41-46f3-ab54-23a87576aae0) najlepiej pasuje.
