### ISSUE TITLE
Opłata za udostępnianie metody płatności Allegro Pay jaka metoda REST?

### ISSUE THREAD

**Issue by ricarderobl** [allegro/allegro-api#7456]
Jaka metoda w REST umożliwia pobranie informacji o zamówieniu czy kupujący wybrał metodę płatności z użyciem Allegro Pay?

**Comment by MartaNowaczyk** [comment]
Nie zwracamy w naszym API takiej informacji. Wszystkie możliwe typy płatności znajdziesz w [dokumentacji](https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET):

"CASH_ON_DELIVERY"
"WIRE_TRANSFER"
"ONLINE"
"SPLIT_PAYMENT"
"EXTENDED_TERM"

**Comment by ricarderobl** [comment]
To w jaki sposób mam sprawdzić czy opłata na billingu o nazwie "Opłata za udostępnienie metody płatności Allegro Pay" została poprawnie naliczona?

**Comment by MartaNowaczyk** [comment]
Tak jak pisałam, nie ma takiej informacji w zamówieniach, jednak w historii operacji billingowych dla [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries) powinieneś dostać informację o zamówieniu, którego dotyczy ta opłata, a to jest równoważne z tym, jak oznaczone by było zamówienie. Jeśli chcesz zgłosić sugestię zmiany, zapraszamy do zakładki [Discussions](https://github.com/allegro/allegro-api/discussions).

**Comment by ricarderobl** [comment]
Jak można wprowadzać opłatę bez możliwości jej jakiejkolwiek weryfikacji? Billing nie jest miejscem do weryfikacji, a rachunkiem. Czyli najpierw jest wykonywana usługa X i wtedy jest wystawiany rachunek Y. A nie jest wystawiany rachunek Y by dowiedzieć się, że wykonano usługę X.

Przykładowo zamawiając usługę zmiany opon wiemy co zlecamy i na tej podstawie otrzymujemy rachunek za zmianę opon. **Aktualnie natomiast Allegro zrobiło, że samochód trafia na warsztat, nie ma zlecenia jakie naprawy należy wykonać, a Allegro wystawia rachunek i mówi, że w samochodzie była zmieniana żarówka.** Jak niby wtedy jest to poprawne, skoro nie jesteśmy w stanie sprawdzić, czy faktycznie zlecaliśmy wymianę żarówki?

Są Państwo całkowicie nieprofesjonalni, taka jest niestety prawda.

**Comment by MartaNowaczyk** [comment]
Dziękuję za wyjaśnienie i dodanie wątku w sugestiach zmian. Wszelkie zapotrzebowania z zakładki Discussions są zgłaszane do odpowiednich zespołów do rozpatrzenia. Im większe zainteresowanie daną zmianą tym lepiej, także zachęcam również innych użytkowników forum do zgłaszania takiego zapotrzebowania przez głosowania na zmianę i wypowiedzi w [wątku](https://github.com/allegro/allegro-api/discussions/7460).
