### ISSUE TITLE
Błędy przy tworzeniu listów przewozowych

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#7457]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

Dzień Dobry, przy niektórych próbach tworzenia listów przewozowych otrzymujemy komunikat Nie udało się utworzyć nowego listu.Info api allegro: 'API przewoźnika jest tymczasowo niedostępne. Ponów próbę później. [Carrier Api Client is temporary unavailable - try again later or report problem]'

Czy trwa aktualnie jakaś awaria?

**Comment by hahyes** [comment]
@Maciej-Wilkosz Tak, trwa awaria od 6 godzin i nie zapowiada się na rychłe jej zakończenie.

**Comment by MaciejFrackowiak** [comment]
Problem udało nam się wyeliminować. Przepraszamy za niedogodności.
