### ISSUE TITLE
Etykieta w formacie ZPL

### ISSUE THREAD

**Issue by jpulkiewicz** [allegro/allegro-api#7458]
Witam,
Generuje i odbieram poprawnie etykiety PDF, mam natomiast problem z pobraniem etykiety w formacie ZPL.
W create-parcel napewno mam "fileFormat":"ZPL" i paczka jest utworzona poprawnie, 
wysylajac request do /parcel-management/parcels/label otrzymuje bad-request

------paczka--------
Method: GET, RequestUri: 'https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/bf6c4015-2f6b-44a8-b21e-6c32ea1320bd', Version: 1.1, Content: <null>, Headers:
{
  Accept: application/vnd.allegro.public.v1+json
  Authorization: Bearer ...(token usuniety)...
}

Response:
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-store, must-revalidate, no-cache, max-age=0
  x-xss-protection: 1; mode=block
  Pragma: no-cache
  X-Frame-Options: DENY
  trace-id: 47b6cf864ab14495
  Date: Mon, 07 Aug 2023 15:04:56 GMT
  X-Content-Type-Options: nosniff
  Strict-Transport-Security: max-age=31536000 ; includeSubDomains
  Expires: 0
  Content-Type: application/vnd.allegro.public.v1+json
  Content-Length: 126
}
{"id":"bf6c4015-2f6b-44a8-b21e-6c32ea1320bd","parcelId":"e098170d-43d5-49cc-8937-494c24b55e78","status":"SUCCESS","errors":[]}

----------etykieta-----------
Request:
Method: GET, RequestUri: 'https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcels/label?parcelId=e098170d-43d5-49cc-8937-494c24b55e78', Version: 1.1, Content: <null>, Headers:
{
  Authorization: Bearer ...(token usuniety)...
  Accept: application/pdf
  Accept: text/plain
  Accept: */*
}

Response:
StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-store, must-revalidate, no-cache, max-age=0
  x-xss-protection: 1; mode=block
  Pragma: no-cache
  X-Frame-Options: DENY
  trace-id: 57bded7386d9088b
  Date: Mon, 07 Aug 2023 15:04:56 GMT
  X-Content-Type-Options: nosniff
  Strict-Transport-Security: max-age=31536000 ; includeSubDomains
  Expires: 0
  Content-Type: application/vnd.allegro.public.v1+json
  Content-Length: 207
}
{"errors":[{"code":"BAD_REQUEST","message":"Opennet cant process label request","details":null,"path":null,"userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}]}

------------------------------

Pytanie oczywiscie czy igdzie jest blad.
Pozdrawiam
J.Pulkiewicz

**Comment by Bober95** [comment]
Nie wiem czy ma to znaczenie ale podajesz wszystkie możliwe wartości:
`Accept: application/pdf
Accept: text/plain
Accept: /`
Spróbuj tylko dla jednego

**Comment by jpulkiewicz** [comment]
@Bober95 Probowalem kazda wartosc z osobna - bez efektu, ale dzieki za sluszne spstrzezenie

**Comment by MaciejFrackowiak** [comment]
@jpulkiewicz Przygotuj proszę nową przesyłkę i spróbuj pobrać dla niej etykietę. Wczoraj mieliśmy problemy techniczne z usługą Allegro One, które mogły rzutować również na działanie usługi na Sandbox.

**Comment by jpulkiewicz** [comment]
@MaciejFrackowiak 
Blad wystapil rowniez w nowej przesylce tj.:

{"id":"baf2bf97-6626-427e-953b-81e8e76f28f7","parcelId":"df64c28d-abff-43b4-a450-6f50ca7dabe6","status":"SUCCESS","errors":[]}

Request:
Method: GET, RequestUri: 'https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcels/label?parcelId=df64c28d-abff-43b4-a450-6f50ca7dabe6', Version: 1.1, Content: <null>, Headers:
{
  Authorization: Bearer <token byl tutaj>
  Accept: */*
}

Response:
StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-store, must-revalidate, no-cache, max-age=0
  x-xss-protection: 1; mode=block
  Pragma: no-cache
  X-Frame-Options: DENY
  trace-id: 119bdbc4c4ee070a
  Date: Tue, 08 Aug 2023 10:13:49 GMT
  X-Content-Type-Options: nosniff
  Strict-Transport-Security: max-age=31536000 ; includeSubDomains
  Expires: 0
  Content-Type: application/vnd.allegro.public.v1+json
  Content-Length: 207
}
{"errors":[{"code":"BAD_REQUEST","message":"Opennet cant process label request","details":null,"path":null,"userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}]}

**Comment by MaciejFrackowiak** [comment]
Skonsultowałem przypadek z zespołem odpowiedzialnym za usługę - niestety, na Sandbox etykiety w formacie ZPL dla przesyłek UPS nie są generowane, możesz otrzymać etykietę tylko w formacie .pdf.

**Comment by jpulkiewicz** [comment]
Dzieki.
Rozumiem, ze w produkcji dostane etykiete zpl bez problemu?

**Comment by MaciejFrackowiak** [comment]
Oczywiście tak.

**Comment by jpulkiewicz** [comment]
Mam jeszcze jedno pytanie jaka wartosc naglowka Accept bedzie prawidlowa dla ZPL?

**Comment by MaciejFrackowiak** [comment]
"text/plain".

**Comment by jpulkiewicz** [comment]
Wielkie dzieki. Pozdrawiam.
