### ISSUE TITLE
Jak w sale/product-offers PATCHEM dodać customParameters do oferty?

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#7459]
Dzień dobry,
Mam problem jak w tytule.
Próbuję uzupełnić customParameters,
Ale w odpowiedzi ciągle dostaję ten sam json oferty bez uzupełnionych customParameters.
Szukałem wszędzie, i nigdzie nie mogę znaleźć jak to można zrobić.
Wysyłam customParameters w ten sposób:

curl_exec(https://allegroapi.io/sale/product-offers/14109895017
Array
(
    [0] => Content-Type: application/vnd.allegro.public.v1+json
    [1] => Accept: application/vnd.allegro.public.v1+json
)
PATCH {"customParameters":[{"name":"Rozmiar","values":[" 19cm"]},{"name":"Kolor","values":["Biały"]}]}

**Comment by MaciejFrackowiak** [comment]
Zasoby /sale/product-offers obecnie nie obsługują parametrów własnych.
