### ISSUE TITLE
[sandbox] Nie można utworzyć nowego konta

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#746]
Nie można utworzyć w sandboxie nowego konta, przy rejestracji cały czas wyświetla się komunikat "Wystąpił błąd serwera"

**Comment by PawelTaberski** [comment]
Problem nadal występuje? Przetestowałem rejestrację i wygląda na to że wszystko działa poprawnie.

**Comment by SlawomirMizerski** [comment]
Po usunięciu wszystkich ciasteczek prawie się udało, teraz nie mogę aktywować konta z linku wysłanego na maila, wyświetla się komunikat "Nie możemy aktywować Twojego konta
Wystąpił błąd serwera. Odczekaj chwilę i zarejestruj się jeszcze raz."

**Comment by SlawomirMizerski** [comment]
Udało się wreszcie aktywować konto.

**Comment by SlawomirMizerski** [comment]
Jak dokonać zakupu testowego tak aby nie kończyło się to komunikatem "Nie udało się kupić przedmiotu"?

**Comment by PawelTaberski** [comment]
Jest obecnie problem na sandboxie sprawę zgłosiłem do odpowiedniego zespołu, proszę o cierpliwość.
