### ISSUE TITLE
Błąd Adres odbiorcy jest nieprawidłowy

### ISSUE THREAD

**Issue by algru1** [allegro/allegro-api#7461]
Dzień dobry,

Dla metody tworzenia paczki o requestId - 884f87b6-5741-4af4-9cf5-028b170d5a4c. Otrzymaliśmy komunikat błędu:
{
  "code": "VALIDATION_ERROR",
  "message": "Receiver address is incorrect",
  "path": "receiver.address.street",
  "userMessage": "Adres odbiorcy jest nieprawidłowy"
}.
W polu receiver.address.street została przekazana wartość Ogrodowa58. Czy problemem jest brak spacji między nazwą ulicy i numerem czy jeszcze coś innego?

Aleksandra Gruszka

**Comment by MaciejFrackowiak** [comment]
Tak, numer budynku powinien być osobno zapisany. Reszta danych wygląda OK.
