### ISSUE TITLE
Get parameters supported by a category API Query

### ISSUE THREAD

**Issue by dmsmatrix** [allegro/allegro-api#7462]
Hi,

We noticed that **Color/Pattern** is available as an attribute for product category (Allegro > Fashion > Clothing, Shoes, Accessories > Men's Clothing > Vests > Casual Vests) for following product on Allegro, but we are getting **variantsAllowed: false** for **Color** property using API _/sale/categories/87846/parameters_

parameter id => 249512

category id => 87846

![image](https://github.com/allegro/allegro-api/assets/92523331/4e564f49-8e24-483c-9548-21ce59fd6089)

Link: https://allegro.pl/oferta/meski-sweter-z-dzianiny-z-dekoltem-w-szpic-i-bez-rekawow-14038898440
![image](https://github.com/allegro/allegro-api/assets/92523331/67ac53cf-e5f1-4c5d-90b9-936272b0ad0e)

Thanks in advance.

**Comment by MartaNowaczyk** [comment]
In this category, it is not possible to group by the "color" parameter. As you wrote, the information about this is in the response for GET /but/categories/87846/parameters:

```
            "id": "249512",
            "name": "color",
            ...
            "options": {
                "variantsAllowed": false,
```

The screen you attached is about the Color/Pattern parameter (colorPattern), which is not the same as the Color parameter with id 249512 in the category.

The information that you can combine offers by colorPattern is returned in GET /sale/categories/{categoryId}:

```
    {
    "id": "87846",
    "name": "Casual Vests",
    "parent": {
        "id": "87834"
    },
    "leaf": true,
    "options": {
        "variantsByColorPatternAllowed": true,
        ...
    }
},
```

You can read more about colorPattern in our [tutorial](https://developer.allegro.pl/tutorials/how-to-create-a-multi-variant-offer-nn9DOL3nXs2#create-a-multi-variant-offer).

**Comment by dmsmatrix** [comment]
OK...but category 87846 doesn't have **colorPattern** parameter, it has only **color** parameter in it...so as **"options.variantsByColorPatternAllowed": true** for this category and **colorPattern** parameter is missing, can I consider color parameter as _colorPattern_ field in _sale/product-offers/ API_ request. Means can I consider color parameter as colorPattern parameter if colorPattern parameter is missing in such case?

**Comment by MartaNowaczyk** [comment]
There is no such parameter, because it is not the "Color" parameter, or any other, but it is grouped based on the main product photo. To better understand this feature, you can look at the example in our [tutorial](https://developer.allegro.pl/tutorials/how-to-create-a-multi-variant-offer-nn9DOL3nXs2#create-a-multi-variant-offer), where we describe in detail the process of creating a multi-variant offer with the colorPattern option.

**Comment by dmsmatrix** [comment]
Thanks for the information. But then what is use of color parameter which is actually there for category. Why cant we use it as an attribute instead of using virtual parameter color/pattern and virtual field colorPattern?

**Comment by dmsmatrix** [comment]
Why I am getting following error for my trace-id **67fcf2fe0a672753**

**{"errors":[{"code":"VALIDATION_ERROR","message":"The color/pattern parameter entered cannot be matched with the offers 14181196733, 14181196799, 14181196869, 14181196942, 14181197014, 14181197066, 14181197120, 14181197185, 14181197249, 14181197298, 14181197358, 14181197406, 14181197456, 14181197524. Use the same color/pattern parameter value in the group of offers (14181196733, 14181196799, 14181196869, 14181196942, 14181197014, 14181197066), (14181197120, 14181197185, 14181197249, 14181197298, 14181197358, 14181197406, 14181197456, 14181197524), (14181197567, 14181197627, 14181197698, 14181197750, 14181197822, 14181197911, 14181197968).","details":null,"path":null,"userMessage":"The color/pattern parameter entered cannot be matched with the offers 14181196733, 14181196799, 14181196869, 14181196942, 14181197014, 14181197066, 14181197120, 14181197185, 14181197249, 14181197298, 14181197358, 14181197406, 14181197456, 14181197524. Use the same color/pattern parameter value in the group of offers (14181196733, 14181196799, 14181196869, 14181196942, 14181197014, 14181197066), (14181197120, 14181197185, 14181197249, 14181197298, 14181197358, 14181197406, 14181197456, 14181197524), (14181197567, 14181197627, 14181197698, 14181197750, 14181197822, 14181197911, 14181197968)."}]}**

**Comment by MaciejFrackowiak** [comment]
You have a product in three different colour versions - so in a request, you should group them into three different colorPattern groups. In the error response, we identified these groups:
1. 14181196733, 14181196799, 14181196869, 14181196942, 14181197014, 14181197066
2. 14181197120, 14181197185, 14181197249, 14181197298, 14181197358, 14181197406, 14181197456, 14181197524
3. 14181197567, 14181197627, 14181197698, 14181197750, 14181197822, 14181197911, 14181197968

**Comment by MaciejFrackowiak** [comment]
You shouldn't put every colour group in a separate array - just one array for all the entries, e.g.
```
{
"name":"Men's V-neck Sleeveless Outerwear Vest - 169231680",
"offers":[
{
"id":14181196733,
"colorPattern":"black"
},
{
"id":14181196799,
"colorPattern":"black"
},
...
```

**Comment by dmsmatrix** [comment]
So its already there...still I am getting an error response

{
    "name":"Men's V-neck Sleeveless Outerwear Vest - 169231680",
    "offers":[
        {
            "id":14181196733,
            "colorPattern":"black"
        },
        {
            "id":14181196799,
            "colorPattern":"black"
        },
        {
            "id":14181196869,
            "colorPattern":"black"
        },
        {
            "id":14181196942,
            "colorPattern":"black"
        },
        {
            "id":14181197014,
            "colorPattern":"black"
        },
        {
            "id":14181197066,
            "colorPattern":"black"
        },
        {
            "id":14181197120,
            "colorPattern":"black"
        },
        {
            "id":14181197185,
            "colorPattern":"green"
        },
        {
            "id":14181197249,
            "colorPattern":"green"
        },
        {
            "id":14181197298,
            "colorPattern":"green"
        },
        {
            "id":14181197358,
            "colorPattern":"green"
        },
        {
            "id":14181197406,
            "colorPattern":"green"
        },
        {
            "id":14181197456,
            "colorPattern":"green"
        },
        {
            "id":14181197524,
            "colorPattern":"green"
        },
        {
            "id":14181197567,
            "colorPattern":"blue"
        },
        {
            "id":14181197627,
            "colorPattern":"blue"
        },
        {
            "id":14181197698,
            "colorPattern":"blue"
        },
        {
            "id":14181197750,
            "colorPattern":"blue"
        },
        {
            "id":14181197822,
            "colorPattern":"blue"
        },
        {
            "id":14181197911,
            "colorPattern":"blue"
        },
        {
            "id":14181197968,
            "colorPattern":"blue"
        }
    ],
    "parameters":[
        {
            "id":54
        },
        {
            "id":"color/pattern"
        }
    ]
}

**Comment by MartaNowaczyk** [comment]
For offer 14181197120 you have "black", but it should be "green".

**Comment by dmsmatrix** [comment]
Added variants correctly now but not cant see variations on product page

{"name":"Men's V-neck Sleeveless Outerwear Vest - 169257600","offers":[{"id":14196267755,"colorPattern":"black"},{"id":14181196733,"colorPattern":"black"},{"id":14181196799,"colorPattern":"black"},{"id":14181196869,"colorPattern":"black"},{"id":14181196942,"colorPattern":"black"},{"id":14181197014,"colorPattern":"black"},{"id":14181197066,"colorPattern":"black"},{"id":14181197185,"colorPattern":"green"},{"id":14181197249,"colorPattern":"green"},{"id":14181197298,"colorPattern":"green"},{"id":14181197358,"colorPattern":"green"},{"id":14181197406,"colorPattern":"green"},{"id":14181197456,"colorPattern":"green"},{"id":14181197524,"colorPattern":"green"},{"id":14181197567,"colorPattern":"blue"},{"id":14181197627,"colorPattern":"blue"},{"id":14181197698,"colorPattern":"blue"},{"id":14181197750,"colorPattern":"blue"},{"id":14181197822,"colorPattern":"blue"},{"id":14181197911,"colorPattern":"blue"},{"id":14181197968,"colorPattern":"blue"}],"parameters":[{"id":54},{"id":"color/pattern"}]}

**Comment by MartaNowaczyk** [comment]
I see, the variants are already visible.
