### ISSUE TITLE
Brak produktów podczas odpytywania /sale/products

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#7463]
Czy wykonuję źle poniższe zapytania? Odpytuję o produkty i na dużą część EAN'ów dostaję pustą tablicę produktów. Poniżej 2 przykłady:

GET https://api.allegro.pl/sale/products?mode=GTIN&phrase=9788364030314
trace-id: c6e41b2acef3248a

GET https://api.allegro.pl/sale/products?mode=GTIN&phrase=9788364030376
trace-id: 9154018fecf8f4b5

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Zapytania są prawidłowe - w naszej bazie produktów nie mamy takich o podanych kodach EAN.

**Comment by tomylee0** [comment]
W takim razie może jest szansa aby przynajmniej chwilowo wyłączyć blokadę edycji ceny lub ilości sztuk oferty jeśli nie ma w niej wszystkich parametrów obowiązkowych?

Dlaczego to jest ważne? Już wyjaśniam. Otóż 7 sierpnia pojawiły się nowe parametry obowiązkowe:
https://allegro.pl/dla-sprzedajacych/7-sierpnia-zmienimy-sposob-wystawiania-ofert-w-kategorii-ksiazki-i-komiksy-x52VPdXkVIk
Jednocześnie brakuje w bazie produktowej sporej ilości produktów (kiedyś były bo na ich podstawie wystawialiśmy oferty - a niedawno zostały usunięte). Nie mamy zatem skąd wziąć wartości dla nowych parametrów obowiązkowych. Skutkiem czego nie jesteśmy w stanie edytować znaczącej ilości ofert pod względem ilości sztuk oraz ceny. A jest to na tyle ważne, że jeśli blokada wciąż będzie obowiązywać to będziemy zmuszeni usunąć mnóstwo aktywnych ofert.

**Comment by MaciejFrackowiak** [comment]
Przykro mi, jednak ze strony API nie mamy takiej mocy sprawczej. Zmiana musiałaby dotyczyć całego serwisu, ponieważ baza produktów jest jedna, podobnie jak wszystkie funkcjonalności, które muszą działać zarówno w API, jak i w serwisie WWW.

**Comment by tomylee0** [comment]
Mogę w takim razie mieć jedynie prośbę do Ciebie o nękanie zespół odpowiedzialny za wdrożenie zmian zapisanych we wspomnianej informacji dla sprzedającego:
https://allegro.pl/dla-sprzedajacych/7-sierpnia-zmienimy-sposob-wystawiania-ofert-w-kategorii-ksiazki-i-komiksy-x52VPdXkVIk

Głównie chodzi mi o wymuszenie działania tego fragmentu który zupełnie nie zgadza się z rzeczywistością:

**W aktywnych ofertach, które wystawiasz w wybranych podkategoriach, automatycznie dodamy i uzupełnimy nowy parametr.**

**Comment by MaciejFrackowiak** [comment]
Jeżeli posiadasz oferty, w których nie zadziałał opisany mechanizm to proszę zgłoś to bezpośrednio poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) wraz ze wskazaniem takich przykładów.
