### ISSUE TITLE
Language code issue

### ISSUE THREAD

**Issue by justynapalka** [allegro/allegro-api#7464]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,
przy wystawianiu oferty pomimo przesyłania parametru language=pl-PL, otrzymujemy poniższy błąd.

{"errors":[{"code":"LanguageNotSupportedException","message":"Language en-GB not supported, supported languages: pl-PL,en-US,cs-CZ","details":null,"path":"/sale/products/4ef2a0d4-2597-4bab-968d-df7c777d71f5/change-proposals","userMessage":"Language en-GB not supported, supported languages: pl-PL,en-US,cs-CZ"}]}

Czy mogę prosić o wsparcie?
Justyna Pałka

 

 - podaj pełne cURL z responsem i requestem (możesz je nam także przekazać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) - w zgłoszeniu podaj numer wątku na GitHubie)
- podaj trace-id
- dokładnie opisz problem -->

**Comment by MaciejFrackowiak** [comment]
Jak widzę w nagłówku Accept-Language przekazujesz wartość "en-GB", której nie obsługujemy. W związku z tym otrzymany komunikat błędu jest w pełni poprawny. Natomiast pole "language" odpowiada tylko za język proponowanych zmian w produkcie.
