### ISSUE TITLE
Problem z sale/product-offers

### ISSUE THREAD

**Issue by gruszja** [allegro/allegro-api#7465]
Cześć,

Nie ukrywam, że dopiero zaczynam swoja prace z Allegro API. Załozyłem konto na allegrosandbox.pl i chce dodać produkt za pomoca sale/product-offers. 
Wczesniej wygenerowalem token autoryzacji za pomoca endpointu https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials.

Wrzucam ten token do autoryzacji, ale przy probie dodania produktu dostaje "errors": [
        {
            "code": "AccessDeniedException",
            "message": "Access is denied",
            "details": null,
            "path": null,
            "userMessage": "No access."
        }
    ]
Pomimo tego, ze po zrobieniu decode tokenu JWT mam dostep do odpowiedniej sekcji
{
  "scope": [
    "allegro:api:orders:read",
    "allegro:api:fulfillment:read",
    "allegro:api:profile:write",
    "allegro:api:sale:offers:write",
    "allegro:api:fulfillment:write",
    "allegro:api:billing:read",
    "allegro:api:campaigns",
    "allegro:api:disputes",
    "allegro:api:sale:offers:read",
    "allegro:api:bids",
    "allegro:api:orders:write",
    "allegro:api:ads",
    "allegro:api:payments:write",
    "allegro:api:sale:settings:write",
    "allegro:api:profile:read",
    "allegro:api:ratings",
    "allegro:api:sale:settings:read",
    "allegro:api:payments:read",
    "allegro:api:messaging"
  ],

Nie bardzo wiem gdzie popelniam błąd i stad prośba o pomoc.

**Comment by MaciejFrackowiak** [comment]
Zasoby /sale/product-offers wymagają autoryzacji typu "bearer-token-for-user", czyli [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow. Korzystając z client_credentials nie uzyskasz dostępu do nich.

**Comment by gruszja** [comment]
Dzieki za pomoc - uzyskalem token zgodnie z device flow. Jednak teraz napotykam na inny problem. Body Request wyglada nastepujaco : {
    "productSet":[{
        "product":{
            "category":{
                "id":"5"
            },
            "name": "testowy produkt"
        }
    }],
    "sellingMode": {
        "price": {
            "amount": "220.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 1
    },
    "images": [
            "https://www.swiatobrazu.pl/zdjecie/artykuly/552332/zdjecie-tygodnia.jpeg"
        ],
    "delivery": {
        "handlingTime": "PT24H",
        "shippingRates": null,
        "additionalInfo": "string",
        "shipmentDate": "2019-08-24T14:15:22Z"
        }
}
A dostaje response :  "errors": [
        {
            "code": "ProductProposalsAccessForbiddenException",
            "message": "Access denied.",
            "details": null,
            "path": "productSet[0].product",
            "userMessage": "Brak dostępu."
        }
    ]
Dodam tylko ze robie zgodnie z instrukcji do dodania aukcji z nowym produktem.

**Comment by MaciejFrackowiak** [comment]
Proszę podaj swój login lub identyfikator konta.

**Comment by gruszja** [comment]
login: gruszja13

**Comment by MaciejFrackowiak** [comment]
Problem tkwił w nieukończonej weryfikacji konta - przeprocesowałem wniosek, teraz powinno być już OK.

**Comment by gruszja** [comment]
Dziekuje bardzo. Działam dalej :)

**Comment by gruszja** [comment]
Po dodaniu wymaganej sekcji images w productSet.product dostaje komunikat "wielkość musi należeć do zakresu od 1 do 2147483647" To jest zwiazane z wielkością zdjecia ? Nie ma konkretnie opisanego czego dotyczy blad. Response:     "errors": [
        {
            "code": "ProductValidationException",
            "message": "Unprocessable entity",
            "details": null,
            "path": "productSet[0].product",
            "userMessage": "wielkość musi należeć do zakresu od 1 do 2147483647"
        }
    ]

**Comment by MaciejFrackowiak** [comment]
Musisz wystawiać ofertę/produkt w kategorii, która jest liściem drzewa kategorii i parametrów. Kategoria o id=5, czyli Dom i Ogród to rozległa kategoria, która posiada szered podkategorii. Całe drzewo możesz pobrać zasobem [GET /sale/categories](https://developer.allegro.pl/documentation/#operation/getCategoriesUsingGET).

**Comment by gruszja** [comment]
Czyli jezeli dobrze rozumiem to w produkcie, ktory dodaje musze zawrzec wszystkie parametry, które otrzymuje z endpointu GET sale/categories/{categoryID}/parameters ?

**Comment by MaciejFrackowiak** [comment]
W produkcie muszą się znaleźć parametry oznaczone flagą "true" przy "requiredForProduct". Spójrz do [naszego poradnika](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-nowym-produktem), gdzie krok po kroku opisaliśmy proces wystawiania oferty z nowym produktem.

**Comment by gruszja** [comment]
Dzieki za podpowiedz. Docelowo bede uzywal kategorii "Farby" gdzie category.id = 261189. Po dodaniu wszystkich parametrow gdzie flaga requiredForProduct = true natrafiam na blad CATEGORY_MISMATCH. Ponizej request i response
Request: 

{
    "productSet":[{
        "product":{
            "category":{
                "id":"261189"
            },
            "parameters":[
                {
                "id": "231773",
                "values":[
                    "Adexbud"
                ]},
                {
                "id": "224017",
                "values":[
                    "testowy kod"
                ]},
                {
                "id": "231721",
                "values":[
                    "puszka"
                ]},
                {
                "id": "231765",
                "values":[
                    "brązowy"
                ]},
                {
                "id": "219021",
                "values":[
                    20.0
                ]},
                {
                "id": "225693",
                "values":[
                    "0744861045021"
                ]}
                ],
            "images": [
                "https://cdf.pl/wp-content/webp-express/webp-images/uploads/2018/02/farby.jpg.webp"
            ],
            "name": "testowy produkt"
        }
    }],
    "sellingMode": {
        "price": {
            "amount": "220.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 1
    },
    "delivery": {
        "handlingTime": "PT24H",
        "shippingRates": null,
        "additionalInfo": "string",
        "shipmentDate": "2019-08-24T14:15:22Z"
        },
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59",
            "name": "string"
},
        "returnPolicy": {
            "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59",
            "name": "string"
},
        "warranty": {
            "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59",
            "name": "string"
}
}
}

Response: "errors": [
        {
            "code": "CATEGORY_MISMATCH",
            "message": "Existing Product related to submitted data was found. The provided category `Farby` (261189) does not match the existing product category `Power` (258020)",
            "details": null,
            "path": "productSet[0].product.category.id",
            "userMessage": "A product from our database has been recognized based on the specified data. The indicated category `Farby` (261189) does not match the product category: `Power` (258020)."
        }
    ]

**Comment by MaciejFrackowiak** [comment]
Otrzymany komunikat mówi, że znaleźliśmy w naszej bazie produktów produkt, który odpowiada podanym przez Ciebie parametrom. Co więcej, podana przez Ciebie kategoria nie odpowiada kategoriom przypisanym do tego produktu, dlatego pojawia się informacja "CATEGORY_MISMATCH". Produkt z naszej bazy o podanych parametrach posiada id=7bada1fc-2d68-4693-af25-f4c01f6d62ac - szczegóły jego znajdziesz korzystając z [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct).

**Comment by gruszja** [comment]
Dzien Dobry, 

Zalozylem nowe konto na allegro sandbox client:113273440. Przy próbie pracy z API dostaje komunikat o braku dostepu pomimo wpisania kodu autoryzacji. Czy problem nie tkwi w weryfikacji konta ?

**Comment by AureliuszBrussy** [comment]
Konto id 113273440 jest zarejestrowane na produkcji. Z kolei konto 106093589 faktycznie zostało utworzone na Sandboxie, natomiast nie jest w pełni aktywne. Powinieneś móc je aktywować przy pierwszej transakcji. 

Aby jednak w pełni testować możliwości API Allegro - [zarejestruj konto Firma](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto).

**Comment by gruszja** [comment]
No a dlaczego gdy jestem zalogowany jako client 113273440  w momencie do przejscia do zakladki Zarzadzaj Aplikacjami (Sandbox) przelacza mi sie automatycznie klient na 106093589  ?

**Comment by AureliuszBrussy** [comment]
Bo konto id 113273440 zarejestrowane jest na produkcji. To zupełnie inna baza kont, te dwa środowiska ich nie współdzielą. Na Sandboxie jesteś zalogowany na koncie id 106093589.

**Comment by gruszja** [comment]
Dobrze, Dziekuje. Pracowalem 2 tygodnie temu na koncie z loginem gruszja13 a teraz jak probuje odzyskac haslo to wyskakuje mi komunikat ze taki login nie istnieje. Dlaczego ?
