### ISSUE TITLE
Kontynuacja ticketu "Błędne parametry Allegro #7329"

### ISSUE THREAD

**Issue by JiriVyhnalek** [allegro/allegro-api#7467]
Witam, kilka dni temu rozwiązaliśmy problem z błędnym tłumaczeniem kolorów w ALlegro.cz, korekta niby została wykonana, ale błąd nadal się pojawia patrz zrzut ekranu.... Co mogę zrobić, aby naprawić problem?
![Snímek obrazovky 2023-08-09 110024](https://github.com/allegro/allegro-api/assets/138673575/650c3669-451b-4b9e-9d32-659c14514677)

**Comment by MaciejFrackowiak** [comment]
Ta kwestia wykracza już poza API - dotyczy stricte parametrów widocznych w serwisie WWW. Proszę zgłoś swoje uwagi poprzez [formularz kontaktowy](https://allegro.cz/pomoc/kontakt?category=02bc595b-6c50-4c0a-9281-3a3bffa11c8d) Allegro.
