### ISSUE TITLE
GET /parcel-management/parcels/label  SANDBOX

### ISSUE THREAD

**Issue by randomWro** [allegro/allegro-api#7468]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Podczas prób tworzenia etykiety ręcznie lub przez postmana, otrzymuje ten sam komunikat:

![obraz](https://github.com/allegro/allegro-api/assets/141820933/4b3feb33-3045-4544-9f16-ff7df24379a2)
![obraz](https://github.com/allegro/allegro-api/assets/141820933/ad581d21-23a7-424f-a576-e1438edac2a2)

https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcels/label?parcelId=d6504e33-868a-4dd4-9b30-358a9fc8851c

**Comment by MartaNowaczyk** [comment]
Problemem może być format etykiety. Na środowisku Sandbox etykiety w formacie ZPL nie są generowane dla wszystkich przesyłek i możesz wygenerować etykietę tylko w formacie .pdf.

**Comment by randomWro** [comment]
> Problemem może być format etykiety. Na środowisku Sandbox etykiety w formacie ZPL nie są generowane dla wszystkich przesyłek i możesz wygenerować etykietę tylko w formacie .pdf.

zmieniłam na pdf:

![obraz](https://github.com/allegro/allegro-api/assets/141820933/b43ffa5a-9c81-4afa-9850-77ad91a8120f)

**Comment by MartaNowaczyk** [comment]
Sprawdź czy na pewno masz w [ustawieniach](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/zamowienia/ustawienia) format PDF, bo taki błąd ze rzutu widzę właśnie, gdy nie jest ten format ustawiony.
