### ISSUE TITLE
Miasto odbiorcy jest nieprawidłowe

### ISSUE THREAD

**Issue by algru1** [allegro/allegro-api#7469]
Dzień dobry,

Dla request id = 0ea30c57-c222-47a4-ae2b-5d3797ae6859 mamy błąd:
 {
  "code": "VALIDATION_ERROR",
  "message": "Receiver city is incorrect",
  "path": "receiver.address.city",
  "userMessage": "Miasto odbiorcy jest nieprawidłowe"
}
dla wartości "city":"Ostrów Wlkp.". Jaka powinna być prawidłowa nazwa miasta w tym przypadku?

Aleksandra Gruszka

**Comment by MartaNowaczyk** [comment]
Dzień dobry, spróbuj "Ostrów Wielkopolski".
