### ISSUE TITLE
Tworzenie przesyłek Packeta

### ISSUE THREAD

**Issue by akonopka11** [allegro/allegro-api#7471]
Witam, mam problem z utworzeniem przesyłki Packeta, konto produkcyjne, commandId fce07964-e2ae-45a9-899a-4a4c35ad0d51, dane, które wysyłam:

"{\"serviceId\":\"529b132a-2f6b-4f37-b7fb-9c4a33aba97c\",\"receiver\":{\"address\":{\"street\":\"S.K.Neumanna359\",\"postCode\":\"27303\",\"city\":\"Stochov\",\"countryCode\":\"CZ\",\"county\":null},\"email\":\"2so6bnz7mf+26428df19@allegromail.pl\",\"name\":\"Martin Makalous\",\"company\":\"\",\"phone\":\"+420604857037\",\"pointId\":{\"id\":\"23879\",\"name\":\"Z-BOX Stochov, u0160kolnu00ed 4333 (COOP)\",\"address\":{\"city\":\"Stochov\",\"street\":\"u0160kolnu00ed 4333\",\"zipCode\":\"273 03\",\"countryCode\":\"CZ\"},\"description\":null}},\"pickup\":{\"company\":\"MOTI\",\"phone\":\"798023509\",\"address\":{\"street\":\"Aksamitna 2\",\"postCode\":\"02-287\",\"city\":\"Warszawa\",\"countryCode\":\"PL\",\"county\":null}},\"items\":[{\"dimensions\":{\"height\":{\"value\":30,\"unit\":\"CENTIMETER\"},\"width\":{\"value\":40,\"unit\":\"CENTIMETER\"},\"depth\":{\"value\":60,\"unit\":\"CENTIMETER\"}},\"weight\":{\"value\":10,\"unit\":\"KILOGRAM\"},\"description\":\"[M-129104-Packeta] Martin Makalous\",\"value\":{\"amount\":356,\"currency\":\"CZK\"},\"type\":\"PACKAGE\"}],\"type\":\"PACKAGE\",\"label\":{\"sender\":{\"address\":{\"street\":\"ROBOTNICZA 11\\/13\",\"postCode\":\"02-261\",\"city\":\"WARSZAWA\",\"countryCode\":\"PL\",\"county\":null},\"email\":\"zamowienia@moti.net.pl\",\"company\":\"MOTI Sp. o.o.\",\"phone\":\"798023509\"},\"fileFormat\":\"PDF\"}}"

Odpowiedź:
    "response": {
        "errors": [
            {
                "code": "BAD_REQUEST",
                "path": "/parcel-management/parcel-create-commands/fce07964-e2ae-45a9-899a-4a4c35ad0d51",
                "details": null,
                "message": "JSON parse error",
                "userMessage": "Nieprawidłowa treść żądania JSON"
            }
        ]
    }
    
W czym może być problem? Mamy ten sam kod do generowania przesyłek dla różnych kurierów, także struktura danych powinna być ok, raczej z samymi danymi jest coś nie tak. Jakieś szczególne podejście do czeskich znaków powinniśmy stosować? Waluta CZK chyba powinna być ok?

**Comment by akonopka11** [comment]
Przyczyna po naszej stronie, przepraszam za zamieszanie.

**Comment by akonopka11** [comment]
Jednak nadal nie działa, mam ten sam problem dla Allegro One też.

**Comment by MartaNowaczyk** [comment]
W requeście nadal jest nieprawidłowa struktura. Coś się u was nie składa - zerknij na "orderDataJson"- nie mamy tego w naszej dokumentacji, jak również na dodany obiekt dla "pointId" - powinien się tam znaleźć tylko identyfikator punktu odbioru. Prawidłową strukturę znajdziesz [tutaj](https://developer.allegro.pl/documentation/#operation/createNewParcel).
