### ISSUE TITLE
WZA label 504

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#7473]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ X ] ze środowiskiem produkcyjnym / with the production environment

Mamy problem z generowaniem etykiet do przesyłek, dostajemy błąd 504. 

przy zapytaniu na url
https://api.allegro.pl/parcel-management/parcels/label?parcelId=a2fccca7-09d9-41e7-bc45-1c166d1fe578
trace-id:  f26dd17ed4a2547f

odpowiedź:
{
	"errors": [
		{
			"code": "ServiceTimeoutException",
			"message": "An error occurred",
			"details": null,
			"path": null,
			"userMessage": "Query response time exceeded. Try again."
		}
	]
}

Występują jakieś problemy z api czy coś nie tak z naszym requestem?

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, przed godz. 15 dosłownie kilka wywołań skończyło się błędem 504. Przepraszam za niedogodności.

**Comment by d3stozaur** [comment]
Tylko ze problem caly czas wystepuje, np. trace-id: 3b0d465f5744a4c7

**Comment by d3stozaur** [comment]
udalo sie cos ustalic?

**Comment by MaciejFrackowiak** [comment]
Jak wspomniałem ostatnio, dokonana została pewna zmiana w konfiguracji, która powinna ograniczyć ponowne wystąpienie błędów.
