### ISSUE TITLE
Pytanie o produkturyzację

### ISSUE THREAD

**Issue by AdrianeZ** [allegro/allegro-api#7475]
Witam, mam pytanie korzystajać z zasobu POST **/sale/product-offers** - kiedy chcemy wystawić ofertę z już **istniejącym** produktem, (podajemy jego uuid w talibcy productSet[0].product) czasami nie uda się wystawić oferty ponieważ brakuje jakiegoś parametru, w **samym** sprawdziłem na jakimś przykładzie i w parametrach produktu dla danej kategorii nie było jednego z parametru które było oznaczone jako **required:true** oraz **requiredForProduct:true** w parametrach kategorii zasób GET **/sale/categories/{categoryId}/parameters.** Co robić najlepiej w takiej sytuacji rozumiem że jeżeli np wystąpi sytuacja że w kategorii został dodany jakis parametr wymagany lub parametr niewymagany został zmieniony na wymagany - nie aktualizujecie powiązanych parametrów powiązanych produktów z kategorią aby zawsze były spójne? Istnieje sposób na podanie ew brakujących parametrów gdzieś w requescie? Proszę też o dokładne wytłumaczenie róznicy między **required** oraz **requiredForProduct**. Pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
Pole "requiredForProduct" informuje, czy dany parametr jest obowiązkowy, gdy tworzysz nowy produkt. Samo "required" natomiast informuje, czy dany parametr jest obowiązkowy przy wystawianiu oferty. Warto także zwrócić uwagę na flagę "describesProduct", którą zwraca [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) - opisuje ona, czy dany parametr jest parametrem produktowym, czy też ofertowym.

**Comment by AdrianeZ** [comment]
Rozumiem, a pierwsza część pytania, gdzie dodać parametry których nie ma w produkcie a są wymagane przy tworzeniu oferty oznaczone jako required?

**Comment by MaciejFrackowiak** [comment]
Istotą jest, czy są to parametry ofertowe czy produktowe - jeżeli produktowe to powinny znaleźć się pod strukturą productSet, natomiast jeżeli ofertowe to poza nią. Spójrz proszę na [nasz poradnik](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#parametry-ofertowe), gdzie opisaliśmy identyfikację ich.
