### ISSUE TITLE
Brak kategorii zdefiniowanej w produkcie

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#7476]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam,
Od środy mamy problem z zaciąganiem danych dla kategorii podanych w produktach (nie można pobrać kategorii dla Id podanego w produkcie.)

Przykład:
Produkt o id 5492605a-d02c-485b-9b51-8ed1754c57e5 ma podłączoną kategorie 261375, ale przy próbie jej ściągnięcia przez zasób
sale/categories/261375 otrzymujemy błąd (trace-id=5797ce4c711e4822)

{"errors":[{"code":"ERROR","message":"Category '261375' not found","details":"ResourceNotFoundException","path":null,"userMessage":"Category '261375' not found"}]}

Problem pojawia się dla sporej grupy przedmiotów.

**Comment by dol1234** [comment]
Ile potrwa ta niespójność bo wg mnie to błąd krytyczny. Nie możemy obecnie korzystać z aplikacji (zaciągamy pola dla kategorii w celu wystawienia oferty)

**Comment by tomylee0** [comment]
Dopytam czy zmiany w bazie produktowej również zakończą się jutro?

**Comment by MartaNowaczyk** [comment]
tak, procesy te są powiązane.

**Comment by dol1234** [comment]
Czy proces się zakończył? Nadal otrzymujemy błędy (Category '261374' in tree 'listing-pl' not found(ERROR))

**Comment by MartaNowaczyk** [comment]
@dol1234 tak, tamten proces zakończył się. W jakimś produkcie nadal widnieje ta kategoria?

**Comment by dol1234** [comment]
Nie mam tej informacji

**Comment by MartaNowaczyk** [comment]
Rozumiem, myślałam, że może coś nam się nie przeprocesowało. Właściwa kategoria dla "Mapy, atlasy, plany miast" to teraz 79420 ("Mapy, przewodniki, książki podróżnicze"). Kategorię 261374 usunęliśmy. Zmiany w kategoriach możesz śledzić dzięki [dziennikowi zdarzeń w kategoriach](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#dziennik-zmian-w-kategoriach). Usunięcie kategorii znajdziesz np. podczas wywołania [GET /sale/category-events?limit=1000&type=CATEGORY_DELETED](https://developer.allegro.pl/documentation/#operation/getCategoryEventsUsingGET_1):
```
...
        {
            "id": "1691729340899850997",
            "occurredAt": "2023-08-11T04:49:00.899Z",
            "type": "CATEGORY_DELETED",
            "category": {
                "id": "261374",
                "name": "Mapy, atlasy, plany miast",
                "parent": {
                    "id": "79420"
                },
                "leaf": true
            },
            "redirectCategory": {
                "id": "79420"
            }
...
```

**Comment by dol1234** [comment]
Dziękuję. Odświeżyłem po raz kolejny list kategorii, zobaczę czy to wystarczy.
