### ISSUE TITLE
Opis przesyłki

### ISSUE THREAD

**Issue by akonopka11** [allegro/allegro-api#7477]
Witam,
Mam taki błąd przy tworzeniu przesyłki Allegro Kurier DHL (konto produkcyjne):
{"id": "3f5ff543-a884-4514-bec0-4614aa19139b", "errors": [{"code": "VALIDATION_ERROR", "path": "items.description", "details": null, "message": "Parcel description is too long", "userMessage": "Opis przesyłki jest za długi"}], "status": "ERROR", "parcelId": null}
Jaki jest dokładnie limit tych znaków? Czy zależy od metody wysyłki? Generujemy przesyłki dla wielu różnych metod. 

Dla Allegro One Box mamy inny problem, bo zawartość tego pola nie pojawia się nigdzie na etykiecie. Czy zamiast tego pola powinnam użyć label.referenceNumber?  Tam chyba są takie ograniczenia (?):
wielkość musi być pomiędzy 0 a 35
musi pasować do wzorca [A-Za-z0-9 _-]

Proszę o pomoc.

**Comment by MartaNowaczyk** [comment]
Jeżeli chodzi o długość pola description - ogólnie jest to od 2 do 100 znaków, choć zależy to od konkretnego przewoźnika, ostatnie dane jakie mam to:
DHL — wymagany (od 2 do 30 znaków)
DPD — opcjonalny (od 2 do 100 znaków, jeżeli kraj odbiorcy to "PL")
FedEx — wymagany (od 2 do 100 znaków)
GLS — opcjonalny (od 2 do 100 znaków)
InPost — opcjonalny (od 2 do 100 znaków)
InPost Kurier — opcjonalny (od 2 do 100 znaków, jeżeli kraj odbiorcy to "PL")
Poczta Polska — opcjonalny (od 2 do 100 znaków)
ORLEN Paczka — opcjonalny (od 2 do 100 znaków)
UPS — opcjonalny (od 2 do 50 znaków, jeżeli kraj odbiorcy "PL")
Allegro — wymagany (od 2 do 50 znaków — jak w UPS) 


Co do Allegro One Box to nie ma takiej możliwości, bo numer referencyjny jest w tym przypadku zajęty. Więcej w wątku #7423

**Comment by akonopka11** [comment]
Ok, dziękuję za informację.
