### ISSUE TITLE
Sandbox - Weryfikacja konta firmowego

### ISSUE THREAD

**Issue by MatMark** [allegro/allegro-api#7478]
Dzień dobry,

można prosić o weryfikację tych dwóch kont firmowych na Allegro sandbox?

Login 1: **MatMarkHex**

Login 2: **MatMarkTest**

**Comment by MartaNowaczyk** [comment]
Na koncie **MatMarkTest** masz wybraną niepełną opcję sprzedażową. Wejdź proszę do [ustawień konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy), skorzystaj z linku, który masz na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)" i wybierz "Weryfikacja pełna". Uzupełnij dane i prześlij dowolne pliki.
**MatMarkHex** - to konto wygląda jakby nie miało w pełni uzupełnionych danych.

**Comment by MartaNowaczyk** [comment]
Na koncie **MatMarkTest** możesz działać, bo mogłam je aktywować. Jeśli chodzi o konto **MatMarkHex** jeszcze staram się wyjaśnić kwestię niepełnych danych w bazie i będę próbowała je aktywować.

**Comment by MatMark** [comment]
Dziękuję za pomoc, już wszystko działa :)
