### ISSUE TITLE
[Sandbox] Przykładowe działające punkty Allegro One Box i Allegro One Point

### ISSUE THREAD

**Issue by mwkkowalczyk** [allegro/allegro-api#7479]
Jakie pointId powinno zadziałać na sandbox dla:
-Allegro One Point
-Allegro One Box
(oraz - Allegro One Point, One Kurier, - Allegro One Box, One Kurier)

**Comment by MartaNowaczyk** [comment]
Na ten moment mogę podać Ci te przykłady:
Allegro One Punkt, One Kurier (Allegro One Punkt A004517)
Allegro One Box, zielony automat AL002WI1

**Comment by mwkkowalczyk** [comment]
Dziękuję za wskazanie punktów.


podrzucę może w tym wątku jeszcze mój problem/błąd z 22a671de-31f7-11ee-be56-0242ac120002 na sandbox'owym koncie cf_skp_test - otóż z lokalizacji z której będziemy wysyłać paczki nie możliwe jest korzystanie z One Kuriera, a skoro przesyłki będzie odbierał kurier UPS (i dostarczał do One Box'ów lub One Point'ów) to jak rozumiem metodę powinienem wybrać (w przypadku Box'ów) 0aafb43c-e66a-46ec-9cc4-29bb39ebb483, zaś dla wskazanej próby utworzenia przesyłki (22a671de-31f7-11ee-be56-0242ac120002) otrzymuję przy sprawdzaniu statusu utworzenia paczki:

This delivery option is unavailable,details:Order delivery method: 0aafb43c-e66a-46ec-9cc4-29bb39ebb483 is not allowed, should be 0b9bed2c-0bc1-4e1f-9694-29bb39ebb483

Ta druga metoda (0b9bed2c-0bc1-4e1f-9694-29bb39ebb483) dzięki wskazaniu we wiadomości wyżej działającego na sandbox'ie Box'a (AL002WI1) wyrzuca mi z kolei i słusznie, że kod pocztowy nadawcy nie jest obsługiwany przez Allegro One (przykład: 22a674b8-31f7-11ee-be56-0242ac120002 - błąd: Sender post code not support next day).

Z jakiego względu przy tej pierwszej próbie sugeruje mi korzystanie z innej metody dostawy (zamiast przyjąć żądanie utworzenia przesyłki) chociaż istotnie nie mogę skorzystać z tej drugiej opcji dostawy.
