### ISSUE TITLE
Dodawanie i usuwanie aukcji w ofercie wielowariantowej

### ISSUE THREAD

**Issue by coobitus** [allegro/allegro-api#748]
Czy jest w tej chwili możliwość (metoda) dodawania oraz usuwania kolejnych aukcji do/z już istniejących ofert wielowariantowych? 

Chodzi np. o sytuację, w której mam istniejącą ofertę wielowariantową na dany model buta w kilku rozmiarach a doszedł mi właśnie kolejny (nowy) rozmiar tego modelu i wystawiłem go w nowej aukcji, którą chcę "podłączyć" do już istniejącej oferty wielowariantowej na ten rozmiar.

Jeżeli nie ma takiej obsługi aktualnie to czy jest planowana w najbliższej przyszłości? No i w końcu czy jest jakaś preferowana metoda obejścia braku obsługi tych operacji jeśli one nie istnieją? Usunąć istniejący set i utworzyć nowy, w którym znajdą się wszystkie aktualne aukcje?

**Comment by coobitus** [comment]
@PawelTaberski a co z dodawaniem aukcji do takiego zestawu? I co z planami?

**Comment by PawelTaberski** [comment]
Obecnie nie ma takiej możliwości, musiałbyś usunąć taki wielowariant i ustawić go na nowo. Zgłosiłem Twoją sugestię odnośnie usuwania i dodawania ofert. Jeśli zdecydujemy się dodać taką możliwość to poinformujemy o tym.
