### ISSUE TITLE
Jak pobrać informacje o zrealizowanych płatnościach pobraniowych "Wysyłam z Allegro"?

### ISSUE THREAD

**Issue by Maczuga** [allegro/allegro-api#7481]
W jaki sposób w API możemy sprawdzić za które przesyłki pobraniowe "Wysyłam z Allegro" została przekazana od was do nas płatność?

GET /order/checkout-forms/:orderId nie zwraca takich informacji. Sekcja "payment" ma paidAmount = null. Nie przychodzą też żadne eventy związane z pobraniem.

Przelew bankowy może przyjść tylko 1 za kilka płatności: "W ramach jednego przelewu możesz dostać wpłaty od kilku kupujących. Będzie to łączna kwota za wszystkie zamówienia z danego dnia roboczego." - dlatego nie możemy wyłącznie po tym rozpoznać do kogo płatność należy.

**Comment by MaciejFrackowiak** [comment]
Takich informacji nie znajdziesz w zasobach API. Szczegółowe informacje natomiast są dostępne w [zakładce](https://allegro.pl/moje-allegro/sprzedaz/wyplaty/przesylki-pobraniowe-wysylam-z-allegro).

**Comment by Maczuga** [comment]
Czy macie w planach dodanie zasobu do pobierania tych informacji przez API?
