### ISSUE TITLE
A request can contain only one parcel / Shipment request has validation errors

### ISSUE THREAD

**Issue by randomWro** [allegro/allegro-api#7482]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Podczas tworzenia kilku paczek dla jednego zamówienia, mimo poprawnego utworzenia (201 Created)
zapytanie o status poprawne: 

https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/{...}
(200 OK)

Finalnie otrzymujemy błąd: 
![obraz](https://github.com/allegro/allegro-api/assets/141820933/5f86acb0-754d-42f6-91f8-6d59f2d42d04)

Powyższy błąd uniemożliwia poprawne wdrożenie usługi. 

trace-id ba2b90240d45dfa4

**Comment by MaciejFrackowiak** [comment]
Otrzymany przez Ciebie komunikat błędu jest prawidłowy - usługę tzw. wielopaczki oferuje tylko DPD i WE|DO. W przypadku innych przewoźników (m.in. Allegro One jak w Twoim requeście) musisz wykonać kolejne requesty dla poszczególnych przesyłek z zamówienia.
