### ISSUE TITLE
AllegroOnePunkt - brak możliwości wygenerowania protokołu

### ISSUE THREAD

**Issue by Wojtu204** [allegro/allegro-api#7483]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X] inny / other

:beetle: **Opis / Description**
Przy próbie pobrania protokołu przesyłek dla AllegroOnePunkt otrzymujemy komunikat:
{
    "errors": [
        {
            "code": "BAD_REQUEST",
            "message": "Allegro carrier does not support generation of protocols",
            "details": null,
            "path": "parcelIds[%s]",
            "userMessage": "Przewoźnik Allegro nie wspiera generowania protokołów"
        }
    ]
}

trace-id: 8b0efabb6a2276cc

Proszę o informację, kiedy funkcjonalność zostanie udostępniona, lub w jaki sposób mamy wygenerować protokół - jest to jeden z kluczowych dokumentów dla Magazynu i kuriera odbierającego przesyłki od nas, w związku z czym powyższy błąd blokuje wdrożenie usługi wysyłkowej.

**Comment by MaciejFrackowiak** [comment]
Nie jest to błąd - po prostu dla przesyłek Allegro One taki protokół nie jest generowany. Nie jest to odosobniony przypadek - m.in. UPS, InPost, Fedex również nie udostępniają protokołów nadawczych.
