### ISSUE TITLE
Podjazd kuriera - którzy kurierzy oferują tę usługę?

### ISSUE THREAD

**Issue by MateuszChodyraApilo** [allegro/allegro-api#7484]
Dzień dobry,

Chciałbym potwirdzić, że:
- Wszyscy kurierzy z _Wysyłam z Allegro_ oferują podjazd kuriera.
- _InPost_ i _ORLEN Paczka_ nie oferują wyboru godzin podjazdu kuriera.

(https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-zamowic-odbior-paczek-przez-kuriera)

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Tak, jest to właściwy katalog usług. Wyjątek stanowią przesyłki Packeta, dla których podjazdu nie zamówisz - szczegóły w [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/wysylam-z-allegro-narzedzie-do-nadawania-przesylek-bezposrednio-z-konta-E7doGw8VgI1).
