### ISSUE TITLE
WZA CREDENTIALS_ID_NOT_PROVIDED

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#7486]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ X ] ze środowiskiem produkcyjnym / with the production environment

Przy próbie wygenerowania przesyłki do zamówienia
trace-id: 6d0b611b0c0c4303
dostajemy komunikat błedu:
{
			"code": "CREDENTIALS_ID_NOT_PROVIDED",
			"message": "Seller didnt provide credentials for own delivery Method",
			"details": "Seller didnt provide credentials for own delivery Method",
			"path": "client credentials",
			"userMessage": "Wybrana metoda dostawy nie obsługuje tego zamówienia"
}
Co to może oznaczać? Dane do allegro są poprawne inne metody się poprawnie generują, service_id jest takie samo jak w zamówieniu.

**Comment by MaciejFrackowiak** [comment]
Komunikat oznacza, że wybrano metodę dostawy, dla której nie podano niezbędnych danych do obsługi umowy własnej.
