### ISSUE TITLE
Different product.id in offer and order

### ISSUE THREAD

**Issue by Marek-ShopStore** [allegro/allegro-api#7487]
Hello,

we are having problems with some offers - we create offer, we get offerId and productId, we save both.
When customer buys offer sometime get different Id of product in lineItems is different from Id we got when we created the offer.

Example:
ID we got from offer and saved to database: b700f3b8-627f-421f-a0a7-45239b504c84
ID we got from line item in order: 02691150-cfa0-432a-947b-d099912880b1

We compared details of those two products using https://developer.allegro.pl/documentation#operation/getSaleProduct and reply content is identical except for productId

We ran script to count number of products affected and it's like 10-20 from 1000.

Why is it happening?

**Comment by Marek-ShopStore** [comment]
Sure think, but when I  call [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getProductOffer) there is different product.id that when I created the offer - see example.

**Comment by MaciejFrackowiak** [comment]
As I wrote - in the lineItem.id you will not find a product.id - it is an identifier of a line item.

**Comment by Marek-ShopStore** [comment]
As I already wrote, I know it.

Once again to be precise, because you already wrote twice think we of course know:

1. we create offer using /sale/product-offers POST and we get productSet containing product with id we save both offer.id and product.id from productSet to database
2. someone orders our offer, we call get /order/checkout-forms/ GET + order.id we get lineItems, for each lineItem we call /sale/offers GET + id from lineItems item.offer.id and in reply there is different product.id that we got in step 1.
3. when we call /sale/products/{productId} with product.id from 1. step and 2. step, reply content is identical except for **product.id**

See example:
ID we got at step 1: b700f3b8-627f-421f-a0a7-45239b504c84
ID we got at step 2: 02691150-cfa0-432a-947b-d099912880b1
Those products have identical name, isbn, description, parameters, everything!

**Comment by MaciejFrackowiak** [comment]
OK, now it is clear.
Product with id=b700f3b8-627f-421f-a0a7-45239b504c84 was deleted from our database because it was a duplicate.
Now, only a valid product has an ID=02691150-cfa0-432a-947b-d099912880b1.

**Comment by Marek-ShopStore** [comment]
So you can anytime change product.id in our offer? How can I tell you deleted the product as when I call /sale/products/{productId} there is no information at all about it.

As I stated in my first post it's like 20 products out of 1000 (2%).

**Comment by MaciejFrackowiak** [comment]
Yes, we can do it. In our product database, you can find some of the same products which exist in more than two versions - so we have to manage to delete duplicates.

**Comment by Marek-ShopStore** [comment]
So why doesn't function /sale/products/{productId} respond with status 404? 

Now it only way we figured out to know if product was deleted is using /sale/products + EAN and if we get different product.id than we have stored we can guess its because product was deleted

**Comment by MaciejFrackowiak** [comment]
We return 404 because the old product doesn't exist anymore. You are not able to find it.

**Comment by Marek-ShopStore** [comment]
Well, you do not.
When I call /sale/products/b700f3b8-627f-421f-a0a7-45239b504c84 I get 200 and data.

But it' seems there is new Id 02691150-cfa0-432a-947b-d099912880b1 in those data.

So does it mean that if you delete duplicate of product and we call  /sale/products GET we will get data with new product.id in reply? Can you please confirm?

**Comment by MaciejFrackowiak** [comment]
Yes, in this case, we removed the product and immediately merged it with another one - so you receive 200 and its new id. However, there can be a situation when we removed a product, and that is all - you will not receive its new id, and 404 as a result.

**Comment by Marek-ShopStore** [comment]
Thank you.
