### ISSUE TITLE
Product being listed from MALL without description

### ISSUE THREAD

**Issue by Marek-ShopStore** [allegro/allegro-api#7488]
It seems there is ongoing product listing from MALL offers in past few days.

We have reviewed the data and there is description missing!

see:
https://allegro.cz/nabidka/krajinou-jizerskych-hor-lubos-y-kolacek-14141645809
https://allegro.cz/nabidka/nove-mesto-nad-vahom-a-okolie-z-neba-kniha-bohus-14141645971
https://allegro.cz/nabidka/55-najkrajsich-miest-a-mesteciek-slovenska-2-14141646199

Can you please fix it or stop it? It will decrease sales of product greatly.

In previous listing from MALL there was quite nice description you created, see:
https://allegro.cz/nabidka/harry-potter-a-fenixuv-rad-j-k-rowlingova-13929036701

**Comment by MartaNowaczyk** [comment]
Missing descriptions in the offer are not API issues, so please contact via the [contact form](https://allegro.pl/pomoc/kontakt) or your account manager about this.
