### ISSUE TITLE
Dokladna specyfikacja struktur Api

### ISSUE THREAD

**Issue by jpulkiewicz** [allegro/allegro-api#7489]
Witam,

Gdzie znajde specyfikacje dotyczaca, dlogosci, formatow, itp dotyczacych struktur w json obowiazujacych w API.

Przyklad - wyslalem "chuliganski" request do [/parcel-management/parcel-create-commands/...] i dostalem  to co ponizej:
{"errors":[{"code":"VALIDATION_ERROR","message":"wielkość musi być pomiędzy 0 a 35","details":"Invalid value: REFPHI20230809250_78787877879986665856785876586756785877587656785457896789689768968956759698686896895457895986986898545675969986985667555589768969856457579698698689767865858675786567567578575757558758758757865786578587587658765675484578969698698698769876897687555896986986895667598868976897689559967668956757569876896897689768976785599869876897687658897689687985765986987698679869865496986789689769869876897689769845897698","path":"label.referenceNumber","userMessage":"wielkość musi być pomiędzy 0 a 35"}]}

a wiec maxymalna dlugosc pola == 35 - wiec warunki walidacji sa

stad ponawiam prosbe o wskazanie specyfikacji struktur w API, osobiscie jestem zainteresowny sekcja parcel-management.

Z gory dziekuje i pozdrawiam.
Jaroslaw Pulkiewicz

**Comment by MartaNowaczyk** [comment]
Witam. Nie zawsze możemy to jednoznacznie określić w dokumentacji. Jeśli np. chodzi o długość pola description przy tworzeniu paczki, to ogólnie jest to od 2 do 100 znaków, choć zależy to od konkretnego przewoźnika. Jakie pole masz w tym momencie na myśli? Możesz podać też trace-id, które zwracamy dla tego błędu.

**Comment by jpulkiewicz** [comment]
Rozumiem jednak nie chodzi mi o konkretne pola, a raczej o cale struktury - chcialbym w produkcji wprowadzic kod z walidacja przed wyslaniem requesta.

**Comment by MartaNowaczyk** [comment]
Nie mamy oddzielnej specyfikacji. [Dokumentacja](https://developer.allegro.pl/documentation) jest miejscem, gdzie znajdziesz opisy i wytyczne dla struktur API.

**Comment by hahyes** [comment]
@jpulkiewicz Dodam tylko za deva, że dokumentacja jest wygenerowana na podstawie tego pliku OpenAPI 3.0: https://developer.allegro.pl/swagger.yaml
