### ISSUE TITLE
Odmowa dostępu

### ISSUE THREAD

**Issue by Toneritusz** [allegro/allegro-api#7491]
Witam

W środowisku testowym wystawiłem ofertę ale gdy prubuję pobrać parametry oferty poprzez https://api.allegro.pl.allegrosandbox.pl/sale/offers/{$offerId} to napotykam na błąd:
Error response: {"errors":[{"code":"AccessDeniedException","message":"The customer does not have permissions to perform these instructions","details":"AccessDeniedException","path":"/sale/offers/7717419308","userMessage":"The customer does not have permissions to perform these instructions"}]} HTTP status code: 403 Something went wrong
Czegoś nie zrobiłem po drodze, ale nie wiem czego.

**Comment by MartaNowaczyk** [comment]
Witam, sprawdź czy przekazujesz odpowiedni `scope allegro:api:sale:offers:read` oraz czy nie korzystasz podczas wystawiania z autoryzacji typu `client_credentials`, która nie posiada kontekstu użytkownika. W[ naszej dokumentacji](https://developer.allegro.pl/documentation/) znajdziesz odpowiednie oznaczenie, jaki typ autoryzacji wymagany jest dla danego zasobu:

- bearer-token-for-user ([code](https://developer.allegro.pl/auth/#app) lub[ device](https://developer.allegro.pl/auth/#DeviceFlow) flow),
- bearer-token-for-application ([client credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow)).

**Comment by Atomek69** [comment]
Dzień dobry, czy nie używając DCR jest możliwość jednorazowo udzielić aplikacji dostępu tak aby w przyszłości nie trzeba było ponawiać zapytania o token i manualnie dawać autoryzację poprzez zalogowanego klienta ?
