### ISSUE TITLE
How to set Handling Time to have correct delivery time at product detail

### ISSUE THREAD

**Issue by Marek-ShopStore** [allegro/allegro-api#7492]
Hello,

we are trying to set handling time in our offers so it corresponds to reality.
How does it work for computing delivery day? 

There seems to be some kind of problem as when we set P2D for product today - than for us means we need **2 whole business days** to have the product ready to dispatch it displays delivery day at product detail as Tuesday (it's Friday 16:00 now).

That is of course wrong date, it should be Thursday (+2 whole business day = Tuesday, but it's after  time when courier picks up package so we will send it in Wednesday so package arrives Thursday)

**Comment by Marek-ShopStore** [comment]
It's behaving unpredictably, it's Friday 16:37, we set following handling times and it displays delivery days as follow:

1. Tuesday
2. Tuesday
3. Wednesday
4. Friday
5. 10 days

Why is that so? There is missing Thursday.

**Comment by AureliuszBrussy** [comment]
Are you looking at the estimated delivery time shown in the offer? This is the time calculated by our algorithms, which consider the declared handling time, carrier data, and the seller's previous delivery data. You can read more [in the article](https://allegro.pl/dla-sprzedajacych/przewidywany-czas-dostawy-twojej-przesylki-AVlrm8wY3Sg). 

You will only see the information about the declared handling time of the shipment when you enter the delivery details in the offer.

**Comment by Marek-ShopStore** [comment]
I tried to translate article you provided using google translator but I didn't find answer to my question.

It seems that if we add HandlingTime to offer https://developer.allegro.pl/documentation#operation/createProductOffers delivery.handlingTime it doesn't skip weekend and it does substract weekend days from HandlingTime.
Example:
We have product with handlingTime set to: P2D
On Friday it displays product will be delivered on Tuesday so it seems it counts Saturday and Sunday.

**Comment by AureliuszBrussy** [comment]
You can change the language of an article using "Change language" in the upper right corner. For "handlingTime" we count only business days, while as I mentioned - in the offer we do not present the declared value, but we take into account many factors. If you have any remarks about the time shown in the offer, please use the [contact form](https://allegro.pl/pomoc/kontakt).

**Comment by Marek-ShopStore** [comment]
Hello, we did some testing again and it displays data that do not make sense at all:
test was conducted at 11:50 we have limit set to 13:00 and we use Allegro delivery for Czech Republic

There is what we set and what allegro.cz displays:

PT0S -> "Buy until 13:00 - tomorrow at pickup point" OK
PT24H -> "Buy until 13:00 - tomorrow at pickup point"  ERROR - should be Thursday (7.9 at pickup point)
P2D -> Friday 8.9 - OK
P3D -> Friday 8.9 - ERROR - should be Monday 11.9
P4D -> Thursday 12.9 - OK
P5D -> 8 days - OK

Error cases explained:
**PT24H** -> user buys now, we need 24 hours handling time so we will send package tomorrow, therefore delivery time cannot be tomorrow!
**P3D** -> user buys now, we need 3 days (72 hours) handling time so we will send package at Friday so user will have package at Monday

Please fix it.

**Comment by AureliuszBrussy** [comment]
Our algorithms take into account previous shipments within the declared time frame. The topic goes beyond the Allegro public API itself, so if you have comments on the performance of the delivery time prediction - [use the contact form](https://allegro.cz/pomoc/kontakt?category=e8b34607-c518-4300-83eb-be7367462e77&subjectId=fe5caa0f-ed48-44dc-9c4a-4dce55fb22da) to pass them on.
