### ISSUE TITLE
Offers are not activated

### ISSUE THREAD

**Issue by EugenBodanov** [allegro/allegro-api#7493]

**Comment by EugenBodanov** [comment]
Good day, could you please tell me where the error is in my code? The offers are being deactivated and the quantity is updated, but they are not being reactivated. 
Code:
    def update_quantity_in_Allegro(self):
        with open('updated_products_quantity.json', 'r') as file:
            quantity_products = json.load(file)

        for product in quantity_products:
            offer_id = product['id']
            new_quantity = product['quantity']
            status = product['status']


            if new_quantity == 0:
                self.deactivate_offer(offer_id)
            elif status == "ENDED" and new_quantity != 0:
                self.activate_offer(offer_id)
                self.update_product_quantity(offer_id, new_quantity)
            else:
                self.update_product_quantity(offer_id, new_quantity)

            time.sleep(1)
    def deactivate_offer(self, offer_id: str):
        data = {
            "publication": {
                "action": "END"
            },
            "offerCriteria": [
                {
                    "type": "CONTAINS_OFFERS",
                    "offers": [{"id": offer_id}]
                }
            ]
        }
        endpoint = f"/sale/offer-publication-commands/{str(uuid.uuid4())}"
        response = self.make_request(endpoint, method="PUT", data=data)
        print(response.json())
        return response.json()
{'id': '850c8350-0cb6-468b-859b-7df15f0606e5', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
{'id': '57d7f493-ae7a-48b8-9ee6-a7588d38abc1', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
{'id': '70cf2b49-daee-477c-a7e0-b808fdcc1b31', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
{'id': '4cd32d90-87c2-420f-892f-aeba55f5d8f9', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}

**Comment by EugenBodanov** [comment]
def activate_offer(self, offer_id: str):
        data = {
            "publication": {
                "action": "ACTIVATE"
            },
            "offerCriteria": [
                {
                    "type": "CONTAINS_OFFERS",
                    "offers": [{"id": offer_id}]
                }
            ]
        }
        endpoint = f"/sale/offer-publication-commands/{str(uuid.uuid4())}"
        response = self.make_request(endpoint, method="PUT", data=data)
        print(response.json())
        return response.json()

**Comment by AureliuszBrussy** [comment]
Please send the trace-id of the request where you are trying to activate an offer. You can find the trace-id in the header of our response. I'll check it out.

**Comment by EugenBodanov** [comment]
Trace ID:
{'id': '3295dbc6-92c5-4fe3-837b-e010bfd12881', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
Trace ID: bfd4167ab6fbfe86
{'id': '222b060a-233a-4ce1-a965-70f076ac99fe', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
{'id': '9045c8a9-5c41-4e1c-a382-12c10429bf70', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
Trace ID: afd2e9f59b03feed
{'id': '2ec9007b-936c-4b65-baeb-98192131df85', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
{'id': '6a18092f-19ec-4056-b702-62267e4a1e0a', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
{'id': '3e76f871-d5e1-4289-a985-89a33b4ef28f', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
{'id': '5d1c5673-ad61-4eb7-899a-51d8a61d78d4', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
{'id': 'bc1d0736-4efe-48e6-80b4-363a71393e1e', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
{'id': 'f5a78248-4452-47df-bdd3-c4f4af20b598', 'taskCount': {'total': 1, 'success': 0, 'failed': 0}}
Trace ID: 6e0e649f3ffaeb9b
{'id': '7c79d712-7a32-4504-b07a-bf8e04fa3c75', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
{'id': '6140725f-4cee-4060-ba6b-c17a8f57860a', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}
Trace ID: ff9ccb7114fe1d8d

**Comment by EugenBodanov** [comment]
Offers:
{
        "id": "14136360280",
        "quantity": 24,
        "status": "ACTIVE"
    },
    {
        "id": "14136322448",
        "quantity": 1,
        "status": "ENDED"
    },
    {
        "id": "14136115486",
        "quantity": 3,
        "status": "ENDED"
    },
    {
        "id": "14136091070",
        "quantity": 4,
        "status": "ACTIVE"
    },
    {
        "id": "14135949870",
        "quantity": 4,
        "status": "ACTIVE"
    },
    {
        "id": "14135923858",
        "quantity": 8,
        "status": "ACTIVE"
    },
    {
        "id": "14135874569",
        "quantity": 5,
        "status": "ACTIVE"
    },
    {
        "id": "14135759171",
        "quantity": 9,
        "status": "ENDED"
    },
    {
        "id": "14135633220",
        "quantity": 5,
        "status": "ENDED"
    },
    {
        "id": "14135387302",
        "quantity": 2,
        "status": "ACTIVE"
    },
    {
        "id": "14135379913",
        "quantity": 1,
        "status": "ACTIVE"
    },

**Comment by AureliuszBrussy** [comment]
Check the details of the tasked command with [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation#operation/getPublicationTasksUsingGET). This will give you the answer as to why the offer was not activated.

**Comment by EugenBodanov** [comment]
I received such message, which is strange because I published my offer through GTIN with help of the Allegro Catalog:
Publication Command Report: {'tasks': [{'offer': {'id': '14136322448'}, 'message': None, 'status': 'NEW', 'scheduledAt': '2023-08-14T09:09:38.25Z', 'finishedAt': None, 'field': 'publication', 'errors': []}]}
Publication Command Report: {'tasks': [{'offer': {'id': '14136322448'}, 'message': None, 'status': 'NEW', 'scheduledAt': '2023-08-14T09:09:38.25Z', 'finishedAt': None, 'field': 'publication', 'errors': []}]}
Publication Command Report: {'tasks': [{'offer': {'id': '14136322448'}, 'message': 'Could not change offer publication status. Your offer description and/or title say that the offered toner is a substitute. Therefore, this offer cannot be listed in the selected category. Edit the category to Allegro Electronics – Computers – Printers and Scanners – Toners – Substitutes. If the offer is already active and you want to edit it, contact us to change its category. Use the form\\:https\\://allegro\\.pl/zglos-naruszenie/oferty. In this situation, you will avoid a notice and point deduction.', 'status': 'FAIL', 'scheduledAt': '2023-08-14T09:09:38.926Z', 'finishedAt': '2023-08-14T09:09:38.925Z', 'field': 'publication', 'errors': [{'code': 'ConstraintViolationException.OfferValidation', 'message': 'Your offer description and/or title say that the offered toner is a substitute. Therefore, this offer cannot be listed in the selected category. Edit the category to Allegro Electronics – Computers – Printers and Scanners – Toners – Substitutes. If the offer is already active and you want to edit it, contact us to change its category. Use the form\\:https\\://allegro\\.pl/zglos-naruszenie/oferty. In this situation, you will avoid a notice and point deduction.', 'details': None, 'path': 'description.id', 'userMessage': 'Your offer description and/or title say that the offered toner is a substitute. Therefore, this offer cannot be listed in the selected category. Edit the category to Allegro Electronics – Computers – Printers and Scanners – Toners – Substitutes. If the offer is already active and you want to edit it, contact us to change its category. Use the form\\:https\\://allegro\\.pl/zglos-naruszenie/oferty. In this situation, you will avoid a notice and point deduction.'}]}]}
Unexpected task status: FAIL

**Comment by AureliuszBrussy** [comment]
@EugenBodanov please, report this error in the offer through [the contact form](https://allegro.pl/pomoc/kontakt) - ask for category change in the offer. They will be able to help. You can also report the error in the product itself.
