### ISSUE TITLE
Liczba sztuk równa 0 

### ISSUE THREAD

**Issue by rafaljosko** [allegro/allegro-api#7494]
Problem z  https://developer.allegro.pl/news/zakonczymy-oferte-jesli-ustawisz-liczbe-sztuk-rowna-0-nn2ZGW8yVi1

Wysyłamy prośbę o zmianę stanu magazynowego przez api na 0 - i otrzymujemy odpowiedź.

Suma sprzedanych i dostępnych sztuk nie może być mniejsza niż 1. (INVALID_SUM_OF_SOLD_AND_AVAILABLE_ITEMS)

**Comment by MartaNowaczyk** [comment]
Podaj proszę trace-id, który zwracamy w odpowiedzi z tym błędem.
