### ISSUE TITLE
Brak możliwości aktywacji konta | Martwe bramki płatnicze

### ISSUE THREAD

**Issue by from-Mateusz** [allegro/allegro-api#7495]
Utworzyłem konto typu **zwykłe** w Sandboxie. Niestety nie mogę go w pełni aktywować. Żadna z "testowych" bramek płatności nie działa tj. nie mogę nawiazac polaczenia z ich adresami.

Konto: mateusz.cz.test@gmail.com

Podobnie jest w przypadku konta **firmowego**. Tam jednak mogę wykonać "zmockowany" przelew, ale aktywacja konta trwa w nieskończoność tj. zatrzymała się na etapie **weryfikacji danych firrmy**.

Proszę o aktywację powyższego konta, abym mógł w pełni korzystać z zasobów rest api.

**Comment by MartaNowaczyk** [comment]
Podane konto zwykłe aktywowałam. Jeśli chcesz aktywować wspomniane konto firmowe, podaj to konto, sprawdzę jak wygląda sytuacja.

**Comment by MKrzeszCoder** [comment]
witam posiadam taki sam problem z kontem firmowym podpiętym do maila : krzeszowskim2002@gmail.com login :krzeszowski
bardzo prosiłbym o aktywację konta. 
Z góry dziękuję za poświęcony czas.

**Comment by Lukasz-Zurek** [comment]
@MKrzeszCoder Aktywowałem i zweryfikowałem wskazane konto.

**Comment by MKrzeszCoder** [comment]
dziękuję za pomoc
