### ISSUE TITLE
Prośba o aktywację konta

### ISSUE THREAD

**Issue by CFGauss1** [allegro/allegro-api#7496]
Witam
Proszę o aktywację konta sandbox: BQelectric

**Comment by AureliuszBrussy** [comment]
@CFGauss1 czy możesz spróbować uzupełnić dane oraz przesłać fałszywe dokumenty w tzw. "krokowcu" na stronie [Moje konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto).

**Comment by CFGauss1** [comment]
W tym momencie nie widzę już możliwości przesyłania dokumentów. Na stronie moje konto wyświetlają mi się 3 kroki pod tytułem: Wystawiaj na wielu rynkach. Zaciąłem się na kroku drugim "Uzupełnij cenniki dostaw o wysyłki międzynarodowe" Próbuje uzupełniać cenniki jednak nie pokazuje mi tego kroku jako wykonanego. Dalej blokuje mi możliwość sprzedaży.

**Comment by AureliuszBrussy** [comment]
@CFGauss1 proszę, abyś zarejestrował nowe konto firma pod innym adresem mailowym. Niestety, ale wystąpiły trudności z aktywacją tego konta (trafił w nieoczekiwany stan). 

W trakcie aktywacji proszę, aby wykonał symulację przelewu weryfikacyjnego (szybki przelew) oraz abyś uzupełnił dane (fałszywe) oraz uzupełnił dokumenty. Wróć do mnie z informacją, gdy już to zrobisz - postaram się szybko aktywować nowe konto.

**Comment by CFGauss1** [comment]
Stworzyłem nowe konto BQ_testowe i wykonałem kroki które Pan opisał.

**Comment by CFGauss1** [comment]
Proszę o aktywację :)

**Comment by AureliuszBrussy** [comment]
@CFGauss1 aktywowałem konto.

**Comment by CFGauss1** [comment]
Dziękuję za pomoc.
