### ISSUE TITLE
Brak możliwości wygenerowania paczki Allegro One Kurier

### ISSUE THREAD

**Issue by amikitiuk98** [allegro/allegro-api#7497]
Allegro returned error: Field: /serviceId - Wybrana metoda dostawy nie obsługuje tego zamówienia.
Podczas generowania etykiety nasz klient dostaje podany powyżej błąd. ID zamówienia allegro to ed3348b0-3859-11ee-a889-2d4c33393d1c, serwis z zamówienia to:
```
"method": {
            "id": "0b9bed2c-0bc1-4e1f-9694-29bb39ebb483",
            "name": "Allegro One Box, One Kurier"
```
Czy jest możliwość wygenerowania paczki w tym serwisie dla tego zamówienia?

**Comment by AureliuszBrussy** [comment]
Proszę o przesłanie trace-id wywołania, gdzie otrzymujecie wspomniany błąd o nieprawidłowym serwisie dostawy. Trace-id znajdziecie w nagłówku naszego response'a z komunikatem błędu. Ew. proproszę o identyfikator komendy, gdzie próbujecie utworzyć przesyłkę. 
Sprawdzę to.

**Comment by amikitiuk98** [comment]
Dziękuję za odpowiedź. Udało się rozwiązać sprawę po naszej stronie. W związku z tym zamykam wątek.
