### ISSUE TITLE
Utrata aktywacji konta po usunięciu aplikacji w środowisku testowym

### ISSUE THREAD

**Issue by gitrid** [allegro/allegro-api#7498]
Witam, jak w tytule - po usunięciu aplikacji w środowisku testowym, nie mogę utworzyć nowej, ze względu na rzekomy brak aktywacji konta (wcześniej się to udało). Utworzyłem nowe konto, niestety po przejściu całego procesu (i podaniu "rzeczywistych" danych adresowych zgodnie z docsami) wciąż nie ma opcji dodania aplikacji.

Nazwy kont: cartotest, cartotest3. Prośba o aktywację

**Comment by MaciejFrackowiak** [comment]
Oba konta są już aktywne.
