### ISSUE TITLE
HttpMessageNotReadableException ( An error has occurred | Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji. )

### ISSUE THREAD

**Issue by Wooconnector** [allegro/allegro-api#7499]
Hi Dear Team, 
Could you please look into my payload once again, I'm getting the same response even after following the tutorial 

Here is my payload :
{"name":"Beanie with Logo","category":{"id":"313513"},"description":{"sections":[{"items":[{"type":"TEXT","content":"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."}]}]},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/110bca\/9e518c694146ac730da8cb35409b"}],"parameters":[{"values":["Kod producenta"],"id":"224017"}],"language":"pl-PL"}

Thanks looking forward to get reply.

**Comment by MaciejFrackowiak** [comment]
I see you received error 422 with whole details: Unable to create product without proper values in all required parameters: [Marka] in category: 313513. In your request, you missed the required parameter "Brand" - you can check which parameters are required to propose a new product - please, check the flag requiredForProduct in [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). We described the process in [our tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-create-a-product).
