### ISSUE TITLE
How can I list products directly via API?

### ISSUE THREAD

**Issue by krestaml** [allegro/allegro-api#7500]
Hello, I know it is a trivial question but I can't get through it. We were trying to get on MALL but they sent us to Allegro. One thing about MALL is they have (from my view) better documentation for their API and it is easier to list products via API.
Can you guide me to "How to list products to Allegro account"? I can't get over the API auth thing. Thank you very much

**Comment by Lukasz-Zurek** [comment]
We have described authentication and authorization processes in [our guide](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY). So first of all, after [application registration](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#application-registration), you should choose authorization method. The most popular method is [Authorization Code flow](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) - which is used in situations where the application needs to perform operations on behalf of the user.

In our [documentation](https://developer.allegro.pl/documentation) you will find the appropriate markings:

- **bearer-token-for-user** - for resource means code or device authorization;
- **bearer-token-for-application** - client_credentials.

Then you can use our resources e.g. functionalities dedicated to [listing an offer with product](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6).

**Comment by hahyes** [comment]
> We were trying to get on MALL but they sent us to Allegro

@krestaml Notice: MALL doesn't exist anymore. Allegro bought them and integrated into their shop.

**Comment by krestaml** [comment]
@Lukasz-Zurek Thank you, but I've had problems with authorization process. I will try it again, but isn't there any English version? Google translate of there API docs from PL is not as good as it should be..

@hahyes Yeah, we noticed, but they did let us know 3 weeks after our application. We listed all products etc. and then they wrote us "Hey, you have to go to Allegro"...

**Comment by Lukasz-Zurek** [comment]
@krestaml You can choose a language at any time by changing location preferences settings to "English":

<img width="1270" alt="Zrzut ekranu 2023-08-18 o 07 54 46" src="https://github.com/allegro/allegro-api/assets/78350270/e9c2e45e-d100-4faa-bba1-9cbf109c7012">

<img width="1334" alt="Zrzut ekranu 2023-08-18 o 07 55 51" src="https://github.com/allegro/allegro-api/assets/78350270/8c876f4d-8935-430d-bd4d-4ca34b68618f">

If you have additional questions regarding our resources and you are not be able to find them in our guide - please don't hesitate to ask us.

**Comment by krestaml** [comment]
@Lukasz-Zurek Thank you, didn't notice the language change, it's little hidden.

Anyways, I still hasn't managed to post products via API because of authentication. I just want be sure what are the exact steps for me to CREATE an product via API instead of using form on Allegro admin to do it manually.

If I get it right, I need an developer app for, or not? This would give me Client ID and Secret which I use for generating bearer token, but if I try to use this Bearer token for "https://api.allegro.pl/sale/product-proposals" I get 403 "No access.". I usually don't have problems with integrating API but here I am confused. Sorry for bothering you with this but I really don't know how to do it, with MALL I had it done in an hour complete.. thank you one more time for your help

**Comment by Lukasz-Zurek** [comment]
@krestaml Apparently you are using a token generated via [Client_credentials flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow) - which is without user context, so you can use only these resources which are marked with **bearer-token-for-application**.

The resource which you want to use - [POST /sale/product-proposals](https://developer.allegro.pl/documentation#operation/proposeSaleProduct) is marked with **bearer-token-for-user** - so you have to use code or device authorization.

The most popular method is [Authorization Code flow](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) - which is used in situations where the application needs to perform operations on behalf of the user.

We have described authentication and authorization processes in [our guide](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY).

**Comment by krestaml** [comment]
@Lukasz-Zurek Thank you, i tried to copy your PHP code here: https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#php and created new application with all scopes checked as an web application. When I open this PHP and click the button, I am redirected to Allegro and confirm it. After that I am redirected back with code in URL as parameter, but I get this error:
`Something went wrong 401 {"error":"Unauthorized","error_description":"Unauthorized"}`
Can you help with this one? Thanks

**Comment by Lukasz-Zurek** [comment]
As I don't see your full request, it will be difficult for me to verify this case. But the `"401 Unauthorized"` error could be retrieved when **client_id:client_secret** form is encoded with Base64 incorrectly. So please make it clear if the data are correct.

You can send us a full request and response (also in json format) using our [contact form](https://allegro.pl/pomoc/kontakt). Please add Github #7500 in your message as it will be easier to trace it.

**Comment by krestaml** [comment]
@Lukasz-Zurek Thanks, I used the example "with PKCE" but had to use "without PKCE"... anyway, after an hour of trying I am still getting API errors about wrong data etc. From this point I will just do it manually via form, which is slow, but I don't know how why is this API so hard to use. I can't get a single error that would be helpful, all I am getting is in PL and still useless, because I don't know where exactly I have an error. Anyway, thank you for your help.
