### ISSUE TITLE
Sandbox account activation request

### ISSUE THREAD

**Issue by KomczeK-Dev** [allegro/allegro-api#7501]
Hello,
can you please activate our business account "**KomczeK_Test**" on Allegro.cz sandbox? Thank you.

**Comment by Lukasz-Zurek** [comment]
Your account is already activated and verified.

**Comment by Kaven01** [comment]
Can I also ask for activation, please? Account "Kaven" on https://allegro.cz.allegrosandbox.pl

**Comment by Lukasz-Zurek** [comment]
@Kaven01 I have already activated your account.
