### ISSUE TITLE
Application creation and authorization

### ISSUE THREAD

**Issue by WorkingSilence-L** [allegro/allegro-api#7503]
We currently have a company (merchant account) and have created an application, but our system wants to integrate data such as orders from other companies (merchant accounts). What should we do?

1. Authorize other merchant accounts to our own merchant accounts that have already created applications

2. Other merchant accounts must also create their own applications

Which of the above solutions should be chosen for implementation

**Comment by Lukasz-Zurek** [comment]
The most common and correct way to create an integration through our API is the first option which I want to precise.

First of all you should register your application (which you have already done), then choose authorization method that meets your needs. If you choose the most popular method like [Authorization Code Flow](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) - you can create user's authorization process which we have described closely in [our guide](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#user-authorization). So basically, for example - you can provide a button/link in your application, e.g. "Login to Allegro", which triggers a properly parameterized HTTP request to a resource that allows user authentication. After successful authorization - the user can use our functionalities - create the offers, check the orders and more - it depends on your application's capabilities.

We have described the whole authorization process in [our guide](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY).
