### ISSUE TITLE
sale product-offers multiple field parameters

### ISSUE THREAD

**Issue by PeteW4W** [allegro/allegro-api#7504]
Hello,

the field "parameters" are specified twice in this API endpoint (https://api.{environment}/sale/product-offers).
First: productSet -> product -> parameters
Second: parameters (on root)

What are the differences?

Which field "parameter" should I use for single items?

**Comment by MaciejFrackowiak** [comment]
Parameters under productSet refer to product parameters. Parameters in the root refer to offer parameters. Please, read [our tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#offer-parameters) for more information.
