### ISSUE TITLE
Can multiple application requests be initiated on the same IP?

### ISSUE THREAD

**Issue by fengzidk** [allegro/allegro-api#7505]
We are a third-party service provider (ERP), due to allegro's rules, we cannot successfully apply to be a seller, therefore, we cannot create applications.

Now, we have Seller A create an app, and we successfully make requests using this app.

However, other sellers cannot accept their stores to authorize the application of seller A.

Therefore, we want each seller to apply for an application, and then authorize their store to their own application, and these applications are all requested by our server, so the IP is the same.

We're not sure if doing so would violate allegro's rules

**Comment by MaciejFrackowiak** [comment]
Several applications can use one IP address. [API limits](https://developer.allegro.pl/tutorials/basic-information-VL6YelvVKTn#limiting-the-number-of-queries-limits) are imposed on ClientID, not on IP.
