### ISSUE TITLE
You cannot use the terms of another seller.

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#7506]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

trace-id: a9a32f5e47bbeeab
wyskakuję ciągle mi błąd 
```
You cannot use the terms of another seller.
```

pomimo że wystawione zostało z poprawnymi kodami dla tego sprzedawcy
```
"afterSalesServices": {
    "impliedWarranty": {
        "id": "e618cb9c-3b27-44df-a6d6-127ce01d0469"
    },
    "warranty": {
        "id": "3f3a0646-246f-44dd-a8db-55c0ddcc0596"
    },
    "returnPolicy": {
        "id": "2eb7cde7-406f-4c21-83d0-f92b85bc1874"
    }
},
```

**Comment by MaciejFrackowiak** [comment]
Na koncie użytkownika, z którego request jest wykonywany widzimy:
```
{
    "count": 0,
    "warranties": []
}
```
Zatem podajesz id warranty, którego nie ma na koncie.
