### ISSUE TITLE
Odświerzanie tokena

### ISSUE THREAD

**Issue by DudekPrzemek** [allegro/allegro-api#7507]
Witam, chciałem się upewnić czy dobrze rozumiem zasadę działania przedłużania ważności tokena. Otrzymałem parę `access_token ` i `refresh_token`.
Czy muszę odświeżyć token w ciągu 12 godzin czy mogę to zrobić za tydzień, bo korzystam z API tylko raz w tygodniu?

**Comment by hahyes** [comment]
@DudekPrzemek Refresh token jest ważny 3 miesiące, więc możesz odświeżyć kiedy tylko tego potrzebujesz.

**Comment by Lukasz-Zurek** [comment]
@DudekPrzemek Potwierdzam to co napisał **hahyes**. Natomiast więcej informacji o odświeżaniu tokena znajdziesz [tutaj](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena).
