### ISSUE TITLE
Prowizja od sprzedaży oferty wyróżnionej

### ISSUE THREAD

**Issue by DudekPrzemek** [allegro/allegro-api#7508]
Witam, próbuję uzyskać informacje odnośnie prowizji od sprzedaży oferty wyróżnionej przy pomocy `/pricing/offer-fee-preview` w odpowiedzi otrzymuje tylko informacje odnośnie prowizji od sprzedaży. Do wyliczenia prowizji przekazuje dane z `/sale/product-offers/{offer_id}`. 
Czy ten zasób posiada wszystkie potrzebne dane do wyliczenia prowizji dla oferty wyróżnionej?

**Comment by Lukasz-Zurek** [comment]
Nie, zasoby /sale/product-offers w swojej strukturze nie mają sekcji odpowiedzialnej za promowanie ofert. W [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-pobrac-opcje-promowania-przypisane-do-oferty) znajdziesz dedykowane zasoby do zarządzania opcjami promowania i to za ich pomocą odczytasz jakiego typu opcje promowania ma dana oferta.

**Comment by DudekPrzemek** [comment]
Pobrałem dane z zasobu `/sale/offers/{offerId}/promo-options` i otrzymałem:
```
'basePackage': {
  'id': 'emphasized10d',
  'validFrom': '2023-08-11T07:30:44.266Z',
  'validTo': '2023-08-21T07:30:43.364Z',
  'nextCycleDate': None
}
```
Wykonałem zapytanie `/pricing/offer-fee-preview` z danymi:
```
{
  'offer': {
    'parameters': [
      {
        'id': '11323',
        'name': 'Stan',
        'values': [
          'Nowy'
        ]
      }
    ],
    'sellingMode': {
      'format': 'BUY_NOW',
      'price': {
        'amount': '61.56',
        'currency': 'PLN'
      }
    },
    'category': {
      'id': '147674'
    },
    'publication': {
      'status': 'ACTIVE'
    },
  },
  "classifiedsPackages": {
    "basePackage": {
      'id': 'emphasized10d',
      'validFrom': '2023-08-11T07:30:44.266Z',
      'validTo': '2023-08-21T07:30:43.364Z',
      'nextCycleDate': None
    }
  }
}
```
Otrzymałem odpowiedź.
```
{
  'errors': [
    {
      'code': 'ERROR',
      'message': 'An error has occurred',
      'details': 'Only advertisements can have packages.',
      'path': None,
      'userMessage': 'Żądanie zawiera niepoprawny format danych.'
    }
  ]
}
```
Zrobiłem test przy użyciu sekcji "promotion" i w tym przypadku wszystko działa poprawnie.
```
{
  'offer': {
    'parameters': [
      {
        'id': '11323',
        'name': 'Stan',
        'values': [
          'Nowy'
        ]
      }
    ],
    'sellingMode': {
      'format': 'BUY_NOW',
      'price': {
        'amount': '61.56',
        'currency': 'PLN'
      }
    },
    'category': {
      'id': '147674'
    },
    'publication': {
      'status': 'ACTIVE'
    },
    "promotion": {
            "emphasized": True,
            "bold": False,
            "highlight": False,
            "departmentPage": False,
            "emphasizedHighlightBoldPackage": False
        }
  }
}
```
W które miejsce muszę podać dane z `/sale/offers/{offerId}/promo-options` abym nie otrzymał błędu?

**Comment by Lukasz-Zurek** [comment]
Zasób ten służy w tym przypadku jedynie do odczytu opcji promowania dostępnych w danej ofercie. Struktura jaka powinna zostać przekazania w żądaniu `/pricing/offer-fee-preview` powinna być zgodna z [dokumentacją](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST).
