### ISSUE TITLE
The remote server returned an error: (422) Unprocessable Entity

### ISSUE THREAD

**Issue by areklal** [allegro/allegro-api#7509]
Występuje problem z  pobieraniem wystawionych aukcji a tym samym ze zmianą ceny oferty. Do dzisiaj rano działało ok - czy coś się zmieniło od rana lub jest jakaś awaria w ApiRest??

**Comment by Lukasz-Zurek** [comment]
Nie odnotowaliśmy awarii w tym czasie. Czy sytuacja się powtarza? Jeśli tak - prześlij proszę trace-id przykładowego żądania.

**Comment by areklal** [comment]
#	Result	Protocol	Host	URL	Body	Caching	Content-Type	Process	Comments	Custom	
6	422	HTTPS	api.allegro.pl	/offers/listing?seller.id=2722090&searchMode=CLOSED&limit=100&offset=0&sort=-endTime	238		application/vnd.allegro.public.v1+json;charset=UTF-8	mailemotochemia_allegro_aukcje:727108	i odpowiedź :   {"errors":[{"code":"InvalidLimitException","message":"Invalid limit parameter value. Allowed values are 1 … 60.","details":null,"path":null,"userMessage":"Zapytanie sformułowane nieprawidłowo. Popraw zapytanie i spróbuj ponownie."}]}

**Comment by areklal** [comment]
@Lukasz-Zurek Czy ograniczenie do 60 zostało wprowadzone wczoraj?

**Comment by Lukasz-Zurek** [comment]
@areklal Nie, funkcjonuje to już od dłuższego czasu.

**Comment by areklal** [comment]
@Lukasz-Zurek to w takim razie dziwne - przestało nam działać dopiero wczoraj.  Ok, zmienimy na 60 i zobaczymy
