### ISSUE TITLE
/sale/offer-publication-commands/ ograniczenia?

### ISSUE THREAD

**Issue by dostawcaopon** [allegro/allegro-api#751]
/sale/offer-publication-commands/
próbuje zmienić status publikacji większej liczby ofert (30.000)
w odpowiedzi otrzymuję błąd: 
ServiceTimeoutException

i tak za każdym razem,
jak daję mniejsza ilość ofert np 100 czy 200 to jest ok
jest jakiś limit w tej kwestii?

przykładowy response uri 
https://api.allegro.pl/sale/offer-publication-commands/2dd6c01b-4001-42d6-8379-ca9162a0ea59

**Comment by MarcinLuczak** [comment]
@dostawcaopon tak, jest taki limit od dzisiaj. Informowaliśmy o nim w komunikacie:

[NEWS] Wprowadziliśmy limit na liczbę edytowanych ofert #749

**Comment by Uriziel01** [comment]
Bardzo fajna zmiana, teraz gdy będę chciał faktycznie wystawić 40 000 ofert to będę wysyłał 40 zapytań z czego pewnie klasycznie z 30 się nie powiedzie za pierwszym razem a z 10 także za drugim etc.. Więc lekko licząc 100 zapytań zamiast jednego.

**Comment by PawelTaberski** [comment]
@Uriziel01 Błędy mogły być spowodowane zbyt dużymi zapytaniami i przekroczeniem czasu odpowiedzi. W przypadku ograniczenia wielkości zapytań może się okazać, że wystawi Pan te oferty szybciej niż dotychczas. Jeśli pojawiły by się jakieś problemy, to prosimy o kontakt.
