### ISSUE TITLE
Nie mogę utworzyć przesyłki 

### ISSUE THREAD

**Issue by righttway** [allegro/allegro-api#7511]
Dzień dobry,

Próbuje przez API utworzyć przesyłkę do zamówienia numer:

Używam endpoint

https://api.allegro.pl/parcel-management/parcel-create-commands/b516e43c-64b2-4ba5-89bd-b04699fe6cc9

Zapytanie:

{
  "serviceId": "259b5c7a-9056-4c74-80ec-8bdc50cb0413",
  "receiver": {
    "address": {
      "street": "Parzniewska 41",
      "postCode": "05-823",
      "city": "Pruszków",
      "countryCode": "PL",
      "county": null
    },
    "email": "lsvgx52omu+18c34ca62@allegromail.pl",
    "name": "Wiktoria Wiktoria",
    "company": "Moja",
    "phone": "123456789",
    "pointId": "PL84035"
  },
  "pickup": {
    "address": {
      "street": "Parzniewska 41",
      "postCode": "05-823",
      "city": "Pruszków",
      "countryCode": "PL",
      "county": ""
    },
    "email": "cs2@4vslurs.pl",
    "name": "Customer Service",
    "company": "4Vslurs Global Market sp. z o.o.",
    "phone": "123456789",
    "pointId": null
  },
  "items": [
    {
      "dimensions": {
        "height": {
          "value": "10",
          "unit": "CENTIMETER"
        },
        "width": {
          "value": "19",
          "unit": "CENTIMETER"
        },
        "depth": {
          "value": "24",
          "unit": "CENTIMETER"
        }
      },
      "weight": {
        "value": "1",
        "unit": "KILOGRAM"
      },
      "description": "Produkty",
      "value": {
        "amount": "0.00",
        "currency": "PLN"
      },
      "type": "PACKAGE"
    }
  ],
  "type": "PACKAGE",
  "label": {
    "sender": {
      "address": {
        "street": "Parzniewska 41",
        "postCode": "05800",
        "city": "Pruszków",
        "countryCode": "PL",
        "county": null
      },
      "email": "pawel@4vslurs.pl",
      "name": "4Vslurs",
      "company": "4Vslurs",
      "phone": "123456789"
    },
    "fileFormat": "PDF",
    "referenceNumber": "ZE_42208"
  },
  "additionalServices": {
    "cashOnDelivery": {"value":{ "amount":"24.99", "currency":"PLN"}, "accountNumber": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX", "express": false},
    "options": null
  }
}

Przy użyciu endpoint https://api.allegro.pl/parcel-management/parcel-create-commands/b516e43c-64b2-4ba5-89bd-b04699fe6cc9 sprawdzamy status paczki i dostajemy taką odpowiedź:

{
    "id": "b516e43c-64b2-4ba5-89bd-b04699fe6cc9",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ANOTHER_SERVICE_NOT_AVAILABLE",
            "message": "One of required services is unavailable. Try again later.",
            "details": "One of required services is unavailable. Try again later.",
            "path": null,
            "userMessage": "Jeden z wymaganych serwisów, do poprawnego działania, jest niedostępny. Spróbuj ponownie za moment."
        }
    ]
}

Proszę o podpowiedź, gdzie jest błąd, przez Panel przesyłka może być generowana.

P.

**Comment by MaciejFrackowiak** [comment]
Wyjaśniam ten przypadek z zespołem, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Problemem w tym przypadku był adres e-mail - dokładnie literówka z requestu powodowała błąd. Z naszej strony oczywiście poprawimy komunikat błędu, który zwracamy, aby był bardziej czytelny.

**Comment by righttway** [comment]
Dziękuję :)
Teraz mam inne błędy, potestuję i dam znać czy się udało.

**Comment by righttway** [comment]
Dzień dobry,

Dziękuję, co do zapytania, wszystko udało się przeprocesować :)
Chciałbym zadać dodatkowe pytanie.

Na sandbox generuję zapytanie dla Allegro One Box i dostaję taką samą odpowiedź ("Jeden z wymaganych serwisów, do poprawnego działania, jest niedostępny. Spróbuj ponownie za moment.")

Próbuje przy użyciu adresu @ (1svgx52omu+18c34ca62@allegromail.pl) z pierwszego zapytania i punktu odbioru AL002WI1
Id transakcji do której dostaję błąd to : d5b57210-eca0-42a1-b2ef-f8f711772635

Z góry dziękuję za podpowiedź.
P.

**Comment by Lukasz-Zurek** [comment]
@righttway Wskazany mail jest błędny - **@allegromail.p**l używamy na produkcji, natomiast na sandboxie prawidłowy adres powinien posiadać **@user.allegrogroup.pl**

**Comment by righttway** [comment]
Dzień dobry,

Dziękuję za odpowiedź, czy jest jakiś uniwersalny @ na którym mogę testować na sandbox dla stworzenia wysyłki Allegro One Box?
Próbowałem różnych kombinacji zawsze z błędem. Nie widzę tego w dokumentacji.

Z góry dziękuję za podpowiedź
P.

**Comment by Lukasz-Zurek** [comment]
Nie, nie mamy uniwersalnego @, to musi być zawsze adres e-mail z konkretnego zamówienia na Allegro Sandbox.
