### ISSUE TITLE
Wysyłam z Allegro - problem z nadaniem przesyłki Allegro One Box, One Kurier - dostawa dzisiaj (parcel-create-commands)

### ISSUE THREAD

**Issue by mmodrzejewski** [allegro/allegro-api#7512]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [x ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,

Mam zgłoszenie od klienta, w związku z błędem nadania przesyłki.

command_id
67fb57dc-f002-4b18-8b84-9befabc4965d

Treść odpowiedzi:
parcel-management/parcel-create-commands/67fb57dc-f002-4b18-8b84-9befabc4965d: 

{"id":"67fb57dc-f002-4b18-8b84-9befabc4965d","parcelId":null,"status":"ERROR
","errors":[{"code":"ERROR","message":"Internal system error","details":null,"path":null,"userMessage":"error.common.internal"}]}

Która nic nie wyjaśnia. Przeanalizowałem treść żądania: struktura requestu wygląda ok - są przesłane dane zgodne z zamówieniem, a wymiary paczki chyba się mieszczą w widełkach (?)
{"height":{"value":"15","unit":"CENTIMETER"},"width":{"value":"30","unit":"CENTIMETER"},"depth":{"value":"40","unit":"CE
NTIMETER"}},"weight":{"value":"5.00","unit":"KILOGRAM"}

Metoda dostawy:
Allegro One Box, One Kurier - dostawa dzisiaj
service_id:
0e454c54-21dd-4e5c-9db2-0553724f9077

Proszę o informację, co poszło nie tak.

Przy okazji, zapytam - czy tego typu **powtarzalny** komunikat oznacza, że dane zlecenie jest już definitywnie do usunięcia? 

To dla nas byłoby istotne, bo teoretycznie mogę w naszym systemie je automatycznie odrzucać i interpretować, że przesyłki się nie uda wygenerować w takiej postaci. Obecnie takie coś zostawiamy do decyzji klienta, który może samodzielnie zlecenie usunąć z systemu i próbować nadać ponownie, a w przypadku automatyzacji jednak wolę być pewien, że tej przesyłki nie ma i już nie będzie.

pozdrawiam

**Comment by MaciejFrackowiak** [comment]
W okresie, w którym generowane było zlecenie przesyłki usługa niestety miała problem techniczny, czego efektem jest końcowy komunikat błędu. Jeżeli pojawi się przy odpytywaniu GET informacja o błędzie to zlecenie nie przejdzie już do statusu pozytywnego. Konieczne będzie przygotowanie kolejnego zlecenia.
