### ISSUE TITLE
Dokumentacja na temat zamawiam z Allegro

### ISSUE THREAD

**Issue by Levena007** [allegro/allegro-api#7514]
Witam,
Jesteśmy w trakcie integracji z Allegro i chcielibyśmy móc korzystać z DPD pickup pointów.
1.	Czy dobrze rozumiem, że nie ma możliwości aby korzystać z DPD pickup pointów z umową własną z przewoźnikiem? Nie widzę takiej funkcjonalności w Sandbox
2.	Czy jedyną metodą takiego wdrożenie jest skorzystanie z Allegro Standard? Doszła do mnie informacja, że implementacja jest dostępna jedynie poprzez Wysyłam z Allegro. Czy to prawda? Czy istnieje jakaś dokumentacja która opisywałaby proces takiej implementacji?
Mam tutaj na myśli kwestie techniczne, a nie formalne.
Będę wdzięczna za pomoc.

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
1. Zgadza się, z umową własną możesz nadawać wyłącznie kuriera DPD i kuriera DPD pobranie. Więcej informacji na temat samych metod i rozliczania znajdziesz w [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/wysylam-z-allegro-narzedzie-do-nadawania-przesylek-bezposrednio-z-konta-E7doGw8VgI1#). Natomiast w przypadku konkretnych pytań dotyczących sposobu rozliczania i umów - skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda).
2. Tak, w przypadku tej konkretnej metody dostawy, skorzystasz z "Wysyłam z Allegro", bez podpisywania umowy z przewoźnikiem. Więcej informacji na temat zasobów WZA w Allegro API znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY).
