### ISSUE TITLE
Aktywacja konta allegro sandbox

### ISSUE THREAD

**Issue by Testowefarby** [allegro/allegro-api#7516]
Założyłem konto allegro sandbox :
testy4592@gmail.com
Nie przychodzi mail aktywacyjny,
proszę o aktywację konta

**Comment by MaciejFrackowiak** [comment]
Sprawdź proszę w spam lub w katalogach Twojej poczty - wiadomość od nas przychodzi jako załącznik .eml - część skrzynek pocztowych traktuje to jako niechcianą wiadomość.

**Comment by Testowefarby** [comment]
faktycznie mail był w spamie, kolejny problem z aktywacją przelewem, w jaki sposób przejść dalej ?

**Comment by MaciejFrackowiak** [comment]
Skorzystaj proszę z dostępnego symulatora płatności i wykonaj przelew, najlepiej wybierając opcję szybkiej płatności.

**Comment by Testowefarby** [comment]
Tak robię ale wyskakuje transaction error

**Comment by MaciejFrackowiak** [comment]
Proszę skorzystaj z alternatywnej metody płatności.

**Comment by Testowefarby** [comment]
Zmieniłem na przelew tradycyjny ale konto też się nie aktywuje, jest oczekiwanie na przelew.  To samo dotyczy weryfikacji firmy . W jaki sposób to zweryfikować? Przecież to konto testowe...
Trzecia sprawa w ustawieniach dostawy nie można wybrać metody dostawy Allegro DHL. Metody dostaw są nieaktualne. Czy będzie to miało znaczenie przy testach API?
Proszę o aktywację konta

**Comment by MaciejFrackowiak** [comment]
Nie przesłałeś też dowolnych plików, aby potwierdzić dane - proszę dokończ proces aktywacji w tzw. [krokowcu](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto).

**Comment by Testowefarby** [comment]
dokumenty przesłane, proszę o potwierdzenie i aktywację

**Comment by MaciejFrackowiak** [comment]
Konto zweryfikowane.

**Comment by CSVK2022** [comment]
@MaciejFrackowiak bardzo proszę o odblokowanie sprzedaży na koncie CSVK_SB

**Comment by MaciejFrackowiak** [comment]
@CSVK2022 Spłać proszę swoje zadłużenie korzystając z symulatora płatności w zakładce [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro).

**Comment by CSVK2022** [comment]
Tym razem się udało, dziękuję.

**Comment by MarcinNowakMacopedia** [comment]
@MaciejFrackowiak  prosba o aktywację konta test_marcin. Czekam na potwierdzenie przelewu.

**Comment by Lukasz-Zurek** [comment]
@MarcinNowakMacopedia Aktywowałem i zweryfikowałem wskazane przez Ciebie konto.

**Comment by tomasz-grzesik** [comment]
Proszę o weryfikację konta: 

- Andzelika
- Stefan

**Comment by MaciejFrackowiak** [comment]
@tomasz-grzesik W przypadku obu kont musisz dokończyć proces rejestracji - tj. przesłać dowolne pliki w ramach weryfikacji dokumentów oraz wykonać przelewy - zrobisz to w zakładce Moje konto w ramach tzw. [krokowca](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto).

**Comment by tomasz-grzesik** [comment]
"Zakładając konto myślałam że weryfikacja jest konieczna tylko jedną metodą, przepraszam, wtedy nie wiedziałam, teraz naprawiam swój błąd"

**Comment by tomasz-grzesik** [comment]
![obraz](https://github.com/allegro/allegro-api/assets/66310299/3dbf4725-ac7c-405a-bdd2-610f86616f79)

**Comment by tomasz-grzesik** [comment]
Już aktywne. Czy to już automatycznie się dzieje?

**Comment by MaciejFrackowiak** [comment]
@tomasz-grzesik "Andzelika" jest już aktywne. Natomiast z kontem "Stefan" jest problem - wybrałeś opcję tylko kupowanie, dlatego pełna aktywacja konta firmowego w tym momencie nie jest możliwa. Do samego kupowania nie ma potrzeby pełnej weryfikacji.

**Comment by tomasz-grzesik** [comment]
> @tomasz-grzesik "Andzelika" jest już aktywne. Natomiast z kontem "Stefan" jest problem - wybrałeś opcję
Tak ma być - jedno konto sprzedawcy, drugie kupującego.

Dziękuję za pomoc.

**Comment by apilo-radek** [comment]
@MaciejFrackowiak , proszę o weryfikację konta firmowego `apilo`

**Comment by Lukasz-Zurek** [comment]
@apilo-radek Konto w pełni zweryfikowane i aktywne.

**Comment by MSfastcr** [comment]
Hello i would like to ask you if is possible to activate on sandbox smart dellivery. We would like to tested. 

Our account is fastcr. Thank you

**Comment by AureliuszBrussy** [comment]
@MSfastcr to have a Smart marking, you must have at least 5 unique positive ratings. At this point you have 9 ratings, while each of them is from the same user. Make 4 more purchases from different accounts and positively rate the transactions. Then your listings will be marked as Smart.

**Comment by MSfastcr** [comment]
> @MSfastcr to have a Smart marking, you must have at least 5 unique positive ratings. At this point you have 9 ratings, while each of them is from the same user. Make 4 more purchases from different accounts and positively rate the transactions. Then your listings will be marked as Smart.

Hello we already do it, but we ane not Smart . Could you please check where is problem?

**Comment by AureliuszBrussy** [comment]
@MSfastcr please be patient - the conditions have been met, the offers will soon be marked as Smart.

**Comment by yohadams** [comment]
Prośba o odblokowanie możliwości sprzedaży na koncie testAccount2262

**Comment by MaciejFrackowiak** [comment]
@yohadams Blokada już zdjęta.
