### ISSUE TITLE
Logo Allegro One i logo znacznika na mapie box/point

### ISSUE THREAD

**Issue by mwkkowalczyk** [allegro/allegro-api#7517]
Gdzie znajdę loga, aby wykorzystać do niezbędnej identyfikacji metod dostawy? 
Allegro One Box, Allegro One Point

**Comment by MaciejFrackowiak** [comment]
To temat nie dotykający bezpośrednio zasobów API, dlatego proszę skontaktuj się z [obsługą serwisu](https://allegro.pl/pomoc/kontakt).

**Comment by mwkkowalczyk** [comment]
To prawda, nie dotyczy API. Dzięki za drogowskaz :)
