### ISSUE TITLE
Pobranie wszystkich możliwych typów płatności oraz statusów zamówień

### ISSUE THREAD

**Issue by Marcel10S** [allegro/allegro-api#7518]
Witam, chciałbym uprzejmie zapytać czy jest możliwość pobrania wszystkich dostępnych typy płatności oraz statusów zamówień, jest taka możliwość z formami dostawy jednak nie widzę podobnego rozwiązania do typów i statusów, 

Znośnego weekendu :)
Marcel Stulczewski

**Comment by hahyes** [comment]
@Marcel10S Znajdziesz te informacje w dokumentacji zasobu: https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET

Typy płatności:

string (CheckoutFormPaymentType)
Enum: "CASH_ON_DELIVERY" "WIRE_TRANSFER" "ONLINE" "SPLIT_PAYMENT" "EXTENDED_TERM"

Statusy zamówień:

any (CheckoutFormStatus)
Enum: "BOUGHT" "FILLED_IN" "READY_FOR_PROCESSING" "CANCELLED"
Describes status of the form delivery and purchase options based on payment and purchase status. * BOUGHT - purchase without checkout form filled in * FILLED_IN - checkout form filled in but payment is not completed yet so data could still change * READY_FOR_PROCESSING - payment completed. Purchase is ready for processing. * CANCELLED - purchase cancelled by buyer.

**Comment by Marcel10S** [comment]
To udało mi się znaleźć, chciałem się tylko upewnić, że allegro nie zwraca tego na bieżąco w żadnym endpoicie na wypadek gdybym chciał synchronizować te wartości

**Comment by hahyes** [comment]
@Marcel10S Teoretycznie można by użyć dokumentacji w pliku OpenAPI 3.0: https://developer.allegro.pl/swagger.yaml do synchronizacji definicji tych dwóch typów, które wymieniłem. Jednakże te typy zwykle zmieniają się bardzo rzadko i deweloperzy informują o takich zmianach.

**Comment by Marcel10S** [comment]
Jasne, bardzo dziękuję za szybką odpowiedz :D
