### ISSUE TITLE
wznowienie oferty zakonczonej z powodu sprzedaży wszystkich sztuk

### ISSUE THREAD

**Issue by dostawcaopon** [allegro/allegro-api#752]
czy jest jakiś sposób na wznowienie oferty ktora zakonczyla sie z powodu sprzedazy wszystkich sztuk?
chodzi o to żeby można było zmienić wartosc "stock" z 0 na ilosc x w zakonczonej ofercie i opublikowac ją

**Comment by PawelTaberski** [comment]
@dostawcaopon Musisz najpierw uzupełnić stock, dokładnie tak jak opisał to @Rnapzsih. Więcej informacji o tych metodach znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-8-offer-publication-commands).

**Comment by dostawcaopon** [comment]
ale tym sposobem wystawie po prostu nową ofertę z nowym id, a ja chciałem wskrzesić "wyprzedaną" ofertę z jej starym id i  właściwościami, np popularnością

**Comment by PawelTaberski** [comment]
Nie wystawisz oferty pod nowym id tylko wznowisz pod starym w tym celu w pierwszej kolejności musisz ją pobrać, aby mieć strukturę jak wygląda dotychczas. Zrobisz to przy pomocy metody [GET na zasobie /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#/offer-management/getOfferUsingGET). Następnie uzupełnij stock tej oferty przy pomocy metody [PUT na zasobie /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#/offer-management/updateOfferUsingPUT) przekaż w niej całą strukturę jaką pobrałeś wcześniej GET-em. I na koniec aktywuj tą ofertę metodą [PUT na zasobie /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#/offer-management/changePublicationStatusUsingPUT).

**Comment by dostawcaopon** [comment]
ok, dzięki
