### ISSUE TITLE
opis produktu

### ISSUE THREAD

**Issue by kochanA** [allegro/allegro-api#7520]
dzień dobry tworzę ofertę na podstawie produktu. To jest wartość description jaka wysyłam przy tworzeniu produktu:

{'sections': [{'items': [{'type': 'TEXT', 'content': '<p>Kokon Pera, dwuosobowa\xa0huśtawka, to wiszący, dwuosobowy fotel marki w kolorze szarym/ciemnoszarym, który zachwyci Cię swoim stylowym designem i wygodą. Obszerny kosz o zaokrąglonym kształcie, drobny wzór plecionki i miękkie poduchy, sprawiają, że jest niesamowicie przytulny, dlatego często staje się ulubionym miejscem relaksu wszystkich domowników. Z powodzeniem sprawdzi się w ogrodzie, na tarasie, balkonie albo w pomieszczeniach zamkniętych. Funkcja złożenia umożliwia szybkie przestawienie fotela w inne miejsce. Stabilna konstrukcja zapewnia bezpieczeństwo użytkowania, a do tego jest odporna na warunki pogodowe.</p> <p> </p>'}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.allegrosandbox.pl/original/117afe/4abe190842a39d374f5be3f86c6a'}]}, {'items': [{'type': 'TEXT', 'content': '<br/> <p> Wytrzymała konstrukcja Fotel osadzony jest na stabilnej, stalowej ramie, malowanej proszkowo. Stelaż kosza jest wykonany ręcznie z trwałej plecionki, odpornej na deszcz, śnieg czy promienie słoneczne. Precyzyjny splot kosza zapewnia bezpieczeństwo użytkowania, ale również nadaje mu oryginalny, niepowtarzalny wygląd.\xa0Na podstawie znajdują się plastikowe nakładki, które stabilizują kokon. W razie potrzeby, można je zdjąć. </p>  <p>  </p>'}]}]}

Tworzy się produkt i oferta, która ma w opisie jedynie tekst. Co może być problemem ?

**Comment by Lukasz-Zurek** [comment]
@kochanA Prześlij proszę trace-id. Sprawdzę dokładnie ten konkretny przypadek.

**Comment by kochanA** [comment]
Błąd był po mojej stronie, wysyłałam złe zdjęcia. 
Mam pytanie odnośnie szablonów opisu. Wystawiając ofertę przez konto sklepowe mam do wyboru wiersze w opisie produktu :
<img width="257" alt="image" src="https://github.com/allegro/allegro-api/assets/99121757/f85bbc0b-66be-49f9-ac4c-5e2d4e7925c7">

Czy przy tworzeniu produktu przez API również jest możliwość tworzenia takiej konstrukcji ? Obecnie wysyłam tylko tekst i obraz, każde osobno. 


Zdarzyło mi się też dostać komunikaty, że w tekście nie jest dozwolone używanie tag'a np <strong> żeby go zastąpić <b>, czy jest jakaś lista dozwolonych tagów w opisie, lub jakiś szczególny sposób formatowania ?

**Comment by Lukasz-Zurek** [comment]
Tak. Wszystkie informacje znajdziesz [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty), w naszym poradniku. Zwróć uwagę na **"Najważniejsze informacje"** i **"Jak wygląda struktura opisu"**.
