### ISSUE TITLE
Brak parametru EAN w /sale/product-offers/{offerId}

### ISSUE THREAD

**Issue by ZakuroPL** [allegro/allegro-api#7521]
Aktualnie nasza aplikacja działa nam na endpoint GET https://api.{environment}/sale/offers/{offerId}
i mogliśmy pobierać EAN'y ofert response["parameters"], id parametru "225693" i w "values" mieliśmy zawsze EAN.

Zmieniamy endpoint na nowy https://api.{environment}/sale/product-offers/{offerId}.
Widzimy, że struktura response jest niemalże identyczna i jeśli chodzi o parametry tak jest, ale dla 2500 ofert dostajemy tylko jeden parametr stan nowy:
{'id': '11323', 'name': 'Stan', 'values': ['Nowy'], 'valuesIds': ['11323_1'], 'rangeValue': None}

Mimo, że produkty w ofertach mają znacznie więcej parametrów. No i używając starego requesta na sale/offers/ oczywiście te EAN'y mogę pozyskać.

**Comment by Lukasz-Zurek** [comment]
Sprawdziłem na przykładowej ofercie i po skorzystaniu z obu zasobów - zwracamy parametr 225693 (EAN (GTIN)).

Prześlij proszę tutaj przykładowe trace-id, lub szczegółowe dane, w tym response - korzystając z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619).

**Comment by ZakuroPL** [comment]
Łukaszu dziękuję za sprawdzenie. Wszystko jest dobrze. Faktycznie jest parametr EAN, ale w 'productSet'. Z racji, że są to oferty pojedynczych produktów spodziewałem się tego parametru jak wcześniej w 'parameters', a nie w 'productSet'/'parameters'

**Comment by ZakuroPL** [comment]
Łukaszu dziękuję za sprawdzenie. Wszystko jest dobrze. Faktycznie jest parametr EAN, ale w 'productSet'. Z racji, że są to oferty pojedynczych produktów spodziewałem się tego parametru jak wcześniej w 'parameters', a nie w 'productSet'/'parameters'
