### ISSUE TITLE
Nagle 25% aktywnych ofert bez parametru obowiązkowego

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#7522]
Wewnętrzne zmiany w kategoriach i parametrach w Allegro spowodowały, że na koncie na którym mamy 120 tys. ofert, to wśród nich pojawiło się aż 30 tys. aktywnych ofert dla których zniknął parametr obowiązkowy lub pojawił się nowy. Skutkiem czego nie udaje się edytować ofert. Przykład: trace-id 23b52a505195f855.

W jednej z informacji dla sprzedających dowiadujemy się, że "W aktywnych ofertach, które wystawiasz w wybranych podkategoriach, automatycznie dodamy i uzupełnimy nowy parametr". A tak się nie dzieje. Podczas sprawdzania niewypełnionych parametrów dostajemy ich w ilości ponad 30 tys.:
trace-id: f97458b85071bdda
...
trace-id: 25fdeb30f5a3a369

Kiedy możemy się spodziewać, że po tej konkretnej wewnętrznej zmianie jak i przy kolejnych parametry zostaną automatycznie uzupełnione przez Was tak jak jest to podane w informacji dla sprzedającego?

**Comment by Lukasz-Zurek** [comment]
Sprawdziłem przykładową ofertę ze wskazanego przez Ciebie trace-id: 23b52a505195f855. Oferta ta wystawiona została 6 lipca, natomiast zmiany wdrożone zostały 26 czerwca, zgodnie z [tym newsem](https://allegro.pl/dla-sprzedajacych/wprowadzilismy-zmiany-w-parametrach-dotyczacych-gier-ksiazek-i-komiksow-wweWzVoPqTm), na stronie "Dla sprzedających". Domyślam się, że chodzi Tobie właśnie o tego newsa.

Tam też informowaliśmy o automatycznym uzupełnieniu parametru "Nośnik", jednak w ofertach wystawianych przez formularz wystawiania.

**Comment by tomylee0** [comment]
Co jakiś czas znikają parametry w aktywnych ofertach. Jak zniknie w stu ofertach lub jednym tysiącu to jeszcze wydaje się to być akceptowalne. Ale blokowanie edycji aż 30 tysiącom ofert wyraźnie zaburza proces aktualizacji sprzedawanego asortymentu. Może jest jakaś szansa aby w podobnych przypadkach najpierw ustawiać w definicji kategorii nowy parametr na nieobowiązkowy, potem powoli updatować go wszystkim klientom i dopiero potem ustawiać go na obowiązkowy.

Kiedyś udało się coś zrobić w podobnej sprawie w wątku #6564 bo w ktorymś momencie napisałem:

> Wygląda na to, że powoli rezygnujecie z planowanej obowiązkowości parametru "Język". W dniu rozpoczęcia tego wątku miałem na koncie kilkadziesiąt tysięcy ofert zwracanych przez /sale/offers/unfilled-parameters. Dziś jest to już kilka tysięcy.

Oczywiście rozumiem, że mechanizm tego typu zmian wewnętrznych jest ogólny i nie dotyczy tylko REST API. Tylko, że jak ktoś obsługuje swoje konto ręcznie to nie będzie miał takiej ilości ofert i problem znikających parametrów (i blokowania edycji) nie będzie rósł do takich rozmiarów jak przy kontach z ponad 100 tys. ofert gdzie przy takiej liczbie użycie REST API jest konieczne.

**Comment by Lukasz-Zurek** [comment]
@tomylee0 Słuszna uwaga, aczkolwiek jest to niestety całkowicie poza naszym zespołem zajmującym się publicznym API i tu mogę jedynie zasugerować kontakt poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e) i w tym miejscu przekazanie sugestii j.w.

**Comment by tomylee0** [comment]
Czy gdybym wystawiał wszystkie oferty poprzez POST /sale/product-offers podając w strukturze żądania jedynie GTIN oraz cenę i ilość sztuk to czy też miałbym blokadę edycji na PATCH /sale/product-offers w opisywanym tu przypadku znikających parametrów lub pojawiających się nowych parametrów?

Chodzi mi o ten sposób który w ogóle nie wymaga znajomości parametrów produktu:

> **Jak wystawić ofertę z produktem za pomocą zasobu /sale/product-offers**
>
> Za pomocą POST /sale/product-offers przy użyciu jednego żądania wystawisz:
> - aktywną ofertę powiązaną z produktem, który istnieje w naszym Katalogu. W strukturze żądania przekaż numer GTIN (lub identyfikator produktu) oraz cenę i liczbę sztuk. Za pomocą GET /sale/products możesz sprawdzić dane produktu.

**Comment by Lukasz-Zurek** [comment]
Korzystając z [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) możesz przekazać tylko to pole, które chcesz edytować np. liczbę sztuk i w tej sytuacji nie zwrócimy Tobie błędu dotyczącego np. obowiązkowych parametrów. Błąd zwrócimy jeśli edytujesz np. sekcję **"parameters"** odpowiedzialną za parametry ofertowe - w sytuacji, gdy w ofercie brakuje któregoś obowiązkowego parametru.

**Comment by tomylee0** [comment]
Czy na pewno? Sprawdziłem przed chwilą na sandboxie. Wysyłam PATCH z tylko delivery.handlingTime ale jednak dostaję błąd o braku obowiązkowego parametru.

trace-id: 22c94e3c6817c3cb

**Comment by Lukasz-Zurek** [comment]
Zweryfikuję to dodatkowo i wkrótce wrócę do Ciebie z informacją.

**Comment by tomylee0** [comment]
To samo na produkcji. Wysyłam PATCH z:

{"delivery":{"handlingTime":"PT72H"}}

I dostaję:

"Missing required parameters: 249493"

trace-id: 7f5671c790e83680

**Comment by Lukasz-Zurek** [comment]
@tomylee0 Przepraszam, wprowadziłem Cię w błąd. Nie ukrywam, że to było w planach, jednak ostatecznie jest tak, że obojętnie co zmienisz - natkniesz się na walidację. Natomiast aby tego uniknąć, musiałbyś korzystać z zasobu [PUT /sale/offer-modification-commands](https://developer.allegro.pl/documentation#operation/modificationCommandUsingPUT), w tym przypadku nie bierzemy pod uwagę obowiązkowości parametrów.

**Comment by Lukasz-Zurek** [comment]
@tomylee0 Generalnie na walidację natkniesz się nawet w przypadku [PUT /sale/offer-modification-commands](https://developer.allegro.pl/documentation#operation/modificationCommandUsingPUT). Czyli jednak tego nie unikniesz. Byłem przekonany, że być może w inny sposób będziesz mógł to ominąć. Dopytuję jednak odpowiedniego zespołu czy planują zmiany w tym zakresie na wspomnianym zasobie PATCH. Jeżeli uzyskam informacje o takich planach - poinformuję Cię o tym w wątku.

**Comment by tomylee0** [comment]
Dzięki wielkie za informację. Wydaje się, że **generalnie dążycie do tego aby sprzedający mógł obsługiwać swoje oferty bez konieczności zaglądania ani do definicji kategorii ani do bazy produktowej**. Świadczy o tym możliwość wystawiania ofert używając jedynie GTIN (oraz oczywiście pól ustalanych wyłącznie przez sprzedającego jak cena, ilość, czas wysyłki itp.). **Ale nie uda się tego osiągnąć jeśli PATCH np. z ceną lub nowym czasem wysyłki się nie powiedzie z powodu zupełnie niezależnej od sprzedającego zmiany zestawu parametrów obowiązkowych** dla tej oferty. No bo albo znikają parametry obowiązkowe w już aktywnej ofercie gdy przenosicie ją z jednej kategorii do drugiej. Albo dodajecie nowy parametr obowiązkowy i nie ustawiacie go w ofercie automatycznie. I dlatego sprzedający nie jest w stanie zrezygnować z pobierania definicji kategorii i pobierania bazy produktowej bo nie będzie miał możliwości edycji swoich ofert jeśli sam nie uzupełni parametru.

A bardzo byśmy chcieli jak najszybciej przejść na obsługę naszych ofert używając jedynie GTIN bez konieczności dostosowywania się do regularnie zmieniających się definicji kategorii i regularnie zmieniającej się bazy produktowej. Do tego często baza produktowa nie nadąża za zmianami w definicji kategorii co często uniemożliwia obsługę ofert i pozostaje nam jedynie usuwać takie oferty.

P.S.
Nawet gdyby nie było walidacji parametrów w metodach "batch'owych" to i tak nie ma tam możliwości aktualizacji wszystkich rzeczy w ofercie (np. nie da się zmienić czasu wysyłki).

**Comment by Lukasz-Zurek** [comment]
@tomylee0 Dziękuję Ci za wszystkie Twoje uwagi. Ten temat jest dość istotny m.in. z uwagi na skalę zmian w kategoriach i bazie produktowej. Przyznam, że temat optymalizacji PATCHa pod tym kątem, był już w trakcie analiz i z tego co wiem - nadal mamy to w planach. Jeśli uda mi się uzyskać szczegóły na ten temat - wrócę do Ciebie z informacją.

**Comment by tomylee0** [comment]
Wrzucam komentarz żeby wątek się nie przeterminował.
