### ISSUE TITLE
Wznawianie ogłoszenia

### ISSUE THREAD

**Issue by Hornir91** [allegro/allegro-api#7525]
Dzień dobry.

Jeśli w ogłoszeniu ustawię parametr publication->republish = true, to rozumiem, że zostanie wznowione to samo ogłoszenie, o takim samym ID oraz będzie miało zachowaną "popularność"?

Jak długo trwa ponowna aktywacja takiego ogłoszenia przez Allegro? Potrzebowałbym pobrać nowe endingAt z wznowionego ogłoszenia, aby móc zaktualizować ten parametr u siebie.

Jeśli chodzi o pakiety dodatkowe, to one również muszą posiadać republish = true, aby zostały wznowione wraz z ogłoszeniem? Czy w przypadku ich ustawienia parametru republish na true w pakietach, ogłoszenie zostanie wznowione lecz już bez pakietów dodatkowych?

Z góry dziękuję za odpowiedź.

Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
Ogłoszenie wznowi się pod innym numerem, bez zachowania popularności. Pakiet bazowy zostanie zachowany taki sam, natomiast, tak jak piszesz, aby pakiet dodatkowy był zachowany, musi mieć wartość **true** w _republish_.

**Comment by Hornir91** [comment]
Sprawdziłem jedno ogłoszenie na produkcji z działu Motoryzacja i po wznowieniu ogłoszenie posiada takie samo id oraz ma zachowane statystyki popularności.

Przykład: ID 14039324741
<img width="412" alt="image" src="https://github.com/allegro/allegro-api/assets/53277040/632cd215-fe49-466b-8c99-e79a38a7e14a">

Jak mam to rozumieć w takim przypadku? Może chodziło Panu o inny typ lub dział, w którym znajduje się ogłoszenie?

Proszę o wyjaśnienie, gdyż muszę rozwiać wszelkie wątpliwości przed wprowadzeniem masowej aktualizacji kilku tys. ogłoszeń.

**Comment by AureliuszBrussy** [comment]
@Hornir91 przepraszam, sprawdziłem to i masz rację - ogłoszenie faktycznie wznawia się pod tym samym numerem z zachowaną popularnością.

Natomiast w kwestii pakietów dodatkowych - tutaj nie było pomyłki.
