### ISSUE TITLE
Błąd na paczce

### ISSUE THREAD

**Issue by mwkkowalczyk** [allegro/allegro-api#7526]
Dotyczy to prod, (nie sandbox).
Uuid: e3ba7a1f-bcf7-4000-aa95-a033212836da
Konto: dobrykalendarz (o ile taka informacja potrzebna, prośba o info czy taka informacja potrzebna "na zaś")

Podczas próby utworzenia listu przewozowego Allegro One Box zgłasza błąd 401 Unathorized, zaś access token jest prawidłowy - dodatkowo pojawia się informacja "Authorization header does not contain space after 'Bearer'".

Spacja po Bearer wydaje się, że jest przekazywana - ale może z Państwa strony będzie większa informacja o błędzie.
(A sandboxowo integracja testowana i nie zgłasza problemu z rzekomym brakiem spacji w header/authorization).

Prośba o weryfikację.

**Comment by AureliuszBrussy** [comment]
Nie udało mi się namierzyć takiego requestu i takiego statusu odpowiedzi dla tego użytkownika. Proszę o przesłanie trace-id wywołania. Znajdziesz je w nagłówku naszej odpowiedzi.

**Comment by mwkkowalczyk** [comment]
druga podobna sytuacja - może ten da się odnaleźć (w pierwszym może literówkę zrobiłem):
2387413d-7b4e-42b7-8dc7-6c47b53340e3

**Comment by mwkkowalczyk** [comment]
póki co zawieszam pytanie - znalazłem pewien problem po mojej stronie

**Comment by mwkkowalczyk** [comment]
@AureliuszBrussy  - niespodziewany problem - dla konta dobrykalendarz (chcieliśmy zweryfikować nowe user_code z pary device-user-code, aby docelowo uzyskać nową parę tokenów access-refresh) przy dwuetapowej weryfikacji przychodzi sms normalnie, ale jest komunikat przeglądarce "Wyczerpano limit weryfikacji kodów SMS", zaś wcale tych kodów SMS nie przyszło jakoś dużo - ze 3 sztuki
Prośba o weryfikację.


![MicrosoftTeams-image](https://github.com/allegro/allegro-api/assets/92345088/002d3951-bd24-46cd-9f63-e62e5aff7e8e)

**Comment by mwkkowalczyk** [comment]
Wątek możemy zamknąć - problem rozwiązany.

**Comment by mwkkowalczyk** [comment]
Ale póki otwarty :) to jeszcze podrzucę zapytanie dla konta dobrykalendarz na produkcji z b6677e6c-11ce-441f-a7f8-86a41e7a9bdb - co jest nie tak z tą próbą utworzenia paczki?

**Comment by Lukasz-Zurek** [comment]
@mwkkowalczyk Zwracamy Tobie błąd "Pole nie może być puste", a dotyczy to konkretnie pola **"receiver.address.city"**, w którym przekazujesz: `"city":"",`
