### ISSUE TITLE
Wdrożenie Kurier DHL i DHL Parcel Shop punkty odbioru - Śnieżka SA

### ISSUE THREAD

**Issue by fmikasniezka** [allegro/allegro-api#7527]
Dzień dobry, 
Wdrażamy usługę kurier DHL i DHL Parcel Shop punkty odbioru. Potrzebujemy przykładowe zapytanie, które nie zwraca błędu.
Obecnie mamy taki bład:
![image](https://github.com/allegro/allegro-api/assets/142798309/e8615b7c-1077-400e-89ee-aa3a2e942802)

Dodatkowo, czy jest możliwości aby nie generować tokenów ręcznie tylko dostać jeden i bedzie on zawsze działał?
Teraz token na ważnosć 12 H w teroii mozna go odswieżać do 3 miesiecy ale nasze urzadzenie nie ma takiej funkcji wiec jest to poza zakresem. Ale i tak po 3 miesiącach trzeba generować nowy z udziałem użytkownika

**Comment by fmikasniezka** [comment]
Jeśli o ten problem, to jednak przez polskie znaki. W takim razie zostaje tylko temat tego tokenu.

**Comment by Lukasz-Zurek** [comment]
@fmikasniezka Z tego co widzę w logach - błąd dotyczy samego commandID (request jest ok), który musi pasować do wzorca: `[a-f0-9]{8}(-[a-f0-9]{4}){4}[a-f0-9]{8})`.

Jeśli chodzi Twoje pytanie o token - nie ma takiej możliwości.

**Comment by fmikasniezka** [comment]
Teraz zapytywaliśmy chyba dla Allegro One nie DHL bo chcieliśmy coś mieć
![image](https://github.com/allegro/allegro-api/assets/142798309/54da4142-8e0e-4de8-8b10-0e4146e099ea)
![image](https://github.com/allegro/allegro-api/assets/142798309/63ac6b1d-f7bf-4620-87e0-c73548cd3aba)

**Comment by Lukasz-Zurek** [comment]
Adres e-mail jest błędny. Użyłeś **@allegromail.pl**, którego używamy na produkcji. W przypadku środowiska testowego Sandbox powinieneś użyć maila **@user.allegrogroup.pl**.

**Comment by fmikasniezka** [comment]
@Lukasz-Zurek Nadal mamy błąd:
![image](https://github.com/allegro/allegro-api/assets/142798309/9d598a97-4942-4b09-b829-827bd181cedb)

**Comment by Lukasz-Zurek** [comment]
@fmikasniezka Czy wskazany adres e-mail pobrany został z istniejącego zamówienia na sandboxie?

**Comment by fmikasniezka** [comment]
@Lukasz-Zurek Nie, bo w sumie nie wiemy jak generować takie zamówienia oraz jakie są istniejące.

**Comment by Lukasz-Zurek** [comment]
@fmikasniezka Konieczne jest posiadanie drugiego, zwykłego konta na Sandboxie do realizowania zakupów. Następnie za pomocą [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET) będąc autoryzowanym jako Sprzedawca, pobierzesz listę zamówień, natomiast za pomocą [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET) uzyskasz szczegóły zamówienia, w których jest również hashowany/maskowany e-mail klienta.

**Comment by fmikasniezka** [comment]
@Lukasz-Zurek Mamy teraz sukces, ale niestety zwracany jest null zamiast ID paczki
![image](https://github.com/allegro/allegro-api/assets/142798309/2245d8e1-4508-4a84-a0fe-8e1307856bb2)

**Comment by Lukasz-Zurek** [comment]
@fmikasniezka Czy jesteś w stanie podać nowy przykład takiego zachowania i np. trace-id? Weryfikujemy to obecnie z operatorem.

**Comment by fmikasniezka** [comment]
@Lukasz-Zurek Dzień dobry, przepraszam za brak odpowiedzi, byłem na urlopie. 

Potrzebujemy teraz takich danych, gdzie mogę je uzyskać?
![image](https://github.com/allegro/allegro-api/assets/142798309/7c9e307e-d4cd-441f-a3c2-df3dc282129b)

**Comment by Lukasz-Zurek** [comment]
@fmikasniezka Odpowiednik wskazanej strony na produkcji jest [pod tym adresem](https://apps.developer.allegro.pl), tam też możesz zarejestrować nową aplikację (w tym przypadku - typu "device") i uzyskać ClientId i Client Secret, czyli dane potrzebne do autoryzacji.

**Comment by fmikasniezka** [comment]
@Lukasz-Zurek Dzień dobry,
Potrzebuję jeszcze informacji, z ilu znaków składa się id Paczki allegro.

**Comment by fmikasniezka** [comment]
@Lukasz-Zurek Dziękuję.
Mam jeszcze pytanie odnośnie nr. nadania paczki od DHL. W serwisie widać ten nr nadania, np DHL 26850855739
![image](https://github.com/allegro/allegro-api/assets/142798309/be3c61e0-67fb-4d54-a0a9-c7ae3d92e87c)

Czy w interfejsie ten numer również się znajduje?
![image](https://github.com/allegro/allegro-api/assets/142798309/668c37bb-d6c4-4fcb-8147-b3e683480cf3)

**Comment by Lukasz-Zurek** [comment]
Tego typu dane zwracamy w polu **“items.waybill”**, gdy skorzystasz z [GET /parcel-management/parcels/{parcelId}](https://developer.allegro.pl/documentation/#operation/getParcelDetails).
