### ISSUE TITLE
Domena adresu email kupującego sandbox vs produkcja

### ISSUE THREAD

**Issue by lukiqs** [allegro/allegro-api#7528]
Korzystająć z zasobu **https://api.{environment}/order/checkout-forms** kupujący posiada email z domeną **user.allegrogroup.pl** (mowa tutaj o sandboxie) Czy w wesji produkcyjnej adresy email będą w **domenie allegromail.pl** ?

**Comment by Lukasz-Zurek** [comment]
Tak.

**Comment by lukiqs** [comment]
Ok, dziękuję za odpowiedź.
