### ISSUE TITLE
I have obtained the authorization code, but when trying to obtain the token, it returns a 500 (Internal Server Error).

### ISSUE THREAD

**Issue by yangsheng8** [allegro/allegro-api#7529]
**The technology stack used is**: nodejs koa。
Sensitive information has been blurred out.

**The code is as follows：**
`
const Koa = require('koa')
const Router = require('koa-router')
const cors = require('@koa/cors')
const axios = require('axios')
const base64 = require('base-64')
const bodyParser = require('koa-bodyparser')

const app = new Koa()
app.use(bodyParser())
const router = new Router()
// Use CORS middleware
app.use(
  cors({
    origin: 'http://48.119.94.110:88', // Set allowed request origins.
  })
)

router.post('/getToken', async (ctx) => {
  const { authorizationCode } = ctx.request.body

  // Call the function to retrieve the access token
  const data = await getAccessToken(authorizationCode)

  // Return the access token
  ctx.body = { data }
})

// Handle the retrieval of access token and refresh token
router.get('/callback', async (ctx) => {
  let code = ctx.query.code

  // Call the function to retrieve the access token.
  const data = await getAccessToken(code)

  // Return the access token.
  ctx.body = { data }
})

// Retrieve the access token.
const getAccessToken = async (authorizationCode) => {
  const clientId = 'b31410fa4b9qxxx3b24eef555e'
  const clientSecret =
    'VRWJX5UncOimOOzsjBJDsFjIgxxxxxxxEt6g7USOZsnOx7Ciw'
  const authorization = Buffer.from(`${clientId}:${clientSecret}`).toString(
    'base64'
  )
  const redirectUri = 'http://48.119.94.110:3000/callback' // Specify your redirect URI
  const tokenUrl = 'https://allegro.pl/auth/oauth/token'

  const headers = {
    Authorization: `Basic ${authorization}`,
    'Content-Type': 'application/x-www-form-urlencoded',
  }

  const content = `grant_type=authorization_code&code=${encodeURIComponent(
    authorizationCode
  )}&redirect_uri=${redirectUri}`

  const response = await axios.post(tokenUrl, content, { headers })

  return response.data
}`

**Comment by yangsheng8** [comment]
> Could you send me your request in json format? Another thing - I don't see that kind of clientId or redirect-uri in our database.
![Request for incorrect image](http://47.111.94.130:88/g1.png)

```javascript
const Koa = require('koa')
const Router = require('koa-router')
const cors = require('@koa/cors')
const axios = require('axios')
const base64 = require('base-64')
const bodyParser = require('koa-bodyparser')

const app = new Koa()
app.use(bodyParser())
const router = new Router()

router.post('/getToken', async (ctx) => {
  const { authorizationCode } = ctx.request.body

  // Call the function to obtain an access token.
  const data = await getAccessToken(authorizationCode)

  ctx.body = { data }
})

router.get('/callback', async (ctx) => {
  let code = ctx.query.code
  ctx.body = { data }
})

// Obtain an access token.
const getAccessToken = async (authorizationCode) => {
  const clientId = 'b31410fa4b9f43f5a44603b24eef735e'
  const clientSecret =
    'VRWJX5UncOimOOzsjBJDsFjIgK0pZYQ6XxEFCx8RAJZd916Et6g7USOZsnOx7Ciw'
  const authorization = Buffer.from(`${clientId}:${clientSecret}`).toString(
    'base64'
  )
  const redirectUri = 'http://47.111.94.130:3000/callback' // Specify your redirect URI
  const tokenUrl = 'https://allegro.pl/auth/oauth/token'

  const headers = {
    Authorization: `Basic ${authorization}`,
    'Content-Type': 'application/x-www-form-urlencoded',
  }

  const content = `grant_type=authorization_code&code=${encodeURIComponent(
    authorizationCode
  )}&redirect_uri=${redirectUri}`

  const response = await axios.post(tokenUrl, content, { headers })

  return response.data
}


app.use(router.routes()).use(router.allowedMethods())

app.listen(3000)
```

**Comment by Lukasz-Zurek** [comment]
After receiving authorization_code - you should call then e.g.: 

```
curl -X POST \
  'https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=pOPEy9Tq94aEss540azzC7xL6nCJDWto&redirect_uri=http://exemplary.redirect.uri'
  -H 'Authorization: Basic YTI...Hg=' 
```

Please look at our [guide](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#autoryzacja-uzytkownika).

**Comment by yangsheng8** [comment]
Yes, after receiving the authorization_code, I used the Koa framework in Node.js to replace curl and send a POST request. However, I encountered an error and received a 500 error message.
Do you have an example of obtaining a token using Node.js?

**Comment by Lukasz-Zurek** [comment]
No, we do not have an example of obtaining a token using Node.js. But maybe someone from this forum hopefully can help you in this case.

**Comment by yangsheng8** [comment]
> No, we do not have an example of obtaining a token using Node.js. But maybe someone from this forum hopefully can help you in this case.

Hello, I am currently using official PHP language to obtain a token. However, the client_id and client_secret in the example are fixed and unchangeable. Our company's requirement is to manage multiple Allegro accounts on our own platform, so the client_id and client_secret are passed in from the front-end as parameters instead of constants. 

I tried passing the client_id and client_secret through the URL to main.php using the following code:
```php
define('CLIENT_ID', $_GET['client_id']); 
define('CLIENT_SECRET', $_GET['client_secret']); 
```
This allowed me to obtain an authorization code. However, when trying to obtain an access token by redirecting to another URL, the client_id and client_secret were lost, resulting in the failure to obtain a token.Could you please advise on any solutions to this issue? Thank you.

**Comment by Lukasz-Zurek** [comment]
Please check our sample PHP code (with or without PKCE) in [our guide](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#user-authorization), at the end of this particular tutorial.
