### ISSUE TITLE
przedsprzedaż, wznowienie oferty

### ISSUE THREAD

**Issue by kochanA** [allegro/allegro-api#7530]
Dzień dobry, czy istnieje możliwość ustawienia przedsprzedaży oferty przez API ? przeszukałam dokumentację ale w zapytaniu "Created offer based on product" nie znalazłam żadnej informacji na ten temat. 
Przez konto sprzedażowe istnieje również możliwość wznowienia oferty jeśli została zakończona w czasie krótszym niż 30 dni, czy ta opcja jest dostępna przez API ?

**Comment by Lukasz-Zurek** [comment]
Tak. W tym celu korzystając z [POST /sale/product/offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) uzupełnij odpowiednio pola:

- **delivery.handlingTime**,
- **delivery.shipmentDate**.

Musisz tutaj również pamiętać o zaktualizowaniu informacji w opisie, zgodnie z informacjami w [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/przedmioty-w-przedsprzedazy-D5AgVlPDdiE).

Dodam, że poprzez nasze API możesz jak najbardziej wznowić ofertę. Więcej informacji na ten temat znajdziesz w [poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#publikacja-oferty).

**Comment by kochanA** [comment]
Dziękuję za odpowiedz. Mam jeszcze pytanie do commandId jak uzyskać ten parametr, który jest niezbędny do wykonania zapytania aktywującego ofertę ?

**Comment by Lukasz-Zurek** [comment]
CommandId generujesz we własnym zakresie, korzystając z dedykowanej do tego aplikacji. Przykładowo jeśli korzystasz z Postmana, możesz łatwo wygenerować ten identyfikator, np. podczas tworzenia przesyłki za pomocą:

[PUT /parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/createNewParcel)

wstawiając w miejsce {commandId}:

`{{$guid}}`

**Comment by kochanA** [comment]
Przesyłam 'trace-id': '3668cc7d9a730445' jest Pan w stanie sprawdzić co z tym zapytaniem jest nie tak ? Otrzymuje odpowiedz {'id': '727c80e8-e8e6-4639-b174-a0953eec0423', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}} status 201 a oferta ciągle jest nie aktywna

**Comment by Lukasz-Zurek** [comment]
@kochanA Oferta została ostatecznie aktywowana. Powyższa odpowiedź oznacza, że zasób zadziałał tutaj asynchronicznie. Aby otrzymać kompletny raport wykonania zadania, skorzystaj z [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET).
