### ISSUE TITLE
Product not found in Product Catalog

### ISSUE THREAD

**Issue by nikodev13** [allegro/allegro-api#7531]
Hej,
jestem świeży w temacie. Wykonuję zapytanie:
https://api.allegro.pl/sale/products?phrase=5903950240258&mode=GTIN
oraz https://api.allegro.pl/sale/products?phrase=KOZA/AB/S/N/O/DR/BLACK&mode=MPN,
jednak nie jest zwracany produkt, jednak istnieje z nim oferta o id 13747244090, z produktem o id 1a25ce29-ff21-4a34-bdec-817161396acd, link do oferty:
https://allegro.pl/oferta/piec-stalowy-koza-obrotowy-ab-fi-150-8-kw-13747244090.
I mam pytanie czy tak powinno to działać? Czy istnieje u was osobny katalog produktów oraz produktów w ofertach?

**Comment by Lukasz-Zurek** [comment]
Zgłosiłem ten temat do odpowiedniego zespołu. Jak tylko uzyskam więcej informacji - napiszę w wątku.

**Comment by Lukasz-Zurek** [comment]
Wskazany produkt nie posiada kodu EAN, natomiast wartość w kodzie producenta jest inna: `KOZA/AB/S/DR/BLACK`- dlatego nie możesz go wyszukać.

Produkt posiadał wyszukiwane przez Ciebie wartości, jednak 3 sierpnia produkt był zmieniany (usunięty EAN i zmiana wartości kodu producenta z `KOZA/AB/S/N/O/DR/BLACK` na `KOZA/AB/S/DR/BLACK`).

Natomiast oferta 13747244090 posiada wcześniejsze wartości ponieważ nie była jeszcze (po tym 3 sierpnia) edytowana.

**Comment by nikodev13** [comment]
dzięki za pomoc :)
