### ISSUE TITLE
DELIVERY_METHOD_NOT_AVAILABLE problem

### ISSUE THREAD

**Issue by jpulkiewicz** [allegro/allegro-api#7533]
Witam,

Mam problem z metoda dostway - "cos jest nie tak" - dostaje nastepujacy blad na serwerze produkcyjnum 
 
[{"code":"DELIVERY_METHOD_NOT_AVAILABLE","message":"Delivery Method is not available for this order","details":"Delivery Method is not available for this order","path":"/serviceId","userMessage":"Wybrana metoda dostawy nie obsługuje tego zamówienia"}]}

Wyprobowalem nastepujace serwisy UPS tj wszystkie z zapytania https://api.allegro.pl/parcel-management/delivery-services
- wszystkie zwracaja blad

"id": "0e4c7d59-64b6-4b06-89c3-c1d941506dd0", "service": "UPS", "name": "Allegro Kurier UPS", "carrierId": "UPS", 
 "id": "199d2a2a-7c90-4ca7-aaf3-c1d941506dd0", "service": "UPS",  "name": "Allegro Kurier UPS pobranie", "carrierId": "UPS",
"id": "0d69a62b-7a66-4bd1-9134-49dea68dccc8", "service": "UPS", "name": "Allegro Odbi\u00F3r w Punkcie UPS", "carrierId": "UPS"

Klient wybral metode dostawy "Kurier UPS" wyciag z obrazka ponizej

![image](https://github.com/allegro/allegro-api/assets/140502955/92151b5e-3451-4a1d-abd5-1f4f659e33d7)

rzeczywista odpowiedz z serwisu dla Allegro Kurier UPS
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-store, must-revalidate, no-cache, max-age=0
  x-xss-protection: 1; mode=block
  Pragma: no-cache
  X-Frame-Options: DENY
  trace-id: 721da1e2e50d496f
  Date: Tue, 22 Aug 2023 17:52:12 GMT
  X-Content-Type-Options: nosniff
  Strict-Transport-Security: max-age=31536000 ; includeSubDomains
  Expires: 0
  Content-Type: application/vnd.allegro.public.v1+json
  Content-Length: 341
}
{"id":"a5988d67-2069-4dfd-ac80-0aa5dda7220c","parcelId":null,"status":"ERROR","errors":[{"code":"DELIVERY_METHOD_NOT_AVAILABLE","message":"Delivery Method is not available for this order","details":"Delivery Method is not available for this order","path":"/serviceId","userMessage":"Wybrana metoda dostawy nie obsługuje tego zamówienia"}]}

Prosze o diagnoze gdzie jest blad.
Pozdrawiam
Jaroslaw Pulkiewicz

**Comment by AureliuszBrussy** [comment]
To jest metoda dostawy spoza oferty Allegro UPS, dlatego wymaga dodania umowy własnej z przewoźnikiem w [ustawianiach Wysłam z Allegro](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia). Po dodaniu umowy pojawi się nowy serwis dla zapytania [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation#tag/Parcel-management).

**Comment by jpulkiewicz** [comment]
Dziekuje, pozdrawiam.
