### ISSUE TITLE
Filtrowanie ofert po "Połączenie z Katalogiem Allegro"

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#7534]
Czy istnieje możliwość z poziomu API pobrać listę ofert, które nie zostały połączone z katalogiem? Chodzi mi o analogiczny mechanizm, jaki znajduje się w Allegro Mój Asortyment filtr "Połączenie z Katalogiem Allegro" [połączone / niepołączone]

**Comment by AureliuszBrussy** [comment]
Tak, możesz to zrobić - wywołaj [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) z query parametrem: "product.id.empty=true" (_GET /sale/offers?product.id.empty=true_). Zwrócimy wszystkie oferty bez powiązanego produktu.
