### ISSUE TITLE
Błąd podczas wysyłki potwierdzeń mailowych

### ISSUE THREAD

**Issue by piotrooo** [allegro/allegro-api#7535]
Nie wiem gdzie zgłosić tego typu rzeczy, więc wrzucam tutaj.

Wygląda jakby jakaś "maszynka" do wysyłania powiadomień mailowych na sandbox'ie się przycieła. Dostaję setki maili dot. sporów (różnych).

Przykład dyskusji `e357e23d-1a73-4567-9922-848c42967dc6`.

**Comment by AureliuszBrussy** [comment]
@piotrooo faktycznie, widzę takie notyfikacje. Wyjaśniam to. Wrócę z informacją.

**Comment by piotrooo** [comment]
Bardzo prosze o szybką poprawke, bo już mam 600 wiadomość na skrzynce!

**Comment by piotrooo** [comment]
Proszę o natychmiastowe przestanie spamowania mojej skrzynki odbiorczej potwierdzeniami!

To już zaczyna być niepoważne. W ciągu całego dnia przychodzą mi maile. Obecnie mam ich już ponad 1000 i cały czas przychodzą... Nie wyobrażam sobie sytuacji, aby przez całą noc przychodziły kolejne.
