### ISSUE TITLE
Problem z pobraniem ofert

### ISSUE THREAD

**Issue by SzymonZasada** [allegro/allegro-api#7536]
Po stworzeniu aplikacji i wygenerowaniu tokenu na podstawie Client_id oraz Client secret, nie moge pobrac swoich ofert chociaż mam autoryzacje.
Url: /sale/offers?limit=100&offset=1
Błąd: **403**  "errors": [
        {
            "code": "AccessDenied",
            "message": "Access is denied",
            "details": null,
            "path": null,
            "userMessage": "Brak dostępu do danego zasobu."
        }
    ]
uzywam tokenu zwróconego przez https://allegro.pl/auth/oauth/token 
Poniżej screen uprawnien aplikacji 
![image](https://github.com/allegro/allegro-api/assets/84040786/2680ce54-e253-4463-be73-90b1ed82fac9)

**Comment by Lukasz-Zurek** [comment]
Wszystko wskazuje na to, że korzystasz z autoryzacji typu `client_credentials`, która nie posiada kontekstu użytkownika. W[ naszej dokumentacji](https://developer.allegro.pl/documentation/) znajdziesz odpowiednie oznaczenie, jaki typ autoryzacji wymagany jest dla danego zasobu:

- bearer-token-for-user ([code](https://developer.allegro.pl/auth/#app) lub[ device](https://developer.allegro.pl/auth/#DeviceFlow) flow),
- bearer-token-for-application ([client credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow)).
