### ISSUE TITLE
Problem z wygenerowaniem etykiet WzA - Sandbox

### ISSUE THREAD

**Issue by wap18** [allegro/allegro-api#7537]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy próbie wygenerowania etykiety dla WzA na środowisku testowym/sandbox dostaję komunikat: 
sender.postCode - Kod pocztowy nadawcy znajduje się poza obszarem One Kuriera.
Na potrzeby testów korzystam z kodu pocztowego: 97-306
Prośba po podesłanie poprawnego kodu dla którego będę mógł wygenerować etykietę.

Pozdrawiam,
Arek Węgrzyn

**Comment by wap18** [comment]
Próbowałem z 97-300 i ten sam błąd.

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę trace-id.

**Comment by wap18** [comment]
Po odpytaniu o status wysyłki mam inny błąd
Trace id: d37af6f550966412
Aktualny błąd: 
{
    "id": "bb5f965a-41ae-11ee-be56-0242ac120002",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "DELIVERY_METHOD_NOT_AVAILABLE",
            "message": "Delivery Method is not available for this order",
            "details": "Delivery Method is not available for this order",
            "path": "/serviceId",
            "userMessage": "Wybrana metoda dostawy nie obsługuje tego zamówienia"
        }
    ]
}

ServiceID w zam: 
"method": {
            "id": "0b9bed2c-0bc1-4e1f-9694-29bb39ebb483",
            "name": "Allegro One Box, One Kurier"
        },
        
Przesłane ID w req przy tworzeniu paczki:   "serviceId": "0b9bed2c-0bc1-4e1f-9694-29bb39ebb483",
TraceID dla tworzenia paczki: 337ac105a74ab556

**Comment by Lukasz-Zurek** [comment]
@wap18 Klient wybrał metodę dostawy: 0d83955a-4297-4169-adef-9790d53b11ff - natomiast podczas tworzenia paczki przekazujesz: 0b9bed2c-0bc1-4e1f-9694-29bb39ebb483. Wybrana przez Klienta metoda musi być zgodna z **serviceId**.
