### ISSUE TITLE
Pobieranie statusu paczki dla WzA

### ISSUE THREAD

**Issue by mkawczynski** [allegro/allegro-api#7539]
Wdrożyliśmy Allegro One Box. Paczki już odbiera kurier UPS. Potrzebuję sprawdzać codziennie, czy wszystkie paczki przygotowane dla kuriera zostały przez niego przeskanowane ( czy niczego nie zostawił, ewentualnie ktoś coś pomylił - np inny kurier zabrał paczkę)
Nie mogę się doszukać sposobu na odczytanie aktualnego statusu doręczenia paczki. 
Proszę o pomoc jak to zrobić przez API.

**Comment by AureliuszBrussy** [comment]
Udostępniamy endpoint do trackingu przesyłek: [GET /order/carriers/{carrierId}/tracking](https://developer.allegro.pl/documentation#operation/getAllegroPickupDropOffPointsGET).

**Comment by mkawczynski** [comment]
Spróbowałem to wykorzystać, jednak endpoint nie zwraca żadnych danych.

Przykład:

wywołanie:
/order/carriers/ALLEGRO/tracking?waybill=1Z83583X6865342878

zwrot:
carrierId: ALLEGRO
waybills:
- waybill: 1Z83583X6865342878
  trackingDetails:

Za pomocą strony UPS można zweryfikować, że paczka została faktycznie doręczona. Próbowałem podawać parcelId zamiast numeru śledzenia, jednak nic nie pomogło.

**Comment by mkawczynski** [comment]
Już znalazłem przyczynę tego stanu, macie swój własny numer śledzenia, który można znaleźć na etykiecie jako "Reference No.1"

Pytanie jest teraz takie: w jaki sposób mogę pograć ten numer za pomocą API?

**Comment by AureliuszBrussy** [comment]
@mkawczynski skorzystaj z waybilla zwróconego w odpowiedzi dla [GET /parcel-management/parcels/{parcelId}](https://developer.allegro.pl/documentation#operation/getParcelDetails).

**Comment by mkawczynski** [comment]
Już wszystko działa, dzięki
