### ISSUE TITLE
Licencja API

### ISSUE THREAD

**Issue by oputyk** [allegro/allegro-api#754]
Dzień dobry. 
Czy można wykorzystać Państwa API do celów komercyjnych? Oczywiście taka informacja pojawiłaby się w naszym serwisie.

Pozdrawiam, Kamil Cegliński.

**Comment by oputyk** [comment]
Chcielibyśmy skorzystać ze zbioru ogłoszeń w celu ich analizy. Jest taka
możliwość?

Pozdrawiam, Kamil Cegliński.

**Comment by PawelTaberski** [comment]
Sprawdź proszę czy aplikacja jaką planujesz zbudować nie narusza naszego regulaminu. Regulamin REST API allegro jest dostępny [tutaj](https://developer.allegro.pl/rules/). Aby stwierdzić, czy taka aplikacja jest dopuszczalna musielibyśmy się zapoznać z już działającą wersją takiej apki.

**Comment by oputyk** [comment]
Aplikacja byłaby podobna w działaniu do tej - http://monitoraukcji.pl.
Pobierałaby cyklicznie oferty, aby szukać ofert według kryteriów ustalonych
przez użytkowników naszej aplikacji. Kiedy taka oferta zostałaby
znaleziona, spełniająca wymagania użytkownika, podawalibyśmy pewne
podstawowe informacje na jej temat i link do strony z tą ofertą na Państwa
serwisie. Chcielibyśmy również mieć możliwość zbierania statystyk cen itp.

**Comment by PawelTaberski** [comment]
Na tym etapie nie jesteśmy w stanie stwierdzić, czy taka aplikacja będzie dopuszczalna. Jeśli chcesz stworzyć aplikację do statystyk to przede wszystkim pamiętaj o punkcie 4.1 [regulaminu](https://developer.allegro.pl/rules/).

**Comment by oputyk** [comment]
W porządku. Nie będziemy zbierać żadnych statystyk dotyczących sprzedaży
Allegro. Zaś informacja o tym, że jakaś oferta ma źródło w Państwa serwisie
będzie również zamieszona, jak i link do niej na Państwa serwisie.

**Comment by PawelTaberski** [comment]
Tak, jak pisałem nie jesteśmy w stanie określić na podstawie samej koncepcji i pomysłu, czy taka aplikacja jest dopuszczalna. Dopiero po sprawdzeniu działającej aplikacji będziemy w stanie to potwierdzić. Jak już pisałem, przy tworzeniu proszę pamiętać o regulaminie zawarliśmy w nim co jest niedopuszczalne.

**Comment by oputyk** [comment]
Rozumiem. Czy potrzebowalibyście wówczas dostępu do kodu?
