### ISSUE TITLE
Błąd CREDENTIALS_ID_NOT_PROVIDED przy zakładaniu przesyłki

### ISSUE THREAD

**Issue by SlawekMat** [allegro/allegro-api#7540]
Dzień dobry,
próbuje założyć paczkę z przesyłka orlen i w zworcie mam komunikat "Wybrana metoda dostawy nie obsługuje tego zamówienia"

{trace-id=a34dbc104af350d3}

**Comment by AureliuszBrussy** [comment]
Spróbuj przekazać pełen serviceId (zwrócony dla [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation#operation/getAvailableDeliveryServices)) dla umowy własnej - razem z częścią po znaku `#`.
