### ISSUE TITLE
Identyfikacja zamówienia na podstawie jego adresu e-mail

### ISSUE THREAD

**Issue by VigorousGreenPanaceum** [allegro/allegro-api#7541]
Jeżeli dobrze rozumiem, każde zamówienie Allegro jest unikalnie identyfikowane za pomocą adresu e-mail (w szczegółach zamówienia ten adres e-mail jest widoczny jako e-mail kupującego).

Czy za pomocą REST API jest możliwe ustalenie szczegółów zamówienia, mając do dyspozycji jedynie powyższy adres e-mail? Chodzi mi w szczególności o metodę dostawy wybraną przez kupującego, której potrzebujemy do utworzenia przesyłki. Niestety nie mamy do dyspozycji id orderu.

Aktualnie jedyną opcję jaką widzę, to stronicowanie wszystkich zamówień użytkownika za pomocą metody GET https://api.allegro.pl/order/checkout-forms i ustalenie, które z tych zamówień ma pasujący adres e-mail. Z oczywistych względów nie rozwiązuje to za bardzo naszego problemu.

Czy jest może jakaś metoda REST API, która to umożliwia? Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Niestety nie mamy w naszym API metody, która umożliwiałaby identyfikację zamówienia po maskowanym adresie e-mail. To też oznacza, że aby móc nadawać przesyłki, potrzebny jest dostęp do zamówień.

**Comment by VigorousGreenPanaceum** [comment]
Rozumiem. Dziękuję za odpowiedź.
