### ISSUE TITLE
May I ask if there are the following interfaces

### ISSUE THREAD

**Issue by VEVOR** [allegro/allegro-api#7542]
1. Obtain promotional information

2. Obtain platform sales trends

3. Publication interface

**Comment by AureliuszBrussy** [comment]
Could you expand on each of the points so that I understand what specifically you mean under each of them? I need a little more context to understand your needs.

**Comment by VEVOR** [comment]
1. Obtain product promotion information, such as being able to query participating products when there are events

2. Sales trends of platform products, such as monthly sales volume of products

Do the documents have these two interfaces

**Comment by AureliuszBrussy** [comment]
@VEVOR thank you for expanding your questions - no, we do not provide such interfaces.
