### ISSUE TITLE
Parametr 248135 nie jest parametrem stringowym

### ISSUE THREAD

**Issue by Wooconnector** [allegro/allegro-api#7545]
Hi Team, 
Please see my payload once again, I'm not able to create the custom brand field showing error as " Parameter 248135 is not a string parameter ", I followed the same as mentioned in the tutorial, please correct me what am I missing. 

Payload : {"name":"Beanie with Logo","category":{"id":"313513"},"description":{"sections":[{"items":[{"type":"TEXT","content":"

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.<\/p>"}]}]},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/110bca\/9e518c694146ac730da8cb35409b"}],"parameters":[{"id":"248135","values":["smart deals"]},{"values":["Kod producenta"],"id":"224017"}],"language":"pl-PL"}

Thanks looking forward to hear from you!

**Comment by Lukasz-Zurek** [comment]
You should provide this parameter like this:

```
         {
          "id": "248135",
          "values": [
            "smart deals"
          ],
          "valuesIds": [
            "248135_859076"
          ]
        },
```
Or if you do not have a specific and correct brand - please choose 248135_1728479 - no brand.

I suggest using [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) as the /sale/offers resources are already marked as **Deprecated** and we are planing to remove them on **January 1, 2024**. You will find more information about these news right [here](https://developer.allegro.pl/news/at-the-beginning-of-2024-we-will-disable-the-sale-offers-resources-for-creating-and-editing-offers-k1dG88KlxHv), and more information about listing an offer with a product - [here](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6).

**Comment by rasskabak** [comment]
I have a similar issue: "Parametr 212878 nie jest parametrem stringowym."

url: https://api.allegro.pl/sale/product-proposals

payload:
 '{"name":"Czapka dziewcz\\u0119ca zimowa z pomponem","category":{"id":"89517"},"images":[{"url":"https:\\/\\/a.allegroimg.com\\/original\\/11a147\\/2ac8e9eb4a389b8ee9a5873a6d3a"}],"parameters":[{"id":"204669","valuesIds":["204669_1705499"]},{"id":"7174","valuesIds":["7174_400"],"values":["Pasmanterie.eu"]},{"id":"212878","values":[100]},{"id":"3475","valuesIds":["3475_45"]},{"id":"11323","valuesIds":["11323_1"]},{"id":"249512","valuesIds":["249512_1647425"]}],"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>Czapka dziewcz\\u0119ca zimowa z pomponem<\\/h1><ul><li><b>Kolor: 6 kremowa najja\\u015bni<\\/b><\\/li><li>Ilo\\u015b\\u0107: 1 szt<\\/li><li>Sk\\u0142ad-kompozycja: 100% akryl<\\/li><li>Wysoko\\u015b\\u0107: 20 cm<\\/li><li>Obw\\u00f3d: 33 - 55 cm<\\/li><li>\\u015arednica pompona: ok. 10 cm<\\/li><\\/ul>"}]},{"items":[{"type":"TEXT","content":"<p>Podana cena dotyczy 1 szt produktu<\\/p>"}]},{"items":[{"type":"TEXT","content":"<p>Kod produktu: 20509-870208<\\/p>"}]}]},"language":"pl-PL"}'

**Comment by Wooconnector** [comment]
Okay, 
Let me give a try. I'll get back to you soon.

**Comment by Wooconnector** [comment]
Thank you it worked ~~

**Comment by Wooconnector** [comment]
Now Could you please help me with this error "Product needs to have at least one image", I followed the same tutorial to create the images do I need to create the image again and assign to the payload and create product my payload is : {
    "category": {
        "id": "313513"
    },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "content": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
                        "type": "TEXT"
                    }
                ]
            }
        ]
    },
    "images": [
        {
            "url": "https://a.allegroimg.com/original/110bca/9e518c694146ac730da8cb35409b"
        }
    ],
    "language": "pl-PL",
    "name": "Beanie with Logo",
    "parameters": [
        {
            "id": "248135",
            "values": [
                "smart deals"
            ],
            "valuesIds": [
                "248135_859076"
            ]
        },
        {
            "id": "224017",
            "values": [
                "Kod producenta"
            ]
        }
    ]
}


Thank you looking forward to hear from you soon.

**Comment by Lukasz-Zurek** [comment]
@rasskabak The parameter 212878  is not a string parameter, so the error message is correct. Please note that this parameter is`"type": "integer"`. So you are providing it in the wrong way.

For example - you should provide these values like this:

```
 {
       "id": "212878",
       "rangeValue": {
         "from": "80",
         "to": "100"
      },
       "values": []
    }
```

You can check the parameters for this category, using **GET /sale/categories/89517/parameters**.

**Comment by Lukasz-Zurek** [comment]
@Wooconnector Please send me a trace-id for this particular request.

**Comment by Wooconnector** [comment]
Hi @Lukasz-Zurek 
Thanks for your quick response, 
We created new image again with the same source URL, Now we're following same as you mentioned above.

**Comment by Wooconnector** [comment]
Hi @Lukasz-Zurek , 
Sorry I'm stuck again with this error "You cannot provide a value suggestion for the Brand parameter without selecting an ambiguous value", and my payload is : {"name":"Beanie with Logo","category":{"id":"313513"},"description":{"sections":[{"items":[{"type":"TEXT","content":"

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.<\/p>"}]}]},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/11aca4\/e774aabe4de9a03b3e455b9fffcb"}],"parameters":[{"valuesIds":["248135_1728479"],"id":"248135","values":["smart deals"]},{"values":["Kod producenta"],"id":"224017"}],"language":"pl-PL"}

Could you please help me asap. 


Thanks

**Comment by Lukasz-Zurek** [comment]
@Wooconnector I have already written earlier that you should provide this parameter this way:

```
         {
          "id": "248135",
          "values": [
            "smart deals"
          ],
          "valuesIds": [
            "248135_859076" (this is ambiguous value)
          ]
        },
```

Or if you do not have a specific and correct brand - please choose 248135_1728479 - no brand. But you should not provide "values" with your own brand suggestion.

So it should look like this:

```
         {
          "id": "248135",
          "valuesIds": [
            "248135_1728479"
          ]
        },
```
