### ISSUE TITLE
request file to list offers

### ISSUE THREAD

**Issue by beatrizm87** [allegro/allegro-api#7547]
Hello, 

I am trying to download a file to list offers that includes all subcategories for Automotive. After we check all fields and click on 'DOWNLOAD TEMPLATE' I get this error 'Failed to generate template. This is most likely due to technical issues. Try again later.'.
Can you send me the file or check why this is happening?
The same problem is present for Collections and Art, Culture and Entertainment, Electronics, etc. I suppose this is related to the quantity of leaf categories chosen but I cannot find a limit in your site. 

Thank you in advance.
Best regards, Beatriz

**Comment by MaciejFrackowiak** [comment]
Here, we can only support topics related to the Allegro API. If you have any questions about flat files, please contact [Allegro support](https://allegro.pl/pomoc/kontakt) directly.
