### ISSUE TITLE
Rename app and move it under different account?

### ISSUE THREAD

**Issue by MERGADOengineer** [allegro/allegro-api#7548]
Hello, we have app (in beta version), that works with Allegro API (sends offers to Allegro marketplace). We already have some users, that are testing our app for some time.

The problem is
1) our app is registered with wrong name (not official name of the app) and 
2) this app is registered under wrong account (we need to move it to our official account)

Is it somehow possible to rename this app (this option is locked in app edit section) and move it under another account? So our users can keep existing tokens?

Thank you very much

**Comment by MaciejFrackowiak** [comment]
Yes, we can rename the app. However, we cannot move it to another account - you must register a new application. Also, users will not be able to keep existing tokens.
