### ISSUE TITLE
No way to get the comission back, once the reuquest has been declined?

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#7549]
Is there a way to ask for comission refund, if one has been already created was declined? I cannot delete existing one, nor can I createa new one. Is Allegro going to keep comission money, if someone makes a mistake a requested refund before customer marked the order as calceled/returned?

Thanks

**Comment by MaciejFrackowiak** [comment]
In such cases, you should contact [Allegro support](https://allegro.pl/pomoc/kontakt) directly.
