### ISSUE TITLE
Tytuł Twojej oferty lub jej dalszy opis może wprowadzać w błąd co do pochodzenia towaru, jego producenta lub marki i tym samym naruszać prawa firmy, która współpracuje z nami w ramach programu Współpraca w Ochronie Praw. W opisie Twoich ofert używasz zarejestrowanego słownego znaku towarowego w celu sprzedaży produktu innej marki (widocznej w sekcji ‘Parametry’)

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#7550]
Wystawiam ofertę. Na pierwszy rzut oka nie widzę niczego, co mogło by naruszać czyjeś prawa autorskie. Mimo tego dostaję błąd. Parametry oferty:

`Array
(
    [afterSalesServices] => stdClass Object
        (
            [impliedWarranty] => stdClass Object
                (
                    [id] => c6d2b658-b816-42e1-b387-e9fbff13e80d
                )

            [returnPolicy] => stdClass Object
                (
                    [id] => e2f0d3e1-a2dc-4eed-aa72-491b8f336440
                )

            [warranty] => stdClass Object
                (
                    [id] => f4eb7985-55a5-4272-abe3-ce2784d54d90
                )

        )

    [category] => stdClass Object
        (
            [id] => 15550
        )

    [customParameters] => Array
        (
            [0] => stdClass Object
                (
                    [name] => Wariant
                    [values] => Array
                        (
                            [0] => Kolor: 1 białoczarny
                        )

                )

            [1] => stdClass Object
                (
                    [name] => Identyfikator
                    [values] => Array
                        (
                            [0] => 5-id-12555/var-55085/set-1
                        )

                )

        )

    [delivery] => stdClass Object
        (
            [handlingTime] => PT48H
            [shippingRates] => stdClass Object
                (
                    [id] => 7a38d8b3-a04f-4bcf-801c-63535759be40
                )

        )

    [description] => stdClass Object
        (
            [sections] => Array
                (
                    [0] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <h1>Chusta / pled</h1><ul><li><b>Kolor: 1 białoczarny</b></li><li>Ilość: 1 szt</li><li>Skład-kompozycja: 100% akryl</li><li>Szerokość: 130 cm</li><li>Długość: 135 cm</li><li>Długość frędzli: 1,5 cm</li></ul>
                                        )

                                )

                        )

                    [1] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <p>Dwustronny maxi szal z wzorem w kurzą stopkę przyjemnie otuli i zagrzeje. Materiał, z którego jest wykonany jest miękki, przyjemny w dotyku. Szal założysz do płaszcza, kurtki, jeansów, botków i adidasów. Dzięki swej wielkości i kwadratowemu kształtowi daje wiele możliwości zastosowań. Końce szala są ozdobione małymi frędzlami.</p>
                                        )

                                )

                        )

                    [2] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <p>Podana cena dotyczy 1 szt produktu</p>
                                        )

                                )

                        )

                    [3] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <p>Kod produktu: 12555-770176</p>
                                        )

                                )

                        )

                )

        )

    [external] => stdClass Object
        (
            [id] => id-12555/var-55085/set-1
        )

    [id] => 14126829306
    [images] => Array
        (
            [0] => stdClass Object
                (
                    [url] => https://a.allegroimg.com/original/11fa03/76a8c148488c8ff6de7c85229309
                )

        )

    [location] => stdClass Object
        (
            [countryCode] => PL
            [province] => POMORSKIE
            [postCode] => 80-180
            [city] => Gdańsk
        )

    [name] => Chusta / pled
    [payments] => stdClass Object
        (
            [invoice] => VAT
        )

    [parameters] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 3786
                    [valuesIds] => Array
                        (
                            [0] => 3786_85
                        )

                    [values] => Array
                        (
                            [0] => Pasmanterie.eu
                        )

                )

            [1] => stdClass Object
                (
                    [id] => 203885
                    [valuesIds] => Array
                        (
                            [0] => 203885_218333
                        )

                )

            [2] => stdClass Object
                (
                    [id] => 248724
                    [valuesIds] => Array
                        (
                            [0] => 248724_1120027
                        )

                )

            [3] => stdClass Object
                (
                    [id] => 11323
                    [valuesIds] => Array
                        (
                            [0] => 11323_1
                        )

                )

            [4] => stdClass Object
                (
                    [id] => 249512
                    [valuesIds] => Array
                        (
                            [0] => 249512_1647427
                        )

                )

        )

    [sellingMode] => stdClass Object
        (
            [format] => BUY_NOW
            [price] => stdClass Object
                (
                    [amount] => 56.53
                    [currency] => PLN
                )

        )

    [stock] => stdClass Object
        (
            [available] => 2
            [unit] => UNIT
        )

    [language] => pl-PL
    [tax] => stdClass Object
        (
            [percentage] => 23.00
        )

    [product] => Array
        (
            [id] => 551b5592-a1c6-4e3e-a8d8-904321d14517
            [quantity] => Array
                (
                    [value] => 1
                )

        )

)
`

**Comment by MartaNowaczyk** [comment]
Z tego co widzę błąd może powodować opis, a dokładnie słowo "adidasów". Jeśli chcesz wyjaśnić zasady lub zgłosić wątpliwości w temacie opisu i wskazanego błędu, napisz proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
