### ISSUE TITLE
Brak możliwości nadania przesyłki poprzez Allegro One

### ISSUE THREAD

**Issue by mediablue** [allegro/allegro-api#7551]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment

Od kilku tygodni występuje problem z nadaniem paczki poprzez allegro one Box

Paczkę nadaję poprzez 
parcel-create-commands
trace-id: a85fdfdacd4994d5

Zwrotka 201

Po czym odpytuję o status
trace-id: 605a9d7593bf9667
otrzymuję 200

`
"status": "ERROR",
    "errors": [
        {
            "code": "ANOTHER_SERVICE_NOT_AVAILABLE",
            "message": "One of required services is unavailable. Try again later.",
            "details": "One of required services is unavailable. Try again later.",
            "path": null,
            "userMessage": "Jeden z wymaganych serwisów, do poprawnego działania, jest niedostępny. Spróbuj ponownie za moment."
        }
    ]`
    
Dodatkowo próbuję robić to samo po stronie frontu:
https://edge.allegro.pl.allegrosandbox.pl/shipment-management/shipments/validate

trace-id: f2757d26c8540166
response
`{"errors":[{"code":"ANOTHER_SERVICE_NOT_AVAILABLE","message":"One of required services is unavailable. Try again later.","details":"One of required services is unavailable. Try again later.","path":null,"userMessage":"Jeden z wymaganych serwisów, do poprawnego działania, jest niedostępny. Spróbuj ponownie za moment."}]}`

Jak to ma działać produkcyjnie skoro po swojej stronie macie problemy od strony frontu?

**Comment by MartaNowaczyk** [comment]
Sprawdzamy opisany przypadek, wrócę z informacją.

**Comment by rsobap** [comment]
Dzień dobry, również zgłaszam ten sam problem z nadaniem na sandbox od strony frontendu, id konta 44267336.

**Comment by MartaNowaczyk** [comment]
Ustaliliśmy, że były problemy z zewnętrzną usługą od której jesteśmy zależni. W tym momencie nie logujemy już błędów. Potwierdźcie proszę czy działanie wróciło do normy. 

@rsobap kiedy wystąpił ten błąd u Ciebie?

**Comment by MartaNowaczyk** [comment]
@rsobap Dziękuję za informację.
