### ISSUE TITLE
Automatyczna zmiana terminu wysyłki w zależności od stanu magazynowego / Automatically reschedule shipments based on stock levels

### ISSUE THREAD

**Issue by mebleteo** [allegro/allegro-api#7552]
[PL]

Cześć,

Piszę z zapytaniem czy istnieje sposób/API, który pozwala na automatyczną zmianę terminu wysyłki w zależności od stanu magazynowego? Podam przykład:

Mam produkt, który ma stan magazynowy 50 sztuk i termin realizacji 24h. 
Stan magazynowy schodzi do 0 i termin realizacji automatycznie zmienia się na np. 6 tygodni

Ponoć taki efekt można uzyskać za pomocą dedykowanego WMS/zewnętrznego oprogramowania, ale w przypadku WMS jest to bardzo droga inwestycja, a zewnętrznego oprogramowania do tej pory nie znalazłem, plus wydaje mi się, że aby korzystać z takiego oprogramowania to trzeba by było przemodelować cały sklep online.

Z góry dziękuję za odpowiedź.

[ENG]

Hi,

I'm writing to ask if there is a way/API that allows to automatically change the shipping time depending on the stock? Let me give an example:

I have a product that has a stock of 50 units and a lead time of 24 hours. 
The stock goes down to 0 and the lead time automatically changes to, say, 6 weeks

Supposedly such an effect can be achieved with a dedicated WMS/external software, but in the case of WMS it is a very expensive investment, and external software I have not found so far, plus it seems to me that in order to use such software it would be necessary to remodel the entire online store.

Thank you in advance for your reply.

**Comment by MartaNowaczyk** [comment]
Nie ma w API zasobu, który automatycznie zmienia czas wysyłki, gdy liczba produktów spadnie do zera. Jeśli produkty nie są dostępne w magazynie, oferta powinna być zakończona.
