### ISSUE TITLE
"NOT_SUPPORTED_BY_CARRIER" - The carrier does not support this operation

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#7554]
Hi, I am trying to send parcel pickup request, but I get response:
````{
    "id": "b11894b0-a538-4f37-bdc8-1fb0ce97dcc8",
    "status": "ERROR",
    "errors": [
        {
            "code": "NOT_SUPPORTED_BY_CARRIER",
            "message": "The carrier does not support this operation",
            "details": null,
            "path": "",
            "userMessage": "The carrier does not support this operation"
        }
    ]
} 
````

carrier used for the order is '1e080d8f-f20a-497a-8f88-4d184a138d2a' - 'Allegro Zasilkovna Pick-up Point payment on delivery'

I did not find a mention about carriers not supporting parcel pickup, so I am bit confused now? Could you please explain the situation? What is a proper way to handle this using API?

following the log of our comunication

````
2023-08-29 08:44:08.051 DEBUG [DefaultMessageListenerContainer-1]   RequestLogger - * Server has sent a request
> PUT http://mpi-api-integrator:8084/v1/allegro-api/parcel-management/parcel-pickup-request-commands/b11894b0-a538-4f37-bdc8-1fb0ce97dcc8
> Content-type: application/vnd.allegro.public.v1+json
> Accept: application/vnd.allegro.public.v1+json
> X-Partner-Code: 0018
> X-Eshop-Code: ALLEGRO.CZ
> Accept-Language: en-US
> Content-Length: 72
{"parcelIds":["abf6804b-1dac-40ba-9004-4e9ef5782d77"],"pickupDate":null}
 
2023-08-29 08:44:08.173 DEBUG [DefaultMessageListenerContainer-1]   RequestLogger - * Server received a response
< 201
< expires: 0
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< retry-after: 5
< x-xss-protection: 1; mode=block
< pragma: no-cache
< date: Tue, 29 Aug 2023 08:44:08 GMT
< strict-transport-security: max-age=31536000 ; includeSubDomains
< trace-id: 16a0d13f8ce5d1f4
< x-frame-options: DENY
< x-content-type-options: nosniff
< content-type: application/vnd.allegro.public.v1+json
< content-length: 126
< Location: /parcel-management/parcel-pickup-request-commands/b11894b0-a538-4f37-bdc8-1fb0ce97dcc8
{"id":"b11894b0-a538-4f37-bdc8-1fb0ce97dcc8","input":{"parcelIds":["abf6804b-1dac-40ba-9004-4e9ef5782d77"],"pickupDate":null}}
 
2023-08-29 08:44:13.504 DEBUG [DefaultMessageListenerContainer-1]   RequestLogger - * Server has sent a request
> GET http://mpi-api-integrator:8084/v1/allegro-api/parcel-management/parcel-pickup-request-commands/b11894b0-a538-4f37-bdc8-1fb0ce97dcc8
> Content-type: application/vnd.allegro.public.v1+json
> Accept: application/vnd.allegro.public.v1+json
> X-Partner-Code: 0018
> X-Eshop-Code: ALLEGRO.CZ
> Accept-Language: en-US
> Content-Length: 0

 
2023-08-29 08:44:13.558 DEBUG [DefaultMessageListenerContainer-1]   RequestLogger - * Server received a response
< 200
< expires: 0
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< x-xss-protection: 1; mode=block
< pragma: no-cache
< x-frame-options: DENY
< trace-id: 9ac8152aee04c359
< date: Tue, 29 Aug 2023 08:44:13 GMT
< x-content-type-options: nosniff
< strict-transport-security: max-age=31536000 ; includeSubDomains
< content-type: application/vnd.allegro.public.v1+json
< content-length: 250
{"id":"b11894b0-a538-4f37-bdc8-1fb0ce97dcc8","status":"ERROR","errors":[{"code":"NOT_SUPPORTED_BY_CARRIER","message":"The carrier does not support this operation","details":null,"path":"","userMessage":"The carrier does not support this operation"}]}
````

**Comment by AureliuszBrussy** [comment]
PACKETA (Zasilkovna) shipments (from Czechia to Czechia) can be sent only at dispatch points.

**Comment by ZajdaBear** [comment]
Could you please help me with other questions as well?
1) What is a proper way to hanlde this request?
2) Do you have a list of carriers, having the same requirement as Zasilkovna?

**Comment by ZajdaBear** [comment]
Hi, sry for further questions. I am trying to understand this in detail.

I understand, I have shipping labels already. that is true with all other Allegro carriers. If I understand correctly, the difference here is, that I do not issue parcel pickup. What is quite confusing for me thou is, that from Allegro GUI, I am able to request the pickup. Please see following picture.

![WhatsApp Image 2023-08-29 at 15 05 43](https://github.com/allegro/allegro-api/assets/109143627/50337e1c-e789-4c61-a2b7-14a6931b44dd)

So the questions are
1) Is creating shipment the end of the process for parcel management? (I will only mark order as sent)
2) Do I need to complete the parcel management process by performing opertaion manualy from your GUI? If not, what is this option for on your GUI?
![image](https://github.com/allegro/allegro-api/assets/109143627/4b895e4f-e8e3-4d3e-b8de-40821648ad6a)

**Comment by AureliuszBrussy** [comment]
You can read more about that in our [help article](https://allegro.cz/pomoc/pro-prodejce/zpusoby-dopravy/allegro-doprava-nastroj-pro-posilani-zasilek-primo-z-uctu-WvqL97RZYtr). In this article we mention, among other things, that you can order the arrival of a courier only with the carrier WE|DO. Packet shipments can only be sent from delivery boxes and shipping locations.
