### ISSUE TITLE
Problem z weryfikacją konta na sandbox

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#7555]
Witam,
Od dluższego czasu nie mogę zweryfikować kont na sandbox. Nie działa żaden sposób weryfikacji.
![image](https://github.com/allegro/allegro-api/assets/16481836/16e26fe0-20fd-41bd-a43c-d90acf3bf7eb)
![image](https://github.com/allegro/allegro-api/assets/16481836/ed95772f-c10d-47b3-af71-52fc9f170770)

**Comment by artzie92** [comment]
Jeden z nich: smart4store.uat@gmail.com

**Comment by artzie92** [comment]
@AureliuszBrussy 
Przy pierwszej transakcji muszę podać kod sms do weryfikacji, a nie ma opcji wyslania sms z sandbox.

Mam jedno konto w statusie weryfikacji juz od dawna. Login: aziemianski

![image](https://github.com/allegro/allegro-api/assets/16481836/95ad8c12-ff1c-41ad-b833-a229b3e8a6a9)

**Comment by AureliuszBrussy** [comment]
Aktywowałem konto aziemianski. 

Co do kod SMS - spróbuj wprowadzić kod 123456.

**Comment by artzie92** [comment]
@AureliuszBrussy ok mam to konto aktywne. Zmieniłem również smart4store_uat na biznesowe. Mogę prosić również o aktywację tego konta?

**Comment by AureliuszBrussy** [comment]
Dla konta smart4store_uat powinieneś jeszcze uzupełnić dane, tak jak przy koncie aziemianski. Dopiero wtedy będę mógł je aktywować.

**Comment by artzie92** [comment]
@AureliuszBrussy dane są uzupełnione:
![image](https://github.com/allegro/allegro-api/assets/16481836/fffe9916-a0e4-4b6d-a2ac-c2f36588494b)

**Comment by AureliuszBrussy** [comment]
Aktywowałem Twoje konto.

**Comment by artzie92** [comment]
Super dziękuję za pomoc!

**Comment by Bursaa** [comment]
Dzięń Dobry!
Czy mogę prosić o ktywacje konta na sandbox o emailu filo9bro@gmail.com

**Comment by AureliuszBrussy** [comment]
@Bursaa udzieliłem już odpowiedzi w wątku #1046.
