### ISSUE TITLE
Wrong product based on MPN

### ISSUE THREAD

**Issue by MERGADOengineer** [allegro/allegro-api#7556]
Hello, we are sending offers of our users to Allegro via API and we encountered some problem.

We are creating offers based on MPN for this client and Allegro created offer for completely different product.

Products MPN is: 8863B
It should be a motorist part, but Allegro paired it automatically with this furniture product: https://allegro.pl/oferta/szafa-idea-nabytek-120-x-178-x-52-cm-bialy-14207598884

If we check this MPN in Allegro search, it returns us our desired product also (14 times), but somehow it paired our MPN to wrong product. https://allegro.pl/listing?string=8863B&description=1

Why did this happen? Is there some way that we can prevent this behavior in future? So our clients will not offer wrong products?

API request we sent was this:

```
"productSet": "product": {"id": "8863B", "idType": "MPN"},
            "sellingMode": {"price": {"amount": "232.94", "currency":  "PLN",
            "stock": {"available": "4"}
```

Thank you!

**Comment by AureliuszBrussy** [comment]
You can check existing products with MPN by using [GET /sale/products](https://developer.allegro.pl/documentation#operation/getSaleProducts). When searching, use query parameters: `mode=MPN&phrase=8863B`. Under this MPN in our Product Catalog, there is only one product and it is "Wardrobe IDEA nábytek 120 x 178 x 52 cm White".
