### ISSUE TITLE
Błąd autoryzacji REST API po stronie programu Enova365

### ISSUE THREAD

**Issue by norbertcala** [allegro/allegro-api#7557]
Dzień dobry

Integrujemy klienta, który posiada program ENOVA365 z Waszym API produkcyjnym.

Dostajemy błąd
„Błąd autoryzacji Allegro:
{"error":"Unauthorized","error_description":"Unauthorized"}”

Klient Twierdzi, że błąd jest po stronie programu ENOVA, ale na środowisku testowym działało wszysko OK.

Gdzie szukać problemu?

Norbert

**Comment by MartaNowaczyk** [comment]
Być może próbujesz zautoryzować aplikację ze środowiska testowego na środowisku produkcyjnym. W zależności od tego, z jakiego środowiska chcesz korzystać, użyj odpowiednich danych. Jeśli nadal masz problem, prześlij proszę pełne żądanie w cURL poprzez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). W zgłoszeniu dopisz GitHub [#7557](https://github.com/allegro/allegro-api/issues/7557).

**Comment by norbertcala** [comment]
Czy moze Pani sprawdzić czy po Stronie Allegro aplikacja jest poprawnie autoryzowana? My dostaliśmy jedynie kody.

**Comment by MartaNowaczyk** [comment]
Po samym kodzie błędu tego nie sprawdzę. Potrzebuję jakieś dane identyfikujące np. trace-id by namierzyć problem w naszych logach. Poza tym obsługa aplikacji o której piszesz powinna to bez problemu sprawdzić, także sugeruję kontakt z twórcą aplikacji.

**Comment by norbertcala** [comment]
Jeśłi chodzi o dane to 
NAZWA AquastorePL
CLIENT ID 630cdd32a1b3420683869cf47d6101ce

**Comment by norbertcala** [comment]
OK - klient skasował aplikacje i prosi żebyśmy założyli nową. 
Co mam wpisać w "ścieżka aplikacji jeśli to program enova365?

**Comment by MaciejFrackowiak** [comment]
Temat kontynuowany w wątku #7562.
