### ISSUE TITLE
Brak dostępu aplikacji do zasobu offers/listing

### ISSUE THREAD

**Issue by kacperKarman** [allegro/allegro-api#7558]
Mam problem z dostępem do zasobu offers/listing z poziomu aplikacji LAZY WARRIOR podłączonej do konta toocki_sklep - otrzymuję błąd 403 z komunikatem 'No access to the specified resorce. Access is possibile only for verified applications'. 
W sekcji 'uprawnienia aplikacji' zostały zaznaczone wszystkie dostępne pozycje, ale działają tylko niektóre zasoby. 
Tą samą aplikację mam podpiętą do konta telstar_sklep i tam wszystko działa bez zarzutu, weryfikacja i generowanie tokenu też działa w taki sam sposób dla obu kont. 
O jaką weryfikację chodzi w komunikacie który otrzymuję? Pamiętam że przy pierwszym podłączeniu aplikacji do poprzedniego konta potrzebna była weryfikacja przez pracownika Allegro i dopiero po tym wszystkie zasoby zaczęły działać. Czy w tym przypadku też potrzebna jest taka weryfikacja?

**Comment by MaciejFrackowiak** [comment]
Dostęp do zasobów /offers/lsiting wymaga weryfikacji aplikacji. Jak widzę tylko aplikacja na koncie "telstar_sklep" została pozytywnie zweryfikowana. Natomiast aplikacja na koncie "toocki_sklep" takiej weryfikacji nie przeszła, stąd w rezultacie brak dostępu do zasobu i błąd 403. Zatem tak, każda aplikacja wymaga osobnej weryfikacji.

**Comment by kacperKarman** [comment]
Ok rozumiem, dziękuję za pomoc!

**Comment by marty62x** [comment]
@kacperKarman co musiałeś zrobić żeby zweryfikować aplikację na koncie `telstar_sklep` i ile tygodni to trwało? Mógłbyś prosze podzielić się takimi informacjami na marty62xx@proton.me? Udało ci się finalnie zweryfikować temat dla sprzedawcy toocki_sklep?
