### ISSUE TITLE
Allegro one 

### ISSUE THREAD

**Issue by 2024OPH** [allegro/allegro-api#7559]
Regarding the connection of MBB overseas warehouses to the Allegro one channel:
The Allegro platform requires the MBB overseas warehouse system to be connected to the Allegro one channel.
During the MBB interconnection process, the Allegro platform designates MBB and WZA as the system interconnection Allegro one channel.
WZA allows customers to register an ID with an account store, and then MBB uses this ID to connect to the WZA system and bind the Allegro one channel.
However, now one ID can only be bound to one MBB OMS account
(OMS account is the MBB user account opened by MBB for each customer).
An MBB customer can only have one OMS account, and a MBB customer has many Allegro store accounts.

Now that we have multiple store accounts on the Allegro platform, we cannot register IDs in the WZA system for multiple store accounts, and MBB cannot register multiple MBB OMS accounts for us with so many Allegro store accounts.

Now we need help from Allegro, how do we do it?

Picture A is our CS system associated allegro client ID, picture B is associated need to log in to https://apps.developer.allegro.pl/, image C is registered good client ID. When the authorize in picture A becomes active, then the client ID and SECRET registered by the customer shop are associated with the CS account
![image](https://github.com/allegro/allegro-api/assets/143609500/7d472ee3-deb8-4394-8924-10219501c54f)

**Comment by AureliuszBrussy** [comment]
From the Allegro side - a single application key (Client ID) can operate one application supporting multiple Allegro accounts. So it is a matter of rethinking the architecture on your part so as not to force the user to register a new application key (Client ID). From our point of view: a single application should have registered one Client ID.

**Comment by 2024OPH** [comment]
A. Can we have clientIDs of multiple stores correspond to one MBB warehouse account?
or
B. We use the clientID of a store to obtain the authorization of other stores in the same group of accounts
Because we have multiple stores in one group of accounts, it would be complicated to repeat the above process.

**Comment by 2024OPH** [comment]
From our point of view: a single application should have registered one Client ID.
What does single application mean?

A single application key (Client ID) can operate one application supporting multiple Allegro accounts
May I ask how to achieve it?

**Comment by MaciejFrackowiak** [comment]
For us, the application means a tool that gives its users access to Allegro API's resources. Your clients shouldn't register their own ClientIDs. The whole process of authorization we described in [our tutorial](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#introduction) - please, read it.

**Comment by 2024OPH** [comment]
[allegro 平台添加CS的方法2023.8.2日.docx](https://github.com/allegro/allegro-api/files/12492149/allegro.CS.2023.8.2.docx)

**Comment by 2024OPH** [comment]
client ID is required to use our store account password
How to register if not by us?
Third-party registration does not guarantee the security of our store.

**Comment by AureliuszBrussy** [comment]
As we mentioned - the application in the OAuth process should present itself with a single Client ID (the application developer registers the Client ID). Later in the OAuth process, authentication takes place, where the user of the Allegro account allows the application to work on his behalf. In this way, one Client ID can support multiple Allegro users, such a user does not need to have access to the account for which the Client ID is registered. You can find out more in [our guide](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY).
