### ISSUE TITLE
Tworzenie nowej aplikacji - co mam wpisać w "ścieżka aplikacji jeśli to program enova365?

### ISSUE THREAD

**Issue by norbertcala** [allegro/allegro-api#7562]
Tak jak w Temacie. 

Co mam wpisać w "ścieżka aplikacji jeśli to program enova365?

Pozdrawiam
Norbert

**Comment by MaciejFrackowiak** [comment]
W tym miejscu należy wpisać adres do przekierowania, czyli adres, pod który wysłanie zostany kod autoryzacyjny. Jeżeli nie znasz tego adresu, skontaktuj się proszę z dostawcą wykorzystywanego oprogramowania.

**Comment by norbertcala** [comment]
Ale to desktopowa aplikacja enova365, zainstalowana na komputerze. Kod autoryzacyjny musze w niej wpisać sam.

**Comment by norbertcala** [comment]
Czy jest szansa na pomoc w tej sprawie?

**Comment by MaciejFrackowiak** [comment]
Skontaktuj się z dostawcą oprogramowania, ponieważ tylko on udzieli Ci odpowiednich wskazówek w kwestii obsługi tego narzędzia.
