### ISSUE TITLE
Etykieta ZPL bez polskich znakow

### ISSUE THREAD

**Issue by jpulkiewicz** [allegro/allegro-api#7563]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzien Dobry, 

Z produkcyjnego API otrzymalem etykiete bez polskich znakow, prosze o stwierdzenie gdzie jest blad.
zgloszona paczka
{"id":"d08eec33-6199-425b-850d-04cee10ca414","parcelId":"c8c79ce3-8d5a-4425-bfed-16ae97c33bf5","status":"SUCCESS","errors":[]}

trace-id z respnse etykiety
 trace-id: a0aee1e53ba9b8d4

Pozdrawiam
Jaroslaw Pulkiewicz

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, ostatnio miała miejsce zmiana, której efektem jest brak polskich znaków - w takiej postaci etykietę otrzymujemy bezpośrednio od UPS.

**Comment by jpulkiewicz** [comment]
Dziękuje za odpowiedź.
