### ISSUE TITLE
Pytanie o zdjęcia produktów z katalogu allegro

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#7565]
Czy zdjęcia z katalogu allegro można wykorzystywać w swoich ofertach zgodnie z prawem? https://allegro.pl/dla-sprzedajacych/prawa-autorskie-do-zdjec-WEYAYdlgacB

Raczej jeśli nie byłoby to zgodne z prawem, api też nie powinno zezwalać na użycie cudzego zdjęcia przy dodawaniu nowej oferty 
 na podstawie istniejącego produktu z katalogu. 

https://allegro.pl/regulamin#artykul-5-rozpoczecie-transakcji

5.5d:
> Użytkownik z chwilą wprowadzenia do Oferty treści stanowiących przedmiot ochrony prawa autorskiego, w szczególności znaków, logotypów, wizerunku, opisu oraz zdjęć („Treść”), zezwala Spółce na nieodpłatne, niewyłączne, nieograniczone czasowo i terytorialnie korzystanie z tych Treści w następującym zakresie:

> **d. użyczania i wprowadzania do obrotu.**

Artykuł wydaje się zaprzeczać temu co jest wpisane w regulamin

**Comment by MaciejFrackowiak** [comment]
Warunki korzystania z Katalogu produktów w API są tożsame z tymi, gdy wystawiasz ofertę poprzez formularz wystawiania. Jeżeli masz jakiekolwiek pytania związane z wykorzystatniem danych z Katalogu produktów to proszę skontaktuj się bezpośrednio z [obsługą serwisu](https://allegro.pl/pomoc/kontakt).
