### ISSUE TITLE
api allegro GET/SALE/OFFER

### ISSUE THREAD

**Issue by kasia202014** [allegro/allegro-api#7566]
Próbuje juz 3 dzien - chce pobrac aktualna liste ofert bez filtrowania i otrzymuje w odpowiedzi pusty slownik - naglowek i token przechodzi
jesli chodzi o zasoby to pobiera liste kategorrii, jednak patrzac na dokumentacje nie widze gdzie jest blad:

import requests
import json

CLIENT_ID='xxx'
CLIENT_SECRET='yyy'

TOKEN_URL = "https://allegro.pl/auth/oauth/token"

def get_access_token():
    try:
        data = {'grant_type': 'client_credentials'}
        access_token_response = requests.post(TOKEN_URL, data=data, verify=False,
                                              allow_redirects=False, auth=(CLIENT_ID, CLIENT_SECRET))
        tokens = json.loads(access_token_response.text)
        access_token = tokens['access_token']
        return access_token
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)

def get_offers_list(token):
    try:
        url = 'https://api.allegro.pl/sale/offers?limit=100&offset=1' 
        headers = {'Authorization':f'Bearer {token}', 
                   'Accept': 'application/vnd.allegro.public.v1+json'}
        main_offer_result = requests.get(url, headers=headers, verify=True)
        return main_offer_result
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)
        
        
def main():
    token = get_access_token()
#    main_categories = get_main_categories(token)
    main_offers=get_offers_list(token)
#    print(main_categories.json())
    main_offers=dict()
    print(main_offers)
    
if __name__ =="__main__":
    main()

**Comment by MaciejFrackowiak** [comment]
Zasób [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) wymaga autoryzacji typu "bearer-token-for-user", a Ty korzystasz z autoryzacji client_credentials, czyli "bearer-token-for-application". Zmień autoryzację na [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow, a otrzymasz listę ofert.

**Comment by kasia202014** [comment]
zmienione w ustawienia aplikacji niestety caly czas zwraca pusty slownik

**Comment by kasia202014** [comment]
zmienilam przechowywanie wyniku na slownik przed i zwraca nastepujacy blad:


{'errors': [{'code': 'AccessDenied', 'message': 'Access is denied', 'details': None, 'path': None, 'userMessage': 'No access to the specified resource.'}]}

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swojego wywołania.

**Comment by kasia202014** [comment]
Jak moge pobrac trace-id do kazdego wywolania?

**Comment by MaciejFrackowiak** [comment]
Trace-id zwracamy w nagłówku odpowiedzi, który od nas otrzymujesz do swojego wywołania.

**Comment by kasia202014** [comment]
wg mnie on nie jest pobierany

ef get_access_token():
    try:
        data = {'grant_type': 'client_credentials'}
        access_token_response = requests.post(TOKEN_URL, data=data, verify=False,
                                              allow_redirects=False, auth=(CLIENT_ID, CLIENT_SECRET))
        tokens = json.loads(access_token_response.text)
        access_token = tokens['access_token']
        return access_token
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)
        
#Jeśli chcemy pobrać więcej niż jeden zasób, pomijamy w ścieżce identyfikator. Przykładowe pobranie listy kategorii Allegro:        
# GET https://api.allegro.pl/sale/categories
# GET https://api.allegro.pl/sale/categories/2
#Wersjonowanie zasobów
#application/vnd.allegro.public.v1+json

        
def get_main_categories(token):
    try:
        url = "https://api.allegro.pl/sale/categories"
        headers = {'Authorization': f'Bearer {token}' , 'Accept': "application/vnd.allegro.public.v1+json"}
        main_categories_result = requests.get(url, headers=headers, verify=False)
        return main_categories_result
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)

        
def get_offers_list(token):
    try:
#        url = 'https://api.allegro.pl/sale/offers?publication.status=ACTIVE' 
        url = 'https://api.allegro.pl//offers/listening'
        headers = {'Authorization': f'Bearer {token}' , 'Accept': "application/vnd.allegro.public.v1+json"}
        main_offer_result = requests.get(url, headers=headers, verify=True)
        return main_offer_result
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)

**Comment by MaciejFrackowiak** [comment]
Wywołujesz inny zasób aniżeli wskazałaś w zgłoszeniu. Zamiast [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) wywołujesz [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) - zasób, do którego dostęp jest limitowany i stąd komunikat błędu. Proszę nanieś niezbędne poprawki.

**Comment by kasia202014** [comment]
wywołanie poprawione

        
def get_offers_list(token):
    try:
#        url = 'https://api.allegro.pl/sale/offers?publication.status=ACTIVE' 
        url = 'https://api.allegro.pl/sale/offers?'
        headers = {'Authorization': f'Bearer {token}' , 'Accept': "application/vnd.allegro.public.v1+json"}
        main_offer_result = requests.get(url, headers=headers)
        return main_offer_result
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)
        
błąd ten sam

**Comment by kasia202014** [comment]
domyślam sie o co chodzi - zgodnie z podpowiedzia do zgłoszenia:
 Brak aukcji na listingu #2202

lista ofert, które chce pobrac widnieja od dluzszego zasu (od kiedy istnieje sklep) na tym samym id - wiecej niz rok
Pytanie jak moge rozwiązac ten problem hurtowo?
nie ma opcji ze przezjde przez ponad 3000 ogloszen "recznie" i zapisze zmiany, zeby miec mozliwosc pobrania listy offert

**Comment by MaciejFrackowiak** [comment]
Jeżeli nadal otrzymujesz błąd 403 to oznacza, że nadal korzystasz z autoryzacji client_credentials. Nie jest to bynajmniej związane z podlinkowanym wątkiem.

**Comment by kasia202014** [comment]
nie otrzymuje bledu 403 - jestem aktualnie na device

w odpowiedzi otrzymuje <Response [200]> lub
blad, który juz wczesniej wklejalam

Przyznam szczerze, ze nie wiem juz skad wynika blad bo probowalam juz wsystkiego

**Comment by MaciejFrackowiak** [comment]
Odpowiedź 200 to prawidłowa odpowiedź, dla której zwracamy listę ofert na danym koncie. Czy na koncie, na którym jesteś zautoryzowana posiadasz oferty bądź ich drafty?

**Comment by kasia202014** [comment]
tak aktualnie posiadam pod 3000 ofert aktywnych

**Comment by MaciejFrackowiak** [comment]
Jednym słowem - proszę podaj nam trace-id wywołania, tylko tak możemy sprawdzić stan faktyczny.

**Comment by kasia202014** [comment]
prosze o informacje jak moge wywolac trace-id

**Comment by kasia202014** [comment]
po rozkodowaniu tokena otrzymalam informacje o uprawnieniach dla aplikacji device:

{
  "alg": "RS256",
  "typ": "JWT"
}

{
  "scope": [
    "allegro:api:orders:read",
    "allegro:api:fulfillment:read",
    "allegro:api:profile:write",
    "allegro:api:fulfillment:write",
    "allegro:api:sale:offers:write",
    "allegro:api:billing:read",
    "allegro:api:campaigns",
    "allegro:api:disputes",
    "allegro:api:bids",
    "allegro:api:sale:offers:read",
    "allegro:api:shipments:write",
    "allegro:api:orders:write",
    "allegro:api:ads",
    "allegro:api:payments:write",
    "allegro:api:sale:settings:write",
    "allegro:api:profile:read",
    "allegro:api:ratings",
    "allegro:api:sale:settings:read",
    "allegro:api:payments:read",
    "allegro:api:shipments:read",
    "allegro:api:messaging"
  ],
  "allegro_api": true,
  "iss": "https://allegro.pl",
  "exp": 1693600914,
  "jti": "9233698b-5882-48ea-9fde-f6cbfe6478aa",
  "client_id": "xxx"
}

**Comment by MaciejFrackowiak** [comment]
W nagłówku odpowiedzi od nas (Headers) znajduje się ta wartość w polu "trace-id".

**Comment by kasia202014** [comment]
juz pisalam nie wyswietla sie zaden naglowek tylko slownik z definicja wyjatkow

**Comment by MaciejFrackowiak** [comment]
Patrząc jeszcze na zdekodowany token - brakuje w nim wpisu "user_name", co oznacza, że cały czas korzystasz z zautoryzacji "client_credentials", a nie device flow jak piszesz.

**Comment by jezewskiBNetrox** [comment]
@kasia202014 Nagłówki odpowiedzi powinny u ciebie być w: `main_offer_result.headers` zgodnie z tym, co mówi dokumentacja tutaj: https://www.w3schools.com/python/ref_requests_get.asp

**Comment by kasia202014** [comment]
zrzuca blad 

{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}

**Comment by MaciejFrackowiak** [comment]
Na podstawie trace-id=b7214f2f0adb8dcc widzę, że otrzymałaś błąd 401 - Unauthorized. Oznacza to, że użytkownik nie jest uwierzytelniony - zaloguj się w Allegro, a następnie spróbuj jeszcze raz wywołać żądanie.

**Comment by kasia202014** [comment]
zalogowalam sie i wywolalam jeszcze raz zadanie pobrania tresci - wynik ponizej:

{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}
{'www-authenticate': 'Bearer realm="oauth2-resource", error="unauthorized", error_description="Full authentication is required to access this resource"', 'trace-id': 'dcedd1102ca6e4ba', 'content-type': 'application/json; charset=utf-8', 'content-length': '102', 'date': 'Tue, 05 Sep 2023 07:22:47 GMT'}

**Comment by kasia202014** [comment]
Przyznam szczeze, ze nie zaleznie od ustawien aplikacji - client czy device, token zwraca te same uprawnienia:

{
  "scope": [
    "allegro:api:orders:read",
    "allegro:api:fulfillment:read",
    "allegro:api:profile:write",
    "allegro:api:fulfillment:write",
    "allegro:api:sale:offers:write",
    "allegro:api:billing:read",
    "allegro:api:campaigns",
    "allegro:api:disputes",
    "allegro:api:bids",
    "allegro:api:sale:offers:read",
    "allegro:api:shipments:write",
    "allegro:api:orders:write",
    "allegro:api:ads",
    "allegro:api:payments:write",
    "allegro:api:sale:settings:write",
    "allegro:api:profile:read",
    "allegro:api:ratings",
    "allegro:api:sale:settings:read",
    "allegro:api:payments:read",
    "allegro:api:shipments:read",
    "allegro:api:messaging"
  ],
  "allegro_api": true,
  "iss": "https://allegro.pl",
  "exp": 1693936339,
  "jti": "12726b73-ad8b-4e8d-ad59-c422c8bcf34c",
  "client_id": "246ba41a1b6c403aa89a69cc71211b49"
}

**Comment by MaciejFrackowiak** [comment]
Niestety, ale cały czas korzystasz z autoryzacji typu "client_credentials", gdzie jak wspominałem nie ma kontekstu użytkownika, zatem danych z konta użytkownika nie pobierzesz.

**Comment by kasia202014** [comment]
prosze o sciezke do dokumnetacji, w ktorej opisujecie jak utworzyc konto device z odpowiednia sciezka do prawidlowej autoryzacji

**Comment by MaciejFrackowiak** [comment]
Cały proces opisany jest krok po kroku w [naszym poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow).
