### ISSUE TITLE
Integracja zewnętrznej aplikacji

### ISSUE THREAD

**Issue by MaciejFrackowiak** [allegro/allegro-api#7568]
Witam, 

chciałbym się zapytać jaka jest procedura weryfikacji aplikacji wspierającą komunikacje mailową do klientów allegro tak aby linki w treści maila do aplikacji nie były traktowane jako naruszenie regulaminu allegro ? 

Bardzo proszę o skierowanie mnie od odpowiedniego działu/osoby.

Dziękuje.

**Comment by MaciejFrackowiak** [comment]
@LukeOtdr My nie weryfikujemy aplikacji - aplikacja i jej działanie powinno być w zgodzie z [Regulaminem REST AP](https://developer.allegro.pl/rules)I oraz [Regulaminem Allegro](https://allegro.pl/regulamin).

**Comment by LukeOtdr** [comment]
Więc z kim mógłbym rozmawiać w tym temacie ? 
Chciałbym aby linki były akceptowane w treści maila podobnie jak w przypadku Baselinkera. Można mnie pokierować gdzieś ?

**Comment by MaciejFrackowiak** [comment]
Na forum GitHub wspieramy w zakresie wykorzystania zasobów API Allegro, nie weryfikujemy natomiast aplikacji. Być może [obsługa Allegro](https://allegro.pl/pomoc/kontakt) będzie mogła Tobie pomóc.
