### ISSUE TITLE
Allegro zamyka oferty

### ISSUE THREAD

**Issue by PiotrSzymala** [allegro/allegro-api#7570]
Dzień dobry, 

Otrzymaliśmy od Allegro takie maile: 
Twoja oferta zakończyła się: 13011478870 - Szyba do kominka samoczyszcząca na wymiar SCHOTT.
Twoja oferta zakończyła się: 13558760004 - SZYBA DO KOMINKA żaroodporna na wymiar GRATISY.

Mają państwo możliwośc sprawdzenia czy oferty zostały zamknięte przez Allegro, czy może jednak przez nasze oprogramowanie?
Skrupulatnie przeszukaliśmy logi z naszej aplikacji, ale niestety nie udało się nic na ten temat znaleź.

**Comment by AureliuszBrussy** [comment]
Zadaj proszę pytanie za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b&kategoria=4b0096d8-57bf-4af7-9a40-81c273a69423) logując się na konto, którego pytanie dotyczy. W ten sposób uzyskasz odpowiedź.
