### ISSUE TITLE
Allegro problemy przy metodzie dostawy "Allegro Przesyłka polecona"

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#7571]
Witam, mam problem przy tworzeniu przesyłki poprzez api dla wskazanej w tytule metody dostawy. Otrzymuję błąd:

{"id":"d0210078-a348-4ba0-b1b7-e833f77cd49c","parcelId":null,"status":"ERROR","errors":[{"code":"VALIDATION_ERROR","message":"Pickup point is incorrect","details":null,"path":"pickup.pointId","userMessage":"Punkt punktu nadania przesyłki jest niepoprawny"}]}

Natomiast na zamówieniu dla którego próbuję utworzyć przesyłke pole pickupPoint jest puste. Prosił bym o wskazanie skąd mogę w takim przypadku pozyskać ten pickupPointId

trace-id: a78cef29165bf1fe

**Comment by MaciejFrackowiak** [comment]
Odpowiednie identyfikatory punktów (pickup.pointId) pobierzesz z API przewoźnika, w tym przypadku Poczty Polskiej (https://www.poczta-polska.pl/webservices/).

**Comment by Maciej-Wilkosz** [comment]
Czy allegro nie przetrzymuje informacji jaki pickup point został wybrany przez klienta?

**Comment by MaciejFrackowiak** [comment]
Nie, ponieważ przesyłkę nadajesz Ty jako sprzedawca, zatem kupujący co najwyżej wybiera punkt receiver.
