### ISSUE TITLE
Proszę o nadanie mi uprawnień sprzedaży, mam konto firmowe jednak nie mogę wystawiac ofert 

### ISSUE THREAD

**Issue by Gradziu31** [allegro/allegro-api#7572]
Tak jak w temacie, mam nieaktywną sprzedaż na moim koncie sandbox - konto założone na dane:
nick: sklepsprzedaje
mail: k.gradek31@gmail.com

bardzo prosze o ściągnięcie wszelkich blokad z tego konta i danie mi uprawnień wystawiania ofert jako firma, dziękuję

**Comment by MaciejFrackowiak** [comment]
Konto jest już zweryfikowane.

**Comment by MaciejFrackowiak** [comment]
@m-kmiec Konto zweryfikowane.

**Comment by m-kmiec** [comment]
Dzięki serdeczne :)

**Comment by mayesto** [comment]
Cześć! Poprosiłbym również o zdjęcie blokady sprzedaży na środowisku testowym, login: maylab

**Comment by MaciejFrackowiak** [comment]
@mayesto Blokada usunięta.

**Comment by mayesto** [comment]
Dziękuję!
