### ISSUE TITLE
Zmiana ilości poprzez PATCH /sale/product-offers/{offerId} a PUT /sale/offer-quantity-change-commands/{commandId} 

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#7573]
Co jest bardziej zalecane do zmiany ilości? 

Zmiana poprzez `PATCH /sale/product-offers/{offerId}` czy zmiana poprzez `PUT /sale/offer-quantity-change-commands/{commandId}`

W kodzie raczej interesuje mnie pojedyńcza zmiana niż batch, czy w tym wypadku użycie batch będzie miało jakieś korzyści, czy lepiej użyć PATCH i przesłać jedno pole? Czy w przypadku zmian samej ilości lub ceny poprzez PATCH api zawsze zwróci 200 czy może też zwrócić 202?

https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pol-oferty
https://developer.allegro.pl/documentation/#operation/quantityModificationCommandUsingPUT

**Comment by MaciejFrackowiak** [comment]
Zasób [PUT /sale/offer-quantity-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/quantityModificationCommandUsingPUT) jest zasobem asynchronicznym, gdzie dodatkowo musisz generować kolejne commandId dla poszczególnych ofert. W przypadku [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) request od razu skupia się na danym atrybucie oferty - w przypadku pojedynczych zmian wydaje się, że korzystanie z PATCH jest efektywniejsze. W przypadku takich zmian PATCH zwróci od status 200.

**Comment by bugproof** [comment]
@MaciejFrackowiak super dziękuje za odpowiedź
