### ISSUE TITLE
Dostęp do /offers/listing

### ISSUE THREAD

**Issue by DamWeg** [allegro/allegro-api#7576]
Dzień dobry,
Kontaktowałem się z Państwem przez formularz w kwestii otrzymania dostępów do offers/listing przez api. 
Prowadzę sklep i myślę, że już czas na wykorzystanie tej opcji w celu dostarczenia klientom najlepszej oferty. 
Aplikację, firmę mam zweryfikowaną ale po długim czasie oczekiwania otrzymałem odmowę bez podania przyczyny.

Proszę o informacje dotyczące kryteriów jakie należy spełnić aby otrzymać dostęp do tej części API. Chodzi o kryteria już zweryfikowanej aplikacji, konta, które działa i generuje obroty od kilku miesięcy mając status super sprzedawcy i 100% pozytywnych opinii od kupujących.

Jeśli natomiast doszło do jakiegoś nieporozumienia proszę o przyznanie dostępu do tego fragmentu.

Pozdrawiam
Damian

**Comment by MaciejFrackowiak** [comment]
Z naszej strony nie weryfikujemy aplikacji, ani nie przyznajemy dostępu - są to decyzje podejmowane całkowicie poza nami. W tym miejscu mogę Cię tylko zachęcić do ponownego kontaktu, aby uzyskać dodatkowe informacje dot. Twojej weryfikacji.

**Comment by DamWeg** [comment]
A są gdzieś jasno określone kryteria jakie należy spełniać aby taki dostęp otrzymać? W mojej opinii jest to trochę niesprawiedliwe, że korzystając narzędzi do sprawdzania cen i chyba też baselinkera mam możliwość sprawdzania aktualnych cen produktu a gdy chcę to wykonać przez api już nie mam takiej możliwości. Pytanie czy ewentualnie istnieje inny sposób aby to wykonać z wykorzystaniem waszego Api?

**Comment by DamWeg** [comment]
Potrzebuje uzyskać taki dostęp dla aplikacji najlepsza_karma_2 na koncie najlepsza_karma

**Comment by MaciejFrackowiak** [comment]
Jak wspomniałem - proces weryfikacji odbywa się poza nami, zatem nie mamy sposobności pomóc. Proszę skontaktuj się z obsługą Allegro, ponieważ to tam odbywa się weryfikacja - tam również poznasz kryteria.

**Comment by DamWeg** [comment]
ok już wysłałem do nich kolejną prośbę o odpowiedź. Widziałem, że w innym wątku sprawdziliście weryfikację aplikacji dlatego myślałem, że jesteście w stanie coś pomóc w tej sprawie

**Comment by MaciejFrackowiak** [comment]
Tylko widzimy status tj. czy aplikacja jest zweryfikowana czy nie - bez już żadnych szczegółów co do samego przebiegu weryfikacji.

**Comment by DamWeg** [comment]
Dla osób które są zainteresowane korzystaniem z czesci API do pobierania ofert informuje ze otrzymałem taka informacje od Allegro.
„zasoby dostępu do części API, gdzie można sprawdzić oferty posortowane np. według ceny po konkretnym gtin produktu - są ogólnie zablokowane dla wszystkich.” 
Myśle ze taka informacja powinna znaleźć się w dokumentacji API aby nie tracić czasu na kontakt w celu przyznania dostępu.

**Comment by MaciejFrackowiak** [comment]
Jeśli spojrzysz w [opis](https://developer.allegro.pl/documentation/#operation/getListing) zasobu to znajdziesz tam informacje, które są przez niego zwracane. Podobne informacje są w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk).
