### ISSUE TITLE
403 GET /parcel-management/delivery-services

### ISSUE THREAD

**Issue by EmilooD** [allegro/allegro-api#7577]
Witam,

przy wysyłam z allegro przy próbie pobrania listy dostawców po autentykacji tokenem dostaję błąd 403 traceid:"524eb22bed80e060".
apka jest zarejestrowana na produkcji, ma scope do shipemntu, środowisko jest ustawione z wytycznymi.

Uprzejmie proszę o jakieś wskazówki.

**Comment by MaciejFrackowiak** [comment]
Podany trace-id prowadzi do wywołania innego zasobu. Błąd 403 w tym przypadku wynika z rodzaju autoryzacji - skorzystałeś z client_credentials, a dostęp umożliwia tylko autoryzacja code lub device flow.

**Comment by EmilooD** [comment]
Dzięki. Faktycznie robiłem testy na order.events, dla parcel to trace-id:"6e9114db733f6887".
Chcę zrobić konektor dla użytkownika, który automatycznie będzie robił wysyłki za użytkownika przycisk - etykietka.
Z którego sposobu autoryzacji powinienem skorzystać?

**Comment by MaciejFrackowiak** [comment]
[Zasoby do obsługi Wysyłam z Allegro](https://developer.allegro.pl/documentation/#tag/Parcel-management) wymagają "bearer-token-for-user", czyli musisz skorzystać z [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow.

**Comment by EmilooD** [comment]
Zmyliła mnie infromacja:

> Status HTTP 200 - odpowiedź prawidłowa. W odpowiedzi otrzymasz m.in. token dostępowy, który pozwoli ci korzystać z zasobów REST API. Kolejna próba użycia tego samego device code skończy się odpowiedzią o statusie 400. Device_code może tylko raz zwrócić token.

Co zrozumiałem, że każdy token muszę odebrać w interakcji z użytkownikiem.

**Comment by MaciejFrackowiak** [comment]
Przy statusie 200 możesz już korzystać z tokena do wywoływania zasobów.

**Comment by EmilooD** [comment]
Dla device

> Status HTTP 200 - odpowiedź prawidłowa. W odpowiedzi otrzymasz m.in. token dostępowy, który pozwoli ci korzystać z zasobów REST API. Kolejna próba użycia tego samego device code skończy się odpowiedzią o statusie 400. Device_code może tylko raz zwrócić token.

Czy to oznacza że przed każdym nowym tokenem muszę pobrać nowy device code bo inaczej dostanę błąd 400?
