### ISSUE TITLE
form dla payment_id

### ISSUE THREAD

**Issue by demural** [allegro/allegro-api#7579]
Posiadamy aplikacje która pobiera dane dotyczące zamówienia na podstawie ID płatności.
Aktualnie aplikacja zawraca błąd. 

"Allegro zwróciło więcej niż jeden form dla payment_id o numerze xxxxx"

Dotychaczas mógł być tylko jeden formularz zamowienia do danej płatności.
Co się zmieniło w tej metodzie ? Który formularz płatności powinien być pobierany ?

**Comment by MaciejFrackowiak** [comment]
W zasobach nie były dokonywane żadne zmiany. Przekaż nam więcej szczegółów, np. trace-id, wówczas będę mógł sprawdzić zakres zwracanych danych.

**Comment by demural** [comment]
chodzi przykładowo o płatność ID  03c67c19-4af0-11ee-90c7-a1bf59ab700a
Nie możemy pobrać danych zamówienia

**Comment by MaciejFrackowiak** [comment]
Z mojego punktu widzenia do wskazanej płatności przypisane jest odpowiednie zamówienie. Sugeruję kontakt z autorem aplikacji, aby wyjaśnić problem, który pojawił się podczas korzystania z niej.
