### ISSUE TITLE
Nieaktywne konto od dwoch tygodni

### ISSUE THREAD

**Issue by DawidMartenczuk** [allegro/allegro-api#758]
Dzien dobry,
Okolo dwoch tygodni temu utworzylem konto testowe w sandboxie, i do tego czasu nie zostalo jeszcze ono aktywowane. Czy mozna je aktywowac jakos recznie?

Login: dHJ1Zmxh

**Comment by PawelTaberski** [comment]
Twoje konto powinno już być w pełni aktywne.

**Comment by DawidMartenczuk** [comment]
Dziala 👍
