### ISSUE TITLE
MultipleProductsFoundException in Books

### ISSUE THREAD

**Issue by Marek-ShopStore** [allegro/allegro-api#7580]
Hello,

we have problem with listing in category books.

Quite often we get response from API: MultipleProductsFoundException

When we search for product using https://developer.allegro.pl/documentation#operation/getSaleProducts
We get reply and there is same product just listed multiple times. They differ in number of parameters set but they are same products.
When we fill our parameters it
1) will still not list product and return MultipleProductsFoundException
2) say our parameters differ from listed product

See for yourself product with EAN/ISBN 9788075551429

It's quite large amount of products (thousands)

What shall we do?

Thanks

**Comment by MaciejFrackowiak** [comment]
Yes, it is possible that our product base has a few items with the same GTIN/EAN/ISBN code.
For example, with the provided ISBN=9788075551429 there are three products - and you as a seller should choose the most suitable for you.
