### ISSUE TITLE
Where to get delivery date?

### ISSUE THREAD

**Issue by Marek-ShopStore** [allegro/allegro-api#7582]
At mall.cz we were able to get expected delivery date for order that was computed based on delivery delay / handling time of products that customer ordered and delivery method user selected. We were also able to get this date from API for each order.

Where do we find this information on allegro and is there option to get it by API?

**Comment by MartaNowaczyk** [comment]
Information about the delivery time can be found in the API Allegro for orders, in the `"delivery.time"` object - `"from"` and `"to"` fields:

- [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET),
- [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET).

**Comment by Marek-ShopStore** [comment]
It is exactly what we needed.
When are those times set? At order creation or at payment time?

**Comment by MartaNowaczyk** [comment]
Time is calculated when the transaction is finalized = e.g. payment completed or payment on delivery (READY_FOR_PROCESSING status).
