### ISSUE TITLE
Program Allegro Ceny - informacje o zakwalifikowaniu ofert

### ISSUE THREAD

**Issue by mstrojecki** [allegro/allegro-api#7583]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam, 

mam problem z programem Allegro Ceny oraz pobieraniu informacji o zakwalifikowaniu ofert do tego programu przez API.
Przykład to oferta nr 14016743657.

I tak:
1) przez API wywołanie endpointu sale/badges?offer.id=14016743657 zwraca pusty wynik

2) w panelu Allegro w zakłądce Mój Asortyment filtrowanie ja na zdjeciu ponizej zwraca pusty wynik
 

![Zrzut ekranu z 2023-09-05 11-22-50](https://github.com/allegro/allegro-api/assets/89082887/bd2573a0-fae8-45d9-b012-f5ad41c4ca0c)

3) w zamówieniu, w którym został kupiony dany produkt z oferty widać, że wyszczegolnione jest wyrownanie w programie Allegro Ceny

 
![Zrzut ekranu z 2023-09-05 11-22-03](https://github.com/allegro/allegro-api/assets/89082887/9107e94f-9f94-4fed-9ebe-7cdfa8d4106f)

Ostatecznie nie wiadomo, czy dana oferta jest w programie czy nie jest. Proszę o wyjaśnienie

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Weryfikuję to z zespołem odpowiedzialnym za ten endpoint. Wrócę z informacją.

**Comment by MartaNowaczyk** [comment]
Oferta 14016743657 nie była dodana do programu Allegro Ceny, brała udział we wrześniowych Allegro Days. Na ten moment nie mamy oddzielnej informacji i nazwy, dlatego w zamówieniu widzisz taką informację. Mamy w planach rozdzielenie tego, aby w przyszłości nie było takich niejasności.
