### ISSUE TITLE
Allegro Przesyłka Mini

### ISSUE THREAD

**Issue by CF-WR617AC** [allegro/allegro-api#7586]
Próbuję poprzez API utworzyć przesyłkę
Allegro Przesyłka Mini.

Niestety otrzymuję komunikat:

```
Pobieranie stanu wykonania zlecenia utworzenia przesyłki z Allegro dla paczki "XXXX" na koncie "XXXXXXXX: Nie znaleziono serwisu po nazwie

Kod błędu: 0 

[DELIVERY_SERVICE_NOT_FOUND_EXCEPTION]: Nie znaleziono serwisu po nazwie
```

Czy ta usługa jest już aktywna? Miała ruszyć dzisiaj, mamy przesyłki, a nadawanie nam nie działa ...

**Comment by MaciejFrackowiak** [comment]
Tak, usługa jest już aktywna. Proszę, podejmij próbę nadania ponownie.

**Comment by CF-WR617AC** [comment]
Teraz coś się zmieniło, otrzymuję komunikat:

`Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.

Kod błędu: 0 

[ERROR]: Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.`

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id wywołania lub wykorzystane commandId.

**Comment by CF-WR617AC** [comment]
nie wiem o czym mowa, korzystam z SELLO

**Comment by MaciejFrackowiak** [comment]
W takim wypadku skontaktuj się proszę bezpośrednio z obsługą Sello.

**Comment by CF-WR617AC** [comment]
SELLO mówi, że to jest problem w API Allegro.

**Comment by CF-WR617AC** [comment]
![image](https://github.com/allegro/allegro-api/assets/84842730/56b90987-357e-4110-853f-183ce56be9e5)

**Comment by CF-WR617AC** [comment]
![image](https://github.com/allegro/allegro-api/assets/84842730/00eb8ae9-3dd9-4ce9-b39a-30dfc620c06e)

**Comment by CF-WR617AC** [comment]
`Pobieranie stanu wykonania zlecenia utworzenia przesyłki z Allegro dla paczki "XXXXX" na koncie "XXXXX" (XXXXX)

 Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.`


Z kim mam się skontaktować ?
Co to znaczy "z nami"? Czyli z kim ?

**Comment by MaciejFrackowiak** [comment]
Korzystasz z oprogramowania zewnętrznego, zatem tylko integrator posiada niezbędne logi, na podstawie których możemy cokolwiek sprawdzić. Zrzuty ekranu z aplikacji nic nam nie powiedzą. Podsumowując, w tym przypadku integrator powinien się z nami skontaktować byśmy mogli zweryfikować konkretną sytuację na podstawie przykładowych danych.

**Comment by CF-WR617AC** [comment]
Podaję trace-id:

`{
retry-after: 5
x-xss-protection: 1; mode=block
pragma: no-cache
strict-transport-security: max-age=31536000 ; includeSubDomains
trace-id: bde70a74e9cbf0d9
x-frame-options: DENY
x-content-type-options: nosniff
Cache-Control: no-store, must-revalidate, no-cache, max-age=0
Date: Tue, 05 Sep 2023 12:30:10 GMT
Location: /parcel-management/parcel-create-commands/64aae0c6-737f-457a-a2dd-7a704f47ad7b

Content-Length: 1146
Content-Type: application/vnd.allegro.public.v1+json
Expires: 0
}`


Proszę o sprawdzenie, czy nie ma tu danych osobowych i ew. usunięcie. Dziękuję.

**Comment by MaciejFrackowiak** [comment]
Problem tkwi w numerze telefonu dostawcy - "Numer telefonu komórkowego nadawcy jest nieprawidłowy". Proszę popraw format numeru telefonu. My oczywiście poprawimy też treść komunikatu błędu.

**Comment by CF-WR617AC** [comment]
Dzięukuję za wsparcie. Faktycznie ruszyło. Dodam, że w następnej przesyłce mam z kolei problem z numerem
odbioryc i też komunikat bardzo dziwny. Ale po usunięciu telefonu odbiorcy ruszyło. Proszę o poprawę tego komunikatu także.

**Comment by mmodrzejewski** [comment]
Dzień dobry,

Mam podobny problem - przesyłka dodana przez API, w ramach usługi: 
**Allegro Mini Przesyłka** (0d021121-97e5-4729-9af6-a05779c6b835)
zwrotka o statusie identyczna jak u autora wątku:
**Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.** (Processing error)
...nie wiadomo o co chodzi, w czym tkwi błąd, zero szczegółów.
traceId zlecenia:
537d72df-4081-4bcd-a244-4af01009499a

Format requesta nie budzi podejrzeń (np. wymiary paczki, waga - są w dopuszczalnych widełkach).

Jedynie wspomniany numer telefonu mi przychodzi na myśl.... my wysyłamy go w naszej integracji (dedykowanej jako pozycja Wysyłam z Allegro -> z wydzielonymi usługami przypisanymi do carrierId: POCZTA_POLSKA) w formacie 9 cyfrowym (bez znaków dodatkowych, żadnych spacji, itd), a w zamówieniu Allegro widnieje jako +48 XXX XXX XXX. 
Czy to jest źródłem problemu?
Warto by było z Waszej strony uzupełnić response, z nakierowaniem, co robimy źle. **Wtedy takich zgłoszeń byłoby mniej**..

**Comment by CF-WR617AC** [comment]
Z moich doświadczeń:
- telefon nadawcy nie może być pusty i nie może być stacjonarny
- telefon odbiorcy możę być pusty ale nie może być stacjonarny

Dalej z moich doświadczeń Allegro wypuszcza poprawki do API w piąki dwa razy w miesiącu, więc w ten piątek może poprawią treść komunikatów, a może pod koniec miesiąca. Zobaczymy.

**Comment by MaciejFrackowiak** [comment]
@mmodrzejewski Weryfikuję Twój przypadek z zespołem, wrócę z odpowiedzią.

**Comment by mmodrzejewski** [comment]
@MaciejFrackowiak czy udało się zweryfikować problem?

**Comment by Lukasz-Zurek** [comment]
@mmodrzejewski Póki co sprawa nadal jest weryfikowana. Jak tylko uzyskam konkretną informację - wrócę z nią w tym wątku.

**Comment by Lukasz-Zurek** [comment]
@CF-WR617AC Poproszę Cię o wskazanie przykładowych paczek. Wystarczy commandId.

**Comment by CF-WR617AC** [comment]
> @CF-WR617AC Poproszę Cię o wskazanie przykładowych paczek. Wystarczy commandId.

RESPONSE 200 (OK) ----------------------------------------------------------------- 14:30:13:221 (47ms)
{
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: 275ddc0c781408de
x-content-type-options: nosniff
strict-transport-security: max-age=31536000 ; includeSubDomains
Cache-Control: no-store, must-revalidate, no-cache, max-age=0
Date: Tue, 05 Sep 2023 12:30:15 GMT

Content-Length: 260
Content-Type: application/vnd.allegro.public.v1+json
Expires: 0
}
{"id":"64aae0c6-737f-457a-a2dd-7a704f47ad7b","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Processing error","details":null,"path":null,"userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}]}



Problem dotyczy absolutnie wszystkich MINI Przesyłek. I tylko MINI Przesyłek, Polecone E-commerce i Kurier24 mają wagę OK.
Ważenie i ręczne wpisywanie wag do kilkudziesięciu przesyłek przez Panią na Poczcie, to jakaś porażka !

**Comment by CF-WR617AC** [comment]
To znaczy, te wagi brakują w software Poczty Polskiej. Tak, jakby API Allegro, albo API Poczty Polskiej nie miało żadnej wagi to poszczególnych przesyłek. Ja podejrzałem jak to wygląda, to są w software Poczty Polskiej w polu WAGA same zera zawsze dla MINI Przesyłki. Prośba o ustalenie z API Poczty Polskiej metody przesyłania wagi, bo Sklepiki czekają jakiś masakryczny czas przy okienku w PP.

**Comment by Lukasz-Zurek** [comment]
W miejscu "wagi" paczki przesłałeś:

```
"weight":{
"value":"0.05",
"unit":"KILOGRAM"
},
```
Konsultuję temat z odpowiednim zespołem. U większości przewoźników ta waga powinna być przyjęta/przetwarzana. Wkrótce wrócę do Ciebie z informacją.

**Comment by Lukasz-Zurek** [comment]
Jeśli chodzi o wskazany przez Ciebie problem w "64aae0c6-737f-457a-a2dd-7a704f47ad7b" - `Numer telefonu komórkowego nadawcy jest nieprawidłowy.` Błąd nie dotyczy zatem stricte wagi.

Natomiast jeżeli chodzi o wagę - j.w. zezwalamy na przekazanie wartości wyższej od zera, np. `"0.05"`, czyli taką, jaką przesłałeś w powyższym requeście. Nie odnotowaliśmy problemów z przekazywaniem danych dotyczących tego pola.

Myślę, że najlepiej będzie jeśli wyjaśnisz ten problem bezpośrednio z Pocztą Polską.
