### ISSUE TITLE
Błędne saldo dla allegro-cz

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#7588]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [x ] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**

Chcę pobrać aktualne saldo w koronach. Na froncie widzę to tak:
![image](https://github.com/allegro/allegro-api/assets/36523118/e4f45905-d318-4ba7-af9a-def050542544)

Tym samym po wykonaniu GET billing/billing-entries?marketplaceId=allegro-cz&limit=1 powinienem otrzymać ostatnią operację czyli wypłatę środków oraz saldo = 0. Natomiast otrzymuję operację wpłaty na 454kc z saldem 17304kc.

Tak jakby do wypłaty środków w koronach nie był przypisany serwis allegro-cz

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, że miałeś na myśli zasób /payments/payment-operations, a nie /billing/billing-entries. Nie zwracamy tej operacji, ponieważ wypłata środków odbywa się w ramach konta Allegro, a nie konkretnego serwisu. Opisaliśmy to w [naszym poradniku](https://developer.allegro.pl/tutorials/wystawianie-i-zarzadzanie-oferta-w-serwisach-zagranicznych-wwzjP4M8gTZ#jak-sprawdzic-oplaty):
<img width="605" alt="Zrzut ekranu 2023-09-6 o 07 48 51" src="https://github.com/allegro/allegro-api/assets/51473661/5e957831-6351-424a-88a2-7db100aa9640">

Tak jest w przypadku tej operacji, w polu `marketplaceId` zwracamy `null`.

**Comment by dlis2010** [comment]
Zgadza się chodziło mi o zasób /payments/payment-operations.

Moim celem było pobranie aktualnego salda w koronach, udało mi się to uzyskać za pomocą:

GET /payments/payment-operations?wallet.paymentOperator=PAYU&currency=CZK&limit=1

Zamykam ;)
