### ISSUE TITLE
delivery.shippingRates Error

### ISSUE THREAD

**Issue by kochanA** [allegro/allegro-api#7589]
Dzień dobry,
staram się wystawić ofertę na koncie sprzedażowym przez API zapytaniem "POST" sale/product-offers. Jakiej wartości bym nie wstawiła jako "delivery.shippingRates" dostaję błąd. Przesyłam trace id zapytania : 'trace-id': '15afcc141219e046'. Proszę o weryfikacje zapytania.

**Comment by MartaNowaczyk** [comment]
Dzień dobry, w podanym przypadku wpisujesz nieprawidłową wartość dla "delivery.shippingRates", a dokładnie "1.25kg". Powinno się tam znaleźć pole "id" z identyfikatorem cennika dostawy. Możliwe identyfikatory cenników pobierzesz metodą [GET /sale/shipping-rates](https://developer.allegro.pl/documentation#operation/getListOfShippingRatestUsingGET).

**Comment by kochanA** [comment]
Dziękuje :) w takim razie mam sugestię do dokumentacji nie ma w niej informacji o dodaniu wartości "id" lub "name"

<img width="373" alt="image" src="https://github.com/allegro/allegro-api/assets/99121757/a19379d1-9e55-4014-83b8-781455c26b08">

**Comment by MartaNowaczyk** [comment]
W [dokumentacji](https://developer.allegro.pl/documentation#operation/createProductOffers) masz rozpisane wszystko, korzystaj z "REQUEST BODY SCHEMA". 
<img width="876" alt="Zrzut ekranu 2023-09-6 o 11 34 43" src="https://github.com/allegro/allegro-api/assets/38425363/079d4983-fddf-436a-9adc-ee5d6e31e58b">
To co podesłałaś to przykład. Jeśli nie podasz cennika jest możliwość, że uzupełnimy go automatycznie. Jeżeli posiadasz jeden cennik dostawy, to przypiszemy go do oferty. W przypadku większej liczby, użyjemy cennika o nazwie default (musisz taki mieć dodany). W innym przypadku wskazujesz konkretny cennik.

**Comment by kochanA** [comment]
ooo super dziękuję w takim razie za informacje :)
