### ISSUE TITLE
Mimo podania wymaganych parametrów edycja oferty jest odrzucona

### ISSUE THREAD

**Issue by medikoo** [allegro/allegro-api#7590]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

_Problem już raz zgłaszany https://github.com/allegro/allegro-api/issues/6539 (brak odpowiedniej dokumentacji jakie pola są wymagane)_

Próbuję zaktualizować ofertę w kategorii `89066`, dla której `GET https://api.allegro.pl/sale/categories/89066/parameters` zwraca następujące wymagane pola 

_Tytuł, EAN, Nośnik:_
<details>

```javascript
[
  {
    id: '237218',
    name: 'Tytuł',
    type: 'string',
    required: true,
    requiredForProduct: true,
    requiredIf: null,
    displayedIf: null,
    unit: null,
    options: {
      variantsAllowed: false,
      variantsEqual: false,
      ambiguousValueId: null,
      dependsOnParameterId: null,
      requiredDependsOnValueIds: null,
      displayDependsOnValueIds: null,
      describesProduct: true,
      customValuesEnabled: false
    },
    restrictions: { minLength: 1, maxLength: 100, allowedNumberOfValues: 1 }
  },
  {
    id: '225693',
    name: 'EAN (GTIN)',
    type: 'string',
    required: true,
    requiredForProduct: true,
    requiredIf: {
      parametersWithValue: [ { id: '11323', oneOfValueIds: [ '11323_1' ] } ],
      parametersWithoutValue: []
    },
    displayedIf: null,
    unit: null,
    options: {
      variantsAllowed: false,
      variantsEqual: false,
      ambiguousValueId: null,
      dependsOnParameterId: '11323',
      requiredDependsOnValueIds: [ '11323_1' ],
      displayDependsOnValueIds: null,
      describesProduct: true,
      customValuesEnabled: false
    },
    restrictions: { minLength: 8, maxLength: 14, allowedNumberOfValues: 1 }
  },
  {
    id: '246845',
    name: 'Nośnik',
    type: 'dictionary',
    required: true,
    requiredForProduct: true,
    requiredIf: null,
    displayedIf: null,
    unit: null,
    options: {
      variantsAllowed: false,
      variantsEqual: false,
      ambiguousValueId: null,
      dependsOnParameterId: null,
      requiredDependsOnValueIds: null,
      displayDependsOnValueIds: null,
      describesProduct: true,
      customValuesEnabled: false
    },
    dictionary: [
      {
        id: '246845_622161',
        value: 'płyta Blu-ray 3D',
        dependsOnValueIds: []
      },
      {
        id: '246845_622165',
        value: 'płyta DVD',
        dependsOnValueIds: []
      },
      {
        id: '246845_622169',
        value: 'płyta Blu-ray',
        dependsOnValueIds: []
      },
      {
        id: '246845_728783',
        value: 'płyta Blu-ray 4K',
        dependsOnValueIds: []
      },
      {
        id: '246845_622173',
        value: 'płyta VCD',
        dependsOnValueIds: []
      },
      {
        id: '246845_622177',
        value: 'kaseta wideo',
        dependsOnValueIds: []
      },
      {
        id: '246845_738593',
        value: 'płyta DVD+Książka',
        dependsOnValueIds: []
      },
      {
        id: '246845_1743943',
        value: 'płyta Blu-ray audio',
        dependsOnValueIds: []
      }
    ],
    restrictions: { multipleChoices: false }
  }
]
```
</details>

Niemniej następujące żądanie, które zawiera wszystkie te informacje:

<details>

```javascript
{ productSet:
   [ { product:
        { parameters:
           [ { id: '249815', valuesIds: [ '249815_1743423', [length]: 1 ] },
             { id: '225693', values: [ '8436027576563', [length]: 1 ] },
             { id: '246845', valuesIds: [ '246845_622169', [length]: 1 ] },
             { id: '237218', values: [ 'Los abrazos rotos / Broken Embraces / Przerwane objęcia (2009)', [length]: 1 ] },
             { id: '124', valuesIds: [ '124_1', [length]: 1 ] },
             [length]: 5 ],
          id: '8436027576563',
          idType: 'GTIN' } },
     [length]: 1 ],
  name: 'Przerwane objęcia (2009) {bd} (Opis!) +PL',
  category: { id: '89066' },
  description:
   { sections:
      [ { items:
           [ { type: 'TEXT',
               content:
                "<h1>Przerwane objęcia / Los abrazos rotos / Broken Embraces (2009)</h1>\n<h2>[Blu-ray]</h2>\n<p><b>UWAGA:</b> Płyta z wydania hiszpańskiego okładka z wydania amerykańskiego</p>\n<p><b>Stan:</b> Bardzo dobry (jak na załączonych zdjęciach)</p>\n<p><b>Polska wersja</b>: Brak na oryginalnej płycie. Na dodatkowej płycie BD-R dołączę mux tego samego blu-ray'a (1:1) z polskim lektorem i napisami</p>\n\n<p>-----------------------------------------------------------------------------------------</p>\n<h2>Dźwięk</h2>\n<ul>\n  <li>🇪🇸 (spa) - Dolby Digital - 5.1(side)</li>\n  <li>🇪🇸 (spa) - Dolby Digital - stereo</li>\n</ul>\n<h2>Napisy</h2>\n<ul>\n  <li>🇪🇸 (spa)</li>\n</ul>\n" },
             [length]: 1 ] },
        [length]: 1 ] },
  images:
   [ 'https://a.allegroimg.com/original/116be2/b80967fc4d8da674b12020add918',
     'https://a.allegroimg.com/original/114ee1/f32189c84deb86ac8d1de8ac1699',
     'https://a.allegroimg.com/original/1199dc/8a7a05464b40b7ae5fe415c6f8a7',
     'https://a.allegroimg.com/original/11c1ae/0a93ff5349cbaba2eef4d698eb4a',
     [length]: 4 ] }
```
</details>

Jest odrzucone z błędem:

```
Nie znaleziono produktu dla podanego identyfikatora.
Nie podano danych niezbędnych do utworzenia propozycji produktu i/lub utworzenia oferty
```

Trace ID: `1578dc4749130ce7`

**Comment by MaciejFrackowiak** [comment]
Skorzystałeś z [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers), który to zasób służy do edycji istniejącej oferty. Jeżeli chcesz utworzyć nową ofertę skorzystaj z [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) lub możesz dodać propozycję produktu korzystając z [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct). Zapoznaj się proszę z [naszym poradnikiem](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA), gdzie szczegółowo opisaliśmy proces wystawiania ofert połączonych z produktem.

**Comment by medikoo** [comment]
> Skorzystałeś z [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers), który to zasób służy do edycji istniejącej oferty.

@MaciejFrackowiak Taki jest cel, chcę edytować istniejącą ofertę

> Jeżeli chcesz utworzyć nową ofertę 

Nie chcę tworzyć nowej oferty. Edytuję istniejącą

**Comment by MaciejFrackowiak** [comment]
Jako id produktu musisz podać wartość istniejącą w naszej bazie - dla podanego przez Ciebie GTIN nie mamy żadnego produktu, dlatego chcąc dodać taki produkt do naszej bazy musisz najpierw zgłosić propozycję jego dodania poprzez [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct).

**Comment by medikoo** [comment]
@MaciejFrackowiak Mówimy o próbie edycji istniejacej oferty (https://allegro.pl/oferta/przerwane-objecia-2009-blu-ray-opis-pl-14019798758) , która ma załączony produkt, który jest w bazie (z GTIN: `8436027576563`).

Jeśli przejdę do edycji oferty na stronie, Allegro widzę załączony produkt z dokładnie tym GTIN:

<img width="1149" alt="Screenshot 2023-09-07 at 09 05 00" src="https://github.com/allegro/allegro-api/assets/122434/51f05e8f-7694-44f2-8d65-ebdf5f378a45">

**Comment by MaciejFrackowiak** [comment]
Wskazana oferta ma przypisany produkt o id=cc2b5ada-4c18-47fe-8272-1ec824ba0c9d. Jeżeli sprawdzisz stan bieżący bazy produktów to dla podanego EAN=8436027576563 nie znajdziesz żadnego produktu - został on usunięty, ponieważ był nieprawidłowy. To co widzisz w ofercie to pozostałość sprzed edycji produktu - dlatego w API otrzymujesz obecnie stan faktyczny tj. nie mamy takiego produktu w bazie.

**Comment by medikoo** [comment]
> nie znajdziesz żadnego produktu - został on usunięty, ponieważ był nieprawidłowy

Dlaczego w takim razie API Allegro na zapytanie o produkty dla tej oferty `https://api.allegro.pl/sale/product-offers/14019798758` zwraca ten produkt, dokładnie w formie jakiej jest pokazany na Allegro:

```javascript
{ product:
        { id: 'cc2b5ada-4c18-47fe-8272-1ec824ba0c9d',
          publication: { status: 'LISTED' },
          parameters:
           [ { id: '237218',
               name: 'Tytuł',
               values: [ 'Los abrazos rotos / Broken Embraces / Przerwane objęcia (2009)' ],
               valuesIds: null,
               rangeValue: null },
             { id: '124', name: 'Liczba płyt w wydaniu', values: [ 'jedna' ], valuesIds: [ '124_1' ], rangeValue: null },
             { id: '246845', name: 'Nośnik', values: [ 'płyta Blu-ray' ], valuesIds: [ '246845_622169' ], rangeValue: null },
             { id: '249814', name: 'Język napisów', values: [ 'polski' ], valuesIds: [ '249814_1743396' ], rangeValue: null },
             { id: '249815', name: 'Język lektora', values: [ 'polski' ], valuesIds: [ '249815_1743423' ], rangeValue: null },
             { id: '225693', name: 'EAN (GTIN)', values: [ '8436027576563' ], valuesIds: null, rangeValue: null } ] }
```

W jaki sposób mam wywnioskować z takiej odpowiedzi, że zwrócony produkt tak naprawdę nie istnieje w bazie i powinien być utworzony bym mógł edytować ofertę?

Dlaczego strona Allegro, nic nie mówi o tym, że produkt nie istnieje w bazie, tylko pokazuje rzekomo podpięty pod ofertę produkt, bez żadnego komunikatu, że to produkt "duch"? Niczym się to nie różni od sytuacji kiedy produkt w bazie istnieje

**Comment by medikoo** [comment]
Zwracam też uwagę, status `publication` dla zwróconego przez wasze API produktu jest `LISTED`.

**Comment by MaciejFrackowiak** [comment]
Skorzystaj z [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct) i pobierz aktualny stan produktu - nie znajdziesz tam EAN/GTIN. Gdy dokonujemy edycji w bazie produktów to nie edytujemy jednocześnie ofert - możesz to zrobić sam korzystając z opcji Pracuj z Katalogiem.

**Comment by medikoo** [comment]
@MaciejFrackowiak Rozwiązałem swój problem używając podczas edycji id produktu (który nie ma prawa ulec zmianie) zamiast EAN, który może zostać zmieniony lub usunięty w rekordzie produktu.

Dzięki za pomoc
