### ISSUE TITLE
Allegro sandbox - płatność nigdy nie zostaje potwierdzona

### ISSUE THREAD

**Issue by CH-gmatkowski** [allegro/allegro-api#7591]
Występuje problem: potwierdzenie płatności
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Po kupnie przedmiotu w przypadku płatności (przelew, karta, blik etc.) zostajemy przekierowani na stronę do wyboru statusu płatności, wybieramy "pozytywnie" po czym nigdy nie dochodzi do potwierdzenia płatności czego wynikiem są wiszące i nieopłacone zakupy.
![image](https://github.com/allegro/allegro-api/assets/129270187/2160c0c9-74f4-4263-ab82-532969c8e474)

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, weryfikujemy tę sytuację.

**Comment by gkopec** [comment]
Testowałem chyba wszystkie dostępne metody płatności na sandboxie i żadna nie kończy się opłatą za zamówenie.

**Comment by mayesto** [comment]
Potwierdzam błąd, u mnie również nie działa

**Comment by PrzemyslawLukanowski** [comment]
Problem występuje po stronie operatora płatności, poinformuję w wątku, gdy uda się go rozwiązać.

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować, przepraszamy za niedogodności.
