### ISSUE TITLE
Problem z aktywnoscia oferty

### ISSUE THREAD

**Issue by jacekZur** [allegro/allegro-api#7592]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
![Zrzut ekranu 2023-09-7 o 09 28 31](https://github.com/allegro/allegro-api/assets/137051004/12969b6e-1b11-42e4-9fe5-e0012419b98f)
![Zrzut ekranu 2023-09-7 o 09 28 20](https://github.com/allegro/allegro-api/assets/137051004/679402f9-769c-49ce-baa8-a566dbcdf526)

Oferta na lisie ofert jest aktywna, a po jej wyswietleniu pojawia sie ze jest zakonczona.

**Comment by MartaNowaczyk** [comment]
Z tego co widzę, oferta znów jest aktywna. Jeśli widzisz niezgodności w działaniu serwisu na stronie www napisz przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt), bo w takim przypadku problemem nie jest publiczne API.
