### ISSUE TITLE
Sandbox - Cannot get through the payment simulator

### ISSUE THREAD

**Issue by DHSC1** [allegro/allegro-api#7593]
sandbox acccount: zajdalen

Hi,
we're using the sandbox acccount: zajdalen for test orders. This account has been functional in the past. However, it is currently not possible to create offers. Apparently your payment simulator has been used in the past. I am now unable to go through it. 

When I try to create a offer, the portal reports:
An error has occurred - You do not have the permissions required to list an offer (sales suspended). Pay the arrears in Settlements with Allegro;

Settlements with Allegro reports:
Sales suspension
The ability to sell from your account is currently suspended. This may be due to unpaid bills or other violations of the Terms & Conditions. To lift the sales suspension, pay the outstanding amounts or contact us.

Current balance is: 
-7,16 PLN

I need to create a test offer and test order. How to proceed?

Thank you in advance for your reply.

**Comment by MartaNowaczyk** [comment]
I have removed the block from the specified account. To settle your payment, use our payment simulator, which you will access from the "[Settlements with Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro)" tab.
