### ISSUE TITLE
Oznaczenie kategorii z podwyższonymi opłatami

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#7595]
Czy możecie w tym swoim świetnym api dodać informację, że w danej kategorii pobieracie zwiększoną prowizję, np. Pozostałe?

**Comment by jezewskiBNetrox** [comment]
A to ci nie starczy? https://developer.allegro.pl/tutorials/jak-sprawdzic-oplaty-nn9DOL5PASX#kalkulator-oplat

**Comment by TimothyKoval** [comment]
Nie, bo nie mam porównania z innymi kategoriami

**Comment by MaciejFrackowiak** [comment]
@TimothyKoval Nie, nie przewidujemy dodania takich oznaczeń.
