### ISSUE TITLE
How to set the reference number for listed products

### ISSUE THREAD

**Issue by VEVOR** [allegro/allegro-api#7598]
POST /sale/product-offers
![image](https://github.com/allegro/allegro-api/assets/99702013/b8531af5-e9d2-43ba-ae27-8c42a88d20ab)

**Comment by MartaNowaczyk** [comment]
"Sygnatura" is the "external.id" field in [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers).
