### ISSUE TITLE
Błąd w kategorii 124264, Odcień ma być wyświetlany dla wartości Koloru ale żadna wartość nie pasuje do danego koloru

### ISSUE THREAD

**Issue by jezewskiBNetrox** [allegro/allegro-api#7599]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam, mam taki problem że w kategorii 124264 (Sukienki) dla parametru Odcień, kolor "czarny" ma pozwalać na wyświetlanie odcieni. Jednocześnie żaden z dostępnych odcieni nie pasuje do koloru "czarny". Czy to błąd? Jak to interpretować?

**Comment by MartaNowaczyk** [comment]
Zweryfikowałam to jeszcze z zespołem odpowiedzialnym za tę funkcjonalność i nie jest to błąd, po prostu może się pojawić kolor i nie mieć odcieni, wynika to z wewnętrznych ustaleń przy projektowaniu tego rozwiązania.

**Comment by jezewskiBNetrox** [comment]
@MartaNowaczyk Dziękuję za odpowiedź.
