### ISSUE TITLE
Nie przekazuje się informacją o chęci zamówienia podjazdu poprzez API

### ISSUE THREAD

**Issue by Rychu1998** [allegro/allegro-api#7600]
Podczas zlecanie przesyłki, z zaznaczoną opcją "zamów kuriera" z API zwracane są propozycję podjazdów. Następnie przekazuje w requescie datę oraz godzinę podjazdu, po czym w odpowiedzi nie otrzymuje żadnego błędu. Jednak kiedy wejdę na zamówienie w allegro nie mam informacji, że kurier został zamówiony (screeny w załącznikach). Co może być przyczyną?

![image (13)](https://github.com/allegro/allegro-api/assets/144427855/0a21e70b-2abf-4086-b408-bdc9d697ca06)
![image (12)](https://github.com/allegro/allegro-api/assets/144427855/1a5db3ae-6ee1-4976-ac9a-1a36da1f2150)
![image (11)](https://github.com/allegro/allegro-api/assets/144427855/5f8f0a32-7d04-4daf-9e87-3259d9ad1a67)
![image (10)](https://github.com/allegro/allegro-api/assets/144427855/c254e947-e775-4311-9687-310969e96278)

**Comment by MartaNowaczyk** [comment]
Sprawdziłam i nie widzę błędu w API podczas zamawiania podjazdu. Nie ma też zrzutu z zamówień o którym piszesz, więc  podeślij proszę.

**Comment by Rychu1998** [comment]
przesyłam xml, request, response oraz screen z allegro gdze jest informacja, że podjazd nie został zamówiony. Proszę o pomoc w rozwiązaniu problemu. 
[response_allegro.txt](https://github.com/allegro/allegro-api/files/12657053/response_allegro.txt)
[request_allegro.txt](https://github.com/allegro/allegro-api/files/12657054/request_allegro.txt)
![allegro_screen](https://github.com/allegro/allegro-api/assets/144427855/b27a0fe9-be61-4d9d-8d3a-6c333033bfbc)
[xml_allegro.txt](https://github.com/allegro/allegro-api/files/12657055/xml_allegro.txt)

**Comment by MartaNowaczyk** [comment]
Przesłałeś request dla tworzenia paczki. Podeślij proszę trace-id dla zamówienia podjazdu dla tej przesyłki PUT /parcel-management/parcel-pickup-request-commands/{commandId}, bo nie mogę odnaleźć takiego zlecenia.
