### ISSUE TITLE
Mini przesyłka

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#7601]
Dzień dobry

mamy problem z zamowieniem przesylki Mini przesyłki, nasz klient ma ustawiony podjazd zeby kurier odbieral paczki lecz przy probie zamowienia przesylki dostajemy blad
Punkt punktu nadania przesyłki jest niepoprawny
 Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.
mimo ze nie przekazujemy punktu nadania. Czy trzeba jakies pole wyslac osobne lub ustawic coś gdzies w allegro?

trace-id 3bf7812a35dda8c4

**Comment by MartaNowaczyk** [comment]
Z naszych logów wynika, że nie przekazujesz wartości w polu pickup.pointId - jest tam null. Dla przesyłek Poczty Polskiej nie da się zamówić podjazdu, dlatego trzeba wskazać odpowiedni punkt nadania.

**Comment by KaMisza** [comment]
Czy w takim razie skoro według umowy kurier podjeżdża po przesyłkę to mamy wprowadzić w pickup poincie najbliższy punkt nadania przesyłki a paczki i tak przekazywać do kuriera po podjeździe?

**Comment by MartaNowaczyk** [comment]
W umowie z Pocztą Polską powinieneś mieć wpisany Urząd pocztowy, który możesz podać pickup.pointId.
