### ISSUE TITLE
Allegro - znikające oferty z parametrem TOP

### ISSUE THREAD

**Issue by PiotrSzymala** [allegro/allegro-api#7602]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X] inny / other

:beetle: **Opis / Description**

Dzień dobry,

Otrzymaliśmy od Allegro takie maile:
Twoja oferta zakończyła się: 13011478870 - Szyba do kominka samoczyszcząca na wymiar SCHOTT.
Twoja oferta zakończyła się: 13558760004 - SZYBA DO KOMINKA żaroodporna na wymiar GRATISY.

Mają państwo możliwośc sprawdzenia czy oferty zostały zamknięte przez Allegro, czy może jednak przez nasze oprogramowanie?
Skrupulatnie przeszukaliśmy logi z naszej aplikacji, ale niestety nie udało się nic na ten temat znaleź. Generalnie te oferty nie powinny być zamykane z naszej strony, ponieważ są to oferty top i posiadamy w kodzie zabezpieczenie przed ich kasowaniem. Niemniej jednak problem występuje i zastanawiamy się co może być przyczyną. Opisana sytuacja dotyczy konta kratki_pl.

**Comment by MaciejFrackowiak** [comment]
Proszę skontaktuj się z nami poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt), abyśmy mogli przekazać dane dot. wskazanych ofert.
