### ISSUE TITLE
Pobieranie statusu listu przewozowego kuriera PPL

### ISSUE THREAD

**Issue by ZakuroPL** [allegro/allegro-api#7603]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: 

Pobieram przez API list przewozowy zwrotu oraz id kuriera "PPL". Jest to czeski przewoźnik.

Niestety, ale nie mogę sprawdzać przez API statusu przesyłki. Czyli jestem w stanie pobrać list i zdobyć ID przewoźnika, ale nie mogę sprawdzić, czy zamówienie wyjechało. Komunikat błędu w response mówi, że tego przewoźnika nie obsługuje. Pytanie, czy planujecie to wdrożyć? Może został on przeoczony? Fajnie, gdybyście obsługiwali tego przewoźnika, biorąc pod uwagę, że odpaliliście allegro.cz :-)

Komunikat response:

{'errors': [{'code': 'INTEGRATOR_STATUSES_ILLEGAL_ARGUMENT', 'message': 'Carrier id PPL is not allowed. Allowed carrier ids: [4PX_EXPRESS, ALLEGRO, AMBRO_EXPRESS, AUSTRIAN_POST_EXPRESS, AUSTRIAN_POST_REGISTERED, CAINIAO, CHINA_EMS, CHINA_POST, CHUKOU1, CNE_EXPRESS, DB_SCHENKER, DHL, DPD, DSV, DTS, ESHIPPING_GLOBAL, EXELOT, FEDEX, FLYT_EXPRESS, GEBRUDER_WEISS, GEIS, GLS, INPOST, JAPAN_POST, KARGOM_KOLAY, KN, LA_POSTE, LITHUANIAN_POST, MEEST, NA_DZISIAJ, NO_LIMIT, ORLEN, PACKETA, PICKPACK, POCZTA_POLSKA, POSTNORD, PTS, RABEN, RHENUS_LOGISTICS, RUCH, SFC, SF_EXPRESS, SHIPTER, SKYNET, SUNYOU, SUUS, TNT_EXPRESS, UKR_POSHTA, UPS, WANB_EXPRESS, WEDO, X_PRESS_COURIERS, YANWEN, YUN_EXPRESS, ZIGZAG]', 'details': None, 'path': '/order/carriers/PPL/tracking', 'userMessage': 'Identyfikator kuriera: PPL jest niedozwolony. Dopuszczalne identyfikatory kurierów to: [4PX_EXPRESS, ALLEGRO, AMBRO_EXPRESS, AUSTRIAN_POST_EXPRESS, AUSTRIAN_POST_REGISTERED, CAINIAO, CHINA_EMS, CHINA_POST, CHUKOU1, CNE_EXPRESS, DB_SCHENKER, DHL, DPD, DSV, DTS, ESHIPPING_GLOBAL, EXELOT, FEDEX, FLYT_EXPRESS, GEBRUDER_WEISS, GEIS, GLS, INPOST, JAPAN_POST, KARGOM_KOLAY, KN, LA_POSTE, LITHUANIAN_POST, MEEST, NA_DZISIAJ, NO_LIMIT, ORLEN, PACKETA, PICKPACK, POCZTA_POLSKA, POSTNORD, PTS, RABEN, RHENUS_LOGISTICS, RUCH, SFC, SF_EXPRESS, SHIPTER, SKYNET, SUNYOU, SUUS, TNT_EXPRESS, UKR_POSHTA, UPS, WANB_EXPRESS, WEDO, X_PRESS_COURIERS, YANWEN, YUN_EXPRESS, ZIGZAG]'}]}

**Comment by MaciejFrackowiak** [comment]
Proszę podaj przykładowe id przesyłki wygenerowanej przez WzA dla podanego przewoźnika.

**Comment by ZakuroPL** [comment]
Podaje dane:
ID zwrotu: 5500facd-fde0-44bf-a58e-34fd5ef38e9a
ID kuriera: PPL
numer listu przewozowego: 20951478330

Nie mam ID przesyłki. Korzystam z zapytania api "/order/carriers/{id_carrier}/tracking"
i przesyłam parametr "waybill" jako numer listu.

**Comment by MaciejFrackowiak** [comment]
[Zasób](https://developer.allegro.pl/documentation/#operation/getParcelTrackingUsingGET) pozwala na sprawdzenie trackingu przesyłek nadanych poprzez Wysyłam z Allegro. W Twoim przypadku mamy do czynienia z przesyłką nadaną poza WzA.

**Comment by ZakuroPL** [comment]
OK. To wszystko jasne. Dziękuję bardzo za szybkie wsparcie.
