### ISSUE TITLE
ProductDuplicate : "A product with such data already exists. Contact the author of the application" ( An Error occurred )

### ISSUE THREAD

**Issue by Wooconnector** [allegro/allegro-api#7605]
Deam Team,

Could you please help me with this error : "Produkt z takimi danymi już istnieje. Skontaktuj się z autorem aplikacji. ( A product with such data already exists. Contact the author of the application ) ", I looked into some of the created ticket on github didn't find my solution. 

My Payload of request is : 

{"name":"Beanie with Logo","category":{"id":"313513"},"description":{"sections":[{"items":[{"type":"TEXT","content":" Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. some more<\/p>"}]}]},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/11c3da\/d0bec09042f9991d24d16289c648"}],"parameters":[{"valuesIds":["248135_1728479"],"id":"248135"},{"values":["Kod producenta"],"id":"224017"}],"language":"pl-PL"}

Thanks looking forward to hear from you soon

**Comment by MartaNowaczyk** [comment]
In the response header you will find the "location" field, where we return the id of the product recognized as a duplicate. In the case of products, we check the parameters marked "describesProduct" - they are the ones that describe the product and allow us to determine whether the given data is not already available in our database as another product. You can find the parameters describing the product using [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).

**Comment by Wooconnector** [comment]
Hi @MartaNowaczyk , 
My location ID is showing like this https://api.allegro.pl/sale/products/266efc93-bdd4-4cfb-8075-48bb6e480847 with this product, 
Could you please let help more in this. 

Thanks

**Comment by Wooconnector** [comment]
Do I need to try to create product with that category parameter in which option.describesProduct is true?

**Comment by MartaNowaczyk** [comment]
If we have already found such a product based on your data, then, as I wrote, we return it in "location". Then you should use that product. You can also check [the product details](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-retrieve-product-data) - [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct). 

The parameters, which are described as options.describesProduct: true within the GET /sale/categories/{categoryID}/parameters, should be passed in the product section, i.e. productSet.product.parameters. However, if you indicate a specific product (for example, the one in the location header), then you do not need to provide this data, we will do it automatically for you. 

You can find more in our [guide](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6).

**Comment by Wooconnector** [comment]
Thanks for sharing!

**Comment by Wooconnector** [comment]
Here is the location of the product : https://api.allegro.pl/sale/products/266efc93-bdd4-4cfb-8075-48bb6e480847

**Comment by MartaNowaczyk** [comment]
We found this product by the parameters specified in the request. Is there any problem with this product? How can I help you?

**Comment by Wooconnector** [comment]
Thanks for your quick response, I'll let you know When I'm needed. 


Thanks
