### ISSUE TITLE
Propose changes in product - rejected

### ISSUE THREAD

**Issue by fabianCyfran** [allegro/allegro-api#7606]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Zasób: **/sale/products/{productId}/change-proposals**
TraceId: **302aeaa940e403fc**
RequestId: **5ad38006-c73a-4450-938b-2479192d4e1d**

Witam,
Próba wysłania propozycji zmiany nazwy produktu zakończyła się statusem **REJECTED**
Ustawiana nazwa to: **RELACJE MIĘDZY SYSTEMAMY WARTOŚCI A PRZEK**
Powód odrzucenia: **The suggested change violates Allegro standards. Learn more.**

Jaki jest dokładny powód odrzucenia tej propozycji?
Jaki są standardy dotyczące nazwy produktu?

**Comment by MartaNowaczyk** [comment]
Proces weryfikacji produktów odbywa się całkowicie poza API. Aby otrzymać szczegóły odrzucenia skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt).
