### ISSUE TITLE
Batch offer unpublish

### ISSUE THREAD

**Issue by joe1d83** [allegro/allegro-api#7608]
Czy w przypadku zakończenia licytacji używając tego zasobu /sale/offer-publication-commands/{commandId}
wszystkie oferty zostaną odwołane ? A jeśli nie to jak można odwołać wszystkie oferty przed zakończeniem licytacji ?

**Comment by jezewskiBNetrox** [comment]
1. Nie.
2. Oferty można odwoływać tylko w niektórych kategoriach i nie da się tego zrobić za pomocą API.

**Comment by joe1d83** [comment]
Dziękuję za informacje
