### ISSUE TITLE
Błąd autoryzacji na środowisku testowym

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#7609]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=7695cfa9ff354980b58fd184aa039906&redirect_uri=https%3A%2F%2Fwww.dobrerowery.pl%2Fadmin%2FAllegroRestApi%2FgetToken&code_challenge=0DUFHB2SL1XY6ZIPEN345G8JMA9VRK&code_challenge_method=plain&scope=allegro%3Aapi%3Aprofile%3Aread+allegro%3Aapi%3Aprofile%3Awrite+allegro%3Aapi%3Asale%3Aoffers%3Aread+allegro%3Aapi%3Asale%3Aoffers%3Awrite+allegro%3Aapi%3Aorders%3Aread+allegro%3Aapi%3Aorders%3Awrite+allegro%3Aapi%3Aratings+allegro%3Aapi%3Adisputes+allegro%3Aapi%3Abids+allegro%3Aapi%3Abilling%3Aread+allegro%3Aapi%3Apayments%3Aread+allegro%3Aapi%3Apayments%3Awrite+allegro%3Aapi%3Asale%3Asettings%3Aread+allegro%3Aapi%3Asale%3Asettings%3Awrite+allegro%3Aapi%3Acampaigns

przechodząc pod ten adres wyrzuca mi bład. Teoretycznie wszystko na moje oko wygląda ok w linku. Gdzie może być problem?

Nie możemy wyświetlić strony
Numer błędu: 1011ad60241da2e3

**Comment by DamianKAtomStore** [comment]
76388

**Comment by Lukasz-Zurek** [comment]
Pod wskazanym numerem błędu (trace-id) widać, że użyłeś błędnego redirect_uri, a powinien być zgodny z tym podanym w [ustawieniach aplikacji](https://apps.developer.allegro.pl.allegrosandbox.pl).

**Comment by DamianKAtomStore** [comment]
Przecież po url_decode powyższego linku parametr redirect_uri ma postać
"https://www.dobrerowery.pl/admin/AllegroRestApi/getToken"
Dokładnie taki sam jaki mam ustawiony w "ADRESY PRZEKIEROWAŃ"

**Comment by DamianKAtomStore** [comment]
https://imgur.com/y7AI3kW
