### ISSUE TITLE
/sale/disputes

### ISSUE THREAD

**Issue by slawomirponiewaz** [allegro/allegro-api#761]
Witam, 
sprawdźcie działanie metody GET na zasobie /sale/disputes, gdyż w mojej opinii zwraca ona więcej rekordów niż powinna.

**Comment by PawelTaberski** [comment]
Co masz na myśli, że zwraca więcej niż powinna? Co zwróciła Twoim zdaniem nad wymiarowo.

**Comment by slawomirponiewaz** [comment]
Ilość dyskusji jakie widzę w https://allegro.pl/dyskusje/sprzedajacy bez zaznaczania opcji "pokaz tylko" jest dużo mniejsza od ilości dyskusji jakie mogę pobrać wspomnianym zasobem.

Dodatkowo, gdy pobieram wiadomości dla tych nadmiarowych dyskusji metodą GET na zasobie /sale/disputes/{disputeId}/messages to dostaję informację, że nie mam uprawnień.

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a z requestem od wspomnianych zasobów i zaznacz, które dane są Twoim zdaniem nad wymiarowe, w zgłoszeniu zaznacz proszę, że informacje przesyłasz na potrzeby zgłoszenia na GitHub-ie numer 761.. Sprawdzimy w czym jest problem

**Comment by slawomirponiewaz** [comment]
pod wskazanym linkiem nie pojawia się formularz

**Comment by PawelTaberski** [comment]
Link działa prawidłowo może spróbuj wyczyścić pliki cookie, dla pewności podsyłam jeszcze raz [tutaj](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) i link do strony na której przekierowujemy na formularz [tutaj](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/mam-problem-z-api-allegro-qzdAgORR5cz).

**Comment by PawelTaberski** [comment]
Zweryfikowaliśmy i problem nie powinien już występować.

**Comment by slawomirponiewaz** [comment]
Jest ok.
