### ISSUE TITLE
Brakujące informacje w response sample dotyczące pobrania danych oferty

### ISSUE THREAD

**Issue by Morph21** [allegro/allegro-api#7610]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [x] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Opis:

Brakuje informacji odnośnie pól content oraz url w "response sample" odnośnie endpointu /sale/product-offers/{offerId}

Przez co podczas generowania klas reprezentujących obiekt json-a otrzymujemy nie pełny model danych. Prosiłbym o poprawę tego w dokumentacji oraz jeżeli możliwe sprawdzenie czy ten problem nie występuje również w innych miejscach w dokumentacji

<img width="1240" alt="image" src="https://github.com/allegro/allegro-api/assets/38075691/089c2355-d4b9-481a-8bc5-c00994fc0e4e">

**Comment by Lukasz-Zurek** [comment]
Dziękuję za zgłoszenie. Potwierdzam. Zweryfikujemy wszystkie tego typu przypadki.
