### ISSUE TITLE
Problem z czasem dostawy przy wznawianiu ofert

### ISSUE THREAD

**Issue by jacekZur** [allegro/allegro-api#7611]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Podczas wznawiania oferty wysylany jest jeden z mozliwych terminow dostawy "handling_time" w tym przypadku P5D. Otrzymujemy zwrotke o niepoprawnym czasie wysylki (widoczne na screen).
Mamy juz kilka ofert, ktore podczas wznawiania maja ten sam blad.
Co moze byc powodem bledu?
![Zrzut ekranu 2023-09-12 o 10 01 25](https://github.com/allegro/allegro-api/assets/137051004/b9d10be1-3f84-4fc2-9f0a-843f97d7d2cc)
![Zrzut ekranu 2023-09-12 o 10 01 14](https://github.com/allegro/allegro-api/assets/137051004/db756a1e-eb89-4bbd-9168-97f7fe0f6a4e)

**Comment by Lukasz-Zurek** [comment]
@jacekZur Prześlij proszę trace-id, a sprawdzę dokładnie ten przypadek.

**Comment by jacekZur** [comment]
Podpowiesz jak je pobrac.

**Comment by Lukasz-Zurek** [comment]
Trace-id znajdziesz w nagłówku naszego response'a z błędem.

**Comment by jacekZur** [comment]
@Lukasz-Zurek  Nie widze takiego wpisu na zrzucie. Jakas podpowiedz :)
![Zrzut ekranu 2023-09-12 o 11 49 38](https://github.com/allegro/allegro-api/assets/137051004/3802be8d-208d-4b8f-9141-820505860b39)

**Comment by Lukasz-Zurek** [comment]
Nie wiem z jakiego oprogramowania korzystasz i czy zapisuje ono trace-id. W tej sytuacji wskaż proszę numer oferty oraz datę próby wznowienia, kiedy wystąpił błąd - namierzę ją.

**Comment by Lukasz-Zurek** [comment]
@jacekZur Ze względów bezpieczeństwa, usunąłem zrzut (z widocznym tam tokenem) z Twojej wiadomości.

**Comment by jacekZur** [comment]
@Lukasz-Zurek 
oferta: 9929821277
wznawiana przed chwila

**Comment by Lukasz-Zurek** [comment]
@jacekZur W żądaniu przekazujesz wartość "P6D", a dostępne, akceptowalne wartości to: PT0S (natychmiast), PT24H (24 godziny), P2D (2 dni), P3D (3 dni), P4D (4 dni), P5D (5 dni), P7D (7 dni), P10D (10 dni), P14D (14 dni), P21D (21 dni), P30D (30 dni), P60D (60 dni). Można również podać te wartości w godzinach, np. PT72H (3 dni).

**Comment by jacekZur** [comment]
@Lukasz-Zurek przekazuje P5D, jak w zalaczniku. I dostaje ten sam komunikat.
wlasnie probowalem jeszcze raz wznowic aukcje.
![Zrzut ekranu 2023-09-12 o 12 36 03](https://github.com/allegro/allegro-api/assets/137051004/2cff3d6b-94f5-45ac-ab29-22530b64c5d6)

**Comment by jacekZur** [comment]
@Lukasz-Zurek  testy 14:27
wyslalem 3 wznowienia z czasem P5D
13419757828 - zwrotka problem z czasem
12082605859 - produkt sie wystawil
9929821277 - zwrotka problem z czasem

Moze teraz bedziesz mogl sprawdzic dlaczego nie dziala wystawianie.

**Comment by Lukasz-Zurek** [comment]
@jacekZur 

13419757828 - `„handlingTime":"P6D"`, stąd błąd,
12082605859 - `„handlingTime":"PT120H"` - tutaj przeszło, ponieważ przekazałeś równowartość „P5D”,
9929821277 - `„handlingTime":"P6D"`, stąd błąd.

**Comment by jacekZur** [comment]
@Lukasz-Zurek 
dzieki za pomoc, jednak po naszej stornie byl problem :)

**Comment by Lukasz-Zurek** [comment]
@jacekZur Najważniejsze, że problem zlokalizowany :)
