### ISSUE TITLE
How can I use the API to set the same price lists for my Czech offers as the ones already in place for my Polish offers on the Polish Allegro?

### ISSUE THREAD

**Issue by EugenBodanov** [allegro/allegro-api#7612]
Good day, how can I use the API to set the same price lists for my Czech offers as the ones already in place for my Polish offers on the Polish Allegro?

**Comment by PrzemyslawLukanowski** [comment]
Hello, you can define one delivery price list that will be included in a single offer, and this delivery price list will applied to allegro.pl and allegro.cz. Delivery methods that will be available on allegro.pl or allegro.cz depend on the value returned in the `marketplaces` field in the response to [GET /sale/delivery-methods](https://developer.allegro.pl/documentation#operation/getListOfDeliveryMethodsUsingGET). 
<img width="718" alt="Zrzut ekranu 2023-09-12 o 13 21 26" src="https://github.com/allegro/allegro-api/assets/51473661/a8d4303d-6409-4757-96e8-7f13d57df414">

You can read more about delivery settings and shipping rates in [our tutorial.](https://developer.allegro.pl/tutorials/account-and-user-data-management-jn9vBjqjnsw)

**Comment by EugenBodanov** [comment]
thanks, it helped.
