### ISSUE TITLE
Wysyłam z Allegro - błąd pól pickup.pointId i label.sender.pointId

### ISSUE THREAD

**Issue by btc-jz** [allegro/allegro-api#7613]
Mam następujący problem, dziś przy próbach utworzenia przesyłki do Allegro Paczkomat (PUT do /parcel-management/parcel-create-commands/) zacząłem otrzymywać komunikat o błędach walidacji:

VALIDATION_ERROR :: pickup.pointId musi pasować do wyrażenia [A-Za-z0-9-_]+. 
VALIDATION_ERROR :: label.sender.pointId musi pasować do wyrażenia [A-Za-z0-9-_]+.

W dokumentacji (https://developer.allegro.pl/documentation/#operation/createNewParcel) pole pickup.pointId nie jest obowiązkowe, pole label.sender.pointId w ogóle nie jest wymienione. Czy dokumentacja jest nieaktualna?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać trace-id lub commandId, dla których otrzymałeś wymienione błędy?

**Comment by btc-jz** [comment]
Przepraszam, źle opisałem problem, błąd dostaję w odpowiedzi na GET /parcel-management/parcel-create-commands/ wywołanym po utworzeniu przesyłki, przykładowe CommandId to e7241034-e7e9-458d-9ef7-8385d4ca6caf

**Comment by CF-WR617AC** [comment]
Potwierdzam, u nas też pojawił się od godziny ten błąd, nie ma póki co rozwiązania

**Comment by CF-WR617AC** [comment]
Rano chodziło OK, teraz pluje błędem:
`musi pasować do wyrażenia [A-Za-z0-9-_]+
ścieżka: receiver.pointId
detale: Invalid value: `

**Comment by CF-WR617AC** [comment]
Poprzez Allegro na te same dane naklejki wychodzą po WzA. Problem jest z usługą "INPOST minikurier24"

**Comment by SoDaUser** [comment]
Prośba o pomoc, dziś normalnie paczki wychodziły obecnie jest błąd jak wyżej opisany:



https://api.allegro.pl/parcel-management/parcel-create-commands/a9d34571-3bff-4aee-aef4-69b483f1f5a8

zwraca błąd:

{"id":"a9d34571-3bff-4aee-aef4-69b483f1f5a8","parcelId":null,"status":"ERROR","errors":[{"code":"VALIDATION_ERROR","message":"musi pasować do wyrażenia [A-Za-z0-9-_]+","details":"Invalid value: ","path":"pickup.pointId","userMessage":"musi pasować do wyrażenia [A-Za-z0-9-_]+"},{"code":"VALIDATION_ERROR","message":"musi pasować do wyrażenia [A-Za-z0-9-_]+","details":"Invalid value: ","path":"label.sender.pointId","userMessage":"musi pasować do wyrażenia [A-Za-z0-9-_]+"}]}

**Comment by PrzemyslawLukanowski** [comment]
Komunikat błędu jest związany z wprowadzeniem nowej walidacji - nie przyjmujemy już pustego stringa "", przekazujcie zamiast tego proszę wartość null. Przepraszam za te niedogodności. 

Co do pola `label.sender.pointId`, które nie występuje w requeście oraz w dokumentacji - weryfikuję jeszcze ten temat.

**Comment by btc-jz** [comment]
Nie wiem czy ktoś coś już zmienił w temacie pola label.sender.pointId, ale po podaniu null w pickup.pointId paczka się utworzyła.

**Comment by SoDaUser** [comment]
U mnie też poszło na testowej przesyłce po ustawieniu pickup.pointId  null.

Korzystamy z aplikacji, ta zmiana to wprowadzenie poprawki, instalki, i aktualizacji.
Mamy szczyt sezonu :/

**Comment by SoDaUser** [comment]
@btc-jz  ta sama walidacja wprowadzona jest w receiver.pointId w przypadku gdy jest kurier.

W temacie walidacji warto poprawić aby:
w polu ulicy nie wpisywać informacji, że płot jest kamienny, budynek zielony i wejście od tyłu
w polu ulicynie wpisywać miejscowości i kodu pocztowego
aby nie robic tego podwójnie

Wydaje mi się, że często powinno być uzyte pole uwagi 

telefon też często ma postać  +XXX XXX XXX,  0XXX XXX XXX , XXX-XXX-XXX

**Comment by q3ok** [comment]
Allegro Kurier DPD -błąd z receiver.pointID, przekazanie wartosci pustej, null, 0, 1 nie działą i ciągle zwraca błąd VALIDATION ERROR, jako "punkt odbiorcy jest niepoprawny". Co mam przekazac w pointID?
uuid przykładowy: 39bdb8d2-6f7e-49cf-a79c-272a176c2e9d

**Comment by Onixarts** [comment]
> Komunikat błędu jest związany z wprowadzeniem nowej walidacji - nie przyjmujemy już pustego stringa "", przekazujcie zamiast tego proszę wartość null. Przepraszam za te niedogodności.

Ale czy to nie są łamiące zmiany? Nie da się od tak u wszystkich użytkowników zmienić sposób walidacji. Prośba o przywrócenie poprzedniego działania bo klienci nie mogą generować etykiet. A w przyszłości takie zmiany powinny być ogłaszane wcześniej, bo one są równie istotne co zmiany w API.

**Comment by Zbigniew-L** [comment]
> > Komunikat błędu jest związany z wprowadzeniem nowej walidacji - nie przyjmujemy już pustego stringa "", przekazujcie zamiast tego proszę wartość null. Przepraszam za te niedogodności.
> 
> Ale czy to nie są łamiące zmiany? Nie da się od tak u wszystkich użytkowników zmienić sposób walidacji. Prośba o przywrócenie poprzedniego działania bo klienci nie mogą generować etykiet. A w przyszłości takie zmiany powinny być ogłaszane wcześniej, bo one są równie istotne co zmiany w API.

Popieram kolegę  powyżej, dodatkowo chciałbym zauważyć że w dokumentacji createNewparcel NIE MA nawet pola pointid w label.sender... po prostu zrobiliście niespodziankę dla wielu osób, czy dodacie to pole do dokumentacji czy inne rozwiązanie? na razie prosimy o przywrócenie systemu aby działał jak wcześniej... jest na to szansa?
![label sender](https://github.com/allegro/allegro-api/assets/41995305/1ad7a1ef-a02b-4003-87b7-28f3d9aa42c5)

**Comment by SoDaUser** [comment]
Robiłem szybka poprawkę dla box,  drugą dla kuriera, 
tu czytam, że z dpd też będa problemy. 

W okresie zakupów szkolnych każda minuta jest dla nas na wagę złota. 
Może uda się, przywrócić poprzednią walidację, aby ewentualne niespodzianki można bezpiecznie/spokojnie wdrożyć ?

**Comment by PrzemyslawLukanowski** [comment]
Do godziny 12:00 wprowadzimy poprawkę, która będzie zmieniać "" na null, jeszcze raz przepraszam za niedogodności. 

@q3ok, @Zbigniew-L - wrócę jeszcze z odpowiedzią co do Waszych pytań.

**Comment by PrzemyslawLukanowski** [comment]
@q3ok W Twoim przypadku problemem jest to, że wartość null przekazujesz "opakowaną" w cudzysłów, przez co traktujemy ją jako wartość stringową.

**Comment by q3ok** [comment]
> @q3ok W Twoim przypadku problemem jest to, że wartość null przekazujesz "opakowaną" w cudzysłów, przez co traktujemy ją jako wartość stringową.

tak, nie jestem w stanie zrobić innej zmiany na szybko. liczę, że zmiana "" na null będzie działać poprawnie, bo to jest do wdrożenia na szybko.
dlaczego nie można robić tak jak było dotychczas, czyli przy przesyłkach kurierskich pomijać te pole?

**Comment by PrzemyslawLukanowski** [comment]
Poprawka jest już na produkcji, problem nie powinien występować.

@Zbigniew-L W tym przypadku, komunikat o `label.sender.pointId ` wprowadza w błąd, ponieważ w rzeczywistości dotyczy on także pola `pickup.pointId`. Ze względu na nasze wewnętrzne zależności na tę chwile nie możemy go niestety usunąć.

@q3ok Dotychczas akceptowaliśmy pusty string "", właśnie wdrożyliśmy poprawkę, która nadal to umożliwia, a dalej - po naszej stronie - zamieniamy go na null, dzięki czemu nie powinniśmy odpowiadać komunikatem błędu.

**Comment by Onixarts** [comment]
Dzięki, mamy potwierdzenie od użytkowników, że jest już OK.
