### ISSUE TITLE
Thread messages

### ISSUE THREAD

**Issue by jakub-marchewka** [allegro/allegro-api#7614]
Dzień dobry,
Czy na endpointy
https://developer.allegro.pl/documentation/#operation/listMessagesGET lub
https://developer.allegro.pl/documentation/#operation/newMessagePOST
są nałożone limity zapytań jak to ma miejsce w przypadku produktyzacji ?

**Comment by Lukasz-Zurek** [comment]
Nie, na wskazanych endpointach nie ma tego typu limitów.

**Comment by jakub-marchewka** [comment]
Dziękuję za odpowiedź.
