### ISSUE TITLE
How to get orders by specific email address?

### ISSUE THREAD

**Issue by Degee** [allegro/allegro-api#7616]
Hi, is there a possibility to get a list of all orders by specific email address from API?

I found just a GET query to endpoint https://api.{environment}/order/checkout-forms filtered by `buyer.login`
Is there any solution to get orders filtered by `buyer.email` or some usefull workaround?

Thank you

**Comment by PrzemyslawLukanowski** [comment]
Unfortunately, it is not possible.- when it comes to buyer's data you can filter orders only by the login.

**Comment by Degee** [comment]
Thank you
