### ISSUE TITLE
parameters id 

### ISSUE THREAD

**Issue by kochanA** [allegro/allegro-api#7618]
Dzień dobry,
tworzę u siebie bazę parametrów do produktów i zauważyłam, że te same parametry mają różne id np "Rodzaj" to między innymi : 220457, 6872, 237786 
Czy parametry są jakoś dodatkowo powiązane z kategoriami ?

**Comment by Lukasz-Zurek** [comment]
Tak:

220457 - Sport i turystyka > Siłownia i fitness > Trening fitness > Obciążniki do ćwiczeń
6872 - Dom i Ogród > Ogród > Baseny i akcesoria > Baseny
237786 - Dom i Ogród > Ogród > Meble ogrodowe > Fotele wiszące

**Comment by kochanA** [comment]
dziękuję za odpowiedz, nie ma innego wyjścia jak tylko uwzględnić kategorie w parametrach
