### ISSUE TITLE
Tworzenie przesyłek dla Punkt DHL POP 

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#7619]
Cześć, mam problem z tworzeniem przesyłek dla POP DHL na środowisku sandbox.

Z jakichś powodów pojawiają mi się następujące błędy.
Czy moglibyście podać mi przyczynę? Czy robię jakiś niepoprawny request?

Przesyłki: 
c3a3ee5c-1fba-492b-8838-bd8721accfc3  - Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.
1e8ca1e7-1fc5-4856-bb22-da53d967ef50 - Punkt odbiorcy jest niepoprawny

Błędy o tyle mnie zastanawiają że tym samym mechanizmem udało mi się utworzyć przesyłkę dla innego zamówienia poprawnie.

**Comment by Lukasz-Zurek** [comment]
Jeżeli chodzi o `c3a3ee5c-1fba-492b-8838-bd8721accfc3 - Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.` - zgłaszam ten problem do odpowiedniego zespołu.

Natomiast w przypadku `1e8ca1e7-1fc5-4856-bb22-da53d967ef50 - Punkt odbiorcy jest niepoprawny` - mimo, że jest to punkt DHL i powinien działać - sprawę również wyjaśnię i wrócę z informacją.

**Comment by marmited** [comment]
ok, to czekam na odpowiedzi.

**Comment by Lukasz-Zurek** [comment]
Póki co wracam z odpowiedzią dot. niepoprawnego punktu. Walidacja operatora wykryła, że w promieniu 5km dla adresu Zarzecze 2 w Krakowie, brakuje wskazanego punktu. Dlatego zwróciliśmy błąd.

**Comment by Lukasz-Zurek** [comment]
@marmited Jeżeli chodzi o c3a3ee5c-1fba-492b-8838-bd8721accfc3 - prawdopodobnie występowały chwilowe problemy z dostępnością usługi DHL. Deweloperzy sprawdzili umowę i nie stwierdzili, żeby uległa ona zmianie. Dodatkowo w historii zamawiania przesyłek na przedmiotowej umowie widoczne są przesyłki zamówione z sukcesem. Przykładem takiej przesyłki jest 15095474. Proponuję spróbować ponownie złożyć zamówienie. Ewentualnie proszę skontaktować się z DHLem w celach wyjaśnień.

**Comment by marmited** [comment]
Dziękuję bardzo za pomoc!
