### ISSUE TITLE
Finished offers although stock>0

### ISSUE THREAD

**Issue by DHSC1** [allegro/allegro-api#7622]
Hello,
I administrate a seller with the login eoshop_market. All offers of the seller get to the status FINISHED (ukončená/zakończona) after some time. This happens even though we always keep the "while stocks last" (do vyprodání zásob / do wyczerpania przedmiotów) option selected for offers. However, the offers get finished even though they are not sold out. We have tried communicating with Allegro via your chat to find out why this is happening and possibly to find out any other offer limitations. However, after finding out that we sync the stock via API, your support referred us to the github forum.  Can you let us know why our offers are being discontinued despite not being sold out (and also having the "while stocks last" option selected for them)?

Offer example: https://allegro.cz/nabidka/berlingerhaus-doza-na-potraviny-sada-3-ks-13934742225

![offer in allegro seller admin](https://github.com/allegro/allegro-api/assets/144317759/e4574922-6fe9-4894-b8dd-16baaff136eb)

![do vyprodání zásob](https://github.com/allegro/allegro-api/assets/144317759/138c7e5b-7cdd-4e8d-b516-ca8b6f63a829)

Thank you.

Best regards

**Comment by Lukasz-Zurek** [comment]
I see that your account is suspended (blocked sale) so you should pay overdue commission fees. So this is why we terminated your offer, even though it had do vyprodání zásob / do wyczerpania przedmiotów option marked.
