### ISSUE TITLE
Create a new Parcel  Bad REQUEST 400

### ISSUE THREAD

**Issue by vojteka100** [allegro/allegro-api#7623]
Witam,
Proszę  pomoc. Mam problem z wykreowaniem nowej przesyłki; BAD REQUEST 400.

{"serviceID":"0d83955a-4297-4169-adef-9790d53b11ff","receiver":{"address":{"street":"Centralna 51","postCode":"31-586","city":"Kraków","countryCode":"PL"},"email":"btgaaf8otm+30a198290@allegromail.pl","name":"Arkadiusz Mal","company":null,"phone":"502494682","pointID":null},"pickup":{"address":{"street":"Polanki","postCode":"30-740","city":"Kraków","countryCode":"PL"},"email":"sklep@motochemia.pl","name":"Lal","company":"Motochemia.pl Arkadiusz Mal","phone":"999902277","pointID":"5cc643f9-7da6-11e7-a14e-246e963207c0"},"items":[{"dimensions":{"height":{"value":"30","unit":"CENTIMETER"},"width":{"value":"30","unit":"CENTIMETER"},"depth":{"value":"30","unit":"CENTIMETER"}},"weight":{"value":"10","unit":"KILOGRAM"},"description":"Art. Motoryzacyjne","value":{"amount":"111","currency":"PLN"},"type":"PACKAGE"}],"type":"PACKAGE","label":{"sender":null,"fileFormat":"PDF","referenceNumber":"12345"},"additionalServices":{"cashOnDelivery":null,"options":null}}

**Comment by Lukasz-Zurek** [comment]
Popraw "serviceI**D**" na "serviceId". Ten mały błąd generuje powyższy komunikat.

**Comment by vojteka100** [comment]
Dziękuję. To było to :)
Pozdrawiam.
