### ISSUE TITLE
Allegro International

### ISSUE THREAD

**Issue by CSVK2022** [allegro/allegro-api#7624]
Dzień dobry, pytanie czy allegro zwraca ID punktów odbioru/ automatów WE|DO ? 
Proszę o ewentualne wskazanie sposobu na ich pobranie.

**Comment by Lukasz-Zurek** [comment]
Lista punktów dostępna jest na [tej](https://www.wedo.cz/en/map) stronie. Niestety znajdujące się tam identyfikatory dodatkowo mapujemy po naszej stronie. W naszym API nie udostępniamy jednak zasobu, który zwróciłby docelowe identyfikatory tych punktów. Konsultuję ten temat jeszcze z odpowiednim zespołem. Wrócę do Ciebie z odpowiedzią.

**Comment by CSVK2022** [comment]
Ok, czekam na info w takim razie

**Comment by kulisz** [comment]
@Lukasz-Zurek Pierwsze pytanie czy w pickupPoint w nazwie zawsze zwracacie kod punktu?
`     :pickupPoint=>
      {:id=>"ALWD0021",
       :name=>"WEDO AlzaBox U Bažantnice ALZABOX2122",
       :description=>"AlzaBox je umístěn nalevo od vchodu do obchodu Coop.",
       :address=>{:street=>"U Bažantnice 770", :zipCode=>"53803", :city=>"Heřmanův městec", :countryCode=>"CZ"}}`

z mapą WE|DO się pokrywa
`{"code"=>"ALZABOX2122",
  "photo"=>"https://i.alza.cz/Foto/ImgGalery/boxes/AB756.jpg",
  "external_code"=>"BOX2122",
  "photo_small"=>"https://i.alza.cz/Foto/ImgGalery/boxes/AB756.jpg",
  "address"=>{"town"=>"Heřmanův Městec", "country"=>"CZ", "street"=>"U Bažantnice", "postal_code"=>"538 03", "number"=>"770"}`

--------

A drugie pytanie to taki przypadek - zwracacie na innym zamówieniu ( 45b66910-512b-11ee-b672-73ad58670202 )
`{:id=>"ALWD0172",
       :name=>"WEDO AlzaBox Ruská ALZABOX1917",
       :description=>"AlzaBox Holešov (Penny)",
       :address=>{:street=>"Ruská 309", :zipCode=>"41703", :city=>"Dubí", :countryCode=>"CZ"}},
     :cost=>{:amount=>"49.00", :currency=>"CZK"}`
i takiego punktu mapy WE|DO nie posiadają. W mieście Dubi jest tylko jeden punkt i mieści się przy innej ulicy

**Comment by Lukasz-Zurek** [comment]
@kulisz Upewniam się co do pierwszej kwestii, natomiast drugą sprawę analizuje już zespół odpowiedzialny za tę usługę. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@CSVK2022 W załączeniu znajdziesz listę punktów WEDO:

[249724_punkty_wedo.csv](https://github.com/allegro/allegro-api/files/12656170/249724_punkty_wedo.csv)

Jak wspomniałem wcześniej - w naszym API nie udostępniamy jednak zasobu, który zwróciłby identyfikatory tych punktów. Zachęcam Cię jednak do przekazania i opisania sugestii w naszym dedykowanym miejscu, tj. [Discussions](https://github.com/allegro/allegro-api/discussions).

**Comment by Lukasz-Zurek** [comment]
@kulisz Odpowiadając na pierwsze pytanie - pickupPoint zawsze zwracamy w nazwie punktu.

Wyjaśniam jeszcze kwestie dotyczące braku punktu ALZABOX1917.

**Comment by kulisz** [comment]
@Lukasz-Zurek Punkty do naszego systemy sobie już pobieramy ze strony WE|DO i przy zejściu zamówienia są odpowiednio parowane więc pozostaje kwestia brakujących punktów bo nawet gdybym korzystał tylko z Waszego pliku to wiesz że w tym pliku Waszym pliku tego punktu nie ma? 
Więc pozwoliliście klientowi wybrać podczas składania zamówienia punkt, którego Wy nie obsługujecie :)

**Comment by Lukasz-Zurek** [comment]
@kulisz Wiem, że tego punktu nie ma na liście :) Inna sprawa - korzystanie z pliku nie jest dobre na dłuższą metę, bo po drodze będą na pewno aktualizacje punktów. Ciężko w tym momencie bazować na jednym pliku.

Natomiast kwestie dotyczące braku punktu ALZABOX1917 są analizowane przez odpowiedni zespół, więc jak tylko uzyskam konkretną informację, wrócę do Ciebie w tym wątku.

**Comment by CSVK2022** [comment]
Dzień dobry, czy udało się coś się ustalić w w/w kwestii? W dalszym ciągu nie jesteśmy w stanie mapować punktów odbioru, których nie zwracacie.

**Comment by Lukasz-Zurek** [comment]
@CSVK2022 Przypomniałem się zespołowi, który weryfikuje ten problem. Proszę o cierpliwość.

**Comment by CSVK2022** [comment]
@Lukasz-Zurek punkt o ID VM01452001: Wybrany punkt odbioru nie jest obsługiwany przez tego przewoźnika, mimo, że znajduje się w wykazie aktywnych punktów, przesłanych kilka wiadomości wcześniej .

**Comment by Lukasz-Zurek** [comment]
@kulisz Punkt ALZABOX1917 był dostępny w momencie zakupu, natomiast został usunięty przez WE|DO niedługo później. Do tego momentu mógł zostać wybrany na formularzu dostawy i zapłaty. Błąd po naszej stronie, ponieważ powinniśmy niezwłocznie przestać zwracać nieaktywny punkt.

Przepraszamy za te utrudnienia.

**Comment by Lukasz-Zurek** [comment]
@CSVK2022 Przekazałem dalej do weryfikacji.

**Comment by CSVK2022** [comment]
Witam, wracam z podobnym problemem, który opisywałem wyżej. 
Tym razem problem występuje z punktami SAZKA. Nie znajdują się ani w dokumentacji od Was ani na mapie WE|DO.
Przykłady :
SAZKA11778801 AWD3359
SAZKA11788301 AWD3455
SAZKA16730401 AWD3597
SAZKA13730901 AWD3364
SAZKA11773202 AWD3380

**Comment by Lukasz-Zurek** [comment]
@CSVK2022 Dziękuję. Dopytuję zespołu odpowiedzialnego za punkty.

**Comment by Lukasz-Zurek** [comment]
@CSVK2022 Mogę potwierdzić problem z punktami. Zespół odpowiedzialny analizuje sytuację. 

Przepraszamy za te utrudnienia.

**Comment by CSVK2022** [comment]
Dziękuję, proszę o info jeżeli się coś uda ustalić.

**Comment by CSVK2022** [comment]
@Lukasz-Zurek czy udało się coś ustalić ?

**Comment by Lukasz-Zurek** [comment]
@CSVK2022 Zgłosiłem ten temat do zespołu odpowiedzialnego za punkty - problem jest bardziej złożony i obejmuje większą liczbę punktów niż zakładano. Poproszę Cię o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@CSVK2022 Zaktualizowaliśmy mapę WE|DO, uspójniając ją z dostępnymi punktami. 

Przepraszamy za utrudnienia.

**Comment by CSVK2022** [comment]
@Lukasz-Zurek Niestety problem z punktami SAZKA dalej aktualny, od wprowadzenia waszej aktualizacji nic się nie zmieniło, zwracany błąd: Wybrany punkt odbioru nie jest obsługiwany przez tego przewoźnika

POST /shipment-management/shipments/create-commands -> trace-id: be58ac8d1064defa
GET /shipment-management/shipments/create-commands/fee353b8-aa00-460f-b812-4771df0eb4d8 -> trace-id: 9f7829b5c2dacfa0

**Comment by Lukasz-Zurek** [comment]
@CSVK2022 Dziękuję Ci za kolejne zgłoszenie. Przekazuję dalej do analizy.

Przepraszamy za te utrudnienia.

**Comment by CSVK2022** [comment]
Czy udało się uzyskać jakieś informacje?

**Comment by Lukasz-Zurek** [comment]
@CSVK2022 Jeszcze nie, oczywiście poinformuję jak to ulegnie zmianie.

**Comment by Lukasz-Zurek** [comment]
@CSVK2022 W podanym przez Ciebie wcześniej przykładzie, próbując nadać przesyłkę z PL do CZ, przekazywałeś nieprawidłowy identyfikator punktu, zamiast SAZKA17607501 powinien być: AWD3382.

**Comment by CSVK2022** [comment]
Dziękuję za pomoc :)
