### ISSUE TITLE
Czas odświeżonego tokena

### ISSUE THREAD

**Issue by mkk852** [allegro/allegro-api#7625]
Dzień dobry,
wykorzystujemy REST API, do którego potrzebny jest token.
Chcemy korzystać z opcji 3msc ważności tokena, dlatego za pomocą php, wykorzystujemy kod umieszczony:
https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena
W efekcie końcowym, zapisujemy jak token, który powinien mieć wydłużoną ważność zmienną $nextToken. 
Wszystkie funkcje wykonują się prawidłowo, zapytania przez API działają z wykorzystaniem $nextToken, jednak działa on maksymalnie 12h i po tym czasie ponownie musimy wywoływać funkcje main().
Co robimy źle? Co powinniśmy zmienić, albo która wartość jest tą, która docelowo jest działającym 3msc tokenem?
Prosimy o pomoc

**Comment by Lukasz-Zurek** [comment]
Podstawowy access_token zawsze jest ważny 12h. Procesu przedłużenia ważności tokena nie można rozumieć dosłownie. Za każdym razem gdy używasz refresh token, w odpowiedzi otrzymujesz nową parę:

- access token (ważny kolejne 12h ),
- refresh token (ważny kolejne 3 miesiące).

Dzięki temu nie musisz za każdym razem od początku się autoryzować. Czyli refresh token pozwala na uzyskanie nowego tokena dostępowego dla danego użytkownika bez konieczności ingerencji z jego strony.

**Comment by mkk852** [comment]
Czy możemy prosić o wskazanie jak powinno zatem wyglądać wykorzystywanie refresh_token, aby nie była wymagana ingerencja użytkownika?
W tym momencie wywołujemy kod 
```php
<?php

define('CLIENT_ID', ''); // wprowadź Client_ID aplikacji
define('CLIENT_SECRET', ''); // wprowadź Client_Secret aplikacji
define('REDIRECT_URI', ''); // wprowadź redirect_uri
define('AUTH_URL', 'https://allegro.pl/auth/oauth/authorize');
define('TOKEN_URL', 'https://allegro.pl/auth/oauth/token');


function getAuthorizationCode() {
    $authorization_redirect_url = AUTH_URL . "?response_type=code&client_id=" 
    . CLIENT_ID . "&redirect_uri=" . REDIRECT_URI;
    ?>
    <html>
    <body>
    <a href="<?php echo $authorization_redirect_url; ?>">Login to Allegro</a>
    </body>
    </html>
    <?php
}

function getCurl($headers, $content) {
    $ch = curl_init();
    curl_setopt_array($ch, array(
        CURLOPT_URL => TOKEN_URL,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => $content
    ));
    return $ch;
}

function getRefreshToken($authorization_code) {
    $authorization = base64_encode(CLIENT_ID.':'.CLIENT_SECRET);
    $authorization_code = urlencode($authorization_code);
    $headers = array("Authorization: Basic {$authorization}","Content-Type: application/x-www-form-urlencoded");
    $content = "grant_type=authorization_code&code=${authorization_code}&redirect_uri=" . REDIRECT_URI;
    $ch = getCurl($headers, $content);
    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong:  $resultCode $tokenResult");
    }
    return json_decode($tokenResult)->refresh_token;
}

function TokenRefresh($token) {
    $authorization = base64_encode(CLIENT_ID.':'.CLIENT_SECRET);
    $headers = array("Authorization: Basic {$authorization}","Content-Type: application/x-www-form-urlencoded");
    $content = "grant_type=refresh_token&refresh_token={$token}&redirect_uri=" . REDIRECT_URI;
    $ch = getCurl($headers, $content);
    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong:  $resultCode $tokenResult");
    }

    return json_decode($tokenResult)->access_token;
}

function main(){
    if ($_GET["code"]) {
        $refreshToken = getRefreshToken($_GET["code"]);
        $nextToken= TokenRefresh($refreshToken);
        echo "access_token = ", $nextToken;
    } else {
        getAuthorizationCode();
    }
}

main();

?>
``` 

Powiedzmy, że
o godz. 10 wywoływana została funkcja main(), użytkownik potwierdził logowanie na allegro
następnie o 10:10 wywoływana jest pierwszy raz i powtarzana co godzinę funkcja x(), która wykorzystuje otrzymany o 10 $nextToken, przez 12h funkcja działa poprawnie, o 22:10 funkcja x() już nie działa, gdyż token jest nieaktualny
jak poprawnie dokonać odświeżenia tokena, aby funkcja x() mogła działać przez kilka dni?
uruchamiając przed upłynięciem 12h funkcji main() nie uzyskujemy otrzymania nowego tokena bez ingerencji użytkownika, potwierdzającego logowanie.
Będziemy wdzięczni za podpowiedzi :)

**Comment by Lukasz-Zurek** [comment]
W naszym poradniku, konkretnie [tutaj](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena) - udostępniliśmy kod realizujący odświeżenie tokena w Pythonie.

W tej sytuacji musisz odświeżać token za każdym razem, przed upływem 12h. Przedłużenie ważności tokena nie wymaga od użytkownika przejścia na stronę zgody tzw. consent screen i ponownego połączenia aplikacji z jego kontem. Do odświeżenia potrzebny jest tak na prawdę tylko refresh_token z wcześniej wygenerowanej pary access_token i refresh_token. 

Czyli co 12h musisz również podmienić access_token (na nowo wygenerowany) dla funkcji x().

**Comment by Lukasz-Zurek** [comment]
Tego typu komunikat błędu pojawia się wówczas, gdy kod potrzebny do wygenerowania pary access_token i refresh_token - jest już nieważny, a jest on ważny 10 sekund. Upewnij się czy mieścisz się w tym czasie.

**Comment by mkk852** [comment]
Niestety chyba potrzebujemy wskazówki, jaka funkcja powinna zostać wywołana podczas działania x() przed upływem 12h, aby token został przedłużony?
wywołując funkcję main() pojawia się okno do potwierdzenia logowania
wykorzystanie samej funkcji getRefreshToken() w x() nie jest możliwe, ponieważ nie mamy $authorization_code który pojawia się po przejściu potwierdzenia logowania

które ze wspomnianych tu: https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena funkcji nalezy zatem użyc i z jakim parametrem, aby móc uzyskać dłuższe działanie tokena?

Prosimy o wsparcie

**Comment by Lukasz-Zurek** [comment]
W naszym tutorialu udostępniliśmy jedynie przykład pokazujący w jaki sposób zdobyć następną parę tokenów za pomocą refresh token. Jak to zrobić głównie ukazuje funkcja `get_next_token()`. Musisz jednak napisać własną implementację, gdzie przechowacie refresh_token i gdzie użyjecie go do odświeżenia. Natomiast sama implementacja, w tym to w jaki sposób to zrobicie, z jakimi warunkami i po jakim czasie zależy już wyłącznie od Was.
