### ISSUE TITLE
DELIVERY_METHOD_NOT_AVAILABLE przy próbie utworzenia paczki

### ISSUE THREAD

**Issue by patryksz14** [allegro/allegro-api#7626]
Próbuję utworzyć testową paczkę (PUT parcel-management/parcel-create-commands/) by wygenerować etykietę przez requesty API wysyłane z postmana, lecz ciągle otrzymuję komunikat DELIVERY_METHOD_NOT_AVAILABLE, choć te konto ma włączone te metody których próbuję używać. Próbowałem z różnymi rodzajami wysyłki, np. DPD czy Allegro One. trace-id requestu: ab4f7d1b1431f43e. Proszę o informację co jest problemem, oraz w jaki sposób mogę to rozwiązać.

**Comment by PrzemyslawLukanowski** [comment]
W requeście musisz przekazać rzeczywisty mail z zamówienia, który jest powiązany z konkretną metodą dostawy wybraną przez kupującego. Na tej podstawie, musisz dobrać odpowiednią usługę dostawy (service id). Informacje o dozwolonych umowach znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke). Jeśli wysyłasz na umowie Allegro, ID metody dostawy zawsze będzie identyczne co ID usługi dostawy. Szczegóły na ten temat znajdziesz także w [naszym newsie.](https://developer.allegro.pl/news/wysylam-z-allegro-zmienimy-identyfikatory-uslug-dostawy-BvMdq20KEIm)
