### ISSUE TITLE
Płatność na sandbox kieruje na nieznany adres 

### ISSUE THREAD

**Issue by jsienkiewicz** [allegro/allegro-api#7627]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Płatność kieruje mnie do nieznanego adresu http://c2c-payu-simulator.dh-test.qxlint/simulator/orders/xxxx**

Czy powyższy adres symulatora płatności jest zarejestrowany w DNS? 
Przy próbie aktywacji sprzedaży i kliknięciu w dowolną metodę płatności (np. BLIK lub mBank), dostaję:
"
Niestety, nie udało się odnaleźć tej strony
Nie udało się połączyć z serwerem pod adresem „c2c-payu-simulator.dh-test.qxlint”.
"

**Comment by PrzemyslawLukanowski** [comment]
Zgłosiłem ten problem do zespołu, który zajmie się weryfikacją problemu. Wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Przygotujemy poprawkę, która wyeliminuje ten problem. Niestety, ale na tę chwilę nie jestem w stanie wskazać, kiedy uda się ją wdrożyć, dlatego na tę chwilę możesz podać nazwę użytkownika, tak abym mógł aktywować konto manualnie.

**Comment by jsienkiewicz** [comment]
Dziękuję,

Czy można aktywować sprzedaż na 3 kontach testowych:
***@***.*** ***@***.***> 

***@***.*** ***@***.***> 

***@***.*** ***@***.***> 

 

Pozdrawiam

Jacek

**Comment by PrzemyslawLukanowski** [comment]
Adresy wyżej zostały niestety zaszyfrowane. Czy możesz podać nazwy użytkowników?

**Comment by jsienkiewicz** [comment]
Oczywiście:
jackiex

Adam01

Bartosz

 

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, aktywowałem pierwsze konto, z drugiego ściągnąłem blokadę sprzedaży, a trzecie było już aktywne.

**Comment by jsienkiewicz** [comment]
Dziękuję, sprzedaż na kontach działa, natomiast tytułowe issue pozostaje otwarte (chociaż dla mojego problemu zablokowanej sprzedaży nie jest w tym momencie istotne)

**Comment by PrzemyslawLukanowski** [comment]
Zgadza się, mamy na uwadze ten problem i planujemy wdrożyć poprawkę. Na tę chwilę nie jestem jednak w stanie wskazać orientacyjnej daty wdrożenia.
