### ISSUE TITLE
How can i use method GET /offers/listing

### ISSUE THREAD

**Issue by allegrocgf** [allegro/allegro-api#7628]
Hello allegro team
I have my own IT team and I want to adjust my prices in batches. I need to use
GET /offers/listing, but the help document tells me that I need to apply, please help me.
Looking forward to hearing from you

Here is a link to the help documentation:
https://developer.allegro.pl/tutorials/how-to-search-and-browse-offers-XxWm2ykMYHl

**Comment by Lukasz-Zurek** [comment]
On our part, we do not verify the application in terms of getting access to GET /offers/listing - these are decisions made entirely outside of us. In this case, I can only encourage you to contact us via [contact form](https://allegro.pl/pomoc/kontakt).

**Comment by allegrocgf** [comment]
Byłem bardzo zmartwiony. Skontaktowałem się z zespołem Allegro za pośrednictwem linku, który mi dałeś, i powiedzieli mi, żebym szukał pomocy na https://github.com/allegro/allegro-api. A kiedy tu pisałem, kazałeś mi się ze mną skontaktować w tle. Skontaktowałem się z obiema stronami, ale jest to bardzo sprzeczne. Proszę o pomoc. Chcę tylko wystąpić o pozwolenie na wywołanie GET /offers/listing.

**Comment by allegrocgf** [comment]
I was very distressed. I contacted the allegro team through the link you gave me, and they told me to seek help at https://github.com/allegro/allegro-api. And when I posted here, you told me to contact me from the background. I contacted both parties, but this is very contradictory. Please help me. I just want to apply for permission to call GET /offers/listing.

**Comment by Lukasz-Zurek** [comment]
@allegrocgf You have clearly been misled through the contact form. You should have been forwarded to the specific department. Please give me your case number so I will try to help you, pushing it forward. Don't worry about that.

**Comment by allegrocgf** [comment]
case no is 36036964

**Comment by Lukasz-Zurek** [comment]
@allegrocgf Thank you.

**Comment by allegrocgf** [comment]
Hello, I haven’t received the message yet. How can I use this method now?

**Comment by Lukasz-Zurek** [comment]
@allegrocgf I have already forwarded your case to the specific department from Customer Service, so you should receive an answer in the case nr 36036964. It is all I could do in this situation, so hopefully you will get some more details soon.

**Comment by allegrocgf** [comment]
ok thank you

**Comment by allegrocgf** [comment]
I have been waiting for many days and I just want to be told what I need to do to use this service.

**Comment by Lukasz-Zurek** [comment]
I just wrote to the specific department and asked about your case. It should not be like this, so I would like to apologize you for waiting for so long without any answer. Hopefully you will receive an answer soon.

**Comment by allegrocgf** [comment]
Okay, thank you. We are in a hurry. Please help us speed up the progress.

**Comment by Lukasz-Zurek** [comment]
@allegrocgf I will do my best, but please note that this case is in another department and as I have already mentioned before - it os out of our hands. I can only let them know that your case is in progress and you still need some answer from their side.

**Comment by allegrocgf** [comment]
Okay, I'm sure you appreciate your help too. But this process took so long, I don’t know why, it’s a simple application process, but it took so long.

**Comment by allegrocgf** [comment]
When can I apply? i have been waiting for a long time

**Comment by Lukasz-Zurek** [comment]
@allegrocgf Unfortunately I don't have any information about your case, this is why I've asked a specific department about the status of your message again. But I suggest you to write another message using our contact form right [here](https://allegro.pl/pomoc/kontakt?kategoria=78c31546-41e0-4305-8a41-4415ed3bd32c), providing all of your data (together with the application name and ClientId - if you are an application creator or if you are the Seller - then give your accounts data and application data which you've received from application creators) and justification - why you need access to GET /offers/listing resource.

As I wrote - this process is out of our hands, so I can only encourage you to write again, using the contact form mentioned above. Hopefully this time you will receive an answer.

**Comment by allegrocgf** [comment]
Then please tell me where I should contact the platform and tell me where to send the email. I will resend the email and write down the precautions you told me.

**Comment by Lukasz-Zurek** [comment]
@allegrocgf I just gave you a link to the contact form in case you do not receive any response. But I've just received a confirmation that the customer service has answered to your previous message. So please continue there.

**Comment by allegrocgf** [comment]
OK, thank you, please help me follow up. This application process has been very long. I need to work as soon as possible. The platform creates APIs for people to use. Rather than requiring such a complicated application process.

**Comment by Lukasz-Zurek** [comment]
The application process is not up to us and our team so unfortunately I cannot help you in this case. But hopefully after receiving an answer from the customer service - the process will go further.
