### ISSUE TITLE
REST API aktualizacja ilości

### ISSUE THREAD

**Issue by mpysz** [allegro/allegro-api#763]
Korzystam z PUT sale/offers/{offerId} do aktualizacji ilości sztuk w ofertach. W odpowiedzi dostaję komunikat:

`The stock level of items may not be lower than sold items`

Jak za pomocą REST API pobrać ilość sprzedanych sztuk dla danej oferty?

**Comment by PawelTaberski** [comment]
W polu stock powinieneś podać ilość aktualnie dostępnych przedmiotów. Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a i responsa wraz z trace-Id sprawdzimy w czym jest problem. Zaznacz w zgłoszeniu, że dane są potrzebne do ticketa na GitHub-ie numer 763.

**Comment by mpysz** [comment]
cURL-a i responsa wraz z trace-Id został wysłany przez formularz.

Rozważmy przypadek:
Produkt w ofercie został kupiony 3 razy. Aktualnie w magazynie zostało 2 sztuki. Wykonując update przez PUT sale/offers/{offerId} tak by kupujący mogli zakupić jeszcze 2 sztuki powinno być:
`stock.available = 2`
czy
`stock.available = 5` ?

**Comment by PawelTaberski** [comment]
Powinieneś podać tyle ile obecnie zostało Tobie do sprzedaży czyli 2 sztuki

**Comment by mpysz** [comment]
Jeśli podam `stock.available = 0` to oferta zostanie zakończona, czy zwrócony zostanie błąd?

**Comment by mpysz** [comment]
Tak, właśnie w takiej sytuacji dostałem błąd, więc sprawa wyjaśniona. Dzięki za szybką odpowiedź.

**Comment by mpysz** [comment]
Wznawiam wątek, bo dotyczy tego samego błędu.

`The stock level of items to be listed may not be lower than 1`

Jednak tym razem podaję stock.avaiable = 1, a mimo tego dostaję powyższy błąd. Gdy ustawię stock.avaiable = 2 to wszystko działa poprawnie.
Proszę o pomoc w tym temacie:
trace-id: 401de2946db35fb7

**Comment by PawelTaberski** [comment]
Podeślij proszę jeszcze pełnego cURL-a i responsa przez [nasz formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). Sprawdzimy w czym jest problem.
W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 763 na GitHub-ie.

**Comment by mpysz** [comment]
Wysłane

**Comment by PawelTaberski** [comment]
@mpysz Dostałem dane od Ciebie i rzeczywiście wygląda to na błąd przekazałem do odpowiedniego zespołu, aby się tym zajęli. Proszę o cierpliwość.
