### ISSUE TITLE
Cannot cancel Allegro carrier shipment / courier pickup

### ISSUE THREAD

**Issue by t0is** [allegro/allegro-api#7630]
Hello

It is not possible to cancel a shipment for Allegro One via API, nor to cancel a courier who is scheduled for pick up tomorrow.

endpoint: `/parcel-management/parcel-cancel-commands/{commandId}`

I get a response -> You cannot cancel a parcel with the Allegro carrier. 

Please, what should be the correct procedure in this case? 

If the customer cancels the order after the shipment is ordered - how do we cancel the shipment? 

If we would at least be able to cancel these via web, that would be enough, but it is not possible either. 

Right now the courier will waste his time and I am worried we will be charged for it as well, even though it is out of our reach. 

Thanks for suggestions.

**Comment by AureliuszBrussy** [comment]
For some carriers, it is not possible to cancel the shipment and/or cancel the pickup order. In this case, the remaining option is to contact the courier company. In the case of Allegro One, for example, you can use the [contact form](https://allegro.pl/kampania/one-pomoc).

**Comment by t0is** [comment]
Thanks for the info. I will contact them.
