### ISSUE TITLE
Obniżka ceny

### ISSUE THREAD

**Issue by Levena007** [allegro/allegro-api#7632]
Witam,
chciałabym przetestować obniżkę cen w sandbox. 
Jednak przy ofertach pokazuje mi że nie posiadam jakości sprzedaży, na odpowiednim poziomie.
Jak mogę przetestować tą funkcjonalność?
Jak podnieś jakoś konta testowego?

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Zasymuluj zakupy z innych kont i sprawdź statystyki w zakładce [Jakość mojej sprzedaży](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/jakosc-sprzedazy). Spróbuj także wykonać inne akcje, które podniosą jakość sprzedaży - wszystkie oceniane obszary wymieniamy w zakładce i [artykule pomocy](https://allegro.pl/pomoc/dla-sprzedajacych/jakosc-mojej-sprzedazy/czym-jest-i-w-czym-pomoze-mi-panel-jakosc-mojej-sprzedazy-AVP4PwzBoCL).

**Comment by Levena007** [comment]
Witam,
czy mogę prosić o informację na temat asymilacji?

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Masz na myśli zasymulowanie? Chodzi o to, abyś zakupiła z innych kont w swoich ofertach, oceniła transakcje itp., tak, aby podbić Jakość sprzedaży.

**Comment by Levena007** [comment]
Kupiłam z 2 konta testowego, oceniłam sprzedającego i na 1 koncie testowym mam komunikat:
"Nie możemy Ci pokazać danych o Twojej jakości sprzedaży
Wskaźniki pokazujemy tylko aktywnym sprzedawcom. W ostatnich 30 dniach na Twoim koncie nie było żadnej aktywnej oferty."

A aktywne aukcje mam bo cały czas testuje

**Comment by AureliuszBrussy** [comment]
Dane są przeliczane raz dziennie, a wyniki wskazują na stan z dnia poprzedniego. Odczekaj, dane powinny się odświeżyć.

**Comment by Levena007** [comment]
ok, dziękuję

**Comment by Levena007** [comment]
Witam,
w dalszym ciągu pojawia się komunikat:
"Wskaźniki pokazujemy tylko aktywnym sprzedawcom. W ostatnich 30 dniach na Twoim koncie nie było żadnej aktywnej oferty."

Wczoraj: kupiłam produkty z wystawionych ofert, oceniłam sprzedaż i dalej nic nie widzę jakości sprzedaży na tym koncie.

Czy mogę prosić o pomoc?
konto: test-company
sandbox

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
@Levena007 czy możesz podpowiedzieć jeszcze jaką dokładnie funkcjonalność chcesz przetestować (a uniemożliwia to brak Jakości sprzedaży)?

**Comment by Levena007** [comment]
Chciałabym przetestować programy, które oferuję "zniżkę" dla klienta, np. Strefa Okazji, Okazja itp

**Comment by AureliuszBrussy** [comment]
@Levena007 rozumiem, że chodzi przede wszystkim o [Kampanie](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/kampanie)? Na Sandbox udostępnialiśmy specjalną kampanię, która służyła do testów funkcjonalności (nie wymagała spełniania dodatkowych kryteriów), w tym momencie nie jest dostępna. Wyjaśniam to z zespołem odpowiedzialnym za ten zasób.

**Comment by Levena007** [comment]
Zastanawiam się również czy macie jakąś checklistę co warto przetestować (mam na myśli transfer zamówienia z allegro do ERP). Mam na myśli właśnie o kampanie i programy, zakupy z konta biznesowego, zestawy itp. A wiec potencjalne rzeczy, które się mogą wysypać

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Nie mamy takiej checklisty, natomiast na pewno warto [przejrzeć poradnik](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR) i zwrócić uwagę na kwestię nadpłat/niedopłat, rozpoznawania Allegro Ceny i realizacji zwrotów i zwrotów środków w ramach Allegro Finanse.

**Comment by AureliuszBrussy** [comment]
@Levena007 dodaliśmy kampanię SANDBOX_TEST_CAMPAIGN, która nie wymaga spełnienia dodatkowych wymagań, prócz obniżki o minimum 40%. Możesz z niej skorzystać aby przetestować działanie oznaczeń.

**Comment by Levena007** [comment]
Dziękuję, nie ma tu jednak na poziomie oferty, rabatu np. 15%. Czy mogę prosić również o taką?

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
@Levena007 niestety, ale nie mamy takiej kampanii. Pozostaje użycie do testów tej zdefiniowanej wcześniej: SANDBOX_TEST_CAMPAIGN.
