### ISSUE TITLE
Product offers 403

### ISSUE THREAD

**Issue by vyvledav** [allegro/allegro-api#7633]
Hello,
upon calling GET https://api.allegro.pl/sale/product-offers/14298203237 we receive 403 Forbidden.
Communication works well, orders etc. are accessible. Using device flow authorization.
Trace ID: c3d0407b99f13054
Does this require any other level of authorisation? We need to get details of offer as we need EAN to pair items from Allegro with our items...
Thanks.

**Comment by AureliuszBrussy** [comment]
The access token you generated is missing the correct scope. Required scope: [allegro:api:sale:offers:read]. Your actual scope are: ["allegro:api:orders:read","allegro:api:payments:read","allegro:api:orders:write"].
