### ISSUE TITLE
warranty

### ISSUE THREAD

**Issue by kochanA** [allegro/allegro-api#7634]
Dzień dobry,
czy jest możliwe utworzenie gwarancji bez załącznika ? 
W poradniku znalazłam informacje, że tak (attachment - niewymagane, załącznik do gwarancji) lecz przy próbie utworzenia warranty dostaje błąd : "Invalid format of file test warranty. The attachment must be in PDF format"
przesyłam trace_id zapytania : 'e152b3e0d83d50cc'

**Comment by AureliuszBrussy** [comment]
Tak, możliwe jest utworzenie gwarancji bez załącznika. W swoim requeście korzystasz z endpointu ([POST /after-sales-service-conditions/attachments](https://developer.allegro.pl/documentation#operation/createAfterSalesServiceConditionsAttachmentUsingPOST)) właśnie służącego do tworzenia obiektu załącznika. Możesz po prostu pominąć ten krok.
