### ISSUE TITLE
Błędne informacje z /order/event-stats

### ISSUE THREAD

**Issue by e-macs** [allegro/allegro-api#7635]
Prowadzę dla kilku klientów system do zarządzania zamówieniami. Wykorzystuję do tego zapytanie /order/event-stats aby pobrać najnowszy event w celu dalszego odpytywania o najnowsze zamówienia. W jednym przypadku(dla jednego klienta) zapytanie to niestety zwraca non stop ten sam numer jakiegoś eventu z lipca, konkretnie 1690007823733824. Nie powinienem tu prawdopodobnie podawać nazwy konta firmy której dotyczy ten problem, więc proszę o wiadomość prywatną jeżeli jest taka możliwość lub utajnienie tego zgłoszenia.

**Comment by AureliuszBrussy** [comment]
Czy możesz podać przykładowe trace-id swojego wywołania? Trace-id znajdziesz w nagłówku naszego response'a. W ten sposób sprawdzimy konkretny request i będę miał wystarczającą ilość danych do weryfikacji.

**Comment by e-macs** [comment]
Proszę: ad37a5489eb4f1

**Comment by AureliuszBrussy** [comment]
Czy to na pewno request wykonany w imieniu tego użytkownika? Ostatni event, jaki dla niego zwracamy jest z dzisiaj (2023-09-19T07:47:59.726Z), wiec nie potwierdzam tego problemu.

**Comment by e-macs** [comment]
może coś źle patrze, a taki id: 45c9700eeaeb964b ?

**Comment by AureliuszBrussy** [comment]
Wciąż nie potwierdzam problemu - zwracamy najnowszy event z datą 2023-09-19T09:42:22.206Z.
