### ISSUE TITLE
Problem z dodaniem produktu

### ISSUE THREAD

**Issue by hyper-cube** [allegro/allegro-api#7636]
Witam, nie mogę dodać produktu w kategorii (id: 257358), dostaję informacje, że w tej kategorii dodawanie produktu jest niemożliwe. Jak mam dodać nowe produkty, które chcielibyśmy (jako producent tych produktów) wstawić na Allegro?

Z góry dziękuję za odpowiedź.

**Comment by AureliuszBrussy** [comment]
W kategorii tej zwracamy wartość false w "productCreationEnabled" ([GET /sale/categories/{categoryId}](https://developer.allegro.pl/documentation#operation/getCategoryUsingGET_1)), więc faktycznie nie udostępniamy w niej opcji tworzenia nowych produktów.  Jeżeli masz uwagi co do braku tej możliwość - przekaż je w [formularzu kontaktowym](https://allegro.pl/pomoc/kontakt).
