### ISSUE TITLE
Pytanie o budowę zapytania wyszukiwarki ofert

### ISSUE THREAD

**Issue by arturniemiec** [allegro/allegro-api#7637]
Dzień dobry,

czytam dokumentację AllegroAPI i mam pytanie - w jaki sposób prawidłowo zbudować request, aby otrzymać w JSON informację zwrotną spełniającą kryteria (kategoria: Allegro->Elektronika->Komputery->Laptopy):
![image](https://github.com/allegro/allegro-api/assets/119438303/718ef622-0785-4615-9ac4-504acd81d2d9)

Gdzie mogę znaleźć listę tych oraz innych parametrów do przekazania? Póki co to testowałem request idąc krok po kroku z tutorialu w Waszej dokumentacji:
```
def get_main_categories(token):
    try:
        url = "https://api.allegro.pl.allegrosandbox.pl/offers/listing?category.id=165&phrase=Samsung&parameter.202865=202865_214113&parameter.202865=202865_214117&parameter.219=219_256&offset=1"
        headers = {'Authorization': 'Bearer ' + token, 'Accept': "application/vnd.allegro.public.v1+json"}
        main_categories_result = requests.get(url, headers=headers, verify=False)
        return main_categories_result
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)
```
Podsumowując - w jaki sposób powyższe parametry mogę umieścić w wartość zmiennej url? I gdzie znajdę nazwę pozostałych parametrów? Z góry dziękuję i pozdrawiam!

**Comment by AureliuszBrussy** [comment]
Gdy rozpoczniesz wyszukiwanie w konkretnej kategorii (GET /offers/listing?category.id=165), w odpowiedzi w sekcji "**filters**" zwrócimy wszystkie możliwe do użycia w danej kategorii dynamiczne parametry. Możesz wykorzystać tą tablicę to dalszego doprecyzowania swojego wyszukiwania. Więcej o tym piszemy w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk#jak-filtrowac-wyniki-wyszukiwania).

**Comment by arturniemiec** [comment]
Dziękuję za odpowiedź. Mam jeszcze jedno pytanie - gdy wykonuje requesty idąc instrukcją krok po kroku, otrzymuję taki oto komunikat zanim otrzymam odpowiedź. Czy to "normalne"? W jaki sposób można go wyłączyć?
![FB_IMG_1695121064433](https://github.com/allegro/allegro-api/assets/119438303/dd85d5ae-dbbc-4e79-8518-da01c1a9af77)

**Comment by AureliuszBrussy** [comment]
Dzieje się tak, gdy żądanie jest kierowane do adresu URL HTTPS bez włączonej weryfikacji certyfikatu SSL. Więcej o certyfikatach w kontekście tej biblioteki [przeczytasz w dokumentacji](https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl). Na własne potrzeby możesz ew. wyłączyć te ostrzeżenia.
