### ISSUE TITLE
Error: "Product already exists"

### ISSUE THREAD

**Issue by lukzaj9** [allegro/allegro-api#7639]
Czy mogę otrzymać jakieś informacje odnośnie błędu? Wcześniej ten błąd się nie pojawiał. Otrzymuję zwrotkę:

{"errors":[{"code":"ProductDuplicate","message":"An error has occurred","details":null,"path":null,"userMessage":"Product already exists. Contact the application author."}]}

Dzięki za pomoc.

**Comment by Lukasz-Zurek** [comment]
Krótko mówiąc oznacza to tyle, że taki produkt już istnieje i w nagłówku odpowiedzi, w "location" zwracamy identyfikator produktu, którego rozpoznaliśmy jako duplikat.

W przypadku produktów sprawdzamy parametry oznaczone **„describesProduct”**, które pozwalają nam stwierdzić, czy podane dane nie znajdują się już w naszej bazie jako inny produkt. Parametry te znajdziesz za pomocą [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).

**Comment by justynapalka** [comment]
Dzień dobry,
dla jasności, oznacza to, że dany produkt istnieje w ogólnym katalogu Allegro, a my poprzez API próbujemy utworzyć go na nowo?

**Comment by Lukasz-Zurek** [comment]
@justynapalka Tak, dokładnie. Wykrywamy istniejący już produkt z identycznymi danymi.

**Comment by justynapalka** [comment]
Dzień dobry,
czy jest w stanie Pan podać mi jaką informację powinniśmy w takiej sytuacji przesyłać, gdy produkt już istnieje i "podpinamy" pod niego nową ofertę?

**Comment by Lukasz-Zurek** [comment]
W sytuacji, gdy produkt już istnieje i w nagłówku odpowiedzi, w "location" zwracamy identyfikator produktu, którego rozpoznaliśmy jako duplikat - sugerujemy, aby przekazać właśnie ten produkt, w części "productSet.product.id". W przypadku takiego żądania, należy pamiętać, że dane (np. parametry) pobierzemy z danych tego konkretnego produktu.
