### ISSUE TITLE
"Product needs to have at least one image" error, pomimo tego że wysyłam images

### ISSUE THREAD

**Issue by adibuu** [allegro/allegro-api#7641]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Chcę wystawić ofertę poprzez API w allegro sandbox. W tym celu wysyłam POST na adres: https://api.allegro.pl.allegrosandbox.pl/sale/product-offers

z body:
`        "productSet": [
            {
                "product": {
                    "name": "Plecki Nillkin CamShield Pro do Samsung Galaxy S22 Ultra czarne",
                    "category": {
                        "id": "353"
                    },
                    "parameters": [
                        {
                            "id": "219781",
                            "name": "Dedykowany model",
                            "valuesLabels": [
                                "Galaxy S22 Ultra"
                            ],
                            "values": [
                                "Galaxy S22 Ultra"
                            ],
                            "unit": null,
                            "options": {
                                "identifiesProduct": true
                            }
                        },
                        {
                            "id": "224017",
                            "name": "Kod producenta",
                            "valuesLabels": [
                                "17119"
                            ],
                            "values": [
                                "17119"
                            ],
                            "unit": null,
                            "options": {
                                "identifiesProduct": false
                            }
                        },
                        {
                            "id": "248135",
                            "valuesIds": [
                                "248135_1134745"
                            ]
                        },
                        {
                            "id": "207786",
                            "name": "Przeznaczenie",
                            "valuesLabels": [
                                "Samsung"
                            ],
                            "valuesIds": [
                                "207786_233858"
                            ],
                            "values": null,
                            "unit": null,
                            "options": {
                                "identifiesProduct": false
                            }
                        },
                        {
                            "id": "206002",
                            "valuesIds": [
                                "206002_225590"
                            ]
                        },
                        {
                            "id": "207790",
                            "name": "Typ",
                            "valuesLabels": [
                                "plecki"
                            ],
                            "valuesIds": [
                                "207790_233882"
                            ],
                            "values": null,
                            "unit": null,
                            "options": {
                                "identifiesProduct": false
                            }
                        },
                        {
                            "id": "207798",
                            "name": "Materiał",
                            "valuesLabels": [
                                "tworzywo sztuczne"
                            ],
                            "valuesIds": [
                                "207798_233910"
                            ],
                            "values": null,
                            "unit": null,
                            "options": {
                                "identifiesProduct": false
                            }
                        },
                        {
                            "id": "207802",
                            "name": "Funkcje",
                            "valuesLabels": [
                                "pochłanianie wstrząsów"
                            ],
                            "valuesIds": [
                                "207802_4"
                            ],
                            "values": null,
                            "unit": null,
                            "options": {
                                "identifiesProduct": false
                            }
                        },
                        {
                            "id": "17448",
                            "name": "Waga produktu z opakowaniem jednostkowym",
                            "valuesLabels": [
                                "0,110 kg"
                            ],
                            "values": [
                                "0.110"
                            ],
                            "unit": "kg",
                            "options": {
                                "identifiesProduct": false
                            }
                        },
                        {
                            "id": "225693",
                            "values": [
                                "6902048235328"
                            ]
                        },
                        {
                            "id": "249372",
                            "name": "Kolekcja",
                            "valuesLabels": [
                                "CamShield Pro"
                            ],
                            "values": [
                                "CamShield Pro"
                            ],
                            "unit": null,
                            "options": {
                                "identifiesProduct": false
                            }
                        }
                    ],
                    "images": [
                        "https://a.allegroimg.com/original/111be1/660eef6548b88dfba1cdeb8b70b6",
                        "https://a.allegroimg.com/original/11b829/e3d82d874d1dbaf1b313542e078c",
                        "https://a.allegroimg.com/original/113be5/57c425854ac3bd7792a4e63c321d",
                        "https://a.allegroimg.com/original/110edc/79d95e9f4719804d463ca76bd655",
                        "https://a.allegroimg.com/original/1125a7/beb2424e406eb542bee745a4caa6",
                        "https://a.allegroimg.com/original/11f3bb/9c9758cf45d8a6c9ec9cb15b1e4a",
                        "https://a.allegroimg.com/original/110e43/7c19da9d41bd877e57475d8dbd10",
                        "https://a.allegroimg.com/original/11d17d/5bba59b848ca970f95cce857934a",
                        "https://a.allegroimg.com/original/11ebd0/5ec89130499398071d0446d5bba0",
                        "https://a.allegroimg.com/original/110388/e7a49b574486a687d96055e90e4d",
                        "https://a.allegroimg.com/original/11ade6/2c151a674d07a232ddf0879a1ee5",
                        "https://a.allegroimg.com/original/11b232/4a7a70b64cf89424f04662585dd4",
                        "https://a.allegroimg.com/original/11c178/1208d5b64872a6470433060b8877",
                        "https://a.allegroimg.com/original/257491/7a8e35434558b286d917c6a49175",
                        "https://a.allegroimg.com/original/11e53f/2b2112ba42dbb716c75d241406a3",
                        "https://a.allegroimg.com/original/11ff58/e5aa53ad43f180cc3d513b76a3f5"
                    ]
                }
            }
        ],
        "parameters": [
            {
                "id": "11323",
                "valuesIds": [
                    "11323_1"
                ]
            },
            {
                "id": "229205",
                "valuesIds": [
                    "229205_340245"
                ]
            }
        ],
        "description": {
            "sections": [
                {
                    "items": [
                        {
                            "type": "TEXT",
                            "content": "<p>Wysokiej jakości etui Camshield Case to świetny sposób na zadbanie nie tylko ochronę swojego urządzenia, lecz i swojej prywatności.</p><p>Produkt wykonany został z wytrzymałego tworzywa PC, które cechuje wysoka odporność na ścieranie oraz uszkodzenia mechanicznie.</p><p>Warto wspomnieć o głównym atucie produktu, którym niewątpliwie jest zamontowany na rewersie slider, dzięki któremu zasłonimy i jednocześnie ochronimy, obszerny aparat zamontowany na rewersie naszego urządzenia.</p><h2>Główne cechy produktu</h2><ul><li>Oryginalny produkt marki Nillkin</li><li>Prywatyzujący, ochronny slider wyniesiony powyżej krawędzi aparatu</li><li>Produkt wykonany z wysokiej jakości materiałów</li><li>Idealne dopasowanie do dedykowanego modelu</li><li>Estetyczny, minimalistyczny design</li><li>Antypoślizgowa powierzchnia rantów</li></ul><h2>Zestaw zawiera</h2><ul><li>Etui Nillkin Camshield Samsung Galaxy S22 Ultra</li></ul>"
                        }
                    ]
                },
                {
                    "items": [
                        {
                            "type": "IMAGE",
                            "url": "https://a.allegroimg.com/original/111be1/660eef6548b88dfba1cdeb8b70b6"
                        }
                    ]
                }
            ]
        },
        "sellingMode": {
            "price": {
                "amount": 73.53,
                "currency": "PLN"
            }
        },
        "stock": {
            "available": 10
        },
        "delivery": {
            "shippingRates": {
                "id": "c872bbd8-9c89-42c5-81f0-c995c9c878e5"
            }
        }`

w odpowiedzi otrzymuję:

`"errors": [
            {
                "code": "ProductValidationException",
                "message": "Product needs to have at least one image",
                "details": null,
                "path": "productSet[0].product",
                "userMessage": "Produkt powinien posiadać co najmniej jedno zdjęcie"
            }
        ]`
        
Dlaczego otrzymuję taki błąd skoro do oferty w productSet[0].product dołączam images?

TRACE-ID = 17c852577fe08c19

**Comment by AureliuszBrussy** [comment]
Problem powoduje próba skorzystania ze zdjęć ze środowiska produkcyjnego. Spróbuj dodać zdjęcia z serwera zewnętrznego lub wgraj zdjęcia za pomocą [POST https://api.allegro.pl.allegrosandbox.pl/sale/images](https://developer.allegro.pl/documentation#tag/Images-and-attachments) i później dodaj je do swojego żądania.

**Comment by adibuu** [comment]
Zmieniłem images w productSet[0].product na tablicę ze zdjęciami z zewnętrznego serwera:

`                    "images": [
                        "https://eoptimo.eu/data/gfx/pictures/large/5/0/4405_5.jpg",
                        "https://eoptimo.eu/data/gfx/pictures/large/5/0/4405_4.jpg",
                        "https://eoptimo.eu/data/gfx/pictures/large/5/0/4405_3.jpg",
                        "https://eoptimo.eu/data/gfx/pictures/large/5/0/4405_2.jpg",
                        "https://eoptimo.eu/data/gfx/pictures/large/5/0/4405_1.jpg"
                    ]`
                    
Niestety, otrzymuję teraz taki błąd:
`        "errors": [
            {
                "code": "OfferImagesNotFoundException",
                "message": "Invalid image address.",
                "details": "OfferImagesNotFoundException",
                "path": null,
                "userMessage": "Podany adres obrazka jest nieprawidłowy."
            }
        ]`

Oczywiście wszystkie adresy do zdjęć działają (można je sprawdzić otwierając adres w przeglądarce).

TRACE-ID: ab0338718ec46cdf

**Comment by AureliuszBrussy** [comment]
Podmieniłeś też zdjęcia w `description`?

**Comment by adibuu** [comment]
Faktycznie, zapomniałem o jednym zdjęciu w opisie. Po jego zmianie jest już ok, oferta została dodana. Dzięki za pomoc 😄
