### ISSUE TITLE
Nie można pobrać zdjęcia z adresu

### ISSUE THREAD

**Issue by Bober95** [allegro/allegro-api#7642]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Podczas próby dodania nowego produktu zwracane są błędy pobrania zdjęcia przez wasze serwery
'Nie można pobrać zdjęcia z adresu ''. Serwer ze zdjęciem zwrócił kod HTTP: 403 FORBIDDEN z błędem: ''.'

Oczywiście przez przeglądarkę obraz jest normalnie dostępny.
TraceID: 2e5de9026fd2858

**Comment by AureliuszBrussy** [comment]
Sprawdzamy to. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Serwer odrzuca nasze żądanie z nagłówkiem: `User-agent: Allegro-ImageDownloader/1.0` i zwraca błąd 403.
