### ISSUE TITLE
Tytuły długości 75 znaków przez API

### ISSUE THREAD

**Issue by PawelPseudo** [allegro/allegro-api#7643]
Witam

Od dzisiaj maja byc tytuly z 50 znakow na 75:
https://developer.allegro.pl/news/zwiekszymy-maksymalny-limit-znakow-w-tytule-oferty-wwVmjaAv2Sz

Czy to juz weszlo na produkcje ?

**Comment by AureliuszBrussy** [comment]
Jeszcze nie wdrożyliśmy tej zmiany. Dam znać, gdy tylko będzie dostępna na produkcji.

**Comment by PawelPseudo** [comment]
A przybliżony termin ?
Dzisiaj, jutro, za miesiąc ?

**Comment by AureliuszBrussy** [comment]
Zgodnie z zapowiedzią, zmianę planujemy wdrożyć dzisiaj. Proszę o jeszcze trochę cierpliwości.

**Comment by AureliuszBrussy** [comment]
@PawelPseudo wdrożyliśmy zmianę.
