### ISSUE TITLE
Link afiliacyjny poprzez API

### ISSUE THREAD

**Issue by arturniemiec** [allegro/allegro-api#7648]
Dzień dobry,

Czy można utworzyć link afiliacyjny w ramach Allegro Polecam poprzez API? Czy jest w planach taka możliwość? Póki co to tylko można zrobić to "ręcznie". Pozdrawiam!

**Comment by AureliuszBrussy** [comment]
Nie udostępniamy takiej możliwości w ramach publicznego API Allegro. Na ten moment nie mamy takich planów, jeżeli natomiast coś się zmieni - będziemy to standardowo komunikować tutaj na GitHubie oraz na [developer portalu](https://developer.allegro.pl/news).
