### ISSUE TITLE
Problem z odzyskaniem moich zakupów przez API /order/checkout-forms

### ISSUE THREAD

**Issue by andreicpp** [allegro/allegro-api#7649]
Dzień dobry,

Dlaczego nie mogę odzyskać przez API zakupów (dostaje pusty JSON typu "checkoutForms": []) , mimo że mam aktywną historię zakupów (ostatni rzut ekranu) oraz poprawne dostępy w konfiguracji API:
- "Lista zamówień" ([GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET)), trace-id 22ab46ccb81855f4
- "Dziennik zdarzeń" ([GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET)), trace-id c72fc5b0f970ae67

Próbowałem również odzyskać wiadomości [GET /messaging/threads](https://developer.allegro.pl/documentation#operation/listThreadsGET) z identyfikatorem śledzenia trace-id 3b996edaf1989edb, gdzie zapytanie jest również typu GET i wymaga bearer-token-for-user, i wszystko działa.

Dziękuję za pomoc.

<img width="1048" alt="Screenshot 2023-09-20 at 1 12 00 PM" src="https://github.com/allegro/allegro-api/assets/14205323/302a20d5-9a4e-4908-ae5b-613925b709f1">
<img width="1007" alt="Screenshot 2023-09-20 at 1 19 16 PM" src="https://github.com/allegro/allegro-api/assets/14205323/6b384cf2-1e7e-4f57-91c6-c74711b161dd">
<img width="1031" alt="Screenshot 2023-09-20 at 1 12 22 PM" src="https://github.com/allegro/allegro-api/assets/14205323/0f27f4f0-a7dc-4d5d-8cfc-15621cbe58c3">
<img width="628" alt="Screenshot 2023-09-20 at 1 21 02 PM" src="https://github.com/allegro/allegro-api/assets/14205323/82c71404-6efe-4b21-9747-b65894c2920c">

**Comment by AureliuszBrussy** [comment]
Przez publiczne API Allegro możesz pobrać tylko listę zamówień sprzedawcy, a nie listę zakupów po stronie kupującego.

**Comment by andreicpp** [comment]
Dziękuje za odpowiedź. A czy istnieje sposób to zrobić po stronie kupującego?

**Comment by AureliuszBrussy** [comment]
Nie, nie udostępniamy takich zasobów.
