### ISSUE TITLE
'PORÓWNAJ X OFERTY TEGO PRODUKTU' - jak to sprawdzić przez API?

### ISSUE THREAD

**Issue by ZakuroPL** [allegro/allegro-api#7650]
Witam.
Przeglądałem dokumentacje oraz stare wątki i przyznaje, że nie udało mi się znaleźć odp. więc pytam :-)

Powiedzcie mi proszę jakim zapytaniem API i jaki parametr da mi informacje o tym ile ofert jest podpiętych pod dany produkt. Wiele sklepów podpina się pod nasze własne produkty, które tak naprawdę nie są naszymi i chcemy zautomatyzować to przez API, aby otrzymywać raport dotyczący ile ofert jest podpiętych pod dany produkt, aby ułatwić nam zgłaszanie to.

**Comment by AureliuszBrussy** [comment]
Nie udostępniamy zasobu, który pozwoliłby na uzyskanie informacji ile i jakie oferty są podpięte pod konkretny produkt.
