### ISSUE TITLE
how get offer_id, ean and MPN

### ISSUE THREAD

**Issue by mpavelcz** [allegro/allegro-api#7652]
Hello,
is there posible get list of products with offer id, EAN and MPN?
When I use /sale/products?phrase with EAN or MPN, there is not offer_id.
And when I use /sale/offers?limit&offset here is offer_id but not EAN or MPN.

Thank you.

**Comment by Lukasz-Zurek** [comment]
Let me explain a bit:

- [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts) - you search here for products in our database - you will not find your offers here.
- [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) - you will retrieve the list of offers of a given seller, but there are no parameters here where you would find data such as EAN. They are only in the details of the offer [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getProductOffer).

Summary: There is no resource in the Allegro API where you could get a list with such data directly.

**Comment by mpavelcz** [comment]
Ok, but how I can update offer if I cant find offerId.
Is posible use: PATCH /sale/product-offers/{offerId} ?

I need update hanglingTime on our products.

**Comment by Lukasz-Zurek** [comment]
@mpavelcz You can find you offer by using [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET). Obviously you can use on of our filters, described [here](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#filtry).

Of course you can use PATCH /sale/product-offers/{offerId} to update handlingTime in one of your offers. You can edit any field of the offer, and at the same time you do not have to transfer its entire model.
