### ISSUE TITLE
Czy API umożliwia sprawdzanie statusu listingów?

### ISSUE THREAD

**Issue by niemawolnychusername** [allegro/allegro-api#7653]
Tak jak w tytule, czy API przewiduje możliwość sprawdzania statusu (aktywne, wygaśnięte, archiwum itd.) wybranych listingów?

Z góry dziękuję za odpowiedź, pozdrawiam.

**Comment by Lukasz-Zurek** [comment]
W przypadku [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) możesz filtrować po **publication.status** - "INACTIVE" "ACTIVE" "ACTIVATING" "ENDED". Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#filtry).

Natomiast jeżeli chodzi o [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing), który wymaga [dodatkowej weryfikacji](https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk#jak-wyszukiwac-i-przegladac-oferty) - takiej możliwości nie ma.
