### ISSUE TITLE
New exception - MatchingProductNotFoundException 

### ISSUE THREAD

**Issue by Marek-ShopStore** [allegro/allegro-api#7654]
Hello,

we are getting new exception - MatchingProductNotFoundException
There was exception ProductNotFoundException before is it same exception or does this new one have different meaning?

**Comment by Lukasz-Zurek** [comment]
We have changed this exception from ProductNotFoundException to MatchingProductNotFoundException, mostly because userMessage is wider - in this case a product can also be created (if we have a complete product definition).
