### ISSUE TITLE
Dziwne eventy aukcji, która nie została zalicytowana

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#7655]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam ponownie,

mam taką bardzo dziwną zagwostkę. Mianowicie mam przypadek aukcji (14312995023), dla której zwrócono takie eventy:

```
MTY5NDQ1MjIwNjExMjMxOQ	OFFER_STOCK_CHANGED	1694452195798
MTY5NDQ1MjIwODkxNjgyNA	OFFER_STOCK_CHANGED	1694452195798
MTY5NDUxNDEzMTE1NDI3Nw	OFFER_ACTIVATED	        1694514120000
MTY5NDgwNDE2MjEwODU3Mw	OFFER_STOCK_CHANGED	1694804151857
MTY5NDgwNDE2Mjk4MzQ2Nw	OFFER_BID_PLACED	1694804151813
MTY5NDgwNDE5NDg0MjEzNw	OFFER_BID_PLACED	1694804184398
MTY5NTAyMDEwNDI3NjE2Nw	OFFER_BID_CANCELED	1695020092946
MTY5NTExODkzMDQ3NjIxNA	OFFER_ENDED	        1695118920000
```

Problem polega na tym, że oferta zakończyła się bez sprzedaży i ja nie wiem, co się z nią dokładnie działo. Nie widzę na portalu żadnych śladów, że była ona kiedykolwiek licytowana. Skąd zatem te zdarzenia w dzienniku? 

Pozdrawiam.

**Comment by Lukasz-Zurek** [comment]
Dzięki za szczegóły. Wyjaśniamy to. Wkrótce wrócę z informacją.

**Comment by hahyes** [comment]
@Lukasz-Zurek Nie powiem, że jestem troszkę zawiedziony no ale trudno, rozumiem. Postaram się dostarczyć inny przykład, jeżeli sytuacja wystąpi ponownie. Pozdrawiam. :)
