### ISSUE TITLE
pricing/offer-fee-preview nie wyswietla wszystkie prowizji.

### ISSUE THREAD

**Issue by info1234567890** [allegro/allegro-api#7657]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by info1234567890** [comment]
Od oferty pobierana jest prowizja strefy okazji, w metodzie tej prowizji brakuje

**Comment by info1234567890** [comment]
Dodatkową informację przez https://allegro.pl/pomoc/kontakt mogę przesłać, ponieważ jedynym komunikatem jest GitHub API Allegro.

**Comment by info1234567890** [comment]
*nie mogę przesłać

**Comment by AureliuszBrussy** [comment]
Kalkulator opłat działa na podstawie parametrów i danych przekazanych w ramach modelu oferty. Strefa okazji i inne kampanie nie są częścią modelu oferty, dlatego ten czynnik nie jest w ogóle brany pod uwagę w kalkulatorze. Jednym słowem - w kalkulatorze nie wyliczysz opłat pobieranych w ramach zgłoszenia oferty do kampanii.
