### ISSUE TITLE
Python - problem z odświeżeniem ważności tokena

### ISSUE THREAD

**Issue by arturniemiec** [allegro/allegro-api#7659]
Dzień dobry,

po testach w sandboxie chciałem przejść na pracę na "żywym organiźmie" Allegro poprzez API. Zarejestrowałem aplikację śledząc instrukcję, otrzymałem ClientID oraz ClientSecret tak jak powinno być. Teraz aby otrzymać token, skorzystałem z [tej instrukcji](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#python). Po wklejeniu do kodu mojego ClientID oraz ClientSecret, jestem proszony o kod. Problem w tym że nie wiem skąd ten kod uzyskać. Gdy zostaję przekierowany na stronę składającą się z 

> AUTH_URL + '?response_type=code&client_id=' + CLIENT_ID + \
>                                  '&redirect_uri=' + REDIRECT_URI

Mam taki oto obraz:
![image](https://github.com/allegro/allegro-api/assets/119438303/398af374-2217-41ee-b046-83e3b5688785)

Dlaczego tak się dzieje? Jak mogę to naprawić? 
Niejasny dla mnie jest REDIRECT_URI i podejrzewam że tutaj tkwi problem - czym miałby być ten adres? Mam nadzieję, że nie jest założeniem że aby uzyskać token/odświeżyć token muszę mieć napisany jakąś własną aplikację webową, której adresem jest właśnie REDIRECT_URI. W instrukcji nie zauważyłem opisu czym jest REDIRECT_URI. Zaznaczam, że jestem mocno początkujący jeżeli chodzi o API Allegro.

Generalnie ideą aplikacji jest możliwość wyszukiwania ofert spełniających określone parametry (opcja KUP TERAZ, przedmiot NOWY) oraz dostęp do Tytułu oferty, ceny, obrazka. Aplikacja nie będzie wystawiać sprzedaży itp. Bardzo mi zależy aby pozyskiwanie tokena czy jego odświeżenie odbywało się w 100% automatycznie.

Całość mojego kodu wygląda w ten sposób:
```
import requests
import json
from __api_credencials import *

CLIENT_ID = clientId()
CLIENT_SECRET = clientSecret()
REDIRECT_URI = "http://exemplary.redirect.uri"       # wprowadź redirect_uri
AUTH_URL = "https://allegro.pl/auth/oauth/authorize"
TOKEN_URL = "https://allegro.pl/auth/oauth/token"

def get_authorization_code():
    authorization_redirect_url = AUTH_URL + '?response_type=code&client_id=' + CLIENT_ID + \
                                 '&redirect_uri=' + REDIRECT_URI
    print("Login to Allegro - use url in your browser and then enter authorization code from returned url: ")
    print("---  " + authorization_redirect_url + "  ---")
    authorization_code = input('code: ')
    return authorization_code


def get_refresh_token(authorization_code):
    try:
        data = {'grant_type': 'authorization_code', 'code': authorization_code, 'redirect_uri': REDIRECT_URI}
        access_token_response = requests.post(TOKEN_URL, data=data, verify=False,
                                              allow_redirects=False, auth=(CLIENT_ID, CLIENT_SECRET))
        tokens = json.loads(access_token_response.text)
        access_token = tokens['refresh_token']
        return access_token
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)


def get_next_token(token):
    try:
        data = {'grant_type': 'refresh_token', 'refresh_token': token, 'redirect_uri': REDIRECT_URI}
        access_token_response = requests.post(TOKEN_URL, data=data, verify=False,
                                              allow_redirects=False, auth=(CLIENT_ID, CLIENT_SECRET))
        tokens = json.loads(access_token_response.text)
        access_token = tokens['access_token']
        return access_token
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)

def main():
    authorization_code = get_authorization_code()
    refresh_token = get_refresh_token(authorization_code)
    print("refresh token = " + refresh_token)
    next_token = get_next_token(refresh_token)
    print("next access token = " + next_token)
    
if __name__ == "__main__":
    main()
```

Pozdrawiam!

**Comment by AureliuszBrussy** [comment]
Adresy do przekierowania to adresy aplikacji, do których przekazany ma zostać przez nas kod autoryzujący - możesz wtedy go przechwycić. 

Błąd jest spowodowany tym, że w swoim kodzie przekazujesz wartość "http://exemplary.redirect.uri", a nie jest ona zdefiniowana w  ustawieniach aplikacji w [Allegro Developer Apps](https://apps.developer.allegro.pl/). Przekazywany adres REDIRECT_URI musi zgadzać się z jednym z tych zdefiniowanych w ustawieniach. 

Jeżeli Twoja aplikacja nie jest w stanie przechwycić kodu autoryzującego, możesz ewentualnie przemyśleć skorzystanie z [Device flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow).
