### ISSUE TITLE
Dodanie produktu przez api bazując na katalogu

### ISSUE THREAD

**Issue by SzymonZasada** [allegro/allegro-api#7661]
Czy jest możliwość przez API dodać ofertę podając tylko Id Katalogu allegro np 33088566-873a-4c76-90b2-ef03972f7b3b oraz cenę dostępność faktury dostawy itp. Chodzi tutaj o pominiecie nazwy, id kategorii zdjec itp(ktore sa juz zawarte w katalogu)?

**Comment by Lukasz-Zurek** [comment]
Tak, w tym celu skorzystaj z [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers). Przykład wystawienia oferty powiązanej z produktem, który istnieje w naszym Katalogu opisaliśmy [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem).
