### ISSUE TITLE
Billings datas endpoint - brak danych

### ISSUE THREAD

**Issue by BartoszWoszczak** [allegro/allegro-api#7662]
Witam,

Czy jest jakiś sposób na połączenie billingu z listem przewozowym?

Obecnie endpoint `https://developer.allegro.pl/documentation#tag/Billing` daje nam możliwość pobrania billingów, niestety nie ma w tym endpoincie danych połączonych z danymi paczki nadawczej.

W CSV generowanym z raportu billingowego, w. opisie szczegółowym mamy podany numer listy przewozowego.

Czy pracujecie lub macie w planach dodanie do tego endpointa danych (wystarczy same ID lub numer listy przewozowego) aby można było w jednym miejscu zidentyfikować o jaką paczkę chodzi? Problemem jest brak danych względem typu wpisu, troszkę to irytujące i wpisy te, prócz infomacji kwotowej, nie pozwalają zweryfikować dokładnie wpisów. Nie chciałbym tego też rozwiązywać poprzez odpytywanie 2-3 dużych endpointów by pobrać tą informację.

Obecnie mamy coś takiego:

```php
 [
    "id" => "YYYY",
    "occurredAt" => "2023-09-01T09:43:42.754Z",
    "type" => [
      "id" => "HB1",
      "name" => "Przesyłka DPD",
    ],
    "value" => [
      "amount" => "-5.99",
      "currency" => "PLN",
    ],
    "tax" => [
      "percentage" => "23.00",
    ],
    "balance" => [
      "amount" => "-115888.46",
      "currency" => "PLN",
    ],
    "order" => [
      "id" => "XXXX",
    ],
  ];
```

A przy okazji dla typów przesyłek, paczek itd. mogłoby być tak:

```php
 [
    "id" => "YYYY",
    "occurredAt" => "2023-09-01T09:43:42.754Z",
    "type" => [
      "id" => "HB1",
      "name" => "Przesyłka DPD",
    ],
    "value" => [
      "amount" => "-5.99",
      "currency" => "PLN",
    ],
    "tax" => [
      "percentage" => "23.00",
    ],
    "balance" => [
      "amount" => "-115888.46",
      "currency" => "PLN",
    ],
    "order" => [
      "id" => "XXXX",
    ],
    "shipping" => [
      "id" => "ZZZ",
      "letter" => "Numer listy przewozowego",
    ],
  ];
```

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Niestety nie mamy możliwości powiązania wpisu billingowego z numerem listu przewozowego. Możesz jedynie powiązać billing z zamówieniem (pole **“order.id”**). 

Dziękuję Tobie jednak za sugestię rozszerzenia powyższego zasobu. Dodaj ją proszę w dedykowanym miejscu, tj. [Discussions](https://github.com/allegro/allegro-api/discussions), gdzie istnieje możliwość oddawania głosów również przez innych użytkowników forum. Pomysły na rozwój naszego API przeglądamy na bieżąco.
