### ISSUE TITLE
C# Model generation best practices?

### ISSUE THREAD

**Issue by BKillisch** [allegro/allegro-api#7663]
Are there any best practices for generating c# models from the allegro REST Api swagger definition?

So far we have been using https://editor.swagger.io/, but it generates some superfluous code, uses Newtonsoft.Json (We use System.Text.Json), and also generates incorrect models for more complex classes like `SaleProductOfferResponseV1`.

Are there any better options?

**Comment by hahyes** [comment]
@BKillisch You might be interested into this project: https://github.com/OpenAPITools/openapi-generator
It is multitool for many languages similar to website you mentioned. Indeed this site generates wrong model (there is less than half of fields in model).
Try with openapi-generator, maybe it will work better somehow.
If not, honestly I have no better idea than doing it manually. Sorry.

**Comment by AureliuszBrussy** [comment]
We do not recommend any particular solution, maybe another GitHub user will give you a more specific hint.
