### ISSUE TITLE
How can I retrieve the 'Kod producenta' attribute value for a product via the API?

### ISSUE THREAD

**Issue by yangsheng8** [allegro/allegro-api#7664]
Hello, I've been using the interface https://api.allegro.pl/sale/offers to access product information. However, I've noticed that it doesn't provide the 'Kod producenta' attribute value for products. Could you please advise me on how to retrieve the 'Kod producenta' attribute value for a product through the API?

**Comment by Lukasz-Zurek** [comment]
The resource which you are trying to use is indented for checking the list of offers. If you want to check the details for specific offer - please use [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getProductOffer).

Obviously if you want to check details for a specific product, you will have to use [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts) where you can search for products in our Catalog. In response, you will receive a list of matching products along with id, name, basic parameters, etc.

**Comment by yangsheng8** [comment]
Thank you, it appears to be working.
