### ISSUE TITLE
Wymagane ubezpieczenia przy tworzeniu przesyłki poprzez API

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#7665]
Mógłbym prosić o podanie wymaganych kwot ubezpieczeń (maksymalnych oraz minimalnych oraz walut ubezpieczenia)  dla konkretnych metod wysyłki do czech? (Np odbiór w punkcie packeta)

**Comment by MartaNowaczyk** [comment]
Packeta ma limit 30 100 CZK, a DHL ma limit 50 000 PLN. Waluta zależy od serwisu (allegro.cz, allegro.pl) i przewoźnika. Packeta na kierunku PL-CZ wymaga podania ubezpieczenia i ewentualnie kwoty pobrania w CZK; DHL na kierunku PL-CZ wymaga podania kwoty ubezpieczenia w PLN, ale ewentualne pobranie następuje w CZK.
