### ISSUE TITLE
Weryfikacja dwu etapowa nie działa allegro sandbox

### ISSUE THREAD

**Issue by Vandeetta** [allegro/allegro-api#7667]
Nie mogę zarządzać moimi aplikacjami sandbox ponieważ wymagana jest weryfikacja dwuetapowa. Moje konto na głównym serwisie allegro jest już chronione dwuetapowo ale nie ważne ile razy próbuje nie dostaje sms na mój telefon. Konto nazywa się michalk123321123

**Comment by MartaNowaczyk** [comment]
Konto michalk123321123 jest z produkcji. Na sandbox nie widzę takiego konta - powinieneś zarejestrować tu oddzielne konto. Na środowisku testowym nie wysyłamy smsów i nie wymagamy dwustopniowego logowania. Jeśli masz inne konto na sandbox, podaj je proszę, to sprawdzę.

**Comment by Vandeetta** [comment]
client:106166374 takie konto wyświetla mi sie w prawym górnym rogu gdy próbuje zarządzać aplikacjami w sandboxie niestety wyświetla wtedy mi się komunikat o aktywacji konta i weryfikacji

**Comment by MartaNowaczyk** [comment]
Wybrałeś konto zwykłe - uzupełnij proszę dane (imię, nazwisko, adres - oczywiście dane fikcyjne), a następnie dokonaj testowego zakupu - konto zostanie aktywowane.

**Comment by Vandeetta** [comment]
Jak mam dokonać zakupu testowego bez ujawniania moich prawdziwych danych?

**Comment by tomsyty** [comment]
> Nie mogę zarządzać moimi aplikacjami sandbox ponieważ wymagana jest weryfikacja dwuetapowa. Moje konto na głównym serwisie allegro jest już chronione dwuetapowo ale nie ważne ile razy próbuje nie dostaje sms na mój telefon. Konto nazywa się michalk12332112

Na sandboxie jak masz włączoną weryfikację dwuetapową to wpisujesz 123456, SMSów nie wysyłają

**Comment by Vandeetta** [comment]
Nie wiem czemu ale nadal nie mogę zarządzać aplikacjami w sandboxie zrobiłem już wszystko (testowy zakup,dodanie danych,weryfikacja 2 etapowa,dodanie adresu) cały czas ten sam błąd

**Comment by MartaNowaczyk** [comment]
@Vandeetta Nadal nie było aktywne. Aktywowałam Twoje konto ręcznie, zobacz teraz.

**Comment by Vandeetta** [comment]
Teraz wgl nie mogę wejść na moje konto na sandboxie przy logowaniu prosi mnie o kod sms wklepuje cokolwiek i nie wchodzi a przecież nie dostanę sms na numer podany tam bo nie jest on prawdziwy

**Comment by tomsyty** [comment]
Nie cokolwiek tylko dokładnie 123456, to nie przykładowy kod tylko kod używany przy weryfikacji dwustopniowej na sandboxie.
