### ISSUE TITLE
Wyprowadzanie zamówień do pliku SCV

### ISSUE THREAD

**Issue by Levena007** [allegro/allegro-api#7668]
Witam,
czy istnieje możliwość wyprowadzenie zamówień do pliku CSV z panelu allegro?
Jesteśmy w trakcie integracji konta, ale na chwilę przenosimy zamówienia do naszego ERP manualnie.
Zastanawiam się nad prostym sposobem automatyzacji tego procesu poprzez transfer zamówień do czasu pełnej integracji.

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Możesz wygenerować takie zestawienie CSV w zakładce [Zestawienie sprzedaży](https://allegro.pl/moje-allegro/sprzedaz/raporty-zamowien).
