### ISSUE TITLE
payments-simulator zwraca status code 504

### ISSUE THREAD

**Issue by mbartuzi** [allegro/allegro-api#767]
Cześć,

Chciałem stworzyć kilka przykładowych aukcji na sandboxie, ale przed wystawieniem aukcji należy aktywować sprzedaż. W tym celu trzeba przejść przez proces aktywacji online przez płatność internetową. Kiedy wybieram dowolny bank jestem przekierowywany na: https://payments-simulator.allegrosandbox.pl/index/UTF/NewPayment, a następnie mam do wyboru ACCEPT albo CANCEL. W obu przypadkach podczas próby wysłania POSTa "makerequest", zwracany jest status code: 504.
Jest jakiś inny sposób na aktywowanie sprzedaży?

**Comment by PawelTaberski** [comment]
Podaj proszę swój login, sprawdzę w czym jest problem.

**Comment by mbartuzi** [comment]
Loginu chwilowo nie pamiętam i nie mogę w tej chwili sprawdzić, ale mail to: bartuzimateusz@gmail.com

**Comment by PawelTaberski** [comment]
Konto powinno być już aktywne.

**Comment by PawelTaberski** [comment]
@mbartuzi Zdarzają się potrzeby z aktywacją konta na środowisku testowym. Jeśli będziesz chciał aktywować kolejne konto i również będziesz miał jakiś problem to napisz do nas.

**Comment by DamianKomorowski** [comment]
@PawelTaberski U mnie również występuje problem z aktywacją konta. Problem po stronie symulatora płatności. Proszę o aktywacje konta Login: EuroParts

**Comment by PawelTaberski** [comment]
Konto aktywowałem już powinno być ok.

**Comment by DamianKomorowski** [comment]
Wygląda Ok dzięki.

**Comment by DamianKomorowski** [comment]
@PawelTaberski  Jednak nie jest jeszcze OK :(
Dostaje komunikat: 
Podczas wznowienia oferty wystąpiły błędy
Użytkownik z blokadą konta Firma nie może wystawiać nowych ofert.

**Comment by PawelTaberski** [comment]
Widzę, że nie masz zweryfikowanego konta firmowego, musisz rozpocząć proces weryfikacji na konto firmowe, bez tego nie mogę Tobie zatwierdzić.

**Comment by DamianKomorowski** [comment]
Własnie rozpocząłem proces weryfikacji.

**Comment by PawelTaberski** [comment]
Teraz powinno już być ok.

**Comment by DamianKomorowski** [comment]
Potwierdzam teraz jest ok dzięki za pomoc ! 👍
