### ISSUE TITLE
Allegro DPD Czechy na allegro.pl i allegro.z

### ISSUE THREAD

**Issue by ZAK2828** [allegro/allegro-api#7671]
Dzień dobry,
W programie prostapaczka muszę skonfigurować usługę Allegro DPD Czechy, widzę, że są dwie usługi pod tą nazwą, a nie wiem, która dotyczy usługi na allegro.pl a która na allegro.cz, czy mogą Państwo napisać mi która odpowiada za który kraj?

Allegro Kurier DPD Czechy - 14b73cc6-28d6-11eb-adc1-0242ac120002

Allegro Kurier DPD Czechy - 14bac5b7-4f11-4b53-9a03-0242ac120002

**Comment by MartaNowaczyk** [comment]
Eksportowe metody dostawy, które zwracamy w ramach [GET /sale/delivery-methods](https://developer.allegro.pl/documentation#operation/getListOfDeliveryMethodsUsingGET) rozróżnisz na podstawie serwisu, na który przeznaczona jest dana metoda dostawy.

Allegro Kurier DPD Czechy - 14b73cc6-28d6-11eb-adc1-0242ac120002 
```
...
"marketplaces": [
    "allegro-pl"
 ]
...
```

Allegro Kurier DPD Czechy - 14bac5b7-4f11-4b53-9a03-0242ac120002
```
...
 "marketplaces": [
     "allegro-cz"
 ]
...
```

**Comment by ZAK2828** [comment]
Dziękuję, nie posiadam dostępu do takich zasobów, korzystam tylko z tego co widzę w programie prostapaczka, a tam jest powielona nazwa i ta kombinacja, także analogiczna prośba, proszę o wskazanie którego marketplacu dotyczą te usługi jeszcze:

Allegro International Odbiór w Punkcie Czechy - 0779bdbb-2043-4ed0-aff7-b3146fe9f54a
Allegro International Odbiór w Punkcie Czechy - af0a4e4-2043-4ed0-aff7-b3146fe9f54a
Allegro International Odbiór w Punkcie Czechy pobranie - 1037d74a-2043-4ed0-aff7-b3146fe9f54a
Allegro International Automaty Paczkowe Czechy - 0bdd3bfb-32c6-4602-b78f-b3146fe9f54a
Allegro International Automaty Paczkowe Czechy - 0e40225c-32c6-4602-b78f-b3146fe9f54a
Allegro International Automaty Paczkowe Czechy pobranie - 191819e3-32c6-4602-b78f-b3146fe9f54a
Allegro International Kurier Czechy - 05621e8a-1bcc-4dad-98c4-b3146fe9f54a
Allegro International Kurier Czechy - 0c7805b4-1bcc-4dad-98c4-b3146fe9f54a
Allegro International Kurier Czechy pobranie - 1401412f-1bcc-4dad-98c4-b3146fe9f54a

**Comment by MartaNowaczyk** [comment]
To aplikacja powinna takie rzeczy udostępniać.

Allegro International Odbiór w Punkcie Czechy - 0779bdbb-2043-4ed0-aff7-b3146fe9f54a
```
"marketplaces": [
                "allegro-pl"
            ]
```
Allegro International Odbiór w Punkcie Czechy - 0af0a4e4-2043-4ed0-aff7-b3146fe9f54a
```
"marketplaces": [
                "allegro-cz"
            ]
```

Allegro International Odbiór w Punkcie Czechy pobranie - 1037d74a-2043-4ed0-aff7-b3146fe9f54a
```
"marketplaces": [
                "allegro-cz"
            ]
```

Allegro International Automaty Paczkowe Czechy - 0bdd3bfb-32c6-4602-b78f-b3146fe9f54a
```
"marketplaces": [
                "allegro-pl"
            ]
```

Allegro International Automaty Paczkowe Czechy - 0e40225c-32c6-4602-b78f-b3146fe9f54a
```
"marketplaces": [
                "allegro-cz"
            ]
```

Allegro International Automaty Paczkowe Czechy pobranie - 191819e3-32c6-4602-b78f-b3146fe9f54a
```
"marketplaces": [
                "allegro-cz"
            ]

```
Allegro International Kurier Czechy - 05621e8a-1bcc-4dad-98c4-b3146fe9f54a
```
"marketplaces": [
                "allegro-pl"
            ]
```

Allegro International Kurier Czechy - 0c7805b4-1bcc-4dad-98c4-b3146fe9f54a
```
"marketplaces": [
                "allegro-cz"
            ]
```

Allegro International Kurier Czechy pobranie - 1401412f-1bcc-4dad-98c4-b3146fe9f54a
```
"marketplaces": [
                "allegro-cz"
            ]
```
