### ISSUE TITLE
Zaznaczanie w ofercie pól dla usług posprzedażowych REST API

### ISSUE THREAD

**Issue by zymod** [allegro/allegro-api#7672]
Witam. Mam problem z aktualizacją pól oferty, a dokładniej z "afterSalesServices".
Chodzi mi dokładnie o te pola => 
{'impliedWarranty': None, 'returnPolicy': None, 'warranty': None}

Udalo mi się wyciągnąć odpowiednie idendyfikatory poprzez zasoby:

"https://api.allegro.pl/after-sales-service-conditions/return-policies/"
"https://api.allegro.pl/after-sales-service-conditions/implied-warranties/"
"https://api.allegro.pl/after-sales-service-conditions/warranties/"

Gdy otrzymane idendyfikatory podmieniam za wartości None, a następnie przesyłam nowe dane za pomocą PUT zmiany nie następują. Czy aby wysłać te dane potrzeba skorzystać z jakiegoś specjalnego zasobu?
Czytając dokumentacje natknąłem się jedynie na wyjaśnienie jak zmienić usługi posprzedażowe dla konta ale jak zaciągnąć je do oferty?

Dziękuję za wyjaśnienie,
Pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
Najprostszym rozwiązaniem jest skorzystanie z [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) i przekazanie właściwego identyfikatora lub nazwy danych warunków zwrotów, reklamacji i gwarancji, np.:
```
{
	"afterSalesServices": {
		"returnPolicy": {
			"id": "8646fdcc-efc8-4ff6-93c8-728a02e4964e"
		}
	}
}
```

Więcej informacji znajdziesz także w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#warunki-reklamacji-i-zwrotow).

**Comment by zymod** [comment]
Okej udało się dzięki.
