### ISSUE TITLE
The standard issuing interface reported an error, indicating that the tracking number is invalid

### ISSUE THREAD

**Issue by VEVOR** [allegro/allegro-api#7673]
POST https://api.allegro.pl/order/checkout-forms/186a2000-5c3e-11ee-86ae-05f75ee9e602/shipments
req：{"carrierId":"DPD","waybill":"250095804610596704"}
resp：{"responseContent":"{\"errors\":[{\"code\":\"CarrierWaybillValidationException\",\"message\":\"Provided waybill is not valid for this carrier\",\"details\":null,\"path\":null,\"userMessage\":\"Wystąpił błąd. Ten numer przesyłki jest niepoprawny dla tego przewoźnika. Nie udało się zapisać zmian. Spróbuj ponownie.\"}]}","statusCode":400}
Tracking number query address：https://t.17track.net/zh-cn#nums=250095804610596704
![image](https://github.com/allegro/allegro-api/assets/99702013/32a225cc-4e4b-477c-bf9a-1bc47501db11)

**Comment by VEVOR** [comment]
English address：https://t.17track.net/en#nums=250095804610596704
![image](https://github.com/allegro/allegro-api/assets/99702013/efa0e365-c475-4101-a664-eea6e2fb56d1)

**Comment by MaciejFrackowiak** [comment]
This is not a valid number for the Polish department of DPD - so as a result you received a correct response. You should use POST /order/checkout-forms/{id}/shipments with carrierId=OTHER and add its name in the field "carrierName".
