### ISSUE TITLE
400 /shipment-management/shipments/create-commands 

### ISSUE THREAD

**Issue by EmilooD** [allegro/allegro-api#7674]
Witam,

wskazany przykład w dokumentacji:
`{
"commandId": "14e142cf-e8e0-48cc-bcf6-399b5fd90b32",
"input": {
"deliveryMethodId": "c3066682-97a3-42fe-9eb5-3beeccab840c",
"credentialsId": "c9e6f40a-3d25-48fc-838c-055ceb1c5bc0",
"sender": {
"name": "Jan Kowalski",
"company": "Allegro.pl sp. z o.o.",
"street": "Główna",
"streetNumber": 30,
"postalCode": "10-200",
"city": "Warszawa",
"state": "AL",
"countryCode": "PL",
"email": "email@mail.com",
"phone": 500600700,
"point": "A1234567"
},
"receiver": {
"name": "Jan Kowalski",
"company": "Allegro.pl sp. z o.o.",
"street": "Główna",
"streetNumber": 30,
"postalCode": "10-200",
"city": "Warszawa",
"state": "AL",
"countryCode": "PL",
"email": "email@mail.com",
"phone": 500600700,
"point": "A1234567"
},
"pickup": {
"name": "Jan Kowalski",
"company": "Allegro.pl sp. z o.o.",
"street": "Główna",
"streetNumber": 30,
"postalCode": "10-200",
"city": "Warszawa",
"state": "AL",
"countryCode": "PL",
"email": "email@mail.com",
"phone": 500600700,
"point": "A1234567"
},
"referenceNumber": "abcd1234",
"description": "Car wheels",
"packages": [
{
"type": "string",
"length": {
"value": "12",
"unit": "CENTIMETER"
},
"width": {
"value": "12",
"unit": "CENTIMETER"
},
"height": {
"value": "12",
"unit": "CENTIMETER"
},
"weight": {
"value": "12.45",
"unit": "KILOGRAMS"
}
}
],
"insurance": {
"amount": "23.47",
"currency": "PLN"
},
"cashOnDelivery": {
"amount": "2.50",
"currency": "PLN",
"ownerName": "Jan Kowalski",
"iban": "PL48109024022441789739167589"
},
"labelFormat": "PDF",
"additionalServices": [
"ADDITIONAL_HANDLING"
]
}
}`

Zwraca błąd 400:
`HTTP/1.1 400 Bad Request
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1 ; mode=block
pragma: no-cache
referrer-policy: no-referrer
date: Tue, 26 Sep 2023 10:46:39 GMT
strict-transport-security: max-age=31536000 ; includeSubDomains
x-frame-options: DENY
trace-id: b931a06a1ebb0a0d
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json
content-length: 133

{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"command","userMessage":"An error has occurred"}]}`

Czy na coś szczególnego należy zwrócić uwagę? 
Pozdrawiam
Emil

**Comment by AureliuszBrussy** [comment]
Z naszych logów wynika, że request został wysłany z pustym payload'em. Sprawdź, czy na pewno wysyłasz dane.

**Comment by EmilooD** [comment]
A trace-id: c99dce524b428adf?

**Comment by AureliuszBrussy** [comment]
Widzę błąd w w tablicy **packages[]** - w "**unit**" przekazujesz CENTIMITER, a powinieneś CENTIMETER.

**Comment by EmilooD** [comment]
Dzięki, faktycznie. Czyli ten błąd "Error occured" może oznaczać wszystko łącznie z błędem danych?
Nowy trace-id: 2bfefb4c5d32af66 (jeśli możemy tak możemy działać)

**Comment by AureliuszBrussy** [comment]
@EmilooD wyjaśniam to z odpowiednim zespołem. Wrócę z odpowiedzią.
