### ISSUE TITLE
Problem ze wznowieniem ogłoszenia poprzez parametr republish

### ISSUE THREAD

**Issue by Hornir91** [allegro/allegro-api#7676]
Dzień dobry.

Mam problem ze wznowieniem ogłoszenia na Allegro o id: 14212668496.

Pomimo zaznaczenia w nim poprzez API parametru republish, ogłoszenie wygasło. Mógłbym dowiedzieć się dlaczego nie zostało wznowione? Z góry dziękuję za odpowiedź.

Pozdrawiam.

**Comment by MartaNowaczyk** [comment]
Sprawdziliśmy i błąd był po naszej stronie, za co najmocniej przepraszamy. Będziemy prowadzić prace, aby wyeliminować takie przypadki w przyszłości. Proszę aktywować to ogłoszenie ponownie. Przepraszamy za niedogodności.`

**Comment by Hornir91** [comment]
Dobrze. Dziękuję za informację.
