### ISSUE TITLE
Wymagana autoryzacja aplikacji

### ISSUE THREAD

**Issue by maciek-lvl** [allegro/allegro-api#7677]
Dzień dobry
mamy problem z podłączeniem aplikacji do pobierania statystyk kampanii reklamowych do jednego z naszych kont

Próbujemy się odbić metodą GET do https://api.allegro.pl/advertising-agencies/clients i otrzymujemy status 403 FORBIDDED.

Trace ID: 46504a6487ab5000
Response Body:
{
    "errors": [
        {
            "code": "FORBIDDEN",
            "message": "Access is forbidden",
            "details": null,
            "path": "/advertising-agencies/clients",
            "userMessage": "Access is forbidden"
        }
    ]
}

Aplikacja jest poprawnie dodana do panelu, działa też bezproblemowo w przypadku innego konta agencyjnego.
W jaki sposób możemy "autoryzować" aplikację?

**Comment by MartaNowaczyk** [comment]
Prowadzimy tutaj wsparcie tylko dla zasobów publicznego API zawartych w [dokumentacji](https://developer.allegro.pl/documentation), dlatego w tej sprawie proszę o kontakt przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
