### ISSUE TITLE
Inny numer nadania niż kod kreskowy na etykiecie

### ISSUE THREAD

**Issue by babikm** [allegro/allegro-api#7678]
Witam,
Problem dotyczy przesyłek Allegro Kurier UPS, Allegro One Box (UPS).
Numer nadania przesyłki generowany przez Allegro (Axxxx) jest inny niż ten który znajduję się w kodzie kreskowym na etykiecie. 
Czy jest opcja aby przez API wyciągnąć faktyczny numer paczki? Jest to problematyczne podczas skanowania etykiet w BL.

**Comment by MartaNowaczyk** [comment]
Aktualnie nie ma takiej możliwości.
