### ISSUE TITLE
REST Api dodanie numeru przesyłki

### ISSUE THREAD

**Issue by Draken79** [allegro/allegro-api#768]
W jaki sposób w REST Api można dodać numer przesyłki do zamówienia? W dokumentacji nie znalazłem takiej metody. Dziękuję.

**Comment by PawelTaberski** [comment]
Chwilowo nie ma takiej możliwości przez REST API, jak wdrożymy taki zasób to poinformujemy o tym. Obecnie możesz dodać numer przesyłki przez WebAPI metodą [doAddPackageInfoToPostBuyForm](https://allegro.pl/webapi/documentation.php/show/id,744).

**Comment by Draken79** [comment]
Dziękuję za odpowiedź, miałem nadzieję, że można bez problemu migrować na REST API, odtwarzając wszystkie funkcjonalności z WEB API. Rozumiem, że na dzień dzisiejszy nie jest to możliwe, ale docelowo tak właśnie będzie?

**Comment by PawelTaberski** [comment]
Tak stopniowo zwiększamy liczbę dostępnych zasobów w REST API, zdajemy sobie sprawę, że jeszcze wielu brakuje.

**Comment by Draken79** [comment]
No tak, tylko żeby dodać numer przesyłki przez WebAPI potrzebny jest id_transakcji w formacie 9 cyfrowym. Czy takie id, można uzyskać z któregoś zasobu REST Api?

**Comment by PawelTaberski** [comment]
Obecnie nie ma możliwości przez REST API pobrania numeru w takim formacie. Aby otrzymać taki numer musisz skorzystać z zasobu [DoGetPostBuyFormsIds](https://allegro.pl/webapi/documentation.php/show/id,1362) w WebAPI.

**Comment by Draken79** [comment]
To wiem, bo korzystam z WebAPI. 
W takim przypadku przejście na REST API nie jest w ogóle możliwe, a przyznam, że niepokoją mnie wiadomości o wyłączaniu kolejnych metod w WebAPI.

**Comment by Draken79** [comment]
No ale co mi z tego, że w Web API zostanie metoda dodawania numeru przesyłki skoro metoda pobierania id potrzebnego do dodania numeru przesyłki zostanie wyłączona. A metoda odpowiadająca jej w REST API działa na innych id niż są potrzebne do dodania przesyłki w Web API. Mam nadzieje, że macie świadomość, że z przyczyn oczywistych nie można dopuścić do takiej sytuacji.

**Comment by PawelTaberski** [comment]
Tak wiemy o tym i na pewno nie wyłączymy metod, które są niezbędne do prawidłowej obsługi, a nie mają swoich odpowiedników w REST API.

**Comment by mack3d** [comment]
Wykorzystałem mapowanie dealId aby uzyskać transactionId.
Trochę jest roboty ale da się 👍

**Comment by Draken79** [comment]
mack3d - a możesz zdradzić jak to zrobiłeś. Mi cały czas zwraca błąd

{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":null,"userMessage":null}]}

używam tego kodu php:

$process = curl_init('https://api.allegro.pl/order/line-item-id-mappings?lineItemId=xxxxxxx');
	curl_setopt($process, CURLOPT_HTTPHEADER, $headers);
	curl_setopt($process, CURLOPT_TIMEOUT, 30);
	curl_setopt($process, CURLOPT_RETURNTRANSFER, TRUE);
	$return = curl_exec($process);
	curl_close($process);
	//$checkout_forms = json_decode($return);
	print_r ($return);

Dzięki!

**Comment by mack3d** [comment]
@Draken79 czy aby na pewno mapuj są dobry UUID?
Chodzi o numer deal-a a nie numer fod-a👍

**Comment by mack3d** [comment]
function getRequest($uri, array $params = []) {
    $headers = ['Accept:
application/vnd.allegro.beta.v1+json','Authorization: Bearer
'.'token','Api-Key: ########'];
    $curl = curl_init($uri);
    curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'GET');
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    $data = json_encode($params);
    curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
    return curl_exec($curl);
}

$mapowanie = getRequest('
https://api.allegro.pl/order/line-item-id-mappings?lineItemId='.$fod-
>lineItems[0]->id);
$map_id = json_decode($mapowanie)->mappings[0]->dealId;

wt., 6 lis 2018 o 09:56 Draken79 <notifications@github.com> napisał(a):

**Comment by coobitus** [comment]
@mack3d dealId to nie jest to samo co transactionId ... dealId to jest identyfikator POZYCJI (produktu) w transakcji, a tymczasem do przekazania numeru paczki potrzebny jest identyfikator samej transakcji ... Z tego mapowania, które jest w REST API nie da się wyciągnąć prawidłowego numeru transakcji niestety ...

**Comment by mack3d** [comment]
@coobitus tak, wiem ale ja to wykorzystałem żeby zdobyć transactionId bo przecież dealId posiada transactionId.
Można? Można!😊

**Comment by coobitus** [comment]
@mack3d a w jaki sposób to zrobiłeś? bo w powyższym kodzie tego nie ma - tam tylko wyciągasz dealId? Więc co masz na myśli mówiąc że "dealId posiada transactionId"?

**Comment by mack3d** [comment]
_dealId_ występuje w **Webapi** w zasobie _doGetSiteJournalDeals_

W tym samym zasobie występuje również transactionId dla danego _dealId_ którego _dealEventType_<>0

**Comment by coobitus** [comment]
@mack3d a czy przypadkiem nie jest tak, że dany dealId może być obsłużony w trakcie swojego "życia" przez kilka różnych transactionId? Bo zdaje się, że w WebAPI jak się coś zmieni w zamówieniu, to oni generują nowy numer transakcji?

**Comment by mack3d** [comment]
Masz racje dlatego ja sprawdzam tylko dla _FOD_ które mają status READY_FOR_... i wyszukuje dla nich najnowszy _transactionId_ gdzie _dealEventType_ == (2,4)
Wiem że nie jest to doskonałe ale przez ok miesiąc działania nie zdarzyło się pomylić.
