### ISSUE TITLE
Jak dodać przewoźnika GLS poprzez API

### ISSUE THREAD

**Issue by saturi-cz** [allegro/allegro-api#7680]
Dobry dzień,

proszę o pomoc w dodaniu własnej umowy przewoźnika na allegro.cz
Niestety czeskie wsparcie odnosi się tylko do GitHuba i samo w sobie nie zna odpowiedzi.

W ustawieniach zamówienia znajduje się sekcja Umowa własna - transport Allegro. Pojawią się pola. Wybieram GLS i co dalej?
Nazwa umowy – czy jest to numer umowy z przewoźnikiem, czy nazwa firmy, która zawarła umowę?
Dane uwierzytelniające API - czy są tożsame z logowaniem do strefy klienta MyGLS? czy Allegro korzysta ze starszej wersji GLS online?

Z góry bardzo dziękuję za pomoc.
Z poważaniem, saturi_cz
Saturi Moda s.r.o.

**Comment by MartaNowaczyk** [comment]
Dzień dobry,

na tym forum zajmujemy się API Allegro, a Twoje pytanie wykracza poza te tematy, dlatego najlepiej jak skorzystasz z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda). 
W [pomocy allegro](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/wysylam-z-allegro-narzedzie-do-nadawania-przesylek-bezposrednio-z-konta-E7doGw8VgI1#jak-dodac-umowe-wlasna-w-wysylam-z-allegro) znalazłam informacje:

> wpisz nazwę umowy – wyświetlimy Ci ją podczas wyboru przewoźnika, gdy będziesz nadawać przesyłkę. Poniżej podaj dane, jakimi logujesz się do narzędzia nadawczego tego przewoźnika.

Czyli wygląda na to, że nazwa umowy jest dowolna.
