### ISSUE TITLE
Problem z Device flow

### ISSUE THREAD

**Issue by Vandeetta** [allegro/allegro-api#7681]
Używam skryptu w pythonie aby wywolywać requesty i nie ważne co robię przy próbie weryfikacji tą metodą otrzymuję komunikat 
Request failed with status code 400
{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/auth/oauth/device","userMessage":null}]}

Funkcja której używam wygląda tak

  ````
def deviceFlowAuth(client_id, client_secret):
      url = "https://allegro.pl.allegrosandbox.pl/auth/oauth/device"
      headers = {
          "Authorization": "Basic " + base64.b64encode(f"{client_id}:{client_secret}".encode()).decode(),
          "Content-Type": "application/x-www-form-urlencoded"
      }
      response = requests.post(url, headers=headers)
  
      if response.status_code == 200:
          print("Request was successful")
          return response.json()  
      else:
          print(f"Request failed with status code {response.status_code}")
          print(response.text)  
          return None

**Comment by MartaNowaczyk** [comment]
Z uwagi na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich, jednak z tego co widzę nie podajesz parametru client_id - `url = (f"https://allegro.pl.allegrosandbox.pl/auth/oauth/device?client_id={client_id}")`.

**Comment by Vandeetta** [comment]
Bardzo dziękuję za pomoc
