### ISSUE TITLE
Pobranie etykiety błąd content-type

### ISSUE THREAD

**Issue by Adrian-baw** [allegro/allegro-api#7682]
Korzystam z przykładu:
https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-etykiete-na-paczke

array:3 [▼
  0 => "Authorization: Bearer <CENZURA>"
  1 => "accept: application/octet-stream"
  2 => "Content-Type: application/vnd.allegro.public.v1+json"
]

Parametry:
"{"shipmentIds":["b221c627-493a-4ff5-b0e4-3d294a7bcfae"],"pageSize":"A6"}"

Adres: https://api.allegro.pl/shipment-management/label

Odpowiedź zwrotna którą otrzymuję: "Unsupported content type. Please check 'Content-Type' request header"

Dane próbuję wywołać curlem w php, testowałem również ręczne wywołanie przez requester i wynik jest ten sam.

Pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swojego wywołania.

**Comment by Adrian-baw** [comment]
6e677b23a989ca84

**Comment by MaciejFrackowiak** [comment]
Dziękuję za dane. Weryfikuję sprawę z zespołem, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Dokonaliśmy drobnej zmiany w konfiguracji usługi, obecnie problem nie powinien już występować.
