### ISSUE TITLE
Brak publication.endedAt

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#7683]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment

Gdzie się podziało `publication.endedAt` w `/sale/offers` czy `/sale/product-offers`?

**Comment by MaciejFrackowiak** [comment]
Pole publication.endedAt dostępne jest tylko w zasobie [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET).

**Comment by TimothyKoval** [comment]
Dlaczego? Skąd mam wiedzieć, czy mogę wznowić daną ofertę? Mam najpierw pobrać wszystkie oferty żeby wyłuskać tę jedną?
