### ISSUE TITLE
Problem NotFound shipments/create-commands sandbox

### ISSUE THREAD

**Issue by Electronc** [allegro/allegro-api#7684]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X] inny / other

:beetle: **Opis / Description**
Przy wywoływaniu zasobu https://api.allegro.pl.allegrosandbox.pl/shipments/create-commands dostaję zwrotkę "Not Found", pomimo poprawnej zwrotki 200 dla requesta do utworzenia paczki.

Request
`https://api.allegro.pl.allegrosandbox.pl/shipments/create-commands/0CFFCC6F-DC13-40FB-BB07-5EAE72798E01`

Zwrotka
`{
    "errors": [
        {
            "code": "NotFoundException",
            "message": "Not found",
            "details": null,
            "path": null,
            "userMessage": "Funkcja niedostÄ™pna. Skontaktuj siÄ™ z autorem aplikacji."
        }
    ]
}`

**Comment by MaciejFrackowiak** [comment]
Prawidłowa ścieżka zasobu to /shipment-management/shipments/create-commands - sprawdź proszę w swoim wywołaniu.

**Comment by Electronc** [comment]
Dziękuję. Zapadnę się pod ziemie : - (
Po poprawnej ścieżce dostałem:
`{
    "commandId": "1281D572-5E79-4C3B-9A29-B5FFC7262A1A",
    "status": "ERROR",
    "errors": [
        {
            "code": "PROCESSING_ERROR",
            "message": "Problem with dispatch. Contact us, and we will help as soon as possible.",
            "details": null,
            "path": null,
            "userMessage": "Problem z nadaniem przesyĹ‚ki. Skontaktuj siÄ™ z nami. PomoĹĽemy jak najszybciej."
        }
    ],
    "shipmentId": null
}`

**Comment by MaciejFrackowiak** [comment]
Wyjaśniam z zespołem co spowodowało błąd, wrócę z odpowiedzią.

**Comment by Electronc** [comment]
@MaciejFrackowiak Wiadomo coś? Wychodzi na to, że ten błąd występuje dla każdej metody dostawy na sandboxie, przynajmniej dla mojego konta.

**Comment by MaciejFrackowiak** [comment]
Problemem w tym przypadku był numer telefonu odbiorcy - jest zapisany w nieprawidłowym formacie. Z naszej strony dopracujemy komunikat błędu by jednoznacznie mówił o powodzie błędu.

**Comment by Electronc** [comment]
> Problemem w tym przypadku był numer telefonu odbiorcy - jest zapisany w nieprawidłowym formacie. Z naszej strony dopracujemy komunikat błędu by jednoznacznie mówił o powodzie błędu.

Numer poprawiłem na ten z dokumentacji. Dalej ten wyskakuje ten błąd. Są jakieś wytyczne co do formatu danych wrażliwych dla paczek?
W środowisku produkcyjnym, też brakuje zwrotek z typem błędu Validation?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id dla poprawionego numeru telefonu. Środowisko produkcyjne z reguły ma dokładniejszą walidację i komunikaty, jednak może się zdarzyć, że również nie będzie to dokładny komunikat.

**Comment by Electronc** [comment]
> Proszę podaj trace-id dla poprawionego numeru telefonu. Środowisko produkcyjne z reguły ma dokładniejszą walidację i komunikaty, jednak może się zdarzyć, że również nie będzie to dokładny komunikat.
`
f0f2b637-eafe-44c5-ae32-28af7274a615`

**Comment by Electronc** [comment]
> Proszę podaj trace-id dla poprawionego numeru telefonu. Środowisko produkcyjne z reguły ma dokładniejszą walidację i komunikaty, jednak może się zdarzyć, że również nie będzie to dokładny komunikat.

Przepraszam za zamieszanie.
UUID
`4d6b55c2-2b8b-46f9-9680-d7320aea6427`

**Comment by Electronc** [comment]
> > Proszę podaj trace-id dla poprawionego numeru telefonu. Środowisko produkcyjne z reguły ma dokładniejszą walidację i komunikaty, jednak może się zdarzyć, że również nie będzie to dokładny komunikat.
> 
> Przepraszam za zamieszanie. UUID `4d6b55c2-2b8b-46f9-9680-d7320aea6427`

Znalazłem błąd. Nie zgadzał się ID metody dostawy.
Dziękuję z góry za pomoc

**Comment by MaciejFrackowiak** [comment]
Cieszę się, iż udało się namierzyć błąd.
