### ISSUE TITLE
Uzyskanie oryginalnego numeru listu przewozowego przewoźnika UPS

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#7685]
Dzień Dobry,

Czy jest możliwość aby poprzez API allegro tworząc przesyłkę za pomocą /parcel-management/parcel-create-commands/{commandId} następnie uzyskać numer listu przewozowego który oryginalnie nadaje UPS w przypadku przesyłek allegro one?

**Comment by AureliuszBrussy** [comment]
Nie, nie ma takiej możliwości, w przypadku Allegro One zwracamy tylko waybill Allegro One.
