### ISSUE TITLE
[Problem] /points-of-service zwraca inną ilość niż jest widoczne na mapie

### ISSUE THREAD

**Issue by grz33gorz** [allegro/allegro-api#7686]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Podczas wyboru punktu odbioru w checkout przez klienta, widnieje niepoprawna liczba punktów w stosunku do realnie występujących. Np. miejscowość RUMIA:

![image](https://github.com/allegro/allegro-api/assets/18413736/abd9b035-ed71-4155-acbc-d7fb50f76e71)

Pobranie danych poprzez /points-of-service zwraca nam poprawną listę/ilość - przez co nie jest to kwestia duplikatów punktów.

Debug przez konsole sugeruje, że te punkty są wielokrotnie nałożone po prostu na mapę.

![image](https://github.com/allegro/allegro-api/assets/18413736/d22ce804-d9ed-4355-b8e2-76935802f0e3)

ID punktu, który ma duplikacje: 906BFE99-FF22-452E-8F41-DFAA827A5FE6

**Comment by AureliuszBrussy** [comment]
Dziękuję za zwrócenie uwagi. Zgłosiłem to do zespołu odpowiedzialnego za usługę.

**Comment by grz33gorz** [comment]
@AureliuszBrussy 

![image](https://github.com/allegro/allegro-api/assets/18413736/982a7a58-222d-4384-a684-262d5e443e4a)

4386913F-7D66-494C-93B5-870C063C8CFE
punkt: Punkt odbioru Inter Cars S.A. - FILIA RUMIA
ul. Grunwaldzka 35
84-230 Rumia

**Comment by AureliuszBrussy** [comment]
Czy mógłbyś jeszcze podać przykładowe trace-id wywołania tego użytkownika pod /points-of-service? Trace-id znajdziesz w nagłówku naszego response'a.

**Comment by grz33gorz** [comment]
@AureliuszBrussy - zsynchronizowałem jeszcze raz punkty (zmieniły się id), ale efekt ten sam.

- trace-id: 23a1dfb676245753
- date: Thu, 28 Sep 2023 07:45:34 GMT

zwraca mi 1 punkt w miejscowość RUMIA

- [id] => ae292366-565e-11ee-84d3-867ed689f6f8
- [name] => FILIA RUMIA

chociaż w DEBUG consolowym aktualnie ID Rumii describedby="6261D294-074C-4A6D-A68C-60DF06A95799" - nie wiem czy to odnosi się do siebie.

**Comment by AureliuszBrussy** [comment]
Dziękuję, wystarczą mi te dane. Jeszcze to analizujemy. Wrócę do Ciebie z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Wdrożyliśmy poprawkę, aktualnie pokazywana liczba powinna być prawidłowa.
