### ISSUE TITLE
Wystawianie oferty z przykładu zwraca mi błąd

### ISSUE THREAD

**Issue by Vandeetta** [allegro/allegro-api#7687]
tak wygląda mój json 
  data = {
  "productSet": [{
    "product": {
      "id": "5902719471797",
      "idType": "GTIN"
    }}],
    "sellingMode": {
      "price": {
        "amount": "220.85",
        "currency": "PLN"
      }
    },
    "stock": {
      "available": 10
    },
     "publication": {
      "status": "INACTIVE"
    }
  }

Request failed with status code 422. Response:
{"errors":[{"code":"MatchingProductNotFoundException","message":"Unprocessable Entity","details":null,"path":"productSet[0].product","userMessage":"Matching product not found for the given ID. The data necessary to create the offer and/or to propose the product was not provided."}]}

**Comment by MartaNowaczyk** [comment]
Widzę, że taki produkt istnieje, także komunikat wygląda na nieodpowiedni. Czy możesz podesłać trace-id, żebym mogła sprawdzić jak Twój request wygląda u nas w logach?

**Comment by Vandeetta** [comment]
58d56430cb3be01b trace id mojego ostatniego requesta

**Comment by MartaNowaczyk** [comment]
Dzięki za trace-id. Dzięki temu wiem, że request był wykonany na środowisku testowym sandbox, a tam w bazie nie mamy takiego produktu, stąd komunikat jest poprawny. W takim wypadku spróbuj [utworzyć nowy produkt](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-utworzyc-nowy-produkt) lub [wystaw ofertę z nowym produktem](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-nowym-produktem).

**Comment by Vandeetta** [comment]
Napotkałem się na podobny problem podczas wystawiania oferty z nowym produktem Trace id 59b5ed12446956bd

Request failed with status code 422. Response:
{"errors":[{"code":"MatchingProductNotFoundException","message":"Unprocessable Entity","details":null,"path":"productSet[0].product","userMessage":"Matching product not found for the given ID. The data necessary to create the offer and/or to propose the product was not provided."}]}
