### ISSUE TITLE
Question about category structure

### ISSUE THREAD

**Issue by DenisScript** [allegro/allegro-api#7688]
Good afternoon.
We have the following question: has the directory structure changed in the last six months/year? Last fall we integrated and added products using the API; now we decided to add some items, but we encountered a lot of errors, for example:

Parametr 245669 nie istnieje.
A product from our database has been recognized based on the specified data. The indicated category `Książki i Komiksy` (91465) does not match the product category: `Książki i Komiksy` (7).

We understand that the structure has changed and ID categories?

**Comment by MaciejFrackowiak** [comment]
Yes, our categories and parameters structure is constantly changing. You should retrieve it on a regular basis.

**Comment by DenisScript** [comment]
Good afternoon. 
We changed our application, unloaded almost all the goods, but there are questions about some:
1. Some of our products have names shorter than 12 characters, so we receive the corresponding error when adding them. How can this be avoided? Is it possible to add, for example, the author to the product name?
2. The category is not defined correctly, we add a book, and we are offered a category with costumes - "The provided category `Literatura piękna` (79153) does not match the existing product category `Kostiumy dla chłopców` (88318)"
3. There are still errors "Invalid GTIN: 245669 - 97854481131161", can they be somehow circumvented?

**Comment by DenisScript** [comment]
Good morning.
If we send a request to /sale/products/{productId}/change-proposals, will these changes take effect immediately, or will there be some kind of moderation?

**Comment by DenisScript** [comment]
And there is another problem - when adding a product, the error "ProductDuplicate" is returned. But when we try to find this product using the request https://api.allegro.pl/sale/products?phrase=9785041814403&mode=GTIN, an empty array is returned to us in the “products” parameter. This is not for all products, but only for some. With what it can be connected?

**Comment by MaciejFrackowiak** [comment]
There will be manual moderation. If you add "notifyViaEmailAfterVerification" with a value "true" to your request, you will receive an email with the verification status.
We recognize duplicates based on GTIN and other product parameters.

**Comment by DenisScript** [comment]
How can we find out the ID of a duplicate product?

**Comment by MaciejFrackowiak** [comment]
In the response to [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/getSaleProduct) we return product.id in the location header.

**Comment by DenisScript** [comment]
What should we do with Invalid GTIN errors? We are adding a new product (there is no duplicate in the ID headers); accordingly, we cannot offer changes.

**Comment by MaciejFrackowiak** [comment]
Please, give me an example trace-id of your request.

**Comment by MaciejFrackowiak** [comment]
It looks like that is not a valid ISBN, so as a result, you received error 422.
