### ISSUE TITLE
Time-out zapytań

### ISSUE THREAD

**Issue by DLibers** [allegro/allegro-api#7689]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

URL: GET https://api.allegro.pl/after-sales-service-conditions/implied-warranties

RESPONSE: 
```
<html><body><h1>408 Request Time-out</h1>
Your browser didn't send a complete request in time.
</body></html>
```

trace-id: nie zwraca
przykładowe trace-id zapytania, które przeszło poprawnie: acd61366b080c20

Mamy pod nasz skrypt podpięte wiele kont allegro i tydzień temu na jednym zaczęły pojawiać się takie błędy. Poprosiliśmy klienta o ponowną autoryzację OAuth i problem zniknął. Po kilku dniach pojawił się na innym koncie i ponowienie zabiegu znowu pomogło. Jednak w ciągu jednego tygodnia trzecie konto również zaczęło mieć ten problem. Błąd pojawia się często (ale nie zawsze) i psuje działanie całego kodu. Proszę o pomoc :)

**Comment by MaciejFrackowiak** [comment]
Czy obecnie problem dotyka konta, na którym przeszło poprawne wywołanie z trace-id=acd61366b080c20?

**Comment by DLibers** [comment]
Tak, mogę jeszcze dodać, że same błędne zapytania faktycznie trwają ponad minutę. Wszystkie zapytania na wszystkich podpiętych kontach są wysyłane z jednego ip

**Comment by MaciejFrackowiak** [comment]
Przejrzeliśmy posiadane przez nas dane i metryki dla wskazanego użytkownika - w ciągu ostatnich 7 dni zawsze zwracaliśmy status 200 dla requestów. Nie mamy żadnych śladów po wspomnianych przez Ciebie błędach.

**Comment by DLibers** [comment]
Znalazłem takie zapytanie trace-id: 7f1dd57057a43a95, które co prawda jest poprawne, ale czas odpowiedzi trwał 57 sekund. Czy też widzicie u siebie taki czas? Co może być przyczyną tego?

**Comment by MaciejFrackowiak** [comment]
Powyższy przypadek można uznać za incydentalny - zwyczajowo odpowiedzi dla GET /sale/offers/{offerId} są niemal natychmiastowe. W logach usługi nie zanotowaliśmy żadnych niepokojących timeoutów.
