### ISSUE TITLE
Metoda /order/event-stats i /order/events?from

### ISSUE THREAD

**Issue by Draken79** [allegro/allegro-api#769]
Pobieram id ostatniego eventu metodą /order/events-stats. Następnie wykorzystuje pobrane id w metodzie /order/events?from={pobrane_id) i dostaje pustą tablicę. 
Okazuje się, że metoda /order/events?from zwraca eventy nowsze od zadanego w parametrze from. Czy nie powinna zwracać starszych?? Proszę o komentarz. Dziękuję

**Comment by PawelTaberski** [comment]
Tak zgadza się tez zasób jest posortowany od najstarszych. Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/orders/#02).

**Comment by Draken79** [comment]
Hm.. sądziłem, że zasób /order/events-stats wraz z zasobem /order/events?from to prosty sposób aby pobrać 100 ostatnich zdarzeń. Nie bardzo zatem rozumiem do czego miałby się przydać id ostatniego zdarzenia pobrane z zasobu /order/events-stats

**Comment by Draken79** [comment]
To jeszcze jedno pytanie, po jakiej wartości jest sortowany zasób order/checkout-forms? 
Napewno nie po dacie i przyznam szczerze nie bardzo mogę dojść po czym..

**Comment by PawelTaberski** [comment]
Nie wiem czy dobrze rozumiem Twoje pytanie. Zasób jest posortowany po dacie zakupu. Ale jeśli pytasz o to w jaki sposób możesz go sortować to możesz skorzystać z offset-u bądź daty zamówienia. Więcej na ten temat [tutaj](https://developer.allegro.pl/orders/#02).

**Comment by Draken79** [comment]
Niestety nie jest posortowany po dacie zakupu. Przy użyciu tego kodu w php:

$process = curl_init('https://api.allegro.pl/order/checkout-forms');
	curl_setopt($process, CURLOPT_HTTPHEADER, $headers);
	curl_setopt($process, CURLOPT_TIMEOUT, 30);
	curl_setopt($process, CURLOPT_RETURNTRANSFER, TRUE);
	$return = curl_exec($process);
	curl_close($process);
	//$dane = json_decode($return);
	print_r ($return);

zwraca dane posortowane 'randomowo':

"boughtAt":"2018-10-15T13:06:08.914Z"
"boughtAt":"2018-10-02T15:24:36.317Z"
"boughtAt":"2018-10-10T20:46:02.815Z"
"boughtAt":"2018-10-16T19:56:36.904Z"
"boughtAt":"2018-10-16T11:37:29.971Z"
"boughtAt":"2018-10-16T11:37:28.986Z"
"boughtAt":"2018-10-12T23:08:01.447Z"
"boughtAt":"2018-10-12T23:08:01.375Z"

itd

**Comment by PawelTaberski** [comment]
Wygląda to na błąd podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) id konta na którym występuje ten problem i pełnego cURL-a i responsa z tymi danymi. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz proszę, ze dane przesyłasz na potrzeby zgłoszenia na GitHub numer 769.

**Comment by PawelTaberski** [comment]
Teraz rozumiem co miał Pan na myśli bardziej chodziło o to, aby traktować to jako punkty odniesienia do pobierania kolejnych paczek, aby nic nie umknęło. Bo w takim wypadku jak Pan to odczytuje to nie jest to pomocne. Jedynie jest Pan pewny, że po tym zdarzeniu nic nowego jeszcze się nie pojawiło, jeśli wywołanie poszczególnych zasobów następuje w dłuższych odstępach czasowych. Postaramy się to inaczej sformułować, dziękujemy za zwrócenie uwagi.

**Comment by PawelTaberski** [comment]
@Draken79 Dostałem informacie, że sortowanie po dacie zakupu powinno już działać prawidłowo.
