### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by karolszabatis** [allegro/allegro-api#7690]
Dzień dobry,

czy mogę prosić o aktywację konta na sandboxie?  `https://apps.developer.allegro.pl.allegrosandbox.pl/`

Login: `sandbox_innrosa`

Pozdrawiam i z góry dziękuję :)

**Comment by MaciejFrackowiak** [comment]
Proszę dokończ proces konfiguracji konta tj. wykonaj przelew poprzez symulator płatności oraz przekaż dowolne pliki jako dokumenty firmowe - zrobisz to w tzw. [krokowcu](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto).

**Comment by MaciejFrackowiak** [comment]
Konto jest już zweryfikowane.
