### ISSUE TITLE
Sanbox - delivery methods to test our new flow

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#7691]
Hi, we have implemented certain changes in our process, which makes it resilient to cases

1. carrier does not support parcel pickup porposals
2. carrier does not support parcel pickup at all

I was trying to find carriers with this limitation, but no luck. Can you let me know, which carriers do behave the way I need?

order ID				                                delivery method name
644c94c0-5d3e-11ee-aad3-796d77fed128	DPD Pickup Point
5ec9ac80-5dd0-11ee-aad3-796d77fed128	Allegro Pocztex Pick-up Point
9d098c90-5dd5-11ee-aad3-796d77fed128	Allegro DHL Pickup
4386de70-5dda-11ee-aad3-796d77fed128	Allegro Pocztex Courier
34c794a0-5ddb-11ee-aad3-796d77fed128	Allegro DHL Courier

**Comment by MaciejFrackowiak** [comment]
Courier Pocztex does not support parcel pickup, so you are not able to get parcel pickup proposals.

**Comment by GabrielKalapos** [comment]
> Courier Pocztex does not support parcel pickup, so you are not able to get parcel pickup proposals.

Thank you Maciej, coudl you please give as as well courier that supports "parcel pick up" but does not support "parcel pick up date proposal"?

**Comment by MaciejFrackowiak** [comment]
Also, for Packeta and WeDo you cannot order a pickup via API resources.

**Comment by ZajdaBear** [comment]
Hi, this was a sandbox question

1. 4386de70-5dda-11ee-aad3-796d77fed128 Allegro Pocztex Courier - allowed parcel proposal and parcel pickup on sandbox.
2. Packeta & WEDO, how are those available on sandbox? My impression is, sandbox is PL only.

**Comment by MaciejFrackowiak** [comment]
1. Your operation with commandId=4c8ae2f8-e477-41d3-bbfa-776421b6491e finished with an error - so you cannot order a pickup for Pocztex parcels.
2. Packeta and WeDo delivery methods are available on the Sandbox.
