### ISSUE TITLE
shipment-management - brak dostępu

### ISSUE THREAD

**Issue by vipquertik** [allegro/allegro-api#7692]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
![allegroApi](https://github.com/allegro/allegro-api/assets/65281084/628920fc-e680-496c-83bd-92b4e3addd54)

Witam,
Mam problem z użyciem nowego zasobu shipment-management/shipments/create-commands 
zamiast parcel-management/parcel-create-commands/{commandId}

Dostaje komunikat Forbidden

**Comment by hahyes** [comment]
@vipquertik Upewnij się, że token, który wysyłasz posiada uprawnienia **allegro:api:shipments:write** oraz **allegro:api:shipments:read**.

**Comment by vipquertik** [comment]
Faktycznie brak uprawnień w aplikacji zarejestrowanej w Allegro. 
Ale nie mogę zmienić tych uprawnień -  są na sztywno przypisane i brak wpisu allegro:api:shipments:read.

Allegro Pomocy !

**Comment by AureliuszBrussy** [comment]
Widzę, że @hahyes wyjaśnił sytuację. Dzięki! :)
