### ISSUE TITLE
Rynki zagraniczne w /offers/listing

### ISSUE THREAD

**Issue by javaguru-pl** [allegro/allegro-api#7693]
Jak w parametrach metody /offers/listing można wskazać, aby wyszukiwanie odbywało się na rynkach zagranicznych? (np. allegro-cz)
W dokumentacji tej metody niestety nigdzie nie ma takiej informacji.

**Comment by MartaNowaczyk** [comment]
Na ten moment nie ma takiej możliwości. Mamy w planach umożliwienie takiego wyszukiwania, jednak nie mamy konkretnej daty. Na pewno poinformujemy o tym w odpowiednim komunikacie, gdy to udostępnimy.
