### ISSUE TITLE
Problem z produktyzacją - 409 przy propozycji produktu

### ISSUE THREAD

**Issue by imper86** [allegro/allegro-api#7694]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Potrzebuję dodać nowy produkt poprzez endpoint `POST /sale/product-proposals`, ale otrzymuję status 409 z informacją o duplikacie.

Trace-id: `cb0663e4ce6927c4`

Request:
```json
{"name":"KURTKA 4F M\u0118SKA ZIMOWA DWUSTRONNA CZARNA","category":{"id":"5537"},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/1112ae\/e1fcac0a4d53ae578a0fe65565ef"}],"parameters":[{"id":"11323","valuesIds":["11323_1"],"rangeValue":null},{"id":"201017","valuesIds":["201017_2377"],"rangeValue":null},{"id":"201025","valuesIds":["201025_2509"],"rangeValue":null},{"id":"201405","valuesIds":["201405_208161"],"rangeValue":null},{"id":"202893","valuesIds":["202893_748689"],"rangeValue":null},{"id":"206438","valuesIds":["206438_227566"],"rangeValue":null},{"id":"221333","valuesIds":["221333_295205"],"rangeValue":null},{"id":"225693","values":["5904698744503"],"rangeValue":null},{"id":"249512","valuesIds":["249512_1647413"],"rangeValue":null},{"id":"3766","valuesIds":["3766_2397"],"rangeValue":null},{"id":"3786","valuesIds":["3786_189"],"rangeValue":null},{"id":"54","valuesIds":["54_8"],"rangeValue":null},{"id":"15851","valuesIds":["15851_2"],"rangeValue":null},{"id":"202897","valuesIds":["202897_32","202897_128"],"rangeValue":null},{"id":"215930","values":["100% POLIESTER"],"rangeValue":null},{"id":"237206","values":["4FWAW23TDJAM434"],"rangeValue":null},{"id":"249516","valuesIds":["249516_1647647"],"rangeValue":null}],"description":null,"language":"pl-PL"}
```

Response:
```json
{"errors":[{"code":"ProductDuplicate","message":"An error has occurred","details":null,"path":null,"userMessage":"Produkt z takimi danymi już istnieje. Skontaktuj się z autorem aplikacji."}]}
```

Widzę, że w nagłówku location mam link https://api.allegro.pl/sale/products/87b5506f-7c19-412f-aa27-f22adf69ae37 ale to jest zupełnie inny produkt. Inny kod producenta, inny EAN.

Dlaczego tak się dzieje? Proste wyszukanie po EANie nie zwraca żadnego wyniku: `/sale/products?ean=5904698744503&includeDrafts=true`

Z góry dzięki za pomoc

**Comment by MartaNowaczyk** [comment]
Z tego co ustaliłam:
- w produkcie, który zidentyfikowaliśmy jest to samo zdjęcie, po którym między innymi wykryliśmy duplikat 
- zdjęcie było błędne, bo na zdjęciu była torba, a powinna być kurtka - w produkcie już je usunęliśmy, więc prośba byś przy tworzeniu produktu dodał również poprawne i to powinno pomóc;
- nie podajesz kodu producenta ("224017") tylko model ("237206");
- tak jak piszesz jest inny EAN, ale nie zawsze identyfikacja może odbywać się po kodzie EAN np. ze względu na to, że te same produkty mogą mieć różne EANy w różnych krajach;
- wyszukałam podobne produkty po modelu - GET /sale/products?phrase=4FWAW23TDJAM434.
