### ISSUE TITLE
Wielopaczkowość DHL

### ISSUE THREAD

**Issue by Farby123** [allegro/allegro-api#7696]
W przypadku próby dodania wielopaczkowości przez API mamy błąd:
![image](https://github.com/allegro/allegro-api/assets/146427529/4ba355d5-95f2-41d5-9974-0eedd79cf785)
w jaki sposób możemy do jednego zamówienia wysłać więcej jak jedną przesyłkę przez kuriera DHL ?

**Comment by MaciejFrackowiak** [comment]
Usługa wielopaczki dostępna jest tylko w DPD. W przypadku DHL musisz wysłać kolejne przesyłki w osobnych requestach.
