### ISSUE TITLE
create variants in sandbox

### ISSUE THREAD

**Issue by shopyon** [allegro/allegro-api#7697]
Hello,
I'm trying to create variants according to https://developer.allegro.pl/documentation#operation/createVariantSet , but I keep getting the error "Oferty 7725294500, 7725294520, 7725294521 mają niedozwolone rynki bazowe allegro-cz, allegro-cz, allegro-cz."
Where is the problem please?

sandbox: api.allegro.pl.allegrosandbox.pl
client ID: 1870466b9a974f29b2a2e84c381c70b9

json:
`{"name":"test variant","offers":[{"id":"7725294500"},{"id":"7725294520"},{"id":"7725294521"}],"parameters":[{"id":"18692"},{"id":"2973"}]}`

**Comment by MartaNowaczyk** [comment]
It is not possible to create variants for offers listed on the base service allegro.cz. We have this information in the [documentation](https://developer.allegro.pl/documentation/#operation/createVariantSet):

> offers must have publication.marketplaces.base equal to allegro-pl
