### ISSUE TITLE
Sandbox sales activation

### ISSUE THREAD

**Issue by HiKami172** [allegro/allegro-api#7698]
Hello, I would like to request sales activation on my sandbox account.
Tried to figure out the way to do it, but it won't go further than payment method.
Here is my client id: Client:106104254
Thank you in advance!

**Comment by MaciejFrackowiak** [comment]
I have activated your regular account. To list an offer on Sandbox you have to change your account to the company one - you can do it [here](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).
