### ISSUE TITLE
Kompresja

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#7699]
Czy API obsługuje jakąś formę kompresji?

**Comment by MaciejFrackowiak** [comment]
Nie, nie stosujemy żadnej kompresji.

**Comment by TimothyKoval** [comment]
[https://github.com/allegro/restapi-guideline#keep-response-gziped](https://github.com/allegro/restapi-guideline#keep-response-gziped) 

Rozumiem, że ten dokument jest nieważny

**Comment by MaciejFrackowiak** [comment]
Jest aktualny - moja pomyłka. Znalazłeś właściwe info.

**Comment by TimothyKoval** [comment]
W takim razie nie działa

```
GET /me HTTP/2
Host: api.allegro.pl
accept-encoding: deflate, gzip, br, zstd
accept-language: pl-PL
accept: application/vnd.allegro.public.v1+json
content-type: application/vnd.allegro.public.v1+json
authorization: bearer eyJhbGciOi ... u5DnYrSVPg
```

```
HTTP/2 200 
trace-id: 614be7f8b9fa45da
date: Mon, 02 Oct 2023 05:14:09 GMT
content-type: application/vnd.allegro.public.v1+json
content-length: 223
```

```
GET /me HTTP/2
Host: api.allegro.pl
accept-language: pl-PL
accept: application/vnd.allegro.public.v1+json
content-type: application/vnd.allegro.public.v1+json
authorization: bearer eyJhbGciOi ... u5DnYrSVPg
```

```
HTTP/2 200 
trace-id: 18580fe5d6391bec
date: Mon, 02 Oct 2023 05:16:01 GMT
content-type: application/vnd.allegro.public.v1+json
content-length: 223
```

**Comment by MaciejFrackowiak** [comment]
Sprawdzimy to i wrócę do Ciebie z odpowiedzią.

**Comment by TimothyKoval** [comment]
Jak wygląda sytuacja?

**Comment by Lukasz-Zurek** [comment]
@TimothyKoval Przepraszam, że musiałeś dłużej czekać na odpowiedź. Skonsultowaliśmy tę sprawę z odpowiednim zespołem. Jak się okazuje - z przyczyn technicznych zrezygnowaliśmy ostatecznie z kompresji. Zaktualizuję dokumentację, ponieważ informacje tam zawarte nie są już aktualne. 

Przepraszamy Cię za lekkie zamieszanie.
