### ISSUE TITLE
WebAPI - rozbieżności typów danych w WSDL

### ISSUE THREAD

**Issue by PhotoSoft** [allegro/allegro-api#77]
Pierwszy problem dotyczy **dealId** w _DoSendRefundFormRequest_ oraz _DoGetRefundsReasonsRequest_, które powinny być zadeklarowane jako **long** tak jak to jest w innych metodach, a nie **int**.

Druga sprawa dotyczy **fvalueDatetime**, które w _FieldsValue_ jest zadeklarowane jako **float**, a powinno być **long** analogicznie jak jest, np. przy **itStartingTime** w _ItemInfoExt_.

Te dwa błędy powodują problemy z przesyłaniem danych .NET.

**Comment by AniaMalinowska** [comment]
Weryfikujemy tę kwestię, prosimy o cierpliwość.

**Comment by PawelTaberski** [comment]
W przypadku metod DoSendRefundFormRequest oraz DoGetRefundsReasonsRequest występuje rozbieżność w dokumentacji, w wsdl-u ten parametr jest w obu przypadkach int.
Dokumentacje oczywiście zaktualizujemy.
A odnośnie problemów, jaki błąd otrzymujesz, z czym on jest związany?

**Comment by PhotoSoft** [comment]
To nie jest rozbieżność w dokumentacji tylko w WSDLu. Przecież wszędzie dealId to long oprócz tych dwóch wymienionych przeze mnie metod:
https://allegro.pl/webapi/documentation.php/show/id,462#method-output

Odnośnie drugiego problemu. Przez zły typ fvalueDatetime poniższy kod (przynajmniej w C#) powoduje, że wysyłana jest błędna data wystawienia aukcji:

```
long unixTime = 1521642822; // 2018-03-21T14:33:42
float fvalueDatetime = unixTime; // otrzymuje 1.52164288E+09, czyli 2018-03-21T14:34:40
```

**Comment by PawelTaberski** [comment]
Teraz rozumiem, sądziłem że chodzi o tą rozbieżność. Przekazałem Pana sugestie do odpowiedniego działu, jak tylko dostanę jakąś informację dam znać.
