### ISSUE TITLE
Zakup produktu, ponowne logowanie - rezultat -> brak mozliwosci zakupu produktu

### ISSUE THREAD

**Issue by lukaszkafel** [allegro/allegro-api#770]
Scenariusz: Wyszukuje aukcje i dokonuje zakupu
    Otrzymuje okno do zalogowania uzytkownika 
    Loguje sie na zalozonego i aktywowanego uzytkownika 
    Przechodze do podsumowania i wyboru oplaci platnosci 
    Potwierdzam platnosc
    Oczekuje podsumowania platnosci, ale otrzymuje ponowne okno do logowania

**Comment by PawelTaberski** [comment]
Mówimy o środowisku testowym, czy produkcji?

**Comment by lukaszkafel** [comment]
Allegrosandbox.pl

**Comment by PawelTaberski** [comment]
Rozumiem tak się spodziewałem obecnie są jakieś problemy z logowaniem, pracujemy nad rozwiązaniem tego problemu. Proszę o cierpliwość.
