### ISSUE TITLE
Aktualizacja wersji tecdoc

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#7700]
Podczas aktualizacji ofert często otrzymujemy błąd o nieaktualnej wersji tecdoc. W czeluściach internetu wyczytałem, że wystarczy wysłać pustego PATCH-a na `/sale/product-offers`, co poniekąd przynosi jakiś skutek.

Jak uniknąć tego typu problemów w przyszłości? Skoro jakieś dane są wymagane w danej formie dla danego produktu, to ani nie widzę potrzeby przesyłania tych danych, ani ich aktualizowania w przypadku zmian w produkcie.

**Comment by PrzemyslawLukanowski** [comment]
W przypadku zmian danych w produkcie, nie aktualizujemy automatycznie informacji w ofercie, musisz to wykonać po swojej stronie. Prócz rozwiązania, które wymieniłeś, możesz także w requeście wysłać wyłącznie `productSet.product.id` wraz z wartością -  na tej podstawie również zaktualizujemy dane na podstawie wskazanego produktu.

**Comment by TimothyKoval** [comment]
Czyli co kwartał muszę bezsensownie rezać miliony ofert?

**Comment by PrzemyslawLukanowski** [comment]
Jeśli zwracamy błąd związany z niezgodnością danych, to tak, taka aktualizacja ofert jest konieczna.
