### ISSUE TITLE
Wysyłam z Allegro - sprawdzenie statusu przesyłki, kilkudniowe, niezmienne IN_PROGRESS (powrót zjawiska)

### ISSUE THREAD

**Issue by mmodrzejewski** [allegro/allegro-api#7701]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,
Chciałbym się odnieść do problemu, który już podobno został rozwiązany dawno temu... Tutaj mam przypadek, że jednak powrócił:
parcel-management/parcel-create-commands/ea86d941-afbf-4727-812f-ed3b2c4763dc

`{"id":"ea86d941-afbf-4727-812f-ed3b2c4763dc","parcelId":null,"status":"IN_PROGRESS","errors":[]}`

Przypadek dotyczy Allegro One Box, usługa
0aafb43c-e66a-46ec-9cc4-29bb39ebb483

Zlecenie było **28.09, ok 11:51**.... Status  **IN_PROGRESS** nie zmienił się, wciąż trwa. 

Rozumiem, że coś nie zadziałało w docelowym API przewoźnika, ale naturalną rzeczą jest tutaj zaktualizowanie informacji, chociażby poprzez zmianę statusu u Was. 

W takiej sytuacji integrator nie wie czego się spodziewać. Można oczywiście założyć automatyczne odrzucenie zlecenia po X czasu, ale...no właśnie, po jakim czasie. Czy możecie coś zasugerować lub wypisać zasady? A najlepiej dostosować mechanizm automatycznej aktualizacji statusu na odrzucony.

W obecnej sytuacji rolę odgrywa obszar interpretacji. Co będzie, jeżeli ja taką przesyłkę odrzucę według własnych założeń i zasugeruję klientowi, aby wygenerował kolejną, a zlecenie **IN_PROGRESS** nagle zostanie przetworzone?

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję tę sytuację z zespołem odpowiedzialnym za usługę Wysyłam z Allegro. Jak tylko dowiem się więcej szczegółów, wrócę z informacją.

**Comment by PrzemyslawLukanowski** [comment]
Otrzymałem informację, że błąd występował sporadycznie i zostanie poprawiony w najbliższych dniach.
