### ISSUE TITLE
Błąd podczas awizacji przesyłki

### ISSUE THREAD

**Issue by inTestowy** [allegro/allegro-api#7702]
Awizacja przesyłki nie przechodzi, zwracając błędy.
Błąd walidacji: "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej. - Problem with dispatch. Contact us, and we will help as soon as possible."
Błąd awizacji: "Awizacja przesyłki nie powiodła się. Proszę zweryfikować poprawność przesyłki."
CommandId: "4ad5646a-4ccb-448e-8658-fd397642d05e".

**Comment by inTestowy** [comment]
Po wysłaniu requesta:
https://api.allegro.pl.allegrosandbox.pl/shipment-management/shipments/create-commands/f1435f38-35e8-4597-b387-d2a9fa7e2a3a

Dostajemy zwrotkę:

{"commandId":"f1435f38-35e8-4597-b387-d2a9fa7e2a3a",
"status":"ERROR","errors":[{"code":"PROCESSING_ERROR","message":"Problem with dispatch. Contact us, and we will help as soon as possible.","details":null,"path":null,"userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}],"shipmentId":null}

Środowisko sandbox, jest to odpytanie po utworzeniu przesyłki metodą 'Create new Shipment', która zwróciła taki commandId oraz pełny przesłany Input - Status 200

**Comment by Electronc** [comment]
> Po wysłaniu requesta: https://api.allegro.pl.allegrosandbox.pl/shipment-management/shipments/create-commands/f1435f38-35e8-4597-b387-d2a9fa7e2a3a
> 
> Dostajemy zwrotkę:
> 
> {"commandId":"f1435f38-35e8-4597-b387-d2a9fa7e2a3a", "status":"ERROR","errors":[{"code":"PROCESSING_ERROR","message":"Problem with dispatch. Contact us, and we will help as soon as possible.","details":null,"path":null,"userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}],"shipmentId":null}
> 
> Środowisko sandbox, jest to odpytanie po utworzeniu przesyłki metodą 'Create new Shipment', która zwróciła taki commandId oraz pełny przesłany Input - Status 200

@inTestowy Podrzuć input do stworzenia paczki. Pewnie tam jest błąd. Miałem identycznie. Na sandboxie jest problem z komunikatami obsługującymi zwrotki błędów. Sprawdź poprawność numeru telefonu, streetnumber jeśli podajesz, upewnij się też że id metody dostawy jest prawidłowe w kontekście zamówienia.

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, widzę, że w polach `streetNumber` przekazujesz 0, taka wartość widnieje również w `receiver.phone`.

**Comment by inTestowy** [comment]
Po odpowiednim uzupełnieniu pól, taki sam rezultat.

Request: "https://api.allegro.pl.allegrosandbox.pl/shipment-management/shipments/create-commands/7a60aa4c-1a0a-44d5-b70f-67a04c793ce8"

Odpowiedź: {"commandId":"7a60aa4c-1a0a-44d5-b70f-67a04c793ce8","status":"ERROR","errors":[{"code":"PROCESSING_ERROR","message":"Problem with dispatch. Contact us, and we will help as soon as possible.","details":null,"path":null,"userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}],"shipmentId":null}

**Comment by PrzemyslawLukanowski** [comment]
Wygląda na to, że kod pocztowy 65-466 podany w `receiver.postalCode` jest błędny.

**Comment by inTestowy** [comment]
Dokładnie tak- dziękuję za pomoc, dla testów wpisywaliśmy losowe dane, aktualnie przesyłka utworzyła się, i posiada prawidłowy status. 

Czy na bazie produkcyjnej komunikaty błędów będą jaśniejsze na nowym 'Shipment management' API?
Po wgraniu takiej wersji do klienta, będziemy musieli dochodzić godzinami co jest nie prawidłowo w przypadku np. błędnego kodu pocztowego?

**Comment by PrzemyslawLukanowski** [comment]
Tak, na bieżąco odpowiednio aktualizujemy treść błędów, tak aby precyzyjnie wskazywały przyczynę.
