### ISSUE TITLE
NO_RESCISSION - The application has not been found.

### ISSUE THREAD

**Issue by rychu-tech** [allegro/allegro-api#7704]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

**Opis / Description**
Wysyłając zapytanie GET https://api.allegro.pl/order/customer-returns/{complaint_id} (z własnym id zwrotu)
Otrzymuję odpowiedź:
    "errors": [
        {
            "code": "NO_RESCISSION",
            "message": "An error has occurred",
            "details": null,
            "path": null,
            "userMessage": "The application has not been found."
        }
    ]
Pozostałe zapytania np. o listę wszystkich zwrotów działają poprawnie.

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swojego wywołania, wówczas będę mógł zweryfikować przypadek.

**Comment by rychu-tech** [comment]
@MaciejFrackowiak 356fcc6ee7513948

**Comment by MaciejFrackowiak** [comment]
Czy na liście zwrotów widzisz ten zwrot o id=9bd72188-5760-xxxxxxx?

**Comment by rychu-tech** [comment]
Aktualnie nie, ale wcześniej był. Jeżeli przekopiowuję teraz jakikolwiek id, który jest na liście, to zapytanie działa poprawnie.
Dla tego, którego nie ma na liście, ale wcześniej był widoczny, zwrot wygląda jak w zgłoszeniu.

**Comment by MaciejFrackowiak** [comment]
Problem tkwi w koncie, z którego wykonujesz request. Wywołujesz zwrot z konta o id=2704xxxx, a wymieniony zwrot pochodzi z konta 10427xxxx.

**Comment by rychu-tech** [comment]
@MaciejFrackowiak Rozumiem, w tym przypadku rzeczywiście, ale w przypadku z trace-id = bc858dadc52858b3 korzystam już z poprawnego konta.

**Comment by MaciejFrackowiak** [comment]
To jest dokładnie ten sam przypadek - zwrot jest dostępny na koncie 10427xxxx, a request pochodzi z 2704xxxx.

**Comment by rychu-tech** [comment]
@MaciejFrackowiak faktycznie, błąd był po naszej stronie. Dziękuję bardzo za pomoc. Nie zmienia to faktu, że błąd mało intuicyjny.
