### ISSUE TITLE
PROCESSING_ERROR - Get shipment cancellation status

### ISSUE THREAD

**Issue by Electronc** [allegro/allegro-api#7706]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem testowym / with the test environment

:beetle: **Opis / Description**

Mam drobny problem z komunikatem przy weryfikowaniu anulowania paczki. Jeśli mógłbym poprosić o wskazówkę, gdzie jest błąd : -).

Request:

`https://api.allegro.pl.allegrosandbox.pl/shipment-management/shipments/cancel-commands/20B2BBA4-C81D-479F-8227-B2FC7634F25F`

Response:
`{
    "commandId": "20B2BBA4-C81D-479F-8227-B2FC7634F25F",
    "status": "ERROR",
    "errors": [
        {
            "code": "PROCESSING_ERROR",
            "message": "Problem with dispatch. Contact us, and we will help as soon as possible.",
            "details": null,
            "path": null,
            "userMessage": "Problem z nadaniem przesyĹ‚ki. Skontaktuj siÄ™ z nami. PomoĹĽemy jak najszybciej."
        }
    ],
    "shipmentId": null
}`

Request tworzący zapytanie o anulowanie paczki:
Path: `https://api.allegro.pl.allegrosandbox.pl/shipment-management/shipments/cancel-commands`

`{
    "commandId": "20B2BBA4-C81D-479F-8227-B2FC7634F25F",
    "input": {
        "shipmentId": "4badbc34-4600-470c-97cf-7d4ea389d405"
    }
}`

Response:
`{
    "commandId": "20B2BBA4-C81D-479F-8227-B2FC7634F25F",
    "input": {
        "shipmentId": "4badbc34-4600-470c-97cf-7d4ea389d405"
    }
}`

**Comment by MaciejFrackowiak** [comment]
Wracam z odpowiedzią - nie ma możliwości anulowania przesyłki Allegro One. Niezwłocznie postaramy się poprawić komunikat błędu, aby jednoznacznie informował o stanie faktycznym.
