### ISSUE TITLE
Brak metod dostaw w cennikach na nowym koncie

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#7707]
Cześć.

Dlaczego w cennikach dostawy na nowym koncie firmowym nie widzę zakładek:
Rozliczasz się z Allegro (sposób rozliczeń Allegro Standard),  Rozliczasz się z przewoźnikiem (sposób rozliczeń Allegro Mix)?
 
 Czy świadczy to o tym że czegoś nie skonfigurowałem odpowiednio?

**Comment by PrzemyslawLukanowski** [comment]
Ten problem nie jest powiązany z API, dlatego skontaktuj się proszę bezpośrednio przez [formularz kontaktowy.](https://allegro.pl/pomoc/kontakt)
