### ISSUE TITLE
Tworzenie paczki w nowym API

### ISSUE THREAD

**Issue by Adrian-baw** [allegro/allegro-api#7709]
Dzień dobry. Próbuję na produkcyjnym API wywołać tworzenie paczki:
/shipment-management/shipments/create-commands

Za każdym razem otrzymuję komunikat: Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.

{"commandId":"3ef4b4d0-102b-46e0-92c1-b62b12c55587","status":"ERROR","errors":[{"code":"PROCESSING_ERROR","message":"Problem with dispatch. Contact us, and we will help as soon as possible.","details":null,"path":null,"userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}],"shipmentId":null}

Powyższy błąd pojawia się przy sprawdzaniu statusu utworzenia paczki.

trace-id przy tworzeniu paczki: 2d98d544a07885ab
trace-id przy pobraniu statusu utworzenia paczki: 8d88f03221b92484

**Comment by Adrian-baw** [comment]
Doprecyzuję. Powyższe trace-id jest z utworzenia paczki, ono nie zwraca żadnego błędu.

Zwrotkę dostaję oczywiście po odpytaniu statusu nadania: /shipment-management/shipments/create-commands/{$shipmentId}

**Comment by Electronc** [comment]
@Adrian-baw doweryfikuj, czy w polach, które wysyłasz puste masz `null` zamiast `''`, ew jeszcze czy format numeru masz np. +48XXXXXXXXX czy XXXXXXXXX

**Comment by Adrian-baw** [comment]
W żadnym polu nie ma nulla. Wszędzie są wysłane jakieś dane. Numery telefonów są w formacie XXXXXXXXX

**Comment by Maczuga** [comment]
Również podpinam się pod problem:

trace-id: f5e6e8af639c145
commandId=cce68050-8aef-45b2-91c0-2c2361257c48

```json
{
   "commandId":"cce68050-8aef-45b2-91c0-2c2361257c48",
   "status":"ERROR",
   "errors":[
      {
         "code":"PROCESSING_ERROR",
         "message":"Problem with dispatch. Contact us, and we will help as soon as possible.",
         "details":null,
         "path":null,
         "userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."
      }
   ],
   "shipmentId":null
}
```

**Comment by MaciejFrackowiak** [comment]
@Adrian-baw Twój przypadek konsultuję z zespołem odpowiedzialnym za usługę. 

@Maczuga Dla przesyłek DHL wagę przesyłki należy podawać w pełnych wartościach.

**Comment by Maczuga** [comment]
@MaciejFrackowiak dzięki, czy jest może jakaś lista takich wyjątków do obsłużenia? Żebyśmy nie musieli w praktyce każdego przypadku w locie łatać.

**Comment by MaciejFrackowiak** [comment]
@Maczuga Niestety nie ma. Ten przypadek z wagą dotyczy jednak tylko DHL.

**Comment by Adrian-baw** [comment]
> @Adrian-baw Twój przypadek konsultuję z zespołem odpowiedzialnym za usługę.

Rozumiem, z niecierpliwością czekam na odpowiedź. Pozdrawiam.

**Comment by vacsapi** [comment]
Hi, we are also dealing with a similar problem:

    [shipment] => Array
        (
            [commandId] => c74da564-54bf-4fc9-ad23-c2d32817fcd7
            [input] => Array
                (
                    [deliveryMethodId] => 19841d0a-374d-4764-8313-84a1765f3340
                    [credentialsId] => 
                    [sender] => Array
                        (
                            [name] => 
                            [company] => VACS TRADE s.r.o.
                            [street] => Trstěnická
                            [streetNumber] => 933
                            [postalCode] => 57001
                            [city] => Litomyšl
                            [state] => 
                            [countryCode] => CZ
                            [email] => 
                            [phone] => +420733389497
                            [point] => 
                        )

                    [receiver] => Array
                        (
                            [name] => Jakub Přikryl
                            [company] => 
                            [street] => Rantířovská 4787
                            [streetNumber] => .
                            [postalCode] => 586 05
                            [city] => Jihlava 
                            [state] => 
                            [countryCode] => CZ
                            [email] => wpheimdron+5c6362bb2@allegromail.com
                            [phone] => +420731872760
                            [point] => 21031
                        )

                    [pickup] => 
                    [referenceNumber] => 231500008
                    [description] => 
                    [packages] => Array
                        (
                            [0] => Array
                                (
                                    [type] => PACKAGE
                                    [length] => Array
                                        (
                                            [value] => 1
                                            [unit] => CENTIMETER
                                        )

                                    [width] => Array
                                        (
                                            [value] => 1
                                            [unit] => CENTIMETER
                                        )

                                    [height] => Array
                                        (
                                            [value] => 1
                                            [unit] => CENTIMETER
                                        )

                                    [weight] => Array
                                        (
                                            [value] => 1
                                            [unit] => KILOGRAMS
                                        )

                                )

                        )

                    [insurance] => Array
                        (
                            [amount] => 471.00
                            [currency] => CZK
                        )

                    [cashOnDelivery] => Array
                        (
                            [amount] => 471.00
                            [currency] => CZK
                            [ownerName] => 
                            [iban] => 
                        )

                    [labelFormat] => PDF
                    [additionalServices] => Array
                        (
                        )

                )

        )

    [status] => Array
        (
            [commandId] => c74da564-54bf-4fc9-ad23-c2d32817fcd7
            [status] => ERROR
            [errors] => Array
                (
                    [0] => Array
                        (
                            [code] => PROCESSING_ERROR
                            [message] => Problem with dispatch. Contact us, and we will help as soon as possible.
                            [details] => 
                            [path] => 
                            [userMessage] => Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.
                        )

                )

            [shipmentId] => 
        )

)
1

**Comment by vacsapi** [comment]
Won't this be the problem? The Allegro API returns us the street and the house number together as one item, but when the label is to be created, are these two data separated - the street separately and the house number separately? We have experience that carriers want this data separately.

**Comment by PrzemyslawLukanowski** [comment]
@Adrian-baw Na tę chwilę, aby wyeliminować problem, możesz uzupełnić pole dotyczące opisu przesyłki - `description`. Wewnętrznie weryfikujemy jeszcze zasadność wymogu tego pola przez przewoźnika.

@vacsapi Please fill the email in the `sender.email` field. And yes, your point is also accurate - this information should be provided separately.

**Comment by vacsapi** [comment]
@PrzemyslawLukanowski Hi, thanks for your response. It is not a problem to fill an email of the sender. The number of the house - how can we do it? We have these information from API Allegro together.

**Comment by Maczuga** [comment]
@PrzemyslawLukanowski czy mógłbym prosić o ponowne sprawdzenie kolejnego przypadku - dlaczego otrzymujemy "Problem with dispatch. Contact us, and we will help as soon as possible." dla podanego requesta:

commandId=f4677cc1-c527-4b13-adf7-0d62a9eda056
trace-id: 5b249e9ede7e8486

Wysyłka UPS Allegro WzA

**Comment by PrzemyslawLukanowski** [comment]
@vacsapi I have double-checked this requirement and it is not necessary to fill in these information separately, it is optional. You can complete it as in your example above.

@Maczuga Wygląda to na problem z formatem numerów telefonu. W `sender.phone` przesyłasz 10 cyfr, natomiast w `receiver.phone` brakuje "+" na początku.

**Comment by vacsapi** [comment]
@PrzemyslawLukanowski Do I understand well that it will be enough to fill the sender email?

**Comment by PrzemyslawLukanowski** [comment]
@vacsapi Yes, it should solve the problem.

**Comment by Electronc** [comment]
@PrzemyslawLukanowski mógłbym poprosić o weryfikację dla command-id: e661fb35-f50c-4aab-9e14-9df676bbdd56
