### ISSUE TITLE
[PYTANIE] [REST] Informacje o kosztach wystawienia i prowizji

### ISSUE THREAD

**Issue by KluseG** [allegro/allegro-api#771]
Dzień dobry.

Pragnę zapytać, czy istnieje w REST API możliwość pobrania informacji o kosztach wystawienia oferty oraz prowizji od sprzedaży? Ew. kiedy taka możliwość (i czy w ogóle) się pojawi?

**Comment by PawelTaberski** [comment]
Tak, możesz sprawdzić takie informacje przy pomocy Kalkulatora opłat. Więcej informacji na ten temat znajdziesz [tutaj](https://developer.allegro.pl/news/2018-10-03-Zmiana_w_kalkulatorze_oplat/).

**Comment by KluseG** [comment]
Dzięki. Dodatkowe pytanie: Czy planujecie wprowadzić jakieś zasoby dot. Allegro Finanse? Np. lista wypłat na konto bankowe, etc. + zwroty zamówień? (coś na kształt doGetRefundsList z WebAPI)

**Comment by PawelTaberski** [comment]
Ilość zasobów w REST API staramy się rozwijać i zwiększać, na chwilę obecną nie wiem kiedy wdrożymy zasób do pobrania wniosków o zwrot prowizji. Jeśli będziemy planowali wdrożyć taki zasób, bądź jakieś inne dot. Allegro Finanse na pewno o tym poinformujemy. Odnośnie zamówień i wpłat obecnie udostępniliśmy zasoby pozwalające na obsługę zamówień. Obejmują one również niedopłaty i nadpłaty. Poradnik na temat obsługi zamówień przez REST API znajdziesz [tutaj](https://developer.allegro.pl/orders/).

**Comment by KluseG** [comment]
Wpłaty - ok. Tylko co z wypłatami? Przydatny zasób

**Comment by PawelTaberski** [comment]
Rozumiem, tak jak pisałem na chwilę obecną nie mam informacji kiedy wdrożymy takie zasoby.
