### ISSUE TITLE
Sandbox - proszę o weryfikację

### ISSUE THREAD

**Issue by Burovytskyi** [allegro/allegro-api#7710]
Witam,
proszę o weryfikację :)
login: 106181434

Zarządzanie aplikacjami Allegro Sandbox

Nie możesz zarejestrować nowej aplikacji
[Aktywuj konto](https://allegro.pl/pomoc/dla-sprzedajacych/rejestracja-i-aktywacja/czym-jest-pelna-aktywacja-konta-i-jak-moge-ja-przeprowadzic-GDeq5WOB8uE) oraz włącz [dwustopniowe logowanie](https://allegro.pl/pomoc/dla-kupujacych/logowanie-i-haslo/czym-jest-dwustopniowe-logowanie-i-dlaczego-warto-z-niego-korzystac-dykqg9nMKSZ).

![image](https://github.com/allegro/allegro-api/assets/11057850/357b2ddd-24ed-408d-bdf4-988e5cbecc1a)

**Comment by MaciejFrackowiak** [comment]
Aktywowałem Twoje konto.

**Comment by Burovytskyi** [comment]
Dziękuje bardzo :)

miłego dnia 👍
