### ISSUE TITLE
Parametry produktu

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#7712]
Czy ktoś może mi wyjaśnić co oznacza w parametrach `describesProduct` i `requiredForProduct`?

Z tego co rozumiem, describesProduct oznacza, że dany parametr trzeba przekazać w `productSet`, a `requiredForProduct` wskazuje, że parametr jest wymagany przy tworzeniu nowego produktu.

Czy w przypadku kiedy wystawiam ofertę z istniejącym produktem `requiredForProduct` jest jednoznaczne z tym, że dany parametr muszę zaciągnąć z tego produktu i nie mogę podać własnej wartości?

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, wartość w `describesProduct`wskazuje, czy parametr należy przekazać w sekcji ofertowej `parameters`, czy. w produktowej `productSet.product.parameters`. `requiredForProduct` oznacza, że parametr należy przekazać w sytuacji, gdy tworzysz nowy produkt i w większości przypadków nie będzie możliwości, aby zmienić w nim wartość, jeśli łączysz ofertę z istniejącym produktem. Wyjątkiem będą parametry, które nie identyfikują produktu, czyli te, które zwracamy w odpowiedzi GET /sale/products/{productID} i są oznaczone jako `"options.identifiesProduct": false` - w takich przypadkach możesz nadpisać wartość.

**Comment by TimothyKoval** [comment]
To czemu np. dla produktu `8d293fef-a66f-4711-afb4-1b3caa73a477` parametr EAN zwraca `identifiesProduct: false`?

**Comment by PrzemyslawLukanowski** [comment]
W przypadku tej kategorii parametrami identyfikującymi produkt są Marka i Kod Producenta - dlatego istnieje możliwość nadpisania parametru EAN.

**Comment by TimothyKoval** [comment]
> Niepoprawna wartość parametru EAN/ISBN/ISSN (225693) dla produktu w ofercie. Prawidłowa wartość parametru dla produktu to: "5906083915390".

Chyba nie bardzo

**Comment by PrzemyslawLukanowski** [comment]
Możesz podać trace-id dla tego komunikatu? Wykonałem test i mogłem zmienić wartość EAN przy wiązaniu z tym produktem.

**Comment by TimothyKoval** [comment]
`454faed7a0e9d6fc`

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję jeszcze tę sytuację, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
W Twoim przypadku problem występuje, ponieważ produkt wystawiasz w kategorii innej od głównej kategorii produktu - w jej przypadku parametr EAN już identyfikuje produkt. Taką informację otrzymasz w odpowiedzi poniższego zapytania, z parameterem category.id:

GET /sale/products/8d293fef-a66f-4711-afb4-1b3caa73a477?category.id=252694

```
{
            "id": "225693",
            "name": "EAN (GTIN)",
            "valuesLabels": [
                "5906083915390"
            ],
            "values": [
                "5906083915390"
            ],
            "unit": null,
            "options": {
                "identifiesProduct": true,
                "isGTIN": true
            }
        },
```
