### ISSUE TITLE
Problem z uzyskaniem tokena

### ISSUE THREAD

**Issue by MirekBur** [allegro/allegro-api#7713]
Hello.
Thanks for the reply.
I am posting my code below.
If I choose:
var content = new StringContent("grant_type=client_credentials", Encoding.UTF8, "application/json");
is the server's response:
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers: { x-frame-options: SAMEORIGIN strict-transport-security: max-age=15552000 accept-ch: Sec-CH-UA,Sec-CH-UA-Mobile,Sec-CH-UA-Platform,Sec-CH-UA-Arch,Sec-CH-UA-Full-Version-List,Sec-CH-UA-Model,Sec-CH-Device-Memory Accept-Ranges: bytes Date: Wed, 04 Oct 2023 05:30:50 GMT ETag: "6244713d-8e" Set-Cookie: _cmuid=e81f42aa-9ad3-4655-8acd-ffa8437ab883; Expires=Thu, 07 Nov 2024 05:30:50 GMT; Path=/; Domain=.allegro.pl; Secure Set-Cookie: datadome=47EtZzJlPiQfc3TQEFi2lvSrPXC~4eZNEOTFhpIBDBSnu-bFN5l3uCjswWHd6DoE94urG9S6sPcw4Ya795DZi3xMxyN6Vq6JqeYvB64MbG4-PocDV2y1gLfp~XhlOxCY; Max-Age=31536000; Domain=.allegro.pl; Path=/; Secure; SameSite=Lax Content-Length: 142 Content-Type: text/html Last-Modified: Wed, 30 Mar 2022 15:03:25 GMT }
 
Although the server response is OK / 200 / I don't see the token returned here. Or am I mistaken?
 
If I choose:
var content = new StringContent("grant_type=client_credentials", Encoding.UTF8, "application/x-www-form-urlencoded");
is the server's response:
{"error":"Unauthorized","error_description":"Unauthorized"}.
 
Could there be a problem with the account activation? Thank you for your help. 
Our account ID is: 106153626 and the account I need to manage is info@prokauf.cz /iZelezarstvi/
Miroslav Burianek
Prokauf Komplex s.r.o.
Tel. +420 724 761 918
 
My code:
private const string ClientId = "353f861161bd9e4424fda4b9599af0be"; 
private const string ClientSecret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"; 
private const string TokenUrl = "https://allegro.pl/auth/oauth/token";

private HttpClient CreateHttpClient() 
{
var httpClient = new HttpClient(); 
var authorization = Convert.ToBase64String(Encoding.ASCII.GetBytes(ClientId + ":" + ClientSecret)); 
httpClient.DefaultRequestHeaders.Add("Authorization", "Basic " + authorization);
return httpClient; 
}
private async Task<string> GetAccessTokenAsync() 
{
var httpClient = new HttpClient(); 
var content = new StringContent("grant_type=client_credentials", Encoding.UTF8, "application/json"); 
var response = await httpClient.PostAsync(TokenUrl, content); 
if (!response.IsSuccessStatusCode) 
{
return "Something went wrong " + response.StatusCode + " " + await response.Content.ReadAsStringAsync(); 
}else { Response.Write("Uspesne provedeni tokenu: " + response + "<BR>"); } 
var result = await response.Content.ReadAsStringAsync(); 
return result; 
}

**Comment by PrzemyslawLukanowski** [comment]
Hello, there are a few things about your issue:

- '353f861161bd9e4424fda4b9599af0be' we don't have such a client ID in our database, I found a different application, that is registered by your account ID - 7e36bb2fxxxxxxd457c3593c1e6;
- because your account and client ID were registered on the Sandbox environment, you should use different addresses to authorize and to use API - https://allegro.pl.allegrosandbox.pl/auth/oauth, https://api.allegro.pl.allegrosandbox.pl/auth/oauth/token for authorization process and  https://api.allegro.pl.allegrosandbox.pl/ to use our resources;
- you chose the client_credentials type of authorization, which gives you access only to those resources, that are marked as bearer-token-for-application in our documentation. These are endpoints that don't have any user context (so, for example, a list of categories and parameters, but not a list of your offers or orders). To use other resources, you need to authorize using [code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow;
- to list offers via API, you will need the company type of account, right now, you have a regular one. You can register a new account and let me know after it's done, and I will activate it. Please note, that you can enter fake data, including account number, because there are no real payments on Sandbox, everything is handled by the payments simulator.

**Comment by PrzemyslawLukanowski** [comment]
W przypadku środowiska testowego załóż proszę nowe konto firmowe lub zmień profil obecnego na firmowe (powinieneś mieć taką możliwość w zakładce [Dane Konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto)). Za pomocą konta firmowego, będziesz mógł zarządzać ofertami za pomocą API. Musisz jednak dodatkowo zmienić aktualny sposób autoryzacji, czyli zamiast wybranego przez Ciebie sposobu [client_credentials ](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#clientcredentials-flow), użyj [code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow oraz dodatkowo zmień adresy wywołań na te, które wymieniłem wyżej.

W kwestii konta na produkcji iZelezarstvi na produkcji wystarczy, że założysz aplikację na środowisku produkcyjnym https://apps.developer.allegro.pl/ i przejdziesz przez autoryzację typu code lub device. W przypadku tego środowiska możesz korzystać z dotychczasowych adresów wywołań https://allegro.pl/auth/oauth, https://allegro.pl/auth/oauth/token i https://api.allegro.pl.

Wszelkie informacje o konkretnych procesach znajdziesz w naszych poradnikach:
 - [wystawianie oferty z produktem](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA),
 - [zarządzanie ofertami](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase),
 - [zarządzanie zamówienia](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR),

Dodam, że jeśli chcesz widzieć informacje na stronie w języku angielskim, użyj proszę ikonę w prawym górnym rogu strony, aby zmienić język.

**Comment by MirekBur** [comment]
Dziękuję za odpowiedź. Próbuję aktywować aplikację poprzez 
https://apps.developer.allegro.pl/, ale nie można zarejestrować nowej 
aplikacji, ponieważ konto nie jest aktywne, patrz printscreen poniżej. 
Czy mógłbyś go dla mnie aktywować tak jak w poprzednim przypadku. 
Dziękuję


------ Původní zpráva ------
Od: "PrzemyslawLukanowski" ***@***.***>
Komu: "allegro/allegro-api" ***@***.***>
Kopie: "MirekBur" ***@***.***>;"Author" ***@***.***>
Odesláno: 04.10.2023 10:40:43
Předmět: Re: [allegro/allegro-api] Problem z uzyskaniem tokena (Issue 
#7713)

**Comment by PrzemyslawLukanowski** [comment]
Konto produkcyjne jest aktywne, czy masz zatem włączone dwustopniowe logowanie na koncie?

**Comment by MirekBur** [comment]
Tak, wystarczyło włączyć weryfikację dwuetapową.
Token dla identyfikatora klienta 5f0741c78d124e61819fbd949d6847bd już dostaję.
Od razu próbowałem uzyskać szczegóły zamówienia 
93bb4050-628c-11ee-b166-35f9e46bff2b, które mamy na iZelezarstvi, ale 
serwer zwrócił błąd: 
{"code":"EmptyUserIdException","message":"user_name from JWT cannot be 
empty","details":null,"path":"/order/checkout-forms/93bb4050-628c-11ee-b166-35f9e46bff2b","userMessage":"user_name 
from JWT cannot be empty"}
Czy byłoby możliwe sprawdzenie, czy identyfikator klienta 5f0741c78d124e61819fbd949d6847bdma dostęp do iZelezarstva, lub czy 
gdzieś w moim skrypcie występuje błąd?
Dziękuję bardzo

uri=https://api.allegro.pl/order/checkout-forms/93bb4050-628c-11ee-b166-35f9e46bff2b
httpClient.DefaultRequestHeaders.Add("Accept", "application/vnd.allegro.public.v1+json");
httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer "+token);
HttpResponseMessage response;
string responseContent;
if (metoda == "GET")
{
response = await httpClient.GetAsync(uri);
responseContent = await response.Content.ReadAsStringAsync();
}

------ Původní zpráva ------
Od: "PrzemyslawLukanowski" ***@***.***>
Komu: "allegro/allegro-api" ***@***.***>
Kopie: "MirekBur" ***@***.***>;"Author" ***@***.***>
Odesláno: 04.10.2023 10:56:21
Předmět: Re: [allegro/allegro-api] Problem z uzyskaniem tokena (Issue 
#7713)

**Comment by PrzemyslawLukanowski** [comment]
Ten błąd oznacza, że token wygenerowałeś w drodze autoryzacji [client_credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow), czyli nie działasz w kontekście specyficznego użytkownika i masz dostęp tylko do takich zasobów jak np. lista kategorii i parametrów. Aby mieć dostęp. m.in. do zamówień, to jako konkretny użytkownik musisz zautoryzować aplikację, aby ta mogła wykonywać operacje w jego imieniu. W tym celu musisz wygenerować token w drodze autoryzacji [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow).

**Comment by PrzemyslawLukanowski** [comment]
Access token jest ważny przez 12 godzin, ale aby nie przeprowadzać ponownej manualnej autoryzacji po tym czasie, możesz skorzystać z mechanizmu odświeżania tokenów. Za pomocą refresh tokena wygenerujesz nową parę tokenów - aplikacja przed upływem 12 godzin może automatycznie odświeżać parę tokenów. Więcej na ten temat przeczytasz [w tej części poradnika](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena).

**Comment by MirekBur** [comment]
Bardzo ci dziękuje za pomoc. Dzięki Twojej pomocy zweryfikowałem token 
i komunikacja już działa. Mam ostatnią prośbę. Chciałbym zbiorczo dodać 
produkty do naszego sklepu. Chcę rozwiązać ten problem, znajdując 
produkty w cs-CZ według EAN i uzyskując ich identyfikator. Następnie 
skorzystam z metody https://api.allegro.pl/sale/product-offers/{id} i 
wyślę JSON, który będzie zawierał cenę, ilość i czas wysyłki. Wszystko 
inne zostanie dodane zgodnie z Twoją bazą danych. Czy jest to 
prawidłowe rozumowanie, czy też muszę dodać więcej danych? A może 
powinienem zastosować inną metodę tworzenia produktu? Widziałem gdzieś 
na forach, co umożliwia produkt-offers/{id}, ale nie mogę tego znaleźć 
ponownie :( . Dziękuję za pomoc.

------ Původní zpráva ------
Od: "PrzemyslawLukanowski" ***@***.***>
Komu: "allegro/allegro-api" ***@***.***>
Kopie: "MirekBur" ***@***.***>;"Author" ***@***.***>
Odesláno: 05.10.2023 7:38:49
Předmět: Re: [allegro/allegro-api] Problem z uzyskaniem tokena (Issue 
#7713)

**Comment by PrzemyslawLukanowski** [comment]
Prócz danych, które wymieniłeś, musisz jeszcze wskazać id produktu, np.

```
{
    "productSet": [
        {
            "product": {
                "id": "{productId}"
            }
        }
    ],
    "sellingMode": {
        "price": {
            "amount": "220.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 10
    },
    "delivery": {
        "handlingTime": "PT48H"
    }
}
```

lub EAN, w takim przypadku musisz dodać dodatkowe pole `product.idType`:

```
{
    "productSet": [
        {
            "product": {
              "id": "{EAN}",
	      "idType": "GTIN"
            }
        }
    ],
    "sellingMode": {
        "price": {
            "amount": "220.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 10
    },
    "delivery": {
        "handlingTime": "PT48H"
    }
}
```

Powyższe operacją zadziałają tylko wtedy, jeśli produkt o określonym ID/GTIN znajduje się w naszej bazie - sprawdzisz to za pomocą [GET /sale/products](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-znalezc-produkt).

Jeśli nie znajdziesz produktu w naszym katalogu, musisz utworzyć nowy, czyli tym samym ilość danych w sekcji `productSet.product` będzie większa, ponieważ musisz dodatkowo przekazać nam nazwę produktu, kategorię i parametry (wymagane parametry w danej kategorii sprawdzisz za pomocą [GET /sale/categories/{categoryID}/parameters ](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2)- informacja o wymagalności danego produktu znajduje się w polu `"requiredForProduct"`) oraz zdjęcia . Taki proces tworzenia nowego produktu opisaliśmy [w tej części](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-nowym-produktem) naszego poradnika, a przykładowy request załączam poniżej:

```
{
    "productSet": [
        {
            "product": {
                "name": "Produkt testowy",
                "category": {
                    "id": "258020"
                },
                "parameters": [
                    {
                        "name": "EAN",
                        "values": [
                            "0744861045021"
                        ]
                    },
                    {
                        "id": "224017",
                        "values": [
                            "test 1587459230"
                        ]
                    },
                    {
                        "id": "202749",
                        "values": [
                            "5.9"
                        ]
                    },
                    {
                        "id": "202869",
                        "values": [
                            "512 GB"
                        ]
                    },
                    {
                        "id": "202829",
                        "valuesIds": [
                            "202829_1"
                        ]
                    },
                    {
                        "id": "202685",
                        "valuesIds": [
                            "202685_212929"
                        ]
                    },
                    {
                        "id": "127448",
                        "valuesIds": [
                            "127448_2"
                        ]
                    },
                    {
                        "id": "202865",
                        "valuesIds": [
                            "202865_214109"
                        ]
                    },
                    {
                        "id": "4388",
                        "valuesIds": [
                            "4388_1"
                        ]
                    },
                    {
                        "id": "202717",
                        "values": [
                            100
                        ]
                    },
                    {
                        "id": "219",
                        "values": [
                            "Bluetooth"
                        ]
                    },
                    {
                        "id": "202821",
                        "values": [
                            "Dual SIM"
                        ]
                    }
                ],
                "images": [
                    "https://...zewnetrzny-adres-pierwszego-obrazka.jpeg",
                    "https://...zewnetrzny-adres-drugiego-obrazka.jpeg"
                ]
            }
        }
    ],
    "images": [
        "https://testowy-adres.com/obrazek.jpg"
    ],
    "sellingMode": {
        "price": {
            "amount": "12.43",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 10
    },
    "delivery": {
        "handlingTime": "PT48H"
    }
}
```

> Następnie
> skorzystam z metody [https://api.allegro.pl/sale/product-offers/{id}](https://api.allegro.pl/sale/product-offers/%7Bid%7D)

W tym miejscu doprecyzuję, że wspomiany przez Ciebie endpoint /sale/product-offers/{offerId} dotyczy metody PATCH, czyli edycji istniejącej już oferty. Więcej na jej temat znajdziesz [w tym miejscu](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pojedynczej-oferty) poradnika. Wcześniej jednak, musisz utworzyć ofertę, zrobisz to za pomocą POST /sale/product-offers, proces tworzenia oferty opisaliśmy [w tym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA).

**Comment by MirekBur** [comment]
﻿Dziękuję za pomoc. Pomoc dotycząca ofert produktów już działa, 
aktualizując ceny i liczbę konstruktorów produktów, ale jeśli chcę 
dodać nowy produkt za pomocą tej metody, serwer zwraca błąd:
"errors":[{"code":"OfferNotFoundException","message":"Not 
Found","details":null,"path":"","userMessage":"Offer 
31cb12ab-289e-47b1-ba46-f4ed712482f0 does not exist."}]}
Mój skrypt to:
string json = "{\"productSet\":[{\"product\":{\"id\":\"" + idProduktu + "\"}}],\"sellingMode\":{\"price\":{\"amount\":\""+cena+"\",\"currency\":\"CZK\"}},\"stock\":{\"available\":"+pocet+"},\"delivery\":{\"handlingTime\":\"PT48H\"}}";
string vysledekDotazu = await OdeslaniDotazu("PATCH", "https://api.allegro.pl/sale/product-offers/" + idProduktu, json);Czy widzisz gdzieś błąd, proszę?

------ Původní zpráva ------
Od: "PrzemyslawLukanowski" ***@***.***>
Komu: "allegro/allegro-api" ***@***.***>
Kopie: "MirekBur" ***@***.***>;"Author" ***@***.***>
Odesláno: 06.10.2023 10:43:53
Předmět: Re: [allegro/allegro-api] Problem z uzyskaniem tokena (Issue 
#7713)
>Prócz danych, które wymieniłeś, musisz jeszcze wskazać id produktu, np.
>{
>    "productSet": [
>        {
>            "product": {
>                "id": "{productId}"
>            }
>        }
>    ],
>    "sellingMode": {
>        "price": {
>            "amount": "220.85",
>            "currency": "PLN"
>        }
>    },
>    "stock": {
>        "available": 10
>    },
>    "delivery": {
>        "handlingTime": "PT48H"
>    }
>}
>
>
>lub EAN, w takim przypadku musisz dodać dodatkowe pole product.idType:
>{
>    "productSet": [
>        {
>            "product": {
>              "id": "{EAN}",
>	      "idType": "GTIN"
>            }
>        }
>    ],
>    "sellingMode": {
>        "price": {
>            "amount": "220.85",
>            "currency": "PLN"
>        }
>    },
>    "stock": {
>        "available": 10
>    },
>    "delivery": {
>        "handlingTime": "PT48H"
>    }
>}
>
>
>Powyższe operacją zadziałają tylko wtedy, jeśli produkt o określonym 
>ID/GTIN znajduje się w naszej bazie - sprawdzisz to za pomocą GET 
>/sale/products.
>Jeśli nie znajdziesz produktu w naszym katalogu, musisz utworzyć nowy, 
>czyli tym samym ilość danych w sekcji productSet.product będzie większa, ponieważ musisz dodatkowo przekazać 
>nam nazwę produktu, kategorię i parametry (wymagane parametry w danej 
>kategorii sprawdzisz za pomocą GET 
>/sale/categories/{categoryID}/parameters - informacja o wymagalności 
>danego produktu znajduje się w polu "requiredForProduct") oraz zdjęcia . Taki proces tworzenia nowego 
>produktu opisaliśmy w tej części naszego poradnika, a przykładowy request załączam poniżej:
>{
>    "productSet": [
>        {
>            "product": {
>                "name": "Produkt testowy",
>                "category": {
>                    "id": "258020"
>                },
>                "parameters": [
>                    {
>                        "name": "EAN",
>                        "values": [
>                            "0744861045021"
>                        ]
>                    },
>                    {
>                        "id": "224017",
>                        "values": [
>                            "test 1587459230"
>                        ]
>                    },
>                    {
>                        "id": "202749",
>                        "values": [
>                            "5.9"
>                        ]
>                    },
>                    {
>                        "id": "202869",
>                        "values": [
>                            "512 GB"
>                        ]
>                    },
>                    {
>                        "id": "202829",
>                        "valuesIds": [
>                            "202829_1"
>                        ]
>                    },
>                    {
>                        "id": "202685",
>                        "valuesIds": [
>                            "202685_212929"
>                        ]
>                    },
>                    {
>                        "id": "127448",
>                        "valuesIds": [
>                            "127448_2"
>                        ]
>                    },
>                    {
>                        "id": "202865",
>                        "valuesIds": [
>                            "202865_214109"
>                        ]
>                    },
>                    {
>                        "id": "4388",
>                        "valuesIds": [
>                            "4388_1"
>                        ]
>                    },
>                    {
>                        "id": "202717",
>                        "values": [
>                            100
>                        ]
>                    },
>                    {
>                        "id": "219",
>                        "values": [
>                            "Bluetooth"
>                        ]
>                    },
>                    {
>                        "id": "202821",
>                        "values": [
>                            "Dual SIM"
>                        ]
>                    }
>                ],
>                "images": [
>                    "
>https://...zewnetrzny-adres-pierwszego-obrazka.jpeg
>",
>                    "
>https://...zewnetrzny-adres-drugiego-obrazka.jpeg
>"
>                ]
>            }
>        }
>    ],
>    "images": [
>        "
>https://testowy-adres.com/obrazek.jpg
>"
>    ],
>    "sellingMode": {
>        "price": {
>            "amount": "12.43",
>            "currency": "PLN"
>        }
>    },
>    "stock": {
>        "available": 10
>    },
>    "delivery": {
>        "handlingTime": "PT48H"
>    }
>}
>
>
> Następnie
> skorzystam z metody https://api.allegro.pl/sale/product-offers/{id}
 W tym miejscu doprecyzuję, że wspomiany przez Ciebie endpoint 
 /sale/product-offers/{offerId} dotyczy metody PATCH, czyli edycji 
 istniejącej już oferty. Więcej na jej temat znajdziesz w tym miejscu poradnika. Wcześniej jednak, musisz utworzyć ofertę, 
 zrobisz to za pomocą POST /sale/product-offers, proces tworzenia 
 oferty opisaliśmy w tym poradniku.

**Comment by PrzemyslawLukanowski** [comment]
Nowe produkty dodawaj proszę za pomocą POST /sale/product-offers. Za pomocą PATCH /sale/product-offers/{offerId} możesz edytować istniejące oferty (nie produkty). Otrzymałeś błąd, ponieważ jako {offerID} przekazałeś productId - nie znaleźliśmy w Twoich ofertach takiego identyfikatora, dlatego odpowiedzieliśmy takim komunikatem. Listę swoich ofert i ich ID znajdziesz w odpowiedzi [GET /sale/offers](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-pobrac-moje-oferty-w-rest-api).
