### ISSUE TITLE
DHL CZ Wartość ubezpieczenia musi być większa lub równa wartości kwoty pobrania.

### ISSUE THREAD

**Issue by mtanasiewicz** [allegro/allegro-api#7715]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam,

Mamy problem z nadaniem przesyłki do Czech z COD za pomocą integracji DHL. Dostajemy błąd Wartość ubezpieczenia musi być większa lub równa wartości kwoty pobrania. Sprawdzaliśmy changelog api i nigdzie nie było wzmianki o wprowadzeniu usługi dodatkowej ubezpieczenie, dokumentacja API w tym zakresie, pokazuje tylko COD jako dostępną usługę dodatkową. Do tej pory nadawaliśmy w ten sposób przesyłki do Czech z COD i nie było problemu.

trace-id dla przesyłki, któą udało się nadać 17.09: da8996da8bff4fc9
trace-id dla przesyłi, która obecnie nie chce się nadać: 1307466323446a98

Uprzejmie prosimy o pomoc i rozjaśnienie problemu.

**Comment by MartaNowaczyk** [comment]
Witam, wyjaśniam tę sytuację, wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Dla podanego trace-id wybrana metoda dostawy to "Allegro International Kurier Czechy pobranie", a tutaj wysokość ubezpieczenia musi być równa lub większa od COD.

**Comment by mtanasiewicz** [comment]
Poproszę o wskazanie zatem jak przekazać ubezpieczenie w usługach dodatkowych. Tak jak wspomniałem w wątku, nie ma takiej informacji w dokumentacji API allegro.

**Comment by mtanasiewicz** [comment]
Przeglądając jeszcze raz dokumentację, dotarłem do informacji o tym, że wszystkie dotychczasowe metody tworzenia przesyłek są DEPRECATED i zakończą swój cykl życia w Q4 2024. Jednocześnie możliwość przekazania ubezpieczenia została udostępniona w nowych metodach tworzenia przesyłek. Musimy zatem przejśc na nową implementację, aby móc wysyłać paczki od razu. Problem w tym, że wraz z wprowadzeniem nowych endpointów do zarządzania, wprowadziliście również nowe uprawnienia. Nasz system obsługuje bardzo wielu klientów i wprowadzenie nowych uprawnień dla OAUTH spowoduje konieczność reautentykacji użytkowników w celu nadania nam nowych uprawnień. Ręczne wykonanie tego procesu spowoduje przestoje na magazynach. Czy wprowadzając te uprawnienia, przygotowaliście się może na taką ewentualność? Czy możemy w prosty sposób rozszerzyć uprawnienia OAUTH bez konieczności wymuszenia ponownej autentykacji dla kilkudziesięciu użytkowników?

**Comment by Lukasz-Zurek** [comment]
@mtanasiewicz Na zasobach **/parcel-management**, które są już oznaczone jako **Deprecated** - możesz przekazać kwotę ubezpieczenia w sekcji:

```
      "value": {                                  - deklarowana wartość paczki
        "amount": "2.50",
        "currency": "PLN"
      }
```

Natomiast w tych nowych - jak już zauważyłeś - jest do tego dedykowana sekcja **"insurance"**.

Zgodnie z Oauth - aby móc dodać nowe scope'y, należy przeprowadzić proces autoryzacji ponownie, więc wymuszenie ponownej autentykacji dla użytkowników to niestety jedyne wyjście.

Nawet jeśli w ustawieniach aplikacji dodasz nowe scope'y, należy je uwzględnić podczas ponownego procesu autoryzacji.

**Comment by mtanasiewicz** [comment]
No nic, w takim razie zabieramy się do pracy...
