### ISSUE TITLE
user_name, a zmiana loginu konta

### ISSUE THREAD

**Issue by wstoch** [allegro/allegro-api#7716]
Dzień dobry.
Czy user_name z tokenu jest niezmienny dla danego konta czy zmienia się wraz ze zmianą loginu konta?

**Comment by MaciejFrackowiak** [comment]
Pozostaje niezmienny.

**Comment by wstoch** [comment]
Czy user_name zawsze jest numeryczny, czy lepiej traktować go jako string?

**Comment by MaciejFrackowiak** [comment]
Identyfikator użytkownika (user_name) przyjmuje zawsze wartość numeryczną.
