### ISSUE TITLE
Get offers with missing parameters

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#7717]
Creating new topic, as I did not find it covered in english
I have a offer 7726101930 which has missing required parameters

```
"validation": {
        "errors": [
            {
                "code": "VALIDATION_ERROR",
                "message": "Missing required parameters: 249445, 249446",
                "details": "",
                "path": "parameters",
                "userMessage": "Missing mandatory parameters: Charger included, Headphones included."
            }
        ],
        "warnings": [],
        "validatedAt": "2023-10-04T11:33:56.861Z"
    }
```

I was expecting to use resurce unfilled-parameters to get all the offers with missing parameters, but I am not sure, why it does not work. I returns empty list. I have tried to querry this specific offer, but still did not come back 

https://api.allegro.pl.allegrosandbox.pl/sale/offers/unfilled-parameters?offer.id=7726101930

```
{
    "offers": [],
    "count": 0,
    "totalCount": 0
}
```

Do you have any idea why this does not work for me?

**Comment by MaciejFrackowiak** [comment]
You have only a draft, not an offer. [The resource](https://developer.allegro.pl/documentation/#operation/getOffersUnfilledParametersUsingGET_1) returns offers only if they are active/were finished.

**Comment by ZajdaBear** [comment]
Thanks, but I am not able to activate a draft, as it is missing required parameters, so how could I have an offer, missing required parameters?
Also I understood draft is a offer status :)

**Comment by MaciejFrackowiak** [comment]
You can check the required parameters in the chosen category using [GET /sale/categories/{categoryId/{parameters}](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). If you fill in all the necessary ones, you will not receive an error message.
