### ISSUE TITLE
Brak dostępu do zasobu /shipment-management/delivery-services

### ISSUE THREAD

**Issue by shivson1337** [allegro/allegro-api#7719]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**

Wdrażamy w swoim systemie zmiany dotyczące metod zarządzania przesyłkami WzA.
Zgodnie z informacjami dodaliśmy aplikacji uprawnienia

![image](https://github.com/allegro/allegro-api/assets/60777356/a6f1fb30-aca8-4027-bda1-beee4590073a)

jednak podczas wywoływania metody **/shipment-management/delivery-services** dostajemy zwrotkę

```json
{
    "errors": [
        {
            "code": "AccessDenied",
            "message": "Access is denied",
            "details": null,
            "path": null,
            "userMessage": "No access to the specified resource."
        }
    ]
}
```

Jest coś, na co powinniśmy zwrócić dodatkową uwagę?

**trace-id:** 999c4f8fb7346e51

**Comment by jezewskiBNetrox** [comment]
@shivson1337 Upewnij się, że wygenerowałeś token z tymi uprawnieniami. Uprawnienia są zapisane wewnątrz tokena i przy zmianie uprawnień musisz wygenerować kompletnie nowy (a nie odświeżyć).

**Comment by shivson1337** [comment]
No tak, o najprostszych kwestiach najłatwiej zapomnieć. Dzięki @jezewskiBNetrox ;)
