### ISSUE TITLE
zapytanie na temat /sale/images

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#772]
Dlaczego w dokumentacji nie ma informacji na temat /sale/images ? Ile zdjęć można wysłać naraz ? Mam nadzieje że nie pojedynczo :-)

**Comment by PawelTaberski** [comment]
Jak korzystać z zasobu do przesyłania zdjęć opisaliśmy w poradniku [tutaj](https://developer.allegro.pl/sale/#step-3-images).
