### ISSUE TITLE
Aktywacja konta allegro sandbox

### ISSUE THREAD

**Issue by appsandboxome** [allegro/allegro-api#7720]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x ] ze środowiskiem testowym / with the test environment
 - [x ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Założyłem konto allegro sandbox j.n.

1. Nie przychodzi link aktywacyjny(w spamie nie ma)
2. Zalogowanie nie jest możliwe

Dlatego poproszę o aktywację konta:

login: **app_sandbox_ome**   
email: **sandbox_app@omecon.com.pl**   

dotyczy:    
allegro.pl.allegrosandbox.pl

**Comment by MaciejFrackowiak** [comment]
Niestety, niezbędne jest, abyś potwierdził rejestrację konta na podstawie odnośnika z przesłanego przez nas maila. Jak widzę ostatnia wysyłka miała miejsce dziś o 13:37. Jeżeli nie otrzymałeś wiadomości to alternatywą jest próba rejestracji konta na inny adres email.

**Comment by appsandboxome** [comment]
Dostałem na email w/w traść z github'a ale linku aktywacyjnego już nie,

Czy można powtórzyć wysłanie w/w linku?

**Comment by MaciejFrackowiak** [comment]
Link otrzymasz wyłącznie próbując zarejestrować konto na "allegro.pl.allegrosandbox.pl" - nie mam możliwości jego ręcznego przesłania.

**Comment by appsandboxome** [comment]
Udało się założyć na w/w email inne konto, przyszedł link aktywacyjny
dziękuję za wsparcie
/close

**Comment by Nowaelektro23** [comment]
Cześć;
Mam problem z aktywacją sprzedaży na koncie Nowaelektro23 w Sandbox?
Weryfikacja konta i firmy trwa. Pytanie ile czasu?

**Comment by MaciejFrackowiak** [comment]
@Nowaelektro23 Zweryfikowałem Twoje konto.
