### ISSUE TITLE
Sens ustawiania handlingTime

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#7721]
Czy jest jakikolwiek sens ustawiania / aktualizacji `handlingTime` w ofertach? Na froncie i tak pokazujecie co chcecie

**Comment by PrzemyslawLukanowski** [comment]
Termin przewidywanej dostawy wyliczamy na podstawie obliczeń, szerzej opisuje to [artykuł](https://allegro.pl/dla-sprzedajacych/przewidywany-czas-dostawy-twojej-przesylki-AVlrm8wY3Sg#jak-obliczamy-czas-wysylki-ktory-wyswietlamy-w-twoich-ofertach) na stronie dla sprzedających, jednak informację, którą przekazujesz w `handlingTime`, zawsze uwzględniamy w ofercie w miejscu zaznaczonym poniżej, na zakładce "Dostawa":

<img width="399" alt="Zrzut ekranu 2023-10-6 o 08 20 00" src="https://github.com/allegro/allegro-api/assets/51473661/6ed6f058-c856-4c7b-b831-fb5807cf3462">

**Comment by cyfranT** [comment]
Podpisujemy się też pod bezsensownością tego jak działa wyświetlanie tej informacji na froncie.
handling time jest gdzieś na końcu w szczególach, a klienci i tak patrzą na informację widoczną bezpośrednio przy ofercie, która nie ma sie nijak również w naszym przypadku do tego jak jesteśmy AKTUALNIE w stanie realizować wysyłki (co deklarujemy w handlingTime)

**Comment by TimothyKoval** [comment]
Dodajcie zasób, który będzie umożliwiał asynchroniczną zmianę handlingTime i możliwość wyłączenia wyświetlania wyliczonego czasu dostawy per konto; jak ktoś jest ogarnięty to sobie będzie aktualizował czas dostawy w zależności od własnych warunków
