### ISSUE TITLE
Dostęp do klienta DHL

### ISSUE THREAD

**Issue by Warmax24** [allegro/allegro-api#7722]
Dzień dobry, podpisaliśmy umowę z DHL, otrzymaliśmy swój nr klienta. Korzystamy z Wapro MAG, chcieliśmy tam podać dane dostępowe do API żeby móc nadawać przesyłki SMART, DHL dał nam info, że pod te przesyłki mamy korzystać nie z naszego numeru klienta, tylko z numeru przypisanego dla Allegro czyli: 2477852, a po login i hasło API do tego numeru mam się zgłosić właśnie do Allegro. Po konsultacji mailowej z obsługą Allegro poproszono mnie o zgłoszenie tej kwestii tutaj na forum, co właśnie czynię.

**Comment by PrzemyslawLukanowski** [comment]
Nie posiadamy i nie generujemy danych do API stricte dla określonych numerów klientów DHL, więc niestety nie wiemy, o jakie dokładnie informacje chodzi. Sugeruję, aby w tym temacie skontaktować się bezpośrednio z Wapro MAG, po to , aby wyjaśnić, jak dokładnie wygląda konfiguracja tej usługi w narzędziu. Jeśli chodzi o nasze API, to wysyłka przesyłek SMART nie powinna wymagać generowania nowych danych, ponieważ informacja o tym, czy zamówienie jest typu SMART, znajduje się bezpośrednio w danych zamówienia.
