### ISSUE TITLE
Gdzie ustawić wymagany numer iban

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#7723]
Witam, przy jednej z metod dostaw allegro one otrzymujemy komunikat : Wybrana metoda dostawy wymaga podania poprawnego numeru iban [This delivery option requires a correct IBAN]'. Gdzie powinno się uzupełnić ten numer?

**Comment by jezewskiBNetrox** [comment]
@Maciej-Wilkosz Trzeba uzupełnić numer konta do wypłat w **Ustawienia wypłat**. Błąd jest też mylący. Jeżeli numer konta do wpłat na koncie Allegro jest inny niż przesłany w API, to wyskakuje też ten błąd.

@MaciejFrackowiak Prosiłbym o usprawnienie tego komunikatu, ponieważ wyskakuje on mimo podania prawidłowego numeru IBAN ale przez to, że nie zgadza on się z numerem podanym na koncie.

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak jak opisał @jezewskiBNetrox - musisz uzupełnić numer konta w zakładce [Ustawienia wypłat](https://allegro.pl/moje-allegro/sprzedaz/ustawienia-wyplat). 

@jezewskiBNetrox Dziękuję za sugestię, przekażę do zespołu odpowiedzialnego za usługę.
