### ISSUE TITLE
Kampanie na rynkach zagranicznych

### ISSUE THREAD

**Issue by Darayavus** [allegro/allegro-api#7724]
Cześć, 
czy zasób /sale/badges zwraca też informacje o marketplaceId, jeżeli oferta o danym id bierze udział w kampaniach na rynku zagranicznym?
Czy można to rozpoznać jedynie przez campaign.id?

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Nie, zasób nie zwraca informacji o rynku zagranicznym. Obecnie poprzez API można otrzymać tylko informacje dot. kampanii dla serwisu allegro-pl.

**Comment by Darayavus** [comment]
OK, dziękuję za odpowiedź
