### ISSUE TITLE
Identyfikator zamówienia allegro w Sandbox

### ISSUE THREAD

**Issue by Nowaelektro23** [allegro/allegro-api#7725]
INPOST wymaga identyfikatora [numeru] zamówienia w schemacie z adresem mail allegro.
 Natomiast w Sandbox identyfikator [numer] zamówienia nie zawiera adresu mail. 
Jak sobie z tym poradzić?

**Comment by PrzemyslawLukanowski** [comment]
Jeśli chodzi o format zamówienia na obu środowiskach, to jest to UUID. Zwracamy mail kupującego na środowisku testowym - różnica polega na tym, że zamiast w domenie @allegromail.pl, zwracamy go w @user.allegrogroup.pl.

**Comment by PrzemyslawLukanowski** [comment]
Powinno wystarczyć, jeśli przekażesz wyłącznie mail kupującego czyli xxxxx+xxxxx@user.allegrogroup.pl, jednak dla pewności możesz dopytać wsparcie ze strony InPost.

**Comment by Nowaelektro23** [comment]
Coś jednak jest nie tak. Do numer zamówienia allegro na sandbox jako kupujący dodałem @user.allegrogroup.pl
Otrzymałem ciągi znaków jak niżej. Inpost środowisko testowe odbija mi komunikat, iż niewłaściwy numer zamówienia.
dd349fe0-6432-11ee-b8a5-d72fcdac8654@user.allegrogroup.pl
b5aefab0-6432-11ee-b8a5-d72fcdac8654@user.allegrogroup.pl
880e3940-6432-11ee-b8a5-d72fcdac8654@user.allegrogroup.pl
9eb018e0-6431-11ee-b8a5-d72fcdac8654@user.allegrogroup.pl
1ea646a0-6432-11ee-b8a5-d72fcdac8654@user.allegrogroup.pl

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie znamy dokładnie środowiska testowego InPostu, dlatego najlepiej będzie, jeśli informacji zaczerpniesz bezpośrednio ze źródła. Tak jak wspomniałem, wg mojej wiedzy powinno wystarczyć przekazanie samego maila z zamówienia. Czyli zamiast dd349fe0-6432-11ee-b8a5-d72fcdac8654@user.allegrogroup.pl przekaż dokładnie taki sam adres mailowy, jaki otrzymujesz w polu `buyer.email`.
