### ISSUE TITLE
NOT_SUPPORTED_BY_CARRIER

### ISSUE THREAD

**Issue by Marek-ShopStore** [allegro/allegro-api#7726]
Hello,
we try using https://api.{environment}/parcel-management/parcels/protocol
First problem is with Zasilkovna we get error: NOT_SUPPORTED_BY_CARRIER
We do not need to order pickup, we already have pickup arranged with them by separate contract. 

Pickup guy is able to get packages for Allegro but problem is that he refuses to scan them one by one if we have more than 50 packages.
Same problem is if we want to put packages to Pickup points - they refuse to scan more than 20 packages.
We are looking at 100+ packages at Monday now and are expecting 200-400 next month on Mondays so we need you to solve it or we won't be able to send it.

We need protocol with barcode one Barcode and list of packages - Packeta API have methods for it.

Second problem is with WeDo, we get error: BAD_REQUEST 
(for example for parcels parcelId'=>['fb492b4b-81a2-41ed-adb1-b959c7fa54fb','f4f8c879-67fb-4523-b417-d8d464b96ba4'])

**Comment by PrzemyslawLukanowski** [comment]
Hello, I verified this topic with the team that is responsible for Ship With Allegro and received confirmation that neither, Zasilkovna nor WeDo support parcel protocols, so it's not possible to generate such a document. This is not our limitation, but those carriers.

We will also verify, why we have returned the 400 status code in the second case and will correct it.

**Comment by Marek-ShopStore** [comment]
Hello,
Zasilkovna definitely supports shipments that allow you to produce protocol.

I have implemented it twice:
https://docs.packetery.com/03-creating-packets/06-packetery-api-reference.html#toc-createshipment
createShipment()

that returns: ShipmentIdDetail with following data:
id
**barcode** - it's what delivery guy needs.

You can get all packages in shipment calling:
shipmentPackets(string $shipmentId)
you will get collection of packages

Than you just render A4 with barcode and table with packages.

**Comment by PrzemyslawLukanowski** [comment]
I forwarded this info to our Ship With Allegro Team but currently, due to limitations on our side, we cannot introduce such "custom" protocols.
