### ISSUE TITLE
 https://api.allegro.pl/shipment-management/shipments/create-commands The remote server returned an error: (400)

### ISSUE THREAD

**Issue by vojteka100** [allegro/allegro-api#7727]
Witam,

 Robię obecnie migrację ze "starej" funkcji do obsługi paczki do nowej funcji API  https://api.allegro.pl/shipment-management/shipments/create-commands  i mam następujący komunikt:  
The remote server returned an error: (400) Bad Request

 token poprawny.
 method: POST

 headers:

  webClient.Headers("Accept") = "application/vnd.allegro.public.v1+json"
  webClient.Headers("Content-Type") = "application/vnd.allegro.public.v1+json"
  webClient.Headers("Authorization") = "Bearer " & token

 payload:
{
  "commandId": "915d4c5e-880a-4607-af5a-5109bf50a6f4",
  "input": {
    "deliveryMethodId": "0d83955a-4297-4169-adef-9790d53b11ff",
    "sender": {
      "name": "Mat.pl  - Rybak",
      "company": "Mat.pl A.Lat",
      "street": "Półanki",
      "streetNumber": "80",
      "postalCode": "20-740",
      "city": "Kokotów",
      "countryCode": "PL",
      "email": "sklep@mata.pl",
      "phone": "512902277"
    },
    "receiver": {
      "name": "A Lat",
      "street": "Centrum 51",
      "streetNumber": "51",
      "postalCode": "20-786",
      "city": "Kokotów",
      "countryCode": "PL",
      "email": "btgaaf8otm+30a198290@allegromail.pl",
      "phone": "502494682"
    },
    "referenceNumber": "123",
    "description": "Art. Motoryzacyjne",
    "packages": [
      {
        "type": "PACKAGE",
        "lenght": {
          "value": "10",
          "unit": "CENTIMETER"
        },
        "width": {
          "value": "30",
          "unit": "CENTIMETER"
        },
        "height": {
          "value": "30",
          "unit": "CENTIMETER"
        },
        "weight": {
          "value": "10",
          "unit": "KILOGRAM"
        }
      }
    ],
    "insurance": {
      "amount": "51",
      "currency": "PLN"
    },
    "labelFormat": "PDF"
  }
}

Nie mogę namierzyć  błędu ? Proszę o pomoc.

**Comment by PrzemyslawLukanowski** [comment]
W strukturze masz dwa drobne błędy związane z nazwami pól i wartości:

- `packages.length` zamiast `packages.lenght`,
- wartość w `weight.unit `- zamiast `KILOGRAM` powinno być `KILOGRAMS`.

**Comment by vojteka100** [comment]
Trace id do mojej próby powyżej.

trace-id: a3d7fb4b51c37836
< content-type: application/json; charset=utf-8
content-type: application/json; charset=utf-8
< content-length: 147
content-length: 147
< date: Mon, 09 Oct 2023 15:49:17 GMT
date: Mon, 09 Oct 2023 15:49:17 GMT


Pozdrawiam.

**Comment by PrzemyslawLukanowski** [comment]
Korzystasz z adresu `/shipment-management/shipments/create-command`, a prawidłowy to `/shipment-management/shipments/create-commands` ("commands" na końcu).

**Comment by vojteka100** [comment]
Dziękuję za pomoc. Działa :)
