### ISSUE TITLE
Powiązane konta Allegro

### ISSUE THREAD

**Issue by toolsworld1** [allegro/allegro-api#7728]
Dzień dobry.

Mam pytanie dotyczące powiązanych kont w Allegro.

Czy dla każdego konta powiązanego z kontem głównym trzeba tworzyć osobne połączenia API czy można zarządzać wszystkim z jednego miejsca?

Będę wdzięczny za odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Dla każdego konta musisz utworzyć osobne połączenie, tzn. wygenerować osobny token, stricte dla danego użytkownika.
