### ISSUE TITLE
[REST] Nieprawidłowy pickupPoint dla paczki w ruchu

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#773]
Dzień dobry,

oto struktura pikckupPoint dla Paczki w RUCHu, i przykładowe dane:

            [pickupPoint] => stdClass Object
                (
                    [id] => 684860
                    [name] => PACZKA w RUCHu: KT-684860-76-62
                    [address] => stdClass Object
                        (
                            [street] => Prądnicka 50
                            [zipCode] => 30-202
                            [city] => Kraków
                        )

                )

jest tutaj błąd, otóz id nie powinno być numeryczne, tylko powinno zawierać w sobie unikalny symbol punktu odbioru ruchu (czyli KT-684860-76-62 zamiast 684860), tak jak jest to przy Inpoście, przykład:

            [pickupPoint] => stdClass Object
                (
                    [id] => LOD31A
                    [name] => Paczkomat LOD31A
                    [description] => Przy markecie Carrefour
                    [address] => stdClass Object
                        (
                            [street] => Szparagowa 7
                            [zipCode] => 91-211
                            [city] => Łódź
                        )

                )

**Comment by PawelTaberski** [comment]
Wygląda to na błąd. Przekazałem Twoją informację do odpowiedniego zespołu. Proszę o cierpliwość.

**Comment by tztztztz** [comment]
Jeszcze informacja - chodzi o serwis produkcyjny allegro, nie testowy, na testowym nie wiem jak to wygląda.

**Comment by PrzemekTurek2017** [comment]
Od tamtej pory nic się nie zmieniło? Będą poprawione te `id` czy parsować `name` ?
Bo response dalej wygląda tak :
```
{
  "id": "961334"
  "name": "PACZKA w RUCHu: KT-961334-82-28"
  "description": null
  "address": {
    "street": "Rzeźnicza 17 przy"
    "zipCode": "31-540"
    "city": "Kraków"
  }
}
```

**Comment by PawelTaberski** [comment]
Otrzymałem informacje, że takie dane otrzymujemy i w taki sposób jak dotychczas będą prezentowane.
