### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by lukasz-ideaware** [allegro/allegro-api#7730]
Dzień dobry,
proszę o aktywację konta sandbox o loginie 'interaktywny'

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.

**Comment by lukasz-ideaware** [comment]
Cześć. Dziękuje. Mam jednak problem z dostaniem się do ep sale/offers - otrzymuję 403
[
    "errors" => [
      [
        "code" => "AccessDenied",
        "message" => "Access is denied",
        "details" => null,
        "path" => null,
        "userMessage" => "No access to the specified resource.",
      ],
    ],
  ]
  
  

Czy muszę zrobić coś jeszcze by dostać się do ep z uprawnieniami allegro:api:sale:offers:read? Ofertę z poziomu panelu udało mi się zrobić

**Comment by PrzemyslawLukanowski** [comment]
Prawdopodobnie token uzyskałeś w ramach autoryzacji [client_credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow) - taki token nie posiada kontekstu użytkownika, dlatego nie możesz wystawić ani pobrać żadnej oferty. Musisz skorzystać z autoryzacji typu [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow).

**Comment by lukasz-ideaware** [comment]
Używam authorization_code.

Przy generowaniu linku do oauth: 

 public static function loginUrl()
    {
        return config('allegro.oauth_url') . 'auth/oauth/authorize?response_type=code&client_id=' . config('allegro.client_id') . '&redirect_uri=' . route('allegro.callback');
    }
    
    przy generowaniu tokena:
    
     public function login($code)
    {
        $query = http_build_query([
            'grant_type' => 'authorization_code',
            'code' => $code,
            'redirect_uri' => route('allegro.callback')
        ]);

        $response = Http::allegroAuth()

            ->post(
                '/auth/oauth/token?' . $query,

            );

        if ($response->ok()) {
            $data = $response->json();
            $accessToken = $data['access_token'];
            $refreshToken = $data['refresh_token'];
            $expire = $data['expires_in'];

            self::setTokens($accessToken, $refreshToken, $expire);
            return true;
        }
        return false;
    }

**Comment by lukasz-ideaware** [comment]
Dodam jeszcze, że w polu scope mam allegro:api:sale:offers:read

**Comment by PrzemyslawLukanowski** [comment]
Dodaj proszę nagłówek Accept z wartością application/vnd.allegro.public.v1+json
 - brak tej informacji jest źródłem problemu.

**Comment by lukasz-ideaware** [comment]
Nagłowek miałem dodany w kodzie wcześniej:

 Http::macro('allegroAuth', function () {
            return Http::baseUrl(config('allegro.oauth_url'))
                ->contentType('application/vnd.allegro.public.v1+json')
                ->withBasicAuth(config('allegro.client_id'), config('allegro.secret'));
        });

Http::macro('allegro', function () {
            return Http::baseUrl(config('allegro.api_url'))
                ->contentType('application/vnd.allegro.public.v1+json')
                ->withToken(Cache::get('allegro_access_token'));
        });

dla pobierania ofert używam maco 'allegro'

public function offers()
    {
        $response = Http::allegro()->get('sale/offers');
        //  dd($response);
        return $response->json();
    }

**Comment by PrzemyslawLukanowski** [comment]
Z tego co widzę, to posiadasz jedynie nagłówek Content-Type, musisz jeszcze dodać Accept.

**Comment by lukasz-ideaware** [comment]
Dzięki, pomogło :)
