### ISSUE TITLE
Dodawanie produktu z pliku JSON

### ISSUE THREAD

**Issue by stalkerGH** [allegro/allegro-api#7732]
Dzień dobry.

Od kilku dni próbuję okiełznać API Allegro w ramach piaskownicy (sandbox). Do tej pory udało mi się poprawnie zarejestrować aplikację i przejść przez wszystkie kroki umożliwiające odczyt oferty. Ofertę najpierw utworzyłem ręcznie według schematu używanego na "produkcyjnym" koncie firmowym, a następnie odczytałem ją za pomocą curl, by poznać strukturę pliku JSON. 

Teraz próbuję opanować dwa zagadnienia:

1) dodawanie własnych produktów - zajmuję się wydrukami, które nie mają i nie muszą mieć według aktualnych zasad Allegro numerów EAN, więc przy ręcznym dodawaniu oferty jednocześnie dodawany jest nowy produkt.

Pytania podstawowe, zanim przejdę do kolejnych kroków: 

a) w jaki sposób dodać nowy produkt,
b) jak poznać jego identyfikator po opublikowaniu, by powiązać go z ofertą.

2) przesyłanie zawartości pliku JSON - wciąż mam błąd `{"errors":[{"code":"JsonMappingException","message":"Message is not readable.","details":null,"path":"description.sections[1].items[1].url","userMessage":"Request contains invalid data. Contact the application author."}]}`

Próbowałem załączać zawartość pliku JSON bezpośrednio do zapytania curl tak jak jest to pokazane w przykładzie https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem, czyli `-d '<tutaj zawartość JSON>'`. Próbowałem również podawać ścieżkę do pliku według dokumentacji curl, tj. `-d @nazwa-pliku.json`, ale komunikat o błędzie jest wciąż ten sam.

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry,

1. Za pomocą POST /sale/product-offers dodasz produkt, który będzie od razu połączony z ofertą. Jego identyfikator zwrócimy w odpowiedzi w polu `productSet.product.id`, jednak - jak wspomniałem - przy tym podejściu nie musisz dodatkowo wiązać go z ofertą, zrobimy to automatycznie. Szczegóły opisaliśmy [w tej części](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-nowym-produktem) poradnika. Jeśli jednak nie wszystko jest do końca jasne, napisz proszę, co wymaga doprecyzowania.

Produkt możesz dodać także za pomocą POST /sale/product-proposals. W tym przypadku, w kolejnym kroku, gdy tworzysz ofertę, musisz dodatkowo zawrzeć informację o nim. Szczegóły tworzenia produktu dla tego podejścia opisaliśmy [w tej części ](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-utworzyc-nowy-produkt)poradnika.

2. Adres w path wskazuje na problem z wartością w polu description.sections[1].items[1].url - upewnij się, że przesyłasz tam prawidłowy adres zdjęcia, czyli struktura powinna wyglądać np. tak:
```
... {
            "items": [{
                "type": "IMAGE",
                "url": "{adres zdjęcia}"
     } ...
```
Gdyby problem wciąż występował, prześlij proszę przykładowe trace-id operacji - w ten sposób przenalizujemy strukturę, którą do nas wysyłasz.

**Comment by stalkerGH** [comment]
Dziękuję za odpowiedź. Rzeczywiście problem leżał w jednym z linków do zdjęć "zjadłem" literę 'h' w 'https'. Teraz import rusza, nawet przy wywołaniu z pliku .json, ale pojawił się kłopot z formatowaniem tekstu w opisie:

''{"errors":[{"code":"VALIDATION_ERROR","message":"Invalid tag: \"ul\", allowed tags: {b}","details":"Invalid value: <p><ul><li><b>Motyw:</b> kwiaty, rośliny, botanika</li><li>Styl: drzeworyt, malarstwo kacho-e</li><li>Autor: Konan Tanigami, Japonia</li><li><b>Format:</b> 21x30 cm (A4), bez oprawy</li><li><b>Papier:</b> matowy, powlekany, 230 g/m2. Pochodzący z odpowiedzialnych źródeł (certyfikat FSC)</li></ul></p>","path":"description.sections[0].items[1].content","userMessage":"Invalid tag: \"ul\", allowed tags: {b}"}]}''

Mniej więcej rozumiem, w czym leży problem, ale proszę o przekierowanie do dokumentacji, w której będzie wyraźnie opisana struktura logiczna opisu i tagów HTML.

**Comment by PrzemyslawLukanowski** [comment]
Błąd występuje, ponieważ listę `<ul>` próbujesz umieścić w ramach akapitu `<p>` - taki zapis nie jest dozwolony i wynika to z ogólnych założeń znaczników HTML. Więcej informacji na temat prawidłowej struktury znajdziesz [w tej części](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty) poradnika.
