### ISSUE TITLE
How to check price converter via API

### ISSUE THREAD

**Issue by MKI-Miro** [allegro/allegro-api#7733]
Hi,

When I edit product offer on for allegro.cz there is option to check  price converter (Przelicznik cen 1 PLN = 5.311311 CZK), but I dont want to do it manually. Is there an option in API to check it for all products?

Thank you

**Comment by PrzemyslawLukanowski** [comment]
If you're asking if is there a way to enable a price converter via API, then yes, you can do so. [Here](https://developer.allegro.pl/tutorials/listing-and-managing-offers-on-foreign-marketplaces-7GndGjeAATn#managing-price-automation-in-offers), you can find all of the details (if you want to see the page in English, please switch the language settings in the top-right corner).

**Comment by MKI-Miro** [comment]
Thank you very much for quick answer.
