### ISSUE TITLE
Brak możliwości wystawienia przedmiotu

### ISSUE THREAD

**Issue by absoftware** [allegro/allegro-api#7734]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Próbuję zintegrować się z modułem `shipment-management` przez REST API, ale do wystawienia przesyłki jest niezbędne jakieś fałszywe zamówienie w sandboxie identyfikowane mailem allegrowym receivera. Bez tego otrzymuję w odpowiedzi dla **GET** `/shipment-management/shipments/create-commands/%s` coś takiego:

```
{
    "commandId": "8a0d6c97-8f56-408e-a7f8-c89c9a48004d",
    "status": "ERROR",
    "errors": [
        {
            "code": "ANOTHER_SERVICE_NOT_AVAILABLE",
            "message": "One of required services is unavailable. Try again later.",
            "details": "One of required services is unavailable. Try again later.",
            "path": null,
            "userMessage": "Jeden z wymaganych serwis\u00f3w, do poprawnego dzia\u0142ania, jest niedost\u0119pny. Spr\u00f3buj ponownie za moment."
        }
    ],
    "shipmentId": null
}
```

Więc próbuję utworzyć zamówienie na koncie testowym `106186627` w następujący sposób:

- Idę do https://allegro.pl.allegrosandbox.pl/
- Potem user dropdown -> sprzedaż -> wystaw przedmiot

**Spodziewane:** Mogę wystawić sprzedaż na stronie https://allegrolokalnie.pl.allegrosandbox.pl/oferty/wystaw

**Aktualnie:** Strona https://allegrolokalnie.pl.allegrosandbox.pl/oferty/wystaw zgłasza błąd `This site can’t be reached`

Proszę o wskazówki jak mogę obejść problem lub o naprawienie tej strony. Czy na przykład muszę je utworzyć poprzez REST API, to wtedy się uda? Prościej by było wyklikać. Z góry dzięki.

Podobne issues:

- https://github.com/allegro/allegro-api/issues/7551
- https://github.com/allegro/allegro-api/issues/7211#issuecomment-1592967212
- https://github.com/allegro/allegro-api/issues/6704
- https://github.com/allegro/allegro-api/issues/1046 (czyżbym nie aktywował konta? bo szczerze mówiąc, nie mogłem tego zrobić przez system płatności w sandbox, bo też otrzymuję `This site can’t be reached`)

**Comment by absoftware** [comment]
**GET** `/shipment-management/delivery-services` zwraca HTTP 500:

```
HTTP 500
x-frame-options: DENY
trace-id: 45d3f08f8508d05d

{
    "errors": [
        {
            "code": "INTERNAL_SERVER_ERROR",
            "message": "Internal server error.",
            "details": null,
            "path": null,
            "userMessage": "Internal server error. Try again in a few minutes."
        }
    ]
}
```

**Comment by Lukasz-Zurek** [comment]
Tak, Twoje konto testowe ma status zwykłego i nie jest w pełni aktywne. Dlatego w pierwszej kolejności przekształć swoje konto na firmowe. Zrobisz to [tutaj](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta). Następnie przejdź do [ustawień wypłat](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty), uzupełnij dane i skorzystaj z naszego symulatora płatności.

Dodam, że jeśli nadal będziesz miał problem z wystawianiem na sandboxie, użyj tego linka: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie

**Comment by absoftware** [comment]
@Lukasz-Zurek Dziękuję za szybką odpowiedź. Przy wystawianiu pierwszej sprzedaży otrzymuję komunikat "Aby aktywować sprzedaż zweryfikuj konto." Czy możecie mi z tym pomóc? To wymaga Waszego zatwierdzenia?

**Comment by Lukasz-Zurek** [comment]
@absoftware Tak, aktywowałem już i zweryfikowałem Twoje konto na sandboxie. Teraz powinno być ok.

**Comment by absoftware** [comment]
@Lukasz-Zurek Dziękuję za pomoc. Rzeczywiście po zweryfikowaniu przestałem widzieć HTTP 500 przy opcjach z opisu tego issue.

Czy w czymś przeszkadza, że mam 80% konfiguracji sprzedaży? Mówi mi, że nie mam "Zweryfikuj dane firmy", a reszta jest.

Jednak jak Tworzę nową przesyłkę przez API, to otrzymuję status:

```
{
    "commandId": "54507825-1d90-48f0-b398-cee18fe6bbbd",
    "status": "ERROR",
    "errors":
    [
        {
            "code": "ANOTHER_SERVICE_NOT_AVAILABLE",
            "message": "One of required services is unavailable. Try again later.",
            "details": "One of required services is unavailable. Try again later.",
            "path": null,
            "userMessage": "Jeden z wymaganych serwisów, do poprawnego działania, jest niedostępny. Spróbuj ponownie za moment."
        }
    ],
    "shipmentId": null
}
```

Czy brak własnej umowy z przewoźnikiem jest problemem? Idzie obejść brakujące klucze dostępowe przewoźników? Chciałbym się skupić na Allegro One.

**Comment by absoftware** [comment]
Ok, jak poprawiłem receiver's email to otrzymałem już bardziej komunikatywny error:

```
{
        "commandId": "6d965925-3808-429a-bb83-1ae2034d59c0",
        "status": "ERROR",
        "errors":
        [
            {
                "code": "DELIVERY_METHOD_NOT_AVAILABLE",
                "message": "Delivery Method is not available for this order",
                "details": "Delivery Method is not available for this order",
                "path": "deliveryMethodId",
                "userMessage": "Wybrana metoda dostawy nie obsługuje tego zamówienia"
            }
        ],
        "shipmentId": null
    }
```

**Comment by Lukasz-Zurek** [comment]
@absoftware Z tego co widzę w logach - w procesie tworzenia paczki wybrałeś inną usługę dostawy aniżeli wybrana przez Kupującego metoda dostawy. Upewnij się co do jej poprawności.

**Comment by absoftware** [comment]
@Lukasz-Zurek Dziękuję za pomoc. Myślę, że ticket może być zamknięty.
