### ISSUE TITLE
Błąd podczas wystawiania aukcji po numerze GTIN

### ISSUE THREAD

**Issue by Vandeetta** [allegro/allegro-api#7735]
Przy próbie wystawienia aukcji otrzymuje taki komunikat, nie widzę takiego błędu w dokumentacji ani w żadnym wątku tutaj na githubie

Request failed with status code 403. Response:
{'expires': '0', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'x-xss-protection': '1; mode=block', 'pragma': 'no-cache', 'x-frame-options': 'DENY', 'trace-id': '57dc56daed562ce2', 'date': 'Tue, 10 Oct 2023 06:33:00 GMT', 'strict-transport-security': 'max-age=31536000 ; includeSubDomains', 'x-content-type-options': 'nosniff', 'content-type': 'application/json; charset=UTF-8', 'content-length': '196'}
{"errors":[{"code":"OfferAccessDeniedException","message":"Forbidden","details":null,"path":"","userMessage":"Access denied. You are not authorized to perform operations on the indicated offer"}]}

**Comment by Lukasz-Zurek** [comment]
Zwracamy powyższy błąd, ponieważ próbujesz wystawić ofertę z poziomu konta zwykłego i tu potrzebne będzie przekonwertowanie go na konto firmowe.
