### ISSUE TITLE
Wartość niejednoznacza dla parametru typ (choinki)

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#7739]
Witam, prosił bym o wyjaśnienie z jakiego powodu występuje podany błąd. 

{"errors":[{"code":"ProductValidationException","message":"Nieprawidłowe wartości parametrów: [parameter = Typ [ Wartość niejednoznaczna - inna]]","details":null,"path":"productSet[0].product","userMessage":"Nieprawidłowe wartości parametrów: [parameter = Typ [ Wartość niejednoznaczna - inna]]"}]}

Natomiast API wskazuje ,że dla podanego parametru istnieje możliwość wybrania wartości niejednoznacznej (parametr id 248464, wartość "inna" id 248464_912047)

traceid: 96a78a59fc3ac819

**Comment by Lukasz-Zurek** [comment]
Mamy tutaj nieco inną sytuację, gdzie dla tego parametru mamy:

`"customValuesEnabled": false` - czyli nie przekażesz własnej wartości, przy jednoczesnym wyborze `248464_912047`.

Z drugiej strony, na liście słownikowej, gdzie są wartości m.in. jodła, sosna, nie mamy takiej wartości, którą chciałbyś przekazać w żądaniu. Natomiast w tej kategorii, aby produkt został prawidłowo utworzony, potrzebujemy konkretnej informacji, a przekazanie wartości `"inna"` nie będzie wystarczające.

Dodam, że powyższy parametr nie jest obowiązkowy, również dla utworzenia produktu. Ponadto oferta jaką próbujesz wystawić odnosi się do choinki filcowej dla dzieci - rozważyłbym w tej sytuacji nieprzekazywanie powyższego parametru, lub ewentualną zmianę kategorii na inną.
