### ISSUE TITLE
Czy da się stworzyć aplikację mobilną w języku Kotlin korzystającą z Api?

### ISSUE THREAD

**Issue by MikolajMalcherek** [allegro/allegro-api#7740]
Chciałbym zapytać, czy istnieje możliwość aby stworzyć aplikację mobilną w języku Kotlin korzystającą z Api. Zauważyłem, że po rejestracji aplikacji na Allegro jej typ to Web. Stąd też pojawiło się u mnie pytanie czy będzie to łatwe do zrobienia. Jeśli nie da się tego zrobić bezpośrednio, być może da się stworzyć własne api w, np. Pythonie korzystające z api Allegro a następnie wykorzystać je w komunikacji z aplikacją mobilną. Będę bardzo wdzięczny za każdą podpowiedź.
Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Jeżeli chodzi o nasze Allegro API, jak już zauważyłeś - podczas [rejestracji nowej aplikacji](https://apps.developer.allegro.pl/new) możesz wybrać dwa typy:

- mającą dostęp do przeglądarki (authorization_code),
- bez dostępu do przeglądarki, np. TV (device_code).

Wszystkie dane wysyłane są i odbierane z API w [formacie JSON](https://en.wikipedia.org/wiki/JSON). Kwestia korzystania z innych języków programowania, czy też parsowania danych json np. do Android - leży już w gestii twórców. 

Być może któryś z forumowiczów realizował już podobny projekt i mógłby podzielić się z Tobą konkretnymi spostrzeżeniami i sugestiami.

**Comment by jezewskiBNetrox** [comment]
@MikolajMalcherek Nie jestem devem Javy ale jak można by **nie korzystać z API** w Kotlinie? Przecież to jedna z bazowych rzeczy w dzisiejszym devie. 

Pierwszy przykładowy przegląd bibliotek, nawet nowe JDK posiada własne HttpClient:
https://ryanharrison.co.uk/2018/06/15/make-http-requests-kotlin.html

Zależy też, co chcesz robić i o jaką formę integracji Ci chodzi. API służy głównie do integracji sprzedaży. Linki do dokumentacji API podrzucił Pan z Allegro powyżej.
