### ISSUE TITLE
WzA, AlegroOne, Shipment management, 400, Nie można prawidłowo sparsować przesłanego obiektu

### ISSUE THREAD

**Issue by Mojeallegro123** [allegro/allegro-api#7741]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dzień dobry.
Podczas tworzenia paczki w nowym API Shipment management cały czas dostajemy ten sam błąd:
               (
                    [code] => ERROR
                    [message] => The request body could not be parsed correctly
                    [details] => 
                    [path] => input.sender.countryCode
                    [userMessage] => Nie można prawidłowo sparsować przesłanego obiektu
                )

Podaję trace-id: a9830fd2b12af7eb

Przykładowy equest jest taki:
{
"commandId": "416856d5-5c3b-11ee-9136-002590a6a63b",
"input": {
"deliveryMethodId": "1decb356-c292-46d2-a723-f260691b856f",
"sender": {
"company": "FIRMA Sp. z o.o.",
"street": "Xxxxxxxx",
"streetNumber": "111",
"postalCode": "05-506",
"city": "Xxxxxxx Xxxxxxxx",
"countryСode": "PL",
"email": "xxxxxx@gmail.com",
"phone": "777777777"
},
"receiver": {
"name": "XXXXX XXXXX",
"street": "Xxxx",
"streetNumber": "17",
"postalCode": "05-500",
"city": "XXXX XXXXX",
"countryСode": "PL",
"email": "3zo9k4clr7+7f7be1df8@allegromail.pl",
"phone": "888888888"
},
 
"referenceNumber": "0033671",
"packages": [
{
"type": "PACKAGE",
"length": {
"value": 50,
"unit": "CENTIMETER"
},
"width": {
"value": 9,
"unit": "CENTIMETER"
},
"height": {
"value": 4,
"unit": "CENTIMETER"
},
"weight": {
"value": 0.27,
"unit": "KILOGRAMS"
}
}
],
"cashOnDelivery": {
"amount": "32.95",
"currency": "PLN",
"ownerName": "FIRMA Sp. z o.o.",
"iban": "PL11222233334444555566667777"
},
"labelFormat": "PDF"
}

Proszę o podpowiedź co jest nie tak w tym requeste?

**Comment by Lukasz-Zurek** [comment]
Widzimy, że pole `"countryCode"` w requeście przekazywane jest jako `"countryu0421ode"`, tzn. takie właśnie dane otrzymaliśmy. Wystąpił zatem najwyraźniej problem przy kodowaniu i tu upewnij się proszę czy po Twojej stronie jest wszystko ok.

**Comment by Mojeallegro123** [comment]
Bardzo dziękuję, tak to jest, błąd z naszej strony.
