### ISSUE TITLE
Problem z przesłaniem etykiety energetycznej

### ISSUE THREAD

**Issue by DLibers** [allegro/allegro-api#7742]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,
Mamy problem z przesłaniem etykiety energetycznej dla produktu. Dostajemy odpowiedź "Invalid file format", ale my przesyłamy jpg, który powinien być poprawny :/

URL: https://upload.allegro.pl/sale/offer-attachments/7b415c48-ff7d-41b2-8ff9-ee30109bf4a5

File:
   - fileName: Okap wyspowy Amica OWC4241OW 648 m³/h LED PowerBooster 266W 3 prędkości_ENERGY_LABEL.jpg
   - contentType: image/jpeg

Response:
`{"errors":[{"code":"ConstraintViolationException","message":"Invalid file format","details":null,"path":null,"userMessage":"Invalid file format"}]}`

trace-id: a7c8b33a4e9cd77b

**Comment by Lukasz-Zurek** [comment]
Upewnij się mimo wszystko czy załączany plik faktycznie jest w formacie jpeg. Jeśli tak, prześlij proszę wspomnianą etykietę. Zweryfikuję to.

**Comment by DLibers** [comment]
Pobieramy obraz z tego linku https://pimcore.gtpoland.eu:86/U%C5%BCytkownicy%20uzupe%C5%82niaj%C4%85cy/21/okap-wyspowy-amica-owc4241ow-etykieta.jpg

**Comment by Lukasz-Zurek** [comment]
@DLibers Konsultuję ten problem z odpowiednim zespołem. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@DLibers Sprawdź proszę czy przekazujesz prawidłowy nagłówek **Content-type**. Według naszych logów otrzymujemy błędny, a powinien być `image/jpeg`.

**Comment by DLibers** [comment]
@Lukasz-Zurek my wysyłamy content-type samego zapytania 
![image](https://github.com/allegro/allegro-api/assets/146194802/6dbe9ba9-d83f-458e-b609-48ccf49f8faf)

Sam plik też ma poprawny content-type
![image](https://github.com/allegro/allegro-api/assets/146194802/7a03a10d-bc70-41af-8c77-c3389abdf41b)

Tutaj jest trace-id z nowego zapytania: 336f90e0407ed713
Jeżeli dalej jest niepoprawny to możecie podać jaki dostajecie?

**Comment by Lukasz-Zurek** [comment]
@DLibers Otrzymujemy `image/jpeg; boundary=-----------------------------28947758029299`

Wyjaśniam to jeszcze z odpowiednim zespołem.

**Comment by Lukasz-Zurek** [comment]
@DLibers Z logów wynika, że otrzymujemy wspomniane powyżej `image/jpeg; boundary=-----------------------------28947758029299`.
