### ISSUE TITLE
Generowanie przesylki WZA

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#7743]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ X ] ze środowiskiem produkcyjnym / with the production environment

Przy probie wygenerowania przesylki dostajemy blad "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej". 

'trace-id': '491b50740484d1c9'

**Comment by Lukasz-Zurek** [comment]
Numery telefonów przekazywane w polach `receiver.phone` i `pickup.phone` odczytywane są przez nasz system jako numery stacjonarne i w tej sytuacji warto dodać przed numerem `+48`. Popraw i daj proszę znać czy to pomogło.

**Comment by d3stozaur** [comment]
niestety dalej to samo 
'trace-id': '5f1aac208131a9e5'

**Comment by Lukasz-Zurek** [comment]
@d3stozaur Ok, konsultuję ten temat z odpowiednim zespołem.

**Comment by Lukasz-Zurek** [comment]
@d3stozaur Wybrana metoda dostawy wymaga podania zweryfikowanego, polskiego numeru iban.

**Comment by d3stozaur** [comment]
Podanie konta z przedroskiem PL daje ciągle ten sam błąd  'trace-id': '2256c4131ba73dfb'
natomiast bez przedrostka PL Wybrana metoda dostawy wymaga podania zweryfikowanego, polskiego numeru iban  'trace-id': 'c167513d485d2740'

**Comment by d3stozaur** [comment]
@Lukasz-Zurek udalo sie cos ustalic?

**Comment by Lukasz-Zurek** [comment]
Błąd dotyczy obiektu **"insurance"**. Pobranie nie może być większe niż ubezpieczenie przesyłki i tu musisz przekazać również dane ubezpieczenia, gdzie kwota musi być wyższa niż ta, którą przekazałeś w części **"cashOnDelivery"**.

**Comment by d3stozaur** [comment]
Działa dzięki. 

p.s.
dobrze by było jakbyście obsłużyli taki przypadek i zwracali odpowiedni komunikat :)
