### ISSUE TITLE
Punkty nadania dla Allegro International

### ISSUE THREAD

**Issue by matcapi** [allegro/allegro-api#7745]
Dzień dobry,

Chciałbym się dowiedzieć które punkty nadania są obsługiwane przez metodę wysyłki: 
**Allegro International Odbiór w Automacie Paczkowym Czechy**
**0e40225c-32c6-4602-b78f-b3146fe9f54a**

W body requestu endpointu [PUT parcel-management/parcel-create-commands/](https://developer.allegro.pl/documentation#operation/createNewParcel) ustawiłem pickup->pointId = **AL012WN1** (allegro) oraz **PNET0900** (InPost) jednak dla obu tych punktów dostałem taką wiadomość  z endpointu [GET parcel-management/parcel-create-commands/](https://developer.allegro.pl/documentation#operation/getParcelCreationStatus):
**Field ShipFrom->PointId specified point is not available for the given carrier**
**Wybrany punkt nadania nie jest obsługiwany przez tego przewoźnika**

Korzystałem z allegro.sandbox.

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
W przypadku Sandboxa, spróbuj proszę nadać przesyłki w jednym z przykładowych punktów:

- ALZABOX2433
- ALWD0064
- ALWD0008

**Comment by matcapi** [comment]
Niestety otrzymałem ten sam komunikat.
Załączam commandId oraz traceId dla PUT
ALZABOX2433 - 5b8cf720-b221-4749-9f12-bc1956c2b1b1 - bca67bd24b4d6051
ALWD0064 - 2f9c4252-2f53-457e-8a25-560a2d12f839 - ef5e106e0060ff3a
ALWD0008 - 608a1a53-91a1-48ef-af63-efe224e65e69 - 1cb3a0dd312177eb

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam za wprowadzenie w błąd w takim razie. Prosiłbym o próbę przekazania w `pickup.pointId` wartości `"anypoint"`.

**Comment by matcapi** [comment]
Gdy nie wybieram punktu nadania, to nie napotykam problemu. Czy ten endpoint nie umożliwia wyboru punktu nadania?

**Comment by PrzemyslawLukanowski** [comment]
Endpoint umożliwia podanie punktu nadania, ale stricte ta usługa dostawy tego nie wymaga - nadanie możliwe jest w dowolnym punkcie APM lub PUDO InPostu.

**Comment by matcapi** [comment]
Poproszę o przykładowy pointId dla AMP i PUDO.

**Comment by PrzemyslawLukanowski** [comment]
@matcapi Aktualnie musisz wskazać wartość `"anypoint"`.

**Comment by matcapi** [comment]
Rozumiem, dziękuję za informację.
