### ISSUE TITLE
Zdublowane usługi 'Allegro International Odbiór w Punkcie Czechy' zwracane przez API

### ISSUE THREAD

**Issue by pawelkucharskiyosi** [allegro/allegro-api#7746]
Dzień dobry,

Podczas pobierania dostępnych rodzajów dostawy jakie zwraca Państwa API otrzymuję np: 

0779bdbb-2043-4ed0-aff7-b3146fe9f54a
0af0a4e4-2043-4ed0-aff7-b3146fe9f54a

obie mają przypisaną nazwę:
Allegro International Odbiór w Punkcie Czechy

Czym one się różnią?
Skąd mogę wiedzieć czy kupujący wybrał usługę która ma Id 0779bdbb-2043-4ed0-aff7-b3146fe9f54a czy 0af0a4e4-2043-4ed0-aff7-b3146fe9f54a?

Czy wybór nieodpowiedniego spowoduje że zostaną naliczone jakieś opłaty?

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry,

Metoda 0779bdbb-2043-4ed0-aff7-b3146fe9f54a dotyczy serwisu `allegro-pl` i będzie widoczna tylko dla kupujących na stronie allegro.pl, natomiast 0af0a4e4-2043-4ed0-aff7-b3146fe9f54a przeznaczona jest na rynek czeski - `allegro-cz`, dla kupujących na allegro.cz. Informację na ten temat znajdziesz w polu `marketplaces` przy danej metodzie dostawy, a to, jaką metodę wybrał kupujący, zwracamy w szczegółach zamówienia w polu `delivery.method.id`. W polu `marketplace.id` zwracamy dodatkowo informację, z jakiego serwisu pochodzi zamówienie.

**Comment by pawelkucharskiyosi** [comment]
dzięuję wszystko jasne
