### ISSUE TITLE
Witam, chciałbym zapytać, czy interfejs API ma funkcję wykrywania, czy sklep jest zablokowany?

### ISSUE THREAD

**Issue by qq16632785** [allegro/allegro-api#7747]
Witam, chciałbym zapytać, czy interfejs API ma funkcję wykrywania, czy sklep jest zablokowany?

**Comment by PrzemyslawLukanowski** [comment]
Jeśli Twoje konto posiada blokadę, to zwrócimy taką informację w polu `validation.errors`, gdy tworzysz draft oferty. W przypadku, gdy chcesz utworzyć aktywną ofertę za pomocą POST /sale/product-offers lub edytować ją przez PATCH /sale/product-offers/{offerID}, odpowiemy statusem 422 również z odpowiednim komunikatem błędu. Nie zwracamy informacji o blokadzie w innych miejscach.

**Comment by qq16632785** [comment]
Czy jeśli konto jest zablokowane, mogę sprawdzić status sklepu poprzez interfejs? To normalny stan sklepu i zablokowany status sklepu!

**Comment by PrzemyslawLukanowski** [comment]
Jak wspomniałem wyżej - prócz komunikatów w odpowiedzi na próbę wystawienia oferty, nie zwracamy informacji o statusie sklepu.
