### ISSUE TITLE
Dodawanie produktów przez API - ProductProposalsAccessForbiddenException error

### ISSUE THREAD

**Issue by yeastcom** [allegro/allegro-api#7748]
Próbuje dodać testowy produkt w allegrosandbox za pomocą endpointa  POST sale/product-offers. 

Oto dane jakie wysyłam przez API:
`{"category":{"id":"89060"},"productSet":[{"product":{"name":"TESTOWY PRODUKT","idType":"GTIN"},"category":{"id":"89060"}}],"delivery":{"shippingRates":null},"stock":{"available":99},"sellingMode":{"price":{"amount":"123.45","currency":"PLN"}}}`

Otrzymuje cały czas error `code] => ProductProposalsAccessForbiddenException [message] => Access denied. [details] => [path] => productSet[0].product [userMessage] => Brak dostępu`

Nie rozumiem z czego wynika błąd.

**Comment by PrzemyslawLukanowski** [comment]
Twoje konto nie było aktywowane, dlatego odpowiadaliśmy statusem 403 Forbidden. Właśnie je aktywowałem, zatem problem nie powinien już występować.

**Comment by fazrik** [comment]
Hi,
I have the same problem with ProductProposalsAccessForbiddenException. 
My Sandbox ClientID: 106804232 (marek@webyslavik.cz).
Could you fully activate my account, please?
Thanks, Marek

**Comment by MaciejFrackowiak** [comment]
@fazrik I have already answered in the thread #8199.
