### ISSUE TITLE
Rabaty transakcyjne. Od jakiej daty liczony jest czas na złożenie wniosku o zwrot prowizji?

### ISSUE THREAD

**Issue by ConteMainteiner** [allegro/allegro-api#7749]
Przy tworzeniu zapytania o zwrot prowizji dostaję błąd CommissionRefundPeriodExpiredException (trace-id: ee1ecde686e3af12)
mimo że zamówienie zostało opłacone 2023-09-03 (trace-id zamówienia: 8ff5b47c070bdec2) więc 45 dni jeszcze nie upłynęło. 
Jeśli sprawdzania jest data lineItems.boughtAt wtedy limit 45 dni jest zdecydowanie za mały biorąc pod uwagę, że nieopłacone przedmioty mogą czekać nawet 30 dni (licytacje) na opłacenie przez klienta zanim Allegro samo takie zamówienie anuluje. Dokładając do tego 14 dni na zgłoszenie zwrotu i kolejne 14 na nadanie paczki, otrzymujemy 58 dni zanim produkt trafi ponownie do sprzedającego.

**Comment by PrzemyslawLukanowski** [comment]
Sprawdzamy datę na poziomie lineItem'a, czyli `lineItems.boughtAt `- w tym przypadku okres 45 dni faktycznie został przekroczony.
Uwagi przekaż proszę za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt), ponieważ dotyczą stricte procesu składania wniosku o rabat, a nie samego API.
