### ISSUE TITLE
Brak możliwości nadania przesyłki Inpost umowa własna

### ISSUE THREAD

**Issue by Rychu1998** [allegro/allegro-api#7753]
W responsie otrzymuje komunikat z prośbą o kontakt w celu rozwiązania problemu. Poniżej załączam requesty oraz respony.
![netcom_1](https://github.com/allegro/allegro-api/assets/144427855/a834602c-1b69-4696-a929-4c15782cdb7d)
![netcom_2](https://github.com/allegro/allegro-api/assets/144427855/b2499703-739e-4af1-b87d-5edc20fa46b2)
![netcom_3](https://github.com/allegro/allegro-api/assets/144427855/a7d42798-9f86-4c54-b166-4814e346b1dc)
![netcom_4](https://github.com/allegro/allegro-api/assets/144427855/642c1add-edfa-472b-8a71-607d3b830796)
![netcom_5](https://github.com/allegro/allegro-api/assets/144427855/4c1b8b2f-7141-415b-b02b-dba2cc01efea)
![netcom_6](https://github.com/allegro/allegro-api/assets/144427855/62c8787d-ef17-47b4-9df1-1fb91639b521)
[netcom_7.txt](https://github.com/allegro/allegro-api/files/12880171/netcom_7.txt)
[netcom_8.txt](https://github.com/allegro/allegro-api/files/12880172/netcom_8.txt)

**Comment by PrzemyslawLukanowski** [comment]
Kwota, którą przekazujesz w `additionalServices.cashOnDelivery.value.amount`, nie może być większa niż kwota w `items.value.amount`.
