### ISSUE TITLE
Metody dostawy (Pakersi,Furgonetka, Bonito)

### ISSUE THREAD

**Issue by Rychu1998** [allegro/allegro-api#7754]
Dzień dobry,
Podczas pobierania usług z API nie mamy takich metod dostawy jak Pakersi, Bonito, Kolporter. Czy wystarczy wskazać dla tych metod Allegro One ? Są to jakieś nowe metody dostawy i należy je pobrać w inny sposób ? 
![metody dosatwy](https://github.com/allegro/allegro-api/assets/144427855/06026fd4-eca6-44c4-bd18-5d12a042de4a)

**Comment by PrzemyslawLukanowski** [comment]
> Czy wystarczy wskazać dla tych metod Allegro One ?

Dokładnie tak, wystarczy wskazać Allegro One, a na stronie oferty pojawi się odpowiednie rozróżnienie.
