### ISSUE TITLE
Pomoc w aktywacji API na koncie

### ISSUE THREAD

**Issue by McjSala** [allegro/allegro-api#7755]
Dzień dobry,

w nawiązaniu do zgłoszenia nr "36587932"    [ref:_00D24aE05._5003VcsXdr:ref]

bardzo proszę o pomoc w rejestracji aplikacji na portalu deweloperskim w celu korzystania z API.

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry,
Czy możesz doprecyzować, jakiej pomocy dokładnie potrzebujesz? Aplikację możesz zarejestrować na stronie https://apps.developer.allegro.pl/ - musisz przy tym posiadać aktywne konto i włączone dwustopniowe logowanie. Jeśli coś wymaga wyjaśnienia, napisz proszę.

**Comment by McjSala** [comment]
Tak - spróbowałem to zrobić  wg instrukcji: 

https://allegro.pl/pomoc/dla-kupujacych/aktywacja-konta/jak-aktywowac-konto-zwykle-za-pomoca-wplaty-online-mGwAg2WXBFV 

jednak nie przenosi mnie do żadnej płatności/banku. Skierowałem się na Waszą infolinie i zostałem pokierowany z tym problemem tutaj

**Comment by PrzemyslawLukanowski** [comment]
Jeśli dotyczy to aktywacji na środowisku produkcyjnym, zgłoś proszę ten problem w zgłoszeniu, które przytoczyłeś na początku - proces aktywacji konta nie jest związany z API, być może osoba, która udzielała odpowiedzi bardziej zasugerowała się rejestracją aplikacji, o której również wspominasz.

Jeśli natomiast problem dotyczy środowiska testowego Sandbox, podaj proszę login, a aktywuję konto manualnie.
