### ISSUE TITLE
Wysyłam z Allegro - problem z nadaniem przesyłki

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#7756]
Witam, mam problem z nadaniem przezywłi przez Wysyłam z allegro.

Request
`{
    "commandId": "1f418dc5-7f19-407d-b3a8-ad99e9b23152",
    "input": {
        "deliveryMethodId": "08c15d0b-9b24-4b3f-89a8-7a2b502abe55",
        "credentialsId": "",
        "sender": {
            "name": "...",
            "company": "...",
            "street": "...",
            "streetNumber": "...",
            "postalCode": "41-902",
            "city": "Bytom",
            "countryCode": "PL",
            "email": "...",
            "phone": "..."
        },
        "receiver": {
            "name": "...",
            "company": "",
            "street": "...",
            "streetNumber": "...",
            "postalCode": "05-127",
            "city": "Białobrzegi",
            "countryCode": "PL",
            "email": "...",
            "phone": "...",
            "point": "A005978"
        },
        "pickup": {
            "name": "...",
            "company": "...",
            "street": "...",
            "streetNumber": "...",
            "postalCode": "41-902",
            "city": "Bytom",
            "countryCode": "PL",
            "email": "...",
            "phone": "..."
        },
        "referenceNumber": "...",
        "description": "...",
        "packages": [
            {
                "type": "PACKAGE",
                "length": {
                    "value": "64",
                    "unit": "CENTIMETER"
                },
                "width": {
                    "value": "38",
                    "unit": "CENTIMETER"
                },
                "height": {
                    "value": "8",
                    "unit": "CENTIMETER"
                },
                "weight": {
                    "value": "20",
                    "unit": "KILOGRAMS"
                }
            }
        ],
        "labelFormat": "PDF",
        "additionalServices": [
            ""
        ],
        "additionalProperties": [
            ""
        ]
    }
}`

Dostaje blad:
`(
    [commandId] => f8d8a826-81ef-44be-9430-ff30a2a565a2
    [status] => ERROR
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => PROCESSING_ERROR
                    [message] => Problem with dispatch. Contact us, and we will help as soon as possible.
                    [details] => 
                    [path] => 
                    [userMessage] => Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.
                )

        )

    [shipmentId] => 
)`

Zgodnie z poradnikiem: https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke

Troche chyba nie rozumiem tej dokumentacji, pomijajac w niej braki. np. w poradniki w przykladnie nie ma naglowka "Content-type: application/vnd.allegro.public.v1+json". Ale wracajac do pytania co nalezy wprowadzic dla:
"sender":{ - dane nadawcy
"receiver":{ - dane odbiorcy
"pickup":{ - wymagane, dane nadawcy

Dwa razy dane nadwcy?

**Comment by mskiba03** [comment]
Czy ktos może mi pomóc, albo napisać dokumentacje, w której nie trzeba się domyślać o co chodzi. Bo błąd skontaktuj się z nami. Pomożemy jak najszybciej, nie bardzo ma sie do rzeczywistości.

**Comment by Eskim83** [comment]
sender to dane nadawcy na etykiecie, pickup to dane gdzie ma podjechać kurier.. Mi ta metoda też nie działa. Ciekawi mnie jak sobie poradziłeś z wyciąganiem numeru ulicy z zamówienia Allegro.

Polecam poprzednią metodę, która jest deprecated (/parcel-management/parcel-create-commands/{commandId}) . Nie musimy wypełniać ubezpieczeń i kwot pobrania, ani pobierać dodatkowych danych.., ale metoda działa.

Zamawianie podjazdu robimy inną metodą jak chcemy.

**Comment by mskiba03** [comment]
Dzięi Eskim83 za podpowiedź. Co do numeru ulicy z zamówenia, to rodzielam po stacji do tablicy, jako numer biore ostatnia wartosc tablicy, a jako ulice bire cala wartosc i usuwam z niej to co jest numer budynku ;) Nie jest to doskonale, bo jak bedzie adres Ulica 3 m 3  to jako ulica bedzie Ulica 3 m a jako numer 3, ale to tez przechodzi :D

**Comment by Eskim83** [comment]
Głupie, ale w sumie zadziała. Niemniej boję się takie rzeczy robić.. może w polu description jeszcze dodatkowo przekażę ulicę. Ten wątek widzę już był 4 dni temu. Brakuje mi metody, która po prostu wygeneruje przesyłkę do zamówienia, ewentualnie pozwoli poprawić dane odbiorcy. Wiesz - to też kwestia skali.. na kilkuset zamówieniach dziennie takie rozwiązanie może generować problemy, bo użytkownicy są nieprzewidywalni.

**Comment by mskiba03** [comment]
Generuje tak ok 400-600 zamowien dziennie i jeszcze problemow nie bylo. Generalnie do tej pory tylko przez api inpost, ale metoda ta sama.

Wracajac do temu to może ktos z allegro sie wypowie nt mojego nic nie mowiacego błedu?

**Comment by Eskim83** [comment]
Przy takiej skali są błędy już obecnie w starej metodzie, bo klienci wpisują adresy np. tak Łagodna3m3 .. mam takich przypadków dużo.

**Comment by Lukasz-Zurek** [comment]
@mskiba03 W kilku miejscach przekazujesz puste stringi. Usuń je proszę. Jednocześnie konsultuję jeszcze ten problem z zespołem odpowiedzialnym za tę usługę.

Generalnie mamy świadomość, że niektóre komunikat są zbyt ogólne. Cały czas pracujemy nad ich odpowiednim mapowaniem. Współpracujemy z operatorem logistycznym, dlatego może to być wydłużone w czasie.

Dla nas również weryfikacja tego typu zgłoszeń jest dość utrudniona i konieczna jest analiza. Zapewniam, że pracujemy nad tym, aby to zoptymalizować.

Dodam, że poprawiłem nasz poradnik, faktycznie brakowało `Content-type`. Dziękuję.

**Comment by Lukasz-Zurek** [comment]
@mskiba03 W polu, w którym obecnie przekazujesz puste stringi `"additionalServices":[""]` - przekaż `null`.

**Comment by mskiba03** [comment]
Panie Łukaszu, ja wszystko rozumiem, ale delikatnie mówią nalegacie na wasze metody wysyłki, przez serwis wszystko działa, ale po api to same problemy. Najpierw powinniście dopracować dokumentacje i działanie funkcji, a potem "nalegać", żebyśmy z tego korzystali.

Wracając do tematu. Dokonałem jednej zmiany a mianowicie, dane do api były pobierane z aplikacji, a w książce adresowej były inne (tzn. takie same, ale inaczej wpisane). Ujednoliciłem te dane i spróbowałem jeszcze raz, I o dziwo, się udało, a nawet wiecej, jedna z wczoraj utworzonych paczek zmienila status z ERROR na SUCCESS, nie wiem czemu ;)

Teraz próbuje i znowu to samo. Przy tworzeniu paczki nie dostaje błędów, ale jak sprawdzam status to jest error. Pytanie, czemu 

POST \
  'https://api.allegro.pl/shipment-management/shipments/create-commands'

zwraca mi sukces a jak sprawdzam 

GET \ 
  'https://api.allegro.pl/shipment-management/shipments/create-commands/{command_id}'

to dostaje ogolny blad, zeby sie z Wami skontaktowac?

Response po utworzeniu paczki:

`{
    "commandId": "27199d54-9de1-47c2-9d0b-5b571074bf98",
    "input": {
        "deliveryMethodId": "08c15d0b-9b24-4b3f-89a8-7a2b502abe55",
        "credentialsId": "",
        "sender": {
            "name": "...",
            "company": "...",
            "street": "...",
            "streetNumber": "...",
            "postalCode": "41-902",
            "city": "Bytom",
            "state": null,
            "countryCode": "PL",
            "email": "...",
            "phone": "...",
            "point": null
        },
        "receiver": {
            "name": "...",
            "company": "",
            "street": "...",
            "streetNumber": "...",
            "postalCode": "05-127",
            "city": "Bia\u0142obrzegi",
            "state": null,
            "countryCode": "PL",
            "email": "...",
            "phone": "...",
            "point": "A005978"
        },
        "pickup": {
            "name": "...",
            "company": "...",
            "street": "...",
            "streetNumber": "...",
            "postalCode": "41-902",
            "city": "Bytom",
            "state": null,
            "countryCode": "PL",
            "email": "...",
            "phone": "...",
            "point": null
        },
        "referenceNumber": "...",
        "description": "...",
        "packages": [
            {
                "type": "PACKAGE",
                "length": {
                    "value": 64,
                    "unit": "CENTIMETER"
                },
                "width": {
                    "value": 38,
                    "unit": "CENTIMETER"
                },
                "height": {
                    "value": 19,
                    "unit": "CENTIMETER"
                },
                "weight": {
                    "value": 20,
                    "unit": "KILOGRAMS"
                }
            }
        ],
        "insurance": null,
        "cashOnDelivery": null,
        "labelFormat": "PDF",
        "additionalServices": [
            ""
        ]
    }
}`

**Comment by Lukasz-Zurek** [comment]
@mskiba03 Sprawdzamy to. Proszę Cię o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@mskiba03 Kluczową rzeczą jest tutaj przekazywanie pustego stringi dla `"additionalServices":[""]` - dla tego przewoźnika nie ma żadnych usług dodatkowych, dlatego należy przekazać `null`.

Ponadto nie można anulować przesyłki Allegro One.

**Comment by Electronc** [comment]
@Lukasz-Zurek  Dlatego może warto, żebyście zadbali dla własnego przewoźnika o przygotowanie wytycznych dla każdego pola i serializację po waszej stronie danych np. numer telefonu, czy chociażby numer ulicy na której jest paczkomat. Przecież to nie jest normalne, że musimy tutaj was pytać o takie drobne rzeczy.

**Comment by mskiba03** [comment]
Dzieki pomoglo.

Mam jeszcze dwa pytania:
1. Obecnie po nadaniu przesylki, zmienia jej status na wysłane, jest mozliwoc żeby tego nie robilo?
2. Jak pobrać list przewozowy?
wywoluje metode
`curl -X 'POST' \
  'https://api.allegro.pl/shipment-management/label' \
  -H 'accept: application/octet-stream' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -d '{
  "shipmentIds": [
    "ba88f0fb-acf3-438a-877e-580da50c0874"
  ],
  "pageSize": "A4",
  "cutLine": true
}'`

nie ma zadnych errorow, ale przegladarka nie pobiera listu.

Podejrzewam ze nie wywolalem poprawnie tego w php

$url = "https://api.allegro.pl/shipment-management/label";
$post['shipmentIds'][] = $shipment_id;
$post['pageSize'] = 'A6';
$post['cutLine'] = true;				
$post_data = json_encode($post);				
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
$result = ($result = curl_exec($ch)) === false ? false : json_decode($result, true);
curl_close($ch);`

**Comment by Lukasz-Zurek** [comment]
@Electronc Tak, mamy świadomość tych utrudnień i monitorujemy to. Zależy nam na tym, aby to uściślić z naszym operatorem logistycznym i przede wszystkim, aby dostosować nasze komunikaty, aby były w pełni czytelne.

**Comment by mskiba03** [comment]
Dziękuje. Pojawił się jeszcze problem przy nadaniu przesyłki:

Allegro Pocztex Kurier 48
6eced786-aee4-47ba-9cb6-e24f8b1d3182

Nie pobiera tej przesyłki z https://api.allegro.pl/shipment-management/delivery-services, przec co nie mozna wybrac typu przesyłki:

Blad:
`{
    "errors": [
        {
            "code": "VALIDATION_ERROR",
            "message": "musi pasowa\u0107 do wyra\u017cenia DOX|PACKAGE|PALLET|OTHER",
            "details": "Invalid value: ",
            "path": "input.packages[0].type",
            "userMessage": "musi pasowa\u0107 do wyra\u017cenia DOX|PACKAGE|PALLET|OTHER"
        }
    ]
}`

**Comment by Eskim83** [comment]
Pozwolę sobie dodać jeszcze inne problemy, które dzisiaj wystąpiły:

- zbyt długa nazwa firmy (max. 30 znaków) - ok, można przyciąć,
- brak +48 przed numerem telefonu.. tego już do końca nie rozumiem
- zbyt długi opis (nazwa przedmiotu) - rozszerzyliście na Allegro możliwość tworzenia tytułu do 75 znaków, a tutaj można maksymalnie 50 znaków.

Problem dotyczy poprzedniej metody, bo nowej się boję jak już wspomniałem.

**Comment by Lukasz-Zurek** [comment]
@mskiba03 Wskazana metoda już nie istnieje. Została zastąpiona Allegro Kurier Pocztex, zgodnie z [newsem](https://allegro.pl/dla-sprzedajacych/wprowadzilismy-zmiany-dla-sprzedajacych-zapowiedziane-na-25-kwietnia-O3En5Bv5zIM#usunelismy-z-cennikow-wybrane-metody-dostawy-poczty-polskiej).

**Comment by Lukasz-Zurek** [comment]
@Eskim83 Tych dotychczasowych zasobów na ścieżce **/parcel-management** nie będziemy już rozwijać. Niemniej jednak zależy nam na korzystaniu z nowych na **/shipment-management** i aby móc ją optymalizować zarówno pod kątem wymienionych pól, jak i komunikatów błędów - aby one były jednoznaczne.

Jeśli mógłbyś sprecyzować dokładnie co zniechęca się do korzystania z nowych zasobów WZA - będziemy wdzięczni. Uwagi przekażę do odpowiedniego zespołu.
