### ISSUE TITLE
Kalkulator opłat prowizji

### ISSUE THREAD

**Issue by Eskim83** [allegro/allegro-api#7759]
Witam

Poprzednio pobierałem informację o kosztach prawie po ludzku - podawałem kategorię, cenę, nazwę (nie wiem po co - jest wymagana, więc była losowa), informację o tym czy oferta jest wyróżniona itd. W ten sposób mogłem sprawdzić koszty dla kilkudziesięciu tysięcy aukcji dosyć szybko (znałem ich kategorię oraz cenę, a to wystarczyło)

Teraz, aby uzyskać podobny efekt dla aukcji już wystawionych muszę pobrać pełne opisy tych kilkudziesięciu tysięcy aukcji i przekazać je do zmienionej pricing/offer-fee-preview. Obowiązkowym elementem jest parameters.

Dla aukcji jeszcze nie wystawionych muszę czarować dane, ale powiem szczerze jeszcze tego elementu nie analizowałem.. choć muszę, bo staramy się wystawiać świadomie.

Czy coś źle robię? Jest jakaś metoda na sprawdzenie planowanych kosztów sprzedaży w zadanej kategorii?

**Comment by Lukasz-Zurek** [comment]
Zasób [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST) jest obecnie jedyną funkcjonalnością w API, za pośrednictwem której sprawdzisz opłaty pod kątem oferty (w tym również kategorii). Potwierdzam, że parametry są wymagane.

Zachęcam Cię jednak do przekazania sugestii/pomysłu na usprawnienie tego zasobu, lub nowej funkcjonalności, w dedykowanym do tego miejscu - [Discussions](https://github.com/allegro/allegro-api/discussions).
