### ISSUE TITLE
Ile Bieżące saldo jest winne i czy interfejs API może bezpośrednio odczytać te dane?  

### ISSUE THREAD

**Issue by qq16632785** [allegro/allegro-api#7760]
https://allegro.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro 
Ile Bieżące saldo jest winne i czy interfejs API może bezpośrednio odczytać te dane?

**Comment by PrzemyslawLukanowski** [comment]
Tak, za pomocą [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries) pobierzesz [historię operacji billingowych oraz saldo zautoryzowanego użytkownika](https://allegro.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro).
