### ISSUE TITLE
Error Messages that Request the Problem is Reported to Application Author

### ISSUE THREAD

**Issue by soph-lawrence** [allegro/allegro-api#7762]
Two SKU examples below that are show two separate errors. 
The Error Messages are:

`An invalid request was sent. Report the problem to the application's author.
`ConstraintViolationException An invalid request was sent. Report the problem to the application's author. - (parameters[8].id)

Example SKUS and relevant docs attached.
[RWN289___80012L_product_allegro_pl.txt](https://github.com/allegro/allegro-api/files/12891365/RWN289___80012L_product_allegro_pl.txt)
[DKP415___N3LC09_product_allegro_pl.txt](https://github.com/allegro/allegro-api/files/12891366/DKP415___N3LC09_product_allegro_pl.txt)

Could you please confirm why these are appearing? 
thanks

**Comment by Lukasz-Zurek** [comment]
@soph-lawrence Please precise your message and send us a trace-id if the problem refers to the public api.

**Comment by lukeroot** [comment]
Closed as issue is non API related. Thanks
