### ISSUE TITLE
Błąd Baselinker problem ze zdjęciem

### ISSUE THREAD

**Issue by WebmasterSolaris** [allegro/allegro-api#7763]
Witam, chciałbym prosić o pomoc w rozwiązaniu problemu z błędem wyskakującym w baselinkerze podczas próby wystawienia aukcji. Mianowicie wyskakuje mi błąd:

Wystąpił błąd podczas wystawiania oferty:
Nie można pobrać zdjęcia z adresu 'https://sklep490642.shoparena.pl/userdata/public/gfx/478837.jpg'. Serwer ze zdjęciem zwrócił kod HTTP: 400 BAD_REQUEST z błędem: ''. (DownloadError.BadRequest productSet[0].product.images)

Próbowałem kontaktować się z baselinkerem, ich odpowiedź: 

BaseLinker przekazuje jedynie linki zdjęć przy wystawianiu do Allegro, to Allegro bezpośrednio odpytuje o zdjęcia produktu, otrzymując błąd.
Przykro mi, ale ten problem nie leży po naszej stronie.

Następnie kontaktowałem się z Allegro i odesłali mnie do Państwa tutaj. Bardzo proszę o pomoc, ponieważ błąd ten występuje bardzo często. Zazwyczaj jest to problem który przy wystawianiu zwraca uwagi do pierwszego zdjęcia bądź miniatury.

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Otrzymaliśmy już podobne zgłoszenie w tym temacie w wątku #7750. Odpowiedni zespół przeanalizuje ten problem - wrócę z odpowiedzią, gdy uda nam się ustalić więcej szczegółów.

**Comment by PrzemyslawLukanowski** [comment]
Wdrożyliśmy dziś zmiany po naszej stronie, jednak jeśli problem nadal się pojawia, to poproszę o nowe przykłady.
