### ISSUE TITLE
Co to za parametr 18118?

### ISSUE THREAD

**Issue by kamper-core** [allegro/allegro-api#7764]
Wystawiając ofertę przez IdoSell zwraca nam błąd o niepoprawnym parametrze 18118
![image](https://github.com/allegro/allegro-api/assets/143624398/e095d708-b794-40d7-9880-f22afd40579f)

**Comment by PrzemyslawLukanowski** [comment]
Parametr 18118 to "Rodzaj". Upewnij się, czy nie przekazujesz w parametrze wartości, którą można wybrać już z listy dostępnych wartości. Jeśli problem wciąż będzie występować, wyślij nam dane, które są zawarte w plikach "żądanie" i "odpowiedź" - w tym celu skontaktuj się przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt), napisz, że masz problem z wystawieniem oferty za pomocą w API i przesyłasz pliki, które są niezbędne do weryfikacji wątku #7764 na GitHubie.
