### ISSUE TITLE
Sandbox - odblokowanie sprzedaży

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#7766]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ X ] ze środowiskiem testowym / with the test environment

Witam,
Poproszę o odblokowanie sprzedaży dla konta avellotestowe w środowisku testowym

**Comment by PrzemyslawLukanowski** [comment]
Anulowałem blokadę sprzedaży. W przyszłości możesz zrobić to także samodzielnie, opłacając rachunek  za pomocą symulatora płatności w zakładce [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro).

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, dziękuję za informację.
