### ISSUE TITLE
Sandbox z domyślnym rynkiem allegro-cz

### ISSUE THREAD

**Issue by przemekwd** [allegro/allegro-api#7767]
Cześć.

Czy konto sandbox może mieć baseMarketplace ustawiony na allegro-cz? Rejestrując nowe kontro na https://allegro.cz.allegrosandbox.pl/ baseMarketplace został ustawiony na allegro-pl. 
Nie mogę też doszukać się opcji zmiany domyślnego rynku - rozumiem, że takowej może nie być.

**Comment by PrzemyslawLukanowski** [comment]
Tak, jest to jak najbardziej możliwe, przed chwilą przeprowadziłem test. Upewnij się, czy na pewno operujesz tokenem dla tego właśnie użytkownika., np. za pomocą wywołania [GET /me](https://developer.allegro.pl/documentation#operation/meGET).

**Comment by przemekwd** [comment]
Tak, token jest dla odpowiedniego użytkownika, a [GET /me](https://developer.allegro.pl/documentation#operation/meGET) właśnie się upewniłem, że coś nie tak jest z domyślnym rynkiem ;) To tak żeby się upewnić, że pomyłka była przy rejestracji (sam go nie tworzyłem, dostałem gotowe) - rejestarując się z https://allegro.cz.allegrosandbox.pl/ ZAWSZE baseMarketplace będzie ustawiony na allegro-cz i nie ma odstępst od tej reguły?

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, potwierdzam.
