### ISSUE TITLE
Środowisko Produkcyjne odrzuca połączenie

### ISSUE THREAD

**Issue by Snajper315** [allegro/allegro-api#777]
Przy każdej próbie połączenia wyrzuca błąd:
Failed to connect to api.allegro.pl port 443: Connection timed out

Po ustawieniu proxy wszystko działa jak powinno.  Sandbox również normalnie akceptuje połączenia.
Hosting wykupiony na hostinger.com , IP serwera: 185.224.138.82

**Comment by pskz** [comment]
Nie zauważyłem takiego problemu, ale natomiast już drugi raz dzisiejszego dnia wygasają tokeny i trzeba się ponownie autoryzować.

**Comment by PawelTaberski** [comment]
@Snajper315 Czy w dalszym ciągu masz problemy z połączeniem z tego serwera, na jaki adres i zasób uderzasz?

**Comment by Snajper315** [comment]
Tak, problem ciągle występuje. Wygląda na to, że serwer gdzieś/kiedyś trafił na czarną listę (?)
Próbuje połączyć się z: https://api.allegro.pl/
zasób: offers/listing
Każde połączenie (z tego serwera) na adres kończy się timeoutem bez względu na zasób i parametry.

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) ip serwerów na których zauważyłeś ten problem. Sprawdzimy to. W zgłoszeniu zaznacz, że informacje są potrzebne do ticketa na GitHub numer 777.

**Comment by Snajper315** [comment]
Dzięki za poświęcony czas, skontaktowałem się z helpdeskiem mojego hostingu, okazało się adres API trafił na greylist.. już wszystko działa.
