### ISSUE TITLE
Zdjęcia w ofercie których nie dodał wystawiający

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#7770]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

Czemu wystawiając ofertę nagle znajduje się w niej zdjęcie, którego sprzedawca nie dodał przy wystawianiu? Trace id `33e50cde6f9d651c`

**Comment by mskiba03** [comment]
jeśli nie dodasz w productId tablicy images[] = null, to do oferty zostaną dorzucone zdjęcia  katalogu allegro dla tego produktu

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, produkt został wskazany w requeście po ID, zatem dołączyliśmy do niego także zdjęcie z katalogu.

**Comment by TimothyKoval** [comment]
Ale przekazane zostało własne zdjęcie

**Comment by PrzemyslawLukanowski** [comment]
Tak, ale miało to miejsce w części ofertowej `"images"`, zatem do obrazka z produktu dodaliśmy obrazek z requestu. Aby nadpisać produktowe zdjęcie/zdjęcia, musisz to zrobić w sekcji `"product.images"`.

**Comment by TimothyKoval** [comment]
Co za skrajny idiotyzm...

**Comment by jezewskiBNetrox** [comment]
> Co za skrajny idiotyzm...

@TimothyKoval Sorry, ale czemu to idiotyzm? Chcąc skorzystać ze zdjęć produktowych i własnych jednocześnie w twojej wersji nie mógłbym tego zrobić. Tutaj można. I nikt tego nie ukrywa, bo w poradniku taka informacja jest - https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty

**Comment by TimothyKoval** [comment]
@jezewskiBNetrox Idiotyzmem jest to, że muszę podawać te zdjęcia w dwóch miejscach.

**Comment by PrzemyslawLukanowski** [comment]
@TimothyKoval Nie musisz, wystarczy, że podasz je w `product.images`, wtedy nie musisz w `images`. Lub w `product.images` przekażesz pustą tablicę, a w `images` właściwe zdjęcia.

**Comment by mskiba03** [comment]
Korzystanie ze zdjęć z katalogu allegro jest niebezpieczne ;) Trzeba się przygotować na ostrzeżenia od Allegro. W katalogu zdjec allegro np. do oleju silnikowego jest dodanych masa zdjec, wiele z nich ma np. zdjęcie z zawieszką i kontaktem do sprzedającego, potem jak ja biorę te zdjęcie, to nie dość ze reklamuje kogoś innego, to dostaje od allegro ostrzeżenie ze zdjęcie niezgodne z regulaminem allegro. I to jest abstrakcja, wykorzystuje zdjęcie z katalogu allegro ale jest ono niezgodne z ich zasadami :D

**Comment by PrzemyslawLukanowski** [comment]
@mskiba03 Możesz podać przykład takiego produktu? Zgłosimy problematyczne zdjęcia do usunięcia.
