### ISSUE TITLE
Błąd przy tworzeniu draftu: Could not change offer publication status.

### ISSUE THREAD

**Issue by Jaanioo** [allegro/allegro-api#7772]
Występuje problem:

Przy tworzeniu draftu wiele produktów wraca z błędem: 
'Could not change offer publication status. Selected product does not exist.'
Skąd ten błąd się bierze? Jaka jest przyczyna. Jak go ograć? 

command_id: "ae6d68df-da55-48a6-b9e7-293effc8c741"
offer id: "14501978252"
https://api.allegro.pl/sale/offer-publication-commands/ae6d68df-da55-48a6-b9e7-293effc8c741/tasks

**Comment by AureliuszBrussy** [comment]
Wczoraj został utworzony draft tej oferty z produktem. Dzisiaj nastąpiła próba aktywacji, natomiast sam produkt pomiędzy utworzeniem draftu, a próbą aktywacji został usunięty z naszego Katalogu Produktów. Stąd wspomniany komunikat błędu.

**Comment by Jaanioo** [comment]
Ten sam problem występuje, w momencie kiedy pomiędzy utworzeniem draftu, a próbą aktywacji jest około 10 minut.

**Comment by AureliuszBrussy** [comment]
Z różnych powodów możemy usuwać utworzone w Katalogu produkty. Jeżeli masz pytania odnośnie konkretnych przypadków, skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt).

**Comment by Jaanioo** [comment]
Czy jest to normalna sytuacja, że jeden produkt nie daje się aktywować po 5-10 razy z rzędu?

**Comment by AureliuszBrussy** [comment]
Jeżeli produkt jest wciąż usuwany z naszego Katalogu Produktów zaraz po utworzeniu, to jest to możliwe.

**Comment by Jaanioo** [comment]
Mam pytanie usuwanie produktu przebiega po waszej stronie?

**Comment by glorifyingpeace** [comment]
Ten mechanizm jest bez sensu. Po to mamy weryfikację draftu a potem także produktu który powstaje żeby na tym etapie wiedzieć czy oferta się wystawi czy nie. Jeśli pojawią się warunki o których Allegro nie wspomina w dokumentacji, to powstaje kolejny sposób weryfikacji dla którego trzeba pisać kolejną logikę obsługi. 
Dodatkowo brak wytycznych sprawia że znów musimy działać po omacku.

**Comment by AureliuszBrussy** [comment]
Produkty są usuwane z Katalogu przez nas, użytkownik nie może tego zrobić samodzielnie. Jeżeli są pytania o powody usunięcia poszczególnych produktów - użytkownicy mogą skorzystać z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt).
