### ISSUE TITLE
Aplikacja nie pokazuje się w panelu zarządzania

### ISSUE THREAD

**Issue by jezewskiBNetrox** [allegro/allegro-api#7775]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [X] z logowaniem lub autoryzacją / with login or authorization
 - [X] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam, 
chciałem zaktualizować uprawnienia jednej aplikacji na https://apps.developer.allegro.pl/ i okazało się, że w ogóle nie ma na liście aktualnie używanej aplikacji.
Możecie sprawdzić, o co chodzi? 

ClientId: 6d22e583b88849c3983534706b2abdad

**Comment by AureliuszBrussy** [comment]
Aplikacja istnieje. Jesteś pewien, czy logujesz się na odpowiednie konto, gdzie faktycznie została zarejestrowana?

**Comment by jezewskiBNetrox** [comment]
> Aplikacja istnieje.

@AureliuszBrussy To wiem, bo jest wykorzystywana cały czas. Jednak nie mam jej na liście i nie mogę jej edytować. Tak, loguje się na odpowiednie konto i z niego była zarejestrowana. Są tam też zarejestrowane dwie stare aplikacje webowe bez nazwy, które są nieużywane.

**Comment by AureliuszBrussy** [comment]
Czy możesz podać login konta, na które się logujesz do [Developer Apps](https://apps.developer.allegro.pl/)? Potwierdzę, czy to odpowiednie konto.

**Comment by jezewskiBNetrox** [comment]
> Czy możesz podać login konta, na które się logujesz do [Developer Apps](https://apps.developer.allegro.pl/)? Potwierdzę, czy to odpowiednie konto.

@AureliuszBrussy Login: Pawel3017

**Comment by AureliuszBrussy** [comment]
To nie jest to konto, musisz szukać dalej :).

**Comment by jezewskiBNetrox** [comment]
> To nie jest to konto, musisz szukać dalej :).

@AureliuszBrussy Z tokena JWT mam takie coś: "user_name": "6601230"

Czy to jest identyfikator wyżej wymienionego konta?

**Comment by AureliuszBrussy** [comment]
To jest id konta Pawel3017, natomiast w JWT przechowujemy id użytkownika, do którego należy dany access token, a nie user id właściciela danego Client ID.

**Comment by jezewskiBNetrox** [comment]
> To jest id konta Pawel3017, natomiast w JWT przechowujemy id użytkownika, do którego należy dany access token, a nie user id właściciela danego Client ID.

@AureliuszBrussy Jeżeli `user_name` się zgadza, to dlaczego jest w tym samym tokenie JWT Client ID nienależący do tego `user_name`? Nie mówiąc o tym, że to ww. konto nie ma żadnego konta nadrzędnego ani nawet powiązanego. To jest konto, z którego moja integracja operuje przez ostatnie kilka lat, jak nie dłużej. Nie wziąłem sobie tych danych ze starego notatnika, na nich operuje od zawsze. Kiedy wprowadzono parcel management, na pewno nawet tą integrację NA TYM KONCIE edytowałem dla nowych uprawnień.

**Comment by AureliuszBrussy** [comment]
Access token należy do użytkownika, w którego imieniu działa aplikacja, identyfikowana przez nas po Client ID. Client ID może być zarejestrowany na dowolnym innym koncie i taka aplikacja może działać w imieniu dowolnego użytkownika. Wystarczy, że w procesie OAuth użytkownik, dla którego aplikacja generuje access token wyrazi na to zgodę. 

Tutaj właśnie mamy taki przypadek, ten Client ID nie był rejestrowany na koncie Pawel3017.

**Comment by jezewskiBNetrox** [comment]
@AureliuszBrussy Rozumiem. Jednakże z rozmowy z klientem wynika, że takiego konta nie ma. Jestem też pewien, że dokonywałem aktualizacji tego Client ID z poziomu konta Pawel3017 (uprawnienia do zasobów parcel management). Nigdy też nie logowałem się na jakiekolwiek inne konta w celach modyfikacji dokładnie tej integracji (na pozostałych znanych mi kontach nie ma tego Client ID, to też sprawdziłem). 

Coś tu jest mocno nie tak. Zakładam, że jedyne co mogę w tym wypadku zrobić to wygenerować gdzieś nową aplikację i na niej dać uprawnienia, których potrzebuje. Jestem jednak pewien, że ta integracja powinna być na Pawel3017.

**Comment by AureliuszBrussy** [comment]
Aplikacja 6d22e583b88849c3983534706b2abdad zawsze była zarejestrowana na innym koncie, nie ma tutaj mowy o pomyłce z naszej strony. Jeżeli nie jesteś w stanie w tym momencie ustalić, co to za konto (niestety, ale nie mogę udzielić takiej informacji) to faktycznie do rozważenia jest opcja utworzenia nowego Client ID i podmienienia go w samej aplikacji.

**Comment by jezewskiBNetrox** [comment]
> zawsze była zarejestrowana na innym koncie

@AureliuszBrussy Jakimś cudem mogłem edytować tą integrację z poziomu konta Pawel3017. I to wcale nie tak dawno, bo WzA nie było integrowane od razu u tego klienta. Nie wiem, jak to możliwe ale naprawdę - zajmuje się tym od dawna i o ile nie pamiętam dokładnie gdzie i kiedy tworzyłem aplikację ale na pewno dokonywałem zmian w uprawnieniach, ponieważ były wymagane do pracy z parcel-management. 

Upewniłem się wielokrotnie co do tego Client ID, nie widnieje nigdzie choćby częściowo podobne. 
W każdym razie wygląda na to, że nic więcej nie zdziałam poza sugerowanym rozwiązaniem. 
Zamykam i dziękuję za odpowiedzi.
