### ISSUE TITLE
Brak zamówień z allegro

### ISSUE THREAD

**Issue by squishfunk** [allegro/allegro-api#7776]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Nie jesteśmy w stanie pobrać tych konkretnych zamówień przez endpoint /order/events

4d2219d0-6c09-11ee-97f9-71fc2050ecba
515b8fb0-6c07-11ee-99f0-e59fd30abb46
65e6d740-6bf9-11ee-9e1b-75dcdaf5050d
63e96af0-6b88-11ee-b726-eb8ae90bccc9
ba5c1360-6b56-11ee-98a1-1b99a6933963
e56c5c50-699d-11ee-b0d1-a150868dd0d1
404c6410-6937-11ee-944f-8f8aaeeb2c78
5852b050-6923-11ee-955e-d544f30d6fa9
4027b6f3-68e8-11ee-8eeb-178d221303c2
b700f9f0-68c3-11ee-bbd6-1103d1757491
5c770340-68ef-11ee-89f6-8b6458f23755
01fba670-68b6-11ee-a1a5-4d7acc30b115
1a535360-6868-11ee-b166-35f9e46bff2b
b588deb2-685c-11ee-a1a5-4d7acc30b115
03257320-6837-11ee-8260-77f5b5733a57
0c030360-683a-11ee-a89c-d1b11c0fe493
e14b18f0-6858-11ee-9e77-35b93cc4171f
91909da1-686a-11ee-a89c-d1b11c0fe493
66516420-6870-11ee-9e77-35b93cc4171f
e91c4e00-6876-11ee-bbd6-1103d1757491
70402c20-6909-11ee-bc40-6fa5029cf009
aa6ff070-6935-11ee-b149-137dbc6a2402
90000440-6a67-11ee-98a1-1b99a6933963
c2dad890-69ea-11ee-b149-137dbc6a2402
da421c00-6b52-11ee-98a1-1b99a6933963
0e688e41-6b46-11ee-b726-eb8ae90bccc9
87e0de30-6ab5-11ee-b726-eb8ae90bccc9
2b281d10-6a93-11ee-b726-eb8ae90bccc9
2f9a06d0-6b3b-11ee-9e26-1dfad1b952ef
68040ce0-6a83-11ee-bab2-ad1dbfbca9d6

Co jest tego powodem?

przykładowy trace-id: 660815bd8239365

**Comment by AureliuszBrussy** [comment]
Nie potwierdzam tego problemu - sprawdziłem wyrywkowo te zamówienia i wygenerowaliśmy dla nich eventy prawidłowo.

**Comment by squishfunk** [comment]
to dlaczego w przypadku wywołania 660815bd8239365 nie zostały zwrócone?
Jeśli tutaj chodzi o parametr limit=1000 to w jaki sposób mogę ustawić offset? W dokumentacji nie podajecie takiego parametru

**Comment by AureliuszBrussy** [comment]
Nie ma offsetu. Zwracamy eventy od najstarszego przechowywanego do najnowszego. Możesz sprawdzać kolejne porcje eventów korzystając z parametru _from_ i podając w nim id najnowszego widzianego eventu (np. z końca pierwszej pobranej porcji). 

Zakładamy, że aplikacja np. zapisuje id ostatnio widzianego eventu, za pomocą GET /order/event-stats sprawdza, czy ostatnio widziany event się zmienił. Jeżeli się zmienił, to dzięki parametrowi _from_ pobiera zdarzenia, które wystąpiły po ostatnim zapisanym zdarzeniu (jednocześnie podmieniając id ostatnio widzianego eventu).

**Comment by squishfunk** [comment]
Oczywiście że zapisuje. Ostatni event id jest zapisywany a później przekazywany w 
```php
'/order/events?from='.$lastEvent.'&limit=1000'
```
Gdzie mam szukać błędu? Próbowałem resetować parametr "from=" ażeby eventy zaczytaly się ponownie od zera. W logach brak któregokolwiek z ww. ID

**Comment by AureliuszBrussy** [comment]
@squishfunk już widzę w czym rzecz - używasz access tokenu, który należy do innego użytkownika (przynajmniej na przykładzie trace-id: 660815bd8239365). Musisz wygenerować access token właściciela tych zamówień.

**Comment by squishfunk** [comment]
@AureliuszBrussy jakie to ma znaczenie czyjego tokena używam przy '/order/events?from='.$lastEvent.'&limit=1000'. Robimy iteracje po każdym koncie allegro w naszym systemie. Zgodnie z waszą dokumentacją ten endpoint tak czy tak powinien zwrócić wszystkie zamówienia

Taki przykład zamówienie: ni1012e280-724f-11ee-87dc-a51ed97be852
1. trace-id: ff415a53ca07f16f  Pierwszy użytkownik brak powyższego zamówienia.
2. trace-id: 4e64f099b679ccb9 Drugi użytkownik brak powyższego zamówienia.

Rzecz jasna te 2 przypadki zapisują lastEventId dla każdego z kont oddzielnie i kontunuują zapytania do API. Trace id podałem dla pierwszych wyników requesta po resecie dziennika zdarzeń

Możecie też zweryfikować że za każdym razem reqest ma inny "Authorization: Bearer" odpowiadający danemu użytkownikowi

**Comment by MaciejFrackowiak** [comment]
Zacznę od odniesienia się do drugiego Twojego posta:
- zamówienie "92890e20-700f-11ee-948c-e3b8932a9b47" należy do konta "xxxx1133", a próbowałeś je pobrać będąc zautoryzowanym na koncie "xxxx6386" - prawidłowo zatem otrzymałeś błąd 404 Not Found.

[GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET) zwraca dane dla zautoryzowanego użytkownika (wymaga "bearer-token-for-user"), a to oznacza, że będąc zautoryzowany jako konto A otrzymasz dane z konta A, adekwatnie dla B - B, itd.

Zamówienie "1012e280-724f-11ee-87dc-a51ed97be852" należy do konta "xxxx8756" i:
- trace-id=ff415a53ca07f16f - tu byłeś zalogowany na właściwym koncie, ale użyłeś niewłaściwych parametrów "from=0&limit=1000" - from 0 oznacza pierwszy event jakikolwiek zwracany przez zasób, na pewno nie jest to wartość uznana jako ostatni pobrany event;
- trace-id=4e64f099b679ccb9 - tu pobrałeś eventy dla konta "xxxx2205", zatem nie mogłeś zobaczyć szczegółów zamówienia, które należy do konta "xxxx8756". I tu również użyłeś nieprawidłowego parametru from - mianowicie "from=0&limit=1000".
