### ISSUE TITLE
Wypłaty za przesyłki pobraniowe Allegro Standard

### ISSUE THREAD

**Issue by invital** [allegro/allegro-api#7777]
Hi,
could I ask you to help find method which return me list of "Wypłaty za przesyłki pobraniowe Allegro Standard".
I am not able find it in documentation: https://developer.allegro.pl/documentation

I will use it for automatic import into our CRM system - for accountancy.
https://allegro.pl/moje-allegro/sprzedaz/wyplaty/przesylki-pobraniowe-wysylam-z-allegro

Thank you.

**Comment by AureliuszBrussy** [comment]
We do not yet provide such an endpoint in Allegro's public API, so there is currently no way to retrieve such information in the API.
