### ISSUE TITLE
Problem ze spedycją 

### ISSUE THREAD

**Issue by Matejko1991** [allegro/allegro-api#7778]
Dzień dobry, przy próbie nadania wysyłki: Allegro Wysyłka z Polski do Czech - Odbiór w Punkcie Packeta, otrzymujemy komunikat widoczny poniżej: 

"trace-id" => array:1 [▼
    0 => "8cd16e1c51726cd6"
  ]

request:

array:6 [▼
  "deliveryMethodId" => "714d388f-6ef4-4bc0-a424-36d2032265ad"
  "sender" => array:9 [▼
    "name" => "xxx"
    "company" => "xxx"
    "street" => "xxx"
    "streetNumber" => "xxx"
    "postalCode" => "xxx"
    "city" => "xxx"
    "countryCode" => "PL"
    "email" => "xxx"
    "phone" => "xxx"
  ]
  "receiver" => array:10 [▼
    "company" => "xxx"
    "street" => "xxx"
    "streetNumber" => ""
    "postalCode" => "xxx"
    "city" => "xxx"
    "countryCode" => "CZ"
    "email" => "xxx"
    "phone" => "xxx"
    "name" => "xxx"
    "point" => "xxx"
  ]
  "packages" => array:1 [▼
    0 => array:5 [▼
      "type" => "PACKAGE"
      "weight" => array:2 [▼
        "value" => "1"
        "unit" => "KILOGRAMS"
      ]
      "length" => array:2 [▼
        "value" => 18
        "unit" => "CENTIMETER"
      ]
      "width" => array:2 [▼
        "value" => 32
        "unit" => "CENTIMETER"
      ]
      "height" => array:2 [▼
        "value" => 36
        "unit" => "CENTIMETER"
      ]
    ]
  ]
  "referenceNumber" => "ZWM 2509_2023"
  "labelFormat" => "PDF"
]

odpowiedz:
array:1 [▼
  "result" => {#3111 ▼
    +"commandId": "48274a98-5562-4e41-9989-d884049d2ad2"
    +"status": "ERROR"
    +"errors": array:1 [▼
      0 => {#3096 ▼
        +"code": "PROCESSING_ERROR"
        +"message": "Problem with dispatch. Contact us, and we will help as soon as possible."
        +"details": null
        +"path": null
        +"userMessage": "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."
      }
    ]
    +"shipmentId": null
  }
]

Co może wywoływać taki problem?

**Comment by AureliuszBrussy** [comment]
Dla przesyłek Packeta niezbędne jest zdefiniowane ubezpieczenia (insurance). Zrób to w walucie CZK.
