### ISSUE TITLE
WZA: błąd przetwarzania parcel-management/parcel-pickup-request-commands, Orlen Paczka

### ISSUE THREAD

**Issue by mmodrzejewski** [allegro/allegro-api#7779]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,

To znowu ja, tym razem zgłaszam problem związany z tworzeniem zleceń odbioru dla kuriera.
https://developer.allegro.pl/documentation/#operation/requestParcelPickup

Pomijając fakt, że wbrew temu, jakoby Orlen nie obsługiwał dat, a API je zwraca...

`parcel-management/pickup-date-proposals?parcelId=5dea5846-ad06-4ef7-acbb-ec76e9edd7ec: {"pickupDateProposals":[{"parcelId":"5dea5846-ad06-4ef7-acbb-ec76e9edd7ec","proposals":[{"date":"2023-10-17","minTime":"09:30","maxTime":"16:00"},{"date":"2023-10-18","minTime":"08:00","maxTime":"16:00"}]}]}`

...to zarówno przy oficjalnych sposobach (bez daty w żadaniu), jak i z wypełnionym terminem, zawsze otrzymujemy:
`{ "code": "ERROR", "message": "Pickup request failed", "details": null, "path": "parcelIds[%s]", "userMessage": "Nie udało się złożyć zlecenia odbioru" }`
przykładowa próba:
6c172c98-01c4-4b0b-ab01-cfe8532cf26e

Dotyczy 
serviceId
04c33651-bd96-484b-a89b-06a797d8eff4
w ramach parcelId
5dea5846-ad06-4ef7-acbb-ec76e9edd7ec

Orlen wskazuje, że kod 93-570 jest obsługiwany
https://www.orlenpaczka.pl/odbiory-kurierskie/

Proszę o wyjaśnienie sytuacji, pozdrawiam

**Comment by AureliuszBrussy** [comment]
Wyjaśniam to z odpowiednim zespołem. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Dziękuję za cierpliwość. Jest to problem po stronie przewoźnika. W zwracanym przez nich błędzie chodzi najprawdopodobniej o brak imienia i nazwiska (w requeście w tych polach podana została nazwa firmy), przez co Orlen odrzuca request zamówienia podjazdu.
