### ISSUE TITLE
sale/categories?parent.id= 

### ISSUE THREAD

**Issue by Rnapzsih** [allegro/allegro-api#778]
Co powinien zwracać zasób `sale/categories?parent.id=` jeżeli jako id podamy id kategorii najniższego rzędu, np id **257528**? 

Ja dostaje takiego response: `{"categories":[]}`

**Comment by PawelTaberski** [comment]
Tak, to poprawne działanie oznacza, że ta kategoria nie ma już kategorii niższego rzędu.

**Comment by Rnapzsih** [comment]
Czy przewidujecie zasób do pobierania informacji na temat danej kategorii po jej id np.  `sale/categories?id=` ? 
Czemu w przypadku podanej błędnego numeru kategorii w `sale/categories?parent.id=` response jest `{"categories":[]}` 

A teraz `https://api.allegro.pl/sale/categories/'.$id.'/parameters` gdzie id daje np **123** (Wyposażenie Domu i Ogrodu) dostaje response `{"parameters":[{"id":"11323","name":"Stan","type":"dictionary","required":true,"unit":null,"options":{"variantsAllowed":true,"variantsEqual":false},"dictionary":[{"id":"11323_1","value":"Nowy"},{"id":"11323_2","value":"Używany"}],"restrictions":{"multipleChoices":false}},{"id":"17448","name":"Waga (z opakowaniem)","type":"float","required":false,"unit":"kg","options":{"variantsAllowed":true,"variantsEqual":false},"restrictions":{"min":0.0,"max":1000000.0,"range":false,"precision":2}},{"id":"219809","name":"Kod produktu","type":"string","required":false,"unit":null,"options":{"variantsAllowed":false,"variantsEqual":false},"restrictions":{"minLength":1,"maxLength":50,"maxValues":10,"multipleChoices":false}}]}`

Czy to jest poprawna odpowiedź? Nie widać, że **123** nie jest kategorią najniższego rzędu. 

Zdarzyło wam się zmienić drzewo kategorii (Lampy) i z kategorii najniższego rzędu zrobić kategorię nadrzędną. W związku z tym, jak posiadając id sprawdzić czy kategoria jest najniższego rzędu.

**Comment by Rnapzsih** [comment]
Dobra znalazłem w opisie - Wielowariantowość w REST API - [https://developer.allegro.pl/news/2018-07-09-Wielowariantowosc/#01](url) informacje na temat zasobu /sale/categories/{categoryId}. To by rozwiązywało jeden problem. Możecie poprawić link w [https://developer.allegro.pl/documentation/#/offer-management/getCategoryUsingGET_1](url) - you can find here - to odnosi się do przykładu z innym zasobem.

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem co masz na myśli gdzie dokładnie źle opisaliśmy w dokumentacji? Oczywiście poprawimy.

**Comment by Rnapzsih** [comment]
1. https://developer.allegro.pl/documentation/#/offer-management/getCategoryUsingGET_1 przekierowuje do https://developer.allegro.pl/sale/#categories gdzie jest opisany zasób `sale/categories?parent.id={categoryId}` a nie `/sale/categories/{categoryId}` 
2. Opis zasobu `/sale/categories/{categoryId}` znajduje się tutaj https://developer.allegro.pl/news/2018-07-09-Wielowariantowosc/#01 
3. Czemu w przypadku podania błędnego numeru kategorii w sale/categories?parent.id= response jest `{"categories":[]}`
4. Czemu w przypadku podania id kategorii nadrzędnej np **123** w zasobie `sale/categories/'.$id.'/parameters ` dostaje odpowiedź `{"parameters":[{"id":"11323","name":"Stan","type":"dictionary","required":true,"unit":null,"options":{"variantsAllowed":true,"variantsEqual":false},"dictionary":[{"id":"11323_1","value":"Nowy"},{"id":"11323_2","value":"Używany"}],"restrictions":{"multipleChoices":false}},{"id":"17448","name":"Waga (z opakowaniem)","type":"float","required":false,"unit":"kg","options":{"variantsAllowed":true,"variantsEqual":false},"restrictions":{"min":0.0,"max":1000000.0,"range":false,"precision":2}},{"id":"219809","name":"Kod produktu","type":"string","required":false,"unit":null,"options":{"variantsAllowed":false,"variantsEqual":false},"restrictions":{"minLength":1,"maxLength":50,"maxValues":10,"multipleChoices":false}}]}`

**Comment by PawelTaberski** [comment]
Teraz rozumiem, oczywiście przy kolejnym wdrożeniu poprawimy. 
Odnośnie Twoich pytań to:
4 - są to parametry nadrzędne dodane do działów, które są we wszystkich podkategoriach takiego działu.
3 - odnośnie tego przypadku uważaliśmy, że jeśli przechodzisz z kategorii wyższego rzędu na niższą i tak dalej, to nie ma możliwości wbicia błędnego id. Jednakże w przypadkach przechowywania drzewa i zmian może to rzeczywiście wprowadzać zamieszanie. Wprowadzimy zmianę abyś wtedy otrzymał 404. 
Prosimy o cierpliwość.

**Comment by Rnapzsih** [comment]
Dzięki za informacje.
