### ISSUE TITLE
issue about 403 Access denied when call /sale/product-offers POST API in sandbox

### ISSUE THREAD

**Issue by xiaolengbuleng** [allegro/allegro-api#7780]
hi,
this is my request and response param,

url= https://api.allegro.pl.allegrosandbox.pl/sale/product-offers  POST

request={"afterSalesServices":{"impliedWarranty":{"id":"b97c57aa-650e-4489-ac66-a1c1268e0a5b"},"returnPolicy":{"id":"21f186ab-5e29-44f6-9c00-228b0f7d58e9"},"warranty":{}},"delivery":{"handlingTime":"P7D","shippingRates":{"id":"c4d6984d-7e5e-4428-bb1e-7822f7a8439f"}},"description":{"sections":[{"items":[{"content":"<p>a text content</p>","type":"TEXT"},{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/11c84e/744295d74bbd8f097fad2e048217"}]}]},"location":{"city":"Gorzów Wielkopolski","countryCode":"PL","postCode":"66-400","province":"LUBUSKIE"},"parameters":[{"id":"11323","name":"Condition","valuesIds":["11323_1"]}],"payments":{"invoice":"NO_INVOICE"},"productSet":[{"product":{"category":{"id":"258919"},"images":["https://a.allegroimg.allegrosandbox.pl/original/11c84e/744295d74bbd8f097fad2e048217"],"name":"test shirt 1010 hhh","parameters":[{"id":"17448","name":"Weight (with packaging)","values":["3.2"]},{"id":"3946","name":"Brand","values":["test"],"valuesIds":["3946_40"]},{"id":"54","name":"Size","valuesIds":["54_2"]},{"id":"249512","name":"Color","valuesIds":["249512_1647414"]},{"id":"249513","name":"Shade","valuesIds":["249513_1647430"]}]}}],"taxSettings":{"rates":[{"countryCode":"PL","rate":"23.00"},{"countryCode":"CZ","rate":"21.00"},{"countryCode":"SK","rate":"EXEMPT"}],"subject":"GOODS"}}

response={"errors":[{"code":"OfferAccessDeniedException","message":"Forbidden","details":null,"path":"","userMessage":"Access denied. You are not authorized to perform operations on the indicated offer"}]}

my sandbox  clientId is 8ecde7d2e6ff46348bc5e0fd4536c45b

please tell me how to fix this issue,thank you

**Comment by AureliuszBrussy** [comment]
You use a regular account, which is intended for buyers. [Register and activate a new company account](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F).

**Comment by xiaolengbuleng** [comment]
> You use a regular account, which is intended for buyers. [Register and activate a new company account](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F).

this is my new comapny account：yw_www@163.com，can you help me to activate this account in sandbox
