### ISSUE TITLE
Problem z nadaniem przesyłki

### ISSUE THREAD

**Issue by mniedzwiedzki** [allegro/allegro-api#7781]
Hej, mam problem z nadaniem przesyłki po sprzedaży na allegro sandbox. Sposób dostawy to Allegro miniKurier24 InPost, po kliknięciu "nadaj przesyłkę" nie ładuje mi się strona: https://manager.paczkomaty.pl.allegrosandbox.pl/allegro/import-auctions.
![image](https://github.com/allegro/allegro-api/assets/44301070/5c6989a1-b9ac-4303-839d-5ae41783766a)

**Comment by AureliuszBrussy** [comment]
Widzę, że na jakimś etapie następuje przekierowanie do InPostu (do url przekierowania natomiast dorzucamy domenę allegrosandbox.pl, dlatego nie ładuje się strona). Korzystasz z opcji "NADAJ PRZESYŁKĘ" z poziomu zakładki "Zamówienia"? Dodawałeś wcześniej testową umowę InPostu (wymaga dostępu do testowego API ShipX)?

**Comment by mniedzwiedzki** [comment]
Tak, korzystam z opcji "nadaj przesyłkę" z tej zakładki. Nie dodawałem testowej umowy InPostu. Używam metody dostawy z sekcji "Oferta specjalna Allegro - InPost" - nic nie wskazuje na wymaganą umowę, czy to konieczne?

**Comment by AureliuszBrussy** [comment]
Tak, nadanie nawet na ofercie specjalnej Allegro wymaga dodania umowy własnej InPostu z [poziomu zakładki](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia). Na środowisku testowym można podać dane testowe otrzymane od InPostu.
