### ISSUE TITLE
Zapytanie przez cURL i żądanie CAPTCHA

### ISSUE THREAD

**Issue by stalkerGH** [allegro/allegro-api#7782]
Zarejestrowałem aplikację typu device na swoim koncie Allegro, autoryzacja jest wykonana, teraz próbuję pobrać listę ofert. Zapytanie jest następujące:

curl -X GET -H "Accept: application/vnd.allegro.public.v1+json" -H "Authorization: Bearer <tutaj wstawić token>" https://allegro.pl/sale/offers

Otrzymuję odpowiedź:

<html>
<head>
<title>allegro.pl</title>
<style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style>
</head>
<body style="margin:0">
<p id="cmsg">Please enable JS and disable any ad blocker</p>
<script data-cfasync="false">var dd={'rt':'c','cid':'AHrlqAAAAAMAQifO06JAEhEAufXCMg==','hsh':'77DC0FFBAA0B77570F6B414F8E5BDB','t':'bv','s':29560,'e':'8193acf1accbd5b29b48d8862a98e9f3180a362d033641567352aa42a12aed88','host':'geo.captcha-delivery.com'}</script>
<script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script>
</body>
</html>

Rozumiem, że na sandboksie nie ma tego typu ograniczeń, bo tam pobierałem oferty bez żadnych ograniczeń i pytań. Jak sobie z tym poradzić na koncie produkcyjnym, jeśli używam tylko cURL?

**Comment by Lukasz-Zurek** [comment]
Korzystasz z błędnego adresu. Do wywołania zasobów API Allegro służy adres https://api.allegro.pl/ (lub https://api.allegro.pl.allegrosandbox.pl/ na Sandbox).

**Comment by stalkerGH** [comment]
Racja! Wcześniej, do autoryzacji i uzyskania tokena, używałem https://allegro.pl i ten adres skopiowałem do kolejnych komend.
Dziękuję za podpowiedź :)
