### ISSUE TITLE
Error message "The title contains forbidden characters: ™"

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#7783]
Hi all, 

our software helps customers to upload products to Allegro but when we tried to send one product, we got error message "The title contains forbidden characters: ™" even though we do not send the title and description via API to Allegro since we are only connecting it to already existing product cards. So we are probably getting an error message for another customer (who created the original offer) - but this customer was able to post the offer even with the forbidden character: https://allegro.cz/nabidka/baby-einstein-hraci-podlozka-4v1-14017691733.

So how come we are getting this error message when the offer already exists on Allegro? 

Thank you in advance!

**Comment by Lukasz-Zurek** [comment]
Could you send me a trace-id of this error? As you have already written - the product name contains "™" character. But the offer's title which you've just sent is "Baby Einstein hrací podložka 4v1", without "™" character. Having a trace-id - I will be able to check it out closely in our logs. Maybe the validation on our side has been changed through the time or there is a different issue.

**Comment by dominikahr** [comment]
What do you mean that the ™" character is not there? I still see it in the offer:
![Baby-Einstein-hrací-podložka-4v1-za-503-Kč-Allegro](https://github.com/allegro/allegro-api/assets/147524238/f801f906-c05c-46e1-8dee-70bfb1f7c4c6)

**Comment by dominikahr** [comment]
We have this info: 
code = ConstraintViolationException.CharacterNotAllowed
userMessage = The title contains forbidden characters: ™

But seems weird to me that the we cannot connect our offer to this one, when we are not even sending the title and description to Allegro. It already exists even with the "™" character.

**Comment by Lukasz-Zurek** [comment]
@dominikahr It is not an offer title. It is a product's name. There is a different between the offer and the product. You can list an offer and assign a product to it.

You have to provide your own title for the offer, then you will be able to list it.

But obviously in the product's data there is a mistake and "™" should not be there (as it causes a problem while listing an offer). I will report it. Thank you.
