### ISSUE TITLE
Pytanie o zamówienia

### ISSUE THREAD

**Issue by AdrianeZ** [allegro/allegro-api#7784]
Hej, planuję napisać integrację pomiędzy systemem ERP i Państwa API aby pobierać i procesować zamówienia. Integracja będzie odbywać się dla wielu kont stąd mam pytania

1. Czy identyfikator checkoutForm.id jest unikalny (niezależny od konta). W sensie na koncie x nie może być takiego samego id jak na koncie y? Czy unikanlność jest na konto?
2. To samo pytanie jesli chodzi o lineItem.id
3. Czy zanim wystąpi zdarzenie READY_FOR_PROCESSING - (Kiedy otrzymuje zdarzenie BOUGHT lub FILLED_IN) powinienem już pobierać dane takie jak płatność, dane do wysyłki oraz dane do faktury? A kiedy dostanę już zdarzenie READY_FOR_PROCESSING je edytować? Co może się zmienić pomiędzy statusami (BOUGHT i FILLED_IN) a READY_FOR_PROCESSING?

**Comment by Lukasz-Zurek** [comment]
1. Tak, identyfikator ten jest unikalny.
2. Tak.
3. Statusy opisaliśmy w naszym poradniku, [tutaj](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#dziennik-zdarzen). 

_Czy zanim wystąpi zdarzenie READY_FOR_PROCESSING - (Kiedy otrzymuje zdarzenie BOUGHT lub FILLED_IN) powinienem już pobierać dane takie jak płatność, dane do wysyłki oraz dane do faktury?_ - Nie.

_A kiedy dostanę już zdarzenie READY_FOR_PROCESSING je edytować?_ - Gdy wystąpi zdarzenie READY_FOR_PROCESSING - nie możesz zmienić danych (tj. Klient nie ma takiej możliwości, np. jako Sprzedający możesz pobrać dane dla tej transakcji, by realizować zamówienie).

_Co może się zmienić pomiędzy statusami (BOUGHT i FILLED_IN) a READY_FOR_PROCESSING?_ - Przełożyłbym to również na to, w jaki sposób działa ów proces w Serwisie Allegro. Klient kupuje w ofercie, ale nie realizuje jeszcze płatności. W tym momencie może się zmienić wszystko - Kupujący w [wybranych sytuacjach](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/anulowanie-zakupu-informacje-dla-sprzedajacych-KMOZGKlO5fR) może anulować zakup, więc pojawi się status BUYER_CANCELLED, czyli nie dojdzie w ogóle do READY_FOR_PROCESSING. Jest jeszcze sytuacja, w której Klient anuluje płatność i ponownie wypełni formularz dostawy i zapłaty, czyli ponownie pojawi się status FILLED_IN. Do momentu zrealizowania płatności - nie dojdzie do momentu pojawienia się statusu READY_FOR_PROCESSING.

**Comment by AdrianeZ** [comment]
Mam okazję podpatrzeć jak robi to system baselinker, tam mimo że zamówienie przez płatnośc online np P24 nie jest opłacone - dane do faktury i wysyłki są już wyświetlane. Rozumiem że nie jest to do końca zalecane?

**Comment by Lukasz-Zurek** [comment]
Nie jest to konieczne, ponieważ te dane i tak ostatecznie nie zostaną wykorzystane w celu realizacji zamówienia. Ewentualnie jeśli chcesz pobierać te dane wcześniej, to i tak musisz je nadpisać danymi po otrzymaniu statusu READY_FOR_PROCESSING (bo dane mogą się zmienić).

Dodam jeszcze, że READY_FOR_PROCESSING jest po zrealizowaniu płatności, lub, gdy Klient wybrał płatność przy odbiorze lub odbiór osobisty.

**Comment by AdrianeZ** [comment]
Rozumiem ostatnie pytanie a czy pole lineItems może się jakkolwiek zmieniać w czasie cyklu życia zamówienia?

**Comment by Lukasz-Zurek** [comment]
Nie. Dodam jednak, że jeden lineItem.id może występować w kilku zamówieniach - jednakże wyłącznie w sytuacji połączenia zakupów przez kupującego.

**Comment by AdrianeZ** [comment]
Mam jeszcze pytanie związane z dopłatami. Rozumiem że jeżeli zostanie wpłacone mniej niż całkowita wartość zamówienia, jest możliwe zrobienie - dopłaty przez użytkownika. W poradniku jest napisane żeby porównywać pola summary.totalToPay.amount oraz payment.paidAmount.amount w obiekcie checkout-form. Jeżeli wartość drugiego pola jest za wysoka pozostaje zwrot środków, a jeżeli jest niedopłata rozumiem że dostanę kolejny event READY_TO_PROCESSING z dodatkowym polem surcharges oraz pole surchages także pojawi się w obiekcie checkoutForm?

**Comment by Lukasz-Zurek** [comment]
W przypadku dopłaty pojawi się drugie zdarzenie READY_FOR_PROCCESING, ponieważ w formularzu dostawy i zapłaty zmienią się **surcharges** i **updatedAt**.

Niedopłata może powstać w wyniku przelewu tradycyjnego, w którym Klient pomyli kwotę i wyślę niższą. Tutaj również otrzymasz zdarzenie READY_FOR_PROCCESING. Należy w tej sytuacji porównać kwoty z pól **summary.totalToPay.amount** i **payment.paidAmount.amount**.

**Comment by AdrianeZ** [comment]
Czy dobrze rozumiem po dopłacie dostanę kolejne zdarzenie READY_FOR_PROCCESING. W obiekcie checkoutForm zmieni się obiekt surchages, zostanie zwiększone pole payment.paidAmount.amount o wartość dopłaty. Załóżmy że summary.totalToPay.amount = 39.99. Przed dopłatą pole payment.paidAmount.amount było 29.99 została wykonana dopłata - dostaje zdarzenie READY_FOR_PROCCESING - pobieram szczegóły zamówienia i już w polu payment.paidAmount.amount jest wartość 39.99 którą mogę porównać z summary.totalToPay.amount?

**Comment by Lukasz-Zurek** [comment]
W przypadku dopłaty, w dzienniku zdarzeń pojawi się kolejne zdarzenie READY_FOR_PROCESSING. W obiekcie surcharges pojawi się kwota dopłaty, jednakże w polu payment.paidAmount.amount nie zwiększymy kwoty o kwotę dopłaty - to należy wyliczyć samodzielnie.
