### ISSUE TITLE
WzA Allegro One Box PROCESSING_ERROR

### ISSUE THREAD

**Issue by righttway** [allegro/allegro-api#7785]
Występuje problem:

 z zasobem REST API / with a REST API resource
 ze środowiskiem produkcyjnym / with the production environment

Dzień dobry, 
nie możemy nadać przesyłki / wygenerować etykiety dla Allegro One Box AL007WXY. Dostajemy odpowiedź która nic nie mówi o błędnym zapytaniu, lub błędach w zapytaniu.

{"id":"04f6ad0f-1aec-47fc-9f0f-bd8f9d079161","parcelId":null,"status":"ERROR","errors":[{"code":"PROCESSING_ERROR","message":"Problem with dispatch. Contact us, and we will help as soon as possible.","details":null,"path":"","userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}]}

Czy mogę prosić o podpowiedź?

**Comment by MaciejFrackowiak** [comment]
W requeście przekazujesz nieprawidłowe id metody dostawy - w zamówieniu widnieje Allegro One Box, One Kurier - a przekazujesz id "0aafb43c-e66a-46ec-9cc4-29bb39ebb483" odpowiadające "Allegro One Box".

**Comment by righttway** [comment]
Dziękuję Bardzo!
