### ISSUE TITLE
Nadanie Allegro czechy wielopaczek wraca z bledem

### ISSUE THREAD

**Issue by Pawelpwg** [allegro/allegro-api#7786]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

ponizej request response, przy dodaniu kolejnej podpaczki wraca blad ktory duzo nie mowi

2023-10-17 15:52:51,838 [ 23 ] INFO Main Logger - [ ITSmart.Kurier.Allegro.OneBox.AllegroOneBoxFacade ]: AllegroRequest: {
  "serviceId": "714d388f-6ef4-4bc0-a424-36d2032265ad",
  "receiver": {
    "address": {
      "street": "",
      "postCode": "",
      "city": "Praha ",
      "countryCode": "CZ",
      "country": null
    },
    "email": "1dwclwuo4c+1823d3242@allegromail.pl",
    "name": "Petra ",
    "company": "",
    "phone": "+",
    "pointId": "485"
  },
  "pickup": {
    "address": {
      "street": " 892A - ",
      "postCode": "",
      "city": "",
      "countryCode": "PL",
      "country": null
    },
    "email": "",
    "name": "",
    "company": ".",
    "phone": "",
    "pointId": null
  },
  "items": [
    {
      "dimensions": {
        "height": {
          "value": 30,
          "unit": "CENTIMETER"
        },
        "width": {
          "value": 30,
          "unit": "CENTIMETER"
        },
        "depth": {
          "value": 30,
          "unit": "CENTIMETER"
        }
      },
      "weight": {
        "value": "3.00",
        "unit": "KILOGRAM"
      },
      "description": "Client:112211309",
      "value": {
        "amount": "278.00",
        "currency": "CZK"
      },
      "type": "PACKAGE",
      "waybill": null
    },
    {
      "dimensions": {
        "height": {
          "value": 30,
          "unit": "CENTIMETER"
        },
        "width": {
          "value": 30,
          "unit": "CENTIMETER"
        },
        "depth": {
          "value": 30,
          "unit": "CENTIMETER"
        }
      },
      "weight": {
        "value": "3.00",
        "unit": "KILOGRAM"
      },
      "description": "Client:112211309",
      "value": {
        "amount": "278.00",
        "currency": "CZK"
      },
      "type": "PACKAGE",
      "waybill": null
    }
  ],
  "type": "PACKAGE",
  "label": null,
  "additionalServices": null
} 2023-10-17 15:52:52,279 [ 23 ] INFO Main Logger - [ ITSmart.Kurier.Allegro.OneBox.AllegroOneBoxFacade ]: Response - Status: {
  "id": "e6132254-e0b0-40b6-b8ff-10dbf6766797",
  "parcelId": null,
  "status": "ERROR",
  "errors": [
    {
      "code": "PROCESSING_ERROR",
      "message": "Problem with dispatch. Contact us, and we will help as soon as possible.",
      "details": null,
      "path": "",
      **"userMessage": "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."**
    }
  ]
}

**Comment by MaciejFrackowiak** [comment]
Przewoźnik Packeta nie obsługuje tzw. wielopaczki. Dla każdej paczki musisz wygenerować osobny request.
