### ISSUE TITLE
AccessDeniedException - on new sandbox account

### ISSUE THREAD

**Issue by zakjar** [allegro/allegro-api#7787]
My Client ID on sandbox is
317055e0afd64c9680961b5bf7c568f8

Account : rejzr

I test API and URL https://api.allegro.pl.allegrosandbox.pl/sale/categories  works OK

but URL https://api.allegro.pl.allegrosandbox.pl/sale/products?phrase=obuv 

{"errors":[{"code":"AccessDeniedException","message":"Access denied.","details":null,"path":null,"userMessage":"No access."}]}

Please review my account to enable testing of all API features

**Comment by PrzemyslawLukanowski** [comment]
Please set up the payout settings using [this tab](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat) and make a payment transfer via our payment simulator. The bank account number can of course be fake. After that, we will be able to activate your account.

Also, it seems that you are using client_credentials type of authorization. To have access to resources that are marked as "bearer token for user" in our documentation use [code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow.

**Comment by zakjar** [comment]
I set bank account ( payment transfer) ... where is payment simulator to confirm account ?  

Client ID I get via https://apps.developer.allegro.pl.allegrosandbox.pl/ ... and I check all checboxes  ( all rights ).  That's the wrong way ?

**Comment by PrzemyslawLukanowski** [comment]
> I set bank account ( payment transfer) ... where is payment simulator to confirm account ?

Thank you, that was enough to activate your account.

> Client ID I get via https://apps.developer.allegro.pl.allegrosandbox.pl/ ... and I check all checboxes ( all rights ). That's the wrong way ?

This is the correct way, your application was registered properly, but I am actually mentioning a different step, the step after - authorizing the application to generate tokens. You have used the [client credentials ](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#clientcredentials-flow)type of authorization, which does not have the user context and it gives you access only to resources marked as "bearer token for application" in our documentation:

<img width="486" alt="Zrzut ekranu 2023-10-19 o 07 34 58" src="https://github.com/allegro/allegro-api/assets/51473661/832844ed-cafb-4fe3-8de8-9913e2f61fbd">
<img width="347" alt="Zrzut ekranu 2023-10-19 o 07 35 15" src="https://github.com/allegro/allegro-api/assets/51473661/5cc9c145-d2ea-41fa-8b93-d027b7ad09ae">

To have access to other endpoints, marked as "bearer token for user", you need to generate a token using [code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow. Thanks to that your token will have user context, and you will be able to, for example, create offers.
