### ISSUE TITLE
Numer listu przewozowego Allegro One z WzA

### ISSUE THREAD

**Issue by areklal** [allegro/allegro-api#7788]
Adresuję przez API Wysyłam z Allegro metodami Allegro One Box, One Kurier   ,    Allegro One Punkt, One Kurier    ,     Allegro One Kurier - dostawa jutro.  Adresacja przebiega pomyślnie, pobieram stiker w pdf. Jak mogę uzyskać przez API WzA numer listu przewozowego (waybill) zaadresowanej paczki??

**Comment by PrzemyslawLukanowski** [comment]
Numer przesyłki zwracamy w polu `packages.waybill` w odpowiedzi [GET /shipment-management/shipments/{shipmentId}](https://developer.allegro.pl/documentation/#operation/getShipmentDetails).
