### ISSUE TITLE
POMOC

### ISSUE THREAD

**Issue by kornel-97** [allegro/allegro-api#7789]
MAM PROBLEM Z PRZEJŚCIEM PIERWSZEJ STRONY Z ALLEGRO PODANEJ PRZEZ FAKTUROWNIA.PL
WSZYSTKO WYPEŁNIŁAM POPRAWNIE ALE NIC SIĘ NIE DZIEJE KIEDY PRZYCISCKAM ,, ZAREJESTRUJ SIĘ,,

**Comment by PrzemyslawLukanowski** [comment]
Otrzymaliśmy już podobne zgłoszenie przez formularz kontaktowy. Spróbuj zmienić nazwę aplikacji, ponieważ ta podana przez Ciebie istnieje już w naszej bazie. Dodatkowo, upewnij się, że masz włączone dwustopniowe logowanie na koncie.

**Comment by kornel-97** [comment]
Dziś rozmawiałam z allegro i Pan powiedział , ze wysłał skrin ekranu w moim imieniu. nie wiem co dalej robić

**Comment by PrzemyslawLukanowski** [comment]
Z tego co widzę, to udało się zarejestrować aplikację, zatem nie ma potrzeby rejestracji kolejnej. Rozumiem, że nie jesteś developerem, który tworzy aplikację, tylko do tej strony zostałaś odesłana w ramach instrukcji od programu Fakturowania. W takiej sytuacji, sugeruję już kontakt ze wsparciem tego oprogramowania, który powinien pokierować, co dalej musisz zrobić aby zacząć korzystać z ich programu. My takiej wiedzy nie posiadamy, ponieważ nie jesteśmy autorami tego oprogramowania, a na forum świadczymy wsparcie dla developerów, którzy tworzą aplikacje.

**Comment by kornel-97** [comment]
Fakturownia każe kontaktować się z Allegro a Allegro z Wami :( i co teraz ?

**Comment by PrzemyslawLukanowski** [comment]
Aplikację udało się zarejestrować, posiada ona ID b6619ce3ef4b42c09c861192a5f8da72, nie za bardzo wiem, w czym dalej możemy pomóc. Posiadając to ID, możesz je wykorzystać przy tworzeniu nowej aplikacji, ale jak rozumiem, nie tworzysz tej aplikacji, tylko zarejestrowałaś ją na potrzeby połączenia z programem Fakturownia. Co do zasady, aplikacja (w tym przypadku Fakturownia) nie powinna zmuszać użytkownika do rejestrowania nowej aplikacji (czyli kroku, który wykonalaś na stronie developer.allegro.pl, ponieważ jest to strona przeznaczona dla developerów). Jeśli Fakturownia uważa, że istnieje jakiś problem techniczny po naszej stronie, poprosimy o kontakt z ich strony na tym forum lub przez formularz kontaktowy.

**Comment by kornel-97** [comment]
Ok zapytam Fakturownię. A co to oznacza  że nie jestem developerem czy to chodzi o nieruchomości czy to że prowadzę działalność?

**Comment by PrzemyslawLukanowski** [comment]
W tym kontekście developer oznacza programistę :)
