### ISSUE TITLE
Popularność z ostatnich 30 dni

### ISSUE THREAD

**Issue by mkaluszka** [allegro/allegro-api#779]
Czy któraś z metod pozwala pobrać ilość sprzedana w obcej aukcji ale tylko w ciągu ostatnich 30 dni? Bo mam wrażenie że obecnie działające metody pozwalają na pobranie bidcount od początku. Być może metoda do listowania aukcji po filtrach tak zwraca ale szukam sposobu pobrania tej informacji dla konkretnego id oferty

**Comment by PawelTaberski** [comment]
Nie wiem czy dobrze rozumiem Twoje pytanie, ale jeśli chodzi Tobie o sprawdzenie popularności oferty to przy pomocy metody [GET na zasobie /offers/listing](https://developer.allegro.pl/documentation/#/offers-listing/getListing). Taką informacje otrzymasz w polu popularity. Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/news/2018-07-03-Listing_ofert/).

**Comment by mkaluszka** [comment]
Niestety ta metoda nie pozwala wyszukać oferty po konkretnym ID. A o to chodzi w tym pytaniu. Przekazanie ID aukcji do phrase nie zwraca 1 wyniku tak jak na stronie allegro, gdzie następuje przekierowanie do konkretnej aukcji

**Comment by PawelTaberski** [comment]
Możesz wyszukać daną ofertę na swoim koncie po frazie. Obecnie zasób nie pozwala na wyszukanie konkretnego numeru oferty. Aby pobrać konkretną ofertę możesz skorzystać z metody GET na zasobie /sale/offers/{offerId}, ale tam znajdziesz tylko informacje o aktualnie dostępnym stocku. W celu sprawdzenia sprzedaży musiałbyś skorzystać z zasobów do obsługi zamówień o których pisaliśmy w [tym poradniku](https://developer.allegro.pl/orders/) i zbierać dane w odniesieniu do ilości sprzedanych przedmiotów w danej ofercie. Na chwilę obecną nie ma zasobu w REST API, który zwróciłby Tobie sprawdzić ilość sprzedanych ofert przez 30 dni.

**Comment by mkaluszka** [comment]
Co oznacza, że zamiast pobrać 1 ofertę na żądanie będę musiał listować wszystkie oferty wybranych użytkowników wg kategorii i przeszukiwać zwrócone wyniki wg mojego zapotrzebowania. Czyli najpierw Wy musicie mi wydać zdecydowanie więcej danych niż potrzebuje, a potem dodatkowo ja muszę je przetworzyć nadmiarowo, aby je ograniczyć do oczekiwanych wyników. Co za 2-stronna optymalizacja ...

**Comment by PawelTaberski** [comment]
Rozumiem zgłosiłem Twój pomysł jako sugestię do odpowiedniego zespołu, jeśli wdrożymy takie rozwiązanie poinformujemy o tym. W takim wypadku jak to opisałeś rzeczywiście przyspieszyłoby ten proces.
