### ISSUE TITLE
Feedback odnośnie katalogowania produktów

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#7791]
Generalnie katalogowanie jako zamysł jest ok, problem w tym, że wiele produktów w katalogu ma niepoprawne parametry, zdjęcia poglądowe z logiem/watermarkiem danego sprzedawcy, opis specyficzny dla danego sprzedawcy i tak naprawdę to jeden wielki syf. Chociażby na zdjęciach możemy znaleźć rzeczy takie jak: nazwy użytkowników allegro, zdjęcia kartonu, zdjęcia monet itp. które w teorii są wbrew regulaminowi allegro i mam wrażenie, że nikt tak naprawdę nie kontroluje tego co tam się dzieje. Tak samo kategoria, czy producent mogą odbiegać od rzeczywistości.

Gdy większość danych się nie zgadza lub nie jest kompletnych w 90% przypadków chociażby w motoryzacji chyba lepiej po prostu zrobić własny produkt w katalogu od podstaw... Tak samo mamy zduplikowane produkty, więc jak mamy zaproponować zmianę, skąd będzie wiadomo który jest tym najbardziej kompletnym i wiarygodnym?

**Comment by AureliuszBrussy** [comment]
Dziękuję za Twój feedback. Wciąż pracujemy na polepszaniem naszego Katalogu Produktów, usuwaniem duplikatów, nasycaniem go parametrami, czy usuwaniem wadliwie utworzonych produktów. Zdajemy sobie sprawę z problemów, które mogą wystąpić i staramy się polepszać doświadczenie sprzedającego czy integratora przy interakcji z naszym katalogiem produktów.

**Comment by bugproof** [comment]
Mam teraz taki problem, np reflektor samochodowy po EAN 5903107027343 prawidłowo strona zabudowy powinna być lewa 
jednak ktoś zrobił produkt w katalogu i zaznaczył że to jest komplet lewa+prawa

I teraz co z takim problemem zrobić? Mogę zgłosić błąd ale co z istniejącymi ofertami które już są wystawione jako komplet/lewa+prawa?

Czy można po prostu zrobić własny produkt w katalogu z tym samym EAN tylko ze stroną lewa?

Też tytuł katalogu jest mylący bo wyświetla "komplet"

![image](https://github.com/allegro/allegro-api/assets/3116731/e1771f5c-d04e-4300-abb1-2c8037e5c601)

Jeśli taka zmiana nie przejdzie to jakie jest rozwiązanie tego problemu? Jest możliwość dodania produktu do katalogu z EAN który już istnieje w allegro?

**Comment by PrzemyslawLukanowski** [comment]
Widzę, że produkt został już odpowiednio poprawiony w naszym katalogu, parametr zawiera prawidłową wartość.

> co wtedy stanie się z istniejącymi ofertami które już są wystawione jako komplet/lewa+prawa?

Zmiana w ofercie nastąpi dopiero po aktualizacji danych w ofercie. W przypadku API wystarczy, że wykonasz jakąkolwiek zmianę za pomocą [PATCH /sale/product-offers/{offerID}](https://developer.allegro.pl/documentation#operation/editProductOffers).

> Czy można po prostu zrobić własny produkt w katalogu z tym samym EAN tylko ze stroną lewa?

Aktualnie nie ma takiej potrzeby, ponieważ - jak wyżej - wartość została już zmieniona w produkcie. Ale tak, EAN nie jest parametrem identyfikującym w danej kategorii, zatem taka operacja byłaby możliwa.

> Też tytuł katalogu jest mylący bo wyświetla "komplet"

Do tej kwestii trudno mi się odnieść, ponieważ nazwa produktu w naszym katalogu to "Depo 9533095E lampa przednia L" i widzę, że to ona aktualnie widnieje [we wszystkich ofertach połączonych z tym produktem](https://allegro.pl/produkt/depo-9533095e-lampa-przednia-l-56bff814-cfa6-40b6-921b-987c797a2b72).

**Comment by bugproof** [comment]
Tylko problem w tym, że takich błędów programowalnie znalazłem ponad 100. Czy w takim wypadku lepiej zgłosić błąd dla każdego z tych produktów w katalogu z założeniem, że zmiana przejdzie? Czy ktoś weryfikuje wiarygodność danych z katalogu?

**Comment by PrzemyslawLukanowski** [comment]
Tak, możesz zgłosić błędy w produktach w takim przypadku. Każdy przypadek jest weryfikowany pod względem wiarygodności, zatem jeśli Twoje sugestie są prawidłowe, to możesz założyć, że zmiana przejdzie.

**Comment by bugproof** [comment]
Super. A czy zanim zmiana przejdzie da się ustawić własny parametr produktu z katalogu za pomocą PATCH? W interfejsie allegro 
 nie można np. zmienić sobie strony zabudowy ale może przez API się da?

**Comment by PrzemyslawLukanowski** [comment]
Danych w produkcie nie możesz zmienić samodzielnie, ale możesz zmienić parametry produktu w Twojej ofercie. Warunkiem jest to, aby dany parametr nie identyfikował produktu - czyli w GET /sale/products/{id} w polu `options.identifiesProduct ` widnieje `false`. W takim przypadku możesz zmienić wartość tego parametru za pomocą metody PATCH.
