### ISSUE TITLE
Tworzenie paczek przez API

### ISSUE THREAD

**Issue by antoniSea** [allegro/allegro-api#7792]
Hej, chciałbym przypiąć paczkę w systemie przez API. Mógłbym prosić o link do części dokumentacji odnośnie zarządzania paczkami?

**Comment by MaciejFrackowiak** [comment]
Poradnik dot. zarządzania przesyłkami poprzez Wysyłam z Allegro znajdziesz [tu](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY).
