### ISSUE TITLE
COMMAND_EXISTS Przy zamawianiu paczki 

### ISSUE THREAD

**Issue by thefreeon** [allegro/allegro-api#7793]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Od rana otrzymuję błąd przy tworzeniu paczek
parcel-management/parcel-create-commands/

"errors": [
            {
                "code": "COMMAND_EXISTS",
                "message": "An order with the submitted ID already exists in the system",
                "details": null,
                "path": "aaaac9ea-e760-3e0f-412e-acb1d276f140",
                "userMessage": "Zlecenie o podanym ID ju\u017c istnieje w systemie"
            }
Paczki w systemie się tworzą

**Comment by MaciejFrackowiak** [comment]
Wysłałeś dwa requesty o tym samym commandId=aaaac9ea-e760-3e0f-412e-acb1d276f140:
1) 2023-10-17 19:59:20 i tu dostałeś odpowiedź z kodem 201;
2) 2023-10-17 19:59:24 i tu odpowiedzieliśmy 400 z uwagi na użycie tego samego commandId co w punkcie 1.

Wygląda to tak jakby aplikacja wysyłała nadmiarowy request po wysłaniu pierwotnego.

**Comment by thefreeon** [comment]
> Wysłałeś dwa requesty o tym samym commandId=aaaac9ea-e760-3e0f-412e-acb1d276f140:
> 
> 1. 2023-10-17 19:59:20 i tu dostałeś odpowiedź z kodem 201;
> 2. 2023-10-17 19:59:24 i tu odpowiedzieliśmy 400 z uwagi na użycie tego samego commandId co w punkcie 1.
> 
> Wygląda to tak jakby aplikacja wysyłała nadmiarowy request po wysłaniu pierwotnego.

Tak wysyłam, jeden to jest PUT drugi to GET ten sam URL
Ten kod działał   od roku a dzisiaj przestał

**Comment by MaciejFrackowiak** [comment]
W obu przypadkach wysłałeś request z PUT.
