### ISSUE TITLE
Odblokowanie sprzedaży - sandbox

### ISSUE THREAD

**Issue by adamb-meritus** [allegro/allegro-api#7794]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dzień dobry,
Proszę o odblokowanie sprzedaży na koncie MeritusTest.

**Comment by MaciejFrackowiak** [comment]
Sprzedaż już odblokowana.
