### ISSUE TITLE
Pytanie o testy automatyczne dla shipment management - sandbox

### ISSUE THREAD

**Issue by adamb-meritus** [allegro/allegro-api#7796]
Dzień dobry, 
chcę napisać automatyczne testy sprawdzające integrację z systemem allegro shipment management do tworzenia i zarządzania przesyłką. Testy uruchamiane byłyby na środowisku testowym sandbox. Do stworzenia przesyłki wymagana jest emai z numerem transakcji. Chciałbym się dowiedzieć czy jest jakaś możliwość automatycznego uzyskania tego numeru transakcji, czy jedyną opcją uzyskania tego numeru to ręczne przeklikanie opcji zakupu z drugiego konta.

**Comment by MaciejFrackowiak** [comment]
Konieczne jest ręczne wyklikanie testowych transakcji.

**Comment by adamb-meritus** [comment]
Dziękuję za odpowiedz, mam jeszcze takie pytanie, jaka jest polityka allegro dotycząca botów, czy mogę np napisać bota przy użyciu selenium, który dokonywał by tych transakcji?

**Comment by MaciejFrackowiak** [comment]
Wszelkie mechanizmy imitujące działanie użytkownika mogą doprowadzić do zablokowania dostępu do Sandbox.
