### ISSUE TITLE
Allegro Kurier DPD Czechy Pobranie

### ISSUE THREAD

**Issue by ZAK2828** [allegro/allegro-api#7797]
Dzień dobry,
Przy próbie wygenerowania biletu z programu ProstaPaczka otrzymałem błąd:
Serwer przewoźnika odrzucił utworzenie listu przewozowego z powodu błędów:
VALIDATION_ERROR - additionalServices.cashOnDelivery.name: Podana wartość jest za krótka 
Gdy ponowiłem próbę wygenerowania biletu to otrzymałem inny błąd:
Serwer przewoźnika odrzucił utworzenie listu przewozowego z powodu błędów:
COMMAND_EXISTS - 7fcc21a4-5e3b-43ed-8a6e-771cfe1d6b46: Zlecenie o podanym ID już istnieje w systemie 
Co może być przyczyną?
Mam log tego błędu z programu, ale nie wiem czy dane które tam są zawierają dane, które nie powinny być publiczne, więc proszę ewentualnie o jakiś mail, albo w formie ticketu, żebym mógł dosłać.

**Comment by Lukasz-Zurek** [comment]
W tym przypadku chyba najlepiej będzie jak wyjaśnisz ten problem bezpośrednio z supportem programu ProstaPaczka. 

Dla nas wspomniany błąd oznacza, że to próba nadania przesyłki, jednak użyty został ten sam identyfikator commandID, a dla każdej tego typu próby - powinien być unikalny. Czyli należy tutaj pamiętać o tym, aby dla każdej nowej przesyłki, którą tworzysz, użyć nowego identyfikatora. Wszystko wskazuje na to, że program, z którego korzysta - ma błąd po swojej stronie.
