### ISSUE TITLE
WzA Allegro One Kurier Dostawa Jutro - Receiver post code not support next day

### ISSUE THREAD

**Issue by righttway** [allegro/allegro-api#7799]
Występuje problem:

 z zasobem REST API / with a REST API resource
 ze środowiskiem produkcyjnym / with the production environment

Dzień dobry,

Nie mogę utworzyć przesyłki przez API z powodu tego że w zamówieniu jest wybrana metoda dostawy Allegro One Kurier Dostawa Jutro a kod pocztowy odbiorcy jest poza strefą dostawy na jutro.

Pytanie - czy jest możliwe zablokowanie takiej opcji podczas składania zamówienia lub zmiany metody dostawy podczas tworzenia wysyłki.

{"id":"51071609-10cc-4bcb-84b1-fb98f5c6d0c1","parcelId":null,"status":"ERROR","errors":[{"code":"BAD_REQUEST","message":"Receiver post code not support next day","details":null,"path":"/parcel-management/parcel-create-commands/51071609-10cc-4bcb-84b1-fb98f5c6d0c1","userMessage":"Kod pocztowy odbiorcy znajduje się poza obszarem One Kuriera"}]}

Pozdrawiam,
Paweł

**Comment by Lukasz-Zurek** [comment]
Dostępność Allegro One Kuriera możesz sprawdzić [tutaj](https://allegro.pl/kampania/one/kurier). Natomiast kod pocztowy przekazujesz w błędnym formacie: 43600, a powinieneś tę wartość przekazać jako "43-600". Spróbuj i daj proszę znać.

**Comment by righttway** [comment]
Dzień dobry,

Dziękuję za pomoc :) Pomogło dodanie myślnika do kodu pocztowego.
