### ISSUE TITLE
Metoda REST change-price-commands

### ISSUE THREAD

**Issue by dfranczuk** [allegro/allegro-api#78]
Dzień dobry,

Próbuję wykonać metodę change-price-commands. Jednak cena nadal pozostaje niezmieniona. Jak długo należy czekać na efekt?

REQEST:

`PUT /offers/6867380795/change-price-commands/0923B8F9-0586-22FE-6330-928255529                                                                                                                                                             9CC HTTP/1.1
Host: api.allegro.pl
Accept: application/vnd.allegro.public.v1+json;charset=UTF-8
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer *****
Accept-Language: PL
Content-Length: 58

* upload completely sent off: 58 out of 58 bytes
< HTTP/1.1 200 OK
< Expires: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< X-Frame-Options: DENY
< Trace-Id: 5e3bb267ab9a707b
< Date: Mon, 19 Mar 2018 11:56:06 GMT
< X-RateLimit-Remaining: 9000
< X-Content-Type-Options: nosniff
< Content-Length: 160
< Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
< X-RateLimit-Limit: 9000
<`

RESPONSE:
`{"id":"0923b8f9-0586-22fe-6330-9282555299cc","input":{"buyNowPrice":{"amount":"23.9","currency":"PLN"}},"output":{"status":"VALIDATED_AND_RUNNING","errors":[]}}`

**Comment by rtnet-pl** [comment]
Zwykle zmiany są widoczne prawie od razu na stronie itemu, z nieco większym opóźnieniem są widoczne w API (kilka minut) a najdłużej zmieniają się na listingach (kilkanaście/kilkadziesiąt minut).
Wczoraj i dzisiaj zauważyłem że są jakieś opóźnienia, ale nie jakieś drastyczne (kilka minut).

**Comment by dfranczuk** [comment]
W moim przypadku zmiana ceny na portalu trwała około godzinę

**Comment by AniaMalinowska** [comment]
Zmiany w ofercie mogą się pojawić w serwisie nawet do 60 minut.

**Comment by rtnet-pl** [comment]
Issue został zamknięty, ale chciałbym zgłosić problem - duże opóźnienie nadal występuje. Do tej pory zmiany widoczne były dużo szybciej (tak jak napisałem wcześniej). Czy mogę prosić o usunięcie opóźnienia?

**Comment by MarcinLuczak** [comment]
@rtnet-pl jak duże są te opóźnienia? Jeśli mniejsze niż 60 minut, to nie jest to błąd.

**Comment by rtnet-pl** [comment]
@MarcinLuczak Mieszczą się w tym limicie. Po prostu "od zawsze" zmiana następowała dużo szybciej. Od weekendu działa to wolniej. Użytkownicy aplikacji zauważyli tą zmianę i kierują do nas prośby o fix :)

**Comment by rtnet-pl** [comment]
@MarcinLuczak Sytuacja wróciła do normy. Czasy są takie jak podawałem na początku. Dziękuję.

**Comment by MarcinLuczak** [comment]
@rtnet-pl dziękuję za informację.
