### ISSUE TITLE
Tokeny - krótki czas expiry_in

### ISSUE THREAD

**Issue by adampajak** [allegro/allegro-api#780]
Od godziny 18tej, refresh tokena zwraca nowy ale z czasem ważności tylko godzinę do przodu. Na produkcji.

**Comment by unkn0wn0** [comment]
Tokeny nie trzymają godzinę a 1 minutę i tak jest praktycznie od rana, a nie 18tej.

**Comment by dlis2010** [comment]
@unkn0wn0  trzymają godzinę, bez jednej sekundy
`[expires_in] => 3599 

@PawelTaberski problem trwa już cały dzień, jakieś informacje?

**Comment by PawelTaberski** [comment]
Prosiłbym o podesłanie przez [formularz kontaktowy ](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) user id sprawdzimy w czym jest problem.

**Comment by kormichu** [comment]
Gorzej, że przez skrócony czas odświeżania tokenów wpadliśmy w limity:

`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/captcha","userMessage":null}]}`

**Comment by PawelTaberski** [comment]
Już powinno być wszystko w porządku kolejne tokeny powinny być już na 12 godzin.

**Comment by mjag8** [comment]
Potwierdzam, świeży token na 12 h:
`[expires_in] => '43199'`

**Comment by solokazama** [comment]
u nas tak samo
po zrobieniu refresha toekn dziala 1 godzine i traci waznosc (i kazda operacja dostaje "invalid token: access toekn expired"

**Comment by adampajak** [comment]
Na sandboxie problem nadal występuje.

**Comment by PawelTaberski** [comment]
Zgłosiłem sprawę do odpowiedniego zespołu, proszę o cierpliwość.

**Comment by PawelTaberski** [comment]
Tak, wiemy sprawę przekazałem do odpowiedniego zespołu. Sprawa powinna być rozwiązana w przyszłym tygodniu.

**Comment by xemix** [comment]
Problem na sandboxie nadal występuje...

**Comment by PawelTaberski** [comment]
Na sandboxie planujemy zostawić taki czas ważności tokenów, czy będzie to dla Ciebie duży problem? Pamiętaj, że zawsze wraz z tokenem przesyłamy w polu expires_in czas jego ważności.

**Comment by xemix** [comment]
Miło by jednak było, gdyby środowisko sandboxa było zgodne 1:1 z produkcją.

**Comment by PawelTaberski** [comment]
Rozumiem przekazałem Twoją uwagę do odpowiedniego zespołu zobaczę co da się zrobić.

**Comment by adampajak** [comment]
Czy informacja została przekazana do zespołu? Kiedy możemy spodziewać się sandboxa 1:1 z produkcją?

**Comment by PawelTaberski** [comment]
Przekazałem Twoją sugestię, jednakże nie będziemy zmieniali czasów ważności tokenów na sandboxie.
