### ISSUE TITLE
ShipmentManagement

### ISSUE THREAD

**Issue by MarcinEtna** [allegro/allegro-api#7800]
Witam mam problem z odpowiedzią metod ShipmentManagement. Mianowicie wysyłając zapytanie do /shipment-management/delivery-services otrzymuję odpowiedź 403 z zawartością:

array:1 [▼
  "errors" => array:1 [▼
    0 => array:5 [▼
      "code" => "AccessDenied"
      "message" => "Access is denied"
      "details" => null
      "path" => null
      "userMessage" => "No access to the specified resource."
    ]
  ]
]
Zapytanie na Pacel odpowiada prawidłowo np /parcel-management/delivery-services zwraca mi 200 z poprawną odpowiedzią.
Czy muszę coś właczyć na moim koncie testowym w sandbox żeby mieć dostęp do tych zasobów? 
Moje konto to: EtnaTest

**Comment by jezewskiBNetrox** [comment]
@MarcinEtna Upewnij się, że token posiada uprawnienia:
**allegro:api:shipments:write | allegro:api:shipments:read**

**Comment by MarcinEtna** [comment]
Tak to było to dzięki

**Comment by MaciejFrackowiak** [comment]
Dokładnie jak wspomniał @jezewskiBNetrox - zasoby [Shipment management](https://developer.allegro.pl/documentation/#tag/Shipment-management) mają osobne scope'y - "allegro:api:shipments:write" oraz "allegro:api:shipments:read".
