### ISSUE TITLE
x-frame api - allegro: domowy_market

### ISSUE THREAD

**Issue by sebax3x** [allegro/allegro-api#7801]
Witam serdecznie,

Czy istnieje możliwość, żebyśmy, korzystając z API, mogli zaimplementować aplikację internetową do obsługi Państwa serwisu na adresie wskazanym w panelu Allegro? Chcielibyśmy wykorzystać klucz API oraz secret key, a także logowanie poprzez oauth.
Czy jest możliwość otwierania podstron związanych z edycją aukcji oraz formularzy wewnątrz okienka iframe? Obecnie, przy próbie wyświetlenia przykładowego linku w iframe, takiego jak https://allegro.pl/offer/14432268286, otrzymujemy komunikat "Refused to display 'https://allegro.pl/' in a frame because it set 'X-Frame-Options' to 'sameorigin".
Naszym celem jest umożliwienie pracownikom naszej firmy otwierania jednocześnie ponad 100 zakładek do edycji. W związku z tym, pracujemy nad aplikacją z zakładkami, która ma to usprawnić. Czy istnieje możliwość umieszczenia naszego serwera na Państwa whiteliście stron, które są wyłączone z ograniczeń X-Frame Options?

**Comment by AureliuszBrussy** [comment]
Nie zmienimy ograniczeń X-Frame-Options. W jakim celu aplikacja działająca w ramach API miałaby wyświetlać podgląd oferty pobrane poza API? Pobieraj dane ofert sprzedającego korzystając z zasobów API (np. [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/getProductOffer)) i w ten sposób możesz prezentować użytkownikom swojej aplikacji dane wielu ofert jednocześnie.
