### ISSUE TITLE
Error while creating shipment

### ISSUE THREAD

**Issue by TomasReznicek** [allegro/allegro-api#7802]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Hello,
I am unable to create shipment via api shipment-management/shipments/create-commands. The POST part of creation works, but when I check the creation status using GET https://api.allegro.pl/shipment-management/shipments/create-commands/ddf296ae-2dae-4601-9878-ea825e8cd254 I receive error:

`{"commandId":"ddf296ae-2dae-4601-9878-ea825e8cd254","status":"ERROR","errors":[{"code":"BAD_REQUEST","message":"Opennet API cannot process request","details":"Opennet API cannot process request","path":null,"userMessage":"Przewoźnik odpowiedział nieznanym błędem [1059]"}],"shipmentId":null}`

**Comment by Lukasz-Zurek** [comment]
As I have checked it closely - there is no possibility to send a package from CZ for this delivery method: 0b9bed2c-0bc1-4e1f-9694-29bb39ebb483 (Allegro One Box, One Kurier). It is dedicated for "allegro-pl" marketplace.

We have marked all of the delivery methods dedicated for CZ:

            "marketplaces": [
                "allegro-cz"
            ],

You can check them by using [GET /shipment-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getDeliveryServices).

If you want to send a package from CZ to PL, you will have to use one of these delivery methods, which we have described [here](https://allegro.pl/pomoc/dla-sprzedajacych/informacje-dla-sprzedajacych/wysylam-do-polski-z-zagranicy-co-zrobic-zeby-moje-oferty-byly-oznaczone-ikona-allegro-smart-zlbn23wwGfl). So it's gonna be UPS or DHL Courier - delivery from Czechia.

**Comment by TomasReznicek** [comment]
Hello,

I've changed the sender address to PL one, but now I have different error:
commandId: 5387b3b1-9c12-44c2-8d8e-14b622b86d29
`{"errors":[{"code":"ServiceTimeoutException","message":"An error occurred","details":null,"path":null,"userMessage":"Query response time exceeded. Try again."}]}` 
Can you please explain me this error?

**Comment by Lukasz-Zurek** [comment]
@TomasReznicek The buyer has selected the pickup point, but you did not provide it in the request, in the **receiver.point** field. There is no possibility to ship this package door to door in this situation.

**Comment by TomasReznicek** [comment]
@Lukasz-Zurek same error with point defined. commandId eeb57498-64f6-4e2c-98af-c485f6cd9d99

**Comment by Lukasz-Zurek** [comment]
@TomasReznicek I don't see any error with commandID: eeb57498-64f6-4e2c-98af-c485f6cd9d99. Are you sure about that commandId?

**Comment by Lukasz-Zurek** [comment]
@TomasReznicek Ok, thank you. I have reported this to another department.

**Comment by Lukasz-Zurek** [comment]
@TomasReznicek This was an error on our side. We have already fixed it.

We are sorry for the inconvenience.
