### ISSUE TITLE
Etykieta DHL + potwierdzenie nadania

### ISSUE THREAD

**Issue by pawelkucharskiyosi** [allegro/allegro-api#7803]
Dzień dobry,

 czy istnieje opcja by API zwracało tylko etykietę DHL bez potwierdzenia nadania?
Czy jest do tego odpowiednia metoda?

Obecnie podczas nadawania przesyłki przez API zwracana jest etykieta i potwierdzenie nadania.
co widać na załączniku.

![etykietyDHL](https://github.com/allegro/allegro-api/assets/147634160/db3ca3a2-d60c-4f34-8750-0c797056d2aa)

**Comment by AureliuszBrussy** [comment]
Nie udostępniamy możliwości takiego wyboru generowanej etykiety.

**Comment by pawelkucharskiyosi** [comment]
dziękuję za odpowiedź
miłego dnia :)
