### ISSUE TITLE
Zmiana id parametrów dla kategorii?

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#7804]
Witam, mam pytanie czy jest gdzieś informacja kiedy allegro postanawia zmienić id parametrów, jak np. ostatnio id parametry strona zabudowy w zestawach tarcz i klocków, klockach i tarczach?

Nie ukrywam, ze takie zmiany powodują tylko zakańczanie aukcji :/

**Comment by AureliuszBrussy** [comment]
W publicznym API nie zwracamy takich informacji. Można jedynie podejrzeć dzięki [GET /sale/category-parameters-scheduled-changes](https://developer.allegro.pl/documentation#operation/getCategoryParametersScheduledChangesUsingGET_1), jakie parametry wkrótce zostaną uobowiązkowione.
