### ISSUE TITLE
Różnice w cenie oferty pobranej przez sale/product-offers oraz sale/offers?offer.id

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#7805]
Wykonując GET /sale/product-offers/... dostaję prawidłową cenę w ofercie 11.95 zł. Taka sama jest na stronie widoczna dla kupującego i takiej się spodziewałem.
trace-id: 1699d91a562c4def 

Ale wykonując GET sale/offers?offer.id=... dostaję cenę 11.73 zł.
trace-id: ceed3e3d06a8ce44

Z czego wynika 11.73 zł w sale/offers/?

**Comment by AureliuszBrussy** [comment]
@tomylee0 potwierdzam ten błąd. Poprawiliśmy to.

**Comment by tomylee0** [comment]
Podobne różnice znalazłem przed chwilą jeszcze w tych ofertach. Poniżej trace-id z GET /sale/product-offers

7a7ae2f7cd3a7aca
be1ef54c0260c8d2
fdd204ee1cc9f536
45fa3faeae41a357
5a0e1e71258d220b
8eba83b32dff360d
545a9bd310315fe4
cb6f609f982591c8
9a37ecb54eb7ab34
ef848f1bcc4ce545
e036b7d1ad016286
91808755b279c1d4
7504482eac326a15
92a3d22f4208b0e
fde0d04641f284f5
6d8a4336043cb538
c56607cb95497810

**Comment by AureliuszBrussy** [comment]
Aktualnie nie powinny już występować żadne niespójności - poprawiliśmy to globalnie.
