### ISSUE TITLE
Is it normal for the billing API to return a negative value

### ISSUE THREAD

**Issue by VEVOR** [allegro/allegro-api#7806]
GET /billing/billing-entries
response: {
    "billingEntries": [
        {
            "id": "c2228aa1-f60d-4bf1-9f18-d23a80193676",
            "occurredAt": "2023-09-21T19:56:02.071Z",
            "type": {
                "id": "FSF",
                "name": "Prowizja od sprzedaży oferty wyróżnionej"
            },
            "offer": {
                "id": "12938597278",
                "name": "VEVOR System Przywoławczy Retekess 16 Pager Czarny"
            },
            "value": {
                "amount": "-110.88",
                "currency": "PLN"
            },
            "tax": {
                "percentage": "23.00"
            },
            "balance": {
                "amount": "-626.82",
                "currency": "PLN"
            },
            "order": {
                "id": "ab723740-58b8-11ee-abd9-efd1bb21bbf1"
            }
        },
        {
            "id": "a34f42ed-cb98-4df7-a017-3389167ef2cb",
            "occurredAt": "2023-09-21T19:56:01.963Z",

**Comment by AureliuszBrussy** [comment]
Yes, this is normal, recognitions have a positive value and charges have a negative value.
