### ISSUE TITLE
parcel-create-commands Internal server 

### ISSUE THREAD

**Issue by larysoftware** [allegro/allegro-api#7807]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Witam podczas wykonywania requestu 

PUT https://api.allegro.pl/parcel-management/parcel-create-commands/0e3b062c-2cd5-4751-814c-423ac8566662

trace id 0e3b062c-2cd5-4751-814c-423ac8566662

dostaję 

{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."}]}

**Comment by AureliuszBrussy** [comment]
W Twoim requeście brakuje wymiarów przesyłki. Postaramy się tutaj poprawić zwrócony komunikat błędu.

**Comment by larysoftware** [comment]
Dziękuję za informację liczymy na poprawkę komunikatu.
