### ISSUE TITLE
Sandbox problem Wystaw pierwszą ofertę

### ISSUE THREAD

**Issue by zakjar** [allegro/allegro-api#7808]
My account in sandbox is "rejzr" login jaroslav.zak@seznam.cz

I have 75% in registration process. And I try "Wystaw pierwszą ofertę" via button "WYSTAW PRZEZ FORMULARZ"

After click a get blank page with text "Twoim domyślnym serwisem jest allegro.cz" and button that redirect me out of sandbox server

I can't use this function on sandbox ?

**Comment by AureliuszBrussy** [comment]
Try to use allegro.cz Sandbox: https://allegro.cz.allegrosandbox.pl/.

**Comment by zakjar** [comment]
Thank you it works
