### ISSUE TITLE
Sklep jest zamknięty, a w backendu pojawi się ten tekst. Czy interfejs API może odczytać ten monit?

### ISSUE THREAD

**Issue by qq16632785** [allegro/allegro-api#7809]
Sklep jest zamknięty, a w backendu pojawi się ten tekst. Czy interfejs API może odczytać ten monit?

Sales suspension
The ability to sell from your account is currently suspended. This may be due to unpaid bills or other violations of the Terms & Conditions. To lift the sales suspension, pay any outstanding amounts or contact us.
[SEE YOUR CURRENT BALANCE](https://allegro.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro?sellerId=108321633)

**Comment by AureliuszBrussy** [comment]
Could you elaborate on your question/need? Unfortunately, I didn't understand your question fully.

**Comment by qq16632785** [comment]
Sklep został zamknięty i zostanie wyświetlony później. Czy API może odczytać tę czcionkę?

**Comment by AureliuszBrussy** [comment]
Nie zwracamy żadnego pola, które mówiłoby o tym, że konto jest zablokowane/odblokowane. Dowiesz się tego, gdy spróbujesz wykonać jakąś zablokowaną operację (np. spróbujesz wystawić ofertę) - wtedy zwrócimy odpowiedni komunikat o tym, że konto jest zablokowane.

**Comment by qq16632785** [comment]
Czy API może odczytać ilość produktów?

**Comment by Lukasz-Zurek** [comment]
@qq16632785 Doprecyzuj proszę Twoje pytanie - jaką ilość produktów masz na myśli?
