### ISSUE TITLE
Allegro sandbox - brak nowych zamówień na koncie sprzedażowym

### ISSUE THREAD

**Issue by KrystianBogiel** [allegro/allegro-api#7811]
- [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other
Występuje problem:
🪲 Opis / Description
Dzień dobry,
Na środowisku testowym gdzie prowadzona jest sprzedaż nie widzę nowych zamówień, są one jednak widoczne na koncie klienta z którego je kupuje. Przy zapytaniu GET o checkout-form również ich nie widać, ani przy liście wszystkich zamówień ani przy odpytywaniu o jedno konkretne zamówienie. Czy to problem z zablokowaniem sprzedaży na koncie? Konto którego dotyczy problem na środowisku Allegro Sandbox: edrabiny_pl.

**Comment by Lukasz-Zurek** [comment]
Z dostępnych mi danych wynika, że na wskazanym koncie nie ma już blokady sprzedaży. Powinieneś mieć dostęp do listy zamówień, pod warunkiem, że prawidłowo się autoryzowałeś jako Sprzedający.

Jeżeli nadal masz problem z brakiem zamówień - prześlij proszę trace-id.

**Comment by Lukasz-Zurek** [comment]
@KrystianBogiel Mogę jedynie potwierdzić, że Twoje konto jest w pełni aktywne. Gdybyś ponownie trafił na jakiekolwiek problemy z pobieraniem zamówień - prześlij proszę trace-id oraz wszelkie szczegóły (np. czas występowania utrudnień).
