### ISSUE TITLE
Punkty nadania dla Allegro Mini Przesyłka

### ISSUE THREAD

**Issue by matcapi** [allegro/allegro-api#7814]
Dzień dobry,

Podobnie jak w tym [wątku](https://github.com/allegro/allegro-api/issues/7745) chiałbym poprosić o przykładowy punkt nadania dla metody "Allegro Mini Przesyłka", który zadziała na środowisku sandbox.

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Proszę spróbować użyć tego punktu: 160322.

**Comment by matcapi** [comment]
Niestety dostaję błąd "Pickup point is incorrect".
commandId = 9e06c2f2-8fa1-4660-934d-ae94ee2dfda3
traceId = 7af425eb8ec33419

**Comment by Lukasz-Zurek** [comment]
Ok. Przepraszamy za te utrudnienia. Zgłosiłem ten problem do odpowiedniego zespołu.

**Comment by matcapi** [comment]
Chciałbym dowiedzieć się, kiedy przewidujecie wprowadzenie korekty do zaobserwowanego problemu. Czy moglibyście mnie poinformować? Czy problem występuje tylko na sandbox czy również na środowisku produkcyjnym?

**Comment by Lukasz-Zurek** [comment]
@matcapi Problem stanowił tutaj punkt, który w środowisku testowym naszego operatora - nie jest obsługiwany. Niestety taka jest specyfika Allegro Sandbox, w przypadku którego możemy mieć pewne niespójności w obsługiwanych punktach.

Podaję kilka punktów, które powinny funkcjonować prawidłowo:

3972853
160369
160370
3972856
160377

Nie jest to żaden globalny problem i sytuacja nie dotyczy produkcji.

**Comment by matcapi** [comment]
Niestety żaden z wymienionych punktów nie zadziałał prawidłowo.

pointId - commandId - traceId
3972853 - 89f64da1-b361-4757-8474-e2d07cad0c25 - d5c2c281e47da0fe
160369 - 11d2127a-262a-4f27-b5af-52c7b620a5b4 - cd4ca0c691c34a7a
160370 - 7d374530-4d7b-4792-9f4e-9d75d3ba5a8f - b26c2b62cf79dedc
3972856 - b36cd737-69d7-4ad2-8eef-6f5378957fcd - 531b691dc65b7856
160377 - 669c7c2e-1738-42a6-a416-96fef36a2a5a - 12a810c1068af2f0

Znalazłem działający pointId: 233052

Rozumiem, że endpoint [GET /order/carriers/ALLEGRO/points](https://developer.allegro.pl/documentation#operation/getAllegroPickupDropOffPointsGET) nie umożliwia pobrania pickup pointów dla poczty polskiej?

**Comment by Lukasz-Zurek** [comment]
Najważniejsze, że udało się Tobie znaleźć działający punkt. Najwyraźniej lista, którą posiadam - nie jest już aktualna, co też oznacza, że to dynamicznie się zmienia. Następnym razem przekażę temat do właściwego zespołu, w celu uzyskania aktualnych, działających punktów.

Co do Twojego pytania - wskazany endpoint niestety nie umożliwia pobrania punktów dla poczty polskiej.
