### ISSUE TITLE
Problem z połączeniem konta z Fakturownia

### ISSUE THREAD

**Issue by Zloma322** [allegro/allegro-api#7815]
Witam, mam problem z zarejestrowaniem zewnętrznej aplikacji do allegro (fakturownia).Wyskakuje błąd o treści (Nazwa aplikacji jest już wykorzystywana - podaj inną.) na liście zarejestrowanych aplikacji nie wyświetla się ona. Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Nazwa aplikacji musi być unikatowa na przestrzeni całego serwisu, więc nie możesz zarejestrować aplikacji o tej samej nazwie (używa ją inny użytkownik). Aplikacja w procesie OAuth nie powinna wymuszać na tobie zarejestrowania nowego identyfikatora aplikacji. Skontaktuj się z supportem Fakturowni aby to wyjaśnić.
