### ISSUE TITLE
nie wiem czemu moje konto sandbox nie jest aktywne, konto prod zwraca 403 mimo pełnej weryfikacji i 2fa

### ISSUE THREAD

**Issue by domainarchitecture** [allegro/allegro-api#7816]
przy klikaniu w linki z weryfikacją konta za pomocą przelewu 404 https://allegro.pl/CodeForm.php/Platnosci
jestem w stanie uzyskać jwt ale nie jestem w stanie użuć api 
jedno i drugie zwraca 403 prosze o kontakt

**Comment by AureliuszBrussy** [comment]
Czy możesz podać login swojego konta? Sprawdzę to.

**Comment by domainarchitecture** [comment]
c96014fb3cc04f42878d1f386f6dea07
to z sandboxa a tam problem z tym że nie moge tego aktywować ani aplikacją bo mowi że zły kod ani sms bo sms nie dochodzi
mam aktywowane na powiedzmy prod ale tam 403 też leci - nie to że bad request, jakieś entity złe czy coś ale taki po prostu 403 - przydałby się jakiś bardziej informacyjny wyjątek może - żeby wiedzieć czeko konkretnie brakuje w tych uprawnieniach moich

**Comment by domainarchitecture** [comment]
OK dzięki wielkie za pomoc! założyłem firmowe i czekam na aktywacje konta po Waszej stronie. tu rzeczywiście wygląda to inaczej

**Comment by AureliuszBrussy** [comment]
Jeżeli chodzi o kody sms - na Sandboxie nie wysyłamy sms, spróbuj sekwencję "123456".

**Comment by domainarchitecture** [comment]
ten link nie dziala
![image](https://github.com/allegro/allegro-api/assets/148473342/10058e41-fd55-4fc6-b485-0e3691c5761d)

**Comment by domainarchitecture** [comment]
no ale limit wysyłanych sms działa ;) nie mogę wypróbować tego sposobu - ale wrócę jak minie czas

**Comment by domainarchitecture** [comment]
możemy sprawdzić to konto? 96ae91d0d82241ab8089f6e46830f51d

**Comment by Lukasz-Zurek** [comment]
@domainarchitecture Aktywowałem Twoje konto firmowe na sandboxie - login: targiem_pl.

**Comment by domainarchitecture** [comment]
dziękuję ale to chyba nie ta bo tamsta miała inny typ konta, ten numer który ostatnio podawałem to inna
Aplikacja tpl
CLIENT ID 96ae91d0d82241ab8089f6e46830f51d

**Comment by Lukasz-Zurek** [comment]
@domainarchitecture Do wskazanej aplikacji na sandboxie przypisane jest powyższe konto o loginie: targiem_pl

Jeżeli chcesz, abym aktywował inne konto na sandboxie - podaj proszę login.

**Comment by domainarchitecture** [comment]
ach login... login się zgadza - miałem wcześniej aplikację z tą nazwą :) 
jednak nadal mam 403 - uprawnienia dla aplikacji wybrałem absolutnie wszystkie
pl.targiem.frontend.features.allegro.AllegroService - {"errors":[{"code":"AccessDeniedException","message":"Authorization error.","details":null,"path":null,"userMessage":"No access."}]}

**Comment by Lukasz-Zurek** [comment]
@domainarchitecture Z tego co widzę - nie przekazałeś nagłówków Accept i Content-type: **application/vnd.allegro.public.v1+json**.

**Comment by domainarchitecture** [comment]
kurcze nie wiem czemu bo w kodzie jest tak  
 
 Request request = new Request.Builder()
                .url(url)
                .post(body)
                .addHeader("Authorization", "Bearer " + accessToken)
                .addHeader("Accept", "application/vnd.allegro.public.v1+json")
                .addHeader("Content-Type", "application/vnd.allegro.public.v1+json")
                .build();

teraz dodałem log do headers i tu też niby jest - ciekawe

[main] INFO pl.targiem.frontend.features.allegro.AllegroService - sendProductOffer [https://api.allegro.pl.allegrosandbox.pl/sale/product-offers]
[main] INFO pl.targiem.frontend.features.allegro.AllegroService - sendProductOffer [Authorization: ██
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
]
[main] ERROR pl.targiem.frontend.features.allegro.AllegroService - {"errors":[{"code":"AccessDeniedException","message":"Authorization error.","details":null,"path":null,"userMessage":"No access."}]}

pl.targiem.exceptions.DomainException: Bąd odpowiedzi z Allegro: 403 kod: 403

**Comment by Lukasz-Zurek** [comment]
@domainarchitecture 

Ok, nagłówki są w porządku. Upewnij się, że nie korzystasz z autoryzacji typu[ client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow), która nie posiada kontekstu użytkownika. Z logów wynika, że Twój token nie posiada kontekstu użytkownika. W[ naszej dokumentacji](https://developer.allegro.pl/documentation/) znajdziesz odpowiednie oznaczenie, jaki typ autoryzacji wymagany jest dla danego zasobu:

- bearer-token-for-user ([code](https://developer.allegro.pl/auth/#app) lub[ device](https://developer.allegro.pl/auth/#DeviceFlow) flow),
- bearer-token-for-application ([client credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow)).

Dla wskazanego [zasobu](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) wymagany jest: bearer-token-for-user ([code](https://developer.allegro.pl/auth/#app) lub [device flow](https://developer.allegro.pl/auth/#DeviceFlow)).

**Comment by domainarchitecture** [comment]
Ok, jeszcze bardziej ciekawe... czyli do wystawienia muszę mieć sesję użytkownika? Nie szkodzi bo docelowo będzie raczej taki flow dokładnie żeby dać możliwość wystawiania produktów z mojej platformy na koncie użytkownika. Dzięki za wyjaśnienia. Spróbuję za jakiś czas.
