### ISSUE TITLE
Aktywacja konta firmowego

### ISSUE THREAD

**Issue by gbr161** [allegro/allegro-api#7817]
Witam
W jaki sposób aktywowac konto firmowe z możliwośćią wystawiania ofert na sandboxie?
Podałem wszystkie wymagane dane, jednak od kilku dni trwa weryfikacja.

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Podaj proszę login konta. Sprawdzę to.

**Comment by gbr161** [comment]
sb1allebot

**Comment by AureliuszBrussy** [comment]
@gbr161 aktywowałem Twoje konto.

**Comment by gbr161** [comment]
Dziękuje
