### ISSUE TITLE
Brak przewoźnika GLOBKURIER

### ISSUE THREAD

**Issue by karolwisniewski88** [allegro/allegro-api#7819]
Jak dodać przewoźnika GLOBKURIER przy tworzeniu przesyłki?

**Comment by AureliuszBrussy** [comment]
Wysyłam z Allegro nie obsługuje tego przewoźnika.

**Comment by karolwisniewski88** [comment]
Nie wiem czy na pewno dobrze się zrozumieliśmy, chodzi mi o listę przewoźników pobieranych za pomocą API  order/carriers.

**Comment by AureliuszBrussy** [comment]
Faktycznie, chodziło mi o inną funkcjonalność. Możesz korzystać z wartości OTHER i wprowadzić własną nazwę ([POST /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation#operation/createOrderShipmentsUsingPOST)).  Możesz zasugerować też wprowadzenie nowej wartości przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
