### ISSUE TITLE
Allegro sandbox - aktywacja/weryfikacjia konta testowe

### ISSUE THREAD

**Issue by appsandboxome** [allegro/allegro-api#7820]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Poproszę o weryfikację założonych kont testowych **   

Założono poniższe konta testowe. wykonano mokapową płatność, ale podczas wystawiania pierwszej oferty zwraca poniższy komunikat   

```
 Aby aktywować sprzedaż zweryfikuj konto.
```

Login:L2_ome_fdx_sand   
email:omecon.fdx.info.l2@omecon.com.pl    

Login:L3_ome_fdx_sand    
email:omecon.fdx.info.l3@omecon.com.pl    

Login:L6_ome_fdx_sand   
email:omecon.fdx.info.preprod@omecon.com.pl

**Comment by Lukasz-Zurek** [comment]
@appsandboxome Zweryfikowałem i aktywowałem wszystkie wskazane konta testowe.
