### ISSUE TITLE
Allegro One Box.

### ISSUE THREAD

**Issue by roberto102** [allegro/allegro-api#7821]
Dzień dobry. Próbuje ogarnąć metodę 
https://api.allegro.pl/shipment-management/shipments/create-commands
wystawianie przesyłek dla usługi Allegro One Box.
Niestety w odpowiedzi otrzymuję 
----------------------------------
{
	"errors": [
		{
			"code": "AccessDenied",
			"message": "Access is denied",
			"details": null,
			"path": null,
			"userMessage": "No access to the specified resource."
		}
	]
}
----------------------------------

Upewniłem się, że mamy w ustawieniach dotyczących włączenia API
uprawnienia niestety nadal nie potrafię sobie z tym poradzić.
(ręcznie przez stronę allegro.pl zadziałało )
Poniżej mój JSON
------------------------------------
{
   "commandId":"", 
   "input":{
      "deliveryMethodId":"0aafb43c-e66a-46ec-9cc4-29bb39ebb483", 
      "credentialsId":"", 
      "sender":{ 
         "name":"Einhell", 
         "company":"Einhell SP. Z O.O.", 
         "street":"Józefa Wymysłowskiego", 
         "streetNumber":"1", 
         "postalCode":"55-080", 
         "city":"Nowa Wieś Wrocławska", 
         "countryCode":"PL", 
         "email":"allegro@einhell.pl", 
         "phone":"+48 795 682 528", 
         "point":"" 
      },
      "receiver":{ 
         "name":"Dorian Turkiewicz",
         "company":"", 
         "street":"Krzycka", 
         "streetNumber":"67a", 
         "postalCode":"53-019", 
         "city":"Wrocław", 
         "countryCode":"PL", 
         "email":"kaov93bbpw+45dc54b47@allegromail.pl", 
         "phone":"+48 601 175 670",
         "point":"AL209DW1"
      },
      "pickup":{ 
         "name":"Dorian Turkiewicz", 
         "company":"", 
         "street":"Krzycka",
         "streetNumber":"67a", 
         "postalCode":"53-019", 
         "city":"Wrocław",
         "countryCode":"PL", 
         "email":"kaov93bbpw+45dc54b47@allegromail.pl", 
         "phone":"+48 601 175 670", 
         "point":"AL209DW1" 
      },
      "referenceNumber":"ZAMEINHELL",
      "description":"Elektronarzędzia", 
      "packages":[ 
         {
            "type":"OTHER", 
            "length":{ 
               "value":12,
               "unit":"CENTIMETER"
            },
            "width":{ 
               "value":12,
               "unit":"CENTIMETER"
            },
            "height":{ 
               "value":12,
               "unit":"CENTIMETER"
            },
            "weight":{ 
               "value":2,
               "unit":"KILOGRAMS"
            }
         }
      ],
      "insurance":{
         "amount":"11", 
         "currency":"PLN" 
      },
      
      "labelFormat":"PDF", 
      "additionalServices":[ 
         "ADDITIONAL_HANDLING"
      ],
"additionalProperties": {}
   }
}
----------------------------------------------

Proszę mi podpowiedzieć co robię źle.

Robert Orzeszek
nazwa klienta Einhell

Einhell Polska Sp. Z O.O.
508 369 270

**Comment by jezewskiBNetrox** [comment]
>Upewniłem się, że mamy w ustawieniach dotyczących włączenia API uprawnienia niestety nadal nie potrafię sobie z tym poradzić.

@roberto102 A wygenerowałeś nowy token? :)

Uprawnienia są również zawarte wewnątrz tokena. Po zmianie uprawnień musisz wygenerować nowy token.

**Comment by Lukasz-Zurek** [comment]
Dokładnie, tak jak wspomniał @jezewskiBNetrox - musisz ponownie przejść przez proces autoryzacji, by uwzględnić: allegro:api:shipments:read i allegro:api:shipments:write.
