### ISSUE TITLE
Issue with uploading product via API

### ISSUE THREAD

**Issue by barbasfilip** [allegro/allegro-api#7822]
Hello, we have an issue when we tried to add product via API into our Offer, but in one point we get an Error about "user does not have Returns Terms". We think we have all settings in account set correctly. Please let us know how to continue, or what problem this error refers to.

We are usiing this endpoint https://api.allegro.pl/sale/product-offers with this bodyData

``php
[
            'productSet' => [[
                "product" => [
                    "id" => "d004aafe-20fa-42a9-82f2-ceaa46e7fb2e",
                    "idType" => "GTIN"
                ]
            ]],
            "stock" => [
                "available" => 0,
                "unit" => "UNIT"
            ],
            "sellingMode" => [
                "price" => [
                    "amount" => "148.50",
                    "currency" => "CZK"
                ]
            ]
        ]
        ``
        Attachment below        

![Snímka obrazovky z 2023-10-19 15-15-15](https://github.com/allegro/allegro-api/assets/123319599/3817de8a-557c-4ec8-a2db-936575b7f588)

**Comment by jezewskiBNetrox** [comment]
@barbasfilip https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6


Read the "Default values that will be used to fill the data in the offer" table. API is trying to set "default" return policy, yet it didn't found one named "default" on your account.

**Comment by barbasfilip** [comment]
Works thank you.
