### ISSUE TITLE
WzA Allegro One Punkt. BAD_REQUEST

### ISSUE THREAD

**Issue by Mojeallegro123** [allegro/allegro-api#7823]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dzień dobry.
Dostajemy "BAD_REQUEST" oraz "Usługa nie jest dostępna pomiędzy wskazanymi lokalizacjami", chociaż status w otpowiedzi "200 OK".
trace-id: fc29e4a0311e41fe

Bardzo proszę o sprawdzeniu ze swojej strony.
Dziękuję.

**Comment by PrzemyslawLukanowski** [comment]
Odpowiedź 200 jest prawidłową odpowiedzią w tym przypadku, ponieważ zlecenie utworzenia przesyłki procesowane jest asynchronicznie - w odpowiedzi na użycie metody GET zwracamy konkretny powód, przez który nie udało nam się utworzyć przesyłki. W tym przypadku kupujący wybrał metodę One Punkt, która powinna zostać nadana do konkretnego punktu odbioru.
