### ISSUE TITLE
zdublowany event READY_FOR_PROCESSING dla tego samego checkoutForm

### ISSUE THREAD

**Issue by kudel** [allegro/allegro-api#7824]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Jeśli ktoś wybierze formę płatności: Allegro Pay Business
**to w liście eventów otrzymujemy zdublowany event READY_FOR_PROCESSING, dla tego samego checkoutForm**

płatność na konto bankowe: 2740174b-6f37-11ee-b4d0-f3dfc2175bf9
zamówienie: 25a6d900-6f37-11ee-ba41-fdf845d07610
zasób: GET  https://api.allegro.pl/order/events/?from=1697711470759305...

Response:
   [0] => stdClass Object
        (
            [id] => 1697799357121446
            [order] => stdClass Object
                (
                    ...

                    [checkoutForm] => stdClass Object
                        (
                            [id] => 25a6d900-6f37-11ee-ba41-fdf845d07610
                            [revision] => f1901a50
                        )

                    ...

                )

            [type] => BOUGHT
            [occurredAt] => 2023-10-20T10:55:45.725Z
        )

    [1] => stdClass Object
        (
            [id] => 1697799568961359
            [order] => stdClass Object
                (
                    ...
                   
                    [checkoutForm] => stdClass Object
                        (
                            [id] => 25a6d900-6f37-11ee-ba41-fdf845d07610
                            [revision] => 3294a91d
                        )

                    ...

                )

            [type] => READY_FOR_PROCESSING
            [occurredAt] => 2023-10-20T10:59:18.351Z
        )

    [2] => stdClass Object
        (
            [id] => 1697799568995054
            [order] => stdClass Object
                (
                    ...

                    [checkoutForm] => stdClass Object
                        (
                            [id] => 25a6d900-6f37-11ee-ba41-fdf845d07610
                            [revision] => 3294a91d
                        )

                    ...

                )

            [type] => READY_FOR_PROCESSING
            [occurredAt] => 2023-10-20T10:59:18.351Z
        )

)

**Comment by PrzemyslawLukanowski** [comment]
Tak, zdublowane eventy mogą występować i nie należy tego traktować jako błąd. Poniżej załączam fragment naszego [poradnika](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR)
<img width="471" alt="Zrzut ekranu 2023-10-20 o 15 33 23" src="https://github.com/allegro/allegro-api/assets/51473661/a1da9173-7d37-4681-917d-24bed28f3562">
.
