### ISSUE TITLE
The specified product exists. The specified parameter `Marka` with the value `bez marki(3786_1704209)` does not match the product parameter `D-look(3786_1651265)`

### ISSUE THREAD

**Issue by 3148846032** [allegro/allegro-api#7825]
The specified product exists. The specified parameter `Marka` with the value `bez marki(3786_1704209)` does not match the product parameter `D-look(3786_1651265)`

Nie jestem w stanie uzyskać atrybutu D-look (3786_1651265) odpowiadającego kategorii 124264 za pośrednictwem API
I am unable to obtain the D-look (3786_1651265) attribute corresponding to category 124264 through the API

**Comment by 3148846032** [comment]
Creating a variant will fail to inform the brand that it does not match the attribute
Tworzenie wariantu nie poinformuje marki, że nie pasuje do atrybutu

**Comment by 3148846032** [comment]
Tworzenie wariantu nie poinformuje marki, że nie pasuje do atrybutu
Creating a variant will fail, informing the brand that it does not match the attribute

**Comment by Lukasz-Zurek** [comment]
You should call **GET /sale/categories/124264/parameters/** ([documentation](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2)) where you will find current data of the Brand parameter (3786) with D-look (3786_1651265) value.

**Comment by 3148846032** [comment]
Resolved. thanks
