### ISSUE TITLE
Pobranie propozycji terminu zamówienia kuriera na sandbox - "Access is denied"

### ISSUE THREAD

**Issue by RKruza** [allegro/allegro-api#7826]
Dzień dobry. Mam problem z pobraniem listy terminów dostępności kuriera.
nazwa konta: Turbopolex

wysyłam na: /shipment-management/pickup-proposals
a w odpowiedzi otrzymuję:  {"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"No access to the specified resource."}]}

będę wdzięczny za pomoc

**Comment by Lukasz-Zurek** [comment]
Upewnij się proszę czy Twój token posiada aktualne uprawnienia (scope): **allegro:api:shipments:write**, który wymagany jest dla tego zasobu. Jeśli nie, będziesz musiał ponownie przejść przez proces autoryzacji i uwierzytelnienia użytkowników.
