### ISSUE TITLE
/sale/offers - 413 Payload Too Large

### ISSUE THREAD

**Issue by gbr161** [allegro/allegro-api#7827]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam,
Dziś podczas próby pobrania ofert z z sandboxa zacząłem otrzymywać odpowiedź jak w tytule:
"response_headers": array:4 [
    0 => "HTTP/1.1 413 Payload Too Large"
    1 => "Content-length: 106"
    2 => "Cache-Control: no-cache"
    3 => "Content-Type: text/html"
  ]

Kod działał od bardzo dawna bez problemu.

**Comment by Lukasz-Zurek** [comment]
Czy mógłbyś podać więcej szczegółów na temat wspomnianego problemu? Od kiedy otrzymujesz błędy 413? Czy Twoje requesty uległy jakiejś zmianie?

**Comment by gbr161** [comment]
Requesty nie uległy zmianie. Podczas dopisywania kolejnej funkcji i zapytaniu o oferty zauważyłem to totalnie przypadkiem. Na środowisku produkcyjnym wszystko wydaje się w porządku.

`string(72) "https://api.allegro.pl.allegrosandbox.pl/sale/offers?limit=1000&offset=0"
array(1) {
  ["http"]=>
  array(4) {
    ["method"]=>
    string(3) "GET"
    ["header"]=>
    string(1820) "User-Agent: AsocialMedia/AllegroApi/v3.1.0 (+https://asocial.media)
Authorization: Bearer eyJhbGciO....
Content-Type: application/vnd.allegro.public.v1+json
Accept: application/vnd.allegro.public.v1+json
Accept-Language: pl-PL
"
    ["content"]=>
    string(2) "[]"
    ["ignore_errors"]=>
    bool(true)
  }
}`

**Comment by jezewskiBNetrox** [comment]
> Requesty nie uległy zmianie. Podczas dopisywania kolejnej funkcji i zapytaniu o oferty zauważyłem to totalnie przypadkiem. Na środowisku produkcyjnym wszystko wydaje się w porządku.
> 
> string(72) "https://api.allegro.pl.allegrosandbox.pl/sale/offers?limit=1000&offset=0" array(1) { ["http"]=> array(4) { ["method"]=> string(3) "GET" ["header"]=> string(1820) "User-Agent: AsocialMedia/AllegroApi/v3.1.0 (+https://asocial.media) Authorization: Bearer eyJhbGciO.... Content-Type: application/vnd.allegro.public.v1+json Accept: application/vnd.allegro.public.v1+json Accept-Language: pl-PL " ["content"]=> string(2) "[]" ["ignore_errors"]=> bool(true) } }

@gbr161 Zapytania GET nie są wspierane z body requestu. Widać, że coś masz wpisane w `content`, a GET tego nie wspiera.
