### ISSUE TITLE
Zwroty Allegro - pytanie o status

### ISSUE THREAD

**Issue by Norivo7** [allegro/allegro-api#7828]
Dzień dobry, 
W automatycznym systemie we własnej implementacji Alllegro-api do obsługi zwrotów zamówień:
Mamy małą anomalie w działaniu obsługi zwrotów - pojawiają się zwroty ze statusem "CANCELED":
![Screenshot from 2023-10-23 08-43-53](https://github.com/allegro/allegro-api/assets/38659561/de689644-327a-4e3a-ba88-902cf6f6f3b3)
Nie mogę znaleźć wzmianki w dokumentacji o opisie statusów obiektów refundu.
Proszę o link albo wytłumaczenie co dany status oznacza.
Kiedy pojawia się status "CANCELED", czy może ustawić się automatycznie, gdy wielokrotnie nie ma środków na koncie żeby wykonać zwrot? Czy możemy wykryć czy ten status został ustawiony manualnie przez którąś z funkcji z panelu Allegro?
Dodam, że żaden z naszych systemów który powininen obsługiwać zwrot środków w Allegro nie ustawia statusu "Canceled".
Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Poniżej załączam zrzut z dostępnymi wartościami pola "status". 

Jest dokładnie tak jak napisałeś - "CANCELED" ustawiamy automatycznie, gdy nie uda nam się pobrać środków z salda sprzedającego. Nie ma możliwości, aby sprzedający ustawił go manualnie po swojej stronie.

<img width="702" alt="Zrzut ekranu 2023-10-23 o 09 54 28" src="https://github.com/allegro/allegro-api/assets/51473661/5dc57ffa-2bdb-4331-90fd-296a365c70f3">

**Comment by Norivo7** [comment]
Okej, rozumiem, tylko teraz zostaje jedna niewiadoma. Stan konta sprzedającego jest wystarczający żeby wykonać zwrot, jednak płatność nie trafia do klienta, a dostaje status "CANCELED". Czy możecie nakierować gdzie może leżeć błąd? W jakich innych przypadkach zwrot nie trafia do klienta? Czy istnieją jakieś opcje typu limitu transakcyjnego do zwrotów? Proszę o pomoc.

**Comment by MaciejFrackowiak** [comment]
W tym konkretnym przypadku przez 24 godziny próbowaliśmy wykonać zwrot dla wskazanej płatności. Środki jednak nie pozwalały na jej wykonanie. Natomiast już po same szczegóły (gdy jak piszesz stan konta sprzedającego jest wystarczający żeby wykonać zwrot) proszę Cię o [kontakt z obsługą serwisu](https://allegro.pl/pomoc/kontakt), ponieważ to już czysto operacyjna czynność związana z obsługą Allegro.

**Comment by MaciejFrackowiak** [comment]
To już pytanie stricte całkowicie poza zakresem API - proszę zadaj je obsłudze Allegro.

**Comment by Norivo7** [comment]
Okej, dziękuje za pomoc. Zamykam temat.
