### ISSUE TITLE
Bon dla nauczycieli

### ISSUE THREAD

**Issue by harorri** [allegro/allegro-api#7829]
Dzień dobry,
obecnie jesteśmy przy implementacji "Bon dla nauczyciela".
Mamy problem z stworzeniem odpowiedniej aukcji do przetestowania nowej funkcjonalności. Dodaliśmy do niej kampanię "Laptop dla nauczyciela - test", pojawiło się oznaczenie na aukcji "Bon dla nauczycieli", ale podczas kupna nie ma sekcji do wpisania bonu.
https://allegro.pl.allegrosandbox.pl/oferta/proba-bon-7728761752

Proszę o pomoc.

**Comment by MaciejFrackowiak** [comment]
Wyjaśniam kwestię z zespołem odpowiedzialnym za usługę, wrócę z odpowiedzią.

**Comment by harorri** [comment]
@MaciejFrackowiak Jest możliwość uzyskania większej ilości kodów do testów?

**Comment by MaciejFrackowiak** [comment]
Każda kombinacja z wykorzystaniem [0-9 A-F] generuje prawidłowy bon.
