### ISSUE TITLE
[REST] Problem z wystawieniem aukcji

### ISSUE THREAD

**Issue by ne7son** [allegro/allegro-api#783]
Dzień dobry,

W momencie tworzenia aukcji z obrazkiem w opisie otrzymuje błąd 
 { code: 'VALIDATION_ERROR',
    message: 'Description images are not valid.',
           details: 'Invalid value: unknown',
           path: 'offerDto',
           userMessage: 'Description images are not valid.' }

obrazek jest ładowany na zasób /sales/images - serwery sandbox
przesyłany json jest zgodny z tutorialem https://developer.allegro.pl/sale/

Przesyłany json: 
{"name":"zgloszenie nr 1 ","category":{"id":"79456"},"location":{"countryCode":"PL","province":"WIELKOPOLSKIE","city":"Poznań","postCode":"60-166"},"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Tekstowy opis przedmiotu</p>"},{"type":"IMAGE","url":"https://4.allegroimg.allegrosandbox.pl/original/114572/145ac2314447966637d434311494"}]}]},"images":[{"url":"https://c.allegroimg.allegrosandbox.pl/original/115022/4d709223430a8cd3ece77cc8cb4c"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"15.4","currency":"PLN"},"startingPrice":null,"minimalPrice":null},"delivery":{"shippingRates":{"id":"7f50dd7f-a972-488e-9f46-1a97b2ff8b03"},"handlingTime":"PT168H","additionalInfo":null,"shipmentDate":null},"payments":{"invoice":"NO_INVOICE"},"stock":{"available":"10","unit":"UNIT"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null}]}

**Comment by imper86** [comment]
A nie zapomniałeś dorzucić linków do obrazków do "images"? Tu przykład z tutoriala:

```json
"images": [                                 -- wymagane ścieżki obrazków, zdjęcia 
                                                prześlesz przy pomocy metody 
                                                POST na zasobie /sale/images.
                                                Pierwsze zdjęcie w tablicy jest jednocześnie 
                                                pierwszym zdjęciem w ofercie (miniaturką).
        {
            "url": "https://e.allegroimg.com/original/01fd60/4ea8d18e4275b0878b7f0562067e"
        },
        {
            "url": "https://e.allegroimg.com/original/018474/c62b54a74120a7983b09d0fa4a4e"
        },
        {
            "url": "https://8.allegroimg.com/original/013a51/4dd0904a4169ad8b0d25a8984b48"
        },
        {
            "url": "https://2.allegroimg.com/original/01b48e/6e777def4a71ba68952358bd2072"
        }
    ],
```

**Comment by ne7son** [comment]
OK, Faktycznie masz racje wszystkie obrazki idące w descripion muszą być zawarte w images.
Dzięki :+1:
