### ISSUE TITLE
Nie znaleziono parametru o id NNN w podanej kategorii NNNNNN

### ISSUE THREAD

**Issue by stalkerGH** [allegro/allegro-api#7830]
Próbuję wystawić ofertę z nowym produktem w kategorii 110912 (Plakaty), ale otrzymuję komunikat:

{ "errors": [ { "code": "ParameterIdNotFoundException", "message": "Unprocessable Entity", "details": null, "path": "productSet[0].product.parameters", "userMessage": "Nie znaleziono parametru o id 774w podanej kategorii110912." } ] } 

Pobrałem parametry dla kategorii 110912:

https://api.allegro.pl/sale/categories/110912/parameters

I nie widzę tam parametru o id 774.

Trace-ID zapytania: 16e527eb637d3143

**Comment by MaciejFrackowiak** [comment]
W swoim requeście wysłałeś:
```
{
                        "id": "774",
                        "name": "Temat",
                        "values": [
                            "zwierzęta"
                        ],
                        "valuesIds": [
                            "774_293333"
                        ],
                        "rangeValue": null
                    }
```
I właśnie dlatego jako rezultat otrzymałeś błąd 422 z przytoczonym komunikatem błędu.

**Comment by stalkerGH** [comment]
Dziękuję, rzeczywiście miałem pomieszane parametry z różnych kategorii. Udało mi się już to uporządkować, ale teraz mam komunikat: 

> Brak dostępu. Nie masz uprawnień do operacji na wskazanej ofercie

Działam na koncie firmowym.

Trace-ID: f9dc05a31370deb2

**Comment by MaciejFrackowiak** [comment]
Konto, z którego wykonany był request to konto zwykłe - a ten typ konta nie może wystawiać ofert poprzez API.

**Comment by stalkerGH** [comment]
Hmmm, w takim razie rejestracja konta na Allegro z podaniem NIP nie jest równoznaczna z posiadaniem konta firmowego? Gdzie mogę sprawdzić, jaki typ konta posiadam?

**Comment by MaciejFrackowiak** [comment]
Skorzystaj z [GET /me](https://developer.allegro.pl/documentation/#operation/meGET) i sprawdź z jakiego konta wykonujesz request. Możesz także rozkodować wykorzystywany token i tam znajdziesz id konta w polu "user_name".

**Comment by stalkerGH** [comment]
Dziękuję, spróbuję. A jak to sprawdzić bezpośrednio na koncie Allegro, z poziomu przeglądarki?

**Comment by MaciejFrackowiak** [comment]
W prawym górnym logu zobaczysz swój login, na który obecnie jesteś zalogowany.

**Comment by stalkerGH** [comment]
> W prawym górnym rogu zobaczysz swój login, na który obecnie jesteś zalogowany.

Wiem, jak sprawdzić login :) Bardziej interesowało mnie sprawdzenie typu konta. Dla potomnych: `Konto -> Moje konto -> Ustawienia konta -> Twoje dane -> Zmień -> Dane konta`.

Wszystkie znaki na niebie i ziemi wskazują, że mam konto firmowe:

![Untitled](https://github.com/allegro/allegro-api/assets/25331715/c4f41aa3-6fd9-40e6-85d2-d3aed0c4d3af)

**Comment by MaciejFrackowiak** [comment]
W [GET /me](https://developer.allegro.pl/documentation/#operation/meGET) taką informację otrzymasz. Nie kwestioniuję, że posiadasz konto firmowe - jednak requesty, o których wspominasz w wątku na pewno wykonałeś z innego konta - konta zwykłego, którego login to xxxxxxx78.

**Comment by stalkerGH** [comment]
Nie rozumiem, jak to możliwe. Na koncie xxxxxxx78 (zwykłym) nie mam żadnych aplikacji związanych z API Allegro, wyłącznie integrację z InPost, więc teoretycznie nie powinno być możliwości pobrania np. listy ofert czy struktury konkretnej oferty po jej ID.  Zresztą z konta zwykłego (prywatnego) nie prowadzę sprzedaży.

Mam za to jedną aplikację na koncie firmowym (xxxxxxxxx_pl). Token używany w zapytaniach jest wygenerowany z pary client_id / client_secret konta firmowego.

O co chodzi? :)

**Comment by MaciejFrackowiak** [comment]
W jaki sposób wykonywałeś te wcześniejsze requesty? Był to jakiś program z interfejsem graficznym np. przeglądarka?

**Comment by stalkerGH** [comment]
> W jaki sposób wykonywałeś te wcześniejsze requesty? Był to jakiś program z interfejsem graficznym np. przeglądarka?

Na początku próbowałem wyłącznie za pomocą curl. Ostatnie kilkanaście prób, w tym ta z informacją o braku uprawnień, była wykonana za pomocą wtyczki Talend API Tester (z przeglądarki). Oczywiście przeglądarka korzysta z tego samego tokena co curl.

**Comment by MaciejFrackowiak** [comment]
To niestety ta wtyczka "gubi" właściwe ClientId i "przedstawia się" jako przeglądarka WWW - w ten sposób rezultatem końcowym są requesty wykonywane z Twojego zwykłego konta (musisz być zalogowany na zwykłym koncie bądź przeglądarka pamięta Twoja sesję z kontem zwykłym).

**Comment by stalkerGH** [comment]
Rozumiem. Czyli mam takie możliwości:

a) całkowicie rezygnuję z używania Talend API Tester,
b) podaję w Talend API Tester właściwe ClientId (jak?),
c) korzystam z Talend API Tester, ale tylko wtedy, gdy jestem zalogowany w innej sesji (karcie) na koncie firmowym,
d) korzystam z curl.

Zgadza się?

**Comment by MaciejFrackowiak** [comment]
Nie wiem jak działa oprogramowanie, z którego korzystasz, ale ClientId danej aplikacji jest nierozłącznie powiązane z jego ClientSecret, gdzie ich kombinacja zakodowana jest niezbędna do wygenerowania tokena. Krótko mówiąc - realizacja wywołań za pośrednictwem cURL wydaje się być najbardziej optymalnym rozwiązaniem.

**Comment by stalkerGH** [comment]
W porządku, spróbuję najpierw rozwiązania c) i dam znać.
