### ISSUE TITLE
Delete ENDED offer

### ISSUE THREAD

**Issue by ZdenekMrazek** [allegro/allegro-api#7831]
Hello, is there a way how to delete the offer to completely get rid of it when it is in another status then ACTIVE?
I can only delete the INACTIVE draft order.
Is there a way how to set the status back to INACTIVE?
If I try to send therequest bellow to the PATCH https://api.allegro.pl/sale/product-offers/14536586681 endpoint, it does not return any error, but it does not change the status at all.

{"stock":{"available":0,"unit":"UNIT"},"publication":{"marketplaces":{"base":{"id":"allegro-cz"}},"status":"INACTIVE","endedBy":"USER","republish":false}}

Thanks.

**Comment by MaciejFrackowiak** [comment]
No, you cannot delete offers with the status "ENDED". Also, you cannot change an offer status to "INACTIVE" again.
