### ISSUE TITLE
błędne działanie zasobu /sale/categories

### ISSUE THREAD

**Issue by barpas** [allegro/allegro-api#7832]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [ X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

po zadaniu pytania: https://api.allegro.pl/sale/categories?parent.id=7
otrzymujemy odpowiedź:  (to jest fragment)
{..},{"id":"79193","name":"Poradniki i albumy","parent":{"id":"7"},"leaf":true,"options":{"variantsByColorPatternAllowed":true,"advertisement":false,"advertisementPriceOptional":false,"offersWithProductPublicationEnabled":true,"productCreationEnabled":true,"customParametersEnabled":true,"sellerCanRequirePurchaseComments":false}},{...}

z której wynika że kategoria 79193 jest liściem 

z kolei zapytanie: https://api.allegro.pl/sale/categories?parent.id=79193 

zwraca pustą listę podkategorii (co jest logiczne skoro kategoria 79193  jest liściem) 

problem w tym że jest to  niezgodnie z prawdą bo kategoria ta posiada 18 podkategorii do których kierują pola w opisach aukcji zasobu list, można to również zobaczyć na stronie: https://allegro.pl/kategoria/poradniki-i-albumy-79193

**Comment by MaciejFrackowiak** [comment]
Jest to prawidłowe działanie mechanizmu - w zasobie /sale/categories otrzymujesz tzw. drzewo asortymentowe, w którym są dostępne kategorie dla sprzedających. Po stronie kupującego natomiast widnieje tzw. drzewo nawigacyjne, gdzie jest ono zachowane sprzed zmian, które miały miejsce [7 sierpnia 2023](https://allegro.pl/pomoc/aktualnosci/7-sierpnia-zmienimy-sposob-wystawiania-ofert-w-kategorii-ksiazki-i-komiksy-lL2zaRwxdc7).

**Comment by barpas** [comment]
interesujące... czyli jeżeli list informuje mnie że aukcja oferowana jest w kategorii 79206 która nie istnieje w "drzewie asortymentowym" to jak mam się dowiedzieć co to w ogóle jest ?

**Comment by MaciejFrackowiak** [comment]
Jeśli pobierzesz szczegóły danej oferty ([GET /sale/product-offers/{offerid}](https://developer.allegro.pl/documentation/#operation/getProductOffer)) to otrzymasz jej właściwą kategorię.

**Comment by barpas** [comment]
tylko jak pobrać szczegóły nie swojej oferty ?!?!?

**Comment by MaciejFrackowiak** [comment]
Nie ma takiej możliwości. Jak wspomniałem wcześniej - drzewo nawigacyjne jest przeznaczone dla kupujących, dla sprzedających kluczowe jest drzewo asortymentowe, a to bez problemów możesz pobrać.

**Comment by barpas** [comment]
czyli podsumowując: zasób offers/listing zwraca w polu kategoria jakieś numerki których (w przypadku niektórych aukcji) w żaden sposób nie da się z niczym połączyć, jak również nie wiadomo z jakiej kategorii są to aukcje i nie da się tego dowiedzieć - zgadza się? 

jak rozumiem wg Allegro wszystko jest w porządku ?

**Comment by MaciejFrackowiak** [comment]
Zasób /offers/listing zwraca id kategorii, która została spłaszczona (szczegóły w pliku dołączonym do artykułu z Pomocy Allegro), a która to kategoria jest dostępna dla kupujących - /offers/listing to odwzorowanie listingu ze strony WWW.

**Comment by barpas** [comment]
zasób offers/listing zwraca np id do kategorii 79206 i innych których nie ma w drzewie nazwanym przez Pana "asortymentowym" i nie ma jak się dowiedzieć co to za kategoria ...

zepsuliście i skomplikowali kolejną prostą rzecz bo zdaje się wyłącznie tym się zajmujecie

**Comment by MaciejFrackowiak** [comment]
Kategoria 79206 jest wymieniona we wspomnianym pliku, jako kategoria, która uległa spłaszczeniu. Swoje uwagi możesz przekazać poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt), ponieważ operacja ta dotyczyła całego Allegro, a nie tylko API.
