### ISSUE TITLE
HttpMessageNotReadableException for product-proposals

### ISSUE THREAD

**Issue by zakjar** [allegro/allegro-api#7833]
Sandbox,  account : rejzr

I am learning to work with api and I try create my first product.  I call

POST data: https://api.allegro.pl.allegrosandbox.pl/sale/product-proposals

{"name":"Froddo G2110130-23 cognac chlapecká dětská kožená zimní obuv","parameters":[{"id":"224017","values":["G2110130-23"]},{"id":"7174","valuesIds":["7174_1705364"]},{"id":"5389","values":["22"]},{"id":"249512","valuesIds":["249512_1647427"]},{"id":"225693","values":["3850391469637"]}],"images":[{"url":"https://a.allegroimg.allegrosandbox.pl/original/117542/0e643c674939b610c0e02502a146"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/11c095/c12756b8444195bb63411961c215"}],"category":{"id":147743},"language":"cs-CZ"}

Response:
{"errors":[{"code":"HttpMessageNotReadableException","message":"An error has occurred","details":null,"path":null,"userMessage":"Požadavek obsahuje neplatné údaje. Kontaktujte autora aplikace."}]}

From the error description, I don't know what exactly to change. Can you help me ?
Do you have an example of "minimal JSON" to create  children's footwear product?

**Comment by MaciejFrackowiak** [comment]
Your request structure is correct, but there is some issue with encoding - as I see in our logs - "Invalid UTF-8 middle byte 0x20". So please, recheck your request if it is correctly encoded.

**Comment by zakjar** [comment]
Thank you - I use Java and apache.http.client

When I add second parametr "UTF-8" in constructor StringEntity ... problem is solved.  

httpPost.setEntity(new StringEntity( instance.data, "UTF-8" ));

!!! But I have new problem. I get now response

{"errors":[{"code":"MissingImageException","message":"Product needs to have at least one image"

But my Json has "images" - and you wrote to me, that my request structure was OK

POST data: https://api.allegro.pl.allegrosandbox.pl/sale/product-proposals
{"name":"Froddo G2110130-23 cognac chlapecká dětská kožená zimní obuv","parameters":[{"id":"224017","values":["G2110130-23"]},{"id":"7174","valuesIds":["7174_1705364"]},{"id":"5389","values":["22"]},{"id":"249512","valuesIds":["249512_1647427"]},{"id":"225693","values":["3850391469637"]}],"images":[{"url":"https://a.allegroimg.allegrosandbox.pl/original/117542/0e643c674939b610c0e02502a146"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/11c095/c12756b8444195bb63411961c215"}],"category":{"id":147743},"language":"cs-CZ"}
Response:
{"errors":[{"code":"MissingImageException","message":"Product needs to have at least one image","details":null,"path":"parameters","userMessage":"Produkt by měl mít alespoň jednu fotografii"}]}

**Comment by zakjar** [comment]
I my Json request I used AllegroImage url ... bat this Url his expired
