### ISSUE TITLE
Problem z zamówieniem podjazdu kuriera Allegro One

### ISSUE THREAD

**Issue by areklal** [allegro/allegro-api#7834]
Witam,

Mamy autorskie narzędzie do adresowania przesyłek Allegro One. Przykłady poprawnie zaadresowanych przesyłek:

Numer listu / nr zam

A0005A6YM1 - dd2e97d0-6f27-11ee-ba2e-698fcda1f654
A00057PNY6 - 0f7e8970-6f28-11ee-948c-e3b8932a9b47

Nie dorabialiśmy funkcji zamawiania podjazdu kuriera przez API, ponieważ wysyłamy sporo przesyłek,  więc docelowo będzie ustawiony stały codzienny podjazd. Wobec tego chcemy narazie zamawiać podjazd kuriera przez WzA - ale zaznaczając te przesyłki i klikając w zamów podjazd nie mamy opcji wyboru - dlczego? Zrzut ekranu : https://prnt.sc/ZHwZnMjFXNlC ---> https://prnt.sc/iLU1G_Hfdzl1

Dla testów zaadresowaliśmy inną przesyłkę nie przez API ale z poziomu WzA 👍 

A0005FIRE2 - 6c91d0c0-7236-11ee-bcb3-f5e1b3e95720 

I tutaj da się zamówić podjazd (zrzut : https://prnt.sc/ENK4_vPMNTzP)- dlaczego? Proszę o pomoc bo już mi ręce opadają :)

**Comment by areklal** [comment]
@MaciejFrackowiak Panie Macieju- jak moje pytanie? Temat jest mocno pilny

**Comment by MaciejFrackowiak** [comment]
Wyjaśniam kwestię z zespołem, jak tylko uzyskam odpowiedź dam znać.

**Comment by areklal** [comment]
@MaciejFrackowiak Rozumiem - od jutra chcemy wysyłać allegro one i bez tego nie damy rady. Może chodzi o jakiś parametr podczas adresowania przez API który decyduje czy można zamawiać kuriera po podjazd czy w ogóle jest to niemożliwe?

**Comment by MaciejFrackowiak** [comment]
Zespół sprawdził sytuację i niestety dla przesyłek (A0005A6YM1, A00057PNY6) nie znaleźliśmy żadnych wywołań w naszym backendzie. Czy w konsoli przeglądarki nie pojawiają się jakieś błędy?

**Comment by areklal** [comment]
@MaciejFrackowiak W sensie wywołań zamówienia podjazdu kuriera? Jak napisałem na samej górze nie próbowaliśmy tego robić przez API tylko z poziomu webowej WzA : Zrzuty : https://prnt.sc/ZHwZnMjFXNlC ---> https://prnt.sc/iLU1G_Hfdzl1  Może sprawdźcie od backendu wartości parametrów dla tych wysyłek i porównajcie z tą do której mogę zamówi podjazd z poziomu przeglądarki : A0005FIRE2 - 6c91d0c0-7236-11ee-bcb3-f5e1b3e95720 .

**Comment by MaciejFrackowiak** [comment]
I właśnie oto chodzi - czy w przeglądarce (jej konsoli) pojawia się cokolwiek niepokojącego podczas próby zamówienia tych podjazdów? Jak pisałem, nie widzimy śladu po jakichkolwiek wywołaniach via WWW, stąd być może coś skrywa konsola.

**Comment by areklal** [comment]
@MaciejFrackowiak Dla przesyłek dla których jest opcja zamówienia podjazdu konsola wygląda tak: https://prnt.sc/hgoiXPKKMRuK a dla  przesyłek dla których nie da się zamówić podjazdu wygląda tak  : https://prnt.sc/7iEFrgOX11ei - czy to coś Wam mówi?

**Comment by MaciejFrackowiak** [comment]
Dziękuję za szczegóły. Przypadek został zaadresowany bezpośrednio do osób odpowiedzialnych za frontend.

**Comment by areklal** [comment]
@MaciejFrackowiak Czy odpowiedź będzie w tym wątku czy jakoś oddzielnie?

**Comment by MaciejFrackowiak** [comment]
Jak tylko otrzymam jakiekolwiek info zwrotne, dam znać w tym wątku.

**Comment by MaciejFrackowiak** [comment]
Problem generuje przesyłka "A0005A8IF4 z commandId: 18129ece-99f3-4069-9a26-56ca3b3e802f" - w requeście pole "pickup" przyjęło wartość "null", zatem już z definicji nie można dla niej zamówić podjazdu. Efektem końcowym jest problem z zamówieniem podjazdu dla każdej innej przesyłki, którą zaznaczałeś razem - tu oczywiście będziemy poprawiać front by takie sytuacje na przyszłość wyeliminować.
