### ISSUE TITLE
NotAllowedException - The HTTP method is not allowed

### ISSUE THREAD

**Issue by ke-mez** [allegro/allegro-api#7835]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Cześć,
Na środowisku testowym próbuję skorzystać z zasobu /shipment-management/shipments/create-commands/
Sprawdziłem: konto posiada uprawnienia allegro:api:shipments:read oraz allegro:api:shipments:write, token jest poprawnie odświeżony i zawiera te uprawnienia.
Jakkolwiek bym tego nie robił, nie jestem w stanie przejść dalej
Przykładowy traceId: d98cbeed208dd5d5
otrzymałem:
statusCode: 405
{\"errors\":[{\"code\":\"NotAllowedException\",\"message\":\"The HTTP method is not allowed\",\"details\":null,\"path\":null,\"userMessage\":\"An error occurred\"}]}

Mogę poprosić o sprawdzenie, co mnie blokuje? I ewentualną pomoc, bo nie wiem, co robię źle :(

**Comment by MaciejFrackowiak** [comment]
Jakiego typu autoryzacji używasz? Pytam, ponieważ w logach nie widzę identyfikatora użytkownika, co świadczyłoby, że korzystasz z autoryzacji client_credentials.

**Comment by ke-mez** [comment]
Jestem prawie pewny, że przeprowadziłem autoryzację typu device_flow, mam user_code, device_code, oraz access_token, czy to wystarczy?

**Comment by MaciejFrackowiak** [comment]
Usuń proszę "/" z adresu wywołania na samym końcu tj. przekaż adres /shipment-management/shipments/create-commands.

**Comment by ke-mez** [comment]
Dziękuję, faktycznie, to wyglądało na niepotrzebne.
Tylko teraz dostałem coś takiego:

{\"errors\":[{\"code\":\"ERROR\",\"message\":\"The object sent cannot be properly parsed\",\"details\":null,\"path\":\"input.additionalServices\",\"userMessage\":\"Nie można prawidłowo sparsować przesłanego obiektu\"}]}
Domyślam się, że którejś ze zmiennych nie podstawiam w sposób poprawny.
Podrzucam nowy traceId: "978dc0eeeb3d8ce2".
Mogę poprosić o sprawdzenie? Nie wiem czy dobrze to rozumiem, czy coś nie tak z pickupem?

**Comment by MaciejFrackowiak** [comment]
Pole "additionalServices" jest tablicą, czyli przekaż proszę tam [] zamiast null - po takiej zmianie request skończy się sukcesem.

**Comment by ke-mez** [comment]
Dziękuję za naprowadzenie :) Faktycznie tam było nie tak, jak być powinno :)
Wracam z kolejnym pytaniem:
Chyba utknąłem na etapie generowania etykiety, korzystając z zasobu:
https://api.{environment}/shipment-management/label
na środowisku testowym, czyli: "https://api.allegro.pl.allegrosandbox.pl/shipment-management/label"
(tym razem sprawdziłem 3 razy czy nie ma dodatkowych dziwnych doklejonych znaków),
próbując wygenerować etykietę dla shipmentId: "282ba787-c8e8-4057-abfc-ed60018cfd14"
Otrzymuję:
"The remote server returned an error: (406) Not Acceptable." 
Czy dobrze rozumiem, że w tym przypadku nagłówek Accept musi być "application/pdf" lub "text/plain"? Czy coś jeszcze powinienem dodać?

**Comment by MaciejFrackowiak** [comment]
Zasób ten wymaga nagłówka "application/octet-stream".

**Comment by ke-mez** [comment]
Szybka odpowiedź, dziękuję, Ale to chyba nie rozwiązuje mojego problemu:
Teraz, gdy nagłówek został odpowiednio nadany, mam coś takiego:
_"The remote server returned an error: (401) Unauthorized."_
w wyjątku złapało się jeszcze to poniżej:
◢ | Headers | {trace-id: cbd256ff2d5041e2 Content-Length: 102 Content-Type: application/json; charset=utf-8 Date: Thu, 26 Oct 2023 12:12:13 GMT WWW-Authenticate: Bearer realm="oauth2-resource", error="unauthorized", error_description="Full authentication is required to access this resource".

Mogę poprosić o rzut okiem i podpowiedź?
Autoryzacja taka sama jak wcześniej :(

**Comment by MaciejFrackowiak** [comment]
Błąd 401 w tym przypadku oznacza, że utraciłeś autoryzację - z logów widzę, że nie zostało przekazane userId konta, czyli nie mogliśmy w rezultacie wykonać requestu.

**Comment by ke-mez** [comment]
Nie wiem czy dobrze myślę:
  Sprawdziłem token dostępowy i widzę w nim uzupełnione wszystkie zmienne które wydają się niezbędne (wyczyściłem wartości, ale są tam)
  "user_name": "",
  "scope": [
    "allegro:api:orders:read",
    "allegro:api:fulfillment:read",
    "allegro:api:profile:write",
    "allegro:api:fulfillment:write",
    "allegro:api:sale:offers:write",
    "allegro:api:billing:read",
    "allegro:api:campaigns",
    "allegro:api:disputes",
    "allegro:api:bids",
    "allegro:api:sale:offers:read",
    "allegro:api:shipments:write",
    "allegro:api:orders:write",
    "allegro:api:ads",
    "allegro:api:payments:write",
    "allegro:api:sale:settings:write",
    "allegro:api:profile:read",
    "allegro:api:ratings",
    "allegro:api:sale:settings:read",
    "allegro:api:payments:read",
    "allegro:api:shipments:read",
    "allegro:api:messaging"
  ],
  "allegro_api": true,
  "iss": "https://allegro.pl.allegrosandbox.pl",
  "exp": "",
  "jti": ""
  "client_id": ""
co mam rozumieć przez "utraciłeś autoryzację"?
UserId nigdzie nie uległo zmianie, wszystko próbuję wykonywać w jednej procedurze.
Jeśli chodzi o client_id, client_secret, user_code, device_code, access_token - wszystkie te zmienne ciągle są dostępne w moim programie, ale ciągle dostaję ten sam błąd.
Odświeżyłem token tuż przed wykonaniem zapytania i to samo :(
 :)

**Comment by MaciejFrackowiak** [comment]
Przekazujesz request, który nie ma ClientId oraz userId - sprawdź proszę dokładnie przekazywane w wywołaniu dane.
