### ISSUE TITLE
Przesyłanie parametru nazwy produktu przy wystawianiu aukcji

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#7836]
Mam pytanie o ten [fragment dokumentacji](https://prnt.sc/PNfHi9Xl7aX0). Przy wystawianiu oferty, prosicie, aby w tablicy `productSet` przesłać nazwę produktu `name` w typie `string` z limitem znaków wynoszącym <=75.

Czy zawsze był ten limit znaków, czy został może dodany/zwiększony w ostatnim czasie? Jeżeli zmieniono coś w tym obszarze, to mniej więcej kiedy?
Czy można ten parametr pominąć całkowicie przy wysyłaniu zapytania i zostanie ono poprawnie obsłużone?

Dla mnie (nieistotne dla powyższego zapytania): 77993.

**Comment by DamianKAtomStore** [comment]
Okej, ale w zapowiedzi informujecie o [tytule oferty](https://prnt.sc/2RUIygZO9bgr), natomiast ja pytam o [nazwę produktu](https://prnt.sc/UiBuvBvGqMuL). Rozumiem więc, że oba te pola zostały objęte zmianą i oba są wymagane?

**Comment by MaciejFrackowiak** [comment]
Nazwa produktu również została ujednolicona do 75 znaków. Jeżeli produkt jest w naszej bazie to nie musisz podawać jego nazwy. Natomiast jeśli dodajesz całkowicie nowy produkt to musisz podać jego nazwę.

**Comment by DamianKAtomStore** [comment]
To wszystko co potrzebowałem wiedzieć, dziękuję za pomoc.

**Comment by DamianKAtomStore** [comment]
Mam jednak jeszcze jedno pytanie. Zauważyliśmy, że system raz puszcza nazwy produktów dłuższe niż 75 znaków, a innym razem nie.
Z informacji od klienta: "ciekawy był przypadek przy towarze EAN 5404020139071. Na tym EAN był błąd 75 znaków, a po dodaniu innego z Allegro EANu który jest błędny jednak przypięty do katalogu : 9319612174872 aukcja się wystawiła"

Czy możecie potwierdzić / zdementować moją teorię:
Jeśli produkt znajduje się w katalogu Allegro (EAN) to Allegro sobie ignoruje przesyłaną nazwę produktu nawet jeśli ma więcej niż 75 znaków, bo mają swoją nazwę w bazie i ta informacja nie jest potrzebna.
Jeśli jednak produktu nie ma w katalogu Allegro (EAN), to już bezwarunkowo trzeba się zmieścić w tym limicie do 75 znaków dla nazwy produktu.

**Comment by MaciejFrackowiak** [comment]
Zgadza się - jeśli produkt jest w bazie to nie ma zasadności przesyłania jego nazwy, ponieważ uwzględnimy jego nazwę z posiadanych już danych. Tu sprzedający zawsze może zgłosić ewentualnie [sugestię](https://developer.allegro.pl/documentation/#operation/productChangeProposal) zmiany danych produktu. 
Tak, tworząc nowy produkt trzymamy się limitu 75 znaków dla nazwy produktu (w naszej bazie można spotkać produkty, których nazwy są dłuższe, jednak to efekt historycznych zmian w samym katalogu).
