### ISSUE TITLE
Allegro One Box

### ISSUE THREAD

**Issue by roberto102** [allegro/allegro-api#7837]
Dzień dobry.
Przebrnąłem prze metodę 
https://api.allegro.pl/shipment-management/shipments/create-commands
Dostaję prawidłową odpowiedź.

---------------------------- Request
{
    
   "input":{
      "deliveryMethodId":"0aafb43c-e66a-46ec-9cc4-29bb39ebb483", 
      "credentialsId":"", 
      "sender":{ 
         "name":"Einhell", 
         "company":"Einhell SP. Z O.O.", 
         "street":"Józefa Wymysłowskiego", 
         "streetNumber":"1", 
         "postalCode":"55-080", 
         "city":"Nowa Wieś Wrocławska", 
         "countryCode":"PL", 
         "email":"allegro@einhell.pl", 
         "phone":"+48 795 682 528"
         
      },
      "receiver":{ 
         "name":"Dorian Turkiewicz",
         "company":"", 
         "street":"Krzycka", 
         "streetNumber":"67a", 
         "postalCode":"53-019", 
         "city":"Wrocław", 
         "countryCode":"PL", 
         "email":"kaov93bbpw+45dc54b47@allegromail.pl", 
         "phone":"+48 601 175 670",
         "point":"AL209DW1"
      },
      "pickup":{ 
         "name":"Dorian Turkiewicz", 
         "company":"", 
         "street":"Krzycka",
         "streetNumber":"67a", 
         "postalCode":"53-019", 
         "city":"Wrocław",
         "countryCode":"PL", 
         "email":"kaov93bbpw+45dc54b47@allegromail.pl", 
         "phone":"+48 601 175 670", 
         "point":"AL209DW1" 
      },
      "referenceNumber":"ZAMEINHELL",
      "description":"Elektronarzędzia", 
      "packages":[ 
         {
            "type":"OTHER", 
            "length":{ 
               "value":12,
               "unit":"CENTIMETER"
            },
            "width":{ 
               "value":12,
               "unit":"CENTIMETER"
            },
            "height":{ 
               "value":12,
               "unit":"CENTIMETER"
            },
            "weight":{ 
               "value":2,
               "unit":"KILOGRAMS"
            }
         }
      ],
      "insurance":{
         "amount":"11.00", 
         "currency":"PLN" 
      },
      
      "labelFormat":"PDF", 
      "additionalServices":[ 
         "ADDITIONAL_HANDLING"
      ],
"additionalProperties": {}
   }
}

---------------------------- Response
{
	"commandId": "c545eb35-9e3c-40a3-b93e-e1b2bcaee450",
	"input": {
		"deliveryMethodId": "0aafb43c-e66a-46ec-9cc4-29bb39ebb483",
		"credentialsId": "",
		"sender": {
			"name": "Einhell",
			"company": "Einhell SP. Z O.O.",
			"street": "Józefa Wymysłowskiego",
			"streetNumber": "1",
			"postalCode": "55-080",
			"city": "Nowa Wieś Wrocławska",
			"state": null,
			"countryCode": "PL",
			"email": "allegro@einhell.pl",
			"phone": "+48 795 682 528",
			"point": null
		},
		"receiver": {
			"name": "Dorian Turkiewicz",
			"company": "",
			"street": "Krzycka",
			"streetNumber": "67a",
			"postalCode": "53-019",
			"city": "Wrocław",
			"state": null,
			"countryCode": "PL",
			"email": "kaov93bbpw+45dc54b47@allegromail.pl",
			"phone": "+48 601 175 670",
			"point": "AL209DW1"
		},
		"pickup": {
			"name": "Dorian Turkiewicz",
			"company": "",
			"street": "Krzycka",
			"streetNumber": "67a",
			"postalCode": "53-019",
			"city": "Wrocław",
			"state": null,
			"countryCode": "PL",
			"email": "kaov93bbpw+45dc54b47@allegromail.pl",
			"phone": "+48 601 175 670",
			"point": "AL209DW1"
		},
		"referenceNumber": "ZAMEINHELL",
		"description": "Elektronarzędzia",
		"packages": [
			{
				"type": "OTHER",
				"length": {
					"value": 12,
					"unit": "CENTIMETER"
				},
				"width": {
					"value": 12,
					"unit": "CENTIMETER"
				},
				"height": {
					"value": 12,
					"unit": "CENTIMETER"
				},
				"weight": {
					"value": 2,
					"unit": "KILOGRAMS"
				}
			}
		],
		"insurance": {
			"amount": "11.00",
			"currency": "PLN"
		},
		"cashOnDelivery": null,
		"labelFormat": "PDF",
		"additionalServices": [
			"ADDITIONAL_HANDLING"
		]
	}
}

Niestety przy próbie wywołania metody 
sprawdzenie statusu przesyłki
https://api.allegro.pl/shipment-management/shipments/create-commands/c545eb35-9e3c-40a3-b93e-e1b2bcaee450
otrzymuję odpowiedź

{
	"errors": [
		{
			"code": "ServiceTimeoutException",
			"message": "An error occurred",
			"details": null,
			"path": null,
			"userMessage": "Query response time exceeded. Try again."
		}
	]
}

proszę o pomoc. 

-----------

**Comment by MaciejFrackowiak** [comment]
Problem tkwi w usługach dodatkowych -  Allegro One Box nie wspiera opcji "ADDITIONAL_HANDLING".

**Comment by roberto102** [comment]
Dziękuję za szybką odpowiedź, niestety przy robieniu przesyłki bez additionalServices występuje ten sam problem
Przetestowałem dla
 "additionalServices":[ ],
i przy braku parametru.

W odpowiedzi otrzymuję prawidłowo wyglądającego jsona.
Niestety gdy odpytuję o status wysyłki ponownie widzę (504 Gateway Timeout)
(https://api.allegro.pl/shipment-management/shipments/create-commands/31945c55-599d-44b9-b84d-edf6daf9dc97)

{
	"errors": [
		{
			"code": "ServiceTimeoutException",
			"message": "An error occurred",
			"details": null,
			"path": null,
[error.json](https://github.com/allegro/allegro-api/files/13112894/error.json)
[response.json](https://github.com/allegro/allegro-api/files/13112895/response.json)
[request.json](https://github.com/allegro/allegro-api/files/13112896/request.json)

			"userMessage": "Query response time exceeded. Try again."
		}
	]
}

**Comment by MaciejFrackowiak** [comment]
Dziękuję za szczegóły - dopytuję zespołu odpowiedzialnego za usługę, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Wdrożyliśmy poprawkę, która powinna rozwiązać problem z timeout'ami. Przepraszamy za niedogodności.

**Comment by roberto102** [comment]
Dziękuję bardzo. Działa.

Robert Orzeszek

czw., 26 paź 2023 o 07:10 MaciejFrackowiak ***@***.***>
napisał(a):
