### ISSUE TITLE
Problem z nadaniem paczki Allegro odbiór w punkcie DHL

### ISSUE THREAD

**Issue by shivson1337** [allegro/allegro-api#7838]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem testowym / with the test environment

:beetle: **Opis / Description**

Podczas nadawania przesyłki Allegro odbiór w punkcie DHL otrzymujemy komunikat 

> Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.

**trace-id**: 96a7770352a815ed

**Comment by MaciejFrackowiak** [comment]
Problem wyjaśniam z zespołem, wrócę z odpowiedzią.

**Comment by shivson1337** [comment]
Zweryfikowałem dodatkowo kwestię nadania tej przesyłki z poziomu strony. Niestety tam efekt jest identyczny.

**Comment by shivson1337** [comment]
Zaryzykowaliśmy i przenieśliśmy kod na wersję produkcyjną. Tam wszystko działa prawidłowo.

Wychodzi więc na to, że problem dotyczy wyłącznie środowiska testowego.

**Comment by MaciejFrackowiak** [comment]
Cieszę się, iż operacja na produkcyjnym serwisie przeszła bez błędów. Komunikat błędu zwrócony został nam bezpośrednio przez DHL - oznacza chwilowe problemy po stronie przewoźnika bądź niepoprawny punkt doręczenia. W takim przypadku warto raz jeszcze wysłać request lub zmienić punkt doręczenia.
