### ISSUE TITLE
PILNE!   Podczas edycji aplikacji nie działa przycisk "Zapisz"

### ISSUE THREAD

**Issue by DanielCyran** [allegro/allegro-api#7839]
Witam,

Na liście moich aplikacji (https://apps.developer.allegro.pl/) istnieje aplikacja o nazwie 'swielobranzowyv2'.

Podczas edycji tej aplikacji, zaznaczam dwie dodatkowe opcje:

Zarządzanie przesyłkami
allegro:api:shipments:read (Odczyt przesyłek, etykiet i protokołów)
allegro:api:shipments:write (Zarządzanie przesyłkami)
Po zaznaczeniu tych dwóch opcji, próbuję zapisać już istniejącą aplikację. Niestety, przycisk 'Zapisz' nie działa. Nie pojawiają się żadne komunikaty błędów.
![xxxx](https://github.com/allegro/allegro-api/assets/96839460/a580d0ae-891f-42b7-962a-6f1e1ed82cf8)

**Comment by MaciejFrackowiak** [comment]
Czy Twoja przeglądarka nie ma włączonej opcji blokowania tzw. wyskakujących okienek? Po kliknięciu Zapisz powinno właśnie pojawić się dodatkowe okienko potwierdzające operację.

**Comment by DanielCyran** [comment]
@MaciejFrackowiak, nie mam żadnych blokad. Dodatkowo, mam informacje od znajomego, że ma ten sam problem. Proszę, zasymulujcie sobie moje konto i sprawdźcie.   (Możemy połączyć się na Google Meet i poprzez udostępnienie ekranu pokażę, że problem istnieje)

**Comment by mskiba03** [comment]
Podpowiem Ci jak ja to zrobiłem, bo mialem ten sam problem. JEsli masz tokeny wygenerowane dawno temu to z nimi jest problem. Nie wiem jak stare tokeny, ale z nowymi nie mialem problemu.

**Comment by jezewskiBNetrox** [comment]
> Podpowiem Ci jak ja to zrobiłem, bo mialem ten sam problem. JEsli masz tokeny wygenerowane dawno temu to z nimi jest problem. Nie wiem jak stare tokeny, ale z nowymi nie mialem problemu.

OP pisze, że mu przycisk na stronie nie działa a nie, że ma problem z tokenem.

**Comment by jezewskiBNetrox** [comment]
> Nabijasz posty? Bo nie wiem po co piszesz, skoro nic nie wnosisz do rozmowy. Mówiłem, że miałem taki sam problem, jak ccialem dodac do tokena scope od wysylam z allegro. Zaznaczyłem scope i przycisk nie działał. Ale tylko dla starszych tokenów. Dla nowszych działał bez problemu. A dla tych co nie działał, wygenerowałem nowe tokeny i również wszsytko było ok. Starsze tokeny działały bezproblemowo, tylko nie mialy dostepu do scope od wysylam z allegro.

@mskiba03 Twój post powyżej w żaden sposób nie podkreśla, że ma coś wspólnego z działaniem panelu. Następnym razem nie przekazuj skrótów myślowych i pisz konkretnie, że przycisk działa nie dajac żadnego feedbacku. A nabijać posty na GitHubie... nie, nie skomentuje tego. Szkoda gadać.

**Comment by DanielCyran** [comment]
@MaciejFrackowiak  Stara aplikacja? Proszę sprawdzić, od kiedy mam to konto... (całkiem świeże konto). Nawet jeśli to byłaby "stara aplikacja", to nie powinniście blokować możliwości zapisywania. Proszę to naprawić, ponieważ to jest błąd. Brakuje jakiejkolwiek informacji czy to jest stara aplikacja czy nowa, co jest błędem..    (podczas próby zapisania musi być jakaś informacja zwrotna)

**Comment by ecat-rg** [comment]
@MaciejFrackowiak potwierdzam występowanie problemu. Zarówno na przeglądarce Firefox jak i Chrome nie ma możliwości zapisu aplikacji, próbowałem dodać uprawnienia dotyczące zarządzania przesyłkami. Po kliknięciu w zapisz nie dzieje się kompletnie nic.

**Comment by MaciejFrackowiak** [comment]
@DanielCyran @ecat-rg Problem przekazałem do zespołu odpowiedzialnego za działanie mechanizmu. Czy podczas próby kliknięcia "Zapisz" pojawia się coś nieprawidłowego w konsoli przeglądarki?

**Comment by ecat-rg** [comment]
@MaciejFrackowiak w konsoli czysto, w Network też się nic nie dzieje.

**Comment by MaciejFrackowiak** [comment]
@ecat-rg Dzięki za info i mała prośba ode mnie - czy możesz nagrać film z otwartą zakładką Network z przeglądarki, gdy wykonujesz kolejne kroki.

**Comment by DanielCyran** [comment]
@MaciejFrackowiak  podczas odtwarzania ustaw sobie jakość wideo na 1080p  https://www.youtube.com/watch?v=qwqJZE2HIA4

**Comment by DanielCyran** [comment]
@MaciejFrackowiak jeśli chcesz więcej niż tylko wideo, to możemy się połączyć na Google Meet

**Comment by MaciejFrackowiak** [comment]
@DanielCyran Sprawdź proszę obecnie, czy masz już możliwość użycia Zapisz.

**Comment by MaciejFrackowiak** [comment]
@DanielCyran Obecnie znaleźliśmy źródło problemu i poprawiamy to per aplikacja. Docelowo oczywiście poprawka obejmie wszystkich.

@ecat-rg Proszę podaj ClientID aplikacji, dla której wystąpił u Ciebie problem.

**Comment by ecat-rg** [comment]
@MaciejFrackowiak 1dfde44a853841828fef9280f649946f

**Comment by DanielCyran** [comment]
@MaciejFrackowiak  czy dziś zostanie to naprawione na każdej aplikacji???

**Comment by MaciejFrackowiak** [comment]
@ecat-rg Już powinno być OK.

@DanielCyran Obecnie poprawiamy to ad hoc. Docelowo oczywiście przeprowadzimy masową operację.

**Comment by Loczek2x1** [comment]
@MaciejFrackowiak u mnie też nie działa, jak to możliwe że taka duża platforma allegro a nie może poradzić sobie z jednym przyciskiem....

![image](https://github.com/allegro/allegro-api/assets/149041037/7ba6f262-8319-410f-a7a3-51f50b5b35e5)

**Comment by MaciejFrackowiak** [comment]
@Loczek2x1 Podaj proszę ClientId aplikacji i problem się rozwiąże. Możemy sobie poradzić - wymaga to jednak zaangażowania pewnych zasobów, które obecnie realizują bardziej newralgiczne potrzeby i zadania.

**Comment by Loczek2x1** [comment]
nazwa konta: aurissiopl2

**Comment by DanielCyran** [comment]
@MaciejFrackowiak  proszę o rozwiązanie tego problemu masowo. Obecnie wielu użytkowników ma z tym przyciskiem problem. Tutaj nie chodzi o rozbudowanie czegoś, ale o naprawę ewidentnego błędu

**Comment by MaciejFrackowiak** [comment]
@Loczek2x1 @DanielCyran Wdrożyliśmy globalną poprawkę, zatem obecnie powinniście móc edytować aplikacje bezproblemowo.

**Comment by DanielCyran** [comment]
@MaciejFrackowiak Dziękuję. Wstępnie potwierdzam, że wdrożona globalna poprawka działa poprawnie. Przetestuję ją gruntownie i dam znać. Pozdrawiam
