### ISSUE TITLE
Postępowanie ze zdjęciami wrzuconymi przez REST api

### ISSUE THREAD

**Issue by imper86** [allegro/allegro-api#784]
Hej,

Taką mam zagwozdkę - rozumiem, że zdjęcia wrzucone na Wasze serwery są cyklicznie usuwane, jeśli nie zostaną użyte w żadnym drafcie/trwającej aukcji. Pytanie natomiast co dzieje się z tymi zdjęciami po zarchiwizowaniu aukcji? Zostają pod starymi linkami i są używane przez archiwum allegro, czy też są usuwane/przenoszone pod inne adresy?

**Comment by PawelTaberski** [comment]
Zdjęcia, które są przypisane do ofert, które przenosimy do archiwum usuwamy po pół roku, czyli po 4 miesiącach po archiwizacji oferty.
