### ISSUE TITLE
Sprawdzenie statusu utworzenia paczki zwraca błąd 504

### ISSUE THREAD

**Issue by KrystianBogiel** [allegro/allegro-api#7841]
- [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Podczas odpytywania o sprawdzenie statusu utworzenia paczki pod zasobem
https://api.allegro.pl/shipment-management/shipments/create-commands/87c520eb-51c4-4d6d-980f-05812c1b8543
otrzymuje w odpowiedzi 504:

trace-id 4b06a86c3c950e96
```
{
	"errors": [
		{
			"code": "ServiceTimeoutException",
			"message": "An error occurred",
			"details": null,
			"path": null,
			"userMessage": "Query response time exceeded. Try again."
		}
	]
}
```

**Comment by MaciejFrackowiak** [comment]
Wdrożyliśmy poprawkę, która powinna rozwiązać problem z timeout'ami. Przepraszamy za niedogodności.

**Comment by KrystianBogiel** [comment]
Potwierdzam, teraz zapytania działają prawidłowo.
