### ISSUE TITLE
Pobranie danych konta na podstawie Client_ID i Client_Secret

### ISSUE THREAD

**Issue by jakubm999** [allegro/allegro-api#7842]
Witam,
posiadam Client_ID i Client_Secret aplikacji, ale problem polega na tym, że nie mogę znaleźć konta, na którym jest zarejestrowana ta aplikacja. Czy na podstawie tych informacji istnieje możliwość wyciągnięcia chociażby loginu/emaila tego konta?

**Comment by MaciejFrackowiak** [comment]
Jeżeli konto to będzie powiązane z Twoim to uzyskasz takie informacje - napisz proszę do nas poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z danymi, które posiadasz.

**Comment by jakubm999** [comment]
Właśnie tutaj jest problem, bo jakbym wiedział, na jakim koncie może być zarejestrowana aplikacja, to bym się zalogował i sobie sprawdził. Nie da się sprawdzić tego przez jakąś metodę w API?

**Comment by MaciejFrackowiak** [comment]
Nie, ponieważ są to dane wrażliwe. Jeżeli w jakikolwiek sposób konto, którego dane posiadasz będzie powiązane z Twoim/Twoimi danymi, itp. to będziemy mogli pomóc.

**Comment by jakubm999** [comment]
Dostałem w piątek odpowiedź, że "nie posiadamy bezpośredniej informacji o połączeniu kont lecz mogą to Państwo zweryfikować po zalogowaniu się na platformę Allegro", tylko niestety w żaden sposób mi to nie pomaga :/

**Comment by MaciejFrackowiak** [comment]
Niestety, jak wspomniałem z uwagi na ochronę danych nie możemy informować do kogo należy klucz, jeżeli zgłoszenie nie jest od osoby, która jest jego właścicielem.
