### ISSUE TITLE
Przegląd cen

### ISSUE THREAD

**Issue by kamilsu** [allegro/allegro-api#7843]
Dzień dobry,
Czy jest dostęp z poziomu REST API do cen statystycznych podanych w opcji: 
Allegro ->Moje Allegro ->Sprzedaż ->Obsługa ofert ->[Przegląd cen](https://allegro.pl/moje-allegro/sprzedaz/przeglad-cen)

**Comment by MaciejFrackowiak** [comment]
Nie, ta opcja nie jest dostępna w API.
