### ISSUE TITLE
problem z nadaniem jakiejkolwiek paczki WzA

### ISSUE THREAD

**Issue by DariuszSzylko** [allegro/allegro-api#7844]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Po wykonaniu /shipment-management/shipments/create-commands
Próbuję pobrać wynik poprzez /shipment-management/shipments/create-commands/{COMMAND_ID}

Otrzymuję: 
{"errors":[{"code":"ServiceTimeoutException","message":"An error occurred","details":null,"path":null,"userMessage":"Przekroczono czas wykonania zapytania. Spróbuj ponownie."}]}

trace id przykładowy: 8dc15f7ff186f8d8

P.S. problem występuje od wczoraj - wczoraj co któryś raz się udało, dodam, że pomimo błędu potrafią tworzyć się numery listów przewozowych w zamówieniu!

**Comment by MaciejFrackowiak** [comment]
Wdrożyliśmy poprawkę, która powinna rozwiązać problem z timeout'ami. Przepraszamy za niedogodności.
