### ISSUE TITLE
Problem z Allegro One Box

### ISSUE THREAD

**Issue by Matejko1991** [allegro/allegro-api#7845]
Dzień dobry, 

przy próbie nadania przesyłki otrzymujemy następujący komunikat. Co on oznacza? Załączam trace_id. 

"trace-id" => array:1 [▼
    0 => "7915093f5c8a65c2"
  ]

array:6 [▼
  "deliveryMethodId" => "08c15d0b-9b24-4b3f-89a8-7a2b502abe55"
  "sender" => array:9 [▼
    "name" => "xxx"
    "company" => "xxx"
    "street" => "xxx"
    "streetNumber" => "xxx"
    "postalCode" => "xxx"
    "city" => "xxx"
    "countryCode" => "PL"
    "email" => "xxx"
    "phone" => "xxx"
  ]
  "receiver" => array:10 [▼
    "company" => "xxx"
    "street" => "xxx"
    "streetNumber" => ""
    "postalCode" => "xxx"
    "city" => "xxx"
    "countryCode" => "PL"
    "email" => "xxx"
    "phone" => "xxx"
    "name" => "xxx"
    "point" => "xxx"
  ]
  "packages" => array:1 [▼
    0 => array:5 [▼
      "type" => "PACKAGE"
      "weight" => array:2 [▼
        "value" => "1"
        "unit" => "KILOGRAMS"
      ]
      "length" => array:2 [▼
        "value" => 30
        "unit" => "CENTIMETER"
      ]
      "width" => array:2 [▼
        "value" => 33
        "unit" => "CENTIMETER"
      ]
      "height" => array:2 [▼
        "value" => 40
        "unit" => "CENTIMETER"
      ]
    ]
  ]
  "referenceNumber" => "ZWM 9892_2023"
  "labelFormat" => "PDF"
]
array:1 [▼
  "result" => {#3097 ▼
    +"errors": array:1 [▼
      0 => {#3098 ▼
        +"code": "ServiceTimeoutException"
        +"message": "An error occurred"
        +"details": null
        +"path": null
        +"userMessage": "Query response time exceeded. Try again."
      }
    ]
  }
]

**Comment by MaciejFrackowiak** [comment]
To problem identyczny jak w [wątku](https://github.com/allegro/allegro-api/issues/7837#issuecomment-1776828491) - weryfikujemy sprawę.

**Comment by DariuszSzylko** [comment]
@MaciejFrackowiak czy udało się coś ustalić? nie mamy możliwości generowania przesyłek WzA poprzez API, wczoraj nie działało również poprzez "Nadaj paczkę" w Allegro.pl (dziś już funkcjonuje ten sposób), jednak jest to duże utrudnienie

**Comment by Matejko1991** [comment]
@DariuszSzylko widzę, że problem podobny jak u nas. Jedynie co to możemy poprzez Allegro bezpośrednio ale jest to duże utrudnienie

**Comment by DariuszSzylko** [comment]
@Matejko1991 u nas dodatkowo generują się 3 etykiety (system próbuje 3 razy wygenerować etykietę zanim się podda), bo usterka działa tak, że przez API nie można pobrać, ale jednak generuje etykiet i ktoś kto ma dostęp do allegro musi ręcznie drukować te etykiety... masakra....

**Comment by MaciejFrackowiak** [comment]
Wdrożyliśmy poprawkę, która powinna rozwiązać problem z timeout'ami. Przepraszamy za niedogodności.
