### ISSUE TITLE
WzA - timeout przy sprawdzeniu statusu

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#7847]
Witam, mam problem, bo za każdym razem przy próbie sprawdzenia statusu utworzenia przesyłki dostaje

https://api.allegro.pl/shipment-management/shipments/create-commands/e994a39d-77e5-491a-b6d3-8afd2d95b7a2

`Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ServiceTimeoutException
                    [message] => An error occurred
                    [details] => 
                    [path] => 
                    [userMessage] => Query response time exceeded. Try again.
                )

        )

)`

command_id - e994a39d-77e5-491a-b6d3-8afd2d95b7a2

ale to nie ma wiekszego znaczenia, bo przy każdym innym jest to samo.

Dodam, ze po wdrożeniu, przez 3 dni działo bez problemu, problem pojawił się dzisiaj

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za przykład, otrzymaliśmy już podobne zgłoszenia, m.in. w #7845. Weryfikujemy sprawę.

**Comment by PrzemyslawLukanowski** [comment]
Wdrożyliśmy poprawkę, która powinna rozwiązać problem z timeout'ami. Przepraszamy za niedogodności.
