### ISSUE TITLE
OAuth(Authorization Code flow) - błąd autoryzacji(Sandbox)

### ISSUE THREAD

**Issue by dsowinski2** [allegro/allegro-api#7848]
Witam, podczas próby integracji z API Allegro natrafiłem na problem, którego nie mogę zdiagnozować.
Przekierowuje użytkownika na: https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=<client_id>&redirect_uri=<redirect_uri>
i dostaje informacje:
```
Próba otwarcia strony została zablokowana
Coś poszło nie tak. Jeżeli sytuacja się powtarza, to zgłoś ten przypadek obsłudze klienta załączając kod błędu. Pomoże nam to w szybszym rozwiązaniu Twojego problemu.

Kod błędu
6efe0b0c7abda6c0
```

redirect uri zgadza się z tym w konfiguracji aplikacji, jest to tunelowany port localhost przez ngrok

Co warto sprawdzić? Czy są gdzieś dostępne informacje o konkretnym błędzie?

**Comment by PrzemyslawLukanowski** [comment]
Z podobnym problemem zetknął się użytkownik w wątku #7269. Zwróć proszę uwagę, czy nie korzystasz z adresu tzw. “loopback”, czyli 127.x.x.x, ponieważ korzystać możesz wyłącznie z adresów domenowych, publicznych adresów IP oraz localhost. Sprawdź, czy zmiana redirect uri na inny adres rozwiąże problem.
