### ISSUE TITLE
Numer zamówienia, a numer karty płatności lub karty transakcji

### ISSUE THREAD

**Issue by mpysz** [allegro/allegro-api#785]
Pobierając zamówienie metodą GET `/order/checkout-forms` otrzymuję checkoutForm wraz z id np. 
`"id": "7ee34aa2-d11a-11e8-a81d-b97f90d62334"`

Zapisując powyższe id jako numer zamówienia w swoim systemie nie jestem w stanie odszukać tego zamówienia w panelu Allegro oraz  w Menedżerze Sprzedaży. W jaki sposób mogę zapisać w swoim systemie 

Numer karty transakcji z menedżera sprzedaży:
![Menedżer sprzedaży](https://image.ibb.co/ka1m5f/1.png)

lub numer karty płatności z panelu Allegro:
![Allegro](https://image.ibb.co/dkHR5f/2.png)
?

Chciałbym pobrać przez REST API jakiś numer, który później jednoznacznie pozwoli mi odszukać zamówienie w Menedżerze Sprzedaży lub panelu Allegro. 
Idealnie było by móc utworzyć link np. https://ms.allegro.pl/transaction/show/{orderId}

**Comment by PawelTaberski** [comment]
Zamówienia jakie pobrałeś metodą GET na zasobie /order/checkout-forms możesz powiązać z tymi znalezionymi przez front w zakładce Zamówienia po numerze płatności. Numery z MS a te z API to są dwie odrębne sprawy i nie da się ich powiązać są różne. MS korzysta z innego API niż to wystawione publicznie.

**Comment by mpysz** [comment]
Super. Sprawdziłem czy wyszukiwarka w zakładce Zamówienia będzie w stanie wyszukać po nr płatności i wyszukuje. Będę mógł nawet w swojej aplikacji skonstruować link:
`https://allegro.pl.allegrosandbox.pl/seller-orders/#!/?query={nrPłatności}`

Dzięki za szybką odpowiedź.

**Comment by neldh** [comment]
Mam podobne pytanie:

W przypadku doplat to wyszukiwanie nie działa. Owszem mogę sobie znaleźć zamowienia po id checkout forma, albo po numerze pierwszej płatności, ale w przypadku kilku doplat czasem moze byc ciezko zidentyfikować ktora jest ktora. Moglibyscie dodać do panelu chociażby wyświetlanie na szczegolach numery dopłat?

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem, w zasobie /order/checkout-forms/{checkoutForm_id} zwracamy identyfikator dopłaty więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/#06).

**Comment by neldh** [comment]
No ok. Przestudiowalem od deski do deski jakieś 15 razy, ale jak się to ma do waszego panelu to nie wiem...

Może inaczej:
1. Przypadek pierwszy:
Wchodzę na https://allegro.pl/seller-orders/#!/?query={nrPłatności} i odnajduję platność. Jestem zadowolony.
2. przypadek drugi:
Wchodzę na https://allegro.pl/seller-orders/#!/?query={nrCheckoutForma} i odnajduję platność powiązaną z tym checkout formem. jestem zadowolony.
3. przypadek trzeci:
Wchodzę na https://allegro.pl/seller-orders/#!/?query={nrDopłaty} i w tym przypadku nie mam wyników.
(nrDopłaty = surcharge.id z REST API)

Ok. To pewnie jest prawidłowe działanie, ale:
Mógłbym zrobić tak:
https://allegro.pl/seller-orders/#!/?query={nrPłatności}
lub tak:
https://allegro.pl/seller-orders/#!/?query={nrCheckoutForma}
i miałbym wyniki wraz z dopłatami.
Jednakże w takim wypadku nie mam nigdzie widocznych tych numerów dopłat, a byłoby to bardzo pomocne, bo w tej chwili panel allegro nie zezwala na wyszukiwanie po numerach dopłat (surcharge.id).

**Comment by PawelTaberski** [comment]
Tutaj zajmujemy się sprawami dotyczącymi API Allegro, zgłoś proszę swoją sugestię przez [formularz kontaktowy](https://allegro.pl/pomoc/dla-sprzedajacych), Tam również możesz zadać pytanie odnośnie MS-a. Nie korzysta on z publicznych zasobów API.

**Comment by neldh** [comment]
ok, poszło
