### ISSUE TITLE
Komunikat "Przekroczono limit 16 zdjęć" / "The limit of 16 images has been exceeded"

### ISSUE THREAD

**Issue by stalkerGH** [allegro/allegro-api#7851]
Próbuję dodać ofertę z produktem. Jedna oferta przeszła bez problemu, kolejna zostaje odrzucona z informacją o błędzie jak w tytule zgłoszenia. Zmiany pomiędzy jedną a drugą ofertą były kosmetyczne: podmiana listy zdjęć, tytułu, opisu i wewnętrznego identyfikatora (SKU). Na wszelki wypadek usunąłem z oferty jedno zdjęcie (zostaje 15), ale komunikat jest ten sam.

trace-id: 2aea70b31a5f4852

**Comment by PrzemyslawLukanowski** [comment]
Upewnij się proszę, czy w opisie oferty (`description`) nie przesyłasz dodatkowo innych adresów niż te zawarte w sekcji `images`. W naszych logach niestety nie widzimy całego body Twojego requestu, więc jeśli problem nadal będzie występować, wklej całą strukturę tutaj (z usunięciem wrażliwych danych jak token) lub jeśli nie chcesz przesyłać tych informacji publicznie, skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt) i napisz, że przesyłasz dane z związku ze zgłoszeniem #7851 na GitHubie, które należy przekazać zespołowi API.

**Comment by stalkerGH** [comment]
> Upewnij się proszę, czy w opisie oferty (`description`) nie przesyłasz dodatkowo innych adresów niż te zawarte w sekcji `images`. 

Dziękuję za podpowiedź. Rzeczywiście problem leżał w sekcji `description` - były tam dwa dodatkowe zdjęcia poza listą 16 umieszczonych wcześniej.
