### ISSUE TITLE
Offer duplicity

### ISSUE THREAD

**Issue by BarnetMichal** [allegro/allegro-api#7852]
Hello,

1, Is it possible to find out via API if the merchant already has an offer for the product? Some API endpoint that would return product offers according to product.id. I need some system to prevent duplicate product offers.

Thank you.

**Comment by PrzemyslawLukanowski** [comment]
Hello,

There is no possibility to filter offers by `product.id`, but if you use [external.id](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#signature) field with the same value for each product, you can use such filter, for example, `GET /sale/offers?external.id={external.id}`.

**Comment by BarnetMichal** [comment]
Would it be possible to add a filter for product.id to the API? Often we solve that the customer switches from one integrator to another or that he creates some offers manually and without the possibility to find out if the product already has offers, there will be duplicates.  I know about the external.id filter but it can be filled with any value if the offer was created by someone other than our system.

**Comment by PrzemyslawLukanowski** [comment]
You can add such a suggestion in the [Discussion](https://github.com/allegro/allegro-api/discussions) tab. This is the place where we collect all of the API development suggestions.

**Comment by BarnetMichal** [comment]
@PrzemyslawLukanowski I try endpoint sale/product-offers/id and the productSet array is returned with the products but the 'EAN (GTIN)' parameter is not filled. I only get it if I call the query for a specific product sale/products/id. Is there any way to get the 'EAN (GTIN)' of a product when querying a specific offer? 

I know the GTIN of the product and I would like to get my offers for this product, what is the best way to get this information? Thank you

**Comment by PrzemyslawLukanowski** [comment]
EAN should be returned, below you can check my sample offer. Could you send me a trace-id where we didn't return this parameter?

```
{
    "name": "32'' TV LED HD UE32K4100AWXXH",
    "productSet": [
        {
            "product": {
                "id": "61df075d-961b-45a8-9664-f5c5fb3a126d",
                "publication": {
                    "status": "LISTED"
                },
                "parameters": [
                    {
                        "id": "213102",
                        "name": "Wersja",
                        "values": [
                            "cyfrowa"
                        ],
                        "valuesIds": [
                            "213102_259418"
                        ],
                        "rangeValue": null
                    },
                    {
                        "id": "213570",
                        "name": "Nominał",
                        "values": [
                            "25 zł"
                        ],
                        "valuesIds": [
                            "213570_261258"
                        ],
                        "rangeValue": null
                    },
                    {
                        "id": "249519",
                        "name": "Nazwa usługi",
                        "values": [
                            "Google Play"
                        ],
                        "valuesIds": [
                            "249519_1647945"
                        ],
                        "rangeValue": null
                    },
                    {
                        "id": "225693",
                        "name": "EAN (GTIN)",
                        "values": [
                            "4260505536473"
                        ],
                        "valuesIds": null,
                        "rangeValue": null
                    }
                ]
            },
            "quantity": {
                "value": 1
            }
        }
    ],
...
}
```

**Comment by BarnetMichal** [comment]
Sure, my sandbox account michal.b@koongo.com, endpoint sale/product-offers/7726433765
![image](https://github.com/allegro/allegro-api/assets/26611033/47203cc4-9aec-45c2-9555-b0d110725f47)

**Comment by PrzemyslawLukanowski** [comment]
Thank you for this example, I forwarded it to our team responsible for this endpoint. Could you please try to list another offer once again? I'm asking cause I was not able to recreate this error, here's my response to the GET method:

```
{
    "name": "Hummingbird t-shirt test neco",
    "productSet": [
        {
            "product": {
                "id": "babe50d2-2a2c-4178-861d-6fd5cf36ba0d",
                "publication": {
                    "status": "LISTED"
                },
                "parameters": [
                    {
                        "id": "223545",
                        "name": "Tytuł",
                        "values": [
                            "test neco neco"
                        ],
                        "valuesIds": null,
                        "rangeValue": null
                    },
                    {
                        "id": "225693",
                        "name": "EAN (GTIN)",
                        "values": [
                            "4066754781790"
                        ],
                        "valuesIds": null,
                        "rangeValue": null
                    }
                ]
            },
            "quantity": {
                "value": 1
            }
        }
    ],...
```

**Comment by BarnetMichal** [comment]
Okay, I created a new one and now see the EAN param for it, so can I rely on the EAN to always return?
Btw I found the trace-id for which you asked before, it`s b21c45fce65ed069, sorry I didn`t know that it was in the response header.

**Comment by PrzemyslawLukanowski** [comment]
Yes, EAN should always be returned in response as part of product parameters. Thank you for the trace-id, it seems it was a temporary issue on our side.
