### ISSUE TITLE
shipment-management/delivery-services

### ISSUE THREAD

**Issue by Eryk1997** [allegro/allegro-api#7854]
Chciałbym pobierać dostępne formy i je mapować u siebie. 
A więc pobieram dostępne formy poprzez: https://api.allegro.pl.allegrosandbox.pl/shipment-management/delivery-services.
Podczas kupowania przedmiotu mam dostępną formę Kurier DPD 
![Zrzut ekranu 2023-10-25 o 12 34 58](https://github.com/allegro/allegro-api/assets/33696058/36721c21-fb96-40b5-9d48-3f35084adafb)

jak pobieram to zamówienie to występują informację: 
"method": {
                    "id": "c3066682-97a3-42fe-9eb5-9bb2978cf293",
                    "name": "Kurier DPD"
                },
                
Natomiast endpoint: shipment-management/delivery-services  nie zwraca mi takiego id -> c3066682-97a3-42fe-9eb5-9bb2978cf293

Czy ja coś robię źle?

**Comment by MaciejFrackowiak** [comment]
Nie, nie robisz nic źle. Nie wszystkie metody dostawy dostępne w ramach cenników dostaw są dostępne jako metody wysyłek w ramach Wysyłam z Allegro. Korzystając z [GET /shipment-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getDeliveryServices) znajdziesz kilka metod dostaw obsługiwanych przez DPD, a jednocześnie realizowanych w ramach WzA.

**Comment by Eryk1997** [comment]
A czy jeśli dodam -> Umowy wlasne wysyłam z allegro to pojawią się te dodatkowe metody dostawy pod  [GET /shipment-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getDeliveryServices) ? 
![Zrzut ekranu 2023-10-25 o 12 15 26](https://github.com/allegro/allegro-api/assets/33696058/66b27f80-763f-4bb8-b7b4-25cfbc06920f)

**Comment by MaciejFrackowiak** [comment]
Tak, wówczas będą one również dostępne. Clue to jednak przypisanie właściwych metod dostaw do ofert, które będa pokrywały się z tymi z WzA.

**Comment by lukasz-ideaware** [comment]
Podepnę się pod pytanie. 
W jaki sposób tworząc przesyłkę przez WzA łączy ona automatycznie przesyłkę z zamówieniem (sandbox)? Jedyne co przekazuję przy tworzeniu przesyłki to wartość i dane odbiorcy. Zastanawia mnie, czy ten mechanizm zadziała zawsze i połączy paczkę z poprawnym zamówieniem.

**Comment by MaciejFrackowiak** [comment]
@lukasz-ideaware Kluczowy jest tu adres zahashowany adres email zamówienia - to w nim kryją się szczegóły, w tym m.in. metoda dostawy.
