### ISSUE TITLE
Kombinacja kodu pocztowego nadawcy i kraju jest niepoprawna

### ISSUE THREAD

**Issue by KrystianBogiel** [allegro/allegro-api#7855]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy próbie utworzenia shipment na kod pocztowy "8‌5-862" sprawdzenie statusu tworzenia przesyłki zwraca status ERROR:
```
{
	"commandId": "dc8e5b96-2e75-4967-a0a6-ad1f1e25e043",
	"status": "ERROR",
	"errors": [
		{
			"code": "BAD_REQUEST",
			"message": "sender combination of postal code and country is invalid",
			"details": null,
			"path": "sender",
			"userMessage": "Kombinacja kodu pocztowego nadawcy i kraju jest niepoprawna"
		}
	],
	"shipmentId": null
}
```

Operacja zakończy się powodzeniem kiedy zamiast wskazanego adresu użyje np. Warszawskiego 00-030.

trace-id /shipment-management/shipments/create-commands cbfeb889eb6260cf
trace-id /shipment-management/shipments/create-commands/{commandId} aec57e449ad9ee53

![image](https://github.com/allegro/allegro-api/assets/70366466/81184658-52f6-43f9-aa3f-12a5ce8902cb)

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję tę sytuację, na tę chwilę wygląda to tak, że kod nie jest dodany w naszej bazie. Wrócę z informacją.

**Comment by KrystianBogiel** [comment]
Teraz odpowiedź zawiera informacje o niedostępnym API, trace-id 654510dc6a0da7e7
```
{
	"commandId": "bd249720-8721-4b70-9451-b30185e79300",
	"status": "ERROR",
	"errors": [
		{
			"code": "CARRIER_API_UNAVAILABLE",
			"message": "Carrier's API is temporarily unavailable. Try again later.",
			"details": "Carrier Api is temporary unavailable - try again later or report problem",
			"path": null,
			"userMessage": "API przewoźnika jest tymczasowo niedostępne. Ponów próbę później."
		}
	],
	"shipmentId": null
}
```

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku rzeczywiście miały miejsce chwilowe problemy techniczne po stronie przewoźnika.

**Comment by KrystianBogiel** [comment]
Komunikat o niedostępnym API na wcześniej utworzonym zapytaniu z trace-id 654510dc6a0da7e7 nadal występuje. 
Przy stworzeniu nowego shipmentu powrócił tytułowy błąd z kombinacją kodu pocztowego i kraju, trace-id 5dc91cd026ee562b.

**Comment by PrzemyslawLukanowski** [comment]
Tak, ponieważ odpytujesz o status tej samej komendy bd249720-8721-4b70-9451-b30185e79300 - w tym przypadku komunikat już się nie zmieni. Co do błędu z kombinacją kodu - przekazałem problem do odpowiedniego zespołu i jak tylko zostanie to naprawione, wrócę z informacją.
