### ISSUE TITLE
Prowizja dla kategorii

### ISSUE THREAD

**Issue by Mihalis76** [allegro/allegro-api#7856]
Dzień dobry.

Czy jest możliwość pobrania wielkości prowizji dla danej kategorii ?

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, możesz skorzystać z kalkulatora opłat - [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST), dzięki któremu sprawdzisz, jakie opłaty pobieramy dla konkretnej oferty. Jest to jedyny zasób, w którym zwracamy informację o prowizji od sprzedaży w danej kategorii. Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-sprawdzic-oplaty-nn9DOL5PASX#kliknij-aby-zobaczyc-response).
