### ISSUE TITLE
Przesyłanie pliku - faktury

### ISSUE THREAD

**Issue by artbski** [allegro/allegro-api#7857]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dobry wieczór.

podczas wywoływanie endpointa : /order/checkout-forms/f7134c00-737c-11ee-9b9a-2b38006646ea/invoices/f023a16a-48ba-49f5-8ab2-db892ed42cd5/file
otrzymuję response'a : 
"errors": [
        {
            "code": "INTERNAL_SERVER_ERROR",
            "message": "Internal server error.",
            "details": null,
            "path": null,
            "userMessage": "Internal server error. Try again in a few minutes."
        }
    ]

I tak już od "few minutes" to trwa ...

**Comment by PrzemyslawLukanowski** [comment]
Otrzymałem informację, że był to czasowy problem z usługą, aktualnie wszystko powinno działać prawidłowo.
