### ISSUE TITLE
Allegro sandbox - aktywacja konta testowego

### ISSUE THREAD

**Issue by bartosz987654** [allegro/allegro-api#7858]
Dzień dobry, 
Czy istnieje możliwość samodzielnej aktywacji sprzedaży w platformie allegro sandbox?
Jeżeli nie to proszę o aktywację konta: Client:106175457

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, aktywowałem Twoje konto. Jeśli jednak chcesz wystawiać i zarządzać ofertami za pomocą API, musisz posiadać konto firmowe. Możesz zmienić profil aktualnego konta lub założyć nowe.

**Comment by bartosz987654** [comment]
Dzień dobry, proszę o ponowną aktywacje konta - typ został zmieniony na konto firmowe w celu wystawiania i zarządzania ofertami za pomocą API.

**Comment by PrzemyslawLukanowski** [comment]
Uzupełnij proszę jeszcze [Ustawienia wypłat](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat) - numer konta może być oczywiście fikcyjny, a sam przelew weryfikacyjny odbywa się za pomocą symulatora płatności.

**Comment by bartosz987654** [comment]
Rozumiem, że wybrana metoda płatności to ma być przelew standardowy? Kiedy następuje przekierowanie do symulatora płatności?

**Comment by PrzemyslawLukanowski** [comment]
Czy masz do wyboru opcję innego przelewu, elektronicznego? Jeśli tak spróbuj wybrać najpierw ją. Widzę, że Twoje konto pojawiło się już w naszym systemie, ale brakuje właśnie potwierdzonego numeru konta.

**Comment by bartosz987654** [comment]
Udało mi się potwierdzić numer konta, czy to już wszystko co muszę wykonać do aktywacji?

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, dziękuję, właśnie aktywowałem konto.
