### ISSUE TITLE
Błąd weryfikacji produktów 

### ISSUE THREAD

**Issue by Jaanioo** [allegro/allegro-api#7859]
Mamy problem z takimi błędami: 

trace-id: 49a39a9a37bc2419

ConstraintViolationException.DependencyValidator
Parametr zależny Rozmiar (128610) nie może przyjąć wartości [44], gdy parametr Rodzaj (215534) ma wartości [dół].

Od czego zależy ten błąd? Co zmienić aby produkt mógł zostać dodany?

**Comment by PrzemyslawLukanowski** [comment]
Parametr "Rozmiar" może mieć uzupełnioną wartość, jeśli w parametrze "Rodzaj" wybrano "komplet". W tej sytuacji widnieje tam "doł", zatem wystarczy uzupełniony parametr "Rozmiar majtek". Możecie usunąć parametr "Rozmiar" (128610) z oferty i komunikat błędu nie powinien wystąpić.

Wygląda na to, że parametr jest nadmiarowo uzupełniony w niektórych produktach, co skutkuje takim właśnie komunikatem błędu. Zgłaszam ten problem dalej do zespołu, który zajmuje się danymi produktów.

**Comment by Jaanioo** [comment]
Jak dobrze rozumiem w tego typu produktach nie powinno być wcale parametru "Rozmiar" tak?

**Comment by PrzemyslawLukanowski** [comment]
Tak, wynika to z zależności parametrów, np. wspomniany parametr "Rozmiar" będzie widoczny na stronie, tylko, gdy w "Rodzaj" wybierzesz "Komplet":

```
            "id": "128610",
            "name": "Rozmiar",
...
            "displayedIf": {
                "parametersWithValue": [
                    {
                        "id": "215534",  -- id parametru "Rodzaj"
                        "oneOfValueIds": [
                            "215534_270230" -- id wartości "Komplet"
                        ]
                    }
                ],...
            },
```
Natomiast w słowniku dostępnych wartości, w polu `dependsOnValueIds`, zwracamy informację o wartości parametru, która umożliwia wybór danej wartości ze słownika, np. w przypadku wartości w parametrze "Rozmiar" zawsze wskazujemy `215534_270230` czyli "komplet", w "rozmiar majtek" tą wartością jest `215534_270226` czyli "doł".

**Comment by Jaanioo** [comment]
Okej dziękuję za odpowiedź
