### ISSUE TITLE
[WebAPI] Jak uzyskac ApiKey dla aplikacji nie mającej URL powrotu

### ISSUE THREAD

**Issue by LBaraniak** [allegro/allegro-api#786]
Dzień dobry,
mam mały problem z uzyskaniem ApiKey do mojego mini skryptu w WebAPI/SOAP. Jest on umieszczony na serwerze i pod niego podpięty mam CRON który raz dziennie po prostu coś wykonuje. I teraz chce podpiąć ten skrypt (kopie) pod inne konto. Chciałem jak zawsze uzyskać ApiKey poprzez panel użytkownika na allegro.pl ale przenosi teraz na apps.developer.allegro.pl gdzie muszę podać Adresy URI do przekierowania którego nie mam. Czy jest możliwość uzyskać ApiKey w podobny sposób jak przed połączeniem generowania kluczy dostępowych? Czy może wcześniej tez było przy WebAPI podawanie URl do przekierowania, a ja po prostu nie ogarnąłem tego?

z góry dzięki za pomoc i wyrozumiałość jeśli problem jest trywialny ;)

**Comment by PawelTaberski** [comment]
Dokładnie tak, ale jeśli w przyszłości będziesz chciał korzystać z REST API to warto podać tam jakiś rzeczywisty adres. Raz podanych danych nie można zmienić, więc będziesz musiał wtedy zarejestrować nową aplikację, aby dostać nowe dane dostępowe.

**Comment by LBaraniak** [comment]
Super, Dziękuję Ci bardzo za pomoc!
