### ISSUE TITLE
Wymiana klucza dostępu API

### ISSUE THREAD

**Issue by terabajt** [allegro/allegro-api#7860]
Dzień dobry. 
Próbuję pobrać autoryzację do allegro API ale mam błąd wymiany klucza. Czy mogę prosić o pomoc? Czy może po prostu nie mam odpowiedniego konta, żeby dostać uprawnienia? 
Moja aplikacja: https://snow-wiggly-aftermath.glitch.me/ moje client ID: 2b04faa0f4424dda911b7be77cf4c4f1

**Comment by MaciejFrackowiak** [comment]
Twoja aplikacja jest prawidłowo zarejestrowana i nie widzę jakichkolwiek przeszkód, abyś uzyskał dla niej pełną autoryzację. Dokonałeś także zmian w zakresie scope - oznacza to, że musisz pobrać nowy token, aby zmienione scope zostały uwzględnione.

**Comment by terabajt** [comment]
Działa, dzięki.
