### ISSUE TITLE
POST /shipment-management/shipments/cancel-commands

### ISSUE THREAD

**Issue by Swistu93** [allegro/allegro-api#7861]
Dzień dobry,

Czy skorzystanie z endpointu pozwalającego na anulowanie przesyłki, spowoduje też anulowanie przesyłki w systemie partnera logistycznego?

[POST /shipment-management/shipments/cancel-commands](https://developer.allegro.pl/documentation/#operation/cancelShipment)

**Comment by MaciejFrackowiak** [comment]
Tak, komenda ta anuluje zlecenie u dostawcy usługi przewozu (wyjątek - nie możesz anulować paczki odebranej przez kuriera lub nadanej w paczkomacie.)

**Comment by Swistu93** [comment]
Dziękuję za pomoc :)

**Comment by Swistu93** [comment]
Urodził się nam sidecase, mianowicie zdarza się, że nadajemy przesyłkę poprzez API firmy kurierskiej, podając adres email klienta ten "anonimizowany" przez Allegro. Ta przesyłka z automatu pojawia się w zamówieniu klienta Allegro, dostaje smart'a jeżeli oferta się łapała itd. - Chcemy ją anulować, by nie była widoczna w Allegro, oraz systemie kuriera.

1) Czy jest możliwe usunięcie jej za pośrednictwem metody **/shipment-management/shipments/cancel-commands** z API allegro?
2) Jeżeli tak, to czy zniknie też z systemu kuriera? Czy trzeba wykonać drugi request już w systemie kurierskim?
3) Czy gdybyśmy skorzystali z API firmy kurierskiej w celu jej cancelowania, to czy automatycznie zostanie "odpięta" od zamówienia klienta w Allegro? 
4) Czy trzeba wtedy skorzystać z dwóch API - Allegro, oraz firmy kurierskiej by wyczyścić zamówienie z przesyłki, która nie była nadana przez API Allegro?

**Comment by MaciejFrackowiak** [comment]
Nie, zasoby z Allegro API anulują wyłącznie przesyłki zamówione przez Wysyłam z Allegro. W zasobach API Allegro nie mamy zasobu umożliwiającego usuwanie dodanych do zamówienia numerów przesyłek.
