### ISSUE TITLE
"Allegro was unable to find an exact match" response

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#7862]
Hello, 

I have a question regarding a product upload via API. When there is more then one product card with the same GTIN we are not able to connect our offer to the existing product card. We simply get a response via API "Allegro was unable to find an exact match". Is there a way how we can pick one of the already existing product cards via API? 

Here are two example products: 9007371220434 and 9007371157235
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/f63d43e5-e59f-4799-99c2-1dbda161d5d5)
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/5f79eec9-3798-4b63-9e68-97e0e7a1ab71)

Thank you in advance for your help!

All the best, 

Dominika

**Comment by PrzemyslawLukanowski** [comment]
Yes, instead of providing GTIN in the request, you need to pass product.id, for example:

```
{
    "productSet": [{
        "product": {
            "id": "d26b023c-d52c-44f9-b61a-321eb202792b" ...
```

Product IDs can be retrieved via GET /sale/products?phrase= {GTIN}&mode=GTIN, e.g. GET /sale/products?phrase= 9007371220434&mode=GTIN
