### ISSUE TITLE
How to recognize if error is in our data or on Allegro

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#7863]
Hi all, 

I have a question regarding responses that we get via API. When we try to upload products from our app to Allegro via API and there are some problems in the data, we get an error message. Right now our app only support creating an offer to already existing product card. But when we get the response, we have to know if the problem is with our data or with the data in the already existing product card that somebody else created. Is it possible to somehow differentiate between these two cases? 

Some examples: 
In this case you can see that the problem is indeed with our data since the prices is 303,20: 
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/9902aad8-4ed8-46eb-bdbf-f666429a2355)

But this error message is not about our data as there is not the special characters included as you can see: 
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/e63456a6-b786-4ee3-8d9f-c261441fc11b)

But it is in this product card to which we tried to connect it to: 
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/5e674960-4ad1-4726-bef5-ab945ec9b993)

For us it is important to know if there is a problem in the data of our customers or if the problem is with the already existing product card that was created by another user. We need it so that we can give clear instructions to our customers about what is going on and what should they do.

Thank you in advance for your help! 

All the best, 

Dominika

**Comment by PrzemyslawLukanowski** [comment]
You can rely on the `errors.path` field, which returns information about the specific section with invalid information. For example:

- if there is invalid information in the product parameters section, we will return:

```
    "errors": [
        {
            "code": "DictionaryParameterValueNotFound",
            "message": "Unprocessable Entity",
            "details": null,
            "path": "productSet[0].product.parameters",
            "userMessage": "An incorrect value `pudełkowsa` has been entered for parameter `Wersja gry`."
        }
    ]
```

- and if something is wrong on the offer level, we will return "path" without "product" included, e.g.:

```
    "errors": [
        {
            "code": "UnsupportedLanguageException",
            "message": "Unprocessable Entity",
            "details": null,
            "path": "language",
            "userMessage": "Unsupported language provided. Supported languages: en-US, pl-PL, uk-UA, cs-CZ, sk-SK."
        }
    ]
```
