### ISSUE TITLE
Próba wystawiania ofert i edycji ofert dla kont zablokowanych

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#7865]
Czy zmieniły się zasady wysyłania odpowiedzi podczas próby utworzenia nowej oferty lub zmiany istniejącej dla zablokowanego konta? Do tej pory nie dostawaliśmy HTTP 200/201/202 a teraz np. podczas wywołania POST /sale/product-offers dostajemy w odpowiedzi HTTP 202. A dopiero podczas sprawdzenia statusu wykonania operacji (link z headera location) otrzymujemy informację, że konto jest zablokowane.

trace-id: aa854238ffbb1bf9
trace-id: 4a7eda944b8626d6

Wydaje się, że taki HTTP 202 wprowadza w błąd i nie powinniśmy dostawać takiej odpowiedzi.

A na edycję oferty dla kont zablokowanych dostajemy HTTP 200.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że nastąpiła taka zmiana. Status konta walidowany jest w momencie aktywacji w oferty, zatem jeśli przez zasób /sale/product-offers ustawicie status "INACTIVE", to w odpowiedzi otrzymacie status 201 Created. W przypadku próby wystawienia aktywnej oferty, potrzebujemy więcej czasu na walidację, zatem operacja zostaje wykonana asynchronicznie, stąd status 202 - nie należy tego traktować jako błąd, ponieważ ostateczny status wykonania zadania zwrócimy w dalszym kroku. 

> A na edycję oferty dla kont zablokowanych dostajemy HTTP 200.

To prawidłowa odpowiedź, ponieważ nie blokujemy edycji ofert.
