### ISSUE TITLE
Ponownie problem z przekroczeniem liczby draftów

### ISSUE THREAD

**Issue by ecat-rg** [allegro/allegro-api#7866]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

Po kilku miesiącach wrócił problem z komunikatem o przekroczonej liczbie draftów, jak tutaj:
https://github.com/allegro/allegro-api/issues/6773

Podsyłam trace-id do sprawdzenia:
cafeb8ef96508fd4

**Comment by PrzemyslawLukanowski** [comment]
Poprawiliśmy licznik draftów, problem nie powinien występować.
