### ISSUE TITLE
403 POST: /messaging/messages

### ISSUE THREAD

**Issue by andreasgylche** [allegro/allegro-api#7867]
Hi all,

I have a question regarding the post endpoint /messaging/messages. When I try to make a request to the endpoint I get a 403 response back with a user message of: "No access to the specified resource". See image below.

![image](https://github.com/allegro/allegro-api/assets/55092864/0d27552d-c32e-4236-87ca-c7b23fbfc7c5)

I have double checked the authentication multiple times and it looks right to my eyes. What is wierd is that I have no issues making requests to other Allegro api endpoints. I have taken a code snippet from postman and posted it below, in hopes of someone can see the mistake.

`
curl --location 'https://api.allegro.pl/messaging/messages' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer {token}' \
--data '{
 "recipient": {
    "login": "some_username"
 },
 "text": "Test",
 }'
`

Or is this endpoint just not accessable to users?

**Comment by PrzemyslawLukanowski** [comment]
It seems that you don't have the required scope: allegro:api:messaging:

<img width="367" alt="Zrzut ekranu 2023-10-27 o 11 03 16" src="https://github.com/allegro/allegro-api/assets/51473661/273f536d-b068-4759-aeec-cd416d213892">
 
Please set it on the https://apps.developer.allegro.pl/ and generate new tokens, so they will have this scope included.

**Comment by andreasgylche** [comment]
That was the issue. Thank you for the quick support!
