### ISSUE TITLE
ConstraintViolationException.LanguageRequired

### ISSUE THREAD

**Issue by Axlii50** [allegro/allegro-api#7868]
{"id":null,"name":"Wyzwolenie. Deir I. Broń psychotroniczna","category":{"id":"79193"},"images":[{"url":"https://a.allegroimg.com/original/1164d9/f347e06140e0aad8d042434e9d22"}],"description":{"sections":[{"items":[{"content":null,"url":"https://a.allegroimg.com/original/1164d9/f347e06140e0aad8d042434e9d22","type":"IMAGE"},{"content":"<h1>WYZWOLENIE. DEIR I. BROŃ PSYCHOTRONICZNA</h1>","url":null,"type":"TEXT"}]}]},"parameters":[**{"id":"2868","values":["polski"],"valuesIds":["2868_1"],"options":null}**,{"id":"17448","values":["0.24"],"valuesIds":null,"options":null},{"id":"75","values":null,"valuesIds":["75_1"],"options":null},{"id":"223545","values":["Wyzwolenie. Deir I. Broń psychotroniczna"],"valuesIds":null,"options":null},{"id":"223489","values":["Wereszczagin Dimitri"],"valuesIds":null,"options":null},{"id":"223541","values":null,"valuesIds":["223541_1646610"],"options":null},{"id":"223493","values":[""],"valuesIds":null,"options":null},{"id":"223341","values":["1"],"valuesIds":null,"options":null},{"id":"223333","values":["145"],"valuesIds":null,"options":null},{"id":"223329","values":["205"],"valuesIds":null,"options":null},{"id":"245669","values":["2010003432980"],"valuesIds":null,"options":null}]}

14:52:45:268	{"errors":[{"code":"ConstraintViolationException.LanguageRequired","message":"An error has occurred","details":null,"path":"language","userMessage":"Brak lub niepoprawna wartość w polu language."}]}

Dzień dobry
przesyłam strukture jaką wysyłam by stworzyc produkt na allegro oraz odpowiedz którą dostaje na allegro 
Zaznaczyłem tez ze parametr "język" jest podawany

**Comment by Axlii50** [comment]
Dzien dobry, czy moge liczyc na jakas pomoc w tej kwesti poniewaz od wczoraj dalej brak odpowiedzi

**Comment by MaciejFrackowiak** [comment]
Niestety nie widzę Twojego pełnego requestu, ale komunikat błędu sugeruje, że w polu "[language](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct)" (które jest obowiązkowe) podałeś nieprawidłową wartość lub w ogóle nie uzupełniłeś wartości tego pola.

**Comment by Axlii50** [comment]
Wyzej wyslalem pelny request wraz z zaznaczeniem parametru language

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swojego wywołania.

**Comment by Axlii50** [comment]
Ten request zostal wykonany 3 dni temu, cala zawartosc jest przedstawiona w pierwszej wiadomosci. Content responsa tez jest zawarty w bazowej wiadomości

**Comment by Axlii50** [comment]
Id parametru oraz id odpowiedzialne za jezyk wyciagnalem z innej oferty wiec id wedlug tego rozumowania powinny byc takie same

**Comment by MaciejFrackowiak** [comment]
Nie, nie jest to tożsame. Pole "language" w requeście odpowiada za język zgłaszanej propozycji produktu. Ty natomiast cały czas odnosisz się do języka jako parametru danego produktu. Spójrz proszę raz jeszcze na strukturę [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct).

**Comment by Axlii50** [comment]
Rzeczywiście to była kwestia tego, trochę żle najwidoczniej rozumiałem błąd + trochę mam wrażenie ze zle nakierowuję błąd. Dziękuje bardzo za pomoc, Miłego dnia :3

**Comment by Axlii50** [comment]
Jeszcze mam pytanie odnośnie podawanej wartosci w parametrze
{"errors":[{"code":"ParameterException.ParameterIsNotValueException","message":"An error has occurred","details":null,"path":"parameters","userMessage":"Parametr 2868 nie jest parametrem stringowym."}]}
Dostaje taki komunikat 

a wartość podaje tak 
![image](https://github.com/allegro/allegro-api/assets/34549741/c28ffe93-cc3e-4012-a481-e036f3c7b7e2)
{"id":"2868","values":["2868_1"],"options":null}
w jaki sposób powinno to wyglądać?

**Comment by Axlii50** [comment]
Zawartość
"{"id":null,"name":"Wyzwolenie. Deir I. Broń psychotroniczna","category":{"id":"79193"},"images":[{"url":"https://a.allegroimg.com/original/11551d/e0509a904d9f9288945d849ec0cf"}],"description":{"sections":[{"items":[{"content":null,"url":"https://a.allegroimg.com/original/11551d/e0509a904d9f9288945d849ec0cf","type":"IMAGE"},{"content":"a","url":null,"type":"TEXT"}]}]},"parameters":[{"id":"2868","values":["2868_1"],"valuesIds":null,"options":null},{"id":"17448","values":["0.24"],"valuesIds":null,"options":null},{"id":"75","values":null,"valuesIds":["75_1"],"options":null},{"id":"223545","values":["Wyzwolenie. Deir I. Broń psychotroniczna"],"valuesIds":null,"options":null},{"id":"223489","values":["Wereszczagin Dimitri"],"valuesIds":null,"options":null},{"id":"223541","values":null,"valuesIds":["223541_1646610"],"options":null},{"id":"223493","values":[""],"valuesIds":null,"options":null},{"id":"223341","values":["1"],"valuesIds":null,"options":null},{"id":"223333","values":["145"],"valuesIds":null,"options":null},{"id":"223329","values":["205"],"valuesIds":null,"options":null},{"id":"245669","values":["2010003432980"],"valuesIds":null,"options":null}],"language":"pl-PL"}
"

**Comment by MaciejFrackowiak** [comment]
Prawidłowa strukrura dla wartości ze słownika:
```
{
            "id": "2868",
            "valuesIds": [
                "2868_1"
            ],
            "values": [],
            "rangeValue": null
        }
```

**Comment by Axlii50** [comment]
Okey, dziekuje bardzo za pomoc 👍
