### ISSUE TITLE
Two same error messages

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#7869]
Hi all, 

we noticed that for some offers we are getting twice almost the same response:

ConstraintViolationException.CurrencyForPublicationCountry - This currency is not supported in the offer's country of listing.
VALIDATION_FAILED - Currency is incorrect for the specified market.

![obrazek](https://github.com/allegro/allegro-api/assets/147524238/dddf737b-fb3e-4b27-a5c8-892e8d36dc44)

Would it be possible to have only one of these for currency? :) So that we do not have to show it twice to our customers. 

Thank you in advance for looking into it! 

All the best, 

Dominika

**Comment by MaciejFrackowiak** [comment]
Please, give me a trace-id of your requests.

**Comment by dominikahr** [comment]
The trace ID is: d7c90a42d7230b68

![Clipboard - October 30, 2023 9 17 AM](https://github.com/allegro/allegro-api/assets/147524238/c7902aaa-14dd-4941-be85-04a200653ec9)

**Comment by MaciejFrackowiak** [comment]
The base marketplace for your account is PL, so you can list offers only in PLN as a base marketplace. If you want sell in CZK, you have to add additionalMarketplaces structure to your request - please, check [our tutorial](https://developer.allegro.pl/tutorials/listing-and-managing-offers-on-foreign-marketplaces-7GndGjeAATn#displaying-offers-on-additional-marketplaces).

**Comment by dominikahr** [comment]
Yes, we know. But our questions is if there is really a need for 2 error messages that are basically saying the same thing: 
ConstraintViolationException.CurrencyForPublicationCountry - This currency is not supported in the offer's country of listing.
VALIDATION_FAILED - Currency is incorrect for the specified market.

**Comment by MaciejFrackowiak** [comment]
Yes, they are needed because they relate to two different fields:

1) first is responsible for checking country of listing and its currency;
2) second is responsible for verifying currency in the price field.
