### ISSUE TITLE
[sandbox] Problem z opłaceniem zamówień z rozpoczętą płatnością

### ISSUE THREAD

**Issue by mapsi-fixi** [allegro/allegro-api#787]
Na sandboxie nie jest możliwe opłacenie oferty która otrzymała status płatności cancelled. Przy ponowniej próbie opłacenia nie pojawia się symulator płatności. Co więcej nie da się również dokończyć zamówienia poprzez zmianę płatności na płatne przy odbiorze.

**Comment by PawelTaberski** [comment]
Prosiłbym o podesłanie zrzutów z tym błędem, sprawę zgłoszę jako błąd.

**Comment by mapsi-fixi** [comment]
Błąd występuje za każdym razem, więc jest prosty do odtworzenia:
1. Zakup produktu
2. Płatnośc z góry
3. status płatności -> cancelled
4. Próba ponownego opłacenia zamównia -> brak symulatora płatności, zamówienie jest zablokowane. Odblokować można je tylko poprzez opłacenie z innymi.

**Comment by PawelTaberski** [comment]
Rozumiem, rzeczywiście jest jakiś problem na środowisku testowym. Sprawę przekazałem do odpowiedniego zespołu, proszę o cierpliwość.
