### ISSUE TITLE
Serwer nie jest w stanie zrealizować zapytania. Spróbuj ponownie za kilka minut.

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#7870]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

Co chwilę mamy 503 na zasobie `PATCH /sale/product-offers/{offerId}`

**Comment by PrzemyslawLukanowski** [comment]
Nie odnotowaliśmy zwiększonej liczby błędów tego dnia. Czy możesz przesłać przykładowe trace-id? Zweryfikujemy przyczynę po naszej stronie.
