### ISSUE TITLE
Nieprawidłowe adresy miast/ulic podczas nadawania przesyłek

### ISSUE THREAD

**Issue by JamesFordV3** [allegro/allegro-api#7871]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dobry,

Pytanko mam. A właściwie 2 pytanka.

1. Jak to jest że kiedy klienci kupują na allegro i wypełniają te wasze formularze "Dane dostawy" to bez problemu akceptujecie chyba wszystko co tam podają, a kiedy przychodzi do nadania przesyłki na podany adres przez klienta to zwracacie błędy typu:

- nieprawidłowa ulica,
- błędne miasto
- nieprawidłowy kod pocztowy
- nazwa firmoy odbiory jest za długa
itp.

Chodzi mi o to że akceptujecie poprawne(według was) adressy dostawy, a gdy przychodzi nadać przesyłkę to są one błędne (według was).

Poniższe przykładowe "nieprawidłowe" dane pochodzą z obiektu **order.deliver.address**:

`
            "adres": {
                "street": "Starogardzka11",
            },

            "adres": {
                "street": "Wioślarska 8 (4 piętro)",
            },

            "adres": {
                "street": "Konwaliowa, 15",
                "city": "Kamionki, pow. poznański",
            },

            "adres": {
                "street": "158",
                "city": "Jaworzynka",
            },

            "adres": {
                "street": "ul. Henryka Sienkiewicza 11 ( wejście od ul.Lipowej 1 )",
            },

            "adres": {
                "street": "UL MIESZKA I 64/8",
                "city": "GORZÓW WLKP.",
            },`

Powyższe przykładowe dane adresów dostawy pochodzą z praktycznych przykładów z obiektu order. Podczas tworzenia przesyłki za pomocą "Create a new parcel", a następnie podczas odpytania o status zwracacie mi błędy po API że podaję nieprawidłowe miasta/ulice, że ulica ma za dużo znaków, że nieprawidłowe znaki znajdują się w ulicy itp, **ale te same dane adresów dostawy zaakceptowaliście wcześniej od klienta kiedy wypełniał formularz podczas zakupu.**

Więc halo, nie uważacie że powinniście to poprawić? Byle kiedy nadziewam się na to że kupujący podał "Gorzów Wlkp." zamiast "Gorzów Wielkopolski" i muszę to ręczenie poprawiać potem, albo że ktoś podaje dodatkowe info w ulicy np. "(11 piętro)" i muszę to usuwać, nieoddzielone ulice od nr domów np. "Smerfowisko153". Ale to pochodzi wszystko z waszych formularzy - ja tylko przekazuję wasze pobrane dane dalej.

2. No i drugie pytanko podobne bardziej dotyczące firmy Inpost metody paczkomatów i jak ta metoda jest zintegrowana z waszym allegro (poprzez Inppost API ShipX). Jeżeli ktoś ma zintegrowane konto z Inposta z allegro i jest możliwe nadawanie paczek paczkomatowych firmy Inpost, to nie wiem czy wiecie ale w ogóle nie potrzeba tam podawać adresów dostawy, tylko **imie, nazwisko, nr telefonu i kod paczkomatu** nie zwracał bym na to uwagi, gdyby nie fakt że przez to że przesyłacie tam adres, to wiele pojawia się wiele błędów jak wyżej że adres/ulica/miasto jest nieprawidłowe. To samo zamówienie od was w serwisie menadzer.paczkomaty podczas tworzenia przesyłki w ich serwisie przechodzi bez problemu bo jedne co tam jest potrzebne to bodajże prawidłowy nr tel i kod paczkomatu. Chodzi tylko o przesyłki paczkomatowe.

**Comment by jezewskiBNetrox** [comment]
@JamesFordV3 Allegro wychodzi z założenia, że skoro zasady walidacyjne poszczególnych usługodawców są różne - to zrobią generyczną walidację a nie walidację dostosowaną do wybranej formy przesyłki. Sprzedawca ma pytać klienta o dane i marnować czas, bo Allegro nie zamierza go marnować. Generalnie punkt 1 dotyczy działania portalu a nie API, więc nie pomogą ci tutaj za bardzo.

**Comment by JamesFordV3** [comment]
@jezewskiBNetrox nieprawda, widzę jak ten system działa - to nie dana firma nie akceptuje tej walidacji tylko ona nie przechodzi przez walidację allegro (przynajmniej w przykładach które opisałem wyżej) - a skąd to wiem? bo wiem że inpost w ogóle nie zawraca błędów typu "nieprawidłowa ulica" podczas tworzenia przesyłki paczkomatowej, bo oni tego obiektu nie wymagają w ogóle, natomiast po stronie allegro otrzymuję taki błąd.

Czuję że allegro zrobiło jakiś swój własny walidator jeszcze po ich stronie za nim wyślą zapytanie na API danego dostawcy.

**Comment by Lukasz-Zurek** [comment]
@JamesFordV3 Przesłałeś dość specyficzne przypadki - np. "ul. Henryka Sienkiewicza 11 ( wejście od ul.Lipowej 1 )". Mogę tutaj potwierdzić, że w formularzu dostawy i zapłaty Klient może wprowadzić (w polu "ulica") więcej znaków aniżeli oczekujemy, bo standardowo pole to powinno zawierać nazwę ulicy i numer domu/mieszkania. W usłudze "Wysyłam z Allegro" musimy być dość uniwersalni, stąd pewne ograniczenia, biorąc pod uwagę wielu różnych przewoźników, którzy mają różnorodne wymagania dotyczące m.in. danych teleadresowych.

Jeśli chodzi o drugie pytanie - najlepiej będzie jak prześlesz jakieś konkretne przykłady. Zweryfikujemy je.

**Comment by JamesFordV3** [comment]
@Lukasz-Zurek no ale nie rozumiem dlaczego macie inną walidacje kiedy to klient wypełnia formularz, a kiedy ja próbuję nadać paczkę poprzez wysyłam z allegro używając danych które sam podał. Rozumiał bym jesczcze gdbym dostał zwrotkę od np. DPD/Inpostu czy konkrentej firmy że adres jest niepoprawny czy miasto - nie zgłaszał bym wtedy tego tutaj (do was), ale na tym etapie widzę że walidacja nie chce przejść jeszcze po waszej stronie.

Dlaczego ja (mój klient) jako sprzedający musi poprawiać te dane po kupującym? Nie możecie zaaplikować ten sam walidator dla kupującego? Tak jak jest teraz mnoży to wiele błędów.

Wiem że przesłałem "dosyć specyficzne" przypadki ale jak ma sie tych 200 zamówień dziennie czy ileś to specyficzny przypadek staje się problemetycznym bo się ich mnoży, tym bardziej że nurtuje mnie to już od jakiegoś czasu czemu muszę poprawiać "Gorzów Wlkp." na "Gorzów Wielkopolski" n razy czy inne podobne powtarzające się przypadki.



2. Jeżeli chodzi o drugie pytanie to chodzi mi to że w przypadku metody nadwania paczek Inpost paczkomatowych w ogóle niepotrzbne walidujecie adres ulicy, miasto i firmę, bo Inpost tego w ogóle nie bierze, a przez to że jest to też walidowane to również pojawia się sporo błędów z punktu 1.

**Comment by Lukasz-Zurek** [comment]
@JamesFordV3 Walidacja w formularzu dostawy i zapłaty na www to kwestia, na którą nie mamy niestety jakiegokolwiek wpływu - to kwestia poza API. Myślę, że temat możesz poruszyć zarówno na [Allegro Gadane](https://spolecznosc.allegro.pl/t5/dla-sprzedających/ct-p/Sprzedajacy), jak i poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda).

Co do drugiego pytania - jak rozumiem - wspomniane błędy pojawiają się po stronie panelu Managera Paczek InPost? Nie otrzymaliśmy od firmy InPost zgłoszeń dotyczących tych utrudnień. Jeżeli nadal one występują, warto zgłosić tę sprawę bezpośrednio do Inpostu. Jeśli InPost potwierdzi problemy po stronie przekazywanych przez nas danych - z pewnością się do nas zwróci.
