### ISSUE TITLE
Oferta z wybraną kategorią nie będzie widoczna w twoim serwisie bazowym

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#7872]
Dostaję taki błąd podczas próby wykonania PATCH'a /sale/product-offers:

ConstraintViolationException.AssortmentVisible
Oferta z wybraną kategorią nie będzie widoczna w twoim serwisie bazowym

trace-id: f88de20c50abdd66

Nie bardzo wiem o co chodzi. Proszę o pomoc.

**Comment by Onixarts** [comment]
Mamy to samo.

**Comment by rasskabak** [comment]
Mamy to samo

**Comment by Lukasz-Zurek** [comment]
Otrzymałem już potwierdzenie, że problem nie powinien się powtarzać.

**Comment by tomylee0** [comment]
U nas problem zniknął około 11:00. Dzięki.
