### ISSUE TITLE
Oferta z wybraną kategorią nie będzie widoczna w twoim serwisie bazowym.

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#7873]
Występuje problem:
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

`afbd3ed667a8c5b`

**Comment by Onixarts** [comment]
Mamy to samo

**Comment by Hornir91** [comment]
Posiadamy taki sam problem.  Prosimy o szybką naprawę.

**Comment by manoos** [comment]
U nas to samo przez API i przez formularz edycji oferty w allegro.pl

**Comment by rasskabak** [comment]
Mamy to samo

**Comment by manoos** [comment]
Już naprawili :)

**Comment by Lukasz-Zurek** [comment]
Potwierdzam - problem został już wyeliminowany. 

Przepraszamy za utrudnienia.
