### ISSUE TITLE
Błąd Oferta z wybraną kategorią nie będzie widoczna w twoim serwisie bazowym

### ISSUE THREAD

**Issue by AdrianeZ** [allegro/allegro-api#7874]
Witam! Od dzisiaj dostajemy błąd korzystając z zasobu PATCH /sale/product-offers/{offerId}. Próbując zaktualizować opisy i zdjecia oferty 
![obraz](https://github.com/allegro/allegro-api/assets/69970869/2fbc48e1-770d-4737-be59-0a449dccdce1)
 Przykład oferty, dla której dostaliśmy błąd https://allegro.pl/oferta/peugeot-boxer-308-206-206-uszczelka-drzwi-nowa-10706034277 co ciekawe wysyłając identyczny request kilka razy w końcu oferta się aktualizuje i błąd nie występuje

**Comment by karoprogramistka** [comment]
Dostajemy ten sam komunikat przy próbie dodania oferty 
![0--erwr](https://github.com/allegro/allegro-api/assets/115866152/19c3efd0-35b8-46f7-9eb7-0581fac664a2)

**Comment by Lukasz-Zurek** [comment]
Przepraszamy za zaistniałe utrudnienia. Nie powinny się już powtarzać.
