### ISSUE TITLE
Dostępność przez API informacji o punkcje odbioru Allegro One Box

### ISSUE THREAD

**Issue by theundefined** [allegro/allegro-api#7875]
### Discussed in https://github.com/allegro/allegro-api/discussions/7050

<div type='discussions-op-text'>

<sup>Originally posted by **theundefined** May  6, 2023</sup>
Nie znalazłem w api możliwości pobrania informacji o konkretnych punktach odbioru Allegro One Box. W szczególności o aktualnym stanie powietrza przy punktach - byłoby super gdyby powstał endpoint api udostępniajacy takie informacje, najlepiej wraz z historią - obecnie są one dostępne z tego co widzę tylko przez stronę.</div>

**Comment by Lukasz-Zurek** [comment]
@theundefined Listę punktów Allegro sprawdzisz za pomocą [GET /order/carriers/ALLEGRO/points](https://developer.allegro.pl/documentation/#operation/getAllegroPickupDropOffPointsGET). Nie zwracamy tam jednak informacji dotyczących aktualnego stanu powietrza przy punktach.

Więcej informacji o powyższym zasobie znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-pobrac-liste-punktow-allegro).

**Comment by theundefined** [comment]
Dzięki :-) Ale - stricte szukałem pod kątem jakości powietrza. Byłoby bardzo fajnie gdyby została dodana :-)

**Comment by Lukasz-Zurek** [comment]
@theundefined Dziękujemy za tę sugestię. Widzę, że już wcześniej utworzyłeś wątek na [Discussions](https://github.com/allegro/allegro-api/discussions/7050). Przeanalizujemy go i skonsultujemy z odpowiednim zespołem.
