### ISSUE TITLE
Infromację o przesyłce, skąd pobrać ShipmentId (WzA)

### ISSUE THREAD

**Issue by eof-the** [allegro/allegro-api#7876]
Chciałbym sprawdzić dane istniejącej przesyłki i się nie da. Sprawdzam Id przesyłki zasobem order/checkout-forms/{id}/shipments
dostaje tu id przesyłki , ale uzywając tego id (zarówno to z id jak id z kolekcji lineItems) z zasobem /shipment-management/shipments/ dostaje informację zwrotną: SHIPMENT_NOT_FOUND

W pomocy jest "Aby pobrać szczegółowe dane paczki, użyj [GET /shipment-management/shipments/{shipmentId}]. Jako shipmentId przekaż identyfikator paczki, który otrzymasz w odpowiedzi dla [GET /shipment-management/shipments/create-commands/{commandId}]."

Paczka była tworzona ręcznie przez www. Nie wiem jaki był nadany shipmentId, ale chyba jakoś powinno to dać się pobrać. Jakim zasobem?

**Comment by Lukasz-Zurek** [comment]
Nie, w tej sytuacji nie uzyskasz informacji o przesyłce. Zasób ten przeznaczony jest do sprawdzania przesyłek nadanych poprzez "Wysyłam z Allegro", za pośrednictwem publicznego API, gdzie **shipmentId** zwracany jest w odpowiedzi dla [GET /shipment-management/shipments/create-commands/{commandId](https://developer.allegro.pl/documentation/#operation/getShipmentCreationStatus).

**Comment by eof-the** [comment]
To jak nadać nie przez publiczne API?

**Comment by Lukasz-Zurek** [comment]
@eof-the Wprowadziłem Cię w błąd, za co przepraszam. Jak się okazuje, podczas tworzenia paczki za pośrednictwem www, **shipmentId** zwracamy w url, wówczas, gdy utworzysz paczkę i przejdziesz na stronę wyboru przesyłki, dla której chcesz pobrać etykiety lub zamówić podjazd. Czyli teoretycznie możesz we własnym zakresie zapisać ów **shipmentId**, by sprawdzić dokładne informacje dotyczące przesyłki za pośrednictwem API.

**Comment by eof-the** [comment]
Niezbyt rozumiem po co to utrudnienie, skoro w zasobach order są informacje o przesyłkach powiązanych z zamówieniem, to powinno też tam być shipmentId. IMO to przeoczenie, które powinniście naprawić.

**Comment by Lukasz-Zurek** [comment]
@eof-the Nie jest to przeoczenie. W zamówieniach nie zwracamy tego typu informacji. Proces nadawania przedmiotu/tworzenia paczki następuje później, po pobraniu szczegółów zamówienia (nie tylko adresu e-mail odbiorcy, ale również danych adresowych).
