### ISSUE TITLE
[WzA] Paczkomaty InPost - pickup proposals

### ISSUE THREAD

**Issue by lukasz-ideaware** [allegro/allegro-api#7877]
Stworzyłem paczkę dla zamówienia, jednak przy próbie zamówienia kuriera otrzymuję pustą listę propozycji terminów odbioru. Dla Allegro One dostaję propozycję terminów. Mam podłączony klucz inPost API z sandboxa https://sandbox-manager.paczkomaty.pl/, paczki pojawiają się w systemie. Czy wynika to może z tego, że w managerze paczek inpost nie mam zweryfikowanych punktów odbioru? 

Pytanie drugie, czy istnieje możliwość włączenia testowych paczkomatów dla sandboxa? Na ten moment w checkoucie dostępne są paczkomaty ze środowiska live, które nie pokrywają się z tymi ze środowiska sandbox co uniemażliwia płynne testowanie integracji (w procesie muszę ręcznie zmienić ID paczkomatu na testowy).

**Comment by PrzemyslawLukanowski** [comment]
To prawidłowe działanie, InPost nie zwraca nam proponowanych godzin. Zamawiając kuriera, nie przekazuj proszę pola `pickupDate`. 

Co co drugiego pytania, przykładowe punkty znajdziesz pod tym linkiem https://sandbox-easy-geowidget-sdk.easypack24.net/.

**Comment by lukasz-ideaware** [comment]
Używam Shipment Managera a nie Parcel Managera
https://developer.allegro.pl/documentation#operation/createPickup
tutaj pole pickupDateProposalId jest wymagane

**Comment by PrzemyslawLukanowski** [comment]
W takiej sytuacji w polu `pickupDateProposalId` przekaż wartość "ANY".

**Comment by lukasz-ideaware** [comment]
Czy mogę założyć, że jeżeli nie mam żadnych propozycji terminów to zawsze wysyłam ANY czy taka sytuacja wystąpi tylko w inpost?

**Comment by PrzemyslawLukanowski** [comment]
> Czy mogę założyć, że jeżeli nie mam żadnych propozycji terminów to zawsze wysyłam ANY czy taka sytuacja wystąpi tylko w inpost?

Taka sytuacji występuje tylko dla InPost. Dla reszty przewoźników, brak propozycji oznacza brak możliwości zamówienia podjazdu.

> I kolejne pytanie, czy mogę grupować metody dostaw po kurierze który obsługuje daną metodę i zbiorczo zamawiać kuriera dla wszystkich paczek przez niego obsługiwanych?

Tak, możesz tak zrobić.
