### ISSUE TITLE
Aktywacja konta firmowego - sandbox

### ISSUE THREAD

**Issue by jensej** [allegro/allegro-api#7878]
Dzień dobry,
aktywacja konta firmowego nie przebiega automatycznie po płatności (sandboxowej)?
moj nick: deqeen
Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.

**Comment by jensej** [comment]
super działa ale pojawił się problem numer 2.
Gdy stworzyłem konto zwykłe i chciałem dokonać zakupu prosi mnie o podanie kodu SMS:
znalazłem coś takiego:

"W przypadku Sandboxa - nie wyślemy kodu SMS. Wprowadź kod: 1234." ale ten kod nie działa.
Moje konto klienta: Client:106221607

**Comment by PrzemyslawLukanowski** [comment]
Dodatkowo aktywowałem Twoje konto, spróbuj proszę ponownie i jeśli wyświetli się miejsce na kod sms, wpisz 123456. Ten kod, który przytoczyłeś, dotyczył logowania na konto.
