### ISSUE TITLE
OfferAccessDeniedException podczas próby wystawienia oferty produktu

### ISSUE THREAD

**Issue by AlpanetPL** [allegro/allegro-api#7879]
Dzień dobry,

Przerabiam wystawianie oferty dla klienta z /sale/offers na /sale/product-offers na koncie sandbox ID: 43968170. Rozdzielałem właśnie parametry na produktowe i ofertowe więc poszło kilka/kilkanaście niepoprawnych requestów - dostawałem błędy głównie o tym, że jakiś parametr nie jest produktowy/ofertowy i powinien być w sekcji productSet.product.parameters. Po skończonych przeróbkach dostaję exception:

"code": "OfferAccessDeniedException",
"message": "Forbidden",
"details": null,
"path": "",
"userMessage": "Access denied. You are not authorized to perform operations on the indicated offer"

Szukałem trochę o tym na Waszym GitHubie i dość często pojawia się problem niefirmowego konta, moje natomiast jest firmowe - przynajmniej taka informacja widnieje w panelu Moje Allegro na  Sandoxie. Będę wdzięczny za sprawdzenie i pomoc - być może konto nie było dość długo używane i stąd problem (chociaż od czwartku 26.10 jest używane dość intensywnie).

Pozdrawiam,
Artur.

**Comment by AlpanetPL** [comment]
[test.json](https://github.com/allegro/allegro-api/files/13206045/test.json)

Dołączam na wszelki wypadek request POST jaki posyłałem na https://api.allegro.pl.allegrosandbox.pl/sale/product-offers.

**Comment by Lukasz-Zurek** [comment]
@AlpanetPL Twoje konto firmowe nie jest w pełni zweryfikowane, dlatego zwracamy Tobie komunikaty ze wskazanym błędem. Mogę również potwierdzić, że to konto zostało zarejestrowane kilka lat temu, przez co może być problem z jego pełną weryfikacją.

Spróbuj jeszcze przejść przez [zmianę danych firmy](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta/zmien-dane-firmy), a następnie [ustawienia wypłat](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat), gdzie konieczne będzie jeszcze skorzystanie z symulatora płatności.

**Comment by AlpanetPL** [comment]
Dziękuję. Wprowadziłem zmiany w danych firmy, dodałem właściciela oraz zrobiłem fikcyjny przelew na 1 zł. Na razie mam informację, że zarówno konto, jak i nowe dane są weryfikowane.

**Comment by Lukasz-Zurek** [comment]
@AlpanetPL Zweryfikowałem Twoje konto, więc teraz powinno być już ok.

**Comment by AlpanetPL** [comment]
Tak, właśnie wystawiłem pierwszy produkt za pomocą /sale/product-offers.
Dzięki wielkie.

**Comment by pavelion** [comment]
Hi, I have the same problem although I am able to create new offer on the sandbox website.

I tried to update account information, bank information etc. but it seems that the process requires me to actually provide real data, transfer money, upload personal documents i.e. no mocks/simulation. I uploaded the photo of my guinea pig as my ID because I could not believe anyone would require my personal documents to access sandbox environment...

Is this normal and really required? My account is several years old as well, my verification process ID: 1dfc8b9c-a140-499f-b913-172906cb3eea

**Comment by Lukasz-Zurek** [comment]
@pavelion No, we do not require any personal documents or real data. We suggest using only fictitious data for their security.

I have activated your account so you already can use it.

**Comment by pavelion** [comment]
Thank you very much! 

> @pavelion No, we do not require any personal documents or real data. We suggest using only fictitious data for their security.
> 
> I have activated your account so you already can use it.
