### ISSUE TITLE
WEBAPI edycja aukcji usuwa parametry z wieloma wartościami

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#788]
Witam,

podczas edycji aukcji przez webapi jest problem z parametrami posiadającymi kilka wartości - zostają usunięte.

1. przykładowo na aukcji było:
`Numery katalogowe zamienników: 1520, LS1401, 50-08350, 12841, 260157, 70 61 0009, CI-LS-3267, 33465-PCS-MS, FL489-H, JTS643`

2. edytuje aukcje przez dochangeitemfields, nie ruszając w ogóle powyższego fida, przykładowo zmieniając stronę zabudowy

3. edycja zakończona, strona zabudowy zmieniona, niestety powyższy fid wygląda teraz tak:
`Numery katalogowe zamienników: 1520`

**Comment by PawelTaberski** [comment]
Prosiłbym o podesłanie przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) requesta i responsa w formacie XML z tym błędem sprawdzimy w czym jest problem. W zgłoszeniu zaznacz proszę, że dane podsyłasz do ticketa numer 788 na GitHub-ie.

**Comment by dlis2010** [comment]
@PawelTaberski widzę, że tę odpowiedź wysyłacie już z automatu...

jakbym to robił po rest to rozumie r&r by mogły coś powiedzieć. W tym wypadku przez webapi przesyłam tylko zmiane fida X w odpowiedzi dostaję aukcje z zmienionym fidem X oraz fidem Y.

Problem jest po Waszej stronie z obsługą tego niesfornego stringa. Dla ułatwienia dodam że numer katalogowy części to fid 39624 - prześlij dalej, będą wiedzieć co z tym zrobić ;)

**Comment by PawelTaberski** [comment]
@dlis2010 Tak, jak pisałem do zweryfikowania problemu potrzebuję Twojego requesta i responsa. Znacznie skróci to czas weryfikacji i będę mógł wtedy powtórzyć ten błąd i sprawdzić w czym jest problem. Jeśli jest to dla Ciebie bardzo czasochłonne podeślij nam choć numer oferty.

**Comment by PawelTaberski** [comment]
Nie zajmujemy się tylko weryfikacją zgłoszeń na GitHub-ie i odpowiedziami na pytania, także jeżeli możemy sobie nawzajem ułatwić pracę, to nie widzę w tym nic złego.
Sprawdziłem sprawę o której napisałeś i problem nie jest w edycji oferty a w samym parametrze, już przy samym pobraniu oferty pobierane jest tylko pierwsze pole. Problem ten nie występuje w REST API ani w formularzu. Przekazałem sprawę do naprawy do odpowiedniego zespołu. Proszę o cierpliwość.

**Comment by dlis2010** [comment]
Wybacz, nerwowa dziś atmosfera u nas i obrywa się Wam rykoszetem...

Weź pod uwagę, że parametr ten jest nie tylko błędnie zwracany w response, ale jest też zmieniany na aukcji.

**Comment by PawelTaberski** [comment]
Własnie o to mi chodziło, że już na etapie pobrania jest problem, przez co widać, że przy jakiejkolwiek zmianie przez WebAPI nie jest przekazywana cała reszta pól bo nie jest w stanie tego obsłużyć. Sprawę,tak jak mówiłem zgłosiłem z wysokim priorytetem i mam nadzieję, że problem szybko uda się rozwiązać.

**Comment by dlis2010** [comment]
@PawelTaberski jak postępy?
