### ISSUE TITLE
Nie mogę pobrać listy dostawców

### ISSUE THREAD

**Issue by daniel500013** [allegro/allegro-api#7880]
Podczas pobierania listy dostawców dostałem taki błąd jaki jest na załączonym obrazku
![image](https://github.com/allegro/allegro-api/assets/30683843/02522cf6-684e-4e43-946f-5da8eae6f707)
Wszystkie uprawnienia mam przypisane podczas generowania tokenu więc to raczej nie jest problem z brakiem uprawnień, tutaj zdjęcie
![image](https://github.com/allegro/allegro-api/assets/30683843/1ed3c041-06b1-4acd-904e-4db82e6ef1d3)

**Comment by Lukasz-Zurek** [comment]
Problem potwierdzam. Przekazałem już zgłoszenie do właściwego zespołu. Wkrótce wrócę z informacją.

**Comment by daniel500013** [comment]
Nadal czekam na informacje

**Comment by Lukasz-Zurek** [comment]
@daniel500013 Pamiętam o Twoim przypadku. Przypomniałem się zespołowi, który nadal weryfikuje dokładną przyczynę. Aczkolwiek sytuacja powinna wrócić już do normy. Czy możesz to potwierdzić?
