### ISSUE TITLE
Parametr `category.id` w zasobie `/sale/products/{productId}` nie powoduje oczekiwanej zmiany

### ISSUE THREAD

**Issue by dawidczech355a** [allegro/allegro-api#7881]
Zauważyłem, że kiedy do zasobu GET `/sale/products/{productId}` przekazuję parametr `category.id`, którego wartość jest równa jednej z kategorii na liście "similar" dla tego produktu, zwrotka jest identyczna jak bez przekazania parametru. Niestety nie jestem w stanie znaleźć przykładu, dla którego przekazanie `category.id` cokolwiek by zmieniało.

Przykład poniżej.

Pytanie o produkt bez `category.id`:
`curl --location 'https://api.allegro.pl/sale/products/54727976-fb32-406c-ba11-7690df025de7' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Accept-Language: pl-PL' \
--header 'Authorization: Bearer XYZ' \
--header 'Content-Type: application/vnd.allegro.public.v1+json'`

Zwraca następującą listę parametrów:
`"parameters": [
        {
            "id": "127415",
            "name": "Producent części",
            "valuesLabels": [
                "Filtron"
            ],
            "valuesIds": [
                "127411_338861"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": true
            }
        },
        {
            "id": "215858",
            "name": "Numer katalogowy części",
            "valuesLabels": [
                "OP 525"
            ],
            "values": [
                "OP 525"
            ],
            "unit": null,
            "options": {
                "identifiesProduct": true
            }
        },
        {
            "id": "129591",
            "name": "Typ samochodu",
            "valuesLabels": [
                "Autobusy",
                "Samochody ciężarowe",
                "Samochody dostawcze",
                "Samochody osobowe"
            ],
            "valuesIds": [
                "129591_8",
                "129591_4",
                "129591_2",
                "129591_1"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        },
        {
            "id": "202285",
            "name": "Rodzaj filtra oleju",
            "valuesLabels": [
                "przykręcany"
            ],
            "valuesIds": [
                "202285_324797"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        },
        {
            "id": "215941",
            "name": "Numery katalogowe zamienników",
            "valuesLabels": [
                "BOSCH 0 451 103 346",
                "BOSCH 0 451 103 906",
                "BOSCH 0 451 203 012",
                "BOSCH 0 986 452 400",
                "Dr!ve+ DP1110.11.0162",
                "OPEN PARTS EOF4033.20",
                "ProfiPower 1F0016",
                "PROFIT 1540-1057",
                "PROFIT 1541-0170",
                "PZL Filters PP87A",
                "QUINTON HAZELL QFL0002",
                "QUINTON HAZELL QFL0141",
                "TOPRAN 101 447",
                "TOPRAN 108 206",
                "WILMINK GROUP WG1746668",
                "WILMINK GROUP WG2223530",
                "WILMINK GROUP WG2280110",
                "WILMINK GROUP WG2280114",
                "WILMINK GROUP WG2284824",
                "WILMINK GROUP WG2284891"
            ],
            "values": [
                "BOSCH 0 451 103 346",
                "BOSCH 0 451 103 906",
                "BOSCH 0 451 203 012",
                "BOSCH 0 986 452 400",
                "Dr!ve+ DP1110.11.0162",
                "OPEN PARTS EOF4033.20",
                "ProfiPower 1F0016",
                "PROFIT 1540-1057",
                "PROFIT 1541-0170",
                "PZL Filters PP87A",
                "QUINTON HAZELL QFL0002",
                "QUINTON HAZELL QFL0141",
                "TOPRAN 101 447",
                "TOPRAN 108 206",
                "WILMINK GROUP WG1746668",
                "WILMINK GROUP WG2223530",
                "WILMINK GROUP WG2280110",
                "WILMINK GROUP WG2280114",
                "WILMINK GROUP WG2284824",
                "WILMINK GROUP WG2284891"
            ],
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        },
        {
            "id": "225693",
            "name": "EAN (GTIN)",
            "valuesLabels": [
                "5904608005250"
            ],
            "values": [
                "5904608005250"
            ],
            "unit": null,
            "options": {
                "identifiesProduct": false,
                "isGTIN": true
            }
        },
        {
            "id": "227345",
            "name": "Numer katalogowy oryginału",
            "valuesLabels": [
                "FORD 5011 838",
                "GENERAL MOTORS 7984460",
                "GENERAL MOTORS 93156363",
                "SCHMITZ CARGOBULL 1341113",
                "VAG 028 115 561 E",
                "VAG 028 115 561 G",
                "VAG 068 115 561",
                "VAG 068 115 561 A",
                "VAG 068 115 561 B",
                "VAG 068 115 561 C",
                "VAG 681 155 613",
                "VOLVO 1257492",
                "VOLVO 1257492-7"
            ],
            "values": [
                "FORD 5011 838",
                "GENERAL MOTORS 7984460",
                "GENERAL MOTORS 93156363",
                "SCHMITZ CARGOBULL 1341113",
                "VAG 028 115 561 E",
                "VAG 028 115 561 G",
                "VAG 068 115 561",
                "VAG 068 115 561 A",
                "VAG 068 115 561 B",
                "VAG 068 115 561 C",
                "VAG 681 155 613",
                "VOLVO 1257492",
                "VOLVO 1257492-7"
            ],
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        },
        {
            "id": "227357",
            "name": "Wysokość",
            "valuesLabels": [
                "139,00 mm"
            ],
            "values": [
                "139.00"
            ],
            "unit": "mm",
            "options": {
                "identifiesProduct": false
            }
        },
        {
            "id": "227821",
            "name": "Średnica zewnętrzna",
            "valuesLabels": [
                "94,0 mm"
            ],
            "values": [
                "94.0"
            ],
            "unit": "mm",
            "options": {
                "identifiesProduct": false
            }
        }
    ]`

Pytanie o ten sam produkt, ale z `category.id` innym niż domyślne (id kategorii z listy "similar"):
`curl --location 'https://api.allegro.pl/sale/products/54727976-fb32-406c-ba11-7690df025de7?category.id=49242' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Accept-Language: pl-PL' \
--header 'Authorization: Bearer XYZ' \
--header 'Content-Type: application/vnd.allegro.public.v1+json'`

Zwraca dokładnie taką samą listę parametrów:
`"parameters": [
        {
            "id": "127415",
            "name": "Producent części",
            "valuesLabels": [
                "Filtron"
            ],
            "valuesIds": [
                "127411_338861"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": true
            }
        },
        {
            "id": "129591",
            "name": "Typ samochodu",
            "valuesLabels": [
                "Autobusy",
                "Samochody ciężarowe",
                "Samochody dostawcze",
                "Samochody osobowe"
            ],
            "valuesIds": [
                "129591_8",
                "129591_4",
                "129591_2",
                "129591_1"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        },
        {
            "id": "202285",
            "name": "Rodzaj filtra oleju",
            "valuesLabels": [
                "przykręcany"
            ],
            "valuesIds": [
                "202285_324797"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        },
        {
            "id": "215941",
            "name": "Numery katalogowe zamienników",
            "valuesLabels": [
                "BOSCH 0 451 103 346",
                "BOSCH 0 451 103 906",
                "BOSCH 0 451 203 012",
                "BOSCH 0 986 452 400",
                "Dr!ve+ DP1110.11.0162",
                "OPEN PARTS EOF4033.20",
                "ProfiPower 1F0016",
                "PROFIT 1540-1057",
                "PROFIT 1541-0170",
                "PZL Filters PP87A",
                "QUINTON HAZELL QFL0002",
                "QUINTON HAZELL QFL0141",
                "TOPRAN 101 447",
                "TOPRAN 108 206",
                "WILMINK GROUP WG1746668",
                "WILMINK GROUP WG2223530",
                "WILMINK GROUP WG2280110",
                "WILMINK GROUP WG2280114",
                "WILMINK GROUP WG2284824",
                "WILMINK GROUP WG2284891"
            ],
            "values": [
                "BOSCH 0 451 103 346",
                "BOSCH 0 451 103 906",
                "BOSCH 0 451 203 012",
                "BOSCH 0 986 452 400",
                "Dr!ve+ DP1110.11.0162",
                "OPEN PARTS EOF4033.20",
                "ProfiPower 1F0016",
                "PROFIT 1540-1057",
                "PROFIT 1541-0170",
                "PZL Filters PP87A",
                "QUINTON HAZELL QFL0002",
                "QUINTON HAZELL QFL0141",
                "TOPRAN 101 447",
                "TOPRAN 108 206",
                "WILMINK GROUP WG1746668",
                "WILMINK GROUP WG2223530",
                "WILMINK GROUP WG2280110",
                "WILMINK GROUP WG2280114",
                "WILMINK GROUP WG2284824",
                "WILMINK GROUP WG2284891"
            ],
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        },
        {
            "id": "225693",
            "name": "EAN (GTIN)",
            "valuesLabels": [
                "5904608005250"
            ],
            "values": [
                "5904608005250"
            ],
            "unit": null,
            "options": {
                "identifiesProduct": false,
                "isGTIN": true
            }
        },
        {
            "id": "227345",
            "name": "Numer katalogowy oryginału",
            "valuesLabels": [
                "FORD 5011 838",
                "GENERAL MOTORS 7984460",
                "GENERAL MOTORS 93156363",
                "SCHMITZ CARGOBULL 1341113",
                "VAG 028 115 561 E",
                "VAG 028 115 561 G",
                "VAG 068 115 561",
                "VAG 068 115 561 A",
                "VAG 068 115 561 B",
                "VAG 068 115 561 C",
                "VAG 681 155 613",
                "VOLVO 1257492",
                "VOLVO 1257492-7"
            ],
            "values": [
                "FORD 5011 838",
                "GENERAL MOTORS 7984460",
                "GENERAL MOTORS 93156363",
                "SCHMITZ CARGOBULL 1341113",
                "VAG 028 115 561 E",
                "VAG 028 115 561 G",
                "VAG 068 115 561",
                "VAG 068 115 561 A",
                "VAG 068 115 561 B",
                "VAG 068 115 561 C",
                "VAG 681 155 613",
                "VOLVO 1257492",
                "VOLVO 1257492-7"
            ],
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        }
    ]`

Parametry obowiązujące w kategorii `49239` są inne niż te w kategorii `49242`. Różnią się między innymi parametrem "Numer katalogowy części", obie kategorie posiadają parametr o takiej nazwie, mają one jednak inne identyfikatory.

Czy rezultat zapytania o szczegóły produktu `/sale/products/{productId}`, z przekazanym parametrem `category.id=49242`, nie powinien skutkować zwróceniem listy parametrów zgodnej z przekazaną kategorią?

**Comment by Lukasz-Zurek** [comment]
@dawidczech355a Potwierdzam. Konsultuję te kwestie z odpowiednim zespołem.

Chciałbym również zwrócić Tobie uwagę na udostępniane w wątku tokeny - z uwagi na bezpieczeństwo danych, sugeruję, abyś nie dodawał tego typu danych na forum.

**Comment by dawidczech355a** [comment]
Oczywiście, dziękuję za uwagę, już poprawiłem mój wpis.

**Comment by dawidczech355a** [comment]
Czy wiadomo cokolwiek w tej sprawie? @Lukasz-Zurek

**Comment by Lukasz-Zurek** [comment]
@dawidczech355a Weryfikujemy to jeszcze. Bardzo proszę o cierpliwość. Postaram się wrócić z odpowiedzią w jak najkrótszym czasie.
