### ISSUE TITLE
Link do oferty

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#7885]
Występuje problem:
 - [x] ze środowiskiem produkcyjnym / with the production environment

Dlaczego URL [http://allegro.pl/oferta/12838854035](http://allegro.pl/oferta/12838854035) przekierowuje do innej oferty, na innym koncie? To samo dzieje się po wpisaniu numeru w wyszukiwarce

**Comment by Lukasz-Zurek** [comment]
Problem ten nie dotyczy API, w związku z czym aby wyjaśnić te kwestie, skorzystaj proszę z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=30db29ca-fb10-434b-a5f0-fc43019af49b).
