### ISSUE TITLE
Aktywacja sprzedaży

### ISSUE THREAD

**Issue by Lukasz-Zurek** [allegro/allegro-api#7886]
### Discussed in https://github.com/allegro/allegro-api/discussions/7883

<div type='discussions-op-text'>

<sup>Originally posted by **lhascilo** October 31, 2023</sup>
Czy mogę prosić o aktywację sprzedaży dla loginu mbblogistics na sandboxie? </div>

**Comment by Lukasz-Zurek** [comment]
@lhascilo Przeniosłem Twój wątek z zakładki Discussions (miejsce dedykowane do sugestii i pomysłów rozwoju Allegro API) do Issues (miejsce do zgłaszania błędów dotyczących API i próśb o aktywację konta na Allegro Sandbox). 

Przejdź proszę jeszcze do [ustawień wypłat](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat) i skorzystaj z symulatora płatności. Daj proszę znać jak wykonasz te czynności.

**Comment by lhascilo** [comment]
Dzień dobry,

Jako ze konto mbblogistics bylo kontem firmowym nie moglem przejsc do symulatora płatości. Zrobiłem to na koncie: Client:106222170 niestety po kliknieciu płatności blik (http://c2c-payu-simulator.dh-test.qxlint/simulator/orders/19672ba2-b820-4958-a6b5-9b6c15525b85) mam komunikat:

Niestety, nie udało się odnaleźć tej strony

Nie udało się połączyć z serwerem pod adresem „c2c-payu-simulator.dh-test.qxlint”.

**Comment by Lukasz-Zurek** [comment]
> Dzień dobry,
> 
> Jako ze konto mbblogistics bylo kontem firmowym nie moglem przejsc do symulatora płatości. 

W tej sytuacji tym bardziej powinieneś mieć taką możliwość. Czy mógłbyś opisać występujące problemy, ewentualnie przesłać tutaj zrzuty ekranu?

> Zrobiłem to na koncie: Client:106222170 niestety po kliknieciu płatności blik (http://c2c-payu-simulator.dh-test.qxlint/simulator/orders/19672ba2-b820-4958-a6b5-9b6c15525b85) mam komunikat:
> 
> Niestety, nie udało się odnaleźć tej strony
> 
> Nie udało się połączyć z serwerem pod adresem „c2c-payu-simulator.dh-test.qxlint”.

To konto posiada status zwykłego, więc możesz je aktywować przy pierwszym zakupie i skorzystaniu z symulatora płatności podczas zakupu - najlepiej będzie jak wybierzesz szybki przelew bankowy, np. mbank.

**Comment by lhascilo** [comment]
Oczywiście. Poklikneciu na dowolną metode płatności (tutaj kliknąłęm na BLIK). strona przekierowuje sie jak na screenie
![obraz](https://github.com/allegro/allegro-api/assets/5717156/66f9394e-f450-4ae3-90bc-50c2e9784703)
![2023-11-02 15_39_27-Window](https://github.com/allegro/allegro-api/assets/5717156/dcfeec9f-6882-45ea-904f-db59fe446f79)
Próbowałem to robic w przeglądarkach EDGE, Chrome, Firefox.

**Comment by Lukasz-Zurek** [comment]
@lhascilo Aktywowałem ręcznie wskazane konta. Sprawdź czy wszystko jest ok.

**Comment by Lukasz-Zurek** [comment]
@lhascilo Nie mam takiej możliwości. Aktywując Allegro Smart na sandboxie, jako kod do Blik przekaż: **777123**.
