### ISSUE TITLE
Błąd przy dodawaniu produktu

### ISSUE THREAD

**Issue by Jaanioo** [allegro/allegro-api#7888]
Dzień dobry. Przy próbie utworzenia produktu dostajemy taki błąd: 
Komunikat Allegro:

t[race-id: 43ee2a2129ebcbac](https://app.asana.com/0/0/1205842120737676)

ConstraintViolationException.AssortmentVisible
Oferta z wybraną kategorią nie będzie widoczna w twoim serwisie bazowym.

Co go powoduje? Jak ograć ten błąd?

**Comment by Lukasz-Zurek** [comment]
Z tego co widzę - wskazany request jest z wczoraj, z godzin porannych. Mieliśmy problemy techniczne, które udało się już wyeliminować.

Przepraszamy za zaistniałe utrudnienia.
