### ISSUE TITLE
Data wygaśnięcia zdjęcia

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#7889]
Przy dodawaniu zdjęcia poprzez API otrzymuje się czas za ile ono wygaśnie, czy jest możliwość pozyskania informacji o dacie wygaśnięcia zdjęcia dodanego do oferty np. z poziomu panelu allegro?

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale nie udostępniamy takiej możliwości.

**Comment by Maciej-Wilkosz** [comment]
A gdy API zwraca bład przy edycji o tym ,że jedno ze zdjęć wygasło. Jest jakaś możliwość aby stwierdzić które?

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie ma takiej możliwości, zwrócimy ogólny błąd.
