### ISSUE TITLE
Autoryzacja wielu kont Allegro z jednej aplikacji

### ISSUE THREAD

**Issue by pskz** [allegro/allegro-api#789]
Temat zgłaszany przez @dtarczynski już w lutym tego roku #11 nadal nie został rozwiązany mimo że issue został przez was zamknięty.

Mimo że mamy to opisane w dokumentacji naszej apki wielkimi literami i boldem, to klienci nie czytają, nie chcą, nie wiedzą, nie rozumieją...

Podczas autoryzacji konieczne jest przekazania parametrów "client_id" oraz "redirect_uri". W momencie podania nieprawidłowego "redirect_uri" zwracacie błąd, ale nie dla złego "client_id", dlaczego? Przecież nie pasuje do aktualnie zalogowanego konta, w efekcie zostaje zwrócony token dla zalogowanego, a nie dla autoryzowanego konta. Co powoduje że zamiast kilku kont, mamy jedno...

Generalnie generuje to ogromne problemy. Klienci nie zdają sobie sprawy że trzymacie sesje w przeglądarce podczas autoryzacji aplikacji, gdy autoryzują następne konto. Wychodzi to dopiero jak okazuje się że zduplikowały się zamówienia, rozjechały się stany magazynowe, i nie wiadomo co jeszcze. 
Ciągle mamy zgłoszenia że coś nie tak z aplikacją, a chodzi o banalny problem z autoryzacją. Jest to już męczące, i robi się nie do zniesienia!!!

Kiedy można się spodziewać poprawienia tego błędu?!

**Comment by PawelTaberski** [comment]
Tak, wiemy o tym problemie zalecamy w takim przypadku przy uwierzytelnieniu pamiętać o wylogowaniu, wiemy, że bywa to problemem. Sprawę jeszcze raz zgłosiłem jako sugestię do odpowiedniego zespołu. Jeśli zdecydujemy się wdrożyć takie rozwiązanie na pewno o tym poinformujemy w odpowiednik komunikacie. I nie wiem czy nie mylimy trochę nomenklatury, chyba że miałeś coś innego na myśli. ClientID jest to swoistego rodzaju login aplikacji (nie usera) a Client Secret jest swojego rodzaju hasłem aplikacji. Numer usera to user ID. Do jednego Client ID może być przypisanych dużo userów.

**Comment by pskz** [comment]
> w takim przypadku przy uwierzytelnieniu pamiętać o wylogowaniu

Developer czy dostawca aplikacji będzie pamiętał, ale przysłowiowy Jan Kowalski nie ma o tym pojęcia, nie czyta komunikatów, albo czyta je pobieżnie, wychodzi z założenia że przecież ma działać. A taka forma autoryzacji udostępniona przez was jest mało intuicyjna. Czy nie wystarczy wymusić logowania za każdym razem gdy następuje próba autoryzacji?

> Do jednego Client ID może być przypisanych dużo userów.

Czy to właśnie nie powoduje problemów? 
Loguje się na stronę apps.developer.allegro.pl jednym kontem, rejestruje apke otrzymuje ClientID i Secret, potem loguje się na inne konto Allegro i też muszę zarejestrować apke którą będę autoryzował. Co taje 2 konta i 2 rożne ClientID.

Teraz, wysyłając zapytanie o autoryzację podaje ClientID i loguje się na pierwsze konto Allegro, dane pasują otrzymuje kod dzięki któremu mogę pozyskać token.
Następnie, wysyłam kolejne zapytanie podając inne ClientID, jest ono z innego konta, ale przeglądarka trzyma sesje z poprzedniego logowania, i tu następuje rozbieżność danych, bo pod tym kontem nie mam zarejestrowanej aplikacji z takim ClientID.

Do tej pory analizując wszystkie zgłoszenia od klientów dotyczące powyższego problemu ClientID dla zarejestrowanych apek było różne. Stąd mój wniosek.

Mam nadzieję że udało mi się to dobrze wytłumaczyć.

**Comment by PawelTaberski** [comment]
Wydaje mi się, że nie do końca mówimy o tym samym. Client ID i Secred Client, tak jak pisałem powinien być przypisany per aplikacja. Jeden klucz dla jednej aplikacji, co ułatwia zarządzanie taką aplikacją. Taką aplikację powinieneś zarejestrować na swoim koncie nie na klienta i dopiero potem uderzać do klientów aby się uwierzytelnili. 
Jeśli założysz, tak jak mówisz klika kluczy dla tej samej aplikacji i wyślesz raz do usera A aby przypisał się do aplikacji A i zatwierdzi. Następnie wyślesz mu aby się zautoryzował do aplikacji B userem B, ale on nie wyloguje usera A to wyskoczy mu okno do powiazania aplikacji B i jak się zgodzi to do jednego konta będą podłączone 2 aplikacje A i B.
Ponadto wszystkie tokeny sa w technologi JWT także możesz je rozkodować w ten sposób otrzymasz m.in. datę wygaśnięcia, identyfikator użytkownika czy aplikacji. Co znacznie ułatwi Tobie zarządzanie tokenami i wyeliminuje problem operacji na nie tym koncie co chciałeś.

**Comment by pskz** [comment]
No właśnie nie ma aplikacji A i B, jest tylko jedna.
Klienci posiadają jedno, lub kilka kont na Allegro, albo zarządzają kilkoma różnymi kontami na raz (nie wnikam), ale chcą te kilka kont mieć na raz w tej aplikacji. Więc muszą każde konto po kolei autoryzować, prawda?, sprawa analogiczna jak w #11 

Ale nie każdy taki klient pamięta o tym żeby się wylogować, a tu po roku trzeba przedłużać autoryzacje bo access token wygasa (już mniejsza o to, ale i to też można by poprawić :) ), kto by pamiętał jak to się robiło rok temu, po prostu klikają i nagle problem. Nie znają się na tym, podchodzą do sprawy ma działać w prosty sposób, a działa na około.

Jakby problemu nie było to bym nie pisał ;) liczę że uda Wam się to w miarę szybko poprawić.

**Comment by PawelTaberski** [comment]
@wwwfactory Tak jak pisałem wiemy o problemie i planujemy wdrożenie rozwiązania tego problemu. Autoryzacja w trybie incognito nie jest rozwiązaniem docelowym :-). Tylko chwilowym obejściem problemu. Jak tylko wdrożymy rozwiązanie tego problemu to poinformujemy o tym w odpowiednim osobnym komunikacie.

**Comment by XardasLord** [comment]
Wydaje mi się, że w dalszym ciągu problem pozostaje nierozwiązany i autoryzując się nowym ClientId i ClientSecret w dalszym ciągu jesteśmy zalogowani jako poprzednio zalogowane konto?

**Comment by XardasLord** [comment]
Użyłem dziś parametru `prompt=confirm` i rzeczywiście pokazuje mi się dodatkowy monit o prośbę kontynuacji na obecnie zalogowanym koncie lub zmiana konta:
![image](https://github.com/allegro/allegro-api/assets/29070326/275ca24e-d023-42e3-9bd2-264e42d6013d)

Natomist gdy klikam "Zmień konto" to dostaję błąd 400. 
![image](https://github.com/allegro/allegro-api/assets/29070326/ec019473-b31d-4675-b60a-7587a638a47e)


URL na który allegro próbuje zrobić redirect: https://allegro.pl/authentication/logout/web?origin_url=https%3A%2F%2Fallegro.pl%2Fauth%2Foauth%2Fauthorize%3Fscope%3D%26response_type%3Dcode%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A6010%252Fauth%252Fallegro-auth-callback%252Fmy-test%26state%3DCfDJ8Jw8PQSv1YNLk8PG82Ho6rJtOUYAH-2li9GUjH5-3zPRTeFRvoCKxkBdfMPTy0U3c9oU5R_4_-iUIWHbKQawHO9H9US52oUtJALMKVn1t8RZbGz6UQok1MIsaPCCjjbwskeX4JPqeF9gUwjvfF7u41VzRQZ05visLzkhix6XYpchX2obDDL0M-ucgTB3Qfo_MEVmDQF0ak8FgovDUufpeI7GwwfIW3NQxY-YGZZURkRXSfzywv6XL0OI67UWAzUw-PsCD2wDu-rif_KSUfYxVaPB056bVD1m_j79GXlxUcktPbMg_ZZXwu03mRFjxRZSuAAppJkzaneTklAKRRfnoF-uWoJI1cfUICjGceHCU6KEgz7nlVI9RO0XnuJDScGh8-ElvfhWCzOoXpdIAuHx5W1yzjmuEGTLkcGdkYee-RDOULjHaa2p28Q06T_8aBL0_VPiGSVM8tEiAT4vrtzeeRthaso_58RRBrqxcmHf_SvSoOFxrYTItTGas88BPrVmhDW-kQ2m-rHzYOexc0rMdkTaTcN4ZahDQK0SJiNWhMtK_ShjeY363NK4TefAwdrr_UV46p5_8fc8Cs1j32uKkauNlWQwkxvgL-XyWEkaMkWa70hKkYZ5ajT2qjPFAD07bgqo10mlzqBHDx7B745iPbobatUpgqnmN0RwKe0tNHLe0X3nHY3uW9h8ztz91dH2CdiZhbj3dKbLwDmog9Qnf3CfbdP9_Uipp7av80zNOklur6FJz8kFRFXGBU5JUitJgPvpkwMVpFc3YA398y1gU60-LGTnk1nb9C6JcUri1xHBqvVZIDwf1HmmJSTYhq3dJGQZmveEN2l_8bAInttUcEgk0Z3Wlj6rx2B8AUzWiL8b3vyvBXtXhx4MAGts3gqnz5s5g_fqjx34b1hrItppGODNO-XTr0FJm9kWjUmuaEph9ajaqTzIXFCmwsIxx6QnyMrn5sOqvFusGLZuc-d64MwYhJrxhd2hRBoLbJMbMruedvskDw9m-jSXpLOwklZzv_pT6aOYwu0jQhG_jzxAS39NO7RV2kKjTVJSYQdmZ93qrh0I2fxclDKd63zacbJ7ocYO2NGqVf3soPlAG53XKx29jq6-OFjEyGPEK8ZlnPD4fMf94DStSotG-yFek0MtafmS7TuzAPePebQkTGQNIqfSMJv_hWrTxwq3AAjYgbLezSNbWttQ3W9M-eFIKlNOKUQFWIn3ROp2qSXnE69GwKX5hzpxyqqIHkxAl7udUz9apzj1z4FFGIsFpjBwfEK00bX6cTBd6Z9dBMUsJxpvX4Tt3WVyVwQss3SvsDC0ZuLenpkG0q0fuNGCZxFge4quboIErcT5IuZTEEYlIjDUETqEfBfPWViL-rw5Xq5C68KEp2DqaKNRfdLrlgabPHAv8zpe-8cDbu4JtvdTdMxZ6TPtY9NMa9WlBrNCc09vE9h64oAv2muQpVD_--6mNYi_NBxruzB0r7EBDp_IwNvWBy5q5sxuVM6dZsj3rIqf9xs3nq5--hu9tjK5F_puZg6TqQLba8QB4vWsnPJMjH9dv7g365OCO3H5jjTXAAh9Bno4vFyFD63Ptdfpn5KzwX9r4fjNBtMP9Nfkf7dNi-RwyyxueYMe7o__70ACf2x-CRb_RIZvqarzi9IvlS1NFnZ8w5K5bJIVh-0hHvh_wcHE_Yr9F0CK3v4rUjjzIN544Coa2CVIItK42TegUTppAc0P_GVhZzD7aIHpIBI89UFYIv2OJm7COkZxVUMH2lVOIYQ71fpeAFpV1_qq8s_QuUkK_8fjwWpGi8zP2XXkjobINzVhhLTxm8EzhlCFeg1ENsjOqsyQy1r_ePBVyw1IZ8g27z4Yx6g3itTwq5lVX278_cOl94BdoUIwlv0IDKpfsg2I4sOAVND3ZD_5_lPSzZiGl2Bjfo3ISaRHEbMWaHrqHKxS8RFuYKIorfDuNqnCaUAOMFEJDttlNxBKMhzM_Lu-ZEj-2GQIYWdLJS9x-_74SK0MqbaCiQDdo2O0RNXIHo15i4YFxUgw6nl-dqnbT868VlRL0HGoAVyJckbGwJzaX955dIcgJhn78FciOxp09BG4BgJeFqMmJ8psDGxbWBipPUACn2HbtbRk-x2OEjaZMq45UHTnJ_UmlI4yAZg37XGyifUViYhFbxfwXNNhLal2hrZar2fVf1MNcHmla4cby6h7CledqAczx3PwwDEk0VXJ8BUKtIAf_vHoS0U68RghtDFU6lOOTEM5rJvA28q1P7QQhF90k0W6lgRDinBcXpVU23ry-Jgyg9A1ljbSTjBErKC0reYxQYgPgr0U8luhKmAYcsFCfHr8uRuMw_N7krtW%26client_id%3D43ebcac1ac9940c0b66189eeed467da0

**Comment by MartaNowaczyk** [comment]
@XardasLord z tego co widzę problem generuje parametr state - wygląda na to, że jest za długi.
