### ISSUE TITLE
Allegro sandbox account API credentials 

### ISSUE THREAD

**Issue by andriusdum** [allegro/allegro-api#7891]
Hi,

I am trying to setup sandbox environment as company. I created account, and try to get API credentials , and as I understand first I need to turn on two-face authentification. I added app and then it asked code from SMS , I try LT and PL number, but I can not get confirmation code in any case. Can you help me with it?
Account name: andriusdumcius

Also do I need to fill other information to be able to use sandbox and test API integration?

**Comment by PrzemyslawLukanowski** [comment]
Hello, on the Sandbox environment it is not necessary to turn on two-factor authentification and also, we do not send codes via SMS - 123456 is used to enable two-factor authentification.

Your account is not activated right now, so you will not be able to list or manage offers via API. Please set up payouts via[ this tab](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat) and let me know after it's done (you don't need to enter a real bank account, all of the payments on Sandbox are processed via payment simulator).

**Comment by andriusdum** [comment]
Hello, 
thank you, I fill that data. Do I need do something more?

**Comment by PrzemyslawLukanowski** [comment]
That's all, I've just activated your account, you can start testing your integration.

**Comment by andriusdum** [comment]
thank you, and where can I find cient_id for API?

**Comment by PrzemyslawLukanowski** [comment]
You will get it after app registration on https://apps.developer.allegro.pl/.

**Comment by andriusdum** [comment]
yes, I got it. thank you.

I am closing this issue
