### ISSUE TITLE
Problem z typem przesyłki

### ISSUE THREAD

**Issue by pawelkucharskiyosi** [allegro/allegro-api#7892]
Proszę o informacje czy poniższy request nie powinien stworzyć przesyłki typu:

Allegro miniKurier24 InPost pobranie

Tworzy niestety typ Standard proszę o informacje dlaczego tak się dzieje Dane osobowe zagwiazdkowane, w rzeczywistym requeście były poprawne

Czy serviecId powinno być inne niż 98f86f81-0018-41c5-ac83-073a56fc7021#ac82656c-1450-4ef6-b2f9-e6977ceb1494?

poniżej request i respons

[request.txt](https://github.com/allegro/allegro-api/files/13222116/request.txt)

[respons.txt](https://github.com/allegro/allegro-api/files/13222117/respons.txt)

**Comment by Lukasz-Zurek** [comment]
@pawelkucharskiyosi Załączone przez Ciebie pliki są nieczytelne. Podaj proszę commandId, lub trace-id.
