### ISSUE TITLE
Endpoint GET /sale/products limit zapytań

### ISSUE THREAD

**Issue by SzymonZasada** [allegro/allegro-api#7893]
Cześć
Środowisko produkcyjne allegro endpoint GET /sale/products
Mam około 50 tys produktów i każdym numerem EAN z produktów strzelam  /sale/products. Problem jest taki iż wg dokumentacji limit to 1000tys zapytań na minutę, a w moim przypadku przez pierwsze 30s potrafię wywołać około 500 requestów, a następnie strasznie zwalnia- wtedy czekam od 3-5s na odpowiedz.  Można to jakoś pominąć? Robi sie jakas kolejka?

**Comment by Lukasz-Zurek** [comment]
Na wskazanym zasobie funkcjonuje dodatkowo tzw. Leaky Bucket - gdy przekroczysz dozwoloną liczbę wywołań na minutę (RPM), wydłużamy czas odpowiedzi.

Więcej informacji o naszych ograniczeniach znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#ograniczenie-liczby-zapytan-limity).

**Comment by SzymonZasada** [comment]
A mógłbym prosić o dozwoloną liczbę, ponieważ nigdzie jej nie umiem znaleźć, która określa ten zasób.

**Comment by Lukasz-Zurek** [comment]
@SzymonZasada Nie udostępniamy informacji o konkretnych limitach dla Leaky Bucket, ponieważ jest to wartość płynna.
