### ISSUE TITLE
Allegro sandbox aktywacja

### ISSUE THREAD

**Issue by SzymonZasada** [allegro/allegro-api#7894]
Nie umiem zrobić aktywacji na allegro sanbox, podaje wszystko itp ale nic z tego
![image](https://github.com/allegro/allegro-api/assets/84040786/a2e0914f-bc63-4731-88a7-b16e12ca6594)
Mogę prosić o ręczna aktywacje
Nazwa konta: motor-expert

**Comment by Lukasz-Zurek** [comment]
@SzymonZasada Musisz jeszcze przejść przez konfigurację [ustawień wypłat](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat), by na końcu skorzystać również z symulatora płatności. Po wykonaniu tych czynności - daj proszę znać, a wykonam aktywację ręcznie.

**Comment by SzymonZasada** [comment]
@Lukasz-Zurek zobacz teraz, nic wiec nie dam rady zrobić ponieważ aktywacja rachunku bankowego(oraz przelew) nie przechodzi i nie wiem dlaczego.

**Comment by Lukasz-Zurek** [comment]
@SzymonZasada Udało się aktywować konto. Możesz już korzystać :)

**Comment by enzonzee** [comment]
Proszę o aktywację. Konto: adrian6228

**Comment by PrzemyslawLukanowski** [comment]
@enzonzee Aktywowałem Twoje konto.

**Comment by dkaczor97** [comment]
Proszę o aktywację konta dawidkaczor97

**Comment by Lukasz-Zurek** [comment]
@dkaczor97 Aktywowałem Twoje konto.

**Comment by AndriiZe** [comment]
Proszę o aktywację mojego konta allegrosandbox: AndriiTest. Nie mogę przejść etapu weryfikacji konta bankowego. Wyjaśnij, jak to zrobić i jak korzystać z symulatora płatności

**Comment by MatyskaMiroslav** [comment]
Proszę o aktywację konta allegrosandbox: Matyska
Nie można utworzyć ofert do testów. Dziękuję.

**Comment by AndriiZe** [comment]
Aby zweryfikować swoje konto, musisz podać i potwierdzić swoje konto bankowe. Jak to zrobić w piaskownicy allegrosandbox

**Comment by Lukasz-Zurek** [comment]
@AndriiZe Musisz wypełnić wszystkie dane na stronie [ustawień wypłat](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat) - zalecam użycie danych fikcyjnych, np. numer rachunku bankowego możesz wygenerować korzystając z generatora tego typu danych, dostępnego w internecie.

Natomiast po wypełnieniu powyższego formularza, wybierasz opcję "szybki przelew online", a następnie klikasz w "Zrób przelew online" i akceptujesz płatność w symulatorze płatności. Nie wykonujesz realnej płatności z uwagi na to, że jest to środowisko testowe.

**Comment by Lukasz-Zurek** [comment]
@MatyskaMiroslav Aktywowałem wskazane przez Ciebie konto.

**Comment by AndriiZe** [comment]
![rr1](https://github.com/allegro/allegro-api/assets/149830295/6e9445c5-4359-4555-8f75-0f4165e845b7)
Wygenerowałem testowy IBAN, próbowałem go sprawdzić, nie zostałem dopuszczony do szybkiego czeku, wybrałem zwykły czek. Zabierz mnie z powrotem, aby zmienić IBAN

**Comment by Lukasz-Zurek** [comment]
@AndriiZe Aktywowałem Twoje konto.

**Comment by Rikko28** [comment]
hello, please help.https://github.com/allegro/allegro-api/issues/7947#issue-1987515574

**Comment by Lukasz-Zurek** [comment]
@Rikko28 I have already helped you in https://github.com/allegro/allegro-api/issues/7947#issue-1987515574.

**Comment by Streyl** [comment]
Czy mógłbym poprosić o aktywacje konta? Konto jest firmowe
![obraz](https://github.com/allegro/allegro-api/assets/43100007/6264c522-7c1a-4f4b-bac3-dfaf44ec8140)

login: Oleksandr
mail: okazanzhy@media4u.pl

**Comment by Streyl** [comment]
> @Streyl Twoje konto jest już aktywne.

Dziękuję bardzo.
