### ISSUE TITLE
Is there an interface for bulk product editing?

### ISSUE THREAD

**Issue by yangsheng8** [allegro/allegro-api#7895]
Hello, I'm currently trying to use the PATCH sale/product-offers/{offerId} request to modify product parameters. However, due to frequent requests, the interface stops responding. Additionally, individual modification operations are also slow. Is there a more effective way to bulk edit parameters such as product prices, inventory, and availability status?

**Comment by Lukasz-Zurek** [comment]
I am not sure how many requests are you making, but please remember that we also use the Leaky Bucket algorithm. If you exceed the number of requests per minute (RPM), the response time is extended.

**Comment by yangsheng8** [comment]
> I am not sure how many requests are you making, but please remember that we also use the Leaky Bucket algorithm. If you exceed the number of requests per minute (RPM), the response time is extended.

Currently, we limit the requests to approximately 60 per minute.
We have 30 accounts, each with roughly 20,000 products, and we need to adjust prices, stock, or set the status to "ENDED" daily.
Because the script runs for an extended period, it often stops running, requiring us to restart it frequently.

**Comment by Lukasz-Zurek** [comment]
You have asked about bulk resource and you can use our resources which we described [here](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#editing-many-offers). 
In a single call you can edit up to 1000 offers. So hopefully it will be effective for your application and our API as well.
