### ISSUE TITLE
API whole Category tree.

### ISSUE THREAD

**Issue by barbasfilip** [allegro/allegro-api#7897]
hello, 
we have some difficulties with uploading products via API. There is sorting by categories/subcategories needed, but we do not have access to whole Category tree.  Can you help us, how we can get the list of categories/subcategories on Allegro?

When I call this https://api.{environment}/sale/categories a get only main categories, but we need whole tree
Thank you

**Comment by Lukasz-Zurek** [comment]
You won't retrieve the entire category tree via the API, but you can retrieve categories using [GET /sale/categories](https://developer.allegro.pl/documentation/#tag/Categories-and-parameters) and drill down into lower-level categories using the **parent.id** parameter.

For example, you send a request: **GET sale/categories?parent.id=165**, select the subcategories for which you would like to get lower categories, e.g. **4937** (**GET sale/categories?parent.id=4937**). Therefore, this way you will be able to get all the information. You don't need the shortest child's ID. You only need **parent.id**, thanks to which you get all the lists of lower categories, in order, according to the above diagram.
