### ISSUE TITLE
Jak sprawdzić z czego wynika różnica w cenie na stronie www i w /sale/product-offers?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#7898]
/sale/product-offers zwraca ofertę z ceną 108.98. Na stronie www cena oferty dla kupującego to 91.18. 
trace-id: b660282580c414d5

/sale/badges dla oferty zwraca pustą tablicę.

Jak należy uzyskać informację przez REST API aby dowiedzieć się z czego wynika różnica w cenie?

**Comment by Lukasz-Zurek** [comment]
Oferta ze wskazanego trace-id posiada ["Gwarancję najniższej ceny"](https://allegro.pl/pomoc/dla-sprzedajacych/promowanie-ofert/co-znaczy-gwarancja-najnizszej-ceny-przy-twojej-ofercie-m01D3l6g2UY). Konsultuję obecnie kwestię zwracania tej niższej ceny w API. Proszę o cierpliwość.

**Comment by tomylee0** [comment]
Głównie zależy mi na tym abym mógł przez REST API sprawdzić **czy konkretna oferta bierze aktualnie udział** w "Gwarancji najniższej ceny" lub "Allegro ceny" lub innym programie, który powoduje, że cena widoczna dla kupującego będzie inna niż ta w GET /sale/product-offers.

**Comment by Lukasz-Zurek** [comment]
@tomylee0 Ok. Z dostępnych mi danych wynika, że takiej możliwości nie ma, ale dopytuję jeszcze zespołu odpowiedzialnego za kampanie promocyjne, a konkretnie za "gwarancję najniższej ceny". Proces zgłaszania ofert w tym przypadku różni się od pozostałych. Jak tylko uzyskam szczegółowe informacje - wrócę w wątku.

**Comment by Lukasz-Zurek** [comment]
@tomylee0 Otrzymałem potwierdzenie, że nie udostępniamy informacji o "Gwarancji najniższej ceny" i o niższej cenie dla oferty ze wspomnianym oznaczeniem w Allegro API.

Zachęcam Cię do przesłania propozycji/uzupełnienia sugestii w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions), dzięki czemu również inni użytkownicy będą mogli oddać swój głos.
