### ISSUE TITLE
swagger.yaml DescriptionSectionItem brakujący `discriminator.mapping` oraz `properties`

### ISSUE THREAD

**Issue by netfarma** [allegro/allegro-api#790]
Witam.
Wydaje mi się, że `DescriptionSectionItem` ma niepełną definicję. Patrząc na zapis `CategoryParameter` to wg mnie brakuje tu `mapping` oraz `properties`.

Korzystam z https://github.com/OpenAPITools/openapi-generator i brak tych elementów powoduje wygenerowanie niepełnych modeli.

Poprzez API w type otrzymujemy `TEXT` lub `IMAGE` więc mapping powinien być.
Patrząc się na `CategoryParameter` czy sekcja `DescriptionSectionItem` nie powinna wyglądać tak?

```   
  DescriptionSectionItem:
      type: object
      description: 'One of: TextItem, ImageItem'
      oneOf:
        - $ref: '#/components/schemas/DescriptionSectionItemText'
        - $ref: '#/components/schemas/DescriptionSectionItemImage'
      discriminator:
        propertyName: type
        mapping:
          TEXT: '#/components/schemas/DescriptionSectionItemText'
          IMAGE: '#/components/schemas/DescriptionSectionItemImage'
      required:
        - type
      properties:
        type:
          type: string
          example: 'TEXT, IMAGE'
```

Po tej poprawce wygenerowany kod jest już OK

**Comment by PawelTaberski** [comment]
@netfarma uzupełniliśmy, dziękujemy jeszcze raz za zwrócenie uwagi.

**Comment by PawelTaberski** [comment]
Dziękujemy za sugestię, możliwe że i również te zmiany wdrożymy. Przekazałem Twoje pomysły do odpowiedniego zespołu.

**Comment by PawelTaberski** [comment]
@netfarma Wdrożyliśmy zaproponowaną przez Ciebie zmianę :-)
