### ISSUE TITLE
Błąd przy aktualizacji ceny produktu

### ISSUE THREAD

**Issue by kacperKarman** [allegro/allegro-api#7900]
Dzień dobry, mam problem z aktualizacją ceny produktu z wykorzystaniem zasobu PATCH /sale/product-offers/:productId. Problem występuje tylko przy niektórych aukcjach, mimo że mechanizm zawsze działa tak samo - pobieram dane produktu endpointem GET /sale/product-offers/:productId, następnie w danych zmieniam tylko cenę i przesyłam ten obiekt w body w endpointcie PATCH /sale/product-offers/:productId. 

Dla aukcji o numerze 14011830978 przy próbie aktualizacji otrzymuję taki obiekt z błędem: 
{
    "errors": [
        {
            "code": "JsonMappingException",
            "message": "Message is not readable.",
            "details": null,
            "path": "compatibilityList.items[0].type",
            "userMessage": "Request contains invalid data. Contact the application author."
        }
    ]
}

Lista compatibilityList w obiekcie który otrzymuję podczas pobierania szczegółów aukcji wygląda w ten sposób (nic z niej nie usuwam, ani nie dodaje): 
"compatibilityList": {
        "type": "PRODUCT_BASED",
        "items": [
            {
                "text": "Motorola Moto E13"
            }
        ]
    },

**Comment by PrzemyslawLukanowski** [comment]
Uwzględnij proszę w requeście wyłącznie pole, w którym wykonujesz zmianę, czyli np. `sellingMode`. Możesz także po prostu usunąć sekcję `compatibilityList` - wtedy i tak podłączymy ją do produktu, ponieważ zadzieje się to automatycznie ze względu na obecność pola `product.id` i zawarty w nim produkt.

**Comment by kacperKarman** [comment]
Dziękuję za pomoc.
