### ISSUE TITLE
Category selection

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#7902]
Hi there, 

we are now doing research into how to allow the creation of a new product card via our app and we were wondering, if it is possible to somehow request a list of all available categories (and subcategories) on Allegro, so that the customer can always choose from up to date selection of categories. 

Thank you in advance! 

Best, 

Dominika

**Comment by PrzemyslawLukanowski** [comment]
Hi, yes, it is possible. We received a similar question today - please check the #7897 thread.
