### ISSUE TITLE
Zmiana chodliwości oferty.

### ISSUE THREAD

**Issue by PiotrSzymala** [allegro/allegro-api#7903]
Dzień dobry, mamy problem z produktem GALINA/TUV, czas realizacji zmienił się na 60 dni, podczas gdy powinien być ustawiony jeden dzień. Klient twierdzi, że nie zostało to zmienione ręcznie. Link do oferty: https://allegro.pl/oferta/biokominek-galina-wolnostojacy-szyba-bezpieczny-14309676668 (obecnie czas realizacji został przywrócony ręcznie na 1 dzień). Czy jest możliwe, że Allegro zmieniło automatycznie czas realizacji? Z naszej strony w kodzie nie znalezliśmy żadnego błędu.

**Comment by Lukasz-Zurek** [comment]
Taką zmianę odnotowaliśmy 2023-10-31 13:35:13 za pośrednictwem API, a konkretnie aplikacji o nazwie "Kratki".
