### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by Yupik** [allegro/allegro-api#7904]
Cześć,

Prosiłbym o aktywację konta sandbox z loginem: linker-test

Obecnie nie jestem w stanie już przejść dalej:
![image](https://github.com/allegro/allegro-api/assets/11853871/5ba29802-6c37-4d0f-b9dd-1d3d8e8298aa)

Ponawianie przelewu nic nie daje :)

**Comment by Lukasz-Zurek** [comment]
@Yupik Aktywowałem już i zweryfikowałem Twoje konto. Powinno być ok.

**Comment by Yupik** [comment]
@Lukasz-Zurek świetnie, potwierdzam, już wszystko okej, dzięki piękne!
