### ISSUE TITLE
PROCESSING_ERROR

### ISSUE THREAD

**Issue by lhascilo** [allegro/allegro-api#7905]
Dzień dobry,

Dziś napotkałem na błąd podczas wysyłki. 

`allegro_errors":[{"code":"PROCESSING_ERROR","message":"Problem with dispatch. Contact us, and we will help as soon as possible.","details":null,"path":"","userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}]}"`

Czy mogę prosić o informację czym jest on spowodowany ? Nie ma podanego konkretnej przyczyny oraz miejsca gdzie trzeba się zgłosić.

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, podaj proszę trace ID lub command ID operacji powiązanej z tym błędem.

**Comment by lhascilo** [comment]
Rozumiem, że chodzi o request ID ? x-request-id: b6fd8084-ba7e-46ed-9e7b-c4f563b3c39d

**Comment by PrzemyslawLukanowski** [comment]
Nie do końca, trace-id zwracamy w nagłówkach odpowiedzi, natomiast commandID w odpowiedzi na próbę utworzenia paczki - jest to wartość, którą wskazujesz, gdy odpytujesz o status przesyłki za pomocą [GET /shipment-management/shipments/create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/getShipmentCreationStatus). W wskazanym request-id niestety nie udało mi się zlokalizować żadnej próby.

**Comment by lhascilo** [comment]
W response w headersie mam takie wartości:

"response_headers_string" => "HTTP/2 200 
server: nginx/1.18.0 (Ubuntu)
date: Tue, 31 Oct 2023 06:42:11 GMT
content-type: application/json; charset=utf-8
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
etag: W/"92836537600a279f80ca941fa33db324"
cache-control: max-age=0, private, must-revalidate
x-request-id: b6fd8084-ba7e-46ed-9e7b-c4f563b3c39d
x-runtime: 0.134871

**Comment by PrzemyslawLukanowski** [comment]
Prosiłbym w takim razie o commandId, które odpytujesz na zasobie [/shipment-management/shipments/create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/getShipmentCreationStatus).

**Comment by lhascilo** [comment]
Nie ja jestem autorem tego rozwiązaniania i nistetety nie wiem jaki command ID został uzyty. Podeślę jeszcze jedno ID jakie mam w logachb w response. Mam nadzieje, ze to będzie prawidłowe:
 "response_string" => "{"uuid":"27634706-cb7a-40fd-add8-c7c4527325d7","status":1}"

**Comment by PrzemyslawLukanowski** [comment]
Tak, to wystarczy, dziękuję. Analizujemy ten przypadek, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Był to chwilowy błąd związany z kontem użytkownika, nie powinien już występować. Prosiłbym o ponowienie requestów.

**Comment by lhascilo** [comment]
Dziękuję bardzo,

Czy moge prosic jeszcze o analizę dla zamówień:
"uuid":"fdca9166-1d7e-40fc-91a4-1bc351c39bd1","status":1}
"uuid":"dbe913e7-092f-484b-94cc-31b06ba77340","status":1}"
"uuid":"8b19addc-8272-4338-a3b5-b574921bb1c4","status":1}

 ?

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku problem również jest powiązany z kontem użytkownika, jednak widzę, że te requesty pochodzą z 03.11.23. Czy problem występuje także obecnie?

**Comment by lhascilo** [comment]
Nie mam takiej, wiedzy. W dniu 03.11.2023 nie powiodła się wysyłka. dostałem zgłoszenie od klienta, a w logach mam jedynie błąd: "PROCESSING_ERROR". Rozumiem, że powinniśmy dziś ponowić wysyłkę ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, proszę o ponowienie.

**Comment by kdabek** [comment]
Dołączę do pytania ponieważ otrzymuję identyczny komunikat, przy próbie pobrania statusu anulowania przesyłki `GET` [https://api.allegro.pl.allegrosandbox.pl/shipment-management/shipments/cancel-commands/](https://api.allegro.pl.allegrosandbox.pl/shipment-management/shipments/cancel-commands/)

Trace-id: fd9b41b84079b94a

Dodam że request `POST` działa poprawnie i tam nie otrzymuję błędu, dopiero próba odczytania statusu kończy się błędem.

**Comment by PrzemyslawLukanowski** [comment]
@kdabek W tym przypadku powodem takiej odpowiedzi jest to, że nie można anulować przesyłki u przewoźnika Allegro.

**Comment by kdabek** [comment]
> @kdabek W tym przypadku powodem takiej odpowiedzi jest to, że nie można anulować przesyłki u przewoźnika Allegro.

Dziękuję, w takim razie przydałby się stosowniejszy komunikat informujący o tym fakcie ;)

**Comment by PrzemyslawLukanowski** [comment]
To prawda :) Na bieżąco staramy się mapować błędy od przewoźników.
