### ISSUE TITLE
Dziwny błąd związany z Współpraca w Ochronie Praw

### ISSUE THREAD

**Issue by jezewskiBNetrox** [allegro/allegro-api#7909]
Witam,

mam problem z próbą wystawienia pewnej aukcji, mianowicie wyskakuje mi ten błąd:

```
Tytuł Twojej oferty lub jej dalszy opis może wprowadzać w błąd co do pochodzenia towaru, 
jego producenta lub marki i tym samym naruszać prawa firmy, która współpracuje z nami w
ramach programu Współpraca w Ochronie Praw. W opisie Twoich ofert używasz zarejestrowanego
słownego znaku towarowego w celu sprzedaży produktu innej marki (widocznej w sekcji ‘Parametry’).
```

I nie, żebym tego błędu nie znał bo zdarza się, kiedy faktycznie zachodzi różnica pomiędzy parametrem Marka a treścią opisu, to tutaj nie rozumiem. Zarówno w opisie jak i w Marka podany jest "Skechers", prosto z listy wartości parametru.

Trace-Id: **a34ef96b12a5266b**

Proszę o zweryfikowanie, dlaczego tutaj ten błąd występuje.
Pozdrawiam serdecznie.

**Comment by PrzemyslawLukanowski** [comment]
Witam, widzę, że w parametrze `Marka` przesyłasz:

```
        {
            "id": "7108",
            "valuesIds": [
                "7108_60"
            ],
            "values": null,
            "rangeValue": null
        }
```

Pod tym ID kryje się `"Vans"`, natomiast `"Skechers"` to `7108_65`

**Comment by jezewskiBNetrox** [comment]
@PrzemyslawLukanowski Dzięki, znalazłem buga po swojej stronie. Zamykam i dziękuję za pomoc.

**Comment by jezewskiBNetrox** [comment]
> Witam, widzę, że w parametrze `Marka` przesyłasz:
> 
> ```
>         {
>             "id": "7108",
>             "valuesIds": [
>                 "7108_60"
>             ],
>             "values": null,
>             "rangeValue": null
>         }
> ```
> 
> Pod tym ID kryje się `"Vans"`, natomiast `"Skechers"` to `7108_65`

@PrzemyslawLukanowski Odkopię temat, ponieważ jak się okazuje problem nie występował tam, gdzie myślałem. Nie przesyłałem Vans. Przesyłałem Skechers. Produkt w katalogu miał markę Vans, więc cokolwiek wpisałem w markę jako parametr nie miało znaczenia, bo API sobie te dane samo podmieniało gdzieś w tle bez mojej ingerencji.

**Comment by jezewskiBNetrox** [comment]
@PrzemyslawLukanowski I jeszcze jedno, dlaczego pozwalacie aby niezgodny z błędem:

```
Tytuł Twojej oferty lub jej dalszy opis może wprowadzać w błąd co do pochodzenia towaru, jego producenta lub marki i tym samym naruszać prawa firmy, która współpracuje z nami w ramach programu Współpraca w Ochronie Praw. W opisie Twoich ofert używasz zarejestrowanego słownego znaku towarowego w celu sprzedaży produktu innej marki.
```

produkt w ogóle zaistniał? Nie rozumiem tego. Mogę stworzyć produkt, nazwać go NIke, dać w opisie Nike ale podać markę w parametrach "Puma". A system sobie tworzy jakiś alternatywny tytuł a opisu nie zmienia. Jest to cholernie wadliwe. 

Z kolei mam też inne pytanie, czy na nowych zasobach ten problem jest wyeliminowany? Rozumiem, że skoro tworzenie produktu i oferty jest powiązane to walidacja wyrzuci takiej propozycji błąd?

**Comment by PrzemyslawLukanowski** [comment]
Według naszych logów skorzystałeś z POST /sale/offers, w tym zasobie nie uzupełniamy automatycznie parametrów. Jako [product.id](http://product.id/) wskazałeś 8a097091-080b-44b4-a728-cc5144560908 (Vans Buty męskie sportowe Old Shool r. 38) i aplikacja sama dostarczyła nam parametry produktu, w tym parametr 7108 wraz z wartością Vans oraz opis. W opisie rzeczywiście występuje rozbieżność - użyte są zdjęcia butów Skechers oraz pada nazwa tej marki. W takim przypadku możesz zgłosić błąd za pomocą [formularza zgłaszania błędów](https://allegro.pl/moje-allegro/sprzedaz/produkt/zglos-blad/8a097091-080b-44b4-a728-cc5144560908) lub [za pomocą API](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-zglosic-blad-w-produkcie).

Dodam, że na bieżąco staramy się usuwać nieprawidłowe produkty oraz zmiany. Co do Twojego ostatniego pytania - ta walidacja jest asynchroniczna, dlatego nie odpowiemy od razu błędem.
