### ISSUE TITLE
Internal server error dla doGetBidItem2

### ISSUE THREAD

**Issue by mkosiek** [allegro/allegro-api#791]
Witam,
Metoda doGetBidItem2 zwraca poniższy błąd dla aukcji 5789427826 (błąd jest powtarzalny):

Typ zawartości text/html;charset=UTF-8 komunikatu odpowiedzi nie zgadza się z typem zawartości powiązania (text/xml; charset=utf-8). Jeśli używasz niestandardowego kodera, upewnij się, czy metoda IsContentTypeSupported jest zaimplementowana poprawnie. Pierwsze 0 bajtów odpowiedzi to: „”.

Błąd wewnętrzny:
Serwer zdalny zwrócił błąd: (500) Wewnętrzny błąd serwera.

**Comment by PawelTaberski** [comment]
Sprawdziłem i oferta jest dosyć stara i ma sporo ofert, jednakże udało mi się pobrać dane przy pomocy metody o której wspominasz. Sprawdź, czy nie ma na swoim serwerze nałożonych jakiś limitów na czas odpowiedzi bądź jej wielkość. Gdyż ja doczekałem się odpowiedzi po 20371ms i miała wielkość 8841989 bytes.

**Comment by mkosiek** [comment]
Podbiłem czas i wielkość odpowiedzi do max, ale nie dało to efektu. Mam kilka takich aukcji, dla których otrzymuję odpowiedź 500 i za każdym razem odpowiedź wraca po 30 sekundach. Próbowałem też zdziałać coś poprzez SOAP UI, ale efekt jest taki sam. 
Czy po Waszej stronie jest limit czasowy na 30 sekund? 
Zauważyłem też, że dla jednej z aukcji, dla której nie dostałem wcześniej odpowiedzi, teraz udało mi się ją uzyskać po 27 sekundach

**Comment by TimothyKoval** [comment]
Korzystasz z https://webapi.allegro.pl/uploader.php?wsdl czy https://webapi.allegro.pl/service.php?wsdl ?

**Comment by mkosiek** [comment]
Z uploader

**Comment by mkosiek** [comment]
Podmieniłem na Service.php i już się wyrabia. Zamykam zgłoszenie. Dzięki
