### ISSUE TITLE
DELIVERY_METHOD_NOT_AVAILABLE

### ISSUE THREAD

**Issue by jpulkiewicz** [allegro/allegro-api#7910]
Dzien dobry,
W api produkcyjnym dla endpoint https://api.allegro.pl/parcel-management/parcel-create-commands/*** otrzymuje blad 

[{"code":"DELIVERY_METHOD_NOT_AVAILABLE","message":"Delivery Method is not available for this order","details":"Delivery Method is not available for this order","path":"/serviceId","userMessage":"Wybrana metoda dostawy nie obsługuje tego zamówienia"}]

Prosze o wskazanie przyczyny bledu

Trace id z response jest nast.
 trace-id: 2b15e42701375eaf

Pozdrawiam
Jaroslaw Pulkiewicz

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, kupujący wybrał metodę dostawy Kurier DPD o id c3066682-97a3-42fe-9eb5-9bb2978cf293, natomiast próba nadania przesyłki następuje na usłudze Allegro Kurier DPD o id c3066682-97a3-42fe-9eb5-3beeccab840c. Te dane się różnią, stąd wspomniany w zgłoszeniu komunikat błędu.

**Comment by PrzemyslawLukanowski** [comment]
Nie zwrócimy tej usługi, [zgodnie z artykułem](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/wysylam-z-allegro-narzedzie-do-nadawania-przesylek-bezposrednio-z-konta-E7doGw8VgI1) Wysyłam z Allegro nie obejmuje wysyłek za pomocą metody dostawy "Kurier DPD".

**Comment by jpulkiewicz** [comment]
Dziekuje za odpowiedz.
