### ISSUE TITLE
Problem z wystawianiem produktu

### ISSUE THREAD

**Issue by Dawid-IziGSM** [allegro/allegro-api#7911]
Chcąc wystawić nowy  produkt za pomocą API sprawdzamy bazę Allegro po EAN i otrzymujemy informacje, że nie ma takiego produktu (GET /sale/products). Gdy chcemy go stworzyć (POST /sale/product-offers ) dostajemy komunikat błędu, że istnieje taki produkt i jest wskazywany inny produkt z innym ean i modelem ale tym samym zdjęciem.  W ofercie mamy kilkadziesiąt produktów ( takie samo etui na różne modele telefonów) o różnych EAN ale tym samym poglądowym zdjęciem. Chodzi mi tu o etui na telefon. Dystrybutor dostarcza tylko takie same zdjęcia do różnych modeli telefonów tego samego pokrowca. Wcześniej takiego problemu nie było. Jak rozwiązać taką sytuację?

(
[code] => PARAMETER_MISMATCH
[message] => The provided parameter 'Dedykowany model'(219781) value (Moto G54 5G) does not match the existing parameter value (Moto G84 5G)
[details] => 
[path] => productSet[0].product.parameters
[userMessage] => Wskazany produkt istnieje. Przesłany parametr `Dedykowany model` o wartości `Moto G54 5G` nie pasuje do parametru produktu `Moto G84 5G`.
)

Produkty do Moto G54 5G i Moto G84 5G to dwa różne produkty. Z różnymi EAN do różnych modeli telefonów. Jedyne co je łączy to takie same zdjęcia jakimi dysponujemy.

**Comment by PrzemyslawLukanowski** [comment]
Podaj proszę trace-id operacji powiązanej z tym komunikatem błędu.
