### ISSUE TITLE
ERROR NOT_SELLER_ORDER 

### ISSUE THREAD

**Issue by pawelignatowski** [allegro/allegro-api#7913]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [ x] ze środowiskiem produkcyjnym / with the production environment
 - [ ?] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy próbie wysłania komunikatu 
/parcel-management/parcel-create-commands/

Otrzymuje komunikat:
__ERROR NOT_SELLER_ORDER 
Order doesn't belong to seller receiver.email 
Nie jesteś właścicielem zamówienia__

Natomiast mam pewność, że jest to zamówienie z tego konta. Co ciekawe importując zamówienie do BaseLinkera otrzymuje etykietę UPS, a nie Allegro One. Co robię nie tak?

Ciekawe, że na koncie innego klienta ta sama usługa (ten sam guid 0aafb43c-e66a-46ec-9cc4-29bb39ebb483) i działa. Otrzymuje etykietę Allegro One.

Czy coś jeszcze musi być spełnione? Na przykład adres e-mail nadawcy/punktu odbioru??

Problematyczne zapytanie:
{
    "serviceId": "0aafb43c-e66a-46ec-9cc4-29bb39ebb483",
    "receiver": {
        "address": {
            "street": "K.kierzkowskiego 5a/2 0",
            "postCode": "30-433",
            "city": "Kraków",
            "countryCode": "PL"
        },
        "email": "texfwi9f9z+5ac509b60@allegromail.pl",
        "name": "Katarzyna Bukowiec Katarzyna B",
        "company": "Katarzyna Bukowiec Katarzyna B",
        "phone": "508442756",
        "pointId": "AL173KR1"
    },
    "pickup": {
        "address": {
            "street": "Logistyczna",
            "postCode": "05-250",
            "city": "Ciemne",
            "countryCode": "PL"
        },
        "email": "sklep@apetete.pl",
        "name": "Apetete  Magazyn Arteria Logis",
        "company": "Apetete  Magazyn Arteria Logistics ",
        "phone": "799 350 907",
        "pointId": null
    },
    "items": [
        {
            "weight": {
                "value": "0.4",
                "unit": "KILOGRAM"
            },
            "dimensions": {
                "height": {
                    "value": "38",
                    "unit": "CENTIMETER"
                },
                "width": {
                    "value": "64",
                    "unit": "CENTIMETER"
                },
                "depth": {
                    "value": "19",
                    "unit": "CENTIMETER"
                }
            },
            "type": "PACKAGE",
            "description": "EAN:4011905236414 ",
            "value": null
        }
    ],
    "type": "PACKAGE",
    "label": {
        "sender": null,
        "fileFormat": "PDF",
        "referenceNumber": "4011905236414 "
    },
    "additionalServices": null
}

Poprawny komunikat na Allegro One z innego środowiska/innego klienta:
{
    "serviceId": "0b9bed2c-0bc1-4e1f-9694-29bb39ebb483",
    "receiver": {
        "address": {
            "street": "Konfederacka 15 0",
            "postCode": "32-020",
            "city": "Kraków",
            "countryCode": "PL"
        },
        "email": "jnd905djmq+7b4e92630@allegromail.pl",
        "name": "Antoni Pirowski Antoni Pirowsk",
        "company": "Antoni Pirowski Antoni Pirowsk",
        "phone": "508597054",
        "pointId": "AL404KR1"
    },
    "pickup": {
        "address": {
            "street": "Annopol 17A rampa 10-11",
            "postCode": "03-236",
            "city": "Warszawa",
            "countryCode": "PL"
        },
        "email": "jnd905djmq+7b4e92630@allegromail.pl",
        "name": "RUCH S.A. Magazyn ColdSea ",
        "company": "ColdSea              ",
        "phone": "504075405",
        "pointId": null
    },
    "items": [
        {
            "weight": {
                "value": "1",
                "unit": "KILOGRAM"
            },
            "dimensions": {
                "height": {
                    "value": "38",
                    "unit": "CENTIMETER"
                },
                "width": {
                    "value": "64",
                    "unit": "CENTIMETER"
                },
                "depth": {
                    "value": "19",
                    "unit": "CENTIMETER"
                }
            },
            "type": "PACKAGE",
            "description": "150446498",
            "value": null
        }
    ],
    "type": "PACKAGE",
    "label": {
        "sender": null,
        "fileFormat": "PDF",
        "referenceNumber": "B"
    },
    "additionalServices": null
}

**Comment by thefoe76** [comment]
Może to jest zamówienie to punktu? id: 08c15d0b-9b24-4b3f-89a8-7a2b502abe55
w przypadku PUNKT i BOX etykieta będzie UPC. 
poza tym parcel-management jest wycofywany. 
https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY

**Comment by Lukasz-Zurek** [comment]
@pawelignatowski We wskazanych dwóch zamówieniach - Kupujący wybrali różne opcje dostawy, stąd pewne różnice.

Adres e-mail: [texfwi9f9z+5ac509b60@allegromail.pl](mailto:texfwi9f9z+5ac509b60@allegromail.pl) odnosi się do zamówienia, w którym Kupujący wybrał "Allegro One Box". W tej sytuacji Sprzedający otrzymuje etykietę UPS.

Dodam, że próbujesz utworzyć tę przesyłkę będąc autoryzowanym na innym koncie - a powinieneś być autoryzowanym na koncie Sprzedawcy, którego dotyczy to zamówienie.

**Comment by pawelignatowski** [comment]
> 08c15d0b-9b24-4b3f-89a8-7a2b502abe55

Próbowałem różnych metod w nadziei, że to baseLinker lub Magento zniekształcają dane. Zmiana na powyższy ID nie dała rezultatu.
Tak samo jak 0aafb43c-e66a-46ec-9cc4-29bb39ebb483, 
0b9bed2c-0bc1-4e1f-9694-29bb39ebb483, 
0ee3467f-5451-4060-856e-7a2b502abe55

**Comment by pawelignatowski** [comment]
> Allegro One Box

Oczywiście, że chodzi o niezrozumiały dla mnie komunikat o złym nadawcy. Klient ma trzy aktywne konta. 

apetete_pl - allegro.apetete_pl@apetete.pl
apetete - allegro.apetete@apetete.pl
Koema - kontakt@koema.pl

Próbowałem na wszystkich z nich. Zawsze ten sam komunikat.

Co do kodów spedytorów to przyzwyczaiłem się że końcówka GUID-a jest najczęściej wystarczająca do identyfikacji. Tu widzę, że końcówka jest taka sama, a w środku wartości są różne. Ciekawe. Mój błąd.
Wydaje mi się, że nie sprawdził Pan i konto "z poprawnym komunikatem" powoływało się na taki rodzaj usługi że otrzymałem etykietę allegroOne, a nie UPS. Mam tą etykietę przed sobą. :)

Wydaje się jednak, że zwracany jest tylko pierwszy błąd i nie w tym problem jaki to rodzaj spedytora. Losowałem już różne wartości i zawsze zatrzymuje się na właścicielu.

Raczej chodzi o konto !? Co z nim jest nie tak? Dlaczego w BaseLinker działa?

**Comment by pawelignatowski** [comment]
> Może to jest zamówienie to punktu? id: 08c15d0b-9b24-4b3f-89a8-7a2b502abe55 w przypadku PUNKT i BOX etykieta będzie UPC. poza tym parcel-management jest wycofywany. https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY



> poza tym parcel-management jest wycofywany.

Dzięki za podpowiedź, ale w przypływie rozpaczy zmieniłem moje działają API na wywoływanie nowych metod w API Allegro. Efekt dokładnie ten sam.

Metody raczej nie są wycofane, ale nie będą rozwijane. Wycofane będą najwcześniej za rok. Jak znam usługi INPOST to tak samo jak  stare API trzymało się lata po wdrożeniu obecnego tak i API Allegro może być dostępne znacznie dłużej.

Zobaczymy czy Allegro chce współpracować z Partnerami jak Microsoft czy jest samolubem na swoim podwórku jak Apple.

**Comment by pawelignatowski** [comment]
> przesyłkę będąc autoryzowanym na innym koncie

Panie Łukaszu
kilkaset jak nie kilka tysięcy zamówień w ciągu tygodnia klient klika ręcznie. Proszę o pilne rozpatrzenie problemu.

**Comment by Lukasz-Zurek** [comment]
@pawelignatowski Konsultuję ten problem z zespołem odpowiedzialnym za usługę "Wysyłam z Allegro".

**Comment by Lukasz-Zurek** [comment]
@pawelignatowski Prześlij proszę trace-id, lub commandId odnoszący się do problemu:

```
ERROR NOT_SELLER_ORDER
Order doesn't belong to seller receiver.email
```

**Comment by pawelignatowski** [comment]
[AllegroOne Nie moje.xlsx](https://github.com/allegro/allegro-api/files/13279006/AllegroOne.Nie.moje.xlsx)

Przesyłam plik Excel z na prędko sporządzonym logiem z komunikatami. W tym przypadku mieliśmy 3ca9982b-072e-491a-b721-c4026b55846f i klient twierdzi że to konto Apetete.pl

**Comment by Lukasz-Zurek** [comment]
@pawelignatowski Zamówienie pochodzi z konta apetete_pl, natomiast próbujesz nadać przesyłkę będąc zautoryzowanym na koncie apetete. W związku z czym przyczyna będzie jednakowa w przypadku pozostałych żądań ze wspomnianym błędem.

**Comment by pawelignatowski** [comment]
[6.xlsx](https://github.com/allegro/allegro-api/files/13279829/6.xlsx)
[5.xlsx](https://github.com/allegro/allegro-api/files/13279830/5.xlsx)
[3.xlsx](https://github.com/allegro/allegro-api/files/13279831/3.xlsx)
Sprawdzałem na trzech kątach do których mam dostęp. 

Nie są to trzy konta? Może klient połączył złe aplikacje.

**Comment by Lukasz-Zurek** [comment]
**f985b349-06af-4fdd-aa0f-49c468f12745:** 

- identyfikator konta z którego zlecane jest utworzenie przesyłki:: 105452710,
- identyfikator konta, do którego należy zamówienie: 44157563

**922a4037-6d00-4903-84bb-2c1e8df88adb:**
- identyfikator konta z którego zlecane jest utworzenie przesyłki: 36846013,
- identyfikator konta, do którego należy zamówienie: 44157563,

**1f5857b6-0156-4251-a6f2-a1f977cb7746:**
- identyfikator konta z którego zlecane jest utworzenie przesyłki: 36846013,
- identyfikator konta, do którego należy zamówienie: 44157563.

Sprzedający cały czas próbuje zlecić wysyłkę paczek będąc autoryzowanym na koncie 44157563.
