### ISSUE TITLE
PATCH /sale/product-offers/{offerId}  i parametry

### ISSUE THREAD

**Issue by thefoe76** [allegro/allegro-api#7914]
W poradniku napisali, mozna edytować, tym sposobem także parametry. Jednak zwraca mi taką odpowiedź na ten json:
`{"parameters":[{"id":"249474","valuesIds":[],"values":["63"],"rangeValue":null},{"id":"247931","valuesIds":[],"values":["400"],"rangeValue":null}]}{"errors":[{"code":"ParameterCategoryException","message":"Unprocessable Entity","details":null,"path":"parameters","userMessage":"The parameter `249474:Prąd znamionowy` should not be specified in the `offer` section."}]}`

nie wiem w czym problem, edycja starą metodą działa ok (czyli wczytanie całego Json i przesłanie go po modyfikacjach, ale wolałbym uzywać tego, ze względu na asynchronicznośc.

**Comment by PrzemyslawLukanowski** [comment]
Parametry dzielą się na parametry ofertowe (które przekazujesz w sekcji `"parameters"`) oraz produktowe (które przekazujesz w sekcji `"productSet.product.parameters"`). Komunikat, który otrzymałeś, wskazuje na to, że parametr 249474 załączasz w sekcji ofertowej, a powinieneś w produktowej - informację, o tym, jakiego rodzaju jest dany parametr, sprawdzisz w odpowiedzi [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2), w polu `"options.describesProduct"`.

**Comment by eof-the** [comment]
Dziwne, bo kiedy wypełnie je przez www, to to w json są w w sekcji parameters. To samo dotyczy edycji przez ponowną publikację kompletnego json aukcji, dodaje te wymagane do parameteres i działa. Nawet w zwrotce brakujących parametrów podajecie scieżkę do "parameters" ([path] => parameters). O co tu chodzi i po co ten bałagan?

**Comment by PrzemyslawLukanowski** [comment]
Czy opisana sytuacja dotyczy zasobów /sale/product-offers czy /sale/offers? Jeśli tych pierwszych, podaj proszę trace-id, gdzie parametry produktowe zwróciliśmy w sekcji `"parameters"`. Jeśli jednak korzystasz z /sale/offers, to jest to prawidłowy scenariusz, ponieważ te zasoby oznaczone są jako deprecated, zostana wyłączone z końcem roku i nie zawierają struktury `product.parameters`.

**Comment by thefoe76** [comment]
przecież parameters ma taką samą strukture dla obu zasobów, tylko jest w innym "miejscu", ale przeciez to nie powinno mieć znaczenia, to jak powinien wyglądać przykładowy json dla PATCH parametru /sale/product-offers?

**Comment by PrzemyslawLukanowski** [comment]
@thefoe76 Moja odpowiedź wyżej dotyczyła komentarza @eof-the, rozwiązaniem Twojego problemu jest moja pierwsza odpowiedź. W zależności od tego, co chcesz zmienić w ofercie, przykładowa struktura może wyglądać różnie. Poniżej przesyłam przykład, który obejmuje zarówno parametry produktowe, jak i ofertowe:

```
{
    "productSet": [
        {
            "product": {
                "parameters": [
                    {
                        "id": "x",
                        "valuesIds": [
                            "xx"
                        ]
                    },
                  ...
                ]
            }
        }
    ],
    "parameters": [
        {
            "id": "xx",
            "values": [
                "xx"
            ]
        }
    ...
      ]
    }
```

Pamiętaj, że aby zmienić wartość parametru w produkcie, nie może on być parametrem, który identyfikuje produkt (czyli w GET /sale/products/{productId} w polu `options.identifiesProduct` musimy zwrócić `false`).

**Comment by eof-the** [comment]
oba konta są moje, rózne komputery :) 
Robiłem za pomocą json z całą sekcją "productSet", dalej nie działa, chyba ze ja czegoś nie rozumiem, chce uzupełnić brakujące parametry, mam przesłać całą sekcję "productSet" tak jak ma być W CAŁOŚCI, czy tylko brakujące parametry?

**Comment by PrzemyslawLukanowski** [comment]
Jeśli parametr jest ofertowy, czyli w odpowiedzi [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2), w polu `"options.describesProduct" `widnieje `"false",` wtedy wystarczy, że przekażesz sekcję `"parameters" `- wraz z parametrami, których nie zmieniasz (wynika to ze specyfiki działania metody PATCH). Jeśli natomiast parametr jest produktowy, wtedy analogicznie musisz przesłać także całą strukturę `productSet.product.parameters` (parametr, który zmieniasz, plus pozostałe). Możesz przekazać nam trace-id operacji, która się nie powiodła - przeanalizuję to i podpowiem, jak skonstruować prawidłowy request.

**Comment by eof-the** [comment]
{"productSet":[{"product":{"id":"19052d18-a7cc-48f9-bd4b-19ee367361fd","publication":{"status":"LISTED"},"parameters":{"parameters":[{"id":"225693","name":"EAN (GTIN)","values":["5902838495087"],"valuesIds":null,"rangeValue":null},{"id":"224017","name":"Kod producenta","values":["EBS1LE 1P C16"],"valuesIds":null,"rangeValue":null},{"id":"248811","name":"Marka","values":["LC Tec"],"valuesIds":["248811_1146379"],"rangeValue":null},{"id":"129912","name":"Rodzaj","values":["wy\u0142\u0105cznik r\u00f3\u017cnicowopr\u0105dowy"],"valuesIds":["129912_11"],"rangeValue":null},{"id":"249474","valuesIds":null,"values":["63"],"rangeValue":null},{"id":"247931","valuesIds":null,"values":["400"],"rangeValue":null},{"id":"235878","values":null,"valuesIds":["235878_479949"],"rangeValue":null}]}},"quantity":{"value":1}}]}

{"errors":[{"code":"JsonMappingException","message":"Message is not readable.","details":null,"path":"productSet[0].product.parameters","userMessage":"Request contains invalid data. Contact the application author."}]}

"trace-id: 7ac86f664f2595d8"

**Comment by PrzemyslawLukanowski** [comment]
Zwróć proszę uwagę, że w obiekcie product, przekazujesz podwójnie pole parameters, to pierwsze jest niepotrzebne. Porównaj tą sekcję z tą, którą wkleiłem wyżej lub z przykładami [z dokumentacji](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pojedynczej-oferty).

```
{
    "productSet": [
        {
            "product": {
                "id": "19052d18-a7cc-48f9-bd4b-19ee367361fd",
                "publication": {
                    "status": "LISTED"
                },
                "parameters": {
                    "parameters": [
...
```

**Comment by thefoe76** [comment]
Głupi błąd, dziekuję za pomoc - teraz wszystko działa.
