### ISSUE TITLE
EmptyUserIdException 

### ISSUE THREAD

**Issue by antoniSea** [allegro/allegro-api#7915]
Hej, mam problem z autentykacją:

Otrzymuję odpowiedz `"code":"EmptyUserIdException","message":"user_name from JWT cannot be empty","details":null`

Przy zapytaniu na GET https://api.allegro.pl/order/checkout-forms?offset=0&limit=100&status=CANCELLED&boughtAt.gte=2023-11-05T19%3A45%3A59.079785Z

Używając takich nagłówków:
"Authorization": "Bearer {token}",
"Content-Type": "application/vnd.allegro.public.v1+json",

gdzie token zamieniłem tokenem wygenerowanym przez https://allegro.pl/auth/oauth/token za pomocą aplikacji o id: "972fc1b48a054003a6c14575d73e2d8b"

**Comment by PrzemyslawLukanowski** [comment]
Komunikat wskazuje, że Twój token nie posiada kontekstu użytkownika, co oznacza, że wygenerowałeś go w ramach autoryzacji [client_credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow). Autoryzacja tego rodzaju daje Ci dostęp wyłącznie do tych zasobów, które w naszej dokumentacji oznaczyliśmy jako "bearer-token-for-application.". Aby posiadać dostęp do zamówień, musisz posiadać kontekst użytkownika, zatem wygeneruj token w drodze autoryzacji [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow).

**Comment by antoniSea** [comment]
Przy użyciu tokena wygenerowanego przy użyciu metody device dostaję taką odpowiedz: `{"error":"invalid_token","error_description":"Cannot convert access token to JSON"}`

Toekn przekazywany jest tak samo w nagłówku authorization `Bearer {token}`

**Comment by PrzemyslawLukanowski** [comment]
Wygląda na to, że przekazujesz w swoim tokenie nadmiarową literę "e" na samym początku. Otrzymujemy "eeyJhbGc...", przez co nie da się zdekodować takiego tokena. Po usunięciu pierwszej litery jest już w porządku, widnieją dane, które wkleiłeś wyżej.
