### ISSUE TITLE
WZA: Processing error,  Allegro Paczkomaty InPost pobranie

### ISSUE THREAD

**Issue by mmodrzejewski** [allegro/allegro-api#7916]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry

Problem dotyczy zamówienia:
2bffa130-7a11-11ee-8cfb-875aa76e8aa2

Za każdym razem to samo (w dniu 3.11 były 4 próby), zlecenie jest przyjmowane, błąd w procesowaniu, np.
parcel-management/parcel-create-commands/33787acc-1dac-47d5-ae86-98b0608f7687
parcel-management/parcel-create-commands/b12cd342-e738-43d6-a681-8958c9f75130
parcel-management/parcel-create-commands/64ef510f-5d09-4cf9-87e0-d26fe4324237
parcel-management/parcel-create-commands/93971c7e-f598-4865-bd00-d085046da2e1
"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej" (Processing error)

Dane adresowe podstawiane z zamówienia Allegro. Zastrzeżenia budzi tylko nazwa firmy odbiorcy (wygląda jak NIP, natomiast NIPu nie podano)

Klient oznaczył już zamówienie jako wysłane (zapewne nadał przez panel)

Proszę o informację zwrotną, co było nie tak, aby uniknąć podobnych sytuacji w przyszłości.

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
@mmodrzejewski Błąd, który otrzymaliśmy od przewoźnika to "Pobranie nie może być większe niż ubezpieczenie przesyłki (13,80 zł). Popraw kwotę w polu "Wartość ubezpieczenia"" - i tu konkretnie chodzi o pole **"value.amount"**.
