### ISSUE TITLE
Status "odebrane" / faktura korekta allegro

### ISSUE THREAD

**Issue by Levena007** [allegro/allegro-api#7918]
Witam,
1. mamy problem ze zmianą statusu w panelu Allegro na "odebraną". Nie zmienia nam się ten status (korzystamy z umowy własnej z DPD). Po czyjej stronie leży zmiana takiego statusu? Allegro, DPD? Czy jest moze jakaś dokumentacja techniczna, która opisuje ten proces?
2. Faktura korekta: czy Allegro wymaga, aby do panelu dołączać fakturę korektę np. przy odstąpieniu od umowy? Czy jeśli tak to czy jest możliwość zrobienia tego automatycznie? Np. przez API? jeśli tak to czy jest dostępna jakaś dokumentacja?

pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Witam,

1. Jeśli masz na myśli status realizacji zamówienia widoczny na zrzucie poniżej, to zmiana leży po stronie sprzedającego, status nie zaktualizuje się automatycznie. Proces po stronie API opisujemy [w tym fragmencie](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#zmiana-statusu-realizacji-zamowienia) naszego poradnika.
<img width="238" alt="Zrzut ekranu 2023-11-6 o 11 50 48" src="https://github.com/allegro/allegro-api/assets/51473661/ae2d96c0-b9ef-44bd-b8e2-250347b5d478">

2. W API udostępniamy możliwość załączenia faktury do zamówienia, szczegóły znajdziesz [tutaj](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#faktury). Twoje pytanie o fakturę korygującą wykracza jednak poza temat API, dlatego zadaj je za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt).

**Comment by Levena007** [comment]
Dziękuję.
3. Czy jeśli klient zgłasza zwrot ptrzez Allegro to czy jako sprzedający powinniśmy zmieniać status z "odebrane" np. na anulowane?

**Comment by PrzemyslawLukanowski** [comment]
Pozostaje to w gestii sprzedającego, ponieważ ten status nie jest widoczny dla kupującego, nie ma również wpływu na inne wskaźniki.

**Comment by Levena007** [comment]
Dziękuję za informację
