### ISSUE TITLE
Tworzenie paczki COMMAND_TIMEOUT

### ISSUE THREAD

**Issue by kdabek** [allegro/allegro-api#7919]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzien dobry,
W środowisku sandbox dla endpointu `POST` [https://api.allegro.pl.allegrosandbox.pl/shipment-management/shipments/create-commands](https://api.allegro.pl.allegrosandbox.pl/shipment-management/shipments/create-commands) otrzymuję cały czas status `IN_PROGRESS`

by finalnie na pytanie o status otrzymać:

```
[
    {
        "code": "COMMAND_TIMEOUT",
        "message": "The time for completing the order has expired",
        "details": null,
        "path": "",
        "userMessage": "Up\u0142yn\u0105\u0142 limit czasu na wykonanie zlecenia"
    }
]
```

To jakieś chwilowe niedomaganie środowiska sandbox czy problem leży gdzie indziej.

Trace id z response tworzenia paczki jest nast.
trace-id: 16ffbdfeadb49b4a

Pozdrawiam
Krystian Dąbek

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że taki problem występował. Aktualnie tworzenie przesyłek działa już poprawnie, przepraszam za niedogodności.
