### ISSUE TITLE
HTML error API Channable

### ISSUE THREAD

**Issue by PPD079** [allegro/allegro-api#7920]
Hello,

•	An API connection for Allegro is available in Channable, which I completed. 
•	At the last moment it throws an error saying for all products: "Invalid HTML subset (description.sections[0].items[0].content)", suggesting that the HTML of ours isn’t correct. 
•	So it looks like our long product description is not right by Allegro standards. 
•	There might be some mistakes in our HTLM-texts, but not with all of them. I know Allegro doesn’t accept ‘old’ HTML signs as <br>.
•	Weird thing: I also tried to use another description, which doesn’t even contains HTML. Still same error.
•	As a result of it, I can’t finish the automatical connection between Channable and Allegro. 

- I called Channable and they can't see what I did wrong using the API. 

How can I solve this, so the API can work?

![allegro1](https://github.com/allegro/allegro-api/assets/149517504/2bd087d2-3263-4a0c-9f61-b254b5f5962c)

**Comment by Lukasz-Zurek** [comment]
You have to check the description closely, because "Invalid HTML subset" means that you used an invalid HTML - [here](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#own-images-and-description) you will find the whole list of available tags.
