### ISSUE TITLE
Problem z aktywacją konta na środowisku testowym

### ISSUE THREAD

**Issue by CodeMiner84** [allegro/allegro-api#7921]
Nie mogę aktywować sprzedaży na allegro sandbox. Konto MeHow. Podczas weryfikacji konta bankowego przenosi mnie na ` c2c-payu-simulator.dh-test.qxlint`, gdzie taka stronie isnieje. Da się coś z tym zrobić ?

**Comment by Lukasz-Zurek** [comment]
@CodeMiner84 Z tego co widzę - zarejestrowałeś konto zwykłe. Jeśli chcesz testować proces wystawiania, etc. musisz przekonwertować to konto na firmowe, za pośrednictwem [tej](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) zakładki. Następnie przejdź do [ustawień wypłat](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty), przechodząc przez całą konfigurację, włącznie z symulatorem płatności.

Natomiast jeśli chcesz pozostać przy koncie zwykłym - daj proszę znać. Aktywuję konto.

**Comment by CodeMiner84** [comment]
hmmm, nie bardzo rozumiem dlaczego dla konta testowego muszę wykonać proces aktyawacji firmy poprzez dane z dokumentu typu np dowód osobisty. Zakładałem, że mogę tu podać jak i wyżej w danych firmy itp testowe randomowe dane. Proszę o informację zwrotną
![Zrzut ekranu z 2023-11-07 20-55-22](https://github.com/allegro/allegro-api/assets/1668366/684d4c69-6049-463b-b8a8-83dcec3217fd)

**Comment by CodeMiner84** [comment]
@Lukasz-Zurek ile zajmuje weryfikacja konta ? Czekam już 10 dzień ? :see_no_evil:

**Comment by Lukasz-Zurek** [comment]
@CodeMiner84 Skorzystaj proszę jeszcze z symulatora płatności w [ustawieniach wypłat](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty), przycisk: "Zrób przelew online". Daj proszę znać po wykonaniu tej czynności (i zaakceptowaniu symulowanej płatności) - aktywuję wówczas konto.

**Comment by CodeMiner84** [comment]
testowy przelew wykonany zgodnie z instrukcją

**Comment by Lukasz-Zurek** [comment]
@CodeMiner84 Konto w pełni aktywne i zweryfikowane. Przepraszam za długi czas realizacji.

**Comment by CodeMiner84** [comment]
@Lukasz-Zurek dziekuje za pomoc.
