### ISSUE TITLE
Data updatedAt dla CheckoForm

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#7922]
Do pobierania zamówień korzystam z endpointa  https://api.{environment}/order/checkout-forms
Jest tutaj pole updatedAt w formacie ISO 8601 format. Czy data jest przekazywana według czasu lokalnego czy UTC? 
W innym miejscu widziałem, że jest dopisek UTC ISO tutaj takiego nie ma, a widzę że czasy nie są lokalne dla zamówień, więc chciałbym mieć jasność w tym przypadku.

**Comment by MartaNowaczyk** [comment]
Data przekazywana jest w UTC.
