### ISSUE TITLE
通过API创建变体如何修正此错误

### ISSUE THREAD

**Issue by 3148846032** [allegro/allegro-api#7923]
The specified product exists. The specified parameter `Marka` with the value `D-look(3786_1651265)` does not match the product parameter `bez marki(3786_1704209)`

Wysłałem wiadomość z prośbą，Jaki jest problem powodujący ten komunikat o błędzie

Request:
Host:api.allegro.pl
POST /sale/product-offers HTTP/1.1
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer 
accept: application/vnd.allegro.public.v1+json
Referer: https://api.allegro.pl

{"parameters":[{"id":"11323","name":"Stan","valuesIds":["11323_1"],"values":null,"rangeValue":null}],"category":{"id":"124264"},"customParameters":null,"compatibilityList":null,"delivery":{"shippingRates":{"id":"195b8903-f37a-4ed4-bdd7-d1ac5420411a"},"handlingTime":"P5D","shipmentDate":null,"additionalInfo":null},"payments":{"invoice":"NO_INVOICE"},"discounts":null,"afterSalesServices":{"impliedWarranty":{"id":"68332fb9-0dc5-454d-9b64-d3db2eb84412"},"returnPolicy":{"id":"ea54cf7c-f65b-4a29-9b27-6824302e7c8c"},"warranty":null},"additionalServices":null,"sizeTable":null,"fundraisingCampaign":null,"location":{"countryCode":"CN","province":null,"city":"Shenzhen","postCode":"0000"},"messageToSellerSettings":{"mode":"HIDDEN"},"publication":{"duration":"P3D","status":"ACTIVE","startingAt":null,"endingAt":null,"endedBy":null,"republish":false,"marketplaces":null},"attachments":null,"contact":null,"b2b":{"buyableOnlyByBusiness":false},"language":"pl-PL","stock":{"available":64,"unit":"UNIT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":89.0,"currency":"PLN"},"minimalPrice":null,"startingPrice":null},"external":{"id":"0e7f84-4-2ca32b9fc586ba5cb1b13eee7675e45b3f5cfc00-3XL"},"productSet":[{"product":{"name":"Sukienka rozkloszowana maxi długa PLUS SIZE 44 XXL","category":{"id":"124264"},"images":["https://a.allegroimg.com/s512/1163b9/85f420834753b40693a8f8d796f0/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL.jpg","https://a.allegroimg.com/s128/1163b9/85f420834753b40693a8f8d796f0/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL.jpg","https://a.allegroimg.com/s128/11b792/f37b3e2045aaa88f3d4c313757fd/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL-Marka-D-look.jpg","https://a.allegroimg.com/s128/11d81a/c67380374dd0ab333a30233fa1cc/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL-Rozmiar-XXL.jpg","https://a.allegroimg.com/s128/11ad23/5430dc5e4e41aa4da33a3345b25b/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL-Wzor-dominujacy-kwiaty.jpg","https://a.allegroimg.com/s128/1105de/f9fce9b643ad8b1a189dc3111fcf/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL-Okazja-koktajlowa.jpg","https://a.allegroimg.com/s128/11590e/5199e0d3453ba76617865a879a73/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL-Fason-rozkloszowana.jpg","https://a.allegroimg.com/s128/111c52/49ea1e1549cb9654f0dd1f49645f/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL-Styl-klasyczna.jpg","https://a.allegroimg.com/s128/115ce3/3c1835f247d5b7aaee5e222021e1/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL-Dekolt-serek-dekolt-V.jpg","https://a.allegroimg.com/s128/11f7c2/e63cc1de4362b36d107e86cfddde/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL-Rekaw-krotki-rekaw.jpg","https://a.allegroimg.com/s512/1167b2/991d12014d16bebf217100db2e15/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL.jpg","https://a.allegroimg.com/s128/1167b2/991d12014d16bebf217100db2e15/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL.jpg","https://a.allegroimg.com/s128/11ff32/48c783624c4faba6d8b1a751e8ba/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL-Marka-D-look.jpg","https://a.allegroimg.com/s128/11dccd/ebd26cb6454c872ca7188bc4a5de/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL-Rozmiar-XXL.jpg","https://a.allegroimg.com/s128/11a316/0d8e8e6943a1b4e4ee9606d6b4f4/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL-Wzor-dominujacy-kwiaty.jpg","https://a.allegroimg.com/s128/11ee8b/739f754e47629cfde63b5f35e96b/Sukienka-rozkloszowana-maxi-dluga-PLUS-SIZE-44-XXL-Okazja-koktajlowa.jpg"],"parameters":[{"id":"18160","name":"Długość","valuesIds":["18160_3"],"values":null,"rangeValue":null},{"id":"3786","name":"Marka","valuesIds":["3786_1651265"],"values":null,"rangeValue":null},{"id":"4126","name":"Rękaw","valuesIds":["4126_3"],"values":null,"rangeValue":null},{"id":"3766","name":"Wzór dominujący","valuesIds":["3766_3"],"values":null,"rangeValue":null},{"id":"127488","name":"Fason","valuesIds":["127488_7"],"values":null,"rangeValue":null},{"id":"127662","name":"Okazja","valuesIds":["127662_3"],"values":null,"rangeValue":null},{"id":"127468","name":"Styl","valuesIds":["127468_4"],"values":null,"rangeValue":null},{"id":"59","name":"Dekolt","valuesIds":["59_8"],"values":null,"rangeValue":null},{"id":"201025","name":"Zapięcie","valuesIds":["201025_2521"],"values":null,"rangeValue":null},{"id":"201017","name":"Materiał dominujący","valuesIds":["201017_2317"],"values":null,"rangeValue":null},{"id":"225693","name":"EAN (GTIN)","valuesIds":null,"values":["0011011434418"],"rangValue":{},"rangeValue":null},{"id":"249512","name":"Kolor","valuesIds":["249512_1647425"],"values":null,"rangeValue":null},{"id":"54","name":"Rozmiar","valuesIds":["54_1044190"],"values":null,"rangeValue":null}]},"quantity":{"value":1}}]}

Response:
{"errors":[{"code":"PARAMETER_MISMATCH","message":"The provided parameter 'Marka'(3786) value (D-look(3786_1651265)) does not match the existing parameter value (bez marki(3786_1704209))","details":null,"path":"productSet[0].product.parameters","userMessage":"The specified product exists. The specified parameter `Marka` with the value `D-look(3786_1651265)` does not match the product parameter `bez marki(3786_1704209)`."}]}

state:422
length:427
ms:1470

**Comment by 3148846032** [comment]
Podałem tylko jedną markę dla tego produktu, dlaczego była ona w konflikcie z innymi markami

**Comment by 3148846032** [comment]
Czy jest jakiś sposób, by to rozwiązać?

**Comment by 3148846032** [comment]
Czy jest jakiś sposób， by to rozwiązać？

**Comment by MartaNowaczyk** [comment]
Błąd wystąpił ponieważ nasz mechanizm na podstawie przesyłanych danych znalazł produkt w naszym katalogu, w którym nie zgadzał się parametr marka. Jednak z tego co sprawdziłam wystawienie tego produktu nie powinno już być problemem. Spróbuj jeszcze raz wystawić ofertę z tymi samymi danymi co tu przesłałeś. Jeśli napotkasz problem podeślij tutaj trace-id do dalszej weryfikacji.

**Comment by 3148846032** [comment]
Odkryłem, że gdy w danych backendu znajduje się kod, który ma to samo kodowanie co dane wydane tym razem, będziesz pasował do marki danych backendu. Jeśli nie jest taki sam, zostanie zgłoszony błąd.

**Comment by MartaNowaczyk** [comment]
Jeśli w naszej bazie znajdziemy produkt, który pasuje do podanych danych, ale różni się wartością dla jakiegoś parametru - trzeba ten parametr poprawić zgodnie z komunikatem. 
Jeśli potrzebujesz pomocy, podeślij trace-id wywołania z błędem.

**Comment by 3148846032** [comment]
Mogę zapytać, czy pasuje pan do istniejących danych na podstawie którego unikalnego pola

**Comment by MartaNowaczyk** [comment]
Na podstawie przesłanych danych znaleźliśmy produkt d4dbda11-eb3c-4843-9776-8714d70f8ffb, ale parametr Marka był inny, dlatego zwróciliśmy błąd, abyś mógł ten parametr poprawić. Jeśli jednak parametr Marka jest według Ciebie błędny możesz [zgłosić błąd](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-report-incorrect-data-in-a-product) w produkcie.
