### ISSUE TITLE
Punkty allegro 

### ISSUE THREAD

**Issue by Rychu1998** [allegro/allegro-api#7924]
Dzień dobry,

Klienci zgłaszają do nas od zeszłego poniedziałku kolejne punkty allegro, których nie możemy pobrać z Państwa webservicu.
przykładowy punkty: AL025WK1, AL150DW1

Podczas składania zamówienia można wybrać te punkty jako sposób dostawy oraz są widoczne na mapach google.
Jednak na stronie https://allegro.pl/kampania/one/znajdz-nas już nie ma takiego punktu widocznego oraz my tak samo nie możemy go pobrać z API.

Czy mogę prosić o wyjaśnienie ? Dodam, że od zeszłego poniedziałku dostajemy coraz więcej takich zgłoszeń o nieistniejących punktach.

**Comment by Lukasz-Zurek** [comment]
@Rychu1998 Problem nie dotyczy stricte API, dlatego aby go wyjaśnić skorzystaj proszę z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=9e378f40-4fc6-47c5-b6a8-4f8dd3102945).

**Comment by pawelkucharskiyosi** [comment]
Prawdopodobnie chodzi o to że niektóre punkty zostały przeniesione w inne miejsca i ich nazwy uległy zmianie jednak w momencie dokonywania zakupu punkt taki jeszcze istniał a teraz już go nie ma, Czy API Allegro może zwrócić listę punktów które zostały przeniesione zmienione zamkniete wraz z datami tego zdarzenia dzięki temu można by kontaktować się z kupującymi i mówić że dnia XXX wybrany przez Pana punkt został zamknięty/przeniesiony i czy paczka ma zostać nadana do punktu YYY?

**Comment by Lukasz-Zurek** [comment]
@pawelkucharskiyosi W pełni Cię rozumiem. Niestety w naszym API nie udostępniamy tego typu funkcjonalności, w postaci np. dziennika zdarzeń związanych ze zmianami w punktach. Jako zespół wparcia API nie mamy wpływu na zmiany punktów - nie monitorujemy ich. Aktualne punkty Allegro zwracamy za pośrednictwem [GET /order/carriers/ALLEGRO/points](https://developer.allegro.pl/documentation/#operation/getAllegroPickupDropOffPointsGET).

**Comment by pawelkucharskiyosi** [comment]
rozumiem jednak co można zrobić w przypadku gdy kupujący wybrał np jeden z następujących punktów AL023WT1, AL347KR1, AL033WPR, AL024WY1, AL028WB1
 API w całym zestawie danych dotyczących konkretnego zamówienia zwraca właśnie taką informację, jednak podczas próby wygenerowania przesyłki z takim właśnie punktem pojawia się problem bo dziś punkty te nie są już dostępne. Czy jeśli wybiorę inny pobliski punkt to przesyłka zostanie wygenerowana czy otrzymam informację iż wskazany przeze mnie punkt nie jest zgodny z tym co wybrał kupujący? Czy API nie mogłoby zwracać rezerwowego punktu który były najbliższy i gdy punkt docelowy nie istnieje wtedy automatycznie mógłbym nadawać do tego rezerwowego najbliższego bez konieczności kontaktu z kupującym i sprawdzania na mapie jaki inny punkt znajduje się w pobliżu tego już nie istniejącego.

**Comment by Lukasz-Zurek** [comment]
@pawelkucharskiyosi Pozwól, że skonsultuję ten temat z odpowiednim zespołem. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@pawelkucharskiyosi W przypadku niedostępności któregoś z punktów, podczas próby utworzenia paczki - możesz wybrać inny, pobliski punkt. Na chwilę obecną nie ma jednak w API żadnego rozwiązania, które ułatwiłoby zarządzanie tego typu zamówieniami. Dlatego mogę tu jedynie zasugerować opisanie propozycji/sugestii w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions) - w jaki sposób moglibyśmy informować o niedostępności punktów Allegro One - czy na zasadzie dziennika zdarzeń, czy też w ramach obecnych funkcjonalności.
