### ISSUE TITLE
Dodawanie produktów przez API - ProductProposalsAccessForbiddenException error na ...sandbox.pl/sale/product-offers

### ISSUE THREAD

**Issue by mrapcakratki** [allegro/allegro-api#7926]
Cześć, podczas dodawania testowego produktu pod adres:
https://api.allegro.pl.allegrosandbox.pl/sale/product-offers
dostaję błąd:

błąd:  {
  errors: [
    {
      code: 'ProductProposalsAccessForbiddenException',
      message: 'Access denied.',
      details: null,
      path: 'productSet[0].product',
      userMessage: 'Brak dostępu.'
    }
  ]
}

Czy mógłbym prosić o aktywację konta?
Dane konta z sandbox:

Cześć Mateusz!
Client:106212557

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Cześć, widzę, że prócz braku aktywacji, sam rodzaj konta nie będzie na tę chwilę odpowiedni do wystawienia oferty - aby wystawiać je za pomocą API, musisz posiadać konto firmowe (Twoje jest zwykłe). Zmień proszę rodzaj konta na firmowe przez zakładkę [Dane Konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto), uzupełnij dane do wypłat (oczywiście możesz wygenerować fikcyjny numer bankowy, ponieważ na Sandboxie wszelkie płatności odbywają się za pomocą symulatora) - napisz, jak to zrobisz, aktywuję wtedy konto.

**Comment by mrapcakratki** [comment]
Dziękuję za odpowiedź. 
Na potrzeby sandboxa zmyśliłem wszystkie dane. 
Zmieniłem konto na firmowe, aktywowałem płatności/rachunek, dodałem warunki zwrotu, warunki reklamacji i cennik.
Czy to wszystko?

**Comment by PrzemyslawLukanowski** [comment]
To wszystko, dziękuję. Aktywowałem Twoje konto.

**Comment by mrapcakratki** [comment]
Serdecznie dziękuję za odpowiedź.
Chcę dodać teraz produkt, dostałem jednak informację że muszę podać dwa brakujące parametry.

errors: [
    {
      code: 'ConstraintViolationException.MissingRequiredParameters',
      message: 'Missing required parameters: 249445, 249446',
      details: 'ConstraintViolationException.MissingRequiredParameters',
      path: 'parameters',
      userMessage: 'Uzupełnij parametry obowiązkowe: Ładowarka w komplecie, Słuchawki w komplecie.'
    }
  ]


Skąd wiadomo jakie są możliwe do wpisania wartości w pola value dla tych parametrów? Czyli co wpisać w miejsce "x"?

const myData = {
        productSet: [
                {
                        product: {
                                name: "TESTOWY PRODUKT",
                                idType: "GTIN",
                                id: "4549292006292", //9311183092159
                                images: ["https://cdn.pixabay.com/photo/2014/02/11/19/35/brown-264289_1280.jpg"],

                        },
                }
        ],
        // parameters: [
        //         {
        //                 id: "249445",
        //                 values: ["x"]
        //         },
        //         {
        //                 id: "249446",
        //                 values: ["x"]
        //         }
        // ],
        // delivery: {
        //         shippingRates: null
        // },
        stock: {
                available: 99
        },
        sellingMode: {
                price: {
                        amount: "123.45",
                        currency: "PLN"
                }
        }
};

**Comment by PrzemyslawLukanowski** [comment]
Skorzystaj z [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2), aby dowiedzieć się, jakiego rodzaju jest dany parametr oraz jakie wartości możesz przekazać. Przykłady prawidłowego wypełnienia parametrów znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#parametry-ofertowe). 
Dla przykładu - dla zapytania GET /sale/categories/165/parameters otrzymasz m.in. wspomniane parametry:

```
            "id": "249446",
            "name": "Słuchawki w komplecie",
            "type": "dictionary",
           "describesProduct": false,
```

```
            "id": "249445",
            "name": "Ładowarka w komplecie",
            "type": "dictionary",
            "describesProduct": false,
```

Oba parametry są typu słownikowego (dictionary), co oznacza, że w polu `"valuesIds"` musisz przekazać wartość z dostępnych w polu `"dictionary"`, czyli np.

```
        parameters: [
                {
                        id: "249445",
                        valuesIds: ["249445_1220085"]
                },
                {
                        id: "249446",
                        valuesIds: ["249446_1220090"]
                }
        ],
```

**Comment by PrzemyslawLukanowski** [comment]
> Rozumiem, jednak skąd wzięta jest ta wartość 165 = categoryId? Skąd ją odczytać? bo w error było tylko:
> 'Missing required parameters: 249445, 249446',

Próbujesz wystawić produkt o wartości GTIN 4549292006292, zatem skorzystałem z wyszukiwarki produktów GET /sale/products?phrase= 4549292006292&mode=GTIN i w odpowiedzi otrzymałem dane tego produktu, w tym informację o category.id, którą mogłem dalej przekazać w GET /sale/categories/{id}/parameters.

> Tak samo skąd odczytać że możliwe jest do wpisania "249445_1220085"? domyślam się że stąd: " dictionary: [Array],"

Tak, dokładnie, w tym polu znajdziesz listę dostępnych wartości dla parametrów słownikowych.

> ale jednak mam problem bo jak używam tej metody dla 165 to dostaję listę w której jest na przykład:

Wykonałem przed chwilą przykładowy request na środowisku testowym i otrzymałem te parametry w odpowiedzi:

```
            "id": "249446",
            "name": "Słuchawki w komplecie",
            "type": "dictionary",
            "required": true,
            "requiredForProduct": false,
            "requiredIf": null,
            "displayedIf": null,
            "unit": null,
            ...
```

```
            "id": "249445",
            "name": "Ładowarka w komplecie",
            "type": "dictionary",
            "required": true,
            "requiredForProduct": false,
            "requiredIf": null,
            "displayedIf": null,
            "unit": null,
            ...
```

**Comment by mrapcakratki** [comment]
Dziękuję za pomoc, wszystko się udało :)

**Comment by PrzemyslawLukanowski** [comment]
Super, cieszę się, że mogłem pomóc :)
