### ISSUE TITLE
"Parcel description is too short"

### ISSUE THREAD

**Issue by lhascilo** [allegro/allegro-api#7927]
Dzień dobry,

w dniu dzisiejszym próbowalismy wygenerować paczkę uuid":"c03d4c07-0cb5-45ba-9768-71b79a03ecd7, dla której otrzymalismy błąd:
llegro_errors":[{"code":"VALIDATION_ERROR","message":"Parcel description is too short","details":null,"path":"items.description","userMessage":"Opis przesyłki jest za krótki"}
Czy mogę prosić o informację co w tym zamówieniu jest nie tak ?

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z komunikatem, przewoźnik przy tworzeniu przesyłki wymaga uzupełnienia opisu, za które odpowiada pole `description`. Musisz przekazać wartość między 1 -50 znaków.

**Comment by lhascilo** [comment]
Ok. Problem jest taki, ze w reuqescie przekazuje descirpiton, przesyłam część zapytaniaL request_string" => "{"description":"Office chair casters","parcels":[{"height":9.50,"length":20.00,"weight":1.216500,"width":12.50}]

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać commandID dla takiego przypadku? Ten, który podałeś w pierwszym poście, zawiera `"description":""`.

**Comment by lhascilo** [comment]
Ten numer UUID jest jedyny, c03d4c07-0cb5-45ba-9768-71b79a03ecd7 i w nim przekazujemy "description":"Office chair casters"

**Comment by PrzemyslawLukanowski** [comment]
Musisz wygenerować nowy numer UUID dla każdej nowej próby utworzenia przesyłki. Stąd obecny komunikat błędu - zwracamy go nadal dla pierwszej próby, gdzie opis nie był uzupełniony.

**Comment by jwmbb** [comment]
Przesyłam nowe UUID dla tej samej przesyłki. Rezultat mamy ten sam za krótki opis przesyłki
241d2354-369b-47ec-b963-247a90e8630f

**Comment by PrzemyslawLukanowski** [comment]
Widzimy, że ten request nadal zawiera puste pole dotyczące opisu: `"description":""`.

**Comment by lhascilo** [comment]
Czy możemy w jakiś sposób przesłać do pana cały request, który przesyłamy? Chcielibyśmy prosić o weryfikację, gdzie leży błąd w request, u nas zaczyna sie od "{"description":"Office chair casters","parcels":[{"height":9.50,"length":20.00,"weight":1.216500,"width":12.50}]

**Comment by PrzemyslawLukanowski** [comment]
Nie otrzymujemy od Państwa tego pola. Dodatkowo, nie obsługujemy w zasobie takiego pola jak `parcels`, `parcels. length`, a widzę, że Państwo je przesyłacie po swojej stronie. Prosiłbym o weryfikację, czy request po Państwa na pewno skonstruowany jest prawidłowo, ponieważ w naszych logach nie znajdujemy odzwierciedlenia danych z przykładu powyżej. Dane odnośnie wymiarów otrzymujemy inne:

```
 "items": [
        {
            "weight": {
                "value": 1.219,
                "unit": "KILOGRAM"
            },
            "dimensions": {
                "height": {
                    "value": 10,
                    "unit": "CENTIMETER"
                },
                "width": {
                    "value": 13,
                    "unit": "CENTIMETER"
                },
                "depth": {
                    "value": 20,
                    "unit": "CENTIMETER"
                }
            }
        }
    ],
```

Przykładowy request mogą Państwo wysłać za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt) z dopiskiem, że dane dotyczą wątku #7927 na GitHubie.

**Comment by lhascilo** [comment]
Przesłałem requesta poprzez formularz. Czy mogę prosić o jego weryfikację ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, zweryfikujemy to jak tylko request zostanie do nas przekierowany, jednak najpierw prosiłbym o weryfikację po Państwa stronie, ponieważ występuje rozbieżność nie tylko w wartości przekazanej w "description", ale - jak wspomniałem- także pozostałe wymiary przesyłki oraz nazewnictwo pól nie jest spójne.

**Comment by jwmbb** [comment]
Aktualnie sprawdzamy format wysyłanego zapytania co do poprzedniej paczki.
Przy próbie utworzenia nowej całkiem innej przesyłki ale również na Czechy mamy inny błąd:

#15  "response_string" => "{"status":3,"allegro_errors":[{"code":"INSURANCE_IS_MISSING","message":"Insurance is required to create a parcel","details":null,"path":"items.value","userMessage":"Ubezpieczenie jest wymagane w celu utworzenia przesyłki"}]}"

Pytanie czy na Czechy wymagane jest ubezpieczenie paczki ? 
UUID: 2f4a6aa1-4308-441e-bb9e-c1d1590ca6b4
Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Tak, wprowadźcie proszę wartość w obiekcie `items[].value`. Dodam, że widzę, że korzystacie ze starszej wersji zasobów, tzn. [parcel-management](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-zarzadzac-przesylkami-poprzez-parcel-management-), które niedawno oznaczyliśmy jako deprecated i w przyszłości będziemy je wyłączać. Zachęcam do uwzględniania w pracach przejścia na zasoby shipment-management, które opisaliśmy w głównej części poradnika.

**Comment by jwmbb** [comment]
OK, Dodamy wartość ubezpieczenia, a Pytanie czy jeszcze jakaś wartość jest wymagana na wysyłkę do Czech ? z tych zamówień co wcześniej wysyłaliśmy?
Co do przejscia na zasób shipment-management to jesteśmy świadomi zmian i mamy zaplanowaną integrację
Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Nie, wygląda na to, że przesyłki zawierają wymagany komplet informacji.

**Comment by PrzemyslawLukanowski** [comment]
Otrzymaliśmy request z formularza kontaktowego - widzę, że pole `description` osadzacie na poziomie ogólnym, czyli na tym samym, co m.in. `receiver`. To pole powinno być osadzone w ramach sekcji `items`.
<img width="609" alt="Zrzut ekranu 2023-11-13 o 08 32 01" src="https://github.com/allegro/allegro-api/assets/51473661/7f3cbd19-5767-4b93-8dcb-85827d794a04">

**Comment by jwmbb** [comment]
Dzień Dobry,
Pytanie jaka jest maksymalna ilość znaków w polu item. description ? 
mając 31 pokazuje nam teraz że jest za długi opis

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, dla jakiego przewoźnika zwróciliśmy taki błąd? Pytam, ponieważ maksymalne wartości mogą się różnić w zależności od tego.

**Comment by jwmbb** [comment]
Allegro Kurier DPD Czechy 
oraz 
Allegro Kurier DHL Czechy

**Comment by PrzemyslawLukanowski** [comment]
Dla DPD jest to 100, dla DHL 30. Jeśli w takim razie błąd otrzymujesz dla DPD, prześlij proszę przykładowe commandId, zweryfikujemy tę sytuację

**Comment by jwmbb** [comment]
Jest, OK skróciliśmy opis do 30 znaków. Pytanie czy jakiś kurier wymaga mniejszej ilości ? musielibyśmy ustawić maksymalna wartość dla naszego API.

**Comment by PrzemyslawLukanowski** [comment]
Nie, 30 to najniższa wartość.

**Comment by jwmbb** [comment]
Dziękuje, myślę że temat do zamknięcia.
