### ISSUE TITLE
How to connect an offer with a product

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#7928]
Hi there, 

I wanted to ask, what parameters can we send when we add offer to a product that is already in Allegro catalogue. Right now we are only sending currency, condition, gtin, price, stock but is it possible to also send other information such as offer title and offer description? And are there some other offer parameters that we can send and they will be displayed instead of the info in the product card? 

Thank you in advance for your answer.

All the best, 

Dominika

**Comment by Lukasz-Zurek** [comment]
Yes, you can send your own values while creating an offer. We described all of the parameters right [here](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-przekazac-wlasne-wartosci-w-zadaniu).
