### ISSUE TITLE
Aktywacja sprzedaży (weryfikacja konta testowego sandbox)

### ISSUE THREAD

**Issue by GR-FDX** [allegro/allegro-api#7929]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Proszę o weryfikację poniższego konta testowego ponieważ nie można dodać do konta nowego asortymentu. Wyświetlany jest następujący komunikat: "Aby aktywować sprzedaż zweryfikuj konto."

Login/e-mail: grzegorz.rogucki.osv@fedex.com

**Comment by PrzemyslawLukanowski** [comment]
Sytuacja identyczna jak w wątku #7926, zatem pozwolę sobie zacytować odpowiedź:

> widzę, że prócz braku aktywacji, sam rodzaj konta nie będzie na tę chwilę odpowiedni do wystawienia oferty - aby wystawiać je za pomocą API, musisz posiadać konto firmowe (Twoje jest zwykłe). Zmień proszę rodzaj konta na firmowe przez zakładkę [Dane Konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto), uzupełnij dane do wypłat (oczywiście możesz wygenerować fikcyjny numer bankowy, ponieważ na Sandboxie wszelkie płatności odbywają się za pomocą symulatora) - napisz, jak to zrobisz, aktywuję wtedy konto.

**Comment by GR-FDX** [comment]
Dzień dobry,
dzięki za informację. Chyba już się uporałem...ze zmianami.
