### ISSUE TITLE
[restapi] [doChangeQuantityItem] Liczba sztuk nie może być mniejsza od liczby sprzedanych przedmiotów.

### ISSUE THREAD

**Issue by pfunkowski** [allegro/allegro-api#793]
Obecna ilość wystawiona na aukcji: 48
Ilość sprzedanych: 1
Ilość docelowa: 5
Ilość wysłana wskazaną metodą: 6
w odpowiedzi błąd:
Liczba sztuk nie może być mniejsza od liczby sprzedanych przedmiotów.

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) request i respons w formacie XML. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz proszę, że informacje są potrzebne do ticketa numer 793 na GitHub-ie.

**Comment by rpicheta** [comment]
Mam podobny problem, czy został już rozwiązany problem kolegi @pfunkowski ?
Jeśli tak to w czym on był?

**Comment by PawelTaberski** [comment]
Z tego co widzę nie otrzymałem od niego informacji, i nikt więcej nie zgłaszał takiego problemu. Podeślij proszę jak wyżej: przez nasz [formularz kontaktowy ](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619)request i respons w formacie XML. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz proszę, że informacje są potrzebne do ticketa numer 793 na GitHub-ie.

**Comment by rpicheta** [comment]
@PawelTaberski wysłałem.

**Comment by PawelTaberski** [comment]
Ok, jak tylko dostanę informację to sprawdzimy w czym jest problem.

**Comment by PawelTaberski** [comment]
@rpicheta Z tego co widzę w tej ofercie która podesłałeś masz o wiele więcej sprzedanych niż 10 a mianowicie 61. Ile masz sprzedanych przedmiotów w danej ofercie sprawdzisz przy pomocy metody DoGetMySoldItems. Jeśli chcesz mieć dostępnych 10 sztuk musisz zmienić na 71.

**Comment by rpicheta** [comment]
@PawelTaberski Dziękuję, sprawdzę i się odezwę czy pozbyłem się problemu.

**Comment by rpicheta** [comment]
@PawelTaberski zgadza się, to był problem. Rozwiązana sprawa.
Jednak mam inne pytanie.
Pobieram swoje aukcje za pomocą RESTapi 'offers/listing' (nawiązując do ticektu: #734 ). Czy jest już może gdzieś ukryty w odpowiedzi odpowiednik bidsCount?
Jeśli nie to muszę wrócić do pobierania poprzez webAPI `getItemsList()` ?

**Comment by PawelTaberski** [comment]
Liczbę sprzedanych przedmiotów w danej ofercie przez ostatnie 30 dni możesz pobrać przy pomocy metody GET na zasobie /sale/offers ,więcej na ten temat [tutaj](https://developer.allegro.pl/my_offers/). W metodzie do listingu nie ma takich danych jest tylko popularność.

**Comment by rpicheta** [comment]
Ok. Dziękuję za szybką odpowiedź. Temat do zamknięcia.
