### ISSUE TITLE
Błąd "receiver.email","userMessage":"Podany hash-mail jest niepoprawny"

### ISSUE THREAD

**Issue by pietruszysko** [allegro/allegro-api#7930]
Występuje problem:
 - [ X] z zasobem REST API / with a REST API resource
 - [ X] ze środowiskiem produkcyjnym / with the production environment

Jeśli zgłaszasz problem z zasobami REST API:
- zasób: https://api.{environment}/parcel-management/parcel-create-commands/adc7a9c4-1d9c-4d46-9a83-309057212f58
Otrzymuje błąd 
{"code":"SERVICE_NOT_AVAILABLE","message":"Requested hashed mail was not recognized","details":"Requested hashed mail was not recognized","path":"receiver.email","userMessage":"Podany hash-mail jest niepoprawny"},"date":"2023-11-07 13:00:18"}
Mail jest prawidłowy - taki jak w zamówieniu allegro: 267cdmkia5+720f03087@allegromail.pl

**Comment by Bober95** [comment]
Potwierdzam, również mam ten błąd

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że występuje chwilowy problem z nadawaniem przesyłek, przepraszam za niedogodności. Już pracujemy nad poprawką, które wyeliminuje ten błąd - poinformuję w wątku.

**Comment by PrzemyslawLukanowski** [comment]
Problem już nie powinien występować.
