### ISSUE TITLE
Incorrect value of the EAN/ISBN/ISSN parametr

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#7931]
Hi there, 

we have a question about this error message: 
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/15335eac-a3e3-4c28-adc1-5e289bed8bb7)

It is said in the documentation that it is enough to send only 1 identifier so in this case it was MPN which is 1374086080.

When I tried to use the MPN to list a product manually, I actually found a product with this MPN:
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/5c4d9ff4-230a-4275-b178-7ab99f4dfa44)

So why was not the offer connected to the product card based on this number and the error message is offering us the EAN number of the product you see in the screenshot? 

Thank you in advance!

Best,

Dominika

**Comment by MartaNowaczyk** [comment]
To more precisely verify this case please provide the trace-id for the call with the error, then I will see what exactly is being sent to us and will be able to help. You can also provide the full request and response.

**Comment by dominikahr** [comment]
Sorry for not including that, here is the trace ID: 343b074323b59755

**Comment by MartaNowaczyk** [comment]
Thank you. We are verifying this case, I will come back with information.

**Comment by MartaNowaczyk** [comment]
This is a bug on our side. We are working on a solution to this problem.

**Comment by MartaNowaczyk** [comment]
We have implemented the fix. Sorry for the inconvenience.
