### ISSUE TITLE
Problem z przesłaniem załącznika

### ISSUE THREAD

**Issue by Darayavus** [allegro/allegro-api#7932]
Cześć,
identyczny problem opisany był w tym wątku:
https://github.com/allegro/allegro-api/issues/7742
jednak nie widzę tam rozwiązania...

Testuję na sandboxie przesyłanie załączników. Plik PDF przechodzi bez problemu. Natomiast pliki JPG, PNG, JPEG dla typów ENERGY_LABEL lub TIRE_LABEL generują błąd Invalid file format.
Content-Type jest prawidłowy dla każdego pliku. 
Kiedy dodaję te same pliki przez formularz na portalu, załącznik tworzony jest prawidłowo.

`curl -X PUT 'https://upload.allegro.pl.allegrosandbox.pl/sale/offer-attachments/458f064d-720e-4a34-a186-abd9cdcb4b35'
 -H 'Authorization: Bearer '
 -H 'Accept: application/vnd.allegro.public.v1+json' 
 -H 'Content-Type: image/png' 
 --data-binary '@pnggrad16rgb.png'`
trace-id: d0b6563870c7bd5d

Proszę o jakąś podpowiedź :)
Pozdrawiam
Darek

**Comment by MartaNowaczyk** [comment]
Podeślij jeszcze plik, który wysyłasz, abyśmy mieli pewność, że format jest prawidłowy. Zweryfikuję to jeszcze z zespołem odpowiedzialnym za tę funkcjonalność. Content-type wygląda na poprawny.

**Comment by Darayavus** [comment]
![etykieta_energetyczna](https://github.com/allegro/allegro-api/assets/89593636/f6601666-7a70-4c63-82d1-c1071855c0bc)
![etykieta_energetyczna2](https://github.com/allegro/allegro-api/assets/89593636/6e8ec134-b97c-4761-bdc0-e4540b6f2043)
![pnggrad16rgb](https://github.com/allegro/allegro-api/assets/89593636/d83e9a85-31cf-4541-a224-2f881f5df0b8)

Trzy przykładowe pliki na których próbowałem.

**Comment by MartaNowaczyk** [comment]
Wszystkie 3 pliki dodałam bez problemu jako załącznik. Formaty są ok. Weryfikujemy jeszcze ten przypadek, także wrócę z informacją.

**Comment by Darayavus** [comment]
OK, dziękuję.

**Comment by MartaNowaczyk** [comment]
Nie odnotowaliśmy problemów z usługą załaczników. Nie znaleźliśmy innej przyczyny, jak to, że plik, który przesyłasz jest niepoprawny. Nie mamy bardziej szczegółowych danych by móc Ci pomóc, ale rekomendujemy byś spróbował jednak z całkiem innym plikiem. Choć u mnie, te przesłane przez Ciebie przechodziły, gdy testowałam w Postmanie. Być może coś po drodze jeszcze się z nimi dzieje, ale to Ty najlepiej wiesz jak działasz, więc będziesz musiał to sprawdzić po swojej stronie.

**Comment by Darayavus** [comment]
Dobra, dziękuję za podpowiedź.
