### ISSUE TITLE
Brak GLS oraz FEDEX na serwisach 

### ISSUE THREAD

**Issue by Gradziu31** [allegro/allegro-api#7933]
W dostępnych wysyłkach nie ma opcji GLS oraz FEDEX, jak w inny sposób zamawiać kurierów przez shipments api jeśli nie mam ich do wyboru na liście, czy coś musze zrobić dodatkowo uzupełnić, aby Ci przewoźnicy pojawili się na liście?
Lub prosze o jakieś inne rozwiązanie, np. jeśli mam stworzyć paczkę przez moje api z GLS lub Fedex i podać numer śledzenia paczki do allegro

**Comment by Lukasz-Zurek** [comment]
Potwierdzam - tych przewoźników nie mamy w usłudze "Wysyłam z Allegro". [Tutaj](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/wysylam-z-allegro-narzedzie-do-nadawania-przesylek-bezposrednio-z-konta-E7doGw8VgI1#z-jakich-metod-dostawy-skorzystasz-w-wysylam-z-allegro) znajdziesz pełną listę metod dostawy obsługiwanych przez WZA.

W tej sytuacji musisz we własnym zakresie zintegrować się z przewoźnikiem - bezpośrednio, lub za pośrednictwem narzędzia/aplikacji zewnętrznej, która takie połączenie oferuje. Nie mogę tutaj jednak zasugerować konkretnego rozwiązania, decyzja należy do Ciebie.

Dodam również, że integracja przewoźnika z naszym API polega na tym, że pobierane są zamówienia, w których kluczowy jest adres e-mail odbiorcy identyfikujący z konkretnym zamówieniem - dzięki czemu numer przesyłki dodawany jest automatycznie w momencie zlecenia przesyłki.
