### ISSUE TITLE
Odblokowanie konta Allegro sandbox

### ISSUE THREAD

**Issue by natdev-developer** [allegro/allegro-api#7934]
Cześć,

mamy zablokowane konto w allegro sandbox. 
Dokonaliśmy fikcyjnej wpłaty i infomacja o blokadzie w allegro sandbox zniknęła, lecz komunikując się z api otrzymujemy błąd "Product proposals unauthorized according to blockade on user's account." 

Prośba o odblokowanie konta allegro sandbox, client: 44324115.

**Comment by PrzemyslawLukanowski** [comment]
Cześć, ściągnąłem blokadę, spróbuj proszę ponowić operację.

**Comment by natdev-developer** [comment]
Działa, dzięki.
