### ISSUE TITLE
Wystawianie przedmiotów jako nie tylko na allegro lokalnie w ramach pracy inżynierskiej.

### ISSUE THREAD

**Issue by MikolajMalcherek** [allegro/allegro-api#7935]
Witam, chciałbym przetestować działanie mojej aplikacji oraz działania API, jednak nie posiadam własnej działalności. Czy w takim przypadku chcąc w ramach pracy inżynierskiej utworzyć konto firmowe - można w jakiś sposób założyć je bez posiadania numeru NIP oraz działalności?

**Comment by PrzemyslawLukanowski** [comment]
W takim przypadku zachęcamy do założenia konta testowego na naszym dedykowanym środowisku testowym - allegro.pl.allegrosandbox.pl. Możesz tutaj założyć konto firmowe, przekazując fikcyjne dane.

**Comment by MikolajMalcherek** [comment]
> W takim przypadku zachęcamy do założenia konta testowego na naszym dedykowanym środowisku testowym - allegro.pl.allegrosandbox.pl. Możesz tutaj założyć konto firmowe, przekazując fikcyjne dane.

Bardzo dziękuję za odpowiedź :)
