### ISSUE TITLE
Kampanie na allegro.cz

### ISSUE THREAD

**Issue by Darayavus** [allegro/allegro-api#7936]
Cześć,
pytałem już o to jakiś czas temu, ponawiam :)
https://github.com/allegro/allegro-api/issues/7724

Czy coś się zmieniło w tym temacie? Przetestowałem zasób, i mimo dołączonych kampanii do kilku ofert CZ, nie widzę ich w reponse.

Czy oferty na allegro.cz, które od przyszłego tygodnia wezmą udział w Black Week będą zwracane przez zasób /sale/badges ?

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Nie wprowadzaliśmy zmian na tym polu, w odpowiedzi zasobu otrzymasz tylko oferty w ramach allegro-pl.

**Comment by Darayavus** [comment]
Dziękuję, a czy jest może jakaś zakładana data, kiedy takie zmiany mogą się pojawić?

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale nie mamy jeszcze dokładnie zaplanowanej daty zmian.

**Comment by Darayavus** [comment]
Dzięki za info, pozdrawiam.
