### ISSUE TITLE
Nie możemy wyświetlić strony Numer błędu: 3d5d55f63931bf9b

### ISSUE THREAD

**Issue by skutop001** [allegro/allegro-api#7938]
Zgodnie z dokumentacją API, używanie przekierowanej strony logowania nie powróciło do mojego uri. Uri, które zarejestrowałem i używałem, są spójne. Konkretne żądanie to: https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=C13A454E8ca542B8A8F5Afac1025C925&redirect_uri=https://skutop.cn/terrace/storeAuthorization

Czy możesz mi pomóc zrozumieć, dlaczego problem jest? Studiowałem kilka metod, z których wszystkie są związane. Proszę pomóż mi

**Comment by skutop001** [comment]
![1699514308377](https://github.com/allegro/allegro-api/assets/150323365/8c6138e4-b676-4211-b132-09fbc9ddfb77)

**Comment by MartaNowaczyk** [comment]
Spróbuj z poprawnym client_id=c13a454e8ca542b8a8f5afac1025c925

**Comment by skutop001** [comment]
Użyłem c13a454e8ca542b8a8f5afac1025c925, ale automatycznie zmienił się na dużą literę po otwarciu linku,

**Comment by MartaNowaczyk** [comment]
Oprócz błędnego client ID, w niektórych autoryzacjach był też problem z redirect_uri, ale z tego co widzę udało Ci się uzyskać Access Token.
