### ISSUE TITLE
Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej

### ISSUE THREAD

**Issue by jwmbb** [allegro/allegro-api#7939]
- [X ] ze środowiskiem produkcyjnym / with the production environment

Dzień Dobry,
Od jakiegoś czasu mamy błędy które powtarzają się do niezależnych paczek i nie możemy znaleźć przyczyny. 
W logach dostajemy błąd :
"message":"Problem with dispatch. Contact us, and we will help as soon as possible.","details":null,"path":"","userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}]}"

Czy możemy prosić o sprawdzenie UUID :

aaadf452-e459-4a51-9916-bd48a0c49e0f
2b8c6a73-4b33-47b1-ab35-d47e4bb73485
f9d14685-1d29-45bb-841b-a43b05cc1f4b
0c2c3147-1f9c-44b5-872f-77abc10e2820

**Comment by MartaNowaczyk** [comment]
Z tego co udało mi się ustalić, problemem jest brak adresu w [książce adresowej Wysyłam z Allegro](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia). Trzeba tam dodać poprawny adres.

**Comment by artbski** [comment]
Mam podobny komunikat dla id: 24891285-96fe-45d2-a772-46bbc78cb05a
Prośba o sprawdzenie.

**Comment by Lukasz-Zurek** [comment]
@artbski Upewnij się co do poprawności wskazanego id: 24891285-96fe-45d2-a772-46bbc78cb05a - nie odnotowałem takiego żądania w ostatnich dniach.

**Comment by PrzemyslawLukanowski** [comment]
@artbski Jest to błąd po stornie operatora zewnętrznego, weryfikujemy tę sytuację. Wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
@artbski Wgraliśmy poprawkę, problem nie powinien już występować.
