### ISSUE TITLE
Prośba o zidentyfikowanie produktu po kodzie API.

### ISSUE THREAD

**Issue by erozkoszpl** [allegro/allegro-api#7940]
nr produktu w api: 56f794b2-650b-4d76-8e5b-667c41766c26 link do produktu w API: https://api.allegro.pl/sale/products/56f794b2-650b-4d76-8e5b-667c41766c26%60 Produkt powoduje błąd w przenoszenia produktów do systemu linker w usłudze fullfilment inpost.

**Comment by MartaNowaczyk** [comment]
Nie widzę u nas takiego produktu. 

Edytowałam tytuł - przeniosłam część treści do opisu, aby zachować porządek.

**Comment by erozkoszpl** [comment]
Co może być powodem i co powinniśmy w takim przypadku zrobić?

**Comment by MartaNowaczyk** [comment]
Dzięki za numer oferty. Tego produktu nie zwracamy przez API, ale w podanej ofercie jest. Weryfikuję to z zespołem odpowiedzialnym za produkty, także wrócę z informacją.

**Comment by erozkoszpl** [comment]
Dobrze, czekamy.

**Comment by MartaNowaczyk** [comment]
Produkt 56f794b2-650b-4d76-8e5b-667c41766c26 został zamieniony na e539b2f1-f43a-4947-b8f5-3b5b7094a77a i taki powinien być teraz w ofercie. Potwierdź proszę, czy teraz jest ok.
