### ISSUE TITLE
Katalog Produktów

### ISSUE THREAD

**Issue by PiotrPiotrP** [allegro/allegro-api#7942]
Zrobiłem testowe zapytanie 
11/09 15:10:53.602  GET    https://api.allegro.pl.allegrosandbox.pl/sale/products?phrase=Bluza requestBody= 
responseBody={"products":[{"id":"0080ae2b-e571-4acd-b000-8b82021ac2b5","name":"New era Bluzy Sportowe S 11546179-S","category":{"id":"87843","similar":[{"id":"147292"},{"id":"261454"},{"id":"260891"},{"id":"260893"},{"id":"258752"},{"id":"259102"},
...
{"id":"121882","name":"Zdrowie","count":0}],"path":[{"id":"954b95b6-43cf-4104-8354-dea4d9b10ddf","name":"Allegro"}]},"filters":[],"nextPage":{"id":"AoMhVAj%2Ff%2F%2F%2FPwUwOGYxMTE4Mi1lMzRiLTQ4ZDMtYTUzMC02ZWFkYjRjY2ZhNzc%3D"}} trace-id=[4743eb68ce3e81e3]
jak powinno wyglądać zapytanie o drugą stronę?
Czy można z katalogu produktów wyszukiwać po numerze aukcji lub po external_id?

**Comment by PrzemyslawLukanowski** [comment]
Aby zobaczyć wyniki z kolejnej strony, użyj parametru `page.id`, w którym przekaż wartość, którą zwróciliśmy w polu `nextPage.id`. W katalogu produktów nie umożliwiamy wyszukiwania według numeru oferty lub external.id.

**Comment by PiotrPiotrP** [comment]
Tak wiem że trzeba użyć parametru nextPage.id tylko czy to powinno wyglądać tak https://api.allegro.pl.allegrosandbox.pl/sale/products?phrase=Bluza&nextPageId=<nextPage.id> czy https://api.allegro.pl.allegrosandbox.pl/sale/products?phrase=<nextPage.id> czy jeszcze jakoś inaczej.

**Comment by PrzemyslawLukanowski** [comment]
Nie `nextPage.Id`, tylko `page.id` :) Zapytanie powinno zatem wyglądać tak - `GET /sale/products?phrase=Bluza&page.id=<wartość z nextPage.id>`

**Comment by PiotrPiotrP** [comment]
Dziękuję

**Comment by PiotrPiotrP** [comment]
Po pobraniu parametrów dla kategorii https://api.{environment}/sale/categories/{categoryId}/parameters mam pole parameters/requierd czy jego odpowiednikiem w https://api.{environment}/sale/products/{productId} jest product/parameters/options/identifiesProduct czy jakieś inne?

**Comment by PrzemyslawLukanowski** [comment]
Są to inne pola:

- w zasobie [/sale/categories/{categoryId}/parameters](https://api.%7Benvironment%7D/sale/categories/%7BcategoryId%7D/parameters) pole `required` mówi o tym, czy dany parametr jest wymagany do utworzenia oferty, `requiredForProduct` - do utworzenia nowego produktu;
- w zasobie [/sale/products/{productId}](https://api.%7Benvironment%7D/sale/products/%7BproductId%7D) pole `identifiesProduct` wskazuje, czy dany parametr identyfikuje produkt, tzn. czy np. możesz zmienić jego wartość podczas edycji oferty.

**Comment by PiotrPiotrP** [comment]
Dziękiuję

**Comment by PunktAutoCzesci** [comment]
Cześć,
mam problem z odczytaniem kolejnej strony. 
phrase: "2004"
mode:  MPN
'/sale/products?phrase=2004&mode=MPN'

w odpowiedzi dostaje: nextPage: 'AoMhVAg%2BmiCbPwUwN2Q5N2ExOC1iMjlkLTQ3OTYtOTlkOS1kYzBmM2Y2MzFhM2M%3D'

Pytanie: jak dokłądnie powinien wyglądać adres zapytania o kolejną stronę? 

czy powinno być page.id czy page%2Eid
czy wartość z nextPage trzeba dodatkowo zakodować do URI ? "AoMhVAg%252BmiCbPwUwN2Q5N2ExOC1iMjlkLTQ3OTYtOTlkOS1kYzBmM2Y2MzFhM2M%253D" ?

tak nie działa
/sale/products/phrase=2004&mode=MPN&page.id=2BmiCbPwUwN2Q5N2ExOC1iMjlkLTQ3OTYtOTlkOS1kYzBmM2Y2MzFhM2M

Request URL is not normalized.

proszę o przykład poprawnego adresu.

**Comment by PiotrPiotrP** [comment]
Jak tworzę własny produkt i chcę sprawdzić czy istnieje w Katalogu produktów taki produkt w którym zgadzają się obowiązkowe parametry. Sprawdzenia mogę dokonać tylko szukając po  ean i nazwie czy są jeszcze inne opcje?

**Comment by PrzemyslawLukanowski** [comment]
Możesz jeszcze przeszukać katalog za pomocą MPN, jest to wartość związana z numerem katalogowym producenta. Więcej informacji na ten temat znajdziesz [w naszym newsie](https://developer.allegro.pl/news/usprawnilismy-wyszukiwanie-produktow-w-naszym-katalogu-7G92kkW53fY).

**Comment by PiotrPiotrP** [comment]
ok, ale po innych parametrach nie? Czyli dopasować muszę po ean, nazwa, MPN a co w sytuacji jak pod podanym eanem jest produkt ale ma inne pola obowiązkowe?

**Comment by PrzemyslawLukanowski** [comment]
Możesz w wyszukiwaniu dodać także odpowiednie filtry dla danej kategorii (w takim przypadku w wywołaniu musisz uwzględnić parametr category.id). Przykłady filtrów znajdziesz [w naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#typy-filtrow-i-stronicowanie).

Jeśli pola obowiązkowe są różne, tzn, uważasz, że w naszej bazie występuje błąd, to w takiej sytuacji możesz zasugerować zmianę danych w produkcie - zrobisz to [za pomocą API ](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-zglosic-blad-w-produkcie) lub przez formularz na stronie - https://allegro.pl/moje-allegro/sprzedaz/produkt/zglos-blad/{productID}.

**Comment by PiotrPiotrP** [comment]
Lista filtrów:

nie jest tożsama z wartościami, które otrzymasz dla GET /sale/categories/{categoryId}/parameters. Filtr tworzysz, podając identyfikator filtra i identyfikator szukanej wartości, na zasadzie {filter.id}={filter.value},
To oznacza że nie mogę od razu filtrować tylko muszę najpierw zrobić zapytanie i jak w odpowiedzi dostanę filtry to mogę zawęzić wyszukiwanie. filtr.id będzie inny niż id parametrów. Czy to się zgadza?

**Comment by PrzemyslawLukanowski** [comment]
Tak, zgadza się - filtry poznasz dopiero, po dołączeniu do zapytania category.id i tak, filtr.id nie musi być identyczny co parameter.id.

**Comment by PiotrPiotrP** [comment]
Dziękuję

**Comment by PiotrPiotrP** [comment]
Jeżeli nie znalazłem produktu w katalogu i chce stowrzyć nowy produkt to czy muszę najpierw skorzystać z https://api.{environment}/sale/product-proposals wziąść id produktu z odpowiedzi i potem stworzyć ofertę https://api.{environment}/sale/product-offers w której podam to id czy mogę od razu dodawać ofertę i proponować produkt przez https://api.{environment}/sale/product-offers, wpisując w polu productSet dane produktu, obowiązkowe parametry itd.?

**Comment by PrzemyslawLukanowski** [comment]
Wybór należy do Ciebie - przewagą zasobu /sale/product-offers jest to, że za pomocą jednego żądania możesz - tak jak napisałeś - od razu wystawić aktywną ofertę połączoną z produktem. W przypadku product-proposals musisz osobno wysłać zdjęcia na nasz serwer oraz owy produkt utworzyć - korzystając z product-offers, wykonasz mniej requestów.

**Comment by PiotrPiotrP** [comment]
Super, dziękuję

**Comment by PiotrPiotrP** [comment]
W dokumentacji jest: 
"Parametry ofertowe są związane z indywidualną ofertą, np. stan, data ważności, etc., a nie z cechą konkretnego produktu. Informację o tym, które parametry są ofertowe, a które produktowe, znajdziesz w polu options.describesProduct:

true - parametr produktowy,

false - parametr ofertowy."
Czy to jest tak że describeProduct = true, można dodać tylko do produktu a describeProduct = false tylko do oferty czy np. describeProduct = true może być jako opcjonalny parametr w ofercie lub na odwrót?

**Comment by PiotrPiotrP** [comment]
Dziękuję

**Comment by PiotrPiotrP** [comment]
Do tej pory jak wystawiałem ofertę za pomocą POST /sale/offers to pole publication mam tak ustawione "publication":{"startingAt":"2023-10-06T18:15:36.000Z","duration":"PT120H","republish":true}, nie daje statusu, i od razu aktywuję ofertę za pomocą sale/offer-publication-commands. Jeżeli teraz na nowym endpoincie wyślę w polu publication "publication":{"startingAt":"2023-10-06T18:15:36.000Z","duration":"PT120H","republish":true}, nie zaznaczając żadnego statusu to czy muszę tą ofertę aktywować czy sama się aktywuje?

**Comment by MaciejFrackowiak** [comment]
Korzystając z POST /sale/product-offers oferta jest domyślnie określana jako aktywna. Jeśli nie chcesz by oferta była od razu aktywna, musisz w polu "publication.status" przekazać wartość "INACTIVE" - opisaliśmy to dokładnie w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#szkic-oferty).

**Comment by PiotrPiotrP** [comment]
Dziękuję

**Comment by PiotrPiotrP** [comment]
To czy Ean jest pbowiązkowym parametrem zależy od kategorii? Można go dodać jako nieobowiązkowy parametr?

**Comment by PiotrPiotrP** [comment]
Jest możliwe że ean jest obowiązkowy dla jednej marki a dla innej nie?

**Comment by MaciejFrackowiak** [comment]
Tak, jest możliwe, że dla niektórych marek będzie wymagany, a dla innych nie. Ostatnia ze zmian w tzw. parametrach zależnych opisywana była w [poście](https://github.com/allegro/allegro-api/issues/6997).

**Comment by PiotrPiotrP** [comment]
Dziękuję za poprzednią odpowiedź. 
Mam jeszcze pytanie o obowiązkowość parametrów. Dla kategorii 124264. Dostałem listę parametrów w których ean pola required i requiredForProduct ma na true ale ma jeszcze w requiredIf parametersWithValue 11323 i 3786. 
Pierwsze pytanie to czy pola required i requiredForProdcut zawsze przychodzą z wartością true jeżeli requiredIf nie jest nullem?
Drugie czy te zależności dotyczą obowiązku wypełnienia bądź nie tego parametru dla oferty i produktu, czy np. tylko dla oferty?

**Comment by MaciejFrackowiak** [comment]
Zgadza się, dla kategorii 124264 parametr EAN jest obowiązkowy podczas tworzenia nowych produktów oraz dla ofert. W przypadku ofert powstaje jednak zależność - EAN jest wymagany, gdy Stan ma tylko wartość Nowy ("11323_1"), a także parametr Marka (3786) przyjmuje jedną z podanych wartości. Wartość dla "requiredIf" może być null'em, a obowiązkowość dla produktu i oferty będzie true. Zależności odnoszą się do ofert - w przypadku produktów decydująca jest flaga "requiredForProduct".

**Comment by PiotrPiotrP** [comment]
Czyli jak chce mieć ofertę połączoną z produktem to w tym przypadku ean i tak jest obowiązkowy nie ważne jakie wartości będę miał w stan i marka?

**Comment by MaciejFrackowiak** [comment]
Produkt dla większości kategorii Allegro musi posiadać wartość GTIN (EAN) z uwagi na fakt, że produkty dodane do naszego katalogu odzwierciedlają produkty w stanie Nowy. Zależność tu występująca oddaje w pełni założenie - EAN jest obowiązkowy jeśli m.in. parametr Stan w ofercie przyjmie wartość "11323_1", czyli Nowy.

**Comment by PiotrPiotrP** [comment]
Ok, jeszcze potrzebuję jedną informację żeby obsłużyć wszystkie przypadki. W podanej wyżej kategorii chce wystawić ofertę z używanym produktem, za pomocą  POST /sale/product-offers tego produktu nie ma w katalogu i chce jednym zapytaniem stworzyć ofertę i produkt. Czy ean w takiej sytuacji będzie wymagany?

**Comment by MaciejFrackowiak** [comment]
Nie, nie będzie wymagany.

**Comment by PiotrPiotrP** [comment]
Dziękuję

**Comment by PiotrPiotrP** [comment]
Dodaję to na sandboxa

**Comment by PrzemyslawLukanowski** [comment]
@PiotrPiotrP Według naszych logów zdjęcia zostały usunięte na etapie tworzenia produktu ze względu na zbyt mały rozmiar.

**Comment by PiotrPiotrP** [comment]
Przy drugiej ofercie mam to samo a to są oferty które przez stary endpoint bez problemu się wystawiały czy w nowym są jakieś inne obostrzenia dla rozmiarów zdjęć?

**Comment by PrzemyslawLukanowski** [comment]
Taka sytuacja może mieć miejsce, jeśli zdjęcia dodajesz na poziomie oferty (bezpośrednio w `"images"`) - dla zdjęć produktów  (`"product.images"`) walidacja rzeczywiście jest bardziej restrykcyjna.

**Comment by PiotrPiotrP** [comment]
Te zdjęcia mają szerokość 437 pikseli i długość 926 czyli spełniają wymogi https://allegro.pl/dla-sprzedajacych/zasady-dla-zdjec-w-galerii-i-w-opisie-YLlAAa2oXf7.

**Comment by PiotrPiotrP** [comment]
a tutaj https://allegro.pl/dla-sprzedajacych/zasady-dla-zdjec-w-galerii-i-w-opisie-YLlAAa2oXf7 jest napisane Obowiązują te same zasady, jak dla zdjęć w ofercie.

**Comment by PiotrPiotrP** [comment]
Czy w produkSet można zrobić tak ,"images":["https://a.allegroimg.com/original/110e6e/242f7d4d4edd97626e630e268b07","https://a.allegroimg.com/original/110fb1/a7534bc244fa8ce5aff9eefa15dd","https://a.allegroimg.com/original/110786/05946fc94e47839cbcfb9f3eccbb","https://a.allegroimg.com/original/114dbf/b56b142747e59723378601907db9"]}}], w sensie czy można tu wysyłać adres zdjęcia z allegro?

**Comment by PiotrPiotrP** [comment]
Pod tym linkiem jest obrazek https://images.stocksell.io/images/2b/2b94606a-c64f-43ea-9d8e-347b6f7f916b a dostałem odpowiedź od allegro że nie Podany adres obrazka jest nieprawidłowy. Invalid image address. OfferImagesNotFoundException . Trace-id=[ece1824a95d74f4f].

**Comment by PrzemyslawLukanowski** [comment]
Tak, możesz tak zrobić, jednak pamiętaj o zgodności środowisk, tzn. jeśli korzystasz z Sandboxa, to zdjęcie musi wcześniej zostać załadowane właśnie na sandboxowy serwer, prawidłowy link, to np. https://a.allegroimg.allegrosandbox.pl/original/112c5c/2f326b82426a8f090eac2ca183ed.

Kwestię weryfikacji rozmiarów obrazka wyjaśniam jeszcze z odpowiednim zespołem, wrócę z informacją.

**Comment by PiotrPiotrP** [comment]
Dziękuję. To jeszcze oprócz rozmiarów mam pytanie dlaczego ten link nie zadziałał https://a.allegroimg.allegrosandbox.pl/original/112c5c/2f326b82426a8f090eac2ca183ed ?

**Comment by PiotrPiotrP** [comment]
Chodziło o ten link https://images.stocksell.io/images/2b/2b94606a-c64f-43ea-9d8e-347b6f7f916b

**Comment by PrzemyslawLukanowski** [comment]
Wykonałem przed chwilą test i ten link również działa. Nie zadziała, jeśli jest przesłany na nasz produkcyjny serwer (czyli korzystałbyś z linku https://a.allegroimg.com...), a próba utworzenia produktu następuje na środowisku testowym i odwrotnie.

**Comment by PiotrPiotrP** [comment]
Ok, tam wcześniej wkleiłem zły link chodzi o ten z mojego serwera https://images.stocksell.io/images/2b/2b94606a-c64f-43ea-9d8e-347b6f7f916b czy tu też ma znaczenie czy to jest produkcyjne środowisko czy testowe?

**Comment by PrzemyslawLukanowski** [comment]
Tak, właśnie do tego linku się odniosłem, link https://images.stocksell.io/images/2b/2b94606a-c64f-43ea-9d8e-347b6f7f916b powinien zadziałać na obu środowiskach, przed chwilą wykonałem testy. Miałem na myśli, że nie zadziałałby, jeśli przesłałbyś go na nasz produkcyjny serwer i skorzystał z nowego linku https://a.allegroimg.com/... .

**Comment by PiotrPiotrP** [comment]
Ok, spróbuję jeszcze raz i jak by nie poszło to wyślę traceId

**Comment by PiotrPiotrP** [comment]
Dostałem błąd. 
POST   https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/ requestBody={"productSet":[{"quantity":{"value":1},"product":{"name":"Biała bluzka L JAA","idType":"GTIN","parameters":[{"id":"201021","valuesIds":["201021_2493"]},{"id":"59","valuesIds":["59_9"]},{"id":"54","valuesIds":["54_5"]},{"id":"3786","valuesIds":["3786_1648501"]},{"id":"15851","valuesIds":["15851_1"]},{"id":"3766","valuesIds":["3766_1"]},{"id":"216925","valuesIds":["216925_1191143"]},{"id":"201025","valuesIds":["201025_2521"]},{"id":"18293","valuesIds":["18293_1"]},{"id":"127708","valuesIds":["127708_10"]},{"id":"201017","valuesIds":["201017_2337"]},{"id":"249512","valuesIds":["249512_1647414"]}],"category":{"id":"76034"},"images":["https://images.stocksell.io/images/b8/b86b523a-477b-4cb5-9baa-5ace7b09e305","https://images.stocksell.io/images/f8/f8371946-779c-4d9f-b78c-9e676a5e7372"]}}],"category":{"id":"76034"},"delivery":{"shippingRates":{"id":"44e79fb3-0c23-45d2-98f1-825d23633468"},"handlingTime":"PT24H"},"publication":{"startingAt":"2023-12-19T17:34:49.000Z","status":"INACTIVE","republish":false},"language":"pl-PL","afterSalesServices":{"impliedWarranty":{"id":"9e3e2cef-b2cc-4971-941a-249111e4a4c2"},"returnPolicy":{"id":"0c667bcc-09c5-433e-b9a1-1e66ef233405"},"warranty":{"id":"38964799-6596-4bb3-847e-781925b46240"}},"stock":{"available":1,"unit":"UNIT"},"parameters":[{"id":"11323","valuesIds":["11323_1"]}],"name":"Biała bluzka L JAA","payments":{"invoice":"VAT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":40.99,"currency":"PLN"}},"location":{"city":"Skawina","countryCode":"PL","postCode":"32-050","province":"MALOPOLSKIE"},"images":["https://images.stocksell.io/images/b8/b86b523a-477b-4cb5-9baa-5ace7b09e305","https://images.stocksell.io/images/f8/f8371946-779c-4d9f-b78c-9e676a5e7372"],"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003ch2\u003eBiała bluzka\u003c/h2\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11ace5/19637321431db2966cb0920b4d1e"},{"type":"TEXT","content":"\u003ch2\u003eOpis Produktu\u003c/h2\u003e\u003cul\u003e\u003cli\u003e\u003cb\u003eMarka\u003c/b\u003e Shein\u003c/li\u003e\u003cli\u003e\u003cb\u003eKolor\u003c/b\u003e Biały\u003c/li\u003e\u003cli\u003e\u003cb\u003eSkład\u003c/b\u003e 95% wiskoza 5% elastan \u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka papierowa\u003c/b\u003e Brak\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka wewnętrzna\u003c/b\u003e \tTak\u003c/li\u003e\u003cli\u003e\u003cb\u003eRozmiar\u003c/b\u003e L\u003c/li\u003e\u003cli\u003e\u003cb\u003eCena katalogowa\u003c/b\u003e 40,99 zł\u003c/li\u003e\u003cli\u003e\u003cb\u003eUwaga\u003c/b\u003e stan idealny\u003c/li\u003e\u003c/ul\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11b135/53ef749549818e2ca4b8e7cb7cd3"}]}]},"external":{"id":"stocksell_896530176"},"taxSettings":{"rates":[{"countryCode":"PL"}]}} exception=Niepoprawna odpowiedź z Allegro. Kod: 422. Błąd: OfferImagesNotFoundException Podany adres obrazka jest nieprawidłowy. Invalid image address. OfferImagesNotFoundException . Trace-id=[a07d639e5c7e7432].
Co tu jest nieprawidłowe?

**Comment by PrzemyslawLukanowski** [comment]
W sekcji `description` korzystasz z linków produkcyjnych - tj.  https://a.allegroimg.pl..  a nie https://a.allegroimg.allegrosandbox.pl.... Problem nie wystąpi, jeśli wcześniej załadujesz obrazki na serwer sandboxowy (wtedy otrzymasz linki właśnie w postaci https://a.allegroimg.allegrosandbox.pl....) lub skorzystasz z linków, które przesyłasz w `images` albo `product.images`.

**Comment by PiotrPiotrP** [comment]
Dziękkuję

**Comment by PiotrPiotrP** [comment]
Usuwany jest endpoint GET sale/offers/{offerId}, a czy sale/offers/?external.id={externalId}, sale/offers/?publication.status={status} i sale/offers/?offer.id={offerId} będą działać?

**Comment by PrzemyslawLukanowski** [comment]
Tak, będą działać. Nie usuwamy metody GET na zasobie /sale/offers, dzięki której możesz pobrać listę ofert.

**Comment by PiotrPiotrP** [comment]
Dziękuję

**Comment by PiotrPiotrP** [comment]
Dostałem taki błąd responseBody={"errorCode":"500","consoleMessage":"Niepoprawna odpowiedź z Allegro. Kod: 422. Błąd: ProductValidationException Nie można stworzyć produktu bez podania poprawnych wartości wszystkich parametrów wymaganych: [EAN (GTIN)] Unable to create product without proper values in all required parameters: [EAN (GTIN)] in category: 25956 productSet[0].product. Trace-id\u003d[5256f92ec7bc1e04].","resultType":"error","message":"Niepoprawna odpowiedź z Allegro. Kod: 422. Błąd: ProductValidationException Nie można stworzyć produktu bez podania poprawnych wartości wszystkich parametrów wymaganych: [EAN (GTIN)] Unable to create product without proper values in all required parameters: [EAN (GTIN)] in category: 25956 productSet[0].product. Trace-id\u003d[5256f92ec7bc1e04]."} 
A marka jest ustawiona jako Shein i stan jako nowy ean nie powinien być obowiązkowy.

**Comment by PrzemyslawLukanowski** [comment]
Według naszych logów jako markę przekazałeś:

```
                    "id": "7174_170",
                    "value": "Nike",
```

a dla niej wymagamy wartości w parametrze GTIN.

**Comment by PiotrPiotrP** [comment]
Dziękuję

**Comment by PiotrPiotrP** [comment]
Zastanawiam się dlaczego dostaję kod 303 
GET    https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/7740823899/operations/3e9076ab-6388-47b6-9100-07cf8004cd2c requestBody= responseStatusCode=303 responseBody= trace-id=[5a9c48cb64174747]
a aukcja 7740823899 jest aktywna?

**Comment by MaciejFrackowiak** [comment]
Jeśli operacja wystawiania oferty jest zakończona zwracamy 303 - zgodnie z [naszym poradnikiem](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#integracja-z-asynchronicznym-api).

**Comment by PiotrPiotrP** [comment]
Dziękuję
