### ISSUE TITLE
Weryfikacja konta na sandboxie

### ISSUE THREAD

**Issue by MikolajMalcherek** [allegro/allegro-api#7943]
Witam,
Od wczoraj otrzymuję komunikat "Aby aktywować sprzedaż zweryfikuj konto". Wykonałem weryfikacje konta bankowego ale ona również jest na etapie weryfikacji. Czy da się jakoś przyspieszyć ten proces?

**Comment by MikolajMalcherek** [comment]
Dodam również, że przy próbie aktywacji dwustopniowego logowania kod sms nie dociera.

**Comment by PrzemyslawLukanowski** [comment]
Podaj proszę login konta, aktywuję je. Na Sandboxie nie wysyłamy SMS, dwustopniowe logowanie w tym środowisku nie jest wymagane do rejestracji aplikacji. Jeśli jednak chcesz je włączyć, wpisz 12345, a przy logowaniu 123456.

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.

**Comment by nikodev13** [comment]
dzień dobry, mogę prosić o aktywację konta testowego na sandboxie? login: nrekiewicz @PrzemyslawLukanowski

**Comment by Lukasz-Zurek** [comment]
@nikodev13 Aktywowałem wskazane konto.

**Comment by nikodev13** [comment]
> @nikodev13 Aktywowałem wskazane konto.

dzięki wielkie :)
