### ISSUE TITLE
Uzyskanie statusu przesyłki zwrotnej Allegro OneBox / Uzyskanie nr przesyłki

### ISSUE THREAD

**Issue by Volix** [allegro/allegro-api#7945]
W aplikacji wczytuje zwroty klientów dokonane przez nich.
Jeśli klient zwraca paczkę poprzez np Inpost, DPD otrzymujemy nr tej przesyłki dzięki któremu możemy na bieżąco sprawdzać jej status. Sprawa się komplikuje w przypadku zwrotu poprzez OneBox, tutaj otrzymujemy nr wewnętrzny Allegro bez informacji o realnym przewoźniku (jak GLS, UPS). Czy jest jakiś sposób, aby to obejść?

Co chciałbym uzyskać:
- informacja o statusie paczki zwrotnej
- i/lub realny nr przesyłki

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję tę kwestię z zespołem odpowiedzialnym za zwroty, wrócę z informacją.

**Comment by PrzemyslawLukanowski** [comment]
Skonsultowałem tę kwestię z odpowiednimi zespołami - przykro mi, ale nie ma takiej możliwości, aby uzyskać te dane.
