### ISSUE TITLE
Forbidden status change for order

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#7946]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

trace-id: 65e38be51b68f92e\

 [errors] => Array
                (
                    [0] => Array
                        (
                            [code] => SellerOrdersStoreForbiddenException
                            [message] => Forbidden status change for order id b8b25db0-7b3e-11ee-a2cc-3d86913a4ec6.
                            [details] => 
                            [path] => /order/checkout-forms/b8b25db0-7b3e-11ee-a2cc-3d86913a4ec6/fulfillment
                            [userMessage] => Forbidden status change for order id b8b25db0-7b3e-11ee-a2cc-3d86913a4ec6.
                        )

                )

Co oznacza ten błąd i jak możemy to naprawić?

**Comment by Lukasz-Zurek** [comment]
Próbujesz zmienić status realizacji zamówienia będąc zalogowanym na koncie, do którego nie należy wskazane zamówienie. Dlatego zwróciliśmy błąd 403.
