### ISSUE TITLE
Dodawanie ofert - brak uprawnień

### ISSUE THREAD

**Issue by lukasz-lopata** [allegro/allegro-api#7949]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Jeśli zgłaszasz problem z zasobami REST API:
 - Zasób :  https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/
Request:
```
{
    "productSet": [
        {
            "product": {
                "name": "Kubek na herbatę a teraz nowy opis",
                "category": {
                    "id": "110886"
                },
                "id": "22d89493-7fd2-4b33-9f97-71b1daee0b56",
                "idType": "GTIN",
                "parameters": [
                    {
                        "id": "248811",
                        "name": "Marka",
                        "values": [
                            "inna"
                        ],
                        "valuesIds": []
                    },
                    {
                        "id": "220677",
                        "name": "Pojemność [ml]",
                        "values": [
                            "1"
                        ],
                        "valuesIds": []
                    },
                    {
                        "name": "Materiał wykonania",
                        "values": [
                            "ceramika"
                        ],
                        "valuesIds": []
                    },
                    {
                        "name": "Kod producenta",
                        "values": [
                            "1"
                        ],
                        "valuesIds": []
                    },
                    {
                        "id": "225693",
                        "name": "EAN (GTIN)",
                        "values": [
                            "12345670"
                        ],
                        "valuesIds": []
                    }
                ],
                "images": []
            },
            "quantity": {
                "value": 1
            }
        }
    ],
    "attachments": [],
    "stock": {
        "avaliabe": 150,
        "unit": "UNIT"
    },
    "parameters": [
        {
            "id": "11323",
            "name": "Stan",
            "values": [
                "Nowy"
            ],
            "valuesIds": []
        }
    ],
    "images": [],

    "delivery": {
        "handlingTime": "PT24H",
        "shippingRates": null,
        "additionalInfo": "string",
        "shipmentDate": "2019-08-24T14:15:22Z"
    }
}
```
Response

```
{
    "errors": [
        {
            "code": "OfferAccessDeniedException",
            "message": "Forbidden",
            "details": null,
            "path": "",
            "userMessage": "Access denied. You are not authorized to perform operations on the indicated offer"
        }
    ]
}

```
- TraceID: f90502f99962cf1c

Mimo, że wszystkie funkcje są przypisane między użytkownikiem a aplikacją, to otrzymujemy błąd 403. Daczego i jak ewentualnie włączyć odpowiednią funkcje?

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
@lukasz-lopata Przyczyną tej sytuacji jest niezweryfikowane konto firmowe, które odczytywane jest przez nas jako konto zwykłe. Najlepiej będzie jak ustalisz wszystkie wymagane dane firmy w [tej zakładce](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta), a następnie [skonfiguruj wypłaty](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty) i skorzystaj z naszego symulatora płatności.

**Comment by lukasz-lopata** [comment]
Pod linkiem konfiguruj wypłaty, strona nie istnieje.

**Comment by Lukasz-Zurek** [comment]
@lukasz-lopata Z tego co widzę - Twoje konto testowe jest już w pełni zweryfikowane. Natomiast błąd, który otrzymałeś po wysłaniu ostatniego żądania - dotyczy braku warunków zwrotów i reklamacji.

**Comment by WGRINGO** [comment]
Mam ten sam problem i nie mogę przeskoczyć.
 Konto aktywne pod sandboxem jako firma dawno temu.
Warunki reklamacji, gwarancji i zwrotów określone.

POST `https://api.allegro.pl.allegrosandbox.pl/sale/product-offers`

`{"productSet":[{"product":{"id":"77f26609-49e8-42f2-93e5-4e2cafc15b75","parameters":[{"id":"248811","valuesIds":["248811_950332"],"values":[],"rangeValue":null,"values":[]},{"id":"129912","valuesIds":["129912_268162"],"values":[],"rangeValue":null},{"id":"224017","valuesIds":null,"values":["7.3"],"rangeValue":null},{"id":"225693","valuesIds":null,"values":["5905548280578"],"rangeValue":null},{"id":"249474","valuesIds":null,"values":["1"],"rangeValue":null}],"images":[]}}],"language":"pl-PL","name":"RN-12 ROZDZIELNIA PLASTIKOWA NT 12M","category":{"id":"46107"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null}],"location":{"countryCode":"PL","province":"DOLNOSLASKIE","city":"\u017Bory","postCode":"43-333"},"afterSalesServices":{"impliedWarranty":{"id":"204965ef-8356-4e9c-86c6-b8e86ade8589"},"returnPolicy":{"id":"64d3ea6b-afbc-4637-a333-e64b813757c5"},"warranty":{"id":"6828950e-0519-4bc3-9273-da6e9f238df7"}},"delivery":{"shippingRates":{"id":"ccc800af-84a2-4fc4-91ad-4402a3157b80"},"handlingTime":"PT0S"},"payments":{"invoice":"VAT"},"promotion":{"emphasized":"False","bold":"False","highlight":"False","departmentPage":"False","emphasizedHighlightBoldPackage":"False"},"publication":{"republish":false,"status":"INACTIVE"},"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Opis<\/p>"}]}]},"stock":{"available":1,"unit":"UNIT"},"images":["https:\/\/a.allegroimg.allegrosandbox.pl\/original\/112ef8\/560120914014a0dfe6ab7279dbfc"],"external":{"id":"143736"},"sellingMode":{"price":{"amount":"123","currency":"PLN"}}}`

Zwraca:
`(403, '{"errors":[{"code":"OfferAccessDeniedException","message":"Forbidden","details":null,"path":"","userMessage":"Brak dostępu. Nie masz uprawnień do operacji na wskazanej ofercie"}]}')`

Co jeszcze może być nie tak ?

**Comment by Lukasz-Zurek** [comment]
@WGRINGO Przyczyną tej sytuacji było niezweryfikowane konto firmowe. Już zweryfikowałem konto, więc nie powinieneś już otrzymać błędu 403.

**Comment by Lukasz-Zurek** [comment]
@WGRINGO W przypadku tego drugiego konta mam problem z aktywacją. Skorzystajcie proszę ponownie z symulatora płatności, po ponownym skonfigurowaniu [ustawień wypłat](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty). Po wykonaniu tych czynności, daj proszę znać w wątku.

**Comment by WGRINGO** [comment]
Kolega zapłacił ponownie. Ciągle jest informacja, że konto czeka na autoryzację.

**Comment by Lukasz-Zurek** [comment]
@WGRINGO Aktywowałem już to konto.

**Comment by WGRINGO** [comment]
Dziękuję. Działa.
