### ISSUE TITLE
WEBAPI - problem z połączeniem od rana

### ISSUE THREAD

**Issue by Adam1610** [allegro/allegro-api#795]
Dzień dobry 

podczas próby połaczenia od rana wyskakuje wyjątek:

SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webapi.allegro.pl/service.php?wsdl' : Start tag expected, '<' not found in ....

Czy są prowadzone jakieś prace techniczne? Dotychczas wszystko działało bez problemu, i nic nie było zmieniane z mojej strony. Dzięki!

**Comment by Adam1610** [comment]
Tak. Przy każdej, wystawianie, zaczytywanie zamówień - obojętne. Żadne zmiany w kodzie ani na serwerze nie były robione. WSDL jest zawsze zaciągany od Was , z poziomu php co sugeruje komunikat Couldn't load from 'https://webapi.allegro.pl/service.php?wsdl'

Do wczoraj wszystko działało super, dziś rano wyrzuca błąd.

Korzystam z API: https://webapi.allegro.pl/service.php?wsdl

**Comment by Adam1610** [comment]
oto fragment kodu który nie działa i wyrzuca błąd:

$options['features'] = SOAP_SINGLE_ELEMENT_ARRAYS;
$allegro = new SoapClient("https://webapi.allegro.pl/service.php?wsdl", $options);

**Comment by Adam1610** [comment]
Dla ułatwienia, podam taki kod do testu - proszę zerknąć czy wykona się prawidłowo? :

<?

try {
	$options['features'] = SOAP_SINGLE_ELEMENT_ARRAYS;
	$allegro = new SoapClient("https://webapi.allegro.pl/service.php?wsdl", $options);
}
catch(Exception $e) {
	echo $e;
}

?>

wykonanie tego wyrzuca: 

SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webapi.allegro.pl/service.php?wsdl' : Start tag expected, '<' not found in /home/....../test.php:7 Stack trace: #0 /home/..../test.php(7): SoapClient->SoapClient('https://webapi....', Array) #1 {main}

**Comment by PawelTaberski** [comment]
Kod wygląda poprawnie, przetestowaliśmy i działa sprawdź proszę na innej maszynie, czy też występuje ten problem

**Comment by Adam1610** [comment]
A nie zablokowaliście mi konta? :)

**Comment by PawelTaberski** [comment]
W takim wypadku powinieneś otrzymać odpowiedni komunikat, jednakże możesz podesłać przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) klucz z jakiego korzystasz i sprawdzę. W zgłoszeniu zaznacz, że informacje podsyłasz do zgłoszenia numer 795 na GitHub.

**Comment by Adam1610** [comment]
Jednak to nie klucz zablokowany. Sprawdziłem na innej maszynie. Musiała nastąpić zmiana po stronie allegro, ponieważ tylko php7 łączy się z API. Starsze wersje nie. Zmienialiście coś po swojej stronie, ssl certyfikat ?

**Comment by pietrach** [comment]
Niestety ale u mnie ten sam problem

**Comment by PawelTaberski** [comment]
@pietrach u Ciebie problem jest inny pytasz po http zamiast https zmień i powinno być wszystko ok.
@Adam1610 upewnij się, że to nie jest kwesita TLS-a wymagamy TLS 1.1 lub 1.2. jednakże wymagamy tego już od czwerca.

**Comment by pietrach** [comment]
Niestety po zmianie dalej to samo:

{ SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webapi.allegro.pl/uploader.php?wsdl' : Start tag expected, '<' not found }

**Comment by pietrach** [comment]
@Adam1610 - na jakim Ty to masz serwerze ? Na home.pl ?

**Comment by pietrach** [comment]
Niby zaczęło działać w piątek po przejściu na wersję PHP 5.3. Teraz mam błąd inny:

**Niepoprawna wersja kategorii lub pól sprzedaży. Proszę sprawdzić lokalne wersje i uaktualnić oprogramowanie!**

**Comment by pietrach** [comment]
Niby udało się rozwiązać powyższy problem ale dziś jest inny:

**Niepoprawna wersja kategorii lub pól sprzedaży. Proszę sprawdzić lokalne wersje i uaktualnić oprogramowanie!**

**Comment by PawelTaberski** [comment]
Sprawdź czy masz najnowszą wartość klucza wersji np. przy pomocy metody [doQueryAllSysStatus](https://allegro.pl/webapi/documentation.php/show/id,62#method-output)

**Comment by pietrach** [comment]
Za każdym razem to robię przy próbie logowania używając metody **doQuerySysStatus**. Problem udało się rozwiązać zwiększając wersję PHP do 5.6

**Comment by magik092** [comment]
Witam,
Od godz. około 11:20 dzisiaj zaczęliśmy na okrągło dostawać przez SOAP błąd Not Found dotyczący różnych metod (np. doQuerySysStatus, doGetSiteJournalDeals, doGetSiteJournal a nawet dla doChangeItemFields).
Dla pewności pobraliśmy na nowo WSDL'a jednak to nie naprawiło problemu.

**Comment by PawelTaberski** [comment]
Wiemy o problemie i pracujemy już nad jego rozwiązaniem prosimy o cierpliwość.

**Comment by magik092** [comment]
Wygląda na to, że już sytuacja wróciła do normy

**Comment by PawelTaberski** [comment]
Dokładnie tak problem nie powinien już występować
