### ISSUE TITLE
Przejście z zasobu /parcel-management na /shipment-management - błąd 403

### ISSUE THREAD

**Issue by softsimple** [allegro/allegro-api#7950]
Mam problem z pobraniem propozycji dat odbioru paczek przez kuriera. Do tej pory nie było problemów przy takiej samej autoryzacji odpytując /parcel-management. Po przejściu na nowe zasoby /shipment-management cały czas leci błąd 403 Forbidden. Proszę o pilną pomoc.

Szczegóły poniżej.
Request:
{https://api.allegro.pl.allegrosandbox.pl/shipment-management/pickup-proposals}
{Method: POST, RequestUri: 'https://api.allegro.pl.allegrosandbox.pl/shipment-management/pickup-proposals', Version: 1.1, Content: System.Net.Http.StringContent, Headers:
{
  Authorization: Bearer  XXX
  Accept: application/vnd.allegro.public.v1+json
  Accept-Language: pl-PL
  Content-Type: application/vnd.allegro.public.v1+json; charset=utf-8
  Content-Length: 237
}}

{StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  trace-id: 1575ab79d0b167d4
  Date: Sat, 11 Nov 2023 12:16:51 GMT
  Content-Length: 140
  Content-Type: application/json; charset=utf-8
}}

{"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"Brak dostępu do danego zasobu."}]}

**Comment by softsimple** [comment]
Pomogła ponowna rejestracja aplikacji na środowisku sandbox wraz z zaznaczeniem uprawnień uprawnień (scopów)

**Comment by Lukasz-Zurek** [comment]
@softsimple Cieszę się, że udało się Tobie wyjaśnić ten problem.
