### ISSUE TITLE
problem związany z przechodzeniem produktów z allegro fulfillment przez integrator - zbędna spacja

### ISSUE THREAD

**Issue by KPSallegro** [allegro/allegro-api#7952]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X] inny / other

:beetle: **Opis / Description**

- Dzień dobry,
mamy problem techniczny związany z przechodzeniem niektórych produktów z allegro fulfillment przez nasz integrator, ponieważ przed numerem SKU wchodzi niepotrzebna spacja. Na przykładzie aukcji o numerze: 13673990614:
w tej aukcji przed numerem SKU (pole sygnatura) wcześniej była zbędna spacja, ale poprzez edycję tej aukcji ją usunęliśmy, problem nadal występował, więc zakończyliśmy i ponownie aktywowaliśmy tą aukcję. Niestety problem nadal występuje.  Czy są Państwo w stanie usunąć tę spację z pamięci serwisu? Wygląda to jakby ta spacja się nadpisała i może czyszczenie pamięci by pomogła, tak jak np. czyszczenie pamięci podręcznej w komputerze. Sprawa była zgłaszana przez formularz allegro (numer referencyjny: "37181632" [ ref:!00D240aE05.!500Ti0dVNK:ref ], ale zostałam przekierunkowana na forum GitHub.

**Comment by MaciejFrackowiak** [comment]
Niestety, ale nie mamy takiej możliwości. Zarządzanie konkretnymi ofertami, w tym edytowanie sygnatury spoczywa wyłącznie na sprzedającym.

**Comment by KPSallegro** [comment]
W takim razie co ma zrobić sprzedający, który poprawił taką ofertę i widzi, że zmiana zapisała się prawidłowo, ale dane zaciągają się tak jakby zmiany nie było?

**Comment by MaciejFrackowiak** [comment]
W API dane są zapisane bez spacji. To jak obsługuje już dane pole integrator to niestety kwestia poza nami. Tu konieczny byłby już kontakt z nim bezpośrednio.

**Comment by KPSallegro** [comment]
A czy byłby Pan w stanie sprawdzić jakie numery SKU wychodzą z allegro dla poniższych ofert:
13674164947, 13673990614, 13673985695 oraz 13674160233?
Z naszej strony podczas edycji oferty wyświetla się prawidłowy numer SKU (bez spacji przed SKU), a mimo to numery SKU wchodzą do integratora nieprawidłowo (z niepotrzebną spacją przed numerem SKU). Również BaseLinker widzi tą zbędną spację, co nie dzieje się w przypadku innych ofert, które prawidłowo wchodzą do integratora.

**Comment by MaciejFrackowiak** [comment]
Na chwilę obecną pola dla podanych ofert zapisane są bez spacji.

**Comment by KPSallegro** [comment]
W załączniku przesyłam odpowiedź, którą dostałam po skontaktowaniu się poprzez formularz allegro. Na czerwono zaznaczyłam informację sugerującą, że GitHub z technicznego punktu widzenia może zweryfikować co może być nie tak w momencie pobierania danych, że taki błąd się pojawia. Czy mogę poprosić o taką weryfikację? 
![odpowiedź allegro](https://github.com/allegro/allegro-api/assets/150655826/2c55f1c5-0436-4429-8391-8cee19c9248a)

**Comment by MaciejFrackowiak** [comment]
Otrzymała Pani w pełni prawidłową odpowiedź - obsługa sprzedającego nie ma dostępu do danych dostępnych za pośrednictwem API. Z naszej strony, czyli osób zdecydowanie bliżej technicznej strony raz jeszcze napiszę, że dla wskazanych ofert w sygnaturze nie widnieje spacja. Natomiast nie sposób mi wyjaśnić dlaczego w aplikacji zewnętrznej ta spacja występuje, ponieważ to oprogramowanie nie jest dostarczane, ani rozpowszechniane przez Allegro - to stricte pytanie do integratora, z którego usług Pani korzysta.
