### ISSUE TITLE
Nr listu przewozowego przesyłki zwrotnej

### ISSUE THREAD

**Issue by pzareba86** [allegro/allegro-api#7953]
Witam, utworzyłam jako klient zwrot i na koncie sprzedawcy w zakłądce zwroty mam status zwrotu ze jest w przygotownaiu, czy moge proisć o to by zostałdodany nr listu wrotego i status zwrotu był zmieniony na doreczony?

![image](https://github.com/allegro/allegro-api/assets/98810516/12c106fc-aafa-4453-9cff-38ecb0966adc)
Potrzebuje widok z nr listu:
![image](https://github.com/allegro/allegro-api/assets/98810516/e75c79f4-98b1-4271-9000-9c4c23f7e466)

**Comment by MaciejFrackowiak** [comment]
W tej sprawie proszę skontaktuj się z [obsługą serwisu](https://allegro.pl/pomoc/kontakt), ponieważ ta kwestia nie dotyka bezpośrednio działania API Allegro.

**Comment by pzareba86** [comment]
Witam,
Jak z obsługa serwisu, jak obsługa allegro każe mi pisać do Państwa, potrzebuje przetestować dodawanie nr listu na sandboxie, dodane mam zamówienie, jest założony zwrot a numeru listu nie ma, proszę o przekierowanie wiadomości do odpowiedniego zatem działu bo czekałam już 3 tygodnie z pierwszym zgłoszeniem, które tez nie wiadomo do kogo trafiło.

pzdr

***@***.***
Patrycja Zaręba
Junior Operations Manager

#WeMakeATeam

email: ***@***.******@***.***>
fax: +48 12 3120 239
mobile: +48724750784
OTCF S.A.
75-412 Koszalin, ul. Monte Cassino 6, Poland

***@***.***
***@***.***
Sponsor of 8 Olympic Committees: Poland, Croatia, Lithuania, Latvia, Portugal, Greece, Slovakia and Serbia for the Olympic Winter Games Beijing 2022
Presenting Sponsor of the Four Hills Tournament 2018-2020, Global Partner of the Wings for Life World Run 2020, Main Sponsor of FIS Alpine Ski World Championships Courchevel-Meribel 2023
________________________________
OTCF S.A. z siedzibą w Krakowie przy ul. Saskiej 25C, 30-720 Kraków, wpisana do rejestru przedsiębiorców Krajowego Rejestru Sądowego prowadzonego przez Sąd Rejonowy dla Krakowa – Śródmieścia w Krakowie, XI Wydział Gospodarczy Krajowego Rejestru  Sądowego pod nr KRS: 0000555276, kapitał zakładowy w wysokości: 7 384 500,00 zł opłacony w całości, NIP: 9451978451, REGON: 356630870, o numerze rejestrowym BDO: 000005025. Ta wiadomość i jej treść mogą zawierać informacje poufne lub zastrzeżone, przeznaczone tylko dla adresata wiadomości. Takie informacje są objęte zakazem ich ujawniania. Wszelkie rozprowadzanie, dystrybucja lub powielanie niniejszej wiadomości lub innego rodzaju wykorzystanie przez osobę lub podmiot nie będący jego adresatem, jest zabronione. Jeżeli otrzymałeś tę wiadomość omyłkowo, proszę bezzwłocznie zawiadomić nadawcę wysyłając odpowiedź na niniejszą wiadomość i usunąć ją z poczty. Dziękuję.
OTCF S.A. with its registered seat in Kraków, ul. Saska 25C, 30-720 Kraków, Poland, registered in the entrepreneurs’ register kept by the District Court for Kraków - Śródmieście District in Krakow, 11th Commercial Department of the National Court Register, entry no KRS 0000555276, its share capital of PLN 7 384 500.00 paid in full, Tax ID No.(NIP) : 9451978451, Business Statistical Number (Regon): 356630870, BDO: 000005025. This e-mail and its content might contain confidential or privileged information intended solely for the use of the addressee. Such information are protected from disclosure. You are hereby notified that any dissemination, distribution or copying or other use of this e-mail by person or entity other than the intended recipient is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by replying to the message and deleting it from your computer. Thank you.

From: MaciejFrackowiak ***@***.***>
Sent: Monday, November 13, 2023 9:51 AM
To: allegro/allegro-api ***@***.***>
Cc: Patrycja Zaręba ***@***.***>; Author ***@***.***>
Subject: [Marketing Mail] Re: [allegro/allegro-api] Nr listu przewozowego przesyłki zwrotnej (Issue #7953)

CAUTION: Ten email pochodzi spoza OTCF. Uważaj na zamieszczone załączniki oraz linki. Podejrzane wiadomości zgłoś na ***@***.******@***.***>

W tej sprawie proszę skontaktuj się z obsługą serwisu<https://allegro.pl/pomoc/kontakt>, ponieważ ta kwestia nie dotyka bezpośrednio działania API Allegro.

**Comment by MaciejFrackowiak** [comment]
Warto w takim razie konkretnie wyrażać swoje potrzeby, abyśmy nie musieli domyślać się, gdzie i dla jakiej operacji mamy cokolwiek zrobić. Proszę o podanie id sprzedającego z Sandbox oraz numer zwrotu - zobaczę, czy będziemy mogli wygenerować numer i status przesyłki zwrotnej.

**Comment by pzareba86** [comment]
Ok, to konto sprzedawcy sportcitytest,  a konto na kupującego – to podam login: ***@***.******@***.***> czy to wystarczy?


***@***.***
Patrycja Zaręba
Junior Operations Manager

#WeMakeATeam

email: ***@***.******@***.***>
fax: +48 12 3120 239
mobile: +48724750784
OTCF S.A.
75-412 Koszalin, ul. Monte Cassino 6, Poland

***@***.***
***@***.***
Sponsor of 8 Olympic Committees: Poland, Croatia, Lithuania, Latvia, Portugal, Greece, Slovakia and Serbia for the Olympic Winter Games Beijing 2022
Presenting Sponsor of the Four Hills Tournament 2018-2020, Global Partner of the Wings for Life World Run 2020, Main Sponsor of FIS Alpine Ski World Championships Courchevel-Meribel 2023
________________________________
OTCF S.A. z siedzibą w Krakowie przy ul. Saskiej 25C, 30-720 Kraków, wpisana do rejestru przedsiębiorców Krajowego Rejestru Sądowego prowadzonego przez Sąd Rejonowy dla Krakowa – Śródmieścia w Krakowie, XI Wydział Gospodarczy Krajowego Rejestru  Sądowego pod nr KRS: 0000555276, kapitał zakładowy w wysokości: 7 384 500,00 zł opłacony w całości, NIP: 9451978451, REGON: 356630870, o numerze rejestrowym BDO: 000005025. Ta wiadomość i jej treść mogą zawierać informacje poufne lub zastrzeżone, przeznaczone tylko dla adresata wiadomości. Takie informacje są objęte zakazem ich ujawniania. Wszelkie rozprowadzanie, dystrybucja lub powielanie niniejszej wiadomości lub innego rodzaju wykorzystanie przez osobę lub podmiot nie będący jego adresatem, jest zabronione. Jeżeli otrzymałeś tę wiadomość omyłkowo, proszę bezzwłocznie zawiadomić nadawcę wysyłając odpowiedź na niniejszą wiadomość i usunąć ją z poczty. Dziękuję.
OTCF S.A. with its registered seat in Kraków, ul. Saska 25C, 30-720 Kraków, Poland, registered in the entrepreneurs’ register kept by the District Court for Kraków - Śródmieście District in Krakow, 11th Commercial Department of the National Court Register, entry no KRS 0000555276, its share capital of PLN 7 384 500.00 paid in full, Tax ID No.(NIP) : 9451978451, Business Statistical Number (Regon): 356630870, BDO: 000005025. This e-mail and its content might contain confidential or privileged information intended solely for the use of the addressee. Such information are protected from disclosure. You are hereby notified that any dissemination, distribution or copying or other use of this e-mail by person or entity other than the intended recipient is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by replying to the message and deleting it from your computer. Thank you.

From: MaciejFrackowiak ***@***.***>
Sent: Monday, November 13, 2023 9:58 AM
To: allegro/allegro-api ***@***.***>
Cc: Patrycja Zaręba ***@***.***>; Author ***@***.***>
Subject: [Marketing Mail] Re: [allegro/allegro-api] Nr listu przewozowego przesyłki zwrotnej (Issue #7953)

CAUTION: Ten email pochodzi spoza OTCF. Uważaj na zamieszczone załączniki oraz linki. Podejrzane wiadomości zgłoś na ***@***.******@***.***>

Warto w takim razie konkretnie wyrażać swoje potrzeby, abyśmy nie musieli domyślać się, gdzie i dla jakiej operacji mamy cokolwiek zrobić. Proszę o podanie id sprzedającego z Sandbox oraz numer zwrotu - zobaczę, czy będziemy mogli wygenerować numer i status przesyłki zwrotnej.

**Comment by MaciejFrackowiak** [comment]
Proszę jeszcze o podanie identyfikatora danego zwrotu.

**Comment by pzareba86** [comment]
Mam 2 zwroty,
Jeden poniżej i tu widzę że nr zwrotu został już dodany:

***@***.***

Drugi nr:


***@***.***
Można tu dodac nr przesyłki inPost?

pozdrawiam
***@***.***
Patrycja Zaręba
Junior Operations Manager

#WeMakeATeam

email: ***@***.******@***.***>
fax: +48 12 3120 239
mobile: +48724750784
OTCF S.A.
75-412 Koszalin, ul. Monte Cassino 6, Poland

***@***.***
***@***.***
Sponsor of 8 Olympic Committees: Poland, Croatia, Lithuania, Latvia, Portugal, Greece, Slovakia and Serbia for the Olympic Winter Games Beijing 2022
Presenting Sponsor of the Four Hills Tournament 2018-2020, Global Partner of the Wings for Life World Run 2020, Main Sponsor of FIS Alpine Ski World Championships Courchevel-Meribel 2023
________________________________
OTCF S.A. z siedzibą w Krakowie przy ul. Saskiej 25C, 30-720 Kraków, wpisana do rejestru przedsiębiorców Krajowego Rejestru Sądowego prowadzonego przez Sąd Rejonowy dla Krakowa – Śródmieścia w Krakowie, XI Wydział Gospodarczy Krajowego Rejestru  Sądowego pod nr KRS: 0000555276, kapitał zakładowy w wysokości: 7 384 500,00 zł opłacony w całości, NIP: 9451978451, REGON: 356630870, o numerze rejestrowym BDO: 000005025. Ta wiadomość i jej treść mogą zawierać informacje poufne lub zastrzeżone, przeznaczone tylko dla adresata wiadomości. Takie informacje są objęte zakazem ich ujawniania. Wszelkie rozprowadzanie, dystrybucja lub powielanie niniejszej wiadomości lub innego rodzaju wykorzystanie przez osobę lub podmiot nie będący jego adresatem, jest zabronione. Jeżeli otrzymałeś tę wiadomość omyłkowo, proszę bezzwłocznie zawiadomić nadawcę wysyłając odpowiedź na niniejszą wiadomość i usunąć ją z poczty. Dziękuję.
OTCF S.A. with its registered seat in Kraków, ul. Saska 25C, 30-720 Kraków, Poland, registered in the entrepreneurs’ register kept by the District Court for Kraków - Śródmieście District in Krakow, 11th Commercial Department of the National Court Register, entry no KRS 0000555276, its share capital of PLN 7 384 500.00 paid in full, Tax ID No.(NIP) : 9451978451, Business Statistical Number (Regon): 356630870, BDO: 000005025. This e-mail and its content might contain confidential or privileged information intended solely for the use of the addressee. Such information are protected from disclosure. You are hereby notified that any dissemination, distribution or copying or other use of this e-mail by person or entity other than the intended recipient is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by replying to the message and deleting it from your computer. Thank you.

From: MaciejFrackowiak ***@***.***>
Sent: Monday, November 13, 2023 10:54 AM
To: allegro/allegro-api ***@***.***>
Cc: Patrycja Zaręba ***@***.***>; Author ***@***.***>
Subject: [Marketing Mail] Re: [allegro/allegro-api] Nr listu przewozowego przesyłki zwrotnej (Issue #7953)

CAUTION: Ten email pochodzi spoza OTCF. Uważaj na zamieszczone załączniki oraz linki. Podejrzane wiadomości zgłoś na ***@***.******@***.***>

Proszę jeszcze o podanie identyfikatora danego zwrotu.

**Comment by MaciejFrackowiak** [comment]
Pani informacje są maskowane (zapewne przez oprogramowanie, z którego Pani wysyła wiadomości) i w efekcie w poście widzę *** zamiast konkretnych informacji.

**Comment by pzareba86** [comment]
Dodaje zatem zdjecia:
![image](https://github.com/allegro/allegro-api/assets/98810516/50543dc1-17f4-4949-b6b0-f917f05cddec)
Tu chciałabym nr listu inpost czy mozna taki dodac?

A tu był drugi zwrot, ale widze że drugi nr się już dodał:

![image](https://github.com/allegro/allegro-api/assets/98810516/1ac0b082-9de6-4875-889c-b24f24963e17)

**Comment by MaciejFrackowiak** [comment]
Skonsultowałem Pani sprawę - i tak, mamy możliwość zasymulowania zmiany statusu przesyłki. Prosiłbym o podanie konkretnych identyfikatorów zwrotów (wzór XXXX/2023), dla których mamy wykonać zmiany.

**Comment by pzareba86** [comment]
Dzień dobry,
Dziękuję za pomoc, chyba możemy zamknąć zgłoszenie, ponieważ nr z dpd który się dodał wystarczył nam do testów.

pozdrawiam

***@***.***
Patrycja Zaręba
Junior Operations Manager

#WeMakeATeam

email: ***@***.******@***.***>
fax: +48 12 3120 239
mobile: +48724750784
OTCF S.A.
75-412 Koszalin, ul. Monte Cassino 6, Poland

***@***.***
***@***.***
Sponsor of 8 Olympic Committees: Poland, Croatia, Lithuania, Latvia, Portugal, Greece, Slovakia and Serbia for the Olympic Winter Games Beijing 2022
Presenting Sponsor of the Four Hills Tournament 2018-2020, Global Partner of the Wings for Life World Run 2020, Main Sponsor of FIS Alpine Ski World Championships Courchevel-Meribel 2023
________________________________
OTCF S.A. z siedzibą w Krakowie przy ul. Saskiej 25C, 30-720 Kraków, wpisana do rejestru przedsiębiorców Krajowego Rejestru Sądowego prowadzonego przez Sąd Rejonowy dla Krakowa – Śródmieścia w Krakowie, XI Wydział Gospodarczy Krajowego Rejestru  Sądowego pod nr KRS: 0000555276, kapitał zakładowy w wysokości: 7 384 500,00 zł opłacony w całości, NIP: 9451978451, REGON: 356630870, o numerze rejestrowym BDO: 000005025. Ta wiadomość i jej treść mogą zawierać informacje poufne lub zastrzeżone, przeznaczone tylko dla adresata wiadomości. Takie informacje są objęte zakazem ich ujawniania. Wszelkie rozprowadzanie, dystrybucja lub powielanie niniejszej wiadomości lub innego rodzaju wykorzystanie przez osobę lub podmiot nie będący jego adresatem, jest zabronione. Jeżeli otrzymałeś tę wiadomość omyłkowo, proszę bezzwłocznie zawiadomić nadawcę wysyłając odpowiedź na niniejszą wiadomość i usunąć ją z poczty. Dziękuję.
OTCF S.A. with its registered seat in Kraków, ul. Saska 25C, 30-720 Kraków, Poland, registered in the entrepreneurs’ register kept by the District Court for Kraków - Śródmieście District in Krakow, 11th Commercial Department of the National Court Register, entry no KRS 0000555276, its share capital of PLN 7 384 500.00 paid in full, Tax ID No.(NIP) : 9451978451, Business Statistical Number (Regon): 356630870, BDO: 000005025. This e-mail and its content might contain confidential or privileged information intended solely for the use of the addressee. Such information are protected from disclosure. You are hereby notified that any dissemination, distribution or copying or other use of this e-mail by person or entity other than the intended recipient is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by replying to the message and deleting it from your computer. Thank you.

From: MaciejFrackowiak ***@***.***>
Sent: Thursday, November 16, 2023 10:52 AM
To: allegro/allegro-api ***@***.***>
Cc: Patrycja Zaręba ***@***.***>; Author ***@***.***>
Subject: [Marketing Mail] Re: [allegro/allegro-api] Nr listu przewozowego przesyłki zwrotnej (Issue #7953)

CAUTION: Ten email pochodzi spoza OTCF. Uważaj na zamieszczone załączniki oraz linki. Podejrzane wiadomości zgłoś na ***@***.******@***.***>

Skonsultowałem Pani sprawę - i tak, mamy możliwość zasymulowania zmiany statusu przesyłki. Prosiłbym o podanie konkretnych identyfikatorów zwrotów (wzór XXXX/2023), dla których mamy wykonać zmiany.
