### ISSUE TITLE
Tworzenie produktu tymczasowego

### ISSUE THREAD

**Issue by KJtTGHAK** [allegro/allegro-api#7954]
Cześć, mam pytanie w jaki sposób mogę wystawić produkt tymczasowy ? Próbuję zrobić to za pomocą /sale/product-offers, oczywiście dla parametr "Stan" inny niż "Nowy" i nie przekazuję wszystkich parametrów identyfikujących produkt
Dostaję komunikat:

Nie można stworzyć produktu bez podania poprawnych wartości wszystkich parametrów wymaganych:

**Comment by Lukasz-Zurek** [comment]
Produkty tymczasowe tworzymy w wybranych kategoriach. Więcej informacji znajdziesz [tutaj](https://allegro.pl/dla-sprzedajacych/produkty-tymczasowe-na-czym-to-polega-Xxx6YKyG0Te).

Oczywiście jeżeli występuje problem dla kategorii z dostępnej listy - prześlij proszę trace-id.

**Comment by KJtTGHAK** [comment]
Dodaję w kategorii 257701 - która jest na liście
Stan inny niż nowy
trace-id: 4dac88b6c3d2ceda

**Comment by Lukasz-Zurek** [comment]
@KJtTGHAK Produkty tymczasowe tworzymy i dołączamy do oferty asynchronicznie. We wskazanym przypadku nie przekazałeś obowiązkowego (wymaganego do wystawienia oferty) parametru EAN (GTIN): 225693, dlatego otrzymujesz błąd. Na proces wystawiania ofert i tworzenia produktów tymczasowych wpływa kilka różnych czynników - opisaliśmy je w naszym [wcześniejszym newsie](https://developer.allegro.pl/news/w-wybranych-kategoriach-bedziemy-tworzyc-produkty-tymczasowe-nn9Y12dbqHM).

**Comment by KJtTGHAK** [comment]
@Lukasz-Zurek Tak wiem, że bez EAN - na tym polega produkt tymczasowy, - "Produkty tymczasowe możemy utworzyć dla przedmiotów ze stanem inny niż Nowy, które nie mają uzupełnionych wszystkich parametrów identyfikujących produkt lub mają wartości niejednoznaczne (inna/inny/pozostałe/brak)."

Poprzez formularz na stronie www dla towaru używanego w tej kategorii ten parametr jest opcjonalny i aukcję mogę dodać, przez API już nie.
![Uploading Zrzut ekranu 2023-11-13 155245.png…]()

**Comment by Lukasz-Zurek** [comment]
@KJtTGHAK Problem okazał się bardziej skomplikowany i wymaga dokładnej analizy całej logiki po naszej stronie. Pamiętamy o Twoim problemie. Przepraszam jednak, że weryfikacja trwa tak długo.

Oczywiście jak tylko otrzymam szczegółowe informacje - wrócę z nimi w tym wątku.

**Comment by KJtTGHAK** [comment]
Witam, problem znowu się pojawił. Dzisiaj po 8:30.
Nie można wystawić przez API produktu tymczasowego, ze stanem inny niż Nowy - bez kodu EAN. Zwracany jest błąd: 'Uzupełnij parametry obowiązkowe: EAN (GTIN).'

**Comment by AureliuszBrussy** [comment]
@KJtTGHAK kontynuujmy wątek w nowym zgłoszeniu: #10763. Tam udzielę odpowiedzi.
