### ISSUE TITLE
Nie mogę zmienić uprawnień aplikacji do sendboxa ...

### ISSUE THREAD

**Issue by keczerad** [allegro/allegro-api#7957]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [X ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Jak w temacie, nie mogę zmienić uprawnień do aplikacji w Sandbox ponieważ wyskakuje komunikat ze nazwa aplikacji musi zawierać od 3 do 50 znaków problem w tym, że jej nie ma a nie można jej zmienić.

**Comment by MartaNowaczyk** [comment]
Na jakim koncie jest ta aplikacja?

**Comment by keczerad** [comment]
Jest na moim koncie ? To nie jest żart a raczej wskazówka.

**Comment by MartaNowaczyk** [comment]
Rozumiem, ale potrzebuję nazwy konta na którym jest ta aplikacja. Możesz też dodać nową z potrzebnymi uprawnieniami.

**Comment by MartaNowaczyk** [comment]
Mamy konto z taką samą nazwą jak login na GH. Są tam dwie aplikacje bez nazwy. Mogę dodać jakieś nazwy, tylko napisz jakie i potwierdź czy to jest to konto.

**Comment by keczerad** [comment]
Tak to jest to konto. Dodakoto może by tak zrobić z aplikacji webowej taką możliwość, ponieważ to jest już moja druga prośba.

**Comment by MartaNowaczyk** [comment]
Dodałam nazwę. Tylko w starszych aplikacjach może wystąpić taka sytuacja. Podczas rejestracji sprawdzamy czy pole nazwa jest wypełnione, a nazwy nie można zmieniać, stąd nie planujemy takiej opcji.
