### ISSUE TITLE
Pobranie informacji o kampanii

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#7958]
Witam,
1. w panelu allegro: https://allegro.pl/moje-allegro/sprzedaz/kampanie?marketplaceId=allegro-pl mamy kampanie black week 2023 i black week Aleobniżka 2023
natomiast w zasobie /sale/badge-campaigns jest tylko kampania black week 2023

Dlaczego nie ma tej drugiej kampanii?

2. Mamy zgłoszone oferty w black week Aleobniżka 2023 jak przez REST API pobrać listę ofert zgłoszonych do tej kampanii?

**Comment by Lukasz-Zurek** [comment]
@manoos 

1. Potwierdzam, że z uwagi na decyzję biznesową - w naszym API nie udostępniamy tej drugiej kampanii - Alleobniżka 2023.
2. Nie pobierzesz obecnie tych ofert. 

Poruszoną powyżej sprawę wyjaśniam obecnie z zespołem odpowiedzialnym za kampanie, ponieważ w tej sytuacji utrudnia to zarządzanie oznaczeniami przypisanymi do ofert. Wkrótce wrócę z informacją.

**Comment by manoos** [comment]
Czy udało się coś wyjaśnić ?

**Comment by Lukasz-Zurek** [comment]
@manoos Dodaliśmy kampanię pod identyfikatorem: "BLACK_WEEK_ALLEOBNIZKA_2023_PL", którą zwracamy już, gdy skorzystasz z GET /sale/badge-campaigns.

Niezmiennie jednak nie będzie można zgłosić oferty do powyższej kampanii poprzez [POST /sale/badges](https://developer.allegro.pl/documentation/#operation/postBadges). Natomiast w przyszłości (choć nie mamy obecnie konkretnego terminu) planujemy udostępnić taką możliwość. O szczegółach poinformujemy w naszych [aktualnościach](https://developer.allegro.pl/news).
