### ISSUE TITLE
Problem z nowym produktem w produktyzacji

### ISSUE THREAD

**Issue by bacok** [allegro/allegro-api#7959]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Cześć.
Mam problem z dodaniem nowego produktu do katalogu produktów. Zapytanie `[GET] https://api.allegro.pl/sale/products?phrase=0045496453657&mode=GTIN` zwraca pustą odpowiedź.
Próba utworzenia nowego produktu kończy się komunikatem `Dodawanie produktów do kategorii nie jest możliwe`.
Trace-id - `950fbf0b46f9652d`
Prośba o weryfikację gdzie leży problem :)

Z góry dzięki :)

**Comment by Lukasz-Zurek** [comment]
W kategorii 256863 nie można tworzyć nowych produktów. W przypadku tego typu przedmiotów jak np. Nintendo Switch, w określonym zestawie, którego nie ma jeszcze w Allegro - może to być problematyczne i konieczne będzie ręczne utworzenie produktu. Bazując na danych, które chciałeś przekazać podczas próby utworzenia produktu - przekazałem temat do odpowiedniego zespołu.

**Comment by Lukasz-Zurek** [comment]
@bacok Wracam z informacją. Tak jak napisałem powyżej - nie utworzysz samodzielnie produktu w powyższej kategorii. Jeżeli natomiast chodzi o ręczne utworzenie produktu - potrzebne są wszystkie niezbędne informacje dotyczące m.in. obowiązkowych parametrów i zdjęć. W requeście, dla parametru 205994 przekazywałeś np. wartość "Lite" 205994_225554 - a bazując na EANie - jest to wersja zwykła/klasyczna. Najlepiej będzie jak skorzystasz z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=603fd405-2a43-4abf-83e7-243743286380) i przekażesz tam niezbędne dane do utworzenia produktu.
