### ISSUE TITLE
Problem z doGetSiteJournalDeals

### ISSUE THREAD

**Issue by modzel64** [allegro/allegro-api#796]
Mam problem z funkcją doGetSiteJournalDeals. Z tutoriala wynika, że powinna ona pobierać 100 najnowszych zdarzeń. Przy kolejnym wywołaniu metody z pierwszym i ostatnim zdarzeniem zwracane są zdarzenia z początku września 2018, czhociaż od tej pory zdarzeń były setki. Poniżej kod który wykorzystuję:
`$response = $api->getSiteJournalDeals(array(
            'sessionId' => $api->getSession()
        ));
        $id_s = [];
        foreach ($response->siteJournalDeals->item as $res) {
            $id = $res->dealEventId;
            if(!in_array($id, $id_s)){
                array_push($id_s, $id); 
            }
        }
        
        $responses = $api->getSiteJournalDeals(array(
            'sessionId' => $api->getSession(),
            'journalStart' => $id
        ));
        
        $dealTransactionIds = [];
        foreach ($responses->siteJournalDeals->item as $rest) {
            if (!in_array($rest->dealTransactionId, $dealTransactionIds) && $rest->dealTransactionId != 0){
                array_push($dealTransactionIds, $rest->dealTransactionId);//  $id = $res->dealEventId;
            }
        }
        
        $send_datas = $api->doGetPostBuyFormsDataForSellers(array(
            'sessionId' => $api->getSession(),
            'transactionsIdsArray' => $dealTransactionIds
        ));
        foreach ($send_datas->postBuyFormData->item as $it){
            echo 'Zamówienie z dnia: '.$it->postBuyFormShipmentAddress->postBuyFormCreatedDate .'<br />';
        }`

**Comment by PawelTaberski** [comment]
Czy nie określasz czasem błędnie startingPoint? I jesteś pewny że dla infoType przesyłasz wartość 0?
Bo nie widzę takich danych w Twoim kodzie. Sprawdź proszę opis metody jaki zamieściliśmy [tutaj](https://allegro.pl/webapi/documentation.php/show/id,65).

**Comment by modzel64** [comment]
Parametr infoType jest używany w metodzie doGetSiteJournal, według tutorialu mam wywołąć metodę doGetSiteJournalDeals 2 razy. Dodałem teraz 'journalStart' => 0, w pierwszym wywołaniu funkcji i mam takie same wyniki. Przy drugim wywołaniu funckcji jako punkt startowy ustawiłałem pierwszą i ostatnią wartość z tablicy, w obu przypadkach zwracane są zdarzenia z września.

**Comment by PawelTaberski** [comment]
Ciekawe, przetestowałem u siebie i daty jak i ilość danych wyglądają poprawnie. Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) swojego pełnego requesta i responsa w formacie XML sprawdzimy w czym jest problem. W zgłoszeniu dodaj, że informacje są potrzebne do ticketa numer 796 na GitHub-ie.

**Comment by modzel64** [comment]
Mogę podesłać odpowiedź w html? Nir robię nic na XML-ach. Wysłałem w formularzu plik ze zwracanymi wartościami i całą akcję której używam.

**Comment by modzel64** [comment]
Mam nadzieję, że to wystarczy...

**Comment by PawelTaberski** [comment]
Z zasady prowadzimy tutaj pomoc tylko dla języków w jakich ostatecznie dochodzi do komunikacji z naszymi serwerami, czyli w tym wypadku XML. Jednakże jeżeli masz problem z przesłaniem danych w takim formacie to dołącz do zgłoszenia, jeśli już nie podesłałeś id konta na jakim występuje problem. Jak tylko otrzymam dane jakie podesłałeś postaram się na tej podstawie zdiagnozować problem.

**Comment by modzel64** [comment]
W formularzu przesłałem wszystkie dane niezbędne do działania Api. Język php to dosyć popularny język programowania, może powinniście pomyleć nad rozszerzeniem możliwości webapi....

**Comment by mack3d** [comment]
Wyświetl sobie wartość $id
'journalStart' => $id
Być może wysyłasz pustą wartość lub zero

**Comment by PawelTaberski** [comment]
@modzel64 Sprawdziłem i metoda na przesłanym przez Ciebie koncie działa prawidłowo. Zgodnie z opisem metody: 
"Aby sterować pobieraniem kolejnych porcji danych (tak aby dotrzeć do danych najświeższych), należy w parametrze journalStart przekazywać wartość dealEventId ostatniego (setnego) elementu, zwracanego w ramach danego wywołania i robić to sukcesywnie, dopóki w wyniku wywołania nie otrzyma się porcji danych mniejszej niż 100 elementów (co będzie świadczyło, że otrzymane dane są danymi najświeższymi)."
I dane są posortowane rosnąco za każdym razem, czyli od najstarszej do najnowszej. Aby dotrzeć do najnowszych musisz sukcesywnie wywoływać, aż dojdziesz do mniej niż 100 w wyniku.
