### ISSUE TITLE
Nie można stworzyć etykiety Allegro One Box - Metoda dostawy jest niedostępna

### ISSUE THREAD

**Issue by zulus** [allegro/allegro-api#7960]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle:

Nie można stworzyć etykiety One Box. Request przechodzi przez `parcel-management/parcel-create-commands` ale później status jest: `Metoda dostawy jest niedostępna` Wiem że metoda jest teraz deprecated, ale w miało działać do 3 kwartału 2024 ;)

Request wysłany via formularz allegro

**Comment by Lukasz-Zurek** [comment]
@zulus Najprawdopodobniej wskazałeś inną usługę dostawy, odmienną od wybranej przez Klienta metody dostawy - stąd zaistniały błąd. Nie otrzymaliśmy jeszcze co prawda zgłoszenia z requestem, jednak zwróć proszę uwagę na informację dostępną w ramce, pod przykładowym response, na [tej stronie](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#pobieranie-listy-uslug-dostawy). Ewentualnie podaj proszę trace-id - sprawdzimy logi, by to potwierdzić.

**Comment by zulus** [comment]
Piszę bo jeszcze wczoraj działało na tych samych identyfikatorach.  Próba wybrania złego service id jest jasna, wtedy jest response że to zamówienie nie pasuje do tej metody dostawy

TraceID tworzenie etykiety 80823be44e522d0
TraceID pobranie statusu etykiety b0d83abd5891ebdb

**Comment by Lukasz-Zurek** [comment]
@zulus Rozumiem. Z tego co widzę, podczas tworzenia przesyłki wybierasz:

0aafb43c-e66a-46ec-9cc4-29bb39ebb483 - "Allegro One Box"

a powinieneś wybrać:

0b9bed2c-0bc1-4e1f-9694-29bb39ebb483 - "Allegro One Box, One Kurier".

ponieważ taką metodę dostawy wybrał Kupujący.

Jeżeli działało wcześniej na identyfikatorze: 0aafb43c-e66a-46ec-9cc4-29bb39ebb483 to pytanie jaką metodę dostawy wybrał Klient. Do dokładnej weryfikacji potrzebny będzie jednak trace-id, lub commandId.

**Comment by zulus** [comment]
Jak zaznaczam "Allegro One Box, One Kurier" to API krzyczy że mu się kod pocztowy nie zgadza dla kuriera. Mimo że chodzi o dostawę do One Box

**Comment by Lukasz-Zurek** [comment]
@zulus Prześlij proszę trace-id/commandId dla tego nowego żądania. Nie jestem pewien czy nadal chodzi o punkt AL044PZ1 i kod pocztowy: 62-030.
