### ISSUE TITLE
Tworzenie draftu oferty

### ISSUE THREAD

**Issue by michaldrozdzynski** [allegro/allegro-api#7963]
Czy jest możliwość stworzenia draftu oferty bez przypisywania konkretnego produktu przez API? Dla niektórych ofert wystawianych przez API nie mam danych na temat tego jaki dany produkt ma w allegro przypisany id lub ean. Potrzebował bym mieć możliwość wystawiania draftu oferty bez przypisanego produktu, co przyspieszyło by później proces ręcznego zatwierdzenia produktu. Ewentualnie, ponieważ dysponuje jedynie id kategorii mógłbym w ramach draftu przypisać dowolny produkt z danej kategorii. Ale również nie znalazłem endpointu który by pozwalał pobierać listę produktów o danej kategorii.

**Comment by MaciejFrackowiak** [comment]
Korzystając z [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts) masz możliwość wyszukiwania produktów z naszej bazy. Możesz skorzystać z parametru "category.id" by zawęzić wyniki do wybranej kategorii. W zdecydowanej większości kategorii wymagamy połączenia oferty z produktem, dlatego już tworząc ofertę możesz od razu ją połączyć z produktem bądź my to zrobimy automatycznie, gdy sprawdzimy, że danego produktu nie ma jeszcze w naszym katalogu. Zachęcam Ciebie do lektury [naszego poradnika](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem), gdzie szczegółowo opisujemy kolejne kroki wystawiania ofert z produktem.

**Comment by michaldrozdzynski** [comment]
Gdy wykorzystuje endpoint GET /sale/products otrzymuje taki błąd:
`stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ConstraintViolationException
                    [message] => An error has occurred
                    [details] => 
                    [path] => 
                    [userMessage] => Brak wymaganych parametrów.
                )

        )

)`

**Comment by MaciejFrackowiak** [comment]
Niezbędne jest, abyś podał jakikolwiek parametr wyszukiwania np. frazę, numer GTIN.

**Comment by michaldrozdzynski** [comment]
problem w tym, że nie mam numeru GTIN, ani żadnej frazy. Czy w takiej sytuacji, nie ma możliwości utworzenia drafta?
