### ISSUE TITLE
Brakujące słowo w tytule oferty

### ISSUE THREAD

**Issue by Devvnul** [allegro/allegro-api#7964]
Witam, mam taki problem. Zauważyłem, że po wystawieniu aukcji przez Allegro API z tytułu oferty zniknęło słowo "Abstrakcja".
Sprawdziłem model i zarówno w "Name" oferty jak i "Name" produktu wstawiam dokładnie tą samą wartość.

Link do aukcji na sandboxie: https://allegro.pl.allegrosandbox.pl/oferta/obraz-na-plotnie-jakas-aukcja-1-abstrakcja-pionowy-50x70-7732964085 

Jaka może być przyczyna?

PS. Zauważyłem również, że przy innej aukcji dodaje się jakby stary tytuł:

https://allegro.pl.allegrosandbox.pl/oferta/obraz-na-plotnie-jakas-aukcja-2-motyw-religijny-kwadrat-50x50-7732965240

**Comment by MaciejFrackowiak** [comment]
Na podstawie przekazanych przez Ciebie danych w requeście rozpoznaliśmy istniejący już w naszym katalogu produkt i dlatego do oferty przypięty został ten produkt. W przypadku obrazu istniejący produkt ma id=ccc4a9c0-f8ee-4d9a-b299-98ff0d7993d1. W przypadku drugiej oferty Twoje dane są duplikatem produktu o id=6889fa26-5d3f-434a-930c-7678469ef4c1.
