### ISSUE TITLE
Usunięcie zdjęć z opisu oferty w galerii

### ISSUE THREAD

**Issue by Devvnul** [allegro/allegro-api#7965]
Drugie pytanie ode mnie w osobnym wątku :-)
Czy jest możliwośc usunięcia / nie dodawania zdjęć, które wrzucam w opis oferty do zdjęć w górnej galerii?

**Comment by MaciejFrackowiak** [comment]
Nie, zdjęcia dodane do opisu oferty automatycznie pojawią się w galerii zdjęć.
