### ISSUE TITLE
Draft oferty nie aktywuje się

### ISSUE THREAD

**Issue by janpalko97** [allegro/allegro-api#7966]
Dzień dobry. Mamy problem ponieważ wiele produktów po wysłaniu requestu o aktywację draftu nie otrzymuje statusu 'ACTIVE', a utrzymuje się status 'INACTIVE'. 

Po przejściu na ten endpoint: https://api.allegro.pl/sale/offers/{offer_id} , nie pokazuje żadnego errora. 

Co możemy zrobić aby drafty takich produktów się aktywowały? 

Przykłady: (externalId / offer_id)
easyitem_2274189 / 14660965652
easyitem_2273778 / 14659477460
easyitem_2276332 / 14671328516

**Comment by MartaNowaczyk** [comment]
W podanych ofertach są przypisane id produktów, których nie ma już w naszym Katalogu. Trzeba uzupełnić te oferty o właściwe produkty, aby je aktywować.

**Comment by MartaNowaczyk** [comment]
Dodałam nazwę. Tylko w starszych aplikacjach może wystąpić taka sytuacja. Podczas rejestracji sprawdzamy czy pole nazwa jest wypełnione, a nazwy nie można zmieniać, stąd nie planujemy takiej opcji.

**Comment by janpalko97** [comment]
Tworzymy draft produktowi za pomocą tego endpointu: /sale/product-offers, allegro samo przypisuje id produktu z katalogu, następnie przy próbie aktywacji draftu dostajemy błąd:  ''Could not change offer publication status. Selected product does not exist.". 

Skoro produkt przestał istnieć to próbujemy utworzyć draft od nowa aby sparowało go z innym produktem z katalogu allegro. Jednak ponownie dostajemy ten sam błąd. Jest tak cały czas, nie ważne ile razy próbujemy utworzyć draft od nowa. 

Czy wie Pani jak rozwiązać ten błąd?

**Comment by MartaNowaczyk** [comment]
Podaj proszę konkretny trace-id wywołania z błędem, żebym mogła sprawdzić Twoje działanie na konkretnym przypadku.

**Comment by MartaNowaczyk** [comment]
Sprawdziłam na przykładzie oferty 14701320458. Tworzysz ofertę z produktem, produkt jest u nas zapisany w Katalogu, ale podczas późniejszej weryfikacji tego produktu sprawdzany jest EAN z [bazą EANów](https://www.gs1.org/services/verified-by-gs1). Jeśli kodu nie ma w GS1, EAN jest usuwany z produktu. Jeśli EAN jest obowiązkowy, to produkt również jest usuwany z naszego Katalogu i tutaj jest właśnie ten przypadek. Dla tej oferty podajesz kod EAN 41085981, który nie istnieje w tej bazie. Kwestie błędnych kodów EAN powinno się wyjaśnić z producentem.

**Comment by janpalko97** [comment]
Super dziękuję bardzo za wskazanie problemu.
