### ISSUE TITLE
allegro-cz refused "VQR010_SAURON_LEVEL_LOW"

### ISSUE THREAD

**Issue by sherstiukarkadiy** [allegro/allegro-api#7969]
all products that I posted additional on allegro-cz were refused with the reason: "VQR010_SAURON_LEVEL_LOW"
What is this reason means? There is no information about this refusal reason on your documentation and tutorials

**Comment by Lukasz-Zurek** [comment]
Please send us a trace-id, we will check it out closely. It refers to low seller quality ratings, but we should return a more specific error response.
