### ISSUE TITLE
Przesłanie pliku z fakturą / PUT

### ISSUE THREAD

**Issue by steinerpl** [allegro/allegro-api#7970]
Witam,
mam problem z wysłaniem faktury do utworzonego wcześniej obiektu faktury.

w PHP pobieram plik z fakturą metodą file_get_contents, następnie base64_encode i dołączam do zapytania curl:
$data = file_get_contents('paragon.pdf');
$data = base64_encode($data);
...
curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($data));

Otrzymuję ciągle response:
[code] => FILE-CONTENT-INVALID
[message] => Attachment for given order [xxx] and invoice [d1f1b276-ced8-4780-bb72-9f5bf582c943] must have a PDF content

Zaznaczam, że raz udało mi się plik poprawnie do faktury ID: 3d1f2c71-040a-4960-b846-acdf885dd96f
Niestety teraz robię na tym samym kodzie i otrzymuję informację zwrotną o niepoprawnym formacie.

**Comment by jezewskiBNetrox** [comment]
@steinerpl Czemu kodujesz zawartość pliku w Base64? Poradnik ani dokumentacja API nic o tym nie mówi.

**Comment by steinerpl** [comment]
@jezewskiBNetrox tak mi zadziałało za pierwszym razem.
Gdy nie koduję w Base64 otrzymuję response:
[code] => EMPTY-ATTACHMENT
[message] => Attachment for given order [xxx] and invoice [d1f1b276-ced8-4780-bb72-9f5bf582c943] must not be empty

**Comment by jezewskiBNetrox** [comment]
@steinerpl Tym bardziej dziwne, ale szczerze w PHP nie programuje, może to jakieś technologiczne różnice. Ten Base64 mnie zdziwił. https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#jak-dodac-fakture-do-zamowienia

**Comment by steinerpl** [comment]
Udało mi się to zrobić usuwając base64 oraz json_encode.
Jednak potwierdzenie wysłania faktury otrzymuję w curl_error:

[errors] => Array
        (
            [0] => stdClass Object
                (
[code] => FILE-UPLOADED
[message] => File for given invoice [9aa9bd6e-1360-45f4-8499-0df496139e7e] has been already uploaded
[details] => 
[path] => /order/checkout-forms/xxx/invoices/9aa9bd6e-1360-45f4-8499-0df496139e7e/file
[userMessage] => File for given invoice [9aa9bd6e-1360-45f4-8499-0df496139e7e] has been already uploaded
                )

        )

**Comment by Lukasz-Zurek** [comment]
@steinerpl Z tego co widzę - żądanie dodania faktury powiodło się 2023-11-15 13:40:51.787, w związku z czym ta próba (2023-11-15 13:41:06.741) odczytywana jest jako kolejna, stąd w odpowiedzi zwracamy odpowiedź 409.
