### ISSUE TITLE
GET /sale/badge-operations/{operationId}

### ISSUE THREAD

**Issue by randomWro** [allegro/allegro-api#7971]
Mam problem z powyższym zasobem na środowisku sandboxowym jak i produkcyjnym.
Na środowisku sandboxa, dla [operationId} 6631ec4d-d649-4502-8138-f16859ad434b
Poprawnie skonfigurowanego Content type oraz autoryzacji otrzymuję zawsze kod błędu BB14.

W zapytaniach dla obu środowisk dostaję następującą odpowiedź:

{
    "errors": [
        {
            "code": "BB14",
            "message": "Operation not found.",
            "details": null,
            "path": null,
            "userMessage": "Operation not found."
        }
    ]
}

Na czym może polegać problem z pobieraniem danych?

**Comment by randomWro** [comment]
trace-id: e6d870c1cee28a71

zapytanie: 
{
    "campaign": {
        "id": "SANDBOX_TEST_CAMPAIGN"
    },
    "offer": {
        "id": "7716816831"
    },
    "prices": {
        "bargain": {
            "amount": "2.80",
            "currency": "PLN"
        }
    }
}

odpowiedź:

{
    "id": "6631ec4d-d649-4502-8138-f16859ad434b",
    "createdAt": "2023-11-15T12:22:07.874Z",
    "updatedAt": "2023-11-15T12:22:07.874Z",
    "campaign": {
        "id": "SANDBOX_TEST_CAMPAIGN"
    },
    "offer": {
        "id": "7716816831"
    },
    "prices": {
        "bargain": {
            "amount": "2.80",
            "currency": "PLN"
        },
        "market": null
    },
    "purchaseConstraints": null,
    "process": {
        "status": "REQUESTED",
        "rejectionReasons": []
    }
}

**Comment by Lukasz-Zurek** [comment]
Za pomocą [GET /sale/badge-operations/{operationId}](https://developer.allegro.pl/documentation/#operation/badgeOperations_get_one) sprawdzisz status wykonania operacji zmiany ceny lub zakończenia oznaczenia. Czyli przekazujesz nieprawidłowy identyfikator. W Twoim przypadku aktualny status zgłoszenia oferty do kampanii, sprawdzisz za pomocą [GET /sale/badge-applications/{applicationId}](https://developer.allegro.pl/documentation/#operation/badgeApplications_get_one).
