### ISSUE TITLE
item_id  różne wyniki przez API 

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#7972]
Nie wiem dlaczego w odpowiedzi dostajemy "Oferta: 041b2586-80e8-11ee-a71e-2fd3ba4b3abe nie istnieje w płatności" skoro te ID to nie jest ID oferty tylko item_id. Id oferty w tym zamówieniu to 04267024-80e8-11ee-a71e-2fd3ba4b3abe.

2023-11-14 14:30:00.344763 - Request:
Array
(
[url] => https://api.allegro.pl/payments/refunds
[content_type] => application/json
[http_code] => 422
[header_size] => 178
[request_size] => 1822
[filetime] => -1
[ssl_verify_result] => 0
[redirect_count] => 0
[total_time] => 5.162606
[namelookup_time] => 0.000937
[connect_time] => 3.01747
[pretransfer_time] => 3.295615
[size_upload] => 255
[size_download] => 212
[speed_download] => 41
[speed_upload] => 49
[download_content_length] => 212
[upload_content_length] => 255
[starttransfer_time] => 0
[redirect_time] => 0
[redirect_url] =>
[primary_ip] => 5.134.213.11
[certinfo] => Array
(
) {
"payment": {
"id": "048afebf-80e8-11ee-aaed-db29dadee78c"
},
"reason": "REFUND",
"lineItems": [{
"id": "041b2586-80e8-11ee-a71e-2fd3ba4b3abe",
"type": "QUANTITY",
"quantity": 1,
"value": null
}
],
"delivery": null,
"overpaid": null,
"surcharges": null,
"additionalServices": null
}

[primary_port] => 443
    [local_ip] => 192.168.0.62
    [local_port] => 40756
    [http_version] => 2
    [protocol] => 2
    [ssl_verifyresult] => 0
    [scheme] => HTTPS
    [appconnect_time_us] => 3295554
    [connect_time_us] => 3017470
    [namelookup_time_us] => 937
    [pretransfer_time_us] => 3295615
    [redirect_time_us] => 0
    [starttransfer_time_us] => 0
    [total_time_us] => 5162606
)
2023-11-14 14:30:00.344791 - Request data:
2023-11-14 14:30:00.344815 Response header:
HTTP/1.1 422 Unprocessable Entity
trace-id: 4e09668bfe839d87
date: Tue, 14 Nov 2023 13:29:58 GMT
content-type: application/json
content-length: 212
x-frame-options: DENY

2023-11-14 14:30:00.344838 Response body: {
"errors": [{
"code": "VALIDATION_ERROR",
"message": "Oferta: 041b2586-80e8-11ee-a71e-2fd3ba4b3abe nie istnieje w płatności",
"userMessage": "Oferta: 041b2586-80e8-11ee-a71e-2fd3ba4b3abe nie istnieje w płatności"
}
]
}

**Comment by Lukasz-Zurek** [comment]
Dla płatności w **payment.id** "048afebf-80e8-11ee-aaed-db29dadee78c" przekazujesz nieprawidłowe **lineItems.id**: 041b2586-80e8-11ee-a71e-2fd3ba4b3abe".

Płatność "048afebf-80e8-11ee-aaed-db29dadee78c" dokonywana była w ramach zamówienia nr "04267022-80e8-11ee-a71e-2fd3ba4b3abe", gdzie **lineItems.id**: "041b2582-80e8-11ee-a71e-2fd3ba4b3abe" (uzyskasz je za pomocą GET /order/checkout-forms/04267022-80e8-11ee-a71e-2fd3ba4b3abe) i taką wartość pownieneś przekazać w celu wykonania zwrotu płatności.

**Comment by centrumelektroniki** [comment]
dziękuję
