### ISSUE TITLE
Taki bład : ProductProposalsAccessForbiddenException

### ISSUE THREAD

**Issue by keczerad** [allegro/allegro-api#7974]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Mam taki błąd {"errors":[{"code":"ProductProposalsAccessForbiddenException","message":"Access denied.","details":null,"path":"productSet[0].product","userMessage":"Brak dostępu."}]}

Konta na sandbox keczerad-emo

**Comment by MaciejFrackowiak** [comment]
Problem powoduje brak weryfikacji tego konta jako firmowe - przeklikałeś tylko zmianę z konta zwykłego, ale nie dokonałeś przelewu weryfikacyjnego i nie przesłałeś dokumentów firmowych. Możesz dokończyć proces konwersji w tzw. krokowcu w zakładce [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by keczerad** [comment]
Ja tego nie widzę, za dużo tego naćpane w tych krokach, promujecie czechy i nic przez to nie widać.

**Comment by MaciejFrackowiak** [comment]
Spójrz proszę tu - https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto - w pierwszym bloku powinien być widoczny krokowiec z konfiguracją sprzedaży.

**Comment by keczerad** [comment]
Nie możesz tego po prostu aktywować ? Na miłość boską wersja sandox nie jest zbieżna z wersję produkcyjną oj jakiegoś perdiliona lat, nadal jest tak samo czyli inaczej, nie maczegoś takiego jak krokowiec którego faktycznie kojarze z wersji produkcyjnej. Teraz na sandoxie jest milion ofert CZ i tyle samo nieaktywnych linków po którymi nic nie ma oprócz komunikatu ze zabłądziłem :).

**Comment by MaciejFrackowiak** [comment]
Nie, nie mam takiej możliwości póki nie wykonasz wspomnianych operacji. Dodam więcej - inni użytkownicy Sandbox'a radzą sobie z tym procesem, zatem wierzę, że też dasz radę i będę mógł aktywować to konto.

**Comment by keczerad** [comment]
Wiesz jak jest przepracowanie wekend a ty klikasz w 10 link a on ci mówi ze nie ma linku i cie nie powiem co chyta.

**Comment by keczerad** [comment]
Krokowiec jest owszem aktywny, ale nie zawsze ?! Czyli nie przewidzieliscie wszystkich scenariuszy, czyli normalka.
Po założeniu konta inneg jest już krokowiec, aele czeka się na aktywację konta (przelew mail z dowodem) ? Czy to drługo trwa ?

**Comment by MaciejFrackowiak** [comment]
Konto "keczerad-emo2" jest już zweryfikowane i aktywne. W przypadku "keczerad-emo" niezbędny jest przelew i dokumenty, abym mógł je aktywować.
