### ISSUE TITLE
AllegroOneBox problem z zamowieniem kuriera

### ISSUE THREAD

**Issue by Pawelpwg** [allegro/allegro-api#7975]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [x ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

![image](https://github.com/allegro/allegro-api/assets/86594547/267766bc-ae0c-45af-b051-e6909f9d58b1)

tak Wyglada zamowienie kuriera przez strone dla allegroOneBox, paczka nadana przez API. Dodam ze ta sytucja dzieje sie tylko ale kuriera UPS, pozostali kurierzy dzialaja prawidlowo

request 
https://api.{environment}/shipment-management/shipments/create-commands

{
  "commandId": "fee9f2c2-f726-4832-a56f-2dfe8fbbe1a9",
  "input": {
    "deliveryMethodId": "0aafb43c-e66a-46ec-9cc4-29bb39ebb483",
    "receiver": {
      "street": "",
      "streetNumber": "19",
      "postalCode": "50-505",
      "city": "xx",
      "countryCode": "PL",
      "country": null,
      "email": "26castqyxi+245324712@allegromail.pl",
      "name": "Serhii ",
      "company": "",
      "phone": "+4850",
      "point": "AL166DW1"
    },
    "sender": {
      "street": "",
      "streetNumber": "3",
      "postalCode": "25-382",
      "city": "Kielce",
      "countryCode": "PL",
      "country": null,
      "email": "b.com",
      "name": "Jerzy ",
      "company": "PPUH ",
      "phone": "790  "
    },
    "packages": [
      {
        "length": {
          "value": 30,
          "unit": "CENTIMETER"
        },
        "width": {
          "value": 40,
          "unit": "CENTIMETER"
        },
        "height": {
          "value": 30,
          "unit": "CENTIMETER"
        },
        "weight": {
          "value": "9.00",
          "unit": "KILOGRAMS"
        },
        "type": "PACKAGE",
        "waybill": null
      }
    ],
    "type": "PACKAGE",
    "labelFormat": "PDF",
    "description": "Client:114299408",
    "insurance": null
  }
}

waybill: A0072YYJ5

**Comment by MaciejFrackowiak** [comment]
Zamieszczony przez Ciebie zrzut ekranu sugeruje, że przekazujesz niewłaściwy identyfikator przesyłki, przez co system nie potrafi jej rozpoznać.

**Comment by Pawelpwg** [comment]
ale jakie złe id? screen to krok drugi przy zamawianiu kuriera w pierwszym kroku wybrałem paczkę nadana przez api, wiec wasz system ja widzi, etykiety przez api i stronę drukują się prawidłowo.

taka sytuacja nie dzieje się gdy paczkę od początku nada się przez stronę, wiec albo jest problem z requestem albo z waszym systemem przetwarzania paczek, wiec proszę o jakaś radę

**Comment by Pawelpwg** [comment]
dodam ze taka sytuacja nie ma miejsc w przypadku kuriera dhl, tam na stronie bez problemu da się zamówić kuriera, wiec wątpię aby to było złe  id po mojej stronie, chyba ze allegro onebox ma jakieś dodatkowe pola  i czegoś mi brakuje, ale w żadnym momencie nie leci błąd lub komunikat o tym

**Comment by MaciejFrackowiak** [comment]
Rozumiem, jednak ciężko mi się odnieść do działania strony WWW - na GitHub wspieramy w zakresie wykorzystania zasobów API i ewentualnych problemów z nimi. Tu jak sam opisujesz jest to problem z WWW - proszę zatem zrób zrzuty ekranu kolejno wykonywanych kroków i prześlij je do [obsługi serwisu](https://allegro.pl/pomoc/kontakt), która powinna ten problem przekazać do weryfikacji.

**Comment by Pawelpwg** [comment]
ale api to nie jest to sam interfejs, ale caly system ktory stoi za tym i w jaki sposob procesuje informacje. zreszta tutaj elementem od ktorego zaczyna sie problem jest wlasnie API a nie interfejs www

dodam jeszcze ze poprzednie metody do nadawania paczek nie mialy tego problemu, dopiero po zmianie na shipment-managment problem sie pokazal, co tez by sugerowalo jakis blad w nowej implementacji

PS
ja rozumiem jak wyglada praca w korporacji, i spychologia, sam to przerabialem, ale nie stosujmy zly wzorcow a sprobujmy rozwiazac problem co pochlonie zdecydowanie mniej energii niz przerzucanie sie miedzy grupami

**Comment by MaciejFrackowiak** [comment]
Mimo szczerych chęci nie mamy możliwości zweryfikowania tego co się dzieje od strony frontu - i dlatego właściwą komórką jest obsługa Allegro, która może ten przypadek zgłosić do weryfikacji. Jak wspomniałem - my odpowiadamy stricte za API i jeżeli problem dotyczyłby zamówienia podjazdu realizowanego przez request API to jak najbardziej jesteśmy właściwym źródłem kontaktu.
