### ISSUE TITLE
Problem z Allegro International pobranie

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#7977]
Witam, dla zamówień:
702b80c0-83e6-11ee-a8af-1705852b21e5, 6ed31780-83f8-11ee-a862-45d7ac9b4379
Próbuję przez API utworzyć przesyłkę za pomocą zasobu /parcel-management/parcel-create-commands/{commandId}
Metoda dostawy: Allegro International Odbiór w Punkcie Czechy pobranie, Allegro International Kurier Czechy pobranie
i dostaję zwrotnie:

  +"id": "c771b120-4c45-48e4-9b78-a2231944c370"
  +"parcelId": null
  +"status": "ERROR"
  +"errors": array:1 [
    0 => {#4420
      +"code": "BAD_REQUEST"
      +"message": "External carrier error"
      +"details": null
      +"path": ""
      +"userMessage": "Błąd API przewoźnika"
    }
  ]
  
Proszę o informację w czym może być problem.

Dodam, że dla metod dostawy płatnych z góry wszystko działa poprawnie.

**Comment by manoos** [comment]
Udało mi się rozwiązać problem, 

Kwotę pobrania przekazywałem w walucie CZK, a deklarowana wartość paczki była w PLN

**Comment by MartaNowaczyk** [comment]
Kwota ubezpieczenia i COD powinny być w walucie CZK, a masz w PLN, stąd błąd od przewoźnika.
