### ISSUE TITLE
Aktywacja konta API allegrosandbox

### ISSUE THREAD

**Issue by adamGitTest** [allegro/allegro-api#7979]
Proszę o aktywację konta w sposób który umożliwi dostęp do API z użyciem autoryzacji device flow w zakresie wystawiania ofert allegro w środowisku sandbox. 
Aktualnie w Danych konta mam sprzedaż Nieaktywna. 
 Client:106740790
Konto ustawione jako firmowe niedawno z nadanym loginem 
LOGIN
Login_106740790
Przelew wysłany symulatorem płatności

**Comment by Lukasz-Zurek** [comment]
@adamGitTest Aktywowałem i zweryfikowałem Twoje konto.
