### ISSUE TITLE
odczyt zamówienia nie zwraca informacji o zestawie

### ISSUE THREAD

**Issue by Zbigniew-L** [allegro/allegro-api#7981]
witam, mamy problem z odczytem informacji o zestawie - mamy przykładowe zamówienie ze sprzedanym zestawem produktów (obecnie już wysłane) - 278eb080-7f09-11ee-8de7-7d532e84cdf7

na liście zamówień widzimy, że zamówienie zawiera 2 produkty (główny + dodatkowy) - jednak odczyt API zwraca jedynie 1 linię (produkt główny), nie ma żadnej informacji (w api) o tym, ze sprzedaliśmy zestaw

oferta nr 13989903790 miała (w przeszłości!) produkt dodatkowy - obecnie oferta nie ma dodatkowego produktu

pobierając obecnie szczegóły oferty ( sale/product-offers/13989903790) nie otrzymujemy informacji o tym, że oferta ma dodatkowy produkt - co jest zrozumiałe, bo obecnie go nie ma (ale w przeszłości miała dodatkowy produkt)

zatem tak długo jak oferta ma dodatkowy produkt możemy odczytać tą informację jednak kiedy np. zdecydujemy zmienić ofertę (np. utworzyć komplet ale z innym towarem) - to nie mamy żadnej możliwości odczytania przez API jaki zestaw został sprzedany w momencie dokonania transakcji, prosimy o informację czy coś robimy nie tak lub w jaki sposób możemy pobrać dane zamówienia aby uzyskać informację o zestawie?

**Comment by MaciejFrackowiak** [comment]
Niestety, ale obecnie nie zwracamy w API informacji o zestawie produktów, który był przedmiotem zakupu. W szczegółach zamówienia znajdziesz wyłącznie informacje o głównej ofercie. W tym momencie najlepszym rozwiązaniem wydaje się tworzenie zestawów oddzielnie, per osobna oferta, aby ich składowe produktów były jednoznaczne do odczytania.
