### ISSUE TITLE
Dodanie dyskusji bez zamówienia

### ISSUE THREAD

**Issue by lukiqs** [allegro/allegro-api#7983]
Witam czy możemy zasymulować dyskusje bez zamówienia na koncie sandboxa: _thulium_ ?

**Comment by MaciejFrackowiak** [comment]
Nie, niestety, aby utworzyć dyskusję niezbędne jest zamówienie.

**Comment by lukiqs** [comment]
A w jakim przypadku może nie być formularza zamówienia (checkoutForm jest null) dla dyskusji ?

**Comment by lukiqs** [comment]
Pytam ponieważ zdażyła się taka sytuacjia u naszego klienta na produkcji

**Comment by MaciejFrackowiak** [comment]
Proszę podaj przykład, wówczas będę mógł to zweryfikować.

**Comment by lukiqs** [comment]
Id dyskusji: _df77300e-2100-4601-9756-90343858c1ac_ oraz checkout form id _3b7d51e0-56ed-11ed-88cf-d7822ab3f122_

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem wskazaną przez Ciebie dyskusję i widzę:
```
"checkoutForm": {
        "id": "3b7d51e0-56ed-11ed-88cf-d7822ab3f122",
        "createdAt": "2022-10-28T18:20:42.000Z"
    }
```

**Comment by lukiqs** [comment]
Dostaliśmy taką odpowiedź od api: 
`{"code":"CheckoutFormNotFoundException","message":"Checkout form 3b7d51e0-56ed-11ed-88cf-d7822ab3f122 not found","details":null,"path":"/order/checkout-forms/3b7d51e0-56ed-11ed-88cf-d7822ab3f122","userMessage":"Checkout form 3b7d51e0-56ed-11ed-88cf-d7822ab3f122 not found"}`

**Comment by MaciejFrackowiak** [comment]
Szczegóły zamówień przechowujemy przez 180 dni od dnia transakcji, zatem otrzymujesz poprawną odpowiedź.

**Comment by lukiqs** [comment]
Rozumiem a czy może być taka sytuacja, że Allegro otwiera ponownie dyskusje (w której szczegóły zamówień są starsze niż 180 dni) ? jeśli tak to czy udało by się na sandboxie otworzyć dyskusje **9e09082a-7534-4cfa-bb70-cb3163a0d86f** z 8 maja 2023 12:19

**Comment by MaciejFrackowiak** [comment]
Tak, dyskusja może zostać ponownie otwarta przez pracownika Allegro. Niestety, na Sandbox nie mamy takiej możliwości.
