### ISSUE TITLE
W żądaniu może być tylko jedna paczka

### ISSUE THREAD

**Issue by Adrian-baw** [allegro/allegro-api#7984]
Dzień dobry. Próbuję nadać 2 paczki na allegro ONE BOX. Wszystkie spedycje działają, ale z tą jedną występują problemy. Dostaję komunikat zwrotny:

 {"status":null,"response":{"result":{"commandId":"1473720e-5708-4879-a740-fb3d8865405e","status":"ERROR","errors":[{"code":"SHIPMENT_VALIDATION_ERROR","message":"A request can contain only one parcel","details":"Shipment request has validation errors","path":"packages","userMessage":"W żądaniu może być tylko jedna paczka"}],"shipmentId":null}}}

Co jest nie tak? W dokumentacji nie widzę informacji żeby był limit do 1 paczki dla allegro one box. Jeżeli takowy występuje to jak nadawać w takim wypadku więcej niż 1 paczkę?

Trace ID: 4173f4a09aaa0169

Pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
Usługa wielopaczki wspierana jest tylko przez DPD. W przypadku Allegro One Box po prostu wyślij osobne requesty dla każdej z paczek.

**Comment by Adrian-baw** [comment]
Rozumiem, czy jest gdzieś informacja, które spedycje trzeba nadawać tylko z 1 paczką jako oddzielne requesty, a które z wieloma paczkami? Czy jest jakaś sekcja w dokumentacji na ten temat którą przeoczyłem?

Pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
Niestety nie - z uwagi na ilość dostępnych przewoźników utrzymanie tych informacji w dokumentacji byłoby trudne do realizacji.

**Comment by Adrian-baw** [comment]
Rozumiem. To znaczy że powinienem zrobić warunek że tylko w spedycji DPD nadawać wiele paczek w 1 requeście, a inne spedycje zawsze po 1 paczce.

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak.

**Comment by Adrian-baw** [comment]
Rozumiem. Jeszcze jedno pytanie. Co w przypadku nadania np. przez pocztępolską 2 paczek z pobraniem? Jak zrobić żeby była 1 kwota pobrania do wszystkich paczek?

Pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
Kwotę pobrania przypisujesz do jednej paczki lub dzielisz ją na przedmioty wchodzące w skład każdej z przesyłek.
