### ISSUE TITLE
AllegroSandbox i błąd wystawienia oferty na rynku czeskim.

### ISSUE THREAD

**Issue by pawelcudowski** [allegro/allegro-api#7986]
Nie mogę udostępnić oferty na rynku czeskim - otrzymuję komunikat:
Nie można wystawiać ofert B2B, C2C i charytatywnych poza allegro.pl..

Przy dodawaniu cennika dostaw, wysyłka z Polski do Czech, mam jedynie opcję e-mail, inne są niewidoczne - nie wyświetlają się.

Mam ustawione konto firmowe.

Moje konto pawelcudowski@interia.pl

**Comment by MartaNowaczyk** [comment]
Z tego co widzę masz konto firmowe, ale nie jest zweryfikowane. Niestety konto było rejestrowane już dawno temu, a od tego czasu się dużo zmieniło. Przez ograniczenia techniczne nie mogę wykonać weryfikacji. Zarejestruj proszę [nowe konto firmowe](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto).

**Comment by pawelcudowski** [comment]
Założyłem konto do testów z danymi, prosiłbym o weryfikację i umożliwienie testowania. 

Nowe konto: Pawel_testZakup
allegro_api@interia.pl

**Comment by MartaNowaczyk** [comment]
Aktywowałam podane konto.
