### ISSUE TITLE
Numer IBAN dla przesyłek pobraniowych

### ISSUE THREAD

**Issue by inTestowy** [allegro/allegro-api#7987]
Czy mogę prosić na koncie:

inTest2_testowy

o ustawienie możliwość nadawania przesyłek z płatnością przy odbiorze ? Ewentualnie wskazanie w jaki sposób mogę na koncie wprowadzić numer konta IBAN ?

**Comment by Lukasz-Zurek** [comment]
Musisz najpierw skonfigurować [ustawienia wypłat](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty) i tam właśnie uzupełnić IBAN. W przypadku nowego zasobu [POST /shipment-management/shipments/create-commands](https://developer.allegro.pl/documentation/#operation/createNewShipment) numer konta IBAN wskazany podczas tworzenia przesyłki - musi być taki sam, jak w ustawieniach (j.w.). Dotyczy to tylko przesyłek na terenie PL, natomiast sam IBAN wymagany jeśli dla wybranej usługi dostawy wymagany numer IBAN (`"forceRequireIban": true`).

Więcej informacji znajdziesz [tutaj](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke).

Dodam, że zoptymalizowaliśmy to na wspomnianym powyżej zasobie. Natomiast w przypadku dotychczasowego zasobu [PUT /parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/createNewParcel) oznaczonego już jako **Deprecated** - kluczowy jest wybór odpowiedniej usługi dostawy, za pobraniem.

**Comment by inTestowy** [comment]
ok, rozumiem. 

Mam w takim razie jeszcze jedno pytanie.

Zamówienia posiada wybraną metodę płatności 'Allegro Kurier Pocztex pobranie'

Podczas tworzenia przesyłki z poziomu aplikacji Allegro , sugerowana metoda dostawy to : 'Allegro Kurier Pocztex pobranie (Pocztex)'

![image](https://github.com/allegro/allegro-api/assets/111511140/7f5e00d1-ca60-4117-8a61-8228505ca7c5)

Poprzez API dostępną metodą dostawy jest 'Allegro Kurier Pocztex pobranie (Pocztex)', jednak podczas tworzenia przesyłki otrzymujemy zwrotnie informację iż :

{"commandId":"ed5a847f-595f-4309-8c49-e3d6c2dec7e4","shipmentId":null,"status":"ERROR","errors":[{"code":"CREDENTIALS_ID_NOT_PROVIDED","details":"Seller didnt provide credentials for own delivery Method","message":"Seller didnt provide credentials for own delivery Method","path":"credentialsId","userMessage":"Wybrana metoda dostawy nie obsługuje tego zamówienia"}]}


obiekt wysłany podczas tworzenia przesyłki:

{"commandId":"ed5a847f-595f-4309-8c49-e3d6c2dec7e4","input":{"deliveryMethodId":"193d950b-0082-408f-9192-6081e5e7e7e2","credentialsId":null,"sender":{"name":"Zenonowa Żabka","company":"intest.testowy 2","street":"testowa 72/","streetNumber":"72","postalCode":"01-001","city":"Warszawa","countryCode":"PL","email":"intest2.testowy@gmail.com","phone":"521523522","point":null},"receiver":{"name":"Jan Kowalski","company":"Adres PL","street":"al. Jana Nowaka- Jeziorańskiego RAZ DDDDDDDDDDDDDD","streetNumber":"12/2","postalCode":"95-070","city":"Aleksandrów Łódzki","countryCode":"PL","email":"3j2tv15cki+6c1d32812@user.allegrogroup.pl","phone":"501501501","point":null},"pickup":{"name":"Zenonowa Żabka","company":"intest.testowy 2","street":"testowa","streetNumber":"72","postalCode":"01-001","city":"Warszawa","countryCode":"PL","email":"intest2.testowy@gmail.com","phone":"521523522","point":null},"referenceNumber":"ZK 704 JK MAG 11 2023","description":"kurier DHL","packages":[{"type":"PACKAGE","length":{"value":10,"unit":"CENTIMETER"},"width":{"value":20,"unit":"CENTIMETER"},"height":{"value":30,"unit":"CENTIMETER"},"weight":{"value":"0.25","unit":"KILOGRAMS"}}],"insurance":{"amount":"120.52","currency":"PLN"},"cashOnDelivery":{"amount":"120.52","currency":"PLN","ownerName":"Zenonowa Żabka","iban":"22 1600 1358 4759 6093 6838 9314"},"labelFormat":"PDF","additionalServices":[]}}

czy mogę prosić o wyjaśnienie tej sytuacji?

**Comment by Lukasz-Zurek** [comment]
Wskazana metoda dostawy funkcjonuje na zasadach [umowy własnej](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/wysylam-z-allegro-narzedzie-do-nadawania-przesylek-bezposrednio-z-konta-E7doGw8VgI1#). W żądaniu nie podałeś jednak identyfikatora umowy własnej w polu "credentialsId". Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke).

**Comment by Lukasz-Zurek** [comment]
@inTestowy Weryfikujemy ten przypadek. Wkrótce wrócę do Ciebie z informacją.

**Comment by Lukasz-Zurek** [comment]
@inTestowy Mieliśmy problemy z Allegro One na środowisku testowym. Udało się już jednak wyeliminować te problemy i sytuacja nie powinna się powtarzać.

Przepraszamy za utrudnienia.
