### ISSUE TITLE
Brak informacji o autentykacji w pliku swaggera

### ISSUE THREAD

**Issue by Arkowsky** [allegro/allegro-api#799]
Pobrałem plik swaggera, zgodnie z issue #278 i ten plik jest w porządku ale brakuje tam informacji na temat autentykacji.
Chodzi o to, że wygenerowałem sobie kod z pliku swagger.yaml ale domyślnie nie ma w tym pliku wymagania autoryzacji.
Swagger jednak umożliwia takie rzeczy:
[](https://swagger.io/docs/specification/authentication/api-keys/)

Czy można liczyć na pomoc? Np. dodanie takich informacji do pliku swagger.yaml czy trzeba to samemu obsłużyć?

**Comment by PawelTaberski** [comment]
Kwestię weryfikacji i autoryzacji opisaliśmy w tym [poradniku](https://developer.allegro.pl/auth/).

**Comment by Arkowsky** [comment]
Rozumiem ale chodzi mi o plik swaggera bo z niego generuje klasy za pomocą https://swagger.io/tools/swagger-codegen/.
Czy jest możliwość by dodać do pliku pola? Myśleliście może o tym?

**Comment by PawelTaberski** [comment]
@Arkowsky Dodaliśmy pole

**Comment by Arkowsky** [comment]
dzięki, wygląda na to, że działa :). Zamykam.
