### ISSUE TITLE
Internal server error przy próbie pobrania typu dostawy

### ISSUE THREAD

**Issue by tomi007** [allegro/allegro-api#7990]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Podczas wysyłania requesta GET / https://api.allegro.pl/shipment-management/delivery-services

dostaje zwrotkę:
`{
"errors": [
{
"code": "INTERNAL_SERVER_ERROR",
"message": "Internal server error.",
"details": null,
"path": null,
"userMessage": "Internal server error. Try again in a few minutes."
}
]
}`

Czy to globalny problem czy występuje tylko na moim koncie?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id przykładowego wywołania.

**Comment by tomi007** [comment]
Gdy podałem do autoryzacji TOKEN zamiast TOKEN-REFRESH to zadziałało :O 
Dlaczego nie mogę pobrać podając token-refresh ?

**Comment by MaciejFrackowiak** [comment]
Refresh token używany jest do przedłużania ważności autoryzacji użytkownika. Do dostępu do zasobów wykorzystujemy access token. Więcej o działaniu refresh tokena znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena).
