### ISSUE TITLE
Baselinker - Allegro API

### ISSUE THREAD

**Issue by VVCards** [allegro/allegro-api#7991]
Cześć,
Do integracji używam Baselinkera.
Wystąpił błąd podczas licytacji:
API Allegro umożliwia wyciąganie wyciągów wyłącznie z rachunków firmowych.
Kolega z Allegro potwierdził, że mam konto firmowe.
Czy możesz doradzić, jak postępować?
Serdeczne pozdrowienia,
RW
------
Hello,
I use Baselinker for integration.
An error occurred while bidding:
Allegro's API only allows statements on company accounts. 
A colleague from Allegro confirmed that I have a company account.
Can you please advise how to proceed?
Kind regards,
RW

**Comment by MaciejFrackowiak** [comment]
Jeżeli korzystasz z gotowego rozwiązania do obslugi integracji API Allegro, to w przypadku błędów proszę skontaktuj się bezpośrednio z obsługą tej aplikacji.
