### ISSUE TITLE
Unpublishing already published offer from an additional marketplace

### ISSUE THREAD

**Issue by PupuCz** [allegro/allegro-api#7992]
Hello, 
I would like to ask how to unpublish, or deactivate an offer from an additional marketplace only? I've created an offer on allegro-pl, which is my base marketplace and later I published said offer to allegro-cz. Then I wanted to leave the offer public for allegro-pl and remove it for allegro-cz, so I removed the additinal marketplace properties from the dto and updated (PATCH) the offer, but the offer on allegro-cz is still active (ID 7732885530). Everything related to publishing/unpublishing offers seems to work only for the base marketplace, so I'm not sure if there is any way to achieve unpublishing offer only for additional marketplaces?

WITH allegro-cz
`{"productSet":[{"product":{"id":"01a5eb72-cc43-4f98-b62c-fb00d0a032c8","idType":"GTIN"},"quantity":{"value":1}}],"stock":{"available":263,"unit":"UNIT"},"publication":{"marketplaces":{"additional":[{"id":"allegro-cz"}]}},"afterSalesServices":{"returnPolicy":{"id":"6ab0ffdb-a764-4ed9-be3c-8b0e86318f40"}},"additionalMarketplaces":{"allegro-cz":{"sellingMode":{"price":{"amount":"234.00","currency":"CZK"}}}},"sellingMode":{"format":"BUY_NOW","price":{"amount":"38.22","currency":"PLN"}},"external":{"id":"218"},"taxSettings":{"rates":[{"rate":"23.00","countryCode":"PL"},{"rate":"21.00","countryCode":"CZ"}]}}
`

WIHTOUT allegro-cz
`{"productSet":[{"product":{"id":"01a5eb72-cc43-4f98-b62c-fb00d0a032c8","idType":"GTIN"},"quantity":{"value":1}}],"stock":{"available":263,"unit":"UNIT"},"afterSalesServices":{"returnPolicy":{"id":"6ab0ffdb-a764-4ed9-be3c-8b0e86318f40"}},"sellingMode":{"format":"BUY_NOW","price":{"amount":"38.22","currency":"PLN"}},"external":{"id":"218"},"taxSettings":{"rates":[{"rate":"23.00","countryCode":"PL"}]}}`

Thank you very much

**Comment by MartaNowaczyk** [comment]
You can remove the intention for the offer to be visible in additional marketplaces by [managing offers in bulk](https://developer.allegro.pl/tutorials/listing-and-managing-offers-on-foreign-marketplaces-7GndGjeAATn#managing-offers-in-bulk) - [PUT /sale/offer-modification-commands/{commandId}](https://developer.allegro.pl/documentation#operation/modificationCommandUsingPUT).

**Comment by PupuCz** [comment]
Ok, I understand, thank you.
