### ISSUE TITLE
Ustawienie widomości w chacie jako nie przeczytana

### ISSUE THREAD

**Issue by antoniSea** [allegro/allegro-api#7994]
Hej, czy jest możliwość aby ustawić chat z konkretnym użytkownikiem jako nie przeczytany przez API?

**Comment by Lukasz-Zurek** [comment]
@antoniSea Nie, nasze API umożliwia jedynie oznaczenie wybranego wątku jako "przeczytany". Nie mamy opcji dotyczącej oznaczenia jako "nieprzeczytany".
