### ISSUE TITLE
Czy możliwe jest po API wykonanie przeglądarkowej opcji "Wyłącz dostawy szybsze niż moja deklaracja"?

### ISSUE THREAD

**Issue by MaciejFrackowiak** [allegro/allegro-api#7997]
### Discussed in https://github.com/allegro/allegro-api/discussions/7996

<div type='discussions-op-text'>

<sup>Originally posted by **tomasz-grzesik** November 20, 2023</sup>
Pare osób ze Zjednoczonych Sprzedawców twierdzi, że otrzymali taką informację od pracownika Allegro.</div>

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma takiej opcji dostępnej w API.

**Comment by tomasz-grzesik** [comment]
Tak myślałem. Dziękuję za potwierdzenie.
