### ISSUE TITLE
Dostawa Allegro One Punkt 

### ISSUE THREAD

**Issue by Mariusz175** [allegro/allegro-api#7998]
Brak w środowisku testowym metody dostawy Allegro One Punkt, Box obsługiwanego przez kuriera UPS "Allegro One Box" oraz "Allegro One Punkt". Wszystkie zamówienia z dostawą do One punkt są składane jakby były obsługiwane przez kuriera Allegro "Allegro One Punkt, One Kurier". Proszę o naprawę. 

Dodatkowo nasz adres nadawczy, który jest w środowisku produkcyjnym obsługiwany przez kuriera Allegro One, w środowisku testowym nie jest obsługiwany. Proszę o dodanie kodu pocztowego nadawcy "80-298". Podczas testów wyskakuje błąd "Kod pocztowy nadawcy znajduje się poza obszarem One Kuriera"

**Comment by MaciejFrackowiak** [comment]
Sprawę konsultuję z zespołem odpowiedzialnym za usługę, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Odnośnie pierwszego zagadnienia - dokonaliśmy niezbędnej poprawki, obecnie zamówienia Allegro One Box oraz Allegro One Punkt realizowane są przez UPS.

Druga kwestia - tu działam w temacie.

**Comment by MaciejFrackowiak** [comment]
Kod 80-298 powinien być już dostępny na Sandbox.
