### ISSUE TITLE
[WzA] - problem z odświeżaniem tokenu

### ISSUE THREAD

**Issue by lukasz-lopata** [allegro/allegro-api#7999]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Pojawił się problem z odświeżaniem tokenu podczas korzystania z Wysyłam z Allegro, niestety endpoint odświeżający token nie zwraca trace-id, ale postaram się opisać problem.

Przypisanie konta do allegro zwraca nam Access token X oraz refresh token Y.

12 godzin później następuje odświeżenie tokenu https://allegro.pl/auth/oauth/token, gdzie w parametrze refresh_token przekazujemy Y. Token odświeża się poprawnie, otrzymujemy Access token L i Refresh token Z.

12 godzin pozniej nastepuje odswiezenie tokenu https://allegro.pl/auth/oauth/token, gdzie w parametrze refresh_token przekazujemy Z. W tym momencie otrzymujemy błąd:

"Błąd podczas odświeżania tokenu:  invalid_grant Invalid refresh token: Z". 

Posiadamy Access token oraz refresh token dla którego wystąpił błąd. Czy to może Państwu pomóc w prześledzeniu problemu?
Pozdrawiam
Łukasz Łopata

**Comment by MaciejFrackowiak** [comment]
Proszę przekaż wspomniane dane poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) - dodaj proszę info, że są to dane do zgłoszenia GitHub #7999.

**Comment by lukasz-lopata** [comment]
Wysłano

**Comment by MaciejFrackowiak** [comment]
Otrzymaliśmy Twoje dane i dzięki temu mogłem przeanalizować sytuację (będę odnosić się do Twoich akapitów)
1) Przypisane konta allegro: - otrzymałeś nową parę access + refresh 15/11/2023 14:30
2) Pierwsze odświeżenie: - nowa para access + refresh przy wykorzystaniu refresh z punktu 1 - 16/11/2023 8:58
3) Błąd przy drugim odświeżeniu: - refresh z punktu 2 wykorzystałeś 17/11/2023 o godz. 9:32 - w wyniku tej operacji otrzymałeś nową parę access + token
4) 17/11/2023 10:16 - tu otrzymujesz komunikat "invalid_grant Invalid refresh token", ponieważ jako refresh wykorzystujesz ponownie ten z punktu 2, którego już wykorzystałeś o 9:32.
