### ISSUE TITLE
REST Dziwne wyniki metody /pricing/offer-quotes

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#8]
Request
```
GET https://allegroapi.io/pricing/offer-quotes?offer.id=7133959477 HTTP/1.1
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer ey(...)mg
Api-Key: eyJjbG(...)bPM=
Host: allegroapi.io

```

Response
```
HTTP/1.1 200 OK
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Trace-Id: 5701aadda537881e
Date: Thu, 15 Feb 2018 15:53:07 GMT
X-RateLimit-Remaining: 8997
X-Content-Type-Options: nosniff
Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
Content-Length: 165
X-RateLimit-Limit: 9000

{"count":1,"quotes":[{"type":"BOLD","name":"Pogrubienie","nextDate":"2018-02-15T15:09:57.008Z","fee":{"amount":"9.0","currency":"PLN"},"offer":{"id":"7133959477"}}]}
```

**Błędy:**
1. nextDate jest z przeszłości (obecnie sprzed 47 minut)
2. Aukcja nie jest promowana (ale kiedyś była, chyba właśnie pogrubiona)

**Comment by MarcinLuczak** [comment]
Dziękuję. Przekazałem to zgłoszenie do odpowiedniego działu, gdzie zostanie ono przeanalizowane.

**Comment by MarcinLuczak** [comment]
Mam informację, że te dwie kwestie zostaną poprawione, ale nie jestem w stanie podać żadnego terminu.

**Comment by rtnet-pl** [comment]
Nieśmiało przypominam się z tematem 🔢

**Comment by MarcinLuczak** [comment]
Zapewniam, że pamiętamy o tej kwestii, ale zmiana tych elementów może trochę potrwać.

**Comment by Jarzebowsky** [comment]
Coś jest działane w tej sprawie, funkcja dalej nie działa, a same oznaczenia BETA sprawują się lepiej niż te starsze. Na ten moment response wraca pusty.
