### ISSUE TITLE
doGetItemsInfo i itemAfterSalesServiceConditions

### ISSUE THREAD

**Issue by grola** [allegro/allegro-api#80]
Pobierając dane oferty metodą doGetItemsInfo w strukturze itemAfterSalesServiceConditions otrzymuję puste wartości mimo, że aukcja ma ustawione wszystkie dane.

**Comment by KrzysztofLukanowski** [comment]
Czy na wejściu określiłeś parametr getAfterSalesServiceConditions = 1?

**Comment by grola** [comment]
Nie, dzięki za naprowadzenie - po dodaniu parametru zadziałało.

Wcześniej chyba działało bez tego parametru?

**Comment by KrzysztofLukanowski** [comment]
Od momentu wprowadzenia warunków dla oferty, domyślnie było 0, czyli nie były pobierane.

**Comment by grola** [comment]
Dziękuję za informację.
