### ISSUE TITLE
Metoda WEBAPI doShowItemInfoExt nie zwraca danych

### ISSUE THREAD

**Issue by kocyk74** [allegro/allegro-api#800]
Od rana metoda WEBAPI doShowItemInfoExt nie zwraca danych.

**Comment by PawelTaberski** [comment]
Sprawdziłem i metoda działa poprawnie, czy problem u Ciebie nadal występuje?

**Comment by kocyk74** [comment]
Tak cały czas response wygląda w ten sposób:

```
HTTP/1.1 100 Continue
Content-Length: 0

HTTP/1.1 200 OK
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Set-Cookie: ws2=293(...); expires=Mon, 22-Oct-2018 11:55:21 GMT; path=/; domain=.allegro.pl
Set-Cookie: QXLSESSID=9c4aaa(...); path=/; domain=.allegro.pl; secure; HttpOnly
Status: 200 OK
Server: Apache
Pragma: no-cache
X-SOAPMethod: doShowItemInfoExt
Date: Mon, 22 Oct 2018 11:25:21 GMT
Connection: close
Vary: Accept-Encoding
Content-Type: text/xml;charset=UTF-8
X-SOAPIgnore: true
```

**Comment by PawelTaberski** [comment]
Niestety nie mogę powtórzyć tego błędu po statusie widzę, że niby wszystko powinno być ok, rozumiem, że otrzymujesz pustą odpowiedź, bez danych. Czy problem występuje tylko na jakiejś ofercie czy na wielu? Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) numer oferty na jakiej występuje taki błąd, klucz z jakiego korzystasz i id usera, a także jeśli masz konkretne czasy wywołań. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że informacje są potrzebne do ticketa numer 800 na GitHub-ie.

**Comment by kocyk74** [comment]
Problem występuje na wielu ofertach. Sprawdziłem jeszcze raz kilkanaście minut temu takie trzy: 7024745473, 7483953130, 7483983270. Reszta informacji poszła przez formularz.

**Comment by PawelTaberski** [comment]
Przy podesłanych przez Ciebie ofertach udało mi się otrzymać responsa, ponadto na Twoim kluczu przy tej metodzie nie widzę żadnych problemów. Przekazałem sprawę do dokładniejszej weryfikacji do odpowiedniego zespołu, proszę o cierpliwość.
Upewnij się, że po Twojej stronie nie występuje jakiś problem z odbiorem responsów.

**Comment by kocyk74** [comment]
Myślę, że wiem skąd rozbieżność w responsach.
Bardzo stary kod po mojej stronie korzysta jeszcze z tego wsdl'a https://webapi.allegro.pl/uploader.php
Po zmianie na service.php otrzymuje normalne odpowiedzi.
