### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by SlaWitDev** [allegro/allegro-api#8000]
Dzień Dobry.
Proszę o aktywację konta sandbox, login: ProlineSW
Obecnie sprzedaż jest zablokowana.

Dziękuję.

**Comment by SlaWitDev** [comment]
Przelew zrobiony, pdf dołączony, krokowiec pokazuje 40% i zegarki przy pkt. 2 i 3.

**Comment by MaciejFrackowiak** [comment]
Wszystko się zgadza - konto aktywne!

**Comment by SlaWitDev** [comment]
Dziękuję.
