### ISSUE TITLE
403 /sale/products

### ISSUE THREAD

**Issue by SlaWitDev** [allegro/allegro-api#8002]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Get search products results: https://api.{{environment}}/sale/products?phrase=4719331311438&mode=GTIN
Get all data of the particular product: https://api.{{environment}}/sale/products/58f9d482-d4b6-4cb5-97e7-97be938dd13b

sandbox, clientId: d70bfb55a2ab49e9bb8c2cd3e39d375c
production, clientId: 87fdd8ca-885e-43ae-aae6-34f30997b2c4

Always responds:
403 Forbidden with body
{
    "errors": [
        {
            "code": "AccessDenied",
            "message": "Access is denied",
            "details": null,
            "path": null,
            "userMessage": "No access to the specified resource."
        }
    ]
}

Produkt prawidłowo widoczny w ofercie:
https://api.allegro.pl/sale/product-offers/13076154424
ID: 58f9d482-d4b6-4cb5-97e7-97be938dd13b
EAN: 4719331311438
Kod producenta: GV-N4090GAMING OC-24GD

**Comment by MartaNowaczyk** [comment]
W logach widzę, że w nagłówku Accept podajesz betę `application/vnd.allegro.beta.v1+json` zamiast public `application/vnd.allegro.public.v1+json`.

**Comment by SlaWitDev** [comment]
Nagłówek Accept nie był wogóle wysyłany - jedynie Content-Type: application/vnd.allegro.public.v1+json. 
Dodanie nagłówka Accept: application/vnd.allegro.public.v1+json załatwiło sprawę, dziękuję za pomoc.
