### ISSUE TITLE
Zakończenie oferty - szkic?

### ISSUE THREAD

**Issue by gbr161** [allegro/allegro-api#8004]
Witam, 
Implementuję zakańczanie ofert poprzez API. 
Endpoint to '/sale/offer-publication-commands/' , akcja 'END' , środowisko sandbox. Oferta zamiast zostać oznaczona jako zakończona zostaje przekształcona w szkic. W jaki sposób uniknąć takiego zachowania i po prostu zakończyć ofertę?
Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Witam, podaj proszę trace-id z takim zachowaniem, abym mogła prześledzić to na konkretnym przykładzie.

**Comment by gbr161** [comment]
9b3c4b40bbe72c54

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Z tego co widzę w logach ofertę z podanego trace-id zakończono 8.11.2023 i w danych oferty ma poprawny status:
```
"publication": {
        "status": "ENDED",
        "duration": null,
        ...
    },

```
Wygląda to tak, że 20.11. próbujesz zmienić status tej samej oferty na "END", choć oferta jest już zakończona. Widzę też requesty z próbą usuwania draftu (DELETE /sale/offers/{offerId}), ale ta oferta nie jest draftem i dostajesz komunikat, "Możesz usunąć tylko szkic oferty." - tym zasobem można usunąć tylko oferty o statusie “INACTIVE”, a ta o której mówimy, ma status "ENDED".
Możesz podesłać mi gdzie dostajesz informację, że to draft?
