### ISSUE TITLE
How to create an offer with discount

### ISSUE THREAD

**Issue by barbasfilip** [allegro/allegro-api#8005]
Hi, I am trying to create an offer with discount.  My base market is allegro-cz. I checked this https://developer.allegro.pl/documentation/#operation/createPromotionUsingPOST_1, but it says "You can create promotions only if your base marketplace is allegro-pl" Is there any option how can I create an offer with discount?

Thank you.

**Comment by MartaNowaczyk** [comment]
On the base marketplace allegro-cz there is no such possibility.

**Comment by barbasfilip** [comment]
OK I understand. So could you please tell me where this functionality will be available for allegro-cz?

Thank you

**Comment by MartaNowaczyk** [comment]
We don't have the option to promote or discount offers for allegro.cz via API. 
You can ask about other options via [contact form](https://allegro.cz/pomoc/kontakt?category=02bc595b-6c50-4c0a-9281-3a3bffa11c8d).
