### ISSUE TITLE
Aktualizacja lineItems w zamówieniu

### ISSUE THREAD

**Issue by gitrid** [allegro/allegro-api#8006]
Proste pytanie, ale nie mogłem znaleźć odpowiedzi bezpośrednio w dokumentacji: używając [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET), przedmioty w zamówieniu zwracane są w "lineItems". Czy mogą one być aktualizowane z jakiegokolwiek powodu, czy są stałe i niezależne od statusu zamówienia?

**Comment by AureliuszBrussy** [comment]
Pole "lineItems" nie zmienia się w całym cyklu życia zamówienia. Dodam jednak, że jeden lineItem.id może występować w kilku zamówieniach - jednakże wyłącznie w sytuacji połączenia zakupów od jednego sprzedającego przez kupującego.

**Comment by gitrid** [comment]
Dziękuję, wszystko jasne.
