### ISSUE TITLE
/pricing/offer-fee-preview i brak price list dla kategorii

### ISSUE THREAD

**Issue by szsabina** [allegro/allegro-api#8007]
Cześć,
Dla ponad 7000 kategorii które mamy w naszym systemie GET /pricing/offer-fee-preview zwraca błąd 422 o treści:

> There is no price list for given category

Problem występuje także przy kategoriach, które stanowią liść w drzewie kategorii i wydaje mi się, że dotyka też kategorii które wcześniej działały (np. kategoria 258986 - RTV i AGD). Z czego on wynika?

**Comment by AureliuszBrussy** [comment]
Czy możesz wskazać trace-id przykładowych wywołań zakończonych tym błędem dla kategorii liści? Trace-id znajdziesz w nagłówku naszego response'a.

**Comment by szsabina** [comment]
Jasne, podrzucam kilka dla różnych kategorii:
`bf0764c4094a3d4f`
`ed29c8061bf28408`
`4eef869d1857c648`
`3682b33156271fd7`
`5309a2d7524a0d9e`

**Comment by AureliuszBrussy** [comment]
Z tego co widzę - każda z tych kategorii jest kategorią ogłoszeniową (dla [GET /sale/categories/{categoryId}](https://developer.allegro.pl/documentation#operation/getCategoryUsingGET_1) zwracamy `"advertisement": true`).  Jeśli sprawdzasz opłaty dla ogłoszenia, to powinieneś przekazać odpowiednie pakiety w polu `classifiedsPackages`, inaczej zawsze zwrócimy 422.
