### ISSUE TITLE
Utworzenie przesyłki - Błąd z nadaniem przesyłki

### ISSUE THREAD

**Issue by tomi007** [allegro/allegro-api#8008]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Po wywołaniu metody GET shipment-management/shipments/create-commands/$commandId

Dostaję zwrotkę

`  "commandId" => "5b86ae7a-ff66-4765-8f29-af7bcbb3ec55"
  "status" => "ERROR"
  "errors" => array:1 [▼
    0 => array:5 [▼
      "code" => "PROCESSING_ERROR"
      "message" => "Problem with dispatch. Contact us, and we will help as soon as possible."
      "details" => null
      "path" => null
      "userMessage" => "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."
    ]
  ]
  "shipmentId" => null`

**Comment by AureliuszBrussy** [comment]
Analizujemy ten przypadek. Wrócę do Ciebie z informacją jak tylko coś ustalimy.

**Comment by tomi007** [comment]
> Analizujemy ten przypadek. Wrócę do Ciebie z informacją jak tylko coś ustalimy.

Czy coś wiadomo?

**Comment by AureliuszBrussy** [comment]
Wygląda to na bug po naszej stronie. Analizujemy to jeszcze i będziemy poprawiać. Wrócę z informacją po poprawce.

**Comment by tomi007** [comment]
> Wygląda to na bug po naszej stronie. Analizujemy to jeszcze i będziemy poprawiać. Wrócę z informacją po poprawce.

Przypominam się, jestem zblokowany :)

**Comment by MaciejFrackowiak** [comment]
@tomi007 Niestety, weryfikacja problemu nadal jest w toku. Wrócimy ze szczegółami, gdy tylko będziemy posiadać konkretne informacje.

**Comment by tomi007** [comment]
> @tomi007 Niestety, weryfikacja problemu nadal jest w toku. Wrócimy ze szczegółami, gdy tylko będziemy posiadać konkretne informacje.

Czy możecie mi wskazać jakąś datę konkretną? Niestety jesteśmy zastopowani i nie możemy działać na pełnych obrotach

**Comment by tomi007** [comment]
> Niestety, ale na chwilę obecną takiej daty nie możemy określić. Weryfikacja źródła problemu, jak i ewentualna poprawka wymaga szczegółowej, wieloskładniowej analizy, gdzie bazujemy również na danych spoza naszych mechanizmów. Co kluczowe i istotne - takie błędne odpowiedzi stanowią dosłownie promil ogółu zapytań, stąd weryfikacja tego problemu jest zdecydowanie utrudniona.

Dlatego w ramach przypomnienia będę się co jakiś czas przypominał. Proszę chociażby o jakąś ścieżkę awaryjną? mam założyć nowe konto? cokolwiek?

**Comment by tomi007** [comment]
> Nie ma "ścieżki awaryjnej" - problem dotyka de facto jednostkowych requestów w skali działania całej usługi Wysyłam z Allegro, stąd inwestygacja nie jest oczywista. Jeżeli będę posiadał wiążące informacje zwrotne, wrócę z odpowiedzią.

Usterka trwa już 2 tygodnie

**Comment by MaciejFrackowiak** [comment]
Czy każdy Twój request kończy się wspomnianym błędem?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj mi trace-id jednego z ostatnich Twoich wywołań.

**Comment by tomi007** [comment]
> Proszę podaj mi trace-id jednego z ostatnich Twoich wywołań.

Co to jest trace-id ?

**Comment by tomi007** [comment]
Podczas GET shipment-management/shipments/create-commands/{commandId}
Teraz dostaje error NOT_AUTHORIZED message This account does not exist 

Autentykuje się poprzez Bearer Token. Wszystkie inne enpointy działają, z czym może być problem?

**Comment by MaciejFrackowiak** [comment]
Sprawę weryfikuję z zespołem odpowiedzialnym za usługę. Wrócę z odpowiedzią.

**Comment by tomi007** [comment]
Rozumiem, że przez miesiąc czasu nie dało się nic ustalić ?

**Comment by MaciejFrackowiak** [comment]
Niestety nie. Jak wspomniałem wcześniej - gdy otrzymam szczegóły, wrócę z odpowiedzią.

**Comment by tomi007** [comment]
To nie zamykajcie wątku. Jest jakiś określony czas na zweryfikowanie zgłoszenia?

**Comment by MaciejFrackowiak** [comment]
To działający automat samoczynnie zamyka wątki po 7 dniach bezczynności. Nie mamy jednego SLA na rozwiązanie ewentualnych problemów. Twój przypadek jest na tyle złożony, że wymaga zaangażowania zewnętrznych podmiotów, co przekłada się na termin realizacji. W skrócie - gdy tylko problem zostanie rozwiązany / zidentyfikowany to wówczas zamieszczę w wątku odpowiednie info.

**Comment by tomi007** [comment]
halo

**Comment by MaciejFrackowiak** [comment]
Zgodnie z wcześniejszymi wiadomościami mogę tylko raz jeszcze napisać - jeśli problem zostanie rozwiązany, to dam znać w tym wątku.

**Comment by MaciejFrackowiak** [comment]
@tomi007 Czy posiadasz bieżący przykład wywołania, który zakończył się opisywanym błędem? Zespół chce przyjrzeć się dokładnie problemowi, dlatego ważne jest, aby opierać się na aktualnych danych.
