### ISSUE TITLE
Błąd TransactionTaxSettingsNotFoundException

### ISSUE THREAD

**Issue by keczerad** [allegro/allegro-api#8009]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Nie można dodać produktu ze stawką 0 na sandoxie ? 

[Traceid:](trace-id: e9f617f4ce397334)

**Comment by AureliuszBrussy** [comment]
Sprawdź dostępne stawki w danej kategorii (GET /sale/tax-settings?category.id={categoryId}). Dla kategorii z Twojego requestu nie ma wariantu ze stawką 0.00.
