### ISSUE TITLE
Sandbox dispatch

### ISSUE THREAD

**Issue by BarnetMichal** [allegro/allegro-api#8010]
Hello,
1) Are there access credentials for the carrier on the sandbox to dispatch the order from the sandbox account? 
2) Can the shipment be split into multiple shipments? I can enter multiple tracking codes but I can't find where to assign the order item to a specific shipment.

**Comment by AureliuszBrussy** [comment]
1. I understand it is about own carrier agreements under WzA on Sandbox?  It would be best if you asked the carrier directly for such access data to the test carrier API. 

2. You can send multiple packages to a single order and indicate that the tracking number is for a specific lineItem. Check endpoint [POST /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation#operation/createOrderShipmentsUsingPOST).

**Comment by BarnetMichal** [comment]
Is it possible to create multiple package shipments via UI? Without carrier agreements, I can't get past the dispatch form.

**Comment by AureliuszBrussy** [comment]
Multi-packing within a single shipment is currently supported only by DPD and WEDO. I only mentioned that you can add more than one tracking number to one order, and you can indicate to which specific lineItem the tracking number was added. 

There is no way in the UI to indicate to which LineItem a specific tracking number has been added. Is an option available only through the API.
