### ISSUE TITLE
Metoda  /sale/offer-quantity-change-commands

### ISSUE THREAD

**Issue by keczerad** [allegro/allegro-api#8011]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ X] ze środowiskiem produkcyjnym / with the production environment
 - [ ]X ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Czemy to jest tak :

![image](https://github.com/allegro/allegro-api/assets/22832921/1ed84101-1f92-42ff-a09e-8f6d7912a496)

a nie tak  ?
![image](https://github.com/allegro/allegro-api/assets/22832921/c33b1b2e-268f-4e73-ad6c-d7cee3a48299)

Rozumiem ze sensu mojego wątku nie musze tłumaczyć ?

**Comment by AureliuszBrussy** [comment]
Rozumiem Twoją sugestię. Najlepiej, jeżeli zgłosisz ją w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions) - wtedy więcej użytkowników będzie miała szanse ją poprzeć i takie ewentualne zmiany są dla nas wtedy bardziej priorytetowe.
