### ISSUE TITLE
how to create product

### ISSUE THREAD

**Issue by skutop001** [allegro/allegro-api#8012]
Hello

I need to create products in the Allegro platform's store, but I don't know which API to use, is/sell/product offers or/sell/product proposals. Additionally, what I don't understand is what Offer refers to?

Also, the id and idType under the product object are UPC code and UPC code, but do I need to upload the SKU code at the same time?
Finally, thank you for your help

**Comment by MaciejFrackowiak** [comment]
If you want just to add the product to our product catalogue, you should use [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct) resource. If you want to list an offer with the assigned product, you should use [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) resource. Please, read [our tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6) where we describe that process precisely.

**Comment by skutop001** [comment]
Thank you for your help. The products that consumers can see should be the POST/sell/product offers resource So is sku code a mandatory parameter to pass?

**Comment by MaciejFrackowiak** [comment]
It depends on what you mean by SKU:
- if SKU is GTIN (EAN) code - it is required in most Allegro categories;
- if SKU is your internal signature (reference number) - in such cases no.

**Comment by skutop001** [comment]
I think the GTIN (EAN) code should be upc (Universal Product Code), so the sku code is our internal code, and I can put it in external, right? Thank you again

**Comment by skutop001** [comment]
I think the GTIN (EAN) code should be upc (Universal Product Code), so the sku code is our internal code, and I can put it in external, right? Thank you again.

**Comment by MaciejFrackowiak** [comment]
Yes, the "external.id" field is a place where you can put your internal code.
