### ISSUE TITLE
Pobieranie historii statusów - parametr description

### ISSUE THREAD

**Issue by przemyslawpipala** [allegro/allegro-api#8014]
Dzień dobry, 

odpytując historię statusów przesyłki za pomocą metody GET /order/carriers/{carrierId}/tracking?waybill={waybill} zwracany jest status za pomocą parametru "code", który dotyczyć może różnych zdarzeń. Dokładniejszy opis jest podany w parametrze "description", stąd pytanie, czy wartość w tym parametrze jest domyślnie zwracana? Czy często zdarzają się przypadki, w których request nie zwraca tego parametru? 

Dziękuję z góry za odpowiedź :)

**Comment by MaciejFrackowiak** [comment]
Jest to pole dodatkowe, w którym zwyczajowo opisywane są problemy z przesyłką. Jednak co kluczowe, nie jest to pole obowiązkowe, zatem dany przewoźnik może zwracać w nim informacje lub nie.

**Comment by przemyslawpipala** [comment]
Dziękuję za odpowiedź. Głównie zależy mi na śledzeniu przesyłek gdzie carrierId = Allegro, czy w takim przypadku raczej parametr "description" będzie zwracany, czy to również może zależeć np. od przewoźnika, który pośredniczy w transporcie takiej przesyłki? Albo czy często może się taka sytuacja zdarzać? Bo jeżeli będą to raczej nieliczne przesyłki, to również będę usatysfakcjonowany taką informacją.

**Comment by MaciejFrackowiak** [comment]
Na Twoje pytanie nie ma jednoznacznej odpowiedzi - zawartość w polu "description" może się pojawić, ale nie mogę Ci zadeklarować, że przykładowo dziś będzie, a jutro nie.

**Comment by przemyslawpipala** [comment]
Ok, dziękuję za informacje :)
