### ISSUE TITLE
TaxSettings - Unprocessable Entity

### ISSUE THREAD

**Issue by Devvnul** [allegro/allegro-api#8015]
Witam, dostaję Unprocessable przez model "TaxSettings". Patrząc na tutorial dodawania oferty przez API wszystko wygląda identycznie tak samo. Czy mógłbym prosić o sprawdzenie o co może chodzić?

trace-id=50c7b73a6f06d4af

**Comment by MaciejFrackowiak** [comment]
Dla każdej kategorii przypisane są inne ustawienia i identyfiaktory stawek VAT. W związku z tym skorzystaj z [GET /sale/tax-settings](https://developer.allegro.pl/documentation/#operation/getTaxSettingsForCategory) by pobrać właściwe ustawienia dla kategorii Twojej oferty tj. 110911.
