### ISSUE TITLE
How to obtain completed refund orders through the API

### ISSUE THREAD

**Issue by bingnew** [allegro/allegro-api#8017]
Dear Allegro team,

Our ERP system wants to retrieve orders with completed refund status through the platform API interface. 
Currently, we can obtain a value for the refund field through the **Get customer returns by provided query parameters** interface. Does this mean that this order has been refunded? If my understanding is incorrect, please tell me how to obtain a refund order with a completed status
In which field is the refund amount obtained?

Looking forward to your reply
![image](https://github.com/allegro/allegro-api/assets/72594584/c2b524e4-1678-49dd-b092-1574c468baab)

**Comment by bingnew** [comment]
In addition, we obtained a refund order with a status of success through the [GET / payments/refunds](https://github.com/allegro/allegro-api/issues/8017#operation/getRefundedPayments) interface, but there was no order_id in the returned data.

**Comment by MartaNowaczyk** [comment]
1. this is only the data for the return of the deposit. It is not a refund confirmation. The status is only for payment returns.

2. There is no order in the payment returns, but there is the buyer's payment ID.
