### ISSUE TITLE
Problem z nadaniem przesyłki  One Box

### ISSUE THREAD

**Issue by RafGra2022** [allegro/allegro-api#8018]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Po wywołaniu metody GET shipment-management/shipments/create-commands/$commandId

Przy próbie rejestracji przesyłki przez REST API dostaje odpowiedź z timeoutem:
wcześniej kilkakrotnie odpowiedź ze statusem "status":"IN_PROGRESS"
jaka jest przyczyna tego problemu?

{
    "id": "79d1a5f7-a945-41bf-8e53-0185912a6eba",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "COMMAND_TIMEOUT",
            "message": "The time for completing the order has expired",
            "details": null,
            "path": "/parcel-management/parcel-create-commands/79d1a5f7-a945-41bf-8e53-0185912a6eba",
            "userMessage": "Upłynął limit czasu na wykonanie zlecenia"
        }
    ]
}

**Comment by MartaNowaczyk** [comment]
Problem jest po naszej stronie i dotyczy przesyłek Allegro ONE. Pracujemy nad poprawą sytuacji.

**Comment by RafGra2022** [comment]
ok,  teraz działa poprawnie, dziękuję!
