### ISSUE TITLE
Product card changes suggestion

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#8019]
Hi there, 

I just wanted to double check with you if I understand correctly when there is a problem in the product card. 

When we try to connect our offer to already existing product card and we get an error, that for example the brand is missing in the product card. We should use POST /sale/products/{productId}/change-proposals, correct? 

In you documentation is written: 
"You must provide:
- product name,
- category - changing the category requires providing all the parameters required under this new category,
- parameters - all required for the category in which the product is located,
- photo - at least one."

So even though we just need to suggest the missing parameter "brand" we need to send product name, category, all the parameters and photo as well? Or is it enough just to send the product ID and the parameter we want to add/change? 

Thank you in advance for your help! 

All the best, 

Dominika

**Comment by MartaNowaczyk** [comment]
Hi Dominika,
If in response you get a message to complete the missing mandatory parameters, pass them in the product object. Specify the product id and other necessary values, like "sellingMode" and "stock." If you don't want your own description and photos you don't need to provide them, we will get them from the product.
