### ISSUE TITLE
Wapro Aukcje - brak możliwości powiązania artkułów z WF-maga z artykułami z Allegro za pomocą kodów kreskowych . 

### ISSUE THREAD

**Issue by LEMARHURT** [allegro/allegro-api#8020]
API Allegro nie przesyła do Wapro Aukcje kodów kreskowych wystawionych w Allegro towarów. Nie ma możliwości powiązania ze sobą artykułow . Gdzie jest błąd?

**Comment by AureliuszBrussy** [comment]
Skontaktuj się z supportem oprogramowania, z którego korzystasz (Wapro) - to w pierwszej kolejności oni powinni sprawdzić, jaki mają problem z pobieraniem niezbędnych Tobie danych.

**Comment by LEMARHURT** [comment]
Wapro twierdzi , że program Wapro Aukcje pobiera dane z API Allegro , jakie są udostępniane przez API . Widocznie Api nie przesyła kodów EAN  , które są niezbędne do powiązania produktów z Allegro  z produktami z Wapro. Proszę o sprawdzenie.

**Comment by AureliuszBrussy** [comment]
EAN zwracamy na liście parametrów produktu po odczytaniu szczegółów oferty ([GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/getProductOffer)). Jeżeli taka informacja jest zapisana w ofercie - zwracamy takie dane.
