### ISSUE TITLE
Uwierzytelnianiu API Allegro w aplikacji bez dostępu do przeglądarki i klawiatury

### ISSUE THREAD

**Issue by baluszynski** [allegro/allegro-api#8021]
Witam, 

Jesteśmy zaangażowani w niekomercyjny projekt studencki, w którym potrzebujemy wykorzystać API Allegro do pobierania listy produktów. Aktualnie próbujemy skorzystać z endpointa GET /sale/products, wymagającego uwierzytelnienia poprzez bearer-token-for-user.

W naszym przypadku, aplikacja nie ma dostępu do przeglądarki ani klawiatury, co sprawia, że konwencjonalne uwierzytelnienie jest wyzwaniem. Zaznajomiliśmy się z metodyką uwierzytelniania za pomocą [DeviceFlow](https://developer.allegro.pl/auth/#DeviceFlow), jednakże chcielibyśmy potwierdzić, czy istnieje możliwość automatycznego odebrania access_tokena bez konieczności interakcji użytkownika w przeglądarce.

Czy po jednorazowym uwierzytelnieniu użytkownika za pomocą linku do przeglądarki, problem ten można rozwiązać poprzez wykorzystanie refresh_tokena w celu przedłużenia ważności tokena? Znalazłem informacje na temat [przedłużenia ważności tokena](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena), ale chciałbym upewnić się, czy jest to odpowiednia ścieżka dla naszego przypadku.

Bardzo dziękuję za udzielenie informacji i odpowiedzi na powyższe pytania. Wasza pomoc będzie nieoceniona w naszym projekcie.

Serdeczne pozdrowienia,

Paweł Bałuszyński

**Comment by shivson1337** [comment]
Tak, zgodnie z dokumentacją.

Aceess token jest ważny 12 godzin, a przez 3 miesięce możecie go odświeżyć przy użyciu refresh tokenu.
Refresh token jest ważny 3 miesiące i po każdym jego użyciu dostajecie nowy access token i nowy refresh token, które ponownie są ważne przez 12 godzin (Access token) i 3 miesiące (Refresh token).

Użycie refresh tokenu nie wymaga dodatkowych działań ze strony użytkownika w przeglądarce.

**Comment by AureliuszBrussy** [comment]
Potwierdzam to co napisał @shivson1337 - mechanizm odświeżania access tokena nie wymaga bezpośredniej interakcji użytkownika.

**Comment by baluszynski** [comment]
Dziękuję bardzo za pomoc, faktycznie zaimplementowanie przedłużenia ważności tokenu rozwiązało mój problem.
