### ISSUE TITLE
Ścieżki aplikacji 

### ISSUE THREAD

**Issue by dariawisniewska575** [allegro/allegro-api#8025]
Chciałabym robić autoryzację za pomocą linku: https://example.com/autoryzacja/1, gdzie 1 to id, które nie jest stałe, dla każdego usera będzie inne, czy jest jakiś sposób, aby dodać "uniwersalny" link na Allegro Developer do ścieżek aplikacji?

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma takiej możliwości. Możesz podać wiele adresów przekierowań z uwzględnieniem ograniczeń podanych w [poście](https://github.com/allegro/allegro-api/issues/2737).
