### ISSUE TITLE
Jak znaleźć produkt, który niby się wybrało przy wystawianiu?

### ISSUE THREAD

**Issue by jezewskiBNetrox** [allegro/allegro-api#8027]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam,
mam poważny problem z tworzeniem ofert. Tworząc ofertę otrzymuje błąd:
```json
{
  "errors": [
    {
      "code": "PARAMETER_MISMATCH",
      "message": "The provided parameter 'Rozmiar'(26388) value (39(26388_16384)) does not match the existing parameter value (40(26388_65536))",
      "details": null,
      "path": "productSet[0].product.parameters",
      "userMessage": "The specified product exists. The specified parameter `Rozmiar` with the value `39(26388_16384)` does not match the product parameter `40(26388_65536)`."
    }
  ]
}
```
Trace-Id: bb3aaa4336237c33
Problem polega na tym, że ja nie wiem, jaki to jest produkt. API nie informuje mnie o tym, z jakim produktem próbował dokonać powiązania. 

Próbowałem też wyszukać produkt poprzez zasób do wyszukiwania produktów w katalogu. Jednak poległem widząc, że ignorowane są filtry dynamiczne.

Trace-Id wyszukiwania: e3a9d205d3204196

Problem pojawił się na przestrzeni dni dla masy ofert i nie wiem, co z tym zrobić. 

Z kolei teraz użyłem zasobu do tworzenia/proponowania produktów do Katalogu i tam problem nie występuje:
49a678e5-f0ee-46b2-bedd-5acc1255bf5f

Jestem ogromnie skonfudowany działaniem API, proszę o wyjaśnienie i jakąś podpowiedź jak mogę rozwiązać ten problem.

**Comment by MartaNowaczyk** [comment]
Produkt, który znaleźliśmy to cf3ac84e-48f5-4548-ba59-2bb5a3bf5359.
Produktu najlepiej szukać po EAN lub kodzie produktu, to najbardziej zawęzi wyniki. Jeśli szukasz po filtrach powinieneś do wyszukiwania dodać parametr z kategorią `category.id=5540`

W sytuacjach, gdy znajdziemy produkt na podstawie przesyłanych danych, można:

- połączyć ofertę z istniejącym już produktem np. na podstawie EAN, zamiast tworzyć nowy produkt na podstawie oferty,
- zmienić swoją wartość w parametrze na tą z komunikatu błędu,
- jeśli widzisz, że wartość parametru jest prawidłowa, a to my mamy błąd w katalogu - zgłosić sugestię zmiany danych w tym produkcie.

**Comment by jezewskiBNetrox** [comment]
@MartaNowaczyk Okej, teraz widzę. Musiałem trochę zaktualizować wiedzę bo dawno nie korzystałem z tej wyszukiwarki. Dzięki
