### ISSUE TITLE
Product validation

### ISSUE THREAD

**Issue by PupuCz** [allegro/allegro-api#8028]
Hello, 
I would like to know more about product validation. How do you determine whether new product can be validated automatically or not? How long do the automatic and manual validations take?

I only found information below regarding this topic
![image](https://github.com/allegro/allegro-api/assets/27767312/9bec1973-7ed5-48c7-adb6-1f3e5a78ee06)

Thank you very much.

**Comment by MartaNowaczyk** [comment]
This process is outside of our Allegro API. It would be better if you ask this question through the [contact form](https://allegro.pl/pomoc/kontakt). Generally, the change request should be handled within 2 business days ([article](https://allegro.pl/dla-sprzedajacych/jak-zmienic-dane-w-produkcie-z-katalogu-allegro-ZGZG89WkOU0#how-to-check-what-is-going-on-with-your-change-request)).

**Comment by PupuCz** [comment]
Ohh ok, sorry, thank you for your help. Have a nice day .
