### ISSUE TITLE
Allegro was unable to find an exact match

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#8029]
Hi there, 

we would like to somehow tackle the issue, when we get the response from Allegro "Allegro was unable to find an exact match". Meaning we send an EAN via API and under this EAN you have more then one product card available. Do you have some process how to determine the best match? 

Or is it at least possible to somehow ask if the product card is correct? For example in this case, under the EAN 5907612236269 you can find 3 product cards:
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/f8e5d7c8-3226-4c67-ba5f-51d1a56b5243)

2 of them are missing a mandatory parameter "input power" and only one product card is complete. Is there an easy way how to validate the status of the product cards and choose the one that does not contain any errors? 

Thank you in advance for your help! 

All the best, 

Dominika

**Comment by MartaNowaczyk** [comment]
We don't have such functionality that you can validate products. If you find several products, you have to choose one yourself. If there is an error in any of them, it's best to report it right away: either [through the API](https://developer.allegro.pl/documentation/#operation/productChangeProposal) or via www - `https://allegro.pl/moje-allegro/sprzedaz/produkt/zglos-blad/{productID}`.
