### ISSUE TITLE
OfferRepository error podczas wznawiania oferty

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#803]
Witam,

wznawiałem własnie ponad 1k ofert, część przeszła, część nie.
jedna z problematycznych:

PUT sale/offer-publication-commands/d9fd4735-c275-4117-b128-39540a2246cf
request:
`{"publication":{"action":"ACTIVATE"},"offerCriteria":[{"offers":[{"id":"7508925112"}],"type":"CONTAINS_OFFERS"}]}`
response:
`{"id":"d9fd4735-c275-4117-b128-39540a2246cf","taskCount":{"total":0,"success":0,"failed":0}}`

GET sale/offer-publication-commands/d9fd4735-c275-4117-b128-39540a2246cf/tasks
```
                    [offer] => stdClass Object
                        (
                            [id] => 7508925112
                        )
                    [message] => OfferRepository error
                    [status] => FAIL
                    [scheduledAt] => 2018-10-22T15:21:16.304+02:00
                    [finishedAt] => 2018-10-22T15:21:28.715+02:00
                    [field] => publication
```

Podczas edycji via formularz otrzymuję:
```
Podczas wznowienia oferty wystąpiły błędy
Oferta nie może zostać wznowiona, ponieważ jest w trakcie kończenia. Poczekaj chwilę i spróbuj ponownie.
```

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) traceId zadania publikacji i pełnego cURL-a i responsa z publikacji i sprawdzenia statusu tego zadania sprawdzimy w czym jest problem. W zgłoszeniu zaznacz proszę, że informacje są potrzebne do ticketa numer 803 na GitHub-ie.

**Comment by dlis2010** [comment]
Ok, paczki wysłane.


PS W zakładce moje oferty po wybraniu statusu "zaplanowana" również od kilku dni "wiszą" mi dwie oferty ze statusem "w trakcie aktywacji".

**Comment by dlis2010** [comment]
Testowałeś to również na przesłanej ofercie? U mnie dalej to samo.

Być może to pomoże zlokalizować problem:
w piątek w celu synchronizacji naszej bazy ze stanami ofert na Allegro zmieniliśmy stan ponad 60 tysięcy ofert. Robiliśmy to dwuetapowo:
- wszystkie oferty które miały być zakończone dostały zlecenie zmiany na END
- wszystkie oferty które miały być wznowione dostały zlecenie zmiany na ACTIVATE

Tylko że, podczas publikacji ofert nie był brany pod uwagę aktualny stan oferty. 
Oznacza to, że:
- zlecenie wznowienia dostały oferty zarówno zakończone jak i te aktywne
- zlecenie zakończenia dostały oferty zarówno oferty aktywne jak i te już zakończone

Już wtedy działo się coś niepokojącego bo stan ofert zmieniał się przez kilkanaście godzin.
W zakładce "moje oferty" też działa się cuda, do dzisiaj po wybraniu "zaplanowana" różne oferty się tam pojawiają z statusem "w trakcie aktywacji".

Może warto przetestować u Was wznawianie aktywnej oferty i kończenie zakończonej oferty - może stąd problem, że powyższa oferta, która już jest zakończona cały czas jest w trakcie kończenia.

Dzięki za pomoc, uzbrajam się w cierpliwość ;)

**Comment by PawelTaberski** [comment]
To nie powinno być problemem, jednakże naprowadziło mnie to na pewien pomysł. 
Aktywowałem ofertę, potem zaraz ją zamknąłem i próbowałem na nowo aktywować i dostałem error. Najprawdopodobniej oferta nie zdarzyła się wewnątrz przeprocesować i dlatego powstał taki problem.
Sprawa jest w weryfikacji u zespołu odpowiedzialnego za te funkcjonalności, także proszę jeszcze o cierpliwość.
Ponadto dwa tygodnie temu mieliśmy pewne problemy z aktywacją ofert co mogło powodować problemy i duże opóźnienia. Teraz od czasu wprowadzenia limitu #749 nie odnotowaliśmy problemów z dużymi opóźnieniami.

**Comment by dlis2010** [comment]
@PawelTaberski witam, są już jakieś wstępne informacje?

nie ukrywam, iż aktualnie powoduje to spore problemy dla nas. 
Aktywne są aukcje których nie mamy na stanie oraz pokończone są aukcje które powinny być aktywne i nic nie możemy z tym zrobić.

Może moglibyśmy zakończyć wszystkie aukcje na koncie i wyczyścić ich "procesowanie"? - nie wiem jak macie to technicznie rozwiązane.

**Comment by PawelTaberski** [comment]
Pracujemy nad rozwiązaniem tego problemu. Dostałem informacje, że niedługo wdrożymy rozwiązanie, które rozwiąże te problemy. Aktualnie możesz spróbować jeszcze raz zakończyć te oferty.

**Comment by dlis2010** [comment]
Możesz bardziej sprecyzować termin "niedługo"? Na dniach, następny tydzień?
Sprawa naprawdę uciążliwa. Problem ten w takiej skali występuje tylko u nas na koncie czy globalnie?

**Comment by PawelTaberski** [comment]
Niestety nie znam dokładnego terminu ustawiłem zgłoszenie z wysokim priorytetem i dałem znać, że sprawa jest pilna. Mam nadzieję że uda się jak najszybciej rozwiązać problem. Wiem, ze udało się już namierzyć przyczynę.

**Comment by dlis2010** [comment]
@PawelTaberski widzę, że problem już rozwiązany od kilku dni wszystko ładnie śmiga.
Niestety dwie oferty od ponad tygodnia wiszą z statusem ACTIVATING - 7457371588 oraz
7508251055 - dostaje taki stan zarówno przez rest api jak i znajdują się w zakładce Moje oferty po wybraniu "zaplanowane"

**Comment by PawelTaberski** [comment]
Sprawdziliśmy i obie podesłane przez Ciebie oferty są aktywne, czy jak pobierzesz je przy pomocy metody GET na zasobie /sale/offers/{offerId} masz status activating?

**Comment by dlis2010** [comment]
Dokładnie tak

**Comment by dlis2010** [comment]
/sale/offers/{offerId} pokazuje ACTIVE 

nastomiast jak listuję oferty za pomocą /sale/offers to te dwie konkretne dostaje z statusem

**Comment by PawelTaberski** [comment]
Rozumiem, sprawdzimy to.

**Comment by PawelTaberski** [comment]
@dlis2010 Problem nie powinien już występować.

**Comment by mpysz** [comment]
Witam,
u mnie pojawił się podobny problem. Podczas wywołania metody `PUT https://api.allegro.pl/sale/offers/7662636295` zwracany zostaje błąd `(422) Unprocessable Entity`.

Podczas próby wznowienia przedmiotu przez formularz zwracany jest błąd:
> Oferta nie może zostać wznowiona, ponieważ jest w trakcie kończenia. Poczekaj chwilę i spróbuj ponownie.

**Comment by mpysz** [comment]
Przesyłam dwa trace-id:
**zadania publikacji**, tutaj request przechodzi poprawnie i zwracane jest `201 Created`, ale w panelu Allegro ciągle widnieje jako Zakończona i nie można jej wznowić `... ponieważ jest w trakcie kończenia.`
`trace-id: 27ee36a402e1367`

**aktualizacji oferty**, tutaj zwracany jest błąd `(422) Unprocessable Entity`
`trace-id: cabe3a658121e24e`

**Comment by PawelTaberski** [comment]
Zgłosiłem sprawę do odpowiedniego zespołu, proszę o cierpliwość.

**Comment by PawelTaberski** [comment]
@mpysz Problem w Twoim wypadku został spowodowany, przez to że zaplanowałeś ofertę do wystawienia, a następnie zakończyłeś ją przed wystawieniem. Nie zezwalamy na wznawianie takich ofert, ale możesz wystawić podobną np. przez formularz.
