### ISSUE TITLE
Autoryzacja ClientId i ClientSecret zwraca unauthorized na endpintach

### ISSUE THREAD

**Issue by SzymonZasada** [allegro/allegro-api#8030]
Cześć

Posiadam parę kont allegro załóżmy allegro1, allegro2,allegro3 itp.
Na zasobie https://allegro.pl/auth/oauth/token  bez problemu mogę pobrać sobie jednocześnie tokeny.
Gdy jestem wylogowany z wszystkich kont allegro i chce zaktualizować ceny i stany allegro zwraca mi błąd autoryzacji niezależnie od konta. Ale gdy się już zaloguje np na allegro1 na chrome to tylko dla tego konta mogę pobrać np zamówienia/ aktualizacje cen(cały czas ten sam token). To samo tyczy się pozostałych kont. 
Jest jakiś sposób abym mógł jednocześnie na wszystkich kontach aktualizować ceny stany posiadając tokeny i nie będąc zalogowanym? 

Używam OAuth grant-type: authorization_code  czy moze OAuth grant-type: device_code rozwiąze moj problem?

**Comment by AureliuszBrussy** [comment]
Czy masz pewność, że np. próbujesz zaktualizować ceny korzystając z access tokena użytkownika, który jest właścicielem danej oferty? Czy access tokeny są na pewno aktualne (nie minęło 12 godzin od ich wygenerowania)? 

Kwestia aktualnego zalogowania do kont na jakimś urządzeniu nie ma tutaj nic do rzeczy.

Dodam, że nie odnotowaliśmy aktualnie żadnych problemów z procesem autoryzacji i uwierzytelniania. Wygląda na jakiś błąd w Twojej implementacji. Zmiana typu autoryzacji nic tutaj nie da.

**Comment by SzymonZasada** [comment]
Tak jestem pewien, ponieważ ten sam błąd mam nawet na pobraniu ofert. Jest tak niezalenie czy tokenu używałem 10h czy może wygenerowałem sobie nowego.  Wszystko sprawdziłem dwa razy.
Dodam że używam do tego nodejs(express) na backendzie oraz Angualra 15 na FE(ale to nie ma nic do rzeczy)

**Comment by SzymonZasada** [comment]
A wiec tak, chce w nocy odpalić update wsumie 80tys aukcji na koncie allegro1 i 50tys aukcji na koncie allegro2.
Dla każdego konta mam już wygenerowany(nowy) osoby token i refreshToken.
Chce zacząć od update konta allegro1 - ale w miedzy czasie jestem zalogowany na konto allegro2 na chrome i dostaje taki o to bład- not authorized w response ale gdy przeloguje się na konto allegro1 nagle zaczyna wszystko dobrze działać

Oczywiście że pomijam ze co chwile dostaje takie komunikaty
![image](https://github.com/allegro/allegro-api/assets/84040786/d9b17b6d-63dc-465f-8ff9-c1f0ecda69af)

**Comment by AureliuszBrussy** [comment]
Przekazałem tą blokadę do weryfikacji. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Miałeś uruchomione tzw. dev tools w przeglądarce, co spowodowało blokadę. Wystarczy, że je zamkniesz i nie użyjesz na Allegro, a blokada nie powinna występować.
