### ISSUE TITLE
About the difference between offer name and product name

### ISSUE THREAD

**Issue by Ruiky** [allegro/allegro-api#8032]
Hello, when we create a product, we assign the same value to the name of the offer as the name of the product, but the product name is not the same. What is the reason for this? Thank you.

![image](https://github.com/allegro/allegro-api/assets/3361159/aa39069e-845a-4097-a0b4-2015f6720c91)
![image](https://github.com/allegro/allegro-api/assets/3361159/0574c8e1-e523-4616-b857-9be21a903b40)

Request parameters:
![image](https://github.com/allegro/allegro-api/assets/3361159/3909b9b4-46b0-49d9-a6ed-3455253ed581)

![image](https://github.com/allegro/allegro-api/assets/3361159/9786e86f-7bd1-42cd-839f-87727c514685)

{"afterSalesServices":{"impliedWarranty":{"id":"25bbbae7-d5b8-48fd-b0f2-41790ba5e099"},"returnPolicy":{"id":"7e7f540f-47b0-440b-845f-386f7d4a5297"}},"category":{"id":"256928"},"delivery":{"handlingTime":"P14D","shipmentDate":"2023-11-23T08:58:59+08:00","shippingRates":{"id":"631f07a3-53e0-4781-8b8e-ee8698e65ba1"}},"description":{"sections":[{"items":[{"type":"TEXT","content":"<ul><li><p>Nazwa marki:NoEnName_Null</p></li><li><p>Pochodzenie:CN (pochodzenie)</p></li><li><p>CN:Fujian</p></li><li><p>Sugerujący seksualność:Nie</p></li><li><p>Figi i bokserki:Bokserki</p></li><li><p>Obsceniczne zdjęcie:Nie</p></li><li><p>Materiał:COTTON</p></li><li><p>Płeć:MEN</p></li><li><p>Typ wzoru:Stałe</p></li></ul>"}]}]},"external":{"id":"a1005004224162584"},"images":["https://a.allegroimg.com/original/11ecef/dbb16c4442d3bd3f64db7960ce1e","https://a.allegroimg.com/original/116fdf/1ba06785443eae7663ac1f22db26","https://a.allegroimg.com/original/118618/d01dd14c4c0c86c0ba9a8fd70125","https://a.allegroimg.com/original/11e739/400da8c34e258f45703c0ac24d2b","https://a.allegroimg.com/original/113577/9c02b4074517a4482e6ad54e272a"],"location":{"city":"shanghangxian","countryCode":"CN","postCode":"364200"},"name":"Bielizna męska bokserki bawełniane oddychające modne spodenki","parameters":[],"payments":{"invoice":"NO_INVOICE"},"promotion":{"bold":false,"departmentPage":false,"emphasized":false,"emphasizedHighlightBoldPackage":false,"highlight":false},"publication":{"status":"ACTIVE","republish":false},"sellingMode":{"format":"BUY_NOW","price":{"amount":"1125.00","currency":"PLN"}},"sizeTable":{},"stock":{"available":100,"unit":"UNIT"},"b2b":{"buyableOnlyByBusiness":false},"language":"pl-PL","productSet":[{"product":{"category":{"id":"256928"},"images":["https://a.allegroimg.com/original/11ecef/dbb16c4442d3bd3f64db7960ce1e","https://a.allegroimg.com/original/116fdf/1ba06785443eae7663ac1f22db26","https://a.allegroimg.com/original/118618/d01dd14c4c0c86c0ba9a8fd70125","https://a.allegroimg.com/original/11e739/400da8c34e258f45703c0ac24d2b","https://a.allegroimg.com/original/113577/9c02b4074517a4482e6ad54e272a"],"name":"Bielizna męska bokserki bawełniane oddychające modne spodenki","parameters":[{"id":"15851","valuesIds":["15851_2"]},{"id":"3946","valuesIds":["3946_1736245"]},{"id":"249513","valuesIds":["249513_1647430"]},{"id":"249516","valuesIds":["249516_1647636"]},{"id":"16099","valuesIds":["16099_1"]},{"id":"203929","valuesIds":["203929_218433"]},{"id":"3766","valuesIds":["3766_14"]},{"id":"201017","valuesIds":["201017_2357"]},{"id":"225693","values":["6906788356664"]},{"id":"216925","valuesIds":["216925_275833"]},{"id":"249512","valuesIds":["249512_1647414"]},{"id":"54","valuesIds":["3806_16"]}]}}]}

Please help me analyze the reason, thank you.

**Comment by AureliuszBrussy** [comment]
On the offer page, in some categories, we present a name generated by us based on the parameters of the offer. This is not an error. In the listing itself, we present the offer name that the vendor has defined.

**Comment by Ruiky** [comment]
Hello, just to ask, we would like to customize product variations such as color and size. Is this supported? Currently, the color and size must match the platform’s dictionary.

**Comment by AureliuszBrussy** [comment]
A product can have many variants. We even combine different variants of the same product ourselves, which you can read about [here](https://allegro.pl/dla-sprzedajacych/czym-sa-warianty-produktowe-4RKPG2ZgnFX).  But the topic raised by you is quite broad, so I don't know exactly what you mean specifically. 

Is it about passing, when creating an offer or product, custom values that are not defined in the value dictionary? Such possibility depends on whether we provide the possibility to add a custom value in a parameter. You can read more in [our guide](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#custom-parameter-values). 

Or is it a matter of connecting offers into multi-variant? You can read about that in our [other guide](https://developer.allegro.pl/tutorials/how-to-create-a-multi-variant-offer-nn9DOL3nXs2).

**Comment by Ruiky** [comment]
Hello, when we were launching the product, we were prompted with an EAN error, but the EAN we provided was correct. We try to make adjustments and the EAN code can be released successfully according to the prompts. Please tell us the reason:
Invalid EAN/ISBN/ISSN (225693) parameter value for the product in offer. Valid product parameter value is: "6908420314810".

The original EAN: 6908420314797 was adjusted to 6908420314810 and it can be released successfully. I don’t know the reason.

**Comment by AureliuszBrussy** [comment]
Please send the trace-id of your request, where we returned this error message in the response. You can find the trace-id in the header of our response. Then I will be able to check exactly what happened.

**Comment by Ruiky** [comment]
{
    "errors": [
        {
            "code": "ProductConstraintViolationException.DataIntegrity",
            "message": "Invalid EAN/ISBN/ISSN (225693) parameter value for the product in offer. Valid product parameter value is: "6908420314810".",
            "userMessage": "Niepoprawna wartość parametru EAN/ISBN/ISSN (225693) dla produktu w ofercie. Prawidłowa wartość parametru dla produktu to: "6908420314810"."
        }
    ]
}

**Comment by Ruiky** [comment]
> From this error message, it appears that we have a different EAN for the indicated product id (or found by us based on passed identifying parameters) in our Product Catalog. You should pass the EAN that we suggest in response. It's hard for me to say anything more here - I would need the trace-id that we return in the response header.

OK Thank you for your reply, we will continue to follow up and provide as much valuable information as possible
