### ISSUE TITLE
Categories where no EAN/ISBN/UPC/MPN is needed

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#8033]
Hello, 

we know, that there are some categories where no EAN/ISBN/UPC/MPN is needed. Is it possible to somehow retrieve the list of categories, where this information is not mandatory? 

An additional question from my side: how does the productization work in this case? Or it does not work in these categories at all and each offer published has to create it's own product card? 

Thank you in advance for your help.

All the best, 

Dominika

**Comment by MaciejFrackowiak** [comment]
No, there is no list with such categories. For example, in the category 110911 parameter "EAN (GTIN)" is not required. EAN/GTIN is one of the parameters which is required in most categories, but for some of them, it is not needed to create a product. Also, we have categories where you do not have to assign the product to an offer.
