### ISSUE TITLE
 GET /sale/product-offers/{offerId}

### ISSUE THREAD

**Issue by randomWro** [allegro/allegro-api#8034]
Dane dostępne w starym endpoincie odnośnie dostępnych promocji różnią się od ww., czy zostaną dodane brakujące informacje?

![obraz](https://github.com/allegro/allegro-api/assets/141820933/ef6199c9-6bf5-4dee-8f67-fc7f53621926)

**Comment by MaciejFrackowiak** [comment]
Nie, te informacje nie zostaną dodane do endpointów /sale/product-offers. Od kilku miesięcy prowadzimy w tej materii akcję informacyjną - ostatnie posty #7714, #7917.

**Comment by randomWro** [comment]
Dziękuję
