### ISSUE TITLE
Edit offer - validation error: description change which will not change translation

### ISSUE THREAD

**Issue by BarnetMichal** [allegro/allegro-api#8035]
Hello

I`m getting this validation error on my sandbox account michal.b@koongo.com when calling Edit an offer endpoint {"errors":[{"code":"VALIDATION_ERROR","message":"Invalid HTML subset","details":"Invalid value: description change which will not change translation XXX","path":"description.sections[0].items[0].content","userMessage":"Invalid HTML subset"}]} in https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/7730730275

Can you please advise me on how to fix it? Thank you.

**Comment by MaciejFrackowiak** [comment]
Unfortunately, I found your request in our logs but without a description section - please, paste it here in a thread.
