### ISSUE TITLE
Czy istnieje możliwość zaciągnięcia bannerów sprzedawcy?

### ISSUE THREAD

**Issue by jtrznadel** [allegro/allegro-api#8039]
Witam,

będąc studentem poszukującym okazji do rozwinięcia umiejętności programistycznych, natrafiłem w  obecnej pracy na ciekawą propozycję stworzenia prostego projektu.

Projekt ten zakłada m. in. zaciąganie bannerów ze sklepów sprzedawców. Mam dostęp do API Allegro, ale mam pewne pytanie dotyczące jego możliwości. Czy jest możliwość pobierania aktualnie zamieszczonych bannerów na sklepie sprzedawcy? Niestety nie mogę znaleźć rozwiązania takowego problemu w dokumentacji API. Chodzi mi oczywiście o bannery zamieszczane w sekcji poniżej:

![obraz_2023-11-23_131957096](https://github.com/allegro/allegro-api/assets/92259524/41857040-c7db-46c0-ad6a-c063a740a849)

Będę wdzięczny za wszelkie informacje i wskazówki dotyczące korzystania z API Allegro oraz wszelkich sugestii dotyczących projektu.

Pozdrawiam!

**Comment by MartaNowaczyk** [comment]
Witaj! Niestety od strony zasobów naszego publicznego API nie będę mogła Ci pomóc, bo nie ma takiej możliwości.
Jeśli masz jakieś konkretne pytania dotyczące Allegro API, pytaj śmiało.
Pozdrawiam!
