### ISSUE TITLE
OfferRepository error podczas wznawiana oferty

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#804]
Witam,

wznawiałem własnie ponad 1k ofert, część przeszła, część nie.
jedna z problematycznych:

PUT sale/offer-publication-commands/d9fd4735-c275-4117-b128-39540a2246cf
request:
`{"publication":{"action":"ACTIVATE"},"offerCriteria":[{"offers":[{"id":"7508925112"}],"type":"CONTAINS_OFFERS"}]}`
response:
`{"id":"d9fd4735-c275-4117-b128-39540a2246cf","taskCount":{"total":0,"success":0,"failed":0}}`

GET sale/offer-publication-commands/d9fd4735-c275-4117-b128-39540a2246cf/tasks
```
                    [offer] => stdClass Object
                        (
                            [id] => 7508925112
                        )
                    [message] => OfferRepository error
                    [status] => FAIL
                    [scheduledAt] => 2018-10-22T15:21:16.304+02:00
                    [finishedAt] => 2018-10-22T15:21:28.715+02:00
                    [field] => publication
```

Podczas edycji via formularz dostaje:
`Podczas wznowienia oferty wystąpiły błędy
Oferta nie może zostać wznowiona, ponieważ jest w trakcie kończenia. Poczekaj chwilę i spróbuj ponownie.`

Dodam, że oferty ostatni raz były startowane/stopowane pod koniec zeszłego tygodnia i już wtedy pojawiały jakieś problemy z ofertami. Przez api przechodziły ale ich wznawianie trwało po kilkanaście godzin.

**Comment by PawelTaberski** [comment]
Hej widzę, że dwa razy założyłeś taki sam ticket pod numerem #803 tam zostawiłem Tobie informacje. Ten ticket zamykam. Dziś są jakieś duże opóźnienia na GitHub-ie to pewnie przez to, założyłeś dwu-krotnie.
