### ISSUE TITLE
Nie mogę uzyskać access token

### ISSUE THREAD

**Issue by FreeWie** [allegro/allegro-api#8040]
Aplikację stworzyłem z konta Allegro. CLIENT_ID i CLIENT_SeCRET mam. Używam aplikacji ze strony https://developer.allegro.pl/tutorials/jak-zaczac-prace-z-rest-api-4RAvV2bgwtj#python w celu uzyskania Access Token. Aplikacja zwraca błąd. Chyba jest problem z autoryzacją.

**Comment by AureliuszBrussy** [comment]
Nie odnotowujemy żadnych ogólnych problemów z autoryzacją. Upewnij się, czy próbujesz wygenerować access token dla właściwego środowiska (na sandbox czy na produkcję?). Sprawdź sobie także przykłady z poradnika dedykowanego [autoryzacji i uwierzytelnianiu](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR).

**Comment by FreeWie** [comment]
Chyba problem leży w tym, że chcę wygenerować access token dla sandbox ale aplikację tworzyłem na koncie produkcyjnym. Zupełnie nie potrafię (nie znam adresu) utworzyć aplikacji na koncie sandbox. Na https://apps.developer.allegro.pl mogę zalogować się tylko z konta produkcyjnego. Proszę o informację jak utworzyć aplikację dla konta sandbox.

**Comment by AureliuszBrussy** [comment]
Utworzyć aplikację dla środowiska testowego możesz [TUTAJ](https://apps.developer.allegro.pl.allegrosandbox.pl/).

**Comment by FreeWie** [comment]
OK. Dziękuję. Mam jednak kolejny problem. Nie mogę aktywować konta na sandbox, gdyż przy próbie przelewu (fikcyjnego - rozumiem), wyświetla się błąd: "Nie można znaleść serwera http://c2c-payu-simulator.dh-test.qxlint"
Może da się inaczej aktywować konto? Client:106756730 email: wiesiek.w@gmail.com

**Comment by AureliuszBrussy** [comment]
Spróbuj proszę wykonać pierwszy zakup - powinno udać się podczas tego procesu aktywować konto. Jeżeli wciąż napotkasz problem - daj znać. 

Dodam tylko, że zarejestrowałeś konto zwykłe. Jeżeli chcesz testować publiczne API w pełni - zarejestruj nowe [konto firma](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F).

**Comment by FreeWie** [comment]
Niestety nadal nie mogę sobie poradzić. Dokonałem zakupu, ale konto nadal nie jest aktywowane. 
Z kolei przy próbie zmiany na konto firmowe nie przepuszcza mnie pozycja formularza Dane użytkownika - Login - nie przyjmuje żadnego loginu.

**Comment by AureliuszBrussy** [comment]
@FreeWie najlepiej, jak zarejestrujesz po prostu nowe konto firmowe na inny adres e-mail. Co do weryfikacji - spróbuj wybrać inną metodę przelewu.

**Comment by Rzexnik** [comment]
@FreeWie 
Hej!
Też jestem totalnie zielony. Udało Ci się poradzić ze swoim problemem?

**Comment by AureliuszBrussy** [comment]
@FreeWie aktywowałem Twoje konto.
