### ISSUE TITLE
JsonMappingException: Request contains invalid data.

### ISSUE THREAD

**Issue by cemsgh** [allegro/allegro-api#8041]
Uruchamiam obsługę /sale/product-offers
Jakbym nie modyfikował treści requestu otrzymuję odpowiedź:
{"errors":[{"code":"JsonMappingException","message":"Message is not readable.","details":null,"path":"productSet","userMessage":"Request contains invalid data. Contact the application author."}]}
Jeden z requestów trace-id: f0293bde01b94a08.
Czy jest możliwe uzyskanie bardziej szczegółowej informacji co jest nie tak?

**Comment by AureliuszBrussy** [comment]
Z naszych logów wynika, że payload jest "urwany" - nie otrzymaliśmy go w całości w tym przykładowym requeście. Dodatkowo widzę, że wysyłasz tablicę `productSet` bez zagnieżdzenia w nim obiektu `product`. 

Upewnij się, czy wysyłasz payload w całości. Przenalizuj dokumentację dokładnie, tak aby mieć pewność, że wysyłana struktura jest prawidłowa. 

Jeżeli nie będziesz miał pomysłu - podeślij proszę tutaj w wątku cały curl (z pełnym payload'em), który wysyłasz.
