### ISSUE TITLE
sale/categories brak zwracanych podkategorii

### ISSUE THREAD

**Issue by cyfranT** [allegro/allegro-api#8042]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Zasób sale/categories zwraca pustą listę podkategorii dla parent.id = 111777  (Podręczniki do szkoły średniej - liceum i technikum)
Trace id: 1653d2620e2e5c57

**Comment by MaciejFrackowiak** [comment]
Jest to prawidłowe zachowanie - odpytując [GET /sale/categories/{categoryId}](https://developer.allegro.pl/documentation/#operation/getCategoryUsingGET_1) otrzymujemy informacje:
```
{
    "id": "111777",
    "name": "Szkoła średnia",
    "parent": {
        "id": "66820"
    },
    "leaf": true,
    "options": {
        "variantsByColorPatternAllowed": true,
        "advertisement": false,
        "advertisementPriceOptional": false,
        "offersWithProductPublicationEnabled": true,
        "productCreationEnabled": true,
        "customParametersEnabled": true,
        "sellerCanRequirePurchaseComments": false
    }
}
```
Kategoria 111777 jest liściem, nie ma pod sobą podkategorii.

**Comment by cyfranT** [comment]
Ok, faktycznie podkategorie wyświetlane w portalu pochodzą z parametrów.. Dzięki za odpowiedź!
