### ISSUE TITLE
Niepoprawna wartość sumy kosztów dla konta

### ISSUE THREAD

**Issue by z4nr34l** [allegro/allegro-api#8043]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

Sumaryczna wartość kosztów zwracana z endpointa `GET /billing/billing-entries` nie zgadza się z wartością w panelu konta allegro.

_Szczegółowa odpowiedź serwera, kwoty oraz zrzuty zostaną podane w zgłoszeniu formularza ze względu na zawartość informacji handlowych._

**Ścieżka reprodukcji**:

1. Pobranie pełnej historii konta do bazy danych;
2. Pobranie sumy kosztów za ten sam okres z bazy danych oraz panelu;
3. Obie wartości nie są równe (Nawet po wykluczeniu zwrotów itd.);

**Comment by MartaNowaczyk** [comment]
Jak tylko otrzymam przesłane przez Ciebie informacje, zweryfikuję to i wrócę z odpowiedzią.

**Comment by z4nr34l** [comment]
Zgłoszenie zostało właśnie wysłane z konta, na którym występuje problem.

**Comment by MartaNowaczyk** [comment]
Dziękuję za informacje.

**Comment by MartaNowaczyk** [comment]
Dziś otrzymałam zrzut. Jak tylko uda nam się zweryfikować te dane, wrócę z informacją.

**Comment by z4nr34l** [comment]
Ok, czy pojawiły się już jakieś informacje w tej kwestii?

**Comment by z4nr34l** [comment]
Czy w takim wypadku będziecie w stanie przygotować listę kategorii, która do czego ma być wliczana?

Niebawem wrzucimy taką sugestię na dyskusjach.

**Comment by MartaNowaczyk** [comment]
Już o to pytałam i dostałam tylko takie wytyczne - listy nie mamy. U nas to dwa oddzielne byty - czyli tak jak pisałam, Koszty nie są 1 do 1 z Historią operacji na koncie.
