### ISSUE TITLE
Problem z uzyskaniem tokena dostępowego dla konta sandbox

### ISSUE THREAD

**Issue by tomsyty** [allegro/allegro-api#8045]
Od dłuższego już czasu mam problem z uzyskaniem tokena dostępowego dla aplikacji typu rozszerzenie do przeglądarki Chrome. Problem trwa gdzieś od roku, radzę sobie jakoś niestety testując aplikacje na produkcji, ale chciałbym w końcu uporać się z tym problemem tylko nie mam pojęcia jak. Jest to albo kwestia zmian w nowszej wersji Chrome albo ustawień po stronie Allegro, bo dawniej nie miałem takiego problemu, miałem rozszerzenie które działało normalnie, po dłuższej przerwie w jego używaniu już nie udało mi się pobrać tokena mimo iż nic nie zmieniałem w kodzie. Wypróbowałem już mnóstwo możliwości i chyba znalazłem przyczynę, jednak nie wiem jak ją obejść. 

Problem jest taki że niezależnie od metody autoryzacji (Code Flow czy Device Flow) pomimo uzyskania kodu nie mogę uzyskać za jego pomocą tokena. Za logowanie na produkcję i sandboxa odpowiada ten sam fragment kodu, podstawiane są jedynie do zmiennych inne Client ID / Client Secret (i Redirect Uri w przypadku Code Flow) i dodawany lub nie do adresu wywołania jest człon ".allegrosandbox.pl". Dla produkcji wszystko działa, dla sandboxa cały czas otrzymuję błąd 403. Porównałem nagłówki w Chrome Devtools i w Postmanie i wychodzi na to że Chrome nie wysyła nagłówka "HOST", w Postmanie gdy nie dołączę tego nagłówka to również otrzymuję 403, w response zwracane są m.in. "<html><head><title>You have been blocked</title><style>(...) Please enable JS and disable any ad blocker (...) 'host':'geo.captcha-delivery.com'" tak jakby dla mojego konta nałożona była jakaś blokada wymagająca rozwiązania captcha, choć wchodząc na stronę allegro.pl.allegrosandbox.pl loguję się normalnie na konto. Nie wiem dlaczego brak nagłówka HOST nie jest problemem dla produkcji, a dla sandboxa już jest.

Czy ktoś z Was pisze również rozszerzenia do Chrome i ma problemy z logowaniem na sandboxa? A jeśli nie ma to może jakieś porady jak wygląda u Was przykładowe logowanie?

**Comment by MaciejFrackowiak** [comment]
A jaki adres wywołań dla Sandbox podajesz? Prawidłowa ścieżka to https://api.allegro.pl.allegrosandbox.pl/

**Comment by tomsyty** [comment]
Taki jest dla wywołań zasobów jak ma się już token dostępowy, ale dla logowania żeby uzyskać token jest https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=...

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak i zapewnia on uzyskanie tokena na Sandbox. Problem wydaje się być na linii rozszerzenie, którego używasz w Chrome - tu mam nadzieję, że jakiś z użytkowników będzie mógł Tobie udzielić wskazówek.
