### ISSUE TITLE
Problem z potwierdzeniem danych na allegro sandbox

### ISSUE THREAD

**Issue by MGabala** [allegro/allegro-api#8046]
Po kliknięciu w "Potwierdź dane":

![obraz](https://github.com/allegro/allegro-api/assets/82496006/465c8079-e8fc-40fa-8d6b-d9020cceade7)
wybieram formę płatności:

![obraz](https://github.com/allegro/allegro-api/assets/82496006/0a9dbcf4-ae11-442f-81f5-9527eaa9fddf)
ale wtedy niestety mam taki błąd:

![obraz](https://github.com/allegro/allegro-api/assets/82496006/996a43fd-cf98-4a5e-9513-44aaf72643c9)

Również po kliknięciu w:

![obraz](https://github.com/allegro/allegro-api/assets/82496006/0c23866e-9935-4f05-ab68-1622571da2ea)

dostaję taki błąd:

![obraz](https://github.com/allegro/allegro-api/assets/82496006/ca9ce0e2-49fb-48d7-8d40-513b3f3c8756)

Proszę o informację czy aby korzystać z wystawiania ofert na allegrosandbox muszę weryfikować swoje konto? Czy poprzez API przejdzie wystawienie oferty mimo braku weryfikacji?

**Comment by MaciejFrackowiak** [comment]
Tak, Twoje konto musi zostać zweryfikowane jako firmowe byś mógł wystawiać oferty przez API. Co istotne, rejestrując konto na Sandbox podaj proszę fikcyjne dane.
