### ISSUE TITLE
Device flow

### ISSUE THREAD

**Issue by edpol27** [allegro/allegro-api#8048]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by MaciejFrackowiak** [comment]
Wyjaśnienie w ramach https://github.com/allegro/allegro-api/issues/8049.
