### ISSUE TITLE
Dodatkowy parametr wyszukiwania w kategorii Elektronika, dokument sprzedaży

### ISSUE THREAD

**Issue by piotrlabak** [allegro/allegro-api#805]
Proszę o dodanie parametru wyszukiwania w kategorii Elektronika (w innych kategoriach pewnie też się przyda) - dokument sprzedaży. Obecnie można wyszukać po fakturze VAT, ale rezultaty są bardzo mylące ponieważ pokazują się wyniki zarówno dla faktury VAT jak i faktury VAT-marża. Myślę, że dla wielu użytkowników jest to bardzo istotna informacja, że na zakupiony towar wystawiona jest pełna faktura 23%.

**Comment by PawelTaberski** [comment]
Dziękuję za Twoją sugestię przekazałem ją do odpowiedniego zespołu. Jeśli wdrożymy takie rozwiązanie poinformujemy o tym osobnym komunikacie.
