### ISSUE TITLE
Zaciąganie aktualnych produktów z aukcji klienta

### ISSUE THREAD

**Issue by purkos** [allegro/allegro-api#8050]
Witam, dostałem propozycje stworzenia strony z produktami które sprzedaje klient na allegro, zamiast robic oddzielne dodawanie produktow na stronie ktore sa aktywne na aukcji allegro, chcialbym by te przedmioty byly zaciagane z aukcji klienta i wyswietlane na stronie wraz z linkiem do przedmiout, oraz po zmianie np: ceny na aukcji automatycznie zmieniala sie takze na stronie, czy jest mozliwosc skonfigurowania takiej opcji?
Z góry dziekuje za odpowiedz

**Comment by MaciejFrackowiak** [comment]
Zgodnie z [Regulaminem REST API Allegro](https://developer.allegro.pl/rules) prezentowanie ofert Allegro w innych serwisach jest zabronione.

**Comment by purkos** [comment]
Nawet jesli ta strona sluzy tylko do tego by przedstawiac aktualne przedmioty sprzedawane przez klienta tylko w allegro oraz przekierowywujaca prosto do sprzedazy tego produktu na allegro?

**Comment by MaciejFrackowiak** [comment]
Ten sam efekt - to jest prezentację ofert danego sprzedającego odniesiesz linkując bezpośrednio do ofert na jego koncie np. https://allegro.pl/uzytkownik/{login}. W tym momencie nie będzie wątpliwości, gdzie prowadzona jest sprzedaż.
