### ISSUE TITLE
unsuccessful attempts to add products and update product date

### ISSUE THREAD

**Issue by mathiasdeknudt** [allegro/allegro-api#8051]
Dear,

Our marketplace integrator (EffectConnect) is trying to sync products and product content to our Allegro account. Unfortunately their attempts are unsuccessful. We were wondering if you could help us with below questions?
 
1) Can you help check if all the necessary settings in the Allegro platform are set correctly, to be able to do this?

2) Can you 'see' these attempts on your side? Can we somewhere see these attempts in the Allgro platform?

3) In the Allegro platform, can we see when a product was last updated?
 
Thank you in advance.
 
------------
 
Nasz integrator marketplace (EffectConnect) próbuje zsynchronizować produkty i ich zawartość z naszym kontem Allegro. Niestety ich próby są bezskuteczne. Zastanawialiśmy się, czy mógłbyś nam pomóc z poniższymi pytaniami?
 
1) Czy mogą Państwo pomóc w sprawdzeniu, czy wszystkie niezbędne ustawienia na platformie Allegro są prawidłowo skonfigurowane, aby móc to zrobić?

2) Czy możesz "zobaczyć" te próby po swojej stronie? Czy możemy gdzieś zobaczyć te próby na platformie Allgro?

3) Czy na platformie Allegro możemy zobaczyć, kiedy produkt był ostatnio aktualizowany?
 
Z góry dziękuję.

**Comment by MaciejFrackowiak** [comment]
In response to your questions:
1. I'm unable to do this because this is not related directly to the Allegro API. Also, without any specific log, we are not able to say whether something is OK or not.
2. Maybe, but without a detailed log from the integrator we cannot do this.
3. You can check if the offer is active on the platform - it should be available in the [My assortment tab](https://allegro.pl/moje-allegro/sprzedaz/obsluga-ofert/moj-asortyment?limit=20&publication.status=ACTIVE&sellingMode.format=BUY_NOW&publication.marketplace=allegro-pl).

**Comment by mathiasdeknudt** [comment]
Dear,

First of all thank you for your feedback.

1. When our integrator pushes new data, will the data be automatically updated in the platform? Or does new data need to be approved by an Allegro Information management team first?
2. OK
3. We have added the products manually, but would like to check/follow-up whether our integrator successfully updated the data, hence a 'last update on date' would be helpful.

4. Could you please send me a link with more information regarding importing products by flat files?

Thank you in advance

**Comment by MaciejFrackowiak** [comment]
Data connected to offers should be updated automatically. Some changes to existing products need to be approved by Allegro employees.  
The last update date is only available in the API directly.
Flat files are not connected with API Allegro, but you can read more about it [here](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-ofert-z-pliku).
