### ISSUE TITLE
Błąd 415 podczas requestu `PUT` `/bidding/offers/{offerId}/bid`

### ISSUE THREAD

**Issue by Miro0** [allegro/allegro-api#8052]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

**Opis / Description**
Poniższe zapytanie z wykorzystaniem API `fetch` w JavaScript zwraca mi kod błędu `415` - niestety nie mogę dojść do jego przyczyny:
```js
await fetch(`https://api.allegro.pl/bidding/offers/${offerId}/bid`, {
  method: 'PUT',
  headers: {
    Accept: 'application/vnd.allegro.public.v1+json',
    Authorization: `Bearer ${user_access_token}`,
    ContentType: 'application/vnd.allegro.public.v1+json',
  },
  body: JSON.stringify({
      maxAmount: {
        amount: amount,
        currency: 'PLN',
      },
    })
});
```

`offerId` - jest ID aktywnej licytacji
`user_access_token` - jest poprawnym `access_token`em użytkownika
`amount` - w teście występuje kwota poniżej obecnej kwoty do licytacji i jest to wartość `integer`

Czy wartość `amount` poniżej kwoty licytacj lub jej typ `integer` może powodować ten błąd `415` czy błąd leży gdzie indziej (w wysyłanych `header`ach przykładowo)?

**Comment by Miro0** [comment]
@MaciejFrackowiak Skąd mogę wyciągnąć trace-id?

Teraz jeszcze widzę dodatkowe informacje dotyczące zwróconego błędu:
```
code: "NotSupportedException"
message: "Unsupported content type. Please check 'Content-Type' request header"
userMessage: "Request contains invalid data. Contact the application author."
```

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przykład. Problemy są dwa:
1. Wywołanie wymaga nagłówka Content-Type w postaci "application/vnd.allegro.public.v1+json" - Ty przekazałeś "text/plain;charset=UTF-8";
2. Zasób wymaga autoryzacji "bearer-token-for-user", natomiast Twój request nie posiada kontekstu użytkownika, czyli najpewniej skorzystałeś z autoryzacji client_credentials.

**Comment by Miro0** [comment]
@MaciejFrackowiak Dziękuję za pomoc. `1.` okazała się prawdziwa - była literówka w headerze `ContentType` vs `'Content-Type'`. Teraz mam już prawidłowy błąd `Kwota, którą oferujesz, jest zbyt niska.`, która odzwierciedla faktyczny stan rzeczy.

Dziękuję za pomoc
