### ISSUE TITLE
AccessDenied

### ISSUE THREAD

**Issue by kamilsu** [allegro/allegro-api#8053]
Hej
Próbuje przejść z /parcel-management/delivery-services na /shipment-management/delivery-services
Niestety na tym samym tokenie stara metoda działa, nowa nie. 

KOMUNIKAT
 [errors] => Array
        (
            [0] => Array
                (
                    [code] => AccessDenied
                    [message] => Access is denied
                    [details] => 
                    [path] => 
                    [userMessage] => No access to the specified resource.
                )

        )

Dodałe scope uprawnienia dla tego aplikacji (minęło już z 6h) nadal nie działa (jak wejdziemy w edycje aplikacji to uprawnienia są nadane)

Zarządzanie przesyłkami

    allegro:api:shipments:read
    Odczyt przesyłek, etykiet i protokołów
    allegro:api:shipments:write
    Zarządzanie przesyłkami

Kilkukrotnie odświeżałem token nadal nic. 

trace-id: 44822c402e62a85

Proszę o pomoc w nakierowaniu co jest nie tak.

**Comment by MaciejFrackowiak** [comment]
Musisz przejść proces autentyfikacji od początku tj. wygenerować nowy access token bez użycia refresh tokena. Samo odświeżanie powoduje zachowanie dotychczasowych scope'ów, bez uwzględnienia wprowadzonej przez Ciebie zmiany.

**Comment by kamilsu** [comment]
Ok dziękuje. Problem rozwiązany. 

Przy okazji warto poprawić dokumentację na stronie https://developer.allegro.pl/tutorials/najwazniejsze-procesy-allegro-w-pigulce-lLAZ8eOP0SP

Zarządzanie przesyłkami przez Wysyłam z Allegro prowadzi do opisu /parcel-management/ który jest już oznaczony jako Deprecated

**Comment by MaciejFrackowiak** [comment]
Cieszę się, iż problem rozwiązany. Jednocześnie dziękuję za zwrócenie uwagi - będziemy aktualizować opis.
