### ISSUE TITLE
Blad w parametrze 

### ISSUE THREAD

**Issue by Dowjones797** [allegro/allegro-api#8055]
Dobry dzień,

mamy problem, w którym interfejs API zwraca błąd w pojedynczym parametrze. Uważam jednak, że wypełniliśmy go poprawnie. W logu widzimy błąd w parametrze: „Parametr Typ nie pozwala na wartości niestandardowe”
Jednak dla produktu EAN: 8590880833543 wysyłamy ten parametr jako parametr 248198_865747 (stolik kawowy).

Czy możecie proszę sprawdzić? Dziękuję.

sprzedawca HELCEL

**Comment by AureliuszBrussy** [comment]
Żeby to dokładnie sprawdzić, potrzebowałbym trace-id wywołania, gdzie zwróciliśmy taki komunikat błędu. Trace-id znajdziesz w nagłówku naszego response'a.

**Comment by AureliuszBrussy** [comment]
Spróbuj pominąć próbę przekazania wartości w tablicy `values` oraz `valuesLabels` dla tego parametru (id 248198, "Typ"), pozostaw tylko `valuesIds`.
