### ISSUE TITLE
Blokowanie podczas autoryzacji OAuth

### ISSUE THREAD

**Issue by XardasLord** [allegro/allegro-api#8056]
Notorycznie jestem blokowany przez Wasze systemy podczas autoryzacji OAuth do allegro z użyciem Authorization Code Flow.
Ostatnie blokowanie nastąpiło o 9:10 (38.41.207.204)

**Comment by AureliuszBrussy** [comment]
Przekazałem to do weryfikacji. Wrócę z informacją.

**Comment by XardasLord** [comment]
Nie ukrywam, że jest to coś blokujące naszą pracę na produkcji

**Comment by AureliuszBrussy** [comment]
@XardasLord tak jak wspomniałem - wrócę z informacją od razu jak otrzymam wyniki analizy, proszę o jeszcze trochę cierpliwości.

**Comment by XardasLord** [comment]
@AureliuszBrussy Minęła ponad doba od zgłoszenia, czy można potraktować temat priorytetowo?

**Comment by AureliuszBrussy** [comment]
Proszę o jeszcze trochę cierpliwości - tak jak wspomniałem, wrócę z informacją jak tylko otrzymam wyniki analizy.

**Comment by AureliuszBrussy** [comment]
@XardasLord to nie była blokada, a Captcha - w naszej opinii pojawienie się jej jest uzasadnione w przypadku takiego ruchu.
