### ISSUE TITLE
Allegro sandbox - Bon dla nauczyciela - czas trwania programu

### ISSUE THREAD

**Issue by kaszryg** [allegro/allegro-api#8057]
Chcę przetestować na sandboxie, jak działa program Bon dla nauczyciela. 
Nie mogę jednak dodać żadnej oferty do programu Laptop dla nauczyciela ‑ test, możliwe że to przez czas trwania, który jest ustawiony w terminie 23 sie. - 31 paź. 2023
Można prosić o poprawkę w tym zakresie? 

Dodatkowe pytanie - idąc za wątkiem https://github.com/allegro/allegro-api/issues/7829 przy testowych zakupach prośba o potwierdzenie, czy
"Każda kombinacja z wykorzystaniem [0-9 A-F] generuje prawidłowy bon."

**Comment by kaszryg** [comment]
> Poprosiłbym jeszcze o numer oferty, którą chciałbyś dodać do programu.
Oferta nr: 7735150453

**Comment by AureliuszBrussy** [comment]
Oferta powinna być już odpowiednio oznaczona, więc możesz przeprowadzić testy.

**Comment by kaszryg** [comment]
Jest ok, mam możliwość płatności bonem, ale mam znów inny problem. Oferta jest w jakiejś kampanii promocyjnej L4T która podwyższa mi cenę do 2570zł https://prnt.sc/fyWQFcB0er4i a chciałbym jeszcze spróbować złożyć zamówienie testowe w 100% opłacone przez bon.

**Comment by AureliuszBrussy** [comment]
Na potrzeby testów skorzystać możemy tylko z kampanii L4T, której zarządzanie nie jest możliwe - możemy oznaczyć ofertę kampanią tylko manualnie. Zmieniliśmy cenę na 2350 zł - możesz przetestować wariant z płatnością całościową za pomocą bonu.

**Comment by kaszryg** [comment]
Chyba ostatnia kwestia - czy dane zamówienia w sekcji payment wyglądają tak samo na produkcji? - dotyczy zamówień opłaconych w pełni bonem dla nauczyciela. 

 "payment": {
    "id": "7f945cec-8ead-11ee-ba79-1388d729bb7a",
    **"type": "WIRE_TRANSFER",
    "provider": "OFFLINE",**
    "finishedAt": "2023-11-29T11:50:36.449Z",
    "paidAmount": null,
    "reconciliation": null

**Comment by AureliuszBrussy** [comment]
Tak, ta sekcja wygląda na produkcji tak samo.
