### ISSUE TITLE
Jaki jest limit liczby access tokenów?

### ISSUE THREAD

**Issue by kowalikus** [allegro/allegro-api#8058]
Na stronie pomocy dotyczącej tworzenia liczby access tokenów https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR jest informacja o limicie jednak jest brak konkretnej granicy po której błąd występuje.

> W Allegro REST API obowiązuje limit dla liczby access tokenów, które możesz wygenerować w określonym czasie dla jednego użytkownika. Jeżeli go przekroczysz, w odpowiedzi zwrócimy błąd HTTP: 429 Too Many Requests. Oznacza to, że działanie twojej aplikacji odbiega od normy - upewnij się, że nie tworzysz więcej tokenów niż wymagają tego operacje, które wykonujesz. Raz wygenerowany token dla jednego użytkownika powinien być używany aż do momentu wygaśnięcia, po tym czasie odśwież token za pomocą refresh tokena.

**Comment by MaciejFrackowiak** [comment]
Jest to celowy zapis, aby nie podawać tej liczby otwarcie z uwagi na zabezpieczenie przed nieautoryzowanymi próbami uzyskania dostępu.
