### ISSUE TITLE
ACTIVATE do INACTIVE

### ISSUE THREAD

**Issue by slawomir-kudla** [allegro/allegro-api#806]
Witam

Aktywacja oferty działa poprawnie

`curl -X PUT -H 'Accept: application/vnd.allegro.beta.v1+json;charset=UTF-8' -H 'Content-type: application/vnd.allegro.beta.v1+json' -H 'Authorization: Bearer eyJ' -H 'Accept-Language: PL' -d '{"publication":{"action":"ACTIVATE","scheduledFor":""},"offerCriteria":[{"offers":[{"id":"6205689243"}],"type":"CONTAINS_OFFERS"}]}' "https://api.allegro.pl.allegrosandbox.pl/sale/offer-publication-commands/185BC6FA-888C-40F7-B1A4-2D85B48D3898"`

niestety jak próbuję ustawić status INACTIVE to występuje błąd który nie ma w zasadzie treści

`curl -X PUT -H 'Accept: application/vnd.allegro.beta.v1+json;charset=UTF-8' -H 'Content-type: application/vnd.allegro.beta.v1+json' -H 'Authorization: Bearer eyJ' -H 'Accept-Language: PL' -d '{"publication":{"action":"INACTIVE","scheduledFor":""},"offerCriteria":[{"offers":[{"id":"6205689243"}],"type":"CONTAINS_OFFERS"}]}' "https://api.allegro.pl.allegrosandbox.pl/sale/offer-publication-commands/185BC6FA-888C-40F7-B1A4-2D85B48D3898"`

pytanie 2
Czy przy ustawieniu INACTIVE muszę podawać za każym razem ów 32 cyfrowy kod by tylko usunąć ofertę?

**Comment by slawomir-kudla** [comment]
[edit]
zamianst INACTIVE trzeba wstawić END

**Comment by PawelTaberski** [comment]
Tak jak powyżej napisał @slawomir-kudla, aby wstrzymac ofertę trzeba ustawić END. INACTIVE jest to draft i tylko wtedy oferta ma taki status. Więcej na temat aktywacji i wstrzymania oferty znajdziesz [tutaj](https://developer.allegro.pl/sale/#step-8-offer-publication-commands).

**Comment by rtnet-pl** [comment]
ps. kasujcie tokeny z wklejek
