### ISSUE TITLE
Offer translation issue

### ISSUE THREAD

**Issue by ivexgit** [allegro/allegro-api#8060]
Sorry if it is not the right place to report it here - I tried to find a different way to report the site's bug but failed.
I hope you can forward this to the appropriate department. 

The issue I want to talk about is with Allegro's multi-language support; precisely - the offer's title and the last part of the breadcrumbs chain are shown untranslated on the site.

The issue's description:

The product and the offer were created via REST API in en-US language. After a time, the translations have been automatically implemented (I've checked this by fetching them via REST API request "#{api_endpoint}/sale/offers/#{offer_id}/translations" - all are OK there). Then, I can find the offer via Allegro's search opened in the browser with pl-PL locale. At this step, all looks good - the title is shown in Polish, and the offer's URL consists of the appropriate words in Polish. But if we get to the offer itself, the main title and the last breadcrumb are shown in the initial language - in English. This is a significant bug not only for visitors but also for search engine indexing, but at the same time, I believe Allegro can fix it shortly.

![Illu](https://github.com/allegro/allegro-api/assets/50912125/f4d7378c-82af-4e1b-adc7-3000f3c9ce57)

**Comment by AureliuszBrussy** [comment]
I explain this with the product translation team. I will be back with an answer soon.

**Comment by AureliuszBrussy** [comment]
We are working to implement the fix. I will be back with an update once we deploy the change.
