### ISSUE TITLE
REST API dla stron firmowych partnerów

### ISSUE THREAD

**Issue by MrBoufigo** [allegro/allegro-api#8061]
Witam, przygotowuję projekt dla oficjalnego sklepu L'Oreal i mam pytanie dt. API.

**Chciałbym dodawać produkty do koszyka i je edytować za pomocą API z poziomu strony firmowej.**

Czy jest to wykonalne?

**Comment by MrBoufigo** [comment]
Dzień dobry, a to dlaczego? Chodzi o sklep L'Oreal.

śr., 29 lis 2023, 09:25 użytkownik AureliuszBrussy ***@***.***>
napisał:

**Comment by AureliuszBrussy** [comment]
Taka jest nasza decyzja, na ten moment na Allegro można złożyć zamówienie tylko z poziomu oficjalnej platformy i aplikacji. Udostępniamy tylko jeden endpoint, który powiązany jest z procesem zakupowym - mianowicie złożeniem oferty w aukcji ([PUT /bidding/offers/{offerId}/bid](https://developer.allegro.pl/documentation#tag/Auctions-and-Bidding))
