### ISSUE TITLE
Sandbox -konto firmowe

### ISSUE THREAD

**Issue by king-belohun** [allegro/allegro-api#8062]
Cześć, proszę o pełną aktywację konta <jakotikotrak+allegroOLM@gmail.com>
Chodzi o zatwierdzenie weryfikacji konta i danych firmy.
![image](https://github.com/allegro/allegro-api/assets/82832117/42751a63-7066-43e4-9c50-c4805d3a82a8)
Dzięki

**Comment by MaciejFrackowiak** [comment]
Gotowe - konto zweryfikowane i aktywne.
