### ISSUE TITLE
Wystawianie kampanii Ads na koncie sandbox

### ISSUE THREAD

**Issue by baltrek** [allegro/allegro-api#8064]
Przy wejściu w panel w Allegro Ads i przy kliknięciu utwórz kampanię, pojawia się okno kampanie sponsorowane, graficzne itp Jednak nie ma możliwości przejścia dalej i wybranie którejś z tych kampanii. Czy ustawianie kampanii jest zablokowane na sandboxie?

**Comment by AureliuszBrussy** [comment]
Problemem jest żółty pasek notyfikacji o środowisku testowym, przez który nie widać paska konfiguracji. Na ten moment mogę doradzić ukrycie/usunięcie elementu `<div class="sandbox-notice">` z poziomu przeglądarkowych DevTools'ów. Wtedy na dole okna zobaczysz element menu konfiguracyjnego, który pozwoli przejść dalej.
