### ISSUE TITLE
Access Denied problem

### ISSUE THREAD

**Issue by Bursaa** [allegro/allegro-api#8065]
Hi!
I get some error using allegro REST API.
I have an application using developer account talib331 and application is connected to the same account. Im using authorization_code access and when i try to add product i get an error(i have access_token and all):
{"errors":[{"code":"OfferAccessDeniedException","message":"Forbidden","details":null,"path":"","userMessage":"Access denied. You are not authorized to perform operations on the indicated offer"}]}
I dont know what makes it that way, I was checking product creation in my webside like 2 month ago using diffrent account and diffrent application and then it worked but now it doesn't. I can give you all of my code executing whole authorization and product/offer management

**Comment by AureliuszBrussy** [comment]
Your account is a regular account - you can only make sales on an account with a company status. API methods related to offer creating and editing are blocked for regular accounts. [Register a company account](https://allegro.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F) if you want to use these endpoints.
