### ISSUE TITLE
Poradnik dla laika.

### ISSUE THREAD

**Issue by Rzexnik** [allegro/allegro-api#8066]
Dzień dobry!
Jestem totalnie zielony w API.
Czy posiadania innego konta na Sandbox niż  tego, którego używam się na zwykłym Allegro (konto firmowe mam na zwykłym)  umożliwi również korzystanie z API na tym koncie głównym? Czy muszę się na sandboxie zalogować tym kontem głównym- firmowym, żeby korzystać z API? I potem mam wysłać fałszywy przelew jako potwierdzenie tożsamości? 
W którym momencie będę mógł skorzystać z API na swoim głównym koncie?
Czytałem większość tych artykułów, ale nie było tam to zawarte jakoś klarownie.
Dziękuję bardzo za cierpliwość i z góry za pomoc.

**Comment by AureliuszBrussy** [comment]
Konto na środowisku produkcyjnym i na Sandboxie to całkowicie oddzielne konta i nie mają ze sobą żadnego powiązania. 

Aby testować API na Sandboxie [zarejestruj nowe konto firma](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F) na dowolne (fałszywe) dane. W trakcie procesu weryfikacji będziesz mógł wykonać symulację przelewu weryfikacyjnego. Uzupełnij też (fałszywe) dane. Gdy to zrobisz - wróć z informacją i loginem (lub adresem e-mailowym) konta. Aktywuję je w pełni.

**Comment by Rzexnik** [comment]
Czy to działa tak, że po prostu można korzystać z API, ale trzeba to zrobić na tym nowym kocnie sanbox? Jeśli tak to trochę szkoda, bo jednak na swoim głównym mam już sprzedane produkty i to by zepsuło sprzedaż robienie tego od nowa wszystkiego.

**Comment by AureliuszBrussy** [comment]
@Rzexnik oczywiście, że można korzystać z publicznego API na środowisku produkcyjnym. Musisz tylko zrozumieć, że to są oddzielne środowiska, z oddzielną bazą użytkowników, ofert itp. Służy do przeprowadzania testów, gdzie bez obaw o realną sprzedaż i opłaty można testować różne scenariusze, np. wystawianie oferty, obsługę zamówień itd. O Sandboxie napisałem, ponieważ właśnie to o niego pytałeś.
 
Niestety, nie mogę polecić żadnego konkretnego oprogramowania.

**Comment by AureliuszBrussy** [comment]
@Rzexnik tak jak wspomniałem - API jest publicznie dostępne na "głównym" (produkcyjnym) Allegro i można z niego śmiało korzystać.

Na Sandboxie także można korzystać z API. Sandbox to po prostu "testowa" wersja Allegro.

**Comment by Rzexnik** [comment]
okej, żeby korzystać z głównego Allegro muszę się zweryfikować na Sandbox, żeby mieć możliwość korzystania API na głównym?

**Comment by Rzexnik** [comment]
C:\Users\Kosma\PycharmProjects\allegro_API\venv\Scripts\python.exe C:/Users/Kosma/PycharmProjects/allegro_API/main.py
C:\Users\Kosma\PycharmProjects\allegro_API\venv\lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'allegro.pl.allegrosandbox.pl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Kosma\PycharmProjects\allegro_API\main.py", line 27, in <module>
    main()
  File "C:\Users\Kosma\PycharmProjects\allegro_API\main.py", line 22, in main
    access_token = get_access_token()
  File "C:\Users\Kosma\PycharmProjects\allegro_API\main.py", line 15, in get_access_token
    access_token = tokens['access_token']
KeyError: 'access_token'

Process finished with exit code 1

**Comment by Rzexnik** [comment]
okej, dziękuję za cierpliwość. Probuję wykonać to co jest w krok po kroku. Token już mam:
import requests
import json
import urllib3

urllib3.disable_warnings()

CLIENT_ID = "..."          # wprowadź Client_ID aplikacji
CLIENT_SECRET = "..."      # wprowadź Client_Secret aplikacji
TOKEN_URL = "https://allegro.pl/auth/oauth/token"


def get_access_token():
    try:
        data = {'grant_type': 'client_credentials'}
        access_token_response = requests.post(TOKEN_URL, data=data, verify=False,
                                              allow_redirects=False, auth=(CLIENT_ID, CLIENT_SECRET))
        tokens = json.loads(access_token_response.text)
        access_token = tokens['access_token']
        return access_token
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)

def get_main_categories(token):
    try:
        url = "https://api.allegro.pl/sale/categories"
        headers = {'Authorization': 'Bearer access token = ...' + token, 'Accept': "application/vnd.allegro.public.v1+json"}
        main_categories_result = requests.get(url, headers=headers, verify=False)
        return main_categories_result
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)


def main():
    token = get_access_token()
    main_categories = get_main_categories(token)
    print(main_categories.json())


if __name__ == "__main__":
    main()

**Comment by Rzexnik** [comment]
i po spacji po bearer wpisałem token

**Comment by AureliuszBrussy** [comment]
W tym przykładzie kodu nie powinieneś wklejać tokenu ręcznie - jest on wewnątrz funkcji main() przekazywany do funkcji get_main_categories(), by później być użyty wewnątrz tejże tej funkcji, w linijce (zmienna `token`):

`headers = {'Authorization': 'Bearer ' + token, 'Accept': "application/vnd.allegro.public.v1+json"}
`
