### ISSUE TITLE
Problem with add proposion. Error

### ISSUE THREAD

**Issue by arturtretyak** [allegro/allegro-api#8067]
We send api request and got some error. What's wrong? It`s look like a bug.

`  [url] => https://api.allegro.pl/sale/product-offers/HS2602
    [headers] => Array
        (
            [0] => Authorization: Bearer "sometoken"
            [1] => Accept: application/vnd.allegro.public.v1+json
            [2] => Content-Type: application/vnd.allegro.public.v1+json
        )
    [request] => {"productSet":[{"product":{"name":"AMMA S\u0141O\u0143 PLUSZAK BING MASKOTKA","id":"HS2602","idType":"MPN","category":{"id":"322049"},"parameters":[{"id":"248811","name":"Marka","values":["bez marki"]},{"id":"3475","name":"Wiek dziecka","values":["12 m +"]},{"id":"244505","name":"Nazwa","values":["MASKOTKA"]},{"id":"237222","name":"Seria","values":["BING"]},{"id":"247724","name":"Materia\u0142","values":["tkanina"]},{"id":"223329","name":"Wysoko\u015b\u0107 produktu","values":["25"]},{"id":"224017","name":"Kod producenta","values":["HS2602"]},{"id":"225693","name":"EAN (GTIN)","values":["5905679701508"]},{"id":"11323","name":"Stan","values":["Nowy"]}]},"quantity":{"value":1}}],"external":{"id":"HS2602"},"stock":{"available":"0.000","unit":"UNIT"},"publication":{"status":"ENDED"},"category":{"id":"322049"},"images":["https:\/\/poland.1b.app\/media\/shop\/\/8d\/c8\/8dc893f04116225bdc54d8925bcdce68.jpg","https:\/\/poland.1b.app\/media\/shop\/\/9f\/6d\/9f6d9b9cedb1860deec3112e9e6a6844.jpg","https:\/\/poland.1b.app\/media\/shop\/\/4c\/5e\/4c5ec86f69465dcf325a6a8b9fe404be.jpg","https:\/\/poland.1b.app\/media\/shop\/\/98\/b0\/98b0b8296091aa5fb3f253318c86b92b.jpg","https:\/\/poland.1b.app\/media\/shop\/\/3d\/22\/3d229a2daf74e12a0ef2a1edd3800714.jpg","https:\/\/poland.1b.app\/media\/shop\/\/99\/58\/995853f0c28b4b9a355b964d8ac7c0b4.jpg"],"name":"AMMA S\u0141O\u0143 PLUSZAK BING MASKOTKA","description":{"sections":[{"items":[{"type":"TEXT","content":"<div class=\"row\"><div class=\"col\"><img src=\"https:\/\/a.allegroimg.com\/original\/1190da\/4998b88b48ccba30bcd03d569ce9\" \/><\/div><\/div><div class=\"row\"><div class=\"col\"><img src=\"https:\/\/a.allegroimg.com\/original\/114f73\/3614ab31428795a3dd3e5b0dc2fd\" \/><\/div><\/div><div class=\"row\"><div class=\"col\"><img src=\"https:\/\/a.allegroimg.com\/original\/1190da\/4998b88b48ccba30bcd03d569ce9\" \/><\/div><div class=\"col\"><h2>S\u0141ODKI PLUSZOWY TOWARZYSZ<\/h2>\n<p>Amma to urocza maskotka, kt\u00f3ra wyr\u00f3\u017cnia si\u0119 swoim nietypowym po\u0142\u0105czeniem postaci \u2013 co sprawia, \u017ce jest jeszcze bardziej oryginalna i atrakcyjna dla dzieci.<\/p>\n<p>Pluszowa Amma wykonana jest z najwy\u017cszej jako\u015bci mi\u0119kkiego pluszu, co sprawia, \u017ce jest idealnym towarzyszem do przytulania i zabawy. Jej wymiary (oko\u0142o 25 cm) s\u0105 idealne dla dzieci, kt\u00f3re szukaj\u0105 towarzysza w codziennych zabawach.<\/p>\n<p>Dodatkowo, maskotka Amma zosta\u0142a wykonana w najdrobniejszych szczeg\u00f3\u0142ach, co czyni j\u0105 niezwykle realistyczn\u0105 i jeszcze bardziej przyjazn\u0105 dla najm\u0142odszych fan\u00f3w.<\/p><\/div><\/div><div class=\"row\"><div class=\"col\"><h2>IDEALNY PREZENT DLA DZIECKA<\/h2>\n<p>To doskona\u0142y pomys\u0142 na prezent dla dziecka, kt\u00f3re ceni sobie oryginalne i kreatywne zabawki. Amma sprawi, \u017ce dziecko zatraci si\u0119 w swojej wyobra\u017ani, tworz\u0105c wspania\u0142e przygody z t\u0105 urocz\u0105 maskotk\u0105.<\/p>\n<p>Nie czekaj, zam\u00f3w ju\u017c teraz pluszowego s\u0142onika-kroliczka Amma i spraw dziecku niezapomnian\u0105 przyjemno\u015b\u0107 w codziennych zabawach i przytulankach!<\/p><\/div><div class=\"col\"><img src=\"https:\/\/a.allegroimg.com\/original\/111c22\/750dfb9a44d1a548443990532f2a\" \/><\/div><\/div><div class=\"row\"><div class=\"col\"><img src=\"https:\/\/a.allegroimg.com\/original\/111c22\/750dfb9a44d1a548443990532f2a\" \/><\/div><\/div>"}]}]},"sellingMode":{"format":"BUY_NOW","price":{"amount":19,"currency":"PLN"}},"parameters":[{"id":"248811","name":"Marka","values":["bez marki"]},{"id":"3475","name":"Wiek dziecka","values":["12 m +"]},{"id":"244505","name":"Nazwa","values":["MASKOTKA"]},{"id":"237222","name":"Seria","values":["BING"]},{"id":"247724","name":"Materia\u0142","values":["tkanina"]},{"id":"223329","name":"Wysoko\u015b\u0107 produktu","values":["25"]},{"id":"224017","name":"Kod producenta","values":["HS2602"]},{"id":"225693","name":"EAN (GTIN)","values":["5905679701508"]},{"id":"11323","name":"Stan","values":["Nowy"]}]}
    [responce] => {"errors":[{"code":"NotSupportedException","message":"Unsupported content type. Please check 'Content-Type' request header","details":null,"path":null,"userMessage":"Request contains invalid data. Contact the application author."}]}
    [code] => 415`

Thank you.

**Comment by AureliuszBrussy** [comment]
You make requests to the offer `HS2602` (which you can see in the request path). Such an offer id does not exist - it is not the id that was created by us. 

You must use the id that is generated by us when creating the offer (POST method).

**Comment by AureliuszBrussy** [comment]
I see in our logs that you sent the wrong Content-Type: `application/x-www-form-urlencoded`.

**Comment by arturtretyak** [comment]
Okay, thank you. But may be you need to edit your documentation.
https://developer.allegro.pl/documentation#tag/User's-offer-information
![image](https://github.com/allegro/allegro-api/assets/33950340/026d69ee-51b0-4ef5-81d9-f2bfd8455c20)

**Comment by AureliuszBrussy** [comment]
`application/vnd.allegro.public.v1+json` is correct. You are sending `application/x-www-form-urlencoded` value.
