### ISSUE TITLE
Problem z zamykaniem ofert przez automat Allegro

### ISSUE THREAD

**Issue by aszejda** [allegro/allegro-api#8069]
Witam, ostatnio regularnie zamykane są nasze oferty z felgami stalowymi. Oferty mają różne tytuły a mimo to część z wystawionych została usunięta. Wiemy, że zmieniły się ostatnio zasady dotyczące duplikatów (tytuły przestały mieć znaczenie a brane są pod uwagę miniaturki oraz parametry), ale nowe zasady miały nie dotyczyć kategorii ... motoryzacja / felgi i opony / felgi. 

Automat działa wybiórczo.  Dla przykładu wystawione wczoraj oferty: 
14796310272
14796310290
14796310276
14796310271
14796310278
14796310283
14796310275
14796310280
14796310273
14796310282
Tylko połowa z nich została zamknięta.

Chcielibyśmy poznać zasadę działania automatu. Niestety bez tego nie jesteśmy w stanie ustawić prawidłowych kryteriów w naszej aplikacji do wystawiania ofert.

**Comment by AureliuszBrussy** [comment]
Jeżeli chciałbyś się dowiedzieć czegoś więcej na temat powodów zakończenia ofert - skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt), tworząc zgłoszenie z konta, do którego te oferty należą.
