### ISSUE TITLE
Prośba o aktywacje konta

### ISSUE THREAD

**Issue by Arkowsky** [allegro/allegro-api#807]
Dzień dobry,
proszę o aktywacje konta w Sandbox
mail: admin@coffeedesk.pl
login: coffeedeskpl

Pozdrawiam

**Comment by PawelTaberski** [comment]
Zaakceptowałem Twoje konta, ale aby mógł zatwierdzić konto firmowe musisz rozpocząć ścieżkę aktywacji konta firmowego, inaczej nie mogę zaakceptować ręcznie.

**Comment by Arkowsky** [comment]
niby już można wejść w wystawianie akucji ale nie możemy  zapisać aukcji - pojawia się kominikat:

"Podczas tworzenia oferty wystąpiły błędy
Użytkownik z blokadą konta Firma nie może wystawiać nowych ofert."

**Comment by PawelTaberski** [comment]
Tak, jak pisałem musisz rozpocząć ścieżkę aktywacji konta firma, wtedy będę mógł zatwierdzić ręcznie takie konto. Musisz przejść w zakładkę moje konto - dane przedsiębiorstwa i skorzystać z przycisku wyślij do weryfikacji

**Comment by Arkowsky** [comment]
Ok, brakowało mi tego "Musisz przejść w zakładkę moje konto - dane przedsiębiorstwa i skorzystać z przycisku wyślij do weryfikacji". Dziękuję. Działa. Zamykam.
