### ISSUE TITLE
Zasób order/checkout-forms/{id}/invoices - klienci nie widzą załączonych faktur w zamówieniu, brak informacji o załączonej fakturze w szczegółach zamówienia

### ISSUE THREAD

**Issue by Qenozis** [allegro/allegro-api#8070]
Witam,
Po załączeniu pliku z dokumentem sprzedaży (fakturą) do zamówienia, jedynym miejscem gdzie widoczna jest przesłana faktura oraz możliwa do pobrania jest lista zamówień (ikonka-przycisk po prawej stronie każdego zamówienia posiadającego załączoną fakturę). Niestety w szczegółach zamówienia jest jedynie odnośnik do dodania faktury (brak jakiejkolwiek informacji o już załączonej fakturze lub fakturach), ale nawet skorzystanie z niego nie powoduje wyświetlenia w szczegółach zamówienia nowo załączonej faktury. Klienci również nie mogą znaleźć (ani pobrać) w swoich zamówieniach załączonych faktur.

Proszę o informację, czy zasób [**order/checkout-forms/{id}/invoices**](https://developer.allegro.pl/documentation#operation/addOrderInvoicesMetadata) miał w założeniu dawać możliwość klientom pobrania z poziomu zamówienia załączonej przez sprzedawcę faktury? Jeśli tak - to zasób ten ma bug/i i tego nie robi, więc wymagałby naprawy. Jeśli nie - to po co on w ogóle istnieje?

**Comment by AureliuszBrussy** [comment]
Oczywiście zasób ma służyć do przekazywania faktury VAT kupującemu, który powinien może sobie później ją pobrać w szczegółach zamówienia. Jeżeli kupujący ma jakiś problem z pobraniem tego pliku z poziomu [Moich Zakupów](https://allegro.pl/moje-allegro/zakupy/kupione) - powinien zgłosić to poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
