### ISSUE TITLE
compatibilityList w zestawie produktów - wycięte do zera 

### ISSUE THREAD

**Issue by PunktAutoCzesci** [allegro/allegro-api#8071]
Cześć,
mam pewien problem z sekcją pasujeDo w zestawach produktów, lub po prostu nie rozumiem jak to działa. 

**method**: "**patch**"

Kategoria produktu głównego to klocki hamulcowe. 

Produkt główny to produkt TecDoc z sekcją pasuje do - 1 szt

Produkt drugi to produkt który nie posiada w ogóle sekcji Pasuje Do. Jest z kategorii w której nie jest obsługiwana taka sekcja. - 1szt.

Po wybraniu tych produktów w productSet z oferty wycinana jest całkowicie sekcja PasujeDo.

Domyślam się, że wynika to z wyświetlania tylko elementów wspólnych, czyli żadnych. 

Pytanie brzmi. Jak mogę przywrócić sekcję PasujeDo z produktu głównego tak żeby była wyświetlana w ofercie która jest takim zestawem?
Ewentualnie czy mogę ją / lub jej id dostarczyć w jakiś inny sposób?

Dzięki.

**Comment by AureliuszBrussy** [comment]
Który z produktów jest pierwszy na liście productSet[]? Ten z wypełnioną sekcją Pasuje do? Czy mógłbyś podesłać np. trace-id przykładowego requestu abyśmy mogli dokładniej sprawdzić ten przypadek?

**Comment by PunktAutoCzesci** [comment]
Pierwszy jest produkt tecDoc. Tace id później podeślę.

pt., 1 gru 2023, 09:01 użytkownik AureliuszBrussy ***@***.***>
napisał:

**Comment by AureliuszBrussy** [comment]
Dziękuję za informację, w takim razie czekam na trace-id i będziemy to dokładniej analizować.

**Comment by PunktAutoCzesci** [comment]
trace-id: 'b5a3b3eb3e71ff55'

**Comment by PunktAutoCzesci** [comment]
nowy trace-id: '78ad92b59a1cebf6'
testuje własną aplikację.

Na razie próbuję tak:
```
data.productSet = [
        {
            product: {
                id: `649f40c2-41d1-4506-9a8b-6c00af6efa18`,
                parameters: [
                    {
                        name: 'Strona zabudowy',
                        values: ['tył'],
                    }, {
                        name: 'Producent części',
                        values: ['TRW']
                    }, {
                        name: 'Typ samochodu',
                        values: ['Samochody osobowe']
                    }, {
                        name: 'Numer katalogowy części',
                        values: ['GDB1330']
                    }
                ],

            },
            quantity: {
                "value": 1
            }
           
        },

        {
            product: {
                id: `1544e56c-fa67-49f0-97cc-0c4bdcb6b5bd`,
            },
            quantity: {
                "value": 1
            },

           
        },
    ]

```

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Dziękuję za szczegółowe dane. Analizujemy temat.

**Comment by PunktAutoCzesci** [comment]
Przez formularz jak dodam pojazd do sekcji pasuje do i chcę zapisać zmiany to mam komunikat:
`Podczas modyfikowania oferty wystąpiły błędy - Produkty wchodzące w skład zestawu pochodzą z kategorii wspierających różne typy sekcji "Pasuje do". Nie można przypisać sekcji "Pasuje do" do oferty.`

![Zrzut ekranu 2023-12-05 220739](https://github.com/allegro/allegro-api/assets/132820484/6ea07143-1e3f-4802-96b0-975ce64dd363)

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Dziękuję za dodatkowe informacje. Jak tylko uzyskam szczegóły - wrócę z odpowiedzią.

**Comment by PunktAutoCzesci** [comment]
Cześć, wiadomo już coś?


śr., 6 gru 2023, 09:33 użytkownik Lukasz-Zurek ***@***.***>
napisał:

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Tak. Przepraszam za długi czas oczekiwania na wyjaśnienie z naszej strony. Problem spowodowany był przez kategorię e-book'ów jednego z produktów. Nasz Serwis nie jest w stanie znaleźć wspólnej sekcji "Pasuje do". Samodzielne wskazanie "Pasuje do" w tej sytuacji również nie jest możliwe.

Jest to proces, który chcemy po naszej stronie zoptymalizować. Nie jestem w stanie zadeklarować czasu, w którym to nastąpi. Jak tylko uda się ten temat zrealizować, poinformuję o tym fakcie w tym wątku.

**Comment by PunktAutoCzesci** [comment]
A czy gdybym łączył np dwa komplety klocków hamulcowych to w jaki sposób
powinna zostać przekazana compatibility list. Zakładając że chciałbym
przekazać własną lub pisać id z tylko jednego produktu tak żeby lista była
w pełni wyświetlana dla kompletu?

czw., 14 gru 2023, 10:40 użytkownik Lukasz-Zurek ***@***.***>
napisał:

**Comment by PunktAutoCzesci** [comment]
Dodam, że dwa różne komplety klocków

czw., 14 gru 2023, 10:51 użytkownik Punkt Auto Części <
***@***.***> napisał:

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Co do zasady - w opisanej przez Ciebie sytuacji powinniśmy automatycznie wyliczyć i przypisać wspólne "Pasuje do" dla obu kompletów klocków. Powinieneś mieć również możliwość samodzielnego zdefiniowania "Pasuje do".

**Comment by PunktAutoCzesci** [comment]
No właśnie chodzi mi o to czy powinienem pisać pasuje do w sekcjach
produktów. Np dwa razy to samo. Czy w sekcji opisowej.

czw., 14 gru 2023, 11:55 użytkownik Lukasz-Zurek ***@***.***>
napisał:

**Comment by Lukasz-Zurek** [comment]
Z tego co widzę części samochodowe, do których należą klocki hamulcowe - bazują na identyfikatorach, więc możesz przekazać to w takiej formie jak wskazałeś powyżej. 

Dodam, że szczegółowe informacje w kontekście kategorii sprawdzisz za pomocą [GET /sale/compatibility-list/supported-categories](https://developer.allegro.pl/documentation/#operation/getCategoriesThatSupportCompatibilityList).

**Comment by PunktAutoCzesci** [comment]
Cześć, wracam z problemem ;)
Faktycznie jeśli podam własną listę aut to jest ona wyświetlana zamiast listy aut z produktu. 
Po dodaniu własnej listy typ compatibility list zmienia się na MANUAL. 
Trzeba go podać w takiej formie: 
```
items: [
            {
                "type": "id",
                "id": `de7a2247-78fa-4a12-94f1-f43b5f33ac7e`
            },
            {
                "type": "id",
                "id": `de7a2247-78fa-4a12-94f1-f43b5f33ac7e`
            },
        ]
```
tak jak pisałeś, trzeba podać **id** a **nie text.** 

Zastanawiam się czy nie ma innej opcji? 

W danych produktu **/sale/products** lista zastosowania przedstawiona jest w takiej formie:
```
id: 649f40c2-41d1-4506-9a8b-6c00af6efa18-fe817b2e4a117fde7887a3d20886c2048ea0d0154ea9e1e2cdbe37881adceecd-2
type: PRODUCT_BASED
items: [
{ text: 'Audi A1 (8X1, 8XK) 1.0 TFSI 2015/03-2018/10' },
{ text: 'kolejne auto' }
]
```
Zastanawiałem się czy w podanym przeze mnie compatibilityList  nie można podać po prostu takiego identyfikatora całej listy zastosowania z produktu,  zamiast wypisywać każde auto po kolei wpisując jego id. 
Jeśli można to w jakiej formie należy to podać ? 

Jeśli się nie da to jest kolejny problem. 
W danych produktu mamy wartości tekstowe, a we własnym compatibilityList.items w ofercie muszę podać **id** każdego auta. 

Pomyślałem, że jak znam id produktu na którym chcę bazować to mogę skorzystać z zasobu **sale/compatibility-list-suggestions** 

Tutaj napotkałem kolejny problem. Zasób nie zwraca list kompatybilności. 

Przykład 1:
/sale/compatibility-list-suggestions?language=pl-PL&product.id=649f40c2-41d1-4506-9a8b-6c00af6efa18
trace-id: '38a0ce94117d6899'
error: 'Dla podanego produktu nie znaleziono sugerowanej tabeli kompatybilności.' 

Przykład 2:
/sale/compatibility-list-suggestions?language=pl-PL&offer.id=14873327168
trace-id: 'faeb4dc437f4dd4b'
error: 'Dla podanej oferty nie znaleziono sugerowanej tabeli kompatybilności.'

Sprawdzicie dlaczego ?
Może macie jakąś sugestię? 
Czy macie jakieś plany co do compatibilityList w przypadku kiedy 1 produkt w zestawie ma compatibilityList np. obsługujący id a drugi w ogóle nie obsługuje compatibilityList lub jest innego typu np. tekstowego? 

Dzięki

**Comment by Lukasz-Zurek** [comment]
> Cześć, wracam z problemem ;) Faktycznie jeśli podam własną listę aut to jest ona wyświetlana zamiast listy aut z produktu. Po dodaniu własnej listy typ compatibility list zmienia się na MANUAL. Trzeba go podać w takiej formie:
> 
> ```
> items: [
>             {
>                 "type": "id",
>                 "id": `de7a2247-78fa-4a12-94f1-f43b5f33ac7e`
>             },
>             {
>                 "type": "id",
>                 "id": `de7a2247-78fa-4a12-94f1-f43b5f33ac7e`
>             },
>         ]
> ```
> 
> tak jak pisałeś, trzeba podać **id** a **nie text.**
> 
> Zastanawiam się czy nie ma innej opcji?

W tej konkretnej sytuacji nie ma innej możliwości.
> 
> W danych produktu **/sale/products** lista zastosowania przedstawiona jest w takiej formie:
> 
> ```
> id: 649f40c2-41d1-4506-9a8b-6c00af6efa18-fe817b2e4a117fde7887a3d20886c2048ea0d0154ea9e1e2cdbe37881adceecd-2
> type: PRODUCT_BASED
> items: [
> { text: 'Audi A1 (8X1, 8XK) 1.0 TFSI 2015/03-2018/10' },
> { text: 'kolejne auto' }
> ]
> ```
> 
> Zastanawiałem się czy w podanym przeze mnie compatibilityList nie można podać po prostu takiego identyfikatora całej listy zastosowania z produktu, zamiast wypisywać każde auto po kolei wpisując jego id. Jeśli można to w jakiej formie należy to podać ?

Niestety takiej możliwości również tutaj nie ma. Należy wprowadzić każdą pozycję.
> 
> Jeśli się nie da to jest kolejny problem. W danych produktu mamy wartości tekstowe, a we własnym compatibilityList.items w ofercie muszę podać **id** każdego auta.
> 
> Pomyślałem, że jak znam id produktu na którym chcę bazować to mogę skorzystać z zasobu **sale/compatibility-list-suggestions**
> 
> Tutaj napotkałem kolejny problem. Zasób nie zwraca list kompatybilności.
> 
> Przykład 1: /sale/compatibility-list-suggestions?language=pl-PL&product.id=649f40c2-41d1-4506-9a8b-6c00af6efa18 trace-id: '38a0ce94117d6899' error: 'Dla podanego produktu nie znaleziono sugerowanej tabeli kompatybilności.'
> 
> Przykład 2: /sale/compatibility-list-suggestions?language=pl-PL&offer.id=14873327168 trace-id: 'faeb4dc437f4dd4b' error: 'Dla podanej oferty nie znaleziono sugerowanej tabeli kompatybilności.'
> 
> Sprawdzicie dlaczego ?

Błędy oznaczają, że w naszej bazie nie posiadamy żadnych sugestii "Pasuje Do" dotyczących wskazanych produktów. Sugestie tworzymy na podstawie list kompatybilności ofert innych sprzedających, a w tej sytuacji wychodzi, że nikt nie wystawił oferty z tym produktem, podając jednocześnie "Pasuje Do".
> 
> Do głowy przychodzi mi jeszcze możliwość wklejania wartości tekstowych z listy zastosowania z danych produktowych i dla każdej wartości tekstowej wywołać: /sale/compatible-products?type=CAR&phrase=wartość_tekstowa_items_z_danych_produktu. ale to by kosztowało na prawdę dużo requestów.
> 
> Może macie jakąś sugestię? Czy macie jakieś plany co do compatibilityList w przypadku kiedy 1 produkt w zestawie ma compatibilityList np. obsługujący id a drugi w ogóle nie obsługuje compatibilityList lub jest innego typu np. tekstowego?

Obecnie nie mamy planów związanych z compatibilityList w kontekście tego co napisałeś.

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Teoretycznie powinniśmy zwrócić wyniki, dlatego temat ten weryfikuję z zespołem odpowiedzialnym za tę usługę. Proszę o cierpliwość.

**Comment by PunktAutoCzesci** [comment]
Cześć, udało się ustalić dlaczego **/sale/compatibility-list-suggestions** nie zawraca wyników / zwraca błąd ?

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Mogę ponownie potwierdzić, że sugestie tworzymy na podstawie list kompatybilności ofert innych sprzedających, a w tej sytuacji wychodzi, że nikt nie wystawił oferty z tym produktem, podając jednocześnie "Pasuje Do", dlatego zwracamy błąd.

Dodam, że wskazane produkty posiadają listę "Pasuje do". Jeżeli chciałbyś przekazać listę z produktu, podczas wystawiania oferty compatibilityList przekaż pusty obiekt, lub `null`.

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Już precyzuję - sugestie na wskazanym zasobie są zwracane tylko dla manualnych tabel kompatybilności, utworzonych przez użytkownika. Nie zwracamy ich na podstawie produktowych.

Jeżeli zatem posiadasz ofertę z produktem z Tecdoc - posiada ona tzw. produktową tabelę kompatybilności. W tej konkretnej sytuacji nie tworzymy sugestii, ponieważ dla oferty z tym produktem nie można utworzyć innej tabeli kompatybilności niż produktowa (tecdoc).

**Comment by PunktAutoCzesci** [comment]
Ok, dzięki za doprecyzowanie. 
W przykładach odpowiedzi /sale/compatibility-list-suggestions jest wymieniony:
"PRODUCT_BASED - for offers associated with product - if compatibility list is provided in the product details (GET/sale/products/{productId}), it needs to be included in the offer in unchanged form."
W jakich sytuacjach jest zwracana sugerowana lista kompatybilności typu "PRODUCT_BASED  ?

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Wiem, że poruszyłeś to już wcześniej, ale skupiłem się na całej logice. Analizujemy funkcjonalność pod kątem dokumentacji. Całkiem możliwe, że dokumentację będziemy musieli zaktualizować / dostosować do stanu faktycznego czyli obecnie obowiązującej logiki. Pozwól, że wrócę do Ciebie z konkretną informacją.

**Comment by PunktAutoCzesci** [comment]
Cześć:

1. Czy ustalono już jak rozwiązać błąd związany z próbą połączenia 2 produktów (1 z compatibility list drugi bez): "Podczas modyfikowania oferty wystąpiły błędy - Produkty wchodzące w skład zestawu pochodzą z kategorii wspierających różne typy sekcji "Pasuje do". Nie można przypisać sekcji "Pasuje do" do oferty."
2. Czy udało się przeanalizować funkcjonalność /sale/compatibility-list-suggestions ->  PRODUCT_BASED pod kątem ewentualnych błędów lub dostosowania dokumentacji?

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci 

Nadal analizujemy temat wspólnie z zespołem odpowiedzialnym za tę usługę. Proszę o cierpliwość.

**Comment by PunktAutoCzesci** [comment]
Cześć, jakieś wieści?

śr., 10 sty 2024 o 23:29 stale[bot] ***@***.***> napisał(a):

**Comment by Lukasz-Zurek** [comment]
Niestety wymaga to czasu. Przede wszystkim dziękuję Tobie za Twoje zgłoszenie, bo dzięki temu dwa wskazane tematy są już analizowane i z pewnością będą optymalizowane.

1. Z uwagi na problemy z wyliczaniem wspólnego "Pasuje do" i utrudnienia w samodzielnym zdefiniowaniu w niestandardowych przypadkach, zespół odpowiedzialny za te funkcjonalności analizuje nowy sposób podejścia do tematu.
2. Problem został już zgłoszony i czeka na dalsze decyzje. Zasób **/sale/compatibility-list-suggestions** nie zwróci typu `PRODUCT_BASED`. Dokumentacja i funkcjonalność były wcześniej dostosowywane pod model ofertowy, który uległ zmianie. W związku z tym - informacje w dokumentacji są nieaktualne i na pewno zostaną wkrótce zaktualizowane.

Monitoruję te dwa tematy i jak tylko uzyskam szczegóły - wrócę z informacjami w tym wątku.

**Comment by PunktAutoCzesci** [comment]
Proszę, przyjąć sugestię, żeby dane produktu Allegro w sekcji `compatibilityList`, oprócz wartości tekstowych zwracały również `id `+             `additionalInfo`.
Obecnie w motoryzacji nie ma za bardzo wykorzystania dla samej informacji tekstowej,  bo w większości kategorii motoryzacyjnych w sekcji ofertowej w `compatibilityList `wymagane są id + `additionalInfo `a nie `text`. 

Ewentualnie można poszukać też innego użytecznego rozwiązania. Np, żeby w sekcji ofertowej można było podać tylko identyfikator listy kompatybilności. Jest on zwracany w produkcie, ale nigdzie nie można go użyć.

Mówimy cały czas o produktach z bazy TecDoc. 

Jeśli chodzi o prezentowanie wspólnych elementów "Pasuje do" to sugeruję dla zestawu w którym **produkt główny posiada sekcję pasuje do a kolejne go nie mają** proponuję:
Wyświetlić listę kompatybilności produktu głównego z nagłówkiem `[nazwa produktu] pasuje do:`

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Prześlij proszę dodatkowo tę sugestię (z ostatniego posta) w dedykowanym do pomysłów wspierających rozwój naszego API, czyli na [Github Discussions](https://github.com/allegro/allegro-api/discussions). Nie chciałem tu konwertować całego wątku w dyskusję z uwagi na inne poruszone tutaj kwestie, które są nadal weryfikowane przez zespół odpowiedzialny za funkcjonalności związane z TecDoc.

**Comment by PunktAutoCzesci** [comment]
Czy jest jakiś konsensus lub decyzje w sprawie listy "Pasuje do"?

**Comment by Lukasz-Zurek** [comment]
Zespół odpowiedzialny za te funkcjonalności zaplanował zmiany dotyczące m.in. PRODUCT_BASED, dokumentacji i logiki tego procesu. Jak tylko zmiany zostaną wdrożone, poinformujemy o nich w [naszych aktualnościach](https://developer.allegro.pl/news/).
