### ISSUE TITLE
Długi czas oczekiwania na weryfikację danych rachunku bankowego i danych firmy na sandbox

### ISSUE THREAD

**Issue by jerzyplecinski1** [allegro/allegro-api#8074]
Jak w temacie, wczoraj założyłem konto na https://allegro.pl.allegrosandbox.pl/ i nadal czekam na weryfikację rachunku bankowego i danych firmy. Jeśli jest taka możliwość proszę o rozpatrzenia tej weryfikacji lub podanie informacji w jakim czasie konto będzie dostępne. 

Login: sklepecomm
jerzy.plecinski21cn@gmail.com

**Comment by AureliuszBrussy** [comment]
Aktywowałem Twoje konto.

**Comment by jerzyplecinski1** [comment]
Dzięki
