### ISSUE TITLE
Zamówienie z Orlen Paczka zawiera nieistniejący punkt

### ISSUE THREAD

**Issue by Maczuga** [allegro/allegro-api#8075]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Zamówienie 2ba2cdf0-8ec7-11ee-8004-2901878c17de

Klient wybrał dostawę do punktu:
ORLEN Paczka: W**S**-813565-H1-33
Chodakowska 35
03-828 Warszawa

Problem w tym, że ten punkt nie istnieje pod takim numerem, powinien być tu numer W**1**-813565-H1-33

Próba nadania z waszym numerem kończy się na błędzie ze strony Orlenu "saved but changed DestinationCode".

Problem zapewne leży zarówno po stronie Orlenu jak i synchronizacji punktów u was, ponieważ od czasu jak synchronizujemy po swojej stronie od kilku miesięcy punkty orlenu - tak punkt, który został zwrócony na Allegro nigdy nie istniał, z kolei W1 - który przechodzi bez problemu już istnieje.

**Comment by AureliuszBrussy** [comment]
Dziękuję za zgłoszenie. Poprawiliśmy to po naszej stronie, nie będziemy już zwracać id `WS-813565-H1-33`.
