### ISSUE TITLE
Brak możliwości pobierania punktów czeskich poprzez API

### ISSUE THREAD

**Issue by Rychu1998** [allegro/allegro-api#8079]
Dzień dobry,

Zwracam się w imieniu naszego wspólnego klienta. Punkty czeskie nie są zwracane przez Państwa API , czy mają Państwo w planach wprowadzić taką metodę w przyszłości ?

**Comment by Rychu1998** [comment]
Wywołujemy w naszej aplikacji Avocado Shipping metodę, która zwraca punkty Allegro One (załącznik poniżej), która nie zwraca nam jednak punktów czeskich dla typów przesyłki np. (Allegro International Odbiór w punkcie), a naszym klientom bardzo na tym zależy. Czy istnieje do tego jakaś inna metoda, której nie znaleźliśmy ? Czy może na chwilę obecną nie mają Państwo tego obsłużonego, jeśli tak to czy planują Państwo dodać taką funkcjonalność ?
 
[allegro punkty.json](https://github.com/allegro/allegro-api/files/13587406/allegro.punkty.json)

**Comment by MaciejFrackowiak** [comment]
Nie, jako Allegro zwracamy informacje tylko o punktach dla przesyłek Allegro One, ponieważ dla nich operatorem przesyłek jest Allegro. Dla każdego innego typu przesyłek operatorem jest podmiot trzeci i to w ramach jego działalności zazwyczaj jest wystawiane API z danymi o punktach. Przesyłki Allegro International są transportowane przez InPost oraz We|Do.
