### ISSUE TITLE
doGetMySellItems niepoprawna ilość aukcji w kategorii 

### ISSUE THREAD

**Issue by KJtTGHAK** [allegro/allegro-api#808]
Zwraca mi niepoprawną ilość elementów kiedy podaję numer kategorii w funkcji doGetMySellItems.
Jeżeli nie podam tego parametru i odfiltruję sobie kategorie ze wszystkich zwróconych elementów, to mam dobrą ilość aukcji.
Co robię źle?
Tak wywołuję funkcję allegro z kategorią:
```php
doGetMySellItems($session_id, null, null, null, $category_id, null, 1000, $page);
```
Tak pobieram wszystko, a potem odfiltrowuje kategorie:
```php
$result = $this->doGetMySellItems($session_id, null, null, null, null, null, 1000, $page);

foreach ($result->sellItemsList->item as $value) 
{
    if ($value->itemCategoryId == $category_id) 
    {
        $result_arr[] = $value->itemId;
    }
}
```
Lista kategorii:
```php
CONST ALLEGRO_CAT_ID_OPONY_OSOBOWE_LETNIE = 257689;
CONST ALLEGRO_CAT_ID_OPONY_OSOBOWE_ZIMOWE = 257691;
CONST ALLEGRO_CAT_ID_OPONY_OSOBOWE_CALOROCZNE = 257692;
CONST ALLEGRO_CAT_ID_OPONY_DOSTAWCZE_LETNIE = 257698;
CONST ALLEGRO_CAT_ID_OPONY_DOSTAWCZE_ZIMOWE = 257699;
CONST ALLEGRO_CAT_ID_OPONY_DOSTAWCZE_CALOROCZNE = 257700;
```

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) requesty i responsy w formacie XML z tych metod i zaznacz proszę w jakich miejscach zauważyłeś rozbieżności. Jesteś pewny, że nie korzystasz z jakiś filtrów, które mogłyby ograniczyć ilość ofert jakie otrzymujesz w odpowiedzi?

**Comment by KJtTGHAK** [comment]
Wydaje mi się że problem występuje dla aukcji, które wkrótce się skończą, w przeciągu paru godzin. Jak zgłaszałem ten błąd miałem takie aukcje. Teraz w obu przypadkach stany się zgadzają, a ja nic nie zmieniałem.
Jeżeli chodzi o ten XML, to jak znowu będę miał niezgodności, to wyślę wam pliki.
