### ISSUE TITLE
Brak produktu TecDoc w produktach Allegro

### ISSUE THREAD

**Issue by PunktAutoCzesci** [allegro/allegro-api#8080]
Cześć, 
nie mogę znaleźć produktu TecDoc

metoda: `/sale/products?`

przykładowy numer szukanej części to: DRM0303S
Producent: DR.MOTOR
Chociaż pełna nazwa to: Dr.Motor Automotive

Niektóre produkty tej marki znajduje. Np: "DRM1002"

Zaznaczam, że chodzi mo tylko o produkty TecDoc. 

Sprawdzicie czy DRM0303S występuje w waszej bazie TecDoc?

Dzięki

**Comment by PunktAutoCzesci** [comment]
Sprawdzałem po mpn i jako tekst. Od frontu też nie znajduje. Sprawdź proszę
czy macie ten produkt w ogóle w bazie treść doc. Dzięki

pon., 4 gru 2023, 08:33 użytkownik AureliuszBrussy ***@***.***>
napisał:

**Comment by AureliuszBrussy** [comment]
Za pomocą takiego query: `GET /sale/products?mode=MPN&phrase=DRM0303S` udało mi się wyszukać 2 produkty pasujące do tej frazy. Natomiast rozumiem, że chodzi o to, że żaden z tych produktów nie ma specyfikacji TecDoc, a tylko takie produkty Ciebie interesują?

**Comment by PunktAutoCzesci** [comment]
Dokładnie tak. Moim zdaniem powinien być też produkt TecDoc.

pon., 4 gru 2023, 10:35 użytkownik AureliuszBrussy ***@***.***>
napisał:

**Comment by AureliuszBrussy** [comment]
Faktycznie, mamy ten produkt TecDoc, natomiast specyfikacja nie został tutaj poprawnie zmapowana. Zgłosiłem to do odpowiedniego zespołu. Wrócę z informacją, jak tylko coś się zmieni w temacie.

**Comment by AureliuszBrussy** [comment]
Analizujemy to. Wrócę z informacją, gdy coś ustalimy.

**Comment by PunktAutoCzesci** [comment]
Kolejny przykład braku produktu TecDoc 
marka: ESEN SKV
nr Katalogowy: 59SKV069

na Allegro brak produktu TecDoc do wyboru

**Comment by PunktAutoCzesci** [comment]
Dodam tylko, że tu jest podobna sytuacja. 
Dla przykładu: nr katalogowy 16SKV294 jest produkt TecDoc w ALlegro - marka to ESEN SKV
Produkt TecDoc którego brakuje na Allegro to 59SKV069 gdzie domyślam się, że w TecDoc podana marka to  SKV GERMANY

Te dwa produkty widnieją w katalogu producenta SKV 
https://www.skv.pl/pl/Parts/59SKV069/information/?searchString=59SKV069&partGroup=Zap%C5%82onnik,%20gazowa%20lampa%20wy%C5%82adowcza

https://www.skv.pl/pl/Parts/16SKV294/?searchString=16SKV294&partGroup=Zamek%20pokrywy%20tylnej

**Comment by AureliuszBrussy** [comment]
Dziękuję za kolejne przykłady. Wrócę z informacją, jak tylko to rozwiążemy.

**Comment by PunktAutoCzesci** [comment]
Cześć, wiadomo już coś?

pt., 15 gru 2023, 03:46 użytkownik stale[bot] ***@***.***>
napisał:

**Comment by AureliuszBrussy** [comment]
@PunktAutoCzesci czekam jeszcze na rozwiązanie. Proszę o jeszcze trochę cierpliwości. Wrócę z informacją.

**Comment by PunktAutoCzesci** [comment]
Cześć, są jakieś wieści?

pt., 22 gru 2023, 15:29 użytkownik stale[bot] ***@***.***>
napisał:

**Comment by AureliuszBrussy** [comment]
@PunktAutoCzesci niestety, wciąż brak wieści, czekam jeszcze na ostateczne rozwiązanie sprawy. Jak tylko otrzymam odpowiedź, napiszę w wątku.

**Comment by PunktAutoCzesci** [comment]
Cześć, są jakieś wieści?

**Comment by PrzemyslawLukanowski** [comment]
Cześć, przepraszam za długi czas oczekiwania na rozwiązanie problemu. Czy mógłbyś jeszcze podać listę priorytetowych kategorii, w których występuje ten problem?

**Comment by PunktAutoCzesci** [comment]
Np. motoryzacja -> układ paliwowy -> części montażowe 
nr kategorii 261089
Ale trudno stwierdzić jakie wszystkie, bo nie ma produktu Allegro a to w nim jest informacja o kategorii.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za przykład, przekazałem temat dalej do zespołu odpowiedzialnego za usługę.

**Comment by PunktAutoCzesci** [comment]
Odświeżam

**Comment by Lukasz-Zurek** [comment]
Jeżeli chodzi o produkt 59SKV069 czy DRM0303S - byłe on utworzone przez Sprzedających i nie posiadają one specyfikacji TecDoc, dlatego specyfikacje TecDoc nie będą dla nich dodawane.

Generalnie jest kilka typów problemów, z którymi nasz Serwis obecnie się mierzy. Wylistowałem je w [tym wątku](https://github.com/allegro/allegro-api/issues/8315#issuecomment-1903695688).

**Comment by PunktAutoCzesci** [comment]
Przed zamknięciem tego wątku pozwolę sobie tylko na jeszcze jedno pytanie. 
Czy dobrze rozumiem, że jeśli produkty są już dodane przez użytkowników to nigdy nie będą aktualizowane do zgodnych ze specyfikacją TecDoc? Jak to się ma do wcześniejszego dodawania osobnych produktów TecDoc pomimo tego, że istniały już one w katalogu? Dane z TecDoc są zazwyczaj wyższej jakości niż w te dodane przez użytkowników. Produkty użytkownikó nie posiadają "TecDocSpecyfication" i często brakuje w nich tabeli zastosowania.

**Comment by Lukasz-Zurek** [comment]
W przypadku aktualizacji z bazy TecDoc i otrzymania specyfikacji TecDoc dla istniejącego produktu - zespół odpowiedzialny za tę funkcjonalność, prawdopodobnie decyduje co dalej tj. czy dane te są mergowane. Nam wszystkim zależy na tym, aby produkty posiadały najwyższą jakość. Aczkolwiek sam proces jest poza nami i nie mogę Tobie sprecyzować jak to szczegółowo wygląda m.in. z uwagi na to, że są to informacje wewnętrzne.
