### ISSUE TITLE
Product EAN not returned

### ISSUE THREAD

**Issue by BarnetMichal** [allegro/allegro-api#8081]
Hello,

1)If I search for a product via the endpoint 'sale/products?phrase=4064197475504&mode=GTIN' on the production, the api returns 5 products. Does Allegro allow to have more products with the same GTIN? For EAN 8059696901421 two identical products.
2)The EAN (GTIN) is not returned in the parameters of these products, I thought it must always return it, is that right? 
Thank you.

**Comment by BarnetMichal** [comment]
aha, I asked about EAN in the issue before  #7852  and there I got the answer that EAN is always returned.

**Comment by Lukasz-Zurek** [comment]
It is true, in this thread https://github.com/allegro/allegro-api/issues/7852 my colleague mentioned it in terms of the EAN parameter. We always return it - if it is available. I am sorry but I misunderstood your question - I was thinking more of the EAN as a filter.

**Comment by BarnetMichal** [comment]
@Lukasz-Zurek Aha ok, thanks for info. Is it possible to have more products with the same GTIN (EAN)? On production, it returns more products if I search by EAN, for example for 4064197475498, 8059696901421.
