### ISSUE TITLE
Lista kampanii w Allegro Ads

### ISSUE THREAD

**Issue by PavvelSte** [allegro/allegro-api#8083]
Dzień dobry, 
Czy istnieje możliwość wyłączenia/włączenia kampanii w Allegro ADS poprzez API? Niestety nie mogę tego znaleźć w dokumentacji.

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Niestety nie, nie mamy takiej funkcjonalności w publicznym API. Mamy już taką sugestię dotyczącą utworzenia takich zasobów, pod [tym linkiem](https://github.com/allegro/allegro-api/discussions/4487). Zachęcam Cię do oddania głosu. Co prawda na ten moment nie mamy takich planów, monitorujemy to jednak na bieżąco.
