### ISSUE TITLE
Sandbox - Konto firmowe

### ISSUE THREAD

**Issue by daniel500013** [allegro/allegro-api#8084]
Cześć, proszę o pełną aktywację konta w.rojek@asiston.pl
Chodzi o zatwierdzenie weryfikacji konta i danych firmy.
![image](https://github.com/allegro/allegro-api/assets/30683843/5b60a7ea-06ca-41ed-a55c-2028d1e365d5)
Dzięki :D

**Comment by AureliuszBrussy** [comment]
Aktywowałem Twoje konto.
