### ISSUE TITLE
Error while trying to link Allegro account

### ISSUE THREAD

**Issue by SunkovyChlebiczek** [allegro/allegro-api#8087]
Hello,
I was testing our software for linking allegro account trought api. I got this error:

Nie możemy wyświetlić strony
Numer błędu: e71d0bfb8a2b9102

What is error means and what is the problem?

It is account: jiri.zajicek@codingbear.com/zajdalen

Thanks.

**Comment by Lukasz-Zurek** [comment]
You have received this error because you have used an incorrect redirect_uri which should be identical as in [registered application's](https://apps.developer.allegro.pl.allegrosandbox.pl) data.
