### ISSUE TITLE
Allegro One Punkt - Problem z podjazdem kuriera i protokołem nadawczym

### ISSUE THREAD

**Issue by matcapi** [allegro/allegro-api#8088]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry, 
Klient zgłosił nam problem z nadawaniem paczek za pomocą metody Allegro One Punkt. Odtworzyłem napotykany przez niego błąd sandbox.

1 - Zamówiłem podjazd kuriera za pomocą:
PUT parcel-management/parcel-pickup-request-commands/34163655-e192-485e-a604-562fb85d4956 || trace-id:d5f209034957785

2 - Próbowałem pobrać protokół nadawczy z:
GET https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcels/protocol?parcelId=44f9c8ee-f6b1-48a2-b753-2f82d1888008 || trace-id:752929e6fca3e1b

Dostałem taką odpowiedź:
HTTP 400
{
    "code": "BAD_REQUEST",
    "message": "Allegro carrier does not support generation of protocols",
    "details": null,
    "path": "parcelIds[%s]",
    "userMessage": "Przewoźnik Allegro nie wspiera generowania protokołów"
}

Wydaje mi się, że ten endpoint powinien zwrócić HTTP 204?

Wchodząc do panelu allegro nie jestem w stanie zweryfikować czy podjazd kuriera został poprawnie zamówiony, a gdy próbuję zamówić podjazd kuriera z panelu to dostaję błąd "Status przesyłki jest niepoprawny dla podjazdu" oraz wyświetla się status "Nie udało się zamówić podjazdu". Zakładam, że powodem jest podjazd kuriera zamówiony z API.

Próba pobrania protokołu wyświetla "Request failed with status code 400".
![Screenshot from 2023-12-04 17-17-47](https://github.com/allegro/allegro-api/assets/134065072/3878e2b0-87d1-4061-a601-a6062fd8c4e0)

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Dla wskazanej przesyłki został zlecony już podjazd, dlatego zwracamy na stronie zwracamy błąd.

Jeżeli natomiast chodzi o błąd 400 - konsultuję ten temat z odpowiednim zespołem. Wkrótce wrócę z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
@matcapi Niestety nie. Temat okazał się bardziej skomplikowany, dlatego zespół odpowiedzialny za usługę nadal to weryfikuje. Jak tylko uzyskam jakiekolwiek informacje - dam znać w wątku.

**Comment by matcapi** [comment]
Odświeżam żeby nie przepadło.

**Comment by Lukasz-Zurek** [comment]
@matcapi W ramach aktualizacji chciałbym poinformować, że problem dotyczący odpowiedzi 204 w opisanej sytuacji jest nadal analizowany przez zespół odpowiedzialny za tę usługę. Realizacja może się wydłużyć w czasie, za co z góry serdecznie przepraszam.

Jak tylko uzyskam informacje w tej sprawie, podzielę się nimi w tym wątku.

**Comment by matcapi** [comment]
Odświeżam żeby nie przepadło.

**Comment by Lukasz-Zurek** [comment]
@matcapi Dziękuję. Pamiętamy. Temat nadal rozpoznawany przez zespół od usługi WZA.

**Comment by matcapi** [comment]
Odświeżam żeby nie przepadło.
