### ISSUE TITLE
Temporary unblock account from the API to process orders

### ISSUE THREAD

**Issue by SvenSlijkoord** [allegro/allegro-api#8089]
Hi,

Our account has been blocked and the only way to unblock it is for us to fulfill all orders. However, our order processing is done in our WHM system which is connected to Allegro via the API.
As of now, we currently cannot process any orders because our API connection is blocked.

Is it possible to unblock our account at least for the API so we can actually process the orders.

Many thanks,
Sven

**Comment by Lukasz-Zurek** [comment]
Hello. 

If your account is on Allegro Sandbox, I will be able to unblock it because it is a test environment. Please give me your login then.

But if your case refers to account on the production - please use our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=8b463d9b-b539-4537-a631-a4b68c62582e).

**Comment by SvenSlijkoord** [comment]
Hi @Lukasz-Zurek,

Thank you for the response! 

This regards the production environment. I have already made contact using the contact form but they redirected us to this GitHub page. Is it possible to get our API unblocked in the production environment?

Many thanks,
Sven

**Comment by Lukasz-Zurek** [comment]
@SvenSlijkoord I am sorry that you have been redirected to us. They redirected you incorrectly. We cannot unblock an account in the production environment. Please continue current correspondence and precise that this case refers to your account's sell block only, not API - maybe our customer service thought about Allegro Sandbox account. If you have any problem, please let me know.
