### ISSUE TITLE
REST API order/checkout-forms a stare id zamówienia

### ISSUE THREAD

**Issue by madkot** [allegro/allegro-api#809]
Dzień dobry,
Czy istnieje możliwość pobierania informacji o zamówieniach mając stare id zamówienia (int) w nowym REST API? Jest to kolejna rzecz, która mogła!by być lepiej przewidziana w nowym API i zdecydowanie ułatwić migrację.

Przy okazji zapytam: Dział sprzedaży dostaje maile ze starymi identyfikatorami (aktu zakupowego). Czy tam też po przejściu na nowe API będą nowe id w formacie UUID?

**Comment by PawelTaberski** [comment]
Możesz skorzystać z zasobu, jaki niedawno udostępniliśmy, przy jego pomocy zmapujesz dealId na lineItemsId. Więcej na ten temat [tutaj](https://developer.allegro.pl/news/2018-10-09_Mapowanie_lineItemId_dealId/).
Odnośnie maila nie wiem który dokładnie masz na myśli. Po przejściu w 100% na REST API wszędzie już będą dostępne tylko identyfikatory w nowym formacie.

**Comment by mack3d** [comment]
Dołączam do prośby o mapowanie transactionId po checkout-form(ID).
Maskotki:
Uuid otrzymujesz już od jakiegoś czasu w mailu potwierdzającym płatność (tylko i wyłącznie w tym mailu)

**Comment by madkot** [comment]
Tak jak maxk3d pisze. Najlepiej by było, aby wszędzie obok nowego id transakcji (checkout-form-ID) pojawiały się w api old-transasction-id(nawet tymczasowo do czasu wylaczenia starego API), mapowanie to zawsze kolejne zapytania do api, ale zadowolę się mapowaniem.. @PawelTaberski jest szansa na utworzenie owego mapowania?

**Comment by expondo** [comment]
Dołączam się do tematu.
Obecnie 100% powiązanie starego API z nowym w zakresie pobierania i aktualizowania zamówień nie jest możliwa i sprawia ogromne trudności.

**Comment by PawelTaberski** [comment]
Rozumiem, przekazałem już wcześniej że więcej osób oczekuje takiej funkcjonalności. Jeśli zdecydujemy się wdrożyć takie rozwiązanie poinformujemy o tym w odpowiednim komunikacie.

**Comment by madkot** [comment]
Jakieś wieści?

**Comment by PawelTaberski** [comment]
Tak, jak pisałem jeśli zdecydujemy się wdrożyć takie rozwiązanie, to poinformujemy o tym w dedykowanym komunikacie.
