### ISSUE TITLE
Sanbox - aktywacja konta 

### ISSUE THREAD

**Issue by OrbisSoftwarePolska** [allegro/allegro-api#8092]
Prosze wkoncu zespół allegro o aktywacje konta sanbox: biuro@orbis-software.pl

Dziekuje.

**Comment by Lukasz-Zurek** [comment]
@OrbisSoftwarePolska Aktywowałem wskazane konto.

**Comment by romigrabarz** [comment]
Proszę również o aktywację konta sandbox: rg@acenter.nysa.pl
Zmieniłem konto na firmowe aby móc edytować oferty i w dalszym ciągu mam komunikat: Weryfikujemy dane Twojej firmy. Proszę o przyspieszenie tego procesu na sandboksie, np. wyłączyć ten etap aby dało się jednym kliknięciem zmienić na firmowe i testować.

**Comment by Lukasz-Zurek** [comment]
@romigrabarz Wskazane konto ma nadal status zwykłego. W jaki sposób zmieniałeś konto na firmowe? Opcja przekonwertowania konta dostępna jest w [ustawieniach konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by romigrabarz** [comment]
Kliknąłem w podany link i wybrałem opcje **Zmień na konto firmowe**, po czym dalej wybrałem **Zweryfikuj dane firmy** - i tutaj mam wciąż komunikat że **Weryfikujemy dane Twojej firmy.**

**Comment by Lukasz-Zurek** [comment]
@romigrabarz Z tym kontem jest coś nie tak, przez co w naszej bazie nie może uzyskać statusu firmowego. Przepraszamy za te utrudnienia.

Czy nie będzie to dla Ciebie problem jeśli zarejestrujesz nowe konto firmowe na sandboxie? Musiałbyś przejść jeszcze przez konfigurację wypłat oraz przelew poprzez symulator płatności. Ja natomiast ze swojej strony pomogę w procesie aktywacji.

**Comment by Lukasz-Zurek** [comment]
@romigrabarz Dziękuję! Konto jest już w pełni aktywne :)
