### ISSUE TITLE
Zarządzanie przesyłkami

### ISSUE THREAD

**Issue by SLUCZAS** [allegro/allegro-api#8095]
Mam problem
Pracuję na automatycznym tworzeniem etykiet przewozowych dla Allgro One. 
Napotkałem pierwszy problem gdzie miałem komunikat brak dostępu
![image004](https://github.com/allegro/allegro-api/assets/143815471/47bbb041-7a4c-426a-a6d1-4d3cc9795a0d)
Z tym sobie na szczęscie poradziłem, trzeba było na stronie https://apps.developer.allegro.pl/  dodać uprawnienia allegro:api:shipments:read oraz allegro:api:shipments:write
Niestey po próbie zwrócenia listy dostępnych form dostawy pojawia się taki komunikat
![image001](https://github.com/allegro/allegro-api/assets/143815471/f691e6da-8010-4024-9cc3-841f9b19eb58)
W scopie mam też dodane shipments:write, shipments:read
O co chodzi tym razem?

**Comment by SLUCZAS** [comment]
Jedynie to znalazłem:  "jti": "ecacd2e4-aeb7-4172-99e9-994b3ffd87f7"

 
Nie wiem czy to jest to trace id bo to razem z token przychodzi w tej strukturze.

**Comment by Lukasz-Zurek** [comment]
@SLUCZAS Wszystko wskazuje na to, że używasz tokena wygenerowanego w ramach autoryzacji typu client_credentails. Taki token nie posiada kontekstu użytkownika, dlatego w odpowiedzi otrzymujesz błąd. 

Aby prawidłowo pobrać listę dostępnych usług dostawy, skorzystaj z autoryzacji typu[ code](https://developer.allegro.pl/auth/#app) lub[ device](https://developer.allegro.pl/auth/#DeviceFlow). W naszej[ dokumentacji](https://developer.allegro.pl/documentation/#) znajdziesz odpowiednie oznaczenia, jakiego rodzaju autoryzacji musisz użyć, aby otrzymać prawidłową odpowiedź z danego endpointu:

- bearer-token-for-user - code lub device flow,
- bearer-token-for-application - client credentials.

**Comment by SLUCZAS** [comment]
dziękuję bardzo za pomoc, już działa :)
