### ISSUE TITLE
Listing Products via Channel Advisor

### ISSUE THREAD

**Issue by SonovaConsumerHearing** [allegro/allegro-api#8097]
Hi team, We're trying to list our products via Channel Advisor on Allegro. But we're keep receiving the error message "Error from Allegro PL: Missing Implied Warranty Definition for name: General Warranty information (id ProductFailedDataValidation)". We have already entered the General Warranty information within Allegro. Do you know how we can get rid of the error message?

**Comment by Lukasz-Zurek** [comment]
Please contact Channel Advisor support. As I can see - the problem refers to Implied Warranty Definition which you are trying to use in the offer as there is no implied warranty information with the name: "General Warranty information" in your Allegro account's settings.

**Comment by SonovaConsumerHearing** [comment]
Hi team,
But I think we have set it up as you can see in the screenshot? Or what setting are you referring to? Could you share an URL? 

![allegro screen](https://github.com/allegro/allegro-api/assets/152997220/5ed9543b-9506-4bc3-ab54-724ad01b512a)

**Comment by Lukasz-Zurek** [comment]
The problem refers to (as we call it in API) the "implied warranty":

https://allegro.pl/moje-allegro/sprzedaz/warunki-reklamacji

In our My Allegro Tab, we call it "complaints terms": https://allegro.pl/moje-allegro/sprzedaz/warunki-reklamacji

which may be misleading.
