### ISSUE TITLE
ConstraintViolationException.NoDuplicateIds

### ISSUE THREAD

**Issue by jakub-kanski** [allegro/allegro-api#8098]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

 Unfortuntely we cannot activate any offer using sale/offer-publication-commands endpoint.  We receive ConstraintViolationException.NoDuplicateIds error. Our problem started occuring today, but we havent changed anything in our code, so I think the issue is on the server side.

Request url: PUT 'https://api.allegro.pl/sale/offer-publication-commands/87d2ffe9-9376-11ee-8a8c-803253b6e3f6'
Request body: {"offerCriteria": [{"offers": [{"id": "14836360639"}], "type": "CONTAINS_OFFERS"}], "publication": {"action": "ACTIVATE"}}

Transaction response: {'tasks': [namespace(offer=namespace(id='14836360639'), message='Could not change offer publication status. Dany parametr możesz podać tylko raz.', status='FAIL', scheduledAt='2023-12-05T15:09:09.258Z', finishedAt='2023-12-05T15:09:09.25Z', field='publication', errors=[namespace(code='ConstraintViolationException.NoDuplicateIds', message='This parameter can be entered only once.', details=None, path='parameters', userMessage='Dany parametr możesz podać tylko raz.')])]}

**Comment by Lukasz-Zurek** [comment]
Thank you for the details. I have already forwarded this case to another department. I will be back with some more information.
