### ISSUE TITLE
Activation of Sales in Sandbox enviroment.

### ISSUE THREAD

**Issue by GeertBraakman** [allegro/allegro-api#8099]
Hello, 

I am trying to create an offer on the allegrosandbox enviroment,  but when i try to do this i get a http 403. `AccessDeniedException`

To fix this I want to activate my account, but when i try to do that I cannot access the Payment Simulator.

I can get to the following screen:
![afbeelding](https://github.com/allegro/allegro-api/assets/36223190/389564c5-6916-4dec-9f53-c84be7abe257)

But when i press a payment method it will say that the website does not exists. and i get the message `Server Not Found`
http://c2c-payu-simulator.dh-test.qxlint/simulator/orders/01ecce0d-ded3-40f6-b6ca-8fa72a5012ad

Am I using the wrong way to activate my account on the sandbox enviroment? Or is the Payment simulator not working correctly for me?

My clientId is `106780032`

Thanks in advance,
Geert Braakman - Covadis

**Comment by SimasBir** [comment]
Hi, 
Please activate Client:106777804 as well.

**Comment by Lukasz-Zurek** [comment]
@GeertBraakman I think that it could be a temporary problem with the payment simulator for this particular account. As I see - your account is not a business account. I suggest converting it to the business account, then - I think - there won't be a problem to activate it. You can do it [here](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

After that you will have to go to [Payouts settings](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat) and use our payment simulator to finish the process.

Please let me know if any additional problem occurs.

**Comment by Lukasz-Zurek** [comment]
> Hi, Please activate Client:106777804 as well.

I can also suggest converting this account to the business account, to be able to create offers, manage orders, etc. You can do it [here](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

After that please go to [Payouts settings](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat) and use our payment simulator to finish the process.

**Comment by GeertBraakman** [comment]
> @GeertBraakman I think that it could be a temporary problem with the payment simulator for this particular account. As I see - your account is not a business account. I suggest converting it to the business account, then - I think - there won't be a problem to activate it. You can do it [here](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).
> 
> After that you will have to go to [Payouts settings](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat) and use our payment simulator to finish the process.
> 
> Please let me know if any additional problem occurs.

Thank you for your help, I transfared to a buisness account and after that i could finish the payment simulator. 
I just filled in all fake details, when can I expect these to be confirmed?

**Comment by Lukasz-Zurek** [comment]
@GeertBraakman Yes, I have already activated your account :)

**Comment by Lukasz-Zurek** [comment]
@SimasBir Everything is good now - I have activated your account :)

**Comment by GeertBraakman** [comment]
> @GeertBraakman Yes, I have already activated your account :)

@Lukasz-Zurek I finished the setup and now I can list orders through the website. 

But now I want to create offers From within our Inventory Management Software. And for that I need to use 
Dynamic Client Registration, I think. The application will run as a Background Task in an On-Premis windows server. So there is no-way for the user to authenticate the application themselfs. 

For this, how can i get a software Identifier on the the SandBox enviroment?
