### ISSUE TITLE
Prośba o aktywacje konta

### ISSUE THREAD

**Issue by cichyraj** [allegro/allegro-api#810]
Dzień dobry,
proszę o aktywacje konta w Sandbox
mail: biuro@cichyraj.pl
login: arekcichy

Pozdrawiam

**Comment by PawelTaberski** [comment]
Aktywowałem konto, ale aby sklep był aktywny musisz w zakładce moje allegro wystartować proces i wysłać wniosek, inaczej nie mogę ręcznie zatwierdzić takiego konta.
