### ISSUE TITLE
Post/putch requests limits

### ISSUE THREAD

**Issue by sherstiukarkadiy** [allegro/allegro-api#8100]
I have many products to putch daily, most of them has different price and stock quantity so I can't use PUT for change this information, at one moment I start see errors like ConnectionError, as I understand that's because I made too much requests, but I can't find this limits anywhere. Can you please tell me what is the requests limit for posting or putching offers?

**Comment by Lukasz-Zurek** [comment]
In Allegro REST API (production and test) there is one main limit imposed on Client ID - 9000 requests per minute.

You can find more information about our limiting right [here](https://developer.allegro.pl/tutorials/basic-information-VL6YelvVKTn#limiting-the-number-of-queries-limits).

But there are some other specific limits per resources. Please read more in [our tutorial](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#limity).

**Comment by sherstiukarkadiy** [comment]
ok, yeah, I read this information, but now I send just 5000 requests per minute and get to block with ConnectionError, why it can refused?

**Comment by Lukasz-Zurek** [comment]
@sherstiukarkadiy Please send me a trace-id where you receive an error - I will check our logs.

**Comment by sherstiukarkadiy** [comment]
HTTPSConnectionPool(host='api.allegro.pl', port=443): Max retries exceeded with url: /sale/product-offers/14790708607 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1258f6320>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

 /sale/product-offers/14790708607  - for example

**Comment by sherstiukarkadiy** [comment]
> @sherstiukarkadiy Please send me a trace-id where you receive an error - I will check our logs.

HTTPSConnectionPool(host='api.allegro.pl', port=443): Max retries exceeded with url: /sale/product-offers/14790708607 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1258f6320>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

/sale/product-offers/14790708607 - for example

**Comment by sherstiukarkadiy** [comment]
2c1df3b19ce9a4d3
aaf3cc8d371774e5
look please on this trace-id, I still have this error but I make not more than 3-5 thousands requests per minute

**Comment by sherstiukarkadiy** [comment]
> @sherstiukarkadiy I have checked the logs and I don't see any 429 errors. Trace-id would be useful to confirm that.
> 
> Another thing is the fact that our specific API resources (on sale/product-offers/ route) have a mechanism that limits the number of requests submitted by a given user. We use the Leaky Bucket algorithm. [More](https://developer.allegro.pl/tutorials/basic-information-VL6YelvVKTn#limiting-the-number-of-queries-limits) about it.
> 
> But as I have already written - I do not see any 429 responses in the logs.

2c1df3b19ce9a4d3
aaf3cc8d371774e5
look please on this trace-id, I still have this error but I make not more than 3-5 thousands requests per minute

**Comment by Lukasz-Zurek** [comment]
@sherstiukarkadiy I can only see an error for trace-id: aaf3cc8d371774e5, where we have returned:

`422 Unprocessable Entity. Errors: Errors{errors=[Error{code='ConstraintViolationException.MissingRequiredParameters', message='Missing required parameters: 18718, 18720, 214822, 214818', details='ConstraintViolationException.MissingRequiredParameters', path='parameters', userMessage='Uzupełnij parametry obowiązkowe: Rodzaj, Typ, Rodzaj produktu, Kolor.'}]}.`

So it is not related to any limits. As I have checked some more logs, we do not return any 429 but in the last 7 days you had had a lot of 422 errors. Please check them out closely.

**Comment by herrAlison** [comment]
I tried everything, but unfortunately without success,

import requests

with requests.session() as session:

url = 'https://register.fdsinstitut.com/ext/index.php'

headers = {}
cookies = {}
donnees = {}

reponse = session.post(url, headers=headers, cookies=cookies, data=donnees)

print(reponse.text)

**Comment by Lukasz-Zurek** [comment]
@herrAlison Could you describe your problem and send some trace-ids? Then I will be able to check the logs and verify your case.
