### ISSUE TITLE
Problem with dispatch. WZA 

### ISSUE THREAD

**Issue by jwmbb** [allegro/allegro-api#8102]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień Dobry,
Mamy Problem z nadaniem przesyłki z jednego konta. 
Czy mogę prosić o pomoc w znalezieniu przyczyny? 
UUID: c80d6bbd-a7af-40c6-8269-680556402cad
UUID: 1a084ad0-5c4b-48bc-8eb3-4c0a5dc67623
Problem występuje na wielu zamówieniach z tego konta i przesyłam tylko 2 przykłady 
Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
@jwmbb Przekazaliśmy już wcześniej zgłoszenie do odpowiedniego zespołu, który analizuje problem. Proszę o cierpliwość.

**Comment by jwmbb** [comment]
![WeChat_Ug6zZhfYPf](https://github.com/allegro/allegro-api/assets/110170769/7cccd535-2100-4a6d-b2cd-e1d3f4b26829)
rozumiem że chodzi o adres w tym miejscu? jeśli tak to mamy ustawiony

**Comment by Lukasz-Zurek** [comment]
@jwmbb Dziękuję. Czy w [książce adresowej](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia) adres wyświetla się prawidłowo?

**Comment by jwmbb** [comment]
problem rozwiązany
