### ISSUE TITLE
Problem z nadaniem przesyłki PROCESSING_ERROR

### ISSUE THREAD

**Issue by kdabek** [allegro/allegro-api#8103]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Po wysłaniu paczki za pośrednictwem `Allegro Kurier Pocztex` dostajemy w odpowiedzi:

```
{
   "commandId":"998f299d-457d-4b97-8f74-240089f5da73",
   "status":"ERROR",
   "errors":[
      {
         "code":"PROCESSING_ERROR",
         "message":"Problem with dispatch. Contact us, and we will help as soon as possible.",
         "details":null,
         "path":null,
         "userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."
      }
   ],
   "shipmentId":null
}
```

Trace Id: 1ce6ace51fc8cd4e

**Comment by AureliuszBrussy** [comment]
@kdabek poprawiliśmy to - problem nie powinien już występować.
