### ISSUE TITLE
Zamykanie aukcji po stronie allegro.

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#8104]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Mam problem z automatycznym zamykaniem aukcji po stronie allegro. W celu aktualizacji aukcji pobieram wszystkie zamknięte aukcje z zasobu 
/sale/offers?publication.status=ENDED

Nr aukcji:
13322584051
13410206602
13129253033

Jeśli stwierdzicie że te aukcje są zamykane przez nas to prosiłbym o zwrotkę jakim requestem są one zamykane. Bo po naszej stronie nie widzę żadnych requestów zamykających te aukcje.

**Comment by DamianKAtomStore** [comment]
To jest konto naszego klienta. Jedynie proszę o podanie requestu który kończy te aukcje i kiedy został wysłany. Nie są to dane w żadnym stopniu wrażliwe.

**Comment by AureliuszBrussy** [comment]
@DamianKAtomStore oferta mogła być zakończona potencjalnie z poziomu innej aplikacji. Nalegam, aby to klient zgłosił się z tym zapytaniem, wtedy udzielimy informacji.
