### ISSUE TITLE
Zdublowana wartość Description paczek

### ISSUE THREAD

**Issue by piojoch** [allegro/allegro-api#8105]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Witam,

Tworzę przesyłkę w środowisku testowym za pomocą endpointu https://developer.allegro.pl/documentation/#operation/createNewParcel, przekazując do niego listę trzech paczek (Items). Jako Description podaję unikalne wartości.

Następnie sprawdzam status utworzonej przesyłki https://developer.allegro.pl/documentation/#operation/getParcelCreationStatus oraz pobieram listę paczek https://developer.allegro.pl/documentation/#operation/getParcelDetails.

Na liście paczek (Items) pobranych ostatnim endpointem (https://developer.allegro.pl/documentation/#operation/getParcelDetails), każda paczka ma ten sam Description.

Wszystko odbywa się w środowisku testowym. Jakiś czas temu robiłem to samo na produkcji i nie było takich problemów. Każda paczka miała Description taki jaki wysłałem podczas tworzenia przesyłki.

Czy problem występuje tylko na środowisku testowym? Czy coś się zmieniło w API?

Pozdrawiam,
Piotr

**Comment by AureliuszBrussy** [comment]
Czy jesteś w stanie podać przykładowe trace-id (lub commandId) takiego wywołania, gdzie tworzysz taką przesyłkę na Sandboxie? Sprawdzimy to.

**Comment by AureliuszBrussy** [comment]
Dziękuję, potwierdzam ten problem. Zgłosiłem to do zespołu zajmującego się Wysyłam z Allegro. Wrócę z informacją.

**Comment by piojoch** [comment]
Mam potrzebę powiązania paczek które nadaje z tymi które są nadane, np. w celu przypisania numerów paczek (Waybill).
W jaki sposób mogę to osiągnąć? Czy jest jakieś inne pole dla którego wartość mogę przekazać na etapie tworzenia przesyłki i później pobrać tą wartość na etapie wywołania getParcelDetails?

**Comment by AureliuszBrussy** [comment]
Nie ma obecnie takiego pola.

**Comment by piojoch** [comment]
Czy możemy przyjąć że kolejność w jakiej podam paczki podczas nadania będzie taka sama jak w getParcelDetails?

**Comment by AureliuszBrussy** [comment]
@piojoch jeszcze potwierdzam to z zespołem odpowiedzialnym za Wysyłam z Allegro. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@piojoch potwierdzam, że lista paczek zawsze będzie w dokładnie takiej samej kolejności.

**Comment by piojoch** [comment]
Super, w takim razie skorzystam z tej zależności. Dziękuję :)
