### ISSUE TITLE
Przekazanie bazy produktów za pomocą API

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#8107]
Dzień dobry,
pisze w sprawie tego artykułu, który otrzymałem od supportu - https://allegro.pl/dla-sprzedajacych/jak-mozesz-przekazac-nam-swoja-baze-danych-produktow-YWqLnDRxPu8 . Niestety oprócz przesłania mi tego linku, okazuje się, że nie są w stanie nic więcej zrobić i odsyłają mnie tutaj...

Chciał bym przekazać Państwu bazę produktów wystawiając własne API, zgodnie z opisem w ostatnim akapicie
![image](https://github.com/allegro/allegro-api/assets/5887720/1f870af8-910d-4ece-ba41-f0fd0b36766b)

Prosił bym o informację gdzie i w jakiej formie mogę się zgłosić, abyście zaczęli Państwo pobierać dane o produktach z naszej bazy.

**Comment by AureliuszBrussy** [comment]
To nie jest proces związany z publicznym API, nie zajmujemy się tym. Kontaktowałeś się może pod adres: brand-data@allegro.pl?

**Comment by rasskabak** [comment]
"To nie jest proces związany z publicznym API," - nie żebym nie wspominał tutaj osobie, która mnie do Was wysłała ;)
Kontaktowałem się, pisaliśmy chwilę, a gdy prawie doszło do konkretów, to od miesiąca nie mam żadnej odpowiedzi. Wczoraj puściłem "przypominajkę" i dostałem autoresponder o urlopie. Może w przyszłym tygodniu coś się w końcu ruszy...
