### ISSUE TITLE
Wyszukiwanie ofert a uwierzytelnianie

### ISSUE THREAD

**Issue by mzamorski** [allegro/allegro-api#811]
Tworzę aplikację desktopową i mam pytanie. Czy można wyszukiwać oferty (publiczne informacje dostępne na platformie) bez konieczności logowania się na konkretne konto Allegro? W jednej z dyskusji mowa była o:

> Token można uzyskać na trzy sposoby/:
> ...
> 2. Token w aplikacji - aplikacja korzysta tylko ze swojego clientId i secret i dostaje token, w którym nie ma > userId, z takim tokenem nie może pobrać danych w imieniu użytkownika, ma dostęp tylko do ‘otwartych > danych’, np. lista metod dostaw lub lista ofert.

[https://github.com/allegro/allegro-api/issues/388#issuecomment-405280940](url)

Jak zatem uzyskać w takim przypadku token oraz czy konieczne będzie obsłużenie 'redirect_uri' na localhost?

**Comment by PawelTaberski** [comment]
W takim wypadku pobierasz token tylko na podstawie clientID, secret i flow client_credentials. Token nie ma wtedy kontekstu klienta, i masz dostęp tylko do publicznych metod jak listing. Więcej na ten temat znajdziesz w wątku #680, gdzie poruszaliśmy tą kwestię, co prawda w odniesieniu do problemów z dostępem do niepublicznych zasobów, ale rozmawialiśmy o tym.
