### ISSUE TITLE
Nadawanie przesyłek InPost

### ISSUE THREAD

**Issue by akonopka11** [allegro/allegro-api#8111]
Dzień dobry,
Pobieram metody dostawy z tego adresu "parcel-management/delivery-services", ale nie widzę tam metod dla InPost. Chcielibyśmy nadawać paczki przez API zamiast przez Managera Paczek? Czy to jest możliwe? Coś musimy gdzieś włączyć, żeby nam się ta metoda pojawiła?
Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
Umowa Allegro Inpost wymaga dodania w [ustawieniach Wysyłam z Allegro](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia) umowy własnej i wybrania opcji "Używaj oferty dla sprzedawców Allegro". Wtedy dopiero pojawi się odpowiednia usługa dostawy. 

Dodam tylko, że jeżeli planujesz rozpocząć korzystanie z Wysyłam z Allegro - zintegruj się z nowymi zasobami z grupy [Shipment management](https://developer.allegro.pl/documentation#tag/Shipment-management). Zasoby Parcel management są oznaczone jako Deprecated i zostaną całkowicie wyłączone w czwartym kwartale 2024.

**Comment by akonopka11** [comment]
Dzień dobry,
Nadal trochę nie do końca rozumiem. My mamy już umowę własną z InPostem, generujemy sobie etykiety przez ich API bezpośrednio. Allegro natomiast podobno negocjuje umowy z przewoźnikami. Znalazłam ten formularz do dodawania umowy własnej, ale mnie nie chodzi o umowę własną, tylko o tę negocjowaną przez Allegro. Chodzi o metody wysyłki "Allegro Kuriert24 InPost" oraz o "Allegro Kuriert24 InPost pobranie". Tam podobno te etykiety inaczej wyglądają (generowane przez https://manager.paczkomaty.pl/). Nawet po dodaniu tej umowy własnej dla InPost też z resztą nie widzę, żeby się pojawiły nowe metody wysyłki pod tym adresem "parcel-management/delivery-services".

**Comment by akonopka11** [comment]
Jeszcze raz podkreślę, że nam nie chodzi o umowę własną.

**Comment by akonopka11** [comment]
To chyba Allegro Mix by było.

**Comment by AureliuszBrussy** [comment]
@akonopka11 aby korzystać z metod InPostu sprzedający musi [dodać umowę własną InPost](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia?sellerId=49442241) i podczas dodawania zaznaczyć checkbox "Używaj oferty dla sprzedawców Allegro".

**Comment by akonopka11** [comment]
Nam nie chodzi o umowę własną, poza tym to nie zadziałało.

**Comment by akonopka11** [comment]
Nie pojawiają nam się żadne dodatkowe metodyt wysyłki, w tym sensie to nie działa.

"Używaj oferty dla sprzedawców Allegro
Zaznacz, jeśli chcesz rozliczać się z przewoźnikiem na wynegocjowanych przez nas warunkach w ramach [sposobu rozliczeń Allegro Mix.](https://allegro.pl/dla-sprzedajacych/jak-rozliczac-koszty-dostaw-na-allegro-m0jYAdk54Sr#metody-rozliczane-sposobem-allegro-mix)"
Tu rzeczywiście piszą o warunkach wynegocjowanych przez Allegro, czyli wygląda, że rzeczywiście powinniśmy tu dodać tę własną umowę. Ale to nie pomaga.

**Comment by AureliuszBrussy** [comment]
@akonopka11 prosiłbym w takim razie o kontakt w tej sprawie przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) po zalogowaniu się do konta, którego ten problem dotyczy i opisanie problemu.

**Comment by akonopka11** [comment]
To był jednak mój błąd. Ale mam teraz inny problem. Konto produkcyjne, sprawdzanie statusu przesyłki ("commandId": "3a96e068-5b29-4060-bc33-f4da6b10cc3c"), mam taki błąd:
{
    "id": "3a96e068-5b29-4060-bc33-f4da6b10cc3c",
    "errors": [
        {
            "code": "CREDENTIALS_ID_NOT_PROVIDED",
            "path": "client credentials",
            "details": "Seller didnt provide credentials for own delivery Method",
            "message": "Seller didnt provide credentials for own delivery Method",
            "userMessage": "Wybrana metoda dostawy nie obsługuje tego zamówienia"
        }
    ],
    "status": "ERROR",
    "parcelId": null
}

Mam dodaną umowę własną i wprowadzony token (sam token, może tam trzeba ID podać też? i np. oddzielić dwukropkiem?)

**Comment by AureliuszBrussy** [comment]
Zwróć uwagę, że gdy odczytasz [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation#operation/getAvailableDeliveryServices), dla umów własnych w id usługi po znaku `#` zwracamy identyfikator umowy własnej. Do nadania musisz użyć pełne id zwrócone w odpowiedzi dla [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation#operation/getAvailableDeliveryServices).
