### ISSUE TITLE
Typy w getProductOffer - które pola są zawsze zwracane a których może nie być lub będą null'ish? 

### ISSUE THREAD

**Issue by itav** [allegro/allegro-api#8112]
Cześć, 

To właśnie jak to jest z tymi typami w zwrotce z getProductOffer?
https://developer.allegro.pl/documentation#operation/getProductOffer

Zakładam, że któreś pola zawsze mają jakąś wartość np. id. 
W dokumentacji nie ma tej informacji albo nie potrafię tego dostrzec, a może macie jakieś gotowe typy (java, ts) ? 

Dzięki z góry, pozdrawiam

**Comment by itav** [comment]
no tak, dla przykładu czy odpowiedz z getProductOffer na oferty która nie ustawionego np. pola name może być: 
`
{
  id: 123,
  name: null,
  ...
`

czy w przypadku kiedy wartość jest nie ustawiona to poprostu nie ma tego pola w json ? 
`
{
  id: 123,
  ...
`
i tak odnośnie wszystkich możliwych pól w tym endpointcie.

**Comment by AureliuszBrussy** [comment]
Dziękuję za sugestię, przyjrzymy się temu w kontekście dokumentacji. Dam znać, jeśli wprowadzimy jakieś zmiany.
