### ISSUE TITLE
Aditional marketplace own description and title

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#8114]
Hi all, 

we are working on the implementation of additional storefronts to our app and we were wondering if it is possible to send our own translation of the title and description or if the only possibility is to use the automatic translation from Allegro. In the FAQ section here: https://developer.allegro.pl/tutorials/listing-and-managing-offers-on-foreign-marketplaces-7GndGjeAATn#displaying-offers-on-additional-marketplaces is mentioned: 
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/224fb1e5-5456-4cc0-b05e-8fd804cb6533)

But I did not find anywhere, if it is also possible to send our own title and description for the additional marketplace. If it is possible, where is it described, how to send this information to Allegro? 

Thank you in advance for your help! 

All the best, 

Dominika

**Comment by AureliuszBrussy** [comment]
Hi Dominika. Yes, you can add your translations and manage them freely. You can read more about this in [our guide](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#offer-translations). [Here in the documentation](https://developer.allegro.pl/documentation#tag/Offer-translations) are endpoints you can use.
