### ISSUE TITLE
Źle zmapowane parametry TecDOc

### ISSUE THREAD

**Issue by PunktAutoCzesci** [allegro/allegro-api#8116]
Strona zabudowy w produkcie TecDoc
'Febi Bilstein 174853 Klamka drzwi'
'ef164941-235a-48e5-98e1-c6e23b1c21ff'
jest źle zmapowana.  

name:
'Strona zabudowy'
values:
(1) ['zewnętrzny']
0:
'zewnętrzny' 

a powinno być:
Strona zabudowy: z przodu, 
Strona zabudowy: z prawej

**Comment by AureliuszBrussy** [comment]
Błędy w produkcie możesz zgłosić np. [w formularzu](https://allegro.pl/moje-allegro/sprzedaz/produkt/zglos-blad/ef164941-235a-48e5-98e1-c6e23b1c21ff). Udostępniamy też możliwość zgłaszania propozycji zmian w produktach za pomocą [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation#operation/productChangeProposal).

**Comment by PunktAutoCzesci** [comment]
Ja zgłaszam źle zmapowany parametr z katalogu TecDoc. Dział katalogu
produktów allegro nie wprowadza zmian do parametrów TecDoc.
Z resztą chodzi o sprawdzenie procesu mapowania a nie o poprawkę tylko
jednego produktu.

pon., 11 gru 2023, 11:47 użytkownik AureliuszBrussy <
***@***.***> napisał:

**Comment by AureliuszBrussy** [comment]
Dziękuję, aktualnie wartość wygląda na prawidłową, mapowanie zostało poprawione.
