### ISSUE TITLE
Opennet API cannot process request

### ISSUE THREAD

**Issue by Pawelpwg** [allegro/allegro-api#8117]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [ X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzisiaj od rana leci "Opennet API cannot process request" przy pobieraniu statusu

2023-12-11 08:45:23,742 [ 10 ] INFO Main Logger - [ ITSmart.Kurier.Allegro.OneBox.AllegroOneBoxFacade ]: AllegroRequest: {
  "serviceId": "0c7805b4-1bcc-4dad-98c4-b3146fe9f54a",
  "receiver": {
    "address": {
      "street": "Jestřebí 42",
      "postCode": "47161",
      "city": "Jestřebí",
      "countryCode": "CZ",
      "country": null
    },
    "email": "rm6o44bq8c+d07438c9@allegromail.pl",
    "name": "Martin ",
    "company": "",
    "phone": "+420722948421",
    "pointId": null
  },
  "pickup": {
    "address": {
      "street": "MALAWA ",
      "postCode": "36-007",
      "city": "Krasne",
      "countryCode": "PL",
      "country": null
    },
    "email": "biuro@",
    "name": "LAVI spolka",
    "company": "LAVI Sp. z o.o.",
    "phone": "731838701",
    "pointId": null
  },
  "items": [
    {
      "dimensions": {
        "height": {
          "value": 30,
          "unit": "CENTIMETER"
        },
        "width": {
          "value": 30,
          "unit": "CENTIMETER"
        },
        "depth": {
          "value": 30,
          "unit": "CENTIMETER"
        }
      },
      "weight": {
        "value": "2.00",
        "unit": "KILOGRAM"
      },
      "description": "Client:117407455",
      "value": {
        "amount": "1172.00",
        "currency": "CZK"
      },
      "type": "PACKAGE",
      "waybill": null
    }
  ],
  "type": "PACKAGE",
  "label": null,
  "additionalServices": null
} } "id": "3e8bc385-5365-44e8-bc17-791f68ac8b07", "parcelId": null, "status": "ERROR", "errors": [
  {
    "code": "BAD_REQUEST",
    "message": "Opennet API cannot process request",
    "details": null,
    "path": "",
    "userMessage": "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."
  }
] }

**Comment by MartaNowaczyk** [comment]
Ostatnio występowały podobne problemy po stronie Opennetu - pomagało ponowienie. Daj znać, czy jak powtórzysz request, problem nadal występuje.

**Comment by Pawelpwg** [comment]
kilka razy probowalem u klienta i wracalo to samo, ale to bylo rano

**Comment by MartaNowaczyk** [comment]
Gdybyś nadal miał problemy, daj znać.
