### ISSUE TITLE
[Allegro Czechy ] Nie otrzymujemy informacji jaka prowizja powinna wynieść dla danego produktu i nie dolicza jej do ceny produktu

### ISSUE THREAD

**Issue by DanielCyran** [allegro/allegro-api#8118]
Podczas wysyłania produktów do Allegro Czechy wystepuje problem gdzie po API nie otrzymujemy informacji jaka prowizja powinna wynieść dla danego produktu i nie dolicza jej do ceny produktu. Dla rynku polskiego działa prawidłowo.
Przykłady:
Rynek polski - prowizja poprawnie doliczona,
ID Allegro: 2791f590-7eed-11ee-b80f-a517dddc05cb
Aukcja: https://allegro.pl/oferta/vacuum-acc-cleaning-liquid-500ml-awh9-dreame-14649242709
**Rynek czeski - prowizja błędnie doliczona**
ID Allegro: 76bd9811-8080-11ee-abca-e56123a36358
Aukcja: https://allegro.cz/nabidka/obal-pb-verse-629-634-cerny-14661867122

**Comment by MartaNowaczyk** [comment]
Potrzebuję więcej szczegółów do weryfikacji. Podaj proszę trace-id dla przypadku, w którym występuje ten problem. Rozumiem, że korzystasz z kalkulatora opłat?

**Comment by DanielCyran** [comment]
@MartaNowaczyk 
Odpytujemy o zamówienie:
https://api.allegro.pl/billing/billing-entries?order.id=32c74150-95c1-11ee-bcd1-1d97ca0ceb42
Odpowiedź z Allegro:
{
    "billingEntries": []
}
(brak prowizji)
trace-id: 269cf44ee0b5fe2d

**Comment by MartaNowaczyk** [comment]
Jeśli zamówienie dotyczy innego serwisu, niż serwis bazowy, powinieneś dodać do swojego zapytania dany serwis, w tym wypadku `"marketplaceId=allegro-cz",` abyśmy zwrócili historię operacji billingowych. Więcej informacji w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-sprawdzic-oplaty-nn9DOL5PASX#historia-operacji-billingowych).
