### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by nwaworek** [allegro/allegro-api#8119]
Bardzo proszę o aktywację 2 kont sandbox (id poniżej) tj:

1. 106787425
2. 106787380

Niestety pomimo poprawnego adresu i wykonania kroków jak w poradniku: https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#srodowisko-testowe konta mają status nieaktywnych

**Comment by Lukasz-Zurek** [comment]
@nwaworek Rozumiem. Aktywowałem już konto.

**Comment by nwaworek** [comment]
@Lukasz-Zurek Bardzo dziękuję. Ticket oczywiście do zamknięcia. Konto jest aktywne :)

**Comment by nwaworek** [comment]
@Lukasz-Zurek jeszcze jedno pytanie. Uzyskałem token:
`{
  "scope": [
    "allegro:api:orders:read",
    "allegro:api:fulfillment:read",
    "allegro:api:profile:write",
    "allegro:api:sale:offers:write",
    "allegro:api:fulfillment:write",
    "allegro:api:billing:read",
    "allegro:api:campaigns",
    "allegro:api:disputes",
    "allegro:api:sale:offers:read",
    "allegro:api:bids",
    "allegro:api:shipments:write",
    "allegro:api:orders:write",
    "allegro:api:ads",
    "allegro:api:payments:write",
    "allegro:api:sale:settings:write",
    "allegro:api:profile:read",
    "allegro:api:ratings",
    "allegro:api:sale:settings:read",
    "allegro:api:payments:read",
    "allegro:api:shipments:read",
    "allegro:api:messaging"
  ],
  "allegro_api": true,
  "iss": "https://allegro.pl.allegrosandbox.pl",
  "exp": 1702338251,
  "jti": "5dca05da-5d2e-443d-b9f0-6047052597e6",
  "client_id": "a3e49f4769444d33aba3cd4ac171228f"
}`

jak widać mam przyznany scope: "allegro:api:sale:offers:write", jednak w odpowiedzi otrzymuję: 

`{
    "errors": [
        {
            "code": "AccessDeniedException",
            "message": "Authorization error.",
            "details": null,
            "path": null,
            "userMessage": "No access."
        }
    ]
}`

Mogę prosić o pomoc?

**Comment by nwaworek** [comment]
Dziękuję. Zamykam zatem :)
