### ISSUE TITLE
Problem z metodą "/sale/loyalty/promotions?user.id=" czyli pobieranie ofert "kup w zestawie"

### ISSUE THREAD

**Issue by Gerston** [allegro/allegro-api#812]
Problem polega na tym, że nie można pobrać wszystkich ofert, mamy na allegro utworzonych ponad 35000 ofert kup w zestawie i pobrać można jedynie do 20000, czyli jeśli podam offset=19900, limit=100 jest OK, ale już offset=20000 zwraca wewnętrzny błąd serwera.

**Comment by PawelTaberski** [comment]
Sprawdziliśmy i rzeczywiście jest problem. Poprawimy to, prosimy o cierpliwość.

**Comment by Gerston** [comment]
Problem dalej występuje, a przynajmniej tak było do wczoraj.
