### ISSUE TITLE
Indefinite error message: PROCESSING_ERROR Problem with dispatch. Contact us, and we will help as soon as possible

### ISSUE THREAD

**Issue by DHSC1** [allegro/allegro-api#8120]
Hello,
We are unable to print a label for order 25d7d240-9411-11ee-94d5-93afe772a354. We are getting a very indefinite error:
[{"code":"PROCESSING_ERROR","details":null,"message":"Problem with dispatch. Contact us, and we will help as soon as possible.","path":"","userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}].
We contacted your frontline support first, and it forwarded us to your GitHub without further details.
Thank you for your help.

**Comment by Lukasz-Zurek** [comment]
@DHSC1 If you a trying to create a label for this order via our API - please send us a trace-id of this request.

**Comment by DHSC1** [comment]
Hello,
I have a fresh example on another order. This is an order: 4df8ae72-c8f5-11ee-9400-f5d4a7cf02a6
Trace id: 4dd31c733b31f1f0
Error is returned again: 
`{"id":"ca873698-5c69-4d8c-ac7e-90183b645839","status":"ERROR","errors":[{"code":"PROCESSING_ERROR","message":"Problem with dispatch. Contact us, and we will help as soon as possible.","details":null,"path":"","userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}]}`

**Comment by AureliuszBrussy** [comment]
Hi @DHSC1, WE|DO does not support cancellations of shipments.
