### ISSUE TITLE
Prosimy o pomoc w związku z błędem podczas umieszczania towarów

### ISSUE THREAD

**Issue by AbramovskyIvan** [allegro/allegro-api#8121]
Dobry dzień!
Próbujemy skonfigurować Twoje API dla naszego systemu księgowego.
Pomyślnie otrzymaliśmy token, pomyślnie odczytaliśmy dane interesujących nas kategorii, jednak mamy problem z tworzeniem zdjęć produktów i samych produktów.
Tak, podczas próby opublikowania obrazu na żądanie
POST /sale/images (binarna metoda przesyłania danych, „content-type”: „image/jpeg”)
zawsze otrzymujemy status odpowiedzi 403 (Forbidden) zarówno w piaskownicy, jak i w systemie produkcyjnym.
To samo dzieje się, gdy staramy się stworzyć produkt na zapyty
POST /sale/product-proposals

Proszę o pomoc w zrozumieniu w czym może tkwić problem. Być może nie zostały spełnione jakieś wymagania lub wybrano błędną ścieżkę autoryzacji?
Dziękuję!

Szczegóły techniczne każdego zapyty:

(przetłumaczone za pomocą google translate)

POST /sale/images :
Headers:
"Authorization":"valid_token",
"Accept":"application/vnd.allegro.public.v1+json",
"Accept-Language":"uk-UA",
"Content-type":"image/jpeg"
Body:
<binary data>

POST /sale/product-proposals :
Headers:
"Authorization":"valid_token",
"Accept":"application/vnd.allegro.public.v1+json",
"Accept-Language":"uk-UA",
"Content-type":"application/vnd.allegro.public.v1+json"
Body:
{
 "name": "Młotowiertarka Dnipro-M RH-16",
 "category": {
  "id": "147650"
 },
 "description": {
  "sections": [
   {
    "items": [
     {
      "type": "TEXT",
      "content": null
     }
    ]
   }
  ]
 },
 "language": "uk-UA",
 "parameters": [
  {
   "id": "237222",
   "values": [
    "RH-16"
   ]
  },
  {
   "id": "128473",
   "values": [
    "1.1"
   ]
  },
  {
   "id": "205021",
   "values": [
    "4850"
   ]
  },
  {
   "id": "25029",
   "values": [
    "3.6"
   ]
  },
  {
   "id": "25689",
   "values": [
    "230"
   ]
  },
  {
   "id": "205137",
   "valuesIds": [
    "205137_222593"
   ]
  },
  {
   "id": "224017",
   "values": [
    "121212"
   ]
  },
  {
   "id": "209202",
   "valuesIds": [
    "209202_238306"
   ]
  },
  {
   "id": "128474",
   "valuesIds": [
    "128474_4"
   ]
  },
  {
   "id": "129631",
   "values": [
    "1212"
   ]
  },
  {
   "id": "24908",
   "values": [
    "1000"
   ]
  },
  {
   "id": "11323",
   "valuesIds": [
    "11323_1"
   ]
  },
  {
   "id": "225693",
   "values": [
    "4823102337296"
   ]
  },
  {
   "id": "128608",
   "valuesIds": [
    "128608_652997"
   ]
  },
  {
   "id": "229205",
   "valuesIds": [
    "229205_340245"
   ]
  }
 ],
 "images": [
  {
   "url": "https://static.dnipro-m.pl/cache/products/8346/catalog_origin_10857.jpg"
  }
 ]
}

**Comment by Lukasz-Zurek** [comment]
@AbramovskyIvan Upewnij się, czy nie korzystasz z autoryzacji typu[ client_credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow), która nie posiada kontekstu użytkownika. W[ naszej dokumentacji](https://developer.allegro.pl/documentation) znajdziesz odpowiednie oznaczenie, jaki typ autoryzacji wymagany jest dla danego zasobu:

- bearer-token-for-user ([code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub[ device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow),
- bearer-token-for-application ([client credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow)).

Zalecam korzystać z autoryzacji typu [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub[ device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow.

**Comment by AbramovskyIvan** [comment]
@Lukasz-Zurek 
Dziękujemy za szybką odpowiedź.
Używam bearer-token-for-application (wydaje się)
Żądanie otrzymania tokena:
https://allegro.pl/auth/oauth/token
headers:
"Authorisation": "Basic id:secret_to_base_64"
"Content-Type": "application/x-www-form-urlencoded
Data:
"grant_type": "client_credentials"

A następnie po prostu używam tokena otrzymanego w odpowiedzi

**Comment by Lukasz-Zurek** [comment]
Zasoby, z których korzystasz są oznaczone [bearer-token-for-user](https://developer.allegro.pl/documentation#section/Authentication/bearer-token-for-user), czyli musisz autoryzować się za pomocą autoryzacji typu [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub[ device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow.

Z przesłanych przez Ciebie informacji wynika, że korzystasz z tokena wygenerowanego w ramach autoryzacji client_credentials i tu uzyskasz dostęp tylko do zasobów oznaczonych **bearer-token-for-application**, np. GET /sale/categories.

**Comment by AbramovskyIvan** [comment]
Dziękujemy za pomoc! Wszystko się udało!
