### ISSUE TITLE
Limit zapytań dla użytkownika - Nowe endpointy

### ISSUE THREAD

**Issue by bartexs6** [allegro/allegro-api#8124]
Dzień dobry,

Mam pytanie dotyczące limitów zapytań dla użytkownika w nowych endpointach tj.:

- [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers)
- [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/editProductOffers)
- [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/getProductOffer)

Oraz:

- GET /sale/products

Jak wyglądają limity zapytań dla tych endpointów?

**Comment by PrzemyslawLukanowski** [comment]
Jeśli chodzi o endpointy:

- [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers)
- [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/editProductOffers)
- [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/getProductOffer)

to nie posiadają one żadnego dodatkowego limitu, w tym przypadku w grę wchodzi tylko globalny limit, który nakładamy na ruch generowany przez aplikację na wszystkich zasobach - 9000 requestów na minutę.

Dla GET /sale/products obowiązuje dodatkowy limit [Leaky Bucket](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#ograniczenie-liczby-zapytan-limity) - jeżeli przekraczasz dozwoloną liczbę wywołań na minutę, wydłużamy czas odpowiedzi. Nie jest to wartość stała, dlatego nie podajemy jej w dokumentacji.

**Comment by bartexs6** [comment]
> Jeśli chodzi o endpointy:
> 
> * [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers)
> * [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/editProductOffers)
> * [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/getProductOffer)
> 
> to nie posiadają one żadnego dodatkowego limitu, w tym przypadku w grę wchodzi tylko globalny limit, który nakładamy na ruch generowany przez aplikację na wszystkich zasobach - 9000 requestów na minutę.
> 
> Dla GET /sale/products obowiązuje dodatkowy limit [Leaky Bucket](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#ograniczenie-liczby-zapytan-limity) - jeżeli przekraczasz dozwoloną liczbę wywołań na minutę, wydłużamy czas odpowiedzi. Nie jest to wartość stała, dlatego nie podajemy jej w dokumentacji.

Jest jakaś przybliżona wartość dla którego Leaky Bucket wydłuży nam czas odpowiedzi czy zmienna się ona dynamicznie?

**Comment by bartexs6** [comment]
Jak wygląda sprawa z limitami na sandboxie. Są takie same jak dla produkcji allegro?

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, Sandbox odzwierciedla środowisko produkcyjne.
