### ISSUE TITLE
Oferty Wielowariantowe - Usuwanie ofert wielowariantowych, rozłączanie aukcji automatycznie połączonych i łączenie w nowe oferty wielowariantowe

### ISSUE THREAD

**Issue by Put3k** [allegro/allegro-api#8125]
Cześć,

Mam problem z ofertami wielowariantowymi.
Wrzuciłem oferty i zostały one automatycznie połączone. Znalazłem oferty wielowariantowe w których występują oferty, usunąłem te oferty wielowariantowe a na aukcji dalej widoczne jest połączenie w oferty wielowariantowe. Utworzyłem nowe oferty wielowariantowe z ofert składających się na usunięte oferty wielowariantowe podając jako parametry rozmiar i colorPattern. W ofercie dalej widoczne są automatycznie utworzone oferty wielowariantowe.
Allegro posiada osobną logikę/bazę danych na przetrzymywanie automatycznie utworzonych ofert wielowariantowych w kategorii Koszulki? Utworzone przeze mnie oferty wielowariantowe nie mają wpływu na aukcję.

Chodzi o kategorię: 89528, 76104, 87913

**Comment by MartaNowaczyk** [comment]
W wybranych kategoriach (widocznych w pkt 1.12.2 [Regulaminu Serwisu](https://allegro.pl/regulamin/pl/zalacznik-2)), oferty wielowariantowe łączymy automatycznie na podstawie parametrów, dlatego usunięcie ofert, które wcześniej zostały do takiej wielowariantowej oferty automatycznie dodane, nie będzie możliwe i nie przewidujemy bezpośredniej ingerencji w zawartość dla ofert wielowariantowych w kategoriach [zarządzanych automatycznie](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/wielowariantowosc-ofertowa-jak-polaczyc-oferty-i-edytowac-warianty-lDkngqrGYhL#automatyczne-laczenie-ofert-tylko-dla-niektorych-kategorii).

**Comment by Put3k** [comment]
@MartaNowaczyk dziękuje za odpowiedź.
W takim razie do czego odnosi się ta informacja?
![image](https://github.com/allegro/allegro-api/assets/114064711/a53dfcb2-aa3c-4313-b26d-523a0ab75f39)

Oraz mam pytanie czy jest jakiś jasny algorytm działania automatycznego łączenia aukcji? Które parametry są kluczowe? Czy jest to wskazane w parametrach kategorii?

**Comment by MartaNowaczyk** [comment]
Wszelkie pytanie dotyczące już samego działania mechanizmu i łączenia ofert najlepiej zadać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt), bo to zasada dotycząca całego allegro, nie API. 

To, jakie parametry możesz użyć sprawdzisz za pomocą [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).  Więcej informacji w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-utworzyc-oferte-wielowariantowa-oA6ZYBg5XFo#sprawdz-parametry).
