### ISSUE TITLE
Edit offer title/description/images

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#8126]
Hi there, 

we are working on sending the offer title, description and images to Allegro but we were wondering how it works, when there is an error in the title/description/images. Our plan is to list the offer anyway and after the user will fix the data, we want to try to add the corrected images/description/offer title. Is it possible to additionally add/change these elements? 

Thank you in advance for your help! 

Best, 

Dominika

**Comment by MartaNowaczyk** [comment]
Hi Dominika,
You can't listing an offer only with a title, description and photos, you should fill in all the necessary data of the product depending on the category. Preliminarily, however, you can create a draft of such an offer by complete its initial data. You create such a draft by specifying "publication.status" with the value "INACTIVE". You can read more about listing in [our tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6).

**Comment by dominikahr** [comment]
Right now, we are only sending EAN, PRICE, CURRENCY, CONDITION and STOCK. We want to be able to provide our own values for offer title, description and images as it is described in your documentation here: https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-provide-your-own-values 

My question now is how it is when we want to add title/description/image to the offer later on. Here is some info about editing a single offer: https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#editing-single-offer
But it is not mentioned if we can also change the offer name. 

So is it possible to additionally add/change offer title, description and images in an already existing active offer?

**Comment by MartaNowaczyk** [comment]
Yes, you can. Just use [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) and send the data to be changed according to the example structure:

```
{
    "name": "Your title",
    "images": [
        "https://... external-image-address.jpeg""
    ],
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>Changed description</p>"
                    }
                ]
            }
        ]
    }
}
```
