### ISSUE TITLE
Checking result of 'Modify the Buy Now price in an offer'

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#8127]
Hi I did not found an answer in documentation.
 If I chage buyNowPrice of an offer using https://api.{environment}/offers/{offerId}/change-price-commands/{commandId}. Where do I find final result? Response is always "VALIDATED_AND_RUNNING"

Thanks

Jirka

**Comment by MartaNowaczyk** [comment]
You can try to query the status again after some time, in the same way. The execution of command can take up to 1 hour. 
If you have any problem with this process, provide the trace-id for this case.

**Comment by ZajdaBear** [comment]
I am not sure, if I udnerstand correcty, but I did sent exact same request now. 

PUT https://api.allegro.pl/offers/13591833929/change-price-commands/90fcf433-c3c8-4cc5-8d97-2433d8fed4f0
```{
    "id": "90fcf433-c3c8-4cc5-8d97-2433d8fed4f0",
    "input": {
        "buyNowPrice": {
            "amount": "889.00",
            "currency": "PLN"
        }
    }
}
```
Response is still the same
```{
    "id": "90fcf433-c3c8-4cc5-8d97-2433d8fed4f0",
    "input": {
        "buyNowPrice": {
            "amount": "889",
            "currency": "PLN"
        }
    },
    "output": {
        "status": "VALIDATED_AND_RUNNING",
        "errors": []
    }
}
```
last trace-id: 697d8b98f6f1887

**Comment by MartaNowaczyk** [comment]
I just now noticed that you are using an older endpoint. A better way to check the status of a price change would be to use  [PUT /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT), where you can change the price in the offer and use additional commands where you get the status of the change. You can read more in our [tutorial](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#price).

**Comment by ZajdaBear** [comment]
Thanks, using this resource instead makes sense.
