### ISSUE TITLE
WzA miniKurier24 InPost, jak ustawić metodę wysyłki

### ISSUE THREAD

**Issue by booklet-mikolajczak** [allegro/allegro-api#8128]
Dzień dobry

W jaki sposób utworzyć przesyłkę miniKurier24 inPost z metodą wysyłki "Dowolny PaczkoPunkt" (pop), domyślnie ustawia się "Odbierze kurier InPost".

Próbowałem klucz `sending_method` / `sendingMethod` o wartości 'pop' przepchnąć w różnych miejscach, ale zawsze kończy się błędem.

Proszę o pomoc i pozdrawiam

**Comment by MartaNowaczyk** [comment]
Dzień dobry,
jeśli chcesz nadać paczkę z punktu odbioru, podczas tworzenia przesyłki powinieneś podać "pickup.point" lub "pickup.pointId" w zależności od tego czy korzystasz z nowej czy starej metody. Punkty odbioru powinny być dostępne u przewoźnika.

**Comment by booklet-mikolajczak** [comment]
Korzystam ze starej wersji

Gdy podam `pickup.pointId` to dostaje: `Usługa niedostępna u tego przewoźnika
`

Request z danymi: https://api.allegro.pl/parcel-management/parcel-create-commands/8bf0585f-36c6-4718-bdad-1f3540fecafd
```
[serviceId] => "9081532b-xxxx-xxxx-xxxx-9252982e9dd8#xxxxxxxx-xxxx-xxxx-xxxx-a071e9a87371"
[receiver] => array(6)
{
    [address] => array(4)
    {
        ...
    }
    [email] => "xxxxxxxx@allegromail.pl"
    [name] => "xxxxxxxxxx xxxxxx"
    [phone] => "xxxxxxxx"
}
[pickup] => array(6)
{
    [address] => array(4)
    {
        [street] => "xxxxxxxxx"
        [postCode] => "xx-xxx"
        [city] => "xxxxxxxxx"
        [countryCode] => "xx"
    }
    [email] => "xxxxxxxxxxxxx"
    [name] => "xxxxxxxxxxxxx"
    [company] => "xxxxxxxxxxxxx"
    [phone] => "xxxxxxxxx"
    [pointId] => "POP-PLE11"
}
[items] => array(1)
{
    ...
}
[type] => "PACKAGE"
[label] => array(3)
{
    ...
}
```


Odpowiedź
```
[id] => "8bf0585f-36c6-4718-bdad-1f3540fecafd"
[parcelId] => null
[status] => "ERROR"
[errors] => array(1)
{
    [0] => array(5)
    {
        [code] => "VALIDATION_ERROR"
        [message] => "Service unavailable for carrier"
        [details] => null
        [path] => "pickup.pointId"
        [userMessage] => "Usługa niedostępna u tego przewoźnika"
    }
}
```

**Comment by MartaNowaczyk** [comment]
Wracam z informacją. Można, jednak tylko za pośrednictwem Managera InPost. W WZA (również przez API) nie jest to dostępne. Przepraszam za wprowadzenie w błąd.

**Comment by booklet-mikolajczak** [comment]
Szkoda :(, ale dziękuje za informacje

**Comment by daniel93333** [comment]
Mam ten sam problem, chciałem skorzystać z nadania w paczkopunkciem, ale dla przesyłek paczkomatowych.
Z tego co widzę to da się dla paczkomatów wybrać taką opcję:
![image](https://github.com/allegro/allegro-api/assets/141407776/0b06d895-cabf-4a4d-8b58-492d39e7ced1)
Ale jak to zrobić przez API?

**Comment by MartaNowaczyk** [comment]
@daniel93333 jeśli wybierasz nadanie w PaczkoPunkcie to powinieneś ją nadać przez Managera Paczek InPost. Konsultowałam to wcześniej z zespołem odpowiedzialnym za WZA i w API nie ma takiej możliwości. Skąd jest ten zrzut?

**Comment by daniel93333** [comment]
To prawda, że w WzA nie ma takiej opcji dla kuriera24 i minikuriera, ale jest taka opcja dla Paczkomatów. Powinno więc dać się to zrobić też przez API.

**Comment by MartaNowaczyk** [comment]
Rozumiem. W tym przypadku możesz spróbować użyć różnych wartości zależnie od wybranej opcji:
- dla PaczkoPunktu => `pickup.point = "any_parcel_shop"`
- dla Paczkomatu => `pickup.point = "any_apm"`
- dla podjazdu kuriera => `pickup.point = null`

**Comment by daniel93333** [comment]
Spróbowałem pickup.point = "any_apm", etykieta się wydrukowała, ale w punkcie dalej nie mogą jej zeskanować (paczka nie podlega nadaniu w punkcie:
commandId: 83dea236-752a-4dc5-a697-0378f81e0ab8
ShipmentId: 5ebedf4f-789a-427f-995c-4ed426afabc8

**Comment by MartaNowaczyk** [comment]
Z tego co widzę w logach, podałeś sender.point=any_parcel_shop, zamiast pickup.point=any_parcel_shop.

**Comment by daniel93333** [comment]
Hmm no właśnie z tego co widzę w swoim requeście to podałem pickup.point=any_parcel_shop, a sender.point pominąłem, to znaczy usunąłem ten parametr z listy. Czy to mogło spowodować błędną interpretacje przez wasz system?
Co należy podać w sender.point jeśli nie należy go pomijać?

**Comment by MartaNowaczyk** [comment]
Dla podanego wcześniej commandId wyglada to inaczej - tak jak pisałam wcześniej. Możesz podać trace-id lub commandId dla powyższego przykładu? Może to już inny request? 
Co do drugiego pytania, to nie powinno być błędnie zinterpretowane. Pole możesz pominąć lub podać null. 
Adres jest wymagany.

**Comment by daniel93333** [comment]
Faktycznie mogłem wkleić request dla innej przesyłki, nie zapisałem sobie niestety requestu, o którym była mowa, ale wydaje mi się, że podałem"any_parcel_shop" w sender.point i pickup.point jednocześnie.
Teraz próbuję robić tak jak pokazałem wyżej i nie ważne czy pominę sender.point czy podam null to dostaje "Opcja 'Inne dane na etykiecie' nie są dostępne dla wybranego przewoźnika". 
CommandId dla tej sytuacji to: f06144f9-3e85-45a1-a68a-d171396c420f

**Comment by MartaNowaczyk** [comment]
Jak tylko to zweryfikuję dam znać.

**Comment by MartaNowaczyk** [comment]
Przewoźnik odrzucił ten request, bo dane właściciela i dane do podjazdu zawierają różnicę w postaci pola point. W sender powinno być również pole "point": "any_parcel_shop". Będziemy zgłaszać to do przewoźnika, żeby poprawili tę walidację.
