### ISSUE TITLE
Brak danych z /order/events

### ISSUE THREAD

**Issue by JacekStawicki360** [allegro/allegro-api#8129]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Na  środowisku testowym nie są zwracane dane z metody https://api.allegro.pl.allegrosandbox.pl/order/events

UserId: 104769919

Coś się dzieje z tą metodą?

**Comment by PrzemyslawLukanowski** [comment]
Wskazany użytkownik nie posiada żadnych zamówień na koncie, dlatego pusta tablica w odpowiedzi GET /order/events to oczekiwany i prawidłowy rezultat.

**Comment by JacekStawicki360** [comment]
mea culpa. 
pomylilem login. Wszystko dziala.
