### ISSUE TITLE
proble z wystawieniem wariantu przez rest

### ISSUE THREAD

**Issue by Agrrr2001** [allegro/allegro-api#813]
Dzień dobry

przy prubie wywołania adresu
https://api.allegro.pl/sale/offer-variants/9d8c82ca-d388-11e8-94d1-18d6c70f7be
z parametrami:
{"offers":[{"id":"7559570790"},{"id":"7559570783"}],"name":"Stan","parameters":[{"id":130563}]}
oraz nagłówkami
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsIxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxZMrTQpbAdH7Ir_SnCJ7UWxKzg

 otrzymuje błąd
 Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji. NotAcceptableException/An error has occurred  

proszę o pomoc bo nie widzę nigdzie błędu który mógłbym popełnić.

**Comment by PawelTaberski** [comment]
Rozumiem, że chcesz stworzyć ofertę wielowariantową, czy na pewno korzystasz z metody PUT?

**Comment by Agrrr2001** [comment]
Tak korzystam z metody put 
zauważyłem też że nie działają mi inne metody związane z wariantami jak np. get /sale/offer-variants
jeśli chodzi o resztę metod to działają poprawnie 
GET-https://allegroapi.io/sale/offer-variants: Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji. NotAcceptableException/An error has occurred

**Comment by PawelTaberski** [comment]
Już widzę o co chodzi, podane zasoby są w wersji beta musisz zmienić nagłówki na:
`application/vnd.allegro.beta.v1+json`
Przy okazji warto zapoznać się z naszym poradnikiem odnośnie łączenia ofert.
Poradnik znajdziesz [tutaj](https://developer.allegro.pl/news/2018-07-09-Wielowariantowosc/).
Ponadto niedawno wdrożyliśmy parametr weryfikujący, opisaliśmy to [tutaj](https://developer.allegro.pl/news/2018-10-22-Parametr_weryfikujacy/).

**Comment by Agrrr2001** [comment]
Wielkie dzięki, przejrzałem oba poradniki ale ten szczegół jakoś mi umknął.
