### ISSUE TITLE
Aktywacja konta na sandboxie

### ISSUE THREAD

**Issue by gkopec** [allegro/allegro-api#8131]
Poproszę o aktywację konta na sandboxie: **test_Kuba**
Czy na sandboxie można włączyć 2FA? Podobno SMSy nie przychodzą...

**Comment by PrzemyslawLukanowski** [comment]
Twoje konto zostało założone ponad rok temu, niestety nie mamy już możliwości aktywacji, musisz utworzyć nowe konto. Na Sandboxie nie wysyłamy SMS, dwustopniowe logowanie w tym środowisku nie jest wymagane do rejestracji aplikacji. Jeśli jednak chcesz je włączyć, wpisz 12345, a przy logowaniu 123456.

**Comment by gkopec** [comment]
@PrzemyslawLukanowski dziękuję
