### ISSUE TITLE
/sale/product-offers/ PATH - aktualizacja samych obrazków images

### ISSUE THREAD

**Issue by sbrzezin** [allegro/allegro-api#8132]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,

zaktualizowałem obrazki za pomocą /sale/product-offers/ PATH. Podałem tylko listę obrazków w atrybucie "images".

{
  images: [http://..... , http://....]
}

Obrazki pojawiły się przy produkcie jednak stare obrazki nadal są. Czyli teraz mam już 10 obrazków - 5 nowych i 5 poprzednich. Czy to prawidłowe zachowanie? A jeśli tak, co zrobić aby obrazki nie zostały dodane lecz nadpisały poprzednie obrazki?

pozdrawiam

Sergiusz Brzeziński

**Comment by PrzemyslawLukanowski** [comment]
Jeśli nie chcesz obrazków z naszego Katalogu Produktów, to przekaż proszę dodatkowo pustą tablicę w polu `productSet.product.images`. Przykładowy request znajdziesz [w naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty):

```
{
    "productSet": [
         {
                        "product": {
                            "id": "990de42f-8a68-4f0c-aedb-060141ffd8e3",
                            "images": []
                        }
        }],
    ...
    "images": [
            "https://...zewnetrzny-adres-pierwszego-obrazka.jpeg",
            "https://...zewnetrzny-adres-drugiego-obrazka.jpeg"
    ]
    ...
  }   
```

**Comment by sbrzezin** [comment]
Czytałem wcześniej dokumentację. Jednak nie poszedłem tą drogą gdyż w katalogu produktu jest tylko 1 obrazek, a nie 5. Uznałem więc, że to nie tu tkwi problem skoro do oferty dokleiło się aż 5 obrazków.

Zastosowałem powyższe i nadal jest problem.

Teraz zamiast 10 obrazków (5 nowych i 5 doklejonych) mam 5 + 1. Ten dodatkowy obrazek to właśnie obrazek z Katalogu Produktów. Jak się go pozybć?

**Comment by PrzemyslawLukanowski** [comment]
Najlepiej będzie, jeśli podeślesz nam trace-id tego przypadku. W ten sposób będziemy mogli przeanalizować logi i zweryfikować ten przypadek. Upewnij się jeszcze, czy ten dodatkowy obrazek nie występuje w opisie oferty.

**Comment by sbrzezin** [comment]
Problem rozwiązany. W skrócie, źródłem problemów okazał się brak synchronizacji pomiędzy opisem produktu a listą obrazków. Myślę, że coś powinno być napisane na ten temat w dokumentacji. W dokumentacji jest przykład sekcji description, a w nim odwołanie się do obrazków z serwera Allegro. I to jest moim zdaniem zła praktyka, a w każdym razie może wprowadzać w błąd. Raczej należy odwołać się do url obrazka zewnętrznego zasobu - tego samego, do którego odwołujemy się w sekcji images. Jeśli odwołujemy się do zasobu z Allegro, to oznacza to, że ten zasób już tam musi być. I powstaje odwieczne pytanie co było pierwsze: kura czy jajko?

**Comment by PrzemyslawLukanowski** [comment]
Cieszę się, że udało się rozwiązać problem i dziękuję za sugestię - poprawimy przykładowe adresy w poradniku.
