### ISSUE TITLE
Losowy błąd 503 przy metodzie offers/listing

### ISSUE THREAD

**Issue by stud3nt** [allegro/allegro-api#8133]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Od kilku dni metoda offers/listing zwraca losowo błąd 503:

`Response from Allegro API: [503] -  - {"errors":[{"code":"SERVICE_UNAVAILABLE","message":"Service unavailable.","details":null,"path":null,"userMessage":"Server is unable to respond to your query. Try again in a few minutes."}]}`

Dzieje się tak przez kilka minut, po czym wszystko wraca do normy. 
Nie jest to przekroczenie limitu zapytań na minutę, bo wtedy kod błędu byłby inny (429).

Ma ktoś pomysł, co może być przyczyną? Allegro prowadzi jakieś niezapowiedziane prace?

**Comment by Lukasz-Zurek** [comment]
@stud3nt Potwierdzam problemy. Analizujemy obecnie z zespołem odpowiedzialnym za tę usługę. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@stud3nt Problem został wyeliminowany. Potwierdź proszę czy błędy ustąpiły.

**Comment by stud3nt** [comment]
@Lukasz-Zurek potwierdzam, że problem został wyeliminowany :)
