### ISSUE TITLE
Brak statystyk Allegro Ads na koncie Sandbox

### ISSUE THREAD

**Issue by baltrek** [allegro/allegro-api#8135]
Dzień dobry. Zauważyłem że na koncie Sandboxowym nie jesteśmy w stanie sprawić aby w statystykach Allegro ADS pojawiły się dane. Czy jest możliwość wrzucenia tam jakichś danych aby wypełnić i wygenerować jakieś statystyki? [konto bartek_sem]

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale nie mamy takiej możliwości na środowisku testowym.
