### ISSUE TITLE
Książka adresowa a nadawca w Wysyłam z Allegro

### ISSUE THREAD

**Issue by Maczuga** [allegro/allegro-api#8139]
W sekcji "Obsługa zamówień -> Zamówienia" na stronie znajduje się Książka adresowa - Wysyłam z Allegro.
Zauważyłem, że adresy nadawcy przesyłane z API są tam dodawane.

Czy jest jakaś możliwość:

- pobrania tych adresów z poziomu API (zależy nam na pobraniu domyślnego adresu)?
- wymuszenia w API, żeby wybierał zawsze domyślny adres? Niestety pusty obiekt "sender" nie przechodzi. Mowa o metodzie "/shipment-management/shipments/create-commands"

**Comment by Lukasz-Zurek** [comment]
Niestety nie można pobrać tych adresów z poziomu API. Nie można również wymusić używania domyślnego adresu we wskazanej metodzie.
