### ISSUE TITLE
sandbox environment error

### ISSUE THREAD

**Issue by yu-www** [allegro/allegro-api#8140]
Hi there,

I am trying to list the offer in the sandbox environment on Allegro, but I am receiving an error message that says ‘You do not have the permissions required to list an offer (sales suspended)’. 

and when I call the API "/sale/product-offers".it returns ‘The user with a blockade on account cannot create new product proposals’.

Could you please help me understand why this is happening and how I can resolve it?

my sandbox account is yw_www@163.com

Thank you  for your help!

**Comment by Lukasz-Zurek** [comment]
Your account has a sales block. First of all you have to settle fictitious debts which you can do right [here](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro), using our payment simulator (it is not a real payment).

The sales block should be revoked automatically, but if not, please let me know.

**Comment by xiaolengbuleng** [comment]
> Your account has a sales block. First of all you have to settle fictitious debts which you can do right [here](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro), using our payment simulator (it is not a real payment).
> 
> The sales block should be revoked automatically, but if not, please let me know.

Which one should I choose？

<img width="1269" alt="image" src="https://github.com/allegro/allegro-api/assets/5554249/ed9eec28-5507-46ea-866f-7ea933d40c03">

**Comment by xiaolengbuleng** [comment]
Do I need to provide a real payment account？

**Comment by xiaolengbuleng** [comment]
> Your account has a sales block. First of all you have to settle fictitious debts which you can do right [here](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro), using our payment simulator (it is not a real payment).
> 
> The sales block should be revoked automatically, but if not, please let me know.

I have already taken care of it, thank you。

**Comment by Lukasz-Zurek** [comment]
@xiaolengbuleng Ok, great. If you have any other issues, please do not hesitate to contact us.

**Comment by skutop001** [comment]
@yu-www are you use wechat?
