### ISSUE TITLE
add product for sanbox

### ISSUE THREAD

**Issue by viettai0211** [allegro/allegro-api#8142]
Hi allegro, please support for me.
My accountID is : 106802282
Now , i am calling with curl : 
curl --location 'https://api.allegro.pl.allegrosandbox.pl/sale/product-proposals' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer user token' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--data '{
  "name": "iPhone 5s tai tai tai",
  "category": {
    "id": "147661"
  },
  "images": [
    {
      "url": ""
    }
  ],
  "parameters": [
    {
      "id": "17448",
      "rangeValue": {
        "from": "111",
        "to": "222"
      },
      "values": [
        "333"
      ],
      "valuesIds": [
        "444"
      ],
      "valuesLabels": [
        "555"
      ],
      "unit": "666",
      "options": {
        "identifiesProduct": true
      }
    }
  ],
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "string"
          }
        ]
      }
    ]
  },
  "language": "pl-PL"
}'

The response is : {
    "errors": [
        {
            "code": "AccessDeniedException",
            "message": "Access denied.",
            "details": null,
            "path": null,
            "userMessage": "No access."
        }
    ]
}

I has checked the role of user : 
allegro:api:orders:read allegro:api:fulfillment:read allegro:api:profile:write allegro:api:sale:offers:write allegro:api:fulfillment:write allegro:api:billing:read allegro:api:campaigns allegro:api:disputes allegro:api:shipments:write allegro:api:bids allegro:api:sale:offers:read allegro:api:orders:write allegro:api:ads allegro:api:payments:write allegro:api:sale:settings:write allegro:api:profile:read allegro:api:ratings allegro:api:sale:settings:read allegro:api:payments:read allegro:api:shipments:read allegro:api:messaging

Thanks.

**Comment by viettai0211** [comment]
I was tried active sales but i miss error : 
![image](https://github.com/allegro/allegro-api/assets/16410371/68a6b12f-e33a-4de0-ab93-02a2695da7a2)

Thanks

**Comment by viettai0211** [comment]
Thank you @Lukasz-Zurek . I was converted my account to business account . but how can i pass this step : 
![image](https://github.com/allegro/allegro-api/assets/16410371/b3e82c5f-f884-48f9-9975-f86ed0098b9a)


Thanks

**Comment by viettai0211** [comment]
Can you give me IBAN and SWITH code to pass this step. 

Thanks,

**Comment by viettai0211** [comment]
I passed over this step .
![image](https://github.com/allegro/allegro-api/assets/16410371/f80e560d-59cb-498a-9f3c-6ead5bda6e26)
Please accept config for my sales setting.
Thanks @Lukasz-Zurek .
Thanks you very much!

**Comment by viettai0211** [comment]
Dear @Lukasz-Zurek . i created product success full. but i can't see it on my account . 
This is the evidence create product success.
please help me to check it.
![image](https://github.com/allegro/allegro-api/assets/16410371/1fe722bd-596d-407e-a4b5-3e8f40820e55)

Thanks

**Comment by viettai0211** [comment]
I tried to using sale/product-offers but i get the result : 
![image](https://github.com/allegro/allegro-api/assets/16410371/d3dc4226-aeb1-4647-98c7-2c70222261dd)
Can you help me to check.
I using clientID :  106742073

Thanks

**Comment by Lukasz-Zurek** [comment]
Please note the fact that [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct) resource is for creating the product in our catalog - it is not related to creating an offer on Allegro. To check the product's data, you can use [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct).

But as I can see - you are trying to use [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers). Your account is regular and you need a business account. You have to convert your account, which you can do [here](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta). Then please [configure the payouts](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty) and make a fictional payment via payment simulator. Obviously you can use one of the online IBAN generators to fill the required data.

**Comment by viettai0211** [comment]
yes. i am using another account with ID : 106742073 .
I have created product success : 
![image](https://github.com/allegro/allegro-api/assets/16410371/025540f4-3cfd-4d4a-bfe1-ccce529a2d3f)
But when i try to get this information on api /sale/products/{productId} . There are no product.
This is the evidence : 
![image](https://github.com/allegro/allegro-api/assets/16410371/316ae464-f5c0-4664-aa58-6dc97c1de702)
I am using same token account with id : 106742073 

Thanks

**Comment by viettai0211** [comment]
I know the problem. When I have created success product , i can get it from api /sale/products/{productId} .Bbut after 3-5 minutes this product will be removed .
Can you explain that for me @Lukasz-Zurek 

Thanks

**Comment by Lukasz-Zurek** [comment]
@viettai0211 This product (b0adc109-44af-4ab6-a681-c12602fefdf9) has been deleted on 2023-12-21 07:28:27 by our automatic mechanism that detects incorrect products with incomplete or inconsistent data.
