### ISSUE TITLE
Kurier DPD umowa własna brak w delivery-services

### ISSUE THREAD

**Issue by krzwaw83** [allegro/allegro-api#8144]
Klient kontaktował się mailowo z kimś z Allegro i został pokierowany do założenia issue tutaj.
W metodzie `/parcel-management/delivery-services` nie jest zwracana podpięta umowa własna z DPD. Klient twierdzi, że jest podpięta w Allegro, ze swojej strony kilkadziesiąt innych podmiotów korzystających z tej metody wysyłki nie ma problemu, mają swoje umowy. 

ID Klienta to ce14889d95914fe6935408e28dd09419 . Czy możecie sprawdzić czy klient ma podpiętą umowę własną z DPD ?

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że zwracamy umowy własne DPD we wspomnianym zasobie dla użytkownika, który korzysta z aplikacji:

```
            "id": "c3066682-97a3-42fe-9eb5-9bb2978cf293#0435c1e8-a3a3-4bb2-afc1-290bb781e642",
            "service": "DPD",
            "name": "Kurier DPD (DPD)",
            "owner": "CLIENT",
```

```
            "id": "259b5c7a-9056-4c74-80ec-9bb2978cf293#0435c1e8-a3a3-4bb2-afc1-290bb781e642",
            "service": "DPD",
            "name": "Kurier DPD pobranie (DPD)",
            "owner": "CLIENT",
            "carrierId": "DPD",
```
