### ISSUE TITLE
Import nowych ofert

### ISSUE THREAD

**Issue by drzemik** [allegro/allegro-api#8145]
Z allegro do systemu produkcyjnego pobieram ostatnio zmodyfikowane oferty metodą GET sale/offer-events?from=$lastEvetId
gdzie $lastEvetId jest ostatnim id. zdarzenia z ostatniej wykonanej metody.
Od jakiegoś czasu w pobranej liście brakuje ofert nowych. Są tylko stare ostatnio zmodyfikowane.
Jaką metodą mogę pobrać nowe oferty?

**Comment by Lukasz-Zurek** [comment]
Możesz to zrobić tę samą metodą, dodając jednak filtr "type": "OFFER_ACTIVATED", dzięki czemu zawęzisz wyniki tylko do ofert wystawionych. Ewentualnie możesz jednocześnie zwiększyć limit (domyślnie jest 100 wyników, maksymalnie 1000).
