### ISSUE TITLE
Cena dostępu do API, oraz zgodność z regulaminem

### ISSUE THREAD

**Issue by piotr-galas** [allegro/allegro-api#8147]
Cześć

Mam dwa pytania:

1. Czy dostęp do wersji produkcyjnej API jest darmowy, nigdzie nie mogłem znaleźć takiej informacji. (Jeśli nie to jaka jest cena)
2. Chciałbym stworzyć aplikacje na użytek prywatny która fetchowała by ceny archiwalnych licytacji, dla danego zapytania (produktu). Use case jest taki, że często licytuje przedmioty z kategorii kolekcje, których cena zmienia się z czasem. Trudno  określić aktualną cenę dlatego przeglądam ręcznie archiwum allegro. Chciałbym to zautomatyzowac.

>...Zabronione jest wykorzystywanie do prezentowania w serwisach konkurencyjnych Ofert (w tym Ofert archiwalnych) publikowanych w ramach Allegro...

Jednak gdybym robił to na własny użytek to myślę, że nie naruszałbym regulaminu

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
1. Dostęp do wersji produkcyjnej Allegro API jest bezpłatny.
2. Nie pobierzesz ofert archiwalnych poprzez nasze API. Możesz jedynie wyszukiwać wg. ofert zakończonych poprzez [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing), który wymaga jednak weryfikacji - więcej informacji znajdziesz [tutaj](https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk#jak-wyszukiwac-i-przegladac-oferty).

Natomiast pobieranie ofert archiwalnych podchodzi pod scrapowanie, a to jest u nas zabronione.

**Comment by piotr-galas** [comment]
Dziękuje za szybkie i rzeczowe wyjaśnienie.
