### ISSUE TITLE
Synchronizacja Allegro - Baselinker produkty

### ISSUE THREAD

**Issue by Schmidova** [allegro/allegro-api#8148]
Witam, w Allegro.cz otrzymaliśmy zamówienie na produkt niedostępny i ukryty w sklepie internetowym juz od dnia 11.10.2023 r. Jest to produkt o numerze EAN 8591680128549 (FIXED EU Adapter do podłączenia ładowarek UK, US, AUS do gniazd UE , biały) - w związku z toho zakończyłem aukcję ręcznie. Korzystamy z spoluprace z Baselinker.cz. Dziwne, že produktu Fixed nie ma juz v XML z produkty dostepnymi, nie znalazłem go ani w inwentarzu Baselinkera, ani w zarządzaniu ofertami Baselinkera. Niemniej jednak w samym Allegro jest oferta z przeszłości i klient właśnie za jej pośrednictwem ją kupił. Pewnie to jakiś błąd synchronizacji danych po stronie Allegro. Baselinker ma wszystko poprawnie aktualizowane co 3 godziny. Prosze o iformację jak często Allegro aktualizuje dane asortymentowe z Baselinkera? Jak jest mozliwe, ze Allegro po 11. 10.  stale oferuje powyższego produktu?
E-shop Nejceny (firma Jařab s.r.o.)
Manager: V. Schmidová, tel. +420 732 821 017
marketing@j-m.cz

**Comment by MaciejFrackowiak** [comment]
W tej sprawie proszę skontaktuj się z supportem Twojego dostawcy integracji - za aktualizację i synchronizację oferty odpowiada integracja. My jako Allegro wyłącznie odbieramy dane od integracji.
