### ISSUE TITLE
Tworzenie przesyłki WZA Kurier DPD

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#8149]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Przy próbie utworzenia przesyłki 
PUT https://api.allegro.pl/parcel-management/parcel-create-commands/0df768a0-9b2d-4947-830b-f18cde05e787
trace_id = 29ab8ff95be8b8ea
dostajemy zwrotke 400 z brakiem błędów {'errors': []}

**Comment by MaciejFrackowiak** [comment]
Problemem jest pole "receiver.name" - powinno tu się znaleźć imię i nazwisko, natomiast we wskazanym requeście jest dołączona nazwa firmy.

**Comment by paafcioc22** [comment]
@MaciejFrackowiak  mam podobny błąd 3a0be3dc-e44d-4af6-99e1-102bf3dbae72

**Comment by MaciejFrackowiak** [comment]
@paafcioc22 W Twoim przypadku problemem jest zawartość pola "label.referenceNumber" - dopuszczalne znaki to "[A-Za-z0-9 _-]*]]", natomiast użyte zostało "górale".

**Comment by paafcioc22** [comment]
ok, ale ta informacja nie jest zwracana. Tylko sam bad request

**Comment by MaciejFrackowiak** [comment]
@paafcioc22 Zgadza sie, i ten przypadek zgłaszam do zespołu odpowiedzialnego za usługę.
