### ISSUE TITLE
'Location' i 'delivery' w /sale/offers/{offerId}

### ISSUE THREAD

**Issue by PiotrLaszczyk** [allegro/allegro-api#815]
Tworzę draft oferty i próbuje edytować kolejno elementy: "parameters", etc...

Czyli cyklicznie: 
1.) 'body' to response z GET /sale/offers/{offerId}
2) updejtuje interesujące mnie pole w 'body' i robię z tym: PUT /sale/offers/{offerId} 

No i wypełniam w ten sposób draft'a. Czemu tak? chciałem widzieć na którym etapie validacja nie przejdzie. Sek w tym że wszystko niby przechodzi. 

Natomiast mam problem z dwoma polami: location i delivery. Pozostałe się ustawiają jak trzeba.

Jedno i drugie ustawiam jak sądzę dobrze:
body["delivery"] = {'handlingTime': 'PT24H', 'additionalInfo': 'Informacje dodatkowe', 'shipmentDate': '2018-10-25T08:00:00Z', 'shippingRates': {'id': 'f9e4ab01-29b5-467b-88b5-6e6062fb0cda'}}

body["location"] = {'countryCode': 'PL', 'province': 'DOLNOSLASKIE', 'city': 'Legnica', 'postCode': '59-220'}

Już mi się powoli pomysły kończą ;)

Please help;)

**Comment by PiotrLaszczyk** [comment]
No nie do końca bo jak się robi update na raz tymi samymi parametermi to się udaje.. ;)

Czyli zamiast:
1.) 'body' to response z GET /sale/offers/{offerId}
2) updejtuje interesujące mnie pole w 'body' i robię z tym: PUT /sale/offers/{offerId}
i w kółko 1-2

to:
'body' to response z GET /sale/offers/{offerId}
updejtuje wszystkie pola w 'body' i z tym: PUT /sale/offers/{offerId}

Także jest jakaś zależność raczej w allegro.... problemem jest że to nie failuje nie.... ustawia się lokacje i delivery, niby przechodzi tyle że dalej jest none.

**Comment by PawelTaberski** [comment]
Niestety nie bardzo rozumiem co masz na myśli. W ramach testów, aby sprawdzić, czy wszystko ok:
1/ Utworzyłem drafta
2/ pobrałem ofertę X na podstawie której utworzę nową
3/ PUT-em uzupełniłem drafta danymi z oferty X i jednocześnie wprowadziłem podesłane przez Ciebie dane do sekcji z wysyłką i lokacją i w responsie dostałem draft oferty z uzupełnionymi tymi polami.
Nie bardzo rozumiem, gdzie dostajesz none, czy te sekcje się nie uzupełniają?
Jeśli tak, to podeślij proszę przykład takiego wywołania. Potrzebowalibyśmy pełnego cURL-a i responsa wraz z traceID. Dane prześlij przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) i zaznacz w nim, że informacje są potrzebne do ticketa na GitHub numer 815.

**Comment by PiotrLaszczyk** [comment]
Już tłumacze gdzie jest bug.

1. robisz get na /sale/offers/{offerId}
2. uzupełniasz wszystkie pola 
3. robisz put na /sale/offers/{offerId}
... działa.

Ale jak zrobisz tak:
1. robisz get na /sale/offers/{offerId}
2. uzupełniasz jedno z pól... powiedzmy parameters
3. robisz put na /sale/offers/{offerId}
4. robisz get na /sale/offers/{offerId}
5. uzupełniasz jedno z pól... powiedzmy EAN
6. robisz put na /sale/offers/{offerId}
7. robisz get na /sale/offers/{offerId}
8. uzupełniasz jedno z pól... description
9. robisz put na /sale/offers/{offerId}
...
I tak kolejno wszystkie pola....i uzupełniasz tak całość... to nie da się w ten sposób uzupełnić 'location' i 'delivery'. Pomimo że każda z operacji put przejdzie bez errora..

**Comment by PawelTaberski** [comment]
Rzeczywiście :-) teraz rozumiem o co Tobie chodziło dziwna sprawa jak przesyłałem całą składnię oferty to edycja przechodzi bez problemu. Sprawę zgłosiłem do odpowiedniego zespołu. Dzięki za czujność :-).
