### ISSUE TITLE
Płatność za zamówienie

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#8150]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Mamy zamówienie checkout_form_id  "21ffe8f0-9a98-11ee-b6c4-37d16bc80188"
które zwraca z api poniższe dane
    "payment": {
        "id": "224a6050-9a98-11ee-b048-7b1ead25eb32",
        "type": "ONLINE",
        "provider": "PAYU",
        "finishedAt": "2023-12-14T15:49:50.795Z",
        "paidAmount": {
            "amount": "1562.00",
            "currency": "CZK"
        },
        "reconciliation": null
    },
    "status": "READY_FOR_PROCESSING",
    "fulfillment": {
        "status": "CANCELLED",
        "shipmentSummary": {
            "lineItemsSent": "ALL"
        }
    },
Wg frontendu zamówienie ma Płatność anulowaną, wg danych z api zamówienie jest opłacone. Czy status w polu fulfilment.status jest równoznaczny z statusem zamówienia? Czy jest w zwrotce do checkout froma jakies pole które określa jdnoznacznie czy zamówienie jest fulfilmentowe?

**Comment by MaciejFrackowiak** [comment]
Wskazane zamówienie zostało opłacone, stad status READY_FOR_PROCESSING. Fulfillment.status to wyłącznie [status realizacji zamówienia](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#zmiana-statusu-realizacji-zamowienia) nadawany przez sprzedającego. W szczegółach zamówienia nie musismy zwracać informacji, czy zamówienie jest realizowane przez usługę One Fulfillment, ponieważ na danym koncie sprzedającego sprzedaż może być tylko prowadzona jako standardowa sprzedaż bądź jako One Fulfillment, nie można łączyć ich.
