### ISSUE TITLE
Aktywacja konta firmowego sandbox

### ISSUE THREAD

**Issue by dolphinGTO** [allegro/allegro-api#8151]
Dzień dobry,
uzupełniłem wszelkie dane, m.in. wykonałem fałszywy przelew weryfikacyjny.
proszę o aktywacje konta "aps2" oraz "Am0001".
Z góry dziękuję.

**Comment by dolphinGTO** [comment]
Panie Łukaszu, oba konta mają status "Konto firmowe". Natomiast status sprzedaży jest "Nieaktywna" pomimo wykonania (fałszywego) przelewu weryfikacyjnego. Po kliknięciu w "Aktywuj sprzedaż" przenosi do strony "Zweryfikuj rachunek bankowy" gdzie nadal widnieje informacja "Weryfikujemy dane rachunku bankowego -> Proces weryfikacji może potrwać kilka dni. Poinformujemy Cię o decyzji e-mailem.".

**Comment by Lukasz-Zurek** [comment]
@dolphinGTO Konta o loginie "aps2" nie ma w naszej bazie na sandboxie. Jeśli chodzi o konto "Am0001" - masz rację, jest firmowe. Właśnie je aktywowałem.

**Comment by dolphinGTO** [comment]
Faktycznie, konto nazywa się "konto_aps2" - byłbym wdzięczny za aktywację i dziękuję za aktywowanie konta "Am0001" :)

**Comment by Lukasz-Zurek** [comment]
@dolphinGTO Nie ma problemu :) Konto "konto_aps2" również w pełni aktywne.

**Comment by dolphinGTO** [comment]
Dziękuję :)
