### ISSUE TITLE
Masowa zmiana cen i stanów

### ISSUE THREAD

**Issue by SzymonZasada** [allegro/allegro-api#8153]
Cześć
Czy w allegro istnieje zasób którym masowo zaktualizuje aukcje np. w body przekaże 1000 produktów z zaktualizowanym stanem i ceną?
Aktualnie używam zasobu  sale/product-offers/{offerID} ale przy dużej ilości aukcji trochę to trwa.

**Comment by MaciejFrackowiak** [comment]
Mamy [całą grupę zasobów](https://developer.allegro.pl/documentation/#tag/Batch-offer-modification) odpowiedzialną za masowe zmiany - jednocześnie możesz edytować do 1000 ofert. W przypadku jednak tych zasobów dana zmiana obejmuje całą grupę ofert np. gdy zwiększasz cenę o jakiś % to cena dla każdej oferty zostanie zmieniona o ten sam procent.

**Comment by SzymonZasada** [comment]
A jest możliwość masowej zmiany ceny, ale indywidualnie dla każdego produktu(np produkt a o 5% a produkt b 12%), czy w tym wypadku tylko pojedynczo?

**Comment by MaciejFrackowiak** [comment]
Tylko pojedynczo dla różnych zmian wartości.
