### ISSUE TITLE
Formatowanie wyglądu oferty przy dodawaniu jej przez API

### ISSUE THREAD

**Issue by MGabala** [allegro/allegro-api#8154]
Dzień dobry,

Pracuje nad integracją z Allegro API i między innymi będę dodawał możliwość dodawania ofert przez API na allegro. W jaki sposób można zaprogramować wygląd? Nie widzę nic na ten temat w dokumentacji API.

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Szczegółowe informacje dot. opisu oferty znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty).
