### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by acerov** [allegro/allegro-api#8155]
Hi, I am new to allegro, registered as developer and registered application, I sucessfully obtained token.
Now I am trying to post product offer but it gives me "Access denied", the same if I just try to GET sale/offers.

My last GET API call on sale/offers have Trace_id d16f2095b6b2672d

Please help,
Alen

**Comment by MaciejFrackowiak** [comment]
[GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) resource requires "bearer-token-for-user" authorization ([code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow). In your request, you used a [client_credentials](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#clientcredentials-flow) authorization which does not have a user context. Please, change authorization method.

**Comment by acerov** [comment]
Hi,

thank you for your help, BUT :)

When I am requesting token, based on "code" that I successfully received, I
changed "grant_type" from "client_credentials"  to "authorization_code" but
know I can't get token in return, I get response:

"error": "invalid_grant", "error_description": "Redirect URI mismatch"

although I send the same URI as registered in application details.

What am I doing wrong?

Thnks,
Alen

**Comment by MaciejFrackowiak** [comment]
This error message means that the redirect URI is not the same as provided in the register application. They must match 1:1, so please recheck it.

**Comment by acerov** [comment]
It is definitely the same, I checked letter by letter, last request URL was:

https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=XKaTOquRIgXd4b5dW7rJMy9OTqusSghT&redirect_uri=https://amethyst.mediacom.hr

and registered URL is https://amethyst.mediacom.hr

Alen

**Comment by MaciejFrackowiak** [comment]
I have checked our logs and the redirect URI had additional values after "https://amethyst.mediacom.hr".

**Comment by acerov** [comment]
It was not the same redirect_uri when requesting "code" and requesting
"token", I changed that and now is the same all over, wher requesting
"code", when requesting "token" and what is "registered"

On all three places it is
https://amethyst.mediacom.hr/v1/oauth/?schema=ltt_sport_trade&api=allegro

But the error remains the same: "Redirect URI mismatch"

Alen

**Comment by acerov** [comment]
Yes I just sent you another email explaining that.

Alen

**Comment by MaciejFrackowiak** [comment]
Please, do not use query params in the redirect URI path - that combination (&api=allegro) generates an issue with your authentication.

**Comment by acerov** [comment]
That was it, I removed params from redirect URI and pushed additional data
that I need through "state" and it is working now, I successfully got token.

Thank you,
Alen
