### ISSUE TITLE
Błąd 403 na środowisku produkcyjnym

### ISSUE THREAD

**Issue by WGRINGO** [allegro/allegro-api#8156]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

U wszystkich naszych klientów zaczął pojawiać się błąd autoryzacji 403/Forbidden przy generowaniu tokena. Do tej pory działało. Problem występuje tylko na środowisku produkcyjnym.

**Comment by MaciejFrackowiak** [comment]
Prośba o podanie przykładowego trace-id wywołania.

**Comment by WGRINGO** [comment]
Poprawka - na sandboxie też nie działa:
'https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiI0NDEwMjIzMiIsInNjb3BlIjpbImFsbGVncm86YXBpOm9yZGVyczpyZWFkIiwiYWxsZWdybzphcGk6cHJvZmlsZTp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOndyaXRlIiwiYWxsZWdybzphcGk6YmlsbGluZzpyZWFkIiwiYWxsZWdybzphcGk6Y2FtcGFpZ25zIiwiYWxsZWdybzphcGk6ZGlzcHV0ZXMiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczpyZWFkIiwiYWxsZWdybzphcGk6YmlkcyIsImFsbGVncm86YXBpOm9yZGVyczp3cml0ZSIsImFsbGVncm86YXBpOmFkcyIsImFsbGVncm86YXBpOnBheW1lbnRzOndyaXRlIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczp3cml0ZSIsImFsbGVncm86YXBpOnByb2ZpbGU6cmVhZCIsImFsbGVncm86YXBpOnJhdGluZ3MiLCJhbGxlZ3JvOmFwaTpzYWxlOnNldHRpbmdzOnJlYWQiLCJhbGxlZ3JvOmFwaTpwYXltZW50czpyZWFkIiwiYWxsZWdybzphcGk6bWVzc2FnaW5nIl0sImFsbGVncm9fYXBpIjp0cnVlLCJhdGkiOiI3YmU4ZWJjOC1jYmE4LTQ2OGMtYjg3ZS00MDhmMzM3MjZjNDQiLCJpc3MiOiJodHRwczovL2FsbGVncm8ucGwuYWxsZWdyb3NhbmRib3gucGwiLCJleHAiOjE3MTA3NTE1NjgsImp0aSI6IjJkODc0MmEwLTM4ZWItNGY1Yi1iNDRjLTYyOTAzODgyZjg4YSIsImNsaWVudF9pZCI6ImIyNmZlYWRmYjU0ODRlOTE5YWY1OWYyOGIwNjA4MDNiIn0.LRr0pATzx1lKaimBFRaGoWjV-Og5O7NtVkKy146eyv0yTk7kTnlldTQP1RPbUSQMBbWWhPnQaS2ljsKY5egte4jK-_xgJGvlkikV9C1HqSq7OS7JiCLEYhdsIkVgjAU-7s33UH27OD7PfoGQrarVmlIDCDUjqkcs3AGleCUhu1lYYHYOfnfA563JltvlQuQ7vTKh-7-SoOcdxMdb9Kxi4mqDwyl8OX_gnU_yvVZ7k6cgDK7AjtWqnguDExj3te2GPzUs5kBaFWCYmCzd4dkGK_NUDMR58H3k86U5HvGKOi2vPcSfTbgMftz-khbFnvsY9iEKk95FfxH6BJ6rpcH2H3Y0fnK8KD4lLDNEdKrhgyq5OJKjerJWM0fqNollQF_JmQIqBjXdEO3SH9RvM-ui-pZU-Ymg2wkgImekzbU-N8niYAVLqDbVAvburclJ5l2R-ccaH4FZ1KmsPs9SHISgUbpDNax9dHOZvNRn7MnnpXcJghj5ZA1mo0WDLD76AwM8bFvSxc09rUcCglh3PtQwZNnUlfzIVEpwotN2G7ZVUWFvLz3TQHE5EfIyCHEKNUxwOJA4HqLzsySjuSEUex8dz194frTBnrDdeJYO7FmnHExHdmGLnjhFoT9AgVPRy4pr-0OJaZ0VTfQf9VPJgx_v4LDVWzRKPxZSGN9drk3P2b0&redirect_uri=https%3A%2F%2Fproman-software.com%2F'

**Comment by WGRINGO** [comment]
To samo przy 10sekundowym kodzie:
'https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=authorization_code&code=CifHlC5jI2XPE7fVWNS7SNcD66PC1SQB&redirect_uri=https%3A%2F%2Fproman-software.com%2F'

**Comment by MaciejFrackowiak** [comment]
Na podstawie danych z Sandbox widzę, że o godz. 11:09 uzyskałeś już autoryzację dla konta i aplikacji z przykładu.

**Comment by WGRINGO** [comment]
Próbuję co jakiś czas, raz może i się udało, ale problem jest dalej:
POST 
'https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=authorization_code&code=FlSJt3InTasxCweqm8WznDFCYPzEYYj0&redirect_uri=https%3A%2F%2Fproman-software.com%2F'

'HTTP/1.0 403 Forbidden'

**Comment by MaciejFrackowiak** [comment]
W wywołaniach, w których uzyskujesz błąd nie przekazujesz ClientID. Sprawdź proszę poprawność wykonywanych operacji, skoro jak sam przyznałeś uzyskałeś autoryzację dla innego przypadku.

**Comment by WGRINGO** [comment]
Od kilku lat nie było żadnych tego typu problemów z autoryzacją do allegro REST API. Problem pojawił się dopiero dziś i to u wszystkich naszych klientów. Musiało się coś zmienić po Waszej stronie. Raz za kiedy ponowienie próby wygenerowania tokena się udaje u mnie na sandboxie ale jest to promil przypadków u klientów dalej jest problem.

Poniżej zamieszczam nagłówki requestów i jest tam ClientId

https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=b26feadfb5484e919af59f28b060803b&redirect_uri=https%3A%2F%2Fproman-software.com%2F&prompt=confirm

POST /auth/oauth/token?grant_type=authorization_code&code=qYS8pxiqjtWnjyk9jBuphEpwdebEuz2t&redirect_uri=https%3A%2F%2Fproman-software.com%2F HTTP/1.0
Content-Encoding: utf-8
Content-Length: 0
Content-Type: application/vnd.allegro.public.v1+json
Accept-Language: PL
Authorization: Basic YjI2ZmVhZGZiNTQ4NGU5MTlhZjU5ZjI4YjA2MDgwM2I6RWtrZXMyR1kxMWNyWWFwR2FzZXMyRlUxendXQ2ZQanR6dXVWeEtKR1RMMVFhOGZvWHhzb0RQcG1GWDgwdXJMcA==
Host: allegro.pl.allegrosandbox.pl
Accept: application/vnd.allegro.public.v1+json;charset=UTF-8
Accept-Encoding: identity
User-Agent: Mozilla/3.0 (compatible; Indy Library)
Cookie: datadome=pW~gc~WM45LsZ4OSJuvMYzikPQP2092JHHSSIzdCHga~G7Zh_iJCt_hABprniAkH1K8TgX007VApHrSXV4IVn8MNlfJVI1x8aOKyLDf4t0aBwQ15gQfrrr1ZVBMzWeu9

W obu przypadkach dostaję wciąż błąd HTTP/1.0 403 Forbidden zarówno powyżej jak i poniżej
 
POST /auth/oauth/token?grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiI0NDA4OTA0NyIsInNjb3BlIjpbImFsbGVncm86YXBpOm9yZGVyczpyZWFkIiwiYWxsZWdybzphcGk6cHJvZmlsZTp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOndyaXRlIiwiYWxsZWdybzphcGk6YmlsbGluZzpyZWFkIiwiYWxsZWdybzphcGk6Y2FtcGFpZ25zIiwiYWxsZWdybzphcGk6ZGlzcHV0ZXMiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczpyZWFkIiwiYWxsZWdybzphcGk6YmlkcyIsImFsbGVncm86YXBpOm9yZGVyczp3cml0ZSIsImFsbGVncm86YXBpOmFkcyIsImFsbGVncm86YXBpOnBheW1lbnRzOndyaXRlIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczp3cml0ZSIsImFsbGVncm86YXBpOnByb2ZpbGU6cmVhZCIsImFsbGVncm86YXBpOnJhdGluZ3MiLCJhbGxlZ3JvOmFwaTpzYWxlOnNldHRpbmdzOnJlYWQiLCJhbGxlZ3JvOmFwaTpwYXltZW50czpyZWFkIiwiYWxsZWdybzphcGk6bWVzc2FnaW5nIl0sImFsbGVncm9fYXBpIjp0cnVlLCJhdGkiOiI3OTNjNDU0NC1iNjU4LTQzMTMtYWEwMC00YTY0Nzk5MDZhZDciLCJpc3MiOiJodHRwczovL2FsbGVncm8ucGwuYWxsZWdyb3NhbmRib3gucGwiLCJleHAiOjE3MTA3NjI5NTQsImp0aSI6IjhmNzI2Yjg1LTIxMmQtNGEzYi05OTE0LTcyMTQ2NmQ2N2E0NCIsImNsaWVudF9pZCI6ImIyNmZlYWRmYjU0ODRlOTE5YWY1OWYyOGIwNjA4MDNiIn0.wLmr2Uwda0lMe5uMSBqVYmDV4eoKbuocdeDOijjJeNblWAvS7EsFbu4cvCTb30U5VIYLsUDYC5h0pAsRDtxPGfSmLZwHvskF4OUOXGHODzBpdJfpgxbAIBIYdPZLGxLinMyIRClfgj31ywFvnRQpbdJk3DeE6hUVXqqZQlGV90dK__rBBiYV5dBUpvZitaK5zwg8_eX_tWrr_ft4NsZkfI-sxiISXDB8_zoNn7en9tdgUFHDiwECcmojs8SUNQfIoww5pCyVndLos56IlV-bFfEdlwycs8u89dYPPiVHTmLSdhK_UyucBzLWnInOFrbyTnfNk8IFV9Y1PYQntSEXDUMs80JBApDJTvXeU8st2ZodXZDZ0Yv_EmNm3mafcaYlrE7Fu4accep5ueZ1qIlmW9VeWgBEuzoNNpe1BIBPmHlwj4kZl74tVAZ7HdAlNtBbRKf5CfSShQ6SXSoyuLHiBZxXH5frSDY8DZsPRIGNEKfIt3AIPDV4FOSQHrEOrtetZSB7zazJzFZJ5HpoPiiEF8XS35gbHBWoy53RV6Bt--KEzziKAfEkV7WAeP4AZIgB5I5gzqvYxIbV-kRS1BLxPMqaqBHZNO8Z1clHByC9TV8s7dP8SMMO6I7yrUB-VmtSx8r4IOtPRwjTeFsMgy7BSUtgejfmpf558pJh0oX-XBM&redirect_uri=https%3A%2F%2Fproman-software.com%2F HTTP/1.0
Content-Encoding: utf-8
Content-Length: 0
Content-Type: application/vnd.allegro.public.v1+json
Accept-Language: PL
Authorization: Basic YjI2ZmVhZGZiNTQ4NGU5MTlhZjU5ZjI4YjA2MDgwM2I6RWtrZXMyR1kxMWNyWWFwR2FzZXMyRlUxendXQ2ZQanR6dXVWeEtKR1RMMVFhOGZvWHhzb0RQcG1GWDgwdXJMcA==
Host: allegro.pl.allegrosandbox.pl
Accept: application/vnd.allegro.public.v1+json;charset=UTF-8
Accept-Encoding: identity
User-Agent: Mozilla/3.0 (compatible; Indy Library)

**Comment by MaciejFrackowiak** [comment]
Spojrzałem na posiadane przez nas logi i:
1) o godz. 12:55:54 otrzymałeś nową parę access token + refresh token (dokładnie ten z Twojego posta);
2) o godz. 13:17:03 zużyłeś przedmiotowy refresh token, aby otrzymać nową parę AT + RT.

W naszych logach nie widzę innych operacji opartych na wskazanym refresh tokenie.

**Comment by WGRINGO** [comment]
Bo problem pojawia się dużo wcześniej:
Włączam aplikację, chcę wygenerować nowy token w tym celu generuję nowy kod 10s za pomocą:

https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=b26feadfb5484e919af59f28b060803b&redirect_uri=https%3A%2F%2Fproman-software.com%2F&prompt=confirm'
Otrzymuję porawny kod 10s, który przekazuję za pomocą komendy POST dalej:

https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=authorization_code&code=qhOptcgHDc4ZwbPX5xm346lHmpSOjv1E&redirect_uri=https%3A%2F%2Fproman-software.com%2F'

I dostaję 'HTTP/1.0 403 Forbidden' zamiast poprawnego responsa tokenami.
Ta sama operacja kończy się sukcesem raz na kilkanaście przypadków, a tak do tej pory nie było i teraz u klientów jest problem czy to chcemy uzyskać Access token czy  refresh token - zazwyczaj otrzymujemy HTTP/1.0 403 Forbidden

**Comment by WGRINGO** [comment]
Witam, czy udało się coś popchnąć w tym temacie ? Nasi klienci coraz bardziej naciskają. Żadna firma nie umie się zautoryzować poprawnie.

**Comment by MaciejFrackowiak** [comment]
Niestety, ale nic więcej w logach nie widzimy oprócz tego co już wspomniałem - uzyskujesz dostęp do naszego API, a ewentualne błędy 401 (tylko takie widzę) dot. sytuacji, gdy nie przekazujesz ClientID. Co kluczowe - żaden z innych naszych użytkowników nie zgłasza jakiegokolwiek problemu z autoryzacją, zatem sprawdź proszę czy nic nie zmieniło się w działaniu Twojej aplikacji.

**Comment by WGRINGO** [comment]
Nic się nie zmieniało po stronie naszej aplikacji od ponad 3 lat ! 
Kluczowy problem wydaje się tutaj:

Otrzymuję porawny kod 10s, który przekazuję za pomocą komendy POST dalej:

Dlaczego to wywołanie zwraca 403 ?
https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=authorization_code&code=qhOptcgHDc4ZwbPX5xm346lHmpSOjv1E&redirect_uri=https%3A%2F%2Fproman-software.com%2F'

**Comment by MaciejFrackowiak** [comment]
W logach widzę, że wielokrotnie korzystasz z tego samego kodu ("qhOptcgHDc4ZwbPX5xm346lHmpSOjv1E"), a jest to kod jednorazowy, czyli nie ma prawa obecnie zadziałać. Przejdź proszę proces od początku z wygenerowaniem nowego kodu i jego użyciem. Dodatkowo, zanotuj proszę trace-id swoich wywołań.

**Comment by WGRINGO** [comment]
Teraz zrobiłem tak:
POST
'https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=authorization_code&code=rYO7kcna6YK9mu8MTN31FJMqH60J5yoV&redirect_uri=https%3A%2F%2Fproman-software.com%2F'

**Comment by WGRINGO** [comment]
Nie mam żadnego traceID bo to jest zwykły POST który wywala się błędem 403. Tak daleko nie dochodzi by uzyskać traceID

**Comment by WGRINGO** [comment]
Kolejny przykład:
'https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=authorization_code&code=slpZjQglaFpg2RBwwspXqFISphDUthza&redirect_uri=https%3A%2F%2Fproman-software.com%2F'
i to samo - błąd 403 fobidden.
Dlaczego taka operacja nie chce od wczoraj przechodzić skoro do tej pory działała ?

**Comment by MaciejFrackowiak** [comment]
W requeście nie przekazujesz ClientID i dlatego kończą się one niepowodzeniem. My po swojej stronie niczego nie zmieniliśmy - jesteś jedyną osobą, która zgłasza problem z autoryzacją, dlatego trudno tu mówić by serwis nie funkcjonowa właściwie.

**Comment by WGRINGO** [comment]
Dodałem CLINET_ID i nie pomogło

'https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=authorization_code&code=3LTj4nQMUkLY94fG95Ufm8znObegXB4Q&client_id=b26feadfb5484e919af59f28b060803b&redirect_uri=https://proman-software.com/'
Dalej 403

**Comment by WGRINGO** [comment]
Co mogę jeszcze zrobić, podać by rozwiązać problem? Klienci się niecierpliwią bo od wczoraj nie działa u nich  autoryzacja i nie mogą zalogować się do API. Może jest jakiś inny sposób ?

**Comment by MaciejFrackowiak** [comment]
Analizujemy posiadane logi i np. o 10:20:49 uzyskałeś autoryzację i token. Po czym o 10:31:30 starasz się kolejny raz autoryzować z kodem 10 sekundowym, który wykorzystałeś do autoryzacji o 10:20:49 - każda taka próba będzie kończyć się niepowodzeniem. Ponadto, po uzyskaniu kodu mija bardzo dużo czasu do Twojego przejścia do requestu po token - praktycznie działasz na granicy 10 sekund.

**Comment by WGRINGO** [comment]
O 10:20 udało mi się pobrać token CURLem preparując requesta. Wygląda na to, że robiąc to samo z aplikacji dostaję 403 forbidden. Musiało się w takim razie zmienić coś w ustawieniach sieciowych/obsłudze POST tego requesta 10sekundowego, która do tej pory działała, a od wczoraj już nie. A czy widać w logach jaki url jest wywoływany?  Może coś jest doklejane czego nie widzę a od jakiegoś czasu zaczęliście odrzucać takie requesty? 
Jeśli chodzi o kod 10sekundowy to wiem że zadziała on tylko w ciągu 10 sekund i to były inne próby które można zignorować.
Natomiast piszesz, że w logach widzisz udane próby bo to się udało 1 czy dwa i to będzie w logach. Natomiast w logach nie będzie tych wielu prób które skończyły się odrzuceniem requesta 403 bo podejrzewam że to serwer odrzuca, a nie aplikacja tylko nie wiem dlaczego. Dlatego trzeba by było zobaczyć logi z sewera z mojego IP 5.63.189.50.

**Comment by WGRINGO** [comment]
W sandboxie client_id jest taki
b26feadfb5484e919af59f28b060803b

Czy możecie w logach  sprawdzić co się dzieje dla pozostałych naszych klientów dla naszej aplikacji o client_id ac707bcd68474ebeb3ab467f9fbddcd9
Może tą drogą uda się coś więcej ustalić.

**Comment by MaciejFrackowiak** [comment]
W odniesieniu do produkcyjnego klucza - widzimy prawidłowe autoryzacje wykonywane przez różnych użytkowników (ostani wpis pochodzi z godz. 12:36).

**Comment by WGRINGO** [comment]
Niestety dalej u wszystkich naszych klientów to nie działa. W jednym dniu u wszystkich przestało działać mimo iż nie było u nich robione (u niektórych nawet od roku). W jednym dniu kilkunastu naszych klientów otrzymuje 403 forbidden przy wysyłaniu  POSTem linku z 10 sekundowym kodem jak już wielokrotnie wspominiałem. Musiało coś się u Was zmienić, jakaś aktualizacja czy coś bo u wszystkich to się stało wczoraj do południa. Nie wiem co jeszcze mogę zrobić. Jakieś pomysły ?

**Comment by MaciejFrackowiak** [comment]
Jeżeli uzyskałeś token po ręczym wywołaniu to znaczy, że proces autoryzacji u nas działa poprawnie. Potwierdzeniem tego jak już wspominałem, jest brak innych głosów ze strony użytkowników. W logach widzimy kolejne wywołania po kod 10 sekundowy, nie ma natomiast śladu po wywołaniach po token. Sugeruję, abyś dokładnie sprawdził działanie swojej aplikacji i wykorzystywane w niej dane. Co więcej, kolejne pomyślne autoryzacje na środowisku produkcynym pojawiają się - zatem trudno mi się zgodzić, że proces przydzielania tokenów nie działa u nas.

**Comment by MaciejFrackowiak** [comment]
Proszę podeślij przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełne Twoje wywołania wraz z odpowiedziami, które otrzymujesz. Dodaj proszę informację, że dotyczy to wątku GitHub 8156.

**Comment by WGRINGO** [comment]
Napisałem zgłoszenie. Dodam tylko, że zrobiłem tymczasowe obejście w aplikacji by póki co rozwiązać problem u klientów dlatego w logach pewnie zobaczycie, że już jest niby wszystko ok, ale tamten problem pozostał nie rozwiązany i pewnie wróci prędzej czy później w innych requestach.

Ps. Usunąłem w poprzednich postach treści tokenów. Jeśli  pozostałe dane nie są już potrzebne i  wypadało ukryć to poproszę o info.

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, widzę na Sandbox, iż kolejne wywołania autoryzacyjne kończą się powodzeniem. Gdy otrzymam Twoje zgłoszenie, to przekażę je z prośbą o weryfikację - oczywiście w odniesieniu do przeszłych dni, nie dziś. Usunięcie tokenów wystarczy - to są dane wrażliwe, reszta może zostać ;)

**Comment by WGRINGO** [comment]
Tak jeszcze informacyjnie - problem się musiał pojawić w nocy z 18 na 19 grudnia bo widzę po logach, że właśnie rano 19-tego po uruchomieniu aplikacji pojawił się pierwszy forbidden u jednego z klientów, może pomoże to dociec co się w tym czasie zmieniło.

**Comment by MaciejFrackowiak** [comment]
Otrzymałem Twoje zgłoszenie, jednak zamieszczone tam dane de facto niczym nie różnią się od tych, które podawałeś w tym wątku wcześniej. Co więcej - nadal nie wiem dlaczego ten sam kod - z Twojego mailowego przykładu jest wykorzystywany dalej? O 13:46 widzę kolejny request z jego wykorzystaniem. I co kluczowe znów bez podanego ClientID.

**Comment by WGRINGO** [comment]
Kod 10 sekundowy jest oczywiśćie za każdym razem inny. Podałem go jako przykład by było wiadomo jaki jest wykorzystywany.

Czy coś się zmieniło w wymaganiach? W dokumentacji https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow
Jest w pkt 1 wymagany parametr CLIENT_ID i ten parametr jest przekazywany w pierwszym kroku by uzyskać 10sekundowy kod autoryzacyjny. Natomiast w pkt 4 już nie jest wymagany więc go tam nie ma - tak zawsze było i czy go dodałem czy nie niczego to zmieniło. Requesty się nie zmieniają bo treść requesta jest taka sama, zmieniłem tylko komponent, który generuje tego requesta. Cały problem wynika z tego, że coś musiało się w nocy z 18 na 19 grudnia zmienić bo przestał ten request typu POST działać na tym komponencie (mowa o Indy w Delphi). Natomiast przekazując te same parametry i URL do innego komponentu (RestClient) generującego POST dostaję poprawną odpowiedź. Więc próbuję cały czas dojść do tego co zostało u Was zmienione (może zmienione było jakieś ustawienie albo jakaś aktualizacja poszła?) co spowodowało, że komponent Indy przestał być w 100% kompatybilny albo jakieś ustawienie, które działało do tej pory przestało być obsługiwane po Waszej stronie. Cała nasza aplikacja jest o niego oparta dlatego obawiam się , że prędzej czy później pojawi się podobny problem, a ja dalej nie będę wiedział gdzie szukać rozwiązania.
Nie wiem jak dokładniej opisać problem. Jeśli trzeba użyć dodatkowych narzędzi do analizy to proszę wskazać jakie.
Pozdrawiam :)

**Comment by MaciejFrackowiak** [comment]
Dzięki za dodatkowy opis, który de facto przyczynił się do znalezienia sedna sprawy. Ruch generowany przez Twoją aplikację został uznany jako mogący wywoływać negatywne skutki dla działania serwisu. I tu wskazówka - zacznij łączyć się do allegro.pl.allegrosandbox.pl po domenie (podczas połączenia TLS musi być ustawione SNI na allegro.pl.allegrosandbox.pl), a nie po adresie IP + nagłówek host. Jeżeli poprawisz to po swojej stronie to my przestaniemy taki ruch (do uzyskania tokena) blokować.

**Comment by WGRINGO** [comment]
Dziękuję bardzo za odpowiedź. Połączenie zawsze było ustawione po domenie (nie przekazuję IP), ale może komponent INDY faktycznie ma jakieś dziwne ustawienie lub przypadłość, które w locie to modyfikuje albo wymaga jakiejś dodatkowej aktualizacji i dlatego nie działa jak powinno. Po świętach postaram się to dokładniej "przetrawić" z kolegami od sieci by ogarnąć temat do końca. Tymczasem pozdrawiam i Wesołych Świąt życzę 🎄

**Comment by MaciejFrackowiak** [comment]
Dziękuję i nawzajem 🎄
