### ISSUE TITLE
Allegro-SK Metody dostaw

### ISSUE THREAD

**Issue by CSVK2022** [allegro/allegro-api#8157]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry, czy planujecie dodać identyfikator rynku słowackiego dla metod dostawy Allegro Kurier DPD/DHL?
Dla allegro-cz działa to poprawnie, wskazując przykładowo jako Allegro Kurier DPD Czechy(allegro-cz) natomiast dla rynku słowackiego brakuje nazwy rynku sprzedaży.
Ewentualnie prosiłbym o podanie id metod do czasu wdrożenia poprawki.

**Comment by MaciejFrackowiak** [comment]
Wszelkie zmiany związane z uruchomieniem domeny "allegro-sk" pojawią się na produkcji wraz z jej upublicznieniem. Stosowne zmiany z pewnością dotyczyć także będą metod dostaw.

**Comment by MaciejFrackowiak** [comment]
W szczegółach zamówienia zwracamy identyfikator marketplace, zatem to może być wskazówka do rozróżnienia testowych zamówień.

**Comment by CSVK2022** [comment]
Spróbuję sformułować inaczej problem :) 
Proszę o informację czy poniższa metoda dostawy dotyczy kanału sprzedaży Allegro-SK czy też metoda dostawy na wszystkich kanałach sprzedaży:
![image (206)](https://github.com/allegro/allegro-api/assets/105273211/dfe2cfed-e77e-4ccc-a434-5bbc7822ec14)
Poniżej zamieszczam przykład jak zwracane jest dla sprzedaży na kanale Allegro-PL: 
![image (207)](https://github.com/allegro/allegro-api/assets/105273211/4f453009-b580-42d2-a4cd-f2a75c29b8a9)

**Comment by MaciejFrackowiak** [comment]
Metoda "0c8d2e29-5826-46a5-a540-5f97a243088d" jest dedykowana pod "allegro-sk".

**Comment by CSVK2022** [comment]
Dziękuję.
