### ISSUE TITLE
Problem z dodaniem nowego kontaktu do ogłoszenia

### ISSUE THREAD

**Issue by Hornir91** [allegro/allegro-api#8158]
Dzień dobry.

Chciałbym się dowiedzieć dlaczego API odrzuca requesty przy próbie dodania nowego kontaktu przy wystawianiu ogłoszenia.

Odpowiedź, którą otrzymuję: "Seller is on virtual number list and cannot create or modify contact".

trace-id: 3e85aa69746cc4f8

**Comment by Lukasz-Zurek** [comment]
@Hornir91 Weryfikujemy obecnie ten przypadek. Co prawda konto posiada blokadę sprzedaży i teoretycznie to właśnie może być powodem błędu, jednak komunikat nie jest precyzyjny, dlatego konsultuję tę sprawę jeszcze z zespołem odpowiedzialnym za tę funkcjonalność.

**Comment by Hornir91** [comment]
Prosiłbym o wprowadzenie takiej informacji, gdyż dopiero, gdy dodałem inny kontakt do ogłoszenia, otrzymałem odpowiedź, że konto jest nieopłacone.

**Comment by Lukasz-Zurek** [comment]
@Hornir91 Chciałbym doprecyzować, że przyczyną błędu na pewno nie jest blokada sprzedaży. Wyjaśniamy jeszcze ten przypadek. Oczywiście wkrótce wrócę ze szczegółami.

**Comment by Hornir91** [comment]
Dobrze, to czekam na informacje w tej sprawie.

**Comment by Hornir91** [comment]
Dobrze. Dziękuję bardzo za informację.
