### ISSUE TITLE
Aktywacja konta na sandboxie

### ISSUE THREAD

**Issue by bart-katowice** [allegro/allegro-api#8159]
te_klient@allegro.pl
Konto do testowych zakupów

**Comment by Lukasz-Zurek** [comment]
@bart-katowice Powiadomienia na sandboxie posiadają załączniki w formacie *eml. Tego typu wiadomości mogą być odczytywane jako spam. Upewnij się proszę czy tak nie było i w tej sytuacji.

Dodatkowo podaj proszę adres e-mail - sprawdzę nasze logi.
