### ISSUE TITLE
Zasymulowanie zmiany statusu przesyłki

### ISSUE THREAD

**Issue by pzareba86** [allegro/allegro-api#8160]
Dzień dobry,
prosze o zasymulowanie zmiany statusu przesyłki i dodanie nr listu dla paczki inpost, mój nr zwrotu:

15 gru 2023 15:08 3PQZ/2023

**Comment by Lukasz-Zurek** [comment]
@pzareba86 Wskaż proszę jeszcze:

- login kupującego, 
- login sprzedającego,
- listę statusów z datą do ustawienia, np.:

_1 paź 2023 17:00 - Nadanie
2 paź 2023 01:00 - W drodze
2 paź 2023 13:00 - Doręczono_

**Comment by pzareba86** [comment]
podaję brakujące dane: 
login kupującego: Client:94508961
p.zareba@otcf.pl

login sprzedającego: sportcitytest
sport_city@4f.com.pl

statusy: 
15.12 Nadanie 
18.12 W drodze
19.12-Doręczono

**Comment by Lukasz-Zurek** [comment]
@pzareba86 Dziękuję. Przekazałem do odpowiedniego zespołu. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@pzareba86 Statusy przesyłki wprowadzone. Proszę sprawdzić.

**Comment by pzareba86** [comment]
Dziękuję, wszystko się zgadza, nr dodany:)
