### ISSUE TITLE
Jak uzyskać cenę produktu?

### ISSUE THREAD

**Issue by edpol27** [allegro/allegro-api#8162]
Tworzę zapytanie, używając wyszukiwanych słów, na przykład:

https://api.allegro.pl/sale/products?phrase=Lampki

Dostaję listę produktów, które nie mają ceny. Na stronie internetowej znajdują się ceny tych produktów.

https://api.allegro.pl/sale/products/{productId}

Otrzymuję wszystkie dane o produkcie z wyjątkiem ceny i waluty.

Jak mogę wykorzystać otrzymane dane produktu, aby poznać cenę i walutę?

**Comment by Lukasz-Zurek** [comment]
W naszym API nie udostępniamy takiej możliwości.

**Comment by edpol27** [comment]
Jeśli nie mogę uzyskać ceny produktu, to jaki jest sens takiego produktu z całym jego opisem i cechami? Zawsze uważałem, że cena produktu powinna być najważniejsza. Kto stworzył tak dziwne API?

**Comment by Lukasz-Zurek** [comment]
@edpol27 Musisz tutaj przede wszystkich odróżnić produkt od oferty, ponieważ to nie jest to samo. Produkt sam w sobie nie posiada ceny. Cenę posiada oferta, więc informacje te, jak i również pozostałe szczegóły (włącznie z przypisanym do niej produktem) sprawdzisz za pomocą [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getProductOffer), będąc zalogowanym jako Sprzedawca. Listę ofert na koncie pobierzesz za pomocą [GET / sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET).

Jeżeli natomiast chcesz poprzez API wyszukiwać oferty według identyfikatorów produktów - nie jest to możliwe.

**Comment by edpol27** [comment]
Rozumiem, że produkt i oferta są różne. Ale mogę znaleźć ofertę innego sprzedawcy za pomocą API. Dlaczego nie mogę sprawdzić ceny tej oferty wyświetlanej na stronie? Jaki jest zatem sens otrzymywania ofert od innego sprzedawcy poprzez API bez ceny za tę ofertę? Czy mogę w jakiś sposób znaleźć {offerId} danej oferty poprzez API, korzystając z identyfikatora oferty lub innych jej danych?

**Comment by Lukasz-Zurek** [comment]
Nie, w naszym API nie ma takiej możliwości. Możesz oczywiście korzystać z odpowiednika wyszukiwarki naszego Serwisu za pomocą [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) - jednakże dostęp do tego zasobu mają tylko zweryfikowane aplikacje. Więcej informacji znajdziesz [tutaj](https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk#jak-wyszukiwac-i-przegladac-oferty).

Nawet jeśli uzyskasz dostęp do wspomnianego zasobu, nie wyfiltrujesz ofert innych użytkowników wg. numeru oferty, czy też identyfikatora produktu.
