### ISSUE TITLE
Nieistniejący produkt przypisany do oferty

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#8164]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Problem dotyczy oferty o identyfikatorze 14914410417 w środowisku produkcyjnym. Oferta ma przypisany produkt o identyfikatorze 
```
"id": "48011546-d690-481d-a828-c1b0cfe3a488",
                "publication": {
                    "status": "LISTED"
                },
```
Próbując pobrać te produkt otrzymuje informacje, że produkt nie istnieje
```
{
            "code": "ProductNotFound",
            "message": "There is no product matched to provided requirements",
            "details": null,
            "path": null,
            "userMessage": "Nie znaleziono produktu spełnijącego kryteria żądania."
        }
```
Przy próbie odpięcia produktu (przesłania null w polu id) otrzymuję odpowiedź
```
{
            "code": "RemoveProductException",
            "message": "Unprocessable Entity",
            "details": null,
            "path": "productSet[0].product",
            "userMessage": "Unable to unlink product from offer."
        }
```

Ofertę z poziomu formularza allegro można opublikować.
Występuje pewna niespójność produkt ma status `LISTED` a próba pobrania go kończy się błędem 404
Co powinienem zrobić w tej sytuacji? Jak połączyć ofertę z nowym produktem?

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, potwierdzam zauważoną przez Ciebie przypadłość mechanizmu. Jeżeli produkt został w międzyczasie usunięty z naszej bazy produktów, to nie jest usuwany jego identyfikator ze szkicu oferty. Na chwilę obecną mechanizm ten tak działa. Wiemy, iż nie jest to rozwiązanie pożądane, dlatego będzie to omawiane przez zespoły odpowiedzialne za funkcjonowanie zasobu.
