### ISSUE TITLE
API nie zwraca wszystkich płatności.

### ISSUE THREAD

**Issue by pawel-karpinski** [allegro/allegro-api#8165]
Występuje problem:
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

API nie zwraca nam kompletu płatności.

Dla poniższego requesta dla płatności z dnia 19.12.2023, dostajemy odpowiedniego responsa.
request:
curl -X GET\

'https://api.allegro.pl/payments/payment-operations?&payment.id=0a757fa2-9e62-11ee-8318-6189d0bbb14e&limit=100&offset=0'

-H 'Authorization: Bearer {token}' 
-H 'Accept: application/vnd.allegro.public.v1+json'

response: **ISTNIEJA DANE - brak problemu**

Dla poniższego requesta, pomimo tego, że w panelu jest informacja dotycząca płatności w dniu 19.12.2023 o opłaceniu to z API nie dostajemy response'a.

request:
curl -X GET\

'https://api.allegro.pl/payments/payment-operations?&payment.id=46e07a86-9e51-11ee-a466-87e0c867a59b&limit=100&offset=0'

-H 'Authorization: Bearer {token}' 
-H 'Accept: application/vnd.allegro.public.v1+json'

response: 
{
    "paymentOperations": [],
    "count": 0,
    "totalCount": 0
}

Takich płatności których nie możemy pobrać jest co najmniej kilka.

**Comment by MaciejFrackowiak** [comment]
Skonsultowałem Twój przypadek z zespołem odpowiedzialnym za zasób - w przypadku drugiej płatności została ona objęta opóźnieniem wypłaty, stąd nie jest jeszcze widoczna w historii operacji.

**Comment by pawel-karpinski** [comment]
Dziękuję.
W jaki sposób osoba obsługująca panel może w takim razie rozróżnić ten status płatności ? 
W tym momencie widzi ona, że zamówienie jest **opłacone** z tym id transakcji : 
![image](https://github.com/allegro/allegro-api/assets/89241687/671ee5de-6a52-4cba-b531-64d66f687398)

**Comment by MaciejFrackowiak** [comment]
Co do zasady - zamówienie jest opłacone (posiada status READY_FOR_PROCESSING). Dane te powinny być widoczne w zakładce [Środki i historia operacji](https://allegro.pl/moje-allegro/sprzedaz/srodki-i-historia-operacji?sellerId=8840276&dateFrom=2023-11-21&dateTo=2023-12-21) - tu jednak po szczegóły proszę skontaktuj się [bezpośrednio z obsługą Allegro](https://allegro.pl/pomoc/kontakt).

**Comment by pawel-karpinski** [comment]
Dziękuję bardzo.
Czy istnieje endpoint to pobrania informacji z zakładki Środki i historia operacji ? 
Nie mogę tego znaleźć w dokumentacji API.

**Comment by MaciejFrackowiak** [comment]
Jest to właśnie endpoint [GET /payments/payment-operations](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory). Warto zwrócić tu uwagę na jeden z dostępnych filtrów - "wallet.type" - gdy wybierzesz dla niego wartość "WAITING" to wówczas w wynikach uzyskasz informacje o drugiej płatności z Twojego przykładu. Domyślnie, gdy nie określisz wartości to zwracamy tylko operacje type "AVAILABLE".

**Comment by pawel-karpinski** [comment]
Super, 
ze strony technicznej mam wszystko czego chciałem.
Dziękuję za pomoc.
