### ISSUE TITLE
WZA: Processing error, Allegro Kurier24 InPost pobranie

### ISSUE THREAD

**Issue by mmodrzejewski** [allegro/allegro-api#8166]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry

Problem dotyczy zamówienia:
862588c0-9f9e-11ee-b27f-dd8c2bb26cff

Nie można nadać paczki. Z API zwracane jest tylko klasyczne
"Processing error"

Przykładowe traceId
cdf8cd5c-1fb7-440c-9d26-549b67b62eb2
5c4e106f-c853-451c-a50b-07507f1694f0
7310b5c9-ab49-417d-af1f-623cca3d9ebe

Rzuciłem okiem: wymiary paczki są ok, waga też. Przypisano pobranie. 

API mogłoby zwracać cokolwiek więcej. Obecna forma nie mówi nic. To kolejny taki enigmatyczny przypadek.

**Comment by MaciejFrackowiak** [comment]
W tym przypadku problemem jest wysokość pobrania vs ubezpieczenie: Pobranie nie może być większe niż ubezpieczenie przesyłki (218,88 zł).
