### ISSUE TITLE
WZA:  Opennet API cannot process request / BAD_REQUEST,  Allegro One

### ISSUE THREAD

**Issue by mmodrzejewski** [allegro/allegro-api#8167]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry

Problem dotyczy zamówienia
612f2f42-9ae3-11ee-9a9d-bd5281995d1f

Nadanie w metodzie:
0e40225c-32c6-4602-b78f-b3146fe9f54a

Zlecenie nadania paczki zwróciło:

message: Opennet API cannot process request
code: BAD_REQUEST
..
Nie sposób z tego wywróżyć, gdzie jest błąd ani jego przyczyny. 
Czy błąd jest po naszej stronie, czy z awarii przewoźnika?

Przykładowe traceId
d3152f41-2bcd-403e-8bc2-f8a2a7d38570

**Comment by Lukasz-Zurek** [comment]
@mmodrzejewski Dziękuję za zgłoszenie. Weryfikujemy. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@mmodrzejewski Konsultujemy jeszcze temat z operatorem logistycznym. Proszę o cierpliwość.

**Comment by mmodrzejewski** [comment]
OK, dziękuję za informację.
Czekam więc na odpowiedź.

**Comment by mmodrzejewski** [comment]
Nie dostałem odpowiedzi w tej sprawie.

**Comment by Lukasz-Zurek** [comment]
@mmodrzejewski Dopytuję zespołu o szczegóły. Przepraszam za długi czas oczekiwania z uwagi na konieczność konsultacji z operatorem logistycznym.

**Comment by Lukasz-Zurek** [comment]
@mmodrzejewski Wszystko wskazuje na to, że to dość częsty problem po stronie naszego operatora, tzn. zlecenie utworzenia przesyłki prawdopodobnie mogło zostać częściowo przyjęte, jednak zanim zostało przetworzone, otrzymaliśmy (i zwróciliśmy) błąd. Czy bylibyście w stanie powtórzyć próbę pobrania etykiety?

Serdecznie przepraszamy za zaistniałe utrudnienia. Nie bagatelizujemy jednak problemu i zostanie on zaopiekowany, tak aby się nie powtarzał.
