### ISSUE TITLE
Ogłoszenia z zaznaczoną opcją republish zostają zakończone

### ISSUE THREAD

**Issue by Hornir91** [allegro/allegro-api#8168]
Dzień dobry.

Kilka miesięcy temu włączyliśmy u klienta opcję automatycznego wznawiania ogłoszeń Allegro. Od pewnego czasu odnotowujemy, że ogłoszenia pomimo tego, iż mają zaznaczoną tą opcję, automatycznie się kończą, np. ogłoszenie o ID: 14571443372.

Wartość parametru publication tego ogłoszenia:

`"publication": {
        "status": "ENDED",
        "duration": "PT720H",
        "endedBy": "EXPIRATION",
        "endingAt": "2023-11-25T15:37:08.000Z",
        "startingAt": null,
        "republish": true,
        "marketplaces": {
            "base": {
                "id": "allegro-pl"
            },
            "additional": []
        }
    },`
Mógłbym dowiedzieć się z czego wynika ten problem?

Chciałbym też zaznaczyć, iż kontaktowałem się już wcześniej w tej sprawie, otrzymując zapewnienie, że problem zostanie rozwiązany.

**Comment by MaciejFrackowiak** [comment]
Niestety, ale nie posiadamy już logów z 25.11.2023, kiedy wskazana oferta zakończyła się.

**Comment by Hornir91** [comment]
W takim razie prosiłbym o sprawdzenie tego ogłoszenia: 14734852210

**Comment by MaciejFrackowiak** [comment]
Wskazana oferta 14734852210 nie została wznowiona z uwagi na aktywną blokadę sprzedaży na koncie.

**Comment by Hornir91** [comment]
Dobrze, dziękuję za informację.
