### ISSUE TITLE
c2c-payu-simulator.dh-test.qxlint nie działa

### ISSUE THREAD

**Issue by PanS4ge** [allegro/allegro-api#8169]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [x] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Nie działa link, który zakładam ma symulować PayU.

Link, that I think is supposed to simulate PayU, doesn't work..

**Comment by MaciejFrackowiak** [comment]
Proszę doprecyzuj - w trakcie, którego procesu pojawiło się u Ciebie przekierowanie do podanego adresu WWW?

**Comment by PanS4ge** [comment]
jak przechodzę do płatności na sandbox allegro.
sprawdziłem pihole oraz adblockery

https://github.com/allegro/allegro-api/assets/69396555/239dd4d7-6847-40d8-a56f-a048d1151fba

**Comment by MaciejFrackowiak** [comment]
Proszę podaj login Twojego konta z Sandbox.

**Comment by PanS4ge** [comment]
PanSageYT

**Comment by MaciejFrackowiak** [comment]
Twoje konto jest już aktywne.
