### ISSUE TITLE
[SANDBOX] problem z uploadem zdjęć do aukcji

### ISSUE THREAD

**Issue by coobitus** [allegro/allegro-api#817]
Od rana mam problem z wrzucaniem zdjęć do aukcji - zwraca mi Internal server error .... Możecie to naprawić asapowo? Adres którego używam to https://upload.allegro.pl.allegrosandbox.pl/sale/images

**Comment by coobitus** [comment]
Heh, zdaje się, że generalnie wystawianie ofert w tej chwili zwraca Internal server error :-)

**Comment by PawelTaberski** [comment]
Problem nie powinien już występować.

**Comment by Qenozis** [comment]
Niestety problem nie zniknął - zdjęć nie da się wgrywać z powodu bliżej nieokreślonego błędu:

{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/images","userMessage":null}]}

Wszystko wykonane zgodnie z lakoniczną i mega skąpą (1-zdaniowią) instrukcją, jaką do tej pory Allegro z bólem wypuściło w świat, ale to i tak sypie wyłącznie dziwnymi błędami. W dokumentacji brak jakiegokolwiek wpisu, mimo zapewnień od kilku miesięcy. Sprawdzałem "działające" rozwiązania z forum - mam niby poprawny kod, a i tak po stronie Allegro wali tym błędem. No chyba że ten błąd to poprawne działanie tego systemu... :O

**Comment by PawelTaberski** [comment]
@Qenozis tak jak odp Tobie tutaj #239 
Przetestowałem jeszcze przed sekundą. Wszystko znajduje się w naszej dokumentacji. Przy opisach zasobów nie podajemy za każdym razem adresu wywołania na środowisku testowym i produkcji. Pokazujemy przykładowe użycie tylko na produkcji.
Opis tego zasobu tak jak podlinkowałeś znajduje się [tutaj](https://developer.allegro.pl/sale/#step-3-images).
Natomiast adresy do środowiska testowego znajdziesz [tutaj](https://developer.allegro.pl/about/#Sandbox).
W przypadku tego zasobu prawidłowy adres wywołania to: 
`https://upload.allegro.pl.allegrosandbox.pl/sale/images`
Przykładowe wywołanie:
`curl -X POST \
  https://upload.allegro.pl.allegrosandbox.pl/sale/images \
  -H 'Authorization: Bearer tu wklej token' \
  -H 'accept: application/vnd.allegro.public.v1+json' \
  -H 'content-type: image/png'`

**Comment by avello** [comment]
Dzisiaj znowu występuje błąd z uploadem zdjęć.
Wczoraj ten sam skrypt działał.
Zwracany jest błąd 500 Internal server error.

**Comment by PawelTaberski** [comment]
@avello Rozumiem, że chodzi Tobie o środowisko testowe, sprawdziłem i rzeczywiście jest jakiś problem, sprawę zgłosiłem do zespołu odpowiedzialnego za ten zasób proszę o cierpliwość.

**Comment by runaway90** [comment]
@PawelTaberski hejka, mam podobny dzisz problem =(

**Comment by PawelTaberski** [comment]
Przetestowałem i zasób działa poprawnie , czy u Ciebie problem dalej występuje?

**Comment by runaway90** [comment]
@PawelTaberski działa, ale dostałem 422 Unprocessable Entity, czy może coś nie tak przekazuję? (urzywam Guzzle).
```
$response = $client->createClientRequest()->post('https://upload.allegro.pl.allegrosandbox.pl/sale/images', [
                'headers' => [
                    'Authorization' => "Bearer " . $token,
                    'Accept' => 'application/vnd.allegro.public.v1+json',
                    'content-type' => 'application/vnd.allegro.public.v1+json',
                ],
                    'json' =>
                        [
                            'url' => "https://[name].pl/wp-content/uploads/2018/04/img_article7.png"
                        ],
```

**Comment by PawelTaberski** [comment]
Wydaje mi się, że problemem może być że wysyłasz w formie tablicy, a powinno być:
```
  -d '{
       "url":"https://imgur.com/1aOIvg3E.jpg"       -- wymagane, link do obrazka
      }'     
```
Więcej na ten temat [tutaj](https://developer.allegro.pl/sale/#step-3-images).

**Comment by neldh** [comment]
to nie to Pawle. 'json' zamienia tablicę na postać json w Guzzle

**Comment by PawelTaberski** [comment]
Rozumiem, sprawdziłem jeszcze raz i zasób działa poprawnie, problemem musi być sam adres, próbowałeś przetestować z innym adresem?

**Comment by runaway90** [comment]
Pablo, przetestowałem ręcznie. 
Guzzle jest poprawny(czyli tak trzeba go urzywać). Problem był nie w nim. 
Wygłąda to tak że z parą plików mam 422-ą, naprzykład "https://contelizer.pl/wp-content/uploads/2018/04/img_article7.png" a z innymi dobrze idzię. Niewiadomo dlaczego. Wczesznej nie było takiego...

**Comment by PawelTaberski** [comment]
Wygląda na to, że jest jakiś problem z połączeniem się z serwerem na jakim trzymasz zdjęcia i pobraniem ich, czy wcześniej działało zaciąganie zdjęć z tego serwera?

**Comment by runaway90** [comment]
@PawelTaberski tak, wygłąda że z firmowych serwerów nie wychodzą zdęjcia. Czy mogę poprosić o wysylce w calości tego komunikata(error-wiadomość z serwera) -> "Image from the given (truncated...)". Nie widzie co przychodzi w calości...

**Comment by runaway90** [comment]
![screenshot 2](https://user-images.githubusercontent.com/20610334/52847380-4c3dd500-310c-11e9-8f4b-9e02659cda9f.png)

**Comment by PawelTaberski** [comment]
Cały komunikat:
```
{
    "errors": [
        {
            "code": "422",
            "message": "Unprocessable entity",
            "details": null,
            "path": null,
            "userMessage": "Image from the given address can not be downloaded. Connection error."
        }
    ]
}
```

**Comment by runaway90** [comment]
@PawelTaberski dziekuję będę sprawdzał dalej. Odpiszę jak coś znajdę.

**Comment by chryssalid** [comment]
Chciałbym się pod temat podpiąć. Próba wysłania zasobu [https://images.ksiazkiniegryza.pl/thumb/500/0/zoom/olejesiuk/978-83-61635-89-5.jpg](https://images.ksiazkiniegryza.pl/thumb/500/0/zoom/olejesiuk/978-83-61635-89-5.jpg) kończy się błędem:

`{"errors":[{"code":"415","message":"415 Unsupported Media Type","details":null,"path":null,"userMessage":"Unallowed image type."}]}`

[](url)

**Comment by PawelTaberski** [comment]
@chryssalid Rzeczywiście w tym wypadku jeśli prześlesz http zamiast https dostaniesz taki błąd, zgłosiłem prośbę o poprawę komunikatu tego błędu.

**Comment by chryssalid** [comment]
@PawelTaberski mam kolejną przypadłość, podobny zasób (wysyłany poprzez link): [https://images.ksiazkiniegryza.pl/thumb/500/0/zoom/olejesiuk/978-83-7183-757-9.jpg](https://images.ksiazkiniegryza.pl/thumb/500/0/zoom/olejesiuk/978-83-7183-757-9.jpg) ale tym razem kończy się to:

`{"errors":[{"code":"NotAllowedException","message":"An error has occurred","details":null,"path":null,"userMessage":"An error occurred"}]}`

**Comment by PawelTaberski** [comment]
@chryssalid Komunikat błędu poprawiony.

**Comment by kkrol93** [comment]
Hej czy na sandboxie wszystko działa?  
{
    "errors": [
        {
            "code": "500",
            "message": "Internal server error",
            "details": null,
            "path": null,
            "userMessage": "Internal server error."
        }
    ]
}
chciałem przetestować działanie uploadu i nie mogę się dostać :(

**Comment by PawelTaberski** [comment]
@kkrol93 A z jakim zasobem masz problem przetestowałem POST /sale/images i wydaje się, że wszystko działa poprawnie otrzymałem normalnie 201.

**Comment by kkrol93** [comment]
właśnie images :)  próbuje postmanem  https://upload.allegro.pl.allegrosandbox.pl/sale/images?url=https://imgur.com/1aOIvg3E.jpg . Contet-type: application/vnd.allegro.public.v1+json 
acceept: application/vnd.allegro.public.v1+json

**Comment by PawelTaberski** [comment]
Rozumiem, że przesyłasz na podstawie linka wtedy w body powinieneś dodać:
{
	"url":"https://imgur.com/1aOIvg3E.jpg"
}
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-3-images).

**Comment by kkrol93** [comment]
dodaje jako parametr , ale pytanie czy na tym etapie to nie ma znaczenia czy poprawnie wysyłam url? jak mam error 500?

**Comment by kkrol93** [comment]
ok działa zrobiłem to curlami i jest ok sorki za kłopot

**Comment by pietroczuk** [comment]
Witam, czy dziś coś się dzieje z uploadem? dostaje error 500
Wgrywam np 5 zdjęć, 4 - ok (201), 5 - err 500. Kolejna próba od razu 500.
Jak odczekam z 30 min, to pierwsze 1-4 wgrywa, później 500

**Comment by MaciejFrackowiak** [comment]
Nie, nie odnotowaliśmy żadnego problemu. Proszę podaj nam trace-id jakie otrzymałeś.

**Comment by Nemanja-Lima** [comment]
Hi guys, can someone help me with this problem?

        $data = ["url" => "https://www.mytrendyphone.pl//images2/Goobay-HDMI-Extension-Cable-withEthernet-5m-02082018-01-p.jpg"];

        $setOffers = "https://upload.allegro.pl.allegrosandbox.pl/sale/images";
        $client = new GuzzleHttp\Client(['verify' => false]);

        try {
            $res = $client->request('POST', $setOffers, [
                'headers' => ["Authorization" => 'Bearer ' . Cache::get('token_allegro'), "Accept" => "application/vnd.allegro.public.v1+json", 'Content-Type: application/vnd.allegro.public.v1+json'],
                'body' => json_encode($data)
            ]);
            $res = json_decode($res->getBody()->getContents());
            return response()->json(['data' => $res]);
        } catch (GuzzleHttp\Exception\GuzzleException $e) {
            $response = $e->getResponse();

            $result = json_decode($response->getBody()->getContents());
            return response()->json(['Photo error data' => $result]);

        }


and response is:

         {
            "Photo error data": {
                        "errors": [{
                                        "code": "415 UNSUPPORTED_MEDIA_TYPE",
                                        "message": null,
                                        "details": null,
                                        "path": null,
                                        "userMessage": "Unallowed image type."
                                     }]
                          }
        }

I think that image fits your requirement.

**Comment by TimothyKoval** [comment]
@Nemanja-Lima 
```
curl -I https://www.mytrendyphone.pl//images2/Goobay-HDMI-Extension-Cable-withEthernet-5m-02082018-01-p.jpg
HTTP/1.1 404 Not Found
```

**Comment by Nemanja-Lima** [comment]
Sry i removed - when i pasted code :/
so url si 
https://www.mytrendyphone.pl//images2/Goobay-HDMI-Extension-Cable-with-Ethernet-5m-02082018-01-p.jpg

**Comment by PrzemyslawLukanowski** [comment]
I tried to upload this picture - in response I've received status 200 with link to the image. Due to multiple programming language we don't provide support for each of them. Could you please send us full request in cURL format via our [contact form](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) with a note - GitHub #2528.
