### ISSUE TITLE
WZA-- Allegro One - Address error

### ISSUE THREAD

**Issue by 2024OPH** [allegro/allegro-api#8170]
Since starting to use the Allegro one logistics channel, the ZWA system has frequently prompted buyers with abnormal addresses.
The ZWA system cannot capture the buyer's address, resulting in the MBB system being unable to generate a logistics order number for the order, resulting in our inability to deliver goods to the buyer in time.

**Comment by MaciejFrackowiak** [comment]
Could you give us an example?

**Comment by 2024OPH** [comment]
1. In all logistics channels of Allegro SMART, the WZA system frequently prompts the buyer’s address to be abnormal.

2. The WZA system cannot capture the buyer's address information and considers the buyer's address to be invalid. As a result, the MBB system cannot generate a logistics tracking number for the order - without a logistics order number, MBB cannot ship to the buyer, resulting in the failure to deliver the goods in time. into the hands of buyers.

a. SMART orders from the official warehouse will not be unable to be shipped due to abnormal addresses.
b. If the order with an abnormal address is changed to a non-SMART logistics channel - the order can be sent normally.

**Comment by 2024OPH** [comment]
![2688980b78b3a724631b2943212a767](https://github.com/allegro/allegro-api/assets/143609500/89e496d6-4097-471d-80d6-d0b77d892546)

**Comment by MaciejFrackowiak** [comment]
Unfortunately, this is not a log from Allegro API. Moreover, if you prepare a correct request for shipment, all the necessary details will be available. It looks like your mechanism issue only.
