### ISSUE TITLE
Fulfillment - basic fee  obtain

### ISSUE THREAD

**Issue by yao657355700** [allegro/allegro-api#8171]
How to obtain the information for each order
Fulfillment - basic fee
Cost.
Do you have an API interface for this fee?

**Comment by MaciejFrackowiak** [comment]
Any billing entry you will find with [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries) resource.

**Comment by yao657355700** [comment]
GET/billing/billing entries
Only the total number can be obtained here
How much do I need to obtain for each order

**Comment by yao657355700** [comment]
> Any billing entry you will find with [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries) resource.

GET/billing/billing entries
Only the total number can be obtained here
How much do I need to obtain for each order

**Comment by MaciejFrackowiak** [comment]
Please, use available filters e.g. "order.id" to retrieve charges for the selected order.

**Comment by yao657355700** [comment]
> Please, use available filters e.g. "order.id" to retrieve charges for the selected order.

Retrieved using order number.
But there is no Fulfillment - basic fee for the order

**Comment by yao657355700** [comment]
> Please, use available filters e.g. "order.id" to retrieve charges for the selected order.

/Billing/billing entries? Order.id=
This API interface will not return fees of OFA type

**Comment by MaciejFrackowiak** [comment]
The fee is charged by the offer, not by the order.

**Comment by yao657355700** [comment]
> The fee is charged by the offer, not by the order.

Which API interface can I obtain the offer from?

**Comment by MaciejFrackowiak** [comment]
If you retrieve billing entries, you will see the structure like this:
```
{
    "billingEntries": [
        {
            "id": "7fd6e8bd-3b32-xxx-b51b-5a878cc00570",
            "occurredAt": "2023-12-22T01:00:19.589Z",
            "type": {
                "id": "OFA",
                "name": "Fulfillment — basic fee"
            },
            "offer": {
                "id": "7fd6e8bd-3b32-xxxx-b51b-5a878cc00570",
                "name": "Number of products (122)"
            },
            "value": {
                "amount": "-864.42",
                "currency": "PLN"
            },
            "tax": {
                "percentage": "23.00"
            },
            "balance": {
                "amount": "-12997.60",
                "currency": "PLN"
            }
        }
```

**Comment by yao657355700** [comment]
> If you retrieve billing entries, you will see the structure like this:
> 
> ```
> {
>     "billingEntries": [
>         {
>             "id": "7fd6e8bd-3b32-xxx-b51b-5a878cc00570",
>             "occurredAt": "2023-12-22T01:00:19.589Z",
>             "type": {
>                 "id": "OFA",
>                 "name": "Fulfillment — basic fee"
>             },
>             "offer": {
>                 "id": "7fd6e8bd-3b32-xxxx-b51b-5a878cc00570",
>                 "name": "Number of products (122)"
>             },
>             "value": {
>                 "amount": "-864.42",
>                 "currency": "PLN"
>             },
>             "tax": {
>                 "percentage": "23.00"
>             },
>             "balance": {
>                 "amount": "-12997.60",
>                 "currency": "PLN"
>             }
>         }
> ```

![345](https://github.com/allegro/allegro-api/assets/87019541/fb4617c1-8584-4522-90b8-d57b4ae2464c)
I need to obtain the detailed data for this,
Where can I get it from?

**Comment by yao657355700** [comment]
Because I need to calculate all the actual costs for each order.
So I need to obtain this fee

**Comment by yao657355700** [comment]
Will these detailed API features be enabled in the future?

**Comment by yao657355700** [comment]
> Unfortunately, you will not receive such information via API.

Is there an API interface to obtain size and weight information for each product?

**Comment by MaciejFrackowiak** [comment]
No, these data are not available via API. All the available fulfillment resources you can find in [our documentation](https://developer.allegro.pl/documentation/#tag/Advance-Ship-Notices).

**Comment by yao657355700** [comment]
> No, these data are not available via API. All the available fulfillment resources you can find in [our documentation](https://developer.allegro.pl/documentation/#tag/Advance-Ship-Notices).

This is not comprehensive.
How do I calculate costs and keep accounts?

**Comment by MaciejFrackowiak** [comment]
We are not responsible for One Fulfillment service. Please, submit your comments to your account manager.

**Comment by yao657355700** [comment]
> We are not responsible for One Fulfillment service. Please, submit your comments to your account manager.

Are you responsible for developing API interface functionality?

**Comment by MaciejFrackowiak** [comment]
If you want any new functionality, you can submit your suggestion to our [Discussions tab](https://github.com/allegro/allegro-api/discussions) where we collect them.

**Comment by yao657355700** [comment]
ok
Wishing you a Merry Christmas

**Comment by MaciejFrackowiak** [comment]
Thank you, and all the best to you!
