### ISSUE TITLE
Wystawianie ofery przy użyciu https://api.allegro.pl/sale/product-offers

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#8175]
Hej,
czy może mi ktoś podpowiedzieć czy przy wykorzystaniu zasobu https://api.allegro.pl/sale/product-offers do wystawiania oferty mam możliwość dodania swojej nazwy, opisu, zdjęć?

Czy jak już wystawiam podając identyfikator produktu to nie mam wpływu na to co jest w opisie itd.

  "productSet": [{
    "product": {
      "id": "5902719471797",        
      "idType": "GTIN"
    }}],

Czy muszę tworzyć nowy produkt w katalogu? Co się stanie jeżeli będę chciał stworzyć produkt z eanem który już jest w katalogu allegro?

Czy zadziała tak:
    "productSet": [{
        "product": {
      "id": "5902719471797",        
      "idType": "GTIN"
      "name":"Produkt testowy",
                  "category":{
                       "id":"258020"
              },
 ?

I jak mogę wskazać własny opis i zdjęcia?

Pozdrawiam
Aleksy

**Comment by jezewskiBNetrox** [comment]
Dużo podstaw wyjaśniają poradniki, które polecam: https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA

**Comment by AleksyZajac** [comment]
Super że wskazałeś poradnik ale już się z nim zapoznałem.

Nie ma tam informacji jak zachowa się system jak będę chciał wystawić produkt z eanem który mają już w bazie.

Zakładam że system nie pozwoli tego zrobić, jak mam więc zmodyfikować opis czy dodać swoje zdjecia?

**Comment by jezewskiBNetrox** [comment]
> Super że wskazałeś poradnik ale już się z nim zapoznałem.
@AleksyZajac Jednak są tam odpowiedzi na takie pytanie jak: "I jak mogę wskazać własny opis i zdjęcia?"
> Nie ma tam informacji jak zachowa się system jak będę chciał wystawić produkt z eanem który mają już w bazie.
@AleksyZajac https://github.com/allegro/allegro-api/issues/8152
> Zakładam że system nie pozwoli tego zrobić, jak mam więc zmodyfikować opis czy dodać swoje zdjecia?
Jest w poradniku.

**Comment by Lukasz-Zurek** [comment]
@AleksyZajac 

> Hej, czy może mi ktoś podpowiedzieć czy przy wykorzystaniu zasobu https://api.allegro.pl/sale/product-offers do wystawiania oferty mam możliwość dodania swojej nazwy, opisu, zdjęć?

Tak, masz taką możliwość.
> 
> Czy jak już wystawiam podając identyfikator produktu to nie mam wpływu na to co jest w opisie itd.
> 
> "productSet": [{ "product": { "id": "5902719471797", "idType": "GTIN" }}],

Nie, jeśli wskazujesz w żądaniu ID produktu (lub GTIN albo MPN, czyli numer katalogowy części), liczbę sztuk oraz cenę przedmiotu, wszystkie pozostałe dane uzupełnimy automatycznie pobierając dane produktu.
> 
> Czy muszę tworzyć nowy produkt w katalogu? Co się stanie jeżeli będę chciał stworzyć produkt z eanem który już jest w katalogu allegro?

Jeżeli nasz system uzna, że próbujesz utworzyć duplikat istniejącego produktu - zwrócimy błąd ze stosownym komunikatem oraz identyfikator istniejącego już produktu w nagłówku odpowiedzi ("location"). Zwróć proszę jednak na nasz [ostatni news](https://developer.allegro.pl/news/wprowadzimy-limit-produktow-ktore-sprzedajacy-moga-dodac-do-katalogu-w-ciagu-miesiaca-oraz-uruchomimy-dodatkowa-walidacje-w-procesie-wystawiania-ofert-z-produktem-nnVXz3OodF8) - czyli nie będziemy próbować tworzyć nowego produktu, nawet jeśli dostarczysz nam wymagane dane w polu **product.id**, np. [numer GTIN](https://allegro.pl/dla-sprzedajacych/kod-producenta-i-numer-ean-w-allegro-wqggrjgj2hR), MPN lub identyfikator produktu,
> 
> Czy zadziała tak: "productSet": [{ "product": { "id": "5902719471797", "idType": "GTIN" "name":"Produkt testowy", "category":{ "id":"258020" }, ?
> 
> I jak mogę wskazać własny opis i zdjęcia?

Opisaliśmy to [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-przekazac-wlasne-wartosci-w-zadaniu).

**Comment by AleksyZajac** [comment]
Panie Łukaszu bardzo dziękuję za odpowiedzi na moje pytania. 

Życzę Wszystkiego dobrego na nadchodzące Święta Bożego Narodzenia i szczęśliwego Nowego Roku.

**Comment by Lukasz-Zurek** [comment]
@AleksyZajac Bardzo dziękuję. Również życzę Zdrowych i Radosnych Świąt Bożego Narodzenia i Do siego roku! 🎄 🎅 🎁
