### ISSUE TITLE
Promowanie ogłoszeń

### ISSUE THREAD

**Issue by Hornir91** [allegro/allegro-api#8177]
Dzień dobry.

W związku z przejściem na zasoby sale/product-offers mam pytanie.

Czy zmienione opcje promowania dotyczą również ogłoszeń czy tylko ofert z produktem? Czy od 1 stycznia 2024 roku promowanie ogłoszeń będzie odbywać się wyłącznie za pomocą zasobów opisanych w poniższym artykule?

https://developer.allegro.pl/news/przypomnienie-upewnij-sie-ze-korzystasz-z-odpowiednich-zasobow-do-promowania-ofert-3Av3eaL7qUn

Dodam, że obecnie promujemy ogłoszenia z wykorzystaniem zasobu `PUT /sale/offer-classifieds-packages/{offerId}`

Z góry dziękuję za odpowiedź.

**Comment by Lukasz-Zurek** [comment]
Zmiany dotyczą tylko ofert z produktem. Nic się natomiast nie zmienia jeśli chodzi o możliwość korzystania z `PUT /sale/offer-classifieds-packages/{offerId}`.
