### ISSUE TITLE
Jakim zasobem zostanie zastąpinony /sale/offers?publication.status=ACTIVE

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#8178]
Czy mogę prosić o informację jakim zasobem zostanie zastąpiony /sale/offers?publication.status=ACTIVE

Z informacji które posiadam to  /sale/offers zostaje zastąpiony /sale/product-offers
ale nie zlokalizowałem w /sale/product-offers możliwości wywołania ?publication.status=ACTIVE

W jaki sposób mogę pobrać aktualnie listę swoich aukcji ze statusem ACTIVE?

**Comment by jezewskiBNetrox** [comment]
Zastąpiony zostaje zasób GET /sale/offers/{offerId} ale zasób GET /sale/offers z listą ofert sprzedawcy pozostaje.

**Comment by AleksyZajac** [comment]
Super,
dzięki za informację.
