### ISSUE TITLE
Dodawanie zdjęć do oferty w zasobie /sale/product-offers

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#8179]
W dokumentacji do zasobu /sale/product-offers jest informacja o możliwości dodania zdjęć:
"images": [
            "https://...zewnetrzny-adres-pierwszego-obrazka.jpeg",
            "https://...zewnetrzny-adres-drugiego-obrazka.jpeg"
        ]

czy zdjęcia w tym zasobie podawane jako zewnętrzne linki np. do mojej strony?

W zasobie /sale/offers zdjęcia najpierw musiałem uploadować do Allegro, czy mam rozumieć że w nowym zasobie nie ma takiej potrzeby?

**Comment by Lukasz-Zurek** [comment]
Dokładnie, zdjęcia mogą pochodzić z zewnętrznych serwerów i nie musisz ich wcześniej wysyłać na serwer Allegro za pomocą [POST /sale/images](https://developer.allegro.pl/documentation/#operation/uploadOfferImageUsingPOST).

**Comment by AleksyZajac** [comment]
Super.
Dzięki za informację.
