### ISSUE TITLE
[SANDBOX] problem z wystawianiem ofert

### ISSUE THREAD

**Issue by coobitus** [allegro/allegro-api#818]
Czy jest jakiś problem z sandboxem? Bo od rana nie daje się wogóle wystawić żadnej oferty. Cały czas mam enigmatyczny błąd "Internal server error". Inne metody działają - np. ściąganie zamówień ... Możecie to pilnie naprawić?

**Comment by coobitus** [comment]
Dodam, że próbuję te oferty wystawić z obrazkami. Jeśli pominę obrazki, to dostaję już "prawidłowy/ludzki" błąd. A obrazków wrzucić nie mogę, bo za każdym razem mam błąd 500 :-(

**Comment by PawelTaberski** [comment]
Problem nie powinien już występować.
