### ISSUE TITLE
The user does not have Returns Terms named: default

### ISSUE THREAD

**Issue by ATomasRZE** [allegro/allegro-api#8180]
Próbuję ustawić cenę produktu wychodzącego w piaskownicy Allegro (/sale/product-offers) i zwraca ten błąd (błąd nie pojawia się na produkcji)

object(stdClass)#54 (1) {
  ["errors"]=>
  array(1) {
    [0]=>
    object(stdClass)#43 (5) {
      ["code"]=>
      string(29) "ReturnPolicyNotFoundException"
      ["message"]=>
      string(20) "Unprocessable Entity"
      ["details"]=>
      NULL
      ["path"]=>
      string(31) "afterSalesServices.returnPolicy"
      ["userMessage"]=>
      string(52) "The user does not have Returns Terms named: default."
    }
  }
}

**Comment by jezewskiBNetrox** [comment]
Jeżeli nie podasz w zapytaniu reguł zwrotu do oferty, automatycznie dobiera taką o nazwie "default". Jeżeli takiej nie ma, wyrzuci takowy błąd. Sprawdź czy masz regułę (politykę) zwrotu nazwaną "default" albo upewnij się, że podajesz ID/nazwę w zapytaniu dla returnPolicy.

**Comment by Lukasz-Zurek** [comment]
@ATomasRZE Dokładnie, potwierdzam tutaj to co napisał @jezewskiBNetrox - dziękuję. Wspominamy o tym w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem), a konkretnie w tabelce.

**Comment by ATomasRZE** [comment]
Gdzie mogę się upewnić, że istnieje opcja domyślna?

**Comment by MaciejFrackowiak** [comment]
Dostępne warunki zwrotów sprawdzisz korzystając z [GET /after-sales-service-conditions/return-policies](https://developer.allegro.pl/documentation/#operation/getPublicSellerListingUsingGET_1) bądź na [stronie WWW](https://allegro.pl/moje-allegro/sprzedaz/warunki-zwrotow).

**Comment by ATomasRZE** [comment]
![obrazek](https://github.com/allegro/allegro-api/assets/32672184/bb3d55c3-f749-403b-851a-d5b9874c3753)
Tak to wygląda, co dalej?

**Comment by MaciejFrackowiak** [comment]
@ATomasRZE Jedna z dostępnych polityk zwrotów powinna mieć nazwę "default" - zatem najprościej zmienić nazwę jednej z wyszczególnionych na zrzucie ekranu.

**Comment by ATomasRZE** [comment]
Dziękuję, teraz działa. Ale pytanie brzmi: jak włączyć walutę CZK? póki co tylko złotówka mi to rozpozna

**Comment by MaciejFrackowiak** [comment]
Zapoznaj się proszę z [naszym poradnikiem](https://developer.allegro.pl/tutorials/wystawianie-i-zarzadzanie-oferta-w-serwisach-zagranicznych-wwzjP4M8gTZ) dot. serwisów zagranicznych. Opisujemy w nim warunki jakie oferta musi spełniać by być widoczna w serwisie zagranicznym, jak określić cenę w walucie obcej i wiele innych cennych wskazówek.
