### ISSUE TITLE
Problem z autoryzacją.

### ISSUE THREAD

**Issue by ItTookaQuarry** [allegro/allegro-api#8182]
Występuje problem z logowaniem lub autoryzacją w środowisku testowym. Po wejściu na adres 'https://allegro.pl.allegrosandbox.pl/auth/oauth/token' dostaję komunikat:

'Zostałeś zablokowany. Dlaczego zostałeś zablokowany? Coś w zachowaniu twojej przeglądarki zwróciło naszą uwagę. Powody mogą być różne:
przeglądasz strony i klikasz dużo szybciej niż przeciętny człowiek,
coś uniemożliwia działanie Javascript na twoim komputerze,
w tej samej sieci operuje robot.
Jeśli coś nie działa prawidłowo, wyślij nam wiadomość. ID: fce62210-753e-2df3-f61e-a580819ee578.

Myślę, że blokada jest związana z wygenerowaniem zbyt dużej liczby tokenów w zbyt krótkim czasie. Czy jest możliwość zdjęcia blokady? Nazwa użytkownika na środowisku testowym - PrzemoDeadlift12. Chciałbym się jeszcze upewnić, czym spowodowana była blokada, żeby już się to nie powtórzyło.

**Comment by MaciejFrackowiak** [comment]
Weryfikuję Twój przypadek, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Problemem jest adres przekierowania, który używasz - proszę dostosuj go do [ograniczeń](https://developer.allegro.pl/news/ograniczenia-w-adresach-przekierowan-redirect_uri-g05YwwE1OC2), o których informowaliśmy.

**Comment by ItTookaQuarry** [comment]
Używam adresu http://localhost:3000. Chyba muszę coś źle rozumieć bo wydawało mi się że jest on dozwolony, ale dalej nie mogę wygenerować tokenu.

**Comment by MaciejFrackowiak** [comment]
Sam adres przekierowania oparty o localhost jest dopuszczalny. Sprawdź proszę pozostałe ustawienia aplikacji, z której wykonujesz request, aby nie przekazywała żadnych dodatkowych nagłówków.

**Comment by ItTookaQuarry** [comment]
Używam next.js 14. Moim celem jest stworzenie listy zamówień i zautomatyzowanie procesu tworzenia etykiet do zamówień. Na początku tworzenia strony wszystko działało dobrze, ale przez mój błąd wygenerowałem bardzo dużo tokenów w krótkim czasie i przestało. Teraz zmieniłem trochę sposób w jaki działa aplikacja z tego
![image](https://github.com/allegro/allegro-api/assets/121888343/65ea3eff-d01b-448c-95e7-f170b6276631)
na ten 
![image](https://github.com/allegro/allegro-api/assets/121888343/a3e44f1e-1f26-49fe-ad98-56a646c77072)
Działa trochę lepiej. Czasem aplikacja działa normalnie 
![image](https://github.com/allegro/allegro-api/assets/121888343/740bbea8-c483-4e6a-9487-f34d4b7eb9a0)
Ale czasem dostanę informację o tym że zostałem zbanowany.
![image](https://github.com/allegro/allegro-api/assets/121888343/9e6baddf-d3e4-4f17-8705-3dea78ef6602)

**Comment by MaciejFrackowiak** [comment]
Oznacza to de facto, że niektóre Twoje działania naruszają integralność działania Sandbox, zgodnie z przypisem na screenie informacyjnym. Jeżeli dla części requestów jest wszystko OK jak sam piszesz, to sam wiesz najlepiej co generuje pojawienie się komunikatu z blokadą.
