### ISSUE TITLE
Tworzenie draftu bez podpiętego produktu

### ISSUE THREAD

**Issue by PanNikczemny** [allegro/allegro-api#8183]
Czy za pomocą nowych zasobów jest możliwość utworzenia Draftu bez podpiętego produktu?

**Comment by AureliuszBrussy** [comment]
Jest to możliwe. Jeżeli kategoria jest sproduktyzowana, to już na podstawie draftu (jeżeli to konieczne) utworzymy nowy produkt, który zostanie podpięty do oferty.

**Comment by PanNikczemny** [comment]
Ale nie chcę żeby cokolwiek zostało automatycznie podpięte czy utworzone.

**Comment by AureliuszBrussy** [comment]
@PanNikczemny rozumiem, natomiast takiego działania (z całkowitym odłączeniem od produktyzacji) nie uda się uzyskać.
