### ISSUE TITLE
Pobieranie informacji o zestawie w ofercie

### ISSUE THREAD

**Issue by Akces-Projects** [allegro/allegro-api#8186]
Czy istnieje jakiś sposób aby stwierdzić, że oferta jest zestawem? 
Muszę pobrać wszystkie oferty naszego sklepu (ok. 15 000) i podzielić na dwie grupy ( produkt / zestaw ). 

[Metoda] https://api.{environment}/sale/offers -  nie widzę informacji o zestawie.
[Metoda] https://api.{environment}/sale/product-offers/{offerId} - 

tutaj jest : `"productSet": [
{
"quantity": {},
"product": {}
}
],` ale wymaga to wykonania 15 000 requestów. 

Czy jest lepszy sposób?

**Comment by MaciejFrackowiak** [comment]
Informacje o zestawie znajdziesz tylko w zasobie /sale/product-offers/{offerId}. I tak, musisz wykonać request dla każdej oferty / zestawu osobno.

**Comment by Akces-Projects** [comment]
Ok, dzięki za odpowiedź
