### ISSUE TITLE
Usuwanie cenników dostaw

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#8188]
W panelu allegro widzę że przy cennikach dostaw jest dostępna opcja usuwania cenników.
W dokumentacji API nie widzę takiej opcji.
Proszę o informację czy usuwanie cenników dostaw z poziomu API jest już możliwe ?

**Comment by AureliuszBrussy** [comment]
Usuwanie cenników dostawy nie jest możliwe przez API. Jeżeli coś się zmieni - oczywiście będziemy to komunikować.
