### ISSUE TITLE
Wyszukanie ID samochodu i dodawanie ogłoszenia samochodowego na allegro poprzez API

### ISSUE THREAD

**Issue by MGabala** [allegro/allegro-api#8189]
Witam, tworzę metodę która pozwoli mi dodawać ogłoszenia samochodowe na allegro poprzez api i z dokumentacji dowiedziałem się, że muszę podać id produktu, ale podczas odpytywania endpointu do wyszukiwania produktów: 

```
https://api.allegro.pl/sale/products?phrase=Ford%20Fusion%201.4%20Tdci&category.id=3
```

zwraca listę części a nie konkretne modele samochodu:

`{"products":[{"id":"11aefeba-5610-4fd6-b121-abdac3ae3321","name":"=SPRĘŻYNA PRZÓD FORD FUSION 2002- 1.4TDCI! CENA!=","category":{"id":"18965","similar":[{"id":"258702"},{"id":"255625"},{"id":"260727"},{"id":"19063"},{"id":"255628"},{"id":"255626"},{"id":"255627"}]},"parameters":[{"id":"127415","name":"Producent części","valuesLabels":["GT-Parts"],"valuesIds":["127415_834252"],"values":null,"unit":null,"options":{"identifiesProduct":true}},{"id":"215858","name":"Numer katalogowy części","valuesLabels":["GT31010"],"values":["GT31010"],"unit":null,"options":{"identifiesProduct":true}},{"id":"214434","name":"Jakość części (zgodnie z GVO)","valuesLabels":["P - zamiennik o jakości porównywalnej do oryginału"],"valuesIds":["214434_266986"],"values":null,"unit":null,"options":{"identifiesProduct":false}},{"id":"129591","name":"Typ samochodu","valuesLabels":["Samochody osobowe"],"valuesIds":["129591_1"],"values":null,"unit":null,"options":{"identifiesProduct":false}},{"id":"216493","name":"Rodzaj zawieszenia","valuesLabels":["standardowe"],"valuesIds":["216493_274581"],"values":null,"unit":null,"options":{"identifiesProduct":false}},{"id":"227349","name":"Strona zabudowy","valuesLabels":["przód"],"valuesIds":["227349_320405"],"values":null,"unit":null,"options":{"identifiesProduct":false}},{"id":"17448","name":"Waga produktu z opakowaniem jednostkowym","valuesLabels":["2,000 kg"],"values":["2.000"],"unit":"kg","options":{"identifiesProduct":false}},{"id":"215941","name":"Numery katalogowe zamienników","valuesLabels":["60-0456","998 132","801010","1500927","RA1819","SP2440"],"values":["60-0456","998 132","801010","1500927","RA1819","SP2440"],"unit":null,"options":{"identifiesProduct":false}},{"id":"227345","name":"Numer katalogowy oryginału","valuesLabels":["2N115310BE","1215301","1337555","1371958"],"values":["2N115310BE","1215301","1337555","1371958"],"unit":null,"options":{"identifiesProduct":false}},{"id":"213906","name":"Waga produktu","valuesLabels":["2,000 kg"],"values":["2.000"],"unit":"kg","options":{"identifiesProduct":false}}],"images":[{"url":"https://a.allegroimg.com/original/06dfbc/cc1137134027a8b9d1c7fe477c8f"},{"url":"https://a.allegroimg.com/original/06f2af/85a7f78b47c4b1ea2cf25672e956"}],"description":{"sections":[{"items":[{"type":"TEXT","content":"<h2>Sprężyna renomowanej firmy:</h2> <h1>GT-PARTS!!</h1> <h1>GT-Parts</h1> <h1>NAJWYŻSZA JAKOŚĆ W NISKIEJ CENIE!!!!</h1> <h1>.</h1> <h2>Sprężyny GT-Parts to części znane z wysokiej jakości wykonania, trwałości, a także niezawodności. Sprężyny przechodzą rygorystyczne testy które mają na celu weryfikację ich wytrzymałości oraz skuteczności, dzięki czemu sprężyny 
`

(Dla przejrzystości usunąłem większą część response)

Proszę o informację w jaki sposób mogę wyszukiwać id samochodów. 

Również proszę o informację czy Allegro API pozwala na dodawanie ogłoszeń samochodowych

**Comment by AureliuszBrussy** [comment]
Filtrując odpowiednio po id kategorii (np. uszczegóławiając w jakiej części drzewa chcesz wyszukać produkt, np. dla Ford: category.id=4036) uda Ci się wyszukać istniejące samochody w Katalogu Produktów. 

Dodam, że podanie id produktu podczas tworzenia oferty nie musi być konieczne. Jeżeli dany produkt/model nie istnieje w naszym katalogu - także możesz swobodnie wystawić ogłoszenie. Opisujemy do [w poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem).
