### ISSUE TITLE
[DEVELOPER PORTAL] subksrypcja

### ISSUE THREAD

**Issue by coobitus** [allegro/allegro-api#819]
Czy jest możliwość "zapisania się" do changeloga oraz do aktualności, które publikujecie na http://developer.allegro.pl ? Chodzi mi o to, żeby dostawać mailem powiadomienia o nowych pozycjach w obydwu tych sekcjach. Wydaje się to szczególnie istotne w momencie, kiedy REST API zmienia się tak intensywnie ... Jeśli nie ma takiej opcji, to czy możecie co s takiego wprowadzić?

**Comment by PawelTaberski** [comment]
Na obecnej stronie nie ma takiej możliwości, ale planujemy wdrożenie nowej strony, na pewno jeszcze nie w tym roku, ale mamy to w planach. W ramach nowej strony również myślimy o subskrypcji. Obecnie polecam śledzenie GitHub-a pod labelką NEW umieszczamy wszelkie zmiany w API Allegro.

**Comment by coobitus** [comment]
@imper86 to byłoby szaleństwo :-) lepiej to zrobić po label, tak jak pisał @PawelTaberski  - ale chyba na Githubie nie ma takiej opcji?

**Comment by collector1871** [comment]
GitHub notifications + filtr na mailu

**Comment by rtnet-pl** [comment]
Z czego połowa powiadomień dotyczy aktywacji kont na sandboxie ;)
