### ISSUE TITLE
Offer price in EUR

### ISSUE THREAD

**Issue by acerov** [allegro/allegro-api#8190]
Hi, I just managed to get first DRAFT offer through REST API, I see it now in my offers.

I posted price in EUR but price is shown in zl without conversion (same amount that should have been in EUR)

my JSON was:
"price": {
            "amount": "199.00",
            "currency": "EUR"
        },
What am I doing wrong?

Second question: Is there an easy way to convert multiple offers from DRAFT to ACTIVE through portal?

**Comment by AureliuszBrussy** [comment]
1. It is not yet possible to specify the amount in euros - currently, none of our marketplaces supports this currency. 

2. You can use batch offer publication endpoint to activate multiple offers at once: [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation#operation/createChangePriceCommandUsingPUT).

**Comment by acerov** [comment]
In API documentation there is example JSON with "EUR" as currency, so I believe it is suported, can you check please?

I sent new offer witl currency "PLN" but now there is no price visible in "my assortment", if I edit offer the price is there.
If i send price in EUR it is visible in "my assortment" as "199 EUR" but on edit it shows "199 zlt"

Please help

**Comment by PrzemyslawLukanowski** [comment]
> In API documentation there is example JSON with "EUR" as currency, so I believe it is supported, can you check please?

Which places do you mean exactly? EUR is not supported at the offer creation stage, you can check the supported currencies via [GET /marketplaces](https://developer.allegro.pl/documentation#operation/marketplacesGET) in the `currencies.base` field. The additional currencies in which buyers can see the offer price can be checked in the `currencies.additional` and yes, here we have EUR.

> I sent new offer with currency "PLN" but now there is no price visible in "my assortment",

I wasn't able to recreate this scenario, price is always visible in the 'my assortment'. Please check if your offer was created successfully with properly returned information about the price.

> If I send price in EUR it is visible in "my assortment" as "199 EUR" but on edit it shows "199 zlt"

Could you please send us a sample trace-id where you were able to define the price in EUR and also a screenshot from 'my assortment 'with a visible offer id?  I'm asking cause both things shouldn't be possible and I wasn't able to recreate them.

**Comment by acerov** [comment]
Now the price is not showing in assortiment regardles of EUR or PLN currency, what is going on?

**Comment by PrzemyslawLukanowski** [comment]
> Now the price is not showing in assortiment regardles of EUR or PLN currency.
> 
> This last one is set in PLN, please check trace id: c3451847a9fed60b

That is because you have defined the price for additional allegro-cz marketplace in PLN instead of CZK (in the `additionalMarketplaces.allegro-cz.sellingMode.price.currency` field). Please check the info in `validation.errors` field

> Another thing not about API is, if I go on "Edit" offer it changes my localization settings to Polish, so I have to change them each time back to English

Please report non-API related issues via the [contact form](https://allegro.pl/pomoc/kontakt), but I presume that you created this offer while using Polish language, and that way, we automatically change the language on the offer edit site according to the offer language.

**Comment by acerov** [comment]
Here are trace ids off POSTs in EUR:
5322a75f019ecc8c
2e9b5675d4b23286
c3af7ac07586b94d
fa97e0e3393ffab5

Screenshot is attached

**Comment by PrzemyslawLukanowski** [comment]
> Please check the info in validation.errors field

Please check this section, we are returning information about invalid currency, so it will not be possible to activate such an offer.

Screenshot is not visible.

**Comment by acerov** [comment]
I send now in PLN but price is still not visible

Trace-id: 5baaaca578ac58eb

**Comment by PrzemyslawLukanowski** [comment]
Please check the validation.errors section, you should receive the following message:

```
            {
                "code": "VALIDATION_FAILED",
                "message": "prices.price.amount.invalidPrecision",
                "details": null,
                "path": "prices[0].price.amount",
                "userMessage": "Number of decimal places is incorrect for the specified market."
            }
```

The price for allegro-cz additional marketplace should not have decimal places.

**Comment by acerov** [comment]
I am receiving validation error "EMPTY_SHIPPING_RATES"

Where can I get ID of my shipping rates?

**Comment by PrzemyslawLukanowski** [comment]
Defined shipping rates on the account can be retrieved via [GET /sale/shipping-rates](https://developer.allegro.pl/documentation#operation/getListOfShippingRatestUsingGET).

**Comment by acerov** [comment]
I tried shippingRates :) thank you

**Comment by acerov** [comment]
I am going through without errors now but am receiving warning:

"Did you know you can reach more customers by adding export options to your offers? Don't wait, add export options now, and increase your sales. Make sure the product has the required labeling in the official..."

What does it mean, what are "export options"?

**Comment by PrzemyslawLukanowski** [comment]
This is just additional information, you don't need to worry about it, it doesn't prevent listing an offer. Export options refer to delivery methods outside Poland, for example:

```
            "id": "14b73cc6-28d6-11eb-adc1-0242ac120002",
            "name": "Allegro DPD Courier Czechia",
```

**Comment by acerov** [comment]
Can I put offer language "en-US" and have description in Polish "pl_PL"?
Reason for that is if I put "pl_PL" and go to edit offer through portal, it shows offer in Polish and changes my localization to "pl_PL"

Or any other way around?

**Comment by acerov** [comment]
I tried sending "en-US" but now Description is handled like it is in "English language, but acctually it is in Polish.

Can I send in one POST description in multiple languages?

And again, how to remain in English GUI when editing offer set in pl-PL?

**Comment by PrzemyslawLukanowski** [comment]
You should set the language as the real language in which you sent the description and title. It cannot be multiple languages. Language in GUI on editing offer will always be changed to the language that you set in the "language" field, but if you create an offer via API you should also edit offer via this channel, using [PATCH /sale/product-offers](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#editing-single-offer). Cross-channel operations are not recommended and may cause issues as the one you mentioned.
