### ISSUE TITLE
Wyłaczenie endpoint sale/offers

### ISSUE THREAD

**Issue by bseltrox1996** [allegro/allegro-api#8191]
Witam, korzystam z [GET] sale/offers do pobierania wszystkich swoich ofert.  Czy ten ednpoint tez zostanie wyłączony? Jeżeli tak to proszę mi powiedzieć, który endpoitn pozwoli mi na pobranie swoich ofert.

**Comment by AureliuszBrussy** [comment]
Endpoint to pobierania samej listy ofert ([GET /sale/offers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET)) nie zostanie przez nas wyłączony. 

Kieruj się tabelką:
| **Endpoint, który usuniemy** | **Odpowiednik endpointu** | 
| :--------: | :--------: | 
| [POST /sale/offers](https://developer.allegro.pl/documentation#operation/createOfferUsingPOST) | [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers) | 
| [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation#operation/updateOfferUsingPUT) | [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/editProductOffers) | 
| [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation#operation/getOfferUsingGET) | [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/getProductOffer) |
