### ISSUE TITLE
Wzywanie kurierów innych niż Allegro One przez API

### ISSUE THREAD

**Issue by polakmaciej** [allegro/allegro-api#8192]
Dzień dobry

Przez Waszą stronę można wezwać np. DHLa czy DPD do zamówienia z allegro. Jak to zrobić przez API? Nie potrafię znaleźć korzystania z metod wysyłki innych niż Allegro One.

**Comment by MaciejFrackowiak** [comment]
Proszę spójrz do [naszego poradnika](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-zamowic-odbior-paczek-przez-kuriera), gdzie opisujemy proces.

**Comment by polakmaciej** [comment]
czyli da się przez sposób dostawy w allegro one zamówić np. DHLa i nie trzeba nic robić u Was na stronie? Wystarczy, że w sposobie dostawy zostanie wybrany odpowiedni dla DHLa, który wybrał klient i wtedy DHL będzie wiedział, żeby przyjechać?

**Comment by MaciejFrackowiak** [comment]
Tak, oczywiście - zgodnie z poradnikiem możesz sprawdzić proponowane terminy odbioru przesyłek praktycznie wszystkich przewoźników.

**Comment by polakmaciej** [comment]
@MaciejFrackowiak nie chodzi o sprawdzanie tylko o wezwanie kuriera. Rozumiem, że znając dostępność kurierów możemy w ciemno w zasadzie wysyłać zapytania i kurier i tak przyjedzie.

**Comment by MaciejFrackowiak** [comment]
Aby mieć pewność należy najpierw sprawdzić proponowane terminy, a następnie złożyć zlecenie odbioru przesyłek.

**Comment by polakmaciej** [comment]
czyli przy wysyłaniu zapytania jest konieczne podanie daty odbioru?

**Comment by MaciejFrackowiak** [comment]
Zgodnie z poradnikiem:

> W żądaniu przekaż:
> - identyfikator paczki w “shipmentId”,
> - ID proponowanego czasu odbioru paczki w "pickupDateProposalId", uzyskanego za pomocą POST /shipment-management/pickup-proposals.

**Comment by polakmaciej** [comment]
znalazłem gdzieś informację, że aby nadać przez API, należy być właścicielem zamówienia, ale nie potrafię nigdzie u Was znaleźć informacji na ten temat.

**Comment by polakmaciej** [comment]
co więcej, przy każdym generowaniu etykiety (do zamówienia, które już istnieje) dostaję za każdym razem nowy, inny guid zamówienia. Tutaj chyba jest coś nie tak.

**Comment by MaciejFrackowiak** [comment]
Tak, nadać przesyłkę można tylko, gdy uzyskasz autoryzację od właściciela danego konta. Otrzymujsz za każdym razem nowe commandId, które jest identyfikatorem przesyłki, a nie zamówienia.

**Comment by polakmaciej** [comment]
Jak uzyskać autoryzację?  Mamy podpięte konto na allegro, pobrany token aplikacji i uprawnienia do allegro:api:shipments:write w apps.developer.allegro.pl (zarówno nadawanie przesyłek jak i pobieranie zamówień w jednym) a dalej jest ten błąd.


Pozdrawiam/Best regards

Maciej Polak

[cid:848f2596-db14-421f-ad26-7c08d1a69b90]<http://www.tecweld.pl/kontakt>

(W celu kontaktu kliknij w logo/Click logo for contact details)



________________________________
Od: MaciejFrackowiak ***@***.***>
Wysłane: czwartek, 28 grudnia 2023 14:42
Do: allegro/allegro-api ***@***.***>
DW: Maciej Polak ***@***.***>; Author ***@***.***>
Temat: Re: [allegro/allegro-api] Wzywanie kurierów innych niż Allegro One przez API (Issue #8192)


Tak, nadać przesyłkę można tylko, gdy uzyskasz autoryzację od właściciela danego konta. Otrzymujsz za każdym razem nowe commandId, które jest identyfikatorem przesyłki, a nie zamówienia.

**Comment by MaciejFrackowiak** [comment]
Musisz korzystać z autoryzacji typu [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow by korzystać z zasobów do nadawania przesyłek.

**Comment by polakmaciej** [comment]
Tak jak pisałem, mam ustawione device i pobieranie zamówień na nim działa. Mam także ustawione uprawnienie allegro:api:shipments:write w nim ale dalej jest ten błąd.

**Comment by MaciejFrackowiak** [comment]
Bez konkretnego trace-id wywołania niestety niewiele mogę więcej napisać, dlatego proszę podaj trace-id Twojego requestu.

**Comment by polakmaciej** [comment]
numer zamówienia 6ffad410-a575-11ee-80c8-01398f6ec394
sposób dostawy 0b9bed2c-0bc1-4e1f-9694-29bb39ebb483
client id typu device z którego nadaję przesyłkę i pobieram zamóweinia 5694f3fc08c1404e852da28bcf594e0f
nadany guid przesyłki, która wywołała błąd 12f04700-65f1-45ff-8c8a-3318925fd8fa

**Comment by MaciejFrackowiak** [comment]
Zamówienie należy do konta "sherman-xxxxxxx", natomiast request wysyłasz będąc zautoryzowanym na koncie "tecweld-xxxxxx" (czyli to konto, na które jest zarejestrowana aplikacja). Tym samym nasz komunikat błędu jest w pełni zasadny. Jednym słowem musisz przejść proces autoryzacji dla konta "sherman-xxxxxxx" by z niego wysyłać requesty.

**Comment by polakmaciej** [comment]
ok, przy próbie generowaniu przesyłki dla konta sherman-xxxx otrzymałem zwrotkę: "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej".
Guid 7b9a00e1-2497-46f7-8e2e-eab028191405

**Comment by MaciejFrackowiak** [comment]
Problemem są wymiary przesyłki, które podałeś:
```
"dimensions": {
                "height": {
                    "value": 0,
                    "unit": "CENTIMETER"
                },
                "width": {
                    "value": 0,
                    "unit": "CENTIMETER"
                },
                "depth": {
                    "value": 0,
                    "unit": "CENTIMETER"
                }
            }
```

Proszę podaj rzeczywiste wymiary przesyłki.

**Comment by polakmaciej** [comment]
Dzień dobry

Dziękuję za odpowiedzi, ale mam jeszcze jedną.
Jak wygląda generowanie protokołów nadania/listów przewozowych (nie mówię teraz o etykietach) dla przesyłek zamówionych przez API? Czy to jest wymagane, czy to jest w ogóle możliwe, jaką metodą?

**Comment by MaciejFrackowiak** [comment]
Nie wszyscy operatorzy pozwalają na [generowanie protokołów](https://developer.allegro.pl/documentation/#operation/getShipmentProtocol) - są to: Allegro One, FedEx, InPost, UPS oraz Poczta Polska. Dla tych przesyłek zwrócimy status 204 no content.
