### ISSUE TITLE
Tworzenie oferty, a istniejący produkt

### ISSUE THREAD

**Issue by gkopec** [allegro/allegro-api#8193]
Chcemy utworzyć ofertę przekazując do API wymagane parametry produktowe i ofertowe. W odpowiedzi jednak dostajemy błąd:
```
{"errors":[{"code":"PARAMETER_MISMATCH","message":"The provided parameter 'Marka'(128970) value (303(128970_510653)) does not match the existing parameter value (1z(128970_510649))","details":null,"path":"productSet[0].product.parameters","userMessage":"The specified product exists. The specified parameter `Marka` with the value `303(128970_510653)` does not match the product parameter `1z(128970_510649)`."}]}
```

Który sugeruje, że w katalogu istnieje już produkt. 

1. Czy jest możliwość automatycznego użycia istniejącego produktu bez zwracania błędu? 
2. Czy możemy przypuszczać, że to na podstawie numeru EAN/GTIN Allegro sprawdza istnienie produktu? 
3. Czy API umożliwia nadpisanie danych produktowych w katalogu Allegro? (https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-zglosic-blad-w-produkcie?)
4. Czy istnieje możliwość utworzenia szkicu oferty przez API?

**Comment by MaciejFrackowiak** [comment]
Odpowiadając na pytania:
1. Oczywiście - wystarczy przekazać id produktu z Katalogu Produktów, a wówczas pobierzemy wszystkie dane przypisane do niego. 
2. Jest to jeden z parametrów, który bierzemy pod uwagę podczas detekcji produktów.
3. Nie, nie pozwalamy na nadpisanie parametrów produktowych. Możesz jedynie zgłosić sugestię zmiany w istniejącym produkcie zgodnie z podlinkowanym artykułem.
4. Oczywiście - wystarczy w polu publication.status przekazać wartość "INACTIVE" ([opis](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#szkic-oferty) z poradnika).
