### ISSUE TITLE
api - get prices (Najpopularniejsza transakcja, Najniższa cena inne sklepy, Najniższa cena Allegro, Sprzedający)

### ISSUE THREAD

**Issue by DHSC1** [allegro/allegro-api#8195]
Hello,
I see that when manually listing, a smart box with price advice is displayed, which should remain even after turning off the "Przegląd cen" function.
![image](https://github.com/allegro/allegro-api/assets/144317759/bd8ac2ed-f7ff-4ef3-8c5c-93d77dc6663e)
My question is: **Is it possible to access this information** (Najpopularniejsza transakcja, Najniższa cena inne sklepy, Najniższa cena Allegro, Sprzedający) **in any way through your API?**
I have looked for any possibility and cannot seem to find it.

Thank you

**Comment by MaciejFrackowiak** [comment]
No, such functionality is not available in the API.

**Comment by DHSC1** [comment]
Hello,
Thank you very much for your reply. Are you planning to address the difference where sellers using the API are limited compared to those listing manually in the future, or is this a deliberate decision?

**Comment by MaciejFrackowiak** [comment]
We do not plan to add this option to the API.
