### ISSUE TITLE
Lista form wysyłki

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#8197]
W jaki sposób mogę pobrać listę wszystkich dostępnych form wysyłki? Za pomocą GET order/checkout-forms/{id} pobieramy szczegóły zamówienia i otrzymujemy np.

```
delivery": {
"address": {},
"method": {
"id": "1fa56f79-4b6a-4821-a6f2-ca9c16d5c925",
"name": "Allegro Paczkomaty InPost"
},
```

Potrzebuję pełną listę metod wysyłek dostępnych na Allegro. Próbowałem za pomocą GET /shipment-management/delivery-services, ale otrzymuje błąd 403

Zależy nam na powiązaniu konkretnej formy wysyłki z Allegro z wysyłką na sklepie, dlatego potrzebujemy pełnej listy

**Comment by MaciejFrackowiak** [comment]
Listę dostępnych metod dostawy pobierzesz korzystając z [GET /sale/delivery-methods](https://developer.allegro.pl/documentation/#operation/getListOfDeliveryMethodsUsingGET). [GET /shipment-management/delivery-service](https://developer.allegro.pl/documentation/#operation/getDeliveryServices) zwraca listę metod dostawy dostępną w ramach Wysyłam z Allegro. Jeżeli otrzymujesz błąd 403 to oznacza, że musisz ponownie się zautoryzować by token posiadał scope'y do obsługi WzA i zasobów /shipment-management.

**Comment by mateuszcom** [comment]
Dziękuję za pomoc - faktycznie problem był z uprawnieniami do WzA. [GET /sale/delivery-methods](https://developer.allegro.pl/documentation/#operation/getListOfDeliveryMethodsUsingGET) spełnia moje oczekiwania
