### ISSUE TITLE
Aktywacja sprzedaży na Allegro Sandbox

### ISSUE THREAD

**Issue by KwiatekMikiBots** [allegro/allegro-api#8198]
Poproszę o aktywacji sprzedaży na koncie `scam`.

**Comment by KwiatekMikiBots** [comment]
a i przy okazji byście zrobili że się da bez proszenia tutaj lol

**Comment by MaciejFrackowiak** [comment]
Niestety, ale nie dokonałeś przelewu weryfikacyjnego i nie przesłałeś dokumentów firmowych. Spróbuj dokończyć proces w zakładce [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by KwiatekMikiBots** [comment]
> Niestety, ale nie dokonałeś przelewu weryfikacyjnego

CZYLI JA SERIO MUSZĘ ZAPŁACIĆ???

a i wczoraj nie mogłem wysłać zdjęć nie wiem czemu ale już dzisiaj mogę więc poproszę znowu o aktywację lol

**Comment by MaciejFrackowiak** [comment]
Na Sandbox działa symulator płatności, czyli żadnego realnego przelewu nie trzeba wykonywać. Konto jest już aktywne.

**Comment by KwiatekMikiBots** [comment]
Dziękuję!
