### ISSUE TITLE
Wyłączenie protokołu TLS 1.0 w Sandboxie

### ISSUE THREAD

**Issue by crowpy** [allegro/allegro-api#82]
Pojawiło się info o wyłączeniu TLS 1.0 po 31 maja.
Zakładam, że sandbox będzie miał niedługo funkcjonalność komunikatu o nieaktualnym protokole TLS.
W jakiś sposób przecież musimy sprawdzić, że jesteśmy gotowi na to wyłączenie.

Pytanie kiedy wyłączycie TLS 1.0 w sandboxie.

Pozdrowienia Tomek Wrona

**Comment by KrzysztofLukanowski** [comment]
Z początkiem kwietnia przestaniemy wspierać TLS 1.0 na sandboxie.

**Comment by rtnet-pl** [comment]
Wynegocjowaną wersję TLS można podejrzeć np. Wiresharkiem.
W naszym wypadku wystarczyło wymusić używanie protokołu TLS 1.2,

https://i.imgur.com/IZdnJmS.png
