### ISSUE TITLE
Rodzaj autoryzacji api

### ISSUE THREAD

**Issue by SzymonZasada** [allegro/allegro-api#8200]
Jak są uwierzytelnianie aplikacje typu baselinker/api? Ponieważ mam w nich połączone konto ale nie widze u siebie na koncie aplikacji REST API, a w.w apliakcje jakos działają w moim imieniu?

**Comment by MaciejFrackowiak** [comment]
Sprawdź proszę zakładkę [Powiązane aplikacje](https://allegro.pl/moje-allegro/moje-konto/powiazane-aplikacje) - tu znajdziesz wszystkie aplikacje, które działają w Twoim imieniu. Każda z aplikacji wykorzystuje jeden z dostępnych typów autoryzacji, o których możesz przeczytać w [naszym poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR).
