### ISSUE TITLE
Błąd przy tworzeniu aukcji wielowariantowej

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#8201]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
https://prnt.sc/dDhxCU2iBDzp 
Dlaczego mam taki błąd? Niezależnie od tego czy tworze ofertę wariantową przez api czy panel allegro. Dodatkowo dodam że aukcje są wystawiane dokładnie z tym samym zdjeciem

tutaj aukcja dla której został wywołany błąd
https://allegro.pl.allegrosandbox.pl/oferta/aniol-i-diabel-limited-edition-7739660691

**Comment by MaciejFrackowiak** [comment]
Twój przypadek konsultuję z zespołem, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Problem generują oferty: 7739660028, 7739660667, ponieważ mają tę samą wartość parametru "Długość bez klamry". Dodatkowo, w kategorii, w której oferty są wystawione działa mechanizm automatycznego łączenia ofert w warianty, dlatego gdy zmienisz wartość jednej z ofert to połączą się one automatycznie w wariant. Tym samym nie musisz wysyłać manualnych requestów z ich łączeniem.

**Comment by DamianKAtomStore** [comment]
Rozumiem, w takim razie czemu dostaję error związany ze zdjęciami? W takim przypadku może to prowadzić do szukania błędu tam gdzie go niema i wprowadzanie w błąd waszych klientów. Prosiłbym w moim imieniu o doprecyzowanie informacji zwrotnej o  niepowodzeniu przy tworzeniu wariantów aukcji.

**Comment by MaciejFrackowiak** [comment]
Dziękuję, Twoją uwagę przekażę do zespołu odpowiedzialnego za usługę.
