### ISSUE TITLE
Eventy dla zamówienia

### ISSUE THREAD

**Issue by Akces-Projects** [allegro/allegro-api#8202]
Czy można jakoś pobrać id eventów powiązanych z konkretnym zamówieniem, lub dostać eventy wstecz, ale nie od samego początku?
Muszę dostać event id który wystąpił kilka dni temu, aby od niego zacząć dalsze pobieranie eventów

**Comment by MaciejFrackowiak** [comment]
[GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET) pozwala na pobranie eventów wg typu zdarzenia lub czasu wystąpienia. Korzystając z parametru "from" możesz określić moment początkowy, dla którego otrzymasz dane. Samego filtrowania wg id zamówienia nie ma.
