### ISSUE TITLE
Problem z dostępem do API przy użyciu tokena - kod 403 Forbidden

### ISSUE THREAD

**Issue by api-test-yexiu** [allegro/allegro-api#8203]
Witam,

Napotkałem problem podczas próby wykonania zapytania GET do API Allegro. Pomimo używania aktualnego tokena, otrzymuję błąd z kodem 403 Forbidden. Oto szczegóły mojego żądania:
curl -X GET \
'https://api.allegro.pl/sale/products?phrase=992186999998&mode=GTIN' \
-H 'Authorization: Bearer XYZ' \
-H 'Accept: application/vnd.allegro.public.v1+json'
Odpowiedź serwera:

Status: 403 Forbidden
Size: 126 Bytes
Time: 13.21 s
Response:
{
  "errors": [
    {
      "code": "AccessDeniedException",
      "message": "Access denied.",
      "details": null,
      "path": null,
      "userMessage": "No access."
    }
  ]
}
Token, którego używam, jest aktualny, ale mimo to ciągle otrzymuję błąd. Czy ktoś może mi pomóc zidentyfikować problem lub wskazać, co może być jego przyczyną?

Z góry dziękuję za wszelką pomoc.

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swojego wywołania.
