### ISSUE TITLE
Problem z uzyskaniem Tokenu.

### ISSUE THREAD

**Issue by lukaszkowy87** [allegro/allegro-api#8204]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam, podczas próby uzyskania tokenu zapomocą Pythona po uzyskaniu odpowiedzi z terminalu i kliknięciu w link otrzymuje następujący komunikat w przeglądarce:

"Niestety… nie można przejść do tej stronyWitryna localhost odrzuciła żądanie połączenia.
Spróbuj wykonać:

Wyszukaj w sieci Web [localhost](https://www.bing.com/search?form=ANLKDR&q=localhost)
Sprawdzanie połączenia
[Sprawdzanie serwera proxy i zapory](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED"

Próbowałem już wyłączyć zaporę i antywirusa, ale nie pomogło.

Macie może jakieś sugestię?

Będę wdzięczny za jakąkolwiek wskazówkę.

Dzięki.

**Comment by MaciejFrackowiak** [comment]
Z samego opisu trudno jednoznacznie o konkretną poradę, ponieważ źródeł problemu może być co najmniej kilka. Na Twoim miejscu sugerowałbym sprawdzenie samych ustawień przeglądarki, czy też adresów DNS. Być może któryś z użytkowników naszego forum miał pododbny problem i będzie mógł Cię wesprzeć.
