### ISSUE TITLE
Problem z aktywacją konta na allegro sandbox 

### ISSUE THREAD

**Issue by simswaper** [allegro/allegro-api#8205]
Witam mam problem z aktywacja konta poprzez przelanie 1,01zł
Przekierowywuje na strone ktora nie dziala

Mail: 6un4i6ht3r@gmail.com

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Aktywowałem wskazane konto.

**Comment by simswaper** [comment]
Dziękuje
