### ISSUE TITLE
Failed to obtain token

### ISSUE THREAD

**Issue by Tiinayoo** [allegro/allegro-api#8206]
Hello!  when I try to get a token, I sometimes succeed, and sometimes I get a response such as "Operation timed out after 300001 ms, received 0 of -1 bytes" or "peer weight TCP connection".
When I tried to get the token again, I got the following response ["error":"invalid_grant", "error_description":" Invalid refresh token :......"]

The problems mentioned above come up every few days, resulting in me having to repeat authorization applications, which is cumbersome and time-consuming. How do I solve this problem to successfully get my token? I hope to hear from you soon. Thank you very much!

**Comment by PrzemyslawLukanowski** [comment]
Hello, please send us sample logs for both cases via our [contact form](https://allegro.pl/pomoc/kontakt). Include information about IP and mention that the data you send is connected with the #8206 thread on GitHub.

**Comment by PrzemyslawLukanowski** [comment]
We received your data, but we cannot find right now any information in our logs associated with your IP. What date are these logs from? Could you please send here logs from maximally 5 days ago (you can remove info about IP, cause we already know it)?

**Comment by Tiinayoo** [comment]
The logs below is from 5days ago.  The Client ID is the same as what I gave you before. Looking forward to your reply soon, thank you~

2023-12-27:
{"url":"https:\/\/allegro.pl\/auth\/oauth\/token","content_type":null,"http_code":0,"header_size":0,"request_size":0,"filetime":-1,"ssl_verify_result":0,"redirect_count":0,"total_time":300.000828,"namelookup_time":1.512836,"connect_time":1.796167,"pretransfer_time":0,"size_upload":0,"size_download":0,"speed_download":0,"speed_upload":0,"download_content_length":-1,"upload_content_length":-1,"starttransfer_time":0,"redirect_time":0,"redirect_url":"","primary_ip":"5.134.213.80","certinfo":[],"primary_port":443,"local_ip":"192.168.1.206","local_port":59632,"errno":28,"error":"Operation timed out after 300000 milliseconds with 0 out of 0 bytes received"}

2023-12-30:
{"url":"https:\/\/allegro.pl\/auth\/oauth\/token","content_type":null,"http_code":100,"header_size":25,"request_size":314,"filetime":-1,"ssl_verify_result":0,"redirect_count":0,"total_time":300.001035,"namelookup_time":0.004122,"connect_time":11.400378,"pretransfer_time":14.091587,"size_upload":1547,"size_download":0,"speed_download":0,"speed_upload":5,"download_content_length":-1,"upload_content_length":1547,"starttransfer_time":15.792241,"redirect_time":0,"redirect_url":"","primary_ip":"5.134.213.80","certinfo":[],"primary_port":443,"local_ip":"192.168.1.206","local_port":41128,"errno":28,"error":"Operation timed out after 300001 milliseconds with 0 out of -1 bytes received"}

2023-12-31:
{"url":"https:\/\/allegro.pl\/auth\/oauth\/token","content_type":null,"http_code":0,"header_size":0,"request_size":0,"filetime":-1,"ssl_verify_result":0,"redirect_count":0,"total_time":112.090215,"namelookup_time":1.515649,"connect_time":3.808701,"pretransfer_time":0,"size_upload":0,"size_download":0,"speed_download":0,"speed_upload":0,"download_content_length":-1,"upload_content_length":-1,"starttransfer_time":0,"redirect_time":0,"redirect_url":"","primary_ip":"5.134.213.80","certinfo":[],"primary_port":443,"local_ip":"192.168.1.206","local_port":45238,"errno":35,"error":"TCP connection reset by peer"}

**Comment by PrzemyslawLukanowski** [comment]
We checked our logs but we didn't detect any traffic anomaly on our side. It seems that the problem may be connected to the network issues on your side. [Some time ago we extended the refresh token validity to 60 seconds after the first use](https://developer.allegro.pl/news/authorization-we-have-extended-refresh-tokens-validity-to-60-seconds-after-first-use-D7KP4E7z4hA) to solve problems like yours, so if you don't receive the token within this time, you can repeat the operation. The refresh token should still be valid, so you won't receive the `401 invalid refresh token` error message, but a new pair of tokens.
