### ISSUE TITLE
"Propose changes in product" nie widzi numeru GTIN, mimo że został on przekazany

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#8208]
Wysyłam request jak niżej, przekazując nr GTIN w parametrze 225693. W odpowiedzi dostaję:

{"id":"c270268a-c166-45c4-8831-37f2aab5d102","name":null,"images":[],"parameters":[{"id":"225693","values":[{**"current":"0789176527527","proposal":null,"reason"**:"Oczekuje na weryfikację.","resolutionType":"UNRESOLVED"}]}],"category":null,"note":null,"notifyViaEmailAfterVerification":true,"language":"pl-PL"}

Na stronie, w zakładce Allegro/Moje Allegro/Sprzedaż/Obsługa ofert/Zgłoszenia zmian również pojawia się informacja, że próbuję wyzerować nr GTIN. Dlaczego API nie widzi tego parametru?

POST https://api.allegro.pl/sale/products/46bbe831-8257-4237-90b2-4bf054358c39/change-proposals

(
    [name] => Grot myśliwski Magnus Killer Bee
    [category] => Array
        (
            [id] => 253935
        )

    [images] => Array
        (
            [0] => Array
                (
                    [url] => https://a.allegroimg.com/original/11ac13/df9e92e84e459306ce9fdbc2205a
                )

        )

    [parameters] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 224017
                    [values] => Array
                        (
                            [0] => Strzaly.pl_523_10679
                        )

                )

            [1] => stdClass Object
                (
                    [id] => 237206
                    [values] => Array
                        (
                            [0] => Strzaly.pl_523_10679
                        )

                )

            [2] => stdClass Object
                (
                    [id] => 225693
                    [values] => Array
                        (
                            [0] => 789176527527
                        )

                )

            [3] => stdClass Object
                (
                    [id] => 208842
                    [values] => Array
                        (
                            [0] => 1
                        )

                )

            [4] => stdClass Object
                (
                    [id] => 237430
                    [valuesIds] => Array
                        (
                            [0] => 237430_409426
                        )

                )

            [5] => stdClass Object
                (
                    [id] => 128975
                    [valuesIds] => Array
                        (
                            [0] => 128975_1161203
                        )

                )

            [6] => stdClass Object
                (
                    [id] => 232265
                    [values] => Array
                        (
                            [0] => 1.00
                        )

                )

        )

    [notifyViaEmailAfterVerification] => 1
    [language] => pl-PL
)

**Comment by PrzemyslawLukanowski** [comment]
Ten produkt zawiera dwa numery GTIN, z czego jeden z nich to ten, który wysyłasz w requeście. Weryfikuję jeszcze z odpowiednim zespołem kwestią związaną z tym, dlaczego zwracamy informację o próbie usunięcia GTIN. Wrócę z informacją.

**Comment by PrzemyslawLukanowski** [comment]
Będziemy pracować nad zmianą tego zachowania, tak aby taka sytuacja nie była interpretowana jako próba usunięcia numeru GTIN. Na tę chwilę nie jestem jednak w stanie wskazać konkretnego terminu.
