### ISSUE TITLE
Aktywacja konta sandbox.

### ISSUE THREAD

**Issue by salesconnectsandbox** [allegro/allegro-api#8209]
Cześć, proszę o aktywację konta sandbox zarejestrowanego na email tech@salesconnect.cz

Z góry dzięki !

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto, wybrałeś jednak konto zwykłe - w takim przypadku nie będziesz mógł wystawiać i zarządzać ofertami za pomocą API. Jeśli chcesz to robić, zmień obecne konto na firmowe lub załóż nowe (a te będziesz mógł wtedy zostawić jako swoje drugie konto, kupującego).

**Comment by salesconnectsandbox** [comment]
Ok, zmieniłem profil na firmowy ale dlaczego nie mogę zarejestrować firmy z Czech ? Nafakeowałem jakieś dummy data z polskiej firmy ale teraz chce to wysłać przelew, który ma potwierdzić dane firmy. Siłą rzeczy te nie będą się zgadzały. Co mam zrobić w takiej sytuacji ?

**Comment by PrzemyslawLukanowski** [comment]
To jest fikcyjny przelew wykonywany za pomocą symulatora płatności, w przypadku środowiska testowego nie powinno być problemu.
