### ISSUE TITLE
Czy można wyłączyć automatyczne dodawanie obrazków z katalogu produktów przy edycji oferty?

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#8210]
Dzień dobry,

Przekazuję pytanie od naszego Użytkownika:

"
__zauważyłem jeszcze taką sytuację, iż jeśli np. dokonujemy edycji (zmiany) choćby tylko samego tytułu oferty, a te oferty są połączone z katalogiem produktów allegro, wówczas po zapisie zmian w ofertach na allegro, tytuł prawidłowo się zmienia i wszystko jest OK, tylko w galerii oferty pojawiają się dodatkowe zdjęcia (prawdopodobnie z katalogu allegro). 
...

 Czy jest możliwość wprowadzić poprawkę, aby takiej sytuacji uniknąć lub też czy jest możliwość skorzystać z jakiejś dodatkowej opcji przed zapisem zmian, aby zablokować automatyczne dodawanie obrazków z katalogu produktów?_"_

**Comment by tomasz-grzesik** [comment]
Jakieś inne rozwiązanie niż to:
"Można to jednak obejść włączając przed zapisem zmian opcję "Rozłącz produkt od oferty", wówczas do galerii nie będą dodawać się niepotrzebne zdjęcia z katalogu produktów allegro. Po zapisie zmian allegro automatycznie łączy z produktem na podstawie numeru EAN. Przy kolejnych edycjach problem już nie występuje."

**Comment by PrzemyslawLukanowski** [comment]
Przy wystawianiu oferty połączonej z produktem, w sekcji `product.images `musisz w takim przypadku przekazać pustą tablicę. Przykład znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty). W takim przypadku nie uwzględnimy w ofercie zdjęć z katalogu, zatem przy każdej edycji za pomocą metody PATCH, jeśli nie przekazujesz nam `product.id`, to zignorujemy dane produktowe. Jeśli jednak wskażesz nam `product.id`, to będziemy to interpretować jako aktualizację oferty o dane z produktu, w tym zdjęcia - rozwiązaniem zatem będzie uwzględnienie w requeście pustej tablicy w `product.images` lub wysłanie wyłącznie tych pól, które użytkownik chce edytować.

**Comment by tomasz-grzesik** [comment]
Dziękuję za informację i link do poradnika.
