### ISSUE TITLE
HttpMessageNotReadableException - Tworzenie produktu (product-proposals)

### ISSUE THREAD

**Issue by Daczek** [allegro/allegro-api#8211]
Witam,
Mam problem z jednym produktem przy próbie przesłania propozycji nowego produktu (z innymi ten problem nie występuje a używam tej samej funkcji tak więc stawiam, że problem jest gdzieś w parametrach ale nie udało mi się dojść w czym dokładnie mimo dziesiątek prób). Kategoria ma productCreationEnabled = 1. Próbowałem przesyłać parametry które wymagają valuesIds zarówno z valuesLabels jak i bez.
Za każdym razem kiedy próbuję utworzyć produkt dostaję błąd:
stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => HttpMessageNotReadableException
                    [message] => An error has occurred
                    [details] => 
                    [path] => 
                    [userMessage] => Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji.
                )

        )

    [duplicate_product_id] => 
)

Dane jakie przesyłam: {"images":["https:\/\/a.allegroimg.com\/original\/113faa\/cdc19ee74e088d562eb2f9b7b53d"],"parameters":[{"id":"11323","valuesIds":["11323_2"],"valuesLabels":["U\u017cywany"]},{"valuesIds":["2868_1"],"id":"2868","valuesLabels":["polski"]},{"id":"223545","values":["SZACHOWNICA FLAMANDZKA ARCYDZIE\u0141A LITERATURY WSP\u00d3\u0141CZESNEJ"]},{"id":"223489","values":["Arturo Perez-Reverte, przek\u0142ad Filip \u0141obodzi\u0144ski"]},{"valuesIds":["249857_1769440"],"id":"249857","valuesLabels":["ksi\u0105\u017cka papierowa"]},{"valuesIds":["75_1"],"id":"75","valuesLabels":["mi\u0119kka"]},{"id":"74","values":["2002"]},{"valuesIds":["223541_478649"],"id":"223541","valuesLabels":["Deagostini"]},{"id":"223493","values":["400"]},{"valuesIds":["249493_1645864"],"id":"249493","valuesLabels":["Proza"]},{"id":"245669","values":["8373141740"]}],"category":{"id":"79153"},"name":"Szachownica Flamandzka Arcydzie\u0142a Literatury Wsp\u00f3\u0142czesnej","language":"pl-PL"}

**Comment by MaciejFrackowiak** [comment]
Problemem jest sekcja "images" - zgodnie z [dokumentacją](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct) zasobu powinna ona wyglądać tak:
```
"images": [

    {
        "url": "string"
    }

]
```
