### ISSUE TITLE
Problem z nieopłaconym kontem

### ISSUE THREAD

**Issue by Hornir91** [allegro/allegro-api#8212]
Dzień dobry.

Dzisiaj otrzymujemy informację o kontach, które nie zostały opłacone przez co niemożliwe jest wystawianie ogłoszeń. Chciałbym prosić o otrzymanie pełnej nazwy konta "300...uto", gdyż mam problem z jego zlokalizowaniem.

Trace-id: fc2bc8152b3fe1a

Z góry dziękuję za odpowiedź.

**Comment by MaciejFrackowiak** [comment]
W kwestii rozliczeń z Allegro proszę skontaktuj się bezpośrednio z [obsługą serwisu](https://allegro.pl/pomoc/kontakt).

**Comment by shivson1337** [comment]
Ewentualnie, jeżeli dobrze rozumiem Twój problem, możesz odpytać zasób https://api.allegro.pl/me - tam uzyskasz nazwę konta dla używanego tokenu.

**Comment by Hornir91** [comment]
Niestety podany sposób nie rozwiązuje problemu, gdyż rozchodzi się o inne konto z sieci powiązanych kont, do którego nie mam access ani refresh tokenu.

**Comment by MaciejFrackowiak** [comment]
Dlatego właśnie najlepszym rozwiązaniem jest kontakt z obsługą Allegro, która ma bezpośredni dostęp do rachunków firmowych.

**Comment by Hornir91** [comment]
Napisałem maila zaraz po pierwszej odpowiedzi, lecz dalej czekam na kontakt ze strony Allegro.
