### ISSUE TITLE
401 "error":"Unauthorized

### ISSUE THREAD

**Issue by bodikosa** [allegro/allegro-api#8213]
Hello. I have problem with auth on prod.
I Try to make request and  get error {"error":"Unauthorized","error_description":"Unauthorized"}.
On Sandbox this functional is working

function getAccessToken() {
    //$authorization = base64_encode(CLIENT_ID.':'.CLIENT_SECRET);
    //device
    $authorization = base64_encode('e601a5a980824c25819432ed8c8633a4:********);
    $headers = array("Authorization: Basic {$authorization}","Content-Type: application/x-www-form-urlencoded");
    $content = "grant_type=client_credentials";
    $url = "https://allegro.pl/auth/oauth/token";
    $ch = getCurl($headers, $url, $content);
    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($tokenResult === false || $resultCode !== 200) {
        var_dump($tokenResult);
        var_dump($resultCode);
        exit ("Something went wrong");
    }
    return json_decode($tokenResult)->access_token;
}

i have changed client secret for security reason

**Comment by PrzemyslawLukanowski** [comment]
Please check a sample code [from our tutorial](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#php). Also, you registered a device app, but it seems that you are trying to use client_credentials type of authorization, which won't give you access to most of the resources - only for those marked as bearer-token-for-application in [our documentation](https://developer.allegro.pl/documentation).

**Comment by bodikosa** [comment]
Can you help me how can i Verify app?

have this problem 
            "code": "VerificationRequired",
            "message": "Access is denied. Verification is required.",
            "details": null,
            "path": null,
            "userMessage": "No access to the specified resource. Access is possible only for verified applications."
            
  to recource /offers/listing

**Comment by PrzemyslawLukanowski** [comment]
Access to this specific resource is restricted and the verification takes place by another department. As we mentioned in [our tutorial](https://developer.allegro.pl/tutorials/how-to-search-and-browse-offers-XxWm2ykMYHl), please use the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) to verify your application.

**Comment by bodikosa** [comment]
I have used this form, but don`t receive response.  Also i tried to write support online but did`t take solving my request. Could you help me accelerate this process?

**Comment by PrzemyslawLukanowski** [comment]
Please be patient, the department responsible for verification should return with an answer in the coming days.
