### ISSUE TITLE
Tworzenie paczek

### ISSUE THREAD

**Issue by Axlii50** [allegro/allegro-api#8214]
Mam pytanie po względem jednego pola w zakresie "Create new shipment" a dokładniej jeżeli tworze paczke do zamówienia które zawiera płatność pobraniową lecz pole "cashOnDelivery" nie zostało by uzupełnione ze względu ze nie jest wymagane to co w takim wypadku by sie stało ?

**Comment by Axlii50** [comment]
Mam tez kolejne pytanie odnośnie tworzenia paczek tzn jak mamy ple w receiver.street to czy jeżeli podamy wartość z pobierania z zamówienia [https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET](url)  z pola delivery.address.street (ze względu ze nie ma streetNumber i obydwa pola są zawarte w street) to czy w takim wypadku mogę to zrobic w ten sposób by nie wymyślać sposobu jak rozdzielić 2 dwie wartosci (chyba ze jest jakiś format w którym jest zapisywane)

**Comment by PrzemyslawLukanowski** [comment]
1. W takim przypadku zwrócimy błąd, nie utworzymy przesyłki.
2. Walidacja w tym przypadku jest już zależna od przewoźnika. Możemy prawidłowo przeprocesować taki request, ale nie dajemy gwarancji, że API po stronie przewoźnika w niektórych przypadkach nie odpowie błędem.

**Comment by PrzemyslawLukanowski** [comment]
Jeśli zamówienie będzie związane z usługą dostawy bez pobrania, ale uzupełnisz pole, które za nie odpowiada, to w takim przypadku również zwrócimy błąd.

**Comment by Axlii50** [comment]
Dobrze czy w takim wypadku jest możliwość otrzymania listy Id sposób dostawy za pobraniem ?

oraz czy jest może jakiś prosty fajny sposób na rozdzielenie (pytanie 2)

**Comment by PrzemyslawLukanowski** [comment]
Listę usług dostawy w Wysyłam z Allegro pobierzesz za pomocą [GET /shipment-management/delivery-services](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-pobrac-liste-uslug-dostawy). Każda związana z pobraniem będzie na końcu posiadać dopisek "pobranie". Natomiast listę wszystkich metod dostawy, jakie występują na Allegro, otrzymasz za pomocą [GET /sale/delivery-methods](https://developer.allegro.pl/documentation#operation/getListOfDeliveryMethodsUsingGET). I tutaj analogicznie każda metoda pobraniowa również posiada taki dopisek.

**Comment by Axlii50** [comment]
a odnośnie pytania drugiego, czy jest jakiś prosty oraz pewny sposób na pozyskanie/rozdzielenie tych rzeczy ?

**Comment by Axlii50** [comment]
rozumiem
Dziękuje za pomoc :)
