### ISSUE TITLE
Status: 422 Unprocessable Entity

### ISSUE THREAD

**Issue by api-test-yexiu** [allegro/allegro-api#8215]
{
  "productSet": [
    {
      "product": {
        "name": "Rozrusznik elektromagnetyczny 12 V 33 331 Przełącznik przekaźnika",
        "category": {"id": "261071"},
        "parameters": [
    {
      "id": "127415",
      "valuesIds": [
        "127416_359665"
      ]
      },
    {
      "id": "215858",
      "values": [
        "67-749"
      ]
    },
    {
      "id": "225693",
      "values": [
        "975966000312"]
    },{
          "id": "129591",
          "valuesIds": ["129591_64"]   },
    {
      "id": "227345",
      "values": [
        "CASE IH C266525",
        "CASE IH C33025",
        "JOHN DEERE AM130365",
        "JOHN DEERE AM132990",
        "JOHN DEERE AM133094",
        "JOHN DEERE GY00185"
      ]
    }
  ],
        "description": {
          "sections": [
            {
              "items": [
                {
                  "type": "TEXT",
                  "content": "<p>Material: ABS and copper</p><p>OE Number: 33 331</p>"
                }
              ]
            }
          ]
        },
        "images": [
          "https://yibaistore.yibainetwork.com/end/upload3/image/assistant_no_logo/1618220253111/1618220253111-1.jpg"
        ],
        "delivery": {
          "shippingRates": {
            "id": "45cdb0ba-42e0-4c85-96f4-68785ff25809"
          },"handlingTime":"PT48H"
        },
        "location": {"countryCode": "CN", "city": "shenzhen", "postCode": "518000"},
        "sellingMode": {
          "format": "BUY_NOW",
          "price": {"amount": "42.44", "currency": "PLN"}
        },
        "impliedWarranty": {"id": "ff5f2a33-f2a8-4228-8e5e-3a5f4aaebf4c"},
        "returnPolicy": {"name": "zhongguocang"},
        "external": {"id": "Macoring-1618220253111"},
        "payments": {"invoice": "NO_INVOICE"},
        "stock": {"available":"99","unit":"UNIT"},
        "publication": {"duration":null,"status": "INACTIVE"}
      }
    }
  ]
}

Status: 422 Unprocessable Entity  , 

Response:{
  "errors": [
    {
      "code": "ConstraintViolationException.AtLeastOneMode",
      "message": "You must select at least one sale method and enter the required prices.",
      "details": "ConstraintViolationException.AtLeastOneMode",
      "path": "sellingMode.null",
      "userMessage": "Musisz wybrać przynajmniej jeden sposób sprzedaży oraz podać wymagane ceny."
    },
    {
      "code": "AvailableStockMustEqualToOneOrBeGreaterThanOne",
      "message": "The stock level of items to be listed may not be lower than 1.",
      "details": "AvailableStockMustEqualToOneOrBeGreaterThanOne",
      "path": "stock.available",
      "userMessage": "Wystawiana liczba nie może być mniejsza niż 1."
    },
    {
      "code": "VALIDATION_FAILED",
      "message": "prices.empty",
      "details": null,
      "path": "prices",
      "userMessage": "Ceny nie mogą być pustą listą."
    },
    {
      "code": "VALIDATION_FAILED",
      "message": "baseMarketplace.nonExistentPriceForBaseMarketPlace",
      "details": null,
      "path": "baseMarketplacePrice",
      "userMessage": "Oferta nie posiada ceny dla rynku bazowego."
    }
  ]
}

**Comment by Axlii50** [comment]
Info: Inserted missing quotes.
 Error:  [Code 180, Structure 111]
 Error:  [Code 22, Structure 235]
 Error:  [Code 22, Structure 236]
 Error:  [Code 141, Structure 237]
 Error:  [Code 22, Structure 237]
 
 Strukture Jsona jest błędnie zrobiona 
 Polecam stronke do formatowania oraz sprawdzania 
 https://jsonformatter.curiousconcept.com/#

**Comment by Axlii50** [comment]
Dokładniej mówiąc narzeka  na fragment ""content":"

Material: ABS and copper

OE Number: 33 331

"
                        }"

**Comment by Axlii50** [comment]
Wszelki inne kody są podane w responsie

**Comment by PrzemyslawLukanowski** [comment]
Problemem było to, że wszystkie dane podałeś w sekcji produktowej `productSet`, zwróć uwagę na to, które z pol należy podać poza tą sekcją - przykład znajdziesz w [dokumentacji](https://developer.allegro.pl/documentation#operation/createProductOffers). Jeśli nadal będziesz otrzymywać w odpowiedzi kod 422, podaj proszę przykładowe trace-id powiązane z operacją.
