### ISSUE TITLE
"Missing required parameters" error message

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#8216]
Hi there, 

I have a questions regarding the "ConstraintViolationException.MissingRequiredParameters" error. Right now we are only sending the parameters via Allegro that are needed to connect an offer to already existing product card. 

We were trying to list 2 offers and got the "ConstraintViolationException.MissingRequiredParameters" error for both. 
For product with EAN 8054703934935 we got: 
```
{
  "errors": [
    {
      "code": "ConstraintViolationException.MissingRequiredParameters",
      "message": "Missing required parameters: 3786, 249512, 202641, 201017, 3766",
      "details": "ConstraintViolationException.MissingRequiredParameters",
      "path": "parameters",
      "userMessage": "Missing mandatory parameters: Brand, Color, Neckline, Main Fabric, Main Pattern."
}
  ]
}
```
I tried to list the offer manually on Allegro but it seems that for this product, no product card exists. So why did we get this error message instead the one saying, that product with this ID was not found on Allegro? 
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/e9792ca1-dd3f-44bb-b757-fe05b4ab3a68)

On the other hand for the second product 190231765660 we got the same error message: 
```
{
  "errors": [
    {
      "code": "ConstraintViolationException.MissingRequiredParameters",
      "message": "Missing required parameters: 25568",
      "details": "ConstraintViolationException.MissingRequiredParameters",
      "path": "parameters",
      "userMessage": "Missing mandatory parameters: Capacity."
    }
  ]
}
```
But this time it seems that it is related to some already existing product card in Allegro catalogue:
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/d88145ae-ccdc-42bd-9841-313fd5d1599d)

So why do we get the same error message for these two cases when it is a different case? Is it possible to somehow differentiate between these two? 

Thank you in advance for your help! 

All the best, 

Dominika

**Comment by MaciejFrackowiak** [comment]
Please, use [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts) to check if the product exists in our product base. 
For "8054703934935" you will find a product with id=c6863b5e-2023-4328-ab6e-28a7907a1e15.
You will see that the product has only a few parameters, without required parameters.
Here, we can talk about topics connected to the API only - if you have any doubts about WWW please contact [Allegro support](https://allegro.pl/pomoc/kontakt).
