### ISSUE TITLE
Błąd 409 na nowym endpoicie - /sale/product-offers

### ISSUE THREAD

**Issue by bartexs6** [allegro/allegro-api#8217]
Witam,

Czy w nowym endpoincie POST /sale/product-offers, jest możliwość żeby zwrócił on błąd o kodzie 409? Tak jak to jest na przykład w przypadku PATCH /sale/product-offers/{offerId}?

**Comment by MaciejFrackowiak** [comment]
Nie, nie zwracamy błędu 409 dla [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers).

**Comment by bartexs6** [comment]
A co w przypadku gdy produkt, który próbuję dodać znajduje się już w katalogu produktów? Jaki kod błędu wtedy zwróci?
I czy da się odróżnić błąd oferty od błędu produktu?

**Comment by MaciejFrackowiak** [comment]
Są dwa podejścia:
1) wystawiasz ofertę z produktem, który jest już w naszej bazie produktów, zatem - możesz to łatwo zweryfikować korzystając z [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts);
2) wystawiasz ofertę z produktem, którego nie mamy w bazie - wówczas w requeście musisz przekazać wszystkie wymagane parametry produktowe, dla utworzenia nowego produktu.

Błędy zwracamy zgodnie z dokumentacją konkretnego zasobu. Spójrz także do [naszego poradnika](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem), gdzie opisujemy szczegółowo kolejne kroki działania z zasobami.
