### ISSUE TITLE
Weryfikacja

### ISSUE THREAD

**Issue by gvccc** [allegro/allegro-api#8218]
Dzień dobry,
Tworzymy aplikację dla naszej firmy. Chcemy móc mieć wgląd po API do ofert a w przyszłości je modyfikować. Moge prosić o weryfikacje aplikacji?  client id 43e52b2e60aa451baac29bebd7311761

**Comment by MaciejFrackowiak** [comment]
Jeżeli chcesz uzyskać dostęp do [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) to proszę skontaktuj się z opiekunem biznesowym (jeżeli takowego posiadasz) lub z obsługą Allegro poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
