### ISSUE TITLE
Aktywacja kont i Allegro Smart na Sandbox

### ISSUE THREAD

**Issue by qb90** [allegro/allegro-api#8219]
Cześć,
proszę o pomoc w aktywowaniu kont na Sandbox z możliwością wystawiania przedmiotów z Allegro Smart

konta zwykłe:
Client:106837152
Client:106837238 (+ Smart)
Client:106837241 (+ Smart)
Client:106837248 (+ Smart)

konta firmowe
firma1apaczka
firma2apaczka (+ Smart)
firma3apaczka (+ Smart)

**Comment by MaciejFrackowiak** [comment]
Konta zwykłe już są aktywne. Z kont zwykłych nie wystawisz ofert poprzez API, zatem służą de facto wyłącznie do kupowania. Natomiast odnośnie kont firmowych musisz dokończyć proces rejestacji tj. wykonać przelewy weryfikacyjne + przesłać dowolne pliki jako dokumenty firmowe. Zrobisz to z poziomu zakładki [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto).

**Comment by qb90** [comment]
Dzięki, firmowe już mają uzupełnione dane i czekają na weryfikację.

**Comment by MaciejFrackowiak** [comment]
Konta firmowe również już są zweryfikowane. Natomiast oznaczenie Smart uzyskasz po spełnieniu [standardowych wymagań](https://allegro.pl/pomoc/dla-sprzedajacych/informacje-dla-sprzedajacych/co-zrobic-aby-moje-oferty-byly-oznaczone-ikona-allegro-smart-lDkP8VbKncV) dla usługi.

**Comment by qb90** [comment]
Te wymagania trochę spowalniają ogólne korzystanie, ale rozumiem, że nie da się tego obejść.
Dzięki za pomoc.
