### ISSUE TITLE
Weryfikacja konta firmowego Allegro Sandbox

### ISSUE THREAD

**Issue by valentinetur** [allegro/allegro-api#8221]
Dzień dobry,
poproszę o aktywację konta firmowego na sandboxie - konto zarejestrowane na adres wigplaza.info@gmail.com

**Comment by MaciejFrackowiak** [comment]
Nie mamy w bazie konta o podanym adresie email. Aby potwierdzić rejestrację, należy kliknąć odnośnik w wiadomości wysyłanej po rejestracji - czy to zrobiłeś?

**Comment by valentinetur** [comment]
@MaciejFrackowiak 
<img width="1436" alt="Screenshot 2024-01-03 at 13 36 21" src="https://github.com/allegro/allegro-api/assets/150016919/bc2b7a62-5892-431d-8c72-dbbf4037b67f">

**Comment by MaciejFrackowiak** [comment]
Patrząc na adres URL to jest to screen z produkcyjnego Allegro, a nie Allegro Sandbox.

**Comment by valentinetur** [comment]
@MaciejFrackowiak 
Przepraszam, chodzi o https://apps.developer.allegro.pl/
<img width="1402" alt="Screenshot 2024-01-03 at 13 39 48" src="https://github.com/allegro/allegro-api/assets/150016919/388714c8-fe74-432a-bd2b-421d47514563">

**Comment by MaciejFrackowiak** [comment]
Ale to nadal nie jest Sandbox - jest on dostępny pod adresem https://allegro.pl.allegrosandbox.pl/ i tu musisz zarejestrować osobne od Allegro konto.

**Comment by valentinetur** [comment]
Так, źle opisałem w tytule. Potrzebuję aktywacji konta na https://apps.developer.allegro.pl/, aby utworzyć aplikację. Aktywowaliśmy konto zgodnie z instrukcjami już tydzień temu, ale nadal jest widoczne jak na zrzucie ekranu, że konto nie zostało aktywowane.
@MaciejFrackowiak

**Comment by MaciejFrackowiak** [comment]
Tam jest warunek łączny - skoro aktywowałeś konto, to pozostaje włączyć dwustopniowe logowanie.
