### ISSUE TITLE
Sandbox - zablokowana sprzedaż: zaległe płatności

### ISSUE THREAD

**Issue by UrszulaITA** [allegro/allegro-api#8222]
Czy to możliwe, że na koncie Sandbox zostały naliczone płatności?
Były kiedyś z tego konta robione testy, a obecnie konto jest zablokowane;

"Sprzedaż na Twoim koncie jest obecnie zablokowana. Powodem mogą być nieopłacone rachunki lub inne naruszenia Regulaminu. Aby odblokować możliwość sprzedaży, ureguluj zaległe płatności lub[ skontaktuj się z nami]"

Widzę, że 30 wrz 2023, 23:59 została naliczona kwota 10,67
Kwota się nie zmienia

Czy testy na Sandboxie są odpłatne? Byłam przekonana, że tylko używanie produkcyjnego Allegro jest płatne, a używanie Sandboxa nie.

Konto: testyita2

**Comment by MaciejFrackowiak** [comment]
Korzystanie z Sandbox jest bezpłatne. My chcąc zachować możliwie duże odwzorowanie działania Allegro naliczamy na Sandbox opłaty, ale możesz je uregulować bezpłatnie korzystając z symulatora płatności na stronie [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro).

**Comment by UrszulaITA** [comment]
Faktycznie! Bardzo dziękuje. Saldo już wyzerowane :)
