### ISSUE TITLE
WzA API nadanie przesyłek Paczkomat w PaczkoPunkcie

### ISSUE THREAD

**Issue by daniel93333** [allegro/allegro-api#8223]
Mam problem, chciałem skorzystać z nadania w PaczkoPunkcie, podobnie jak w issue #8128  ale dla przesyłek paczkomatowych.
Z tego co widzę to da się dla paczkomatów wybrać taką opcję nadania w WzA:
![image](https://github.com/allegro/allegro-api/assets/141407776/87a2969e-f7fd-4e47-a309-af61b2226acf)
Ale jak to zrobić przez API?

**Comment by PrzemyslawLukanowski** [comment]
Odpowiedzi udzieliliśmy w pierwotnym wątku #8128.
