### ISSUE TITLE
Aktywacja konta Sandbox

### ISSUE THREAD

**Issue by kamilOrlowski123** [allegro/allegro-api#8224]
Proszę o aktywację konta dla użytkownika sandbox: 106834533
Chciałem aktywować konto, zrobiłem wirtualny przelew, ale nie mogę aktywować dwuskładnikowego uwierzytelniania. Podałem kod z google authenticator, ale sms nie dochodzi a po drugiej próbie dostałem informację, że limit SMS został wyczerpany.

**Comment by PrzemyslawLukanowski** [comment]
Skonfiguruj jeszcze proszę [ustawienia wypłat](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat), pozwoli nam to dalej przeprocesować Twoje konto. Jeśli chodzi o dwustopniowe logowanie, to nie jest one wymagane w środowisku testowym do rejestracji aplikacji, nie wysyłamy tutaj również sms-ów. Jeśli jednak chcesz je włączyć, wpisz 12345, a przy logowaniu 123456.

**Comment by PrzemyslawLukanowski** [comment]
@kamilOrlowski123 Również po mojej stronie - konto aktywne.
