### ISSUE TITLE
Autoryzajca za pomocą Authorization Code flow - pobieram dane dotyczące ceny w ofercie - licytacji ale jak pobrać datę zakończenia licytacji?

### ISSUE THREAD

**Issue by Ziajak** [allegro/allegro-api#8225]
Witam,

za pomocą REST API uwierzytelniam się i otwieram sesję.
Mogę korzystać z:
/bidding/offers/{offerId}/bid
i pobieram dane odnośnie ceny w danej licytacji

Gdzie pobiorę informacje dotyczące daty zakończenia licytacji?
Czy tutaj to znajdę:
/offers/listing

Przy próbie wykorzystania '/offers/listing' wyrzuca mi błąd:
`{'errors': [{'code': 'VerificationRequired', 'message': 'Access is denied. Verification is required.', 'details': None, 'path': None, 'userMessage': 'Brak dostępu do danego zasobu. Dostęp możliwy tylko dla zweryfikowanych aplikacji.'}]}
Koniec programu
`

Przykładowy kod, gdzie już za pomocą access_token otwieram sesje:

`headers = {}
headers['charset'] = 'utf-8'
headers['Accept-Language'] = 'pl-PL'
headers['Content-Type'] = 'application/json'

headers['Accept'] = 'application/vnd.allegro.public.v1+json'
headers['Authorization'] = "Bearer {}".format(access_token)

with requests.Session() as session:
    session.headers.update(headers)

    DEFAULT_API_URL = 'https://api.allegro.pl'

    response = session.get(DEFAULT_API_URL + '/offers/listing?category.id=77917&phrase=laptop&fallback=false&limit=1&searchMode=DESCRIPTIONS')
                          
    
    print(response.json())

print("Koniec programu")`

**Comment by MaciejFrackowiak** [comment]
Dostęp do zasobu [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) jest limitowany, zatem prawidłowo otrzymałeś informację o braku dostępu. Jeżeli chciałbyś uzyskać dostęp to skontaktuj się ze swoim opiekunem biznesowym (jeśli takowego posiadasz) lub poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z obsługą Allegro.

**Comment by Ziajak** [comment]
Dziękuje za szybko odpowiedź.
Napisałem poprzez formularz. 
Rozumiem, że informacja o dacie zakończenia licytacji znajduje się w tym zasobie:
GET /offers/listing
?

**Comment by MaciejFrackowiak** [comment]
Tak, dla licytacji zwracamy pole "publication" ze zwracaną wartością endingAt.

**Comment by Ziajak** [comment]
Rozumiem. Dziękuje.
Na chwilę obecną nie ma dostępnego jakiegoś zasobu, który jest od razu dostępny i mógłbym uzyskać takie dane -
data zakończenia licytacji ?

**Comment by MaciejFrackowiak** [comment]
Nie, takie dane są widoczne tylko dla sprzedawcy danej oferty.

**Comment by Ziajak** [comment]
Dziękuje za pomoc!
