### ISSUE TITLE
Błąd logowania

### ISSUE THREAD

**Issue by kamilOrlowski123** [allegro/allegro-api#8226]
Cześć,

coś jest nie tak ze środowiskiem sandbox, nie mogę się zalogować oraz zrestartować hasła, dostaję komunikat "Coś poszło nie tak. Spróbuj ponownie za chwilę."

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście mieliśmy chwilowe problemy, obecnie wszystko już działa prawidłowo. Przepraszam za niedogodności.
