### ISSUE TITLE
Aktywacja konta allegro sandbox

### ISSUE THREAD

**Issue by Jochca** [allegro/allegro-api#8227]
Dzień dobry, piszę w sprawie prośby o aktywację konta sandbox dla dwóch podanych adresów e-mail:
1. pawel.chmura@innovationsoftware.pl
2. pawel.chmura04@gmail.com

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, aktywowałem pierwsze konto, a w przypadku drugiego skonfiguruj jeszcze proszę [ustawienia wypłat](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat), co pozwoli mi je dalej przeprocesować.
