### ISSUE TITLE
Masowa zmiana podatku VAT na rynku czeskim

### ISSUE THREAD

**Issue by premax** [allegro/allegro-api#8228]
Dzień dobry

Ponieważ z nowym rokiem zmieniono w CZ stawki VAT i niestety Allegro w "moich" kategoriach (t.j. książka) z niewiadomych przyczyn postanowiło nie konwertować starych stawek (10%) na nowe (0%), to potrzebuję masowo zmienić stawki VAT na czeskim rynku. 

Próbowałem tak:

` {
    "modification": {
    "marketplaceId": "allegro-cz",
    "payments": {
      "invoice": "VAT",                            
      "tax": {                                     
         "percentage": "EXEMPT"                     
      }                                            
    }
   },
    "offerCriteria":[
      {
        "type":"CONTAINS_OFFERS",
        "offers":[
         {
           "id":"14922280501"
         },
         {
          "id":"14922280425"
         }
       ]
     }
    ]
 }
`

ale dostaję zwrotkę: 

>  "code": "SETTING_NOT_FOUND",
>                     "message": "This VAT setting is not found for the rate: 10.00, subject: GOODS, exemption basis: null, and country: CZ.",
> 

Więc pewnie coś robię nie tak?
Traceid: 416b0f24ddb90959

Oddzielnym pytaniem jest, dlaczego w kategorii Książki pokazujecie do wyboru VAT EXEMPT a nie 0%, ale to podobno już ogarniacie.

PP

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, wskazany zasób umożliwia edycję stawki VAT wyłącznie dla bazowego kraju wysyłki oferty, zatem aby zmienić je dla countryCode: CZ, musisz wykonać to z osobna dla każdej oferty przy pomocy [PATCH /sale/product-offers/{offerID}](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pojedynczej-oferty).

> Oddzielnym pytaniem jest, dlaczego w kategorii Książki pokazujecie do wyboru VAT EXEMPT a nie 0%, ale to podobno już ogarniacie.

Podatkowo nie mamy dostępnej stawki 0%, możesz zadeklarować zwolnienie (EXEMPT) lub że towar jest poza VAT (OUT_OF_SCOPE_OF_VAT). Dotyczy to wszystkich kategorii.
