### ISSUE TITLE
Możliwość edycji umowy własnej

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#8229]
Posiadamy umowę własną z Pocztą Polską. Ich API jest dość ciekawe, bo autoryzacja opiera się na haśle do konta. Hasło to jest zmieniane co 30 dni, bo taki wymóg stawia Poczta Polska. Należałoby co 30 dni robić autoryzacje w ustawieniach zamówień Allegro

![image](https://github.com/allegro/allegro-api/assets/37405655/44fcc488-9571-442b-be11-976d8fa84256)

Czy istnieje metoda API, to updatu umowy własnej?

**Comment by PrzemyslawLukanowski** [comment]
Nie, nie udostępnimy takiego API.

**Comment by daniel93333** [comment]
Podłączę się do tematu apropo poczty polskiej. Żeby dodać tą umowę trzeba dodać dane do logowania dla e-nadawacy, ale nie da się nadawać przez WzA przesyłek Allegro Kurier Pocztex ani Allegro Odbiór w Punkcie Pocztex. Da się tylko nadać te przesyłki w wersji pobraniowej. Czy to nie jest błąd? Skoro takie przesyłki bez pobrania można poprawnie nadać bezpośrednio w e-nadawcy rozliczając poprawnie smarta, to dlaczego nie da się w WzA?
![image](https://github.com/allegro/allegro-api/assets/141407776/1a77b999-c63a-4f4a-ae7c-e48f038897f2)

**Comment by daniel93333** [comment]
Zrobiłem test i dodałem z palca credentialsId - etykieta wygenerowała się poprawnie, ale mimo to nie widać jej w e-nadawcy.
Proszę o weryfikację - commandId: 4677581f-4256-4e68-b969-0c0e3fbd74a2
