### ISSUE TITLE
doGetSiteJournalDeals a doGetMySoldItems - różnice w wynikach

### ISSUE THREAD

**Issue by omecon-allegro** [allegro/allegro-api#823]
1. Witam wywołuje te metody i otrzymuje różne wyniki. Tzn metoda doGetMySoldItems zwraca więcej wyników niż metoda doGetSiteJournalDeals.

Oto wyniki metody doGetSiteJournalDeals :
DealEventId:3982040286;DealEventType:1;DealId:1882236809;DealEventTime:1537610129;DealTransactionId:0;DealSellerId:48288104;DealItemId:7402523408;DealQuantity:1
DealEventId:3982040963;DealEventType:2;DealId:1882236809;DealEventTime:1537610160;DealTransactionId:903616346;DealSellerId:48288104;DealItemId:7402523408;DealQuantity:1
DealEventId:3984577212;DealEventType:1;DealId:1883113426;DealEventTime:1537728284;DealTransactionId:0;DealSellerId:48288104;DealItemId:7402819955;DealQuantity:1
DealEventId:3984579881;DealEventType:2;DealId:1883113426;DealEventTime:1537728322;DealTransactionId:904173626;DealSellerId:48288104;DealItemId:7402819955;DealQuantity:1
DealEventId:3984583262;DealEventType:1;DealId:1883115301;DealEventTime:1537728376;DealTransactionId:0;DealSellerId:48288104;DealItemId:7402819955;DealQuantity:1
DealEventId:3984583775;DealEventType:2;DealId:1883115301;DealEventTime:1537728383;DealTransactionId:904174601;DealSellerId:48288104;DealItemId:7402819955;DealQuantity:1

A oto wyniki doGetMySoldItems:
ItemId:7404863035;ItemTitle:Wyczerpany wkład do długopisu2;ItemThumbnailUrl:
ItemId:7402832578;ItemTitle:Wyczerpany wkład do długopisu długiego;ItemThumbnailUrl:
ItemId:7402523408;ItemTitle:Wyczerpany wkład do długopisu;ItemThumbnailUrl:
ItemId:7402407610;ItemTitle:Wyczerpany wkład do długopisu;ItemThumbnailUrl:
ItemId:7383597310;ItemTitle:Wyczerpany wkład do długopisu;ItemThumbnailUrl:
ItemId:7400471149;ItemTitle:Wyczerpany wkład do długopisu2;ItemThumbnailUr
ItemId:7402819955;ItemTitle:Wyczerpany wkład do długopisu;ItemThumbnailUrl:
ItemId:7472820200;ItemTitle:20180724/4;ItemThumbnailUrl:

Czy mogę prosić o wyjaśnienie?

2. Dlaczego w przypadku ofery 7402819955 orzymujemy podwójne wyniki w metodzie doGetSiteJournalDeals? Podobnie na koncie allegro(https://allegro.pl/seller-orders/#!/) dana sprzedaz widoczna jest 2 razy? Na aukcji był wystawiony 1 przedmiot i został kupiony przez jedną osobę.

**Comment by PawelTaberski** [comment]
Odnośnie podwójnych danych to zgodnie z dokumentacją otrzymujesz najpierw dealEventType 1 czyli utworzenie aktu zakupowego a potem 2 czyli uzupełnienie formularza pozakupowego. Więcej na temat tej metody znajdziesz [tutaj](https://allegro.pl/webapi/documentation.php/show/id,742#method-output).
Odnośnie ilości zakupów widzę że jednego dnia we wrześniu w odstępach około minutowych jeden user kupił od ciebie po 1 sztuce przedmiotu dwukrotnie.

**Comment by omecon-allegro** [comment]
W punkcie 1 chodziło o to, że metoda doGetSiteJournalDeals zwraca tylko dane dla:
7402523408, 7402819955
natomiast metoda doGetMySoldItems:
7404863035, 7402832578, 7402523408, 7402407610, 7400471149, 7402819955, 7472820200

nie wiem jak mam to napisać?

**Comment by PawelTaberski** [comment]
Teraz rozumiem :-) rozbieżność zwróconej ilości sprzedanych ofert wynika z różnych czasów z jakich zwracamy dane w przypadku doGetSiteJournalDeals są zwracane z ostatnich 45 dni, dlatego widzisz tam dwie najnowsze sprzedaże, a starszych już nie.

**Comment by omecon-allegro** [comment]
1. Ile dni wynosi to dla doGetMySoldItems?
2. parametr metody doGetSiteJournalDeals - journalStart. Punkt startu, pozwalający na sterowanie pobieraniem kolejnych porcji danych dot. informacji o zdarzeniach związanych z formularzami pozakupowymi (jego wartość zwracana jest w polu dealEventId struktury siteJournalDeals).
Zdaje się, że w dokumentacji jest pewna niejednoznaczność:
Zwracanych jest zawsze 100 **najnowszych** zdarzeń (zaczynając od punktu podanego w parametrze journalStart), posortowanych rosnąco po czasie ich wystąpienia. Aby sterować pobieraniem kolejnych porcji danych (**tak aby dotrzeć do danych najświeższych**), należy w parametrze journalStart przekazywać wartość dealEventId ostatniego (setnego) elementu, zwracanego w ramach danego wywołania i robić to sukcesywnie, dopóki w wyniku wywołania nie otrzyma się porcji danych mniejszej niż 100 elementów (co będzie świadczyło, że otrzymane dane są danymi najświeższymi).
te dwa wyboldowane fragmenty się wykluczają. Rozumiem, że na początku są podawane najstarsze zdarzenia?

**Comment by PawelTaberski** [comment]
Odnośnie Twoich pytań:
1/ Zwraca wynik z ostatnich 60 dni potem oferty trafiają do archiwum.
2/ metoda zwraca maksymalnie 100 od danego punktu startu i tak jak napisałeś sortuje od najstarszych do najnowszych.

**Comment by omecon-allegro** [comment]
Czy nie można by ponieważ mamy tu 100 w wyniku umożliwić też 100 w metodach:
doGetPostBuyData, doGetTransactionsIDs i doGetPostBuyFormsDataForSellers?

**Comment by PawelTaberski** [comment]
Na chwilę obecną powoli zmierzamy w kierunku całkowitego przejścia na REST API, dlatego wszelkie zmiany i nowości wdrażamy już tylko tam. I obecnie nie planujemy wdrażania zmian w tych metodach jakie wymieniłeś w WebAPI.

**Comment by omecon-allegro** [comment]
Póki co to REST api się nie nadaje np z powodu problemów z logowaniem wielu użytkowników. Bardzo chcielibyśmy przepisać wszystko na rest api.

**Comment by PawelTaberski** [comment]
Jakie dokładnie masz na myśli problemy z logowaniem, jeśli chodzi Tobie o zapamiętywanie sesji to pracujemy nad tym.

**Comment by omecon-allegro** [comment]
dokładnie o tym myśle oraz o tym że brak możliwości wyświetlania kto jest zalogowany. Po rozkodowaniu tokena mamy dostęp tylko do userId bez loginu a nie ma metody na pobranie takowych danych.
Ok wróćmy do metody doGetSiteJournalDeals. Mam tu 2 problemy.
1.
Dostajemy 100 najstarszych zdarzeń  (zaczynając od punktu podanego w parametrze journalStart).
Nie jest to niestety prawdą.
W pierwszym wywołaniu otrzymujemy:
DealEventId:3982040286;DealEventType:1;DealId:1882236809;DealEventTime:1537610129 Sat Sep 22 11:55:29 CEST 2018;DealTransactionId:0;DealSellerId:48288104;DealItemId:7402523408;DealQuantity:1
DealEventId:3982040963;DealEventType:2;DealId:1882236809;DealEventTime:1537610160 Sat Sep 22 11:56:00 CEST 2018;DealTransactionId:903616346;DealSellerId:48288104;DealItemId:7402523408;DealQuantity:1
DealEventId:3984577212;DealEventType:1;DealId:1883113426;DealEventTime:1537728284 Sun Sep 23 20:44:44 CEST 2018;DealTransactionId:0;DealSellerId:48288104;DealItemId:7402819955;DealQuantity:1
DealEventId:3984579881;DealEventType:2;DealId:1883113426;DealEventTime:1537728322 Sun Sep 23 20:45:22 CEST 2018;DealTransactionId:904173626;DealSellerId:48288104;DealItemId:7402819955;DealQuantity:1
DealEventId:3984583262;DealEventType:1;DealId:1883115301;DealEventTime:1537728376 Sun Sep 23 20:46:16 CEST 2018;DealTransactionId:0;DealSellerId:48288104;DealItemId:7402819955;DealQuantity:1
DealEventId:3984583775;DealEventType:2;DealId:1883115301;DealEventTime:1537728383 Sun Sep 23 20:46:23 CEST 2018;DealTransactionId:904174601;DealSellerId:48288104;DealItemId:7402819955;DealQuantity:1
DealEventId:4064573103;DealEventType:1;DealId:1906609871;DealEventTime:1540821774 Mon Oct 29 15:02:54 CET 2018;DealTransactionId:0;DealSellerId:48288104;DealItemId:7643264376;DealQuantity:1

teraz ustawiamy journalStart na DealEventTime ostatniego zdarzenia(1540821774) i o dziwo otrzymujemy te same wyniki:
DealEventId:3982040286;DealEventType:1;DealId:1882236809;DealEventTime:1537610129 Sat Sep 22 11:55:29 CEST 2018;DealTransactionId:0;DealSellerId:48288104;DealItemId:7402523408;DealQuantity:1
DealEventId:3982040963;DealEventType:2;DealId:1882236809;DealEventTime:1537610160 Sat Sep 22 11:56:00 CEST 2018;DealTransactionId:903616346;DealSellerId:48288104;DealItemId:7402523408;DealQuantity:1
DealEventId:3984577212;DealEventType:1;DealId:1883113426;DealEventTime:1537728284 Sun Sep 23 20:44:44 CEST 2018;DealTransactionId:0;DealSellerId:48288104;DealItemId:7402819955;DealQuantity:1
DealEventId:3984579881;DealEventType:2;DealId:1883113426;DealEventTime:1537728322 Sun Sep 23 20:45:22 CEST 2018;DealTransactionId:904173626;DealSellerId:48288104;DealItemId:7402819955;DealQuantity:1
DealEventId:3984583262;DealEventType:1;DealId:1883115301;DealEventTime:1537728376 Sun Sep 23 20:46:16 CEST 2018;DealTransactionId:0;DealSellerId:48288104;DealItemId:7402819955;DealQuantity:1
DealEventId:3984583775;DealEventType:2;DealId:1883115301;DealEventTime:1537728383 Sun Sep 23 20:46:23 CEST 2018;DealTransactionId:904174601;DealSellerId:48288104;DealItemId:7402819955;DealQuantity:1
DealEventId:4064573103;DealEventType:1;DealId:1906609871;DealEventTime:1540821774 Mon Oct 29 15:02:54 CET 2018;DealTransactionId:0;DealSellerId:48288104;DealItemId:7643264376;DealQuantity:1

2.
W przypadku kiedy mamy tych wyników więcej może się wydarzyć, że w pierwszej "paczce" zwróconych wyników dostaniemy DealEventType: 1 a dopiero po tym jak odpytamy o następną "paczkę" danych dostaniemy DealEventType: 2 także, żeby odpowiedzieć sobie na pytanie czy jest formularz pozakupowy czy nie musimy odpytać o cały dziennik zdarzeń. Czyli w przypadku użytkowników z dużą ilością transakcji takie działanie wydaje się mało efektywne. Czy to jakoś można rozwiązać?

**Comment by omecon-allegro** [comment]
Dziekuję za szybką odpowiedź.
oki mea culpa, rzeczywiście to działa w przypadku pierwszego punktu.
czy coś możemy poradzić w punkcie 2?

**Comment by omecon-allegro** [comment]
Czy mógłbym prosić o jakieś informacje na temat zwracanych typów zdarzeń?
dealEventType | int
Typ zdarzenia (1 - utworzenie aktu zakupowego (deala), 2 - utworzenie formularza pozakupowego (transakcji), 3 - anulowanie formularza pozakupowego (transakcji), 4 - zakończenie (opłacenie) transakcji przez Allegro Finanse). Każde z typów zdarzeń (oprócz 1, dla którego ID transakcji nie jest jeszcze znane), generowane jest osobno dla każdego deala wchodzącego w skład transakcji.

W tej chwili udało mi się uzyskać typy 1 i 2. Zakładam, że w pesymistycznym przypadku mogą się one pojawić w dwóch różnych odpowiedziach metody doGetSiteJournalDeals. Także nie do końca będzie działał scenariusz opisany tu:
https://allegro.pl/webapi/tutorials.php/tutorial/id,100421

Kiedy pojawiają się typy 3 i 4? W jakich przypadkach? Nie znalazłem opcji na anulowanie formularza pozakupowego.

**Comment by PawelTaberski** [comment]
3 otrzymujesz w przypadku anulowania płatności w takim wypadku musisz również jeszcze raz uzupełnić formularz.
Natomiast 4 otrzymujesz jak płatność przeszła z sukcesem i jest zatwierdzona.
