### ISSUE TITLE
Product exist - parameter does not match

### ISSUE THREAD

**Issue by acerov** [allegro/allegro-api#8231]
Hello,

I am creating product offer and sending EAN and server returns error that parameter Length does not match product parameter Length.

BUT our Length is correct, whe checked EAN and length is ok, obviously Length in products are not correct.

What to do?

We can not report you errors in products and wait till it is fixed because we have thousands of products, it will be huge job.

Trace id: 7469d476e9acc591

**Comment by jezewskiBNetrox** [comment]
@acerov Sadly that's how product catalog in Allegro works - if product with EAN already exists you can only report errors and nothing else. If you want help, you need to report errors and wait. It is a big issue with catalog people complain about from a very beginning.

**Comment by acerov** [comment]
I understand, I avoided that error with getting parameters from product catalog. I know it is a shortcut but that way offers get through. Thank you for your help.
