### ISSUE TITLE
API dla klienta

### ISSUE THREAD

**Issue by dawidof** [allegro/allegro-api#8232]
Jako klient, mam historię zamówień, ale te zamówienia już za 2-3 lata znikają i już nie możliwości zobaczyć opis produktu i inne dane. Na allegro można zobaczyć, że są towary który mają 5-letnią gwarancję albo nawet dłużej, ale historia zamówień po prostu znika i to jest słabe. Rozumiem, że trzymanie informacji (obrazków) wymaga dodatkowych zasobów finansowych. Więc stąd moja idea, czy w ogóle jest taka opcja zrobienie API dla klienta, nie dla sprzedawcy? Jako klienci mogliśmy by trzymać informację o naszych zamówieniach przynajmniej lokalnie. Myślę, że nie jestem taki jedyny który ma problem usuniętą historią zamówień i potrzebuję tą historię.

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie mamy takich planów. Otrzymaliśmy już jednak taką sugestię, na którą głos możesz oddać w zakładce Discussions, [w tym wątku](https://github.com/allegro/allegro-api/discussions/5394).

**Comment by dawidof** [comment]
Ile potrzeba głosów, żeby to zacząć implementować?

**Comment by PrzemyslawLukanowski** [comment]
Wpływ mają na to także nasze wewnętrzne zależności, na ile będzie możliwe udostępnienie takiego endpointu - w momencie ustalenia decyzji poinformujemy w wątku.
