### ISSUE TITLE
Aktywacja konta sandbox.

### ISSUE THREAD

**Issue by salesconnectsandbox** [allegro/allegro-api#8233]
Cześć, proszę o aktywację konta sandbox zarejestrowanego na email techsalesconnect@gmail.com

Proszę również o informację czy po aktywacji muszę coś aktywować w panelu deweloperskim czy to już będzie śmigać ?

**Comment by PrzemyslawLukanowski** [comment]
Cześć, aktywowałem konto i tak, możesz już zarejestrować aplikację na stronie https://developer.allegro.pl.allegrosandbox.pl/

**Comment by adamGitTest** [comment]
Korzystając z otwartego wątku również prosiłbym o aktywację innego konta w sposób który umożliwi dostęp do API z użyciem autoryzacji device flow w zakresie wystawiania ofert allegro w środowisku sandbox.
LOGIN
businessABS
E-MAIL
businesscommerceabs@gmail.com

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.
