### ISSUE TITLE
Listing Issues with Channel Advisor - EAN & Parameter identifer

### ISSUE THREAD

**Issue by SonovaConsumerHearing** [allegro/allegro-api#8234]
Hi all,

I'm trying to list products via Channel Advisor but I keep receiving the following error messages:

_"Error from Allegro PL: Linking with product failed. For closest match the following values need to be updated: Parameter 'EAN (GTIN)' with values: [4044155249545] should be changed to values: [4012418044657, 4044155249545]. (id ProductFailedDataValidation)"_

**What do I have to do to get rid of this error message? I only want to enter the value "4044155249545" since this is the only correct EAN. The other suggested EAN is not correct. I'm experiencing this with a few more products.**

I also have a question regarding the Parameter identifer, I'm receiving this error message: _"Error from Allegro PL: The value of the attribute with identifier 217641 can contain up to 255 characters.|The value of the attribute with identifier 217641 can contain up to 255 characters.|ConstraintViolationException.MaxSize (id ProductFailedUpdate)"_

**Where do I get a list of the attribute/parameter identifier numbers? I'm not sure what attribute the error message is referring to.** 

Thank you for your help!

**Comment by PrzemyslawLukanowski** [comment]
Hi, please remember in the future to report errors that occur in Channel Advisor directly to their support. Thanks to that, they can send us more specific logs that can help us solve the problem.

The first error indicates that based on other parameters we found an existing product in our Catalog and we are trying to associate your offer with it. There's a discrepancy between the EAN in our database and the EAN you sent. You have two options:

- change the EAN in your offer according to the information in the error message;
- report incorrect data in our catalog. I assume your product is Headphones on-the-ear Sennheiser HD 600 so you can do it via this form - https://allegro.pl/moje-allegro/sprzedaz/produkt/zglos-blad/e4169b8b-e644-419d-81b7-7d0c807a7a2a (this is the product with which we are trying to link your offer);

The parameter 217641 is 'Additional features'. The list of all parameters in the given category can be retrieved via API, using [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2).
