### ISSUE TITLE
Numer zamówienia a "czas na wysłanie"

### ISSUE THREAD

**Issue by ZAK2828** [allegro/allegro-api#8235]
Dzień dobry,
Nie jestem programistą, ale potrzebuje się dowiedzieć czy jest jakiś sposób za pomocą API uzyskać takie dane o zamówieniu, żeby każdemu numerowi zamówienia przypisać "czas na wysłanie", które jest w zamówieniu.
Chodzi mi o te pole "czas na wysłanie":
![obraz](https://github.com/allegro/allegro-api/assets/63778087/62c0b33d-812f-4239-9da7-3b53dfcb0463)
Jeżeli tak, to czy mogliby Państwo podesłać jak nazywają się te zasoby, link do dokumentacji o tym itp.?
Z góry dziękuję za pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, 
Tak, zwracamy informacją o 'czasie na wysłanie' w odpowiedzi [GET /order/checkout-forms](https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET) i [GET /order/checkout-forms/{Id} ](https://developer.allegro.pl/documentation#operation/getOrdersDetailsUsingGET). Data zawarta jest w polu `time.dispatch.to`.
