### ISSUE TITLE
Aplikacje

### ISSUE THREAD

**Issue by Tanioagd** [allegro/allegro-api#8239]

**Comment by Tanioagd** [comment]
Mamy zainstalowane 5 aplikacji. Potrzebuję jedną usunąć. Nie wiem kto wcześniej je instalował i do czego służą. Mogę prosić o jakąś podpowiedź

![Zrzut ekranu 2024-01-08 140323 allegro](https://github.com/allegro/allegro-api/assets/155977034/692d2efe-17fe-4db5-a8c8-ce1b2f875d87)

**Comment by PrzemyslawLukanowski** [comment]
Na żadnej z aplikacji nie widzimy ruchu w ciągu ostatnich kilku miesięcy, w związku z czym nie możemy stwierdzić, do czego konkretnie były używane. Wygląda jednak na to, że na tę chwilę nie są wykorzystywane.
