### ISSUE TITLE
Oferty z tagami dodanymi przez REST API nie pojawiają się na stronie użytkownika

### ISSUE THREAD

**Issue by jkubacki** [allegro/allegro-api#824]
1. Dodaję tagi przez REST API (`POST sale/offers/{offerId}/tags`)
2. Widzę że tagi są dodane jak wchodzę w w edycję oferty (https://allegro.pl/offer/{offerId}) Tagi są też zwracane w endpoincie `GET /sale/offers/{offerId}/tags`
3. Na stronie https://allegro.pl/uzytkownik/{login} w tagach nie widać produktów.

Po wejściu na stronę edycji oferty i zapisaniu oferty po pewnym czasie się pojawiają na stronie użytkownika.

Czy powinienem zrobić coś jeszcze oprócz `POST sale/offers/{offerId}/tags` aby aktywna oferta pojawiła się pod tagiem na stronie użytkownika?

Próbowałem wykonać `PUT /sale/offer-publication-commands/` - bez efektu

**Comment by PawelTaberski** [comment]
Wystarczy, że przypiszesz je, tak jak napisałeś przy pomocy metody POST na zasobie /sale/offers/{offer_ID}/tags. 
Więcej na temat tagów i jak korzystać z zasobów z tym związanych w REST API znajdziesz [tutaj](https://developer.allegro.pl/news/2018-09-24-Tagi-zalaczniki/).
Zmiana na froncie może zająć chwilę w przypadku tagów czasem warto odczekać dobrą godzinę

**Comment by jkubacki** [comment]
Hej Paweł. Dzięki za odpowiedź.

Taj jak pisałem - użyłem metody POST na zasobie `/sale/offers/{offer_ID}/tags`.

Na froncie od strony edycji oferty `https://allegro.pl/offer/{offerId}` tagi są dodane i widać je w polu do edycji.

Niestety po 24h wciąż tagi nie są widoczne na stronie `https://allegro.pl/uzytkownik/{login}`. Więc na dobrą sprawę nie spełniają w ogóle swojej funkcji jaką jest przedstawienie użytkownikom oferty po tagach.

Widoczne są dopiero po zapisaniu oferty (bez zmian) od strony `https://allegro.pl/offer/{offerId}`. Wygląda na to że jakiś cache się nie odświeża do tej listy po dodaniu tagów.

Tagi dodaję do *aktywnych* ofert (nie do draftów, które później publikuję).

Proszę o zbadanie sprawy.

**Comment by PawelTaberski** [comment]
Przetestowałem na przykładowej ofercie i tag dodał się po chwili. Czy problem u Ciebie dalej występuje? Jeśli tak podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a z przypisania taga wraz z Trace-id tego zadania. Podeślij dane od takiego taga, który nie chce się przypisać. Sprawdzimy w czym jest problem.

**Comment by jkubacki** [comment]
Nie. Mam dokładnie ten sam problem i nie znalazłem rozwiązania innego niż ręczne wchodzenie w edycję każdej aukcji i jej zapisywanie. W moim przypadku skala to około 25000 aukcji.

Problem nie jest związany z konkretnym zapytaniem do api więc wysłanie pojedynczego curla mija się z celem. Domyślam się, że wina tutaj może być po stronie źle odświeżanego cache przy tej metodzie dodania tagów.

**Comment by PawelTaberski** [comment]
@dlis2010 Sprawdziłem na podstawie oferty jaką podesłałeś i rzeczywiście jest jakiś problem. Sprawę przekazałem do odpowiedniego zespołu. Proszę o cierpliwość.

**Comment by jkubacki** [comment]
@PawelTaberski jest jakiś update w tej sprawie? Sprawdziłem i problem nadal występuje.

**Comment by PawelTaberski** [comment]
Pracujemy nad rozwiązaniem tego problemu, proszę o jeszcze trochę cierpliwości.

**Comment by PawelTaberski** [comment]
@jkubacki Problem nie powinien już występować. Daj proszę znać czy u Ciebie teraz działa.

**Comment by jkubacki** [comment]
Problem nie występuje. Tagi aktualizują się poprawnie na stronie użytkownika.

Przepraszam za tak późną odpowiedź. Dzięki za pomoc @PawelTaberski
