### ISSUE TITLE
How to activate offer?

### ISSUE THREAD

**Issue by acerov** [allegro/allegro-api#8240]
Hi,

I am trying to PATCH offer and set Status to "ACTIVE" but am receiving error:
"The HTTP method is not allowed"

What am I doing wrong?

I found info on "activating" offer here:
https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#offer-status-change

Trace-id: 7cd44aece4d9dd18

**Comment by PrzemyslawLukanowski** [comment]
Hi, you received an error cause instead of /sale/product-offers/{offerId} you indicated /sale/offers/{offerID} route.
