### ISSUE TITLE
Błąd "receiver.email","userMessage":"Podany hash-mail jest niepoprawny"

### ISSUE THREAD

**Issue by kdabek** [allegro/allegro-api#8242]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Zgłaszam błąd, który już pojawiał się w innych wątkach:
```
{
   "code":"SERVICE_NOT_AVAILABLE",
   "message":"Requested hashed mail was not recognized",
   "details":"Requested hashed mail was not recognized",
   "path":"receiver.email",
   "userMessage":"Podany hash-mail jest niepoprawny"
}
```

e-mail podany w zamówieniu wydaje się poprawny i jest na koncie sandbox: `1i4t8xu8rq+405373891@user.allegrogroup.pl`

trace_id: efc043734c984fdc

**Comment by PrzemyslawLukanowski** [comment]
Wygląda na to, że próbujesz utworzyć przesyłkę na środowisku produkcyjnym zamiast testowym - tego właśnie środowiska dotyczy wskazane trace-id.
