### ISSUE TITLE
dostęp do ofert

### ISSUE THREAD

**Issue by Lotier6** [allegro/allegro-api#8244]
Chciałbym uzyskać dostęp przez API do wybranych ofert wystawionych na Allegro? Czy jest to możliwe? Konkretnie chciałbym je udostępnić w moim sklepie.

**Comment by Lotier6** [comment]
Dziękuję bardzo!
A czy do oferty innych sprzedawców też mogę mieć dostęp przez API?

**Comment by PrzemyslawLukanowski** [comment]
Taki dostęp jest możliwy w ograniczony sposób w ramach [GET /offers/listing](https://developer.allegro.pl/documentation#operation/getListing), jednak dostęp do tego zasobu wymaga weryfikacji aplikacji. Cel, o którym wspomniałeś na początku, jest w takim przypadku niezgodny z naszym [regulaminem](https://developer.allegro.pl/rules) (punkt 4.1c):

> 4.1.
> 
> Oprogramowanie REST API nie może być wykorzystywane w sposób naruszający prawa Spółki oraz osób trzecich, w szczególności niedozwolone jest:
> c. wykorzystywanie do prezentowania w serwisach konkurencyjnych Ofert (w tym Ofert archiwalnych) publikowanych w ramach Allegro,
