### ISSUE TITLE
Brak błędu przy podaniu obcej waluty w polu insurence dla przesyłki.

### ISSUE THREAD

**Issue by radz2k** [allegro/allegro-api#8245]
URL: https://api.allegro.pl/shipment-management/shipments/create-commands

Robimy integrację z przesyłkami Allegro i testując utworzenie pierwszej przesyłki na produkcji napotkaliśmy nietypową sytuację.

`    "insurance" => array:2 [▼
      "amount" => "1266.00"
      "currency" => "CZK"
    ]`

Podaliśmy wartość w czeskich koronach oraz walutę CZK, natomiast przesyłka utworzyła się z tą samą wartością ale w PLN.

`  +"insurance": {#2631 ▼
    +"amount": "1266.0"
    +"currency": "PLN"
  }`

Jeśli ubezpieczenie przesyłki jest możliwe wyłącznie w PLN to zdaje się że powinien zostać zwrócony błąd w tej sytuacji.

Brak komunikatu błędu może tutaj powodować, że klienci przez niewiedzę będą ubezpieczać przesyłki na błędne kwoty. Ma to swoje konsekwencje szczególnie w walutach takich jak CZK, gdzie stosunek do PLN jest nawet kilkukrotny.

Proszę o weryfikację.

**Comment by AureliuszBrussy** [comment]
Czy jesteś w stanie wskazać trace-id wywołania (zwracamy w nagłówku response'a), gdzie utworzyłeś taką przesyłkę lub id komendy (ew. przesyłki)? Zweryfikujemy to.

**Comment by radz2k** [comment]
`{#2601 ▼
  +"commandId": "81c2227c-6d79-4430-9636-2afd7418dae8"
  +"status": "SUCCESS"
  +"errors": null
  +"shipmentId": "0d42f2b1-17d9-4d1a-b190-0c6ac64d5ad9"
}`

**Comment by radz2k** [comment]
![image](https://github.com/allegro/allegro-api/assets/2965966/5229d9e8-7bfd-4b17-bad6-0a35493e044a)

**Comment by AureliuszBrussy** [comment]
@radz2k wyjaśniam to z zespołem odpowiedzialnym za Wysyłam z Allegro. Wrócę do Ciebie z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@radz2k pracujemy nad poprawką. Dam znać po wdrożeniu.

**Comment by Maczuga** [comment]
Czyżby "poprawka" została wdrożona? Dostajemy błąd od dzisiaj przy podawaniu waluty CZK - "Waluta nie jest wspierana przez metodę dostawy".

**Comment by AureliuszBrussy** [comment]
Tak, fix został wdrożony.
