### ISSUE TITLE
Uzyskaj pełną listę zamówień produktów

### ISSUE THREAD

**Issue by ATomasRZE** [allegro/allegro-api#8246]
Próbuję uzyskać pełną listę zamówień produktów. Zamówiłem produkt na sandboxie, który tam wysłałem. Widzę zamówienie na koncie. Ale po użyciu /sale/offers pojawia się komunikat {"errors":[{"code":"AccessDenied","message":"Odmowa dostępu","details":null,"path":null,"userMessage" : „Brak dostępu do określonego zasobu.”}]}
Gdzie jest problem?

**Comment by Lukasz-Zurek** [comment]
Podaj proszę trace-id. Przyczyna może leżeć zarówno po stronie uprawnień - scope'ów, autoryzacji (w przypadku [Client_credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow) nie uzyskasz dostępu do ofert), jak i statusie konta.

**Comment by ATomasRZE** [comment]
Masz na myśli to?
220ee5912b6448079f1dc9530c92588f

**Comment by Lukasz-Zurek** [comment]
Nie, trace-id znajdziesz wśród nagłówków, w odpowiedzi na wysłane żądanie. To co przesłałeś to ClientId. Udało mi się jednak sprawdzić logi i wszystko wskazuje na to, że próbujesz uzyskać dostęp do listy ofert korzystając z tokena uzyskanego w ramach [Client_credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow). Taki token nie posiada kontekstu użytkownika, dlatego w odpowiedzi otrzymujesz kod 403. Aby prawidłowo listę ofert, skorzystaj z autoryzacji typu[ code](https://developer.allegro.pl/auth/#app) lub[ device](https://developer.allegro.pl/auth/#DeviceFlow). 

W naszej[ dokumentacji](https://developer.allegro.pl/documentation/#) znajdziesz odpowiednie oznaczenia, jakiego rodzaju autoryzacji musisz użyć, aby otrzymać prawidłową odpowiedź z danego endpointu:

- bearer-token-for-user - [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow;
- bearer-token-for-application - [client credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow);

**Comment by Lukasz-Zurek** [comment]
Z jakiej metody autoryzacji korzystałeś? Jeśli [client credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow) to przyczynę wskazałem powyżej.

Jeśli jednak korzystałeś z innej metody autoryzacji, prześlij proszę pełen request i response w formacie json. Skorzystaj w tym celu z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=2ea3623d-9fc0-4faa-8318-6fa96559c12a). W wiadomości wskaż numer wątku #8246.

**Comment by ATomasRZE** [comment]
```
public function getAllegroOffers()
    {
        $token = $this->getAccessToken();
        //$token = \Configuration::get('COFISCZ_ALLEGRO_AUTH_TOKEN');

        $headers = array("Authorization: Bearer {$token}","accept: application/vnd.allegro.public.v1+json","Content-Type: application/vnd.allegro.public.v1+json");
        $url = $this->getUrl()."/sale/offers";

        $ch = $this->getCurl($headers, $url);
        $result = curl_exec($ch);
        curl_close($ch);

        var_dump($result);
    }
```

```
public function getAccessToken(): string
    {
        if(\Configuration::get('COFISCZ_ALLEGRO_SANDBOX')) {
            $authorization = base64_encode(\Configuration::get('COFISCZ_ALLEGRO_SANDBOX_CLIENT_ID').':'.\Configuration::get('COFISCZ_ALLEGRO_SANDBOX_CLIENT_SECRET'));
            $url = \Configuration::get('COFISCZ_ALLEGRO_API_SANDBOX_URL_TOKEN');
        }else{
            $authorization = base64_encode(\Configuration::get('COFISCZ_ALLEGRO_CLIENT_ID').':'.\Configuration::get('COFISCZ_ALLEGRO_CLIENT_SECRET'));
            $url = \Configuration::get('COFISCZ_ALLEGRO_API_URL_TOKEN');
        }
        $headers = array("Authorization: Basic {$authorization}","Content-Type: application/x-www-form-urlencoded");
        $content = "grant_type=client_credentials";

        $ch = $this->getCurl($headers, $url, $content);
        $tokenResult = curl_exec($ch);
        $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        if ($tokenResult === false || $resultCode !== 200) {
            exit ("Cannot get AccessToken");
        }
        return json_decode($tokenResult)->access_token;
    }
```

Response now is:
`
{"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"No access to the specified resource."}]}`

**Comment by Lukasz-Zurek** [comment]
@ATomasRZE Używasz [client credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow). Przyczynę wskazałem wyżej, w [tym](https://github.com/allegro/allegro-api/issues/8246#issuecomment-1884923419) poście.

**Comment by ATomasRZE** [comment]
Czy możesz edytować kod, aby działał?

**Comment by ATomasRZE** [comment]
Próbowali tak jak w pierwszym przypadku, ale to nie działa w ten sposób

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę całe żądanie (z pełnymi danymi) i odpowiedź w json. Skorzystaj w tym celu z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=2ea3623d-9fc0-4faa-8318-6fa96559c12a). Powołaj się na wątek #8246.
