### ISSUE TITLE
Delivery and shipping settings

### ISSUE THREAD

**Issue by acerov** [allegro/allegro-api#8247]
Hi,

I am unable to set delivery and shipping settings in portal for allegro.pl and allegro.cz.
It is set ok only for allegro.pl, I am unable to set it for allegro.cz, I do not understand those forms.

As a consequence our offers are not accepted on allegro.cz

So my question is how to set those settings through API (or through portal)

Please share some JSON example that contain delivery prices for both allegro.pl and allegro.cz for POST on these endpoints:
sale/delivery-settings
sale/shipping-rates

Please help

**Comment by Lukasz-Zurek** [comment]
First of all you can use [GET /shipment-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getDeliveryServices) and note that we return delivery services for other marketplaces than allegro-pl, for example:

```
"marketplaces": [
                "allegro-cz"
            ],
```

Another thing is the fact that you will find the same field in the [GET /sale/delivery-methods](https://developer.allegro.pl/documentation/#operation/getListOfDeliveryMethodsUsingGET) resource. We have described it in our [tutorial](https://developer.allegro.pl/tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#jak-pobrac-ustawienia-dostawy). 

Then you can create new shipping-rates via [POST /sale/shipping-rates](https://developer.allegro.pl/documentation/#operation/createShippingRatesSetUsingPOST).
