### ISSUE TITLE
Brak produktu TecDoc

### ISSUE THREAD

**Issue by PunktAutoCzesci** [allegro/allegro-api#8248]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Cześć,
zasób` /sale/products `nie zwraca mi produktu TecDoc - czyli takiego zawierającego sekcję `tecdocSpecification`
marka: `AS-PL`
nr katalogowy: `ABE9049(NTN)`
phrase: `${marka} ${nrKatalogowy}`

Sprawdzicie dlaczego? Ten produkt powinien być w bazie TecDoc.

Dzięki

**Comment by Lukasz-Zurek** [comment]
Jeśli skorzystasz z **GET /sale/products?phrase=ABE9049(NTN)** - zwrócimy Tobie produkt `"c0995089-0045-4935-950a-01d5f6dd5e28"`. Nie wyszuka go jednak podczas wyszukiwania po obu frazach: `ABE9049(NTN)` i `AS-PL`. Tej drugiej nie ma w nazwie produktu.

Dodam, że produkt wyszukasz również po numerze katalogowym: **GET /sale/products?phrase=ABE9049(NTN)&mode=MPN**.

**Comment by PunktAutoCzesci** [comment]
Przypomnę tylko istotę mojego pytania.
Chodzi o brak produktu TecDoc

śr., 10 sty 2024, 08:53 użytkownik Lukasz-Zurek ***@***.***>
napisał:

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Produkt ten nie został ostatecznie zaimportowany z bazy TecDoc. Przyczyna mogła leżeć po stronie brakujących danych, lub błędu w bazie danych. Dokładna weryfikacja tego stanu rzeczy byłaby złożonym procesem. Mam jednak nadzieję, że przy kolejnym imporcie błąd ten zostanie poprawiony.

Serdecznie przepraszamy za te utrudnienia.

**Comment by Lukasz-Zurek** [comment]
Nie możemy udostępniać takich informacji.

**Comment by PunktAutoCzesci** [comment]
Czy mogę prosić w takim razie o informację po wgraniu?

czw., 11 sty 2024 o 08:16 Lukasz-Zurek ***@***.***>
napisał(a):

**Comment by Lukasz-Zurek** [comment]
Proces ten odbywa się całkowicie poza naszym zespołem i nie jest to kwestia dni czy tygodni. Zapisuję sobie jednak Twój wątek i jeżeli uzyskam informacje dotyczące nowego importu - dam znać w tym wątku.

**Comment by PunktAutoCzesci** [comment]
Zauważyłem, że jest BAAARDZO dużo produktów TecDoc których brakuje w bazie produktów Allegro. 
Gdzie mogę zgłaszać takie przypadki, żeby nie odbijać się od ściany?
Wydaje mi się, że nie po to Allegro płaci spore pieniądze za licencję, żeby ich baza była tak bardzo wybrakowana... 

Do tego na Allegro jest duży problem z duplikatami których też nie brakuje.

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Dziękuję za wszystkie przykłady, które przekazałem już do odpowiedniego zespołu.

**Comment by PunktAutoCzesci** [comment]
Czy jest jakaś informacja zwrotna?

**Comment by Lukasz-Zurek** [comment]
Odpowiedziałem w [tym wątku](https://github.com/allegro/allegro-api/issues/8280#issuecomment-1926406053).
