### ISSUE TITLE
Problem z edycją ogłoszenia

### ISSUE THREAD

**Issue by Hornir91** [allegro/allegro-api#8251]
Dzień dobry.

Mam problem z edycją ogłoszenia samochodu elektrycznego BMW EQE. Mianowicie, był on wystawiany poprzez stary endpoint POST /sale/offers i nie posiada przypisanej pojemności silnika w cm3.

Po przejściu na nowy endpoint PATCH sale/product-offers mam problem z jego edycją, gdyż wymagacie podania pojemności silnika jako jednego z parametrów odpowiedniej kategorii. Treść błędu poniżej.

`Parameter with ID 5 not found in the specified category 322915.\n`

Trace ID: a37a9febf88f9688

Dodam też, że testowo dodałem podobny samochód elektryczny już całkowicie poprzez nowy endpoint POST sale/product-offers i tutaj nie ma żadnych problemów, gdyż nowe auto posiada automatycznie dopisaną pojemność 1 cm3.

Prosiłbym o informację co mamy zrobić w takiej sytuacji - usunąć obecne ogłoszenie i wystawić je ponownie, czy będziecie wprowadzać jakieś poprawki po swojej stronie?

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry,

> gdyż wymagacie podania pojemności silnika jako jednego z parametrów odpowiedniej kategorii

Doprecyzuję - jest właśnie odwrotnie, taki parametr nie występuje w kategorii 322915 i na to wskazuje komunikat. Wystarczy zatem, że ze struktury `productSet.product.parameters` usuniesz ten parametr:

```
                  {
                        "id": "5",
                        "values": [
                            1
                        ]
                    }
```

Jeśli spróbujesz edytować tę ofertę przez stronę internetową (lub wystawić nową w tej kategorii), taki parametr również nie będzie wyświetlony oraz możliwy do uzupełnienia.

**Comment by Hornir91** [comment]
Teraz jak jeszcze raz przeczytałem komunikat, to faktycznie działa on w drugą stronę :D. Postaram się odfiltrować ten parametr z listy. 
Dziękuję.
