### ISSUE TITLE
Tworzenie listów przewozowych za pomocą API. Kiedy i jak stosować ? 

### ISSUE THREAD

**Issue by keczerad** [allegro/allegro-api#8254]
Chciałbym się dowiedzieć jak stosować metodę: 
[/shipment-management/shipments/create-commands]

W zasadzie wszystko na Sandboxie działa prawidłowo, jednak nie potrafię zrozumieć kiedy stosować mamy dla klientów "deliveryMethodId" a kiedy "credentialsId" ?  Skąd wziąć  "credentialsId"  ?

Dodam zę obecnie testowałem kilku przewożników na "deliveryMethodId" i wszystko działa prawidłowo.

Czytałem to:

https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#jak-dodac-numer-przesylki-do-przedmiotu-w-zamowieniu

**Comment by AureliuszBrussy** [comment]
`credentialsId` dla metody dostawy istnieje w przypadku, gdy danym użytkownik (sprzedający) dodał w Wysyłam z Allegro umowę własną. `deliveryMethodId` posługujesz się przy nadawaniu zawsze, natomiast przy nadawaniu na umowie własnej - posługujesz się dodatkowo `credentialsId`. Więcej piszemy o tym [w poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke).

`credentialsId` otrzymasz sprawdzając dostępne dla danego użytkownika usługi dostawy ([GET /shipment-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getDeliveryServices)).

**Comment by keczerad** [comment]
Jeszcze mam pytanie w metodzie [/shipment-management/delivery-services] mamy dostępną opcję ubezpieczenia, czy jeżeli w tejze metodzie dostawy mamy ubezpieczenie np do 500 zlotych to mozemy z takeigo ubezpeiczenia skorzystać bez dodatkowych opłat ?  Zakładajac mamy towar za 100 zlotych to w ramcha oplaty i tegoż ubezpieczenia za 500 my przy zakladaniu listu mozemy podać ze ubezpieczamy za 100 i jest to bez oplat ?

**Comment by AureliuszBrussy** [comment]
To już jest kwestia indywidualnych własności konkretnych usług dostawy. Więcej o usługach dostawy znajdziesz w [pomocy Allegro](https://allegro.pl/dla-sprzedajacych/dostawa). Jeżeli masz jakieś dodatkowe pytania dot. samych usług dostaw, skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt).

**Comment by keczerad** [comment]
Podczas kreowanie przesyłki przez UI jest coś takiego:
![image](https://github.com/allegro/allegro-api/assets/22832921/06f42269-636b-4274-b6c1-432127a2416c)
czy my w API mamy możliwość pobrania tych wartości z usług odstawy jezeli chodzi o Rodzaj przesyłki (Paczka, koperta)  oraz wymiary i paczki (Gabarys S, Gabaryt M, Gabaryt L) ? Takzeby też dać uzytkownikom możliwość wyboru ?

**Comment by AureliuszBrussy** [comment]
Nie udostępniamy takich danych w API - tutaj pozostaje samodzielna implementacja.

**Comment by AureliuszBrussy** [comment]
Dziękuję za Twoją sugestię, najlepiej jak zgłosisz ją w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions), gdzie zbieramy wszystkie propozycje społeczności. 

Grupa gabarytowa determinowana jest w InPoście automatycznie na podstawie przesłanych wymiarów przesyłki.

**Comment by keczerad** [comment]
Czy w orlenie, poczcie polskie itp też tak jest ?

**Comment by AureliuszBrussy** [comment]
Tak.
