### ISSUE TITLE
Problem z frazą w metodzie GET /sale/products

### ISSUE THREAD

**Issue by TomaszPabianItPiast** [allegro/allegro-api#8255]
Dzień dobry, dzisiaj zauważyłem problem z pobieraniem informacji o towarze poprzez metodę GET /sale/products jeśli we frazie podam "MEYLE 30-26 725 0009".

Bez białych znaków działa ale nie zwraca poszukiwanego amortyzatora.

**Comment by AureliuszBrussy** [comment]
Potwierdzam ten błąd dla tego produktu. Jestem w trakcie wyjaśniania tego przypadku. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@TomaszPabianItPiast poprawiliśmy ten produkt.

**Comment by AureliuszBrussy** [comment]
Poprawialiśmy to globalnie, natomiast wygląda na to, że nie rozwiązaliśmy tego problemu w 100%. Zgłosiłem to do odpowiedniego zespołu. Wrócę z informacją.

**Comment by TomaszPabianItPiast** [comment]
Witam, czy problem został namierzony i poprawiony globalnie?

**Comment by AureliuszBrussy** [comment]
Wciąż nie wykluczyliśmy takich przypadków w 100% - mogą się one zdarzyć. Monitorujemy to i staramy się na bieżąco eliminować takie błędy w produktach. Sprawa jest technicznie skomplikowana i pracujemy też nad całkowitym uniknięciem takich przypadków.

**Comment by TomaszPabianItPiast** [comment]
nowa porcja fraz dla których dostaję błąd
MAXGEAR 23-0036
MAXGEAR 23-0139
MAXGEAR 23-0050
MAXGEAR 23-0058
MAXGEAR 24-0269
MAXGEAR 24-0072
MAXGEAR 24-0149
MAXGEAR 24-0113
MAXGEAR 24-0060
MAXGEAR 24-0233
MAXGEAR 27-1306
MAXGEAR 27-1290
MAXGEAR 27-1286
MAXGEAR 27-1272
MAXGEAR 27-1279
MAXGEAR 27-1280

**Comment by AureliuszBrussy** [comment]
@TomaszPabianItPiast dziękuję, zgłaszam je do odpowiedniego zespołu.

**Comment by TomaszPabianItPiast** [comment]
MAXGEAR 21-0194
MAXGEAR 19-0828
MAXGEAR 19-2857
TRW GDB1517
KK-21078

**Comment by PZuba** [comment]
Dzień dobry,
Nasz Klient nadal zgłasza problemy - proszę o informację jaki jest status zadania po Państwa stronie.

Poniżej kilka przykładowych towarów. Proszę o naprawę.
MGZ-103041
19-2207
19-2256
AC219100

**Comment by AureliuszBrussy** [comment]
@PZuba dziękuję za zgłoszenie, przekazałem te przykłady do zespołu odpowiedzianego za poprawę, możesz spodziewać się, że zostaną uspójnione. Zaadresowaliśmy ten problem i wyeliminowaliśmy znaczną większość takich przypadków, jednakże dla niektórych corner case'ów wciąż takie produktu się pojawiają - staramy się to regularnie poprawiać.
