### ISSUE TITLE
Limits imposed on queries and number of sessions in the Allegro API

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#8258]
Hi there, 

we have a question regarding this topic: 
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/af574e50-6376-47d2-b28f-775fba4fa438)

We have an app that is helping clients to list and update offers on Allegro via API. Does it mean that for our whole app we have the limit of  9000 requests per minute? Even if we would have hundreds of clients, we still have a rate limit capped at 9000 requests per minute?

Thank you in advance! 

All the best, 

Dominika

**Comment by Lukasz-Zurek** [comment]
Yes, indeed. The current limit value (9000 req/min) is determined on the basis of the data we have. While optimizing the functioning of the application, it allows users to operate correctly (in accordance with the limit).
