### ISSUE TITLE
415 when uploading valid image in Sandbox

### ISSUE THREAD

**Issue by sellosebastian** [allegro/allegro-api#826]
Most image uploads work just fine but sometimes I get a 415 NotSupportedException. 
I can't find anything wrong with the image I'm trying to upload. 

Trace-ID for an upload that fails: b817bfa09c97b6de

Any ideas on what might be wrong?

**Comment by PawelTaberski** [comment]
You are sure that you have good headers for the given photo format:
'content-type: "image/jpeg", or "image/png", or "image/gif”?
More about that you can find [here](https://developer.allegro.pl/en/sale/#step-3-images).

**Comment by sellosebastian** [comment]
I'm sure I have good headers. 9 out of 10 images upload just fine.

**Comment by sellosebastian** [comment]
Same problem in production environment. 
Trace-ID for failed upload in production: 68cd6301027ae908

**Comment by PawelTaberski** [comment]
But all the photos have the same format? Every time you have problem with the same photo or different? What is the response status?

**Comment by sellosebastian** [comment]
Yes, all images are jpg's. 
I get this response: '415 - "{\\"errors\\":[{\\"code\\":\\"NotSupportedException\\",\\"message\\":\\"An error has occurred\\",\\"details\\":null,\\"path\\":null,\\"userMessage\\":\\"An error occurred\\"}]}"'. 

But as far as I can tell there is nothing wrong with the image I'm uploading.

**Comment by PawelTaberski** [comment]
Status 415 mean that you have incorrect image type. Can you try to edit this image and save it as jpg, and try to send it, again?
Remember that in headers you should have image/jpeg not jpg.

**Comment by sellosebastian** [comment]
I have tried editing the image and uploading it again. Still no luck. 
I have image/jpeg in my header.

**Comment by PawelTaberski** [comment]
Very weird, please send us a full cURL, response for Trace-ID: 68cd6301027ae908 and image with which you have a problem. Send this information via our [contact form](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619), and mark that information are needed for ticket 826 on GitHub.

**Comment by sellosebastian** [comment]
I've sent the requested information. Hope it helps.

**Comment by PawelTaberski** [comment]
As soon as I get the information I will check what the problem is, please be patient

**Comment by PawelTaberski** [comment]
I still waiting for data but in logs we see that in headers you have image/jpg - you should have as I say before image/**jpeg**

**Comment by PawelTaberski** [comment]
Please send newest trace-id in which you are sure you have good header.

**Comment by sellosebastian** [comment]
Trace-ID: 1725d37663feb998

**Comment by PawelTaberski** [comment]
Once more in logs we see header image/jpg. You must overwrite this header when you send a request. This must be the problem. Maybe you overwrite this header with image format that you send?
