### ISSUE TITLE
ProductNotFoundException

### ISSUE THREAD

**Issue by PiotrPiotrP** [allegro/allegro-api#8261]
Przy próbie edycji dostaje błąd, ProductNotFoundException Product not found for the specified ID. Tuż przed edycją pobrałem ofertę z produktem i wychodzi że jest. Co tu jest źle?

01/12 10:34:37.951   GET    https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/7741669630 requestBody= responseStatusCode=200 responseBody={"name":"SPODNIE JEANSY DAMSKIE 34 AAM","productSet":[{"product":{"id":"a3f5258e-5011-4165-99c2-b7aab66fb607","publication":{"status":"LISTED"},"parameters":[{"id":"204501","name":"Zapięcie","values":["zapięcie z przodu"],"valuesIds":["204501_221217"],"rangeValue":null},{"id":"225693","name":"EAN (GTIN)","values":["7759556909277"],"valuesIds":null,"rangeValue":null},{"id":"215534","name":"Rodzaj","values":["dół"],"valuesIds":["215534_270226"],"rangeValue":null},{"id":"3946","name":"Marka","values":["adidas"],"valuesIds":["3946_218533"],"rangeValue":null},{"id":"201017","name":"Materiał dominujący","values":["jedwab"],"valuesIds":["201017_2361"],"rangeValue":null},{"id":"249512","name":"Kolor","values":["czarny"],"valuesIds":["249512_1647413"],"rangeValue":null},{"id":"15851","name":"Płeć","values":["Produkt damski"],"valuesIds":["15851_1"],"rangeValue":null},{"id":"249418","name":"Rozmiar majtek","values":["116-128"],"valuesIds":["249418_1217386"],"rangeValue":null},{"id":"3766","name":"Wzór dominujący","values":["print (nadruk)"],"valuesIds":["3766_218065"],"rangeValue":null},{"id":"205646","name":"Cechy dodatkowe","values":["brak","ochrona UV","odpinane ramiączka"],"valuesIds":["205646_1048576","205646_1","205646_256"],"rangeValue":null}]},"quantity":{"value":1}}],"parameters":[{"id":"11323","name":"Stan","values":["Nowy"],"valuesIds":["11323_1"],"rangeValue":null}],"images":["https://a.allegroimg.allegrosandbox.pl/original/1159ee/5218248449c48ac88e5404cfcd4d","https://a.allegroimg.allegrosandbox.pl/original/11ea1b/e592a869451aaf0f3c01ac969d95","https://a.allegroimg.allegrosandbox.pl/original/11099a/06ffce404951b1889e4b1bc681c5"],"afterSalesServices":{"impliedWarranty":{"id":"55f17cad-3715-49e3-979a-4db15c2ba5c0"},"returnPolicy":{"id":"a0abdc6a-74f5-4d2f-accf-3179d36f16ea"},"warranty":null},"payments":{"invoice":"NO_INVOICE"},"sellingMode":{"format":"AUCTION","price":{"amount":"55.99","currency":"PLN"},"startingPrice":{"amount":"44.99","currency":"PLN"},"minimalPrice":null},"stock":{"available":1,"unit":"UNIT"},"location":{"countryCode":"PL","province":"MALOPOLSKIE","city":"Skawina","postCode":"32-050"},"delivery":{"shippingRates":{"id":"46d946ca-b1c9-43e4-8c02-4aed1eb99911"},"handlingTime":"PT24H","additionalInfo":null,"shipmentDate":null},"description":{"sections":[{"items":[{"type":"TEXT","content":"<h2>SPODNIE JEANSY DAMSKIE</h2>"}]},{"items":[{"type":"TEXT","content":"<h2>Opis Produktu</h2><ul><li><b>Marka</b> Pull&amp;Bear</li><li><b>Kolor</b> Blue</li><li><b>Skład</b> 32</li><li><b>Metka papierowa</b> Produkt posiada metki papierowe.</li><li><b>Metka wewnętrzna</b> Produkt posiada metki wewnętrzne.</li><li><b>Rozmiar</b> 34</li><li><b>Cena katalogowa</b> 99,99 zł</li></ul>"},{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/11099a/06ffce404951b1889e4b1bc681c5"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/1159ee/5218248449c48ac88e5404cfcd4d"},{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/11ea1b/e592a869451aaf0f3c01ac969d95"}]}]},"external":{"id":"stocksell_269164167"},"category":{"id":"76024"},"tax":null,"taxSettings":{"subject":null,"exemption":null,"rates":[]},"sizeTable":null,"discounts":{"wholesalePriceList":null},"contact":null,"fundraisingCampaign":null,"messageToSellerSettings":null,"attachments":[],"b2b":null,"additionalServices":null,"compatibilityList":null,"additionalMarketplaces":{"allegro-cz":{"sellingMode":null,"publication":{"state":"NOT_REQUESTED","refusalReasons":[]}},"allegro-sk":{"sellingMode":null,"publication":{"state":"NOT_REQUESTED","refusalReasons":[]}}},"id":"7741669630","language":"pl-PL","publication":{"status":"ACTIVE","duration":"PT120H","endedBy":null,"endingAt":"2024-01-14T11:40:00.000Z","startingAt":null,"republish":true,"marketplaces":{"base":{"id":"allegro-pl"},"additional":[]}},"validation":{"errors":[],"warnings":[],"validatedAt":"2024-01-12T09:34:37.945Z"},"createdAt":"2024-01-09T11:40:03.000Z","updatedAt":"2024-01-09T11:40:03.832Z"} trace-id=[2f8f7a375629d6cd] 

01/12 10:34:38.169 PATCH  https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/7741669630 requestBody={"id":"7741669630","productSet":[{"quantity":{"value":1},"product":{"name":"SPODNIE JEANSY DAMSKIE 34 AAM","idType":"GTIN","parameters":[{"id":"3766","valuesIds":["3766_218065"]},{"id":"15851","valuesIds":["15851_1"]},{"id":"201017","valuesIds":["201017_2361"]},{"id":"205646","valuesIds":["205646_1048576","205646_1","205646_256"]},{"id":"215534","valuesIds":["215534_270226"]},{"id":"249418","valuesIds":["249418_1217386"]},{"id":"225693","values":["7759556909277"]},{"id":"3946","valuesIds":["3946_218533"]},{"id":"204501","valuesIds":["204501_221217"]},{"id":"249512","valuesIds":["249512_1647413"]}],"category":{"id":"76024"},"images":["https://images.stocksell.io/images/4f/4fcfcb8a-9ced-40e9-bd14-4bc6f63e8e4f","https://images.stocksell.io/images/37/37ffdd77-0a53-4e8f-be73-5eda9ad36a09","https://images.stocksell.io/images/9b/9bc63215-7936-4877-8c69-c120fe66e113"]}}],"category":{"id":"76024"},"delivery":{"shippingRates":{"id":"46d946ca-b1c9-43e4-8c02-4aed1eb99911"},"handlingTime":"PT24H"},"publication":{"duration":"PT120H","endingAt":"2024-01-14T11:40:00.000Z","marketplaces":{"base":{"id":"allegro-pl"},"additional":[]},"status":"ACTIVE","republish":true},"language":"pl-PL","afterSalesServices":{"impliedWarranty":{"id":"55f17cad-3715-49e3-979a-4db15c2ba5c0"},"returnPolicy":{"id":"a0abdc6a-74f5-4d2f-accf-3179d36f16ea"}},"stock":{"available":1,"unit":"UNIT"},"parameters":[{"id":"11323","valuesIds":["11323_1"]}],"name":"SPODNIE JEANSY DAMSKIE 34 AAM","payments":{"invoice":"NO_INVOICE"},"sellingMode":{"format":"AUCTION","price":{"amount":55.99,"currency":"PLN"},"startingPrice":{"amount":44.99,"currency":"PLN"}},"location":{"city":"Skawina","countryCode":"PL","postCode":"32-050","province":"MALOPOLSKIE"},"images":["https://images.stocksell.io/images/4f/4fcfcb8a-9ced-40e9-bd14-4bc6f63e8e4f","https://images.stocksell.io/images/37/37ffdd77-0a53-4e8f-be73-5eda9ad36a09","https://images.stocksell.io/images/9b/9bc63215-7936-4877-8c69-c120fe66e113"],"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003ch2\u003eSPODNIE JEANSY DAMSKIE\u003c/h2\u003e"}]},{"items":[{"type":"IMAGE","url":"https://images.stocksell.io/images/4f/4fcfcb8a-9ced-40e9-bd14-4bc6f63e8e4f"},{"type":"TEXT","content":"\u003ch2\u003eOpis Produktu\u003c/h2\u003e\u003cul\u003e\u003cli\u003e\u003cb\u003eMarka\u003c/b\u003e Pull\u0026amp;Bear\u003c/li\u003e\u003cli\u003e\u003cb\u003eKolor\u003c/b\u003e Blue\u003c/li\u003e\u003cli\u003e\u003cb\u003eSkład\u003c/b\u003e 32\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka papierowa\u003c/b\u003e Produkt posiada metki papierowe.\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka wewnętrzna\u003c/b\u003e Produkt posiada metki wewnętrzne.\u003c/li\u003e\u003cli\u003e\u003cb\u003eRozmiar\u003c/b\u003e 34\u003c/li\u003e\u003cli\u003e\u003cb\u003eCena katalogowa\u003c/b\u003e 99,99 zł\u003c/li\u003e\u003c/ul\u003e"}]},{"items":[{"type":"IMAGE","url":"https://images.stocksell.io/images/37/37ffdd77-0a53-4e8f-be73-5eda9ad36a09"},{"type":"IMAGE","url":"https://images.stocksell.io/images/9b/9bc63215-7936-4877-8c69-c120fe66e113"}]}]},"external":{"id":"stocksell_269164167"},"taxSettings":{"rates":[{"countryCode":"PL"}]}} exception=Niepoprawna odpowiedź z Allegro. Kod: 422. Błąd: ProductNotFoundException Product not found for the specified ID. Unprocessable Entity productSet[0].product. Trace-id=[eca7a4aa9c4c2bc8].

**Comment by PrzemyslawLukanowski** [comment]
Ten produkt został w międzyczasie (04.01.2024 o 10:36) usunięty z naszej bazy przez nasz wewnętrzny mechanizm ze względu na brak wszystkich parametrów. Wygląda na to, że w momencie utworzenia produkt nie posiadał numeru GTIN. 
Ta operacja nie powoduje automatycznego usunięcia produktu z oferty, jednak jeśli odpytasz GET /sale/products/a3f5258e-5011-4165-99c2-b7aab66fb607, to otrzymasz w odpowiedzi status `404 Not Found`.

**Comment by PiotrPiotrP** [comment]
To jest marka Shein i z tego co pisałem z wami tutaj https://github.com/allegro/allegro-api/issues/7942#issuecomment-1888289724 wychodziło że EAN nie jest obowiązkowy.

**Comment by PrzemyslawLukanowski** [comment]
Ten konkretny produkt według naszych danych posiadał uzupełnioną markę jako "Adidas".

**Comment by PiotrPiotrP** [comment]
Dziękuję, to jakiś błąd po naszej stronie.
