### ISSUE TITLE
Automatyczna autoryzacja do konkretnego konta Allegro

### ISSUE THREAD

**Issue by Devvnul** [allegro/allegro-api#8263]
Witam, mam takie pytanie. Czy z dostępnych metod autoryzacji, któraś z nich pozwala na automatyczną autoryzację do Allegro API, kompletnie bez ingerencji użytkownika? Chodzi o aplikację webową i chciałbym to rozegrać w taki sposób, żeby wszystko się działo pod maską i kiedy użytkownik zaloguje się do mojej apki, będzie mógł od razu używać funkcji typu dodaj ofertę itp.

**Comment by AureliuszBrussy** [comment]
Każda metoda autoryzacji wymaga (przynajmniej przy pierwszym uwierzytelnianiu) interakcje ze strony użytkownika - czyli wyrażenie zgody na działanie aplikacji w jego imieniu. 

Po uzyskaniu pierwszej pary access i refresh token - możesz korzystać z [możliwości odświeżania tokena](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena), dzięki czemu unikniesz kolejnych interakcji użytkownika.

**Comment by Devvnul** [comment]
Rozumiem, dziękuję za rozwianie wątpliwości :)
