### ISSUE TITLE
Pobieranie prowizji dla wyróżnionych

### ISSUE THREAD

**Issue by Skuller97** [allegro/allegro-api#8264]
Dzień dobry, 
korzystam z endpointu: /sale/product-offers/{offerId}
następnie chcę pobrać koszty prowizji z endpointu: /pricing/offer-fee-preview 

natomiast z pierwszego endpointu nie otrzymuje informacji na temat:
       "promotion": {
            "emphasized": true,
            "bold": false,
            "highlight": false,
            "departmentPage": false,
            "emphasizedHighlightBoldPackage": false
        },
        
        w jaki sposób mam uzyskać te dane dla każdego rodzaju oferty, niezależnie czy aktywna, czy zakończona?

**Comment by Skuller97** [comment]
@AureliuszBrussy

**Comment by AureliuszBrussy** [comment]
Wraz z wyłączeniem endpointów do tworzenia i edycji ofert ze ścieżek /sale/offers - taka metoda promowania ofert (przez ustawianie flag w strukturze oferty) przestała być przez nas wspierana. Aktualnie wspieramy promowanie poprzez [dedykowane zasoby](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-pobrac-dostepne-opcje-promowania).  Niebawem zaproponujemy nowe metody kalkulowania opłat. Wszelkie zmiany będziemy oczywiście komunikować.
