### ISSUE TITLE
GET /fulfillment/stock

### ISSUE THREAD

**Issue by Marcel10S** [allegro/allegro-api#8265]
Czy aby korzystać z zasobu /fulfillment/stock potrzebuję jakiejś subskrybcji? 
Korzystam na środowisku sandbox i przy próbie strzału na dany endpoint dostaję informację o braku subskrybcji.
Upewniłem się, że moje konto na dostęp do allegro:api:fulfillment:read

Treść błędu:
{
    "errors": [
        {
            "code": "ACCESS_TO_FULFILLMENT_FORBIDDEN",
            "message": "Access for seller 106172899 is forbidden",
            "details": null,
            "path": "/fulfillment/stock",
            "userMessage": "Nieaktywny status subskrypcji"
        }
    ]
}

**Comment by AureliuszBrussy** [comment]
Konto musi być odpowiednio oznaczone (jako konto Fulfillment), abyś miał dostęp do zasobów związanych z Allegro One Fulfillment. 

W związku z tym, że musi być to konto czyste konto, które nie ma wystawionych żadnych ofert, [zarejestruj nowe konto firma](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F). Gdy to zrobisz - daj znać (podaj login), oznaczymy to konto odpowiednim statusem.
