### ISSUE TITLE
Problem z pobraniem /parcel-management/parcels/label

### ISSUE THREAD

**Issue by kkeiichi** [allegro/allegro-api#8266]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Mam problem z pobraniem etykiety na paczkę poprzez API. W momencie pobierania etykiety za pomocą żądania:

```
GET /parcel-management/parcels/label?parcelId=55353e63-7f61-4d7e-a386-40c990d82da0&pageFormat=A6 HTTP/1.1
Host: api.allegro.pl
Accept: application/pdf
Authorization: Bearer …
```
otrzymuję za każdym razem błąd 400 Bad Request z zawartością:
```
{
    "errors": [
        {
            "code": "ANOTHER_SERVICE_NOT_AVAILABLE",
            "message": "One of required services is unavailable. Try again later.",
            "details": "One of required services is unavailable. Try again later.",
            "path": null,
            "userMessage": "Jeden z wymaganych serwisów, do poprawnego działania, jest niedostępny. Spróbuj ponownie za moment."
        }
    ]
}
```

Błąd aktualnie dotyczy jedynie tej jednaj paczki 55353e63-7f61-4d7e-a386-40c990d82da0. Inne rejestrują się bez problemu i mogę także pobrać dla nich etykietę.

Środowisko: produkcja
Konto, na rzecz którego wykonywana jest akcja: TRUDI_Sklep
Problem pojawia się przy każdej próbie. Występuje nieprzerwanie od 11 stycznia od około 13.00.
TraceId: 823c31759540e923

**Comment by PrzemyslawLukanowski** [comment]
Problem był związany z ustawieniami danego konta - nie powinien już występować. Przepraszam za niedogodności.

**Comment by kkeiichi** [comment]
Kolejny raz mam identyczny problem, jak w początkowym zgłoszeniu. Próba pobrania przygotowanej etykiety do paczki:
`
GET /parcel-management/parcels/label?parcelId=9c8ab848-6a1f-4835-96e3-f7551a8458fa&pageFormat=A6 HTTP/1.1
Host: api.allegro.pl
Accept: application/pdf
Authorization: Bearer …
`
kończy się znów otrzymaniem błędu 400 Bad Request:
`
{
    "errors": [
        {
            "code": "ANOTHER_SERVICE_NOT_AVAILABLE",
            "message": "One of required services is unavailable. Try again later.",
            "details": "One of required services is unavailable. Try again later.",
            "path": null,
            "userMessage": "Jeden z wymaganych serwisów, do poprawnego działania, jest niedostępny. Spróbuj ponownie za moment."
        }
    ]
}
`

Błąd dotyczy tej jednaj paczki 9c8ab848-6a1f-4835-96e3-f7551a8458fa.

Środowisko: produkcja
Konto, na rzecz którego wykonywana jest akcja: CubicFun_Sklep
Problem pojawia się przy każdej próbie.
TraceId: f71a3b76b78e0585

Obecnie problem dotyczy innego konta niż poprzednio. Tydzień temu odpisaliście, że problem był w ustawieniach konta. Ja w ten sam sposób obsługuję kilkanaście kont Allegro. Czy to znaczy, że we wszystkich trzeba skontrolować jakieś ustawienie, które powoduje występowanie tego błędu?

**Comment by MartaNowaczyk** [comment]
Na tym koncie też był ten sam problem co wcześniej - za co przepraszamy. Pracujemy nad tym, by wszystkie konta z tym problemem były poprawione, aby nie było trzeba ich zgłaszać.

**Comment by kkeiichi** [comment]
To niestety mam kolejny przypadek, tym razem znów w kontekście konta z pierwszego zgłoszenia, którego ustawienia były korygowane: TRUDI_Sklep.

Wywołanie:
```
GET /parcel-management/parcels/label?parcelId=26c302b2-c84e-4502-b0bc-1afee7d8f010&pageFormat=A6 HTTP/1.1
Host: api.allegro.pl
Accept: application/pdf
Authorization: Bearer …
```
znów kończy się otrzymaniem błędu 400 Bad Request. Odpowiedzi nie przytaczam, jest identyczna, jak wcześniej.

Błąd dotyczy obecnie paczki 26c302b2-c84e-4502-b0bc-1afee7d8f010.

Środowisko: produkcja
Konto, na rzecz którego wykonywana jest akcja: TRUDI_Sklep
Problem pojawia się przy każdej próbie.
TraceId: 861be2ad81503990

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za szczegółowe dane. Potwierdzam problem po naszej stronie, wrócę z informacją, gdy uda się go rozwiązać.

**Comment by PrzemyslawLukanowski** [comment]
Spróbuj ponownie nadać paczkę. Jeśli mimo wszystko błąd nadal się powtórzy, daj proszę znać w wątku.

**Comment by kkeiichi** [comment]
Niestety nadal bez zmian. Błąd ten sam.
Nowoprzydzielona paczka: 85a0ff60-0b9f-4f71-84c7-1cc822937911
TraceId przy pobieraniu etykiety: aef00ca69bb4dd6d

**Comment by PrzemyslawLukanowski** [comment]
Chciałbym dopytać jeszcze o proces tworzenia konta - czy zgodnie z instrukcją tworzysz konto przez wejście na ustawienia Wysyłam z Allegro?

**Comment by kkeiichi** [comment]
Chodzi o konto, z którego nastąpiła sprzedaż, czy konto, na którym zarejestrowana jest aplikacja?
Ja jedynie zarządzam kontem, które ma zarejestrowaną aplikację w panelu pod adresem https://apps.developer.allegro.pl/ Aplikacja wymaga uprawnień allegro:api:shipments:read i allegro:api:shipments:write.
Konta, z których następuje sprzedaż, są kontami klientów, do których dostępu nie posiadam i nie wiem jak były utworzone. Konta klientów mają powiązaną aplikację, która korzysta z API w celu rejestracji przesyłek i generowania etykiet adresowych.
Chętnie dopytam klientów o sposób w jaki tworzyli konto i czy wykonali punkty z instrukcji. Czy mogę prosić o wskazanie o jaką instrukcję chodzi? Czy chodzi o ustawienia w https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia?

**Comment by PrzemyslawLukanowski** [comment]
Chodzi o konto sprzedawcy, do którego należy zamówienie. 

Tak, poproszę, aby ten użytkownik, dla którego występuje problem, wszedł na stronę https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia i wszedł np. w "Wydruk etykiet - Wysyłam z Allegro" i to powinno wystarczyć - ustawienia konta powinny się utworzyć.

**Comment by PrzemyslawLukanowski** [comment]
Doprecyzuję, że chodzi dokładnie o ten fragment instrukcji:

<img width="585" alt="Zrzut ekranu 2024-01-25 o 14 56 07" src="https://github.com/allegro/allegro-api/assets/51473661/752133e2-aa60-4842-bdfd-2c3e9491bfc6">
 
Prosiłbym także, abyś jako twórca aplikacji, również wykonał krok opisany w pierwszym podpunkcie.

**Comment by kkeiichi** [comment]
Dziękuję za pomoc i wskazanie o co dokładnie chodzi. Skontaktuję się z Klientami i skontroluję ustawienia.
Na koncie, na którym zarejestrowana jest aplikacja, także wykonam te same działania.
