### ISSUE TITLE
Problem z utworzeniem aplikacji 

### ISSUE THREAD

**Issue by Dekorlux** [allegro/allegro-api#8267]
Witam 

Chce powiązać konto allegro z fakturowania i dlatego potrzebuje zarejestrować aplikacje i pobrać klucze API, ale przy rejestracji mam ciągle błąd nazwa już istnieje aplikacji, chociaż ciągle zmieniam nadal to samo, a nie mam na koncie żadnej aplikacji zarejestrowanej.

**Comment by PrzemyslawLukanowski** [comment]
Nazwa musi być unikalna w kontekście całego Allegro. Musisz użyć takiej, która nie została jeszcze zarejestrowana przez żadnego użytkownika.
