### ISSUE TITLE
Allegro sandbox aktywacja konta

### ISSUE THREAD

**Issue by francus11** [allegro/allegro-api#8269]
Chcę dodać aplikację do allegro sandbox. Utworzyłem konto na email adriandevaccess@gmail.com. Jednak nie mogę dokończyć rejestracji ponieważ konto nie jest aktywowane i prosi o zrobienie przelewu, którego nie da się zrobić

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto. Jeśli jednak chciałbyś wystawiać i zarządzać ofertami za pomocą API, będziesz potrzebować konta firmowego. W takim przypadku możesz zmienić rodzaj aktualnego konta lub utworzyć nowe (a wtedy to może Ci posłużyć jako drugie konto, kupującego).

**Comment by pawel-rochowiak** [comment]
WItam. Ja również chciałbym prosić o aktywację kont. 
Chodzi o dwa zwykłe konta z loginami TalarNU1,TalarNU2. Nie mogę dokonac testowego zakupu.
oraz o konto firmowe z loginem Fragment.

Z góry dziękuję za pomoc.

**Comment by MartaNowaczyk** [comment]
@pawel-rochowiak dla kont zwykłych uzupełnij podstawowe dane takie jak adres itp. 
Na koncie firmowym "Fragment" masz wybraną niepełną opcję sprzedażową. Wejdź proszę do [ustawień konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy), skorzystaj z linku, który masz na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)" i wybierz "Weryfikacja pełna". Uzupełnij dane i prześlij dowolne pliki, abym mogła aktywować to konto.

**Comment by MartaNowaczyk** [comment]
Na koncie TalarNU2 nie uzupełniłeś danych. Na sandboxie nie wysyłamy smsów, stąd weryfikacja telefonu nie jest możliwa, ale też nie jest wymagana. 
Konta TalarNU1 i Fragment aktywowałam.

**Comment by MartaNowaczyk** [comment]
Nie ma sprawy, ludzka rzecz :) 
Teraz jest ok, aktywowałam.

**Comment by ryszardlet** [comment]
O ile to możliwe to również prosiłbym o aktywację konta o loginie hummerce w sandboxie. Niestety nie mogę dodać aplikacji (z powodu problemów z weryfikacją konta). Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
@ryszardlet Aktywowałem wskazane przez Ciebie konto.

**Comment by Tanioagd** [comment]
Witam. Ja również chciałabym prosić o aktywację kont.
Chodzi o konta firmowe z loginami tanioagd, TragarSklep 

Z góry dziękuję za pomoc.

**Comment by MartaNowaczyk** [comment]
Witam, widzę tylko konto "tanioagd", gdzie masz wybraną niepełną opcję sprzedażową. Wejdź do [ustawień konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy), skorzystaj z linku, który masz na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)" i wybierz "Weryfikacja pełna". Uzupełnij dane i prześlij dowolne pliki, abym mogła aktywować to konto.

Sprawdź czy dla tego drugiego konta "TragarSklep" podałeś prawidłową nazwę, bo nie widzę go na sandboxie, jest tylko na produkcji.

**Comment by Tanioagd** [comment]
Próbuję zrobić pełna weryfikację jednak wychodzi mi informacja:  Nie mogliśmy wysłać formularza. Proszę spróbuj ponownie

**Comment by MartaNowaczyk** [comment]
Czy problem się powtarza i czy próbowałeś w różnych przeglądarkach? Podeślij proszę zrzut z tym błędem.

**Comment by Tanioagd** [comment]
Tak próbowałam w innej przeglądarce i ten sam błąd
![weryfikacja allegro](https://github.com/allegro/allegro-api/assets/155977034/60928597-27ea-41fa-8e0f-6d058bdb4b2c)

**Comment by MartaNowaczyk** [comment]
Czy wszystkie wymagane pola były wypełnione?

**Comment by Tanioagd** [comment]
Tak, ale jak zatwierdzam wysłanie to wychodzi też napis to pole jest wymagane przy nr PESEL. 
![pole jest wymagane ](https://github.com/allegro/allegro-api/assets/155977034/989a3b36-237e-4264-81d3-f6cc7840e1dc)

**Comment by MartaNowaczyk** [comment]
Błędu nie widzę po naszej stronie, bo przetestowałam to przed chwilą. Wpisz proszę PESEL, bo jest wymagany i powinno przejść. Skorzystaj z jakiegoś generatora fikcyjnych danych.

**Comment by MartaNowaczyk** [comment]
Tak, to była druga opcja z której można było skorzystać. W każdym razie aktywowałam twoje konto.

**Comment by Tanioagd** [comment]
Proszę o aktywację jeszcze jednego: TragarSklep

**Comment by MartaNowaczyk** [comment]
To konto ma wybraną niepełną opcję sprzedażową, także powtórz kroki, które wykonałeś dla konta "tanioagd".

**Comment by Tanioagd** [comment]
Kroki powtórzone. Powinno być ok, więc proszę o aktywację.

**Comment by MartaNowaczyk** [comment]
@Tanioagd coś się zmieniło, ale wcześniej anulowałeś proces i niestety teraz jest tak namieszane, że lepiej i szybciej będzie jak założysz nowe konto - od razu firmowe i wybierzesz pełną aktywację.

**Comment by Tanioagd** [comment]
Konto założone: SklepTragar. Proszę o aktywację

**Comment by enzonzee** [comment]
Poproszę o aktywację kont: BigBadWoof oraz wawrzyniak.marcin89@gmail.com
Czy można wystawiać oferty na 'zwykłych' kontach?

**Comment by MartaNowaczyk** [comment]
@Tanioagd Aktywowałam konto SklepTragar

**Comment by MartaNowaczyk** [comment]
@enzonzee na koncie BigBadWoof masz wybraną niepełną opcję sprzedażową. Wejdź do [ustawień konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy), skorzystaj z linku, który masz na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)" i wybierz "Weryfikacja pełna". Uzupełnij dane i prześlij dowolne pliki, abym mogła aktywować to konto.

Oferty wystawisz tylko na koncie firmowym. Konto zwykłe wawrzyniak.marcin89@gmail.com jest już aktywne.

**Comment by Tanioagd** [comment]
Dziękuję za aktywację konta SklepTragar. Chciałabym jeszcze powiązać te dwa konta. Głowne ma być tanioagd

**Comment by enzonzee** [comment]
@MartaNowaczyk dziękuje.
Konto BigBadWoof uzupełnione.
Czyli osoba prywatna bez firmy nie może wystawiać i zarządzać ofertami przez API?

**Comment by MartaNowaczyk** [comment]
@Tanioagd [tutaj](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/powiazane-konta) powinieneś mieć taką możliwość.

**Comment by MartaNowaczyk** [comment]
@enzonzee aktywowałam konto BigBadWoof. 
Bez konta firmowego nie można sprzedawać i wystawiać, niezależnie czy to API czy UI. Nie trzeba mieć konta firmowego by zarządzać aplikacjami i mieć dostęp do API.

**Comment by Tanioagd** [comment]
A muszę kupować abonament??? 
![Zrzut ekranu 2024-01-22 132522](https://github.com/allegro/allegro-api/assets/155977034/60087e2c-a4f5-4abb-a4f3-8996ef3b29f1)

**Comment by MartaNowaczyk** [comment]
@Tanioagd Opcja ta dostępna jest tylko z abonamentem. Na sandbox to nie problem, bo rachunki opłacasz symulatorem płatności, nie ma realnych opłat.

**Comment by enzonzee** [comment]
Czy konto firmowe moze posiadać osoba, która działa na działalności nierejestrowanej?

**Comment by MartaNowaczyk** [comment]
@enzonzee nie jest to kwestia API, więc najlepiej jak takie informacje potwierdzisz przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt), jednak z tego co wiem bez zarejestrowanej działalności nie można mieć konta firmowego, bo musisz mieć NIP i Regon, a w tym wypadku tego nie będzie. Jednak tak jak pisałam, większe kompetencje znajdziesz w odpowiednim dziale z formularza.

**Comment by Tanioagd** [comment]
Proszę  o pomoc z połączeniem kont. Nadal nie otrzymuje tego kodu weryfikacyjnego.

**Comment by Tanioagd** [comment]
konto które chce dołączyć to SklepTragar

**Comment by MaciejFrackowiak** [comment]
@Tanioagd Odpowiedziałem w wątku #8377.

**Comment by Zipp197** [comment]
Witam,

prośba o aktywację konta sandbox: Zipp197

**Comment by Lukasz-Zurek** [comment]
@Zipp197 Musisz jeszcze przejść przez [konfigurację wypłat](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty), a następnie skorzystać z symulatora płatności. Daj proszę znać jak już wykonasz te kroki.

**Comment by Zipp197** [comment]
@Lukasz-Zurek Dzięki za informacje. Już powinno być gotowe :)

**Comment by Lukasz-Zurek** [comment]
@Zipp197 Dziękuję! Aktywowałem :)

**Comment by TTomzynski** [comment]
Proszę o aktywację konta sandbox.
Nick: devdigitalberry

**Comment by Lukasz-Zurek** [comment]
@TTomzynski Aktywowałem konto.

**Comment by TTomzynski** [comment]
@Lukasz-Zurek Dziękuje :)

**Comment by pawel-rochowiak** [comment]
Proszę o aktywację konta sandbox.
TalarNU2

**Comment by Lukasz-Zurek** [comment]
@pawel-rochowiak Aktywowałem wskazane konto.
