### ISSUE TITLE
Problem z uploadem zdjęć do ofert

### ISSUE THREAD

**Issue by Arkowsky** [allegro/allegro-api#827]
Witam,

zgodnie z dokumentacją pod adresem [https://developer.allegro.pl/sale/#step-3-images](https://developer.allegro.pl/sale/#step-3-images) próbujemy uploadować zdjęcie ale dostajemy jako odpowiedź:
"Plik nie jest obrazem w formacie JPG, PNG lub GIF."

chociaż plik jest na pewno w png i ma prawidłowy rozmiar.

**Czy jest dzisiaj jakiś problem z uploadem obrazków?**

używając nawet curl dostajemy komunikat:

curl -X POST -H 'authorization: Bearer TOKEN' -H 'accept: application/vnd.allegro.public.v1+json' -H 'content-type: "image/png"' --data-binary "@Cat.png" https://upload.allegro.pl/sale/images

gdzie TOKEN to jest mój access_token - nie ma problemu z autoryzacją - to działa.

**Comment by PawelTaberski** [comment]
Nie odnotowaliśmy dziś problemów z tym zasobem. Sprawdziłem i zasób działa normalnie. Trochę mnie dziwi wartość nagłówka jaką podajesz, powinno być:
`'content-type: image/png'`
,a u ciebie widzę wartość w "" tak przesyłasz ostatecznie? Jeśli tak to usuń "" i powinno być ok.

**Comment by Arkowsky** [comment]
dzięki.

**Comment by Arkowsky** [comment]
Jeżeli jest możliwość to proszę zaktualizujcie dokumentacje - w przykładzie są błędy.
Taka pożądna firma i takie rzeczy ;)?

![screenshot 2018-10-29 at 08 52 06](https://user-images.githubusercontent.com/19975089/47636315-2dfd9a80-db58-11e8-9df5-ec499f0ecea7.png)

**Comment by PawelTaberski** [comment]
@Arkowsky Dzięki za informacje zaraz to zmienimy, aby nie wprowadzało w błąd.
