### ISSUE TITLE
Błąd TecdocSpecificationNotFound w /sale/products

### ISSUE THREAD

**Issue by PunktAutoCzesci** [allegro/allegro-api#8271]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

w zasobie
'/sale/products?phrase=AS-PL%20A0016&language=pl-PL'
dostaje w odpowiedzi błąd:
'TecdocSpecificationNotFound'

trac-id: 'e112480725c7d4de'

Przy próbie wyszukania produktów od frontu Allegro zamiast produktu dostaje komunikat "Nie udało się wyświetlić produktów."

proszę o sprawdzenie

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Zgłosiłem od razu do właściwego zespołu - ten sam błąd zwracamy przy odpytaniu tego konkretnego produktu, mimo, że posiada on wersję TecDoc.

Z góry przepraszamy za utrudnienia.

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Poprawiliśmy ten przypadek. Widzę, że prawidłowo już zwracamy wskazany produkt.

**Comment by PunktAutoCzesci** [comment]
tutaj kolejne przykłady:
AS0008
S0417
S0324
SS0010
S0493
S0401
A0007
A0012
A0049
S0571
SS0010(BOSCH)
A0056
S0414
S0385
S0271
ARE0086(BOSCH)
S0275

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Oczywiście powyższe przykłady już wcześniej przekazałem do odpowiedniego zespołu. W to systemowego rozwiązania, zresztą nawet lepiej, bo jak sam widzisz - przykłady się mnożą, a ręczne poprawki byłyby tutaj średnim rozwiązaniem.

Jak tylko uzyskam jakiekolwiek informacje w tej sprawie - wrócę w tym wątku.

Raz jeszcze przepraszamy za te utrudnienia.

**Comment by PunktAutoCzesci** [comment]
Kolejney przykłąd:
`DRM0863`

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Jeżeli chodzi o "TecdocSpecificationNotFound" (komunikat "Nie udało się wyświetlić produktów." na froncie) - przypadki te zostały poprawione. Mamy jeszcze jednak produkty, w których brakuje parametru dot. TecDoc - w tym przypadku produkty nadal mogą nie być zwracane i ten problem nadal jest w trakcie weryfikacji.

Czy możesz potwierdzić czy część przypadków została poprawiona?

Oczywiście ten nowy `DRM0863` przekazuję dalej.

**Comment by PunktAutoCzesci** [comment]
Cześć, 
systemowe działanie nie pomogło. 

nadal  **/sale/products** zwraca błędy a od frontu jest komunikat "Nie udało się wyświetlić produktów." 

Poniżej przykładowa lista stringów powodujących błędy. 


(270) ['TEXTAR 94048100', 'TEXTAR 98026800', 'TEXTAR 94044600', 'TEXTAR TEX1033', 'TEXTAR 92173103', 'TEXTAR 92183505', 'TEXTAR 92195903', 'TEXTAR 92202403', 'TEXTAR 92228503', 'MAXGEAR 11-0972', 'MAXGEAR 11-1109', 'MAXGEAR 11-0833', 'MAXGEAR 24-0273', 'MAXGEAR 11-1182', 'MAXGEAR 21-0447', 'MAXGEAR 11-1060', 'MAXGEAR 11-0986', 'MAXGEAR 11-1156', 'MAXGEAR 11-1205', 'MAXGEAR 11-1140', 'MAXGEAR 24-0375', 'MAXGEAR 24-0321', 'MAXGEAR 24-0376', 'MAXGEAR 24-0378', 'MAXGEAR 82-0259', 'MAXGEAR 82-0413', 'MAXGEAR 19-2734', 'MAXGEAR 26-1184', 'MAXGEAR 23-0027', 'MAXGEAR 23-0036', 'MAXGEAR 23-0066', 'MAXGEAR 23-0109', 'MAXGEAR 21-0391', 'MAXGEAR 24-0236', 'MAXGEAR 23-0058', 'MAXGEAR 23-0060', 'MAXGEAR 23-0070', 'MAXGEAR 23-0071', 'MAXGEAR 27-1311', 'MAXGEAR 24-0223', 'MAXGEAR 21-0390', 'MAXGEAR 19-3500', 'MAXGEAR 19-3497', 'MAXGEAR 19-2625', 'MAXGEAR 19-2183', 'MAXGEAR 26-1074', 'MAXGEAR 28-0335', 'MAXGEAR 19-3198', 'MAXGEAR 23-0033', 'MAXGEAR 19-3236', 'MAXGEAR 11-0501', 'MAXGEAR 27-1290', 'MAXGEAR 12-1745', 'MAXGEAR 12-1763', 'MAXGEAR 23-0042', 'MAXGEAR 82-0208', 'MAXGEAR 11-0554', 'MAXGEAR 82-0222', 'MAXGEAR 82-0402', 'MAXGEAR 19-3376', 'MAXGEAR 19-2237', 'MAXGEAR 23-0073', 'MAXGEAR 27-1307', 'MAXGEAR 13-0175', 'MAXGEAR 13-0179', 'MAXGEAR 14-0030', 'MAXGEAR 23-0092', 'MAXGEAR 23-0101', 'MAXGEAR 23-0110', 'MAXGEAR 23-0055', 'MAXGEAR 23-0105', 'MAXGEAR 24-0218', 'MAXGEAR 24-0225', 'MAXGEAR 11-0413', 'MAXGEAR 27-1306', 'MAXGEAR 21-0389', 'MAXGEAR 13-0194', 'MAXGEAR 23-0132', 'MAXGEAR 24-0239', 'MAXGEAR AC156489', 'MAXGEAR 12-1866', 'MAXGEAR 12-2081', 'MAXGEAR 26-1503', 'MAXGEAR 12-2030', 'MAXGEAR 72-3646', 'MAXGEAR 12-2237', 'MAXGEAR 49-3096', 'MAXGEAR 13-0209', 'MAXGEAR 82-0249', 'MAXGEAR 77-0053', 'MAXGEAR AC230095', 'MAXGEAR 26-1904', 'MAXGEAR 26-1840', 'MAXGEAR 49-2385', 'MAXGEAR 19-3683', 'MAXGEAR 72-3961', 'MAXGEAR AC230045', 'MAXGEAR 11-1204', 'MAXGEAR 12-2382', 'MAXGEAR 27-1231', …]

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za przykłady. Przekazałem je do zespołu odpowiedzialnego za usługę, wrócę z informacją, gdy uda się rozwiązać problem.

**Comment by PrzemyslawLukanowski** [comment]
Czy mógłbyś przesłać nam plik ze wszystkimi frazami, które zwracają błąd? Możesz to zrobić za pośrednictwem [formularza](https://allegro.pl/pomoc/kontakt), dopisując, że dane powiązane są ze zgłoszeniem #8271 na GitHubie.

**Comment by PunktAutoCzesci** [comment]
Cześć, 
jeśli się da, to sprawdź proszę chociaż na przykładach które masz. Ja będę mógł pozbierać ich więcej dopiero za kilka dni.

**Comment by PrzemyslawLukanowski** [comment]
Jasne, dziękuję.

**Comment by PunktAutoCzesci** [comment]
Na dzisiaj mam taką listę:
"MAXGEAR 11-0972", "MAXGEAR 11-1109", "MAXGEAR 11-0833", "MAXGEAR 24-0273", "MAXGEAR 11-1182", "MAXGEAR 21-0447", "MAXGEAR 11-1060", "MAXGEAR 11-0986", "MAXGEAR 11-1156", "MAXGEAR 11-1205", "MAXGEAR 11-1140", "MAXGEAR 24-0375", "MAXGEAR 24-0321", "MAXGEAR 24-0376", "MAXGEAR 24-0378", "MAXGEAR 82-0259", "MAXGEAR 82-0413", "MAXGEAR 19-2734", "MAXGEAR 26-1184", "MAXGEAR 23-0027", "MAXGEAR 23-0036", "MAXGEAR 23-0066", "MAXGEAR 23-0109", "MAXGEAR 21-0391", "MAXGEAR 24-0236", "MAXGEAR 23-0058", "MAXGEAR 23-0060", "MAXGEAR 23-0070", "MAXGEAR 23-0071", "MAXGEAR 27-1311", "MAXGEAR 24-0223", "MAXGEAR 21-0390", "MAXGEAR 19-3500", "MAXGEAR 19-3497", "MAXGEAR 19-2625", "MAXGEAR 19-2183", "MAXGEAR 26-1074", "MAXGEAR 28-0335", "MAXGEAR 19-3198", "MAXGEAR 23-0033", "MAXGEAR 19-3236", "MAXGEAR 11-0501", "MAXGEAR 27-1290", "MAXGEAR 12-1745", "MAXGEAR 12-1763", "MAXGEAR 23-0042", "MAXGEAR 82-0208", "MAXGEAR 11-0554", "MAXGEAR 82-0222", "MAXGEAR 82-0402", "MAXGEAR 19-3376", "MAXGEAR 19-2237", "MAXGEAR 23-0073", "MAXGEAR 27-1307", "MAXGEAR 13-0175", "MAXGEAR 13-0179", "MAXGEAR 14-0030", "MAXGEAR 23-0092", "MAXGEAR 23-0101", "MAXGEAR 23-0110", "MAXGEAR 23-0055", "MAXGEAR 23-0105", "MAXGEAR 24-0218", "MAXGEAR 24-0225", "MAXGEAR 11-0413", "MAXGEAR 27-1306", "MAXGEAR 21-0389", "MAXGEAR 13-0194", "MAXGEAR 23-0132", "MAXGEAR 24-0239", "MAXGEAR AC156489", "MAXGEAR 12-1866", "MAXGEAR 12-2081", "MAXGEAR 26-1503", "MAXGEAR 12-2030", "MAXGEAR 72-3646", "MAXGEAR 12-2237", "MAXGEAR 49-3096", "MAXGEAR 13-0209", "MAXGEAR 82-0249", "MAXGEAR 77-0053", "MAXGEAR AC230095", "MAXGEAR 26-1904", "MAXGEAR 26-1840", "MAXGEAR 49-2385", "MAXGEAR 19-3683", "MAXGEAR 72-3961", "MAXGEAR AC230045", "MAXGEAR 11-1204", "MAXGEAR 12-2382", "MAXGEAR 27-1231", "MAXGEAR 21-0380", "MAXGEAR 21-0381", "MAXGEAR 21-0398", "MAXGEAR 23-0121", "MAXGEAR 21-0864", "MAXGEAR 24-0212", "MAXGEAR 13-0177", "MAXGEAR 21-0432", "MAXGEAR 23-0046", "MAXGEAR 12-2056", "CORTECO 21653153", "DENSO DCN44003", "DENSO DG-186", "GSP 803035", "GSP 511659", "GSP 834021", "GSP 844006", "GSP 845065", "TEXTAR 94048100", "TEXTAR 98026800", "TEXTAR 94044600", "TEXTAR TEX1033", "MEYLE 40-146500000", "MEYLE 1267250044", "MEYLE 1267250055", "MEYLE 7267250036", "MEYLE 53-123210006", "MEYLE 3160504317/HD", "MEYLE 7160600023/HD", "MEYLE 7141030001/HD", "MEYLE 4160200003/HD", "MEYLE 6160200029/HD", "MEYLE 7123190005", "MEYLE 0140272109"

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za przykłady, je również przekazałem dalej do zespołu odpowiedzialnego za usługę.

**Comment by PunktAutoCzesci** [comment]
Cześć, poniżej przykłady z dzisiaj. Mogą zawierać powtórzenia jeśli produkty z poprzedniej listy jeszcze nie zostały naprawione.

"AS-PL S0275", "AS-PL A0016", "AS-PL A0034", "AS-PL S0417", "AS-PL S0324", "AS-PL SS0010", "AS-PL S0401", "AS-PL A0007", "AS-PL A0049", "AS-PL S0571", "AS-PL SS0010(BOSCH)", "AS-PL A0056", "AS-PL S0414", "AS-PL S0271", "TEXTAR 94048100", "TEXTAR 98026800", "TEXTAR 94044600", "TEXTAR TEX1033", "TEXTAR 92202303", "MAXGEAR 11-0972", "MAXGEAR 11-1109", "MAXGEAR 11-0833", "MAXGEAR 24-0273", "MAXGEAR 11-1182", "MAXGEAR 21-0447", "MAXGEAR 11-1060", "MAXGEAR 11-0986", "MAXGEAR 11-1156", "MAXGEAR 11-1205", "MAXGEAR 11-1140", "MAXGEAR 24-0375", "MAXGEAR 24-0321", "MAXGEAR 24-0376", "MAXGEAR 24-0378", "MAXGEAR 82-0259", "MAXGEAR 82-0413", "MAXGEAR 19-2734", "MAXGEAR 26-1184", "MAXGEAR 23-0027", "MAXGEAR 23-0036", "MAXGEAR 23-0066", "MAXGEAR 23-0109", "MAXGEAR 21-0391", "MAXGEAR 24-0236", "MAXGEAR 23-0058", "MAXGEAR 23-0060", "MAXGEAR 23-0070", "MAXGEAR 23-0071", "MAXGEAR 27-1311", "MAXGEAR 24-0223", "MAXGEAR 21-0390", "MAXGEAR 19-3500", "MAXGEAR 19-3497", "MAXGEAR 19-2625", "MAXGEAR 19-2183", "MAXGEAR 26-1074", "MAXGEAR 28-0335", "MAXGEAR 19-3198", "MAXGEAR 23-0033", "MAXGEAR 19-3236", "MAXGEAR 11-0501", "MAXGEAR 27-1290", "MAXGEAR 12-1745", "MAXGEAR 12-1763", "MAXGEAR 23-0042", "MAXGEAR 82-0208", "MAXGEAR 11-0554", "MAXGEAR 82-0222", "MAXGEAR 82-0402", "MAXGEAR 19-3376", "MAXGEAR 19-2237", "MAXGEAR 23-0073", "MAXGEAR 27-1307", "MAXGEAR 13-0175", "MAXGEAR 13-0179", "MAXGEAR 14-0030", "MAXGEAR 23-0092", "MAXGEAR 23-0101", "MAXGEAR 23-0110", "MAXGEAR 23-0055", "MAXGEAR 23-0105", "MAXGEAR 24-0218", "MAXGEAR 24-0225", "MAXGEAR 11-0413", "MAXGEAR 27-1306", "MAXGEAR 21-0389", "MAXGEAR 13-0194", "MAXGEAR 23-0132", "MAXGEAR 24-0239", "MAXGEAR AC156489", "MAXGEAR 12-1866", "MAXGEAR 12-2081", "MAXGEAR 26-1503", "MAXGEAR 12-2030", "MAXGEAR 72-3646", "MAXGEAR 12-2237", "MAXGEAR 49-3096", "MAXGEAR 13-0209", "MAXGEAR 82-0249", "MAXGEAR 77-0053", "MAXGEAR AC230095", "MAXGEAR 26-1904", "MAXGEAR 26-1840", "MAXGEAR 49-2385", "MAXGEAR 19-3683", "MAXGEAR 72-3961", "MAXGEAR AC230045", "MAXGEAR 11-1204", "MAXGEAR 12-2382", "MAXGEAR 27-1231", "MAXGEAR 21-0380", "MAXGEAR 21-0381", "MAXGEAR 21-0398", "MAXGEAR 23-0121", "MAXGEAR 21-0864", "MAXGEAR 24-0212", "MAXGEAR 13-0177", "MAXGEAR 21-0432", "MAXGEAR 23-0046", "MAXGEAR 12-2056", "MEYLE 40-146500000", "MEYLE 1267250044", "MEYLE 1267250055", "MEYLE 7267250036", "MEYLE 53-123210006", "MEYLE 3160504317/HD", "MEYLE 7160600023/HD", "MEYLE 7141030001/HD", "MEYLE 4160200003/HD", "MEYLE 6160200029/HD", "MEYLE 7123190005", "MEYLE 0140272109", "MEYLE 7146310016", "MEYLE 6148600000", "MEYLE 6155236002", "MEYLE 40-123190004", "MEYLE 29-123190000", "MEYLE 6148600001", "MEYLE 7146100003", "MEYLE 0500061155", "MEYLE 6160100100", "MEYLE 7155237035", "MEYLE 5140183265", "MEYLE 7155237040", "MEYLE 7155237038", "MEYLE 7123190011", "MEYLE 6155230003", "MEYLE 0155232105", "MEYLE 11-155230003", "MEYLE 31-155230018", "MEYLE 7146790002", "MEYLE 37-123190018", "MEYLE 7147410003", "MEYLE 6155230015", "MEYLE 16-155230019", "MEYLE 28-155230018", "MEYLE 11-155230005", "MEYLE 37-155230006", "MEYLE 7123190010", "MEYLE 30-267250009", "MEYLE 37-155230004", "MEYLE 35-155230029", "MEYLE 11-148010000", "MEYLE 37-148850012", "MEYLE 7123190012", "MEYLE 37-148850001", "MEYLE 6148850011", "MEYLE 37-148850002", "MEYLE 29-148850000", "MEYLE 7145310009", "MEYLE 37-148850005", "MEYLE 29-148850001", "MEYLE 36-147400003", "MEYLE 7146400010", "MEYLE 37-148010000", "MEYLE 5148010000", "MEYLE 16-145310013", "MEYLE 0145310002", "MEYLE 7148850005", "MEYLE 5123200007", "MEYLE 6145310001", "MEYLE 7123190014", "MEYLE 11-145310011", "MEYLE 11-145310012", "MEYLE 7148850011", "MEYLE 30-148850010", "MEYLE 5146400004", "MEYLE 0123190036", "MEYLE 5146400003", "MEYLE 7145310005", "MEYLE 6146400010", "MEYLE 16-145310002", "MEYLE 5146400002", "MEYLE 36-146400003", "MEYLE 7144980061", "MEYLE 36-148850007", "MEYLE 37-148850008", "MEYLE 1123240022", "MEYLE 1155231049", "MEYLE 2148850009", "MEYLE 2148850012", "MEYLE 2155230011", "MEYLE 3142260008", "MEYLE 3146400015", "MEYLE 3148990081", "MEYLE 0520130900", "MEYLE 28-160310016", "MEYLE 32-147100007", "BOSCH 0258003189", "BOSCH 0242232804", "BOSCH 0445116012", "BOSCH 0445116016", "TRW GDB1794", "TRW GDB1826DTE", "TRW GDB1848", "TRW GDB1981", "TRW GDB3613", "TRW ST1334", "BLUE PRINT ADL143015", "BLUE PRINT ADN18931", "BLUE PRINT ADN14720", "BLUE PRINT ADN18931B", "BLUE PRINT ADT37616", "BLUE PRINT ADA102502", "BLUE PRINT ADT322112", "QUARO QD5097", "QUARO QP9911", "QUARO QP7802", "QUARO QP5874", "QUARO QP6454", "QUARO QP6972", "QUARO QP6972C", "QUARO QP3860", "QUARO QP3341", "QUARO QP3746", "QUARO QP5317", "QUARO QP6229", "QUARO QP7578", "QUARO QP5781", "QUARO QP6233", "QUARO QP0727", "QUARO QS0240/HQ", "QUARO QS0541/HQ", "QUARO QS0542/HQ", "QUARO QS1766/HQ", "QUARO QS1774/HQ", "QUARO QS1840/HQ", "QUARO QS2109/HQ", "QUARO QS2194/HQ", "QUARO QS2799/HQ", "QUARO QS2819/HQ", "QUARO QS3851/HQ", "QUARO QS4111/HQ", "QUARO QS6663/HQ", "QUARO QS8786/HQ", "QUARO QS9837/HQ", "QUARO QS0851/HQ", "FEBI BILSTEIN 34635", "FEBI BILSTEIN 22490", "FEBI BILSTEIN 29984", "FEBI BILSTEIN 33062", "FEBI BILSTEIN 170994", "BERU ZS369", "VICTOR REINZ 71-41338-00", "VICTOR REINZ 71-36182-00", "VICTOR REINZ 61-35420-20", "VICTOR REINZ 81-10479-00", "MAGNETI MARELLI 941319170057", "DAYCO 5PK835", "ATE 13.0460-0413.2", "ATE 13.0460-0283.2", "SACHS 3000828202", "CORTECO 21653153", "CORTECO 12011426B", "LUK 415016310", "LUK 600003800", "LUK 620116609", "HELLA 4RA007507-081", "HELLA 9XU358039-091", "HELLA 6NU010171-641", "HELLA 8ET009149-051", "HELLA 6PP009400-471", "HELLA 6PU012680-021", "HELLA 8ET009149-181", "HELLA 8ET009142-361", "HELLA 6DD008622-491", "INA 558008310", "INA 531002410", "INA 531024220", "INA 531022510", "INA 531002920", "INA 531003410", "INA 531016620", "VDO S107542002Z", "CONTINENTAL 3PK960", "CONTINENTAL 6PK2140", "CONTINENTAL CT986", "CONTINENTAL CT901WP1", "CONTINENTAL CT1164K1", "CONTINENTAL CT726", "CONTINENTAL WPS3035", "LEMFORDER 2514701", "LEMFORDER 2599301", "LEMFORDER 3551501", "LEMFORDER 3750101", "PIERBURG 7.22684.12.0", "DELPHI SS20098"

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za kolejne przykłady, je również przekazałem do zespołu odpowiedzialnego za usługę. Wstępnie problem powinien zostać rozwiązany do końca tygodnia, jednak może się to przedłużyć o kilka dni.

**Comment by PunktAutoCzesci** [comment]
Dawka świeżych nowych przykładów:
TEXTAR 94048100
TEXTAR 98026800
TEXTAR 94044600
MAXGEAR 24-0273
MAXGEAR 21-0447
MAXGEAR 11-1060
MAXGEAR 11-0986
MAXGEAR 11-1156
MAXGEAR 11-1205
MAXGEAR 11-1140
MAXGEAR 24-0375
MAXGEAR 24-0321
MAXGEAR 24-0376
MAXGEAR 24-0378
MAXGEAR 82-0413
MAXGEAR 19-2734
MAXGEAR 23-0027
MAXGEAR 23-0066
MAXGEAR 23-0109
MAXGEAR 23-0058
MAXGEAR 23-0060
MAXGEAR 23-0070
MAXGEAR 23-0071
MAXGEAR 24-0223
MAXGEAR 19-3500
MAXGEAR 19-3497
MAXGEAR 19-2625
MAXGEAR 19-2183
MAXGEAR 28-0335
MAXGEAR 19-3198
MAXGEAR 23-0033
MAXGEAR 82-0208
MAXGEAR 11-0554
MAXGEAR 82-0222
MAXGEAR 19-2237
MAXGEAR 23-0073
MAXGEAR 14-0030
MAXGEAR 23-0055
MAXGEAR 23-0105
MAXGEAR 12-1866
MAXGEAR 26-1503
MAXGEAR 12-2030
MAXGEAR 12-2237
MAXGEAR 82-0249
MAXGEAR 77-0053
MAXGEAR 49-2385
MAXGEAR 19-3683
MAXGEAR 72-3961
MAXGEAR 11-1204
MAXGEAR 23-0121
MAXGEAR 12-2056
MAXGEAR 12-2072
MAXGEAR 12-2222
MAXGEAR 12-2238
MAXGEAR 12-1530
MAXGEAR 24-0249
MAXGEAR 12-2016
MAXGEAR 12-2209
MAXGEAR 12-2034
MAXGEAR 12-2218
MAXGEAR 12-2220
MAXGEAR 12-2379
MAXGEAR 19-3691
MAXGEAR 23-0079
MAXGEAR 21-0426
MAXGEAR AC265912
MAXGEAR 24-0269
MAXGEAR 68-0227
MAXGEAR 12-1861
MAXGEAR 12-2135
MAXGEAR 12-2208
MAXGEAR 24-0237
MAXGEAR 12-2123
MAXGEAR 26-1903
MAXGEAR AC219100
MAXGEAR 49-2320
MAXGEAR 49-2382
MAXGEAR 72-5326
MAXGEAR 12-2351
MAXGEAR 23-0093
MAXGEAR 19-3721
MAXGEAR 11-0797
MAXGEAR 28-0455
MAXGEAR 19-3311
MAXGEAR 12-1966
MAXGEAR 12-2104
MAXGEAR 82-0587
MAXGEAR 12-1887
MAXGEAR 61-0109
MAXGEAR 26-1876
MAXGEAR AC230006
MAXGEAR 12-2333
MAXGEAR 11-0603
MAXGEAR 23-0126
MAXGEAR 11-0804
MAXGEAR 28-0452
MAXGEAR 24-0256
MAXGEAR 72-3620
MAXGEAR 82-0766
MAXGEAR 26-1883
MAXGEAR AC230164
MAXGEAR AC230165
MAXGEAR 11-0805
MAXGEAR 72-3619
MEYLE 1267250044
MEYLE 1267250055
MEYLE 7123190005
MEYLE 6148600000
MEYLE 6155236002
MEYLE 40-123190004
MEYLE 29-123190000
MEYLE 7146100003
MEYLE 0500061155
MEYLE 6160100100
MEYLE 7155237035
MEYLE 7155237040
MEYLE 7155237038
MEYLE 7123190011
MEYLE 6155230003
MEYLE 0155232105
MEYLE 11-155230003
MEYLE 31-155230018
MEYLE 7146790002
MEYLE 7147410003
MEYLE 6155230015
MEYLE 16-155230019
MEYLE 28-155230018
MEYLE 11-155230005
MEYLE 37-155230006
MEYLE 7123190010
MEYLE 37-155230004
MEYLE 35-155230029
MEYLE 37-148850012
MEYLE 7123190012
MEYLE 37-148850002
MEYLE 29-148850000
MEYLE 7145310009
MEYLE 36-147400003
MEYLE 37-148010000
MEYLE 16-145310013
MEYLE 5123200007
MEYLE 6145310001
MEYLE 7123190014
MEYLE 11-145310012
MEYLE 30-148850010
MEYLE 7145310005
MEYLE 6146400010
MEYLE 16-145310002
MEYLE 36-146400003
MEYLE 7144980061
MEYLE 36-148850007
MEYLE 1155231049
MEYLE 2155230011
MEYLE 28-160310016
BOSCH 1006209808
TRW GDB1794
TRW GDB1848
TRW GDB1094
TRW GDB1672
TRW GDB1672DTE
TRW JAR207
TRW GDB1675DTE
TRW GDB3567
TRW MST374
TRW GDB1042
TRW GDB3628
TRW GDB1094DTE
TRW PJQ110
TRW GDB1794DTE
TRW MST374RAC
TRW GDB1675
TRW GDB1892
TRW GDB1848DTE
TRW GDB1892DTE

**Comment by AureliuszBrussy** [comment]
Dziękuję za kolejną porcję przykładów, właśnie przekazałem je do zespołu odpowiedzialnego za tą usługę - niebawem je poprawimy.

**Comment by PunktAutoCzesci** [comment]
Widzę, że część z przykładów np "24-0375" powtarza się z tymi z 28.06.2024. Przez kilka miesięcy nikt z tym nic nie zrobił?

**Comment by AureliuszBrussy** [comment]
@PunktAutoCzesci dzięki za zwrócenie uwagi. Wtedy dostaliśmy potwierdzenie, że tak, natomiast podrążę temat, czy faktycznie tak się stało. Dam znać.

**Comment by PunktAutoCzesci** [comment]
Kolejny tydzień mija a nadal nic się nie zmienia. Może lepiej usunąć te produkty zamiast zwracać błędy? 
Użytkownicy sami je dodadzą jeśli mapowanie z TecDoc jest tak "problematyczne"...

**Comment by AureliuszBrussy** [comment]
@PunktAutoCzesci jeszcze to wyjaśniam, ponaglam sprawę. Dziękuję też za Twoją uwagę. Postaram się możliwie szybko wrócić z informacją.

**Comment by PunktAutoCzesci** [comment]
Odświeżam. ponownie załączam listę wyszukiwań które powodują błąd. 
I ponownie, są na niej produkty które zgłaszałem już 28 czerwca. Czy kogoś w ogóle to obchodzi? 

(97) ['TRW GDB1848', 'TRW GDB1094', 'TRW GDB1042', 'TRW GDB1094DTE', 'TRW PJQ110', 'TRW GDB1892', 'TRW GDB1848DTE', 'TRW GDB1892DTE', 'MAXGEAR 24-0273', 'MAXGEAR 21-0447', 'MAXGEAR 11-1060', 'MAXGEAR 11-0986', 'MAXGEAR 11-1156', 'MAXGEAR 11-1205', 'MAXGEAR 11-1140', 'MAXGEAR 24-0375', 'MAXGEAR 24-0321', 'MAXGEAR 24-0376', 'MAXGEAR 24-0378', 'MAXGEAR 19-2734', 'MAXGEAR 23-0027', 'MAXGEAR 23-0066', 'MAXGEAR 23-0109', 'MAXGEAR 23-0058', 'MAXGEAR 23-0060', 'MAXGEAR 23-0070', 'MAXGEAR 23-0071', 'MAXGEAR 19-3500', 'MAXGEAR 19-3497', 'MAXGEAR 19-2625', 'MAXGEAR 19-2183', 'MAXGEAR 28-0335', 'MAXGEAR 19-3198', 'MAXGEAR 23-0033', 'MAXGEAR 82-0208', 'MAXGEAR 11-0554', 'MAXGEAR 19-2237', 'MAXGEAR 23-0073', 'MAXGEAR 14-0030', 'MAXGEAR 23-0055', 'MAXGEAR 23-0105', 'MAXGEAR 12-1866', 'MAXGEAR 26-1503', 'MAXGEAR 12-2030', 'MAXGEAR 12-2237', 'MAXGEAR 82-0249', 'MAXGEAR 49-2385', 'MAXGEAR 19-3683', 'MAXGEAR 72-3961', 'MAXGEAR 11-1204', 'MAXGEAR 23-0121', 'MAXGEAR 12-2222', 'MAXGEAR 12-2238', 'MAXGEAR 24-0249', 'MAXGEAR 12-2016', 'MAXGEAR 12-2034', 'MAXGEAR 12-2218', 'MAXGEAR 12-2220', 'MAXGEAR 19-3691', 'MAXGEAR 23-0079', 'MAXGEAR 21-0426', 'MAXGEAR AC265912', 'MAXGEAR 24-0269', 'MAXGEAR 12-1861', 'MAXGEAR 12-2135', 'MAXGEAR 12-2123', 'MAXGEAR 26-1903', 'MAXGEAR AC219100', 'MAXGEAR 49-2320', 'MAXGEAR 49-2382', 'MAXGEAR 12-2351', 'MAXGEAR 23-0093', 'MAXGEAR 19-3721', 'MAXGEAR 11-0797', 'MAXGEAR 28-0455', 'MAXGEAR 19-3311', 'MAXGEAR 12-1966', 'MAXGEAR 12-2104', 'MAXGEAR 82-0587', 'MAXGEAR 12-1887', 'MAXGEAR 61-0109', 'MAXGEAR 26-1876', 'MAXGEAR AC230006', 'MAXGEAR 23-0126', 'MAXGEAR 11-0804', 'MAXGEAR 28-0452', 'MAXGEAR 24-0256', 'MAXGEAR 72-3620', 'MAXGEAR 82-0766', 'MAXGEAR AC230164', 'MAXGEAR AC230165', 'MAXGEAR 11-0805', 'MAXGEAR 72-3619', 'MAXGEAR 12-2126', 'MAXGEAR 12-2229', 'MAXGEAR 26-1910', 'MAXGEAR 12-1839']

**Comment by AureliuszBrussy** [comment]
Dziękuję za kolejne przykłady produktów. Przepraszam za niedogodność i dłuższy czas rozwiązania tego problemu. Przekazałem te nowe przykłady oraz ponagliłem zespół, który jest w stanie poprawić te przypadki.
