### ISSUE TITLE
"Dodawanie własnych wartości zostało zablokowane"

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#8272]
Próbuję zaktualizować produkt przez POST https://api.allegro.pl/sale/products/f95d1228-5180-4a83-8ed1-726a05e180ff/change-proposals .

Parametry zapytania:
{"name":"Ko\u0142ki ryflowane bukowe 8x35mm 100szt","category":{"id":314853},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/11ac8f\/ba2dd96e42f0b358209f896528a0"}],"parameters":[{"id":"303","values":["8.00"]},{"id":"227361","values":["35.00"]},{"id":"222637","values":[100]},{"id":"247585","valuesIds":["247585_716949"]},{"id":"247589","valuesIds":["247589_4"]},{"id":"17448","values":["0.001"]},{"id":"224017","values":["MetalGear.pl_355"]},{"id":"225693","values":["5904172402240"]},{"id":"248811","valuesIds":["248811_950468"],"values":["MetalGear.pl"]}],"notifyViaEmailAfterVerification":true,"language":"pl-PL"}

W odpowiedzi dostaję:
[code] => CreateProductSuggestionValidationException [message] => Zgłaszanie błędów w produkcie zakończyło się błędem: Nieprawidłowo wypełnione parametry: [Dodawanie własnych wartości zostało zablokowane, wybierz wartość ze słownika dla parametru 248811 (Marka)] [details] => [path] => /sale/products/f95d1228-5180-4a83-8ed1-726a05e180ff/change-proposals [userMessage] => Zgłaszanie błędów w produkcie zakończyło się błędem: Nieprawidłowo wypełnione parametry: [Dodawanie własnych wartości zostało zablokowane, wybierz wartość ze słownika dla parametru 248811 (Marka)] 

Pomimo, że dla tego parametru w tej kategorii pole customValuesEnabled jest równie true.

W jaki sposób mogę sprawdzić, czy w tej kategorii mogę przekazać własną wartość, czy nie?

**Comment by rasskabak** [comment]
Pobieram aktualną listę parametrów przez API i parametr Marka cały czas występuje pod numerem 248811. Wynika to też jasno z komunikatu błędu - wybierz wartość ze słownika dla parametru **248811** (Marka)

**Comment by Lukasz-Zurek** [comment]
Ok, rozumiem. Prześlij proszę trace-id dla świeżego żądania. Sprawdzę dokładnie, bo komunikat może być też mylący.

**Comment by rasskabak** [comment]
Problem nadal występuje. Przykładowy trace-id: dbf0f05e969e9d99

**Comment by Lukasz-Zurek** [comment]
@rasskabak Dziękuję za zgłoszenie i konkretny przykład. Zweryfikuję to i odpowiem kompleksowo w Twoim nowym [wątku](https://github.com/allegro/allegro-api/issues/10142).
