### ISSUE TITLE
Data wpływu na konto allegro przy pobraniu

### ISSUE THREAD

**Issue by lasoczczyk** [allegro/allegro-api#8274]
Dzień dobry, na potrzeby księgowe potrzebuję uzyskać datę płatności zamówienia.
Przy zamówieniu standardowym datę zamówienia pobieram z ventu BOUGHT a datę płatności ze statusu READY_FOR_PROCESSING. 
To ogarnąłem.

Jak jest w przypadku zamówienia pobraniowego? Nie ma specjalnego eventu na to.
Skąd pobrać datę otrzymania przez allegro płatnosci z pobrania?
W /order/checkout-forms/{id} znalazłem pole "surcharges" i tam możliwa wartość CASH_ON_DELIVERY - czy to właśnie stąd mam pobrać tą datę?

**Comment by Lukasz-Zurek** [comment]
Nie, pole **"surcharges"** odpowiedzialne jest za dopłaty.

Jeżeli chodzi o CASH_ON_DELIVERY - w **/order/checkout-forms/{id}** zwracamy jedynie datę przekazania formularza do realizacji, konkretnie w polu **"finishedAt"**. Nie jest to jednak tożsame z datą płatności.

Natomiast [dla metod, za które Sprzedawca rozlicza się z Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/platnosc-od-kupujacego/kiedy-i-w-jaki-sposob-dostaniesz-pieniadze-za-zamowienia-z-platnoscia-przy-odbiorze-oAyjyMWWncL) - środki wpłyną na subkonto, co możesz sprawdzić za pomocą [GET /payments/payment-operations](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory) w polu **"occurredAt"**.

**Comment by lasoczczyk** [comment]
Bardzo dziękuję.
Działam zatem.

**Comment by lasoczczyk** [comment]
Hmmm a jak w takim razie powiązać płatność z konkretnym zamówieniem :)
