### ISSUE TITLE
Tworzenie szkicu

### ISSUE THREAD

**Issue by PiotrPiotrP** [allegro/allegro-api#8275]
Próbuję stworzyć draft  
POST   https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/ requestBody={"productSet":[{"quantity":{"value":1},"product":{"name":"test walidacji 2 M PSHEA","idType":"GTIN","parameters":[{"id":"129310","valuesIds":["129310_208361"]},{"id":"201089","values":["40"]},{"id":"3766","valuesIds":["3766_1"]},{"id":"201025","valuesIds":["201025_2513"]},{"id":"201077","valuesIds":["201077_2581"]},{"id":"54","valuesIds":["54_4"]},{"id":"3786","valuesIds":["3786_2"]},{"id":"129313","valuesIds":["129313_65536"]},{"id":"15851","valuesIds":["15851_1"]},{"id":"129309","valuesIds":["129309_3"]},{"id":"249512","valuesIds":["249512_1647423"]},{"id":"201017","valuesIds":["201017_2381"]}],"category":{"id":"254259"},"images":["https://images.stocksell.io/images/e9/e9466533-0b2e-4a99-9135-78b6be136cfd","https://images.stocksell.io/images/97/97dc3ef0-e7db-40ad-9bc5-56392ca13843","https://images.stocksell.io/images/24/244b1526-392a-49f3-8b20-e99ff0aad25a"]}}],"category":{"id":"254259"},"delivery":{"shippingRates":{"id":"46d946ca-b1c9-43e4-8c02-4aed1eb99911"},"handlingTime":"PT24H"},"publication":{"duration":"PT120H","startingAt":"2024-01-15T11:46:29.000Z","republish":true},"language":"pl-PL","afterSalesServices":{"impliedWarranty":{"id":"55f17cad-3715-49e3-979a-4db15c2ba5c0"},"returnPolicy":{"id":"a0abdc6a-74f5-4d2f-accf-3179d36f16ea"}},"stock":{"available":1,"unit":"UNIT"},"parameters":[{"id":"11323","valuesIds":["11323_1"]}],"name":"test walidacji 2 M PSHEA","payments":{"invoice":"NO_INVOICE"},"sellingMode":{"format":"ADVERTISEMENT","price":{"amount":98.99,"currency":"PLN"},"startingPrice":{"amount":98.99,"currency":"PLN"}},"location":{"city":"Skawina","countryCode":"PL","postCode":"32-050","province":"MALOPOLSKIE"},"images":["https://images.stocksell.io/images/e9/e9466533-0b2e-4a99-9135-78b6be136cfd","https://images.stocksell.io/images/97/97dc3ef0-e7db-40ad-9bc5-56392ca13843","https://images.stocksell.io/images/24/244b1526-392a-49f3-8b20-e99ff0aad25a"],"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003ch2\u003etest walidacji 2\u003c/h2\u003e"}]},{"items":[{"type":"IMAGE","url":"https://images.stocksell.io/images/e9/e9466533-0b2e-4a99-9135-78b6be136cfd"},{"type":"TEXT","content":"\u003ch2\u003eOpis Produktu\u003c/h2\u003e\u003cul\u003e\u003cli\u003e\u003cb\u003eMarka\u003c/b\u003e Pull\u0026amp;Bear\u003c/li\u003e\u003cli\u003e\u003cb\u003eKolor\u003c/b\u003e Niebieskis\u003c/li\u003e\u003cli\u003e\u003cb\u003eSkład\u003c/b\u003e jeans\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka papierowa\u003c/b\u003e Produkt posiada metki papierowe.\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka wewnętrzna\u003c/b\u003e Produkt posiada metki wewnętrzne.\u003c/li\u003e\u003cli\u003e\u003cb\u003eRozmiar\u003c/b\u003e M\u003c/li\u003e\u003cli\u003e\u003cb\u003eCena katalogowa\u003c/b\u003e 99,99 zł\u003c/li\u003e\u003c/ul\u003e"}]},{"items":[{"type":"IMAGE","url":"https://images.stocksell.io/images/97/97dc3ef0-e7db-40ad-9bc5-56392ca13843"},{"type":"IMAGE","url":"https://images.stocksell.io/images/24/244b1526-392a-49f3-8b20-e99ff0aad25a"}]}]},"external":{"id":"stocksell_297784379"},"taxSettings":{"rates":[{"countryCode":"PL"}]}} exception=Niepoprawna odpowiedź z Allegro. Kod: 422. Błąd: ProductValidationException Nie można stworzyć produktu bez podania poprawnych wartości wszystkich parametrów wymaganych: [EAN (GTIN)] Unable to create product without proper values in all required parameters: [EAN (GTIN)] in category: 254259 productSet[0].product. Trace-id=[a991ffcc03c4e242].
Czy jest możliwość utworzenia szkicu oferty i produktu?
A jak nie ma to jak powinno wyglądać stworzenie szkicu w takiej sytuacji jak powyżej?

**Comment by lasoczczyk** [comment]
Musisz podać EAN czyli w productset -> product -> id musisz wpisać prawidłowy kod EAN zamiast "129310" co pewnie jest twoim ID wewnętrznym?
Bez podania EAN nie utworzysz produktu.

**Comment by PiotrPiotrP** [comment]
Dziękuję

**Comment by Lukasz-Zurek** [comment]
@PiotrPiotrP Posłużę się tutaj [wcześniejszą wypowiedzią](https://github.com/allegro/allegro-api/issues/7963#issuecomment-1813850001) mojego kolegi. Czyli w przypadku kategorii 254259 wskazanie EANu będzie konieczne.

**Comment by michal20111** [comment]
Mam problem ze wskazaniem EAN dla kategorii 18719 - szyby samochodowe nie mogę utworzyć przez to produktu. Co można zrobić w takim przypadku ?

**Comment by michal20111** [comment]
nawet jak dostaję id z katalogu mam że żadanie jest błędne {
    "b2b": {
        "buyableOnlyByBusiness": false
    },
    "delivery": {
        "handlingTime": "PT24H",
        "shippingRates": {
            "id": "25c4bdc5-e5df-4bbb-859b-0195faa91345"
        },
        "additionalInfo": ""
    },
    "stock": {
        "available": 1,
        "unit": "UNIT"
    },
    "language": "pl-PL",
    "category": {
        "id": 18719
    },
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_2"
            ]
        },
        {
            "id": "129591",
            "valuesIds": [
                "129591_64",
                "129591_1",
                "129591_2"
            ]
        },
        {
            "id": "127415",
            "valuesIds": [
                "127415_708165"
            ]
        },
        {
            "id": "215858",
            "values": [
                "2760AGSCMVZ"
            ]
        },
        {
            "id": "214434",
            "valuesIds": [
                "214434_266990"
            ]
        },
        {
            "id": "232713",
            "valuesIds": [
                "232713_368433"
            ]
        },
        {
            "id": "232501",
            "valuesIds": [
                "232501_4",
                "232501_16"
            ]
        }
    ],
    "payments": {
        "invoice": "VAT"
    },
    "name": "TEST",
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": 150,
            "currency": "PLN"
        }
    },
    "location": {
        "city": "WARSZAWA",
        "countryCode": "PL",
        "postCode": "00-200",
        "province": "MAZOWIECKIE"
    },
    "images": [
        {
            "url": "https:\/\/a.allegroimg.com\/original\/118e8e\/1dc0afd648c38764ba8aaf37733c"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/113e50\/26ba99bd4db08f36c081d32511c4"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11bd91\/3864db4b4ba0850ae81c600a2e80"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/119979\/957a7ca443e88a46e221583bc165"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/116b18\/551cce6b4331a576e5e4c845306e"
        }
    ],
    "product": {
        "id": "1de86769-8bf6-4774-89dc-83940c32091d"
    },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h1>SZYBA PRZEDNIA DO AUTA"
                    }
                ]
            },
           
        ]
    },
    "external": {
        "id": "B76959"
    },
    "tax": {
        "percentage": "23.00",
        "rate": "23.00"
    },
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "2eaa8d18-7120-47e0-b45f-254cfa89d1b0"
        },
        "returnPolicy": {
            "id": "86f49dcd-f4f6-4a95-97ca-9873a351312e"
        },
        "warranty": {
            "id": "b66aabf1-bb5b-4b0a-a500-9b658ed67ec0"
        }
    },
    "publication": {
        "status": "INACTIVE"
    }
}

**Comment by michal20111** [comment]
nawet jak mam id z katalogu to mam że żadanie błędne {
    "b2b": {
        "buyableOnlyByBusiness": false
    },
    "delivery": {
        "handlingTime": "PT24H",
        "shippingRates": {
            "id": "25c4bdc5-e5df-4bbb-859b-0195faa91345"
        },
        "additionalInfo": ""
    },
    "stock": {
        "available": 1,
        "unit": "UNIT"
    },
    "language": "pl-PL",
    "category": {
        "id": 18719
    },
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_2"
            ]
        },
        {
            "id": "129591",
            "valuesIds": [
                "129591_64",
                "129591_1",
                "129591_2"
            ]
        },
        {
            "id": "127415",
            "valuesIds": [
                "127415_708165"
            ]
        },
        {
            "id": "215858",
            "values": [
                "2760AGSCMVZ"
            ]
        },
        {
            "id": "214434",
            "valuesIds": [
                "214434_266990"
            ]
        },
        {
            "id": "232713",
            "valuesIds": [
                "232713_368433"
            ]
        },
        {
            "id": "232501",
            "valuesIds": [
                "232501_4",
                "232501_16"
            ]
        }
    ],
    "payments": {
        "invoice": "VAT"
    },
    "name": "TEST",
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": 150,
            "currency": "PLN"
        }
    },
    "location": {
        "city": "WARSZAWA",
        "countryCode": "PL",
        "postCode": "00-200",
        "province": "MAZOWIECKIE"
    },
    "images": [
        {
            "url": "https:\/\/a.allegroimg.com\/original\/118e8e\/1dc0afd648c38764ba8aaf37733c"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/113e50\/26ba99bd4db08f36c081d32511c4"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11bd91\/3864db4b4ba0850ae81c600a2e80"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/119979\/957a7ca443e88a46e221583bc165"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/116b18\/551cce6b4331a576e5e4c845306e"
        }
    ],
    "product": {
        "id": "1de86769-8bf6-4774-89dc-83940c32091d"
    },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "SZYBA PRZEDNIA DO AUTA"
                    }
                ]
            },
           
        ]
    },
    "external": {
        "id": "B76959"
    },
    "tax": {
        "percentage": "23.00",
        "rate": "23.00"
    },
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "2eaa8d18-7120-47e0-b45f-254cfa89d1b0"
        },
        "returnPolicy": {
            "id": "86f49dcd-f4f6-4a95-97ca-9873a351312e"
        },
        "warranty": {
            "id": "b66aabf1-bb5b-4b0a-a500-9b658ed67ec0"
        }
    },
    "publication": {
        "status": "INACTIVE"
    }
}

**Comment by Lukasz-Zurek** [comment]
@michal20111 Zgodnie z [odpowiedzią w innym wątku](https://github.com/allegro/allegro-api/issues/8286#issuecomment-1894996035), przekazujesz nieprawidłową strukturę oferty, m.in. bez obiektu "productSet". Dodatkowo upewnij się co do wymagalności parametrów potrzebnych do utworzenia produktu.
