### ISSUE TITLE
Brak EAN produktu dla order/checkout-forms

### ISSUE THREAD

**Issue by krzwaw83** [allegro/allegro-api#8276]
Przy wywołaniu `order/checkout-forms` nie dostajemy dla konta 3a6e5350-b392-11ee-bf46-bb565b513962 EANów produktów. EANy są przypisane do produktu, ale w API nie przychodzą. Sprawdzaliśmy uprawnienia w ustawieniach Allegro i wygląda, że wszystko jest tak jak powinno. Co może być powodem braku zwracania EANów ?

**Comment by krzwaw83** [comment]
Błąd w opisie, chodzi numer konta, nie aukcji - poprawiłem.

**Comment by PrzemyslawLukanowski** [comment]
W ramach zasobu do pobierania zamówień `order/checkout-forms`, zgodnie z założeniami, nie zwracamy pola z wartością EAN. Nie tylko dla wskazanego zamówienia, ale dla wszystkim ogółem. Jeśli masz na myśli inne pole, które występuje w innych zamówieniach, ale w tym nie, doprecyzuj proszę zgłoszenie.
