### ISSUE TITLE
Problem z pobieraniem aktywności wszystkich aukcji /sale/offer-events

### ISSUE THREAD

**Issue by igornizio** [allegro/allegro-api#8277]
Czy wycofaliście opcję /sale/offer-events, aby obserwować statusy związane z aktywnością aukcji co pozwala nam na analizy.
Czy jest takaś alternatywa? Ostatnie dane zostały pobrane 10h temu

Zapytanie: https://api.allegro.pl/sale/offer-events?limit=1000&type=OFFER_BID_PLACED
Odpowiedź: Something went wrong: 403 Resource id #18

**Comment by MartaNowaczyk** [comment]
Zasób działa i nie planujemy go usuwać.
Sprawdź czy czasem nie użyłeś autoryzacji typu client_credentials, która nie posiada kontekstu użytkownika. Aby skorzystać z tego zasobu musisz wygenerować token za pomocą autoryzacji [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow).

**Comment by igornizio** [comment]
Autoryzacja jest przez code, funkcja nagle przestała działać i wyrzucać błąd
moje zapytanie:
    $headers = array("Authorization: Bearer {$token}", "Accept: application/vnd.allegro.public.v1+json", "Content-Type: application/vnd.allegro.public.v1+json");
    $url = "https://api.allegro.pl/sale/offer-events?limit=1000&type=OFFER_BID_PLACED"; 
    $ch = getCurl($headers, $url);
    $mainCategoriesResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($mainCategoriesResult === false || $resultCode !== 200) {
				exit ("Something went wrong:  $resultCode $tokenResult");
    }
    $categoriesList = json_decode($mainCategoriesResult);
    return $categoriesList;

**Comment by MartaNowaczyk** [comment]
Podaj proszę trace-id dla tego przypadku, żebym mogła sprawdzić co tam pod spodem do nas przesyłasz.
