### ISSUE TITLE
Unable to create a listing with API - error is vague

### ISSUE THREAD

**Issue by manweCZ** [allegro/allegro-api#8278]
Hello,
im trying to connect our client's shop with Allegro.cz to enable listings of client's products on Allegro, however when I try to add offer by calling /sale/product-offers endpoint with data below, i get vague error:
(
                    [code] => JsonMappingException
                    [message] => Message is not readable.
                    [details] => 
                    [path] => productSet
                    [userMessage] => Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji.
                )

I have no idea what's missing or what's wrong. I've been looking into the docs for couple of hours now and there is zero information as to which fields are required, so Im just left with trial and error approach (ie. according to the docs, only "stock" is required). Thank you for your help.

data i am sending is below: (ill try to format it if possible)

{
   "productSet":{
      "product":{
         "id":"4003198856660",
         "idType":"GTIN",
         "images":[
            "https:\/\/www.kalia.cz\/images\/products\/CIRF10C_open.jpg",
            "https:\/\/www.kalia.cz\/images\/products\/CIRF10C_wrapping_back.jpg"
         ],
         "category":{
            "id":"256342"
         },
         "parameters":[
            {
               "id":"11323",
               "valuesIds":[
                  "11323_1"
               ]
            },
            {
               "id":"130389",
               "values":[
                  1
               ]
            },
            {
               "id":"130390",
               "valuesIds":[
                  "130390_5"
               ]
            },
            {
               "id":"225693",
               "values":[
                  "4003198856660"
               ]
            },
            {
               "id":"248928",
               "valuesIds":[
                  "248928_1681708"
               ]
            }
         ]
      },
      "quantity":{
         "value":1
      }
   },
   "afterSalesServices":{
      "impliedWarranty":{
         "id":"d8f68c08-b22a-4b48-b082-a6a8c8c13738"
      },
      "returnPolicy":{
         "id":"658b8b9a-7e41-41c7-acc5-c23c1f60df57"
      }
   },
   "external":{
      "id":"CI-RF-10C"
   },
   "name":"Tombow Irojiten sada pastelek 10ks - Volume 8 - Fluorescence I",
   "language":"cs-CZ",
   "stock":{
      "available":34,
      "unit":"UNIT"
   },
   "sellingMode":{
      "format":"BUY_NOW",
      "price":{
         "amount":362.88,
         "currency":"CZK"
      }
   }
}

**Comment by MartaNowaczyk** [comment]
There is an error because, the structure for `productSet` is incorrect. It should be an array of objects
```
"productSet": [
{ ... }
],
```

**Comment by manweCZ** [comment]
@MartaNowaczyk wow, thats a stupid mistake on my part, thank you :)
