### ISSUE TITLE
Brakujące produkty TecDoc marki AS-PL

### ISSUE THREAD

**Issue by PunktAutoCzesci** [allegro/allegro-api#8280]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Cześć,
poniżej lista produktów TecDoc marki AS-PL których brakuje w bazie produktów. 
`/sale/products`
Proszę o informację po ich dodaniu. 

ABE9006(NACHI)
ABE9069S
ABE9032(NTN)
ABE9031
ABE9044
ABE9003(SKF)
ABE9050
ABE9046(INA)
ABE9039(KOYO)
ABE9001
ABE9032
ABE9016(NSK)
ABE9196
ARE2009(OEM)
ABE9045
ABE9046
ABE9020
ABE9015
ABE9077(NSK)
ABE9195(SKF)
ARE2008(OEM)
ARE0002(OEM)
ABE9021(BULK)
ABE9007(NSK)
ABE9014(NSK)
ABE9088(KOYO)
ARS0095(BOSCH)
ABE9004(NACHI)
ABE9238(NACHI)
ABE9239(NACHI)
ABE9241(NSK)
ABE9242(NSK)
ABE9039(NSK)
ABE9067(INA)
ABE9118(WTW)
ABE9101(INA)
ABE9028(NTN)
ABE9080(INA)
ABE9045(INA)
ABE9120(INA)
ABE9033(INA)
ABE9047
AT0006
ABE9019(NTN)
ABE9005(SKF)
ABE9019(SKF)
ABE9199(NSK)
BX220(IKA)
ABE9002(SKF)
ABE9018(FAG)(BULK)
ABE9075(INA)
ABE9001(SKF)
ABE9162(KBC)
ABE9042(SKF)
ABE9156(NTN)
ABE9021(SKF)
ABE9150(SKF)
ABE9038(SKF)
ABE9186(SKF)
ABE9010(SKF)
ABE9020(FAG)
ABE9080S
ABE9045(KOYO)(BULK)
ABE9028(NSK)
ABE9129(NSK)
ABE9107(SKF)
ABE9049(NACHI)
ABE9240(NACHI)
ABE9018(KOYO)
ABE9002(NACHI)
ABE9003(NACHI)
ABE9021(NACHI)
ABE9003(KOYO)
ABE9085(KOYO)
ARE0003(OEM)
ARE4005(OEM)
ABE9001(NSK)
ABE9066(KOYO)
ABE9005(NTN)
ABE9196(BULK)
ABE9035(SKF)
ABE9176
ARE5007(OEM)
ABE9002(NSK)
ZS0002
ABE9006(FAG)
ABE9004(FAG)(BULK)
ABE9004(FAG)
ABE9003(NSK)(BULK)
ABE9014
ABE9040(NSK)
ARE0001(OEM)
ARE4003(OEM)
ABE9027
ABE9030
ABE9007
ABE9229S
ARE0011(OEM)
ABE9043
ABE9029
ABE9004
ABE9021
ABE9004(NSK)
ABE9016
ABE9034
ABE9017
ABE9006
ABE9018
ABE9044(NSK)
ABE9006(BULK)
ABE9002(NTN)
ABE9030(BULK)
ABE9005
ABE9008
ABE9107(NTN)
ABE9009
ABE9006(NSK)
ARE0007(OEM)
ARE4004(OEM)
ABE9024
ABE9006(NSK)(BULK)
ABE9062
ZS0005
P2002
RTP9006S
MP0022
ABE9006(SKF)
ABE9003(FAG)
ABE9207S
ABE9050(SKF)
ABE9136(INA)
ABE9200(NSK)
ABE9061(SKF)
ABE9007(SKF)
ABE9004(KOYO)
ABE9021(KOYO)
CBE9002(NSK)
ABE9177
BX204(IKA)
ABE9005(NSK)
ABE9020(NTN)
ABE9051(SKF)
ABE9201(NSK)
ABE9204(KOYO)
ABE9040(SKF)
ABE9006(SKF)(BULK)
SBH0097(IKA)
ABE9001(NTN)(BULK)
ABE9005(NTN)(BULK)
ABE9030(NSK)
160.504.092.080
BSX74(IKA)
ABE9045(BULK)
ABE9026(BULK)
ABE9025(BULK)
ABE9024(BULK)
ABE9021(NTN)(BULK)
ABE9020(NTN)(BULK)
ABE9020(BULK)
ABE9019(NTN)(BULK)
ABE9019(BULK)
ABE9018(NTN)(BULK)
ABE9018(BULK)
ABE9015(BULK)
ABE9010(NSK)(BULK)
ABE9010(BULK)
ABE9007(BULK)
ABE9005(BULK)
ABE9004(BULK)
ABE9003(NTN)(BULK)
ABE9002(NTN)(BULK)
ABE9001(NSK)(BULK)
ABE9035(NSK)
ABE9004(NTN)
ABE9034(NTN)
ABE9006(FAG)(BULK)
BSX172-173(IKA)
M0006
MP0008
ABE9019(NSK)
ABE9038(NSK)
ABE9021(NSK)
ABE9002(NSK)(BULK)
ABE9039(SKF)
ABE9069(INA)
ABE9036
ABE9066(NTN)
ABE9006(NTN)
ABE9021(NSK)(BULK)
ABE9034(NSK)
ABE9038(NTN)
ABE9026
ABE9085(INA)
ABE9001(BULK)
ABE9047(NSK)
ABE9004(NSK)(BULK)
ABE9020(NSK)
ABE9059(NSK)
ABE9060(NSK)
ABE9003(NTN)
ABE9042(NSK)
ABE9018(NTN)
ABE9027(NTN)
ABE9025(NTN)
ABE9004(NTN)(BULK)
ABE9003(BULK)
ABE9058(NSK)
ABE9010(NSK)
ABE9016(BULK)
ABE9061(NSK)
ABE9090(INA)
ABE9018(FAG)
ABE9001(NTN)
RTP9007S
LASX15-16(IKA)
MP0007
MP0017
SS0017(OEM)
ABE9176(NSK)
ABE9099(INA)
911-980
ABE9073(KOYO)
ARE0005(OEM)
SBU9086(BULK2)
BX213(IKA)
BX215(IKA)
ABE9190(SKF)
ABE9094(KOYO)
MP0015
ABE9024(NSK)
ABE9210(SKF)
S1186
ABE9004(SKF)
ABE9017(KOYO)
ABE9174(NSK)
ABE9065(INA)
ARS2035S
ABE9007(NTN)
ABE9078(NSK)
ABE9054(NSK)
ABE9087(NTN)
ABE9166(NTN)
ABE9053(NSK)
ABE9006(KOYO)
ABE9205S
ABE9009(INA)
ABE9072(INA)
ABE9083(INA)
ABE9051(NSK)
ABE9102(NSK)
ABE9033(NSK)
ABE9071(INA)
ABE9068(INA)
ABE9070(INA)
ABE9095(NTN)
ABE9008(NSK)
ABE9202(NSK)
SS0004(OEM)
LAX82(IKA)
ABE9018(NSK)
ABE9065
ABE9019
ABE9028
ABE9015(NSK)
ABE9049(NTN)
ABE9003
ABE9050(NTN)
ABE9139(NTN)
ARE0019(OEM)
ABE9006(NTN)(BULK)
ABE9003(NSK)
ABE9035
ABE9036(NSK)
ARE0006(OEM)
ABE9021(NTN)
ABE9010
ABE9025
ABE9002(FAG)
P2001
ABE9002

**Comment by Lukasz-Zurek** [comment]
@PunktAutoCzesci Dziękuję za kolejne przykłady, które przekazałem już do odpowiedniego zespołu do dalszej weryfikacji.

**Comment by PunktAutoCzesci** [comment]
Czy jest jakaś informacja zwrotna?

**Comment by Lukasz-Zurek** [comment]
Mieliśmy wcześniej problemy dotyczące błędu "TecdocSpecificationNotFound", w przypadku którego wszystkie znalezione przez nas problematyczne przypadki zostały poprawione, o czym poinformowałem w tym [wątku](https://github.com/allegro/allegro-api/issues/8271#issuecomment-1899835618).

Wskazane produkty marki AS-PL, ale również ESEN SKV (wymienione w [wątku](https://github.com/allegro/allegro-api/issues/8248)) oraz DR.MOTOR (wymienione w [wątku](https://github.com/allegro/allegro-api/issues/8305)) - są dostępne w naszym katalogu i można je znaleźć za pomocą GET /sale/products. Jednakże część tych produktów nie otrzymało TecDoc z powodu braku przemapowania produktu z TecDoc. Problem ten jest niestety nadal weryfikowany. Przypomniałem się zespołowi, który się tym zajmuje.

Oczywiście może się zdarzyć, że część produktów nie posiada specyfikacji TecDoc. Są to np. produkty utworzone przez sprzedających. Druga kwestia jest taka, że posiadamy bazę od TecDoc, ale to nie oznacza, że mamy wszystkie produkty z TecDoca w naszej bazie produktów. Część z nich nie ma, bo mamy np. zaimportowaną wcześniejszą wersję TecDoc, lub nie zostały odpowiednio przemapowane j.w.
