### ISSUE TITLE
Zamawianie podjazdu DPD

### ISSUE THREAD

**Issue by allegrofan** [allegro/allegro-api#8283]
Od kilku dni jest problem z zamówieniem podjazdu kuriera DPD.

https://api.allegro.pl/parcel-management/pickup-date-proposals?parcelId='.$parcelid.'&readyDate='.$data.'

$data to dzisiaj 2024-01-16
$parcelid to przesyłka np: efa837e9-dc91-44a8-a0ab-51a501553f7f

W odpowiedzi nie otrzymuję proponowanych godzin odbioru od do.
Bez godzin otrzymuję komunikat Array ( [errors] => Array ( [0] => Array ( [code] => INTERNAL_SERVER_ERROR [message] => Internal server error. [details] => [path] => [userMessage] => Internal server error. Try again in a few minutes. ) ) ) 

po wywołaniu: https://api.allegro.pl/parcel-management/parcel-pickup-request-commands/'.$UUID.'', 'PUT', $data

 $data[parcelIds]=array($parcelid);
      $data[pickupDate][date] = $datanow;
      $data[pickupDate][minTime] = $minTime;
      $data[pickupDate][maxTime] = $maxTime;

**Comment by Lukasz-Zurek** [comment]
@allegrofan Potwierdzam błąd. Wyjaśniamy z zespołem odpowiedzialnym za usługę.

**Comment by Lukasz-Zurek** [comment]
@allegrofan W żądaniu nie wskazałeś wartości w polach:  **"minTime"** i **"maxTime"** (w obu przypadkach przesłałeś **null**). Powinniśmy jednak zwrócić czytelny błąd, natomiast tak jak napisałeś - zwróciliśmy błąd 500 i tu mogę już zapewnić, że zespół odpowiedzialny za "Wysyłam z Allegro" pracuje nad poprawką.

Przepraszamy za zaistniałe utrudnienia.

**Comment by Lukasz-Zurek** [comment]
@allegrofan Zweryfikujemy tę sprawę.

**Comment by Lukasz-Zurek** [comment]
@allegrofan Tak. Dodam, że niektórzy przewoźnicy nie zwracają nam proponowanych godzin odbioru.

Chciałbym również poinformować, że błąd dotyczący zwracanego przez nas błędu 500 (Internal server error) został poprawiony i powinniśmy już zwracać czytelny komunikat.

Przepraszamy za zaistniałe utrudnienia.
