### ISSUE TITLE
Ustawienie "Opcje wystawienia Pakiet ogłoszeniowy" w json przy tworzeniu oferty

### ISSUE THREAD

**Issue by MGabala** [allegro/allegro-api#8284]
Dzień dobry,

Pracuje nad integracją z allegro i aktualnie opracowałem metodę która dodaje nam ogłoszenie na allegro, ale został ostatni krok, czyli dodanie w json informacji na temat:

![obraz](https://github.com/allegro/allegro-api/assets/82496006/46f05cb3-7956-49af-9adb-f6246880babc)

obecnie dostajemy taką zwrotkę:

```
    "validation": {
        "errors": [
            {
                "code": "ConstraintViolationException.ValidAdvertisementPackage",
                "message": "The classifieds package is not associated with the offer, or the category does not match the package.",
                "details": "ConstraintViolationException.ValidAdvertisementPackage",
                "path": "sellingMode",
                "userMessage": "Pakiet ogłoszeniowy nie jest przypisany do oferty lub kategoria nie pasuje do pakietu."
            }
        ],
        "warnings": [],
        "validatedAt": "2024-01-16T17:55:19.284Z"
    }
    ```
i ogłoszenie dodaje się jako szkic.

Czy można prosić o wskazówkę dotyczącą tego elementu?

**Comment by MartaNowaczyk** [comment]
Zgodnie z komunikatem błędu - w ofercie brakuje pakietu ogłoszeniowego, który należy do niej przypisać. Opisaliśmy ten krok w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-wystawic-i-zarzadzac-ogloszeniem-K6r3Z47dKcy#pakiet-i-opcje-dodatkowe).
