### ISSUE TITLE
 Redirect URI mismatch

### ISSUE THREAD

**Issue by TihomirS** [allegro/allegro-api#8285]
Hi,

I get Authorization Code on https://st.mercoria.com/channels/allegro?code=2h5s1eyxldmSbCdV5oW9TommGrhfd6KR&state=67
and https://st.mercoria.com/channels/allegro is on REDIRECT URIS

On the next step after the granting token, I want to be redirected to https://st.mercoria.com/channels/edit?id=67
and put https://st.mercoria.com/channels/edit on REDIRECT URIS

but I get this: Array ( [error] => invalid_grant [error_description] => Redirect URI mismatch. ) 

Any ideas?

Best wishes,
Tihomir

**Comment by MartaNowaczyk** [comment]
During the authorization process (in both steps) you should use the same redirect_uri - one registered on Developer Apps.

**Comment by TihomirS** [comment]
hmm .. why do I have options for multiple in REDIRECT URIS...

**Comment by TihomirS** [comment]
sorry to reopen,
I changed my logic and now I use only one redirect_uri and https://st.mercoria.com/channels/allegro is on REDIRECT URIS

but on the second step, I receive:
The requested URL returned error: 400

**Comment by MartaNowaczyk** [comment]
Please provide us with the details of your call - full request and response in JSON format. For data security, send them via the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) with a note that it concerns GitHub - thread #8285

**Comment by TihomirS** [comment]
Hi,

I sent details yesterday 17.01 with  case number "39566519" ref:!00D240aE05.!500Ti03zVd4:ref
just want to inform you here too :)

T.

**Comment by MartaNowaczyk** [comment]
I still haven't received this report, can you write in the same thread asking for it to be forwarded to API support? It's best to provide a current example if the problem still occurs, because some time has passed and logs may be incomplete.

**Comment by TihomirS** [comment]
Hi,

the situation is the same.
I created a new request and sent all data in JSON via the contact form again:

We have received your case number "39757851" ref:!00D240aE05.!500Ti04RdMS:ref

**Comment by MartaNowaczyk** [comment]
I got the data from your message and there is a problem with redirect_uri again. It looks like you didn't send the same redirect_uri as in the first authorization code request. The redirect_uri must be the same in both cases. In the message I only have a request for a token, can you also send me what you send in the first request for an authorization code?

**Comment by TihomirS** [comment]
Hi,

My first link is:
https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=1214de3e415b4315b3c45e4c84cf5f59&redirect_uri=https://st.mercoria.com/channels/allegro&prompt=confirm&state=67

I change my code to use only https://st.mercoria.com/channels/allegro and pass different get params to it.

T.

**Comment by MartaNowaczyk** [comment]
Hi, redirect_uri should be the same in the first and second call. If you add a parameter, it should be the same in both.

**Comment by TihomirS** [comment]
??!
hmm, this is params, not the address it self... I need to use them if 2 URI must be the same... 
will try to find a workaround...

**Comment by TihomirS** [comment]
If I use it clearly - https://st.mercoria.com/channels/allegro
but pass the value on &state you will be sent it to my first address with GET .. so the URI will not be the same again?!

**Comment by TihomirS** [comment]
OK, 
I change my code and finaly get token :)

Thanks!
