### ISSUE TITLE
Próba zmiany ceny zwraca MissingRequiredParameters

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#8287]
Próbuję zmienić cenę oraz ilość sztuk, przy pomocy PATCH https://api.allegro.pl/sale/product-offers/13917442961. W body przekazuję:
 [sellingMode] => Array ( [price] => Array ( [amount] => 14.75 [currency] => PLN ) ) [stock] => Array ( [available] => 25 [unit] => UNIT )

W odpowiedzi dostaję:
stdClass Object ( [code] => ConstraintViolationException.MissingRequiredParameters [message] => Missing required parameters: 215997, 216029 [details] => ConstraintViolationException.MissingRequiredParameters [path] => parameters [userMessage] => Uzupełnij parametry obowiązkowe: Kolor, Materiał dominujący. )

W/g dokumentacji, w przypadku nie przekazania wszystkich pól, powinny one zostać złożone z bieżących danych oferty oraz produktu. Zgaduję, że w/w pola stały się wymagane gdzieś w międzyczasie, gdy oferta była już aktywna i dlatego w momencie zapisu oferty nie przechodzi ona walidacji po stronie serwera.
Jest moje przypuszczenia są słuszne, to jest to o tyle kłopotliwe, że w zasadzie nie można "szybko przemielić" wszystkich ofert, żeby zaktualizować stany magazynowe i ceny, tylko za każdym razem złożyć całą ofertę, analogicznie jak w przypadku starej metody sale/offers.

**Comment by MartaNowaczyk** [comment]
Tak jak piszesz, jeśli w parametrach nastąpiły zmiany, to musisz je uzupełnić, bo jest jeszcze walidacja przy zmianie ceny. Sama zmiana stanu magazynowego powinna przejść bez walidacji parametrów. Pracujemy nad tym, aby zmiana ceny działała, tak jak zmiana stocku, ale to na pewno nie nastąpi w tym kwartale.

**Comment by rasskabak** [comment]
Sam stock GENERALNIE działa. Generalnie - ponieważ mimo wszystko wyrzuca błąd, jeśli oferta nie ma podanego prawidłowego kodu EAN.

**Comment by rasskabak** [comment]
A jednak nie do końca...

PATCH https://api.allegro.pl/sale/product-offers/13198834674
Body: Array ( [stock] => Array ( [available] => 137 [unit] => SET ) )

Response: (trace-id fbe6506a08cc37e4)
{"errors":[{"code":"ConstraintViolationException.MissingRequiredParameters","message":"Missing required parameters: 11323, 248928, 220893, 129129, 224017","details":"ConstraintViolationException.MissingRequiredParameters","path":"parameters","userMessage":"Uzupełnij parametry obowiązkowe: Stan, Marka, Kolor dominujący, Motyw, Kod producenta."}]}

**Comment by MartaNowaczyk** [comment]
Spróbuj bez pola "unit" powinno przejść.

**Comment by rasskabak** [comment]
Faktycznie, przeszło :)

**Comment by rasskabak** [comment]
Temat wrócił.
Próbuję zmienić cenę w aktywnej ofercie, bez ruszania innych pól. W odpowiedzi otrzymuję informację o brakujących parametrach. Jest to produkt z kategorii, którą jakiś czas temu łączyliście z inną kategorią, więc tego typu ofert nagle zrobiło się kilkaset, jeśli nie tysiąc. W tej sytuacji uzupełnianie nowych parametrów potrwa pewnie z miesiąc, a cenę musimy zmienić "na już".

PATCH https://api.allegro.pl/sale/product-offers/14559213037
Body: Array ( [sellingMode] => Array ( [price] => Array ( [amount] => 6.34 [currency] => PLN ) ) )
trace-id: 6e273070cfd91199 
Response: {"errors":[{"code":"ConstraintViolationException.MissingRequiredParameters","message":"Missing required parameters: 249685, 215949, 127812","details":"ConstraintViolationException.MissingRequiredParameters","path":"parameters","userMessage":"Uzupełnij parametry obowiązkowe: Rodzaj, Liczba sztuk, Marka.","metadata":{}}]}

**Comment by MartaNowaczyk** [comment]
Rozumiem, jednak na ten moment przy zmianie ceny nadal sprawdzamy parametry. Pracujemy nad tym by to zmienić, jednak nie mamy niestety konkretnej daty wdrożenia.

**Comment by rasskabak** [comment]
Weszły nowe endpointy, dzięki którym miała być możliwość zmiany poszczególnych pól w ofercie, po czym okazuje się, że i tak trzeba wypełnić praktycznie całą strukturę, bo inaczej system w którymś miejscu i tak rzuci błędem. Pół biedy, gdyby dotyczyło to próby wystawienia nowego produktu - oferta po prostu by się nie wystawiła i trzeba by było ustawić odpowiednio wszystkie pola.
Tu natomiast mamy do czynienia z ofertami które weszły na Allegro, potem zostały przeniesione do innej kategorii, pojawiły się dla nich nowe wymagane parametry i teraz nie możemy zaktualizować ceny. A takich ofert mamy w tej chwili około 2000. I teraz możemy albo sprzedawać je po starej cenie, licząc, że przynajmniej część z nich nie będzie poniżej kosztów zakupu. Albo wyłączyć połowę ofert, przeklikać wszystko ręcznie, a potem liczyć, że za pół roku znowu nie polecą do innej kategorii i sytuacja się powtórzy.
Jeśli potrzebuję pracownika na pół etatu, który będzie zajmował się ręczną aktualizacją ofert, to korzystanie z API trochę mija się z celem.

**Comment by MartaNowaczyk** [comment]
Rozumiem, przekazałam Twoją opinię do zespołu, który się tym zajmuje. Gdybędę miała jakieś konkretne informacje w tym temacie dam znać.
