### ISSUE TITLE
Problem z zamówieniem podjazdu Allegro One

### ISSUE THREAD

**Issue by Moro-PL** [allegro/allegro-api#8288]
W baselinker podczas zamówienia kuriera dla Allegro One dostaję komunikat

Błąd zewnętrznego przewoźnika (BAD_REQUEST ) Data: 2024-01-17. Godzina odbioru od: 08:03. Godzina odbioru do: 15:00 Data: 2024-01-18. Godzina odbioru od: 08:00. Godzina odbioru do: 15:00 Data: 2024-01-19. Godzina odbioru od: 08:00. Godzina odbioru do: 15:00 (#PC5)

o co może chodzić?

Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by MartaNowaczyk** [comment]
Komunikaty błędów widoczne w Baselinkerze powinny być najpierw konsultowane z ich obsługą, która powinna zweryfikować problem, a jeśli stwierdzą, że błąd jest po stronie allegro, powinni się z nami skontaktować i przesłać odpowiednie dane do weryfikacji.
W tym momencie po samym komunikacie mogę tylko powiedzieć, że mogła być podana błędna godzina podjazdu. 
Nie wiem jednak co jest do nas przesyłane, więc abym mogła to zweryfikować potrzebuję danych, które uzyskasz od Baselinkera. Potrzebne są trace-id lub commandId dla tego przypadku.
