### ISSUE TITLE
Błąd 403 w 'shipment-management/shipments/create-commands'

### ISSUE THREAD

**Issue by lasoczczyk** [allegro/allegro-api#8289]
Dzień dobry

Próbuję na środowisku testowym utworzyć przesyłki allegro za pomocą:
'shipment-management/shipments/create-commands'.

Dodałem do upranień tworzenie przesyłek w /apps.developer.allegro.pl.allegrosandbox.pl/

Inne funkcje działają (np pobranie kategorii), natomiast tworzenie paczki wyrzuca 
403: Access is denied, No access to the specified resource.

Podaję trace-id: 13730e0d4bf1d8ca

Proszę o sprawdzenie i pomoc.

**Comment by Lukasz-Zurek** [comment]
Z tego co widzę w logach - brakuje scope'a **allegro:api:shipments:write**.

**Comment by lasoczczyk** [comment]
OK już wiem od czego.
Token dostępowy był wygenerowany przed zaznaczeniem allegro:api:shipments:write
Po wygenerowaniu tokena na nowo - zaczęło działać.
Dziękuję. Mozna zamnkąć.

**Comment by lasoczczyk** [comment]
Jeżeli jeszcze mogę kontynuować z innym problemem...
Jaki e-mail testowy można podać w środowisku testowym, żeby przeszło dalej.

Aktualnie mam błąd:
[status] => ERROR 
[code] => SERVICE_NOT_AVAILABLE 
[message] => Requested hashed mail was not recognized 
[details] => Requested hashed mail was not recognized 
[path] => receiver.email 
[userMessage] => Podany hash-mail jest niepoprawny

A podałem realny e-mail klienta maskowany.

**Comment by lasoczczyk** [comment]
@Lukasz-Zurek utknąłem :( Zerknij proszę na wiadomość wyżej.

**Comment by Lukasz-Zurek** [comment]
@lasoczczyk Czy przekazałeś faktyczny maskowany e-mail klienta z istniejącego na sandboxie zamówienia? Adres posiada domenę @allegromail.pl, który należy do produkcji. Natomiast na środowisku testowym adresy mailowe są w domenie user.allegrogroup.pl

**Comment by lasoczczyk** [comment]
Przekazałem prawdziwy ale ze srodowiska produkcyjnego.... podmieniłem koncówkę i liczyłem że to zadziała :)

OK już wiem zatem co muszę zrobić.... założę drugie konto testowe, złożę zamówienie i posłużę się tym mailem.
Dzięki.

**Comment by lasoczczyk** [comment]
Zrobiłem tak jak mówiłem powyżej.
Załozyłem konto, złozyłem zamowienie i dodałem paczkę.
Tworzę paczkę i niestety zwraca mi błąd - próbowałem już kilka razy i nie wiem, o co chodzi...
"Wybrana metoda dostawy nie obsługuje tego zamówienia" Moze pod "command Id" bedziersz mogl podejrzec.

Id zamówienia: 025f1690-b53e-11ee-8d74-d1c3fda4d60b
Command ID: 770ce723-4f55-4214-870d-9d71a76fbfa8
DeliveryMethodId => 08c15d0b-9b24-4b3f-89a8-7a2b502abe55
Receiver->point => A004503
email: ej3lp2dk5n+2ca4a9893@user.allegrogroup.pl

I znów utknąłem... :P

**Comment by Lukasz-Zurek** [comment]
@lasoczczyk Dla wskazanego zamówienia zwróciliśmy inny adres mailowy Kupującego. W żądaniu dotyczącym utworzenia nowej przesyłki, w polu **"receiver.email"** przekazujesz innego maila.

**Comment by lasoczczyk** [comment]
Eh juz chyba zmęczony jestem faktycznie. Poszło dalej.
Ok to teraz tylko pobranie etykiety :)
Dzięki wielkie.

**Comment by lasoczczyk** [comment]
OK udało się, dostałem etykietę ale wygląda tak jak w załączniku - czy to poprawna testowa etykieta?

I w zasadzie to zaznaczyłem EPL a wyszedł PDF...

[allegro_123136.pdf](https://github.com/allegro/allegro-api/files/13973408/allegro_123136.pdf)

**Comment by Lukasz-Zurek** [comment]
@lasoczczyk To prawidłowa etykieta na środowisku testowym. Musiałeś na samym początku, podczas tworzenia paczki - zdefiniować PDF, stąd zaistniała sytuacja.

**Comment by Lukasz-Zurek** [comment]
Potwierdzam - nie jest to błąd. Na produkcji uzyskasz już normalną etykietę.
