### ISSUE TITLE
[sandbox] DoGetSellFormFieldsForCategory nie zwraca atrybutów specyficznych

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#829]
Sprawdzone na kilku losowo wybranych kategoriach, zwracane są tylko podstawowe pola, fidy do 350. Kolejnych nie ma i nie da się przez to wystawić aukcji - brak pól wymaganych.

**Comment by MartaNowaczyk** [comment]
@Onixarts Sprawdziłam na kategorii 1488 (Nesesery i aktówki) i dostaję fidy większe niż 350. Czy problem u Ciebie dalej występuje? Jeśli tak podeślij proszę przez nasz [formularz kontaktowy ](https://allegro.pl/pomoc/kontakt#subjectId=7e8e35b6-d773-4a0a-8d38-c056148165e8)pełnego cURL-a z błędnymi informacjam i napisz, że to zgłoszenie na GitHubie #829. Sprawdzimy w czym jest problem.

**Comment by Onixarts** [comment]
Już działa, dziękuję.
