### ISSUE TITLE
Wznowienie oferty brak błędu oraz brak aktualizacji na allegro PATCH /sale/product-offers

### ISSUE THREAD

**Issue by Eryk1997** [allegro/allegro-api#8290]
Próbuję wznowić ofertę, która spełnia wymagania. 
przesyłam request do /sale/product-offers
 https://developer.allegro.pl/documentation#operation/editProductOffers
 Nie otrzymuję błędów i aukcja na allegro nie zmienia swojego statusu.

**Comment by Lukasz-Zurek** [comment]
Z logów wynika, że zwróciliśmy błąd 422 - brak obowiązkowego parametru "Marka" (129369).

**Comment by Eryk1997** [comment]
Super dziękuję za pomoc.

**Comment by Eryk1997** [comment]
@Lukasz-Zurek Ale wydaje mi się, że jak przesyłam aktualizację statusu to nie powinno wyrzucać błędu odnośnie Marki 

np: 
"publication": {
         "status": "ACTIVE"
     }
     
     według dokumentacji przykład: 
     
      curl -X PATCH
  ‘https://api.allegro.pl/sale/product-offers/9531382307’
  -H 'Authorization: Bearer {token}'
  -H 'Accept: application/vnd.allegro.public.v1+json'
  -H 'Content-Type: application/vnd.allegro.public.v1+json'
  -d ’{
    "publication": {
         "status": "ACTIVE"
     }
  }’

**Comment by Lukasz-Zurek** [comment]
Pod spodem jest walidacja parametrów, którą bierzemy pod uwagę przy próbie aktywowania/wznowienia oferty.

Aby sprawdzić status ukończenia zadania, skorzystaj z adresu otrzymanego w nagłówku **Location** i zasobu [GET /sale/product-offers/{offerId}/operations/{operationId}](https://developer.allegro.pl/documentation#operation/getProductOfferProcessingStatus).

Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#publikacja-oferty-w-asynchronicznym-api).
