### ISSUE TITLE
GET /sale/user-ratings niedziałający parametr recommended

### ISSUE THREAD

**Issue by arolznov** [allegro/allegro-api#8291]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

W metodzie GET /sale/user-ratings jeśli podamy parametr recommended z wartością string "true" lub "false" np. GET /sale/user-ratings?recommended=true zwraca komunikat Wewnętrzny błąd serwera, spróbuj ponownie później. Bez parametru recommended jest ok.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, jednak nie udało mi się powtórzyć tego przypadku. Czy możesz podać trace-id dla operacji, gdzie odpowiedzieliśmy błędem? Być może wartość boolean przekazujesz jako string, tak jak właśnie to opisałeś - zamiast ?recommended="true", spróbuj przekazać ?recommended=true.

**Comment by arolznov** [comment]
trace id dla:
false => c0dbe8f0d7b4ad78
true => ce3caa238a4a53b8

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za przykłady. Problem powoduje stricte połączenie dwóch parametrów `lastChangedAt` i `recommended`. Wyjaśniam tę kwestię z zespołem odpowiedzialnym za usługę, wrócę z informacją.

**Comment by PrzemyslawLukanowski** [comment]
Tak, jest to błąd po naszej stronie, zespół przygotuje poprawkę - wrócę z informacją, gdy już będzie gotowa.

**Comment by PrzemyslawLukanowski** [comment]
Wdrożyliśmy poprawkę, problem już nie występuje.
