### ISSUE TITLE
Utworzenie oferty dla produktu w kategorii Felgi Aluminiowe (257711) nie pozwala na ustawienie listy "Pasuje do"

### ISSUE THREAD

**Issue by pawel-mazur** [allegro/allegro-api#8293]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

https://api.allegro.pl.allegrosandbox.pl/sale/products/352b74a4-7139-474a-8916-237e3f993b87

Produkt występuje w kategorii Felgi Aluminiowe (257711).

Sam produkt ma ustawioną informację (`trace-id: 2d1f96758d116be4`):

```
    "id": "352b74a4-7139-474a-8916-237e3f993b87",
    "name": "Felgi FE177/BY2038 16x7\" 5x114.3 ET40 9",
    "category": {
        "id": "257711",
    },
    ...
    "compatibilityList": null,
```

https://api.allegro.pl.allegrosandbox.pl/sale/product-offers

Wysłanie żądania z pustą listą zakłada szkic (`trace-id: 6b98e912abd2fb73`)

```
   "compatibilityList": null,
```

Przesłanie żądania ze wskazaną listą zwraca komunikat błędu (`trace-id: 221b482efc957f09`)

```
    "compatibilityList": {
        "items": [
            {
                "id": "f2eb40cb-64de-49a6-afc4-1cded2ec88c2",
                "type": "ID"
            }
        ],
        "type": "MANUAL"
    },
```

```
{
    "errors": [
        {
            "code": "CompatibilityListCategoryNotSupportedException",
            "details": null,
            "message": "Unprocessable Entity",
            "path": "compatibilityList",
            "userMessage": "We do not support the creation of compatibility lists in category `257711`."
        }
    ]
}
```

Pobranie listy dostępnych grup produktów zwraca jedną grupę (`trace-id: 6bd811e71bf4173f`)

```
{
    "groups": [
        {
            "id": "be956e74642d5b18c6a4864aad39f494",
            "text": "Mercedes-Benz"
        }
    ],
    "count": 1,
    "totalCount": 1
}
```

W danej grupie dostępne są dwa pojazdy (`trace-id: dbb8c5f060dc6a9`)

```
{
    "count": 2,
    "totalCount": 2,
    "compatibleProducts": [
        {
            "id": "38b96342-2a3f-4e3b-b895-cfe96816bbec",
            "text": "Mercedes-Benz G (3FS) 1998ccm 224KM/",
            "group": {
                "id": "be956e74642d5b18c6a4864aad39f494"
            },
            ...
        },
        {
            "id": "f2eb40cb-64de-49a6-afc4-1cded2ec88c2",
            "text": "Mercedes-Benz Klasa G (54545454) 4134ccm 288KM/385kW",
            "group": {
                "id": "be956e74642d5b18c6a4864aad39f494"
            },
            ...
        }
    ]
}
```

Z czego może wynikać problem. Jak można zaktualizować listę "Pasuje do" dla już utworzonego produktu? Czy na środowisku SandBox są dostępne inne niż wymienione pojazdy dla których można znaleźć dopasowania produktów?

Dlaczego odpytanie zasobu (`trace-id: af425f1559d81c39`) oraz (`trace-id: 4b0b3986ad0fb2fa`), zwaracją kolejno informacje o dopasowaniu produktu do list zwróconych wyżej?

https://api.allegro.pl.allegrosandbox.pl/sale/compatible-products?type=CAR&phrase=DAEWOO+CIELO+Sedan+I+1.5+16V++2004 
https://api.allegro.pl.allegrosandbox.pl/sale/compatible-products?type=CAR&phrase=LEXUS+LS+Sedan+III+430++2000

```
{
    "count": 1,
    "compatibleProducts": [
        {
            "id": "f2eb40cb-64de-49a6-afc4-1cded2ec88c2",
            "text": "Mercedes-Benz Klasa G (54545454) 4134ccm 288KM/385kW",
            "group": {
                "id": "be956e74642d5b18c6a4864aad39f494"
            },
            "attributes": [
                {
                    "id": "BODY",
                    "values": [
                        "Sedan"
                    ]
                },
          ...
```

Czy to ze względu na dopasowanie atrybutu `Body:Sendan`, które pojawiło się w nazwie modelu auta?

**Comment by MartaNowaczyk** [comment]
Zgodnie z komunikatem nie możesz w danej kategorii dodać sekcji Pasuje do. Możliwe kategorie sprawdzisz za pomocą [GET /sale/compatibility-list/supported-categories](https://developer.allegro.pl/documentation/#operation/getCategoriesThatSupportCompatibilityList).

Środowiska produkcyjne i testowe są od siebie całkowicie niezależne. Na sandbox lista grup i lista pojazdów są ograniczone, stąd najlepsze dopasowanie różni się od tego oczekiwanego. Na produkcji bez problemu wyszukasz odpowiedni model auta.

**Comment by pawel-mazur** [comment]
Tak, ta kategoria na środowisku sandbox nie jest zwracana w zasobie o którym Pani wspomina.

Wg. dokumentacji (https://allegro.pl/dla-sprzedajacych/nowa-wersja-sekcji-pasuje-do-WEVgxnkoOiv) w kategorii nadrzędnej Felgi (https://allegro.pl/kategoria/opony-i-felgi-felgi-257708), ta funkcjonalność powinna być dostępna. Korzystamy z tego mechanizmu produkcyjnie, a wszystkie produkty które posiadamy, utworzone są właśnie w jej podkategoriach.

Na środowisku sandbox kategoria o której wspominam zawiera możliwość filtrowania produktów przez stronę. Dlaczego nie jest dostępna w api?

![Zaznaczenie_134](https://github.com/allegro/allegro-api/assets/7546262/157c20ac-0049-4ef2-94e4-c963bfc7af17)

Czy jest możliwość włączenia tej funkcjonalności w tej kategorii na środowisku sandbox, tak jak na produkcyjnej wersji?

**Comment by MartaNowaczyk** [comment]
Skonsultuję opisaną sprawę z zespołem odpowiedzialnym za funkcjonalność "Pasuje do" i wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Wdrożyliśmy zmianę i "Pasuje do" powinno być już dostępne w kategorii "Felgi samochodowe" na Sandbox.

**Comment by pawel-mazur** [comment]
Bardzo dziękuję za wdrożoną zmianę, funkcjonalność działa prawidłowo.

Ostatnie pytanie jakie mam to czy można prosić o zaktualizowanie listy pojazdów ze środowiskiem produkcyjnym? Obecnie są dostępne tylko dwa modele aut.

Wg. dokumentacji, przez formularz, założyłem propozycję nowego modelu. Czy i ew. kiedy rozpatrywane są takie prośby na środowisku sandbox?

![download](https://github.com/allegro/allegro-api/assets/7546262/12217f19-ea17-47d1-8410-77112e228c68)

**Comment by MartaNowaczyk** [comment]
Cieszę się, że działa. Drugą kwestię zgłaszam do odpowiedniego zespołu, wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Wracam z odpowiedzią. Niestety, nie zwiększymy listy pojazdów, a propozycje modeli nie są rozpatrywane na sandboxie.

**Comment by pawel-mazur** [comment]
Rozumiem, jeszcze raz dziękuję. Zamykam zgłoszenie.
