### ISSUE TITLE
Waluta nie jest wspierana przez metodę dostawy

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#8294]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

Podczas zlecania utworzenia przesyłki przez `PUT /parcel-management/parcel-create-commands` otrzymuję błąd `Waluta nie jest wspierana przez metodę dostawy`

Trace id `36c00abddb858dff`, `16cd7ff40a2ea697`, command id `afafedda-e387-5ba8-bb3b-7c15df4e8fd8`

Jeszcze rano bez problemu tworzone były podobne przesyłki

**Comment by MartaNowaczyk** [comment]
W podanym przykładzie jest metoda dostawy "Allegro International Automaty Paczkowe Czechy", gdzie podana jest wartość ubezpieczenia w walucie PLN, zamiast CZK.

**Comment by q3ok** [comment]
Mam podobny problem korzystając ze "starej" metody parcel-management.
Niezależnie czy w items.value.currency podam PLN, czy CZK jest błąd.

Przykładowo generowanie etykiety parcel-create-commands 342a3339-54e0-4528-8eec-83f62a58c993

**Comment by ZAK2828** [comment]
Jest Pani pewna, że ma być CZK? Bo właśnie dzisiaj też przestały nam chodzić bilety dla metod "czeskich", i docelowo mamy CZK jako walutę, i bilet w programie prostapaczka się nie wygenerował, jak zmieniłem walutę na PLN, to bilet się utworzył.

**Comment by MartaNowaczyk** [comment]
@ZAK2828 podasz konkretny trace-id, dla tego przypadku z błędem?

**Comment by ZAK2828** [comment]
Nie jestem programistą niestety, korzystam tylko z gotowego programu, ale błąd tu przytoczony miałem taki sam i na innych forach też ludzie zgłaszają ten błąd.
Mam komunikat błędu jaki ten program wygenerował, może to Pani pomoże?
Ale w tym błędzie są dane, które nie wiem czy powinny być jawne, więc mógłbym jakoś na maila/ticketem Pani to podesłać?

**Comment by Pibrusz** [comment]
Witam 
Mamy podobny problem na wielu zamówieniach, podsyłam dane do przykładowego:
```
{
    "id": "e57bfa1e-a488-4f94-91ad-ecafef2b8b00",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "VALIDATION_ERROR",
            "message": "Currency is not supported by deliery method",
            "details": null,
            "path": "items.value.amount",
            "userMessage": "Waluta nie jest wspierana przez metodę dostawy"
        }
    ]
}
```
Request po paczkę

`"{serviceId":"14bac5b7-4f11-4b53-9a03-0242ac120002","receiver":{"address":{"street":"*****","postCode":"******","city":"*********","countryCode":"CZ"},"email":"alsr5lw40a+6b65e66e0@allegromail.pl","name":"**********","company":"","phone":"+********"},"pickup":{"address":{"street":"*******","postCode":"******","city":"*******","countryCode":"PL"},"email":"******8","name":"***","company":"****","phone":"*****"},"items":[{"dimensions":{"height":{"unit":"CENTIMETER","value":"11"},"width":{"unit":"CENTIMETER","value":"20"},"depth":{"unit":"CENTIMETER","value":"20"}},"weight":{"value":"1.00","unit":"KILOGRAM"},"description":"*****","type":"PACKAGE","value":{"amount":"1232","currency":"CZK"}}],"label":{"fileFormat":"PDF","referenceNumber":"******"}}`

**Comment by MartaNowaczyk** [comment]
Kwestia walut zależy rynku bazwoego i od metody dostawy, więc może u ciebie była inna. 
Dane wrażliwe można przesyłać za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt) z dodaniem w treści numeru wątku na GitHubie.

**Comment by ZAK2828** [comment]
@MartaNowaczyk Nic nie zmienialiśmy w programie, skonfigurowaliśmy raz, działało przez X miesięcy, dzisiaj wyrzuca błąd.
Ewidentnie coś musiało się zmienić po Państwa stronie.
Zwłaszcza, że wiele osób zgłasza problemy z tym błędem.
Wyślę pełen komunikat błędu przez formularz.

**Comment by q3ok** [comment]
> `"{serviceId":"14bac5b7-4f11-4b53-9a03-0242ac120002","receiver":{"address":{"street":"*****","postCode":"******","city":"*********","countryCode":"CZ"},"email":"alsr5lw40a+6b65e66e0@allegromail.pl","name":"**********","company":"","phone":"+********"},"pickup":{"address":{"street":"*******","postCode":"******","city":"*******","countryCode":"PL"},"email":"******8","name":"***","company":"****","phone":"*****"},"items":[{"dimensions":{"height":{"unit":"CENTIMETER","value":"11"},"width":{"unit":"CENTIMETER","value":"20"},"depth":{"unit":"CENTIMETER","value":"20"}},"weight":{"value":"1.00","unit":"KILOGRAM"},"description":"*****","type":"PACKAGE","value":{"amount":"1232","currency":"CZK"}}],"label":{"fileFormat":"PDF","referenceNumber":"******"}}`

@Pibrusz 
Z ciekawości, bo to chyba paczka pobraniowa, i ona idzie bez 'cashOnDelivery'?

**Comment by MartaNowaczyk** [comment]
@Pibrusz @q3ok dla metody dostawy "Allegro Kurier DPD Czechy" ("14bac5b7-4f11-4b53-9a03-0242ac120002") ubezpieczenie powinno być w walucie PLN. 

Wzmocniona walidacja po naszej stronie spowodowała, że otrzymujecie odpowiednie błędy.

**Comment by q3ok** [comment]
> ubezpieczenie powinno być w walucie PLN.

Uprzejmie proszę w takim razie odnieść się do https://github.com/allegro/allegro-api/issues/8297 które blokuje możliwość pobrania waluty w której powinno być ubezpieczenie

**Comment by CSVK2022** [comment]
Mamy ten sam problem, commandID b7caaee9-bb4f-4bc6-905c-7b489a2dc6db
Zamówienia metodą Allegro Kurier DPD Czechy Pobranie generują się poprawnie.

**Comment by MartaNowaczyk** [comment]
@q3ok na pewno ktoś odpowie na to zgłoszenie.

@CSVK2022 nie mogę znaleźć tego commandId. Czy na pewno jest poprawny?

**Comment by wap18** [comment]
> @Pibrusz @q3ok dla metody dostawy "Allegro Kurier DPD Czechy" ("14bac5b7-4f11-4b53-9a03-0242ac120002") ubezpieczenie powinno być w walucie PLN.
> 
> Wzmocniona walidacja po naszej stronie spowodowała, że otrzymujecie odpowiednie błędy.

Czy dla metody create new parcel która jest deprecated: 
parcel-management/parcel-create-commands/{commandId}
nie przekazanie wartości 
"value": {
"amount": "2.50",
"currency": "PLN"
}, 
spowoduje brak ubezpieczenia paczki? 

Czy jest tak jak opisane w artykule: 
https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/allegro-international-czechy-informacje-dla-sprzedajacych-1nw4LyzOKSz#sprawdz-szczegolowa-instrukcje-nadawania-przesylek-przez-wysylam-z-allegro
"W cenę przesyłki wliczone jest ubezpieczenie do 5000 zł lub 25000 CZK – jest to maksymalna wartość ubezpieczenia" 
I paczka jest ubezpieczona z automatu.

**Comment by MartaNowaczyk** [comment]
@ZAK2828 otrzymałam dane z formularza kontaktowego, sprawdziłam i Twoja metoda to "Allegro Kurier DPD Czechy" ("14bac5b7-4f11-4b53-9a03-0242ac120002") podajecie walutę w CZK, a powinna być w PLN, stąd błąd po uszczelnieniu walidacji.

**Comment by Pibrusz** [comment]
@q3ok 
to zamówienie opłacone 

@MartaNowaczyk podana kwota jest brana do ubezpieczenia ?

**Comment by Pibrusz** [comment]
@MartaNowaczyk czy nie przekazanie pola wartości paczki/zamówienia skutkuje brakiem ubezpieczenia paczki ? 


> > @Pibrusz @q3ok dla metody dostawy "Allegro Kurier DPD Czechy" ("14bac5b7-4f11-4b53-9a03-0242ac120002") ubezpieczenie powinno być w walucie PLN.
> > Wzmocniona walidacja po naszej stronie spowodowała, że otrzymujecie odpowiednie błędy.
> 
> Czy dla metody create new parcel która jest deprecated: parcel-management/parcel-create-commands/{commandId} nie przekazanie wartości "value": { "amount": "2.50", "currency": "PLN" }, spowoduje brak ubezpieczenia paczki?
> 
> Czy jest tak jak opisane w artykule: https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/allegro-international-czechy-informacje-dla-sprzedajacych-1nw4LyzOKSz#sprawdz-szczegolowa-instrukcje-nadawania-przesylek-przez-wysylam-z-allegro "W cenę przesyłki wliczone jest ubezpieczenie do 5000 zł lub 25000 CZK – jest to maksymalna wartość ubezpieczenia" I paczka jest ubezpieczona z automatu.

**Comment by MartaNowaczyk** [comment]
@wap18 @Pibrusz 
Tak, to pole jest potrzebne do wyliczenia ubezpieczenia. W nowym API zostało zastąpione przez pole insurance. Jeżeli nie chcesz ubezpieczenia, możesz też przekazać w tym miejscu 0 PLN.

Przepraszam za dłuższe oczekiwanie na odpowiedź, ale wolałam skonsultować sprawę z zespołem odpowiedzialnym za WZA.

**Comment by Pawelpwg** [comment]
to mozna to podsumowac?
czyli kwota pobrania idzie w CZK
a kwota ubezpieczenia idzie w PLN? czy skad dokladnie brac walute?

**Comment by MartaNowaczyk** [comment]
Jeśli masz na myśli "Allegro Kurier DPD Czechy" to kwota pobrania będzie CZK, ale Ubezpieczenie w DPD (realizowanym przez polski oddział DPD) zawsze jest w PLN. 
Natomiast Packeta wymaga podania ubezpieczenia i ewentualnie kwoty pobrania w CZK.

**Comment by Pibrusz** [comment]
@MartaNowaczyk czy do jeszcze któryś metod ("Allegro Kurier DPD Czechy" ("14bac5b7-4f11-4b53-9a03-0242ac120002")) wprowadzona została podobna walidacja ?

**Comment by MartaNowaczyk** [comment]
@Pibrusz to ogólna walidacja, tylko tutaj najczęściej pojawiały się rozbieżności w walucie ubezpieczenia, stąd najczęstsze błędy występują przy tej metodzie.
