### ISSUE TITLE
Rest api - Parcel management

### ISSUE THREAD

**Issue by skrzyh** [allegro/allegro-api#8295]
Dzień dobry

Podczas pobierania zamówienia dostajemy metodę dostawy jaką wybrał klient:
"Allegro Kurier Pocztex pobranie" z id  (193d950b-0082-408f-9192-6081e5e7e7e2)

Chciałbym wygenerować etykietę przez metodą PUT "/parcel-management/parcel-create-commands/"  z tym identyfikatorem usługi "193d950b-0082-408f-9192-6081e5e7e7e2"

Zwrócony komunikat:
Wybrana metoda dostawy nie obsługuje tego zamówieniaclient credentials

Seller didnt provide credentials for own delivery Method

Podczas pobierania "/parcel-management/delivery-services" ta usług "Allegro Kurier Pocztex pobranie" nie jest zwracana.

Czy mogę prosić o wyjaśnienie jak mogę wygenerować etykietę dla "Allegro Kurier Pocztex pobranie" jeśli dostałem zamówienie z takim typem ?

**Comment by MartaNowaczyk** [comment]
Aby wysyłać tą metodą trzeba mieć dodaną umowę własną w ustawieniach dostawy.
