### ISSUE TITLE
Zmiana statusu po dodaniu przesyłki

### ISSUE THREAD

**Issue by allegrofan** [allegro/allegro-api#8296]
Po utworzeniu przesyłki poprzez API Allegro zdarza się, że zamówienie zmienia status na SENT. 
Przykład zamówienia: 5e781ea1-b547-11ee-af72-37bed499d892

**Comment by MartaNowaczyk** [comment]
Jeśli masz abonament i odpowiednie ustawienia w [Zamówieniach](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia), to zmiana statusu może być automatyczna, wtedy status zmienia się na “SENT”, gdy dodasz numer przesyłki.

**Comment by allegrofan** [comment]
Rzeczywiście miałem to zaznaczone. Dzięki za sugestię i rozwiązanie problemu.
