### ISSUE TITLE
Brak dostępu po API do zasobów /shipment-management/*

### ISSUE THREAD

**Issue by q3ok** [allegro/allegro-api#8297]
Występuje problem:
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [X] z logowaniem lub autoryzacją / with login or authorization

:beetle: **Opis / Description**

Aplikacja korzystająca z API, nawet po ponownym zarejestrowaniu w systemie Allegro, nie otrzymuje w scope 'allegro:api:shipments:write', który wg. dokumentacji jest wymagany do zasobów /shipment-management/*.

W związku z tym powstaje błąd 'No access to the specified resource.', nawet przy próbie odczytania listy dostępnych usług wysyłek.

Otrzymywany zestaw scope uprawnień: allegro:api:orders:read allegro:api:profile:write allegro:api:sale:offers:write allegro:api:billing:read allegro:api:campaigns allegro:api:disputes allegro:api:bids allegro:api:sale:offers:read allegro:api:orders:write allegro:api:ads allegro:api:payments:write allegro:api:sale:settings:write allegro:api:profile:read allegro:api:ratings allegro:api:sale:settings:read allegro:api:payments:read allegro:api:messaging

**Comment by q3ok** [comment]
Prawdopodobny problem który może to spowodować:

w związku z dodanym wymogiem waluty do ubezpieczenia przy generowaniu wysyłki, które nie zawsze jest w walucie w której zostało opłacone zamówienie (np. Allegro Kurier DHL Czechy), spowoduje to problem przy generowaniu etykiety:
**jaką walutę do ubezpieczenia paczki przyjąć?**
czy znowu trzeba wrócić do rozpoznawania po sposobie/nazwie wysyłk? (podobnie jak na samym początku po wprowadzeniu WzA trzeba było kombinować bo nie było deliveryserviceid w checkoutform?) :)

W 'starym' zasobie z delivery services nie ma informacji o tym, w jakiej walucie powinno być ubezpieczenie, nowy zasób j/w niedostępny.

**Comment by MartaNowaczyk** [comment]
1. Sprawdź czy masz zaznaczony odpowiedni scope dla aplikacji z której korzystasz https://apps.developer.allegro.pl/, a potem wygeneruj nowy token/powiązanie.

2. Dane dotyczące waluty zwracamy dla [GET /shipment-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getDeliveryServices) np.
```

...
{
            "id": {
                "deliveryMethodId": "1401412f-1bcc-4dad-98c4-b3146fe9f54a",
                "credentialsId": null
            },
            "name": "Allegro International Kurier Czechy pobranie",
            "carrierId": "ALLEGRO",
            "additionalServices": [],
            "owner": "ALLEGRO",
            "marketplaces": [
                "allegro-cz"
            ],
            "packageTypes": [
                "PACKAGE"
            ],
            "cashOnDelivery": {
                "limit": 25000,
                "currency": "CZK",
                "paymentType": "WALLET_TRANSFER",
                "forceRequireIban": false
            },
            "insurance": {
                "limit": 25000,
                "currency": "CZK"
            },
            "features": {}
        },
        {
            "id": {
                "deliveryMethodId": "14b73cc6-28d6-11eb-adc1-0242ac120002",
                "credentialsId": null
            },
            "name": "Allegro Kurier DPD Czechy",
            "carrierId": "DPD",
            "additionalServices": [
                {
                    "id": "additionalHandling",
                    "name": "Paczka niestandardowa",
                    "description": "Paczka o kształcie, który nie jest prostopadłościanem (np. opona, tuba) lub taka, która jest owinięta stretchem, folią lub innym materiałem utrudniającym przesuwanie."
                }
            ],
            "owner": "ALLEGRO",
            "marketplaces": [
                "allegro-pl"
            ],
            "packageTypes": [
                "PACKAGE"
            ],
            "cashOnDelivery": null,
            "insurance": {
                "limit": 50000,
                "currency": "PLN"
            },
            "features": {}
        },
...

```

**Comment by q3ok** [comment]
Dziękuję, działa, nie znałem strony https://apps.developer.allegro.pl/
