### ISSUE TITLE
Wystpuje problem: [z logowaniem lub autoryzacją ]

### ISSUE THREAD

**Issue by LukaszMalekBH** [allegro/allegro-api#8298]
Nie dostaję hasła sms w ramach uwierzytelnienia dwuskładnikowego na serwisie deweloperskim, nie mogę tym samym uzyskać dostępu do zdefiniowania nowej aplikacji. 

Jak rozwiązać ten problem?

**Comment by PrzemyslawLukanowski** [comment]
Czy masz na myśli środowisko testowe? Dwustopniowe logowanie nie jest tutaj wymagane, aby założyć aplikację, być może Twoje konto nie zostało aktywowane (jeśli nie masz pewności, podaj proszę login/mail). Nie wysyłamy również sms-ów na tym środowisku. Jeśli jednak chcesz włączyć dodatkowe logowanie, wpisz 12345, a przy samym logowaniu 123456.

**Comment by LukaszMalekBH** [comment]
Dwustopniowe logowanie włączyłem. 

Tutaj mam jednak nadal informację "[Aktywuj konto](https://allegro.pl/pomoc/dla-sprzedajacych/rejestracja-i-aktywacja/czym-jest-pelna-aktywacja-konta-i-jak-moge-ja-przeprowadzic-GDeq5WOB8uE) oraz włącz [dwustopniowe logowanie](https://allegro.pl/pomoc/dla-kupujacych/logowanie-i-haslo/czym-jest-dwustopniowe-logowanie-i-dlaczego-warto-z-niego-korzystac-dykqg9nMKSZ)."

https://apps.developer.allegro.pl.allegrosandbox.pl/

Konto: HAPPY24_PL

**Comment by LukaszMalekBH** [comment]
Zrealizowane. Prośba o aktywację.

**Comment by PrzemyslawLukanowski** [comment]
Wszystko się zgadza, aktywowałem konto.
