### ISSUE TITLE
Uprawnienia w REST API

### ISSUE THREAD

**Issue by Lebioda** [allegro/allegro-api#83]
Po co zostało wprowadzone REST API i skomplikowane metody uwierzytelniania skoro nie ma nawet opcji uprawnień dla aplikacji? Użytkownik musi dać aplikacji 100% uprawnień mimo, że wg autora pobiera ona tylko informacje o ocenach.

Czy planowane są zmiany w tym zakresie?

**Comment by KrzysztofLukanowski** [comment]
Nie planujemy zmian w tym zakresie. Wbrew pozorom proces uwierzytelniania jest prosty - wystarczy [oauth](https://developer.allegro.pl/auth/), a do korzystania z zasobów WebAPI możesz wykorzystywać logowanie uzyskanym tokenem w ramach [doLoginWithAccessToken](https://allegro.pl/webapi/documentation.php/show/id,101582).

**Comment by Lebioda** [comment]
Pytam o uprawnienia. Robię aplikację publiczną. Użytkownicy muszą dać aplikacji 100% uprawnień do swojego konta. Nie mogą zgodzić się tylko na pobieranie ocen. Można im pokazywać oceny, a w tle bez ich wiedzy manipulować aukcjami.

**Comment by kormichu** [comment]
Również potrzebuję ograniczony dostęp do konta. Wystarczą mi tylko podstawowe informacje o koncie użytkownika

**Comment by KrzysztofLukanowski** [comment]
To od Was zależy jakie dane będziecie przetwarzać i o dostęp do jakich danych poprosicie użytkownika.

**Comment by Lebioda** [comment]
Przecież użytkownik nie jest informowany do jakich danych dostęp ma aplikacja. Jest tylko informacja

> Powiązanie umożliwia aplikacji wykonywanie w Twoim imieniu operacji na Allegro, takich jak np. pobieranie danych o zamówieniach czy wystawianie ofert.

i użytkownik wyraża zgodę na wszystko albo na nic. Nie ma opcji np. "zezwól tylko na pobieranie ocen".

Ja wiem, że mogę pobierać tylko oceny. Użytkownik ma mi na słowo uwierzyć?

**Comment by DINK74** [comment]
@KrzysztofLukanowski - czy mógłby Pan czytać pytanie i dopiero potem odpowiadać?
Chodzi o to, że obecnie jeśli użytkownik powiąże aplikację ze swoim kontem na Allegro i się z niej zaloguje to aplikacja może wykonać potencjalnie szkodliwe operacje - np. skasować aukcje, zmienić w nich ceny albo podmienić numer konta do wpłaty pokazywany na aukcji (choć w tym zakresie Allegro "załatało" problem wyłączając opcję wyświetlania numeru konta :-)
Oczywiście autoryzacja tokenem i tak jest lepsza niż dotychczasowe przekazywanie konta/hasła ale wymagane jest "ludzkie zaufanie" do autora aplikacji.
Co ciekawe - przy autoryzacji pojawia się parametr **scope** opisany jako "Zasięg danych/funkcjonalności do których użytkownik autoryzował aplikacje (obecnie nieużywany)" - czyli gdzieś/kiedyś jakiś developer zajarzył, że taka opcja powinna być dostępna. Pytanie - czemu nie została wdrożona?

**Comment by DINK74** [comment]
@Lebioda czuję się trochę wywołany do tablicy, bo zakładam że piszesz o mojej aplikacji, która wylicza średnią ocen do kwalifikacji do SS - i faktycznie w komentarzach na grupie fb pojawiają się pytania o zakres działań aplikacji - muszę odpowiadać, że - istotnie - opiera się na "zaufaniu do developera" o którym wspomniał @awronski :-)
A poważnie - w dokumentacji widać, że ktoś miał podobne obiekcje i stąd pojawił się parametr "scope" - niestety nie jest używany. Inną opcją byłby dostęp typu read-only pozwalający wyłącznie na pobieranie danych z konta bez ich modyfikacji (to wystarczyłoby np. w przypadku mojej aplikacji).
Póki REST API składało się z jednej funkcji do zmiany cen można to było przeboleć, ale odkąd pojawił się po stronie SOAP doLoginWithAccessToken to w zasadzie zautoryzowana aplikacja może niemal wszystko.

**Comment by KrzysztofLukanowski** [comment]
@DINK74 Spieszę z wyjaśnieniem - rzeczywiście mamy w planach pytanie użytkownika o zakres uprawnień, jednak nie jestem w stanie określić terminu, w którym pojawi się taka możliwość. Jak tylko będziemy mieli więcej informacji, poinformujemy o tym na githubie oraz [portalu developerskim](https://developer.allegro.pl/news/).

**Comment by mnieznanski** [comment]
Czy coś się zmieniło w tej sprawie? Czy jako użytkownik mogę zarządzać uprawnieniami aplikacji developera? Np. nadać uprawnienia tylko do pobierania zamówień, bez zarządzania ofertami (albo odwrotnie). Nie widzę takiej opcji w MOJE KONTO->Bezpieczeństwo->Powiązane Aplikacje. Nie widzę też, aby przy podłączaniu aplikacji można było zaznaczać uprawnienia. Jest wszystko albo nic.

**Comment by MaciejFrackowiak** [comment]
@mnieznanski Na ekranie zgody wyświetlane są wszystkie uprawnienia, z którymi dana aplikacja wystąpiła o token. To autor aplikacji decyduje, które scope'y są niezbędne do funkcjonowania poprawnego aplikacji. Jeżeli masz zastrzeżenia co do ilości udostępnianych danych to proszę zgłoś je bezpośrednio do autora aplikacji, ponieważ to on zarządza uprawnieniami aplikacji.
