### ISSUE TITLE
Logowanie REST API

### ISSUE THREAD

**Issue by SoDaUser** [allegro/allegro-api#830]
Dzień Dobry

Mam pytanie dotyczące sposobu logowania. 
Korzystam z API-SOAP w zakresie obsługi zamówień. 
Obserwuję wzrost udziału REST API z niektórych funkcji chętnie bym skorzystał rozwijając aplikację.
(np. rejestrując dziś nową aplikację korzystającą z API-SOAP konieczne jest podanie adresu powrotu, którego nie posiadam)

Reasumując, mam następujący problem: 
Aplikacja nie jest aplikacją web, działa w środowisku, niewidocznym z zewnątrz. 
Przyznam, że uruchamianie serwera, jedynie po to aby udostępnić "adres powrotu" jest problemem.

W jaki sposób korzystać z REST API w takiej aplikacji, usłudze ?

**Comment by qqgg231** [comment]
Mam ten sam problem. Nie mogę wygenerować klucza WebAPI, ponieważ strona wymaga ode mnie "Adresu URI do przekierowania"

**Comment by MartaNowaczyk** [comment]
@SoDaUser @qqgg231 Pracujemy nad rozwiązaniem dla takich przypadków. To kwestia jeszcze około 2 tygodni, żeby to udostępnić. 
Można też podać localhost:{port} i 'słuchać' na tym adresie.

**Comment by qqgg231** [comment]
Tu jest więcej informacji:
https://github.com/allegro/allegro-api/issues/786

**Comment by qqgg231** [comment]
Wystarczy podać jako adres URI:
       `https://localhost:80`

**Comment by SoDaUser** [comment]
Dziękuję za odpowiedź, na localhost trochę ryzykowne :) możemy zapętlić Allegro.
Słuchanie nic nie da, bo nikt nie będzie szeptał.

Czekam z niecierpliwością. Pozdrawiam

**Comment by GosiaJK** [comment]
Dołączam się do życzeń. Również używam wewnętrzną aplikacje do WebAPI i chętnie przesiądę się na Rest jeśli tylko pojawi się to ułatwienie związane z logowaniem.

Pozdrawiam
Gosia

**Comment by FromAnyHole** [comment]
@SoDaUser @qqgg231 @MartaNowaczyk - ja pierdziu... to "słuchanie" na [localhost:80], o ile serwery autoryzujące w ogóle pozwolą na jawny protokół, było by pierwszym krokiem do narażenia końcowych użytkowników na przechwycenie klucza 10-sekundowego (odsyłanego na adres powrotu), a potem samego token'a ! ;-)

**Comment by GosiaJK** [comment]
Minęło już 20 dni. Czy ułatwiliście już dostęp dla użytkowników, którzy są jednocześnie twórcami aplikacji dla Api?
