### ISSUE TITLE
Allegro MiniPrzesyłka ERROR: Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.

### ISSUE THREAD

**Issue by allegrofan** [allegro/allegro-api#8300]
Czy jest obecnie problem z zamawianiem przesyłek z poczty?
Próbuję zamówić ale mam błąd:
Allegro MiniPrzesyłka 

ERROR: Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.

**Comment by PrzemyslawLukanowski** [comment]
Poproszę o przykładowe command ID lub trace id powiązane z tym komunikatem błędu.

**Comment by allegrofan** [comment]
62a1d88f-9f44-4b09-906b-539fe4751f5c

aktualny komunikat: ERROR: Wystąpił‚ błąd komunikacji z API przewoźnika

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję i potwierdzam, aktualnie występują problemy po stronie Poczty Polskiej.
