### ISSUE TITLE
Pobieranie statystyk oferty.

### ISSUE THREAD

**Issue by ERPgit2** [allegro/allegro-api#8302]
Jaką metoda można pobrać statystyki sprzedaży, obserwujących, wizyt dla naszych ofert?

**Comment by MartaNowaczyk** [comment]
Takie dane znajdziesz tylko w [GET /sale/offers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET) w obiekcie "stats" (watchersCount, visitsCount).

**Comment by ERPgit2** [comment]
Czyli w zasobie, który został wyłączony na początku tego roku i odpowiednik GET /sale/product-offers/ nie daje takiej możliwości?
