### ISSUE TITLE
Operacje bilingowe - niepełne informacje

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#8303]
Hej,

Pobierając informacje bilingowe za pomocą GET /billing/billing-entries dostajemy niepełne informację odnośnie danej operacji.

Przykładowo otrzymujemy opłatę z type.id = "DTR" co oznacza "DPD - Kurier opłaty dodatkowe". Brakuje natomiast informacji czego dokładnie dotyczy ta opłata, a co jest widoczne przykładowo na froncie:
![image](https://github.com/allegro/allegro-api/assets/36523118/23199485-f89c-4bc4-be41-0d6e14d345a2)

W jaki sposób za pomocą API uzyskać powyższą nazwę usługi dodatkowej lub jej kod?

**Comment by MartaNowaczyk** [comment]
Niestety, nie mamy takich informacji w API.

**Comment by dlis2010** [comment]
Czy są plany rozbudowania tego zasobu o te dane?

Rozumiem, iż podczas projektowania zasobu wystarczyło, aby zwracał type.id niestety wraz z rozbudową systemu samo type.id przestało wystarczać. W celu prawidłowej funkcjonalności zasobu konieczne jest aby zwracał komplet informacji (wraz z kodem/nazwą usługi dodatkowej).

Aktualnie mamy teraz takie trochę wróżenie z fusów, dostajemy opłatę:
> DTR => "DPD - Kurier opłaty dodatkowe"
lecz nie mamy pojęcia czego ta opłata tak naprawdę dotyczy.

Jest to dość problematyczne bo o ile o wszystkich opłatach tak naprawdę powinniśmy wiedzieć w momencie generowania przedmiotu danej opłaty (np generujemy etykietę - spodziewamy się opłaty za etykietę, sprzedamy towar - spodziewamy się prowizji itd...) to zaczęły pojawiać się opłaty na które nie mieliśmy wpływu - np. dopłaty kurierskie, które nie zawsze są należne - dlatego chcielibyśmy mieć możliwość ich namierzenia.

Chyba, że jest jakieś inne alternatywne rozwiązanie, aby wyłapać takie opłaty ?
