### ISSUE TITLE
Generowanie wysyłki przez /shipment-management a brak streetNumber w /order/checkout-forms

### ISSUE THREAD

**Issue by q3ok** [allegro/allegro-api#8304]
### Generowanie wysyłki przez /shipment-management a brak streetNumber w /order/checkout-forms
Aktualnie, w checkout-forms jako adres dostawy jest tylko ulica (street), nie ma numeru budynku w osobnym polu.
Zasób do tworzenia przesyłek w shipment-management w polach odbiorcy (czy też punktu pickup) ma rozdzielone pola ulicy i numeru budynku.

Czy w związku z tym
- Czy do checkout-forms zostanie dodane również pole z numerem budynku?
- Czy można nadawać paczki z zasobu shipment-management bez podawania streetNumber, tylko kopiując street z checkout-form?
- Czy we własnym zakresie należy rozbić street z checkout-form na nazwę ulicy i na numer budynku?

Idąc dalej, czy może są plany żeby w WzA podawać po prostu uuid checkout-form + dane dotyczące samej przesyłki (wymiary,ubezpieczenie,opis,parametry etykiety), zamiast kopiować te dane "u siebie", ale zostawiając zapasowo (gdy podane dane w checkout-form są błędne i trzeba je "poprawić") możliwość podania danych do nadpisania tych z checkout-form?

**Comment by MartaNowaczyk** [comment]
> Czy do checkout-forms zostanie dodane również pole z numerem budynku?

Nie mamy tego w planach na ten moment.

> Czy można nadawać paczki z zasobu shipment-management bez podawania streetNumber, tylko kopiując street z checkout-form?

Pole to jest wymagane podczas tworzenia przesyłki. Niektórzy przewoźnicy mogą wymagać tego pola.

> Czy we własnym zakresie należy rozbić street z checkout-form na nazwę ulicy i na numer budynku?

Tak.

Jeśli chodzi o zmianę w WZA, to nie mamy w tym momencie w planach, by pobierać te dane automatycznie.

**Comment by q3ok** [comment]
Piszę ponownie w temacie, bo zastanawiam się czy ktoś już może opracował sposób na rozdzielenie adresu z street na nazwę ulicy + numer budynku, która działała by **zawsze** w poprawny sposób?
Niestety, problem pojawia się głównie przy ulicach mających numer w nazwie, jak też różnym sposobie zapisu przez klientów w przypadku numerów mieszkań, czy nawet niekiedy numerów mieszkań które są dwuczłonowe.
W pewnym momencie i tak można trafić na zapisany adres, który "rozwali" rozbicie, i zamiast automatyzacji wystawiania etykiet (co można robić na aktualnym zasobie parcel-management) wchodzi się w sytuacje, w których trzeba będzie poprawiać dane wpisane przez klienta.

Przykładowe nazwy ulic które mogą sprawiać problemy:
ul. Jana Pawła 2 222 m.2
ul. Bitwy Warszawskiej 1920 r. 12/I m.3
ul. Harcerzy Września 1939 50a m. 60b

do tego dochodzą też przeróżne formy zapisu bez spacji, z innymi znakami przestankowymi, no i też zagraniczne nazwy ulic, gdzie nie mam doświadczenia w tym, jakie mogą być użyte nazwy, a tym bardziej jakie mogą być sposoby zapisu (czyli defacto trzeba by było mieć dostosowany parser pod każdy kraj docelowy).

Aktualnie to może wyglądać tak, że automat próbuje wygenerować przesyłkę rozdzielając automatycznie (i może tym samym przekazać "głupoty", a i tak wygeneruje - czyli przesyłka może nie dotrzeć, albo będzie dłużej w transporcie == niezadowolenie klienta) i dopiero gdy przyjdzie zwrotka, że są błędne dane umożliwić wpisanie danych użytkownikowi (czyli dodatkowy koszt, bo czas), lub za każdym razem prosząc użytkownika o rozdzielenie nazwy (też dodatkowy koszt, bo czas).

Na pewno nadal nie ma planów na dodanie tego pola już na etapie checkout-form? Ew. może powrót do nazwy ulicy w jednym polu, zamiast rozbijania przez klientów?
