### ISSUE TITLE
 Brakujące produkty TecDoc marki DR.MOTOR

### ISSUE THREAD

**Issue by PunktAutoCzesci** [allegro/allegro-api#8305]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Cześć,
poniżej lista produktów TecDoc marki Dr.Motor Automotive (DR.MOTOR) których brakuje w bazie produktów.
/sale/products
Proszę o informację po ich dodaniu.

DRM0168Q
DRM01777
DRM01785
DRM01114
DRM01776
DRM01783
DRM01780
DRM01782
DRM0305S
DRM0560S
DRM0607
DRM0818
DRM01463
DRM14201S
DRM01827
DRM01975
DRM181005
DRM81005
DRM01009
DRM21C07
DRM21C13
DRM01666S
DRM01808
DRM01809
DRM01810
DRM01997
DRM12811S
DRM6403
DRM19801
DRM21834
DRM168201S
DRM218202S
DRM218204S
DRM01789
DRM02216
DRM6402
DRM6806
DRM12814
DRM15806
DRM158201
DRM01804
DRM01590
DRM01589
DRM01591
DRM02144
DRM01791
DRM21304
DRM02212
DRM02209
DRM01935
DRM01934
DRM01857
DRM211160
DRM02145
DRM02149
DRM02146
DRM02148
DRM02147
DRM18529
DRM12026
DRM02150
DRM02220
DRM01817
DRM9203
DRM21255
DRM02221
DRM21C21
DRM161113
DRM121105
DRM121107
DRM121108
DRM151114
DRM151112
DRM151115
DRM151113
DRM02215
DRM28201S
DRM28203S
DRM118201S
DRM218201S
DRM218203S
DRM21922R
DRM13205S
DRM72210S
DRM16214S
DRM212102
DRM22210S
DRM62028S
DRM62048S
DRM15235S
DRM16232S
DRM0629S
DRM01000
DRM01023
DRM01937
DRM02125
DRM01470S
DRM01998
DRM02154
DRM01792
DRM01988
DRM0908S
DRM02139
DRM01784
DRM038
DRM039
DRM0120
DRM036
DRM037
DRM049
DRM0152S
DRM0253
DRM0153
DRM0301S
DRM0302S
DRM0300S
DRM0303S
DRM0343S
DRM0409
DRM0304S
DRM0495S
DRM0307
DRM0311S
DRM0420S
DRM0509
DRM0581S
DRM0585
DRM0609S
DRM0612
DRM0629
DRM0672
DRM0772SL
DRM0803
DRM0806
DRM0825
DRM0192K
DRM01106
DRM01107
DRM01108
DRM01109
DRM01110
DRM01111
DRM01112
DRM01113
DRM01116
DRM01117
DRM01118
DRM01119
DRM01120
DRM01121
DRM01123
DRM01057S
DRM01245
DRM01289
DRM01309
DRM01667
DRM01726R
DRM01731
DRM01378
DRM01779
DRM01781
DRM01971
DRM0499
DRM0835
DRM0836
DRM01192
DRM01169
DRM01235
DRM01290
DRM161001
DRM81004
DRM01210
DRM21C01
DRM21C02
DRM21C03
DRM21C12
DRM21C14
DRM21C16
DRM21C17
DRM21C18
DRM21C19
DRM21C20
DRM01457
DRM62018
DRM62020
DRM62016
DRM01010
DRM01753S
DRM01811
DRM01813
DRM01842S
DRM01869
DRM01872
DRM01963
DRM01405
DRM02153
DRM02178
DRM8801
DRM8802
DRM13801
DRM22801
DRM218207
DRM2935
DRM01807
DRM61108C
DRM61109C
DRM211127C
DRM16802
DRM21829
DRM01803
DRM01989
DRM21705
DRM21704S
DRM21705S
DRM18531
DRM18534
DRM18538
DRM18524
DRM2012
DRM21916R
DRM72209
DRM8205
DRM21254
DRM01815
DRM8213
DRM161114
DRM171101
DRM151111
DRM211157
DRM211158
DRM211159
DRM211165
DRM28202S
DRM8210S
DRM16231S
DRM16211S
DRM62047SL
DRM62042S
DRM0586
DRM01481
DRM01129
DRM02151
DRM01922
DRM02242
DRM02260
DRM02264
DRM18539
DRM6027
DRM02227
DRM02228
DRM02235Q
DRM02103
DRM01878
DRM02189
DRM02187
DRM02206
DRM02102
DRM02186
DRM02192
DRM02105
DRM02258
DRM02252
DRM21275
DRM21274
DRM02250
DRM02251
DRM02263
DRM01942S
DRM02236
DRM02243
DRM02253
DRM02262
DRM01999
DRM02255
DRM02247
DRM02223
DRM02101
DRM02233
DRM01474
DRM01373
DRM0351
DRM01291S
DRM01750S
DRM02239S
DRM01226S
DRM0822S
DRM0350
DRM02257S
DRM02226
DRM21709
DRM21708
DRM02104
DRM02231
DRM02229
DRM02232Q
DRM02240
DRM02225
DRM02183
DRM72218
DRM22226
DRM22225
DRM62046
DRM8208
DRM8209
DRM12217
DRM10213
DRM02188
DRM02184
DRM10216
DRM02185
DRM02224
DRM02238
DRM02100
DRM22227
DRM21263
DRM21264
DRM21262
DRM21265
DRM62050
DRM02249
DRM222107
DRM01881
DRM02261
DRM02237
DRM02246
DRM01879R
DRM02245
DRM01376
DRM01377
DRM01374
DRM11204S
DRM8212S
DRM18222S
DRM61210S
DRM8211S
DRM222106
DRM13207S
DRM10215S
DRM21206S
DRM21268S
DRM02254S
DRM02256S
DRM16233S
DRM12220S
DRM02259S
DRM62101
DRM22201S
DRM02234
DRM2812
DRM21825
DRM-N002
DRM2938
DRM21273
DRM02182
DRM01131S
DRM14804
DRM2939
DRM2937
DRM14805
DRM6601
DRM0584S
DRM01983
DRM02208S
DRM16806
DRM2815
DRM01790
DRM02211
DRM16226
DRM18522S
DRM61803
DRM21822
DRM21254S
DRM21272
DRM62047S
DRM02244
DRM21821
DRM01984S
DRM222105
DRM72207
DRM72208
DRM12815
DRM15014
DRM11803
DRM21841
DRM10214
DRM01982R
DRM188201S
DRM21837
DRM2816
DRM91101
DRM72006
DRM02248
DRM121110
DRM211164
DRM01661
DRM01679
DRM01351RS
DRM02219
DRM21270
DRM21271
DRM121106
DRM218206
DRM21269
DRM2813
DRM61804
DRM01985S
DRM02194
DRM218205S
DRM72206
DRM12817
DRM12818
DRM18804
DRM15805
DRM211155C
DRM02213
DRM10217
DRM21836
DRM8803
DRM6807
DRM02217
DRM02218
DRM62043
DRM02210
DRM9204
DRM21824
DRM13204
DRM121109
DRM15804
DRM211124
DRM18011
DRM211123
DRM6601/0.50
DRM211125

**Comment by PunktAutoCzesci** [comment]
Czy jest jakaś informacja zwrotna?

**Comment by Lukasz-Zurek** [comment]
Odpowiedziałem w [tym wątku](https://github.com/allegro/allegro-api/issues/8280#issuecomment-1926406053).
