### ISSUE TITLE
Aktywacja konta testowego

### ISSUE THREAD

**Issue by mjonninen** [allegro/allegro-api#8306]
Dzień dobry, chciałbym aktywować sprzedaż na Testowym środowisku login: pro_hurt24test przeklikałem weryfikację, ale od 2 dni nie ma zmian, nie mogę wystawić testowego produktu.

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, czy to na pewno prawidłowy login? Nie widzę takiego użytkownika w naszej bazie. Czy potwierdziłeś rejestrację  poprzez link aktywacyjny, który wysłaliśmy na maila?

**Comment by mjonninen** [comment]
Przepraszam obciąłem znak,
nazwa to: **pro_hurt_24test**

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie, w międzyczasie udało mi się dotrzeć do tej nazwy - aktywowałem konto.

**Comment by mjonninen** [comment]
Dziękuję. Mam jeszcze pytanie, chciałem na sandboxie kupić jakiś przedmiot i sprawdzić generowanie etykiety Smart poprzez API, konieczne jest zakładanie drugiego konta testowego "klienta", żeby zakupić przedmiot?

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, w takim przypadku wystarczy, że założysz drugie konto - może być zwykłe, nie musi być firmowe.

**Comment by PrzemyslawLukanowski** [comment]
Tak, autoryzacja typu device będzie wystarczająca. DCR przychodzi z pomocą wtedy, gdy inni użytkownicy musieliby instalować instancję Twojej aplikacji we własnej infrastrukturze, a jak rozumiem, to nie będzie taki przypadek.

**Comment by mjonninen** [comment]
Dziękuję, w przypadku DeviceFlow jest krok z kojarzeniem aplikacji, weryfikacją po przejściu na Allegro (po wywołaniu auth/oauth/device?client_id=).
https://allegro.pl.allegrosandbox.pl/uzytkownik/bezpieczenstwo/skojarz-aplikacje?code=
jest tam pole expires_in, czy konieczne jest ponawianie tego kroku tzn. przechodzenie po wygaśnięciu na Allegro i znów potwierdzanie czy można bazować na raz wystawionym device_code a potem odświeżanie tokenu poprzez
https://{{AllEnv}}/auth/oauth/token?grant_type=urn:ietf:params:oauth:grant-type:device_code&device_code=.
Zależy mi na tym, żeby automat nie potrzebował przejścia na stronę Allegro za każdym razem po wygaśnięciu kodu uzyskanego z oauth/device. Proszę o pomoc, może coś źle zrozumiałem.

**Comment by mjonninen** [comment]
Witam,
czy mając podłączone to samo konto Allegro w Baselinker i we własnej integracji, możliwe są problemy natury blokowania 1 czy 2 integracji albo samego konta? Baselinkera używamy do pobierania informacji o zamówieniu a własna integracja zawęża się do tworzenia i podpinania przesyłki do zamówień.
