### ISSUE TITLE
Problem z wysyłką Pocztą Polską

### ISSUE THREAD

**Issue by jzby-dev** [allegro/allegro-api#8307]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [x ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

<!-- [Zapoznaj się z zasadami korzystania z forum API Allegro na GitHubie](https://github.com/allegro/allegro-api/wiki#zasady-korzystania-z-forum-api-allegro-na-githubie)

Próbuję nadać przesyłkę Poczta Polską za pośrednictwem Allegro i od wczoraj jest z tym problem. Request:

{
    "serviceId": "093d950b-8497-4cc7-aa2a-6081e5e7e7e2",
    "receiver": {
        "address": {
            "street": "xxxxx",
            "postCode": "xxxxx",
            "city": "xxxxx",
            "countryCode": "PL"
        },
        "email": "xxxxxx@allegromail.pl",
        "name": "xxxxx",
        "company": "xxxxx",
        "phone": "xxxxx",
        "pointId": null
    },
    "pickup": {
        "address": {
            "street": "xxxxx",
            "postCode": "xxxxx",
            "city": "xxxxx",
            "countryCode": "PL"
        },
        "email": "xxxxx",
        "name": "xxxxx",
        "company": "xxxxx",
        "phone": "xxxxx",
        "pointId": "xxxxx"
    },
    "type": "PACKAGE",
    "label": {
        "fileFormat": "ZPL",
        "referenceNumber": "F_2024_03778"
    },
    "items": [
        {
            "weight": {
                "value": 2,
                "unit": "KILOGRAM"
            },
            "dimensions": {
                "height": {
                    "value": 27,
                    "unit": "CENTIMETER"
                },
                "width": {
                    "value": 26,
                    "unit": "CENTIMETER"
                },
                "depth": {
                    "value": 27,
                    "unit": "CENTIMETER"
                }
            },
            "description": "Elektronika",
            "value": {
                "amount": 0,
                "currency": "PLN"
            }
        }
    ]
}

Odpowiedź:
Array
(
    [id] => 33f1fdae-e7e7-4936-bd4c-5e7fd8e1a5b0
    [parcelId] => 
    [status] => ERROR
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => VALIDATION_ERROR
                    [message] => Communication error with carrier's API occurred
                    [details] => 
                    [path] => parcelIds[%s]
                    [userMessage] => Wystąpił błąd komunikacji z API przewoźnika
                )

        )

)

**Comment by jzby-dev** [comment]
Obcięło mi część treści, dodaję request i odpowiedź serwera:
Obcięło mi część treści, dodaję request i odpowiedź serwera:
{
    "serviceId": "093d950b-8497-4cc7-aa2a-6081e5e7e7e2",
    "receiver": {
        "address": {
            "street": “xxxxx”,
            "postCode": “xxxxx”,
            "city": "xxxxx",
            "countryCode": "PL"
        },
        "email": "xxxxx",
        "name": "xxxxx",
        "company": "xxxxx",
        "phone": "xxxxx",
        "pointId": null
    },
    "pickup": {
        "address": {
            "street": "xxxxx",
            "postCode": "xxxxx",
            "city": "xxxxx",
            "countryCode": "PL"
        },
        "email": "xxxxx",
        "name": "xxxxx",
        "company": "xxxxx",
        "phone": "xxxxx",
        "pointId": "249319"
    },
    "type": "PACKAGE",
    "label": {
        "fileFormat": "ZPL",
        "referenceNumber": "F_2024_03778"
    },
    "items": [
        {
            "weight": {
                "value": 2,
                "unit": "KILOGRAM"
            },
            "dimensions": {
                "height": {
                    "value": 27,
                    "unit": "CENTIMETER"
                },
                "width": {
                    "value": 26,
                    "unit": "CENTIMETER"
                },
                "depth": {
                    "value": 27,
                    "unit": "CENTIMETER"
                }
            },
            "description": "Elektronika",
            "value": {
                "amount": 0,
                "currency": "PLN"
            }
        }
    ]
}





Array
(
    [id] => 33f1fdae-e7e7-4936-bd4c-5e7fd8e1a5b0
    [parcelId] => 
    [status] => ERROR
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => VALIDATION_ERROR
                    [message] => Communication error with carrier's API occurred
                    [details] => 
                    [path] => parcelIds[%s]
                    [userMessage] => Wystąpił błąd komunikacji z API przewoźnika
                )

        )

)

**Comment by PrzemyslawLukanowski** [comment]
Powodem tego błędu były problemy po stronie Poczty Polskiej. Otrzymaliśmy informację, że sytuacja powinna już wrócić do normy, możesz ponowić request.
