### ISSUE TITLE
WZA Poczta Polska błąd

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#8308]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

przy probie stworzenia przesylki trace_id: 6209e1b13fe9834e  dostajemy blad 500: Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.

**Comment by PrzemyslawLukanowski** [comment]
Powodem tego błędu były problemy po stronie Poczty Polskiej. Otrzymaliśmy informację, że sytuacja powinna już wrócić do normy, możesz ponowić request.

**Comment by d3stozaur** [comment]
Faktycznie już działa, dzieki.
