### ISSUE TITLE
Nowy plik CSV

### ISSUE THREAD

**Issue by BI-PLAST** [allegro/allegro-api#8310]
Dzień dobry, poproszę o przekazanie przykładowego pliku CSV po lutowych zmianach / link do specyfikacji technicznej / opis formatu pliku (z nowym rekordem). 

Chcemy przygotować się na zmiany, by wiedzieć jak rozliczać płatności od klientów z systemem ENOVA. Chodzi o księgowość. Wypłaty środków, to co dostajemy teraz o północy, ale po zmianach plus ewentualne instrukcje dla informatyków.

**Comment by BI-PLAST** [comment]
Allegro wysłało nas wcześniej tu. Proszę – sprawdzić poniżej.

 

To gdzie uzyskam w końcu jakieś informacje?

 

 

Dzień dobry,

Dziękuję za doprecyzowanie.

Jeśli chodzi o sprawy zewnętrznych aplikacji, które chce Pan łączyć z Allegro, może Pan  te kwestie śmiało konsultować na githubie - platformie dla wystawiających na Allegro.pl

Podsyłam link - https://github.com/allegro/allegro-api

Chciałabym dodać, że po mojej wiadomości na Pana adres e-mail może zostać wysłana krótka ankieta dotycząca mojej pracy. Zachęcam do jej wypełnienia. 

Życzę miłego dnia!


Pozdrawiam
// Magdalena Sito
Zespół Allegro

**Comment by Lukasz-Zurek** [comment]
@BI-PLAST Podkreślam raz jeszcze - jeśli Twoja sprawa dotyczy masowej edycji/wystawiania ofert poprzez plik CSV, czy też innej funkcjonalności Allegro, ale spoza publicznego API -  powinieneś otrzymać odpowiedź po kontakcie poprzez formularz. Najwyraźniej zostałeś źle przekierowany przez konsultanta. 

Natomiast jeśli sprawa dotyczy funkcjonalności dostępnej wyłącznie po stronie zewnętrznego narzędzia, z którego korzystasz - musisz skontaktować się z supportem narzędzia. Zakładam, że chodzi o wspomniany system ENOVA.
