### ISSUE TITLE
Punkty typu POP dostępne dla klientów w ramach metody dostaw Allegro Paczkomaty InPost, brak możliwości nadania w Inpost. Możliwy bug.

### ISSUE THREAD

**Issue by radz2k** [allegro/allegro-api#8311]
Pytanie dotyczy przesyłek nadawanych w ramach metody Allegro Paczkomaty InPost w ramach tzw. oferty specjalnej Allegro - InPost.

Korzystamy z tej metody dostawy od kilku lat i nigdy do tej pory klienci nie mieli możliwości wyboru punktów typu Pick Up Point (POP) w ramach tej metody dostawy.

W ostatnich kilku dniach otrzymujemy kolejne zamówienia z wysyłką do punktów POP zamiast do Paczkomatów.

Przykładowe kody:
POP-ILA9
POP-KRA228

![image](https://github.com/allegro/allegro-api/assets/2965966/28b00824-4cb5-4914-a348-d8c237e980da)

![image](https://github.com/allegro/allegro-api/assets/2965966/0741c01f-0ad2-4e91-aa86-8df6fd0a4cb3)

Problem polega na tym, że paczek tych nie możemy później nadać w serwisie InPost (ani po ich API, ani przez ich serwis WEB), ponieważ nie istnieje skojarzenie z Allegro po adresie mailowym. Podając adres mailowy klienta przy nadawaniu przesyłki, nie zostaje znalezione zamówienie w Allegro.

Wnioskujemy z tego, że albo w Allegro zostały omyłkowo zaczytane punkty typu POP (Pick Up Point) do wyboru w ramach metody Allegro Paczkomaty InPost, a nie powinny, lub też punkty POP zostały udostępnione do wyboru klientom celowo w ramach ustaleń Allegro -> Inpost, jednak InPost nie obsłużył tego po swojej stronie.

W rezultacie nie da się nadawać tych paczek w ramach usługi Smart za 0zł i trzeba to robić na własny koszt.

Istotne ze względu na możliwą skalę problemu.

Prosiłbym o zbadanie tego tematu.

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję tę kwestię po naszej stronie, jednak z uwagi na to, że nie jest to problem stricte związany z naszym API sugerowałbym także zgłoszenie go bezpośrednio do InPost. Wrócę z informacją, gdy uda mi się ustalić więcej szczegółów.

**Comment by radz2k** [comment]
Właśnie nie koniecznie problem jest po stronie InPost, to zależy od tego czy punkty typu PickUp powinny w ogóle być dostępne w ramach dostawy do paczkomatów, jeśli nie, to problem jest po stronie Allegro, że udostępnia te punkty klientom do wyboru w ramach dostawy "Allegro Paczkomaty InPost". Ta opcja wydaje się bardziej prawdopodobna, zważywszy na to, że nigdy nie było z tym problemu (od lat wysyłamy setki paczek miesięcznie tą metodą) i punkty typu PickUp nigdy nie były dostępne w ramach dostawy Allegro Paczkomaty InPost.

**Comment by MartaNowaczyk** [comment]
Tak jak napisał @PrzemyslawLukanowski - po swojej stronie, staramy się uzyskać szczegółowe informacje na ten temat, także wrócimy z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowaliśmy ten problem po naszej stronie - nie jest to błąd, że w ramach metody Allegro Paczkomaty InPost, kupujący mogą wybierać również tzw. PaczkoPunkty. Zmianę tę [wdrożyliśmy w w październiku 2023](https://allegro.pl/pomoc/aktualnosci/od-dzis-mozesz-odbierac-przesylki-inpost-rowniez-w-punktach-odbioru-2Y6G1E8qGU1). Ponieważ nie stwierdziliśmy żadnego błędu po stronie naszego API, możesz skorzystać z [formularza kontaktowego ](https://allegro.pl/pomoc/kontakt) i przekazać konkretny numer zamówienia, hashowany mail, z którym jest problem, a odpowiedni zespół zweryfikuje tę sytuację. Sugeruję także, tak jak wspomniałem wcześniej, kontakt z przewoźnikiem, aby wyjaśnić dlaczego nie możesz nadać przesyłki do PaczkoPunktu w ramach rozliczeń w Allegro Smart.
