### ISSUE TITLE
Możliwość pobrania pliku faktury dodanego do zamówienia

### ISSUE THREAD

**Issue by krychaj5** [allegro/allegro-api#8312]
Witam, chciałbym pobrać fakture dodaną już do zamówienia w celu wysłania jej w załączniku wiadomości do klienta

niestety zasób [GET /order/checkout-forms/{id}/invoices](https://developer.allegro.pl/documentation/#operation/getOrderInvoicesDetails)

zwraca jedynie podstawowe informacje o pliku faktury

https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#jak-pobrac-informacje-o-fakturach-dodanych-do-zamowienia

**Comment by MartaNowaczyk** [comment]
Zasób ma służyć do przekazywania faktury VAT kupującemu, który może ją później pobrać np. w szczegółach zamówienia. Sprzedający może pobrać dodaną do zamówienia fakturę w zakładce "Zamówienia od kupujących".
