### ISSUE TITLE
Allegro sandbox - aktywacja konta

### ISSUE THREAD

**Issue by szymonwawak** [allegro/allegro-api#8313]
Dzień dobry,

Prosiłbym o aktywację sandboxowego konta o loginie WAWITretail
Dodatkowo chciałbym wspomnieć o problemie jaki przytrafił mi się podczas przeklikiwania aktywacji konta bankowego - posłużyłem się numerem konta z instrukcji do API. Na maila otrzymałem informację z portalu sandbox o tym, że rozpoczęto zmianę konta do wypłat oraz przycisk "Potwierdź nowe konto". URL prowadził do konta sandboxowego jednak po jego kliknięciu zostałem przekierowany do środowiska produkcyjnego.

**Comment by MartaNowaczyk** [comment]
Konto WAWITretail aktywowałam. Dziękuję za informację.
