### ISSUE TITLE
Czy API Allegro pozwala na monitorowanie cen w ofertach innych sprzedających np. na podstawie EAN?

### ISSUE THREAD

**Issue by aygore1** [allegro/allegro-api#8314]
Cześć, 

czy orientujecie się czy API Allegro pozwala na monitorowanie cen w ofertach innych sprzedających np. na podstawie EAN? W uproszczeniu chodzi o scenariusz w którym listujemy EAN i w oparciu o ten EAN otrzymujemy zakres cenowy danego produktu na Allegro i ID poszczególnych ofert innych sprzedających.

**Comment by MartaNowaczyk** [comment]
Nie ma możliwości wyszukiwania ofert wprost po EAN w API. Można jedynie spróbować uzyskać dostęp do zasobu [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing), który pozwala na przegląd publicznych ofert, jednak dostęp do tego zasobu podlega weryfikacji. Wszelkie szczegóły znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk).
