### ISSUE TITLE
Brakujące produkty TecDoc marki  AUTOFREN (AUTOFREN SEINSA)

### ISSUE THREAD

**Issue by PunktAutoCzesci** [allegro/allegro-api#8315]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Cześć,
poniżej lista produktów TecDoc marki AUTOFREN których brakuje w bazie produktów.
/sale/products
Proszę o informację po ich dodaniu.

D4867
D4868
D4881
D4938
2874
2875
C91000
D43360S
D43579S
D43584S
D025541AK
D43578S
D1750
D7286C
D44092S
D43618A
D44153S
D44091S
D43164A
D42258C
D43064C
D43084A
D43231C
D4519
D4780
D11059
D41022
D41402
D43064K
D44010S
D7524C
D7571
D025787AK
D41227

**Comment by Lukasz-Zurek** [comment]
To ja tak ogólnie wyjaśnię, że mamy bazę od TecDoc, ale to nie oznacza, że posiadamy wszystkie produkty z TecDoc w naszym katalogu. Wskazane produkty są wyszukiwane poprzez zasób /sale/products (choć nie posiadają one specyfikacji TecDoc). 

Wspominałem w innym wątku, że aktualizacja bazy odbywa się co pewien czas. Może się jednak zdarzyć, że niektóre produkty po prostu nie posiadają TecDoc, ponieważ zostały one utworzone przez Sprzedawców w czasie, gdy brakowało danego produktu.

**Comment by PunktAutoCzesci** [comment]
Rozumiem, jednak nie pokrywa się to z tym co widzę.
Są tysiące o ile nie miliony produktów które już posiadały produkt allegro
a pomimo to został w katalogu utworzony osobny produkt TecDoc.
Tylko niewielka część zgłaszanych przeze mnie braków to produkty nowe (nowe
w TecDoc).
Jak na razie powtarzalna cecha to różne nazwy marki w allegro w porównaniu
z TecDoc.
Nie chcę łączyć swoich produktów z produktami nie TecDoc, bo nie ma ich
cyklicznych aktualizacji.
Zgodnie z tym co mówi dział katalogu allegro, duplikaty będą usuwane. W
przypadku duplikatów TecDoc i zwykłych zapewne zostanie produkt TecDoc.
Być może dzięki temu uda się wam ustalić co konkretnie było przyczyną i
wprowadzić rozwiązanie systemowe zamiast łatać braki.

pon., 22 sty 2024, 07:47 użytkownik Lukasz-Zurek ***@***.***>
napisał:

**Comment by Lukasz-Zurek** [comment]
Rozumiem. Przyznam, że ten proces jest całkowicie poza naszym zespołem (nie dotyczy stricte samego API) i nie byliśmy świadomi tego typy problemów. W tym momencie bardziej pośredniczymy między Tobą, a zespołem, który na co dzień odpowiada za TecDoc po stronie Allegro. 

Otrzymałem natomiast informacje o tym, że występował problem z niektórymi produktami (było ich łącznie **6334**) z TecDoca - dla których sprzedawcy otrzymywali błąd: “Nie udało się wyświetlić produktu.”. Te produkty zostały już przez nas poprawione.

Drugi problem to brak parametru dotyczącego wersji TecDoc, dla którego produkty mogą nie być zwracane. Cały czas pracujemy nad tym, aby to poprawić.

Jest jeszcze rzecz, o której wspomniałem w poprzednim poście - kwestia aktualizacji z bazy TecDoc i przemapowywania produktów, w przypadku problemów po aktualizacji. Ten proces dzieje się również poza naszym zespołem i nie jest to proces w pełni automatyczny.
