### ISSUE TITLE
No access to the specified resource.

### ISSUE THREAD

**Issue by ATomasRZE** [allegro/allegro-api#8316]
Próbuję uzyskać listę zamówień za pomocą „/sale/offers”, ale nawet gdy używam obu drugich tokenów, nadal pojawia się ten sam błąd:

{"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"No access to the specified resource."}]}

gdzie można to włączyć w piaskownicy?

**Comment by Lukasz-Zurek** [comment]
Przede wszystkim zasób /sale/offers służy do pobierania listy ofert. Do uzyskania listy zamówień służy [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET).

Prześlij proszę trace-id, natomiast jeśli go nie posiadasz - przekaż nam pełen request i response, zgodnie z moim [wcześniejszym](https://github.com/allegro/allegro-api/issues/8246#issuecomment-1903346249) zaleceniem.

**Comment by ATomasRZE** [comment]
```
public function getAllegroOffers()
    {
        $token = $this->getAccessToken();
        //$token = \Configuration::get('COFISCZ_ALLEGRO_AUTH_TOKEN');

        $headers = array("Authorization: Bearer {$token}","accept: application/vnd.allegro.public.v1+json","Content-Type: application/vnd.allegro.public.v1+json");
        $url = $this->getUrl()."/order/checkout-forms";

        $ch = $this->getCurl($headers, $url);
        $result = curl_exec($ch);
        curl_close($ch);

        var_dump($result);
    }
```

```
public function getAccessToken(): string
    {
        if(\Configuration::get('COFISCZ_ALLEGRO_SANDBOX')) {
            $authorization = base64_encode(\Configuration::get('COFISCZ_ALLEGRO_SANDBOX_CLIENT_ID').':'.\Configuration::get('COFISCZ_ALLEGRO_SANDBOX_CLIENT_SECRET'));
            $url = \Configuration::get('COFISCZ_ALLEGRO_API_SANDBOX_URL_TOKEN');
        }else{
            $authorization = base64_encode(\Configuration::get('COFISCZ_ALLEGRO_CLIENT_ID').':'.\Configuration::get('COFISCZ_ALLEGRO_CLIENT_SECRET'));
            $url = \Configuration::get('COFISCZ_ALLEGRO_API_URL_TOKEN');
        }
        $headers = array("Authorization: Basic {$authorization}","Content-Type: application/x-www-form-urlencoded");
        $content = "grant_type=client_credentials";

        $ch = $this->getCurl($headers, $url, $content);
        $tokenResult = curl_exec($ch);
        $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        if ($tokenResult === false || $resultCode !== 200) {
            exit ("Cannot get AccessToken");
        }
        return json_decode($tokenResult)->access_token;
    }
```

Response now is:
`
{"errors":[{"code":"EmptyUserIdException","message":"user_name from JWT cannot be empty","details":null,"path":"/order/checkout-forms","userMessage":"user_name from JWT cannot be empty"}]}`

**Comment by Lukasz-Zurek** [comment]
@ATomasRZE Udzieliłem odpowiedzi w [tym](https://github.com/allegro/allegro-api/issues/8246#issuecomment-1905601217) wątku.
