### ISSUE TITLE
Blokada API podczas uwierzytelniania

### ISSUE THREAD

**Issue by XardasLord** [allegro/allegro-api#8317]
Jestem notorycznie blokowany zarówno na produkcyjnym jak i testowym (sandbox) API.

Dla poniższego URL'a czyli zwrotki z autoryzacji dostaję blokadę:

https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?scope=&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A6010%2Fauth%2Fallegro-auth-callback%2Fmy-test&state=CfDJ8IrydYoEV75AgyFVaTxrcxre_2iBc2Uv2_4gtTB4CEJhSxkn-jYtlrsl8SQbv00zTgDdzBcv2xlDl0u4_0RefcErhvLAIBwcj1gSY59U_dHMK_EtEO07ws9tsVdEbieFG_VAO4XXQANSV8ADXmgYKTl4HLEMtpRsqIL2P3kRgctJFDmGsimIrr_8vXmnh8PCElKOwQlo63M0A9fqKCzu8X0SlhReLivv8b1wi6whG5z-DCBpWXDlU5NNpTWJHr_47Q&client_id=43ebcac1ac9940c0b66189eeed467da0

Blokada jaką dostaję:
![image](https://github.com/allegro/allegro-api/assets/29070326/2717cb50-fb52-4d85-b6c0-dfc290ff5593)

**Comment by MartaNowaczyk** [comment]
Sprawdzamy przyczynę blokady. Wrócę z informacją.
