### ISSUE TITLE
Zmiana statusu na "odebrane" w Allegro

### ISSUE THREAD

**Issue by Levena007** [allegro/allegro-api#8318]
Witam,
Byłabym wdzięczna za informację na jakieś podstawie odbywa się zmiana statusu w zamówieniach Allegro na "odebrane".
W chwili obecnej w naszym zintegrowanym koncie status "wysłane" na "odebrane" zmieniamy ręcznie po sprawdzeniu statusu numeru listu przewozowego w DPD.
Zastanawiam się czy dane mówiące że klient odebrał zamówienie znajdują się w systemie Allegro i powinny być zaciągane z DPD jako zintegrowanego z wami Allegro, lub też my powinniśmy to w jakiś sposób zaimplementować.

Będę wdzięczna za odpowiedź

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Witam, rozumiem, że nie widzicie tego statusu w swojej integracji? Jeśli tak, to statusy przesyłek można pobrać przez API [GET /order/carriers/{carrierId}/tracking?waybill={waybill}](https://developer.allegro.pl/documentation/#operation/getAllegroParcelTrackingUsingGET), jednak ma on zastosowanie wyłącznie dla przesyłek przewoźników nadanych w ramach Wysyłam z Allegro. Więcej informacji w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-pobrac-historie-statusow-przesylek). Statusy te są

**Comment by Levena007** [comment]
Witam, rozumiem, że w przypadku umowy własnej musimy się bezpośrednio zintegrować z DPD? Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Jeśli nie działacie przez WZA to w takim wypadku bezpośrednio z DPD. Jeśli macie umowę własną, korzystacie z WZA przez API Allegro i dodacie tę umowę w [ustawieniach](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia) allegro, to nie musicie bezpośrednio z DPD.
