### ISSUE TITLE
Ograniczenie ilości znaków nazwy ulicy

### ISSUE THREAD

**Issue by daniel93333** [allegro/allegro-api#8319]
Allegro ogranicza maksymalną długość nazwy ulicy do 35 znaków, tymczasem najdłuższa nazwa ulicy w Polsce to 56 znaków.

**Comment by MartaNowaczyk** [comment]
Jeśli problem ten dotyczy API i przez to masz problemy z prawidłowymi danymi podaj proszę trce-id wywołania. Jeśli to kwestia działania całego allegro napisz proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
Gdy wysyłasz zgłoszenie opieraj się na szczegółowych informacjach - podstawa, to gdzie występuje problem (jaki endpoint), podaj też przykład np. wspomnianą ulicę itd.

**Comment by MartaNowaczyk** [comment]
Nie mogę znaleźć tego commandId. Czy na pewno jest poprawny? Może lepiej podaj trace-id z nagłówka odpowiedzi.
Tak czy inaczej długość tego pola nie jest zależna tylko od nas, jest też zależna od przewoźnika, bo trzeba sobie zdawać sprawę, że dane z naszego API są dalej przekazywane do przewoźników, którzy mają też swoje zasady, przez co musimy się do nich dostosować i zwracamy odpowiednie komunikaty błędów.

**Comment by daniel93333** [comment]
Możliwe, że jest już nieaktualny, bo to sprzed kilku dni.
Ale jeśli chodzi o Wasz argument to nie zgodzę się z nim, ponieważ przewoźnikiem było Allegro One i to nie w wersji UPS...

**Comment by MartaNowaczyk** [comment]
Na ten moment 35 znaków zostaje, ale jak podasz nazwę ulicy, której nie da się w żaden sposób skrócić, to przekażę zespołowi odpowiedzialnemu za WZA.

**Comment by daniel93333** [comment]
Proszę bardzo:
Bulwary Miast Partnerskich-Bulwar Loughborough
Generała Michała Karaszewicza - Tokarzewskiego
Podpułkownika Stanisława Sowiźrała-Sobolewicza
por. Bronisława Skury-Skoczyńskiego"Robotnika"
Tadeusza Marii Barbary Włodzimierza Fijewskich
bł. ks. phm. Stefana Wincentego Frelichowskiego
Szkolny Park Sportowy im. Janusza Kusocińskiego
Aleja 28 Słupskiego Pułku Lotnictwa Myśliwskiego
III Łużyckiej Dywizji Artylerii Przeciwlotniczej
Przyjaciół Wielkiej Orkiestry Świątecznej Pomocy
Bulwary Miast Partnerskich-Bulwar Schwäbisch Hall
im. Roberta Baden-Powella Naczelnego Skauta Świata
Most 18 Bielskiego Batalionu Desantowo-Szturmowego
Samodzielnego Dywizjonu Artylerii Przeciwlotniczej
Węzeł Łagiewnicki im. ks.kard. Adama Stefana Sapiehy
Most im. Karola Olszewskiego i Zygmunta Wróblewskiego
Rynek Stefana Kardynała Wyszyńskiego - Prymasa Polski
Organizacji Młodzieży Towarzystwa Uniwersytetów Robotniczych

**Comment by MartaNowaczyk** [comment]
Te ulice idzie skrócić do 35 znaków, większość zawiera imiona i pełne nazwy których nie trzeba rozpisywać. Np.:
Gen. M.Karaszewicza-Tokarzewskiego
Ppłk. S. Sowiźrała-Sobolewicza
por. B. Skury-Skoczyńskiego
T.M.B.W. Fijewskich
al.28 Słupskiego P.L.M.
Org.Młodzieży Tow.Uniw.Robotniczych
Bulw.Miast Partn.-Bulw.Loughborough

**Comment by daniel93333** [comment]
No dobrze, tylko proszę zaproponować skrypt, który miałby to robić.
Mam nadzieję, że nie proponujecie robić tego ręcznie bo relikt minionej epoki, a jeśli już to wy powinniście poskracać te nazwy w waszej bazie, bo to od was przychodzą adresy, które nie spełniają waszych wymogów....

**Comment by MartaNowaczyk** [comment]
Rozumiem, że pisząc od nas masz na myśli zamówienia. Niestety na ten moment nie mamy w planach zmian w tym zakresie i  po przekroczeniu limitu pozostaje edycja nazwy ulicy we własnym zakresie.
