### ISSUE TITLE
Token i refreshToken-czy jest możliwość zmiany czasu życia tokenów

### ISSUE THREAD

**Issue by SzymonZasada** [allegro/allegro-api#8321]
Cześć
Jest jakakolwiek możliwość tymczasowej zmiany czasu życia tokena na allegro sandbox?
 np token wazny 10 min a refreshToken wazny 1 dzien ?

**Comment by Lukasz-Zurek** [comment]
Nie, nie ma takiej możliwości.

**Comment by jezewskiBNetrox** [comment]
> Cześć Jest jakakolwiek możliwość tymczasowej zmiany czasu życia tokena na allegro sandbox? np token wazny 10 min a refreshToken wazny 1 dzien ?

@SzymonZasada Jeżeli odświeżysz token po 10 minutach, to stary przestanie działać. Więc teoretycznie możesz samemu token "wygaszać" po 10 minutach i wydaje mi się, że nikt ci nie zabroni.

@Lukasz-Zurek Jest jakiś limit generowania tokenów na dzień? ;)

**Comment by Lukasz-Zurek** [comment]
@jezewskiBNetrox Tego zdradzić nie możemy :) Mogę jedynie potwierdzić, że w naszym API obowiązuje limit dla liczby access tokenów, które możesz wygenerować w określonym czasie dla jednego użytkownika - jeśli zostanie on przekroczony, w odpowiedzi zwrócimy błąd 429. Nie mówimy otwarcie o tym jaki jest limit, z uwagi na zabezpieczenie przed nieautoryzowanymi próbami uzyskania dostępu.

**Comment by Lukasz-Zurek** [comment]
@SzymonZasada W przypadku, gdy access token usera wygasł - używasz refresh tokena w celu wygenerowania nowej pary tokenów (access + refresh). Refresh token zawsze jest ważny przez 3 miesiące i po pierwszym odświeżeniu możesz z niego korzystać jeszcze przez 60 sekund. Te 60 sekund buforu wprowadziliśmy na wypadek, gdyby występowały problemy np. po stronie Twojej aplikacji, czy też nieoczekiwane problemy po naszej stronie.
