### ISSUE TITLE
How to automatically get a token?

### ISSUE THREAD

**Issue by masterlan01** [allegro/allegro-api#8324]
Hello,
I have registered my application "MotoSearch" on apps.developer.allegro.pl. This application will be hosted on my server and will run as a PHP script without involving users and their browsers. It will perform GET requests to search for products and offers using the REST API.

Could you please advise on how to automatically obtain a token for executing these requests **without human involvement**?

**Comment by MaciejFrackowiak** [comment]
You are not able to obtain a token without user interaction. The user must give consent to make a request in his name. Please, check [our tutorial](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY) where we describe all of the available authentication methods.

**Comment by MaciejFrackowiak** [comment]
We are not responsible for giving access to /offers/listing. Please, send your request directly to [Allegro support](https://allegro.pl/pomoc/kontakt).

**Comment by masterlan01** [comment]
thank you
