### ISSUE TITLE
Shipping price list named: default 

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#8326]
Hi there, 

when we were testing something, we got the error message "The user does not have a shipping price list named: default". So I renamed the shipping price list (even though there was only 1) and tried to list the products again via API and I still got the same error.

Here is shown that I had only 1 price list and it was named default: 
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/5c3d2912-21c8-4880-859b-af31ca64e958)

Here you can see that with only one price list, it should not even be needed to rename it to "default": 
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/d0e9e884-680a-4ce6-ab9d-15a5bab60131)

The only thing that helped was to delete the Allegro connection from our app a reconnect it for this user again. Is that a bug on your side? Or is this how it should work? 

I would expect that when I renamed the shipping price list to default and tried to send the product via API to allegro again, that allegro would have updated info that there is only 1 shipping price list and it is named default. 

Thank you in advance for your help! 

All the best, 

Dominika

**Comment by Lukasz-Zurek** [comment]
Please send me a trace-id. I will verify it closely.

**Comment by dominikahr** [comment]
Sorry, I do not have it as I already fixed it by deleting the connection between our app and Allegro a reconnecting. Can you please at least tell me how it is supposed to work from your side? 
Is that the intended behavior that I had to renew the connection so that allegro would take into consideration, that the delivery price list was already renamed to default? Or should it already be taken into consideration once we try to list the product via API again? Thank you in advance :)

**Comment by Lukasz-Zurek** [comment]
Ok, it's good that you have already handled it. It's nice to see it. 

It should be already taken into consideration once we try to list the product via API again. If you had similar situation, please just let me know (and please remember about trace-id, it will be needed).
