### ISSUE TITLE
shipment-management/shipments/create-commands NOT_SELLER_ORDER

### ISSUE THREAD

**Issue by EmilooD** [allegro/allegro-api#8327]
Witam,

trace-id: b433b581886b7e28 na środowisku produkcyjnym jest komunikat, że nie jestem właścicielem zamówienia, ścieżka e-mail. Mam dwa konta allegro w ramach, których przetwarzam zamówienia. Konta są połączone. Do tej pory API działało na drugim koncie i nie było problemów z generowaniem wysyłki z zamówień pochodzących z drugiego konta. Dziś dostałem zamówienie z pierwszego konta i otrzymuje błąd NOT_SELLER_ORDER. Wprowadziłem konfiguracje pozwalającą podstawiać e-mail w sekcji sender na odpowiedni z konta pochodzenia, ale bez skutku.

Uprzejmie proszę o pomoc we wskazaniu błędu.

Pozdrawiam
ED

**Comment by Lukasz-Zurek** [comment]
Aby utworzyć paczkę należy być zautoryzowanym na koncie Sprzedającego, do którego należy zamówienie (mapujemy to po zahashowanym adresie e-mail). Tu nic się nie zmieniło i błąd zwróciliśmy prawidłowo.

**Comment by EmilooD** [comment]
Czy to oznacza, że jeśli aplikacja jest autoryzowana poprzez grant_type=authorization_code, to dla każdego konta powinna być osobna rejestracja?

**Comment by Lukasz-Zurek** [comment]
Nie. Rejestrujesz jedną aplikację. Jeżeli posiadasz dwa odrębne konta to każde konto uwierzytelniasz w odrębnym toku. Proces ten opisaliśmy [tutaj](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#autoryzacja-uzytkownika).
