### ISSUE TITLE
API Allegro Ads

### ISSUE THREAD

**Issue by webcosteu** [allegro/allegro-api#8329]
Dzień dobry!

Dla naszego klienta, który jest agencją o statusie Partner, pobieramy statystyki dla Polski przez API, zgodnie ze schematem opisanym tutaj: https://developer.allegro.pl/docs/advertising-agencies-api.

Jednakże, nie mogę odnaleźć informacji w dokumentacji dotyczącej pobierania statystyk z rynku czeskiego. W starym systemie klienta widzę zapytania skierowane pod adres https://edge.allegro.pl/ads-panel/api. Jednak, gdy próbuję wykonać to zapytanie, otrzymuję błąd: {"error":"unauthorized","error_description":"Full authentication is required to access this resource"}. Dodatkowo, nie znalazłem dokumentacji dotyczącej edge.allegro.pl.

Czy moglibyście potwierdzić, czy istnieje możliwość pobierania statystyk z rynku czeskiego poprzez API Allegro Ads?

Z góry dziękuję!

**Comment by Lukasz-Zurek** [comment]
Nie, nie ma takiej możliwości. Nie udostępniamy tego typu zasobów na naszym [publicznym API](https://developer.allegro.pl/documentation).

**Comment by webcosteu** [comment]
proszę o doprecyzowanie, rozumiem, że nie można pobierać danych z rynku czeskiego, czy w ogóle planujecie wprowadzić taką możliwość?
Proszę również powiedzić czym jest https://edge.allegro.pl/ads-panel/api. i co znaczy ten 
błąd: {"error":"unauthorized","error_description":"Full authentication is required to access this resource"}

**Comment by Lukasz-Zurek** [comment]
Nie mamy takiego zasobu na publicznym API, pod https://api.allegro.pl, więc tu niezależnie od rynku - nie ma takiej funkcjonalności. Wskazane API: https://edge.allegro.pl/ads-panel/api nie jest publiczne i nie uzyskasz do niego dostępu.

Jeśli chodzi o ADSy na publicznym API (dostępnym dla wszystkich użytkowników) - mamy już taką sugestię na stronie Github [Discussions](https://github.com/allegro/allegro-api/discussions/4487). Obecnie nie upubliczniamy zasobów Allegro Ads. Jeżeli coś się zmieni w tej sprawie z pewnością zakomunikujemy to na [naszej stronie](https://developer.allegro.pl/news).
