### ISSUE TITLE
Nie działa sekcja "Wielowariantowość" na produkcji

### ISSUE THREAD

**Issue by coobitus** [allegro/allegro-api#833]
Od dzisiaj, mniej więcej od południa nie działa zakłądka "Wielowariantowość" w sekcji Moje oferty - pokazuje się pusta strona :-) Możecie to naprawić jak najszybciej?

**Comment by MartaNowaczyk** [comment]
@coobitus u mnie zakładka się wyświetla. Przeczyść przelądarkę i sprawdź lub użyj innej. W sprawach zakładek w allegro pisz przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).

**Comment by coobitus** [comment]
@MartaNowaczyk teraz faktycznie zaczęła działać, ale przez kilka godzin nie była dostępna. I nie byłą to kwestia przeglądarki :-)
