### ISSUE TITLE
Webhook/Trigger - Powiadomienia o zdarzeniach 

### ISSUE THREAD

**Issue by centosshop** [allegro/allegro-api#8330]
Dzień Dobry
Czy udostępniacie państwo funkcję powiadomień o zdarzeniach na koncie sprzedawcy allegro (trigger/webhook) który byłby wyzwalany i przesyłał do programu informacje o sprzedaży produktu?
Chodzi o to żeby nie odpytywać co kilka chwil API i sprawdzać czy pojawiła się nowa sprzedaż.

**Comment by MaciejFrackowiak** [comment]
Nie, nie obsługujemy webhook'ów.

**Comment by michsko544** [comment]
Czy jest możliwość, że w przyszłości dodacie webhooki? Jeśli tak to mniej więcej kiedy można by się takiej funkcjonalności spodziewać? Pozwoliłoby to na dużo łatwiejsze dwustronne integracje z innymi platformami ecommerce.

Erli już ma tzw hooki, dzięki czemu nie trzeba strzelać CRONem do chwile do API ;)

**Comment by MaciejFrackowiak** [comment]
@michsko544 Na chwilę obecną nie mamy tego w planach. Jeżeli coś ulegnie zmianie, to oczywiście poinformujemy o tym na forum.
