### ISSUE TITLE
za pomocą API mogę uzyskać inne oferty dotyczące produktu?

### ISSUE THREAD

**Issue by yablochnyi** [allegro/allegro-api#8331]
Cześć, czy za pomocą API mogę uzyskać inne oferty dotyczące produktu?
![Снимок экрана 2024-01-23 204203](https://github.com/allegro/allegro-api/assets/75489338/34edf170-ae22-4ee4-8f38-bf7bada90c75)

**Comment by MaciejFrackowiak** [comment]
Nie, nie zwracamy tych informacji w API.
