### ISSUE TITLE
Aktualizacja jednego parametru w wielu produktach

### ISSUE THREAD

**Issue by is-tomaszgasior** [allegro/allegro-api#8332]
`sale/products/{productId}/change-proposals` ma limit 100 sugestii na dzień. Chciałbym zgłosić poprawkę 2 500 produktów, w których błędnie jako język publikacji zamiast języka polskiego jest ustawiony język afrykanerski.  Czy jest na to lepszy sposób niż kolejkowanie tego po API przez wiele dni? Czy można to zrobić jakoś przez obsługę Allegro i jeśli tak, to czy tutaj na GitHubie czy trzeba kontaktować się z konta Allegro?

**Comment by MaciejFrackowiak** [comment]
Nie, w API nie mamy obejścia tego limitu. Możliwe, że obsługa serwisu ma uproszczoną procedurę na to - proszę skontaktuj się bezpośrednio poprzez [formularz](https://allegro.pl/pomoc/kontakt).
