### ISSUE TITLE
Czas odpowiedzi 

### ISSUE THREAD

**Issue by mjaskiewiczSellpander** [allegro/allegro-api#8333]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Nasze pytanie jest odrzucane przez zbyt długi czas oczekiwania na odpowiedź dla klienta ClientID cdeccbeca2294146a17f7abc4a7a44b9. Otrzymujemy taką odpowiedź
"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." Kod odpowiedzi HTTP 0

**Comment by MaciejFrackowiak** [comment]
Proszę doprecyzuj zgłoszenie - do jakiej usługi wysyłałeś żądanie, czy posiadasz trace-id takiego wywołania?

**Comment by mjaskiewiczSellpander** [comment]
Nie zwraca nam trace-id błąd występuje przy następujących endpointach 
 /sale/product-offers/{offerId} -GET
 /sale/offers -GET
  /sale/product-offers/{offerId} -PATCH

**Comment by MaciejFrackowiak** [comment]
Przejrzałem posiadane logi dla podanego ClientID - w ciągu ostatnich 7 dni dosłownie promil zapytań zakończył się timeout'em, co przy skali ponad 1 mln requestów nie jest czymś ponad normę.

**Comment by mjaskiewiczSellpander** [comment]
Również dla aplikacji ClientId ce0b7dc693ca4fce9795405ce544b0a8 występuje analogiczna sytuacja pomimo mniejszej ilości zapytań. Czy macie Państwo podobne zgłoszenia

**Comment by MaciejFrackowiak** [comment]
Dla wskazanego ClientID przy blisko 65 tysiącach wywołaniach w okresie ostatnich 7 dni dokładnie 2 (dwa) zakończyły się timeout'em.
