### ISSUE TITLE
Wysyłki Allegro - pole z uwagami dla kuriera

### ISSUE THREAD

**Issue by lasoczczyk** [allegro/allegro-api#8334]
Dodaję paczkę za pomocą:
/shipment-management/shipments/create-commands

Ustawiłem:
    $data->input->referenceNumber='ZAM/N24/4324234';
    $data->input->description='Części LPG';
    $data->input->labelFormat='EPL';

Ale nie widzę w  dokumentacji pola, gdzie mogę wprowadzić uwagi dla kuriera odnośnie dostawy (to co wpisuje nieraz klient), czyli np:
"Nie ma mnie w domu do 13"
"Proszę dzwonić przed dostawą"
"Dostawa od strony rampy"
itd itd....

Jest to dosyć istotne. Jak mogę dodać dodatkowy tekst dla kuriera?

**Comment by MaciejFrackowiak** [comment]
Nie ma możliwości dodania takich informacji - nie ma pola na dodatkowe informacje.

**Comment by lasoczczyk** [comment]
Fatalnie... :( OK dzięki. 
Mogło by się znaleźć w API... 
Ale w sumie klient allegro też nie ma możliwości wpisać uwag dla kuriera, tylko ogólne informacje do zamówienia dla sprzedawcy.
