### ISSUE TITLE
Creation of a product card

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#8335]
Hi there, 

we want to add the possibility to create new product cards (in case the product is not in allegro catalogue) via our app. We tried to create the product card in the sandbox environment but we came across some errors that we do not full understand. Can you please explain more in detail, what the errors mean? 

When we try to create new offer on Allegro Sandbox, we get error message "Matching product not found for the specified ID, or the data necessary to create the product and/or offer was not provided." (trace_id = ea900ed1b7c4bb0). So we found right category to place our new product into and found and fill all required parameters from your resource ("sale/categories/258242/parameters"). But when we try to create this new product (same way as described in your documentation), we get response like this (trace_id = 9c2bb3643fb132a2):

"""
{
"errors": [
{
"code": "PARAMETER_MISMATCH",
"message": "The provided parameter 'Marka'(2928) value (Siemens(2928_212625)) does not match the existing parameter value (Adler(2928_212489))",
"details": null,
"path": "productSet[0].product.parameters",
"userMessage": "The specified product exists. The specified parameter Marka with the value Siemens(2928_212625) does not match the product parameter Adler(2928_212489)."
},
{
"code": "PARAMETER_MISMATCH",
"message": "The provided parameter 'Model'(237206) value (TP501R09) does not match the existing parameter value (BXCO1470E)",
"details": null,
"path": "productSet[0].product.parameters",
"userMessage": "The specified product exists. The specified parameter Model with the value TP501R09 does not match the product parameter BXCO1470E."
},
{
"code": "PARAMETER_MISMATCH",
"message": "The provided parameter 'Kolor dominuj\u0105cy'(129357) value (czarny(129357_3)) does not match the existing parameter value (be\u017cowy/br\u0105zowy(129357_1))",
"details": null,
"path": "productSet[0].product.parameters",
"userMessage": "The specified product exists. The specified parameter Kolor dominuj\u0105cy with the value czarny(129357_3) does not match the product parameter be\u017cowy/br\u0105zowy(129357_1)."
}
]
}
"""

What seems to be the problem? In first response you tell us, that this product was not found (and even if we search for this product in Allegro Sandbox, its not there) and when we provide all necessary data, we get response, that this product exists (and its different brand, different model and different color). When we try to search for this parameters from your response (Adler BXCO1470E) in Allegro main page or "list using form" in Allegro administration, it doesn't find any products.

Thank you in advance for your help! 

All the best, 

Dominika

**Comment by Lukasz-Zurek** [comment]
Thank you for your message. As I see - the values in product's parameters do not match the values which you are providing in the request. The problem is the fact that the product apparently does have some incorrect data for example brand parameter Siemens(2928_212625) (the product's name is EKSPRES SIEMENS TP501R09 EQ.500 (CZERŃ). You can report an incorrect data via [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal), while testing this resource as well.

**Comment by dominikahr** [comment]
**But for this EAN we got the response "Matching product not found for the specified ID"** - so based on what was our product data paired with this incorrect product? Because in that response (trace_id = 9c2bb3643fb132a2) you told us that our product (Siemens TP501R09 black) should be Adler BXCO1470E beige/brown, which is totally different product. Is it based on EAN (4242003837115)? Because if we search this EAN on Allegro Sandbox, if finds no products at all.

To sum it all up: 
1. We tried to list our offer 
2. We got the response "Matching product not found for the specified ID"
3. We tried to create the new product card - we tried to list the offer together with all the necessary data to create a product card) according to this: 
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/5ddb2d94-eba1-411a-b445-94a42d7d264e)
4. We got the information the the product already exists but with a different data

**Comment by Lukasz-Zurek** [comment]
@dominikahr Ok, it's clear, thank you for your patience :) 

There are two problems:

1. The product has invalid parameters (all these three mentioned in the error) - I have already reported this to another department to correct them.
2. There is a problem with searching of this product: **GET sale/products?phrase=4242003837115&mode=GTIN** - so I am consulting this case with a specific department as well.

I will come back with some more information.

Sorry for the inconvenience.

**Comment by dominikahr** [comment]
@Lukasz-Zurek ok, thank you for checking :) We will continue testing with some other product. 

I have one more question: we have sent "KLUDI BOZZ Umyvadlová baterie bez podomítkové tělesa, chrom" as a product name and the final product name provided by allegro was "BOZZ ścienna bateria umywalka uchwyt BOZZ montaż podtynkowy dwuotworowy perlator s-pointer Eco M 24x1 rozety o średnicy 70mm wysięg wylewki 170mm chrom" even though we did not even send the information about the dimensions of the product. So where did this information come from? And is it possible to somehow influence more what the final product name will look like? 
We only found this in the documentation regarding this topic: 
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/74b06c7e-b60d-4499-8ab9-675c73215aa1)

**Comment by Lukasz-Zurek** [comment]
Regarding this previous product - EKSPRES SIEMENS TP501R09 EQ.500 (CZERŃ) - I have already corrected the parameters. Please note that this is a test environment, so sometimes users create products with some incorrect data.

We are still consulting the problem with product's searching (using EAN).

Another thing - the product name - we are verifying it with another department. Please be patient. But if you mean the rules - I can only confirm. There is no other way to influence the product name more. In some of the categories it is an automatic process.
