### ISSUE TITLE
Metoda UploadInvoice

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#8336]
Witam, 

pomimo utworzenia faktury poprzez metode postNewInvoicewgrania oraz wgrania faktury poprzez metodę API UploadInvoice klient nie otrzymał powiadomienia o fakturze. Czy trzeba wykonać jakieś dodatkowe akcje aby uzyskać ten efekt?

**Comment by Lukasz-Zurek** [comment]
Jeżeli faktura została prawidłowo dodana to kupujący powinien automatycznie otrzymać powiadomienie e-mail.

**Comment by Maciej-Wilkosz** [comment]
Prosił bym o weryfikację. Trace-Id po wykonaniu metody Upload-Invoice 8b3870e87e7fc6e0 . Powiadomienie nie zostało przekazane do klienta pomimo poprawnego przesłania faktury

**Comment by Lukasz-Zurek** [comment]
Potwierdzam, że żądanie w API zostało przetworzone prawidłowo. Natomiast w sprawie powiadomienia klient powinien skontaktować się z nami, korzystając z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=d4e05a9d-86a1-441d-978a-f2e1cdc3ae0c).
