### ISSUE TITLE
Using API for parcing Ads on my website 

### ISSUE THREAD

**Issue by Varuosaturg** [allegro/allegro-api#8337]
Hello, 

I have website in Estonia and would like to download ads from Allegro.pl (used car parts). 
Is it possible using API or any other sort of parcing ?

**Comment by Lukasz-Zurek** [comment]
No, it is not possible.

**Comment by Varuosaturg** [comment]
hmm. Did allegro offers some sort of cooperation ? 
Because i know some web site that already using Allegro ads. 
Or all this stuff is not supported by allegro and its just done from their side ?

**Comment by Lukasz-Zurek** [comment]
No. We do sort of cooperation. We just do not have that kind of resources in the [public Allegro API](https://developer.allegro.pl/documentation) so it is not possible to use them through our API.

**Comment by Lukasz-Zurek** [comment]
But what kind of help do you need, as we do not have that kind of resources in our public API? Or maybe you have some general questions about ADS in Allegro or other - then please use our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=76428715-3f41-46f3-ab54-23a87576aae0).
