### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by mchojaczyk** [allegro/allegro-api#8338]
Proszę o aktywację konta na sandbox login: Testowy123456

**Comment by Lukasz-Zurek** [comment]
@mchojaczyk Musisz jeszcze [skonfigurować wypłaty](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat) i skorzystać z naszego symulatora płatności, by to zatwierdzić.

**Comment by mchojaczyk** [comment]
Dodane

**Comment by Lukasz-Zurek** [comment]
@mchojaczyk Aktywowałem.

**Comment by mchojaczyk** [comment]
Dziękuje

**Comment by filip-programist** [comment]
Dzień dobry. Czy mogę również prosić o aktywację? Login: Filto
Podczas aktywacji nie mogę skorzystać z symulatora płatności ponieważ pokazuje się że jest błędny url

**Comment by Lukasz-Zurek** [comment]
@filip-programist Zarejestrowałeś konto zwykłe, stąd zaistniała sytuacja. Przekonwertuj konto na firmowe. Zrobisz to w [tej](https://allegro.pl/moje-allegro/moje-konto/dane-konta) zakładce. Następnie przejdź do ustawień wypłat i skorzystaj ze wspomnianego symulatora płatności.

**Comment by filip-programist** [comment]
Dobrze, dziękuję

**Comment by filip-programist** [comment]
Zrobiłem już wszystko i przekształciłem konto na firmowe i dalej nie mogę nic zrobić. Czy mogę prosić o aktywację?

**Comment by Lukasz-Zurek** [comment]
@filip-programist Odpowiedź otrzymałeś już w [innym wątku](https://github.com/allegro/allegro-api/issues/8374#issuecomment-1916392647).
