### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by Ante1204** [allegro/allegro-api#8339]
Dzień dobry 
Proszę o aktywację konta sandbox "anteeowms". Tworzę jedynie integrację WMS z usługami kurierskimi, więc chciałabym pominąć weryfikację konta bankowego. 
-->

**Comment by Lukasz-Zurek** [comment]
[Konfiguracja rachunku bankowego](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat) i skorzystanie z symulatora płatności są wymagane, by móc aktywować konto na sandboxie. Podkreślam jednak, że jest to środowisko testowe, więc tego typu dane mogą być fikcyjne. Podobnie jak w przypadku symulatora płatności - nie wykonujesz prawdziwego przelewu.

**Comment by Ante1204** [comment]
Ponownie proszę o aktywację. Uzupełniłam konto i dokumenty
Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
@Ante1204 Dziękuję. Aktywowałem już.
