### ISSUE TITLE
Problem z autoryzacją

### ISSUE THREAD

**Issue by Bitnalstream** [allegro/allegro-api#834]
//naprawione

**Comment by Magdalenanieckula1** [comment]
Dzień dobry,
Mam problem z autoryzacją konta na koncie sandbox. Nie mogę wykonać opłaty autoryzacyjnej, gdyż nie działa przycisk Akceptacji. Proszę o pomoc w zakresie autoryzacji konta.
Adres: magdalena.nieckula@white-pr.com

**Comment by MartaNowaczyk** [comment]
@Magdalenanieckula1 podanego maila magdalena.nieckula@white-pr.com nie widzę na Sandboxie. Czy chodzi o konto z #988 czy jeszcze jakieś inne?
