### ISSUE TITLE
Metody Allegro Pay oraz do kosztów wysyłek, progów Smart! i kosztów Smart!

### ISSUE THREAD

**Issue by ricarderobl** [allegro/allegro-api#8340]
Czy będą w przyszłości jak tak to kiedy metody umożliwiające pobieranie tych danych?

Jeżeli są, to prosimy o wskazanie (ostatnio jak sprawdzaliśmy cały czas nie można było tych danych pobrać poprzez REST).

**Comment by Lukasz-Zurek** [comment]
Nie mamy takich funkcjonalności - zachęcam Cię do opisania tej sugestii w dedykowanym miejscu - [Github Discussions](https://github.com/allegro/allegro-api/discussions).

Jeżeli chodzi o Allegro Smart! - w naszym publicznym API udostępniamy jedynie zasoby do sprawdzania klasyfikacji oferty i sprzedawcy. Więcej informacji znajdziesz [tutaj](https://developer.allegro.pl/tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#kwalifikacja-w-programie-allegro-smart).
