### ISSUE TITLE
Have problem with approving  offers/listing

### ISSUE THREAD

**Issue by bodikosa** [allegro/allegro-api#8341]
Make request to through Postman
curl --location --request GET 'https://api.allegro.pl/offers/listing' \
--header 'Authorization: Bearer test' \
--header 'Accept-Language: en-US' \

And got this 
{
    "errors": [
        {
            "code": "NotAcceptableException",
            "message": "Not acceptable representation requested. Please check 'Accept' request header",
            "details": null,
            "path": null,
            "userMessage": "Request contains invalid data. Contact the application author."
        }
    ]
}

Support sand me there

My CLIENT ID 78221d36290c4dd78abcc78b0ac116f7

**Comment by Lukasz-Zurek** [comment]
Jeśli jesteś w [Programie Partnerskim](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm) skontaktuj się ze swoim opiekunem. W innym wypadku skontaktuj się z nami przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). Kryteria dostępu wymieniliśmy w punkcie 3.2 naszego [regulaminu](https://developer.allegro.pl/rules).

Jeśli chodzi o komunikat błędu, upewnij się dodatkowo czy prawidłowo przekazujesz nagłówek "Accept" i wartość "application/vnd.allegro.public.v1+json". Nie zmienia to faktu, że i tak nie posiadasz obecnie dostępu do wskazanego zasobu, j.w. Dostęp do [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) mają tylko zweryfikowane aplikacje.
