### ISSUE TITLE
Obsługa umów kurierskich w środowisku testowym

### ISSUE THREAD

**Issue by Ante1204** [allegro/allegro-api#8342]
Dzień dobry
Czy posiadają Pastwo dane testowe do umów własnych z kurierami aby po prostu można było przetestować działanie zamawiania kuriera przez Państwa api. Zakładka "Umowy własne - wysyłam z allegro"

**Comment by MaciejFrackowiak** [comment]
Nie, nie posiadamy takich danych. Należy je otrzymać od firm kurierskich.
