### ISSUE TITLE
Problem z załącznikami order/checkout-forms/{id}/invoices/{invoiceId}/file

### ISSUE THREAD

**Issue by mariuszsokolowski** [allegro/allegro-api#8343]
Dzień dobry,
podczas dodawania faktury/dowodu zakupu do zamówienia poprzez endpoint
HTTP PUT: https://api.{environment}/order/checkout-forms/{id}/invoices/{invoiceId}/file

Przykład kodu C#:
```
var _client = new HttpClient()
 _client.DefaultRequestHeaders.Add("Accept", $"application/vnd.allegro.public.v1+json");
                    _client.DefaultRequestHeaders.Add("Accept", $"application/pdf");
                    _client.DefaultRequestHeaders.Add("Authorization", $"Bearer {accessToken}");
                    var file = File.ReadAllBytes(URL)
                    var content = new ByteArrayContent(file);
                    HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Put, $"{_baseAPIURL}order/checkout-forms/{id}/invoices/{invoiceId}/file");
                    request.Content = content;
                    var response = await _client.SendAsync(request);
```
dostaję odpowiedź od API o kodzie błędu 504 (GetwayTimeout).
Przykład  response od API:
```
"{\"errors\":[{\"code\":\"ServiceTimeoutException\",\"message\":\"An error occurred\",\"details\":null,\"path\":null,\"userMessage\":\"Query response time exceeded. Try again.\"}]}"
```
Dodam, że załącznik jest mniejszy niż 3MB.
FV w końcu doda się do zamówienia, natomiast może to zająć od 1-X requestów.
Problem jest również przy endpoint:

``` 
messaging/message-attachments/{attachmentId}
```
Dodam, że przy innych requestach wszystko przechodzi bez najmniejszego problemu.
Problem pojawia się zarówno na testowym środowisku sandbox jak i API produkcyjnym.
Proszę o informację w czym może leżeć problem.

**Comment by mariuszsokolowski** [comment]
Proszę dodatkowo o informację kiedy zostają wysyłane przez allegro automatyczne email odnośnie dodanych FV do zamówienia.
![image](https://github.com/allegro/allegro-api/assets/34654351/459ef15f-414e-4deb-97ee-d3fc71b513ff)
Czy dotyczy to tylko firm czy również osób fizycznych (po dodaniu dowodu zakupu).
Od strony API można wywołać w/w funkcjonalność?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj przykładowe wywołanie (wraz z trace-id), dla którego otrzymałeś timeout. Powiadomienia wysyłamy, gdy do zamówienia zostanie dodana faktura - kupujący musi wybrać opcję faktury w swoim zamówieniu, aby finalnie otrzymał wiadomość.

**Comment by mariuszsokolowski** [comment]
Dziękuję za szybką odpowiedź.
Trace-Id z dzisiaj (sandbox):
```
trace-id: c545fc48663abd6a
```
Przykład wywołania jak powyżej:
```
var _client = new HttpClient()
 _client.DefaultRequestHeaders.Add("Accept", $"application/vnd.allegro.public.v1+json");
                    _client.DefaultRequestHeaders.Add("Accept", $"application/pdf");
                    _client.DefaultRequestHeaders.Add("Authorization", $"Bearer {accessToken}");
                    var file = File.ReadAllBytes(URL)
                    var content = new ByteArrayContent(file);
                    HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Put, $"{_baseAPIURL}order/checkout-forms/{id}/invoices/{invoiceId}/file");
                    request.Content = content;
                    var response = await _client.SendAsync(request);
```

**Comment by MaciejFrackowiak** [comment]
@mariuszsokolowski Prośba o przykładowe trace-id z produkcji lub ClientID Twojej aplikacji, dla której uzyskiwałeś timeouty.

**Comment by mariuszsokolowski** [comment]
Poniżej przesyłam trace-id z produkcji
```
trace-id: 171eeb38aa9f23c7
```

**Comment by MaciejFrackowiak** [comment]
Jeśli chodzi o produkcyjny ClientID (z podanego trace-id: 171eeb38aa9f23c7) - dla ponad 900 zapytań nieprawidłowo przekazywałeś {invoiceId} z wywołania. 
Przykładowo - zamiast samego stringa z id to jako invoiceId wklejasz "%7B%22id%22:%223f230612-a353-45a3-b864-5f43146a88b9%22%7D", czyli zserializowany obiekt {"id":"3f230612-a353-45a3-b864-5f43146a88b9"}.

**Comment by mariuszsokolowski** [comment]
Dziękuję za słuszne uwagi Panie Macieju, natomiast sprawdzał Pan poprawne requesty?

Przykładowo Trace-id:6bfdefb55d207f11
Z datą: 28 Jan 2024 15:51:02
oraz requestem
```
{Method: PUT, RequestUri: 'https://api.allegro.pl/order/checkout-forms/49365660-b236-11ee-af72-37bed499****/invoices/d1247a0b-317c-4e92-a03a-d83cba60****/file', Version: 1.1, Content: System.Net.Http.ByteArrayContent, Headers:
{
  Accept: application/vnd.allegro.public.v1+json
  Accept: application/pdf
  Authorization: Bearer secrect
  Content-Length: 148074
}}
```

Co w w/w requescie jest nie tak, że API zwraca status błędu 504?

**Comment by MaciejFrackowiak** [comment]
Dla podanego trace-id=6bfdefb55d207f11 nie znaleźliśmy żadnych błędów czy też problemów od strony naszej usługi. Podobnie jak w przypadku Twoich wywołań na Sandbox widzimy, że połączenie zostaje zerwane przez Twoją aplikację jeszcze zanim zaczniemy je przetwarzać. 
Mała sugestia od nas - możesz zweryfikować, czy wysyłasz poprawną wartość w nagłówku HTTP Content-Length, zgodną z rozmiarem pliku. Na przykładzie podesłanego loga w requeście widzimy wartość 148074 (bajty). Wartość ta wygląda prawidłowo, ale być może faktyczny plik jest mniejszy, serwer czeka na przesłanie reszty danych, zgodnie z określonym rozmiarem, żeby zacząć obsługiwać request, ale nigdy ich nie otrzymujemy.

**Comment by mariuszsokolowski** [comment]
Dziękuję za sugestie.
Jeśli chodzi o rozmiary pliku i Content-Length są one takie same.
