### ISSUE TITLE
Problem podczas zamykania aukcji w API OfferAccessDeniedException

### ISSUE THREAD

**Issue by ircoo2022** [allegro/allegro-api#8345]
Tak jak w tytule podczas próby zamknięcia 

array(2) { ["stock"]=> array(2) { ["unit"]=> string(4) "UNIT" ["available"]=> int(1) } ["publication"]=> array(1) { ["status"]=> string(5) "ENDED" } } 

object(stdClass)#3 (1) { ["errors"]=> array(1) { [0]=> object(stdClass)#4 (5) { ["code"]=> string(26) "OfferAccessDeniedException" ["message"]=> string(9) "Forbidden" ["details"]=> NULL ["path"]=> string(0) "" ["userMessage"]=> string(82) "Access denied. You are not authorized to perform operations on the indicated offer" } } } OfferAccessDeniedException dla oferty ID 15023730445 

taki error zwraca nam 

PS. Inne konta OK są gdy to samo wywołujemy

dane 
array(2) { ["stock"]=> array(2) { ["unit"]=> string(4) "UNIT" ["available"]=> int(1) } ["publication"]=> array(1) { ["status"]=> string(5) "ENDED" } } 
wysyłane są na:
CURLOPT_URL => 'https://api.allegro.pl/sale/product-offers/'.$offer_id,

**Comment by MaciejFrackowiak** [comment]
Jest to poprawny komunikat - próbujesz zamknąć ofertę należącą do konta xxx79013 będąc zautoryzowanym (używając tokena) dla innego konta - a dokładnie konta xxx03398.

**Comment by ircoo2022** [comment]
ok a dlaczego
CURLOPT_URL => 'https://api.allegro.pl/sale/offers?limit=1000&offest=0'

jak odpytuje to zawsze te same oferty tylko rózna ilość?
CURLOPT_URL => 'https://api.allegro.pl/sale/offers?limit=1000&offest=1000', lub CURLOPT_URL => 'https://api.allegro.pl/sale/offers?limit=1000&offest=0', 

to zawsze te same oferty

Są inne zapytania ktore zwracaja oferty dla zalogowanego? ( apki nie zweryfikokowane0

**Comment by MaciejFrackowiak** [comment]
Proszę podaj konkretne trace-id swoich wywołań bym mógł zweryfikować faktyczne dane.

**Comment by MaciejFrackowiak** [comment]
Spójrz też na używany parametr - właściwa nazwa to "offset".
