### ISSUE TITLE
a issue about Edit an offer

### ISSUE THREAD

**Issue by yu-www** [allegro/allegro-api#8346]
Hi,

When I edit an offer by the following request，I got the error response。
How can I modify the size correctly？

thank you for help.

url=https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/7743803019

trace-id=770ee487987fd672

request={"afterSalesServices":{"impliedWarranty":{"id":"9247c128-5f39-4bb5-9f9c-23714860424f"},"returnPolicy":{"id":"12a34ad2-9678-40ed-9bc8-a9f3f7d59943"},"warranty":{"id":"e4dab6a0-d2d1-4f92-b3d9-1811b88a9120"}},"delivery":{"handlingTime":"P60D","shippingRates":{"id":"51b157c2-9a4c-4e52-8503-d15fb5a37ee5"}},"description":{"sections":[{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/117864/8a4c832c4fbba71f191f61f7e50b"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/11eb2e/ab631446456fba04d64d7e06a98d"}]}]},"external":{"id":"3224312211"},"images":["https://a.allegroimg.allegrosandbox.pl/original/11a4ec/4feed214423093069cb6b5c72c5b","https://a.allegroimg.allegrosandbox.pl/original/117864/8a4c832c4fbba71f191f61f7e50b","https://a.allegroimg.allegrosandbox.pl/original/11eb2e/ab631446456fba04d64d7e06a98d","https://a.allegroimg.allegrosandbox.pl/original/1196c7/5226d418462d9e39793124311c28","https://a.allegroimg.allegrosandbox.pl/original/118175/553232da4067a6e9ab830a62a2d6","https://a.allegroimg.allegrosandbox.pl/original/115aa1/2dd508d44ba4914e87660adcce7f"],"location":{"city":"hhhh","countryCode":"BR","postCode":"87878"},"name":"Women's undershirt with a half high collar","offerId":"7743803019","parameters":[{"id":"11323","valuesIds":["11323_1"]}],"payments":{"invoice":"NO_INVOICE"},"productSet":[{"product":{"id":"4a58b6f0-df6f-44a3-b91c-f1368839ed7e","name":"Women's undershirt with a half high collar","parameters":[{"id":"15851","valuesIds":["15851_1"]},{"id":"3786","valuesIds":["3786_1704209"]},{"id":"249882","valuesIds":["249882_1773437"]},{"id":"201041","values":["5"]},{"id":"249512","valuesIds":["249512_1647414"]},{"id":"249516","valuesIds":["249516_1647637"]},{"id":"3766","valuesIds":["3766_1"]},{"id":"4126","valuesIds":["4126_1"]},{"id":"201017","valuesIds":["201017_2317"]},{"id":"225693","values":["96385074"]}]}}],"sellingMode":{"price":{"amount":"455","currency":"PLN"}},"stock":{"available":44,"unit":"UNIT"},"taxSettings":{"rates":[{"countryCode":"CZ","rate":"21.00"},{"countryCode":"SK"},{"countryCode":"PL"}],"subject":"GOODS"}}

response={"errors":[{"code":"PARAMETER_MISMATCH","message":"The provided parameter 'Rozmiar'(249882) value (3XL (46)(249882_1773437)) does not match the existing parameter value (M (38)(249882_1773429))","details":null,"path":"productSet[0].product.parameters","userMessage":"The specified product exists. The specified parameter `Rozmiar` with the value `3XL (46)(249882_1773437)` does not match the product parameter `M (38)(249882_1773429)`."}]}

**Comment by yu-www** [comment]
the environment is in sandbox

**Comment by MaciejFrackowiak** [comment]
You are not able to do such an operation. There is a product (id=4a58b6f0-df6f-44a3-b91c-f1368839ed7e) assigned to the offer, which has a parameter Size with the value "M (38)" (id=249882_1773429). It is a product parameter, so you cannot change its value in the offer. If you want other Size values you should assign the correct product to that offer.

**Comment by yu-www** [comment]
> You are not able to do such an operation. There is a product (id=4a58b6f0-df6f-44a3-b91c-f1368839ed7e) assigned to the offer, which has a parameter Size with the value "M (38)" (id=249882_1773429). It is a product parameter, so you cannot change its value in the offer. If you want other Size values you should assign the correct product to that offer.

So How can I distinguish whether a parameter is a product parameter that I can't change it  or an offer parameter/product parameter that I can change it？

**Comment by MaciejFrackowiak** [comment]
If you retrieve parameters existing in the chosen category by [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) you will receive a response with all the details about parameters. The mask "describesProduct" with the value "true" says that this parameter is a product parameter. You are not able to change product parameters. You can only propose a change in the existing product by [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal).

**Comment by yu-www** [comment]
> If you retrieve parameters existing in the chosen category by [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) you will receive a response with all the details about parameters. The mask "describesProduct" with the value "true" says that this parameter is a product parameter. You are not able to change product parameters. You can only propose a change in the existing product by [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal).

I got the parameters with category id 76034 by [GET /sale/categories/{categoryId}/parameters]. The parameter id 249512 has the mask "describesProduct" with the value "true",but I can change this product parameters.

this product parameter 249512 I can change by [PATCH /sale/product-offers/{offerId}] :
<img width="313" alt="image" src="https://github.com/allegro/allegro-api/assets/5554249/ceba50e0-62e7-4914-bcc2-a67e938c495d">


this product parameter 54 I can't change by [PATCH /sale/product-offers/{offerId}] :
<img width="271" alt="image" src="https://github.com/allegro/allegro-api/assets/5554249/b805bee4-231d-458a-b2a9-898fb6835ea2">

I cannot distinguish the difference between these two product parameter. why one can change and another can't 

thank you for help

**Comment by MaciejFrackowiak** [comment]
We have several product identification rules - one allows distinguishing offers by colors, not by size.

**Comment by yu-www** [comment]
> We have several product identification rules - one allows distinguishing offers by colors, not by size.

Does this mean that I cannot determine which product parameters can be modified and which cannot be modified through APIs

**Comment by MaciejFrackowiak** [comment]
In some cases yes. For example - for "Blouses" (id=76034) the more important parameter is Size (which differentiates products) than Color.
