### ISSUE TITLE
Dodanie aplikacji Allegro do zewnętrznego serwisu

### ISSUE THREAD

**Issue by caroteczek** [allegro/allegro-api#8348]
Mam takie pytanie, zarejestrowałam aplikację Allegro, i dodałam dane Client secret oraz Client password do zewnętrznego programu. ale mam takie błąd kiedy ten zewnętrzny serwis próbuje pobrać umowy:
![image](https://github.com/allegro/allegro-api/assets/157691660/20e6a402-346c-4bae-8637-eefa543e8224)
Jak mogę to rozumieć ?

**Comment by MartaNowaczyk** [comment]
Do weryfikacji przyczyny tego błędu potrzebuję więcej danych np. trace-id z nagłówka odpowiedzi lub commandId dla zapytania z tym problemem. Jeśli nie masz takich danych, to informacje te możesz uzyskać u twórcy narzędzia z którego korzystasz.

**Comment by caroteczek** [comment]
@MartaNowaczyk  Przesyłam potrzebne dane:

trace-id f732e690a4c225d3

zasób:  https://api.allegro.pl/parcel-management/delivery-services

**Comment by MartaNowaczyk** [comment]
Dziękuję za trace-id. Po weryfikacji wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
W tym przypadku jest problem z kontem w WzA - prośba żebyś zastosował się do [instrukcji](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY) - chodzi o akapit "Zanim skorzystasz z API Wysyłam z Allegro..."
