### ISSUE TITLE
Ustawienia fabryczne

### ISSUE THREAD

**Issue by Cervinkashop** [allegro/allegro-api#8350]
Dobry dzień,
 
mamy problem z ustawieniami. Połączenie będzie miało formę API i teraz Allegro zgłasza następujący błąd:
Ustaliliśmy innego producenta (inny) ponieważ na liście producentów z Allegry nie jest ten właściwy producent.
Ale potem podczas importu zwraca błąd, że producent nie jest wyraźnie wybrany:
X Something went wrong:  422 {"errors":[{"code":"ProductValidationException","message":"Nieprawidłowe wartości parametrów: [parameter = Producent [ Wartość niejednoznaczna - inny]]","details":null,"path":"productSet[0].product","userMessage":"Nieprawidłowe wartości parametrów: [parameter = Producent [ Wartość niejednoznaczna - inny]]"}]}
Czy możesz nam doradzić, jak postępować?

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę trace-id, a zweryfikuję ten konkretny przypadek.

**Comment by Cervinkashop** [comment]
trace-id: dfac22ff5af36fe3

**Comment by Lukasz-Zurek** [comment]
W tablicy **"values"** przekaż wartość własną dotyczącą nazwy producenta, której nie posiadamy w słowniku. Może się jednak zdarzyć, że wystawienie oferty z produktem nadal zakończy się podobnym błędem. Kluczowa będzie zatem wartość z listy. Jeżeli na liście producentów faktycznie brakuje preferowanej przez Ciebie wartości, możesz to zgłosić kontaktując się poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).

**Comment by Lukasz-Zurek** [comment]
@Cervinkashop Wszystkie niezbędne informacje na temat zasobów do zarządzania warunkami zwrotów, reklamacji i gwarancji znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-zarzadzac-warunkami-zwrotow) (podlinkowałem poradnik dotyczący warunków zwrotów - returnPolicy, natomiast niżej znajdziesz [informacje zarządzaniu warunkami reklamacji](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-zarzadzac-warunkami-reklamacji) - impliedWarranties i [gwarancji](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-zarzadzac-informacjami-o-gwarancjach) - warranties).
