### ISSUE TITLE
Dopłata do Smarta 

### ISSUE THREAD

**Issue by Eryk1997** [allegro/allegro-api#8351]
Dzień dobry, czy podczas pobierania informacji o zamówieniu z api order/checkout-forms otrzymuję informację jaka była dopłata do SMART? 

Jeśli tak to proszę o przykład, jeśli nie to w jaki sposób mogę to pobrać?

**Comment by MaciejFrackowiak** [comment]
Nie, informacje te nie są dostępne w zamówieniach. Wszelkie opłaty znajdziesz w [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries).
