### ISSUE TITLE
Problem z kontem bankowym przy integracji

### ISSUE THREAD

**Issue by Bingo19B** [allegro/allegro-api#8352]
Dzień dobry,  mamy problem z weryfikacją konta bankowego przy integracji z nowym programem do obsługi zamówień. Teraz przesyłam dokładny komunikat zwrotny, który otrzymujemy: 

Allegro uuid dla requesta 435b1581-8dd5-499f-8882-fc3b512c7bb8 Response: This delivery option requires a verified Polish IBAN number 

Pozdrawiam

Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ x] inny / other

:beetle: **Opis / Description**

**Comment by MaciejFrackowiak** [comment]
Rachunek bankowy, który podajesz do zwrotu pobrań nie jest zweryfikowany. Zrobisz to w zakładce [Ustawienia wypłat](https://allegro.pl/moje-allegro/sprzedaz/ustawienia-wyplat).

**Comment by Bingo19B** [comment]
Rachunek jest dodany w tych ustawieniach i przy nim jest jest znaczek "zaakceptowane"

**Comment by MaciejFrackowiak** [comment]
Szkopuł w tym, że w requeście podany został nr rachunku bankowego składający się z 25 cyfr, a przyjęta wartość dla Polski to 26 cyfr. Proszę sprawdź dokładnie przekazywany numer IBAN.

**Comment by Bingo19B** [comment]
Witaj. 
Dziękujemy za kontakt. 
Odpowiemy najszybciej jak to będzie możliwe. 
W razie potrzeby kontaktu telefonicznego przypominamy iż, pracujemy w godzinach 7.00-15.00 od poniedziałku do piątku. Kontakt telefoniczny pod numerem 95 750 81 12 lub 697 066 295. 

Pozdrawiamy
zespół Bingo-Shop

**Comment by Bingo19B** [comment]
Witaj. 
Dziękujemy za kontakt. 
Odpowiemy najszybciej jak to będzie możliwe. 
W razie potrzeby kontaktu telefonicznego przypominamy iż, pracujemy w godzinach 7.00-15.00 od poniedziałku do piątku. Kontakt telefoniczny pod numerem 95 750 81 12 lub 697 066 295. 

Pozdrawiamy
zespół Bingo-Shop

**Comment by Bingo19B** [comment]
Witaj. 
Dziękujemy za kontakt. 
Odpowiemy najszybciej jak to będzie możliwe. 
W razie potrzeby kontaktu telefonicznego przypominamy iż, pracujemy w godzinach 7.00-15.00 od poniedziałku do piątku. Kontakt telefoniczny pod numerem 95 750 81 12 lub 697 066 295. 

Pozdrawiamy
zespół Bingo-Shop
