### ISSUE TITLE
Delete/Remove Allegro Sandbox Account

### ISSUE THREAD

**Issue by blauweb** [allegro/allegro-api#8353]
Dzień dobry,

Proszę o usunięcie konta client:106863993.
Potrzebuje założyc konto firmowe zamiast tego.

Pozdrawiam,

**Comment by MaciejFrackowiak** [comment]
Możesz zmigrować obecne konto zwykłe na firmowe - zrobisz to z poziomu zakładki [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by blauweb** [comment]
Próbowałem, ale do tego musze zweryfikować numer telefonu, a sms nigdy nie przychodzi.Wysłano z mojego urządzenia Galaxy
-------- Oryginalna wiadomość --------Od: MaciejFrackowiak ***@***.***> Data: 26.01.2024  06:48  (GMT+01:00) Do: allegro/allegro-api ***@***.***> DW: blauweb ***@***.***>, State change ***@***.***> Temat: Re: [allegro/allegro-api] Delete/Remove Allegro Sandbox Account (Issue #8353) 
Możesz zmigrować obecne konto zwykłe na firmowe - zrobisz to z poziomu zakładki Dane konta.

**Comment by MaciejFrackowiak** [comment]
Na Sandbox nie wysyłamy sms - domyślny kod to 123456.

**Comment by MaciejFrackowiak** [comment]
Już wszystko gotowe.

**Comment by blauweb** [comment]
Okazuje się, że jest jakiś błąd na moim koncie, gdzie brakuje informacji o województwie, przez co requesty o dodanie oferty nie wchodzą na sandboxie:
Problem jest opisany tutaj:
#8355

Dostałem sugestie, że mam założyć nowe konto, aby to naprawić, ale nie zamierzam zakładać nowej poczty z powodu błędu w waszym sandboxie. 
Prosiłbym z tego względu o usunięcie mojego konta albo naprawę.

Otworzyłem ten wątek, bo nie jestem zadowolony z analizy i sugestii koleżanki z tamtego wątku.
Przepraszam za kłopot.

**Comment by MaciejFrackowiak** [comment]
Koleżanka postąpiła zgodnie z dostępnymi możliwościami, które posiadamy w kontekście Sandbox. Obecnie możesz zarejestrować kolejne konto na dotychczasowy adres email.
