### ISSUE TITLE
INVALID_STATE podczas wysyłania ogłoszenia

### ISSUE THREAD

**Issue by blauweb** [allegro/allegro-api#8355]
[Sandbox]
login: blaubitTest

Podczas wysyłania oferty mam taki dziwny błąd:
Object { code: "INVALID_STATE", message: "Invalid state null for country PL", path: "location.state", … }
​​​​​
code: "INVALID_STATE"
​​​​​
details: null
​​​​​
message: "Invalid state null for country PL"
​​​​​
path: "location.state"
​​​​​
userMessage: "Wskazane województwo jest nieprawidłowe."

Zupełnie nie jestem w stanie tego odnieść do mojego kodu, jako że paczka z danymi zamówienia nie wymaga takich danych.
W profilu mam wrażenie, że wszędzie mam ustawione/wypełnione dane, tj. gwarancja, zwrot, reklamacja itd.

Czy możliwe jest, że w danych osobowych do firmy, jako kraj pochodzenia i urodzenia dałem inne niż polskie?

**Comment by MartaNowaczyk** [comment]
Sprawdź czy podczas wystawiania oferty masz poprawnie podane województwo "location.province". Tutaj masz [dokumentację](https://developer.allegro.pl/documentation/#operation/createProductOffers):

> province | stringThis field is mandatory if countryCode is set to "PL", for other values, currently, it is ignored. For countryCode equalling "PL", this field must be set to one of the following: DOLNOSLASKIE, KUJAWSKO_POMORSKIE, LUBELSKIE, LUBUSKIE, LODZKIE, MALOPOLSKIE, MAZOWIECKIE, OPOLSKIE, PODKARPACKIE, PODLASKIE, POMORSKIE, SLASKIE, SWIETOKRZYSKIE, WARMINSKO_MAZURSKIE, WIELKOPOLSKIE, ZACHODNIOPOMORSKIE.

**Comment by blauweb** [comment]
Mam tę aplikację przejętą po kimś inny i "location" w ogóle nie jest wysyłane w zapytaniu. I na produkcji, działa to bez problemu. Czy ustawienia w metodzie dostawy mogą tu mieć znaczenie? Bo to byłaby jedyna różnica w konfiguracji pomiędzy produkcją i sandboxem.

**Comment by MartaNowaczyk** [comment]
Najpierw powinieneś się upewnić jakie dane przesyłasz, także aby to zweryfikować podaj trace-id dla tego błędu lub request i response w formacie JSON przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem, że dotyczy GitHuba nr wątku 8355. Nie zmieniamy nic na kontach, poza tym to już nie jest kwestia API.

**Comment by blauweb** [comment]
A czego to jest kwestia, gdzie wasz system decyduje o tym, skąd pobiera dane 'location' podczas otrzymywania żadania? :)
Ja wiem dokładnie jakie dane wysyłam, i nie wysyłam wśród nich "location". Jak wysyłam, to działa. Ale nie powinienem musieć ich wysyłać, zgodnie z waszą dokumentacją. 
I fakt, że działa to na produkcji bez tych danych temu tylko dowodzi.

Rzecz w tym, że na sandboxie nie mam gdzie ustawić województwa w swoim profilu - a tutaj leży problem, że tej informacji brakuje. Silnik waszego API próbuje pobrać dane z mojego profilu, a tam brakuje informacji o województwie. Response (podany w opisie zapytania) jasne pokazuje, że informacja np. country istnieje, ale brakuje informacji state/province.

**Comment by MartaNowaczyk** [comment]
Widzę, że dopisałeś konto i że sprawa dotyczy sandboxa. Niestety, nie mogę dopisać do tego konta województwa. Jednak nie jest to globalny problem, bo na innych kontach jest poprawnie. Możliwe, że jakieś dane nie były wypełnione poprawnie podczas rejestracji i aktywacji konta.

**Comment by blauweb** [comment]
No dobrze, ale to co teraz? Bo komentarz spekulacyjny od supportu mi nic nie daje :) Ja potrzebuje rozwiązania.

**Comment by MartaNowaczyk** [comment]
Możesz spróbować dodać nowe konto na sandboxie, uzupełnij tylko wszystkie dane.

**Comment by blauweb** [comment]
Nie będę tworzył specjalnie nowego maila pod to. Usuń proszę w takim razie prosze moje obecne konto i wtedy założe nowe na ten sam adres.

**Comment by MartaNowaczyk** [comment]
Możesz już skorzystać z tego maila podczas tworzenia nowego konta.

**Comment by MartaNowaczyk** [comment]
Na tym koncie masz wybraną niepełną opcję sprzedażową. Wejdź proszę do [ustawień konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy), skorzystaj z linku, który masz na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)" i wybierz "Weryfikacja pełna". Uzupełnij dane i prześlij dowolne pliki, abym mogła aktywować to konto.

**Comment by blauweb** [comment]
Niestety nie mogłem wrócić do tego poziomu. Ale odnalazłem w innym miejscu "pełna aktywacja" i tam wysłałem potrzebne dokumenty.

**Comment by MartaNowaczyk** [comment]
Aktywowałam to konto, widzę, że województwo jest na koncie, więc teraz powinno być ok.

**Comment by blauweb** [comment]
Czy dane firmy muszą być potwierdzone? Bo widzę, że tam wciąż widnieje "czeka na weryfikację".

**Comment by MartaNowaczyk** [comment]
Na sandboxie, po ręcznej aktywacji tak to wygląda niestety.

**Comment by blauweb** [comment]
Wygląda na to, ze działa teraz. Jeszcze nie przeprowadziłem wszystkim testów, ale na ten moment zamknę wątek.
Moje obserwacje dla was:
Moje konto było na początku "prywatne", a następnie zostało przekonwertowane na "biznesowe".
Podczas konwersji, nie było pola do podawania województwa, ale podczas nowego konta "biznes", takie pole istnieje.
Wniosek z tego taki, że tutaj leżała przyczyna tego błędu.
