### ISSUE TITLE
Kod kreskowy Etykiety - Allegro Odbiór w Punkcie UPS

### ISSUE THREAD

**Issue by Oktawian12** [allegro/allegro-api#8356]
Dzien dobry,
Czy mozliwe jest/z ktorego miejsca moge pobrac kod kreskowy etykiety UPS? Problem występuje tylko w przypadku dostawy do punktu w polu waybill jest zwracana wartosc z reference na etykiecie.
Example:
{
  "parcelId": "fe934b32-853a-4b03-9003-133e3ac305ba",
  "serviceId": "0aafb43c-e66a-46ec-9cc4-29bb39ebb483",
  "label": {
    "sender": {
      "name": "*****",
      "company": "*****",
      "address": {
        "street": "*****",
        "postCode": "02-657",
        "city": "Warszawa",
        "county": null,
        "countryCode": "PL"
      },
      "email": "*****",
      "phone": "*****"
    },
    "fileFormat": "PDF",
    "referenceNumber": "ZK3814012024"
  },
  "receiver": {
    "name": "*****",
    "company": "",
    "address": {
      "street": "*****",
      "postCode": "93-460",
      "city": "\u0141\u00f3d\u017a",
      "county": "",
      "countryCode": "PL"
    },
    "pointId": "AL045EL1",
    "email": "wid0050zey+18b6522a2@allegromail.pl",
    "phone": "*****"
  },
  "pickup": {
    "name": "*****",
    "company": "*****",
    "address": {
      "street": "*****",
      "postCode": "02-657",
      "city": "Warszawa",
      "county": null,
      "countryCode": "PL"
    },
    "pointId": null,
    "email": "*****",
    "phone": "*****"
  },
  "items": [
    {
      "waybill": "A000D244G4",
      "dimensions": {
        "height": {
          "value": "35",
          "unit": "CENTIMETER"
        },
        "width": {
          "value": "25",
          "unit": "CENTIMETER"
        },
        "depth": {
          "value": "5",
          "unit": "CENTIMETER"
        }
      },
      "weight": {
        "value": "1",
        "unit": "KILOGRAM"
      },
      "description": "0000112427",
      "value": {
        "amount": "0.00",
        "currency": "PLN"
      },
      "type": "PACKAGE"
    }
  ],
  "type": "PACKAGE",
  "additionalServices": {
    "options": []
  },
  "state": "CREATED"
}

**Comment by MartaNowaczyk** [comment]
Jeśli dobrze Cię zrozumiałam, to taka informacja powinna być zwracana [w nowym WZA](https://developer.allegro.pl/documentation/#operation/getShipmentDetails), w obiekcie additionalProperties.
