### ISSUE TITLE
Zamówienia One Fulfillment by Allegro

### ISSUE THREAD

**Issue by jakub-marchewka** [allegro/allegro-api#8357]
Dzień dobry, czy istnieje możliwość rozpoznania zamówień przetwarzanych przez One Fulfillment by Allegro w 
https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET
lub
https://developer.allegro.pl/documentation#operation/getOrderEventsUsingGET
?

**Comment by Lukasz-Zurek** [comment]
Nie, nie ma takiej możliwości i jednocześnie - na ten moment - nie ma takiej potrzeby.

Co istotne - gdy skorzystasz z [GET /me](https://developer.allegro.pl/documentation/#operation/meGET), jeśli sprzedawca posiada status One Fulfillment - w polu **"features"** zwracamy wartość "ONE_FULFILLMENT". Jeśli sprzedawca korzysta z tej usługi, obsługą w pełni zajmuje się nasz magazyn. Więcej informacji na ten temat znajdziesz [tutaj](https://developer.allegro.pl/tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw#jak-obslugiwac-zamowienia).

**Comment by jakub-marchewka** [comment]
Dziękuję za odpowiedź. Zaistniała potrzeba pobrania nr przesyłek, ale widzę, że w tym celu trzeba stukać na inny endpoint. Nie chciałbym tego robić dla wszystkich zamówień. Myślę, że mogę to rozwiązać przez pole features.
