### ISSUE TITLE
Oferty podpięte do produktu w katalogu

### ISSUE THREAD

**Issue by tryllu** [allegro/allegro-api#8358]
Czy istnieje jakaś możliwość aby pobrać dane na temat numerów ofert przypiętych do produktu o danym productId?

Endpointem `https://api.{environment}/sale/products/{productId}` można pobrać dane produktu, ale nie ma tam informacji o ofertach.
Endpointem `https://api.{environment}/offers/listing` nie można z kolei wyszukiwać po konkretnym produkcie z produktyzacji.

**Comment by MartaNowaczyk** [comment]
Niestety, nie ma takiej możliwości.

**Comment by maniootek** [comment]
Mam produkt z własnym numerem EAN. Tworzę kartę produktu w katalogu Allegro, a następnie wystawiam do niej ofertę jako promowaną. Ktoś inny podłącza się do tego samego produktu z niższą ceną, ale jego oferta nie jest promowana.
Czy mogę wykryć taką sytuację przez API?

**Comment by MartaNowaczyk** [comment]
Nie ma takiej możliwości.

**Comment by maniootek** [comment]
Istnieje jakiś sposób aby uniemożliwić innym podpinanie się do mojego produktu?

**Comment by MartaNowaczyk** [comment]
@maniootek nie ma takiego sposobu.

**Comment by maniootek** [comment]
Jeśli produkt jest mojej marki to też nie?

**Comment by MartaNowaczyk** [comment]
To już nie kwestia API, więc skontaktuj się proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
