### ISSUE TITLE
Filtrowanie po parametrze typu TEXT w /offers/listing

### ISSUE THREAD

**Issue by javaguru-pl** [allegro/allegro-api#8359]
Mam pytanie do metody offers/listing, a konkretnie do filtrowania po parametrach aukcji typu TEXT:

W sekcji w dokumentacji są podane przykłady filtrowania po parametrach aukcji: 
https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk#jak-filtrowac-wyniki-wyszukiwania

Jak można filtrować wyniki po parametrze typu TEXT?
Dodanie poniższego ciągu do URL-a, **niestety NIE działa**:
**&parameter.23310=RP-HF100E-K**

Bardzo proszę o przykład prawidłowego URL-a z filtrem typu TEXT.
Z góry dziękuję.

**Comment by MartaNowaczyk** [comment]
Podaję przykład wyszukiwania po filtrze miejscowości  `/offers/listing?phrase=harry+potter&category.id=98697&location.city=Poznań` 
Możesz też podać cały swój request z wyszukiwaniem, wtedy sprawdzę na Twoim przykładzie.

**Comment by javaguru-pl** [comment]
Witam Pani Marto,
Nie chodzi mi o filtrowanie po filtrze miejscowości - gdyż taki przykład jest podany w dokumentacji - więc on jest jasny.
Natomiast ja mam na myśli filtrowanie po parametrze typu TEXT. Numer tego parametru to **23310**, a przykładowa wartość po której chce filtrować to **RP-HF100E-K**. W dokumentacji brakuje przykładu filtrowania po parametrze typu TEXT.

Poniżej podaję przykład całego URL-a:

https://api.allegro.pl/offers/listing?category.id=66887&fallback=false&offset=0&limit=60&sort=relevance&searchMode=REGULAR&sellingMode.format=BUY_NOW&parameter.23310=RP-HF100E-K

Niestety w/w URL nie działa prawidłowo (filtr jest całkowicie pomijany).

**Comment by MartaNowaczyk** [comment]
Witam, niestety taki parametr 23310 nie istnieje, także nie mamy jak go brać pod uwagę. W każdym razie musisz mieć też na uwadze, że możesz korzystać tylko z tych filtrów, które są dostępne na liście "filters". W tym układzie co podałeś z filtrów typu TEXT jest tylko "location.city".

**Comment by javaguru-pl** [comment]
Dziękuję za wyjaśnienie.
