### ISSUE TITLE
Identyfikator transakcji do Inpostu

### ISSUE THREAD

**Issue by coobitus** [allegro/allegro-api#836]
Tworząc paczkę w API Inpostu i chcąc tam skorzystać z opcji Allegro Paczkomaty, należy podać login konta sprzedawcy oraz "identyfikator transakcji" z Allegro. Jak sądzę na podstawie tych dwóch danych Inpost jest w stanie w Waszym systemie zweryfikować, czy faktycznie taka transakcja miała miejsce. W WebAPI w polu z id transakcji podawało się wartość z pola postBuyFormId. To była po prostu jakaś duża LICZBA. W REST API nie ma takiego pola, a jego odpowiednikiem jest (chyba?) pole "id" w zamówieniu (korzystam ze ściągania ZAMÓWIEŃ, nie zdarzeń). Ale to pole ma zupełnei inny format - to jest UUID. Czy w takim razie mam do Inpostu przekazywać tenże właśnie UUID? Czy może brać ten numer transakcji z jakiegoś innego miejsca?

**Comment by MartaNowaczyk** [comment]
@coobitus mając UUID możesz skorzystać z [zasobu](https://developer.allegro.pl/news/2018-10-09_Mapowanie_lineItemId_dealId/) i uzyskać int dla InPostu - niestety InPost na ten moment nie przyjmuje naszego formatu danych

**Comment by MartaNowaczyk** [comment]
@coobitus ani w jedną ani w drugą stronę nie dostajesz poprawnej odpowiedzi? Sprawdziłam przed chwilą i dostaję UUID na podsatwie dealId i odwrotnie.

**Comment by coobitus** [comment]
A ja nie dostaję :-) Mam UUID o sprawdzam dealId. Przykładowy zestaw : 

sprzedawca : kajasport

headers : 
[0] => Authorization: bearer eyJhbGciOiJSUzI....
[1] => Accept: application/vnd.allegro.beta.v1+json

url : https://api.allegro.pl/order/line-item-id-mappings?lineItemId=f7b24ce1-d879-11e8-a8fe-9b7425fa5c81

wynik : 
stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ERROR
                    [message] => An error has occurred
                    [details] => 
                    [path] => 
                    [userMessage] => 
                )

        )

)

**Comment by coobitus** [comment]
Heh, już wiem o co chodzi :-( Ja podaję w zapytaniu numer ZAMÓWIENIA, a Wy zrobiliście mapowanie na numer POZYCJI W ZAMÓWIENIU ... A przecież ta sama dostawa jest na całe zamówienie ... Masakra jakaś ... Mam nadzieję, że z Inpostem w nowej wersji dogadacie się tak, żeby przekazywać im numer zamówienia do weryfikacji, a nie numery każdej z pozycji zamówienia ...

**Comment by coobitus** [comment]
@MartaNowaczyk jednak coś mi się tu nie zgadza ... Piszesz, że można wyciągnąć dealId na podstawie lineItemId ... Ale do Inpostu potrzebujemy przekazać inne pole z WebAPI - postBuyFormId !!! dealId odpowiada logicznie lineItemId bo w jednej transakcji może być więcej niż jeden produkt. Ale postBuyFormId odpowiada logicznie NUMEROWI ZAMÓWIENIA! Bo do Inpostu przekazujemy ID CAŁEJ TRANSAKCJI a nie jakieś id dla każdego z produktów z osobna (dealId). I to jest logiczne, bo ja mogę w jednej paczce wysłać więcej niż jeden produkt! I jak z tego wybrnąć? BARDZO PILNE!

**Comment by MartaNowaczyk** [comment]
@coobitus przepraszam jeśli wprowadziłam cię w błąd. Miałam na myśli, że możesz na tej podstawie połączyć dwa "światy" i wyciągnąć odpowiednie dane dla InPostu. Samo mapowanie nie zwraca wartości, które możesz użyć bezpośrednio w InPost.

https://github.com/allegro/allegro-api/issues/768

**Comment by coobitus** [comment]
@MartaNowaczyk wybacz moje zdenerwowanie, ale to co mi podpowiedziałaś jest o kant dupy potłuc ... I kompletnie nie na temat :-P Z tego co widzę po innych postach to wiecie o tym od dawna i palcem nie ruszyliście do tej pory. Sami ze swojego systemu jesteście w stanie te dane przekazać bezpośrednio do Inpostu a tych, którzy korzystają z Waszego nowego API macie w dupie - przez tyle czasu nie byliście w stanie przygotować prostego rozwiązania podającego w zamówieniu z REST API również STARY numer transakcji ... Śmieszne i tragiczne zarazem. 

To co piszesz o "wyciąganiu odpowiednich danych dla Inpostu" też jest o kant dupy potłuc, bo efektywnie sprowadza się do tego, że i tak trzeba ściągnąć to zamówienie przez WebAPI !!!! KWADRATURA KOŁA !!!!

Zamiast pisać że "stale rozwijacie nowe API" weźcie się po prostu do roboty i udostępnijcie przynajmniej ten stary numer transakcji w zamówieniach z REST API - dopóki nie dogadacie się z Inpostem co do obsługi Waszych UUID ...

**Comment by coobitus** [comment]
Minął kolejny miesiąc i nadal temat nie jest rozwiązany ...

**Comment by MartaNowaczyk** [comment]
@coobitus Pytasz o to samo w kilku wątach. Tak jak napisał Ci Paweł:

> Trwają rozmowy z Inpostem w sprawie rozwiązania tej sytuacji, jak już wielokrotnie informowaliśmy, jak tylko otrzymamy jakieś konkretne informacje, poinformujemy o tym w dedykowanym komunikacie.

**Comment by coobitus** [comment]
@MartaNowaczyk dlaczego zamykasz ten temat? Nie rozwiązaliście problemu więc nie widzę powodu, dla którego można by ten temat zamknąć ...

**Comment by MartaNowaczyk** [comment]
@coobitus zamknęłam, ponieważ prowadzisz ten sam temat w kilku wątkach. Rozbicie jednego tematu na kilka wątków nie jest czytelne dla nikogo i trudno znaleźć odpowiednie informacje. Proponuję byś zdecydował się na jeden.
