### ISSUE TITLE
Aplikacja do przetwarzania danych.

### ISSUE THREAD

**Issue by ralph9001** [allegro/allegro-api#8360]
Czy aplikacja typu Saas, w której sprzedawcy będą autoryzowali swoje konta, a która będzie pobierała duże ilości danych z api Allegro powinna być w jakiś sposób wpisana na whiteliste przez Allegro? Mam na myśli, czy przy takim schemacie adres IP serwera Saas nie zostanie zablokowany?

**Comment by MartaNowaczyk** [comment]
Wiele aplikacji pobiera duże ilości danych i nie mają takich problemów. Jeśli jednak zdarzy się blokada IP możesz zgłosić to do nas, a my sprawdzimy jej przyczynę i podpowiemy jak jej uniknąć.
