### ISSUE TITLE
Etykiet zamówień

### ISSUE THREAD

**Issue by Eryk1997** [allegro/allegro-api#8361]
Dzień dobry, chciałbym się dowiedzieć jak mogę pobrać ile etykiet przewidują dla zamówienia. W jaki sposób mogę pobrać to z api?

**Comment by MartaNowaczyk** [comment]
Nie wiem czy o to Ci chodzi, ale w [zamówieniach](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET) mamy pole "calculatedNumberOfPackages", które określa łączną liczbę przesyłek w zamówieniu.
