### ISSUE TITLE
Dopłaca do danego produktu

### ISSUE THREAD

**Issue by Eryk1997** [allegro/allegro-api#8362]
Dzień dobry, 
chciałbym się dowiedzieć jak pobrać kwotę dopłacana przez allegro do danego produktu. W jaki sposób mogę uzyskać takie wartości z API?

**Comment by MaciejFrackowiak** [comment]
Informacje o płatności, którą pokrywa Allegro w ramach programu Allegro Ceny znajdziesz w szczegółach zamówienia - w [poradniku](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#jak-rozpoznac-zamowienie-zlozone-w-ramach-programu-allegro-ceny) opisaliśmy ten proces. Oczywiście stosowne kwoty znajdziesz również w [billingu](https://developer.allegro.pl/documentation/#operation/getBillingEntries).
