### ISSUE TITLE
Czas przechowywania danych,

### ISSUE THREAD

**Issue by ralph9001** [allegro/allegro-api#8363]
Gdzie znajdę informacje z jakiego okresu można pobrać dane po API dla poszczególnych metod?

**Comment by MaciejFrackowiak** [comment]
Jakie endpointy masz na myśli? Proszę doprecyzuj, wówczas postaram się pomóc.

**Comment by MaciejFrackowiak** [comment]
Odpowiadając:
- /billing/billing-entries - okres 6 lat, niezbędne jest użycie filtrów "occurredAt.gte" i "occurredAt.lte", aby zawęzić wyniki do wybranego okresu;
- /order/checkout-forms/{id} - gwarantujemy dostęp do zamówień przez okres 180 dni;
- /order/customer-returns - zwracamy dane z okresu ostatnich 2,5 lat.
