### ISSUE TITLE
ConstraintViolationException.InvalidParameterIdsInCategory - dla parametrów które nie zostały przekazane

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#8368]
Próbuję poprawić kategorię oferty. W zapytaniu przesyłam id nowej kategorii oraz nowy parametr, który jest w tej kategorii wymagany. W odpowiedzi otrzymuję "Nieprawidłowe parametry (245105, 10926, 216045, 246849) dla wybranej kategorii.". Zgaduję, że chodzi o parametry, które w tej chwili są zdefiniowane w dla oferty, w jej bieżącej kategorii. 
W dokumentacji nie znalazłem informacji w jaki sposób można usunąć parametr, jeśli nie znika ona samoistnie.

url: PATCH https://api.allegro.pl/sale/product-offers/13449402575
trace-id: a61c7855941328fc 

`Array ( [category] => Array ( [id] => 111696 ) [parameters] => Array ( [0] => stdClass Object ( [id] => 11323 [valuesIds] => Array ( [0] => 11323_1 ) ) ) )`

**Comment by Lukasz-Zurek** [comment]
Tego typu żądanie nie przejdzie. Próbujesz zmienić kategorię na inną niż 100136, którą posiada przypisany do oferty produkt (a ten nie posiada kategorii podobnych). Najlepiej będzie jak wyszukasz produkt dla preferowanej kategorii, o określonych parametrach i zmienisz produkt w ofercie.
