### ISSUE TITLE
DownloadError.NotFound 

### ISSUE THREAD

**Issue by yu-www** [allegro/allegro-api#8369]
Hi,
 Please help me take a look at the following question。I can find and open this image "https://img2.mangoerp.com/temp/2024/01/23/10/10_67332114-97bc-4111-b0e1-ed337a5f7fda.png",but the response return NotFound

the environment is in sandbox. 

thank you for help.

https://api.allegro.pl.allegrosandbox.pl/sale/images

request: {"url":"https://img2.mangoerp.com/temp/2024/01/23/10/10_67332114-97bc-4111-b0e1-ed337a5f7fda.png"}

response: {"errors":[{"code":"DownloadError.NotFound","message":"Downloading image from URL 'https://img2.mangoerp.com/temp/2024/01/23/10/10_67332114-97bc-4111-b0e1-ed337a5f7fda.png' failed. Server returned the following HTTP status code: 404 NOT_FOUND and response body: ''.","details":null,"path":null,"userMessage":"Downloading image from URL 'https://img2.mangoerp.com/temp/2024/01/23/10/10_67332114-97bc-4111-b0e1-ed337a5f7fda.png' failed. Server returned the following HTTP status code: 404 NOT_FOUND and response body: ''."}]}

**Comment by AureliuszBrussy** [comment]
I checked it - when I open the url "https://img2.mangoerp.com/temp/2024/01/23/10/10_67332114-97bc-4111-b0e1-ed337a5f7fda.png" I also get a 404 error. It looks like it is not available on the server.

**Comment by yu-www** [comment]
> I checked it - when I open the url "https://img2.mangoerp.com/temp/2024/01/23/10/10_67332114-97bc-4111-b0e1-ed337a5f7fda.png" I also get a 404 error. It looks like it is not available on the server.

This looks a bit strange. I should be able to open this image normally and directly access this URL in a browser.

<img width="1216" alt="image" src="https://github.com/allegro/allegro-api/assets/5554249/b7e083d4-5a8e-4016-ae09-9c4ee3a060a0">

**Comment by AureliuszBrussy** [comment]
![image](https://github.com/allegro/allegro-api/assets/68948612/ebac9e86-b58b-4f4d-bf3a-5afebb844718)


Request:
```
Request URL:
https://img2.mangoerp.com/temp/2024/01/23/10/10_67332114-97bc-4111-b0e1-ed337a5f7fda.png
Request Method:
GET
Status Code:
404 Not Found
Remote Address:
172.22.9.148:3128
Referrer Policy:
strict-origin-when-cross-origin
```

Response header:
```
Accept-Ranges:
bytes
Access-Control-Allow-Methods:
GET,POST,PUT
Access-Control-Allow-Origin:
*
Ali-Swift-Global-Savetime:
1706517237
Cache-Control:
max-age=18076225
Content-Length:
221
Content-Md5:
9LFpWRl0VtnNQPaMOqNSGA==
Content-Type:
text/html
Date:
Mon, 29 Jan 2024 08:33:57 GMT
Eagleid:
2ff62d9b17065172375752730e
Etag:
"F4B16959197456D9CD40F68C3AA35218"
Expires:
Thu, 20 Apr 2018 04:16:44 GMT
Last-Modified:
Thu, 12 Nov 2015 09:09:36 GMT
Server:
Tengine
Timing-Allow-Origin:
*
Via:
cache5.l2fr1[274,274,404-1280,M], cache39.l2fr1[275,0], cache6.es2[318,318,404-1280,M], cache7.es2[322,0]
X-Cache:
MISS TCP_MISS dirn:-2:-2
X-Oss-Cdn-Auth:
success
X-Oss-Hash-Crc64ecma:
3205434100428798722
X-Oss-Object-Type:
Normal
X-Oss-Request-Id:
65B762F54D75C8343474A629
X-Oss-Server-Time:
3
X-Oss-Storage-Class:
Standard
X-Swift-Cachetime:
1
X-Swift-Error:
orig response 4XX error

X-Swift-Savetime:
Mon, 29 Jan 2024 08:33:57 GMT
```
