### ISSUE TITLE
about update price

### ISSUE THREAD

**Issue by skutop001** [allegro/allegro-api#8370]
Regarding the issue of modifying prices

I use API(PUT /offers/{offerId}/change-price-commands/{commandId}) to request modification of the quoted price

If the value of currency is PLA, is it possible to modify the offer price in the Polish market

If the value of currency is CZK, is it possible to modify the offer price in the Czech market
so this is ture?

json is 

{
"id": "6365996a-6cae-11e9-a923-1681be663d3e",
   "input": {
        "buyNowPrice": {
             "amount": "123.45",
            "currency": "PLN"
          }
     }
}

**Comment by AureliuszBrussy** [comment]
Please use the [batch offer price modification resource](https://developer.allegro.pl/documentation#operation/priceModificationCommandUsingPUT) to change the offer price - this resource is adapted to price changes in different marketplaces. You can [read more in our tutorial](https://developer.allegro.pl/tutorials/listing-and-managing-offers-on-foreign-marketplaces-7GndGjeAATn#managing-offers-in-bulk).

**Comment by skutop001** [comment]
I want update change PL and CZ  price .
and use  API (PUT /sale/offer-price-change-commands/{commandId})
So I need to send it twice, right?
First time "marketplaceId": "allegro-pl" 
Second time "marketplaceId": "allegro-cz" 
Is this right to do

**Comment by AureliuszBrussy** [comment]
@skutop001 yes, exactly, this is the right way.

**Comment by skutop001** [comment]
I want Query offers for price<100 ,
So what API do I use to query

**Comment by AureliuszBrussy** [comment]
You want to check offers with price lower or greater than 100? You can use [GET /sale/offers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET) and `sellingMode.price.amount.lte` and/or `sellingMode.price.amount.gte` query parameter.

**Comment by skutop001** [comment]
query parameter  how to write

**Comment by skutop001** [comment]
https://api.allegro.pl/sale/offer-price-change-commands/7cc392ad-62c7-4f8d-9d80-fb8048c298e2?shopId=16
I use this api . result is :
{"id":"7cc392ad-62c7-4f8d-9d80-fb8048c298e2","createdAt":"2024-01-29T10:52:31.041Z","taskCount":{"total":0,"success":0,"failed":0}} 
I see in the picture that the price in the Czech market has not changed, it is still 73 CZK

**Comment by AureliuszBrussy** [comment]
You can check command status by [using price automation command summary](https://developer.allegro.pl/documentation#operation/getofferPriceAutomationModificationCommandStatusUsingGET) and/or [price automation command detailed report](https://developer.allegro.pl/documentation#operation/getofferPriceAutomationModificationCommandTasksStatusesUsingGET).

Automatic price conversion via API is possible. You can read more about managing price automation [in our tutorial](https://developer.allegro.pl/tutorials/listing-and-managing-offers-on-foreign-marketplaces-7GndGjeAATn#managing-price-automation-in-offers).

**Comment by skutop001** [comment]
Informacja - Od momentu wystawienia oferty minęło ponad 12 godzin, dlatego nie możesz zmienić niektórych danych.

**Comment by skutop001** [comment]
why can not change price?

**Comment by AureliuszBrussy** [comment]
Looks like you're sending other changes besides the price change. Please send a trace-id of the request where you encountered this error message. The trace-id can be found in the response header. I will be able to check it then.

**Comment by skutop001** [comment]
data is lose  
I would like to inquire, is there a price limit for API(PUT /sale/offer-price-change-commands/{commandId}) modifications that cannot be modified within 12 hours?

Or can an offer only be modified once within 12 hours?

**Comment by MaciejFrackowiak** [comment]
For [PUT /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT) there is only one limit -  250 000 offer changes per hour or 9000 offer changes per minute. There should be something different than a price change to receive such an error as you received, but without trace-id I am unable to check it.
