### ISSUE TITLE
Is it possible to adjust inventory in batches?

### ISSUE THREAD

**Issue by api-test-yexiu** [allegro/allegro-api#8371]
curl -X PATCH ‘https://api.allegro.pl/sale/product-offers/9531382307’ \
-H 'Authorization: Bearer {token}' \
-H 'Accept: application/vnd.allegro.public.v1+json' \
-H 'Content-Type: application/vnd.allegro.public.v1+json' \
-d ‘{"stock": { "available": 2, "unit": "UNIT"}}’

Is it possible to adjust inventory in batches?

**Comment by AureliuszBrussy** [comment]
Yes, we do have an endpoint intended for batch offer quantity modification: [PUT /sale/offer-quantity-change-commands/{commandId}](https://developer.allegro.pl/documentation#operation/quantityModificationCommandUsingPUT). You can read more about it [in our tutorial](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#quantity).

**Comment by api-test-yexiu** [comment]
![image](https://github.com/allegro/allegro-api/assets/155221200/3a6f81f4-a228-4f6b-917d-b4e1629a66fd)
I saw a way to adjust inventory in batches, but this seems to adjust all offer IDs to a single value, which is not what I want.

I want offer id A = 30 id B =50 to submit this inventory/price request together in batches

**Comment by AureliuszBrussy** [comment]
I understand, such a way of batch modification is not supported by us.

**Comment by api-test-yexiu** [comment]
sale/product-offers
product-offers/15102316375
What is the API request speed limit? Can you send me a complete speed limit form?

**Comment by AureliuszBrussy** [comment]
The overall limit on the API key is 9000 requests per minute. There may be an additional rate limit on this resource, but in this case we do not share this information openly.

**Comment by api-test-yexiu** [comment]
https://api.allegro.pl/sale/offers?publication.status=ACTIVE
![image](https://github.com/allegro/allegro-api/assets/155221200/b21ef90a-8465-4f1b-8f1d-897796d4e284)
How can I get all link information?

**Comment by AureliuszBrussy** [comment]
Are you referring to checking the next page of results? Use the offset and limit parameters for this purpose. You can read more about this in [our tutorial](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#list-of-offers).

**Comment by api-test-yexiu** [comment]
![image](https://github.com/allegro/allegro-api/assets/155221200/959d820d-ffa5-4da9-9fe2-254a02469f0b)
Is it possible to query based on the shelf time?

**Comment by AureliuszBrussy** [comment]
No, there is no such query parameter.

**Comment by api-test-yexiu** [comment]
Is there a way to modify GTIN codes in batches?

**Comment by api-test-yexiu** [comment]
![image](https://github.com/allegro/allegro-api/assets/155221200/d66d2f5f-c2ba-44b2-a9ef-7e634f0dae36)
This was applied, but not amended

**Comment by api-test-yexiu** [comment]
I need to replace GTIN in bulk,because 
![image](https://github.com/allegro/allegro-api/assets/155221200/dad7d4ec-3382-4526-8fba-b2ab70c49dac)

**Comment by AureliuszBrussy** [comment]
We do not provide resources for editing parameters in bulk. You have to edit it in each offer separately.

**Comment by api-test-yexiu** [comment]
How should I edit replace with API

**Comment by api-test-yexiu** [comment]
How should I edit replace with API
 can you help me QAQ

**Comment by api-test-yexiu** [comment]
![image](https://github.com/allegro/allegro-api/assets/155221200/6a1b35d9-a893-4511-b91b-2a85d87f84c6)
I want to replace GTIN in batches but it doesn’t work

**Comment by AureliuszBrussy** [comment]
We do not have a resource to change GTINs in batch.

**Comment by api-test-yexiu** [comment]
So how do I modify GTIN using API?

**Comment by api-test-yexiu** [comment]
![image](https://github.com/allegro/allegro-api/assets/155221200/3d661df9-f547-43c0-bd6f-b7b094bc83e2)
{
    "errors": [
        {
            "code": "JsonMappingException",
            "message": "Message is not readable.",
            "details": null,
            "path": "productSet[0]",
            "userMessage": "Request contains invalid data. Contact the application author."
        }
    ]
}

**Comment by api-test-yexiu** [comment]
![image](https://github.com/allegro/allegro-api/assets/155221200/3bc209d5-8cab-4098-9afb-1cb2eb016378)

**Comment by api-test-yexiu** [comment]
![image](https://github.com/allegro/allegro-api/assets/155221200/c5c542b6-8de2-4393-83b4-d80ad2e20390)

**Comment by api-test-yexiu** [comment]
I don't know how to modify EAN

**Comment by AureliuszBrussy** [comment]
The last attempt was correct, but, as I wrote before: for arrays (e.g. productSet, images, description, parameters) we are on an all-or-nothing basis (in compliance with the guidelines in [RFC7396](https://tools.ietf.org/html/rfc7396)), so you should send **all** required parameters.

**Comment by api-test-yexiu** [comment]
ok

**Comment by api-test-yexiu** [comment]
![image](https://github.com/allegro/allegro-api/assets/155221200/fd99b19f-e216-4c7a-a371-a039477163f4)
I have another question. If EAN is optional, will it affect sales if I don't fill in the content? Or will it affect my other API applications?

**Comment by AureliuszBrussy** [comment]
If the EAN is optional, you do not need to fill it in. On the other hand, it is worthwhile to fill in the parameter correctly. This makes it easier, for example, for buyers to search for offers.

**Comment by api-test-yexiu** [comment]
How can I query EAN in batches

**Comment by AureliuszBrussy** [comment]
What specifically do you have in mind? Are you talking about searching products in batch for multiple EANs at once? If you mean that, then no, there is no such possibility - you can only search products for one EAN at a time ([GET /sale/products](https://developer.allegro.pl/documentation#operation/getSaleProducts)).

**Comment by AureliuszBrussy** [comment]
The EAN is stored in the product parameters, and we return the parameters only after querying an offer's details. We do not return the parameters in the offer list.
