### ISSUE TITLE
Wgrywanie bazy produktów

### ISSUE THREAD

**Issue by BartlomiejCalus** [allegro/allegro-api#8373]
Dzień dobry,
Nasz klient chciałby wprowadzić swoją bazę produktów na podstawie których będziemy tworzyli oferty. Zależy nam na możliwości jednorazowego wgrania całej bazy produktów (lub chociaż jej większej części) oraz potem możliwej aktualizacji atrybutów.
Czy istnieje możliwość wykonania takich operacji przez Wasze API? A jeśli nie to czy istnieje jakiś inny sposób na przesyłanie takich danych?

**Comment by AureliuszBrussy** [comment]
Możliwe, że najbardziej dogodną opcją dla sprzedającego będzie [opcja opisana w artykule pomocy](https://allegro.pl/dla-sprzedajacych/jak-mozesz-przekazac-nam-swoja-baze-danych-produktow-YWqLnDRxPu8).

Dodam natomiast, że w ramach publicznego API udostępniamy endpoint do proponowania nowych produktów: [POST /sale/product-proposals](https://developer.allegro.pl/documentation#operation/getSaleProduct). W jednym requeście możesz utworzyć jeden produkt. Więcej przeczytasz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-utworzyc-nowy-produkt).

**Comment by BartlomiejCalus** [comment]
Dziękuję za informację
