### ISSUE TITLE
Aktywacja konta sandbox + Pytanie dot. wystawiania ofert sandbox

### ISSUE THREAD

**Issue by Smerf90** [allegro/allegro-api#8374]
Dzień Dobry, 
Bardzo proszę o aktywację sprzedaży konta Sandbox dla loginu nr.: 106870666

Czy jest możliwe utworzyć firmowe konto na Sandboxie bez posiadania działalności?

- Jeśli tak, to jak powinny wyglądać dokumenty do weryfikacji konta, czy dane mogą zostać zmyślone?

Chciałbym przetestować aplikację jednak wystawianie i obsługa zamówień przez API dostępna jest wyłącznie dla kont firmowych. 

Z góry bardzo dziękuję za odpowiedź, 
Pozdrawiam, 
Maciej

**Comment by MartaNowaczyk** [comment]
Dzień dobry, na sandboxie dodasz konto firmowe bez prawdziwych dokumentów, wystarczą dwa dowolne pliki w odpowiednim formacie. Wszelkie dane mogą być fikcyjne, a przelewy są symulowane, także tutaj nie musisz się niczym martwić.
Konto, które podałeś do aktywacji, to konto zwykłe. Czy chcesz je tak aktywować, czy przekształcić na firmowe? Jeśli chcesz zmienić na firmowe, to zrobisz to w [tej zakładce](https://allegro.pl/moje-allegro/moje-konto/dane-konta).

**Comment by Smerf90** [comment]
Super, Założyłem nowe konto firmowe. 
Jeśli jest taka możliwość proszę o aktywację obydwu kont tj. login: **106870666** oraz **Smerf16**
Konto zwykłe posłuży do symulacji sprzedaży więc byłoby bardzo pomocne w procesie testów. 
Dziękuję

**Comment by filip-programist** [comment]
Dzień dobry, ja bym również poprosił o pomoc. Login: Filto 
Zrobiłem wszystko i dalej mi wyskakuje komunikat że aby w sandboxie utworzyć aplikację muszę mieć zweryfikowane konto a zależy mi na czasie

**Comment by MartaNowaczyk** [comment]
@smerf oba konta są już aktywne.

**Comment by MartaNowaczyk** [comment]
@filip-programist Na koncie "Filto" masz wybraną niepełną opcję sprzedażową. Wejdź proszę do [ustawień konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy), skorzystaj z linku, który masz na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)" i wybierz "Weryfikacja pełna". Uzupełnij dane i prześlij dowolne pliki, abym mogła aktywować to konto.

**Comment by MartaNowaczyk** [comment]
@filip-programist aktywowałam twoje konto.
