### ISSUE TITLE
Problem z dodawaniem propozycji produktów POST sale/product-proposals

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#8375]
Występuje problem:
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

Mam problem z dodawaniem propozycji produktów POST sale/product-proposals
Wysyłam dane produktu a w odpowiedzi dostaję całkiem inny produkt przykład poniżej:

Trace ID: 420614884a50d5cc

Request:

{
	"name": "Kabina prysznicowa szklana czarna 110x70 P satyna + pianka czyszcz\u0105ca PinUp",
	"category":
	{
		"id": "253705"
	},
	"images": [
	{
		"url": "https://a.allegroimg.com/original/11b010/6d54a6a4455b83e965075afe71e4"
	}],
	"parameters": [
	{
		"id": "129056",
		"values": [110]
	},
	{
		"id": "129057",
		"values": [70]
	},
	{
		"id": "223745",
		"valuesIds": ["223745_306165"]
	},
	{
		"id": "223749",
		"valuesIds": ["223749_1"]
	},
	{
		"id": "223753",
		"values": [6]
	},
	{
		"id": "223757",
		"valuesIds": ["223757_306177"]
	},
	{
		"id": "223765",
		"values": [200.5]
	},
	{
		"id": "225693",
		"values": ["5904530728371"]
	},
	{
		"id": "237214",
		"values": ["Idea Black KDJ+S + PinUp Clean"]
	},
	{
		"id": "223761",
		"valuesIds": ["223761_306189"]
	},
	{
		"id": "224017",
		"values": ["27721-59144-PC"]
	},
	{
		"id": "129033",
		"valuesIds": ["129033_1770965"]
	}],
	"language": "pl-PL"
}

Response:

{
	"id": "14e2c47c-58ef-46e7-8753-53d9eb45a9e6",
	"location": "https://api.allegro.pl/sale/products/14e2c47c-58ef-46e7-8753-53d9eb45a9e6"
}

**Comment by MartaNowaczyk** [comment]
Trace-id, który podajesz dotyczy wyszukiwania produktów GET /sale/products, a nie dodawania propozycji produktu. Czy to na pewno ten ID?

**Comment by avello** [comment]
Faktycznie mogłem nie to podać.
Przed chwilą wygenerowałem nowe zapytanie, te same dane i ta sama błędna odpowiedź
trace-id: 8e6287534fa55b7a

**Comment by MartaNowaczyk** [comment]
Problemem tutaj są błędy w produkcie, bo produkt dotyczy według tytułu i danych pojemnika na cebulę, a ma też w sobie np. EAN, opis i zdjęcia kabiny, stąd pojawił się jako duplikat. W takim wypadku najlepiej zgłosić błąd w produkcie. Z mojej strony zgłosiłam już to do poprawki.

**Comment by avello** [comment]
Nadal jest ten sam problem z tym samym produktem, mieliście to poprawić.
Żadne z parametrów które wysyłam nie pasują do zwracanego produktu

**Comment by MartaNowaczyk** [comment]
Rozumiem, w takim wypadku zgłoś proszę to jeszcze raz przez [stronę sugestii dla produktów](https://allegro.pl/moje-allegro/sprzedaz/produkt/zglos-blad/14e2c47c-58ef-46e7-8753-53d9eb45a9e6). Podaj proszę poprawny EAN.
