### ISSUE TITLE
Where I can get my seller id and access token (support didn't answer)

### ISSUE THREAD

**Issue by A-AWESOME** [allegro/allegro-api#8376]

**Comment by AureliuszBrussy** [comment]
You can get seller id through the AP by using [GET /me](https://developer.allegro.pl/documentation#operation/meGET). You can generate an access token through the authorization and authentication process, which we describe in [our tutorial](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY).
