### ISSUE TITLE
powiązanie kont 

### ISSUE THREAD

**Issue by Tanioagd** [allegro/allegro-api#8377]
Stworzyłam dwa konta testowe: tanioagd i SklepTragar. Chciałabym powiązać to drugie konto z pierwszym. Jednak nie przychodzi sms weryfikacyjny
![powiąż konta](https://github.com/allegro/allegro-api/assets/155977034/7de2e014-d5ee-4be8-8650-390b04639731)

**Comment by MaciejFrackowiak** [comment]
Proszę skorzystaj z domyślnego hasła: TestToken1234

**Comment by Tanioagd** [comment]
Dziękuję. Konta powiązane
