### ISSUE TITLE
Edycja oferty

### ISSUE THREAD

**Issue by PiotrPiotrP** [allegro/allegro-api#8378]
Co oznacza komunikat, który dostałem w odpowiedzi na próbę edycji oferty?
PATCH  https://api.allegro.pl/sale/product-offers/15082637603 requestBody={"id":"15082637603","productSet":[{"quantity":{"value":1},"product":{"name":"PLUS SIZE SUKIENKA KOKTAJLOWA ZDOBIONA 48 V9A","idType":"GTIN","parameters":[{"id":"54","valuesIds":["3806_9"]},{"id":"4126","valuesIds":["4126_4"]},{"id":"18160","valuesIds":["18160_3"]},{"id":"201017","valuesIds":["201017_2377"]},{"id":"216925","valuesIds":["216925_275825"]},{"id":"201025","valuesIds":["201025_2509"]},{"id":"15851","valuesIds":["15851_1"]},{"id":"59","valuesIds":["59_2429"]},{"id":"3786","values":["estila"],"valuesIds":["3786_85"]},{"id":"127468","valuesIds":["127468_8"]},{"id":"127662","valuesIds":["127662_3"]},{"id":"127488","valuesIds":["127488_225850"]},{"id":"202477","valuesIds":["202477_4","202477_1048576"]},{"id":"3766","valuesIds":["3766_1"]},{"id":"249512","valuesIds":["249512_1647413"]},{"id":"201089","values":["1"]}],"category":{"id":"124264"},"images":["https://images.stocksell.io/images/3d/3d9bbb7e-f716-4ddd-bbc1-0e74e22c3e3a","https://images.stocksell.io/images/ad/ad74fb1b-dcbb-4afe-9dfa-c585fd6b1d67","https://images.stocksell.io/images/f8/f850d172-3018-4186-b8e6-b42b8186d61d"]}}],"category":{"id":"124264"},"delivery":{"shippingRates":{"id":"92cb3f82-ae74-4d10-8804-2d9a444c4d55"},"handlingTime":"PT24H"},"publication":{"marketplaces":{"base":{"id":"allegro-pl"},"additional":[{"id":"allegro-cz"}]},"startingAt":"2024-01-24T18:41:00.000Z","status":"ACTIVE","republish":false},"language":"pl-PL","afterSalesServices":{"impliedWarranty":{"id":"3de10450-def9-43dd-8c04-408fa5115f8a"},"returnPolicy":{"id":"10bbd9d6-a61a-421b-aafd-e2289c330400"},"warranty":{"id":"aced38bb-6db9-4e8e-b2a9-ebc1d31b5ac5"}},"stock":{"available":1,"unit":"UNIT"},"parameters":[{"id":"11323","valuesIds":["11323_1"]}],"name":"PLUS SIZE SUKIENKA KOKTAJLOWA ZDOBIONA 48 V9A","payments":{"invoice":"VAT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":166.99,"currency":"PLN"}},"location":{"city":"Skawina","countryCode":"PL","postCode":"32-050","province":"MALOPOLSKIE"},"images":["https://images.stocksell.io/images/3d/3d9bbb7e-f716-4ddd-bbc1-0e74e22c3e3a","https://images.stocksell.io/images/ad/ad74fb1b-dcbb-4afe-9dfa-c585fd6b1d67","https://images.stocksell.io/images/f8/f850d172-3018-4186-b8e6-b42b8186d61d"],"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003ch2\u003ePLUS SIZE SUKIENKA KOKTAJLOWA ZDOBIONA\u003c/h2\u003e"}]},{"items":[{"type":"IMAGE","url":"https://images.stocksell.io/images/3d/3d9bbb7e-f716-4ddd-bbc1-0e74e22c3e3a"},{"type":"TEXT","content":"\u003ch2\u003eOpis Produktu\u003c/h2\u003e\u003cul\u003e\u003cli\u003e\u003cb\u003eMarka\u003c/b\u003e estila\u003c/li\u003e\u003cli\u003e\u003cb\u003eKolor\u003c/b\u003e Czarny\u003c/li\u003e\u003cli\u003e\u003cb\u003eSkład\u003c/b\u003e 95% poliester 5% elastan\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka papierowa\u003c/b\u003e Brak\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka wewnętrzna\u003c/b\u003e \tTak\u003c/li\u003e\u003cli\u003e\u003cb\u003eRozmiar\u003c/b\u003e 48\u003c/li\u003e\u003cli\u003e\u003cb\u003eCena katalogowa\u003c/b\u003e 221,99 zł\u003c/li\u003e\u003cli\u003e\u003cb\u003eUwaga\u003c/b\u003e możliwe punktowe braki w zdobieniach\u003c/li\u003e\u003c/ul\u003e"}]},{"items":[{"type":"IMAGE","url":"https://images.stocksell.io/images/ad/ad74fb1b-dcbb-4afe-9dfa-c585fd6b1d67"},{"type":"IMAGE","url":"https://images.stocksell.io/images/f8/f850d172-3018-4186-b8e6-b42b8186d61d"}]}]},"external":{"id":"stocksell_346316796"},"taxSettings":{"rates":[{"countryCode":"PL"}]}} exception=Niepoprawna odpowiedź z Allegro. Kod: 422. Błąd: ConstraintViolationException.ValidTemporaryProduct Oferta po zmianie nie kwalifikuje się już na produkt tymczasowy. Usuń go lub przypisz inny produkt. After modification, the offer is no longer eligible as a temporary product. Remove it or link a different product. ConstraintViolationException.ValidTemporaryProduct . Trace-id=[b59f424c3679470a].
O co chodzi z produktem tymczasowym?

**Comment by MartaNowaczyk** [comment]
Do oferty, którą edytujesz miałeś przypisany [produkt tymczasowy](https://allegro.pl/dla-sprzedajacych/produkty-tymczasowe-na-czym-to-polega-Xxx6YKyG0Te). Request, który podałeś zawiera już inne dane, przez co oferta nie kwalifikuje się na produkt tymczasowy. Podstawowym parametrem, który ma na to wpływ jest parametr "Stan", tutaj podajesz dla niego wartość "Nowy", a to wyklucza skorzystanie z dotychczasowego produktu tymczasowego. W takim wypadku musisz podpiąć już pełnoprawny produkt.

**Comment by PiotrPiotrP** [comment]
Kiedy oferta jest łączona z tymczosowym produktem, tylko gdy Stan ma wartość inną niż nowy? 
W zapytaniu podaje wszystkie dane produktu a nie id, to nie powinno przełączyć na produkt pasujący lub stowrzyć nowy?
A jeżeli nie działa podanie wszystkich danych to w jaki sposób się odpina produkt od oferty i łączy ją z innym bądz tworzy nowy gdy tego innego nie ma w katalogu?

**Comment by MartaNowaczyk** [comment]
Zasady produktów tymczasowych znajdziesz w tym [artykule](https://allegro.pl/dla-sprzedajacych/produkty-tymczasowe-na-czym-to-polega-Xxx6YKyG0Te).  Oferta ma produkt tymczasowy nie tylko ze względu na parametr Stan, ale jeszcze wtedy, gdy nie ma uzupełnionych innych parametrów. 
Request dotyczy edycji (PATCH) - tu nie stworzymy nowego produktu - możesz jednak podpiąć [istniejący w naszym katalogu produkt ](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-znalezc-produkt) do oferty (podaj jego ID) lub [wystawić nową ofertę z produktem](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-nowym-produktem).
