### ISSUE TITLE
Jak przez API masowo zmienić czas dostawy z PT24H na PT72H dla np. 5000 ofert 

### ISSUE THREAD

**Issue by lukiopmoto** [allegro/allegro-api#8379]
Dzień dobry,

Przez realizuję wysyłki 3 razy w tygodniu (poniedziałek, wtorek i środę). W tych dniach chciałbym aby czas wysyłki podany w ofertach na allegro był ustawiony na PT24H. Od środy po 12:00 chciałbym jednak masowo i szybko zmieniać czas dostawy dla wszystkich ofert na PT72H. Czy jest obecnie w API taka możliwość **by nie robić tego pojedynczo dla każdej oferty** poprzez: [PATCH na zasobie /sale/product-offers/{offerID}] gdyż jest to zadanie mało wydajne i dla nas i dla Allegro?

Chciałbym zrobić to tak jak wykonuje się inne operacje zbiorcze podając 100 czy 500 identyfikatorów ofert oraz nowy czas dostawy i zmienia się to jednym requestem tak jak to:

"offerCriteria": [
    {
      "offers": [ 
        {"id": ... }, 
        ... 
      ],
      "type": "CONTAINS_OFFERS"
    }
  ]

Zmiana czasu dostawy obecnie (pojedynczo) wykonuje się  obecnie kilka godzin, przez co nie wszystkie oferty zdążą się zaktualizować i część klientów kupuje towar z myślą iż dostanie go następnego dnia.

Proszę o informację, pomoc lub podpowiedź czy planują Państwo wdrożyć do API taką funkcjonalność.

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, nie ma możliwości wprowadzenia masowej zmiany czasu wysyłki w ofertach. Nie mamy tego też w planach na najbliższe zmiany. Swoją sugestię zmiany możesz zamieścić w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions).

**Comment by lukiopmoto** [comment]
To jaką metodę Państwo preferują w chwili obecnej do zmiany czasu dostawy dla pojedynczej oferty?

Dzisiaj przy próbie zmiany czasu dostawy dla oferty otrzymałem taką odpowiedź:

```
stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ConstraintViolationException.NoDuplicateIds
                    [message] => This parameter can be entered only once.
                    [details] => ConstraintViolationException.NoDuplicateIds
                    [path] => parameters
                    [userMessage] => Dany parametr możesz podać tylko raz.
                )
        )
)
```

Mój kod do zmiany czasy dostawy:

```
public function updateDeliveryTime($offerId, $deliveryHours) {
        $url = "https://api.allegro.pl/sale/product-offers/{$offerId}";

        $data = array(
            "delivery" => array(
                "handlingTime" => "PT{$deliveryHours}H"
            )
        );

        $response = $this->patch($url, $data);
        return $response;
    }
```

**Comment by MaciejFrackowiak** [comment]
PATCH wywołany jak na przykładzie niżej:
```
{ 
        "delivery": {
        "handlingTime": "PT24H"
         }
}
```
zmienił bez przeszkód czas wysyłki w ofercie. 
Sprawdź proszę poprawność swojego kodu.

**Comment by lukiopmoto** [comment]
Dzień dobry,

To proszę przez Api spróbować zmienić czas dostawy dla naszej oferty: 14737019721 na PT96H czy P4D 

Wywala błąd:
```
stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ConstraintViolationException.NoDuplicateIds
                    [message] => This parameter can be entered only once.
                    [details] => ConstraintViolationException.NoDuplicateIds
                    [path] => parameters
                    [userMessage] => Dany parametr możesz podać tylko raz.
                )
        )
)
```

**Comment by lukiopmoto** [comment]
Próba zmiany czasy dostawy na 4 dni dla tej oferty (13303678621) to taki błąd:

```
stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ConstraintViolationException.ImproperlyAssignedDictionaryParameter
                    [message] => The dictionary parameter should be completed through the value identifier for 250019.
                    [details] => ConstraintViolationException.ImproperlyAssignedDictionaryParameter
                    [path] => parameters[7]
                    [userMessage] => Parametr słownikowy należy uzupełnić poprzez identyfikator wartości dla 250019.
                )

            [1] => stdClass Object
                (
                    [code] => ConstraintViolationException.NoDuplicateIds
                    [message] => This parameter can be entered only once.
                    [details] => ConstraintViolationException.NoDuplicateIds
                    [path] => parameters
                    [userMessage] => Dany parametr możesz podać tylko raz.
                )

            [2] => stdClass Object
                (
                    [code] => ConstraintViolationException.NoValueInDictionaryParameter
                    [message] => No value was given for parameter (250019)
                    [details] => ConstraintViolationException.NoValueInDictionaryParameter
                    [path] => parameters
                    [userMessage] => Nie podano wartości dla parametru Model opony (250019).
                )
        )
)
```

**Comment by MaciejFrackowiak** [comment]
To są błędy walidacyjne ofert, a nie błędne czasy wysyłki. Podaj proszę trace-id dla powyższych operacji, abym mógł jednoznacznie stwierdzić, co jest nie tak z requestami.

**Comment by lukiopmoto** [comment]
Zauważyłem że problem dotyczy starszych ofert, wystawionych jeszcze jakiś czas temu. Nowym ofertom bez problemu zmieniam czas dostawy przez ten sam mechanizm.

**Comment by MaciejFrackowiak** [comment]
Jak wspomniałem - to są problemy walidacyjne parametrów oferty, a nie samego czasu wysyłki. Dlatego spójrz dokładnie w dane jakie są przekazywane w zakresie parametrów oferty.

**Comment by lukiopmoto** [comment]
No najwyraźniej przy okazji aktualizacji czasu dostawy (kod poniżej) ma miejsce też walidacja oferty, która nie pozwala na zmianę czasu dla starszych ofert. 

{ 
        "delivery": {
        "handlingTime": "PT24H"
         }
}

Jak znaleźć to trace-id? Co to jest? Gdzie go znajdę? Chętnie to Państwu podam.

**Comment by MaciejFrackowiak** [comment]
Trace-id znajdziesz w nagłówku (Headers) odpowiedzi od naszego serwera.

**Comment by lukiopmoto** [comment]
"trace-id: eaae4d61951dcd4b"

**Comment by lukiopmoto** [comment]
Ten trace-id (wyżej) to bezskuteczna próba zmiany czasu dostawy oferty 14647626629 na PT96H

**Comment by MaciejFrackowiak** [comment]
Gdy pobierzesz szczegóły oferty GET /sale/product-offers/{offerId} zobaczysz, że występuje tam parametr o id=237206 (Model), który obecnie nie jest dostępny w kategorii 257689. To on powoduje błąd, ponieważ obecnie jedynym właściwym parametrem modelowym jest 250019 - Model opony.

**Comment by lukiopmoto** [comment]
Ok, to jak w takim razie zmienić czas dostawy dla tych ofert? 

Wystawiając oferty przez API nie podawałem nazwy modelu tylko wskazałem: ID produktu allegro (wg produktyzacji).

**Comment by lukiopmoto** [comment]
Nie rozumiem dlaczego tak się  dzieje, to nielogiczne. Co ma model opony w ofercie do zmiany czasu dostawy? Przecież to nie powinno być weryfikowane w tym przypadku. Mamy czekać jakoś, aż Państwo to jakość naprawią czy trzeba usunąć wszystkie oferty i dodać na nowo?

**Comment by lukiopmoto** [comment]
Pobrałem ofertę i ma ona parametr model o id=237206. Piszą Państwo że nie posiada obecnie przypisanego do siebie parametru Model o id=237206. A posiada, proszę sprawdzić co zwraca API dla tej oferty:

```
[6] => stdClass Object
                                        (
                                            [id] => **237206**
                                            [name] => Model
                                            [values] => Array
                                                (
                                                    [0] => Powergy
                                                )

                                            [valuesIds] => 
                                            [rangeValue] => 
                                        )
```

Jest też drugi parametr model, z tym że ja go nie dodawałem do oferty, tylko Państwo. Nie rozumiem czemu ja miałbym teraz dla tysięcy ofert go aktualizować.

```
[17] => stdClass Object
                                        (
                                            [id] => 250019
                                            [name] => Model opony
                                            [values] => Array
                                                (
                                                    [0] => P6000 Powergy
                                                )

                                            [valuesIds] => Array
                                                (
                                                    [0] => 250019_1790981
                                                )

                                            [rangeValue] => 
                                        )
```

**Comment by MaciejFrackowiak** [comment]
Wspominałem o produkcie - a nie o ofercie, który już tego parametru (Model) nie posiada. Na chwilę obecną konsultuję sytuację z zespołem odpowiedzialnym za zmianę, czy istnieje możliwość "odświeżenia" ofert bez ingerencji użytkownika.

**Comment by lukiopmoto** [comment]
Super, będę wdzięczny za wszelkie informacje.

W między czasie proszę podpowiedzieć, jak usunąć parametr Model w danej ofercie? Jaka metodą się posłużyć w Państwa API?

**Comment by lukiopmoto** [comment]
Dla produktu Allegro: ae906785-a760-4d68-a2c9-eb7aa6283eeb jeszcze 25 stycznie tego roku parametr Model znajdował się pod ID parametru: 237206. 

Nagle po kilku dniach chcę zmienić czas dostawy dla tego produktu i się nie daje bo zmieniliście mu Państwo ID Modelu z 237206 na 250019.

Dlaczego to się automatycznie nie zaktualizowało w ofertach skoro zmienił się tylko ID parametru produktu?

Inni nasi koledzy z branży widzę wybrali technikę usuwania dziesiątek tysięcy ofert bo też nie poradzili sobie z tym błędem. Proszę o odpowiedź czy możecie Państwo automatycznie to przegenerować czy też trzeba będzie usuwać 50tys. ofert?

Od kiedy jeżeli to nie tajemnica pojawił się ten nowy parametr Model opony (250019) w oponach osobowych? Bo widzę że terenowe i dostawcze mają cały czas 237206, chyba że to też tymczasowo.

**Comment by lukiopmoto** [comment]
Dzień dobry, czy możecie Państwo przegenerować automatycznie dla naszych ofert te ID parametrów Modeli. Tak by oferty podpięte pod produkty które mają obecnie dwa parametry odpowiedzialne za model (250019, 237206) lub mają nieprawidłowy ten parametr (237206 zamiast 250019) zostały poprawnie zwalidowane i można będzie im edytować chociażby czas dostawy.

W przeciwnym wypadku jednym rozwiązaniem będzie usunięcie całej naszej oferty z Allegro i wystawienie na nowo.

**Comment by MaciejFrackowiak** [comment]
Otrzymałem informację, że paramer Model (237206) został odpięty od ofert. Operacja ta powinna umożliwić edycję ofert bez żadnych problemów już.

**Comment by lukiopmoto** [comment]
No ok dziękuję. A co z przypadku gdy to był (237206) jedyny parametr w ofercie odpowiadający za informację o Modelu? Przykładowo w oponach terenowych i dostawczych Model przekazywany jest tylko i wyłącznie w tym parametrze (237206) a jego usunięcie może spowodować, wspomnianą sytuację gdzie w ofercie nie ma żadnej informacji o Modelu, przez co też nie da się edytować takiej oferty przez API bo walidacja nie zakończy się pomyślnie.

**Comment by MaciejFrackowiak** [comment]
Mówimy tu cały czas o kategoriach, w których pojawił się parametr Model opony (250019). Nie wychodźmy poza zakres zgłaszanego na wstępie problemu.

**Comment by lukiopmoto** [comment]
Np. oferta 15069687396 nie ma żadnej informacji w produkcie o Modelu i nie da się jej edytować. Jedyny parametr informujący o modelu (237206) został usunięty. A nie zastąpiono go nowym odpowiednikiem. Czy jest szansa, aby teraz i takie oferty uzupełnić o brakujące modele?

**Comment by lukiopmoto** [comment]
Problem został rozwiązany połowicznie. W sytuacji gdy oferta miała zdublowane modele (237206 i 250019) i usunięto 237206 to wszystko działa już poprawnie i oferty takie da się edytować.

Drugi jednak przypadek, gdy oferta posiadała tylko jeden parametr odpowiadający za model i był to (237206) - w efekcie otrzymaliśmy oferty bez żadnego parametru informującego o Modelu co skutkuje brakiem możliwości edytowania takiej oferty. 

Czy widzą  Państwo jakieś sensowne rozwiązanie tego problemu? np. przegenerowanie ofert które miały Model podany w parametrze (237206) i uzupełnienie tych ofert o nową wartość Modelu tj. parametr 250019? Czy są na to jakieś szanse?

Rozumiem że parametr Model o ID 250019 występuje tylko w kategoriach:            
 '257689', // Osobowe letnie
'257691', // Osobowe zimowe
'257692', // Osobowe całoroczne

W oponach terenowych i dostawczych parametr Model to cały czas 237206, tak? Czy to też za chwilę się zmieni?

**Comment by lukiopmoto** [comment]
Komunikat z API przy próbie edycji wspomnianej oferty:
```
{
code:ConstraintViolationException.MissingRequiredParameters, 
message:Missing required parameters: 250019,
details:ConstraintViolationException.MissingRequiredParameters,
path:parameters,
userMessage:Uzupe\u0142nij parametry obowi\u0105zkowe: Model.
}
```

Dodam tylko że takich ofert mamy setki.

**Comment by MaciejFrackowiak** [comment]
Na przykładzie oferty nr 15069687396 - oferta jako wartość dla parametru 237206 miała podane "2156516H", co nie jest prawidłowym modelem tej opony. W związku z tym wartość z 237206 nie została zmigrowana do parametru z id=250019. Każda kolejna oferta, która miała niewłaściwą wartość podaną jako Model nie została zmapowana na wartość w nowym parametrze 250019. W tym momencie należy edytować takie oferty i określić dla nich wartość w parametrze 250019.
Parametr 250019 jest dostępny obecnie w kategoriach:
- Motoryzacja > Opony i felgi > Opony > Do samochodów osobowych
- Motoryzacja > Opony i felgi > Opony > Do samochodów osobowych > Letnie
- Motoryzacja > Opony i felgi > Opony > Do samochodów osobowych > Zimowe
- Motoryzacja > Opony i felgi > Opony > Do samochodów osobowych > Całoroczne

Proces ten odbywa się całkowicie poza API, dlatego nie sposób mi odpowiedzieć na pytanie co do dalszych planów zmian.

**Comment by MaciejFrackowiak** [comment]
Nie, nie przewidujemy takiej edycji aktualnych ofert.

**Comment by lukiopmoto** [comment]
OK dziękuję.

**Comment by lukiopmoto** [comment]
Na koniec prośba o usunięcie numerów ofert o których wspominałem w odpowiedziach. Można je częściowo wygwiazdkować lub całkowicie usunąć. Ja nie mam takiej możliwości.
