### ISSUE TITLE
Połączenie z API

### ISSUE THREAD

**Issue by krasu11** [allegro/allegro-api#8380]
Witam,
Mam pytanie odnośnie podłączenia się do API. Chciałbym, aby klienci mieli możliwość "przerzucania" swoich ofert z allegro na inną stronę oraz żeby automatycznie oferty się aktualizowały przy ewentualnej sprzedaży na dwóch stronach (stan magazynowy).
Czy allegro pobiera za coś takiego opłaty? Jakie dokładnie ustawienia przy rejestracji aplikacji powinienem wybrać, aby wszystko było poprawnie ustawione? Czy macie jakieś specjalne wymagania przy tego typu rzeczach?

**Comment by MaciejFrackowiak** [comment]
Dostęp do naszego API jest bezpłatny. Wszelkie kwestie związane z realizacją projektu, o którym wspomniałeś pozostają w Twojej gestii. Dokumentację naszych zasobów znajdziesz [tu](https://developer.allegro.pl/documentation/), a wiele pomocnych informacji znajdziesz w naszych poradnikach na [portalu developerskim](https://developer.allegro.pl/).
