### ISSUE TITLE
billing/billing-entries

### ISSUE THREAD

**Issue by Eryk1997** [allegro/allegro-api#8382]
Dzień dobry, 
czy jest możliwość otrzymania przykładowych responsów dla 
- Dopłata do Smarta
- Allegro cena

z endpointu billing/billing-entries? 
ewentualnie jaki jest type dla tych przykładów

**Comment by MaciejFrackowiak** [comment]
Opłata za Smart jest wliczana w prowizję od sprzedaży, nie ma osobnego typu zdarzenia billingowego.
Natomiast "Wyrównanie w programie Allegro Ceny" ma typ "PS1". Nie dysponujemy przykładowymi wywołaniami dla każdego typu opłaty billingowej. Testowe dane możesz uzyskać na Sandbox.
