### ISSUE TITLE
Możliwość pobrania przez API ustawień wysyłki tego samego dnia

### ISSUE THREAD

**Issue by relains** [allegro/allegro-api#8383]
Dzień dobry,

Szukam w dokumentacji i nie mogę znaleźć czy jest gdzieś opcja pobierania ustawień dni i godzin wysyłki tego samego dnia, które ustawia się w tym miejscu?

https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-granicznych-godzin-wysylki

Pozdrawiam
Rafał Stępień

**Comment by MaciejFrackowiak** [comment]
Te ustawienia dostępne są tylko na stronie WWW.
