### ISSUE TITLE
Allegro FBA - zamówienia

### ISSUE THREAD

**Issue by jakub-marchewka** [allegro/allegro-api#8384]
Dzień dobry, czy w przypadku zamówień FBA informacja o wysłaniu przesyłki przez Allegro znajdzie się w zasobie order events w zdarzeniu FULFILLMENT_STATUS_CHANGED?

**Comment by MartaNowaczyk** [comment]
Tak, to zmiana statusu zamówienia, więc będzie w zdarzeniu FULFILLMENT_STATUS_CHANGED
