### ISSUE TITLE
Zmiana tytułu oferty

### ISSUE THREAD

**Issue by slawomir-kudla** [allegro/allegro-api#8385]
Witam

Wystawiam ofertę z jej atrybutami a jednym z atrybutów jest klucz "name" i on jest dokładnie pod takim adresem:

`[productSet][0][product][name] => Tytuł oferty`

ów tytuł przechodzi poprawnie podczas pierwszego wystawienia oferty, jednak próbując zaktualizować tytuł na jakiś inny np.

`[productSet][0][product][name] => Nowy tytuł`

To wszystkie atrybuty które próbuję zaktualizować przechodzą poprawnie prócz tego konkretnego "name" (pozostaje stara wartość)

co jest powodem? po wystawieniu oferty (jeszcze bez publikacji) jest zblokowana możliwość zmiany tego parametru?

Sprawdzam na środowisku testowym
`trace-id: 8e86030f3385091d`

**Comment by MartaNowaczyk** [comment]
Zmiana tytułu powinna być możliwa. Widzę, że kilka razy zmieniałeś dane na tej ofercie, ale z tego co widzę, przy ostatniej zmianie podałeś nowy tytuł "Renault Scenic WWW12", a zwracamy nadal "Renault Scenic XYZ12", także jeszcze to zweryfikuję i wrócę do ciebie z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Nazwa się nie zmienia, bo zmieniasz nazwę produktu "product.name", a tego nie zrobisz przez PATCH, jedynie możesz zasugerować zmianę przez [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal). Możesz też edytować samą nazwę oferty np. wysyłając PATCH z samym polem "name".

**Comment by slawomir-kudla** [comment]
nie wiem czy konstrukcyjnie popełniam błąd ale API sugeruje że produkt nie istnieje

```
[code] => ProductForSuggestedProposalDoesNotExistException
[message] => Product with id: 7745351096 does not exist for suggested proposal
[details] => 
[path] => /sale/products/7745351096/change-proposals
[userMessage] => Przesłano niepoprawne żądanie. Produkt o podanym ID: 7745351096 nie istnieje.
```

`trace-id: 1d5f2869fe330309`

**Comment by MartaNowaczyk** [comment]
To co podajesz, to nie id produktu tylko numer oferty. Jak chcesz zmienić tytuł oferty przy edycji wyślij "name" poza obiektem "productSet".

**Comment by slawomir-kudla** [comment]
Dzień dobry

Nie bardzo rozumiem Pani koncepcji w ów requecie pole "name" które było poza obiektem productSet przykład:

```
[method] => post
[uri] => /sale/products/7745351096/change-proposals
[data] => [
      [language] => pl-PL
      [name] => Nowa wartość
      [note] => Some additional note to product changes proposal.
      [category] => [
             [id] => 18374
      ]
)
```

Też nie mam czegoś takiego jak id produktu mam tak prawdę mówiąc jedynie id oferty

czy jest możliwość przy użyciu id oferty zmiana tytułu? bardzo proszę o jakiś przykład

**Comment by MartaNowaczyk** [comment]
Może niejasno się wyraziłam. Zmianę tytułu możesz zrobić metodą `PATCH /sale/product-offers/7745351096` wystarczy przesłać np.

```
{
"name": "zamieniony tytuł"
}
```
[POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal) używasz, gdy chcesz zmian w produkcie w Katalogu Produktów allegro.

**Comment by slawomir-kudla** [comment]
dzięki działa
