### ISSUE TITLE
Nie połączysz oferty z wybranym produktem. 

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#8386]
Dzień dobry, co może powodować taki błąd przy próbie edycji oferty? Prosił bym o wyjaśnienie.

trace-id: bf6a5012364a22c6

treść błędu:
{
  "errors": [
    {
      "code": "ProductConstraintViolationException.DataIntegrity",
      "message": "The offer can not be linked to the product. The product does not match the offer. It was previously unlinked. Select another product.",
      "details": null,
      "path": null,
      "userMessage": "Nie połączysz oferty z wybranym produktem. Produkt nie pasuje do oferty i został już wcześniej odłączony. Wybierz inny produkt."
    }
  ]
}

**Comment by MartaNowaczyk** [comment]
To nie kwestia samego API, więc wyjaśnienie sytuacji zajęło mi trochę czasu. Udało mi się ustalić, że produkt był już jakiś czas temu uznany jako niezgodny z tym, co jest w ofercie i został odłączony od oferty - stąd ten błąd. Po Twoim zgłoszeniu zweryfikowano dane ponownie i teraz nie widać niezgodności. Tym samym przywrócono produkt i błąd nie powinien już występować.
