### ISSUE TITLE
What is the best way to link a Magento 2 storefront to Allegro?

### ISSUE THREAD

**Issue by ETBTSH** [allegro/allegro-api#8387]
Looking at extending our product catalogue onto Allegro. Using Magento 2, is there any recommended connectors? I've seen CEDCommerce and Macopedia but from what I read they both have serious issues either via customer service or not connecting to Allegros API. Does anyone have any suggestions please?

**Comment by AureliuszBrussy** [comment]
For our part, we can not recommend any specific solution. However, maybe one of the other users will point something out or give you a suggestion.
