### ISSUE TITLE
error: 9022503b81c20fb8, 29c06c6ee8566a9, a61d398dff89833b

### ISSUE THREAD

**Issue by AlleOllePL** [allegro/allegro-api#8388]
We trying to connect to the Rest API in sandbox. We created our app: AlleOlle_Ocena_Bot and granted the following scopes

- allegro:api:sale:offers:read
- allegro:api:sale:offers:write
- allegro:api:sale:settings:read
- allegro:api:ads
- allegro:api:campaigns

the link to the app is the following: https://apps.developer.allegro.pl.allegrosandbox.pl/edit/fa8521ac97bf4411ab9a0c04b13a5b55

We successfully managed to issue access token with our client id and secret on this endpoint: 

POST https://allegro.pl.allegrosandbox.pl/auth/oauth/token

We receive the following result

{
    "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6cmVhZCJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9hbGxlZ3JvLnBsLmFsbGVncm9zYW5kYm94LnBsIiwiZXhwIjoxNzA2Njg1NTg1LCJqdGkiOiIwZjFlZjkzNC0zZTFhLTQ3MDctOGNlMC00Zjg5YWUwZjZiYjgiLCJjbGllbnRfaWQiOiJmYTg1MjFhYzk3YmY0NDExYWI5YTBjMDRiMTNhNWI1NSJ9.b_KLGVfYCM92HVY6i58PCJysT4zzulOeobw-3d_Ekbva3YUvWADHaz84mqUAsLXw0ORHdL-3OCg0skzwYoF0LldAvqu94kDnZwuT7PMV1W7qP_GROYmRekdxOBvKRF93wWc0O2iZzjtF1o7Vvo11SFMebXrr2RioPs_nPs7yMLUsdHoHZrQa7Do52UPCK1GQ5t53sSpJc3XH6KbvwGOv4Yx4CuunXJshSwPSiQyuCjjvUQfSKREo6DgK1CuW874rp8LJslJjoPdTtzph5J6fv3T9etq6Jp6w6D48TASDDrvmTeANhfDZOgD_HK8ypYbITF25rbz5MW3qx082ugMOykgsX3n77AcmoTomQ1jgmCmZ5xbSzTmg0etdA8OMwN-4zTE-RLbPy5-5lVDcF4T3BBzUQ7A_pJwUkZHWncWMfPEeaH3XJCKyNzb-OHT6s1lzHa2pdHTMM6BKcEeAFQSF0saa4naDbcm5UpSNVXdiPkfv3YAxogG2_RTR20eqU5Nmn5tz-4A3YE5UNiTpzczG1GOHXbSkrIhl6zN_uqPi_cCxpVLqT3pCh9H_IQpUTTkdMO8JMZZFMc1T6aWNJn9nuwvEQKXC70BuUTQmg3mPYDVOz_Rh3FCwNRJZmZofk8sTgv0w8-qWXvIla1dmeVH6lIbT0c-j9KYora4CeIIHw6g",
    "token_type": "bearer",
    "expires_in": 43199,
    "scope": "allegro:api:ratings allegro:api:sale:offers:read",
    "allegro_api": true,
    "iss": "https://allegro.pl.allegrosandbox.pl",
    "jti": "0f1ef934-3e1a-4707-8ce0-4f89ae0f6bb8"
}

However, if we try to request offers from the API, we get Access denied error

Here is an example of the request:

GET https://api.allegro.pl.allegrosandbox.pl/sale/offers

Response

{
    "errors": [
        {
            "code": "AccessDenied",
            "message": "Access is denied",
            "details": null,
            "path": null,
            "userMessage": "No access to the specified resource."
        }
    ]
}

We are providing you few trace ids for debugging purpose, all of them have the same error: 9022503b81c20fb8, 29c06c6ee8566a9, a61d398dff89833b

**Comment by AureliuszBrussy** [comment]
[GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) resource requires "bearer-token-for-user" authorization ([code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow). In your request, you used a [client_credentials](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#clientcredentials-flow) authorization which does not have a user context. Please, change authorization method.
