### ISSUE TITLE
Brak dzieci kategorii Smartfony i telefony komórkowe

### ISSUE THREAD

**Issue by przemek-pacura** [allegro/allegro-api#8389]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Endpoint https://api.allegro.pl/sale/categories?parent.id=4 dla Smartfony i telefony komórkowe zwraca
(...)
            "id": "165",
            "name": "Smartfony i telefony komórkowe",
            "parent": {
                "id": "4"
            },
            "leaf": true,
(...)
Patrząc na www (https://allegro.pl/kategoria/smartfony-i-telefony-komorkowe-165) gdzie mamy podkategorie to chyba powinien zwracać leaf false i powinna być możliwość pobrania jego dzieci po po jego id?
Endpoint https://api.allegro.pl/sale/categories?parent.id=165 zwraca pustą listę kategorii gdzie dla innych jak np. Smartwatche mamy poprawną listę podkategorii.

**Comment by AureliuszBrussy** [comment]
W zasobie /sale/categories otrzymujesz tzw. drzewo asortymentowe, w którym są dostępne kategorie dla sprzedających. Po stronie kupującego natomiast widnieje tzw. drzewo nawigacyjne i różni się ono od tego asortymentowego. 

W drzewie nawigacyjnym grupujemy oferty na podstawie parametrów w ofercie. Więcej o tym możesz przeczytać w [naszym newsie](https://developer.allegro.pl/news/w-styczniu-2024-zmniejszymy-liczbe-kategorii-po-stronie-sprzedajacego-w-smartfonach-i-telefonach-komorkowych-zl0K8K3dXcy).

**Comment by p3le** [comment]
Czy to samo tyczy się podkategorii w Kultura i rozrywka > Książki i Komiksy > Książki dla dzieci > Literatura dziecięca? Odpowiedź z `/sale/categories?parent.id=66781` zwraca pustą tablicę kategorii. Na froncie aplikacji podkategorie już są:

![image](https://github.com/allegro/allegro-api/assets/2972454/7b868527-5a71-4d7c-8f0e-100ad7be2760)

natomiast w parametrach tej podkategorii nie ma:

![image](https://github.com/allegro/allegro-api/assets/2972454/ce564669-d3a8-4b34-b188-d179c57d3823)

Trace-id: 3c9a52928e50b7c0

**Comment by AureliuszBrussy** [comment]
@p3le tak, tutaj jest taka sama sytuacja.

**Comment by p3le** [comment]
> @p3le tak, tutaj jest taka sama sytuacja.

Ok, to w takim razie:
1. dlaczego w aukcjach nie widać tych parametrów?
2. dlaczego aukcje wystawione w podkategoriach, które teraz są parametrami mają przypisane stare category.id?

Na ten moment jest to bardzo problematyczne, bo o ile w aukcjach z podkategorii smartfonów, id kategorii zostało zmienione, o tyle te zgłaszane przeze mnie maja stare id kategorii, które nie istnieje.

**Comment by p3le** [comment]
> Kategoria 66781 (Książki dla dzieci) to kategoria najniższego rzędu - nie ma już podkategorii. W drzewie nawigacyjnym grupujemy podkategorie na podstawie parametru "Gatunek" (249493), gdzie znajduje się m.in. gatunek o nazwie "Literatura dziecięca". W jakiej ofercie posiadasz zapisaną kategorię, która nie istnieje?

Chociażby oferty, które zwróci API na taki request:

`{
    "phrase": "9788366005150",
    "sellingMode.format": "BUY_NOW",
    "parameter.11323": "11323_1",
    "option": [
        "SMART"
    ],
    "limit": 5
}`

**Comment by AureliuszBrussy** [comment]
Jest tak, ponieważ [GET /offers/listing](https://developer.allegro.pl/documentation#tag/Public-offer-information) zwraca wyniki w ramach drzewa nawigacyjnego, a nie asortymentowego. Jeżeli odpytasz o ofertę w imieniu wystawiającego sprzedawcy (np. GET /sale/product-offers/{offerId}), przypisana kategoria będzie zgodna z kategorią asortymentową.
