### ISSUE TITLE
Błędny sposób i koszt dostawy w mailu po zakupie (Koszt wpisany przez Kupującego)

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#839]
Witam,

sporadycznie w mailach które otrzymujemy po sprzedaży jest informacja:
`Sposób i koszt dostawy | Koszt wpisany przez Kupującego Inny sposób dostawy 8,99 zł`

natomiast do tej samej transakcji w zakładce zamówienia czy też w karcie płatności jest już informacja:
`Sposób dostawy: Allegro Paczkomaty 24/7 InPost |   | 8,99 zł`

![bez tytulu](https://user-images.githubusercontent.com/36523118/47681169-18748900-dbc9-11e8-9562-96072fa63dd0.png)

Czym to może być spowodowane?

**Comment by MartaNowaczyk** [comment]
@dlis2010 na pewno nie dostaliście innego maila z ponownym wyborem sposobu dostawy?

**Comment by dlis2010** [comment]
@MartaNowaczyk nie, jest to jedyny fod wypełniony przez kupującego.
Mamy tego sporo więcej, kilka transakcji z ostatnich dni (id wpłaty):  

920487901, 920468621, 920388813
`Sposób i koszt dostawy | Koszt wpisany przez Kupującego Inny sposób dostawy 8,99 zł`

920426653, 920346034
`Sposób i koszt dostawy | Koszt wpisany przez Kupującego Inny sposób dostawy 8,00 zł`

Każdorazowo jest wypełniany fod tylko raz. Jak widać dotyczy to zarówno paczkomatu jak i poczty.

**Comment by dlis2010** [comment]
@MartaNowaczyk jakieś nowe informacje?

**Comment by PawelTaberski** [comment]
Ponagliłem zespół pracujący nad tym problemem, mam nadzieję, że niedługo rozwiążą ten problem. Proszę o cierpliwość.
