### ISSUE TITLE
Problem z aktualizacją produktu OFFER_CHANGED 

### ISSUE THREAD

**Issue by potockit** [allegro/allegro-api#8390]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,

Chciałbym zgłosić problem dotyczący integracji naszej aplikacji z Allegro. Pojawia się on podczas synchronizacji danych ofert. Nasz system automatycznie pobiera informacje o nowych aukcjach utworzonych na Państwa portalu. Klienci często korzystają z opcji "stwórz podobny". 
Niestety, eventy dotyczące tej operacji wysyłany jest przed finalizacją zmian przez klienta, a event OFFER_CHANGED nie jest później wysyłany co powoduje brak ponownej synchronizacji oferty.

Przykładem jest docelowa aukcja X utworzona na podstawie Y importujemy ja na pierwszy event jaki przyjdzie następnie klient modyfikuje produkt (zdjęcia, cenę, itd) niestety event OFFER_CHANGED nie zostaje wysłany i aukcja nie zostanie ponownie zaktualizowana. 

Przykładowa aukcja pobrana z Allegro pobrała następujące dane:

![obraz](https://github.com/allegro/allegro-api/assets/32292568/1d50107e-eac0-4e21-b4da-8aa51ba8bcda)

a tak wygląda produkt w serwisie Allegro

![obraz](https://github.com/allegro/allegro-api/assets/32292568/6377348d-330f-4631-b14c-24214757c409)

Aktualna cena produktu to 489 zł my odebraliśmy, że wartość produktu to 98 zł, często mamy zdjęcia zaciągnięte z poprzedniego produktu.

Eventy dla powyższego przykładu jakie przychodzą to:
<tu lista>

Proszę o weryfikacje
dla ofert 15112153616 lista Event-ów
2024-01-31 16:15:16.371 EventType=OFFER_TRANSLATION_UPDATED
2024-01-31 16:15:16.149 EventType=OFFER_STOCK_CHANGED
2024-01-31 16:15:16.131 EventType=OFFER_ACTIVATED
2024-01-31 15:15:19.554 EventType=OFFER_STOCK_CHANGED

**Comment by AureliuszBrussy** [comment]
Analizujemy to. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Te zmiany były wykonane na ofercie jeszcze nieaktywowanej (drafcie). Zwracamy natomiast eventy tylko dla ofert aktywnych, albo zaplanowanych do aktywowania (wypełnione pole publication.startingAt).
