### ISSUE TITLE
Weryfikujemy dane Twojej firmy

### ISSUE THREAD

**Issue by Eryk1997** [allegro/allegro-api#8391]
Dzień dobry, czy mogę prosić o aktywację konta firmowego? 
konto: Eryk_innovation
<img width="1010" alt="Zrzut ekranu 2024-01-31 o 17 46 11" src="https://github.com/allegro/allegro-api/assets/33696058/af7fe5fa-7537-4c79-b4eb-f209e1099a0d">

Chciałbym dodać oferte, która otrzyma "supercena" (ALLEGRO_PRICES), a bez tego chyba jest to niemożliwe.

**Comment by AureliuszBrussy** [comment]
Aktywowałem Twoje konto.
