### ISSUE TITLE
Tworzenie oferty na zestaw

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#8392]
Witam, 

prosił bym o wskazanie fragmentu dokumentacji API allegro która wskazuje jak poprawnie powinno się tworzyć ofertę produktową na zestaw składający się z kilku różnych produktów.

**Comment by AureliuszBrussy** [comment]
Fragment dot. tworzenia zestawów produktowych znajdziesz [w naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-utworzyc-zestaw-produktowy). Oczywiście źródłem będzie także sama dokumentacja: [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers).
