### ISSUE TITLE
Wysyłka do czech (zamówienie z czech)

### ISSUE THREAD

**Issue by krzysda** [allegro/allegro-api#8393]
Witam,
Dlaczego generując etykietę w serwisie 1401412f-1bcc-4dad-98c4-b3146fe9f54a Allegro International Kurier Czechy pobranie
podaję kwotę zamówienia w CZK i otrzymuję komunikat: 

Waluta nie jest wspierana przez metodę dostawy

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swojego wywołania, wówczas będę mógł sprawdzić szczegóły.

**Comment by krzysda** [comment]
65bb5e0d-65bb-65bb-65bb-65bb5e0d3663

**Comment by MaciejFrackowiak** [comment]
Problem stanowi waluta ubezpieczenia (items.value) - powinno być wyrażone w CZK, a masz w PLN.

**Comment by krzysda** [comment]
Faktycznie, ok dzięki

**Comment by krzysda** [comment]
Czy można jeszcze sprawdzić ten numer 5bcb71e-65bc-65bc-65bc-65bcb71e2c06 podobny problem

**Comment by MaciejFrackowiak** [comment]
W logach za ostatnie 14 dni nie mogę namierzyć podanego commandId - sprawdź proszę jego poprawność.

**Comment by krzysda** [comment]
a faktycznie: 65bcb71e-65bc-65bc-65bc-65bcb71e2c06

**Comment by MaciejFrackowiak** [comment]
W tym przypadku ubezpieczenie jest wyrażone w CZK, a powinno być w PLN.

**Comment by krzysda** [comment]
ale kwota pobrania może być w CZK

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak.

**Comment by krzysda** [comment]
ok dzięki
