### ISSUE TITLE
Wyjaśnienie przyczyny problemu podczas tworzenia przesyłki przez API produkcyjne

### ISSUE THREAD

**Issue by inTestowy** [allegro/allegro-api#8394]
Dzień dobry,

chciałabym uzyskać informację zwrotną co jest przyczyną nie utworzenia przesyłki za pomocą API produkcyjnego. Z Państwa strony otrzymujemy zwrotkę:

{"id":"f912f8f3-1ff4-41cf-9b76-3db89d10c449","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","details":null,"message":"Processing error","path":"","userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}]}

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Problem stanowią wymiary przesyłki, które podałaś:
```
"items": [
        {
            "dimensions": {
                "height": {
                    "value": 0,
                    "unit": "CENTIMETER"
                },
                "width": {
                    "value": 0,
                    "unit": "CENTIMETER"
                },
                "depth": {
                    "value": 0,
                    "unit": "CENTIMETER"
                }
            }
```
Zamiast 0 powinny pojawić się realne wartości.

**Comment by inTestowy** [comment]
ok, rozumiem. 

Dziękuje za pomoc.
