### ISSUE TITLE
Katalog Produktów

### ISSUE THREAD

**Issue by PiotrPiotrP** [allegro/allegro-api#8398]
Dzień dobry

dostałem taki komunikat:

POST   https://api.allegro.pl/sale/product-offers/ requestBody={"productSet":[{"quantity":{"value":1},"product":{"name":"TED BAKER TOERBKA CZARNA Z KOKARDĄ DAMSKA  1ŻGA","idType":"GTIN","parameters":[{"id":"203889","valuesIds":["203889_246982"]},{"id":"15851","valuesIds":["15851_1"]},{"id":"3766","valuesIds":["3766_2397"]},{"id":"203921","valuesIds":["203921_218377"]},{"id":"249512","valuesIds":["249512_1647413"]},{"id":"3786","valuesIds":["3786_270502"]},{"id":"715","valuesIds":["715_1"]},{"id":"203885","valuesIds":["203885_218309"]},{"id":"203893","valuesIds":["203893_2048"]},{"id":"234373","valuesIds":["234373_383065"]}],"category":{"id":"261793"},"images":["https://images.stocksell.io/images/2c/2c2bf782-0089-434e-add6-60513baeeb98","https://images.stocksell.io/images/13/130da063-676c-4e31-8d9e-cee83a8af509","https://images.stocksell.io/images/6f/6f97b41a-674f-4116-9b28-e1295f58c9df"]}}],"category":{"id":"261793"},"delivery":{"shippingRates":{"id":"92cb3f82-ae74-4d10-8804-2d9a444c4d55"},"handlingTime":"PT24H"},"publication":{"startingAt":"2024-02-02T17:42:52.000Z","republish":false},"language":"pl-PL","afterSalesServices":{"impliedWarranty":{"id":"3de10450-def9-43dd-8c04-408fa5115f8a"},"returnPolicy":{"id":"10bbd9d6-a61a-421b-aafd-e2289c330400"},"warranty":{"id":"aced38bb-6db9-4e8e-b2a9-ebc1d31b5ac5"}},"stock":{"available":1,"unit":"UNIT"},"parameters":[{"id":"11323","valuesIds":["11323_1"]},{"id":"229205","valuesIds":["229205_340261"]}],"name":"TED BAKER TOERBKA CZARNA Z KOKARDĄ DAMSKA  1ŻGA","payments":{"invoice":"VAT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":150.99,"currency":"PLN"}},"location":{"city":"Skawina","countryCode":"PL","postCode":"32-050","province":"MALOPOLSKIE"},"images":["https://images.stocksell.io/images/2c/2c2bf782-0089-434e-add6-60513baeeb98","https://images.stocksell.io/images/13/130da063-676c-4e31-8d9e-cee83a8af509","https://images.stocksell.io/images/6f/6f97b41a-674f-4116-9b28-e1295f58c9df"],"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003ch2\u003eTED BAKER TOERBKA CZARNA Z KOKARDĄ DAMSKA\u003c/h2\u003e"}]},{"items":[{"type":"IMAGE","url":"https://images.stocksell.io/images/2c/2c2bf782-0089-434e-add6-60513baeeb98"},{"type":"TEXT","content":"\u003ch2\u003eOpis Produktu\u003c/h2\u003e\u003cul\u003e\u003cli\u003e\u003cb\u003eMarka\u003c/b\u003e Ted Baker\u003c/li\u003e\u003cli\u003e\u003cb\u003eKolor\u003c/b\u003e czarny\u003c/li\u003e\u003cli\u003e\u003cb\u003eSkład\u003c/b\u003e 100% polichlorek winylu\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka papierowa\u003c/b\u003e Brak\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka wewnętrzna\u003c/b\u003e \tTak\u003c/li\u003e\u003cli\u003e\u003cb\u003eRozmiar uniwersalny\u003c/b\u003e\u003c/li\u003e\u003cli\u003e\u003cb\u003eStan przedmiotu\u003c/b\u003e Smugi różnej wielkości na materiale.\u003c/li\u003e\u003cli\u003e\u003cb\u003eCena katalogowa\u003c/b\u003e 183,99 zł\u003c/li\u003e\u003c/ul\u003e"}]},{"items":[{"type":"IMAGE","url":"https://images.stocksell.io/images/13/130da063-676c-4e31-8d9e-cee83a8af509"},{"type":"IMAGE","url":"https://images.stocksell.io/images/6f/6f97b41a-674f-4116-9b28-e1295f58c9df"}]}]},"external":{"id":"stocksell_886243578"},"taxSettings":{"rates":[{"countryCode":"PL"}]}} exception=Niepoprawna odpowiedź z Allegro. Kod: 422. Błąd: offerCounter Nie wystawisz kolejnej oferty z tym produktem. W tej kategorii możesz przyłączyć max 5 ofert do jednego produktu. Znajdź inny produkt w Katalogu lub dodaj nowy. You will not create another offer with this product. In this category, you can attach a maximum of 5 offers to one product. Find another product in the Catalog or add a new one. . Trace-id=[d1579391f9650bee].

a produktu z eanem 5906224100494 nie ma w katalogu.

**Comment by PiotrPiotrP** [comment]
POST   https://api.allegro.pl/sale/product-offers/ requestBody={"productSet":[{"quantity":{"value":1},"product":{"name":"TED BAKER TOERBKA CZARNA Z KOKARDĄ DAMSKA  1ŻGA","idType":"GTIN","parameters":[{"id":"203921","valuesIds":["203921_218377"]},{"id":"225693","values":["5906224100494"]},{"id":"15851","valuesIds":["15851_1"]},{"id":"249512","valuesIds":["249512_1647413"]},{"id":"715","valuesIds":["715_1"]},{"id":"203893","valuesIds":["203893_2048"]},{"id":"203889","valuesIds":["203889_246982"]},{"id":"203885","valuesIds":["203885_218309"]},{"id":"234373","valuesIds":["234373_383065"]},{"id":"3766","valuesIds":["3766_2397"]},{"id":"3786","valuesIds":["3786_270502"]}],"category":{"id":"261793"},"images":["https://images.stocksell.io/images/2c/2c2bf782-0089-434e-add6-60513baeeb98","https://images.stocksell.io/images/13/130da063-676c-4e31-8d9e-cee83a8af509","https://images.stocksell.io/images/6f/6f97b41a-674f-4116-9b28-e1295f58c9df"]}}],"category":{"id":"261793"},"delivery":{"shippingRates":{"id":"92cb3f82-ae74-4d10-8804-2d9a444c4d55"},"handlingTime":"PT24H"},"publication":{"startingAt":"2024-02-02T18:55:30.000Z","republish":false},"language":"pl-PL","afterSalesServices":{"impliedWarranty":{"id":"3de10450-def9-43dd-8c04-408fa5115f8a"},"returnPolicy":{"id":"10bbd9d6-a61a-421b-aafd-e2289c330400"},"warranty":{"id":"aced38bb-6db9-4e8e-b2a9-ebc1d31b5ac5"}},"stock":{"available":1,"unit":"UNIT"},"parameters":[{"id":"229205","valuesIds":["229205_340261"]},{"id":"11323","valuesIds":["11323_1"]}],"name":"TED BAKER TOERBKA CZARNA Z KOKARDĄ DAMSKA  1ŻGA","payments":{"invoice":"VAT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":150.99,"currency":"PLN"}},"location":{"city":"Skawina","countryCode":"PL","postCode":"32-050","province":"MALOPOLSKIE"},"images":["https://images.stocksell.io/images/2c/2c2bf782-0089-434e-add6-60513baeeb98","https://images.stocksell.io/images/13/130da063-676c-4e31-8d9e-cee83a8af509","https://images.stocksell.io/images/6f/6f97b41a-674f-4116-9b28-e1295f58c9df"],"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003ch2\u003eTED BAKER TOERBKA CZARNA Z KOKARDĄ DAMSKA\u003c/h2\u003e"}]},{"items":[{"type":"IMAGE","url":"https://images.stocksell.io/images/2c/2c2bf782-0089-434e-add6-60513baeeb98"},{"type":"TEXT","content":"\u003ch2\u003eOpis Produktu\u003c/h2\u003e\u003cul\u003e\u003cli\u003e\u003cb\u003eMarka\u003c/b\u003e Ted Baker\u003c/li\u003e\u003cli\u003e\u003cb\u003eKolor\u003c/b\u003e czarny\u003c/li\u003e\u003cli\u003e\u003cb\u003eSkład\u003c/b\u003e 100% polichlorek winylu\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka papierowa\u003c/b\u003e Brak\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka wewnętrzna\u003c/b\u003e \tTak\u003c/li\u003e\u003cli\u003e\u003cb\u003eRozmiar uniwersalny\u003c/b\u003e\u003c/li\u003e\u003cli\u003e\u003cb\u003eStan przedmiotu\u003c/b\u003e Smugi różnej wielkości na materiale.\u003c/li\u003e\u003cli\u003e\u003cb\u003eCena katalogowa\u003c/b\u003e 183,99 zł\u003c/li\u003e\u003c/ul\u003e"}]},{"items":[{"type":"IMAGE","url":"https://images.stocksell.io/images/13/130da063-676c-4e31-8d9e-cee83a8af509"},{"type":"IMAGE","url":"https://images.stocksell.io/images/6f/6f97b41a-674f-4116-9b28-e1295f58c9df"}]}]},"external":{"id":"stocksell_886243578"},"taxSettings":{"rates":[{"countryCode":"PL"}]}} exception=Niepoprawna odpowiedź z Allegro. Kod: 422. Błąd: offerCounter Nie wystawisz kolejnej oferty z tym produktem. W tej kategorii możesz przyłączyć max 5 ofert do jednego produktu. Znajdź inny produkt w Katalogu lub dodaj nowy. You will not create another offer with this product. In this category, you can attach a maximum of 5 offers to one product. Find another product in the Catalog or add a new one. . Trace-id=[df75144aada46134].

**Comment by PiotrPiotrP** [comment]
Już nie ważne

**Comment by MaciejFrackowiak** [comment]
Nasz mechanizm rozpoznaje produkty i oferty na podstawie EAN oraz pozostałych parametrów produktowych, dlatego wykryliśmy, że na Twoich kontach przekroczyłeś już limit 5 ofert przypisanych do poszczególnych produktów.
I tak dla:
- trace-id=d1579391f9650bee - znaleziony produkt ma id=6d725ccc-a9f9-4774-9739-6c2b89e67963
- trace-id=df75144aada46134 - i tu również ten sam produkt z id=6d725ccc-a9f9-4774-9739-6c2b89e67963
