### ISSUE TITLE
Wystawianie ofert

### ISSUE THREAD

**Issue by PiotrPiotrP** [allegro/allegro-api#8399]
Dostaje taki błąd:

POST   https://api.allegro.pl/sale/product-offers/ requestBody={"productSet":[{"quantity":{"value":1},"product":{"name":"KAREN MILLEN SUKIENKA FIOLETOWA KOKTAJLOWA 36 Y1A","idType":"GTIN","parameters":[{"id":"201017","valuesIds":["201017_2377"]},{"id":"3786","valuesIds":["3786_33"]},{"id":"15851","valuesIds":["15851_1"]},{"id":"18160","valuesIds":["18160_2"]},{"id":"127662","valuesIds":["127662_3"]},{"id":"202477","valuesIds":["202477_2"]},{"id":"3766","valuesIds":["3766_1"]},{"id":"4126","valuesIds":["4126_2"]},{"id":"201025","valuesIds":["201025_2509"]},{"id":"54","valuesIds":["3806_3"]},{"id":"59","valuesIds":["59_2433"]},{"id":"216925","valuesIds":["216925_1191143"]},{"id":"127468","valuesIds":["127468_4"]},{"id":"249512","valuesIds":["249512_1647423"]},{"id":"127488","valuesIds":["127488_2"]},{"id":"201089","values":["1"]}],"category":{"id":"124264"},"images":["https://images.stocksell.io/images/0d/0d3246be-bc7a-4cc1-8c97-1f784020a54c","https://images.stocksell.io/images/2d/2d8d015b-59a7-45c6-8796-533276bad52c","https://images.stocksell.io/images/57/57461692-fe20-4886-b2ec-548bcec67032"]}}],"category":{"id":"124264"},"delivery":{"shippingRates":{"id":"92cb3f82-ae74-4d10-8804-2d9a444c4d55"},"handlingTime":"PT24H"},"publication":{"startingAt":"2024-02-02T17:54:16.000Z","republish":false},"language":"pl-PL","afterSalesServices":{"impliedWarranty":{"id":"3de10450-def9-43dd-8c04-408fa5115f8a"},"returnPolicy":{"id":"10bbd9d6-a61a-421b-aafd-e2289c330400"},"warranty":{"id":"aced38bb-6db9-4e8e-b2a9-ebc1d31b5ac5"}},"stock":{"available":1,"unit":"UNIT"},"parameters":[{"id":"11323","valuesIds":["11323_1"]}],"name":"KAREN MILLEN SUKIENKA FIOLETOWA KOKTAJLOWA 36 Y1A","payments":{"invoice":"VAT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":414.99,"currency":"PLN"}},"location":{"city":"Skawina","countryCode":"PL","postCode":"32-050","province":"MALOPOLSKIE"},"images":["https://images.stocksell.io/images/0d/0d3246be-bc7a-4cc1-8c97-1f784020a54c","https://images.stocksell.io/images/2d/2d8d015b-59a7-45c6-8796-533276bad52c","https://images.stocksell.io/images/57/57461692-fe20-4886-b2ec-548bcec67032"],"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003ch2\u003eKAREN MILLEN SUKIENKA FIOLETOWA KOKTAJLOWA\u003c/h2\u003e"}]},{"items":[{"type":"IMAGE","url":"https://images.stocksell.io/images/0d/0d3246be-bc7a-4cc1-8c97-1f784020a54c"},{"type":"TEXT","content":"\u003ch2\u003eOpis Produktu\u003c/h2\u003e\u003cul\u003e\u003cli\u003e\u003cb\u003eMarka\u003c/b\u003e Karen Millen\u003c/li\u003e\u003cli\u003e\u003cb\u003eKolor\u003c/b\u003e Fioletowy \u003c/li\u003e\u003cli\u003e\u003cb\u003eSkład\u003c/b\u003e 90%poliester,10%elastan\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka papierowa\u003c/b\u003e Tak\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka wewnętrzna\u003c/b\u003e \tTak\u003c/li\u003e\u003cli\u003e\u003cb\u003eRozmiar\u003c/b\u003e 36\u003c/li\u003e\u003cli\u003e\u003cb\u003eCena katalogowa\u003c/b\u003e 920,99 zł\u003c/li\u003e\u003c/ul\u003e"}]},{"items":[{"type":"IMAGE","url":"https://images.stocksell.io/images/2d/2d8d015b-59a7-45c6-8796-533276bad52c"},{"type":"IMAGE","url":"https://images.stocksell.io/images/57/57461692-fe20-4886-b2ec-548bcec67032"}]}]},"external":{"id":"stocksell_638857674"},"taxSettings":{"rates":[{"countryCode":"PL"}]}} exception=Niepoprawna odpowiedź z Allegro. Kod: 422. Błąd: ConstraintViolationException.DependencyValidator Parametr zależny Odcień (249513) nie może przyjąć wartości [granatowy], gdy parametr Kolor (249512) ma wartości [fioletowy]. Dependent parameter Odcień (249513) cannot take values [granatowy] when parameter Kolor (249512) has values [fioletowy] ConstraintViolationException.DependencyValidator parameters. Trace-id=[dfebf40af5010555].

a parameter 249513 nie był wysłany, skąd się bierze taki problem i jak go rozwiązać?

**Comment by MartaNowaczyk** [comment]
Na podstawie przesłanych danych rozpoznaliśmy produkt w naszej bazie produktowej `4b6fd9cf-1b2c-463e-8459-2bc903133600`. W danych tego produktu zapisana jest wartość dla parametru "Odcień" jako "granatowy". Tego parametru nie przekazujesz, a podajesz "Kolor" jako "fioletowy". "Odcień" jest parametrem zależnym, który może przyjąć tylko określone wartości. W tej sytuacji powinieneś zmienić wartość parametru "Kolor" na "niebieski" lub nie przekazywać go w ogóle. 
Jeśli masz zastrzeżenia co do danych produktu, z którym chcemy połączyć ofertę, możesz [zgłosić sugestię zmiany w produkcie](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-zglosic-blad-w-produkcie).

**Comment by MartaNowaczyk** [comment]
Na podstawie danych jak parametry i zdjęcia znaleźliśmy duplikat. W tym produkcie jest takie samo zdjęcie jak w requeście (sukienka w kolorze fioletowym) + pasujące parametry. Wszelkie sprawy dotyczące identyfikacji produktów są poza API, także jeśli chcesz poznać szczegóły skontaktuj się przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619).
