### ISSUE TITLE
REST API /sales/offer-contacts/ zwraca błąd

### ISSUE THREAD

**Issue by painter10** [allegro/allegro-api#84]
Przy wywołaniu metody /sales/offer-contacts/?seller.id={seller_id} otrzymuję wiadomość zwrotną:
`
{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":null,"userMessage":null}]}`

Metodę wywołuję następująco:
`curl -X GET -H 'authorization: Bearer eyJh.........Kg' -H 'api-key: eee........eeee' -H 'Accept: application/vnd.allegro.public.v1+json' 'https://api.allegro.pl/sale/offer-contacts/?seller.id=11111'`

**Comment by KrzysztofLukanowski** [comment]
Czy token, którym się autoryzujesz, dot. konta, w sprawie którego wysyłasz zapytanie? Czy na tym koncie na pewno są kontakty? Upewnij się proszę, że podałeś prawidłowy seller.id.

**Comment by painter10** [comment]
Seller.id jest prawidłowy, pobierany przez webApi metodą doGetItemsInfo.
Natomiast token jest powiązany z innym kontem, niż Seller.Id podany w zapytaniu.

**Comment by KrzysztofLukanowski** [comment]
Kontakty możesz pobrać jedynie dla uwierzytelnionego użytkownika, więc w tym przypadku Seller.Id nie jest poprawny.
