### ISSUE TITLE
Problem z wystawianiem oferty na istniejący produkt

### ISSUE THREAD

**Issue by grzegorz-krupkowski** [allegro/allegro-api#8400]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [ x] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**

Podany request  sprawdzający czy produkt istnieje:
/sale/products?phrase=5901721606319&mode=GTIN&category.id=75996

daje mi taki response:
{"products":[],"categories":{"subcategories":[{"id":"75996","name":"Body","count":0}],"path":[{"id":"954b95b6-43cf-4104-8354-dea4d9b10ddf","name":"Allegro"},{"id":"ea5b98dd-4b6f-4bd0-8c80-22c2629132d0","name":"Moda"},{"id":"1454","name":"Odzież, Obuwie, Dodatki"},{"id":"75993","name":"Bielizna damska"},{"id":"75996","name":"Body"}]},"filters":[_tu wylistowane wszystkie marki_],"minValue":null,"maxValue":null,"unit":null}],"nextPage":null}

Tabela produktow pusta, wobec czego nalezy podejrzewac, że produkt nie istnieje w danej kategorii. Próba załozenia go powoduje jednak zwracany błąd: Matching product not found for the specified ID.

Jak towar sprobuje znaleźć przez interfejs to okazuje się że jednak istnieje:
https://allegro.pl/kategoria/bielizna-damska-body-75996?string=5901721606319

Dlaczego w takim razie nie jest zwracany w metodzie /sale/products ?
Proszę o pomoc, mam co najmniej kilka/kilkanaście takich przypadków w dniu dzisiejszym.

**Comment by MartaNowaczyk** [comment]
Z tego co piszesz wynika, że próbowałeś wystawić ofertę z produktem o EANie 5901721606319. Czyli pewnie podstawiłeś pod product.id te EAN, a jako "idType" dałeś GTIN. W tym momencie dostaniesz błąd, bo taki produkt nie istnieje, co zresztą zauważyłeś przy wyszukiwaniu produktu po tym GTINie. [Zgodnie z komunikatem](https://developer.allegro.pl/news/wprowadzilismy-limit-produktow-ktore-sprzedajacy-moga-dodac-do-katalogu-w-ciagu-miesiaca-oraz-uruchomilismy-dodatkowa-walidacje-przy-wystawianiu-ofert-8dv6kygn2fk), aby utworzyć produkt nie możesz podawać product.id, tylko powinieneś pozostawić pole product.id puste i podać pozostałe dane, czyli tutaj GTIN dodasz jako parametr produktu w polu product.parameters. 
Jeśli chodzi o wyszukiwarkę, to nie powinieneś się nią sugerować, bo nie wyszukuje ona produktów, tylko oferty.

**Comment by grzegorz-krupkowski** [comment]
OK, faktycznie po tym jak nie przekazuje eanu w Product.Id mam komunikat ze nie podany został rozmiar. Ale ogólnie wszystko to u nas działa od x czasu i wydaje mi sie z tym eanem tez towary przechodzily nawet jak nie byly w katalogu.
Tak czy inaczej z mojej strony jest już OK.
