### ISSUE TITLE
Brak synchronizacji ilości sztuk w ofertach z programu ideaERP

### ISSUE THREAD

**Issue by kamilkomtek** [allegro/allegro-api#8401]
API wysyła poprawny komunikat, nie zwraca błędów - pomimo to ilości się nie zmieniają.

**Comment by kamilkomtek** [comment]
Odnośnie zamykania aukcji - wskazana aukcja 13125125795 nie jest zamykana przez system IDEAerp. W dniu wczorajszym przesłaliśmy do Allegro informację o zmianie stocku produktu dla aukcji, w zwrotce z Allegro otrzymaliśmy informację, iż zmiana statusu nie została przez nas przesłana (state":"NOT_REQUESTED" a sama aukcja pozostaje w statusie aktywna "status":"ACTIVE". Poniżej dodaję zwrotkę otrzymaną od Allegro dla wskazanej aukcji. {"allegro-cz":{"sellingMode":{"price":{"amount":"255.00","currency":"CZK"}},"publication":{"state":"NOT_REQUESTED","refusalReasons":[]}}},"id":"13125125795","language":"pl-PL","publication":{"status":"ACTIVE","duration":null,"endedBy":null,"endingAt":null,"startingAt":null,"republish":false,"marketplaces":{"base":{"id":"allegro-pl"},"additional":[]}},"validation":{"errors":[],"warnings":[],"validatedAt":"2024-01-23T11:12:31.189Z"},"createdAt":"2023-01-11T10:24:07.000Z","updatedAt":"2024-01-30T13:39:28.465Z"}
Proszę o kontakt bezpośrednio z Allegro w celu wyjaśnienia dlaczego dana aukcja jest zamykana mimo braku wysyłki informacji o zmianie statusu.

W sprawie wysyłki stanów dla wskazanej aukcji Allegro - przesłaliśmy request {"stock":{"available":85},"publication":{"status":"ACTIVE"},"delivery":{}}
na URL https://api.allegro.pl/sale/product-offers/13178573238

response body allegro: {"name":"PRZENOŚNY CICHY INHALATOR SIATECZKOWY NEBULIZATOR DLA DZIECI I DOROSŁYCH","productSet":[{"product":{"id":"1a17506c-261b-49a3-bd4d-0587341d032a","publication":{"status":"LISTED"},"parameters":[{"id":"225693","name":"EAN (GTIN)","values":["5901299954782"],"valuesIds":null,"rangeValue":null},{"id":"224017","name":"Kod producenta","values":["ECN005"],"valuesIds":null,"rangeValue":null},{"id":"209158","name":"Marka","values":["Esperanza"],"valuesIds":["209158_238126"],"rangeValue":null},{"id":"237206","name":"Model","values":["ECN005"],"valuesIds":null,"rangeValue":null},{"id":"205826","name":"Kolor dominujący","values":["biały"],"valuesIds":["205826_225038"],"rangeValue":null},{"id":"212422","name":"Rodzaj","values":["kieszonkowe","membranowe","nebulizator","ultradźwiękowe"],"valuesIds":["212422_1026479","212422_1026480","212422_8","212422_1026482"],"rangeValue":null},{"id":"209566","name":"Zasilanie","values":["bateryjne","USB"],"valuesIds":["209566_2","209566_1769032"],"rangeValue":null},{"id":"249829","name":"Wyrób medyczny","values":["tak"],"valuesIds":["249829_1765554"],"rangeValue":null},{"id":"209618","name":"Skład zestawu","values":["maska dla dorosłych","maska dla dzieci","nebulizator (rozpylacz)","przewód powietrza","torba transportowa"],"valuesIds":["209618_2","209618_1","209618_16","209618_512","209618_64"],"rangeValue":null},{"id":"212458","name":"Tryb pracy","values":["ciągły"],"valuesIds":["212458_254250"],"rangeValue":null},{"id":"209530","name":"Szybkość inhalacji","values":["0.2"],"valuesIds":null,"rangeValue":null},{"id":"209522","name":"Średnia wielkość cząsteczek MMAD","values":["4"],"valuesIds":null,"rangeValue":null},{"id":"209610","name":"Pojemność zbiornika na lek","values":["6"],"valuesIds":null,"rangeValue":null},{"id":"628","name":"Poziom hałasu","values":["20"],"valuesIds":null,"rangeValue":null},{"id":"212470","name":"Moc","values":["2"],"valuesIds":null,"rangeValue":null},{"id":"223333","name":"Szerokość produktu","values":["5.5"],"valuesIds":null,"rangeValue":null},{"id":"223329","name":"Wysokość produktu","values":["16"],"valuesIds":null,"rangeValue":null},{"id":"201321","name":"Głębokość produktu","values":["5.5"],"valuesIds":null,"rangeValue":null},{"id":"211574","name":"Waga produktu","values":["378"],"valuesIds":null,"rangeValue":null},{"id":"17448","name":"Waga produktu z opakowaniem jednostkowym","values":["0.5"],"valuesIds":null,"rangeValue":null}]},"quantity":{"value":1}},{"product":{"id":"abd812d8-decb-4f43-bd43-4fb03ae1e726","publication":{"status":"LISTED"},"parameters":[]},"quantity":{"value":1}}],"parameters":[{"id":"11323","name":"Stan","values":["Nowy"],"valuesIds":["11323_1"],"rangeValue":null},{"id":"229205","name":"Stan opakowania","values":["oryginalne"],"valuesIds":["229205_340245"],"rangeValue":null},{"id":"249946","name":"Typ wyrobu medycznego","values":["wyrób medyczny lub wyrób medyczny do diagnostyki in-vitro"],"valuesIds":["249946_1785985"],"rangeValue":null},{"id":"249945","name":"Producent wyrobu medycznego","values":["Esperanza"],"valuesIds":null,"rangeValue":null}],"images":["https://a.allegroimg.com/original/116791/0b0784c541a183e93c8b40fb3784","https://a.allegroimg.com/original/117e6f/31a3aeee4b31a7f9eb07915ff0dc","https://a.allegroimg.com/original/11c06d/712c54244aa2a6b3c61e79efcd1c","https://a.allegroimg.com/original/110a71/070943b0402bb62713c245b103be","https://a.allegroimg.com/original/1150be/abc975c041beb70ec8cf84fc91bf","https://a.allegroimg.com/original/112874/af546901485b884230dabf6a3b9e","https://a.allegroimg.com/original/1173dd/cf593f0e4537b81a523cbd8af601","https://a.allegroimg.com/original/11e214/eb7f97de44429a43d48d6fee6a8b","https://a.allegroimg.com/original/118f2d/290328154ebd8acb84dd6ffde54e","https://a.allegroimg.com/original/11f4c5/9fc92f4e4f4491da4c97e15be8d4","https://a.allegroimg.com/original/11291f/cec0942543e2be55474ce22843af"],"afterSalesServices":{"impliedWarranty":{"id":"26661763-ba3f-40c2-9d05-bb3eab78c7fa"},"returnPolicy":{"id":"1988c29f-6f38-44aa-a632-a56f2b1eac7e"},"warranty":{"id":"c796b67f-53b3-41eb-9c86-35d7c495431e"}},"payments":{"invoice":"VAT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":"79.99","currency":"PLN"},"startingPrice":null,"minimalPrice":null},"stock":{"available":85,"unit":"UNIT"},"location":{"countryCode":"PL","province":"MALOPOLSKIE","city":"Kraków","postCode":"30-820"},"delivery":{"shippingRates":{"id":"f0b1fd36-1659-4e28-a57a-16040235f858"},"handlingTime":"PT0S","additionalInfo":null,"shipmentDate":null},"description":{"sections":[{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11291f/cec0942543e2be55474ce22843af"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/116791/0b0784c541a183e93c8b40fb3784"},{"type":"TEXT","content":"<h2>✅ NIEWIELKI, CICHY A ZARAZEM SKUTECZNY!</h2>\n<p><b>✔</b> Nebulizator membranowy tworzy aerozol korzystając <b>z nowej technologii membranowej</b></p>\n<p><b>✔</b> Dzięki bezgłośnej pracy <b>użyjesz tego urządzenia bardzo dyskretnie</b>, a jego <b>niewielki rozmiar</b> pozwoli zmieścić je bez trudu w torebce lub aktówce</p>\n<p><b>✔</b> Urządzenie zapewnia<b> długi czas działa</b> - na jednym zestawie baterii <b>może pracować nawet do 4 godzin</b></p>\n<p><b>✔ </b>Tworzy odpowiedniej wielkości cząsteczki aerozolu, <b>niezbędne do prawidłowej inhalacji</b></p>\n<p></p>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11e214/eb7f97de44429a43d48d6fee6a8b"},{"type":"TEXT","content":"<h2>✅ W zestawie 5 x roztwór soli fizjologicznej 0.9% NaCl 5ml</h2><h2>✅ Zestaw z większą liczbą ampułek znajdziesz nad opisem!</h2>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11f4c5/9fc92f4e4f4491da4c97e15be8d4"},{"type":"TEXT","content":"<h2>Specyfikacja</h2><ul><li>Zasilanie: 2 baterie alkaliczne AA 1,5 V (nie znajdują się w zestawie) / zasilanie przez przewód USB (załączony)</li><li>Pobór mocy: ok. 1,5-2 W</li><li>Częstotliwość ultradźwięków:  103 kHz~123 kHz</li><li>Pobór prądu w trybie czuwania: < 0,1 mA</li><li>Pobór prądu podczas pracy: < 500 mA</li><li>Pojemność leku: <b>6 ml</b></li><li>Średnia prędkość nebulizacji:  <b>≥ 0,2 ml/min</b></li><li>Wielkość cząstek (MMAD)<b>: od 3 do 5 μm</b></li><li>Wydajność aerozolu: 0,087 ml/min</li><li><b>Poziom hałasu: ≤ 21 dB</b></li><li>Automatyczne wyłączenie: brak leku / po 20 minutach ciągłej pracy</li><li>Zakres temperatury pracy: 10°C ~ 40°C</li><li>Zakres wilgotności podczas pracy: wilgotność względna 10% ~ 95%</li><li>Zakres temperatury przechowywania: -20°C ~ 50°C</li><li>Wielkość urządzenia: 6.0 * 5.5 * 13.0 [cm]</li></ul>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11c06d/712c54244aa2a6b3c61e79efcd1c"},{"type":"TEXT","content":"<h2>W zestawie:</h2><ul><li>jednostka główna</li><li>element nebulizacyjny</li><li>maska dla dorosłego</li><li>maska dla dziecka</li><li>ustnik</li><li>pokrowiec</li><li>przewód USB DC 5 V</li><li>zatyczka gumowa</li><li>instrukcja w j. polskim</li><li>roztwór soli fizjologicznej 5ml</li></ul>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/1173dd/cf593f0e4537b81a523cbd8af601"},{"type":"TEXT","content":"<p>✅ W celu poprawnej inhalacji należy<b> wlać lek w górnej części inhalatora</b> (głowicy).</p><p>Aby prawidłowo zachować parametry pracy należy <b>czyścić siateczkę po inhalacji.</b></p><p>Nebulizator można używać do podawania wszystkich leków przeznaczonych do nebulizacji:</p><ul><li><b>roztworów</b> (np. Berodual, Mucosolvan, Ventolin)</li><li><b>zawiesin </b>(np. Benodil, Flixotide , Nebbud, Pulmicort)</li><li><b>wodnych roztworów chlorku sodu (</b>sól fizjologiczna o stężeniu 0,9% i sól hipertoniczna o stężeniu 3)</li></ul><p><b>✅ Do inhalacji sterydów oraz antybiotyków</b> polecamy inhalator flaem z naszej oferty (13214119188)</p><p>Produkt posiada:</p><ul><li>oznaczenie CE 93/42/EEC dla urządzeń medycznych</li><li>oznakowania w języku polskim</li><li>instrukcję obsługi w j.polskim</li><li>informację o deklaracji zgodności UE</li></ul>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/112874/af546901485b884230dabf6a3b9e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/110a71/070943b0402bb62713c245b103be"}]}]},"external":{"id":"027101"},"category":{"id":"258791"},"tax":{"percentage":"8.00","rate":"8.00","subject":"GOODS","exemption":null,"id":"d17ae618-fa02-48fc-830a-b2829eb44f00"},"taxSettings":{"subject":"GOODS","exemption":null,"rates":[{"rate":"8.00","countryCode":"PL"},{"rate":"21.00","countryCode":"CZ"}]},"sizeTable":null,"discounts":{"wholesalePriceList":null},"contact":null,"fundraisingCampaign":null,"messageToSellerSettings":null,"attachments":[],"b2b":null,"additionalServices":null,"compatibilityList":null,"additionalMarketplaces":{"allegro-cz":{"sellingMode":{"price":{"amount":"453.00","currency":"CZK"}},"publication":{"state":"PENDING","refusalReasons":[]}}},"id":"13178573238","language":"pl-PL","publication":{"status":"ACTIVE","duration":null,"endedBy":null,"endingAt":null,"startingAt":null,"republish":false,"marketplaces":{"base":{"id":"allegro-pl"},"additional":[{"id":"allegro-cz"}]}},"validation":{"errors":[],"warnings":[],"validatedAt":"2023-12-27T11:16:45.978Z"},"createdAt":"2023-01-25T09:33:41.000Z","updatedAt":"2024-01-11T10:32:14.321Z"}

response status code 200 = true

W tym przypadku również proszę o kontakt z Allegro. Jeśli Allegro będzie w stanie wykazać w którym momencie aukcja została zamknięta, oraz dlaczego zadeklarowana ilość nie została zmieniona to prosiłbym o zwrot zadania - na ten moment nie jestem w stanie zlokalizować błędu.

**Comment by MaciejFrackowiak** [comment]
W opisanej sytuacji najlepszym rozwiązaniem będzie, gdy integrator skontaktuje się z nami, ponieważ wklejanie requestów bez szczegółów tj. trace-id nie pozwala nam na odnalezienie tych wywołań.

**Comment by MaciejFrackowiak** [comment]
Dlatego tak kluczowe jest, abyśmy mogli z integratorem wymienić logi, stąd niezbędny jest jego kontakt z nami.

**Comment by kamilkomtek** [comment]
Panie Kamilu
Logi przechowujemy 5 dni, po tym czasie eksport jest usuwany. Nie prześlę Panu traceID dla wskazanego przykładu, przesyłam natomiast logi i traceID do przykładu wskazanego przez Pana Piotra-
dla aukcji 13564800296 wysyłamy następujący request: {"stock":{"available":64},"publication":{"status":"ACTIVE"},"delivery":{}}
na url https://api.allegro.pl/sale/product-offers/13564800296
"Trace-Id":"9a1fd490e606914f"
Proszę o przesłanie trace ID do obsługi Allegro i zwrot zadania w przypadku otrzymania odpowiedzi - po weryfikacji Allegro będziemy w stanie dalej weryfikować dany przypadek.

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem podany trace-id=9a1fd490e606914f - stock w ofercie został prawidłowo zmieniony na wskazane 64 sztuki.

**Comment by kamilkomtek** [comment]
Czy można podać z jaką datą było wykonane zapytanie API i odpowiedź?

**Comment by MaciejFrackowiak** [comment]
Proszę bardzo - 2024-02-05 14:55:12.

**Comment by kamilkomtek** [comment]
Pytanie do integratora
Dlaczego zgłoszony błąd 02.02.2024 - a podsyła logi z 05.02.2024?

**Comment by MaciejFrackowiak** [comment]
Taki trace-id otrzymałem od Ciebie w poście z 5 lutego 2024, 5:16PM - zatem po zweryfikowaniu danych oddałem tylko właściwą datę, która odpowiada podanemu trace-id.
