### ISSUE TITLE
Wysyłam z Allegro retry-after

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#8402]
Zmieniam integrację na nowe metody przeznaczone do tworzenia paczek w Wysyłam z Allegro na środowisku testowym.
Zachowanie endpointu 
https://api.{environment}/shipment-management/shipments/create-commands jest nieprawidłowe

Odpytując endpoint o status utworzenia przesyłki za każdym razem otrzymuję w nagłówku retry-after o wartości 5, pomimo tego że w treści zwrotki mam: {"commandId":"d0b29d9a-de93-440b-8572-e9b488bedf2a","status":"SUCCESS","errors":null,"shipmentId":"40a202aa-364b-46ff-9949-c70a559d0691"}.

Przykładowe traceID: "72143d7e0eda07e".

Ten sam problem pojawia się gdy endpoint zwraca błędy utworzenia przesyłki.

**Comment by marmited** [comment]
podobną sytuację widzę w endpoincie:
shipment-management/pickups/create-commands

Nagłówek ma retry-after: 5
Zwrotka:
{"commandId":"58037aec-2274-47d5-8290-c44e1e807978","input":{"shipmentIds":["40a202aa-364b-46ff-9949-c70a559d0691"],"pickupDateProposalId":"2024020513001500"}}

**Comment by MartaNowaczyk** [comment]
Przepraszam za długie oczekiwanie na odpowiedź. Wspomniany nagłówek jest standardem komunikacji HTTP i nie wpływa  na logikę w sytuacji odpowiedzi pozytywnej - może on być przydatny przy niepowodzeniu operacji, dlatego nie jest to uznawane za błąd.
