### ISSUE TITLE
Problem z połączeniem z Allegro rest po zmianie serwera i przeniesieniu domen i zmianie serwera.

### ISSUE THREAD

**Issue by lasoczczyk** [allegro/allegro-api#8403]
Dzień dobry. 
Przenosilismy nasz sklep internetowy z KEI do HOME.
Niestety po przenosinach nie mozemy się połączyć przez CURL z pańśtwa API.

Czy mogli by państwo zerknąć czy z jakichś powodów wyrzuca nam bład z kodem 400? Próbowałem się łączyc okolo godziny 22 i pozniej (dzis) 4 lutego. 
Nie mozemy otrzymać nawet tokena.

Czy sa jakieś specjalne ustawienia, zwiazane z certyfikatami, domenami lub ustawieniami CURL czy TSL które powinienem sprawdizc na nowym serwerze?

Łączymy się z domeny nagaz24.pl
Uzytkownik: www_nagaz24_pl
ID: ecafb52692784a9a9a00a5ec009a65b3

Prosimy o pilną pomoc - nie mozemy obsługiwać zamowien w naszym systemie.

Mogę załaczyc nasze PHPINFO.

**Comment by AureliuszBrussy** [comment]
Jaki dokładnie response otrzymujecie? Prosiłbym pełen response, wraz z nagłówkami. Nie widzę zarejestrowanego żadnego ruchu spod tego klucza w ostatnich dniach. Abym mógł to namierzyć - potrzebuję możliwie dużo informacji.

**Comment by lasoczczyk** [comment]
Na poprzednim serwerze dzialalo wszystko ok.
Na nowym w HOmecloud:

Próbuję zalogować się przez Allegro z panelu naszego sklepu
Wysyłam ID klienta. 
https://allegro.pl/auth/oauth/authorize?&state=%2Fauth%2Flogin&response_type=code&client_id=ecafb52692784a9a9a00a5ec009a65b3&redirect_uri=https%3A%2F%2Fnagaz24.pl%2Fadmin%2Findex.php%3Fk%3Dallegro%26s%3Dallegro_connect

Otrzymuje w odpowiedzi kod po zalogowaniu w allegro.
Natomiast kiedy wysyłam otrzymany kod do https://allegro.pl/auth/oauth/
https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=cfaq89DYaB55u5SsjFCGBB3t4t2EqgMj&redirect_uri=https%3A%2F%2Fnagaz24.pl%2Fadmin%2Findex.php%3Fk%3Dallegro%26s%3Dallegro_connect

Otrzymuje w  odpowiedzi CURL kod 400.
Dodałem  curl_setopt($ch, CURLOPT_VERBOSE, true);

I w debugu zapisało mi następujące informacje:

* About to connect() to allegro.pl port 443 (#5170)
*   Trying 5.134.213.80...
* Connected to allegro.pl (5.134.213.80) port 443 (#5170)
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.allegro.pl,O=Allegro sp. z o.o.,L=Poznan,ST=wielkopolskie,C=PL
* 	start date: sie 18 00:00:00 2023 GMT
* 	expire date: wrz 10 23:59:59 2024 GMT
* 	common name: *.allegro.pl
* 	issuer: CN=DigiCert Global G2 TLS RSA SHA256 2020 CA1,O=DigiCert Inc,C=US
* Server auth using Basic with user 'ecafb52692784a9a9a00a5ec009a65b3'
> POST /auth/oauth/token?grant_type=authorization_code&code=cfaq89DYaB55u5SsjFCGBB3t4t2EqgMj&redirect_uri=https%3A%2F%2Fnagaz24.pl%2Fadmin%2Findex.php%3Fk%3Dallegro%26s%3Dallegro_connect HTTP/1.1
Authorization: Basic ZWNhZmI1MjY5Mjc4NGE5YTlhMDBhNWVjMDA5YTY1YjM6eDhoVDFETm9vWG5pZ0RHWFRsMzJnd2ZpNTIyRGhXTEpyV2NBUlRPMG9TelFYdGlVdlVQRmUxamlSbzE4TzRTUw==
Host: allegro.pl
Accept: */*
Content-Length: -1
Content-Type: application/x-www-form-urlencoded
Expect: 100-continue

< HTTP/1.1 400 Bad request
< Content-length: 90
< Cache-Control: no-cache
< Connection: close
< Content-Type: text/html
< 
* Closing connection 5170

**Comment by AureliuszBrussy** [comment]
Analizujemy to. Wrócę do Ciebie z odpowiedzią.

**Comment by lasoczczyk** [comment]
Przesyłam nasze PHPinfo w załączniku - moze cos trzeba ustawić dodatkowo -to nowo skonfigurowany serwer.
Zwykle pobranie CURL-em bez uwierzytelniania działa normalnie i moge pobierac z zewnatrznego adresu.

Probowałem załozyc nową aplikację ale ten sam efekt - na sandbox również to samo...

[PHP 7.4.33 - phpinfo().pdf](https://github.com/allegro/allegro-api/files/14167720/PHP.7.4.33.-.phpinfo.pdf)

Proszę o pomoc - dziś wszystko przeklejaliśmy ręcznie...

**Comment by lasoczczyk** [comment]
OK wywaliłem wszystko, podejrzewam ze błąd tkwi w innym kodowaniu dziwnych znaczków i spacji w adresie URL na nowym serwerze.

Przekleiłem nowy przykład PHP ze strony:
https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#autoryzacja-uzytkownika

Podstawiłem moje dane.
Uruchomiłem.
Jest chyba lepiej Bo otrzymałem jakiekiolwiek informacje zamiast kodu 400:
Trace ID: 2574913826d9bc19

I błąd: Authorization header does not contain space after 'Bearer'.
Mogę prosic o zerknięce?

**Comment by lasoczczyk** [comment]
Niestety ten blad 401 występuje  juz na etapie pobrania tokena po wysłaniu kodu.
W waszym przykładzie widzę ze funkcja łączy się z https://allegro.pl/auth/oauth/token
Tam nie jest wysyłane nic w nagłowku narazie i wlasnie mnie dziwi ten bład :)

**Comment by AureliuszBrussy** [comment]
Generując access_token powinieneś wysłać nagółwek:

` -H 'Authorization: Basic YTI...Hg=' `

Autoryzacja typu Basic, z zawartością w formie client_id:client_secret (dane otrzymane przy rejestracji aplikacji) w postaci Base64. Pamiętaj aby zakodować całość danych client_id:client_secret wraz ze znakiem “:” pomiędzy wartościami (`Basic base64(clientId:secret)`).

**Comment by lasoczczyk** [comment]
Dodałem:

` curl_setopt_array($ch, array(
        CURLOPT_URL => TOKEN_URL,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => $content,
        CURLOPT_VERBOSE=> true,
        CURLOPT_STDERR=> $verbose,  
        CURLOPT_HTTPHEADER=>array("Authorization: Basic ".base64_encode(CLIENT_ID.':'.CLIENT_SECRET)),
     //   CURLOPT_USERNAME =>CLIENT_ID,
     //   CURLOPT_PASSWORD => CLIENT_SECRET
    ));`

Ale dalej zwraca mi 401.
Ale tym razem odpowiedź jest inna. podsyłam zrzut z godziny 14:12

[CURLOPT_VERBOSE.txt](https://github.com/allegro/allegro-api/files/14180075/CURLOPT_VERBOSE.txt)

Małymi kroczkami i w końcu zadziała....

**Comment by AureliuszBrussy** [comment]
Czy na pewno nie wykorzystujesz tego samego kodu autoryzacyjnego? Widzimy próby użycie tego samego kodu w dużych odstępach czasu - samo kod jest jednorazowego użytku oraz jest ważny przez 10 sekund.

**Comment by lasoczczyk** [comment]
Tak tak mozliwe ze cos kilka razy odświeżyłem ale przypadkiem, robiłem sporoo prób z roznymi kodami.
Dzis zrobiłem tylko jedną próbę o 8:19 i w tej pojedynczej próbie mam 401 
Zerknijcie proszę - pewnie jakaś pierdółka a u nas masakra - wszystko ręcznie robimy od powniedziałku.... :(

CURL_VERBOSE: [allegro.txt](https://github.com/allegro/allegro-api/files/14190353/allegro.txt)

P.S.
I zastanawia mnie jak zmiana serwera mogła mieć wpływ na działający do tej pory kompletny system połączenia....
A moze podeślę dwa php info - nowego i starego serwera i ktoś coś zauważy?

**Comment by AureliuszBrussy** [comment]
Czy mógłbyś wysłać krok po kroku sekwencyjnie wszystkie operacje, które wykonujesz w ramach uwierzytelniania, najlepiej w formie curl z timestampami? Chodzi o:

1. Wygenerowanie authorization code.
2. Próba użycia tego authorization code w ramach generowania access tokena - tak, abym widział wszystkie użyte query parametry. 

Niestety, wciąż nie udało nam się namierzyć powodu tego problemu.

**Comment by lasoczczyk** [comment]
Właśnie na coś wpadłem, przypadkiem zauważyłem ze mamy na serwerze godzine wstecz - pokazuje 7 zamiast 8.
Przestawiłem na GMT+1 ale nie zadziałało :) Napisałem do adminów.
Jak nam to przestawią spróbuje ponownie i odezwę się.

Czy to moze byc przyczyna braku autoryzacji?

**Comment by AureliuszBrussy** [comment]
@lasoczczyk nie sądzę, aby to miało wpływ na problem z autoryzacją.

**Comment by AureliuszBrussy** [comment]
Najlepiej, jeżeli wyślesz te dane przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). W zgłoszeniu podkreśl, że chodzi o zgłoszenie z GitHuba: #8403.

**Comment by lasoczczyk** [comment]
Niestety nie można wysłac przez formularz wiadomosci ani zalaczników. W sprawie Allegro API tylko kierują tutaj.] na GitHub

Wklejam informacje i 2 pliki. Prosże najwyzej usunąć newralgiczne dane po zapisaniu. A ja dodatkowo wygeneruje sobie nowe klucze pozniej jak zacznie dzialac.

W załaczniku kod "autoryzacja.php.txt" ktory skopiowałem z pomocy i wstawiłem swoje dane.
[autoryzacja.php.txt](https://github.com/allegro/allegro-api/files/14193727/autoryzacja.php.txt)

Kod w pierwszym etapie na podstawie id i secret generuje mi poniższy link:

https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=ecafb52692784a9a9a00a5ec009a65b3&redirect_uri=https%3A%2F%2Fnagaz24.pl%2Fadmin%2Findex.php%3Fk%3Dallegro%26s%3Dallegro_connect&code_challenge_method=S256&code_challenge=I6DwmMsr81CF54jn9MQ5uBhAtTJ2JH6Ypr-73kBZaVo

13:03 klikam w ten link

13:04 loguję się na www_nagaz24_pl

13:05 dostaję odpowiedz z kodem: EULUljqjl8Q87w2xd58vxkiOWpQB5lcV

Tworzę zlepek: 
ID dwukropka i Secret i robię z niego skrót base64
ecafb52692784a9a9a00a5ec009a65b3:x8hT1DNooXnigDGXTl32gwfi522DhWLJrWcARTO0oSzQXtiUvUPFe1jiRo18O4SS
Czyli: 
ZWNhZmI1MjY5Mjc4NGE5YTlhMDBhNWVjMDA5YTY1YjM6eDhoVDFETm9vWG5pZ0RHWFRsMzJnd2ZpNTIyRGhXTEpyV2NBUlRPMG9TelFYdGlVdlVQRmUxamlSbzE4TzRTUw==

Potem wysyłam:
grant_type=authorization_code&code=EULUljqjl8Q87w2xd58vxkiOWpQB5lcV&redirect_uri=https%3A%2F%2Fnagaz24.pl%2Fadmin%2Findex.php%3Fk%3Dallegro%26s%3Dallegro_connect&code_verifier=".$code_verifier
przez CURL z nagłówkiem: ("Authorization: Basic *****"))  w miejscu gwiazdek wstawiam powyższy zlepek base64

Curl zwraca 
Something went wrong 401 {"error":"Unauthorized","error_description":"Unauthorized"}
Szczegóły w pliku "curl_verbose.txt"
[curl_verbose.txt](https://github.com/allegro/allegro-api/files/14193730/curl_verbose.txt)

**Comment by AureliuszBrussy** [comment]
Sprawdzamy to. Wrócę z odpowiedzią.

**Comment by lasoczczyk** [comment]
Juz sobie poradziłem. 
Wywaliłem code_challenge i zaczelo dzialac. 
Panel jest i tak zablkowany na jedno IP wiec luzik.
