### ISSUE TITLE
Wznawianie oferty 

### ISSUE THREAD

**Issue by Eryk1997** [allegro/allegro-api#8404]
Za pomocą endpointu: `/sale/offer-publication-commands` wznawiam ofertę ale nie dostaje błędu. Patrząc w panelu allegro oferta nie ma przypisanej kategorii. W jaki sposób mogę pobrać takie błędy?

**Comment by PrzemyslawLukanowski** [comment]
Nie otrzymujesz błędu ani informacji o tym, że operacja przebiegła prawidłowo, ponieważ ten zasób działa asynchronicznie. Aby poznać ostateczny rezultat, w tym ew. błędy, skorzystaj z [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#informacje-o-publikacji).

**Comment by Eryk1997** [comment]
Dobrze dziękuję
