### ISSUE TITLE
Wystawianie nowego produktu.

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#8405]
Dzień Dobry,

czy ostatnio były nanoszone jakieś zmiany na logikę wystawiania produktu? Od niedawna mamy problem - otrzymujemy błąd Matching product not found for the specified ID. Owszem przekazujemy ID oraz IdType GTIN dla nowego prudktu, i zwykle to do tej pory działało.

trace-id: 41e8d82036a21a5f

**Comment by MaciejFrackowiak** [comment]
Proszę zapoznaj się z ostatnią [zmianą](https://github.com/allegro/allegro-api/issues/8397).
