### ISSUE TITLE
Sandbox, prośba o odblokowanie konta

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#8406]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

Na sandboxie nie udaje mi się wystawic oferty: trace-id 21ce7e672f41e866.
Próbuję klikać w "Rozliczenia z Allegro" ale nie udało mi się znaleźć symulatora płatności.

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem działanie funkcjonalności - bez przeszkód dokonałem wpłaty. Wejdź proszę na [stronę](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) i wprowadź kwotę w "okienku" przy Bieżące saldo. Następnie wybierz formę płatności i postępuj zgodnie z flow.

**Comment by tomylee0** [comment]
Nie bardzo rozumiem. Mam obowiązek zapłacić za sandboxa? Flow każe płacić.

![image](https://github.com/allegro/allegro-api/assets/48419261/f673168a-bc46-4e6f-8cb2-6a7a95e2fb51)

**Comment by MaciejFrackowiak** [comment]
Tak, to jest standardowy symulator płatności na Sandbox, taki jak np. przy płatności za zakupy.

**Comment by MaciejFrackowiak** [comment]
Skorzystaj proszę z przelewu elektronicznego np. mBank i płatność rozliczy się niemal natychmiast.

**Comment by tomylee0** [comment]
Wybranie przelewu mBank zadziałalo. Dzięki za pomoc.
