### ISSUE TITLE
Skąd wziąć SELLER_ID?

### ISSUE THREAD

**Issue by Arkowsky** [allegro/allegro-api#841]
Witam serdecznie,

Pewnie banalne pytanie:
Skąd wziąć SELLER_ID do metody pobierającej shipping-rates
?
![screenshot 2018-10-30 at 10 55 33](https://user-images.githubusercontent.com/19975089/47710147-5a85e500-dc32-11e8-982b-21751b4e1579.png)

**Comment by mpysz** [comment]
#156

**Comment by mpysz** [comment]
#156
> seller.id to nic innego niż identyfikator konta użytkownika.
> 
> Jak będziesz zalogowany na docelowym koncie to wpisz adres https://allegro.pl/login/user i dostaniesz ID. To jeden z wielu sposobów.

**Comment by MartaNowaczyk** [comment]
@Arkowsky oprócz tego SELLER_ID znajdziesz w zasobach do pobierania zdarzeń [/order/events](https://developer.allegro.pl/documentation/#/order-management/get_order_events)

**Comment by Arkowsky** [comment]
Dziękuję, działa. Zamykam.

**Comment by runaway90** [comment]
@MartaNowaczyk nie mogę sprawdzić SELLER_ID, przy pobieraniu zdarzeń _/order/events_ jak nić się nie wydarzeło. Dostaję pusty response.

**Comment by PawelTaberski** [comment]
@runaway90 Nie bardzo ciebie rozumiem, czy nie korzystasz czasem w tej metodzie z tokena uzyskanego przy pomocy autoryzacji client credentials? Jeśli nie to jak wygląda Twoje zapytanie?

**Comment by runaway90** [comment]
@PawelTaberski tak, korzystam się z tokiena uzyskanego przy pomocy autoryzacji client credentials.

**Comment by PawelTaberski** [comment]
@runaway90 Nie client-credentials jest tylko dla publicznych zasobów jak listingi, nie pobierzesz nim informacji od konkretnego usera, bo wtedy musisz być zautoryzowany jako dany user. I pewnie dostałes status 403 odpowiedzi czyli forbidden
