### ISSUE TITLE
Pytanie dot. nadawania paczek Allegro DPD Czechy

### ISSUE THREAD

**Issue by macieq000** [allegro/allegro-api#8410]
Witam,

mam pytanie dot. generowania etykiet poprzez API Allegro DPD Czechy. Obecnie generujemy etykiety z autorskiego oprogramowania. Przesyłki DPD Allegro standard normalnie wpadają nam na rozrachunki Allegro, natomiast przesyłki Allegro DPD Czechy wpadają z jakiegoś powodu na naszą umowę własną. 

Wyjaśniając sprawę z działem IT DPD dostaliśmy info że trzeba podać jak poniżej:
<payerType>THIRD_PARTY</payerType>

Pytanie co muszę podać w 
thirdPartyFID i  authDataV1

**Comment by AureliuszBrussy** [comment]
Pytanie dotyczy zmiennych, które nie występują w naszym publicznym API, więc niestety nie będę w stanie odpowiedzieć na Twoje pytanie.

**Comment by macieq000** [comment]
Ok, a czy można znaleźć gdzieś przykład jak powinno wyglądać poprawne zapytanie? Bo dostaliśmy info z DPD że wg ich najlepszej wiedzy, paczki Allegro DPD Czechy w odróżnieniu od paczek Allegro DPD standard powinny być generowane bezpośrednio na WzA. Czyli idąc tym tokiem jako thirdPartyFID powinniśmy podać jakiś numer Allegro a nie nasz numer umowy?

**Comment by AureliuszBrussy** [comment]
Tak, powinniście korzystać właśnie z Wysyłam z Allegro, np. za pomocą API. Nie mamy tutaj do zasugerowania żadnych obejść. Działanie samego Wysyłam z Allegro w ramach naszego publicznego API [opisujemy w poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY). Opisujemy tam także przykładowe requesty.
