### ISSUE TITLE
"Pickup point is incorrect",

### ISSUE THREAD

**Issue by Pawelpwg** [allegro/allegro-api#8411]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [ x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

paczka allegro przsylka polecona, request i response podspodem, mozecie doradzic co jest nie tak z requestem? 

pickup point zostal podany przez poczte polska, a additionalSerivices nie ma wogole w requescie

2024-02-05 17:18:54,547 [ 10 ] INFO Main Logger - [ ITSmart.Kurier.Allegro.OneBox.AllegroOneBoxFacade ]: AllegroRequest: {
  "commandId": "959e194e-7eaf-4e3f-9643-279934ccbae1",
  "input": {
    "deliveryMethodId": "aa1d05e0-943b-47cb-a759-9d8c16707129",
    "receiver": {
      "street": "ulica",
      "streetNumber": "6a",
      "postalCode": "33-100",
      "city": "tarnów",
      "countryCode": "PL",
      "country": null,
      "email": "11111@allegromail.pl",
      "name": "j n",
      "company": "",
      "phone": "+111111",
      "point": null
    },
    "pickup": {
      "name": "l spolka",
      "company": "l Sp. z o.o.",
      "street": "m",
      "streetNumber": "892A",
      "postalCode": "36-007",
      "city": "Krasne",
      "state": null,
      "countryCode": "PL",
      "email": "biuro@l.pl",
      "phone": "111111111",
      "pointId": "248130"
    },
    "sender": {
      "street": "m",
      "streetNumber": "892A",
      "postalCode": "36-007",
      "city": "Krasne",
      "countryCode": "PL",
      "email": "biuro@l.pl",
      "name": "L spolka",
      "company": "L Sp. z o.o.",
      "phone": "111111111"
    },
    "packages": [
      {
        "length": {
          "value": 30,
          "unit": "CENTIMETER"
        },
        "width": {
          "value": 30,
          "unit": "CENTIMETER"
        },
        "height": {
          "value": 30,
          "unit": "CENTIMETER"
        },
        "weight": {
          "value": "1",
          "unit": "KILOGRAMS"
        },
        "type": "PACKAGE",
        "waybill": null
      }
    ],
    "type": "PACKAGE",
    "labelFormat": "PDF",
    "description": "liceum3",
    "insurance": {
      "amount": "28.00",
      "currency": "PLN"
    }
  }
} 2024-02-05 17:18:56,485 [ 35 ] INFO Main Logger - [ ITSmart.Kurier.Allegro.OneBox.AllegroOneBoxFacade ]: Response - Status: {
  "commandId": "959e194e-7eaf-4e3f-9643-279934ccbae1",
  "status": "ERROR",
  "errors": [
    {
      "code": "VALIDATION_ERROR",
      "message": "Pickup point is incorrect",
      "details": null,
      "path": "pickup.point",
      "userMessage": "Punkt punktu nadania przesyłki jest niepoprawny"
    },
    {
      "code": "VALIDATION_ERROR",
      "message": "Service is unavailable for selected parcel type",
      "details": null,
      "path": "additionalServices",
      "userMessage": "Usługa niedostępna dla wybranego typu przesyłki"
    }
  ],
  "shipmentId": null
}

**Comment by AureliuszBrussy** [comment]
Drugi komunikat błędu dotyczy typu przesyłki - dostępny dla tej metody dostawy typ to "DOX". Dostępne typy paczek dla danej usługi dostawy pobierzesz za pomocą [GET /shipment-management/delivery-services](https://developer.allegro.pl/documentation#operation/getDeliveryServices).

Weryfikujemy jeszcze problem dla pierwszego komunikatu błędu, wrócę jeszcze z informacją.

**Comment by Pawelpwg** [comment]
ok czyli typ paczki zamiast package dac dox? komunikat jest troche mylacy ale spoko, poprawi sie logike

**Comment by AureliuszBrussy** [comment]
Zgadza się. Co do pierwszego błędu - w obiekcie pickup wysłałeś niepoprawną nazwę pola - zamiast `point`, wrzuciłeś `pointId`.

**Comment by Pawelpwg** [comment]
fatycznie, nie zauwazylem tego, i pewnie zostalo z starej implentacji, dzieki za zwrocenie uwagi, wrzucam poprawki i testuje

**Comment by Pawelpwg** [comment]
jeszcze jedno pytanie do pickup point, w jaki sposob nalezy rozpoznawac ktory pikcup poin przekazac w zaleznosci od typu przesylki?
inaczej mowiac, mam pickup point dla poczty, ale jesli go przekaze w dla przykladowo onebox to wraca blad, wiec jaki warunek zaimplementowac

**Comment by AureliuszBrussy** [comment]
Niestety, nie do końca rozumiem, czy mógłbyś uszczegółowić pytanie? Definiowanie punktu odbioru przesyłki przez kuriera zależy od tego, jaką metodą dostawy nadajesz przesyłkę. Nieraz, tak jak w przypadku Poczty Polskiej musi być to punkt urząd Poczty Polskiej, nieraz wystarczy, że będzie to dowolny adres odbioru, pod który ma podjechać kurier.
