### ISSUE TITLE
Próbuję stworzyć ofertę za pomocą requestu:

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#8412]
Próbuję utworzyć ofertę przez endpoint: sale/product-offers, ale otrzymuję błąd o braku zdjęć pomimo tego, że zdjęcie zostało dodane.

Środowisko produkcyjne.

Trace ID: "383ab49fd5667459"
Zwrotka:

`{"errors":[{"code":"ProductValidationException","message":"Product needs to have at least one image","details":null,"path":"productSet[0].product","userMessage":"Produkt powinien posiadać co najmniej jedno zdjęcie"}]}`

**Comment by AureliuszBrussy** [comment]
Błąd wystąpił, ponieważ przesłane zdjęcie było zbyt małych rozmiarów i zostało wykluczone. Nie spełniło wymagań bazy produktowej.

**Comment by marmited** [comment]
Dziękuję, szukam informacji o rozmiarze zdjęć i znalazłem coś takiego:

Wszystkie zdjęcia mają określone minimalne rozmiary (dłuższy bok minimum 500 pikseli).
Maksymalny rozmiar zdjęcia – 2560 x 2560 pikseli. Na Allegro możesz wgrać zdjęcia o maksymalnej rozdzielczości 26 Mpx. Zdjęcia o boku dłuższym niż 2560 pikseli proporcjonalnie przeskalujemy, aby mieściły się w rozmiarze 2560x2560.

Czy to prawda?

**Comment by AureliuszBrussy** [comment]
Potwierdzam.
