### ISSUE TITLE
Nie znaleziono pasującego produktu dla wskazanego identyfikatora.

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#8415]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Mam błąd z wystawianiem aukcji. Wystawiam aukcje z produktem nieistniejącym w waszym katalogu. 
Otrzymuję wiadomość zwrotną: "Nie znaleziono pasującego produktu dla wskazanego identyfikatora."
trace-id: 690c5d088700e35e

O co może chodzić?

**Comment by MaciejFrackowiak** [comment]
Twój błąd jest bezpośrednio związany ze [zmianą](https://github.com/allegro/allegro-api/issues/8397), którą ostatnio ogłosiliśmy. Jak widzę w requeście przekazałeś idType oraz GTIN jako id.
