### ISSUE TITLE
Brak potwierdzenia aktualizacji uprawnień aplikacji przy parametrze prompt=confirm

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#8417]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] z logowaniem lub autoryzacją / with login or authorization

1. Jestem zalogowany na allegro na koncie X
2. Moja aplikacja jest zalogowana na koncie Y
3. Aktualizuję uprawnienia aplikacji przez [https://apps.developer.allegro.pl/](https://apps.developer.allegro.pl/)
4. W mojej aplikacji loguję się ponownie generując link z parametrem `prompt=confirm` w celu pozyskania nowych uprawnień
5. Zostaję zapytany, czy chcę się zalogować jako X, klikam inne konto i loguję się jako Y
6. Brak zapytania o uprawnienia aplikacji (no profit)
7. Loguję się jeszcze raz, tym razem już jako Y (tak zostałem przelogowany autoryzując aplikację, co jest jak dla mnie bez sensu - co ma oauth do frontu?)
8. Dopiero teraz jestem pytany czy zgadzam się na nowe uprawnienia aplikacji

**Comment by AureliuszBrussy** [comment]
Parametr prompt wymusza tylko pojawienie się ekranu, na którym użytkownik potwierdza, czy jest pewien, że chodzi o logowanie na dane konto - nie wymusza on ponownego potwierdzenia zakresów dostępów dla aplikacji. 

Sama zmiana zakresów uprawnień z poziomu Developer Apps przy ponownym logowaniu spowoduje konieczność potwierdzenia nowych uprawnień, natomiast rozpropagowanie tych zmian może zająć kilka chwil. To powoduje, że jeżeli próba logowania nastąpi od razu po zmianie uprawnień - ekran potwierdzenia nowych zakresów może się jeszcze nie pojawić.
