### ISSUE TITLE
Wyszukiwanie zamówień po numerze oferty?

### ISSUE THREAD

**Issue by bswierzewski** [allegro/allegro-api#8418]
Witam serdecznie, chciałem zapytać czy dla zasobu /order/checkout-forms w najbliższym czasie jest przewidziana rozbudowa parametrów wyszukiwania o pole offer.id? Aktualnie chyba nie istnieje sposób by pobrać wszystkie zamówienia dla danej oferty.

**Comment by AureliuszBrussy** [comment]
Nie planujemy takiej zmiany. Faktem jest także to, że nie udostępniamy opcji pobrania wszystkich zamówień dla danej oferty. Możesz zgłosić swoją sugestię w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions) - to tam zbieramy wszystkie propozycje rozwoju.
