### ISSUE TITLE
How to detect anulowane zamowenia?

### ISSUE THREAD

**Issue by invital** [allegro/allegro-api#8419]
Dear Allegro Tech support,
can you show me how we can detect CANCELLED orders? We are using API for importing NEW orders from Allegro to our CRM system. The endpoint for searching NEW orders is https://api.allegro.pl/order/checkout-forms?fulfillment.status=NEW , that's work well. Sometimes customers cancel the order but we do not know about it,  Allegro will return money to customer but we send package because we are not knowing about CANCELLED order.

I wanted to somenthing with it, so my idea was calling endpoint: /order/checkout-forms?updatedAt.lte=2018-07-31T08%3A48%3A14.889Z&updatedAt.gte=2018-07-31T08%3A48%3A14.888Z;
I thought that if order change status then updatedAt must be change too, but this parametr is stayed same - so I cannot detect via this parameter orders with changed status. How we can detect changing status of order? I cannot calling all existing orders and detecting if something change, I thought updatedAt should work with situations but updatedAt is not changing in case of change status.

I am testing it with zamowenia c2f5c9a0-c4fa-11ee-a81a-5ffa8cf20f17
Zamowenia was created at: 6 lut 2024, 15:20
Zamowenia was canceled at: 6 lut 2024, 17:19
API returning updateAt: 2024-02-06T14:21:43.297Z (In my local time it is 06.02.2024 15:21)

**Comment by AureliuszBrussy** [comment]
The best way to detect changes in orders is to use orders event journal: [GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET). You can read more about this journal in [our guide](https://developer.allegro.pl/tutorials/process-orders-PgPMlWDr8Cv#event-log).
