### ISSUE TITLE
 GET /sale/categories/{category.id}

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#8420]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource

Od wczoraj metoda dla wielu kategorii zwraca błąd , mimo ze kategorie normalnie są dostępne na frontendzie allegro , jako kategorie najniższego rzędu

W przypadku kategorii 79433 i wielu innych , zwracany jest błąd:
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ERROR
                    [message] => Category '79433' in tree 'listing-pl' not found
                    [details] => ResourceNotFoundException
                    [path] =>.
                    [userMessage] => Category '79433' in tree 'listing-pl' not found
                )

        )

)

**Comment by 11mszot** [comment]
nadal nie rozumiem dlaczego to wywołanie zwraca błąd , dwa dni temu działało prawidłowo i zwracało listę parametrów dla wskazanej kategorii

**Comment by AureliuszBrussy** [comment]
Oznacza to, że w drzewie asortymentowym nie istnieje już taka kategoria - znajduje się ona tylko w drzewie nawigacyjnym. Źródłem drzewa kategorii powinno być dla Ciebie tylko [GET /sale/categories/{categoryId}](https://developer.allegro.pl/documentation#operation/getCategoryUsingGET_1). Nie możesz brać kategorii bezpośrednio z drzewa nawigacyjnego.

**Comment by 11mszot** [comment]
To jakiś absurd , że kategorie frontendowe , mają być inne niż kategorie dla Api , pracuję z api allegro od 10 lat i zawsze lista kategorii na frontendzie była zgodna z tą zwracaną przez api. W mojej ocenie znowu strzeliliście jakiego babola , i teraz odwracacie kota ogonem

**Comment by AureliuszBrussy** [comment]
Nie jest to błąd - to zmierzone działanie, które pozwala nam uprościć drzewo kategorii. Wcześniej, gdy utrzymywaliśmy jedno drzewko, w różnych jego częściach mieliśmy podobne kategorie, co powodowało, że w każdej z takich kategorii sprzedający musiał wystawiać różne oferty z takim samym produktem. Aktualnie wystarczy, że sprzedający wystawi ofertę w jednej z kategorii asortymentowych, a my pokażemy ofertę w wielu podobnych do siebie kategoriach drzewa nawigacyjnego. 

Rozpoczęliśmy takie działanie już kilka lat temu, możesz przeczytać o tym np. [w newsie](https://developer.allegro.pl/news/na-poczatku-grudnia-zaczniemy-scalac-kategorie-po-stronie-sprzedajacego-k1nyd205YHo) z 2021 roku.

**Comment by 11mszot** [comment]
Aplikacja którą nnapisałem kilka lat temu , wie że dany przedmiot może być wystawiony w kategorii 79433 , i przez lata to robił. Chętnie dopiszę stosowny algorytm , bo rozumiem że wszystko się zmienia , tylko z jakiego zasobu i jaką metodą  mam teraz uzyskać informację o aktualnie prawidłowej kategorii dla tego produktu?

**Comment by AureliuszBrussy** [comment]
Tak jak wspomniałem, do pobrania i mapowania drzewa korzystaj z [GET /sale/categories/{categoryId}](https://developer.allegro.pl/documentation#operation/getCategoryUsingGET_1). Możesz też korzystać z naszego zasobu do pobierania sugestii pasujących do frazy kategorii: [GET /sale/matching-categories](https://developer.allegro.pl/documentation#operation/categorySuggestionUsingGET).

Udostępniamy także dziennik zmian w kategoriach: [GET /sale/category-events](https://developer.allegro.pl/documentation#operation/getCategoryEventsUsingGET_1). W przypadku np. usunięcia kategorii znajdziesz informację, do jakiej kategorii nastąpiło przekierowanie:

```
{
"id": "MTEzMjQzODU3NA",
"occurredAt": "2019-06-26T15:26:43.891Z",
"type": "CATEGORY_DELETED",
"category": {
  "id": "165",
  "name": "Smartphones and Cell Phones",
  "parent": {
      "id": "4"
  },
"leaf": false
},
"redirectCategory": {
"id": "7"
}
}
```

**Comment by 11mszot** [comment]
/sale/categories{categoryId} zwraca not found : Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ERROR
                    [message] => Category '79433' not found
                    [details] => ResourceNotFoundException
                    [path] =>.
                    [userMessage] => Category '79433' not found
                )

        )

)
Czy to oznacza że za każdym razem mam pobierać całą historię zmian kategorii , przez zasób : GET /sale/category-events] ?

**Comment by 11mszot** [comment]
No i niestety panie Aureliszu , przejrzałem wszystko co zwraca wskazana przez pana metoda /sale/category-events , i nie znalazłem ani śladu informacji , co się stało z kategorią 79433

**Comment by AureliuszBrussy** [comment]
@11mszot weryfikujemy to. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@11mszot ta kategoria została usunięta z drzewa asortymentowego 09-08-2023, stąd brak informacji na tym zasobie - zwracamy tylko informacje o ostatnich 3 miesiącach.
