### ISSUE TITLE
Szukanie ofert po numerze EAN na offers/listing

### ISSUE THREAD

**Issue by JakubSzuber** [allegro/allegro-api#8421]
Witam, chciałem zapytać czy przy przykładowym zapytaniu https://api.allegro.pl/offers/listing?searchMode=DESCRIPTIONS&phrase=8711252182117 zostaną znalezione oferty dla podanego EAN'a? Gdy wpisuje się w wyszukiwarkę Allegro ten numer EAN "8711252182117" wtedy pomyślnie znajdywane są produkty (mimo tego, że w opisie ani parametrach nie ma nigdzie podanego EAN'a - czyli EAN musi być przypisany do ofert ale nigdzie nie jest on wyświetlany w opisie ofert):

![image](https://github.com/allegro/allegro-api/assets/90647840/10909386-9d26-429f-a2a9-045e89a15d85)

Czy jak zrobimy request https://api.allegro.pl/offers/listing?searchMode=DESCRIPTIONS&phrase=8711252182117 wtedy również zostaną znalezione te oferty pomimo faktu, że nie mają tego numeru EAN w opisie? Parametr "searchMode=DESCRIPTIONS" według dokumentacji szuka tylko po tytule i opisie produktu, więc podejrzewam, że niestety nie zostaną zwrócone żadne oferty, ale chciałbym się upewnić.

**Comment by JakubSzuber** [comment]
Czyli oferty z przypisanym do nich numerem EAN "8711252182117" znalezione dla https://api.allegro.pl/offers/listing?phrase=8711252182117 nawet gdy ten EAN jest nie wyświetlany w opisie oferty (jest tylko przypisany do ofert pod spodem)?

**Comment by AureliuszBrussy** [comment]
Tak.
