### ISSUE TITLE
Provided waybill is not valid for this carrier

### ISSUE THREAD

**Issue by KaMisza** [allegro/allegro-api#8422]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource

 - https://api.allegro.pl/order/checkout-forms/f07f4550-c404-11ee-89d8-27a2d87a627f/shipments
 REQUEST BODY
 - {"carrierId":"ALLEGRO","waybill":"1000713716065U","lineItems":[{"id":"f07951e0-c404-11ee-89d8-27a2d87a627f"}]}
 RESPONSE BODY
 - {"errors":[{"code":"CarrierWaybillValidationException","message":"Provided waybill is not valid for this carrier","details":null,"path":null,"userMessage":"Wystąpił błąd. Ten numer przesyłki jest niepoprawny dla tego przewoźnika. Nie udało się zapisać zmian. Spróbuj ponownie."}]}
- "Trace-Id":"ea79e9f3bc22bafe"
- ID Allegro dla zamówienia od którego został utworzony list przewozowy "integration_id": "c464c330-c45b-11ee-adf8-e3e70557e2d9"
- dokładnie opisz problem -->
Wysyłamy numer listu przewozowego, ale ten jest odrzucany ze zwrotką w response body

**Comment by AureliuszBrussy** [comment]
Ten waybill jest charakterystyczny dla DPD. Jako carrierId wskaż "DPD".
