### ISSUE TITLE
Nadawanie przesyłki Sandbox

### ISSUE THREAD

**Issue by Tanioagd** [allegro/allegro-api#8423]
Występuje problem:
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ X ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [x] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,
problem dotyczy zamówień:
99b2f6c0-c58c-11ee-be6b-29c1f53944b7
e31dc091-c101-11ee-97aa-33ca046a5f1f

przy próbie nadania przesyłki dostaję komunikat:
"Process konfigurowania konta WZA zakończył się błędem. Spróbuj odświeżyć stronę za chwilę lub skontaktuj się z nami w celu weryfikacji tego problemu."

Co jest powodem takiego komunikatu? Czy czegoś brakuje w konfiguracji konta?

**Comment by Tanioagd** [comment]
Udało mi się dostać do takich trace-id:
c0a090a18930ceb5
f6f8aae953b890b7

632fb2bd175ea6f5
a9bb000eb6040264

**Comment by MaciejFrackowiak** [comment]
Weryfikuję przypadki z zespołem odpowiedzialnym za usługę, wrócę z odpowiedzią.

**Comment by Tanioagd** [comment]
Udało się coś ustalić w sprawie powyższego błędu?

**Comment by MaciejFrackowiak** [comment]
Weryfikujemy to - jak wspomniałem wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Mam jedno pytanie pomocnicze - w jaki sposób wywołujesz requesty do nas? Czy korzystasz bezpośrednio z naszego API, czy opierasz się o jakiegoś integratora? Pytam, ponieważ komunikat, który otrzymałeś w pierwszym poście sugeruje na działanie poza API.

**Comment by Tanioagd** [comment]
Generalnie opieram się o działanie integratora waszego API - ale z racji niejasnego błędu zwracanego przez API spróbowałem nadać przesyłkę przez stronę [https://allegro.pl.allegrosandbox.pl/](https://allegro.pl.allegrosandbox.pl/), gdzie przy próbie nadania przesyłki przez przycisk "Nadaj przesyłkę" występował właśnie taki błąd jak wyżej.

Sprawdziłem teraz i błąd zdaje się więcej nie występować. Zamykam temat.
