### ISSUE TITLE
Brak potrzebnych informacji w zasobie /sale/product-offers/{offerId}

### ISSUE THREAD

**Issue by Morph21** [allegro/allegro-api#8424]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

w wyżej wymienionym zasobie brakuje podstawowych informacji które są w endpoincie  /sale/offers takich jak:
currentPrice - dla licytacji
biddersCount - dla licytacji
primaryImageUrl - chyba że to zawsze będzie pierwszy element na liście images

Czy ten problem będzie naprawiony czy te dane przychodzą ale nie ma ich w dokumentacji po prostu?

**Comment by MaciejFrackowiak** [comment]
Obecnie zdecydowana większość ofert w serwisie to oferty Kup Teraz, dlatego pominięcie tych informacji (currentPrice, biddersCount) nie jest przypadkowe. Informacje te są nadal dostępne na ogólnej liście ofert - [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET). 
Natomiast odnośnie zdjęcia - tak, pierwsze zdjęcie z tablicy "images" to pierwsze foto.

**Comment by Morph21** [comment]
Rozumiem.
a czy pole startedAt nie istnieje w tym zasobie z tego samego powodu? Czy powinniśmy tutaj kierować się innym polem które oznacza początek istnienia oferty?

**Comment by MaciejFrackowiak** [comment]
Tak, pola startedAt również nie ma, ponieważ dla ofert Kup Teraz de facto nie ma znaczenia ich czas rozpoczęcia.

**Comment by Morph21** [comment]
W tym wypadku bardziej chodzi o to żeby użytkownik był w stanie zobaczyć kiedy tą ofertę opublikował w prosty sposób. Dla samej oferty pewnie nie ma znaczenia ale już dla jakichś danych statystycznych typu ile się średnio sprzedało dziennie z danej oferty to bez czasu początkowego nie ma takiej informacji

**Comment by MaciejFrackowiak** [comment]
Dane te nadal są w endpoincie GET /sale/offers.

**Comment by Morph21** [comment]
Ok, dziękuję za odpowiedź. Pozwolę sobie zostawić otwarty ten issue na dzisiaj jakby jeszcze były jakieś pytania żeby nie tworzyć nowego. Jutro go zamknę
