### ISSUE TITLE
Zamykanie aukcji

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#8425]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Przy próbie zamkniecia aukcji przez endpoint https://api.allegro.pl/sale/product-offers/  wysylamy dane 
{"stock":{},"publication":{"status":"ENDED"},"delivery":{}}
w zwrotce w sekcji productSet dostajemy informacje

            "publication":{
               "status":"LISTED"
            },

natomiast w sekcji glownej 
   "publication":{
      "status":"ENDED",
      "duration":null,
      "endedBy":"ADMIN",
      "endingAt":null,
      "startingAt":null,
      "republish":false,
      "marketplaces":{
         "base":{
            "id":"allegro-pl"
         },
         "additional":[
            {
               "id":"allegro-cz"
            }
         ]
      }
   },
Mimo to aukcja jest cały czas aktywna, do tej pory aukcje zamykaliśmy w ten sposób i nie było żadnego problemu tutaj pierwszy raz mamy taki przypadek, coś robimy nie tak?
"Trace-Id":"3e78af5d1e59f90e"

**Comment by MaciejFrackowiak** [comment]
Oferta odpowiadająca trace-id została zatrzymana przez administratora - 29.01.2024 14:28. W serwisie WWW również jest zakończona.

**Comment by d3stozaur** [comment]
https://allegro.pl/oferta/hot-wheels-city-tor-samochodowy-atak-smoka-na-straz-pozarna-tor-5-hdp03-14685001797  ale dalej na stronie mozna kupic

**Comment by MaciejFrackowiak** [comment]
Trace-id prowadzi do innej oferty - xxxxxx59857.

**Comment by d3stozaur** [comment]
Faktycznie mój błąd że nie zauwazyłem róznicy w numerach, jedno tylko pytanie, w jakis sposb te aukcje sa powiazane? poniewaz wyszukanie aukcji 14428059857  przekierowuje bezposrednio na aukcje 14685001797

**Comment by MaciejFrackowiak** [comment]
To nasz wewnętrzny mechanizm, który rozpoznaje podobieństwo ofert i w przypadku zakończonych zwraca aktualnie trwającą z tym samym asortymentem.

**Comment by d3stozaur** [comment]
ok dziekuje za informacje
