### ISSUE TITLE
Nie moge uzyskać seller id, które pozwoliłoby mi na używanie Allegro API

### ISSUE THREAD

**Issue by aigeekjkf** [allegro/allegro-api#8427]
Chciałbym się dowiedzieć gdzie moge znaleźć seller id na Allegro. 
Jest mi potrzebne do stworzenia integracji sklepu Wordpress z Allegro.
Wie ktoś gdzie moge je znaleźć?

**Comment by MaciejFrackowiak** [comment]
Skorzystaj z zasobu [GET /me](https://developer.allegro.pl/documentation/#operation/meGET), w którym zwrócimy id konta.
