### ISSUE TITLE
Aktywacja sprzedaży

### ISSUE THREAD

**Issue by tomasz-k** [allegro/allegro-api#843]
Witam, czy jest możliwość odblokowania wystawiania ofert dla konta firmowego? W panelu przechodzi mi do wykonania płatności testowej 1.01 zł i po wyborze banku  przenosi do symulatora płatności z buttonami Accept i Cancel, jednak od dwóch dni po kliknięciu na Accept wyskakuje jedynie alert Error. 
Login: tkbit

**Comment by MartaNowaczyk** [comment]
@tomasz-k konto aktywowane
