### ISSUE TITLE
Masowe pobieranie szczegółów ofert

### ISSUE THREAD

**Issue by krychaj5** [allegro/allegro-api#8430]
Witam, chciałbym pobrać szczegóły wielu swoich ofert jednocześnie za pomocą zasobu https://developer.allegro.pl/documentation#operation/getProductOffer

lecz udaje mi się otrzymywać jedynie szczegóły pojedynczej oferty (przy pojedynczym requeście)

GET https://api.allegro.pl/sale/product-offers/${offerId}

próbowałem przekazywać kilka ID w ścieżce w różny sposób np. 
https://api.allegro.pl/sale/product-offers?offer.id=1&offer.id=2&offer.id=3
lub
https://api.allegro.pl/sale/product-offers?1,2,3,4

lecz bezskutecznie
czy jest możliwośc aby zasób ten zwrócił szczegóły dotyczące wielu ofert jednocześnie?

**Comment by AureliuszBrussy** [comment]
Nie, nie jest to możliwe, tym zasobem możesz pobierać szczegóły oferty pojedynczo. Jedynym zasobem do pobierania listy ofert jest endpoint [GET /sale/offers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET).
