### ISSUE TITLE
Brak wymaganego parametru

### ISSUE THREAD

**Issue by mareklemur** [allegro/allegro-api#8432]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Podczas wystawiania oferty z podpiętym produktem jest taki błąd:
{"errors":[{"code":"ConstraintViolationException.MissingRequiredParameters","message":"Missing required parameters: 222637","details":"ConstraintViolationException.MissingRequiredParameters","path":"parameters","userMessage":"Uzupełnij parametry obowiązkowe: Liczba sztuk w opakowaniu."}]}
gdy ten parametr zostanie uzupełniony w ofercie,, to jest taki błąd:
{"errors":[{"code":"ParameterCategoryException","message":"Unprocessable Entity","details":null,"path":"parameters","userMessage":"Parameter `222637:Liczba sztuk w opakowaniu` should not be specified as in section `offer`."}]}
W produkcie brakuje obowiązkowego parametru, ale nie można go dodać w ofercie. Jak wystawić taką ofertę?

**Comment by AureliuszBrussy** [comment]
Wygląda na to, że zamiast przekazać parametr w sekcji produktowej, czyli w `productSet[].product.parameters`, przekazujesz go w ramach parametrów ofertowych (`parameters`). 

Więcej o odróżnianiu parametrów ofertowych od produktowych przeczytasz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#parametry-ofertowe).
