### ISSUE TITLE
Błąd podczas dodawania oferty - brak obrazka pomimo że obrazek został wysłany na serwer

### ISSUE THREAD

**Issue by gkopec** [allegro/allegro-api#8435]
Przy próbie dodania oferty z obrazkiem API zwraca błąd:
```
{"errors":[{"code":"ProductValidationException","message":"Product needs to have at least one image","details":null,"path":"productSet[0].product","userMessage":"Produkt powinien posiadać co najmniej jedno zdjęcie"}]}
```
Pomimo, że obrazek jest wgrany i dołączony do payloada:
https://a.allegroimg.allegrosandbox.pl/original/113803/0df132ef46faa383b9f114eadcd5

Za to dodanie trochę większego obrazka już działa:
https://a.allegroimg.allegrosandbox.pl/original/11b945/dd2d5f654db28a2aab0b1dd9d951

Czy są gdzieś wytyczne dotyczące minimalnej wielkości obrazka?
Warto dodać, że aukcja z dwoma obrazkami się dodała poprawnie:
https://allegro.pl.allegrosandbox.pl/oferta/wklad-zaworu-do-klimatyzacji-vw-gm-5szt-7746684562

**Comment by AureliuszBrussy** [comment]
Dłuższy bok nie może być mniejszy niż 400px. Poza tym zdjęcie musi także być odpowiedniej jakości - mamy mechanizmy automatycznej oceny i odrzucamy zdjęcia słabej jakości.

**Comment by gkopec** [comment]
@AureliuszBrussy czy można liczyć, że w przyszłości API odpowie innym błędem niż brak obrazka? I skoro mechanizmy odrzucają błędne obrazki to dlaczego udało się założyć aukcję z tym małym obrazkiem (https://allegro.pl.allegrosandbox.pl/oferta/wklad-zaworu-do-klimatyzacji-vw-gm-5szt-7746684562) ?

**Comment by AureliuszBrussy** [comment]
@gkopec tak, planujemy zmienić zwracamy komunikat tak, aby był zrozumiały. Przeanalizujemy też, dlaczego w tym drugim przypadku to nieodpowiednie zdjęcie zostało użyte w ofercie.
