### ISSUE TITLE
Asynchroniczne API wystawiania oferty - kiedy status odpowiedzi 202?

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#8437]
Mam pytanka:
1. Czy można w jakiś sposób przetestować status odpowiedzi 202?
2. Czy status odpowiedzi 202 może być zwrócony przy tworzeniu szkicu (wyłączona publikacja oferty):
```
  "publication": {
      "status": "INACTIVE"
    }
```

**Comment by MaciejFrackowiak** [comment]
Niestety, ale nie ma mechanizmu generującego 202 "na życzenie" - to wyłącznie efekt obciążenia naszych mechanizmów. Ponadto, 202 pojawi się tylko przy aktywacji oferty - przy tworzeniu szkicu nie wystąpi.

**Comment by tomasz-grzesik** [comment]
Dziękuję za udzielenie odpowiedzi.
