### ISSUE TITLE
Prośba o aktywację konta sandbox

### ISSUE THREAD

**Issue by gkopec** [allegro/allegro-api#8438]
Poproszę o aktywację konta sandbox: INVENTO_TEST

**Comment by MaciejFrackowiak** [comment]
Przekonwertowałeś swoje konto zwykłe na firmowe, jednak wybrałeś opcję tylko kupuję, przez co nie mamy możliwości pełnej weryfikacji tego konta. Zmień proszę swój wybór na chcę sprzedawać - zrobisz to w zakładce [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by gkopec** [comment]
@MaciejFrackowiak czy możesz sprawdzić teraz?

**Comment by MaciejFrackowiak** [comment]
Teraz jest OK - konto jest już aktywne.
