### ISSUE TITLE
Brakujące parametry niektórych produktów

### ISSUE THREAD

**Issue by K-Mazur** [allegro/allegro-api#8439]
Dzień dobry,

Mam problem z wystawianiem niektórych produktów przy pomocy zasobu https://developer.allegro.pl/documentation#operation/createProductOffers

Mianowicie przy niektórych produktach brakuje jednego z parametrów - model.

Konkretny przykład poniżej:

1. Opona *Mirage MR-HP172 235/60R18 107 V wzmocnienie (XL)* o numerze EAN (GTIN) `6953913173993`.
2. Wyszukuję produkt dla tej opony na podstawie EAN (GTIN). https://developer.allegro.pl/documentation#operation/getSaleProducts Otrzymuję z API jeden produkt o ID `b5869404-5755-4086-88a8-6d29d70c4e50`.
3. Produkt ten w parametrze "category" ma kategorię o ID `257694` - Opony -> Do samochodów 4x4/SUV -> Letnie
4. Ma też uzupełnione podobne kategorie "category.similar", a w tablicy podobnych kategorii znajduje się kategoria o ID `257689` - Opony -> Do samochodów osobowych -> Letnie.
5. Próbuję więc wystawić ten produkt w obydwu kategoriach -  `257694` oraz `257689`.
6. O ile w kategorii "głównej" - `257694` produkt wystawia się bez problemu, to w kategorii "podobnej" `257689` otrzymuję błąd:
```
{
    "errors": [
        {
            "code": "ConstraintViolationException.MissingRequiredParameters",
            "path": "parameters",
            "details": "ConstraintViolationException.MissingRequiredParameters",
            "message": "Missing required parameters: 250019",
            "userMessage": "Uzupe\u0142nij parametry obowi\u0105zkowe: Model."
        }
    ]
}
```
Rzeczywiście prawdą jest, że produkt o ID `b5869404-5755-4086-88a8-6d29d70c4e50` nie ma parametru model `250019`. Ma natomiast inny parametr model - `237206`.

Jeśli nawet przy wyszukiwaniu produktu na podstawie EAN (GTIN) zawężę wyszukiwanie do kategorii o ID `257689` to nadal otrzymuję produkt o tym samym ID, bez parametru model `250019` (a z parametrem model o ID `237206`). 

 

Jak radziliby Państwo rozwiązać ten problem? Powinienem ten parametr przypisywać manualnie? Czy może to jest błąd po Państwa stronie? 

 

Na jakiegoś rodzaju błąd po Państwa stronie wskazywałoby to, że dla porównania produkt o ID `02ecd4e3-b65d-4ad3-a12c-a37c714e623a` udało mi się poprawnie wystawić w obu powyższych kategoriach - `257694` oraz `257689`.  Różnica jest taka, że produkt ten ma w parametrach przypisany parametr Model o ID `250019`, ale mimo to udaje się go wystawić w kategorii `257694`, gdzie parametr model ma ID = `237206` (inne ID), a produkt tego parametru nie ma przypisanego (to znaczy ma przypisany model, ale o ID `250019`, a nie `237206`).

Innymi słowy, korzystam z tego samego schematu przy wystawianiu opony *245/40/21 Y Bridgestone DUELER ALENZA 001* (ean: `3286341006018`, produkt `02ecd4e3-b65d-4ad3-a12c-a37c714e623a`), oraz *Mirage MR-HP172 235/60R18 107 V wzmocnienie (XL)* (ean: `6953913173993`, produkt `b5869404-5755-4086-88a8-6d29d70c4e50`), czyli:
1. Wyszukanie produktu na podstawie EAN (GTIN).
2. Wystawienie produktu w kategorii `257694` - Opony -> Do samochodów 4x4/SUV -> Letnie, oraz `257689` - Opony -> Do samochodów osobowych -> Letnie, z uzupełnieniem dwóch parametrów - stan oraz ilość opon w ofercie.

Mimo zastosowania tego samego schematu jedna opona wystawia się poprawnie w obu kategoriach, a druga nie.

**Comment by MaciejFrackowiak** [comment]
Istotę różnicy stanowi parametr Model, który przyjmuje różne id w zależności od kategorii.
Dla produktu "b5869404-5755-4086-88a8-6d29d70c4e50" głównym parametrem Model jest 237206 odpowiadający kategorii 257694.
Produktowi "02ecd4e3-b65d-4ad3-a12c-a37c714e623a" odpowiada Model 250019 z kategorią główną 257689.
Kategoria 257689 i jej aktualny parametr 250019 został "spadkobiercą" kategorii 237206, stąd nijako akceptacja obu kategorii.
Dla kategorii 257694 jest przypisany jeden parametr Model 237206 i stąd komunikat zwrotny o braku parametru dla kategorii 257689.
