### ISSUE TITLE
Błąd przy wznawianiu aukcji

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#8441]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
wznawiam aukcję prostym
```
{
  "stock": {
    "available": 36
  },
  "publication": {
    "status": "ACTIVE"
  }
}
```

dlaczego zwracacie błąd typu "Uzupełnij parametry obowiązkowe: Waga produktu." skoro produkt już dawno jest wystawiony i chodzi tu tylko o ponowną aktywację oferty?

trace-id: b1985b8a31c5986a

**Comment by MaciejFrackowiak** [comment]
Podczas aktywacji oferty jest ona walidowana - w Twoim przypadku brakuje w niej obowiązkowego dla kategorii 90061 parametru, dlatego nie możemy pozwolić na wznowienie oferty bez uzupełnienia brakujących danych.

**Comment by DamianKAtomStore** [comment]
W jaki sposób więc została ona wystawiona za pierwszym razem?

**Comment by MaciejFrackowiak** [comment]
Parametr Waga produktu (213906) został uznany jako obowiązkowy od dnia 15.01.2024, czyli już po dacie ostatniego wznowienia tej oferty przez Ciebie.
