### ISSUE TITLE
błędna kategoria

### ISSUE THREAD

**Issue by ArturBakAxl** [allegro/allegro-api#8443]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

korzystam z zasobu [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getProductOffer)
nr aukcji 15124415871
w odpowiedzi dostaję nr kategorii **66781** (czyli nadrzędną) w stosunku do tego co jest na https://allegro.pl/oferta/odwagi-pinku-15124415871, czyli **66791** (kategoria ostatniego rzędu)

**Comment by AureliuszBrussy** [comment]
Kategoria 66791 nie istnieje w drzewie asortymentowym (dla sprzedającego) - jest obecna tylko w drzewie nawigacyjnym (dla kupującego). Kategoria 66781 jest liściem. Nie mamy tutaj żadnego błędu.  

Kategorie drzewa asortymentowego sprawdzisz za pomocą [GET /sale/categories](https://developer.allegro.pl/documentation#operation/getCategoriesUsingGET).
