### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by PoshlandPro** [allegro/allegro-api#8446]
Proszę o aktywację konta na sandbox login: squawks

Pozdrawiam.
Damian.

**Comment by MaciejFrackowiak** [comment]
Proszę dokończ proces aktywacji tj. prześlij dowolne pliki jako dokumenty oraz wykonaj przelew weryfikacyjny korzystając z naszego symulatora - zrobisz to w zakładce [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by PoshlandPro** [comment]
Zrobione.

**Comment by MaciejFrackowiak** [comment]
Konto aktywowane.

**Comment by PoshlandPro** [comment]
Dziękuję.
