### ISSUE TITLE
Downloading image from URL returned the following HTTP status code: 403 FORBIDDEN

### ISSUE THREAD

**Issue by WebFunly** [allegro/allegro-api#8447]
Hi, we want to use the BaseLinker connector between the woocemmerce e-shop and Allegro. When trying to list the menu, it gives us an error: "Downloading image from URL 'https://angel-wings.cz/wp-content/uploads/2023/09/chlupate-ruzovo_tmavesede-1.png' failed. The server returned the following HTTP status code: 403 FORBIDDEN and response text: ''. (DownloadError.Forbidden productSet[0].product.images)"

BaseLinker sees the following images and has downloaded them to itself. 1 product went well for us at allegro. Another not.

We tried enabling everything on the e-shop and nothing changed, while the image can be used on other pages as well. Can't think of what the problem could be? BaseLinker Support has asked us to try to contact you.

BaseLinker referred me to you after the online call where we went through it together. He probably doesn't know what could be causing it. Thank you for your help. Lukas

**Comment by MaciejFrackowiak** [comment]
The issue is connected to IP addresses - the domain owner "[angel-wings.cz](http://angel-wings.cz/)" has to unlock download files from its server for the Allegro IP addresses.
