### ISSUE TITLE
Dodawanie zdjęcia do oferty - nie z zewnętrznego serwisu

### ISSUE THREAD

**Issue by MGabala** [allegro/allegro-api#8448]
Witam, pracuje nad integracją z Allegro.API i zastanawiam się czy jest możliwość **wysłania plików** zamiast zaciągać zdjęcia z zewnętrznego serwisu?

![obraz](https://github.com/allegro/allegro-api/assets/82496006/f5d723e6-63e5-47eb-ae54-878249124cab)

**Comment by MaciejFrackowiak** [comment]
W przypadku zasobów /sale/product-offers wystarczy wskazać miejsce plików na serwerze zewnętrznym i my je automatycznie dodamy do ofert. Nie ma natomiast opcji dołączenia realnych plików do requestu i wysłania ich jednocześnie.

**Comment by MaciejFrackowiak** [comment]
Oferta musi posiadać minimum jedno zdjęcie - dopóki jest to szkic nie musisz określać tablicy "images". Aktualizować zdjęcia zawsze możesz korzystając z [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers).

**Comment by MGabala** [comment]
Czy mogę wysłać wtedy pliki a nie link do zdjęcia?

**Comment by MaciejFrackowiak** [comment]
Oczywiście nie.
