### ISSUE TITLE
Data płatności różnica miedzy rapartem z konta a API

### ISSUE THREAD

**Issue by MDziubek** [allegro/allegro-api#8449]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Pobieram dane o płatnosciach korzystając z endpointu: payments/payment-operations, wszystko działa i API zwraca dane.
Podczas weryfikacji przez użytkownika doszedłem do tego że mam rózne daty. Response z API (https://api.allegro.pl/payments/payment-operations?payment.id=70eff765-a901-11ee-8839-870b87a2e5f1):

```json
{
  "paymentOperations": [
    {
      "type": "CONTRIBUTION",
      "group": "INCOME",
      "wallet": {
        "paymentOperator": "PAYU",
        "type": "AVAILABLE",
        "balance": {
          "amount": "343.99",
          "currency": "PLN"
        }
      },
      "occurredAt": "2024-01-01T23:58:27.507Z",
      "value": {
        "amount": "93.99",
        "currency": "PLN"
      },
      "marketplaceId": "allegro-pl",
      "payment": {
        "id": "70eff765-a901-11ee-8839-870b87a2e5f1"
      },
      "participant": {
        "id": "1",
        "companyName": null,
        "login": "*****",
        "firstName": "F**p",
        "lastName": "*****k",
        "address": {
          "street": "ul. *******",
          "city": "******",
          "postCode": "11-111"
        }
      }
    }
  ],
  "count": 1,
  "totalCount": 1
}
````

Jak mozna stwierdzić jest to 1 styczeń 2024, użytkownik weryfikuje zaimportowane dane przez strone konta:
https://allegro.pl/moje-allegro/sprzedaz/srodki-i-historia-operacji?dateFrom=2024-01-01&dateTo=2024-01-02

i tam widzi datę 2 stycznia 2024:

![image](https://github.com/allegro/allegro-api/assets/9452524/c55eae89-4235-43a6-acce-d47359e67bf3)

Skąd rozbieżność pomiędzy tymi 2 wynikami?

**Comment by MaciejFrackowiak** [comment]
Zauważ proszę, że w API zwracamy czas wystąpienia zdarzenia wg czasu Zulu, czyli +0 względem strefy GMT. Natomiast serwis WWW uwzględnia bieżący czasy występujący w Polsce, czyli +1.
