### ISSUE TITLE
Dostęp do swoich zamówień

### ISSUE THREAD

**Issue by mariolos** [allegro/allegro-api#8451]
Czy api umożliwia dostęp do szczegółów swoich zamówień? Jako kupujący chciałbym mieć podgląd do szczegółów wszystkich swoich zamówień.

Pozdrawiam

**Comment by jezewskiBNetrox** [comment]
> Czy api umożliwia dostęp do szczegółów swoich zamówień? Jako kupujący chciałbym mieć podgląd do szczegółów wszystkich swoich zamówień.
> 
> Pozdrawiam

@mariolos Nie, API służy głównie sprzedającym i nie udostępnia zasobów do podglądu zamówień kupujących.

**Comment by AureliuszBrussy** [comment]
Tak jak wspomniał @jezewskiBNetrox - aktualnie nie udostępniamy takiego zasobu.
