### ISSUE TITLE
Brak dostepu do zasobu getProductOfferProcessingStatus pomimo ważnego tokena

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#8452]
Witam,
Próbuje ściągnąć status operacji poprzez zasób getProductOfferProcessingStatus
Pomimo tego, że token jest ważny i zawiera odpowiednie dostępy otrzymuję błąd "Full authentication is required to access this resource"
Prosiłbym o sprawdzenie dlaczego tak jest (trace-id=3a6a0e8fcd09eed)

**Comment by AureliuszBrussy** [comment]
Sprawdź, czy na pewno korzystasz z access tokena właściwego użytkownika (do którego należy ta oferta). Możesz rozkodować swój token - wpisz w wyszukiwarce “decode jwt token” i na jednej z dostępnych stron zweryfikuj wartość user_name po wklejeniu swojego tokena.

Upewnij się, czy korzystasz z access tokena typu bearer-token-for-user - wygenerowanego w procesie [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/zlq9e75GdIR#device-flow). 

Jeżeli żadne z powyższych nie rozwiązuje Twojego problemu - sprawdź swój kod i upewnij się, że nie formatujesz w jakiś niewłaściwy sposób tokena.

**Comment by AureliuszBrussy** [comment]
Jeszcze raz się przyjrzałem możliwym powodom: prawdopodobnie jest to brak nagłówka Authorization wraz z tokenem lub brak tokena w tym nagłówku. Wygląda na to, że jest on "gubiony" po Twojej stronie na jakimś etapie w momencie przekierowania z 303 ze sprawdzania statusu.

**Comment by dol1234** [comment]
Dziękuję za odpowiedz, token jest poprawny i działa na inych zasobach (i tak jak napisałem sprawdziłem po jego rozkodowaniu czy zawiera odpowiednie scope). W tokenie nie ma nazwy użytkownika tylko jego numeryczna interpretacja. Sprawdziłem w Fiddlerze i nagłówki Authentication, Accept oraz ContnetType wychodzą poprawnie.
