### ISSUE TITLE
Problem produktyzacji

### ISSUE THREAD

**Issue by janpalko97** [allegro/allegro-api#8456]
Dzień dobry. Mamy problem z produktem. Jego głównym materiałem jest poliester. Jeśli ustawiamy parametr: Materiał dominujący na wartość poliester dostajemy błąd: 

trace-id: da4f4fc91ab15e8f

PARAMETER_MISMATCH
Wskazany produkt istnieje. Przesłany parametr `Materiał dominujący` o wartości `poliester(201017_2377)` nie pasuje do parametru produktu `elastan(201017_2381)`.

Co możemy zrobić w tej sytuacji?

**Comment by AureliuszBrussy** [comment]
Na podstawie przesłanych w requeście parametrów rozpoznaliśmy, że mamy już ten produkt w naszym Katalogu Produktów, jednak jeden z parametrów ma inną wartość. Rozpoznany produkt ma id: `d7301417-e2ec-4bca-b407-e10b79d271dd`. Możesz odczytać dane produktu za pomocą [GET /sale/products/{productId}](https://developer.allegro.pl/documentation#operation/getSaleProducts). 

Są 2 opcje:
1. Możesz po prostu zmienić wartość na sugerowaną przez nas. 
2. Jeżeli uważasz, że w naszym Katalogu Produktów jest błąd, możesz przekazać sugestię zmiany za pomocą [GET /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation#operation/productChangeProposal) lub [przez formularz](https://allegro.pl/moje-allegro/sprzedaz/produkt/zglos-blad/d7301417-e2ec-4bca-b407-e10b79d271dd).
