### ISSUE TITLE
Sandbox - 403 Forbidden do zasobów sale/offers, sale/offer-tags

### ISSUE THREAD

**Issue by XardasLord** [allegro/allegro-api#8457]
Posiadam następujący token wygenerowany do autoryzacji w Allegro Sandbox:

eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiIxMDYxNjI2NTMiLCJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6cmVhZCIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6cmVhZCIsImFsbGVncm86YXBpOnNoaXBtZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpzaGlwbWVudHM6cmVhZCIsImFsbGVncm86YXBpOm9yZGVyczp3cml0ZSJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9hbGxlZ3JvLnBsLmFsbGVncm9zYW5kYm94LnBsIiwiZXhwIjoxNzA3Nzg0NTg3LCJqdGkiOiIwZGYwMzc5NC0wYzAyLTQ4OTUtOTYyZC0wYTQwNzhmNGY4YjYiLCJjbGllbnRfaWQiOiI3MGIzNTJkZTlhYjc0YjRjOWIwZjRjMjM5MjY4OWVkOCJ9.dggin5GDSs1g03W1Aq7rM8W7SVSSHTiXxP8frCgEmohvfUJKeH38_mTer7Do-4nms_EjASB5T2rk0WkANO_5kvX5gtWGes0RmEd4etTErfiU3RfjgGZHv5Zv9X0aEIXPF5T4D5BkmENzsH5QEeq85TrTr-8-BlCypWOaSRd9VxlBFe1MX7rAv0mpXgrla0m4E2zbiB9e0sgPrO-yvngI0f_A60QWkd0p1QpDhBBQshPCtGmbCty7CaIYbOa6oq4ev7XWkYFfwhEHYFoN2b3Am-HbUwioQmVl63szZcChuMxllCkV6AQ8A83wmwwz9hydE2lbQ03FlzpEeffYQVn1gUTH947kv6BP1OIW18ntU7mNg_srr71NWRqtblMf3_RNlwQIXAelJGE4Hh41B9XGLB5xRbdH6Pe3TBNqH-cb_H1BHGK0g3gTvNWY4LdlNq_GaFQvTYFAcUnWRqSryiAkBrRURHRmGAfnMDiGf788vZ-ypOqZdhgwSamlgo_q_QMvG4VmjdlfO_mi3sBdLCxwpkIMrBkUrXPnYBoNf_liXO1QCphMtpPgwqQeqyr1x99CI22V3x4DV0TNUfE3sZKp75j9SlqKiAxE8BqnaoU8TKF2W184lbu7fwJLBhGkWCJXkoLlbzYYBPjMILCAEHmtisEPB3re65uPRGc-YuviEwk

Dostaję błąd 403 na poniższych zasobach, pomimo poprawnego ustawienia scopu do zasobów `allegro:api:sale:offers:read`  oraz `allegro:api:sale:settings:read` zgodnie z dokumentacją Allegro API.:
```
sale/offer-tags
sale/offers
```

Na produkcyjnym środowisku Allegro wszystko działa OK pomimo dokładnie tych samych ustawień.

Konto Allegro Sandbox: **xardaslord**

Bardzo proszę o pilną inwestygację

**Comment by AureliuszBrussy** [comment]
Tagi ofertowe dostępne są dla kont z aktywnym abonamentem. Abonament możesz aktywować w [zakładce Abonamenty](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/abonamenty).

**Comment by XardasLord** [comment]
@AureliuszBrussy dzięki. 

Przy okazji mam pytanie, ponieważ z uwagi na ograniczenie listy unikalnych tagów ofertowych (limit 200 unikalnych tagów) potrzebuje w naszym systemie zmienić sposób wyciągania pewnych identyfikatorów że wszystkich naszych aukcji. Dotychczas korzystaliśmy z tagów ofertowych jednak ze względu na ten limit jesteśmy zmuszeni zmienić podejście - chyba że istnieje możliwość zwiększenia tego limitu?

A mianowicie chcielibyśmy zapisywać teraz te nasze wewnętrzne identyfikatory w polu "Kod producenta". W jaki sposób najwydajniej będzie zaciągnąć na starcie systemu wszystkie identyfikatory (kod producenta) z naszych aukcji? Niestety zauważyłem, że szczegóły oferty są dopiero po podaniu ID oferty, więc pierwsze co przychodzi mi do głowy to zaczytać wszystkie oferty a następnie w pętli odpytywać o szczegóły każdej z nich, aby pobrać kod producenta (słabo jeśli chodzi o wydajność). Czy istnieje jakiś lepszy sposób na to?

**Comment by AureliuszBrussy** [comment]
W polu "Kod producenta" powinny być przekazywane faktyczne kody producenta - jest to istotne z punktu widzenia tworzenia produktów i używania naszego Katalogu Produktów. Zewnętrzne identyfikatory powinniście przechowywać w polu `external.id`. Pole to możesz odczytać pobierając listę ofert [GET /sale/offers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET).

**Comment by XardasLord** [comment]
A jest możliwość wpisania kodu do pola external.id z poziomu portalu Allegro?

**Comment by AureliuszBrussy** [comment]
Tak, jest to pole "Sygnatura" znajdujące się pod polem tytułu oferty.

**Comment by XardasLord** [comment]
Dzięki wielkie za pomoc
