### ISSUE TITLE
Problem z wysyłką GLS - brak formy wysyłki w /parcel-management/delivery-services

### ISSUE THREAD

**Issue by jzby-dev** [allegro/allegro-api#8458]
Dział handlowy włączył na koncie Allegro wysyłkę kurierem GLS, ale https://api.allegro.pl/parcel-management/delivery-services nie zwraca tej formy wysyłki, czy wymagane są jakieś dodatkowe czynności aby można było korzystać z formy wysyłki przez API?

**Comment by AureliuszBrussy** [comment]
Wysyłam z Allegro nie obsługuje GLS - przez nasze narzędzie nie nadasz przesyłki za pomocą tego kuriera. Pozostaje inne narzędzie, np. te bezpośrednio udostępniane przez firmę kurierską.

**Comment by jzby-dev** [comment]
Ok, a co należy przekazać w requeście do GLS żeby wysyłka była rozliczana przez Allegro? To w ogóle jest możliwe? Informacje które dostałem z działu handlowego są dość mętne...

**Comment by jzby-dev** [comment]
Dzięki, teraz wszystko jasne.
