### ISSUE TITLE
Błąd "Podany hash-mail jest niepoprawny" przy zakładaniu wysyłki z poprawnym mailem

### ISSUE THREAD

**Issue by Vekz** [allegro/allegro-api#8459]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Hej,
Mam problem ze zwracanym statusem dla operacji zakładania przesyłki `/shipment-management/shipments/create-commands/` dla commandId: `55c0db79-1038-434a-bf2a-24ca72ad23ae`.
Tytułowy błąd występuje w ścieżce `receiver.email`, lecz po weryfikacji - jest przesyłany poprawny email klienta.

Czy mógłbym prosić o asystę?

**Comment by AureliuszBrussy** [comment]
Płatność dla tego zamówienia nie została zakończona, stąd brak możliwości wygenerowania przesyłki.
