### ISSUE TITLE
Błąd konfigurowania konta WZA

### ISSUE THREAD

**Issue by bart-katowice** [allegro/allegro-api#8461]
Występuje problem:
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Konto Lazienki_eco (na sandboxie)
Przy próbie pobrania listy usług dostaw https://api.allegro.pl.allegrosandbox.pl/shipment-management/delivery-services błąd 422:
{"errors": [{
   "code": "ANOTHER_SERVICE_NOT_AVAILABLE",
   "message": "One of required services is unavailable. Try again later.",
   "details": "One of required services is unavailable. Try again later.",
   "path": null,
   "userMessage": "Jeden z wymaganych serwisĂłw, do poprawnego dziaĹ‚ania, jest niedostÄ™pny. SprĂłbuj ponownie za moment."
}]}
no i pewnie, co jest powiązane, przy próbie nadania przez weba przesyłki błąd: "Process konfigurowania konta WZA zakończył się błędem. Spróbuj odświeżyć stronę za chwilę lub skontaktuj się z nami w celu weryfikacji tego problemu."

Przykładowe trace-id: b946bf63c7588acf

**Comment by PrzemyslawLukanowski** [comment]
Czy aktywowałeś konto zgodnie z informacją z [instrukcji](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY)?
<img width="603" alt="Zrzut ekranu 2024-02-13 o 07 06 38" src="https://github.com/allegro/allegro-api/assets/51473661/300810bd-4adb-4097-9653-fe44645c2068">

**Comment by bart-katowice** [comment]
Próbowałem. Nie da się dodać niczego do książki adresowej (błąd: Nie udało się pobrać książki adresowej, spróbuj ponownie później.), jak również nie da się nadać przesyłki (Process konfigurowania konta WZA zakończył się błędem. Spróbuj odświeżyć stronę za chwilę lub skontaktuj się z nami w celu weryfikacji tego problemu.)

**Comment by bart-katowice** [comment]
Czy coś udało się stwierdzić? Czy może chodzić o brak weryfikacji firmy? Jeśli tak, to poproszę o weryfikację :-)
![obraz](https://github.com/allegro/allegro-api/assets/72733651/8ee17484-4638-4e71-bf88-82b6162902a6)

**Comment by Lukasz-Zurek** [comment]
@bart-katowice Z naszej perspektywy posiadasz już zweryfikowane konto. Problem dotyczący WZA nadal jednak weryfikujemy. Proszę Cię o cierpliwość.

**Comment by bart-katowice** [comment]
up... temat wciąż aktualny

**Comment by bart-katowice** [comment]
Zadziałało. Dzięki
