### ISSUE TITLE
Nie można pobrać etykiety do stworzonej przesyłki (/shipment-management/label) / niejasny komunikat błędu

### ISSUE THREAD

**Issue by righttway** [allegro/allegro-api#8462]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry,

nie mogę pobrać etykiet do stworzonych przesyłek.
Dla przykładu:

{{
  "id": "43a6c3ad-aef7-481a-ad34-a58f52e973ba",
  "deliveryMethodId": "0aafb43c-e66a-46ec-9cc4-29bb39ebb483",
  "packages": [
    {
      "waybill": "A000F5JH01",
      "type": "PACKAGE",
      "length": {
        "value": 20,
        "unit": "CENTIMETER"
      },
      "width": {
        "value": 16,
        "unit": "CENTIMETER"
      },
      "height": {
        "value": 7,
        "unit": "CENTIMETER"
      },
      "weight": {
        "value": 1,
        "unit": "KILOGRAMS"
      }
    }
  ],
  "insurance": null,
  "cashOnDelivery": null,
  "createdDate": "2024-02-12T17:50:07.063Z",
  "canceledDate": null,
  "carrier": "ALLEGRO",
  "labelFormat": "PDF",
  "additionalServices": [],
  "additionalProperties": {
    "EXTERNAL_CARRIER_WAYBILL": "1Z8359FR6831040530",
    "FIRST_MILE_CARRIER": "UPS"
  }
}}

przy próbie pobrania etykiety dla paczki 43a6c3ad-aef7-481a-ad34-a58f52e973ba dostaje poniższą odpowiedź:

{"errors":[{"code":"ANOTHER_SERVICE_NOT_AVAILABLE","message":"One of required services is unavailable. Try again later.","details":"One of required services is unavailable. Try again later.","path":null,"userMessage":"Jeden z wymaganych serwisów, do poprawnego działania, jest niedostępny. Spróbuj ponownie za moment."}]}

Co robię źle?

P.

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, czy aktywowałeś konto zgodnie z informacją z [instrukcji](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY)?

<img width="603" alt="Zrzut ekranu 2024-02-13 o 07 06 38" src="https://github.com/allegro/allegro-api/assets/51473661/62b9c241-e3fc-4243-a871-ed5305d1003b">

**Comment by righttway** [comment]
Dzień dobry,

poprosiłem klienta żeby to zweryfikował, rzeczywiście coś nie jest tak z kontem. Ma zrobić zgłoszenie gdyż nie może zapisać adresu "Nie udało się dodać danych adresowych, spróbuj ponownie później".
Dodam tylko że działało to wcześniej więc musiały nastąpić jakieś zmiany w między czasie ;)
Dam znać gdy uda się zapisać adres i ponowię próbę pobrania etykiety.

P.
