### ISSUE TITLE
Problem z dodawaniem propozycji produktu

### ISSUE THREAD

**Issue by fabianCyfran** [allegro/allegro-api#8463]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis**

Za pomocą zasobu **/sale/product-proposals** wysłaliśmy propozycję i w odpowiedzi otrzymaliśmy id produktu. Jednak niezależnie od upłyniętego czasu od wysłania propozycji, próba wyszukania tego produktu za pomocą zasobu **sale/products/{productId}** kończy się błędem: **ProductNotFound**

Trace id z zasobu **/sale/product-proposals**: 49a705c4d9816180

**Comment by PrzemyslawLukanowski** [comment]
Produkt został niezwłocznie usunięty po utworzeniu, ponieważ nasz wewnętrzny, asynchroniczny proces walidacji GTIN ustalił, że dany numer GTIN nie jest zweryfikowany przez GS1 - https://www.gs1.org/services/verified-by-gs1/results?gtin=7290108380460.

**Comment by fabianCyfran** [comment]
Powinna być walidacja przed dodaniem produktu i odpowiednia zwrotka, bo ostatecznie nie wiadomo czy faktycznie produkt został pomyślnie utworzony.
