### ISSUE TITLE
Error: Order doesn't belong to seller Nie jesteś właścicielem zamówienia

### ISSUE THREAD

**Issue by KaMisza** [allegro/allegro-api#8465]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 
Podczas nadania przesyłki otrzymuję komunikat Error: Order doesn't belong to seller Nie jesteś właścicielem zamówienia
 "serviceId": "c3066682-97a3-42fe-9eb5-3beeccab840c",
zamówienie utworzone z oferty "offer_id": "7671097163" należącej do tego samego konta, z którego próbuje nadać przesyłkę.

**Comment by PrzemyslawLukanowski** [comment]
Podaj proszę trace-id lub command-id powiązane z operacją, dla której otrzymujesz błąd. Oferta 7671097163 należy do użytkownika ****2333 - [zdekoduj](https://jwt.io/) token, za pomocą którego próbujesz nadać przesyłkę i upewnij się, że w polu `user_name` widnieje to samo id.

**Comment by KaMisza** [comment]
Trace ID 6731057fd58b2658
Token po weryfikacji pokrywa się z user_name z oferty

**Comment by PrzemyslawLukanowski** [comment]
Mail kupującego, który przekazujesz, powiązany jest zamówieniem 1943a2a0-c753-11ee-aed5-2df2dc812ef0, które należy do innego konta (dane wskazują, że jest to Twoje powiązane konto) - dotyczy także dwóch innych ofert niż ta wskazana w zgłoszeniu.
