### ISSUE TITLE
Kody CN w katalogach produktowych

### ISSUE THREAD

**Issue by Marcel10S** [allegro/allegro-api#8466]
Dzień dobry chciałbym zapytać czy udostępniacie gdzieś kody CN w katalogach produktowych? Chciałbym móc je zaciągnąć z api, ale nie mogłem znaleźć takiego zasobu w dokumentacji :D

**Comment by AureliuszBrussy** [comment]
Nie zwracamy kodów CN w naszym publicznym API.
