### ISSUE TITLE
Error: Kod pocztowy odbiorcy jest niedostępny

### ISSUE THREAD

**Issue by Grubyxxx** [allegro/allegro-api#8467]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource

trace_id: 345666743b27f39d url url: GET https://api.allegro.pl/parcel-management/parcel-create-commands/323d4c4d-8437-4c94-882a-556be1e41775

Wysyłam z Allegro Kurier DHL (Allegro pl) - podczas nadawnia przesyłki otrzymuję błąd Error: Kod pocztowy odbiorcy jest niedostępny
Po weryfikacji widzę, że podane kody pocztowe w zamówieniach są prawidłowe,

**Comment by AureliuszBrussy** [comment]
W polu `receiver.postCode` wysłałeś niepoprawną wartość: `26600`, zamiast `26-600`.

**Comment by Grubyxxx** [comment]
Allegro WZA trace_id: 6926e480645d05bc, url: GET https://api.allegro.pl/parcel-management/parcel-create-commands/ffdaf89c-a2a1-4093-b67d-e4b3e5bf27ab - tutaj jest 26-600 i jest ten sam błąd.

**Comment by AureliuszBrussy** [comment]
Z odpowiedzi API Poczty Polskiej wynika, że ten kod pocztowy aktualnie nie jest dostępny. Myślę, że warto zweryfikować kod dla podanego przez kupującego adresu (np. na stronie https://kody.poczta-polska.pl/) lub np. upewnić się co do jego poprawności z kupującym.
