### ISSUE TITLE
Requested hashed mail was not recognized Podany hash-mail jest niepoprawny

### ISSUE THREAD

**Issue by KaMisza** [allegro/allegro-api#8469]
- [x ] z zasobem REST API / with a REST API resource
 
 - Allegro WZA trace_id: d7e0ba9afab0084a, shipping_order_id: 92796, 
 
 - url: GET https://api.allegro.pl/parcel-management/parcel-create-commands/261a05c1-945c-48c1-829f-fb95be902b8c
 
Podczas próby nadania przesyłki otrzymuję zwrotkę Requested hashed mail was not recognized Podany hash-mail jest niepoprawny, według danych pobranych z Allegro dla tego zamówienia  "client_email": "dnn4kfvfce+599952cb5@allegromail.pl" pokrywa się z client_mail wysyłanym przez nas dla przesyłki

**Comment by AureliuszBrussy** [comment]
Zamówienie zostało anulowane nie jest w statusie READY_FOR_PROCESSING), dlatego nie można wygenerować przesyłki.
