### ISSUE TITLE
Produkcyjne api nie dodaje ofert

### ISSUE THREAD

**Issue by Arkowsky** [allegro/allegro-api#847]
Witam serdecznie:

na produkcyjnym allegro na loginie:
**CoffeeDesk_pl**
nie dodaje nam ofert - nie widzę ich w panelu admina(np. Moje oferty).

Dzisiaj dodaliśmy już 94 oferty i one są widoczne ale dodaliśmy jeszcze z 50 i dostaliśmy odpowiedź od api z prawidłowym responsem, chociaż nie widać tych ostatnich 50 w "Moje oferty".
Tak jakby coś stanęło, chociaż odpowiedź z api była prawidłowa.

Zatem wydaje się, że oferty czekają w kolejce na dodanie po Waszej stronie? Czy tak jest?
A może Wasza kolejka stanęła z jakiegoś powodu?

Podaję przykładową nazwę produktu, który wystawiamy:
teapigs Chamomile Flowers 50 piramidek

Z góry dziękuję za pomoc.

**Comment by PawelTaberski** [comment]
Co to znaczy, że otrzymałeś prawidłową odpowiedź. Czy sprawdzałeś status publikacji tych ofert przy pomocy zasobu: GET na zasobie /sale/offer-publication-commands/{commandId}/tasks ? Jeśli tak jaką odpowiedź otrzymujesz?

**Comment by Arkowsky** [comment]
Już rozumiem. Oferty się dodają jako draft - dostają identyfikator ale mają błędy walidacji. Obsłużyłem to po naszej stronie.
Dziękuję. Zamykam.
