### ISSUE TITLE
Proszę o ponowną aktywację/weryfikację konta

### ISSUE THREAD

**Issue by SylwesterZarebski** [allegro/allegro-api#8470]
Poproszę o aktywację/weryfikację ponad rocznego konta sandboksowego, na którym nagle przestała działać sprzedaż.
Login: sylwester.zarebski@prog.pl

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem to konto, jednak jest to konto zwykłe - jeśli planujesz wystawiać oferty lub zarządzać nimi przez API, musisz posiadać konto firmowe. W takim przypadku możesz przekształcić obecne konto lub założyć nowe.

**Comment by SylwesterZarebski** [comment]
Dziękuję bardzo.
