### ISSUE TITLE
Sandbox account activation

### ISSUE THREAD

**Issue by SunkovyChlebiczek** [allegro/allegro-api#8471]
Hello,
I need to activate my sandbox account, so I can start to create offers.

Client:106795500

Thank you!

**Comment by PrzemyslawLukanowski** [comment]
I've activated your account, but keep in mind that you've chosen a regular type of account. To list and manage offers via API you'll need a company account - you can transform your current account or create a new one.

**Comment by SunkovyChlebiczek** [comment]
Hello Przemysław, thank you for activation and reminder. Can you transform it into bussines accout, or do I need to do it myself? If yes, where? Because it seems like bussines account to me. Thank you!

**Comment by SunkovyChlebiczek** [comment]
Hello, I´ve found it. Can you activate my business account? Thanks :)

**Comment by PrzemyslawLukanowski** [comment]
One step remains :) Please set up payouts via t[his tab](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat), then I'll be able to activate the account. Of course, you can use a fake number account, cause there are no real payments on Sandbox.

**Comment by SunkovyChlebiczek** [comment]
Should be done :)

**Comment by PrzemyslawLukanowski** [comment]
Account activated :)

**Comment by PrzemyslawLukanowski** [comment]
Sure, the link to allegro.cz sandbox is - https://allegro.cz.allegrosandbox.pl. Let me know if your account requires activation after registration.

**Comment by SunkovyChlebiczek** [comment]
Thank you. I´ll let you know, if I need help.

**Comment by SunkovyChlebiczek** [comment]
Hello, can you check if our sandbox is activated for bussines account? SCandbox
Thank you!

**Comment by PrzemyslawLukanowski** [comment]
Hello, it's not activated, but this time I need a little more time to investigate what is wrong, cause I cannot activate it manually. Please be patient, I will return with an answear.

**Comment by PrzemyslawLukanowski** [comment]
Could you please send once again the verification transfer?

**Comment by SunkovyChlebiczek** [comment]
Hello Przemysław, transfer should be done. Could you also take a look on account "chlebicek" if it is activated as bussines account? Verification transfer should be "paied" as well. Dzieki.

**Comment by MartaNowaczyk** [comment]
@SunkovyChlebiczek  Yes, it's verified as a business account.

**Comment by PrzemyslawLukanowski** [comment]
@SunkovyChlebiczek Thank you for making the transfer, I've activated the SCandbox account.
