### ISSUE TITLE
Problem z edytowaniem ofert 

### ISSUE THREAD

**Issue by Vandeetta** [allegro/allegro-api#8473]
Przy próbie zmiany ceny oferty otrzymuje 
Error updating product offer: 405 Client Error: Method Not Allowed for url: https://api.allegro.pl/sale/product-offers/
używam metody patch tak jak w dokumentacji 
response = requests.patch(url, headers=headers, json=payload)

**Comment by PrzemyslawLukanowski** [comment]
Prawidłowa ścieżka dla metody PATCH to https://api.allegro.pl/sale/product-offers/{offerID} - po '/' musicie wskazać, która ofertę należy edytować.
