### ISSUE TITLE
Pobieranie zdjęcia do tworzonej oferty, DownloadError.NotFound

### ISSUE THREAD

**Issue by matecz11** [allegro/allegro-api#8474]
- [x] środowisko testowe 
- [x] zasób REST API
Cześć, próbuję dodać nowy produkt, ale z /sale/product-offers dostaję odpowiedź:
```
<Response [422]>
{'errors': [{'code': 'DownloadError.NotFound', 'message': "Downloading image from URL 'https://cdn.matecz.xyz/img/test2.jpg' failed. Server returned the following HTTP status code: 404 NOT_FOUND and response body: ''.", 'details': None, 'path': 'images', 'userMessage': "Downloading image from URL 'https://cdn.matecz.xyz/img/test2.jpg' failed. Server returned the following HTTP status code: 404 NOT_FOUND and response body: ''."}]}
```
co ciekawe URL jest prawidłowy:
(google colab notebook):
```python
>>> import requests
>>> r = requests.get('https://cdn.matecz.xyz/img/test2.jpg')
>>> print([r.status_code, r.url, r.headers])
[200, 'https://cdn.matecz.xyz/img/test2.jpg', {'Date': 'Wed, 14 Feb 2024 14:23:53 GMT', 'Content-Type': 'image/jpeg', 'Content-Length': '126998', 'Connection': 'keep-alive', 'Last-Modified': 'Wed, 14 Feb 2024 13:07:25 GMT', 'ETag': '"65ccbb0d-1f016"', 'Cache-Control': 'max-age=14400', 'CF-Cache-Status': 'MISS', 'Accept-Ranges': 'bytes', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=N%2BZpbNQdep6I%2FzAwgHMeUTorhwysGMMfHolKFB2pAdpiFSvM0JhXBKOJiBD1FpO95jlkhldl0W7twlM5sUB%2FLLT50vcaf%2Fzm21AVrJFebbVIeoUTMz2aAEQbVSd7KmTOIA%3D%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '8555f8b4392c4584-ATL', 'alt-svc': 'h3=":443"; ma=86400'}]
```
```
nginx logs
2400:cb00:73:1024::ac44:8a58 - - [14/Feb/2024:12:06:32 +0100] "GET /img/test2.jpg HTTP/1.1" 404 153 "-" "Allegro-ImageDownloader/1.0"
2400:cb00:646:1024::ac45:4744 - - [14/Feb/2024:15:23:53 +0100] "GET /img/test2.jpg HTTP/1.1" 200 126998 "-" "python-requests/2.31.0"
```
cloudflare tuneluje ruch, ponieważ mam tylko na ipv6 port 80 dostępny (VPS).
[test2.jpg](https://cdn.matecz.xyz/img/test2.jpg)

**Comment by PrzemyslawLukanowski** [comment]
Wygląda na to, że komunikat jest prawidłowy - nie możemy odnaleźć zdjęcia pod tym adresem, dlatego zwracamy 404 Not Found. Po wejściu w link wyświetla się:

<img width="260" alt="Zrzut ekranu 2024-02-14 o 16 29 52" src="https://github.com/allegro/allegro-api/assets/51473661/5d48cf15-4843-42eb-8fc0-a32b0855e232">

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć tego błędu - zarówno na produkcji, jak i Sandboxie, otrzymuję w odpowiedzi prawidłowy link ze zdjęciem. Czy możesz powtórzyć operację? Jeśli problem się powtarza, prześlij proszę przykładowe trace-id. Czy dla innego przykładowego adresu otrzymujesz podobny błąd?

**Comment by PrzemyslawLukanowski** [comment]
Przyczyną jest wielka litera na początku `SellingMode`, powinno być `sellingMode`.

**Comment by matecz11** [comment]
Jak napisałeś tak zadziałało, ale jeszcze mam ostatnie pytanie;
w productSet.images daje zdjęcie, które chciałbym żeby było zdjęciem produktu
```
   { 'productSet': [{
        'product': {
            'category': {
                'id': '112627'
            },
            'name': 'Sos 1 testowanie',
            'images': ['https://cdn.matecz.xyz/img/test2.jpg'],
...}],
    'images': ['.../test1.jpg', '.../test2.jpg', ...],
}
```
natomiast zdjęciem produktu/ pierwszym zdjęciem jest test1.jpg. Jak to zmienić? Kolejność zdjęć w liście ma znaczenie?

**Comment by Lukasz-Zurek** [comment]
Zdjęciem głównym zawsze będzie pierwsze zdjęcie przesłane w tablicy **images** i tylko tutaj kolejność ma znaczenie.

**Comment by matecz11** [comment]
Znowu dostaję
```
{'errors': [{'code': 'DownloadError.NotFound', 'message': "Downloading image from URL 'https://cdn.matecz.xyz/img/footer_1.jpg' failed. Server returned the following HTTP status code: 404 NOT_FOUND and response body: ''.", 'details': None, 'path': 'images', 'userMessage': "Downloading image from URL 'https://cdn.matecz.xyz/img/footer_1.jpg' failed. Server returned the following HTTP status code: 404 NOT_FOUND and response body: ''."}]}
```
pomimo, iż zdjęcie jest.
![image](https://github.com/allegro/allegro-api/assets/160010431/a93bf51a-1f7b-4695-b7d0-7dc42d02c7ad)
![image](https://github.com/allegro/allegro-api/assets/160010431/cdfb3c5f-1371-4be0-b6a8-eeafa2aba012)

Wyczyściłem cache CloudFlare i nie ma dalej pomysłu co jest nie tak. 
linki do zdjęć: (linki bezpośrednio z mojego CDN)
![image](https://cdn.matecz.xyz/img/8032942645508.jpg)
![image](https://cdn.matecz.xyz/img/8032942645508_cat.png)
![image](https://cdn.matecz.xyz/img/logo_1.jpg)
![image](https://cdn.matecz.xyz/img/footer_1.jpg)
```
>>> print(d['images'])
['https://cdn.matecz.xyz/img/8032942645508.jpg', 'https://cdn.matecz.xyz/img/8032942645508_cat.png', 'https://cdn.matecz.xyz/img/logo_1.jpg', 'https://cdn.matecz.xyz/img/footer_1.jpg']
```

**Comment by Lukasz-Zurek** [comment]
@matecz11 Sprawdzamy to. Jak tylko uzyskamy szczegóły, wrócę do Ciebie z informacją.

**Comment by Lukasz-Zurek** [comment]
@matecz11 Doprecyzuj jeszcze proszę kiedy dokładnie otrzymałeś powyższe błędy dotyczące zdjęć? W miarę możliwości prześlij proszę przykładowe trace-id wywołania.

**Comment by matecz11** [comment]
@Lukasz-Zurek podczas metody POST dla zasobu /product-offers podczas dodawania nowego produktu. W niedzielę, nie zmieniając nic po stronie CDN ani wysyłanego słownika, udało się bez problemu. Nie znam przyczyny takiego zachowania i ciężko jest mi je odtworzyć

**Comment by Lukasz-Zurek** [comment]
@matecz11 A czy jesteś w stanie określić kiedy (chodzi o datę) dokładnie wystąpiły błędy? Wspomniałeś tylko, że w niedzielę udało się już bez problemu. Chcielibyśmy namierzyć problem.

**Comment by matecz11** [comment]
@Lukasz-Zurek ok 15 minut przed tą wiadomością:  https://github.com/allegro/allegro-api/issues/8474#issuecomment-1948395340

**Comment by Lukasz-Zurek** [comment]
@matecz11 Dziękuję. Przekazałem te informacje dalej do analizy.

**Comment by Lukasz-Zurek** [comment]
@matecz11 Dziękuję, przekazałem dalej.

**Comment by Lukasz-Zurek** [comment]
@matecz11 Od od 2024-02-21 23:50:07.875 zdjęcia pobierają się poprawnie.

Natomiast wcześniej, bo 2024-02-21 14:28:59,477 serwer zwrócił 404 i takie nagłówki:

`'Date': 'Wed, 21 Feb 2024 13:28:59 GMT', 'Content-Type': 'text/html', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=14400', 'CF-Cache-Status': 'MISS', 'Report-To': '{"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v3?s=g3CzpAiasrTwauldl6Rj6tBU%2BBUspzlomhV8zZCDCoiwxr3fl6YLDx%2Btm5BA00dQZdCb6BDdvMFUaJ8mN47wt%2BqVmZUNEnOXvvWNeH3ojfu8XF2g2WyzAnhe7xFRWJ9BZQ%3D%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Vary': 'Accept-Encoding', 'CF-RAY': '858a840958691655-WAW', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400'`

Być może to problem z cachce Cloudflare, być może coś innego. Musisz to zweryfikować po swojej stronie. 

My problemu po naszej stronie nie potwierdzamy.
