### ISSUE TITLE
GET /sale/user-ratings przyznaje dostęp za pośrednictwem bearer-token-for-application

### ISSUE THREAD

**Issue by vitalijr2** [allegro/allegro-api#8475]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

[**GET** `/sale/user-ratings`](https://developer.allegro.pl/documentation#operation/getUserRatingsUsingGET) przyznaje dostęp za pośrednictwem **bearer-token-for-application**, podczas gdy powinien być dostępny tylko za pomocą **bearer-token-for-user**

Miałem problemy z dostępem do `/sale/offers`, jednocześnie zauważyłem, że `/sale/user-ratings` jest dla mnie dostępny.

Zacząłem szukać rozwiązania i znalazłem tam #8328, gdzie [odpowiedź mówi](https://github.com/allegro/allegro-api/issues/8328#issuecomment-1906130785), że zasoby, w których wymagany jest **bearer-token-for-user**, należy uzyskać tylko poprzez **Device flow**, natomiast zasoby, w których **bearer-token-for-application** jest wymagane są dostępne za pomocą tokena uzyskanego w ramach **Client Credentials flow**. Sprawdziłem zasób `/me`, który powinien być również dostępny poprzez **bearer-token-for-user** i wszystko jest z nim w porządku.

**Comment by vitalijr2** [comment]
**/sale/user-ratings**

```http
https://api.allegro.pl/sale/user-ratings
HTTP/2 200 
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
trace-id: 456aa036ed76eba9
date: Wed, 14 Feb 2024 18:57:42 GMT
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json
content-length: 14
x-frame-options: DENY
strict-transport-security: max-age=15552000
```
```json
{
   "ratings":[
      
   ]
}
```

**/me**

```http
https://api.allegro.pl/me
HTTP/2 403 
trace-id: fee195b346f3463d
content-type: application/json; charset=utf-8
content-length: 145
date: Wed, 14 Feb 2024 19:00:31 GMT
x-frame-options: DENY
strict-transport-security: max-age=15552000
```
```json
{
   "errors":[
      {
         "code":"AccessDenied",
         "message":"Access is denied",
         "details":null,
         "path":null,
         "userMessage":"No access to the specified resource."
      }
   ]
}
```

**Comment by Lukasz-Zurek** [comment]
@vitalijr2 Dziękuję Ci za zwrócenie na to uwagi. Wyjaśniam ten temat z zespołem odpowiedzialnym za tę funkcjonalność.
