### ISSUE TITLE
Problem z logowaniem "device flow" poprzez allegro API w aplikacji w technologii blazor korzystającej z przeglądarki w trybie DEBUG 

### ISSUE THREAD

**Issue by Kamys85** [allegro/allegro-api#8476]
Występuje problem:
 - [X] z logowaniem lub autoryzacją / with login or authorization

Opis
Obecnie pracuję nad aplikacją blazor, która korzysta z usług allegro API. Niestety problem jest już od samego początku, bowiem podczas logowania. Poniżej opiszę problem logowania w trybie, którego wybrałem, a mianowicie "Device flow".
1. Uruchamiam przeglądarkę w trybie DEBUG dla mojej aplikacji
Parametry, z którymi przeglądarka została uruchomiana to: 
```
"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-renderer-backgrounding --disable-sync --metrics-recording-only --no-first-run --no-default-browser-check --user-data-dir=C:\Users\kamys\AppData\Local\Microsoft\VisualStudio\17.0_cf4ed014\WebTools\90107F59_8A1A4734 about:blank --remote-debugging-port=0
```
2. Wysyłam zapytanie o token weryfikacyjny: https://allegro.pl/auth/oauth/device?client_id=xxx
3. Otrzymuję odpowiedź 
```
{
  "device_code": "ErJZ2f86yjw6bcJbyv32C3DAa9xDnPov",
  "expires_in": 3600,
  "user_code": "pmn7qncq8",
  "interval": 5,
  "verification_uri": "https://allegro.pl/uzytkownik/bezpieczenstwo/skojarz-aplikacje",
  "verification_uri_complete": "https://allegro.pl/uzytkownik/bezpieczenstwo/skojarz-aplikacje?code=pmn7qncq8"
}
```
4. Na nowej karcie przeglądarki wpisuję adres https://allegro.pl/uzytkownik/bezpieczenstwo/skojarz-aplikacje?code=pmn7qncq8
5. I tu problem, bowiem albo zostaję zablokowany albo jest monit o potwierdzenie, że jestem człowiekiem, który niestety nie prowadzi do sukcesu (czasem pojawia się też stronka logowania, która jednak szybko znika i pojawia się stronka, że zostałem zablokowany)

PONADTO:
Zauważyłem, że również samo standardowe logowanie w przeglądarce w trybie DEBUG przy użyciu loginu i hasła nie przechodzi. Pojawia się stronka, że zostałem zablokowany, przy czym adresem, widocznym w przeglądarce jest: https://allegro.pl/logowanie?origin_url=%2F

**Comment by Lukasz-Zurek** [comment]
Jest to prawidłowe zachowanie. Tego typu operacje wykonywane na allegro.pl w ramach przeglądarki w trybie debug mogą prowadzić do wspomnianej blokady po naszej stronie.
