### ISSUE TITLE
Błąd przy tworzeniu listu przewozowego DPD Pickup

### ISSUE THREAD

**Issue by aszymkowiak** [allegro/allegro-api#8477]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,
od poniedziałku przy próbie utworzenia przesyłki dla "Allegro Odbiór w Punkcie DPD Pickup" otrzymuję błąd przy pobieraniu status przesyłki: 

Kroki jakie wykonuje:

1. Utworzenie listu przewozowego wysyłając zapytanie na endpoint: "parcel-management/parcel-create-commands/(commandID)"
 przy pomocy methody PUT. W tym miejscu otrzymuję status zwrotu 201 (Created)
trace-id: d7f30c7e17ddb7c2
2. Pobranie statusu listu przewozowego przy pomocy methody GET na endpoint "parcel-management/parcel-create-commands/(commandID)". Tutaj otrzymuje status zwrotu 200 (OK) z odpowiedzią:
{
    "id": "",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Processing error",
            "details": null,
            "path": "",
            "userMessage": "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."
        }
    ]
}
trace-id: 524ad772d82165bc

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, błąd, który widzimy po naszej stronie, to "Maksymalne wymiary przesyłki z nadaniem lub doręczeniem w Żabce to 60 cm x 40 cm x 40 cm.". Na bieżąco poprawiamy komunikaty zwracane w API, zatem wkrótce i w tym przypadku to doprecyzujemy.

**Comment by aszymkowiak** [comment]
Dziękuję za odpowiedź. Miłego dnia :)

**Comment by aszymkowiak** [comment]
Dziękuję za odpowiedź. Miłego dnia :)

**Comment by aszymkowiak** [comment]
Dziękuję za odpowiedź. Miłego dnia :)
