### ISSUE TITLE
Brak informacji w logu o tym, że klient zgłosił zwrot

### ISSUE THREAD

**Issue by shopelo** [allegro/allegro-api#8478]
Dzień dobry,
Klient dokonał zakupu (WZA - smart) i dokonał płatności. Została wygenerowana etykieta, został zmieniony status zamówienia.
Przesyłka czeka na odebranie przez kuriera (nie została jeszcze odebrana przez kuriera).
Klient zalogował się do Panelu Administracyjnego Allegro i widzi przy zamówieniu informacje "Kupujący zgłosił zwrot" ale w API brak jest informacji.
Proszę o sprawdzenie i informacje czy powinien być jeszcze sprawdzany jakiś zasób ?

ID: fb589d00-cb43-11ee-a5d5-1d160ad77da9
status: "READY_FOR_PROCESSING"

**Comment by PrzemyslawLukanowski** [comment]
W takim przypadku proszę odpytać [GET /order/customer-returns](https://developer.allegro.pl/documentation/#operation/getCustomerReturns) - w zasobie zwracamy informacje o zwrotach wykonanych przez klienta, m.in. identyfikator zamówienia powiązanego ze zwrotem. Więcej informacji znajduje się w [naszym poradniku.](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#zwroty-klienckie)

**Comment by shopelo** [comment]
Dziękuję za informacje.

Czy oznacza to, że procesując tysiące zamówień dziennie – każde zamówienie będziemy musieli odpytywać co x minut czy przypadkiem nie pojawiła się informacja w /order/customer-returns przed odebraniem zamówienia przez kuriera?

Czy nie uważają Państwo, że informacja o tym, że klient dokonał zwrotu przed zmianą statusu na „SENT” (przed nadaniem przesyłki) powinna pojawić się w dzienniku? Brak takiej informacji w dzienniku spowoduje jedynie floodowanie requestami czy przypadkiem klient nie dokonał zwrotu przed wysłaniem?

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem problem, jednak w tej chwili jest to jedyne rozwiązanie. Przekazałem informację do odpowiedniego zespołu - jeśli w przyszłości zdecydujemy się na zmiany na tym polu, będziemy o tym informować.
