### ISSUE TITLE
[Sandbox] ERR_BLOCK_SELL_COMPANY_INFO  - Nie można wystawić oferty

### ISSUE THREAD

**Issue by tomasz-k** [allegro/allegro-api#848]
Witam,
nie mogę wystawić aukcji przez REST API ponieważ dostaję błąd walidacji:
`'validation' => 
  array (
    'errors' => 
    array (
      0 => 
      array (
        'code' => 'VALIDATION_ERROR',
        'message' => 'ERR_BLOCK_SELL_COMPANY_INFO',
        'details' => '',
        'path' => '',
        'userMessage' => '',
      ),
    ),
    'validatedAt' => '2018-10-31T16:21:40.424Z',
  )`

Znalazłem w dokumentacji WEBAPI, że to oznacza że konto typu firma nie jest aktywne, jeśli to znaczy to samo w REST API to nie wiem dlaczego taki błąd się pojawia, skoro dzisiaj mi aktywowano te konto.
Login: tkbit

**Comment by TomekKaczmarek** [comment]
Faktycznie, konto jest aktywne. Próbujesz jednak skorzystać z opcji zarezerwowanych dla konta firma:
https://allegro.pl/pomoc/dla-sprzedajacych/dane-i-ustawienia-konta/kiedy-i-jak-moge-zmienic-status-konta-rKxBgnr6ksx

Rozpocznij proces aktywacji konta firma na środowisku testowym (załącz dowolne pliki) i daj znać, zatwierdzimy weryfikację - wtedy konto otrzyma status firma i będziesz mógł skorzystać z odpowiednich opcji.

**Comment by tomasz-k** [comment]
Zaraz to sprawdzę, wcześniej prywatnie nie zakładałem konta firmowego, więc myślałem że uzupełnienie danych firmowych przy rejestracji wystarczy, ale faktycznie taka walidacja ma sens :) W każdym razie od prawie godziny usiłuję to zrobić i ciągle dostaję 503 i komunikat, że są problemy z serwerem lub czasem mnie przenosi na stronę główną bez żadnego komunikatu, a dane i tak nie są zmienione.

**Comment by TomekKaczmarek** [comment]
@tomasz-k niestety mamy problemy z środowiskiem testowym, nie mogę zaakceptować aktywacji Twojego konta jako konto firma. Pracujemy nad rozwiązaniem tego problemu.

**Comment by tomasz-k** [comment]
Chyba się już udało, bo wszystko działa, dzięki za pomoc
