### ISSUE TITLE
Produkt zniknął z katalogu, ale nie został odpięty od oferty

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#8481]
Mamy ofertę która jest (była) połączona z produktem. Zdaje się, że produkt został usunięty z katalogu, jednak oferta cały czas zachowuje się, jak gdyby była połączona z produktem. Komunikat na stronie nie jest do końca jasny - nie wiadomo, czy jest to tymczasowy problem, czy faktycznie powinniśmy odpiąć obecny produkt i poszukać nowego.
Natomiast przez API, chyba lepiej byłby by po prostu odpiąć produkt

W każdym razie - przy obecnym stanie nie da się zaktualizować ceny w ofercie, bez "przemielenia" również innych parametrów - produktu, dalej pewnie okaże się, że brakuje niektórych parametrów, lub że trzeba również poprawić kategorię.

EDIT: Z poziomu WWW nie da się odpiąć produktu od tej oferty - wyświetla się pusta strona

Przez WWW:
![image](https://github.com/allegro/allegro-api/assets/5887720/9ec189d4-d6b9-4ca9-988d-a0eec6e6de7f)

Przez API:
trace-id: 5f470e2963117082 
PATCH https://api.allegro.pl/sale/product-offers/14211269004
Parametry zapytania: Array ( [sellingMode] => Array ( [price] => Array ( [amount] => 46.99 [currency] => PLN ) ) )
Odpowiedź
{"errors":[{"code":"ProductNotFoundException","message":"Unprocessable Entity","details":null,"path":"productSet[0].product","userMessage":"Nie znaleziono produktu dla wskazanego identyfikatora."}]}

**Comment by Lukasz-Zurek** [comment]
Mogę potwierdzić, że produkt został usunięty z naszej bazy i w tej sytuacji najlepiej będzie jak poprzez API, w trakcie edycji oferty, zmienisz produkt przypisany do oferty.
