### ISSUE TITLE
Problem z parametrami, są wymagane, ale nie pozwala mi ich dodać - generuje błąd

### ISSUE THREAD

**Issue by Avatarus** [allegro/allegro-api#8487]
Witam, mam problem z API, wszystko działało do czasu...
Jeśli próbuje dodać/edytować metodą product-offers z takim zapytanie:
`[name] => Urodlin trójłatkowy (tzw. Indiański banan)
    [language] => pl-PL
    [external] => stdClass Object
        (
            [id] => 4
        )

    [afterSalesServices] => stdClass Object
        (
            [impliedWarranty] => stdClass Object
                (
                    [id] => f4f9ed01-f8c4-4cc2-b153-7c73ca2f6031
                )

            [returnPolicy] => stdClass Object
                (
                    [id] => 76266945-bddd-4e57-a32c-19730c7f6653
                )

            [warranty] => stdClass Object
                (
                    [id] => 46ba6a7d-f2a9-46ae-81a3-572b3676141f
                )

        )

    [delivery] => stdClass Object
        (
            [shippingRates] => stdClass Object
                (
                    [id] => df6e97f6-7fe5-48db-8299-d9b4519af5c6
                )

            [handlingTime] => P1D
        )

    [location] => stdClass Object
        (
            [city] => Pszów
            [countryCode] => PL
            [postCode] => 44-370
            [province] => SLASKIE
        )

    [payments] => stdClass Object
        (
            [invoice] => NO_INVOICE
        )

    [sellingMode] => stdClass Object
        (
            [format] => BUY_NOW
            [price] => stdClass Object
                (
                    [amount] => 78
                    [currency] => PLN
                )

        )

    [category] => stdClass Object
        (
            [id] => 99730
        )

    [parameters] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 16292
                    [valuesIds] => Array
                        (
                            [0] => 16292_14
                        )

                )

            [1] => stdClass Object
                (
                    [id] => 212434
                    [rangeValue] => stdClass Object
                        (
                            [from] => 20
                            [to] => 40
                        )

                )

            [2] => stdClass Object
                (
                    [id] => 233729
                    [values] => Array
                        (
                            [0] => Urodlin
                        )

                )

            [3] => stdClass Object
                (
                    [id] => 25548
                    [valuesIds] => Array
                        (
                            [0] => 25548_8
                        )

                )

        )`
        
(usunąłem dalsze bo nie są ważne dla tego błędu).
Tak samo jeśli dodam pola Producent i nazwa łacińska do sekcji parametry. 
Wywala błąd: 
****Parameter `16292:Rodzaj rośliny` should not be specified as in section `offer`.
Parametry te są wylistowane jak sprawdzam parametry dla kategorii: 99730

Jak ma to działać? Czemu nie mogę dodać nowej oferty/modyfikować istniejącej jeśli podaje parametry?
W roślinach dany produkt (konkretna odmiana rośliny), może mieć setki producentów, różne parametry wysokościowe, wiek itp. 
Jak poprawnie sformułować to zapytanie do /sale/product-offers/ID aby stworzyć produkt z parametrami itp?

**Comment by Lukasz-Zurek** [comment]
@Avatarus Musisz zwrócić uwagę na to, czy dany parametr jest produktowy czy ofertowy. Opisaliśmy to w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#parametry-ofertowe).

Parametr, o którym mowa w komunikacie - tj. 16292 - jest parametrem produktowym, ponieważ, gdy skorzystasz z [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2), w polu **options.describesProduct** posiada on wartość **true**.

**Comment by Avatarus** [comment]
dobrze to w takim razie inaczej. Załóżmy że chce założyć wszystkie aukcje na nowo, mam  czyste konto allegro. Sprzedaje rośliny więc każdy produkt jest inny u każdego producenta. Jaka powinna być droga poprawna?
Najpierw tworzę produkt tą metodą:

**Comment by Avatarus** [comment]
/sale/product-proposals

a następnie na podstawie ID zwróconego, tworzę ofertę poprzez /sale/product-offers
dobrze to rozumiem?
z góry dzięki

**Comment by Lukasz-Zurek** [comment]
@Avatarus Tak, to jedna ze ścieżek. Najlepiej jednak będzie jak w pierwszej kolejności sprawdzisz czy dany produkt istnieje już w naszym katalogu, a jeżeli tak jest - przekazujesz od razu ID produktu (lub numer GTIN) poprzez /sale/product-offers.

Jeżeli produktu nie ma w naszym katalogu - tworzysz go za pomocą /sale/product-proposals, lub przechodzisz od razu do /sale/product-offers i tam przekazujesz wszystkie wymagane parametry. Produkt utworzymy automatycznie na podstawie tych danych. 

Proces wystawiania ofert za pomocą [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) opisaliśmy [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem).
