### ISSUE TITLE
[MAIN SITE RELATED] Localization preferences has a logical error

### ISSUE THREAD

**Issue by havlli** [allegro/allegro-api#8488]
Sorry for posting this in this repo since is not API related, but this issue is related to your main portal. I've already contacted support on the site as well six months ago but looks like till this day it wasn't fixed.

PROBLEM: The localization settings is not handled correctly, "Delivery To" has no effect on the actual availability of shipping, and its set by the "Language" setting instead. Meaning; if set my language of the site from Polish to English the site show only International orders even that "Delivery To" is still Poland. 

For illustration:
![image](https://github.com/allegro/allegro-api/assets/26801047/f339114d-0bde-4946-973c-da0b05c3baab)
![image](https://github.com/allegro/allegro-api/assets/26801047/3cfdb5c1-a0f2-4d97-9822-10321d8523ab)

These two settings should show orders with same availability, only the language of the site should change. Instead all the orders that should be available to poland residents are gone and only the orders with international shipping are shown.

I should add that is related to the search and vendor specific pages where you should see their products, it has no affect to accessing the product page itself and ordering but you need to have direct link to the product page.

I did receive answer long time ago from your Customer Support, which said that is by "design", which makes absolutely no sense, why would company want to not provide their services to all non-polish speakers living in Poland? There's people that will figure this out like me sure, but there will be plenty that will not and just look for the products elsewhere. Sounds like loss of potential profit to me, on top of that is really annoying, but hopefully you can forward this to the right place!

**Comment by AureliuszBrussy** [comment]
I've analyzed this and can't confirm that when you switch "Language" to, for example, "English", it only shows listings with international delivery only. It also shows listings with delivery only to Poland. Maybe I didn't understand something from your argumentation? Can you show some examples?

**Comment by havlli** [comment]
Sure, I have replicated the issue multiple times now in the Private Mode of the browser so the issue is not related to cookies or account-specific settings. Using endpoint `https://allegro.pl/listing?string=myprotein` or simply using the search bar with "myprotein" results in more than 500 offers displayed when the language is set to Polish, when you switch language to English it goes down to less than 35 offers.

![allegroa](https://github.com/allegro/allegro-api/assets/26801047/b7df36c0-1803-430f-841c-9c3cfbc38ec1)

**Comment by AureliuszBrussy** [comment]
This is because we show listings for which we have translations available. We now automatically translate those offers that have defined delivery abroad. Thank you for bringing this to our attention - I have forwarded your point of view to the right team. At this point, I can't promise that things will change soon, but we are aware of what you mean.
