### ISSUE TITLE
Modyfikacja ilości w istniejacej ofercie PUT sale/offers/{}

### ISSUE THREAD

**Issue by Raafal78** [allegro/allegro-api#849]
Witam,
mam pytanie związane z modyfikacją instniejącej oferty. Chcę w istniejącej ofercie zmienić tylko ilość sztuk.

Wiec na początek pobieram szczegóły oferty z : GET sale/offers/{offerId} - i tu jest ok
Później modyfikuję ilość sztuk:  ['stock'] -> available = 3;

Teraz chcę za pomocą PUT sale/offers/7459768055 zrobić modyfikację.
Nawet nie modyfikując żadnego pola  czyli przekazując wynik z GET-a do PUT-a dostaję błędy.
Przypuszczam że chodzi o Header. Ewentualnie czy modyfikując istniejąca aukcję trzeba używać UUID ?

Takie mam dane które wysyłam: 
array (size=7)
  19913 => boolean true
  10002 => string 'https://api.allegro.pl/sale/offers/7459768055' (length=45)
  42 => boolean true
  10023 => 
    array (size=3)
      0 => string 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NDExNTA3ODksInVzZXJfbmFtZSI6IjQxNjgyODE3Iiwia......................z'... (length=612)
      1 => string 'accept: application/vnd.allegro.public.v1+json' (length=46)
      2 => string 'content-type: application/vnd.allegro.public.v1+json' (length=52)
  10036 => string 'PUT' (length=3)
  64 => boolean false
  10015 => string '{"id":"7459768055","name":"Figurka Harry Potter POP! Zgredek Dobby","category":{"id":"100130"},"parameters":{"0":{"id":"11323","valuesIds":{"0":"11323_1"},"values":{},"rangeValue":null}},"ean":null,"description":{"sections":{"0":{"items":{"0":{"type":"TEXT","content":"<p><\/p>\n\n<p>Figurki POP! od firmy Funko to ju\u017c od d\u0142u\u017cszego czasu fenomen na rynku figurek zwi\u0105zanych ze \u015bwiatem film\u00f3w, serial\u00f3w, gier czy komiks\u00f3w. Dzi\u0119ki oryginalnemu designowi figurki POP! ci'... (length=2547)

W odpowiedzi dostaje 400

HTTP/1.1 400 Bad Request
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
**Trace-Id: 823bf784fe2ccdae**

{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers/7459768055","userMessage":null}]}

Jaki powinien być prawidłowy curl który pozwoli na modyfikację ilości w istniejącej ofercie ?

**Comment by TomekKaczmarek** [comment]
Z tego co widzę, nagłówki są poprawne, bo poprawnie wysyłasz Accept i Content-Type. Potrzebny jest jeszcze nagłówek Authorization.

Pamiętaj, że jeśli chcesz zmienić coś w ofercie i przesyłasz żądanie zasobem PUT /sale/offers/{offerId} dane oferty, to muszą one być kompletne. Najlepiej przesłać po prostu wszystkie dane, które otrzymałeś zasobem GET /sale/offers/{offerId} i zmienić odpowiednio wartość w:
`    "stock": {
        "available": 2,
        "unit": "UNIT"
    },`

**Comment by Raafal78** [comment]
Autorization jest na samym początku: 
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NDExNTA3ODksInVzZXJfbmFtZSI6IjQxNjgyODE3Iiwia......................z'

Po wielu próbach już nawet przekazuję wszystko co dostaję z GET /sale/offers/{offerId}  do PUT /sale/offers/{offerId}  i mam cały czas błędy.

Można prosić o dokładną weryfikację tych wywołań
Trace-Id: 823bf784fe2ccdae

**Comment by TomekKaczmarek** [comment]
@Raafal78 OK, sprawdzimy. Napisz jeszcze proszę, czy dla wszystkich ofert masz ten problem, czy tylko dla tej jednej konkretnej?

**Comment by Raafal78** [comment]
Na razie testuję restApi tylko na tej jednej ofercie. Od kilku dni /offers/{offerId}/change-price-commands/{commandId} idzie bez problemów a z tym PUT /sale/offers/{offerId} nie mogę ruszyć.
Dzięki za weryfikację czekam na info.

**Comment by TomekKaczmarek** [comment]
@Raafal78 sprawdziłem tę konkretną ofertę i nie mogę powtórzyć błędu.

Poniżej wrzucam curl z requestem dla PUT (nie zmieniałem liczby sztuk, po prostu sprawdziłem, czy poprawnie przejdzie PUT, bez zmiany danych). Porównaj z treścią Twojego requesta.

`curl -X PUT \
  https://api.allegro.pl/sale/offers/7459768055 \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Authorization: Bearer {token}' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -d '{
    "id": "7459768055",
    "name": "Figurka Harry Potter POP! Zgredek Dobby",
    "category": {
        "id": "100130"
    },
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ],
            "values": [],
            "rangeValue": null
        }
    ],
    "ean": null,
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p></p>\n\n<p>Figurki POP! od firmy Funko to już od dłuższego czasu fenomen na rynku figurek związanych ze światem filmów, serialów, gier czy komiksów. Dzięki oryginalnemu designowi figurki POP! cieszą się ogromną popularnością. Uroczy wygląd figurek urzeka nie tylko zapalonych kolekcjonerów ale także ludzi niezwiązanych wcześniej z tym hobby. Przesłodka Figurka POP! to świetny pomysł na drobny prezent czy upominek. </p>\n<p> </p>\n<p>Figurka POP! Harry Potter - Doby.</p>\n<p>Urocza figurka wykonana jest z winylu.</p>\n<p>Wymiary: ok. 10 cm.</p>\n<p>Całość w oryginalnym opakowaniu.</p>\n<p>Produkt oryginalny, licencjonowany.</p>\n<p>Jak na zdjęciu :)</p>\n<p> </p>\n<p>Mega pomysł na prezent dla każdego fana serii filmów Harry Potter. Sprawdź także pozostałe figurki Funko POP! dostępne w sklepie GeekUP!</p>\n<p></p> "
                    },
                    {
                        "type": "IMAGE",
                        "url": "https://7.allegroimg.com/original/01ac86/edfa2f1c46f0ac47daf30da60c27"
                    }
                ]
            }
        ]
    },
    "compatibilityList": null,
    "images": [
        {
            "url": "https://7.allegroimg.com/original/01ac86/edfa2f1c46f0ac47daf30da60c27"
        }
    ],
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "61.6",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null
    },
    "stock": {
        "available": 20,
        "unit": "UNIT"
    },
    "publication": {
        "duration": null,
        "status": "ACTIVE",
        "startingAt": null,
        "endingAt": null
    },
    "delivery": {
        "shippingRates": null,
        "handlingTime": "PT24H",
        "additionalInfo": "",
        "shipmentDate": null
    },
    "payments": {
        "invoice": "VAT"
    },
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "eefc10e8-8d8c-4cea-8260-b8226cb8f302"
        },
        "returnPolicy": {
            "id": "e858c925-db70-41d9-9af1-ddbbd8f02711"
        },
        "warranty": {
            "id": "01ec5825-4f34-40e3-8f9f-b7e7179e1660"
        }
    },
    "additionalServices": null,
    "sizeTable": null,
    "promotion": {
        "emphasized": true,
        "bold": false,
        "highlight": false,
        "departmentPage": false,
        "emphasizedHighlightBoldPackage": false
    },
    "location": {
        "countryCode": "PL",
        "province": "MAZOWIECKIE",
        "city": "Raszyn",
        "postCode": "05-090"
    },
    "external": {
        "id": "1531817791"
    },
    "attachments": [],
    "contact": null,
    "validation": {
        "errors": [],
        "validatedAt": "2018-07-18T08:45:22.047Z"
    },
    "createdAt": "2018-07-17T08:56:40Z",
    "updatedAt": "2018-11-02T06:07:18.462Z"
}'`

**Comment by Raafal78** [comment]
.
