### ISSUE TITLE
Błąd o używaniu kontaktu innego sprzedawcy

### ISSUE THREAD

**Issue by Hornir91** [allegro/allegro-api#8490]
Dzień dobry.

Dzisiaj podczas próby aktywacji ogłoszenia, pojawił się komunikat:
"Could not change offer publication status. You cannot use the contacts of another seller."

Problem w tym, że od miesięcy używamy tego samego kontaktu do wystawiania danej marki samochodów i dotychczas nie było żadnego problemu.

Problem nie dotyczy jedynie jednej marki, a kilku, dlatego podaję wszystkie trace ID błędów:
152d102bc1b162da
1d0df57e6b15617e
d64817e56719b088
6cbb55f4de96169c
f587484019b12484
3928c0ed6ad4fae6
63516c9d71d6170b

Proszę o wyjaśnienia.
Z góry dziękuję.

**Comment by Lukasz-Zurek** [comment]
@Hornir91 Niestety na podstawie wskazanych trace-id nie mogę zweryfikować wspomnianego problemu. Prześlij proszę przykładowe numery ofert.

**Comment by Hornir91** [comment]
15171493143
15171516845
15171517044
15171538784
15171543241
15171559265
15171567039

**Comment by Hornir91** [comment]
Większość z ww. szkiców jest już nieaktualna (wystawiliśmy całkiem nowe ogłoszenia) i jedynie problem występuje jeszcze we dwóch:
15171517044
15171538784

**Comment by Lukasz-Zurek** [comment]
@Hornir91 Sprawdzamy to. Wkrótce wrócę z informacją.

**Comment by Hornir91** [comment]
@Lukasz-Zurek wiadomo już coś w tym temacie?

**Comment by Lukasz-Zurek** [comment]
@Hornir91 Wdrożyliśmy niedawno poprawkę i sytuacja nie powinna się już powtarzać. Dopytuję jeszcze dla pewności.

**Comment by Hornir91** [comment]
Ok, dziękuję.
