### ISSUE TITLE
Problem z walutą dla Allegro Kurier DHL Czechy pobranie

### ISSUE THREAD

**Issue by akonopka11** [allegro/allegro-api#8491]
Witam,
Podczas generowania etykiety dla metody wysyłki "Allegro Kurier DHL Czechy pobranie" mam komunikat:
"The currency is not supported by the delivery option"
Z czego to może wynikać?
"commandId": "d6430e51-9ffd-4adc-8f9c-63858fc4bc73"

**Comment by Lukasz-Zurek** [comment]
@akonopka11 W polu **insurance.currency** przekazujesz CZK, natomiast dla tej usługi dostawy wymagana jest wartość PLN.

**Comment by akonopka11** [comment]
Korzystam z tego adresu:
https://api.{environment}/parcel-management/parcel-create-commands/{commandId}
Czy tam jest taka opcja? Czy tylko tutaj?
https://api.{environment}/parcel-management/parcel-create-commands/{commandId}

**Comment by akonopka11** [comment]
A dlaczego domyślnie jest wysyłana nieprawidłowa wartość? A może można to gdzieś przez panel Allegro zmienić? Zdaję sobie sprawę, że powinniśmy przejść na te nowe adresy, brak czasu powoduje, że jeszcze tego nie zrobiliśmy.

**Comment by Lukasz-Zurek** [comment]
@akonopka11 Według naszych logów - takie dane zostały nam przekazane w żądaniu dotyczącym utworzenia paczki.

Generalnie w przypadku zasobów **/parcel-management/** ubezpieczenie musisz przekazać w polu **items.value.amount**, przekazując również odpowiednią walutę w **items.value.currency**. 

Natomiast nie zwracamy informacji o tym jaka waluta wymagana jest dla ubezpieczenia per usługa dostawy jak skorzystasz z **GET /parcel-management/delivery-services**. Informacje te zwracamy na nowym zasobie **GET /shipment-management/delivery-services**.

> [...] A może można to gdzieś przez panel Allegro zmienić?

Obawiam się, że w "Moim Allegro" takich ustawień nie ma.
