### ISSUE TITLE
Problem z dodaniem nr. śledzenia paczki | /order/checkout-forms/{order_id}/shipments SANDBOX

### ISSUE THREAD

**Issue by Smerf90** [allegro/allegro-api#8492]
Dzień dobry, 
Mam problem z dodaniem nr. śledzenia paczki dla zamówienia.

`Kod błędu: 400, Treść błędu: {"errors":[{"code":"ERROR","message":"Bad Request","details":null,"path":null,"userMessage":"Bad Request"}]}`

Nie mogę znaleźć gdzie leży problem. 

Login: `Smerf16` - SANDBOX

environment: `"allegro.pl.allegrosandbox.pl"`
Próbuję dodać nr. śledzenia dla zamówienia: `"db400e70-cc12-11ee-84d6-4f1818e6445d"` 
carrierId: `"DHL"`
waybill: `"27846490583"`

* Numer przesyłki powinien być zgodny, gdyż jest to prawdziwy numer paczki tego przewoźnika (dostarczona ok. tydzień temu)
* Gdyby był nieprawidłowy powinienem dostać ERROR 422

Token ważny - działający

**Python**

```
order_id  = "db400e70-cc12-11ee-84d6-4f1818e6445d"
carrierId  = "DHL"
tracking  = "27846490583"

def Update_Tracking_Allegro(order_id: str, carrierId: str, tracking: str):
    """
    Updates `tracking_id` for order - Allegro
    """

    url  = f"https://api.{environment}/order/checkout-forms/{order_id}/shipments"

    print(url)

    headers = {
            "Authorization": f"Bearer {ACCESS_TOKEN}",
            "Accept": "application/vnd.allegro.public.v1+json",
            "Content-Type": "application/vnd.allegro.public.v1+json"
        }
    
    data = {
        "carrierId": carrierId,
        "waybill": tracking,
    }


    try:
        response = requests.post(url, headers=headers, data=data, verify=False)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"Błąd `Update_Tracking_Allegro`. Kod błędu: {response.status_code}, Treść błędu: {response.text}")
        return None

Update_Tracking_Allegro(order_id, carrierId, tracking)
```

Błąd tyczy się requestu jednak w kodzie nie widzę błędu. 
`Kod błędu: 400, Treść błędu: {"errors":[{"code":"ERROR","message":"Bad Request","details":null,"path":null,"userMessage":"Bad Request"}]}`

Będę wdzięczny za wszelką pomoc. 

Pozdrawiam,
Maciej

**Comment by Lukasz-Zurek** [comment]
Otrzymaliśmy od Ciebie nieprawidłową strukturę body:

`carrierId=DHL&waybill=27846490583`

Powinno być w json, np:

```
{
    "carrierId": "DHL",
    "waybill": "27846490583"
  }
```

**Comment by Smerf90** [comment]
Aaa, rzeczywiście. 
Dziękuję bardzo
