### ISSUE TITLE
Weryfikacja konta allegro sandbox

### ISSUE THREAD

**Issue by szymix2Pro** [allegro/allegro-api#8494]
Proszę o weryfikacje konta do allegro sandbox 
Nazwa konta: fdfd
Clinet: 106870573

**Comment by AureliuszBrussy** [comment]
To jest konto zwykłe - możesz aktywować je w trakcie składania pierwszego testowego zamówienia. Jeżeli chciałbyś testować Allegro jako sprzedający, [zarejestruj nowe konto firma](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F). Gdy podczas rejestracji przejdziesz tzw. "krokowiec" (wykonasz symulację przelewu weryfikacyjnego oraz uzupełnił fikcyjne dane) daj znać - aktywuję konto.

**Comment by szymix2Pro** [comment]
Dziękuje za odp
Nowe konto:
SzyAPI1231

**Comment by AureliuszBrussy** [comment]
@szymix2Pro aktywowałem Twoje konto.

**Comment by JacekStawicki360** [comment]
Dzien dobry,
prosze o aktywacje konta sprzedawcy **360sprzedawca** na sandbox.
Chodzi o weryfikacje rachunku bankowego oraz danych firmy.

**Comment by Lukasz-Zurek** [comment]
@JacekStawicki360 Aktywowałem wskazane konto.
