### ISSUE TITLE
Parametr - isDraft dla GET /sale/products/{productId}

### ISSUE THREAD

**Issue by array3** [allegro/allegro-api#8495]
Cześć.
Moje pytanie dotyczy parametru isDraft, którego opis to:

- (boolean) Flag that informs if product is waiting for resolution of basic parameters change proposal.

Jeżeli dobrze rozumiem, to w momencie gdy w serwisie widnieje status zgłoszenia zmiany dla danego produktu jako "oczekujące" lub "częściowo zweryfikowane" to powinien on zwrócić wartość **_True_**, natomiast gdy takich zgłoszeń nie ma to wartość **_False_**?

**Comment by Lukasz-Zurek** [comment]
Wartość **true** w polu **isDraft** aktualnie dotyczy wyłącznie draftów produktu, które tworzymy na podstawie sugestii zmian użytkowników ze strony internetowej. Pole to nie jest zatem związane z nowymi produktami, które tworzysz za pomocą POST /sale/product-offers lub POST /sale/product-proposals.
