### ISSUE TITLE
GET order/event-stats kiedy może zwrócić pustą odpowiedź?

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#8496]
Witam,

Mam pytanie dotyczące zasobu `GET order/event-stats`

W jakiej sytuacji możemy otrzymać odpowiedź 200 ale bez klucza `latestEvent`?

Czy jest możliwa sytuacja, że zapytanie raz na jakiś czas zwróci pusty wynik zamiast ostatniego zdarzenia?

Niestety, nie mam `trace-id`, sytuacja nastąpiła około 2024-02-14 17:48.  Obecnie `trace-id: 25daf6ffe1e3d354` zwraca zawsze dobrą odpowiedź.

**Comment by Lukasz-Zurek** [comment]
Generalnie jeżeli w ciągu ostatnich 60 dni nie było żadnego zdarzenia, to, gdy skorzystasz z GET order/event-stats, powinniśmy Tobie zwrócić:

```
{
    "latestEvent": null
}
```

Jeżeli otrzymałeś pusty wynik zamiast ostatniego zdarzenia - mogło dojść do błędu po naszej stronie. Taka odpowiedź nie powinna być zwracana.

Jeżeli ta sytuacja się powtórzy, daj proszę znać.
