### ISSUE TITLE
Bład pobierania danych adreowych z zaobu order/checkout-forms

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#8497]
Dla zamówień opłaconych i dla zasobu:
https://api.{environment}/order/checkout-forms/{id}

w polu "delivery": {
		"address": null,

od godziny około 11 dostajemy null zamiast danych zamawiającego.
Id zamówienia: 8499c380-cf10-11ee-ab5b-358ace0c4a6e, 93804ef1-cf10-11ee-bb8a-cf80236c57ec

**Comment by manoos** [comment]
Co ciekawe "status": "FILLED_IN", ale wpłata już jest

**Comment by manoos** [comment]
Czy coś wiadomo ? Wszystkie nowe zamówienia mają adress null i status FILLED_IN mimo że są opłacone.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam problem po naszej stronie, pracujemy nad rozwiązaniem. Informacja jest także widoczna na naszym Status Page - https://api.allegrostatus.pl/. Wrócę z informacją po wyeliminowaniu błędu.

**Comment by arolznov** [comment]
u nas taka sama sytuacja, brak zdarzeń typu READY_FOR_PROCESSING w zasobie /order/events

**Comment by manoos** [comment]
Na api.allegrostaus.pl od 12:35:27 jest informacja, że problem jest już rozwiązany, ale zamówienia dalej mają status FILLED_IN, kiedy zostanie on zaktualizowany?

**Comment by mojosoft** [comment]
Potwierdzam problem nadal występuje.

**Comment by PrzemyslawLukanowski** [comment]
> Na api.allegrostaus.pl od 12:35:27 jest informacja, że problem jest już rozwiązany,

Usunęliśmy tę błędną informację, status zaktualizujemy po wyeliminowaniu problemu, przepraszam za niedogodności.

**Comment by manoos** [comment]
Jaki jest przewidywany czas usunięcia usterki? 
Czy opóźnienia w realizacji zamówień będą miały wpływ na statystyki terminowości ?

**Comment by mskiba03** [comment]
Wiadomo juz cos?

**Comment by arolznov** [comment]
chyba coś zaczyna ruszać, pojawiły sie jakies eventy READY_FOR_PROCESSING

**Comment by PrzemyslawLukanowski** [comment]
Tak, potwierdzam, statusy zamówień zaczynają już się zmieniać. Potwierdzę jednak jeszcze ostatecznie, gdy błąd zostanie naprawiony.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam zakończenie awarii, nadal wysyłamy eventy dla zaległych zamówień, wkrótce wszystkie powinny otrzymać odpowiedni status. Jeszcze raz przepraszam za niedogodności wywołane tą sytuacją.
