### ISSUE TITLE
Brakujący event READY_FOR_PROCESSING

### ISSUE THREAD

**Issue by kanoe92** [allegro/allegro-api#8498]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Nie otrzymałem eventu READY_FOR_PROCESSING pomimo tego, że zamówienie klienta jest już opłacone. Dodatkowo, dostałem już e-maila, o tym, że otrzymałem wpłatę od kupującego. Sprawdzałem również na portalu Allegro w zakładce z finansami - wpłata jest zaksięgowana.

Sprawdziłem endpoint order/events i dostałem 2 eventy z tego zamówienia: BOUGHT oraz FILLED_IN. Status zamówienia zatrzymał się na tym drugim. 

Co w takim wypadku? 
Czy mam założyć, że zamówienie jest już w pełni opłacone i mogę rozpocząć realizację zamówienia? 
Czy jest możliwe, że status READY_FOR_PROCESSING przyjdzie po jakimś czasie? 
Czy zdarzają się tego typu problemy?

Z góry dziękuję za pomoc i odpowiedzi :)

**Comment by arolznov** [comment]
bug https://github.com/allegro/allegro-api/issues/8497

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak jak napisał @arolznov - występuje aktualnie problem po naszej stronie. Pracujemy nad wyeliminowaniem błędu.

**Comment by oponika** [comment]
Podbijam temat, problem występuje, wszystkie zamówienia po godzinie 11:00 nie mają zaktualizowanego statusu pomimo dokonanych wpłat, wszystko ma status FILLED_IN

**Comment by szymanski-m** [comment]
Podbijam temat, u mnie identyczny problem.

**Comment by PrzemyslawLukanowski** [comment]
Zaczęliśmy już wysyłać eventy ze statusem "READY_FOR_PROCESSING", wkrótce wszystkie zamówienia otrzymają poprawny status i komplet danych.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam zakończenie awarii, nadal wysyłamy eventy dla zaległych zamówień, wkrótce wszystkie powinny otrzymać odpowiedni status. Jeszcze raz przepraszam za niedogodności wywołane tą sytuacją.
