### ISSUE TITLE
Zmiana i usuwanie zdjęć

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#85]
W jaki sposób należy usuwać zdjęcia z oferty przy nowym opisie ? 

Mamy na przykład ofertę dodaną z 3 zdjęciami (PHOTO_FID_16, PHOTO_FID_17, PHOTO_FID_18), 

Zmieniamy i wysylamy opis który zawiera tylko 1 zdjęcie ( PHOTO_FID_16)
W ofercie modyfikuje się pierwsze zdjęcie , ale 2 pozostałe zostają mimo że ich nie wysyłamy. 

Z kolei przy próbie wysłania w polach fieldsToModify wartosci null dla fidow 17 i 18  dostajemy ERR_OTHER_PHOTO_ERROR.

**Comment by pfunkowski** [comment]
Metoda dochangeitemfields
https://allegro.pl/webapi/documentation.php/show/id,922

wt., 20 mar 2018, 20:24 użytkownik pepe <notifications@github.com> napisał:
