### ISSUE TITLE
[REST] Sandbox umarł

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#850]
Dobry wieczór, jak w temacie 
na sandboxie macie 503 service unawa.......

**Comment by FromAnyHole** [comment]
Cześć jego pamięci... Amen !

**Comment by TomekKaczmarek** [comment]
Zaiste... Walczymy z tematem.

**Comment by Onixarts** [comment]
Coś ruszyło, dzięki.

**Comment by TomekKaczmarek** [comment]
Sandbox powinien już być dostępny. Sprawdźcie proszę.

**Comment by Onixarts** [comment]
3 problemy przy kopowaniu. Timeout po wciśnięciu kup. Za drugim razem przeszło dalej ale wywalił się przycisk kupuję i płacę. Za trzecim razem poszedł FOD ale symulator banku "poszedł nie tak". Za 4 razem poszło.

**Comment by Onixarts** [comment]
Dlatego, że raz idzie a raz nie :).

Próba wystawienia aukcji `Błąd podczas weryfikacji, czy użytkownik jest dostępny w usłudze ustawień sklepów (w celu wystawienia jako Strefa Marek). (0x80004005)`

Przez www również nie da się wystawić, ale nie wiadomo jakie błędy.

**Comment by TomekKaczmarek** [comment]
@Onixarts ewidentnie pospieszyłem się z dobrymi wieściami. Problemy są nadal - walczymy.
