### ISSUE TITLE
GetAllegroPickupDropOffPoints - kiedy będzie można pobierać dane o punktach odbioru z Czech?

### ISSUE THREAD

**Issue by twylandowski-cfi** [allegro/allegro-api#8500]
Witajcie,
Chciałbym pobrać listę wszystkich punktów odbioru dla wysyłek do Czech, ale API zwraca tylko UPS i ALLEGRO_ONE_BOX z Polski.
Kiedy planujecie udostępnić listę punktów z Czech?
Pozdrawiam,
Tomasz

**Comment by piqub** [comment]
Temat zapoczątkowany w [Github Discussions](https://github.com/allegro/allegro-api/discussions): https://github.com/allegro/allegro-api/discussions/8763

**Comment by Lukasz-Zurek** [comment]
@piqub Dziękuję.
