### ISSUE TITLE
Allegro Sandbox seller account - do I need to provide real company financial information?

### ISSUE THREAD

**Issue by Anca-Anca** [allegro/allegro-api#8501]
Dears,

I'm trying to set up an Allegro sandbox seller account for testing purpose.
Do I need to provide real company financial information at this point? - The application asks me at this point to verify the bank account in order to post an offer.

Thank you,
Anca

-----------------------------------------------------
Kochani,

Próbuję założyć konto sprzedawcy w piaskownicy Allegro w celach testowych.
Czy na tym etapie muszę podawać prawdziwe informacje finansowe firmy? - Aplikacja prosi mnie w tym momencie o weryfikację konta bankowego w celu zamieszczenia oferty.

Dziękuję,
Anka

**Comment by Lukasz-Zurek** [comment]
No, you don't have to provide real company information. You should use fictional data.

If you already have a business (company) account, please set payouts right [here](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty), and then please use our payment simulator. If you finish this process and your account is still not activated, please give me your login and let me know.

**Comment by Anca-Anca** [comment]
Dear @Lukasz-Zurek ,

Thank you for the response.
I have re-tried again but I cannot bypass the activation of bank account. Please help.
![image](https://github.com/allegro/allegro-api/assets/160516241/d58ab398-faa6-42ef-b5a3-dbf4026bf9bd)


Best regards,
Anca
