### ISSUE TITLE
I want to integrate odoo with allegro

### ISSUE THREAD

**Issue by vladosmolovskiy** [allegro/allegro-api#8502]
Hi, I want to integrate odoo with Allegro. I need to set up cron job, that will take new orders each 10 minutes, my question is that possible to auth without going to any links and perform manual login process?

**Comment by Lukasz-Zurek** [comment]
If you want to use our API and retrieve orders, you will have to use one of [these authorization methods](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY), apart from [Client_credentials flow](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#clientcredentials-flow), which gives an access only to public data (like list of the categories and parameters, etc.).
