### ISSUE TITLE
Blokada konta na sandboxie

### ISSUE THREAD

**Issue by Darayavus** [allegro/allegro-api#8505]
Cześć,
bardzo proszę o odblokowanie "sprzedaży" na koncie `Darayavus`.
![blokada](https://github.com/allegro/allegro-api/assets/89593636/d4c54a27-e408-4b4f-8791-68f45625c7c8)

Czy powodem blokady były tylko "nieopłacone rachunki" czy coś jeszcze?

Pozdrawiam

**Comment by Darayavus** [comment]
Tak, mogę, dziękuję. A co z ofertami, które tam były? Teraz ich nie widzę. Trochę ich wyprodukowałem :) Przydałyby się do testowania Słowacji ;)

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale te oferty zostały usunięte z uwagi na akcję, o której wspominaliśmy [w newsie](https://developer.allegro.pl/news/sandbox-14-lutego-2024-zaktualizujemy-liste-kategorii-i-parametrow-oraz-usuniemy-wszystkie-oferty-AgbYK0kEOUq). Taki proces staramy się przeprowadzać raz na kwartał. W tym przypadku musisz wystawić nowe oferty.

**Comment by Darayavus** [comment]
OK, dziękuję za wyjaśnienie i pomoc ;)

**Comment by AdrianeZ** [comment]
Mozna prosić to samo dla konta CopentroTester - odblokowanie sprzedaży?

**Comment by PrzemyslawLukanowski** [comment]
@AdrianeZ Czy to n pewno prawidłowe konto? Nie widzimy po naszej stronie żadnych blokad lub zadłużeń na tym koncie.

**Comment by AdrianeZ** [comment]
Ja też nie widzę ale jak próbuje wystawić przez api to pojawia się informacja taka jak w formualrzu wystawiania: 
![obraz](https://github.com/allegro/allegro-api/assets/69970869/3b334fab-398a-47c4-b0d1-1837559216d8)
konto jest ok

**Comment by AdrianeZ** [comment]
![obraz](https://github.com/allegro/allegro-api/assets/69970869/2649ef97-83d1-4b74-ab2c-2c9b63cfda54)

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za informację. Przekazuję ten problem dalej i wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
@AdrianeZ Zdjęliśmy blokadę, wynikała ona z rachunku bankowego, który był identyczny również dla innych kont, które taką blokadę posiadały. Sugeruję korzystać z bardziej unikalnych numerów rachunków.
