### ISSUE TITLE
Wysyłka faktur do allegro - Trwa skanowanie

### ISSUE THREAD

**Issue by Morph21** [allegro/allegro-api#8507]
Witam, chciałbym się mniej więcej dowiedzieć od czego zależy to czy faktura przesłana do allegro dostaje status "skanowana"
a raczej "Security scan for SELLER invoice in given order [xxx-xxx] is in progress"

Podam tutaj jako przykład klienta który przesyłając faktury do około 50 zamówień dla mniej więcej połowy dostał status skanowania.

Zastanawiamy się przede wszystkim dlaczego aż tyle plików dostaje taki status, oraz czy jest coś co możemy zrobić aby zmniejszyć tą ilość lub kompletnie ją wyzerować.

Drugą sprawą jest opcja przetestowania na sandboxie takiego przypadku, czy jest jakiś sposób w którym da się to zrobić (oferta na konkretny produkt/ format pliku etc) czy raczej jest to na zasadzie szczęścia?

Kolejne pytanie odnosi się masowego sprawdzenia statusu wysyłki faktur do allegro, czy planujecie Państwo rozwinąć api w tym zakresie (bo nie znalazłem nigdzie informacji że da się to na ten moment wykonać)

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać nieco więcej szczegółów - w odpowiedzi którego endpointu otrzymałeś taką odpowiedź? Czy możesz podać przykładowe trace-id operacji lub id zamówienia?

**Comment by Morph21** [comment]
Taka odpowiedź wpadła między innymi do zamówień o id: 
- a44d0c50-c97a-11ee-9400-f5d4a7cf02a6
- 080099f0-cbcf-11ee-990e-8d54a845ca77

Niestety nie wiem które to trace-id bo jest tam teraz 5 faktur z tego co widzę więc klient pewnie dodał kilka razy myśląc że coś jest nie tak jako że my to potraktowaliśmy jako błąd umożliwiając powtórne przesłanie faktury.

Co do endpointu to chodzi o ten: PUT /order/checkout-forms/{id}/invoices/{invoiceId}/file

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za szczegóły, skonsultowałem ten temat z zespołem odpowiedzialnym za obsługę faktur. 

> od czego zależy to czy faktura przesłana do allegro dostaje status "skanowana"
> a raczej "Security scan for SELLER invoice in given order [xxx-xxx] is in progress"

Każdą fakturę skanujemy, żeby wyeliminować celowe lub niecelowe przesyłanie zainfekowanych plików. Status, o którym wspominasz, wystąpi wyłącznie w sytuacji, gdy nie zakończyliśmy skanowania dla poprzedniego pliku, a klient już dodał następny plik.

> Zastanawiamy się przede wszystkim dlaczego aż tyle plików dostaje taki status, oraz czy jest coś co możemy zrobić aby zmniejszyć tą ilość lub kompletnie ją wyzerować.

Aby zmniejszyć liczbę tych błędów, możecie odczekać chwilę przed załadowaniem nowego dokumentu.  Rodzi się tutaj jednak pytanie, dlaczego klient chciałby załączać do zamówienia więcej niż jedną fakturę? Być może po Waszej stronie, po uploadzie pliku, od razu sprawdzacie metodą GET, czy faktura została dodana i ponawiacie upload, jeśli jej nie ma (nie będzie jej, bo ponieważ należy odczekać przynajmniej kilkadziesiąt milisekund). Czy macie po swojej stronie jakiś mechanizm retry lub inny algorytm, który ponawia wysyłkę? Requesty przychodzą zbyt szybko, żeby ktoś to ręcznie wykonywał np. odstęp między pierwszą, prawidłową dodaną fakturą, a drugą, dla której zwróciliśmy wspomniany status, wynosi niecałą sekundę.

> Drugą sprawą jest opcja przetestowania na sandboxie takiego przypadku, czy jest jakiś sposób w którym da się to zrobić (oferta na konkretny produkt/ format pliku etc) czy raczej jest to na zasadzie szczęścia?

Tak, jest to możliwe - jeśli będziecie wykonywać kilka requestów z rzędu dla jednego zamówienia, to wspomniany komunikat da się odtworzyć również na Sandboxie.

> Kolejne pytanie odnosi się masowego sprawdzenia statusu wysyłki faktur do allegro, czy planujecie Państwo rozwinąć api w tym zakresie (bo nie znalazłem nigdzie informacji że da się to na ten moment wykonać)

Nie planujemy takich zmian.

**Comment by Morph21** [comment]
Mamy możliwość wysłania przez klienta faktur do allegro dla zamówień które zaksięgował u nas w systemie na raz,
w przypadku tego klienta księgował on ponad 50 zamówień, następnie była wykonywana wysyłka po kolei dla każdego zamówienia automatycznie. 

Więc rozumiem że wygląda to w takim przypadku tak:

Załóżmy że mówimy o wysyłce dwóch faktur
1. Wysyłamy POST /order/checkout-forms/{id}/invoices/ żeby wygenerować invoice id

2. Wysyłamy PUT /order/checkout-forms/{id}/invoices/{invoiceId}/file żeby przesłać dokument do allegro

Dla pierwszego dokumentu jest ok

I teraz zostaje powtórzone to samo dla dokumentu drugiego

POST /order/checkout-forms/{id}/invoices/
i to powinno wygenerować prawidłowo id

następnie wysyłamy PUT

który zwraca nam błąd ze skanowaniem ponieważ wcześniejszy dokument jeszcze nie zakończył skanowania?

I teraz jeżeli dobrze rozumiem powinniśmy poinformować użytkownika że dokument został wysłany do allegro, czeka na zatwierdzenie/zeskanowanie.
I sprawdzić status tej wysyłki dopiero po jakimś czasie?

**Comment by PrzemyslawLukanowski** [comment]
> który zwraca nam błąd ze skanowaniem ponieważ wcześniejszy dokument jeszcze nie zakończył skanowania?

Tak, jednak według naszych logów informację o skanowaniu poprzedniej faktury otrzymujecie już na endpoincie POST /order/checkout-forms/{id}/invoices. 

> I teraz jeżeli dobrze rozumiem powinniśmy poinformować użytkownika że dokument został wysłany do allegro, czeka na zatwierdzenie/zeskanowanie.
> I sprawdzić status tej wysyłki dopiero po jakimś czasie?

Dokładnie tak, aktualnie wysyłka kolejnej faktury do zamówienia odbywa się zbyt szybko, stąd w odpowiedzi `409 Conflict`.

**Comment by PrzemyslawLukanowski** [comment]
Problemem jest to, że ta wysyłka faktury odbywa się w ramach tego samego zamówienia. Użytkownik dodaje jeden dokument, nie mija sekunda, po czym dodawany jest drugi dokument do zamówienia, do którego przed momentem załączył fakturę.

**Comment by Morph21** [comment]
z tego co się orientuję to raczej nie możliwe, dodajemy po kolei do każdego zamówienia fakturę osobno więc raczej powinny być te dwa wyżej wymienione zapytania po kolei wysyłane do każdego zamówienia z listy

Więc u was w logach to powinno wyglądać bardziej w taki sposób
POST /order/checkout-forms/1/invoices/
PUT /order/checkout-forms/1/invoices/{invoiceId}/file
POST /order/checkout-forms/2/invoices/
PUT /order/checkout-forms/2/invoices/{invoiceId}/file
POST /order/checkout-forms/3/invoices/
PUT /order/checkout-forms/3/invoices/{invoiceId}/file


gdzie 1,2,3 to powiedzmy numer zamówienia

**Comment by Morph21** [comment]
I nie do końca rozumiem bo wydaje mi się że sobie zaprzeczasz. 

bo z jednej strony mówisz że taka faktura do allegro się przesłała i czeka na skanowanie  jeżeli dostaliśmy błąd o skanowaniu a z drugiej strony że ten błąd dostajemy już na poziomie POST /order/checkout-forms/{id}/invoices/

Co według mnie nie jest wykonalne ponieważ jeśli dostali byśmy błąd na zapytaniu tym pierwszym to nie wykonalibyśmy drugiego nie mając invoice id co za tym idzie faktura nie została by przesłana do allegro.

Tak więc albo ten błąd dostajemy na poziomie drugiego zapytania (PUT) i faktura wpada do allegro i sobie czeka gdzieś w kolejce na skanowanie (wtedy moglibyśmy użytkownikowi powiedzieć że została przesłana i się przetwarza)

Albo dostajemy ten błąd na pierwszym zapytaniu co skutkuje tym że faktura do allegro nie została przesłana i musimy umożliwić użytkownikowi jej kolejną wysyłkę

**Comment by PrzemyslawLukanowski** [comment]
Podam przykład dla zamówienia a44d0c50-c97a-11ee-9400-f5d4a7cf02a6

2024-02-20 07:35:25.628 - operacja POST /order/checkout-forms/{id}invoices zakończona **sukcesem**, zwracamy status 201 i otrzymujecie `invoice.id`,
2024-02-20 07:35:26.251 - ponowna operacja POST /order/checkout-forms/{id}invoices, skanowanie poprzedniego dokumentu się nie zakończyło dlatego zwróciliśmy status **409**,
2024-02-20 07:35:26.533 - ponowna operacja POST /order/checkout-forms/{id}invoices, teraz zakończona **sukcesem**, zwracamy status 201 wraz z nowym `invoice.id`,
2024-02-20 07:35:27.108 - ponowna operacja POST /order/checkout-forms/{id}invoices, skanowanie poprzedniego dokumentu się nie zakończyło, dlatego zwróciliśmy status **409**,
2024-02-20 07:35:27.253 - ponowna operacja POST /order/checkout-forms/{id}invoices, skanowanie poprzedniego dokumentu się nie zakończyło, dlatego zwróciliśmy status **409**,
2024-02-20 07:35:27.493 - ponowna operacja POST /order/checkout-forms/{id}invoices, teraz zakończona **sukcesem**, zwracamy status 201 wraz z nowym `invoice.id`,
2024-02-20 07:36:04.199 - ponowna operacja POST /order/checkout-forms/{id}invoices, zakończona **sukcesem**, zwracamy status 201 wraz z nowym `invoice.id`,

później następuje jeszcze kilka prób, na które zwracamy 201 lub 409.

**Comment by Morph21** [comment]
I pomiędzy tymi zapytaniami post nie było ani razu wywołanego tego PUT z faktycznym przesłaniem dokumentu?

**Comment by PrzemyslawLukanowski** [comment]
Były również:

2024-02-20 07:35:25.994
2024-02-20 07:35:26.890
2024-02-20 07:35:27.884
2024-02-20 07:36:04.586

na wszystkie odpowiedzieliśmy prawidłowym kodem 200, ponieważ posługiwaliście się prawidłowym invoice.id, uzyskanym z wcześniejszej, zakończonej sukcesem metody PUT.
