### ISSUE TITLE
Updating Units in Bulk

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#8509]
Hi there, 

we were wondering if you are planning to introduce a bulk update option similar to the one Kaufland has: 
![image](https://github.com/allegro/allegro-api/assets/147524238/71610383-9e40-40a4-8ab1-847b33f588f0)
https://sellerapi.kaufland.com/?page=inventory#updating-units-in-bulk

It is quite difficult to not go over the limit of 9000 requests per minute with so many clients that need to update product data on a regular basis. The only option that Allegro has for bulk editing is, that all the offers we update would need to have the sama data, which they mostly do not have, so we need to update each offer separately. 

Thank you in advance for your answer!

All the best, 

Dominika

**Comment by Lukasz-Zurek** [comment]
We have resources which give you a possibility to edit many offers,  up to 1000 offers. Please check [our tutorial](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#editing-many-offers) for more information.

If you have some specific questions, please let me know.

**Comment by dominikahr** [comment]
Yes, but if we understand it correctly in this case we can edit up to 1000 offers but **only with the same values**. So we could only update the price of 1000 products, if all the products would have a new same price. In case of Kaufland, we can update up to 150 offers and each offer in the one request can have different data, for example price. 

Do we understand the option offered by Allegro in a wrong way? If not, are you planning to offer something similar to Kaufland in the future?

**Comment by Lukasz-Zurek** [comment]
You understood the option in our API in correct way. Even though we don't plan to add something similar to the option in Kaufland, I can only recommend sending that kind of suggestion in our [Github Discussions](https://github.com/allegro/allegro-api/discussions), where we collect various ideas for the development of the Allegro API.
