### ISSUE TITLE
Czy zostanie dodanie wyszukiwanie po czasie wystawienia?

### ISSUE THREAD

**Issue by dave7280** [allegro/allegro-api#851]
Wyszukiwanie po czasie wystawienia - np wystawione w ciagu 2h.

Czy takie wyszukiwanie zostanie udostepnione jako rozszerzenie metody REST _/offers/listing_?
Jesli ktos chce przeszukiwac aukcje w celu znalezienia nowych ofert, musi on wykonywac nastepujace czynnosci:

1. Pobranie aukcji z uzyciem sortowania od najnowszych i zapisanie tzw snapshota, 
2. Kolejne pobranie aukcji i sprawdzenie ktore elementy ulegly zmianie.

Czy jest jakas szansa na dodanie po prostu filtra "wystawione w ciagu" do Rest API?
A jesli nie, moze dodanie pola "startingTime" do informacji o ofercie?

Obecnie api nie trzyma sie kupy, zwracane jest "endTime" czyli czas konca aukcji, ale za to nie ma daty rozpoczecia co rowniez utrudnia sprawe. 
Jesli dodana zostala by data rozpoczecia czyli ten "startingTime" to mysle ze niebylby potrzebny filtr "wystawione w ciagu".

Dodatkowo jest mozliwosc wyszukiwania po czasie wystawienia w glownym serwisie (Poza API) w niektorych dzialach, ale wymaga ono parsowania htmla co tylko obciaza serwery allegro. "?startingTime=X"

Nie rozumiem dlaczego usuwacie metode WebAPI _doGetItemsList_ kosztem wykastrowanego RESTOwego _/offers/listing_. W usuwanej metodzie, znajduje sie filtrowanie po czasie wystawienia.

Metoda na odnalezienie nowych aukcji sie oczywiscie jakas znajdzie, tyle ze tego typu "workaroundy" prowadza do obciazenia waszych serwerow poprzez pobieranie pelnej wersji serwisu.

**Comment by TomekKaczmarek** [comment]
W zasobie GET /offers/listing nie wspieramy filtra wystawione w ciągu, ponieważ nie jest on już dostępny - zwróć proszę uwagę, nie ma go również na froncie serwisu. 

Datę wystawienia oferty zwracamy w zasobach, które zalogowanemu sprzedawcy pozwalają zarządzać jego ofertami - https://developer.allegro.pl/my_offers/. W jakim celu potrzebujesz daty wystawienia oferty w zasobie z publicznymi danymi o ofertach?

**Comment by dave7280** [comment]
Zgadzam sie ze dla sprzedawcow wszystko jest juz dostepne.
Co do wykorzystania, do w celu wyszukiwania nowych ofert ktore spelniaja moje kryteria i mozna je uznac za atrakcyjne.

Filtra wystawione w ciagu niby nie ma, jednak dodanie parametru w URL ciagle dziala. 

Przyklad:

https://allegro.pl/kategoria/laptopy-491?startingTime=1&order=m

Wiec ciagle jedynym rozwiazanie pozostaje wykonywanie snapshotow listy aukcji i sortowanie po dacie dodania.. nienajlepsze rozwiazanie, ewentualnie korzystanie z funkcjonalnosci ktorej oficjalnie nie ma.. no ale jednak jeszcze dziala.

**Comment by TomekKaczmarek** [comment]
@dave7280 dzięki za wyjaśnienia i sugestię - przekazałem ją do odpowiedniego zespołu. Jeśli zdecydujemy się wdrożyć taką zmianą, poinformujemy o tym w osobnym komunikacie.

**Comment by dave7280** [comment]
Powoli zbliza sie temrin wygasniecia doGetItemsList, jakies informacje w sprawie dodania ewentualnego pola dot. daty dodania oferty sprzedazy?

**Comment by PawelTaberski** [comment]
@dave7280 Jak najbardziej just już możliwość takiego filtrowania poniżej przykładowe wywołanie:
/offers/listing?category.id=4094&startingTime=PT1H
Wszystkie dostępne filtry w danej kategorii znajdziesz w wywołaniu w "filters".
Polecam zapoznać się z [naszym poradnikiem](https://developer.allegro.pl/listing/) na temat wyszukiwania ofert.

**Comment by dave7280** [comment]
Super, dziekuje! :)
