### ISSUE TITLE
wprowadzenie produktów pod marką własną

### ISSUE THREAD

**Issue by Karpeta** [allegro/allegro-api#8510]
Dobry dzień,
jesteśmy czeskimi sprzedawcami na czeskim Allegro.cz. Mamy problem z załadowaniem produktów, które sprzedajemy pod własną marką i kodem EAN. Do wgrania produktów korzystaliśmy z pośrednika /ponieważ nasz e-sklep nie posiada API/, niestety na Allegro wgrane zostało jedynie minimum produktów innych producentów. Mamy już zarejestrowaną naszą markę na Allegra / marka to Proutidekorace/, ale nie możemy przesłać produktów. Więc nasze pytanie brzmi jak wgrać te nasze produkty /jest to około 500 rodzajów produktów/ na Allegro.
Dziękuję za odpowiedź.

**Comment by Lukasz-Zurek** [comment]
W tej sytuacji najbardziej optymalnym rozwiązaniem wydaje się być opcja opisana na stronie "Dla sprzedających", pod [tym adresem](https://allegro.pl/dla-sprzedajacych/jak-mozesz-przekazac-nam-swoja-baze-danych-produktow-YWqLnDRxPu8).

Jeżeli chodzi o nasze publiczne API, udostępniamy zasób do tworzenia nowych produktów: [POST /sale/product-proposals](https://developer.allegro.pl/documentation#operation/getSaleProduct), ale w tym przypadku, w jednym requeście możesz utworzyć tylko jeden produkt. Więcej informacji na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-utworzyc-nowy-produkt).
