### ISSUE TITLE
Data zamówienia /checkout-forms/{id}

### ISSUE THREAD

**Issue by SzymonZasada** [allegro/allegro-api#8511]
Cześć
 Czy jest możliwość wyciągnąć dokładna datę zamówienia z zasobu /checkout-forms/{id} zamiast /events. Z tego co udało mi sie znależć to lineItems[0].boughtAt pasuje , ale nie jestem pewien czy moze byc sytuacja ze lineItems bedzie puste

**Comment by Lukasz-Zurek** [comment]
Nie powinno być takiej sytuacji i faktycznie powinieneś zwrócić uwagę na datę w **lineItems[0].boughtAt**.
