### ISSUE TITLE
Authorization Exception/ Access Denied

### ISSUE THREAD

**Issue by xupehu** [allegro/allegro-api#8513]
Hello,

it seems like we get „Access Denied” and authorization exception errors, do we require some special permission to upload products via API?
If we purposefully send wrong information we get normal errors back, indicating the error, but if we seemingly give correct information we get these errors.
Every permission is checked regarding the API on our side.

**Comment by Lukasz-Zurek** [comment]
Make sure you do not use authorization type [ client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow), which does not have a user context. In [our documentation](https://developer.allegro.pl/documentation/) you will find the appropriate indication of what type of authorization is required for a given resource:

- bearer-token-for-user ([code](https://developer.allegro.pl/auth/#app) lub[ device](https://developer.allegro.pl/auth/#DeviceFlow) flow),
- bearer-token-for-application ([client credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow)).

**Comment by xupehu** [comment]
Hello,

thank you, it was successful. We have a lot of products in our catalogue (300.000) and we saw that you can pair products with already existing offers. Can you give us an example code on how to upload these first?

**Comment by Lukasz-Zurek** [comment]
@xupehu You can create products using [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct). More information and sample request you will find [here](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-create-a-product).

You can also search for existing products using [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts). More information [here](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-find-a-product).
