### ISSUE TITLE
Brak aktualizacji ceny oferty

### ISSUE THREAD

**Issue by Swistu93** [allegro/allegro-api#8514]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Oferta https://allegro.pl/oferta/zestaw-sprezyn-zawieszenia-przod-tyl-14169446570 od >24h ma nieaktualną cenę na listingu i karcie produktu mimo iż w panelu klienta jest zaktualizowana. Oferty aktualizujemy poprzez API, podobna sytuacja miała już miejsce w przeszłości https://github.com/allegro/allegro-api/issues/6862

![image](https://github.com/allegro/allegro-api/assets/124684960/87059416-1359-4e4e-ba1a-bbf0e4e59c72)

![image](https://github.com/allegro/allegro-api/assets/124684960/374c32ef-f673-49a5-b018-8288847cfff0)

**Comment by SzymonZasada** [comment]
Osobiście, mogę powiedzieć że miałem nieraz identyczna sytuacje przy aktualizacji cen przez api. Niestety jedyna opcja jaka u mnie zadziałała, to ręcznie zakończenie oferty i wznowienie po około 5 min.

**Comment by Swistu93** [comment]
Panie Szymonie, dziękuję za odpowiedź i propozycję quickfixu. 

Bardziej liczę na weryfikację problemu i jego rozwiązanie. Mamy 900k ofert, nie wyobrażam sobie ręcznej weryfikacji rozjazdów w cenach na karcie produktu względem zakładki "Mój asortyment" oraz zastosowanie zaproponowanego work around.
