### ISSUE TITLE
redirect_uri gdzie sprawdzić, czy zostało podane przy rejestracji aplikacji 

### ISSUE THREAD

**Issue by bozenadula** [allegro/allegro-api#8517]
Dzień dobry,

Rozpoczynam swoja przygodę i z Allegro REST API i z integracjami. Mój poprzednik zostawił niedziałającą integrację z allegro. Próbuję znaleźć źródło problemu. Na stronie Aplikacje REST API przeglądam szczegóły naszej zarejestrowanej aplikacji i nie widzę, żeby podana była informacja o redirect_uri. Czy oznacza to, że ta informacja nie została podana podczas rejestracji? Czy jest wymóg podania wszystkich adresów, z których będziemy korzystać podczas integracji? 

Z góry dziękuję za info
Bożena

**Comment by Lukasz-Zurek** [comment]
Jeżeli aplikacja jest typu web, tzn. podczas rejestracji wybrany został pierwszy rodzaj aplikacji, gdzie posiada ona dostęp do przeglądarki, w której użytkownik loguje się do Allegro (np. aplikacja na serwerze albo plik wykonywalny) - to wtedy redirect_uri znajdziesz w szczegółach aplikacji, w części "ADRESY PRZEKIEROWAŃ".

Jeśli natomiast wybrany został drugi rodzaj aplikacji, typu device - adresu przekierowań nie ma. Ma to oczywiście związek z samym sposobem autoryzacji w ramach Device flow.

Więcej informacji o autoryzacji w naszym API, znajdziesz [tutaj](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#wstep).

**Comment by bozenadula** [comment]
Dzięki za odpowiedź.  Nasza aplikacja jest zarejestrowana jako Device. W szczegółach API mamy tylko CLIENT ID i CLIENT SECRET. 
Czytałam dokumentację :-) tylko nie wiem czy ze zrozumieniem. Czy raz otrzymany device_code i token dostępowy są stałe i  już stale można z nich korzystać przy współpracy naszego systemu i Allegro? Wystarczy jednorazowa zgoda użytkownika na dostęp aplikacji do REST API?

**Comment by Lukasz-Zurek** [comment]
Tylko dane CLIENT ID i CLIENT SECRET są stałe, natomiast w toku każdorazowej autoryzacji device code czy uzyskany token są unikalne (natomiast sam token ważny jest 12h). Więcej informacji znajdziesz [tutaj](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) i zachęcam do przejrzenia tego procesu krok po kroku i w razie konkretnych wątpliwości - chętnie je wyjaśnię.

Jak wspomniałem - podstawowy token dostępowy (access_token) ważny jest 12 godzin. Aby nie wymuszać na użytkowniku ponownej autoryzacji aplikacji dwa razy na dobę, udostępniamy proces odświeżania tokenów, który z kolei opisaliśmy w [tym miejscu](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena).

**Comment by bozenadula** [comment]
Dzięki za cierpliwość. Przeczytałam o przedłużeniu ważności tokena. W przykładowym kodzie python (dokumentacja) używane jest redirect_uri, którego jak pisałeś powyżej w moim przypadku nie ma. Macie taki przykład pythona dla aplikacji Device?  Czy jest możliwość symulacji autoryzacji na środowisku testowym?

**Comment by Lukasz-Zurek** [comment]
Jeżeli piszesz o tym [artykule](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow-autoryzacja-uzytkownika), udostępniamy przykładowe zapytanie w Python, ale nie wymagamy tutaj redirect_uri. 

Oczywiście możesz przetestować proces autoryzacji na sandboxie :) Zwróć uwagę, że adresy na sandboxie różnią się od tych na produkcji:

**Adres wywołania metod** - https://api.allegro.pl.allegrosandbox.pl/
**Rejestracja aplikacji** - https://apps.developer.allegro.pl.allegrosandbox.pl/
**Adres do autoryzacji** - https://allegro.pl.allegrosandbox.pl/auth/oauth/

**Comment by bozenadula** [comment]
Raczej o artykule na temat [przedłużania](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena).

**Comment by Lukasz-Zurek** [comment]
@bozenadula Faktycznie we wskazanym przykładzie jest on dostępny, ale z całą pewnością redirect_uri jest ignorowany na poziomie żądania, więc tu problemu nie przewiduję :)

**Comment by bozenadula** [comment]
Dzień dobry, 
Łączę się przez API, jednak otrzymuję  komunikat 
![image](https://github.com/allegro/allegro-api/assets/103446565/f8958179-8e9c-45b7-908a-2a92526a6d2b) przykład dla "external_order_id": "ccc62d70-d176-11ee-8971-e917fa5f34df", mam metodę dostawy   "delivery_method": "Allegro One Box, One Kurier", wysyłam serviceId   '0b9bed2c-0bc1-4e1f-9694-29bb39ebb483'. Czy problem może wynikać z tego, że kod z którego korzystam jest oparty na parcel management a nie shipment managment . 

Bożena

**Comment by Lukasz-Zurek** [comment]
@bozenadula Nie, aczkolwiek zasoby na ścieżce **/parcel-management/** są oznaczone jako **deprecated**, więc przyszłościowo lepiej będzie jak zaczniesz korzystać już z nowych na **/shipment-management/**, ponieważ zasoby **/parcel-management/** wraz z końcem roku planujemy usunąć.

Natomiast problem stanowi na pewno kod pocztowy, na naszym środowisku testowym nie mamy po prostu ustawionych połączeń między tymi oddziałami/punktami. Podaj proszę commandId, lub trace-id, zweryfikuję to bardziej szczegółowo.

**Comment by bozenadula** [comment]
hmmm... przyznam, że robię próby od razu na produkcji i muszę szybko uruchomić jak już będą na tym pracować to zmienię kod na developie pod shipment 

przykład odrzuconej awizacji - generalnie dot. to wszystkich przesyłek, które dziś testuję 
command_id 84c3c8db-f51d-49fa-9fac-6233bc584d50

**Comment by Lukasz-Zurek** [comment]
@bozenadula Kod pocztowy wskazany w części **"receiver"** jest bez myślnika: 94004 i prawdopodobnie to powoduje błąd. Popraw proszę i daj znać czy przeszło :)

**Comment by bozenadula** [comment]
@Lukasz-Zurek Wysłaliśmy z myślnikiem i mamy ten sam błąd 
command_id 562b1302-29c8-44fa-b665-47e18e6184b5

**Comment by Lukasz-Zurek** [comment]
@bozenadula Sprawdzamy jeszcze po naszej stronie. Jak tylko uzyskam szczegóły, wrócę z informacjami.

**Comment by bozenadula** [comment]
cześć w słoneczny poniedziałek
wiemy już coś

**Comment by Lukasz-Zurek** [comment]
@bozenadula Problem nadal jest analizowany przez odpowiedni zespół, ale oczywiście poinformuję jak tylko uzyskam informacje.

**Comment by Lukasz-Zurek** [comment]
@bozenadula Problem dotyczy braku punktów. W żądaniu nie ma podanych punktów nadawcy/odbiorcy w polach **sender.point**, **pickup.point** i **receiver.point**, a nadanie door to door nie jest możliwe w przypadku tej konkretnej metody dostawy. Musisz wskazać konkretne punkty.

**Comment by bozenadula** [comment]
@Lukasz-Zurek czy te pola powinny być zawsze w zapytaniu? testowaliśmy też dostawę 'Allegro Kurier DPD' i błąd był ten sam. Zawsze wysyłamy od nas z magazynu, a paczki odbiera kurier. Nie wiem więc co wpisywać w sender.point i pickup.point. Czy receiver.point przychodzi w pakiecie danych zamówienia allegro. Rozumiem, że jest jakiś numer paczkomatu, czy punktu odbioru, ale co gdy wysyłamy na adres domowy?  Macie listę, które metody dostawy wymagają tych danych?

**Comment by Lukasz-Zurek** [comment]
@bozenadula Tak. Prześlij proszę przykładowe trace-id dla Allegro Kurier DPD. Wyjaśnimy to.

Jeżeli chodzi o Allegro one box, one kurier to bazujemy na punktach wskazanych przez Klienta na etapie zamówienia. Generalnie usługa "Wysyłam z Allegro" bazuje na danych z zamówienia.

Nie posiadamy listy metod wymagających wskazania identyfikatora punktu. Natomiast w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke) opisujemy to jak korzystać **pickup.point** i **receiver.point**.

Jeżeli używasz powyższych pól, możesz je wypełnić wartością pobraną:

- ze szczegółów zamówienia, za pomocą GET /order/checkout-forms/{id}, w polu: **delivery.pickupPoint.id**,
- z API odpowiedniego przewoźnika. Model każdego z nich jest różny, dlatego odwołaj się bezpośrednio do dokumentacji API przewoźników (przykładowe wartości poszczególnych przewoźników w podlinkowanym poradniku).

**Comment by bozenadula** [comment]
Zanim zajmę się powyższym, potrzebuję pomocy w przedłużeniu ważności tokena. Pisałeś, że REDIRECT_URI nie jest potrzebne. To w jaki sposób pozyskać authorization code, żeby rozpocząć proces? Jeżeli redirect_uri zdefiniujemy jako pusty string to otzrymujemy adres strony, której nie można wyświetlić 
![image](https://github.com/allegro/allegro-api/assets/103446565/9d9ac35a-6e4c-457d-9aae-ac1b104e726b)
, jeśli zaś skrócimy link po client_id to otrzymujemy błąd 
![image](https://github.com/allegro/allegro-api/assets/103446565/6146ce16-98b0-404f-baf7-cf0e1abd55cb)
Możecie coś podpowiedzieć. Oczywiście chodzi o tę część[ dokumentacji ](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena) 
![image](https://github.com/allegro/allegro-api/assets/103446565/80ab5a17-b123-4aea-9523-00b0265a57e9)

**Comment by Lukasz-Zurek** [comment]
@bozenadula Kod uwzględnia cały proces generowania tokena metodą [Authorization Code Flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#autoryzacja-uzytkownika). Tam również udostępniamy pierwszą część (z przytoczonego powyżej) kodu, odpowiedzialną za autoryzację (bez procesu odświeżania ważności tokena). W procesie tym wymagamy redirect_uri.

Natomiast przy odświeżaniu access_tokena (grant_type=refresh_token) nie potrzebujesz już kodu autoryzującego, redirect_uri nie jest zatem wymagane.

**Comment by bozenadula** [comment]
@Lukasz-Zurek udało mi się zrealizować i pozyskiwanie tokenów i generowanie przesyłek. Moja pierwsza w życiu integracja "Jestem zwycięzcą" ;-) Przede mną anulacja oraz pobieranie zdarzeń związanych z przesyłką. Dziękuję za dotychczasową pomoc i wsparcie. Wydaje mi się, że możemy zamknąć wątek. Miłego dnia.

**Comment by Lukasz-Zurek** [comment]
@bozenadula Bardzo się cieszę :-) Oczywiście gdyby pojawiły się jakieś dodatkowe pytania dotyczące innych procesów/funkcjonalności w API, chętnie pomogę.

Również życzę miłego dnia.
