### ISSUE TITLE
Dostawa z Polski

### ISSUE THREAD

**Issue by SoftSolid** [allegro/allegro-api#852]
Większość aukcji nie chce mi się wznowić bo nie ma ustawionego parametru "Dostawa z Polski".
Oczywiście ma to ustawione ale stare API zwraca sellFormId = 34858 "Dostawa z Polski" a nowe zwraca id= 128188 "Dostawa z Polski" dla tej samej kategorii.
Przy wznawianiu wymaga nowego ID którego a my nawet nie możemy pobrać przez stare API bo się nie pobiera. Id kategorii o której mówię to 112112 - Majtki :).

**Comment by Uriziel01** [comment]
Witamy w API Allegro ;)

**Comment by TomekKaczmarek** [comment]
@SoftSolid to, z którego API korzystasz nie powinno mieć znaczenia. I WebAPI i REST API powinny Tobie pozwolić uzupełnić brakujące parametry. Aczkolwiek, tylko przez REST API możesz wprowadzać zmiany w zakończonej ofercie.

Podeślij proszę kilka przykładowym identyfikatorów ofert, w których otrzymujesz ten błąd. Ustawiłeś automatyczne wznowienie oferty, czy korzystasz z metody doSellSomeAgain?

**Comment by SoftSolid** [comment]
Wznawiam przez nowe REST API. Problem jest w tym, że nie chce mi wznowić aukcji ponieważ brakuje ustawionego parametru "Dostawa z Polski". Wygląda na to, że wznawianie przez REST API wymaga parametru o ID 128188. A tego parametru nie ma przez stare API. Przez stare API jest id 34858 - "Dostawa z Polski". I ustawienie tego nic nie daje bo wymagane jest id 128188.

**Comment by TomekKaczmarek** [comment]
@SoftSolid podaj proszę ID takiej oferty.
