### ISSUE TITLE
Produkturyzacja, stan: używany - EAN wymagany, czy niewymagany?

### ISSUE THREAD

**Issue by Lukasz-Zurek** [allegro/allegro-api#8520]
### Discussed in https://github.com/allegro/allegro-api/discussions/8518

<div type='discussions-op-text'>

<sup>Originally posted by **Kuba-Id** February 21, 2024</sup>
Przy wywołaniu funkcji: sale/categories/16482/parameters
Id: **16482** - to "**Rowery i akcesoria / Rowery / Miejskie**"

Mamy informację od API:

    [20] => stdClass Object
        (
            [id] => 225693
            [name] => EAN (GTIN)
            [type] => string
            [required] => 1
            [requiredForProduct] => 1
            [requiredIf] => stdClass Object
                (
                    [parametersWithValue] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [id] => 11323
                                    [oneOfValueIds] => Array
                                        (
                                            [0] => 11323_1
                                        )

                                )

                        )

                    [parametersWithoutValue] => Array
                        (
                        )

                )

            [displayedIf] => 
            [unit] => 
            [options] => stdClass Object
                (
                    [variantsAllowed] => 
                    [variantsEqual] => 
                    [ambiguousValueId] => 
                    [dependsOnParameterId] => 
                    [describesProduct] => 1
                    [customValuesEnabled] => 
                )

            [restrictions] => stdClass Object
                (
                    [minLength] => 8
                    [maxLength] => 14
                    [allowedNumberOfValues] => 1
                )

        )

Wnioskujemy, że parametr EAN - dla nowego produktu jest wymagany, jeśli w produkcie w parametrze: **11323 (Stan)** pojawi się wartość: **11323_1 (Nowy)**.

Oferta ma natomiast ustawioną dla parametru:  **11323 (Stan)**, wartość: **11323_2 (Używany)**.

Rower jest "używany", nie "nowy", zatem EAN nie powinien być wymagany.

Dobrze zakładam?

Po wykonaniu produkturyzacji, metodą "**sale/product-proposals**" dla kategorii: 16482
Mamy odpowiedź API:

`{"error_message":"B\u0142\u0105d podczas dodawania produktu do bazy Allegro: UnableToCreateProductWithoutAllRequiredParametersException.\nNie mo\u017cna stworzy\u0107 produktu bez podania poprawnych warto\u015bci wszystkich parametr\u00f3w wymaganych: [EAN (GTIN)]","errors":true,"success_url":"\/admin\/allegro-product\/index\/column\/id\/dir\/desc\/page\/1\/product\/157210\/id\/157210"}`

sale/product-proposals - chce jednak EAN, dla roweru używanego? Mimo, że metoda:
"**sale/categories/16482/parameters**", zwróciła informację, iż EAN jest wymagany, tylko, jeśli rowery jest nowy.

Trace ID:  dee6f28c0c9f7914

Będę bardzo wdzięczny za pomoc, wyjaśnienie!</div>

**Comment by Lukasz-Zurek** [comment]
@Kuba-Id Dziękuję za szczegółowe dane. Weryfikuję ten przypadek i wkrótce wrócę do Ciebie z informacją.

**Comment by Lukasz-Zurek** [comment]
@Kuba-Id Wymagalność i zależność, o której piszesz - obejmuje tutaj proces wystawiania, natomiast w tej sytuacji próbujesz utworzyć nowy produkt za pomocą **sale/product-proposals**. EAN dla tej kategorii jest wymagany do utworzenia produktu, dlatego zwracamy wspomniany komunikat.

**Comment by Kuba-Id** [comment]
W jaki sposób w takim razie mam skutecznie sprawdzać informację: jakie parametry są obowiązkowe przy tworzeniu nowego produktu?
Za pomocą jakiej funkcji?

**Comment by Lukasz-Zurek** [comment]
@Kuba-Id Sprawdzisz to za pomocą **/sale/categories/16482/parameters**. Zwróć uwagę na pole **"requiredForProduct"** - jeżeli wartość = **true**, to oznacza, że parametr ten jest wymagany do utworzenia nowego produktu.

**Comment by Kuba-Id** [comment]
Czyli podsumowując:

1. Dla produkturyzacji, jeśli mamy:
requiredForProduct - jeśli mamy true - to parametr jest wymagany bezwzględnie? Zawsze?

2. requiredIf - w takim razie jaki ma sens ta właściwość? Do jakiego procesu ma ona znaczenie?

**Comment by Lukasz-Zurek** [comment]
@Kuba-Id 

1. Tak. Bez tego parametru nie utworzysz produktu.
2. Zależności te są istotne w procesie wystawiania ofert.

**Comment by Kuba-Id** [comment]
Ten sam produkt - rower używany, można wystawić z poziomu panelu Allegro, bez podawania numeru EAN.
Dlaczego zatem, jest on potrzebny przy wystawianiu za pomocą API?

Testowaliśmy to i ręcznie w panelu, dało się produkt wystawić, bez podawania numeru EAN.

**Comment by Kuba-Id** [comment]
Panie Łukaszu, a można wystawić za pomocą API ofertę z rowerem używanym bez wykonywania uprzednio produkturyzacji, aby nie podawać numeru EAN o którym mowa w podanym wątku?

Chodzi o sytuację, w której wystawiamy ofertę, lecz nie wskazujemy produktu do której oferta ma być przypisana.

Należałoby to zrobić w taki sposób:

[https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem)

Wystawianie oferty z produktem > sekcja "Aktywną ofertę powiązaną z produktem, którego nie ma w naszym Katalogu. "

Czyli dane do oferty i produktu podajemy w jednym Requeście. Wtedy produkt: rowery UŻYWANY (które nie potrzebuje EAN'u), bo się wystawił?

**Comment by Lukasz-Zurek** [comment]
Tak, ale to również zależy od wskazanej podkategorii. Przykładowo w rowerach miejskich (16482) - parametr EAN jest wymagany tylko dla wartości “Nowy” w parametrze Stan:Musiałbyś sprawdzić dokładne zależności w pozostałych podkategoriach.
