### ISSUE TITLE
Moje konto sandbox nadal nie jest aktywne

### ISSUE THREAD

**Issue by prestt** [allegro/allegro-api#8521]
Założyłem i zweryfikowałem konto Sandbox wczoraj (login: maxsote), nadal nie jest aktywne, z tego co czytam to powszechny problem - prosiłbym o aktywację :)

**Comment by Lukasz-Zurek** [comment]
Aktywowałem konto :)

**Comment by prestt** [comment]
Bardzo dziękuję :)
