### ISSUE TITLE
WZA - DPD pobranie - COD_IBAN_NOT_VERIFIED

### ISSUE THREAD

**Issue by matcapi** [allegro/allegro-api#8523]
Dzień dobry,

Gdy próbuję wysłać paczkę w sandbox metodą DPD pobranie, to dostaję taki błąd:
```
{
    +"code": "COD_IBAN_NOT_VERIFIED"
    +"message": "This delivery option requires a verified Polish IBAN number"
    +"details": "Provided Iban has to be verified"
    +"path": "additionalServices"
    +"userMessage": "Wybrana metoda dostawy wymaga podania zweryfikowanego, polskiego numeru iban"
}
```
konto: sma-asport
uuid: 49e6b823-9725-4554-91e6-53cdd2e29aa0
trace-id: 3f04d8cd4925d474

Czy przesyłany numer IBAN musi pokrywać się z tym, ustawionym w konfiguracji konta allegro? 
Jeśli tak, to gdzie mogę go sprawdzić?

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, numer musi się pokrywać. Sprawdzisz go w zakładce [Ustawienia Wypłat](https://allegro.pl/moje-allegro/sprzedaz/ustawienia-wyplat).
