### ISSUE TITLE
Problem z aktywacją konta firmowego na środowisku testowym Sandbox

### ISSUE THREAD

**Issue by dejw28** [allegro/allegro-api#8524]
Zmieniłem konto na firmowe na środowisku testowym Sandbox (login: DejwShop), w dalszym ciągu mam odpowiedź z api "Prowadząc sprzedaż na koncie zwykłym (nie zarejestrowanym jako konto firma), nie możesz korzystać z tej metody Publicznego API" - prosiłbym o aktywację.

**Comment by Lukasz-Zurek** [comment]
@dejw28 Aktywowałem wskazane konto.
