### ISSUE TITLE
problem z usuwaniem przesyłki

### ISSUE THREAD

**Issue by YpsilonSH** [allegro/allegro-api#8527]
Wg dokumentacji przesyłki można usuwać:
 Jak anulować paczkę
Jeżeli utworzono paczkę, ale np. nieprawidłowo wypełniono niektóre dane, możesz ją anulować za pomocą [POST /shipment-management/shipments/cancel-commands](https://developer.allegro.pl/documentation/#operation/cancelShipment). W polu “shipmentId” przekaż identyfikator paczki, którą chcesz usunąć.

Nie możesz anulować paczki odebranej przez kuriera lub nadanej w paczkomacie.

Przesyłka świeżo utworzona omyłkowo.
Po wywołaniu komendy usunięcia przez API, gdy sprawdzam status usunięcia za pomocą [GET /shipment-management/shipments/cancel-commands/{commandId}] dostaję odpowiedź:
"{""commandId"":""c1be1d1b-1c72-48d6-a440-cf2114313c2c"",""status"":""ERROR"",""errors"":[{""code"":""PROCESSING_ERROR"",""message"":""Problem with dispatch. Contact us, and we will help as soon as possible."",""details"":null,""path"":null,""userMessage"":""Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.""}],""shipmentId"":null}"
i nie zostaje ona usunięta. W serwisie www również polecenie "ANULUJ PRZESYŁKĘ" jest poszarzałe i niedostępne.

**Comment by Lukasz-Zurek** [comment]
@YpsilonSH Dziękuję Ci za zgłoszenie. Przekazałem ten przypadek dalej do weryfikacji.

**Comment by YpsilonSH** [comment]
Jeszcze weryfikują?

**Comment by Lukasz-Zurek** [comment]
@YpsilonSH Przepraszam za dłuższy czas oczekiwania na odpowiedź.

Nie możesz anulować:
* paczek ze wskazaną metodą dostawy z “carrierId”: “ALLEGRO”,
* pozostałych paczek odebranych przez kuriera lub nadanych w paczkomacie.”

Tę właśnie informację zaktualizowaliśmy w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-anulowac-paczke).

Natomiast co do błędu - zwracaliśmy nieprawidłowy/nieczytelny komunikat błędu, ale został już on przez nas poprawiony.

**Comment by LucasCichon** [comment]
W jaki sposób można przetestować anulowanie przesyłem na allegro.sandbox?

**Comment by Lukasz-Zurek** [comment]
@LucasCichon Zapoznaj się proszę z naszym [poradnikiem](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#srodowisko-testowe), gdzie opisujemy szczegóły dotyczące sposobu działania środowiska testowego sandbox, adresy wywołania zasobów, itd.
