### ISSUE TITLE
Błędne dane zwracane przez doGetItemsInfo

### ISSUE THREAD

**Issue by szymon-convertis** [allegro/allegro-api#853]
Dzień dobry,
Podczas pobierania informacji o aukcjach poprzez webapi za pomocą metody doGetItemsInfo otrzymuję dla niektórych aukcji błędne dane.
Np dla aukcji 7317171883 wycinek zwracanych danych to:

stdClass Object
(
    [itemInfo] => stdClass Object
        (
            [itId] => 7317171883
            [itCountry] => 1
            [itName] => Zielone sandały damskie, szpilki VICES 1166-31 r39
            [itEndingTime] => 0
            [itEndingInfo] => 1
      )
)

Wg dokumentacji, itEndingInfo = 1 oznacza, że aukcja wciąż trwa natomiast aukcja tak naprawdę jest już zakończona:|
https://allegro.pl/zielone-sandaly-damskie-szpilki-vices-1166-31-r39-i7317171883.html

Próba zakończenia takiej aukcji poprzez metodę doFinishItems kończy się oczywiście błędem ERR_YOU_CANT_CHANGE_ITEM 

proszę o informację o przyczynach takiego działania webapi.

**Comment by rtnet-pl** [comment]
https://github.com/allegro/allegro-api/issues/61

**Comment by szymon-convertis** [comment]
Dzięki ale ten problem znam i jego obejście juz mam napisane 

W aktualnym pytaniu chodzi o bląd w drugą stronę, czyli aukcja jest zakończona a w webapi widnieje jako trwająca. I niestety nie trwa to kilkunastu minut ale dużo dlużej

**Comment by PawelTaberski** [comment]
Rzeczywiście jest jakiś problem w przypadku tej oferty, proszę o cierpliwość badamy sprawę.

**Comment by szymon-convertis** [comment]
dziękuję, Poniżej lista aukcji z którymi dzisiaj mieliśmy problem:
    [0] => 7260834661
    [1] => 7261807629
    [2] => 7262701069
    [3] => 7263078723
    [4] => 7263707112
    [5] => 7308030225
    [6] => 7317171883

**Comment by szymon-convertis** [comment]
Kiedy można się spodziewać odpowiedzi?

**Comment by PawelTaberski** [comment]
Pracujemy nad rozwiązaniem tego problemu, prosimy o jeszcze trochę cierpliwości.
