### ISSUE TITLE
GET /payments/payment-operations

### ISSUE THREAD

**Issue by fabMoth4n** [allegro/allegro-api#8533]
Witam,

do niedawna w zasobie [GET](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory) w grupie OUTCOME dostawaliśmy informacje o wypłatach z konta, a w tym momencie przychodzą same prowizje od sprzedaży. Jak pobrać informacje o wypłatach?

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem działanie endpointu - zwracamy zdarzenia z grupy OUTCOME, w tym wypłaty. Proszę podaj konkretne trace-id bym mógł zweryfikować przypadek.

**Comment by fabMoth4n** [comment]
trace id: b8fc6912bf50a98d

**Comment by fabMoth4n** [comment]
OK wypłaty się już pojawiły. Proszę mi jeszcze powiedzieć gdzie w takim obiekcie jest umieszczona informacja o tym, że to jest wypłata środków?
object(stdClass)[1360]
  public 'type' => string 'DEDUCTION_CHARGE' (length=16)
  public 'group' => string 'OUTCOME' (length=7)
  public 'wallet' => 
    object(stdClass)[1361]
      public 'paymentOperator' => string 'PAYU' (length=4)
      public 'type' => string 'AVAILABLE' (length=9)
      public 'balance' => 
        object(stdClass)[1362]
          public 'amount' => string '1000' (length=6)
          public 'currency' => string 'PLN' (length=3)
  public 'occurredAt' => string '2024-02-22T12:29:50.493Z' (length=24)
  public 'value' => 
    object(stdClass)[1363]
      public 'amount' => string '-34.07' (length=6)
      public 'currency' => string 'PLN' (length=3)
  public 'marketplaceId' => string 'allegro-pl' (length=10)
  public 'deduction' => 
    object(stdClass)[1364]
      public 'id' => string '8e9d1b0f-dc4f-45bc-9b83-bf8d12b1cb42'

**Comment by MaciejFrackowiak** [comment]
Wypłaty oznaczone są w polu "type" wartością "PAYOUT". Jak widzę, ostatnie takie zdarzenie miało miejsce - "occurredAt": "2024-02-21T23:34:59.057Z".
