### ISSUE TITLE
Problem przy wywołaniu /order/events?type=READY_FOR_PROCESSING&from=1708691889591911

### ISSUE THREAD

**Issue by e-macs** [allegro/allegro-api#8534]
Mam dziwny problem co jakiś czas z wywołaniem zasobu z tytułu, przykład błędu poniżej. 
Trace-id e70cd68a9100f04e

Czy możecie mi pomóc? 
Mam taki mechanizm, że odpytuję API co jakiś czas o nowe eventy, i zapisuje sobie ostatni zwrócony.
I czasem dla konkretnych klientów mam błąd jak niżej.

HTTP/1.0 404 Not Found expires: 0 cache-control: no-cache, no-store, max-age=0, must-revalidate x-xss-protection: 0 pragma: no-cache referrer-policy: no-referrer date: Mon, 26 Feb 2024 16:00:18 GMT trace-id: e70cd68a9100f04e x-content-type-options: nosniff content-type: application/json content-length: 286 x-frame-options: DENY strict-transport-security: max-age=15552000 {"exception":"[object] (RuntimeException(code: 404): HTTP/1.0 404 Not Found expires: 0 cache-control: no-cache, no-store, max-age=0, must-revalidate x-xss-protection: 0 pragma: no-cache referrer-policy: no-referrer date: Mon, 26 Feb 2024 16:00:18 GMT trace-id: e70cd68a9100f04e x-content-type-options: nosniff content-type: application/json content-length: 286 x-frame-options: DENY strict-transport-security: max-age=15552000

**Comment by MaciejFrackowiak** [comment]
Wskazane trace-id (e70cd68a9100f04e) prowadzi do wywołania GET /order/checkout-forms/08a06571-3a44-11ed-8f60-317c9563e60a. Zwróciliśmy 404 Not found, ponieważ zamówienie to pochodzi z 22.09.2022 09:00 - a zwracamy szczegóły zamówień z okresu ostatnich 180 dni.

**Comment by e-macs** [comment]
dzięki wielkie, udało się rozwiązać problem
