### ISSUE TITLE
PATCH /sale/product-offers/{offerId}: błąd 422

### ISSUE THREAD

**Issue by RobertCh2** [allegro/allegro-api#8535]
Usiłuję uaktualnić »Kod producenta« w ofercie, wysyłam json: {"productSet":[{"product":{"parameters":[{"id":"224017","name":"Kod producenta","values":["0103010"],"valuesIds":null,"rangeValue":null}]}}]}. Dostaję błąd 422. Co może być źle?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swojego wywołania.

**Comment by RobertCh2** [comment]
437980f53b0ffde4

**Comment by MaciejFrackowiak** [comment]
Jak widzę otrzymałeś całą listę "wyjaśnień" wraz z błędem 422:
- Uzupełnij parametry obowiązkowe: Marka, Nazwa handlowa, Waga, EAN (GTIN).
- Niepoprawna wartość parametru EAN/ISBN/ISSN (225693) dla produktu w ofercie. Prawidłowa wartość parametru dla produktu to: "5601655500027"
- Niepoprawna wartość parametru Marka (248926) dla produktu w ofercie. Prawidłowa wartość parametru dla produktu to: "inny"
- Niepoprawna wartość parametru Waga (225117) dla produktu w ofercie. Prawidłowa wartość parametru dla produktu to: "0.190"

Edytując jakąkolwiek tablicę musisz przekazać całą jej zawartość tj. w tym przypadku wszystkie parametry produktowe widniejące w części productSet. Oczywiście, musisz także uzupełnić brakujące parametry zgodnie ze wskazówkami.

**Comment by RobertCh2** [comment]
Dziękuję za wyjaśnienia. Kierowałem się wskazówką z tutoriala: »Skorzystaj z [PATCH /sale/product-offers/{offerId](https://developer.allegro.pl/documentation/#operation/editProductOffers) oraz przekaż w strukturze żądania tylko te pola, które rzeczywiście chcesz zmienić. W pozostałych polach pozostawimy dotychczasową wartość«. Informacja, że w przypadku tablicy trzeba przekazać całą jej zawartość jakoś mnie ominęła.

**Comment by MaciejFrackowiak** [comment]
Poniżej zapisu, który cytujesz jest dodana ramka z:

```
Ważne! Pamiętaj, że w przypadku tablic (np. productSet, images, description) przyjmujemy zasadę wszystko albo nic (zgodnie z RFC7396)....
```

**Comment by RobertCh2** [comment]
Uzupełniłem parametry Marka, Nazwa handlowa, Waga, EAN (GTIN). Nadal dostaję błąd 422. 

Czy muszę jeszcze coś uzupełnić (»wszystkie parametry produktowe widniejące w części productSet«)? Jeśli tak, to gdzie można znaleźć te listę takich parametrów?

Czy można jakoś samodzielnie pozyskać listę »wyjaśnień« do zapytań ?

Trace-ID: d699725e036b86a5.

**Comment by MaciejFrackowiak** [comment]
W odpowiedzi do Twojego requesta zwróciliśmy błąd 422 z informacją, że request zawiera nieprawidłowe dane - pole "path" zdradza miejsce wystąpienia błędu:
```
"path":"productSet[0].product.parameters[0].values"
```
W parametrze Marka (id=248926) przekazujesz wartość niejednoznaczną "inny", a dla kategorii oferty "77742" umożliwiamy dodanie własnej wartości przy parametrze Marka tj. flaga "customValuesEnabled" ma wartość "true".
Co więcej, do Twojej oferty przypisany jest konkretny produkt o id=4b951c35-3ce9-495e-a913-c5c6cd5f848d, zatem edytując ofertę musisz przekazać stricte wartości, które go opisują ([GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct)). Jeżeli tego nie zrobisz to finalnie i tak zwrócimy błąd mówiący o konieczności uwzględnienia danych ze wskazanego produktu.
