### ISSUE TITLE
[OAuth] Nie możemy wyświetlić strony...

### ISSUE THREAD

**Issue by vitalijr2** [allegro/allegro-api#8536]
Tworzę własną integrację z Allegro REST API, sprawdzam proces „Autoryzacja użytkownika” https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#autoryzacja-uzytkownika

Na etapie, w którym muszę przejść do strony w celu potwierdzenia
> **3.** Po poprawnym uwierzytelnieniu užitej zostanie przekierowany do strony, na kwojrzej zgąda się by dana aplikacjacija sławy pozężyce operacji/żądań w jego iminimu:

widzę stronę z identyfikatorem błędu . Czy możecie mi powiedzieć, w czym tkwi problem?
![screenshot_2024-02-27_08-20-42_117508050](https://github.com/allegro/allegro-api/assets/368917/71b3b404-eee4-40c6-a1ad-b7d5ef931a65)

Poprzedni krok dla opcji `prompt=confirm` zakończył się pomyślnie.
![screenshot_2024-02-27_08-21-00_053968056](https://github.com/allegro/allegro-api/assets/368917/b71422aa-4ff0-4d7e-94c3-514db0bd7e52)

**Login**: mama4care
**Client id**: acd8...c806

Nie wiem czy to ważne, ale ja do dostępu zewnętrznego używam serveo.net, oni używają SSL dla domeny tymczasowej

**Comment by MaciejFrackowiak** [comment]
Komunikat, który otrzymałeś sugeruje, że adres przekierowania (redirect URI), który masz podany w aplikacji jest niezgodny z tym, który wprowadziłeś podczas rejestracji aplikacji w sekcji [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/). Adresy muszą być zgodne 1:1.
