### ISSUE TITLE
Błąd podczas generowania tokenu w Authorization Code flow

### ISSUE THREAD

**Issue by SzymonZasada** [allegro/allegro-api#8544]
Próbuje wygenerować token dla konta ale dostaję taki bład - próbowałem z 5x.
Jakoś 2 minuty wcześniej bez problemu wygenerowałem token dla innego konta.
Wszystko na allegro-sanbox

Numer błędu: b59437d117d5b716

**Comment by SzymonZasada** [comment]
Teraz gdy wyświetliło mi numer błędu, ale odświeżyłem stronę po około 5 min( w miedzy czasie pisałem tego postu) to poprawnie wygenerowałem token, chociaż nie jest to do końca rozwiązanie.

**Comment by MaciejFrackowiak** [comment]
Błąd, który otrzymałeś sugeruje, że adres przekierowania (redirect URI), który widnieje w aplikacji nie jest zgodny 1:1 z adresem podanym podczas rejestracji aoplikacji w zakładce [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/). Proszę sprawdź poprawność przekazanego adresu.

**Comment by SzymonZasada** [comment]
Spojrzałem i wszystko jest takie same, właśnie to było pierwsze na co zwróciłem uwagę.

**Comment by MaciejFrackowiak** [comment]
Czy obecnie, udaje Ci się już generować token, z poprawioną wersją redirect URI?

**Comment by SzymonZasada** [comment]
Redirect URI sa takie same w obu aplikacjach(allegro) oraz wspólne w mojej aplikacji. Próbowałem po generować token ale w obu przypadkach randomowo czasem działa czasem nie.

**Comment by MaciejFrackowiak** [comment]
Jeżeli ponownie natrafisz na problem, proszę podaj identyfikator błędu.

**Comment by SzymonZasada** [comment]
oki
