### ISSUE TITLE
Get product price by EAN

### ISSUE THREAD

**Issue by zavovi** [allegro/allegro-api#8546]
Dear Allegro,
I am a developper of internation application for collecting UHD and BluRay movies (Moun Movies - https://www.mounmovies.com) and we have a feature, which show shops and prices for each product with link to the shop. I wanted to add Allegro as a new shop into app with Developper API but I see that it is impossible. Please, could you help me? Is there any other solution? I need only price and link by EAN, nothing more. Now we can accept XML (like Google or Heureka) and we can add any other solution for you.

Please help.
Thank you very much!

**Comment by MaciejFrackowiak** [comment]
No, we do not offer this kind of connection.
