### ISSUE TITLE
How to add your own images

### ISSUE THREAD

**Issue by api-test-yexiu** [allegro/allegro-api#8548]
![image](https://github.com/allegro/allegro-api/assets/155221200/e65ca0d3-3f37-4e8e-a0fe-0e66a6a316d2)

I can't understand the meaning of this explanation. What is the difference between these two ways of writing?

**Comment by MaciejFrackowiak** [comment]
There is one main difference - if you do not provide an offer description we will also add images from our product catalog, no matter if you provide an empty array in the product.images section.

**Comment by api-test-yexiu** [comment]
Can you give an example? I still can't understand what this means
