### ISSUE TITLE
Wtyczka do automatycznego rozliczania wpłat z allegro i banków w subiekt GT

### ISSUE THREAD

**Issue by gwalkowski** [allegro/allegro-api#8549]
Witam, czy zna ktoś jakieś rozwiązanie do automatycznego rozliczania wpłat z allegro w programie sprzedażowym Subiekt GT. Niestety ręczne powiązywanie przelewów z zestawienia allegro i rozliczanie dokumentów w subiet gt zabiera strasznie dużo czasu. Może allegro ma na to lepszy sposób? Mogę opisać nasze działanie obecne:
1.Pobieramy zestawienie miesięczne z allegro wpłat w pliku csv
2.Pobieramy zestawienie z banku ing
3.W exelu szukamy powiązań po nicku klienta
4.Ręcznie rozliczamy dokumenty sprzedażowe w subiekt gt
Może jest jakiś partner allegro który by pomógł w takiej automatyzacji?

**Comment by MaciejFrackowiak** [comment]
Jako Allegro udostępniamy wyłącznie nasze API, natomiast całość procesów związanych z jego implementacją jest już po stronie integratorów. Być może któryś z użytkowników forum będzie mógł Tobie udzielić wskazówek.

**Comment by MBiernat7** [comment]
Witam,
Pisałem dla klienta dokładnie takie narzędzie, skrypt w Pythonie, który bierze CSV z Allegro, łączy się ze Sferą Subiekta GT, wyszukuje nierozliczone FS/PA/ZW po ID transakcji lub loginie + kwocie, i automatycznie zakłada operacje bankowe rozliczające faktury. Obsługuje wpłaty, zwroty, pobrania i wypłaty środków, radzi sobie z rozliczeniami częściowymi i robi jeszcze kilka innych rzeczy. Na koniec wypluwa raport XLSX z porównaniem kwot CSV vs Subiekt, księgowa wie co się rozliczyło i gdzie są rozbieżności.

Jeżeli sprawa jeszcze aktualna daj znać na kontakt@kombinatstudio.pl
