### ISSUE TITLE
Problem z refresh tokenem

### ISSUE THREAD

**Issue by infogos** [allegro/allegro-api#855]
Witam

Napisałem aplikację w php dla rest api i wszystko działa oprócz odświeżenia tokena.
Czy refresh_tokena napewno można użyć po wygaśnięciu access_tokena czyli 12 godzinach?
Pomaga ponowne wejście na logowania allegro i potwierdzenie aplikacji. Przy czym od napisania jej minąłe kilka dni więc napewno nie chodzi o te 365.

Przy próbie odświeżenia otrzymuję takie informacje:
"{"error":"invalid_grant","error_description":"Invalid refresh token: eyJhb....."}"

Access_token ma długość 590 znaków, natomiast refresh_token 650.

Co może powodować problem?

**Comment by PawelTaberski** [comment]
Jesteś pewny, że podajesz najnowszy refresh tzn. uzyskany przy generowaniu poprzedniego tokena dostępowego? Zgodnie z tym co opisaliśmy w naszej instrukcji [tutaj](https://developer.allegro.pl/auth/#refresh-token).

**Comment by infogos** [comment]
Tak, jeszcze raz sprawdziłem. Ostatnio wygenerowany 3 listopada.

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) clientId, userId i środowisko na którym występuje problem. Sprawdzimy w czym jest problem.

**Comment by infogos** [comment]
ClietId i userId to to samo? Wysłałem tylko clientID.

Serwer php 5.6.37, a środowisko aplikacji własne, autorskie.

**Comment by PawelTaberski** [comment]
Client ID to jakby login aplikacji dostajesz go wraz z secretem przy rejestracji aplikacji, a user id to identyfikator konta allegro na którym masz zarejestrowaną daną aplikację.

**Comment by infogos** [comment]
Przesłałem formularz jeszcze raz z clientId i userId.

**Comment by PawelTaberski** [comment]
User Id o jaki prosiłem to identyfikator konta usera w którego imieniu chcesz uzyskać token. Przepraszam za wprowadzenie w błąd zbyt skupiłem się na wyjaśnieniu różnicy :-)

**Comment by PawelTaberski** [comment]
Otrzymaliśmy dane, badamy temat. Proszę o cierpliwość.

**Comment by Onixarts** [comment]
U nas również czasami zdarza się, że token refreshujący staje się niepoprawny. Nie znam niestety szczegółów - jest to tylko informacja od użytkowników. Muszą wtedy ponownie autoryzować aplikację.

**Comment by infogos** [comment]
No jak by się to tylko zdarzało to nie było by tak bardzo źle, ale tu się w ogóle nie chce odświeżyć.

**Comment by Onixarts** [comment]
A jesteś pewien, że nie masz przypadkiem dwóch różnych instancji swojego kodu/dwóch wątków które wzajemnie sobie psują tokeny?

**Comment by infogos** [comment]
Dwóch to nie mam napewno.

**Comment by PawelTaberski** [comment]
@infogos W logach nie widzimy prób odświeżania. Podeślij nam proszę przez nasz [formularz](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) cały request sprawdzimy, czy w nim nie ma jakiś problemów.

**Comment by infogos** [comment]
Tydzień temu były ostatnie próby odświeżania. Potem już codziennie było ręcznie logowane bo aplikacja musiała już działać. To może na 2 dni przestaniemy się logować, żeby odświeżanie zaczęło działać?

**Comment by infogos** [comment]
Tzn żeby się próbowało odświeżać i wtedy coś się da więcej powiedzieć.

**Comment by PawelTaberski** [comment]
Tak, wtedy bylibyśmy w stanie wychwycić w logach czy jest problem, a jeśli tak to gdzie.

**Comment by infogos** [comment]
To logowanie wstrzymane. Teraz system będzie sam próbował odświeżać tokeny.

**Comment by infogos** [comment]
W moim systemie mam od wczoraj od 12:00 błędy (system uruchamia się co 3 godziny). Z kiedy te logi poprawne są? Wcześniej przed 12:00 wczoraj 14 listopada czy później?

**Comment by PawelTaberski** [comment]
Widzimy, że wczoraj o 12 próba zakończyła się sukcesem

**Comment by infogos** [comment]
Czy jak podam jaki mam aktualnie refresh token to czy możecie sprawdzić czy jest poprawny?

**Comment by PawelTaberski** [comment]
Oczywiście, ale podeślij nam takie informacje przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619), w zgłoszeniu zaznacz, że informacja jest potrzebna do ticketa numer 855 na GitHub-ie.

**Comment by infogos** [comment]
Hm... ale ja go podmieniam na nowy. Czy w logach widać, że próbowałem odświeżać tym samym cały czas?
Dzisiaj rano przesłałem aktualny refresh token jaki mam zapisany w bazie. Nie wiem czy już do Was dotarł.

Czy refresh tokena można użyć po 12 godzinach czyli po wygaśnięciu normalnego tokena?

**Comment by PawelTaberski** [comment]
Widzimy, że jak przechodzisz całą ścieżkę autoryzacji to bierzesz najnowszego refresha i przy pierwszym odświeżeniu z niego korzystasz i działa. Niestety przy kolejnych próbach również korzystasz z tego pierwszego i wtedy już nie działa. Potem po pewnym czasie znów przechodzisz całą ścieżkę i sprawa się powtarza. Wygląda na to że nie podmieniasz refresha na najnowszego przy kolejnych próbach.

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem, o którym fragmencie dokumentacji mówisz, przedłużenie ważności tokena opisaliśmy [tutaj](https://developer.allegro.pl/auth/#refresh-token) i request jest inny niż w przypadku autoryzacji.

**Comment by infogos** [comment]
Chodzi mi o odpowiedź serwera. Jest tam napisane przy przedłużaniu, że odpowiedź jest taka sama. Jest pokazane, że jest parametr scope ale przy go w rzeczywistości nie ma.

**Comment by PawelTaberski** [comment]
Rzeczywiście, przy najbliższym wdrożeniu na stronę poprawimy. Dzięki za doprecyzowanie.

**Comment by kris86k** [comment]
Jeśli to nie tajemnica to czy mógłbyś wrzucić część swojego kodu odpowiadającego za odświeżanie tokena?
