### ISSUE TITLE
DPD Punkt Odbioru PL16618

### ISSUE THREAD

**Issue by randomWro** [allegro/allegro-api#8550]
Dzień dobry, 
czy DPD Punkt umożliwia nadanie wielu paczek w jednym zapytaniu?

trace-id :
6f65fdf661697db7

Zapytanie wygląda na poprawne, lecz w odpowiedzi otrzymujemy 400 Bad Request.
{"errors":[{"code":"ERROR","message":"Bad Request","details":null,"path":null,"userMessage":"Bad Request"}]}

**Comment by MaciejFrackowiak** [comment]
Spójrz proszę na swój request - przekazujesz dwukrotnie pole "type" - raz w głównej strukturze, raz pod "items".

**Comment by randomWro** [comment]
Wysyłając zapytanie korzystam z https://api.allegro.pl/parcel-management/parcel-create-commands/

według dokumentacji type jest wysyłany podwójnie:

![obraz](https://github.com/allegro/allegro-api/assets/141820933/02d9c7e6-cb00-4b9a-907f-a866598d150d)

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, można podać dwojako type. W swoim requeście na pewno wprowadzasz kod pocztowy w nieprawidłowym formacie (bez -) oraz zapomniałeś przy wadze o value.

**Comment by randomWro** [comment]
Wszystkie dane zostały podane poprawnie, podczas zapytania. Problem został rozwiązany przez nasz dział IT.

![obraz](https://github.com/allegro/allegro-api/assets/141820933/a23fda30-ffa4-4cb6-90ef-db0a12b44e11)
![obraz](https://github.com/allegro/allegro-api/assets/141820933/6cbeb32a-d110-4fb2-b631-0e8f0d300ee2)
