### ISSUE TITLE
Obsługa zamówień dla różnych serwisów 

### ISSUE THREAD

**Issue by Eryk1997** [allegro/allegro-api#8553]
Chciałbym zrobić obsługę zamówień dla danego konta allegro pod konkretny serwis.

Czy należy pobrać serwisy dla konta z -> https://developer.allegro.pl/documentation#operation/marketplacesGET. Następnie korzystać z pobranych zasobów w celu manewrowania jakie zamówienia chciałbym pobierać?

**Comment by Lukasz-Zurek** [comment]
Co do korzystania ze wskazanego zasobu do pobrania serwisów - za pomocą [GET /marketplaces](https://developer.allegro.pl/documentation#operation/marketplacesGET) sprawdzisz ID serwisów, w których użytkownik może wyświetlić swoje oferty, a także inne dane, które dotyczą konkretnego serwisu, np. języki, w jakich oferta może być utworzona, a także wyświetlona kupującemu, jak również dostępne waluty oraz kraje dostawy.

Natomiast obiekt **"marketplace"** zwracany na zamówieniach czy eventach - określa (w polu **"id"**) identyfikator serwisu, w którym kupujący zakupił przedmiot. Za pomocą parametru wyszukiwania **"marketplace.id"** możesz filtrować zamówienia per serwis, a więcej na ten temat przeczytasz [tutaj](https://developer.allegro.pl/tutorials/wystawianie-i-zarzadzanie-oferta-w-serwisach-zagranicznych-wwzjP4M8gTZ#zarzadzanie-zamowieniami).

**Comment by Eryk1997** [comment]
Dobrze, czyli tak jak pisałem najlepiej jest pobrać marketplace dla danego konta, a następnie udzielić możliwość wyboru z którego marketplace.id chce pobierać zamówienia.

**Comment by Lukasz-Zurek** [comment]
@Eryk1997 Tak, dokładnie.
