### ISSUE TITLE
Czy istnieje możliwość zgłaszania Badge campaigns dla Allegro CZ?

### ISSUE THREAD

**Issue by glorifyingpeace** [allegro/allegro-api#8554]
Czy istnieje możliwość zgłaszania Badge campaigns dla Allegro CZ?

**Comment by glorifyingpeace** [comment]
Ok, to widziałem i super.
Będę miał informacje o kampaniach trwających.
Teraz muszę przez POST zgłosić propozycję oferty:
https://api.{environment}/sale/badges

Jak powinien wyglądać ten payload?
{
"campaign": {
"id": "BARGAIN"
},
"offer": {
"id": "12345678"
},
"prices": {
"bargain": {
"amount": "9.99",
"currency": "PLN"
}
}
}

**Comment by Lukasz-Zurek** [comment]
Za pomocą wspomnianego [GET /sale/badge-campaigns](https://developer.allegro.pl/documentation/#operation/badgeCampaigns_get_all) szukasz kampanii na rynek czeski i jej identyfikator przekazujesz na [POST /sale/badges](https://developer.allegro.pl/documentation/#operation/postBadges).

Na produkcji póki co zwracamy tylko jedną kampanię: "ALLEGRO_PRICES_CZ". Z czasem zapewne pojawią się kolejne.

Natomiast na sandboxie jest tego zdecydowanie więcej.

**Comment by glorifyingpeace** [comment]
Zrobiłem kilka zgłoszeń ale za każdym razem mam odpowiedź:

`{
    "id": "8895815c-699f-4463-b016-98c1f5ef6b56",
    "createdAt": "2024-02-29T14:08:54.025Z",
    "updatedAt": "2024-02-29T14:08:54.547Z",
    "campaign": {
        "id": "ALLEGRO_PRICES_CZ"
    },
    "offer": {
        "id": "15197095540"
    },
    "prices": {
        "bargain": {
            "amount": "200.00",
            "currency": "CZK"
        },
        "market": null
    },
    "purchaseConstraints": null,
    "process": {
        "status": "DECLINED",
        "rejectionReasons": [
            {
                "code": "BB0",
                "messages": [
                    {
                        "text": "An error occurred while processing the submission. Try again later.",
                        "link": null
                    }
                ]
            }
        ]
    }
}`

**Comment by Lukasz-Zurek** [comment]
@glorifyingpeace Wyjaśniam to z odpowiednim zespołem. Wkrótce wrócę do Ciebie z informacją.

**Comment by glorifyingpeace** [comment]
Dziękuję za odpowiedź. Czy jestem w stanie zgłaszać oferty do Allegro days CZ?
