### ISSUE TITLE
Monitor / Licznik zamówień do zrealizowania

### ISSUE THREAD

**Issue by Blady999** [allegro/allegro-api#8555]
Czy ktoś dysponuje rozwiązaniem umożliwiającym wyświetlanie ilości zamówień do zrealizowania z podziałem na konkretnych przewoźników?
Coś w rodzajku.
OneBox: x
Inpost : x 
DPD: x
itp.

**Comment by MaciejFrackowiak** [comment]
Jako Allegro nie dysponujemy takim rozwiązaniem, ale być może któryś z użytkowników formum będzie mógł Tobie udzielić wskazówek.
