### ISSUE TITLE
Płatność za pobraniem w Allegro Pocztex

### ISSUE THREAD

**Issue by matcapi** [allegro/allegro-api#8556]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry,

W allegro sandbox mam zamówienie ac42bc5b-6fe5-3e33-a152-ef03d994f7eb, płatność za pobraniem, Allegro Pocztex.
Jednak metoda wysyłki 093d950b-8497-4cc7-aa2a-6081e5e7e7e2 jest oznaczona jako nieobsługująca płatności za pobraniem.
Jest to błąd, czy wybieram złą metodę wysyłki?

Dziękuję i pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Wygląda, że przekazujesz nieprawidłową metodę wysyłki. Próbowałem wyszukać podane przez Ciebie id zamówienie, jednak nie znalazłem go. Zasada jest jedna - jako metodę wysyłki przekazujesz identyfikator pobrany z zamówienia, z pola delivery.method.id.

**Comment by matcapi** [comment]
Wyląda na to, że podałem id szczegółów zamówienia (https://allegro.pl.allegrosandbox.pl/moje-allegro/zakupy/kupione/ac42bc5b-6fe5-3e33-a152-ef03d994f7eb). 

Poprawny numer zamówienia: d2f543e0-d197-11ee-924d-9d08fe4f593a
Jego metoda wysyłki: 193d950b-0082-408f-9192-6081e5e7e7e2

Nie widzę by ta metoda była zwracana przez parcel-management/delivery-services.

**Comment by MaciejFrackowiak** [comment]
Metoda Allegro Kurier Pocztex pobranie wymaga umowy własnej, dlatego nie jest zwracana domyślnie w /parcel-management/delivery-services.

**Comment by matcapi** [comment]
Dziękuję za wyjaśnienie.
