### ISSUE TITLE
Zablokowana sprzedaż - informacja z API

### ISSUE THREAD

**Issue by kamiljozwik** [allegro/allegro-api#8557]
Na jednym z moich produkcyjnych kont widzę komunikat:

> Sprzedaż na Twoim koncie jest obecnie zablokowana. 
> Powodem mogą być nieopłacone rachunki lub inne naruszenia Regulaminu. Aby odblokować możliwość sprzedaży, ureguluj zaległe płatności lub skontaktuj się z nami.

Czy istnieje w API endpoint, który zwróciłby mi informacje o blokadach nałożonych na moje konto?

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma takiego endpointu w API Allegro.
