### ISSUE TITLE
Finanse / koszty sprzedaży

### ISSUE THREAD

**Issue by kamiljozwik** [allegro/allegro-api#8558]
Korzystając z paneli sprzedawcy pod adresem `https://allegro.pl/moje-allegro/sprzedaz/panel-sprzedawcy` widzę pozycję "Koszty sprzedaży" w kafelku "Finanse". Jest to suma kosztów dla kont na rynkach polskim i czeskim.
Czy jestem w stanie odpytać jakiś endpoint API o dokładnie tę wartość?

**Comment by MaciejFrackowiak** [comment]
W API udostępniamy tylko zasób [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries), który odpowiada za prezentację danych z zakładki [Rozliczenia z Allegro](https://allegro.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro).
