### ISSUE TITLE
Status wznawiania oferty

### ISSUE THREAD

**Issue by kaczorks** [allegro/allegro-api#8559]
Wznawiam oferty za pomocą https://api.allegro.pl/sale/offer-publication-commands/{commandId} ale w zwrocie nie dostaję żadnych błędów mimo że oferta się nie wznowiła z powodu niezgodności parametru z katalogiem który wyniknął już po publikacji oferty. Jak weryfikować czy wznowienie było udane czy nie ? Pobierać ponownie oferty ?

**Comment by MaciejFrackowiak** [comment]
Szczegółowy raport z wykonania zadania pobierzesz korzystając z [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET).

**Comment by kaczorks** [comment]
Czy takie żądanie można sprawdzić zaraz po wysłaniu zadania czy raport będzie dostępny dopiero za jakiś czas ?

**Comment by kaczorks** [comment]
> Szczegółowy raport z wykonania zadania pobierzesz korzystając z [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET).

Czy takie żądanie można sprawdzić zaraz po wysłaniu zadania czy raport będzie dostępny dopiero za jakiś czas ?

**Comment by MaciejFrackowiak** [comment]
Raport zwróci informacje po wykonaniu zadania, zazwyczaj niemal natychmiastowo, choć na wznowienie ofert mamy 60 minut.
