### ISSUE TITLE
[REST][SANDBOX] Nie działa PUT /sale/offers

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#856]
Przy próbie aktualizacji drafta oferty cały czas zwraca błąd:
`{
  "errors": [{
    "code": "INTERNAL_SERVER_ERROR",
    "message": "Internal Server Error",
    "details": null,
    "path": "/sale/offers/6205652837",
    "userMessage": null
  }]
}`

Nawet próbowałem wysłać PUT-em to co dostałem z GET-a, niczego nie zmieniając, ale i tak ciągłe zwraca błąd.

Co ciekawe jeśli na przykład przekaże nieprawidłową wartość wymaganego parametru to prawidłow zwracany jest błąd walidacji.

**Comment by PawelTaberski** [comment]
Obecnie mamy pewne problemy na środowisku testowym, ale pracujemy już nad ich rozwiązaniem. Prosimy o cierpliwość.
