### ISSUE TITLE
Too many requests when getting product detail /sale/products/{product_id}

### ISSUE THREAD

**Issue by ondrados** [allegro/allegro-api#8560]
I need to download all the customer's offers, which is fine, but if I then try to request individual product details that are included in each offer I get `429 Too Many Requests`

I understand that there is a leaky bucket algorithm on this endpoint, but if I understand correctly, it should be applied only after overcoming 9000 requests per minute.

Can you at least give me an estimate of how many requests I can make and and especially how many parallel requests there can be at one time.

Or if there is another way to achieve that I need to get the product detail (I am mainly interested in the GTIN - EAN which is only in detail endpoint) together with the offer.

Thank you!

EDIT:

There is product parameters in productSet but it is missing `identifiesProduct` and `isGTIN` option, so how do I find out if this is the right parameter

**Comment by MaciejFrackowiak** [comment]
No, Leaky Bucket works regardless standard limit of 9000 rpm. We do not share information about its value. 
Using [GET /sale/categories/{categoryId}/product-parameters](https://developer.allegro.pl/documentation/#operation/getFlatProductParametersUsingGET) you will find which parameters are required to be described in product.parameters section.
