### ISSUE TITLE
Waluta nie jest wspierana przez metodę dostawy

### ISSUE THREAD

**Issue by jwmbb** [allegro/allegro-api#8561]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

Dzień Dobry,
Przy tworzeniu etykiety zwraca nam błąd że waluta nie jest wspierana przez metodę dostawy..
Kurier który jest wybrany to Allegro Wysyłka z Polski do Czech - Odbiór w Punkcie Packeta
ID 9d3a5560-4cb9-43f3-8714-c695cff07cd1
w tragu items przekazujemy takie dane value":{"amount":"48.93","currency":"PLN"}
Mogę prosić o informację dlaczego nie przechodzi?

**Comment by MaciejFrackowiak** [comment]
Wartość przesyłki powinna być podana w CZK.

**Comment by jwmbb** [comment]
czy dla każdego kuriera na CZ powinna mieć wartość CZK ? widziałem w innym wątku że dla DPD powinna być PLN

**Comment by MaciejFrackowiak** [comment]
Nie ma jednej reguły. Wszystko zależy od konkretnej metody dostawy i przewoźnika.

**Comment by User1326** [comment]
gdzie znajdę informację jakie waluty mam podawać dla jakiego przewoźnika/metody?
