### ISSUE TITLE
Rest API with shipments

### ISSUE THREAD

**Issue by HerVoj1985** [allegro/allegro-api#8563]
Hello,
we're connecting a client to your API and some things aren't clear to me.

1. If I create a shipment via the "Create new shipment" method, I need to insert somewhere the ID of the order that was created on the allegro shop (some UUID). In which field should I put it?
2. For other work (label printing, protocol printing, shipment cancellation, etc.) I need the shipmentId, which is again some UUID. Can I find it somewhere in the response of the "Create new shipment" method?
3. Can I also find package numbers in the "Create new shipment" response? Or do I have to call the "Get shipment details" method separately (i found waybill field in "packages" node in response of the method "Get shipment details")?
4. If I want to use pickup points (we want to use the methods: Allegro Automaty Paczkowe Zasilkovna, Allegro Odbiór w Punkcie Zasilkovna), do you have a method to download pickup points or should we use the API of the carrier Zasilkovna?

Thank you.

**Comment by MaciejFrackowiak** [comment]
In response to your questions:1
1) No, you do not have to put order.id to create a new shipment request;
2) In response to [GET /shipment-management/shipments/create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/getShipmentCreationStatus) we will return shipmentId;
3) Yes, you have to call [GET /shipment-management/shipments/{shipmentId}](https://developer.allegro.pl/documentation/#operation/getShipmentDetails) to find a waybill;
4) You should use carrier API. We also return in [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET) id of the pickup point chosen by the buyer.

**Comment by HerVoj1985** [comment]
Thank you,
i have additional questions below.

1. So when I create an order in the allegro e-shop and then want to create a shipment and a label via the REST API, don't I need to somehow link this order to the newly created shipment?
2. I still forgot. How can I track the shipment to see where it is currently and we are most interested in the "delivered" and "returned to sender" statuses. Where can I find a list of these statuses and through which method can I track the shipment in this way?
3. After I have created shipments and want to hand them over to the courier, is it necessary to send something else to allegro via the REST API? E.g. confirmation of the list of given shipments (we will print the protocol via the "Get shipments protocol" method).

Thank you.

**Comment by MaciejFrackowiak** [comment]
1. No, you do not need to link the order with the shipment.
2. You can track parcels via [GET /order/carriers/{carrierId}/tracking](https://developer.allegro.pl/documentation/#operation/getParcelTrackingUsingGET).
3. No, it is not necessary. Only a few carriers provide parcel protocols.

**Comment by HerVoj1985** [comment]
Thank you.

**Comment by HerVoj1985** [comment]
I'm sorry. I also forgot to ask if you have a tracking url, where a page with tracking information will be displayed in the browser when clicked? For example: https://allegro.pl/tracking?waybill=AA2333344

**Comment by MaciejFrackowiak** [comment]
Parcel tracking details will be available in the order details: https://allegro.pl/moje-allegro/sprzedaz/zamowienia/

**Comment by HerVoj1985** [comment]
I understand, but I'm interested in the exact URL where I can pass the shipment (shipmentId?) or package number (waybill). We display the given URL in our application so that the user can click on it.

**Comment by HerVoj1985** [comment]
OK, thank you.

**Comment by HerVoj1985** [comment]
And can you send me a list of the final states that the shipment can have? DELIVERED status is clear. What will the final status look like when the shipment is returned back to the sender?

**Comment by MaciejFrackowiak** [comment]
In the resource [response](https://developer.allegro.pl/documentation/#operation/getParcelTrackingUsingGET) schema, you will find every single status.

**Comment by HerVoj1985** [comment]
I understand. In our SW, however, we recognize the final statuses of shipments in order to notify the client. The delivered shipment has the status DELIVERED (in your API example), but we need to know in advance the status (code) of the shipment that will be returned to the sender (eg will have status code RETURNED?).

**Comment by HerVoj1985** [comment]
Ah, No I see. I only looked at the response example and not the response definition. I'm sorry.

**Comment by LucasCichon** [comment]
I have two questions related to this topic:
1. Is it possible to link a shipment with an order?
2. Why is my newly created shipment connected to an order even though I'm not linking it directly? In fact, all the created shipments are connected to the same order.
This is my shipment, created using the API:
![image](https://github.com/user-attachments/assets/8a42895c-a8af-47ae-8c3a-3ec5f693ba6b)
And here is the order ID:
![image](https://github.com/user-attachments/assets/ce9ad959-39e7-45c2-a1b5-6e89338caf42)

**Comment by MaciejFrackowiak** [comment]
@LucasCichon 

1. We automatically match the shipment with the order based on the email address.
2. It looks like you are still using the same transaction email address.
