### ISSUE TITLE
Parameter xxxx should not be specified as in section 'offer'.

### ISSUE THREAD

**Issue by shivson1337** [allegro/allegro-api#8565]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Podczas tworzenia oferty przy wprowadzeniu parametru otrzymujemy błąd 

`Parameter '209066:Maksymalny obwód szyi' should not be specified as in section 'offer'.`

Na pierwszy rzut oka zapytanie wygląda poprawnie. Co robimy nie tak?

**trace-id:** ad3dd72343277622

**Comment by shivson1337** [comment]
Już wszystko wiem ;)

**Comment by drpartsallegro** [comment]
Podziel sie co bylo nie tak
