### ISSUE TITLE
Dodawanie zdjęć produktowych i ofertowych

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#8567]
Chce pomieszać zdjęcia z produktu wraz ze swoimi podczas wystawiania oferty.

Z tego co widzę to endpoint https://api.{environment}/sale/product-offers

ma dwie stryktury "images": 

```
"productSet": [
{
  "product": {
  "name": "iPhone 5s",
  "category": {},
  "id": "c9e39cae-9cb6-11e9-a2a3-2a2ae2dbcce4",
  "idType": "GTIN",
  "parameters": [],
  "images": [
  "string"
  ]
  },
  "quantity": {},
  "responsiblePerson": {}
}
],
```

oraz

```
"images": [
"string"
],
```

Początkowo zakładałem że zdjęcia pochodzące z katalogu produktów powinienem dodawać do struktury wewnątrz "productSet" a swoje własne do "images" - z tego co widzę to działa, natomiast nie mam wtedy możliwości sortowania zdjęć. Mogę też dodać wysztkie do tego bezpośredniego "images" w odpowiedniej kolejności i wtedy też to działa. Jaki jest poprawny sposób?

**Comment by MaciejFrackowiak** [comment]
Jak zauważyłeś, pole "images" występuje dwukrotnie:
1) w productSet.product.images - w tej części dodajesz zdjęcia do produktu, czyli zostaną zachowane w naszej bazie produktów, gdy zatwierdzimy dany produkt. Będą dostępne wraz z produktem dla każdego;
2) w części ofertowej wywołania jako pole "images" - to są zdjęcia stricte ofertowe, które dodajesz Ty i będą dostępne tylko w Twojej ofercie.

Do oferty automatycznie dodajemy zdjęcia z produktu, chyba że przekażesz pustą tablicę [] przy productSet.product.images - wówczas zdjęć z katalogu nie dodamy do Twojej oferty.

Spójrz proszę do [naszego poradnika](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty), gdzie opisujemy zależności związane z obsługą zdjęć.

**Comment by marmited** [comment]
Dobrze, cyzli podczas tworzenia oferty gdy też tworzę produkt powinienem przekazać zdjęcia produktowe w productSet.product.images. Zdjęcia dla  dla tej konkretnej oferty w images. To podejście ostatecznie zamieści na ofercie wszystkie zdjęcia z tych dwóch obszarów, tak?

Zależy mi na tym żeby zarządzać kolejnością tych zdjęć w jasny sposób na ofercie, czy mogę przekopiować zdjęcia produktowe również do "images" i sobie to tam ustawić? Spowoduje to wyświetlenie ich tylko jeden raz w odpowiedniej kolejności?

Drugi przypadek, Tworzenie oferty/edycja z wskazanym produktem z katalogu (jako w productSet.product.id przekazuje identyfikator istniejącego produktu), który ma swoje zdjęcia. Powiedzmy że ma swoje 3 zdjęcia a ja chciałbym z 2 z nich skorzystać. Gdzie przekazać te linki do zdjęć pochodzących z katalogu? jako tablica dwu elementowa w productSet.product.images czy może mogę je wpleść w moje zdjęcia "images", a doproductSet.product.images przekazać pustą tablicę.


Wydaje mi się że te tematy nie są opisane w poradniku.

**Comment by MaciejFrackowiak** [comment]
Nie sposób nam opisać wszystkich kombinacji, które użytkownicy API mają zamiar "wymyślić" - kierujemy się podstawowymi krokami i zasadami.

Odnosząc się do pierwszego akapitu - tak, pamiętaj jednak, że w ofercie maksymalnie może się znaleźć 16 zdjęć. Zatem jeśli dodasz swoich 10, a w produkcie jest już 10, to z produktu dodamy tylko 6.

Jeżeli przekopiujesz zdjęcia z części produktowej, a tam nie wstawiesz pustej tablicy to zdjęcia będą zdublowane.

Najbezpieczniej - pusta tablica + wybrane zdjęcia ofertowe pod "images".

**Comment by marmited** [comment]
Rozumiem, dziękuję.
