### ISSUE TITLE
Prowizja od sprzedaży oferty wyróżnionej - nieścisłości

### ISSUE THREAD

**Issue by maniootek** [allegro/allegro-api#8568]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Nie zgadzają mi się kwoty prowizji względem tego co pokazuje API z zasobu **https://api.allegro.pl/pricing/offer-fee-preview** a tym co pokazuje portal allegro podczas edycji oferty w przeglądarce

zapytanie do zasobu:
```
{
   "offer":{
      "category":{
         "id":"252642"
      },
      "publication":{
         "duration":"PT72H"
      },
      "sellingMode":{
         "format":"BUY_NOW",
         "price":{
            "amount":"269.00",
            "currency":"PLN"
         }
      },
      "parameters":[
         
      ],
      "promotion":{
         "emphasized":true
      }
   }
}
```

odpowiedź:
```
{
   "commissions":[
      {
         "name":"Prowizja od sprzedaży",
         "type":"commissionFee",
         "fee":{
            "amount":"39.71",
            "currency":"PLN"
         }
      },
      {
         "name":"Prowizja od sprzedaży oferty wyróżnionej",
         "type":"commissionFeatureFee",
         "fee":{
            "amount":"29.79",
            "currency":"PLN"
         }
      }
   ],
   "quotes":[
      {
         "name":"Wystawienie przedmiotu",
         "type":"listingFee",
         "fee":{
            "amount":"0.00",
            "currency":"PLN"
         },
         "cycleDuration":"PT240H",
         "classifiedsPackage":null
      },
      {
         "name":"Opłata za wyróżnienie",
         "type":"distinctionFee",
         "fee":{
            "amount":"19.90",
            "currency":"PLN"
         },
         "cycleDuration":"PT240H",
         "classifiedsPackage":null
      }
   ]
}
```

API pokazuje koszty prowizji od sprzedaży 39,71 a na stronie z edycją oferty pisze 28,14-30,13
![image](https://github.com/allegro/allegro-api/assets/45625552/7afa37fd-b9a2-4089-939e-a4eeca1e5fb5)
Jest duża różnica. Coś tu jest nie tak?

**Comment by MaciejFrackowiak** [comment]
Pamiętaj proszę, że wycena w kalkulatorze ma charakter szacunkowy, nie uwzględnia jakichkolwiek zniżek, które masz na koncie. Co więcej, [ostatnio](https://github.com/allegro/allegro-api/issues/8407) wprowadziliśmy zmiany w zasobie - konsekwencją tego jest m.in. zmiana w opcjach promowania, gdzie "emphasized" nie jest już dostępne.

**Comment by MaciejFrackowiak** [comment]
Dodam także, że dla części kategorii istotne jest określenie stanu w ofercie - pomiędzy Nowy a Używany istnieją różnice w kwocie naliczanej prowizji. W swoim requeście nie określiłeś stanu, a jest to kluczowe by uzyskać właściwą wycenę.

**Comment by MartaNowaczyk** [comment]
Odpowiem w zastępstwie Macieja. Aby uwzględniał stan musisz dodać taki parametr do swojego zapytania. Uzupełnij "parameters". Za parametr stan odpowiada parametr "11323" z odpowiednimi wartościami dla danej kategorii. W przypadku kategorii "252642" dla [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) zwracamy poniższe dane:

```
    "parameters": [
        {
            "id": "11323",
            "name": "Stan",
            "type": "dictionary",
            "required": true,
            "requiredForProduct": false,
            "requiredIf": null,
            "displayedIf": null,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": true,
                "ambiguousValueId": null,
                "dependsOnParameterId": null,
                "describesProduct": false,
                "customValuesEnabled": false
            },
            "dictionary": [
                {
                    "id": "11323_1",
                    "value": "Nowy",
                    "dependsOnValueIds": []
                },
                {
                    "id": "11323_2",
                    "value": "Używany",
                    "dependsOnValueIds": []
                },
                {
                    "id": "11323_238066",
                    "value": "Po zwrocie",
                    "dependsOnValueIds": []
                },
                {
                    "id": "11323_238058",
                    "value": "Powystawowy",
                    "dependsOnValueIds": []
                },
                {
                    "id": "11323_238062",
                    "value": "Uszkodzony",
                    "dependsOnValueIds": []
                }
            ],
            "restrictions": {
                "multipleChoices": false
            }
        },
```
Konkretny przykład znajdziesz w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-sprawdzic-oplaty-nn9DOL5PASX#kalkulator-oplat).

**Comment by maniootek** [comment]
zmieniłem moje zapytanie na takie:
`{
	"offer": {
		"category": {
			"id": "253274"
		},
		"publication": {
			"duration": "PT72H"
		},
		"sellingMode": {
			"format": "BUY_NOW",
			"price": {
				"amount": "8.99",
				"currency": "PLN"
			}
		},
		"parameters": [
			{
				"id": "11323",
				"ValuesIds": [
					"11323_1"
				],
				"values": [],
				"rangeValue": null
			}
		],
		"promotion": {
			"emphasized": true
		}
	}
}`

ale dalej źle pokazuje:
`{
	"commissions": [
		{
			"name": "Prowizja od sprzedaży",
			"type": "commissionFee",
			"fee": {
				"amount": "1.33",
				"currency": "PLN"
			}
		},
		{
			"name": "Prowizja od sprzedaży oferty wyróżnionej",
			"type": "commissionFeatureFee",
			"fee": {
				"amount": "1.00",
				"currency": "PLN"
			}
		}
	],
	"quotes": [
		{
			"name": "Wystawienie przedmiotu",
			"type": "listingFee",
			"fee": {
				"amount": "0.00",
				"currency": "PLN"
			},
			"cycleDuration": "PT240H",
			"classifiedsPackage": null
		},
		{
			"name": "Opłata za wyróżnienie",
			"type": "distinctionFee",
			"fee": {
				"amount": "19.90",
				"currency": "PLN"
			},
			"cycleDuration": "PT240H",
			"classifiedsPackage": null
		}
	]
}`
