### ISSUE TITLE
in stock

### ISSUE THREAD

**Issue by api-test-yexiu** [allegro/allegro-api#8570]
I have an idea. I need to adjust the inventory regularly. The inventory that is not in stock will be cleared to 0, but the inventory cleared link will be automatically removed from the shelves. How can I re-list the link? Will re-listing the link occupy the quota for listing the product?

**Comment by api-test-yexiu** [comment]
![image](https://github.com/allegro/allegro-api/assets/155221200/92281f8f-820b-42b3-8e97-f2dbc56bde7c)
I use the API to adjust the inventory, but I can't go from 0 to 100 and the link is still down

**Comment by MaciejFrackowiak** [comment]
You should also activate the offer again:
```
{
  "publication": {
        "status": "ACTIVE"
    }
}
```
Please, read [our tutorial](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#offer-status-change) too.
