### ISSUE TITLE
createOrderShipmentsUsingPOST (Bad Request 400)

### ISSUE THREAD

**Issue by novastar88** [allegro/allegro-api#8571]
Endpoint:
[setOrderFulfillmentUsingPUT](https://developer.allegro.pl/documentation/#operation/setOrderFulfillmentUsingPUT)

Pełny url zapytania::
`https://api.allegro.pl/order/checkout-forms/e5c539b2-d6d5-11ee-ae05-b9adb9aa3d92/fulfillment`

Header:
`{'accept': 'application/vnd.allegro.public.v1+json', 'Authorization': 'Bearer <token>', 'Content-type': 'application/vnd.allegro.public.v1+json'}`

Body:
`{'status': 'PROCESSING', 'shipmentSummary': {'lineItemsSent': 'NONE'}}`

Status zamówienia w chwili użycia endpointa: `"NEW"`

Środowisko:
Python 12.2
requests

Response:
Kod: 400
Error message: Bad Request

Proszę o pomoc, co robię nie tak, bo już mi się skończyły pomysły.

**Comment by MaciejFrackowiak** [comment]
Nie wiem jak działa Twój skrypt/aplikacja, jednak przekazanie requestu:
```
{
  "status": "SENT",
  "shipmentSummary": {
    "lineItemsSent": "NONE"
  }
}
```
z nagłówkami, które tu podałeś kończy sie statusem 204, czyli status zamówienia został prawidłowo zmieniony.

**Comment by novastar88** [comment]
Rozwiązanie problemu:
Trzeba było użyć `json.dumps()` (nieprawidłowe wysłanie jsona).
