### ISSUE TITLE
REST API. The commandId in the response is empty when calling createShipment

### ISSUE THREAD

**Issue by KodiaqTheBear** [allegro/allegro-api#8573]
- [ ] z zasobem REST API / with a REST API resource
 - [ ] with the production environment

Endpoint:
/shipment-management/shipments/create-commands

Request content:
{"commandId":"","input":{"deliveryMethodId":"1acc38bc-9f08-470d-95b3-11c76ab6e905","sender":{....

Response: HTTP STATUS 200:
 {"commandId":"","input":{"deliveryMethodId":"1acc38bc-9f08-470d-95b3-11c76ab6e905","credentialsId":null,"sender":{....

Hello, please help.
I can't get the commandId in the response to the createShipment call.
The response contains the complete input node according to the sent data, but the commandId is an empty text string.
If I call createShipment again with the same data, the response is an error 400: COMMAND_EXISTS.
But again there is no CommandId value in this response. And that's why I won't move on with it.
Thanks a lot for the advice

**Comment by MartaNowaczyk** [comment]
Please send the trace-id of this query without commandId for verification.

**Comment by Lukasz-Zurek** [comment]
@KodiaqTheBear Thanks a lot! I have forwarded this data to another department. We are verifying this case. Please be patient.

**Comment by KodiaqTheBear** [comment]
@Lukasz-Zurek Thank you too. Please is there any progress? The customer is already impatient. :-(

**Comment by Lukasz-Zurek** [comment]
@KodiaqTheBear I have just received a confirmation that we have already fixed it yesterday afternoon.

**Comment by KodiaqTheBear** [comment]
@Lukasz-Zurek Thank you. Please does this mean that we didnt sent anything wrong?

**Comment by Lukasz-Zurek** [comment]
@KodiaqTheBear Yes, you did not sent anything incorrectly. There was a problem with a commandId, we were overwriting it with an empty value.

We are sorry for this inconvenience.

**Comment by KodiaqTheBear** [comment]
trace-id: da72c6632fec0c22
@Lukasz-Zurek : We tried a new call but it doesn't go through. We sent the commandId as an empty string in the request but response:
 {"errors":[{"code":"VALIDATION_ERROR","message":"musi pasować do wyrażenia ([a-f0-9]{8}(-[a-f0-9]{4}){4}[a-f0-9]{8})" ...

Thanks

**Comment by Lukasz-Zurek** [comment]
@KodiaqTheBear Please try not providing a commandId at all. Then we will generate it automatically.
