### ISSUE TITLE
Podpowiedzi cenowe - endpoint

### ISSUE THREAD

**Issue by meridPL** [allegro/allegro-api#8574]
Dzień dobry,

Czy jest możłiwość pobrania przez api podpowiedzi cenowych jak w przypadku tradycyjnego dodawania oferty ? 
Zdjęcie poniżej
![image](https://github.com/allegro/allegro-api/assets/14768785/7b7a2a81-b446-433e-901f-27bcd9dae467)

**Comment by MaciejFrackowiak** [comment]
Nie, ta funkcjonalność dostępna jest wyłącznie na stronie WWW.
