### ISSUE TITLE
Problem by transfering the description through Allegro API

### ISSUE THREAD

**Issue by EugenBodanov** [allegro/allegro-api#8576]
Hello, I have a problem by transfering description for my offer through Allegro API
Example 1:
Failed to upload product 8435631900054 to Allegro. Response: {'errors': [{'code': 'VALIDATION_ERROR', 'message': 'Invalid tag: "ul", allowed tags: {b, p}', 'details': 'Invalid value: <p>Jeśli chcesz dodać Twojemu domowi nutkę oryginalności, dzięki <b>Leżak rozkładany Marbueno 90 x 108 x 66 cm</b> to osiągniesz.</p><ul><li>Rodzaj: <ul><li>Składanego Krzesła</li><li>Fotel zero gravity</li></ul></li><li>Materiał: <ul><li>Stal</li><li>Textilene</li></ul></li><li>Właściwości: <ul><li>Składany</li><li>Odporne na</li><li>Oddychający</li><li>Elastyczny</li><li>Łatwy i wygodny w użyciu</li></ul></li><li>Zawiera: Poduszka</li><li>Zalecane stosowanie: <ul><li>Plaża</li><li>Zewnętrzny</li><li>Ogród</li><li>Kemping</li></ul></li><li>Maksymalna waga: 110 kg</li><li>Wymiary ok.: 90 x 108 x 66 cm</li></ul>', 'path': 'description.sections[0].items[0].content', 'userMessage': 'Invalid tag: "ul", allowed tags: {b, p}'}]}
Example 2:
Failed to upload product 8435631900047 to Allegro. Response: {'errors': [{'code': 'VALIDATION_ERROR', 'message': 'Invalid HTML subset', 'details': 'Invalid value: <p>Jeśli chcesz dodać Twojemu domowi nutkę oryginalności, dzięki <b>Zasklená veranda Marbueno Składany 190 x 27 x 58 cm</b> to osiągniesz.</p>Właściwości: SkładanyOdporne naOddychającyElastycznyŁatwy i wygodny w użyciuRodzaj: Zasklená verandaMateriał siedziska: textilénMateriał: PoliesterStalTextileneWysokość siedziska ok.: 27 cmZawiera: PoduszkaTryby: 3 TrybyZalecane stosowanie: PlażaZewnętrznyOgródMaksymalna waga: 110 kgWymiary ok.: 190 x 27 x 58 cm', 'path': 'description.sections[0].items[0].content', 'userMessage': 'Invalid HTML subset'}]}
Format in which I make the request:
            "description": {
                "sections": [
                    {
                        "items": [
                            {
                                "type": "TEXT",
                                "content": formated_description
                            }
                        ]
                    } 
                ]
            },
Could you please tell me, where is my error?

PS This link doesn't work https://developer.allegro.pl/tutorials/listing-offers-4RAvLdaqMf8#offer-description

**Comment by MaciejFrackowiak** [comment]
Please, read [our tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#own-images-and-description) about description requirements. You will find which tags are available and in what order you can use them.

**Comment by EugenBodanov** [comment]
Hello, I have read guide, but I can add description to the product just with <b> and <p> tags, when I use others(h1, h2, ul, ol, li) I got an error responce from the server, could you please send me an link to the guide where I can find how to use another tags?

**Comment by MartaNowaczyk** [comment]
Example:

`<h1>Headline 1</h1><h2>Headline 2</h2><p>plain text,&nbsp;<b>bold:</b></p><ul><li>list 1</li><li>list 2</li><li>list 3</li></ul>`

[Link to the guide](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#types-of-content-in-the-description).

**Comment by EugenBodanov** [comment]
But I get such error:
Failed to upload product 8420778077639 to Allegro. Response: {'errors': [{'code': 'VALIDATION_ERROR', 'message': 'Invalid tag: "ul", allowed tags: {b}', 'details': 'Invalid value: <p>Jeśli chcesz dodać Twojemu domowi nutkę oryginalności, dzięki <b>Wypełnienie do poduszki Naturals BLANCO Biały (60 x 60 cm)</b> to osiągniesz.<ul><li>Kolor: Biały</li><li>Z pianką: Puste włókno</li><li>Wymiary ok.: 60 x 60 cm</li><li>Materiał: 100 % poliester</li><li>Instrukcja prania: <ul><li>Nie używać wybielacza</li><li>Do not dry-clean</li><li>Możliwość prania w pralce</li></ul></li><li>Nie nadaje się dla: Żelazko</li></ul></p>', 'path': 'description.sections[0].items[0].content', 'userMessage': 'Invalid tag: "ul", allowed tags: {b}'}]}

**Comment by EugenBodanov** [comment]
Full error:
```json
{
  "Failed to upload product 8420778077639 to Allegro. Response": {
    "errors": [
      {
        "code": "VALIDATION_ERROR",
        "message": "Invalid tag: \"ul\", allowed tags: {b}",
        "details": "Invalid value: <p>Jeśli chcesz dodać Twojemu domowi nutkę oryginalności, dzięki <b>Wypełnienie do poduszki Naturals BLANCO Biały (60 x 60 cm)</b> to osiągniesz.<ul><li>Kolor: Biały</li><li>Z pianką: Puste włókno</li><li>Wymiary ok.: 60 x 60 cm</li><li>Materiał: 100 % poliester</li><li>Instrukcja prania: <ul><li>Nie używać wybielacza</li><li>Do not dry-clean</li><li>Możliwość prania w pralce</li></ul></li><li>Nie nadaje się dla: Żelazko</li></ul></p>",
        "path": "description.sections[0].items[0].content",
        "userMessage": "Invalid tag: \"ul\", allowed tags: {b}"
      }
    ]
  }
}
```

**Comment by MartaNowaczyk** [comment]
Try this:

`<p><b>Wypełnienie do poduszki Naturals BLANCO Biały (60 x 60 cm)</b></p><ul><li>Kolor: Biały,</li><li>Z pianką: <b>Puste włókno</b>,</li><li>Wymiary ok.: 60 x 60 cm,</li><li>Materiał: 100 % poliester.</li></ul><p><b>Instrukcja prania:</b></p><ul><li>Nie używać wybielacza,</li><li>Do not dry-clean,</li><li>Możliwość prania w pralce,</li><li>Nie nadaje się dla: Żelazko</li></ul><p>Jeśli chcesz dodać Twojemu domowi nutkę oryginalności, dzięki temu to osiągniesz.</p>"`

A good way to start is also to create an offer through allegro.co.uk and then download it through the API, so you get the effect you want and get to know the possible formatting of the description.
