### ISSUE TITLE
https://apps.developer.allegro.pl/ - nie pozwala na dodanie nowej aplikacji

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#8578]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Próbuję się zalogować na https://apps.developer.allegro.pl to wywala dziwny błąd 
Nie możemy wyświetlić strony
Numer błędu: 287b241f01517bad

Po wejściu pod link https://apps.developer.allegro.pl/ widzę komunikat
Nie możesz zarejestrować nowej aplikacji
Aktywuj konto oraz włącz dwustopniowe logowanie.

Linki kierują do głównego Allegro.... co ma do cholery Allegro testowego do Allegro normalnego? Z jakiej paki widzę monit o konieczności aktywacji konta na Allegro głównym skoro jestem na testowym?
Co tu się od&^&^#a??

**Comment by Lukasz-Zurek** [comment]
Wskazany przez Ciebie numer błędu odnosi się do nieprawidłowego redirect_uri w procesie autoryzacji. Redirect_uri musi być identyczny jak w ustawieniach danej aplikacji, na stronie https://apps.developer.allegro.pl.

Ponadto z tego co widzę - nie jest to środowisko testowe. Twój przykład odnosi się stricte do środowiska produkcyjnego, gdzie posiadasz maksymalną liczbę zarejestrowanych aplikacji.

Jeśli jednak masz problem z rejestracją aplikacji na środowisku testowym - prześlij proszę szczegółowe informacje np. login konta + ewentualnie doprecyzuj wykonywane po kolei czynności.

**Comment by qshop123** [comment]
Dzień dobry
Rzeczywiście, logowałem się do produkcji. Po skorygowaniu endpointa i próbie logowania do sandboxa, mam jednak błąd

Nie możemy wyświetlić strony
Numer błędu: be090d01a3840cda

Co oznacza błąd "be090d01a3840cda"?

Próbowałem wyszukać w Google ale znajduje mi "DRZWI TYLNE Z DACHEM NISKIM, BEZ OKNA TYLNEGO"

**Comment by Lukasz-Zurek** [comment]
@qshop123 be090d01a3840cda to identyfikator błędu. Tutaj również numer błędu odnosi się do nieprawidłowego redirect_uri w procesie autoryzacji. Redirect_uri musi być identyczny jak w ustawieniach danej aplikacji, na stronie https://apps.developer.allegro.pl.allegrosandbox.pl.
