### ISSUE TITLE
POST /sale/loyalty/promotions bundle

### ISSUE THREAD

**Issue by mjag8** [allegro/allegro-api#858]
Witam,

moje pytanie dotyczy sposobu działania zestawów promocyjnych. Tworząc promocję o takiej strukturze "offerCriteria":

"offerCriteria": [
    {
      "type": "CONTAINS_OFFERS",
      "offers": [
        {
          "id": "1122334455",
          "quantity": 2,
          "promotionEntryPoint": true
        },
        {
          "id": "2233445566",
          "quantity": 1,
          "promotionEntryPoint": true
        }
      ]
    }

Mój zestaw to dwie sztuki `1122334455` i jedna sztuka `2233445566`

Jak to wygląda od strony ilościowej? 
Jeżeli np. mam na sprzedaż w magazynie 10 sztuk `1122334455`, czy sprzedaż w zestawie zmniejszy ilość dostępną do kupienia indywidualnie?
Druga sprawa - czy można ustawić stworzenie powyższego bundla o limitowanej ilości sztuk? Mając 10 sztuk `1122334455` jest możliwość sprzedania powyższego zestawu 5-cio krotnie, nie w nieskończoność. 
Będę wdzięczny za jakieś info w tych kwestiach

**Comment by PawelTaberski** [comment]
Na wstępie chciałbym Tobie polecić nasz poradnik dla zestawów i rabatów, który dziś wdrożyliśmy. Jest on dostępny [tutaj](https://developer.allegro.pl/offer_bundles/#6). 
Co do Twoich pytań to:
Stock w ofercie będzie pomniejszony odpowiednia do tego co określiłeś w zestawie jak klient go zakupi. Jeśli składa się z 2 szt. z jednej oferty i 1 szt. z innej, to tak własnie ubędzie.
Nie ma możliwości ograniczenia ilości zestawów, jednakże jeśli stock jednej z ofert spadnie w tym wypadku np. tej pierwszej której musi być wyższy niż 2 do jednej sztuki, to zestaw nie będzie już widoczny.

**Comment by mjag8** [comment]
I już wszystko wiem, dzięki za pomoc
