### ISSUE TITLE
Błąd przy stworzeniu zestawu z wielu sztuk jednego przedmiotu, który jeszcze nie jest w katalogu

### ISSUE THREAD

**Issue by gitrid** [allegro/allegro-api#8581]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

**Opis / Description**
Zgodnie z [dokumentacją](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-utworzyc-zestaw-ktory-sklada-sie-z-wielu-sztuk-jednego-przedmiotu) można wystawić [1] ofertę z nowym produktem, który nie występuje jeszcze w katalogu; [2] zestaw, który składa się z wielu sztuk jednego przedmiotu. Niestety wygląda na to, że nie da się połączyć [1] i [2], czyli stworzyć zestawu z wielu sztuk jednego przedmiotu, który jeszcze nie jest w katalogu. Zapytanie działa dla oferty bez zestawu, ale przy zmianie parametru productSet.quantity.value pojawia się błąd "ProductDoesNotExist" ('trace-id': '2bfe3f437d778e66'):
```
22:39:06 web.1      | openapi_client.exceptions.ApiException: (422)
22:39:06 web.1      | Reason: Unprocessable Entity
22:39:06 web.1      | HTTP response headers: HTTPHeaderDict({'expires': '0', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'x-xss-protection': '0', 'pragma': 'no-cache', 'trace-id': '2bfe3f437d778e66', 'date': 'Sun, 03 Mar 2024 22:39:06 GMT', 'x-content-type-options': 'nosniff', 'content-type': 'application/json; charset=UTF-8', 'content-length': '139', 'x-frame-options': 'DENY', 'strict-transport-security': 'max-age=15552000'})
22:39:06 web.1      | HTTP response body: b'{"errors":[{"code":"ProductDoesNotExist","message":null,"details":null,"path":"products[0]","userMessage":"This product does not exist."}]}'
```
1) Czy dobrze interpretuję, że nie da się jednocześnie dodać produktu i stworzyć zestawu? Jeżeli nie to będę wdzięczny za wskazanie przyczyny błędu.
2) Czy jest jakiś "sprytniejszy" sposób na obejście problemu niż najpierw dodanie przedmiotu do katalogu przez [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct)?

**Comment by Lukasz-Zurek** [comment]
Bardzo Ci dziękuję za dokładnie opisanie sytuacji.

1. Dobrze to interpretujesz - nie obsługujemy zestawów bez produktów - w tym przypadku musisz wskazać identyfikator lub GTIN produktu z naszego Katalogu.
2. Nie, obecnie nie ma innego sposobu na zrealizowanie tego.
