### ISSUE TITLE
Blad przy tworzeniu przesylki

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#8582]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Mamy problem przy utworzeniu przesylki DHL na Słowację, " Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."

PUT trace_id: e33cf0c7828015d1
GET trace_id: def1ee29ad69cb5b

**Comment by MaciejFrackowiak** [comment]
Weryfkujemy przypadek z dostawcą usługi, wrócę do Ciebie z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Problem w Twoim przypadku generowała kwota ubezpieczenia (jej przelicznik). Poprawka została już wdrożona. De facto przesyłka jest automatycznie ubezpieczona do limitu w danej cenie. Jeżeli chcesz podać ubezpieczenie większe niż kwota pobrania to DHL stosuje przelicznik 4,60 PLN/EUR.
