### ISSUE TITLE
Sandbox autoryzacja, blokada

### ISSUE THREAD

**Issue by Morph21** [allegro/allegro-api#8583]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization

:beetle: **Opis / Description**

Przy próbie autoryzacji dostaje komunikat

Zostałeś zablokowany.
Dlaczego zostałeś zablokowany? Coś w zachowaniu twojej przeglądarki zwróciło naszą uwagę. Powody mogą być różne:
 przeglądasz strony i klikasz dużo szybciej niż przeciętny człowiek
 coś uniemożliwia działanie Javascript na twoim komputerze
 w tej samej sieci (IP XX.XXX.XXX.XXX) operuje robot
Jeśli coś nie działa prawidłowo wyślij nam wiadomość.
ID: 9d226d83-4c2c-3c46-5790-215b02c3e0b6

Po wcześniejszym prawidłowym rozwiązaniu captcha.

Dzieje się tak na środowisku testowym przy redirect uri na http://localhost:8443

**Comment by MaciejFrackowiak** [comment]
Weryfikujemy Twój przypadek, wrócę z odpowiedzią.

**Comment by Morph21** [comment]
@MaciejFrackowiak czy udało się ustalić coś więcej odnośnie tego przypadku?

**Comment by MaciejFrackowiak** [comment]
Już powinno być OK - proszę spróbuj ponownie.

**Comment by Morph21** [comment]
Widzę że działa od wczoraj, bardziej się zastanawiam czy to jakiś problem po Waszej stronie był czy u nas. Jeżeli to problem u nas to chciałbym wiedzieć czy możemy w jakiś sposób uniknąć lub zminimalizować jego występowanie

**Comment by MaciejFrackowiak** [comment]
Było to ograniczenie po naszej stronie.

**Comment by Morph21** [comment]
Ok, dziękuję za rozwiązanie problemu

**Comment by Ozueld** [comment]
Witam,
mam identyczny problem

ID: 13cb2de8-88ce-ccc1-f2d6-c3d433b9b32c
Allegro Sandbox
Adres przekierowań: https://oauth.pstmn.io/v1/browser-callback
