### ISSUE TITLE
Błędny kod kraju dla odbioru w punkcie

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#8585]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

W zasobach zamówienia ponownie dostałem błędny kod kraju dla punktu odbioru:
"pickupPoint": {
			"id": "3352",
			"name": "Michalovce, Staničná 10",
			"description": "Potraviny Antónia - železničná stanica",
			"address": {
				"street": "Staničná 10",
				"zipCode": "071 01",
				"city": "Michalovce",
				"countryCode": "PL"
			}
		},

Powinien być SK

**Comment by AureliuszBrussy** [comment]
Zgłosiłem to do odpowiedniego zespołu - analizujemy to. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@manoos czy możesz podać id tego zamówienia?

**Comment by manoos** [comment]
@AureliuszBrussy  oczywiście:
2a877600-d8cd-11ee-892d-2f4cf1abc3bb

**Comment by AureliuszBrussy** [comment]
Pracujemy nad fixem. Wrócę z informacją po wdrożeniu.

**Comment by manoos** [comment]
Jeszcze jeden ciekawy przypadek:

"pickupPoint": {
			"id": "-353635-K4K2-34",
			"name": "ORLEN Paczka: -353635-K4K2-34",
			"description": null,
			"address": {
				"street": "CYPRIANA GODEBSKIEGO 1",
				"zipCode": "62-800",
				"city": "Kalisz",
				"countryCode": "PL"
			}
		},

numer zamówienia: afbe5350-d7c1-11ee-bdf7-3388c4701409

**Comment by manoos** [comment]
w tym przypadku to nie poprawny jest id i name

**Comment by AureliuszBrussy** [comment]
Tutaj problem wystąpił dla tego punktu po stronie przewoźnika - w takiej formie został nam ten punkt zwrócony w momencie składania zamówienia. Prawidłowa wartość to `KA-353635-K2-34`. W tym momencie do takiego punktu swobodnie nadasz przesyłkę - przewoźnik poprawił wartość.
