### ISSUE TITLE
Brak eventu READY_FOR_PROCESSING

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#8586]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Mamy problem z jednym zamowieniem checkout form id: 7dd74011-d6d9-11ee-b2ac-a9f3396c4e1f
przy sprawdzeniu takiego zamowienia na endpoincie https://api.allegro.pl/order/checkout-forms/7ddf7d71-d6d9-11ee-b2ac-a9f3396c4e1f zamowienie jest zwracane i ma "status": "READY_FOR_PROCESSING"
Natomiast zapytania na https://api.allegro.pl/order/events?limit=500&from=1707982332351029 nie zwracaja takiego zdarzenia, jest tylko zdarzenie FILLED_IN 1709194193502765 i BOUGHT 1709194193532860, brak jest eventu READY_FOR_PROCESSING.

Jest to dosyć istotny błąd bo nawet według poradnika powinniśmy bazować na eventach i dopiero jak event jest READY_FOR_PROCESSING powinniśmy pobierać formularz pozakupowy a tutaj brakuje tego kluczowego eventu.

**Comment by MaciejFrackowiak** [comment]
Czy to jest "7dd74011-d6d9-11ee-b2ac-a9f3396c4e1f" prawidłowe id zamówienia? Pytam, ponieważ nie mogę go namierzyć.

**Comment by d3stozaur** [comment]
faktycznie, to jest poprawny 7ddf7d71-d6d9-11ee-b2ac-a9f3396c4e1f   cos sie zle przekleilo i w pierwszym czlonie 1 za duzo bylo

**Comment by MaciejFrackowiak** [comment]
Dziękuję za podany przykład, weryfikuję z zespołem problem.

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, dla niewielkiej grupy zamówień (w skali całego Allegro) z dnia 29.02.2024 mogła wystąpić sytuacja, że nie pojawił się event READY_FOR_PROCESSING. Obecnie event jest już dostępny, również wszelkie pozostałe ewentualne braki zostały uzupełnione. Przepraszam za niedogodności.

**Comment by d3stozaur** [comment]
Faktycznie teraz zwraca, dzieki za pomoc
