### ISSUE TITLE
Sandbox  - sales suspended

### ISSUE THREAD

**Issue by BarnetMichal** [allegro/allegro-api#8588]
Hello Allegro,

can you please check my sandbox account michal.b@koongo.com. When editing or adding offers I get the message "You do not have the permissions required to list an offer (sales suspended). Pay the arrears in Settlements with Allegro;"

Thank you

**Comment by MaciejFrackowiak** [comment]
You should pay off your Sandbox debts using [Settlements with Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro?sellerId=44190193) tab.

**Comment by BarnetMichal** [comment]
it works, thank you
