### ISSUE TITLE
Brak informacji o produktach w odpowiedzi

### ISSUE THREAD

**Issue by jesiiu** [allegro/allegro-api#8589]
Witam, 
Po pobraniu informacji o zamówieniach z konta Allegro 
"lineItems": [
        {
            "id": "xxx",
            "offer": {
                "id": "xxxx",
                "name": "Plecak....",
                "external": null,
                "productSet": null
            },
            "quantity": 1,
            ...
brakuje informacji o zakupionym produkcie (EAN, SKU, MPN). Próbowałem pobrać zamówienia z 
Get order events
Get order events statistics
Get the user's orders
            Get an order's details
            Dla wszystkich odpowiedzi występuje ta sama sytuacja. Reszta informacji związana z dostawą i szczegółami zamówienia z tego co widziałem jest zawarta w odpowiedzi. 
        
Jak mogę uzyskać informację na temat produktu? Może brakuje jakiegoś uprawnienia aplikacji w ustawieniach?

**Comment by jesiiu** [comment]
No to w takim razie w jaki sposób mogę pobrać informacje na temat produktów z zamówienia? 
Sama nazwa oferty niewiele mi pomaga bo nie mam jak rozpoznać takiego produktu w systemie. 
Aukcje wystawiane są przez Baselinkera, który wymaga przesłania SKU oraz EAN produktu.
Dla każdego produktu z zamówienia musiałbym pobierać informacje osobno przez jakieś zapytanie pobierające informacje o ofercie po ID produktu?

**Comment by MartaNowaczyk** [comment]
Gdy pobierzesz szczegóły oferty otrzymasz informacje o ID produktu (z Katalogu Produktów Allegro), który był tam użyty oraz parametry, gdzie możesz znaleźć np. EAN. Jeśli dobrze Cię zrozumiałam, to może Ci pomóc uzupełnianie pola "external" w ofercie, pojawia się ono też w zamówieniach. Jeśli dodałbyś tam SKU lub inne dane, które potrzebujesz, wtedy łatwo by Ci było połączyć zamówienie z danym produktem.

**Comment by jesiiu** [comment]
Czyli jeżeli dobrze rozumiem to całe data flow powinno wyglądać tak:
Zamówienie -> Wyciągnięcie ID produktu z zamówienia ->sale/product-offers/IDProduktu_z_zamówienia -> Pobranie pozostałych informacji o produkcie

Pozostaje jeszcze jedna kwestia 
product-offers/IDProduktu_z_zamówienia zwraca mi tylko
{ "id": "",
                        "name": "EAN (GTIN)",
                        "values": [
                            "123456789"
                        ],
}
                      
 W odpowiedzi dostaję tylko EAN (GITN), nie widzę nigdzie SKU oraz MPN. Wolałbym opierać się na wsyzstkich parametrach produktu a nie tylko na tym jednym

**Comment by jesiiu** [comment]
> Jeśli dobrze Cię zrozumiałam, to może Ci pomóc uzupełnianie pola "external" w ofercie, pojawia się ono też w zamówieniach. Jeśli dodałbyś tam SKU lub inne dane, które potrzebujesz, wtedy łatwo by Ci było połączyć zamówienie z danym produktem.

Jak mogę to uzupełnić skoro oferty wysyłane są z BASELINKER?

**Comment by MartaNowaczyk** [comment]
SKU produktu nie mamy w danych produktu, chyba, że go właśnie dodasz w oddzielnym polu jako sygnaturę (external.id). Nie zawsze też znajdziesz w danych API MPN. Jeśli chodzi o integrację z Baselinker, to z nimi powinieneś się skontaktować w tej sprawie. Z mojej strony mogę powiedzieć, że takie pole udostępniamy w API Allegro, a jak je wykorzystuje Baselinker i czy można je tam dodać to już kwestia samej integracji.

**Comment by jesiiu** [comment]
Dobrze, w takim razie dziękuje za odpowiedź w tej kwestii. 
Natomiast mam jeszcze jedno pytanie - w pobranych zamówieniach mam pole reconciliation - z czym związane są te dane?

**Comment by MartaNowaczyk** [comment]
Dotyczy programu Allegro Ceny. Więcej informacji znajdziesz w wątku [#4279](https://github.com/allegro/allegro-api/issues/4279).

**Comment by MartaNowaczyk** [comment]
> Wartości produktów / przesyłek w odpowiedzi są wartościami netto czy brutto?

brutto
> W odpowiedzi nie widzę również nigdzie pola ze stawą VAT, rozumiem że stawka ustalana jest na postawie rynku na którym produkt został sprzedany, przykładowo allegro-pl 23%, allegro-cz 21%?

jest to kwota brutto więc nie ma tu pola VAT

**Comment by MartaNowaczyk** [comment]
Zapewne tak, ale kwestie podatkowe to już niestety kwestia poza API, także skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=8e9451b1-1538-4d45-bf7e-d6353555f6ff) lub z informacji [w pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/sprzedaz-miedzynarodowa).

**Comment by jesiiu** [comment]
A jeszcze jednak jedno pytanie będę miał
Na allegro w zamówieniu widnieje informacja o dacie sprzedaży, przykładowo 
data sprzedaży:7 mar 2024, 16:52; rynek: allegro.pl

Z którego pola w response mogę pobrać tą datę bo widzę w kilku miejscach daty ale nigdzie nie ma konkretnie informacji o dacie sprzedaży, poza tym ww odpowiedzi chyba jest data z innej strefy czasowej bo w porównaniu do informacji na allegro godziny w response są przesunięte o godzinę wcześniej

**Comment by MartaNowaczyk** [comment]
W zamówieniach z API datę sprzedaży znajdziesz w "lineItems[0].boughtAt".
W API mamy czas uniwersalny (czas "Zulu"). W moim allegro znajdziesz czas przesunięty o 1 lub 2 godziny w zależności od tego czy w danym momencie obowiązuje czas zimowy czy czas letni.

**Comment by jesiiu** [comment]
> W zamówieniach z API datę sprzedaży znajdziesz w "lineItems[0].boughtAt". W API mamy czas uniwersalny (czas "Zulu"). W moim allegro znajdziesz czas przesunięty o 1 lub 2 godziny w zależności od tego czy w danym momencie obowiązuje czas zimowy czy czas letni.

Czy jest możliwość żeby w momencie w którym klient kupując więcej niż jeden produkt otrzymam dwie różne daty w polach lineItems[0].boughtAt?

**Comment by MartaNowaczyk** [comment]
Data zakupu jest tylko jedna, bo to nadal jest jeden zakup.

**Comment by jesiiu** [comment]
Dobrze dziękuje bardzo za informację 
Przy okazji życzę wszystkiego dobrego z okazji dnia kobiet Pani Marto :)

**Comment by MartaNowaczyk** [comment]
Dziękuję bardzo :)

**Comment by jesiiu** [comment]
Mam jeszcze jedno pytanie tym razem dotyczących generowania etykiet. Czy deliveryMethodId oraz credentialsId wysyłki w opowiedzi z endpointu **Get available delivery services** są zmienne czy mogę sobie je zapisać żeby za każdym razem nie odpytywać API niepotrzebnie?

**Comment by jesiiu** [comment]
Dobrze, dziękuje :)

**Comment by jesiiu** [comment]
Udało mi się utworzyć etykietę i ją pobrać ale zauważyłem pewien problem, nie utworzyła się ona jako etykieta smart a zakup był SMART. Utworzyłem etykietę ręcznie na allegro przez panel i zrobiła się smart. 
Teoretycznie przesyłam wszystkie wymagane informacje (deliveryId, credentialsId, email klienta). 
Na naszym koncie jest podpięta umowa z InPost. Mogę podesłać pełne body zapytania w celu weryfikacji.

**Comment by MartaNowaczyk** [comment]
Podaj commandId lub trace-id.

**Comment by jesiiu** [comment]
1cd2ef41-7ab9-4ce1-8224-49d8e6ea09b8

**Comment by MartaNowaczyk** [comment]
Czy ten commandId jest prawidłowy? Nie widzę go w logach. W takim wypadku podeślij może trace-id lub request i response, możesz skorzystać z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt) z dopiskiem, że dotyczy wątku na GH #8589.

**Comment by jesiiu** [comment]
Taki commandId otrzymalem w odpowiedzi.
W takim razie skontaktuję się przez formularz i podeślę dane które były wysłane

**Comment by MartaNowaczyk** [comment]
Dobrze, czekam na dane.

**Comment by MartaNowaczyk** [comment]
W tym wypadku problemem może być wygenerowanie 2 przesyłek do tego samego zamówienia - wtedy tylko to pierwsze jest SMART.

**Comment by jesiiu** [comment]
Poprzednia etykieta została usunięta i próbowałem utworzyć nową i nie ma SMART. Poprzednia miała smart, ta która została utworzona przez panel allegro. Możliwe, że nie zrobiła się smart przez to że już była poprzednia etykieta? Ale w takim razie wydawało by mi się to dosyć dziwne, że nie można utworzyć drugiej etykiety SMART jeżeli poprzednia była anulowana.

Przesyłam jeszcze raz commandId oraz shipmentID
{"commandId":"512e0be1-4787-4abb-aba4-f7677254d25d","status":"SUCCESS","errors":null,"shipmentId":"c0ccfcbb-fb69-4c24-9f5c-c3f3a8d3128d"}
Proszę o weryfikację

**Comment by jesiiu** [comment]
Tak, zgadza się, w tamtym przypadku były dwie przesyłki jednocześnie, jedna moja przez API oraz drugra przez panel allegro.
W tym przypadku który podesłałem, jedna była wygenerowana wcześniej ALE została usunięta i teraz jest nowa wygenerowana przez API bez smart

**Comment by jesiiu** [comment]
Wygenerowałem dzisiaj etykietę dla kompletnie nowego zamówienia i faktycznie wyszła taka ze SMARTEM. Wydaje mi się jednak to dosyć dziwne, że można utworzyć tylko jedną taką a każda kolejna jest zwykła, nawet jeżeli poprzednia zostanie usunięta. Co w momencie w którym zamówienie trzeba wysłać na 3 przesyłki i kupujący kupi te 3 przesyłki? Wtedy też będzie jedna smart?

**Comment by MartaNowaczyk** [comment]
Z tego co wiem, to anulowana też wchodzi w skład wykorzystanych przesyłek SMART tak jak w Menadżerze InPost to było. Jeżeli do zamówienia będą przypisane 3 przesyłki smart, to będą 3.

**Comment by jesiiu** [comment]
Faktycznie tak jest, wszystko przetestowałem i działa :)
Jeszcze jedno pytanie, czy jest możliwość powiązania jednej aplikacji do kilku kont Allegro. Przykładowo aktualnie na jednym koncie Allegro mam aplikację która pobiera sobie zamówienia i teraz chciałbym tą samą aplikacją pobierać zamówienia z drugiego konta bez konieczności zarządzania drugim kluczem Api

**Comment by MartaNowaczyk** [comment]
Tak właśnie powinieneś działać. Po prostu musisz się zautoryzować na drugim koncie.

**Comment by MartaNowaczyk** [comment]
Aplikację możesz mieć na koncie A, a konta B, C itd. można się zautoryzować jako użytkownik. Czyli np. w procesie autoryzacji [Device Flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow-autoryzacja-uzytkownika) dla każdego użytkownika podajesz ten sam Client ID i Client Secret, ale już od pkt. 3 będziesz miał różne konta, to wtedy dla jednej aplikacji będziesz miał dwóch zautoryzowanych użytkowników.

**Comment by jesiiu** [comment]
Czyli jeżeli dobrze rozumiem, to nie muszę na koncie B allegro rejestrować nowej aplikacji, tylko podłączyć tą z konta A, finalnie i tak dostanę nowy zestaw kluczy dostępu dla konta B którymi będę musiał zarządzać tak jak tymi z konta A (proces odświeżania )

**Comment by MartaNowaczyk** [comment]
Dokładnie tak.

**Comment by jesiiu** [comment]
Okei super, wszystko juz wiem 
Dziękuje za pomoc :)

**Comment by jesiiu** [comment]
No i jednak jest jakiś problem, w momencie w ktróym używam dwóch kont i próbuję utworzyć przesyłkę otrzymuję odpowiedź
NOT_SELLER_ORDER, z tego co widzę to poprawnie dobieram zamówienie pod access_key jednak zawszę zwraca mi to, 
Podsyłam commandId w celu weryfikacji, 15ad9a51-6593-4e14-b93b-9d4bf7b6d7b1.

**Comment by jesiiu** [comment]
Mogę dodać, że na koncie A wszystko działa bez problemu ale na koncie B juz jest problem
