### ISSUE TITLE
Weryfikacja konta

### ISSUE THREAD

**Issue by xkowalczyk** [allegro/allegro-api#8591]
Proszę o zweryfikowania konta sandbox: Client:106923952

**Comment by AureliuszBrussy** [comment]
Aktywowałem Twoje konto.

**Comment by TomasPilar** [comment]
@AureliuszBrussy  can you activate my sandbox account as well - Client: conviu ([info@conviu.com](mailto:info@conviu.com)) (Sandbox). Thank you

**Comment by PrzemyslawLukanowski** [comment]
@TomasPilar I've already replied in #5101 thread.
