### ISSUE TITLE
Modyfikacja produktu - parametr producent (warość Inna/Inny)

### ISSUE THREAD

**Issue by array3** [allegro/allegro-api#8592]
Opis problemu:
Produkt stworzony poprzez serwis Allegro posiada następującą przykładową strukturę parametru producent:

```
**struktura stworzona poprzez serwis**
{
            "id": "248798",
            "name": "Producent",
            "options": {
                "identifiesProduct": true
            },
            "values": [
                "NAZWA_PRODUCENTA"
            ],
            "valuesIds": [
                "248798_942234"
            ],
            "valuesLabels": [
                "Inna"
            ]
 }
```

```
**struktura akceptowana przez API**
nie posiada parametru values (który odpowiada za uszczegółowienie producenta niewystępującego na liście)
{
            "id": "248798",
            "name": "Producent",
            "options": {
                "identifiesProduct": true
            },
            "valuesIds": [
                "248798_942234"
            ],
            "valuesLabels": [
                "Inna"
            ]
 }
```

Przy próbie wysłania struktury w formie takiej jak ta stworzona w serwisie (z parametrem values) jest zgłaszany błąd:
```
CreateProductSuggestionValidationException
Adding custom values has been disabled, please select a value from the dictionary for parameter 248798 (Producent)
```

Moje pytanie, w jaki sposób można dodać parametr dodatkowy dla struktury producenta i wartości "Inna" (kiedy zadany producent nie występuje na liście producentów)? Taka opcja jest w serwisie w polu Producent podaj wartość dla opcji "Inna".

**Comment by array3** [comment]
Dziękuję za szybką odpowiedź, trace-id: 87111ee2db06793d

**Comment by AureliuszBrussy** [comment]
Trafiłeś w tym przypadku na reguły walidacyjne dla produktów. 

W tym momencie są 2 sposoby, aby poradzić z tym poradzić:
- zgłosić potrzebę (przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt)) dodania do danej kategorii w parametrze producent nowej wartości słownikowej. Dzięki czemu po potwierdzeniu jej dodaniu będziesz mógł z niej skorzystać. 
- w przypadku braku konieczności dodania marki - możesz skorzystać z wartości słownikowej "bez marki".
