### ISSUE TITLE
Problem z utworzeniem etykiety

### ISSUE THREAD

**Issue by akonopka11** [allegro/allegro-api#8593]
Witam, mam problem z utworzeniem etykiety. Czy mogę prosić o sprawdzenie przyczyny?

endpoint: parcel-management/parcel-create-commands.

commandId:
f7c75def-c8ab-43cd-8a5e-ffcdad6c836c

odpowiedź:
{"id": "f7c75def-c8ab-43cd-8a5e-ffcdad6c836c", "errors": [{"code": "ERROR", "path": "", "details": null, "message": "Processing error", "userMessage": "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}], "status": "ERROR", "parcelId": null}

**Comment by akonopka11** [comment]
"value":{"amount":11.66,"currency":"PLN"}

**Comment by akonopka11** [comment]
Nie doliczyłam kosztu wysyłki, to pewnie ta przyczyna, zaraz to sprawdzę

**Comment by AureliuszBrussy** [comment]
Wartość ubezpieczenia nie może być niższa, niż wartość pobrania. Zwróć uwagę na walutę, w której zdefiniowana jest wartość pobrania.

**Comment by akonopka11** [comment]
"commandId": "f8dc2d91-d956-4d18-a328-a4770e9db3df"

\"additionalServices\":{\"cashOnDelivery\":{\"value\":{\"amount\":\"11.66\",\"currency\":\"EUR\"}
\",\"value\":{\"amount\":11.66,\"currency\":\"PLN\"}
Czyli jeśli ta kwota 11.66 jest w EUR, to powinnam ją przeliczyć na PLN i to ustawić w value.amount? To jest wartość ubezpieczenia?

**Comment by akonopka11** [comment]
działa, dziękuję za pomoc
