### ISSUE TITLE
Od marca dostaję zwrotkę "Too Many Requests"

### ISSUE THREAD

**Issue by PunktAutoCzesci** [allegro/allegro-api#8594]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

Cześć, 
proszę o weryfikację, dlaczego dostaję zwrotkę o przekroczeniu limitu zapytań. 
Aplikacja działała stabilnie przez ponad rok, Od początku marca mam problem z limitem. 

po wysłaniu ok 4600 zapytań dostaję zwrotkę "Too Many Requests"

przykładowe trace-id: 
**'e8da53b507a866a9'**

Moja aplikacja działa asynchronicznie. Obecnie mam ustawiony limit na jedno pytanie co 10ms lub więcej.

**Comment by PunktAutoCzesci** [comment]
Będę wdzięczny za szybką reakcję. Problem staje się bardzo poważny.

**Comment by PunktAutoCzesci** [comment]
Może przyda się w identyfikacji problemu. 
Radzę sobie jak mogę i obecnie wysyłam zapytania partiami po 100. (z zachowaniem przerw 10-30ms pomiędzy zapytaniami i maksymalnie 30 połączeń na raz)
Po wysłaniu 100 zapytań czekam na zebranie wszystkich odpowiedzi. Jeśli w tych stu odpowiedziach wystąpi odpowiedź z "Too Many Requests" robię przerwę 65 sekund i kontynuuję proces. 

Na ten moment takich serii w których nie występuje błąd "Too Many Requests" jest maksymalnie 5-11 
Czyli 500 - 1100 zapytań. 
Logika by podpowiadała, że jeśli w jakiś sposób przekraczam limit, po przerwie 65 sekund następne błędy zaczną sypać się po 9000 zapytań. Niestety nie. Kolejne są znacznie wcześniej.  
Podsyłam po jednym trace ID z partii (500-1100) zapytań. 

mniej niż 1100 zapytań i zaczęły się błędy "Too Many Requests". Trace ID:
552388a67b0815fe
mniej niż 700 zapytań i zaczęły się błędy "Too Many Requests". Trace ID:
596e53b30236db4e
mniej niż 900 zapytań i zaczęły się błędy "Too Many Requests". Trace ID:
b8c26d8b1c24131f
mniej niż 700 zapytań i zaczęły się błędy "Too Many Requests". Trace ID:
fce54cf50ac27346
mniej niż 700 zapytań i zaczęły się błędy "Too Many Requests". Trace ID:
9070f72755446425
mniej niż 700 zapytań i zaczęły się błędy "Too Many Requests". Trace ID:
aa299950bdd31e5a

**Comment by AureliuszBrussy** [comment]
Dziękuję za dodatkowe dane. Prosiłbym o jeszcze trochę cierpliwości.

**Comment by PunktAutoCzesci** [comment]
Są już jakieś wstępne ustalenia? Nie ukrywam, że aktualizacja ofert na ten
moment jest znacznie utrudniona.

czw., 7 mar 2024, 15:39 użytkownik AureliuszBrussy ***@***.***>
napisał:

**Comment by AureliuszBrussy** [comment]
Jeszcze to wyjaśniamy. Proszę o jeszcze trochę cierpliwości.

**Comment by AureliuszBrussy** [comment]
Namierzyliśmy powód. Problem nie powinien już występować.

**Comment by PunktAutoCzesci** [comment]
Potwierdzam. 
Czy można wiedzieć co było przyczyną? 
Dzięki

**Comment by AureliuszBrussy** [comment]
Niestety, ale nie mogę wchodzić w szczegóły. Związane to było z naszą infrastrukturą.

**Comment by PunktAutoCzesci** [comment]
Ważne, że działa. Dziękuję za pomoc.
