### ISSUE TITLE
ChannelEngine - Allegro API issue with field Brand Other 

### ISSUE THREAD

**Issue by HubschRetail** [allegro/allegro-api#8595]
Hi,

I do have an issue with the mapping stage and understanding why some products are showing up and yet they are not live.

We have also a problem that in the mapping stage with ChannelEngine we don't show up under the BRAND field which makes us use ''other'' and then map it further as ''Other Brand¨, yet Channelengin and you do not support such a solution after all as they flagged it as an error why products don't sync with Allegro.

![Allegro _mapping issue](https://github.com/allegro/allegro-api/assets/162421302/0d5a1f14-f76d-4a79-9451-c9d85cbf4e7b)

Brand: HubschRetailApps

**Comment by AureliuszBrussy** [comment]
Problems and questions about Channel Engine please explain with their support. 

Regarding the issue of adding a brand to the dictionary in a particular category - please, make such a request via the [contact form](https://allegro.pl/pomoc/kontakt). Your request will be forwarded and processed properly this way.

**Comment by HubschRetail** [comment]
Hi,

I will copy their answer lower.

So I assume it must be your team otherwise I am stuck if neither of the involved parties are willing to fix this brand field issue and assist with adding Hubsch there or providing me with the solution.


CN: Unfortunately, using the Brand field in the Option attributes is not being accepted by Allegro.
You can contact Allegro to add your brand on their end first. After that, we will request for an import so the Brand will also become available in Channel Engine._

**Comment by AureliuszBrussy** [comment]
Have you contacted through the contact form to request that a brand be added to a parameter in a category? If so, can you provide the ticket number?

If you did not submit it through the contact form - please do so. The issue will then go to the appropriate team.

**Comment by HubschRetail** [comment]
Hi,

It was a chat room where I explained it all and added the same screenshot and then I got re-directed to Github. 
Frankly, I am close to not even working further on this issue, this is not efficient. I am sorry but this is not a way to go.

Can you please connect me with the integration specialist who will not bounce me from a chat room to a chat room and can help to fix the issue?

**Comment by AureliuszBrussy** [comment]
Please, use the contact form via mail from available options (from [contact form](https://allegro.pl/pomoc/kontakt?subjectId=7e8829e8-fdce-4bfe-82f3-59f4279fd738&kategoria=fd7bf2ce-58e5-4a4f-bc41-b76c99cb8490)). Write that you need to add a new dictionary value to the indicated parameter in a category. I am sure you will then be supported correctly.
