### ISSUE TITLE
Problem z API na baselinker

### ISSUE THREAD

**Issue by freekilleksf2** [allegro/allegro-api#8596]
Dzień dobry mam problem z wystawianiem aukcji z 1 konta na 2 z poziomu baselinkera, administrator bl kazał mi się kontatkować bezpośrednio tutaj więc proszę o pomoc. pokazuje mi sie podany błąd : Zakończono z błędem : Podany identyfikator odpowiedzialnej osoby jest nieprawidłowy. (ConstraintViolationException.ValidResponsiblePerson productSet[0].responsiblePerson)
![113d](https://github.com/allegro/allegro-api/assets/162422758/3017c1ba-2f01-409d-81fc-5cebd3a02d97)

**Comment by AureliuszBrussy** [comment]
Problemem prawdopodobnie jest to, że Baselinker próbuje w obiekcie `productSet[0].responsiblePerson` przekazać identyfikator osoby odpowiedzialnej, który nie jest dostępny dla danego konta (na które przenoszone są oferty). Należy tam wprowadzić identyfikator utworzony na tym drugim koncie. Bez wskazania konkretych requestów przez integratora trudno mi będzie powiedzieć coś więcej. 

To jest niestety coś, co powinien wyjaśnić support Baselinkera.

**Comment by freekilleksf2** [comment]
dziękuję bardzo lecz na obu kontach mam tą samą osobę odpowiedzialną dlatego tego nie rozumiem

**Comment by AureliuszBrussy** [comment]
To, że dane tej osobą są takie same nie oznacza, że jest to dokładnie ten sam wpis. Osoba odpowiedzialna jest definiowana unikatowo na każdym koncie, w związku z tym te wpisy mają inny identyfikator.

**Comment by freekilleksf2** [comment]
czyli co mi Państwo polecacie zrobić ?

**Comment by AureliuszBrussy** [comment]
Proszę wyjaśnić to z Baselinkerem - to ta aplikacja prawdopodobnie przesyła niepoprawny identyfikator.

**Comment by freekilleksf2** [comment]
dziękuję
