### ISSUE TITLE
Zwiększenie limitów API

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#8598]
Gdzie mam się udać w celu zwiększenia limitów do API?

**Comment by MartaNowaczyk** [comment]
Nie opisałeś sytuacji, a być może integracja wymaga pewnych optymalizacji. Najlepiej jednak, wszelkie dane wrażliwe i szczegółowy opis zgłaszać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt), skąd będzie przekazany do naszego zespołu.

**Comment by PunktAutoCzesci** [comment]
Zależy o jaki zasób pytasz. Niektóre są ograniczone odgórnie. Np. dane produktowe. 
Standardowe limity są na prawdę spore. 9000 zapytań na minutę. Ostatnio obserwuję problemy z błędnie naliczanym limitem. 
https://github.com/allegro/allegro-api/issues/8594
W jakim zasobie masz problemy z limitem?

**Comment by TimothyKoval** [comment]
@PunktAutoCzesci Tak, wiem o tym. Wdrażamy nowe rozwiązania i najzwyczajniej w świecie już 9000 nie wystarcza, a będzie więcej :) Sam wiesz jak jest w tej branży, każdy sprzedawca ma 200 czy nawet 400 tysięcy ofert, stany i ceny zmieniają się drastycznie, a na zepsutym rynku jak nie jesteś najtańszy to Cię nie ma

**Comment by PunktAutoCzesci** [comment]
Wszystko jasne. Myślałem, że to dla jednego klienta. 
Korzystając z okazji, też obserwujecie problemy z przedwczesnym ucięciem limitu? 
Mi teraz Allegro na zasobie /sale/product-offers/ zwraca "Too many request" po ok 700 zapytaniach.

**Comment by TimothyKoval** [comment]
@PunktAutoCzesci Ciężko stwierdzić, bo nierealne jest monitorowanie każdego zapytania dla każdego klienta na każdym serwerze. Ale tak "na oko" problem u nas występuje głównie rano, kiedy wchodzą nowe "cenniki" i trzeba zaktualizować milion ofert.

Swoją drogą, kiedyś w odpowiedzi był nagłówek `X-Rate-Limit`, ale widzę, że się znudził.
