### ISSUE TITLE
Walidacja opisu w doVerifyItem | Nieprawidłowy podzbiór HTML

### ISSUE THREAD

**Issue by krychu90** [allegro/allegro-api#86]
Witam,
dlaczego poprawność opisu nie jest sprawdzana w metodzie _doVerifyItem_? Oferta przechodzi przez _doVerifyItem_, ale przez _doNewAuctionExt_ już nie.

Co jest nie tak z opisem tej oferty? Dostaję informację "Nieprawidłowy podzbiór HTML"
```
<p>XXX</p>
<ul>
<li><strong>AA</strong></li>
<li><strong>BB</strong></li>
<li><strong>CC</strong></li>
</ul>
```

Pozdrawiam

**Comment by PawelTaberski** [comment]
Metoda o której wspomniałeś nie sprawdza poprawności fid 341. Opis jest weryfikowany w metodzie doNewAuctionExt. Podeślij pełny fid 341 jaki przesyłasz sprawdzimy w czym jest problem. Na pierwszy rzut oka korzystasz ze złego znacznika do pogrubienia. Dopuszczalny jest <b>, więcej na temat znaczników jakie możesz używać znajdziesz [tutaj](https://developer.allegro.pl/new_desc/). Ponadto opis najlepiej przesyłać w jednej linii, nie można rozdzielać kolejnych sekcji, trzeba zachować JSON-ową strukturę.

**Comment by krychu90** [comment]
> Metoda o której wspomniałeś nie sprawdza poprawności fid 341. Opis jest weryfikowany w metodzie doNewAuctionExt.

To ja wiem, pytałem dlaczego nie jest sprawdzana poprawność pola z opisem? Jeżeli metoda ma sprawdzać poprawność wprowadzonych pól to powinna też sprawdzić poprawność opisu.

**Comment by krychu90** [comment]
> Metoda doVerifyItem nie jest już rozwijana od pewnego czasu i nie będziemy jej aktualizować

I to zdanie pięknie opisuje w jakim stanie jest allegro API. Brawo!

**Comment by yncki** [comment]
Ale chwila, doVerifyItem o której piszecie weryfikuje przeciez poprawnosc wystawienia oferty przez localId i to dziala. Chyba pytanie dotyczylo doCheckNewAuctionExt ? Bo ono faktycznie jest w aktualnym stanie bez wiekszego sensu.

A jak wygląda sprawa z doCheckItemDescription ? Dobrze by bylo jakby je oznaczyc w dokumentacji ze sa @deprecated zamiast wprowadzac ludzi w blad i marnujac przy tym czas. 

Kolejna sprawa to nadal niejasne informacje o wystawianiu oferty na 341. 

Np. 
<p><b>test</b></p> przejdzie, ale juz 
<p><b></b></p> nie przejdzie, 

<p><b> > 40kg </b></p> nie przejdzie, ale
<p><b> &lt; 40kg </b></p> przejdzie 

kosmos. 

Nawet API Prestashopa ma lepszą dokumentację :)

**Comment by krychu90** [comment]
> Chyba pytanie dotyczylo doCheckNewAuctionExt ? 

Dokładnie tak

**Comment by PawelTaberski** [comment]
Przepraszam też myślałem o doCheckNewAuctionExt, a nie doVerifyItem. I tak jak jest w dokumentacji metoda obecnie pozwala na: "...na sprawdzenie ogólnych oraz szczegółowych kosztów związanych z wystawieniem oferty przed jej faktycznym wystawieniem." nie do sprawdzenia opisu.

**Comment by kfijalko** [comment]
Dziś wystawiałem z:
<p>XXX</p>
<ul>
<li><b>parametr</b>wartosc</li>
<li><b>parametr</b>wartosc</li>
<li><b>parametr</b>wartosc</li>
</ul>
dostałem błąd - nieprawidłowy podzbiór html

**Comment by PawelTaberski** [comment]
Musiałbym zobaczyć całego fid-a jak przesyłasz, sekcja typu:
`"type": "TEXT",
 			"content": "<p>Test<b>Test</b></p><ul><li><b>parametr</b>wartosc</li><li><b>parametr</b>wartosc</li><li><b>parametr</b>wartosc</li></ul>"
 		}]`
Wystawia się prawidłowo.

**Comment by kfijalko** [comment]
Zgadza się, działa "losowo". Mam kilka takich sekcji i na około 20 wywołań 2 razy otrzymałem błąd z nieprawidłowym podzbiorem html. Teraz stosuję <h2></h2><ul><li></li></ul> - jeszcze nie otrzymałem błędu.

**Comment by yncki** [comment]
@PawelTaberski Gdzie mozna wyslac XMLa z blednym requestem na 341 ?

**Comment by kfijalko** [comment]
@yncki możesz przeciągną plik do okienka z treścią lub kliknąc link w stopce okienka "selecting then".

**Comment by PawelTaberski** [comment]
@yncki Jeśli chcesz podesłać pełnego requesta (ze swoimi danymi) możesz to zrobić przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt#subjectId=9fe60f94-a07b-47e5-84b4-b15beafe2422), a następnie wklej tutaj numer ticketa.

**Comment by yncki** [comment]
@PawelTaberski Ticket#1246523836

**Comment by PawelTaberski** [comment]
Ta metoda nie sprawdza poprawności nowego opisu, aby sprawdzić poprawność nowego opisu, ale nie wystawiać oferty możesz od teraz skorzystać z nowych zasobów do REST API, którymi utworzysz ofertę. Możesz tam też utworzyć draft i uzupełniać go metodą [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#!/offer/updateOfferUsingPUT). Oferta jest za każdym razem walidowana pod kontem poprawności. Nie pojawi się w serwisie dopóki jej nie opublikujesz. Poradnik jak korzystać z nowych zasobów znajdziesz tutaj:

**Comment by p3le** [comment]
Witam,

mam ten sam problem. Ticket#1249465386

**Comment by PawelTaberski** [comment]
@p3le Jaki dokładnie masz problem, bo poruszaliśmy tutaj kilka spraw? Przy pomocy jakiej metody wystawiasz ofertę? Przez REST czy WebAPI?

**Comment by p3le** [comment]
@PawelTaberski Problem jest taki jak nazwa tematu, "Nieprawidłowy podzbiór HTML" i opis w której konkretnie sekcji. Zawartość sekcji przesłałem w tickecie, a aukcję wystawiam przez WebAPI metodą doNewAuctionExt.

**Comment by PawelTaberski** [comment]
Brak sekcji i zamiast data powinno być content. Poniżej poprawny opis na podstawie Twojego:
` {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p><b>Model SC 430</b></p>........."
                    }
                ]
            }
        ]
    },`
Więcej na temat jak poprawnie skonstruować nowy opis znajdziesz [tutaj](https://developer.allegro.pl/new_desc/#03).

**Comment by p3le** [comment]
@PawelTaberski Sekcje są, w załączniku wysłałem tylko tą, do której otrzymałem błąd w odpowiedzi z API. Dziwne jednak jest to, że po usunięciu tej sekcji aukcja się wystawia, mimo tego że pozostałe sekcje skonstruowane są identycznie.

**Comment by PawelTaberski** [comment]
Czy problem nadal występuje? testowałem Twoje zapytanie i oferta wystawiła się bez problemu, problem był z błędną nazwą contentu.

**Comment by p3le** [comment]
Opis jest zgodny z tym co w dokumentacji, a mimo to dalej nie przechodzi. Przesyłam pełny opis, który jest wysyłany do api: https://pastebin.com/BMVnVZdu
