### ISSUE TITLE
Aby aktywować sprzedaż zweryfikuj konto (sandbox)

### ISSUE THREAD

**Issue by many-to-one** [allegro/allegro-api#8600]
Chcę wystawić swoją pierwszą ofertę na firmowym koncie allegro.pl.allegrosandbox.pl. Po tym jak wybieram kategorie, pojawia się komunikat, że nie można wystawić oferty bez weryfikacji konta.
Login: testosteron
W zakładce "KONTO" inny komunikat: "Aktywuj sprzedaż, aby móc wystawiać oferty i sprzedawać na Allegro" po wejściu w który muszę dodać metody płatności i wybrać cennik dostaw, ale nie mogę tego zrobić, ponieważ wyświetla się kolejny komunikat: "Czekamy na potwierdzenie rachunku bankowego
Odblokujemy możliwość ustawienia dostawy, gdy tylko otrzymamy potwierdzenie rachunku bankowego Twojej firmy."

**Comment by many-to-one** [comment]
Chcę wystawić swoją pierwszą ofertę na firmowym koncie allegro.pl.allegrosandbox.pl. Po tym jak wybieram kategorie, pojawia się komunikat, że nie można wystawić oferty bez weryfikacji konta.

**Comment by many-to-one** [comment]
Login: testosteron

**Comment by AureliuszBrussy** [comment]
Zarejestruj proszę całkiem [nowe konto firma](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F). Gdy potwierdzisz rejestrację, przejdź proszę przez. tzw. krokowiec, gdzie uzupełnisz fałszywe dane oraz wykonasz symulację przelewu weryfikacyjnego. Gdy to zrobisz - daj mi znać, aktywuję Twoje konto.

**Comment by many-to-one** [comment]
Dziękuję za szybką odpowiedz. Przy rejestracji podawaję fałszywy NIP i system nie przepuszcza("Nieprawidłowy format NIP-u"), dla ciekawości jak wpisuję realny to faktycznie zaciąga realne dane do podglądu. Pytanie: czy ja musze podawać faktyczny NIP czy robię coś nie tak, że system nie wczytuje fałszywy?

**Comment by AureliuszBrussy** [comment]
Skorzystaj z jakiegoś generatora NIPu (np. dostępnego online), aby wygenerować go w odpowiednim formacie (z prawidłową cyfrą kontrolną).

**Comment by many-to-one** [comment]
Próbowałem dokonać przelewu po uzupełnienu wszyskich danych (IBAN i SWIFT) i zostałem (niby) przekerowany do strony "mojego" banku i dostałem komunikat na tej stronie "Wystąpił błąd". Czy tak ma być? Przecież dane były fałszywe, czy znowu coś zrobiłem nie tak?

**Comment by AureliuszBrussy** [comment]
Podaj proszę login konta.

**Comment by many-to-one** [comment]
retset

**Comment by AureliuszBrussy** [comment]
Aktywowałem Twoje konto.

**Comment by many-to-one** [comment]
Super, bardzo dziękuję.
