### ISSUE TITLE
editProductOffers (403 AccessDenied)

### ISSUE THREAD

**Issue by novastar88** [allegro/allegro-api#8601]
Endpoint:
[editProductOffers](https://developer.allegro.pl/documentation/#operation/editProductOffers)

Pełny url zapytania:
`https://api.allegro.pl/sale/product-offers/15263745049`

Header:
`{'accept': 'application/vnd.allegro.public.v1+json', 'Authorization': 'Bearer <token>', 'Content-type': 'application/vnd.allegro.public.v1+json'}`

Body:
`{'stock': {'available': 65, 'unit': 'UNIT'}}`

Środowisko:
Python 12.2
requests 2.31.0

Response:
Kod: 403
Error message: AccessDenied

Proszę o pomoc.

**Comment by MaciejFrackowiak** [comment]
Twój obecny token nie posiada scope "allegro:api:sale:offers:write" niezbędnego do edycji ofert. [Edytuj](https://apps.developer.allegro.pl/) uprawnienia swojej aplikacji, a następnie ponownie zautoryzuj aplikację.

**Comment by novastar88** [comment]
Czy mówimy tu o kliencie o id: 5d9*****46ec*****9e107*****df3e0?
Takie uprawnienie jest ustawione w panelu.

**Comment by MaciejFrackowiak** [comment]
Zmieniłeś zakres uprawnień, ale wciąż działasz na tokenie, który nie uwzględnia tejże zmiany. Musisz ponownie zautoryzować aplikację, aby zaakceptować nowy zakres uprawnień aplikacji.

**Comment by novastar88** [comment]
Dziękuję za pomoc. A jeszcze takie pytanie co do tego endpointa, jak działa `"UNIT" "PAIR" "SET"`?
Wszystko mamy na sztuki, więc ustawiam na unit. A co by się stało jakbym ustawił to na pair podczas ustawiania nowej ilości mając sztuki? Trochę nie rozumiem tego ustawienia bo widzę go pierwszy raz. Zazwyczaj była poprostu liczba czegośtam i ją się ustawiało.

**Comment by MaciejFrackowiak** [comment]
Jest to odzwierciedlenie określenia tego co oferujesz w ofercie - czy jest to sztuka, komplet czy para. Podobne ustawienie dostępne jest na stronie WWW:
<img width="701" alt="Zrzut ekranu 2024-03-7 o 09 45 32" src="https://github.com/allegro/allegro-api/assets/53566763/0f3319b6-2bae-4dee-844c-d0cd7052fec0">

**Comment by novastar88** [comment]
Dziękuję za pomoc.
