### ISSUE TITLE
Brakujące informacje w response sample dotyczące pobrania cenników hurtowych

### ISSUE THREAD

**Issue by Morph21** [allegro/allegro-api#8602]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

Podobny problem do tego który zgłaszałem tutaj #7610 
w endpoincie https://api.{environment}/sale/loyalty/promotions
brakuje w response sample odpowiednich danych, w dokumentacji mamy informację taką:

```
{
  "promotions": [
    {
      "benefits": [
        {
          "specification": {
            "type": "string"
          }
        }
      ],
      "createdAt": "2019-05-01T10:12:32.321Z",
      "id": "7c9a76d3-9fd0-4d13-a4ce-5d49bec12c79",
      "offerCriteria": [
        {
          "offers": [
            {
              "id": "1233432",
              "quantity": 5,
              "promotionEntryPoint": false
            }
          ],
          "type": "CONTAINS_OFFERS"
        }
      ],
      "status": "ACTIVE"
    }
  ],
  "totalCount": 0
}
```

a w zwrotce endpoint zwraca dodatkowe informacje:

```
{
  "promotions": [
    {
      "id": "c8b95163-f537-48cc-b2b2-c2177a2e4b96",
      "createdAt": "2024-03-06T10:14:20.138Z",
      "benefits": [
        {
          "specification": {
            "name": "dużo",
            "thresholds": [
              {
                "quantity": {
                  "lowerBound": 5
                },
                "discount": {
                  "percentage": "10"
                }
              },
              {
                "quantity": {
                  "lowerBound": 10
                },
                "discount": {
                  "percentage": "15"
                }
              }
            ],
            "type": "WHOLESALE_PRICE_LIST"
          }
        }
      ],
      "offerCriteria": [
        {
          "type": "OFFERS_ASSIGNED_EXTERNALLY"
        }
      ],
      "status": "ACTIVE"
    }
  ],
  "totalCount": 3
}
```

Kolejną rzeczą której tam brakuje to wszystkie informacje odnośnie tego co możemy podać w parametrze wejściowym promotionType są tam podane 3 wartości tylko a z tego co widzę możemy również podać "WHOLESALE_PRICE_LIST"

**Comment by MaciejFrackowiak** [comment]
Jeżeli otworzysz zakładkę z odpowiedziami (200) to masz możliwość wybrania response schema w zależności od typu promocji - wówczas otrzymasz układ odpowiedzi dla wybranego rodzaju promocji. Sam podgląd - ramka po prawej stronie -zawiera wyłącznie ogólny układ, bez uwzględnienia wybranego typu promocji.

**Comment by Morph21** [comment]
Ja to rozumiem że to jest w zakładce z odpowiedzią jednakże z tamtego miejsca nie mam możliwości skopiowania json-a który mogę sobie automatycznie przetworzyć na klasy w jakimkolwiek języku programowania chce.

I parsowanie takiego stringa nie odbywa się na zasadzie sprawdzania czy ta wartość jest jakaś konkretna i dopiero później się nie przerabia na klasy tylko konwertujemy całą zawartość body do obiektów odpowiadających jednemu endpointowi.

Reasumując powinien być tam pełen response jaki może przyjść

**Comment by MaciejFrackowiak** [comment]
Rozumiem Twoje oczekiwania, jednak obecna wersja dokumentacji nie pozwala na wprowadzenie tego typu rozwiązania.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przedstawienie Twoich spostrzeżeń, jednak w najbliższym czasie nie mamy zaplanowanych żadnych prac w tym zakresie.
