### ISSUE TITLE
Dodawanie ogłoszeń motoryzacyjnych przez API

### ISSUE THREAD

**Issue by kamilb88** [allegro/allegro-api#8604]
Czy można używając Państwa API wystawić ogłoszenie motoryzacyjne?

**Comment by MaciejFrackowiak** [comment]
Oczywiście tak - zajrzyj do [naszego poradnika](https://developer.allegro.pl/tutorials/jak-wystawic-i-zarzadzac-ogloszeniem-K6r3Z47dKcy), gdzie znajdziesz kluczowe informacje.
