### ISSUE TITLE
Problem z zasobami /sale/delivery-methods oraz /sale/shipping-rates

### ISSUE THREAD

**Issue by makerlabs** [allegro/allegro-api#8605]
Witam,
Dlaczego metoda /sale/delivery-methods (zwraca całkowicie inna listę metod niż ta która jest dostępna po stronie serwisu sandbox Allegro. Pomimo, że wybiera że ma zwrócić wszystkie metody dla allegro-pl zwraca mi metody które umożliwiają wysyłkę do innych krajów przez co jak klient wybiera wysyłkę do Słowacji i tworzy nowy cennik za pomocą metody /sale/shipping-rates otrzymuje komunikat:
Missing delivery method [07515f0a-9d73-4c68-8a41-feff819cdc9f] required in bundle \"SlovakiaBundle\, który raz w ogóle nic nie mówi bo odnosi się do jakiś abstrakcyjnych nazw w ogóle nie występujących ani w dokumentacji ani w samym API. I odnosi się do uuid dostawy której w ogóle nie ma na liście dla serwisu allegro-pl.

Już pomijam że jak się wchodzi na dodawanie cenników z poziomu serwisu Allegro można wybrać dodatkowo z jakiego do jakiego kraju następuje wysyłka.

Pozdrawiam
Marcin Butlak

**Comment by MartaNowaczyk** [comment]
Podaj proszę przykładowy trace-id w którym zwracamy nieodpowiednie dane oraz dla przypadku w którym dostajecie wspomniany błąd.
