### ISSUE TITLE
Pytanie o oferty wielowariantowe

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#8607]
Dzień dobry mam pytanie o oferty wielowariantowe. 
Czy posiadając ofertę wielowariantową złożonej z aukcji [a, b, c] mogę przez wasze API sprawić aby usunąć jedną konkretną aukcję z seta? Czyli np usuwam aukcje "c" i wtedy oferta wariantowa składa się tylko z [a, b]

W waszym poradniku https://developer.allegro.pl/tutorials/jak-utworzyc-oferte-wielowariantowa-oA6ZYBg5XFo#usun-oferte-wielowariantowa wspominacie tylko o usuwaniu kompletnie setu wariantów. 

za to w https://developer.allegro.pl/documentation/#operation/updateVariantSet
wymagacie parametrów i nazwy VariantSetu

**Comment by MartaNowaczyk** [comment]
Ofertę wielowariantową możesz edytować przez [PUT /sale/offer-variants/{setId}](https://developer.allegro.pl/documentation/#operation/updateVariantSet) jeśli nie łączymy ich automatycznie. Swój VariantSet możesz znaleść za pomocą [GET /sale/offer-variants](https://developer.allegro.pl/documentation/#operation/getVariantSets)?query={query}, wtedy dane, które tam dostaniesz możesz użyć do edycji.

Tak jak pisałam, miej tylko na uwadze, że w niektórych kategoriach (wymienionych w pkt 1.12.2 [Regulaminu Serwisu](https://allegro.pl/regulamin/pl/zalacznik-2)), oferty wielowariantowe łączymy automatycznie na podstawie parametrów, w związku z czym usunięcie jednej z ofert, która wcześniej została do takiej wielowariantowej oferty automatycznie dodana, nie będzie możliwe. [Kategorie zarządzane automatycznie](https://allegro.pl/dla-sprzedajacych/wprowadzamy-automatyczne-laczenie-ofert-w-oferty-wielowariantowe-EYWkzVmdOsD).
