### ISSUE TITLE
Aktywacja konta na sandbox

### ISSUE THREAD

**Issue by saborpl** [allegro/allegro-api#8608]
Witam, nie mogę dokończyć procesu rejestracji. Można prosić a aktywację konta? 
login: dev76bitpl
![image](https://github.com/allegro/allegro-api/assets/7511140/03032802-e987-4fec-adfb-3830924d0cca)

**Comment by AureliuszBrussy** [comment]
Przejdź proszę przez cały tzw. krokowiec od początku - wszystkie kroki, które widzisz z poziomu zakładki "[Moje konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto)". W szczególności wykonaj symulację przelewu weryfikacyjnego w kroku 2 oraz uzupełnił fałszywe dane do weryfikacji w kroku nr 3. Gdy to zrobisz - daj znać, dokończę aktywację konta.

**Comment by saborpl** [comment]
zrobiłem przelew, dostałem dwa maile w celu potweirdzenia konta. Po kliknięciu przenosi mnie na produkcyjne allegro.... poniżej link z przycisku oraz załącznik z mailami

https://t.allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat/potwierdz-nowe-konto?utm_source=notification&utm_medium=payoutAccountChanged&utm_campaign=de0b263b-3cb1-4e5a-b0c4-d14aa9e1027d&tr_n=confirm-new-payout-account&tr_id=106885607-v30&tr_d=allegro.pl&tr_c=payout-settings&tr_s=BTJX8kQ2

![Screenshot 2024-03-08 at 08 30 36](https://github.com/allegro/allegro-api/assets/7511140/ccbc02dc-6183-4ead-8be0-fbf401e02c69)

**Comment by AureliuszBrussy** [comment]
Aktywowałem Twoje konto.

**Comment by MarcinBazylak** [comment]
> zrobiłem przelew, dostałem dwa maile w celu potweirdzenia konta. Po kliknięciu przenosi mnie na produkcyjne allegro.... poniżej link z przycisku oraz załącznik z mailami
> 
> https://t.allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat/potwierdz-nowe-konto?utm_source=notification&utm_medium=payoutAccountChanged&utm_campaign=de0b263b-3cb1-4e5a-b0c4-d14aa9e1027d&tr_n=confirm-new-payout-account&tr_id=106885607-v30&tr_d=allegro.pl&tr_c=payout-settings&tr_s=BTJX8kQ2
> 
> ![Screenshot 2024-03-08 at 08 30 36](https://private-user-images.githubusercontent.com/7511140/311153287-ccbc02dc-6183-4ead-8be0-fbf401e02c69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTE1MjEsIm5iZiI6MTcwOTg5MTIyMSwicGF0aCI6Ii83NTExMTQwLzMxMTE1MzI4Ny1jY2JjMDJkYy02MTgzLTRlYWQtOGJlMC1mYmY0MDFlMDJjNjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMDk0NzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTM4N2I0ZTMxMmI4MjI2ZmQzNjI2M2I1NmVjZmM1M2UzNzNjZDk4OGNlMzU5MzVlNzZiZTJjMGJjMTY4ZDc1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LJiOAvNyNNy7zrTtWTE3m6NBhUGihjeTh8qNe5-bBgs)

Mam ten sam problem. Login outlet_first_p

Mogę prosić o pomoc?

**Comment by saborpl** [comment]
Dzięki, działa.

**Comment by AureliuszBrussy** [comment]
@MarcinBazylak aktywowałem Twoje konto.

**Comment by MarcinBazylak** [comment]
> @MarcinBazylak aktywowałem Twoje konto.

Działa. Dzięki.

**Comment by dominikwoj27** [comment]
hej, proszę również o aktywację konta
login 1022pressure

**Comment by AureliuszBrussy** [comment]
@dominikwoj27 aktywowałem Twoje konto.
