### ISSUE TITLE
Category 259871 was not found

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#8609]
Próbuję pobrać wartość prowizji dla kategorii 259871.

POST https://api.allegro.pl/pricing/offer-fee-preview
trace-id: 84cb0802ed4105d 

W odpowiedzi dostaję: 
 {"errors":[{"code":"ERROR","message":"Category not found","details":"Category 259871 was not found","path":null,"userMessage":"Category 259871 was not found"}]}

Kategoria na pewno istnieje, w przeglądarce wyświetla się bez problemu:
https://allegro.pl/kategoria/koraliki-porcelanowe-i-szklane-szklane-perelki-kuleczki-259871

**Comment by AureliuszBrussy** [comment]
Powodem takiego stanu rzeczy jest to, że wskazana kategoria (id=259871) jest kategorią nawigacyjną, którą widzą tylko kupujący, a nie kategorią asortymentową, w której sprzedawcy mogą wystawiać swoje przedmiot (id=259852). Kategoria została w przeszłości scalona z inną - oznacza to, że jeśli kategoria A została scalona kategorią B, to oferty możesz wystawić tylko w kategorii B, ale kupujący zobaczą ją zarówno w kategorii A, jak i B. Więcej na temat tego przeczytasz na [naszej stronie](https://developer.allegro.pl/news/na-poczatku-grudnia-zaczniemy-scalac-kategorie-po-stronie-sprzedajacego-k1nyd205YHo), jak i na [stronie dla sprzedających](https://allegro.pl/dla-sprzedajacych/laczymy-kategorie-z-tym-samym-asortymentem-AggmRPKrnuY).
