### ISSUE TITLE
Brak informacji o długości pól?

### ISSUE THREAD

**Issue by Arkowsky** [allegro/allegro-api#861]
Gdzie można znaleźć informacje na temat tego jaką długość może mieć pole name w ofercie?
Mogłoby to być w definicji swaggera:

![screenshot 2018-11-05 at 14 26 06](https://user-images.githubusercontent.com/19975089/48000749-c4a4fb00-e106-11e8-9b61-765137e5c4a9.png)

Chodzi o to, że przy wysyłaniu dostaje ERR_ITEM_NAME_TOO_LONG. Gdyby to było w definicji swaggera, to codegen do swaggera by wygenerował mi wstępną walidację a tak to muszę wysyłać requesty i kolejno odkrywać długość pól?

**Comment by PawelTaberski** [comment]
@Arkowsky Dodaliśmy informacje o które prosiłeś do dokumentacji w polu maxLength

**Comment by Arkowsky** [comment]
Dziękuję, super informacja :)
