### ISSUE TITLE
Tax settings not found

### ISSUE THREAD

**Issue by yu-www** [allegro/allegro-api#8610]
Hi,
I got a question when I call the "/sale/product-offers" API

this is the request:

`{"afterSalesServices":{"impliedWarranty":{"id":"f00c8fea-0afb-4223-bf36-8c23280492e0"},"returnPolicy":{"id":"1f27b00b-3863-46a9-b462-6728bf7a21fc"},"warranty":{}},"delivery":{"handlingTime":"PT24H","shippingRates":{"id":"fab5252f-fb4d-4d06-8621-d108de88450a"}},"description":{"sections":[{"items":[{"content":"<p>Gumowa podeszwa&nbsp;</p>\n\n<p>JAKOŚĆ NAJWYŻSZEJ JAKOŚCI: Nasze obuwie jest szyte ręcznie i wykonane z najwyższej jakości skr przy użyciu najnowocześniejszych maszyn i najnowocześniejszych technik.Wszystkie nasze produkty są wytwarzane ręcznie przez wykwalifikowanych rzemieślnikw, ktrzy mają duże doświadczenie w precyzyjnych technikach wytwarzania niezbędnych do wytworzenia produktu Oferujemy.&nbsp;</p>\n\n<p>NAJWYŻSZY KOMFORT: nasi specjaliści od zaopatrzenia przeszukują świat, aby zastosować najbardziej zaawansowaną technologię zapewniającą komfort na rynku.W pełni wyściełana wkładka, żelowa wkładka na piętę i tępe wsparcie łuku uzupełniają ten wspaniały mokasyn, aby zapewnić niezrwnany komfort i dopasowanie. Amortyzowana wkładka i oddychająca skrzana cholewka zapewni Ci wyjątkowe wsparcie dla Twoich wynikw.</p>\n\n<p>&nbsp;SOLIDNE WSPARCIE: Antypoślizgowa, elastyczna gumowa podeszwa kierowcy i amortyzacja zapewniają doskonały komfort, solidne wsparcie i przyczepność do chodzenia.Jest miękki w dotyku, ktry dopasowuje się do stopy podczas noszenia.Wygodny podczas chodzenia lub stania przez cały dzień.&nbsp;</p>\n\n<p>DOSKONAŁE NA KAŻDĄ OKAZJĘ: codzienne mokasyny męskie mają swobodny design i świetnie nadają się na wszystkie okazje, takie jak spacery, jazda samochodem, na zewnątrz, wewnątrz, do biura i na zakupy.&nbsp;</p>\n\n<p>Działa zgodnie z rozmiarem.&nbsp;</p>\n\n<p>EU38 = długość stopy24cm&nbsp;</p>\n\n<p>EU39 = długość stopy 24,5 cm&nbsp;</p>\n\n<p>EU40 = długość stopy 25cm&nbsp;</p>\n\n<p>EU41 = długość stopy 25,5 cm&nbsp;</p>\n\n<p>EU42 = długość stopy 26cm&nbsp;</p>\n\n<p>EU43 = długość stopy 26,5 cm&nbsp;</p>\n\n<p>EU44 = długość stopy27cm&nbsp;</p>\n\n<p>EU45 = długość stopy 27,5 cm&nbsp;</p>\n\n<p>EU46 = długość stopy 28cm&nbsp;</p>\n\n<p>EU47 = długość stopy 28,5 cm&nbsp;</p>\n\n<p>EU48 = długość stopy 29cm</p>\n","type":"TEXT"},{"type":"IMAGE","url":"https://a.allegroimg.com/original/118566/d8e1153d41569e4d162536faefdc"}]}]},"external":{"id":"1104-1-39"},"images":["https://a.allegroimg.com/original/114984/c5c2b7804bcea7378fcc130bf296"],"location":{"city":"quanzhou","countryCode":"CN","postCode":"362000"},"name":"Męskie mokasyny skórzane wsuwane buty do jazdy","parameters":[{"id":"11323","valuesIds":["11323_1"]},{"id":"219629","valuesIds":["219629_286869"]},{"id":"229205","valuesIds":["229205_340245"]}],"payments":{"invoice":"NO_INVOICE"},"productSet":[{"product":{"category":{"id":"147418"},"images":["https://a.allegroimg.com/original/1146ac/b5b9337245028ce0b8cd4721bea8","https://a.allegroimg.com/original/118566/d8e1153d41569e4d162536faefdc","https://a.allegroimg.com/original/114984/c5c2b7804bcea7378fcc130bf296","https://a.allegroimg.com/original/11cb9b/d9776fbf4f77b2173f1f49855184","https://a.allegroimg.com/original/11a325/a0d450f043e99d1a005fef3a839a","https://a.allegroimg.com/original/117a5e/1803a9674a7694ed73467a78e350","https://a.allegroimg.com/original/1140ac/70e166454eceae3018e0c03c8901","https://a.allegroimg.com/original/114fe4/af89f28849ad9e99333c92f7e00e","https://a.allegroimg.com/original/11b1f7/0dc97de14df3a0a4157e3ad0caed","https://a.allegroimg.com/original/11f514/9287ea4d4c01910a8e12866874b1","https://a.allegroimg.com/original/11b230/9fdc20b740ababbbd7ce7325fd40","https://a.allegroimg.com/original/11dc57/4fe7fc0344a1be9cdbce6bfaaea6"],"name":"Męskie mokasyny skórzane wsuwane buty do jazdy","parameters":[{"id":"7108","valuesIds":["7108_1769718"]},{"id":"249512","valuesIds":["249512_1647413"]},{"id":"203093","values":["25"]},{"id":"22728","valuesIds":["22728_1"]},{"id":"224017","values":["25859"]},{"id":"127048","valuesIds":["127048_64"]},{"id":"6828","valuesIds":["6828_380577"]},{"id":"64","valuesIds":["64_2"]},{"id":"15851","valuesIds":["15851_2"]},{"id":"17448","values":["0.5"]},{"id":"203085","valuesIds":["203085_1"]},{"id":"203101","valuesIds":["203101_215285"]},{"id":"215922","values":["black"]},{"id":"215926","values":["1"]},{"id":"217481","values":["rubber"]},{"id":"219857","valuesIds":["219857_287861"]},{"id":"232289","valuesIds":["232289_366645"]},{"id":"234173","valuesIds":["234173_1","234173_2"]},{"id":"237206","values":["men loafers"]},{"id":"249516","valuesIds":["249516_1647640"]},{"id":"3766","valuesIds":["3766_8"]}]}}],"sellingMode":{"price":{"amount":"118","currency":"PLN"}},"stock":{"available":1000,"unit":"PAIR"},"taxSettings":{"rates":[{"countryCode":"CZ","rate":"21%"},{"countryCode":"SK","rate":"20%"},{"countryCode":"PL","rate":"23%"}],"subject":"GOODS"}}`

response:
{"errors":[{"code":"TransactionTaxSettingsNotFoundException","message":"Unprocessable Entity","details":null,"path":"tax","userMessage":"Tax settings not found"}]}

Did I miss any parameter？

**Comment by yu-www** [comment]
this is my new request: 
{"afterSalesServices":{"impliedWarranty":{"id":"f00c8fea-0afb-4223-bf36-8c23280492e0"},"returnPolicy":{"id":"1f27b00b-3863-46a9-b462-6728bf7a21fc"},"warranty":{}},"delivery":{"handlingTime":"PT24H","shippingRates":{"id":"fab5252f-fb4d-4d06-8621-d108de88450a"}},"description":{"sections":[{"items":[{"content":"<p>Gumowa podeszwa&nbsp;</p>\n\n<p>JAKOŚĆ NAJWYŻSZEJ JAKOŚCI: Nasze obuwie jest szyte ręcznie i wykonane z najwyższej jakości skr przy użyciu najnowocześniejszych maszyn i najnowocześniejszych technik.Wszystkie nasze produkty są wytwarzane ręcznie przez wykwalifikowanych rzemieślnikw, ktrzy mają duże doświadczenie w precyzyjnych technikach wytwarzania niezbędnych do wytworzenia produktu Oferujemy.&nbsp;</p>\n\n<p>NAJWYŻSZY KOMFORT: nasi specjaliści od zaopatrzenia przeszukują świat, aby zastosować najbardziej zaawansowaną technologię zapewniającą komfort na rynku.W pełni wyściełana wkładka, żelowa wkładka na piętę i tępe wsparcie łuku uzupełniają ten wspaniały mokasyn, aby zapewnić niezrwnany komfort i dopasowanie. Amortyzowana wkładka i oddychająca skrzana cholewka zapewni Ci wyjątkowe wsparcie dla Twoich wynikw.</p>\n\n<p>&nbsp;SOLIDNE WSPARCIE: Antypoślizgowa, elastyczna gumowa podeszwa kierowcy i amortyzacja zapewniają doskonały komfort, solidne wsparcie i przyczepność do chodzenia.Jest miękki w dotyku, ktry dopasowuje się do stopy podczas noszenia.Wygodny podczas chodzenia lub stania przez cały dzień.&nbsp;</p>\n\n<p>DOSKONAŁENA KAŻDĄ OKAZJĘ: codzienne mokasyny męskie mają swobodny design i świetnie nadają się na wszystkie okazje, takie jak spacery, jazda samochodem, na zewnątrz, wewnątrz, do biura i na zakupy.&nbsp;</p>\n\n<p>Działa zgodnie z rozmiarem.&nbsp;</p>\n\n<p>EU38 = długość stopy24cm&nbsp;</p>\n\n<p>EU39 = długość stopy 24,5 cm&nbsp;</p>\n\n<p>EU40 = długość stopy 25cm&nbsp;</p>\n\n<p>EU41 = długość stopy 25,5 cm&nbsp;</p>\n\n<p>EU42 = długość stopy 26cm&nbsp;</p>\n\n<p>EU43 = długość stopy 26,5 cm&nbsp;</p>\n\n<p>EU44 = długość stopy27cm&nbsp;</p>\n\n<p>EU45 = długość stopy 27,5 cm&nbsp;</p>\n\n<p>EU46 = długość stopy 28cm&nbsp;</p>\n\n<p>EU47 = długość stopy 28,5 cm&nbsp;</p>\n\n<p>EU48 = długość stopy 29cm</p>\n","type":"TEXT"},{"type":"IMAGE","url":"https://a.allegroimg.com/original/118566/d8e1153d41569e4d162536faefdc"}]}]},"external":{"id":"1104-1-39"},"images":["https://a.allegroimg.com/original/111176/07f727e848169c0af24c4ed5191a"],"location":{"city":"quanzhou","countryCode":"CN","postCode":"362000"},"name":"Męskie mokasyny skórzane wsuwane buty do jazdy","parameters":[{"id":"11323","valuesIds":["11323_1"]},{"id":"219629","valuesIds":["219629_286869"]},{"id":"229205","valuesIds":["229205_340245"]}],"payments":{"invoice":"NO_INVOICE"},"productSet":[{"product":{"category":{"id":"147418"},"images":["https://a.allegroimg.com/original/1160c2/157c0d6d412395f14c725e34962d","https://a.allegroimg.com/original/118566/d8e1153d41569e4d162536faefdc","https://a.allegroimg.com/original/111176/07f727e848169c0af24c4ed5191a","https://a.allegroimg.com/original/11d139/d4f8be804eabbdd4caea1d00c874","https://a.allegroimg.com/original/11f5df/b4f0288f4224832805b1c6920c53","https://a.allegroimg.com/original/111aa1/cdf210e740c5913f7226fede0a5b","https://a.allegroimg.com/original/117dbc/47ecb3304a28824815dfd690ece6","https://a.allegroimg.com/original/1132e0/80b66a0a435ba3e17573136f6bcd","https://a.allegroimg.com/original/111639/41f62df14f858aa99868b5d222c9","https://a.allegroimg.com/original/112195/d5b490ec4497ad4924bf0cf17edd","https://a.allegroimg.com/original/114baf/64aeb3c549df97412fd496de7041","https://a.allegroimg.com/original/1116b3/eae5eff140f082805460fc68c475"],"name":"Męskie mokasyny skórzane wsuwane buty do jazdy","parameters":[{"id":"7108","valuesIds":["7108_1769718"]},{"id":"249512","valuesIds":["249512_1647413"]},{"id":"203093","values":["25"]},{"id":"22728","valuesIds":["22728_1"]},{"id":"224017","values":["25859"]},{"id":"127048","valuesIds":["127048_64"]},{"id":"6828","valuesIds":["6828_380577"]},{"id":"64","valuesIds":["64_2"]},{"id":"15851","valuesIds":["15851_2"]},{"id":"17448","values":["0.5"]},{"id":"203085","valuesIds":["203085_1"]},{"id":"203101","valuesIds":["203101_215285"]},{"id":"215922","values":["black"]},{"id":"215926","values":["1"]},{"id":"217481","values":["rubber"]},{"id":"219857","valuesIds":["219857_287861"]},{"id":"232289","valuesIds":["232289_366645"]},{"id":"234173","valuesIds":["234173_1","234173_2"]},{"id":"237206","values":["men loafers"]},{"id":"249516","valuesIds":["249516_1647640"]},{"id":"3766","valuesIds":["3766_8"]}]}}],"sellingMode":{"price":{"amount":"118","currency":"PLN"}},"stock":{"available":1000,"unit":"PAIR"},"taxSettings":{"rates":[{"countryCode":"CZ","rate":"21"},{"countryCode":"SK","rate":"20"},{"countryCode":"PL","rate":"23"}],"subject":"GOODS"}}

the response is :
{"errors":[{"code":"TransactionTaxSettingsNotFoundException","message":"Unprocessable Entity","details":null,"path":"tax","userMessage":"Tax settings not found"}]}

I have removed "%",but still got the wrong response.

**Comment by AureliuszBrussy** [comment]
Send in your request taxSettings like this:

```
    "taxSettings": {
        "rates": [
            {
                "countryCode": "CZ",
                "rate": "21.00"
            },
            {
                "countryCode": "SK",
                "rate": "20.00"
            },
            {
                "countryCode": "PL",
                "rate": "23.00"
            }
        ],
        "subject": "GOODS"
    }
```
