### ISSUE TITLE
Brak  sposobu dostawy z zamówienia w delivery-services.

### ISSUE THREAD

**Issue by MaciejKost** [allegro/allegro-api#8612]
Zamówienie z allegro posiada sposób dostawy Allegro Paczkomat Inpost, które posiada ID 2488f7b7-5d1c-4d65-b85c-4cbcf253fd93.

Przy generowaniu paczki (parcel-management/parcel-create-commands) zostaje przekazywany ID wskazany wyżej, lecz zwrotnie otrzymuję błąd o treści:

"Wybrana metoda dostawy nie obsługuje tego zamówienia"

Wykonałem zapytanie, aby sprawdzić dostępne sposoby dostawy:
https://api.{environment}/parcel-management/[delivery-services.txt]

otrzymałem poniższe dane, w których nie ma sposobu dostawy z zamówienia.

(https://github.com/allegro/allegro-api/files/14538054/delivery-services.txt)

Jakie rozwiązać problem?

**Comment by MartaNowaczyk** [comment]
Podaj proszę trace-id z odpowiedzi z tym błądem.

**Comment by MaciejKost** [comment]
Trace id : "622dd1087b3b7a8a"

**Comment by MartaNowaczyk** [comment]
Sprawdź proszę czy na pewno masz oddaną [umowę własną](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/wysylam-z-allegro-narzedzie-do-nadawania-przesylek-bezposrednio-z-konta-E7doGw8VgI1#jak-dodac-umowe-wlasna-w-wysylam-z-allegro) dla tego przewoźnika. Wygląda jakby jej brakowało.
