### ISSUE TITLE
Add product, which is not in Allegro Catalog through API

### ISSUE THREAD

**Issue by EugenBodanov** [allegro/allegro-api#8613]
Good afternoon, could you please send me a link to a guide, where described how I can add my products through API, which are not in Allegro Catalog?

**Comment by MartaNowaczyk** [comment]
Links to our guide:
- [list an active offer assigned to a product, which is not in our Catalog](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71B).
- [create a product](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-create-a-product)

**Comment by EugenBodanov** [comment]
First link doesn't work:
![image](https://github.com/allegro/allegro-api/assets/124465640/32b2f629-473b-4ef9-8777-3fcc4a85666b)
where can I find all categories, which Allegro has?

**Comment by PrzemyslawLukanowski** [comment]
There was a typo, the correct link is https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-list-an-offer-assigned-to-a-new-product.

You can retrieve all categories using [GET /sale/categories](https://developer.allegro.pl/documentation#operation/getCategoriesUsingGET).
