### ISSUE TITLE
Które zasoby wymagają których uprawnień

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#8614]
1. Zauważyłem, że zasób /sale/allegro-prices-offer-consents/{offerId} wymaga uprawnienia do allegro:api:profile:read. Czy to nie pomyłka że taki zasób wymaga tego samego uprawnienia co np. zasób /me?

2. Gdzie mogę znaleźć który zasób wymaga którego uprawnienia? W https://developer.allegro.pl/documentation/ nie wszystkie zasoby mają to opisane. Albo w drugą stronę -  jak mogę łatwo znaleźć wszystkie zasoby które wymagają np. allegro:api:profile:read?

Dopytuję ponieważ nie chcę zmuszać klientów do nadawania wszystkich uprawnień a jedynie tych które są faktycznie niezbędne.

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Odpowiadając na pytania:
1. Nie jest to pomyłka. Z tym zasobem współgra zasób [GET /sale/allegro-prices-account-eligibility](https://developer.allegro.pl/documentation/#operation/getAllegroPricesEligibilityForAccount), który zwraca informacje o zgodzie konta na uczestnictwo w Allegro Ceny, zatem by nie mieszać różnych scope'ów został przypisany jeden i ten sam.
2. [Tu](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#scope-w-api-allegro) zwracamy listę wszystkich scope'ów wraz z opisem głównych funkcjonalności dla nich przewidzianych.
