### ISSUE TITLE
PUT /sale/offer-publication-commands/{commandId}

### ISSUE THREAD

**Issue by api-test-yexiu** [allegro/allegro-api#8616]
PUT /sale/offer-publication-commands/{commandId}
How do I get {commandId}

**Comment by PrzemyslawLukanowski** [comment]
You need to generate [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) on your side.

**Comment by api-test-yexiu** [comment]
Can you describe it in detail? How to obtain {commandId}

**Comment by PrzemyslawLukanowski** [comment]
CommandId/UUID is a globally unique identifier that consists of 32 hexadecimal numbers (e.g.: f89a3fd6-3193-4d4a-896c-a117b5ae33f2), it is not something you obtain/retrieve from Allegro, you need to generate it by yourself. How - it depends on which programming language you are using. Please check the possible solutions on the Internet.

**Comment by api-test-yexiu** [comment]
```
 {
    "modification": {
        "publication": {
            "duration": "PT480H"          
        }
    },
    "offerCriteria": [
        {
        "offers": [
            {
                "id": "15273033209"
            }
        ],
                "type": "CONTAINS_OFFERS"
        }
    ]
 }
```

```
{
    "errors": [
        {
            "code": "COMMAND_ALREADY_REGISTERED_WITH_DIFFERENT_CONTENT",
            "message": "Command with the given id but with different content is already registered.",
            "details": null,
            "path": "",
            "userMessage": "Command with the given id but with different content is already registered."
        }
    ]
}
```

Why can't I edit twice? Are there any restrictions?

**Comment by PrzemyslawLukanowski** [comment]
Yes, the given commandID can be used only once, you need to generate a new commandID for every new command.

**Comment by api-test-yexiu** [comment]
okay

**Comment by api-test-yexiu** [comment]
```
GET /sale/offer-modification-commands/9b1c1e4e-3c44-44bf-a99d-5c37df8af517/tasks HTTP/1.1
Host: api.allegro.pl
Authorization:  Bearer token
Content-Type:  application/vnd.allegro.public.v1+json
Accept:  application/vnd.allegro.public.v1+json
Content-Length: 314

 {
    "modification": {
        "publication": {
            "duration": "PT480H"          
        }
    },
    "offerCriteria": [
        {
        "offers": [
            {
                "id": "15273033209"
            }
        ],
                "type": "CONTAINS_OFFERS"
        }
    ]
 }
```

```
{
    "tasks": [
        {
            "offer": {
                "id": "15273033209"
            },
            "message": "EXCEPTION_WHILE_DURATION_LIMIT_UPDATE",
            "status": "FAIL",
            "field": "duration",
            "errors": [
                {
                    "code": "IllegalOfferUpdateException.DurationLimitChangeAfterActivation",
                    "message": "You cannot change the offer duration.",
                    "details": null,
                    "path": "publication.duration",
                    "userMessage": "You cannot change the offer duration."
                }
            ]
        }
    ]
}
```I don’t understand why the modification failed

**Comment by PrzemyslawLukanowski** [comment]
Please check the `message` or `userMessage` - "You cannot change the offer duration".

**Comment by api-test-yexiu** [comment]
why,
![image](https://github.com/allegro/allegro-api/assets/155221200/162be24a-7ecd-4976-b9e5-531c93443c84)
I can modify it successfully in the background, but why can’t the interface be modified?

**Comment by PrzemyslawLukanowski** [comment]
I'm not sure what operations you have performed, but I checked it and the offer duration cannot be changed:

<img width="389" alt="Zrzut ekranu 2024-03-11 o 10 54 02" src="https://github.com/allegro/allegro-api/assets/51473661/517004ba-1a8e-4110-8422-815fc6621a30">

as in our [article](oferty-przez-formularz/jak-zmienic-szczegoly-oferty-po-jej-wystawieniu-3GBbgYX1RSn):

<img width="611" alt="Zrzut ekranu 2024-03-11 o 10 54 57" src="https://github.com/allegro/allegro-api/assets/51473661/c717cc19-7a50-40b4-9148-5328e5607cab">

**Comment by api-test-yexiu** [comment]
oh , no 
![image](https://github.com/allegro/allegro-api/assets/155221200/51b0aecb-65ce-4fa5-a570-94f8da4513f4)
What I want to modify is this value

**Comment by PrzemyslawLukanowski** [comment]
This field is `delivery.handlingTime `and it cannot be changed in bulk.
