### ISSUE TITLE
Endpoint order/events - Full authentication is required to access this resource

### ISSUE THREAD

**Issue by studiowizjo** [allegro/allegro-api#8617]
During an attempt to query through the API to the endpoint "https://api.allegro.pl/order/events", we receive an error:

`401 Unauthorized`

The entire response is:

```json
{
    "error": "unauthorized",
    "error_description": "Full authentication is required to access this resource"
}
```

Our request is:

- Method: "GET"
- No query parameters (we want to initially fetch everything)

Headers:

```json
{
    "Accept": "application/vnd.allegro.public.v1+json",
    "Accept-Language": "pl-PL",
    "Authorization": "...cut...", // Can be checked in the email sent on 07.03
    "Content-Type": "application/vnd.allegro.public.v1+json"
}
```

As for the authorization, we tried both "Authorization Code flow" and "Device flow", and in both cases, we are authorizing correctly. However, when making a request to this endpoint, nothing changes, and it's always this error. The above request is made for the "Device flow" method.

I have also submitted a report through Allegro on 07.03 but have not received a response, so I am reporting it this way as well. In my report, the headers are not censored, so it may give a bit more information.

**Comment by studiowizjo** [comment]
Where can I get the "trace-id"? I couldn't find anything about it in the documentation: https://developer.allegro.pl/documentation, nor do I see such a value in the response. It only returns the information that I pasted above.

**Comment by PrzemyslawLukanowski** [comment]
The trace-id can be retrieved in the response headers. You can also send me your client id, I will try to track this request that way.

**Comment by PrzemyslawLukanowski** [comment]
More information about trace id can be found here https://developer.allegro.pl/tutorials/basic-information-VL6YelvVKTn#communication-protocol.

**Comment by studiowizjo** [comment]
Ok, got it. Trace-id: `b9336068a223ec2a`

**Comment by PrzemyslawLukanowski** [comment]
Thank you. I've checked our logs and they confirm what I mentioned earlier - we didn't receive any token, so please make sure you are providing it correctly, along with the Authorization header.

**Comment by studiowizjo** [comment]
So, how should the request look like? What am I missing? Could you provide, for example, a curl command format or a Guzzle request example to see where the problem lies?

From our side, it appears that the headers are being sent. I don't know why they are not visible in your logs.

Here is a curl example of request which I tried to test in Postman:

```
curl --location 'https://api.allegro.pl/order/events' \
--header 'Basic: our_secret_value' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Accept-Language: pl-PL'
```

or as PHP Guzzle simplified snippet:

```php
<?php

$client = new Client();

$headers = [
  'Basic' => 'our_secret_value',
  'Accept' => 'application/vnd.allegro.public.v1+json',
  'Content-Type' => 'application/vnd.allegro.public.v1+json',
  'Accept-Language' => 'pl-PL'
];

$request = new Request('GET', 'https://api.allegro.pl/order/events', $headers);
$response = $client->sendAsync($request)->wait();

echo $response->getBody();
```

**Comment by studiowizjo** [comment]
Ok, I've found it. The reason was that only in the authorization request, the "Authentication" header should be of type "Basic" and constructed based on client_id and client_secret, whereas in all subsequent requests, it should be of type "Bearer" and use the token.

Thank for engagement =).
