### ISSUE TITLE
Nazwa odbiorcy jest za krótka

### ISSUE THREAD

**Issue by daniel93333** [allegro/allegro-api#8618]
W zapytaniu o commandId a77741eb-a138-4fc6-8f8d-091a906107ae dostałem błąd, że "nazwa odbiorcy jest za krótka". Nazwą tą było "Grzegorz K". Mimo, że brak pełnego nazwiska istnieją imiona i nazwiska krótsze niż cała ta fraza.

**Comment by PrzemyslawLukanowski** [comment]
Walidacja bierze pod uwagę zarówno imię, jak i nazwisko - nazwisko nie może składać się z jednej litery, stąd zwrócony błąd.

**Comment by daniel93333** [comment]
Jak to się ma do rodo i cenzurowania danych na etykietach?
Przecież klient miał prawo nie przekazywać pełnego nazwiska.
Druga sprawa dlaczego pozwalacie na składanie zamówień z danymi do wysyłki, które nie spełniają waszej walidacji?

**Comment by PrzemyslawLukanowski** [comment]
Na forum świadczymy wsparcie w tematach technicznych związanych z API, pytanie o rodo skieruj proszę do[ formularza kontaktowego](https://allegro.pl/pomoc/kontakt), ponieważ przedstawiony wymóg nie jest ograniczeniem stricte po stronie API, ale całego narzędzia Wysyłam z Allegro. Jeśli chodzi o drugie pytanie, to walidacja pola występuje po stronie przewoźnika. Nazwisko musi posiadać minimum dwa znaki, zatem wystarczy, że w takim przypadku dodasz kropkę.

**Comment by daniel93333** [comment]
Hmmm dodawałem podkręślnik i nie przeszło, czy możecie potwierdzić, że kropka będzie zaakceptowana?

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale nie możemy tego uogólnić, dany przewoźnik może mieć wymaganie dotyczące braku znaków specjalnych lub/i ilości znaków dla danego wyrażenia (tutaj poprawię moją poprzednią wypowiedź, część przewoźników może oczekiwać np. trzech znaków zamiast dwóch).
