### ISSUE TITLE
Autoryzacja 

### ISSUE THREAD

**Issue by Eryk1997** [allegro/allegro-api#8619]
Próbuję dokonać autoryzacji na koncie sandbox: 
https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=a6212e5eb8bd49b085b81db4e8932c3a&redirect_uri=http://localhost:8080/shop/apteka/allegro/account/authorization&code_challenge_method=XXXX

ale dostaję błąd.

Zostałeś zablokowany.
Dlaczego zostałeś zablokowany? Coś w zachowaniu twojej przeglądarki zwróciło naszą uwagę. Powody mogą być różne:

    przeglądasz strony i klikasz dużo szybciej niż przeciętny człowiek
    coś uniemożliwia działanie Javascript na twoim komputerze
    w tej samej sieci (IP 192.162.146.195) operuje robot

Jeśli coś nie działa prawidłowo
ID: e6576409-2b1d-307d-4e31-b650d26db86e

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za dane, zweryfikujemy sytuację i wrócimy z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
@Eryk1997 Czy problem nadal występuje?
