### ISSUE TITLE
Przekroczono czas wykonania zapytania. Spróbuj ponownie.

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#8620]
Przy wczytywaniu zwrotów metodą **/order/customer-returns**
otrzymuję komunikat:
"Przekroczono czas wykonania zapytania. Spróbuj ponownie."

Problem pojawia się od piątku.

Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że w piątek po naszej stronie miały miejsce prace, które mogły przyczynić się do tego stanu rzeczy. Przepraszam za niedogodności. Sytuacja powinna się już unormować, jeśli jednak cały czas zwracamy time-outy, podaj proszę przykładowe trace-id.
