### ISSUE TITLE
Automatyzacja cen

### ISSUE THREAD

**Issue by PavvelSte** [allegro/allegro-api#8622]
Dzień dobry,
Chcę dodać do swojej aplikacji możliwość monitorowania cen konkurencji dla swoich produktów. Widzę że są firmy zajmujące się tym profesjonalnie. Jednak nie mogę znaleźć w Waszej dokumentacji z jakich endpointów korzystają. W jaki sposób te firmy pobierają dane do analizy i jak uzyskać dostęp do tych informacji?

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Służy do tego endpoint [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing), jednak dostęp do niego mają wyłącznie zweryfikowane aplikacje.

Jeśli jesteś w [Programie Partnerskim](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm), skontaktuj się ze swoim opiekunem. W innym wypadku napisz do nas przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
