### ISSUE TITLE
Brakujący event READY_FOR_PROCESSING

### ISSUE THREAD

**Issue by szymanski-m** [allegro/allegro-api#8623]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Występuje problem z pobraniem zamówienia które pojawiło się o godzinie 01:05 dnia 12.03.2024.

Curl do pobrania zamówienia (bez headera autoryzacyjnego):

```
curl --location 'https://api.allegro.pl/order/events?limit=1000&type=READY_FOR_PROCESSING&from=1710201704621169' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
```

Po wysłaniu tego curla nie otrzymuję zamówienia które zostało złożone o godzinie 01:05. Ostatnie zamówienie, które skrypt pobrał jest z 01:01.
Id brakującego zamówienia to `26960140-e004-11ee-ace1-654d2e5507bf`. Skrypt, którego używam działał przez długi czas, aż do teraz, więc podejrzewam że problem jest po stronie API allegro. 

Problem wygląda na podobny, jak tutaj: https://github.com/allegro/allegro-api/issues/8498#event-11888499750

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam problem. Pracujemy nad rozwiązaniem, wrócę z informacją, gdy wyślemy brakujące eventy.

**Comment by PrzemyslawLukanowski** [comment]
Event powinien już być dostępny, przepraszam za utrudnienia.

**Comment by szymanski-m** [comment]
Dziękuję!
