### ISSUE TITLE
POST /sale/product-offers, Error: Not Found

### ISSUE THREAD

**Issue by CrazyTaolt** [allegro/allegro-api#8624]
API : /sale/product-offers
Method: POST
Error: Not Found

May I ask if the platform API is currently being updated? We are currently experiencing many 404 errors

**Comment by PrzemyslawLukanowski** [comment]
We have [maintenance work on Sandbox](https://developer.allegro.pl/news/sandbox-upcoming-maintenance-YWBrqo8rVHA) but on the Production environment, everything works properly. On which environment are you facing this issue? If on Production, please send us sample trace-ids.
