### ISSUE TITLE
Błąd Szukaj

### ISSUE THREAD

**Issue by vderka** [allegro/allegro-api#8630]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ X] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Po wygenerowaniu dummy tekstu i wklejeniu go do pola wyszukiwarki [Szukaj] 
Generated 100 paragraphs, 9219 words, 62771 bytes of [Lorem Ipsum](https://www.lipsum.com/)
![error](https://github.com/allegro/allegro-api/assets/60393506/c140cc82-4a36-42a3-89fe-eecbcde663c9)

Strona nie wyświetla komunikatu typu "Nie mamy tego czego szukasz" tylko strona się nie wczytuje.
![error2](https://github.com/allegro/allegro-api/assets/60393506/19688ac0-eb6e-4f91-8322-5ca3a5646fd7)

**Comment by MaciejFrackowiak** [comment]
Napotkany problem z działaniem wyszukiwarki na stronie WWW zgłoś proszę poprzez [formularz kontaktowy Allegro](https://allegro.pl/pomoc/kontakt).
