### ISSUE TITLE
Aktywacja konta i Allegro Smart dla kupującego na Sandbox

### ISSUE THREAD

**Issue by Aleksandrze** [allegro/allegro-api#8632]
Dzień dobry

Proszę o aktywowaniu kont na Sandbox oraz nadania SMART dla konta kupującego:

* mrooczek - sprzedający
* majabe - kupujący (aktywacja smart)

Dziękuje

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry,

Aktywowałem konto mrooczek, dla konta majabe jako rodzaj konta wybrałeś firmowe z opcją sprzedaży - spróbuj proszę wykonać zakup, istnieje jednak prawdopodobieństwo, że je także będziemy musieli w pełni aktywować. W takim przyopadku uzupełnij najpierw konto bankowe przez [ustawienia wypłat ](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat). 
Opcję Smart dla kupującego możesz "opłacić" samodzielnie przez stronę https://allegro.pl.allegrosandbox.pl/smart (w metodach płatności wybierz proszę przelew bankowy i np. Santander).

**Comment by Aleksandrze** [comment]
Dziękuje 

Mam jeszcze jedno pytanie odnośnie sprzedaży. Dobrze rozumiem że na sanboxie, sprzedający też musi spełniać wszystkie wymagania jak w tym artykulie: https://allegro.pl/pomoc/dla-sprzedajacych/informacje-dla-sprzedajacych/co-zrobic-aby-moje-oferty-byly-oznaczone-ikona-allegro-smart-lDkP8VbKncV, aby kupujący mogli kupować u niego ze SMART?

Jeżeli tak, to czy istniej możliwość dodania opinij i td .dla konta mrooczek?

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale w tym przypadku musisz samodzielnie wypełnić opisane warunki.

**Comment by Aleksandrze** [comment]
Dzień dobry

Proszę o aktywowaniu kont na Sandbox:

    majabe - sprzedający 

Dziękuje

**Comment by PrzemyslawLukanowski** [comment]
@Aleksandrze Aktywowałem Twoje konto.

**Comment by Aleksandrze** [comment]
@PrzemyslawLukanowski  dziękuje, jednak z kontem jest coś nie tak.
Info od testera: ogólnie niby konto działa, ale nie można nadać przesyłek
![obraz](https://github.com/allegro/allegro-api/assets/44478401/f96c4d0a-14c3-468e-bfd2-afff197dc700)

**Comment by PrzemyslawLukanowski** [comment]
W takim przypadku poprosimy o commandId powiązane z próbą utworzenia przesyłki. Upewnijcie się, że przekazujecie prawidłowy mail odbiorcy z zamówienia.

**Comment by Aleksandrze** [comment]
Teraz tester ma coś takiego na stronie Allegro przy próbie utworzenia paczki 
![obraz](https://github.com/allegro/allegro-api/assets/44478401/be8f1389-521e-4431-b969-dc5571277807)

**Comment by Aleksandrze** [comment]
Teraz przy próbie użycia API na momencie pobrania listy dostawców w odp dostałem to:
[toString() unavailable - no suspended threads] zamiast listy dostawców

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję ten problem z zespołem odpowiedzialnym za Wysyłam z Allegro. Wrócę z odpowiedzią, jak tylko uda nam się namierzyć jego źródło.

**Comment by PrzemyslawLukanowski** [comment]
Wygląda na to, że Wasze konto na Wysyłam z Allegro zostało źle utworzone, zresetowaliśmy  je. Aktywuj usługę jeszcze raz [zgodnie z instrukcją:](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY)
<img width="504" alt="Zrzut ekranu 2024-04-23 o 09 38 53" src="https://github.com/allegro/allegro-api/assets/51473661/b1bc5188-9e44-456a-9f09-421ace135227">
