### ISSUE TITLE
Przesyłka paletowa DPD

### ISSUE THREAD

**Issue by caroteczek** [allegro/allegro-api#8633]
Dzień dobry,

mam pytanie, czy można poprzez api Allegro nadać przesyłkę gabarytową/paletową na umowie własnej przewoźnika DPD ?
Chodzi o przesyłki, które przekraczają dopuszczalną wagę gabarytową, i stają się z automatu przesyłkami paletowymi.

**Comment by AureliuszBrussy** [comment]
Tak, możesz nadać przesyłkę gabarytową/paletową w usłudze DPD przez API Wysyłam z Allegro.

**Comment by caroteczek** [comment]
Dziękuję, ale czy może mi pan podać link do dokumentacji ? Ponieważ testując to na stronie Allegro, wysyłając paczkę na umowie własnej z przewoźnikiem dodanej do Wysyłam Allegro, nie mogę wysłać paczki ze względu na przekroczenie wagi gabarytowej:
[
![2024-03-13_11h00_47](https://github.com/allegro/allegro-api/assets/157691660/3bfde351-dec1-48ff-8178-b67e4149e18b)
](url)
![2024-03-13_11h00_47](https://github.com/allegro/allegro-api/assets/157691660/70944d05-0ae6-472b-91f5-02293bc8fb34)

Ale rozumiem, że bezpośrednio przez stronę Allegro nie mam takiej możliwości, ale już połączenie api na to zezwala ?
