### ISSUE TITLE
Jak pobrać kod potrzebny do wygenerowania access tokena w alikacji desktopowej (na Windows)

### ISSUE THREAD

**Issue by maniootek** [allegro/allegro-api#8638]
Potrzebuję uzyskać access token i refresh token od użytkownika mojej aplikacji desktopowej. Muszę wygenerować odpowiedni link do allegro z moim client Id i uruchomić go w przeglądarce dla użytkownika, żeby mógł sięz zalogować wpisująć swój login i hasło. Z tym sobie poradzę uruchamiając taki kod w języku AutoIt:
`Local $URL ="https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=" & $g_ALLEGRO_CLIENT_ID & "&redirect_uri=" & $g_URL_REDIRECTION"`
`ShellExecute($URL)`
ale jak potem pobrać z przeglądarki ten kod w adresie który się pojawia? Ktoś podpowie?
![image png b7a687dcfcdc34bf81293def7d2a8405 1](https://github.com/allegro/allegro-api/assets/45625552/9ea9071d-b755-4ae2-b7f0-8362938b52b7)

**Comment by AureliuszBrussy** [comment]
Nie prowadzimy takiego wsparcia, natomiast być może któryś z użytkowników zaglądających do zgłoszeń miał takie doświadczenia i będzie w stanie Ci coś powiedzieć.

**Comment by many-to-one** [comment]
Musisz stworzyć html plik i użyj JavaScript:

const urlParams = new URLSearchParams(window.location.search);
const code = urlParams.get('code');

**Comment by Toumash** [comment]
Dokładnie tak + taką stronę musisz zahostować jakoś. Nie mam pojęcia jak wygląda taki deployment w autoit ale chatgpt mówi, że żeby taki prosty serwer www postawic lokalnie wystarczy taki kodzik - tutaj masz przejęcie tego `?code=XXXX` z querystring z którym możesz już dokończyć cały flow uwierzytelnienia (zamienic go na access_token)

```
#include <Array.au3>
#include <HTTPConstants.au3>
#include <Inet.au3>

; Start the local server
TCPStartup()
$listenSocket = TCPListen("127.0.0.1", 8080)
If $listenSocket = -1 Then
    MsgBox($MB_SYSTEMMODAL, "Error", "Failed to start the server")
    Exit
EndIf

MsgBox($MB_SYSTEMMODAL, "Server", "Server is running. Waiting for authorization...")

; Wait for a connection
While True
    $acceptSocket = TCPAccept($listenSocket)
    If $acceptSocket <> -1 Then
        ; Received a request
        $request = TCPRecv($acceptSocket, 2048)
        
        ; Extract the authorization code from the request
        $authCode = StringRegExpReplace($request, ".*code=([^& ]+).*", "\1")
        If $authCode <> "" Then
            MsgBox($MB_SYSTEMMODAL, "Authorization Code", "Authorization code: " & $authCode)
            ; You can now proceed to exchange the authorization code for an access token.
        EndIf
        
        ; Send a response to the browser
        TCPSend($acceptSocket, "HTTP/1.1 200 OK" & @CRLF & "Content-Type: text/plain" & @CRLF & @CRLF & "Authorization successful. You can close this window.")
        TCPCloseSocket($acceptSocket)
        ExitLoop
    EndIf
WEnd

TCPShutdown()

```

**Comment by maniootek** [comment]
@Toumash dzięki wielkie za poświęcony czas i dobre chęci! Właśnie już korzystałem chata-gpt i to samo mi zaproponował, problem było wykonanie tego kodu w pętli dla wielu kont ale już sobie międzyczasie poradziłem. Dzieki jeszcze raz! temat można zamknąć
