### ISSUE TITLE
No title in an offer 

### ISSUE THREAD

**Issue by justynapalka** [allegro/allegro-api#8639]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Can you please support me why for any offers send via API second title, so not the one generated automatically doesn't match with our internal PIM system?

An offer: https://allegro.pl/oferta/kurtka-regatta-yare-vii-r-s-15295290177

Product feed:

{
    "name": "Regatta - M\u0119ski softshell Yare VII",
    "category": {
        "id": "112290"
    },
    "images": [
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11d256\/ab8b8b1c402e966bd76a7c8a8433"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/1118a6\/14a6086e4c65bd6f8215b43a8a66"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/1138a8\/a296489c454db2e43ac58f8dadda"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11e3e6\/7db9b97045b4894de0fba7b74a94"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11254d\/549691a64451b59d49eff80904e0"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/110db0\/2a16d66247dd8da411ebd1f721d2"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/119310\/3c7e044a4e9bb78c76f9154be250"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/117af7\/7362666842bc97accad7ed6144c4"
        }
    ],
    "parameters": [
        {
            "id": "224017",
            "values": [
                "RML242"
            ]
        },
        {
            "id": "130411",
            "valuesIds": [
                "130411_2"
            ]
        },
        {
            "id": "210746",
            "valuesIds": [
                "210746_256"
            ]
        },
        {
            "id": "249512",
            "valuesIds": [
                "249512_1647422"
            ]
        },
        {
            "id": "25588",
            "valuesIds": [
                "25588_244546"
            ]
        },
        {
            "id": "206438",
            "valuesIds": [
                "206438_227562"
            ]
        },
        {
            "id": "25748",
            "valuesIds": [
                "25748_16"
            ]
        },
        {
            "id": "25929",
            "valuesIds": [
                "25929_26"
            ]
        },
        {
            "id": "215930",
            "values": [
                "90% Poliester",
                "10% Elastan"
            ]
        },
        {
            "id": "237206",
            "values": [
                "Yare VII"
            ]
        },
        {
            "id": "237210",
            "values": [
                "Yare VII"
            ]
        },
        {
            "id": "54",
            "valuesIds": [
                "54_3"
            ]
        },
        {
            "id": "225693",
            "values": [
                "5063019249643"
            ]
        }
    ],
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h1>Regatta - M\u0119ski softshell Yare VII<\/h1><p>Elastyczna i elegancka, nasza m\u0119ska kurtka rozpinana Yare VII to idealny wyb\u00f3r na aktywne dni. Wykonana ze stretchu Extol z recyklingu, ta sportowa kurtka dostosowuje si\u0119 do twoich ruch\u00f3w. Kolorowe panele nadaj\u0105 jej energetyczny wygl\u0105d.<\/p><ul><li>Dzianina Extol Stretch z ciep\u0142ym spodem - 90% poliester\/10% elastan - 235 g\/m\u00b2<\/li><li>Panele z elastycznej siatki - 96% poliester z recyklingu\/4% elastan - 220 g\/m\u00b2<\/li><li>2 dolne zasuwane kieszenie<\/li><li>Elastyczne \u0142\u0105czenie przy ko\u0142nierzu, mankietach i dolnej kraw\u0119dzi<\/li><\/ul><p><b>Technologia:<\/b><\/p><p>Extol Stretch: Ergonomiczna i elastyczna tkanina do czynno\u015bci wymagaj\u0105cych du\u017cej energii<\/p><p>Tkanina z recyklingu: Wykonane z recyklingowanych plastikowych butelek<\/p><p><b>Materia\u0142:<\/b><\/p><p>90% Poliester, 10% Elastan<\/p>"
                    }
                ]
            }
        ]
    },
    "language": "pl-PL"
}

**Comment by AureliuszBrussy** [comment]
That is because of the way you are creating offers. You created this offer by using a product that exists in our product catalog, and you did not set the name of the offer - hence we are using the name of the product (from our Product Catalog) in the offer name. You should set you own offer title in `name` field. Documentation is available [here](https://developer.allegro.pl/documentation#operation/createProductOffers).
