### ISSUE TITLE
Problem po nadaniu przesyłki

### ISSUE THREAD

**Issue by DanyloSydorchukYosi** [allegro/allegro-api#8642]
Po nadaniu przesyłki na środowisku produkcyjnym nie możemy pobrać etykiety.
TraceId: 415f9944093f1d6e

**Comment by MaciejFrackowiak** [comment]
Problem generuje samo zamówienie - Allegro One Kurier nie obsługuje tzw. wielopaczki, a w requeście umieściłeś dwie przesyłki. Nadaj każdą z nich osobno.
