### ISSUE TITLE
Dostęp do API bez konta sprzedawcy

### ISSUE THREAD

**Issue by kacperKarman** [allegro/allegro-api#8643]
Czy jest jakiś sposób na wygenerowanie potrzebnych tokenów i tym samym uzyskanie dostępu do API bez konieczności zakładania konta sprzedawcy? 
Czy istnieje możliwość stworzenia czegoś w rodzaju konta deweloperskiego i dodania tam aplikacji z dostępem do zasobu offers/listing?

**Comment by MaciejFrackowiak** [comment]
Nie, nie mamy takiej możliwości. Musisz posiadać konto użytkownika, aby zarejestrować swoją aplikację, z której następnie będziesz wykonywać requesty do API Allegro.

**Comment by kacperKarman** [comment]
A czy po pełnej aktywacji konta i ustawieniu dwustopniowego logowania ale bez aktywacji konta firmowego otrzymam bez problemu dostęp do zasobu offers/listing dla aplikacji którą podłączę do tego konta?

**Comment by MaciejFrackowiak** [comment]
Nie, dostęp do zasobu [/offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) jest limitowany. Musisz mieć [zweryfikowaną](https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk) aplikację by korzystać z tego zasobu.

**Comment by kacperKarman** [comment]
Na czym polega ta weryfikacja aplikacji? Widzę że musiałbym się skontaktować w tej sprawie przez formularz z linku. Na jakiej podstawie później dostęp do tego zasobu może zostać mi przyznany lub nie?

**Comment by MaciejFrackowiak** [comment]
Kwestia przyznawania dostępu i samych wymogów jest poza nami - to kwestia biznesowa, stąd niezbędny jest kontakt bezpośrednio z obsługą Allegro.

**Comment by kacperKarman** [comment]
Ok rozumiem, wszystko już jest chyba dla mnie jasne w tej kwestii. Dziękuję za informacje.
