### ISSUE TITLE
C# RESTApi Offers Listing

### ISSUE THREAD

**Issue by aaa1niepodam** [allegro/allegro-api#865]
Czy jest jakiś normalny sposób żeby skorzystać z REST API w aplikacji C# okienkowej/formsowej?

Zależy mi jedynie na metodzie **/offers/listing**, próbowałem ją wywołać bez tokena, ale jest błąd że trzeba być zalogowanym czy tam uwierzytelnionym aby z niej skorzystać.
A pobierania tokena nie da się wykonać bez jakiś ręcznych kombinacji.

**Comment by rtnet-pl** [comment]
Nie próbowałem wywoływać tej metody bez autoryzacji, chociaż niby się da. Mamy aplikacje w C# która korzystają z REST, niestety trzeba dopisać sobie serwis który w tle będzie odnawiać tokeny co kilka godzin.

**Comment by PawelTaberski** [comment]
Aby korzystać z takich metod nie potrzeba tokenu usera wystarczy autoryzacja typu client credentials.  Pobierasz token tylko na podstawie clientID, secret i flow client_credentials. W takim wypadku token nie ma kontekstu klienta.

**Comment by mrzechowicz** [comment]
Możesz rozwinąć temat "flow client_credentials" lub podać linka do dokumentacji?
https://developer.allegro.pl/auth/ tu nie ma o tym słowa.
Robię zapytanie z client_id:
`"https://allegro.pl/auth/oauth/authorize?response_type=code&client_id="+ clientId +"&redirect_uri=http://localhost:8000`
Po przekierowaniu mam code i to co dostaję muszę wpisać w:
`https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code="+code+"&redirect_uri=http://localhost:8000";`

a później token, który jest dodaje w ostatniej linijce, ale jak to uprościć:
```
            var client = new RestClient(url);
            var request = new RestRequest(Method.GET);
            request.AddHeader("Accept", "application/vnd.allegro.public.v1+json");
            request.AddHeader("content-type", "application/vnd.allegro.public.v1+json");
            request.AddHeader("Authorization", $"Bearer {accessToken}");
```

**Comment by aaa1niepodam** [comment]
Możesz rozwinąć temat "flow client_credentials" lub podać linka do dokumentacji?
https://developer.allegro.pl/auth/ tu nie ma o tym słowa.
Robię zapytanie z client_id:
`"https://allegro.pl/auth/oauth/authorize?response_type=code&client_id="+ clientId +"&redirect_uri=http://localhost:8000`
Po przekierowaniu mam code i to co dostaję muszę wpisać w:
`https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code="+code+"&redirect_uri=http://localhost:8000";`

a później token, który jest dodaje w ostatniej linijce, ale jak to uprościć:
```
            var client = new RestClient(url);
            var request = new RestRequest(Method.GET);
            request.AddHeader("Accept", "application/vnd.allegro.public.v1+json");
            request.AddHeader("content-type", "application/vnd.allegro.public.v1+json");
            request.AddHeader("Authorization", $"Bearer {accessToken}");
```

**Comment by PawelTaberski** [comment]
@aaa1niepodam Token przy pomocy flow client_credentials. otrzymasz robiąc takiego POST-a na 
`curl -XPOST --basic client_id:secret https://allegro.pl/auth/oauth/token --data 'grant_type=client_credentials'`
gdzie client_id -> to client id a secret to secret

**Comment by AmazingDesign** [comment]
@PawelTaberski jak się ma konieczność wysyłania `grant_type` jako form-data skoro w Waszej dokumentacji jest napisane, że wszystko idzie w obie storny JSON-ami.

Bardzo mylące wg mnie :/

**Comment by PawelTaberski** [comment]
W dokumentacji nie mamy opisanej tej formy, niedługo uzupełnimy ten brak.

**Comment by AmazingDesign** [comment]
Macie napisane, że całe API używa JSON-ów. Uzupełnijcie koniecznie. Bo stracony kawał czasu.

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem co masz na myśli API Allegro składa się z 2 środowisk WebAPI i REST API jedno jest oparte na XML a drugie JSON.
