### ISSUE TITLE
HttpMessageNotReadableException when calling sale/product-proposals

### ISSUE THREAD

**Issue by MKI-Miro** [allegro/allegro-api#8652]
Hi, I am getting \"HttpMessageNotReadableException which is not very helfull. Can you please write me a tip what should be wrong when calling sale/product-proposals

Thank you

`{
  "name": "Sung Kim: Port",
  "description": null,
  "category": {
    "id": "257813"
  },
  "images": [
    {
      "url": "https://a.allegroimg.com/original/116071/b95998d341ea87b8612db2880203"
    }
  ],
  "parameters": [
    {
      "id": "224017",
      "rangeValue": null,
      "values": [
        "3129"
      ],
      "valuesIds": null,
      "valuesLabels": null,
      "unit": null,
      "options": null
    },
    {
      "id": "201325",
      "rangeValue": null,
      "values": [
        "1000"
      ],
      "valuesIds": null,
      "valuesLabels": null,
      "unit": null,
      "options": null
    },
    {
      "id": "234937",
      "rangeValue": null,
      "values": [
        "Sung Kim: Port"
      ],
      "valuesIds": null,
      "valuesLabels": null,
      "unit": null,
      "options": null
    },
    {
      "id": "237210",
      "rangeValue": null,
      "values": [
        "Anatolian 1000 standard"
      ],
      "valuesIds": null,
      "valuesLabels": null,
      "unit": null,
      "options": null
    },
    {
      "id": "3475",
      "rangeValue": null,
      "values": null,
      "valuesIds": [
        "3475_90"
      ],
      "valuesLabels": null,
      "unit": null,
      "options": null
    },
    {
      "id": "127812",
      "rangeValue": null,
      "values": null,
      "valuesIds": [
        "127812_1766919"
      ],
      "valuesLabels": null,
      "unit": null,
      "options": null
    },
    {
      "id": "225693",
      "rangeValue": null,
      "values": [
        "8698543131293"
      ],
      "valuesIds": null,
      "valuesLabels": null,
      "unit": null,
      "options": {
        "identifiesProduct": true
      }
    }
  ],
  "language": "pl-PL"
}`

**Comment by PrzemyslawLukanowski** [comment]
This request looks fine, I wasn't able to recreate the mentioned error. Could you send us the trace-id connected with this operation?

**Comment by MKI-Miro** [comment]
{HeaderParameter { Name = trace-id, Value = dca52d167dfb05, Type = HttpHeader, Encode = False, ContentType =  }}

**Comment by PrzemyslawLukanowski** [comment]
At the beginning of the request body, outside json, you are providing additional data which is causing this error:

`--8db11bc4-6f53-41be-b0d7-8d7e30026597 Content-Type: application/json; charset=utf-8 Content-Disposition: form-data; name="application/json" `

**Comment by MKI-Miro** [comment]
thank you I am going to investigate it because this is all my code:

`var request = new RestRequest($"sale/product-proposals");
request.AddHeader("Accept", "application/vnd.allegro.public.v1+json");
request.AddHeader("Content-Type", "application/vnd.allegro.public.v1+json");
request.AddHeader("Authorization", "Bearer " + accessToken);

request.AddParameter("Language", "pl-PL");

string jsonString = JsonSerializer.Serialize(product);
request.AddBody(jsonString);

var response = await restClient.ExecutePostAsync(request);`

**Comment by MKI-Miro** [comment]
![Capture](https://github.com/allegro/allegro-api/assets/5434248/4789f189-24f5-4d13-9335-d76d62b3020d)
This is how my request look like and i dont see the thing that you are mentioning. Really weird

**Comment by MKI-Miro** [comment]
So I have found the problem. If you are using RestSharp library in C# it adds some more stuff to request. I havent found a way to remove it.

Here is solution for .NET  without RestSharp:

`using (var client = new HttpClient())
{
    client.BaseAddress = new Uri("https://api.allegro.pl/");

    string jsonString = JsonSerializer.Serialize(product);
    var content = new StringContent(jsonString, Encoding.UTF8, "application/vnd.allegro.public.v1+json");

    content.Headers.ContentType = new MediaTypeHeaderValue("application/vnd.allegro.public.v1+json");

    client.DefaultRequestHeaders.Add("Accept", "application/vnd.allegro.public.v1+json");
    client.DefaultRequestHeaders.Add("Authorization", "Bearer " + accessToken);

    var response = await client.PostAsync("sale/product-proposals", content);
}`

Thank you for your help.
