### ISSUE TITLE
ConstraintViolationException.GallerySize for new Offer

### ISSUE THREAD

**Issue by MKI-Miro** [allegro/allegro-api#8657]
Hi

I want to attach new offer for product that already has images but I am getting ConstraintViolationException.GallerySize

`{"errors":[{"code":"ConstraintViolationException.GallerySize","message":"You have to add at least 1 image.","details":"ConstraintViolationException.GallerySize","path":"null","userMessage":"Musisz dodać przynajmniej 1 zdjęcie."}]}`

Here is request and reponse:
![image](https://github.com/allegro/allegro-api/assets/5434248/4ee6801c-a002-41e3-b659-385a68476651)

What do I wrong?

Thank you

**Comment by AureliuszBrussy** [comment]
Please send the trace-id that is in the header of our response with this error message. I will check exactly what happened.

**Comment by MKI-Miro** [comment]
{trace-id=6b7733ed9bd87942}

**Comment by AureliuszBrussy** [comment]
As far as I can see, you are sending `null` in the `images` array, which means that we do not retrieve images from the Product Catalog. We will use images from our Product Catalog if you omit this field and do not send it at all.

**Comment by MKI-Miro** [comment]
thank you, it works now.
