### ISSUE TITLE
Not found product by ID 

### ISSUE THREAD

**Issue by vladosmolovskiy** [allegro/allegro-api#8658]
Hello I'm trying to get all product details by calling https://api.{environment}/sale/products/{productId}  - I use ID from offer that is coming either through API or from product management panel. I checked that API for several products it always returns 404 error not found, I don't understand what I do wrong

**Comment by AureliuszBrussy** [comment]
Could you let me know if you are sure you are using the product id? The product id is in uuid format. If you are sure - please send the trace-id that is in the header of our response with this error message. I will check exactly what happened.

**Comment by vladosmolovskiy** [comment]
Solved, working now.
