### ISSUE TITLE
`/sale/offer-publication-commands/{commandId}` czy aby na pewno już nie metoda BETA?

### ISSUE THREAD

**Issue by Uriziel01** [allegro/allegro-api#866]
Witam,
czy mogę prosić o potwierdzenie/sprawdzenie czy metoda `[PUT] /sale/offer-publication-commands/{commandId}` została faktycznie przeniesiona z bety do zasobów publicznych? Pytam gdyż próbowałem w dniu wczorajszym używać jej z zasobu public i otrzymywałem `An error has occurred` podczas gdy wywołanie jej na końcówce BETA działa dalej bez zarzutu.

**Comment by PawelTaberski** [comment]
Przetestowałem i działa w wersji public czy na pewno przesyłasz taką wartość nagłówków:
`application/vnd.allegro.public.v1+json`
