### ISSUE TITLE
Tworzenie przesyłek i pobieranie statusu etykiety, bez WzA

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#8660]
- Nie mam umowy własnej z przewoźnikiem. 
- Utworzyłem przesyłkę za pomocą zasobu PUT parcel-management/parcel-create-commands/4956ca29-a530-8834-5f37-ae2f257d62ca
- Próbuję pobrać status etykiety wołając GET parcel-management/parcel-create-commands/4956ca29-a530-8834-5f37-ae2f257d62ca

W odpowiedzi otrzymuję:
 {"id":"4956ca29-a530-8834-5f37-ae2f257d62ca","parcelId":null,"status":"ERROR","errors":[{"code":"CREDENTIALS_ID_NOT_PROVIDED","message":"Seller didnt provide credentials for own delivery Method","details":"Seller didnt provide credentials for own delivery Method","path":"client credentials","userMessage":"Wybrana metoda dostawy nie obsługuje tego zamówienia"}]}

Trace-id: 47b5f64bf12c6bd 

Których metod powinienem użyć, jeśli chcę nadawać przesyłki Allegro Paczkomaty, a nie chcę ustawiać własnego numeru umowy?

**Comment by Lukasz-Zurek** [comment]
[Tutaj](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/wysylam-z-allegro-narzedzie-do-nadawania-przesylek-bezposrednio-z-konta-E7doGw8VgI1#z-jakich-metod-dostawy-skorzystasz-w-wysylam-z-allegro) znajdziesz zestawienie przesyłek jakie możesz nadać bez umowy, jak również z umową własną.

W tym konkretnym przypadku dla metody "Allegro Paczkomaty InPost" nie możesz przekazać usługi dostawy: 2488f7b7-5d1c-4d65-b85c-4cbcf253fd93, ponieważ wymagany jest również identyfikator umowy własnej.

Po dodaniu umowy własnej w ustawieniach zamówień, w usługach dostawy zwrócimy Tobie identyfikator, który w przypadku zasobu parcel-management otrzymuje konstrukcję: id_metody#id_umowy_wlasnej. Więcej informacji [tutaj](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#pobieranie-listy-uslug-dostawy).

**Comment by rasskabak** [comment]
Ktrórej metody dostawy powinienem w takim razie użyć, jeśli chcę nadać przesyłkę "Allegro Paczkomaty InPost", bez dodawania własnej umowy?

**Comment by Lukasz-Zurek** [comment]
@rasskabak Tego typu pytania najlepiej kierować bezpośrednio do obsługi klienta, dlatego skorzystaj proszę z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt).

**Comment by rasskabak** [comment]
Za każdym razem kiedy piszę na support cokolwiek, co ma w treści "API", to od razu przekierowują mnie tutaj... ale pewnie, mogę spróbować.

**Comment by Lukasz-Zurek** [comment]
@rasskabak Mam nadzieję, że tym razem uda Ci się uzyskać informacje. W dziale obsługi klienta mamy dedykowany zespół, który zajmuje się stricte "Wysyłam z Allegro", włącznie z metodami dostawy, umowami i rozliczeniami przesyłek. Myślę, że tu należy skupić się po prostu na samej usłudze WZA.
