### ISSUE TITLE
prices.price.amount.invalidPrecision when creating new offer

### ISSUE THREAD

**Issue by MKI-Miro** [allegro/allegro-api#8661]
Hi

When I am creating new offer for product I am getting error 

`prices.price.amount.invalidPrecision
prices[0].price.amount
Liczba miejsc po przecinku jest niepoprawna dla podanego rynku.
`

But all my prices are with 2 decimals. I dont see a problem in request. Can you please provide detailed error?

{trace-id=d74de6138dfa8135}

Thank you

**Comment by Lukasz-Zurek** [comment]
Thank you for your message. I am consulting this case with another department. Please be patient. I will be back with some more information.

**Comment by Lukasz-Zurek** [comment]
@MKI-Miro I have already received a confirmation that you can't define decimal (non-zero) value for CZK. It does mean that you should provide a value e.g. 90.00, 100.00, etc.

**Comment by MKI-Miro** [comment]
it works thank you
