### ISSUE TITLE
Brak dostępu do listy usług dostawy (Sandbox)

### ISSUE THREAD

**Issue by krzysztofpawlik** [allegro/allegro-api#8664]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Po wywołaniu GET https://api.allegro.pl.allegrosandbox.pl/shipment-management/delivery-services
otrzymuję błąd:

{"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"No access to the specified resource."}]}

Trace ID: 6ae37950eb0be8ff
Konto takemorenet

**Comment by AureliuszBrussy** [comment]
Brakuje Ci odpowiedniego scope'a: `allegro:api:shipments:write`. Więcej o scope'ach przeczytasz [w poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#lista-dostepnych-scope-ow).
