### ISSUE TITLE
Nie można dodać wiadomości do dyskusji: Kod HTML we wiadomosci

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#8665]
Błąd występuje dla każdej wartości zawierającej znak nowej linii:
VALIDATION_ERROR

Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [ X] ze środowiskiem produkcyjnym / with the production environment
 - [X ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by AureliuszBrussy** [comment]
Możesz wskazać jakiś przykładowy trace-id?

**Comment by tomasz-grzesik** [comment]
("curl -X POST -H 'Accept: application/vnd.allegro.public.v1+json' -H "
 "'Accept-Encoding: gzip, deflate' -H 'Accept-Language: pl-PL' -H "
 "'Authorization: Bearer "
 ...
 "-H 'Connection: keep-alive' -H 'Content-Length: 48' -H 'Content-Type: "
 "application/vnd.allegro.public.v1+json' -H 'User-Agent: "
 'python-requests/2.30.0\' -d \'{"text": "test\\r\\n\\r\\ntest2", "type": '
 '"REGULAR"}\' '

**Comment by tomasz-grzesik** [comment]
błąd pojawia się przy występowaniu znaku nowej linii

**Comment by shivson1337** [comment]
Błąd występuje też w interfejsie na stronie Allegro.

![image](https://github.com/allegro/allegro-api/assets/60777356/f48c608c-3c60-4ace-b7c2-755ea2a3d568)

**Comment by AureliuszBrussy** [comment]
Wycofaliśmy już tą wersję, aktualnie problem nie powinien występować.

**Comment by tomasz-grzesik** [comment]
Dzięki za szybką reakcję.
