### ISSUE TITLE
Błąd na sandboxie przy dodawaniu cennika dostaw

### ISSUE THREAD

**Issue by krzysztofpawlik** [allegro/allegro-api#8667]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Występuje błąd na sandboxie przy dodawaniu cennika dostaw:

Treść żądania:
`{
	"name": "Cennik 2",
	"rates": [
		{
			"deliveryMethod": {
				"id": "0aafb43c-e66a-46ec-9cc4-29bb39ebb483"
			},
			"maxQuantityPerPackage": 1,
			"firstItemRate": {
				"amount": "9.99",
				"currency": "PLN"
			},
			"nextItemRate": {
				"amount": "9.99",
				"currency": "PLN"
			}
		}
	]
}`

POST /sale/shipping-rates HTTP/2
Host: api.allegro.pl.allegrosandbox.pl
User-Agent: curl/7.61.1
Authorization: Bearer ...
Accept: application/vnd.allegro.public.v1+json
Content-type: application/vnd.allegro.public.v1+json
Content-Length: 50

`{"errors":[{"code":"BAD_REQUEST","message":"Message is not readable.","details":null,"path":"request.body","userMessage":"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."}]}`

Trace ID: 6a550eae15415e2c
Konto: takemorenet

**Comment by krzysztofpawlik** [comment]
Poprawiłem żądanie i obecnie mam błędy ""Wskazana metoda dostawy nie jest dostępna dla użytkownika." i "Brak metod [08c15d0b-9b24-4b3f-89a8-7a2b502abe55] wymaganych w pakiecie metod AllegroOnePunktBoxBundle".

Nie mogę znaleźć miejsca w którym można to ustawić. Być może oczekiwanie na weryfikację rachunku i danych firmy powoduje problem, jak można to przejść?

**Comment by Lukasz-Zurek** [comment]
@krzysztofpawlik Aktywowałem i zweryfikowałem już Twoje konto - tu powinno być ok.

Natomiast jeżeli chodzi o opcje dostawy - oprócz Allegro One Box, musisz wskazać również Allegro One Punkt (08c15d0b-9b24-4b3f-89a8-7a2b502abe55).
