### ISSUE TITLE
Problem z przekierowaniem do localhost

### ISSUE THREAD

**Issue by TuanDangIT** [allegro/allegro-api#8668]
Dzień dobry.

Przy poprawnym uwierzytelnieniu na stronie allegro nie przekierowywuje on już do localhost, mimo ustawienia takiej opcji w ,,URIs to redirect". Blokuje dostęp z poziomu localhosta.

[client:106742073]

Pozdrawiam.

**Comment by Lukasz-Zurek** [comment]
Niestety nie odnotowałem tego problemu w logach. Podaj proszę więcej danych, w tym również ClientId.

**Comment by TuanDangIT** [comment]
ClientID: e39e563a918540dd94cf14a9ee5fbe0e

Wpisując odpowiednio localhost do URIs Redirect nie działa. Dostęp jest zablokowany.

**Comment by Lukasz-Zurek** [comment]
@TuanDangIT Jaki dokładnie adres próbujesz wpisać i gdzie? Czy masz na myśli: http://localhost:1313/allegro ? Czy chodzi Tobie o proces autoryzacji, czy może chcesz go zmienić na stronie https://apps.developer.allegro.pl.allegrosandbox.pl ?

Z tego co widzę w Redirect URI posiadasz inny adres.

**Comment by TuanDangIT** [comment]
Próbuje po pomyślnej autoryzacji ustawić przekierowanie do swojego localhosta.

**Comment by Lukasz-Zurek** [comment]
@TuanDangIT W tej kwestii nie możemy niestety pomóc.

**Comment by TuanDangIT** [comment]
Coś takiego mi wyskakuje. Może to więcej pomoże.

**Comment by TuanDangIT** [comment]
![image](https://github.com/allegro/allegro-api/assets/128043070/4000b05d-9bdf-470e-8d0d-404e5cc90da4)

**Comment by Lukasz-Zurek** [comment]
@TuanDangIT Przekazałem tę sprawę do weryfikacji. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@TuanDangIT The problem with the ID from the print screen occurred on March 2, not March 20 and this blockade has been already solved. Please confirm these dates and if the new problem occurs - please give me a fresh data. Thank you.

**Comment by TuanDangIT** [comment]
Problem rozwiązany. Dziękuję.
