### ISSUE TITLE
Czy możliwa jest prowizja od sprzedaży 0 zł?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#8669]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

Dostaję prowizję od sprzedaży 0 zł. Czy faktycznie tu ma być 0 zł? Pobieram GET /sale/product-offers a następnie używam odpowiedzi do stworzenia POST /pricing/offer-fee-preview i otrzymuję:

```
{
  "commissions": [
    {
      "name": "Prowizja od sprzedaży",
      "type": "commissionFee",
      "fee": {
        "amount": "0.00",
        "currency": "PLN"
      }
    }
  ],
  "quotes": [
    {
      "name": "Wystawienie przedmiotu",
      "type": "listingFee",
      "fee": {
        "amount": "0.00",
        "currency": "PLN"
      },
      "cycleDuration": "PT240H"
    }
  ]
}
```

Trace-id obu operacji:
5fde87fedf9d2ea7
33104a1703b6f8b3

**Comment by Lukasz-Zurek** [comment]
@tomylee0 Dzięki za zgłoszenie. Sprawdzamy.

**Comment by Lukasz-Zurek** [comment]
@tomylee0 I już wracam z odpowiedzią - prowizja została zwrócona w wysokości 0.00 PLN ze względu na zniżkę którą posiada użytkownik - “POWITALNY_PL_I_2024”.

**Comment by tomylee0** [comment]
Dzięki za pomoc. Pozdrawiam.
