### ISSUE TITLE
PUT https://api.allegro.pl/sale/offers/$id - czy to działa? 

### ISSUE THREAD

**Issue by Rnapzsih** [allegro/allegro-api#867]
Czy ten zasób w ogóle działa? Nie mogę zaktualizować stanów...

**Comment by PawelTaberski** [comment]
Rozumiem, że chodzi tobie o metodę PUT na zasobie /sale/offers/{offerId} przetestowałem i wszystko wygląda poprawnie, a jaki respons otrzymujesz?

**Comment by Rnapzsih** [comment]
@PawelTaberski  - Nie miałem żadnego. Dziwne, z localhost poszło..... chociaż 
`  [7533673248] => {"errors":[{"code":"VALIDATION_ERROR","message":"ERR_YOU_CANT_CHANGE_ITEM","details":"","path":"","userMessage":""}]}
    [7533684829] => {"errors":[{"code":"VALIDATION_ERROR","message":"ERR_YOU_CANT_CHANGE_ITEM","details":"","path":"","userMessage":""}]}`

A po chwili przeszło....
