### ISSUE TITLE
Refresh token nie działa po 60 sekundach 

### ISSUE THREAD

**Issue by softlike-zsp** [allegro/allegro-api#8670]
Po dokonaniu autoryzacji otrzymałem parę kluczy access_token i refresh_token.  Zgodnie z dokumentacją Allegro access_token jest ważny 12 godz, aby otrzymać kolejną parę kluczy,  wystarczy użyć refresh_token. Niestety gdy to robię zgodnie z dokumentacją w języku Python https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena otrzymuję błąd 400. I nie otrzymuję parę kluczy. Co ciekawe w dokumentacji Allegro jest napisanie, że refresh_token jest ważny do następnego odświeżenia 60 sekund. I faktycznie tak jest, bo po wygenerowaniu nowej pary kluczy, gdy w ciągu 60 sekund użyję refres_token do uzyskania nowej pary kluczy to je otrzymuję, ale po 60 sekundach refresh_token jest już nieaktywny. W jaki sposób użyć refresh_token aby otrzymać nową parę kluczy ?

**Comment by Lukasz-Zurek** [comment]
Myślę, że najlepiej będzie jak prześlesz nam przykłady i po kolei opiszesz jakie dane nam przekazujesz, bo jeśli otrzymujesz błąd 400 dotyczący _Invalid refresh token_ oznacza to, że już go raz użyłeś.  Skontaktuj się z nami poprzez formularz i w zgłoszeniu dopisz GitHub[ #8670](https://github.com/allegro/allegro-api/issues/8670).

**Comment by softlike-zsp** [comment]
Rozwiązałem problem z refresh_tokenem. Można zamknąć ten wątek. Wytłumaczę dla pozostałych oraz proszę zmienić opis w dokumentacji w Allegro API "Przedłużenie ważności tokena" Chodzi o to, że po dokonaniu autoryzacji otrzymałem parę kluczy access_token i refresh_token. Okazało się, że refresh_token jest ważny przez 60 sekund i trzeba użyć funkcji "get_next_token" z dokumentacji, aby wygenerowała się ponownie para kluczy, z tym, że refresh_token będzie mieć już dłuższy termin ważności niż 60 sekund. Docelowo jest ważny 3 miesiące.  W dokumentacji nie jest o tym napisane, że po otrzymaniu pierwszej pary kluczy, trzeba ponownie ją wygenerować, po to aby refresh_token był ważny przez 3 miesiące.  
https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#python
