### ISSUE TITLE
The specified product exists

### ISSUE THREAD

**Issue by yu-www** [allegro/allegro-api#8671]
Hi,

I got the wrong response, thank you for help.

request=`{"afterSalesServices":{"impliedWarranty":{"id":"def61f53-38d4-4b8f-a779-ac5f8bbb29ea"},"returnPolicy":{"id":"9814d7df-a0f4-4c8d-9847-5b7a004dfaf3"},"warranty":{}},"delivery":{"handlingTime":"P5D","shippingRates":{"id":"64a52d41-e0fa-4168-bcff-8960b504bb08"}},"description":{"sections":[{"items":[{"content":"<p><b>Air flow meter </b><b>For TOYOTA 22204-22010 Przepływomierz Powietrza</b></p>\n\n<p><b>Replacement for the following numbers</b></p>\n\n<p><b>OEM NUMBERS:</b> TOYOTA 22204-0C020 // TOYOTA 22204-0D030 // TOYOTA 22204-0J010 // TOYOTA 22204-22010 // LEXUS 22204-0C020 // LEXUS 22204-0D030 // LEXUS 22204-0J010 // LEXUS 22204-22010</p>\n\n<p><b>APPLICATION IN VEHICLES:</b></p>\n\n<p>LEXUS LEXUS GS (_S16_) Saloon 300 (JZS160_) 2000/10 to 2004/12 219km</p>\n\n<p>LEXUS GS (_S16_) Saloon 300 (JZS160_) 1997/08 to 2000/10 222km</p>\n\n<p>LEXUS GS (_S19_) Saloon 300 (GRS190_) 2005/04 to 2011/11 249km</p>\n\n<p>LEXUS GS (_S19_) Saloon 450h (GRS191_, GWS191_) 2006/02 to 2011/11 296km</p>\n\n<p>LEXUS GS (_S19_) Saloon 450h (GRS191_, GWS191_) 2006/02 to 2011/11 345km</p>\n\n<p>LEXUS GS (_S19_) Saloon 430 (UZS190_) 2005/04 to 2011/11 283km</p>\n\n<p>LEXUS IS I (_E1_) Saloon 300 (JCE10) 2001/09 to 2005/07 213km</p>\n\n<p>LEXUS IS SportCross (_E1_) Estate 300 (JCE10_) 2001/10 to 2005/10 213km</p>\n\n<p>LEXUS LS (_F3_) Saloon 430 (UCF30) 2000/08 to 2006/08 282km</p>\n\n<p>LEXUS RX (_U3_) SUV 300 (MCU35_) 2003/05 to 2008/12 204km</p>\n\n<p>LEXUS RX (_U3_) SUV 400h (MHU38_) 2005/09 to 2008/12 211km</p>\n\n<p>LEXUS RX (_U3_) SUV 400h AWD (MHU38_) 2004/09 to 2008/12 211km</p>\n\n<p>TOYOTA TOYOTA AVENSIS VERSO (_M2_) MPV 2.0 (ACM20_) 2001/08 to 2009/11 150km</p>\n\n<p>TOYOTA AVENSIS (_T25_) Liftback 1.6 VVT-i (ZZT250_) 2003/04 to 2008/11 110km</p>\n\n<p>TOYOTA AVENSIS (_T25_) Liftback 1.8 (ZZT251_) 2003/03 to 2008/10 129km</p>\n\n<p>TOYOTA AVENSIS (_T25_) Liftback 2.0 (AZT250_) 2003/03 to 2008/11 147km</p>\n\n<p>TOYOTA AVENSIS (_T25_) Liftback 2.4 (AZT251_) 2003/10 to 2008/10 163km</p>\n\n<p>TOYOTA AVENSIS (_T25_) Liftback 2.4 (AZT251_) 2003/09 to 2008/11 170km</p>\n\n<p>TOYOTA AVENSIS Saloon (_T25_) Saloon 1.6 VVT-i (ZZT250_) 2003/04 to 2008/11 110km</p>\n\n<p>TOYOTA AVENSIS Saloon (_T25_) Saloon 1.8 (ZZT251_) 2003/04 to 2008/11 129HP</p>\n\n<p>TOYOTA AVENSIS Saloon (_T25_) Saloon 2.0 (AZT250_) 2003/04 to 2008/11 147km</p>\n\n<p>TOYOTA AVENSIS Saloon (_T25_) Saloon 2.4 (AZT251_) 2003/10 to 2008/10 163km</p>\n\n<p>TOYOTA AVENSIS Saloon (_T25_) Saloon 2.4 (AZT251_) 2003/09 to 2008/11 170km</p>\n\n<p>TOYOTA AVENSIS Estate (_T25_) Estate 1.6 VVT-i (ZZT250_) 2003/04 to 2008/11 110km</p>\n\n<p>TOYOTA AVENSIS Estate (_T25_) Estate 1.8 (ZZT251_) 2003/04 to 2008/11 129km</p>\n\n<p>TOYOTA AVENSIS Estate (_T25_) Estate 2.0 (AZT250_) 2003/04 to 2008/11 147km</p>\n\n<p>TOYOTA AVENSIS Estate (_T25_) Estate 2.0 VVTi (AZT250_) 2003/04 to 2008/11 155km</p>\n\n<p>TOYOTA AVENSIS Estate (_T25_) Estate 2.4 (AZT251_) 2003/10 to 2008/10 163km</p>\n\n<p>TOYOTA AVENSIS Estate (_T25_) Estate 2.4 (AZT251_) 2003/09 to 2008/11 170km</p>\n\n<p>TOYOTA CAMRY Saloon (_V3_) Saloon 3.0 (MCV30_) 2001/08 to 2006/11 186km</p>\n\n<p>TOYOTA CELICA Coupe (_T23_) Coupe 1.8 16V VT-i (ZZT230_) 1999/08 to 2005/07 143km</p>\n\n<p>TOYOTA CELICA Coupe (_T23_) Coupe 1.8 16V TS (ZZT231_) 1999/08 to 2005/09 192km</p>\n\n<p>TOYOTA COROLLA (_E12_) Liftback 1.4 VVT-i (ZZE120_) 2001/11 to 2007/02 97km</p>\n\n<p>TOYOTA COROLLA (_E12_) Liftback 1.6 VVT-i (ZZE121_) 2002/01 to 2006/12 110km</p>\n\n<p>TOYOTA COROLLA (_E12_) Liftback 1.8 VVTL-i TS (ZZE123) 2001/11 to 2007/02 192km</p>\n\n<p>TOYOTA COROLLA (_E12_) Liftback 1.8 VVTL-i TS (ZZE123_) 2005/10 to 2006/12 218km</p>\n\n<p>TOYOTA COROLLA (_E12_) Liftback 1.8 VVTL-i TS (ZZE123_) 2005/02 to 2007/02 224km</p>\n\n<p>TOYOTA COROLLA Saloon (_E12_) Saloon 1.4 VVT-i (ZZE120_) 2001/10 to 2006/10 97km</p>\n\n<p>TOYOTA COROLLA Saloon (_E12_) Saloon 1.6 VVT-i (ZZE121_) 2001/10 to 2008/03 110km</p>\n\n<p>TOYOTA COROLLA Estate (_E12_) Estate 1.4 VVT-i (ZZE120_) 2002/01 to 2007/02 97km</p>\n\n<p>TOYOTA COROLLA Estate (_E12_) Estate 1.6 VVT-i (ZZE121_) 2002/01 to 2007/08 110km</p>\n\n<p>TOYOTA COROLLA Verso (_E12_) MPV 1.6 VVT-i (ZZE121_) 2001/08 to 2004/05 110km</p>\n\n<p>TOYOTA COROLLA Verso (_E12_) MPV 1.8 VVT-i (ZZE122_) 2001/12 to 2004/05 135km</p>\n\n<p>TOYOTA COROLLA Verso (ZER_, ZZE12_, R1_) MPV 1.6 (ZNR10_) 2004/04 to 2009/03 110km</p>\n\n<p>TOYOTA COROLLA Verso (ZER_, ZZE12_, R1_) MPV 1.8 (ZNR11_) 2004/04 to 2009/03 129km</p>\n\n<p>TOYOTA LAND CRUISER PRADO (_J12_) Closed Off-Road Vehicle 4.0 (GRJ120, GRJ125) 2002/12 to 2010/12 249km</p>\n\n<p>TOYOTA MR 2 III (ZZW3_) Convertible 1.8 16V VT-i (ZZW30) 1999/10 to 2007/06 140km</p>\n\n<p>TOYOTA PREVIA (_R3_) MPV 2.4 (ACR30) 2000/02 to 2006/02 156km</p>\n\n<p>TOYOTA PRIUS Liftback (_W2_) Liftback 1.5 Hybrid (NHW20_) 2003/09 to 2009/12 78km</p>\n\n<p>TOYOTA RAV 4 II (_A2_) SUV 1.8 (ZCA25_, ZCA26_) 2000/08 to 2005/11 125km</p>\n\n<p>TOYOTA RAV 4 II (_A2_) SUV 2.0 4WD (ACA21, ACA20) 2000/05 to 2005/11 150km</p>\n\n<p>TOYOTA YARIS (_P1_) Liftback 1.0 (SCP10_) 2003/03 to 2005/09 65km</p>\n\n<p>TOYOTA YARIS (_P1_) Liftback 1.0 (SCP10_) 1999/04 to 2005/09 68km</p>\n\n<p>TOYOTA YARIS (_P1_) Liftback 1.3 (NCP10_, SCP12_) 1999/11 to 2005/10 86km</p>\n\n<p>TOYOTA YARIS (_P1_) Liftback 1.3 (SCP12_, NCP10_, SCP13_) 2002/04 to 2005/09 87km</p>\n\n<p>TOYOTA YARIS (_P1_) Liftback 1.5 (NCP13_) 2003/01 to 2005/11 105km</p>\n\n<p>TOYOTA YARIS (_P1_) Liftback 1.5 (NCP13_) 2001/04 to 2005/09 106km</p>\n\n<p>TOYOTA YARIS VERSO (_P2_) MPV 1.3 (NCP20_, NCP22_) 2002/11 to 2005/09 84km</p>\n\n<p>TOYOTA YARIS VERSO (_P2_) MPV 1.3 (NCP20_, NCP22_) 1999/08 to 2002/10 86km</p>\n\n<p>TOYOTA YARIS VERSO (_P2_) MPV 1.5 (NCP21_) 2000/03 to 2005/09 105km</p>\n\n<p>TOYOTA YARIS VERSO (_P2_) MPV 1.5 (NCP21_) 2000/03 to 2005/09 106km</p>\n\n<p>TOYOTA YARIS (_P9_) Liftback 1.3 VVT-i (SCP90_) 2005/08 to 2010/11 87km</p>\n","type":"TEXT"},{"type":"IMAGE","url":"https://a.allegroimg.com/original/11e382/6588aacd4559bec105e43f30d054"}]}]},"external":{"id":"YT000476-A"},"images":["https://a.allegroimg.com/original/11992c/04fc444646098aaf55220184760b"],"location":{"city":"weifang","countryCode":"CN","postCode":"261000","province":"małopolskie"},"name":"For TOYOTA 22204-22010 Przepływomierz Powietrza","parameters":[{"id":"11323","valuesIds":["11323_1"]},{"id":"229205","valuesIds":["229205_340245"]}],"payments":{"invoice":"NO_INVOICE"},"productSet":[{"product":{"category":{"id":"256142"},"images":["https://a.allegroimg.com/original/11dea0/08db9b6745b2aefa944b1b7910aa","https://a.allegroimg.com/original/1127a7/c3204aa24939af52904f69876df3","https://a.allegroimg.com/original/114d7f/8acac0734ba7a024d7d39f7fbd60","https://a.allegroimg.com/original/11aae7/907f0ad3416caa64335d8cc6e21e","https://a.allegroimg.com/original/11b487/82e86d0f42e9927a13b49820fb83","https://a.allegroimg.com/original/11992c/04fc444646098aaf55220184760b","https://a.allegroimg.com/original/111012/cdfeddbe4c6382c8c9e0561b9c3f"],"name":"For TOYOTA 22204-22010 Przepływomierz Powietrza","parameters":[{"id":"129591","valuesIds":["129591_1"]},{"id":"127415","values":["YT-TEK"],"valuesIds":["127415_22"]},{"id":"215858","values":["22204-22010"]},{"id":"214434","valuesIds":["214434_266990"]},{"id":"215941","values":["22204-22010"]},{"id":"227345","values":["22204-22010"]}]}}],"sellingMode":{"price":{"amount":"82.99","currency":"PLN"}},"stock":{"available":10,"unit":"UNIT"},"taxSettings":{"rates":[{"countryCode":"CZ","rate":"21.00"},{"countryCode":"SK","rate":"20.00"},{"countryCode":"PL","rate":"23.00"}],"subject":"GOODS"}}`

response=`{"errors":[{"code":"PARAMETER_MISMATCH","message":"The provided parameter 'Producent części'(127415) value (Inny(127415_22)) does not match the existing parameter value (3F Quality(127411_338509))","details":null,"path":"productSet[0].product.parameters","userMessage":"The specified product exists. The specified parameter `Producent części` with the value `Inny(127415_22)` does not match the product parameter `3F Quality(127411_338509)`."},{"code":"PARAMETER_MISMATCH","message":"The provided parameter 'Numer katalogowy części'(215858) value (22204-22010) does not match the existing parameter value (9040251999037)","details":null,"path":"productSet[0].product.parameters","userMessage":"The specified product exists. The specified parameter `Numer katalogowy części` with the value `22204-22010` does not match the product parameter `9040251999037`."}]}`

**Comment by Lukasz-Zurek** [comment]
We identified a product 5b989654-bed2-4319-b404-c7d6fcc79443 based on the parameters which you have provided in your request.  But as it is not clear enough - I am consulting this case with another department. I will be back with some more details.

**Comment by yu-www** [comment]
> We identified a product 5b989654-bed2-4319-b404-c7d6fcc79443 based on the parameters which you have provided in your request. But as it is not clear enough - I am consulting this case with another department. I will be back with some more details.


Hi, may I ask if there is any update on this issue？
Thank you for help.

**Comment by Lukasz-Zurek** [comment]
@yu-www Please be patient. I will let you know as soon as possible.

**Comment by M4GiK** [comment]
Podpinamy się pod temat, mamy podobny problem.

2024-03-25 12:12:12,906 ERROR {"errors":[{"code":"PARAMETER_MISMATCH","message":"The provided parameter 'Kod producenta'(224017) value (10964) does not match the existing parameter value (5902365219170)","details":null,"path":"productSet[0].product.parameters","userMessage":"The specified product exists. The specified parameter `Kod producenta` with the value `10964` does not match the product parameter `5902365219170`."}]} - URG-716_SPODNIE_62

**Comment by MartaNowaczyk** [comment]
@M4GiK podaj proszę trace-id do weryfikacji

**Comment by Lukasz-Zurek** [comment]
@yu-www In your specific case, we identified a product from our product catalog, based on the:

- image/photo - which was identical, 
- parameter 129591 (Car type): 129591_1. 

This is why we have returned an error - our system compared other parameters that were not compatible with the product.
