### ISSUE TITLE
Tworzenie paczki Allegro Kurier DHL Czechy pobranie - Cyrylica

### ISSUE THREAD

**Issue by MILsoldier** [allegro/allegro-api#8676]
Witam, 
przy tworzeniu przesyłki przy pomocy metody /parcel-management/parcel-create-commands/{commandId} na DHL Czechy, przy podaniu ulicy : VERONSKÉ NÁMĚSTÍ dostaję błąd: 
errors":[{"code":"VALIDATION_ERROR","message":"Cyrillic should not be used","details":null,"path":"receiver.name","userMessage":"Nie należy używać cyrylicy"}]
Dane z zamówienia pobrane są przy pomocy metody /order/checkout-forms/
Proszę o pomoc.

**Comment by AureliuszBrussy** [comment]
Czy mógłbyś przesłać commandId komendy, gdzie wystąpił ten problem? Sprawdzimy to.

**Comment by MILsoldier** [comment]
"id":"3b32a811-e313-44ae-92fa-7616831686c7"

**Comment by AureliuszBrussy** [comment]
Dziękuję. Wyjaśniam to. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Problem sprawa wartość w polu, który zwróciliśmy w `"path"`, czyli `"receiver.name"`. W pierwszym członie znajduje się jeden znak pochodzący właśnie z cyrylicy - jest do drugi znak z ciągu. Wystarczy, że zmienisz go na `"I"`.

**Comment by MILsoldier** [comment]
Dziękuję za pomoc.
