### ISSUE TITLE
Rest API error with email

### ISSUE THREAD

**Issue by HerVoj1985** [allegro/allegro-api#8677]
Hello,
I'm sending requests to the allegro api. The /shipment-management/shipments/create-commands request is OK and I get the commandId back. The next request to obtain the shipmentId already ends with the error that the email is not valid. Is there any limitation in the recipient, what kind of email must be there?

Request
GET https://api.allegro.pl.allegrosandbox.pl/shipment-management/shipments/create-commands/b2ac68a7-92b5-4428-93e1-06cd0dcf62dc HTTP/1.1
Content-Type: application/vnd.allegro.public.v1+json
Accept: application/vnd.allegro.public.v1+json
Authorization: Bearer XXX
Host: api.allegro.pl.allegrosandbox.pl

Response
{
  "commandId": "b2ac68a7-92b5-4428-93e1-06cd0dcf62dc",
  "status": "ERROR",
  "errors": [
    {
      "code": "VALIDATION_ERROR",
      "message": "Incorrect format of Allegro email",
      "details": "Invalid value: allegro@hobynaradi.cz",
      "path": "resolveHash.email",
      "userMessage": "Allegro mail jest w niepoprawnym formacie"
    }
  ],
  "shipmentId": null
}

Thank you.

**Comment by AureliuszBrussy** [comment]
You should generate some test order. Simply list an offer from one account and make a purchase on that offer from another account. The order will include an email address that will allow you to create a shipment.

**Comment by AureliuszBrussy** [comment]
There is a payment simulator on Sandbox - you do not have to provide real data.

**Comment by HerVoj1985** [comment]
I created a purchase https://allegro.pl.allegrosandbox.pl/moje-allegro/zakupy/kupione/6c6bf037-54a9-3e02-b429-4bcc89bb4097, but I don't see the email anywhere. Just a phone. I am looking at the purchase detail.
![email](https://github.com/allegro/allegro-api/assets/161469249/e6915bcf-dc02-4447-ba68-3337ff653259)

**Comment by AureliuszBrussy** [comment]
You can see the e-mail address on the merchant side ([Orders tab](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/zamowienia)).

**Comment by HerVoj1985** [comment]
I don't see anywhere in the sandbox where I can create a purchase. Nor where could I find the section My assortment etc. (we have an account from the client podpora@hobynaradi.cz). Can't they have it banned or something? Can you please send me the exact section where I can see, for example, the New offer button or something similar?

I only see this in the menu:
![image](https://github.com/allegro/allegro-api/assets/161469249/150bff30-8b03-432c-ae44-5b9fc9e2380e)

**Comment by AureliuszBrussy** [comment]
You can create a new offer via form: https://allegro.cz.allegrosandbox.pl/offer/.

**Comment by HerVoj1985** [comment]
Hmmm, i tried, but:
![image](https://github.com/allegro/allegro-api/assets/161469249/e6638d5f-3ed3-4968-9d8d-0ec5c1c8ef0c)

**Comment by AureliuszBrussy** [comment]
Please, use correct marketplace Sandbox (allegro.cz), use link: https://allegro.cz.allegrosandbox.pl/offer/

**Comment by HerVoj1985** [comment]
Thank you.
