### ISSUE TITLE
How can i do the Client_credentials flow Authentication and authorization in Allegro SANDBOX

### ISSUE THREAD

**Issue by andreinacuellor** [allegro/allegro-api#8679]
Hi!

I am trying to test the REST API Allegro in Sandbox using the Client_credentials flow Authentication and authorization. But I am getting t

{
    "error": "Unauthorized",
    "error_description": "Unauthorized"
}

This is the curl:

curl --location --request POST 'https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials' \
--header 'Authorization: MWEyOTBiMDdjODkzNDJjMGIyMjIwNWFkODg2NjdmNDQ6Y3FjSUdBU2dPYTh1NU1oSjEzbEh5UmFUSkY0aHpTMVN4MXJJVWdXdThabTc5V2RQbzR4V1A4V2V1V2hHZzZWTg==' \
--header 'Cookie: datadome=6vwgteqmNmYiaOhjGx_zxnZrSHMg4IJqC_oMK1gVgcK6D8CRg2m9V9Ra3LwXnQoL8q1g8L5l1Nyb1bE_XH8tHTamDdv71QaWc0XxCYMdItqD~nJsm3MhjHrxoM3iohN_; _cmuid=4304892a-d6ff-4c26-b8d1-b0f23f28a77e; wdctx=v4.jkNmHuPkHIr5xGDkJFDtupAnRK7Rxw1xQICaGbPz6_-0n0czxWF80VjuV3v4ZQMAlPFAIdylUdJVy5upMDuHLsZxcNB5vBQ_1PG6UtupqPIxY6TxeotORatontB4qzRwIUJ_r35GxkFaqJJP3-yKjcC1nKfZKj0ZsCQH8cPPw8m_RSpERR0IjQ9WWI0no5XBHx_FYY4c292EY8LFODIdMZpDJfkPK6kLRyzf6KHfdaw4bj0xtzJFCfvRjA'

I created an app from here: https://apps.developer.allegro.pl.allegrosandbox.pl/ to get the client and secrete Id
then i add the header Authorization with the "client_id:client_secret" Base64 enconded. 

what i am doing wrong?

**Comment by AureliuszBrussy** [comment]
Authorization header should look like this: `'Authorization: Basic base64(clientId:secret)'`, so you are missing `Basic` within this string.
