### ISSUE TITLE
Czy WebAPI wogóle działa?

### ISSUE THREAD

**Issue by juhacz** [allegro/allegro-api#868]
Czy WebAPI działa, bo mam wrażenie, że od 17:52 nie działa.

**Comment by kuli-g** [comment]
Webapi u mnie działa, i nie stwierdziłem żadnych problemów wieczorem, w restapi nie pobiera nowego tokenu ale z niego nie korzystam póki co... z tego co widzę na fejsie to niektórzy dostają błąd 404 jak wchodzą na główną stronę allegro.

**Comment by juhacz** [comment]
U mnie tylko tyle, w każdym skrypcie
PHP Fatal error:  Uncaught SoapFault exception: [HTTP] Could not connect to host in

**Comment by juhacz** [comment]
Moim zdaniem jednak nie działa .....

**Comment by kuli-g** [comment]
przed chwilą dosłownie pobierałem zamówienia przez webapi, normalnie weszły. Awaria wysoce losowa, ciężko stwierdzić czemu jednym działa innym nie, może allegro ma problem z jakimś łączem

**Comment by juhacz** [comment]
to jednak problem z moim hostingiem :(

**Comment by kuli-g** [comment]
oj może wcale nie, przez moje łącze działa normalnie, a jak próbuję się wbić przez nordVPN nawet z serwera w Polsce to allegro nie ma. Poczekaj, może niedługo naprawią, połowa polski nie ma dostępu do allegro

**Comment by juhacz** [comment]
To była wina mojego hostingu i dnsów.
