### ISSUE TITLE
403 Forbidden response trying to Authenticate with Authentication Flow to Allegro API

### ISSUE THREAD

**Issue by andreinacuellor** [allegro/allegro-api#8681]
Hi!

I am trying to test the REST API Allegro in Sandbox using Authorization Code flow Authentication and authorization. But I am getting 403 Forbidden response

This is the curl:

curl --location --request POST 'https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxx&redirect_uri=https%3A%2F%2Ftest.salesforce.com%2F' \
--header 'Cookie: datadome=3PoF9j9qtHc_t~t1CYRV4923bilGfnh0cu4RWnVQB_Jz4Bshs4WSw4J4kwvEMi1hH_pFME8zLxqzWYKUaKnKAXUq8LdgacEu79lOCAkDNHhg2B43FsKJO6lLO8zPu6hG; TEST_QXLSESSID=b8e5978896a2f0a28650889100cea17ac09461e20bcc68//00; _cmuid=4304892a-d6ff-4c26-b8d1-b0f23f28a77e; wdctx=v4.p8JGIYsvQBPqHU5BwRTjptRha6lwy-rl-7nsVkqHNGcsQeFiRR8QYL66aDgMH_a-vqNrZrT8ppFZOEa79H_9uKrQlG1wQIn1TjfQttK48rjS5Vcj8WC92ZW-XkEt0VahpWradbzWRAaY36g61qSBIB5ovLHuMw_Hq2WVDa7S3MJOwBzDcx1baPKokW_om07GXnwU11KMgX8LF8dBvsbtjoxW8J_bynorPlI5ngJ8Mhpmaw7Ed033ZYJiKg'

I created an app from here: https://apps.developer.allegro.pl.allegrosandbox.pl/ to get the client and secret Id

what I am doing wrong?

**Comment by Lukasz-Zurek** [comment]
You should not use POST while calling this request, it is incorrect. You should use a properly parameterized HTTP request - as above - that allows user authentication. Use it directly in your browser. We will return a code in the url of the redirect-url.

Then please follow the [next steps of authentication and authorization](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#user-authorization).
