### ISSUE TITLE
Zablokowana sprzedaż - sandbox 

### ISSUE THREAD

**Issue by karolszabatis** [allegro/allegro-api#8684]
Chciałbym odblokować sprzedaż na swoim koncie na sandboxie. 
Proszę o informację jak to mogę zrobic.
Konto: sandbox_innrosa

Zablokowana sprzedaż
Sprzedaż na Twoim koncie jest obecnie zablokowana. Powodem mogą być nieopłacone rachunki lub inne naruszenia Regulaminu. Aby odblokować możliwość sprzedaży, ureguluj zaległe płatności lub[ skontaktuj się z nami]

**Comment by Lukasz-Zurek** [comment]
Nie mamy wskazanego loginu w naszej bazie Allegro Sandbox. Podaj proszę prawidłowy.

**Comment by Lukasz-Zurek** [comment]
@karolszabatis Ok, odblokowałem konto :)
