### ISSUE TITLE
Brak możliwości ustawienia SameDay w Sandbox

### ISSUE THREAD

**Issue by relains** [allegro/allegro-api#8697]
Dzień dobry,

Czy możecie mi dla konta olmed-sandbox w środowisku testowym aktywować kuriera Allegro One dostawa dzisiaj? W tej chwili zauważyłem, że przy tym kurierze w cennikach dostawy jest taka informacja, ale ona raczej dotyczy środowiska produkcyjnego.

![image](https://github.com/allegro/allegro-api/assets/19413434/6d8fb2ba-60cd-441a-8411-3b086cff997a)

P.S.
Na zrzucie ekranu w adresie e-mail brakuje suffix-u dla domeny, na środowisku produkcyjnym też.

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Na Sandboxie możesz włączyć tą metodę dostawy w cenniku (ignorując informacje o konieczności kontaktu, możesz zapisać cennik z takim ustawieniem) i to wystarczy, aby w Twojej ofercie pojawiła się możliwość zamówienia z dostawą tego samego dnia. Aktualnie nie ograniczamy tego tak jak na produkcji. 

Dzięki za zwrócenie uwagi na suffix - pracujemy nad poprawką.

**Comment by relains** [comment]
No dobra, faktycznie udało się uzyskać wyświetlanie SameDay na sandbox. Ale teraz mam kolejne pytanie na przykładzie zamówienia: b92b7c32-7b48-3858-8004-f8b6821dcfe5

![image](https://github.com/allegro/allegro-api/assets/19413434/7a85a5a6-2cbf-44d3-aef0-d4326ebd8604)

Widać, że klientowi faktycznie pokazał się SameDay, ale w request daty $delivery['dispatch']['time']['from'] oraz $delivery['dispatch']['time']['to'] są na poniedziałek 25.03.2024r:

![image](https://github.com/allegro/allegro-api/assets/19413434/f1469aac-d3a1-4e63-8016-920a150ace79)

**Comment by AureliuszBrussy** [comment]
Sprawdzamy to. Wrócę z informacją.

**Comment by relains** [comment]
Czy coś już wiadomo?

**Comment by MartaNowaczyk** [comment]
Prezentowany czas wysyłki dla kupującego nie opiera się jedynie na deklaracji sprzedającego, lecz wynika z jego historycznego zachowania i ustawionych deklaracji czasu wysyłki. Jeśli chodzi o dispatch, to tam jest po prostu deklarowany czas wysyłki i stąd mogą być tu rozbieżności.

**Comment by relains** [comment]
Czy zatem my jesteśmy jakoś w stanie przez API pobrać tą informację do kiedy klientowi się wyświetla, że otrzyma przesyłkę?

**Comment by MartaNowaczyk** [comment]
Niestety, nie.
