### ISSUE TITLE
Integration Between Salesforce and Allegro

### ISSUE THREAD

**Issue by andreinacuellor** [allegro/allegro-api#8698]
Hi,

I am trying to Integrate Salesforce with Allegro.
What we want is every time a customer buys or tries to contact our seller account in Allegro whether by Allegro Message Center or by Disputes, we will be able to get those messages into Salesforce and also we send replies from Salesforce to Allegro. 

I found out that there are several resources we can use but its authorizations are type "bearer-token-for-user". As you know, this type only allows security scheme type authorizationCode OAuth Flow and x-deviceCode OAuth Flow. But we would need something more serve-to-server authentication. 

Can you tell me if it is possible or if I could use authorizationCode OAuth Flow and In some way don't need the user's consent to its operation?

**Comment by AureliuszBrussy** [comment]
We only use OAuth 2.0 for the authentication and authorization process. It is not possible to bypass user-consent and at least once the user must agree to act on their behalf. After that, you can refresh the access token using the refresh token.

**Comment by andreinacuellor** [comment]
ah ok so I can do the user-consent once and then I can continue using the refresh token?

**Comment by AureliuszBrussy** [comment]
Exactly. However, you must bear in mind that in some cases tokens may be revoked (e.g., password change on a user account).

**Comment by andreinacuellor** [comment]
Ok thank you!
