### ISSUE TITLE
Brak przesyłek do zamówienia

### ISSUE THREAD

**Issue by MateuszsuetaM** [allegro/allegro-api#8699]
Dzień dobry :)

Przy pobieraniu przesyłek dla jednego z zamówień otrzymuję pusty zasób "shipments" mimo że zamówienie ma przypisaną w allegro.pl przesyłkę i jest już w drodze.

![image](https://github.com/allegro/allegro-api/assets/19281300/a092a938-d574-4e83-8e51-06b033a7d2e0)

https://api.allegro.pl/order/checkout-forms/{OrderId}/shipments

Trace-id zapytania:
cd029458ad2c3803

**Comment by AureliuszBrussy** [comment]
Nie widzę takiej przypisanej przesyłki w tym zamówieniu, tym bardziej, że zamówienie nie jest w statusie READY_FOR_PROCESSING. Jeżeli gdzieś pojawia się informacja o numerze przesyłki - prosiłbym, aby sprzedający wyjaśnił to za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt). Z punktu widzenia publicznego API wszystko jest ok.

**Comment by MateuszsuetaM** [comment]
Rzeczywiście, mój błąd - klient zamówił dwa razy. 
Przepraszam za zamieszanie i pozdrawiam :)
