### ISSUE TITLE
Problem z metodą doGetSellFormFieldsForCategory

### ISSUE THREAD

**Issue by smok55453** [allegro/allegro-api#87]
Witam.
Mam pewien problem z metodą doGetSellFormFieldsForCategory.
Wywołuję tę metodę dla countryId = 1 oraz categoryId = 89266. Otrzymuję komunikat: 
SoapFault exception: [Client] looks like we got no XML document in /home/.../Allegro.php:841
Dla niektórych kategorii działa to poprawnie i pobiera mi wszystkie pola, a dla innych dostaję ten komunikat. Wykonuję integrację w języku PHP oraz używam sandboxa.
Ktoś wie w czym może być problem?

**Comment by PawelTaberski** [comment]
Na allegro brak kategorii o wskazanym przez Ciebie id, dlatego dostajesz błąd. Drzewo dostępnych  kategorii pobierzesz przy pomocy metody: [doGetCatsData](https://allegro.pl/webapi/documentation.php/show/id,46)

**Comment by smok55453** [comment]
Dokładnie przy pomocy tej metody pobrałem wszystkie kategorie jakąś godzinę temu. I ta kategoria tam jest. Jeżeli pobrałem przy pomocy doGetCatsData tą kategorię to widocznie musi ona istnieć.

P.S Cały czas działam na sandbox allegro.

**Comment by PawelTaberski** [comment]
Sprawdziłem na środowisku testowym i rzeczywiście w przypadku tej kategorii występuje jakiś problem. Sprawę przekazałem do odpowiedniego zespołu.

**Comment by smok55453** [comment]
Ok, dziękuję za poświęcony czas, jeżeli będzie coś wiadomo, to proszę o informację,

**Comment by PawelTaberski** [comment]
Oczywiście, jednocześnie chciałbym poinformować, że niedługo wdrożymy nowe środowisko testowe.
