### ISSUE TITLE
Komunikacja z API

### ISSUE THREAD

**Issue by xemix** [allegro/allegro-api#870]
Cześć, działa Wam poprawnie komunikacja z API? Z każdej metody otrzymuję 'Could not connect to host'.

**Comment by bartoszkurek** [comment]
Od 17:30 nie miałem kontaktu z REST API, jakieś 5 minut temu wszystko zaczęło działać, sprawdź teraz.

**Comment by xemix** [comment]
Dzięki, faktycznie wszystko zaczyna działać...

**Comment by magik092** [comment]
Potwierdzam, była jakaś luka w działaniu API. Na ten moment wszystko wydaje się działać prawidłowo.

Przepraszam że tutaj ale nie chcę zakładać osobnego Issue. Allegro - mam prośbę - mam stare konto na (id=43948416) sandbox jednak nijak nie dam rady go aktywować (info o koniecznej aktywacji po zalogowaniu na sandbox), moglibyście mi je aktywować? :) Z góry dzięki!

**Comment by PawelTaberski** [comment]
@magik092 Wstępnie aktywowałem Twoje konto, ale aby je w pełni aktywować musisz wystartować ścieżkę aktywacji konta firma przez moje allegro, prześlij jakieś dowolne pliki.

**Comment by magik092** [comment]
Gotowe! Dzięki wielkie :)
