### ISSUE TITLE
API locked-out after normal usage

### ISSUE THREAD

**Issue by z4nr34l** [allegro/allegro-api#8704]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [X] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X] inny / other

:beetle: **Opis / Description**

We got locked-out in our offices for normal usage of Allegro API, we sent ticket to support via Allegro Panel, contacted our Allegro VIP supervisor and we can't gat a solution for 2 days. Today we got info to post that problem there.

Ticket ID: `40926927`

**Comment by Lukasz-Zurek** [comment]
I do not have access to this type of correspondence. But If you do have a contact with your VIP, please continue the correspondence directly with him.

**Comment by z4nr34l** [comment]
> I do not have access to this type of correspondence. But If you do have a contact with your VIP, please continue the correspondence directly with him.

He told us to contact with you...

**Comment by Lukasz-Zurek** [comment]
@z4nr34l Ok, I understand. If the problem refers strictly to our public API then please precise it here. I will try to help you.

**Comment by z4nr34l** [comment]
We had sent our IP address via Allegro Panel support form - case id: `40926927`.
We can't even connect to any endpoint, for example: `https://api.allegro.pl/sale/offers`.

We get ECONNRESET on every try, but when we route our traffic via external sites (with other Public IP), we can comunicate with API again for around one day before we are getting locked.

**Comment by Lukasz-Zurek** [comment]
@z4nr34l Ok, thank you for a clarification. As far as I know - this case refers to the other problem, which is out of our hands. You did not provide IP address in the message, but maybe you have provided it to your supervisor. Please provide all details in this case: `40926927` and continue to contact your supervisor. We cannot help you here and we cannot push this case forward.

**Comment by z4nr34l** [comment]
We filled missing IP addresses in support case now. We will contact supervisor.

**Comment by z4nr34l** [comment]
Our supervisor returned us again here. We also sent second case to ensure this time you got IP addresses.

Case IDS: `40926927` `40942515`

**Comment by Lukasz-Zurek** [comment]
@z4nr34l Ok, but he has forwarded this case to GitHub incorrectly. We cannot help you. But as far as I know, your supervisor has already forwarded this case to another department so the case is in progress.
