### ISSUE TITLE
Aktywacja Smart na koncie sprzedającego

### ISSUE THREAD

**Issue by relains** [allegro/allegro-api#8706]
Dzień dobry,

Proszę o włączenie Allegro Smart dla konta sprzedającego olmed-sandbox.

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Oznaczenie Smart uzyskasz po spełnieniu [standardowych wymagań](https://allegro.pl/pomoc/dla-sprzedajacych/informacje-dla-sprzedajacych/co-zrobic-aby-moje-oferty-byly-oznaczone-ikona-allegro-smart-lDkP8VbKncV) dla usługi, także na Sandboxie. Nie mamy możliwości manualnego włączenia.

**Comment by relains** [comment]
Muszę mieć minimum 50 zamówień na Sandbox żeby mieć Smart-a? Dlaczego nie mogę np. wejść w zakładkę skuteczność wysyłki? Jak mam w takim razie sprawdzić jakich kryteriów mi brakuje?

**Comment by AureliuszBrussy** [comment]
Nie, nie musisz mieć 50 zamówień. 

Wystarczy, że spełnisz jeden z warunków dot sprzedaży:
- poziom [jakości sprzedaży](https://allegro.pl/pomoc/dla-sprzedajacych/jakosc-mojej-sprzedazy/czym-jest-i-w-czym-pomoze-mi-panel-jakosc-mojej-sprzedazy-AVP4PwzBoCL) na Twoim koncie jest wyższy niż Neutralny lub co najmniej Neutralny na wszystkich Twoich kontach lub
- masz co najmniej 5 unikalnych pozytywnych ocen transakcji (łapek w górę) w ciągu ostatnich 12 miesięcy oraz masz średnią ocen sprzedaży na poziomie co najmniej 98% lub
- masz tytuł [Super Sprzedawcy](https://allegro.pl/pomoc/dla-sprzedajacych/jakosc-mojej-sprzedazy/czym-jest-program-super-sprzedawca-7wOB6zjX6U4).

Najłatwiej będzie spełnić warunek nr 2 dokonując zakupów z 5 różnych kont i wystawiając 5 ocen pozytywnych. 

Poza tym pozostaje kwestia spełnienie warunków dot. oferty, czyli ustawienie warunków zwrotów oraz udostępnienie odpowiednich metod dostawy.

**Comment by relains** [comment]
No niestety, ale nadal jest coś nie tak.

Na koncie olmed-sandbox mam 5 ocen pozytywnych od 5 różnych kupujących:
![image](https://github.com/allegro/allegro-api/assets/19413434/0b6ed2cf-47e2-448b-8497-5b5ae77ded41)

Cennik domyślny spełnia wymagania smart:
![image](https://github.com/allegro/allegro-api/assets/19413434/d1c55930-2be9-4b17-ac4c-7f396a575338)

W ofercie wybrany jest ten cennik:
![image](https://github.com/allegro/allegro-api/assets/19413434/6951fa87-74d0-48c9-97d9-1867be151c8f)

Mimo, że klient Client:94627242 ma wykupionego smarta to znaczka smart nie ma przy ofercie:
![image](https://github.com/allegro/allegro-api/assets/19413434/17a8cb1c-9162-40af-bf46-0936ef7d1c7c)

**Comment by MartaNowaczyk** [comment]
Dzięki za zrzuty, postaram się to zweryfikować i wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Przepraszam, że musiałeś trochę poczekać, ale mimo, tego co pokazałeś na zrzucie nie mieliśmy w systemie 5 unikalnych ocen, aby tego tak nie zostawić dodaliśmy do Twojego konta oznaczenie smart.
