### ISSUE TITLE
W opisie swojej oferty umieszczasz zdjęcia

### ISSUE THREAD

**Issue by MKI-Miro** [allegro/allegro-api#8707]
Hi

I am getting this error when i am trying to create new offer:

System.Exception: 'W opisie swojej oferty umieszczasz zdjęcia, które naruszają zasady serwisu. Zgodnie z Regulaminem Allegro zdjęcia muszą być związane z oferowanym przedmiotem oraz nie mogą zawierać tekstu (wyjątek stanowią nazwy kolorów, wzorów, miar jednostek, nazwy marek/producentów, nazwy technologii). Dodatkowo zgodnie z naszymi zasadami opis oferty powinien być uzupełniony o co najmniej jedno zdjęcie prezentujące oferowany Towar.  Edytuj galerię zdjęć.  Publikacja oferty nie będzie możliwa do momentu wprowadzenia wskazanych zmian. W opisie swojej oferty umieszczasz zdjęcia, które naruszają zasady serwisu. Zgodnie z Regulaminem Allegro zdjęcia muszą być związane z oferowanym przedmiotem oraz nie mogą zawierać tekstu (wyjątek stanowią nazwy kolorów, wzorów, miar jednostek, nazwy marek/producentów, nazwy technologii). Dodatkowo zgodnie z naszymi zasadami opis oferty powinien być uzupełniony o co najmniej jedno zdjęcie prezentujące oferowany Towar.  Edytuj galerię zdjęć.  Publikacja oferty nie będzie możliwa do momentu wprowadzenia wskazanych zmian. ConstraintViolationException.OfferValidation'

Offer name is: Złoczyńcy Disneya
Offer image is image of puzzle without any text

{trace-id=2b6be3d784eb3e95}

Can you please provide me what do I wrong?

Thank you

**Comment by AureliuszBrussy** [comment]
To explain this, I ask that the seller write through [the contact form](https://allegro.pl/pomoc/kontakt) after logging into his account.

**Comment by MKI-Miro** [comment]
I am sorry I dont uderstand what you mean by your answer. Can you please provide what i need to do in more details?

**Comment by MartaNowaczyk** [comment]
The error is not a matter of problems with the public API, but with Allegro's general rules for images. Unfortunately, I don't see the description in our logs, hence I don't know what kind of photos they are. The best solution is to send the links to the photos from the description and the content of the error via [the contact form](https://allegro.pl/pomoc/kontakt), then the people who deal with photo validation will be able to help you accordingly.
