### ISSUE TITLE
Brak dostępu do zasobu

### ISSUE THREAD

**Issue by MateuszsuetaM** [allegro/allegro-api#8708]
Dzień dobry,

przy próbie zmiany statusu:
https://api.allegro.pl/order/checkout-forms/{OrderId}/fulfillment

otrzymuję status 403Forbidden mimo ustawienia dostępu do tego zasobu

Trace-id zapytania:
9575fade3dae4e54

pozdrawiam :)

**Comment by AureliuszBrussy** [comment]
W access tokenie brakuje scope'a: [allegro:api:orders:write]. Więcej o uprawnieniach przeczytasz na [naszym poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#scope-w-api-allegro).

**Comment by MateuszsuetaM** [comment]
po dodaniu nadal ten sam błąd 
trace-id:
75702e9ec1ed2e5e

**Comment by MateuszsuetaM** [comment]
Rozwiązałem - należało po zmianie zakresu uprawnień ponownie zautoryzować aplikację.
