### ISSUE TITLE
Sandbox account activation

### ISSUE THREAD

**Issue by AnlakiX** [allegro/allegro-api#8709]
Please activate the account on sandbox environment: Client:106949039

**Comment by MartaNowaczyk** [comment]
This is a regular account - you can activate it during your first test order. If you would like to test Allegro as a seller, [register a new company account](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F).

**Comment by AnlakiX** [comment]
Hello I have transformed the account to become a seller but still have troubles with activation. Could you activate the account:
testtest123123
Thank you

**Comment by MartaNowaczyk** [comment]
You have chosen the option with occasional sales - please go to full verification so that I can fully activate this account. You will do it in [this tab](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/srodki-i-historia-operacji).

**Comment by AnlakiX** [comment]
Unfortunately the account is in a state that does not allow changes mentioned

**Comment by MartaNowaczyk** [comment]
That was enough. I activated your account.

**Comment by AnlakiX** [comment]
Thanks, I can test selling now.

**Comment by AnlakiX** [comment]
Reopening:
Cannot post sell listing due to the following error:

"Wystąpił błąd - Użytkownik z blokadą konta Firma nie może wystawiać nowych ofert."

**Comment by MartaNowaczyk** [comment]
I am verifying the case, please wait.

**Comment by AnlakiX** [comment]
Okay, I have created a request for account deletion. Can it be sped up so I can recreate the account on the same email and not wait 60 days? Thanks

**Comment by MartaNowaczyk** [comment]
Yes, you can already register a new company account with the same email. Fill in all possible data and when you go through the process let me know, I will activate it.

**Comment by AnlakiX** [comment]
Hello, I have created the company account
test_org_123
Can you activate it? Thanks

**Comment by PrzemyslawLukanowski** [comment]
@AnlakiX Hello, I've activated your account.

**Comment by AnlakiX** [comment]
Thank you, everything seems to be working now.
