### ISSUE TITLE
Brak synchronizacji ze sklepem

### ISSUE THREAD

**Issue by dorotadodo** [allegro/allegro-api#871]
Dzień dobry, odesłano mnie tu w związku z problemem jaki się pojawił. 
Od razu napiszę jestem laikiem więc prosze o cierpliwość. Z pewnością nie mam pojęcia jakie informacje powinnam wstawić.
Od poniedziałku nie synchronizuje się allegro ze sklepem (presta 1.6..14) poprzez API dokładnie zaczęło się to dziać w poniedziałek  między godz: 9:57 a 10:04, o tej porze klient ponawiał płatność i poprzednia została ściągnięta do sklepu (ta odrzucona), kolejna płatność o 10:04 już nie pojawiła się w sklepie
Moduł do integracji z firmy X13
Działa wystawianie aukcji  z pozycji sklepu (nie dostaję powiadomień o wystawieniu aukcji, ale aukcja jest wystawiona), natomiast nie ściągają się zamówienia z allegro do sklepu. 
mój login Dorota_dodo
 Po mojej stronie nie było żadnych zmian.

Edit:
Problem z wystawianiem jest nieco większy niż myślałam - nie dostawanie maili że wystawiłam towar. Towar się wystawił z Presty w allegro - ALE na moim prywatnym koncie allegro, które nie jest w żaden sposób zsynchronizowane ze sklepem, nie ma w sklepie haseł ani klucza API do tego konta.  Nie wiem jak to jest możliwe. Nie umiem tu wstawić zdjęcia

**Comment by PawelTaberski** [comment]
W takim wypadku musiała Pani dać odpowiednie uprawnienia tej aplikacji dla obu kont, aby działa w Pani imieniu.
W sprawie takich problemów proszę się kontaktować z autorem aplikacji. My nie odpowiadamy za to w jaki sposób dana aplikacja wykorzystuje API Allegro. My tylko dostarczamy dany zbiór możliwości, z którego można korzystać przy budowie aplikacji.

**Comment by dorotadodo** [comment]
No własnie na tym polega problem że w sklepie do konta prywatnego nie ma żadnych danych, nic nie jest wpisane, ani hasło, ani Klucz Api ani nigdy nie robiłam autoryzacji, żeby to konto było aktywne. 
Dlatego też nie rozumiem jak to jest możliwe że mając ustawione tylko dane do 1 konta wystawia wystawia się cos na kompletnie innym koncie, do którego nie ma dostępu.

Skontaktowałam się również z autorem aplikacji.

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) login konta prywatnego na którym wprowadziły się zmiany. Sprawdzimy, czy jest z nim powiązana jakaś aplikacja. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 871 na GitHub-ie.
