### ISSUE TITLE
Offer and product title translated for no reason

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#8710]
Hi there,

we are just testing a function of creating new product cards via our app. And it happens quite a lot, that you automatically translate the title even though it is in correct langauge. I am sending product title and offer title in Czech on CZ Allegro and it was for some reason automatically translated to polish which is wrong:

![image](https://github.com/allegro/allegro-api/assets/147524238/bd652773-a151-47a9-9100-6d8aca24f25d)

Can you please tell me why the offer title was translated? 

Thank you in advance!

All the best, 

Dominika

**Comment by MartaNowaczyk** [comment]
At this point I see that the title is translated correctly, however, you have made an edit to the offer. It is possible that something did not translate from our product database. If the situation occurred again please send the trace-id from the creation of the new product/offer (do not edit it and end it before verification).

**Comment by dominikahr** [comment]
Hi Marta, 

it was not a one time thing, it is happening for all products for which I try to create a product card. I am sending the product title in czech on allegro.cz and it is being translated to polish automatically. After a little while the product name is automaticalny translated back to czech by Allegro but the offer title will stay in polish. 

Also a note: we are not sending the language of the data. But we thought it will just be uploaded in the provided form. When I tested it on PL sandbox, I was sending there CZ product title and it was not being translated. And now when I am sending CZ title to CZ allegro it is being translated.

**Comment by dominikahr** [comment]
@MartaNowaczyk even though we now tried adding the language of the data in the request, it was translated to polish. After I created the product card it looked like this:
![image](https://github.com/allegro/allegro-api/assets/147524238/5f1811b2-9c26-46be-bba3-11a220b6f7ba)
And after a little while it looks like this: 
![image](https://github.com/allegro/allegro-api/assets/147524238/273f910d-772f-45b1-96c8-305bed8628f6)
https://allegro.cz/nabidka/t-shirt-meski-okragly-dekolt-project-x-rozmiar-m-15359731783

The product name we have suggested in the request is "Pánské triko s krátkým rukávem Project X 88161131 hnědý". It is in Czech, we have send the information about the language and it was still translated to polish by allegro. 

How can we fix this?

**Comment by MartaNowaczyk** [comment]
I'll check it more closely and let you know.

**Comment by dominikahr** [comment]
Hi @MartaNowaczyk, any news regarding this topic? :)

**Comment by MartaNowaczyk** [comment]
The problem is on our side and we are trying to solve it, also please have some patience and apologize for the inconvenience.

**Comment by MartaNowaczyk** [comment]
Until we implement the fix, you can avoid this problem and set the "name" field for the offer outside the productSet section - that is, duplicate the "name" you send in "productSet.product.name".

**Comment by dominikahr** [comment]
Hi @MartaNowaczyk, thank you for the tip :) Do you have any estimated date when it could be fixed from your side?

**Comment by MartaNowaczyk** [comment]
Unfortunately, no, this is a bigger change than we expected, hence we do not have a specific date.
