### ISSUE TITLE
Pobieranie informacji o modelach samochodów i ich szczegóły

### ISSUE THREAD

**Issue by MGabala** [allegro/allegro-api#8711]
Witam, pracuję nad integracją z Allegro i aby poprawnie móc zorganizować dodawanie nowych ofert przez API potrzebuję informacje jakie produkty (samochody) są w allegro i jakie mają ID aby dalej wyszukać sobie konkretne informacje na ten temat. Przeszukałem już trochę dokumentacji i nie znalazłem nic sensownego. 

Pytanie jest proste:

Potrzebuję znaleźć szczegółowe informacje na temat modeli marki FORD

następnie potrzebuję wyszukać jakie są poszczególne parametry takie jak silnik dla modelu FUSION

czyli: jakie są wersje silników, jakie są wersje mocy itd

czy allegro API daje możliwość takiej synchronizacji?

**Comment by MartaNowaczyk** [comment]
Myśle, że w tym temacie może pomóc Ci [wyszukiwanie produktów](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-znalezc-produkt) i przeszukiwanie drzewa kategorii - [GET /sale/categories/{categoryId}](https://developer.allegro.pl/documentation/#operation/getCategoryUsingGET_1) a potem jego parametrów - [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). Innej możliwości nie widzę.
