### ISSUE TITLE
Request contains invalid data. Contact the application author.

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#8712]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry
Przy próbie wystawienia szkicu jest błąd "Request contains invalid data. Contact the application author." - strasznie dużo mówi. Coś tam w obrazkami po logu ale są obrazki. trace-id: 678bb610321dc830

Proszę o pomoc.

**Comment by MartaNowaczyk** [comment]
Dla "images" przesyłasz obiekt zamiast tablicy. Sprawdź zgodność struktury z [dokumentacją](https://developer.allegro.pl/documentation/#operation/createProductOffers).
![image](https://github.com/allegro/allegro-api/assets/38425363/63cd7fee-4658-48ba-9d21-82387d4e5baf)

**Comment by qshop123** [comment]
Dzień dobry
Pani Marto, rzeczywiście wygląda inaczej struktura. Przeanalizowałem dokumentację i dale nie wiem co tam podać?
- base64 zdjęcia?
- link url do zdjęcia?
- link do zdjęcia z waszego serwera?
- raw?

Proszę o pomoc dalszą bo z dokumentacji to nie wynika.

**Comment by MartaNowaczyk** [comment]
[Linki do zdjęć](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty):
```
...

"images":[   
    "https://...zewnetrzny-adres-pierwszego-obrazka.jpeg",
    "https://...zewnetrzny-adres-drugiego-obrazka.jpeg",
    "https://...zewnetrzny-adres-trzeciego-obrazka.jpeg"
   ]
...
```

**Comment by qshop123** [comment]
Dziękuje za odpowiedź
czy "zewnetrzny-adres-pierwszego-obrazka" oznacza 
A) Zewnętrzny adres obrazka z serwera Allegro wgrywany poprzez "sale/images"?
B) Bezpośredni adres URL do zdjęcia w postaci "https://domena/obrazek.jpg"?

Proszę o odpowiedź.

**Comment by MartaNowaczyk** [comment]
Oba URL'e są akceptowane (A i B).

**Comment by qshop123** [comment]
Ok, mamy więc :
"message":"At least one image should be attached to add product."

trace-id: f451006772dd87b4

**Comment by MartaNowaczyk** [comment]
Polecam korzystać z wyszukiwarki by sprawdzić czy ktoś już nie pytał o taki błąd np. #7105 
Tutaj ten sam przypadek - brak zdjęcia w "productSet" dla nowego produktu.

**Comment by qshop123** [comment]
A może tak : 
"message":"At least one image should be attached to add product **in the productSet section**."? 

Komunikat błędu powinien jasno wskazywać o co chodzi, prawda?

**Comment by MartaNowaczyk** [comment]
Zgłoszę taką sugestię do zespołu odpowiedzialnego za ten komunikat.

**Comment by qshop123** [comment]
Super, dziękuję.
Działa teraz...na razie.

**Comment by MartaNowaczyk** [comment]
Sugestia zmiany komunikatu błędu została odrzucona. Musisz bazować na ścieżce, którą wskazujemy w odpowiedzi **"path":"productSet[0].product".**
