### ISSUE TITLE
Sandbox: symulację doręczenia przesyłek

### ISSUE THREAD

**Issue by Aleksandrze** [allegro/allegro-api#8715]
Dzień dobry

Proszę o symulację doręczenia przesyłek.

Środowisko: sandbox
Konto na Allegro: mrooczek

Kurier: Allegro One Punkt
Zamówienie: 2ad597f0-e821-11ee-b6ce-f3176bd69caa
Przesyłka: 241c5e7d-0b11-41b5-94f9-365b4a984003
Statusy:
23.03.2024 13:00 – Oczekuje na nadanie
25.03.2024 12:00 – W drodze
26.03.2024 15:24 – W trakcie doręczenia
26.03.2024 18:00 – Oczekuje na odbiór w punkcie
27.03.2024 11:23 – Przesyłka została doręczona do odbiorcy lub odebrana z punktu odbioru

Kurier: Allegro One Punkt
Zamówienie: 2ad597f0-e821-11ee-b6ce-f3176bd69caa
Przesyłka: 8e936b4c-e59d-410f-b66b-cc584bb92dcb
Statusy:
23.03.2024 13:00 – Oczekuje na nadanie
25.03.2024 12:00 – W drodze
26.03.2024 15:24 – W trakcie doręczenia
26.03.2024 18:00 – Oczekuje na odbiór w punkcie

Kurier: Allegro One Box, One Kurier
Zamówienie: 061a9cc0-e827-11ee-b6ce-f3176bd69caa
Przesyłka: b791c963-e64e-4625-a6ce-56ee660a9481
Statusy:
23.03.2024 13:00 – Oczekuje na nadanie
24.03.2024 11:58 – W drodze
25.03.2024 15:24 – W trakcie doręczenia
26.03.2024 18:00 – Wystąpił problem z przesyłką

Kurier: Orlen Paczka
Zamówienie: 654da620-e81c-11ee-b6ce-f3176bd69caa
Przesyłka: b6d3bc86-8fca-424b-abe4-f85722ce017c
Statusy:
22.03.2024 13:00 – Oczekuje na nadanie
23.03.2024 19:21 – W drodze

Kurier: Allegro Kurier DPD
Zamówienie: dc3129e0-e819-11ee-b6ce-f3176bd69caa
Przesyłka: 41c8c05e-10c2-4051-99c0-089af32985b9
Statusy:
23.03.2024 13:00 – Oczekuje na nadanie
24.03.2024 11:58 – W drodze
25.03.2024 15:24 – W trakcie doręczenia
26.03.2024 18:00 – Kurier wystawił awizo

Kurier: Allegro Kurier DPD Pobranie
Zamówienie: 50a37f30-e81a-11ee-b6ce-f3176bd69caa
Przesyłka: ecc71944-5bbc-42e9-94d2-912bfafdc68e
Statusy:
23.03.2024 13:00 – Oczekuje na nadanie
24.03.2024 11:58 – W drodze
25.03.2024 15:24 – W trakcie doręczenia
26.03.2024 18:00 – Przesyłka została doręczona do odbiorcy lub odebrana z punktu odbioru

Kurier: Allegro Kurier DPD Pobranie (wielopaczka)
Zamówienie: 50a37f30-e81a-11ee-b6ce-f3176bd69caa
Przesyłka: 4cb8a3ec-5a22-49be-b2e9-79cc3c020df3
Statusy:
23.03.2024 13:00 – Oczekuje na nadanie
24.03.2024 11:48 – W drodze
25.03.2024 15:04 – W trakcie doręczenia
26.03.2024 17:12 – Przesyłka została doręczona do odbiorcy lub odebrana z punktu odbioru
27.03.2024 08:14 - Przesyłka została zwrócona do nadawcy

**Comment by PrzemyslawLukanowski** [comment]
Widzę, że podałeś identyfikatory przesyłek z Wysyłam z Allegro. Abyśmy mogli nadać statusy musimy posiadać numery przewozowe przesyłek, są to wartości, które zwracamy w polu `packages.waybill` dla każdej z przesyłek.

**Comment by PrzemyslawLukanowski** [comment]
Gotowe, jednak dla dwóch pierwszych przesyłek omyłkowo nadmiarowo dodałem statusy PENDING oraz AVAILABLE_FOR_PICKUP, przepraszam za kłopot. Jeśli w jakiś sposób zaburza to Twoje testy, podaj proszę nowe numery przesyłek.

**Comment by Aleksandrze** [comment]
Dziękuje. Za chwilę lub jutro poproszę jeszcze dla kilka paczek zmienić status

Dodatkowo mam 2 pytania:
1) Czy po anulowaniu przesyłki na stronie Allegro, czy można pobrać ten status? W tej chwili nadal jest pobierany poprzedni  status.

Numer zamówienia 50a37f30-e81a-11ee-b6ce-f3176bd69caa
Paczka: 0000003051783Q
Paczka miała status "Doręczona", wchodzę na Allegro i anuluję przesyłkę 
![obraz](https://github.com/allegro/allegro-api/assets/44478401/c9684310-6128-43fa-93ae-ae99bd658450)

Od API nadal dostaję status "Doręczona"
![obraz](https://github.com/allegro/allegro-api/assets/44478401/b17c0516-bc3a-4e69-bacb-0390e372eb6e)

2) Dla jakich statusów jest dozwolone Anulowanie przesyłek na Allegro?

**Comment by PrzemyslawLukanowski** [comment]
1. Nie zwrócimy tego statusu, ponieważ nie jest to status generowany po stronie przewoźnika.
2. Zgodnie z informacją z [naszego poradnika](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-anulowac-paczke): 


> Nie możesz anulować:
> 
> - paczek ze wskazaną metodą dostawy z “carrierId”: “ALLEGRO”,
> - pozostałych paczek odebranych przez kuriera lub nadanych w paczkomacie.
