### ISSUE TITLE
How to close discussion with Allegro API

### ISSUE THREAD

**Issue by andreinacuellor** [allegro/allegro-api#8716]
Hi,

The resource POST /sale/disputes/{disputeId}/messages to add a message to the discussion, when the Type is "END_REQUEST" is it the same as clicking "ASK THE BUYER TO CLOSE THE DISCUSSION" form the allegro web page?

**Comment by MartaNowaczyk** [comment]
Yes, END_REQUEST is “ASK FOR CLOSING THE DISCUSSION”.

**Comment by andreinacuellor** [comment]
Thanks!
