### ISSUE TITLE
Problem z generowaniem etykiety NOT_SELLER_ORDER

### ISSUE THREAD

**Issue by jesiiu** [allegro/allegro-api#8718]
Witam, mam problem z obsługą drugiego konta przez API, aplikacja jest zarejestrowana na koncie A i  zautoryzowana na koncie A - wszystko działa, Ta sama aplikacja została zautoryzowana na koncie B i pojawił się problem z generowaniem etykiet wysyłkowych. W odpoweidzi od API dostaję informację: 
{"code":"NOT_SELLER_ORDER","message":"Order doesn't belong to seller","details":"Order doesn't belong to seller","path":"email","userMessage":"Nie jeste\u015b w\u0142a\u015bcicielem zam\u00f3wienia"}

Z mojej strony wygląda na to, że odpowiedni klucz jest dobierany do odpowiedniego zapytania ale cały czas jedyne co otrzymuję podczas generowania etykiety to właśnie błąd. 
Kiedy zmieniałem statusy zamówień z "NOWE" na "W REALIZACJI" nie miałem takiego problemu i wszystko przebiegło pomyślne.
Mógłbym prosić o weryfikację tej sprawy ?
Podsyłkam przykładowe commandId - 48f4a16e-ecf1-4949-94c6-525033e2e58a

Jeżeli jest możliwość to prosiłbym o podesłanie kawałka klucza autoryzacyjnego zapytanie to porównałbym sobie czy na pewno odpowiedni klucz został podany w zapytaniu. Chyba, że problem leży gdzie indziej ale na ten moment nie jestem wstanie tego zweryfikować

**Comment by MartaNowaczyk** [comment]
Z tego co widzę mylisz tokeny. Jesteś zautoryzowany jako konto z początkiem ID "28...", a zamowienie dotyczy konta z początkiem ID "11..."

**Comment by jesiiu** [comment]
Tak wiem, właśnie sobie to uświadomiłem, że zrobiłem literówkę w programie i wszystko wskazywało na to, żejest dobrze ale jednak finalnie wyszło, że tak nie jest
Już opanowane, pozdrawiam serdecznie
