### ISSUE TITLE
How to send personal question to support?

### ISSUE THREAD

**Issue by kavuncheg** [allegro/allegro-api#8719]
How to send personal question to support?

**Comment by MartaNowaczyk** [comment]
You can use the [contact form](https://allegro.pl/pomoc/kontakt).

**Comment by kavuncheg** [comment]
Thank you, I sent message

**Comment by MartaNowaczyk** [comment]
Not yet, as soon as customer service give it to us we will definitely answer it.

**Comment by kavuncheg** [comment]
Good morning, I sent 2 question from contact form, but I didn't get any answer (

**Comment by MartaNowaczyk** [comment]
As I wrote it will receive customer service, probably messages are waiting in the queue, hence it may take a while to respond.

**Comment by kavuncheg** [comment]
Maybe there is other way to solve my problem? I use this API and got error 403. I have client_id, but how to give to you this id with secure way?

**Comment by MartaNowaczyk** [comment]
The contact form is the only way, but you can also give me the trace-id you get in the error response.

**Comment by kavuncheg** [comment]
But I can get data from this url https://api.allegro.pl/sale/categories

**Comment by MartaNowaczyk** [comment]
Make sure you do not use authorization type [client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow), which does not have a user context. In [our documentation](https://developer.allegro.pl/documentation/) you will find the appropriate indication of what type of authorization is required for a given resource:

- bearer-token-for-user ([code](https://developer.allegro.pl/auth/#app) lub[ device](https://developer.allegro.pl/auth/#DeviceFlow) flow),
- bearer-token-for-application ([client credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow)).

**Comment by kavuncheg** [comment]
Can you check rights for my username - OK-LIVING.
And what type we must use?

**Comment by kavuncheg** [comment]
Now, I understood. Thank you a lot.
