### ISSUE TITLE
[REST] [INPOST] BRAK MOŻLIWOŚCI INTEGRACJI Z ALLEGRO INPOST

### ISSUE THREAD

**Issue by coobitus** [allegro/allegro-api#872]
Tak jak w temacie, ku przestrodze dla wszystkich zainteresowanych deweloperów. Nie ma w tej chwili możliwości w Allegro REST API żeby zintegrować się z Inpostem wykorzystując którykolwiek ze sposobów dostawy oznaczonych jako "Allegro Inpost *". 

Allegro nie dostarcza odpowiedniego identyfikatora transakcji potrzebnego dla Inpostu. I nie jest w stanie już od paru miesięcy nic z tym zrobić. Piszą ciągle o tym że sprawa jest w toku, ale w praktyce nic to nie zmienia z punktu widzenia deweloperów chcących w 100% przejść na obsługę zamówień przez REST API.

**Comment by coobitus** [comment]
Minął kolejny miesiąc i nadal temat nie jest rozwiązany ...

**Comment by PawelTaberski** [comment]
Trwają rozmowy z Inpostem w sprawie rozwiązania tej sytuacji, jak już wielokrotnie informowaliśmy, jak tylko otrzymamy jakieś konkretne informacje, poinformujemy o tym w dedykowanym komunikacie.

**Comment by coobitus** [comment]
Jak wygląda sytuacja w temacie? Coś z tym zrobiliście w końcu? Z informacji od moich klientów wynika, że właśnie przestaliście wysyłać w mailach z zamówieniami pobraniowymi ten stary numer płatności, więc w takim przypadku nie można nawet tego obsłużyć ręcznie - przez wyciągnięcie tego numeru z maila (sic!) i wprowadzenie go do naszego sklepu ręcznie - żeby potem obsłużyć paczkę w Inpost .... 

Czyli cały czas ograniczacie funkcjonalności nie troszcząc się o rozwiązanie zasadniczego problemu ...

**Comment by PawelTaberski** [comment]
Pracujemy wspólnie nad nowym zasobem w tym miesiącu powinien już być gotowy.

**Comment by wilktomasz** [comment]
@PawelTaberski 
Czy "w tym miesiącu" nowy zasób jest gotowy?

**Comment by PawelTaberski** [comment]
@wilktomasz Tak już jest taki zasób, więcej informacji znajdziesz tutaj #1217

**Comment by coobitus** [comment]
@PawelTaberski to chyba jakiś żart? Ten ticket o którym piszesz dotyczy możliwości dodania numeru przesyłki do zamówienia na Allegro. Ale żeby to zrobić, to trzeba ten numer najpierw mieć - czyli wygenerować go na Inpoście. A żeby to zrobić to trzeba mieć "prawidłowy" numer płatności z zamówienia. I cały czas pytamy się o możliwość wyciągnięcia tego ostatniego ... Wydaje mi się, że @wilktomasz też o to pyta ... Z tego wniosek że nie jest prawdą to co napisałeś, że "ten zasób już jest gotowy"?

**Comment by PawelTaberski** [comment]
@wilktomasz @coobitus Teraz rozumiem odnośnie tej sprawy jesteśmy w stałym kontakcie z Inpostem i pracują nad tym, jednakże czas może się wydłużyć od tego o jakim informowaliśmy tutaj #1043
