### ISSUE TITLE
Wystąpił błąd komunikacji z API przewoźnika

### ISSUE THREAD

**Issue by krzysda** [allegro/allegro-api#8720]
Witam, przy serwisie 1c8d2e29-f313-4992-9fa4-5f97a243088d otrzymuję ciągle komunikat Wystąpił błąd komunikacji z API przewoźnika czy to faktycznie błąd przewoźnika czy może komunikat jest nieprecyzyjny i może oznaczać coś innego.

**Comment by MartaNowaczyk** [comment]
Zdarza się, że jest nieprecyzyjny. Do weryfikacji podaj proszę commandId lub trace-id.

**Comment by krzysda** [comment]
66017c47-6601-6601-6601-66017c475a2f

**Comment by MartaNowaczyk** [comment]
Błąd spowodowany jest tym, że kwota ubezpieczenia nie może być mniejsza niż kwota pobrania.

**Comment by krzysda** [comment]
ale całe zamówienie jest w EURO a ubezpieczenie trzeba podać w PLN użyłem więc aktualnego średniego kursu NBP

**Comment by MartaNowaczyk** [comment]
Jak chcesz zapłacić za ubezpieczenie i wpisać jakąś kwotę, to na dzień dzisiejszy przelicznik DHL to 4.6. Możesz też podać 0,00 zł i wtedy paczka jest ubezpieczona do limitu w cenie.
