### ISSUE TITLE
Problem z otrzymywaniem odwróconej etykiety ZPL

### ISSUE THREAD

**Issue by marcinwojcikyosi** [allegro/allegro-api#8721]
Dzień dobry,

jeden z klientów zgłosił problem z otrzymywaniem odwróconej etykiety ZPL korzystając z Wysyłam z Allegro i zaznaczając usługę UPS. Sprawdziliśmy to na swoim środowisku i wydarzyło się to samo, tzn. otrzymaliśmy odwróconą etykietę. Skontaktowaliśmy się z naszymi programistami, którzy przejrzeli kod i potwierdzili, że etykieta ZPL jest pobierana z Allegro już w takiej formie, tzn. tej odwróconej. Prosiłbym o weryfikację i infor
mację, co jest lub może być tego przyczyną. Przykładowa etykieta w załączniku, id przykładowego requesta na sandboxie poniżej.

Przykład requesta na sandbox trace-id = fdc84a0468011921
Etykieta - 
[WysylamZAllegro1Z0103240913510944.pdf](https://github.com/allegro/allegro-api/files/14744537/WysylamZAllegro1Z0103240913510944.pdf)

**Comment by Bober95** [comment]
Dzień dobry, sprawdziłem i faktycznie u mnie również są odwrócone, tylko właściwie w czym to przeszkadza ? Przecież kartkę można odwrócić

**Comment by MartaNowaczyk** [comment]
Po naszej stronie nic nie było zmieniane, więc to musi być zmiana po stronie UPS. Najważniejsze, że z samym wydrukiem nie ma problemu.

**Comment by marcinwojcikyosi** [comment]
Problem u Klienta jest poważny, ponieważ "**po wydruku jednej takiej etykiety sterownik drukarki zapamiętuje ten typ wydruku i nie można go w żaden sposób przestawić. Ostatnio po takim wydruku musieliśmy resetować sterowniki i na nowo instalować drukarki do etykiet. Wydruk etykiety "na odwrót" powoduje problemy na magazynie z odpowiednim dopasowaniem jej do etykiety dodatkowej.**"

Czy jesteśmy w stanie potwierdzić, że odwrócone etykiety są spowodowane UPS, a nie Allegro?

**Comment by MartaNowaczyk** [comment]
Sprawdzaliśmy to po naszej stronie i to kwestia UPS. Wyjaśniamy tę zmianę z nimi.

**Comment by marcinwojcikyosi** [comment]
Dziękuję, w takim razie czekam na informację

**Comment by MartaNowaczyk** [comment]
Dostaliśmy odpowiedź od UPS, że jest to prawidłowe działanie. Etykieta jest pierwotnie odwrócona, w jej treści jest komenda odwracająca POI, która jest interpretowana przez drukarkę i odwaraca etykietę do poprawnej orientacji, zgodnie z specyfikacją. Kwestie poprawnego korzystania z etykiet UPS konsultuj proszę z ich obsługą techniczną.
