### ISSUE TITLE
Filter request by date time? 

### ISSUE THREAD

**Issue by andreinacuellor** [allegro/allegro-api#8724]
Hi!

I am trying to get all user threads using this resource: List user threads (https://api.{environment}/messaging/threads)

I know there are 2 parameters: limit( max 20) and offset (max 15000000)

Is there a way to filter by date? or offset parameter is a parameter in minutes? 

Or I always get the last 20 threads that I haven't read? 

Because I need to call this request from Salesforce from time to time to know if I have received a new message from a thread or a new thread has been created?

Or from you, what would be the best approach to not miss any new message / new thread?

**Comment by MartaNowaczyk** [comment]
There is no sorting or filtering by date. You just have to save on your side what you already have and keep downloading from that point.

**Comment by andreinacuellor** [comment]
and what type is offset parameter? is It minutes or just the number of threads you want to retrieve?

**Comment by MartaNowaczyk** [comment]
This is the index number of the thread. The offset parameter you can use to indicate the place from which you want to download another portion of data e.g. GET /messaging/threads?limit=10&offset=5 you will download 10 threads starting with the one indexed as 5, then you can download another 10 from thread 15 and so on.

**Comment by andreinacuellor** [comment]
the documentation says that the threads are sorted by last message date, starting from newest.

So the offset = 0 would be the thread with the newest message?

**Comment by MartaNowaczyk** [comment]
Yes, the newest thread is 0.

**Comment by andreinacuellor** [comment]
thanks
