### ISSUE TITLE
GET /sale/offer-classifieds-packages/{offerId} nie zwraca żadnego zasobu dla offerId

### ISSUE THREAD

**Issue by partiid** [allegro/allegro-api#8725]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description** 
GET /sale/offer-classifieds-packages/{offerId} zwraca 404 - prawdopodobnie zamiast po offerId zwraca po ClassifiedsId lub coś podobnego, bo dla żadnej oferty nie zwraca classifieds chociaż powinno. 

Curl: 
```
 curl --location --request GET 'https://api.allegro.pl/sale/offer-classifieds-packages/15339824005' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer [tutaj token]' \
--header 'Host: api.allegro.pl' \
--header 'Connection: keep-alive'
```

Zwrotka: 
```
"errors": [
        {
            "code": "ClassifiedForOfferNotFoundException",
            "message": "Classified with id: 15339824005 does not exist.",
            "details": null,
            "path": null,
            "userMessage": "Classified with id: 15339824005 does not exist."
        }
    ]
```
Niestety zasób ten jest opisany, aby podać id oferty co czynię, dla każdej oferty to samo, nie znajduje Classified z podanym id choć w dokumentacji jest opisane aby podać id oferty. 
Może ja coś robię nie tak? 
Proszę o pomoc. Pozdrawiam

**Comment by MartaNowaczyk** [comment]
[Zasoby te dotyczą ogłoszeń](https://developer.allegro.pl/tutorials/jak-wystawic-i-zarzadzac-ogloszeniem-K6r3Z47dKcy) (gdy w polu sellingMode.format masz wartość "ADVERTISEMENT"), a Ty masz oferty zwykłe ("BUY_NOW").

**Comment by partiid** [comment]
Dzięki za pomoc, do zamknięcia.
