### ISSUE TITLE
API - Unable to add new products

### ISSUE THREAD

**Issue by MartaNowaczyk** [allegro/allegro-api#8729]
Hi,

We can't upload new products via API, it gives this error, what about it?

stdClass Object ( [errors] =&gt; Array ( [0] =&gt; stdClass Object ( [code] =&gt; MatchingProductNotFoundException [message] =&gt; Unprocessable Entity [details] =&gt; [path] =&gt; productSet[0 ].product [userMessage] =&gt; No product matches the entered number. ) ) ) Add product fails

_Originally posted by @Ricomsecure in https://github.com/allegro/allegro-api/discussions/8727_

**Comment by MartaNowaczyk** [comment]
It seems that the data is not correct. You should provide an ID of the existing product or GTIN. This is due to the error you sent. I don't know what you are sending because you didn't specify the trace-id for this call.

**Comment by Ricomsecure** [comment]
this is a new product that is not yet based on Allegro. It is our product that we import to the European market and the EAN is: 8594200195304. Our product ID is: 604283. We have filled in all the parameters.

Could you help me?

**Comment by MartaNowaczyk** [comment]
In this case, you need to list the offer with a new product ([tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-list-an-offer-assigned-to-a-new-product)) or[ add a new product ](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-create-a-product)and list based on it ([tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-list-an-offer-with-a-product)). 

The error occurs because you are probably passing the GTIN of an unknown product in "productSet.product.id". If you get such an error, or you know that such a product does not exist you need to add such a product, and pass the GTIN in the parameters - as in the first tutorial I linked.
