### ISSUE TITLE
Problem z wystawianiem ofert Umidigi

### ISSUE THREAD

**Issue by Servatechsro** [allegro/allegro-api#8730]
Dzień dobry,

Mamy nieustający problem z ofertami marki Umidigi. Niestety nie możemy wystawić ofert przez Baselinker. Pojawiają się błędy typu model XY nie koresponduje z marką UMI. Po zmianie modelu również nie uda się oferty wystawić a po zmianie marki na Umidigi pojawi się komunikat, że marka "Umidigi" nie odpowiada wartości UMI (widoczne na 3x zrzutach ekranu). Jeśli wystawimy oferty przez portal Allegro, oferty nie można później edytować, czy raczej zapisać je po edycji. Pojawiają się wtedy te same błędy, co w przypadku Baselinker i żadne ustawianie parametrów również nie pomaga (widoczne na ostatnim screenie). Jest to zdecydowanie błąd po stronie portalu Allegro. W zeszłym roku sprzedawaliśmy produkty na polskim rynku bez problemu. Następnie w Państwa katalogu marka Umidigi została dodana obok pierwotnej marki UMI i od tego czasu są z tym problemy. Prosimy o rozwiązanie tego problemu. Mamy wiele produktów marki Umidigi, które chcielibyśmy sprzedawać na wszystkich rynkach, ale niestety nie jest to możliwe. 

Z góry dziękujemy i pozdrawiamy

Zespół Servatech s.r.o.
![1](https://github.com/allegro/allegro-api/assets/165013326/82a13403-b48f-49bc-a696-dd054de5236c)
![2](https://github.com/allegro/allegro-api/assets/165013326/8542d7d6-d473-4b75-838e-7f46cebcd2dd)
![3](https://github.com/allegro/allegro-api/assets/165013326/416ad76c-a7f7-460a-b986-baebfb0fa57e)
![4](https://github.com/allegro/allegro-api/assets/165013326/ec07b324-0ed3-4f2c-848d-4c1445fb65da)

**Comment by Lukasz-Zurek** [comment]
Twój problem dotyczy generalnie katalogu produktów i konkretnych marek, a nie samego procesu wystawiania. Nasze API zwraca czytelne komunikaty, które w tym przypadku Baselinker przekazuje w panelu swojego narzędzia. Najlepiej będzie jak skorzystasz mimo wszystko z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt).
