### ISSUE TITLE
How to buy from allegro using API?

### ISSUE THREAD

**Issue by Viaroge** [allegro/allegro-api#8731]
I do not intend to sell on Allegro; rather, I aim to purchase products from Allegro using their API. Our goal is to integrate Allegro's auto parts into our marketplace, enabling our customers to make purchases through our platform. Despite our interest solely in purchasing, our account application was rejected, with Allegro citing, 'Unfortunately, we had to reject your company data. You cannot sell on Allegro.' It's important to clarify that we are not seeking to sell on Allegro but rather to buy from them. Could you please assist in resolving this issue? or is it possible to purchase from allegri using API with out account activation?

**Comment by Lukasz-Zurek** [comment]
I cannot help you regarding account verification - this process is out of our hands. 

Another thing - we do not have the resources in our public API to make purchases on Allegro, so it is impossible.

**Comment by Viaroge** [comment]
> I cannot help you regarding account verification - this process is out of our hands.
> 
> Another thing - we do not have the resources in our public API to make purchases on Allegro, so it is impossible.
"motopoland.com.ua" as i know motopoland have integration with allegro and have the same stocks in automotive industry as allegro have we want to do same, how do it?  you can check links bellow


https://motopoland.com.ua/detail/14495589036/

https://allegro.pl/oferta/mercedes-w212-lift-amg-zderzak-przod-a2128852638-idealny-14495589036?reco_id=7ebaee1e-eb68-11ee-be98-c2c94d0aa7e2&sid=1b14f67fa36602937f1572a57e6df4124ef63b53ab9897d3b9ab8b1bd1d899d5

**Comment by Lukasz-Zurek** [comment]
@Viaroge I cannot help you in this case. This is API forum. In our public API we only share [Allegro One Fulfillment resources](https://developer.allegro.pl/tutorials/one-fulfillment-by-allegro-0ADwgOLqWSw). [More information](https://help.allegro.com/sell/pl/a/czym-jest-one-fulfillment-by-allegro-O3Pwb4VeoHg) about this service.

I suggest [contact form](https://allegro.pl/pomoc/kontakt) to get more information about it. But this is not typical dropshipping service.
