### ISSUE TITLE
pobranie listy parametrów produktów.

### ISSUE THREAD

**Issue by bmusialekcepd** [allegro/allegro-api#8732]
witam, w jaki sposób mogę pobrać liste wszytskich dostepnych parametrów w allegro?

**Comment by jezewskiBNetrox** [comment]
> witam, w jaki sposób mogę pobrać liste wszytskich dostepnych parametrów w allegro?

@bmusialekcepd Każda kategoria ma osobną listę parametrów. Musiałbyś pobrać wszystkie kategorie i wtedy parametry każdej kategorii z osobna.

**Comment by Lukasz-Zurek** [comment]
@bmusialekcepd Dokładnie tak jak napisał już @jezewskiBNetrox. Aby pobrać listę parametrów skorzystaj z [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2), ale w tym przypadku musisz wskazać id kategorii i aby uzyskać oczekiwane rezultaty, o których wspomniałeś w wątku, musiałbyś to zrobić dla każdej kategorii.
