### ISSUE TITLE
How set a thread as read

### ISSUE THREAD

**Issue by andreinacuellor** [allegro/allegro-api#8736]
Hi,

When i use the resource **_https://api.{environment}/messaging/threads_** and I get the user list of threads, are those threads automatically set as read within Allegro? or when I get them I need to use the resource **_https://api.{environment}/messaging/threads/{threadId}/read_** to mark those threads as read?

**Comment by MartaNowaczyk** [comment]
Will be marked as read when you use PUT /messaging/threads/{threadId}/read.

**Comment by andreinacuellor** [comment]
and if I send a new message using https://api.{environment}/messaging/message-attachments, does it also mark the thread as read or also I need to use PUT /messaging/threads/{threadId}/read.?

**Comment by MartaNowaczyk** [comment]
No, you need to use PUT /messaging/threads/{threadId}/read.

**Comment by andreinacuellor** [comment]
thanks
