### ISSUE TITLE
Endpoint /messaging/messages {'errors': [{'code': 'ERROR', 'message': 'Bad Request', 'details': None, 'path': None, 'userMessage': 'Bad Request'}]}

### ISSUE THREAD

**Issue by matecz11** [allegro/allegro-api#8737]
- [X] Sandbox

Cześć,
używając python3 i requests próbuję automatycznie wysłać wiadomość do kupującego po zakupie. Niestety dostaję ww. error przy każdej próbie.
```
url = 'https://api.allegro.pl.allegrosandbox.pl/messaging/messages'
txt = f'tekst autorespondera'
recipient = respond.json()['checkoutForms'][0]['buyer']['login'] # respond po odpytaniu /order/checkout-forms
payload = {
    'recipient': {
        'login': str(recipient)
    },
    'text': txt
}
headers = {'Authorization': f'Bearer {token}', 'Accept': "application/vnd.allegro.public.v1+json", 'Content-type': 'application/vnd.allegro.public.v1+json'}
resp = requests.post(url, headers=headers, data=payload)

```
w odpowiedzi dostaję:
```
{'errors': [{'code': 'ERROR', 'message': 'Bad Request', 'details': None, 'path': None, 'userMessage': 'Bad Request'}]}
```
Testy dla loginów: 'jakiś_login' i 'Client:1234567890'
Co robię źle? 
Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Możesz podać trace-id, który dostajesz dla tego błędu do weryfikacji, wtedy będę mogła odszukać to w logach. Prowadzimy wsparcie w zakresie samego API Allegro, dlatego do naszej weryfikacji powinieneś przesłać dane w formacie JSON, albo wspomniany trace-id.

**Comment by matecz11** [comment]
Jasne, jedno z najświeższych:
```
{'content-encoding': 'gzip', 'trace-id': '5b2749e07e476fe8', 'date': 'Wed, 27 Mar 2024 12:01:51 GMT', 'content-type': 'application/json', 'transfer-encoding': 'chunked', 'strict-transport-security': 'max-age=15552000'}
```

**Comment by MartaNowaczyk** [comment]
Postaram się to zweryfikować. Dam znać jak będę miała jakieś informacje.

**Comment by MartaNowaczyk** [comment]
Przykro mi, ale nie mamy logów dla tego przypadku.

**Comment by matecz11** [comment]
Sprawdziłem na allegro.pl i dostaję ten sam response:
```
text
'{"errors":[{"code":"ERROR","message":"Bad Request","details":null,"path":null,"userMessage":"Bad Request"}]}'
```
```
headers
{'content-encoding': 'gzip', 'trace-id': '898ac2173e0dff99', 'date': 'Wed, 10 Apr 2024 20:44:24 GMT', 'content-type': 'application/json', 'transfer-encoding': 'chunked', 'x-frame-options': 'DENY', 'strict-transport-security': 'max-age=15552000'}
```
Może to coś pomoże?

**Comment by MartaNowaczyk** [comment]
Dostałam informację z formularza kontaktowego. Poprawny payload to {"recipient": {"login": "jakis_login"}, "text": "dzięki"}.

**Comment by matecz11** [comment]
{'recipient': {'login': 'matecz'}, 'text': 'dzięki'} (skopiowane z Twojej odpowiedzi, jedyne co to zmieniłem login)
 {'content-encoding': 'gzip', 'trace-id': '5eb6376ac69d31e0', 'date': 'Fri, 19 Apr 2024 09:20:52 GMT', 'content-type': 'application/json', 'transfer-encoding': 'chunked', 'strict-transport-security': 'max-age=15552000'}
 b'{"errors":[{"code":"ERROR","message":"Bad Request","details":null,"path":null,"userMessage":"Bad Request"}]}'

**Comment by MartaNowaczyk** [comment]
Musisz to sprawdzić po swojej stronie, bo to bez problemu przechodzi w czystym JSON. Pewnie wysyłasz ' zamiast ".

**Comment by MartaNowaczyk** [comment]
Cieszę się, że udało się rozwiązać problem.
