### ISSUE TITLE
Długość pola "Firma" na koncie kupującego

### ISSUE THREAD

**Issue by caroteczek** [allegro/allegro-api#8739]
Dzień dobry,

jaka jest minimalna oraz maksymalna ilość znaków dla pola "Firma" na koncie kupującego ?
![image](https://github.com/allegro/allegro-api/assets/157691660/f49fe2e4-ae28-4a27-8283-ace4200d5fd8)
Ponieważ klient wprowadził znak "-" w tym miejscu, i  nie generuje się list przewozowy:
![image](https://github.com/allegro/allegro-api/assets/157691660/bc00a0d0-c250-4279-b3d5-cc210eb99cf0)
![image](https://github.com/allegro/allegro-api/assets/157691660/7f0c878e-d70b-4b49-a809-af28028b7662)

**Comment by Lukasz-Zurek** [comment]
@caroteczek Nie jest to co prawda pytanie dotyczące API, sprawdziłem jednak limity i w procesie zakupowym dla tego konkretnego pola nie ma minimalnej liczby znaków, natomiast maksymalna wynosi 64 znaki.
