### ISSUE TITLE
about create offer of describe 

### ISSUE THREAD

**Issue by skutop001** [allegro/allegro-api#8740]
Due to violations of the Allegro Terms & Conditions and/or legal regulations, our automated systems have located and removed your offer from all markets where it was available.

If there were promotion options in your offer, they have been ended.

See below for details. 
 Your offer description included advertising content.According to the Allegro Terms & Conditions (Appendix No. 2, Section 2(1.10)) you are not allowed to include information in the offer description about the possibility to purchase the product outside Allegro, or which encourages agreeing on a price for the product outside the auction.Here are some examples of prohibited expressions:Before you buy, contact us to check availability,Negotiable price,goods presented through other channels/advertisements, at the store, at the online store, etc.,buyout price (no auction, outside Allegro) is...,price per unit, but I will sell only as a set,multiply the highest bid price by three,if the offer does not reach the minimum price, I will consider the highest bid,I will sell, even if the minimum price is not reached,don’t want to wait until the offer ends — contact us,Looking for something else? Contact us,I can list it in a separate offer at your request,Ask about freebies, etc.Organize the content of your offers — remove the information that encourages buying off-site.Additional information:
Sales outside Allegro and bypassing fees
Rules for offer listing and descriptions
What a good offer description should contain
Appendix No.2 to the Allegro Terms & Conditions\\Concerns offers:Etui Do Motorola MOTO G14 Miękki Zderzak Szczupły TPU Ochrona Marmurowy
Etui Do Motorola MOTO G14 Miękki Zderzak Szczupły TPU Ochrona Marmurowy
Multiple violations may result in your account being suspended.You may relist removed offers. Make sure their titles and/or descriptions are in accordance with our rules. To relist them, go to the My Assortment tab and click Relist next to the selected offers. Use the filter Offer Status: expired. If your

**Comment by MartaNowaczyk** [comment]
Here we provide Allegro API support, so for general issues, please write through the [contact form](https://allegro.pl/pomoc/kontakt).

**Comment by skutop001** [comment]
Here are some examples of prohibited expressions:

Before you buy, contact us to check availability,

Negotiable price,

goods presented through other channels/advertisements, at the store, at the online store, etc.,

buyout price (no auction, outside Allegro) is...,

price per unit, but I will sell only as a set,

multiply the highest bid price by three,

if the offer does not reach the minimum price, I will consider the highest bid,

I will sell, even if the minimum price is not reached,

don’t want to wait until the offer ends — contact us,

Looking for something else? Contact us,

I can list it in a separate offer at your request,

Ask about freebies, etc.

**Comment by skutop001** [comment]
But I didn't include these words, so I'm confused. Why did I delete my offer

**Comment by skutop001** [comment]
![image](https://github.com/allegro/allegro-api/assets/150323365/c1f6cf8f-dd0f-4169-a536-a375ff4f456c)

**Comment by skutop001** [comment]
this is my describe :
Odpinany pasek crossbody jest wystarczająco mocny, abyś mógł go łatwo używać wszędzie, wyposażony w długą linę, aby zaspokoić Twoje potrzeby przy różnych okazjach.

Wykonany z wysokiej jakości elastycznych i miękkich krawędzi zderzaka z gumy TPU przy użyciu technologii galwanizacji, nie blaknie.

Idealnie pasuje do Twojego smartfona, precyzyjne wycięcia umożliwiają pełny dostęp do ekranu dotykowego, przycisków, aparatu i portów;

Umożliwia dostęp do wszystkich przycisków i portów do ładowania i synchronizacji;

Lekka konstrukcja idealnie pasuje do Twojego telefonu, nie sprawia, że Twój telefon wygląda nieporęcznie.

Stan: nowy

Pakiet:

1 x etui Telefonu; 1 x Pasek Crossbody

**Comment by MartaNowaczyk** [comment]
We do not verify descriptions here, so write about it through the [contact form](https://allegro.pl/pomoc/kontakt).
