### ISSUE TITLE
share 

### ISSUE THREAD

**Issue by api-test-yexiu** [allegro/allegro-api#8741]
How can I bulk share quotes from Poland to Czech Republic and Slovakia via API
![image](https://github.com/allegro/allegro-api/assets/155221200/03cd583a-8f1f-4d06-906e-b8fad7f2a4b5)

**Comment by api-test-yexiu** [comment]
```
PUT /sale/offer-modification-commands/20456ce5-5026-401f-85a3-df970176a15b HTTP/1.1
Host: api.allegro.pl
Authorization:  Bearer TOKEN
Content-Type:  application/vnd.allegro.public.v1+json
Accept:  application/vnd.allegro.public.v1+json
Content-Length: 671

{
  "modification": {
   "publication": {
     "marketplaces": {
        "base": {
            "id": "allegro-pl"  
          },
       "additional": [    
              {
              "id": "allegro-cz"          
              }
       ]
     }
 }, "additionalMarketplaces": {
     "allegro-cz": {        
         "sellingMode": {        
             "price": {            
                 "amount": "684", 
                 "currency": "CZK" 
             }
         }
     }
 }
  },
  "offerCriteria": [
    {
      "offers": [
        {
          "id": "15249831290"
        }
      ],
      "type": "CONTAINS_OFFERS"
    }
  ]
}
```

**Comment by MartaNowaczyk** [comment]
Information about managing offers in bulk you can find in our [guide](https://developer.allegro.pl/tutorials/listing-and-managing-offers-on-foreign-marketplaces-7GndGjeAATn#managing-offers-in-bulk).

**Comment by api-test-yexiu** [comment]
```
PUT /sale/offer-modification-commands/7c9b2f78-de3c-4ddd-9446-de9f35c63de6 HTTP/1.1
Host: api.allegro.pl
Authorization:  Bearer **
Content-Type:  application/vnd.allegro.public.v1+json
Accept:  application/vnd.allegro.public.v1+json
Content-Length: 496

{
  "modification": {
      "publication": {
          "marketplaces": {
              "additional": {
                  "add": [  
                      {
                          "id": "allegro-cz"  
                      }
                  ],
              }
          }
      }
  },
  "offerCriteria": [
      {
          "type": "CONTAINS_OFFERS",
          "offers": [
              {
                  "id": "15275992658"
              }
          ]
      }
  ]
}
```

{
    "errors": [
        {
            "code": "MESSAGE_NOT_READABLE",
            "message": "Message not readable",
            "details": null,
            "path": null,
            "userMessage": "Request contains invalid data. Contact the application author.",
            "metadata": {}
        }
    ]
}

**Comment by MartaNowaczyk** [comment]
The problem is the comma. Remove it and it should be ok.
![image](https://github.com/allegro/allegro-api/assets/38425363/168b74f5-abe0-4181-b942-f3d9a5af64bb)

**Comment by api-test-yexiu** [comment]
It was added, but the price was not automatically calculated.
![image](https://github.com/allegro/allegro-api/assets/155221200/cd376be3-dce5-4e5b-aef8-bd80707b8dd2)
How can I use API to automatically calculate prices?

**Comment by MartaNowaczyk** [comment]
You can use [price automation in offers](https://developer.allegro.pl/tutorials/listing-and-managing-offers-on-foreign-marketplaces-7GndGjeAATn#managing-price-automation-in-offers).
