### ISSUE TITLE
Connection Reset Error while requesting allegro api using axios

### ISSUE THREAD

**Issue by mohan-mandal-pattern** [allegro/allegro-api#8742]
Występuje problem: 
 - [] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

I got the connection reset error while requesting Allegro API using Axios but did not get the same error while using fetch API. Can you help me why this is happening on our system?

**Comment by MartaNowaczyk** [comment]
We do not provide support for programming languages or libraries. If you have a specific error from our API please provide a specific example that I can identify in our logs. 
Perhaps other users of our community have experienced a similar problem and will help.
