### ISSUE TITLE
Compatible-products puste na sandbox

### ISSUE THREAD

**Issue by TomaszPabianItPiast** [allegro/allegro-api#8743]
Dzień dobry, przy próbie pobrania listy kompatybilności dla części samochodowych dostaję pustą listę na sandboxie. Pytanie czy źle generuję zapytanie czy ta lista powinna być pusta czy tylko na sandboxie jest to puste?

requestUri "https://api.allegro.pl.allegrosandbox.pl/sale/compatible-products"
requestString "type=CAR&phrase=SEAT AROSA (6H) 1.0 1997.05 - 2004.06"
trace-id: 5575a184b1774eec

**Comment by Lukasz-Zurek** [comment]
Otrzymujesz pusty wynik ze względu na fakt korzystania ze środowiska testowego.

Za pomocą GET /sale/compatible-products/groups?type=CAR możesz sprawdzić, że zwracamy tylko "Mercedes-Benz", natomiast na produkcji otrzymasz już pełną listę.
