### ISSUE TITLE
Tworzenie paczki do wskazanego zamówienia

### ISSUE THREAD

**Issue by malesiuk** [allegro/allegro-api#8744]
Dzień dobry,
Mam utworzone 3 zamówienia, które mają jednakową listę produktów, te same dane sprzedającego i kupującego oraz ten sam punkt odbioru. Przy próbie utworzenia paczki metodą **/shipment-management/shipments/create-commands** z intencją utworzenia paczki np. do drugiego zamówienia paczka tworzy się zawsze do pierwszego zamównienia. 
W jakis sposób utworzyć paczkę do konkretnego (wskazanego?) zamówienia? Nie widzę pola w payload, do którego można by przekazać identifikator zamówienia (a ułatwiłoby ono życie).

Podaję jeszcze numery zamówień (jeśli w czymś to pomoże):
37061b70-ec50-11ee-9395-ff40c8234cce
8fd744b0-eccb-11ee-9395-ff40c8234cce
b3af4b30-eccb-11ee-9395-ff40c8234cce

Metoda dostawy to **Allegro One Box**.

Jeśli jest to jednak opisane w dokumentacji to przepraszam i prosze o wskazanie metody rozwiązania takiego case'a.

**Comment by Lukasz-Zurek** [comment]
Podczas tworzenia nowej paczki musisz pamiętać o przekazaniu prawidłowego, unikalnego adresu e-mail Kupującego, w polu **"receiver.email"**. Musi to być prawidłowy, [maskowany adres e-mail](https://help.allegro.com/sell/pl/a/jak-wyswietlamy-adresy-e-mail-w-korespondencji-w-ramach-allegro-D7aze0RPaSZ). Na podstawie takiego maila, identyfikujemy konkretne zamówienie.

Sam adres e-mail uzyskasz oczywiście za pomocą [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET).

Czyli generalnie proces jest taki, że pobierasz informacje per konkretne zamówienia, w tym dane Kupującego i jego maskowany adres e-mail i przekazujesz te dane w procesie tworzenia paczki.

**Comment by malesiuk** [comment]
Dzięki za szybką odpowiedź. Czyli okazuje się, że czasem warto zadać pytanie niż samemu to rozkminiać :)
Pozdro!
