### ISSUE TITLE
Utworzenie w katalogu dwóch produktów z tym samym EANem

### ISSUE THREAD

**Issue by WGRINGO** [allegro/allegro-api#8745]
Witam.

Jak mogę założyć dwa produkty w katalogu Allegro z tym samym EANem
Przykładowy EAN takiego produktu jest w katalogu produkcyjnym ALLEGRO:
5900280933102

Potrzebuję zrobić to samo na sandboxie, ale za każdym razem dostaję odpowiedź że produkt już istnieje i nie zgadza się kod producenta który w jednym przypadku to: "1566833", a w drugim  "C47-OS1-ST6K".
![image](https://github.com/allegro/allegro-api/assets/46341708/137dff46-a4e8-42ee-930a-5e3d8327c20e)

Potrzebuję przetestować taką sytuację w mojej aplikacji i muszę mieć przypadek 1:1 bo u klienta coś nie działa.
A może  jest jakaś możliwość by przenieść towar z katalogu Allegro do sandboxa by móć testować inne przypadki lub przynajmniej request by poszedł do produkcyjnego katalogu zmiast sandboxowego ?

**Comment by Lukasz-Zurek** [comment]
> Jak mogę założyć dwa produkty w katalogu Allegro z tym samym EANem Przykładowy EAN takiego produktu jest w katalogu produkcyjnym ALLEGRO: 5900280933102

Niestety w kategorii (257007), w której utworzony został produkt, identyfikujemy go m.in. na podstawie wskazanego EANu, więc obecnie (gdy będziesz wskazywał ten sam EAN) będziemy zwracać Tobie duplikat, sugerując, aby skorzystać z produktu, który jest już w naszym katalogu produktów.

> 
> Potrzebuję przetestować taką sytuację w mojej aplikacji i muszę mieć przypadek 1:1 bo u klienta coś nie działa. A może jest jakaś możliwość by przenieść towar z katalogu Allegro do sandboxa by móć testować inne przypadki lub przynajmniej request by poszedł do produkcyjnego katalogu zmiast sandboxowego ?

Niestety nie ma takiej możliwości.

**Comment by WGRINGO** [comment]
No i co teraz? Jak mogę przetestować powyższy przypadek ? Co sugerujecie zrobić?

**Comment by Lukasz-Zurek** [comment]
@WGRINGO Domyślnie staramy się nie przyjmować produktów na identycznych EANach, nawet jeśli to różne wersje kolorystyczne tego samego produktu, więc trudno będzie mi Tobie zasugerować skuteczne rozwiązanie, które teoretycznie miałoby omijać nasze domyślne reguły.

**Comment by WGRINGO** [comment]
Ok "staramy się nie przyjmować" się, ale w katalogu Allegro są takie przypadki i klient nie może utworzyć poprawnie aukcji bo ma błędy w stylu: Nieprawidłowy kod producenta, nieprawidłowa ilość żył w kablu itd. Przez to nie potrafi naszą aplikacją wystawić aukcji i zrzuca problem na nas.
Poza tym moje to jak to zostało utworzone w produkcyjnym katalogu allegro to czemu nie można i sandboxie ?

**Comment by Lukasz-Zurek** [comment]
W przypadku tych konkretnych produktów z EAN: 5900280933102 - zostały one utworzone w 2021 roku, czyli dość dawno temu. Pisząc "staramy się nie przyjmować produktów na identycznych EANach" mam tu na myśli obecną sytuację i zasady obowiązujące w naszym serwisie.

Dodam, że w naszym API zwracamy różnego rodzaju błędy związane z katalogiem produktów. Tutaj najlepiej jak podasz konkretny przykład, abym mógł go zweryfikować. Być może ten błąd leży po naszej stronie. 

Czasami jednak nasz system zwraca duplikat, tj. istniejący już w naszej bazie produkt, który różni się parametrami. Jeżeli te parametry produktu są błędne, udostępniamy możliwość zgłoszenia takich błędów w naszym API, za pomocą [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal).

Jest jeszcze jedna istotna kwestia - na podstawie niektórych parametrów, identyfikujemy istniejący produkt. Jeżeli ten proces również nie działa po naszej stronie zgodnie z oczekiwaniem, staramy się go optymalizować na bieżąco, dlatego jeśli posiadasz tutaj również przykładowe żądania - chętnie je zweryfikuję.

**Comment by WGRINGO** [comment]
Tylko mi nie chodzi o to. Problem jest taki, że macie dwa środowiska: Produkcyjne i SANDBOX. Klientowi coś nie działa na środowisku produkcyjnym, a ja nie jestem w stanie odtworzyć tej sytuacji na SANDBOXIE.
Ciężko diagnozować coś czego nie da się odtworzyć, a tu właśnie mamy taką sytuację - zapytanie o EAN zwraca dwa produkty różniące się w przypadku kabla ilością żył:

![image](https://github.com/allegro/allegro-api/assets/46341708/da16cbad-2275-40cc-8711-601302473a1f)

Chodzi mi o możliwość stworzenia w katalogu produktów takiej samej sytuacji jaka jest na środowisku produkcyjnym. To że odchodzicie od takich sytuacji to inna sprawa, ale dopóki jest to dostępne na środowisku produkcyjnym to u klientów aplikacja nie zachowuje się zgodnie z oczekiwaniem i nie ma tego jak diagnozować, klienci zwalają winę na nas bo na Allegro działa dobrze a w naszej aplikacji działa źle. No chyba, że na produkcyjnym zablokujecie również taką możliwość i wtedy nie będzie tematu (ale nie sądzę by tak się dało).

I jeszcze jedna wątpliwość do rozwiania to czy przez API można na produkcyjnym zakładać takie podwójne towary w katalogu czy taka sytuacja była możliwa do zrealizowania tylko przez samo Allegro.
Pozdrawiam :)

**Comment by Lukasz-Zurek** [comment]
Katalog produktów różni się znacząco pomiędzy środowiskiem produkcyjnym, a testowym. To dwa różne światy. Co istotne - te różnice nie są zależne od naszego zespołu, który zajmuje się tutaj publicznym API, więc niewiele mogę Tobie pomóc. Poza dostępnymi produktami, różnice występują również w identyfikacji według parametrów, a ta identyfikacja działa niezależnie, czyli zarówno gdy próbujesz utworzyć produkt na Allegro, jak również poprzez API. Potwierdzam, że te różnice bardzo utrudniają weryfikację na Sandboxie, jeśli nie uniemożliwiają.

Wskazane produkty z EANem 4044773008708 również tworzone były niemal 3 lata temu. Wszystko wskazuje na to, że przez API. Nie mogę jednak Cię zapewnić, że można obecnie na produkcji utworzyć dwa podobne produkty, bo jak wspomniałem - nasz system na to nie pozwoli, a to też jest zależne od reguł identyfikacyjnych. Z pewnością są kategorie, w których system takie żądania przepuści. Nie mamy jednak tego typu listy kategorii.

Generalnie chętnie pomógłbym Tobie w weryfikacji takich problematycznych przypadków. Nie wiem jednak na ile będę w stanie Tobie pomóc z racji technicznych ograniczeń.
