### ISSUE TITLE
Błędne przypisywanie kategorii na Allegro

### ISSUE THREAD

**Issue by DanielCyran** [allegro/allegro-api#8748]
Tytuł produktu "Olej łososiowy dla zwierząt z CBD 500 mg 10ml"

1. Produkt został wysłany przez nasz system na podstawie EAN  do prawidłowej kategorii  „Suplementy dla psów i kotów”
2. Allegro po czasie z automatu przeniosło do kategorii „Produkty konopne”  (prawdopodobnie na podstawie tytułu produktu allegro przeniosło ofertę)
3.  Następnie Allegro ponownie przeniosło ofertę do tej kategorii, którą nasz system początkowo ustawił, czyli "Suplementy dla psów i kotów"

Wina ewidentnie leży po stronie Allegro, ponieważ najpierw zmieniło kategorię na niewłaściwą, a następnie na właściwą, czyli tę, którą pierwotnie ustaliliśmy.

Ogólnie rzecz biorąc, Allegro ma problemy z API, ponieważ produkty są kategoryzowane na podstawie EAN, a zdarzają się sytuacje, w których w katalogu Allegro znajdują się produkty o tym samym EAN w kilku kategoriach. Niekiedy system wybiera najmniej oczywistą kategorię, gdzie znajdują się trzy oferty z zupełnie innymi produktami

Naturalnym podejściem powinno być dopasowywanie do kategorii, gdzie jest najwięcej produktów w katalogu Allegro z danym EAN, zamiast wybierania spośród trzech kategorii, gdzie jest najmniej produktów. Późniejsze wskazanie Allegro na błędne kategoryzowanie jest slabe.

**Comment by MartaNowaczyk** [comment]
Z tego co piszesz to nie jest kwestia problemów z API tylko kwestia ogólnych zasad dla produktów w Allegro. W tym przypadku swoje spostrzeżenia powinieneś zgłosić przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
