### ISSUE TITLE
W jaki sposób pobrać moje oferty?

### ISSUE THREAD

**Issue by prestt** [allegro/allegro-api#8749]
W poradniku:

https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase

jest informacja, aby użyć zasobu /sale/offers, jednak po jego użyciu na produkcji zwracany jest taki link:

https://developer.allegro.pl/news/na-poczatku-2024-roku-wylaczymy-zasoby-sale-offers-sluzace-do-tworzenia-i-edycji-ofert-BvqK3XOaEcW

a zasób products-offers wymaga podania offer id. Jak w takim razie mogę pobrać wszystkie moje oferty? Szukałem odpowiedzi używając lupki i np w tym wątku:

https://github.com/allegro/allegro-api/issues/8430

sugerujecie użyć /sale/offers, w dokumentacji też nie ma żadnego info o tym, że zasób jest zablokowany:

https://developer.allegro.pl/documentation#operation/searchOffersUsingGET

a na sandboxie ten zasób normalnie działa. Jaka jest zatem prawidłowa metoda na pobranie wszystkich moich ofert?

**Comment by MartaNowaczyk** [comment]
Zasób [GET /sale/offers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET) nie jest zablokowany i to właśnie on służy do pobierania listy ofert.

**Comment by prestt** [comment]
Pani Marto faktycznie - ten link był na szczegółach oferty, a nie na /sale/offers, czyli /sale/offers do pobrania ofert, /sale/product-offers/{offer_id} do szczegółów oferty, sorry za zamieszanie :)
