### ISSUE TITLE
Aktywacja konta firmowego sandbox

### ISSUE THREAD

**Issue by abcmeble** [allegro/allegro-api#875]
Bardzo proszę o aktywowanie konta firmowego:
sklepabcmeble
Symulacja płatności nadal nie działa.

**Comment by PawelTaberski** [comment]
Wstępnie zaakceptowałem Twoje konto, aby dokończyć aktywację przejdź do zakładki moje konto w Moim Allegro i wyślij do nas dokumenty do weryfikacji (jakieś dowolne pliki) aby zakończyć proces.

**Comment by abcmeble** [comment]
Dziękuję bardzo za pomoc
