### ISSUE TITLE
Does Allegro have an attachment size limit at the time of upload in the allegro message center?

### ISSUE THREAD

**Issue by andreinacuellor** [allegro/allegro-api#8750]
Hi,

I would like to call the resource https://api.{environment}/messaging/threads/{threadId}/messages to get the messages per thread with attachments integrating with Salesforce.
I can see that the attachment comes with the following parameters:
"fileName": "image.png",            - file name
"mimeType": "image/png",            - file type
"url": "https://upload.allegro.pl/message-center/message-attachments/97dc0b60-2da4-4247-92ba-b748630ba0f6", - file URL address
"status"

Is that URL a public link that I can download and save in Salesforce? 
In Salesforce there is a limit of 2GB per attachment, Does Allegro have limit in the attachment size?

**Comment by MartaNowaczyk** [comment]
This is not a public link to download the attachment, but exactly with this resource you can download it through the API. 
The maximum file size is 5MB.

**Comment by andreinacuellor** [comment]
Using this resource: GET https://api.{environment}/messaging/message-attachments/{attachmentId} ?

the Content-Disposition and Content-Type responses return what type of data?

**Comment by MartaNowaczyk** [comment]
the Content-Disposition returns attachment information e.g. `attachment; filename="=?UTF-8?Q?name.jpg?="; filename*=UTF-8''name.jpg`
the Content-Type returns attachment type: `image/png`, `image/gif`, `image/bmp`, `image/tiff`, `image/jpeg`, `application/pdf`.
