### ISSUE TITLE
Aktywacja/potwierdzenie konta sandbox

### ISSUE THREAD

**Issue by KrzysztofPlachta** [allegro/allegro-api#8751]
Prosze o aktywacje nowego konta testowego na srodowisku sanbox:
krzysztof.plachta771@gmail.com

**Comment by MartaNowaczyk** [comment]
Podane konto to konto zwykłe (kupującego), ale brakuje w nim podstawowych danych jak imię, nazwisko i adres. Uzupełnij te dane, a później możesz zrobić aktywację przy pierwszej transakcji.

**Comment by KrzysztofPlachta** [comment]
Dane uzupełnione , aktywacja wykonana

**Comment by MartaNowaczyk** [comment]
Na koncie krzysztof.plachta771@gmail.com nadal nie widzę uzupełnionych danych.

**Comment by KrzysztofPlachta** [comment]
prosze o info czy teraz jest ok

**Comment by MartaNowaczyk** [comment]
Jest ok, aktywowałam Twoje konto.
