### ISSUE TITLE
Problem z wygenerowaniem i odświeżeniem tokenu

### ISSUE THREAD

**Issue by SzymonZasada** [allegro/allegro-api#8753]
Cześć
Od wczoraj mam problem z odświeżaniem i generowaniem tokenu. Dostaje 
`400 Bad Request from POST https://allegro.pl.allegrosandbox.pl/auth/oauth/token`
gdzie stało się to z dnia na dzień.
Dotyczy to wszystkich kont oraz apliakcji. 
Czasy:
2024-03-29T08:46:37.812+01:00
2024-03-29T08:46:37.914+01:00
2024-03-29T08:46:38.026+01:00
2024-03-29T08:46:38.119+01:00

Dla kont na allegro sandbox motor-expert oraz motor-expert2

**Comment by SzymonZasada** [comment]
Spróbowałem, odświezyć token, ale dostaje bład refresh tokena, którego otrzymalem godzine wczesniej

**Comment by MartaNowaczyk** [comment]
W tym wypadku najlepiej będzie jak podeślesz nam przykłady i po kolei opiszesz jakie dane nam przekazujesz. Prześlij je przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) i w zgłoszeniu dopisz GitHub #8753.
