### ISSUE TITLE
Nie mogę wystawić produktu na słowackim i czeskim rynku na Sandboxie

### ISSUE THREAD

**Issue by pawelcudowski** [allegro/allegro-api#8754]
Po próbie udostępnienia na jeden z tych rynków, otrzymuję odpowiedź:
Nie można wystawiać ofert B2B, C2C i charytatywnych poza allegro.pl.
Konto pawelcudowski

**Comment by PrzemyslawLukanowski** [comment]
Wygląda to na problem z Twoim kontem, które od 2020 nie zostało ostatecznie zweryfikowane jako firmowe. W takiej sytuacji, niestety, ale musisz zarejestrować nowe konto - nasze mechanizmy związane z weryfikacją zmieniły się od tego czasu i nie mamy już możliwości aktywacji i weryfikacji tego konta.

**Comment by pawelcudowski** [comment]
W związku z tym proszę o aktywację konta:
test_api_allegro@interia.pl,
abym mógł przetestować działanie na rynkach zagranicznych

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.
