### ISSUE TITLE
Wyszukiwanie produktów /sale/products

### ISSUE THREAD

**Issue by Morph21** [allegro/allegro-api#8755]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Witam, mamy dwa problemy związane z wyszukiwaniem produktów:

1. Na sandbox nie pobiera nam produktów wyszukując po frazie jeżeli dana fraza zawiera polskie znaki.
Nie wiem czy coś źle przesyłamy czy brakuje jakiejś informacji o tym w dokumentacji.

Fraza: "BIAŁA BLUZKA DAMSKA KRÓTKA"

Zapytanie jest tworzone z następującymi parametrami: ( nie wiem czy powinniśmy tutaj robić encoding frazy czy nie)
"phrase" -> "BIA%C5%81A+BLUZKA+DAMSKA+KR%C3%93TKA"
"language" -> "pl-PL"

W zwrotce dostajemy status 200 i brak wyników.

2. Nie da się ograniczyć listy zwracanych produktów więc zawsze przychodzi minimum 30, w dokumentacji nie ma o tym wzmianki więc zakładam że tak to aktualnie funkcjonuje i nie jest to błąd. Czy była by możliwość rozszerzenia tego endpointu o parametr limit aby pobrać mniejszą ilość produktów?

**Comment by PrzemyslawLukanowski** [comment]
Co do pierwszego problemu, to nie udało mi się powtórzyć tego błędu, wyniki dostaję zarówno dla frazy bez, jak i z encodingiem. Czy możesz podać trace-id Waszego wywołania? Zobaczę, w jakiej postaci otrzymujemy to zapytanie. 
Jeśli chodzi o kwestię dodania dodatkowego parametru, zachęcam Cię do założenia sugestii w zakładce [Discussion](https://github.com/allegro/allegro-api/discussions), w której zbieramy wszelkie pomysły na rozwój API.

**Comment by Morph21** [comment]
trace-id:
159a451e09117d50

**Comment by Morph21** [comment]
Z tego co widzę to wymagacie jakiegoś konkretnego kodowania. Bez żadnego kodowania nie zwracacie wyniku co można łatwo sprawdzić wywołując zapytanie poprzez curl. Gdy zostanie wywołane zapytanie z postmana lub innych programów ono jest domyślnie kodowane w domyślny sposób danego softu. Przykład:

```curl -H "Authorization:Bearer Wstaw_tutaj_token" -H "Accept:application/vnd.allegro.public.v1+json;charset=UTF-8" -X GET 'https://api.allegro.pl.allegrosandbox.pl/sale/products\?phrase=Biała'
```

Zwraca

{"code":"-","message":"Bad Request","destination":{"serviceTag":null,"host":null,"path":null,"originalDst":null},"details":{"connectionId":4345354}}


Zmiana literki "ł" na "l" powoduje zwrotkę z waszego systemu prawidłową.

Domyślnie jest wymagane aby url był zakodowany tak żeby nie miał spacji i kilku innych znaków.
I to nasze oprogramowanie akurat robi domyślnie, jeżeli chcemy zakodować dodatkowo jakiś parametr dla polskich znaków robimy to per parametr. Co oznacza że kodujemy ręcznie dany parametr a następnie oprogramowanie które wysyła zapytanie koduje cały url, dlatego podwójne kodowanie jest tam widoczne.

Tak więc nie można wysłać polskich znaków do allegro bez zakodowania ich jako część url-a

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za tę sugestię, dodamy taką informację na poziomie naszego poradnika.
