### ISSUE TITLE
Weryfikacja klucza API

### ISSUE THREAD

**Issue by Mujoku** [allegro/allegro-api#8756]
Cześć! 
Jakieś 3 tygodnie temu zgłosiłem się z prośbą o weryfikacje klucza. Dostałem w ciągu 30 minut odpowiedź, że prośba została przekazana i podałem szczegółowy opis działania aplikacji. Do dziś cisza. Czy to powinno trwać tak długo?

`{'errors': [{'code': 'VerificationRequired', 'message': 'Access is denied. Verification is required.', 'details': None, 'path': None, 'userMessage': 'No access to the specified resource. Access is possible only for verified applications.'}]}
Failed to fetch offers.
No offer to display.`

Chodzi oczywiście o zasób _offers/listing_

**Comment by MartaNowaczyk** [comment]
Cześć, na tym forum nie zajmujemy się weryfikacją aplikacji dla GET /offers/listing i nie mamy wglądu w jego proces. To pytanie powinno trafić tam gdzie je pierwotnie zadałeś, czyli w kontynuacji korespondencji o dostęp o której piszesz.
