### ISSUE TITLE
Not getting get orders response from Allegro?

### ISSUE THREAD

**Issue by mohan-mandal-pattern** [allegro/allegro-api#8758]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

We are using fetch API to request orders from Allegro to get the response back but now it is not giving the response back. Is there something that happened on your side that we are facing this issue?

**Comment by Lukasz-Zurek** [comment]
If it is possible, please give me a trace-id. I will check it closely.
