### ISSUE TITLE
Refresh token to get all disputes

### ISSUE THREAD

**Issue by andreinacuellor** [allegro/allegro-api#8759]
Hi,

I have been using the refresh token to use all the resources in the message center but when I tried to use it in Disputes, it didn't work. Isn't possible to use refresh token with disputes? if not, how long does the normal token last?

**Comment by Lukasz-Zurek** [comment]
If you want to use our resources, you will always have to use an access_token which is valid for 12 hours. I guess you have written about token refreshing/extending process and using of access_token after refreshing it (generating a new pair of tokens). The token may have already expired while you have been trying to use it in Disputes resources.

**Comment by andreinacuellor** [comment]
No, i have been using the refresh_token to use the resources in Message Center and it has been working fine, but when I tried to use it with Disputes, it didn't work. 
I have been using refresh_token because this question I did: https://github.com/allegro/allegro-api/issues/8698

**Comment by Lukasz-Zurek** [comment]
Refresh token is for extending an access token. While using the resources, you have to use an access token. Maybe you wrote about refreshed (via refresh token) access token. If we return an error, apparently you are using an access token which has been already terminated.

To verify it closely, I will need a trace-id and a full request (with a token), which you can send using our [contact form](https://allegro.pl/pomoc/kontakt). Please add an information that your message relates to #8759 thread.

**Comment by andreinacuellor** [comment]
it is because the integration I need to do needs to be in the back end without the user interaction, but all the message center and dispute resources don't work with the authorization server to serve, so I need to use the authorization code flow, and previously I was told that I could run once the authorization with the user interaction and continue using the refresh token.

**Comment by andreinacuellor** [comment]
In the authorization code flow i was using the refresh_token
{
    "access_token": "xxxxxxxxXXX",
    "token_type": "bearer",
    "refresh_token": "xxxxxxxxXXX",
    "expires_in": 43199,
    "scope": "allegro:api:orders:read allegro:api:profile:read allegro:api:sale:settings:read allegro:api:payments:read allegro:api:disputes allegro:api:shipments:read allegro:api:sale:offers:read allegro:api:messaging",
    "allegro_api": true,
    "iss": "https://allegro.pl.allegrosandbox.pl",
    "jti": "xxxxxxxx"
}

**Comment by Lukasz-Zurek** [comment]
> it is because the integration I need to do needs to be in the back end without the user interaction, but all the message center and dispute resources don't work with the authorization server to serve, so I need to use the authorization code flow, and previously I was told that I could run once the authorization with the user interaction and continue using the refresh token.

Yes, you were correctly instructed by my colleague. Please send me some trace-ids, I will try to verify it closely.

> In the authorization code flow i was using the refresh_token { "access_token": "xxxxxxxxXXX", "token_type": "bearer", "refresh_token": "xxxxxxxxXXX", "expires_in": 43199, "scope": "allegro:api:orders:read allegro:api:profile:read allegro:api:sale:settings:read allegro:api:payments:read allegro:api:disputes allegro:api:shipments:read allegro:api:sale:offers:read allegro:api:messaging", "allegro_api": true, "iss": "https://allegro.pl.allegrosandbox.pl", "jti": "xxxxxxxx" }

Ok, that's good. You should use the process which we described [here](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#extending-token-validity). But I am still wondering why and what kind of error do you receive, so I will need more data/details.

**Comment by andreinacuellor** [comment]
Sorry, i think i made a mistake, now the refresh token is working with resources for disputes as well, thanks
