### ISSUE TITLE
Zgłaszenie ofert do StrefyOkazji

### ISSUE THREAD

**Issue by pfunkowski** [allegro/allegro-api#876]
Czy jest możliwość zgłaszania i zdejmowania ofert do wyróżnień (strefa okazji) poprzez restApi

**Comment by PawelTaberski** [comment]
Możesz zarządzać opcjami promowania, przy pomocy sekcji "promotion", więcej na ten temat [tutaj](https://developer.allegro.pl/sale/#similar-offer).

**Comment by pfunkowski** [comment]
Nie wiem czy dobrze wytłumaczyłem problem, chodzi mi o:
https://allegro.pl/dla-sprzedajacych/wyroznij-swoje-oferty-specjalnym-oznaczeniem-na-listach-ofert-z-okazji-black-week-i-nie-tylko-z8eYgE9Xefk
Udostępniony link wskazuje na:
    "promotion": {                              --  niewymagane, opcje promowania,
                                                przy każdej z opcji należy wybrać 
                                                jedną z wartości: false (opcja nieaktywna); 
                                                true (opcja aktywna)
        "emphasized": true,                     -- wyróżnienie
        "bold": false,                          -- pogrubienie
        "highlight": false,                     -- podświetlenie
        "departmentPage": false,                -- oferta promowana na stronie kategorii
        "emphasizedHighlightBoldPackage": false -- pakiet promowania: wyróżnienie,
                                                podświetlenie i pogrubienie oferty
    },

**Comment by PawelTaberski** [comment]
Nie obecnie przez REST API możesz przypisać tylko oznaczenie na listingu odnośnie rabatów ilościowych. Więcej na ten temat [tutaj](https://developer.allegro.pl/offer_bundles/#10) innych chwilowo nie ma.
