### ISSUE TITLE
Recomendation of Allegro API best practices

### ISSUE THREAD

**Issue by andreinacuellor** [allegro/allegro-api#8760]
Hi,

I am trying to do an integration between Salesforce and Allegro through your Allegro API. The idea is to be able to respond to all the messages from Allegro Messages Center and Discussions from Salesforce, and create threads and discussions as a case is Salesforce. I just want to know if you have any advice of best practices when using Allegro API.

Thank you.

**Comment by Lukasz-Zurek** [comment]
We cannot recommend any best practices as preparing an integration is strictly up to you and your needs. We do not interfere into this process.

But obviously if you have any specific questions regarding our resources and information which we return in the responses, please let me know.
