### ISSUE TITLE
Statusy zamówień - Anulowane

### ISSUE THREAD

**Issue by jesiiu** [allegro/allegro-api#8761]
Witam, 
Opierając się na dokumentacji Allegro Api wywnioskowałem, że zamówienia mogą mieć takie statusy:

> BOUGHT - klient kupił, ale jeszcze nie zapłacił za zamówienie.
> FILLED_IN - zdarzenie z takim typem może pojawić się więcej niż raz, jeśli klient wypełni FOD kilka razy np. gdy nie zakończy płatności lub doszło do jej anulowania. Pamiętaj, że przy tym statusie mogą zmienić się dane, aż do czasu zakończenia płatności.
> READY_FOR_PROCESSING - klient wypełnił [FOD](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/czym-jest-formularz-dostawy-i-platnosci-D5AgVlYv8tq) i sfinalizował płatność (status: zakończona), albo wybrał płatność przy odbiorze lub odbiór osobisty. Dopiero w tym statusie zobaczysz adres dostawy jaki klient podał na FOD. Jeśli otrzymasz ten status, masz pewność, że w danych na FOD nic się już nie zmieni. Dlatego możesz:
> pobrać jego szczegóły,
> sprawdzić czy zgadza się kwota płatności,
> przejść do kolejnych kroków realizacji zamówienia.
> BUYER_CANCELLED - kupujący anulował zamówienie.
> FULFILLMENT_STATUS_CHANGED - oznacza zmianę statusu realizacji zamówienia przez sprzedającego.
> AUTO_CANCELLED - zamówienie zostało automatycznie anulowane przez Allegro.

Dzisiaj okazało się, że otrzymaliśmy zamówienie w statusie "CANCELLED" - nigdzie takiego statusu nie widzę w liście obowiązujących statusów przez co anulowane zamówienie zostało wysłane do klienta. I tu zmierzamy do kolejnego punktu problemu - dla zamówienia które było anulowane - na allegro widnieje informacja przy zamówieniu KUPUJĄCY ANULOWAŁ, utworzyła się etykieta wysyłkowa którą wygenerowaliśmy w Managerze Paczek, dnia 28.03 otrzymałem informację na czacie allegro, że - 

> Dziękuję za czas oczekiwania. Jeśli oznaczą Państwo ze swojej strony zamówienie jako anulowane, to
> jest ono zaciągane przez menagera paczek. Narzędzie inpostu nie zaciąga jedynie tych zamówień,
> które fizycznie zostały anulowane przez samego kupującego.

Jeżeli dobrze rozumiem to dla zamówień anulowanych przez klienta/allegro nie powinno być możliwości utworzenia etykiety wysyłkowej a jednak dla tego zamówienia udało się taką etykietę wygenerować i w tym momencie anulowane zamówienie pojechało do klienta.

Mógłbym prosić o jakieś wyjaśnienie tej sytuacji i ewentualne wyjaśnienie lub dopowiedzenie jakie jeszcze statusy mogą się pojawić i jak możemy uniknąć takich sytuacji w przyszłości?

**Comment by MartaNowaczyk** [comment]
Menager Paczek jest poza API, więc jeśli obsługa Allegro miała informację o zamówieniu i zweryfikowała jego stan, to ich odpowiedź powinna być wystarczająca. 
Statusy o których piszesz są w dzienniku zdarzeń zamówień. Status "CANCELLED" jest [w samych zamówieniach](https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET) i tam mamy status zamówienia `status` i status realizacji zamówienia `fulfillment.status` - jeśli to ten status, to jest to pewnie to co dostałeś w odpowiedzi od obsługi Allegro. 
Nie wiem czy piszesz o zdarzeniach czy o statusie zamówienia, dlatego proszę podaj trace-id gdzie zwracamy według Ciebie niepoprawny status. Możesz też przesłać request i response w formacie JSON przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem jakiego wątku na GH to dotyczy.

**Comment by jesiiu** [comment]
Status cancelled otrzymałem w polu "status" nie "fulfillment.status", no ale tak jak podesłałem cytat z dokumentacji nie jest on tam opisany, a status CANCELLED który otrzymałem od Pani w odpowiedzi jest dopiero określony w parametrach które mogę wysłać w zapytaniu. Wydaje mi się, że powinien być on uwzgledniony wraz z innymi statusami.

Co do managera paczek, to nadal nie rozumiem dlaczego utworzyła się przesyłka skoro zamówienie ma status Anulowane przez kupującego gdzie cytując raz jeszcze 

> Narzędzie inpostu nie zaciąga jedynie tych zamówień,
> które fizycznie zostały anulowane przez samego kupującego.

**Comment by MartaNowaczyk** [comment]
W dokumentacji jest odpowiedni status: 
![image](https://github.com/allegro/allegro-api/assets/38425363/0ea0da6b-d9f3-418b-9f9f-3e778507e7e8)
Jeśli sprawa dotyczy Managera Paczek, to powinieneś ją kontynuować w poprzedniej korespondencji z obsługą Allegro. Tam powinieneś otrzymać wyjaśnienia dlaczego tak się stało.
Jeśli jednak uważasz, że API zwraca nieprawidłowe dane i przez to wydarzyła się taka sytuacja, podeślij konkretny przykład trace-id, request i response w formacie JSON, czy chociaż numer zamówienia, bo w tym momencie nie mam nawet jak tego sprawdzić.

**Comment by jesiiu** [comment]
1. ID Zamówienia - 5a2a0cd0-ec53-11ee-8ba8-f505429739df - zamówienie dotyczące managera paczek

2. Tak w dokumentacji jest odpowiedni status, ale jest on w sekcji "QUERY PARAMETERS" - w miejscu w którym znajdują się parametry które można przesłać do serwera żeby otrzymać zamówienia w wybranym przez siebie statusie. 
![cannceled](https://github.com/allegro/allegro-api/assets/22199603/9dfc5f36-6160-4557-99a2-a6dfb7427c52)
Podsyłam screen z dokumentacji Allegro API opisującej flow obsługi zamówień i wydaje mi się, że warto było by zawrzeć ten status w tym miejscu również, skoro ów taki występuje :)

**Comment by MartaNowaczyk** [comment]
1. Zamówienie zwraca: `"status": "CANCELLED",` w zdarzeniach też widać poprawny typ `"type": "BUYER_CANCELLED"` (to jest to z Twojego zrzutu) także wygląda na to, że było anulowane przez kupującego i była w API taka informacja. Nie widzę tu nieprawidłowości ze strony API. Dlaczego w Managerze Paczek tak to zadziałało, to już nie mój obszar kompetencji, więc tutaj odeślę do korespondencji, którą wcześniej prowadzono w tej sprawie.
2. W szczegółach zamówienia jest ten status - widać go również w response. Nie będziemy zmieniać opisu, bo z dokumentacją wszystko się zgadza. 
![image](https://github.com/allegro/allegro-api/assets/38425363/c07b009d-8577-4ecf-98d3-fbf199c03bfc)

**Comment by jesiiu** [comment]
> Zamówienie zwraca: "status": "CANCELLED", w zdarzeniach też widać poprawny typ "type": "BUYER_CANCELLED" (to jest to z Twojego zrzutu) także wygląda na to, że było anulowane przez kupującego i była w API taka informacja. Nie widzę tu nieprawidłowości ze strony API. Dlaczego w Managerze Paczek tak to zadziałało, to już nie mój obszar kompetencji, więc tutaj odeślę do korespondencji, którą wcześniej prowadzono w tej sprawie.

Dobrze to prosiłbym o informację zwrotną w tej kwestii tylko

Co do drugiego no to nie ma problemu, chciałem tylko zwrócić uwagę, że taka sytuacja występuje

**Comment by MartaNowaczyk** [comment]
Trochę się nie zrozumieliśmy. Musisz sam to wyjaśnić w korespondencji, którą wcześniej prowadziłeś lub rozpocząć nową - ja do Twoich wiadomości nie mam dostępu.
