### ISSUE TITLE
Aktywacja konta testowego [SANDBOX]

### ISSUE THREAD

**Issue by Puszekokruszek123** [allegro/allegro-api#8762]
Zweryfikowałem konto bankowe symulatorem płatności, 
Wysłałem żądane dokumenty do weryfikacji Firmy.
Czy mogę prości o pełną aktywację konta **PuszekOkruszek** ?

**Comment by Lukasz-Zurek** [comment]
@Puszekokruszek123 Aktywowałem wskazane konto.
