### ISSUE TITLE
API troble with DPP and WEDO label informations

### ISSUE THREAD

**Issue by MSfastcr** [allegro/allegro-api#8764]
Hello ,

I would like to ask you for help me with our troubles with Get Shipment. 

We call allegro to register Shipment, but we receive that Client is temporary unavailable . 

Could you please help? It in case DPD and We/DO - Alza Box , with Packeta is everything OK.

**Comment by Lukasz-Zurek** [comment]
@MSfastcr Hello.

Please give me a trace-id of the request. We will look at this.

**Comment by MSfastcr** [comment]
Shipment ID 0121c096-f7a6-41b4-8bb4-1c59c723ae37

**Comment by Lukasz-Zurek** [comment]
@MSfastcr Thank you, but unfortunately I cannot find this shipment. If it is possible, please send me a trace-id of this request.

**Comment by MSfastcr** [comment]
Hello sorry i can not have these id. I have only Command ID , but i thing it can not help you.

**Comment by Lukasz-Zurek** [comment]
@MSfastcr I have checked this ID 0121c096-f7a6-41b4-8bb4-1c59c723ae37 and could not find it in our logs. We have logs only from the last 14 days.

**Comment by MSfastcr** [comment]
Hello, would like to ask you which DPD we should use for DPD smart delivery? In API we have few options like :
Allegro Kurier DPD
Allegro Kurier DPD Czechy
Allegro Kurier DPD Czechy pobranie

It should be that we are calling wrong DPD account. Could you please let us know ID of DPD which we should use?

**Comment by Lukasz-Zurek** [comment]
You can find more details about DPD smart delivery methods in Allegro Help, right [here](https://help.allegro.com/sell/en/a/allegro-dpd-courier-information-for-sellers-x5Kv3kAeBuY) or about Allegro DPD delivery methods to Czechia, [here](https://help.allegro.com/sell/en/a/allegro-dpd-pickup-and-allegro-dpd-parcel-lockers-with-dispatch-from-poland-to-czechia-K6VL2oM3Pcl). Another thing - it is more about proper delivery methods and method of settlement so If you have that kind of questions - please use our [contact form](https://allegro.pl/pomoc/kontakt). Our forum is more about API itself.

**Comment by MSfastcr** [comment]
Hi,
this is an error message from 03/27/2024 13:05
![image](https://github.com/allegro/allegro-api/assets/133961242/40ffaf30-5bac-4ae1-b146-fa37ad0e32d7)
Will it help you find the log?

Is it possible to communicate here in German?

**Comment by Lukasz-Zurek** [comment]
Ok, I understand. But it will be difficult to verify this specific case as I have tried to find commandId: c663e2d9-3f9f-4581-a037-9c8330ff8fab but without any success. I am not sure right now if you are using our [Allegro API](https://developer.allegro.pl/documentation).

If you are using it, I will need is a trace-id/and full request.

We do not communicate here in German.

**Comment by MSfastcr** [comment]
Yes, we use the Allegro API.
We received this response:
{"commandId":"55d4d450-6464-4ebb-9481-d01461f03c7f","status":"ERROR","errors":[{"code":"CARRIER_API_CLIENT_UNAVAILABLE","message":"Carrier Api Client is temporary unavailable - try again later or report problem","details":"Carrier Api Client is temporary unavailable - try again later or report problem","path":null,"userMessage":"API przewoźnika jest tymczasowo niedostępne. Ponów próbę później."}],"shipmentId":null}

![image](https://github.com/allegro/allegro-api/assets/133961242/6e7c5972-3c78-4d5b-a8a4-9a51765f383f)

**Comment by Lukasz-Zurek** [comment]
@MSfastcr Thank you! This is a correct commandId which I have just found. I have forwarded this case to another department. Please be patient. I will be back with some more details.

**Comment by Lukasz-Zurek** [comment]
@MSfastcr The problem is the fact that you are not providing any value in the **sender.streetNumber** field.

On the other hand we have returned an incorrect error message, so we are working on it and it should be corrected soon.

**Comment by MSfastcr** [comment]
Thanks for your answer.
We check the data we send.

**Comment by MSfastcr** [comment]
Hello,
We adjusted the settings of the data sent according to the Allegro API. Tests look good.
Today we found out that sender.streetNumber is newly required for the WEDO carrier. Unfortunately, I couldn't find any info about it.
Are there any other changes planned?
Thank you

**Comment by Lukasz-Zurek** [comment]
@MSfastcr We are not planning any changes in the Ship with Allegro changes in the upcoming future, but if so - we will inform about it in [our news](https://developer.allegro.pl/news).

**Comment by MSfastcr** [comment]
Hi,
can you help me check if there were any outages on the Allegro side today?
We received a 500 error while communicating, but there was no outage on our end.
The date is 23/04/2024 and the time is approx. 13:00
Thank you.

**Comment by MSfastcr** [comment]
Sorry, additional:
code: 500 - message: Internal Server Error

**Comment by Lukasz-Zurek** [comment]
@MSfastcr Do you have any trace-ids? We haven't noticed any major problems on this date, but having more details will be useful for further investigation.
