### ISSUE TITLE
Sandbox account activation

### ISSUE THREAD

**Issue by DHSC1** [allegro/allegro-api#8765]
Hello,
I am contacting you with a request to activate a sandbox account for login: test_SC_shoptet

**Comment by kamilkodzi** [comment]
Hi, Please activate my account too <3:
gs-rr-test

best regards,
Kamil

**Comment by MaciejFrackowiak** [comment]
@DHSC1 Your account is active now.

**Comment by MaciejFrackowiak** [comment]
@kamilkodzi You have to make a bank transfer (using our payment simulator) and send us company documents (any files) to confirm your registration. You can do it in the [Account information](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) tab.

**Comment by kamilkodzi** [comment]
@MaciejFrackowiak just send documents and payments :)

**Comment by MaciejFrackowiak** [comment]
@kamilkodzi Done!
