### ISSUE TITLE
SMART logistics channel connected to Allegro platform

### ISSUE THREAD

**Issue by 13413409629** [allegro/allegro-api#8769]
Our warehouse is in Poland
We want to open the SMART logistics channel of the Allegro platform
How should we contact the logistics personnel of the Allegro platform for docking?
Or where do we need to connect to the logistics channels of the Allegro platform?

**Comment by MartaNowaczyk** [comment]
Here we deal with Allegro API support. Our API allows you to [send orders with SMART shipment](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV).  I realize that you may look for something else, so you can get the SMART shipping information on our [website](https://allegro.pl/dla-sprzedajacych/kategoria/allegro-smart) or contact allegro support via the [contact form](https://allegro.pl/pomoc/kontakt).
