### ISSUE TITLE
Błąd umowy przy tworzeniu listu przewozowego poczta polska

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#8770]
Otrzymujemy błąd "Niepoprawna weryfikacja utworzenia listu przewozowego: Produkt ('Przesyłka firmowa polecona (845)') nie znajduje się na umowie zawartej z Pocztą Polską S.A. . Prosił bym o informację czy faktycznie treść błędu wskazuje na dokładny problem? Czy może zaszły jakieś zmiany w tym kontekście do których było trzeba się dopasować aby utrzymać działanie wysyłki? Dodam ,że jeszcze używamy starych endpointów (parcel managment) a nie nowych (shipment managment) - również proszę o informację jeżeli to by miało powodować problem w tym przypadku.

**Comment by MartaNowaczyk** [comment]
Podaj proszę trace-id dla tego błędu. Postaram się to wtedy zweryfikować na tym konkretnym przypadku.
