### ISSUE TITLE
/offers/listing  -  przestało działać

### ISSUE THREAD

**Issue by biuronimo** [allegro/allegro-api#8772]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Cześć, 
zasób **/offers/listing** przestał działać. 
Aplikacja była pozytywnie zweryfikowana i wszystko działało. Dzisiaj dostaje odpowiedź 
Nie dostaliśmy też żadnej informacji o zmianach. 

'VerificationRequired'
'Access is denied. Verification is required.'
'No access to the specified resource. Access is possible only for verified applications.'

przykładowy **trace-id:**
**ed92d59f4ac0044a**

Proszę o weryfikację po stronie backendu.

**Comment by Mujoku** [comment]
Dostałem również informację, że dostęp do zasobu /offers/listing został wyłączony "z powodów biznesowych".

**Comment by biuronimo** [comment]
Czy mogę prosić o weryfikację czy aplikacja CLIENT ID 46d5d10cab2045b2806c3dd4003cf51d ma przydzielony dostęp?

**Comment by Lukasz-Zurek** [comment]
@biuronimo Z tego co widzę, to wskazana aplikacja nie ma dostępu do zasobu /offers/listing.

**Comment by biuronimo** [comment]
Czy mogę prosić o komentarz do tego? 
![Zrzut ekranu 2024-04-12 082830](https://github.com/allegro/allegro-api/assets/165898549/4bb3d300-cbde-418d-84e1-e8059fd31bcb)
Lub informacji kiedy pojawi się oficjalna informacja w aktualnościach dla sprzedających?

**Comment by Lukasz-Zurek** [comment]
@biuronimo Nie ingerujemy w proces weryfikacji, więc nie jestem w stanie wypowiedzieć się w tym temacie. 

Natomiast w przypadku jakichkolwiek zmian dotyczących zasobu /offers/listing, tradycyjnie poinformujemy o tym fakcie w [aktualnościach](https://developer.allegro.pl/news).
