### ISSUE TITLE
Metoda do sprawdzania/pokazywania ile osób kupiło dany przedmiot?

### ISSUE THREAD

**Issue by mrapcakratki** [allegro/allegro-api#8773]
Dzień dobry. Korzystam z wyszukiwania produktów poprzez GET /offers/listing.
Jak uzyskać poprzez API informację, ile osób kupiło dany przedmiot z danego ogłoszenia/od danego sprzedawcy?
Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Informacje te określamy w naszym Serwisie jako "popularność" i zwracamy je w polu **"popularityRange"** z przedziałami: **0, [1-5], [6-10], [11-20], [21-50], [51-100], [101+]**.

W istniejącym polu **"popularity"** zwrócimy dolną wartość danego zakresu.

Więcej informacji znajdziesz [tutaj](https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk#jak-wyszukiwac-i-przegladac-oferty).

**Comment by mrapcakratki** [comment]
Sandbox:

SŁUCHAWKI DLA DZIECI Kocie uszy Bluetooth B39 LED ----- mode: BUY_NOW ----- price: 45.00 PLN ----- popularity: 1 ----- popularityRange [1-5]

Jak interpretować taki response?

**Comment by mrapcakratki** [comment]
Dziękuję za odpowiedź. Czyli jeżeli dobrze rozumiem to dla przykładu jak pojawi się w odpowiedzi Popularity 21 i Range [21-50] to znaczy że np. 32 sztuki kupiono w tej danej ofercie?

**Comment by Lukasz-Zurek** [comment]
@mrapcakratki Dokładnie tak, 32 sztuki zakupione w ofercie będą w ten sposób określane i generalnie to może być każda liczba mieszcząca się w zakresie [21-50].

**Comment by mrapcakratki** [comment]
Mam jeszcze pytanie. Zmieniłem clientid i clientsecret z sandboxowych na produkcyjne, zmieniłem również wszystkie adresy na nie-sandboxowe. Autoryzacja przebiega pomyślnie, otrzymuję z allegro.pl API token, natomiast podczas zapytania dostaję "error.response.status 403
error.response.statusText Forbidden", gdzie i jak należy ustawić uprawienia?

**Comment by mrapcakratki** [comment]
Jeżeli należy skontaktować się z Supportem to pod który adres email?

**Comment by Lukasz-Zurek** [comment]
@mrapcakratki Dostęp do zasobów **/offers/lsiting** na środowisku produkcyjnym wymaga weryfikacji aplikacji. Jeśli jesteś w [Programie Partnerskim](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm) skontaktuj się ze swoim opiekunem. W innym wypadku skontaktuj się z nami przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). Kryteria dostępu wymieniliśmy w punkcie 3.2 naszego [regulaminu](https://developer.allegro.pl/rules).

**Comment by mrapcakratki** [comment]
Czy zestawienie 600 produktów (z offsetami co 60) dla określonego zapytania zawsze prezentuje te same rekordy tak zwane 'pierwsze z brzegu' na które natrafi zapytanie? Czy jest możliwość uzyskania szerszego zakresu?

**Comment by Lukasz-Zurek** [comment]
> Czy zestawienie 600 produktów (z offsetami co 60) dla określonego zapytania zawsze prezentuje te same rekordy tak zwane 'pierwsze z brzegu' na które natrafi zapytanie? 

Tak. Działa to analogicznie do wyszukiwarki Allegro.

> Czy jest możliwość uzyskania szerszego zakresu?

Niestety nie.

**Comment by Lukasz-Zurek** [comment]
Prócz podanych przeze mnie ścieżek kontaktowych, niestety nie jestem w stanie nic więcej zarekomendować. Proces ten jest poza naszym zespołem. Mogę jedynie zachęcić Cię do ponownego kontaktu z obsługą Allegro.
