### ISSUE TITLE
Language and Country

### ISSUE THREAD

**Issue by andreinacuellor** [allegro/allegro-api#8774]
Hi!
Is there a way to identify the language and country of the client who is writing the message or the discusion when using the Allegro API, for example:
Message Center
- List user threads
- list messages in thread
Or
Dispute:
- Get user's disputes
- Get messages within a dispute

**Comment by MaciejFrackowiak** [comment]
No, there is no method to identify language or country.

**Comment by andreinacuellor** [comment]
you have three domains, don't you? and to communicate with each of them you have to change the domain in the call, right? so I know that the message is from Poland, Czech Republic and Slovakia?

**Comment by MaciejFrackowiak** [comment]
Yes, we have a service in three countries now, but the API is one for all the marketplaces. So we do not have to switch the domain between them.

**Comment by andreinacuellor** [comment]
and in each different environment, should we create a new account to sell products?

**Comment by MaciejFrackowiak** [comment]
No, using one account you can sell on all the marketplaces. Please, read our tutorial about [the Allegro foreign marketplaces](https://developer.allegro.pl/tutorials/listing-and-managing-offers-on-foreign-marketplaces-7GndGjeAATn).

**Comment by MaciejFrackowiak** [comment]
Yes, indeed.

**Comment by andreinacuellor** [comment]
And when you use the resource to get all the disputes, is there anything that tells you about the product you are complaining about? 
curl --location 'https://api.allegro.pl.allegrosandbox.pl/sale/disputes' \
--header 'Authorization: Bearer XXXXX' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Cookie: datadome=XXXXXXXXX'

**Comment by MaciejFrackowiak** [comment]
When you [retrieve a list of disputes](https://developer.allegro.pl/documentation/#operation/getListOfDisputesUsingGET), you will get a list of them, and in the checkoutForm.id you will find an identifier of the order connected to the dispute. Then, you can get details of that order using [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET) - and you will see what single lineItems belong to that order.

**Comment by andreinacuellor** [comment]
ah yes, I see in that resource you also can retrieve the marketplace id right? that one is where the order is placed?
`"marketplace": {
"id": "allegro-pl"
},`

**Comment by MaciejFrackowiak** [comment]
Yes, in the order details, we return marketplace.id as a marketplace, where the order was placed.

**Comment by andreinacuellor** [comment]
thanks
