### ISSUE TITLE
Punkt nadania przesyłki jest niepoprawny

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#8776]
Dzień Dobry, przy próbie wygenerowania listu przewozowego z odpowiednim adresem nadania zgadzającym się z tym w umowie z pp otrzymuje błąd. trace-id: 155ccc018abc150

**Comment by MartaNowaczyk** [comment]
Według naszych logów nie przekazujesz wartości w polu pickup.pointId - widnieje tam null. Dla przesyłek Poczty Polskiej nie da się zamówić podjazdu, dlatego powinieneś wskazać odpowiedni punkt nadania.

**Comment by Maciej-Wilkosz** [comment]
Skąd mogę pozyskać odpowiednie pointId?

**Comment by MartaNowaczyk** [comment]
Nie posiadamy takiej listy.  Punkty pocztowe możesz próbować znaleźć na stronie Poczty Polskiej.
