### ISSUE TITLE
Brak zwracanego filtra stan towaru w /offers/listing

### ISSUE THREAD

**Issue by p3le** [allegro/allegro-api#8778]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Od wczoraj lub dziś (trudno określić dokładną datę) w odpowiedzi z `/offers/listing` przestaliśmy otrzymywać filtr ze stanem towaru. To samo można zaobserwować bezpośrednio na frontendzie allegro.pl w sekcji filtrów.

Proszę o informację czy jest to błąd czy stan towaru został celowo usunięty?

**Comment by Lukasz-Zurek** [comment]
Potwierdzam ten problem. Zespół odpowiedzialny za te funkcjonalności pracuje obecnie nad wdrożeniem poprawki, jeszcze w dniu dzisiejszym. 

Przepraszamy za te utrudnienia.

**Comment by p3le** [comment]
@Lukasz-Zurek uprzejmie proszę o informację zwrotną, jak problem zostanie rozwiązany.

**Comment by p3le** [comment]
Dziękuję za informację

**Comment by p3le** [comment]
Wracam ponownie z tym samym problemem: kategoria [Szampony](https://allegro.pl/kategoria/nadwozie-szampony-253265) - wg API kategoria posiada filtr "Stan", natomiast w listingu tego nie ma. Proszę o weryfikację czy zgłaszany poprzednio problem nie powrócił.

**Comment by Lukasz-Zurek** [comment]
@p3le Problemów nie odnotowaliśmy. Czy dobrze rozumiem, że filtr "Stan" dostępny i widoczny jest w API na zasobie GET /offers/listing, natomiast nie ma go w [wynikach](https://allegro.pl/kategoria/nadwozie-szampony-253265), bezpośrednio na stronie Allegro?

**Comment by p3le** [comment]
@Lukasz-Zurek odpytując API o parametry w danej kategorii po endpoincie /sale/categories/{categoryId}/parameters otrzymuję informację o tym, że dana kategoria posiada filtr "Stan". W związku z tym, aby maksymalnie optymalizować zapytanie do /offers/listing (limity) od razu dodaję interesujący mnie filtr ze stanem towaru, aby już na etapie pierwszego zapytania do API odfiltrować interesujące mnie wyniki. API zwraca mi puste dane, bo w /offers/listing nie ma tego filtra - tutaj jest rozbieżność o którą pytam. Podział na kategorie nawigacyjne i asortymentowe nie ma znaczenia, bo odpytuję różne liście z całego drzewa i mimo że z /sale/categories/{categoryId}/parameters parametr stan przychodzi, to w /offers/listing i na froncie tego nie ma.

**Comment by Lukasz-Zurek** [comment]
@p3le Ok, rozumiem. W przypadku GET /offers/listing może się zdarzyć, że niektóre kategorie nie posiadają po prostu danego filtru (bez względu na to czy taki parametr dostępny jest w tej kategorii po odpytaniu /sale/categories/{categoryId}/parameters, czy też nie). Wszystkie dostępne filtry zwracamy w polu "filters". Czyli tutaj mamy spójność, ponieważ na listingu w Allegro również go nie ma.

**Comment by p3le** [comment]
Nie bardzo jest spójność, skoro parametry dla danej kategorii pobierane z jednego enpointa nie pokrywają się ze zwracanymi danymi z innego, tutaj /offers/listing. Do momentu odpytania listingu po API bez jakichkolwiek filtórw, nie mamy teraz pewności czy dany filtr jest dostępny czy nie, mimo że dana kategoria ma ten filtr przypisany...

**Comment by Lukasz-Zurek** [comment]
Zasób GET /sale/categories/{categoryId}/parameters zwraca wszystkie dostępne (w ramach wskazanej kategorii) parametry, których można użyć w procesie wystawiania, etc. Natomiast w przypadku GET /offers/listing - parametry udostępniamy wyłącznie w formie filtrów, dzięki czemu można zawęzić wyniki wyszukiwania. I tu co istotne - brak danego parametru wśród dostępnych w danej kategorii filtrów - nie jest błędem. Nie każdy parametr może występować jako filtr.
