### ISSUE TITLE
Endpoint offers/listing zaczął ignorować filtrowanie po nowych produktach

### ISSUE THREAD

**Issue by stud3nt** [allegro/allegro-api#8779]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Użyte zapytanie:

offers/listing?include=all&searchMode=REGULAR&sellingMode.format=BUY_NOW&fallback=false&limit=60&offset=60&category.id=7&phrase=pan+tadeusz&parameter.11323=11323_1

Do niedawna działało to całkowicie poprawnie, tj. zwracało wyłącznie produkty z parametrem "nowy".
Obecnie zwraca nowe i używane - tak jakby filtrowanie po parametrze było ignorowane.

**Comment by p3le** [comment]
Mogę potwierdzić, sam założyłem przed momentem ticket: https://github.com/allegro/allegro-api/issues/8778

**Comment by Lukasz-Zurek** [comment]
@stud3nt @p3le Również potwierdzam tutaj zgłaszany problem. Zespół odpowiedzialny za wyszukiwarkę pracuje obecnie nad wdrożeniem poprawki, jeszcze w dniu dzisiejszym. 

Przepraszamy za te utrudnienia.
