### ISSUE TITLE
Aukcja z EAN - błąd

### ISSUE THREAD

**Issue by FreelinePL** [allegro/allegro-api#878]
Przy próbie wystawienia aukcji z podanym EAN, jest taki oto błąd:
`Sender: Element '{https://webapi.allegro.pl/service.php}fvalueInt': '3474636612666' is not a valid value of the atomic type 'xs:int'. `
Nr EAN jest poprawny. Dlaczego API go odrzuca?

**Comment by FreelinePL** [comment]
var_dum z requesta dla odpowiedniego fid:
`{ ["fid"]=> int(337) ["fvalueString"]=> string(0) "" ["fvalueInt"]=> int(3474636612666) }`

**Comment by PawelTaberski** [comment]
Zgodnie z opisem tego fid-a powinieneś go przesłać jako string:
`               <ns1:item>
                  <ns1:sellFormId>337</ns1:sellFormId>
                  <ns1:sellFormTitle>Europejski Kod Towarowy</ns1:sellFormTitle>
                  <ns1:sellFormCat>0</ns1:sellFormCat>
                  <ns1:sellFormType>1</ns1:sellFormType>
                  <ns1:sellFormResType>1</ns1:sellFormResType>
                  <ns1:sellFormDefValue>0</ns1:sellFormDefValue>
                  <ns1:sellFormOpt>8</ns1:sellFormOpt>
                  <ns1:sellFormPos>0</ns1:sellFormPos>
                  <ns1:sellFormLength>18</ns1:sellFormLength>
                  <ns1:sellMinValue>0.00</ns1:sellMinValue>
                  <ns1:sellMaxValue>0.00</ns1:sellMaxValue>
                  <ns1:sellFormDesc/>
                  <ns1:sellFormOptsValues/>
                  <ns1:sellFormFieldDesc/>
                  <ns1:sellFormParamId>0</ns1:sellFormParamId>
                  <ns1:sellFormParamValues/>
                  <ns1:sellFormParentId>0</ns1:sellFormParentId>
                  <ns1:sellFormParentValue/>
                  <ns1:sellFormUnit/>
                  <ns1:sellFormOptions>0</ns1:sellFormOptions>
               </ns1:item>
`

**Comment by FreelinePL** [comment]
Sprawdzałem to parę razy, musiałem opisy pomylić. Faktycznie fid 337 jest jako string. Mea culpa.
