### ISSUE TITLE
Przerzucanie ofert na inny portal.

### ISSUE THREAD

**Issue by krasu11** [allegro/allegro-api#8782]
Witam,
Mam problem z przerzuceniem  większej  ilość i ofert z allegro.  Niestety przerzuca się 25 ofert i niestety na tym koniec. Jak mogę zwiększyć ilość i prędkość dodawania? Ponieważ chciałbym przerzucać po kilka tysięcy jak nie więcej ofert na raz. Czy jest u Was jakiś odgórny limit 25 ofert, bo po osiągnięciu jego przestaje się "przerzucać"? Czy można to jakoś rozwiązać? Bardzo prosiłbym o jak najszybszą odpowiedź, ponieważ bardzo zależy mi na czasie.
Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Domyślam się, że korzystasz z jakiegoś narzędzia, które wykorzystuje API Allegro - w tym momencie wszelkie wskazówki powinienneś otrzymać od autora tejże aplikacji. My jako Allegro nie limitujemy ilości kopiowanych ofert.

**Comment by krasu11** [comment]
Witam ponownie,

Niestety nadal występuje problem z integracją. To jest odpowiedź api jaka
otrzymuję. Czy jest Pan mi w stanie pomóc? Bo niestety integruje się 5
ofert i na tym koniec. A powinno ponad 7000. Wysyłam zdjęcie odpowiedzi.

Pozdrawiam!



W dniu pt., 5.04.2024 o 06:51 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
Niestety, ale nie widzę Twojego zdjęcia, o którym wspominasz.

**Comment by MaciejFrackowiak** [comment]
Możesz zamieścić bezpośrednio w wątku na GitHub.

**Comment by krasu11** [comment]
Udało mi się rozwiązać problem dodawania produktów i limitu ich dodawania.
Niestety pojawił się błąd- wszystko było dobrze i dodało się kompletne 135
produktów, a następnie produkty zaczęły dodawać się bez zdjęć. Czy jest Pan
w stanie mi z tym pomóc? Domyśla się Pan jaki może być powód, że nagle
przestały dodawać się zdjęcia, a reszta danych produktowych dodaje się
poprawnie?
Z góry dziękuję za pomoc!

W dniu wt., 9.04.2024 o 08:21 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
Niestety bez żadnych technicznych szczegółów tj. trace-id wywołania czy choćby graficznego zobrazowania problemu to nie sposób odpowiedzieć co się zadziało.

**Comment by krasu11** [comment]
Czy mógłbym prosić Pana maila, aby wszystko wysłać Panu wysłać?

W dniu śr., 10.04.2024 o 07:47 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
Komunikujemy się korzystając z ogólnodostępnego forum, aby każdy z jego użytkowników miał dostęp do wątków i mógł również udzielić wsparcia.

**Comment by krasu11** [comment]
Próbuję uzyskać rekordy z api, ale po określonej liczbie trafień api otrzymuję tylko 5 rekordów. Oraz dodatkowo tak jak pisałem wcześniej, jest problem ze zdjęciami (nagle po około 135 produktach przestały się zgrywać). Wysyłam screenshoty.

![9b0fae56-aa35-4e84-82f4-8c13db07f9f0](https://github.com/allegro/allegro-api/assets/158199941/65f46ab3-9efb-45b6-92c5-9e31639bca46)
![72def2bb-26ee-4542-a0fa-af03d15efd97](https://github.com/allegro/allegro-api/assets/158199941/64770342-4ab4-4a59-9d81-5f4cf362c8cd)

**Comment by MaciejFrackowiak** [comment]
Na podstawie samych zrzutów nie ustalę stanu faktycznego na Twoim koncie - w zakładce "Headers" znajdziesz trace-id - proszę podaj je nam.

**Comment by krasu11** [comment]
Wysyłam token id. Jeśli to nie starczy mogę wysłać jeszcze zdjęcia danych.

Token id:

Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiIxMTg5NTcwODUiLCJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6cmVhZCIsImFsbGVncm86YXBpOmJpZHMiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCIsImFsbGVncm86YXBpOm1lc3NhZ2luZyJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9hbGxlZ3JvLnBsIiwiZXhwIjoxNzEyNzY1OTU4LCJqdGkiOiI2MjI0MmQyYS0zMTcxLTQ2MzQtOWEwNS04ZmVhYmJkZTFiM2MiLCJjbGllbnRfaWQiOiIzYzQzMTIyNWRkYzE0YWE2OGY1YzAwYjFlZjYxNzFiMiJ9.LHMIQ385I1PNLiW_e0zhb4_yrcWPUMTclsGq0WMqcded_y7lcNJpmIqezAsnzKcrEZQbwjIcNbyP7XM1LXruyNDIr6zYZm0eO37_e9Bvohn2w6bmnGUUi9KtO2YMDCqUUCfUneilbHGQTjztuCpfH10T3-5m3GTVGU9hnlBW5nmYqqBJxLiT65EUVxchKEGXBo_MWnr3LyYHXWsY4XlDbEBIZXgQtoqKBmLMZykduNqQcagmFEsP23KuufZNVZGR1ptjvqacUtHznLNLskCVtcWTUagydMapVC1PuTXcDuaUNcg_GDGNHF26dLhEr6HMceSeV0aEgNDmm9PsImxysw

**Comment by MaciejFrackowiak** [comment]
Na wstępie - proszę nie umieszczaj w wątkach pełnego tokenu - to są dane wrażliwe (post edytowałem). 
Jak widzę na swoim koncie masz aktywnych 5 ofert, zatem zasób [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) zwraca właściwe dane - tam również widnieje liczba 5 przy "count" i "totalCount".

**Comment by krasu11** [comment]
Dlatego prosiłem o maila, ponieważ nie mam gdzie indziej tego Panu wysłać.
Musiałem widocznie pomylić token id. Mogę wysłać poprawny, ale gdzie? Tak,
aby było to bezpieczne.

W dniu śr., 10.04.2024 o 13:18 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
Nie są nam potrzebne Twoje kolejne tokeny - wystarczy trace-id wywołania. Jak wspomniałem wcześniej, znajdziesz go w nagłówku odpowiedzi "Headers".

**Comment by krasu11** [comment]
Witam ponownie,

Dzisiaj dostałem komunikat na koncie, że aplikacji rest api może być tylko
5 na jednym koncie allegro. Czy skoro moja była 8 to czy to mógł być powód
błędnego działania integracji i braku przykładowo zczytywania zdjęć?

W dniu śr., 10.04.2024 o 13:27 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
Na pewno nie - jedno z drugim nie ma żadnej korelacji.

**Comment by krasu11** [comment]
A czy możecie umowżliwić podiadanie na koncir większej ilości aplikacji niż
5?

W dniu czw., 11.04.2024 o 11:53 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
Nie, jest to limit stały.

**Comment by krasu11** [comment]
Jeśli jest to stały limit to jak udało się stworzyć łącznie 8 aplikacji?
Może z tego powodu pojawiały się problemy? Jest Pan pewien, że nie mogło to
działać negatywnie na integrację?

W dniu czw., 11.04.2024 o 12:11 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
Na pewno nie. Jak wspomniałem wcześniej - jedno z drugim nie ma nic wspólnego. Każda aplikacja działa niezależnie od drugiej.

**Comment by krasu11** [comment]
Aktualnie przy posiadaniu już pięciu aplikacji mam możliwość
zarejestrowania nowej. Czy nowa będzie odpowiednio działać? Czy to błąd
allegro?

W dniu czw., 11.04.2024 o 12:31 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
Dyskutujemy tu od jakiegoś czasu o rejestracji kolejnej aplikacji, a de facto każdą jedną czynność / operację możesz wykonać przy użyciu obecnych. Limit 5 aplikacji jest limitem stałym, a tylko przez wewnętrzne odświeżanie danych widzisz obecnie możliwość rejestracji kolejnej. Sugerowałbym się skupić na clue problemu, który masz, a nie na szukaniu go trochę tam gdzie go nie ma, czyli w rejestracji kolejnej aplikacji.

**Comment by MaciejFrackowiak** [comment]
Alternatywnie możesz zarejestrować aplikację na koncie, z którego wykonywałeś requesty - jak widzę tam masz tylko 2 aplikacje.

**Comment by krasu11** [comment]
Mógłbym, ale na tym koncie integracja 5 produktów działa bez zarzutów, więc
w niczym mi to nie pomoże. Problem pojawił się przy próbie integracji ponad
7k produktów. Dlatego muszę zarejestrować to na koncie z większą ilością
produktów.

W dniu czw., 11.04.2024 o 14:28 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
Aplikację możesz zarejestrować na koncie A, a wykorzystywać ją przez dowolne konto B, C, D, itd.

**Comment by krasu11** [comment]
Ale wtedy trzeba powiązać obydwa konta tak? Czy w jaki sposób to działa?

W dniu czw., 11.04.2024 o 14:45 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
Musisz zautoryzować użytkownika w imieniu, którego chcesz wykonywać operacje. Zapoznaj się proszę z [naszym poradnikiem dot. autoryzacji](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR) - opisane są tam wszelkie dostępne możliwości i kolejne kroki.

**Comment by krasu11** [comment]
A czy jestescie w stanie sprawdzic po koncie, ktore klucze (zarejestrowane
aplikacje) nie są aktywne/używane?

W dniu czw., 11.04.2024 o 14:52 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by krasu11** [comment]
A czy jestescie w stanie sprawdzic po koncie, ktore klucze (zarejestrowane
aplikacje) nie są aktywne/używane?

**Comment by krasu11** [comment]
Witam,
Byłbym wdzięczny za odpowiedź i pomoc.
Pozdrawiam

W dniu pt., 12.04.2024 o 14:00 Maciej ***@***.***> napisał(a):

**Comment by MaciejFrackowiak** [comment]
Ty jako właściciel konta i osoba, która rejestrowała aplikacje chyba najlepiej wiesz, z których aplikacji korzystasz lub chcesz korzystać nadal.
