### ISSUE TITLE
Endpoint order/checkout-forms zwraca 404 Not Found

### ISSUE THREAD

**Issue by studiowizjo** [allegro/allegro-api#8792]
Wysylajac zapytanie na endpoint: https://api.allegro.pl/order/checkout-forms/d7f67930-f358-11ee-addb-eb598ebdd867 otrzymuje odpowiedz:

```
{"errors":[{"code":"CheckoutFormNotFoundException","message":"Checkout form d7f67930-f358-11ee-addb-eb598ebdd867 not found...
```

Ten checkout form ID jest wziety z linku podgladu zamowienia z panelu Allegro: https://allegro.pl/moje-allegro/sprzedaz/oferta/d7f67930-f358-11ee-addb-eb598ebdd867?sellerId=41496971

Moj trace ID to: ce72fddfea2d4c39

**Comment by MaciejFrackowiak** [comment]
Spojrzałem na wskazane id zamówienia i niestety nie mogę zlokalizować go w naszej ogólnej bazie zamówień. Sprawdź proszę jego poprawność.
