### ISSUE TITLE
Zdarzenie dodania informacji o numerze przesyłki

### ISSUE THREAD

**Issue by studiowizjo** [allegro/allegro-api#8793]
Czy w momencie kiedy w panelu Allegro lub poprzez API zostanie dodany numer przesyłki do zamówienia, to jest generowane jakieś zdarzenie, które można pobrać przez API, tak aby mieć informację o tym, że został on wprowadzony?

**Comment by MartaNowaczyk** [comment]
Nie pobierzesz takiej informacji.

**Comment by studiowizjo** [comment]
Rozumiem, że w dzienniku zdarzeń również nie pojawi się wtedy nowe zdarzenie?

**Comment by MartaNowaczyk** [comment]
Nie.
