### ISSUE TITLE
Problem z doChangePriceItem

### ISSUE THREAD

**Issue by forfiter1** [allegro/allegro-api#88]
Witam
Próbuję zmienić cenę metodą doChangePriceItem. 
Błąd ERR_BID_DURING_CHANGES: Dokonanie zmiany nie jest możliwe z uwagi na fakt, że w aukcji złożone zostały oferty kupna.

Dlaczego ? Zmiana ceny przecież jest możliwa w ofertach z kupionymi już przedmiotami.  A w API nie ?

**Comment by DINK74** [comment]
Jest dokładnie tak jak piszesz - przez REST można dokonać zmiany w każdej aukcji, a przez SOAP - tylko na aukcjach bez ofert.
PS. było o tym wiele razy pisane - proponuję przeszukać issues.

**Comment by PawelTaberski** [comment]
Tak jak wyżej :-) dodam tylko, że dokładny opisy metod dostępnych po rest API znajdziesz tutaj: https://developer.allegro.pl/documentation/
Metoda do zmiany ceny to: [PUT /offers/{offerId}/change-price-commands/{commandId}](https://developer.allegro.pl/documentation/#!/default/put_offers_offerId_change_price_commands_commandId)

**Comment by forfiter1** [comment]
OK. Rozumiem, że ta metoda pamięta dawne czasy kiedy nie można było zmienić nic po kupieniu przez kogoś w ofercie. Ale przecież to było parę lat temu. Nie możecie w tej metodzie zmienić tego ?

**Comment by PawelTaberski** [comment]
Obecnie bardziej rozwijamy środowisko REST API dlatego tam dodajemy wszystkie nowe metody, m.in. zmianę ceny.
