### ISSUE TITLE
[REST] miniaturki zdjęć w medodzie /sale/offers zamiast pełnego rozmiaru

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#880]
Dzień dobry, 
Jak w temacie, 

Czy jest szansa na pobieranie miniatur na tym zasobie z nie zdjęć pełnowymiarowych? 
Przy limicie na poziome 1000 rek. to tak średnio wygląda.

pozdrawiamy wwwfactory

**Comment by rtnet-pl** [comment]
```
 internal static string ReplaceFullImageUrl(string url)
        {
            return url.Replace("/original/", "/s64/");
        }
```

**Comment by wwwfactory** [comment]
Dziękuję, zamykamy...

**Comment by wwwfactory** [comment]
Nie jeszcze nie zamykamy, 
Czy @PawelTaberski autoryzuje tą odpowiedź, czy można przyjąć że zawsze to będzie działać ? Na chwilę obecną to działa ale co dalej.

**Comment by PawelTaberski** [comment]
@wwwfactory Nie bardzo rozumiem, co masz na myśli przez miniaturkę, zwracamy link do pierwszego zdjęcia, które zawsze jest również miniaturką. Możesz je oczywiście zaprezentować w mniejszej rozdzielczości.
