### ISSUE TITLE
Aktywacja konta Sandbox

### ISSUE THREAD

**Issue by many-to-one** [allegro/allegro-api#8801]
Dzień dobry,
proszę o aktywację konta alfapro. To jest nowe konto które zostało powiązane przez NIP konta retset. I teraz czekam na weryfikację firmy. W sumie nie wiem czy mam po prostu poczekać czy potrzebna jest ingerencja z Waszej strony.
![image](https://github.com/allegro/allegro-api/assets/114101893/145c29af-3595-400e-8875-7aa522713956)

**Comment by MaciejFrackowiak** [comment]
Konto aktywne.

**Comment by many-to-one** [comment]
Dzięki
