### ISSUE TITLE
/product-proposals 403 Error

### ISSUE THREAD

**Issue by yyyakupyazici** [allegro/allegro-api#8806]
I have a bearer-token-for-user and I call /sale/product-proposals service. It returns 403 error. When I parse accessToken , I see I have allegro:api:sale:offers:write scope in accessToken. Is there anything else I should do also?

**Comment by MartaNowaczyk** [comment]
Give me the trace-id of the header from the reply with the error.  I'll check what's going on.

**Comment by yyyakupyazici** [comment]
Sure . It is b9e06eef82707b6c

**Comment by MartaNowaczyk** [comment]
The account you used for authorization is a regular account that is not active. You must have a company account to create products via API.

**Comment by yyyakupyazici** [comment]
Thanks for your reply.
