### ISSUE TITLE
DCR in sandbox environment

### ISSUE THREAD

**Issue by AnlakiX** [allegro/allegro-api#8809]
Hello, I would like to receive a Software statement ID for the application "test_test_123" (application id: c47c52b1a03e4dcaa5f4709019e61734) in sandbox environment. This is for automation of editing sale offers for self owned account without having to manually authorize the application every time it is called (1/day).
Thank you

**Comment by AureliuszBrussy** [comment]
DCR will not allow you to bypass the need to re-authenticate. To bypass the need to re-authenticate, use the token refresh option. You can read more about extending token validity and refresh token [in our tutorial](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#check-what-apps-are-linked-to-your-allegro-account).
