### ISSUE TITLE
payments-simulator.allegrosandbox.pl zwraca 504

### ISSUE THREAD

**Issue by netfarma** [allegro/allegro-api#881]
Mam problem z dokonaniem testowej płatności przy aktywowaniu konta firmowego dajar_netfarma

prosżę o aktywację

**Comment by PawelTaberski** [comment]
Wstępnie aktywowałem Twoje konto aby w pełni aktywować konto firmowe musisz przejść do zakładki Moje Konto i wystartować proces weryfikacji konta firmowego. Prześlij do nas jakieś dowolne dwa pliki.

**Comment by netfarma** [comment]
Dzięki, zrobiłem tak jak piszesz.
Udało mi się już wystawić na tym koncie aukcję.
Pozdrawiam

**Comment by Rikko28** [comment]
Hello, can you resolve my problem with test payments too? "daviva" account

**Comment by MaciejFrackowiak** [comment]
@Rikko28 We will check it and answer in #5693 thread.
