### ISSUE TITLE
W kategorii `620` nie jest wspierana wartość type `TEXT`

### ISSUE THREAD

**Issue by TomaszPabianItPiast** [allegro/allegro-api#8810]
Dzień dobry, próbuję wystawić towar nowymi metodami SalesProductOffer zamiast SalesOffer.

Niestety na sandboxie nie udało się przetestować zamienników i muszę to robić na aplikacji produkcyjnej.

W zapytaniu z traceId = 3d1542683d5d3b2a
dostaję zwrotkę że "W kategorii `620` nie jest wspierana wartość type `TEXT`."

Byłbym wdzięczny za pomoc co trzeba poprawić oraz przeglądnięcie requesta czy coś jeszcze w nim jest źle.

**Comment by AureliuszBrussy** [comment]
Komunikat błędu dotyczy sekcji "Pasuje do" (compatibilityList). Przekazany przez Ciebie typ sekcji "Pasuje do" jest w wersji tekstowej, która nie jest wspierana w danej kategorii. Więcej na temat tego, jak sprawdzić, czy w danej kategorii możesz dodać sekcję Pasuje do do oferty i w jakiej formie, przeczytasz [w naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-sekcja-pasuje-do-E7Zj6gAEGil#jak-sprawdzic-czy-w-danej-kategorii-moge-dodac-sekcje-pasuje-do-do-oferty).

**Comment by TomaszPabianItPiast** [comment]
Ok w takim razie  w przypadku gdy mam juz product id nie będę wysyłał compatybilityList - zobaczymy jak będzie działać.

Teraz z tym trace id - 66a193f86c1acd90
mam że Wybrany produkt ma sekcję "Pasuje do" ale nie jest ona przypisana do oferty, użyj produktowej sekcji "Pasuje do". Zaktualizuj dane produktowe w ofercie.

**Comment by AureliuszBrussy** [comment]
@TomaszPabianItPiast czy wysyłasz `null` w `compatibilityList`? Powinniśmy przypisać wartość z produktu, jeżeli całkiem pominiesz to pole. `null` wskazuje nam, że nie chcesz użyć danych z produktu.

**Comment by TomaszPabianItPiast** [comment]
Nie rozumiem, najpierw pisze Pan że 
"_Nie musisz podawać tej listy jeżeli chcesz skorzystać z istniejącego..._"
a następnie że muszę przepisać tą listę z produktu... 
ale na produkcie ta lista jest tylko w wersji tekstowej
a wersji tekstowej nie wspiera ta kategoria

to jak powinien wyglądać ten konkretny request?

na razie jest taki:

`{
   "productSet":[
      {
         "product":{
            "name":"Sachs 314 753 Amortyzator",
            "category":{
               "id":"19063"
            },
            "id":"dfd03381-2711-4cec-8629-a43d62bb26c3",
            "idType":null,
            "parameters":[
               {
                  "id":"127415",
                  "name":null,
                  "rangeValue":null,
                  "values":null,
                  "valuesIds":[
                     "127411_19"
                  ],
                  "valuesLabels":null,
                  "unit":null
               },
               {
                  "id":"129591",
                  "name":null,
                  "rangeValue":null,
                  "values":null,
                  "valuesIds":[
                     "129591_1"
                  ],
                  "valuesLabels":null,
                  "unit":null
               },
               {
                  "id":"17448",
                  "name":null,
                  "rangeValue":null,
                  "values":[
                     "1.81"
                  ],
                  "valuesIds":null,
                  "valuesLabels":null,
                  "unit":null
               },
               {
                  "id":"204053",
                  "name":null,
                  "rangeValue":null,
                  "values":null,
                  "valuesIds":[
                     "204053_128"
                  ],
                  "valuesLabels":null,
                  "unit":null
               },
               {
                  "id":"215858",
                  "name":null,
                  "rangeValue":null,
                  "values":[
                     "314 753"
                  ],
                  "valuesIds":null,
                  "valuesLabels":null,
                  "unit":null
               },
               {
                  "id":"216493",
                  "name":null,
                  "rangeValue":null,
                  "values":null,
                  "valuesIds":[
                     "216493_274581"
                  ],
                  "valuesLabels":null,
                  "unit":null
               },
               {
                  "id":"225693",
                  "name":null,
                  "rangeValue":null,
                  "values":[
                     "4013872767199"
                  ],
                  "valuesIds":null,
                  "valuesLabels":null,
                  "unit":null
               }
            ],
            "images":[
               "https://a.allegroimg.com/original/11e767/994b88c54d508985b4c4e7792e13",
               "https://a.allegroimg.com/original/110c25/188c09234599bb3e75d4afccd597"
            ]
         },
         "quantity":{
            "value":1
         }
      }
   ],
   "b2b":null,
   "attachments":null,
   "fundraisingCampaign":null,
   "additionalServices":null,
   "delivery":{
      "additionInfo":null,
      "handlingTime":"PT24H",
      "shipmentDate":null,
      "shippingRates":{
         "id":"9501b79f-b391-4a14-96b8-c0216fdc3cc5"
      }
   },
   "publication":null,
   "compatibilityList":null,
   "language":"pl-PL",
   "category":{
      "id":"19063",
      "leaf":false,
      "name":"",
      "parent":null,
      "options":null
   },
   "parameters":[
      {
         "id":"11323",
         "name":null,
         "rangeValue":null,
         "values":null,
         "valuesIds":[
            "11323_1"
         ]
      },
      null,
      null,
      null,
      null,
      null,
      null,
      null
   ],
   "afterSalesServices":{
      "impliedWarranty":{
         "id":"76258a55-ff09-42df-999d-1e2609902349",
         "name":null
      },
      "returnPolicy":{
         "id":"933b9739-033a-4966-a8b0-09b624745d52",
         "name":null
      },
      "warranty":{
         "id":"50f69317-787a-4b66-a1fb-a47acf51bc63",
         "name":null
      }
   },
   "sizeTable":null,
   "discounts":null,
   "name":"Amortyzator tył do FIAT STILO/BRAVO 07-",
   "payments":{
      "invoice":"VAT"
   },
   "sellingMode":{
      "format":"BUY_NOW",
      "minimalPrice":null,
      "price":{
         "amount":"252.48",
         "currency":"PLN"
      },
      "startingPrice":null
   },
   "location":{
      "city":"Bieruń",
      "countryCode":"PL",
      "postCode":"43-150",
      "province":"MAZOWIECKIE"
   },
   "images":[
      "https://a.allegroimg.com/original/11e767/994b88c54d508985b4c4e7792e13",
      "https://a.allegroimg.com/original/110c25/188c09234599bb3e75d4afccd597"
   ],
   "description":{
      "sections":[
         {
            "items":[
               {
                  "type":"TEXT",
                  "content":"<p><b>Kod towaru: 314 753</b></p><p><b>Numery OE: </b>51797471, 50701243, 50707958, 50705315, 50705393, 50705316, 51800724, 50701244, 50705394, 51797471, 50705394, 51841201, 51800724, 50705315, 50707958, 27-M09-A, 814901002539, 23963, 69494, 42916, JGT277S, 343397</p><h2>W przypadku wątpliwości przy prawidłowym doborze części, rekomendowana jest weryfikacja wg numeru nadwozia VIN.</h2><h1>Amortyzator tył do FIAT STILO/BRAVO 07-</h1><p><b>Parametr</b>: SEOV27/13X227A      </p>",
                  "url":null
               },
               {
                  "type":"IMAGE",
                  "content":null,
                  "url":"https://a.allegroimg.com/original/11e767/994b88c54d508985b4c4e7792e13"
               }
            ]
         },
         {
            "items":[
               {
                  "type":"TEXT",
                  "content":"<p>Produkty marki <b>SACHS</b> są produkowane z wykorzystaniem wysokiej jakości materiałów i zawierają najlepszą dostępną technologię. Dlatego liczni znani producenci samochodowi wyposażają swoje pojazdy w produkty marki SACHS: każdego roku z linii produkcyjnych zjeżdża ponad 10 milionów nowych pojazdów wyposażonych w tłumiki drgań i amortyzatory marki SACHS. Co więcej, firma SACHS oferuje wysokiej jakości sprzęgła dla producentów oryginalnego wyposażenia oraz na rynek części zamiennych.</p>",
                  "url":null
               },
               {
                  "type":"IMAGE",
                  "content":null,
                  "url":"https://a.allegroimg.com/original/110c25/188c09234599bb3e75d4afccd597"
               }
            ]
         },
         {
            "items":[
               {
                  "type":"TEXT",
                  "content":"<p><b>Stosowane w samochodach</b></p><p>FIAT BRAVO II (198_) 1.4 16V 2008.03 - </p><p>FIAT BRAVO II (198_) 1.4 16V 2008.03 - </p><p>FIAT BRAVO II (198_) 1.6 D Multijet 2008.03 - </p><p>FIAT STILO (192_) 1.2 16V (192_XA1B) 2002.02 - 2006.11</p><p>FIAT STILO (192_) 1.6 16V (192_XB1A) 2001.10 - 2006.11</p><p>FIAT STILO (192_) 1.6 16V (192_XB1A) 2001.10 - 2006.11</p><p>FIAT STILO (192_) 1.8 16V (192_XC1A) 2001.10 - 2006.11</p><p>FIAT STILO (192_) 1.9 JTD (192_XE1A) 2001.10 - 2006.11</p><p>FIAT STILO (192_) 1.9 JTD (192_XE1A) 2001.10 - 2006.11</p><p>FIAT STILO (192_) 1.9 D Multijet 2005.09 - 2006.11</p><p>FIAT STILO (192_) 1.9 D Multijet 2005.09 - 2006.11</p><p>FIAT STILO (192_) 1.9 JTD 2003.09 - 2006.11</p><p>FIAT STILO (192_) 1.9 JTD 2003.09 - 2006.11</p><p>FIAT BRAVO II (198_) 1.9 D Multijet 2007.04 - </p><p>FIAT BRAVO II (198_) 1.4 2007.04 - </p><p>FIAT BRAVO II (198_) 1.4 T-Jet 2007.09 - </p><p>FIAT BRAVO II (198_) 1.4 T-Jet 2007.09 - </p><p>FIAT BRAVO II (198_) 1.6 D Multijet 2007.09 - </p><p>FIAT BRAVO II (198_) 1.6 D Multijet 2008.03 - </p><p>FIAT BRAVO II (198_) 1.9 D Multijet 2007.04 - 2008.12</p><p>FIAT STILO (192_) 1.6 16V 2005.05 - 2006.11</p><p>FIAT STILO (192_) 1.6 16V 2005.05 - 2006.11</p><p>FIAT BRAVO II (198_) 2.0 D Multijet 2008.09 - </p><p>FIAT BRAVO II (198_) 1.4 LPG 2008.12 - 2014.12</p><p>FIAT BRAVO II (198_) 2.0 D Multijet 2008.09 - </p><p>FIAT STILO (192_) 1.9 JTD (192_XF1A) 2002.02 - 2006.11</p><p>FIAT STILO (192_) 1.9 JTD (192_XF1A) 2002.02 - 2006.11</p><p>FIAT STILO (192_) 2.4 20V (192_XD1A) 2001.10 - 2006.11</p><p>FIAT STILO (192_) 1.4 16V 2004.01 - 2006.11</p><p>FIAT STILO (192_) 1.4 16V 2004.01 - 2006.11</p><p>FIAT STILO (192_) 1.9 JTD 2004.01 - 2006.11</p><p>FIAT STILO (192_) 1.9 JTD 2004.01 - 2006.11</p><p>FIAT STILO (192_) 1.4 16V 2005.03 - 2006.11</p><p>FIAT STILO (192_) 1.9 D Multijet 2005.09 - 2006.11</p><p>FIAT STILO (192_) 1.9 D Multijet 2005.09 - 2006.11</p><p>FIAT STILO (192_) 1.9 D Multijet 2005.09 - 2006.11</p><p>FIAT STILO (192_) 1.9 JTD (192AXS1B, 192BXS1B) 2004.09 - 2006.11</p><p>FIAT BRAVO II (198_) 1.9 D Multijet 2007.04 - </p><p>FIAT BRAVO II (198_) 1.4 T-Jet 2007.09 - </p><p>LANCIA DELTA III (844_) 1.6 D Multijet 2008.08 - 2014.08</p><p>LANCIA DELTA III (844_) 1.6 D Multijet 2011.04 - 2014.08</p><p>LANCIA DELTA III (844_) 1.4 Bifuel 2011.07 - 2014.08</p><p>LANCIA DELTA III (844_) 1.4 2008.09 - 2014.08</p><p>LANCIA DELTA III (844_) 1.6 D Multijet 2008.09 - 2014.08</p><p>LANCIA DELTA III (844_) 2.0 D Multijet 2008.09 - 2014.08</p><p>LANCIA DELTA III (844_) 1.8 2009.01 - 2014.08</p><p>LANCIA DELTA III (844_) 2.0 D Multijet 2008.09 - 2014.08</p><p>LANCIA DELTA III (844_) 1.4 2008.09 - 2014.08</p><p>LANCIA DELTA III (844_) 1.9 D Multijet 2009.01 - 2014.08</p><p>LANCIA DELTA III (844_) 1.4 16V 2010.07 - 2014.08</p>",
                  "url":null
               }
            ]
         },
         {
            "items":[
               {
                  "type":"TEXT",
                  "content":"<p></p>",
                  "url":null
               }
            ]
         }
      ]
   },
   "external":{
      "id":"314 753"
   },
   "stock":{
      "available":20,
      "sold":0,
      "unit":"UNIT"
   },
   "tax":null,
   "messageToSellerSettings":null,
   "id":null,
   "validation":null
}`

**Comment by AureliuszBrussy** [comment]
Wysyłając `null` przekazujesz wprost informację, że nie chcesz tam umieścić żadnej informacji - wtedy nie pobierzemy wartości z produktu. Nie przesyłaj w ogóle w swoim payloadzie pola `compatibilityList` - wtedy automatycznie uzupełnimy go danymi z produktu.

**Comment by TomaszPabianItPiast** [comment]
Czy ze wszystkimi nulami mogę tak postąpić?
Konwertuję obiekty na requesta i z tego co rozumiem wystarczy że ustawię w JsonSerializerSettings NullValueHandling na Ignore ?
