### ISSUE TITLE
błędna informacja customValuesEnabled

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#8812]
Hej, dla kategorii 257083 oraz parametru Marka jest informacja, że customValuesEnabled są włączone:
```
{'variantsEqual': True,
 'variantsAllowed': False,
 'ambiguousValueId': '7108_52',
 'describesProduct': True,
 'customValuesEnabled': True,
 'dependsOnParameterId': None}
```
Niestety po podaniu w zmianie produktu `/sale/products/2ad06fa4-4ecd-46e0-8f2d-f7cb1a2eadf0/change-proposals` marki:
```
'parameters': [
    {'id': 7108, 'values': ['FB2'], 'valuesIds': ['7108_52']},
    ...
]
```
otrzymujemy 
```
{'errors': [{'code': 'CreateProductSuggestionValidationException', 'message': 'An error has occurred while reporting product errors: Invalid parameters entered: [Adding custom values has been disabled, please select a value from the dictionary for parameter 7108 (Marka)]', 'details': None, 'path': '/sale/products/2ad06fa4-4ecd-46e0-8f2d-f7cb1a2eadf0/change-proposals', 'userMessage': 'An error has occurred while reporting product errors: Invalid parameters entered: [Adding custom values has been disabled, please select a value from the dictionary for parameter 7108 (Marka)]', 'metadata': {}}]}
```

**Comment by AureliuszBrussy** [comment]
Czy mógłbyś podesłać trace-id tego wywołania z próbą sugestii zmiany w produkcie? Znajdziesz go w nagłówku response'a z tym błędem.

**Comment by anih** [comment]
Pewnie: `'trace-id': '118b134b32425b60'`

**Comment by AureliuszBrussy** [comment]
Sprawdziłem to - ze względów jakościowych Katalogu Produktów całkowicie blokujemy możliwość dodawania wartości własnych parametrów dla sugestii zmian. Ta zasada dotyczy też formularza sugestii na stronie. Stąd też komunikat błędu.

**Comment by anih** [comment]
W takim razie w jaki sposób zmienić markę z wybranej z katalogu na coś co nie występuje w dozwolonych wartościach?

**Comment by AureliuszBrussy** [comment]
W tym przypadku nalepiej, jeżeli taka rzeczywista marka zostanie wpisana do słownika, co rozwiąże problem. Najlepiej, jeżeli taką potrzebę zgłosi sprzedający przez [formularz kontatkowy](https://allegro.pl/pomoc/kontakt).
