### ISSUE TITLE
Zamówienia nie przechodzą do ERP - powód kod pocztowy

### ISSUE THREAD

**Issue by Levena007** [allegro/allegro-api#8814]
Witam,
wdrażamy integrację, którą prowadzimy bezpośrednio do naszego SAPa.
Konto: Karcher_Official

Mamy problem z kilkoma zamówieniami, które nie przechodzą do naszego systemu.
Nasi developerzy podejrzewają, że SAP zaciąga informację z konfiguracji konta klienta, które nie jest widoczne dla nas jako sprzedawcy.
Za każdym razem problem jest związany z kodem pocztowym. 
W szczegółach zamówienia (adres dostawy) jest wyświetlany poprawny numer kodu pocztowego w każdym z zamówień - zgadza się z miejscowością. We wszystkich zamówieniach klienci nie chcieli faktury.

e42cebd0-e0ac-11ee-92d0-6b52e4b52aae- - Unexpected data received for field PostCode:A-1220
83842ec2-e880-11ee-8ba8-f505429739df - 	Unexpected data received for field PostCode:97 - 525
6a256400-f3f0-11ee-ab62-cd0876a6bb66 - No data in SAP	Unexpected data received for field PostCode:BT8 7BW

Będę bardzo wdzięczna za pomoc w ustaleniu przyczyny problemu.
Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Integracja powinna bazować na obiekcie "[delivery](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET)" w zakresie pobierania danych do wysyłki dla konkretnego zamówienia. We wskazanych przypadkach rzeczywiście błędy wskazują na dane z konta użytkownika, a nie danych wysyłkowych.

**Comment by MaciejFrackowiak** [comment]
Kod pocztowy jest walidowany dla adresów, gdzie operuje Allegro, to jest Polska, Czechy, Słowacja. Nie sposób nam zapewnić walidację dla każdego kraju. Musimy jednak pamiętać, że jeśli klient ma konto od dłuższego czasu to obecne walidacje go nie dotyczą, a to oznacza, że w strukturze kodu mogą występować np. dodatkowe spacje jak w przytoczonym wyżej przypadku.

**Comment by Levena007** [comment]
Dziękuję za informację
Pozdrawiam
