### ISSUE TITLE
Sandbox account does not activate

### ISSUE THREAD

**Issue by mohan-mandal-pattern** [allegro/allegro-api#8815]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Hey Allegro team, I have done a fake bank transfer for the Sandbox account but after that, it does not activate the Sandbox account for us. Please can you inform me what is the cause for this problem. If you have any solution please let me know.

**Comment by MaciejFrackowiak** [comment]
Please give me a login or email address assigned to your account.

**Comment by mohan-mandal-pattern** [comment]
account: Pattern_EU

**Comment by mohan-mandal-pattern** [comment]
Thank you so much!
