### ISSUE TITLE
Pobieranie etykiety paczki dla danego zamówienia

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#8816]
1. Pobieram dane o przesyłkach do danego zamówienia metodą GET /order/checkout-forms/{id}/shipments]
2. Response zawiera shipments, które posiadają id
3. Próbuje metodą POST /shipment-management/label pobrać etykietę, ale otrzymuje błąd
4. Próbuję za pomocą metody GET /shipment-management/shipments/{shipmentId} pobrać szczegóły paczki, ale również otrzymuje błąd.

Znalazłam informację, że shipmentId powinnam przekazać identyfikator paczki GET /shipment-management/shipments/create-commands/{commandId}, ale paczki nie są tworzone przez API, a id, które otrzymuje nie jest tak naprawdę shipment_id, mimo, że dokumentacja sugeruje coś innego.

W jaki sposób w takim razie znając checkout_form zamówienia można pobrać etykietę dla paczki stworzonej do tego zamówienia?

**Comment by MaciejFrackowiak** [comment]
To są de facto dwa niezależne od siebie twory.
Zasób [GET /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/getOrderShipmentsUsingGET) pozwala na pobranie numerów trackingowych przypisanych do zamówienia, które wcześniej zostały dodane do niego za pośrednictwem [POST /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST).
Aby pobrać etykietę nadawczą realizowaną w ramach usługi Wysyłam z Allegro należy najpierw przygotować przesyłkę dla konkretnego zamówienia w oparciu o zasób [POST /shipment-management/shipments/create-commands](https://developer.allegro.pl/documentation/#operation/createNewShipment). Szczegółowo proces obsługi przesyłek opisaliśmy w [poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY).

**Comment by martacronic** [comment]
Rozumiem, ale w naszym przypadku etykiety nie są przygotowywane przez API, a chcielibyśmy jej w celu automatyzacji procesów pakowania przez API pobierać.

**Comment by MaciejFrackowiak** [comment]
Aby pobrać [etykietę](https://developer.allegro.pl/documentation/#operation/getShipmentLabels) niezbędne jest podanie "shipmentIds", które definiują dla jakich przesyłek etykiety mają zostać wygenerowane. ShipmentId natomiast to identyfikator utworzonej w kroku wcześniejszym przesyłki, który nie ma żadnej korelacji z zasobem odpowiedzialnym za numery trackingowe.

**Comment by martacronic** [comment]
![image](https://github.com/allegro/allegro-api/assets/37405655/a8cf38c5-4520-4c7c-b906-a5b9fea9d428)

Od strony frondendu można bez problemu pobrać etykietę nie tylko w momencie tworzenia paczki, ale również później. Czy istnieją metody na pobranie listy paczek lub podobne gdziekolwiek poza response z [POST /shipment-management/shipments/create-commands](https://developer.allegro.pl/documentation/#operation/createNewShipment) ?

**Comment by MaciejFrackowiak** [comment]
Nie, korzystając z zasobów API opieramy się na shipmentId, które otrzymasz w odpowiedzi dla [GET /shipment-management/shipments/create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/getShipmentCreationStatus).

**Comment by martacronic** [comment]
Ok, dziękuję za informacje. Przynajmniej oszczędziłam sporo czasu na szukaniu możliwości pobrania etykiety od strony zamówienia.

Czy planują Państwo w przyszłości pracę nad zasobem odzwierciedlającym dane zawarte w /moje-allegro/sprzedaz/wysylam/lista-przesylek ?

**Comment by MaciejFrackowiak** [comment]
Nie, na chwilę obecną nie ma takich planów.

**Comment by FishBeat** [comment]
> Aby pobrać [etykietę](https://developer.allegro.pl/documentation/#operation/getShipmentLabels) niezbędne jest podanie "shipmentIds", które definiują dla jakich przesyłek etykiety mają zostać wygenerowane. ShipmentId natomiast to identyfikator utworzonej w kroku wcześniejszym przesyłki, który nie ma żadnej korelacji z zasobem odpowiedzialnym za numery trackingowe.

Mam utworzony ShipmentId jak mam teraz go zamienić na shipmentIds?

**Comment by AureliuszBrussy** [comment]
@FishBeat jeżeli uzyskałeś `shipmentId` (w odpowiedzi na [GET /shipment-management/shipments/create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/getShipmentCreationStatus)) to w kolejnym etapie możesz skorzystać z niego do utworzenia zlecenia odbioru oraz wygenerowania etykiety. `shipmentIds` to tablica, możesz utworzyć zlecenie odbioru oraz wygenerować etykietę dla więcej niż jedne paczki. W [poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-etykiete-na-paczke) dowiesz się więcej na ten temat.

**Comment by FishBeat** [comment]
Już rozumiem, dziękuję za sprostowanie. Mam jeszcze pytanie - 

w odpowiedzi na /shipment-management/shipments/$shipmentId otrzymuję numer nadania przesyłki więc wszystko jest poprawnie wygenerowane do tej pory. Czy w przypadku wysyłek metodą "Automaty ORLEN Paczka" które nadaję tylko i wyłącznie w punkcie ORLEN muszę najpierw generować zlecenie odbioru czy mogę od razu przejść do wygenerowania etykiety (https://api.allegro.pl/shipment-management/label)?

**Comment by AureliuszBrussy** [comment]
Tak, w takim przypadku omijasz zlecenie odbioru przesyłki.

**Comment by FishBeat** [comment]
Ok, w takim razie nie rozumiem dlaczego serwer nic mi nie zwraca, nawet błędu. Mam utworzoną paczkę przez API z deklaracją etykiety w formacie PDF (mogę pobrać etykietę przez WzA) wysyłam przykładowe zapytanie:

$data:
Array
(
    [shipmentIds] => Array
        (
            [0] => 3aa88fad-68ab-4ad6-b7fa-3ac235165d5e
        )

    [pageSize] => A6
)

Kod PHP:
$data = json_encode($data);

                  $acces_token = trim($acces_token);
                  $curl = curl_init();
                  curl_setopt_array($curl, array(
                  CURLOPT_URL => "https://api.allegro.pl/shipment-management/label",
                  CURLOPT_RETURNTRANSFER => true,
                  CURLOPT_MAXREDIRS => 10,
                  CURLOPT_TIMEOUT => 30,
                  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                  CURLOPT_CUSTOMREQUEST => "POST",
                  CURLOPT_POSTFIELDS => $data,
                  CURLOPT_HTTPHEADER => array(
                  "Accept:application/octet-stream",
                  "Authorization:Bearer $access_token",
                  "Cache-Control:no-cache",
                  "Connection:keep-alive",
                  "Content-Type:application/vnd.allegro.public.v1+json",
                  "Host:api.allegro.pl"
                  )));
                      
                  $response = curl_exec($curl);
                  $err = curl_error($curl);
                  
                  curl_close($curl);
                  
                  if ($err) {
                  echo "cURL Error #:" . $err;
                  } else {
                  $response = json_decode($response);

                  echo 'ODPOWIEDŹ:<pre>';
                  print_r($response);
                    echo '</pre>';

Odpowiedź nic nie zawiera, co jest nie tak?

Dodam, że jeżeli podam błędny "shipmentId" to od razu mam odpowiedź z serwera o błędzie: 

ODPOWIEDŹ:

stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => SHIPMENT_NOT_FOUND
                    [message] => Requested shipment was not found
                    [details] => Requested shipment was not found
                    [path] => shipmentId
                    [userMessage] => Nie odnaleziono przewozu
                )

        )

)

Zakładam zatem, że z kodem raczej wszystko jest ok, a mimo to przy poprawnym "shipmentId" w odpowiedzi nie mam nic.

**Comment by AureliuszBrussy** [comment]
@FishBeat w odpowiedzi otrzymujesz plik binarny, a korzystasz z funkcji json_decode(). Sprawdź też jaki otrzymujesz response code. Spróbuj zmodyfikować swój kod.

**Comment by FishBeat** [comment]
Serdeczne dzięki! Wystarczyło usunąć jedną linijkę z funkcją json_decode() i wszystko gra. Rok bym nad tym siedział i bym na to nie wpadł, hueh ;/
