### ISSUE TITLE
Aktywacja konta Sandbox

### ISSUE THREAD

**Issue by Dejvis000** [allegro/allegro-api#8819]
Proszę o aktywowanie konta Allego Sandbox
mail: t.lisicki@gmail.com
login: Vive_test_123

**Comment by MartaNowaczyk** [comment]
Na tym koncie masz wybraną niepełną opcję sprzedażową. Wejdź proszę do [ustawień konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy), skorzystaj z linku, który masz na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)" i wybierz "Weryfikacja pełna". Uzupełnij dane i prześlij dowolne pliki, abym mogła aktywować to konto.

**Comment by Dejvis000** [comment]
Przepraszam, że tak wolno odpisuję lecz jestem tylko pośrednikiem od biznesu, aktualnie mamy taki komunikat, czy jest teraz możliwość aktywacji czy należy czekać?
![image](https://github.com/allegro/allegro-api/assets/21193548/3ff93764-aa07-40fb-a386-20a7ec784fa7)

**Comment by MartaNowaczyk** [comment]
Jest możliwość :) Aktywowałam to konto.
