### ISSUE TITLE
[sandbox] aktywacja konta

### ISSUE THREAD

**Issue by FreelinePL** [allegro/allegro-api#882]
Nie dostałem maila aktywującego konto w sandbox. Login "freeline", konto firmowe.

**Comment by PawelTaberski** [comment]
Sprawdzałeś czy informacje nie trafiła np. do spamu?
Na jakim adresie e-mail chciałeś zarejestrować konto? Podeślij nam przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) ten adres sprawdzimy to, w zgłoszeniu zaznacz, że informacje są potrzebne do ticketa numer 882 na GitHub-ie.

**Comment by FreelinePL** [comment]
Nie trafiła do spamu. Sprawdzałem, gdzie tylko się da, nawet w logach serwera pocztowego.

**Comment by PawelTaberski** [comment]
Podeślij proszę, tak jak pisałem wcześniej maila na jakiego rejestrowałeś konto. Sprawdzimy w czym jest problem.

**Comment by FreelinePL** [comment]
Wysłałem formularz kontaktowy w tym samym czasie, co odpowiedź tu.

**Comment by PawelTaberski** [comment]
Nie podesłałeś na jakiego maila chciałeś założyć konto, rozumiem że z tego z jakiego do nas napisałeś. Jeśli tak to sprawdziłem i na ten mail wysłaliśmy informację i nie wystąpiły żadne problemy (informacja dotarła). Jeśli nie masz jej w żadnym folderze to spróbuj ponownie założyć konto na te dane.

**Comment by FreelinePL** [comment]
Z jakiego maila wysyłacie informacje? Sprawdzę w logach.

**Comment by PawelTaberski** [comment]
Powinieneś otrzymać maila z adresu: no-reply@allegrosandbox.pl
