### ISSUE TITLE
WzA + paczkomaty - problem z ubezpieczniem

### ISSUE THREAD

**Issue by jzby-dev** [allegro/allegro-api#8821]
Próbuję nadać paczkę do paczkomatu, jak w większości przypadków deklaruję wartość 0 PLN:

```
            [items] => Array
                (
                    [0] => Array
                        (
                            [dimensions] => Array
                                (
                                    [height] => Array
                                        (
                                            [value] => 8
                                            [unit] => CENTIMETER
                                        )

                                    [width] => Array
                                        (
                                            [value] => 38
                                            [unit] => CENTIMETER
                                        )

                                    [depth] => Array
                                        (
                                            [value] => 64
                                            [unit] => CENTIMETER
                                        )
                                )
                            [weight] => Array
                                (
                                    [value] => 2
                                    [unit] => KILOGRAM
                                )

                            [description] => Elektronika
                            [value] => Array
                                (
                                    [amount] => 0
                                    [currency] => PLN
                                )

                            [type] => PACKAGE
                        )
                )
```

W odpowiedzi dostaję:
VALIDATION_FAILED :: items.value.amount Problem with ordering a shipment. Check your shipment data for errors. [ error.inpost.validation_failed.insurance.amount.too_small ]. Czy jest wymóg ubezpieczania niektórych paczek?

**Comment by AureliuszBrussy** [comment]
Czy przesyłka jest pobraniowa?

**Comment by jzby-dev** [comment]
Nie, to są zwykłe przesyłki bez pobrania, hurtowo je w tej chwili ubezpieczam, bo inaczej nie da się ich nadać. Jeśli chce Pan sprawdzić którąś to problem dotyczył np. tej: 
37eac98a-708a-4705-90ff-c23c89fba0e2	
605120898474100121386327

**Comment by AureliuszBrussy** [comment]
Dziękuję za podesłanie przykłady. Analizujemy to. Wrócę z odpowiedzią.

**Comment by jzby-dev** [comment]
Teraz dla odmiany jest:
VALIDATION_FAILED :: items.value.amount Insurance amount should be provided.

**Comment by KarolMryka** [comment]
Czy udało się rozwiązać problem? Inpost twierdzi, że po ich stronie było nic zmieniane. Czyli wynika z tego, że po stronie Allegro? Kiedy usterka zostanie usunięta? Wciąż nie można nadawać przesyłek poprzez Api.

**Comment by jzby-dev** [comment]
Ze swojej strony mogę zaproponować dwa rozwiązania (czy też obejścia) problemu:
1. Nadawanie tych paczek z ubezpieczeniem (prawdopodobnie to kosztuje)
2. Przejście z zasobów API parcel-management na shipment-management, w tych nowszych problem nie występuje

**Comment by AureliuszBrussy** [comment]
@KarolMryka proszę o jeszcze trochę cierpliwości. Jeszcze to wyjaśniamy.

**Comment by jzby-dev** [comment]
Przepraszam, jednak zmiana na shipment-management nie rozwiązuje problemu.

**Comment by KarolMryka** [comment]
Kolejny dzień bez wysyłek do Paczkomatów. Proszę o informację czy to problem globalny, po stronie Allegro, czy może to problem wybiórczy niektórych klientów? 
Czy wprowadzaliście Państwo zmiany w systemie polegające na odrzucaniu przesyłek z / bez ubezpieczenia - stąd ten dziwny komunikat? Nasza firma nie dokonywała żadnych zmian w systemie ERP a nadawanie nagle przestało działać i tylko dla PACZKOMATÓW.

**Comment by KarolMryka** [comment]
Kolejny dzień bez wysyłek do Paczkomatów. Proszę o informację czy to problem globalny, po stronie Allegro, czy może to problem wybiórczy niektórych klientów?

**Comment by KarolMryka** [comment]
Nie mamy dostępu - to system ERP - i nic nie było zmieniane. Nie damy rady przerobić systemu na kolanie, ponieważ ktoś coś zmienił po swojej stronie blokując całą naszą spółkę. 
Ale ku zdziwieniu dziś wszystko bez żadnej informacji ruszyło - ciekawe czy ktoś (Allegro lub Insport) przyznają się do zmian w działaniu.

**Comment by AureliuszBrussy** [comment]
@KarolMryka jest to powiązane ze zmianą w implementacji po naszej stronie. Wdrożyliśmy też wczoraj wieczorem kolejną zmianę, która rozwiązuje sprawę związaną z ubezpieczeniem. Aktualnie ten komunikat błędu nie powinien wystąpić przy takich requestach, które wykonuje Twoja integracja.
