### ISSUE TITLE
WZA: InPost Paczkomaty [error.inpost.validation_failed.custom_attributes.sending_method.unavailable]

### ISSUE THREAD

**Issue by mmodrzejewski** [allegro/allegro-api#8826]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry

Problem z nadaniem przesyłki WZA: Allegro Paczkomaty InPost, service_id / umowa własna: 
**2488f7b7-5d1c-4d65-b85c-4cbcf253fd93#51d7dcae-6b33-4e54-a8b4-2acb643cd269**
Było kilka prób nadania, przykładowe id:
**387de7d9-3c04-4412-9af0-2c9debaa65db**

Zwrotka
VALIDATION_FAILED
 error.inpost.validation_failed.custom_attributes.sending_method.unavailable

Klient jako punkt nadania podstawił: **POP-ZGR1**
Czy to jest przyczyną problemu? 

Pozdrawiam

**Comment by skmaksio** [comment]
To samo u mnie, wszystkie przesyłki:
 [code] => VALIDATION_FAILED
                    [message] => Problem with ordering a shipment. Check your shipment data for errors. [ error.inpost.validation_failed.custom_attributes.sending_method.unavailable ]
                    [details] => unavailable
                    [path] => /parcel-management/parcel-create-commands/db7e44c9-2076-5b7e-a529-064dfdcfb2a0
                    [userMessage] => Problem z zamówieniem przesyłki. Sprawdź, czy dane przesyłki nie zawierają błędów. [ error.inpost.validation_failed.custom_attributes.sending_method.unavailable ]

**Comment by AureliuszBrussy** [comment]
Dziękuję za podesłanie przykładów. Analizujemy to. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Pracujemy nad poprawką. Będę jeszcze Was update'ował w wątku.

**Comment by mmodrzejewski** [comment]
Dzień dobry.
Czy są jakieś aktualizacje w tym temacie?

**Comment by AureliuszBrussy** [comment]
@mmodrzejewski wgraliśmy poprawkę. Błąd nie powinien występować.
