### ISSUE TITLE
Jak powiązać konta Sandbox

### ISSUE THREAD

**Issue by many-to-one** [allegro/allegro-api#8827]
Witam,
Posiadam dwa firmowych konta na Sandbox(ie) Zeby je powiązać muszę podać kod który (niby?) ma być wysłany na mój numer telefonu. Jest jakiś fałszywy kod?

**Comment by MaciejFrackowiak** [comment]
Spróbuj proszę: TestToken1234

**Comment by many-to-one** [comment]
Zadziałało, dzięki
