### ISSUE TITLE
"/fulfillment/stock"  Incomplete return data

### ISSUE THREAD

**Issue by yao657355700** [allegro/allegro-api#8829]
The returned data does not include the EAN code of one's own store,
May I ask what's going on?

**Comment by MaciejFrackowiak** [comment]
Please, give me a trace-id of your request.

**Comment by yao657355700** [comment]
> Please, give me a trace-id of your request.

Gtins
Why isn't there an ean from my own store in this collection?
![123](https://github.com/allegro/allegro-api/assets/87019541/40ade153-1cd6-41f5-983c-3f86d3deb53c)

**Comment by yao657355700** [comment]
> Please, give me a trace-id of your request.

Can this interface return the value of OfferID?

**Comment by MaciejFrackowiak** [comment]
According to the endpoint [documentation](https://developer.allegro.pl/documentation/#operation/getFulfillmentStock) we return a list of product's GTIN numbers. You deliver products to the warehouse, not offers.

**Comment by yao657355700** [comment]
My product is already being sold in your warehouse

**Comment by MaciejFrackowiak** [comment]
Yes, but as I wrote - you delivered products, not offers, so we return products in response to the [GET /fulfillment/stock](https://developer.allegro.pl/documentation/#operation/getFulfillmentStock) resource.

**Comment by yao657355700** [comment]
Is there an interface to obtain the value of productid?

**Comment by yao657355700** [comment]
GET/filling/lock
Can this interface return the value of the product's "OfferID"

**Comment by yao657355700** [comment]
GET /fulfillment/stock 
Can this interface return the value of the product's "OfferID"

**Comment by MaciejFrackowiak** [comment]
Nothing has changed since yesterday, so once again:
- GET /fulfillment/stock will not return offerId, because it returns products,
- about the value of the productId - you reported a suggestion, which is under verification now.

If anything changes, we will let you know about it in our communication.

**Comment by yao657355700** [comment]
Is there an API interface that can retrieve return order information

**Comment by yao657355700** [comment]
Is there an API interface that can retrieve return order information

**Comment by MaciejFrackowiak** [comment]
Yes, we have it. I have already answered in the thread https://github.com/allegro/allegro-api/issues/8846.
