### ISSUE TITLE
Allegro WebAPI nie działa

### ISSUE THREAD

**Issue by kiczek** [allegro/allegro-api#883]
Po przejściu na https://webapi.allegro.pl/service.php?wsdl otrzymujemy informacje o błędzie:

> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Header/>
  <SOAP-ENV:Body>
    <SOAP-ENV:Fault>
      <faultcode>SOAP-ENV:Client</faultcode>
      <faultstring xml:lang="en">Internal Server Error</faultstring>
    </SOAP-ENV:Fault>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

Problem pojawił się w nocy i API do tej pory nie działa.

**Comment by FromAnyHole** [comment]
Nic podobnego - tej nocy było nawet (średnio) mniej błędów WebAPI, niż jest to zwykle ;-)

**Comment by PawelTaberski** [comment]
@kiczek Sprawdziłem i wygląda, że wszystko działa poprawnie. Czy problem nadal u Ciebie występuje.
