### ISSUE TITLE
error:"Missing delivery method"

### ISSUE THREAD

**Issue by xcg340122** [allegro/allegro-api#8831]
Hello, I am trying to add a new country's express method, which is Slovakia. First, I obtained all the permitted express method codes through API, and found the id of Slovakia as shown in the picture below. Then, when creating the shipping template, I used this id:"d9616fd2-9a79-11e5-8994-f eff819cdc9f", however, the creation will return an error with the error content {"code":"MISSING_DELIVERY_METHOD","message":"Missing delivery method" [d9616fd2-9a79-11e5-8994-feff819cdc9f]"}
Unlike the "Delivery method not found" error type, how does this work?
![image](https://github.com/allegro/allegro-api/assets/16789191/88d967e0-9889-4528-891d-d87e6613931f)

**Comment by MartaNowaczyk** [comment]
Provide the trace-id for the error you mention. I will verify it. 
All delivery services available for user you can get by [GET /shipment-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getDeliveryServices). Give me trace-id or commandId for

**Comment by xcg340122** [comment]
> Provide the trace-id or commandId for the error you mention. I will verify it. All delivery services available for user you can get by [GET /shipment-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getDeliveryServices).

I used this API to get the delivery method id :"https://api.{environment}/sale/delivery-methods"

**Comment by MartaNowaczyk** [comment]
The error you have sent looks incomplete. I asked for the trace-id from the error response header so that I could check the data you sent in the logs, but you did not provide it. If you chose a delivery method to the Czech Republic, you should also add a delivery method to Slovakia. I think that's the issue here.

**Comment by xcg340122** [comment]
> The error you have sent looks incomplete. I asked for the trace-id from the error response header so that I could check the data you sent in the logs, but you did not provide it. If you chose a delivery method to the Czech Republic, you should also add a delivery method to Slovakia. I think that's the issue here.

Isn't the Delivery method in Slovakia just the id of deliveryMethod? I have delivered it and tested it. If I write wrong, the feedback will be "Delivery method not found". Now the feedback is: "Missing delivery method" indicates that there is no mistake. I will resend the request for trace-id and send it to you later

**Comment by MartaNowaczyk** [comment]
Yes, this is the ID of the delivery method.

**Comment by xcg340122** [comment]
> The error you have sent looks incomplete. I asked for the trace-id from the error response header so that I could check the data you sent in the logs, but you did not provide it. If you chose a delivery method to the Czech Republic, you should also add a delivery method to Slovakia. I think that's the issue here.

Response：
{"errors":[{"code":"MISSING_DELIVERY_METHOD","message":"Missing delivery method [07515f0a-9d73-4c68-8a41-feff819cdc9f] required in bundle \"SlovakiaBundle\".","details":null,"path":null,"userMessage":"Brak metod [07515f0a-9d73-4c68-8a41-feff819cdc9f] wymaganych w pakiecie metod \"SlovakiaBundle\"."}]}

trace-id:7ef1d9266e4836e2

**Comment by xcg340122** [comment]
> According to the message, you need to add a shipment with ID 07515f0a-9d73-4c68-8a41-feff819cdc9f, which is not in the request.

But Slovakia is this, and the value was obtained through the api, not generated by me

**Comment by xcg340122** [comment]
> According to the message, you need to add a shipment with ID 07515f0a-9d73-4c68-8a41-feff819cdc9f, which is not in the request.

And as I mentioned above, if an id does not exist, the feedback will be not found, rather than Missing delivery method

**Comment by MartaNowaczyk** [comment]
Okay, I will verify it again.

**Comment by MartaNowaczyk** [comment]
I don't see any other problems here.  Add a delivery method to your request:
   ...
     {
      "deliveryMethod": {
        "id": "07515f0a-9d73-4c68-8a41-feff819cdc9f"
      },
  ...
along with other necessary data and the request will be correct.

**Comment by xcg340122** [comment]
> I don't see any other problems here. Add a delivery method to your request: ... { "deliveryMethod": { "id": "07515f0a-9d73-4c68-8a41-feff819cdc9f" }, ... along with other necessary data and the request will be correct.

Okay, thank you. Problem solved
