### ISSUE TITLE
Pobieranie etykiety - błąd: The remote server returned an error: (422) Unprocessable Entity.

### ISSUE THREAD

**Issue by TomaszPabianItPiast** [allegro/allegro-api#8834]
Witam, staram się pobrać etykietę do wysyłki stworzonej z requesta z trace id - daf63cecde97a375

samo tworzenie nie zwraca błędów ale przy próbie wywołania 
shipment-management/label

gdzie spodziewam się dostać labelkę dostaję błąd jak w tytule.

Czy źle generuję zapytanie o etykietę czy jest jakiś błąd z przesyłką którego nie wyłapałem?

**Comment by MartaNowaczyk** [comment]
Podaj proszę trace-id, który zwracamy w nagłówku odpowiedzi z błędem.

**Comment by TomaszPabianItPiast** [comment]
stworzenie wysyłki trace id = b8d2c78fe9f40c4d
pobranie etykiety trace id = e6dbef6c2fab6827

**Comment by MartaNowaczyk** [comment]
Nie widzę błędu 422 przy pobieraniu etykiety o trace id = e6dbef6c2fab6827. Czy to na pewno ten przykład?

**Comment by hajdusia** [comment]
Mam ten sam problem.

Endpoint: `https://api.allegro.pl/shipment-management/label`
trace-id: `38977ad32d7a9595`

Odpowiedź z serwera:
```json
{"errors":[{"code":"ANOTHER_SERVICE_NOT_AVAILABLE","message":"One of required services is unavailable. Try again later.","details":"One of required services is unavailable. Try again later.","path":null,"userMessage":"Jeden z wymaganych serwis\xc3\xb3w, do poprawnego dzia\xc5\x82ania, jest niedost\xc4\x99pny. Spr\xc3\xb3buj ponownie za moment."}]}
```

Nie jestem też w stanie nadać przesyłki przez WzA na stronie Allegro. Problem występuje dla dowolnej przesyłki Allegro One Box.

**Comment by hajdusia** [comment]
Wydaje mi się, że wystąpił podobny problem co w https://github.com/allegro/allegro-api/issues/8693 , moje konto też jest nowe i wygląda jakby było źle zainicjalizowane.

**Comment by MartaNowaczyk** [comment]
@hajdusia dzięki za przykład. Sprawa jest w trakcie weryfikacji, wrócę z odpowiedzią tak szybko jak to możliwe.

**Comment by MartaNowaczyk** [comment]
@hajdusia poprawiliśmy Twoje konto. Teraz powinno być ok, spróbuj ponownie.
