### ISSUE TITLE
Dodatkowe informacje o płatności

### ISSUE THREAD

**Issue by DanielInsert** [allegro/allegro-api#8838]
Cześć,

W temacie wczorajszego update'u -> https://developer.allegro.pl/news/zamowienia-dodalismy-dodatkowe-informacje-o-platnosci-wwxoRvvxET5 

Jeżeli mamy AllegroPay to dlaczego występuje ID płatności P24?

![AP](https://github.com/allegro/allegro-api/assets/166800949/84f275c5-ad55-4c11-aada-973fb112068c)

Czy aktualnie coś to zmienia w cesyjności płatności ? plus jak wygląda taka wpłata w koncie, nie różni się technicznie od przykładu poniżej?

![wpłata1](https://github.com/allegro/allegro-api/assets/166800949/63cebe7f-5da3-4bbe-8da3-65cf81a80a43)

**Comment by AureliuszBrussy** [comment]
Operatorem takiej płatności wciąż jest albo PayU albo Przelewy24. Zwracanie informacji o Allegro Pay w zamówieniu niesie przede wszystkim wartość informacyjną dla sprzedającego, [ponieważ może się to wiązać z naliczeniem dodatkowych opłat](https://help.allegro.com/sell/pl/a/oplata-za-zakupy-oplacone-przy-pomocy-allegro-pay-aMloER5YAFG). Technicznie taka wpłata nie różni się niczym od pozostałych.

**Comment by DanielInsert** [comment]
Dziękujemy
