### ISSUE TITLE
Allegro Automat ORLEN Paczka błąd

### ISSUE THREAD

**Issue by bartekc7** [allegro/allegro-api#8839]
Dzień dobry,
Potrzebuje wskazówki co może być powodem poniższego błędu?
API Sandbox
Metoda dostawy: Allegro Automat ORLEN Paczka
Kod punktu: WS-529284-J2-34

{
  "commandId": "02937a88-cb52-4ee9-8953-147112462f55",
  "status": "ERROR",
  "errors": [
    {
      "code": "ERROR",
      "message": "Processing error",
      "details": null,
      "path": null,
      "userMessage": "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."
    }
  ],
  "shipmentId": null
}

**Comment by MartaNowaczyk** [comment]
Dzień dobry, w tym przypadku problemem jest brak wymaganego przez przewoźnika pola `sender.name`.

**Comment by bartekc7** [comment]
Dziękuje za odpowiedź. Dziś bez żadnych zmian ta wysyłka przechodzi. Czy to był błąd i został naprawiony?
Dokumentacja twierdzi że wymagane jest pole Name LUB Company

![image](https://github.com/allegro/allegro-api/assets/207927/6dbd4e74-bbb1-45d5-bc73-60509d434d90)

**Comment by MartaNowaczyk** [comment]
Może się zdarzyć, że niektórzy przewoźnicy mogą tego pola wymagać. Nic nie było poprawiane, w tamtym wypadku taką informację zwrócił przewoźnik.
