### ISSUE TITLE
Unsuccesful Refund through API

### ISSUE THREAD

**Issue by justynapalka** [allegro/allegro-api#8840]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

While refunding we are sending this message:
POST https://api.allegro.pl/payments/refunds/
{
  "payment": {
    "id": "71408c47-f01c-11ee-a208-43762ae3c906"
  },
  "reason": "REFUND",
  "lineItems": {[
      "id": "58db6d70-f01c-11ee-9328-85196bb0299c",
      "type": "QUANTITY",
      "quantity": 1
  ]}
}

The response we are getting shows below error.
Can you please advice what needs to be ammended?

{
  "code": "VALIDATION_ERROR",
  "message": "Oferta: 58db6d70-f01c-11ee-9328-85196bb0299c ilość przekroczona, dostępna: 0, żądana: 1",
  "userMessage": "Oferta: 58db6d70-f01c-11ee-9328-85196bb0299c ilość przekroczona, dostępna: 0, żądana: 1"
}
Justyna

**Comment by justynapalka** [comment]
Hi, sorry, is there a chance I can get an answer on this one?

Much appreciated.
Justyna

**Comment by MartaNowaczyk** [comment]
The error occurred because there was already one refund in processing (created on April 11). Now it already has a canceled status, hence you can repeat the request.

**Comment by justynapalka** [comment]
Hi,
we have a confirmation customer received a refund but in Allegro panel there is no update the return was processed.
Can you please advise what is causing this?

Thanks
Justyna

API:
/developers/powelll/Clive/src/Allegro/Api/AllegroApi.php:134:
class stdClass#2388 (8) {
  public $id =>
  string(36) "38ac8f10-fc9a-11ee-a32b-5f5e83682b37"
  public $payment =>
  class stdClass#2412 (1) {
    public $id =>
    string(36) "71408c47-f01c-11ee-a208-43762ae3c906"
  }
  public $reason =>
  string(6) "REFUND"
  public $status =>
  string(3) "NEW"
  public $createdAt =>
  string(24) "2024-04-17T09:09:40.133Z"
  public $totalValue =>
  class stdClass#2413 (2) {
    public $amount =>
    string(6) "149.99"
    public $currency =>
    string(3) "PLN"
  }
  public $lineItems =>
  array(1) {
    [0] =>
    class stdClass#2411 (3) {
      public $id =>
      string(36) "58db6d70-f01c-11ee-9328-85196bb0299c"
      public $type =>
      string(8) "QUANTITY"
      public $quantity =>
      int(1)
    }
  }
  public $surcharges =>
  array(0) {
  }
}

**Comment by MartaNowaczyk** [comment]
Please specify exactly where you do not see this information.

**Comment by MartaNowaczyk** [comment]
Hi, your case is under verification, I will return with an answer as soon as possible.

**Comment by MartaNowaczyk** [comment]
Yes, there are no refunds on our side.
