### ISSUE TITLE
Ten sam "Client id" i "Client secret" dla wielu apliakcji, czy ten sam?

### ISSUE THREAD

**Issue by GregTora** [allegro/allegro-api#8842]
Używam od dłuższego czasy API do obsługi zamówień na magazynie. Potrzebuję dodatkowo użyć API w innych celach w innym miejscu/innej aplikacji.

Proszę o informację, czy mam użyć obecnie używany "Client id" i "Client secret" w tym innym miejscu/innej aplikacji, czy mam (jeżeli można) wygenerować nowy "Client id" i "Client secret"?

**Comment by MartaNowaczyk** [comment]
Poprawna zasada to jedna aplikacja jeden Client ID. Jeśli są to całkowicie odrębne aplikacje, to możesz wygenerować inny.
