### ISSUE TITLE
Automatyczna wiadomość po zakupie wraz z załącznikiem

### ISSUE THREAD

**Issue by GregTora** [allegro/allegro-api#8843]
Potrzebuję automatycznie wysyłać do Klientów (którzy złożyli i opłacili zamówienie) wiadomość wraz z załącznikiem (plik .pdf). Załącznik to dokument zakupu (faktura lub paragon). Dokument zakupu jest magazynowany w ERP (jeżeli ułatwi to proces to katalog z tymi plikami .pdf może być osobno wydzielony, aby "wiadomość do Klienta pobierała" załącznik z odpowiedniego katalogu, a nie bezpośrednio z ERP). Treść wiadomości może być stała, bez żadnych dynamicznych treści.

Proszę o informację, jakie rozwiązanie będzie do tego optymalne? Czy za pomocą API, czy jest może jakiś inny mechanizm który spełni w/w potrzeby?

**Comment by MaciejFrackowiak** [comment]
Do wysyłania wiadomości do klientów służą zasoby [Centrum wiadomości](https://developer.allegro.pl/documentation/#tag/Message-Center) - oczywiście dostępne są one w API. Poszczególne endpointy opisujemy w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-centrum-wiadomosci-XxWm2K890Fk).
