### ISSUE TITLE
Automatyczna wiadomość z plikiem .pdf

### ISSUE THREAD

**Issue by GregTora** [allegro/allegro-api#8844]
Czy taka funkcjonalność, jaka jest widoczna na poniższym screenie (jest to korespondencja z sekcji "Wiadomości"), to jest funkcjonalność Allegro (np. za pomocą API)? Czy za taki mechanizm odpowiada zewnętrzna aplikacja (np. Baselinkier)?

[1] - Plik .pdf z dokumentem zakupu
[2] - Treść wiadomości

![obraz](https://github.com/allegro/allegro-api/assets/166823872/e3e921ce-fafd-4d2a-ad92-1c7a62e25476)

**Comment by MaciejFrackowiak** [comment]
To jest funkcjonalność zewnętrznej aplikacji wykorzystująca zasoby API [Centrum wiadomości](https://developer.allegro.pl/documentation/#tag/Message-Center).
