### ISSUE TITLE
Sandbox naliczanie opłat

### ISSUE THREAD

**Issue by Joasia25** [allegro/allegro-api#8847]
Chciałabym przetestować pobieranie danych o naliczonych opłatach. Czy w Sandbox da się zasymulować sprzedaż swojego przedmiotu, aby zostały naliczone opłaty? Jeśli tak to w jaki sposób?

**Comment by MaciejFrackowiak** [comment]
Na Sandbox działa mechanizm tożsamy z produkcyjnego Allegro tzn. opłaty za sprzedaż są pobierane automatycznie z otrzymanego wpływu. Nie można tego zmienić. Więcej o tym przeczytasz w [Pomocy Allegro](https://help.allegro.com/sell/pl/a/automatyczne-pobieranie-naleznosci-za-nasze-uslugi-z-pieniedzy-ktore-masz-ze-sprzedazy-8dvEzZreAfM).

**Comment by Joasia25** [comment]
Czyli musze stworzyć kolejne konto na Sandobox i kupować z innego konta? Czy tak to zadziała?

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak.
