### ISSUE TITLE
EAN

### ISSUE THREAD

**Issue by PiotrLaszczyk** [allegro/allegro-api#885]
Wystawiam oferty i od czasu do czasu trafia się oferta której EAN nie przechodzi walidacji w allegro (0,5% wszystkich aukcji):

"validation": {"errors": [{"code": "VALIDATION_ERROR", "message": "Podany kod EAN jest niepoprawny."

Przykłądowy EAN który sfailował "5900694410775", oferta miała pójść do kategorii: "category": {"id": "93705"}

Pytanie, od czego zależny validacja w allegro, to jest porównywane z kategorią? 

Można jakoś sprawdzić EAN zanim się wystawi ofertę?

**Comment by FromAnyHole** [comment]
Algorytm z cyfrą kontrolną dla EAN-13 nie jest może oczywisty, ale jest raczej prosty...
Twój EAN z przykładu jest błędny, walidatorów jest masa (jeśli nie chce ci się napisać).

**Comment by PiotrLaszczyk** [comment]
To że można sobie w necie sprawdzić to wiadomo. Zastanawia mnie czemu jest (dość spora) populacja EANów które nie przechodzą walidacji. Producenci 'olewają' powszechnie obowiązujące standardy czy też EAN-13 ma ileś tam wariantów.

Pytam bo nie jestem ekspertem od EANów ;)

**Comment by kormichu** [comment]
EAN ma kilka wariantów, ale są one różnej długości: https://framework.zend.com/manual/2.4/en/modules/zend.validator.barcode.html

Nie wiem, które Allegro obsługuje

**Comment by PawelTaberski** [comment]
Więcej informacji na temat EAN-ów ich długości, jakie możesz podać znajdziesz [tutaj](https://allegro.pl/dla-sprzedajacych/kod-ean-w-allegro-wqggrjgj2hR). Nie ma możliwości przez API sprawdzenia wcześniej czy EAN jest poprawny.
