### ISSUE TITLE
Aktywacja konta na Sandbox

### ISSUE THREAD

**Issue by Wojtu204** [allegro/allegro-api#8850]
Proszę o aktywację na środowisku sandbox konta na adres email:
login: Wojtu
email: schnitter@o2.pl

Dziękuję i pozdrawiam
Wojtek

**Comment by lukoc** [comment]
Również proszę o aktywację konta firmowego w sandboxie, login: Lanaccount

**Comment by AureliuszBrussy** [comment]
@Wojtu204 konto z tymi danymi nie istnieje na Sandboxie. Dokończ proces rejestracji - niezbędne jest potwierdzenie rejestacji poprzez link otrzymany w wiadomości na skrzynkę mailową.

@lukoc aktywowałem Twoje konto.

**Comment by Wojtu204** [comment]
Niestety nie mam możliwości dokończenia aktywacji - link z maila aktywacyjnego kieruje na stronę główną portalu, próba zalogowania z jej poziomu kończy się niepowodzeniem.
Skopiowałem link i próbowałem otworzyć na innym urządzeniu - efekt ten sam jak wyżej.

**Comment by AureliuszBrussy** [comment]
Sprawdziłem to i aktualnie nie rozpoznałem żadnych problemów dot. procesu zakładania konta. Spróbuj zarejestrować się jeszcze raz (możesz spróbować także na inny adres mailowy).

**Comment by Wojtu204** [comment]
Na inny adres zadziałało, konto osobiste zostało założone. Dziękuję za pomoc.
