### ISSUE TITLE
Dziwny parametr "Rozmiar (new)" pojawiający się w niektórych kategoriach

### ISSUE THREAD

**Issue by jezewskiBNetrox** [allegro/allegro-api#8852]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,
wystawiamy aukcje korzystając ze wcześniej ustalonego szablonu z bazy danych. Niestety w ostatni weekend pojawił się znikąd parametr `Rozmiar (new)` i wywołał on masę błędów w wystawianiu a będąc szczerym nie ma on za bardzo sensu w niektórych kategoriach ani nie został nigdzie zapowiedziany. Stąd zgłaszam to jako błąd.

Przykładowy trace-id: `d1258d9ee295fea4`
Kategoria 259091 (Pajacyki) zwraca parametry takie jak "Rozmiar" i "Rozmiar (new)". 
To samo w 89525 (Sweterki), trace-id: `14673f6055fe36a5`.

Pozdrawiam.

**Comment by MartaNowaczyk** [comment]
Z tego co wiem parametr słownikowy Rozmiar (new) docelowo zastąpi liczbowy parametr Rozmiar, stąd pewnie te zmiany. Jednak nie jest to kwestia zmian w API Allegro, tylko ogólnego działania allegro i o takich rzeczach jak zmiany w parametrach praktycznie nie informujemy jako wsparcie API. W tej sprawie sugeruję kontakt przez [formularz kontaktowy.](https://allegro.pl/pomoc/kontakt)

**Comment by jezewskiBNetrox** [comment]
@MartaNowaczyk Sprawdzałem też zmiany zapowiadane w aktualnościach dla sprzedawców, ale niestety nic nie znalazłem. 
>Z tego co wiem parametr słownikowy Rozmiar (new) docelowo zastąpi liczbowy parametr Rozmiar, stąd pewnie te zmiany.
To potrzebowałem wiedzieć przede wszystkim. Zmiana jest na tyle dziwna, ze wolałem się upewnić czy jest intencjonalna. 

Dziękuję za informację i pozdrawiam.
