### ISSUE TITLE
AccessDenied

### ISSUE THREAD

**Issue by pr0fes0rre** [allegro/allegro-api#8854]
client:106959585
email: michals@ecom.house

Po zarejestrowaniu i utworzeniu aplikacji REST API otrzymałem dane do autoryzacji, którymi generuję token. Włączone mam teoretycznie wszystkie uprawnienia i np 

`https://api.allegro.pl.allegrosandbox.pl/sale/categories`

poprawnie zwraca kategorie.

Gdy chcę uderzyć po oferty
```
allegro:api:sale:offers:read
Odczyt danych o ofertach
```
`https://api.allegro.pl.allegrosandbox.pl/sale/offers`

otrzymuję 403 Forbidden i 
```
{
    "errors": [
        {
            "code": "AccessDenied",
            "message": "Access is denied",
            "details": null,
            "path": null,
            "userMessage": "No access to the specified resource."
        }
    ]
}
```

To samo gdy uderzam po produkty

`https://api.allegro.pl.allegrosandbox.pl/sale/products`

Czy potrzebuję jakiejś dodatkowej aktywacji konta w sandbox?

**Comment by MaciejFrackowiak** [comment]
Wynika, że korzystasz z autoryzacji client_credentials, natomiast zasoby /sale/offers czy też /sale/products wymagają autoryzacji typu "[bearer-token-for-user](https://developer.allegro.pl/documentation/#section/Authentication/bearer-token-for-user)".

**Comment by pr0fes0rre** [comment]
Ok widzę swój błąd czyli muszę wykonać [tą autoryzację](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#autoryzacja-uzytkownika)
Po wygenerowaniu redirect_url prowadzi mnie do allegro logowanie i następnie nie mogę się zalogować 
_Login, e-mail lub hasło są nieprawidłowe_ a przy próbie odzyskania hasła _Login lub e-mail są nieprawidłowe_

**Comment by MaciejFrackowiak** [comment]
Twoje konto na Sandbox nie jest aktywne - będę mógł je aktywować, gdy uzupełnisz je danymi (podaj fikcyjne dane).

**Comment by pr0fes0rre** [comment]
Uzupełniłem dane Imię i Nazwisko oraz Login

**Comment by MaciejFrackowiak** [comment]
Twoje konto teraz jest już aktywne. Tym samym odzyskanie danych do konta bez przeszków powinno być dostępne.

**Comment by pr0fes0rre** [comment]
dalej nie mogę się zalogować a ozdyskanie hasła nie jest możliwe.

**Comment by pr0fes0rre** [comment]
oraz w ramach testów chciałem zarejestrować drugą aplikację typu device pod tym linkiem https://apps.developer.allegro.pl.allegrosandbox.pl/
jednak po wyklikaniu wszystkich niezbędnych parametrów przy kliknięciu "Zarejestruj" nic się nie dzieje, nie dostaję zadnego komunikatu o błędzie, nie przechodzę do innej strony a po odświerzeniu nie widzę nowej aplikacji.

**Comment by MaciejFrackowiak** [comment]
Jak widzę funkcjonalność przypomnienia hasła działa bezproblemowo. Natomiast w przypadku rejestracji aplikacji - proszę zobrazuj to zrzutem ekranu.

**Comment by pr0fes0rre** [comment]
wciąż nie mogę się zalogować 
przy autoryzacji urzytkownika
generuję taki url:
`https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=cccf62e8771c4a6894f545ba2c84f900&redirect_uri=http://localhost:8000`
i po odesłaniu na stronę mój login i hasło nie przechodzą a po przejściu do przypomnienia hasła otrzymuję:
![reset_hasla](https://github.com/allegro/allegro-api/assets/154209376/3ea35b46-446c-4a12-b7a4-28484063ede8)

co do rejestracji jestem na stronie https://apps.developer.allegro.pl.allegrosandbox.pl/
![aplikacje_allegro](https://github.com/allegro/allegro-api/assets/154209376/f0dd6f9b-6914-4a3f-ba4a-9c816df38e24)

przechodzę do 'zarejestruj aplikację'

![nowa_aplikacja](https://github.com/allegro/allegro-api/assets/154209376/ec8e817b-4629-40fe-ab95-6bf9cbf41087)


Po wyklikaniu wszystkich opcji i przyciśnięciu **zarejestruj** nic dalej się nie dzieje. Ani nie otrzymuję błędu ani aplikacja nie jest rejestrowana

**Comment by MaciejFrackowiak** [comment]
Mamy trochę poplątania tu - masz zarejestrowaną aplikację na Sandbox, a adres do autoryzacji używasz z produkcyjnego Allegro. Konsekwencją tego jest odzyskanie hasła - korzystasz z serwisu produkcyjnego, a nie Sandbox. Natomiast odnośnie rejestracji aplikacji - nazwa aplikacji musi być unikalna w skali całego Sandbox, a taka istnieje już - podczas walidacji powinien przy nazwie pojawić się "dymek" z taką informacją. Po prostu nadaj swojej aplikacji bardziej unikalną nazwę.

**Comment by pr0fes0rre** [comment]
Bardzo dziękuję,
Zgadza się, używałem złego adresu problem został rozwiązany. 
Jednak w przypadku próby rejestracji nowej aplikacji zmiana nazwy na bardziej unikalną nie pomaga nie wyświetla się żadna informacja że z nazwą jest coś nie tak, jedynie pole z nazwą zostaje podświetlone na zielono
( abstrakcyjny przykłąd, ten ani żadna inna kombinacja nazw nie daje żadnego efektu)
![allegro_dev_app_create](https://github.com/allegro/allegro-api/assets/154209376/91664d61-7ea6-45e7-81e2-6ffa446e58d1)


Inspekcja wysylanego zapytania pokazuje:
URL: https://edge.allegro.pl.allegrosandbox.pl/developer/my-applications
Status: 403 Forbidden

**Comment by MaciejFrackowiak** [comment]
Proszę aktywuj [dwustopniowe logowanie](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dwustopniowe-logowanie) (domyślny kod: 123456) - to powinno ostatecznie pomóc.

**Comment by pr0fes0rre** [comment]
Tak, włączenie dwustopniowego logowania pomogło, bardzo dziękuję.
