### ISSUE TITLE
Jedna umowa z Pocztex, dwie karty

### ISSUE THREAD

**Issue by akonopka11** [allegro/allegro-api#8855]
Dzień dobry,
Mamy pod jedną umowę z Pocztexem podpięte konto w Elektronicznym Nadawcy, dla którego mamy dwie różne karty i dla każdej z tych kart osobny urząd nadania. W ustawieniach umowy własnej w Allegro jest widoczny tylko jeden z tych urzędów nadania. Jak nadać przesyłkę dla tego drugiego urzędu nadania / drugiej karty?
Pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
W Allegro korzystamy tylko z domyślnej karty, nie ma możliwości zarządzania wieloma kartami jednocześnie.
