### ISSUE TITLE
Filtrowanie zdarzeń po dacie utworzenia zdarzenia

### ISSUE THREAD

**Issue by softlike-zsp** [allegro/allegro-api#8857]
Dzień dobry, 
czy jest możliwość filtrowania zdarzeń po dacie utworzenia zdarzenia w taki sposób: 
https://api.allegro.pl/order/events?type=READY_FOR_PROCESSING&occurredAt.gte=2024-04-15T13%3A20%3A00.000Z

Wysyłam powyższy request do API i otrzymuję niestety zdarzenia poza ustalonym zakresem, więc ten filtr nie działa. A może da się inaczej uzyskać ten efekt ?

**Comment by MaciejFrackowiak** [comment]
Zasób [GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET) ma dostępne ściśle określone filtry: from, type, limit, zatem Twoja kombinacja nie może zadziałać. Możesz zatem skorzystać z parametru "from", aby ustalić początkowe miejsce, od którego otrzymasz dane. Zajrzyj do [poradnika](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#jak-pobrac-dziennik-zdarzen-dla-zamowien), gdzie dokładnie opisaliśmy działanie endpointu.
