### ISSUE TITLE
WZA DHL Odbiór w punkcie

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#8858]
Mam pytanie odnośnie generowania przesyłek DHL przez api, otóż przy probie wygenerowania przesyłki otrzymujemy błąd 
"Punkt nadania przesyłki jest niepoprawny" i teraz pytanie skąd ten punkt nadania można otrzymać? W polu pickup/pointId probowaliśmy podawać id punktu nadawczego DHL lecz błąd jest dalej ten sam.

traceId: ae68b459e8c3804a

**Comment by MaciejFrackowiak** [comment]
Punkty nadania dostępne są w API danego przewoźnika - w przypadku DHL jest to [strona](https://developer.dhl.com/).

**Comment by d3stozaur** [comment]
To moze inaczej powiem jaki mamy problem, nasz klient chce nadać paczki przez nasz system poprzez Wysyłam z Allegro i dla paczek z DHL dostajemy komunikaty błedu: 
 Kod pocztowy punktu nadania przesyłki jest niedostępny
 Punkt nadania przesyłki jest niepoprawny
traceId: eba9a0c5892cdc9d
"serviceId": "07c12933-584e-453d-bee5-60f3f32dfc73"
Czy ten punkt nadawczy to powinniśmy my mieć ustawiony w systemie i wysyłać w requescie czy też można to jakoś ustawić w koncie allegro? Mamy innych klientów którzy korzystaja z tej metody dostawy i nie podają punktu nadawczego i nie ma żadnego problemu.

**Comment by MaciejFrackowiak** [comment]
Punktem nadania występującym jako pointId to punkt z sieci przewoźnika, z którego są odbierane i nadawane przesyłki. Identyfikator ten jak wspomniałem wcześniej można brać z API danego przewoźnika. Jeśli przesyłka ma być nadana po prostu z adresu, to w miejscu "pointId" nie należy niczego podawać, ponieważ miejscem podjęcia jest po prostu adres, a nie specyficzny punkt z punktów odbioru przewoźnika.

**Comment by d3stozaur** [comment]
A czy istnieje jakas strona/tabelka/mozliwosc zobaczenia jakie kody pocztowe sa dostepne? Poniewaz bez podania id punktu nadawczego to dostajemy komunikat Kod pocztowy punktu nadania przesyłki jest niedostępny

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id wywołania, gdzie wysyłasz request już bez pointId.

**Comment by d3stozaur** [comment]
2cf6c5d257e58057

**Comment by MaciejFrackowiak** [comment]
Poprawny kod pocztowy przypisany do wskazanej ulicy to 42-202.

**Comment by d3stozaur** [comment]
teraz wszystko dziala dziekuje
