### ISSUE TITLE
[sandbox] aktywacja konto testowe platnosci

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#886]
Nie mogę potwierdzić konta do sprzedaży na sandboxie bo nie działa bramka testowych płatności. https://payments-simulator.allegrosandbox.pl/index/UTF/NewPayment żaden przycisk nie wywołuje akcji

**Comment by PawelTaberski** [comment]
Podeślij proszę login konta jakie chcesz aktywować.

**Comment by PawelTaberski** [comment]
Konto powinno już być aktywne.

**Comment by d3stozaur** [comment]
działa dziękuję
