### ISSUE TITLE
Wystawienie oferty na serwisach dodatkowych

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#8862]
W jaki sposób wystawiając ofertę mogę ustalić jej widoczność w serwisach dodatkowych? Zdaje się, że dodanie id serwisów w `publication.marketplaces.additional` nie załatwia sprawy; otrzymuję błąd `brak ceny w walucie rynku`.

Czy jeżeli nie ustalę konkretnej ceny w `additionalMarketplaces` nie powinien zadziałać automatyczny przelicznik cen?

**Comment by PrzemyslawLukanowski** [comment]
Reguły przelicznika cen musisz dodatkowo przypisać do oferty, jeśli chcesz, aby cena w ofercie przeliczała się automatycznie. Więcej na ten temat znajdziesz [w naszym poradniku](https://developer.allegro.pl/tutorials/wystawianie-i-zarzadzanie-oferta-w-serwisach-zagranicznych-wwzjP4M8gTZ#jak-przypisac-i-usunac-reguly-przelicznika-cen-w-ofertach). [W czerwcu zautomatyzujemy proces wyświetlania ofert w serwisach dodatkowych](https://developer.allegro.pl/news/zmienimy-proces-widocznosci-oferty-w-serwisach-zagranicznych-4Rxed0jbEsj), będzie się to odbywać na podstawie metod dostawy - wtedy automatycznie będziemy ustawiać cenę dla serwisu dodatkowego.
