### ISSUE TITLE
Problem z wystawianiem aukcji. Parametr zależny nie może przyjąć wartości

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#8866]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

trace-id: c04b6398e36acbc0

Przy wystawianiu aukcji dostaję błąd "Parametr zależny Rozmiar (128610) nie może przyjąć wartości [46], gdy parametr Rodzaj (215534) ma wartości [dół]."

Problem w tym że w jsonie który przesyłam do was nie podaje żadnego parametru o id 128610. Czym jest spowodowany ten błąd?

**Comment by AureliuszBrussy** [comment]
Analizujemy to. Wrócę z wyjaśnieniem.

**Comment by AureliuszBrussy** [comment]
Wskazany w requeście produkt jest utworzony w kategorii 76025 ("Jednoczęściowe"), gdzie parametr Rozmiar (128610) jest wymagany i jego wartość została zapisana w produkcie. Czy jesteś pewien, że ten produkt powinien być wystawiona w kategorii 76024 ("Dwuczęściowe")?
