### ISSUE TITLE
Pole punkt odbiorcy ze wskazanym id nie zostało znalezione

### ISSUE THREAD

**Issue by bartekc7** [allegro/allegro-api#8867]
Dzień dobry,
Mimo podania istniejącego kodu punktu odbioru nie udaje się nadać przesyłki w usłudze Allegro One Box, UPS
Z czego to może wynikać? 
API sandbox.

"point": "AL024WK1"

{
  "commandId": "db5bc822-7b8c-49bc-b75f-a218a8e8514d",
  "status": "ERROR",
  "errors": [
    {
      "code": "BAD_REQUEST",
      "message": "receiver.point with specified PointId was not found",
      "details": null,
      "path": "receiver.point",
      "userMessage": "Pole punkt odbiorcy ze wskazanym id nie zostało znalezione"
    }
  ],
  "shipmentId": null
}

**Comment by AureliuszBrussy** [comment]
Wyjaśniam kwestię tego punktu z odpowiednim zespołem. Wrócę z odpowiedzią.
