### ISSUE TITLE
monitorowanie cen w ofertach innych sprzedających

### ISSUE THREAD

**Issue by zop2690** [allegro/allegro-api#8869]
hej,

czy przez API można pobierać ceny innych ofert zgrupowanych z własną ofertą? Chodzi mi o możliwość monitorowania cen w ofertach innych sprzedających np. na podstawie EAN przy wykorzystaniu API? 

Mówiąc prościej,  listujemy np. EAN i w oparciu o niego otrzymujemy zakres cenowy danego produktu na Allegro i ID poszczególnych ofert innych sprzedających.

Z góry dzięki za informacje.

**Comment by MaciejFrackowiak** [comment]
Nie, nie posiadamy zasobu, który zwracałby tego typu dane.
