### ISSUE TITLE
Dziwny błąd w parametrach podczas wywoływania /sale/offers

### ISSUE THREAD

**Issue by lwadas** [allegro/allegro-api#887]
Dzień dobry, 

Znalazłem dziwny błąd niew wiem czy przydatny ale, jak lista parametrów ma brakujące klucze tzn:
`parameters = array( 0=>array(...), 1=>array(...), 3=>array(...) )`

To serwer zwraca takie mało mówiące info ;)
`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers","userMessage":null}]}`

**Comment by MartaNowaczyk** [comment]
@Iwadas Dzięki. Weźmiemy to pod uwagę jak będziemy pracować nad opisem błędów.
