### ISSUE TITLE
API needs refreshing

### ISSUE THREAD

**Issue by justynapalka** [allegro/allegro-api#8870]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Hi,
can I get a support with the below one?

We are getting a message ' PROD Allegro API needs refreshing. Please accept via https://allegro.pl/uzytkownik/bezpieczenstwo/skojarz-aplikacje?code=zsyyaiict
The link expires in 5 minutes'

After clicking the link and message in Allegro portal 'It worked', the message is still popping up.

Thanks
Justyna

**Comment by MaciejFrackowiak** [comment]
It looks like a message from some application - please, contact application support.
