### ISSUE TITLE
API - Wyciąganie znacznika SUPER CENA z WŁASNYCH ofert

### ISSUE THREAD

**Issue by basarakrystian** [allegro/allegro-api#8871]
Wiem, że jest opcja wyciągania tego za pomocą: [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing), jednak po zapytaniu o weryfikację aplikacji dostaliśmy informację zwrotną:

> Wracam z informacjami w sprawie nadania dostępów do zewnętrznym programów. Dostałem wiadomość, że ze względów biznesowych cały proces został wstrzymany, dlatego nie będzie można udzielić zgody na weryfikację aplikacji.
> 
> Jeśli proces zostanie wznowiony, to będziemy Państwa o tym informować.

W związku z tym, czy jest jakakolwiek inna opcja, żeby wyciągnąć super cenę z ofert zalogowanego użytkownika?

**Comment by MaciejFrackowiak** [comment]
Nie ma takiej możliwości.
