### ISSUE TITLE
You have to provide shipping rates and offer's location.

### ISSUE THREAD

**Issue by mcrock** [allegro/allegro-api#888]
Witam,
Na sandboxie przy próbie wystawienia ogłoszenia (ADVERTISEMENT) w kategorii motoryzacja otrzymuję komunikat: 

> You have to provide shipping rates and offer's location.

Jeszcze w sobotę identyczna próba kończyła się powodzeniem. Dodam, że oczywiście mam ustawioną lokalizację, a dziś podczas prób ustawiałem także 'delivery' => null jak znalazłem na przykładach (w sobotę działało bez tego). Próbowałem także zarówno z wersją public jak i beta. :( 

Jakaś podpowiedź?

**Comment by MartaNowaczyk** [comment]
@mcrock Dziękujemy za info. Sprawdzimy.

**Comment by MartaNowaczyk** [comment]
@mcrock sprawdziłam i udało mi się wystawić ogłoszenie bez błędów, które opisujesz. Poniżej mój najświeższy curl z requestem:
`curl -X PUT \
  https://api.allegro.pl.allegrosandbox.pl/sale/offers/6206013641 \
  -H 'Authorization: Bearer {token}
  -H 'accept: application/vnd.allegro.public.v1+json' \
  -H 'content-type: application/vnd.allegro.public.v1+json' \
  -d '{
    "id": "6206013641",
    "name": "FORD F150 test ogłoszenie",
    "category": {
        "id": "146727"
    },
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_2"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "1",
            "valuesIds": [],
            "values": [
                "2009"
            ],
            "rangeValue": null
        },
        {
            "id": "4",
            "valuesIds": [],
            "values": [
                "190000"
            ],
            "rangeValue": null
        },
        {
            "id": "5",
            "valuesIds": [],
            "values": [
                "4600"
            ],
            "rangeValue": null
        },
        {
            "id": "14",
            "valuesIds": [],
            "values": [
                "235"
            ],
            "rangeValue": null
        },
        {
            "id": "12",
            "valuesIds": [
                "12_3"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "128789",
            "valuesIds": [],
            "values": [
                "5"
            ],
            "rangeValue": null
        },
        {
            "id": "3",
            "valuesIds": [
                "3_10"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "178",
            "valuesIds": [
                "178_1"
            ],
            "values": [],
            "rangeValue": null
        }
    ],
    "ean": null,
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>To sedan. Uczciwy, wielki, amerykański luksusowy sedan, prawdziwy potomek krążowników szos sprzed wielu dekad.</p>"
                    }
                ]
            }
        ]
    },
    "compatibilityList": null,
    "images": [
        {
            "url": "https://1.allegroimg.allegrosandbox.pl/original/03de3d/a50107a0427e8bfc6447abbedda1"
        },
        {
            "url": "https://b.allegroimg.allegrosandbox.pl/original/031ce4/be3181494aa6a1572452e646d24b"
        },
        {
            "url": "https://0.allegroimg.allegrosandbox.pl/original/03c351/dc0f96574733b8edf2ca56d491c0"
        }
    ],
    "sellingMode": {
        "format": "ADVERTISEMENT",
        "price": {
            "amount": "150000",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null
    },
    "stock": null,
    "publication": {
        "duration": "PT240H",
        "status": "ACTIVE",
        "startingAt": null,
        "endingAt": "2018-11-24T06:39:08Z"
    },
    "delivery": {
        "shippingRates": null,
        "handlingTime": null,
        "additionalInfo": null,
        "shipmentDate": null
    },
    "payments": {
        "invoice": "NO_INVOICE"
    },
    "afterSalesServices": null,
    "additionalServices": null,
    "sizeTable": null,
    "promotion": null,
    "location": {
        "countryCode": "PL",
        "province": "WIELKOPOLSKIE",
        "city": "Poznań",
        "postCode": "60-166"
    },
    "external": null,
    "attachments": [],
    "contact": {
        "id": "bb7c2be2-c135-4fae-b3d7-317b0e8b377a"
    },
    "validation": {
        "errors": [],
        "validatedAt": "2018-11-14T06:39:06.229Z"
    },
	"createdAt": "2018-11-14T06:47:11Z",
    "updatedAt": "2018-11-14T06:47:11.37Z"
}'`

**Comment by mcrock** [comment]
Dziękuję za info - porównam sobie z tym co ja wysyłam i zobaczymy :)

**Comment by k8207** [comment]
Witam
Mam ten sam problem. Jakiś czas temu testowałem i ogłoszenie zostało dodane bez błędów.  Obecnie otrzymuję:
"errors": [
            {
                "code": "VALIDATION_ERROR",
                "message": "You have to provide shipping rates and offer's location.",
                "details": "",
                "path": "",
                "userMessage": "Podaj identyfikator cennika dostawy razem z lokalizacją."
            }
        ]

**Comment by MartaNowaczyk** [comment]
@mcrock @k8207 dzięki za zgłoszenie. Potwierdzamy ten błąd i będziemy nad nim pracować.

**Comment by redwingecommerce** [comment]
Czy jest ustalony termin naprawy buga?
