### ISSUE TITLE
Brak możliwości dodania nowej aplikacji do Sandbox

### ISSUE THREAD

**Issue by radoslawkozlowskiis** [allegro/allegro-api#8882]
Występuje problem:
 - [X] ze środowiskiem testowym
 - [X] na portalu https://developer.allegro.pl

Dzień dobry,
przy próbie dodania nowej aplikacji na środowisku testowym, otrzymuję błąd 403 w konsoli.

Nazwa sprzedawcy: sanbox_innrosa2

![image](https://github.com/allegro/allegro-api/assets/121158873/616b3444-4c98-46d5-a299-4c7fe4d24050)

**Comment by AureliuszBrussy** [comment]
Spróbuj aktywować [dwustopniowe logowanie](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dwustopniowe-logowanie) (domyślny kod: 123456) - to powinno rozwiązać problem.
