### ISSUE TITLE
Modyfikacja stanu magazynowego w wielu ofertach jednocześnie

### ISSUE THREAD

**Issue by netfarma** [allegro/allegro-api#889]
Witam,
czy (i kiedy) będzie dostępna metoda pozwalająca na modyfikację ilości w kilkunastu ofertach jednocześnie?

Prowadzimy sprzedaż w wielu kanałach i stan magazynowy zmienia się u nas dynamicznie. 
Każda synchronizacja stanów to wiele produktów do zaktualizowania i przesyłanie całych obiektów ofert (jak to zostało zaproponowane tu https://github.com/allegro/allegro-api/issues/849#issuecomment-435307063) po to aby zaktualizować tylko stan magazynowy to wg mnie zbyt duży narzut.

Nowa metoda mogłaby wyglądać podobnie do 
`/sale/offer-modification-commands/{commandId}` 

z tą różnicą, że pole `modification` oraz `offerCriteria` umieściłbym wewnątrz `offers`

np
```
  "offers": [
        {
           "offerCriteria": [...],
           "modification": {
              "stock": {
                    "available": 0,
              },
              ...
          }
        }
      ]

```

**Comment by MartaNowaczyk** [comment]
@netfarma dziękujemy za propozycję :) Kończymy pracę nad podobnym rozwiązaniem i niedługo (mam nadzieję, że w ciągu tego tygodnia) opublikujemy informacje na ten temat.
