### ISSUE TITLE
Mark message(s) as unread

### ISSUE THREAD

**Issue by mathiasdeknudt** [allegro/allegro-api#8890]
Dear,

We were wondering if it is possible to mark a message in the Message Center as UNREAD after it has been read? This feature would be extremely useful, as multiple colleagues are using the platform, and it would help clarify which messages still require a response.

Thank you in advance.

Kind regards,

Mathias

**Comment by PrzemyslawLukanowski** [comment]
Hello, such feature is not available either on the website or via API.

**Comment by mathiasdeknudt** [comment]
Dear,

Ok, thank you. Is this something that you would consider to add as a possible feature? I believe it would be something all sellers would be very happy with. Moreover, I believe it would be also beneficial for the customers and it could drastically reduce support time on your side.

Thank you in advance

Mathias

**Comment by mathiasdeknudt** [comment]
Is there another place where I can leave ideas for non-API development?

**Comment by PrzemyslawLukanowski** [comment]
You can send them via [contact form.](https://allegro.pl/pomoc/kontakt)

**Comment by mathiasdeknudt** [comment]
Ok, thanks
