### ISSUE TITLE
Products automatically changing to the Offer Status 'Expired'

### ISSUE THREAD

**Issue by mathiasdeknudt** [allegro/allegro-api#8891]
Dear,

Some of our products with the Offer Status "active" seem to automatically get the status "expired" after being "active" for some time. We were wondering what is causing this and how we can prevent our products from getting this status?

Thank you in advance.

Kind regards,

Mathias

**Comment by PrzemyslawLukanowski** [comment]
The "expired" status means that the time you have defined in the "publication.duration" field has passed. For example, if you provided "P3D", it means the offer was active for 3 days and we ended it after that time.  To prevent this you can send null in the "publication.duration" field. That way, the offer will be active until all items are sold.

**Comment by mathiasdeknudt** [comment]
Dear,

Thank you, that really helpful.

Products which reach 0 stock also seem to get the 'expired' status. Will they automatically be listed again when we have stock again for these products?

Thank you in advance.

Mathias

**Comment by PrzemyslawLukanowski** [comment]
For these offers, you should get "EMPTY_STOCK" status, as in our [documentation](https://developer.allegro.pl/documentation#operation/getProductOffer):

<img width="712" alt="Zrzut ekranu 2024-04-18 o 08 48 15" src="https://github.com/allegro/allegro-api/assets/51473661/fa3b8b04-9224-4686-ac76-317ecead2536">

No, such an offer will not be activated automatically after adding stock, you need to use [PATCH /sale/product-offers/{offerId)](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#offer-status-change) or [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#relisting-offers) to activate them. 

Offer can be relisted automatically, with the same initial stock, if you set  "publication.republish" field as true:

<img width="649" alt="Zrzut ekranu 2024-04-18 o 08 55 29" src="https://github.com/allegro/allegro-api/assets/51473661/3cb04a1f-444e-4575-be9d-612b983fe141">

**Comment by mathiasdeknudt** [comment]
Ok, thank you!
