### ISSUE TITLE
Dostaję "OfferAccessDeniedException" przy próbie wystawienia oferty

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#8892]
Według mnie zarejestrowana aplikacja posiada potrzebne uprawnienia natomiast przy próbie wystawienia oferty dostaję:

```
{
   "errors":[
      {
         "code":"OfferAccessDeniedException",
         "message":"Forbidden",
         "details":null,
         "path":"",
         "userMessage":"Access denied. You are not authorized to perform operations on the indicated offer",
         "metadata":{
         }
      }
   ]
}
```

trace-id: e5e7a29969bde6db

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Zwracamy taki komunikat, ponieważ konto użytkownika, który próbuje wystawić ofertę, to konto zwykłe. Za pomocą API oferty mogą wystawiać wyłącznie konta firmowe.

**Comment by tomylee0** [comment]
Dziękuję. Pozdrawiam.

**Comment by many-to-one** [comment]
No właśnie ja dostaję dokładnie taki sam błąd, a wcześniej działało bez problemu, a mam konto FIRMOWE

**Comment by PrzemyslawLukanowski** [comment]
@many-to-one Podaj proszę w takim razie przykładowe trace-uid wywołania, na które odpowiedzieliśmy tym błędem.

**Comment by many-to-one** [comment]
Gdzie mogę znależć trace-id?

**Comment by PrzemyslawLukanowski** [comment]
Wartość zwracamy w nagłówku odpowiedzi. Jeśli nie możesz jej znaleźć, możesz podać id/login konta.

**Comment by many-to-one** [comment]
retset

**Comment by many-to-one** [comment]
trace id: 59c1e5879638d91a

**Comment by PrzemyslawLukanowski** [comment]
@many-to-one Otrzymujesz ten błąd, ponieważ oferta należy do konta, o którym wspomniałeś, ale request wykonujesz będąc zautoryzowany na innym koncie. Takim, które nie jest właścicielem tej oferty, stąd odpowiedź 403 Forbidden.

**Comment by many-to-one** [comment]
Tak jest, już znalazłem swój błąd w kodzie, dziekuję
