### ISSUE TITLE
Pobieranie informacji z katalogu SANDBOX

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#8897]
Dlaczego gdy udaje mi się wystawić aukcję z eanem 8653142287413 to pozniej nie moge pobrac informacji o tym produkcie przez ean?
Na produkcji jest okej

/sale/products?mode=GTIN&phrase=8653142287413

**Comment by AureliuszBrussy** [comment]
Czy możesz wskazać id produktu o który chodzi?

**Comment by AureliuszBrussy** [comment]
Czy możesz wskazać id produktu o który chodzi?
