### ISSUE TITLE
Błąd CheckoutFormNotFoundException podczas pobierania szczegółów zamówienia przez endpoint: order/checkout-forms/{checkoutFormId}

### ISSUE THREAD

**Issue by studiowizjo** [allegro/allegro-api#8898]
Wysylajac zapytanie GET na endpoint: order/checkout-forms/cab01d70-ecfb-11ee-b593-3bd3bdb54a12 otrzymujemy odpowiedz:

```json
{
    "errors": [
        {
            "code": "CheckoutFormNotFoundException",
            "message": "Checkout form cab01d70-ecfb-11ee-b593-3bd3bdb54a12 not found",
            "details": null,
            "path": "/order/checkout-forms/cab01d70-ecfb-11ee-b593-3bd3bdb54a12",
            "userMessage": "Checkout form cab01d70-ecfb-11ee-b593-3bd3bdb54a12 not found"
        }
    ]
}
```

Dlaczego pokazuje, ze to ID nie zostalo znalezione, skoro otrzymalismy je ze zdarzenia pobranego z endpointu: order/events z pola (order -> checkoutForm -> id)?

**Comment by AureliuszBrussy** [comment]
Kupujący wykonał oddzielne zakupy, a następnie łącznie je opłacił. Otrzymujesz wtedy nowy event z nowym numerem zamówienia, a stare usuniemy. Aby zidentyfikować taką sytuację możesz oprzeć się na pojedynczym akcie zakupowym - lineItem.id (jeżeli jeden lineItem.id występuje w kilku eventach oznacza to, że mamy do czynienia z połączeniem zakupów przez kupującego).
