### ISSUE TITLE
[REST] Sandbox post - NotAllowedException - An error has occurred

### ISSUE THREAD

**Issue by Sojtin** [allegro/allegro-api#890]
Zgodnie z tutorialem z https://developer.allegro.pl/sale/#step-6-draft próbuje utworzyć drafta. Dane takie jak w przykładzie. Header tak samo. Token ważny - GET na np https://api.allegro.pl.allegrosandbox.pl/sale/categories/89009/parameters działa i zwraca dane. Natomiast w odpowiedzi na POSTa z przykładu dostaje:

`         'code' => 'NotAllowedException',
                        'message' => 'An error has occurred',
                        'details' => null,
                        'path' => null,
                        'userMessage' => 'An error occurred'`

Jak mam to interpretować? W czym problem?

**Comment by MartaNowaczyk** [comment]
@Sojtin Musiałabym zobaczyć co przesyłasz w requeście dla POST /sale/offers. Podeślij proszę curla do sprawdzenia.

**Comment by Sojtin** [comment]
@MartaNowaczyk problemem był doklejany slash na końcu URL w nieoficjalnym kliencie php.

**Comment by MartaNowaczyk** [comment]
@Sojtin dzięki za info. Zamykam

**Comment by premax** [comment]
> @MartaNowaczyk problemem był doklejany slash na końcu URL w nieoficjalnym kliencie php.

Niech zgadnę, chodziło o klienta https://github.com/Wiatrogon/php-allegro-rest-api oraz funkcję getUri() ?   Właśnie straciłem parę godzin na rozgryzienie tego, dzięki.
