### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Shoppinhouse** [allegro/allegro-api#8901]
Dzień dobry, proszę o informację w jaki sposob ustawic api i gdzie to zrobic. Sprzedaję ebooka przez wordpress woocommerce, ebook jest mojego autorstwa i jestem oficjalnym wydawcą. W jaki sposob i gdzie samodzielnie zintegrowac sprzedaż ebooków z allegro?

**Comment by PrzemyslawLukanowski** [comment]
Aby otrzymać dostęp do API dla ebooków, skontaktuj się proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). Po swojej stronie udostępniamy zasoby, które możesz zaimplementować po swojej stronie. Nie posiadamy jednak wiedzy, jak działa wordpress woocommerce, dlatego nie będziemy mogli pomóc w konfiguracji tego oprogramowania.

**Comment by PrzemyslawLukanowski** [comment]
Możesz napisać na adres ebooki@allegro.com, więcej szczegółów znajdziesz [w tym artykule](https://help.allegro.com/sell/pl/a/jakich-przedmiotow-nie-mozna-wystawiac-na-allegro-a-jakie-mozna-wystawiac-warunkowo-8dvEzZMRkT8#publikacje-elektroniczne-ebooki-i-audiobooki-).

**Comment by Shoppinhouse** [comment]
Dzień dobry, próbowałam, przekoerowali mnie na forum
    Pozdrawiam,Barbara KornakShoppinhouse Specjalistyczny Sklep ZoologicznyM: +48 530 555 ***@***.*** NASZĄ OFERTĘ UBEZPIECZEŃ- UBEZPIECZYMY RÓWNIEŻ PSA I KOTA!STRONA Z PEŁNĄ OFERTĄ UBEZPIECZEŃ ONLINEZAPRASZAMY DO SKLEPU ZOOLOGICZNEGO
  

 Od: PrzemyslawLukanowski ***@***.***>Wysłano: piątek, kwietnia 19, 2024 07:25Do: allegro/allegro-api ***@***.***>DW: Shoppinhouse ***@***.***>; Author ***@***.***>Temat: Re: [allegro/allegro-api] API (Issue #8901) 
Możesz napisać na adres ***@***.***, więcej szczegółów znajdziesz w tym artykule.

**Comment by PrzemyslawLukanowski** [comment]
Proszę w takim razie napisać bezpośrednio na [ebooki@allegro.com](mailto:ebooki@allegro.com).

**Comment by Shoppinhouse** [comment]
Z adresu ebooki przekierowali mnei na forum bo nie potrafili mi pomóc :(
    Pozdrawiam,Barbara KornakShoppinhouse Specjalistyczny Sklep ZoologicznyM: +48 530 555 ***@***.*** NASZĄ OFERTĘ UBEZPIECZEŃ- UBEZPIECZYMY RÓWNIEŻ PSA I KOTA!STRONA Z PEŁNĄ OFERTĄ UBEZPIECZEŃ ONLINEZAPRASZAMY DO SKLEPU ZOOLOGICZNEGO
  

 Od: PrzemyslawLukanowski ***@***.***>Wysłano: piątek, kwietnia 19, 2024 07:54Do: allegro/allegro-api ***@***.***>DW: Shoppinhouse ***@***.***>; Author ***@***.***>Temat: Re: [allegro/allegro-api] API (Issue #8901) 
Proszę w takim razie napisać bezpośrednio na ***@***.***

**Comment by PrzemyslawLukanowski** [comment]
Skontaktowałem się z zespołem z tego adresu mailowego, jednak nie mogą potwierdzić, aby wczoraj lub dziś doszła do nich wiadomość. Być może doszło do jakiegoś nieporozumienia, napisz proszę wiadomość jeszcze raz.

**Comment by Shoppinhouse** [comment]
dzień dobry, przesyłam wiadomość, dostałam ją 15,04
    Pozdrawiam,Barbara KornakShoppinhouse Specjalistyczny Sklep ZoologicznyM: +48 530 555 ***@***.*** NASZĄ OFERTĘ UBEZPIECZEŃ- UBEZPIECZYMY RÓWNIEŻ PSA I KOTA!STRONA Z PEŁNĄ OFERTĄ UBEZPIECZEŃ ONLINEZAPRASZAMY DO SKLEPU ZOOLOGICZNEGO
  

 Od: PrzemyslawLukanowski ***@***.***>Wysłano: piątek, kwietnia 19, 2024 09:50Do: allegro/allegro-api ***@***.***>DW: Shoppinhouse ***@***.***>; Author ***@***.***>Temat: Re: [allegro/allegro-api] API (Issue #8901) 
Skontaktowałem się z zespołem z tego adresu mailowego, jednak nie mogą potwierdzić, aby wczoraj lub dziś doszła do nich wiadomość. Być może doszło do jakiegoś nieporozumienia, napisz proszę wiadomość jeszcze raz.

**Comment by PrzemyslawLukanowski** [comment]
Udało mi się dotrzeć do tej korespondencji i widzę, że 9 kwietnia, w zgłoszeniu 41213451 otrzymała Pani instrukcję, która dotyczy integracji z API do ebooków.

**Comment by Shoppinhouse** [comment]
Szukalam, nie mam meila z takiego dnia

**Comment by PrzemyslawLukanowski** [comment]
Wiadomość zostałą wysłana o 15:33, tytuł "Re: Odpowiedź na zgłoszenie nr "41213451" [ ref:!00D240aE05.!500Ti084EG4:ref ]". Jeśli mimo wszystko nie może Pani tego odnaleźć, prosiłbym o ponowny kontakt przez formularz, powołując się na ten numer sprawy, lub na adres ebooki@allegro.com.

**Comment by Shoppinhouse** [comment]
znalazlam, ale link https://developer.allegro.pl/tutorials/jak-zaczac-prace-z-rest-api-4RAvV2bgwtj nie działa

**Comment by PrzemyslawLukanowski** [comment]
Prawidłowy link to https://developer.allegro.pl/tutorials/pierwsze-kroki-MRwYEoOq0im.
