### ISSUE TITLE
Aktywowanie konto allegro

### ISSUE THREAD

**Issue by TuanDangIT** [allegro/allegro-api#8903]
Proszę o aktywacje konta allegro:
bicofirma@gmail.com

Pozdrawiam.

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem to konto, jest to jednak konto zwykłe. Jeśli chcesz wystawiać i zarządzać ofertami przez API, musisz posiadać konto firmowe. Możesz zmienić rodzaj obecnego konta lub założyć nowe.

**Comment by TuanDangIT** [comment]
Zamieniłem już, ale dalej nie mogę wystawiać i zarządzać ofertami przez API.

**Comment by PrzemyslawLukanowski** [comment]
Skonfiguruj jeszcze proszę [ustawienia wypłat](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat) i daj znać, wtedy będę mógł aktywować to konto.

**Comment by TuanDangIT** [comment]
Dodałem. W trakcie weryfikacji.

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem konto.

**Comment by TuanDangIT** [comment]
Zaraz sprawdzę. Dziękuje bardzo.
