### ISSUE TITLE
How to differentiate betweeen Fulifillment by Merchant and Fulfillment by Allegro(One Fulfillment by Allegro) in the order?

### ISSUE THREAD

**Issue by mohan-mandal-pattern** [allegro/allegro-api#8904]
Hi there, I was wondering if there is a specific attribute that can help us distinguish between orders that are fulfilled by the merchant versus those that are fulfilled by Allegro. Also, I have a question regarding the endpoint located at https://developer.allegro.pl/documentation#tag/Fulfillment-Parcels. Specifically, I would like to know how long it takes after a customer creates an order for the parcel to be ready, and how long it takes for this endpoint to provide information on products that are shipped directly from the warehouse to the customer.

**Comment by PrzemyslawLukanowski** [comment]
Hello, a merchant with the One Fulfillment type of account can only fulfill orders by Allegro warehouse, so all of the orders on this account will be One Fullfilment type, there's no need to distinguish them. When it comes to your second question, these operations should take place within 24 hours, below you can see shipping and delivery hours to customers:
<img width="622" alt="Zrzut ekranu 2024-04-19 o 08 04 13" src="https://github.com/allegro/allegro-api/assets/51473661/b27697a6-5fa6-41ab-b059-bae9e89bfbfd">

**Comment by mohan-mandal-pattern** [comment]
If we connect the One fulfilment account with the Business account then how we can differentiate between FBM and One fulfilment by Allegro? 
When we fetch the orders from this endpoint - https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET we do not differentiate between FBM orders and Fulfilment by Allegro orders. So can you tell me little more details how we can differentiate the orders if the account is same for both One fulfilment and Business account?

**Comment by PrzemyslawLukanowski** [comment]
Even if your accounts are linked, you should receive orders only for the account for which you are authorized with your token. So if you use a token for the One fulfilment account , in the response we will return only 1F orders. If it's different, and you are receiving orders from both accounts, please send me a sample trace-id with the order ID that doesn't belong to the account you've got token.

**Comment by mohan-mandal-pattern** [comment]
Could you clarify if creating a One Fulfillment Account based on the Business Account (https://allegro.pl/pomoc/dla-sprzedajacych/one-fulfillment-by-allegro/jak-zaczac-korzystac-z-one-fulfillment-by-allegro-aMDP0d4dYs4#how-to-create-a-one-fulfillment-account-based-on-a-business-account) will result in a different Client ID and Client Secret for the One Fulfillment Account? This is my final question. Thank you.

**Comment by PrzemyslawLukanowski** [comment]
No, you can still use your already registered client Id and client secret.

**Comment by mohan-mandal-pattern** [comment]
You mean both the account have same client id and client secret?

**Comment by PrzemyslawLukanowski** [comment]
Using your already registered clientId you can just authenticate another user (the one fulfillment account) to use that app. There's no need to register another application, because one clientId can be used by multiple users.

**Comment by mohan-mandal-pattern** [comment]
How will we get the different access tokens and refresh tokens for different accounts?

**Comment by PrzemyslawLukanowski** [comment]
You should be logged in as a One Fulfillment account and authorize the application. You can find more details in [our tutorial](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY). It depends on which account is authorizing the application, and for this account, you will get a pair of tokens.

**Comment by mohan-mandal-pattern** [comment]
If both the accounts authorize the same application then will we get the different access token and refresh token or same for both accounts?

**Comment by mohan-mandal-pattern** [comment]
Is it better to have the same application for different accounts or different applications for different accounts? We are going to use both accounts and will get the orders for both the FBM and One fulfilment type.
One more question, can both accounts access the application simultaneously and able to fetch orders for both the accounts simultaneously?

**Comment by PrzemyslawLukanowski** [comment]
The best and recommended approach is to have only one application that can be used by multiple users. 

> One more question, can both accounts access the application simultaneously 

Yes.

> and able to fetch orders for both the accounts simultaneously?

Both accounts can make requests simultaneously, but for account "A" we will return only orders that belong to this account, we will not return orders for "B" account. Tokens have encoded information about user ID, and for this account orders will be returned.

**Comment by mohan-mandal-pattern** [comment]
Thank you very much, @PrzemyslawLukanowski, for patiently answering my questions! Have a great day!

**Comment by PrzemyslawLukanowski** [comment]
No problem, I'm glad I could help :) Thank you and have a great day too!
