### ISSUE TITLE
Cudne kody błędów i ich odszyfrowywanie

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#891]
Endpoint: https://api.allegro.pl/sale/offer-variants/{setId}
metoda PUT z headersami:
```
{
            'Authorization': 'Bearer ...',
            'Accept': 'application/vnd.allegro.beta.v1+json',
            'Content-Type': 'application/vnd.allegro.beta.v1+json',
            'Accept-Language': 'pl',
        }
```
request:
```
{'name': 'Czółenka brązowe skórzane',
 'offers': [{'id': 7352061993},
            {'id': 7352062046},
            {'id': 7352062034},
            {'id': 7352062024},
            {'id': 7352062006}],
 'parameters': [{'id': '26388'}]}
```
I najważniejsze, co się zje**:
```
{'errors': [{'code': 'ERROR', 'message': 'An error has occurred', 'details': None, 'path': None, 'userMessage': None}]}
```
Ja rozumiem, że ciężko wymyślić cokolwiek sensownego jako błąd, ale wyszstko byłoby lepsze od tego. A żeby było zabawniej, to jeszcze tydzień temu requesty budowane w ten sam sposób działały...

**Comment by anih** [comment]
W sumie doszedłem co jest nie tak, ale jednak informacja, że aukcje nie należą do użytkownika byłaby ułatwiająca życie.

**Comment by MartaNowaczyk** [comment]
@anih Rozumiem, będziemy mieli to na uwadze.

**Comment by lukasnet** [comment]
@MartaNowaczyk Macie to na uwadze , ale nic z tym jak zwykle nie robicie! 
Przy edycji aukcji dostaje "An error has occurred" i weź teraz szukaj i męcz się co jest nie tak...  chyba temu powinny służyć te pola 'details' i 'userMessage' ?!
**Czy nie możecie zwracać czytelnych błędów co konkretnie?! tylko robicie taką amatorszczyznę! żenada :(** 

Tylko proszę mi pisać aby przesyłał wam szczegóły i pełnego requesta bo nie o to chodzi abyśmy ciągle wymieniali się tego typu postami etc. tylko zróbcie porządną obsługę błędów!

**Comment by MartaNowaczyk** [comment]
@lukasnet 

> Macie to na uwadze , ale nic z tym jak zwykle nie robicie!
skąd to możesz wiedzieć. Wszystkich błędów nie sprawdziłeś przed i po zmianach. 

Mamy to na uwadzę przy tworzeniu nowych zasobów i poprawiamy przy wcześniejszych jeśli mamy pełne dane i zweryfikowaną sytuację. 

> Tylko proszę mi pisać 

To mam pisać czy jednak nie? ;)
