### ISSUE TITLE
Brak Client_secret w środowisku sandboxowym 

### ISSUE THREAD

**Issue by El-Karollo** [allegro/allegro-api#8910]
Witam serdecznie.
Walczę z środowiskiem testowym już trochę czasu i.. niestety, nie mogę tego ogarnąć.
Mam konto, które jest aktywowane i ma 2 stropniowe uwierzytelnianie.

Po zrobieniu aplikacji, gdy wchodzę w szczegóły - niestety, jest tylko client_id, bez widocznego client_secret.
Ponadto, jak edytuję API to wszystkie uprawnienia są odznaczone. Po zaznaczeniu ich, gdy klikam zapisz, nic się nie dzieje.
Gdy patrzę w Live HTTP Headers podczas klikania "zapisz" wychodzi taki nagłówek:
``{"name":null,"description":"sandbox","applicationType":"HEADLESS","redirectUris":[],"publicScopes":["allegro:api:ads","allegro:api:bids", [...] }  
PUT: HTTP/2.0 404   
date: Fri, 19 Apr 2024 10:16:28 GMT  
content-type: application/vnd.allegro.public.v1+json  
[...]``

Chciałbym już zacząć pracę nad integracją sklepu internetowego z allegro, ale idzie mi to strasznie topornie :)
Pisałem maila przez formularz kontaktowy, ale po tygodniu oczekiwań stwierdziłem, że napiszę tutaj.
Mój ID klienta w sandbox'ie to: client:106980365

Serdecznie dziękuję za odpowiedź,
Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Jest to znany nam problem, opisany wcześniej w wątku https://github.com/allegro/allegro-api/issues/8902. Pracujemy nad jego wyeliminowaniem.

**Comment by MaciejFrackowiak** [comment]
Problem już nie występuje, jednak w wyniku błędu po naszej stronie byliśmy zmuszeni usunąć problematyczne aplikacje. Proszę o założenie nowej i jednocześnie przepraszam za powstałe utrudnienia.

**Comment by El-Karollo** [comment]
Niestety, ale na moim koncie nadal są aplikacje których nie mogę usunąć. Problem ciągle istnieje.
Client id: 106980365

**Comment by AureliuszBrussy** [comment]
@El-Karollo czy problem aktualnie występuje? Mógłbyś podać nazwy tych aplikacji?

**Comment by El-Karollo** [comment]
@AureliuszBrussy  tak, występuje. Nadal nie widać Secret oraz nie można usunąć aplikacji. Ich nazwy to: modelmania_eu_box oraz modelmania_eu_sandbox

**Comment by AureliuszBrussy** [comment]
@El-Karollo pracujemy jeszcze na naprawą dla Sandboxa. Wrócę z informacją po poprawce.

**Comment by El-Karollo** [comment]
Pragnę zaznaczyć, że wadliwe aplikacje zostały skasowane przez zarządzających - za co dziękuję. Zaś nowa aplikacja na sandboxie wydaję się być działająca. Secret_id już się pokazuje. Samych odpowiedzi od API jeszcze nie testowałem :)

**Comment by AureliuszBrussy** [comment]
@El-Karollo potwierdzam, poprawiliśmy to.
