### ISSUE TITLE
Pobieranie danych oferty za pomocą external.id

### ISSUE THREAD

**Issue by speedygopl** [allegro/allegro-api#8913]
Jak pobrać dane oferty za pomocą get sale/product-offers/ kiedy nie mam offerid? Mam do dyspozycji jedynie external.id oferty.

**Comment by PrzemyslawLukanowski** [comment]
W takim przypadku najpierw skorzystaj z [GET /sale/offers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET) wraz z użyciem parametru `external.id`. W ten sposób poznasz ID oferty, które możesz przekazać później w zasobie /sale/product-offers/{offerID}, aby pobrać szczegóły oferty.
