### ISSUE TITLE
Możliwość wyboru zwracanych pól w zapytaniu GET

### ISSUE THREAD

**Issue by aygore1** [allegro/allegro-api#8915]
Hej, 

czy istnieje możliwość zmniejszenia wielkości odpowiedzi GET poprzez wybór konkretnych pól np.

GET https://api.allegro.pl/sale/product-offers/1234567889**?fields=["name"]**
Niestety 'fields' nie działa a w dokumentacji nie znalazłem.

Pozdrawiam!

**Comment by PrzemyslawLukanowski** [comment]
Nie, nie udostępniamy takiej możliwości. Jeśli coś miałoby się zmienić w tym temacie, opublikujemy komunikat na naszej stronie.
