### ISSUE TITLE
Call the interface: https://api.allegro.pl/sale/product-offers to publish, categoryid = 67430, there is no corresponding attribute "'Stan' (id: 11323)" in this category, but the interface reports an error: Parameter Stan defined ambiguously. The specified value and the specified dictionary value Nowy do not match

### ISSUE THREAD

**Issue by VEVOR** [allegro/allegro-api#8918]
Call the interface: https://api.allegro.pl/sale/product-offers to publish, categoryid = 67430, there is no corresponding attribute "'Stan' (id: 11323)" in this category, but the interface reports an error: Parameter Stan defined ambiguously. The specified value and the specified dictionary value Nowy do not match

Input： **categoryID：67430**
{"additionalMarketplaces":{"allegro-sk":{"sellingMode":{"price":{"amount":"58.99","currency":"EUR"}}},"allegro-cz":{"sellingMode":{"price":{"amount":"1559","currency":"CZK"}}}},"afterSalesServices":{"impliedWarranty":{"id":"1af05c99-e682-4302-962e-2d1ce846d453"},"returnPolicy":{"id":"6b80a909-599c-469b-adb0-7bb537a6451e"}},"category":{"id":"67430"},"delivery":{"handlingTime":"P2D","shippingRates":{"id":"a4d396b2-e72b-4114-8420-b974b4605bae"}},"description":{"sections":[{"items":[{"type":"IMAGE","url":"https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-1.2.jpg"},{"content":"<h1>Mała lodówka 6L</h1><p></p><p>Tę wielofunkcyjną minilodówkę o pojemności 6 litrów można schłodzić do 59°F / 15℃ poniżej temperatury otoczenia i potrzebuje tylko dwóch godzin, aby osiągnąć najlepszy efekt chłodzenia! Niski poziom decybeli ≤38 dB nie zakłóci pracy i życia. Wyposażona w domowy zasilacz i przewód zasilający USB, ta lodówka jest idealna do użytku wewnątrz i na zewnątrz, gdzie trzeba przechowywać żywność, napoje, mleko matki, lekarstwa, kosmetyki itp.</p><ul><li>Inteligentna regulacja temperatury</li> <li> Specjalnie zaprojektowany dla urody</li> <li> Cicha praca</li> <li> Kompaktowy, ale pojemny</li> <li> Wszechstronny i praktyczny</li></ul>","type":"TEXT"}]},{"items":[{"content":"<p>Specyfikacje</p><p>Numer modelu produktu: CBA-6L-I</p> <p> Czarny kolor</p> <p> Pojemność (L): 6 L / 8 puszek</p> <p> Zakres chłodzenia: 59 ℉/15 ℃</p> <p> Materiał podszewki wewnętrznej: podszewka aluminiowa</p> <p> Zasilanie: prąd stały 9 V; Chłodzenie: 18 W</p> <p> Waga: 4,08 funta / 1,85 kg</p> <p> Hałas: ≤38 dB</p> <p> Rozmiar: 9,56 x 7,63 x 14 cali / 2243 x 194 x 356 mm</p>","type":"TEXT"},{"type":"IMAGE","url":"https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-8.jpg"}]},{"items":[{"type":"IMAGE","url":"https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-9.jpg"},{"content":"<p>W drodze</p><p>Dzięki lusterku do makijażu HD i trzem regulowanym lampkom upiększającym LED możesz dostosować jasność światła do otoczenia podczas nakładania makijażu.</p>","type":"TEXT"}]},{"items":[{"content":"<p>Lustro HD i światło LED</p><p>Dzięki lusterku do makijażu HD i trzem regulowanym lampkom upiększającym LED możesz dostosować jasność światła do otoczenia podczas nakładania makijażu.</p>","type":"TEXT"},{"type":"IMAGE","url":"https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-10.jpg"}]},{"items":[{"type":"IMAGE","url":"https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-11.jpg"},{"content":"<p>Różnorodne możliwości zastosowania</p><p>Ta 6-litrowa kosmetyczna lodówka to doskonały wybór w każdej sytuacji. Dzięki możliwości przechowywania do ośmiu (330 ml) puszek ulubionych napojów idealnie nadaje się do przechowywania różnych produktów spożywczych, owoców, napojów, kosmetyków i leków, aby zapewnić im chłód i ciepło. Niezależnie od tego, czy wybierasz się na kemping, czy po prostu potrzebujesz dodatkowej przestrzeni do przechowywania, ta mała lodówka zapewni Ci wszystko!</p>","type":"TEXT"}]},{"items":[{"content":"<p>Kompaktowy i przenośny</p><p>Mała i lekka (4,08 funta / 1,85 kg), ta lodówka do makijażu jest idealnym towarzyszem wszystkich zajęć na świeżym powietrzu. Dzięki miękkiemu uchwytowi z PU przenoszenie jest dziecinnie proste! Już nigdy nie będziesz musiał się martwić o dźwiganie ciężkich lodówek.</p>","type":"TEXT"},{"type":"IMAGE","url":"https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-12.jpg"}]},{"items":[{"type":"IMAGE","url":"https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-14.jpg"},{"content":"<p>Cicha praca</p><p>Nie pozwól, aby głośna lodówka zakłóciła Twój odpoczynek! Dzięki zaawansowanej technologii redukcji hałasu ta przenośna minilodówka działa na poziomie poniżej 38 dB, co czyni ją idealną opcją do użytku w sypialniach, miejscach pracy i innych miejscach, w których ważna jest cisza.</p>","type":"TEXT"}]},{"items":[{"content":"<p>Inteligentna kontrola temperatury</p><p>Ta chłodniejsza i cieplejsza zamrażarka może automatycznie regulować temperaturę wewnętrzną lodówki i zmniejszać zamrażanie do 59 ℉ poniżej temperatury otoczenia. Po włączeniu ta kompaktowa lodówka osobista potrzebuje tylko dwóch godzin, aby osiągnąć najlepszy efekt chłodzenia!</p>","type":"TEXT"},{"type":"IMAGE","url":"https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-15.jpg"}]},{"items":[{"content":"<p>Zawartość Paczki</p><p>1 * mała lodówka</p> <p> 1 x amerykański zasilacz</p> <p> 1 * kabel USB</p> <p> 1 * ręcznik</p> <p> 1x instrukcja</p>","type":"TEXT"}]},{"items":[{"content":"<p>Funkcje i szczegóły</p><p>Inteligentna regulacja temperatury: Nasza minilodówka umożliwia automatyczną regulację temperatury wewnętrznej lodówki. Tryb chłodzenia może osiągnąć temperaturę otoczenia poniżej 59 ℉/15ºC. Osiągnięcie odpowiedniej wydajności chłodzenia zajmuje tylko dwie godziny i można go używać do przechowywania żywności, napojów, mleka matki, produktów do pielęgnacji skóry, leków do przechowywania.</p> <p> Specjalnie dla urody: Konstrukcja lusterka do makijażu HD i świateł LED pozwala dostosować jasność świateł do otoczenia podczas makijażu (3 regulowane poziomy), aby uzyskać najlepszą jasność dla idealnego makijażu.</p> <p> Cicha praca: dzięki cichej technologii urządzenie pracuje z poziomem hałasu poniżej 38 dB, dzięki czemu jest cichsze i mniej przeszkadza w pracy i codziennym życiu. Nie zakłóca wypoczynku i doskonale wpasowuje się w każde otoczenie – czy to sypialnia, gabinet czy pokój dziecięcy.</p> <p> KOMPAKTOWA, ALE PRZESTRONNA: Nasza minilodówka ma małą obudowę, ale mieści do ośmiu puszek o pojemności 330 ml w 6-litrowym pojemniku i waży zaledwie 4,08 funta / 1,85 kg. Miękki uchwyt PU sprawia, że ​​jest przenośny i łatwy do przenoszenia, idealny do przechowywania żywności, napojów, mleka matki, produktów do pielęgnacji skóry, lekarstw i nie tylko.</p> <p> Wszechstronność i wygoda: osobista lodówka jest dostarczana zarówno z kablem zasilającym USB, jak i domowym zasilaczem, dzięki czemu można jej używać również podczas jazdy samochodem i aktywności na świeżym powietrzu. Elegancki wygląd i wygodne funkcje sprawiają, że jest to również idealny prezent dla krewnych i przyjaciół, którzy lubią wędrówki, pikniki lub kempingi.</p>","type":"TEXT"}]}]},"discounts":{"wholesalePriceList":{"id":"631c8f35-73f0-408b-bc63-1f6d46d33b09"}},"external":{"id":"MNBXHSZJMBB6LMOFZV2"},"id":"15493774650","language":"pl-PL","location":{"city":"Czech Republic","countryCode":"CZ","postCode":"25261","province":"Jenec  West Prague"},"parameters":[{"id":"11323","name":"Condition","values":["New"],"valuesIds":["11323_1"]}],"payments":{"invoice":"VAT"},"productSet":[{"product":{"images":["https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-1.2.jpg","https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-1.21.jpg","https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-8.jpg","https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-9.jpg","https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-10.jpg","https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-11.jpg","https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-12.jpg","https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-14.jpg","https://d3uelg7zvfr5gj.cloudfront.net/product/MNBXHSZJMBB6LMOFZ/mini-fridge-m100-15.jpg"],"name":"Mini Lodówka Jednodrzwiowa 6L Przenośny  Czarna 8 Puszek 3 Tryb Światła Lus"}}],"publication":{"marketplaces":{"additional":[{"id":"allegro-cz"},{"id":"allegro-sk"}],"base":{"id":"allegro-pl"}}},"sellingMode":{"format":"BUY_NOW","price":{"amount":259.99,"currency":"PLN"}},"stock":{"available":1,"unit":"UNIT"},"taxSettings":{"rates":[{"countryCode":"PL","rate":23.00},{"countryCode":"CZ","rate":21.00},{"countryCode":"SK","rate":20.00}]}}

OutPut:
resultCode: 422, resultMsg: Unprocessable Entity failMsg:{"errors":[{"code":"InvalidDictionaryParameter","message":"The dictionary parameter 'Stan' (id: 11323) is defined ambiguously. Provided value and the dictionary value 'Nowy' are different.","details":null,"path":"parameters","userMessage":"Parameter Stan defined ambiguously. The specified value and the specified dictionary value Nowy do not match.","metadata":{}}]}

**Comment by VEVOR** [comment]
Is trace-id the ID returned by successful listing publishing? Please tell me the meaning? Calling the listing interface: Create offer based on product must be successful before the id can be returned, but it was not successful.
The same scenario: calling the Edit an offer interface, the OfferID is: 15493774650, and the same error occurs when submitting. There is no attribute 'Stan' (id: 11323) in the final category ID: 67430, but the following error is reported:
Unprocessable Entity failMsg:{"errors":[{"code":"InvalidDictionaryParameter","message":"The dictionary parameter 'Stan' (id: 11323) is defined ambiguously. Provided value and the dictionary value 'Nowy' are different .","details":null,"path":"parameters","userMessage":"Parameter `Stan` defined ambiguously. The specified value and the specified dictionary value `Nowy` do not match.","metadata": {}}]}

**Comment by Lukasz-Zurek** [comment]
W return a trace-id of your request in the response headers so we can identify this specific case. We should return it for 422 error code. But thanks for the offer.id - I will check it out closely and will let you know.
