### ISSUE TITLE
ASN

### ISSUE THREAD

**Issue by mohan-mandal-pattern** [allegro/allegro-api#8919]
Is there any UI to create ASN?

**Comment by Lukasz-Zurek** [comment]
No, unfortunately not. But you can still test our API functionalities on our test environment (sandbox). But please note that we can run One Fulfillment service only on the test account where no offer has been created so far / not even a draft has been prepared.

**Comment by Lukasz-Zurek** [comment]
@mohan-mandal-pattern I misled you a bit. If your test account is marked as One Fulfillment, then you should have an access to UI on [this site](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/fulfillment/). So you will be able to [add/edit ASN](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/fulfillment/edytuj-awizo) too.
