### ISSUE TITLE
PUT /sale/offers

### ISSUE THREAD

**Issue by Rick420** [allegro/allegro-api#892]
Czy metoda PUT na zasobie /sale/offers działa poprawnie na sandboxie?
Dostaję taką odpowiedź która zbytnio nie mówi w czym jest problem

> {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers/6206010358","userMessage":null}]}

**Comment by MartaNowaczyk** [comment]
@Rick420 jaki dostajesz status?

**Comment by Rick420** [comment]
Status to 0

**Comment by MartaNowaczyk** [comment]
@Rick420 niemożliwe żebyś dostał taki status. Podeślij proszę curle z danymi z requesta, żebym mogła to sprawdzić, bo błąd jest za ogólny.

**Comment by Rick420** [comment]
Błąd był spowodowany przez zły JSON, teraz chciałbym aktywować konto by móc wystawić ofertę do końca lecz nie mogę aktywować. Mógłbym prosić o aktywację?  login : Yatta

**Comment by MartaNowaczyk** [comment]
@Rick420 konto aktywowane. Jeśli wszystko ok zamknij proszę ten wątek.

**Comment by Qenozis** [comment]
> @Rick420 **niemożliwe żebyś dostał taki status**. Podeślij proszę curle z danymi z requesta, żebym mogła to sprawdzić, bo błąd jest za ogólny.

Muszę Panią zmartwić, bo taki status "0" istnieje (przynajmniej na sandboxie) i oznacza:
"couldn't open file"
Nr tego błędu: 26.
