### ISSUE TITLE
Brak odpowiedzi serwera zapytanie PATCH "/sale/product-offers/{offerId}"

### ISSUE THREAD

**Issue by BartlomiejCalus** [allegro/allegro-api#8920]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry, od samego rana mamy problem z zapytaniem PATCH "/sale/product-offers/{offerId}". Za każdym razem jak wysyłamy zapytanie w odpowiedzi otrzymujemy wiadomość: 
"{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Try again in a few minutes."}]}" 

Trace-id odpowiedzi: 28d129e883298c1f

**Comment by Lukasz-Zurek** [comment]
Dziękuję za zgłoszenie. Konsultuję temat z odpowiednim zespołem. Wkrótce wrócę do Ciebie ze szczegółami.

**Comment by Lukasz-Zurek** [comment]
@BartlomiejCalus 

Na wstępie zaznaczę, że błędnie zwracamy tutaj błąd 500, za co przepraszamy. Planujemy to poprawić, aby zwracany był kod błędu zgodny z rzeczywistością. Przepraszamy za te utrudnienia.

Natomiast co do samego żądania - okazuje się, że błędnie przekazujesz dane dotyczące załącznika (przekazujesz pełne, zahashowane dane). W pierwszej kolejności powinieneś utworzyć obiekt załącznika i przesłać plik - [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#zalaczniki) opisaliśmy te procesy. Następnie uzyskany identyfikator załącznika - przekaż w polu **"attachments.id"**.

**Comment by BartlomiejCalus** [comment]
Jasne, rozumiem. Dziękuję za pomoc
