### ISSUE TITLE
Informacja o tym czy oferta posiada warianty sale/product-offers

### ISSUE THREAD

**Issue by Morph21** [allegro/allegro-api#8924]
Czy jest gdzieś przesyłana informacja o tym że oferta posiada warianty podczas pobierania jej danych czy dla każdej oferty należy używać endpointu /sale/offer-variants żeby pobrać wszystkie zestawy wariantów i na tej podstawie sprawdzać jaka oferta posiada warianty?

**Comment by Lukasz-Zurek** [comment]
Niestety nie. W tej sytuacji tak jak wspomniałeś - należy używać wspomnianego endpointu /sale/offer-variants i generalnie zapisywać oferty dodane wcześniej jako wielowariantowe.

**Comment by Morph21** [comment]
Dziękuję za informację

**Comment by Lukasz-Zurek** [comment]
@atomaszewski-bl Nie, warianty produktowe różnią się od tych ofertowych i nie zwracamy tego typu informacji na wskazanym zasobie.

**Comment by atomaszewski-bl** [comment]
@Lukasz-Zurek Dzięki, a czy jest jakiś zasób (lub czy jest planowany taki zasób) z którego taką informację można wyciągnąć (aby połączyć w naszym systemie oferty w warianty, tak jak Allegro je połączyło)?

**Comment by Lukasz-Zurek** [comment]
Niestety nie posiadamy takiego zasobu, jak również nie mamy go w planach. Mogę jednak zachęcić Cię do zaproponowania takiego rozwiązania w dedykowanym miejscu, czyli na [Github Discussions](https://github.com/allegro/allegro-api/discussions), gdzie zbieramy sugestie związane z rozwojem naszego API. Jednocześnie również inni użytkownicy forum mogą oddać swój głos.

**Comment by atomaszewski-bl** [comment]
@Lukasz-Zurek Jeszcze jedno pytanie: czy jest znana data kiedy wszystkie kategorie będą oparte na wariantach produktowych, a nie ofertowych? Rozumiem, że będzie się to wiązać również z wyłączeniem zasobu `/sale/offer-variants` ponieważ nie będzie on już skuteczny.

**Comment by Lukasz-Zurek** [comment]
@atomaszewski-bl Nie. Jeśli jednak cokolwiek zmieni się w tym temacie, z całą pewnością zapowiemy te zmiany odpowiednio wcześniej w [naszych aktualnościach](https://developer.allegro.pl/news), które możesz również [zasubskrybować](https://developer.allegro.pl/newsletter).
