### ISSUE TITLE
use of refresh_token and redirect_uri

### ISSUE THREAD

**Issue by ranfyy** [allegro/allegro-api#8925]
I am following the Device flow:
	https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow

In the end I get an access_token and a refresh_token.
The access_token is valid for 12 hours.

But after that I am supposed to use the refresh_token.

Therefor I want to use Extending token validity:
	https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#extending-token-validity

Here I shall provide a redirect_uri which I don't have.

Where do I get a redirect_uri?

Regards

**Comment by PrzemyslawLukanowski** [comment]
When it comes to a device flow type of authorization, you don't need to provide redirect_uri when requesting a refresh token.

**Comment by ranfyy** [comment]
Ahh OK, thanks
