### ISSUE TITLE
Wystawienie oferty typu przedsprzedaż

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#8926]
Dzień Dobry, prosił bym o wskazanie miejsca w dokumentacji które wskazuje jak można wystawić ofertę typu "przedsprzedaż". Prosił bym o wskazanie konkretnego pola gdyż wstępnie nie mogłem zlokalizować odpowiedzi na to pytanie przeglądając dokumentacje ofert.

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, musisz uzupełnić odpowiednio pola:

- `delivery.handlingTime`,
- `delivery.shipmentDate`.

Oraz zaznaczyć taką informację w opisie oferty.
