### ISSUE TITLE
/order/events/ Problem z zarządzaniem zamówieniami. 

### ISSUE THREAD

**Issue by Matus4709** [allegro/allegro-api#8928]
Udało się uzyskać token przekazać go, ale aplikacja zwraca błąd:

`{'errors': [{'code': 'EMPTY_USER_ID', 'message': 'User name from JWT cannot be empty', 'details': None, 'path': '/order/events', 'userMessage': 'User name from JWT cannot be empty', 'metadata': {}}]}`

Pobranie głównych kategorii przeszło bez problemu. 
Mój kod: 

CLIENT_ID = settings.ALLEGRO_CLIENT_ID
CLIENT_SECRET = settings.ALLEGRO_CLIENT_SECRET
TOKEN_URL = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token"

def get_access_token(request):
    try:
        data = {'grant_type': 'client_credentials'}
        access_token_response = requests.post(TOKEN_URL, data=data, verify=True,
                                             allow_redirects=False, auth=(CLIENT_ID, CLIENT_SECRET))
        access_token_response.raise_for_status()
        tokens = json.loads(access_token_response.text)
        access_token = tokens['access_token']

        # Zapisanie tokena dostępu w sesji
        request.session['access_token'] = access_token
        return access_token
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)
def offers(request):
    url = 'https://api.allegro.pl.allegrosandbox.pl/order/events'
    headers = {
        'Authorization': f'Bearer {get_access_token(request)}',
        'Accept': 'application/vnd.allegro.public.v1+json',
    }
    response = requests.get(url,headers=headers).json()
    print(response)
    return render(request, 'index.html',{'events':response})

**Comment by PrzemyslawLukanowski** [comment]
Komunikat wskazuje, że Twój token nie posiada kontekstu użytkownika, co oznacza, że wygenerowałeś go w ramach autoryzacji [client_credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow). Autoryzacja tego rodzaju daje Ci dostęp wyłącznie do tych zasobów, które w naszej dokumentacji oznaczyliśmy jako "bearer-token-for-application.". Aby posiadać dostęp do zamówień, musisz posiadać kontekst użytkownika, wygeneruj proszę token w drodze autoryzacji [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow).

**Comment by PrzemyslawLukanowski** [comment]
Wygląda na to, że token wygenerowany w ramach środowiska testowego próbujesz użyć na produkcji (https://api.allegro.pl/offers/listing) lub nie przekazujesz tokena w ogóle. Dodam, że na produkcji dostęp do zasobu /offers/listing jest ograniczony, tylko dla aplikacji zweryfikowanych. Jeśli problem na Sandboxie nadal będzie występować, prześlij proszę przykładowe trace-id.

**Comment by Matus4709** [comment]
Rzeczywiście pojawia się tam błąd że nie używam środowiska testowego, aczkolwiek po zmianie `https://api.allegro.pl.allegrosandbox.pl/offers/listing` problem nadal występuje 

`<oauth>
<error_description>Full authentication is required to access this resource</error_description>
<error>unauthorized</error>
</oauth>`

**Comment by PrzemyslawLukanowski** [comment]
Ten błąd wskazuje na to, że token nie jest dołączony do requestu. Czy możesz podać przykładowe trace-id?
