### ISSUE TITLE
Błąd "DELIVERY_METHOD_NOT_ALLOWED"

### ISSUE THREAD

**Issue by adibuu** [allegro/allegro-api#8929]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Chce utworzyć nowy cennik dostaw, wysyłam żądanie POST na endpoint: "/sale/shipping-rates" 
body:

`{
  name: "eZlVUVCu7T",
  rates: [
    {
      deliveryMethod: { id: "2488f7b7-5d1c-4d65-b85c-4cbcf253fd93" },
      maxQuantityPerPackage: 1,
      firstItemRate: { amount: 10.95, currency: "PLN" },
      nextItemRate: { amount: "0.00", currency: "PLN" },
    },
    {
      deliveryMethod: { id: "685d8b40-2571-4111-8937-9220b1710d4c" },
      maxQuantityPerPackage: 1,
      firstItemRate: { amount: 16.99, currency: "PLN" },
      nextItemRate: { amount: "0.00", currency: "PLN" },
    },
    {
      deliveryMethod: { id: "b20ef9e1-faa2-4f25-9032-adbea23e5cb9" },
      maxQuantityPerPackage: 1,
      firstItemRate: { amount: 15.39, currency: "PLN" },
      nextItemRate: { amount: "0.00", currency: "PLN" },
    },
    {
      deliveryMethod: { id: "2653ca13-67c8-48c3-bbf8-ff9aa3f70ed3" },
      maxQuantityPerPackage: 1,
      firstItemRate: { amount: 21.99, currency: "PLN" },
      nextItemRate: { amount: "0.00", currency: "PLN" },
    },
    {
      deliveryMethod: { id: "07c12933-584e-453d-bee5-60f3f32dfc73" },
      maxQuantityPerPackage: 1,
      firstItemRate: { amount: 11.9, currency: "PLN" },
      nextItemRate: { amount: "0.00", currency: "PLN" },
    },
    {
      deliveryMethod: { id: "0c330aea-900f-4830-9de8-72fadd2a3916" },
      maxQuantityPerPackage: 1,
      firstItemRate: { amount: 11.99, currency: "PLN" },
      nextItemRate: { amount: "0.00", currency: "PLN" },
    },
  ],
};`

w odpowiedzi otrzymuję błędy:

`{
  errors: [
    {
      code: "DELIVERY_METHOD_NOT_ALLOWED",
      message: "Delivery method is not allowed for user",
      details: null,
      path: "rates[4].deliveryMethod.id",
      userMessage: "Wskazana metoda dostawy nie jest dostępna dla użytkownika.",
    },
    {
      code: "DELIVERY_METHOD_NOT_ALLOWED",
      message: "Delivery method is not allowed for user",
      details: null,
      path: "rates[5].deliveryMethod.id",
      userMessage: "Wskazana metoda dostawy nie jest dostępna dla użytkownika.",
    },
  ],
}`

Dlaczego niektóre metody dostaw nie są dostępne dla mojego konta? Tworząc cennik dostaw bezpośrednio w panelu allegro żaden taki błąd nie występuje. Także testując tą samą funkcjonalność mojej aplikacji w środowisku sandboxowym, wszystko działa poprawnie.

trace-id: 6577a49b67af1f34

**Comment by Lukasz-Zurek** [comment]
@adibuu Konsultuję Twój problem z odpowiednim zespołem. Jak tylko uzyskam więcej informacji - wrócę do Ciebie ze szczegółami.

**Comment by Lukasz-Zurek** [comment]
@adibuu Próbujesz (na koncie zwykłym) dodać metody:

- Allegro Odbiór w Punkcie DHL; 07c12933-584e-453d-bee5-60f3f32dfc73,
- Allegro Automat DHL POP BOX; 0c330aea-900f-4830-9de8-72fadd2a3916,

a w tym przypadku wymagane jest posiadanie konta firmowego.

**Comment by adibuu** [comment]
> @adibuu Próbujesz (na koncie zwykłym) dodać metody:
> 
> * Allegro Odbiór w Punkcie DHL; 07c12933-584e-453d-bee5-60f3f32dfc73,
> * Allegro Automat DHL POP BOX; 0c330aea-900f-4830-9de8-72fadd2a3916,
> 
> a w tym przypadku wymagane jest posiadanie konta firmowego.

Dzięki za pomoc. Proponuję rozbudować "userMessage" w zwracanym błędzie o tą informację. Na pewno ułatwi to znalezienie błędu w przyszłości innym użytkownikom :)

**Comment by Lukasz-Zurek** [comment]
> > @adibuu Próbujesz (na koncie zwykłym) dodać metody:
> > 
> > * Allegro Odbiór w Punkcie DHL; 07c12933-584e-453d-bee5-60f3f32dfc73,
> > * Allegro Automat DHL POP BOX; 0c330aea-900f-4830-9de8-72fadd2a3916,
> > 
> > a w tym przypadku wymagane jest posiadanie konta firmowego.
> 
> Dzięki za pomoc. Proponuję rozbudować "userMessage" w zwracanym błędzie o tą informację. Na pewno ułatwi to znalezienie błędu w przyszłości innym użytkownikom :).

Dzięki za sugestię. Fakt - przy kilku dodawanych metodach dostawy dobrze byłoby wskazać te problematyczne. Zwrócę na to uwagę zespołowi odpowiedzialnemu za całą funkcjonalność.
> 
> Czy znajdę gdzieś listę metod dostaw które są dostępne dla zwykłego konta oraz dla kont firmowych?

Niestety nie mamy tego spisanego w naszym serwisie https://developer.allegro.pl.

**Comment by adibuu** [comment]
> > > @adibuu Próbujesz (na koncie zwykłym) dodać metody:
> > > 
> > > * Allegro Odbiór w Punkcie DHL; 07c12933-584e-453d-bee5-60f3f32dfc73,
> > > * Allegro Automat DHL POP BOX; 0c330aea-900f-4830-9de8-72fadd2a3916,
> > > 
> > > a w tym przypadku wymagane jest posiadanie konta firmowego.
> > 
> > 
> > Dzięki za pomoc. Proponuję rozbudować "userMessage" w zwracanym błędzie o tą informację. Na pewno ułatwi to znalezienie błędu w przyszłości innym użytkownikom :).
> 
> Dzięki za sugestię. Fakt - przy kilku dodawanych metodach dostawy dobrze byłoby wskazać te problematyczne. Zwrócę na to uwagę zespołowi odpowiedzialnemu za całą funkcjonalność.
> 
> > Czy znajdę gdzieś listę metod dostaw które są dostępne dla zwykłego konta oraz dla kont firmowych?
> 
> Niestety nie mamy tego spisanego w naszym serwisie https://developer.allegro.pl.

Dzięki za odpowiedź. Odnośnie tego czy metoda dostawy jest dostępna dla zwykłego czy firmowego konta to fajnie byłoby mieć tą informację w zwracanych danych z tego endpointu: /sale/delivery-methods. Kolejna mała sugestia odnośnie rozbudowy API😄.
