### ISSUE TITLE
Autoryzacja wybranego konta

### ISSUE THREAD

**Issue by maniootek** [allegro/allegro-api#8930]
Czy da się podczas autoryzacji konta wywołać monit o wpisanie samego hasła dla wybranego loginu? Coś w rodzaju logowania google już z wybranym loginem. Chciałbym uniknąć sytuacji, gdy chcę zautoryzować konto X a użytkownik podaje dane logowania dla konta Y

**Comment by Lukasz-Zurek** [comment]
W naszych procesach autoryzacji nie ma niestety takiej możliwości.

**Comment by Lukasz-Zurek** [comment]
@maniootek Dzięki za sugestię. Tego typu pomysły zbieramy i monitorujemy na [Github Discussions](https://github.com/allegro/allegro-api/discussions). Zachęcam Cię mimo wszystko do opisania jej w kontekście naszej [autoryzacji w API](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#wstep).
