### ISSUE TITLE
Settlements with Allegro

### ISSUE THREAD

**Issue by JunchengJi** [allegro/allegro-api#8931]
![Snipaste_2024-04-22_22-45-39](https://github.com/allegro/allegro-api/assets/77001822/6c9675a6-483a-4916-a9ec-1110a4b25c3d)

Rejected payment
Failed to register your payment. Please try again.

I have tried multiple times, but failed.

my account :  etradeSandbox

**Comment by Lukasz-Zurek** [comment]
Please try to use quick payments and different bank. If the problem still occurs, please let me know.

**Comment by JunchengJi** [comment]
have already been solved.
