### ISSUE TITLE
Pole punkt odbiorcy ze wskazanym id nie zostało znalezione

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#8932]
Dzień Dobry, otrzymujemy błąd podany w tytule, pomimo przekazania punktu 1 do 1 z zamówienia. Prośba o wskazanie przyczyny. trace-id: 35e439e5a273d162

**Comment by Lukasz-Zurek** [comment]
Z dostępnych mi danych wynika, że wskazany punkt A006760 jest obecnie niedostępny, dlatego zwróciliśmy błąd.
