### ISSUE TITLE
Prośba o aktywację konta sandboxowego / pytanie o uwierzytelnianie

### ISSUE THREAD

**Issue by El-Karollo** [allegro/allegro-api#8933]
Witam serdecznie
Prosiłbym o aktywacje możliwości wystawiania produktów na sprzedaż oraz przeglądania ofert w koncie sandbox.
Client:106980365
allegro@modelmania.com.pl

No, chyba że coś robię źle. Używam Client_credentials flow i pobrać kategorię mogę. No i właściwie tu się kończą moje możliwości. Chcę zrobić synchronizację z naszym obecnym sklepem online oraz allegro. Powinienem był użyć DCR?
Jeśli tak, to prosiłbym o nadanie Software statement ID aplikacji modelmania_sandbox.

Z góry dziękuję za pomoc :)

**Comment by Lukasz-Zurek** [comment]
Z tego co widzę Twoje konto posiada status zwykłego, a to zdecydowanie utrudni zarządzanie ofertami czy wystawianie. Sugeruję przekształcenie konta na firmowe. Zrobisz to [tutaj](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

Natomiast jeśli chodzi o autoryzację, wspomniany client_credentials flow nie posiada kontekstu użytkownika. Dlatego uzyskasz dostęp tylko do ogólnodostępnych zasobów, np. lista kategorii i parametrów. W[ naszej dokumentacji](https://developer.allegro.pl/documentation/) znajdziesz odpowiednie oznaczenie, jaki typ autoryzacji wymagany jest dla danego zasobu:

- bearer-token-for-user ([code](https://developer.allegro.pl/auth/#app) lub[ device](https://developer.allegro.pl/auth/#DeviceFlow) flow),
- bearer-token-for-application ([client credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow)).

W tej sytuacji sugeruję skorzystać z [authorization code flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow), lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow). DCR nie będzie Tobie potrzebny.

**Comment by El-Karollo** [comment]
Ok. Wybrałem Device flow. No i napisałem już autoryzacje, zaprogramowałem wszystkie daty aby token nie był co chwila wydawany na nowo. Po upływie 12h mam zrobić refresh token. No i tu się pojawiają problemy, bowiem tego trochę nie rozumiem. Mam zapisany refresh-token, który dostałem wcześniej. Trochę nie rozumiem jakie mam wysłać zapytanie do API aby otrzymać nową parę... W tutorialu jest konieczność kolejnego klikania na przejście stronę allegro. Czy jest możliwość zrobienia tego bez ingerencji administratora?

**Comment by Lukasz-Zurek** [comment]
Niestety nie, tzn. proces przedłużania ważności tokena zrealizować można tylko sposobem opisanym w [poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena).

Co do konta na sandboxie - przed momentem je aktywowałem.

**Comment by El-Karollo** [comment]
Trochę nie rozumiem. Jest to napisane dość zawile. Prosiłbym o lekką poprawkę jeśli jestem w błędzie. Na początku Device Flow otrzymuje klasyczny token oraz refresh_token. Token jest ważny 12godzin i to na nim mogę robić wszystkie operacje - wystawiać oferty, edytować je, itp. Po upływie 12godzin muszę go odświeżyć. Aby odświeżyć token potrzebuję ingerencji użytkownika. Po odświeżeniu tokenu ten znowu jest ważny 12godzin - i to na nim operuję aukcjami. Zgadza się?

Czyli, aby była pełna automatyzacja nadal będę potrzebować akcji użytkownika raz na 12godzin? Przyjmując, że ktoś jest w sklepie rano i to odklika - to nie ma problemu. Później jest trudniej, gdy nikogo w sklepie nie ma. Będzie problem aby zsynchronizować stany magazynowe z stanami na allegro... Czy ja coś źle zrozumiałem?

**Comment by Lukasz-Zurek** [comment]
Przepraszam, faktycznie moja odpowiedź była chaotyczna. Generalnie refresh token pozwala na uzyskanie nowej pary tokenów - access_token i refresh_token dla danego użytkownika **bez konieczności ingerencji z jego strony**. 

Ingerencja użytkownika potrzebna jest tylko na początku procesu [autoryzacji](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow-autoryzacja-uzytkownika) 

- **punkt 3, 4a, 5** w tutorialu - _Poproś użytkownika, aby przeszedł z poziomu dowolnego urządzenia na podany przez ciebie adres (verification_uri) i podał tam kod użytkownika (user_code)_,
- następnie odpytując POST https://allegro.pl/auth/oauth/token?grant_type=urn:ietf:params:oauth:grant-type:device_code&device_code={device_code} (punkt 4b [poradnika](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow-autoryzacja-uzytkownika) uzyskujesz parę tokenów. 

Później natomiast odświeżanie tokena możesz samodzielnie zautomatyzować.

**Comment by El-Karollo** [comment]
No właśnie. Stąd moje pytania. Nie widzę możliwości na automatyzację (bez udziału użytkownika) refresh tokena. Według poradnika, patrząc na kod przykładowy PHP, konieczna jest ingerencja użytkownika. Trzeba podać redirect_uri mimo, że w aplikacji wybrałem wersje "nie przeglądarkową" (bez podawania url-i). Trochę nie wiem, jak odpytać API aby otrzymać nową parę tokenów z automatu. Z punktami 3, 4a, 4b mam oprogramowany. Dostaję token działający na 12h i wszystko działa jak należy.

**Comment by Lukasz-Zurek** [comment]
Przykład w poradniku faktycznie zawiera redirect-uri, nie jest on jednak wymagany.

**Comment by Lukasz-Zurek** [comment]
@El-Karollo Poprawiłem przykładowy request w poradniku.

**Comment by Lukasz-Zurek** [comment]
@El-Karollo Zalecane jest, aby odświeżać token co 12 godzin, bo będzie to bardziej efektywne (odświeżanie tokena 2x na dobę). Oczywiście API pozwoli na taką akcję przed upływem 12 godzin.
