### ISSUE TITLE
Centrum wiadomości

### ISSUE THREAD

**Issue by many-to-one** [allegro/allegro-api#8936]
Witam, czy centrum wiadomości przez api działa asynchronicznie(websocket), czy trzeba odświeżać stronę żeby zobaczyć nową wiadomość w czacie?

**Comment by Lukasz-Zurek** [comment]
Nie działa to asynchronicznie i trzeba odświeżać stronę tj. pobierać informacje np. o nowych wiadomościach dla wskazanego wątku, etc.
