### ISSUE TITLE
Brak możliwości wytestowanisa kuriera Allegro One Box, DPD

### ISSUE THREAD

**Issue by relains** [allegro/allegro-api#8938]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dlaczego na sandbox nie można wybrać kuriera "Allegro One Box, DPD" ?? Musiałem "na pałę" wrzucić zmiany na produkcji licząc, że wszystko zadziała jak należy, ponieważ na sandbox pomimo tego, że w ustawieniach dostawy są takie same teksty jak na produkcji, że Allegro One Box i Punkt będzie woził UPS i DPD to już od strony klienta sandbox nie można DPD wybrać, tylko UPS się pokazuje.

**Comment by PrzemyslawLukanowski** [comment]
Jeśli chodzi o formularz dostawy, to nie pokazujemy tutaj informacji o konkretnym kurierze, który dowozi przesyłkę:

<img width="228" alt="Zrzut ekranu 2024-04-23 o 12 27 40" src="https://github.com/allegro/allegro-api/assets/51473661/af3ff66e-21af-4d8e-87ad-7cf7e9051159">

Kurier, który zrealizuje dowóz wybierany jest z automatu. Samą metodę zwracamy "Allegro One Box, DPD" na Sandboxie i da się dołączyć ją do cennika.

Jeśli źle zrozumiałem Twoje pytanie lub masz na myśli inne miejsce, daj proszę znać.
