### ISSUE TITLE
Error:  Imię i nazwisko jest wymagane.

### ISSUE THREAD

**Issue by KaMisza** [allegro/allegro-api#8939]
- [x ] z zasobem REST API / with a REST API resource
 
Podczas próby nadania przesyłki o trace-id c370951e1e124ae za pomocą metody [Wysyłam z Allegro Kurier DPD (Allegro pl)] otrzymujemy komunikat Error:  Imię i nazwisko jest wymagane. W jsonie przesyłki przekazujemy imię oraz nazwisko w polu "name".

**Comment by PrzemyslawLukanowski** [comment]
W polu `path` oraz `message` informujemy, że komunikat dotyczy pola `pickup.name`. W Twoim przypadku przekazujesz tam jeden wyraz - to musi być imię i nazwisko.
