### ISSUE TITLE
WZA Metody dostaw One Punkt, One Box i pole carrierId

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#8941]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Mam pytanie na temat endpointu https://api.allegro.pl/parcel-management/delivery-services i pola carrierId w zwróconych danych z tego endpointu. 
Dlaczego np. dla metody poniżej w tym polu czy innym nie przekazanych informacji jaki kurier faktycznie obsługuje daną przesyłkę? W tej chwili dochodzą nowe metody dostaw obsługiwane przez różnych kurierów i mamy Allegro One Punkt obsługiwane przez DPD albo przez UPS i na podstawie danych z api nie można w żaden sposób tego rozróżnić oprócz sprawdzania po nazwie co jest dosyć słabym rozwiazaniem. Czy pole carrierId w takich metodach dostaw nie powinno być ustawione odpowiednio UPS, DPD skoro to właśnie ten przewoźnik obsługuje tą przesyłkę? 
		{
			"id": "08c15d0b-9b24-4b3f-89a8-7a2b502abe55",
			"service": "ALLEGRO",
			"name": "Allegro One Punkt, UPS",
			"owner": "ALLEGRO",
			"carrierId": "ALLEGRO",
			"additionalServices": {
				"cashOnDelivery": {
					"available": false,
					"expressAvailable": false
				},
				"options": []
			}
		},
		{
			"id": "09ef5a54-c34d-41ef-908e-9b45ffbfa2e8",
			"service": "ALLEGRO",
			"name": "Allegro One Punkt, DPD",
			"owner": "ALLEGRO",
			"carrierId": "ALLEGRO",
			"additionalServices": {
				"cashOnDelivery": {
					"available": false,
					"expressAvailable": false
				},
				"options": []
			}
		}

**Comment by PrzemyslawLukanowski** [comment]
Ten przewoźnik w przypadku metod Allegro One jest podwykonawcą, głównym przewoźnikiem pozostaje Allegro. W danych zamówienia zwracamy id metody dostawy, na tej podstawie możecie dopasować usługę dostawy Wysyłam z Allegro, na której należy nadać przesyłkę.

Jeśli zależy Ci na dodaniu dodatkowych informacji w tym zasobie, zachęcam do zgłoszenia sugestii w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions).
