### ISSUE TITLE
Opisy aukcji

### ISSUE THREAD

**Issue by WGRINGO** [allegro/allegro-api#8946]
Czy jest jakaś metoda w API, która pozwala wysłać opis aukcji i otrzymać z powrotem jego poprawioną przez Allegro wersję?
Co jakiś czas zdarza się, że mój walidator nie radzi sobie z html wrzuconym przez klienta i trzeba dorabiać dodatkowe przypadki.
A wystawiając opis przez Wasz panel www macie to jakoś ogarnięte. Czy nie dałoby się wystawić odpowiedniej metody w API by raz na zawsze mieć z tym spokój?

**Comment by Lukasz-Zurek** [comment]
Nie udostępniamy tego typu zasobu. Natomiast akceptowane przez nas znaczniki HTML oraz strukturę opisu opisaliśmy [w naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty). 

Wszelkiego rodzaju sugestie/propozycje dotyczące nowych zasobów/funkcjonalności w API możesz nam przekazywać w dedykowanej do tego części, na [Github Discussions](https://github.com/allegro/allegro-api/discussions).
