### ISSUE TITLE
Prosze o aktywację konta inekom w allegrosandbox. 

### ISSUE THREAD

**Issue by inekom** [allegro/allegro-api#8947]
Dzień dobry,

Proces weryfikacji konta inekom utknął na koncie bankowym. I weryfikacji danych firmy w allegrosandbox.

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
@inekom Aktywowałem wskazane konto.

**Comment by Lukasz-Zurek** [comment]
Na sandboxie nie musisz ustawiać dwustopniowego logowania, by zarejestrować aplikację. Jeśli jednak to robisz - nasz system nie wysyła smsów na środowisku testowym. Wprowadź ciąg cyfr: 123456.
