### ISSUE TITLE
Allegro one service_id a name

### ISSUE THREAD

**Issue by bozenadula** [allegro/allegro-api#8948]
Dzień dobry,

Tytułem wstępu nadmienię, że generalnie do integracji zamówień używamy baselinkera ale już jeżeli chodzi o przesyłki integrujemy się bezpośrednio z allegro.
Przyjrzałam się danym na liście pobranych serwisów i dla  różnych numerów id powtarzają się nazwy. Czasami mają one różne id przewoźnika, ale czasami rekordy różnią się tylko service_id. 
Nasz problem polega na tym, że w danych z baselinkera dostajemy nazwę sposobu dostawy, którą mapujemy na service_id i awizujemy przesyłkę allegro. Czy macie Państwo jakieś wskazówki, żeby otrzymaną nazwę mapować z odpowiednim id.

Przykłady:
![image](https://github.com/allegro/allegro-api/assets/103446565/185d0ecf-6508-4301-938b-80a5bc86f0d5)

**Comment by Lukasz-Zurek** [comment]
W skrócie - metody dostawy są rozróżniane wg. pola **"marketplaces"** (informacje te uzyskasz oczywiście za pomocą GET /shipment-management/delivery-services),

np. **Allegro Odbiór w Punkcie DPD Pickup Czechy** występuje dwukrotnie z wartością **allegro-pl** (0eacfb24-ffa3-45c1-9908-093c1d6b03ea) i **allegro-cz** (06ead16c-ee49-4486-aff1-093c1d6b03ea).

Dodatkowo metody rozróżniane są wg. **"carrierId"**:

- DPD_CZ to metoda eksportowa z Czech do Słowacji, realizowana przez DPD Czechy, dostępna w serwisie **allegro-sk**,
- DPD - to metoda exportowa z Polski do Słowacji, realizowana przez DPD Polska, dostępna na **allegro-sk**,

np. **Allegro Kurier DPD** (c3066682-97a3-42fe-9eb5-3beeccab840c - DPD, 0ace25bc-e52d-442b-8464-9442cdd03cd3 - DPD_CZ).
