### ISSUE TITLE
Dodawanie ofert za pomocą REST API Allegro

### ISSUE THREAD

**Issue by poczta111** [allegro/allegro-api#895]
Witam

Tworzę wersję roboczą (tak zwany draft) za pomocą Allegro REST API (https://api.allegro.pl/sale/offers) Wersja robocza zostaje utworzona - nie ma żadnych błędów.

Czy mogę ją edytować korzystając ze strony allegro.pl ? Chciałbym przejrzeć tą wersję roboczą a następnie ręcznie wystawić. Czy jest taka możliwość?

**Comment by MartaNowaczyk** [comment]
@poczta111 Witam, na ten moment drafty utworzone przez REST API nie są widoczne na froncie. Jesteśmy w trakcie ustaleń w tym temacie.

**Comment by poczta111** [comment]
Witam

Ok. Mam jeszcze jedno pytanie. Dlaczego nie mogę wystawić draftu który
dodał się bez błędu. I skąd mam wziąć UUID (universally unique identifier)?
Walczę z tym od rana i cały czas otrzymuję komunikat o błędzie z którego
nic nie wynika.

    public function opublikujAukcjeNaAllegro()
    {

        $header = array();
        $header[] = "authorization: Bearer " . allegro::getAuthToken();
        $header[] = "accept: application/vnd.allegro.public.v1+json";
//"image/png", albo "image/gif"
        $header[] = "content-type: application/vnd.allegro.public.v1+json";
// albo en-EN


$data='{"publication":{"action":"ACTIVATE","scheduledFor":""},"offerCriteria":[{"offers":[{"id":"7672673441"}]
,"type":"CONTAINS_OFFERS"}]}';

        $resp = allegro::jsonCall("
https://api.allegro.pl/sale/offer-publication-commands/b1441984-28f4-4cea-9a9d-4b44ebc9aacd",
$data, $header);

        echo "<pre>";
        print_r($resp);
        echo "</pre>";

    }

Kod błędu:

stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => NotAllowedException
                    [message] => An error has occurred
                    [details] =>
                    [path] =>
                    [userMessage] => An error occurred
                )

        )

)


czw., 15 lis 2018 o 07:20 MartaNowaczyk <notifications@github.com>
napisał(a):

**Comment by poczta111** [comment]
Witam

Udało mi się rozwiązać problem. Okazało się że źle wysyłałem dane. Brakowało metody PUT. 
Pojawił się jednak kolejny problem. Po wystawieniu aukcji otrzymuję komunikat zwrotny z którego nic nie wynika. Oczywiście produkty są wystawione. Zostały prawidłowo wystawione na allegro. 

stdClass Object
(
    [id] => 4a42f603-8277-fb08-ef13-13e6d69051da
    [taskCount] => stdClass Object
        (
            [total] => 0
            [success] => 0
            [failed] => 0
        )

)

**Comment by TomekKaczmarek** [comment]
@poczta111 jeśli odpytasz ten zasób zaraz po zleceniu wystawienia, dostaniesz zera dla wszystkich typów tasków. O status wystawienia warto pytać z pewnym opóźnieniem, by zadania zdążyły się przetworzyć i dopiero na tej podstawie otrzymasz informacje czy i jak wszystkie taski udało się przetworzyć.

Więcej szczegółów na ten temat: https://developer.allegro.pl/sale/#step-9-tasks
