### ISSUE TITLE
WYsyłam z allegro metoda dostawy: Allegro Odbiór w Punkcie DPD Pickup

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#8953]
Witam,
dla metody dostawy Allegro Odbiór w Punkcie DPD Pickup, przesyłka z Polski do Czech, dostaję taki komunikat:
`Niewspierany kraj nadania`

Komunikat ten mam w REST API, ale też w formularzu: Formularz Wysyłam z Allegro na stronie allegro.pl

**Comment by Lukasz-Zurek** [comment]
Zwróć proszę uwagę na to, jaki serwis przypisany ma usługa dostawy, z której korzystasz. Wspomnianą metodę dostawy zwracamy jako dwa odrębne identyfikatory:

- 06ead16c-ee49-4486-aff1-093c1d6b03ea, gdzie:
```
            "marketplaces": [
                "allegro-cz"
            ],
```
- 0eacfb24-ffa3-45c1-9908-093c1d6b03ea:
```
            "marketplaces": [
                "allegro-pl"
            ],
```

**Comment by manoos** [comment]
Nie rozumiem odpowiedzi. W formularzu na stronie allegro to nie ja wybieram metodę dostawy.
Tak samo ustawienie cennika, wchodzę w panelu allegro wysyłka z Polski do Czech.

**Comment by manoos** [comment]
Ok już widzę.
