### ISSUE TITLE
Długi czas aktywacji oferty na środowisku sandbox

### ISSUE THREAD

**Issue by lubodzia** [allegro/allegro-api#8954]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Ostatnio zauważyliśmy wydłużony czas aktywacji oferty środowisku sandbox. Po dodaniu oferty trzeba czekać około godzinę żeby stała się aktywna. Wcześniej takie problemy nie występowały. Z czego wynikają te problemy? Czy da się je jakoś ominąć? Może mamy zbyt aktywnych ofert na koncie sandbox? Proszę o jakąś podpowiedź co może być nie tak. Konto sprzedawcy businessABS.

<!-- [Zapoznaj się z zasadami korzystania z forum API Allegro na GitHubie](https://github.com/allegro/allegro-api/wiki#zasady-korzystania-z-forum-api-allegro-na-githubie)

URL: https://api.allegro.pl.allegrosandbox.pl/sale/product-offers
Request:
{
    "productSet": [
        {
            "product": {
                "name": "Spr\u0119\u017Cyna, klocek hamulcowy",
                "images": [
                    "https://source.unsplash.com/user/c_v_r/1900\u00D7800"
                ],
                "parameters": [
                    {
                        "id": "224017",
                        "values": [
                            "2024_04_25_77"
                        ]
                    },
                    {
                        "id": "248135",
                        "values": [
                            "Carmedia"
                        ]
                    }
                ],
                "category": {
                    "id": "313513"
                }
            }
        }
    ],
    "parameters": [
        {
            "id": "11323",
            "values": [
                "Nowy"
            ]
        }
    ],
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "200.00",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 10
    },
    "messageToSellerSettings": {
        "mode": "OPTIONAL",
        "hint": null
    },
    "b2b": {
        "buyableOnlyByBusiness": false
    },
    "external": {
        "id": "af1a8fff-68d9-4683-950a-52bac45b1b68_256"
    },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "\u003Ch2\u003EBRAK OPISU AUKCJI\u003C/h2\u003E",
                        "url": null
                    }
                ]
            }
        ]
    }
}
Response:
{
    "name": "Sprężyna, klocek hamulcowy",
    "productSet": [
        {
            "product": {
                "id": "723fbbc9-178f-4fc4-810a-229471eb8a10",
                "publication": {
                    "status": "PROPOSED"
                },
                "parameters": [
                    {
                        "id": "248135",
                        "name": null,
                        "values": [
                            "Carmedia"
                        ],
                        "valuesIds": [
                            "248111_856102"
                        ],
                        "rangeValue": null
                    },
                    {
                        "id": "224017",
                        "name": null,
                        "values": [
                            "2024_04_25_77"
                        ],
                        "valuesIds": null,
                        "rangeValue": null
                    }
                ]
            },
            "quantity": {
                "value": 1
            },
            "responsiblePerson": null
        }
    ],
    "parameters": [
        {
            "id": "11323",
            "name": "Stan",
            "values": [
                "Nowy"
            ],
            "valuesIds": [
                "11323_1"
            ],
            "rangeValue": null
        }
    ],
    "images": [
        "https://a.allegroimg.allegrosandbox.pl/original/11ec19/862495c540f6a376844902a7a26d"
    ],
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "b84e26b9-a3b0-4f83-9301-e35b4ae1304d"
        },
        "returnPolicy": {
            "id": "d5d03cf4-5f29-480e-b653-782224161934"
        },
        "warranty": null
    },
    "payments": {
        "invoice": "VAT"
    },
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "200.00",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null
    },
    "stock": {
        "available": 10,
        "unit": "UNIT"
    },
    "location": {
        "countryCode": "PL",
        "province": "MAZOWIECKIE",
        "city": "Warszawa",
        "postCode": "02-972"
    },
    "delivery": {
        "shippingRates": {
            "id": "6ddafe04-d234-4cd5-9954-27184d729b63"
        },
        "handlingTime": "PT24H",
        "additionalInfo": null,
        "shipmentDate": null
    },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h2>BRAK OPISU AUKCJI</h2>"
                    }
                ]
            }
        ]
    },
    "external": {
        "id": "af1a8fff-68d9-4683-950a-52bac45b1b68_256"
    },
    "category": {
        "id": "313513"
    },
    "tax": null,
    "taxSettings": null,
    "sizeTable": null,
    "discounts": {
        "wholesalePriceList": null
    },
    "contact": null,
    "fundraisingCampaign": null,
    "messageToSellerSettings": {
        "mode": "OPTIONAL"
    },
    "attachments": [],
    "b2b": {
        "buyableOnlyByBusiness": false
    },
    "additionalServices": null,
    "compatibilityList": null,
    "additionalMarketplaces": {
        "allegro-cz": {
            "sellingMode": null,
            "publication": {
                "state": "NOT_REQUESTED",
                "refusalReasons": []
            }
        },
        "allegro-sk": {
            "sellingMode": null,
            "publication": {
                "state": "NOT_REQUESTED",
                "refusalReasons": []
            }
        }
    },
    "id": "7759336395",
    "language": "pl-PL",
    "publication": {
        "status": "INACTIVE",
        "duration": null,
        "endedBy": null,
        "endingAt": null,
        "startingAt": null,
        "republish": false,
        "marketplaces": {
            "base": {
                "id": "allegro-pl"
            },
            "additional": []
        }
    },
    "validation": {
        "errors": [],
        "warnings": [],
        "validatedAt": "2024-04-25T08:34:41.728Z"
    },
    "createdAt": "2024-04-25T08:34:41.000Z",
    "updatedAt": "2024-04-25T08:34:41.744Z"
}

**Comment by Lukasz-Zurek** [comment]
Nie odnotowaliśmy większych problemów związanych z czasem aktywacji oferty na sandboxie. Generalnie trzymamy się zasady 60 minut, w czasie którym oferta powinna zostać wystawiona/aktywowana/wznowiona.

**Comment by Lukasz-Zurek** [comment]
@lubodzia To maksymalny czas. Dochodzi tutaj jednak kwestia związana ze środowiskiem testowym. Dla pewności - czy mógłbyś doprecyzować jeszcze od kiedy dokładnie wydłużył się czas aktywacji ofert i przesłać przykładowe trace-id? Z góry dziękuję.

**Comment by lubodzia** [comment]
Skąd wziąć trace-id? Dostałem tylko taką odpowiedź:
`{
    "name": "Sprężyna, klocek hamulcowy",
    "productSet": [
        {
            "product": {
                "id": "723fbbc9-178f-4fc4-810a-229471eb8a10",
                "publication": {
                    "status": "PROPOSED"
                },
                "parameters": [
                    {
                        "id": "248135",
                        "name": null,
                        "values": [
                            "Carmedia"
                        ],
                        "valuesIds": [
                            "248111_856102"
                        ],
                        "rangeValue": null
                    },
                    {
                        "id": "224017",
                        "name": null,
                        "values": [
                            "2024_04_25_77"
                        ],
                        "valuesIds": null,
                        "rangeValue": null
                    }
                ]
            },
            "quantity": {
                "value": 1
            },
            "responsiblePerson": null
        }
    ],
    "parameters": [
        {
            "id": "11323",
            "name": "Stan",
            "values": [
                "Nowy"
            ],
            "valuesIds": [
                "11323_1"
            ],
            "rangeValue": null
        }
    ],
    "images": [
        "https://a.allegroimg.allegrosandbox.pl/original/11ec19/862495c540f6a376844902a7a26d"
    ],
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "b84e26b9-a3b0-4f83-9301-e35b4ae1304d"
        },
        "returnPolicy": {
            "id": "d5d03cf4-5f29-480e-b653-782224161934"
        },
        "warranty": null
    },
    "payments": {
        "invoice": "VAT"
    },
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "200.00",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null
    },
    "stock": {
        "available": 10,
        "unit": "UNIT"
    },
    "location": {
        "countryCode": "PL",
        "province": "MAZOWIECKIE",
        "city": "Warszawa",
        "postCode": "02-972"
    },
    "delivery": {
        "shippingRates": {
            "id": "6ddafe04-d234-4cd5-9954-27184d729b63"
        },
        "handlingTime": "PT24H",
        "additionalInfo": null,
        "shipmentDate": null
    },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h2>BRAK OPISU AUKCJI</h2>"
                    }
                ]
            }
        ]
    },
    "external": {
        "id": "af1a8fff-68d9-4683-950a-52bac45b1b68_256"
    },
    "category": {
        "id": "313513"
    },
    "tax": null,
    "taxSettings": null,
    "sizeTable": null,
    "discounts": {
        "wholesalePriceList": null
    },
    "contact": null,
    "fundraisingCampaign": null,
    "messageToSellerSettings": {
        "mode": "OPTIONAL"
    },
    "attachments": [],
    "b2b": {
        "buyableOnlyByBusiness": false
    },
    "additionalServices": null,
    "compatibilityList": null,
    "additionalMarketplaces": {
        "allegro-cz": {
            "sellingMode": null,
            "publication": {
                "state": "NOT_REQUESTED",
                "refusalReasons": []
            }
        },
        "allegro-sk": {
            "sellingMode": null,
            "publication": {
                "state": "NOT_REQUESTED",
                "refusalReasons": []
            }
        }
    },
    "id": "7759336395",
    "language": "pl-PL",
    "publication": {
        "status": "INACTIVE",
        "duration": null,
        "endedBy": null,
        "endingAt": null,
        "startingAt": null,
        "republish": false,
        "marketplaces": {
            "base": {
                "id": "allegro-pl"
            },
            "additional": []
        }
    },
    "validation": {
        "errors": [],
        "warnings": [],
        "validatedAt": "2024-04-25T08:34:41.728Z"
    },
    "createdAt": "2024-04-25T08:34:41.000Z",
    "updatedAt": "2024-04-25T08:34:41.744Z"
}`

Na request:
`{
    "productSet": [
        {
            "product": {
                "name": "Spr\u0119\u017Cyna, klocek hamulcowy",
                "images": [
                    "https://source.unsplash.com/user/c_v_r/1900\u00D7800"
                ],
                "parameters": [
                    {
                        "id": "224017",
                        "values": [
                            "2024_04_25_77"
                        ]
                    },
                    {
                        "id": "248135",
                        "values": [
                            "Carmedia"
                        ]
                    }
                ],
                "category": {
                    "id": "313513"
                }
            }
        }
    ],
    "parameters": [
        {
            "id": "11323",
            "values": [
                "Nowy"
            ]
        }
    ],
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "200.00",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 10
    },
    "messageToSellerSettings": {
        "mode": "OPTIONAL",
        "hint": null
    },
    "b2b": {
        "buyableOnlyByBusiness": false
    },
    "external": {
        "id": "af1a8fff-68d9-4683-950a-52bac45b1b68_256"
    },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "\u003Ch2\u003EBRAK OPISU AUKCJI\u003C/h2\u003E",
                        "url": null
                    }
                ]
            }
        ]
    }
}`

Url: https://api.allegro.pl.allegrosandbox.pl/sale/product-offers

**Comment by lubodzia** [comment]
Problem zauważyliśmy od 22 kwietnia czyli od początku tego tygodnia.

**Comment by Lukasz-Zurek** [comment]
@lubodzia Ok, ta sytuacja dotyczy wydłużenia czasu publikacji po naszej stronie, a szerzej poinformowaliśmy o tym w [tym newsie](https://developer.allegro.pl/news/zaczynamy-dokladniej-weryfikowac-oferty-wydluzamy-czas-publikacji-0AlRZz9gksG).

**Comment by lubodzia** [comment]
Dziękuję w takim razie za informacje 👍
