### ISSUE TITLE
Problem logging into Sandbox

### ISSUE THREAD

**Issue by Andrithor** [allegro/allegro-api#8955]
Hi. 
I want to use the sandbox enviroment to place an order to the integrator system. The connection between the integrator and Allegro is working but I need to see what data will be sent over to the integrator system. But I can not login to the sanbox enviroment, how can I log in so I can get a mirror of the real account in sandbox enviroment?

**Comment by Andrithor** [comment]
Aha, ok. Thank you for the answer.
So I need the integrator to make a separate connection to the sandbox enviroment I guess.

**Comment by Andrithor** [comment]
Another question, does the business account in the Sandbox enviroment have to be verified as well?

**Comment by Andrithor** [comment]
It´s not possible to create an account in the sandbox enviroment, when I have filled in all the absic information and click on "Next" nothing happens.
![image](https://github.com/allegro/allegro-api/assets/34315740/9593e8b9-38d3-4aac-b2d0-78603c14f01a)

**Comment by PrzemyslawLukanowski** [comment]
> So I need the integrator to make a separate connection to the sandbox enviroment I guess.

Yes, exactly.

> Another question, does the business account in the Sandbox enviroment have to be verified as well? And do I really need to put in bank details?? And get the bank verified?

Yes, this is a similar process to the production, but in this case, you don't need to provide real data, you can use fake bank account number, generated by an online tool.

**Comment by PrzemyslawLukanowski** [comment]
You can send any files, it doesn't have to be a bank documents.

**Comment by Andrithor** [comment]
How long does it take for the "bank details" to be verified?

**Comment by PrzemyslawLukanowski** [comment]
Please send me login/mail so I can activate it manually.

**Comment by Andrithor** [comment]
Is it ok to send here? Or should I send an e-mail to you?

**Comment by PrzemyslawLukanowski** [comment]
Password is not necessary, I just activated your account.
