### ISSUE TITLE
Filter for search in descriptions

### ISSUE THREAD

**Issue by gupiccraft** [allegro/allegro-api#896]
The site I made (broavto.com) successfully displays the desired ads with the help of the GetTeamSheet function using several filters, including searching in headings. But the third day I can not find the filter you need to search in the descriptions. 

I ask for help from knowledgeable people.

**Comment by MartaNowaczyk** [comment]
@gupiccraft We are talking here about the [allegro API](https://developer.allegro.pl/en/). Do you have any questions about that?

**Comment by gupiccraft** [comment]
Well, this question is about Allegro Web API. I have a valid site, working on Allegro Web API. But I need to add a function, bark searching for ads by description. Since this is done at the Allegro itself, marking the point **"szukaj też w opisach ofert"**. I studied the documentation for a long time but did not find the opportunity to do it. Therefore, I ask for help.

**Comment by PawelTaberski** [comment]
You can search by description in WebAPI when you first use doGetItemsList in response section filters you will get all possible filters:
`            <ns1:item>
               <ns1:filterId>description</ns1:filterId>
               <ns1:filterName>Szukaj też w opisach i parametrach</ns1:filterName>
               <ns1:filterType>country</ns1:filterType>
               <ns1:filterControlType>checkbox</ns1:filterControlType>
               <ns1:filterDataType>boolean</ns1:filterDataType>
               <ns1:filterIsRange>false</ns1:filterIsRange>
               <ns1:filterRelations>
                  <ns1:relationAnd>
                     <ns1:item>search</ns1:item>
                  </ns1:relationAnd>
                  <ns1:relationExclude>
                     <ns1:item>categoryPage</ns1:item>
                     <ns1:item>departmentPage</ns1:item>
                     <ns1:item>mainPage</ns1:item>
                     <ns1:item>similar</ns1:item>
                     <ns1:item>special</ns1:item>
                  </ns1:relationExclude>
               </ns1:filterRelations>
            </ns1:item>
`

**Comment by gupiccraft** [comment]
Looks like this is what I need! Just the function doGetItemsList returns only 20 filters, and among them there is no filter with ID description. Anyway, thanks for the help.
