### ISSUE TITLE
Allegro shipping - printing labels via API

### ISSUE THREAD

**Issue by ZArez22** [allegro/allegro-api#8968]
Hello how can we print shipping labels for "allegro shipping" via API?

We print in our warehouse directly on Zebra printers labels from PPL, DPD, GLS. But in Allegro portal we found shipping via "Allegro" which is cheaper.

Thank you Milan Zarecky

**Comment by MartaNowaczyk** [comment]
If you use "[Ship with Allegro](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV)" you can create labels, and receive them in PDF, EPL or ZPL file. For more information about labels, see [the dedicated guide](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-create-a-label-for-shipment) on our website.

**Comment by ZArez22** [comment]
Perfect Marta thank you so much. M
