### ISSUE TITLE
Can we create One Fulfilment Account on Sandbox account?

### ISSUE THREAD

**Issue by mohan-mandal-pattern** [allegro/allegro-api#8976]
Are we able to create One fulfilment account on Sandbox account and are we able to create order on that account to test the One fulfilment type order?

**Comment by PrzemyslawLukanowski** [comment]
Yes, you need to create a company account and we can mark such it as One Fulfillment type. Please note that there shouldn't be any offers on the account until we change the account type.

**Comment by mohan-mandal-pattern** [comment]
How to create a company account? Can you give us a link for that account setup?

**Comment by PrzemyslawLukanowski** [comment]
Here's the link https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F - if you are seeing this page in Polish, change the language settings on the top-right corner.

**Comment by mohan-mandal-pattern** [comment]
Email - allegro@pattern.com and Username - Pattern_EU 
This is our sandbox business account. What do we need to create a One fulfilment account?

**Comment by PrzemyslawLukanowski** [comment]
We need to mark this account as One Fulfillment type. I've forwarded this request to the team responsible for the One Fulfillment service. I'll be back with answer when it's done, please be patient.

**Comment by PrzemyslawLukanowski** [comment]
I see that you already have two active offers on this account. Sorry, but as I mentioned there can't be any offers on the account, please register a new account.

**Comment by mohan-mandal-pattern** [comment]
Before converting to One Fulfilment type, the Live Business count should not include offers. Am I right?

**Comment by mohan-mandal-pattern** [comment]
Is it possible for the Sandbox account to link to a One fulfilment account as mentioned in the Allegro documentation [here](https://allegro.pl/pomoc/dla-sprzedajacych/one-fulfillment-by-allegro/jak-zaczac-korzystac-z-one-fulfillment-by-allegro-aMDP0d4dYs4#how-to-create-a-one-fulfillment-account-based-on-a-business-account)?

**Comment by PrzemyslawLukanowski** [comment]
I'm verifying it with the team responsible for the One Fulfillment service.

**Comment by mohan-mandal-pattern** [comment]
@PrzemyslawLukanowski do you have any update regarding this?

**Comment by PrzemyslawLukanowski** [comment]
Yes, sorry for the delay, but yesterday we had a bank holiday in Poland (tomorrow also). I received information that on Sandbox you need to create a new account and after that, we can mark it as a One Fulfillment type.

**Comment by mohan-mandal-pattern** [comment]
OK but do we have to follow the same requirement given in the documentation [here](https://allegro.pl/pomoc/dla-sprzedajacych/one-fulfillment-by-allegro/jak-zaczac-korzystac-z-one-fulfillment-by-allegro-aMDP0d4dYs4#how-to-create-a-one-fulfillment-account-based-on-a-business-account)?

**Comment by PrzemyslawLukanowski** [comment]
No, you just need to have a company account with no offers.

**Comment by mohan-mandal-pattern** [comment]
As I mentioned earlier, I have a Sandbox account, but I don't know how to create a One Fulfilment account. Can you assist me with this, please?

**Comment by PrzemyslawLukanowski** [comment]
As I wrote above, you need to create a new company account via this link https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F and after that, send me the account login - we will mark it as One Fulfillment.
