### ISSUE TITLE
Czy da się pobrać dane wszystkich produktów przypisanych do konta?

### ISSUE THREAD

**Issue by jurtomasz13** [allegro/allegro-api#8979]
Tak jak w tytule, czy jest możliwość pobrania wszystkich produktów dla danego konta? Widziałem, że jest opcja pobrania poszczególnych produktów wg. id, fraz itp aczkolwiek potrzebowałbym całą listę albo jeśli się nie da to dla wszystkich produktów z wybranego zamówienia.

**Comment by PrzemyslawLukanowski** [comment]
Nie udostępniamy takiej funkcjonalności. Informację o przypisanym produkcie możesz sprawdzić jedynie w szczegółach oferty [GET /sale/product-offers/{offerID}](https://developer.allegro.pl/documentation#tag/User's-offer-information).

**Comment by jurtomasz13** [comment]
Dziękuję za informację
