### ISSUE TITLE
Brak mozliwosci wystawiania ofert w allegro sandbox

### ISSUE THREAD

**Issue by kotarbamateusz** [allegro/allegro-api#898]
Nie mam możliwość wystawiania ofert, bo muszę dokonać wstępnej płatności, a tej nie mogę zrobić, bo akceptacja płatności nie działa (przycisk accept i decline nie reaguje)
![opera_2018-11-15_12-49-24](https://user-images.githubusercontent.com/38426380/48554241-28d17700-e8de-11e8-80f8-b683938f7c02.png)

Proszę o akceptacje wystawiania aukcji dla 
Konta: testamateusz
Adres email: kotarbamateusz@gmail.com

na witrynie
https://allegro.pl.allegrosandbox.pl

**Comment by MartaNowaczyk** [comment]
@kotarbamateusz konto aktywowane

**Comment by daksamit** [comment]
Problem zauważyłem jużjakiś czas temu.
Czym to jest spowodowane bądź kiedy będzie naprawione?
Też nie mogę aktywować konta: daksamit@daksamit.pl

**Comment by PawelTaberski** [comment]
Wstępnie aktywowałem Twoje konto, aby je w pełni aktywować przejdź do zakładki Moje Konto i prześlij do nas dokumenty do weryfikacji z załączonymi dowolnymi dwoma plikami.
