### ISSUE TITLE
Zostałeś zablokowany Sandbox

### ISSUE THREAD

**Issue by many-to-one** [allegro/allegro-api#8980]
Nie mogę zalogować się przez swoją aplikacje a nawet wejść na sandbox, dostaję komunikat: "Zostałeś zablokowany"

Nie wiem czy nie jest powodem błąd w cdn axios, bo wykorzystuję kod JavaScript do logowania:

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
u tego linka wygasł SSL certyfikat

Zamieniłem link na właściwy i po próbie logowania najpierw dostałem sprawdzanie na robota, a potem komunikat o zablokowaniu

<< Zostałeś zablokowany.

Dlaczego zostałeś zablokowany? Coś w zachowaniu twojej przeglądarki zwróciło naszą uwagę. Powody mogą być różne:
 przeglądasz strony i klikasz dużo szybciej niż przeciętny człowiek
 coś uniemożliwia działanie Javascript na twoim komputerze
 w tej samej sieci (IP ***.**.***.**) operuje robot
Jeśli coś nie działa prawidłowo wyślij nam wiadomość. >>

**Comment by PrzemyslawLukanowski** [comment]
Prześlij proszę powyższe informacje, ale **wraz z adresem IP**, przez [formularz kontaktowy.](https://allegro.pl/pomoc/kontakt). Zweryfikujemy ten przypadek.

**Comment by many-to-one** [comment]
Mineło trochę czasu i zadziałało, wystarczyło poczekać
