### ISSUE TITLE
Waluta nie jest wspierana przez metodę dostawy

### ISSUE THREAD

**Issue by piojoch** [allegro/allegro-api#8981]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry, mam problem z nadaniem przesyłki z metodą "Allegro Kurier DPD Czechy pobranie" (1bffdb01-72dc-434a-a940-0242ac120002). Dostaję komunikat "Waluta nie jest wspierana przez metodę dostawy (VALIDATION_ERROR: The currency is not supported by the delivery option)". Jest to zamówienie do Czech, zatem zarówno kwotę pobrania, jak i wartość paczki wskazuję w koronach czeskich.

CommandId: db39fad5-d1a6-4a38-a925-dbaa4113331b

Proszę o informacje w czym tutaj jest problem.

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, w tym przypadku ubezpieczenie musisz podać w PLN. Te informacje, jaką walutę przekazać, znajdziesz w odpowiedzi [GET /shipment-management/delivery-services](https://developer.allegro.pl/documentation#operation/getDeliveryServices):

```
        {
            "id": {
                "deliveryMethodId": "1bffdb01-72dc-434a-a940-0242ac120002",
                "credentialsId": null
            },
            "name": "Allegro Kurier DPD Czechy pobranie",
...
            "marketplaces": [
                "allegro-cz"
            ],
            "cashOnDelivery": {
                "limit": 50000,
                "currency": "CZK",
                "paymentType": "WALLET_TRANSFER",
                "forceRequireIban": false
            },
            "insurance": {
                "limit": 50000,
                "currency": "PLN"
            }...
        },
```
Waluta dla COD zawsze jest związane z rynkiem dostawy, który zwracamy w "marketplaces". Natomiast waluta ubezpieczenia zależy od kraju operatora - w tym przypadku dostawę realizuje DPD Polska.

**Comment by piojoch** [comment]
Dziękuję.
