### ISSUE TITLE
Dodawanie nowego produktu Sandbox API

### ISSUE THREAD

**Issue by many-to-one** [allegro/allegro-api#8982]
'trace-id': '934e67a58752e29'

Nie mogę podmienić wartość EAN na inny przy dodawaniu nowego produktu. Jak zostawiam stary EAN to nie ma problemu

**Comment by PrzemyslawLukanowski** [comment]
Zwróciliśmy błąd "Niepoprawna wartość parametru EAN (GTIN)", ponieważ [zgodnie z informacją na stronie GS1](https://www.gs1.org/services/verified-by-gs1/results?gtin=5904659189888) taki EAN nie jest prawidłowy

**Comment by many-to-one** [comment]
Tak jest, udało się jak dodałem istniejący EAN, bo wcześniej dla testu dodawałem wymyślony. Dzięki za podpowiedź.
