### ISSUE TITLE
Podczas tworzenia oferty występuje błąd - 422 Podany adres obrazka jest nieprawidłowy

### ISSUE THREAD

**Issue by Morph21** [allegro/allegro-api#8989]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Próbuję utworzyć ofertę z obrazkiem i dostaję błąd tak jak w tytule, 422 Unprocessable entity

`{"errors":[{"code":"OfferImagesNotFoundException","message":"Invalid image address.","details":"OfferImagesNotFoundException","path":null,"userMessage":"Podany adres obrazka jest nieprawidłowy.","metadata":{}}]}`

Na początku próbowałem podawać adres url obrazka hostowany na naszym serwisie (nie wiem czy powinno się dać tak zrobić - jeśli tak to prosiłbym o potwierdzenie)
Następnie używając endpointu  POST /sale/images najpierw zrobiłem upload obrazka na serwer testowy allegro który przebiegł pomyślnie i adres url który został zwrócony przesłałem w body w liście "images".

Poniżej trace-id:

Próba nr 1 - adres url obrazka z własnego hostingu: trace-id: fd4163dc91e607be
Próba nr 2 - adres url obrazka allegro - trace-id: bd55f27e929d1515

**Comment by MartaNowaczyk** [comment]
Problemem było nieprawidłowe zdjęcie w samym produkcie. Usunęłam to zdjęcie, więc teraz problem nie powinien występować. Potwierdzam jeszcze, że można dodać własne linki.

**Comment by Morph21** [comment]
ok, dziękuję za pomoc
