### ISSUE TITLE
Aktywacja konta na sandboxie

### ISSUE THREAD

**Issue by krzysztofpawlik** [allegro/allegro-api#899]
Dzień dobry,
mam prośbę o aktywację konta na sandboxie.
W panelu widoczna jest cały czas informacja "Nieaktywne - trwa weryfikacja Twoich danych.".
Login: takemorenet

**Comment by PawelTaberski** [comment]
Wstępnie aktywowałem Twoje konto, aby w pełni aktywować konto firmowe musisz rozpocząć ścieżkę weryfikacji. Przejdź do zakładki Moje konto i prześlij nam jakieś dowolne dwa pliki.
