### ISSUE TITLE
Niepowodzenie getProductOfferProcessingStatus

### ISSUE THREAD

**Issue by matcapi** [allegro/allegro-api#8997]
Dzień dobry,

Chciałbym poprosić o opisanie przypadku niepowodzenia
https://developer.allegro.pl/documentation#operation/getProductOfferProcessingStatus

Trafił do mnie przypadek, w którym dostajemy 404 z  ```Wskazana operacja nie istnieje: 57b3f646-76e0-4a82-b921-1f93efe4e85f.```.
Wiem, że po tygodniu operacje są usuwane, ale nie wiem jak wyglądał response oraz jak go obsłużyć, gdy operacja została wykonana.

**Comment by Lukasz-Zurek** [comment]
Co do zasady - w momencie, gdy zakończymy przetwarzać operację, w odpowiedzi na żądanie GET /sale/product-offers/{offerId}/operations/{operationId} wysyłamy status **HTTP 303 See Other**, a w nagłówku `location` przekazujemy odnośnik kierujący do zasobu z danymi oferty.

Przykładowy response:

```
HTTP/1.1: 303 See other
location: https://api.allegro.pl/sale/product-offers/numer_oferty
```

**Comment by matcapi** [comment]
Czy mogę założyć, że w przypadku statusu 303 response body zawsze będzie puste?

**Comment by Lukasz-Zurek** [comment]
@matcapi Dopytuję jeszcze dla pewności, czy nie przewidujemy tu przypadkiem sytuacji, w których body jest zwracane. Wkrótce wrócę do Ciebie z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
@matcapi Upewniłem się w tej kwestii, konsultując to z zespołem odpowiedzialnym za funkcjonalność - potwierdzam, że w przypadku statusu 303 response body zawsze będzie puste.

**Comment by matcapi** [comment]
Dziękuję za informacje.
