### ISSUE TITLE
ERR_INTERNAL_SYSTEM_ERROR

### ISSUE THREAD

**Issue by waliwdenko** [allegro/allegro-api#9]
SoapFault exception: [ERR_INTERNAL_SYSTEM_ERROR] Wewnętrzny bład systemu. OFFER_DEFAULT_ERROR_MESSAGE

przy próbie modyfikacji aukcji, jak mamy diagnozować taki problem?

**Comment by MarcinLuczak** [comment]
Czy problem nadal występuje? Jakich ofert dotyczy? Każdej, czy tylko niektórych? Jeśli tak, to proszę o podanie przykładów.

Jakie elementy tych ofert mają być edytowane?

**Comment by AdamDudarski** [comment]
Mamy ten sam komunikat podczas próby wystawienia aukcji. Pozostałe metody działają. Jedynie metoda doNewAuctionExt zwraca błąd:

<soap-env:envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
	<soap-env:body>
		<soap-env:fault>
			<faultcode>ERR_INTERNAL_SYSTEM_ERROR</faultcode>
			<faultstring>Internal system error</faultstring>
			<faultactor>Internal system error</faultactor>
		</soap-env:fault>
	</soap-env:body>
</soap-env:envelope>

Problem występuje od kilku dni. Działa aktualizacja kategorii i parametrów, nie można jednak wystawić aukcji. 

Klient zgłaszał problem za pośrednictwem formularza kontaktowego i na Państwa koncie na fb, nakazano mu jednak skontaktowanie się za naszym pośrednictwem z obsługą WebAPI. Konto, na którym występuje problem to konto o loginie 'tribecco'.

**Comment by MarcinLuczak** [comment]
@AdamDudarski nie możesz wystawić żadnej oferty? Dla każdej z nich pokazuje się ten komunikat błędu? Podeślij proszę za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt#appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=43e5756c-725f-449a-973d-21bd06e213fb) XML-e z requestem i responsem, w których problem jest widoczny. 

> skontaktowanie się za naszym pośrednictwem z obsługą WebAPI

Naszym, czyli jakim? Jesteś dostawcą oprogramowania, za pośrednictwem którego użytkownicy korzystają z Allegro? Jakie to oprogramowanie/firma?

**Comment by AdamDudarski** [comment]
@MarcinLuczak Tak, jesteśmy dostawcą oprogramowania sklepowego, w którym można wystawiać aukcje za pośrednictwem WebAPI. 

Jedyną metodą, w której występuje problem jest metoda doNewAuctionExt. 

Klient korzysta jeszcze z oprogramowania innego dostawcy. Otrzymaliśmy screeny od klienta przedstawiające w nim ten sam błąd, dlatego zasugerowaliśmy uszkodzone konto i kontakt bezpośrednio z Państwem, jednak skierowano klienta z powrotem do nas.

Przesłałem wszystkie dane i request za pośrednictwem formularza kontaktowego [Ticket#1246202470].

**Comment by kormichu** [comment]
Potwierdzam na naszych sklepach występuje to samo.  Mam już nawet napisany specjalny "fix" na ten problem odpytując się po kilka razy z 1s przerwą jeśli wywali Internal system error. Niestety nie zawsze to pomaga

**Comment by MarcinLuczak** [comment]
Czy powtarzanie tych zapytań powoduje, że one są wykonywane prawidłowo, czy błąd nadal jest zwracany?

**Comment by AdamDudarski** [comment]
Podczas moich testów na tym koncie, ani razu nie udało mi się wystawić aukcji. Każdorazowo występuje błąd Internal System Error. Każda próba wystawienia aukcji na tym koncie kończy się tym błędem. 

Otrzymałem odpowiedź od Państwa w sprawie zgłoszenia wysłanego przez formularz kontaktowy:
"Proszę jednak, aby wskazany Sprzedający skontaktował się z nami z przypisanego do konta adresu e-mail. Tylko w takiej sytuacji będę mogła udzielić informacji odnośnie pojawiającego się komunikatu."

Śmieszna sprawa bo wcześniej poproszono Sprzedającego o to by dostawca oprogramowania skontaktował się w sprawie tego problemu z obsługą WebAPI.

Tak czy inaczej, przed chwilą spróbowałem jeszcze usunąć załączane zdjęcia z formularza, bo zauważyłem że posiadają znak wodny. Same zdjęcia nie są duże. Okazało się, że jedno z nich powoduje ten błąd. Zdjęcie ma wymiary 345 x 800px (95.16 kB). Format PNG. W tym samym formularzu przesyłane są jeszcze trzy inne zdjęcia, zarówno większe wagowo jak i wymiarowo i jedno z nich jest też zdjęciem w formacie png. Każde z nich przechodzi a to jedno nie..... Pozostawienie tylko tego zdjęcia w formularzu powoduje błąd. Usunięcie tylko jego i pozostawienie trzech pozostałych umożliwia wystawienie aukcji. Zagadka... 

Jest to schemat elementu który klient wykorzystuje w wielu produktach.

WebAPI analizuje jakoś te zdjęcia i jeśli uzna że np. zawiera znak wodny to kończy sprawę błędem wewnętrznym?

**Comment by MarcinLuczak** [comment]
@AdamDudarski API sprawdza czy zdjęcie jest prawidłowo zapisane, tzn. czy jest zapisane zgodnie z algorytmami danego rozszerzenia. Jeśli coś jest nie tak z plikiem, API nie przepuści takiego zdjęcia. Proszę zamiast niego dodać zdjęcie prawidłowo zapisane do pliku *.png.

**Comment by AdamDudarski** [comment]
Zgadza się, po ponownym zapisaniu zdjęcia aukcja przeszła. Dziękuję za pomoc.

**Comment by kormichu** [comment]
@MarcinLuczak jeszcze odnośnie ponawiania requestów. Nie monitoruje całego ruchu (z uwagi na duże rozmiary requestów dodających aukcje) więc ciężko mi powiedzieć czy zawsze to pomoga. Jak widać w przypadku @AdamDudarski nie. Mam za to przypadek w którym wywołanie po raz drugi tego samego requestu pomogło:

`
2018-02-13T14:23:53+01:00 INFO (6): #doNewAuctionExt
...

RESPONSE HEADERS: 

HTTP/1.1 500 Internal Service Error
Date: Tue, 13 Feb 2018 13:23:38 GMT
Server: Apache
Vary: Accept-Encoding
Set-Cookie: ws2=<< ciach >>; expires=Tue, 13-Feb-2018 13:53:38 GMT; path=/; domain=.allegro.pl
X-SOAPIgnore: true
X-SOAPMethod: doNewAuctionExt
Set-Cookie: QXLSESSID=<< ciach >>%2F%2F02; path=/; domain=.allegro.pl; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Length: 368
Content-Type: text/xml; charset=utf-8

RESPONSE: 

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>ERR_INTERNAL_SYSTEM_ERROR</faultcode><faultstring>Wewnętrzny bład systemu.</faultstring><faultactor>doNewAuctionExt - Internal System Error.</faultactor></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>`

I ponowienie requestu:

`2018-02-13T14:23:53+01:00 INFO (6): #doNewAuctionExt
...
RESPONSE HEADERS: 

HTTP/1.1 200 OK
Date: Tue, 13 Feb 2018 13:23:48 GMT
Server: Apache
Vary: Accept-Encoding
Set-Cookie: ws2=<< ciach >>; expires=Tue, 13-Feb-2018 13:53:48 GMT; path=/; domain=.allegro.pl
X-SOAPIgnore: true
X-SOAPMethod: doNewAuctionExt
Set-Cookie: QXLSESSID=<< ciach >>%2F%2F02; path=/; domain=.allegro.pl; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Length: 399
Content-Type: text/xml; charset=utf-8

RESPONSE: 

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php"><SOAP-ENV:Body><ns1:doNewAuctionExtResponse><ns1:itemId>7183352310</ns1:itemId><ns1:i
temInfo>0</ns1:itemInfo><ns1:itemIsAllegroStandard>0</ns1:itemIsAllegroStandard></ns1:doNewAuctionExtResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>`

Logi zapisują się dopiero po wykonaniu wszystkich requestów dlatego proszę się sugerować datami w nagłówkach odpowiedzi

**Comment by MarcinLuczak** [comment]
@kormichu dziękuję, ale same response'y niestety nie wystarczą. Udostępnij proszę także requesty, abym mógł się im przyjrzeć.

**Comment by kormichu** [comment]
Emaila z requestami już do Was wysyłałem w trochę innej sprawie bo najprawdopodobniej związanej ze zbyt długą odpowiedzią serwera przy wystawianiu aukcji. Co dziwne logger requestów, który miałem zamontowany na phpowy SoapClient logował jedynie nagłówki odpowiedzi bez samego body (Content-length był zwracany dodatni). Ale mniejsza o to. Email poszedł do Macieja Potepa i dotyczył 2 klientów: ljk14 oraz Met-Rol-Bud​

**Comment by MarcinLuczak** [comment]
@kormichu ale czy to były requesty, dla których w responsie zwracaliśmy ERR_INTERNAL_SYSTEM_ERROR?

**Comment by kormichu** [comment]
Z logów requestów który wysłałem na maila był tam jeden i znajdował się w pliku Met-Rol-Bud-allegro-api.log.txt.zip . Jest tam też sporo innych bo włączałem logowanie requestów okresowo. Jak będzie trzeba to wyślę jeszcze raz maila bo nie chcę tutaj wstawiać danych klienta

**Comment by MaciejPotepa** [comment]
> Z logów requestów który wysłałem na maila był tam jeden i znajdował się w pliku Met-Rol-Bud-allegro-api.log.txt.zip . Jest tam też sporo innych bo włączałem logowanie requestów okresowo. Jak będzie trzeba to wyślę jeszcze raz maila bo nie chcę tutaj wstawiać danych klienta

Wszystkie pliki mamy i nadal pracujemy nad tym problemem. Sytuacja jest bardzo rozproszona i ciężka do namierzenia. Prosimy o cierpliwość i przepraszam za kłopoty.
