### ISSUE TITLE
Data zakończenia wyróżnienia aukcji

### ISSUE THREAD

**Issue by sz4rlej** [allegro/allegro-api#90]
Nie mogę znaleźć w dokumentacji stąd pytanie: czy istnieje możliwość pobrania daty zakończenia promowania/wyróżnienia dla aukcji?

Może jest możliwość pobrania listy obciążeń konta razem z datami i numerami aukcji, których te obciążenia dotyczą?

**Comment by MarcinLuczak** [comment]
@sz4rlej 

> Nie mogę znaleźć w dokumentacji stąd pytanie: czy istnieje możliwość pobrania daty zakończenia promowania/wyróżnienia dla aukcji?

Oferta będzie promowana/wyróżniona dopóki jest wystawiona. Chyba, że ręcznie wyłączysz w niej promowanie.


> Może jest możliwość pobrania listy obciążeń konta razem z datami i numerami aukcji, których te obciążenia dotyczą?

Metoda [doMyBillingItem](https://allegro.pl/webapi/documentation.php/show/id,301) powinna w tym przypadku pomóc.

**Comment by Lebioda** [comment]
@sz4rlej Czy nie pytasz czasem o to: https://github.com/allegro/allegro-api/issues/90
