### ISSUE TITLE
Sandbox różnica w moich ofertach

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#900]
Hej,
Jak to możliwe, że w Ustawieniach w moich ofertach mam 86 aukcji:
![image](https://user-images.githubusercontent.com/24191650/48571890-4a475880-e908-11e8-9ba3-3e011eb0915a.png)

A w sprzedawanych ofertach, które widzą wszyscy ponad 2.5k?:
https://allegro.pl.allegrosandbox.pl/uzytkownik/titolr10?order=m

**Comment by PawelTaberski** [comment]
Jesteś pewny, że nie masz ustawionego jakiegoś filtrowania np. tylko po zaplanowanych? Podeślij proszę pełny zrzut.

**Comment by jakubmaguza** [comment]
![image](https://user-images.githubusercontent.com/24191650/48606705-6555af00-e980-11e8-93e7-a44f98cf2995.png)

**Comment by PawelTaberski** [comment]
Rzeczywiście dziwnie to wygląda sprawę zgłosiłem do sprawdzenia zespołowi odpowiedzialnemu za tą funkcjonalność. Proszę o cierpliwość.

**Comment by jakubmaguza** [comment]
Czy coś wiadomo w tym temacie? Albo czy moglibyście przynajmniej wyczyścić do zera moje konto z aukcji?

**Comment by PawelTaberski** [comment]
Już wiem w czym jest problem "Moje Oferty" na Sandboxie nie posiadają danych z czasów, w których istniała tylko zakładka "Sprzedaję". Dlatego każda nowo założona oferta oczywiście będzie widoczna w zakładce Moje Oferty i każda edycja oferty, której nie widać w zakładce "Moje Oferty" spowoduje pojawienie się jej w "Moje oferty". Jest to oczywiście błąd, ale tak jak mówiłem przy edycjach i po dłuższym okresie dane te powinny się wyrównać.

**Comment by jakubmaguza** [comment]
Okej, ale do zakładki "Sprzedaję" nie mogę wejść, więc proszę o wyczyszczenie wszystkich aukcji :)

**Comment by jakubmaguza** [comment]
Dziękuję :)

**Comment by PawelTaberski** [comment]
Rozmawiałem z zespołem odpowiedzialnym za tą funkcjonalność i w najbliższym czasie nie będziemy uspójniać tych danych, gdyż wymaga to dużych nakładów pracy, a nie wpływa aż tak negatywnie na testowanie. Zwłaszcza, że po API zwracamy poprawne dane.

**Comment by jakubmaguza** [comment]
To ja może jeszcze raz poproszę:
Proszę o USUNIĘCIE, albo wyczyszczenie mojego konta na sandboxie. Nie potrzebuję synchronizacji, tylko potrzebuję pozbyć się tych wszystkich aukcji.

**Comment by PawelTaberski** [comment]
Przekazałem Twoją prośbę do tego zespołu.

**Comment by PawelTaberski** [comment]
Tak, jak pisałem przekazałem Twoją prośbę do odpowiedniego zespołu, niestety nic więcej zrobić w tej kwestii nie mogę. Nie jestem w stanie Tobie sam wyczyścić tych danych.

**Comment by jakubmaguza** [comment]
Niestety 'odpowiedni zespół' okazał się nieodpowiedni, ponieważ przez ponad miesiąc nie zrobili nic. Czy jest szansa na przekazanie tego jakiemuś innemu zespołowi ? :) Raz na jakiś czas czyścicie sandboxa z tego co mi wiadomo.
PS. Wszystkiego dobrego :)

**Comment by jakubmaguza** [comment]
Chyba bot wam źle działa, bo pojawiła się nowa odpowiedź :)

**Comment by PawelTaberski** [comment]
@jakubmaguza Rzeczywiście dziwne, mało tego nawet na maila nie otrzymałem powiadomienia o wcześniejszej Twojej informacji. Dopiero o tej teraz. Ponadto od zespołu, który pracuje nad tą funkcjonalnością dostałem informacje, że nie będziemy automatycznie usuwać tamtych ofert.

**Comment by jakubmaguza** [comment]
> każda edycja oferty, której nie widać w zakładce "Moje Oferty" spowoduje pojawienie się jej w "Moje oferty". Jest to oczywiście błąd, ale tak jak mówiłem przy edycjach i po dłuższym okresie dane te powinny się wyrównać.

Próbowałem pobrać listę wszystkich moich ofert żeby je edytować i móc je usunąć. Niestety wykonanie zapytania na zasobie sale/offers zwraca mi:

"count":20,
"totalCount":89

czyli tylko oferty widoczne w zakładce "Moje Oferty". Nie mogąc pobrać tych ofert nie mogę ich edytować. Proszę o pomoc raz jeszcze...

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa, wraz z trace-id. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 900 na GitHub-ie.

**Comment by jakubmaguza** [comment]
Request to po prostu:
```
curl -X GET \
  https://api.allegro.pl.allegrosandbox.pl/sale/offers \
 -H 'Authorization: Bearer {token}' \
 -H 'content-type: application/vnd.allegro.beta.v1+json'
```
a response:
![image](https://user-images.githubusercontent.com/24191650/51320437-17345900-1a60-11e9-9858-3a2ebb66fa30.png)

W tym zapytaniu chyba nie ma TraceID.

**Comment by PawelTaberski** [comment]
@jakubmaguza  Bardziej chodziło mi o id usera itp, dlatego prosiłem o całość przez formularz kontaktowy, ale już rozumiem w czym masz problem. Z defaultu zgodnie z dokumentacją [GET /sale/offers](https://developer.allegro.pl/documentation/#/offer-management/searchOffersUsingGET) zwracamy 20 w wyniku, aby przejrzeć wszystkie musisz użyć parametrów limit i offset.

**Comment by jakubmaguza** [comment]
To nic nie zmienia, bo i tak TotalCount = 89. Jeśli ustawię limit na 1000, to jedyne w responsie otrzymuję:

    "count":89,"totalCount":89

To nie jest problem zapytania IMO.
Pobieram dane dla swojego zalogowanego konta, więc w parametrach jest tylko bearer, nic więcej.
Konto: https://allegro.pl.allegrosandbox.pl/uzytkownik/titolr10?order=m&bmatch=baseline-dict-resort-uni-1-0-0108

Jeśli jednak udałoby się po prostu wyczyścić to wszystko, to też będzie dobre rozwiązanie.

**Comment by PawelTaberski** [comment]
Teraz rozumiem sądziłem, że masz na myśli że dostajesz tylko 20 z 89 a ofert na tym koncie masz znacznie więcej i nie wszystkie są tu widoczne. Podeśli proszę jeszcze to trace-id masz je w nagłówkach w responsie.

**Comment by jakubmaguza** [comment]
Trace-Id=a156baf7b219abd8

**Comment by PawelTaberski** [comment]
@jakubmaguza Jednak niezbędny będzie pełny request z tokenem z jakiego korzystasz i respons do tego tokena wraz z trace-id. Podeślij proszę te dane przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) i zaznacz, że że dane są potrzebne do ticketa numer 900 na GitHub-ie. Wygląda to na błąd.

**Comment by jakubmaguza** [comment]
Wysłane. Czy mogę generować nowe bearery, czy muszę poczekać aż sprawdzicie na tym?

Zgłoszenie numer "04493210" ref:_00D24aE05._5001o3DDzQ3:ref

**Comment by PawelTaberski** [comment]
@jakubmaguza Możesz działać normalnie ze spokojem.

**Comment by PawelTaberski** [comment]
@jakubmaguza Udało nam się przeindeksować Twoje oferty przez Moje Allegro powinieneś widzieć już wszystkie oferty jakie masz na tym koncie, i możesz je zakończyć.

**Comment by jakubmaguza** [comment]
Na razie wszystko działa, dzięki!

**Comment by PawelTaberski** [comment]
OK, to zamykam 👍
