### ISSUE TITLE
How to Create a Test Order with Allegro Prices Program in Sandbox

### ISSUE THREAD

**Issue by unwnu** [allegro/allegro-api#9002]
Dear Allegro Support Team,

From your [documentation](https://allegro.pl/regulamin/zalacznik/21), I understand that the selection of offers for the program is made automatically, which might not allow us to thoroughly test the discount as needed.

Could you please guide me on how to create a test order with the Allegro Prices program?
Specifically, I am interested in how I can apply a discount to a specific product in the sandbox.

Thank you for your assistance.

**Comment by MartaNowaczyk** [comment]
Give me the offer number from the account on the sandbox and I will try to add it to the Allegro Prices program. Only then you will be able to test your purchase with such an offer.

**Comment by unwnu** [comment]
ID: 7738719739

**Comment by MartaNowaczyk** [comment]
Your offer with id 7738719739 is already in prgram Allegro Prices. You can make a test purchase using another account.

**Comment by unwnu** [comment]
@MartaNowaczyk Everything is good. Thanks again for your assistance.

**Comment by Vitalka13** [comment]
Dzień dobry!
Tydzień temu Allegro usunęło wszystkie oferty z naszego asortymentu i musieliśmy stworzyć nowe. Więc bardzo proszę, aby Państwo znowu włączyli nam promo Allegro Ceny dla jednej oferty. Podaję ID 7773093455.
Z góry dziękuję!
