### ISSUE TITLE
Niestabilność  /sale/categories/{categoryId}/parameters

### ISSUE THREAD

**Issue by deneb-k** [allegro/allegro-api#901]
W dokumentacji parametry typu string, którym można podać więcej niż jedną wartość oznaczone są jako multipleChoices. Tydzień temu zauważyłem, ze ten parametr zniknął i trzeba rozpoznawać to po maxValues. A teraz maxValues zmieniło się na allowedNumberOfValues.

Na czym to finalnie stanie i kiedy? Wysyłam nagłówek "Accept: application/vnd.allegro.public.v1+json" i oczekiwałbym tu jakiejś stabilności.

Przykładowo dla kategorii 67480:
`
[id] => 216917
                    [name] => Załączone wyposażenie
                    [type] => string
                    [required] => 
                    [unit] => 
                    [options] => stdClass Object
                        (
                            [variantsAllowed] => 
                            [variantsEqual] => 
                        )
                    [restrictions] => stdClass Object
                        (
                            [minLength] => 1
                            [maxLength] => 40
                            [allowedNumberOfValues] => 10
                        )
`

**Comment by TomekKaczmarek** [comment]
@deneb-k faktycznie - przeoczyliśmy wcześniej to pole i nie było udokumentowane. Przepraszamy za kłopot.

Na przyszłość, jeśli taka sytuacja będzie miała miejsce, zgłoś nam proszę, że mamy nieudokumentowane pole w modelu, zanim zaczniesz z niego korzystać.

**Comment by deneb-k** [comment]
Właściwie ciężko było się zorientować, ze to pole jest nieudokumentowane, bo w dokumentacji parametr z polem "dictionary" ma wpisany typ "string". Więc z dokumentacji by wynikało, że w string też jest multipleChoices.
