### ISSUE TITLE
ERR_CATEGORY_LIMITED

### ISSUE THREAD

**Issue by mjag8** [allegro/allegro-api#902]
Pracuję nad draftem dla nowej oferty, wystawiam produkt w kategorii '250193', to samo występuje też 
 przynajmniej w przypadku przypisania kategorii '250806'.

Wywołuję GET na sale/offers/{id}
- otrzymuję mój draft

Następnie PUT na sale/offers/{id}

Zwraca:

    ["errors"]=>
    array(1) {
      [0]=>
      object(stdClass)#399 (5) {
        ["code"]=>
        string(16) "VALIDATION_ERROR"
        ["message"]=>
        string(20) "ERR_CATEGORY_LIMITED"
        ["details"]=>
        string(0) ""
        ["path"]=>
        string(0) ""
        ["userMessage"]=>
        string(0) ""
      }

Gdzieś w dokumentacji WebAPI stoi:
**ERR_CATEGORY_LIMITED**
Wystawianie ofert w tej kategorii zostało ograniczone.

Co robić w tym wypadku? Czy jakieś kategorie zostały jeszcze ograniczone pod tym względem (jeżeli ten komunikat jest poprawny)?

**Comment by PawelTaberski** [comment]
Sprzedaż w niektórych kategoriach wymaga spełnienia odpowiednich warunków, tak jest i również w tym przypadku. 
Sprzedaż w kategorii Ebooki prowadzić mogą wyłącznie oficjalni dystrybutorzy, po spełnieniu odpowiednich wymagań technicznych i podpisaniu osobnej umowy z Allegro. Więcej na ten temat znajdziesz [tutaj](https://allegro.pl/pomoc/dla-sprzedajacych/przedmioty-zakazane-i-dopuszczone-warunkowo/publikacje-elektroniczne-e-booki-audiobooki-videobooki-itp-mGwAg1qLRHM).

**Comment by mjag8** [comment]
Problem rozwiązany :+1:
