### ISSUE TITLE
WZA nie da się zamówić Allegro Kurier DPD

### ISSUE THREAD

**Issue by krzysztofgal** [allegro/allegro-api#9021]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x ] inny / other

:beetle: **Opis / Description**

Zamawianie przesyłki kończy się komunikatem " Wybrana metoda dostawy nie obsługuje tego zamówienia Delivery Method is not available for this order", ja korzystam ze starego api WZA ale inni sprzedawcy również sygnalizują problem. Metody innych przwoźników i np. One DPD działają.

**Comment by MaciejFrackowiak** [comment]
Proszę podaj przykładowe trace-id wywołania.

**Comment by krzysztofgal** [comment]
Nie mam możliwości teraz tego zrobić.

**Comment by MaciejFrackowiak** [comment]
Przekaż w zleceniu nadania przesyłki metodę dostawy stricte z zamówienia, wówczas nie będzie żadnego problemu.

**Comment by krzysztofgal** [comment]
Breaking change bez żadnej zapowiedzi to żaden problem, rozumiem można zamykać XD.

**Comment by MaciejFrackowiak** [comment]
Nie wprowadziliśmy tu żadnej zmiany. Mechanizm tak działa "od zawsze".
