### ISSUE TITLE
API trouble with DPD

### ISSUE THREAD

**Issue by BRfastcr** [allegro/allegro-api#9035]
Hello,
I would like to ask you for help me with our troubles with Get Shipment.
We are testing the API on the Allegro sandbox.
We call allegro to register Shipment, but we get an error message "Unexpected carrier error"

ShipmentId = d007c984-39cc-461e-9a82-a473b6a364fe
{"commandId":"777ed523-e3e7-4db0-a058-a48b7fa46cc5","status":"ERROR","errors":[{"code":"UNKNOWN_ERROR","message":"Unexpected carrier error","details":null,"path":null,"userMessage":"Nieoczekiwany błąd

There is no error with other carriers (e.g. WEDO).

Could you please help?

**Comment by MartaNowaczyk** [comment]
I will check it out closely and will let you know.

**Comment by MartaNowaczyk** [comment]
Providing the sender's phone number (sender.phone) should help. We will correct the error message on our side.

**Comment by BRfastcr** [comment]
We added the sender.phone data and now we have a test without an error.

We now have another error that we don't know what it means.
20.05.2024
13:54
{"commandId":"f04416d8-20cc-4664-8276-226846c7ff13","status":"ERROR","errors":[{"code":"CARRIER_API_CLIENT_UNAVAILABLE","message":"Carrier Api Clientis temporary unavailable - try again later or repo

![image](https://github.com/allegro/allegro-api/assets/167966561/25da4a5b-6d01-4fb2-a3f8-e09855fcb18b)

**Comment by BRfastcr** [comment]
Hi,
we tried the registration a little later and everything was fine.
Thank you
