### ISSUE TITLE
Webapi

### ISSUE THREAD

**Issue by swiatpociech** [allegro/allegro-api#904]
Skrypt .php importujący zamówienia z systemu allegro przestał importować te zamówienia 15 listopada ok godziny 16;30. Skrypt działa, bo importuje zamówienia sprzed tej daty ale nie chce zaimportować zamówień późniejszych. Wprowadzone zostały zmiany Webapi właśnie tego dnia, czy może to mieć to wpływ na działanie skryptu ?

# Logowanie Webapi

$client = new SoapClient('https://webapi.allegro.pl/uploader.php?wsdl');
$version = $client->doQuerySysStatus(1, 1, $webapi_key);
$session = $client->doLoginEnc($login, base64_encode( hash('sha256', $pass, true) ), 1, $webapi_key, $version['ver-key']);

# doLoginEnc - dane zwracane

$nr_sesji = $session['session-handle-part']; // nr sesji
$user_id = $session['user-id']; // nr zalogowanego użytkownika
$server_time = $session['server-time']; // aktualny unixowy czas z serwera allegro

# TUTAJ BĘDZIEMY DODAWAĆ KOLEJNE ZAPYTANIA

} // koniec try WebApi
catch(SoapFault $error) // wychwytywanie błędów
{
echo 'Błąd ', $error->faultcode, ': ', $error->faultstring, "n";
}

$transakcje = $client->doGetSiteJournalDeals($nr_sesji, $pozycja_startowa);

/* $przedmiot = $transakcje->{'site-journal-array'}; // tytuł przedmiotu */

foreach($transakcje as $item)
{

$i=0;

$ile++;
foreach($item as $item2)
 {
 $i++;
 switch($i)
  {
  case 1:
   $pozycja_startowa=$item2;
   echo "start: ".$pozycja_startowa."<br>";
   break;

  case 2:
   $typ_zdarzenia=$item2;
   break;
  
  case 3:
   $timestamp=$item2;
   $item2=gmdate("Y-m-d\TH:i:s\Z", $timestamp);
   break;

  case 4:
   $id_aktu_zakupowego=$item2;
   break;
   
  case 5:
   $item_kopia=$item2;
   break;

  case 7:
   $identyfikator_oferty=$item2;
   break;

  case 9:
   $ilosc_kup_teraz=$item2;
   break;

  case 8:
   $kontrahent = $client->doGetPostBuyData($nr_sesji,array($identyfikator_oferty),array($item2));
   foreach($kontrahent as $item3)
   { 
   $t=0;
   foreach($item3 as $item4)
   {
   $t++;
   if($t==2)
    {
    foreach($item4 as $item5)
     {
     foreach($item5 as $item6)
      {
      foreach($item6 as $item7)
       {
       $r++;
       switch($r)
        {
        case 2:
         $nick_allegro=$item7;
         break;

        case 4:
         $imie_allegro=$item7;
         break;

        case 5:
         $nazwisko_allegro=$item7;
         break;

        case 7:
         $firma_allegro=$item7;
         break;

        case 10:
         $kod_allegro=$item7;
         break;

        case 11: 
         $miasto_allegro=$item7;
         break;

        case 12:
         $adres_allegro=$item7;
         break;

        case 13;
         $email_allegro=$item7;
         break;

        case 14:
         $telefon_allegro=$item7;
         break;

        }
       }
      }
     }
    }
   }
  }
  break;
  }
 }

$dane_oferty = $client->doShowItemInfoExt($nr_sesji, $identyfikator_oferty);
foreach($dane_oferty as $transakcja_1)
{
$przedmiot_tytul_1 = $transakcja_1->{'it-name'};
$get_gr = trim($przedmiot_tytul_1);
$dane_wej = array(',');
$dane_wyj = array('.');
$przedmiot_tytul_1=str_replace( $dane_wej, $dane_wyj, $get_gr);

$cena_kup_teraz = $transakcja_1->{'it-buy-now-price'};
break;
}

$cena_kup_teraz_razem=$ilosc_kup_teraz*$cena_kup_teraz;
echo $przedmiot_tytul_1."<br>".$id_aktu_zakupowego."<br>";
$r=0;
$formularz_kupna = $client->doGetPostBuyFormsDataForSellers($nr_sesji,array($item_kopia));
   foreach($formularz_kupna as $transakcja)
    {
    $adres_wysylki = $transakcja->{'post-buy-form-shipment-address'};
    $kod_wys = $adres_wysylki->{'post-buy-form-adr-postcode'};
    $adres_wys = $adres_wysylki->{'post-buy-form-adr-street'};
    $miasto_wys = $adres_wysylki->{'post-buy-form-adr-city'};
    $name_wys = $adres_wysylki->{'post-buy-form-adr-full-name'};
    $firma_wys = $adres_wysylki->{'post-buy-form-adr-company'};
    $telefon_wys = $adres_wysylki->{'post-buy-form-adr-phone'};
    
    $dane_do_fv = $transakcja->{'post-buy-form-invoice-data'};
    $firma_fv = $dane_do_fv->{'post-buy-form-adr-company'};
    $name_fv = $dane_do_fv->{'post-buy-form-adr-full-name'};
    $adres_fv = $dane_do_fv->{'post-buy-form-adr-street'};
    $kod_fv = $dane_do_fv->{'post-buy-form-adr-postcode'};
    $miasto_fv = $dane_do_fv->{'post-buy-form-adr-city'};
    $nip_fv = $dane_do_fv->{'post-buy-form-adr-nip'};

    $wiadomosc_sprzed = $transakcja->{'post-buy-form-msg-to-seller'};
     $get_gr = trim($wiadomosc_sprzed);
     $dane_wej = array(',');
     $dane_wyj = array('.');
     $wiadomosc_sprzed=str_replace( $dane_wej, $dane_wyj, $get_gr);
    $czy_fv = $transakcja->{'post-buy-form-invoice-option'};
    $metoda_platosci = $transakcja->{'post-buy-form-pay-type'};

    $status_platnosci = $transakcja->{'post-buy-form-pay-status'};
    $cena_dost = $transakcja->{'post-buy-form-postage-amount'};
    $cena_z_dost = $transakcja->{'post-buy-form-amount'};
    
    $dane_produktu = $transakcja->{'post-buy-form-items'};

    $punkt_odbioru = $transakcja->{'post-buy-form-gd-address'};
    $nazwa_po1 = $punkt_odbioru->{'post-buy-form-adr-full-name'};
    $nazwa_po2 = explode(" ",$nazwa_po1);
    $nazwa_po = $nazwa_po2[1];
    $nazwa_sposobu_dostawy = $transakcja->{'post-buy-form-shipment-id'};

    foreach($dane_produktu as $itemi)
     {
     $d_prod = $itemi->{'post-buy-form-it-deals'};
     $przedmiot_tytul=$itemi->{'post-buy-form-it-title'};
     foreach($d_prod as $itemi1)
      {
      $cena_prod = $itemi1->{'deal-final-price'};
      $ilosc_prod = $itemi1->{'deal-quantity'};
      }
     }
    }

**Comment by kocyk74** [comment]
Proponuje zacząć od zmiany:
`$client = new SoapClient('https://webapi.allegro.pl/uploader.php?wsdl');`
na
`$client = new SoapClient('https://webapi.allegro.pl/service.php?wsdl');`

**Comment by swiatpociech** [comment]
Po zmianie wyrzuca taki błąd:
Błąd Sender: Element '{https://webapi.allegro.pl/service.php}DoQuerySysStatusRequest': Missing child element(s). Expected is ( {https://webapi.allegro.pl/service.php}sysvar ). n

**Comment by swiatpociech** [comment]
Problem rozwiązany, wyskakiwał Fatal Error przy próbie importu sprzedaży z oferty którą usunęło Allegro i na tym skrypt przerywał działanie, zbieg okoliczności.

Dziękuję za pomoc
