### ISSUE TITLE
Info o limitach znaków w generowaniu etykiet.

### ISSUE THREAD

**Issue by Sellasist** [allegro/allegro-api#9040]
Użytkownicy Sellasist korzystający z integracji z Allegro zwrócili problem w generowaniu etykiet przy sprzedaży na Allegro z kilkoma przewoźnikami. Mianowicie chodzi o ilość znaków w niektórych rubrykach. 

Przykładowo sprzedając ten sam produkt przez przewoźnika A i B, u A w polu opisu przesyłki mieści się dany tekst, a u B po wydruku zostaje on ucięty. Stąd do wprowadzenia poprawek w Sellasist potrzebujemy znać ilość dostępnych znaków dla konkretnych pól, konkretnych form wysyłki lub chociaż wskazówki, gdzie szukać takiej info.

Chodzi konkretnie o:

API Wysyłam z Allegro / przewoźnik Packeta
w polu opis przesyłki (parcel / description)

API Wysyłam z Allegro (ogólne):
pole label / reference number (nr referencyjny)

API Poczta Polska
Pole opis (przesyłka type)

API InPost ShipX
Pole uwagi (comments)

**Comment by MaciejFrackowiak** [comment]
Description dla Packeta - max 128 znaków.

referenceNumber w zależności od operatora:
- Allegro One - 35 znaków,
- UPS - 35 znaków,
- DPD - 27 znaków,
- Poczta Polska - 36 znaków,
- InPost - 28 znaków,
- DHL - 36 znaków,
- Orlen - 36 znaków,
- Packeta - 36 znaków.

W pozostałych kwestiach proszę o kontakt z PP i InPost, ponieważ nie są to nasze API.
