### ISSUE TITLE
Błąd podczas wystawiania oferty. "Nie znaleziono produktu dla wskazanego identyfikatora.".

### ISSUE THREAD

**Issue by lubodzia** [allegro/allegro-api#9049]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dostaje niezrozumiały błąd podczas tworzenia oferty, po zmianie kodu produktu oferta powstaje. 
W parametrach podaje kod towaru 2024_05_17_03 dostaje błąd "**Nie znaleziono produktu dla wskazanego identyfikatora.**". Nie rozumiem czym jest ten błąd spowodowany. Jeżeli towaru nie ma w katalogu o danym identyfikatorze to chyba powinien być dodany z czasem do katalogu?
Proszę o wyjaśnienie co było przyczyną błędu abym mógł się przed nim ustrzec w przyszłości.

Request:
`{
    "productSet": [
        {
            "product": {
                "name": "Uszczelka, filtr oleju",
                "images": [
                    "https://bcsafilesdev.blob.core.windows.net/bd5895d5-395f-4f72-b39f-c27ff0d659e9/img_14.jpg?skoid=7ff2a1fc-787f-4a5d-a78e-f1dd85cdbda7\u0026sktid=53d83e1d-82ae-4273-84e9-01ec5045dd81\u0026skt=2024-05-17T09%3A49%3A22Z\u0026ske=2024-05-24T09%3A49%3A21Z\u0026sks=b\u0026skv=2023-11-03\u0026sv=2023-11-03\u0026st=2024-05-17T09%3A49%3A22Z\u0026se=2024-05-24T09%3A49%3A21Z\u0026sr=b\u0026sp=r\u0026sig=%2BQ6En2tugXC0pUFRBPBJQ35PsYATPyHDj0AsGS5nxMQ%3D"
                ],
                "parameters": [
                    {
                        "id": "224017",
                        "values": [
                            "2024_05_17_03"
                        ]
                    },
                    {
                        "id": "248135",
                        "values": [
                            "Skross"
                        ]
                    }
                ],
                "category": {
                    "id": "313513"
                }
            }
        }
    ],
    "parameters": [
        {
            "id": "11323",
            "values": [
                "Nowy"
            ]
        }
    ],
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "1.00",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 20
    },
    "messageToSellerSettings": {
        "mode": "OPTIONAL",
        "hint": null
    },
    "publication": {
        "duration": "P3D",
        "endingAt": null,
        "startingAt": null,
        "status": null,
        "republish": false
    },
    "b2b": {
        "buyableOnlyByBusiness": false
    },
    "external": {
        "id": "1592110a-e098-496f-b289-8c4ae8c6a1fc_133"
    },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "IMAGE",
                        "content": null,
                        "url": "https://bcsafilesdev.blob.core.windows.net/bd5895d5-395f-4f72-b39f-c27ff0d659e9/img_14.jpg?skoid=7ff2a1fc-787f-4a5d-a78e-f1dd85cdbda7\u0026sktid=53d83e1d-82ae-4273-84e9-01ec5045dd81\u0026skt=2024-05-17T09%3A49%3A22Z\u0026ske=2024-05-24T09%3A49%3A21Z\u0026sks=b\u0026skv=2023-11-03\u0026sv=2023-11-03\u0026st=2024-05-17T09%3A49%3A22Z\u0026se=2024-05-24T09%3A49%3A21Z\u0026sr=b\u0026sp=r\u0026sig=%2BQ6En2tugXC0pUFRBPBJQ35PsYATPyHDj0AsGS5nxMQ%3D"
                    },
                    {
                        "type": "TEXT",
                        "content": "\u003Ch1\u003Eala ma kota\u003C/h1\u003E",
                        "url": null
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "\u003Ch2\u003Eaaa\u003C/h2\u003E",
                        "url": null
                    },
                    {
                        "type": "IMAGE",
                        "content": null,
                        "url": "https://bcsafilesdev.blob.core.windows.net/bd5895d5-395f-4f72-b39f-c27ff0d659e9/img_14.jpg?skoid=7ff2a1fc-787f-4a5d-a78e-f1dd85cdbda7\u0026sktid=53d83e1d-82ae-4273-84e9-01ec5045dd81\u0026skt=2024-05-17T09%3A49%3A22Z\u0026ske=2024-05-24T09%3A49%3A21Z\u0026sks=b\u0026skv=2023-11-03\u0026sv=2023-11-03\u0026st=2024-05-17T09%3A49%3A22Z\u0026se=2024-05-24T09%3A49%3A21Z\u0026sr=b\u0026sp=r\u0026sig=%2BQ6En2tugXC0pUFRBPBJQ35PsYATPyHDj0AsGS5nxMQ%3D"
                    }
                ]
            }
        ]
    }
}`

Response:
`{
    "errors": [
        {
            "code": "ProductNotFoundException",
            "message": "Unprocessable Entity",
            "details": null,
            "path": "productSet[0].product",
            "userMessage": "Nie znaleziono produktu dla wskazanego identyfikatora.",
            "metadata": {}
        }
    ]
}`

trace-id: "9f79c6329a8670e5",

**Comment by MartaNowaczyk** [comment]
Gdy nie ma podanego "product.id" powinna nastąpić próba dodania nowego produktu. Sprawdzimy jeszcze ten przypadek, także wrócę z informacją.

**Comment by MartaNowaczyk** [comment]
Błąd wystąpił po naszej stronie i będziemy starali się wyeliminować takie przypadki. Przepraszamy za niedogodności.
