### ISSUE TITLE
Puste odpowiedzi

### ISSUE THREAD

**Issue by lmakurat** [allegro/allegro-api#905]
Żądanie 
https://api.allegro.pl/order/checkout-forms

zwraca mi zawsze pusty wynik:
{
    "checkoutForms": [],
    "count": 0,
    "totalCount": 0
}

podobna sytuacja dla https://api.allegro.pl/order/events
{
    "events": []
}

Na koncie, dla którego wykonywane jest żądanie są zamówienia, i to z różnymi statusami.
Czy po stworzeniu aplikacji można zarządzać ACLami, do czego ma dostęp? Nie znalazłem takiej informacji, nigdzie, ale nie widzę innej przyczyny niezgodności danych w systemie z danymi w API.

**Comment by TomekKaczmarek** [comment]
Upewnij się, że jesteś zautoryzowany jako sprzedawca, który otrzymał te zamówienia. Pamiętaj też, że zwracamy dane z 60 ostatnich dni.
