### ISSUE TITLE
Planowanie wystawienia opóźnione o 1-2 godziny

### ISSUE THREAD

**Issue by jezewskiBNetrox** [allegro/allegro-api#9055]
Witam,

mam ostatnio taki problem, że usilnie Allegro dodaje mi bodajże 2 godziny do daty-godziny wystawienia.
Wysyłam obiekt `publication` w takiej formie:
```
   "publication":{
      "duration":"P3D",
      "endingAt":null,
      "marketplaces":null,
      "startingAt":"2024-05-20T21:01:01Z",
      "status":null,
      "endedBy":null,
      "republish":false
   }
```

Niestety taka aukcja wystawiłaby się o godzinie 23. Wygląda na to, że czas podawany przeze mnie jest traktowany jako UTC i dodawany jest różnica strefy czasowej. Co mogę zrobić, żeby API interpretowało czas prawidłowo?

**Comment by AureliuszBrussy** [comment]
Przesyłasz czas prawidłowo w "Zulu" (GMT), różni się on od czasu w naszej aktualne strefie czasowej (+2 względem GMT). Musisz uwzględnić strefy czasowe.

**Comment by jezewskiBNetrox** [comment]
@AureliuszBrussy Zatem jeżeli napiszę to w formie `2024-05-20T21:01:01+02:00` to API powinno rozpoznać to prawidłowo jako 21:01?

**Comment by AureliuszBrussy** [comment]
Nie, przyjmujemy i zwracamy czas tylko w UTC.
