### ISSUE TITLE
[REST] sale/loyalty/promotion max bundles

### ISSUE THREAD

**Issue by madkot** [allegro/allegro-api#906]
Dzień dobry,
wystawianie zestawów ma następujący warunek

- Do jednej oferty dodasz do 7 zestawów.

Chciałbym się dowiedzieć więcej, a mianowicie czy ten limit tyczy się zarówno ofert będących entry pointem jak i nie?
Jeśli wszystkich to jak allegro decyduje o wyświetleniu konkretnego bunda dla entry-pointa jeśli posiada przypisane więcej niż jeden zestaw?

**Comment by PawelTaberski** [comment]
Na wstępie chciałbym Tobie polecić nasz poradnik odnośnie zestawów i rabatów. Znajdziesz go [tutaj](https://developer.allegro.pl/offer_bundles/#5).
Odnośnie Twojego pytania nie wiem czy dobrze Ciebie zrozumiałem mamy 3 ograniczenia odnośnie zestawów:
- Zestaw możesz utworzyć z co najmniej 2 ofert.
- Zestaw możesz utworzyć z maksymalnie 9 ofert.
- Do jednej oferty dodasz do 7 zestawów.
O tym czy dany zestaw będzie się wyświetlał na wybranej ofercie, czy nie decydujesz w polu "promotionEntryPoint". Czyli jedna oferta może wchodzić w skład, aż 7 zestawów i zaprezentujemy na niej te 7 zestawów. Oczywiście w widoku oferty będzie to w formie zwiniętej listy.
