### ISSUE TITLE
customer information when they send a message

### ISSUE THREAD

**Issue by andreinacuellor** [allegro/allegro-api#9068]
Hi! 

there is any request that i can use to retrieve that from the customer(first name, last name, email) that send a message from the Allegro Message Center(offer, order) and Disputes message center?

**Comment by MaciejFrackowiak** [comment]
No, we don't have it. You can only match buyer data from [order details data](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET).

**Comment by andreinacuellor** [comment]
So if a customer send a message to a sellet from an offer, there is not way to get the customer information right?

**Comment by MaciejFrackowiak** [comment]
Right.

**Comment by andreinacuellor** [comment]
ok thanks
