### ISSUE TITLE
Roznice w zwracanych informacjach GET /sale/offers i sale/offers/{offerId}

### ISSUE THREAD

**Issue by JacusK** [allegro/allegro-api#907]
Dlaczego wywolanie /sale/offers i sale/offers/{offerId} zwraca rozne informacje ? Czy nie mozna tego ujednolicic ? np. w zbiorczym wywolaniu ofert sa informacje o dacie rozpoczecia oferty, ilosci wyswietlen, ilosci sprzedanych produktow, itp. a w wywolaniu konkretnej oferty offerId tych informacji nie ma. Konkretnie czesci informacji nie ma w ogole ( sprzedaz ) a czesc jest pusta ( data rozpoczecia, itp. )

**Comment by PawelTaberski** [comment]
Metody te służą do dwóch różnych celów dlatego też pola są różne. Metodą GET sale/offers/{offerId} pobierzesz wszystkie pola oferty , aby na tej podstawie wystawić podobną, bądź np. dokonać zmian w trwającej ofercie PUT-em. Natomiast GET /sale/offers  jest to twój listing ofert, którym pobierzesz zarówno zakończone oferty, jak i nawet drafty ofert. Więcej na ten temat [tutaj](https://developer.allegro.pl/my_offers/#1a).

**Comment by JacusK** [comment]
A czy nie mozna zrobic tego w taki sposob zeby dane zwracane dla konkretnej oferty zawieraly rowniez informacje dostepne w listingu ofert ?

**Comment by PawelTaberski** [comment]
Dane jakie pobierzesz metodą GET sale/offers/{offerId} służą do zmiany w ofercie i wystawiania nowych na jej podstawie i zawierają wszystkie pola jakie są niezbędne do stworzenia nowej oferty. Natomiast GET /sale/offers jest odwzorowaniem zakładki moje oferty dlatego pola w nich zawarte się różnią i nie mogą być identyczne.

**Comment by JacusK** [comment]
Zgadza sie - tylko ze jesli ja potrzebuje dane dotyczace statystyki ( czyli ilosc wyswietlen, ilosc produktow, itp. ) to musze pobrac wszystkie oferty i znalezc tylko te wlaciwa - zamiast pobrac jedna konkretna i miec juz te informacje. Czy nie prosciej byloby zawrzec te informacje przy pobraniu konkretnej oferty ?

**Comment by PawelTaberski** [comment]
Byłyby to nad wymiarowe pola w stosunku do tego czemu dedykowane są te metody. Ponadto większa ilość danych zwracanych w takie metodzie powodowała by obciążenie zasobów. Z tej perspektywy wydajniejsze jest wywołanie kilku metod, bądź jednej kilkukrotnie zamiast zwracanie wszystkiego w jednym responsie.
