### ISSUE TITLE
Allegro.cz: Can not access orders via REST API

### ISSUE THREAD

**Issue by nickn17** [allegro/allegro-api#9074]
We already have a REST API for our eshop (allegro.cz, client Id f0c209fca14a41bfaa046360982ff4ef)
sale/offers are working great. But if I would access to sold items / order list. Every order endpoint returns empty result. 

- order/events
- order/event-stats
- order/checkout-forms
- payments/payment-operations

However, users have already placed orders. Any idea why the rest api requests are empty?

![image](https://github.com/allegro/allegro-api/assets/8830860/eddab00b-32b0-4b0d-a6fa-3c4301643a64)

`
  | Array
-- | --
  | (
  | [status] => ok
  | [message] => OK
  | [url] => https://api.allegro.pl/order/events
  | [payload] => Array
  | (
  | )
  |  
  | [data] => Array
  | (
  | [events] => Array
  | (
  | )
  |  
  | )
  |  
  | [output] => {"events":[]}
  | )
  | Array
  | (
  | [status] => ok
  | [message] => OK
  | [url] => https://api.allegro.pl/order/event-stats
  | [payload] => Array
  | (
  | )
  |  
  | [data] => Array
  | (
  | [latestEvent] =>
  | )
  |  
  | [output] => {"latestEvent":null}
  | )
  | Array
  | (
  | [status] => ok
  | [message] => OK
  | [url] => https://api.allegro.pl/order/checkout-forms
  | [payload] => Array
  | (
  | )
  |  
  | [data] => Array
  | (
  | [checkoutForms] => Array
  | (
  | )
  |  
  | [count] => 0
  | [totalCount] => 0
  | )
  |  
  | [output] => {"checkoutForms":[],"count":0,"totalCount":0}
  | )
  | Array
  | (
  | [status] => ok
  | [message] => OK
  | [url] => https://api.allegro.pl/payments/payment-operations
  | [payload] => Array
  | (
  | )
  |  
  | [data] => Array
  | (
  | [paymentOperations] => Array
  | (
  | )
  |  
  | [count] => 0
  | [totalCount] => 0
  | )
  |  
  | [output] => {"paymentOperations":[],"count":0,"totalCount":0}
  | )

`

**Comment by PrzemyslawLukanowski** [comment]
It looks that you may using a token for the user, who doesn't have any orders, but to verify that I will need a sample trace-id of the response, where we returned an empty array. Also, could you please send me an order ID that should be visible on the account? You can get it from the order details in the orders tab.

**Comment by nickn17** [comment]
Please could you check also. Maybe I sent you wrong trace ID
https://api.allegro.pl/order/events
trace-id: 81079ef743f25bf1

SellerID  ****7063 is connected to APP with client ID xxxxxxx046360982ff4ef

SellerID **** 5693 is connected to appl with client ID xxxxxxxx87e2f94b3fd6c
But this is different eshop..

**Comment by PrzemyslawLukanowski** [comment]
This trace-id is also associated with the user ***693 and it was sent by ***982ff4ef app.

**Comment by nickn17** [comment]
How is this possible that I can login REST API applications client ID to another Allegro user :( 

If I log to https://apps.developer.allegro.pl/
I see for logged user smdled
APP smdledxxxxxxx.cz CLIENTID xxxxxxf94b3fd6c
In allegro.cz if see for this user smdled sellerID =  xxxxx5693

If I log to https://apps.developer.allegro.pl/
I see for logged user lacnepxxxxx
APP lacnepxxxxxx.sk CLIENTID xxxxxxxa046360982ff4ef
In allegro.cz if see for this user smdled sellerID =  xxxxx7063

When I perform OAUTH user, do you think APP is automatically logged with currently logged user on allegro.cz? 
It's not a bug that system allowed me to autenticate with different seller ID? 

Damn.. sale/offers
I see offer from another shop 
offers":[{"id":"15640076168","name":"LED žárovka halogenová G4 kapsule 20W 320LM 12V Halostar Oven OSRAM","ca

**Is there any request how to verify current seller id?** I have to add protection.
Or could your return after user autorization
https://allegro.cz/auth/oauth/token
sellerId and not only access/refresh token?

**Comment by nickn17** [comment]
I tested now... 

I log in allegro.cz, developer.allegro.pl with account A
on eshop A, i deleted token and autenticate again via oauth/ user token
- Now I see orders from shop A

I logout/login in allegro.cz, developer.allegro.pl with account B
on eshop B, i deleted token and autenticate again via oauth/ user token
Both sale/offers are now ok. 

But this bug should be fixed, this is not good, that you return token for app and totally different seller Id. **Autentication is automatically redirected without login/user form with currently logger user on your website.** 

Or please return seller Id in auth/oauth/token
I will add own protection. This could do a big problem when some shop export offers or import orders from another eshop.

**Comment by nickn17** [comment]
Thank you for an answer. Prompt=confirm and GET /me will be enough for me.
