### ISSUE TITLE
Pobieranie ofert i wycofanie endpointa /sale/offers

### ISSUE THREAD

**Issue by balandzik** [allegro/allegro-api#9076]
Chciałbym pobrać z API listę wszystkich moich aukcji. W dokumentacji doczytałem, że należy do tego celu użyć endpointa GET /sale/offers
Tymczasem dziś trafiłem na informację, że zostanie on wycofany. Nie umiem jednak znaleźć informacji, czy samo pobieranie listy aukcji będzie nadal aktywne, czy też należy skorzystać z jakiejś alternatywnej metody. Nie widzę odpowiednika, np. GET /sale/product-offers bez wskazywania konkretnej oferty, tylko do pobierania całości. Wydaje mi się, że GET /sale/offers do pobierania danych pozostaje, ale chciałbym się upewnić, że dobrze myślę.

**Comment by PrzemyslawLukanowski** [comment]
Tak, dobrze myślisz, na tę chwilę nie mamy planów, aby wycofać GET /sale/offers i nigdzie takiej informacji nie publikowaliśmy. Jeśli gdzieś znalazłeś takie dane, podziel się proszę linkiem, sprawdzimy to.

**Comment by balandzik** [comment]
Myślę, że podaliście komunikat precyzyjnie, nie ma się do czego przyczepić. Po prostu tytuł komunikatu
"Przypomnienie: wraz z końcem 2023 roku wyłączymy zasoby /sale/offers i /sale/offers/{offerId} "
Mógł sugerować, że cały endpoint /sale/offers zniknie. Dlatego chciałem się upewnić. Dziękuję za informację.
