### ISSUE TITLE
[Pytanie] Monety - kampanie

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#908]
Mam obecnie kilka tysięcy (nawet nie wiem dokładnie ile - dużo) kampanii monetowych dodanych do pojedynczych ofert. Teraz chciałbym przejść na nawy typ kampanii - dla kategorii. Czy jest sposób na zakończenie "starych" bez klikania w każdą ?

**Comment by PawelTaberski** [comment]
Obecnie nie mamy obsługi kampanii monetowych w API Allegro, także nie ma możliwości w ten sposób automatycznej zmiany. W przyszłości możliwe, że wdrożymy takie rozwiązanie. Jeśli tak to poinformujemy o tym w dedykowanym komunikacie.
