### ISSUE TITLE
Pobieranie list punktów odbioru Allegro Automat ORLEN Paczka

### ISSUE THREAD

**Issue by Tomash667** [allegro/allegro-api#9080]
Czy można za pomocą api allegro pobrać listę punktów odbioru dla Allegro Automat ORLEN Paczka? Wydaje mi się że nie ma takiej możliwość ale wolę się upewnić.

Metoda https://api.allegro.pl.allegrosandbox.pl/order/carriers/ORLEN/points zwraca 
Feature unavailable. Contact the application author

**Comment by MaciejFrackowiak** [comment]
Nie, punkty odbioru poza Allegro One dostępne są wyłącznie w API danego przewoźnika, w tym przypadku [Orlen](https://www.orlenpaczka.pl/integracja-z-orlen-paczka/).
