### ISSUE TITLE
Wartości słownikowe atrybutów

### ISSUE THREAD

**Issue by TomaszGrzywacz** [allegro/allegro-api#9081]
Proszę o pomoc, jak można odczytać pełną listę wartości słownikowych przypisanych do atrybutów właściwych dla danej kategorii.

Przykład: w kategorii "**Dom i Ogród - Narzędzia - Spawarki - Półautomaty spawalnicze**" atrybut "**Metody spawania**" może przyjąć wartość wybraną z listy: brak informacji; Cięcie plazmowe; MIG/MAG; MMA; PAW; SAW; TIG.

Niestety dostępny do pobrania plik z listą kategorii i atrybutów nie zawiera tych informacji. A chcemy w naszym systemie mieć pełne odwzorowanie w/w atrybutów.

**Comment by MaciejFrackowiak** [comment]
Korzystając z zasobu [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) możesz pobrać wszystkie parametry i wartości przypisane dla nich w danej kategorii.

**Comment by TomaszGrzywacz** [comment]
Dziękuję!
