### ISSUE TITLE
EAN issues ?

### ISSUE THREAD

**Issue by yao657355700** [allegro/allegro-api#9085]
May I ask if you will conduct detailed information verification on EAN in the future?
EAN has a record, but does not provide specific product information. Does this meet the requirements?

**Comment by PrzemyslawLukanowski** [comment]
Hello, we require that EAN should be registered in the [GS1](https://www.eprodukty.gs1.pl/catalog).

**Comment by yao657355700** [comment]
> Hello, we require that EAN should be registered in the [GS1](https://www.eprodukty.gs1.pl/catalog).

Is it okay if there is no registered product information?

**Comment by yao657355700** [comment]
> Hello, we require that EAN should be registered in the [GS1](https://www.eprodukty.gs1.pl/catalog).

Can you use your system to help me check if this EAN meets your requirements,
thanks
EAN：768420578454

**Comment by PrzemyslawLukanowski** [comment]
Yes, this EAN is correct, you can also check it on your own on the site I linked above.

<img width="929" alt="Zrzut ekranu 2024-05-24 o 09 54 00" src="https://github.com/allegro/allegro-api/assets/51473661/52044db2-aa72-4336-b7fc-30a6a3549eae">

**Comment by yao657355700** [comment]
Will your system program check if there is product information on the EAN code on the GS1 website?

**Comment by PrzemyslawLukanowski** [comment]
No, if EAN is registered in the GS1 that's enough for us.

**Comment by yao657355700** [comment]
> No, if EAN is registered in the GS1 that's enough for us.

What you're saying in this announcement is just checking if the EAN code is registered in GS1, right?
It won't check if there is any product information in the EAN code in GS1, will it?
![345](https://github.com/allegro/allegro-api/assets/87019541/7c935908-13b8-4c1e-8cc5-c8a4c7bf32a8)

**Comment by PrzemyslawLukanowski** [comment]
Yes, exactly.

**Comment by yao657355700** [comment]
/sale/offers
How can the product data returned by this interface be distinguished between these four states?
I can't distinguish it from the fields returned
![1234](https://github.com/allegro/allegro-api/assets/87019541/071418d5-d198-4051-8fc8-2a5fcf1abd68)

**Comment by PrzemyslawLukanowski** [comment]
This is an offer publication status, in our documentation, you can check possible values along with the description:

<img width="600" alt="Zrzut ekranu 2024-05-28 o 11 57 06" src="https://github.com/allegro/allegro-api/assets/51473661/82b50fc2-f451-4002-9328-973ed8488e00">

**Comment by yao657355700** [comment]
Why do I see the product in a Pending state in the background, but the API interface returns ENDED

**Comment by PrzemyslawLukanowski** [comment]
Pending is associated with ACTIVATING, but I assume you are using some google online translator, because there is not Pending status on the website, but "scheduled":
<img width="127" alt="Zrzut ekranu 2024-05-28 o 12 17 00" src="https://github.com/allegro/allegro-api/assets/51473661/10c2658a-ba24-4231-85a7-8343b9463c9d">

Please attach the screenshot with the offer id and visible status, I'll check it.

**Comment by yao657355700** [comment]
14106601401
13987676254
These two are in different states, but they both return ENDED
![12](https://github.com/allegro/allegro-api/assets/87019541/cefe9b47-e04d-4ebf-a05a-3caed768d40e)

**Comment by yao657355700** [comment]
API Data
![111](https://github.com/allegro/allegro-api/assets/87019541/9b57d722-82fe-4b69-93c8-b69cbd7e606c)
![222](https://github.com/allegro/allegro-api/assets/87019541/574dd148-9cc4-4a50-809b-9ee9fa4e3e37)

**Comment by PrzemyslawLukanowski** [comment]
Ok, now I see that you are a One Fulfillment seller. In this case, both statuses on the website are correct and are associated with the ENDED status in the API. Here you can check information from our [tutorial](https://developer.allegro.pl/tutorials/one-fulfillment-by-allegro-4R9dXyMPlc9):

<img width="516" alt="Zrzut ekranu 2024-05-28 o 12 39 04" src="https://github.com/allegro/allegro-api/assets/51473661/12d875a1-bf7a-4fb7-bf27-b52d98362544">

**Comment by yao657355700** [comment]
Can the API return the status directly corresponding to the backend product?

This approach now makes it difficult for us to distinguish which products are no longer available for sale,
Which products are currently in stock.

I don't know if you understand what I mean.

**Comment by PrzemyslawLukanowski** [comment]
I understand, but unfortunately, it is not possible.

**Comment by yao657355700** [comment]
Like the two products above me, 
One product is no longer for sale, while another product has just been launched and is currently being prepared for stocking. 
﻿ 
But my ERP system cannot distinguish the status of each of these two products

**Comment by PrzemyslawLukanowski** [comment]
Eventually, you can rely on `endedBy` field in the response to [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#tag/User's-offer-information
<img width="732" alt="Zrzut ekranu 2024-05-28 o 14 13 58" src="https://github.com/allegro/allegro-api/assets/51473661/206b6d35-b515-4ed9-b31c-75647517d404">
)

A different status will be returned for Pending ("EMPTY_STOCK") and different when you stop offer on your own ("USER").

**Comment by yao657355700** [comment]
good
I'll give it a try tomorrow.

Thank you very much for your help

**Comment by yao657355700** [comment]
I have two more questions to ask
1. Is there an interface to obtain the size and weight information of each product
2. Is there an interface to obtain the warehouse processing fee (OFA) for each order

**Comment by PrzemyslawLukanowski** [comment]
1. Unfortunately, no.
2.  Yes, you can retrieve it along with other fees via [GET /billing/billing-entries](https://developer.allegro.pl/documentation#operation/getBillingEntries).

**Comment by yao657355700** [comment]
But there is only one total number in this, not for each order

**Comment by PrzemyslawLukanowski** [comment]
This resource is a reflection of this tab - https://allegro.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro. If you see one entry also on the website, the API response is correct.

**Comment by yao657355700** [comment]
good
Thank you for your answer.
