### ISSUE TITLE
Aktywacja - sandbox

### ISSUE THREAD

**Issue by pmichalski-synthrone** [allegro/allegro-api#909]
Witam,

Potrzebuję aktywować w środowisku sandbox konto:
pawel-toeldorado

Niestety aktywacja przez payments simulator nie działa

**Comment by PawelTaberski** [comment]
Konto aktywowałem, powinno już wszystko działać.

**Comment by pmichalski-synthrone** [comment]
@PawelTaberski 
Dzięki.
Mogę liczyć na podpowiedź, czemu w takim razie otrzymuję w kroku 4b z 
https://developer.allegro.pl/auth/#DeviceFlow
odpowiedź
{"error":"Unauthorized","error_description":"Full authentication is required to access this resource"}

? Z góry dzięki

**Comment by pmichalski-synthrone** [comment]
@PawelTaberski 
Proszę jeszcze o aktywację dla konta:
integrations@synthrone.com

Dzięki

**Comment by PawelTaberski** [comment]
Wstępnie zaakceptowałem Twoje konto, aby w pełni aktywować konto firmowe musisz przejść do zakładki moje konto i wysłać do nas dokumenty do weryfikacji (jakieś dowolne 2 pliki).

**Comment by gorgotluk** [comment]
Dzień dobry,

@PawelTaberski 
Czy ja również mogę prosić o aktywację mojego konta na sandboxie. Login: gorgotluk. 

Z góry dziękuję.

**Comment by PawelTaberski** [comment]
@gorgotluk Wstępnie zaakceptowałem Twoje konto teraz (jak wyżej) musisz przejść do zakładki moje konto i wysłać do nas dokumenty do weryfikacji (jakieś dowolne 2 pliki).

**Comment by banachg** [comment]
Witam,

Prosze o aktywację sprzedaży na koncie banachg@gmail.com w sandboxie.
Niestety payments-simulator nie reaguje na próby aktywacji poprzez przelew.

**Comment by PawelTaberski** [comment]
@banachg Aktywowałem Twoje konto, powinno już działać.

**Comment by alabijak** [comment]
Dzień dobry, 
proszę o aktywację konta tes12345.

**Comment by PawelTaberski** [comment]
@alabijak Aktywowałem Twoje konto powinno już wszystko działać.

**Comment by matsie93** [comment]
Dzień dobry,
proszę o aktywację konta m2sienko na sandboxie. Wypełniłem formularz dla konta firma i wysłałem 2 przykładowe pdfy jednak nie otrzymałem żadnego maila potwierdzającego.

**Comment by PawelTaberski** [comment]
@matsie93 Aktywowałem Twoje konto

**Comment by kkrol93** [comment]
Dzień Dobry! Jest możliwość aktywacji konta krzysztofkrolm8@gmail.com? Z góry dziękuję!

**Comment by PawelTaberski** [comment]
Jesteś pewny, ze na taki adres e-mail założyłeś konto bo nie widzę konta z przypisanym takim adresem e-mail na Sandboxie

**Comment by kkrol93** [comment]
tak na 100 % krzysztofkrolm8@gmail.com :)

**Comment by PawelTaberski** [comment]
A jaki login, bo niestety pod takim mailem nic nie znajduje może to jakiś błąd.

**Comment by kkrol93** [comment]
kkrol93

**Comment by PawelTaberski** [comment]
Kwestia odświeżenia, dzięki za dane, już znalazłem i aktywowałem Twoje konto.

**Comment by kkrol93** [comment]
Wielkie dzięki!

**Comment by mushira** [comment]
Dzień dobry,
Proszę o aktywację konta:  ctinet (Client:44176545).
Niestety przy próbie autoryzacji (wejściu na url który powinien zwrócić token) nadal mam komunikat: "Full authentication is required to access this resource"

**Comment by MartaNowaczyk** [comment]
@mushira jeśli zgłoszenie dotyczy konta na produkcji zgłoś się przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt), gdzie ci pomogą. My możemy pomóc tylko na sandboxie ;)

**Comment by mushira** [comment]
Ale właśnie chodzi o sandbox :) @MartaNowaczyk 
> 
> 
> @mushira jeśli zgłoszenie dotyczy konta na produkcji zgłoś się przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt), gdzie ci pomogą. My możemy pomóc tylko na sandboxie ;)

**Comment by MartaNowaczyk** [comment]
@mushira sprawdziłam po Client:44176545 i był tylko na produkcji :P

jest konto ctinet, ale najpierw musisz wejść w Moje konto uzupełnić dane przedsiębiorstwa, wybrać zastosuj i później jeszcze w tym samym miejscu powinieneś wybrać dwa dowolne pliki i je wysłać, wtedy z automatu powinno ci zaakceptować konto firma :) Jakby coś nie poszło daj znać.

**Comment by mushira** [comment]
@MartaNowaczyk czy mogłabyś zerknąć na konto sandbox o którym pisałem wcześniej? (ctinet).
Dzięki :)

**Comment by mushira** [comment]
@MartaNowaczyk nadal mam zwrotkę:

<oauth><error_description>Full authentication is required to access this resource</error_description><error>unauthorized</error></oauth>

A w panelu sandbox mam info:
2019-05-13 13:33:01 | Pozytywna weryfikacja Allegro

**Comment by likrot** [comment]
Witam, poproszę o pełną aktywację konta: 44205187

**Comment by browin-pziemba** [comment]
Nie chcę otwierać nowego tematu, aktywacja przez Payment Simulator nie działa, proszę o aktywację:
piotr(dot)ziemba(at)browin(dot)com.

**Comment by arturm2** [comment]
Proszę o aktywację konta w Sandbox: arturm2
Dzięki, pozdrawiam,
artur

**Comment by PatrykBocian** [comment]
@arturm2 Proszę upewnij się, czy podałeś prawidłowe dane, bo nie widzę użytkownika o podanym loginie.

**Comment by arturm2** [comment]
Ustawiłem nazwę konta w sandbox: arturm2

Dzięki a szybką reakcję!

Artur

pt., 25 paź 2019, 14:15 użytkownik PatrykBocian <notifications@github.com>
napisał:

**Comment by PrzemyslawLukanowski** [comment]
@arturm2 Aktywowałem Twoje konto.

**Comment by arturm2** [comment]
Dzięki!

pt., 25 paź 2019, 14:26 użytkownik PrzemyslawLukanowski <
notifications@github.com> napisał:

**Comment by jacekskowron** [comment]
Prośba o aktywację konta w sandbox: jacekskowron
Dziękuję.

**Comment by MaciejFrackowiak** [comment]
@jacekskowron Widzę, że Twoje konto jest już w pełni aktywne.

**Comment by PrzemyslawLukanowski** [comment]
@elfiorr Aktywowałem Twoje konto.

**Comment by reprezenter** [comment]
Proszę aktywować konto: softmare_test

**Comment by AureliuszBrussy** [comment]
@reprezenter aktywowałem Twoje konto.
