### ISSUE TITLE
Allegro International Automaty Paczkowe Czechy

### ISSUE THREAD

**Issue by Pibrusz** [allegro/allegro-api#9099]
Witam 
wysyłając request z podaną metodą dostawy cały czas dostaję response: 
`Allegro returned error: Field: items.value.amount - Waluta nie jest wspierana przez metodę dostawy.`
Dla podanych service ID:
`"id": "0bdd3bfb-32c6-4602-b78f-b3146fe9f54a",
"id": "0e40225c-32c6-4602-b78f-b3146fe9f54a"`
jaka powinna być przesłana wartość w items.value.amount  (aktualnie wysyłany PLN, zgodnie z kiedyś uzyskaną informacją)?? 
request w załączeniu przez panel

**Comment by Pibrusz** [comment]
FYI W zgłoszeniu proszę powołać się na numer sprawy: 42373384

**Comment by Lukasz-Zurek** [comment]
@Pibrusz W przypadku usług dostawy, odpowiednio: 

0bdd3bfb-32c6-4602-b78f-b3146fe9f54a - PLN,
0e40225c-32c6-4602-b78f-b3146fe9f54a - CZK.

Informacje te zwracamy w polu **"insurance.currency"**, gdy skorzystasz z GET /shipment-management/delivery-services.
