### ISSUE TITLE
Rozbieznosci w sandboksie

### ISSUE THREAD

**Issue by JacusK** [allegro/allegro-api#910]
Skad sie biora takie rozbieznosci w sanboksie i API ?
Dla przykladu aukcja https://allegro.pl.allegrosandbox.pl/aparat-cyfrowy-sony-i6206010161.html
pokazuje ze jest dostepna 1 sztuka i 10 wyswietlen.
W Panelu Allegro w zakladce Sprzedaje pokazuje ze sa dostepne 2 sztuki i nie ma zadnej sprzedazy oraz zadnych wyswietlen. 
Natomiast w zaklace Sprzedane pokazuje ze zostala 1 sztuka sprzedana
Na dodatek API GET sale/offers tez zwraca rozne informacje dla tej konkretnej aukcji - brak sprzedanych produktow, dostepna 1 sztuka, 0 wyswietlen

**Comment by PawelTaberski** [comment]
Sprawdziłem i ilość zgadza mi się z tym co na froncie jest jedna sztuka i brak sprzedaży. Podeślij nam proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) zrzuty z Mojego Allegro np do tej oferty co podesłałeś i opisz rozbieżności jakie zauważyłeś. Dodatkowo podeślij proszę pełnego cURL-a i responsa wraz z trace-id z metody o której wspomniałeś. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 910 na GitHub-ie.

**Comment by JacusK** [comment]
Link do formularza kontaktowego jest do rzeczywistego Allegro - czy tam mam wyslac informacje ?
Poza tym, to napisalem w czym sa rozbieznosci - w ilosciach dostepnych, w sprzedazy, w ilosci wyswietlen
metoda sale/offers - dla tej konkretnej aukcji zwraca ilosc wyswietlen [visitsCount] = 1, sprzedaz [sold] = 0, ilosc [available] = 2 a metoda sale/offers/6206010161 zwraca ilosc [available] = 1
Nie bardzo wiem po co mam przesylac cale cURLe - skoro wyniki sa zwracane - tylko ze bledne

**Comment by PawelTaberski** [comment]
Potrzebujemy wyśledzić dany request i sprawdzić czemu jest taka rozbieżność. Dodatkowo zrzut z Mojego Allegro dałby mi pogląd gdzie dokładnie widzisz taką rozbieżność, bo tego nie jestem w stanie zobaczyć. Podeślij proszę te informacje ułatwi nam to rozwiązanie problemy i znacznie przyspieszy zdiagnozowanie.

**Comment by JacusK** [comment]
OK, ale nie uzyskalem odpowiedzi czy te dane mam przeslac przez formularz kontaktowy rzeczywistego Allegro ?

**Comment by PawelTaberski** [comment]
Tak i zaznacz, że dane są potrzebne do GitHuba ticket numer 910.

**Comment by JacusK** [comment]
Wysłane - Przyjęliśmy zgłoszenie numer "03978210" ref:_00D24aE05._5001o31HRkY:ref

**Comment by PawelTaberski** [comment]
@JacusK Ciągle czekam na przekazanie informacji, jednakże już udało mi się wykryć kilka podobnych przypadków i sprawę już przekazałem do poprawy do odpowiedniego zespołu. Proszę o cierpliwość.

**Comment by JacusK** [comment]
OK, czekam. Widze ze moj przypadek nie jest odosobniony - patrz #913

**Comment by PawelTaberski** [comment]
Udało nam się rozwiązać problem, ale dane zostaną zaktualizowane z 6 dni wstecz i od teraz będą już się poprawnie naliczać, także wcześniej nadal może występować pewna rozbieżność.
