### ISSUE TITLE
SANDBOX 503 service unavailable - Koszyk / składanie zamówienia

### ISSUE THREAD

**Issue by Smerf90** [allegro/allegro-api#9101]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

**SANDBOX**

Dzień dobry,
Nie jestem wstanie dodać, usunąć produktów z koszyka ani ich zamówić. 
![image](https://github.com/allegro/allegro-api/assets/64829995/b9daab32-3f04-47a2-be54-5b23fcc50d9b)

Ponowne logowanie nie pomaga. 

Czy to problem po mojej stronie? Jeśli tak, to w jaki sposób go rozwiązać? 

Pozdrawiam,
Maciej

**Comment by Lukasz-Zurek** [comment]
Problem przekazałem dalej do weryfikacji. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@Smerf90 Prześlij proszę więcej danych, np. login konta na sandboxie i numery ofert dodanych do koszyka.

**Comment by Smerf90** [comment]
Login konta na którym występuje problem: 106870666
Numery ofert z koszyka: 
7763305179 - oferta wystawiona kilka dni temu z mojego drugiego konta (firmowego) przez API
7749488814 - losowa oferta ze strony głównej, nie znam szczegółów

Konta nie używałem dłuższy czas t.j jakieś 2 miesiące. Wymagane więc było ponowne logowanie, wszystkie ciasteczka zaakceptowane. 

Zmiana ilości przedmiotów również nie jest możliwa. Liczba produktów się zmienia jednak wartość koszyka się nie aktualizuje. 

![image](https://github.com/allegro/allegro-api/assets/64829995/b6c48415-e63e-4a9c-b58b-91f65e2c23f7)

![image](https://github.com/allegro/allegro-api/assets/64829995/09337012-8ba4-4dd2-a637-06bf8c1884a0)

**Comment by Lukasz-Zurek** [comment]
@Smerf90 Ok, dziękuję za szczegóły :)

**Comment by Lukasz-Zurek** [comment]
@Smerf90 Sprawdzamy. Chciałbym Cię jeszcze dopytać czy po wylogowaniu z konta, nadal mogłeś dodawać przedmioty (i zmieniać ich liczbę) do koszyka, jako niezalogowany?

**Comment by Lukasz-Zurek** [comment]
@Smerf90 Ok, dziękuję. Sprawdzamy dalej.

**Comment by bartoszslx** [comment]
Witam, 

Mam ten sam problem. Czyli nie można dodawać produktów do koszyka. Z tego co zauważyłem problem występuje w zależności z jakiego Internetu korzystamy. Na mobilnym plus działa, na orange światłowód działa, na światłowodzie od lokalnego dostawcy nie działa(testowane w dwóch różnych lokalizacjach). Normalne allegro.pl działa bez problemu.

**Comment by Lukasz-Zurek** [comment]
@Smerf90 @bartoszslx W ciągu ostatnich kilku dni nie odnotowaliśmy po naszej stronie 503, więc wszystko wskazuje na to, że przyczyna leży po stronie operatora sieci, który blokuje komunikację z usługą odpowiedzialną za zarządzanie koszykiem na sandboxie.

**Comment by bartoszslx** [comment]
@Lukasz-Zurek

Przed chwilą w przeglądarce Edge udało mi się dodać produkt do koszyka będąc niezalogowanym jak i zalogowanym. W trybie incognito jest problem.

W moim przypadku mam błąd 429 Too Many Requests.

![image](https://github.com/allegro/allegro-api/assets/52525554/7d197ac7-5607-47aa-803a-ea68644b5f23)

Po kilku próbach otrzymałem komunikat: 
Jeśli coś nie działa prawidłowo wyślij nam wiadomość.
ID: a7dc66b5-732e-bfd6-66f4-be8d1c9746aa

Po rozwiązaniu captchy dostałem kolejny komunikat.
Zostałeś zablokowany.

Dlaczego zostałeś zablokowany? Coś w zachowaniu twojej przeglądarki zwróciło naszą uwagę. Powody mogą być różne:
 przeglądasz strony i klikasz dużo szybciej niż przeciętny człowiek
 coś uniemożliwia działanie Javascript na twoim komputerze
 w tej samej sieci (IP 31.42.x.x) operuje robot
Jeśli coś nie działa prawidłowo wyślij nam wiadomość.

ID: 29454c83-7f9e-527d-234a-75a8a812f915

Teraz ponownie mam błąd 503 w trybie incognito. W normalnym trybie wszystko działa ok.

Zrobiłem dodatkowe testy na czystym firefox, który nie ma żadnych dodatkowych wtyczek i dla zasobu https://edge.allegro.pl.allegrosandbox.pl/carts/changeQuantityCommand tak samo dostaje 429.

**Comment by Smerf90** [comment]
U mnie już wszystko działa. Nic nie zrobiłem, coś się odblokowało 🤷‍♂️

Zostawiam wątek otwarty gdyby Bartosz miał jeszcze problemy i chciał go kontynuować.

**Comment by Lukasz-Zurek** [comment]
@Smerf90 Dziękuję za informację. Cieszę się, że problem zażegnany :) 

@bartoszslx Czy problem nadal występuje? Czy próbowałeś przełączać się na inną sieć?
