### ISSUE TITLE
Captcha dla E2E testów

### ISSUE THREAD

**Issue by PTQuality** [allegro/allegro-api#9111]
Cześć Wam,
mam pytanie. Wertowałem waszą dokumentację, ale nie znalazłem odpowiedzi na moje pytania.

Chciałbym stworzyć projekt oparty o Waszego sandboxa, dla moich testów E2E (playwright) na warstwie GUI + API. Nie znalazłem wzmianki w regulaminie czy jest to dozwolone. 

Napotkałem, jednak problem w postaci captchy, czy jest możliwość jej dezaktywacji/obejścia? Moje testy, nie mogą się nawet zalogować na konto ze względu na nią. Nawet, jeśli rozwiązałbym ją manualnie (czego bym wolał uniknąć) to i tak otrzymuje komunikat, że zostałem zablokowany.

You have been blocked.

Why this blocking? Something about the behaviour of the browser has caught our attention.

There are various possible explanations for this:
 you are browsing and clicking at a speed much faster than expected of a human being
 something is preventing Javascript from working on your computer
 there is a robot on the same network (IP - X) as you
If something does not work please let us know.

ID: 6c67749c-33f1-ed2a-f8b5-04ea074eafa6

[EDIT]
Zrobiłem konwersję na konto biznesowe, ale dalej nie mogę zarejestrować aplikacji w Sandboxie, widzę, że mam weryfikację dla rachunku bankowego (opłaciłem waszym symulatorem) oraz weryfikację danych firmy. 
Client: secretLogin

**Comment by Lukasz-Zurek** [comment]
Kwestię dotyczącą blokady przekazałem dalej do weryfikacji. Wkrótce wrócę z informacją.

Jeśli natomiast chodzi o wskazane konto na sandboxie - aktywowałem je.

**Comment by PTQuality** [comment]
Dzięki Łukasz za aktywację, udało mi się dostać do API. Pozostawiam, więc pytanie czy jest możliwość albo widnieje informacja w dokumentacji, jak się zautoryzować, aby aplikacja mogła wizualnie działać i nie dostawać captchy :)

**Comment by Lukasz-Zurek** [comment]
@PTQuality Co do samego sandboxa - nie mam dobrych wieści - nie możesz zautomatyzować procesów po stronie GUI - nasz serwis będzie to zawsze blokował i niestety nie możesz tego obejść. Korzystaj proszę z samego API, oczywiście zgodnie z obowiązującymi u nas limitami.

**Comment by PTQuality** [comment]
Łukaszu smutne wieści niesiesz dla mnie, ale przynajmniej sytuacja jest jasna i zrozumiała. Dzięki wielkie za informację zwrotną, udanego tygodnia/weekendu
