### ISSUE TITLE
CheckoutFormNotFoundException error

### ISSUE THREAD

**Issue by bandee2** [allegro/allegro-api#9119]
Hi,

Can you please check why I get this error message for a valid order ID?

`{"errors":[{"code":"CheckoutFormNotFoundException","message":"Checkout form C277E5E0-1CC4-11EF-9593-DBB5C9D000D0 not found","details":null,"path":"/order/checkout-forms/C277E5E0-1CC4-11EF-9593-DBB5C9D000D0","userMessage":"Checkout form C277E5E0-1CC4-11EF-9593-DBB5C9D000D0 not found"}]}`

trace-id: c91c302ca65da2e3

Thank you in advance!

**Comment by Lukasz-Zurek** [comment]
@bandee2 Please provide it in this form: c277e5e0-1cc4-11ef-9593-dbb5c9d000d0. Then you should retrieve your order details.

**Comment by bandee2** [comment]
@Lukasz-Zurek I've sent the order ID in the request already with lowercase, the response capitalize it.

**Comment by Lukasz-Zurek** [comment]
@bandee2 I have checked our logs and I see that we did receive `/order/checkout-forms/C277E5E0-1CC4-11EF-9593-DBB5C9D000D0` request from your side.

**Comment by bandee2** [comment]
@Lukasz-Zurek Indeed, I looked into the code and there was a line that uppercased the input value. Now it's working, thank you!
