### ISSUE TITLE
Sandbox - order/events nie zwraca nowych danych?

### ISSUE THREAD

**Issue by xemix** [allegro/allegro-api#912]
Cześć, 
dziś w sandbox dokonałem zakupu - aukcja, która istnieje już od jakiegoś czasu, 'do wyczerpania zapasów'.
Jednak endpoint `order/events` nie zwraca dzisiejszego zakupu, zwraca jedynie 'stare' 25 zdarzeń, które testowałem jakiś czas temu. Endpoint `order/event-stats` zwraca:
```
object(stdClass)#12 (1) {
  ["latestEvent"]=>
  object(stdClass)#11 (2) {
    ["id"]=>
    string(16) "1539703946470987"
    ["occurredAt"]=>
    string(24) "2018-10-16T15:32:13.285Z"
  }
}
```

Endpoint `order/events` zwraca jedynie 25 zdarzeń z testów sprzed miesiąca.
Czy problem występuje tylko u mnie? Co do mojego kodu - nie widzę nic co by mogło powodować problem, ponieważ jest to zwykłe zapytanie do Endpointa, z Access-token'em.

**Comment by PawelTaberski** [comment]
Pamiętaj, że przy pomocy GET na zasobie /order/events  pobierzesz tylko zdarzenia z ostatnich 60 dni. Czy sprawdzałeś ostatnie zdarzenie jakie otrzymujesz bo w responsie są one sortowane od najstarszego do najnowszego na podstawie pola occurredAt.
Jeśli nie widzisz tam najnowszego zdarzenia to podeślij nam proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełne cURL-e z tych metod, responsy i trace-id tych zadań. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 912 na GitHub-ie.
Nawiasem polecam nasz poradnik na temat zarządzania zamówieniami, który jest dostępny[ tutaj](https://developer.allegro.pl/orders/).

**Comment by xemix** [comment]
Tak, ale order/event-stats powinien zwrócić ID oraz datę najnowszego zdarzenia, prawda? A zwraca to co podałem w pierwszym poście, ignorując całkowicie dzisiejsze zamówienia. 
Wiadomość została wysłana za pomocą formularza kontaktowego.

**Comment by PawelTaberski** [comment]
Rozumiem, czyli wychodzi że musi być jakiś problem z tą metodą. Jak tylko otrzymam dane zapoznam się z nimi i dam znać.

**Comment by PawelTaberski** [comment]
Z tego co widzę w danych jakie podesłałeś nie ma nowszego zdarzenia niż te z końcówką ...775 i jeśli wywołasz GET na zasobie /order/events?from=...775 to dostaniesz pustą tablicę bo nie ma nowszego zdarzenia niż takie, tzn nie ma kolejnego. Jeśli chciałbyś pobrać te z końcówka 775 to musiałbyś podać from od poprzedzającego.

**Comment by xemix** [comment]
Chodzi o to, że metoda zwraca mi zamówienia z października. W panelu zamówień Allegro Sandbox mam ostatnią transakcję: 19 lis 2018, 15:54, zaś metoda `order/events` i `order/event-stats` w ogóle nie zwraca tych danych w dziennikach. `order/events` pobieram także z znacznikiem 0 (bez parametru from) - zwraca 32 zdarzenia sprzed miesiąca, nowych nie zwraca.

**Comment by xemix** [comment]
Przed chwilą dokonałem kolejnego zakupu - w panelu allegro sandbox widzę zamówienia (wszystko jest OK), maile otrzymałem - metoda dalej nie zwraca nowych danych.

**Comment by PawelTaberski** [comment]
Sprawdziłem u siebie na nowym zamówieniu i dane spływają poprawnie, a próbowałeś wykonać requesta bez żadnych parametrów tzn. bez from i limit? Czy efekt ciągle masz taki sam? Jakie zamówienie dostajesz po wywołaniu zasobu /order/event-stats poprzednie tzn starsze od najnowszego?
