### ISSUE TITLE
Kilka aplikacji czy jedna aplikacja?

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#9123]
Mam kilka integracji do zarządzania aukcjami każda z nich działa tak samo tylko, że pobiera dane z innego źródła, każda używa tego samego ClientId i ClientSecret i tak sobie myślę, czy to jest dobre rozwiązanie, czy stworzenie kilku aplikacji o innych nazwach jest bardziej wydajne? Pytam o to szczególnie ze względu na limity, limity chyba są na aplikacje a nie na IP? 

Czy to dobry pomysł stworzyć osobną aplikacje z innym ClientId i ClientSecret na każdą integracje aby mogła przetwarzać więcej aukcji na minute?

Jedną zaletą jest to, że klient może sobie połączyć konta tylko raz, i włączyć dowolną integracje bez ponownej autoryzacji, ale jeśli każda aplikacja ma swój własny limit trochę martwi mnie wydajność.

Jaka jest oficjalna rekomendacja Allegro w tej sprawie?

**Comment by Lukasz-Zurek** [comment]
Zgadza się, limit jest na aplikację/ClientId i wynosi 9000 zapytań na minutę. Opisujemy to również [tutaj](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#ograniczenie-liczby-zapytan-limity). Nie odnotowaliśmy jednak utrudnień w tym zakresie, więc wydajność nie wydaje się tutaj być problemem.

Przede wszystkim jeśli tworzysz więcej niż jedną aplikację, dopilnuj, aby pełniły one różne funkcje. Co prawda na jednym koncie możesz mieć maksymalnie 5 zarejestrowanych aplikacji, jeśli jednak miałyby one obejmować te same procesy, zalecam utworzenie jednej aplikacji, kierując się zasadą - jedna aplikacja = jeden Client ID.

**Comment by bugproof** [comment]
A czy np. Sello ma stworzoną tylko 1 aplikację? Mają dość dużo użytkowników czy mają jakiś własny limit ustalony przez Allegro?

**Comment by bugproof** [comment]
Dlatego w moim rozwiązaniu staram się zoptymalizować wszystko jak najlepiej się da, między innymi mam kopię wszystkich ofert u siebie lokalnie zamiast za każdym razem pobierać je z allegro i synchronizuje je pollując zdarzenia i zapisując ostatnie widziane zdarzenie w bazie (idealniejsze byłyby webhooki). Też nie przetwarzam wszystkiego na raz tylko mam kolejkę która żyje sobie na osobnym wątku i przetwarza sobie różne zadania czekając aż zakończy się poprzedni task. Dość długo zajęło mi zaplanowanie takiego rozwiązania bo też dokumentacja allegro nie posiada żadnej strony z "best practices" co myślę, że ułatwiło by tworzenie aplikacji wielu osobom.

Pytanie pojawiło się stąd, że mam np 10 połączonych kont które sprzedają 50000 przedmiotów jakiegoś dostawcy X i 50000 przedmiotów dostawcy Y i każdy z tych dostawców ma jakieś swoje API/ lub plik który aktualizuje się co np. godzinę. Myślę, że osobne Client ID mogłoby tu zrobić dużą różnicę chociażby na możliwość aktualizowania aukcji równolegle (in parallel) mając swoją chociażby własną kolejkę/wątek/proces.
