### ISSUE TITLE
Wrong number of sold items at /sale/offers

### ISSUE THREAD

**Issue by maxprihodko8** [allegro/allegro-api#913]
When searching for the info of the offers at the test REST API we get the wrong number of items available. From the admin panel the number is wrong too, only at the auction page it is right. For example for the auction 6206028566 at the test Allegro store we have 15 all items, at the product page 13 available to buy (other 2 were bought), but when we go to the admin page we see all 15 available and using the REST API /sale/offers we get the same 15 available and 0 sold. The trace-id of the response is 6206028566. Also the /offers/listing does not have this problem (shows 13 available), but don't have current status of the offer. 

Also offers could not be filtered by the list of ids at the REST API, we would like to get this functionality. 
Also categories full list could not be taken, we would like to take all categories with one query.

**Comment by PawelTaberski** [comment]
Thank you for information, we will check this. Please send us by [contact form](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619)
a cURL and response with wrong data. Write that the information is for the ticket number 913.

**Comment by PawelTaberski** [comment]
We solve this problem, but the data will be updated from 6 days back and from now will already be correctly calculated.

**Comment by maxprihodko8** [comment]
Thank you. The problem does not exists anymore.
