### ISSUE TITLE
Błąd 403 Forbidden przy obsłudze wiadomości

### ISSUE THREAD

**Issue by Jankes02** [allegro/allegro-api#9134]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy próbie wysłania wiadomości (POST https://api.allegro.pl/messaging/messages) otrzymuję błąd 403 Forbidden. Analogiczny błąd pojawia się przy próbie otrzymania wszystkich wątków wiadomości użytkownika (GET https://api.allegro.pl/messaging/threads). Wnioskuję zatem, że problem dotyczy wszystkich endpointów Message Center. W aplikacji zarejestrowanej na allegro developer apps jest zaznaczone allegro:api:messaging.

Do żądania dołączyłem nagłówki:
"Authorization": "Bearer TOKEN"
"Accept": "application/vnd.allegro.public.v1+json"
"Content-Type": "application/vnd.allegro.public.v1+json"

Body żądania:
{
&nbsp;&nbsp;&nbsp;&nbsp;    "Recipient": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        "Login": "login"
&nbsp;&nbsp;&nbsp;&nbsp;    },
&nbsp;&nbsp;&nbsp;&nbsp;    "Text": "wiadomosc"
}

Body odpowiedzi:
{
&nbsp;&nbsp;&nbsp;&nbsp;    "errors": [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            "code": "AccessDenied",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            "message": "Access is denied",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            "details": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            "path": null,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            "userMessage": "No access to the specified resource."
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        }
&nbsp;&nbsp;&nbsp;&nbsp;    ]
}

**Comment by MartaNowaczyk** [comment]
Sprawdź czy w tokenie masz już uwzględniony ten scope.

**Comment by Jankes02** [comment]
Dziękuję za pomoc, nie wiedziałem, że po aktualizacji uprawnień trzeba jeszcze raz wygenerować kod autoryzacji
