### ISSUE TITLE
https://upload.allegro.pl/sale/images kilku użytkowników jedno zdjęcie

### ISSUE THREAD

**Issue by netfarma** [allegro/allegro-api#914]
Witam,
Czy mogę wykorzystać w kilku różnych aukcjach wystawionych przez różnych użytkowników zdjęcia wgrane przez jednego z nich?

Obecnie technicznie jest to możliwe, ale zastanawiam się, czy tak powinno to działać?
Przecież zdjęcia przesyłane są z uprawnieniami użytkownika A a użytkownik B może je wykorzystać w swojej aukcji.
Jeśli jest to działanie celowe, to chciałbym mieć tą pewność, bo chcę w odpowiedni sposób przygotować swoją lokalną bazę.

Jeśli to jest tylko niedopatrzenie to też proszę o informacę, bo będę w takim razie przesyłał dla każdego użytkownika osobne zdjęcia dotyczące tego samego produktu.

Pozdrawiam

**Comment by PawelTaberski** [comment]
Obecnie rzeczywiście możesz korzystać ze zdjęć które wystawiłeś na jednym koncie na wielu, jednakże nie zalecamy takich rozwiązań. Lepiej używać danych zdjęć na jednym koncie.

**Comment by deneb-k** [comment]
No dopiero co nie było żadnego "nie zalecamy". https://github.com/allegro/allegro-api/issues/741

Weź tu człowieku pisz integrację z tym API.

**Comment by PawelTaberski** [comment]
@deneb-k  Wszystko się zgadza, tak jak w wątku który podesłałeś takie rozwiązanie działa. Ale nie zalecam bo jeśli obsługujesz wielu sprzedawców, to może się przytrafić, że podepniesz komuś zdjęcie innego sprzedawcy. Dlatego bezpieczniej na jednym koncie mieć zdjęcia od jednego konta.

**Comment by deneb-k** [comment]
Czyli uściślając. Nie zalecasz tego tylko w trosce o nasze umiejętności programistyczne. Nie ma w planach zablokowania takiego działania, tak?

**Comment by PawelTaberski** [comment]
Na dzień dzisiejszy nie słyszałem o takich planach. I zalecam ze względów bezpieczeństwa danych. Nie wątpię w Twoje umiejętności :-)
