### ISSUE TITLE
Stawka VAT dla metody dostawy

### ISSUE THREAD

**Issue by wuj3k** [allegro/allegro-api#9141]
Witam,

Czy mogę poprosić o informacje, w jaki sposób określić stawkę VAT dla metody dostawy która została wybrana przez kupującego w ofercie? Bo w end point'cie z szczegółami oferty jest tylko informacja o cenie dostawy i waluty.

Nie mogłem znaleść tej informacji ani w dokumentacji api ani tutaj na forum.

Z góry dziękuje.

**Comment by MartaNowaczyk** [comment]
Witam, zgadza się, nie udostępniamy takich informacji w ofercie. Niestety w kwestiach podatkowych nie możemy pomóc. Prowadzimy tu wsparcie tylko w zakresie API Allegro.

**Comment by wuj3k** [comment]
Moje pytanie właśnie dotyczyło API. Ale może jeszcze rozwinę swoje pytanie: 

Ogólnie informacje o produkcie z zamówienia danego użytkownika, w swojej aplikacji pobieram poprzez end point - 
```https://api.{environment}/order/checkout-forms/{id}``` i tam jest np. stawka VAT dla kupionego produktu. 
Pobieram stamtąd też cenę wysyłki, ale chciałbym też pozyskać informacje o stawce VAT jaka zostałą zastosowana na tą konkretną wysyłke. 

I moje pytanie brzmiało, w jakiś sposób można ją pobrać, np. poprzez jakiś inny zasób w Państwa API :)

**Comment by MartaNowaczyk** [comment]
Nie mamy takiej informacji w API.

**Comment by MartaNowaczyk** [comment]
Nie ma możliwości przez API określić jaki to VAT dla danej przesyłki. To już są kwestie podatkowe i to niestety nie mój temat, żebym mogła z czystym sumieniem polecić rozwiązanie.

**Comment by wuj3k** [comment]
ok, dziękuje za informacje :)
