### ISSUE TITLE
Zestaw produktów API - Dodać  kolejny. 

### ISSUE THREAD

**Issue by jomardyan** [allegro/allegro-api#9144]
Dzień dobry, jak mogę przez API dodać kolejny produkt do oferty?

Noe mogę znaleźć takiego requestu.

**Comment by jezewskiBNetrox** [comment]
@jomardyan Co masz na myśli przez "dodanie kolejnego produktu"? Zwiększenie ilości oferowanych sztuk?

**Comment by jomardyan** [comment]
> @jomardyan Co masz na myśli przez "dodanie kolejnego produktu"? Zwiększenie ilości oferowanych sztuk?

Zestaw Allegro 2(lub wiele) różnych produktów. 

![image](https://github.com/allegro/allegro-api/assets/18527406/c78a680a-0bd7-4f6c-89ca-1ee52e33a651)

**Comment by jomardyan** [comment]
![image](https://github.com/allegro/allegro-api/assets/18527406/c6d3c10a-61c6-48ea-bad9-fe95f6392681)

**Comment by Lukasz-Zurek** [comment]
@jomardyan Zestaw produktów utworzysz za pomocą: [POST /sale/product-offers](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA).

[Tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-utworzyc-zestaw-produktowy) znajdziesz więcej informacji.

**Comment by jomardyan** [comment]
@Lukasz-Zurek  moje pytanie brzmi, jak edytować istniejący produkt i dodać, a nie dodawać go od początku. Czy istnieje takiej możliwości ?

**Comment by Lukasz-Zurek** [comment]
@jomardyan Tak, istnieje taka możliwość. Zrobisz to edytując ofertę za pomocą [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers), dokładając kolejny produkt w obiekcie **productSet**.
