### ISSUE TITLE
What exactly event id is the last in the list of offer-events?

### ISSUE THREAD

**Issue by oleksandrLebedenkoovoko** [allegro/allegro-api#9153]
The endpoint: GET /sale/offer-events (example: `https://api.allegro.pl/sale/offer-events?from=MTU2Mzg2NTM5MTU2Mzg0Ng`)

If I want to see all new events, I need to use `from` query parameter.
It is not clear which event is the latest to use in the next query.
The last one is the last in the list from the previous response? Or the last one from the 'occurredAt' field perspective?
Because sometimes this date doesn't correlate with a sequence in the list. Could you please explicitly tell me what I should rely on?

https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#event-journal-concerning-changes-in-seller-s-offers

**Comment by MartaNowaczyk** [comment]
GET /sale/offer-events is an event journal that returns information about changes from the last 24 hours. The results are returned according to which event occurred - from oldest to newest. In the query you should indicate the id of the event that is last in the list.
