### ISSUE TITLE
Brak dostępu do API Allegro

### ISSUE THREAD

**Issue by pawelkasza** [allegro/allegro-api#9155]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ X] z logowaniem lub autoryzacją / with login or authorization
 - [ X] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Jestem na https://developer.allegro.pl dostęp do API / Zarządzaj API. Wyskakuje mi komunikat aktywuj konto.
Konto jest aktywne bo to nie jest nowe konto. Mam tak na wszystkich kontach: reklamowy-sklep, partyshop, znaki-bhp

**Comment by MartaNowaczyk** [comment]
Na pewno nie jest to cały komunikat, cały brzmi:
"Nie możesz zarejestrować nowej aplikacji. Aktywuj konto oraz włącz dwustopniowe logowanie." 
Jeśli konta są aktywne, to pewnie brakuje Ci dwustopniowego logowania.

**Comment by SylwesterXXX** [comment]
Proszę aktywować konto "romertest", niby wszystko zrobione poprawnie , ale nie aktywowało się samoczynnie

**Comment by pawelkasza** [comment]
Ogarnięte dzięki
