### ISSUE TITLE
Pobieranie danych do faktury /order/checkout-forms

### ISSUE THREAD

**Issue by simple-studio** [allegro/allegro-api#916]
Witam,

Chciałbym zapytać dlaczego pobierając dane klienta poprzez "/order/checkout-forms" nie są zwracanie informacje o adresie zamieszkania? Jedyne dane jakie można pobrać to adres dostawy, jednak bardzo często adresy różnią się od siebie, natomiast wystawiając fakturę potrzebny jest adres zamieszkania klienta. Nie mam na myśli klienta który chciałby otrzymać fakturę na firmę. Czy istnieje inna funkcja do pobierania owego adresu?

**Comment by PawelTaberski** [comment]
Przez REST API nie ma możliwości pobrania innego adresu jak tylko ten, który user podał w zamówieniu, bądź przy fakturze.

**Comment by PawelTaberski** [comment]
Obecnie nie planujemy wdrożenia takiej funkcjonalności.
