### ISSUE TITLE
sandbox bank account verification

### ISSUE THREAD

**Issue by Pack4you** [allegro/allegro-api#9166]
Could you please help me with bank account verification on my sandbox account?

Login: pack4you_dev

Thank you.

**Comment by MaciejFrackowiak** [comment]
Please, make a bank transfer (by payment simulator) - you can do it in the [Account details](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) tab.

**Comment by MarkSoftSlovakia** [comment]
I did, but still not verified "We are waiting for confirmation of the bank account by the payment verifier"

**Comment by Pack4you** [comment]
I did, but still not verified "We are waiting for confirmation of the bank account by the payment verifier"

**Comment by Pack4you** [comment]
Great - Thank you.
