### ISSUE TITLE
Próba autoryzacji w sandbox

### ISSUE THREAD

**Issue by sojuz88** [allegro/allegro-api#917]
Witam,

Przy próbie autoryzacji klienta: 44089084

Otrzymuje komunikat:  Unauthorized - Full authentication is required to access this resource

Aplikacja ma typ DEVICE.

Po pobraniu kodu i aktywowaniu go na stronie próba pobrania tokena kończy się powyższym komunikatem

**Comment by PawelTaberski** [comment]
Czy w nagłówku Authorization na pewno podałeś zgodnie z [nasza dokumentacją](https://developer.allegro.pl/auth/#DeviceFlow):
"autoryzację typu Basic, z zawartością w formie client_id:client_secret (dane te otrzymałeś przy rejestracji aplikacji) zakodowane przy pomocy Base64. Pamiętaj aby zakodować całość danych client_id:client_secret wraz ze znakiem “:” pomiędzy wartościami."

**Comment by sojuz88** [comment]
Jeżeli client_id to to samo co klucz web api to tak właśnie zrobiłem.

Kwestia która mnie zastanawia - czy w post powinienem wysłać to w taki sposób:
{
grant-type: device_code,
device_code: [device_code]
}

Gdzie kod "device_code" otrzymuje z metody https://allegro.pl/auth/oauth/device

**Comment by sojuz88** [comment]
Czyli powinno być tak w post data:
{
'grant-type': 'urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code',
'device_code': [device_code]
}
Takie rozwiązanie także zwraca błąd:
Unauthorized - Full authentication is required to access this resource

Jest jeszcze taki szczegół, że strona wpisywania kodu jest na adresie sandbox'a, ale po wpisaniu strona z podziękowaniem wyskakuje już z normalnego url'a allegro

**Comment by PawelTaberski** [comment]
Podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) trace-id tego zadania sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 917 na GitHub-ie.

**Comment by sojuz88** [comment]
Faktycznie jest dwa razy Authorization.
Macie tak w przykładzie: https://developer.allegro.pl/auth/#userDeviceFlow
Podpunkt 4b

Teraz jest inny komunikat: {"error":"Unauthorized","error_description":"Bad credentials"}

Gdzie parametry POST wyglądają tak:
`https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=i2oSV4aEHqwH8C82MrpkTKl8j11PsQDY`

**Comment by PawelTaberski** [comment]
Rzeczywiście :-) już poprawiłem.
Odnośnie Twojego requesta wskazuje że masz jakiś błąd w danych client id albo secret bądź w kodowaniu. Jesteś pewny, że podajesz prawidłowe dane i zakodowałeś całość wraz z dwukropkiem po środku?

**Comment by sojuz88** [comment]
Problem był w tym, że token próbowałem uzyskać na normalnym adresie, a device_code dostawałem z sandboxa. Już działa. Dziękuje za pomoc!
