### ISSUE TITLE
Proszę o zweryfikowanie konta sprzedawcy sandbox

### ISSUE THREAD

**Issue by Morph21** [allegro/allegro-api#9170]
Dzień dobry,

Prosiłbym o zatwierdzenie weryfikacji dla konta sandbox widocznego poniżej

sellerId=105893409

Dane zostały podane z generatora więc nie powinny być realne

**Comment by MartaNowaczyk** [comment]
Dzień dobry, aktywowałam podane konto.

**Comment by SylwesterXXX** [comment]
Proszę aktywować konto "romertest", niby wszystko zrobione poprawnie , ale nie aktywowało się samoczynnie

**Comment by Morph21** [comment]
Dziękuję za pomoc
