### ISSUE TITLE
Sprzedawcy połączeni do katalogu produktów.

### ISSUE THREAD

**Issue by ralph9001** [allegro/allegro-api#9181]
Czy jest w api zasób, który pozwoliłby monitorować oferty pod kątem sprzedawców, którzy się podłączyli do katalogu?

Chodzi o sytuację gdzie sprzedawca oferuje produkt swojej marki a następnie inny sprzedawca się do niego podpina z innym produktem.

**Comment by MartaNowaczyk** [comment]
Nie mamy takiego zasobu.
