### ISSUE TITLE
Próba dodania sandboxowego konta shipx kończy się błędem

### ISSUE THREAD

**Issue by WGRINGO** [allegro/allegro-api#9186]
Występuje problem: 
 - [X] ze środowiskiem testowym / with the test environment

Witam.
Próbuję dodać nową umowę własną na sandboxie. Wchodzę w zamówienia - ustawienia - "umowy własne - wysyłam z allegro" w allegro-zamówienia. Podaję token otrzymany z shipx z sandboxa i próba założenia metody własnej kończy się nieokreślonym błędem "an error has occured".
![image](https://github.com/allegro/allegro-api/assets/46341708/340dd858-bd4c-4057-9a19-ef969b38010f)

**Comment by MaciejFrackowiak** [comment]
Potwierdzam problem - działamy by przywrócić właściwe funkcjonowanie usługi.

**Comment by MaciejFrackowiak** [comment]
Problem wyeliminowany, przepraszam za utrudnienia.

**Comment by WGRINGO** [comment]
Spoko - teraz działa
