### ISSUE TITLE
Znaki specjalne w tytule ile zabierają miejsca ?

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#919]
Dzień dobry,
macie tabelę gdzieś ile miejsca zabierają znaki specjalne np. & z tytułu allegro ?

**Comment by PawelTaberski** [comment]
Nie mamy nigdzie spisanej takiej tabeli, jednakże możliwe znaki w tytułach ofert w webAPI znajdziesz w [tabeli ASCII](https://www.cs.cmu.edu/~pattis/15-1XX/common/handouts/ascii.html) + polskie znaki diaktryczne.

**Comment by centrumelektroniki** [comment]
nie pomaga nam to. 
dam przykład tytułu:
PSI PATROL FLIP & FLY POJAZD FIGURKA RUBBLE
wg nas są to 43 znaki, Wy liczycie 47.

inaczej liczycie & tylko dlaczego ? i gdzie znajdę te wszystkie wyjątki ?

**Comment by PawelTaberski** [comment]
Znaki specjalne tego typu są zapisywane jako encje czyli np & jako &amp; czyli 5 znaków. Nie mamy nigdzie tego spisane, ale np [tu jest](https://dev.w3.org/html5/html-author/charref) wymienione różne encjonowanie znaków.

**Comment by PawelTaberski** [comment]
@centrumelektroniki Dodatkowo jeśli nie jesteś pewny ile znaków zabiera jaki znak specjalny, a nie chce Tobie się szukać, to zawsze możesz wejść przez moje allegro do formularza wystawiania i od razu Tobie policzy :-)

**Comment by centrumelektroniki** [comment]
chcemy automatycznie wystawiać oferty przez RESTA

**Comment by PawelTaberski** [comment]
@centrumelektroniki Rozumiem to wtedy tak jak powiedziałem znaki specjalne są encjowane czyli zajmują tyle znaków co dana encja.

**Comment by centrumelektroniki** [comment]
allegro każdy znak spoza najbardziej podstawowego zakresu (małe i duże litery oraz cyfry) liczy jako encje? czy tylko niektóre? jeśli niektóre - to dokładnie które znaki są liczone przez allegro po zakodowaniu do encji? i jeszcze jak dla pewności jest liczone kodowanie encji? są to encje dziesiętne, szesnastkowe, symboliczne, czy może jeszcze jakoś inaczej?

**Comment by PawelTaberski** [comment]
@centrumelektroniki Kwestię tytułów, opisaliśmy w [naszym poradniku](https://developer.allegro.pl/sale/#step-4-title), tam również znajdziesz stosowny przykład.

**Comment by centrumelektroniki** [comment]
Panie Pawle, które znaki specjalne liczycie jako encje i w jakim kodowaniu ? 
Dziękuję za link, jednak nie udziela odpowiedzi na nasze pytanie.

**Comment by PawelTaberski** [comment]
Dopytałem jeszcze odpowiedni zespół i otrzymałem odpowiedź że obecnie stosujemy 4 encje z poniższym kodowaniem:
    '&': '&amp;',
    '"': '&quot;',
    '<': '&lt;',
    '>': '&gt;'
reszta (polskie znaki, reszta znaków specjalnych) nie powinna mieć żadnego wpływu na długość tytułu
