### ISSUE TITLE
Zdjęcia

### ISSUE THREAD

**Issue by potejtooo** [allegro/allegro-api#9194]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Problem z zasobem https://api.allegro.pl/sale/images
trace-id: 84d95058a032a82, b2b7cd3a44d274a7
W odpowiedzi dostaje link do zdjęcia który nie działa, np. 
https://a.allegroimg.com/original/111358/0259da204f0da9f1708616132828
https://a.allegroimg.com/original/1154e0/b6adc7e84054b345caaea3a2d06f
Object not found.

**Comment by dol1234** [comment]
Problem pojawił się chyba dzisiaj rano..
Zdjęcia pojawiają się pod zasobem z opóźnieniem lub wcale (Object not found)

**Comment by MartaNowaczyk** [comment]
To problem po naszej stronie. Dziękuję za zgłoszenia, działamy już w temacie. W sumie powinno się już poprawiać. Przepraszamy za niedogodności.
