### ISSUE TITLE
[sandbox] doShowItemInfoExt zwraca niepoprawne kwoty wysyłek

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#920]
Przemnożone są one przez 100, nie ma przecinków.

Na aukcji cena 8,99, API zwraca `<ns1:postageAmount>899</ns1:postageAmount>`.
Sprawdzone na kilku aukcjach, efekt ten sam.

**Comment by Onixarts** [comment]
Poszło mailowo.

**Comment by PawelTaberski** [comment]
@Onixarts 
Dane dotarły. Sprawdziłem na swoich ofertach i jest kropka, dziwne.
Sprawę zgłosiłem do głębszej analizy do zespołu odpowiedzialnego za tą funkcjonalność.
Proszę o cierpliwość.
