### ISSUE TITLE
WZA UPS - dodatkowa etykieta 

### ISSUE THREAD

**Issue by matcapi** [allegro/allegro-api#9207]
Dzień dobry,

Dostałem informację, że dla przesyłek UPS istnieją dwa szablony etykiet do pobrania. Według przekazanych informacji, gdy wykonam request do ```GET /shipment-management/shipments/{shipmentId}```, to w ```additionalProperties``` powinien znajdować się numer wewnętrzny paczki UPS.

Dla przesyłki ```c48199e7-a20c-40ce-a1b0-8c071f22d1f0``` na środowisku sandbox, pole ```additionalProperties``` jest puste.
Przesyłka została utworzona za pomocą starego zasobu ```/parcel-management``` - czy to ma znaczenie?

Gdy już uzyskam ów numer, to co potrzebuję zrobić by pobrać alternatywną etykietę?

**Comment by MartaNowaczyk** [comment]
Tak, `additionalProperties` zwracamy tylko dla [GET /shipment-management/shipments/{shipmentId}](https://developer.allegro.pl/documentation/#operation/getShipmentDetails).

**Comment by matcapi** [comment]
@MartaNowaczyk dziękuję za odpowiedź. Rozumiem, że ```additionalProperties``` jest zwracane tylko w [GET /shipment-management/shipments/{shipmentId}](https://developer.allegro.pl/documentation/#operation/getShipmentDetails).

Pozostaję jednak bez odpowiedzi na dwa pytania:

1. Na środowisku sandbox, dla przesyłki ```c48199e7-a20c-40ce-a1b0-8c071f22d1f0``` (WZA Kurier UPS), endpoint [GET /shipment-management/shipments/{shipmentId}](https://developer.allegro.pl/documentation/#operation/getShipmentDetails) zwraca puste ```additionalProperties```. Czy przyczyną takiego zachowania jest fakt, że przesyłka została utworzona za pomocą ```/parcel-management```?

2. Gdy uzyskam wartość z ```additionalProperties```, to co potrzebuję zrobić by pobrać alternatywną etykietę?

**Comment by MartaNowaczyk** [comment]
1. Powinno zwracać dla przesyłek np. Allegro One, które dostarcza UPS, podaj proszę trace-id dla tego przypadku - może nie użyłeś takiej metody dostawy.
2. W additionalProperties dostajesz tylko informację o oryginalnym numerze przesyłki zawartym w kodzie kreskowym etykiety np. dla Allegro One Box. Nie wygenerujesz alternatywnej etykiety.

**Comment by MartaNowaczyk** [comment]
Metoda, którą masz wybraną to "Allegro Kurier UPS", a dla tej metody nie ma innego numeru przesyłki jak UPSu, stąd brak danych dla `additionalProperties`.

**Comment by matcapi** [comment]
Dziękuję za wyjaśnienie.
