### ISSUE TITLE
Jak sprawdzić datę utworzenia zamówienia?

### ISSUE THREAD

**Issue by jurtomasz13** [allegro/allegro-api#9209]
Witam, w jaki sposób sprawdzić datę utworzenia zamówienia? Po pobraniu listy zamówień widzę pole updatedAt, które nie musi wskazywać na date utworzenia, a datę aktualizacji, są jeszcze lineItems w których jest pole boughtAt aczkolwiek też nie jestem tego pewien. Którego pola powinienem użyć aby mieć rzetelną datę utworzenia zamówienia?

**Comment by MartaNowaczyk** [comment]
Wspomniana przez ciebie data w "lineItems.boughtAt" to konkretna data zakupu oferty, czyli utworzenia zamówienia.

**Comment by jurtomasz13** [comment]
Dziękuję, zamykam.
