### ISSUE TITLE
[REST/WebAPI] Autoryzacja - ostatnie zmiany / niejasności / dziÓry ;-)

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#921]
Należy chyba pochwalić zespół z Poznania, że po ponad dwóch latach (!) od uruchomienia REST, zabrano się wreszcie za uporządkowanie spraw najważniejszych - czyli całego systemu autoryzacji, Bravo ! ;-)

Ale tak poważnie - co jest a czego nie ma, albo czego nie ma w dokumentacji, albo co nie do końca zgadza się z dokumentacją ? Po pierwsze potwierdzam, że w porównaniu do zeszłego tygodnia - pary token'ów niosą już poprawne czasy (daty) ich ważności, sekwencja kolejnych par tokenów zachowuje się logicznie (czyli z marszu są unieważniane poprzednie acc-token'y - niezależnie od tego czy akcja odnowienia jest przed czy po upływie 12 godzin). Aplikacje REST poprawnie wpadają do nowej zakładki każdego użytkownika końcowego, również do tejże zakładki samego autora/właściciela aplikacji. Nadal nie ma jednak informacji (kontroli w panelu API) dla właściciela aplikacji - ilu użytkowników powiązało swoje konta z daną aplikacją, jakie to konkretnie konta z Allegro, może daty pierwszej autoryzacji... A wracając do całego silnika autoryzacji - nie piszecie ani słowem na temat kolejnych autoryzacji TEGO SAMEGO użytkownika, a to działa przecież tak, że kolejne takie autoryzacje dodają kolejne "ścieżki" autoryzacji (bez jakiegokolwiek wpływu na inne autoryzacje tego samego user'a), nie podajecie czy są tu przewidziane jakieś limity ilościowe, kolejne kody 10-sekundowe lecą nawet przed upływem ważności poprzedniego kodu oraz jego poprawnej obsługi w cyklu autoryzacji. Kolejna sprawa - informacja w dokumentacji na temat wymogów autoryzacji, jest obecnie nieaktualna, podajecie taki format łącza:
https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=a21...6be&redirect_uri=http://exemplary.redirect.uri
Adres powrotu można podać niezgodny z zadeklarowanym dla danej aplikacji, można też w ogóle nie podawać adresu powrotu - proces autoryzacji przechodzi tak czy inaczej. Podobne nieścisłości pojawiają się przy konstrukcji samych zapytań (żądań) autoryzacji - można to wysłać w okrojonej formie i też działa, co ciekawe zadziała nawet z IP innego Host'a niż ten adres IP, dla którego nazwa DNS wynikająca z adresu powrotu dla aplikacji - znajduje się na liście adresów dla danej aplikacji (w panelu API). Mam tu już pewne przemyślenia na temat "bezpieczeństwa", ale więcej nie napiszę...

**Comment by PawelTaberski** [comment]
Jeszcze chciałbym doprecyzować kwestię redirecta, otóż w dokumentacji podajemy, że podanie redirect_uri jest wymagane w endpoincie /authorize jak i /token i jest to prawda.
Tylko w sytuacji, kiedy client ma zarejestrowane tylko jedno redirect_uri endpointy będą działały bez podania tej wartości. Nie rekomendujemy korzystania z tej opcji, gdyż działanie to może się zmienić.

**Comment by FromAnyHole** [comment]
Przyglądamy się sprawie...
Uważnie ;-)
