### ISSUE TITLE
zmiana ceny ofert, type INCREASE_PRICE

### ISSUE THREAD

**Issue by KamilKarpinski** [allegro/allegro-api#9219]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Przy próbie zmian ceny oferty z type "INCREASE_PRICE" zwracany jest błąd.

https://api.allegro.pl.allegrosandbox.pl/sale/offer-price-change-commands/2b232dff-da18-4200-9c2f-d3d201fa1a35

Przesyłam:

  {
       "modification":{
        "type":"INCREASE_PRICE",     
        "marketplaceId": "allegro-pl",  
        "price":{                 
            "amount":"1.00",     
            "currency":"PLN"
           }
        },
    "offerCriteria":[
        {
          "type":"CONTAINS_OFFERS",
          "offers":[              
           {
             "id":"7767258141"
           }
          ]
        }
     ]
  } 
  
  Odpowiedź:
  
  {
    "errors": [
        {
            "code": "VALIDATION_ERROR",
            "message": "PriceModificationDto validator error: type is not given or price, value and percentage conflict",
            "details": "Invalid value: PriceModificationDto{type=INCREASE_PRICE, marketplaceId='allegro-pl', price=PLN 1.00, value=null, percentage='null'}",
            "path": "modification",
            "userMessage": "PriceModificationDto validator error: type is not given or price, value and percentage conflict",
            "metadata": {}
        }
    ]
}

trace-id: 9cb8c27d0e9756cb

**Comment by MaciejFrackowiak** [comment]
Używasz niewłaściwej struktury - zamiast "price" powinno być "value".
