### ISSUE TITLE
/pricing/offer-fee-preview a "Prowizja od sprzedaży oferty wyróżnionej"

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#9221]
Oferta jest wyróżniona (trace-id: e199531d9d3c298). Sprawdzam /pricing/offer-fee-preview i dostaję tylko "Prowizję od sprzedaży" (trace-id: d000ce64ca466d8c): 

```
  "commissions": [
    {
      "name": "Prowizja od sprzedaży",
      "type": "commissionFee",
      "fee": {
        "amount": "3.86",
        "currency": "PLN"
      }
    }
  ]
```

Czy nie powinno być tam też "Prowizja od sprzedaży oferty wyróżnionej" (commisionFeatureFee)?

**Comment by MartaNowaczyk** [comment]
Nie widzę byś w zapytaniu podał w danych oferty informacje dotyczące promowania, stąd pewnie różnica.

**Comment by tomylee0** [comment]
Ano tak. Kiedyś wystarczyło pobrać ofertę i bezpośrednio dać ją do offer-fee-preview. Teraz już chyba to nie wystarcza.

**Comment by MartaNowaczyk** [comment]
Zgadza się, na poprzednich zasobach tak to działało. W obecnych nie ma promowań.

**Comment by tomylee0** [comment]
Poproszę o dokładniejszą informację na temat jak w tej chwili możemy na istniejących już ofertach sprawdzić wszystkie rodzaje prowizji od sprzedaży i ich kwoty jakie dla tej oferty zostaną pobrane w momencie sprzedaży? Lub może istnieje gdzieś taki poradnik? 

Znalazłem w "Sprawdzanie opłat" -> "Kalkulator opłat" dosyć powierzchowną treść: 

_Skorzystaj z POST /pricing/offer-fee-preview, aby sprawdzić, jakie opłaty naliczymy w ramach konkretnej oferty. Wystarczy, że w strukturze offer przekażesz pełne dane oferty._ 

Taka informacja wydaje się nie być wystarczająca biorąc pod uwagę zmiany w zasobach.

**Comment by tomylee0** [comment]
Zapytam od razu konkretniej. Proszę o odpowiedź czy teraz muszę z odpowiedzi na /sale/offers/{offerId}/promo-options pobrać wszystkie istniejące tam basePackages.id oraz wszystkie istniejące tam extraPackages.id i te zebrane wartosci wziąć za nazwę atrybutu w obiekcie promotion i ustawić je na true w /pricing/offer-fee-preview w obiekcie offer? Jeśli tak, to zrobiło się to naprawdę skomplikowane. Może jest łatwiejszy sposób?

I drugie pytanie. Do czego służą classifiedsPackages w /pricing/offer-fee-preview?

**Comment by MartaNowaczyk** [comment]
Tak, dzięki `GET /sale/offers/{offerId}/promo-options `odczytasz jakiego typu opcje promowania ma dana oferta i wtedy możesz je podać w obiekcie promotion. Dostępne są: `emphasized1d`, `emphasized10d`, `promoPackage`, `departmentPage`.
Niestety nie ma łatwiejszego sposobu.
`classifiedsPackages` to promowanie ogłoszeń.
