### ISSUE TITLE
400 Client Error: Bad Request for url: https://api.allegro.pl/sale/product-offers. Message is not readable.

### ISSUE THREAD

**Issue by Liritt** [allegro/allegro-api#9223]
Hello, I am trying to create an offer throught the /sale/product-offers endpoint. 
To do this, I use the "requests" package from python.
However, I keep getting the error "Message is not readable.". As there is no other explanation and I do not find an error in the payload that I send, I would like to know why it is not working.
Trace id : 22c6e86866c7f1f3
headers: 
```json
{
      "Authorization": f"Bearer {token}",
      "Accept": f"application/vnd.allegro.public.v1+json",
      "Content-Type": f"application/vnd.allegro.public.v1+json"
}
```
Payload: 
```json
{
      "productSet": [{
          "product": {
              "id": "8718369160861",
              "idType": "GTIN"
          }
      }],
      "sellingMode": {
          "price": {
              "amount": "88.45",
              "currency": "PLN"
          }
      },
      "stock": {
          "available": 62
      },
      "delivery": {
          "handlingTime": "PT24H",
      }
}
```
Could you tell me where is the error please ?

**Comment by Liritt** [comment]
I managed to fix this error, however I now have a status 422: "Missing required parameters: 248708" which corresponds to an attribute named "Type" but I have no clue as to what it is and why do I have to put this value as the only thing I want to create is an offer and not a product

**Comment by AureliuszBrussy** [comment]
Product data in some cases may be incomplete, for example, in a situation where it does not have all the parameters required at that moment for listing. If in response you receive information about missing required parameters, provide them in product object. You can check parameter ID with its value via [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).
