### ISSUE TITLE
Offers duplication & deletion

### ISSUE THREAD

**Issue by Liritt** [allegro/allegro-api#9229]
Hello, 

We created an offer with id 15868860328 on product with EAN 5414709190743.
Because in our internal process, when we do not have stock anymore we:
- delete the offer in our application
- delete the offer on Allegro

We wanted to simulate a situation where we got a refill of the product we deleted before on Allegro.
What we did was creating with the same values an offer with the same EAN. What we did not expect was having 2 exact same offers with 2 differents ids: 15868066254 and the last one, 15868860328. 
Why does your system allow duplications of offers ? 
We did not set the stock at 0 on Allegro before creating another offer, would it have deleted the offer with id 15868860328 if we set the stock to 0 before creating another one ?

How should we handle this ?

Thanks in advance

**Comment by Liritt** [comment]
I have another question based on your deletion process, if I understood well, deleting an offer = setting stock to 0. 
We have an offer (15863870504) that we created directly on the back-office. However, we tried to update the stock to 0, as to simulate a deletion and that's where we received the error "Missing required parameter". Even if there is this error, it looks like we are live on on the front. How can we forcefully set our stock to 0/ change our price if we ever get this error in an automatic way ? Because it looks like it could create problems of stock in case we want to delete a product we do not have stock anymore.

**Comment by MaciejFrackowiak** [comment]
In Allegro you can list more than one offer with the same EAN/product. So if your product stock is 0, you should set offer stock = 0 - as a result, we will finish the offer immediately. 
After refill of the product, you can set a new stock for the existing offer and then, activate it again using [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) or [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT).
Please, read our tutorial about [editing offer fields](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#editing-offer-fields) and [offer status change](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#offer-status-change).

**Comment by MaciejFrackowiak** [comment]
You cannot delete the offer - you can just finish it, and you don't have to set the stock = 0. If you change the offer stock, we don't take into account offer parameters. So the process always will go on.

**Comment by Liritt** [comment]
I see, thanks !
