### ISSUE TITLE
[REST] metoda /order/checkout-forms : ustalenie daty "zdarzenia"

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#923]
Jak w temacie,
jak ustalić datę zdarzenia w danych zwracanych w tej metodzie ?
jedyne znaczniki czasowe jakie tam występują to
'lineItems' =>  'boughtAt' =>  które występują więcej niż raz ...

Pozdrawiamy wwwfactory

**Comment by PawelTaberski** [comment]
Lista zamówień z /order/checkout-forms jest sortowana po dacie zakupów. Możesz również w ten sposób filtrować dane jakie otrzymasz np:
`https://api.allegro.pl/order/checkout-forms?lineItems.boughtAt.lte=2018-07-31T08%3A48%3A14.889Z&lineItems.boughtAt.gte=2018-07-31T08%3A48%3A14.888Z` 
Jeśli potrzebujesz datę wystąpienia zmiany to otrzymasz ją w /order/events w polu "occurredAt"

**Comment by PawelTaberski** [comment]
Od najnowszego do najstarszego. Więcej na ten temat [tutaj](https://developer.allegro.pl/orders/#03).
