### ISSUE TITLE
Adding missing mandatroy attributes to an offer

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#9235]
Hi, I was wondering, if there is a way to enrich offer with mandatory product parameters, without "removing" existing ones
example:
I have an offer with missing parameters 59, 18160. Other mandatory parameters were already filled in on the product. I patch the offer with 2 missing parameters, and now all the parameters, that were existing on product are now "gone" and error message list all the mandatory parameters as missing (except 59 and 18160 I have PATCHed)

Original `"message": "Missing required parameters: 18160, 59"`
After adding it to the offer the error reads
`"message": "Missing required parameters: 54, 3786, 249512, 4126, 3766, 127488, 127662, 127468, 201017, 201025"`

I hope this question makes sense. I was not able to find an answer myself in documentation.

Cheers!

**Comment by MartaNowaczyk** [comment]
In that case, you'll need to send a full list of parameters  - for arrays we are on an all-or-nothing basis (in compliance with the guidelines in [RFC7396](https://tools.ietf.org/html/rfc7396)). Here's our [guide](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#editing-single-offer).

**Comment by MartaNowaczyk** [comment]
Just send a list of all those to be included, those you had + those that are missing. If you don't want to add a parameter, you don't add it to the list. 
If you want to add a new product proposal, use [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). You can check if parameter is required to create a product in the `requiredForProduct` field.
