### ISSUE TITLE
Brak zmiany statusy zamowienia po stronie kupujacego na srodowisku sandbox

### ISSUE THREAD

**Issue by bmusialekcepd** [allegro/allegro-api#9242]
witam,

zlozyslismy zamowienie testowe na srodowisku sandbox - 67bc4920-2e0d-11ef-81d9-c7a80c0ae342.
Zmienielimsy mu status jako wysłane + dodalismy przesyłke
@
<img width="1381" alt="Zrzut ekranu 2024-06-19 o 15 08 48" src="https://github.com/allegro/allegro-api/assets/139112632/9e8e7879-86fe-4d48-af01-f459a6360081">
<img width="1381" alt="Zrzut ekranu 2024-06-19 o 14 24 09" src="https://github.com/allegro/allegro-api/assets/139112632/928292b5-166c-4415-893a-3ee48b205aff">

Po stronie klienta zamowienie dalej widnieje jako 'w przygotowaniu'
![Uploading MicrosoftTeams-image (55).png…]()

**Comment by AureliuszBrussy** [comment]
Czy status po stronie kupującego wciąż jest niezmieniony?

**Comment by AureliuszBrussy** [comment]
Poszperałem trochę - status po stronie kupującego nie jest odzwierciedleniem zmian statusu po stronie sprzedającego. Odzwierciedla natomiast historię statusów faktycznej przesyłki. Na Sandboxie ten status nie zmieni się automatycznie. 

Zmieniłem status tej przesyłki na dostarczoną.

**Comment by bmusialekcepd** [comment]
dzikeuje za informacje
