### ISSUE TITLE
[500] Server error: `PATCH https://api.allegro.pl/sale/product-offers/xxx` resulted in a `500 Internal Server Error`

### ISSUE THREAD

**Issue by robsonek** [allegro/allegro-api#9244]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy wywoływaniu metody PATCH sale/product-offers mam zwrotkę:

> {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Try again in a few minutes."}]}

> [trace-id] =>  671425f653cd48d2
> [trace-id] => c472444ac9407a35

**Comment by AureliuszBrussy** [comment]
Powodem błędów jest to, że wysyłasz nieprawidłowe url do zdjęć - zawierające nieenkodowane białe znaki (spacja), np.:

`http://st...ee.pl/F1/381942/Bar001058_hoker_vivia 1500x1500 v2.jpg`

**Comment by robsonek** [comment]
ok, dziękuje. Działa :)
