### ISSUE TITLE
błąd [błąd: ''str'' object has no attribute ''method''] WzA

### ISSUE THREAD

**Issue by Grubyxxx** [allegro/allegro-api#9246]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,

Napotkaliśmy się dzisiaj na błąd u naszych klientów, przy zamówieniach z Allegro, korzystających z WzA

[błąd: ''str'' object has no attribute ''method'']

Niestety nie ma zasady co do metody wysyłki, dzieję się to niezależnie od wybranej metody - jest losowe

**Comment by MaciejFrackowiak** [comment]
Proszę podaj przykładowe trace-id wywołania.
