### ISSUE TITLE
Cannot create accounts on the sandbox front

### ISSUE THREAD

**Issue by Liritt** [allegro/allegro-api#9247]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

When trying to create a business account and a customer account on the sandbox, we got this error when pressing "Next" button
![image](https://github.com/allegro/allegro-api/assets/110486250/75a7b6e1-4e8f-4cfb-82e7-df7f315cf3ae)

**Comment by MartaNowaczyk** [comment]
Show a screenshot at which point it is.

**Comment by Liritt** [comment]
I putted random values but the error is when we press the "Next" button. Once pressed, we get this error and cannot press any other button unless reloading the page.
![image](https://github.com/allegro/allegro-api/assets/110486250/9603792e-4cfc-4c58-b9b0-e99b68effdaa)

**Comment by MartaNowaczyk** [comment]
We checked and failed to repeat the error. Check if you have any security features enabled.

**Comment by Liritt** [comment]
Maybe due to my navigator (Chromium), but one of my co-worker managed to do it.

**Comment by MartaNowaczyk** [comment]
I'm happy to hear that it worked out. Have a nice day.
