### ISSUE TITLE
[REST] Pobieranie Zdarzeń i ich treść w metodzie /order/events

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#926]
Witam ponownie 
Dziś pojawiło się pytanie o dane zwracane w ww metodzie. A konkretnie :

Wszystkie zdarzenia dotyczą tego samego kupującego
Wszystkie pozycje zamówienia mają te same 'lineItems' => Id.

1 zdarzenie: 'type' =>  'BOUGHT', checkoutFormid' => '027fab92-ee3c-11e8-ba5a-91b9c258ebf6' 
2 zdarzenie:  'type' =>  'BOUGHT', checkoutFormid' => 'ff652522-ee3b-11e8-af6c-6d12b997806b'
3 zdarzenie: 'type' =>  READY_FOR_PROCESSING',  'checkoutForm' => 
                  'id' =>  '3647be41-ee3c-11e8-9cd8-e152beb6be5b'
4 zdarzenie:   'type' =>  'FILLED_IN' 'checkoutForm' => 
                  'id' =>  '3647be41-ee3c-11e8-9cd8-e152beb6be5b'

Pytanie: 

Dlaczego z dwóch zamówień o różnych Id zrobiło się trzecie zamówienie o innym id i dalej proces zakupowy operował już na tym zamówieniu ? Czy to jest normalne zachowanie czy jakiś błąd. (rano wasze serwery zgłaszały problemy)

Pozdrawiamy wwwfactory

**Comment by PawelTaberski** [comment]
Taka sytuacja mogła wystąpić w przypadku zakupu kilku produktów i następnie wypełnienia dla nich jednego formularza opcji dostawy, wtedy są one niejako grupowane i już są widoczne pod nowym id.
