### ISSUE TITLE
Matching error - product with EAN 0710845860669

### ISSUE THREAD

**Issue by Liritt** [allegro/allegro-api#9260]
Hello,

Today we sold 2 products with the ean 0710845860669, which are, in our catalog, valve kit from the brand Quarq. 
However, the product on Allegro is a bike, from the brand "Rondo".

I searched the owner of this EAN with GS1 and found that it is owned by "Sram Corporation". https://www.gs1.org/services/verified-by-gs1/results?gtin=0710845860669

Quarq is a brand owned by Sram. However Rondo isn't which proves that the product on Allegro is not the good one.

Based on this information, could it be possible to delete this product, so that we can avoid sending offers on it please ?

Thanks in advance

**Comment by MaciejFrackowiak** [comment]
If you have any remarks about existing products, you can propose a change by [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal). We do not provide a resource which will delete a product.
