### ISSUE TITLE
Brakma płatności nie zwraca płatności mimo ,że w panelu zamówienie jest opłacone przez PayU

### ISSUE THREAD

**Issue by Lucjan540** [allegro/allegro-api#9264]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [ x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Płatność o ID a49ca6bc-2f0b-11ef-af95-ef16a0129004 nie jest zwracana przez bramkę mimo ,że jest płatnością PayU opłacoaną. 

- trace id - 79ed6ad094d8a522
- url 
https://api.allegro.pl/payments/payment-operations?occurredAt.gte=2024-06-19T00:00:00Z&occurredAt.lte=2024-06-21T23:59:59Z&offset=0&limit=50

**Comment by MaciejFrackowiak** [comment]
Wskazana płatność znajduje się na saldzie środków oczekujących. Aby wyfiltrować takie pozycje skorzystaj z filtra "wallet.type=WAITING".

**Comment by Lucjan540** [comment]
Dlaczego w takiej sytuacji zamówienie jest "opłacone" skoro oczekujemy na płatność ?

**Comment by MaciejFrackowiak** [comment]
Zamówienie zostało opłacone - zarządzanie tymi środkami jest wyłącznie opóźnione. Szczegółowe informacje znajdziesz w [Pomocy Allegro](https://help.allegro.com/sell/pl/a/zakladka-srodki-i-historia-operacji-7G6ElROnWuB).

**Comment by Lucjan540** [comment]
Korzystając z filtr "wallet.type=WAITING"mogę założyć ,że wszystkie płatności, które wpłyną w ten sposób są opłacone i prawidłowe a jedynie zarządzanie tymi środkami jest opóźnione ?

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak.
