### ISSUE TITLE
Fulfilment status for orders

### ISSUE THREAD

**Issue by Liritt** [allegro/allegro-api#9265]
Hello,

I would like to know which fulfilment status to put and at which moment, and what consequences does it bring customer side and seller side.

NEW -> New order, bought / paid / filled by customer
PROCESSING
READY_FOR_SHIPMENT
READY_FOR_PICKUP
SENT -> status to put when we ship the order
PICKED_UP
CANCELLED -> status to put when we cancel or refund the order ?
SUSPENDED.

For the rest, I couldn't find any part of the documentation explaining them, could you please enlighten me ?

Thanks

**Comment by MaciejFrackowiak** [comment]
These seller order statuses are mainly to keep orders in order. As you described, every new order has a NEW status. If you ship the order, the order should be changed to SENT. So only you as a seller decide which status has an order.

**Comment by Liritt** [comment]
Does that mean that if I only want to use "SENT" and "CANCELLED" statuses, I can ignore all other statuses ?
In which type of situation should the "SUSPENDED" status be used ?

Thanks

**Comment by MaciejFrackowiak** [comment]
It all depends on your way of order management. For example, the "SUSPENDED" status you can use if you wait for the goods delivery and now you are not able to send it to the buyer.
