### ISSUE TITLE
Wrong order status for 9e0c5fe0-3076-11ef-9d77-b5aee86ce776

### ISSUE THREAD

**Issue by Liritt** [allegro/allegro-api#9266]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Hello, 

From the /order/events and the /order/checkout-forms endpoints we get that order status of 9e0c5fe0-3076-11ef-9d77-b5aee86ce776 is "FILLED_IN" even thought it was cancelled by the buyer during payment.

The order should be "CANCELLED" but it stayed as "FILLED_IN".
Could you please check it out please ?

Thanks

**Comment by MaciejFrackowiak** [comment]
As I see in our database, only payment was cancelled. The buyer didn't cancel the order. It means that he still can pay for that order.
