### ISSUE TITLE
Aktywacje kont na Sandbox: michaszko, Client:107111040

### ISSUE THREAD

**Issue by michaldrewka** [allegro/allegro-api#9269]
Poproszę o aktywację kont na Sandbox: michaszko, Client:107111040.

**Comment by AureliuszBrussy** [comment]
Aktywowałem konto michaszko. Client:107111040 to konto zwykłe - aktywujesz sie przy pierwszej transakcji.

**Comment by michaldrewka** [comment]
Dziekuję za aktywację 👍
