### ISSUE TITLE
[SANDBOX] Problem z rejestracją Aplikacji

### ISSUE THREAD

**Issue by multiart** [allegro/allegro-api#927]
Witam.
Dzisiaj doświadczam następującego problemu: będąc na stronie https://allegro.pl.allegrosandbox.pl/moje-konto chcę przejść do opcji WebAPI Informacje i ustawienia. Po kliknięciu w link na ułamek sekundy pojawia się informacja, że wystąpił błąd podczas ładowania strony i następuje przekierowanie na https://allegro.pl/login/form?authorization_uri=....

**Comment by PawelTaberski** [comment]
Ta strona już nie istnieje informacje o wszystkich kluczach jakie zarejestrowałeś zarówno w WebAPI jak i REST API  znajdziesz na tej stronie: https://apps.developer.allegro.pl/
Natomiast dla sandboxa tutaj:  https://apps.developer.allegro.pl.allegrosandbox.pl/
