### ISSUE TITLE
Connect to business account on sandbox

### ISSUE THREAD

**Issue by Liritt** [allegro/allegro-api#9270]
Hello,

How can I connect to my sandbox business account ? I writted my identifiers on url https://allegro.pl.allegrosandbox.pl/logowanie?origin_url=%2F but i guess it only works with customer accounts so where can I login on my business account ?

Thanks

**Comment by PrzemyslawLukanowski** [comment]
Hello, Sandbox is a separate environment from the production environment, so you need to register a new business account. You cannot log in using production credentials. 
Use fake credentials when registering, there are no real payments in Sandbox, each payment is handled by a payment simulator.

**Comment by Liritt** [comment]
That's what I did, I created a sandbox business account and wanted to log in, but it says that the credentials I gave were wrong, which is not true.

**Comment by Liritt** [comment]
The name of the account is spacefoot_test, it normally is an activated account

**Comment by PrzemyslawLukanowski** [comment]
Yes, I confirm that the account is active.  I cannot repeat this scenario, so it looks like the password may have been entered incorrectly. If your current password is not working, click "Recover password" and change it.

**Comment by Liritt** [comment]
I will try that. Also, I try to buy something with a customer account with blik but it keeps saying that the Blik code I put is incorrect, how can I pay a product in the sandbox ?

**Comment by PrzemyslawLukanowski** [comment]
Please use the 123456 blik code on Sandbox.

**Comment by Liritt** [comment]
Well it didn't work, but after using the last payment option it finally worked.
I tried resetting the password of the sandbox business account but I never receive the email that is supposed to be sent...

**Comment by PrzemyslawLukanowski** [comment]
You need to wait a moment after entering the blik code, at least it worked when I was checking it a while ago.

There was some delay with the email - now you should receive all three of them at 11:44.
