### ISSUE TITLE
Dostęp do rozkazu  GET /offers/listing   

### ISSUE THREAD

**Issue by Dawid-BetterSoft** [allegro/allegro-api#9272]
Dzień dobry

Reprezentuję spółkę BetterSoft. Tworzymy oprogramowanie do automatyzacji sprzedaży.  
Na rynku jesteśmy od 6 lat, choć wcześniej istnieliśmy pod JDG. 

Dla naszych klientów obsługujemy średniomiesięcznie ~ 320 tysięcy transakcji (dane za 2023). 
Oprogramowanie pracujące przez API rozwijamy od 2015 roku (pamięta jeszcze WebApi) 

Na jesieni ubiegłego roku jeden z naszych VIP-owskich klientów uzyskał dostęp do  wymienionego w tytule rozkazu, a my dla niego przygotowaliśmy dedykowaną rozbudowę naszego oprogramowania o funkcje śledzenia ofert konkurencji. 

Ponieważ działa to bardzo sprawnie - chcielibyśmy taki dostęp uzyskać dla naszego ClientID aplikacji - aby funkcjonalność udostępnić szerszemu gronu klientów.  
Jak możemy to zrobić?  

pozdrawiam
Dawid Kopański

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, poprosimy w tym przypadku o przesłanie powyższych informacji przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).

**Comment by Dawid-BetterSoft** [comment]
Witam panie Przemysławie
Formularz kontaktowy, sprawa 42878614, cytuję:

_Dzień dobry,

dziękuje za wiadomość.

Prosiłabym o skierowanie swojego zapytania za pomocą poniższego linku:
https://github.com/allegro/allegro-api

należy kliknąć w zakładkę Issues, a następnie New issue.

Jeśli nie posiadają Państwo tam konta prosiłabym o jego założenie, podając adres e-mail i hasło. 

Po rejestracji wysyłamy e-mail z linkiem do aktywacji.

Po zarejestrowaniu konta wystarczy dokończyć zakładanie zapytania. Wybrać odpowiedni temat i podać wymagane w formularzu dane.

Gdyby pojawiły się dodatkowe pytania pozostaje do dyspozycji oraz życzę miłego dnia!

Pozdrawiam
// Sandra Dudek
Zespół Allegro_

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam, ale w wyniku pomyłki musiał Pan zostać błędnie odesłany na forum. Poniżej załączam informację z naszego [poradnika](https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk), weryfikacja aplikacji następuje po kontakcie przez formularz.

<img width="499" alt="Zrzut ekranu 2024-06-25 o 10 56 24" src="https://github.com/allegro/allegro-api/assets/51473661/f20822c5-a3ff-422a-9d59-c187eea9cc76">

**Comment by Dawid-BetterSoft** [comment]
Panie Przemysławie - jeszcze raz.  

Od dokładnie kliknięcia w ten link formularza zaczęliśmy naszą drogę i zostaliśmy odesłani tu.

Nawet pokusiłem się o odpisanie na wiadomość zacytowaną powyżej, tłumacząc że chodzi o rejestrację aplikacji, podpisanie NDA itd...   - odpowiedź była taka, że (znów cytat): 

_Dziękuję za wiadomość.

Poprzednia konsultantka przekazała Państwu poprawne informacje, a jeżeli mają Państwo dodatkowe pytania to proszę o ich doprecyzowanie.


Pozdrawiam
// Gabriela Krawczyk_

**Comment by PrzemyslawLukanowski** [comment]
Najmocniej przepraszam za tę sytuację, jednak na forum nie zajmujemy się weryfikacją aplikacji, wszelkie zgłoszenia, zgodnie z opisem na stronie, przyjmujemy przez formularz kontaktowy. Prosiłbym ponownie o przekazanie takiej informacji w zgłoszeniu, natomiast ze swojej strony zlokalizuję jednostkę odpowiedzialną za wiadomość i poinformuję o zaistniałej pomyłce w odpowiedzi.

**Comment by Dawid-BetterSoft** [comment]
Ok dziękuję!
