### ISSUE TITLE
Price change on the offer 

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#9276]
Hi, we have a problem with the offer 15530938679. The price on Allegro is 2145.70 PLN on Allegro, but the change did not come thru API from our system. From the responses to our PATCH requests, I can tell the price was still correct (3050.00 PLN) on Jun 17th 2024 @14:26:34 (< trace-id: 9250bfec05c21fb0), after that the price was lowered to 2145.70 PLN. Is there a way to figure out, where the price change originated from?

Thx.

Jirka

**Comment by ZajdaBear** [comment]
I was asked to push correct price thru API now, so please note, the price is correct now, but I am looking for the change to 2145.70 PLN, I have no record of.

**Comment by PrzemyslawLukanowski** [comment]
Hello, the price on this offer was changed to 2145.70 on 18.06.2024 16:27 by the seller via the browser form.

**Comment by ZajdaBear** [comment]
Thank you so much
