### ISSUE TITLE
[SANDBOX] [REST] Brak zdarzeń 

### ISSUE THREAD

**Issue by DamianKomorowski** [allegro/allegro-api#928]
Dla wczorajszej transakcji dokonanej około godziny 22 lis 2018, 23:37 Brakuje zdarzeń na zasobie /order/events  
Nr. Płatności : 9e9cad12-eea6-11e8-98cb-112fda3e4dc4 
Nr. oferty : 6206030570
Transakcję widać na https://allegro.pl.allegrosandbox.pl/seller-orders/#!/
Proszę o informację dlaczego taka sytuacja wystąpiła.

**Comment by PawelTaberski** [comment]
Pamiętasz, że lista posortowana jest od najstarszych i najnowsze powinno być na końcu. I czy zasób /order/event-stats zwraca Tobie najnowsze zdarzenie?
Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/orders/#02).

**Comment by DamianKomorowski** [comment]
Oczywiście pamiętam. 
Jednak zdarzeń odnośnie tego zakupu nie ma na tym zasobie. 
W kolejnym dniu dokonałem nowej transakcji na tej samej aukcji i zdarzenia pojawiły się prawidłowo.

**Comment by DamianKomorowski** [comment]
Pytanie czy problemem na przykład mogło być to, że ta aukcja była dopiero co wystawiona ?

**Comment by PawelTaberski** [comment]
Nie powinno mieć to znaczenia, a jak pobierałeś zdarzenia? Pamiętaj że domyślnie pobierzesz tylko listę 100 najstarszych, aby dotrzeć do nowszych musisz wywołać ponownie z danym numer id eventy. Więcej na ten temat [tutaj](https://developer.allegro.pl/orders/#07). 
Jeśli mimo to nie ma wśród najnowszych tego zdarzenia, to podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619):

- pełnego cURL-a z wywołania GET na zasobie /order/events z najnowszymi zdarzeniami
- traceID tego zadania
- responsa

W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 928 na GitHub-ie
