### ISSUE TITLE
Kwota ubezpieczenia jest niższa niż kwota POD

### ISSUE THREAD

**Issue by jezewskiBNetrox** [allegro/allegro-api#9287]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,
nie jestem pewien czy to błąd czy też nie ale mam problem. Dla określonych danych próbujemy nadać przesyłkę za pomocą /parcel-management przez WZA:

Identyfikator zamówienia: `1328e560-338c-11ef-9f20-e961d738563c`
Metoda dostawy: `259b5c7a-9056-4c74-80ec-8bdc50cb0413` (Allegro Kurier DPD pobranie)
Wartość dostawy podawana w `cashOnDelivery.value`: `98.19`

Niestety nie jestem w stanie udostępnić trace-id dla tej sytuacji. Mam nadzieję, że podane dane są wystarczające.

Wyskakuje błąd po walidacji o takiej treści:
`The insurance amount cannot be less than the POD amount`

Zakładam, że chodzi o wartość `cashOnDelivery.value` jednak nie rozumiem, co jest nie tak z tą wartością. Nie podajemy nigdzie kwoty ubezpieczenia. Co zatem jest nie tak?

**Comment by AureliuszBrussy** [comment]
Wartość przedmiotu w polu **items[].value** (stąd bierzemy wartość ubezpieczenia) została zdefiniowana na 93.20 zł, czyli na mniejszą kwotę CoD (98.19 zł) - stąd błąd.

**Comment by jezewskiBNetrox** [comment]
> Wartość przedmiotu w polu **items[].value** (stąd bierzemy wartość ubezpieczenia) została zdefiniowana na 93.20 zł, czyli na mniejszą kwotę CoD (98.19 zł) - stąd błąd.

@AureliuszBrussy Rozumiem, czyli płatność za dostawę pobraniową ze Smart! nie liczy się do ubezpieczenia? Mógłbym przy okazji też zapytać, jak to widzi dział WzA dla przesyłek pobraniowych bez Smarta? Miałbym od razu problem z głowy.

**Comment by AureliuszBrussy** [comment]
Ubezpiecz przesyłkę na kwotę równą bądź wyższą niż kwota COD. Czyli w przypadku Smart! nie musisz doliczać kwoty za dostawę, a bez Smarta - razem z kosztem dostawy.

**Comment by jezewskiBNetrox** [comment]
@AureliuszBrussy Kłaniam się nisko i serdecznie dziękuję. Pozdrawiam. :)
