### ISSUE TITLE
415 Unsupported Media Type File is not PNG, JPG, GIF or SVG image.

### ISSUE THREAD

**Issue by netfarma** [allegro/allegro-api#929]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] także w allegro.pl.allegrosandbox.pl

:beetle: **Opis**
Problem walidacji zdjęć dotyczy zarówno REST API jak i edycji przedmiotu przez przeglądarkę.
Zdjęcia, które jeszcze w piątek mogłem swobodnie przesłać, dziś są odrzucane

**Comment by MartaNowaczyk** [comment]
@netfarma dzięki za zgłoszenie. Rzeczywiście jest problem z dodawaniem zdjęć na sandboxie. Przekazałam sprawę opowiedniemu zespołowi.

**Comment by marast78** [comment]
U mnie natomiast mam

```
Message: Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => NotSupportedException
                    [message] => An error has occurred
                    [details] => 
                    [path] => 
                    [userMessage] => An error occurred
                )

        )
)
```

Dla każdego formatu zdjęć, CLIENT ID: fe3519326e2c4486b053e64f8801cedc

Możecie sprawdzić w czym problem? Dostaję dodatkowo status 415, plik istnieje, url poprawny, mime/type poprawne

   ```
 [headers] => Array
        (
            [0] => Accept-Language: pl-PL
            [1] => Accept: application/vnd.allegro.public.v1+json
            [2] => Authorization: Bearer <TOKEN>
            [3] => image/png
        )

    [data] => @/var/www/project/files/goods/2/8/images/id11/Avatar082208.png
    [url] => https://upload.allegro.pl.allegrosandbox.pl/sale/images
    [code] => 415
```

**Comment by MartaNowaczyk** [comment]
@marast78 Przed chwilą na produkcji przesłałam zdjęcie i nie wystąpiły żadne problemy.  Czy to dokładnie ten sam problem? Występuje na środowisku testowym czy na produkcji?
Najlepiej jakbyć podesłał pełne cURLe z responsem i requestem (możesz przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z informacją, że dotyczy GitHuba #929). Błąd o którym piszesz jest zbyt ogólny by to dokładnie zweryfikować.

**Comment by marast78** [comment]
@MartaNowaczyk to jednak coś w kodzie, bo jak puściłem przez insomnie to zadziałało

**Comment by MartaNowaczyk** [comment]
@marast78 teraz widzę, podałeś samo image/png zamiast Content-Type: image/png
