### ISSUE TITLE
Create a shipment by API

### ISSUE THREAD

**Issue by Liritt** [allegro/allegro-api#9290]
Hello,

Among the required informations to create a shipment, we have to give 
![image](https://github.com/allegro/allegro-api/assets/110486250/a49a60fa-18ab-464c-b3b1-7e75e0382ef0)
Does it mean that we have to put our return address that is given in our return policy ?

Also,
![image](https://github.com/allegro/allegro-api/assets/110486250/8665c4f2-4bfe-494a-9f23-f01011afea1a)
This ask us a state when the customer is from US or Canada, but we do not get this information when importing order, same with the street number. How can we get these informations ?
Informations given when importing orders :
![image](https://github.com/allegro/allegro-api/assets/110486250/e2a1bcf3-0efd-45fe-8ad1-a9b6f616d5d1)
which does not include "state" or "street number".

Thanks

**Comment by PrzemyslawLukanowski** [comment]
Hello,

> Does it mean that we have to put our return address that is given in our return policy ?

It doesn't need to be the same address, you can use any sender address, we don't validate whether it's the same as defined in the return policy.

> This ask us a state when the customer is from US or Canada, but we do not get this information when importing order, same with the street number. How can we get these information ?

Unfortunately, you need to provide state field on your side. A street number is included in the order details along with the street name in the "street" field - you need to separate number also on your own.

**Comment by Liritt** [comment]
So for a US customer we have to manually check his address and put his corresponding state ?

**Comment by PrzemyslawLukanowski** [comment]
Yes, exactly.

**Comment by Liritt** [comment]
Ok thanks, and where can we get our generated allegro email ?

**Comment by PrzemyslawLukanowski** [comment]
Allegro receiver email is returned in the order details via [GET /order/checkout-forms](https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET) and [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation#operation/getOrdersDetailsUsingGET), field `buyer.email.`
