### ISSUE TITLE
Metoda change-price-commands zwraca bład w marketplace allegro-cz

### ISSUE THREAD

**Issue by p3le** [allegro/allegro-api#9296]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Mam problem z wysłaniem ceny na marketplace allegro-cz. Poniżej wklejam szczegóły:

trace-id: 6531821465a2dad3
error: ChangePrice.InvalidCurrency

uuid: 660a17fb-452a-4a82-88e4-13d4ca43ff6f
amount: 109
currency: CZK

Używam pojedynczej metody do wysyłki na allegro-pl i allegro-cz, różnicą jest inna kwota i waluta. W allegro-pl tego problemu nie ma. Proszę o weryfikację co jest nie tak. Dump danych które trafiają jako request body:

```
Array
(
    [id] => 660a17fb-452a-4a82-88e4-13d4ca43ff6f
    [input] => Array
        (
            [buyNowPrice] => Array
                (
                    [amount] => 109
                    [currency] => CZK
                )

        )

)
```

**Comment by AureliuszBrussy** [comment]
[PUT /offers/{offerId}/change-price-commands/{commandId}](https://developer.allegro.pl/documentation#operation/createChangePriceCommandUsingPUT) niestety nie obsługuje marketplace'ów dodatkowych. Możesz zmienić cenę tylko na rynku bazowym. 

Aby swobodnie zmieniać cenę na rynku dodatkowym możesz skorzystać albo z komendy batch'owej [PUT /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation#operation/priceModificationCommandUsingPUT), albo z edycji oferty za pomocą [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/editProductOffers).

**Comment by p3le** [comment]
Dziękuję za wyjaśnienie, offer-price-change-commands z przekazaniem marketplaceId zadziałało :)
