### ISSUE TITLE
Tworzenie oferty - POST /sale/product-offers

### ISSUE THREAD

**Issue by pr0fes0rre** [allegro/allegro-api#9299]
client: 106959585

Przy próbie tworzenia oferty za 
https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#kliknij-aby-zobaczyc-request

oraz

https://developer.allegro.pl/documentation/#operation/createProductOffers

w zapytaniu [POST /sale/product-offers] podając takie body 
``` 
 {
                "productSet": [
                    {
                        "product": {
                            "name": "Data volume test 9164",
                            "id": "000483ab-f500-4df4-bfe5-a7d0f7257f50",
                            "idType": "GTIN"
                            
                            
                        },
                        "quantity": {"value": 1},
            
                    }
                ],
                "delivery":{"shippingRates":{"id":"d3c29d53-437d-4a57-8d55-b09479e51024","name":"default"}},
                "stock": {"available": 99, "unit": "UNIT"},
                "sellingMode": {"format": "BUY_NOW", "price": {"amount": "123.45", "currency": "PLN"}}
            
            }
```

otrzymuję 

```
{
    "errors": [
        {
            "code": "OfferAccessDeniedException",
            "message": "Forbidden",
            "details": null,
            "path": "",
            "userMessage": "Access denied. You are not authorized to perform operations on the indicated offer",
            "metadata": {}
        }
    ]
}
```
W panelu aplikacji mam zaznaczone wszystkie możliwe uprawnienia, oraz ja chcę utworzyć nową ofertę a nie edytować istniejącą.

**Comment by PrzemyslawLukanowski** [comment]
Musisz posiadać konto firmowe, aby wystawiać oferty i nimi zarządzać za pomocą API. W Twoim przypadku korzystasz z konta zwykłego.

**Comment by pr0fes0rre** [comment]
Zmieniłem konto na firmowe, ale dalej otrzymuję błąd

```
{
    "errors": [
        {
            "code": "OfferAccessDeniedException",
            "message": "Forbidden",
            "details": null,
            "path": "",
            "userMessage": "Access denied. You are not authorized to perform operations on the indicated offer",
            "metadata": {}
        }
    ]
}
```

Uzupełniłem dane na sandbox i czekam na potwierdzenie rachunku bankowego, oraz danych firmy. Czy taki proces może potrwać długo?

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje, tak więc endpoint nie powinien już zwracać 403.

**Comment by sduranowski1** [comment]
hej, ja własnie tez zmienilem na firmowe i u mnie tez nie działa póki co

**Comment by sduranowski1** [comment]
client:107394386

**Comment by PrzemyslawLukanowski** [comment]
@sduranowski1 Skonfiguruj jeszcze proszę [Ustawienia Wypłat](https://salescenter.allegro.com/payout-settings). Po tej czynności będę mógł aktywować konto.

**Comment by sduranowski1** [comment]
Dodałem fikcyjny rachunek konta oraz dowod osobisty, ale to chyba jeszcze
nie zostalo potwierdzone jeszcze.

**Comment by PrzemyslawLukanowski** [comment]
@sduranowski1 Zgadza się, dopiero teraz aktywowałem Twoje konto.
