### ISSUE TITLE
REST - jak pobrać koszt dostawy z oferty bez przypiętego cennika?

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#930]
Cześć, mam pytanie w jaki sposób pobrać koszt dostawy z oferty bez przypiętego cennika (ceny dostawy wpisane "z palca")?

**Comment by MartaNowaczyk** [comment]
@rtnet-pl jeśli chodzi o REST API, korzystamy tylko z zapisanych cenników, także tych "z palca" nie pobierzesz. Jest jeszcze taka możliwość przez WebAPI metodą doGetItemFields.

**Comment by rtnet-pl** [comment]
Dzięki za odpowiedź.
O doGetItemFields wiem i korzystamy z niej obecnie, ale chcemy się pozbyć całkowicie starego API z aplikacji.
Domyślam się, że skoro takiej możliwości obecnie nie ma, to prawdopodobnie jej nie będzie czyli pozostajecie wyłącznie przy cennikach?

**Comment by MartaNowaczyk** [comment]
@rtnet-pl Dokładnie. Wspominaliśmy też https://github.com/allegro/allegro-api/issues/493, że do pierwszej połowy 2019 roku możesz edytować i wznawiać oferty bez cennika dostawy. Po tym terminie będzie to obowiązkowe - jak w przypadku wystawiania nowych ofert.

**Comment by rtnet-pl** [comment]
Rozumiem. Ostatnie pytanie - ile maksymalnie mogę mieć cenników?

**Comment by PawelTaberski** [comment]
@rtnet-pl Na jednym koncie możesz mieć maksymalnie 250 cenników.
Więcej na temat cenników znajdziesz [tutaj](https://developer.allegro.pl/sale/#shipping-rates).

**Comment by rtnet-pl** [comment]
Dzięki
