### ISSUE TITLE
Downloading image from URL ERROR

### ISSUE THREAD

**Issue by goses** [allegro/allegro-api#9304]
Dzień dobry,

od miesiąca dodajemy oferty Allegro z naszego sklepu poprzez napisany skrypt API, nic teraz nie zmienialiśmy a od wczoraj nie możemy nic dodać bo jest błąd z obrazkiem, Allegro nie może pobrać obrazka? ale jak się wchodzi w link wszystko działa, obrazki działają, SSL też, nie rozumiem o co chodzi?

JSON odpowiedzi:
```
array (
  'errors' => 
  array (
    0 => 
    array (
      'code' => 'DownloadError.ServiceUnavailable',
      'message' => 'Downloading image from URL \'https://parts-center.pl/img_produkty/244696_ZD2_preview_rev_1_08112023dP8lE.webp\' failed. Server returned the following HTTP status code: 503 SERVICE_UNAVAILABLE and response body: \'{"code":"UF,URX","message":"upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED","destination":{"serviceTag":null,"host":"public-downloader","path":"/get?url=https%3A%2F%2Fparts-center.pl%2Fimg_produkty%2F244696_ZD2_preview_rev_1_08112023dP8lE.webp&max_size=26214400","originalDst":null},"details":{"connectionId":9995265}}
\'.',
      'details' => NULL,
      'path' => 'images',
      'userMessage' => 'Downloading image from URL \'https://parts-center.pl/img_produkty/244696_ZD2_preview_rev_1_08112023dP8lE.webp\' failed. Server returned the following HTTP status code: 503 SERVICE_UNAVAILABLE and response body: \'{"code":"UF,URX","message":"upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED","destination":{"serviceTag":null,"host":"public-downloader","path":"/get?url=https%3A%2F%2Fparts-center.pl%2Fimg_produkty%2F244696_ZD2_preview_rev_1_08112023dP8lE.webp&max_size=26214400","originalDst":null},"details":{"connectionId":9995265}}
\'.',
      'metadata' => 
      array (
      ),
    ),
  ),
) 
```

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, wyjaśniamy już ten problem w wątku #9300.

**Comment by PrzemyslawLukanowski** [comment]
Błąd już nie powinien występować, przepraszam za problemy.

**Comment by goses** [comment]
Niestety ale u mnie dalej nie działa, dalej jest problem ale już z innym zdjęciem, tym razem .jpg

JSON:
`array (
  'errors' => 
  array (
    0 => 
    array (
      'code' => 'DownloadError.ServiceUnavailable',
      'message' => 'Downloading image from URL \'https://parts-center.pl/images/manitou-allegro.jpg\' failed. Server returned the following HTTP status code: 503 SERVICE_UNAVAILABLE and response body: \'{"code":"UF,UO","destination":{"serviceTag":null,"host":"public-downloader","path":"/get?url=https%3A%2F%2Fparts-center.pl%2Fimages%2Fmanitou-allegro.jpg&max_size=26214400","originalDst":null},"message":"upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED","details":{"connectionId":8936462}}
\'.',
      'details' => NULL,
      'path' => 'images',
      'userMessage' => 'Downloading image from URL \'https://parts-center.pl/images/manitou-allegro.jpg\' failed. Server returned the following HTTP status code: 503 SERVICE_UNAVAILABLE and response body: \'{"code":"UF,UO","destination":{"serviceTag":null,"host":"public-downloader","path":"/get?url=https%3A%2F%2Fparts-center.pl%2Fimages%2Fmanitou-allegro.jpg&max_size=26214400","originalDst":null},"message":"upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED","details":{"connectionId":8936462}}
\'.',
      'metadata' => 
      array (
      ),
    ),
  ),
) `

**Comment by goses** [comment]
Ok teraz sprawdziłem i przeszły 2 oferty, chyba już jest ok.

**Comment by PrzemyslawLukanowski** [comment]
dziękuję za potwierdzenie.
