### ISSUE TITLE
Pick-up point not found - Allegro Automat DHL BOX 24/7

### ISSUE THREAD

**Issue by randomWro** [allegro/allegro-api#9306]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - 
trace-id 1f5e65d5cf96f333

Dzień dobry, 
mimo dostępnych i prawidłowo działających AP DHL od kilku dni nie możemy zgłosić paczek do automatów. Przy paczkach do PO ten problem nie występuje. W odpowiedzi dla AP każdorazowo otrzymujemy błąd:

![obraz](https://github.com/allegro/allegro-api/assets/141820933/f0cc781c-4869-4df1-869c-f74a8050de9b)

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, wybrana przez Was metoda dostawy to "Allegro Odbiór w Punkcie DHL" (07c12933-584e-453d-bee5-60f3f32dfc73), tymczasem przesyłkę do tego punktu można nadać tylko dla metody "Allegro Automat DHL BOX 24/7" (0c330aea-900f-4830-9de8-72fadd2a3916).
