### ISSUE TITLE
WZA Orlen Paczka Bład

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#9307]
Mamy problem na produkcji przy zamowieniu przesylki  Wysyłam z Allegro Odbiór w Punkcie ORLEN Paczka
Problem z nadaniem przesyłki. Brak informacji o błędzie. Skontaktuj się z nami.
trace-id: 692637fe17f9abd0

**Comment by PrzemyslawLukanowski** [comment]
Wybrana metoda dostawy to "Allegro Odbiór w Punkcie ORLEN Paczka", jednak w requeście brakuje punktu odbioru. Przekazałem prośbę do zespołu odpowiedzialnego za Wysyłam z Allegro o poprawę komunikatu błędu.

**Comment by d3stozaur** [comment]
Ok dzieki za pomoc
