### ISSUE TITLE
[REST] różnica w danych zwracanych przez metody /order/checkout-forms/ 

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#931]
Dzień dobry - jak w temacie 
czy dane oferty (jednej oferty) zwracane przez metodę 
/order/checkout-forms
różnią się od danych z metody która pobiera tylko jedno id
/order/checkout-forms/f4ade313-ef0d-11e8-940c-57e21643ce7a

wwwfactory

**Comment by MartaNowaczyk** [comment]
@wwwfactory dane powinny być takie same
