### ISSUE TITLE
Cannot PATCH offer parameters

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#9317]
Hi, I am trying to PATCH offerId `15842933943` with all the mandatory parameters, and I get unexpected validation error I do not understand.

````{
    "errors": [
        {
            "code": "DictionaryParameterValueNotFound",
            "message": "Unprocessable Entity",
            "details": null,
            "path": "productSet[0].product.parameters",
            "userMessage": "An incorrect value `201025_2521` has been entered for parameter `Zapięcie`.",
            "metadata": {}
        }
    ]
}
````
the message itself is clear, but I do not understand, why is the value considered incorrect.. The offer is for product from 5537 category. Resource `/sale/categories/5537/parameters` returns `201025_2521` as one of the possible values for parameter `201025`.

trace-id: 8076c71fdd6a9a22

**Comment by PrzemyslawLukanowski** [comment]
Hi, dictionary parameter values should be sent in the `valuesIds` field. You are sending them in the `values` field and that is causing the error.

**Comment by ZajdaBear** [comment]
I can see that now. Sorry for that and thanks for your help.

**Comment by PrzemyslawLukanowski** [comment]
No worries, I'm glad I could help.
