### ISSUE TITLE
Nie można pobrać usług dostawczych

### ISSUE THREAD

**Issue by it-cewe-pl** [allegro/allegro-api#9318]
Zwracany jest błąd AccessDenied, co jest dziwne bo zawsze to działało. 
Odpytuję ten adres URL
https://api.allegro.pl/shipment-management/delivery-services

trace-id: e5deee8c21c53658

Inne zasoby działają poprawnie tj zwracane są wyniki.

Wymagany jest jakiś inny token, albo ponowna autoryzacja aplikacji ?

**Comment by PrzemyslawLukanowski** [comment]
W Twoim tokenie brakuje zakresu `allegro:api:shipments:write`. Musisz go dodać do aplikacji na stronie https://apps.developer.allegro.pl/ i ponownie zautoryzować aplikację w imieniu użytkownika. W ten sposób nowo wygenerowane będą posiadały już dodatkowy scope i będziesz mógł pobrać dane z zasobu.

**Comment by it-cewe-pl** [comment]
Dziękuję za informację
