### ISSUE TITLE
Bład przy pobieraniu ofert

### ISSUE THREAD

**Issue by JacusK** [allegro/allegro-api#932]
Z czego wynika blad podczas pobierania ofert w sandboksie ?

500 Error when searching seller offer (sellerId: 44067425, searchCriteria: {"limit":"100","offset":"0"};

Wystepuje losowo co ktores pobraniem. Czasem uda sie poprawnie pobrac dane.

**Comment by PawelTaberski** [comment]
Rozumiem, że chodzi tobie o zasób /offers/listing przetestowałem na zmiennych jakie podesłałeś i nie udało mi się powtórzyć takiego błędy, wszystko wydaje się ok.
Podeślij przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) proszę pełnego cURL-a i responsa wraz z traceID z takim błędem sprawdzimy w czym jest problem.
W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 932 na GitHub-ie.

**Comment by PawelTaberski** [comment]
@JacusK przykładowe requesty i responsy pozwalają szybciej zdiagnozować przyczynę, niezbędne są traceID bo pozwalają nam wyśledzić konkretnego requesta i co się z nim działo. Jak tylko otrzymam dane to sprawdzimy w czym jest problem. A propo przesyłania niestety obecnie możemy takie dane przyjmować tylko przez formularz kontaktowy.

**Comment by PawelTaberski** [comment]
@JacusK Dostałem dane sprawdziłem i rzeczywiście jest problem z początku myślałem, że chodzi Tobie o metodę do listingów. Sprawę przekazałem do odpowiedniego zespołu. Proszę o cierpliwość.
