### ISSUE TITLE
WZA - umowy własne - wiele punktów nadawczych

### ISSUE THREAD

**Issue by Wojtu204** [allegro/allegro-api#9329]
Dzień dobry

Proszę o informację, w jaki sposób mamy przeprocesować kwestię umów własnych w Wysyłam z Allegro w momencie kiedy mamy wiele punków nadawczych, gdzie każdy z nich ma:
- dla DPD odrębne FID
- dla DHL odrębny identyfikator SAP
Czy w tym przypadku mamy na każdym koncie dla każdego punktu wprowadzić odrębne dane umowy własnej, dane logowania do API i ID i podczas zakładania paczki w shipment-management podawać w "credentialsId" numer odpowiedniej umowy, czy jest to rozwiązane w inny sposób?

Pozdrawiam
Wojtek

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, jak opisałeś to w pytaniu. Osobne dane to osobna umowa własna w Wysyłam z Allegro.

**Comment by Wojtu204** [comment]
Dziękuję za wyjaśnienie.
Pozdrawiam
Wojtek
