### ISSUE TITLE
Category 323421 was not found /pricing/offer-fee-preview

### ISSUE THREAD

**Issue by Desseres** [allegro/allegro-api#9333]
Występuje problem:
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**

Jeśli zgłaszasz problem z zasobami REST API:
Metoda /pricing/offer-fee-preview nie ma możliwości sprawdzania 5 poziomu kategorii i prowizji dla nich.
Przykładowa oferta: https://allegro.pl/oferta/domestos-750-ml-do-wc-pine-zielony-14103791137 znajduje się w kategorii o ID `323421` https://allegro.pl/kategoria/srodki-czyszczace-srodki-do-toalet-323421. 

Niestety dla tej kategorii nie istnieje możliwość sprawdzenia prowizji. Otrzymuje się błąd że kategoria `nie istnieje` co jest nie prawdą bo przecież widzę że istnieje.
 https://allegro.pl/moje-allegro/sprzedaz/kalkulator-oplat?categoryId=323421

```json
{
    "errors": [
        {
            "code": "ERROR",
            "message": "Category not found",
            "details": "Category 323421 was not found",
            "path": null,
            "userMessage": "Category 323421 was not found"
        }
    ]
}
```

**Comment by Desseres** [comment]
Co więcej, gdybym chciał ustalić rodzica dla kategorii o id `323421` i pobrać prowizję dla rodzica to również nie mogę tego zrobić, ponieważ metoda `https://api.allegro.pl/sale/categories/323421` zwraca błąd że kategoria nie istnieje.

```json
{
    "errors": [
        {
            "code": "ERROR",
            "message": "Category '323421' not found",
            "details": "ResourceNotFoundException",
            "path": null,
            "userMessage": "Category '323421' not found",
            "metadata": {}
        }
    ]
}
```

Dopiero dla kategorii wyżej, której nie jestem w stanie ustalić poprzez API dostaję odpowiedź.

```json
{
    "id": "253359",
    "name": "Środki czyszczące",
    "parent": {
        "id": "317369"
    },
    "leaf": true,
    "options": {
        "variantsByColorPatternAllowed": true,
        "advertisement": false,
        "advertisementPriceOptional": false,
        "offersWithProductPublicationEnabled": true,
        "productCreationEnabled": true,
        "customParametersEnabled": true,
        "sellerCanRequirePurchaseComments": false
    }
}
```

**Comment by PrzemyslawLukanowski** [comment]
Komunikat jest prawidłowy, ponieważ kategoria istnieje jedynie jako kategoria nawigacyjna, widoczna dla kupujących. Jako sprzedający nie masz możliwości wystawienia w niej ofert:

<img width="203" alt="Zrzut ekranu 2024-07-3 o 09 25 55" src="https://github.com/allegro/allegro-api/assets/51473661/a0034f9e-a1aa-4047-a67d-2374c19d18f5">

Więcej informacji na ten temat znajdziesz [w tym artykule](https://help.allegro.com/sell/pl/a/jak-laczymy-kategorie-w-ktorych-wystawiasz-oferty-5LaEYwWw2H5?marketplaceId=allegro-pl).

**Comment by Desseres** [comment]
fajnie fajnie, ale niekonsekwencja stosowania ID kategorii wprowadza w błąd.
Wywołując zapytanie: `https://api.allegro.pl/offers/listing?phrase=8720181377242&sellingMode.format=BUY_NOW&searchMode=REGULAR&sort=+price` otrzymuję json w którym mam podany ID kategorii.

```json
{
                "id": "15160771696",
                "name": "Domestos Przedłużona Moc Płyn do czyszczenia WC Pine Fresh 750 ml",
                "seller": {
                    "id": "74148862",
                    "login": "Stark2020",
                    "company": true,
                    "superSeller": false
                },
                "promotion": {
                    "emphasized": true,
                    "bold": false,
                    "highlight": false
                },
                "delivery": {
                    "availableForFree": false,
                    "lowestPrice": {
                        "amount": "9.99",
                        "currency": "PLN"
                    }
                },
                "images": [
                    {
                        "url": "https://a.allegroimg.com/original/11ff1c/08ead42e4b208ec9052339ac8dd7/Domestos-Przedluzona-Moc-Plyn-do-czyszczenia-WC-Pine-Fresh-750-ml"
                    }
                ],
                "sellingMode": {
                    "format": "BUY_NOW",
                    "price": {
                        "amount": "7.51",
                        "currency": "PLN"
                    },
                    "popularity": 11,
                    "popularityRange": "[11-20]"
                },
                "stock": {
                    "unit": "UNIT",
                    "available": 144
                },
                "category": {
                    "id": "323421"
                }
            },
```

Podana przez API kategoria to `323421`. Jak mam ustalić poprzez metody API że dana kategoria to kategoria 'nawigacyjna' i jak określić kategorie wyższego poziomu przy pomocy API?

**Comment by PrzemyslawLukanowski** [comment]
Nie ma takiej możliwości, oferty zwracane w ramach /offers/listing to oferty z widoku dla kupującego, dlatego mogą uwzględniać kategorie nawigacyjne, które nie istnieją w drzewie asortymentowym dla sprzedającego. Wszystkie kategorie dla sprzedającego pobierzesz w ramach [GET /sale/categories](https://developer.allegro.pl/documentation#operation/getCategoriesUsingGET).

**Comment by Desseres** [comment]
Czyli nie jestem w stanie pobrać przez API rodzica kategorii nawigacyjnej, bo nie istnieje ona w drzewie asortymentowym, ale istnieje w innych miejscach systemu, co jest śmieciową informacją wprowadzającą w błąd bo w żaden sposób kategorii nawigacyjnej nie idzie powiązać z drzewem asortymentowym. Wręcz zajebiście ...

**Comment by Desseres** [comment]
@PrzemyslawLukanowski co należy zrobić żeby mieć dostęp do metody `https://api.allegro.pl/sale/products`? 
Jak wysyłam json'a o treści

```json
{
  "phrase": "5903560623090",
  "mode": "GTIN",
  "language": "pl-PL",
  "searchFeatures": "SIMILAR_CATEGORIES"
}
```

to otrzymuje komunikat o braku uprawnień:

```json
{
    "errors": [
        {
            "code": "AccessDenied",
            "message": "Access is denied",
            "details": null,
            "path": null,
            "userMessage": "No access to the specified resource."
        }
    ]
}
```

czyli kolejny sposób na to żeby ustalić w jakiej kategorii z drzewa kategorii powinien znaleźć się produkt jest niedostępny. Dodatkowo odwołanie w dokumentacji do "This resource is limited with [Leaky Bucket](https://developer.allegro.pl/tutorials/basic-information-VL6YelvVKTn#limiting-the-number-of-queries-limits) mechanism." nie istnieje ... więc nie wiem co miałbym przeczytać żeby nie zadawać kolejnych pytań. Pewnie chodzi o ten link https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#ograniczenie-liczby-zapytan-limity ale nadal, mam ustawione na koncie RPM na poziomie -1?

**Comment by PrzemyslawLukanowski** [comment]
Przekaż proszę nagłówek Accept z wartością application/vnd.allegro.public.v1+json. W Twoim przypadku wygląda na to, że to właśnie to spowodowało błędną odpowiedź 403.

Dziękuję za zgłoszenie o błędnym linku, poprawimy to.
