### ISSUE TITLE
aktywacja konta

### ISSUE THREAD

**Issue by pap7tomek** [allegro/allegro-api#934]
prosze o aktywacje konta tomekromek na sandboxie

**Comment by MartaNowaczyk** [comment]
@pap7tomek konto na sandboxie aktywowane.

**Comment by mmilian** [comment]
proszę o aktywacje konta dla loginu: allegro_test na sanboxie.

**Comment by MartaNowaczyk** [comment]
@mmilian konto aktywowane. Teraz wystarczy, że przejdziesz do zakładki Moje konto i prześlesz nam w ramach weryfikacji jakieś dowolne dwa pliki.
