### ISSUE TITLE
Delivery-services - identyfikacja

### ISSUE THREAD

**Issue by bozenadulabrowin** [allegro/allegro-api#9345]
Cześć,

mamy integrację przez baselinker, ale przesyłki obsługujemy sami przez api allegro. Baselinker zwraca nam tylko name np. Allegro Kurier DPD, w jaki sposób dobrać odpowiednie 'deliveryMethodId', gdy nazwa w podanych przez Was danych się powtarza (zapytanie na endpoint 'delivery-services'?
![image](https://github.com/allegro/allegro-api/assets/173157770/cba2a33e-0abb-48ec-8d87-f4aae29e1fc4)

Bardzo proszę o podpowiedź.

Pozdrawiam
Bożena Duła

**Comment by AureliuszBrussy** [comment]
Odpowiednia usługa dostawy powinna zostać zmapowana po id, nie po jej nazwie. W zamówieniu zwracamy to id w polu `delivery.method.id`. Usługi dostawy w WzA korzystają z dokładnie tych samych identyfikatorów (`deliveryMethodId`). Jeżeli występują jakieś trudności z mapowaniem usług dostawy w Baselinkerze - proszę wyjaśnić to z ich supportem.

**Comment by bozenadulabrowin** [comment]
Dziękuję za odpowiedź

**Comment by bozenadulabrowin** [comment]
Dziękuję za odpowiedź
