### ISSUE TITLE
Non-functioning sandbox

### ISSUE THREAD

**Issue by DHSC1** [allegro/allegro-api#9349]
Hello,
we're trying to test on allegro sandbox and it looks like nothing around the transports is working. Even the cart pass doesn't work when I'm in the customer position trying to select shipping for an order. The price lists are not working either. Does this know of this problem? Is there any maintenance going on on the sandbox that should be causing this?

Tested on account: scandbox

![image](https://github.com/allegro/allegro-api/assets/144317759/5a461254-0df3-4c14-a576-f37b90c2ed3c)
![image](https://github.com/allegro/allegro-api/assets/144317759/2df44ddc-5417-485f-b2d8-67f74ca278ec)

**Comment by AureliuszBrussy** [comment]
Currently, I cannot confirm these problems - I was able to go through the ordering process. Are there still problems on your side?

**Comment by DHSC1** [comment]
I just tried both cases (price list and picking a carrier in the cart) and the situation is the same.

**Comment by DHSC1** [comment]
I also deleted the cookies and logged out/logged in.

**Comment by AureliuszBrussy** [comment]
Can you provide the login of the account from which you are trying to make a purchase?

I would also ask for a screenshot of the browser's developer console, from the window where the error message appears.

**Comment by DHSC1** [comment]
Hello,
it started working again over the weekend. Thank you for your cooperation.
