### ISSUE TITLE
DPD - odrzucenie paczki ze względu na gabaryty

### ISSUE THREAD

**Issue by Wojtu204** [allegro/allegro-api#9356]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other
Dzień dobry

Przy wysyłce paczki z metodą własną DPD otrzymaliśmy odrzucenie z komunikatem:
Podane wymiary paczki przekaczają maksymalną wagę gabarytową

Wymiary paczki podane w żądaniu:
WIDTH": "60.000",
HEIGHT": "60.000",
LENGHT": "70.000",
WEIGHT": "7.192",

Suma wymiarów nie przekracza 300cm.
Proszę o weryfikację poprawności działania w tym obszarze.
ID usługi użytej do przesyłki: c3066682-97a3-42fe-9eb5-3beeccab840c
UUID: 0bfe0e36-2a37-4a5b-aa82-56a98722cb79

Dziękuję i pozdrawiam
Wojtek

**Comment by AureliuszBrussy** [comment]
Widzę, że nie jest to metoda własna DPD, a Allegro Kurier DPD. W tym przypadku przesyłka znacznie przekracza wagę gabarytową, liczoną ze wzoru: [wysokość (cm) x długość (cm) x szerokość (cm)] / 6000. Max. waga rzeczywista i gabarytowa dla tej metody dostawy to 10 kg.

Więcej o tym przeczytasz w [pomocy dla sprzedającego](https://help.allegro.com/sell/pl/a/allegro-kurier-dpd-informacje-dla-sprzedajacych-LR88B9KlzFe#maksymalne-wymiary-oraz-waga-przesylek).

**Comment by AureliuszBrussy** [comment]
Dopłaty są doliczane po odbiorze (np. na sortowni) - jeżeli okaże się, że przesyłka nie spełnia wytycznych i jest niezgodna z deklaracją podczas jej tworzenia.

**Comment by Wojtu204** [comment]
Proszę jeszcze o informację, czy jeśli przykładowo waga gabarytowa, wynosi 28,5kg, a była zadeklarowana poniżej 10kg, obowiązuje tylko dopłata:
Dopłata do usługi Allegro Kurier DPD do paczki o wadze powyżej 25 do 31,5 kg (wagi rzeczywistej lub gabarytowej)
czy wskazana i suma poniższych progów?

**Comment by AureliuszBrussy** [comment]
Kwota zgodna z przedziałem w regulaminie - nie sumuje się z wcześniejszymi zakresami.

**Comment by Wojtu204** [comment]
Dziękuję, temat wyjaśniony.
