### ISSUE TITLE
Planowana zmiana zakładki "Sprzedaż" na "Sales Center" - adresy wywołań API

### ISSUE THREAD

**Issue by tomsyty** [allegro/allegro-api#9357]
Allegro planuje wprowadzić od października zmiany, zamiast zakładki "Sprzedaż" będzie "Sales Center". Jest ono w innej domenie (allegro.com), czy planowana jest też zmiana wywołań dla api lub może po okresie testowym który trwa obecnie przerzucą Sales Center z domeny .com na .pl? Pytam ponieważ mam skrypty działające w kontekście uruchamianej strony i próba wywołań api ze strony w domenie .com pod adresy api w domenie .pl będzie skutkować błędami CORS.

**Comment by AureliuszBrussy** [comment]
Nie, nie planujemy zmienić adresu wywołania publicznego API.

**Comment by KrzychuWalek** [comment]
Jaki jest adres salescenter.allegro.com dla sandboxu

Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
@KrzychuWalek adres to: https://salescenter.allegro.com.allegrosandbox.pl/.
