### ISSUE TITLE
[REST] Czasami brak danych dostawy w danych z /order/checkout-forms/{id}

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#936]
Zdarza się, że w danych zwróconych metodą /order/checkout-forms/{id} brak danych dostawy, brak delivery->address, mimo, że w panelu allegro widać te dane, widać,  że użytkownik wprowadził dane dostawy,

Id checkout form gdzie jest problem:

.... narazie ukryte ....

chciałbym się dowiedzieć czy publicznie mogę je podać, bo nie mam pewności czy jest zabezpieczenie które pozwala na oglądanie checkout form tylko partnerowi którego dotyczy?

Wystepuje to bardzo rzadko, raz na kilkaset zamówień, ale niestety zdarza się.

**Comment by MartaNowaczyk** [comment]
@tztztztz delivery->address - pokazujemy dopiero przy statusie READY_FOR_PROCESSING, czyli dopiero wtedy, gdy płatność będzie zakończona. W tym przypadku jest tylko rozpoczęta i masz status FILLED_IN.
checkoutForms_id - żeby pobrać szczegóły zamówienia musisz być zautoryzowany, także nie ma obaw.

**Comment by tztztztz** [comment]
To w takim razie podwójny błąd poniewaź ja pobieram tylko i wyłącznie te Eventy które są READY_FOR_PROCESSING, nie pobieram innego statusu. Więc jeżeli event pokazuje, że jest READY_FOR_PROCESSING a Checkout Forms jest FILLED_IN to coś nie tak.

Co więcej w tym przypadku klient nie tylko już zapłacił, co jeszcze te dane do wysyłki wypełnił.

Dodatkowo nie dzieje się tak dla każdego pobrania, tylko tak jak wspomniałem, sporadycznie, więc wydaje mi się, że nadal jest nie tak.

Id checkout form:

61b0bd83-f0c0-11e8-b8b6-d7fb51a277f5

**Comment by MartaNowaczyk** [comment]
@tztztztz żebym mogła to potwierdzić podaj cURL z responsem i requestem (możesz je nam także przekazać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) - w zgłoszeniu podaj numer wątku na GitHubie) oraz trace-id.

**Comment by tztztztz** [comment]
To jest niewykonalne bo nie korzystam z żadnego cURLa ani linii komend. Macie wszystkie informacje jakie są potrzebne do rzowiązania tego problemu:

1. pobieram tylko i wyłącznie eventy gdzie status to READY_FOR_PROCESSING I NIGDY ŻADNYCH INNYCH, W ŻĄDNYM MIEJSCU, NIGDY
2. od czasu do czasu checkout_form na które wskazuje event zamiast mieć status READY_FOR_PROCESSING ma status FILLED_IN i brak adresu

**Comment by MartaNowaczyk** [comment]
@tztztztz dziękuję za id eventu. Sprawdziłam i rzeczywiście ma inny status niż ten w zamówieniu. Nie powinno to tak wyglądać. Sprawę weryfikujemy.

**Comment by MartaNowaczyk** [comment]
@aktywnitu @tztztztz sprawa w trakcie weryfikacji - proszę o jeszcze trochę cierpliwości

**Comment by MartaNowaczyk** [comment]
@aktywnitu problem namierzony, musimy go jeszcze poprawić, także jeszcze trochę cierpliwości...

**Comment by MartaNowaczyk** [comment]
@tztztztz @aktywnitu Przepraszamy za te niespójności. Wprowadziliśmy poprawkę, która powinna wyeliminować takie problemy w przyszłości.

**Comment by aktywnitu** [comment]
Dzień dobry Pani Marto,
miło słyszeć tak dobre informacje.
Czekam zatem na tą istotną poprawkę.

**Comment by aktywnitu** [comment]
O! Napisałem komentarz, a tu w tym samym czasie Pani Marta informuje o wprowadzonej już poprawce.
Dziękuję Pani i życzę miłej pracy na dziś.

**Comment by MartaNowaczyk** [comment]
Dziękuję, wzajemnie :)

**Comment by aktywnitu** [comment]
@MartaNowaczyk , niestety nic się nie zmieniło.
W dalszym ciągu pojawiają się zamówienia bez danych do wysyłki mimo, że są za pobraniem:
Przykłady zamówień:
6b71ba06-ff97-11e8-a474-55c966d57068
693c2ae4-ff1f-11e8-9905-fdd6adf3eb40

Prosiłbym o sprawdzenie powyższych zamówień i naprawę problemu oraz wysłanie do dziennika zdarzeń uaktualnionych statusów dla "niekompletnych" zamówień pobraniowych.

**Comment by MartaNowaczyk** [comment]
@aktywnitu uaktualniliśmy na ten moment statusy zamówień. Obecnie pracujemy jeszcze nad poprawką w tym temacie.

**Comment by aktywnitu** [comment]
@MartaNowaczyk dziękuję za informację. Czekam na info o usunięciu usterki.

**Comment by aktywnitu** [comment]
Pani Marto, na szczęście zamówienia mają już poprawny status. Co prawda jest ich mniej(kilkadziesiąt w tygodniu) niż w grudniu(kilkaset), ale wraz ze stabilizacją API dodam kolejne konta testowe.

**Comment by MartaNowaczyk** [comment]
@aktywnitu dziękuję za informację :)
