### ISSUE TITLE
Błąd podczas zamawiania kuriera  

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#9360]
Dzień dobry,
próbuję zamówić przyjazd kuriera 
```
POST shipment-management/pickups/create-commands
{
   "commandId":"6c351a85-8b27-4930-99d2-41dee44c268d",
   "input":{
      "shipmentIds":[
         "3244d447-fa0f-4c47-9645-cb47f49e8095"
      ],
      "pickupDateProposalId":"2024070814000000"
   }
}
```
W odpowiedzi dostaję 
```
GET shipment-management/pickups/create-commands/6c351a85-8b27-4930-99d2-41dee44c268d

{
   "commandId":"6c351a85-8b27-4930-99d2-41dee44c268d",
   "status":"ERROR",
   "errors":[
      {
         "code":"BAD_REQUEST",
         "message":"Opennet API cannot process request",
         "details":"",
         "path":"",
         "userMessage":"Problem z nadaniem przesyłki. Brak informacji o błędzie. Skontaktuj się z nami."
      }
   ],
   "pickupId":null,
   "carrierPickupId":null
}
```

Zgodnie z komunikatem kontaktuję się.

**Comment by MartaNowaczyk** [comment]
Dzień dobry, błędny jest tu zakres godzin podjazdu "2024070814000000" zakres według tego zapisu to godziny 14:00 do 00:00 co jest niepoprawne - bo 00:00 to już kolejny dzień.

**Comment by mzawodzinski** [comment]
Ustawiłem do 16:00
```
{
   "commandId":"515977d7-2628-423c-9ff3-0ef6f2ae6f7e",
   "input":{
      "shipmentIds":[
         "39b37545-e6b7-4dd9-9517-89abcd20df92"
      ],
      "pickupDateProposalId":"2024070814001600"
   }
}
```
 ten sam komunikat.

Swoją drogą to w dokumentacji przydałby się jakiś lepszy opis tego pola, obecnie jest opisane jako "Internal pickup proposal ID". Po przykładzie domyśliłem że początek to data i godzina ale już nie wiedziałem za co odpowiada końcówka i dlatego dałem zera.

**Comment by MartaNowaczyk** [comment]
Mamy odpowiedź od przewoźnika, ze to nieprawidłowe godziny. Pobrałeś propozycje z [POST /shipment-management/pickup-proposals](https://developer.allegro.pl/documentation/#operation/getPickupProposals)?

**Comment by mzawodzinski** [comment]
Właściwie to dostałem dane ok klienta 🙈
Teraz działa, dzięki
