### ISSUE TITLE
Access the sandbox api

### ISSUE THREAD

**Issue by travisalicesgarden** [allegro/allegro-api#9367]
Hello,
I'm creating a sandbox account to access the api key but I can't access "my applications" because my account isn't validated. 

Is it possible to duplicate my production account on the sandbox account to avoid re-entering everything and save time? 

If this isn't possible, can you tell me what I need to do to access the api key so that I can get on with setting up Allegro?

Thanks for your support

**Comment by Lukasz-Zurek** [comment]
> Is it possible to duplicate my production account on the sandbox account to avoid re-entering everything and save time?

Not, it is not possible.

> If this isn't possible, can you tell me what I need to do to access the api key so that I can get on with setting up Allegro?

First of all you should have a business account, then configure payouts via this [site](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty). Please fill fictional data (together with IBAN) and use our payment simulator. Then please give me your sandbox account login - I will try to help you with activation process.

**Comment by travisalicesgarden** [comment]
We put the IBAN of our account because we didn't know which one to put. We're waiting for this to be checked. 
How can I use the payment simulator? 
Your documentation doesn't mention this...

My sandbox login is sweeek

**Comment by Lukasz-Zurek** [comment]
@travisalicesgarden We have described this specific process in our [tutorial](https://developer.allegro.pl/tutorials/first-steps-MRwXmYZrnc9#activate-your-sandbox-account).

Anyway, I have just activated your account so it could be good now.

**Comment by travisalicesgarden** [comment]
Great!
Thank you so much for your help

**Comment by travisalicesgarden** [comment]
Can you tell me why my production account hasn't been activated?

**Comment by Lukasz-Zurek** [comment]
@travisalicesgarden Regarding activation process on the production account - please use this [contact form](https://allegro.pl/pomoc/kontakt). This process is out of our hands and we do not have any access to it.
