### ISSUE TITLE
Nieprawidłowe informacje o zakończonej ofercie

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#937]
Występuje problem: 
 - [X] z metodą WebAPI
 - [X] z metodą REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [X] inny

:beetle: **Opis**

Problem dotyczy wielu aukcji, np. **7686745299**.

Metoda `doGetItemsInfo` zwraca:
```
<ns1:itEndingTime>0</ns1:itEndingTime>
<ns1:itEndingInfo>1</ns1:itEndingInfo>
```

W logach `doGetSiteJournal` `changeType == end` mam z datą **2018-11-22 16:12:44**

Tymczasem endpoint `/sale/offers/7686745299` zwraca:

```
"publication": {
	"duration": null,
	"status": "ENDED",
	"startingAt": null,
	"endingAt": null
}
```

Na froncie oferta jest zakończona

**Comment by MartaNowaczyk** [comment]
@TimothyKoval dzięki za zgłoszenie. Sprawą zajmuje się już odpowiedni zespół.

**Comment by TimothyKoval** [comment]
`7684421712` aukcja zakończona, w logach mam end, api odpowiada że trwa

**Comment by MartaNowaczyk** [comment]
@TimothyKoval dzięki za kolejny przykład. Nadal walczymy.

**Comment by MartaNowaczyk** [comment]
@deneb-k Pewne poprawki już wdrożyliśmy, jednak może zdarzyć się pojedynczy przypadek, w którym nadal status będzie niepoprawny. Będziemy rozwiązywać tę kwestię. Jeśli natrafisz na taki przypadek podaj go proszę, a uaktualnimy jego status. 
Za niedogodności przepraszamy - postaramy się to naprawić w jak najkrótszym terminie.
