### ISSUE TITLE
Do i have fully access?

### ISSUE THREAD

**Issue by bartflow** [allegro/allegro-api#9373]
Hi,

When i do an api call towards you to make an offer i now get the error this error:

{
    "errors": [
        {
            "code": "SellerAccountUnverifiedException",
            "message": "Product proposal unauthorized according to unverified account.",
            "details": null,
            "path": "productSet[0].product",
            "userMessage": "Użytkownik z nieaktywnym lub niezweryfikowanym kontem nie może zgłaszać nowych propozycji utworzenia produktu.",
            "metadata": {}
        }
    ]
}

The trace-id: 2d754b1c395eab2d
My account is bartproductflow

Do you need to fully activate it, or im a missing something?

**Comment by MartaNowaczyk** [comment]
Your account was not fully active. I have activated your account.
