### ISSUE TITLE
Na konkretnym adresie IP: ECONNRESET

### ISSUE THREAD

**Issue by KowalczykDawid** [allegro/allegro-api#9376]
Podczas próby zapytania GET `https://api.allegro.pl/sale/offers` dostaję ECONNRESET - dzieje się to tylko na jednym konkretnym adresie IP.

IP: 18.xxx.xxx.xxx

Proszę o weryfikacje czy wszystko jest po waszej stronie w porządku.

**Comment by Lukasz-Zurek** [comment]
@KowalczykDawid Czy byłbyś w stanie wysłać nam przykładowy request dla którego otrzymujesz ten błąd, tak abyśmy mogli spróbować go odtworzyć. Czy problem występuje dla wszystkich połączeń czy pojawił się kilka razy?

Z góry dziękuję za szczegóły.

**Comment by KowalczykDawid** [comment]
Kod przykładowy: 
const ALLEGRO_URL = 'https://api.allegro.pl';

const data = await axios.get(`${ALLEGRO_URL}/sale/offers`, {
        headers: {
          Authorization, // "Bearer " + authorizationToken
          Accept: 'application/vnd.allegro.public.v1+json'
        }
      })

Uwaga:
Na podanym wyżej adresie dostaje za każdym razem ECONRESET jednak po dodaniu proxy w axios - wszystko działa tak jak należy. 
Proxy config dodany jest zaraz po headers jako zmienna obiektowa z wartościami {
protocol: 'http',
    host: XXX,
    port: 8800
}

**Comment by Lukasz-Zurek** [comment]
@KowalczykDawid Dziękuję.

**Comment by Lukasz-Zurek** [comment]
@KowalczykDawid Problem nie powinien już występować. 

Przepraszamy za zaistniałe utrudnienia.

**Comment by KowalczykDawid** [comment]
Działa, dziękuje/
