### ISSUE TITLE
Błąd podczas próby wygenerowania przesyłki "CREDENTIALS_ID_NOT_PROVIDED"

### ISSUE THREAD

**Issue by pawelkucharskiyosi** [allegro/allegro-api#9380]
W konfiguracji umowy własnej z InPost podany jest prawidłowy token ShipX
wybrana przez kupującego metoda dostawy ma id: 2488f7b7-5d1c-4d65-b85c-4cbcf253fd93
w requeście jaki przesyłamy jest wybrane takie samo id jednak zwracana jest informacja:

"code": "CREDENTIALS_ID_NOT_PROVIDED",
      "details": "Seller didnt provide credentials for own delivery Method",
      "message": "Seller didnt provide credentials for own delivery Method",
      "path": "credentialsId",
      "userMessage": "Wybrana metoda dostawy nie obsługuje tego zamówienia"
      
      Co jest przyczyną i w jaki sposób wygenerować przesyłkę do takiego zamówienia.
      
      Poniżej cały request i respons:
 
 Request:
      
      
  {"commandId": "6c4b6232-0e24-47e6-b9f9-18e2ef82c22e",
  "input": {
    "deliveryMethodId": "2488f7b7-5d1c-4d65-b85c-4cbcf253fd93",
    "sender": {
      "name": "WORKSTYLE WORKSTYLE",
      "company": "WORKSTYLE",
      "street": "Podwale 3",
      "postalCode": "32-500",
      "city": "Chrzanów",
      "countryCode": "PL",
      "email": "info@workstyle.pl",
      "phone": "793666326"
    },
    "receiver": {
      "name": "Sara RODO",
      "company": "Sara RODO",
      "street": "RODO",
      "postalCode": "41-600",
      "city": "Świętochłowice",
      "countryCode": "PL",
      "email": "b3fvc5rsjl+d30a8675@allegromail.pl",
      "phone": "507RODO",
      "point": "SWC07M"
    },
    "referenceNumber": "WZ_638_07_2024",
    "packages": [
      {
        "type": "PACKAGE",
        "length": {
          "value": 42,
          "unit": "CENTIMETER"
        },
        "width": {
          "value": 31,
          "unit": "CENTIMETER"
        },
        "height": {
          "value": 4,
          "unit": "CENTIMETER"
        },
        "weight": {
          "value": "2.00",
          "unit": "KILOGRAMS"
        }
      }
    ],
    "labelFormat": "ZPL",
    "additionalServices": []
  }
}
{
  "commandId": "6c4b6232-0e24-47e6-b9f9-18e2ef82c22e"
}

Respons:

{
  "commandId": "6c4b6232-0e24-47e6-b9f9-18e2ef82c22e",
  "input": {
    "deliveryMethodId": "2488f7b7-5d1c-4d65-b85c-4cbcf253fd93",
    "sender": {
      "name": "WORKSTYLE WORKSTYLE",
      "company": "WORKSTYLE",
      "street": "Podwale 3",
      "postalCode": "32-500",
      "city": "Chrzanów",
      "countryCode": "PL",
      "email": "info@workstyle.pl",
      "phone": "793666326"
    },
    "receiver": {
      "name": "Sara RODO",
      "company": "Sara RODO",
      "street": "RODO",
      "postalCode": "41-600",
      "city": "Świętochłowice",
      "countryCode": "PL",
      "email": "b3fvc5rsjl+d30a8675@allegromail.pl",
      "phone": "507RODO",
      "point": "SWC07M"
    },
    "referenceNumber": "WZ_638_07_2024",
    "packages": [
      {
        "type": "PACKAGE",
        "length": {
          "value": 42,
          "unit": "CENTIMETER"
        },
        "width": {
          "value": 31,
          "unit": "CENTIMETER"
        },
        "height": {
          "value": 4,
          "unit": "CENTIMETER"
        },
        "weight": {
          "value": "2",
          "unit": "KILOGRAMS"
        }
      }
    ],
    "labelFormat": "ZPL",
    "additionalServices": [],
    "additionalProperties": {}
  },
  "traceId": "a582a94498985c1"
}
{
  "commandId": "6c4b6232-0e24-47e6-b9f9-18e2ef82c22e",
  "status": "ERROR",
  "errors": [
    {
      "code": "CREDENTIALS_ID_NOT_PROVIDED",
      "details": "Seller didnt provide credentials for own delivery Method",
      "message": "Seller didnt provide credentials for own delivery Method",
      "path": "credentialsId",
      "userMessage": "Wybrana metoda dostawy nie obsługuje tego zamówienia"
    }
  ],
  "retryAfter": 5,
  "traceId": "d37aa0791dd1ca79"
}

**Comment by Lukasz-Zurek** [comment]
We wskazanym żądaniu nie przekazujesz pola **"credentialsId"** i identyfikatora umowy własnej, który powinien się w nim znajdować, dlatego zwracamy powyższy błąd.

**Comment by pawelkucharskiyosi** [comment]
Dziękuję za odpowiedź
