### ISSUE TITLE
Proszę o aktywacje konta | sandbox

### ISSUE THREAD

**Issue by NotIdrizdi** [allegro/allegro-api#9383]
Proszę o aktywacje konta eneskaplan741 eneskaplan741@gmail.com w serwisie Allegro Sandbox

**Comment by MartaNowaczyk** [comment]
Na podanym koncie masz wybraną niepełną opcję sprzedażową. Wejdź proszę do [ustawień konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy), skorzystaj z linku, który masz na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)" i wybierz "Weryfikacja pełna". Uzupełnij dane i prześlij dowolne pliki, abym mogła aktywować to konto.

**Comment by NotIdrizdi** [comment]
Po kliknięciu "Wróć do wyboru weryfikacji" nie ma możliwości wybrania weryfikacji pełnej: 
![image](https://github.com/allegro/allegro-api/assets/158852400/381e9aa6-aab4-40c4-8d4d-cdd202641f33)

**Comment by MartaNowaczyk** [comment]
Sprawdź jeszcze proszę, czy możesz to przeprocesować przez zakładkę [Moja sprzedaż](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/panel-sprzedawcy) - tam również powinien być widoczny przycisk [aktywuj sprzedaż].

**Comment by NotIdrizdi** [comment]
W tej zakładce również nie ma tego przycisku, możesz sprawdzić czy nie ma już czasem ustawionej pełnej weryfikacji? Dodałem warunki sprzedaży, może to coś tutaj zmieniło.

**Comment by NotIdrizdi** [comment]
Wciąż dane firmy nie są zweryfikowane:
![image](https://github.com/allegro/allegro-api/assets/158852400/9cee900a-43fd-4aa9-93d3-bb3153073f73)

**Comment by MartaNowaczyk** [comment]
Czasami w tym krokowcu może to tak wyglądać po ręcznej aktywacji. Spróbuj wystawić ofertę lub [dodać aplikację](https://apps.developer.allegro.pl.allegrosandbox.pl/).

**Comment by NotIdrizdi** [comment]
Okej już działa, dzięki.
