### ISSUE TITLE
Request zakończenie aukcji allegro - Idea Erp

### ISSUE THREAD

**Issue by mvtit** [allegro/allegro-api#9387]
Dzień dobry, W ostatnim czasie zmieniliśmy system ERP, i występują pewne problemy z zakończeniem ofert które mają stan magazynowy równy 0. Aktualnie oferta nie zostaje zakończona i sprzedajemy produkt którego nie mamy. Zwróciłem się z prośbą do supportu IDEA ERP by zweryfikowali sprawę. Dostałem informację że Allegro odpowiedziało z sukcesem na reqest lecz w dalszym ciągu nie zakończyło oferty. W załączniku w pliku txt przedstawię wiadomość od specjalisty Idea Erp.

// edytowano ze względu na wrażliwe dane

**Comment by MartaNowaczyk** [comment]
Witam 8.07.2024 o godz. 19:56 oferta była aktywowana przez aplikację BaseLinker.

**Comment by mvtit** [comment]
Wszystko jasne. Dziękuje za informację.
