### ISSUE TITLE
 Rozbieżność między prowizją zwracaną przez API a tą podaną w panelu sprzedawcy

### ISSUE THREAD

**Issue by kaczmarekmilosz94** [allegro/allegro-api#9392]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

Cześć, 

mam pytanie odnośnie API naliczania prowizji: "/pricing/offer-fee-preview"
Zauważyliśmy rozbieżność między prowizją zwracaną przez API a tą podaną w panelu sprzedawcy.

Kalkulator prowizji pokazuje kwotę tożsamą z tym co przedstawia panel sprzedawcy.

Prowizja API zwraca "commisionFee" równą:  **~94 PLN (14,76%)** a w panelu sprzedawcy:   **~68 PLN (10,46%)**

payload: 
`{
  "offer": {
    "id": "14439249818",
    "external": {
      "id": "83446"
    },
    "category": {
      "id": "322022"
    },
    "parameters": [],
    "sellingMode": {
      "format": "BUY_NOW",
      "price": {
        "amount": "639.5",
        "currency": "PLN"
      },
      "minimalPrice": null,
      "startingPrice": null
    },
    "publication": {
      "status": "ACTIVE",
      "startingAt": null,
      "startedAt": "2023-10-04T13:40:37Z",
      "endingAt": null,
      "endedAt": null,
      "marketplaces": {
        "base": {
          "id": "allegro-pl"
        },
        "additional": []
      },
      "state": null
    }
  }
}`

response:
`{"commissions":[{"name":"Prowizja od sprzedaży","type":"commissionFee","fee":{"amount":"94.40","currency":"PLN"}}],"quotes":[{"name":"Wystawienie przedmiotu","type":"listingFee","fee":{"amount":"0.00","currency":"PLN"},"cycleDuration":"PT240H","classifiedsPackage":null}]}`

Problem nie dotyczy każdej oferty, ale tych (z tego co testowaliśmy) które były wcześniej promowane, ale obecnie już nie są (dla ww. oferty od zakończenia promowania minął ponad miesiąc). 
Proszę o podpowiedź czy jest coś czego nie uwzględniamy w requescie i jest to efekt zamierzony, czy może jest to problem w samym API.

Z góry dzięki :)

**Comment by PrzemyslawLukanowski** [comment]
Zgłosiłem ten przypadek do zespołu odpowiedzialnego za usługę. Wrócę z informacją, gdy uda mi się ustalić przyczyny rozbieżności.

**Comment by PrzemyslawLukanowski** [comment]
W Twoim requeście zabrakło zdefiniowania parametru "Stan" jako "Nowy". Wystarczy, że dołożysz w nim:

```
        "parameters": [{
            "id": "11323",
            "valuesIds": ["11323_1"]
        }],
```

i rozbieżności już nie będzie.

**Comment by kaczmarekmilosz94** [comment]
Dzięki za pomoc! :D Faktycznie pomogło. Mam tylko pytanie: czy ten sam parametr może być użyty dla każdej oferty, jeżeli sprzedajemy tylko produkty - stan "nowe", czy może się on różnić w zależności od np. kategorii

**Comment by PrzemyslawLukanowski** [comment]
ID tego parametru jest stałe, więc w każdej kategorii możecie użyć dokładnie tego samego fragmentu, co wkleiłem powyżej :)
