### ISSUE TITLE
Status przesyłki zwrotnej

### ISSUE THREAD

**Issue by mawa1209** [allegro/allegro-api#9398]
Witam,

Czy istnieje możliwość pobrania statusu przesyłki wysyłanej jako zwrot?
Interesuje mnie, czy przesyłka została już przekazana kurierowi. Informacje o zwrotach pobieram przez order/customer-returns, natomiast nie widzę tam nigdzie pola odpowiadającego za status przesyłki.

**Comment by MartaNowaczyk** [comment]
Witam, w polu "status" zwracamy status zwrotu, są tam dostępne wartości, dzięki którym idzie to mniej więcej określić:
CREATED, DISPATCHED, IN_TRANSIT, DELIVERED. Wszystkie statusy znajdziesz w naszej [dokumentacji](https://developer.allegro.pl/documentation#operation/getCustomerReturns).

**Comment by mawa1209** [comment]
Dziękuję za pomoc
