### ISSUE TITLE
doChangeItemFields nie powoduje żadnej zmiany

### ISSUE THREAD

**Issue by TheNutPL** [allegro/allegro-api#94]
Witam, 
Próbuję stworzyć funkcjonalność, która będzie aktualizowała cenę, ilości oraz opis danej aukcji. Korzystam z WebAPI, ale **doChangeItemFields** nie powoduje żadnych zmian. Po zalogowaniu przez WebAPI wykonywane jest kolejne zapytanie ze zmianą wartości pół, które mniej więcej wygląda tak:
`$changeItem = $soapClient->call('doChangeItemFields', array(
	'sessionId' => $sessionID,
	'itemId' => $itemID,
	'fieldsToModify' => array(array(
		'fid' => 1,
		'fvalueString' => 'Nowy tytuł aukcji'
	)),
	'previewOnly' => 0
));`
Po wykonaniu tego zapytania skrypt zwraca m.in. tablicę **changedItem** ze wszystkimi polami, w tym z tytułem, którego wartość brzmi "Starty tytuł". Nie ma żadnego kodu błędu, a tytuł nie został zmieniony na nowy.
Dodam, że aukcja jest świeża, bez dokonanych zakupów (podobno WebAPI nie pozwala na zmiany w aukcjach, w których dokonano zakupu (?))

**Comment by MaciejPotepa** [comment]
Dzień dobry

Żebyśmy mogli Ci pomóc musisz podesłać pełną treść requesta i response zapisane w pliku XML. Nie pełnimy wsparcia technicznego z poziomu języków programowania. 

Pamiętaj, że zmiany mogą być przetwarzane nawet do 60 minut. 

Co do Twojego pytania.

Za pomocą WebAPI możesz zmienić cenę tylko jeżeli oferta nie ma ofert zakupu. W przypadku gdy w ofercie były zakupy, do zmiany ceny można wykorzystać tylko REST API.

Resztę instrukcji co możesz zmienić i kiedy znajdziesz [tutaj](https://allegro.pl/pomoc/faq/jak-zmienic-szczegoly-transakcji-po-wystawieniu-oferty-PD0MKYWlKun).

**Comment by emesio** [comment]
Dzień dobry @MaciejPotepa . Mam też czasem problem z aktualizacją opisu, zatem podepnę się pod ten wątek. Tylko że mój jest ciut inny. Używam tej metody bardzo często, praktycznie zawsze działa, a problem występuje szacunkowo w ok 1-2% przypadków. Udało mi jednak namierzyć taki przypadek i wygenerować dla niego pełne requesty i response dla nich. Mógłbyś rzucić okiem?

W skrócie - miałem aukcję, której wywołanie doChangeItemFields powodowało błąd: ERR_STANDARDIZED_DESCRIPTION_INCORRECT.
W teorii banalne - błąd w strukturze nowego opisu. Pewnie teraz macie takich setki. Tylko że tenże sam opis używam w pozostałych 3000 aukcji i ona niczym się nie wyróżnia.
Dziwnie zaczyna się tu: zamknąłem tę aukcję. Wystawiłem ją ponownie. Dla nowej aukcji, wysłałem ponownie identyczny doChangeItemFields. Zadziałało.

Brzmi to dość kosmicznie. Mógłbyś rzucić okiem?

Przypadek aukcji nr 7221779206 - rzucał błąd. Request i response dla doChangeItemFields w zał.
Aukcja nowa 7257519538 - zadziałało. Request i response w zał.

[7221779206-request.txt](https://github.com/allegro/allegro-api/files/1849423/7221779206-request.txt)
[7221779206-response.txt](https://github.com/allegro/allegro-api/files/1849424/7221779206-response.txt)
[7257519538-request.txt](https://github.com/allegro/allegro-api/files/1849425/7257519538-request.txt)
[7257519538-response.txt](https://github.com/allegro/allegro-api/files/1849426/7257519538-response.txt)

**Comment by kormichu** [comment]
@emesio <kaszle><kaszle> .. session_id .. <kaszle>

**Comment by TimothyKoval** [comment]
@emesio Stawiałbym na &#8211;

PS. Zmień hasło do konta

**Comment by emesio** [comment]
@kormichu Ah, zdążyłeś odpisać. A mnie oświeciło i znalazłem błąd i myślałem że zdążę usunąć ;) Ale nie, to nie kwestia session-id, tylko innej ilość zdjęć. W doChangeItemFields było odwołanie do PHOTO_FID17, którego nie było w oryginalnej aukcji. Rozwiązanie to wysyłać zarówno opis, jak i wszystkie zdjęcia, choć to dużo więcej danych.

**Comment by emesio** [comment]
@timo hasło było tymczasowe - ale dzięki za pamięć. To nie kwestia myślnika - przechodzi poprawnie. Dzięki za tipy.

**Comment by TheNutPL** [comment]
@MaciejPotepa już wszystko jasne. Macie błąd w swojej dokumentacji.
Zgodnie z dokumentacją na stronie ( [https://allegro.pl/webapi/documentation.php/show/id,922](allegro.pl/webapi) ) zapytanie powinno wyglądać tak, a przynajmniej jego część:
`itemId' => 2303130924, 
   'fieldsToModify' => array(
      array(
         'fid' => 1,
         'fvalueString' => 'Nowy tytuł oferty',
...`
A powinno wyglądać tak:
`itemId' => 2303130924, 
   'fieldsToModify' => array('item' => array(
      array(
         'fid' => 1,
         'fvalueString' => 'Nowy tytuł oferty',
...`
W _fieldsToModify_ powinna się jeszcze znaleźć tablica _item_ w której zamieszamy pola do zmiany.

**Comment by MaciejPotepa** [comment]
@TheNutPL dzięki za uwagę. Zweryfikujemy to i poprawimy.
