### ISSUE TITLE
Zły format dla etykiety Allegro One Box, UPS - GIF zamiast ZPL

### ISSUE THREAD

**Issue by it-cewe-pl** [allegro/allegro-api#9403]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Etykiety dla przewoźnika Allegro One Box, UPS są zwracane w formacie GIF, zamiast ZPL.

endpoint: /shipment-management/label
trace-id: 5667f2bebc2f68ba

W starym endpoincie (/parcel-management/parcels/label?parcelId=[_id_]) etykiety były zawsze zwracane w poprawnym formacie ZPL.

**Comment by MartaNowaczyk** [comment]
Nie mamy takiego formatu etykiety. W logach widzę etykietę w formacie ZPL. Proszę przesłać otrzymaną etykietę.

**Comment by it-cewe-pl** [comment]
https://docs.cewe.de/s/gRJNGcrJGbxp2pB

Pod linkiem można znaleźć etykietę z One Box'a oraz, kuriera UPS.
Niestety nie potrafiłem znaleźć punktu obsługiwanego przez DPD, aby sprawdzić poprawność Allegro One Box, DPD

**Comment by MartaNowaczyk** [comment]
Etykiety są w formacie ZPL z tego co widzę, więc wygląda to na zgodne z logami i wartościami, które były wysłane podczas tworzenia przesyłki "labelFormat":"ZPL".

**Comment by it-cewe-pl** [comment]
Proszę otworzyć etykietę w edytorze tekstu. 
W jednej jest poprawny kod ZPL
^XA
^LRN
^MNY
^MFN,N
^LH10,12
....

A w drugiej jest nagłówek pliku GIF
GIF89a�...

Nie przetwarzam etykiet w żaden sposób, zapisuję bezpośrednio na dysku to co API zwróci.
Z tego co się orientuję, API UPSa zwracało (zapewne nadal to robi) etykiety w formacie GIF.

**Comment by it-cewe-pl** [comment]
![etykieta](https://github.com/user-attachments/assets/709ccca7-a8f8-4ef4-bc6e-ea1bb484c9b1)

trace-id zapytanie z zrzutu ekranu: 77fc918752d384d6
To napewno nie jest poprawny kod ZPL

**Comment by MartaNowaczyk** [comment]
Dziękuję za szczegóły, będziemy to wyjaśniać. Wrócę z informacją.

**Comment by MartaNowaczyk** [comment]
Wracam z informacją. Na sandboxie etykiety w UPS mają taki format i to nie jest błąd. Zwracamy tam sam kod kreskowy, bo takie mamy możliwości. Na produkcji dostępne są poprawne formaty ZPL i PDF.

**Comment by it-cewe-pl** [comment]
Rozumiem, dziękuję za szybką odpowiedź.
