### ISSUE TITLE
API questions on the cost of tax

### ISSUE THREAD

**Issue by lalala108** [allegro/allegro-api#9405]
Hi, I would like to ask you which interface can be used to get the taxes related to the orders that are currently deducted by the allegro platform?

**Comment by Lukasz-Zurek** [comment]
You can read the tax rate (if set in the offer) in the response for:

[GET /order/checkout-forms](https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET),
[GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation#operation/getOrdersDetailsUsingGET),

in the "lineItems[]" object, where we return an object "tax", together with these fields:

- rate - tax rate,
- subject - the subject of taxation,
- exemption - exemption from taxation.

In [our guide](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#opcje-faktury-i-stawki-vat) you can find more information about setting the tax rate in your offer.

**Comment by lalala108** [comment]
Okay, I see that the interface provides the tax rate of the corresponding product, but we still need to calculate the actual tax deduction based on the tax rate, right?

**Comment by Lukasz-Zurek** [comment]
Yes.

**Comment by lalala108** [comment]
Okay, understood. Thank you very much.
