### ISSUE TITLE
Błędna suma za wystawienie przedmiotu

### ISSUE THREAD

**Issue by wotekPL** [allegro/allegro-api#942]
Występuje problem:
 - [X] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym

Request: https://pastebin.com/D9gSqDH9
Response: https://pastebin.com/k4mgLqvT

Przy sprawdzeniu ceny za wystawienie przedmiotu z opcją promowania jako Pakiet podświetlenie, wyróżnienie, pogrubienie otrzymujemy w odpowiedzi otrzymujemy błędną cenę:

> Wystawienie przedmiotu: 0,08 zł
Opłata za wyróżnienie: 19,00 zł
Podświetlenie: 3,00 zł
Pakiet pogrubienie + podświetlenie + wyróznienie: 123,00 zł
Opłata za pogrubienie: 2,00 zł

**Comment by MartaNowaczyk** [comment]
@wotekPL dziękujemy za zgłoszenie. Sprawę przekazałam do odpowiedniego zespołu.

**Comment by wotekPL** [comment]
Czy znamy jakieś przybliżone ETA?

**Comment by MartaNowaczyk** [comment]
@wotekPL na ten moment niestety nie mamy, ale pracujemy nad tym.

**Comment by wotekPL** [comment]
Jakieś eta?

**Comment by MartaNowaczyk** [comment]
@wotekPL na ten moment mam tylko tyle, że sandbox na dzień dzisiejszy nie odzwierciedla produkcji w tym aspekcie. 
Zaznaczyłeś jednak, że takie zachowanie zauważyłeś również na produkcji, ale przykładu z produkcji nie mamy. Masz taki przykład - to podeślij proszę.
