### ISSUE TITLE
Dodawanie oferty - warunki reklamacji

### ISSUE THREAD

**Issue by bmusialekcepd** [allegro/allegro-api#9428]
witam,

tworze nowa oferte dodajc informacje o warunku reklamacji. trace-id = 70c49460d55917b
W parametrach wskazalem 008579ee-28d1-4bcb-a853-a2e2d2f9f2aa lecz w szkicu w allegro podczas edycji  7772964683 
 wskazuje na warunek  reklamacji 'default'. Prosze o analize.
![Uploading Zrzut ekranu 2024-07-16 o 12.42.05.png…]()

**Comment by bmusialekcepd** [comment]
chodzi o srodowisko sandbox

**Comment by Lukasz-Zurek** [comment]
Przekazane przez Ciebie dane zostały zignorowane (dlatego do oferty dodaliśmy warunki reklamacji oznaczone jako "default"), ponieważ wysłałeś je w nieprawidłowy sposób:

```
   "impliedWarranty":{
      "id":"008579ee-28d1-4bcb-a853-a2e2d2f9f2aa"
   }
```

Warunki reklamacji powinieneś przekazać w obiekcie **"afterSalesServices"**, np.

```
      "afterSalesServices": {
          "impliedWarranty": {
                  "id": "008579ee-28d1-4bcb-a853-a2e2d2f9f2aa"
        }
    },
```
