### ISSUE TITLE
Błąd przy checkout-forms "An error has occurred"

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#943]
Błąd jest dla zamówienia o id "49a05002-f301-11e8-bf75-a9d7a28c5475".

**Comment by MartaNowaczyk** [comment]
@aktywnitu prośba, żeby zawsze podawać jak najwięcej danych zgodnie z szablonami, które widzisz przy zakładaniu nowego tematu, może to skrócić czas weryfikacji błędu. 
Sprawdzamy twoje zgłoszenie.

**Comment by aktywnitu** [comment]
OK. Będę uzupełniał w miarę możliwości te informacje.
Tutaj być może powiązany błąd:
https://github.com/allegro/allegro-api/issues/945

**Comment by MartaNowaczyk** [comment]
@aktywnitu sprawdziliśmy i w tym przypadku to nie błąd. Klient najpierw zrobił oddzielne zakupy w różnych ofertach, a potem zapłacił wspólnie. Dostałeś w ten sposób najpierw np. dwa zamówienia z różnymi id, a gdy kupujący zapłacił za oba naraz ich id zostały zastąpione jednym - nowym.

**Comment by aktywnitu** [comment]
Dziękuję Marto za wyjaśnienie.
Szkoda, że błąd nic nam o tym nie mówi, a przydałby się do efektywnego przeglądania dziennika zdarzeń.
Pomijam zatem tego typu błędy pod warunkiem, że zamówienie nie jest READY_FOR_PROCESSING.

**Comment by MartaNowaczyk** [comment]
@aktywnitu Masz rację, błąd nie jest czytelny w żaden sposób. Zobaczymy, może uda nam się je poprawić.
