### ISSUE TITLE
Confirmation of API to get balance issue

### ISSUE THREAD

**Issue by lalala108** [allegro/allegro-api#9442]
Hi,can you tell me which interface in the API interface corresponds to which field to get the real balance data of the store? Because currently through the interface can get a lot of various balance charges, not quite clear which is the actual store balance, as shown in the screenshot.
![question](https://github.com/user-attachments/assets/c4265f00-0f71-4f91-bdc7-d0be4d8f0790)

**Comment by MartaNowaczyk** [comment]
First "Balance" from your screenshot you can find in [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries) in the "balance" field. You will also find a summary of the month ("type.id""SUM" - "Summary of the month"). The last marked thing we don't have in our API. 
For clarification one by one from the screenshot:
1. Amount of current arrears.
2. The invoice for the last month.
3. The last balance is the difference between sales and costs.

If you want to know more about this tab please write via [the contact form](https://allegro.pl/pomoc/kontakt).

**Comment by lalala108** [comment]
Okay,thank you for your response.
