### ISSUE TITLE
Logowanie do Allegro sandbox

### ISSUE THREAD

**Issue by pr0fes0rre** [allegro/allegro-api#9446]
Dzień dobry,
chciałem zalogowac się do swojego testowego konta biznesowego i przy poróbie loogwania zostałem poproszony o podanie kodu SMS z numeru telefonu jaki podałem.
Problem w tym, że przy zakłądaniu konta (pierwotnie prywatnego) podałem placeholderowy nr telefonu i nie mam możliwości dostania na niego kodu weryfikującego.

**Comment by Lukasz-Zurek** [comment]
Na środowisku testowym nie wysyłamy smsów i tu wystarczy, że wpiszesz ciąg cyfr "123456".

**Comment by pr0fes0rre** [comment]
Wpisywałem taki ciąg i dostawałem komunikat o błędnym kodzie a obecnie pojawia się: Wyczerpano limit weryfikacji kodów SMS

**Comment by Lukasz-Zurek** [comment]
@pr0fes0rre Odczekaj i ponów próbę. Testowałem przed momentem i bez problemu przepuszcza mi ciąg cyfr "123456".

**Comment by pr0fes0rre** [comment]
Potiwerdzam, udało mi się zalogować po chwili z tym ciągiem.
Dzięki za pomoc!
