### ISSUE TITLE
line-item-id-mappings  bug "An error has occurred"

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#945]
Występuje problem: 
 - [x] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Żądanie:
order/line-item-id-mappings z parametrami GET:
{
        'lineItemId': "bd0e3462-5acf-42e2-a3cd-d1c396513f90"
 }

Odpowiedź:
{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":null,"userMessage":null}]}

Dla części identyfikatorów zamówień mapowanie zwraca powyższy błąd.
Tutaj przykładowe id:
6b154a82-2ced-4220-8c18-92594ff700ec
d3909572-f02e-11e8-b8b6-d7fb51a277f5

**Comment by aktywnitu** [comment]
Chyba jednak pomyłka.
Zamykam.

**Comment by aktywnitu** [comment]
Jednak jest błąd.
Przykładowy lineItemId:
d59191d0-f22c-11e8-a3e2-dfc7643a5150

**Comment by MartaNowaczyk** [comment]
@aktywnitu dzięki, sprawdzimy obie kwestie.

**Comment by MartaNowaczyk** [comment]
@aktywnitu to nie to samo co w 943. Czy jesteś pewien, że podajesz odpowiednie id - linteItemsId.id? Wydaje mi się, że podajesz checkout-form.id.

**Comment by MartaNowaczyk** [comment]
@aktywnitu ten id d59191d0-f22c-11e8-a3e2-dfc7643a5150 powinien działać bez problemu. Sprawdź proszę swoje wywołanie.
