### ISSUE TITLE
Aktywacja konta na Allegro Sandbox

### ISSUE THREAD

**Issue by Adrian-Nowakowski** [allegro/allegro-api#9450]
Dzień dobry,
moje konto oczekuje już dłuższy czas na aktywację w Allegro Sandbox.
_(dzisiaj chciałem jeszcze raz zweryfikować, ale także nie zadziałało)_

Czy byłaby możliwość ręcznej aktywacji konta?
Adres email: piotr.doniak@upblue.pl

**Comment by Lukasz-Zurek** [comment]
@Adrian-Nowakowski Właśnie aktywowałem Twoje konto :)

**Comment by Adrian-Nowakowski** [comment]
Dzięki! Myślę, że wątek można zamknąć. :)
