### ISSUE TITLE
Stare konto na sandbox

### ISSUE THREAD

**Issue by michal-jablonsk84** [allegro/allegro-api#9458]
Hej,

kiedyś miałem konto na sandbox założone na starego maila michal.jablonski@allegro.pl 
chciałbym je odzyskać, liczyłem, że mail resetujący hasło przekieruje się z allegro.pl na allegro.com, ale raczej nie...
jak można odzyskać takiego konto?

![Zrzut ekranu 2024-07-19 132945](https://github.com/user-attachments/assets/ba615392-56ce-487d-b117-b8ce97bcd879)

**Comment by Lukasz-Zurek** [comment]
Hej!

Edytowałem Twój adres e-mail i powinno być ok :)
