### ISSUE TITLE
Aktywacja konta.

### ISSUE THREAD

**Issue by ITPKR** [allegro/allegro-api#946]
Proszę o aktywacje konta "ITPKR" w sandboxie ponieważ symulator Payu nie działa.

**Comment by MartaNowaczyk** [comment]
@ITPKR Zrobione. Aby w pełni aktywować konto firmowe musisz przejść do zakładki moje konto i wysłać do nas dokumenty do weryfikacji (jakieś dowolne 2 pliki).

**Comment by ITPKR** [comment]
Dziękuję. Załączyłem dwa dowolne pliki. Czekam na weryfikację.

**Comment by ITPKR** [comment]
Jest OK, dziękuję.

**Comment by robert-skarzycki** [comment]
Mam ten sam problem - konto `rskarzycki-ceneo`, na sandboksie.  W koncie mam wpis "Nieaktywne - trwa weryfikacja Twoich danych", a metoda WebAPI `doShowUser` zwraca mi `usernotactivated = 1`.

**Comment by PawelTaberski** [comment]
@robert-skarzycki Aktywowałem Twoje konto powinno już być ok.

**Comment by pogotowiefiskalne** [comment]
Czy mogę prosić o aktywację Allegro Finanse (chodzi o wypłaty) - PayU i Przelewy24 dla konta sello_test123

**Comment by PrzemyslawLukanowski** [comment]
@pogotowiefiskalne Aktywowałem usługę.

**Comment by urszulade** [comment]
proszę o aktywację konta na sandboxie: testyita

**Comment by PrzemyslawLukanowski** [comment]
@urszulade Odpowiedź w #6190
