### ISSUE TITLE
W tej kategorii wymagamy, aby oferty były połączone z Katalogiem produktów Allegro.

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#9463]
Jakim zasobem można pobrać informacje o tym że oferta w danej kategorii musi być powiązana z produktem?

![image](https://github.com/user-attachments/assets/aad23727-4750-4845-85c8-fb2bd6d2984c)

Allegro pozwala na publikacje takich ofert, mimo tego nie da się ich edytować. Trochę bez sensu i prowadzi do błędów. Czy jedyna opcja to analiza błędów? przydałaby się zasób w stylu /sale/product-offers/errors który zwraca błędy/problemy wszystkich ofert przed próbą jakiejkolwiek edycji/publikacji/zmiany

**Comment by MaciejFrackowiak** [comment]
Zgodnie z komunikatem, od 1 lipca 2024 wymagamy, aby wszystkie oferty były połączone z [Katalogiem Produktów](https://help.allegro.com/sell/pl/a/od-dzis-wymagamy-aby-wszystkie-oferty-byly-polaczone-z-katalogiem-produktow-allegro-oAaO1ZyR9S0). Nie przewidujemy dodawania żadnego osobnego endpointu do obsługi masowej błędów. Dla każdej oferty z osobna otrzymujesz pełną listę błędów podczas walidacji danej oferty.
