### ISSUE TITLE
Jak pobrać limit ofert tego samego produktu danej kategorii?

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#9464]
Niektóre kategorie pozwalają na wystawienie 5 ofert na jednym koncie z tym samym produktem. Skąd można pobrać te limity? Jest jakiś zasób gdzie podaje się categoryId i zwraca limit?

**Comment by MaciejFrackowiak** [comment]
Nie, takiej informacji w API nie zwracamy. Pod [linkiem](https://assets.allegrostatic.com/popart-attachments/att-1cb79e2e-ff1f-4358-83e0-db2789881774) znajdziesz listę kategorii objętych limitem.
