### ISSUE TITLE
API Production

### ISSUE THREAD

**Issue by travisalicesgarden** [allegro/allegro-api#9467]
Hi, 

I'm contacting you because we still can't generate the api key for our production account. 
Can you help us? 
This is the **sweeek** account

Thanks for your support

**Comment by MaciejFrackowiak** [comment]
To create an application you have to activate [two-factor authentication](https://help.allegro.com/sell/en/a/what-is-two-factor-authentication-and-why-you-should-use-it-x5KbM72MvF6) on your account.

**Comment by travisalicesgarden** [comment]
<img width="689" alt="image" src="https://github.com/user-attachments/assets/833e8917-adc2-4c33-b65c-34a9fdde745e">

I get this message, it's impossible to move on to the next step

**Comment by MaciejFrackowiak** [comment]
Just activate an option [here](https://allegro.pl/moje-allegro/moje-konto/dwustopniowe-logowanie).

**Comment by travisalicesgarden** [comment]
It's ok!
thanks for your support
