### ISSUE TITLE
set "Wznawianie oferty" flag by REST-API

### ISSUE THREAD

**Issue by Folganoid** [allegro/allegro-api#947]
Hi. There is a question: How I can switch ON the "Wznawianie oferty" flag by REST-API? Thanx :)

**Comment by MartaNowaczyk** [comment]
Hi. You can read about it [here](https://developer.allegro.pl/en/my_offers/#6) in English of course :)

**Comment by premax** [comment]
> Hi. You can read about it [here](https://developer.allegro.pl/en/my_offers/#6) in English of course :)

To nie jest odpowiedź na pytanie. Pod podanym linkiem nie ma nic na temat opcji "automatycznie wznów ofertę po zakończeniu", jest tylko o ręcznym (przez API) wznawianiu ofert, które się już zakończyły. Przedmówcy, jak i mi, chodzi o tę opcję: 

![image](https://user-images.githubusercontent.com/1401870/53269549-73d30580-36e9-11e9-9f3a-3b62abfae65a.png)

**Comment by MartaNowaczyk** [comment]
@premax nie ma takiej opcji w REST API i nie planujemy jej dodawać. Najlepiej korzystać z ofert "do wyczerpania przedmiotów" lub wznawiać je po jej zakończeniu.
