### ISSUE TITLE
Czech sandbox, account activation

### ISSUE THREAD

**Issue by Maremic** [allegro/allegro-api#9474]
Hello, 
I am new to allegro, trying to connect our Laravel eshop to your API 
as I found in different post here, 
I created account on czech version of sandbox, with fake credentials
as mentioned here => 
 https://github.com/allegro/allegro-api/issues/7250 

in next step they are mentioning payment simulation to finich process, 
but I cant found it anywhere

My account name should be AntAvion

Thanks a lot,
Mareš Michal

**Comment by AureliuszBrussy** [comment]
@Maremic I have activated your account.

**Comment by Maremic** [comment]
@AureliuszBrussy  Thank you very much ! 
for futher testing can be that payment simulator found anywhere to test payments ?

**Comment by AureliuszBrussy** [comment]
When placing an order, the payment simulator should work properly.
