### ISSUE TITLE
Aktywacja konta na allegro sandbox

### ISSUE THREAD

**Issue by bmusialekcepd** [allegro/allegro-api#9475]
witam, 

prosze o aktywacje konta patrycja.orczykowska@cepd.tech. Link aktywacyjny nie dziala

**Comment by AureliuszBrussy** [comment]
Proszę o ponowną próbę rejestracji i próbę skorzystania z linku aktywacyjnego. W tej chwili nie odnotowujemy problemów z rejestracją konta. 

Jeżeli link aktywacyjny nie działa - co dokładnie się dzieje po wejściu w odnośnik?
