### ISSUE TITLE
[401] /sale/product-offers pomimo tego ze token zadzialal na poprzednim endpoincie

### ISSUE THREAD

**Issue by drpartsallegro** [allegro/allegro-api#9476]
Otrzymuje 401 blad w ponizszym endpoincie, token uzywany wczesniej przy https://api.allegro.pl/sale/products?ean=433289-5116 i nie bylo problemu.

`https://api.allegro.pl/sale/product-offers`
`Request Body: {'productSet': [{'product': {'id': '48b575ee-c066-4825-ac4e-31f7d10733c3'}}], 'sellingMode': {'price': {'amount': '1000', 'currency': 'PLN'}}, 'stock': {'available': 1}, 'publication': {'status': 'ACTIVE'}}`

`Response: {"errors":[{"code":"AccessDeniedException","message":"Unauthorized","details":null,"path":"","userMessage":"Failed to authenticate query.","metadata":{}}]}`

Aplikacja ma pozwolenie na wszystko; konto ma pozwolenie na wystawianie ofert i jest zweryfikowane i ma 2 stopniowe logowanie

**Comment by MaciejFrackowiak** [comment]
Korzystasz z autoryzacji typu client_credentials, a [zasób](https://developer.allegro.pl/documentation/#operation/createProductOffers) wymaga autoryzacji typu "[bearer-token-for-user](https://developer.allegro.pl/documentation/#section/Authentication/bearer-token-for-user)", czyli [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow.

**Comment by drpartsallegro** [comment]
Dzieki za szybka odpowiedz, zgadza sie.
