### ISSUE TITLE
Problem z tworzeniem offert przez API 

### ISSUE THREAD

**Issue by Stalkies** [allegro/allegro-api#9487]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy próbie utworzenia oferty ze statusem INACTIVE, czyli jako szkic, pojawia się błąd walidacji. Jeszcze wczoraj skrypt działał w pełni i od tego czasu nie zmieniałem nic w zapytaniu.
trace-id = 7bda718aff7714ae

**Comment by AureliuszBrussy** [comment]
Aktualnie zwracamy error zgodnie z oczekiwaniami (o braku zdjęcia), natomiast pracujemy nad możliwości utworzenia szkicu bez tej walidacji produktu. Na chwilę wdrożyliśmy taką zmianę, natomiast przyniosła nieoczekiwane efekty, przez co musieliśmy wycofać tą wersję.

**Comment by Stalkies** [comment]
Jak szybko zostanie to naprawione?

**Comment by AureliuszBrussy** [comment]
Jeszcze upewnię się, czy ta konkretna zmiana, którą mam na myśli faktycznie mogła wpłynąc na Twój problem: 
kiedy dokładnie zauważyłeś zmianę w zachowaniu przy tworzeniu szkiców? Od kiedy miałeś zaimplementowane to rozwiązanie z działaniem na szkicach? Czy masz jakiś przykład trace-id, czy np. id szkicu, gdzie wcześniej udaje się utworzyć szkic z tymi minimalnymi danymi?

**Comment by Stalkies** [comment]
Nic nie zmieniałem w zapytaniach. W poniedziałek wszystko działało. Wszystkie offerty co tworzyłem usuwałem więc nie mam id szkicu.

**Comment by Stalkies** [comment]
Zauważyłem również, że podczas tworzenia szkiców przez stronę Allegro, a nie przez API, używany jest stary endpoint post **/sale/offers**. Jeśli go używam, wszystko działa świetnie, jednak istnieje kilka istotnych minusów:

1. Nie mogę używać obrazów, które nie znajdują się na serwerze Allegro, i muszę wykonywać dodatkowe żądanie, aby załadować obrazy.
2. Niemożność wykonywania wielu żądań na minutę (jak to było w przypadku aktualnego endpointu **/sale/product-offers**).


Przypuszczam, że problem pozostał niezauważony, ponieważ na stronie internetowej używany jest przestarzały (niezepsuty obowiązkową walidacją) sposób API. W obecnej sytuacji niemożliwe jest stworzenie oferty w szkicach, korzystając z aktualnych metod API.

**Comment by AureliuszBrussy** [comment]
@Stalkies jest możliwe utworzenie oferty w szkicach, natomiast po zwalidowaniu produktu. Faktycznie formularz na stronie korzysta jeszcze ze starszych zasobów, natomiast to niebawem się zmieni. Tak jak wspomniałem w innym wątku - po dopracowaniu wprowadzimy zmianę, która pozwoli na utworzenie szkicu bez próby utworzenia produktu na nowych zasobach.

**Comment by Stalkies** [comment]
Super. Bardzo czekam na ta zmiane

**Comment by Stalkies** [comment]
W takim przypadku pojawia się problem. Korzystając z Allegro API mogę stworzyć ofertę używając starego API w piaskownicy, ale główne API już nie wspiera tej funkcji. To może mocno zdezorientować programistę, ponieważ u niego wszystko będzie działać, ale nie u klienta. Można albo wyłączyć tę funkcję w piaskownicy również, albo na czas, gdy nie ma alternatywy, włączyć ją do tworzenia ofert bez walidacji.

**Comment by AureliuszBrussy** [comment]
Tutaj mamy do czynienia tylko z jednym z wielu use case'ów, który w żaden sposób nie blokuje całego flow wystawiania oferty produktu. Na ten moment nie wprowadzimy żadnych zmian. Tak jak wspomniałem, niebawem formularz całkowicie przestanie korzystać z wygaszonych zasobów, i wprowadzimy zmianę, która umożliwi utworzenie szkicu dla takiego konkretnie przypadku (bez próby tworzenia produktu).
