### ISSUE TITLE
Zmiana cen Kup teraz w zaplanowanych.

### ISSUE THREAD

**Issue by kris86k** [allegro/allegro-api#949]
Witam.
Dlaczego change-price-commands nie zmienia ceny Kup teraz w zaplanowanych ofertach?
Z tego co pamiętam w starym api to działa bez problemu.
Czy to jest błąd czy zaplanowane działanie?
Czy jest inna metoda w REST pozwalająca na zmianę ceny w zaplanowanych?

Zmieniam swoje prywatne skrypty na REST i teraz muszę łączyć stare api z nowym co jest z założenia bez sensu...

Czy ofertę zaplanowaną i trwającą mogę zakończyć jedną metodą czy muszę używać dwóch?

Pozdrawiam,
Krzysiek.

**Comment by MartaNowaczyk** [comment]
@kris86k zmiana ceny w zaplanowanej ofercie przez change-price-commands powinna być możliwa. Sprawdzałam przed chwilą i nie miałam problemu, aby zmienić cenę i liczbę przedmiotów w takiej ofercie.
Aby zakończyć ofertę zaplanowaną i trwającą skorzystaj z metody /sale/offer-publication-commands/{commandId} dodając do tablicy "offers" numery ofert.
