### ISSUE TITLE
Bład podczas dodwania oferty

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#9493]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Podczas próby utworzenia oferty przez POST /sale/product-offers 

```
{"stock":{"available":"1","unit":"UNIT"},"delivery":{"shippingRates":{"id":"53381d05-0b64-44f7-aab5-da316df5cbf9"},"handlingTime":"PT24H"},"publication":{"duration":null,"status":"INACTIVE"},"language":"pl-PL","category":{"id":"55203"},"parameters":[{"id":"64","valuesIds":["64_2"]},{"id":"3766","valuesIds":["3766_1"]},{"id":"7108","valuesIds":["7108_284513"]},{"id":"11323","valuesIds":["11323_1"]},{"id":"15851","valuesIds":["15851_1"]},{"id":"22728","valuesIds":["22728_1"]},{"id":"203509","valuesIds":["203509_217217"]},{"id":"219629","valuesIds":["219629_286869"]},{"id":"249512","valuesIds":["249512_1647414"]},{"id":"26388","valuesIds":["26388_4096"]},{"id":"203093","values":["23"]},{"id":"224017","values":["N-2410-KRCZ-30CR-0-38"]},{"id":"225693","values":["978020137962"]}],"afterSalesServices":{"impliedWarranty":{"id":"8a860b38-9f18-4063-ac53-04508cab90f7"},"returnPolicy":{"id":"76af87bb-db68-4473-8b5a-964b4192ec2f"}},"name":"Traper - ROZMIAR 38","payments":{"invoice":"VAT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":"269.00","currency":"PLN"}},"location":{"countryCode":"PL","province":"MAZOWIECKIE","city":"Warszawa","postCode":"98-765"},"images":["https:\/\/a.allegroimg.allegrosandbox.pl\/original\/113dff\/3052c117473db3ad5dc327c7079b"],"description":{"sections":[{"items":[{"type":"TEXT","content":"

ble ble ble<\/p>"}]}]},"external":{"id":"N-2410-KRCZ-30CR-0-38"}}
```
W odpowiedzi dostaję: Parameter '64:Materiał zewnętrzny' should not be specified as in section 'offer'.
Tylko że parametr 64 jest ustawiany ```"parameters":[{"id":"64","valuesIds":["64_2"]}, ... ```

Mam wątpliwości czy o to chodzi bo komunikat mówi o sekcji 'offer', a  w /sale/product-offers  nie ma takiej sekcji więc domyślam się ze chodzi o sekcje parameters.

**Comment by MartaNowaczyk** [comment]
Parametr "64" ma opcję "describesProduct": true, czyli powinien znaleźć się w części produktowej `productSet.parameters`. Więcej znajdziesz w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem).
