### ISSUE TITLE
Oferta - pole republish a reczna zamkniecie aukcji

### ISSUE THREAD

**Issue by bmusialekcepd** [allegro/allegro-api#9497]
witam,

mam pytanie o mechanizm działania flagi republish na ofercie.

Przypadek:

1. Zakładam ofertę z flafa repubslih=true oraz duration=null(do wyczerpania zapasów)
2. W miedzyczasie zmieniam status oferty przez API https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#zmiana-statusu-oferty na 'ENDED'. Stan produktu dalej jest wiekszy od 0
3. Pytanie czy przez flage republish allegro bedzie probowalo wznowic aukcje? Allegro rozroznia czy aukacja zostala zamknieta przez brak stocku czy przez klienta? Wznawia aukcje tylko jezeli byla zamknieta przez brak stocku a potem stock został uzupełniony?

**Comment by AureliuszBrussy** [comment]
Oferta wznowi się (jako nowa oferta, z nowym id) w przypadku wyprzedania lub po zakończeniu czasu trwania. W przypadku wysłania ENDED do takiego wznowienia nie dojdzie.
