### ISSUE TITLE
doNewAuctionExt - częste błędy API

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#95]
Witam serdecznie,

Proszę o naprawę mechanizmu wystawiania aukcji (doNewAuctionExt), gdyż metoda często zwraca: Error Fetching http headers i ERR_INTERNAL_SYSTEM_ERROR - w tle czasami wystawia BEZWIEDNIE aukcje...

Zgłaszany problem często występuje, już od kilku lat i nadal nie został naprawiony.
Wielokrotnie były wysyłane do Państwa paczki XML.

**Comment by AniaMalinowska** [comment]
Problem wynika z tego, że requesty dotyczące ofert są czasem długo przetwarzane. 
Planujemy rozwiązać ten problem w architekturze REST.

**Comment by samilmarekrygula** [comment]
Dokładnie ten sam problem mam cały czas od długiego czasu. 

zapytania wychodzą z domeny zmienolej.pl

**Comment by samilmarekrygula** [comment]
@PawelTaberski wysłane, ale podałeś numer 96, więc też tak podałem w formularzu kontatkowym, a chyba miało być 95.

**Comment by PawelTaberski** [comment]
@samilmarekrygula Dokładnie tak miało być 95 :-) ale spokojnie będę pamiętał :-), jak tylko otrzymam dane to zweryfikujemy w czym jest problem.
