### ISSUE TITLE
Kod produktu

### ISSUE THREAD

**Issue by KamZal** [allegro/allegro-api#950]
Witam, kiedy będzie możliwość edycji "kodu produktu" dla trwających ofert przez API?

<img width="967" alt="shot_181202_172419" src="https://user-images.githubusercontent.com/45545759/49346868-b7911280-f698-11e8-965d-b8e176a4247e.png">

**Comment by MartaNowaczyk** [comment]
Kod produktu to dodatkowy parametr, którego dotyczą te same zasady co reszty parametrów. Możesz go bez problemu [zmienić](https://developer.allegro.pl/my_offers/#2) przy pomocy REST API (ID parametru 219809).
