### ISSUE TITLE
Aktywacja konta sandbox: brzostowski-dev

### ISSUE THREAD

**Issue by brzostowski** [allegro/allegro-api#9501]
Czy mógłbym prosić o aktywację konta na sandbox: brzostowski-dev?

oraz chciałbym się zapytać czy salescenter jest dostępny w wersji sandbox?

**Comment by MartaNowaczyk** [comment]
Aktywowałam twoje konto.
https://salescenter.allegro.com.allegrosandbox.pl/

**Comment by brzostowski** [comment]
Super, dzięki wielkie
