### ISSUE TITLE
Authentication for POST

### ISSUE THREAD

**Issue by Maremic** [allegro/allegro-api#9504]
Hi, I am connecting API to our laravel project,
account name Antavion 
I am maybe just confused in some process but stuck for while on it, so I will ask 

```
public function __construct()
    {
        // allegro.pl.allegrosandbox.pl
        //api.allegro.pl.allegrosandbox.pl
        $this->client = new Client(['base_uri' => 'https://api.allegro.pl.allegrosandbox.pl']);
    }

    private function getToken()
    {
        if (Cache::has('allegro_token')) {
            return Cache::get('allegro_token');
        }

        $response = $this->client->post('https://allegro.pl.allegrosandbox.pl/auth/oauth/token', [
            'form_params' => [
                'grant_type' => 'client_credentials',
                'client_id' => env('ALLEGRO_CLIENT_ID'),
                'client_secret' => env('ALLEGRO_CLIENT_SECRET'),
                // 'redirect_uri' => env('ALLEGRO_REDIRECT_URL'),
            ],
            'headers' => [
                'Authorization' => 'Basic ' . base64_encode(env('ALLEGRO_CLIENT_ID') . ':' . env('ALLEGRO_CLIENT_SECRET')),
            ],
        ]);

        $tokenData = json_decode($response->getBody()->getContents(), true);
        Cache::put('allegro_token', $tokenData['access_token'], $tokenData['expires_in']);

        return $tokenData['access_token'];
    }
    
    private function makeRequest($method, $uri, $options = [])
    {
        $options['headers'] = [
            'Authorization' => 'Bearer ' . $this->getToken(),
            'Accept' => 'application/vnd.allegro.public.v1+json',
            'Accept-Language' => 'en-US',
            'Content-Type' => 'application/vnd.allegro.public.v1+json',
        ];

        // dd($options);

        try {
            $response = $this->client->request($method, $uri, $options);
            return json_decode($response->getBody()->getContents(), true);
        } catch (ClientException $e) {
            // Extract detailed error response
            $responseBody = $e->getResponse() ? $e->getResponse()->getBody()->getContents() : 'No response body';
            return [
                'error' => $e->getMessage(),
                'response' => $responseBody
            ];
        } catch (RequestException $e) {
            // Handle other request-related exceptions
            $responseBody = $e->getResponse() ? $e->getResponse()->getBody()->getContents() : 'No response body';
            return [
                'error' => $e->getMessage(),
                'response' => $responseBody
            ];
        }
    }
```
    
    this is my code for handling token and auth, 
    its working properly for getting categories Ids as 
    
   ```
 public function getCategoriesId() //OK
    {
        return $this->makeRequest('GET', '/sale/categories');
    }
    
    or getting category by ID and so on 
    but when I am trying to post some test product it result in 
    
    [
    "error" => """
      Client error: `POST https://api.allegro.pl.allegrosandbox.pl/sale/product-offers` resulted in a `401 Unauthorized` response:\n
      {"errors":[{"code":"AccessDeniedException","message":"Unauthorized","details":null,"path":"","userMessage":"Failed to au (truncated...)\n
      """,
    "response" => "{"errors":[{"code":"AccessDeniedException","message":"Unauthorized","details":null,"path":"","userMessage":"Failed to authenticate query.","metadata":{}}]}",
  ]
```
  
  which little confused me cuz for GET requests I dont get 401 at all 
  
  ```
public function createProductOffer(array $json = null)
    {
        if (!$json && App::isLocal()) {
            // Test data
            $json = [
                'productSet' => [
                    [
                        'product' => [
                            'id' => '5902719471797',
                            'idType' => 'GTIN'
                        ]
                    ]
                ],
                'sellingMode' => [
                    'price' => [
                        'amount' => '220.85',
                        'currency' => 'PLN'
                    ]
                ],
                'stock' => [
                    'available' => 10
                ],
                'publication' => [
                    'status' => 'INACTIVE'
                ]
            ];
        } else {
            return false;
        }

        return $this->makeRequest('POST', '/sale/product-offers', [
            'json' => $json
        ]);
        
    }
```
    
    I am trying to send simple data for testing, I am maybe sending json badly, but I tried it for while with same results 
    
    also  i tried change $this->client = new Client(['base_uri' => 'https://api.allegro.pl.allegrosandbox.pl']);
    to "https://allegro.pl.allegrosandbox.pl", which resulted in CAPTCHA 403
    
    or maybe I should use different type of auth ? but in other our apis we are using oAuth token normaly
    
    Thanks for any answers

**Comment by Maremic** [comment]
"json" => array:4 [
    "productSet" => array:1 [
      0 => array:1 [
        "product" => array:2 [
          "id" => "5902719471797"
          "idType" => "GTIN"
        ]
      ]
    ]
    "sellingMode" => array:1 [
      "price" => array:2 [
        "amount" => "220.85"
        "currency" => "PLN"
      ]
    ]
    "stock" => array:1 [
      "available" => 10
    ]
    "publication" => array:1 [
      "status" => "INACTIVE"
    ]
  ]
  "headers" => array:4 [
    "Authorization" => "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOmZ1bGZpbGxtZW50OnJlYWQiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOndyaXRlIiwiYWxsZWdybzphcGk6ZnVsZmlsbG1lbnQ6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6YmlkcyIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpzaGlwbWVudHM6d3JpdGUiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCIsImFsbGVncm86YXBpOnNoaXBtZW50czpyZWFkIiwiYWxsZWdybzphcGk6bWVzc2FnaW5nIl0sImFsbGVncm9fYXBpIjp0cnVlLCJpc3MiOiJodHRwczovL2FsbGVncm8ucGwuYWxsZWdyb3NhbmRib3gucGwiLCJleHAiOjE3MjE5NDMwNjUsImp0aSI6ImU1YzA1ZTA3LTRlODUtNDZhNC1iZmJiLTE5NzZkZDc3ODJiMyIsImNsaWVudF9pZCI6IjhmYjRiMzcxYTA1ODRjZGJiNzI0ZjY5YmFkMmE4ZmY1In0.NVOzSDvsBnViPI_JqHO37jMcfQqGlVTBUMDK6FvkG4zO4TVkxf2L_A5mngBVYJK-YjWyRQt9gK-TdbrxwlBpBp-OCMhAJubfvaQ3RxOpC6rjSVTyRwG7JZ70a1y9dIuqihgRSPf59HFuA2QMaVcfYfJzP_O-0nxSQX0ugUGfqvC-IDP4lcvXRizA29iJru23vAkEYTD7wk0mHno4U8qk-udASuNTIP4YeDr54jKqQycmMHW1qC06o70yZjQnQbYOC5Z9A7kQdqMzcEI09oK85AKKzzhDoz74dqCri56d9ATdRQYSdZotZ9LoCZyiGlYJedS-UXH0JSPbhoaNNE9vA6q3ykkDQ-Ggh2knk6b9s1yjtSbDf9t5-dObGIxfvCXuSlBQVqv8-BEtehs5EXvmM88ByBjxLOs081U4Sf_1N7LV8qBXOUjtQAZC9R5G0GZHEL11fqQ2EUZQNHUVEkEgZMPB72SoHDzFH0x2u5v-VjiNVK9qa46PyzjRlqPmJj29ilACP69Nm7tg4vhZH4w28IsyxnFVEkReWQoMQZoVh9Zo0iS8VI1cyF7xXOj14Ugq9pmd0ay7EEh9cply7UYvC4xsbn6jm6awFZGD_Q-tRh8NUWFwmy0rtw-fPeGGypjeVp1DiAUq_bvx4hSwxuPnMGPoga0ymG7UYsygaC0s3f4"
    "Accept" => "application/vnd.allegro.public.v1+json"
    "Accept-Language" => "en-US"
    "Content-Type" => "application/vnd.allegro.public.v1+json"
  ]
]

this is how dd($options) looks like in post request

**Comment by MartaNowaczyk** [comment]
I see that you are using client_credentials type of authorization. To have access to resources that are marked as "bearer token for user" in our documentation (e.g. POST /sale/product-offers which you have been trying to use) use [code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow.

**Comment by MartaNowaczyk** [comment]
The token provided confirms that it has no user context.

**Comment by Maremic** [comment]
ok its working, how often I need manualy get that token ? I need only server to server communication with no user inputs, 
how long will this access token last? (I used device flow), is code flow better for my needs ?

**Comment by Maremic** [comment]
I did not refresh token with access one, maybe if that can happen to auto refreshing access token without need of manual interactions ?

**Comment by MartaNowaczyk** [comment]
The basic access token (access_token) is valid for 12 hours. In order to ensure that a user is not obliged to perform application authorization twice a day, we also make it possible to refresh tokens by refresh_token which is used to obtain a new access token for the user in a transparent way (without user actions). Such a token is valid for 3 months and after first refresh, you can use it for another 60 seconds.
Thanks to so-called renewable token lifetime, each time you use the refresh token, you will receive a new pair - access token (valid for another 12 h) and refresh token (valid for another 3 months).
You can find more about authorization in our [tutorial](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY).
