### ISSUE TITLE
Opóźnienia w działaniu API 03.12.2018?

### ISSUE THREAD

**Issue by Uriziel01** [allegro/allegro-api#951]
Występuje problem: 
 - [X] inny

:beetle: **Opis**
Czy w dniu dzisiejszym występują jakiekolwiek problemy z wydajnością REST API? Mamy potworne opóźnienia w przetwarzaniu request'ów przez API.

**Comment by PawelTaberski** [comment]
Co to znaczy duże opóźnienia tzn ile ms? I na jakich metodach to zaobserwowałeś?

**Comment by Uriziel01** [comment]
Nie chodzi o żadną konkretną metodą, raczej o wszystkie zapytania wykonywane na API w dniu dzisiejszym (a także wczoraj w nocy), ale możliwe że problem leży po stronie naszej infrastruktury serwerowej, analizujemy właśnie problem po naszej stronie.

**Comment by PawelTaberski** [comment]
Po naszej stronie nie widzę, żadnych niepokojących opóźnień.

**Comment by PawelTaberski** [comment]
@Uriziel01 Właśnie dostałem informacje, że może występować opóźnienie czasowe w przetwarzaniu ofert i odświeżaniu danych.

**Comment by Uriziel01** [comment]
Nie wiem czy mówimy o tym samym problemie, ale czy wiadomo do kiedy takie problemy mogą występować?
