### ISSUE TITLE
[sandbox] Użytkownik z blokadą nałożoną na konto nie może zgłaszać nowych propozycji utworzenia produktu

### ISSUE THREAD

**Issue by gkopec** [allegro/allegro-api#9511]
Czy można prosić o odblokowanie konta sandbox **kuba_test**? Przy próbie wystawienia dostaję błąd

```
"Could not save offer Reason: {"errors":[{"code":"SellerAccountWithSellBlockadeException","message":"Product proposals unauthorized according to blockade on user's account.","details":null,"path":"productSet[0].product","userMessage":"Użytkownik z blokadą nałożoną na konto nie może zgłaszać nowych propozycji utworzenia produktu.","metadata":{}}]}"
```

**Comment by MartaNowaczyk** [comment]
Odblokowałam konto kuba_test.

**Comment by gkopec** [comment]
@MartaNowaczyk bardzo dziękuję. Mam tu jeszcze jedno zablokowane **INVENTO_TEST**, czy możesz pomóc?

**Comment by MartaNowaczyk** [comment]
Pewnie :) Zrobione.

**Comment by gkopec** [comment]
@MartaNowaczyk wielkie dzięki. Czy to nasza wina, można tego uniknąć w przyszłości?

**Comment by MartaNowaczyk** [comment]
To finansowa blokada sprzedaży, którą czasem nawet po uregulowaniu należności na sandboxie musimy ręcznie zdjąć. To bardzo rzadkie przypadki.
