### ISSUE TITLE
Sandbox Account activation

### ISSUE THREAD

**Issue by xmarti13** [allegro/allegro-api#9514]
Good afternoon,

would it be possible to activate the sandbox account tweb_testshop?

Best regards

PM

**Comment by MartaNowaczyk** [comment]
Proszę dokończ proces rejestracji wykonując przelew weryfikacyjny (poprzez symulator płatności) oraz przesyłając dowolne pliki jako dokumenty firmowe. Zrobisz to w zakładce [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by xmarti13** [comment]
Hi,

it is not unfortunatelly possible.
If I click on Edit company details, the error appears:

Account details

Something went wrong. Try again later.


I've tried it at https://allegro.cz.allegrosandbox.pl/moje-allegro/muj-ucet/udaje-uctu/zmenit-udaje-o-spolecnosti and https://salescenter.allegro.com.allegrosandbox.pl/account/data/change-company-data
Both the same error result. So I can't do anything more with it.

Best regards

Pavel

**Comment by MartaNowaczyk** [comment]
Can you check in another browser, or even on another computer? Sometimes language settings, automatic translations, or computer security can mess things up here. If that doesn't help please send a screenshot with the error.

**Comment by xmarti13** [comment]
I've tried the operation on another browser (never used for Allegro before) and then on another computer.
In both case the same - after the clicking on link Edit company details, the error report appears only.
And if I want to Activate the selling, after click on Choose in the box Sell and buy the error Try again later apears too.
Both screens attached
![screen-allegro-01](https://github.com/user-attachments/assets/83bc3738-9f64-4354-aa02-7da2e80d071f)
![screen-allegro-02](https://github.com/user-attachments/assets/4c5daad3-1555-4330-ad67-e400dfb337c0)

**Comment by kerstinek** [comment]
Cześć, też mam problem z aktywacją konta: TadeuszSales

**Comment by MaciejFrackowiak** [comment]
@xmarti13 Please, use a direct link: https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty

**Comment by MaciejFrackowiak** [comment]
@kerstinek Konto już jest aktywne.

**Comment by Sellen236x** [comment]
Hi

Can you please activate sandbox account: sellen
basic platform should be allegro.cz

Thank you

**Comment by PrzemyslawLukanowski** [comment]
@Sellen236x Hi, I've activated your account.

**Comment by PrzemyslawLukanowski** [comment]
It seems you are trying to log in to allegro.pl website instead of allegro.pl.allegrosandbox.pl.

**Comment by xmarti13** [comment]
Hi, I was few days out of office and now I'd like to finish registering the sandbox.
Today the selection between buy+sell / buy only worked, so I made a payment in payment simulator. 
Now the registration is waiting:
We are waiting for confirmation of the bank account by the payment verifier

So this is the point, you can activate our accout?

Thank you

**Comment by AureliuszBrussy** [comment]
I have activated your account.

**Comment by xmarti13** [comment]
> I have activated your account.

Great, thank you. It seems working now.
