### ISSUE TITLE
Price change command status COMMAND_OUTDATED

### ISSUE THREAD

**Issue by promsters** [allegro/allegro-api#9517]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Ceny na aukcjach zmieniamy hurtowo na wszystkich marketplace'ach jednocześnie wykonujac osobne priceChangeCommand per marketplace.

Od kilku dni widzimy dużą ilość odrzuconych commandów z tytułowym błędem.

Poniżej przesyłam przykład z dzisiaj:

Command dla marketplace PL:
commandId: `ffd85e35-0ed0-43e8-973d-f36203c47e2c`
traceId: `98029568b3ee160`
`
{"offerCriteria":[{"offers":[{"id":"14680781052"}],"type":"CONTAINS_OFFERS"}],"modification":{"type":"FIXED_PRICE","marketplaceId":"allegro-pl","price":{"amount":"260.62","currency":"PLN"}}}
`

Command dla marketplace CZ:
commandId: `c5e2211b-f76f-4d4e-9353-a8a19e9cbfdd`
traceId: `271c4f3ba7b5be70`
`
{"offerCriteria":[{"offers":[{"id":"14680781052"}],"type":"CONTAINS_OFFERS"}],"modification":{"type":"FIXED_PRICE","marketplaceId":"allegro-cz","price":{"amount":"1546","currency":"CZK"}}}
`

Command dla marketplace SK:
commandId: `dc7457de-ee09-4f73-973e-bab1b168b35e`
traceId: `5d9ac80c07dffdcd`
`
{"offerCriteria":[{"offers":[{"id":"14680781052"}],"type":"CONTAINS_OFFERS"}],"modification":{"type":"FIXED_PRICE","marketplaceId":"allegro-sk","price":{"amount":"72.51","currency":"EUR"}}}
`

Błędny status pojawił się tylko dla commanda na marketplace allegro cz.

Z góry dzięki za odpowiedź.

**Comment by MaciejFrackowiak** [comment]
Problem generują wykonywane przez Ciebie podwójne requesty dla tych samych rynków.
Przykładowo, wywołanie commandId=c5e2211b-f76f-4d4e-9353-a8a19e9cbfdd zakończyło się błędem, ponieważ niecałą minutę wcześniej wysłałeś identyczny request z commandId=37811df1-dda4-4b42-b1b0-fdd2d5720f9a, również dla allegro-cz. Pierwotny request jeszcze nie przetworzył się, a już wysłałeś zdublowany.

**Comment by promsters** [comment]
@MaciejFrackowiak Dzięki za trop. W logach faktycznie udało nam się odszukać te zdublowane commandy i działamy nad poprawką.
