### ISSUE TITLE
aktywacja konta sandbox

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#952]
Bardzo proszę o aktywację konta kobietakoala na sandbox. Z góry dziękuje.

**Comment by PawelTaberski** [comment]
@martacronic Aktywowałem, konto powinno już być aktywne.

**Comment by martacronic** [comment]
Dziękuję bardzo i miłego dnia.

**Comment by PawelTaberski** [comment]
@martacronic Również :-)
