### ISSUE TITLE
Kurier DHL pobranie - brak usługi

### ISSUE THREAD

**Issue by Wojtu204** [allegro/allegro-api#9525]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Proszę o weryfikację poprawności działania API dla zasobu:
https://api.allegro.pl/shipment-management/delivery-services

Lista dostępnych usług nie zawiera Kurier DHL pobranie (umowa własna) - ID usługi: 8de8c002-9f06-4e91-b8bc-aebcae3b9fe7.
Umowa jest zdefiniowana w panelu, usługa jest dostępna z poziomu klienta - zamówienia są składane z tą formą przesyłki, jednak żądania wygenerowania przesyłki są odrzucane, ponieważ nie jesteśmy w stanie dostarczyć ID umowy własnej - ID jest matchowane na podstawie dostępnych usług zwracanych z API, a ponieważ ta usługa nie jest zwracana, nie matchujemy ID umowy własnej.
Trace-id dla zapytań:
ce028ea3a2090b59
eb663613bc1e81f9
W obydwu przypadkach brakuje powyższej usługi.

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam za niedogodności, był to problem wygenerowany z naszej winy. Umowa własna powinna już być zwracana w odpowiedzi zasobu.

**Comment by Wojtu204** [comment]
Dziękuję, usługa jest już widoczna.
