### ISSUE TITLE
Variants in czech base Allegro

### ISSUE THREAD

**Issue by Maremic** [allegro/allegro-api#9534]
Hi, I found out that one cant create variants of products in czech based allegro, 
I want just know if there is a way to solve  our problem 

so we will sell books, antique books, we have it ordered under one release,
so we have release with EAN/ISBN 

and under it we have products which can have different conditions (based on dmg, like very good state, like a new, or damaged and so on )

I know there is some automatic function for colors and sizes, but can I use some field for this condition ? 

thanks very much, 
with regards
Mareš Michal

**Comment by PrzemyslawLukanowski** [comment]
Unfortunately, it is not possible. You can use only parameters marked as `"options.variantsAllowed": true` in response to [GET / sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2). But as you already noticed, it is not possible to create multi-variant offers on others marketplaces as allegro.pl.
