### ISSUE TITLE
Ujednolicenie sposobu wyliczenia ceny na liście przedmiotów oraz liście usług dodatkowych 

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#954]
:bulb: **Sugestia**

Aktualnie dla każdego przedmiotu mamy: quantity oraz price, gdzie price to cena jednostkowa.
Niestety dla usług dodatkowych price to cena wszystkich zakupionych sztuk. Brak informacji o cenie jednostkowej. Pomocne przy fakturowaniu.

**Comment by PawelTaberski** [comment]
Przy jakim zasobie brakuje Tobie takich informacji rozumiem, że chodzi Tobie już o zarządzanie zamówieniami, tak?

**Comment by aktywnitu** [comment]
/order/checkout-forms*

**Comment by PawelTaberski** [comment]
Zgłosiłem Twoją sugestię do odpowiedniego zespołu, jeśli zdecydujemy się wdrożyć takie rozwiązanie to poinformujemy o tym w osobnym komunikacie.
