### ISSUE TITLE
How to Create a Test Order with Allegro Prices Program in Sandbox

### ISSUE THREAD

**Issue by Vitalka13** [allegro/allegro-api#9540]

**Comment by Vitalka13** [comment]
Dzień dobry!
Tydzień temu Allegro usunęło wszystkie oferty z naszego asortymentu i musieliśmy stworzyć nowe. Więc bardzo proszę, aby Państwo włączyli nam promo Allegro Ceny dla jednej oferty. Podaję ID 7773093455.
Z góry dziękuję!

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, przekazałem prośbę do odpowiedniego działu. Wrócę, gdy będzie to gotowe.

**Comment by PrzemyslawLukanowski** [comment]
Zakwalifikowaliśmy ofertę do programu Allegro Ceny.

**Comment by Vitalka13** [comment]
Dziękuję! Sprawdziłam, ale mam jakieś dziwne ograniczenie. Wcześniej takiego nie było. Czy to jest jakiś błąd?
![цц](https://github.com/user-attachments/assets/30463f22-1beb-4f3f-baf9-fe4e228cfaf1)

**Comment by PrzemyslawLukanowski** [comment]
Jest to prawidłowe ograniczenie w ramach programu Allegro Ceny.

**Comment by Vitalka13** [comment]
Ok, dziękuję za informację!

**Comment by PrzemyslawLukanowski** [comment]
Jeśli jest to problem, możemy to zmienić - jest to do konfiguracji po naszej stronie.

**Comment by Vitalka13** [comment]
Czy to ograniczenie działa tylko na sandboxie, czy również na stronie głównej?

**Comment by PrzemyslawLukanowski** [comment]
Tak, na produkcji również.

**Comment by Vitalka13** [comment]
A może Pan powiedzieć od kiedy zostało wprowadzone ograniczenie? bo szczerze mówiąc nie zauważyłam tego wcześniej

**Comment by PrzemyslawLukanowski** [comment]
Takie ograniczenie jest już od dłuższego czasu, jednak o tym, ile sztuk kupujący może zakupić w danej kategorii, decydują nasze wewnętrzne mechanizmy. Być może zazwyczaj po prostu było to więcej niż 1.

**Comment by Vitalka13** [comment]
Czy mogę poprosić Państwo usunąć ograniczenie na sandboxie, abyśmy mogli spokojnie testować promo?)

**Comment by PrzemyslawLukanowski** [comment]
Tak, usunęliśmy ograniczenie.
