### ISSUE TITLE
Zablokowana sprzedaż Sandbox

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#9544]
Proszę o odblokowanie sprzedaży na sandbox dla konta mateuszcom2. Przeprowadziliśmy poprawnie symulację opłaty salda, ale w przypadku tego konta sprzedaż nadal jest zablokowana. Na innym koncie proces przeszedł bez problem. Potrzebujemy aktywnego drugiego konta w celach testowych

**Comment by AureliuszBrussy** [comment]
Usunąłem blokadę.

**Comment by mateuszcom** [comment]
Dziękuję za pomoc
