### ISSUE TITLE
Allegro czech version, multiple questions

### ISSUE THREAD

**Issue by Maremic** [allegro/allegro-api#9549]
Hi, 
So we bumped into some fails while trying to implement our products to allegro, 
I want to ask:

1. Will allegro.cz have same features like pl version in future ?
2. Can we as czech bussines create allegro.pl account and then have products on pl and additionalMarketplaces at cz ? so we can use features what are missing on czech site ?  
3. How big is your product catalogue ?  We are large antique with books, one of the biggest in czech (antikavion.cz)
we have around 1M offered books, mostly czech, but other languages too.
4. is sandbox catalogue same with live one ? if is possible that I found less books thanks to smaller test catalogue? 
On PL version we liked:
- we liked versions offers so we can have release and under it its grouped products with different states, conditions, similar to our current  system
- we could be able to make unique products, I suppose you dont have much czech books in catalogue for us to pair our products
- we was kinda ok with 20k products in month, its little unfortune but it can still grow up in time

I have tried to connect API to our czech eshop, so we could offer on allegro too, but I find out its not made for implementation with huge eshops right ? plus its hard to find some older but popular czech books on your catalogue (as far as I tried) 

thanks, you helped me here a lot with testing and tries to implement it,
little feedback, a lot of restrictions I found out from some ost here, or POST errors, instead of documentation, it would be nice 
to make clear what czech version can and what cant, I found a lot of issues about this topic

regards, 
Mareš Michal
Antik Avion

**Comment by PrzemyslawLukanowski** [comment]
Hello, the first questions are associated with Allegro in general more than with API technical issues so I would kindly ask you to send them via [contact form](https://allegro.pl/pomoc/kontakt). The number of products in our catalog is an internal information so sorry, but we cannot share this data.

> is sandbox catalogue same with live one ? if is possible that I found less books thanks to smaller test catalogue?
> On PL version we liked:

The Sandbox catalog is different from the one production. Yes, there are less products.

If you want to check whether the given product exists in our catalog, you can use [GET /sale/products](https://developer.allegro.pl/documentation#operation/getSaleProducts).
