### ISSUE TITLE
Status FILLED_IN dla zamówienia z płatnością CASH_ON_DELIVERY

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#955]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

order/checkout-forms/e0f23cb3-f2ee-11e8-a40e-ef08815f7077

Status zamówienia powinien być READY_FOR_PROCESSING.
Brak danych do wysyłki.

**Comment by PawelTaberski** [comment]
Z tego co widzę na requesta o taki numer doszedł poprawny respons ze statusem 200.  Czy respons przyszedł niekompletny, czy nie zgadzał się tylko status?
Podeślij przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) proszę numer oferty, login usera który dokonał zakupu i respons wraz z trace-id jaki otrzymałeś, sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że informacje są potrzebne do ticketa numer 955 na GitHub-ie.

**Comment by tztztztz** [comment]
Jest już zgłoszenie na ten sam temat:

https://github.com/allegro/allegro-api/issues/936

**Comment by PawelTaberski** [comment]
Po tym jak doprecyzowałeś rzeczywiście wychodzi, że to ten sam problem, sprawa jest w trakcie weryfikacji. Mam nadzieję, ze niedługo uda się rozwiązać problem.

**Comment by mack3d** [comment]
Dołączam informacje iż mam ten sam problem w drugim zamówieniu w ciągu tygodnia.

**Comment by PawelTaberski** [comment]
@mack3d  Podeślij proszę requesty i responsy przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619), w zgłoszeniu zaznacz, że informacje są potrzebne do zgłoszenia na GitHub-ie numer 955. Przekażę tę informacje do zespołu, który stara się poprawić ten błąd.

**Comment by aktywnitu** [comment]
Niestety nadal występuje problem.
Proszę o wdrożenie poprawki.

**Comment by PawelTaberski** [comment]
@aktywnitu Podeślij proszę najnowsze requesty i responsy przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619), w zgłoszeniu zaznacz, że informacje są potrzebne do zgłoszenia na GitHub-ie numer 955. Przekażę tę informacje do zespołu, który pracuje nad tym problemem, wdrożyliśmy poprawkę i wydawało się że teraz powinno być ok.

**Comment by aktywnitu** [comment]
Nie za bardzo wiem, co miałbym podesłać.
Po prostu są zamówienia np.:
6b71ba06-ff97-11e8-a474-55c966d57068
693c2ae4-ff1f-11e8-9905-fdd6adf3eb40
, które mają niepoprawny status FILLED_IN, brak w nich danych do wysyłki, mimo, że są to zamówienia z opłatą przy odbiorze.

**Comment by PawelTaberski** [comment]
@aktywnitu Jasne te dane powinny wystarczyć, przekazałem je do odpowiedniego zespołu, który pracuje nad tym problemem.

**Comment by PawelTaberski** [comment]
@jchodubska Jeszcze mamy pewnie problemy, jeśli zauważyłeś jakieś nieścisłości to podeślij proszę numery zamówień i jaki problem w nich zauważyłeś

**Comment by jchodubska** [comment]
Zauważyłam, że zamówienia zaczęły się aktualizować i zmieniać statusy na poprawne

**Comment by PawelTaberski** [comment]
@jchodubska Rozumiem, jakbyś wychwycił jeszcze jakieś nieprawidłowości, to podsyłaj nam je proszę.

**Comment by PawelTaberski** [comment]
@aktywnitu Tak jak odpowiedzieliśmy Tobie w tickecie #936 - uaktualniliśmy na ten moment statusy zamówień. Obecnie pracujemy jeszcze nad poprawką w tym temacie.
