### ISSUE TITLE
sandbox - wywołanie product-offers/operations 

### ISSUE THREAD

**Issue by bmusialekcepd** [allegro/allegro-api#9552]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

witam, 
przy probie wywołania https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/7774892857/operations/32d190f8-6330-42ea-8dfc-472551197eda otrzymuje Access denied. You are not authorized to perform operations on the indicated offer.

trace-id 8d88661bca98343b

**Comment by PrzemyslawLukanowski** [comment]
Witam, zwróciliśmy błąd, ponieważ oferta należy do użytkownika ****7443, natomiast operację wykonałeś, będąc zautoryzowany jako użytkownik ****36521.
