### ISSUE TITLE
Błędy kod recaptcha

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#956]
Witam,

Ostatnio mam duże problemy z odświeżeniem tokenów dla RestAPI. Raz działa raz nie. Teraz wysyłając request:

Do:

https://ssl.allegro.pl/auth/oauth/token

z POST (wypełnione poprawne, wykropkowałem):

grant_type=authorization_code&code=...&api-key=...&redirect_uri=....

Dostaję stronę z zółtym:

Błąd, spróbuj jeszcze raz.
Zaznacz poniższe pole:

Oraz niedziałającą captcha:

Informacja dla właściciela witryny – wykryliśmy BŁĄD:
nieprawidłowa domena dla klucza witryny

Dla takiego ustawienia:

data-sitekey="6Les6wsUAAAAAIaI5ozoiE0ERoQcB5hdB5uJRRoa"

**Comment by kiczek** [comment]
Potwierdzam, problem występuje od soboty.

**Comment by PawelTaberski** [comment]
Podeślijcie proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) client ID na których macie problem i jak macie trace-id. Sprawdzimy w czym jest problem. W zgłoszeniu zaznaczcie proszę, że dane potrzebne do ticketa numer 956 na GitHub-ie.

**Comment by pgasidlo** [comment]
Czy coś wiadomo w tym temacie. O ile przez przełom roku było ok, dzisiaj znowu o północy zamiast oczekiwanego JSON strona z prośbą o captcha.

**Comment by PawelTaberski** [comment]
Tamten problem rozwiązaliśmy, podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) client_id na jakim otrzymałeś taki błąd. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 956 na GitHub-ie.
