### ISSUE TITLE
Maskowa aktualizacja stanu dla ofert 

### ISSUE THREAD

**Issue by bmusialekcepd** [allegro/allegro-api#9562]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

witam, za pomoca funkcji aktualizuje stan dla ofert
   0 => "7773432626"
    1 => "7773418637"
    2 => "7773412308"
    3 => "7773328885"
    4 => "7773325038"
    5 => "7773317743"
    6 => "7773317149"
    7 => "7773303605"
    8 => "7773161559"
    9 => "7773156441"
    10 => "7773156168"
    11 => "7773151529"
    12 => "7773149912"
    13 => "7775017384"
    14 => "7775016475"

Ustawiam stan na 0. Pomimo to stan na aukcji 7775017384 dalej = 100

trace-id = 21b519c55425d3af

**Comment by AureliuszBrussy** [comment]
Nie możesz ustawić liczby sztuk na 0. W takim przypadku zakończ ofertę.

**Comment by bmusialekcepd** [comment]
powiniem jej ustawic status ENDED czy jakis inny?

**Comment by AureliuszBrussy** [comment]
Tak, aby zakończyć ofertę, ustaw status ENDED.
