### ISSUE TITLE
jak wygenerować pmd_id per produkt?

### ISSUE THREAD

**Issue by Vitalka13** [allegro/allegro-api#9564]

**Comment by Vitalka13** [comment]
Dzień dobry!
Aby zgłosić o błąd w ofercie, potrzebuję wygenerować pmd_id per produkt. Proszę powiedzieć, gdzie i w jaki sposób mogę to zrobić?

**Comment by AureliuszBrussy** [comment]
Nie możesz generować samodzielnie id produktu. Możesz sprawdzić id danego produktu w ofercie - zwracamy go w productSet.product.id. Możesz też wyszukać produkt w naszym katalogu i pobrać jego id za pomocą [GET /sale/products](https://developer.allegro.pl/documentation#operation/getSaleProducts).

**Comment by Vitalka13** [comment]
A w jaki sposób mogę pobrać id za pomocą GET /sale/products?

**Comment by AureliuszBrussy** [comment]
Przeszukując listę produktów dostępnych w Katalogu Produktów. Opisujemy ten proces w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-znalezc-produkt).

**Comment by Vitalka13** [comment]
Bardzo dziękuję!
