### ISSUE TITLE
Co zmienia PUT /sale/offer-quantity-change-commands/{commandId}

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#957]
Szybkie pytanie:
Czy zmienia się:
1) liczba dostępnych przedmiotów
2) początkowa liczba przedmiotów
?

Pozdrawiam,
KF

**Comment by PawelTaberski** [comment]
Nie rozumiem dokładnie o co pytasz, ale dokładny opis tego zasobu znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/#3g), podajesz tam tylko jedną wartość.

**Comment by kfijalko** [comment]
W WebAPI działało tak, że zmianiała się "początkowa liczba przedmiotów".
Przykład:
poczatkowa liczba przedmiotów = 10
sprzedane = 6
dostępne = 4
jak zmieniałem przez WebAPI to ustawiałem 
początkowa liczba przedmiotów = mój stan magazynowy + sprzedane

W REST jest informacja, że zmienia się "liczba przedmiotów w ofercie", tylko która?
1) jeżeli "dostępnych" to ustawiam na mój stan magazynowy
2) jeżeli "początkowa" to wyliczam zgodnie z powyższym

kf

**Comment by PawelTaberski** [comment]
W REST API podajesz tyle przedmiotów ile chcesz oferować, jak sprzedałeś kiedyś 5 w ofercie masz obecnie 6 a chcesz aby było teraz 10, to ustawiasz 10 już nie musisz nic sumować. W tej metodzie przez REST API masz dwie opcje. Możesz zwiększyć stock o x przedmiotów bądź ustawić na konkretną liczbę.

**Comment by kfijalko** [comment]
ok

**Comment by runaway90** [comment]
@PawelTaberski przepraszam, ale co w tej metodzie jest {commandId} w url?

**Comment by PawelTaberski** [comment]
W polu CommandID wskaż identyfikator pod jakim zapiszemy to polecenie.
CommandID to identyfikator danego requesta, na jego podstawie sprawdzisz stan realizacji twojego żądania. Więcej na ten temat znajdziesz [tutaj.](https://developer.allegro.pl/about/#ids)
