### ISSUE TITLE
Śledzenie przesyłki API

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#9570]
Mam pewien problem z wyświetleniem trackingu przesyłki. Korzystam z **GET /order/carriers/{carrierId}/tracking?waybill={waybill}**

Gdy wywołuję metodę, nie otrzymuję żadnej historii przesyłki, pomimo tego, że przesyłka została odebrana.

Przykładowy response, który otrzymuję:
`{"carrierId":"a3b4db98-4a70-4542-84ee-c642604d9d8a","waybills":[{"waybill":"28115804701","trackingDetails":null}]}`

Dla każdej testowanej przesyłki wynik jest taki sam **null**

**Comment by PrzemyslawLukanowski** [comment]
Wartość, którą przekazujesz w {carrierID}, nie wygląda na prawidłowo. To musi być ID przewoźnika, które zwracamy w [GET /order/carriers](https://developer.allegro.pl/documentation#operation/getOrdersCarriersUsingGET), np. "DHL".

**Comment by mateuszcom** [comment]
Dziękuję za pomoc - trochę mnie nomenklatura zmyliła :)
