### ISSUE TITLE
Dziwne wpisy w dzienniku zdarzeń RESTAPI

### ISSUE THREAD

**Issue by kuli-g** [allegro/allegro-api#958]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Przy próbie wydobycia informacji z nich dostaję błąd ERROR | An error has occurred i nic więcej

`1543749369889391 | 1 | 1543749358 | 9e9037e2-f623-11e8-aa00-530c56d664d1

1543749391065557 | 1 | 1543749374 | a9800db2-f623-11e8-93df-27b5562b6e5f  

1543749418926722 | 1 | 1543749402 | b6ba21a2-f623-11e8-93df-27b5562b6e5f

1543749436482153 | 1 | 1543749420 | c5db1e02-f623-11e8-aa00-530c56d664d1 

1543749481870084 | 1 | 1543749463 | e03b96d2-f623-11e8-93df-27b5562b6e5f

1543749506099358 | 1 | 1543749494 | f350d7d2-f623-11e8-93df-27b5562b6e5f'

identyfikator zdarzenia, status, czas, UUID

Chyba był już poruszany ten temat ale chodzi mi ogólnie że jeśli już system zwraca jakiś UUID to chociaż powinien mieć jakąś odpowiedź gdy klient o niego pyta...

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem o co Tobie dokładnie chodzi? Z jakiego zasobu korzystasz jaką dokładnie odpowiedź dostajesz?

**Comment by kuli-g** [comment]
Chodzi mi o sytuację gdy kupujący naklika KupTeraz a dopiero później łącznie ustali formę wysyłki, w dzienniku pojawiają się wpisy które stają się nieaktualne po wypełnieniu formularza. REST mógłby zwracać w takich przypadkach np UUID formularza dostawy zamiast informacji że wystąpił błąd bo tak to nie wiadomo czy to prawdziwy błąd czy tylko nieaktualny UUID. 

PS: temat powstał zanim zaraz po wstawieniu znalazłem podobny #943 dlatego myślę że można go zamknąć

**Comment by PawelTaberski** [comment]
Teraz rozumiem, sprawę tego niejasnego komunikatu już zgłosiliśmy, mam nadzieję że niedługi zostanie poprawiony na bardziej klarowny i jednoznaczny.
