### ISSUE TITLE
Tworzenie przesyłki na umowie własnej

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#9582]
Czy istnieje jakiś zasób dzięki któremu będę mógł pobrać wszystkie identyfikatory umowy własnej (credentialsId), które mogę użyć przy tworzeniu nowej paczki dla POST /shipment-management/shipments/create-commands

**Comment by AureliuszBrussy** [comment]
Tak, gdy skorzystasz z [GET /shipment-management/delivery-services](https://developer.allegro.pl/documentation#operation/getDeliveryServices) zwrócimy wszystkie usługi dostawy, z których może skorzystać dany sprzedający, w tym te dodane w ramach umowy własnej. Te na umowie własnej będą miały podaną wartość w polu `id.credentialsId`.
