### ISSUE TITLE
Allegro Sandbox, brak dostępu

### ISSUE THREAD

**Issue by OtcfDevTeam** [allegro/allegro-api#9595]
Występuje problem przy próbie wejść na allegrosandbox https://allegro.pl.allegrosandbox.pl/ : 

![image](https://github.com/user-attachments/assets/98a206cc-d734-41df-84e7-7586c0c3f13a)

 - [ Please enable JS and disable any ad blocker] ze środowiskiem testowym / with the test environment

**Comment by Lukasz-Zurek** [comment]
Poproszę o więcej szczegółów. Czy na stronę jesteś kierowany z narzędzia typu Postman? 

Jeżeli chodzi o nasze API na sandboxie, link powinien wyglądać tak: api.allegro.pl.allegrosandbox.pl. Dodatkowo upewnij się co do wspomnianego w komunikacie javascript (powinien być włączony) i czy korzystasz jeszcze z jakiegoś oprogramowania do blokowania reklam, który mógłby przyczynić się do niewyświetlania captchy.

**Comment by OtcfDevTeam** [comment]
Sam serwis sanbox WWW nie działał przez chwilę i komunikat który się pojawiał nie był do końca prawdziwy (JS włączony w przeglądarce i brak adblokerów)
Teraz działa więc zamykam zgłoszenie
