### ISSUE TITLE
doGetPostBuyData - błędny kod kraju

### ISSUE THREAD

**Issue by rafwlaz** [allegro/allegro-api#96]
Metoda dla kraju `Polska` zwraca w `userCountryId` wartość `0` zamiast prawidłowej `1`.
Dane w przypadku pobrania danych wysyłki są już zwracane prawidłowo.

**Comment by AniaMalinowska** [comment]
Sprawdziłam i metoda zwraca prawidłowe dane - w polu userCountryId otrzymałam 1. 
Abyśmy mogli sprawdzić Twój przypadek, proszę, podeślij [przez formularz kontaktowy](https://allegro.pl/pomoc/kontakt#appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=9fe60f94-a07b-47e5-84b4-b15beafe2422) request i response.
