### ISSUE TITLE
[REST API] /sale/categories/{categoryId}/parameters - złe właściwości parametrów

### ISSUE THREAD

**Issue by PawelSzGit** [allegro/allegro-api#960]
Występuje problem:
 - [X] z zasobem REST API
 
Witam, pobierając pola kategorii id: 5540 (Sandały) w odpowiedzi dostaje iż pole id: 6828 (nosek) nie jest wymagane i posiada ( 'required': False ). Niestety kiedy nie przesyłam tego pola dostaje zwrotkę, że jest ono wymagane.

**Comment by PawelTaberski** [comment]
Czy jesteś pewny, że dostajesz info, że właśnie tego parametru brak, przetestowałem i wystawiłem ofertę w kategorii `"id": "5540"` bez parametru `"id": "6828", "name": "Nosek",` i oferta opublikowała się prawidłowo. Podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619):

- responsa z zasobu GET /sale/offers/{offerId} z draftu z jakim masz problem,
- pełnego cURL-a i responsa z zasobu w jakim dostajesz informacje, że ten parametr jest wymagany.

Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane potrzebne do ticketa numer 960 na GitHub-ie.

**Comment by PawelSzGit** [comment]
Przepraszam to błąd jednego z naszych programistów. Zamykam
