### ISSUE TITLE
Błąd na sandboxe - wystawianie oferty

### ISSUE THREAD

**Issue by mwojtasikdressler** [allegro/allegro-api#9607]
na koncie SK_test1
przy próbie wystawiania oferty(DODAJ NOWĄ OFERTE) wyskakuje komunikat o zmianie języka i nie przechodzi dalej
![Zrzut ekranu 2024-08-07 110402](https://github.com/user-attachments/assets/e2679d7a-9883-436a-b455-ffa8f90fc987)

nie ładują się zamówienia i asortyment
te przyciski nie działają jak i dodawanie do koszyka i kup teraz
![obraz](https://github.com/user-attachments/assets/3f930d5c-e6d0-42c1-8b27-4a08432862dc)

problem występuje na firefixsie i edge (usuniecie ciasteczek nie pomogło)

ogólnie nie wiele da się zrobić na koncie a jest potrzebne do przetestowania sprzedaży audiobooków

**Comment by AureliuszBrussy** [comment]
Nie jestem w stanie aktualnie potwierdzić na ten moment żadnego z tych problemów - każda z tych funkcji działa bez zarzutu. Twoje konto jest w pełni aktywne, więc to nie powinna być przyczyna problemów.

Czy jesteś w stanie wejść np. bezpośrednio do formularza wystawiania: https://allegro.pl.allegrosandbox.pl/offer/ ?

**Comment by mwojtasikdressler** [comment]
problem występuje po wejściu w ten link mam takie okno

![obraz](https://github.com/user-attachments/assets/64551e4d-e87c-40ae-9fd6-b7bde1716234)

**Comment by mwojtasikdressler** [comment]
konsola firefoxa wypluła miedzy innymi coś takiego

Content-Security-Policy: Zablokowano niezabezpieczone żądanie „http://edge.allegro.pl.allegrosandbox.pl/notification-badges”.
Content-Security-Policy: Zablokowano niezabezpieczone żądanie „http://edge.allegro.pl.allegrosandbox.pl/packages/summary”.

**Comment by mwojtasikdressler** [comment]
przy dodaniu do koszyka 
Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „https://edge.allegro.pl.allegrosandbox.pl/carts/changeQuantityCommand” (brakujący nagłówek CORS „Access-Control-Allow-Origin”). Kod stanu: 429.

Error: Failed to add to cart. Status: 0. Data: "". [index.es6_fbf0bd79.js:2:55586](https://assets.allegrostatic.com/sc-15219/index.es6_fbf0bd79.js)
Error: Failed to add to cart. Status: 0. Data: "".

**Comment by AureliuszBrussy** [comment]
Dziękuję, sprawdzamy to. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@mwojtasikdressler czy wspomniane problemy nadal występują?

**Comment by mwojtasikdressler** [comment]
Wygląda na to że już działa
Dziekuje
