### ISSUE TITLE
Tajemnicze "chwilowe" zamykanie aukcji po 10, 20 i 30 dniach (wielokrotność 10 dni)

### ISSUE THREAD

**Issue by coobitus** [allegro/allegro-api#961]
Jest taki problem w Waszym API (WebAPI), prawdopodobnie od bardzo dawna. Otóż mamy aukcję, która jest wystawiona "do wyczerpania zapasów". Czyli teoretycznie cały czas powinna być aktywna - dopóki nie wyprzeda się cała dostępna na aukcji ilość. Tymczasem wcale to tak nie działa - takie przynajmniej mam obserwacje ...

Sprawdzając co jakiś czas taką aukcję przy pomocy metody "doShowItemInfoExt" z WebAPI można natrafić na takie momenty, że dostaniemy zwrotne info, że ta aukcja się już zakończyła !!! Chodzi dokładnie o pole "itEndingInfo" które opisane jest w dokumentacji tak :

"Informacja na temat stanu oferty (1 - trwa, 2 - zakończyła się w sposób "naturalny" (koniec czasu trwania, albo wykupienie wszystkich dostępnych przedmiotów w przypadku Kup Teraz), 3 - została zakończona przez sprzedającego przed czasem)."

W sytuacji o której mówię ten parametr przyjmuje wartość "2" - czyli że aukcja została zakończona w sposób naturalny (??!!!?!?) Tymczasem ta aukcja cały czas jest dostępna publicznie, a co więcej po pewnym czasie (zwykle po kilku do kilkudziesięciu minutach) to samo zapytanie zwraca już poprawną wartość, czyli "1". 

Do niedawna takie sytuacje miały nagminnie miejsce jak kończył się czas dokładnie 30 dni od daty wystawienia aukcji. Wniosek z tego taki, że wystawianie "do wyczerpania zapasów" to był de facto pic na wodę fotomontaż, bo de facto te aukcje po prostu zamykaliście po 30 dniach i je po chwili spowrotem "wznawialiście". 

Od niedawana (chyba od wprowadzenia opłat za promocje co 10 dni) zauważyłem, że taka sama sytuacja ma miejsce co 10 dni. Czyli aukcja "zamyka się na chwilę" 10, 20, 30, 40 itd dni od daty jej wystawienia. 

Jest do delikatnie rzecz ujmując dziwne rozwiązanie, i w dodatku nigdzie nieudokumentowane. Szczególnie jeśli ktoś wykorzystuje te dane do tego, żeby w efekcie automatycznie zamknąć taką aukcję w zintegrowanym z Allegro sklepie.

Proszę o wyjaśnienie dlaczego tak to działa, dlaczego to nie jest udokumentowane i czy możecie to naprawić ASAP.

**Comment by PawelTaberski** [comment]
Wszystko się zgadza poruszaliśmy już tą kwestię tutaj kilkukrotnie m.in. w wątku #61, jest to spowodowane tym, że następuje wznowienie cyklu. W tym czasie może się zdarzyć, ze przez API zwrócimy informacje, że oferta jest zakończona.

**Comment by coobitus** [comment]
A nie możecie wyłączyć tej sygnalizacji w API? Przecież to jest bardzo poważny BUG w systemie ...

**Comment by PawelTaberski** [comment]
Takie wznowienie cyklu jest dla nas niezbędne, sugeruje aby zabezpieczyć się przed tym ustawić jakieś okienko czasowe w którym ponownie odpytasz, czy ta oferta jest rzeczywiście zakończona, czy to tylko spowodowane automatycznym wznowieniem.

**Comment by anih** [comment]
Takie np. godzinne okienko czasowe, bo patrząc, że wystawianie ofert potrafi złapać laga, to pewnie i ten mechanizm też?

**Comment by PawelTaberski** [comment]
Jak w przypadku każdej zmiany na ofertach informujemy, że może potrwać do godziny. Choć w znaczącej większości przypadków jest to o wiele krótszy czas nie przekraczający kilku minut.

**Comment by PawelTaberski** [comment]
Może źle mnie zrozumiałeś, bo oferta przez front jest cały czas aktywna dla klientów, a co do czasu to, tak jak pisałem jest to w znaczącej większości kwestia minuty dwóch (a nawet krócej) jak dostajesz taki komunikat po API. W jakiś granicznych przypadkach może się zdarzyć dłużej. Zawsze asekuracyjnie podajemy godzinę w odniesieniu do wszystkich zmian w ofertach, bo w jakiś granicznych sytuacjach może się wydarzyć że będzie to dłuższy czas niż kilka minut. Oferta nie jest zamknięta nie zmienia się jej numer, nie traci popularności, klienci mogą na niej normalnie kupować i jest to dla nich niezauważalne.

**Comment by coobitus** [comment]
Heh .. ale przez API ta oferta jest widoczna jako zamknięta :-) Co nam po frontendzie?

**Comment by PawelTaberski** [comment]
Jest to niezbędne do prawidłowego rozliczenia m.in. opłat. Nie jest to bug i z tego co wiem nie planujemy zmiany działania tego mechanizmu.

**Comment by Radeq** [comment]
@PawelTaberski Czy w nowym REST API (zasób GET sale/offers , /sale/offers/{offerId} ) problem również występuje?

**Comment by PawelTaberski** [comment]
@Radeq Nie w REST API taka sytuacja nie powinna się wydarzyć.

**Comment by TimothyKoval** [comment]
@PawelTaberski Nie dość, że jest to bug, to jest to bug **KRYTYCZNY**. Otrzymuję od Waszego API odpowiedź, że aukcja jest zakończona, co traktuję jako kompetentną informację. Kto mi zapłaci za wszystkie problemy związane z faktem sprzedaży produktu którego już nie oferuję? Allegro, czy Allegro w wyniku decyzji sądu?

**Comment by FromAnyHole** [comment]
@PawelTaberski - w REST-API "nie powinna" ??????????
Pierwszy raz tego BUG'a widziałem chyba w 2012, no może 2013 roku...
Tyle razy było to zgłaszane, opisywane, no i kicha ! A wystarczyło dodać specjalną wartość (np. 4) dla tego pola - jako tryb "obsługowy" przedmiotu, no ale po co się wysilać - se weźta i oprogramujta sami !!

**Comment by PawelTaberski** [comment]
Tak, jak już pisałem. Jest to niezbędne do prawidłowego rozliczenia m.in. opłat. Nie jest to bug i z tego co wiem nie planujemy zmiany działania tego mechanizmu. REST API działa w oparciu o inne mechanizmy i tam taka sytuacja nie występuje. Jeśli jest to dla Państwa przeszkoda zachęcam do przechodzenia na REST API.

**Comment by TimothyKoval** [comment]
A jak będę wam płacił co dziesiątą fakturę, bo jest to niezbędne do prawidłowego działania mojej firmy, to będzie to błąd czy nie błąd?

**Comment by Arkowsky** [comment]
Chciałbym tylko by była świadomość, że ten błąd u nas spowodował, że aukcja została oznaczona jako zakończona chociaż nie była i nie aktualizowaliśmy już stanów magazynowych(ufając, że zakończona to zakończona - czy w dokumentacji jest opisany ten błąd?). Klienci zatem kupowali rzeczy których nie było. Jeden z nich założył spór na allegro i zostaliśmy za to zablokowani. 

Rozumiem, że jest nowe api i pewnie na nie przejdziemy za jakiś czas ale zgadzam się z przedmówcami - TO JEST BŁĄD KRYTYCZNY i powinien być naprawiony w starym API bo jest jeszcze pewnie dużo osób, którzy dowiedzą się o nim jak się coś zepsuje.

**Comment by PawelTaberski** [comment]
Tak, jak już pisałem nie jest to bug i nie planujemy zmiany działania tego mechanizmu. REST API działa w oparciu o inne mechanizmy i tam taka sytuacja nie występuje. Ponadto powoli już wygaszamy wszelkie zasoby do zarządzania ofertami w WebAPI #1043 dlatego zachęcamy do przechodzenia na REST API.
