### ISSUE TITLE
Produkty - wiele wartości w parametrze w którym powinna być jedna

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#9610]
Mam pytanie jak rozpoznawać że parametr może przyjmować wiele wartości.

Przykład:
w produkcie f7adc46e-e5c2-441a-8b38-bd8ad2f56eaf jest parametr 225693 (EAN (GTIN)) który ma 2 wartości, 
natomiast parametr ten w kategorii tego produktu ma w ustawieniach restrictions->allowedNumberOfValues = 1

**Comment by AureliuszBrussy** [comment]
Jeden produkt w naszym Katalogu Produktów może mieć zapisane wiele GTIN. Natomiast podczas wystawiania oferty produktu należy wybrać tylko jeden z nich. Ostatecznie sprawdzisz to właśnie w polu `restrictions`.

**Comment by avello** [comment]
Ok, moje pytanie było jak rozpoznawać że parametr może przyjmować wiele wartości.
To że zwraca mi wiele wartości GTIN to widzę, ale jak zechcę zgłosić błąd w produkcie przez API muszę wysłać też parametry i chcę wiedzieć kiedy mogę wysyłać wiele wartości.

**Comment by AureliuszBrussy** [comment]
Ok, rozumiem, dozwoloną liczbę wartości w parametrze dla produktu pobierzesz za pomocą [GET /sale/categories/{categoryId}/product-parameters](https://developer.allegro.pl/documentation#operation/getFlatProductParametersUsingGET), informacje zwrócone również w `restrictions`.

**Comment by avello** [comment]
dziękuję o to mi chodziło
