### ISSUE TITLE
Wystawienie oferty  sale/product-offers do wyczerpania zapasów

### ISSUE THREAD

**Issue by SzymonZasada** [allegro/allegro-api#9611]
Wg dokumentacji https://developer.allegro.pl/documentation/#operation/createProductOffers 
w czasie trwania aukcji publication.duration nie ma opcji aby trwała do zakończenia przedmiotów - widze tylko te opcje:

 This field must be set to one of the following:
- for auctions: 1 day, 3 days, 5 days, 7 days, 10 days
- for buy-now offers: 3 days, 5 days, 7 days, 10 days, 20 days, 30 days
- for advertisements: 10 days, 20 days, 30 days.

Jak mogę wystawić aukcje przez api aby było do zakończenia zapasów?

**Comment by AureliuszBrussy** [comment]
Nie przekazuj żadnej wartości, lub przekaż `null` - wtedy oferta produktu zostanie wystawiona do wyczerpania zapasów.
