### ISSUE TITLE
sandbox

### ISSUE THREAD

**Issue by tongalalal** [allegro/allegro-api#9617]
![image](https://github.com/user-attachments/assets/a9d394c6-e633-4964-9e4a-0145f260dead)

Why doesn't the 'Next' button respond when registering a sandbox?

**Comment by Lukasz-Zurek** [comment]
This may have something to do with the translation plugin. Please try also in incognito mode.

**Comment by tongalalal** [comment]
When I close the translation plugin and try again, clicking NEXT still has no response. My network works fine when requesting other data, but there is no response when registering this sandbox corporate account.”

**Comment by Lukasz-Zurek** [comment]
@tongalalal I have just tested our registration form and it works correctly. Try in incognito mode.
