### ISSUE TITLE
Problem z wgrywaniem ofert z pliku

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#9628]
W sumie nie wiem czy to zgłoszenie to tutaj ale zaryzykuję,
próbuje wgrać oferty przez opcję importu z pliku,
jeśli produkt jest w katalogu to dodaje się normalnie ale jeśli go nie ma to krzyczy że nie może połączyć z katalogiem i mam uzupełnić EAN(GTIN) chociaż jest uzupełniony.

Przykładowy plik 5c141ce0-b996-4f7e-9932-5d59755fffe5 
tu jedna aukcja została utworzona, a druga nie

**Comment by Lukasz-Zurek** [comment]
W sprawie wystawiania z pliku skontaktuj się proszę poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
