### ISSUE TITLE
Zmiana ceny zakończonej aukcji

### ISSUE THREAD

**Issue by janzdanowski** [allegro/allegro-api#963]
Czy to normalne, że przez REST API można zmienić cenę zakończonej aukcji?
Wydaję mi się, że jeszcze niedawno podczas próby zmiany ceny takiej aukcji zwracany był błąd. Teraz tak nie jest.

**Comment by PawelTaberski** [comment]
Tak, możesz edytować zakończoną ofertę, a następnie potem ją aktywować pod tym samym numerem jaki miała wcześniej, dzięki czemu nie traci ona swojej całej popularności. Więcej na temat ofert pisalismy w [naszym poraniku](https://developer.allegro.pl/sale/).
