### ISSUE TITLE
Aktywacja konta allegro sandbox

### ISSUE THREAD

**Issue by MarekCiecharowski** [allegro/allegro-api#9631]
Proszę o aktywacje konta na sandbox.
Login: cksolutions
Mam problem z potwierdzeniem konta bankowego:
![obraz](https://github.com/user-attachments/assets/18c989ee-17db-4f36-b7e6-be130ae66077)

**Comment by Lukasz-Zurek** [comment]
@MarekCiecharowski Spróbuj jeszcze wykonać te czynności w trybie incognito. Niemniej jednak zgłosiłem ten problem dalej do weryfikacji.

**Comment by MarekCiecharowski** [comment]
Ok, przeszło, teraz mam komunikat "Czekamy na potwierdzenie rachunku bankowego przez weryfikatora płatności".
Jak długo to potrwa?
Kolejna sprawa to potwierdzenie tożsamości - jest to konto testowe, więc nie dodam prawdziwego skanu dowodu, a przy dodaniu jakiegokolwiek pliku mam błąd (poniżej) - jak to obejść?
![obraz](https://github.com/user-attachments/assets/29737377-9385-40de-800e-2f60d9c34bbc)

**Comment by Lukasz-Zurek** [comment]
@MarekCiecharowski Udało mi się ręcznie aktywować Twoje konto. Sprawdź proszę czy jest już ok.

**Comment by MarekCiecharowski** [comment]
Dziękuję, działa.
Mam jeszcze pytanie czy na sandobox działa dodawanie faktur do zamówień?
Realizuje to wg opisu: https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#jak-dodac-fakture-do-zamówienia.
Nie ma żadnego błędu, jako wynik dostaje status 200 ale przesłany plik nie dodaje się do zamówienia - sprawdzałem na zamówieniu da84a990-567e-11ef-b606-9bc49a2a9de3.
Z góry dziękuję za odpowiedź.

**Comment by MarekCiecharowski** [comment]
Jest ok, dziękuję za pomoc.
