### ISSUE TITLE
[REST] numery listów przewozowych oraz informacja o wysyłce

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#964]
Dzień dobry,
Jak w temacie,

Czy można via REST uzupełnić numer listu przewozowego w zamówieniu,
Czy można via REST uzupełnić informacje o tym że przesyłka jest już wysłana ?

Jeżeli nie to czy są takie plany ? 

pozdrawiamy wwwfactory

**Comment by PawelTaberski** [comment]
Obecnie nie ma możliwości dodania numeru przesyłki przez REST API, planujemy wdrożenie tego rozwiązania, możliwe że dedykowany zasób pojawi się już w tym miesiącu, jak tylko wdrożymy takie rozwiązanie poinformujemy o nim w dedykowanym komunikacie.

**Comment by wwwfactory** [comment]
Na pierwsze pytanie już nalazłem odpowiedź  w poście sprzed 8 dni. 
pozostaje pytanie drugie

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem, co masz na myśli przez przesyłka wysłana? Jeśli chodzi Tobie o status jaki jest dostępny przez front "Oznacz jako wysłane" to obecnie nie ma planów na wdrożenie takiego zasobu w REST API. Oznaczenie to służy tylko do filtrowania wiadomości przez front w zakładce Zamówienia.

**Comment by wwwfactory** [comment]
Okey, odpowiedź wyczerpująca.
Pojawia się jeszcze jedno pytanie, 
Czy po zaznaczeniu we froncie "oznacz jako wysłane" nie podejmujecie działać w stylu : wyślij do klienta powiadomienie o tym fakcie....

**Comment by PawelTaberski** [comment]
Tak, jak pisałem wcześniej ten status służy tylko do filtrowania i klient nie otrzymuje żadnego maila w tej sprawie. Wysyłamy do klienta informacje jak dodasz numer przesyłki.

**Comment by wwwfactory** [comment]
Dziękuję zamykamy...
