### ISSUE TITLE
Upload invoice file

### ISSUE THREAD

**Issue by MarekCiecharowski** [allegro/allegro-api#9643]
Dzień dobry

Mam pytanie dotyczące endointa: https://api.{environment}/order/checkout-forms/{id}/invoices/{invoiceId}/file
Jako body należy przesłać plik w formacie binarnym. Funkcja zwraca kod 200, plik pojawia się przy zamówieniu, ale jak próbuje pobrać pdfa  od strony zamówienia allegro to niestety nie otwiera się, jest uszkodzony.
Jakie powinno być kodowanie znaków przesyłanego pliku? Ja używam UTF8.
Numer zamówienia na sandboxie to da84a990-567e-11ef-b606-9bc49a2a9de3, a do zgłoszenia dołączam plik w formacie binarnym.
[plik.txt](https://github.com/user-attachments/files/16590314/plik.txt)

**Comment by Lukasz-Zurek** [comment]
Czy załączasz prawidłowy plik pdf? Dołączany przez Ciebie plik to TXT. Przetestowałem i po załączeniu prawidłowego pdf jest on prawidłowo wyświetlany po stronie kupującego.

**Comment by MarekCiecharowski** [comment]
Aby dołączyć plik pdf przez REST API muszę go skonwertować na: "string <binary> File in a binary format" (tak wynika z dokumentacji API).
To co przesłałem w pliku TXT to jest wynik tej konwersji z pdf na string binary.
Jak przesyłam na endpoint plik w takiej postaci jak w TXT to jest zwracany kod 200, plik jest dołączany do zamówienia w allegro.
Ale jak wejdę w ten plik po zalogowaniu się do sandbox, to jest on uszkodzony, nie otwiera się.
Stąd moje pytanie jak ma wyglądać ta konwersja z pdf na string binary, jaki format/kodowanie, itp?

**Comment by Lukasz-Zurek** [comment]
Nie wnikamy w sposób konwersji, wspieramy różne - niemniej jednak [tutaj](https://github.com/allegro/allegro-api/issues/5772) znajdziesz wątek, w którym inny użytkownik próbował dodać plik przy pomocy serwera Node.js i biblioteki Axios. Całkiem możliwe, że błąd leży po Twojej stronie np. plik nie jest konwertowany w całości.

Jeśli podasz szczegółowe dane, być może któryś z użytkowników forum będzie mógł Tobie pomóc.

**Comment by MarekCiecharowski** [comment]
Dziękuję za pomoc, okazało się, że to trywialnie proste.
Gdyby ktoś się z tym "męczył" w .NET to podaje kod w C#:
                byte[] fileByteArray = File.ReadAllBytes(filePath);
                var contentByteArray = new ByteArrayContent(fileByteArray);
                response = await _client.PutAsync(builder.Uri, contentByteArray);
Czyli należy przesłać tablicę bajtów, a nie stringa.
