### ISSUE TITLE
Pobranie etykiety przewoźnika

### ISSUE THREAD

**Issue by AccessDeniedException** [allegro/allegro-api#9648]
Czy jest możliwość pobrania etykiety przewoźnika do utworzonej przesyłki? Próbuję na sandboxie pobrać etykietę do utworzonej przesyłki, ale w pliku otrzymuję wyłącznie numer przesyłki i kod kreskowy bez danych Nadawcy, odbiorcy itp. W dokumentacji niestety nie znajduję nic na ten temat.

**Comment by Lukasz-Zurek** [comment]
Na sandboxie dla niektórych przewoźników możemy faktycznie zwracać sam kod kreskowy i tutaj niestety nie da się tego zmienić.

**Comment by AccessDeniedException** [comment]
Rozumiem, że na produkcyjnej wersji zamiast kodu kreskowego otrzymam prawidłową, pełną etykietę przewoźnika?
Mogę prosić o przykład takiej etykiety dla Allegro One Box, UPS lub DPD?

**Comment by Lukasz-Zurek** [comment]
@AccessDeniedException Tak na produkcji będzie już prawidłowa etykieta.

Dodam, że etykiety otrzymujemy bezpośrednio od przewoźników, więc nie jestem tutaj w stanie przesłać przykładowych.

**Comment by AccessDeniedException** [comment]
Dziękuję za odpowiedź.
