### ISSUE TITLE
[REST] zarządzanie finansami

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#965]
Witamy ponownie,
czy via REST jest/będzie możliwość sprawdzenia: 
"Lista wpłat od Kupujących",
"Lista moich wypłat",
"Saldo i wypłata środków"

ogólnie - zarządzanie finansami  ?
Pozdrawiamy wwwfactory

**Comment by PawelTaberski** [comment]
Najprawdopodobniej wdrożymy odpowiednie zasoby do obsługi tego typu zadań, ale nie znam dokładnej daty. Jak tylko będziemy mieli jakieś konkretne informacje w tym zakresie, to poinformujemy o tym w osobnym komunikacie.

**Comment by wwwfactory** [comment]
Dziękujemy zamykamy...
