### ISSUE TITLE
PHP query about the product

### ISSUE THREAD

**Issue by jprkna** [allegro/allegro-api#9653]
Zdravím,
rád bych vypsal pomocí PHP výpis svých produktů. Poté bych u jednotlivých produktů chtěl automaticky měnit počet kusů. 
Bohužel něco je špatně, nemohu si vypsat ani jedno zboží i když znám jeho offerId.
Vygeneroval jsem CLIENT ID a CLIENT SECRET, pomocí nich generuji access_token. To vše funguje.

Bohužel nemohu získat informace o zboží.
   
```
 $offerUrl = "https://api.allegro.pl/sale/product-offers/$offerId";
    $headers = [
        'Authorization: Bearer ' . $token,
        'Accept: application/vnd.allegro.public.v1+json',
    ];
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $offerUrl);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    $response = curl_exec($ch);
    $httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($httpcode == 200) {
        $data = json_decode($response, true);
        return $data;
    } else {
        echo "Chyba při získávání nabídky.\n";
        echo "HTTP Kód: " . $httpcode . "\n";
        echo "Odpověď: " . $response . "\n";
        exit;
    }
```

Odpověď je kód: 500:
{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Try again in a few minutes.","metadata":{}}]}

Kde je chyba?

**Comment by MaciejFrackowiak** [comment]
Please, give me a trace-id of your request.

**Comment by jprkna** [comment]
Here is the complete header of the response to the query for the specific item:
HTTP/2 500 expires: 0 cache-control: no-cache, no-store, max-age=0, must-revalidate x-xss-protection: 0 pragma: no-cache date: Fri, 16 Aug 2024 07:16:32 GMT trace-id: 48dbb91218cb6006 vary: Origin,Access-Control-Request-Method,Access-Control-Request-Headers content-type: application/json; charset=utf-8 x-frame-options: DENY strict-transport-security: max-age=15552000 x-content-type-options: nosniff

Thank you

**Comment by MaciejFrackowiak** [comment]
Thanks for the details.
To use [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getProductOffer) you have to use [code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow authorization. 
Client_credentials authorization, which you used doesn't have a user context, so you are not able to retrieve offer details.

**Comment by jprkna** [comment]
Thanks for the info, it's working now.
