### ISSUE TITLE
Asynchroniczne dodawanie oferty - odpytanie funkcji operations

### ISSUE THREAD

**Issue by bmusialekcepd** [allegro/allegro-api#9662]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

witam,

po asynchroniczmym dodaniu oferty odpytuje funkcje sprawdzania wykonania zadania:
trace_id 8b7a50619fdb0457

Oferta została dodana ponad godzine temy a dalej nie jest przetworzona

**Comment by bmusialekcepd** [comment]
czyli dalej zwraca status 200

**Comment by MaciejFrackowiak** [comment]
Jak widzę wskazana oferta jest aktywna, zadanie zostało zakończone.

**Comment by bmusialekcepd** [comment]
w takim razie kiedy ta metoda zwraca 303?

**Comment by bmusialekcepd** [comment]
zrobilem sobie kolejke w ktorej zbieram wszytskie operacje dla ofert dodawanych asynrhonicznie. Chcialem je wszytskie odpptywac az zaczna zwrac 303 zeby miec pewnosc ze wylapalem ewnetualne bledy i je zalogowac.

**Comment by MaciejFrackowiak** [comment]
Oprogramowanie, z którego korzystasz robi automatyczne przekierowanie z 303 do 200, stąd nie widzisz tego statusu.

**Comment by bmusialekcepd** [comment]
dzieki
