### ISSUE TITLE
GET /offers - get categories and filters

### ISSUE THREAD

**Issue by Stanislav93** [allegro/allegro-api#967]
Dzień dobry.

Korzystamy z REST API na życzenie - 

GET 
/offers{category.id}

Otrzymujemy dane -

 {"offers": [
    { produkty },
  ],
  "pageToken": {
    "next": "eyJwIjpbIjIiXSwibGltaXQiOlsiNjAiXX0=",
    "previous": null
  },
  "count": 121446,
  "fallbackMode": {
    "mode": "NONE"
  },
  "sponsoredOffers": [],
  "searchScenarioName": "baseline-cl-n-aut-1-2-1123"
}

Pomóżcie, jak uzyskać takie dane - 

{
  "items": {
    "promoted": [],
    "regular": []
  },
  "searchMeta": {
    "availableCount": 6000,
    "totalCount": 658170,
    "fallback": false
  },
  "categories": {
    "subcategories": [],
    "path": []
  },
  "filters": [],
  "sort": []
}

GET
/offers/listing{category.id}

Jak poprawnie zobacz filtry do kategorii?

**Comment by PawelTaberski** [comment]
Przykładowe w zapytanie w takim wypadku to `https://api.allegro.pl/offers/listing?category.id=78013`
Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/news/2018-07-03-listing_ofert/).
