### ISSUE TITLE
Zostałeś zablokowany.

### ISSUE THREAD

**Issue by michalevk** [allegro/allegro-api#9670]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ x] ze środowiskiem testowym / with the test environment
 - [ x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Hej, wyskakuje mi w api cały cały
{
	"url": "https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAYXzN1iaVTj4AuQtsOQ==&cid=_JldvO9dlmqwnaI1pt6yyd5os3s8hPghIAvzP6BoDoD9q6nT3RLQSw1zkuXvJgOYQyJz6XbLxMGoKUDxwb52UAFA3KwuN90EfTHwgtrJBAzQmSpo_o836uQPc~zh6O7Y&referer=https%3A%2F%2Fallegro.pl.allegrosandbox.pl%2Fsale%2Foffers&hash=77DC0FFBAA0B77570F6B414F8E5BDB&t=bv&s=29544&e=1b1ad8afac1486d334f18d426f55d07b5332ecc51c810b3dd14fa1cac85160db"
}
jak wejde na tą strone mam komunikat:
Zostałeś zablokowany.

Dlaczego zostałeś zablokowany? Coś w zachowaniu twojej przeglądarki zwróciło naszą uwagę. Powody mogą być różne:
 przeglądasz strony i klikasz dużo szybciej niż przeciętny człowiek
 coś uniemożliwia działanie Javascript na twoim komputerze
 w tej samej sieci (IP 185.11.108.57) operuje robot
Jeśli coś nie działa prawidłowo wyślij nam wiadomość.

ID: a429b27d-c39e-2e48-6d15-5c842fcd0d1c

Oczywiscie na sandboxie konto:pzevk

**Comment by MaciejFrackowiak** [comment]
Korzystaj z publicznego adresu wywołań API tj. https://api.allegro.pl.allegrosandbox.pl/
