### ISSUE TITLE
AccessDenied - pomimo posiadanych uprawnień

### ISSUE THREAD

**Issue by Dawid-Kowalczyk** [allegro/allegro-api#9673]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [X] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Opis:
- Endpoint: https://api.allegro.pl/pricing/offer-quotes?offer.id=XXX
- Response: {
    "errors": [
        {
            "code": "AccessDenied",
            "message": "Access is denied",
            "details": null,
            "path": null,
            "userMessage": "Brak dostępu do danego zasobu.",
            "metadata": {}
        }
    ]
}

Pomimo podania dobrego tokena(uprawnień na koncie) i parametrów w header - dostaje taką informację. Inne endpointy działają bez problemu.
Proszę o adres email na który mogę podać clientID w celu weryfikacji o co chodzi.

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swojego wywołania.

**Comment by Dawid-Kowalczyk** [comment]
trace-id: 4e02ecc2789745b9

**Comment by Dawid-Kowalczyk** [comment]
Token generowałem 3 razy - widzę że dane uprawnienia są już od początku założenia konta.
![Zrzut ekranu z 2024-08-19 09-59-21](https://github.com/user-attachments/assets/13c04a2a-b949-4487-b4f9-5b18793b6dc2)

**Comment by MaciejFrackowiak** [comment]
Musisz przejść proces autoryzacji raz jeszcze, aby aktualne scope zostały uwzględnione w tokenie. Nie wystarczy tylko odświeżyć aktualnego tokena.

**Comment by Dawid-Kowalczyk** [comment]
Zadziałało, dziękuje
