### ISSUE TITLE
HTTP 422 podczas aktualizacji ceny aukcji: "Please remove links to external sales websites outside Allegro"...

### ISSUE THREAD

**Issue by Pitupitupit** [allegro/allegro-api#9675]
Występuje problem:
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**

W odpowiedzi na żądanie aktualizujące cenę aukcji dostaliśmy kod http 422 z komunikatem: 
`Please remove links to external sales websites outside Allegro from the offer description. You can only provide links to websites that include additional information about the product.`

Przykładowy trace-id z 19.08 09:22:29 **1eac7996cd01d0ba** (z końcówki PUT /offers/xxx/change-price-commands/yyy)

Mimo błędu to z tego co widzę cena aukcji została zaktualizowana. 

Dlaczego podczas aktualizacji ceny dostajemy błąd dotyczący opisu aukcji?

Czy problematyczny link to https://support.apple.com/pl-pl/109522? Jeśli tak, to czy to nie jest błąd, że ten link powoduje problem? Zgodnie z komunikatem błędu jest to link z dodatkowymi informacjami o produkcie od producenta.

**Comment by MaciejFrackowiak** [comment]
Cena nie została zmieniona, ponieważ otrzymałeś wspomniany błąd 422. Co więcej, to nie jest oferta, tylko draft (publication.status=INACTIVE), zatem działa mechanizm walidujący jego poprawność. W celu wyjaśnienia już samej poprawności treści draftu, proszę Cię o kontakt z [obsługą serwisu](https://allegro.pl/pomoc/kontakt).

**Comment by Pitupitupit** [comment]
Dzięki za pomoc!

Patrzyłem na inną aukcję (inny rozmiar paska zegarka) dlatego sądziłem, że cena się zmieniła. Dodatkowo nie wiedziałem, że aukcja jest niekatywna.
