### ISSUE TITLE
Pobranie szczegółów oferty w Rest API

### ISSUE THREAD

**Issue by statmonitor** [allegro/allegro-api#968]
Planuję uruchomienie serwisu prezentującego statystyki sprzedaży. 
Aktualnie aby pobrać szczegóły oferty wraz z informacją o dokonanych zakupach używam metod WebApi: `doGetBidItem2`, `doGetItemsInfo`. 

1. Czy planujecie udostępnienie podobnych, zwracających informacje o dowolnej aukcji metod w Rest API?
2. Czy planowane jest usunięcie powyższych metod z WebApi, tak jak w przypadku `doGetItemsList`?

**Comment by PawelTaberski** [comment]
Niektóre z tych funkcjonalności jakie oferowały te metody już są dostępne w REST API. Metody do obsługi zamówień [opisaliśmy tutaj](https://developer.allegro.pl/orders/), a informacje o ofertach możesz pobrać np. przy pomocy [zasobu GET /offers/listing](https://developer.allegro.pl/documentation/#/offers-listing/getListing).
W przyszłości planujemy wyjście z WebAPI i całkowite przejście na REST API. Obecnie nie ma wyznaczonej dokładnej daty. Jak tylko będziemy mieć jakieś dokładniejsze informacje to poinformujemy o tym w osobnym komunikacie.
