### ISSUE TITLE
Prowizje od sprzedaży - jakie endpoint

### ISSUE THREAD

**Issue by Dawid-Kowalczyk** [allegro/allegro-api#9685]
Dzień dobry,
nie umiem znaleźć w dokumentacji informacji który endpoint mi zwróci Prowizje od sprzedaży dla danego id.

Proszę o info gdzie je znajdę lub proszę o podesłanie owego endpointa.

**Comment by MaciejFrackowiak** [comment]
Proszę skorzystaj z [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST).

**Comment by Dawid-Kowalczyk** [comment]
dziekuje
