### ISSUE TITLE
GetPostBuyFormsDataForSellersResponse - zwraca niepełne dane

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#969]
Występuje problem: 
 - [X] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Wygląda na to, że metoda DoGetPostBuyFormsDataForSellersRequest zwraca niepełne dane, o ile wywoływana jest dla wielu formularzy naraz.  W responsie wywołanym dla listy formularzy brakuje pola postBuyFormAdrId dla wysyłek w paczkomatach. W responsie dla pojedynczego  formularza wszystko jest OK. Problem pojawił się 05.12.2018 wieczorem, przedtem takich sytuacji nie było. Teraz jest dość częsty Wysyłam zestaw xmli dla jednego wybranego przypadku formularza 940982811 (20:43:29.472).

**Comment by PawelTaberski** [comment]
@lukada4100 Rzeczywiście dziwnie to wygląda, dostałem Twoje requesty i responsy i sprawę przekazałem do rozpatrzenia przez zespół zajmujący się tą funkcjonalnością, wygląda to na błąd.

**Comment by PawelTaberski** [comment]
Pracujemy nad rozwiązaniem tego problemu, prosiłbym o jeszcze trochę cierpliwości.

**Comment by lukada4100** [comment]
3 miesiączki minęły, wątek automatycznie się zamknął, a problemu wciąż nie udało się rozwiązać...
