### ISSUE TITLE
Pobieranie informacji na temat liczby aktywnych aukcji(doGetItemsList)

### ISSUE THREAD

**Issue by mwiercioch** [allegro/allegro-api#97]
Chciałbym pobrać dokładną liczbę wystawionych aukcji z podziałem na nowe oraz używane. Do tego celu wykorzystuję metodę doGetItemsList. Kiedy w filtrach ustawiam jedynie identyfikator użytkownika zwracana jest prawidłowo ilość(tak sama jak w panelu allegro, zakładka "sprzedaję"). Problem pojawia się gdy do filtrów dodaję kolejny element, czyli 'filterId' => 'condition'. Metodę wywołuję 2 razy. Za pierwszym razem filterValueId ustawiam na 'new', zaś drugim razem na 'used'. Suma pól "itemsCount" ze zwracanej struktury niestety nie jest równa(różnica to kilkanaście k aukcji) z tym co jest dostarczane bez użycia filtra 'condition'.

Moje pytanie brzmi, czy schemat który zaproponowałem do rozwiązania mojego zadania jest prawidłowy? Czy istnieje jeszcze jakiś stan poza new i user?
Z góry dzięki za pomoc.

**Comment by KrzysztofLukanowski** [comment]
Pytanie, czy wszystkie przedmioty mają określony parametr "Stan"? W części kategorii nie wymagamy tego parametru, dlatego różnica pomiędzy wynikami może być spowodowana brakiem "stanu" w niektórych ofertach.
