### ISSUE TITLE
Wystawianie opinii sprzedającym przez API

### ISSUE THREAD

**Issue by qqgg231** [allegro/allegro-api#970]
:bulb: **Sugestia**

Czy jest to w tej chwili możliwe? Nie mogę znaleźć takiego zasobu na https://developer.allegro.pl/documentation/ 

Jeśli nie jest możliwe , proszę o dodanie zasobu :-)

**Comment by MartaNowaczyk** [comment]
Na ten moment nie planujemy takiego zasobu, ale dziękujemy za sugestię.
