### ISSUE TITLE
HTTP 404 SHIPMENT_NOT_FOUND, POST ~/shipment-management/shipments/create-commands

### ISSUE THREAD

**Issue by Limokolo** [allegro/allegro-api#9704]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Request zwraca nieopisany dla endpointu w dokumentacji error HTTP 404.
TraceID: bde6ecb1a8756aa5
{
    "errors": [
        {
            "code": "SHIPMENT_NOT_FOUND",
            "message": "Requested shipment was not found",
            "details": "Requested shipment was not found",
            "path": "shipmentId",
            "userMessage": "Nie odnaleziono przewozu",
            "metadata": {}
        }
    ]
}

Ta sama metoda nie działa również dla przykładowych danych podanych na https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke
Trace-Id: 392b763027037a60

Prosiłbym o pomoc w zlokalizowaniu błędu.

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Zamiast metody POST korzystasz z GET - w tym przypadku status 404 jest prawidłowy i jest opisany w dokumentacji.

**Comment by Limokolo** [comment]
Okej, to rzeczywiście dość znacząca różnica. Niedopatrzenie braku "https" w Postmanie, który nie wysyła POST na http://
Gdyby ktoś mierzył się kiedykolwiek z podobnym problemem, niech upewni się, że link do endpointa jest https://
https://stackoverflow.com/a/28461500

Dzięki za pomoc
