### ISSUE TITLE
/sale/categories  zwraca błędne dane. 

### ISSUE THREAD

**Issue by PunktAutoCzesci** [allegro/allegro-api#9707]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

:beetle:
Cześć, mam problem z zasobem `/sale/categories`
API zwraca niewłaściwe wartości. Chodzi o to, że przy np. olejach silnikowych zwraca wartość **leaf** podczas gdy są  są jeszcze kategorie podrzędne. 

`trace-id ='72cc373bdd03aff'`

```
id ='253181'
leaf =true
name = 'Oleje silnikowe'
options = {variantsByColorPatternAllowed: true, advertisement: false, advertisementPriceOptional: false, offersWithProductPublicationEnabled: true, productCreationEnabled: true, …}
parent = {id: '18903'}
sciezka = 'Motoryzacja/Chemia/Oleje silnikowe'
```

Tak to wygląda od frontu:
https://allegro.pl/kategoria/253181
'Oleje silnikowe' to nie liść. Liście dla olejów silnikowych to: Mineralne, Półsyntetyczne, Syntetyczne

Z ciekawości spróbowałem pobrać dzieci "Olejów silnikowych." 
`/sale/categories?parent.id=253181`
zakończyło się niepowodzeniem
`trace-id = '33f8948cdc2ad76'`
a właściwie zwrotnie dostałem pustą tablicę `categories = [ ]`

Poradzicie coś na to? 
Dzięki

**Comment by MaciejFrackowiak** [comment]
Jest to prawidłowe działanie - w Allegro mamy dwa rodzaje kategorii:
- asortymentowe, czyli takie, w których sprzedajacy może wystawić ofertę - i te są dostępne w ramach zasobu GET /sale/categories;
- nawigacyjne, czyli dostępne tylko z punktu widzenia kupującego.

W Twoim przypadku kategorią liściem jest kategoria o id=253181. Wskazane przez Ciebie wartości: Mineralne, Półsyntetyczne, Syntetyczne występują jako parametr Rodzaj (id=250273) dla ww. kategorii.

**Comment by PunktAutoCzesci** [comment]
Ok dzięki, 
błąd wziął się z tego, że miałem produkt "Olej silnikowy Febi Bilstein 0W40 1 l 0W-40" który miał przypisaną kategorię id 253184 (Oleje syntetyczne). 
Prawdopodobnie na Allegro była zmiana kategorii, dlatego próbowałem wczytać nieistniejącą kategorię.

**Comment by PunktAutoCzesci** [comment]
Ok dzięki,
błąd wziął się z tego, że miałem produkt "Olej silnikowy Febi Bilstein 0W40 1 l 0W-40" który miał przypisaną kategorię id 253184 (Oleje syntetyczne).
Prawdopodobnie na Allegro była zmiana kategorii, dlatego próbowałem wczytać nieistniejącą kategorię.
