### ISSUE TITLE
[REST] http 500 w sale/offers 

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#971]
Dzień dobry

dotyczy sandbox
w dniu dzisiejszym metoda /sale/offers zwraca http 500 w mniej więcej 40% zapytań 

pozdrawiamy wwwfactory

**Comment by wwwfactory** [comment]
500 Error when searching seller offer (sellerId: 43955771, searchCriteria: {"limit":"20","offset":"0"};

**Comment by wwwfactory** [comment]
sytuacja wygląda już normalnie... zamykamy ?

**Comment by MartaNowaczyk** [comment]
sprawdziłam i dostaję poprawny status, także można zamknąć
