### ISSUE TITLE
Testowanie kampanii monetowej

### ISSUE THREAD

**Issue by Vitalka13** [allegro/allegro-api#9717]

**Comment by Vitalka13** [comment]
Dzień dobry!
Chcielibyśmy przetestować kampanię monetową na allegrosandbox, nasze konto Test_3PRozetka. Ale pokazuje nam, że nasze konto nie spełnia wszystkich warunków kampanii. Bardzo proszę o pomoc, co musimy zrobić, aby kampania była dostępną dla naszego konta?

**Comment by MaciejFrackowiak** [comment]
Udostępniliśmy opcję na Twoim koncie.

**Comment by Vitalka13** [comment]
Dzień dobry!
Czy mogę prosić jeszcze raz aktywować kampanię monetową, bo znowu jest nie dostępna.
![87878](https://github.com/user-attachments/assets/4b456ceb-8bfd-462b-85ed-f6ee80a5f749)

**Comment by Vitalka13** [comment]
działa, 
bardzo dziękuję!
