### ISSUE TITLE
Large number of unauthorized request

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#9718]
Hi, on production environment I have noticed significant number of responses from you API returning
````
{
    "timestamp": "2024-08-23T06:40:03.857+00:00",
    "path": "/v1/allegro-api/order/checkout-forms",
    "status": 401,
    "error": "Unauthorized",
    "requestId": "bc478cf1-146133"
}
````

I would like to understand what the problem is, as vast majority of request is ok. We sent 7000 request on this resource in last 2 day across all our partners, and get about 200x 401 responses. The rest was ok. Since the request seem exactly the same, I do not understand, why we would get authorization issues.

list of few example requests

5eb1b0e0-165450
5eb1b0e0-165374
bc478cf1-146133
bc478cf1-146100
bc478cf1-123395
bc478cf1-123348
5eb1b0e0-103900
5eb1b0e0-103847

Could you please let me know, what was wrong?

THX!

Jirka Z

**Comment by MartaNowaczyk** [comment]
Hi, the 401 is an authentication problem, but there is also an incorrect path to the resource, it should be [/order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET). In such cases, always provide the trace-id from the response header of the request with the error, and I will be able to help you better and faster.
