### ISSUE TITLE
Sandbox activation

### ISSUE THREAD

**Issue by SunkovyChlebiczek** [allegro/allegro-api#9722]
Hello, I would like to ask for activation of sandbox account with login 'scmuminci'. Also for confirmation of the bank account we chose 'standart/postal transfer'. Is that ok? Thanks in advace.

**Comment by MaciejFrackowiak** [comment]
Your account is active now.

**Comment by SunkovyChlebiczek** [comment]
Hello, could you please activate also sandbox account 'HvezdaSmrti'? Thank you in advance.

**Comment by Lukasz-Zurek** [comment]
@SunkovyChlebiczek Yes, I have just activated your account.

**Comment by SunkovyChlebiczek** [comment]
@Lukasz-Zurek Thank you.
