### ISSUE TITLE
Pytanie o "produktyzację"

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#973]
Panie i Panowie z Allegro: "Produktyzacja - grupujemy oferty z tym samym produktem".
Skoro zmiana wchodzi od stycznia to czy możemy poznać jej wpływ na Rest API?

**Comment by TimothyKoval** [comment]
Skąd te wieści?

**Comment by kfijalko** [comment]
https://allegro.pl/dla-sprzedajacych/produktyzacja-grupujemy-oferty-z-tym-samym-produktem-3GXjwznjziE

**Comment by MartaNowaczyk** [comment]
@kfijalko wraz z wprowadzeniem produktyzacji udostępnimy odpowiednie zasoby w REST API:
 - najpierw damy możliwość łączenia oferty z produktem,
 - potem możliwość dodania samego produktu.
Więcej szczegółów podamy wkrótce.

**Comment by MartaNowaczyk** [comment]
@martacronic tak jak pisałam, więcej szczegółów podamy wkrótce.

**Comment by MartaNowaczyk** [comment]
@martacronic @kfijalko pod tym [adresem](https://allegro.pl/dla-sprzedajacych/kategoria/produktyzacja) znajdziecie więcej informacji dotyczących produktyzacji w alllegro. Strona ta będzie uzupełniana o nowe informacje. Wiadomo, że REST API będzie działać na podobnej zasadzie, więc może wam się przydać jeśli jeszcze na nią nie trafiliście.

**Comment by martacronic** [comment]
Informację dla sprzedających przeczytałam bardzo uważnie. Wiem, że kilka tysięcy aukcji będzie wymagało jakiś zmian z mojej strony co wymaga czasu. Gdybym wiedziała co mam robić, to bym tego czasu nie marnowała i już dostosowywała moje aukcję.

W styczniu 2019 grupujecie już kategorie:
- Książki i Komiksy
- Smartfony i telefony komórkowe
- Telewizory

Gdyby to były moje kategorie, to wiem, że już bym nie miała szans zdążyć do końca stycznia. 
Jak były wprowadzane nowe opisy, to zajęło to nam pół roku, ale wiedzieliśmy, że do czerwca jest czas. Teraz zgrupujecie produkty i mimo, że aukcje będą istniały, to od strony efektywności sprzedaży jeśli nie będą w porę podpięte, to będą "martwe".

**Comment by kfijalko** [comment]
@MartaNowaczyk przeczytałem i nie chcę trafić na koniec listy ofert, gdzie nikt nie zagląda. 
Dlatego chciałbym jak najszybciej dostosować moje oferty. 
Jak pewnie w większości kategorii, w moich "częściach samochodowych" jest, mnóstwo małych sprzedawców, którzy przeklikają swoje oferty i podłączą pod produkty. Kilku dużych, którzy mają "opiekunów" i informacje dostają wcześniej.
Ja natomiast jestem za duży na małego i za mały na dużego, i wszystko muszę sam.
Apeluję do Was o jak najszybsze przekazanie informacji jak to ma działać.
Katalog produktów:
- na jakich zasadach definiujemy nowe produkty
- kto i jak weryfikuje czy są duble
- co jeżeli do produktu są podpięte oferty nie od tego produktu
i takie tam...?
Jak to się ma do przygotowywanego słownika zastosowań?
Najbardziej mnie interesuje kategoria "części samochodowe".

**Comment by MartaNowaczyk** [comment]
@martacronic w [artykule](https://allegro.pl/dla-sprzedajacych/kategoria/produktyzacja), który wcześniej podałam jest informacja jak należy się przygotować do tego tematu:

> Jak przygotować się do zmian
-Podaj kod EAN w ofercie:
  -- Jeżeli go rozpoznamy - możesz potwierdzić, że sprzedajesz dany produkt w ofercie
  -- Jeżeli go nie rozpoznamy - w przyszłości, na jego podstawie łatwiej wskażesz produkt w ofercie.
-Uzupełniaj wartości pozostałych parametrów, które w danej kategorii jednoznacznie identyfikują produkt, np. ISBN, Kod producenta, Oznaczenie kodowego modelu, etc.
-Zadbaj o poprawne wartości tych parametrów.
-Przypisz właściwy produkt do oferty w formularzu wystawiania. Uzupełnimy wtedy część parametrów w ofercie. Więcej informacji na temat tej opcji znajdziesz w [artykule w pomocy Allegro](https://allegro.pl/pomoc/faq/jak-powiazac-oferte-z-produktem-oGq7n07WYSq).

@kfijalko 
1. Model definiowania produktów jest jeszcze w trakcie prac
2. Duble zweryfikują nasze wewnętrzne mechanizmy
3. Będziemy je weryfikować i rozłączać, gdy ktoś niepoprawnie podepnie swoją ofertę pod produkt

**Comment by martacronic** [comment]
> 1. **Model definiowania produktów jest jeszcze w trakcie prac**

Minął miesiąc i zmiany od strony Allegro zaczynają być wdrażane w niektórych kategoriach, w dokumentacji Rest API nic do tego się nie pojawiło, a bot zamyka wątek.

**Comment by MartaNowaczyk** [comment]
@martacronic to duży projekt i jest dopracowywany. Jak tylko będzie to możliwe na pewno damy tu taką informację, ale w oddzielnym wątku. Spokojnie, nawet jak bot zamknie wątek taka informacja się pojawi, to bardzo ważny temat i dla was, i dla nas.

**Comment by kozoo** [comment]
@MartaNowaczyk , dla mnie ważne jest pytanie, czy w ramach produktyzacji allegro będzie banowało wszelkie aukcje tego samego produktu jednego użytkownika?

Chodzi mi o to czy będzie można wystawić 15x ten sam filtr powietrza o tym samym kodzie EAN: 5901234567890 pod ofertami:

Filtr oleju Audi
Filtr oleju VW
Filtr oleju Kolejna marka i model?

Czy to będzie dozwolone?

Proszę o odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Jest to dozwolone, jednak musisz liczyć się z tym, że zaniżysz w ten sposób popularność każdej z ofert.
