### ISSUE TITLE
Nowa metoda wysyłki - problemy z ulicami

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#9733]
:bulb: **Sugestia / Suggestions**

Dzień dobry,

w danych checkout form pobranych przez API, mamy tylko jedno pole w których są dane ulicy: buyer->address->street, np. "Lepino 7/1".

Natomiast w danych potrzebnych do stworzenia wysyłki nową metodą, czyli "https://api.{environment}/shipment-management/shipments/create-commands",

mamy wymagane już dwa pola dla odbiorcy:

receiver->street oraz receiver->streetNumber

gdzie jak rozumiem powinno być wpisane odpowiednio: "Lepino" oraz "7/1"

To jest poważny problem przy takiej strukturze jaką stworzyliście,  ponieważ nikt nie będzie tego wprowadzał / rozdzielał ręcznie, trzeba to robić automatycznie - przez rozdzielenie ciągu znaków wg. spacji na podciągi, traktując ostatni element jako numer ulicy.

Tyle tylko, że to będzie powodować błędy, kiedy klient wpisze numer niestandardowo, np. używając chociażby przez przypadek, dodatkowej spacji w numerze ulicy.

To co zrobiliście, to bez wątpliwości POWAŻNY BŁĄD PROJEKTOWY.

Apeluję o zmianę pola "streenNumber" na opcjonalne z wymaganego, lub całkowite jego usunięcie tak jak to jest teraz w starej metodzie, inaczej może to powodować poważne problemy z dostawami.

**Comment by MartaNowaczyk** [comment]
Dzień dobry, mamy 2 sugestie dotyczące tego problemu, dopisz proszę tam swoje komentarze:
- https://github.com/allegro/allegro-api/discussions/9218
- https://github.com/allegro/allegro-api/discussions/9217
Wiem, że na ten moment nie ma w planach rozdzielenia tego w zamówieniu, ale nowe głosy są ważne, bo dzięki temu widać jak potrzebna jest taka zmiana.

**Comment by tztztztz** [comment]
Dla mnie obydwa rozwiązania są sensowne, i zagłosowałem za nimi.

**Comment by tztztztz** [comment]
Kwestia tylko jak w najlepszy sposób śledzić ewentualną zmianę którą wykonacie w tym nowym mechanizmie? Będzie jakieś powiadomienie wysłane?

**Comment by MartaNowaczyk** [comment]
Nie wiemy jeszcze czy i kiedy wdrożymy taką zmianę, ale wszystkie zmiany komunikujemy na GH, na stronie w [Aktualnościach](https://developer.allegro.pl/news) oraz przesyłamy w [newsletterze](https://developer.allegro.pl/newsletter).
