### ISSUE TITLE
Fidy dostaw

### ISSUE THREAD

**Issue by SoftSolid** [allegro/allegro-api#974]
Podczas wystawiania aukcji pojawia się taki komunikat:
"Problem z wystawieniem aukcji - Niepoprawna wartość w polu formularza sprzedaży (np. zbyt duża ilość znaków w tytule oferty). Kurier DPD pobraniowy (kolejna sztuka) - fid: 206"

Czy coś się zmieniło z fidami dostaw ?

**Comment by MartaNowaczyk** [comment]
@SoftSolid Nic nie zmienialiśmy. Sprawdź proszę czy wprowadziłeś poprawne wartości w tym polu. Jeśli problem będzie nadal występował podeślij response i request w XML (możesz też skorzystać z [formularza](https://allegro.pl/pomoc/kontakt) do przesłania danych).

**Comment by SoftSolid** [comment]
Czy w metodzie doNewAuctionExt dostępne są nowe sposoby dostawy ? DPD (fid 107,207,307) i DPD pobranie (fid 106,206,306) ?

**Comment by MartaNowaczyk** [comment]
@SoftSolid Podane metody dostawy [udostępniliśmy w marcu 2018](https://allegro.pl/webapi/news.php/page,5#news_100600). Oprócz standardowego pola Przesyłka kurierska (fid 44,144,244 i 45,145,245) są dostępne oddzielne pola dla konkretnych przewoźników.

**Comment by SoftSolid** [comment]
Czy te dodane dostawy działają starym API ? w metodzie doNewAuctionExt ?

**Comment by MartaNowaczyk** [comment]
tak, powinny działać dla doNewAuctionExt. Masz jakiś problem z ich dodaniem?

**Comment by SoftSolid** [comment]
Tak. 
Pojawia mi się komunikat "Problem z wystawieniem aukcji - Niepoprawna wartość w polu formularza sprzedaży (np. zbyt duża ilość znaków w tytule oferty). Kurier DPD pobraniowy (kolejna sztuka) - fid: 206".
Jeśli usunę dostwy DPD z cennika dostaw to aukcja wystawia się bez problemu.

**Comment by MartaNowaczyk** [comment]
@SoftSolid sprawdziłam i nie mam problemu z dodaniem przesyłki DPD (fidy 106,206,306).  
Podeślij proszę request i response w formacie XML dla wywołania, które zwraca błąd (jeśli chcesz możesz zrobić to przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) allegro z dopiskiem, że sprawa dotyczy zgłoszenia #974 na GitHubie)

**Comment by SoftSolid** [comment]
Wysłane.

**Comment by MartaNowaczyk** [comment]
Z tego co widzę wartość dla np. fid 306 powinna być typu integer, bo to ilość w paczce. Sprawdź też pozostałe. Tylko przy takim problemie powienieneś dostać inny błąd.  Na początek sprawdź to. 
Poza tym nie jest to xml i nie widziałam w przesłanym pliku komunikatu błędu.

**Comment by SoftSolid** [comment]
Zmieniłem to i nie ma poprawy.
Taki jest błąd zwracany przez wasz system
ERR_INVALID_VALUE_IN_ATTRIB_FIELD

**Comment by SoftSolid** [comment]
Dobra już chyba wiem w czym jest problem. Dam znać.

**Comment by SoftSolid** [comment]
Rozwiązane. Dzięki.
