### ISSUE TITLE
Integracja / Pobieranie aukcji do woocommerce

### ISSUE THREAD

**Issue by programista-nautil** [allegro/allegro-api#9741]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Stworzyłem wtyczkę na wordpressa do Swoich potrzeb, która importuje aukcje z allegro do woocommerce.
Wszystko działało poprawnie aż do dzisiaj. 

Dostałem w logach info, że token wygasł. Wygenerowałem nowy i jest informacja, że wygenerował się poprawnie ale teraz dostaje cały czas błąd 

```
 [27-Aug-2024 07:42:48 UTC] Rozpoczęcie procesu dla ID aukcji: 15321702611
[27-Aug-2024 07:42:48 UTC] Błąd w odpowiedzi z API Allegro: 500 - {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Try again in a few minutes.","metadata":{}}]}
[27-Aug-2024 07:42:48 UTC] Kod błędu: INTERNAL_SERVER_ERROR
[27-Aug-2024 07:42:48 UTC] Komunikat błędu: Internal server error.
[27-Aug-2024 07:42:48 UTC] Dodatkowe informacje: Array
(
    [code] => INTERNAL_SERVER_ERROR
    [message] => Internal server error.
    [details] => 
    [path] => 
    [userMessage] => Internal server error. Try again in a few minutes.
    [metadata] => Array
        (
        )

)
```
kawałek funkcji do pobierania info konkretnej aukcji 
```

function get_allegro_auction($auction_id, $token) {
    $api_url = "https://api.allegro.pl/sale/product-offers/$auction_id"; 

    $response = wp_remote_get($api_url, array(
        'headers' => array(
            'Authorization' => 'Bearer ' . $token,
            'Accept' => 'application/vnd.allegro.public.v1+json',
            'User-Agent' => 'YourAppName/1.0 (yourname@example.com)'
        )
    ));

    if (is_wp_error($response)) {
        error_log('Błąd podczas pobierania aukcji z API Allegro: ' . $response->get_error_message());
        return false;
    }
```

Sprawdzałem statusy API to wszystkie działają, co mogę sprawdzić, gdzie szukać problemu ?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swojego wywołania.

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem logi - korzystasz z autoryzacji Client_credentials - aby pobrać szczegóły oferty musisz skorzystać z autoryzacji typu "bearer-token-for-user", czyli [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow.

**Comment by programista-nautil** [comment]
Proszę: 
Trace-ID: 4ed6db29337f759a

**Comment by MaciejFrackowiak** [comment]
Dziękuję za trace-id - powód błędu już wyżej wskazałem.

**Comment by programista-nautil** [comment]
> Sprawdziłem logi - korzystasz z autoryzacji Client_credentials - aby pobrać szczegóły oferty musisz skorzystać z autoryzacji typu "bearer-token-for-user", czyli [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow.

Bardzo dziękuję na nakierowanie. 

Wszystko już działa poprawnie :)
