### ISSUE TITLE
Rabat ilościowy a strefa okazji.

### ISSUE THREAD

**Issue by kris86k** [allegro/allegro-api#975]
Witam.
Czy nie odnotowaliście kiedykolwiek błędu z dodawanie rabatów ilościowych do "Strefa okazji - rabaty"?
Mam na myśli czy przy dodawaniu rabatów do ofert przez restapi te oferty nie były w wyniku błędu automatycznie zgłaszane do "strefy okazji-rabaty"?
Mam z tym problem bo nie zgłaszałem się do strefy okazji, a mimo to oferty się w niej znalazły. Prawdopodobnie doszło do tego w okolicach 5.11.2018.

Id przykładowych ofert: 7500846853, 7019262388, 6756248898, 6756249583.

Czy możecie mi podesłać log w którym, będzie informacja kiedy i w jaki sposób oferty zostały zgłoszone do strefy okazji - rabaty?

**Comment by MartaNowaczyk** [comment]
@kris86k nie jest to błąd. Zgodnie z podanymi [informacjami](https://allegro.pl/dla-sprzedajacych/sprawdz-dlaczego-warto-i-jak-skorzystac-ze-specjalnych-oznaczen-ofert-w-strefie-okazji-z8eYgE9Xefk) rabaty to też Strefa Okazji.

**Comment by kris86k** [comment]
W regulaminie jest napisane, że ofertę do strefy okazji trzeba złożyć ręcznie. Gdzie jest napisane, że dodanie rabatu ilościowego przez api do oferty skutkuje dodaniem do "strefy okazji - rabaty" ? Przecież to dwie oddzielne usługi. Żeby dodać ofertę z rabatem ilościowym do "Strefy okazji - rabaty" przez www należy zaptaszkować odpowiednie pole. Coś tu nie gra. Proszę zwrócić uwagę, że co innego to "strefa okazji - rabaty", a co innego rabat ilościowy w ofercie.

**Comment by MartaNowaczyk** [comment]
@kris86k w ramach Strefy Okazji możesz skorzystać z różnych oznaczeń ofert, w tym rabatów o których piszesz. Nie jest to jednoznaczne z trafieniem na [listę ofert w Strefie Okazji](https://allegro.pl/strefaokazji) - aby tu trafić należy wybrać oznaczenie okazja.
Oferta oznaczona jako rabat ilościowy wyświetla się tak samo jak wcześniej - z oznaczeniem rabatu na liście ofert w danej kategori/wyszukiwaniu czy na stronie oferty.

O tym, że rabaty ilościowe i inne oznaczenia są formalnie przypisane do Strefy Okazji mówi pkt III [regulaminu](https://allegro.pl/regulaminy/regulamin-strefy-okazji-9dGVAPB69In).

**Comment by kris86k** [comment]
Nie mówię, że formalnie tak nie jest ale żeby trafić do strefy okazji z poziomu www należy zaptaszkować odpowiednie pole podczas dodawania rabatu. Jak to się odbywa z poziomu API? Nie widzę rozgraniczenia na API i www zatem albo jest błąd i to zgłoszenie odbywa się bez wiedzy i zgody użytkownika albo się nie odbywa i ta sytuacja dotknęła tylko mnie.

**Comment by MartaNowaczyk** [comment]
@kris86k w takim razie podeślij proszę zrzut z listy ofert Strefy Okazji, gdzie widać twoją ofertę z rabatem ilościowym.

> "Możesz zwiększyć liczbę sztuk lub przedmiotów, które sprzedajesz w ramach jednej transakcji. Dodaj rabat ilościowy do swoich ofert - klient zapłaci mniej za kilka przedmiotów, a ty zwiększysz swoją sprzedaż Bez dodatkowych opłat.

Dodać rabat na stronę oferty możesz bezpłatnie, ale samo oznaczenie na liście ofert specjalnym oznaczeniem jest płatne:

>"Możesz również, dodatkowo, oznaczyć rabat na listach ofert. Oznaczenie na liście ofert jest płatne. Stawki tej prowizji określa Załącznik nr 1 do Regulaminu Okazji pkt. 3."

**Comment by kris86k** [comment]
Np: 7183969884 To jest oferta która została oznaczona wczoraj...
Tej jest dużo. Za sam listopad zostało mi naliczone kilkaset złotych podwojonej prowizji z tego tytułu...

**Comment by PawelTaberski** [comment]
@kris86k W tych temat proszę pisz do nas przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) tutaj rozwiązujemy tylko tematy związane z API Allegro na wysokość opłat i typy nie mamy wpływu ani dokładnej wiedzy o stawkach itp.

**Comment by kris86k** [comment]
Jestem w kontakcie z obsługą. Proszę o jasną informację. Czy rabat do oferty dodawany przez Rest API zgłasza ofertę do "Strefa okazji - Rabaty"?
Pytanie drugie jeśli na pierwsze odpowiedź brzmi tak. Dlaczego i czy jest możliwość aby tak się nie działo?

**Comment by PawelTaberski** [comment]
Wszystkie oznaczenia są w strefie okazji i są to płatne oznaczenia i tak dodanie oznaczenia powoduje, że oferta pojawia się w strefie okazji.
Jeśli nie chcesz aby oferta była w strefie możesz po prostu dodać rabaty ilościowe bez płatnych oznaczeń.

**Comment by PawelTaberski** [comment]
@kris86k Nie bardzo rozumiem o co jeszcze pytasz wydaje mi się, że jasno odpowiedziałem, że dodanie płatnego oznaczenia powoduje pojawienie się oferty w strefie okazji. Nie ma oznaczeń poza strefą. Jak nie chcesz, aby była w strefie okazji to nie może mieć płatnych oznaczeń.

**Comment by kris86k** [comment]
Wyjaśniłem do dokładnie ale ponowię pytanie. Są dwie usługi. "Rabat ilościowy w ofercie" oraz oznaczenie "Strefa okazji - rabaty". To drugie jest płatne ale dodanie rabatu ilościowego do oferty nie jest płatne co potwierdza strona strona informacyjna rabatów. https://allegro.pl/dla-sprzedajacych/rabaty-ilosciowe-XE2m69YqPIo
Cytuję:
> Możesz zwiększyć liczbę sztuk lub przedmiotów, które sprzedajesz w ramach jednej transakcji. Dodaj rabat ilościowy do swoich ofert - klient zapłaci mniej za kilka przedmiotów, a ty zwiększysz swoją sprzedaż **Bez dodatkowych opłat.**

Zgadza się?

Zgłoszenie do "Strefa okazji - Rabaty" przez www odbywa się poprzez zaptaszkowanie odpowiedniego pola przy dodawaniu rabatu czyli zgodnie z regulaminem wymagane jest zgłoszenie przez sprzedawcę. Nie dzieje się to automatycznie. Tu wszystko jest OK.
Moje pytanie po raz kolejny brzmi czy przy dodawaniu "rabatu ilościowego do oferty" przez Rest API (POST /sale/loyalty/promotions) taka oferta jest automatycznie zgłaszana do "Strefa okazji - Rabaty". 
Tak lub nie.

**Comment by MartaNowaczyk** [comment]
Nie, dlatego prosiłam o zrzut jeśli widzisz taką ofertę na liście ofert. Na liście znajdziesz się dopiero wtedy,  gdy skorzystasz z zasobu do składania wniosku o włączenie płatnego oznaczania rabatu ilościowego w ofercie POST /sale/loyalty/promotion-campaigns.

**Comment by MartaNowaczyk** [comment]
@kris86k sprawdzamy czy nie ma tu błędu. Proszę o trochę cierpliwości.

**Comment by MartaNowaczyk** [comment]
Sprawdziliśmy i nie ma błędu po naszej stronie. Z analizy wynika, że rabaty ilościowe były włączone wcześniej - jeszcze przed tym jak za oznaczenia naliczaliśmy opłaty. 
Była komunikacja, że należy wyłączyć płatne oznaczenia, żeby uniknąć opłat. Wysyłaliśmy mailing "Wprowadzamy opłatę za oznaczenie rabatu na listach ofert" i [zapowiedź zmiany](https://allegro.pl/pomoc/aktualnosci/5-listopada-zmiana-regulaminu-strefy-okazji-allegro-wqA9ydArGSb) oraz samą [zmianę ](https://allegro.pl/pomoc/aktualnosci/zmiana-regulaminu-strefy-okazji-allegro-R8nYe3rxgsq) w regulaminie. 
Błędu technicznego nie stwierdziliśmy, dlatego resztę spraw proszę kierować przez formularz kontaktowy z naszą obsługą.

**Comment by Netkomzyrardow** [comment]
Witam. Mam praktycznie identyczny problem. Nigdy nie zgłaszałem chęci uczestniczenia w Strefie okazji i nigdy nie zaznaczalem w rabatach ilościowych funkcji specjalnego oznaczenia a mimo to od kilku dni zostały mi doliczone opłaty z tytułu korzystania z w/w opcji w wyniku czego naliczyło mi kilkanaście tys zł rachunku Allegro. Widzę że mój przypadek zatem nie jest jednostkowy. Jak sie zakończyła sprawa u Pana?

**Comment by MartaNowaczyk** [comment]
@Netkomzyrardow Skontaktuj się proszę w tej sprawie przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) tutaj rozwiązujemy tylko tematy związane z API Allegro, a naliczenie opłat to już inna kwestia.

**Comment by kris86k** [comment]
Pozwolę sobie jednak odpisać.
Generalnie skończyło się na niczym. Allegro twierdzi, że wysyłało powiadomienia odnośnie opłat. Ja tych opcji nie włączałem, oni twierdzą, że były włączone przed wejściem opłat i powinienem je wyłączyć sam...
Napisz co Ci odpisali do mnie na priv lub krzysiek@kg-gsm.pl

**Comment by tapety** [comment]
WItam ja mam identyczny problem w listopadzie włączyłem rabat ilościowy we wszystkich aukcjach i NIGDZIE nie było napisane, że jest to płatne a nawet po wejściu w "dowiedz się więcej" jest dwukrotnie podkreślone sformułowanie " klient zapłaci mniej za kilka przedmiotów, a ty zwiększysz swoją sprzedaż **bez dodatkowych opłat**." J nie wyrażałem zgody na wzięcie udziału w kampani strefa okazji rabaty tylko chciałem mieć rabat ilościowy. Allegro naliczyło mi ok 4000zł. Jeszcze nie odpowiedzieli ale widzę po postach czego mogę się spodziewać. W najgorszym wypadku skończy się w sądzie bo to co Allegro zrobiło nie jest normalne i jak widzę nie jestem w tym sam. Jak by miał ktoś jakieś informację proszę pisać: kaseton1@o2.pl

**Comment by MartaNowaczyk** [comment]
@tapety tak jak pisałam w innych przypadkach, w tej sprawie proszę pisać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=8d8fa12b-0b41-421c-bf52-c0431e42119f).
