### ISSUE TITLE
POST /shipment-management/shipments/create-commands method not allowed

### ISSUE THREAD

**Issue by IT-nutri** [allegro/allegro-api#9755]
Witam,

Wdrażamy nowe endpointy do naszej aplikacji,

Zostały one wprowadzone jak poniżej

'api'  => [
            'parcel' => [
                /**
                 * Use this resource to create parcel for delivery.
                 * Method: POST
                 * https://developer.allegro.pl/documentation/#operation/createNewParcel
                 */
                //'create'          => '/parcel-management/parcel-create-commands/',
                'create'      => '/shipment-management/shipments/create-commands',
                /**
                 * Use this resource to get parcel creation status.
                 * Method: GET
                 * https://developer.allegro.pl/documentation/#operation/getParcelCreationStatus
                 */
                //'creation_status' => '/parcel-management/parcel-create-commands/',
                'creation_status' => '/shipment-management/shipments/create-commands/',
                /**
                 * Use this resource to get label for created parcel.
                 * Returned content type depends on created parcel.
                 * Method: POST
                 * https://developer.allegro.pl/documentation/#operation/getParcelLabel
                 */
                //'get_label'       => '/parcel-management/parcels/label',
                'get_label'         => '/shipment-management/label',
            ]
        ]
        
        W momencie processowania zamówień, wszystkie zamówienia są zgodnie processowane. Problem występuje w przypadku Allegro One Box
        
        [OrderToReceipt] Błąd fis zam.: Nie udało się wygenerować etykiety Allegro ONE: Client error: `PUT https://api.allegro.pl/shipment-management/shipments/create-commands254c9fcf-11ab-4747-b3a4-9246c0631b95` resulted in a `405 Method Not Allowed` response:
{"errors":[{"code":"NotAllowedException","message":"The HTTP method is not allowed","details":null,"path":null,"userMess (truncated...)
, numer:6898752

Endpointy są wdrożone według instrukcji
  
 Utwórz nową paczkę	
[PUT /parcel-management/parcel-create-commands/{commandId}]       
[POST /shipment-management/shipments/create-commands]

Dlaczego problem method not allowed występuje tylko w przypadku Allegro One Box a w każdym innym wypadku inpost, kurier etc, zamówienia przechodzą normalnie?

**Comment by MartaNowaczyk** [comment]
Witam, dla nowego WZA (shipment-management) mamy metodę POST, a commandId podajemy w ścieżce lub wcale. W podesłanych danych z waszego systemu widać `PUT https://api.allegro.pl/shipment-management/shipments/create-commands254c9fcf-11ab-4747-b3a4-9246c0631b95`, więc nie wygląda to poprawnie. Sprawdź działanie swojej aplikacji, a do weryfikacji przesyłaj proszę trace-id, który zwracamy w nagłówku odpowiedzi.

**Comment by IT-nutri** [comment]
Jak wyjaśniłem, podczas processowania zamówień przeszło około 7 zamówień, 6 to były kurier i inpost (wszystkie z allegro) a podczas procesowania zamówienia allegro one box z dostawa do punktu orlen paczka otrzymałem w.w error.

Problem w tym, że w kodzie aplikacji nie ma nigdzie metody PUT. 

Gdyby problem rzeczywiście dotyczył ścieżki i commandId, to dlaczego 6 kolejnych zamówień poszło bez problemu a tylko to jedno nie?

POST https://api.allegro.pl/shipment-management/shipments/create-commands/254c9fcf-11ab-4747-b3a4-9246c0631b95

Czy taka ścieżka będzie poprawna w takim razie? Ponieważ na stronie developerskiej jest adres api POST /shipment-management/shipments/create-commands bez / na końcu

Prosiłbym o wyjaśnienie tych kwestii i rozpoczniemy analizę kodu aplikacji.

**Comment by MartaNowaczyk** [comment]
Dlatego do weryfikacji potrzebuję trace-id, abym mogła namierzyć ten problem u nas w logach. CommandId może być w body lub wcale, w ścieżce nie dla nowego WZA - poprawiłam to we wcześniejszej wiadomości.

**Comment by IT-nutri** [comment]
Okazało się, że problem mógł dotyczyć cache aplikacji. Na chwile obecną nie udało się odtworzyć problemu - prosiłbym o zamknięcie.

**Comment by MartaNowaczyk** [comment]
Rozumiem, dziękuję za informację. Zamykam.
