### ISSUE TITLE
Zbiorczy protokół nadania przesyłek Allegro DHL - drukują sie pojedyńcze protokoły (Śnieżka SA)

### ISSUE THREAD

**Issue by fmikasniezka** [allegro/allegro-api#9756]
Dzień dobry,
Od mniej więcej początku lipca drukują się pojedyncze protokoły nadania przesyłek dla Allegro DHL. 
Powinien być jeden zbiorczy.
Czy są Państwo w stanie zmienić to tak by działało to jak dawniej?

**Comment by MartaNowaczyk** [comment]
Dzień dobry, generalnie protokoły powinny generować się zbiorczo. Czy możesz podać konkretny przykład gdzie nie dostajesz zbiorczego protokołu?

**Comment by fmikasniezka** [comment]
Wszystko działa już jednak poprawnie.
Zamykam.
