### ISSUE TITLE
Parcel-management - błąd zakładania przesyłki

### ISSUE THREAD

**Issue by Wojtu204** [allegro/allegro-api#9759]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry
Przy zakładaniu paczki na zasobie:
https://api.allegro.pl/parcel-management/parcel-create-commands

Dla niektórych przesyłek otrzymujemy komunikat błędu:
{
    "id": "dc670bbe-b135-44ce-9541-4b7066d4e6d5",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "SHIPMENT_VALIDATION_ERROR",
            "message": "Entered text exceeds 20 characters",
            "details": "Shipment request has validation errors",
            "path": "/parcel-management/parcel-create-commands/dc670bbe-b135-44ce-9541-4b7066d4e6d5",
            "userMessage": "Długość podanego tekstu przekracza 20 znaków"
        }
    ]
}

Przykładowe ID komend, dla których mamy błąd:
dc670bbe-b135-44ce-9541-4b7066d4e6d5
b2076759-f55c-4602-b3e3-db3e581cb104
2294f9fe-7f7b-4704-a827-107262ede71e
a7727ae4-2fa8-45ed-af10-81ec793207bb
18b8f828-8785-4bde-8241-fdb8e7d1653b

Proszę o weryfikację i poprawę. Zapytania z tych komend nie różnią się strukturą od poprawnie procesowanych.

Dziękuję i pozdrawiam
Wojtek

**Comment by MartaNowaczyk** [comment]
Dzień dobry, to pewnie limit znaków w "description". Limity są różne i na sztywno ustawione przez przewoźników. W tym konkretnym przypadku trzeba się zmieścić w 20 znakach.
