### ISSUE TITLE
Issue with aplication scope - AccessDenied

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#9763]
HI, I was not able to access shipment-management/delivery-services resource. I was getting 403 with "AccessDenied" errorCode. I found in issues, the issue should be with our application scope not containing "allegro:api:shipments:read" and "allegro:api:shipments:write".
I have checked the application (clientId: c3713a327d0d4248815c7e668d5fe844) and I can see both options enabled.
![image](https://github.com/user-attachments/assets/f82c3e8b-ab89-47ea-96cc-821f81c3a7a3)

However I cannot get the response. I have also decoded token and it does not have these two options in scope. I have checked clientId matches. Could you advise please?

````
{
  "user_name": "111533210",
  "scope": [
    "allegro:api:orders:read",
    "allegro:api:fulfillment:read",
    "allegro:api:profile:write",
    "allegro:api:sale:offers:write",
    "allegro:api:fulfillment:write",
    "allegro:api:billing:read",
    "allegro:api:campaigns",
    "allegro:api:disputes",
    "allegro:api:sale:offers:read",
    "allegro:api:bids",
    "allegro:api:orders:write",
    "allegro:api:ads",
    "allegro:api:payments:write",
    "allegro:api:sale:settings:write",
    "allegro:api:profile:read",
    "allegro:api:sale:settings:read",
    "allegro:api:payments:read",
    "allegro:api:messaging"
  ],
  "allegro_api": true,
  "iss": "https://allegro.pl",
  "exp": 1724872027,
  "jti": "1b91ae9a-9751-48d4-b404-0ecbe5a8339b",
  "client_id": "c3713a327d0d4248815c7e668d5fe844"
}
````

THX. Jirka Z

**Comment by AureliuszBrussy** [comment]
It may take a few minutes to propagate the scope change. In addition, you should generate a entirely new access and refresh token pair- do not use the refresh token generated before the scope change, as it will have the same scopes as before the change.

**Comment by ZajdaBear** [comment]
Thanks!, we have unlinked the app and linked it back and that seems to do the trick.

Jirka
