### ISSUE TITLE
Problem ze zleceniem wysyłki zamówienia na czeski Parcelbox

### ISSUE THREAD

**Issue by powroznikOmg** [allegro/allegro-api#9769]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Opis
Dzień dobry. Mam problem ze zrealizowaniem jednego z zamówień na Allegro obsługiwane metodą wysyłki jak na screenie:
![image](https://github.com/user-attachments/assets/ddfee92d-74e3-408a-8ae3-455520b5492e)
Problem w tym, że nie umiem znaleźć odpowiedniego paczkomatu odpytując zasób: https://api.allegro.pl/order/carriers/ALLEGRO/points
Przy próbie złożenia zamówienia na nr paczkomatu jaki otrzymałem otrzymuje komunikat API:
Wybrany Punkt odbioru nie jest obsługiwany przez tego przewoźnika
Poniżej zamieszczam zwrotkę  z powyższego requesta. Nie umiem znaleźć odpowiedniego paczkomatu ani po frazie ALZA ani ALWD.
[paczkomatyALlegro.txt](https://github.com/user-attachments/files/16796339/paczkomatyALlegro.txt)

Proszę o szybkie rozpatrzenie problemu, gdyż ze względu na restrykcyjne zasady terminowości realizacji zamówienia musimy jak najszybciej zrealizować to zamówienie

**Comment by MaciejFrackowiak** [comment]
Endpoint [GET /order/carriers/ALLEGRO/points](https://developer.allegro.pl/documentation/#operation/getAllegroPickupDropOffPointsGET) zwraca punkty odbioru przesyłek wyłącznie dla usługi Allegro One. W swoim zamówieniu masz wskazaną inną metodę dostawy - Allegro International wraz z podanym konkretnym punktem dostawy wybranym przez kupującego.

**Comment by powroznikOmg** [comment]
W takim razie jaką metodą WS mogę odpytać o paczkomaty z Czech? Mam problem, że zamówienie do systemu spływa nam jako ALZABOX i dotychczas udawało się je realizować. To przeszło kiedy podałem numer ALWD, ale nie zmieniłem metody dostawy, ponieważ w requeście do zamówienia podałem właściwą (0e40225c-32c6-4602-b78f-b3146fe9f54a)

**Comment by MaciejFrackowiak** [comment]
Takie informacje pobierzesz tylko z API danego operatora logistycznego.

**Comment by powroznikOmg** [comment]
Dziękuję za szybką pomoc. Zamykam temat
