### ISSUE TITLE
Jaka jest procedura oznaczania "wysłane"

### ISSUE THREAD

**Issue by Krystus** [allegro/allegro-api#977]
Pobieram zamówienie przez **order/checkout-forms**, pobieram szczegóły poszczególnych zamówień przez **/order/checkout-forms/{checkoutForm_id}**. Zamówienie zrealizowałem po stronie autorskiego panelu (faktura, etykieta, fizyczna realizacja).

Po swojej stronie mogę odznaczyć, że gotowe. Jak do Allegro posłać info "wysłane" by nie robić tego kilka razy? Przy okazji jest metoda na przesłanie info do klienta o etykiecie?

**Comment by MartaNowaczyk** [comment]
@Krystus "wysłane" o których piszesz to tylko oznaczenie na froncie - nie ma go w REST API. Oznaczenie to pozwala sprzedającym, którzy korzystają tylko z zakładek allegro do zarządzania swoją sprzedażą, filtrować swoje zamówienia. Nawet wtedy żadna informacja (powiadomienie) nie trafia do kupującego.
Nie planujemy takiego oznaczenia dodawać do REST API.

**Comment by megi39** [comment]
to znaczy, że przy trzystu zamówieniach dziennie trzeba będzie od lutego je wszystkie ręcznie oznaczać jako wysłane???

**Comment by MartaNowaczyk** [comment]
@megi39 do czego potrzebne ci to oznaczenie? Ta opcja nie jest brana pod uwagę przy Super Sperzdawcy. To dodanie numeru przesyłki jest tutaj priorytetowe.

**Comment by martacronic** [comment]
@MartaNowaczyk wiele osób zgłasza tą niespójność. Jeśli wejdziemy od strony frondendu w Zamówienia, to jest możliwość sortowania. Po wybraniu opcji "do wysłania" pokazują się wszystkie przesyłki niezależnie czy numer wysyłki został dodany czy nie. Jeśli chcę rzeczywiście sprawdzić, czy wszystko zostało wysłane od strony frondendu, to nie ma takiej możliwości jeśli numery trackingu są dodawane przez API. Dla nas dodanie numeru trackingu jest równoznaczne z wysłaniem paczki.

Jest to niespójne i ogranicza możliwości wyłapywania zamówień, które nie zostały z jakiś powodów wysłane lub zamówień do których nie został dodany numer paczki. To, że w 2019 r. będziecie wymagać dodawania numeru przesyłek sprawia, że chcemy jak najlepiej to wykonać.

Nie zawsze API jest używane do stworzenia aplikacji, która w całości zastępuje frondend Allegro. Ja korzystam z kilku metod, które usprawniają pracę.

**Comment by MartaNowaczyk** [comment]
@martacronic rozumiem, zgłosiłam taką sugestię do odpowiedniego zespołu.

**Comment by megi39** [comment]
> @megi39 do czego potrzebne ci to oznaczenie? Ta opcja nie jest brana pod uwagę przy Super Sprzedawcy. To dodanie numeru przesyłki jest tutaj priorytetowe.

Może brana nie jest, ale dodatkowe punkty są naliczane a o tytuł SS nie "walczą" sprzedawcy z 20zam dziennie, więc to takie robienie nam pod górkę.

**Comment by jakubmaguza** [comment]
Czy są jakieś plany nad wprowadzeniem możliwości oznaczenia jako 'Wysłane'?
Potwierdzam to co napisali koledzy wyżej -> taka opcja bardzo się przyda żeby móc widzieć na froncie czy wszystkie zamówienia są zrealizowane. Ewentualnie zastąpienie opcji 'wysłane' opcją 'dodany numer przesyłki'. Nie rozumiem sensu rozdzielenia tych dwóch rzeczy...

**Comment by MartaNowaczyk** [comment]
@jakubmaguza rozumiem, pracujemy nad zasobem, który pozwoli określić między innymi status zamówienia. Jak tylko będzie gotowy damy znać w oddzielnym komunikacie.

**Comment by jakubmaguza** [comment]
Nie byłoby łatwiej i szybciej dodać jednego filtra na froncie?

**Comment by MartaNowaczyk** [comment]
@jakubmaguza przepraszam, pomyślałam, że chodzi ci o dodanie opcji "wysłane" do REST API. W takim razie chodzi ci o filtrowanie zamówień w panelu allegro?

**Comment by jakubmaguza** [comment]
Chodzi mi o jedną z tych opcji :) Jeśli będzie filtrowanie w panelu, to nie będzie potrzeby oznaczać jako wysłane. W ten sposób łatwo będzie można zidentyfikować zamówienia które się przeoczyło przy wysyłce :)

**Comment by jakubmaguza** [comment]
Dziękuję :)
