### ISSUE TITLE
Missing category through request 

### ISSUE THREAD

**Issue by NicksssN** [allegro/allegro-api#9770]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

We've got 13s categories of 14s from the main category [Kuchnia](https://allegro.pl/kategoria/meble-kuchnia-1510)

Don't get the category [Krzesła](https://allegro.pl/kategoria/kuchnia-krzesla-112728)

Request : "/sale/categories?parent.id=1510"

[answer.txt](https://github.com/user-attachments/files/16796403/answer.txt)

Image of the list with categories that we've got:
As you can see there is missed Krzesła
![image](https://github.com/user-attachments/assets/aab44217-2d35-41f3-9faa-3660999472d7)

**Comment by MaciejFrackowiak** [comment]
Category 112728 (Krzesła) is a navigation category available only for buyers using Allegro listing. You will not find this category in the assortment tree (GET /sale/categories resource).

**Comment by NicksssN** [comment]
How can we list offers in this category?

**Comment by NicksssN** [comment]
Ok, but we also don't get the category https://allegro.pl/kategoria/salon-krzesla-112737
