### ISSUE TITLE
Allegro Finanse - Aktywacja

### ISSUE THREAD

**Issue by KluseG** [allegro/allegro-api#978]
Witam.

Proszę o aktywację PayU na sandboxie, chciałbym potestować kilka funkcjonalności z WebAPI :)

ID: 44056760

Z góry dziękuję i pozdrawiam.

**Comment by MartaNowaczyk** [comment]
Witam, niestety na sandboxie nie aktywujemy PayU :(

**Comment by KluseG** [comment]
@MartaNowaczyk Jak w takim razie mogę przetestować metody takie jak doGetMyPayouts?

**Comment by PawelTaberski** [comment]
Niestety nie ma takiej możliwości, nie możesz sobie przelać środków fikcyjnych na jakieś fikcyjne konto.
