### ISSUE TITLE
Problem z pobraniem etykiety Allegro One Box, DPD

### ISSUE THREAD

**Issue by Wojtu204** [allegro/allegro-api#9781]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Występuje problem z pobieraniem etykiety logistycznej.
Trace-id: 606d5de63d36bb78

Otrzymujemy komunikat:
{
	"errors": [
		{
			"code": "CARRIER_API_CLIENT_UNAVAILABLE",
			"message": "Carrier Api Client is temporary unavailable - try again later or report problem",
			"details": "Carrier Api Client is temporary unavailable - try again later or report problem",
			"path": null,
			"userMessage": "API przewoźnika jest tymczasowo niedostępne. Ponów próbę później.",
			"metadata": {}
		}
	]
}

W headerze mamy status 408

![image](https://github.com/user-attachments/assets/e71699c5-77e5-460e-b139-529fb74f99fb)

Z tego, co zauważyłem problem dotyczy przesyłki założonej na metodzie:
0b257488-c85d-4507-b967-9b45ffbfa2e8
Etykieta pobierana w ZPL.

W przypadku metody c3066682-97a3-42fe-9eb5-3beeccab840c problem nie występuje.

**Comment by MartaNowaczyk** [comment]
Problem był po naszej stronie, ale wdrożyliśmy poprawkę. Przepraszamy za niedogodności. Spróbuj jeszcze raz w takim razie.

**Comment by Wojtu204** [comment]
Etykieta pobiera się poprawnie, dziękuję za rozwiązanie problemu.
