### ISSUE TITLE
Status utworzenia paczki

### ISSUE THREAD

**Issue by many-to-one** [allegro/allegro-api#9785]
Witam, przy wywołaniu zasobu:
https://api.allegro.pl.allegrosandbox.pl/shipment-management/shipments/create-commands/{commandId}
zwraca błąd:

{
    "errors": [
        {
            "code": "NOT_FOUND",
            "message": "The specified resource was not found",
            "details": null,
            "path": "/shipment-management/shipments/create-commands/6933c130-6624-11ef-97df-7166871624c9",
            "userMessage": "Podany zas\u00f3b nie zosta\u0142 odnaleziony",
            "metadata": {}
        }
    ]
}

'trace-id': '5ca784c2cb4914f8'

**Comment by many-to-one** [comment]
Prblem został rozwiązany

**Comment by df950** [comment]
Mam chyba podobny problem. Jak ty go rozwiązałeś?

**Comment by MaciejFrackowiak** [comment]
@df950 Proszę opisz swój problem. Podaj także przykładowe trace-id wywołania.

**Comment by df950** [comment]
Po wywołaniu "GET /shipment-management/shipments/create-commands/8129571e-5015-4349-85da-8f279ab1f4fe"
Otrzymuję odpowiedź:
"HTTP/1.1 404 Not Found
trace-id: 8cdd05c1ff885400
date: Wed, 26 Mar 2025 09:06:36 GMT
content-type: application/vnd.allegro.public.v1+json
content-length: 258
x-frame-options: DENY
strict-transport-security: max-age=15552000
x-content-type-options: nosniff

{"errors":[{"code":"NOT_FOUND","message":"The specified resource was not found","details":null,"path":"/shipment-management/shipments/create-commands/8129571e-5015-4349-85da-8f279ab1f4fe","userMessage":"Podany zasób nie został odnaleziony","metadata":{}}]}"

Wcześniej tworząc przesyłkę otrzymałem
"POST shipment-management/shipments/create-commands"
:"
{
    "commandId": "8129571e-5015-4349-85da-8f279ab1f4fe",
    "input": {
        "deliveryMethodId": "1b28f4fb-df3e-4324-a6ef-707a3f1be43b",
        "credentialsId": null,
..."

Zdarza się taki problem od czasu. Generuje ponownie przesyłkę bez zmiany jakichkolwiek  parametrów,  i wtedy jest wszystko jest OK. Oczywiście otrzymuję nowe "commandId".

**Comment by MaciejFrackowiak** [comment]
@df950 Request z POST wysłałeś z konta xxxx0193, a odpytywałeś o GET będąc zautoryzowanym na koncie xxxx5552. Sama transakcja pochodzi z konta xxxx5552, zatem POST został nieprawidłowo wysłany.

**Comment by df950** [comment]
Dziękuję za pomoc.
