### ISSUE TITLE
Długość podanego tekstu przekracza 20 znaków

### ISSUE THREAD

**Issue by many-to-one** [allegro/allegro-api#9786]
Wywołanie zasobu:
"https://api.allegro.pl.allegrosandbox.pl/shipment-management/shipments/create-commands/{commandId}"
zwraca błąd:

{'commandId': '76151633-8580-4891-9010-7a1ce7d1f931', 'status': 'ERROR', 'errors': [{'code': 'SHIPMENT_VALIDATION_ERROR', 'message': 'Entered text exceeds 20 characters', 'details': 'Shipment request has validation errors', 'path': 'packages.textOnLabel', 'userMessage': 'Długość podanego tekstu przekracza 20 znaków'}], 'shipmentId': None}

'trace-id': '5e909ccb6f12659b'

Problem występuje kiedy chcę zrealizować zamówienie składające się z trzech produktów. Przy realizowaniu zamówienia z jednym lub dwoma produktami wszystko działa poprawnie.

**Comment by MartaNowaczyk** [comment]
Długość pola description nie powinna przekraczać 20 znaków, a pewnie jak masz więcej zamówień to dodajesz coś do tego pola i w końcu jest za długie. W tym konkretnym requeście masz "description":"008-979 x 1, 1256 x 1, SG-01 x 1".

**Comment by many-to-one** [comment]
Dziękuję, teraz wiem o co chodzi
