### ISSUE TITLE
Cannot make two factor authentication

### ISSUE THREAD

**Issue by hoszke** [allegro/allegro-api#9798]
I am using the Allegro Developer Sandbox (https://apps.developer.allegro.pl.allegrosandbox.pl/). I cannot create a new application because I need to enable two-factor authentication. However, the SMS code never arrives (I have tried multiple phone numbers), and now I receive a 'Too many requests' error when attempting to get a new two-factor authentication code.

What is the solution?
![Screenshot 2024-09-02 at 11 41 12](https://github.com/user-attachments/assets/be438ac5-91be-470c-9d6a-361c647687ba)

![Screenshot 2024-09-02 at 11 38 33](https://github.com/user-attachments/assets/2e6bca2c-8bfc-4ab6-ab2d-7e8e6ac829b7)

![Screenshot 2024-09-02 at 11 42 28](https://github.com/user-attachments/assets/b858b45e-ecb6-4ba5-81e0-9616be9da4df)

**Comment by PrzemyslawLukanowski** [comment]
Hello, it is not necessary to enable 2FA on the Sandbox env, as we wrote in [our tutorial](https://developer.allegro.pl/tutorials/basic-information-VL6YelvVKTn#test-environment):

<img width="427" alt="Zrzut ekranu 2024-09-2 o 11 47 40" src="https://github.com/user-attachments/assets/f728a2d1-5839-4edf-86d0-8f4389524b66">

I assume your account is not activated. Could you please send me your login?

**Comment by hoszke** [comment]
> I assume your account is not activated. Could you please send me your login?

hoszke_dev

**Comment by PrzemyslawLukanowski** [comment]
Please set up payouts via [this tab](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat), thanks to that I will be able to activate your account. You can provide a fake bank account number.

**Comment by PrzemyslawLukanowski** [comment]
And done on my side. Your account is activated and now you should be able to register a new account.
