### ISSUE TITLE
Brak możliwości aktywowania konta

### ISSUE THREAD

**Issue by mapsi-fixi** [allegro/allegro-api#98]
moje konto na nowym sandboxie nie może wystawiać aukcji z powodu braku weryfikacji. Przeszedłem przez   testową płatność aktytwacyjną, natomiast status jest nadal 'trwa weryfikowanie', 2 dzień. Robiłem zakupy przez payU - też nic nie dało. Czy można to jakoś ręcznie popchnąć? Nick : mapsiu #

**Comment by KrzysztofLukanowski** [comment]
Adres, który wprowadziłeś do ustawień konta powinny mieć swoje odzwierciedlenie w rzeczywistości. Wówczas pełna aktywacja powiedzie się. Wskazane konto jest już aktywne.

**Comment by mapsi-fixi** [comment]
Konto nadal nie może wystawiać przedmiotów na sprzedaż 😢

**Comment by KrzysztofLukanowski** [comment]
Sprawdź proszę czy już jest okej.

**Comment by mapsi-fixi** [comment]
Już dziala, dzięki wielkie za szybką pomoc 😊
