### ISSUE TITLE
Sandbox - too many request - while putting product to cart

### ISSUE THREAD

**Issue by hoszke** [allegro/allegro-api#9801]
Cannot put product to cart.

Sometimes simple cannot put, sometimes error shown.

While debugging "Too Many Request" shown. I have tried from more IP addresses.

account: hoszke_dev
product: https://allegro.pl.allegrosandbox.pl/oferta/iphone-xi-binngie-se-2027-7775397428

I just want to make an order.

![Screenshot 2024-09-02 at 14 58 12](https://github.com/user-attachments/assets/b29fe911-6f5e-4e0b-8ff6-a9027758882e)

**Comment by PrzemyslawLukanowski** [comment]
Does this problem still occur? I wasn't able to recreate it, itmes are properly added to the cart.
