### ISSUE TITLE
Brak wartości opcji w filtrze MULTI

### ISSUE THREAD

**Issue by walik92** [allegro/allegro-api#981]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Brak wartości dla niektórych opcji w filtrze MULTI 'oferta ma' - przykład dla kategorii 8993
 {
            "id": "option",
            "type": "MULTI",
            "name": "oferta ma",
            "values": [
                {
                    "value": "FREE_SHIPPING",
                    "name": "darmowa dostawa",
                    "selected": false
                },
                {
                    "value": "FREE_RETURN",
                    "name": "darmowy zwrot InPost",
                    "selected": false
                },
                {
                    "name": "wniesienie",
                    "selected": false
                },
                {
                    "name": "montaż",
                    "selected": false
                },
                {
                    "name": "ustawienie",
                    "selected": false
                },
                {
                    "name": "przygotowanie do pracy",
                    "selected": false
                },
                {
                    "name": "zapakowanie na prezent",
                    "selected": false
                },
                {
                    "value": "VAT_INVOICE",
                    "name": "faktura VAT",
                    "selected": false
                },
                {
                    "value": "COINS",
                    "name": "Monety Allegro",
                    "selected": false
                },
                {
                    "value": "BRAND_ZONE",
                    "name": "Strefa Marek",
                    "selected": false
                },
                {
                    "value": "SUPERSELLER",
                    "name": "Super Sprzedawca",
                    "selected": false
                },
                {
                    "value": "SMART",
                    "name": "Allegro Smart!",
                    "selected": false
                }
            ]
        },

**Comment by walik92** [comment]
Opcje wniesienie, montaż, ustawienie,  przygotowanie do pracy oraz zapakowanie na prezent nie posiadają zmiennej value

**Comment by PawelTaberski** [comment]
@walik92 Ah teraz rozumiem aby skorzystać z tego filtru podaj np. `/offers/listing?category.id=67430&opcje-dostawy=wniesienie`

**Comment by walik92** [comment]
@PawelTaberski ok dzięki. A czy można to jakoś ustandaryzować ? Podobny problem jest z filtrem campaign z opcją wyprzedaż.

**Comment by PawelTaberski** [comment]
@walik92 Zgłosiłem tą sprawę do odpowiedniego zespołu z prośbą o ujednolicenie, proszę o cierpliwość.

**Comment by PawelTaberski** [comment]
@walik92 Rozwiązaliśmy problem, wdrożyliśmy pole "VALUE", możliwe jest już filtrowanie, np:
/offers/listing?phrase=od+20&category.id=8993&option=CARRY_IN
