### ISSUE TITLE
sale/offer-price-change-commands/{command}/tasks - COMMAND_NOT_FOUND

### ISSUE THREAD

**Issue by bmusialekcepd** [allegro/allegro-api#9814]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

witam,

09.03 za pomoca sale/offer-price-change-commands wysylam commanda dla aktualizacji ceny = 2.00.
Generuje UUID = e98c0df5-7585-44fe-9889-feaaab9e7452

za pomoca [sale/offer-price-change-commands/e98c0df5-7585-44fe-9889-feaaab9e7452/tasks sprawdzam czy command jejst przetworzony. Fukncja zwraca COMMAND_NOT_FOUND
traceId: e300576b43efec0d

**Comment by PrzemyslawLukanowski** [comment]
Witam, Nie widzę w naszych logach requestu PUT /sale/offer-price-change-commands/e98c0df5-7585-44fe-9889-feaaab9e7452, jak również dużej części pozostałych operacji, dla których zwracamy 404 Not Found. Wygląda na to, że te requesty nie zostały do nas prawidłowo wysłane. Jest duża dysproporcja między zadaniami, które zlecasz (1,052 w ciągu ostatnich 7 dni), a liczbą odpytań o status wykonania zadania (9,166). Aż dla 8,126 zwróciliśmy 404, podczas gdy tylko dla 1,047 odpowiedziieliśmy prawidłowym statusem..

Upewnij się, że te zadania na pewno istnieją, czy został dla nich zwrócony status 201 - jeśli tak, przekaż nam trace-id.
