### ISSUE TITLE
warunki ochrony marek - srodowisko sandbox

### ISSUE THREAD

**Issue by bmusialekcepd** [allegro/allegro-api#9823]
witam, na srodowisku sandbox probuje aktywowac oferte 7775356489. Dostaje blad: [{"code":"ConstraintViolationException.OfferValidation","message":"Due to the lack of confirmation of the Brand Protection Conditions, you cannot list offers with the protected brands\u2019 products from the protected brands list, included in appendix no 1, section 2 par. 2 of the Allegro Terms&Conditions. If you want to list offers with those brands, accept Brand Protection Conditions. If you sell with a Regular Account, use Allegro Lokalnie.","details":null,"path":"name","userMessage":"Due to the lack of confirmation of the Brand Protection Conditions, you cannot list offers with the protected brands\u2019 products from the protected brands list, included in appendix no 1, section 2 par. 2 of the Allegro Terms&Conditions. If you want to list offers with those brands, accept Brand Protection Conditions. If you sell with a Regular Account, use Allegro Lokalnie."}]

Probuje zaakceptowac nowy regulamin dla dla konta sandbox DNatura nie dziala salescenter

**Comment by AureliuszBrussy** [comment]
Powinieneś móc zaakceptować regulamin na stronie: https://salescenter.allegro.com.allegrosandbox.pl/brands-to-protect. Nie potwierdzam w tym momencie problemu z dostępem do zakładki. Spróbuj proszę jeszcze raz.
