### ISSUE TITLE
Wysyłam z Allegro - zapytanie

### ISSUE THREAD

**Issue by NotIdrizdi** [allegro/allegro-api#9825]
Witam, z poziomu panelu przy nadawaniu przesyłki przez przewoźnika Allegro Kurier Pocztex widzę, że nadanie odbywa się w urzędzie pocztowym, jak to się ma do API tworzenia przesyłek? Czy można wypełnić sekcję pickup na adres na który kurier ma przyjechać po paczkę czy musi to być koniecznie urząd pocztowy?

![image](https://github.com/user-attachments/assets/e3deb5be-ff4c-4441-ba59-95d2a561e6f7)

**Comment by PrzemyslawLukanowski** [comment]
Witam, W API Wysyłam z Allegro również nie można zamawiać podjazdów kuriera Poczty Polskiej, dlatego w takiej sytuacji sekcję `pickup` możesz pozostawić pustą. Pole to nie jest wymagane.

**Comment by NotIdrizdi** [comment]
Okej, jeszcze dodatkowe zapytanie, czemu otrzymuje taki błąd:
[{\"code\":\"DELIVERY_METHOD_NOT_AVAILABLE\",\"details\":\"Delivery Method is not available for this order\",\"message\":\"Cannot create a shipment using the Allegro Standard contract. Delivery method assigned to this order is the merchant controlled one. Change the service and try again.\",\"path\":\"deliveryMethodId\",\"userMessage\":\"Nie można utworzyć przesyłki przy użyciu umowy Allegro Standard. Metoda przypisana do tego zamówienia to umowa własna. Zmień umowę i spróbuj ponownie.\"}] dla commandId: 94f12807-c75d-4a99-9c5e-f43b0cc609bd
gdy próbuje utworzyć przesyłkę? Wybrana metoda dostawy: c3066682-97a3-42fe-9eb5-3beeccab840c (Allegro Kurier DPD)
![image](https://github.com/user-attachments/assets/970e74f3-7a6f-4508-b330-f405a3c4a493)
credentialsId jest null w /shipment-management/delivery-services i wcześniej mogłem bezproblemowo wysyłać paczki przez DPD, bez własnej umowy

**Comment by PrzemyslawLukanowski** [comment]
Tutaj również komunikat jest prawidłowy zgodnie z [ostatnimi zmianami](https://developer.allegro.pl/news/wysylam-z-allegro-od-22-sierpnia-2024-dla-uslug-dostawy-allegro-standard-nie-skorzystasz-juz-z-umowy-wlasnej-4Rr2roy7ziz):

> (...) Ponadto, dla usług dostawy spoza Allegro Standard, dla których sprzedający posiada umowy własne, nie będzie mógł już zmienić przewoźnika realizującego dostawę. Oznacza to, że powinien utworzyć przesyłkę zgodnie z wybranym przez kupującego w zamówieniu przewoźnikiem.
