### ISSUE TITLE
Tworzenie przesyłek WZA

### ISSUE THREAD

**Issue by piotreqm** [allegro/allegro-api#9829]
Zintegrowaliśmy nasz system z Allegro API, by nadawać przesyłki WZA z firmowych magazynowych kolektorów danych.

Napotykamy problem:

{ "commandId": "2337a1eb-36b7-4247-8fd8-162e30c62805", "status": "ERROR", "errors": [ { "code": "NOT_SELLER_ORDER", "details": "Order doesn't belong to seller", "message": "Order doesn't belong to seller", "path": "email", "userMessage": "Nie jesteś właścicielem zamówienia" } ] }

jednak jesteśmy przekonani co do tego, że łączymy się do właściwego konta - tego, na którym zostało złożone zamówienie.

Wskazanie path: email - tu wstawiamy adres e-mail zgodny z adresem e-mail konta Allegro.

Proszę o pomoc - wskazanie, dlaczego to nie działa?

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że komunikat błędu w tym przypadku jest prawidłowy, ponieważ zamówienie powiązane z danym mailem odbiorcy należy do konta xxxx146 (exxxxxlaw), natomiast request zostaje wysłany z konta xxxx220 (Huxxxxxxl12).

**Comment by piotreqm** [comment]
@PrzemyslawLukanowski 
Utworzyliśmy jedną aplikację w Allegro i powiązaliśmy ją ze wszystkimi kontami - czy dlatego request może być wysyłane jako Huxxxxxxl12?

Ponadto, w innym przypadku mam komunikat:
`shipmentCreationStatus: { "commandId": "0df907d2-cfd2-4086-9bab-93c00f9cf05c", "status": "ERROR", "errors": [ { "code": "CREDENTIALS_ID_NOT_PROVIDED", "details": "Seller didnt provide credentials for own delivery Method", "message": "Seller didnt provide credentials for own delivery Method", "path": "credentialsId", "userMessage": "Wybrana metoda dostawy nie obsługuje tego zamówienia" } ] }`
Czy dla Allegro Inpost muszę w zapytaniu podawać creadentialsID, skoro są one wgrane na koncie?

**Comment by PrzemyslawLukanowski** [comment]
> Utworzyliśmy jedną aplikację w Allegro i powiązaliśmy ją ze wszystkimi kontami - czy dlatego request może być wysyłane jako Huxxxxxxl12?

Tak, aplikacja może w takim razie może operować tokenami dla wszystkich użytkowników i w tym przykładzie doszło do "pomieszania" tokenów. 

> Czy dla Allegro Inpost muszę w zapytaniu podawać creadentialsID, skoro są one wgrane na koncie?

Dokładnie tak, musisz przekazać wartość w credentialsID.

**Comment by piotreqm** [comment]
> Tak, aplikacja może w takim razie może operować tokenami dla wszystkich użytkowników i w tym przykładzie doszło do "pomieszania" tokenów.
Faktycznie, przy powiązaniu aplikacji z kontem coś poszło nie tak. 

> Dokładnie tak, musisz przekazać wartość w credentialsID.
ok

Dziękuję za pomoc :)
