### ISSUE TITLE
Problem ze zmianą ilości dostępnych przedmiotów w aukcji

### ISSUE THREAD

**Issue by piotrkomisarski** [allegro/allegro-api#983]
Witam

Wywołując metodę doChangeQuantityItem  dostajemy taki błąd:

Operacja na ofercie nie jest możliwa z uwagi na fakt, że oferta nie została wystawiona przez zalogowanego użytkownika, oczekuje na wystawienie lub jest zakończona. (24) 

Mógłbym komuś wysłać na priva xmla który wysyłamy i odbieramy żeby to zdiagnozował ?

Piotr Komisarski

**Comment by PawelTaberski** [comment]
Z błędu wynika jakbyś próbował błędnym identyfikatorem sesji (należącym do innego usera) edytować ofertę, która jest na koncie innego użytkownika. Jeśli jesteś pewny, że używasz poprawnego identyfikatora sesji należącego do usera, który tą ofertę wystawił, to podeślij nam przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa w formacie XML sprawdzimy w czym jest problem.  W zgłoszeniu zaznacz proszę, że dane potrzebne są do zgłoszenia numer 983 na GitHub-ie.

**Comment by piotrkomisarski** [comment]
Ok. WYsłane

**Comment by kazz3m** [comment]
Witam,

Mam identyczny problem. Mogę wystawiać towary ale nie mogę zmieniać ich parametrów (cena, ilość, zakończenie)

**Comment by PawelTaberski** [comment]
@kazz3m Otrzymałem dane od Ciebie i widzę, że w polu <ns1:itemId> podajesz błędny numer oferty, który zaczyna się od 2 a wyżej podałeś, że chciałbyś edytować zupełnie inną ofertę, której numer poprawnie zaczyna się od 7.

**Comment by kazz3m** [comment]
@PawelTaberski poprawiłem typowanie pola w wsdl'u jest long a interpretowało mi jako int. Niestety dalej mam ten sam komunikat.

**Comment by kazz3m** [comment]
@PawelTaberski Jest ok! Dzięki :)
