### ISSUE TITLE
Zgłoszenie odbioru paczek

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#9842]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ X ] ze środowiskiem produkcyjnym / with the production environment

przy próbie zamówienia przyjazdu kuriera dostaliśmy poniższy błąd  mimo że przesylki istnieja (są już dostarczone a przyjazd był zamawiany przed obiorem paczek)
{
	"commandId": "8e4848ca-7636-4de9-beee-351a987f77e2",
	"status": "ERROR",
	"errors": [
		{
			"code": "SHIPMENT_NOT_FOUND",
			"message": "Requested shipment was not found",
			"details": "Requested shipment was not found",
			"path": "shipmentId",
			"userMessage": "Nie odnaleziono przewozu"
		}
	],
	"pickupId": null,
	"carrierPickupId": null
}
trace-id a6bc96b15af3adb3 POST na /shipment-management/pickups/create-commands
trace-id 5e1f7aa08036e859 GET   na /shipment-management/pickups/create-commands

**Comment by PrzemyslawLukanowski** [comment]
Otrzymujesz ten błąd, ponieważ paczki zostały stworzone przez usera 12xxxx11, natomiast request wykonywany jest przez usera 62xxx66.
