### ISSUE TITLE
Błąd w PAYU Simulator uniemożliwia aktywację konta na sandboksie

### ISSUE THREAD

**Issue by robert-skarzycki** [allegro/allegro-api#985]
Mam ten sam problem jak issue #946 - konto `rskarzycki-ceneo`, na sandboksie.  W koncie mam wpis "Nieaktywne - trwa weryfikacja Twoich danych", a metoda WebAPI `doShowUser` zwraca mi `usernotactivated = 1`. PAYU Simulator zwraca 504 przy requeście `makerqeuest` (po kliknięciu w zielonego ticka).

_Originally posted by @robert-skarzycki in https://github.com/allegro/allegro-api/issues/946#issuecomment-446880288_

**Comment by PawelTaberski** [comment]
Aktywowałem Twoje konto powinno już być wszystko ok.

**Comment by robert-skarzycki** [comment]
Teraz działa, dzięki!
