### ISSUE TITLE
Weryfikacja konta sprzedażowego sandbox

### ISSUE THREAD

**Issue by AdrianPiechota** [allegro/allegro-api#9851]
Proszę o aktywację konta i sprzedaży:
Konto: b91925569s
Email: b91925569+sprzedaz@gmail.com

Nie można dodać załącznika do formularza  "Potwierdź tożsamość"
![obraz](https://github.com/user-attachments/assets/a39302b8-ba8b-449c-9a3e-59d632685876)
![obraz](https://github.com/user-attachments/assets/10111b7d-e6e1-4161-95ce-947af6f26f37)

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto. Problem, o którym wspominasz jest nam znany, zgłosiłem go już do zespołu odpowiedzialnego za rejestrację konta.

**Comment by AdrianPiechota** [comment]
Dziękuję
