### ISSUE TITLE
Aktualizacja stany magazynowego - OFFER_NOT_FOUND

### ISSUE THREAD

**Issue by bmusialekcepd** [allegro/allegro-api#9857]
witam,

za pomocą funkcji sale/offer-quantity-change-commands aktualizuje stan dla oferty 12505083720 na stan = 3.
Podczas sprawdzania raportu commanda dostaje wynik:
[{"code":"OFFER_NOT_FOUND","message":"Offer not found.","details":null,"path":null,"userMessage":"Offer not found."}]

command-id = e5ebd593-149f-4c14-af76-b3ef23338ac8

Oferta istnieje

**Comment by Lukasz-Zurek** [comment]
Potwierdzam, że oferta nr 12505083720 została już zarchiwizowana (zakończona 11.07), stąd komunikat.
