### ISSUE TITLE
WebApi: doNewAuctionExt - "Provided postal code is incorrect"

### ISSUE THREAD

**Issue by jzskyshop** [allegro/allegro-api#986]
Mam problem z WebApi Allegro (http://allegro.pl/webapi). Podczas próby wystawienia nowej aukcji (metoda "doNewAuctionExt") dostaję komunikat błędu "Provided postal code is incorrect" - prosiłbym o wskazówkę co może być nie tak - którego kodu pocztowego może dotyczyć błąd?

**Comment by MartaNowaczyk** [comment]
@jzskyshop podeślij proszę twój request i response w formacie XML do weryfikacji. (jeśli nie chcesz przesyłać ich bezpośrednio tutaj, możesz je przesłać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem, że to do zgłoszenia #986 na GitHubie, a trafi to do mnie)

**Comment by MartaNowaczyk** [comment]
@jzskyshop z moich informacji wynika, że błąd powoduje kod pocztowy w fid 32:
<ns1:fid>32</ns1:fid>
<ns1:fvalueString>S63 5DB</ns1:fvalueString>

**Comment by MartaNowaczyk** [comment]
@jzskyshop Jeśli chodzi o walidację kodu pocztowego, jest to uzależnione od kraju jaki podajesz w fid 9. Jeśli podajesz 1 (Polska), a z tego co widzę w podesłanym requeście taką wartość właśnie podajesz, dochodzi do walidacji formatu kodu pocztowego. Jeśli podany kod pocztowy nie dotyczy PL powinieneś w fid 9 podać odpowiednią wartość dla kraju, którego kod ten dotyczy. Wartości dla fid 9 z listą krajów pobierzesz metodą DoGetCountries.
