### ISSUE TITLE
Error Rithum

### ISSUE THREAD

**Issue by Vellemanski** [allegro/allegro-api#9860]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x ] inny / other

:beetle: **Opis / Description**
Few months ago we have started to list our items on Allegro via Rithum. At the beginning we had around 800 products listed.
In July we had to clean manually our inventory on Allegro portal and we expected that everything get imported through Rithum again. We have now over 1000 products in the feed but only 300 listed due to the major Error issues that cannot be solved at our side. We have contacted Rithum but issues come from Allegro. Here are the 2 most common issues:

![image](https://github.com/user-attachments/assets/aa0a8350-588e-4a62-88b3-1cf77e056ea3)

How to solve this please? 

Thanks for any tips.

**Comment by Lukasz-Zurek** [comment]
Please note that any errors should be explained directly with Rithum. If Rithum sees any unexpected errors from our side - they should inform us about it. 

But we already know what is wrong in your specific case - as far as I know - we are working on it.

**Comment by Vellemanski** [comment]
Ok, thanks for your feedback. Any idea how soon can we expect some kind of soulution? Our sales is very low at the moment due to those listing problems :(

**Comment by Lukasz-Zurek** [comment]
@Vellemanski We do not know, but it is a priority for us.
