### ISSUE TITLE
HttpMessageNotReadableException przy wywołaniu POST /sale/product-proposals

### ISSUE THREAD

**Issue by RestITPL** [allegro/allegro-api#9863]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Czasami występuje problem przy proponowaniu produktów w katalogu. Niestety nie mogę zidentyfikować przyczyny problemu. Proszę o pomoc.
Przykładowe dane:
Dane wysyłane w requście:
-------------------
language: pl-PL
category:
  id: '89000'
description:
  sections:
  - items:
    - type: TEXT
      content: "<h1>TirTir Ceramic Milk Ampoule Nawilżające serum do twarzy 10ml</h1>"
  - items:
    - type: IMAGE
      url: https://a.allegroimg.com/original/112d70/8866cc6c4d4e9df646403c4f7589
    - type: TEXT
      content: |-
        <p><b>TirTir Ceramic Milk Ampoule Nawilżające serum do twarzy</b></p> <p>TIRTIR – Ceramic Milk Ampoule – intensywnie nawilżająca ampułka do twarzy o mlecznej konsystencji.</p> <p>Produkt wzmacnia barierę hydrolipidową skóry i nadaje jej zdrowy blask.</p> <p>Zawiera kompleks ceramidów, który odbudowuje barierę ochronną i wspomaga regenerację skóry.</p> <p><b>Ekstrakt z ryżu </b>odżywia skórę, działa przeciwstarzeniowo, a adenozyna poprawia jej jędrność.</p> <p><b>Niacynamid</b> delikatnie rozjaśnia, a fermenty wzmacniają naturalny mikrobiom skóry.</p> <p>Ampułka została przebadana dermatologicznie, jest wegańska i polecana do pielęgnacji skóry suchej, matowej oraz pozbawionej elastyczności.</p> <p><b>Składniki aktywne:</b></p> <ul>
        <li>
        <b>Kompleks ceramidów </b>– regeneruje i wzmacnia barierę hydrolipidową.</li>
        <li>
        <b>Ekstrakt z ryżu </b>– odżywia, wygładza, rozjaśnia, nawilża, opóźnia procesy starzenia.</li>
        <li>
        <b>Niacynamid </b>– wzmacnia barierę hydrolipidową, działa przeciwzapalnie i rozjaśniająco.</li>
        <li>
        <b>Adenozyna</b> – poprawia jędrność, wygładza i działa przeciwzmarszczkowo.</li>
        <li>
        <b>Fermenty </b>– wzmacniają mikrobiom skóry, podnoszą jej odporność na czynniki zewnętrzne.</li>
        </ul>
  - items:
    - type: TEXT
      content: "<p><b>Działanie:</b> Nawilżenie, wzmocnienie bariery hydrolipidowej,
        rozświetlenie, poprawa elastyczności, delikatne rozjaśnienie.</p> <p>Rekomendowany
        do pielęgnacji: skóry suchej, z osłabioną barierą hydrolipidową, pozbawionej
        blasku.</p>"
    - type: IMAGE
      url: https://a.allegroimg.com/original/11e2f7/751e174b41018608bead2d05208a
parameters:
- id: '11323'
  valuesIds:
  - '11323_1'
  values: []
  rangeValue:
- id: '249829'
  valuesIds:
  - '249829_1765555'
  values: []
  rangeValue:
- id: '249948'
  valuesIds:
  - '249948_1785986'
  values: []
  rangeValue:
- id: '229205'
  valuesIds:
  - '229205_340245'
  values: []
  rangeValue:
images:
- https://a.allegroimg.com/original/112d70/8866cc6c4d4e9df646403c4f7589
- https://a.allegroimg.com/original/11e2f7/751e174b41018608bead2d05208a
name: TirTir Ceramic Milk Ampoule Nawilżające serum do twarzy 10ml
----------- Koniec danych w requescie

----------  ROW POST DATA
{"name":"TirTir Ceramic Milk Ampoule Nawil\u017caj\u0105ce serum do twarzy 10ml","category":{"id":"89000"},"images":["https://a.allegroimg.com/original/112d70/8866cc6c4d4e9df646403c4f7589","https://a.allegroimg.com/original/11e2f7/751e174b41018608bead2d05208a"],"language":"pl-PL","parameters":[{"id":"11323","valuesIds":["11323_1"]},{"id":"249829","valuesIds":["249829_1765555"]},{"id":"249948","valuesIds":["249948_1785986"]},{"id":"229205","valuesIds":["229205_340245"]}],"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003Ch1\u003ETirTir Ceramic Milk Ampoule Nawil\u017caj\u0105ce serum do twarzy 10ml\u003C/h1\u003E"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/112d70/8866cc6c4d4e9df646403c4f7589"},{"type":"TEXT","content":"\u003Cp\u003E\u003Cb\u003ETirTir Ceramic Milk Ampoule Nawil\u017caj\u0105ce serum do twarzy\u003C/b\u003E\u003C/p\u003E \u003Cp\u003ETIRTIR \u2013 Ceramic Milk Ampoule \u2013 intensywnie nawil\u017caj\u0105ca ampu\u0142ka do twarzy o mlecznej konsystencji.\u003C/p\u003E \u003Cp\u003EProdukt wzmacnia barier\u0119 hydrolipidow\u0105 sk\u00f3ry i nadaje jej zdrowy blask.\u003C/p\u003E \u003Cp\u003EZawiera kompleks ceramid\u00f3w, kt\u00f3ry odbudowuje barier\u0119 ochronn\u0105 i wspomaga regeneracj\u0119 sk\u00f3ry.\u003C/p\u003E \u003Cp\u003E\u003Cb\u003EEkstrakt z ry\u017cu \u003C/b\u003Eod\u017cywia sk\u00f3r\u0119, dzia\u0142a przeciwstarzeniowo, a adenozyna poprawia jej j\u0119drno\u015b\u0107.\u003C/p\u003E \u003Cp\u003E\u003Cb\u003ENiacynamid\u003C/b\u003E delikatnie rozja\u015bnia, a fermenty wzmacniaj\u0105 naturalny mikrobiom sk\u00f3ry.\u003C/p\u003E \u003Cp\u003EAmpu\u0142ka zosta\u0142a przebadana dermatologicznie, jest wega\u0144ska i polecana do piel\u0119gnacji sk\u00f3ry suchej, matowej oraz pozbawionej elastyczno\u015bci.\u003C/p\u003E \u003Cp\u003E\u003Cb\u003ESk\u0142adniki aktywne:\u003C/b\u003E\u003C/p\u003E \u003Cul\u003E\n\u003Cli\u003E\n\u003Cb\u003EKompleks ceramid\u00f3w \u003C/b\u003E\u2013 regeneruje i wzmacnia barier\u0119 hydrolipidow\u0105.\u003C/li\u003E\n\u003Cli\u003E\n\u003Cb\u003EEkstrakt z ry\u017cu \u003C/b\u003E\u2013 od\u017cywia, wyg\u0142adza, rozja\u015bnia, nawil\u017ca, op\u00f3\u017ania procesy starzenia.\u003C/li\u003E\n\u003Cli\u003E\n\u003Cb\u003ENiacynamid \u003C/b\u003E\u2013 wzmacnia barier\u0119 hydrolipidow\u0105, dzia\u0142a przeciwzapalnie i rozja\u015bniaj\u0105co.\u003C/li\u003E\n\u003Cli\u003E\n\u003Cb\u003EAdenozyna\u003C/b\u003E \u2013 poprawia j\u0119drno\u015b\u0107, wyg\u0142adza i dzia\u0142a przeciwzmarszczkowo.\u003C/li\u003E\n\u003Cli\u003E\n\u003Cb\u003EFermenty \u003C/b\u003E\u2013 wzmacniaj\u0105 mikrobiom sk\u00f3ry, podnosz\u0105 jej odporno\u015b\u0107 na czynniki zewn\u0119trzne.\u003C/li\u003E\n\u003C/ul\u003E"}]},{"items":[{"type":"TEXT","content":"\u003Cp\u003E\u003Cb\u003EDzia\u0142anie:\u003C/b\u003E Nawil\u017cenie, wzmocnienie bariery hydrolipidowej, roz\u015bwietlenie, poprawa elastyczno\u015bci, delikatne rozja\u015bnienie.\u003C/p\u003E \u003Cp\u003ERekomendowany do piel\u0119gnacji: sk\u00f3ry suchej, z os\u0142abion\u0105 barier\u0105 hydrolipidow\u0105, pozbawionej blasku.\u003C/p\u003E"},{"type":"IMAGE","url":"https://a.allegroimg.com/original/11e2f7/751e174b41018608bead2d05208a"}]}]}}
--- END OF ROW POST DATA

--------------------
----- Zwrot z api:
------------------

{"errors":[{"code":"HttpMessageNotReadableException","message":"An error has occurred","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji.","metadata":{}}]}

**Comment by PrzemyslawLukanowski** [comment]
Jak widzisz, ten request został źle sformatowany, osadź proszę cały JSON w znacznikach `` (ikona code u góry na pasku) oraz podaj trace-id wywołania.

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam, teraz zauważyłem, że JSON jest na dole zgłoszenia. Weryfikuję ten problem.

**Comment by PrzemyslawLukanowski** [comment]
Zwróć uwagę na sekcję `images`, powinna to być tablica z obiektami:

<img width="514" alt="Zrzut ekranu 2024-09-12 o 11 16 41" src="https://github.com/user-attachments/assets/ee556c28-d966-46f3-98d3-d6b0cf890667">

W Twoim przypadku wysyłasz:

```
    "images": [
        "https://a.allegroimg.com/original/112d70/8866cc6c4d4e9df646403c4f7589",
        "https://a.allegroimg.com/original/11e2f7/751e174b41018608bead2d05208a"
    ],
```

**Comment by RestITPL** [comment]
Dziękuję, pomogło.
Stanąłem jednak na konieczności wysłania marki, której nie ma na liście marek w tej kategorii. Muszę wybrać "inna marka". Nie wiem jednak jak przekazać samą wartość nazwy marki.

**Comment by RestITPL** [comment]
To pomogło. Dziekuję. 
Mam jednak inny kłopot. Proponuję produkt. Dostaję zwrotkę i id tego proponowanego produktu. Jednak potem nie mogę gu użyć przy wysyłaniu oferty. Co ciekawe znowu mogę proponować ten sam produkt, dostaję inne id.
Proszę zerknąć na takie id zaproponowanych produktów (są to zaproponowane produkty z tymi samymi danymi):
46c7a502-82b4-4b87-8bf3-30e6304cc03a
1629c22f-b5d6-44f8-9220-802e3f06215f

**Comment by PrzemyslawLukanowski** [comment]
Te produkty zostały usunięte po utworzeniu, ponieważ zadziałał nasz wewnętrzny mechanizm sprawdzania poprawności numeru GTIN. Nie pobierzesz ich także za pomocą GET /sale/products/{productID}. Dlatego też mogłeś utworzyć drugi, z podobnymi danymi. Weryfikuję, na ile zasadna była to operacja - czy GTIN rzeczywiście był nieprawidłowy.

**Comment by PrzemyslawLukanowski** [comment]
Tak, usunięcie GTIN było zasadne, wskazany numer GTIN 90443077 nie istnieje w bazie GS1.
