### ISSUE TITLE
Zmiana permissionów w aplikacji, a autoryzacja uzytkowników

### ISSUE THREAD

**Issue by matcapi** [allegro/allegro-api#9874]
Dzień dobry,

Potrzebuję dodać w ustawieniach aplikacji https://apps.developer.allegro.pl/ permissiony:
- `allegro:api:shipments:read`
- `allegro:api:shipments:write`

Podczas zapisywania zmian pojawia się komunikat 
![image](https://github.com/user-attachments/assets/65c80dc0-3dc3-45af-879c-03dd2f03bfa8)

Czy po zatwierdzeniu zmian aplikacji, autoryzacja uzytkowników będzie działać poprawnie dla endpointów, które wymagają permissionów, które już były przed zmianą?

**Comment by Lukasz-Zurek** [comment]
> Czy po zatwierdzeniu zmian aplikacji, autoryzacja uzytkowników będzie działać poprawnie dla endpointów, które wymagają permissionów, które już były przed zmianą?

Tak, jednak aby wspomniane scope'y funkcjonowały prawidłowo, konieczna będzie ponowna autoryzacja/potwierdzenie uprawnień przez użytkowników.

**Comment by matcapi** [comment]
Dziękuję za odpowiedź.
