### ISSUE TITLE
16324550001 - aktywacja zakończonej oferty

### ISSUE THREAD

**Issue by bmusialekcepd** [allegro/allegro-api#9875]
witam,

czy moge prosic o informacje co jest powodem wznawiania tej oferty na allegro? Z naszego systemu nie wyszła prośba o aktywowanie oferty ale wzownila sie wczoraj o 18.

**Comment by Lukasz-Zurek** [comment]
Z tego co widzę oferta została wznowiona wczoraj, 2024-09-12 20:01:39.325 - za pośrednictwem aplikacji zewnętrznej zintegrowanej z naszym API.
