### ISSUE TITLE
Dostarczanie wiadomości do klientów

### ISSUE THREAD

**Issue by NotIdrizdi** [allegro/allegro-api#9877]
Witam, wysyłam faktury na zakodowane maile klientów, które podajecie w zamówieniu - powinny one zostać dodane do centrum wiadomości i wysłane bezpośrednio do klienta natomiast od 3 dni przestały zostać wysyłane wiadomości.

Sprawdziłem po swojej stronie, wysłałem maila na swój prywatny adres e-mail i wiadomość doszła. Czy możecie sprawdzić czemu wiadomości nie są dodawane do centrum wiadomości?

E-maile były wysyłane z mail-a: noreply@primely.pl

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, że nie wysyłasz wiadomości w ramach zasobów [API dla Centrum wiadomości?](https://developer.allegro.pl/tutorials/jak-zarzadzac-centrum-wiadomosci-XxWm2K890Fk#nowa-wiadomosc) W takim przypadku zgłoś proszę problem przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?srsltid=AfmBOop3BNFyxI9IVkrSLxueFNh-j85rEbYRNZqUJ23N2Lr1yzsXXirO).

**Comment by NotIdrizdi** [comment]
Tak - wysyłam bezpośrednio na e-mail klienta, wysłałem zgłoszenie.
