### ISSUE TITLE
Problem z sutoryzacja konta SANDBOX  

### ISSUE THREAD

**Issue by Magdalenanieckula1** [allegro/allegro-api#988]
Dzień dobry,
Bardzo proszę o aktywację konta: white_pr@interia.pl
Bedę wdzieczna za sprawną interwencje.
Pozdrawiam,
MN

**Comment by AssAssIn1909** [comment]
Również prosze o aktywacje konta o loginie itp_pli

**Comment by SzymonG4** [comment]
Także poproszę o aktywację konta neokram1

**Comment by SzymonG4** [comment]
A gdzie dokładnie mam Wam wysłać pliki?

**Comment by tanieobuwie** [comment]
Bardzo Państwa proszę o aktywację konta tanieobuwie_hurt :)

**Comment by PawelTaberski** [comment]
@SzymonG4 W zakładce Moje Konto --> Ustawienia konta --> Twoje dane. Tam dodaj jakieś dwa dowolne pliki i wyślij do weryfikacji.

**Comment by PawelTaberski** [comment]
@tanieobuwie jesteś pewny, że do prawidłowy login, bo nie widzę takiego konta.

**Comment by tanieobuwie** [comment]
chodzi o login konta allegro? 
tanieobuwie_hurt

**Comment by tanieobuwie** [comment]
Staram się podłączyć wtyczkę Woocommerce-Allegro, gdy wpisuję WebAPI pokazuje brak połączenia, mimo, że RESTAPI jest ok. Nie wiem co dalej robić.

**Comment by PawelTaberski** [comment]
Tak login konta, ale nie na https://allegro.pl/ tylko na https://allegro.pl.allegrosandbox.pl/
Czyli na środowisku testowym. Jeśli chcesz założyć konto na sandboxie wcześniej zobacz [tutaj](https://developer.allegro.pl/about/#Sandbox).

**Comment by pogotowiefiskalne** [comment]
Witam,

czy mogę prosić o aktywację konta: sello_test123

**Comment by PawelTaberski** [comment]
@pogotowiefiskalne Aktywowałem Twoje konto, wszystko powinno już działać.
