### ISSUE TITLE
Warunki Ochrony Marek - Sandbox

### ISSUE THREAD

**Issue by KrzychuWalek** [allegro/allegro-api#9886]
Problem z akceptacją  Warunki Ochrony Marek na sandbox i w efekcie brak możliwości wysyłki produkty przez REST API

https://static.investmag.pl/kw/17264817890916167047.jpg

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem ten problem do zespołu odpowiedzialnego za ten widok, wrócę z informacją.

**Comment by PrzemyslawLukanowski** [comment]
Wdrożyliśmy poprawkę, problem nie powinien już występować.

**Comment by KrzychuWalek** [comment]
Dziękuję
:)
