### ISSUE TITLE
/sale/offer-quantity-change-commands/

### ISSUE THREAD

**Issue by pablokol** [allegro/allegro-api#989]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Nie mogę wykonać aktualizacji ilości dostępnych dla aukcji 7116416318 przy użyciu zasobu /sale/offer-quantity-change-commands/
Aukcja ma zakończoną sprzedaż i nie mogę jej wznowić przez RESAPI zanim nie zwiększę ilości dostępnej.

trace id=91dc0c50-3a5d-4175-bffd-fde22c1544ee

**Comment by MartaNowaczyk** [comment]
Z moich informacji wynika, że ofertę udało się ponownie wystawić. Daj znać czy wszystko ok.

**Comment by pablokol** [comment]
Aukcje wznawiamy ręcznie. Bardziej mnie ciekawi dlaczego nie działa  /sale/offer-quantity-change-commands/ na niektórych aukcjach

**Comment by MartaNowaczyk** [comment]
@pablokol jeśli napotkasz kolejny taki przpdek, nie ruszaj go proszę do czasu zakończenia weryfikacji. W innym wypadku trudno będzie nam coś ustalić.

**Comment by pablokol** [comment]
Przesyłam dane kolejnego przypadku: id aukcji:6361565411, trace id "d7b3c71f-67f9-47f9-9173-33d45eed8574". Komunikat błędu:"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE"

**Comment by pablokol** [comment]
Nie mogę ręcznie zmienić kategorii dla oferty, która miała sprzedaż. Co zrobić w takiej sytuacji?

**Comment by MartaNowaczyk** [comment]
@pablokol w takiej sytuacji nie ma możliwości edytowania oferty i wystawienia jej ponownie z tym samym numerem. Musisz wystawić nową czyli np. pobrać sobie ją metodą [GET na zasobie /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#!/offer-management/getOfferUsingGET), a później z danych, które otrzymasz zrobić draft metodą [POST na zasób /sale/offers](https://developer.allegro.pl/documentation/#!/offer-management/createOfferUsingPOST), gdzie możesz wprowadzić modyfikacje, a następnie opublikować. Więcej znajdziesz[ tutaj](https://developer.allegro.pl/sale/#similar-offer).

**Comment by MartaNowaczyk** [comment]
@pablokol podany trace-id nie jest prawidłowy - znajdziesz go w nagłówku w odpowiedzi. 
Co do liczby przedmiotów w tej ofercie  to teraz widać 6 sztuk - czyli tak jak zmieniałeś.  W takim przypadku problem z nieodpowiednią liczbą przedmiotów nie powienien występować. Do pełnej weryfikacji potrzebuję pełne curle z response i request lub poprawny trace-id.
