### ISSUE TITLE
"Oferta nieznaleziona. Została usunięta, zarchiwizowana lub nigdy nie istniała." podczas wystawiania aukcji

### ISSUE THREAD

**Issue by jezewskiBNetrox** [allegro/allegro-api#9890]
Dzień dobry,

szybkie pytanie, ponieważ borykam się z tym od jakiegoś czasu. Dla (wydaje się) losowych zadań wystawienia produktów pojawia się błąd: "Oferta nieznaleziona. Została usunięta, zarchiwizowana lub nigdy nie istniała.".

Przykłady Trace-Id: 
7de12b2d3d17e4e20
941bf05d2b4c36690

Nie udało mi się tego odtworzyć na tym samym koncie i danych produktu więc niestety nie wiem, skąd bierze się ten problem. Ostatnie wątki tutaj o tym błędzie są z 2022 roku.

Nie wygląda też na to, że te aukcje widnieją gdzieś aktywne, sprawdzane bądź jako szkice. Tak jakby znikały. Czy ten problem jest po mojej stronie? Proszę o sprawdzenie tych trace-id.

Pozdrawiam.

**Comment by MartaNowaczyk** [comment]
Dzień dobry, niestety nie mogę już znaleźć w logach podanych trace-id, więc nie mogę tego sprawdzić. Wygląda na to, że nie są to aktualne przykłady. Gdyby pojawił się nowy proszę o podanie.

**Comment by MartaNowaczyk** [comment]
Dziwna sytuacja, bo tych trace-id też nie mam w logach, ani na produkcji, ani na środowisku testowym. Jakiego środowiska to dotyczy? W takim wypadku proszę o podesłanie danych w formacie json - request i response. Jeśli nie chcesz tutaj możesz przesłać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem, że dotyczy wątku 9890 na GitHubie i prosisz by przekazali to do wsparcia API.

**Comment by jezewskiBNetrox** [comment]
@MartaNowaczyk Udało mi się wygenerować nowy błąd, przesłałem go przez formularz kontaktowy: treść zapytania oraz odpowiedzi wraz z trace-id.

Dotyczy to środowiska produkcyjnego.

**Comment by MartaNowaczyk** [comment]
Dziękuję, otrzymaliśmy dane. Dzięki temu odszukaliśmy twoje requesty w naszych logach. 
Na ten moment analizujemy ten problem, bo wygląda na to, że komunikat jest nieadekwatny do sytuacji. Jak będę miała konkretne informacje wrócę z odpowiedzią. 
Zastanawia mnie jeszcze dlaczego trace-id które przesyłasz są błędne. Na pewno bierzesz je z odpowiedniego miejsca?

Z tego co jeszcze widzę w podanych danych, to przesyłasz przy metodzie POST "id": null, gdzie pole to nie powinno być w ogóle podawane. Dostajesz w odpowiedzi warning z taką informacją?

**Comment by jezewskiBNetrox** [comment]
@MartaNowaczyk 

>Zastanawia mnie jeszcze dlaczego trace-id które przesyłasz są błędne. Na pewno bierzesz je z odpowiedniego miejsca?

Sprawdziłem kod i okazuje się, że trace-id pochodziły z zapytania POST /sale/product-offers więc nie ze sprawdzenia statusu wystawienia, które wskazuje o tym, że oferta nieznaleziona. Mogło to wprowadzić w błąd, przepraszam. 
Jednak jestem pewien, że trace-id pochodzi ze środowiska produkcyjnego. Nie ma opcji, żeby coś modyfikowało trace-id w tym wypadku (biorę prosto z obiektu odpowiedzi odpowiedni nagłówek trace-id).

>Z tego co jeszcze widzę w podanych danych, to przesyłasz przy metodzie POST "id": null, gdzie pole to nie powinno być w ogóle podawane. Dostajesz w odpowiedzi warning z taką informacją?

Nigdy nie widziałem, żeby pojawiały się ostrzeżenia a jednak implementacja ma już trochę czasu. W logach też mam pusto. Co do samego nulla poprawiłem to i nie powinno to już być problemem.

Czekam w takim razie na efekty analizy.

**Comment by MartaNowaczyk** [comment]
Z naszej weryfikacji wynika, że to twoje działania powodują ten błąd:

1. 2024-09-17T11:19:57.374Z  tworzysz ofertę XYZ przez API, zwracamy ci też link do sprawdzenia wyniku operacji.
2. 2024-09-17T11:19:58.400Z usuwasz ofertę XYZ przez API.
3. Sprawdzasz stan oferty przez link z kroku pierwszego i otrzymujesz prawidłowy błąd, że takiej oferty nie ma.

**Comment by jezewskiBNetrox** [comment]
@MartaNowaczyk Jest to absolutnie możliwe. Nie pomyślałem o tym. Teoretycznie kod do czyszczenia szkiców nie powinien się uruchamiać w tych godzinach ale coś nie zadziałało do końca jak trzeba. Dziękuję za analizę. Problem będę naprawiał po swojej stronie. Jeśli problem się powtórzy, wznowię wątek ale na ten moment można zamknąć temat. 

Pozdrawiam serdecznie. :)
