### ISSUE TITLE
Zablokowane konto Sandbox

### ISSUE THREAD

**Issue by radoslawkozlowskiis** [allegro/allegro-api#9892]
Występuje problem:
 - [ x ] ze środowiskiem testowym / with the test environment

Dzień dobry,
po zalogowaniu na konto sandbox otrzymuję poniższy komunikat:

> Zablokowana sprzedaż
Sprzedaż na Twoim koncie jest obecnie zablokowana. Powodem mogą być nieopłacone rachunki lub inne naruszenia Regulaminu. Aby odblokować możliwość sprzedaży, ureguluj zaległe płatności lub skontaktuj się z nami.

Prosiłbym o odblokowanie konta.

Login: sanbox_innrosa2

Dziękuję! :)

**Comment by MartaNowaczyk** [comment]
Dzień dobry, odblokowałam twoje konto :)

**Comment by mdxkom** [comment]
Hej, mamy ten sam problem. Prośba o odblokowanie kont:
- XkomAss01
- XkomAss03

**Comment by MartaNowaczyk** [comment]
Hej @mdxkom, odblokowałam oba konta.

**Comment by kornels5** [comment]
Cześć, mam ten sam problem, prośba o odblokowanie konta: sandboxASCO_SI_2

**Comment by Lukasz-Zurek** [comment]
@kornels5 Odblokowałem Twoje konto.

**Comment by Aleksandrze** [comment]
Hej, mamy ten sam problem. 
Prośba o odblokowanie kont: mrooczek

**Comment by Lukasz-Zurek** [comment]
@Aleksandrze Konto odblokowane.

**Comment by Skwarek71830** [comment]
Hej, mam ten sam problem na koncie: testowe2137

**Comment by erte2704** [comment]
Cześć, poproszę o odblokowanie: test_tez

**Comment by PrzemyslawLukanowski** [comment]
@Skwarek71830 @erte2704 Usunąłem blokady na kontach.

**Comment by PrzemyslawLukanowski** [comment]
@kurekq Odblokowałem Twoje konto.

**Comment by PrzemyslawLukanowski** [comment]
@DanielLuka81 Gotowe, usunąłem blokadę.

**Comment by PrzemyslawLukanowski** [comment]
@Pietrox Dzień dobry, gotowe, usunąłem blokadę.
