### ISSUE TITLE
cannot get/post order invoice - order not found - [sandbox]

### ISSUE THREAD

**Issue by hoszke** [allegro/allegro-api#9895]
I have an order in sandbox:
80c75750-736a-11ef-8814-01f4267834b6
Order exists, I can download it via /order/checkout-forms

But when I try to POST or GET to invoices endpoint, I have got ORDER-NOT-FOUND error message.

https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms/80c75750-736a-11ef-8814-01f4267834b6/invoices

{"errors":[{"code":"ORDER-NOT-FOUND","message":"Order with id [80c75750-736a-11ef-8814-01f4267834b6] not found","details":null,"path":"/order/checkout-forms/80c75750-736a-11ef-8814-01f4267834b6/invoices","userMessage":"Order with id [80c75750-736a-11ef-8814-01f4267834b6] not found"}]}

**Comment by PrzemyslawLukanowski** [comment]
Hello, I've answered in the #4415 thread.
