### ISSUE TITLE
"Processing error" podczas sprawdzania statusu tworzenia wysyłki

### ISSUE THREAD

**Issue by jezewskiBNetrox** [allegro/allegro-api#9897]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,

mam problem z tworzeniem przesyłek pobraniowych poprzez stary zasób API (parcel management).

Przykład:
"/parcel-management/parcel-create-commands/9b014552-fb83-4820-9045-21e93e399c46"
Trace-id: 99d26cffe75410a8

Zwróciło status OK oraz błąd z treścią:
```
{"id":"9b014552-fb83-4820-9045-21e93e399c46","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","details":"","message":"Processing error","path":"/parcel-management/parcel-create-commands/9b014552-fb83-4820-9045-21e93e399c46","userMessage":"Problem z nadaniem przesy\u0142ki. Skontaktuj si\u0119 z nami. Pomo\u017Cemy jak najszybciej."}]}
```

Proszę o wskazanie, co jest problemem. Problem pojawił się w ostatnich dniach.

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, użytkownik w Elektronicznym Nadawcy nie posiada podpiętego urządu nadania, w którym musi nadać paczkę. W tej sytuacji musi się skontaktować z Pocztą Polską i odpowiednio to ustawić w ich narzędziu.

**Comment by jezewskiBNetrox** [comment]
@PrzemyslawLukanowski Dziękuję za informację. Zamykam temat. Pozdrawiam.

**Comment by jezewskiBNetrox** [comment]
@PrzemyslawLukanowski Prosiłbym o przekazanie drobnego feedbacku i ewentualne zaktualizowanie w tym wypadku komunikatów. Problem był niestandardowy - dla konta EN zmienił się dostępny urząd nadania, jednakże konfiguracja konta EN sama w sobie była prawidłowa. W danych umowy własnej na Allegro natomiast trzeba było ponownie ustawić urząd nadania oraz zmienić w integracji kod "pointId", który wskazywał na urząd nadania. 
Mam nadzieję, że to pomoże w identyfikowaniu przyszłych problemów z konfiguracją konta EN: Allegro czy też innym użytkownikom.

Pozdrawiam.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za komentarz, przekazuję go oczywiście do zespołu odpowiedzialnego za usługę Wysyłam z Allegro.
