### ISSUE TITLE
Zasób /sale/offers/{offerId} - błąd przy wykonywaniu zapytania do API

### ISSUE THREAD

**Issue by mateuszrusyn** [allegro/allegro-api#990]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Przy wykonywaniu zapytania do API: /sale/offers/{offerId} otrzymuję zwrotkę JSON o następującej treści:
`{"errors":
          [
             {
                "code":"ERROR",
                 "message":"An error has occurred",
                 "details":null,
                 "path":"/sale/offers/7718718363",
                 "userMessage":null
             }
         ]
}`

Do zapytania podawaliśmy otrzymany z Allegro API obiekt JSON przedmiotu, który jest prawidłowy. Kod był wykonywany w PHP przy użyciu cURL oraz GuzzleHTTP. W obu przypadkach (przy wykonywaniu zapytań za pomocą tych bibliotek w skrypcie PHP) otrzymuję powyższy response. Kod, którego używam:

```
 $curlFirst = curl_init('https://api.allegro.pl/sale/offers/7718718363');
                        $header = [
                                'Authorization: Bearer exampleBearer',
                                'Accept: application/vnd.allegro.public.v1+json',
                                'Content-Type: application/vnd.allegro.public.v1+json'
                        ];
                        curl_setopt($curlFirst, CURLOPT_RETURNTRANSFER, true);
                        curl_setopt($curlFirst, CURLOPT_HTTPHEADER, $header);
                        curl_setopt($curlFirst, CURLOPT_CUSTOMREQUEST, 'GET');
                        curl_setopt($curlFirst, CURLOPT_HEADER, true);
                        curl_setopt($curlFirst, CURLINFO_HEADER_OUT, true);
                        $curl_response_first = curl_exec($curlFirst);
                        curl_close($curlFirst);

                        $decodeFirst = json_decode($curl_response_first, true);
                        $data = $decodeFirst;
                        $curl = curl_init('https://api.allegro.pl/sale/offers/7718718363');
                        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
                        curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
                        curl_setopt($curl, CURLOPT_HTTPHEADER, $header);
                        curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'PUT');
                        curl_setopt($curl, CURLOPT_HEADER, true);
                        curl_setopt($curl, CURLINFO_HEADER_OUT, true);
                        $curl_response = curl_exec($curl);
                        curl_close($curl);
```

Problem nie występuje w przypadku wysyłania requesta bezpośrednio przez cURL w wersji CLI przy takim wykonaniu komendy (jest to ogólnie rzecz biorąc odwzorowanie powyższego kodu do wersji CLI):

`curl -H 'Content-Type: application/vnd.allegro.public.v1+json' -H "Accept: application/vnd.allegro.public.v1+json" -H "Authorization: Bearer exampleBearer" -X PUT -d '{"id":"7718718363","name":"PODNOŚNIK SZYBY BLIC OUTLET","category":{"id":"629"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"17448","valuesIds":[],"values":["1"],"rangeValue":null},{"id":"129591","valuesIds":["129591_1"],"values":[],"rangeValue":null},{"id":"214434","valuesIds":["214434_266986"],"values":[],"rangeValue":null},{"id":"215858","valuesIds":[],"values":["6060-00-95391801P"],"rangeValue":null},{"id":"215941","valuesIds":[],"values":["VW","3B1837461","BLIC","60600095391801P","6060-00-95391801P"],"rangeValue":null}],"ean":null,"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>PODNOŚNIK SZYBY BLIC OUTLET</h1><p><b>Produkty z sygnaturą w tytule OUTLET pochodzą ze zwrotów (ustawowy zwrot, rezygnacja z zakupu). Każda część została sprawdzona i nie nosi śladów użytkowania,oraz jest w oryginalnym opakowaniu. </b></p><p><b>Produkty są oryginalne i podlegają standardowej gwarancji producenta.</b></p>"}]},{"items":[{"type":"TEXT","content":"<h2>Parametry produktu:</h2><p><b>Producent:</b><b>BLIC</b></p><p><b>Indeks produktu:</b> <b>P11406520</b></p>"},{"type":"IMAGE","url":"https://c.allegroimg.com/original/019d79/c32fb8d941a2bf00d85cdec1e82c"}]},{"items":[{"type":"TEXT","content":"<h2>Numery katalogowe części:</h2><p><b>OE:</b> VW : 3B1837461</p><p><b>OEM:</b>  BLIC : 60600095391801P , 6060-00-95391801P</p>"}]},{"items":[{"type":"TEXT","content":"<h2>Występuje w pojazdach:</h2><p>Jeśli masz wątpliwości, czy dana część pasuje do Twojego samochodu, prosimy o kontakt za pomocą formularza kontaktowego z podaniem numeru VIN.</p>"}]}]},"compatibilityList":null,"images":[{"url":"https://c.allegroimg.com/original/019d79/c32fb8d941a2bf00d85cdec1e82c"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"101.16","currency":"PLN"},"startingPrice":null,"minimalPrice":null},"stock":{"available":1,"unit":"UNIT"},"publication":{"duration":null,"status":"ACTIVE","startingAt":null,"endingAt":null},"delivery":{"shippingRates":null,"handlingTime":"PT24H","additionalInfo":"","shipmentDate":null},"payments":{"invoice":"VAT"},"afterSalesServices":{"impliedWarranty":{"id":"ef8a2fd5-4fde-4298-989e-dff5c615a31a"},"returnPolicy":{"id":"1ee10218-bb14-49d0-9587-ceccac087588"},"warranty":{"id":"79efeb2c-0628-4921-a90e-36991d0307e2"}},"additionalServices":null,"sizeTable":null,"promotion":{"emphasized":false,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"WIELKOPOLSKIE","city":"Kościan","postCode":"64-000"},"external":null,"attachments":[],"contact":null,"validation":{"errors":[],"validatedAt":"2018-12-14T08:48:38.17Z"},"createdAt":"2018-12-10T11:15:14Z","updatedAt":"2018-12-14T08:48:38.592Z"}' https://api.allegro.pl/sale/offers/7718718363`

Do tej komendy został dodany obiekt JSON zwrócony przez API, w tym wypadku request wykonuje się poprawnie i API zwraca kod 200 i wykonuje poprawnie akcje. W przypadku wysyłania poprzez oprogramowanie Postman również akcja wykonuje się pomyślnie. Request dla odwzorowania przypadku w Postmanie: https://pastebin.com/LPqYhibT (do zaimportowania w oprogramowaniu Postman)

Kod był wykonywany na różnych wersjach PHP (od 5.6 do 7.2) oraz na różnych środowiskach, systemach operacyjnych oraz maszynach. Problem występuje wyłącznie przy użyciu cURL/GuzzleHTTP wykorzystanych w skryptach PHP.

**Comment by MartaNowaczyk** [comment]
Z tego co piszesz nie ma problemu po stronie allegro. Prowadzimy wsparcie dla języków w jakich dochodzi do ostatecznej komunikacji z naszymi serwerami.
Mam nadzieję, że znajdzie się tu ktoś kto ma integracje w PHP i ci pomoże.
