### ISSUE TITLE
test kampania Golden Deals_Black Weeks 2024

### ISSUE THREAD

**Issue by Vitalka13** [allegro/allegro-api#9904]

**Comment by Vitalka13** [comment]
Dzień dobry!
Chcielibyśmy przetestować kampanię Golden Deals_Black Weeks 2024 na sandboxie dla naszego konta Test_3PRozetka. W jaki sposób to można zrobić?

**Comment by Lukasz-Zurek** [comment]
Konsultuję to jeszcze. Wkrótce wrócę do Ciebie z informacją.

**Comment by Lukasz-Zurek** [comment]
@Vitalka13 Powinniście już mieć dostęp do wspomnianej kampanii.

**Comment by Vitalka13** [comment]
Zauważyłam, że wszystkie oferty w asortymencie na moim koncie Test_3PRozetka mają status zakończone i wymagane są poprawki. Ale kiedy próbuję edytować ofertę, to właśnie nie wiem. co dokładnie muszę zmienić, ponieważ w ofercie nie pokazuje żadnych błędów. Czy mogę prosić o akceptacje kilka ofert, aby można było przetestować na nich kampanię?
Na przykład tę oferty:

7775590632
7775702993
7773019481
7773020019

**Comment by Lukasz-Zurek** [comment]
@Vitalka13 Miałaś blokadę sprzedaży na tym testowym koncie, to też dlatego oferty zostały zakończone. Możesz teraz spróbować je ponownie wystawić/aktywować.

**Comment by Vitalka13** [comment]
Dzień dobry!
Znowu mam ten sam problem, wszystkie oferty są zakończone i wymagają poprawić błędy.

**Comment by Lukasz-Zurek** [comment]
@Vitalka13 Tak, masz blokadę. Zanim ją zdejmę, wyjaśnię te kwestie dodatkowo z odpowiednim zespołem. Wkrótce wrócę do Ciebie z informacją.

**Comment by Vitalka13** [comment]
Dzień dobry!
Czy udało się coś wyjaśnić?

**Comment by Lukasz-Zurek** [comment]
@Vitalka13 Tak, Twoje konto jest już odblokowane.
