### ISSUE TITLE
updatedAt has stopped updating/changing

### ISSUE THREAD

**Issue by DHSC1** [allegro/allegro-api#9905]
Hi,
For orders, the updatedAd status has stopped updating when I change the fulfillment status in the Allegro portal. We want to sync the current order status from Allegro and we call the orders using a filter on updatedAd.

For example: order on test env (sandbox): ae961a70-7416-11ef-9b6f-1328915f5349
I've changed fullfilment status, but updatedAd is same (old):
    },
    "updatedAt": "2024-09-16T10:31:19.936Z",
    "revision": "bd4d65cd"
}

Alternatively, how else can we filter/determine if the fulfillment status has changed on an order?

**Comment by DHSC1** [comment]
Additional question:

What order changes should trigger a change to updatedAt? In the documentation, I only see that it's possible to filter based on this status, but it doesn't specify that only specific actions change it. Therefore, I assume that all changes to an order should cause updatedAt to be updated.

**Comment by Lukasz-Zurek** [comment]
Fulfillment status does not have any influence on **"updatedAd"** field. There is no alternative field for which we would return a change to **"fulfillment.status"** with the time of that change. But each time **"fulfillment.status"** is changed, the content of the **"checkoutForm.revision"** field changes - this provides information that the order status has changed. You can read more about the field in [our guide](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#zmiana-statusu-realizacji-zamowienia).

The **"updatedAt"** field refers to the order status ("status" field). So when this status changes - the "updatedAt" is updated with a new date.
