### ISSUE TITLE
Płatność pobraniowa nie jest wspierana dla wybranej metody dostawy

### ISSUE THREAD

**Issue by mmartowicz** [allegro/allegro-api#9909]
Dzień dobry,

posiadamy integrację API naszego systemu kurierskiego z AllegroOne i trafiliśmy na przypadek u klienta, w którym przy próbie wygenerowania listu przewozowego dla przesyłki pobraniowej otrzymujemy błąd "Płatność pobraniowa nie jest wspierana dla wybranej metody dostawy". Klient twierdzi, że na koncie Allegro wszystko jest skonfigurowane poprawnie i z poziomu Allegro może wygenerować listy. Czy mógłbym prosić o informację co może być problemem?

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, poproszę o trace-id lub commandID związane z tym komunikatem błędu. Wtedy będę mógł dokładnie zweryfikować ten przypadek. Wstępnie możecie się upewnić, czy przy tworzeniu przesyłki na pewno wskazujecie poprawną usługę dostawy - z pobraniem. Wszystko wskazuje na to, że przekazywany jest tam inny identyfikator.

**Comment by SzymonPalich** [comment]
Ustaliliśmy, że prawdopodobnie została usługa dostawy, która nie wspiera COD - Allegro One Kurier - dostawa jutro.
Temat do zamknięcia.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za potwierdzenie.
