### ISSUE TITLE
Nie odświeżają się oferty

### ISSUE THREAD

**Issue by gg1112** [allegro/allegro-api#991]
Podczas pobierania listy ofert danej kategorii w REST API nie odświeżają się oferty, w kółko są te same oferty, mimo że na stronie allegro pojawiły się nowe, z czego to wynika?

**Comment by gg1112** [comment]
Od momentu jak zaloguję się do allegro i po raz pierwszy pobiorą oferty to później przy kolejnych pobieraniach są w kółko te same oferty.

**Comment by PawelTaberski** [comment]
Potrzebowalibyśmy więcej szczegółów. Podeślij nam proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) przykładowe cURl-e wraz z responsami i traceID i opisz jakie rozbieżności zauważyłeś. Zaznacz w zgłoszeniu, że dane są potrzebne do ticketa numer 991 na GitHub-ie.
