### ISSUE TITLE
Lista wniosków o zwrot prowizji - komunikat braku dostępu

### ISSUE THREAD

**Issue by zaczy** [allegro/allegro-api#9916]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ C] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: 

Na środowisku sandbox/produkcyjnym wywołuję metodę `/order/refund-claims`, np.

`https://api.allegro.pl.allegrosandbox.pl/order/refund-claims?status=REJECTED`

Content-type: application/vnd.allegro.public.v1+json

W odpowiedzi otrzymuję

```
{"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"No access to the specified resource.","metadata":{}}]}
```

Według [dokumentacji](https://developer.allegro.pl/documentation#operation/getRefundApplications) do operacji wymagane są oprawnienia `allegro:api:orders:read`, które token przekazywany w nagłówku posiada

Token zdekodowany przy pomocy http://jwt.io:

```
{
  "user_name": "107301590",
  "scope": [
    "allegro:api:orders:read",
    "allegro:api:fulfillment:read",
    "allegro:api:profile:write",
    "allegro:api:fulfillment:write",
    "allegro:api:sale:offers:write",
    "allegro:api:billing:read",
    "allegro:api:campaigns",
    "allegro:api:disputes",
    "allegro:api:bids",
    "allegro:api:shipments:write",
    "allegro:api:sale:offers:read",
    "allegro:api:orders:write",
    "allegro:api:ads",
    "allegro:api:payments:write",
    "allegro:api:sale:settings:write",
    "allegro:api:profile:read",
    "allegro:api:ratings",
    "allegro:api:sale:settings:read",
    "allegro:api:payments:read",
    "allegro:api:shipments:read",
    "allegro:api:messaging"
  ],
  "allegro_api": true,
  "iss": "https://allegro.pl.allegrosandbox.pl",
  "exp": 1726690157,
  "jti": "f026323b-3f37-45f9-b73b-35bb243455b2",
  "client_id": "a575d30ef2d34599b7dba6039757231a"
}
```

**Comment by MartaNowaczyk** [comment]
Podajesz niepoprawny Accept `application/vnd.allegro.private.v1+json`. Powinno być `application/vnd.allegro.public.v1+json`.

**Comment by MartaNowaczyk** [comment]
Sprawdź czy w ogóle go przekazujesz, bo możesz nie podawać w ogóle tego Accepta, a u nas widoczny jest jako nieprawidłowy.

**Comment by zaczy** [comment]
Tak - to jest to! Po dodaniu nagłówka Accept metoda zaczęła zwracać wyniki.

Co ciekawe, że inne metody GET w tej samej konfiguracji dotąd działały poprawnie.

Dzięki!
