### ISSUE TITLE
sandbox Warianty 

### ISSUE THREAD

**Issue by amper01** [allegro/allegro-api#992]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

curl -X GET \
  https://api.allegro.pl.allegrosandbox.pl/sale/categories \
  -H 'accept: application/vnd.allegro.public.v1+json' \
  -H 'authorization: Bearer ....

zwraca tablice kategorii w której 
 {
            "id": "5",
            "name": "Dom i Ogród",
            "parent": null,
            "leaf": false,
            "options": {
                "variantsByColorPatternAllowed": true,
                "advertisement": false,
                "advertisementPriceOptional": false
            }
        },

następnie wywołuję https://api.allegro.pl.allegrosandbox.pl/sale/categories/5/parameters
**zwraca pustą tablicę.** 

Natomiast korzystając z interfejsu 
https://allegro.pl.allegrosandbox.pl/offer/...
w opisie znaleźć można nr kategorii: 68631
zapytanie https://api.allegro.pl.allegrosandbox.pl/sale/categories/68631/parameters
zwraca pełną tabele parametrów w tym informacje o interesującej mnie kategorii:

{
 "id": "18062",
            "name": "Motyw",
            "type": "dictionary",
            "required": false,
            "unit": null,
            "options": {
                **"variantsAllowed": true,**
                "variantsEqual": false
            },
"dictionary": [
                {
                    "id": "18062_512",
                    "value": "Sport"
                },
                ],

następny request
curl -X PUT \
  https://api.allegro.pl.allegrosandbox.pl/sale/offer-variants/7a49f998-af85-4391-bf2b-57e9b6a97429 \
  -H 'accept: application/vnd.allegro.beta.v1+json' \
  -H 'authorization: Bearer ...
  -d '{"offers":[{"colorPattern":"Sport","id":"6206060334"},{"colorPattern":"Sport","id":"6206060333"},{"colorPattern":"Sport","id":"6206060332"}],"name":"fototapety","parameters":[{"id":"18062_512"},{"id":"color/pattern"}]}'

otrzymuję w odpowiedzi:
{
    "errors": [
        {
            "code": "VARIANT_ATTRIBUTE_NOT_ALLOWED_IN_CATEGORY",
            "message": "Łączenie ofert po parametrze 18062_512 jest zablokowane w kategorii 68631.",
            "details": null,
            "path": null,
            "userMessage": "Łączenie ofert po parametrze 18062_512 jest zablokowane w kategorii 68631."
        }
    ]
}

**Comment by PawelTaberski** [comment]
Możesz połączyć oferty po parametrze o id 18062, ale ty podajesz, że chcesz połączyć po 18062_512 a masz różne wartości w ofertach. Ponadto dlaczego podajesz "colorPattern? Sprawdź proszę nasz poradnik w jaki sposób łączyć oferty, zwłaszcza [przykład z pamięcią RAM](https://developer.allegro.pl/multi_variant_offers/#3) będzie dla Ciebie pomocny.

**Comment by amper01** [comment]
Dzięki - ruszyło dla  kategorii 18062 i różniących się w aukcjach wartościach parametru.
