### ISSUE TITLE
Błąd zakładania przesyłki Allegro Kurier DHL

### ISSUE THREAD

**Issue by Wojtu204** [allegro/allegro-api#9920]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry,
mamy problem z zakładaniem jednej paczki, na wysłane żądanie dostajemy odpowiedź:
{
    "commandId": "6cd0ba46-a7cf-422b-95cf-3ba1a5e72926",
    "status": "ERROR",
    "errors": [
        {
            "code": "CARRIER_ERROR",
            "message": "Error has occurred in the external carrier system: Błędy walidacji przesyłki: Wystąpił błąd podczas dodawania przesyłki. Spróbuj ponownie później.",
            "details": "",
            "path": "",
            "userMessage": "Wystąpił błąd w systemie zewnętrznego przewoźnika: Błędy walidacji przesyłki: Wystąpił błąd podczas dodawania przesyłki. Spróbuj ponownie później."
        }
    ],
    "shipmentId": null
}

Proszę o info, co jest powodem takiego zachowania - dla analogicznych przesyłek na usłudze a3b4db98-4a70-4542-84ee-c642604d9d8a błąd nie występuje.

**Comment by MartaNowaczyk** [comment]
DHL miał awarię. Kilka minut temu podobno rozwiązano problem. Spróbuj w takim razie ponownie.

**Comment by Wojtu204** [comment]
Niestety - próba z 13:31 zakończona błędem:
{
    "commandId": "b156212c-0413-4e44-b146-2dbc7c85ee25",
    "status": "ERROR",
    "errors": [
        {
            "code": "BAD_REQUEST",
            "message": "External carrier error",
            "details": "",
            "path": "",
            "userMessage": "Błąd zewnętrznego przewoźnika"
        }
    ],
    "shipmentId": null
}

**Comment by MartaNowaczyk** [comment]
To już inny przewoźnik. Zweryfikujemy w czym problem i wrócę z informacją.

**Comment by MartaNowaczyk** [comment]
Okazuje się, że problemy też miał DPD, ale ponoć wraca już do normy.

**Comment by Wojtu204** [comment]
Na ten moment zgłoszone błędy nie występują, dziękuję za weryfikację.
