### ISSUE TITLE
Błędny komunikat przy rejestracji konta

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#9923]
Przy próbie rejestracji konta na sandbox wyskoczył mi komunikat "coś poszło nie tak",
sprawdziłem w konsoli 
![image](https://github.com/user-attachments/assets/ca55b15d-472f-4763-b1b1-6e7f782dc13c)

I wychodzi na to że wyświetlacie błędny komunikat.
Sprawdziłem na produkcji i jest dokładnie ten sam problem.

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę adres e-mail, który podawałeś podczas rejestracji na sandboxie. Skonsultuję temat.

**Comment by mzawodzinski** [comment]
Sam mail nie ma znaczenia,
chodzi o to że jak system wykryje że mail jest podobny do hasła to wyświetla komunikat "spróbuj ponownie" chociaż widać że z serwera dostał informacje jaki był konkretnie błąd.
Więc ktoś może klikać co chwila "załóż konto" zamiast poprawić hasło.

Możesz podać np. 
mail jakismail1@gmail.com
hasło Jakismail1@gmail.com

**Comment by Lukasz-Zurek** [comment]
Dzięki za zgłoszenie. Przekazuję temat dalej.
