### ISSUE TITLE
[REST] puste odpowiedzi z task id ?

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#993]
Czy to normalne zachowanie że metody
/sale/offer-quantity-change-commands/{$commandId}/tasks
/sale/offer-publication-commands/{$commandId}/tasks

zwracają dziś puste dane ? 
tasks => ()

zlecenie wysłąne o 13:49

pozdrawiamy wwwfactory

**Comment by wwwfactory** [comment]
Widzę że taski "zchodzą" ale z dużym opóźnieniem. Nie mniej jednak czy normalne zachowanie to puste pole z informacją ?

**Comment by PawelTaberski** [comment]
Zgodnie z [naszą dokumentacją](https://developer.allegro.pl/my_offers/#3) powinieneś otrzymać response w stylu: 
`{
    "id": "aacfb40c-daca-4252-91ef-244d68d28123",
    "taskCount": {
            "total": 0,
            "success": 0,
            "failed": 0
    }
}`
Czy taką odpowiedź otrzymujesz czy inną?
