### ISSUE TITLE
Checkout Forms - parametr GTE

### ISSUE THREAD

**Issue by jurtomasz13** [allegro/allegro-api#9934]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

API URL - "https:/api.allegro.pl/order/checkout-forms?offset=0&limit=100&lineItems.boughtAt.gte=1970-01-01T00%3A00%3A00.000Z"

Problem: Przy parametrze "lineItems.boughtAt.gte" ustawionym na date "1970-01-01T00:00:00.000Z" powinno pobierać 100 najstarszych zamówień, aczkolwiek z jakiegoś powodu pobiera 100 najnowszych zamówień.

**Comment by Lukasz-Zurek** [comment]
@jurtomasz13 Przetestowałem zarówno na sandboxie, jak i na produkcji i filtrowanie działa prawidłowo. Prześlij proszę trace-id. Czy sytuacja się powtarza?

**Comment by Lukasz-Zurek** [comment]
@jurtomasz13 Dziękuję za trace-id. Zweryfikuję i wkrótce wrócę do Ciebie z informacją.

**Comment by Lukasz-Zurek** [comment]
@jurtomasz13 Przekazujesz offset=0, dlatego zwracamy Tobie najnowsze wyniki. Musisz użyć wyższej wartości, aby móc uzyskać starsze zamówienia, lub użyć zakresu czasowego "lineItems.boughtAt.gte" i "lineItems.boughtAt.lte". Więcej informacji o filtrach znajdziesz [tutaj](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#lista-zamowien).

**Comment by jurtomasz13** [comment]
Hmm, przekazuje offset 0 aczkolwiek przekazuje również "lineItems.boughtAt.gte" czyli 1 rekord powinien się zaczynać od następnego zamówienia, które jest najbliższe podanej daty, w moim przypadku była to data 1970-01-01 czyli powinien pobrać pierwsze 100 zamówień a pobrał 100 ostatnich zamówień. Czy mógłbym prosić aby podał mi pan parametry, które musiałbym przekazać aby otrzymać 100 najstarszych zamówień?
