### ISSUE TITLE
Czy methods webapi doSendPostBuyForm jest jeszcze w uzyciu?

### ISSUE THREAD

**Issue by krs2k** [allegro/allegro-api#994]
Aktualnie zwraca mi cos takiego:
{#4025
  +"postBuyForm": {#4026
    +"transactionId": 727924166
    +"transactionPackageIds": {#4024}
    +"transactionPayByLink": {#4023
      +"actionHttpMethod": "POST"
      +"actionUrl": "NP_PAYGW_URL_PAYMENT_NEW"
      +"actionData": {#4022
        +"item": array:17 [
          0 => {#4021
            +"actionKey": "pos_id"
            +"actionValue": "NP_PAYGW_POS_ID"
          }
          1 => {#3653
            +"actionKey": "pos_auth_key"
            +"actionValue": "NP_PAYGW_POS_AUTH_KEY"
          }
          2 => {#3656
            +"actionKey": "ts"
            +"actionValue": "1545073694"
          } 
...

**Comment by PawelTaberski** [comment]
Podeślij nam proszę pełnego requesta i responsa przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619), sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że informacje są potrzebne do zgłoszenia numer 994 na GitHub-ie.

**Comment by krs2k** [comment]
Ok, dzieki :)
