### ISSUE TITLE
Brak odblokowania sprzedaży po uregulowaniu płatności

### ISSUE THREAD

**Issue by d-golebiowski** [allegro/allegro-api#9940]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Mam problem z działaniem na środowisku testowym, gdyż sprzedaż została zablokowana i po uregulowaniu płatności nie została ona odblokowana.

![image](https://github.com/user-attachments/assets/dbee5b9e-a1d7-4f86-901d-fb605d7a1aff)

Uregulowanie płatności odbyło się **17 września 2024** i do dnia **20 września 2024** sprzedaż w dalszym ciągu nie została odblokowana.

email: esprzedaz.alert@gmail.com
Login: esprzedaz_com

Generalnie nie mam dostępu do wiadomości wysyłanych na email.

**Comment by PrzemyslawLukanowski** [comment]
Anulowałem blokadę, problem nie powinien już występować.

**Comment by d-golebiowski** [comment]
Dziękuję bardzo, potwierdzam, że działa.
