### ISSUE TITLE
Problem z Uwierzytelnieniem REST API ALlegro w WAPRO Aukcje

### ISSUE THREAD

**Issue by MOON-IN-THE-ROOM** [allegro/allegro-api#9941]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [X ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
![Screenshot_1](https://github.com/user-attachments/assets/992fe983-875b-48f9-abe3-ad9f1d7412d9)
Mam problem z uwierzytelnieniem aplikacji Wapro Aukcje w REST API Allegro. Pojawia się błąd numer 63af5f0c76060006 jak w załączonym screenie. Co robić?

**Comment by Lukasz-Zurek** [comment]
Z tego co widzę w logach wynika, że używany jest nieprawidłowy redirect_uri (powinien być zgodny z tym zarejestrowanym [tutaj](https://apps.developer.allegro.pl). 

Niemniej jednak zachęcam Cię tutaj do bezpośredniego kontaktu z supportem narzędzia.

**Comment by Lukasz-Zurek** [comment]
@MOON-IN-THE-ROOM Korzystasz z narzędzia zewnętrznego. Nie znam jego konfiguracji, więc najlepiej będzie jak napiszesz do supportu narzędzia. Redirect_uri to adres do przekierowania, na który wysyłamy kod potrzebny w toku autoryzacji. Właściciel aplikacji ustala ten adres podczas rejestracji aplikacji.

**Comment by MOON-IN-THE-ROOM** [comment]
OK, rozumiem, skontaktowałem się z suportem narzędzia z prośba o udostępnienie tego linku.

**Comment by MOON-IN-THE-ROOM** [comment]
Dziękuję za pomoc, sprawa zamknięta. Udało się autoryzować.

**Comment by MOON-IN-THE-ROOM** [comment]
Dziękuję za pomoc, sprawa zamknięta. Udało się autoryzować.
