### ISSUE TITLE
Sandbox subcategories

### ISSUE THREAD

**Issue by many-to-one** [allegro/allegro-api#9947]
Witam, 
zauważyłem, że brakuje subkategorii: 'Zdalnie sterowane' w Allegro -> Dziecko
 -> Zabawki:
![image](https://github.com/user-attachments/assets/be66d446-e611-4d91-bcc4-b1c1d1e5862a)

To tak ma być? Czy taka sytuacja występuje tylko na środowisku sandbox, czy na produkcji też?

**Comment by PrzemyslawLukanowski** [comment]
Witam, nie mogę tego potwierdzić - kategorię zwracamy zarówno na produkcji, jak i Sandboxie:

```
        {
            "id": "11841",
            "name": "Zdalnie sterowane",
            "parent": {
                "id": "11818"
            },
            "leaf": true,
            "options": {
                "variantsByColorPatternAllowed": true,
                "advertisement": false,
                "advertisementPriceOptional": false,
                "offersWithProductPublicationEnabled": true,
                "productCreationEnabled": true,
                "customParametersEnabled": true,
                "sellerCanRequirePurchaseComments": false
            }
        },
```

Widzę, że na załączonym obrazku brakuje więcej podkategorii, np. "Antystresowe" (259497), "Bujaki, skoczki" (19477), "Zabawki terapeutyczne" (319706). Spróbuj powtórzyć request `GET /sale/categories?parent.id=11818` i jeśli kategorii wciąż będzie brakować, prześlij nam przykładowe trace-id.

**Comment by many-to-one** [comment]
Już wiem gdzie jest problem. Podkategorii w moim przypadku zwraca zapytanie: offers/listing/?category.id=11818&limit=60
I na środowisku testowym po prostu nie było wystawiono (prawdopodobnie) żadnej oferty w podkategorii 'Zdalnie sterowane'. Teraz wystawiłem testową ofertę w tej podkategorii i mam ją w odpowiedzi. Więc teraz wszystko jasne. Dziękuję.
