### ISSUE TITLE
tokeny - invalid_token

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#995]
Dzień dobry,
ostatnio bardzo często w odpowiedzi z Allegro otrzymujemy "invalid_token". Czasami zwrócone jest tylko raz po czym wszystko działa dalej prawidłowo ale częściej należy utworzyć nowy token. Zdarzają się przypadki, że każdego dnia musimy generować nowy token. Z czego to wynika?

**Comment by TimothyKoval** [comment]
Prawdopodobnie odświeżasz token kilka razy "na raz". Odświeżenie tokena (lub jego wygenerowanie) powoduje natychmiastową blokadę starego. Zanim otrzymasz odpowiedź z nowym tokenem najprawdopodobniej w innym "wątku" odświeżasz token już nieaktualny.

**Comment by PawelTaberski** [comment]
Do weryfikacji problemu potrzebowalibyśmy więcej szczegółów. Czy pamiętasz aby przy odświeżaniu korzystać z najnowszego refresha, który otrzymałeś z ostatnim tokenem?
Jeśli tak, to do weryfikacji potrzebowalibyśmy pełnego cURL-a i responsa wraz z trace-id. Podeślij proszę te dane przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) i w zgłoszeniu zaznacz, że dane te są potrzebne do ticketa numer 995 na GitHub-ie.

**Comment by FromAnyHole** [comment]
@PawelTaberski - to coś z tej samej bajki...
Czy poniższa odpowiedź jest jedyną i "poprawną" dla konta użytkownika, które się "wyczepiło" z danej aplikacji REST ? Tak przy okazji, responsy re-autoryzacyjne nie niosą nagłówka [Trace-Id: xxxxxx].
========================================
HTTP/1.1 400 Bad Request
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Date: Tue, 18 Dec 2018 12:34:56 GMT
Content-Type: application/json;charset=UTF-8
X-Backend: auth_1028061_dc4_xxxxxxxxxxxxxxx
Vary: Accept-Encoding
Age: 0
X-Req-Counter: 1
Content-Security-Policy: block-all-mixed-content; report-uri https://allegroapi.io/seclog/csp;
X-Hit: HIT 0
X-Origin: s42xxx
X-Content-Type-Options: nosniff
grace: none
X-XSS-Protection: 1; report=https://allegro.pl/seclog/xss
Transfer-Encoding: chunked
Connection: close
X-Frame-Options: SAMEORIGIN

002bf
{"error":"invalid_grant","error_description":"Invalid refresh token: xxxxxxxxxxxxxxxxxxxxxxxxxxx ... CUT!

**Comment by FromAnyHole** [comment]
@PawelTaberski - czyli powyższy przykład, to typowa odpowiedź po "wycofaniu zgody" dla danej aplikacji - zarazem dla ostatniego (ważnego) token'a, jak i przy próbie re-autoryzacji ("error":"invalid_grant") ?

**Comment by PawelTaberski** [comment]
Tak, jak napisałem dostaniesz identyczną odpowiedź zarówno w przypadku odpięcia aplikacji jak i starego refresha.
