### ISSUE TITLE
Pobrana prowizja od sprzedaży

### ISSUE THREAD

**Issue by bherczyk** [allegro/allegro-api#996]
Witam,
czy jest możliwe pobranie rzeczywistej prowizji od sprzedaży poprzez API?
Chodzi mi o dane takie jakie są dostępne w Moje konto -> Rachunki -> Historia.
Poprzez API mogę obliczyć prowizję jaka będzie pobrana, a ja bym chciał uzyskać prowizję jaka była rzeczywiście pobrana.

**Comment by PawelTaberski** [comment]
Jeśli chodzi Tobie o opłaty i prowizje, to obecnie nie ma takich metod w REST API, za to są w Web API.
Jeśli chcesz:

- Pobrać bieżące saldo z konta skorzystaj z [doMyBilling](https://allegro.pl/webapi/documentation.php/show/id,109)
- Sprawdzić koszty związane z ofertą skorzystaj z [doMyBillingItem](https://allegro.pl/webapi/documentation.php/show/id,301)

**Comment by mjag8** [comment]
Czy w związku z ostatnimi zmianami udostępniacie jakiś sposób otrzymania rzeczywistych prowizji dla danej transakcji poprzez API?

**Comment by PawelTaberski** [comment]
Jeśli chcesz pobrać [historię operacji billingowych](https://allegro.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) skorzystaj z zasobu GET /billing/billing-entries. W odpowiedzi otrzymasz m.in. wysokość prowizji od danej sprzedaży.  Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/charges/#0).
