### ISSUE TITLE
Mail nadawcy jest w niepoprawnym formacie 

### ISSUE THREAD

**Issue by playzino** [allegro/allegro-api#9963]
Tworząc przesyłkę z użyciem

https://api.allegro.pl/shipment-management/shipments/create-commands

dostaję błąd walidacji
[code] => VALIDATION_ERROR
                    [message] => Incorrect format of Allegro email
                    [details] => Invalid value: allegro@xxx.pl
                    [path] => resolveHash.email
                    [userMessage] => Allegro mail jest w niepoprawnym formacie

jest to adres nadawcy  sender->email oraz reciver->mail

**Comment by Lukasz-Zurek** [comment]
W tym przypadku problem dotyczy **receiver.email**, ponieważ musi to być maskowany adres mailowy klienta, pobrany z zamówień.

**Comment by playzino** [comment]
Dzięki, pomyliłem reciver z pickup.
