### ISSUE TITLE
Walidacja adresu przekierowań - myślnik w hostname

### ISSUE THREAD

**Issue by robert-skarzycki** [allegro/allegro-api#997]
Występuje problem:
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Podczas próby dodania aplikacji na Allegro Sandbox otrzymuję błąd `Adres przekierowań powinny być poprawnymi adresami URL` - próbuję użyć tego typu urla:
```
https://dev.portal.a-dev/Somewhere
```
Wygląda na to, że walidacji nie przechodzi kawałek `a-dev`, bo taki adres - `https://dev.portal.local/Somewhere` przechodzi walidację.

Czy jest szansa, żeby walidację przechodził adres, który w tej części hostname zawiera myślnik? Taki mam setup środowisk testowych, że taki znak zawierają.

**Comment by FromAnyHole** [comment]
Hej, nie ma takiego host'a: [dev.portal.a-dev] !

**Comment by PawelTaberski** [comment]
@robert-skarzycki Obecnie wspieramy wszystkie oficjalne TLD, a także  .local i .localhost ,możesz również podać IP-ka z sieci wewnętrznej. Co do adresu jaki podałeś przekazałem Twoją sugestię, aby zezwolić również na takie adresy. Jeśli zdecydujemy się wdrożyć takie rozwiązanie to poinformujemy o tym.

**Comment by robert-skarzycki** [comment]
Takie mamy hostname'y lokalnie, ale faktycznie, nie jest to prawilny URL.
