### ISSUE TITLE
Sanbox - Problem with Sandbox Apps

### ISSUE THREAD

**Issue by skraloupak** [allegro/allegro-api#9975]
Hello,
From yesterday, i can not **update** or **create** new app on the Sandbox. Any changes are not made.
When I updated the app, nothing happened.

Update the app
![screenshot 324](https://github.com/user-attachments/assets/2b307d35-d1c5-4d39-aa50-ed7e464c4b86)

Create new app
![screenshot 325](https://github.com/user-attachments/assets/38e964fe-9539-441f-840f-174876400716)

Can you check, please?  
Sandbox user: feedyio

Thanks
Jan

**Comment by MartaNowaczyk** [comment]
We cannot reproduce such a problem. It is also ok with your account. Have you checked in another browser or in incognito mode?

**Comment by skraloupak** [comment]
Hy Marta,
thank you for your reply.

I've tried the incognito mod, but it's impossible to pass the Captcha. I've successfully completed the puzzle a few times, but it finally blocked me. Yesterday i had the same problem, and in the end I managed somehow, but maybe not perfectly and that's why nothing works on my sandbox.

Captcha on the production server works perfectly. I did not have any problem.

**Comment by MartaNowaczyk** [comment]
Try changing/recovering your password and logging in with this new one. If this does not help we will look at other possibilities.

**Comment by skraloupak** [comment]
Thank you, it helps.

But unfortunately, I still can not update the app, and I have the same problem (in incognito mode).
Maybe I could just change the redirect uri. Are you authorized to change it so I can test the application?

**Comment by skraloupak** [comment]
Hey, it's possible that this has been fixed? Everything works now.

Thank you for your help
