### ISSUE TITLE
Numery przesyłek wysłane po API widoczne w interfejsie Allegro

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#998]
:bulb: **Sugestia**

Mnie i wielu innym Sprzedawcom brakuje tej opcji.
Moim zdaniem ujednolica sposób zachowania platformy i eliminuje wątpliwości co do poprawności przesłanego numeru poprzez API.

**Comment by hrabjasz** [comment]
Podejrzewam że chodzi o REST API, na chwile obecną nie ma możliwości wysłania numeru przesyłki do Allegro za jego pomocą.

**Comment by PawelTaberski** [comment]
Jeśli chodzi o REST to tak jak napisał @hrabjasz obecnie nie ma możliwości taka metoda powinna pojawić się jeszcze w tym kwartale.
