### ISSUE TITLE
Zwroty Sandbox

### ISSUE THREAD

**Issue by many-to-one** [allegro/allegro-api#9988]
Chcę dokonać zwrotu zamówienia na koncie sandbox ale muszę podać dane konta do zwrotu środków (26-cyfrowy numer konta), co mam wpisać?
![image](https://github.com/user-attachments/assets/3fd5eb83-f5b8-4daf-9952-e38c680e455e)

**Comment by Lukasz-Zurek** [comment]
Wpisujesz fikcyjny numer konta. Możesz go wygenerować korzystając np. w generatorów dostępnych online.

**Comment by many-to-one** [comment]
Udało się , dzięki
