### ISSUE TITLE
Niezgodna ilość ofert w REST API i na stronie

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#999]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Na stronie mamy ok. 8k ofert: https://allegro.pl/uzytkownik/Quickson?order=d&offerTypeBuyNow=1
W API mamy ok. 4.7k ofert: GET /offers/listing?searchMode=REGULAR&limit=100&sort=%2bprice&fallback=false&sellingMode.format=BUY_NOW&option=0&seller.id=24768654&include=all&offset=0 HTTP/1.1

![image](https://user-images.githubusercontent.com/36500569/50286794-d2b59d80-0460-11e9-8760-c3618c6f4ad6.png)

**Comment by PawelTaberski** [comment]
Sprawdzamy to,rzeczywiście wygląda to dziwnie. Do przeglądania własnych ofert zalecam metodę GET na zasobie /sale/offers

**Comment by rtnet-pl** [comment]
Dzięki. Klient twierdzi, że problem dotyczy tylko tego konta (ma ich kilka).
Chętnie używalibyśmy /sale/offers ale zakres danch zwracanych przez tą metodę jest mniejszy (brakuje nam chyba popularności)

**Comment by PawelTaberski** [comment]
Rozumiem, tak jak pisałem sprawdzamy jak tylko dowiem się czegoś konkretnego dam znać.

**Comment by PawelTaberski** [comment]
@rtnet-pl Informacje liczbowe już powinny się zgadzać z tym co widać na froncie. Różnica wynikała z ofert wielowariantowych.

**Comment by rtnet-pl** [comment]
@PawelTaberski Dziękuję bardzo. Sprawdzimy po wakacjach :) ps. Wesołych świąt

**Comment by PawelTaberski** [comment]
@rtnet-pl  Również zdrowych i spokojnych :-)

**Comment by mpysz** [comment]
Witam, u mnie ten sam problem. Wywołując GET https://api.allegro.pl/offers/listing?seller.id=43162901 otrzymuję 2801 ofert, a powinno być 3686 i tak też jest wyszukując przez stronę Allegro.

**Comment by PawelTaberski** [comment]
@mpysz Z tego co widzę liczba ofert zgadza się z tą widoczną na froncie (https://allegro.pl/uzytkownik/SmA-Lancerto?order=m) rozbieżność tak jak pisałem wcześniej wynika z ofert wielowariantowych.

**Comment by mpysz** [comment]
Nie jest to dla mnie zrozumiałe, ale skorzystałem z GET /sale/offers, żeby pobrać oferty i tutaj jest ok - liczba ofert się zgadza.

**Comment by PawelTaberski** [comment]
@mpysz  Tak, bo w /sale/offers masz widoczne wszystkie swoje oferty, a w zasobie /offers/listing są widoczne na froncie i niektóre z nich wchodzą w skład jednej oferty wielowariantowej, dlatego liczba może się różnić. Jednakże zwróć uwagę że już w sekcji filters znajdziesz całkowitą liczbę ofert.
