### ISSUE TITLE
Błąd przy zakładaniu konta sandbox

### ISSUE THREAD

**Issue by DWparts** [allegro/allegro-api#9994]
Mam problem z zakładaniem konta na sandboxie Allegro. 

Z tego co zrozumiałem, aby korzystać z sandboxa, najpierw muszę utworzyć konto oraz przejść weryfikację. Kiedy próbuję założyć konto, napotykam taki błąd:
![error](https://github.com/user-attachments/assets/d4bea923-4bc9-459a-baa8-16260b022ec9)

**Comment by DWparts** [comment]
Udało się utworzyć konto. 
Proszę o aktywacje: it@dwparts.eu

**Comment by MaciejFrackowiak** [comment]
Jak widzę jest to konto zwykłe - aktywujesz je automatycznie podczas płatności za dowolne zamówienie na Sandbox.

**Comment by DWparts** [comment]
Zrobiłem płatność na sandbox, oraz zrobiłęm dwuskładnikowe logowanie, ale nadal nie mam możliwości zarejestrowania apliakcji. 
Robię według tego poradnika: https://developer.allegro.pl/tutorials/pierwsze-kroki-MRwYEoOq0im#utworz-aplikacje
![screen](https://github.com/user-attachments/assets/11a00a43-d914-44d2-9338-1e144792d1c7)

**Comment by MaciejFrackowiak** [comment]
Spójrz proszę teraz.

**Comment by DWparts** [comment]
Nadal to samo

**Comment by MaciejFrackowiak** [comment]
W międzyczasie skonwertowałeś konto na firmowe, co wymagało weryfikacja konta firmowego. Przed momentem je aktywowałem, i jak sam piszesz już wszystko winno być OK.
