### ISSUE TITLE
Błąd 403 przy próbie pobrania reguł cenowych

### ISSUE THREAD

**Issue by ravnet1999** [allegro/allegro-api#9996]
Dzień dobry,
Próbuję pobrać reguły cenowe z adresu https://api.allegro.pl/sale/price-automation/rules, ale dostaję błąd 403. Z jakiego powodu może się tak dziać? Czy muszę gdzieś na swoim koncie włączyć obsługę tego? Dodaję nagłówek Bearer z tokenem, token jest na pewno ważny, bo dla adresu shipment-management/delivery-services normalnie pobieram informację o metodach wysyłki, zmiana adresu powoduje błąd. Może w ustawieniach aplikacji REST API potrzebuję mieć włączone jakieś uprawnienia? Podejrzewałam, że może te poniżej, ale dodanie ich i przelogowanie przez API nie pomogło. Proszę o pomoc.

Zarządzanie ofertami

    allegro:api:sale:offers:read
    Odczyt danych o ofertach
    allegro:api:sale:offers:write
    Tworzenie, edycja, łączenie i zamykanie ofert

Ustawienia sprzedaży

    allegro:api:sale:settings:read
    Odczyt ustawień sprzedaży
    allegro:api:sale:settings:write
    Zarządzanie ustawieniami sprzedaży

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id wywołania, dla którego otrzymałeś błąd 403.

**Comment by ravnet1999** [comment]
trace-id: 1331618794f77a2d

**Comment by ravnet1999** [comment]
Spróbuję jeszcze raz, aczkolwiek zrobiłam to.

**Comment by ravnet1999** [comment]
Ok, dziękuję, token wcześniej się tylko odświeżył pewnie, a już miałam kiedyś taką sytuację, nowy jest potrzebny w ogóle w takiej sytuacji.
