### ISSUE TITLE
nowe metody /shipment-management

### ISSUE THREAD

**Issue by mmfreq** [allegro/allegro-api#9997]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

metoda GET
https://api.allegro.pl/shipment-management/delivery-services

{"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"No access to the specified resource.","metadata":{}}]}

medoda GET
/parcel-management/delivery-services
działa prawidłowo

nadawałem ponownie umprawnienia, na koncie widać że aplkacja ma dostęp do nowego zasobu, a niestety nie wpuszcza.

**Comment by MaciejFrackowiak** [comment]
Wygląda, że Twój token nie posiada scope "allegro:api:shipments:write" - sama zmiana ustawień w zakresie uprawnień aplikacji to za mało. Musisz przejść ponownie autoryzację, by użytkownik potwierdził nowy zakres uprawnień aplikacji.

**Comment by mmfreq** [comment]
Tak, robiłem to juz kilka razy jako użytkownik i nadal jest ten bład.

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma to żadnego wpływu na autoryzację aplikacji.

**Comment by mmfreq** [comment]
Przy innym koncie klienckim jest to samo.

**Comment by MaciejFrackowiak** [comment]
Niestety, z mojej perspektywy mogę tylko raz jeszcze powtórzyć - taka sytuacja ma miejsce, gdy token nie posiada właściwych scope. Tylko ponowna autoryzacja zapewni uwzględnienie nowych uprawnień w samym tokenie.

**Comment by mmfreq** [comment]
CLIENT ID
cb642a80-a3b4-4e6d-bc80-efb461354d1d

**Comment by mmfreq** [comment]
no i działa, brakowało accept, dziekuje za pomoc.
